### PR TITLE
install_prereqs.sh user local pip install

### PR DESCRIPTION
**Pull request by ahundt**
This will help prevent lots of permissions, version, and security trouble. :-)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7608)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot add to whitelist

Sorry @ahundt, #3537 strikes again.

**Comment by jwnimmer-tri** [comment]
+@jamiesnape and +@soonho-tri for feature and platform review, please.  (We'll test on `-unprovisioned` after review happens, perhaps.)

**Comment by jamiesnape** [comment]
> This will help prevent lots of permissions, version, and security trouble. :-)

Permissions and security trouble?

**Comment by ahundt** [comment]
well, permissions trouble at least. I don't have permission to install in /usr/local/lib on some machines. see https://github.com/pypa/pip/issues/1668

**Comment by jamiesnape** [comment]
How do you install the rest of Homebrew?

**Comment by ahundt** [comment]
Apologies, I misstated that since it doesn't exactly apply to the macOS install. I don't have access to that directory when I use my university server farm with linuxbrew, which installs to the `~/.linuxbrew` directory by default. 

In this particular case, I'm on macOS. For some reason or another I often see permissions get screwed up in `/usr/local/lib/python2.7/site-packages/` both on local macOS installs and on local linux installs. I've found that using `pip install --user` all lets me uniformly install on all OSes without encountering permissions issues. Here is the full error output from just before I added the patch in this PR, just in case you find that informative:

```
athundt@Andrews-2013-MacBook-Pro-3|~/src/drake on master
± ./setup/mac/install_prereqs.sh
Already up-to-date.
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/formula.rb:2367:in `fails_with'

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:207:in `fails_with'

==> Tapping dreal-deps/coinor
Cloning into '/usr/local/Homebrew/Library/Taps/dreal-deps/homebrew-coinor'...
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 9), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), done.
Tapped 12 formulae (54 files, 63.3KB)
Warning: bazel 0.8.1 is already installed
Warning: boost 1.65.1 is already installed
Warning: cmake 3.10.0 is already installed
Warning: doxygen 1.8.13_1 is already installed
Warning: glew 2.1.0 is already installed
Warning: glib 2.54.2 is already installed
Warning: graphviz 2.40.1 is already installed
Warning: homebrew/science/ipopt 3.12.8_1 is already installed, it's just not linked.
You can use `brew link ipopt` to link this version.
Warning: libyaml 0.1.7 is already installed
Warning: lz4 1.8.0 is already installed
Warning: numpy 1.13.3 is already installed
Warning: pkg-config 0.29.2 is already installed
Warning: protobuf 3.5.0.1 is already installed
Warning: python 2.7.14 is already installed
Warning: scipy 1.0.0 is already installed, it's just not linked.
You can use `brew link scipy` to link this version.
Warning: tinyxml 2.6.2 is already installed
Warning: tinyxml2 6.0.0 is already installed
Warning: yaml-cpp 0.5.3 is already installed
==> Downloading https://homebrew.bintray.com/bottles/bash-completion-1.3_3.high_sierra.bottle.tar.
######################################################################## 100.0%
==> Pouring bash-completion-1.3_3.high_sierra.bottle.tar.gz
==> Caveats
Add the following line to your ~/.bash_profile:
  [ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/bash-completion/1.3_3: 189 files, 608.2KB
==> Downloading https://homebrew.bintray.com/bottles/clang-format-2017-11-14.high_sierra.bottle.ta
######################################################################## 100.0%
==> Pouring clang-format-2017-11-14.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/clang-format/2017-11-14: 12 files, 5.3MB
==> Downloading https://homebrew.bintray.com/bottles/diffstat-1.61.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring diffstat-1.61.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/diffstat/1.61: 8 files, 63.1KB
==> Installing clp from dreal-deps/coinor
==> Installing dependencies for dreal-deps/coinor/clp: coin_data_sample, coin_data_netlib, coinutils, osi
==> Installing dreal-deps/coinor/clp dependency: coin_data_sample
==> Downloading https://dl.bintray.com/dreal/homebrew-coinor/coin_data_sample-1.2.10.high_sierra.b
######################################################################## 100.0%
==> Pouring coin_data_sample-1.2.10.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/coin_data_sample/1.2.10: 44 files, 1.5MB
==> Installing dreal-deps/coinor/clp dependency: coin_data_netlib
==> Downloading https://dl.bintray.com/dreal/homebrew-coinor/coin_data_netlib-1.2.6.high_sierra.bo
######################################################################## 100.0%
==> Pouring coin_data_netlib-1.2.6.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/coin_data_netlib/1.2.6: 94 files, 4.7MB
==> Installing dreal-deps/coinor/clp dependency: coinutils
==> Downloading https://dl.bintray.com/dreal/homebrew-coinor/coinutils-2.10.14.high_sierra.bottle.
######################################################################## 100.0%
==> Pouring coinutils-2.10.14.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/coinutils/2.10.14: 73 files, 1.6MB
==> Installing dreal-deps/coinor/clp dependency: osi
==> Downloading https://dl.bintray.com/dreal/homebrew-coinor/osi-0.107.5.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring osi-0.107.5.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/osi/0.107.5: 33 files, 1.2MB
==> Installing dreal-deps/coinor/clp
==> Downloading https://dl.bintray.com/dreal/homebrew-coinor/clp-1.16.11.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring clp-1.16.11.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/clp/1.16.11: 66 files, 2.7MB
==> Downloading https://homebrew.bintray.com/bottles/nlopt-2.4.2_2.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring nlopt-2.4.2_2.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/nlopt/2.4.2_2: 23 files, 1.5MB
==> Downloading https://homebrew.bintray.com/bottles/patchutils-0.3.4.high_sierra.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring patchutils-0.3.4.high_sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/patchutils/0.3.4: 36 files, 289.4KB
==> Installing vtk@8.0 from robotlocomotion/director
==> Installing dependencies for robotlocomotion/director/vtk@8.0: jsoncpp, libharu
==> Installing robotlocomotion/director/vtk@8.0 dependency: jsoncpp
==> Downloading https://homebrew.bintray.com/bottles/jsoncpp-1.8.3.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring jsoncpp-1.8.3.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/jsoncpp/1.8.3: 23 files, 627.1KB
==> Installing robotlocomotion/director/vtk@8.0 dependency: libharu
==> Downloading https://homebrew.bintray.com/bottles/libharu-2.3.0.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libharu-2.3.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libharu/2.3.0: 40 files, 1.7MB
==> Installing robotlocomotion/director/vtk@8.0
==> Downloading https://drake-homebrew.csail.mit.edu/bottles/vtk@8.0-8.0.1.high_sierra.bottle.tar.
######################################################################## 100.0%
==> Pouring vtk@8.0-8.0.1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/vtk@8.0/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/vtk@8.0/lib
    CPPFLAGS: -I/usr/local/opt/vtk@8.0/include


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/vtk@8.0/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/vtk@8.0.pth
==> Summary
🍺  /usr/local/Cellar/vtk@8.0/8.0.1: 3,343 files, 112.9MB
Collecting lxml
  Downloading lxml-4.1.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (8.7MB)
    100% |████████████████████████████████| 8.7MB 157kB/s
Collecting matplotlib
  Downloading matplotlib-2.1.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.2MB)
    100% |████████████████████████████████| 13.2MB 107kB/s
Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages
Collecting pygame
  Downloading pygame-1.9.3-cp27-cp27m-macosx_10_9_intel.whl (4.8MB)
    100% |████████████████████████████████| 4.8MB 300kB/s
Requirement already up-to-date: PyYAML in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: Sphinx in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: subprocess32 in /Users/athundt/Library/Python/2.7/lib/python/site-packages (from matplotlib)
Requirement already up-to-date: python-dateutil>=2.0 in /Users/athundt/Library/Python/2.7/lib/python/site-packages (from matplotlib)
Requirement already up-to-date: backports.functools-lru-cache in /Users/athundt/Library/Python/2.7/lib/python/site-packages (from matplotlib)
Requirement already up-to-date: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/athundt/Library/Python/2.7/lib/python/site-packages (from matplotlib)
Requirement already up-to-date: cycler>=0.10 in /usr/local/lib/python2.7/site-packages (from matplotlib)
Requirement already up-to-date: numpy>=1.7.1 in /usr/local/lib/python2.7/site-packages (from matplotlib)
Requirement already up-to-date: pytz in /Users/athundt/Library/Python/2.7/lib/python/site-packages (from matplotlib)
Requirement already up-to-date: six>=1.10 in /usr/local/lib/python2.7/site-packages (from matplotlib)
Requirement already up-to-date: Pygments>=2.0 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already up-to-date: babel!=2.0,>=1.3 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Collecting setuptools (from Sphinx)
  Downloading setuptools-38.2.4-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 2.4MB/s
Requirement already up-to-date: imagesize in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already up-to-date: Jinja2>=2.3 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already up-to-date: alabaster<0.8,>=0.7 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already up-to-date: snowballstemmer>=1.1 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already up-to-date: sphinxcontrib-websupport in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already up-to-date: requests>=2.0.0 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already up-to-date: typing; python_version < "3.5" in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already up-to-date: docutils>=0.11 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already up-to-date: MarkupSafe>=0.23 in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.3->Sphinx)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests>=2.0.0->Sphinx)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests>=2.0.0->Sphinx)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests>=2.0.0->Sphinx)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests>=2.0.0->Sphinx)
Installing collected packages: lxml, matplotlib, pygame, setuptools
  Found existing installation: matplotlib 2.0.2
    Uninstalling matplotlib-2.0.2:
      Successfully uninstalled matplotlib-2.0.2
  Rolling back uninstall of matplotlib
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/mpl_toolkits/gtktools.py'
-> [2]
```
In this particular case I can fix it with chmod, but I think `pip install --user` is a better solution.

**Comment by ahundt** [comment]
> Sorry @ahundt, #3537 strikes again. I added you to the bot whitelist, so it won't spam you in the future.

@jwnimmer-tri no worries, I didn't even notice. Sometimes I'm told I don't check my email often enough, and now I can cite quantifiable benefits. 👍

**Comment by soonho-tri** [comment]
FYI, `brew doctor` checks the permission of `/usr/local/lib/python2.7/site-packages` and gives you a warning something like the following if it detects a problem there.

```
Warning: /usr/local/lib/python2.7/site-packages isn't writable.
This can happen if you "sudo pip install" software that isn't managed
by Homebrew. If you install a formula with Python modules, the install
will fail during the link step.
```

I think it's safe for us to assume that a user has clean output from `brew doctor` which makes us less worry about the problem.

**Comment by soonho-tri** [comment]
At the same time, `--user` seems to be a safer option. I'd like to know if there is a downside of using it.

BTW, if we want to enable `--user`, I think we should enable it for Ubuntu's script as well.

**Comment by jwnimmer-tri** [comment]
(Ubuntu doesn't use pip, though; only `apt` and `dpkg`.)

**Comment by soonho-tri** [comment]
> (Ubuntu doesn't use pip, though; only apt and dpkg.)

:face_palm:

**Comment by jamiesnape** [comment]
My main reservation is that we have had so much trouble with Mac and Python lately and things are currently stable, so while I think this is a reasonable thing to do, it would prefer not to change anything unless we really have another problem.

**Comment by ahundt** [comment]
>>  (Ubuntu doesn't use pip, though; only apt and dpkg.)
>
> :face_palm:

This caused many problems for me in the past! I switched to using pip with ubuntu and found that to be much more stable. In particular if you use any package that's in pip and not in apt-get you're out of luck with the apt-get system. That includes almost anything you want to be up to date use in robotics/machine learning...

**Comment by jwnimmer-tri** [comment]
For the record -- on Ubuntu, Drake does use some pip packages -- look for `pypi_archive` entries in `WORKSPACE`.  The trick is that we just use them locally within Drake (within Bazel's sandbox), rather that installing them user- or system-wide.  This is a good blend of getting the newest and best, without any installation headaches, but remaining insensitive to (and not disrupting) the developers' other projects.

This PR, though, is about macOS, for which I think jamiesnape's response is on point.  In principle, `--user` is probably better, but the macOS ecosystem and CI is difficult and brittle enough that we're hesitant to change it without a major investment in testing and resources on hand to deal with the inevitable build breaks, bug reports, and fallout in general.

I guess @soonho-tri if you were interesting in taking this on as a project to verify and work through CI (including things like `drake-visualizer` testing, etc.), I would probably bless it as "Let the macOS developers decide what they want their toolchain to be".

**Comment by soonho-tri** [comment]
> I guess @soonho-tri if you were interesting in taking this on as a project to verify and work through CI (including things like drake-visualizer testing, etc.), I would probably bless it as "Let the macOS developers decide what they want their toolchain to be".

Well. I prefer to keep it as it is. I'd rather adding a call `brew doctor` and checking its exit code to warn users if the exit code is non-zero.

**Comment by jwnimmer-tri** [comment]
@soonho-tri (or @jamiesnape) if your disposition here is not to merge this PR but rather to do some `brew doctor` thing, could you open an issue about that and then close this PR?  Having a stalled PR in the list is a distraction.

**Comment by jamiesnape** [comment]
@soonho-tri I am kind of waiting for the numpy situation to stabilize, i.e., whether we will be on a release on or master or on a fork. I would say there is a strong possibility we should support `--user`, but not sure about rolling out `virtualenv` support for Mac, but not Linux. We can close this for now, regardless.

**Pull request closed without merging**
