### PR TITLE
Move into tools/lint our clang-format-includes 

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7245)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for documentation review, please.
+@soonho-tri for feature and platform review per rotation, please.

**Comment by soonho-tri** [comment]
:lgtm: (except `clion.rst` part)

---

Reviewed 12 of 13 files at r1.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7245#-:-KwGD9epnedQijH8Tv3L:b-upbmjg)*

**Comment by soonho-tri** [comment]
@jwnimmer-tri , do we need to re-trigger the CI for this PR?

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7245#-:-KwGDGvfoe-CHSRI5oFG:b-rjmksn)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7245#-:-KwLNkR2VmIvmNhoVo7w:bmxilld)*

**Pull request merged**
