### PR TITLE
Fixed a shadow error in double pendulum example.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6799)

### CODE REVIEW

**Comment by liangfok** [comment]
+@ericcousineau-tri for feature review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6799#-:-Kr6MlAzKiD-ydbWx5KL:bua8qfi)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thank you!

BTW, per Jeremy's comment on Slack, an acceptable hotfix alternative would be to rename `foo` to `foo_in` as well.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6799#-:-Kr6OF6e5xOhORMRFMSZ:b-wh85y9)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6799)*

**Comment by liangfok** [comment]
Thanks, I considered doing that but figured this was a cleaner approach.

+@ggould-tri for platform review please. Thanks.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6799#-:-Kr6ZUqA0YM6rxkP30FA:b-647rx0)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6799#-:-Kr7631pKLOc67NdYWIv:bnfp4nl)*

**Pull request merged**
