### PR TITLE
[py manipulation] Condense into a single module

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #11802.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18973)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @EricCousineau-TRI @ggould-tri @sammy-tri in case this affects you.

I'll assign to Grant for review on Monday.  Feel free to self-assign as reviewer prior to that in case you have any concerns.

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18973#-:-NQQXAPgDJ5DtlO2rSFU:bgf7pv7)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18973#-NQQX5586aLR0RJ_d1i8:-NQQX5586aLR0RJ_d1i9:bvcv0kf) (no related file):*
Working

Checking on Anzu-master-Drake-PR.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18973)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18973#-NQQX5586aLR0RJ_d1i8:-NQQiBPsAoBCAwJeMEsP:b-l28nif) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Checking on Anzu-master-Drake-PR.
</blockquote></details>

Passed.

___

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18973#-:-NQQtKJTA-lBzQtY7Syv:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/manipulation/kuka_iiwa.py` line 6 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18973#-NQQsIfG-W1j-OXcmDkT:-NQQsIfG-W1j-OXcmDkU:beoj6k8) ([raw file](https://github.com/RobotLocomotion/drake/blob/4eed7564b934a84a1f6bcbf5fefb7837d0c69249/bindings/pydrake/manipulation/kuka_iiwa.py#L6)):*
> ```Python
> this module can be imported from pydrake.manipulation directly.
> 
> This module will be deprecated at some point in the future.
> ```

minor:  Does "in the future" mean in a short-term follow-up PR?
If not, this is the sort of forward-looking statement that deserves an issue number.
(or... just deprecate it now and be done with it?)

The same applies to the other rollup files below.



_Code quote:_
```Python
in the future
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18973)* status: 1 unresolved discussion (waiting on @ggould-tri)

___
*[`bindings/pydrake/manipulation/kuka_iiwa.py` line 6 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18973#-NQQsIfG-W1j-OXcmDkT:-NQQu-ae5_AghOANe5hQ:bsipuxk) ([raw file](https://github.com/RobotLocomotion/drake/blob/4eed7564b934a84a1f6bcbf5fefb7837d0c69249/bindings/pydrake/manipulation/kuka_iiwa.py#L6)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Does "in the future" mean in a short-term follow-up PR?
If not, this is the sort of forward-looking statement that deserves an issue number.
(or... just deprecate it now and be done with it?)

The same applies to the other rollup files below.
</blockquote></details>

There is a TODO with a date in the BUILD file.  My hypothesis is that's sufficient.

```
# TODO(jwnimmer-tri) On 2023-06-01 add deprecation for these modules.
# See #18683 for an example of what to do.
```

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18973)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/manipulation/kuka_iiwa.py` line 6 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18973#-NQQsIfG-W1j-OXcmDkT:-NQQvHsv4reN8qIshlbl:b-jla0bi) ([raw file](https://github.com/RobotLocomotion/drake/blob/4eed7564b934a84a1f6bcbf5fefb7837d0c69249/bindings/pydrake/manipulation/kuka_iiwa.py#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is a TODO with a date in the BUILD file.  My hypothesis is that's sufficient.

```
# TODO(jwnimmer-tri) On 2023-06-01 add deprecation for these modules.
# See #18683 for an example of what to do.
```
</blockquote></details>

OK works for me.

**Pull request merged**
