### PR TITLE
[doc] Offically support macOS Ventura

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #18327

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19458)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for both reviews please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19458#-:-NW3p3P20Aa6gLqjd6OO:b-2gceyk)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @BetsyMcPhail and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews +(release notes: feature).

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19458#-:-NW45TipExDWY5_2Ypfx:b-94xvy9)* status: 1 unresolved discussion

___
*[`doc/_pages/installation.md` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19458#-NW44y_Z9Z2tiYGVPD47:-NW44y_Z9Z2tiYGVPD48:bjj3h22) ([raw file](https://github.com/RobotLocomotion/drake/blob/49070fe2d0553c91694d6f74aad1dc6500bb7631/doc/_pages/installation.md#L57)):*
> ```Markdown
> | Ubuntu 20.04 LTS (Focal Fossa)     | GCC 9                    | C++17 |
> | Ubuntu 22.04 LTS (Jammy Jellyfish) | GCC 11                   | C++20 |
> | macOS Monterey (12)                | Apple LLVM 14 (Xcode 14) | C++20 |
> ```

This also needs a row added for Ventura.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19458)* status: 1 unresolved discussion

___
*[`doc/_pages/installation.md` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19458#-NW44y_Z9Z2tiYGVPD47:-NW4741AB3tBF3eReqNl:b-m16fax) ([raw file](https://github.com/RobotLocomotion/drake/blob/49070fe2d0553c91694d6f74aad1dc6500bb7631/doc/_pages/installation.md#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This also needs a row added for Ventura.
</blockquote></details>

Nice catch, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19458)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
