### PR TITLE
Benchmark render engines with google benchmark and add documentation

### PR DESCRIPTION
**Pull request by tehbelinda**
- add google benchmark to the build
- add shadow configuration to Ospray params

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12440)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
At first glance, this seems like more of an inward-facing utility for developers, and not a demo for users to learn about Drake?  As such, it seems inappropriate for `//examples`.  I'd advise placing the program directly in `//geometry/render`, or alternatively something along the lines of `//geometry/benchmarking` if there are going to be tons of them.

**Comment by jwnimmer-tri** [comment]
I think we don't do enough of committing our tooling to master.  If someone makes a code change on the basis of suggestions from this tool, we want others to be able to replicate that result.  If we want to re-measure six months later, we shouldn't have to root around in personal branches to do that.

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI Adding performance regression testing to CI can be difficult, and documenting the tools to a level where a random person can reproduce your results can take time.  I wouldn't let the perfect be the enemy of the good.  If the code and documentation are sufficient for you and @tehbelinda to use this tool and and communicate about its results between yourselves, and if a platform reviewer feels like we can responsibly collectively maintain the program in the face of other evolving code, then I think it's good to have on master.  All else being equal, any code you are actively engaging with (whether benchmarking code or anything else) is _much_ better to have on master than in personal branches.

**Comment by tehbelinda** [comment]
per f2f discussions - I agree with committing tooling to master and not leaving stale personal branches around for later, so for more immediate usage, we're going to add documentation on choosing between render engines with the benchmarking results thus far

**Comment by tehbelinda** [comment]
+@seancurtis-tri for feature review please

**Comment by tehbelinda** [comment]
Yes please

**Comment by tehbelinda** [comment]
___
*[geometry/geometry_doxygen.h, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LvupcJl8W9DHVWGJOje:-LvvcHWGALK32Y7LXPKj:bbmtzut) ([raw file](https://github.com/robotlocomotion/drake/blob/e03576e1f041095f1f7425916a1ebce8f1cf2a5f/geometry/geometry_doxygen.h#L21)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW How would you define "feature"?  It seems to be a bit of a mash up between: 
  - portions of API supported
  - Lighting artifacts
  - Computation requirements (GPU vs CPU)
</blockquote></details>

Open to interpretation... something you can use that might not be critical? Let me know if you have other ideas on how to structure this

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/render_benchmark.cc, line 215 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12440#-Lw-UtLBDe6Q228ypSb3:-LwGI2dc8nD_a2iV-Vz-:b-2c282l) ([raw file](https://github.com/robotlocomotion/drake/blob/e03576e1f041095f1f7425916a1ebce8f1cf2a5f/geometry/benchmarking/render_benchmark.cc#L215)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It seems if you output the images, that gets included in the timing, yes?
</blockquote></details>

I don't think so, I just ran it with/without saving the images and the results were similar
https://github.com/google/benchmark#controlling-timers

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/render_benchmark.cc, line 216 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12440#-Lw-UyopAEkAar_IMS3f:-LwGIseD4hU3z4FU0tHC:b-kkwvp3) ([raw file](https://github.com/robotlocomotion/drake/blob/e03576e1f041095f1f7425916a1ebce8f1cf2a5f/geometry/benchmarking/render_benchmark.cc#L216)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Also, when you print images, it would be good to print out the full path of the image being written (I don't know how painful that'll be.)
</blockquote></details>

it's not painful but it does interrupt the command line output which is not pretty. Seeing as the path is something the user has to pass in anyway, they should know where it is, so I'm not sure this is worth it?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/proximity_doxygen.h, line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LwL0NcY4d8YDXCFYkhs:-LwL0NcY4d8YDXCFYkht:b9tjxa3) ([raw file](https://github.com/robotlocomotion/drake/blob/8be6879a3b78b066cd3b76ef1d51a29c6e0139c4/geometry/proximity/proximity_doxygen.h#L7)):*
> ```objc
> /** @addtogroup proximity_queries
> 
>  Proximity queries span a range of types, including:
> ```

I just put some basic stuff in here so it wouldn't be empty and I could link the Next topic chain down to Render Engine. I'm conscious of scope creep here but if there's anything you think I should add for now let me know

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_ospray.cc, line 98 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LwL58fp2bbZ08doLLro:-LwL58fq6i70RdCK_r7c:bquopuk) ([raw file](https://github.com/robotlocomotion/drake/blob/8be6879a3b78b066cd3b76ef1d51a29c6e0139c4/geometry/render/render_engine_ospray.cc#L98)):*
> ```cpp
>   if (params.background_color) {
>     const Vector3d& c = *params.background_color;
>     background_color_ = ColorD{c(0) / 255.0, c(1) / 255.0, c(2) / 255.0};
> ```

I realised that the params doc actually say this should be in the range 0-1 so I'm changing the benchmark to divide this instead

**Comment by tehbelinda** [comment]
___
*[geometry/geometry_doxygen.h, line 8 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-Ly6OnPb4qXJnzuAjC6V:-Ly6aFdX0fJ7GibCmvfD:bw5e3fp) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/geometry_doxygen.h#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd like a stub for this group that indicates it's under construction.
</blockquote></details>

just making sure, you're referring to the `proximity_queries` group, right? i.e. related to the comment in `proximity_doxygen.h`? geometry_roles already has docs

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_vtk.cc, line 391 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyA_TX73wTRZ7Odl6xi:-LyBEU8n0-y-6ywP_hsY:bhwj5og) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/render/render_engine_vtk.cc#L391)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Are these settings equivalent to us not having had the declaration in the first place? Or does this represent a different  resultant image?
</blockquote></details>

It does result in a different image. This gets set by default in the ospray one so I figured it should be consistent?

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/README.md, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBIApzApRm9gwUoJ-Y:-LyBf9ed-F5wGHwcJA4P:b-f3gj6l) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/benchmarking/README.md#L1)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm not sure about the purpose of this README.md and the relationship it has to the benchmark included in this PR and possible future benchmark executables. Maybe we should discuss it.
</blockquote></details>

Hmm I started this before the other doxygen docs were added, so I don't think it's as relevant anymore since most of this is covered there

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/render_benchmark.cc, line 108 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBPAhW-26J1P3WY5k5:-LyBj9HoCBYcb0OwyI_O:b-52cl69) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/benchmarking/render_benchmark.cc#L108)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I thought an empty string meant no images output.
</blockquote></details>

It does, but that's handled at the outer level. The image_path_name function itself still falls back to generating a file path with a temp dir if someone asks for it? It doesn't actually save the image

at the outer level:
```
  if (!FLAGS_save_image_path.empty()) {
    const std::string path_name = image_path_name("VtkColor", state, "png");
    SaveToPng(color_image_, path_name);
    saved_image_paths.insert(path_name);
  }
```

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/render_benchmark.cc, line 127 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBPgPO7Gtz6JAmeFOU:-LyBjx3_B1xMaW80IpvG:b-mlq14o) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/benchmarking/render_benchmark.cc#L127)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: 1 sphere is zero rows? 5 spheres is also zero rows? That also seems *really* screwy.
</blockquote></details>

1 sphere  = 1 row : (1 - 1) / 4 + 1 = 0 / 4 + 1 = 0 + 1 = 1
5 spheres = 2 rows : (5 - 1) / 4 + 1 = 4 / 4 + 1 = 1 + 1  = 2
would another set of parentheses before the + 1 at the end help?

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/README.md, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBIApzApRm9gwUoJ-Y:-LyBlT8K65t_Iy88RsnM:b-tl1j9b) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/benchmarking/README.md#L1)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

Hmm I started this before the other doxygen docs were added, so I don't think it's as relevant anymore since most of this is covered there
</blockquote></details>

oh I just got to your comment below, I like the idea, I'll move the doxygen into here and link it

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine.h, line 297 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBTVFH54APv-pSyZHa:-LyBmLBp7ohK_zzLe5gr:b-e6az5e) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd626b2349601c7a8e48e7a2750ac8e34deac4a/geometry/render/render_engine.h#L297)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Are you sure about the world frame?
</blockquote></details>

Yes - am I missing something? is there a concept of the render engine's scene frame that's different?

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_vtk.cc, line 391 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyA_TX73wTRZ7Odl6xi:-LyBmjT9ACZeUbqFEFY8:b-dgatxf) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/render/render_engine_vtk.cc#L391)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Would you say the change in color image is noticeable?
</blockquote></details>

yeah the sphere does look different

.png)

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/render_benchmark.cc, line 47 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBMpnP1Tpu4Gq011HZ:-LyBii0cAL-FBsl2fp0B:b-bt82mw) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/benchmarking/render_benchmark.cc#L47)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Several things:

1. This really shouldn't be a global variable.
2. The comment would probably be better as: "The paths to the saved images."
3. Is it a *set* for a reason? Do you plan on redundantly adding the same path multiple times? If not, the fact that this is going to do string comparisons to insert strings seems a bit redundant. (Although, when iterating through the result, at least they'll be sorted....is that the purpose?) If so, worth noting.
</blockquote></details>

1. I tried to put it in the RenderEngineBenchmark class but google benchmark actually instantiates it multiple times. I'll make another class for it then
2. Ok
3. Yes, since google benchmark does it multiple times. I'll add a comment about that. No particular reason for the sorting

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_doxygen.h, line 84 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBG5tN35a95OJwiwmf:-LyBvdZr8Dl0dNnvvQes:b-q9548s) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/render/render_doxygen.h#L84)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I think that all of the benchmark discussion should go a single file (e.g., the README.md) file and this should merely reference it.

I'd advocate that it should link to the eventual url to the file in github.
</blockquote></details>

actually, does it have to stay as a README.md? I'm having some trouble linking, potentially because they're in different directories, and I'm tempted to just make it all doxygen and use groups or something else instead

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/render_benchmark.cc, line 47 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBMpnP1Tpu4Gq011HZ:-LyC37Bn9hz9XC6YMaTp:b5odrmo) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/benchmarking/render_benchmark.cc#L47)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

1. I tried to put it in the RenderEngineBenchmark class but google benchmark actually instantiates it multiple times. I'll make another class for it then
2. Ok
3. Yes, since google benchmark does it multiple times. I'll add a comment about that. No particular reason for the sorting
</blockquote></details>

1. Hm although this might get messy since the BENCHMARK_XX macros are at the global scope

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/render_benchmark.cc, line 66 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBORxe0aa001GU3HBq:-LyC3iVFCsN9kgzvSong:b-3qo1y5) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/benchmarking/render_benchmark.cc#L66)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

What's the point of the `using` declaration (here and on `TearDown`)?
</blockquote></details>

it's needed to avoid the build warning-error from overriding just one of the overloaded virtual functions for SetUp

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/render_benchmark.cc, line 108 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBPAhW-26J1P3WY5k5:-Ly_HCwuCx7Qzhy23o5f:b9b6tao) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/benchmarking/render_benchmark.cc#L108)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

What I'm confused about is that in this file, you only invoke it if a save path has been defined. So, it doesn't make sense to have the function support a calling mode that is counter to intent.
</blockquote></details>

ok, how about making it throw a logic error then if it's empty?

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_vtk.cc, line 391 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyA_TX73wTRZ7Odl6xi:-Ly_MdXOACjJK2tSluQa:bffp9v2) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/render/render_engine_vtk.cc#L391)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This is a bit worrying. In principle, I'd rather not make it so that a default-instantiated renderer produces a different image without some significant documentation.

Obviously you've copied this from OSpray and revealed that the lights don't match. So, there is a defect in that the lights don't match. Quite unfortunate.

I'd suggest changing the definition in `RenderEngineVtk` so that it reflects the original, default lighting (the fun is figuring out what those parameters should be) and then change OSPray to match it (with the idea that there are probably fewer users of ospray than vtk so less disruption).

Thoughts?
</blockquote></details>

Hmm...lemme try a few different parameters and see how this goes

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_vtk.cc, line 391 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyA_TX73wTRZ7Odl6xi:-Ly_PjIW5nvZG4w2xWKb:b-t2kqjw) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/render/render_engine_vtk.cc#L391)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Good luck
</blockquote></details>

Ok so, it seems like the difference is caused only by the line`light_->SetLightTypeToCameraLight();` And it's only revealing itself in the benchmark because I change the light position and the frame of reference wasn't the camera frame before. 

So since it was never possible to offset the light transform, I'd imagine no user would run into issues with this unmatch anyway?

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine.h, line 297 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyBTVFH54APv-pSyZHa:-Ly_RYEa0_6FxmwjT9-B:b-kjhbqn) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd626b2349601c7a8e48e7a2750ac8e34deac4a/geometry/render/render_engine.h#L297)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You have to careful there. Is `C` really the camera frame? Is the camera centered in C? Because it's not centered in the frame the light position gets defined. Crazy, right?
</blockquote></details>

Gosh okay, so in the comment I can say, it's relative to the camera position, and then say we use the notation defining a frame C assuming C is centered with the camera as its origin?

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_vtk.cc, line 391 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyA_TX73wTRZ7Odl6xi:-Ly_ykJI6gpXb0LfKIUG:b-mga93o) ([raw file](https://github.com/robotlocomotion/drake/blob/36d4f838e97445ec6c2357e9ec7c125e104f37b0/geometry/render/render_engine_vtk.cc#L391)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Per f2f. I hadn't communicated my purpose well. What we want to confirm is that the addition of an explicitly declared light to `RenderEngineVtk` doesn't change the output (for a fixed scene) from when we *weren't* explicitly declaring it.
</blockquote></details>

Yep, confirmed

**Comment by tehbelinda** [comment]
I try not to get my hopes up :P

**Comment by tehbelinda** [comment]
it's almost tomorrow work wise, soo +@ggould-tri for platform review please

**Comment by jwnimmer-tri** [comment]
FYI Needs macOS builds triggered.

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/render_benchmark.cc, line 147 at r10](https://reviewable.io/reviews/robotlocomotion/drake/12440#-LyjSy0GD7dOTCYdPZJx:-LykQs3GE9rukztW_dVO:byt7qik) ([raw file](https://github.com/robotlocomotion/drake/blob/a51f07db1a991f0ed5914d59257a9ab09614385b/geometry/benchmarking/render_benchmark.cc#L147)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Why is this class living in the root namespace at global scope?
</blockquote></details>

it's under the drake::geometry::render namespace so that it can be see as a friend class from `RenderEngine`, which is also in the drake::geometry::render namespace

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12440#-Lyjh1vu1R0x2hOWFBL2:-Lyk_ahe-nuidrD6a04c:b-iph1re) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Triggered....this could be interesting.
</blockquote></details>

Oops I guess it reset when I updated the PR, re-triggered

---

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12440#-Lyjh1vu1R0x2hOWFBL2:-LylCKUo8dR-AJCjoJVI:b-4p83ae) (no related file):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

Oops I guess it reset when I updated the PR, re-triggered
</blockquote></details>

Ok I'm not sure why they didn't link in but they seem to have passed:
https://drake-jenkins.csail.mit.edu/job/mac-mojave-clang-bazel-experimental-release/48/
https://drake-jenkins.csail.mit.edu/job/mac-catalina-clang-bazel-experimental-everything-release/17/

---

**Comment by tehbelinda** [comment]
+(status: commits are properly curated)

**Pull request merged**
