### PR TITLE
[workspace] Upgrade bazelisk to latest release v1.22.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21972)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-packaging please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot linux-noble-unprovisioned-gcc-cmake-experimental-packaging please
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-cmake-experimental-packaging please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
Oops, typo on the Ubuntu site.  We'll re-run those:

@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-packaging please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot linux-noble-unprovisioned-gcc-cmake-experimental-packaging please

The existing macOS builds are in progress and probably won't need to be re-run:

* https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release/41/consoleFull
* https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-unprovisioned-clang-cmake-experimental-packaging/13/consoleFull
* https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-unprovisioned-clang-wheel-experimental-release/86/consoleFull

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.  Low priority.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21972#-:-O83Tgaq1wv5quUOzeWT:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
