### PR TITLE
Add parsing of string options to SNOPT.

### PR DESCRIPTION
**Pull request by mposa**
Quick addition, adding use of SNOPT's `snset` to set string values. I wasn't sure if a 7.4 workaround was also needed, like some of the other methods, and so did not add that.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13397)

### CODE REVIEW

**Comment by mposa** [comment]
As far as i could tell, "print file" is the only string option that Drake currently supports. This is to allow the others

**Comment by jwnimmer-tri** [comment]
Adding a unit test would be a good way to demonstrate (to @hongkai-dai and future maintainers) the specific effect that this change achieves.  It sounds like there must be string options available other than just `Print file`.

**Comment by mposa** [comment]
Updated with @jwnimmer-tri 's more readable comparison.

While a unit test would be great, I'm not sure what one would look like. Conceivably, we could test by checking the option. Unfortunately, I tried to do this (while debugging options), and was not able to figure out SNOPT's poorly documented API. There is a method `sngetc` that seems appropriate, but I couldn't get it to do anything.

**Comment by jwnimmer-tri** [comment]
Two options for unit testing (or perhaps more appropriately called acceptance testing):

(1) Set a string option with a bogus name, and confirm that an error occurs.  Set a valid name and confirm no error occurs.  Given the structure of the implementation, this is sufficient to show the options are making their way into `snset`.

(2) Set a string option that changes program output, either numerically or in the details of the print file.  Confirm that the difference in output is congruent with whether or not the option was set (i.e., run it twice, once with and once without the option set).

**Pull request merged**
