### PR TITLE
Adds missing sparse UpdateCoefficient binding to LinearEqualityConstaint

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22151)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22151#-:-OBRMBQ-6Z_5PQxdC9bE:bltox9h)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@sammy-tri for platform review please, thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22151#-:-OBRNgEB-iFa18nK1WB9:bptxe99)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @AlexandreAmice)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22151#-:-OBS2VEd1Hs2KbmvSlRl:bnfp4nl)* status: missing label for release notes (waiting on @AlexandreAmice)

**Review by sammy-tri — COMMENTED** [review]
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22151#-:-OBS2rNx7mx-dilrCGP2:b-chsgxs)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),hongkai-dai

**Pull request merged**
