### PR TITLE
Add specific suppressions for runtime/references to common

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #2274.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3896)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Add DNM (unless done carefully).  Be sure this has been rebased to latest master under Jenkins before merging.

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for all review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3896#-:-KUvaBOtSwokYaCNrVA8:b-7ewwmf)*

**Comment by jwnimmer-tri** [comment]
-@david-german-tri +@sammy-tri for all review, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3896#-:-KV0Hz_5389GNX2933Rq:b-dzmit1)*

**Comment by david-german-tri** [comment]
:lgtm: -@sammy-tri +@david-german-tri

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3896#-:-KV0IZj9g4v7Lvs4DI_X:b-b6mstx)*

**Comment by jwnimmer-tri** [comment]
Rebased to master, to removing DNM.

**Pull request merged**
