### PR TITLE
Add AddNonnegativePolynomialConstraint function.

### PR DESCRIPTION
**Pull request by hongkai-dai**
MathematicalProgram can add different types of nonnegative polynomial constraint with the same API.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289#-:-MsVx6R59M4k6NlrIXJK:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @RussTedrake)

___
*[solvers/mathematical_program.h, line 2578 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16289#-MsWO9qb5MieT05CLujR:-MsWO9qb5MieT05CLujS:b-aqr7d3) ([raw file](https://github.com/robotlocomotion/drake/blob/b028e9a69f12b5aa41e76d7f8f12d35a3e7ea8f1/solvers/mathematical_program.h#L2578)):*
> ```objc
>    * @param monomial_basis The monomial basis m for this polynomial, such that p
>    * = mᵀQm
>    * @param type The type of the non-negative polynomial (sos, sdsos, dsos).
> ```

it took me a few minutes looking at the code to see why you were introducing more API.  please make the relationship between this and AddSosConstraint more explicit (with a note both here and in the AddSosConstraint doc.).
___
*[solvers/mathematical_program.h, line 2583 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16289#-MsWOZnADSmUjhoWe8NG:-MsWOZnADSmUjhoWe8NH:b-dv93c8) ([raw file](https://github.com/robotlocomotion/drake/blob/b028e9a69f12b5aa41e76d7f8f12d35a3e7ea8f1/solvers/mathematical_program.h#L2583)):*
> ```objc
>    * indeterminates if necessary.
>    */
>   MatrixXDecisionVariable AddNonnegativePolynomialConstraint(
> ```

Two questions / minor concerns about the title.
(1) it's verbose; is the "polynomial" implied by the argument?  (we didn't use AddSosPolynomialConstraint above?)
(2) it's imprecise.  we are not adding an exact, nonnegativity constraint; only a relaxed version of that.

proposal: don't add these new methods, just add the new (optional) type argument to `AddSosConstraint`.  dsos and sdsos are still sos.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[solvers/mathematical_program.h, line 2578 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16289#-MsWO9qb5MieT05CLujR:-MsX29bt6iCRjio5LgI9:b-r4ksug) ([raw file](https://github.com/robotlocomotion/drake/blob/b028e9a69f12b5aa41e76d7f8f12d35a3e7ea8f1/solvers/mathematical_program.h#L2578)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it took me a few minutes looking at the code to see why you were introducing more API.  please make the relationship between this and AddSosConstraint more explicit (with a note both here and in the AddSosConstraint doc.).
</blockquote></details>

Done. Good call, I removed the new API
___
*[solvers/mathematical_program.h, line 2583 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16289#-MsWOZnADSmUjhoWe8NG:-MsX2Byd4ZQp0Nh5johs:b-51xeuh) ([raw file](https://github.com/robotlocomotion/drake/blob/b028e9a69f12b5aa41e76d7f8f12d35a3e7ea8f1/solvers/mathematical_program.h#L2583)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Two questions / minor concerns about the title.
(1) it's verbose; is the "polynomial" implied by the argument?  (we didn't use AddSosPolynomialConstraint above?)
(2) it's imprecise.  we are not adding an exact, nonnegativity constraint; only a relaxed version of that.

proposal: don't add these new methods, just add the new (optional) type argument to `AddSosConstraint`.  dsos and sdsos are still sos.
</blockquote></details>

Done. Good call, I added the optional type argument to `AddSosConstraint`.

**Review by RussTedrake — COMMENTED** [review]
:lgtm: (with a few nits)
+@sherm1 for platform review, please.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289#-:-Ms_NbUj0DdSRkJNkE3A:b-jbl0ak)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @hongkai-dai and @sherm1)

___
*[solvers/mathematical_program.h, line 2524 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16289#-Ms_Mc_d86HAaIthZw1t:-Ms_Mc_e9DnnD-iFD9FR:bvgv23y) ([raw file](https://github.com/robotlocomotion/drake/blob/2670fc0bb2120f72fc701ec7171df48ac2345f1a/solvers/mathematical_program.h#L2524)):*
> ```objc
>    * semidefinite.
>    * @param type The type of the polynomial. @default is kSos, but the user can
>    * also use kSdsos and kDsos.
> ```

nit: perhaps add citation so that people know that sdsos and dsos are?
___
*[solvers/mathematical_program.h, line 2547 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16289#-Ms_Mu160bO5OF53wfH-:-Ms_Mu160bO5OF53wfH0:b-fxp9aq) ([raw file](https://github.com/robotlocomotion/drake/blob/2670fc0bb2120f72fc701ec7171df48ac2345f1a/solvers/mathematical_program.h#L2547)):*
> ```objc
>    */
>   std::pair<MatrixXDecisionVariable, VectorX<symbolic::Monomial>>
>   AddSosConstraint(const symbolic::Polynomial& p,
> ```

nit: mention `type` in the docstring, or refer to the other variant of the method?  (here and below)
___
*[solvers/mathematical_program.cc, line 1368 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16289#-Ms_NWiv1dtuFNZPaoUx:-Ms_NWiv1dtuFNZPaoUy:b7vpxyd) ([raw file](https://github.com/robotlocomotion/drake/blob/2670fc0bb2120f72fc701ec7171df48ac2345f1a/solvers/mathematical_program.cc#L1368)):*
> ```cpp
> MathematicalProgram::AddSosConstraint(
>     const symbolic::Expression& e,
>     MathematicalProgram::NonnegativePolynomial type) {
> ```

nit: can you add some minimal c++ test coverage for these new arguments?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @RussTedrake and @sherm1)

___
*[solvers/mathematical_program.h, line 2524 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16289#-Ms_Mc_d86HAaIthZw1t:-Ms_sCKdA8WRpTYAtXQk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2670fc0bb2120f72fc701ec7171df48ac2345f1a/solvers/mathematical_program.h#L2524)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: perhaps add citation so that people know that sdsos and dsos are?
</blockquote></details>

Done.
___
*[solvers/mathematical_program.cc, line 1368 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16289#-Ms_NWiv1dtuFNZPaoUx:-Msa1vxZ3gPwCyUGJSs0:b-j12ynj) ([raw file](https://github.com/robotlocomotion/drake/blob/2670fc0bb2120f72fc701ec7171df48ac2345f1a/solvers/mathematical_program.cc#L1368)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: can you add some minimal c++ test coverage for these new arguments?
</blockquote></details>

Done. The functionality of sdsos and dsos are tested in scaled_diagonally_dominant_matrix_test.cc and diagonally_dominant_matrix_test.cc, so in this PR I only add a minimal c++ test to make sure that mathematical program adds some constraints with the new argument.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few minor comments.

> Reviewed 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289#-:-MsaL19c8GIiCl0Mf2fi:bkry7ar)* status: 3 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 2556 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16289#-MsaJ8n3Dfr7czwfhQnv:-MsaJ8n3Dfr7czwfhQnw:b-i2ikx0) ([raw file](https://github.com/robotlocomotion/drake/blob/f7251156cca039abdce5b59c493e6d89e233ec19/solvers/mathematical_program.h#L2556)):*
> ```objc
>    *
>    *  - The coefficients matrix Q, which is positive semidefinite.
>    *  - The monomial basis m.
> ```

minor: These two lines are out of place. Move them to just after "bindings expressing:" above (just before the new @param text).
___
*[solvers/mathematical_program.h, line 2569 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16289#-MsaK4EF8YazvEpnocXI:-MsaK4EF8YazvEpnocXJ:bg97n1w) ([raw file](https://github.com/robotlocomotion/drake/blob/f7251156cca039abdce5b59c493e6d89e233ec19/solvers/mathematical_program.h#L2569)):*
> ```objc
>    * program. It returns the coefficients matrix Q, which is positive
>    * semidefinite.
>    * @param type Refer to NonnegativePolynomial class documentation.
> ```

minor: not clear why the @param description here is different than the longer descriptions for the previous overloads. Maybe consider using this short description for all these methods and move the longer text and reference to the doc for NonnegativePolynomial to avoid having to duplicate it?
___
*[solvers/mathematical_program.h, line 2584 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16289#-MsaJvvR-yY8eMAYLdHz:-MsaJvvR-yY8eMAYLdI-:bkucaop) ([raw file](https://github.com/robotlocomotion/drake/blob/f7251156cca039abdce5b59c493e6d89e233ec19/solvers/mathematical_program.h#L2584)):*
> ```objc
>    *
>    *  - The coefficients matrix Q, which is positive semidefinite.
>    *  - The monomial basis m.
> ```

minor: these two lines need to follow "... pair expressing:" above.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 2569 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16289#-MsaK4EF8YazvEpnocXI:-MsaLtHF2QAG-DRy3daj:b-11e2vs) ([raw file](https://github.com/robotlocomotion/drake/blob/f7251156cca039abdce5b59c493e6d89e233ec19/solvers/mathematical_program.h#L2569)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: not clear why the @param description here is different than the longer descriptions for the previous overloads. Maybe consider using this short description for all these methods and move the longer text and reference to the doc for NonnegativePolynomial to avoid having to duplicate it?
</blockquote></details>

Done. NonnegativePolynomial already has the documentation on the reference. I modified the documentation here to refer to NonnegativePolynomial

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16289#-:-MsaYThU1ps_FiLQKwU_:b-c7f1bi)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Comment by RussTedrake** [comment]
@hongkai-dai -- I see now that we have https://drake.mit.edu/doxygen_cxx/classdrake_1_1solvers_1_1_mathematical_program.html#a903fd7b5970fb835030958fe57d8cd6e .  That seems inconsistent with the discussion we had here.  Might we want to change THOSE to be AddSosPolynomial?

**Comment by hongkai-dai** [comment]
@RussTedrake yes I was indeed working on a PR to replace NewNonnegativePolynomial with NewSosPolynomial. Will send the PR today.

**Pull request merged**
