### PR TITLE
Clarify documentation for FindResource and friends

### LINKED ISSUE #7678: DRAKE_RESOURCE_ROOT vs drake-distro rename
In #7575 it is possible that we broke `DRAKE_RESOURCE_ROOT`, or expectations related to it.

(More details are already on slack; I will fill more detail here as I learn.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #7678.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7680)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@fbudin69500 are you available / interested to feature-review this documentation change?

**Comment by jwnimmer-tri** [comment]
-@fbudin69500 +@EricCousineau-TRI for all review, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with some minor BTWs.

Can I ask if this happens to address any of #7624?

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/find_resource.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-L2L20SL5dWBxTOrkjYW:-L2L20SL5dWBxTOrkjYX:b-hmfszm) ([raw file](https://github.com/robotlocomotion/drake/blob/765fccc1e6df515eb13942d3fbe2c027519fd0ff/common/find_resource.h#L87)):*
> ```objc
> /// Attempts to locate a Drake resource named by the given @p resource_path.
> /// The @p resource_path refers to the relative path within the Drake source
> /// repository, pre-pended with `drake/`.  For example, to find the source
> ```

BTW minor grammar nit `prepended` vs`pre-pended`?

---

*[common/find_resource.h, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-L2L28XgA4yyrqMf4QgB:-L2L28XhxbsYkGOn0JKF:b-5ff5ih) ([raw file](https://github.com/robotlocomotion/drake/blob/765fccc1e6df515eb13942d3fbe2c027519fd0ff/common/find_resource.h#L88)):*
> ```objc
> /// The @p resource_path refers to the relative path within the Drake source
> /// repository, pre-pended with `drake/`.  For example, to find the source
> /// file `examples/pendulum/Pendulum.urdf`, the @p resource_path would be
> ```

BTW minor formatting I though I had seen other PRs prefer the use of `` `resource_path` `` rather than `@p resource_path` for formatting parameters. Did I misunderstand that?

---

*[common/find_resource.h, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-L2L2llMGVhmxDj970a3:-L2L2llMGVhmxDj970a4:b-y9duov) ([raw file](https://github.com/robotlocomotion/drake/blob/765fccc1e6df515eb13942d3fbe2c027519fd0ff/common/find_resource.h#L112)):*
> ```objc
> ///
> /// When the environment variable is set, resources are sought in relation to
> /// it by appending the FindRssource() `resource_path` to the environment
> ```

BTW typo `Rssource` -> `Resource`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-:-L2L2wFkQVBGhmYZDXgp:b-pfybd3)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-:-L2L6w85RdE9WTtxWuH0:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
I don't know the cause of #7624, but I can't imagine a case where a misunderstanding these particular API docs would be part of the failure chain.  I don't think the python stuff relies on the environment variable at all.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/find_resource.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-L2L20SL5dWBxTOrkjYW:-L2L6xbVUaSVzk79FsWn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/765fccc1e6df515eb13942d3fbe2c027519fd0ff/common/find_resource.h#L87)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor grammar nit `prepended` vs`pre-pended`?
</blockquote></details>

Done.

---

*[common/find_resource.h, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-L2L28XgA4yyrqMf4QgB:-L2L73WZKxWm0tkQZzZk:brus0i1) ([raw file](https://github.com/robotlocomotion/drake/blob/765fccc1e6df515eb13942d3fbe2c027519fd0ff/common/find_resource.h#L88)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor formatting I though I had seen other PRs prefer the use of `` `resource_path` `` rather than `@p resource_path` for formatting parameters. Did I misunderstand that?
</blockquote></details>

OK Others may do it differently, but this way is allowed.

---

*[common/find_resource.h, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-L2L2llMGVhmxDj970a3:-L2L71b-ZlqCn2xf4u1x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/765fccc1e6df515eb13942d3fbe2c027519fd0ff/common/find_resource.h#L112)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW typo `Rssource` -> `Resource`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-:-L2L6RYrK7WB7s9sNo1b:barzl3t)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7680)*

**Comment by fbudin69500** [comment]
I'll look into #7624 . I can reproduce it on Linux but not on MacOS (where the command works successfully).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7680#-:-L2LF8ttL42NV9dD_uB2:b250y15)*

**Pull request merged**
