### PR TITLE
solvers: ensure IPOPT uses MUMPS as its linear solver

### LINKED ISSUE #14419: Issues with ipopt 3.13 from Homebrew on macOS
```
Exception of type: OPTION_INVALID in file "IpAlgBuilder.cpp" at line 268:
Exception message: Selected linear solver MA27 not available.
Tried to obtain MA27 from shared library "libhsl.dylib", but the following error occured:
dlopen(libhsl.dylib, 2): image not found
```

Temporary workaround was #14288.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #14419. CI update for Mac should be fine to happen post-merge.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14446)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@hongkai-dai for feature review.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14446#-:-MODQtW51a7CffdN6UIL:b-vtj4vo)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14446#-:-MODSuv32Amnk6g9NKcD:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai

**Pull request merged**
