### PR TITLE
Rotation constraint visualization

### PR DESCRIPTION
**Pull request by hongkai-dai**
Visualize the McCormick Envelope for the rotation constraint. I find it convenient for debugging, and also for future presentation.

I plot the intersection region (with the box) for 1, 2, 3 binary variables. The red lines are the boundary of the intersection regions, between the boxes and the sphere.

bin1_box
1 binary variable case

bin2_box
2 binary variables case

bin3_box
3 binary variables case

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5529)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@russtedrake for feature review please. `lcm_call_matlab_client` works great! 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-:-KfO8BFmkkqhoSWqxc2g:bidt697)*

**Comment by RussTedrake** [comment]
Those plots do look really useful (although it took me a moment to orient myself in them until I remembered that it is only visualizing the first orthant -- they look bigger than that given the perspective).

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/CMakeLists.txt, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-Kf_wqWe3XcV2_DmszsB:-Kf_wqWe3XcV2_DmszsC:b73wp2f) ([raw file](https://github.com/robotlocomotion/drake/blob/0afafd80dac33f7b3f1385116c548745ffa5e6cb/drake/solvers/CMakeLists.txt#L158)):*
> ```CMake
>           drakeLcm
>           drakeLCMTypes)
>   drake_install_headers(rotation_constraint_visualization.h)
> ```

rotation_constraint_visualization is only used by your test program (so far), and it seems like it is only likely to be used by that program, at least for now.  I propose moving rotation_constraint_visualization.h into the test directory, and NOT including it in the list of installs.  At least until there is another consumer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-:-Kf_xokIpfG9_UHj5-EX:b-y1a2ks)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/CMakeLists.txt, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-Kf_wqWe3XcV2_DmszsB:-Kfc48Pa_mQk8_ZfPt_V:bvo0fuy) ([raw file](https://github.com/robotlocomotion/drake/blob/0afafd80dac33f7b3f1385116c548745ffa5e6cb/drake/solvers/CMakeLists.txt#L158)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

rotation_constraint_visualization is only used by your test program (so far), and it seems like it is only likely to be used by that program, at least for now.  I propose moving rotation_constraint_visualization.h into the test directory, and NOT including it in the list of installs.  At least until there is another consumer?
</blockquote></details>

Done. I moved it to the test folder, and removed the installs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-:-KfdRPJoMNALCmFuaVHr:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review please

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-:-KfdUwrt9lk1EZFbRYgS:b-10xzum)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 9 files at r1, 2 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529)*

**Comment by soonho-tri** [comment]
nice work!

:lgtm: (aside one BTW).

---

Reviewed 5 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/test/rotation_constraint_visualization.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-KfgFqwAa82YlD44hUMK:-KfgFqwAa82YlD44hUML:boaehp8) ([raw file](https://github.com/robotlocomotion/drake/blob/270fb9d1d6c5177613cafa1087b6d193664da5b6/drake/solvers/test/rotation_constraint_visualization.h#L18)):*
> ```objc
>  * @param bmin The innermost corner of the box
>  * @param bmax The outermost corner of the box
>  * @param color The rgb color of the surface to be plotted. @default is [0.5, 0.2, 0.3]
> ```

BTW, this line is > 80.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-:-KfgL0tRboVYO9JcetRs:b4b683m)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/test/rotation_constraint_visualization.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-KfgFqwAa82YlD44hUMK:-KfgUxoUKoBt0QJhkT0X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/270fb9d1d6c5177613cafa1087b6d193664da5b6/drake/solvers/test/rotation_constraint_visualization.h#L18)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this line is > 80.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/CMakeLists.txt, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-KfgVO5s2-GtaHBDruwM:-KfgXYx5ZnfXOm3eO1a5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a51aa72a06f70470dce60fc96128251cb99fe62b/drake/solvers/test/CMakeLists.txt#L39)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, no need this anymore?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5529#-:-Kfgj-U0joEostkj96ry:b-l70wzf)*

**Pull request merged**
