### PR TITLE
[multibody] Rename spaceXYZ mobilizers to more closely match joint terminology

### PR DESCRIPTION
**Pull request by sherm1**
(This is a yak shave for adding RpyFloatingJoint per #14949)

Renames 
- SpaceXyzFloatingMobilizer -> RpyFloatingMobilizer 
- SpaceXyzMobilizer -> RpyBallMobilizer

Updates related names and comments.

This provides consistency internally, though the user-visible names for Joints (quaternion_floating, rpy_floating vs. ball_rpy) don't quite match. However, this PR deals only in internal changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@amcastro-tri for feature review, please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-:-Np1qJOq2YRiXOswFpV8:bkta03b)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
Thank you Sherm, this makes sense to me.
Probably a good idea to capture either in a TODO or an issue what the plan is with the now called `BallRpyJoint`, which we should probably now name `RpyBallJoint`.

:lgtm: 

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-:-NpLw_cY-Uohv_I2X0tR:b-kkhjd8)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/tree/ball_rpy_joint.h` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLW7p39xvOd7pGoPo-:-NpLW7p39xvOd7pGoPo0:bqjitgo) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/ball_rpy_joint.h#L27)):*
> ```objc
> /// @tparam_default_scalar
> template <typename T>
> class BallRpyJoint final : public Joint<T> {
> ```

would we like to name this `RpyBallJoint`? are you simply trying to avoid deprecation or this is not even in the plan?
___
*[`multibody/tree/rigid_body.h` line 292 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLvhuVE3vHubVVU8fk:-NpLvhuVE3vHubVVU8fl:b-xtgrnx) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/rigid_body.h#L292)):*
> ```objc
>   /// @note A floating body is not necessarily modeled with a quaternion
>   /// mobilizer, see has_quaternion_dofs(). Alternative options include a
>   /// roll-pitch-yaw (Rpy) parametrization of rotations, see
> ```

minor, I'd probably write `rpy` (preferred) or `RPY`
___
*[`multibody/tree/rpy_ball_mobilizer.h` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLtiuA4Iur2F_Uumdx:-NpLXPEcBaGzUCIvf19r:b5wiwz0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/rpy_ball_mobilizer.h#L22)):*
> and in fact we call it an "rpy_ball_joint" in Drake

Is this some nomenclature we'll use in the future? AFAIKT the term `rpy_ball_joint" only shows in this one line
___
*[`multibody/tree/rpy_ball_mobilizer.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLY7Sw5eXrLDCPrBMw:-NpLY7Sw5eXrLDCPrBMx:b-p5rqx) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/rpy_ball_mobilizer.h#L29)):*
> ```objc
> // roll-pitch-yaw angles (also known as space-fixed x-y-z Euler angles or
> // extrinsic angles). That is, the generalized coordinates q for this mobilizer
> // correspond to angles q=[θ₀ θ₁ θ₂], for a sequence of rotations about the Fx,
> ```

minor, I persnally like spaces around the `=` sign.

**Review by sherm1 — COMMENTED** [review]
Feature review comments resolved, with an open discussion about naming, PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-:-NpMA8Og3AaTkXlggwrG:bj5dtqu)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/tree/ball_rpy_joint.h` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLW7p39xvOd7pGoPo-:-NpM6awEEH_yGFt3mEGp:b-i6gk7x) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/ball_rpy_joint.h#L27)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

would we like to name this `RpyBallJoint`? are you simply trying to avoid deprecation or this is not even in the plan?
</blockquote></details>

Ideally we would name all the joints consistently. However, my feeling now is that it isn't really worth the pain to rename existing joints. Instead I went with making the new floating joint consistent with the old floating joint, and making the internal mobilizers consistent internally. If we add a quaternion version of Ball joint, we can call it BallQuaternionJoint or decide on renaming at that time. The current PR avoids public changes altogether, which is a plus.

The ideal names IMO would have been BallRpy, BallQuaternion, FloatingRpy, and FloatingQuaternion because then the joint variants would alphabetize together. We could move that way by renaming the existing floating joint to floating_quaternion_joint. But is this really going to solve any user problems? I'm guessing that people are able to find the joints they need. And the floating joints are most often added automatically under the covers without the user needing to name them.

WDYT?
___
*[`multibody/tree/rigid_body.h` line 292 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLvhuVE3vHubVVU8fk:-NpM93GG9jYiesHRc5s1:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/rigid_body.h#L292)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, I'd probably write `rpy` (preferred) or `RPY`
</blockquote></details>

Done
___
*[`multibody/tree/rpy_ball_mobilizer.h` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLtiuA4Iur2F_Uumdx:-NpM9ZzU6uvbnA1EQcNs:b3x9mdb) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/rpy_ball_mobilizer.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> and in fact we call it an "rpy_ball_joint" in Drake

Is this some nomenclature we'll use in the future? AFAIKT the term `rpy_ball_joint" only shows in this one line
</blockquote></details>

Done, thanks -- that was a typo.
___
*[`multibody/tree/rpy_ball_mobilizer.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLY7Sw5eXrLDCPrBMw:-NpM9q5GEqS7ccJWMhyS:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/rpy_ball_mobilizer.h#L29)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, I persnally like spaces around the `=` sign.
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
+@jwnimmer-tri for platform review per rotation, please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-:-NpMARjn9k7YITSXj1nM:bu01odg)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 15 of 17 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-:-NpMH15I9ZULTlmlOVoU:b-vtj4vo)* status: 8 unresolved discussions

___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMDsCI2WYhxGaC5jtC:-NpMDsCI2WYhxGaC5jtD:b-cptqtu) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/plant/test/compliant_contact_manager_test.cc#L29)):*
> ```cpp
> #include "drake/multibody/tree/prismatic_joint.h"
> #include "drake/multibody/tree/revolute_joint.h"
> #include "drake/multibody/tree/rpy_ball_mobilizer.h"
> ```

BTW The lack of any other changes in this file probably indicates that this is a dead include, and could be removed instead of renamed.
___
*[`multibody/rational/rational_forward_kinematics.cc` line 11 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMDxVnBdIaedlcyM7w:-NpMDxVnBdIaedlcyM7x:b-cptqtu) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/rational/rational_forward_kinematics.cc#L11)):*
> ```cpp
> #include "drake/multibody/tree/prismatic_mobilizer.h"
> #include "drake/multibody/tree/revolute_mobilizer.h"
> #include "drake/multibody/tree/rpy_ball_mobilizer.h"
> ```

BTW The lack of any other changes in this file probably indicates that this is a dead include, and could be removed instead of renamed.
___
*[`multibody/tree/rpy_floating_mobilizer.h` line 78 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMGhKT0pVUnn8Ecccp:-NpMGhKT0pVUnn8Ecccq:b-vnisn) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.h#L78)):*
> ```objc
> 
>   // Overloads to define the suffix names for the position and velocity
>   // elements.
> ```

This is bug fix which is important to mention in the commit message.

I guess "release notes: none" is still good though, since there is no way and end-user could ever be using this class -- it's an internal class with no public joint for it yet.
___
*[`multibody/tree/rpy_floating_mobilizer.cc` line 18 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMIKcU2xA3HVoBYCM5:-NpMIKcU2xA3HVoBYCM6:b-338sfh) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.cc#L18)):*
> ```cpp
> 
> template <typename T>
> std::string RpyFloatingMobilizer<T>::position_suffix(
> ```

Missing unit tests for both of these new functions.

See `QuaternionFloatingJointTest.NameSuffix` for an example of what we need.
___
*[`multibody/tree/rpy_floating_mobilizer.cc` line 20 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMIfWp4D_kiRXbs3qO:-NpMIfWq8p9nhJIgM0vW:b-9i6m77) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.cc#L20)):*
> ```cpp
> std::string RpyFloatingMobilizer<T>::position_suffix(
>     int position_index_in_mobilizer) const {
>   // Note: The order of variables here is documented in get_quaternion().
> ```

nit The phrase "documented in get_quaternion" does not seem relevant here.
___
*[`multibody/tree/rpy_floating_mobilizer.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMIwhW1vSt6pnbdt9L:-NpMIwhW1vSt6pnbdt9M:boi4wsv) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.cc#L23)):*
> ```cpp
>   switch (position_index_in_mobilizer) {
>     case 0:
>       return "qx";
> ```

I imagine that we want `r` not `qx`, etc?

Ditto throughout the two new functions.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)* status: 8 unresolved discussions

___
*[`multibody/tree/rpy_floating_mobilizer.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMIwhW1vSt6pnbdt9L:-NpMJSWU2sY3mhDfWGCi:b-cgdwan) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.cc#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I imagine that we want `r` not `qx`, etc?

Ditto throughout the two new functions.
</blockquote></details>

Ah, I guess "r,p,y,x,y,z" would have a duplicate use of "y".  Still, is "qx" a sufficiently clear abbreviation for "space-x" or "roll"?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)* status: 8 unresolved discussions

___
*[`multibody/tree/rpy_floating_mobilizer.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMIwhW1vSt6pnbdt9L:-NpMJqvB8PcYCxyuQXno:b-365mox) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.cc#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, I guess "r,p,y,x,y,z" would have a duplicate use of "y".  Still, is "qx" a sufficiently clear abbreviation for "space-x" or "roll"?
</blockquote></details>

Huh, it's what `RpyBallMobilizer` already uses.  I guess it's consistent, so I'll unblock myself here.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)* status: 2 unresolved discussions

___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMDsCI2WYhxGaC5jtC:-NpMNbpu7wkwQZsIAfmM:bogt763) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/plant/test/compliant_contact_manager_test.cc#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The lack of any other changes in this file probably indicates that this is a dead include, and could be removed instead of renamed.
</blockquote></details>

Done. There were a lot of dead includes in this test.
___
*[`multibody/rational/rational_forward_kinematics.cc` line 11 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMDxVnBdIaedlcyM7w:-NpMOPvYBS2ebxMAMYDc:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/rational/rational_forward_kinematics.cc#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The lack of any other changes in this file probably indicates that this is a dead include, and could be removed instead of renamed.
</blockquote></details>

Done.
___
*[`multibody/tree/rpy_floating_mobilizer.h` line 78 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMGhKT0pVUnn8Ecccp:-NpMS2LW85Kbv1ErLaMh:b3wh8k0) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.h#L78)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is bug fix which is important to mention in the commit message.

I guess "release notes: none" is still good though, since there is no way and end-user could ever be using this class -- it's an internal class with no public joint for it yet.
</blockquote></details>

Done (updated commit message & added tests)
___
*[`multibody/tree/rpy_floating_mobilizer.cc` line 18 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMIKcU2xA3HVoBYCM5:-NpMQnOVCFcsKLAa_eHW:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.cc#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing unit tests for both of these new functions.

See `QuaternionFloatingJointTest.NameSuffix` for an example of what we need.
</blockquote></details>

Done
___
*[`multibody/tree/rpy_floating_mobilizer.cc` line 20 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMIfWp4D_kiRXbs3qO:-NpMRISl0v9SHwNtmlH5:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.cc#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The phrase "documented in get_quaternion" does not seem relevant here.
</blockquote></details>

Done
___
*[`multibody/tree/rpy_floating_mobilizer.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpMIwhW1vSt6pnbdt9L:-NpMM8XyEaNRt5YGPfgb:broxfq) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c38cd0b9f51c564f081fafd78358173aa198b9a/multibody/tree/rpy_floating_mobilizer.cc#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I finally found https://github.com/RobotLocomotion/drake/pull/14971#pullrequestreview-822659535.  Withdrawn.
</blockquote></details>

Yeah, I started out thinking r,p,y but then saw what RpyBall did. #14971 discussion shows lots of thought went into these names already -- better to stick to the plan!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)* status: 2 unresolved discussions

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)* status: 1 unresolved discussion

___
*[`multibody/tree/ball_rpy_joint.h` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLW7p39xvOd7pGoPo-:-NpMaRrK4t4qZ9FpVaR6:bxotdjp) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/ball_rpy_joint.h#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Ideally we would name all the joints consistently. However, my feeling now is that it isn't really worth the pain to rename existing joints. Instead I went with making the new floating joint consistent with the old floating joint, and making the internal mobilizers consistent internally. If we add a quaternion version of Ball joint, we can call it BallQuaternionJoint or decide on renaming at that time. The current PR avoids public changes altogether, which is a plus.

The ideal names IMO would have been BallRpy, BallQuaternion, FloatingRpy, and FloatingQuaternion because then the joint variants would alphabetize together. We could move that way by renaming the existing floating joint to floating_quaternion_joint. But is this really going to solve any user problems? I'm guessing that people are able to find the joints they need. And the floating joints are most often added automatically under the covers without the user needing to name them.

WDYT?
</blockquote></details>

I love the way you explained this, thanks. But I am afraid it'll get lost. Could we captgure this in an issue?
___
*[`multibody/tree/rpy_ball_mobilizer.h` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLtiuA4Iur2F_Uumdx:-NpMb0gg1bzsGAd_hj-D:bt523ab) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/rpy_ball_mobilizer.h#L22)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done, thanks -- that was a typo.
</blockquote></details>

still, this string only shows in file names (like `ball_rpy_joint.h`), the comment seems to suggest otherwise. I'd suggest that if you are talking about the class, simply write `BallRpyJoint`. If you are talking of the name (i.e. `BallRpyJoint::kTypeName`) then `ball_rpy`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)* status: 1 unresolved discussion

___
*[`multibody/tree/ball_rpy_joint.h` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLW7p39xvOd7pGoPo-:-NpMcDGW9VvMfBumPVIv:bb4qksl) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/ball_rpy_joint.h#L27)):*
> Could we captgure this in an issue?

I must have misunderstood something.  What would the issue say?

The premise of Sherm's response is that no additional renaming is necessary, so nothing here is left undone.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)* status: 1 unresolved discussion

___
*[`multibody/tree/ball_rpy_joint.h` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLW7p39xvOd7pGoPo-:-NpMgQfOAyfRsnghnhG0:b-cwinke) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/ball_rpy_joint.h#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Could we captgure this in an issue?

I must have misunderstood something.  What would the issue say?

The premise of Sherm's response is that no additional renaming is necessary, so nothing here is left undone.
</blockquote></details>

Done. Yes, I'm advocating "won't fix" but I think Alejandro is asking for a broader discussion so I captured this in #20841. We can close it "won't fix" if no one feels strongly about changing existing names.
___
*[`multibody/tree/rpy_ball_mobilizer.h` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20827#-NpLtiuA4Iur2F_Uumdx:-NpMhNTSD6gCJZ0V2X1c:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff3f512c40f1746eee4c1513c2930fddac1c9c8a/multibody/tree/rpy_ball_mobilizer.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

still, this string only shows in file names (like `ball_rpy_joint.h`), the comment seems to suggest otherwise. I'd suggest that if you are talking about the class, simply write `BallRpyJoint`. If you are talking of the name (i.e. `BallRpyJoint::kTypeName`) then `ball_rpy`.
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
> Dismissed @amcastro-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20827)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri

**Pull request merged**
