### PR TITLE
Add RotationMatrix constructor that takes RollPitchYaw argument

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8661)

### CODE REVIEW

**Comment by mitiguy** [comment]
Review status: 0 of 46 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8661#-LAyiFJkAYCIQrJttVJH:-LAyiFJl2I5d13g2At7P:bi8z0pu) (no related file):*
Feature review +@hongkai-dai 
Platform review +@soonho-tri 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8661)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 46 of 46 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8661#-LAyjXFl40VC8DMY3CfF:-LAyjXFl40VC8DMY3CfG:bjqwrn2) ([raw file](https://github.com/robotlocomotion/drake/blob/20c81eacd465b416de2c6aa5fbb02d084d68ba40/math/rotation_matrix.h#L142)):*
> ```objc
>     const T s0 = sin(r), s1 = sin(p), s2 = sin(y);
>     const T Rxx = c2 * c1;
>     const T Rxy = c2 * s1 * s0 - s2 * c0;
> ```

BTW, both `Rxy` and `Rxz` use `c2 * s1`, you could factor them out.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8661#-:-LAyp_E-77C39YjXkkT-:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 44 of 46 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 684 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8661#-LB-LVB0-Ag22Far5K4F:-LB-LVB0-Ag22Far5K4G:bk36wt3) ([raw file](https://github.com/robotlocomotion/drake/blob/20c81eacd465b416de2c6aa5fbb02d084d68ba40/math/rotation_matrix.h#L684)):*
> ```objc
> // TODO(mitiguy) Delete this code after all call sites removed.
> // TODO(mitiguy) Mark as deprecated as shown below.
> // DRAKE_DEPRECATED("This code is deprecated per issue #8323. "
> ```

Can we uncomment this part (`DRAKE_DEPRECATED`)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8661)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 46 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8661#-:-LB1PytS-Pwel8YBcyw2:bnfp4nl)*

**Comment by mitiguy** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[math/rotation_matrix.h, line 684 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8661#-LB-LVB0-Ag22Far5K4F:-LB2zQLN2CrNkHd-ffnL:byiq1sy) ([raw file](https://github.com/robotlocomotion/drake/blob/20c81eacd465b416de2c6aa5fbb02d084d68ba40/math/rotation_matrix.h#L684)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Can we uncomment this part (`DRAKE_DEPRECATED`)?
</blockquote></details>

Done.  New comment added.  
Cannot deprecate until call sites have been removed.
Call sites will go in next PR. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8661)*

**Pull request merged**
