### PR TITLE
Complete upgrade of supported Bazel version to 0.14.1

### PR DESCRIPTION
**Pull request by jamiesnape**
Needs Mac CI update.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9005)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@jwnimmer-tri for feature and platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all discussions resolved, platform LGTM from [jwnimmer-tri], labeled "do not merge"

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9005#-:-LF2h6R2DxcjN_03ge2P:bnfp4nl)*

**Comment by BetsyMcPhail** [comment]
Mac CI has been updated

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Pull request merged**
