### PR TITLE
Update SpatialAcceleration methods to parallel SpatialVelocity.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)

### CODE REVIEW

**Comment by mitiguy** [comment]
This PR helps with part of issue[ 16189]( https://github.com/RobotLocomotion/drake/issues/16189).

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699#-:-MxpFKQl5Uz6-YSoW-Ea:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature review pass complete. A few nits, plus the parameter name `omega` should be replaced with `angular_velocity` -- see my comments below.

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699#-:-MxuZbjC4-ZaQEQ4YKmB:b-1h7aam)* status: 6 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[multibody/math/spatial_acceleration.h, line 40 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MxuMnBlCaVu_zv7Joqn:-MxuMnBlCaVu_zv7Joqo:bn3eapr) ([raw file](https://github.com/robotlocomotion/drake/blob/020e76b6bb0c033f1b2e1da820f43b3b69729a3e/multibody/math/spatial_acceleration.h#L40)):*
> ```objc
> /// in section @ref multibody_spatial_vectors.
> ///
> /// The typeset for A_MB_E is @f$\,{^MA^B}@f$ and its definition is
> ```

minor: the typeset version doesn't show the expressed-in frame
___
*[multibody/math/spatial_acceleration.h, line 44 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MxuO3t07CyMaRmr0_cC:-MxuO3t07CyMaRmr0_cD:b-f60khd) ([raw file](https://github.com/robotlocomotion/drake/blob/020e76b6bb0c033f1b2e1da820f43b3b69729a3e/multibody/math/spatial_acceleration.h#L44)):*
> ```objc
> /// spatial velocity in frame M and @f$\frac{^Md}{dt}@f$ denotes the time
> /// derivative taken in frame M. To differentiate a vector, we need to
> /// specify in what frame the time derivative is taken, see [Mitiguy 2016, §6.1]
> ```

minor: it's not clear to me that the 2016 version of your book is available (on your web site the available version wasn't dated). Can a reader actually get this reference somehow? If not you should modify it to something they can actually get.
___
*[multibody/math/spatial_acceleration.h, line 50 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MxuOdDH0o35Gu1O3rfi:-MxuOdDH0o35Gu1O3rfj:b-9msnmz) ([raw file](https://github.com/robotlocomotion/drake/blob/020e76b6bb0c033f1b2e1da820f43b3b69729a3e/multibody/math/spatial_acceleration.h#L50)):*
> ```objc
> /// In source code (monogram) notation, we write `A_MB = DtM(V_MB)`, where
> /// `DtM()` denotes the time derivative in frame M. Details on vector
> /// differentiation is in section @ref Dt_multibody_quantities.
> ```

BTW I followed this link -- it's really good!
___
*[multibody/math/spatial_acceleration.h, line 73 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MxuOpbT9X-c8Ncw1nJR:-MxuOpbT9X-c8Ncw1nJS:b-15g4uu) ([raw file](https://github.com/robotlocomotion/drake/blob/020e76b6bb0c033f1b2e1da820f43b3b69729a3e/multibody/math/spatial_acceleration.h#L73)):*
> ```objc
> 
>   /// Constructs a spatial acceleration from an angular acceleration @p `alpha`
>   /// and a translational acceleration @p `a`.
> ```

nit: don't use `@p` on a quantity that is already in back quotes. That has no effect in Doxygen but makes it harder to read here.

Also, this formatting is inconsistent with the other methods where you used α and 𝐚 in the Doxygen brief. 
___
*[multibody/math/spatial_acceleration.h, line 175 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MxuW6ZgD9xYQyAjIvJ7:-MxuW6ZgD9xYQyAjIvJ8:bv3ynqt) ([raw file](https://github.com/robotlocomotion/drake/blob/020e76b6bb0c033f1b2e1da820f43b3b69729a3e/multibody/math/spatial_acceleration.h#L175)):*
> ```objc
>   /// @note This method speeds the Shift() computation when ω_MB = 0, even if
>   /// α_MB ≠ 0 (α_MB is stored in `this`).
>   SpatialAcceleration<T> ShiftWithOmegaZero(const Vector3<T>& offset) const {
> ```

minor: see my comment below -- we shouldn't be spelling out "Omega". Instead consider something like `ShiftWithZeroAngularVelocity()`.
___
*[multibody/math/spatial_acceleration.h, line 287 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MxuTldOE2VeEHCDxT8o:-MxuTldP3G4GCifQz0uK:bglc6uy) ([raw file](https://github.com/robotlocomotion/drake/blob/020e76b6bb0c033f1b2e1da820f43b3b69729a3e/multibody/math/spatial_acceleration.h#L287)):*
> ```objc
>       const Vector3<T>& omega,
>       const SpatialVelocity<T>& velocity_of_moving_frame,
>       const SpatialAcceleration<T>& acceleration_of_moving_frame) const {
> ```

minor: the parameter name `omega` seems out of place here (and in the other methods also). Instead consider `angular_velocity_of_this_frame` or something like that to match the other nice names. Also note that we document everywhere else that we use `w` in code to stand for `ω` -- we don't spell it out. And `w` would look even weirder here.
___
*[multibody/math/spatial_velocity.h, line 132 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MxuVt7I6XshE7UVDbhF:-MxuVt7I6XshE7UVDbhG:bqcmqp2) ([raw file](https://github.com/robotlocomotion/drake/blob/020e76b6bb0c033f1b2e1da820f43b3b69729a3e/multibody/math/spatial_velocity.h#L132)):*
> ```objc
>   /// If frame C is rigidly fixed to frame B, V_BC_E = 0 and this method
>   /// produces a Shift() operation (albeit inefficiently).
>   /// @see %SpatialAcceleration::ComposeWithMovingFrameVelocity() for the
> ```

nit: Velocity -> Acceleration

**Review by sherm1 — COMMENTED** [review]
Oh, I forgot to mention -- this is really nice! The notation is crisp and clear.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699#-:-MxuZt_LCyDOj4zgwGeW:bpae4u6)* status: 6 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
CI is failing

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699#-:-MyETSjL6IdLm2QrWB-_:bpzgx0j)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699#-:-MyJgcjeBbzrgsUNqv1Z:b-n0m1lx)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[multibody/math/spatial_acceleration.h, line 291 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyJfU-j55HYuT2epbxX:-MyJfU-j55HYuT2epbxY:b-a53k91) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/math/spatial_acceleration.h#L291)):*
> ```objc
>       const Vector3<T>& angular_velocity_of_this_frame,
>       const SpatialVelocity<T>& velocity_of_moving_frame,
>       const SpatialAcceleration<T>& acceleration_of_moving_frame) const {
> ```

BTW the signature of this method is odd. It requires (pos,vel,acc) of moving frame but those parameters aren't adjacent -- the angular velocity of `this` frame is stuck between pos & vel. I think we're stuck with it now, though -- flipping the meaning of the first two parameters would be a disaster since they have the same types!

Maybe the method documentation could point out the odd ordering in the hope of reducing the chance of error?

**Review by sherm1 — COMMENTED** [review]
+@jwnimmer-tri for platform review please, Thursday per rotation

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699#-:-MyJhUqYBpqlH9Qyv2O7:bykcvs4)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @mitiguy)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699#-:-MyKUmLHAA0BmNs0HuDf:bnfp4nl)* status: 8 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKOzkE7r4nmjkmf3Cj:-MyKOzkF0-EA-wgOLF4-:b-fjo3pp) (no related file):*
FYI In general, we should be precise and not use the word "method" in our documentation to refer to a C++ member function.

https://stackoverflow.com/questions/8596461/in-c-what-is-the-difference-between-a-method-and-a-function

However, this PR is consistent with the existing informal use of "method" throughout all of the documentation in this directory, so is OK as-is.

---
___
*[multibody/math/spatial_acceleration.h, line 223 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKQx1O4buGIrZY9Qv4:-MyKQx1O4buGIrZY9Qv5:bzicgqc) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/math/spatial_acceleration.h#L223)):*
> ```objc
>   ///   α_MC = α_MB + α_BC + ω_MB x ω_BC
>   /// </pre>
>   /// @see %SpatialVelocity::ComposeWithMovingFrameVelocity() for the related
> ```

nit The purpose of `%` is to prevent a spurious hyperlink.  However, it seems like a hyperlink to the function would be nice here.



_Suggestion:_
```objc
@see SpatialVelocity::ComposeWithMovingFrameVelocity()
```
___
*[multibody/math/spatial_acceleration.h, line 328 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKQTRJC_k1OC2mu7Pb:-MyKQTRK7D53KsUm4iML:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/math/spatial_acceleration.h#L328)):*
> ```objc
> /// @param[in] A2_E spatial acceleration expressed in the same frame E as A1_E.
> /// @note The general utility of this method is questionable and this method
> /// should only be used if you are sure it makes sense. .
> ```

typo



_Suggestion:_
```objc
.
```
___
*[multibody/math/spatial_velocity.h, line 132 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKPQLS5AprpVIPZU_o:-MyKPQLS5AprpVIPZU_p:bzicgqc) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/math/spatial_velocity.h#L132)):*
> ```objc
>   /// If frame C is rigidly fixed to frame B, V_BC_E = 0 and this method
>   /// produces a Shift() operation (albeit inefficiently).
>   /// @see %SpatialAcceleration::ComposeWithMovingFrameAcceleration() for the
> ```

nit The purpose of `%` is to prevent a spurious hyperlink.  However, it seems like a hyperlink to the function would be nice here.



_Suggestion:_
```objc
/// @see SpatialAcceleration::ComposeWithMovingFrameAcceleration()
```
___
*[multibody/tree/body_node.h, line 547 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKOHEO5u6BcL6Qf3LT:-MyKOHEO5u6BcL6Qf3LU:b-omxi5o) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/tree/body_node.h#L547)):*
> ```objc
>                                                   V_PB_W, A_PB_W);
>     } else {
>       const SpatialAcceleration<T> A_PB_W =           // Eq. (4), with w_FM = 0.
> ```

nit This `// Eq 4 ...` comment has taken a vacation to the right-hand margin.  That seems a bit too far to be easily readable while skimming.
___
*[bindings/pydrake/multibody/math_py.cc, line 217 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKUS3_8OCP6qbbVlUf:-MyKUS3_8OCP6qbbVlUg:bhf8ca3) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L217)):*
> ```cpp
>         overload_cast_explicit<Class, const Vector3<T>&, const Vector3<T>&>(
>             &Class::Shift),
>         py::arg("offset"), py::arg("angular_velocity_of_this_frame"),
> ```

It seems somewhat mean to not provide python users with _any_ nice 1-argument Shift method anymore?  Should we default the `angular_velocity_of_this_frame` to zero in the bindings here, so that calls to `a.Shift(p)` still work without any impact to users?
___
*[bindings/pydrake/multibody/math_py.cc, line 222 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKSLRD6-2iiMfkn2qG:-MyKSLRE-6ET8rQ0QNyO:b-oq1ddf) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L222)):*
> ```cpp
>         "Shift(p_PoQ_E, w_WP_E) is deprecated, and will be removed on or around"
>         " 2022-07-01. Please instead use "
>         "Shift(offset, angular_velocity_of_this_frame)";
> ```

nit I don't think the users will understand this.  The method isn't going away, just the kwarg names are changing.

Something along these lines would be more clear, with specific mention of "kwarg names":



_Suggestion:_
```cpp
        "The kwarg names p_PoQ_E and w_WP_E are deprecated, and will"
        " be removed on or around 2022-07-01. Please instead name them"
        " as offset and angular_velocity_of_this_frame, respectively.";
```
___
*[bindings/pydrake/multibody/math_py.cc, line 237 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKSn6j2rYd9Hr-Py6o:-MyKSn6k3RUuvQ6H9mJl:b-ydad2s) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L237)):*
> ```cpp
>         cls_doc.ComposeWithMovingFrameAcceleration.doc);
>     constexpr char doc_ComposeMovingFrameAccel_deprecatedArgName[] =
>         "ComposeWithMovingFrameAcceleration(p_PB_E, w_WP_E, V_PB_E, A_PB_E)"
> ```

nit Ditto.  Mention "kwarg names" (which are deprecated), not the method (which is not deprecated).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKOzkE7r4nmjkmf3Cj:-MyO_Otd6hRGsntIuWvO:b-2owpb8) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI In general, we should be precise and not use the word "method" in our documentation to refer to a C++ member function.

https://stackoverflow.com/questions/8596461/in-c-what-is-the-difference-between-a-method-and-a-function

However, this PR is consistent with the existing informal use of "method" throughout all of the documentation in this directory, so is OK as-is.
</blockquote></details>

I used this as an  opportunity to clean up some of the function/method language here .

---
___
*[multibody/math/spatial_acceleration.h, line 223 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKQx1O4buGIrZY9Qv4:-MyO9PBWCPqygQjxK07-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/math/spatial_acceleration.h#L223)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The purpose of `%` is to prevent a spurious hyperlink.  However, it seems like a hyperlink to the function would be nice here.
</blockquote></details>

Done.
___
*[multibody/math/spatial_acceleration.h, line 291 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyJfU-j55HYuT2epbxX:-MyOasr52okBZYF-jmh7:b85zlkz) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/math/spatial_acceleration.h#L291)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the signature of this method is odd. It requires (pos,vel,acc) of moving frame but those parameters aren't adjacent -- the angular velocity of `this` frame is stuck between pos & vel. I think we're stuck with it now, though -- flipping the meaning of the first two parameters would be a disaster since they have the same types!

Maybe the method documentation could point out the odd ordering in the hope of reducing the chance of error?
</blockquote></details>

I think the signature was chosen to parallel Shift() and ShiftInPlace(), e.g.,:

Shift( const Vector3<T>& offset,
         const Vector3<T>& angular_velocity_of_this_frame);

I added cross-talk between Shift() and ComposeWithMovingFrameAcceleration() to  draw more attention to these related "cousin" functions and to provide advice on choosing the proper function. 
___
*[multibody/math/spatial_acceleration.h, line 328 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKQTRJC_k1OC2mu7Pb:-MyOAVIiETMESFx4vluo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/math/spatial_acceleration.h#L328)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[multibody/math/spatial_velocity.h, line 132 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKPQLS5AprpVIPZU_o:-MyOidvf9hcyA24gf5wR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/math/spatial_velocity.h#L132)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The purpose of `%` is to prevent a spurious hyperlink.  However, it seems like a hyperlink to the function would be nice here.
</blockquote></details>

Done.
___
*[multibody/tree/body_node.h, line 547 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKOHEO5u6BcL6Qf3LT:-MyOinuT4suYBL3XlZHd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/multibody/tree/body_node.h#L547)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This `// Eq 4 ...` comment has taken a vacation to the right-hand margin.  That seems a bit too far to be easily readable while skimming.
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/math_py.cc, line 217 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKUS3_8OCP6qbbVlUf:-MyOq-9M13Bn4SZrcJRc:bbt5xwo) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems somewhat mean to not provide python users with _any_ nice 1-argument Shift method anymore?  Should we default the `angular_velocity_of_this_frame` to zero in the bindings here, so that calls to `a.Shift(p)` still work without any impact to users?
</blockquote></details>

SpatialAcceleration::Shift(offset) was a _bad_ idea -- easily misused (as I have done).  It has limited practical use -- mostly for efficient internal calculations.  Long ago, the method was marked as "Advanced" to warn users.  Let's revisit if there are Python uses that truly need ShiftWithZeroAngularVelocity(). 
___
*[bindings/pydrake/multibody/math_py.cc, line 222 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKSLRD6-2iiMfkn2qG:-MyP2hTHEJ8akLtU2zNt:bqtwa5u) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L222)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I don't think the users will understand this.  The method isn't going away, just the kwarg names are changing.

Something along these lines would be more clear, with specific mention of "kwarg names":

</blockquote></details>

Done with different wording (here and elsewhere).  
___
*[bindings/pydrake/multibody/math_py.cc, line 237 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKSn6j2rYd9Hr-Py6o:-MyP3-j548Nrrx0CkLSQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L237)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Ditto.  Mention "kwarg names" (which are deprecated), not the method (which is not deprecated).
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy and @sherm1)

___
*[bindings/pydrake/multibody/math_py.cc, line 217 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKUS3_8OCP6qbbVlUf:-MyPLVxG4ID5vP2qXRop:bv6qsin) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L217)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

SpatialAcceleration::Shift(offset) was a _bad_ idea -- easily misused (as I have done).  It has limited practical use -- mostly for efficient internal calculations.  Long ago, the method was marked as "Advanced" to warn users.  Let's revisit if there are Python uses that truly need ShiftWithZeroAngularVelocity(). 
</blockquote></details>

Trying to group some functions as "C++ only" makes it more difficult to maintain the overall codebase.  We should keep our entropy in check.  Boring code is good code.

If the `ShiftWithZeroAngularVelocity` is useful for C++ users, then we should bind it in pydrake.  If it's too dangerous to survive, then we should purge it from C++ as well.

The only reason not to bind a C++ function in Python should be when the type signature doesn't work in Python (usually due to the lack of static typing).  Otherwise, we should be consistent and uniform.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[bindings/pydrake/multibody/math_py.cc, line 217 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKUS3_8OCP6qbbVlUf:-MyPZaywBX_fVf_gjPJq:b-74tuf4) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Trying to group some functions as "C++ only" makes it more difficult to maintain the overall codebase.  We should keep our entropy in check.  Boring code is good code.

If the `ShiftWithZeroAngularVelocity` is useful for C++ users, then we should bind it in pydrake.  If it's too dangerous to survive, then we should purge it from C++ as well.

The only reason not to bind a C++ function in Python should be when the type signature doesn't work in Python (usually due to the lack of static typing).  Otherwise, we should be consistent and uniform.
</blockquote></details>

I am OK with creating with a Python binding for ShiftWithZeroAngularVelocity(offset) -- albeit I am reluctant to do.  This method was purposely marked as "Advanced" because we needed it to be public due to how we were using it internally.  Perhaps a "Developer only" marking would be more explicit/appropriate as its use for C++ or Python users is questionable.  I think our use of "Advanced" is worth discussion.  @sherm1 may want to weigh in here.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[bindings/pydrake/multibody/math_py.cc, line 217 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKUS3_8OCP6qbbVlUf:-MyPfHrk0FHcWf8kV7AV:bfqdbpp) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L217)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

I am OK with creating with a Python binding for ShiftWithZeroAngularVelocity(offset) -- albeit I am reluctant to do.  This method was purposely marked as "Advanced" because we needed it to be public due to how we were using it internally.  Perhaps a "Developer only" marking would be more explicit/appropriate as its use for C++ or Python users is questionable.  I think our use of "Advanced" is worth discussion.  @sherm1 may want to weigh in here.
</blockquote></details>

If you want to document the C++ function as a "Internal use only", then it's OK to omit it from pydrake.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @sherm1)

___
*[bindings/pydrake/multibody/math_py.cc, line 217 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKUS3_8OCP6qbbVlUf:-MyT14OxAv7WhNzxwZUn:b-243an) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you want to document the C++ function as a "Internal use only", then it's OK to omit it from pydrake.
</blockquote></details>

My 2¢: Now that it has a name that clearly says what it does, I don't think it presents any danger to Python users (even if they won't get any noticeable performance boost as we do in C++). If it is easier to maintain a matched set between C++ and Python then I think we ought to just bind this one too. I'd rather see that than making this "internal use only" because it may have utility for advanced users for the same reason we wanted it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy and @sherm1)

___
*[bindings/pydrake/multibody/math_py.cc, line 217 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKUS3_8OCP6qbbVlUf:-MyhO8_R0ZmWsj8ADe2C:b-dxcbts) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L217)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

My 2¢: Now that it has a name that clearly says what it does, I don't think it presents any danger to Python users (even if they won't get any noticeable performance boost as we do in C++). If it is easier to maintain a matched set between C++ and Python then I think we ought to just bind this one too. I'd rather see that than making this "internal use only" because it may have utility for advanced users for the same reason we wanted it.
</blockquote></details>

Makes sense.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @sherm1)

___
*[bindings/pydrake/multibody/math_py.cc, line 217 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16699#-MyKUS3_8OCP6qbbVlUf:-Myhkpi59ZuRUEuaqPiT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6836cf03ecabe5c10d1943d4f659b6a8995c9844/bindings/pydrake/multibody/math_py.cc#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Makes sense.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
Just waiting on @sherm1 now.

**Review by sherm1 — COMMENTED** [review]
Looks even better now :lgtm:

> Reviewed 3 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699#-:-MyiRqMA4vsLixf4hCVf:b64dbo1)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16699#-:-MyiSGcM878KmwMYlNCI:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @mitiguy)

**Pull request merged**
