### PR TITLE
Update director to support ellipsoid visualization

### PR DESCRIPTION
**Pull request by rdeits**
This moves the director submodule up to include https://github.com/RobotLocomotion/director/pull/272 which allows `drake-visualizer` to render ellipsoids. It would be extremely useful for me to have this in the version of Director shipped with Drake, rather than having to keep around another copy of Director just for this feature. 

This could, in the future, allow us to replace the hand-coded LCMGL calls that Drake uses to render inertial ellipsoids: https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/BotVisualizer.m#L178 with native `drake-visualizer` ellipsoids. I've done that in my own package here: https://github.com/rdeits/RigidBodyTreeInspector.jl#inertial-ellipsoids

@liangfok could you please give me a feature review?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3640)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by tkoolen** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
I believe this PR was superseded by #3738.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3640#-:-KTiOZoBP7QHdLnrDPm4:bioplss)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3640)*

**Comment by liangfok** [comment]
I've confirmed that the current director submodule SHA (https://github.com/RobotLocomotion/director/commit/38499093ba928a869bda48fb69437fa0f1a44189) includes this PR's submodule SHA (https://github.com/RobotLocomotion/director/commit/7d16d08e171b99316662abd943cc365f10934dc1), and will thus close this PR.

**Comment by liangfok** [comment]
@rdeits, sorry! I just noticed you had tagged me in your original post. For reference, I more frequently check the PRs that are assigned to me through Reviewable's dashboard: https://reviewable.io/reviews#-. See the "assigned to me" section.

To assign me a review, log into this PR through Reviewable and then add a comment that contains the words "+@liangfok". This of course works with anyone else's github user name as well.

**Comment by rdeits** [comment]
@liangfok ah, ok. I hadn't quite wrapped my head around Reviewable. Thanks!

**Pull request closed without merging**
