### PR TITLE
[SAP] SapSolver uses supernodal sparse algebra

### PR DESCRIPTION
**Pull request by amcastro-tri**
SapSolver uess supernodal algebra by default.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055#-:-N0mHoHVAP_ajw91IE2C:bzgdhpr)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature review done. PTAL.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055#-:-N0qhoIKE9F87p86nIuR:bpplnaq)* status: 6 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.h` line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qh6VfAwvMWxCRWkzJ:-N0qh6VfAwvMWxCRWkzK:bny80it) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L115)):*
> ```objc
>   // SAP uses sparse supernodal algebra by default. Set this to true to use
>   // dense algebra instead. Typically used for testing.
>   bool use_dense_algebra{false};
> ```

With this change in default choice of solver, we lost all test coverage on the dense solver.
___
*[`multibody/contact_solvers/sap/sap_solver.h` line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qaq8pA2oHY0v2dsrU:-N0qaq8pA2oHY0v2dsrV:b-xt3a8c) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L168)):*
> ```objc
> 
>     // Dimensionless momentum residual at each iteration. Of size num_iters + 1.
>     std::vector<double> momentum_residual;
> ```

Should this vector be cleared when Reset() is called?
___
*[`multibody/contact_solvers/sap/sap_solver.h` line 282 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qe0glDDT1KkzR663i:-N0qe0glDDT1KkzR663j:b-tv4bye) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L282)):*
> ```objc
> 
>   // Updates the supernodal solver with the constraint's Hessian G(v),
>   // factorizes it, and solves for the search direction `dv`.
> ```

There are a few preconditions that need to be documented:
1. Pointers non-null.
2. The supernodal solver is initialized to have the proper size (otherwise an exception is thrown in `UpdateSuperNodalSolver()`.
3. (Maybe) Factor hasn't been called by supernodal solver? I forgot what happens if you call Factor twice in a row.
___
*[`multibody/contact_solvers/sap/sap_solver.h` line 299 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qet4f6mWm6BlmKo1L:-N0qet4f6mWm6BlmKo1M:b16i9iw) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L299)):*
> ```objc
>   // @pre context was created by the underlying SapModel.
>   void CalcSearchDirectionData(const systems::Context<T>& context,
>                                SuperNodalSolver* supernodal_solver,
> ```

The parameter `supernodal_solver` deserves a note -- If it's null, the dense solver will be called. 
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qb9Yg4-JOmgWux0qK:-N0qb9Yg4-JOmgWux0qL:b-q99r0y) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.cc#L151)):*
> ```cpp
>         // the stopping criteria is satisfied at k = 0 (good guess), then we
>         // skip the expensive instantiation of the solver.
>         supernodal_solver = MakeSuperNodalSolver();
> ```

Looks like a new solver is instantiated at every iteration. Is that intended?
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qhWtkDW_GpUAwO1gZ:-N0qhWtkDW_GpUAwO1g_:b59bkua) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.cc#L336)):*
> ```cpp
> 
>   // If the very last iterate satisfies Armijo's, we use it.
>   if (satisfies_armijo(alpha, ell)) return std::make_pair(alpha, iteration);
> ```

I'm curious why this is required for this PR. Is it because some unit test failed without it?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: 5 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.h` line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qh6VfAwvMWxCRWkzJ:-N144reS93QfApHta2P5:b-yhmaia) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L115)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

With this change in default choice of solver, we lost all test coverage on the dense solver.
</blockquote></details>

The dense solver is mostly meant for debugging. Right now in the unit tests we are using it to test the supernodal Hessian, which indirectly provides coverage for the dense solver.
Do you consider this to be insufficient? we could parameterize the fixtures on the algebra type, but I think we'd be overcomplicating things. WDYT?
___
*[`multibody/contact_solvers/sap/sap_solver.h` line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qaq8pA2oHY0v2dsrU:-N145VTg0MnGlT0PaqWS:bnrttix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L168)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Should this vector be cleared when Reset() is called?
</blockquote></details>

good call, thanks
___
*[`multibody/contact_solvers/sap/sap_solver.h` line 282 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qe0glDDT1KkzR663i:-N1468hL6FomwHL-Iol6:b-pd2r9w) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L282)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There are a few preconditions that need to be documented:
1. Pointers non-null.
2. The supernodal solver is initialized to have the proper size (otherwise an exception is thrown in `UpdateSuperNodalSolver()`.
3. (Maybe) Factor hasn't been called by supernodal solver? I forgot what happens if you call Factor twice in a row.
</blockquote></details>

Done. Number (3) is not a pre-condition given we update the weight matrix before we call `Factor()`.
___
*[`multibody/contact_solvers/sap/sap_solver.h` line 299 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qet4f6mWm6BlmKo1L:-N146yGTBILhlWn3Gjvb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L299)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The parameter `supernodal_solver` deserves a note -- If it's null, the dense solver will be called. 
</blockquote></details>

Done.
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qb9Yg4-JOmgWux0qK:-N148Ev5ASwiQRu64e7c:b-jtmi2f) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.cc#L151)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Looks like a new solver is instantiated at every iteration. Is that intended?
</blockquote></details>

nooo! thanks catching this.
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qhWtkDW_GpUAwO1gZ:-N148KxI7Ghlhg_18WQN:b-x0akuw) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.cc#L336)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm curious why this is required for this PR. Is it because some unit test failed without it?
</blockquote></details>

It is not required and unit tests will pass just fine. It came from #17045.
In retrospect, I can push #17045 separately. However this is definitely and improvement and we could push it in this PR. Thoughts?

**Review by xuchenhan-tri — COMMENTED** [review]
feature :lgtm: 
+@rpoyner-tri for platform review on Tuesday per rotation please.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055#-:-N15Q1J8ArBTJzyoT5US:bvlc2bi)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @amcastro-tri and @rpoyner-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.h` line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qh6VfAwvMWxCRWkzJ:-N15QVKF1ob0kYgh4o67:b3bn1z7) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L115)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

The dense solver is mostly meant for debugging. Right now in the unit tests we are using it to test the supernodal Hessian, which indirectly provides coverage for the dense solver.
Do you consider this to be insufficient? we could parameterize the fixtures on the algebra type, but I think we'd be overcomplicating things. WDYT?
</blockquote></details>

I agree that the dense hessian is tested indirectly. However, the `CallDenseSolver()` function is now left untested.
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qhWtkDW_GpUAwO1gZ:-N15OmyEAQnaHjEdVvIz:b-8j6qef) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.cc#L336)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

It is not required and unit tests will pass just fine. It came from #17045.
In retrospect, I can push #17045 separately. However this is definitely and improvement and we could push it in this PR. Thoughts?
</blockquote></details>

I think it's fine either way. 
My personal preference would be a separate PR if you don't mind the extra editing churn.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.h` line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qh6VfAwvMWxCRWkzJ:-N15iup24zueSWYBGjPf:bxvyt9v) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.h#L115)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I agree that the dense hessian is tested indirectly. However, the `CallDenseSolver()` function is now left untested.
</blockquote></details>

Added more tests.
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N0qhWtkDW_GpUAwO1gZ:-N15ipK89L4dj8j1PgSY:b-1ykxgf) ([raw file](https://github.com/robotlocomotion/drake/blob/b4c0758c3cd3e021316d4f3b5df16e3728f6960a/multibody/contact_solvers/sap/sap_solver.cc#L336)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think it's fine either way. 
My personal preference would be a separate PR if you don't mind the extra editing churn.
</blockquote></details>

It'd be quite a bit of churn if I need to come up with a very specific test for this.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 468 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N19iAngC6qgIG-hcAjR:-N19k8Gj-WOAVRmsp7f4:bkom2ue) ([raw file](https://github.com/robotlocomotion/drake/blob/e589f2c8a4356b07f5a3c07b131e9dff5ee21472/multibody/contact_solvers/sap/sap_solver.cc#L468)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

btw, consider `DRAKE_DEMAND(parameters_.use_dense_algebra || (supernodal_solver != nullptr));` to get the entire correct condition into the error message.
</blockquote></details>

Do you mean?
```c++
if (!parameters_.use_dense_algebra)
  DRAKE_DEMAND(!parameters_.use_dense_algebra && (supernodal_solver != nullptr));
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 468 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N19iAngC6qgIG-hcAjR:-N19uu6G8ItcJykChDM0:b-3m78s) ([raw file](https://github.com/robotlocomotion/drake/blob/e589f2c8a4356b07f5a3c07b131e9dff5ee21472/multibody/contact_solvers/sap/sap_solver.cc#L468)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Do you mean?
```c++
if (!parameters_.use_dense_algebra)
  DRAKE_DEMAND(!parameters_.use_dense_algebra && (supernodal_solver != nullptr));
```

</blockquote></details>

My hope was to get rid of the `if` altogether. Perhaps I got the Demorgan's law shuffling wrong, but it should be possible to express the logic you want in one line.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 468 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N19iAngC6qgIG-hcAjR:-N19vq4l18tjX918dbN3:b-klkvhc) ([raw file](https://github.com/robotlocomotion/drake/blob/e589f2c8a4356b07f5a3c07b131e9dff5ee21472/multibody/contact_solvers/sap/sap_solver.cc#L468)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

My hope was to get rid of the `if` altogether. Perhaps I got the Demorgan's law shuffling wrong, but it should be possible to express the logic you want in one line.
</blockquote></details>

The predicate should be reworked all together. If supernodal_solver != nullptr AND use_dense_algebra == true, then the supernodal solver will still be invoked. This is slightly confusing.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 468 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N19iAngC6qgIG-hcAjR:-N19wwG2B2j5fqZ3mtTd:bht87p2) ([raw file](https://github.com/robotlocomotion/drake/blob/e589f2c8a4356b07f5a3c07b131e9dff5ee21472/multibody/contact_solvers/sap/sap_solver.cc#L468)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The predicate should be reworked all together. If supernodal_solver != nullptr AND use_dense_algebra == true, then the supernodal solver will still be invoked. This is slightly confusing.
</blockquote></details>

Perhaps
```
  DRAKE_DEMAND(parameters_.use_dense_algebra || (supernodal_solver != nullptr));
  // Update search direction dv.
  if (!parameters_.use_dense_algebra)
    CallSuperNodalSolver(context, supernodal_solver, &data->dv);
  } else {
    CallDenseSolver(context, &data->dv);
  }
```

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 468 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N19iAngC6qgIG-hcAjR:-N1AMMY0ENglx6yc6XaD:b-4m7oye) ([raw file](https://github.com/robotlocomotion/drake/blob/e589f2c8a4356b07f5a3c07b131e9dff5ee21472/multibody/contact_solvers/sap/sap_solver.cc#L468)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Perhaps
```
  DRAKE_DEMAND(parameters_.use_dense_algebra || (supernodal_solver != nullptr));
  // Update search direction dv.
  if (!parameters_.use_dense_algebra)
    CallSuperNodalSolver(context, supernodal_solver, &data->dv);
  } else {
    CallDenseSolver(context, &data->dv);
  }
```
</blockquote></details>

I see. I thought it had to do more with how the error message read. Yeap, you got your laws right @rpoyner-tri (I believe you need absorption here but there might be many ways to do it).
Done

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot retest this please.

**Comment by amcastro-tri** [comment]
Weird, why is it that I can't reproduce any of the CI failures? what am I doing wrong?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
I think this may have something to do with the change in default line search parameters.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055#-:-N1Aoxaw91iq-k2J10c6:b-404w80)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
That is correct @xuchenhan-tri, thanks! The new default is great. All these tests now perform much less iterations since once SAP's state reaches the correct "contact mode", Newton's method will converge in the next iteration if alpha=1. In particular for stiction this is exactly true since the cost becomes exactly quadratic.

I ended up updating the unit tests to force SAP's failure and test throw conditions.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055#-:-N1Ayhlc5aOGpCzMuEGn:bhjjw6r)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 315 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N1AzJ03AhXcRadXTcQP:-N1AzJ03AhXcRadXTcQQ:beubwrp) ([raw file](https://github.com/robotlocomotion/drake/blob/96d0cf0d091a1951a668f2ee7d99c2d21d7c3d8d/multibody/contact_solvers/sap/sap_solver.cc#L315)):*
> ```cpp
> 
>   int iteration = 1;
>   for (; iteration < max_iterations; ++iteration) {
> ```

fyi @xuchenhan-tri, I modified this condition to be a strict inequality so that iterations are counted correctly.
That is, we count number of calls to `CalcCostAlongLine()`. There is one right before this loop at `ls_alpha_max`. The behavior should not change, only the reported number of iterations.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: thanks.

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17055#-:-N1B19kmDBdsrIAD46OA:brfqlva)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 315 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17055#-N1AzJ03AhXcRadXTcQP:-N1B0_B2ESm_ZVh3Anha:b-ykt16x) ([raw file](https://github.com/robotlocomotion/drake/blob/96d0cf0d091a1951a668f2ee7d99c2d21d7c3d8d/multibody/contact_solvers/sap/sap_solver.cc#L315)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

fyi @xuchenhan-tri, I modified this condition to be a strict inequality so that iterations are counted correctly.
That is, we count number of calls to `CalcCostAlongLine()`. There is one right before this loop at `ls_alpha_max`. The behavior should not change, only the reported number of iterations.
</blockquote></details>

This is slightly subtle. Consider putting this as a inline comment.

**Pull request merged**
