### PR TITLE
Add EricCousineau-TRI and SeanCurtis-TRI as platform reviewers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6859)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI +@SeanCurtis-TRI +@ggould-tri +@sammy-tri +@sherm1 +@soonho-tri +@RussTedrake for all review, please.

**Comment by soonho-tri** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6859#-:-KrhqgUWp_lviWXpLf6L:b-uwkowd)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6859#-:-KrjX45L7LUsXM0f1YYR:bnfp4nl)*

**Comment by ggould-tri** [comment]
:clap: :clap: :clap: :clap: :clap: 
:lgtm:
:clap: :clap: :clap: :clap: :clap: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6859#-:-KrkMrocJZVVnY5JygGR:b-63uub3)*

**Comment by EricCousineau-TRI** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6859#-:-KrkPoImT7Ls7fGvENyf:b-uwkowd)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6859#-:-KrkQXLkkTOiAFV5Oypl:bmxilld)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6859#-:-Krk_5pUJKX_4FqnuIu8:bnfp4nl)*

**Comment by sherm1** [comment]
Woo hoo! Congratulations, and condolences, Eric & Sean. :lgtm_strong: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6859#-:-Krkis33-tIA7GCNBrnO:b-tuqt02)*

**Pull request merged**
