### PR TITLE
Fixed mutex logic in ros_clock_publisher_test.

### PR DESCRIPTION
**Pull request by liangfok**
I noticed with while talking with @naveenoid this morning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4541)

### CODE REVIEW

**Comment by liangfok** [comment]
Since this fixes a defect in #4507:

+@naveenoid for feature review please.
+@sammy-tri for platform review please.

Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4541#-:-KZLphkv0764lxiBF3ln:b-xv3pwl)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4541#-:-KZLr9eYm2MtCYcH4ged:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm: with one comment below

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ros/drake_ros_systems/test/ros_clock_publisher_test.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4541#-KZMivH6q2KRrYt9LZVo:-KZMivH7oLUZnrVs-rUg:b-q24zwf) ([raw file](https://github.com/robotlocomotion/drake/blob/b6e4ffe1993ad12767182d726e10e573827760bf/ros/drake_ros_systems/test/ros_clock_publisher_test.cc#L42)):*
> ```cpp
>   rosgraph_msgs::Clock get_received_message() {
>     std::lock_guard<std::mutex> lock(data_mutex_);
>     return recieved_message_;
> ```

typo "recieved_message_" should be "received_message_  (I know it's not new in this diff, but we should fix that one I think)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4541#-:-KZMjB78QhB8UMW2O1rN:bq1iatn)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4541)*

**Comment by liangfok** [comment]
I addressed all reviewer comments and am now waiting for CI to complete.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ros/drake_ros_systems/test/ros_clock_publisher_test.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4541#-KZMivH6q2KRrYt9LZVo:-KZMyhpCllzvbRcFQItk:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/b6e4ffe1993ad12767182d726e10e573827760bf/ros/drake_ros_systems/test/ros_clock_publisher_test.cc#L42)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

typo "recieved_message_" should be "received_message_  (I know it's not new in this diff, but we should fix that one I think)
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4541#-:-KZMdgGddKz2FxwRKaHI:b-icmjjw)*

**Pull request merged**
