### PR TITLE
Add the difference of convex decomposition for nonconvex quadratic forms

### PR DESCRIPTION
**Pull request by hongkai-dai**
This utility function is going to be used for solving non-convex quadratic equality constraint. It is inspired by the paper
```
  DC Decomposition of NOnconvex Polynomials with Algebraic Techniques
  by Amir Ali Ahmadi, Georgina Hall
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7280)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-:-Kwep3FM2QHuN8aKBUIp:bll7v0f)*

**Comment by avalenzu** [comment]
Review pass done. PTAL.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/solvers/nonconvex_optimization_util.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwfi68S5MkrLVzOkB_h:-Kwfi68S5MkrLVzOkB_i:b3uda9w) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.cc#L8)):*
> ```cpp
> namespace solvers {
> std::pair<Eigen::MatrixXd, Eigen::MatrixXd>
> ConvexDecompositionNonConvexQuadraticForm(
> ```

Could we change this to a verb-phrase like `DecomposeNonConvexQuadraticForm`?

---

*[drake/solvers/nonconvex_optimization_util.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfkF46EDbEyzbVEmAY:-KwfkF46EDbEyzbVEmAZ:b-8pu16k) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.cc#L8)):*
> ```cpp
> namespace solvers {
> std::pair<Eigen::MatrixXd, Eigen::MatrixXd>
> ConvexDecompositionNonConvexQuadraticForm(
> ```

Here you treat non-convex as two words (`NonConvex`), but in the naming of the header file, it's treated as one word (`nonconvex`). We should be consistent. Two-words appears to be the preferred choice in the overall code-base, although there aren't any `snake_case`examples.

---

*[drake/solvers/nonconvex_optimization_util.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfdQ4Mfns_vjUf9hMb:-KwfdQ4Mfns_vjUf9hMc:b-au030r) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.cc#L20)):*
> prog.AddLinearConstraint(Q1.array() - Q2.array() ==
>                            ((Q + Q.transpose()) / 2).array());

This appears not to match the constraint described in the header:

>     Q₁ - Q₂ = Q

---

*[drake/solvers/nonconvex_optimization_util.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwf_CX_0KedC2V19dn8:-Kwf_CX_0KedC2V19dn9:bu4e6yk) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.h#L15)):*
Replace
> To find the optimal Q₁, Q₂, we aim to solve ...

with
>To find the optimal Q₁ and Q₂  we solve ...

---

*[drake/solvers/nonconvex_optimization_util.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwf_cBf3YaRmPrH_6fl:-Kwf_cBf3YaRmPrH_6fm:b-lj9aou) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.h#L15)):*
> ```objc
>  * xᵀQx = xᵀQ₁x - xᵀQ₂x,
>  * Q₁, Q₂ are positive semidefinite.
>  * To find the optimal Q₁, Q₂, we aim to solve the following semidefinite
> ```

Why are these the optimal Q₁ and Q₂?

---

*[drake/solvers/nonconvex_optimization_util.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfaSAi50lfNUUEKeZp:-KwfaSAi50lfNUUEKeZq:bsf4tml) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.h#L22)):*
> ```objc
>  *     Q₁ - Q₂ = Q
>  *     Q₁, Q₂ are positive semidefinite
>  * This decomposition Q = Q₁ - Q₂ can be used later, to solve the non-convex
> ```

"This decomposition" -> "The decomposition"

---

*[drake/solvers/nonconvex_optimization_util.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfXEbFQYF415gvyChx:-KwfXEbFQYF415gvyChy:b-6pm3mo) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.h#L27)):*
> ```objc
>  * decomposition, for example
>  *   Undominated d.c Decompositions of Quadratic Functions and Applications
>  *   to Branch-and-BOund Approaches
> ```

Typo: BOund -> Bound

---

*[drake/solvers/test/nonconvex_optimization_util_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwfayoq7xEuo_pcGzD9:-Kwfayoq7xEuo_pcGzDA:bz7udfx) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/nonconvex_optimization_util_test.cc#L11)):*
Suggested rewording:

> Decompose a PSD matrix Q. This should yield Q1 = Q and Q2 = 0.

---

*[drake/solvers/test/nonconvex_optimization_util_test.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfbJIXjsrvVPO8U7X2:-KwfbJIXjsrvVPO8U7X3:b6i5wny) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/nonconvex_optimization_util_test.cc#L21)):*
> ```cpp
> 
> GTEST_TEST(DecomposeNonConvexQuadraticForm, Test1) {
>   // Decomposes a negative definite matrix Q, then Q1 = 0, and Q2 = -Q.
> ```

Re-word as above.

---

*[drake/solvers/test/nonconvex_optimization_util_test.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfbRr5dj18mNanbc9d:-KwfbRr5dj18mNanbc9e:b6i5wny) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/nonconvex_optimization_util_test.cc#L31)):*
> ```cpp
> 
> GTEST_TEST(DecomposeNonConvexQuadraticForm, Test2) {
>   // Decomposes an indefinite matrix Q, [0, 1; 1 0].
> ```

Re-word as above.

---

*[drake/solvers/test/nonconvex_optimization_util_test.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfbTroFGOszvXAEXfa:-KwfbTroFGOszvXAEXfb:b6i5wny) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/nonconvex_optimization_util_test.cc#L56)):*
> ```cpp
> 
> GTEST_TEST(DecomposeNonConvexQuadraticForm, Test3) {
>   // Decomposes an indefinite matrix Q = [1 3; 1, 1]
> ```

Re-word as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-:-Kwfp-43EgkKn8eDjMwt:b837gv3)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/solvers/nonconvex_optimization_util.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwfi68S5MkrLVzOkB_h:-KwhArThbW0EpBxIm6qE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.cc#L8)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Could we change this to a verb-phrase like `DecomposeNonConvexQuadraticForm`?
</blockquote></details>

Done.

---

*[drake/solvers/nonconvex_optimization_util.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfkF46EDbEyzbVEmAY:-KwhBKdHwyuynRHVwCFc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.cc#L8)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Here you treat non-convex as two words (`NonConvex`), but in the naming of the header file, it's treated as one word (`nonconvex`). We should be consistent. Two-words appears to be the preferred choice in the overall code-base, although there aren't any `snake_case`examples.
</blockquote></details>

Done.

---

*[drake/solvers/nonconvex_optimization_util.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfdQ4Mfns_vjUf9hMb:-KwhBSYBMEBNYCfS_h_t:b-376vyb) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.cc#L20)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> prog.AddLinearConstraint(Q1.array() - Q2.array() ==
>                            ((Q + Q.transpose()) / 2).array());

This appears not to match the constraint described in the header:

>     Q₁ - Q₂ = Q
</blockquote></details>

Done. Good catch.

---

*[drake/solvers/nonconvex_optimization_util.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwf_CX_0KedC2V19dn8:-KwhBb3lkXghfcUOzfsM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.h#L15)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Replace
> To find the optimal Q₁, Q₂, we aim to solve ...

with
>To find the optimal Q₁ and Q₂  we solve ...
</blockquote></details>

Done.

---

*[drake/solvers/nonconvex_optimization_util.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwf_cBf3YaRmPrH_6fl:-KwhBbha2qiH8pR0yDZp:b-fctgbh) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.h#L15)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Why are these the optimal Q₁ and Q₂?
</blockquote></details>

In the decomposition of convex optimization, they try to optimize term
```
x' * Q1 * x - x' * Q2 * x,
```
where Q1, Q2 are p.s.d matrices. One technique is to write this function as
```
p1 - p2
p1 = x' * Q1 * x
p2 = x' * Q2 * x
```
the last two equality constraint is replaced by 
```
p1 >= x' * Q1 * x (A second order cone constraint)
p1 <= 2*x0'*Q1*(x - x0) + x0' * Q1 * x0 + delta (A linear constraint)
p2 >= x' * Q2 * x (A second order cone constraint)
p2 <= 2 * x0' * q2(x - x0) + x0' * Q2 * x0 + delta (A linear constraint)
```
where x0 is a given point. The expressions on the right-hand side 2 * x0' * Q1 (x - x0) + x0' * Q1 * x0 is the linearization of x' * Q1 * x at point x0. We know that for each positive scalar delta, the constraint p1 <= 2 * x0' * Q1 * (x - x0) + x0' * Q1 * x0 + delta holds for a small neighbourhood around x0. We want to get the maximal range that this inequality holds, which is an ellipsoid
```
(x - x0)' * Q1 * (x - x0) <= delta
```
When delta is given, the size of this ellipsoid can be approximated by -trace(Q1). We want to maximize the volume of the ellipsoid such that the inequality holds, namely we want to minimize trace(Q1). Same logic works for minimizing trace(Q2).

---

*[drake/solvers/nonconvex_optimization_util.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfaSAi50lfNUUEKeZp:-KwhDR1fs6-V_27we5uC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.h#L22)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

"This decomposition" -> "The decomposition"
</blockquote></details>

Done.

---

*[drake/solvers/nonconvex_optimization_util.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfXEbFQYF415gvyChx:-KwhDU4Qu_QK0ug-y43N:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/nonconvex_optimization_util.h#L27)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Typo: BOund -> Bound
</blockquote></details>

Done.

---

*[drake/solvers/test/nonconvex_optimization_util_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwfayoq7xEuo_pcGzD9:-KwhDb3H4LYaxX3RUn9o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/nonconvex_optimization_util_test.cc#L11)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Suggested rewording:

> Decompose a PSD matrix Q. This should yield Q1 = Q and Q2 = 0.
</blockquote></details>

Done.

---

*[drake/solvers/test/nonconvex_optimization_util_test.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfbJIXjsrvVPO8U7X2:-KwhDmt8dyrDjb00NsTN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/nonconvex_optimization_util_test.cc#L21)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Re-word as above.
</blockquote></details>

Done.

---

*[drake/solvers/test/nonconvex_optimization_util_test.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfbRr5dj18mNanbc9d:-KwhDnhU3wtcGGOHlTpr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/nonconvex_optimization_util_test.cc#L31)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Re-word as above.
</blockquote></details>

Done.

---

*[drake/solvers/test/nonconvex_optimization_util_test.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-KwfbTroFGOszvXAEXfa:-KwhDoKfgvN1X5lTdQxU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/nonconvex_optimization_util_test.cc#L56)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Re-word as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7280)*

**Comment by avalenzu** [comment]
:lgtm: +@ggould-tri  for platform review.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/non_convex_optimization_util.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwf_cBf3YaRmPrH_6fl:-Kwjfn4DVZJHXCezYCe7:b-qon1vo) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/non_convex_optimization_util.h#L15)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

In the decomposition of convex optimization, they try to optimize term
```
x' * Q1 * x - x' * Q2 * x,
```
where Q1, Q2 are p.s.d matrices. One technique is to write this function as
```
p1 - p2
p1 = x' * Q1 * x
p2 = x' * Q2 * x
```
the last two equality constraint is replaced by 
```
p1 >= x' * Q1 * x (A second order cone constraint)
p1 <= 2*x0'*Q1*(x - x0) + x0' * Q1 * x0 + delta (A linear constraint)
p2 >= x' * Q2 * x (A second order cone constraint)
p2 <= 2 * x0' * q2(x - x0) + x0' * Q2 * x0 + delta (A linear constraint)
```
where x0 is a given point. The expressions on the right-hand side 2 * x0' * Q1 (x - x0) + x0' * Q1 * x0 is the linearization of x' * Q1 * x at point x0. We know that for each positive scalar delta, the constraint p1 <= 2 * x0' * Q1 * (x - x0) + x0' * Q1 * x0 + delta holds for a small neighbourhood around x0. We want to get the maximal range that this inequality holds, which is an ellipsoid
```
(x - x0)' * Q1 * (x - x0) <= delta
```
When delta is given, the size of this ellipsoid can be approximated by -trace(Q1). We want to maximize the volume of the ellipsoid such that the inequality holds, namely we want to minimize trace(Q1). Same logic works for minimizing trace(Q2).

</blockquote></details>

Got it. Thanks for the explanation.

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwfayoq7xEuo_pcGzD9:-Kwjf8desAAlv_IM_kgO:b-mmzn2e) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/non_convex_optimization_util_test.cc#L11)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW: I think the acronym "PSD" should be capitalized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-:-Kwjg4E1LB2XTnLf5JTv:b4t1nfk)*

**Comment by ggould-tri** [comment]
:lgtm:, one objection below.

---

Reviewed 3 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/non_convex_optimization_util.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwjnp9TzDc1HnMi0D9d:-Kwjnp9TzDc1HnMi0D9e:b-7rkfap) ([raw file](https://github.com/robotlocomotion/drake/blob/eab805d1e5b6497735170e776bdff9b23c7051b1/drake/solvers/non_convex_optimization_util.cc#L38)):*
> ```cpp
>                            Q2.cast<symbolic::Expression>().trace());
>   prog.AddCost(s);
>   prog.Solve();
> ```

You should test the `SolutionResult` return value of `Solve()` or document why you do not need to do so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-:-Kwjo3K5PFFIz0rhNvwd:b-nn8yml)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/non_convex_optimization_util.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwjnp9TzDc1HnMi0D9d:-Kwx-HOt4DA2dIm9J-oN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eab805d1e5b6497735170e776bdff9b23c7051b1/drake/solvers/non_convex_optimization_util.cc#L38)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

You should test the `SolutionResult` return value of `Solve()` or document why you do not need to do so.
</blockquote></details>

Done.

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7280#-Kwfayoq7xEuo_pcGzD9:-Kwx-cEFkiRxI_563dEz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5e1bf5337a562c539a9c0a8914d56d8ca49910/drake/solvers/test/non_convex_optimization_util_test.cc#L11)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW: I think the acronym "PSD" should be capitalized.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7280)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 7 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7280)*

**Pull request merged**
