### PR TITLE
[Bazel] Add a whole pile of BUILD files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4332)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by rpoyner-tri** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/BUILD, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4332#-KXwVOS1uabGbVA0i7xT:-KXwVOS1uabGbVA0i7xU:b-7on4j2) ([raw file](https://github.com/robotlocomotion/drake/blob/6087364b33cc9bf423eb7cf3ec3dd10028d92e88/drake/systems/framework/primitives/BUILD#L40)):*
> ```Python
> 
> cc_library(
>     name = "constant_vector_source",
> ```

twice?xn

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4332)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/primitives/BUILD, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4332#-KXwVOS1uabGbVA0i7xT:-KXwZ2LhYQ4MND--WKLg:b-eyowtb) ([raw file](https://github.com/robotlocomotion/drake/blob/6087364b33cc9bf423eb7cf3ec3dd10028d92e88/drake/systems/framework/primitives/BUILD#L40)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

twice?xn
</blockquote></details>

Hmm?  Do you mean vs the above library?  One is _value_ source, the other is _vector_ source.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4332)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/BUILD, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4332#-KXwVOS1uabGbVA0i7xT:-KXxA1lO_QbHN_COICnj:b-fofp76) ([raw file](https://github.com/robotlocomotion/drake/blob/6087364b33cc9bf423eb7cf3ec3dd10028d92e88/drake/systems/framework/primitives/BUILD#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm?  Do you mean vs the above library?  One is _value_ source, the other is _vector_ source.
</blockquote></details>

so it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4332)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4332#-:-KXxA9KiTSFwSsQ02SaN:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Alright, with the new push, everything C++ that can & should be in Bazel is in Bazel.  Thus still missing are:
- any library or program that requires a missing external (solver, bullet, ...) to compile;
- any test that requires  a missing external (solver, bullet, ...) to compile;
- old wrong-named code like robotInterfaces such.

PTAL.

---

Review status: 12 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4332#-:-KXxjLuUoaCLLVf-7UPJ:b6wpzcl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
This is heroic.  :lgtm:

---

Reviewed 22 of 22 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4332#-:-KXzuDK5_k6S8kHVYhL3:br6zqgd)*

**Pull request merged**
