### PR TITLE
[tools] Switch stl2obj to use VTK built from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19945 and #16502.
Requires #20068.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20084)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20084#-:-Nd1UNgP-wAEKMviyd0v:bmxilld)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20084#-:-Nd1Xi3-AuNKu0YU0u-4:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
