### PR TITLE
Improve doxygen formatting of monolane builder

### LINKED ISSUE #4560: Doxygen File Descriptions Do Not Have Automatically-Generated Links
# Problem Definition

Doxygen's [automatic link generation feature](https://www.stack.nl/~dimitri/doxygen/manual/autolink.html) is not working on file descriptions. This became a problem in #4389, which contains file descriptions in `drake-distro/drake/automotive/maliput/monolane/builder.h` and `drake-distro/drake/automotive/maliput/monolane/loader.h` that references numerous classes, structs, etc. When reading the generated Doxygen website, clarity would be greatly improved if the aforementioned references could be links to the classes', structs', etc., documentation.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #4560.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4596)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@maddog-tri for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4596#-:-KZgNRiuwwuGP_dZB79u:b-4zoj1h)*

**Comment by sherm1** [comment]
Your volunteer platform reviewer approves this message -- :lgtm: (assuming you've looked at the doxygen output).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4596#-:-KZh5OeP8za714WX1Sij:bn0fdw5)*

**Comment by maddog-tri** [comment]
:lgtm: (Much better than the @file level docs, thank you.)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4596#-:-K__VEZIwC8vImSbHBmT:bg2k69p)*

**Comment by jwnimmer-tri** [comment]
Using override-merge for comment-only change.

**Pull request merged**
