### PR TITLE
Fix gradient computation in SamePointConstraint.

### LINKED ISSUE #17002: DoEval computes incorrect gradient in SamePointConstraint
I just realized that the gradient computation in SamePointConstraint (used in Iris) is incorrect
https://github.com/RobotLocomotion/drake/blob/9dd93ce043f011b6b2ba4a3f593f4e40d9623f86/geometry/optimization/iris.cc#L280-L285

This assumes that the first nq element of y.derivatives() should store the gradient w.r.t q. Namely we assume that the derivatives stored in y is w.r.t q, p_AA and p_BB. While that is how we use DoEval in optimization, theoretically DoEval should support taking gradient w.r.t any arbitrary variables.

I believe the math should be like this
```
y = p_WA - p_WB
dy/dq = Jq_v_WA - Jq_v_WB
dy/dp_AA = R_WA
dy/dp_BB = -R_WB
```
So if we denote the variable we take derivative as z, namely x.derivatives() stores dx/dz, then to compute dy/dz, we use the chain rule as
```
dy/dz = dy/dx * dx/dz
```
where dy/dx = [dy/dq dy/dp_AA, dy/dp_BB].

Hence the code would be
```cc
Eigen::MatrixXd dy_dx(3, nq + 6);
dy_dx << Jq_v_WA - Jq_v_WB, R_WA, -R_WB;
Eigen::MatrixXd dy_dz = dy_dx * ExtractGradient(x);
*y = InitializeAutoDiffGivenGradient(p_WA - p_WB, dy_dz);
```

cc @RussTedrake @AlexandreAmice

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #17002

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17003)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17003#-:-N07BRN-3IXKBjnk7HrN:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
If corrects a math mistake in library code, that should probably be "release notes: yes"?

**Review by hongkai-dai — COMMENTED** [review]
This class is in an unnamed namespace in cc code, I don’t think any external users will access this code.

The previous implementation computes the right gradient when x is set with InitializeGradient, which is how this code is called in optimization solver. So the fix doesn’t change the behavior when we call this constraint in optimization.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17003#-:-N07WQcBBRSmWk_CGh2l:b-xijkk2)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
I agree that this does not change any behavior from the current API.  It only improves matters if someone were to pick up this chunk of code and reuse it elsewhere in the codebase (as a more general constraint).

cc @mpetersen94 for awareness.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17003#-:-N0BMw2_BurQWHd08_7N:bq4joeh)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[geometry/optimization/iris.cc, line 217 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17003#-N0BN7xI0FW7z20u2Tf2:-N0BN7xI0FW7z20u2Tf3:b-1a4yog) ([raw file](https://github.com/robotlocomotion/drake/blob/e543fbd1c35dfc09bef05dc61b821e2c40f0bc16/geometry/optimization/iris.cc#L217)):*
> ```cpp
>                       const Context<double>& context)
>       : solvers::Constraint(3, plant->num_positions() + 6, Vector3d::Zero(),
>                             Vector3d::Zero()),
> ```

btw -- good call, thanks.
___
*[geometry/optimization/iris.cc, line 285 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17003#-N0BNZw57GheaHjiPQHR:-N0BNZw57GheaHjiPQHS:b-eub0qe) ([raw file](https://github.com/robotlocomotion/drake/blob/e543fbd1c35dfc09bef05dc61b821e2c40f0bc16/geometry/optimization/iris.cc#L285)):*
> ```cpp
>     const Eigen::Vector3d y_val =
>         X_WA * math::ExtractValue(p_AA) - X_WB * math::ExtractValue(p_BB);
>     Eigen::Matrix3Xd dy_dz(3, plant_->num_positions() + 6);
> ```

This variable is dydx, not dydz.  in fact, I would remove all mentions of z (including the comment above)?  you don't need it.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17003)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[geometry/optimization/iris.cc, line 285 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17003#-N0BNZw57GheaHjiPQHR:-N0BnDtm-3pklEi73n87:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e543fbd1c35dfc09bef05dc61b821e2c40f0bc16/geometry/optimization/iris.cc#L285)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This variable is dydx, not dydz.  in fact, I would remove all mentions of z (including the comment above)?  you don't need it.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17003#-:-N0DtxHn-FFbJYz3yy_C:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for Monday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17003#-:-N0RqO1C1m8Ca_DK8zG2:b-jarjz8)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
Would I be correct to understand that this is fixing an error in a callback computation from optimizer code for which we have no actual failure case, and that's why there's no test case for #17002 ?

Assuming so, :lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17003#-:-N0WS6JfE-xdON1fUbm7:b-dner1m)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
