### PR TITLE
[pydrake] Clean up binding code for trajectory_optimization_py.cc

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This makes use of the binding style of declaring a block for each unique class and defining the Class (and associated) alias.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18721)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for both reviews, please.

+(release notes: none) 
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18721#-:-NND7HCFCtm-ZBbkIAQ2:b-mmavr5)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@jwnimmer-tri +@sherm1 for both reviews please. (To better redistribute the load.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18721#-:-NNDN4ts5lWFP_BWz1qh:b8wyozm)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +@jwnimmer-tri  -@sherm1.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18721#-:-NNDOcm241KI5mDpKmN3:b-m5fqeb)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[`bindings/pydrake/systems/trajectory_optimization_py.cc` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18721#-NNDOFCo316SJACbrUBy:-NNDOFCo316SJACbrUBz:b-oo8iq3) ([raw file](https://github.com/RobotLocomotion/drake/blob/5a28acc67a3807228fa4ff909c767c2711a9b559/bindings/pydrake/systems/trajectory_optimization_py.cc#L50)):*
> ```cpp
>     constexpr auto& cls_doc = doc.MultipleShooting;
>     py::class_<Class> cls(m, "MultipleShooting", cls_doc.doc);
>     cls.def("time", &Class::time, cls_doc.time.doc)
> ```

nit For consistency with `DirectTranscription` below.



_Suggestion:_
```cpp
cls  // BR
    .def
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18721)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
