### PR TITLE
Fix Logic Bug in Affine Hull Construction

### LINKED ISSUE #20985: Bad numerics when converting from HPolyhedron to VPolytope
### What happened?

I have a block with dimensions 0.03m x 0.03m x 0.075m represented as an HPolyhedron. This is a 3 dimensional block, however when I convert it to a VPolytope the resulting object only has 4 vertices (rather than 8). This is not a problem when the block is 3m x 3m x 7.5 m, pointing to bad numerics when the conversion is occurring. One way to deal with this problem which came up in discussion with @cohnt is to not perform the projection into the affine subspace when the polyhedron is full dimensional. 

Here is some code to replicate the error on my machine (NB: I pip installed drake, so Gurobi/MOSEK are not enabled afaik):
```
import numpy as np
from pydrake.all import HPolyhedron, VPolytope
A1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b1 = np.array([0.03, 0.03, 0.075, 0.03, 0.03, 0.075])
H = HPolyhedron(A1, b1)
V = VPolytope(H)
print(V.vertices())
```
And here is a deepnote link with that code:
https://deepnote.com/workspace/robot-8b6e-0c23709f-282f-4cb6-9f2c-5f0f6b6ae534/project/01-Introduction-Duplicate-8da81b4c-e019-405e-9890-ed0632b1892c/notebook/intro-a15aa6c570764ee3a4f8427b456f4208

I don't know if this should be a separate issue, but also the `tol` parameter when converting in the other direction (VPolytope -> HPolyhedron), is not exposed in the python bindings and is probably similarly relevant when working with smaller (yet physically plausible manipuland-sized) objects. 

### Version

1.25.0

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

pip install drake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by cohnt**
The logic used to construct the affine hull has an error where not all the vectors of the basis will be found. A minimum example that causes this failure is included in the test cases.

The fix is to replace the iteration over the standard basis vectors with iterating over the perpendicular space of the current basis. That way, if basis vectors are added that make it infeasible to move along one of the later basis vectors, we instead try to move along a different direction, discovering a full basis in all cases.

Resolves #20985. cc @chsahit

+@hongkai-dai for feature review, since you're familiar with this class?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009)

### CODE REVIEW

**Comment by cohnt** [comment]
-@hongkai-dai for feature review
+@alexandreamice for feature review

**Review by AlexandreAmice — COMMENTED** [review]
I sent you a PR that avoids all matrix factorizations. 

Also, please use orthogonal complement, not perpendicular space.

I will review the tests once you get a chance to see my changes.

> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-:-Nra05wu5x2aFmFmyrOE:bseoqws)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/hpolyhedron.h` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-Nr_tq6GCrOeH8lMBBun:-Nr_tq6GCrOeH8lMBBuo:b8bqqdz) ([raw file](https://github.com/RobotLocomotion/drake/blob/71cb0f1ed80d56f550b95e837ff18e5efcb76753/geometry/optimization/hpolyhedron.h#L49)):*
> ```objc
>   coordinate system of its affine hull. `tol` specifies the numerical tolerance
>   used in the computation of the affine hull. See the documentation of
>   AffineSubspace for  tighter tolerance can be used with commercial solvers
> ```

nit: whitespace



_Suggestion:_
```objc
for tighte
```

**Review by cohnt — COMMENTED** [review]
Merged the PR, updated throughout to use orthogonal complement instead of perpendicular space, and fixed some tolerance issues in the test cases.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-:-Nrl3fToBfURilxPjZjs:b-cehug9)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/hpolyhedron.h` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-Nr_tq6GCrOeH8lMBBun:-Nrl3kN68EQj5MJ8xWwi:bdt9mng) ([raw file](https://github.com/RobotLocomotion/drake/blob/71cb0f1ed80d56f550b95e837ff18e5efcb76753/geometry/optimization/hpolyhedron.h#L49)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: whitespace
</blockquote></details>

Fixed. Also, the grammar was a bit odd.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-:-Nrl503Q42TH1qe91sCm:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/affine_subspace.cc` line 131 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-Nrl4QqW-Wsks_pNCC-x:-Nrl4QqXEVPkNPgRLrQ2:bfkpin0) ([raw file](https://github.com/RobotLocomotion/drake/blob/efd01cc2ac68ca5f43fe534d1e6163cbb30acde3/geometry/optimization/affine_subspace.cc#L131)):*
> ```cpp
>         }
>         // Now that we've found a new basis vector, we break out of the inner
>         // loop, to compute a new basis for the orthogonal complement.
> ```

nit: Whoops, this comment is no longer relevant. 



_Code quote:_
```cpp
        // Now that we've found a new basis vector, we break out of the inner
        // loop, to compute a new basis for the orthogonal complement.
```
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 283 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-Nrl4yLo03t2dPlNzQJ1:-Nrl4yLo03t2dPlNzQJ2:bggo07d) ([raw file](https://github.com/RobotLocomotion/drake/blob/efd01cc2ac68ca5f43fe534d1e6163cbb30acde3/bindings/pydrake/geometry/test/optimization_test.py#L283)):*
> ```Python
>         vpoly = mut.VPolytope(np.array(
>             [[0., 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]))
>         hpoly = mut.HPolyhedron(vpoly=vpoly)
> ```

Can remove this line now.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/affine_subspace.cc` line 131 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-Nrl4QqW-Wsks_pNCC-x:-Nrl8SY15g4OlEEe6I_Y:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/efd01cc2ac68ca5f43fe534d1e6163cbb30acde3/geometry/optimization/affine_subspace.cc#L131)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: Whoops, this comment is no longer relevant.
</blockquote></details>

Done.
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 283 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-Nrl4yLo03t2dPlNzQJ1:-Nrl8Le_7TaK9fV8KE3T:b-r5vi3a) ([raw file](https://github.com/RobotLocomotion/drake/blob/efd01cc2ac68ca5f43fe534d1e6163cbb30acde3/bindings/pydrake/geometry/test/optimization_test.py#L283)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can remove this line now.
</blockquote></details>

Why? We still provide tol as an optional argument.

**Review by AlexandreAmice — COMMENTED** [review]
+@jwnimmer-tri for platform. Thanks

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-:-NrlS2CeDpWc8DFIb-n9:be9ymu0)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-NrlYyjI7TTDBFD1z8Uq):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit When you choose a subject line for the final merge, instead of saying only "Fix Logic Bug in Affine Hull Construction" it would help to contextualize which subsystem this applies to.  Some mention of "convex sets" or "geometry optimization" or etc.
</blockquote></details>

Will do.

Perhaps something like "Fix a logic bug when constructing an AffineSubspace as the affine hull of a ConvexSet." ?
___
*[`geometry/optimization/affine_subspace.cc` line 134 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-NrlahS9E4QvHGyBmdUk:-Nrlgh6iBpthgF4m5Ce2:b-89vk8j) ([raw file](https://github.com/RobotLocomotion/drake/blob/9af85e9394b638bfa26f347cf94d05fb2c6c649e/geometry/optimization/affine_subspace.cc#L134)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm having a hard time following in what sense "dimension_added" is carrying any meaning here.  This is only place that sets it to false, so it seems to me like this should just say `break;`, and we can ditch the variable?  Nothing on this line seems to relate to "was anything added yes / no".
</blockquote></details>

I'm fine with getting rid of the variable and just `break`ing. @AlexandreAmice, was there a specific reason not to do that?
___
*[`geometry/optimization/hpolyhedron.h` line 52 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-NrlYYwz7Q6NPsHr1rZZ:-NrlfaL65g45WHpXIEAx:bt2vr1b) ([raw file](https://github.com/RobotLocomotion/drake/blob/9af85e9394b638bfa26f347cf94d05fb2c6c649e/geometry/optimization/hpolyhedron.h#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit No `const` in header file pass-by-value:

https://drake.mit.edu/styleguide/cppguide.html#Use_of_const
</blockquote></details>

Fixed.
___
*[`geometry/optimization/test/affine_subspace_test.cc` line 607 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-Nrl_f0BBIFLaO17fCHC:-NrlfgfYAdUyvKJLnuhe:b88eqcn) ([raw file](https://github.com/RobotLocomotion/drake/blob/9af85e9394b638bfa26f347cf94d05fb2c6c649e/geometry/optimization/test/affine_subspace_test.cc#L607)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Should this `as2` be `as3`?

(This is why I try personally to avoid introducing variable names that only differ by a tiny integer; it's very easy to typo it and not notice.  Some redundancy in the naming can help a lot, e.g., "foo" vs "bar" or "alpha, bravo, charlie" .  Or breaking into separate GTEST_TEST cases so it can just be plain `A` and `b` everywhere.)
</blockquote></details>

Yes, good catch! Fixed.
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 283 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-Nrl4yLo03t2dPlNzQJ1:-Nrlh4Hc4UKXkRLlJLRa:bnntntm) ([raw file](https://github.com/RobotLocomotion/drake/blob/efd01cc2ac68ca5f43fe534d1e6163cbb30acde3/bindings/pydrake/geometry/test/optimization_test.py#L283)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The line 283 (the first call, without a tol) is not strictly necessary per our habits.  We don't usually unit-test that the arguments with default values can be omitted.  Usually the presence of a default is sufficiently obvious from a plain reading of the bindings, so we don't need to invest test code to flag regressions.  People will probably spot them with their eyeballs.

It's also fine it you want to keep it this way.  It's not too much cost in terms of code bloat to have this test stay around.
</blockquote></details>

I'll keep it then.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/affine_subspace.cc` line 134 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-NrlahS9E4QvHGyBmdUk:-NrlibXe7b4LtFyI9Dhw:baiqoy2) ([raw file](https://github.com/RobotLocomotion/drake/blob/9af85e9394b638bfa26f347cf94d05fb2c6c649e/geometry/optimization/affine_subspace.cc#L134)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

I'm fine with getting rid of the variable and just `break`ing. @AlexandreAmice, was there a specific reason not to do that?
</blockquote></details>

No we can just break here. I thought we would need that variable but turns out there is no need to keep track of it.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/affine_subspace.cc` line 134 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21009#-NrlahS9E4QvHGyBmdUk:-Nrlp_pgDcK-1SgtJqkc:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9af85e9394b638bfa26f347cf94d05fb2c6c649e/geometry/optimization/affine_subspace.cc#L134)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

No we can just break here. I thought we would need that variable but turns out there is no need to keep track of it.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21009)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by cohnt** [comment]
Platform reviewer: when squashing and merging, please use the commit message "Fix a logic bug when constructing an AffineSubspace as the affine hull of a ConvexSet."

**Pull request merged**
