### PR TITLE
[doc] Add macOS stable releases for pip wheels

### LINKED ISSUE #15958: Publish macosx pip wheels
For our stable releases, we should upload a macOS-compatible wheel to PyPI.

- Highest priority is Python 3.9 (cp39-none, Homebrew default).
- Lower priority is Python 3.8 (cp38-none, Big Sur and Monterey default).
- We do not plan to ship Python 3.7 (cp37-none, Catalina default).

It's probable that we should improve our whl release automation, testing, and CI prior to attempting this.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
I've uploaded a v1.5.0 wheel using this process.

Closes #15958.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17619)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@svenevs and +@rpoyner-tri for all reviews, please; have a look at the portions you're familiar with.

**Review by svenevs — COMMENTED** [review]
:lgtm: with some small suggestions, nice to see the staging job is working as expected!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17619#-:-N7q6j_v310N6zNZRYHa:b-hbopu7)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`doc/_pages/release_playbook.md` line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17619#-N7q5zRg0Utwjx3jhYDz:-N7q5zRg0Utwjx3jhYE-:b-7suujo) ([raw file](https://github.com/robotlocomotion/drake/blob/22e6001c68064c4aff8b7b27eff94b831358cf68/doc/_pages/release_playbook.md#L276)):*
> ```Markdown
> ### Mac wheel builds
> 
> 1. Open the [Jenkins Wheel Staging](https://drake-jenkins.csail.mit.edu/view/Wheel/job/mac-big-sur-unprovisioned-clang-wheel-staging-snopt-mosek-release/) page.
> ```

FYI I added a staging view in the event that we want to add more staging jobs in the future (e.g., linux wheels and/or apt). https://drake-jenkins.csail.mit.edu/view/Staging/
___
*[`doc/_pages/release_playbook.md` line 280 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17619#-N7q5fOv0eAzV1bv8Krm:-N7q5fOv0eAzV1bv8Krn:bsc5ndq) ([raw file](https://github.com/robotlocomotion/drake/blob/22e6001c68064c4aff8b7b27eff94b831358cf68/doc/_pages/release_playbook.md#L280)):*
> ```Markdown
>    will use your GitHub credentials.
> 3. Click "Build with Parameters".
> 4. Change "sha1" to the **git sha** corresponding to ``v1.N.0`` and
> ```

Minor, I think the full sha is required, should that be explained?
___
*[`doc/_pages/release_playbook.md` line 283 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17619#-N7q6XEW5GTeHNjieuA2:-N7q6XEW5GTeHNjieuA3:b8udwcb) ([raw file](https://github.com/robotlocomotion/drake/blob/22e6001c68064c4aff8b7b27eff94b831358cf68/doc/_pages/release_playbook.md#L283)):*
> ```Markdown
>    "release_version" to ``1.N.0``.
> 5. Click "Build"; the build will finish after approximately 75 minutes.
> 6. After it's finished, open the "Console Output" and find the URL of the built
> ```

FYI easiest way to find macOS uploads is searching the log for `/usr/local/bin/aws`, on linux `/usr/bin/aws`.  May be helpful to note here since the logs are quite loggy.

**Review by svenevs — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17619)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17619#-:-N7qZmgG6XSdxB0dC0rl:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),svenevs (waiting on @jwnimmer-tri)

**Pull request merged**
