### PR TITLE
mkdoc: Fix comment handling edge cases

### LINKED ISSUE #12445: Suggested improvement for `mkdoc.py`
A suggestion to improve: https://github.com/RobotLocomotion/drake/blob/master/third_party/com_github_pybind_pybind11/mkdoc.py#L275

```
    # Convert `typewriter` to ``typewriter``.
    rr = r'([\s\-,;:!.()]+)`([^\s`]|[^\s`].*?[^\s`])`([\s\-,;:!.()]+)'
    while re.search(rr, s):
        s = re.sub(rr, r'\1``\2``\3', s, flags=re.DOTALL)
```

(I noticed that the current version only converts the first `typewriter` of each line, at least on my ubuntu machine)

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Closes #12445

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12519)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Er, forgot Reviewable doesn't do the issue cross referencing. Re-stating in pure GitHub comment: pybind/pybind11#1896

**Comment by jwnimmer-tri** [comment]
As an aside, I would like to see the commit title be useful.  "Fix a bug in [filename]" conveys very little information.  Maybe "mkdoc: Fix comment handling edge cases" or something.

**Comment by m-chaturvedi** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12519#-Lxbwvp27QhQ4LnxFzvt:-LxcDrYQDGAPV1RWwXBZ:b-q46uoo) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Fine by me (that's why I gave this the magic reviewable "FYI" :-) ), just wanted to be sure it had been thought about.
</blockquote></details>

@ericcousineau-tri 
I think there the first problem mentioned in the issue is irrelevant.
From what I understand, the complainant is meaning that the regex doesn't replace all the `typewriters`,  and they use the for loop to 'solve' the problem.  
In fact, python's `sub` replaces all the occurrences found, to start-with (by default `count=0`). 
https://docs.python.org/3/library/re.html#re.sub

Why this works, even when our comment is not ending with anything in `[\s\-,;:!.()]`is because we're adding a `\n` if the comment is non-empty here: 
https://github.com/RobotLocomotion/drake/blob/master/third_party/com_github_pybind_pybind11/mkdoc.py#L245

I have updated the PR, with this understanding. 

---

**Comment by EricCousineau-TRI** [comment]
___
*[tools/workspace/pybind11/test/mkdoc_test.py, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12519#-LxbvQIl8VKYIMGtIdaz:-LxcVSxkCJqogyMMsxku:b-7orpyc) ([raw file](https://github.com/robotlocomotion/drake/blob/9c58d95036afcb06db82980a120fb2beb52e9e28/tools/workspace/pybind11/test/mkdoc_test.py#L5)):*
<details><summary><i>Previously, m-chaturvedi (Mmanu Chaturvedi) wrote…</i></summary><blockquote>

OK, I tried to add a test from what I understand, please let me know if this is what you meant.
</blockquote></details>

To address Grant's comment, I think this test file could be clarified with a `TODO` to test full `mkdoc` functionality (such as symbol association), and refer readers to the Christmas tree test for symbol association in the meantime.

That, or even better, `process_comment` is moved to its own file (perhaps `cc_doxygen_to_rst.py`) under `drake/tools/workspace/pybind11`, and the test file focuses only on that information.

**Comment by m-chaturvedi** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12519#-Lxbwvp27QhQ4LnxFzvt:-LxcXPtK5vL1JCuGBR-5:b-xuzraw) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Sweet, glad it simplified things!

Just to check, this specific discussion is about upstreaming; were you talking about the original issue?
If so, did you mean to respond to the regex bit below, or in the overall discussion?
</blockquote></details>

Sorry about that!  I meant to post in the box above this.  I was trying to say about the overall PR. 

---

**Comment by m-chaturvedi** [comment]
___
*[tools/workspace/pybind11/test/mkdoc_test.py, line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12519#-Lxce-WJA0zoa8T6AQvm:-LxceOUC1yadhLtXWnIV:b-lm7x8j) ([raw file](https://github.com/robotlocomotion/drake/blob/8c03af314bf5520ff93fd021982199e14105edde/tools/workspace/pybind11/test/mkdoc_test.py#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW It's perhaps best to explicitly refer to the filename as `sample_header_documentation_py_test`, but fine for now. Thanks!
</blockquote></details>

OK, yeah.  I just wanted to make sure that we have a permanent link, because a name is more time-dependent than a link, :).

**Comment by m-chaturvedi** [comment]
___
*[tools/workspace/pybind11/test/mkdoc_test.py, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12519#-LxbvQIl8VKYIMGtIdaz:-LxgEbdG9pGy8wEaiJB9:b1jeymd) ([raw file](https://github.com/robotlocomotion/drake/blob/9c58d95036afcb06db82980a120fb2beb52e9e28/tools/workspace/pybind11/test/mkdoc_test.py#L5)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, my bad - thank you for explaining!
</blockquote></details>

Updated.  I am sorry about the misunderstanding.  I think the misunderstanding was in the functional vs unit-testing bit.
[ Also, I was thinking that maybe we should not hard-code the exact line numbers in the file, and do some pre-processing before using it in the tests.  Like we could use the delta from the previous comment.  ]

**Pull request merged**
