### PR TITLE
Polished rigid_body_plant_unit_test some.

### PR DESCRIPTION
**Pull request by liangfok**
Minor tweaks that help me better understand the code.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4289)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.

\CC: @edrumwri since I touched your code.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-:-KXkmF2Aq9qsplCs49Sq:bp7zdxx)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-KXkq8bQVv2kxsiGYSQN:-KXkq8bR2LziyIl2zYHF:bci77jf) ([raw file](https://github.com/robotlocomotion/drake/blob/5b6204e716c5caf7854183805634273c917a0c2b/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L163)):*
> ```cpp
> 
>         // TODO(edrumwri): Uncomment the following test when the quaternion
>         // derivative code is correct.
> ```

Reference #4121 here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-KXkq8bQVv2kxsiGYSQN:-KXkuVkSHSQx_FCHBog9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5b6204e716c5caf7854183805634273c917a0c2b/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L163)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Reference #4121 here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-:-KXlBVuLbJoONmSDaM9d:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. +@david-german-tri for platform review per rotation schedule.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-:-KXlC8Ydu1Txt_kxs5VP:bedqpo8)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-KXlChZYhGu9R7hY7Cvi:-KXlChZYhGu9R7hY7Cvj:b-epk6qo) ([raw file](https://github.com/robotlocomotion/drake/blob/bad2e273f990aedbb91816d9e5e054ea1daa609b/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L68)):*
> ```cpp
> }
> 
> // Tests the generalized velocities to generalized coordinates time
> ```

Missing a period. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-KXlChZYhGu9R7hY7Cvi:-KXlD3U56iGHIl69HN7Q:b-rstlbx) ([raw file](https://github.com/robotlocomotion/drake/blob/bad2e273f990aedbb91816d9e5e054ea1daa609b/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L68)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Missing a period. :)
</blockquote></details>

Hmm...where?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-KXlChZYhGu9R7hY7Cvi:-KXlDrRYBhgYF6iINoW5:b-i3gqse) ([raw file](https://github.com/robotlocomotion/drake/blob/bad2e273f990aedbb91816d9e5e054ea1daa609b/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L68)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Hmm...where?
</blockquote></details>

Sorry, my mistake- didn't see the comment continued on the next line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-KXlChZYhGu9R7hY7Cvi:-KXlE77hCdQGjzcFFecE:blyphgc) ([raw file](https://github.com/robotlocomotion/drake/blob/bad2e273f990aedbb91816d9e5e054ea1daa609b/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L68)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Sorry, my mistake- didn't see the comment continued on the next line.
</blockquote></details>

No problem!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289#-:-KXlOrBYjI0AMmn0GRMH:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4289)*

**Pull request merged**
