### PR TITLE
getting_help: Add hints for Binder / Colab

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
As motivated by: https://stackoverflow.com/q/66216899/7829525

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14660)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@soonho-tri for both reviews, please!

+(status: single reviewer ok) 
\cc @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14660#-:-MTknARq0bWUtS4a8cuU:biysobq)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14660#-:-MTl0xiw3DdkKgV9aD_R:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform)

___
*[doc/getting_help.rst, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14660#-MTl18A1Ddfi87U8q-Xh:-MTl18A1Ddfi87U8q-Xi:b-fj95t7) ([raw file](https://github.com/robotlocomotion/drake/blob/81b27887e6ffcf45133dd3cd81990e1b18859485/doc/getting_help.rst#L75)):*
> ```reStructuredText
>     -   A version of your notebook that we can access. Please check this by
>         re-visiting your URL in a private browsing window. (You can add
>         notebooks to public GitHub Gists.)
> ```

FYI, In case you want to add more instructions, I think we can add a link, for example, https://medium.com/deena-does-data-science/jupyter-notebook-extensions-e6b57d004e8e

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14660)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform)

___
*[doc/getting_help.rst, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14660#-MTl18A1Ddfi87U8q-Xh:-MTl9dLH6fj600Yo7S7Z:bduwnk0) ([raw file](https://github.com/robotlocomotion/drake/blob/81b27887e6ffcf45133dd3cd81990e1b18859485/doc/getting_help.rst#L75)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, In case you want to add more instructions, I think we can add a link, for example, https://medium.com/deena-does-data-science/jupyter-notebook-extensions-e6b57d004e8e 
</blockquote></details>

OK That article goes a bit beyond advice that I'd like to support (e.g. installing conda), and I don't have another one readily on-hand.

Will defer for now, but thank you!

**Comment by EricCousineau-TRI** [comment]
Skipping slow builds

**Pull request merged**
