### PR TITLE
adds python bindings to barycentric mesh and dynamic programming algorithms

### PR DESCRIPTION
**Pull request by RussTedrake**
(this time w/o the extra commit, now that #8066 has landed)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8069)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for feature review, please.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-:-L5JSZtD7DVL99twoDCH:b7kye1q)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/systems/BUILD.bazel, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K2VLamoPXBileXyYX:-L5K4RzYUJC32wGf-Gg7:b-wxmmju) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/systems/BUILD.bazel#L70)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Same as above: `cc_deps` should only include header-only libraries, to avoid ODR issues.
</blockquote></details>

(or rather, ODR violation-robust libraries)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8069)*

**Comment by RussTedrake** [comment]
Review status: 7 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[bindings/pydrake/BUILD.bazel, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K21jFWa9ZZsIajaDA:-L5KzzyRkhlTjVOxorRs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/BUILD.bazel#L87)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can this be removed? This should be incorporated into `//tools/install/libdrake:drake_shared_library`, which right now is included via `drake_pybind_library`.
</blockquote></details>

Done.

---

*[bindings/pydrake/BUILD.bazel, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K292feGmo16r0mNIV:-L5KzbOTayu6neMX_8ms:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/BUILD.bazel#L227)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can a mention of https://github.com/RobotLocomotion/drake/issues/8041 be made here?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/BUILD.bazel, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K2VLamoPXBileXyYX:-L5L-CKlWwTMy0SjWxU4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/systems/BUILD.bazel#L70)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

(or rather, ODR violation-robust libraries)
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/controllers_test.py, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K2p3_PYV5xYg7usT4:-L5L-S45MfRqF0G6o9H_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/systems/test/controllers_test.py#L35)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

If the scope of these imports is not being tested (as it is in `all_test`), can these imports be moved up to the top?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/controllers_test.py, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K3-I9_d03diBsEHJ7:-L5L-_lrsI23rGlcIa65:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/systems/test/controllers_test.py#L37)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can `cm` be aliased to `color_map`?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_test.py, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K3P7YBu3oGOantOTY:-L5L-kfz4WMbwyYhk9Vq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/test/math_test.py#L9)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can these be methods be changed to `snake_case`?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_test.py, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K3RmUlDioVhjfIh_w:-L5L-yNPPNw4I2KqyAOe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/test/math_test.py#L14)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can these be changed from `self.assertTrue(a == b)` to `self.assertEquals(a, b)`?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_test.py, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K3d3OvNrKszmlEfQw:-L5L0Fz8AYYdIRX_AEkW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/test/math_test.py#L18)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Would it be difficult to test all values of `Eval`? perhaps `eval_values_expected`, and use `np.allclose`?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_test.py, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8069#-L5K3XquTWveRJgJREwQ:-L5L0IW75eItAXFhF2OF:b-gps8dr) ([raw file](https://github.com/robotlocomotion/drake/blob/14f35f1779d5c3ee8be24606b84b5d7657055e6f/bindings/pydrake/test/math_test.py#L45)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can this dead code be removed?
</blockquote></details>

done.  (I had left it in intentionally for the future debugger, but i guess i agree)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8069)*

**Comment by RussTedrake** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8069)*

**Comment by RussTedrake** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
I am able to run `math_test` on our local Mac machine; however, I do get the same failures with linting tests (where `math` is once again shadowed).

**Pull request closed without merging**
