### PR TITLE
Make installing documentation prereqs optional

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #13832. CI will need some tweaks once this merges.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14168)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14168)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14168#-MJc3F9R3iqiY7gE0Nxt:-MJc3F9R3iqiY7gE0Nxu:b-2u7y4d) (no related file):*
> CI will need some tweaks once this merges.

Can you elaborate on what is happening / will happen?

Is the general idea that "linux-bionic-gcc-bazel-experimental-documentation" will become Required?

Will there be different AMI for `--with-doc-only` used only for that build, so that we can prove that the "manual" tags are precise?

I looked at the console output of the linux-bionic-gcc-bazel-experimental-documentation build of this PR.  I think it might be difficult, if that build fails, for a developer to determine what failed, or what commands to run to reproduce locally.  Could we add more information to that script to highlight more carefully what commands it is running?

---
___
*[bindings/pydrake/doc/BUILD.bazel, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14168#-MJcGoB09rZeerBiEIET:-MJcGoB09rZeerBiEIEU:br0b8s0) ([raw file](https://github.com/robotlocomotion/drake/blob/09268a54f0582aa415f66d828d185452caef6749/bindings/pydrake/doc/BUILD.bazel#L25)):*
> ```Starlark
>         # network; we should fail-fast if someone tries to turn them on.
>         "block-network",
>         "manual",
> ```

_Meta_ Throughout this PR, anywhere we add a "manual" tag we should have a comment explaining why (or a citation to a consolidated paragraph that explains why, if it's long).

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14168)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jamiesnape and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14168#-MJc3F9R3iqiY7gE0Nxt:-MJcMU6E2CFSI2A5o9tB:b-l8z6sx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> CI will need some tweaks once this merges.

Can you elaborate on what is happening / will happen?

Is the general idea that "linux-bionic-gcc-bazel-experimental-documentation" will become Required?

Will there be different AMI for `--with-doc-only` used only for that build, so that we can prove that the "manual" tags are precise?

I looked at the console output of the linux-bionic-gcc-bazel-experimental-documentation build of this PR.  I think it might be difficult, if that build fails, for a developer to determine what failed, or what commands to run to reproduce locally.  Could we add more information to that script to highlight more carefully what commands it is running?
</blockquote></details>

The output is certainly going to need to be augmented with the three or four different bazel commands that are run. Whether we actually make linux-bionic-gcc-bazel-experimental-documentation, required, I am still pondering. The actual documentation building does not cache, so the build time is longer. We can certainly have provisioned and unprovisioned builds if necessary, though an extra AMI is quite a lot of overhead. I am open to suggestions.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14168)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14168#-MJc3F9R3iqiY7gE0Nxt:-MJcOk-BC9anOE-mEeAq:b61lr10) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

The output is certainly going to need to be augmented with the three or four different bazel commands that are run. Whether we actually make linux-bionic-gcc-bazel-experimental-documentation, required, I am still pondering. The actual documentation building does not cache, so the build time is longer. We can certainly have provisioned and unprovisioned builds if necessary, though an extra AMI is quite a lot of overhead. I am open to suggestions.
</blockquote></details>

If we run _only_ the doc-related commands (and not `test //...` prior to them) on the `-documentation` builds, that might be a lot faster?  (The pydrake compilation would still be cached?)

I'd like to have some CI coverage that the typical case (when a user does _not_ opt-in to the `--with-doc` during install_prereqs), that `test //...` still passes.  I think that means we want a sans-doc AMI for most builds.  I'll give more thought about how to supplement that with doc builds.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14168)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14168#-MJc3F9R3iqiY7gE0Nxt:-MJcdLZ34ANTyXqup16k:b1mszq7) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If we run _only_ the doc-related commands (and not `test //...` prior to them) on the `-documentation` builds, that might be a lot faster?  (The pydrake compilation would still be cached?)

I'd like to have some CI coverage that the typical case (when a user does _not_ opt-in to the `--with-doc` during install_prereqs), that `test //...` still passes.  I think that means we want a sans-doc AMI for most builds.  I'll give more thought about how to supplement that with doc builds.
</blockquote></details>

For doc builds, maybe a fair starting point is to have only:

1. linux-bionic-unprovisioned-gcc-bazel-experimental-documentation
2. linux-bionic-unprovisioned-gcc-bazel-continuous-documentation
3. linux-bionic-unprovisioned-gcc-bazel-nightly-documentation

Where (3) is the only one that actually pushes to the website, where (2) is always running, and where (1) is opt-in during pre-merge.

If find too many post-merge failures of the continuous docs build, we'll have to escalate it to pre-merge.

---

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14168)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jamiesnape and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14168#-MJc3F9R3iqiY7gE0Nxt:-MJgez7U99PFjwTNf89K:b-kfqakz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For doc builds, maybe a fair starting point is to have only:

1. linux-bionic-unprovisioned-gcc-bazel-experimental-documentation
2. linux-bionic-unprovisioned-gcc-bazel-continuous-documentation
3. linux-bionic-unprovisioned-gcc-bazel-nightly-documentation

Where (3) is the only one that actually pushes to the website, where (2) is always running, and where (1) is opt-in during pre-merge.

If find too many post-merge failures of the continuous docs build, we'll have to escalate it to pre-merge.
</blockquote></details>

That sounds about what I was thinking. I think we are on the same page.

---

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature review, modulo the discussion below.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14168#-:-MJh7eMN1BzB8iSdB6MU:b-dr1snz)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14168#-MJc3F9R3iqiY7gE0Nxt:-MJh7cj0CYV8Htd-5JzK:b-d3pzei) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

That sounds about what I was thinking. I think we are on the same page.
</blockquote></details>

I'm OK to merge this PR once the following are done:

(a) Unfinished tasks are filed as a issues (or subtasks within some issues):
- Add "continuous" build ("2." above)
- Task to speed up doc builds
- Task to remove docs prereqs from non-documentation CI images

(b) Confirm for me that all of the build targets and tests newly labelled as "manual" as of this PR are covered by the "nightly documentation" CI build steps already.  It seems like `bazel build //doc:serve_sphinx //bindings/pydrake/doc:serve_sphinx` might be missing.

---

**Comment by jamiesnape** [comment]
Looks like I need this for the Mac fixes due to our Sphinx formula using Python 3.8.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please
@drake-jenkins-bot llinux-focal-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot llinux-focal-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-documentation please.

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-bionic-unprovisioned-gcc-bazel-experimental-documentation/1/console and https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-experimental-documentation/1/console look good to me, so I think that covers (2) above.

**Comment by jamiesnape** [comment]
I will add continuous and nightly as soon as we hit merge. Doc builds are taking 18-19 minutes, so maybe that is fast enough. Unless we provision images, I can't see us speeding that up by much more than a minute or two.

**Comment by jamiesnape** [comment]
+(priority: high) since this helps the Mac fire.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14168#-:-MLmvEF_0G9CKVfb64ZD:bybe5xg)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14168#-MJc3F9R3iqiY7gE0Nxt:-MLmtxVF7wKi2LuQEoun:bffq9t3) (no related file):*
> (a) Unfinished tasks are filed as a issues (or subtasks within some issues):
> Add "continuous" build ("2." above)

OK _"I will add continuous and nightly as soon as we hit merge."_

> Task to speed up doc builds

OK We agree to skip this for now.  We can open a ticket with specific problems in the future, if we need one.

> Task to remove docs prereqs from non-documentation CI images

OK => #14310

> (b) Confirm for me that all of the build targets and tests newly labelled as "manual" as of this PR are covered by the "nightly documentation" CI build steps already.  It seems like bazel build //doc:serve_sphinx //bindings/pydrake/doc:serve_sphinx might be missing.

This seems like it's not done yet?  We are running the `gen...` targets in CI, but the targets I listed above are different.  To merge this urgent PR, maybe this should turn into a follow-up issue instead.

---

**Review by sherm1 — COMMENTED** [review]
The change looks fine and matches the recipe in #13832. I don't understand its significance though -- it seems to introduce manual steps where there were none before. However, I will defer to feature review that this is appropriate, so platform :lgtm:.

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14168#-:-MLnPOd_9CqotoSyXPFm:b-v4xddi)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Comment by jamiesnape** [comment]
> This seems like it's not done yet? We are running the gen... targets in CI, but the targets I listed above are different. To merge this urgent PR, maybe this should turn into a follow-up issue instead.

https://github.com/RobotLocomotion/drake-ci/blob/425c8239e235a46498e682f6facbac43b03b0334/driver/configurations/bazel/step-build.cmake#L58 has `//bindings/pydrake/doc:serve_sphinx` and `//doc:serve_sphinx`.

**Pull request merged**
