### PR TITLE
Fix yaml_load test for Xcode

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4618)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-xcode-experimental please

**Comment by jwnimmer-tri** [comment]
Platform :lgtm: assuming it gets an appropriate feature review and passes CI.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4618#-:-K_1BRF-59ag6bQfNruk:b-4a90g3)*

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by jamiesnape** [comment]
Unfortunately looks like this isn't going to work.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-xcode-experimental please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4618#-:-K_4zXNtCnabWbuBtzyX:bnfp4nl)*

**Pull request merged**
