### PR TITLE
gitignore: Add Python bytecode, due to implicit Python path behavior

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates #10996

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11004)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Ah, sorry!

The repro for the Sphinx docs, before #10998 @ 56b0d229, was what Russ mentioned #10996:
```
$ bazel run //doc:serve_sphinx
# Or: ./bazel-bin/doc/serve_sphinx
$ ls doc/*.pyc
```

I didn't see anything crop up from `bazel test` or `bazel build`.

**Comment by jwnimmer-tri** [comment]
But #10998 was merely a bug in our imports.  If our imports are correct, is there any repro?

**Comment by EricCousineau-TRI** [comment]
> If our imports are correct, is there any repro?

At present, I didn't see any bytecode litter when running `bazel test --cache_test_results=false //...`; however, I'd still like them to be ignored at some point.
When should we have them be ignored? After we don't see any `*.pyc` files crop up for a few weeks / months?

**Comment by jwnimmer-tri** [comment]
That's where we disagree.  I think that they should not be ignored -- I think they should never appear in the first place, ever!  To help enforce that, we should _not_ add them to gitignore, so that when something breaks, we find out about it.  Would you be satisfied using the user-specific or checkout-specific gitignore features, instead?

**Comment by EricCousineau-TRI** [comment]
Yeah, I'd be fine with that!

However, I'm still not fine with the presently huge scope of our `.gitignore` - would you mind if I filed an issue / PR to minimize the number of things we're ignoring? (things that probably should not be there, or belong in user-specific gitignore files?)

**Comment by jwnimmer-tri** [comment]
Yes, I'd happily support housecleaning on the current gitignore(s).

**Comment by EricCousineau-TRI** [comment]
You, sir, have yourself a deal!

**Pull request closed without merging**
