### PR TITLE
Updates license of all drake-distro/ros packages to be BSD-3-Clause.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves the drake-distro/ros portion of #4045.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5803)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please.

**Comment by liangfok** [comment]
+@jamiesnape for feature review please.
+@ggould-tri for platform review please.

Thanks!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5803#-:-KhXqYcjSovJZnaNlew2:b-rp02ij)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5803#-:-KhXqpCRipsFGI74lwf9:bnfp4nl)*

**Comment by ggould-tri** [comment]
I concur that Liang is sole author and can relicense these files.  :lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5803#-:-KhYD097mMEDq9U68M4m:bkk5ixh)*

**Pull request merged**
