### PR TITLE
pydrake systems: Fix mis-directed binding `System.get_num_output_ports`

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Found this while reviewing #8936 - whoops!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8938)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@sherm1 for both reviews, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8938#-:-LEH5FgF59cKoCtkSk3L:b-3q8wn7)*

**Comment by sherm1** [comment]
:lgtm: x 2

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8938#-:-LEH8_eK8ThpvvTnh1f3:b4xzgsb)*

**Comment by sherm1** [comment]
(merge pending CI)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8938#-:-LEH8eST9PlrPlyi5vFg:bich4j3)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
Just a flake. Normally GitHub's problem.

**Pull request merged**
