### PR TITLE
[pydrake] Add symbolic.Expression.Unapply

### LINKED ISSUE #16013: Symbolic visitor in pydrake
As best I can tell, there is no way to visit or otherwise structurally decompose a [`pydrake.symbolic.Expression`](https://drake.mit.edu/pydrake/pydrake.symbolic.html#pydrake.symbolic.Expression).  This means that any operations (other than arithmetic) that a user wants to do on an Expression need to be added as member functions, instead of being defined externally.

In C++ we have [`drake::symbolic::VisitExpression`](https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1symbolic.html#ab58092344918003fc7e186b1c57bbc7f), but it is not bound in pydrake (and probably should not be, anyway -- we shouldn't expose the `ExpressionCell` hierarchy).

I think we should be able to come up with a more Pythonic technique for visiting / decomposing an Expression.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #16013.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16014)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16014#-:-MnaN15645cZGR42ll-J:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/symbolic_py.cc, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16014#-MnaLVRf63GYi-8N7vz0:-MnaLVRgC95SZVFIhg7B:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8e8d46089adea8092d0f57acf251fc6ef095f2/bindings/pydrake/symbolic_py.cc#L7)):*
> ```cpp
> #include "fmt/ostream.h"
> #include "pybind11/eigen.h"
> #include "pybind11/eval.h"
> ```

unused?

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule (tomorrow is OK), please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16014#-:-MnaVb0n71Z0Z4EKNo6f:beokwyz)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[bindings/pydrake/symbolic_py.cc, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16014#-MnaLVRf63GYi-8N7vz0:-MnaVUYXDm5lwPBpq6_I:b-4nudoo) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8e8d46089adea8092d0f57acf251fc6ef095f2/bindings/pydrake/symbolic_py.cc#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Yes!

My original implementation was a lot more ... "creative", shall we say.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: platform, with nit on public API and nit on testing

> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16014#-:-MnfUYiY4Wf5wC3brxEr:byhnuf6)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/symbolic_py_unapply.cc, line 26 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16014#-MnfTXnOEgggBe8EzXM_:-MnfTXnP0i4BLnOwnQT0:bpup2qt) ([raw file](https://github.com/robotlocomotion/drake/blob/27ba3e7fe0dc6a744220c71066bfdbb856a00448/bindings/pydrake/symbolic_py_unapply.cc#L26)):*
> ```cpp
>       return m.attr("acos");
>     case ExpressionKind::Add:
>       return m.attr("_reduce_add");
> ```

nit By returning a direct reference to `_reduce_add`, it's unclear if this is intended to be public API. (A user can very easily inspect this object, and then use it for value comparison, etc.).

Consider hoisting this to public API, or clarify that it is unstable.
___
*[bindings/pydrake/test/symbolic_test.py, line 1513 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16014#-MnfU2OLBUPvI6eJ9FBE:-MnfU2OLBUPvI6eJ9FBF:bd6cpen) ([raw file](https://github.com/robotlocomotion/drake/blob/27ba3e7fe0dc6a744220c71066bfdbb856a00448/bindings/pydrake/test/symbolic_test.py#L1513)):*
> ```Python
>         for e in expressions:
>             with self.subTest(e=e):
>                 self._check_one_round_trip(e)
> ```

nit While this is good for coverage, I could make this test pass by replacing `Unapply` with `lambda e: ((lambda: e), ())`.

Consider adding a test that compares each element of decomposition for a slightly nontrivial expression:
```
def test_structure(self):
    ...
    ctor, args = e.Unapply()
    self.assertIs(ctor, Expression)
    self.assertEqual(args, (exp, e_x))
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16014)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/test/symbolic_test.py, line 1513 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16014#-MnfU2OLBUPvI6eJ9FBE:-MnfUmxrC-6M4zFX9v-n:boz9u31) ([raw file](https://github.com/robotlocomotion/drake/blob/27ba3e7fe0dc6a744220c71066bfdbb856a00448/bindings/pydrake/test/symbolic_test.py#L1513)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit While this is good for coverage, I could make this test pass by replacing `Unapply` with `lambda e: ((lambda: e), ())`.

Consider adding a test that compares each element of decomposition for a slightly nontrivial expression:
```
def test_structure(self):
    ...
    ctor, args = e.Unapply()
    self.assertIs(ctor, Expression)
    self.assertEqual(args, (exp, e_x))
```
</blockquote></details>

Ah, `test_replace` would fail. But perhaps something more direct is a bit more digestible.

(Resolving)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16014)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[bindings/pydrake/symbolic_py_unapply.cc, line 26 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16014#-MnfTXnOEgggBe8EzXM_:-MnfYvLO49UsAkysS5F5:b-37ajet) ([raw file](https://github.com/robotlocomotion/drake/blob/27ba3e7fe0dc6a744220c71066bfdbb856a00448/bindings/pydrake/symbolic_py_unapply.cc#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit By returning a direct reference to `_reduce_add`, it's unclear if this is intended to be public API. (A user can very easily inspect this object, and then use it for value comparison, etc.).

Consider hoisting this to public API, or clarify that it is unstable.
</blockquote></details>

My design intent is that:

(1) the return value from `Unapply(e)` will always be a `(callable, args)` pair such that `callable(*args)` will always succeed and re-create the given `e`, e.g., the round-trip test; and

(2) the user is not allowed to refer to `_reduce_add` by name since it starts with an underscore, e.g., they should not be doing `from pydrake.symbolic import _reduce_add`.

I am not sure how anything in the PR suggests otherwise, or leave any ambiguity?  I believe you that there is some ambiguity in your mind, and I'm happy to clarify the code or docs somehow, but I don't understand where the question is coming from.

The function _is_ "unstable" in the sense that we are free to change its name or implementation at any moment, but is _not_ "unstable" in the sense of intent (1) above -- it will always be _some_ callable that meets the contract of `Unapply`.

Maybe the missing point is that the `ctor` returned by `Unapply()` should not be used for any other purpose other than re-constructing the `args` it was mated with (possibly after transforming them first)?   I guess that was implied for me by the contract of `Unapply` -- it says what `ctor` will do (re-create `e`).  If a user presumes that is does more than that, maybe that's their own fault?

Anyway, some guidance would be appreciated.
___
*[bindings/pydrake/test/symbolic_test.py, line 1513 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16014#-MnfU2OLBUPvI6eJ9FBE:-Mnfatc2DAXYLeihdI_q:b62l18d) ([raw file](https://github.com/robotlocomotion/drake/blob/27ba3e7fe0dc6a744220c71066bfdbb856a00448/bindings/pydrake/test/symbolic_test.py#L1513)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, `test_replace` would fail. But perhaps something more direct is a bit more digestible.

(Resolving)
</blockquote></details>

Done.

I had gone back and forth on this.  The current tests captured the contract concisely.  If I were to try to spell out the exact return values and types of Unapply, I could be constraining its implementation beyond the contract.

However, this made me think a bit more about the contract I want.  I do think it's important to promise that certain kinds of terms always unpack to Expressions, so I've done that (and tested for it) now.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16014)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/symbolic_py_unapply.cc, line 26 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16014#-MnfTXnOEgggBe8EzXM_:-Mnflkln-AK73kagEaqN:b8f7rhc) ([raw file](https://github.com/robotlocomotion/drake/blob/27ba3e7fe0dc6a744220c71066bfdbb856a00448/bindings/pydrake/symbolic_py_unapply.cc#L26)):*
> [...] should not be used for any other purpose other than re-constructing [...]

Yeah, that'd help.

I was concerned about supporting a workflow where you may need to re-map `ctor` to something else, not just `args`. For example, a conversion routine from Drake symbolic to `sympy` expressions.
___
*[bindings/pydrake/test/symbolic_test.py, line 1540 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16014#-MnflTUxCCo72vMS0CSN:-MnflTUy21adeACMp18M:b-tvtria) ([raw file](https://github.com/robotlocomotion/drake/blob/a778574445c53c8c6009fda6986bf42e1351cb37/bindings/pydrake/test/symbolic_test.py#L1540)):*
> ```Python
>         self.assertGreater(len(args), 0)
>         for arg in args:
>             if isinstance(arg, float):
> ```

nit Logic a bit unclear, had to read docstring for `test_is_composite`.

To clarify, I believe you should be able to do the following:
```
self.assertIsInstance(arg, (float, sym.Expression))
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16014)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
