### PR TITLE
[FEM] Add mesh utilities to support FEM demo

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
In particular, add the ability to create a box volume mesh that is
discretized with the diamond cubic pattern.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14734)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@damrongguoy for feature review please, thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14734#-:-MUuNdN546am8TvIYh90:b316iip)* status: LGTM missing from assignee DamrongGuoy (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: with optional requests on the basis of `dev`.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14734#-:-MUvVg4m9eb_1i6AzCS9:b25acqp)* status: 8 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUv-H0t7DgExSUoH3c9:-MUv-H0t7DgExSUoH3cA:bgtn80h) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.h#L4)):*
> ```objc
> 
> #include <utility>
> #include <vector>
> ```

Nit: do we need `<utility>` and `<vector>` in this header file? If not, move them to the .cc file please.
___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUv0Cgz6arxUaQZPhyO:-MUv0Cgz6arxUaQZPhyP:b-yl8xen) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.h#L7)):*
> ```objc
> 
> #include "drake/common/default_scalars.h"
> #include "drake/common/eigen_types.h"
> ```

Nit: do we need `default_scalars.h` and `eigen_types.h` in this header file?  If not, move them to the .cc file please.

Minimizing #include in this header file will reduce chances of recompiling the dependent code of this header file.
___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUvBUAu2FSM5z48KXWl:-MUvBUAu2FSM5z48KXWm:b-a00x8e) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.h#L17)):*
> ```objc
> /** Generates a tetrahedral volume mesh of a given box by subdividing the box
>  into _rectangular cells_ (volume bounded by six axis-aligned faces) and
>  subdividing each rectangular cell into five tetrahedra. The output mesh will
> ```

Optional.  Perhaps you can add this to help the reader?

```C++
Two adjacent rectangular cells (sharing a rectangular face) are subdivided
in the patterns that are mirrored of the other.
```

You can point to an image file of the mesh too, if you have it.  We can have images in GitHub code review now.


___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUv4LANDFpBJX2QPKnX:-MUv4LANDFpBJX2QPKnY:b-piw4xd) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.cc#L44)):*
> ```cpp
>   }
>   return vertices;
> }
> ```

Optional.  Would something like this work?  I didn't try it, so I don't know for sure. Then, it's not copypasta anymore.
```C++
  // Initially generate vertices in box's frame B.
  std::vector<VolumeVertex<T>> vertices =
      geometry::internal::GenerateVertices<T>(box, num_vertices);
  for (VolumeVertex<T>& vertex : vertices) {
    // Transform to World frame.
    vertex = VolumeVertex<T>(X_WB * vertex.r_MV());
  }
  return vertices; // vertices in World frame.
```
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUv8yPMEJ0IHBKT79cn:-MUv8yPN8K4h3LsD9wga:b-dpic0y) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.cc#L110)):*
> ```cpp
>           elements.emplace_back(v[3], v[0], v[5], v[1]);
>           elements.emplace_back(v[0], v[6], v[3], v[5]);
>         }
> ```

Optional. Now that we allow PNG files (or JPEG) for documentation and code review.  Would you be interested to draw pictures of the even and the odd tetrahedrizations?  I suppose they are mirrors of the other.  You can put the image files in the newly created directory `multibody/fixed_fem/dev/images/` directory. In the future, we can move them to `geometry/proximity/images/`.

If I'll do it myself, I'll output a very coarse mesh (2 rectangular cells, 10 tetrahedra) to VTK (see geometry/proximity/mesh_to_vtk.h).  Use Paraview to "clip" and show the "odd" rectangular cell and then the "even" rectangular cell.  Please let me know if you need help with Paraview. 
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUvAAe07Ma-O9lb-Lb4:-MUvAAe07Ma-O9lb-Lb5:bpcefnr) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.cc#L110)):*
> ```cpp
>           elements.emplace_back(v[3], v[0], v[5], v[1]);
>           elements.emplace_back(v[0], v[6], v[3], v[5]);
>         }
> ```

Since this is `dev`, I do not manually check each tetrahedron one by one.  I trust the author.
___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUvQW9A9kA-7B-VNQSB:-MUvQW9A9kA-7B-VNQSC:b-20qi1u) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L30)):*
> ```cpp
> //   B. The mesh conforms to the box.
> //
> // @retval true when all conditions passed.
> ```

Optional.  If this code was copied and modified from an existing code, please briefly describe it here in one or two sentences.  It will aid refactoring in the future.
___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 116 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUvTBaZ9Z1S2PTuGYTQ:-MUvTBaZ9Z1S2PTuGYTR:bvwi93f) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L116)):*
> ```cpp
>   const RigidTransform<double> X_WB(Eigen::Quaternion<double>(1, 2, 3, 4),
>                                     Vector3d(1, 2, 3));
>   const Box box(Box::MakeCube(2 * dx));
> ```

Optional.  Perhaps use a "non-regular" box like `Box(1.2 * dx, 2.3 * dx, 3.5 * dx)` ?  Otherwise, since it's `dev`, a TODO like this would be fine too.
```C++
// TODO(xuchenhan-tri): More comprehensive test with a more random box like Box(0.12, 0.23, 0.35). 
```

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the quick review! I addressed the comments, PTAL, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14734#-:-MUyYUtu-4MN-WxTHsyW:buutx0l)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUv-H0t7DgExSUoH3c9:-MUyIeo_1wZRU2TLDTX1:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.h#L4)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Nit: do we need `<utility>` and `<vector>` in this header file? If not, move them to the .cc file please.
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUv0Cgz6arxUaQZPhyO:-MUyIg-K7f8-GfzqJ2kz:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.h#L7)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Nit: do we need `default_scalars.h` and `eigen_types.h` in this header file?  If not, move them to the .cc file please.

Minimizing #include in this header file will reduce chances of recompiling the dependent code of this header file.
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUvBUAu2FSM5z48KXWl:-MUyXE54E3Dct-L97dpm:b22fy6) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.h#L17)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional.  Perhaps you can add this to help the reader?

```C++
Two adjacent rectangular cells (sharing a rectangular face) are subdivided
in the patterns that are mirrored of the other.
```

You can point to an image file of the mesh too, if you have it.  We can have images in GitHub code review now.



</blockquote></details>

Done, I also added an image file, PTAL.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUv4LANDFpBJX2QPKnX:-MUyJnf80czl-lqCIVsB:b-9ohsnm) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.cc#L44)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional.  Would something like this work?  I didn't try it, so I don't know for sure. Then, it's not copypasta anymore.
```C++
  // Initially generate vertices in box's frame B.
  std::vector<VolumeVertex<T>> vertices =
      geometry::internal::GenerateVertices<T>(box, num_vertices);
  for (VolumeVertex<T>& vertex : vertices) {
    // Transform to World frame.
    vertex = VolumeVertex<T>(X_WB * vertex.r_MV());
  }
  return vertices; // vertices in World frame.
```
</blockquote></details>

Yes, this would work nicely, thank you!
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUv8yPMEJ0IHBKT79cn:-MUyXJW5-cyEy_NC5t_U:b10dzdb) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.cc#L110)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional. Now that we allow PNG files (or JPEG) for documentation and code review.  Would you be interested to draw pictures of the even and the odd tetrahedrizations?  I suppose they are mirrors of the other.  You can put the image files in the newly created directory `multibody/fixed_fem/dev/images/` directory. In the future, we can move them to `geometry/proximity/images/`.

If I'll do it myself, I'll output a very coarse mesh (2 rectangular cells, 10 tetrahedra) to VTK (see geometry/proximity/mesh_to_vtk.h).  Use Paraview to "clip" and show the "odd" rectangular cell and then the "even" rectangular cell.  Please let me know if you need help with Paraview. 
</blockquote></details>

I added an image file to show the tetrahedrization, PTAL.
___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUvQW9A9kA-7B-VNQSB:-MUyKlcx078b99muAnWz:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L30)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional.  If this code was copied and modified from an existing code, please briefly describe it here in one or two sentences.  It will aid refactoring in the future.
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 116 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUvTBaZ9Z1S2PTuGYTQ:-MUyLpF793DUG_eTdmbR:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L116)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional.  Perhaps use a "non-regular" box like `Box(1.2 * dx, 2.3 * dx, 3.5 * dx)` ?  Otherwise, since it's `dev`, a TODO like this would be fine too.
```C++
// TODO(xuchenhan-tri): More comprehensive test with a more random box like Box(0.12, 0.23, 0.35). 
```
</blockquote></details>

Done, thanks!

**Review by DamrongGuoy — COMMENTED** [review]
It looks good @xuchenhan-tri .

+@jwnimmer-tri for platform review please.  This is under `dev`.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14734#-:-MUymG0B1pKEuOJbXzTk:bmw26ba)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUvBUAu2FSM5z48KXWl:-MUylR8xDAGJ69WKQm3R:b-tnu4fi) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done, I also added an image file, PTAL.
</blockquote></details>

The image file looks good.  Thank you!
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14734#-MUv8yPMEJ0IHBKT79cn:-MUyliAs1WuQZlj-ssFS:b-9755fn) ([raw file](https://github.com/robotlocomotion/drake/blob/55c2888706d1037e69aa66387587616e886c7294/multibody/fixed_fem/dev/mesh_utilities.cc#L110)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I added an image file to show the tetrahedrization, PTAL.
</blockquote></details>

Thank you!

**Review by xuchenhan-tri — COMMENTED** [review]
-@jwnimmer-tri The platform review is not required since this is in `dev`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14734#-:-MUymrG_8DuQQAuGORyt:bprgk4n)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
