### PR TITLE
Cut rotation_conversion_test by a factor of 66 by sampling more coarsely

### PR DESCRIPTION
**Pull request by david-german-tri**
Specifically, reduce the number of samples from 20^4 to 7^4. This decreases runtime under valgrind from approximately an hour to approximately a minute.  Since it's right on the edge of "small" and "medium", up the size to "medium".

Contributes to #3873.

+@hongkai-dai for feature review, +@sherm1 for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3889)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
I prefer to choose an even number, so when the range goes from -x to x, the sample does not coincide with 0 (0 can be a special case sometimes, when singularity occurs). So maybe change `kSweepSize` from 7 to 6? Otherwise LGTM:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3889#-:-KUsCtH7vZSzGlVTnvqA:bn4bxlq)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3889#-:-KUsDGwL8IUeMu4S1xWi:bnfp4nl)*

**Comment by david-german-tri** [comment]
> So maybe change kSweepSize from 7 to 6?

Done.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3889#-:-KUsEU2MdMY-aABHuzUS:b-bcvgp2)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3889#-:-KUsby0wIQj5WycQmnAU:bnfp4nl)*

**Pull request merged**
