### PR TITLE
Remove  libgl1-mesa-dri and xvfb

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
From the Xenial installation script and the Trusty install instructions.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5207)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by BetsyMcPhail** [comment]
+@jamiesnape and +@jwnimmer-tri for review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5207#-:-KdBpb4rzZu0d5WvvexS:b-xx6tnb)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5207#-:-KdBs_mUgPnG6kwm9FPv:bnfp4nl)*

**Comment by patmarion** [comment]
hmm, i think director tests use xvfb?

**Comment by jamiesnape** [comment]
On CI, yes. This does not affect CI.

**Comment by jwnimmer-tri** [comment]
I guess it's okay to toss this.  I do think running offscreen tests locally (not in CI) is to our advantage, but we don't do it yet, and we can re-add appropriate instructions again once we need it.

See also #5216 which needs xvfb to run a test without DISPLAY, but the code is disabled so ¯\_(ツ)_/¯.

:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5207#-:-KdD6wHDlBw7n59U8byJ:b-6z6uha)*

**Pull request merged**
