### PR TITLE
Move DeformableBodyId/Index out of deformable_model.h

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20216)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews please (if there's time).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20216#-:-NejjyWD16zpvS_NzYXz:bemdqs9)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20216#-:-NejouKc4qmLBy-1Yltc:bnfp4nl)* status: 1 unresolved discussion

___
*[`multibody/plant/deformable_ids.h` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20216#-NejoUEDENY5waQZX0yS:-NejoUEDENY5waQZX0yT:b-emje42) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e3986b2b0486408baceee80d2ec97e67407d786/multibody/plant/deformable_ids.h#L13)):*
> ```objc
> using DeformableBodyId = Identifier<class DeformableBodyTag>;
> 
> /** Internally indexes deformable bodies, only used after Finalize(). */
> ```

BTW If "Internally" here is meant to indicate that users should not consume this class, our canonical phrasing for that is:

```c++
/** (Internal use only) Indexes deformable bodies, only ... */
```

If it's not meant to be "internal use only", then possibly another word than "internally" would help clarify.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20216)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

___
*[`multibody/plant/deformable_ids.h` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20216#-NejoUEDENY5waQZX0yS:-NejpXAaEqu8GpUOJ77z:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e3986b2b0486408baceee80d2ec97e67407d786/multibody/plant/deformable_ids.h#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If "Internally" here is meant to indicate that users should not consume this class, our canonical phrasing for that is:

```c++
/** (Internal use only) Indexes deformable bodies, only ... */
```

If it's not meant to be "internal use only", then possibly another word than "internally" would help clarify.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20216)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
