### PR TITLE
Add consolidated director-based image visualizer.

### LINKED ISSUE #6945: Write director script / plugin to visualize drake's image_t
Per f2f with @kunimatsu-tri, it'd be useful to have a utility from within Director to visualize drake's `image_t` (`robotlocomotion`) message type.

Steps:

- [x] Create a simple translator to `bot_core` image types to leverage existing code. (Hacky, but gets things done.)
- [ ] Create a simplified image viewer that is `bot_core` independent.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This consolidates all LCM image-viewing related functionality into a single script, to fully resolve #6945.

I'd like to separate camera intrinsics from the images for now, and layer on those properties (for `director`-based point cloud stuff) at a later point, using different components.
Presently, this is in `drake` to be consumed by `drake-visualizer`, but could potentially migrate to `director`.

\cc @patmarion Please let me know if anything in this setup looks off / has a funny code smell. Had to do a bit of hacking to get it to work on VTK 5 + 8.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7023)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-:-Ku0qVUXcLuqR8X1F8aL:b-1actl4)*

**Comment by kunimatsu-tri** [comment]
checkpoint.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/visualization/show_images.py, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1YBJM6TsFpvX1ldMr:-Ku1YBJM6TsFpvX1ldMs:b-z4zbqj) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L42)):*
> ```Python
> import robotlocomotion as rl
> 
> is_vtk_5 = vtk.vtkVersion().GetVTKMajorVersion() == 5
> ```

BTW, how about putting underscore at the beginning?
https://www.python.org/dev/peps/pep-0008/#global-variable-names

---

*[drake/systems/sensors/visualization/show_images.py, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1Xg7TiSHmBMi4-Xlm:-Ku1Xg7TiSHmBMi4-Xln:b-dgrt54) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L44)):*
> ```Python
> is_vtk_5 = vtk.vtkVersion().GetVTKMajorVersion() == 5
> 
> verbose = False
> ```

BTW, ditto.

---

*[drake/systems/sensors/visualization/show_images.py, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1XzSWpVzJ2jMziNNq:-Ku1XzSWpVzJ2jMziNNr:b-dgrt54) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L45)):*
> ```Python
> 
> verbose = False
> max_depth = -1  # m
> ```

BTW, ditto.

---

*[drake/systems/sensors/visualization/show_images.py, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1VDGK2FW05RiTLPyy:-Ku1VDGK2FW05RiTLPyz:b-q07lu0) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L47)):*
> ```Python
> max_depth = -1  # m
> 
> kDefaultChannel = "DRAKE_RGBD_CAMERA_IMAGES"
> ```

BTW, Drake follows PEP8 as Python style guide, and constants should be written in all capital letters with underscores separating words in PEP8: https://www.python.org/dev/peps/pep-0008/#constants

---

*[drake/systems/sensors/visualization/show_images.py, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1Yu406qyLk35WsuHC:-Ku1Yu406qyLk35WsuHD:b3eldeo) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L61)):*
> ```Python
>         Otherwise, it should return False.
>         """
>         raise Exception("Not implemented")
> ```

How about raising "NotImplementedError" instead?
https://docs.python.org/2/library/exceptions.html#exceptions.NotImplementedError

---

*[drake/systems/sensors/visualization/show_images.py, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1_12owOPxf3-DQ8nH:-Ku1_12owOPxf3-DQ8nI:b-rlfb90) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L82)):*
> ```Python
>         self.view.installImageInteractor()
>         # Add actor.
>         self.imageActor = vtk.vtkImageActor()
> ```

BTW, this should be snake_case, i.e. `self.image_actor`.

---

*[drake/systems/sensors/visualization/show_images.py, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1_6yrNFFnKGg0kLls:-Ku1_6yrNFFnKGg0kLlt:b-dgrt54) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L91)):*
> ```Python
>         self.view.backgroundRenderer().SetBackground2(0, 0, 0)
> 
>         self.depthMapper = None
> ```

BTW, ditto.

---

*[drake/systems/sensors/visualization/show_images.py, line 291 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1qH2wQ-3lA8I6rVbt:-Ku1qH2wQ-3lA8I6rVbu:bx61fa1) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L291)):*
> ```Python
>     """ Gets a properly shaped NumPy view of a VTK image's memory. """
>     data = vtk_to_numpy(image.GetPointData().GetScalars())
>     data.shape = get_vtk_image_shape(image)
> ```

This is a bit confusing to me since the shape of numpy array usually takes `(h, w, num_channels)` order.  How about documenting like "all the arrary both from vtk and numpy take (h, w, num_channels) order through out the file. Note that this is different from numpy's convention." or something at the top level .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-:-Ku1rOX8i9GK7IsrYQiZ:b6o68ox)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/sensors/visualization/show_images.py, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1YBJM6TsFpvX1ldMr:-Ku57VVGPM7nt6zeRKzW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L42)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, how about putting underscore at the beginning?
https://www.python.org/dev/peps/pep-0008/#global-variable-names
</blockquote></details>

Done.

---

*[drake/systems/sensors/visualization/show_images.py, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1Xg7TiSHmBMi4-Xlm:-Ku57VphffyGXy2vNfc7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L44)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, ditto.
</blockquote></details>

Done.

---

*[drake/systems/sensors/visualization/show_images.py, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1XzSWpVzJ2jMziNNq:-Ku57W8YRhUvtQnKhYzC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L45)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, ditto.
</blockquote></details>

Done.

---

*[drake/systems/sensors/visualization/show_images.py, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1VDGK2FW05RiTLPyy:-Ku57WbZQQPhdlhD2KBC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L47)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, Drake follows PEP8 as Python style guide, and constants should be written in all capital letters with underscores separating words in PEP8: https://www.python.org/dev/peps/pep-0008/#constants
</blockquote></details>

Done.

---

*[drake/systems/sensors/visualization/show_images.py, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1Yu406qyLk35WsuHC:-Ku57S07cN85_i4tDdmw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L61)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

How about raising "NotImplementedError" instead?
https://docs.python.org/2/library/exceptions.html#exceptions.NotImplementedError
</blockquote></details>

Done.

---

*[drake/systems/sensors/visualization/show_images.py, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1_12owOPxf3-DQ8nH:-Ku57SOhEEVYbs4Sl6LT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L82)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, this should be snake_case, i.e. `self.image_actor`.
</blockquote></details>

Done.

---

*[drake/systems/sensors/visualization/show_images.py, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1_6yrNFFnKGg0kLls:-Ku57Xie8rjmhNAoPHVE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L91)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, ditto.
</blockquote></details>

Done.

---

*[drake/systems/sensors/visualization/show_images.py, line 291 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1qH2wQ-3lA8I6rVbt:-Ku57tdv9fhyZQk4q8bU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L291)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

This is a bit confusing to me since the shape of numpy array usually takes `(h, w, num_channels)` order.  How about documenting like "all the arrary both from vtk and numpy take (h, w, num_channels) order through out the file. Note that this is different from numpy's convention." or something at the top level .
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023)*

**Comment by kunimatsu-tri** [comment]
:lgtm: since almost all the comments I made are for style or comments.
Thank you for working on this. This is going to be very useful!

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/sensors/visualization/show_images.py, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku54mLs5T9oVeSRnU4e:-Ku54mLs5T9oVeSRnU4f:b7tl2ai) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L72)):*
> ```Python
>     """
>     def __init__(self, image_handler):
>         self.name = 'Image View'
> ```

PEP8 syas "Use one leading underscore only for non-public methods and instance variables."

So, `self.name` should be `self._name`. ditto for everything else.

---

*[drake/systems/sensors/visualization/show_images.py, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1_12owOPxf3-DQ8nH:-Ku5503a95Apq_bhDFlU:bdm8dm0) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L82)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, this should be snake_case, i.e. `self.image_actor`.
</blockquote></details>

Sorry, this should be `self._image_actor`.

---

*[drake/systems/sensors/visualization/show_images.py, line 172 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku55VQeK9WGJLm54B1x:-Ku55VQeK9WGJLm54B1y:b3srmz1) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L172)):*
> ```Python
>         else:
>             # Direct connection.
>             # self.depthMapper = None
> ```

It seems this is unnecessary anymore? 

---

*[drake/systems/sensors/visualization/show_images.py, line 343 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku57qnNXHUEoisr9F4E:-Ku57qnNXHUEoisr9F4F:bs3eur1) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L343)):*
> ```Python
>         dtype = np.int16
>     else:
>         raise Exception("Unsupported pixel type: {}".format(pixel_desc))
> ```

BTW, how about raising `TypeError` instead?
https://docs.python.org/2/library/exceptions.html#exceptions.TypeError

---

*[drake/systems/sensors/visualization/show_images.py, line 355 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku58N7TuR00Su_wdYxg:-Ku58N7TuR00Su_wdYxh:b-lsjlyy) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L355)):*
> ```Python
>     # Copy data over.
>     data[:] = data_in[:]
>     # Return image.
> ```

BTW, the code below is self-describing so you don't need to repeat in the comment exactly what you write as the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-:-Ku5DE2mWZZJNPioHNyw:b-j5ocv5)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/sensors/visualization/show_images.py, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku54mLs5T9oVeSRnU4e:-Ku5FusHlJRpsZcSLaQe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L72)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

PEP8 syas "Use one leading underscore only for non-public methods and instance variables."

So, `self.name` should be `self._name`. ditto for everything else.

</blockquote></details>

Done.

---

*[drake/systems/sensors/visualization/show_images.py, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku1_12owOPxf3-DQ8nH:-Ku5Db4U-emGCWFYUa9B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L82)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Sorry, this should be `self._image_actor`.
</blockquote></details>

Done.

---

*[drake/systems/sensors/visualization/show_images.py, line 172 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku55VQeK9WGJLm54B1x:-Ku5G6rC_Bs48HgVoJo2:b-dnvgo5) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L172)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

It seems this is unnecessary anymore? 
</blockquote></details>

Done. (Had forgotten to uncomment it.)

---

*[drake/systems/sensors/visualization/show_images.py, line 343 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku57qnNXHUEoisr9F4E:-Ku5Dkt0zRKOQk2enQPd:bnb9sj7) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L343)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, how about raising `TypeError` instead?
https://docs.python.org/2/library/exceptions.html#exceptions.TypeError
</blockquote></details>

Done. Since it's not a Python type per se that it's erroring out on, I've changed it to `RuntimeError`.

---

*[drake/systems/sensors/visualization/show_images.py, line 355 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-Ku58N7TuR00Su_wdYxg:-Ku5FObc-oywM77l4irj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d84d9bd4123acf08f946cea2621198da003463/drake/systems/sensors/visualization/show_images.py#L355)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, the code below is self-describing so you don't need to repeat in the comment exactly what you write as the code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023)*

**Comment by kunimatsu-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for platform review (Tues), please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-:-KuMDltm4ZcSl1d0qQFi:bp3innf)*

**Comment by sammy-tri** [comment]
First pass complete, just a couple nits

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/visualization/show_images.py, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-KuQDOH-SVl6kmPWZvgb:-KuQDOH-SVl6kmPWZvgc:bm3belf) ([raw file](https://github.com/robotlocomotion/drake/blob/d307091f42cc8e8301c075697e88a9f341fb7d78/drake/systems/sensors/visualization/show_images.py#L14)):*
> ```Python
>     ./show_images.py
> 
> This provides a simple image viewer widget, based upon:
> ```

does `based upon` in this case mean that the source code for those was the inspiration/basis for this implementation?  (I ask because this implementation doesn't seem to use them)

---

*[drake/systems/sensors/visualization/show_images.py, line 204 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-KuQFDaG2MTZQVqoRvhc:-KuQFDaG2MTZQVqoRvhd:b-gfblci) ([raw file](https://github.com/robotlocomotion/drake/blob/d307091f42cc8e8301c075697e88a9f341fb7d78/drake/systems/sensors/visualization/show_images.py#L204)):*
> ```Python
>     """
>     def __init__(self, handlers):
>         super(ImageArrayWidget, self).__init__()
> ```

This isn't a typical thing to for a class which inherits directly from `object`, is it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-:-KuQII10xq-ZYRScb3LC:b-xtsz6)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/visualization/show_images.py, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-KuQDOH-SVl6kmPWZvgb:-KuQQ9gQu702GpUH-ic4:bit7xjl) ([raw file](https://github.com/robotlocomotion/drake/blob/d307091f42cc8e8301c075697e88a9f341fb7d78/drake/systems/sensors/visualization/show_images.py#L14)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

does `based upon` in this case mean that the source code for those was the inspiration/basis for this implementation?  (I ask because this implementation doesn't seem to use them)
</blockquote></details>

Done - clarified wording.

---

*[drake/systems/sensors/visualization/show_images.py, line 204 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-KuQFDaG2MTZQVqoRvhc:-KuQQEok2ywQeKfjwO7M:b-pxbr6x) ([raw file](https://github.com/robotlocomotion/drake/blob/d307091f42cc8e8301c075697e88a9f341fb7d78/drake/systems/sensors/visualization/show_images.py#L204)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This isn't a typical thing to for a class which inherits directly from `object`, is it?
</blockquote></details>

Done.
(Had forgotten about that! I tested out having this inherit from `QWidget`, got annoyed, and switched it back.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7023#-:-KuQUmU_M72iar9fKjcj:bnfp4nl)*

**Pull request merged**
