### PR TITLE
Add support for numpy 2.0

### PR DESCRIPTION
**Pull request by johnwparent**
Changes:
- [workspace] Upgrade pybind11 to latest commit (https://github.com/RobotLocomotion/pybind11/pull/72).
- Disable Gynmasium-related regression tests on macOS.  DrakeGym might not work anymore on macOS.
- Update some unit test syntax for latest numpy.
- Revert our temporary pin to `numpy < 2`. We no longer constraint numpy at all.
- Fix namedview repr to add `<>` to comply with Python's required semantics.

Towards #21577.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21684)

### CODE REVIEW

**Comment by johnwparent** [comment]
cc @BetsyMcPhail

**Comment by jwnimmer-tri** [comment]
Thanks, looks promising so far!

The next step is to push a second commit onto this branch that reverts #21582, and then launch every macOS Unprovisioned Experimental build (to see how it works versus numpy 2).

**Comment by johnwparent** [comment]
@jwnimmer-tri pushed the revert, how do we kick off the extra jobs?

**Comment by jwnimmer-tri** [comment]
Docs at https://drake.mit.edu/jenkins.html, but here it is:

@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-cmake-experimental-packaging please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by johnwparent** [comment]
Thanks!

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please

I pushed some unit test fixes.  We'll see how new builds fare.

If the Gym tests are still broken with upstream bugs (they were yesterday), then we'll just disavow Gym support on macOS and disable them.

**Comment by jwnimmer-tri** [comment]
> ... then we'll just disavow Gym support on macOS and disable them.

I've pushed this change now too.

Remaining work is to fix the namedvector test failure, and get our macOS CI machines up an running again.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
I'm going to let the current CI job finish to see where we stand, and then push the pybind11 git sha bump.

If the only remaining CI failure is the namedview test failure, I'll also push a nerf for that test.

Conceivably this will be green and ready to merge tomorrow morning.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 2 of 4 files at r3, 2 of 3 files at r4, 3 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21684)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @johnwparent)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
I am somewhat hopeful that CI might pass this time around.  In any cases, we're close.

+@EricCousineau-TRI are you able to feature-review this?  Goal would be to land it before Monday.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: feature
+@ggould-tri for platform please!

> Reviewed 3 of 3 files at r2, 2 of 4 files at r3, 2 of 3 files at r4, 3 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21684#-:-O1MtEeW7Y0CXv4QhAu8:btpjq2x)* status: LGTM missing from assignee ggould-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @johnwparent)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 2 of 4 files at r3, 2 of 3 files at r4, 3 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21684#-:-O1NSU-76S32GjMIdMUT:bnfp4nl)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @johnwparent)

**Pull request merged**
