### PR TITLE
[geometry] Move RenderEngineVtk into its own directory

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Leave only the params class and factory function as non-internal.

This scheme aligns with what we agreed on for `geometry/render_gltf_client`.

Towards #16502.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17169)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please.

\CC @svenevs @rpoyner-tri @joemasterjohn FYI

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17169)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
:lgtm: 

Just a few naming conventions to follow up.
1) In `geometry/render_gltf_client`, we put `MakeRenderEngineGltfClient()` and `RenderEngineGltfClientParams` directly under `drake::geometry` namespace. 
2) The factory method lives in `factory.{h, cc}` rather than `render_engine_gltf_client_factory.{h, cc}`.
3) The `engine` is omitted in `render_gltf_client_params.{.h, cc}`.

I was following the Slack discussion but I can modify the files in `geometry/render_gltf_client` to make them a completely mirrored structure.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17169#-:-N1svmu466WxyseYgM0_:b-rnewy0)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @zachfang)

**Review by jwnimmer-tri — COMMENTED** [review]
Most likely I did it wrong here, and gltf is correct.  I'll go back and check.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17169#-:-N1sze5lCXSBw9zWzgrs:bkoxrqg)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri and @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17169#-N1szb7e9Bwm1plL-vVZ:-N1szb7e9Bwm1plL-vV_:bk7kyr1) (no related file):*
Working

I think the factory naming isn't quite right.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17169)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri, @rpoyner-tri, and @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17169#-N1szb7e9Bwm1plL-vVZ:-N1t46VQDs2CeW8s3qSp:bou29bf) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I think the factory naming isn't quite right.
</blockquote></details>

Done.  The factory and namespace stuff was wrong, fixed now.  For the params, we need the struct classname and filename to match, so I kept the filename unchanged.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17169#-N1t43MH-i7rgMrYDvwl:-N1t43MH-i7rgMrYDvwm:bcg3sq5) (no related file):*
Working

Double-checking the deprecation shims via Anzu testing.

___

**Review by jwnimmer-tri — COMMENTED** [review]
@rpoyner-tri it seems you've already read the whole PR?  Would you like to serve as platform review?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17169#-:-N1t8RCJCQXr56NYYFaa:b-ljd43v)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri and @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17169#-N1t43MH-i7rgMrYDvwl:-N1t8Ojb-bqdH1n0BERB:b-i0krp5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Double-checking the deprecation shims via Anzu testing.
</blockquote></details>

Done -(status: do not merge).

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 12 of 14 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17169)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @zachfang)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17169#-:-N1tcp_F2UDzPmYsu52R:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),zachfang (waiting on @zachfang)

**Pull request merged**
