### PR TITLE
Modified Drake Build System to Support ROS If ROS Is Present.

### PR DESCRIPTION
**Pull request by liangfok**
Contributes to: https://github.com/RobotLocomotion/drake/issues/1733

_Again, this is in the spirit of cultivating a culture of small pull requests!_

# Major Changes
* Added a unit test called `ros_test` that demonstrates that it can instantiate a ROS node.

# Notes
* The unit test is automatically built if ROS is found on the local machine.
* The unit test will be extended to evaluate more drake-specific functionality in future PRs.

# How to Run Unit Test
_The following instructions only work on Ubuntu Linux 14.04._

[Install ROS Indigo](http://wiki.ros.org/indigo/Installation/Ubuntu).

Open two terminals. In the first terminal, start `roscore`:

```
$ source /opt/ros/indigo/setup.bash
$ roscore
```

In the second terminal, run the unit test:

```
$ source /opt/ros/indigo/setup.bash
$ cd [drake distro]/drake/pod-build
$ ctest -VV -R ros_test
```

Note that the unit test will fail if `roscore` is not running. This is expected behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2103)

### CODE REVIEW

**Comment by liangfok** [comment]
I currently use option `WITH_ROS` within `[drake distro]/drake/CMakeLists.txt` as the boolean variable to determine whether ROS support is included. One disadvantage of this is it requires the user to modify a file that's version-controlled. An alternative is to require the user to set an environment variable like `DRAKE_INCLUDE_ROS_SUPPORT` and to modify `[drake distro]/drake/CMakeLists.txt` to check for the existence and value of this variable to decide whether to include ROS support in Drake. What do you think?

**Comment by RussTedrake** [comment]
I think that ROS support should be built if ROS is found.  I don’t see a good reason to have a WITH_ROS flag.  The WITH_ flags at the superbuild level indicate that we are asking drake to install an external by itself — this is not the first time I’ve had to apologize for the name, so we should consider updating it.  

The USE_MATLAB was a request because people for some reason want to be able to build without matlab even if they have matlab (not a use case I personally understand!).  But I think that should be the exception, not the norm.

- Russ

**Comment by liangfok** [comment]
OK great. I will modify this PR to include ROS support if it is found on the local machine.

**Comment by liangfok** [comment]
I've modified this PR to automatically build the new `ros_test` unit test when ROS is found on the local system. I'm using the ROS detection method that @gerkey recommended [here](http://answers.ros.org/question/227611/what-is-the-best-way-for-cmakeliststxt-to-check-if-ros-is-installed/).

One potential issue is the fact that [roscore](http://wiki.ros.org/roscore) must be running before executing the unit test. Otherwise the unit test will fail. Is this a problem? I've opened [this issue](https://github.com/gerkey/ros1_external_use/issues/12) asking what is the best way to launch `roscore` automatically.

**Comment by sammy-tri** [comment]
FWIW, I disagree with forcing all optional features on if the prerequisites are detected.  (I haven't chimed in on the USE_MATLAB discussion, but I have been following it).  I think it's valuable for a number of reasons to turn off features selectively without having to uninstall dependencies to trick the build system. Example uses include testing different configurations (particularly when there's fallback code which compiles instead of something which depends on the detected configuration), reducing build times, etc.  This is the approach taken by most automake based projects, which frequently allow passing --without-foo to the configure script even if foo's dependencies are present.

I have no problem with Drake defaulting things to on when the dependency is present (as automake based build systems often do), but if there's a valid compilation environment without a detected item, I'd say we should be able to turn the feature off without changing the system configuration.

**Comment by liangfok** [comment]
@sammy-tri, would you say that the fundamental limitation that prevents the use of a `--without-foo` flag is https://github.com/RobotLocomotion/drake/issues/2105? If so, let's re-open that issue.

**Comment by liangfok** [comment]
@RussTedrake, since this PR passed the CI build suite, I believe it's ready for you to review / merge.

**Comment by sammy-tri** [comment]
I hadn't thought about why --without-foo would be difficult (if the superbuild is responsible for compiling the dependency in the first place, it isn't).  I guess in the case of disabling MATLAB, #2105 probably is the actual problem.

**Comment by RussTedrake** [comment]
reviewed.

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/test/CMakeLists.txt, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2103#-KFdurlW2KzXYLDUilHy:-KFdurlW2KzXYLDUilHz:1955333368) ([raw file](https://github.com/robotlocomotion/drake/blob/912dc8ce2bbff132ece07a930cd68a63115ebebc/drake/systems/test/CMakeLists.txt#L13)):*
why QUIET?  i think it's useful to see the output.  especially if we start doing this multiple times in multiple directories (which would be inefficient)... we'd like to see it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2103#-:-KFdv4IEjfqmBr9lDTmf:-384175694)*

**Comment by liangfok** [comment]
Thanks for the review. I addressed the comments and am now waiting for the CI test suite.

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/test/CMakeLists.txt, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2103#-KFdurlW2KzXYLDUilHy:-KFeSYq4IJxZe3ESpHt0:-572325013) ([raw file](https://github.com/robotlocomotion/drake/blob/912dc8ce2bbff132ece07a930cd68a63115ebebc/drake/systems/test/CMakeLists.txt#L13)):*
I modified this PR to move the `find_package(roscpp QUIET)` to `[drake distro]/drake/CMakeLists.txt` so it will only need to be done once. I kept it quiet but added message print statements indicating whether ROS support will be included. I believe this is preferable since we don't want to print false positives if the user does not in fact have or want ROS installed on the local system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2103#-:-KFeV5r4MO5Sw4r96fcY:-961330239)*

**Comment by liangfok** [comment]
@RussTedrake: This PR is ready for you to review again.

**Comment by liangfok** [comment]
@david-german-tri: I think CI encountered a flake [here](https://drake-jenkins.csail.mit.edu/job/experimental/918/compiler=msvc-64,label=windows/console).

@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
That flake is most likely another manifestation of #2035.

**Comment by liangfok** [comment]
@RussTedrake: This PR passed [CI build #923](https://drake-jenkins.csail.mit.edu/job/experimental/923/) and is thus ready for another round of review.

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2103#-:-KFkgYE9UsDyxNuYdWvP:1417088721)*

**Comment by liangfok** [comment]
@david-german-tri, since @RussTedrake gave this PR a LGTM, I will assign it to you for final review / merge. It's currently going through another round of CI tests given the recent PR merges.

**Comment by liangfok** [comment]
I believe [CI Build #944](https://drake-jenkins.csail.mit.edu/job/experimental/944/) encountered flake https://github.com/RobotLocomotion/drake/issues/2035.

**Comment by liangfok** [comment]
@david-german-tri: I believe [CI build 962](https://drake-jenkins.csail.mit.edu/job/experimental/962/) encountered a massive flake. I'm actually having trouble even opening the [full console log of gcc,linux_matlab](https://drake-jenkins.csail.mit.edu/job/experimental/962/compiler=gcc,label=linux_matlab/consoleFull) using Apple's Safari browser.

@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
@david-german-tri: [CI build 963](https://drake-jenkins.csail.mit.edu/job/experimental/963/) also suffered a similar fault as [CI build 961](https://drake-jenkins.csail.mit.edu/job/experimental/961/).

```
08:44:09 cl : Command line error D8040: error creating or communicating with child process [C:\projects\workspace\experimental\f30d52b4\pod-build\externals\lcm\lcm-prefix\src\lcm-build\lcm\lcm.vcxproj] [C:\projects\workspace\experimental\f30d52b4\pod-build\externals\lcm\lcm.vcxproj] [C:\projects\workspace\experimental\f30d52b4\pod-build\lcm.vcxproj]
```

**Comment by david-german-tri** [comment]
general tip for large logs: `curl https://drake-jenkins.csail.mit.edu/job/experimental/962/compiler=gcc,label=linux_matlab/consoleText`

**Comment by liangfok** [comment]
Thanks @david-german-tri. Is `curl` preferred over `wget`? If so, why? Just curious.

**Comment by david-german-tri** [comment]
Just personal preference.

**Comment by liangfok** [comment]
Looking at the log file if [CI build 962, gcc/linux-matlab](https://drake-jenkins.csail.mit.edu/job/experimental/962/compiler=gcc,label=linux_matlab/consoleText), I see that the first error occurs on line 27776:

```
27776 /home/ubuntu/workspace/experimental/06107e1d/drake/examples/Cars/publishDrivingCommand.cpp:5:57: fatal error: lcmtypes/drake/lcmt_driving_control_cmd_t.hpp: No such file or directory
27777  #include "lcmtypes/drake/lcmt_driving_control_cmd_t.hpp"

```
Searching for `lcmt_driving_control_cmt_t.hpp`, I see that it's actually generated on line 30628:

```
30628 [ 25%] Generating lcmgen/lcmtypes/drake/lcmt_driving_control_cmd_t.hpp
```

Thus, the problem may be a missing depency specification within the build system or a multi-threaded race condition issue.

**Comment by david-german-tri** [comment]
Great catch, thanks!  Please open an issue?

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
Not sure why this is assigned to me, but :lgtm: regardless.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2103#-:-KFuHjRUykNVLtcD-F2E:800459941)*

**Comment by david-german-tri** [comment]
Merging without waiting for drake005.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2103#-:-KFuIHjcZok7Fzt4Txzg:-1260366380)*

**Pull request merged**
