### PR TITLE
[doc] Add release notes v1.6.0

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for review. If the nightlies are clean tonight (08-15/16), could release tomorrow (08-16).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716#-:-N9YU-hVAp1Jv9DcPNzN:b-29libl)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: so far

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716#-:-N9YrxAZ6HD6pBXBHkJQ:b-vlbdz2)* status: 6 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.6.0.md` line 32 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17716#-N9YrBNYDQBZAVrtiA8S:-N9YrBNYDQBZAVrtiA8T:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/811cc61e7cb15330c0d5e57b12d6b5cfd02a96b6/doc/_release-notes/v1.6.0.md#L32)):*
> ```Markdown
> New features
> 
> * TBD
> ```

nit



_Suggestion:_
```Markdown
* None
```
___
*[`doc/_release-notes/v1.6.0.md` line 66 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17716#-N9YrHVECkpspcXjozsZ:-N9YrHVF65j4nXt2Jiww:bma089u) ([raw file](https://github.com/robotlocomotion/drake/blob/811cc61e7cb15330c0d5e57b12d6b5cfd02a96b6/doc/_release-notes/v1.6.0.md#L66)):*
> ```Markdown
> * Add PolyhedronConstraint as a kinematic constraint ([#17596][_#17596])
> * Implement capability to define coupler constraints ([#17639][_#17639])
> * Move MakeRenderEngineGltfClient() from the dev folder ([#17678][_#17678])
> ```

nit 17678 ended up being demoted back to private visibility; I think we should nix this line for now?
___
*[`doc/_release-notes/v1.6.0.md` line 95 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17716#-N9YrWfI-yFNdXYPAV91:-N9YrWfJD5R415TgTC4-:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/811cc61e7cb15330c0d5e57b12d6b5cfd02a96b6/doc/_release-notes/v1.6.0.md#L95)):*
> ```Markdown
> Fixes
> 
> * TBD
> ```

nit



_Suggestion:_
```Markdown
* None
```
___
*[`doc/_release-notes/v1.6.0.md` line 125 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17716#-N9Yr_nM84JHMSyQM37h:-N9Yr_nM84JHMSyQM37i:bme31sd) ([raw file](https://github.com/robotlocomotion/drake/blob/811cc61e7cb15330c0d5e57b12d6b5cfd02a96b6/doc/_release-notes/v1.6.0.md#L125)):*
> ```Markdown
> New features
> 
> * TBD
> ```

nit (also ditto immediately below)



_Suggestion:_
```Markdown
* None
```
___
*[`doc/_release-notes/v1.6.0.md` line 175 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17716#-N9YrmJG0fxomySUEt_c:-N9YrmJHDsvvIwP2yCnu:b-vha84p) ([raw file](https://github.com/robotlocomotion/drake/blob/811cc61e7cb15330c0d5e57b12d6b5cfd02a96b6/doc/_release-notes/v1.6.0.md#L175)):*
> ```Markdown
> 
> 
> * Remove scipy dependency ([#17559][_#17559])
> ```

nit This is "removal of deprecated" so at minimum needs to be noted in that section below; it's okay to keep it here also, if you like.
___
*[`doc/_release-notes/v1.6.0.md` line 216 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17716#-N9Ys-WU1fOYUZY4mMLv:-N9Ys-WV8yAfGBn4DADY:b-afxnrl) ([raw file](https://github.com/robotlocomotion/drake/blob/811cc61e7cb15330c0d5e57b12d6b5cfd02a96b6/doc/_release-notes/v1.6.0.md#L216)):*
> ```Markdown
> 
> This release provides [pre-compiled binaries](https://github.com/RobotLocomotion/drake/releases/tag/v1.6.0) named
> ``drake-YYYYMMDD-{focal|mac}.tar.gz``. See [Stable Releases](/from_binary.html#stable-releases) for instructions on how to use them.
> ```

Reminder to fix all of the dates in all of the playbook-noted places.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`doc/_release-notes/v1.6.0.md` line 175 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17716#-N9YrmJG0fxomySUEt_c:-N9YuW3jEMGKTzxfTBEV:b-14ovxl) ([raw file](https://github.com/robotlocomotion/drake/blob/811cc61e7cb15330c0d5e57b12d6b5cfd02a96b6/doc/_release-notes/v1.6.0.md#L175)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is "removal of deprecated" so at minimum needs to be noted in that section below; it's okay to keep it here also, if you like.
</blockquote></details>

I see the label, but I'm not seeing what deprecated item was removed in that PR. Clue-bat please?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.6.0.md` line 175 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17716#-N9YrmJG0fxomySUEt_c:-N9Yuw8s1dJpcReO6PyA:bpyfv5b) ([raw file](https://github.com/robotlocomotion/drake/blob/811cc61e7cb15330c0d5e57b12d6b5cfd02a96b6/doc/_release-notes/v1.6.0.md#L175)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I see the label, but I'm not seeing what deprecated item was removed in that PR. Clue-bat please?
</blockquote></details>

https://github.com/RobotLocomotion/drake/blame/4df89d6516b35aeb7804e38ba74039b1f162c420/doc/_release-notes/v1.1.0.md#L8-L13

The removal-of-deprecation bullet point would be something like "Unconditionally installing scipy as a dependency of pydrake".

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716#-:-N9b3zJCD21XpQ0ISB5M:b-safpmt)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716#-:-N9b4UVjAH_yBFi0TZ90:b-jzc2h8)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@seancurtis-tri for second look.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716#-:-N9b7EcQ11joMj-nmde0:b-7pnd4r)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: No changes needed. Just one wry observation.

> Reviewed 1 of 2 files at r2, 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17716#-:-N9b8njMEUWkAbgXRa5k:b-wtdkzm)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.6.0.md` line 52 at r8](https://reviewable.io/reviews/robotlocomotion/drake/17716#-N9b7GOY-UaUh3Q3yMvS:-N9b7GOY-UaUh3Q3yMvT:b-2huupo) ([raw file](https://github.com/robotlocomotion/drake/blob/bc4d18ea87b8637651047c4c2ef3f59a40e38d92/doc/_release-notes/v1.6.0.md#L52)):*
> ```Markdown
> * Add positive_semidefinite_constraints when calling GetAllConstraints ([#17712][_#17712])
> * ExtractGradient now accounts for the storage order of its input ([#17516][_#17516])
> * Polynomial prunes terms with trivially-zero coefficients ([#17611][_#17611])
> ```

BTW Just as a passing editorial comment. It's funny that `GurobiSolver` has gotten rid of the automatic culling of small coefficients in the same release that `Polynomial` adds it.  :) Bwa, ha, ha.

**Comment by rpoyner-tri** [comment]
@betsymcphail please help with tagging docker images and uploading release to S3.
Date: 20220816
SHA: 4df89d6516b35aeb7804e38ba74039b1f162c420
Release tag: [v1.6.0](https://github.com/RobotLocomotion/drake/tree/v1.6.0)
Thanks!

**Comment by BetsyMcPhail** [comment]
I realized when doing the 1.7.0 release I had somehow missed this tag. Docker/S3/Apt for 1.6.0 will be ready soon.

**Comment by BetsyMcPhail** [comment]
The Docker, apt and .tar.gz for 1.6.0 have all been created and upload.

**Pull request merged**
