### PR TITLE
Add Graphviz rendering for Diagrams.

### PR DESCRIPTION
**Pull request by david-german-tri**
diagram_of_diagrams

It looks a lot better in SVG or PNG than it does in JPG, but GitHub appears to prefer JPG.

@naveenoid for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5545)

### CODE REVIEW

**Comment by naveenoid** [comment]
Thanks a lot for this @david-german-tri Apart from a few BTWs I have one main question : I dont see any obvious documentation for actually rendering the svg/png/jpg itself. Or am I missing something here? Perhaps there needs to be a bit of a doxy comment at LeafSystem.h/diagram.h explaining how leafsystem/diagram architects can proceed to visualize their components. 

Otherwise :lgtm: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 455 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5545#-Kfex0M-LnGaIVukBp2C:-Kfex0M0Aa3lILfIyKzA:b19uyvx) ([raw file](https://github.com/robotlocomotion/drake/blob/a551ccab29588edf24ddff3fbaa39406f1576775/drake/systems/framework/diagram.h#L455)):*
> ```objc
>   /// @name                      Graphviz methods
>   //@{
> ```

BTW: Dont you want to have some doxy documentation at the Diagram level for the graphviz methods? Perhaps just a redirect to system.h doxy block or to the external graphviz doc?

---

*[drake/systems/framework/leaf_system.h, line 262 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5545#-KfexYwOYqxGQRvkQMOv:-KfexYwTBcIh_SmdxWVY:bvqf7qw) ([raw file](https://github.com/robotlocomotion/drake/blob/a551ccab29588edf24ddff3fbaa39406f1576775/drake/systems/framework/leaf_system.h#L262)):*
> ```objc
> 
> 
>   // Emits a graphviz fragment for this System. Leaf systems are visualized as
> ```

BTW: Why isnt this a doxy comment block?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5545#-:-KfexiI5LllY-y6Dzj6-:b54v4aq)*

**Comment by david-german-tri** [comment]
> Perhaps there needs to be a bit of a doxy comment at LeafSystem.h/diagram.h explaining how leafsystem/diagram architects can proceed to visualize their components.

Done.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 455 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5545#-Kfex0M-LnGaIVukBp2C:-KfhmoDZdkC0GImdfOBj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a551ccab29588edf24ddff3fbaa39406f1576775/drake/systems/framework/diagram.h#L455)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Dont you want to have some doxy documentation at the Diagram level for the graphviz methods? Perhaps just a redirect to system.h doxy block or to the external graphviz doc?
</blockquote></details>

Done.

---

*[drake/systems/framework/leaf_system.h, line 262 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5545#-KfexYwOYqxGQRvkQMOv:-KfhnI0gaxOW2nqGp1Ov:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a551ccab29588edf24ddff3fbaa39406f1576775/drake/systems/framework/leaf_system.h#L262)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Why isnt this a doxy comment block?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5545#-:-KfhmRM2fg4BzEd2VJC3:b-not7r1)*

**Comment by naveenoid** [comment]
Reviewed 2 of 7 files at r2.
Review status: 3 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5545)*

**Comment by david-german-tri** [comment]
+@sammy-tri 

---

Review status: 3 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5545#-:-KfkzGjbNtqsf_hQsa9I:bt5szf5)*

**Comment by david-german-tri** [comment]
(for platform review)

---

Review status: 3 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5545#-:-KfkzILHSLyAyHw7BXrT:b-mkh542)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5545#-:-Kflo2ONj9SI36hC9Lrc:bnfp4nl)*

**Pull request merged**
