### PR TITLE
FastQP in solveLCPmex

### PR DESCRIPTION
**Pull request by psiorx**
This lets the c++ implementation of solveLCP call fastQP first and only falls back on pathlcp when fastQP fails.  This substantially reduces the number of calls to pathlcp and makes this implementation much faster than solveLCP in all Atlas sims regardless of whether the hands are used.

### CODE REVIEW

**Comment by psiorx** [comment]
Are these errors real?  

Can't reproduce locally and I logged into the build server and the segfault is happening in libdrakeRigidBodyConstraint in MinDistanceConstraint.eval.  The other error is in drakeGradientUtil.

Neither of these should be touched by these changes.

**Comment by RussTedrake** [comment]
The other big thing that changed was the eigen version.  Maybe that's the cause?

- Russ

**Comment by psiorx** [comment]
Ah, that's right.  Let me pull in the drake-distro changes and test that.

**Comment by psiorx** [comment]
That wasn't it.  At least not on 14.04.  Drake006 is running an older distro, though.  I'll wait for some of the other build servers to chime in.

**Comment by RussTedrake** [comment]
This looks good to me.

**Pull request merged**
