### PR TITLE
Install VTK

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129. FYI @stonier.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6325)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/vtk.bzl, line 500 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6325#-Kmg4UfSHi0NcnT09a7-:-Kmg4UfT5KSgPYrSaV9B:b-9j2gwb) ([raw file](https://github.com/robotlocomotion/drake/blob/33af3b6238b13a7be88cbbf0a40e0676334b361a/tools/vtk.bzl#L500)):*
> ```Python
>     name = "install",
>     dest = ".",
>     files = {},
> ```

BTW, I'm not sure I like relying on `str(x)` (for `x` being a `list`) to effectively be `repr(x)`. I had to verify for myself that this actually works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6325#-:-Kmg5RfN0mYjqm_wfPkr:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6325)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by jwnimmer-tri** [comment]
-@soonho-tri +@jwnimmer-tri stealing platform.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6325#-:-KmlAdA7bdvMTxwWZ5f2:bnfp4nl)*

**Pull request merged**
