### PR TITLE
Fix ASan problems in pose_aggregator_test.cc and normalize_vector.h

### LINKED ISSUE #11391: Mojave build fails with ASan
[`mac-mojave-clang-bazel-experimental-address-sanitizer`](https://drake-jenkins.csail.mit.edu/view/Mac%20Mojave/job/mac-mojave-clang-bazel-experimental-address-sanitizer/2/) fails.
Three tests fail:

* [ ] `//math:normalize_vector_test`
* [x] `//solvers:cost_test`
* [ ] `//systems/rendering:pose_aggregator_test`

To (approximately) reproduce on Linux 18.04 with gcc (`7.4.0`): 
`bazel test --config=asan --copt -O0 <test_name>`

### PR DESCRIPTION
**Pull request by m-chaturvedi**
To reproduce: 

- `bazel test --config=asan --copt -O0 //systems/rendering:pose_aggregator_test`
   [Error](https://gist.github.com/m-chaturvedi/abd860710c7f5a4671dd986c10e9dbd6)

- `bazel test --config=asan --copt -O0  //math:normalize_vector_test`
   [Error with line numbers (via @jamiesnape) ](https://gist.github.com/m-chaturvedi/76eb5d2fa09233c75bd885d2e759a4da)
   [Reference](https://eigen.tuxfamily.org/dox/TopicPitfalls.html)

Closes #11391

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11395)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-address-sanitizer-release please

We expect the build to fail, but the number errors to reduce by 1.

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-address-sanitizer-release please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-address-sanitizer please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-address-sanitizer-release please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-address-sanitizer please

**Comment by jamiesnape** [comment]
+@sammy-tri for feature and platform review.

**Comment by m-chaturvedi** [comment]
___
*[math/normalize_vector.h, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11395#-LeHulGJBPWBqoibecmC:-LeI0ZMH-P50njgwlIv_:b-sok1ed) ([raw file](https://github.com/robotlocomotion/drake/blob/a44c13bfbf54420feaf80df067c98856bb402979/math/normalize_vector.h#L43)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the `auto` keyword is causing problem here, by using `-matGradMultMat`, the type of `ddx_norm_times_norm` is an Eigen expression, not a concrete type like `Eigen::Matrix<double, Rows, Cols>`. Now when we remove `-` sign, `auto ddx_norm_times_norm` becomes of type `Eigen::Matrix<double, Rows, Cols>`.
</blockquote></details>

Yes, the `auto` keyword is causing a problem here.  
When we remove the `-` sign, we don't have a reference to a temporary variable that goes out of scope:
https://eigen.tuxfamily.org/dox/TopicPitfalls.html

The minus sign when later used, doesn't store reference to a temporary variable because `*ddx_norm` is of type `drake::math::Gradient<Derived, Derived::RowsAtCompileTime, 1>::type`.

This is clear form the log.

**Comment by m-chaturvedi** [comment]
___
*[math/normalize_vector.h, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11395#-LeHulGJBPWBqoibecmC:-LeI7oALDhtkuMV8tfMC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a44c13bfbf54420feaf80df067c98856bb402979/math/normalize_vector.h#L43)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sounds good, thanks!

If you could rename the variable `ddx_norm_times_norm` to `minus_ddx_norm_times_norm` then I think we are good to go.
</blockquote></details>

Done.

**Pull request merged**
