### PR TITLE
Iris from clique cover

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20615)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+(status: do not merge) 

+@wernerpe For first pass feature review. 

Could you please review the design of both `IrisFromCliqueCover` and `ApproximateConvexCoverFromCliqueCover` and see if you like it?

+@calderpg-tri Could you take a look in  `approximate_convex_cover_from_clique_cover.cc` and tell me if all the concurrency implementations looks okay?

This PR provides a full, first pass implementation towards #20372. If Peter agrees with the design, separate PRs will be filed for the many base classes and their concrete implementations that are included this PR as currently, this is way too much code to review properly.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-:-NkaHoqC5-b43Cc0tKy9:b-mq5q0d)* status: 3 unresolved discussions, LGTM missing from assignees wernerpe,calderpg-tri, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/approximate_convex_cover_builder_base.cc` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkaM1PW-6HT8l62BJfB:-NkaM1PW-6HT8l62BJfC:buqdynq) ([raw file](https://github.com/RobotLocomotion/drake/blob/7baa67ee09ae3afae9943e434d3a24c559dca2cd/planning/approximate_convex_cover_builder_base.cc#L44)):*
> ```cpp
> // the queue is filling, pop will wait until a job is available.
> template <typename T>
> class AsyncQueue {
> ```

+@calderpg-tri If you could take a look and make sure I did nothing silly here.
___
*[`planning/approximate_convex_cover_builder_base.cc` line 59 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkaM7-9BD6n337Mp7Sl:-NkaM7-9BD6n337Mp7Sm:b-b19ayn) ([raw file](https://github.com/RobotLocomotion/drake/blob/7baa67ee09ae3afae9943e434d3a24c559dca2cd/planning/approximate_convex_cover_builder_base.cc#L59)):*
> ```cpp
>   // Marked no lint since the linter really dislikes passing a non-const
>   // reference.
>   bool pop(T& write_reference /*NOLINT*/) {
> ```

+@calderpg-tri Is this okay to do?
___
*[`planning/approximate_convex_cover_builder_base.cc` line 209 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkaMJgQ7042XKvRl_kL:-NkaMJgQ7042XKvRl_kM:b-ulvkgj) ([raw file](https://github.com/RobotLocomotion/drake/blob/7baa67ee09ae3afae9943e434d3a24c559dca2cd/planning/approximate_convex_cover_builder_base.cc#L209)):*
> ```cpp
>     // The computed cliques from the max clique solver. These will get pulled
>     // off the queue by the set builder workers to build the sets.
>     AsyncQueue<VectorX<bool>> computed_cliques;
> ```

+@calderpg-tri I am fairly confident on the type safety here given the `AsyncQueue` implementation, but I want to double check.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20615)* status: 3 unresolved discussions, LGTM missing from assignees calderpg-tri,wernerpe, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/approximate_convex_cover_builder_base.cc` line 209 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkaMJgQ7042XKvRl_kL:-NkaO7Dt1pYkk-rGUO41:bid94qs) ([raw file](https://github.com/RobotLocomotion/drake/blob/7baa67ee09ae3afae9943e434d3a24c559dca2cd/planning/approximate_convex_cover_builder_base.cc#L209)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

+@calderpg-tri I am fairly confident on the type safety here given the `AsyncQueue` implementation, but I want to double check.
</blockquote></details>

At first glance, I don't see why this needs a separate thread work queue implementation.  It seems like the desired behavior here is basically a dynamically-scheduled parallel-for loop, so you can use something like [DynamicParallelFor{Range, Index}Loop](https://github.com/RobotLocomotion/drake/blob/master/planning/visibility_graph.cc#L142-L158) ([implementation](https://github.com/ToyotaResearchInstitute/common_robotics_utilities/blob/master/include/common_robotics_utilities/parallelism.hpp#L406C17-L406C17)).

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20615)* status: 3 unresolved discussions, LGTM missing from assignees calderpg-tri,wernerpe, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/approximate_convex_cover_builder_base.cc` line 209 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkaMJgQ7042XKvRl_kL:-NkaPPFD35FZNylc_VgN:bxlxboe) ([raw file](https://github.com/RobotLocomotion/drake/blob/7baa67ee09ae3afae9943e434d3a24c559dca2cd/planning/approximate_convex_cover_builder_base.cc#L209)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

At first glance, I don't see why this needs a separate thread work queue implementation.  It seems like the desired behavior here is basically a dynamically-scheduled parallel-for loop, so you can use something like [DynamicParallelFor{Range, Index}Loop](https://github.com/RobotLocomotion/drake/blob/master/planning/visibility_graph.cc#L142-L158) ([implementation](https://github.com/ToyotaResearchInstitute/common_robotics_utilities/blob/master/include/common_robotics_utilities/parallelism.hpp#L406C17-L406C17)).
</blockquote></details>

I have one thread `clique_cover_thread` producing cliques. I have other threads which want to consume those cliques (without waiting for all the cliques to be produced) and build convex sets. This seems different than a `DynameParallelFor` loop.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20615)* status: 3 unresolved discussions, LGTM missing from assignees calderpg-tri,wernerpe, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/approximate_convex_cover_builder_base.cc` line 209 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkaMJgQ7042XKvRl_kL:-Nka_vMY0DMyCRgbcsyE:b-j2w3na) ([raw file](https://github.com/RobotLocomotion/drake/blob/7baa67ee09ae3afae9943e434d3a24c559dca2cd/planning/approximate_convex_cover_builder_base.cc#L209)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Ah, I see. A couple thoughts:

- Do you have a sense of the comparative runtimes of solving for max clique ("a") and building a convex set ("b")? Presumably on balance b > a such that this thread pool parallelism is useful - if b <= a there could be simpler approaches to parallelism here.
- Consider if there is a way to factor out the async work queue to a separate internal-only implementation (e.g. `async_work_queue_internal.h`) that could be reviewed and tested separately.
</blockquote></details>

It is somewhat hard to compare this as it will be highly dependent on how a user sets the options.

Users specify the size of the graph passed to max clique. If this is big, then max_clique will take a while, but if its small it can be very fast. Moreover, max clique could be solved via mip which will be fairly slow, or via a greedy heuristic which could be super fast.

On the other hand, building a convex set will essentially be `Iris`. Again, depending on the dimension of the space and how the user sets the IRIS options, IRIS could take much longer or much less than than max_clique.

I'll think about the second point.

**Review by AlexandreAmice — COMMENTED** [review]
Many of these methods should be callable from Python. As written, I have `unique_ptr` being passed as function arguments in a lot of places which will make binding them impossible. I will need to appropriately change many of these signatures.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-:-Nkfs8TyEdcb3WgXgArY:b-tngzxq)* status: 3 unresolved discussions, LGTM missing from assignees calderpg-tri,wernerpe, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Comment by wernerpe** [comment]
*[`planning/approximate_convex_cover_builder_base.h` line 19 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkpjnKdBZ5hM-3ph28T:-NkpjnKdBZ5hM-3ph28U:bj4oab0) ([raw file](https://github.com/RobotLocomotion/drake/blob/95efd3686b9f1c7217922a74d9db234cd5c6219d/planning/approximate_convex_cover_builder_base.h#L19)):*
> ```objc
> using geometry::optimization::ConvexSet;
> using geometry::optimization::ConvexSets;
> using graph_algorithms::MaxCliqueSolverBase;
> ```

One concern I have is that we are too focused on using greedy clique covers. Depending on the sizes of the problems people might want to directly approximate MinCliqueCover instead of approximating MaxClique and then using that to greedily construct a clique cover. (Specifically, if people want to use ReduVCC or the like, the async clique solving and region inflation will not work)

**Comment by wernerpe** [comment]
*[`planning/approximate_convex_cover_builder_base.cc` line 25 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkpknqF2dD7EwbzK0_m:-NkpknqF2dD7EwbzK0_n:btvs18u) ([raw file](https://github.com/RobotLocomotion/drake/blob/95efd3686b9f1c7217922a74d9db234cd5c6219d/planning/approximate_convex_cover_builder_base.cc#L25)):*
> ```cpp
> // A very simple implementation of a thread-safe asynchronous queue for use when
> // exactly one threads fills the queue while one (or more) threads empties the
> // queue.
> ```

See comment about MaxClique vs MinCliqueCover in approximate_convex_.... .h

**Comment by wernerpe** [comment]
*[`planning/iris_from_clique_cover.cc` line 29 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkqJ-D4B2fKJSyDs0le:-NkqJ-D4B2fKJSyDs0lf:b-3h41jh) ([raw file](https://github.com/RobotLocomotion/drake/blob/95efd3686b9f1c7217922a74d9db234cd5c6219d/planning/iris_from_clique_cover.cc#L29)):*
> ```cpp
> class ConvexObstaclesVisibilityMaker final : public AdjacencyMatrixBuilderBase {
>  public:
>   explicit ConvexObstaclesVisibilityMaker(const ConvexSets& obstacles)
> ```

If I understand correctly, this is specific to the convex obstacles + standard iris case?

**Comment by wernerpe** [comment]
*[`planning/iris_from_clique_cover.cc` line 51 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkqJJvY2jgMDA34P9z2:-NkqJJvY2jgMDA34P9z3:bm3dumh) ([raw file](https://github.com/RobotLocomotion/drake/blob/95efd3686b9f1c7217922a74d9db234cd5c6219d/planning/iris_from_clique_cover.cc#L51)):*
> ```cpp
>       }
>       return true;
>     };
> ```

Why are we not using the already implemented checker class? This is what I was using for the python implementation.

**Comment by wernerpe** [comment]
I think we should be mindful of what all needs to be added to make this work for cspace. E.g. using the scenegraph collision checker / the visibilitygraph class instead of just checking if points are inside of sets.

**Review by AlexandreAmice — COMMENTED** [review]
Doesn't `visibility_graph_builder.cc/h` cover this?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-:-NkqL8Mj4Tej_Gb_i0Ky:b-dzzzh1)* status: 7 unresolved discussions, LGTM missing from assignees calderpg-tri,wernerpe, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`planning/iris_from_clique_cover.cc` line 29 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkqJ-D4B2fKJSyDs0le:-NkqKaE65_vZvSpx9Aio:b-4na2pv) ([raw file](https://github.com/RobotLocomotion/drake/blob/95efd3686b9f1c7217922a74d9db234cd5c6219d/planning/iris_from_clique_cover.cc#L29)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

If I understand correctly, this is specific to the convex obstacles + standard iris case?
</blockquote></details>

Yes. It is essentially meant to be the `collision_checker/visbility_graph` for the convex obstacle case.
___
*[`planning/iris_from_clique_cover.cc` line 51 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20615#-NkqJJvY2jgMDA34P9z2:-NkqKiTb5ePi4qV8_AVj:bfn69fj) ([raw file](https://github.com/RobotLocomotion/drake/blob/95efd3686b9f1c7217922a74d9db234cd5c6219d/planning/iris_from_clique_cover.cc#L51)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

Why are we not using the already implemented checker class? This is what I was using for the python implementation.
</blockquote></details>

It seems unnecessary to make a plant out of the convex obstacles? This is not how I expect normal IRIS users are operating, but I may be wrong.

**Comment by wernerpe** [comment]
Ah I got confused, iris_from_clique_cover only handles the convex obstacle case. Yes, that renders my previous comment obsolete :thumbsup:

**Comment by RussTedrake** [comment]
Should we close this in favor or #20831 ?

**Pull request closed without merging**
