### PR TITLE
Better error message for zero-duration trajectory segments in GcsTrajectoryOptimization.

### LINKED ISSUE #21722: Solving GcsTrajectoryOptimization with Minimum Duration Zero Leads to Cryptic Bug
### What happened?

If the user sets the minimum duration in regions to zero, this occasionally causes strange bugs in the construction of a `PiecewiseTrajectory`, when success would be expected. Here's a simple reproduction:
```
from pydrake.all import Point, Hyperrectangle, GcsTrajectoryOptimization

gcs = GcsTrajectoryOptimization(1)
start = gcs.AddRegions([Point([0])], 0)
goal = gcs.AddRegions([Point([1])], 0)
mid = gcs.AddRegions([Hyperrectangle([0], [1])], 1, h_min=0)

gcs.AddEdges(start, mid)
gcs.AddEdges(mid, goal)

gcs.SolvePath(start, goal)
```
Running this yields the following output:
```
INFO:drake:Solved GCS shortest path using Mosek with convex_relaxation=true and preprocessing=true and rounding.
INFO:drake:Finished 1 rounding solutions with Mosek, discarding 99 duplicate paths.
Failure at common/trajectories/piecewise_trajectory.cc:19 in PiecewiseTrajectory(): condition 'breaks_[i] - breaks_[i - 1] >= kEpsilonTime' failed.
```
I'll try to diagnose this and fix it sometime in the next couple of days.

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by cohnt**
Because `PiecewiseTrajectory` can't handle segments of zero length, GcsTrajectoryOptimization can have weird behavior is `h_min` is set to zero and there are no velocity limits. This provides a clearer error message.

I also changed the default value for `h_min` to be `1e-6`. This should make it less likely for users to encounter the error inadvertently, and also brings the C++ default argument in line with the Python default argument. (Currently, they are mismatched.)

Closes #21722. +@russtedrake for feature review, if you have time?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  small requests.  thanks for doing this.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-:-O2gSa5JAfNpCu5qYRim:b2vf6hl)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O2gRusJCBOOEmhlLGhP:-O2gRusJCBOOEmhlLGhQ:b-3uc8mp) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2fb6332cb3e0738e9d69c7fa07f353b7b24579e/planning/trajectory_optimization/gcs_trajectory_optimization.h#L13)):*
> ```objc
> #include "drake/common/trajectories/bezier_curve.h"
> #include "drake/common/trajectories/composite_trajectory.h"
> #include "drake/common/trajectories/piecewise_trajectory.h"
> ```

this should go in the cc file since it seems you don't need it for the header.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 553 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O2gSqVLARZdYyAgPhLg:-O2gSqVLARZdYyAgPhLh:b-jer2bo) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2fb6332cb3e0738e9d69c7fa07f353b7b24579e/planning/trajectory_optimization/gcs_trajectory_optimization.h#L553)):*
> ```objc
>   */
>   Subgraph& AddRegions(const geometry::optimization::ConvexSets& regions,
>                        int order, double h_min = 0, double h_max = 20,
> ```

let's change this one, too. 
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 2347 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O2gSUn-CAK-3ROq9Q5P:-O2gSUn-CAK-3ROq9Q5Q:b-vi644f) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2fb6332cb3e0738e9d69c7fa07f353b7b24579e/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L2347)):*
> ```cpp
>   gcs.AddEdges(middle, goal);
>   gcs.AddTimeCost();
>   DRAKE_EXPECT_THROWS_MESSAGE(gcs.SolvePath(start, goal), ".*zero duration.*");
> ```

there are two new calls to throw, but only one of those cases is caught here. is there a way to catch the other?

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O2gRusJCBOOEmhlLGhP:-O2jdpeT9Vlir475G65l:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2fb6332cb3e0738e9d69c7fa07f353b7b24579e/planning/trajectory_optimization/gcs_trajectory_optimization.h#L13)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this should go in the cc file since it seems you don't need it for the header.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 553 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O2gSqVLARZdYyAgPhLg:-O2jduDl-eujQceYg-hz:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2fb6332cb3e0738e9d69c7fa07f353b7b24579e/planning/trajectory_optimization/gcs_trajectory_optimization.h#L553)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

let's change this one, too.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 2347 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O2gSUn-CAK-3ROq9Q5P:-O2jdzMLAmrbDLZ3wjhq:b2w3d1l) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2fb6332cb3e0738e9d69c7fa07f353b7b24579e/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L2347)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

there are two new calls to throw, but only one of those cases is caught here. is there a way to catch the other?
</blockquote></details>

The last trajectory segment is handled differently during the rounding, hence the repeated code (and the second throw call). With that in mind, do you still want me to add a separate test case for that? If so, then I will do so.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 553 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O2gSqVLARZdYyAgPhLg:-O2k7awM5N7E0b6VLU2L:b-84a7zz) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2fb6332cb3e0738e9d69c7fa07f353b7b24579e/planning/trajectory_optimization/gcs_trajectory_optimization.h#L553)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Just realized this broke some of the test cases, which were using the default value (and expecting it to be 0). I've fixed all those instances now.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 2347 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O2gSUn-CAK-3ROq9Q5P:-O3I5wUZ93-kBa3X4haD:bucsxuq) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2fb6332cb3e0738e9d69c7fa07f353b7b24579e/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L2347)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

The last trajectory segment is handled differently during the rounding, hence the repeated code (and the second throw call). With that in mind, do you still want me to add a separate test case for that? If so, then I will do so.
</blockquote></details>

Yes please. The philosophy is that every line of code in the implementation should get run by one of the tests.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 2347 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O2gSUn-CAK-3ROq9Q5P:-O3IgBdO3p5As2q2FAhi:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2fb6332cb3e0738e9d69c7fa07f353b7b24579e/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L2347)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Yes please. The philosophy is that every line of code in the implementation should get run by one of the tests.
</blockquote></details>

Done.

**Comment by cohnt** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Review by RussTedrake — COMMENTED** [review]
:lgtm: 
+@sherm1 for platform review, please.

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-:-O4FcEUh3KsnGfpyYSWm:b-ypy4ms)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending one comment

> Reviewed 1 of 4 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-:-O4GjKhbBDxinWdan7xP:bac8jo0)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 1776 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O4GhkF58-DPUDfpEM4P:-O4GhkF58-DPUDfpEM4Q:bp1k7d8) ([raw file](https://github.com/RobotLocomotion/drake/blob/329ea4ed0bfc3adfc32beb776ec2deb065c0c446/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1776)):*
nit: it appears to me that h could be non-zero though very small here and still trip this error condition. Consider wording the error message to reflect that, something like
> ... returned a segment with near-zero duration. h_min must be at least {kEpsilonTime} ...

BTW just checking: is it true that velocity limits will prevent this error condition from occurring?
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 1804 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O4Gij3J5caqgv9vIYMO:-O4Gij3J5caqgv9vIYMP:b-n3tvf3) ([raw file](https://github.com/RobotLocomotion/drake/blob/329ea4ed0bfc3adfc32beb776ec2deb065c0c446/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1804)):*
> ```cpp
>         "GcsTrajectoryOptimization returned a trajectory segment with zero "
>         "duration. Make sure you set h_min to be nonzero for regions whose "
>         "subgraph order is larger than 1 or impose velocity limits.");
> ```

nit: same comment here

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 1776 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O4GhkF58-DPUDfpEM4P:-O4HZ5VeAawXtZhwEuxN:b-8hvjf9) ([raw file](https://github.com/RobotLocomotion/drake/blob/329ea4ed0bfc3adfc32beb776ec2deb065c0c446/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1776)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: it appears to me that h could be non-zero though very small here and still trip this error condition. Consider wording the error message to reflect that, something like
> ... returned a segment with near-zero duration. h_min must be at least {kEpsilonTime} ...

BTW just checking: is it true that velocity limits will prevent this error condition from occurring?
</blockquote></details>

I reworded the error message per your suggestion. I've also fixed the grammar -- it should be "regions whose subgraph order is at least 1". (Note that `num_control_points == order + 1`.)

Velocity limits *should* generally prevent this, since having duration zero in a subgraph with nonzero order requires infinite velocity. Indeed, I've always used the default `h_min=0`, and as long as there were velocity limits, I never ran into problems -- the bug only happened when I dropped the velocity constraints trying to produce a MWE for a different issue. Maybe there is some pathological case, but I'm not super concerned about it.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 1804 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21734#-O4Gij3J5caqgv9vIYMO:-O4H_oBaBpDxncq015ZD:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/329ea4ed0bfc3adfc32beb776ec2deb065c0c446/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1804)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: same comment here
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21734)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Pull request merged**
