### PR TITLE
Irb140 urdf

### PR DESCRIPTION
**Pull request by hongkai-dai**
1. Add robotiq hand to examples
2. Add a convex hull collision elements for ABB arm in irb_140_convhull.urdf
3. Add IRB 140 with robotiq hand
4. The joint1 and joint 3 in ABB arm urdf are in the opposite direction as the real robot. Change these two joints.

@gizatt , I got an error when I run `simulWithHand` even in the master branch, could you check it?

### CODE REVIEW

**Comment by gizatt** [comment]
simulWithHand works OK for me on your branch. What error are you getting?

Also, why has the robotiq_hand_description folder been added? It's definitely a todo to get the robotiq hand in its own Examples folder, but that particular code looks out of date. (It refers to the robotiq hand by a pretty old name...)

**Comment by hongkai-dai** [comment]
@gizatt  The error I got for simulWithHand is
```
Error in
NonlinearProgram/objectiveAndNonlinearConstraints
(line 568)
          [f(f_count+(1:obj.nlcon{i}.num_cnstr)),G(f_count+(1:obj.nlcon{i}.num_cnstr),obj.nlcon_xind_stacked{i})]
          = ...

Error in
NonlinearProgram/snopt/snopt_userfun
(line 1293)
        [f,G] =
        objectiveAndNonlinearConstraints(obj,x_all);
        
Error in snoptUserfun (line 6)
  [f,G] = SNOPT_USERFUN(x);

Error in NonlinearProgram/snopt (line
1356)
        [x_free,objval,exitflag,xmul,Fmul]
        =
        NonlinearProgramSnoptmex(x0_free,
        ...

Error in NonlinearProgram/solve (line
952)
            [x,objval,exitflag,infeasible_constraint_name]
            = snopt(obj,x0);

Error in
DynamicalSystem/resolveConstraints (line
325)
      [x,~,exitflag,infeasible_constraint_name]
      = solve(prog,x0);

Error in DrakeSystem/getInitialState
(line 53)
            [x0,success] =
            resolveConstraints(obj,x0);

Error in
TimeSteppingRigidBodyManipulator/getInitialState
(line 166)
      x0 = obj.manip.getInitialState();

Error in simulWithHand (line 24)
x0_hand = r_hand.getInitialState();
```
I copied the robotiq_hand_description from https://github.com/RobotLocomotion/Hands

**Comment by RussTedrake** [comment]
We already have a robotiq hand in drake master - it's probably even more up to date than the one in hands.  Please ref that one instead.

- Russ

**Comment by RussTedrake** [comment]
please definitely remove the redundant robotiq hand model.  also, the current protocol is to add the .obj files and .stl files, but not the .wrl files - since matlab will make the .wrl files from the .stl files (on the first call, and include them as local files in the directory so they will be there afterwards).

**Comment by RussTedrake** [comment]
seems like you'll also need to convert the convex hull wrls to stls/objs if you want them to be usable in the non-vrml viewers.

fwiw - i have the beginnings of a distributable mesh converter in https://github.com/RobotLocomotion/meshConverters -- it does not convert wrl to obj / stl yet, but it would be easy to add that support (I picked a tool that could do it).

**Comment by hongkai-dai** [comment]
I will close this pull request now as I need to make a lot of modifications, I will reopen the pull request once it is ready

**Comment by gizatt** [comment]
Hongkai -- I can't replicate your issue with simulWithHand -- is there any chance you have out of date or extraneous files floating around that might be interfering? (All files pointed to by the IRB140 class are tracked, so that causing a problem would be somewhat surprising...)

**Pull request closed without merging**
