### PR TITLE
Add CMake option to enable OpenMP

### LINKED ISSUE #19091: Add OpenMP selection in CMake builds
We offer CMake flags like `-DWITH_SNOPT=ON` to configure optional components of Drake.  However, we're missing one for OpenMP (e.g., `-DWITH_OPENMP`).

We should either add such an option, or provide documentation for how to do it manually (by setting `CFLAGS` uniformly for the entire downstream project).

Whatever we decide, we should fix CI jobs for "CMake Everything" on Ubuntu to turn on OpenMP.  Currently, it is off in CMake jobs but on in "Bazel Everything" jobs.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Fixes #19091.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20703)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20703)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware)

___
*[`CMakeLists.txt` line 472 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-NmvdvboCzVQ1ZlmLFCc:-Nmvdvbp-oF6WvcBjY1-:b67dhqc) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5fa8bb506d236268b6808ef7412c112705a29df/CMakeLists.txt#L472)):*
> ```CMake
> option(WITH_OPENMP "Build with support for OpenMP" OFF)
> 
> if(WITH_OPEN)
> ```

nit Typo `WITH_OPENMP`.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20703)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware)

___
*[`CMakeLists.txt` line 472 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-NmvdvboCzVQ1ZlmLFCc:-Nn4wGvbBLZxLmZQnIut:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5fa8bb506d236268b6808ef7412c112705a29df/CMakeLists.txt#L472)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Typo `WITH_OPENMP`.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
I'm not sure how you tested this locally, but for me it doesn't seem to be working:

```console
jwnimmer@call-cps:~/jwnimmer-tri/drake-build$ cmake ../drake -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_OPENMP=ON
...
-- Build files have been written to: /home/jwnimmer/jwnimmer-tri/drake-build
jwnimmer@call-cps:~/jwnimmer-tri/drake-build$ make
/usr/bin/cmake -S/home/jwnimmer/jwnimmer-tri/drake -B/home/jwnimmer/jwnimmer-tri/drake-build --check-build-system CMakeFiles/Makefile.cmake 0
...
[ 62%] Performing configure step for 'drake_cxx_python'
cd /home/jwnimmer/jwnimmer-tri/drake-build/drake_build_cwd && /usr/bin/bazel info --announce_rc
Starting local Bazel server and connecting to it...
ERROR: Config value 'openmp' is not defined in any .rc file
make[2]: *** [CMakeFiles/drake_cxx_python.dir/build.make:94: drake_cxx_python-prefix/src/drake_cxx_python-stamp/drake_cxx_python-configure] Error 2
make[2]: Leaving directory '/home/jwnimmer/jwnimmer-tri/drake-build'
make[1]: *** [CMakeFiles/Makefile2:842: CMakeFiles/drake_cxx_python.dir/all] Error 2
make[1]: Leaving directory '/home/jwnimmer/jwnimmer-tri/drake-build'
make: *** [Makefile:149: all] Error 2
```

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

For the record, I'll note that we do not have a 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-:-NnEoGrG-BBZ9H5aO_IA:bfmsyqm)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-NnAQGDG1FvLKHOfb-Q4:-NnAQGDG1FvLKHOfb-Q5:bvypycl) (no related file):*
nit The file `drake/cmake/bazel.rc.in` has the following comment, which is now slightly out of date:

```
# Match CMAKE_BUILD_TYPE as well as the WITH_FOO customizations for solvers.
build @BAZEL_CONFIG@
```

Probably just removing "for solvers" (saying just "... WITH_FOO customizations") would suffice as a fix.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-NnEohtYBWv_XsdfkyES:-NnEohtYBWv_XsdfkyET:bgruhsn) (no related file):*
BTW I think `drake-ci/driver/configurations/cmake.cmake` (and possibly `drake-ci/driver/environment.cmake`) will need some changes in support of this feature.  When performing a CMake build in https://drake-jenkins.csail.mit.edu/view/Everything/, we should set `-DWITH_OPENMP=ON` in the build (except not on macOS builds, because OpenMP is not supported there).

(I don't mind whatever PR order is easiest.  The CI change could happen _after_ this merges.)

___

**Review by jwnimmer-tri — COMMENTED** [review]
~For the record, I'll note that we do not have a~

*(oops, typo)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-:-NnEpPuG7l0azjn7NxqS:b-pbjxe4)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20703)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-NnAQGDG1FvLKHOfb-Q4:-NnFLgDUDUYaYVnP8GN_:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The file `drake/cmake/bazel.rc.in` has the following comment, which is now slightly out of date:

```
# Match CMAKE_BUILD_TYPE as well as the WITH_FOO customizations for solvers.
build @BAZEL_CONFIG@
```

Probably just removing "for solvers" (saying just "... WITH_FOO customizations") would suffice as a fix.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-NnEohtYBWv_XsdfkyES:-NnFLh8p5trE0plKi34T:b-liebts) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think `drake-ci/driver/configurations/cmake.cmake` (and possibly `drake-ci/driver/environment.cmake`) will need some changes in support of this feature.  When performing a CMake build in https://drake-jenkins.csail.mit.edu/view/Everything/, we should set `-DWITH_OPENMP=ON` in the build (except not on macOS builds, because OpenMP is not supported there).

(I don't mind whatever PR order is easiest.  The CI change could happen _after_ this merges.)
</blockquote></details>

I think it makes most sense to make the CI changes once this lands; that way CI isn't trying to use a non-existent option. (Also, IIUC, CMake CI must not be enabling OpenMP at all, presently?)

___

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule, please.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-:-NnFNW7u1CAAzIfqV_rc:bfqkacy)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-NnEohtYBWv_XsdfkyES:-NnFNIlu2sfEwi_c6y-0:be47oly) (no related file):*
> I think it makes most sense to make the CI changes once this lands; that way CI isn't trying to use a non-existent option.

Fine by me.  (Maybe this PR shouldn't "Fixes: ..." (close) the issue, though.)

> Also, IIUC, CMake CI must not be enabling OpenMP at all, presently?

Yes, that was my guess as well.

___

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm:
+(release notes: feature) 

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20703#-:-NnFUiXRDfknl4ZOBS3X:b55jxua)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
