### PR TITLE
[py yaml] Add support for Union[List[T], ...]

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20920.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20919)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
:lgtm: feature.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20919#-:-NqEgoTjBl05BwUmoZ4Y:b-n37teh)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20919#-NqEgqjv3-dioLr-ceaY:-NqEgqjv3-dioLr-ceaZ:b-qjwtbk) (no related file):*
BTW. I was reading a file-level comment in `yaml_test_typed.py`. I wonder if we need to "keep in sync" with `drake/common/yaml/test/example_structs.h` to add a similar C++ struct.
```
# To provide test coverage for all of the special cases of YAML loading, we'll
...
# and should be roughly kept in sync with the definitions in that file.
```

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20919)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20919#-NqEgqjv3-dioLr-ceaY:-NqEp_yY0fT0BHB7xw9j:b-sg8mty) (no related file):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. I was reading a file-level comment in `yaml_test_typed.py`. I wonder if we need to "keep in sync" with `drake/common/yaml/test/example_structs.h` to add a similar C++ struct.
```
# To provide test coverage for all of the special cases of YAML loading, we'll
...
# and should be roughly kept in sync with the definitions in that file.
```
</blockquote></details>

I added some comments.

___

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20919)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri platform :lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20919#-:-NqOElI1ApGtLgVU6ypd:b-227mr4)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),zachfang

**Pull request merged**
