### PR TITLE
Add ExternallyAppliedSpatialForceMultiplexer

### LINKED ISSUE #13139: Need a `ValueMultiplexer` or at very least `ExternalAppliedSpatialForceMultiplexer`
Carry-over from #12401, where we observed that there is only one "applied_spatial_force" input port on MultibodyPlant, which takes a `std::vector<ExternalAppliedSpatialForce<T>>`.  But some use cases will require multiple external forces, coming from different systems, to be applied to the same MBP.

The `ExternalAppliedSpatialForceMultiplexer` is an obvious solution.  But one could also do a nice, fully-type-erased implementation of a more generic `ValueMultiplexer` that multiplexes multiple `std::vector<Value>` into a single one at the output.  As usual, @jwnimmer-tri had some excellent thoughts on #12401.  Opening this issue so that we don't lose track of it.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #13139
Relates #16923

py plant:
- Remove unneeded qualifier for ExternallyAppliedSpatialForce
- test_propeller: Use body name rather than magic number

adder_test:
- Add check for discrete number of states
- Use std::make_unique instead of .reset()

\cc @amcastro-tri @jwnimmer-tri 

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@russtedrake Might you have time for quick feature review?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171#-:-NFBHILB1q_ImZX7IdKJ:bv2kip9)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: with just a few comments below.  thanks!
+@sherm1 for platform review, please.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171#-:-NFJ03wrCI1IAErdOZiK:b3ud4bg)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @EricCousineau-TRI and @sherm1)

___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFJ-GF-1_gOb1TZPX4l:-NFJ-GF-1_gOb1TZPX4m:bl9nc2t) ([raw file](https://github.com/robotlocomotion/drake/blob/62383a4f9eaafc05605e8a62c3ed712c5d2ce738/multibody/plant/externally_applied_spatial_force_multiplexer.h#L16)):*
> ```objc
> 
> @system
> name: ExternallyAppliedSpatialForceMultiplexer
> ```

nit: can we make it clear that the inputs are still std::vector<ExternallyAppliedSpatialForce> (as opposed to just ExternallyAppliedSpatialForce elements by themselves)
___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFIzcB302VvuoeYQ-g8:-NFIzcB302VvuoeYQ-g9:bphbjkt) ([raw file](https://github.com/robotlocomotion/drake/blob/62383a4f9eaafc05605e8a62c3ed712c5d2ce738/multibody/plant/externally_applied_spatial_force_multiplexer.h#L41)):*
> ```objc
>   */
> 
>   explicit ExternallyAppliedSpatialForceMultiplexer(int num_inputs);
> ```

nit: strange whitespace (between the comment and the method, but then no whitespace after...?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake and @sherm1)

___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFJ-GF-1_gOb1TZPX4l:-NFJEm1v1vNJCowD6fhY:bcpuz8q) ([raw file](https://github.com/robotlocomotion/drake/blob/62383a4f9eaafc05605e8a62c3ed712c5d2ce738/multibody/plant/externally_applied_spatial_force_multiplexer.h#L16)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: can we make it clear that the inputs are still std::vector<ExternallyAppliedSpatialForce> (as opposed to just ExternallyAppliedSpatialForce elements by themselves)
</blockquote></details>

Done, I think?
Though admittedly, this name is now super long.

Should I just revert, and denote input port types instead?
___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFIzcB302VvuoeYQ-g8:-NFJFIQj1YDNO6e1d6FP:b-qsx7uj) ([raw file](https://github.com/robotlocomotion/drake/blob/62383a4f9eaafc05605e8a62c3ed712c5d2ce738/multibody/plant/externally_applied_spatial_force_multiplexer.h#L41)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: strange whitespace (between the comment and the method, but then no whitespace after...?
</blockquote></details>

Done. Oops!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFJHcPe9iqoS6EJLC93:-NFJHcPe9iqoS6EJLC94:bhsajiq) (no related file):*
Working: Mark revision.

___

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFJ-GF-1_gOb1TZPX4l:-NFJtH645RzLlNQyzNPU:bf2vzxp) ([raw file](https://github.com/robotlocomotion/drake/blob/62383a4f9eaafc05605e8a62c3ed712c5d2ce738/multibody/plant/externally_applied_spatial_force_multiplexer.h#L16)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done, I think?
Though admittedly, this name is now super long.

Should I just revert, and denote input port types instead?
</blockquote></details>

I prefer the shorter name.  I just want it to be clear in the docs.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFJ-GF-1_gOb1TZPX4l:-NFK1Mhw2-yexV-oyzDY:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/62383a4f9eaafc05605e8a62c3ed712c5d2ce738/multibody/plant/externally_applied_spatial_force_multiplexer.h#L16)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I prefer the shorter name.  I just want it to be clear in the docs.
</blockquote></details>

OK Thanks!

**Review by sherm1 — COMMENTED** [review]
I also prefer the shorter name.

"Combining" forces usually means adding them together, which is what I expected here at first. I see that what is actually happening is concatenation, rather than combining. To avoid confusion, please consider saying that explicitly here and naming the output port "concatenated" rather than "combined".

Platform :lgtm: pending a few minor things.

> Reviewed 2 of 7 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171#-:-NFK0k6Y3XDuw3B-ET6V:b-ix2h9i)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 13 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK4gheC98SY4EaKxSP:-NFK4gheC98SY4EaKxSQ:bgfatyh) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/externally_applied_spatial_force_multiplexer.h#L13)):*
> ```objc
> 
> /**
> Combines multiple std::vector<>'s of ExternallyAppliedSpatialForce<T>.
> ```

BTW Combines->Concatenates

Also consider promising that the inputs are concatenated in order of input port number, or say explicitly that the concatenation order is undefined. (I mildly prefer the former because I think that's what users would expect.)
___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK0cx7Aq4kVrl-MVao:-NFK0cx7Aq4kVrl-MVap:b-7f6qmt) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/externally_applied_spatial_force_multiplexer.h#L22)):*
> ```objc
> - u(N-1)
> output_ports:
> - combined
> ```

BTW consider "concatenated" rather than "combined" per comment above
___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK1X8mCcRJKr44TfBd:-NFK1X8n9Wx_g3hYEq-M:b-7ugi49) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L16)):*
> ```cpp
> namespace {
> 
> using ListType = std::vector<ExternallyAppliedSpatialForce<double>>;
> ```

BTW better to tie this to the dut. Consider:



_Code snippet:_
```cpp
using ListType = 
    ExternallyAppliedSpatialForceMultiplexer<double>::ListType;
```
___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 75 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK3SO1B7hz_ge348sW:-NFK3SO27nVlLIPYYFEm:bbt53f5) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L75)):*
> ```cpp
> 
> // Tests that the system computes the correct sum.
> TEST_F(ExternallyAppliedSpatialForceMultiplexerTest, AddTwoVectors) {
> ```

nit: sum -> concatenation, AddTwoVectors -> ConcatenateTwoVectors
___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 94 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK3kMq7WxNtPOQDijo:-NFK3kMq7WxNtPOQDijp:b-tg3wav) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L94)):*
> ```cpp
> 
> // Asserts that adders have direct-feedthrough from all inputs to the output.
> TEST_F(ExternallyAppliedSpatialForceMultiplexerTest, AdderIsDirectFeedthrough) {
> ```

nit: adders, Adder -> multiplexers, Multiplexer

**Comment by jwnimmer-tri** [comment]
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 34 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK6waK4pPiGGrssteg:-NFK6waK4pPiGGrssteh:b-sq5f96) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/externally_applied_spatial_force_multiplexer.h#L34)):*
> ```objc
> 
>   using ValueType = ExternallyAppliedSpatialForce<T>;
>   using ListType = std::vector<ValueType>;
> ```

nit If we're going to publish these as public types, then we need to Doxygen-document them.

(My own preference would be to bury them in 'private' anyway.  They don't appear to be useful to users at all.)

**Comment by jwnimmer-tri** [comment]
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK0cx7Aq4kVrl-MVao:-NFK7N1-4wXB9FTVr0Le:by3yskr) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/externally_applied_spatial_force_multiplexer.h#L22)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider "concatenated" rather than "combined" per comment above
</blockquote></details>

FWIW my 2c would be just `y0` for consistency since that's what https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_multiplexer.html calls it and it likewise that system also does concatenation.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake and @sherm1)

___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 13 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK4gheC98SY4EaKxSP:-NFKvC6o9YsVkSz8bSDS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/externally_applied_spatial_force_multiplexer.h#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Combines->Concatenates

Also consider promising that the inputs are concatenated in order of input port number, or say explicitly that the concatenation order is undefined. (I mildly prefer the former because I think that's what users would expect.)
</blockquote></details>

Done.
___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK0cx7Aq4kVrl-MVao:-NFKvEH1ATRNksG_u74e:b90ixoh) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/externally_applied_spatial_force_multiplexer.h#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FWIW my 2c would be just `y0` for consistency since that's what https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_multiplexer.html calls it and it likewise that system also does concatenation.
</blockquote></details>

Done, going for `y0`
___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.h` line 34 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK6waK4pPiGGrssteg:-NFKvFckBuwyjBNDQhIM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/externally_applied_spatial_force_multiplexer.h#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If we're going to publish these as public types, then we need to Doxygen-document them.

(My own preference would be to bury them in 'private' anyway.  They don't appear to be useful to users at all.)
</blockquote></details>

Done.
___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK1X8mCcRJKr44TfBd:-NFKvGXi94J2Sy8UHJVo:b-np3rg3) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW better to tie this to the dut. Consider:
</blockquote></details>

OK Buried privately, but thanks!
___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 75 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK3SO1B7hz_ge348sW:-NFKvI3--f4pJ2IZ4XDx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L75)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: sum -> concatenation, AddTwoVectors -> ConcatenateTwoVectors
</blockquote></details>

Done.
___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 94 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK3kMq7WxNtPOQDijo:-NFKvI_d1EC_-fKJetWg:bwhevzm) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: adders, Adder -> multiplexers, Multiplexer
</blockquote></details>

Done. Removed qualifier (sufficiently informative, IMO)

**Comment by jwnimmer-tri** [comment]
*[`multibody/plant/externally_applied_spatial_force_multiplexer.cc` line 22 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFKvtKz7Mapcw1MCEp3:-NFKvtKz7Mapcw1MCEp4:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/b082bb854a9d2bb8496670263e6e9236e39f7921/multibody/plant/externally_applied_spatial_force_multiplexer.cc#L22)):*
> ```cpp
>     }
>     this->DeclareAbstractOutputPort(
>         "combined",
> ```

typo



_Suggestion:_
```cpp
"y0"
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake and @sherm1)

___
*[`multibody/plant/externally_applied_spatial_force_multiplexer.cc` line 22 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFKvtKz7Mapcw1MCEp3:-NFKxWd5EhSmObTMfZVZ:b-2aqurm) ([raw file](https://github.com/robotlocomotion/drake/blob/b082bb854a9d2bb8496670263e6e9236e39f7921/multibody/plant/externally_applied_spatial_force_multiplexer.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done. D'oh, thanks! Used `kUseDefaultName`

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 75 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK3SO1B7hz_ge348sW:-NFL-6xT1ZEgfnX7bzYh:blgzfyy) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L75)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still says "sum" in the comment above.
___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 94 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK3kMq7WxNtPOQDijo:-NFL-CSL9j_ZxbPWV4aX:baehis7) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L94)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Removed qualifier (sufficiently informative, IMO)
</blockquote></details>

Still says "adder" in the comment above

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake and @sherm1)

___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 75 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK3SO1B7hz_ge348sW:-NFL0Owi8p6t2hLFW81k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L75)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Still says "sum" in the comment above.
</blockquote></details>

Done.
___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 94 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK3kMq7WxNtPOQDijo:-NFL0Q48Ebi9GfkSgI6I:bncypct) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Still says "adder" in the comment above
</blockquote></details>

Done. Sorry!

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18171)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc` line 94 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18171#-NFK3kMq7WxNtPOQDijo:-NFL7AWX-W__q0p8nKLl:b-vqkjus) ([raw file](https://github.com/robotlocomotion/drake/blob/a6885463c9959dbc91e55747c9ac101f04afc478/multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc#L94)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Sorry!
</blockquote></details>

No worries!

**Pull request merged**
