### PR TITLE
[planning] Port kinematic trajectory optimization from anzu

### PR DESCRIPTION
**Pull request by RussTedrake**
+@jwnimmer-tri for feature review, please.

As discussed in https://docs.google.com/document/d/1foZ4Cg39mzYVUX-TRn3LubmuMAfUmFQbPFh5StHPa_w/edit, I've put this alongside the existing trajectory optimization classes.

I will add python bindings in a follow-up PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18113)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint for now.

If you decide to change folders, the updated first commit should reflect that directly (via a rebase amending the first commit with `git mv`); the second commit should not have any file moves.

> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18113#-:-NEWP9AB1meMZIaVnRkp:bquh9ar)* status: 13 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @RussTedrake)

___
*[`systems/trajectory_optimization/BUILD.bazel` line 171 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWFVeNBv17LHJCyFqH:-NEWFVeNBv17LHJCyFqI:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/BUILD.bazel#L171)):*
> ```Starlark
>     deps = [
>         ":kinematic_trajectory_optimization",
>         "@drake//solvers:constraint",
> ```

typo



_Suggestion:_
```Starlark
"//solvers:constraint
```
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWD0kA1Z3sPC3W_nSd:-NEWD0kA1Z3sPC3W_nSe:bnbngdz) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L18)):*
> ```objc
> 
> namespace drake {
> namespace trajectory_optimization {
> ```

On one hand, I think dropping the `namespace systems` here vs its neighbors is just fine -- it's allowed by the GSG, and seems well-enough justified.

However, it might pose a challenge when adding pydrake bindings.  There is no `pydrake.trajectory_optimization` module, and it seems a bit of shame to add a new one only to deprecate it soon after for the final module name.

Maybe it makes more sense to put this into `drake/planning/trajectory_optimization/...` from the get-go, with the expectation that the other things here will get moved into place soon after.  Then the python bindings could be `pydrake.planning.KinematicTrajectoryOptimization` from the get-go, no further changes Python nor C++.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWNUhY95s_gqtTN-C5:-NEWNUhY95s_gqtTN-C6:b-rmk7ic) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L21)):*
> ```objc
> 
> /** Optimizes the position trajectory of a multibody model. The trajectory is
> represented as a B-form spline. */
> ```

When I skimmed this in Anzu again for the first time a few days ago, the one thing that gave me pause in a few instances was the space of the optimization.

I think it's worth saying something about us optimizing using C-space or q vector in the overview here, to set the stage.

Also, I think this class assumes qdot == v?  If yes, it should say so here as well.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWMM3O3udzcAVFxVDC:-NEWMM3O3udzcAVFxVDD:b-chqkaq) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L82)):*
> ```objc
> 
>   /** Adds a linear cost on the duration of the trajectory. */
>   void AddDurationCost(double weight = 1.);
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals

Ditto throughout.

(Either `1` or `1.0` is fine; only `1.` is verboten.)



_Suggestion:_
```objc
1.0
```
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWOgka8eL6rvrQTq0q:-NEWOgka8eL6rvrQTq0r:b-rus22) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L100)):*
> ```objc
>   void AddGenericPositionConstraint(
>       const std::shared_ptr<solvers::Constraint>& constraint,
>       const std::array<double, 2>& plan_interval,
> ```

nit I presume we have a `@pre` that `plan_interval[0] <= plan_interval[1]`?
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 129 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWGOwN3FalCyMf6mIg:-NEWGOwN3FalCyMf6mIh:b-r643p8) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L129)):*
> ```objc
>   }
> 
>   // TODO(russt): Support passing a solver instead of only using Snopt.
> ```

I would have thought calling `ChooseBestSolver` would be the natural next step to undo the hard-coded Snopt, instead of specifying one explicitly?



_Suggestion:_
```objc
// TODO(russt): Support passing a solver or using ChooseBestSolver
// instead of only using Snopt.
```
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 143 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWOt4o0f02HbKFLBmk:-NEWOt4o0f02HbKFLBml:bykqsu5) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L143)):*
> ```objc
>   ComputeFirstSolution(
>       std::vector<KinematicTrajectoryOptimization>* programs,
>       std::optional<double> min_duration = std::nullopt);
> ```

The API docs don't explain `min_duration` at all.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 173 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWOzo_8Uui-4AOcDg1:-NEWOzo_8Uui-4AOcDg2:bn8m8eg) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L173)):*
> ```objc
>   }
> 
>   void set_num_validation_points(int num_evaluation_points) {
> ```

Missing API docs for all three of these setters.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 204 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWP6vZ1sqxADx_YpzC:-NEWP6vZ1sqxADx_YpzD:b-rus22) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L204)):*
> ```objc
>   void AddLinearConstraint(const symbolic::Formula& f,
>                            const std::array<double, 2>& plan_interval = {
>                                {0.0, 1.0}});
> ```

nit I presume we have a `@pre` that `plan_interval[0] <= plan_interval[1]`?
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 226 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWEtqw8762ogcwVYbQ:-NEWEtqw8762ogcwVYbR:b-gc3zk) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L226)):*
> ```objc
>   // Returns a placeholder decision variable (not actually declared as a
>   // decision variable in the MathematicalProgram) associated with the
>   // generalized acceleration vector.
> ```

nit Inconsistent formatting of private API commands.  Either use `/* */` for these two private functions to match the API comments on `UpdateGenericConstraints` etc private functions below, or alternatively switch the below to use `//` to match here.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 243 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWN-IP55CA8qL1WsEd:-NEWN-IP55CA8qL1WsEe:b-nqmoe) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L243)):*
> ```objc
> 
>   void AddQuadraticCost(const symbolic::Expression& expression,
>                         const std::array<double, 2>& plan_interval = {{0, 1}});
> ```

nit The `plan_interval` is never set to anything other than this.  There's no reason for it to be an parameter.

Ditto for AddLinearCost below.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 330 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWJHl16hhcBJx4xvGj:-NEWJHl16hhcBJx4xvGk:b-xthv87) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L330)):*
> ```objc
>   int initial_num_evaluation_points_{3};
> 
>   solvers::SolverOptions solver_options_;
> ```

There is something subtle going on here which needs a comment somewhere.

The `prog_` already has a set of SolverOptions, and we always have a `prog_` (it's never nullptr).  So why don't we just use the prog's SolverOptions for customization?

It's because we will reset `prog_` over and over again.  We've chosen to store the options separately to save the trouble of `prog_->SetSolverOptions(old_prog->solver_options())` during the reset.
___
*[`systems/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc` line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWM4spE5fx9XfoWnW3:-NEWM4sq3A1_5OCnJpgL:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc#L21)):*
> ```cpp
> std::shared_ptr<ExpressionConstraint> MakeExpressionConstraint(int num) {
>   VectorXDecisionVariable position(num);
>   for (int i = 0; i < num; i++)
> ```

nit



_Suggestion:_
```cpp
++i
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18113)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWD0kA1Z3sPC3W_nSd:-NEWcG959DaLzLCSvyrv:bd4u6nx) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On one hand, I think dropping the `namespace systems` here vs its neighbors is just fine -- it's allowed by the GSG, and seems well-enough justified.

However, it might pose a challenge when adding pydrake bindings.  There is no `pydrake.trajectory_optimization` module, and it seems a bit of shame to add a new one only to deprecate it soon after for the final module name.

Maybe it makes more sense to put this into `drake/planning/trajectory_optimization/...` from the get-go, with the expectation that the other things here will get moved into place soon after.  Then the python bindings could be `pydrake.planning.KinematicTrajectoryOptimization` from the get-go, no further changes Python nor C++.
</blockquote></details>

Done.  This was just an oversight on my part.  My intention was to put it in the same namespace / python bindings file as the other trajectory optimization classes.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWNUhY95s_gqtTN-C5:-NEWcZdu-x2isMClChHu:bc2y3k) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When I skimmed this in Anzu again for the first time a few days ago, the one thing that gave me pause in a few instances was the space of the optimization.

I think it's worth saying something about us optimizing using C-space or q vector in the overview here, to set the stage.

Also, I think this class assumes qdot == v?  If yes, it should say so here as well.
</blockquote></details>

Done.  in my view the positions of a multibody plant are always q, unambiguously, but i've tried to make it more clear.  There is also no explicit relationship to MultibodyPlant anywhere in this code.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWOgka8eL6rvrQTq0q:-NEWfVJiDMLwx1kgGaeO:bvq00tw) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L100)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I presume we have a `@pre` that `plan_interval[0] <= plan_interval[1]`?
</blockquote></details>

Done. We do now.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 129 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWGOwN3FalCyMf6mIg:-NEWfqXO66RAxwPzQUmd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L129)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I would have thought calling `ChooseBestSolver` would be the natural next step to undo the hard-coded Snopt, instead of specifying one explicitly?
</blockquote></details>

Done.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 143 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWOt4o0f02HbKFLBmk:-NEWniMOBXPhAD9WtPH4:b-kvymk9) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The API docs don't explain `min_duration` at all.
</blockquote></details>

I am on the fence about this method.  It seems not very pure and adds a lot of complexity.  Clearly it was needed for the anzu workflow.  i am thinking that maybe we purge it here, and add a workspace method to replace it in anzu?

The alternative, I think, is to enlist siyuan or calder to help me document it properly (not just for what it does, but why it does it!)

If this gets removed, then initial_num_evaluation_points could be num_evaluation_points, and num_validation_points, max_control_points, AddKnots, and UpdateGenericConstraints could potentially disappear (into the workspace method).
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 173 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWOzo_8Uui-4AOcDg1:-NEWoy8zEuQiXIkQHKIP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L173)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing API docs for all three of these setters.
</blockquote></details>

Done.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 204 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWP6vZ1sqxADx_YpzC:-NEWpL7r0dO4KQCKkqFV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L204)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I presume we have a `@pre` that `plan_interval[0] <= plan_interval[1]`?
</blockquote></details>

Done.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 226 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWEtqw8762ogcwVYbQ:-NEWpZnm809XK0XRgpNO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L226)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Inconsistent formatting of private API commands.  Either use `/* */` for these two private functions to match the API comments on `UpdateGenericConstraints` etc private functions below, or alternatively switch the below to use `//` to match here.
</blockquote></details>

Done.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 243 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWN-IP55CA8qL1WsEd:-NEWqUA-7Nxdhj0OPGZ-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L243)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The `plan_interval` is never set to anything other than this.  There's no reason for it to be an parameter.

Ditto for AddLinearCost below.
</blockquote></details>

Done.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 330 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWJHl16hhcBJx4xvGj:-NEWqePjDBbulnI9fFWw:b-p9qlai) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L330)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is something subtle going on here which needs a comment somewhere.

The `prog_` already has a set of SolverOptions, and we always have a `prog_` (it's never nullptr).  So why don't we just use the prog's SolverOptions for customization?

It's because we will reset `prog_` over and over again.  We've chosen to store the options separately to save the trouble of `prog_->SetSolverOptions(old_prog->solver_options())` during the reset.
</blockquote></details>

Agreed.  This is another thing that we could simply purge if we remove `ComputeFirstSolution`.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18113)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @RussTedrake)

___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 143 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWOt4o0f02HbKFLBmk:-NEX2946EBorWWPOPGS2:b-xne5u0) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L143)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I am on the fence about this method.  It seems not very pure and adds a lot of complexity.  Clearly it was needed for the anzu workflow.  i am thinking that maybe we purge it here, and add a workspace method to replace it in anzu?

The alternative, I think, is to enlist siyuan or calder to help me document it properly (not just for what it does, but why it does it!)

If this gets removed, then initial_num_evaluation_points could be num_evaluation_points, and num_validation_points, max_control_points, AddKnots, and UpdateGenericConstraints could potentially disappear (into the workspace method).
</blockquote></details>

Choosing exactly how to capture the features we want into a useful API design goes a bit beyond my expertise here.  Having read through the code more carefully now, it does seem plausible to me to split out this function, but I might not be the best person to ask.

If it does get split, a natural home seems to be `optimize_manipulation_trajectory` (which would stay in Anzu only, at least for now).  Depending on which function points need to be exposed for unit testing, it could plausibly even live in the cc file entirely, not even declared in the header.

If it does get split out, then the tactic to do that is to open an Anzu PR with that refactoring, review it, and merge it.  Then afterwards, replace the first commit in this PR with the fresh copies of the h/cc/test files from Anzu.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18113)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @RussTedrake)

___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 42 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEXvTZb44yF7P5cHioh:-NEXvTZc0me5T01w2pxy:bue7e7z) ([raw file](https://github.com/robotlocomotion/drake/blob/d477729838cda4ba967564e6e9b7ec3577db4c9d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L42)):*
> ```objc
>   by a B-form spline with the same order and number of control points as the
>   initial guess, `position_curve_seed`. */
>   KinematicTrajectoryOptimization(
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Implicit_Conversions



_Suggestion:_
```objc
explicit KinematicTrajectoryOptimization
```
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.cc` line 71 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEXy3KYDvFCTX03il1l:-NEXy3KYDvFCTX03il1m:bh08kw2) ([raw file](https://github.com/robotlocomotion/drake/blob/d477729838cda4ba967564e6e9b7ec3577db4c9d/systems/trajectory_optimization/kinematic_trajectory_optimization.cc#L71)):*
> ```cpp
>                          wrapped_constraint_->num_vars());
>     }
>     wrapped_constraint_->Eval(x_sum, y);
> ```

The math that underlies summing up some decision variable inputs here is not clear to me.

I seem to recall that it's bspline magic, but I don't think the math is explained anywhere in the h or cc files.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.cc` line 80 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEXvGz71FA4kbeDXnXv:-NEXvGz71FA4kbeDXnXw:b377c3n) ([raw file](https://github.com/robotlocomotion/drake/blob/d477729838cda4ba967564e6e9b7ec3577db4c9d/systems/trajectory_optimization/kinematic_trajectory_optimization.cc#L80)):*
> ```cpp
>   }
> 
>   int numOutputs() const { return wrapped_constraint_->num_outputs(); }
> ```

nit To my first reading, `numOutputs()` is dead code.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.cc` line 433 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEXtzMnA8E5chmWGxiY:-NEXtzMnA8E5chmWGxiZ:b-z8t1tj) ([raw file](https://github.com/robotlocomotion/drake/blob/d477729838cda4ba967564e6e9b7ec3577db4c9d/systems/trajectory_optimization/kinematic_trajectory_optimization.cc#L433)):*
> ```cpp
>     const ConstraintWrapper& constraint, MathematicalProgram* prog) const {
>   DRAKE_ASSERT(prog != nullptr);
>   log()->info("Adding generic position constraint at {} points.",
> ```

nit All uses of `log()->info(...)` throughout this file are too verbose.

Successfully calculating a trajectory optimization should _not_ print anything to the console.  Such messages would log too much output when optimizing using dozens of threads at once, or as part of a motion control loop.
___
*[`systems/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc` line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEXz6HO-sLTtaMmfs2Q:-NEXz6HO-sLTtaMmfs2R:be8qtp9) ([raw file](https://github.com/robotlocomotion/drake/blob/d477729838cda4ba967564e6e9b7ec3577db4c9d/systems/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc#L1)):*
> ```cpp
> #include "systems/trajectory_optimization/kinematic_trajectory_optimization.h"
> ```

This unit test apparently only serves to demonstrate a lack of segfaults.  There's not a single gtest `EXPECT_...` condition anywhere in it.

At minimum that's surprising enough that it needs an overview comment explaining why we don't need to check anything, but I suspect the reality is that we're just missing a lot of important `EXPECT` conditions and the test needs surgery.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18113)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.h` line 143 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEWOt4o0f02HbKFLBmk:-NEYah0vEYDuF1j5rcWe:b-dafztm) ([raw file](https://github.com/robotlocomotion/drake/blob/bc169a3877b6f5b04691d2a0cb8ce1a18a96936d/systems/trajectory_optimization/kinematic_trajectory_optimization.h#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Choosing exactly how to capture the features we want into a useful API design goes a bit beyond my expertise here.  Having read through the code more carefully now, it does seem plausible to me to split out this function, but I might not be the best person to ask.

If it does get split, a natural home seems to be `optimize_manipulation_trajectory` (which would stay in Anzu only, at least for now).  Depending on which function points need to be exposed for unit testing, it could plausibly even live in the cc file entirely, not even declared in the header.

If it does get split out, then the tactic to do that is to open an Anzu PR with that refactoring, review it, and merge it.  Then afterwards, replace the first commit in this PR with the fresh copies of the h/cc/test files from Anzu.
</blockquote></details>

OK.  I'll bring the relevant changes from this PR back into anzu and do the cleanup there; then come back to this one.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.cc` line 71 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEXy3KYDvFCTX03il1l:-NEYbivM3bmCV2LoA2ns:bnzp2df) ([raw file](https://github.com/robotlocomotion/drake/blob/d477729838cda4ba967564e6e9b7ec3577db4c9d/systems/trajectory_optimization/kinematic_trajectory_optimization.cc#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The math that underlies summing up some decision variable inputs here is not clear to me.

I seem to recall that it's bspline magic, but I don't think the math is explained anywhere in the h or cc files.
</blockquote></details>

i don't think this part is so magical; it is just a polynomial evaluation (sum of basis * vars).  Getting the coefficients and the correct subset of the vars (which happens below), is more magical, but is pretty standard for b-splines.
___
*[`systems/trajectory_optimization/kinematic_trajectory_optimization.cc` line 433 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEXtzMnA8E5chmWGxiY:-NEYcq-b6Z8T4kuCEYlR:b21flcw) ([raw file](https://github.com/robotlocomotion/drake/blob/d477729838cda4ba967564e6e9b7ec3577db4c9d/systems/trajectory_optimization/kinematic_trajectory_optimization.cc#L433)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit All uses of `log()->info(...)` throughout this file are too verbose.

Successfully calculating a trajectory optimization should _not_ print anything to the console.  Such messages would log too much output when optimizing using dozens of threads at once, or as part of a motion control loop.
</blockquote></details>

Done.  Agreed!  I almost removed them before myself.
___
*[`systems/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc` line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18113#-NEXz6HO-sLTtaMmfs2Q:-NEYdExj1uj5bsYhohLy:b-72ec1j) ([raw file](https://github.com/robotlocomotion/drake/blob/d477729838cda4ba967564e6e9b7ec3577db4c9d/systems/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This unit test apparently only serves to demonstrate a lack of segfaults.  There's not a single gtest `EXPECT_...` condition anywhere in it.

At minimum that's surprising enough that it needs an overview comment explaining why we don't need to check anything, but I suspect the reality is that we're just missing a lot of important `EXPECT` conditions and the test needs surgery.
</blockquote></details>

Will address in the anzu PR.

**Comment by RussTedrake** [comment]
Adding "do not review" until I sort out the anzu side.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18113)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master

**Comment by RussTedrake** [comment]
I'm making progress with a more-significant-than-I-expected cleanup in anzu.  will reopen a fresh PR from there soon.  closing this version.

**Pull request closed without merging**
