### PR TITLE
add signal-scope as optional external

### PR DESCRIPTION
**Pull request by patmarion**

### CODE REVIEW

**Comment by patmarion** [comment]
I can rebase and push a new version of this.

**Comment by patmarion** [comment]
@RussTedrake I've fixed the commit so it's able to merge again

**Comment by patmarion** [comment]
Anything I can do to help push this along?

**Comment by RussTedrake** [comment]
I'm pulling as fast as i can now that the builds are healthier.

**Comment by RussTedrake** [comment]
install missing prereq on drake001:
https://github.com/mitdrc/signal-scope/issues/10

and manually confirmed that it builds aok now.

**Pull request merged**
