### PR TITLE
Remove drake/matlab/{solvers,systems}

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Also remove `drake/matlab/util/qpSpline` which depends on `matlab/solvers`.

Relates #6369.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6420)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.

Note that Jenkins will fail on this PR until #6421 is merged first, but I've confirmed this passes when tested in conjunction with #6421.

(Do not merge until I've assigned additional review.)

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 652 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6420#-:-KnZ27vn4_lY1pVil1Gu:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for all review, please.

**Comment by sherm1** [comment]
Wow, that makes me a little sad. Those 652 files represent a lot of hard work and significant accomplishment in their day. RIP! :lgtm:

---

Reviewed 652 of 652 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6420#-:-KnZx_YGY7UNwjCzy5mv:b-yjndkt)*

**Pull request merged**
