### PR TITLE
Remove glib as a public dependency of lcm

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates to #7764.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7765)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7765#-:-L2vn4M5y8Ez1OTeTaEx:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

Maybe (separately) the `pkg_config_repository` should allow the caller to turn off `--static`?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7765#-:-L2w3o6sxNJs7dotWuF7:b-jp1yst)*

**Comment by jamiesnape** [comment]
> Maybe (separately) the pkg_config_repository should allow the caller to turn off --static?

Yes, I will PR something shortly.

**Pull request merged**
