### PR TITLE
Add a tolerance for the RgbdCamera unit test

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
* Rename AssertNE to AssertNear and make use of template
* Replace EXPECT_EQ with AssertNear

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5504)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@sammy-tri both level review please since this is a small change.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5504#-:-KfHxzt76TLZr2o7ELOb:b-edw8p8)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5504#-KfI8kDjCSmkf3SLmaeS:-KfI8kDjCSmkf3SLmaeT:bq42ymw) ([raw file](https://github.com/robotlocomotion/drake/blob/78b99e2ae5d8fde92ed20369a0c816ad10b6ec93/drake/systems/sensors/test/rgbd_camera_test.cc#L153)):*
> ```cpp
>   const double b = static_cast<double>(value_b);
>   const double t = static_cast<double>(tolerance);
>   ASSERT_NEAR(a, b, t);
> ```

(apologies in advance for this one).  Trying to reason about floating point values as if they're integers makes me nervous because things so rarely come out exactly at integer values...   in this case it's probably safe because no arithmetic has been performed after the cast, but if that's what we're asserting I think a comment  saying so would be wise at the minimum.

Does this not compile/work if value_a, value_b, and value_c are of type `int` and then you do an ASSERT_LE() on the absolute value like before?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5504)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/test/rgbd_camera_test.cc, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5504#-KfI8kDjCSmkf3SLmaeS:-KfIBpy7wD8avaoxae-I:bg4tdw9) ([raw file](https://github.com/robotlocomotion/drake/blob/78b99e2ae5d8fde92ed20369a0c816ad10b6ec93/drake/systems/sensors/test/rgbd_camera_test.cc#L153)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

(apologies in advance for this one).  Trying to reason about floating point values as if they're integers makes me nervous because things so rarely come out exactly at integer values...   in this case it's probably safe because no arithmetic has been performed after the cast, but if that's what we're asserting I think a comment  saying so would be wise at the minimum.

Does this not compile/work if value_a, value_b, and value_c are of type `int` and then you do an ASSERT_LE() on the absolute value like before?
</blockquote></details>

Thanks for your comment!

No. It worked. 

The reason I changed is that I would need to use `AssertLe` for `int` too and then when I changed it to be template version, I jest felt weird since it's casting `int` to `int`when T is `int`.
If that would be OK, I'm happy to get this back to the former version with template.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5504)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5504#-KfI8kDjCSmkf3SLmaeS:-KfIaWwQKS6pz5gA3FX0:b8zg68r) ([raw file](https://github.com/robotlocomotion/drake/blob/78b99e2ae5d8fde92ed20369a0c816ad10b6ec93/drake/systems/sensors/test/rgbd_camera_test.cc#L153)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Thanks for your comment!

No. It worked. 

The reason I changed is that I would need to use `AssertLe` for `int` too and then when I changed it to be template version, I jest felt weird since it's casting `int` to `int`when T is `int`.
If that would be OK, I'm happy to get this back to the former version with template.

</blockquote></details>

I was thinking more like this if it compiles (no templates since I think you can pass a uint8_t to a function expecting an int without the compiler complaining?):
```
void AssertIntNear(int value_a, int value_b, int value_c) {
  ASSERT_LE(std::abs(value_a - value_b), value_t);
}
```

Or if that doesn't work, yeah, the older version using templates with the sometimes redundant cast.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5504)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5504#-:-KfIfcGZar3p2TOp6e74:bnfp4nl)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5504#-:-KfIfgBHZWXJ5Nf8PeeX:b-s794vx)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/test/rgbd_camera_test.cc, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5504#-KfI8kDjCSmkf3SLmaeS:-KfJ8Dd7y7Ky_7VlQJrR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/78b99e2ae5d8fde92ed20369a0c816ad10b6ec93/drake/systems/sensors/test/rgbd_camera_test.cc#L153)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Worked without any compiler warnings and errors.

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5504)*

**Pull request merged**
