### PR TITLE
[math] Move code from rotation_matrix.h to cc

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@jwnimmer-tri 
Perhaps you can also platform review too? 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-:-NRAv8c_4m0xGjDSRTQH:bo8v0f8)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`math/rotation_matrix.h` line 636 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRAwJf11zOH0fmW1EGl:-NRAwJf2-MRYAQ5i9ROj:buivzcd) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a188a1816eec5d27d6944a3aab818c6208e8f1b/math/rotation_matrix.h#L636)):*
> ```objc
>   /// (Internal use only) Constructs a RotationMatrix without initializing the
>   /// underlying 3x3 matrix. Here for use by RigidTransform but no one else.
>   explicit RotationMatrix(internal::DoNotInitializeMemberFields) {}
> ```

We already have a "do not init" constructor.  Why do we need the new "bool" one 20 lines below?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`math/rotation_matrix.cc` line 454 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRAybJp7olufRMhBbxE:-NRAybJp7olufRMhBbxF:b-2htwdf) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a188a1816eec5d27d6944a3aab818c6208e8f1b/math/rotation_matrix.cc#L454)):*
> ```cpp
>   RotationMatrix<T> R_BC(internal::DoNotInitializeMemberFields{});
>   if constexpr (std::is_same_v<T, double>) {
>     internal::ComposeRinvR(*this, R_AC, &R_BC);
> ```

@sherm1 please check this.

My understanding of your work is that this ComposeRintR really needs to remain in the header file.

I'd certainly buy (and prefer) having the `else` body live in the cc file, but I'm not sure about the `if` body.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mitiguy)

___
*[`math/rotation_matrix.h` line 413 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NREPHxwCrgnGG3LbI7G:-NREPHxwCrgnGG3LbI7H:b-5rqa31) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a188a1816eec5d27d6944a3aab818c6208e8f1b/math/rotation_matrix.h#L413)):*
> ```objc
>   /// @note It is possible (albeit improbable) to create an invalid rotation
>   /// matrix by accumulating round-off error with a large number of multiplies.
>   RotationMatrix<T> InvertAndCompose(const RotationMatrix<T>& other) const;
> ```

minor: this method should remain inline
___
*[`math/rotation_matrix.cc` line 454 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRAybJp7olufRMhBbxE:-NREODX07VZ5lll3XVQM:bn6brny) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a188a1816eec5d27d6944a3aab818c6208e8f1b/math/rotation_matrix.cc#L454)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sherm1 please check this.

My understanding of your work is that this ComposeRintR really needs to remain in the header file.

I'd certainly buy (and prefer) having the `else` body live in the cc file, but I'm not sure about the `if` body.
</blockquote></details>

Thanks for the heads-up! Yes, these should remain inline. It's not that they wouldn't function correctly like this, but that the whole point of them is to speed up these measured hot-spot operations. Adding unnecessary linkage overhead partially defeats that purpose.

All of these methods meet our standard for inline functions -- consider the important case where T==double. This method is literally a single executable line, just the call to ComposeRinvR(), with return value optimization eliminating the temporary variable.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @sherm1)

___
*[`math/rotation_matrix.cc` line 454 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRAybJp7olufRMhBbxE:-NREQNRW5Vjwhh3KJTKK:b-48puhy) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a188a1816eec5d27d6944a3aab818c6208e8f1b/math/rotation_matrix.cc#L454)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Thanks for the heads-up! Yes, these should remain inline. It's not that they wouldn't function correctly like this, but that the whole point of them is to speed up these measured hot-spot operations. Adding unnecessary linkage overhead partially defeats that purpose.

All of these methods meet our standard for inline functions -- consider the important case where T==double. This method is literally a single executable line, just the call to ComposeRinvR(), with return value optimization eliminating the temporary variable.
</blockquote></details>

When you say "all of" do you mean

"all of the things we call within InvertAndCompose like inverse and operator-mul"

or do you mean

"all of the changes in this PR"

?

Because to me, `ToQuaternion` does _not_ meet the definition of okay-to-inline, for example.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mitiguy)

___
*[`math/rotation_matrix.cc` line 454 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRAybJp7olufRMhBbxE:-NREYlVY1pgE1yQVWh6I:b-3wj06u) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a188a1816eec5d27d6944a3aab818c6208e8f1b/math/rotation_matrix.cc#L454)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When you say "all of" do you mean

"all of the things we call within InvertAndCompose like inverse and operator-mul"

or do you mean

"all of the changes in this PR"

?

Because to me, `ToQuaternion` does _not_ meet the definition of okay-to-inline, for example.
</blockquote></details>

Apologies for ambiguity. By "all of" I meant the four methods that use bespoke AVX functions for speed (two of those are in RotationMatrix and two in RigidTransform). Only one of those four appears to be relocated in this PR and that's the only thing I would like to see moved back to inline. I agree that the other relocations here are good.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @sherm1)

___
*[`math/rotation_matrix.cc` line 454 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRAybJp7olufRMhBbxE:-NRE_0M049oFnxOmvf-H:b2xlyuj) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a188a1816eec5d27d6944a3aab818c6208e8f1b/math/rotation_matrix.cc#L454)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Apologies for ambiguity. By "all of" I meant the four methods that use bespoke AVX functions for speed (two of those are in RotationMatrix and two in RigidTransform). Only one of those four appears to be relocated in this PR and that's the only thing I would like to see moved back to inline. I agree that the other relocations here are good.
</blockquote></details>

Thanks!  Fully agree.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-:-NRF7jiO9v80dWbzIVnh:b9krqcj)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRF7m-00JmaHIQpk8Lk):*
I'll plan to fix the commit message when I squash, but in case you beat me to it:

This PR does more than just move some code.  It introduces sanity-checks on `theta`.  We should mention that in the commit message, since that's the actual user-visible effect of this change.
___
*[`math/rotation_matrix.cc` line 58 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRF7OTw3Fm-Z86cs9bV:-NRF7OTw3Fm-Z86cs9bW:bfdu7n7) ([raw file](https://github.com/RobotLocomotion/drake/blob/96ed675cff895c90be489e19220eddfd71e47891/math/rotation_matrix.cc#L58)):*
> ```cpp
> RotationMatrix<T> RotationMatrix<T>::MakeXRotation(const T& theta) {
>   using std::isfinite;
>   DRAKE_DEMAND(isfinite(theta));
> ```

nit Nowhere else in this class aborts the problem if the user provides wrong input.  We should maintain that convention in the new code here as well.

Likewise the other two MakeRotation factory functions.



_Suggestion:_
```cpp
DRAKE_THROW_UNLESS(isfinite(theta));
```

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRF7m-00JmaHIQpk8Lk):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'll plan to fix the commit message when I squash, but in case you beat me to it:

This PR does more than just move some code.  It introduces sanity-checks on `theta`.  We should mention that in the commit message, since that's the actual user-visible effect of this change.
</blockquote></details>

Possible commit message, something like:
Move code from rotation_matrix.h to rotation_matrix.cc. Sanity-check theta arg to MakeRotationMatrixZ(), etc.
___
*[`math/rotation_matrix.cc` line 58 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRF7OTw3Fm-Z86cs9bV:-NRFpEfIA9j3vMdW4D-y:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/96ed675cff895c90be489e19220eddfd71e47891/math/rotation_matrix.cc#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Nowhere else in this class aborts the problem if the user provides wrong input.  We should maintain that convention in the new code here as well.

Likewise the other two MakeRotation factory functions.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19040)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19040#-NRF7m-00JmaHIQpk8Lk):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Possible commit message, something like:
Move code from rotation_matrix.h to rotation_matrix.cc. Sanity-check theta arg to MakeRotationMatrixZ(), etc.
</blockquote></details>

OK, I'll use that as inspiration -- but with a subject line less than the 63-character upper limit.

**Comment by EricCousineau-TRI** [comment]
Setting to `release notes: none` as this may not be relevant to users.

**Comment by EricCousineau-TRI** [comment]
(but still a great change ;) )

**Comment by jwnimmer-tri** [comment]
The release note should be the second sentence: "Sanity-check the theta arg to MakeRotationMatrixZ(), etc."

**Pull request merged**
