### PR TITLE
[workspace] Upgrade tinygltf to latest release v2.8.23

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21569)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21569)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21569#-O-I8tz81Wzd1JOxF7Ke:-O-I8tz81Wzd1JOxF7Kf:b5dfr7k) (no related file):*
We'll wait for #21520 to merge. That actively benefits from the change in tinygltf version. So, we'll merge that, rebase this so we have proof of compatibility.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not review) 

+@jwnimmer-tri for both reviews, please.

+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21569#-:-O0G_PMTEUmOTUVc3pY0:bkld8fd)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21569#-O-I8tz81Wzd1JOxF7Ke:-O0G_OdpBUYVX0cgYeZU:bb6un1j) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

We'll wait for #21520 to merge. That actively benefits from the change in tinygltf version. So, we'll merge that, rebase this so we have proof of compatibility.
</blockquote></details>

Done

___

**Comment by SeanCurtis-TRI** [comment]
+(release notes: fix)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both

> Reviewed 2 of 2 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21569#-:-O0G_o3_-MbG3qGIU5pr:bb6yyy8)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
