### PR TITLE
Begin to remove `EXPORT` decorations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Turn off ELF hidden visibility by default
- Stop using drakeCommon_export.h

Filing this now just to get come CI input.  Still a WIP.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3668)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jwnimmer-tri** [comment]
This seems to be passing in CI.  Let's some some review going.

+@sherm1 for feature review, please.
+@david-german-tri for platform review, please.
+@sammy-tri for conceptual review (the premise; not the code details).

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTFklFmOZ4U_SpViONU:bd052rd)*

**Comment by david-german-tri** [comment]
I cannot argue with the goodness of this.  :lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTG1tYl6cJX4JWHvcfa:bldfhe9)*

**Comment by sammy-tri** [comment]
Does this mean the approach of using a single project-wide header with appropriate export macros (as discussed in #3666 is off the table?

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTG7d6_j2FXWg2ur8CQ:bxg2wnv)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri I considered it, but it didn't seem worth the machinations required, e.g., to get extern template class instantiations working in that framework.  If anyone has a reason to want a one-single-header solution I'm all ers.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTG8yq5MuCSUmE2G4M_:bf2o5mu)*

**Comment by sammy-tri** [comment]
I guess my hesitation comes from the fact that these are a lot easier to delete than that they ever will be to put back.  Some may consider this a feature, but I'd prefer less radical action which still satisfies your primary goal if it's doable.  I haven't looked into the single header solution in detail, so it may not be.  I can see some complications which I didn't originally envision (for the one-single-header option).

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTG9muVOTGFyWr2vM0S:b-3fqn7q)*

**Comment by jwnimmer-tri** [comment]
I can probably find a way to limp along with a one-true-FOO form of them while we discuss.  But I don't see any endgame where we want them in a form similar to that, so I'm not sure why we should open ourselves up to strange linker errors without an endgame in mind.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTGCxGPTYec0gHdomac:b7otal4)*

**Comment by jwnimmer-tri** [comment]
FTR I'm preparing a second PR with this one-true-FOO option, to see what it looks like.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTGHE1gqQdih1ofHK4z:b-yknhsc)*

**Comment by sammy-tri** [comment]
I guess the die is cast.  If we ever want Windows support or hidden ELF symbols back, it's gonna be unpleasant, but :lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTGHHZwPJSs-_mV28bi:beozy2r)*

**Comment by sherm1** [comment]
I agree with @sammy-tri that this is a little scary since it is a one-way commitment, like jumping off a cliff. But ... it looks *SO* much nicer this way! Further commitment would be to get rid of any `#ifdef _MSC_VER`s in the code at the same time. Anyway, this is what abandoning support for Windows should look like. :lgtm: 

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_assert.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-KTGGK0z7FpNVy7XnjHw:-KTGGK1-D0YjWW7kQIOE:b-m66ba2) ([raw file](https://github.com/robotlocomotion/drake/blob/4e6c7703abe9b4796d6573d0d642fb493121d5de/drake/common/drake_assert.h#L72)):*
> ```objc
> // Abort the program with an error message.
> #if _MSC_VER
> __declspec(noreturn)
> ```

BTW, do you want to get rid of all things MSCV along with the exports?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTGH9ggIoS7xHsjpV9-:b-zeqhjl)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/drake_assert.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-KTGGK0z7FpNVy7XnjHw:-KTGIkDGSJ8M3osPwPIF:b-scklac) ([raw file](https://github.com/robotlocomotion/drake/blob/4e6c7703abe9b4796d6573d0d642fb493121d5de/drake/common/drake_assert.h#L72)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, do you want to get rid of all things MSCV along with the exports?
</details>
Someone can own that in a separate PR.  It's not actively in my way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668)*

**Comment by jwnimmer-tri** [comment]
See #3671 for another way to do this, for discussion purposes.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTGJG25WZRhxxr1xfLG:b-t1kkjz)*

**Comment by sammy-tri** [comment]
Given my statements here it's probably no surprise that I like #3671 if it's workable.  I do note that it (since it's the one single header) lacks the "am I building the library" conditional.  I don't know if it matters.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3668#-:-KTGJnpiQq8HtpK7JKus:b-3h9l34)*

**Comment by jwnimmer-tri** [comment]
I going to try #3671 and see if we can get away with just that; it should be less controversial, and unblocks my other immediate work.  In any case, it will create a unified spelling so that we can perl pie it all away later trivially if we want to.  I'm going to leave this PR open until 3671 merges though, in case we find a hiccup there.

**Comment by jwnimmer-tri** [comment]
#3671 won.  Closing this alternative.

**Pull request closed without merging**
