### PR TITLE
Create DrivingCommandMux, Disable Multiplexer output vector downcasting under AutoDiff

### LINKED ISSUE #8921: Subsystems that poll named vector inputs fail when T = AutoDiffXd.
There seems to be a failure happening when a Diagram is set up in such a way that one subsystem polls an input which is a subclass of BasicVector, and when `T = AutoDiffXd`.  Under such circumstances, a `std::logic_error` like the following is thrown:
```
System::EvalVectorInput(): expected value of type drake::automotive::DrivingCommand<drake::AutoDiffXd> for input port[0] but the actual type was drake::systems::BasicVector<drake::AutoDiffXd>. (Subsystem ::AutomotiveSimulator::idm_car_simple_car)
```
but no such error is thrown when `T = double`.

This error can be reproduced via `bazel run //automotive:automotive_simulator_test` after making [these changes](https://github.com/RobotLocomotion/drake/compare/master...jadecastro:simplecar-autodiff-diagram-issue) to `automotive_simulator_test.cc`.  In this particular example, SimpleCar polls a `DrivingCommand<T>`, whose input is connected to the output of a Multiplexer, which is also of type `DrivingCommand<T>`. 

An error is thrown when stepping the `AutoDiffXd` Simulator at line 487, but not when stepping the `double` Simulator at line 480.  The current workaround is to configure SimpleCar with only BasicVector inputs (and reference the vector elements using `DrivingCommandIndices`), but authors shouldn't need to rely on that.  Also, note that this seems to be particular to Diagrams, as we are already using `SimpleCar<AutoDiffXd>` [elsewhere](https://github.com/RobotLocomotion/drake/blob/master/automotive/test/trajectory_optimization_test.cc).

### PR DESCRIPTION
**Pull request by jadecastro**
Closes #8921.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@jwnimmer-tri for feature review (since it looks like you're not on Monday's platform duties).

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957#-:-LEW5lZ1D11BxfgHHVi_:blti9kj)*

**Comment by jwnimmer-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[automotive/driving_command_mux.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEWGUrw3ZiqKdaNLvlq:-LEWGUrw3ZiqKdaNLvlr:b-6tq6mt) ([raw file](https://github.com/robotlocomotion/drake/blob/801dac390375c832de757749d8e0d604d32b6ab9/automotive/driving_command_mux.h#L12)):*
> ```objc
> /// A special-purpose multiplexer that packs two scalar inputs into a
> /// vector-valued output of type DrivingCommand<T>, where the inputs feed
> /// directly through to the output.
> ```

FYI It's _probably_ obvious that the units of the two scalar inputs are exactly the same as the matching DrivingCommand elements, but possibly its worth calling that out here specifically.

---

*[automotive/driving_command_mux.h, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEWFhDODADxRzxfE_3d:-LEWFhDODADxRzxfE_3e:bkdinar) ([raw file](https://github.com/robotlocomotion/drake/blob/801dac390375c832de757749d8e0d604d32b6ab9/automotive/driving_command_mux.h#L29)):*
> ```objc
> /// Currently, no other values for `T` are supported.
> ///
> /// @ingroup primitive_systems
> ```

Probably this class is not general enough to be cited as a primitive?

---

*[automotive/test/automotive_simulator_test.cc, line 476 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEWGv1D4uA5wfRfTCgP:-LEWGv1EAqYiWchTHJoj:b215zo9) ([raw file](https://github.com/robotlocomotion/drake/blob/801dac390375c832de757749d8e0d604d32b6ab9/automotive/test/automotive_simulator_test.cc#L476)):*
> ```cpp
> 
>   const auto& diagram =
>       dynamic_cast<const systems::Diagram<double>&>(simulator->GetDiagram());
> ```

Unclear why we need to dynamic_cast here -- it seems like `System<double>` would have been good enough?

---

*[systems/primitives/multiplexer.cc, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEWFZpeER4iMpaitVeZ:-LEWFZpeER4iMpaitVe_:b-ns0lmu) ([raw file](https://github.com/robotlocomotion/drake/blob/801dac390375c832de757749d8e0d604d32b6ab9/systems/primitives/multiplexer.cc#L62)):*
> ```cpp
> template <typename U>
> Multiplexer<T>::Multiplexer(const Multiplexer<U>& other)
>     : Multiplexer<T>(other.input_sizes_, *MakeBasicVectorOrThrow<T, U>(other)) {
> ```

When a System does not support AutoDiff, the ToAutoDiffXdMaybe method should return nullptr, not throw.  By deferring a runtime check here until the conversion attempt is made, I think that we can no longer meet that contract.

I believe the best solution here is to change the Multiplexer(BasicVector) constructor to pass an empty SystemTypeTag, like ConstantVectorSource does, as well as updating our API comments in a similar way.

How does that sound?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[automotive/driving_command_mux.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEWLQYN4u9ORtjfoIgl:-LEWLQYOBzXPvrpna4A_:bf6mnrz) ([raw file](https://github.com/robotlocomotion/drake/blob/801dac390375c832de757749d8e0d604d32b6ab9/automotive/driving_command_mux.cc#L25)):*
> ```cpp
> template <typename T>
> template <typename U>
> DrivingCommandMux<T>::DrivingCommandMux(const DrivingCommandMux<U>& other)
> ```

nit GCC wants us to omit the name `other` here (unused variable)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957)*

**Comment by jadecastro** [comment]
Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/driving_command_mux.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEWGUrw3ZiqKdaNLvlq:-LEeiGeb3r9wvBGkoK-H:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/801dac390375c832de757749d8e0d604d32b6ab9/automotive/driving_command_mux.h#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It's _probably_ obvious that the units of the two scalar inputs are exactly the same as the matching DrivingCommand elements, but possibly its worth calling that out here specifically.
</blockquote></details>

Fixed.

---

*[automotive/driving_command_mux.h, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEWFhDODADxRzxfE_3d:-LEeiIW4AmMEkowYiW0r:b-1rxz1e) ([raw file](https://github.com/robotlocomotion/drake/blob/801dac390375c832de757749d8e0d604d32b6ab9/automotive/driving_command_mux.h#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Probably this class is not general enough to be cited as a primitive?
</blockquote></details>

Done. Now in `automotive_systems`

---

*[automotive/test/automotive_simulator_test.cc, line 476 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEWGv1D4uA5wfRfTCgP:-LEei987-a3HfV7IfEM0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/801dac390375c832de757749d8e0d604d32b6ab9/automotive/test/automotive_simulator_test.cc#L476)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why we need to dynamic_cast here -- it seems like `System<double>` would have been good enough?
</blockquote></details>

Done.

---

*[systems/primitives/multiplexer.cc, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEWFZpeER4iMpaitVeZ:-LEeiB2F5Ye-LLRgDJgz:b-p5bzhc) ([raw file](https://github.com/robotlocomotion/drake/blob/801dac390375c832de757749d8e0d604d32b6ab9/systems/primitives/multiplexer.cc#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When a System does not support AutoDiff, the ToAutoDiffXdMaybe method should return nullptr, not throw.  By deferring a runtime check here until the conversion attempt is made, I think that we can no longer meet that contract.

I believe the best solution here is to change the Multiplexer(BasicVector) constructor to pass an empty SystemTypeTag, like ConstantVectorSource does, as well as updating our API comments in a similar way.

How does that sound?
</blockquote></details>

That makes much better sense.  Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957)*

**Comment by jwnimmer-tri** [comment]
Check CI for some linter complaints.

:lgtm: feature review.

---

Reviewed 6 of 6 files at r2.
Review status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri]

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEirfGL1DM4uvUsXss-:-LEirfGL1DM4uvUsXss0:b-tdkk6b) (no related file):*
Needs platform review assigned.

---

*[systems/primitives/multiplexer.h, line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEirPim2Hz07cLTs-wR:-LEirPim2Hz07cLTs-wS:b-18u3dy) ([raw file](https://github.com/robotlocomotion/drake/blob/dacdab00a6928b73a747f678be74f40f7d6eebc0/systems/primitives/multiplexer.h#L44)):*
> ```objc
>   /// `model_vector`.  In addition, the output type derives from that of
>   /// `model_vector`.
>   explicit Multiplexer(const systems::BasicVector<T>& model_vector);
> ```

The fact that this overload does not support system scalar conversion should be clear from its API docs.

FYI ConstantVectorSource has some language to this effect, if you want to borrow it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957#-:-LEiqrGTDMy4iugecNo-:b-ylu5x6)*

**Comment by jadecastro** [comment]
Review status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri]

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEirfGL1DM4uvUsXss-:-LEj91r29nvOZS2F4G4r:b-lnraik) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs platform review assigned.
</blockquote></details>

+@ericcousineau-tri platform review, please.

---

*[systems/primitives/multiplexer.h, line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEirPim2Hz07cLTs-wR:-LEj8iS67hfVgSooQ-P-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dacdab00a6928b73a747f678be74f40f7d6eebc0/systems/primitives/multiplexer.h#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The fact that this overload does not support system scalar conversion should be clear from its API docs.

FYI ConstantVectorSource has some language to this effect, if you want to borrow it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM from [jwnimmer-tri]

---

*[automotive/BUILD.bazel, line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEj9rs56INEYKY1elVs:-LEj9rs56INEYKY1elVt:bsdgolh) ([raw file](https://github.com/robotlocomotion/drake/blob/bb3c1516d86faa86db59751c9a03b6af00cef8ae/automotive/BUILD.bazel#L29)):*
> ```Python
> 
> drake_cc_package_library(
>     name = "automotive",
> ```

FYI I think there were library_lint complaints last push also (in the -everything builds), that would still appear here.  The `drake_cc_package_library` in `automotive` is missing the new mux.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957)*

**Comment by jadecastro** [comment]
Review status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM from [jwnimmer-tri]

---

*[automotive/BUILD.bazel, line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEj9rs56INEYKY1elVs:-LEjAq3xA2izSOqs1cZh:b-yv63pe) ([raw file](https://github.com/robotlocomotion/drake/blob/bb3c1516d86faa86db59751c9a03b6af00cef8ae/automotive/BUILD.bazel#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think there were library_lint complaints last push also (in the -everything builds), that would still appear here.  The `drake_cc_package_library` in `automotive` is missing the new mux.
</blockquote></details>

D'oh. Thanks. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: platform review, with some minor BTWs.

---

Reviewed 2 of 8 files at r1, 4 of 6 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, ericcousineau-tri]

---

*[automotive/test/driving_command_mux_test.cc, line 35 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEjSitJ7Xnqq_IC1YnI:-LEjSitL4SRYn0Mkcx8B:b-q62w1q) ([raw file](https://github.com/robotlocomotion/drake/blob/08d5e1887cd48524270ad5773e5a45aa1dc083c0/automotive/test/driving_command_mux_test.cc#L35)):*
> ```cpp
>   ASSERT_EQ(1, mux_->steering_input().size());
>   ASSERT_EQ(1, mux_->acceleration_input().size());
>   ASSERT_EQ(2, context_->get_num_input_ports());
> ```

FYI This check seems slightly redundant, in that the behavior of `context_` should already be locked down by other tests?

---

*[automotive/test/driving_command_mux_test.cc, line 38 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEjSrJxD1DritxAt5zn:-LEjSrJxD1DritxAt5zo:btemkpg) ([raw file](https://github.com/robotlocomotion/drake/blob/08d5e1887cd48524270ad5773e5a45aa1dc083c0/automotive/test/driving_command_mux_test.cc#L38)):*
> ```cpp
>   ASSERT_EQ(1, mux_->get_num_output_ports());
>   ASSERT_EQ(2, mux_->get_output_port(0).size());
>   ASSERT_EQ(1, output_->get_num_ports());
> ```

FYI These two checks seems slightly redundant, in that the behavior of `output_` should already be locked down by other tests?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957#-:-LEjTLPZ5KHgLPI00Rbs:bdcflqx)*

**Comment by jadecastro** [comment]
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, ericcousineau-tri]

---

*[automotive/test/driving_command_mux_test.cc, line 35 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEjSitJ7Xnqq_IC1YnI:-LEjVAL6DTutuWfv7YAE:bt0ddmw) ([raw file](https://github.com/robotlocomotion/drake/blob/08d5e1887cd48524270ad5773e5a45aa1dc083c0/automotive/test/driving_command_mux_test.cc#L35)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI This check seems slightly redundant, in that the behavior of `context_` should already be locked down by other tests?
</blockquote></details>

Agree- removed.

---

*[automotive/test/driving_command_mux_test.cc, line 38 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8957#-LEjSrJxD1DritxAt5zn:-LEjVC1e1kynudpZJumJ:bt0ddmw) ([raw file](https://github.com/robotlocomotion/drake/blob/08d5e1887cd48524270ad5773e5a45aa1dc083c0/automotive/test/driving_command_mux_test.cc#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI These two checks seems slightly redundant, in that the behavior of `output_` should already be locked down by other tests?
</blockquote></details>

Agree- removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, ericcousineau-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8957)*

**Pull request merged**
