### PR TITLE
Update vector gen to implement the required DoClone override

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4941)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4941#-:-KbWPTKxY7vsKg-Kq9Nq:b-7fek4o)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/lcm_vector_gen.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4941#-KbWpa2chZAi1DO-okcz:-KbWpa2chZAi1DO-okd-:bo5v96s) ([raw file](https://github.com/robotlocomotion/drake/blob/f349ec1a8f6546262906df2aab2a55cdfc4991fe/drake/tools/lcm_vector_gen.py#L86)):*
> ```Python
> def generate_default_ctor(hh, context, _):
>     put(hh, DEFAULT_CTOR % context, 2)
> ```

FYI Meta:  pep8 hates this file.  I don't think your code makes that worse, but it's hard to tell.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4941#-:-KbWpwJQc-2V5otNo2qb:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/lcm_vector_gen.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4941#-KbWpa2chZAi1DO-okcz:-KbWsewH3LBNJJXux67-:b-nzn5mq) ([raw file](https://github.com/robotlocomotion/drake/blob/f349ec1a8f6546262906df2aab2a55cdfc4991fe/drake/tools/lcm_vector_gen.py#L86)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI Meta:  pep8 hates this file.  I don't think your code makes that worse, but it's hard to tell.
</blockquote></details>

BTW really?  I just finished pep8 sanitizing it in #3912, I thought.  Maybe I did it wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4941)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/tools/lcm_vector_gen.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4941#-KbWpa2chZAi1DO-okcz:-KbWsqQ4tLrnwJ6Undx1:banzuv7) ([raw file](https://github.com/robotlocomotion/drake/blob/f349ec1a8f6546262906df2aab2a55cdfc4991fe/drake/tools/lcm_vector_gen.py#L86)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW really?  I just finished pep8 sanitizing it in #3912, I thought.  Maybe I did it wrong.
</blockquote></details>

Sorry, #4912 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4941)*

**Pull request merged**
