### PR TITLE
py math: Bind analog for `np.linalg.solve` for AutoDiffXd, Expression

### LINKED ISSUE #14264: py math: Should support analog to `np.linalg.solve` for AutoDiffXd / Expression
Encountered on StackOverflow:
https://stackoverflow.com/questions/64593813/is-np-linalg-solve-not-working-for-autodiff

FYI @hongkai-dai

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #14264

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14266)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai for feature review, please!

I naively mimicked what I had done in #11173. Don't have a ton of time to polish it up, but this should work?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14266#-:-MKqPQ19BGFkExWHGeYq:bakr3ep)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14266)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/math_pybind.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14266#-MKs5ViT-bKHt1mrqM-0:-MKs5ViT-bKHt1mrqM-1:b76drcu) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9d30fc0b207006ac7df9102b7aa92a66c7b9c0/bindings/pydrake/math_pybind.h#L19)):*
> ```objc
>   DRAKE_THROW_UNLESS(A.rows() == A.cols());
>   DRAKE_THROW_UNLESS(b.rows() == A.rows());
>   return Eigen::PartialPivLU<MatrixX<T>>(A).solve(b);
> ```

Curious why you choose PartialPivLU, according to Eigen, this is not very accurate https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14266)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/math_pybind.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14266#-MKs5ViT-bKHt1mrqM-0:-MKt4g9X2iN8AKeVbL-D:b-az3c71) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9d30fc0b207006ac7df9102b7aa92a66c7b9c0/bindings/pydrake/math_pybind.h#L19)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why you choose PartialPivLU, according to Eigen, this is not very accurate https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html
</blockquote></details>

Not choosing for optimality, but closest to what NumPy might use.

Did you have a chance to read the comment linked to in the code?
https://github.com/RobotLocomotion/drake/issues/14264#issuecomment-719036358

**Comment by SeanCurtis-TRI** [comment]
Six months of no activity. Worth keeping this open?

**Comment by jwnimmer-tri** [comment]
Thanks for your interest in contributing to Drake! Since this PR has not received any updates over the past 6+ months, we are closing it automatically. To resume the PR again, you may reopen it with updates (be sure to reopen before you push any changes), or open a new one.

**Pull request closed without merging**
