### PR TITLE
[parsing] Start to add DiagnosticPolicy for detail_sdf_parser

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16784.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16799)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri you are welcome to take a sneak peek here if you like.  I think the basic form is what I want.  Before asking for a full review, I still need to look at code coverage and make sure the tests are sufficient to cover the new error-vs-warning branches.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.a

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16799#-:-MyJAZcZ8NW7eVnzM0jA:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
