### PR TITLE
Cpplint readability inheritance

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix all cpplint readability/inheritance issues, and enable the warning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2248) &emsp; Multiple assignees:&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@sammy-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sammy-tri">sammy-tri</a>

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@sammy-tri  (still reviewing)

---

Reviewed 9 of 14 files at r1.
Review status: 9 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 239 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2248#-KGrCXdTtL41w6NJaA93:-KGrCXdUR9cqahImeWkL:-116050260) ([raw file](https://github.com/robotlocomotion/drake/blob/bee470265c7a64f53621118ab6b0b5ce2fc2ee2d/drake/systems/plants/RigidBodySystem.cpp#L239)):*
We're mixing virtual and override in the same class...   do we care?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2248#-:-KGrCrWiKwjhn6RVvZdI:1057409648)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2248#-:-KGrDARlPxE9-WJIbTmR:1417088721)*

**Comment by jwnimmer-tri** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 239 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2248#-KGrCXdTtL41w6NJaA93:-KGrFJCeH7Ya6ULK7Xxp:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/bee470265c7a64f53621118ab6b0b5ce2fc2ee2d/drake/systems/plants/RigidBodySystem.cpp#L239)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2248)*

**Comment by liangfok** [comment]
Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2248)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2248#-:-KGrJXcXA7eCYlulY701:-1868698381)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri Ready for platform review and merge.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2248#-:-KGs80chVJ_uAPs7CeRH:1417088721)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 239 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2248#-KGrCXdTtL41w6NJaA93:-KGs89Z-IouvZClkqf2J:676834233) ([raw file](https://github.com/robotlocomotion/drake/blob/bee470265c7a64f53621118ab6b0b5ce2fc2ee2d/drake/systems/plants/RigidBodySystem.cpp#L239)):*
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2248)*

**Pull request merged**
