### PR TITLE
Fix some issues with NLopt which affected solving IK problems

### PR DESCRIPTION
**Pull request by sammy-tri**
This PR represents my attempt to make NLopt handle constraints with mixed equalities/inequalities, as well as inequalities with different upper and lower bounds.  It is not sufficient to actually enable NLopt for IK problems, as IK problems frequently (partially) duplicate some constraints, and NLopt has issues with this case, thus I have not enabled IK based on the presence of NLopt.

Eventual IPOPT integration should handle the IK cases in the absence of SNOPT.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2417) &emsp; Multiple assignees:&emsp;@Lucy-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/Lucy-tri">Lucy-tri</a>,&emsp;@ggould-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/ggould-tri">ggould-tri</a>

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@lucy-tri for feature review, +@ggould-tri for platform review

<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> #### Fix some issues with NLopt which affected solving IK problems
> 
> This PR represents my attempt to make NLopt handle constraints with mixed equalities/inequalities, as well as inequalities with different upper and lower bounds.  It is not sufficient to actually enable NLopt for IK problems, as IK problems frequently (partially) duplicate some constraints, and NLopt has issues with this case, thus I have not enabled IK based on the presence of NLopt.
> 
> 
> 
> Eventual IPOPT integration should handle the IK cases in the absence of SNOPT.
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-:-KIEdUkr1S3NxMZwtoPZ:-682341675)*

**Comment by Lucy-tri** [comment]
I have questions in my comments below, but I'm leaving on vacation so i'm marking this :lgtm:  so I don't hold things up. 

<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> +@lucy-tri for feature review, +@ggould-tri for platform review
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/solvers/NloptSolver.cpp, line 97 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEn301501_vvlj-Min:-KIEn301501_vvlj-Mio:558631541) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L97)):*
> ```cpp
>   const Constraint* constraint;
>   const VariableList* variable_list;
>   bool force_bounds;
> ```

Need better name or comment for what "force" means. Maybe you mean set to infinity? +

---

*[drake/solvers/NloptSolver.cpp, line 100 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEmaPkbbmk1yMC8m62:-KIEmaPkbbmk1yMC8m63:-2000165179) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L100)):*
> ```cpp
>   bool force_upper;
>   // TODO(sam.creasey) It might be desirable to have a cache for the
>   // result of evaluatinf the constraints if NLopt were being used in
> ```

/s/evaluatinf/evaluating/

---

*[drake/solvers/NloptSolver.cpp, line 128 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEneaHzB8D8ylfVgG4:-KIEneaHzB8D8ylfVgG5:-2047116168) ([raw file](https://github.com/robotlocomotion/drake/blob/60e11e1417ec64f1b3ec54d7e1ea1c02b8c829ef/drake/solvers/NloptSolver.cpp#L128)):*
> ```cpp
> // and
> // http://ab-initio.mit.edu/wiki/index.php/NLopt_Reference#Nonlinear_constraints
> double EvaluateScalarConstraint(const std::vector<double>& x,
> ```

Why is this removed? 

---

*[drake/solvers/NloptSolver.cpp, line 177 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIF-7ysuZTKJKYjibHq:-KIF-7ysuZTKJKYjibHr:-882804054) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L177)):*
> ```cpp
>     if (!wrapped->active_constraints.count(i)) { continue; }
>     if (wrapped->force_bounds && wrapped->force_upper &&
>         (upper_bound(i) != std::numeric_limits<double>::infinity())) {
> ```

don't you want to check that upper is NOT -inf?   +(type: bug) 

---

*[drake/solvers/NloptSolver.cpp, line 218 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEp16A7idEAROHvjjV:-KIEp16A7idEAROHvjjW:-1079888112) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L218)):*
> ```cpp
> 
> template <typename C>
> void WrapConstraint(const OptimizationProblem::Binding<C>& binding,
> ```

Is there a way to notate the input params versus output params?

---

*[drake/solvers/NloptSolver.cpp, line 221 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEvQhUyVO6AbDsLEwy:-KIEutePejMZ0gKJkasd:1849368749) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L221)):*
> ```cpp
>                     double constraint_tol,
>                     nlopt::opt* opt,
>                     std::list<WrappedConstraint>* wrapped_list) {
> ```

Seems like wrapped_list could be a param of this function.  Callers never read it, or write it, they just create it. 

---

*[drake/solvers/NloptSolver.cpp, line 222 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIErVxR2etlay5Q6PQV:-KIErVxR2etlay5Q6PQW:-430539018) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L222)):*
> ```cpp
>                     nlopt::opt* opt,
>                     std::list<WrappedConstraint>* wrapped_list) {
>   WrappedConstraint wrapped_eq(binding.constraint().get(),
> ```

These name don't tell me what the var does.  Consider names like upper_lower_eq (instead of wrapped_eq) and  upper_lower_neq 

---

*[drake/solvers/NloptSolver.cpp, line 261 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEtnNFdFZpLPMvbn9o:-KIEtnNGsbsAlNAJ8Sjv:1108889513) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L261)):*
> ```cpp
>       wrapped_list->back().force_bounds = true;
>       wrapped_list->back().force_upper = true;
>       opt->add_inequality_mconstraint(
> ```

Its unclear to me why you are calling add_inequality_mconstraint twice and what force_x does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-:-KIF-uqoOlyBEYavuyxO:-1227773947)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[drake/solvers/NloptSolver.cpp, line 130 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KITQfntzQT_ghly6MZP:-KITQfntzQT_ghly6MZQ:1062331739) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L130)):*
> ```cpp
>   } else {
>     if (lb == -std::numeric_limits<double>::infinity()) {
>       std::cerr << "Unable to handle constraint with no bounds." << std::endl;
> ```

I'm not sure we want direct stderr writes in runtime code, and I'm not clear why the throw below is not adequate.  Please comment this to explain the stderr duplication, so that when we have a proper logging and assert mechanism we can revisit why this case needs special treatment.

---

*[drake/solvers/NloptSolver.cpp, line 177 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIF-7ysuZTKJKYjibHq:-KITRexE8lXwTNK9-4V0:417989753) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L177)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> don't you want to check that upper is NOT -inf?   +(type: bug) 
</details>
LGTM -- I think the test here is that the upper bound is not equal to its default (no-upper-bound) value, ie that there is a nontrivial upper bound set.

---

*[drake/solvers/NloptSolver.cpp, line 182 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KITSBbgDCHz4tVHX3Gk:-KITSBbgDCHz4tVHX3Gl:-874258188) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L182)):*
> ```cpp
>           upper_bound(i));
>     } else if (wrapped->force_bounds && !wrapped->force_upper &&
>                (lower_bound(i) != std::numeric_limits<double>::infinity())) {
> ```

This one, by contrast, looks sketchy.  A lower bound of positive infinity is not a reasonable default and does not reasonably mean no constraint.

If infinities are being used as a sentinel value rather than as an actual trivial/prohibitory bound, consider std::isfinite() instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2417)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[drake/solvers/NloptSolver.cpp, line 97 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEn301501_vvlj-Min:-KITb4hNmNMIahdJkp2s:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L97)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Need better name or comment for what "force" means. Maybe you mean set to infinity? +
</details>
Done.

---

*[drake/solvers/NloptSolver.cpp, line 100 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEmaPkbbmk1yMC8m62:-KITb81JV8Le8xxDLJJ0:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L100)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> /s/evaluatinf/evaluating/
</details>
Done.

---

*[drake/solvers/NloptSolver.cpp, line 128 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEneaHzB8D8ylfVgG4:-KITbU_xNZ97KkIo4PiC:1440175097) ([raw file](https://github.com/robotlocomotion/drake/blob/60e11e1417ec64f1b3ec54d7e1ea1c02b8c829ef/drake/solvers/NloptSolver.cpp#L128)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Why is this removed? 
</details>
It was only called for linear equality constraints, which now work through the vector version.

---

*[drake/solvers/NloptSolver.cpp, line 130 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KITQfntzQT_ghly6MZP:-KITbAiHY0iWH-pPEw64:-1218300763) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L130)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> I'm not sure we want direct stderr writes in runtime code, and I'm not clear why the throw below is not adequate.  Please comment this to explain the stderr duplication, so that when we have a proper logging and assert mechanism we can revisit why this case needs special treatment.
</details>
Removed, that was leftover debugging code.  Agreed a better logging mechanism would be a win here.

---

*[drake/solvers/NloptSolver.cpp, line 182 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KITSBbgDCHz4tVHX3Gk:-KITbpGQxaNm2q2xryww:-1209904044) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L182)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> This one, by contrast, looks sketchy.  A lower bound of positive infinity is not a reasonable default and does not reasonably mean no constraint.
> 
> If infinities are being used as a sentinel value rather than as an actual trivial/prohibitory bound, consider std::isfinite() instead.
</details>
This one was a bug.  ApplyConstraintBounds would have thrown an exception had we actually made it through this conditional with the lower bound equal to negative infinity (but I think the check should still be there, so I fixed the sign error)

---

*[drake/solvers/NloptSolver.cpp, line 218 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEp16A7idEAROHvjjV:-KITcT5yoCEKsNO4hfd6:98877614) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L218)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Is there a way to notate the input params versus output params?
</details>
Input params are const references (or pod), the non-const pointers are mutated by this function.  

---

*[drake/solvers/NloptSolver.cpp, line 221 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEvQhUyVO6AbDsLEwy:-KITccEsEPfjDpEvK7yi:648665401) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L221)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Seems like wrapped_list could be a param of this function.  Callers never read it, or write it, they just create it. 
</details>
The list is mutated over several calls to WrapConstraint...  since it's a free function, local storage wouldn't be particularly useful since the elements of wrapped_list need to remain valid until the end of Solve().  I'm not sure where else to scope the list except in the scope of Solve()?

---

*[drake/solvers/NloptSolver.cpp, line 222 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIErVxR2etlay5Q6PQV:-KITdRurCWbx2vpCFrNx:614455803) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L222)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> These name don't tell me what the var does.  Consider names like upper_lower_eq (instead of wrapped_eq) and  upper_lower_neq 
</details>
Added some comments.  I wrapped_equality_constraint vs wrapped_inequality_constraint seemed really verbose to me.

---

*[drake/solvers/NloptSolver.cpp, line 261 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-KIEtnNFdFZpLPMvbn9o:-KITdq2y7KyVo7CadVbT:-1798858889) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2dc9307fb15e55829f5631a673cda737ba7f20/drake/solvers/NloptSolver.cpp#L261)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Its unclear to me why you are calling add_inequality_mconstraint twice and what force_x does.
</details>
Added some additional comments to WrappedConstraint

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2417)*

**Comment by ggould-tri** [comment]
:lgtm:

<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> I have questions in my comments below, but I'm leaving on vacation so i'm marking this :lgtm:  so I don't hold things up. 
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2417#-:-KIUNo-_AuX4L0Wirxe1:1417088721)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
