### PR TITLE
Make symbolic::Variable compatible with Eigen::Matrix

### PR DESCRIPTION
**Pull request by soonho-tri**
Related issue : #4624 , #4619.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4627)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.
+@jwnimmer-tri , platform-review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-:-K_2FsF3ZwSy3sAHlnO4:bfpnbc5)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-:-K_2LipSUaVCOLDjrj45:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Thanks for getting this done so quickly!

---

Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-:-K_2LpgtDGYV7Oo9cFXr:b-6qclli)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2HwAYRbRCrVsP9Qy2:-K_2HwAZ1rHeg8aosrHe:bx9yrs8) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
> ```cpp
> }
> 
> Variable::Variable() : Variable{""} {}
> ```

BTW By using `""` here, we are relying on the optimizing compiler to see that something like `__builtin_strlen` on the string literal is zero, and thus branch into the empty-rep (libstdc++) and/or short-string`basic_string` (libc++) optimization .  I suspect that in practice this works very well, but by invoking`std::string()` directly here (which probably hard-codes the size to zero, and thus probably dead-code's away the size guards more reliably) instead of passing in an empty char string, we are more likely to be fast in more cases.

In short: consider `: Variable{std:string()} {}` here instead.

Normally I don't nitpick this, but using a std::string in the default-constructed value of an Eigen Scalar is possibly somewhere worth prematurely optimizing.  It probably gets called a _lot_.

You'd even be within your rights to put this body into the header file (for inlining), if you wanted.  Possibly even with a direct implementation, though that makes me wonder about get_next_id being atomic and "slow" anyway (which makes me wonder if we want to spin our IDs on default-constructed variables, which I'll post as a separate discussion).

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2Lrhm0XFILDGtLDtw:bqvik0y) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
> ```cpp
> }
> 
> Variable::Variable() : Variable{""} {}
> ```

This churns the ID pool when creating default-constructed variables.  Please add a comment (to the header?) clarifying why one anonymous `Variable{}` is different from a fresh anonymous `Variable{}`.

I buy that two `"x"` variables are distinct, because there's multiple bindings for `x` depending on context.  But why should anonymous variables be distinct?  Are they merely unnamed, or are they absent / bottom?

This also relates to performance of Eigen matrices of these variables vs ID allocation, but that should be only a secondary concern.  The primary concern should be to get the semantics correct.

---

*[drake/common/symbolic_variable.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2KPb_bAmWGbdItcPA:-K_2KPb_bAmWGbdItcPB:b-o0zgrl) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L39)):*
> ```cpp
> 
> ostream& operator<<(ostream& os, const Variable& var) {
>   os << var.get_name();
> ```

BTW Should this print something helpful on a default-constructed Variable?

---

*[drake/common/symbolic_variable.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2MiEiBceiheGl4BMJ:-K_2MiEiBceiheGl4BMK:b-meyd6n) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.h#L18)):*
> ```objc
> class Variable {
>  public:
>   /** Default constructor. This is needed to have Eigen::Matrix<Variable>. */
> ```

BTW Is there any code in-tree yet that should guard against (fail-fast on) anonymous variables?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2NpJd39BzC9JiKmId:b-r255pa) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This churns the ID pool when creating default-constructed variables.  Please add a comment (to the header?) clarifying why one anonymous `Variable{}` is different from a fresh anonymous `Variable{}`.

I buy that two `"x"` variables are distinct, because there's multiple bindings for `x` depending on context.  But why should anonymous variables be distinct?  Are they merely unnamed, or are they absent / bottom?

This also relates to performance of Eigen matrices of these variables vs ID allocation, but that should be only a secondary concern.  The primary concern should be to get the semantics correct.
</blockquote></details>

To be super clear.. I would also be content here if anonymous Variables were given an identical ID (e.g., `0`) and documented to be equivalent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2HwAYRbRCrVsP9Qy2:-K_2PVkx_F43oVK_czUX:bmjcp4q) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW By using `""` here, we are relying on the optimizing compiler to see that something like `__builtin_strlen` on the string literal is zero, and thus branch into the empty-rep (libstdc++) and/or short-string`basic_string` (libc++) optimization .  I suspect that in practice this works very well, but by invoking`std::string()` directly here (which probably hard-codes the size to zero, and thus probably dead-code's away the size guards more reliably) instead of passing in an empty char string, we are more likely to be fast in more cases.

In short: consider `: Variable{std:string()} {}` here instead.

Normally I don't nitpick this, but using a std::string in the default-constructed value of an Eigen Scalar is possibly somewhere worth prematurely optimizing.  It probably gets called a _lot_.

You'd even be within your rights to put this body into the header file (for inlining), if you wanted.  Possibly even with a direct implementation, though that makes me wonder about get_next_id being atomic and "slow" anyway (which makes me wonder if we want to spin our IDs on default-constructed variables, which I'll post as a separate discussion).
</blockquote></details>

Very good point! Thanks!!

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2PXtMh06jXR_hxoi5:b-ui0bxc) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To be super clear.. I would also be content here if anonymous Variables were given an identical ID (e.g., `0`) and documented to be equivalent.
</blockquote></details>

I was thinking about it as well. I think it depends on how we use those anonymous variables. @hongkai-dai, do you have a thought on this?

I was thinking about the following use case where we use `Eigen::Matrix<Variable>` as a factory to create bunch of `Variable`s:

```
// 2 x 2 Matrix. All elements are anonymous vars.
Eigen::Matrix<Variable, 2, 2> m;
Variable &x{m(0,0)};
Variable &y{m(1,0)};
Variable &z{m(0,1)};
Variable &w{m(1,1)};
...
/// use x, y, z, w
...
```

In this case, I think `x`, `y`, `z`, and `w` have to have different `ID`s.

---

*[drake/common/symbolic_variable.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2KPb_bAmWGbdItcPA:-K_2RZBKSezp4VBhVf74:bw4cazv) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should this print something helpful on a default-constructed Variable?
</blockquote></details>

I'm not sure. Actually, which one do you prefer?

1) Anonymous variable has a non-zero string name (i.e. `"dummy").
2) Anonymous variable has zero-string name, but when it's printed, we check the special case and print `"dummy"`.

---

*[drake/common/symbolic_variable.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2MiEiBceiheGl4BMJ:-K_2PNGvQAPiAsHgAEEO:b-p9jje9) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.h#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is there any code in-tree yet that should guard against (fail-fast on) anonymous variables?
</blockquote></details>

Probably not, because the default `Variable()` constructor was deleted previously. I'll check things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2U0WH8V5fWmVf4vqy:b-b6yom2) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I was thinking about it as well. I think it depends on how we use those anonymous variables. @hongkai-dai, do you have a thought on this?

I was thinking about the following use case where we use `Eigen::Matrix<Variable>` as a factory to create bunch of `Variable`s:

```
// 2 x 2 Matrix. All elements are anonymous vars.
Eigen::Matrix<Variable, 2, 2> m;
Variable &x{m(0,0)};
Variable &y{m(1,0)};
Variable &z{m(0,1)};
Variable &w{m(1,1)};
...
/// use x, y, z, w
...
```

In this case, I think `x`, `y`, `z`, and `w` have to have different `ID`s.
</blockquote></details>

I agree in that example they should have different IDs.  But do we want to do that?  They would all be unnamed there, and likely difficult to work with?  The proof engine would need nonce names for them anyway.

I guess it seems to me like the default constructor should return a once-and-forever anonymous value with ID zero.  If we want unnamed variables, we can add another constructor to supply them -- either by producing `name="{anonymousNN}` where NN is the identifier, or perhaps more likely, a helper routine to return a fresh Eigen::Matrix where the cells are filled with Variables like `m00` already -- i.e. useful row/col-derived names.

Mostly I want to hear what Hongkai thinks, though.

---

*[drake/common/symbolic_variable.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2KPb_bAmWGbdItcPA:-K_2T9yfppGkhFSlOm16:b-4a3g20) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L39)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'm not sure. Actually, which one do you prefer?

1) Anonymous variable has a non-zero string name (i.e. `"dummy").
2) Anonymous variable has zero-string name, but when it's printed, we check the special case and print `"dummy"`.

</blockquote></details>

I was very happy with `get_name()` being empty (so not option 1), though would defer to you and Hongkai.  But this operator seemed like user convenience for logging & display, so could perhaps be more elaborate -- as long as it could distinguish a user string from a default "helpful no-op" string.

---

*[drake/common/symbolic_variable.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2MiEiBceiheGl4BMJ:-K_2TjCJe4mQxt6FaWtR:b-l1oj0k) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.h#L18)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Probably not, because the default `Variable()` constructor was deleted previously. I'll check things.
</blockquote></details>

Right, anonymous variables didn't used to exist.  Now that they do, are there functions whose contract should have a precondition to reject them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2Ut5i2h7Sx2vp955Z:b-58gja1) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I agree in that example they should have different IDs.  But do we want to do that?  They would all be unnamed there, and likely difficult to work with?  The proof engine would need nonce names for them anyway.

I guess it seems to me like the default constructor should return a once-and-forever anonymous value with ID zero.  If we want unnamed variables, we can add another constructor to supply them -- either by producing `name="{anonymousNN}` where NN is the identifier, or perhaps more likely, a helper routine to return a fresh Eigen::Matrix where the cells are filled with Variables like `m00` already -- i.e. useful row/col-derived names.

Mostly I want to hear what Hongkai thinks, though.
</blockquote></details>

If this anonymous symbolic variable is only used in creating an Eigen matrix, then I think they should have the same ID, like ID 0, and hopefully add the logic in `symbolic::Variable` that a variable with ID 0 is not useful (cannot be used to create a symbolic expression).

If the usage of the anonymous symbolic variable include the following case
```C++
symbolic::Variable x;
symbolic::Variable y;
symbolic::Expression x_plus_y = x + y
```
then the anonymous symbolic variables should have different IDs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2X3BtdRt2ZPPu2ECw:b-pocm41) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If this anonymous symbolic variable is only used in creating an Eigen matrix, then I think they should have the same ID, like ID 0, and hopefully add the logic in `symbolic::Variable` that a variable with ID 0 is not useful (cannot be used to create a symbolic expression).

If the usage of the anonymous symbolic variable include the following case
```C++
symbolic::Variable x;
symbolic::Variable y;
symbolic::Expression x_plus_y = x + y
```
then the anonymous symbolic variables should have different IDs.
</blockquote></details>

@hongkai-dai, but I think you do want to have the last example, right (or not)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2YPa-WEeWAtl4QKgZ:b2x2km5) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@hongkai-dai, but I think you do want to have the last example, right (or not)?
</blockquote></details>

I think the last example would look better, if we do not use the anonymous variable, but variable with names
```C++
symbolic::Variable x("x");
symbolic::Variable y("y");
symbolic::Expression x_plus_y = x + y;
```

When working with symbolic variables, in most cases I find I need to print out the expression for debugging purpose. With anonymous variables, the printed out message is not very helpful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2_N0ugZG3ZgpiISCg:b-ba7jcz) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the last example would look better, if we do not use the anonymous variable, but variable with names
```C++
symbolic::Variable x("x");
symbolic::Variable y("y");
symbolic::Expression x_plus_y = x + y;
```

When working with symbolic variables, in most cases I find I need to print out the expression for debugging purpose. With anonymous variables, the printed out message is not very helpful.

</blockquote></details>

Sounds good to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2_rRktnTVt36nECty:bh07q7p) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Sounds good to me.
</blockquote></details>

FWIW, I also really liked the suggestion that `Expression{Variable{}}` is an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by soonho-tri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_variable.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2Lrhm0XFILDGtLDtv:-K_2fOGM1qMuJe_ehezM:b-dkcbhu) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L22)):*
Is it good now?

> FWIW, I also really liked the suggestion that Expression{Variable{}} is an error.

Added `DRAKE_DEMAND` in `ExpressionVar::ExpressionVar(const Variable& v)`. 

---

*[drake/common/symbolic_variable.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2KPb_bAmWGbdItcPA:-K_2fczR1Lz7LuvFjlPy:bjvhybh) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.cc#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was very happy with `get_name()` being empty (so not option 1), though would defer to you and Hongkai.  But this operator seemed like user convenience for logging & display, so could perhaps be more elaborate -- as long as it could distinguish a user string from a default "helpful no-op" string.
</blockquote></details>

I'll leave it as it is since it seems that we won't really use the anonymous variable in a meaningful way. (it's mainly for Eigen::Matrix).

---

*[drake/common/symbolic_variable.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2MiEiBceiheGl4BMJ:-K_2fqgw6hbN_Yw5hdij:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/79b5ec3a94bc49337d07dcb1e6e5bcdc6b6db3e6/drake/common/symbolic_variable.h#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Right, anonymous variables didn't used to exist.  Now that they do, are there functions whose contract should have a precondition to reject them?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-:-K_2gIfwBugHCWt9XuIE:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_variable.h, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2f1k1jjbOxAXr1Lq3:-K_2f1k2do-Dyoj6d5y7:bcwn9kf) ([raw file](https://github.com/robotlocomotion/drake/blob/093ef0ca4db011427dc075f0ae7dc682d84cd4d1/drake/common/symbolic_variable.h#L20)):*
> ```objc
>   /** Default constructor. This is needed to have Eigen::Matrix<Variable>. The
>       objects created by the default constructor share the same ID, zero. As a
>       result, they all be identified as a single variable by equality operator
> ```

BTW typo s/be/are/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-:-K_2gUHK1nc0nt46Jh4b:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/common/symbolic_variable.h, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4627#-K_2f1k1jjbOxAXr1Lq3:-K_2hbql0MTNBnfU3P5z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/093ef0ca4db011427dc075f0ae7dc682d84cd4d1/drake/common/symbolic_variable.h#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW typo s/be/are/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4627)*

**Pull request merged**
