### PR TITLE
Teach Bazel to conditionally handle packages hoisted up a directory

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

The post-directory-shuffle outcome is tested by Jenkins in PR #7503.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7502)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7502#-:-L-bhnWn4Yc2HPfqK5mM:bv2pqqi)*

**Comment by SeanCurtis-TRI** [comment]
+@seancurtis-tri 

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7502#-:-L-bm6q_Htt1kDSyi3PX:b-l9yj1x)*

**Comment by soonho-tri** [comment]
Reviewed 14 of 24 files at r1.
Review status: 14 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7502)*

**Comment by soonho-tri** [comment]
Reviewed 9 of 24 files at r1.
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7502#-L-c-qgohQM2FO4hrwFd:-L-c-qgohQM2FO4hrwFe:br8ellv) ([raw file](https://github.com/robotlocomotion/drake/blob/8c3bccd029603efddd674b1d5408f644b2c11218/CMakeLists.txt#L95)):*
> ```CMake
> 
> ExternalProject_Add(drake_cxx_python
>   SOURCE_DIR "${PROJECT_SOURCE_DIR}"
> ```

I don't quite understand why this works. Shouldn't we make this change after hoisting up `drake` dir?

---

*[tools/install/libdrake/BUILD.bazel, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7502#-L-c10BpTlcLQB45eNnb:-L-c10BpTlcLQB45eNnc:bad60e9) ([raw file](https://github.com/robotlocomotion/drake/blob/8c3bccd029603efddd674b1d5408f644b2c11218/tools/install/libdrake/BUILD.bazel#L117)):*
> ```
>     hdrs = [":libdrake_headers"],
>     include_prefix = "drake" if HAS_MOVED_6996 else None,
>     strip_include_prefix = "/",
> ```

Is this necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7502)*

**Comment by jwnimmer-tri** [comment]
Review status: 22 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7502#-L-c-qgohQM2FO4hrwFd:-L-cB093SaQcrTia9NU6:bbxi8g6) ([raw file](https://github.com/robotlocomotion/drake/blob/8c3bccd029603efddd674b1d5408f644b2c11218/CMakeLists.txt#L95)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I don't quite understand why this works. Shouldn't we make this change after hoisting up `drake` dir?
</blockquote></details>

I don't know either, but CI likes it.

---

*[tools/install/libdrake/BUILD.bazel, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7502#-L-c10BpTlcLQB45eNnb:-L-cF8k_2If6tRwCERWc:buzmwjm) ([raw file](https://github.com/robotlocomotion/drake/blob/8c3bccd029603efddd674b1d5408f644b2c11218/tools/install/libdrake/BUILD.bazel#L117)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

Done.

Yes, though only when HAS_MOVED_6996 (though it was a no-op even when unconditional).  I've added the guard for clarity, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7502)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 24 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7502#-L-c-qgohQM2FO4hrwFd:-L-cGFlq9lXwEXlOspHx:bynkeua) ([raw file](https://github.com/robotlocomotion/drake/blob/8c3bccd029603efddd674b1d5408f644b2c11218/CMakeLists.txt#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't know either, but CI likes it.
</blockquote></details>

Hmm... @jamiesnape , could you help us?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7502#-:-L-cGF9AtaCsl4J_J1UE:bnfp4nl)*

**Comment by jamiesnape** [comment]
To answer the question about `SOURCE_DIR`, it should have been `"${PROJECT_SOURCE_DIR}"` from the start, so my mistake. Since we override the configure, build, and install commands anyway, it is not of great consequence to CMake what it is, really. CTest and CDash would prefer it were the folder that contains the `CTestConfig.cmake`, which is `"${PROJECT_SOURCE_DIR}"`.

**Pull request merged**
