### PR TITLE
Do not use pods_use_pkg_config_packages with Bullet

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3472)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3472#-KRni9InwS-3nGEAwDBs:-KRni9InwS-3nGEAwDBt:b-p0wuv1) ([raw file](https://github.com/robotlocomotion/drake/blob/39adc16ebb35a1dfc1a1c14886697677c30ab259/drake/systems/plants/collision/CMakeLists.txt#L13)):*
> ```CMake
> 
> if(BULLET_FOUND)
>   target_compile_definitions(drakeCollision PUBLIC
> ```

BTW, we think these are not actually necessary post #3445, right?  (I'm fine with leaving them in to minimize the change, regardless.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3472#-:-KRnihJP8GLUC9lLCIaM:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3472#-KRni9InwS-3nGEAwDBs:-KRnnLQh0TsOr6adRwW1:b-9xrhop) ([raw file](https://github.com/robotlocomotion/drake/blob/39adc16ebb35a1dfc1a1c14886697677c30ab259/drake/systems/plants/collision/CMakeLists.txt#L13)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, we think these are not actually necessary post #3445, right?  (I'm fine with leaving them in to minimize the change, regardless.)
</details>
Not sure what `BULLET_COLLISION`, but probably not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3472)*

**Comment by jamiesnape** [comment]
Looks like BULLET_COLLISION is needed. I am going to clean up that call now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Pull request merged**
