### PR TITLE
[multibody] Discrete MultibodyPlant uses sampled output ports

### LINKED ISSUE #20545: Reuse ContactSolverResults for performance
This issue is initially raised in the DrakeDeveloper Slack: https://drakedevelopers.slack.com/archives/C0JNB2E3S/p1699888429416319

To facilitate description and discussion of the issue, I will define a few notations to begin with. At a given time t at which a discrete update is performed, we use xᵈ⁻(t) to denote the pre-update discrete state value and xᵈ⁺(t) to denote the post-update value. In #19225, we designed a mechanism to emulate discrete input port sampling in a discrete MultibodyPlant by allowing sampling force input ports only during discrete updates. We use uᵈ⁻(t) to denote the value of the input port forces before sampling (i.e., the value from the sampling done in the previous step), and uᵈ⁺(t) to denote the value of the input port forces from sampling at time t. The value of uᵈ⁺(t) and xᵈ⁺(t) are held constant over the discrete update period, and at the beginning of the next discrete update, we relabel them to (xᵈ⁻(t+1), uᵈ⁻(t+1)) for the computation of the next update. Since #19225, we consistently sample the input ports before performing the discrete update. In other words, the computation of the next discrete state xᵈ⁺(t) is a function of (xᵈ⁻(t), uᵈ⁺(t)).

With these notations in mind, I'll now describe the issue:
In the discrete update for MultibodyPlant, the computation bottleneck usually occurs at computing the contact solver results (SAP or TAMSI), so we would like to cache the results to prevent repeated computation. Ideally, we would like to only perform **one** contact solver computation per discrete step. However, as the slack threads referenced above points out, the current design precludes the caching the contact solver result to some extent. In particular, the contact solver computation are sometimes carried out **twice** in a single discrete step.

To see that, consider the following example:
In the discrete update, the contact solver computation is carried out using (xᵈ⁻(t), uᵈ⁺(t)) which is followed by updating xᵈ⁻(t) to xᵈ⁺(t). Then, immediately after the discrete update, a user of MultibodyPlant pulls on its [contact results output port](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#aa6f63e059613961ba0abb2c1c4532e7c) (which depends on the contact solver results).  Since the discrete state x_d has changed from xᵈ⁻(t) to xᵈ⁺(t) and the contact solver results depend on x_d, the cached contact solver results is invalidated and re-computation is triggered with (xᵈ⁺(t), uᵈ⁺(t)). Similarly, this cached contact solver result is invalidated again at the next discrete update because a new input port value will be sampled right before for the computation of the contact solver results for the next update.

Notice that in the example above, pulling on MultibodyPlant output ports depending on contact solver results repeatedly does not trigger additional contact solver computation because the cached result which is a function of (xᵈ⁺(t), uᵈ⁺(t)) remains valid. Therefore, in a discrete step, we perform at least one contact solver computation and at most two.

Here are a couple of alternatives I have considered to prevent the additional contact solver computation:
1. In the discrete update, instead of computing xᵈ⁺(t) as a function of (xᵈ⁻(t), uᵈ⁺(t)), compute xᵈ⁺(t) as a function of (xᵈ⁻(t), uᵈ⁻(t)). That is, use the input port force value from the previous time step for the discrete update.
This prevents the addtional contact solver computation because if any output port depending the contact solver results has been pulled on since the last discrete update, a computation of contact solver results would have been carried out using (xᵈ⁻(t), uᵈ⁻(t)) (or equivalently (xᵈ⁺(t-1), uᵈ⁺(t-1))), and that cache entry value is still valid and can be reused.
2. With extreme care, manually manage the contact solver cache entry so that when an output port depending on it is pulled after the update from xᵈ⁻(t) to xᵈ⁺(t), reuse the contact solver result computed with (xᵈ⁻(t), uᵈ⁺(t)), instead of recomputing it with (xᵈ⁺(t), uᵈ⁺(t)).

Here are some of the implications for each and the trade-offs:

Option 1 is a breaking change. It offsets the sampling time of input port forces for MultibodyPlant by one step. An immediate consequence is that one cannot modify the input port value and advance a single discrete step and observe any immediate response as is [done here for example](https://github.com/RobotLocomotion/drake/blob/083afa560b77ba819e53945a6479f6974b250550/multibody/plant/test/actuated_models_test.cc#L507-L509). However, note that this is already the behavior for output ports, i.e., modifying input port forces values to MultibodyPlant will not immediately trigger any response in MultibodyPlant output ports, because input port forces are only sampled in a discrete update.

Option 2 is non-breaking. On the other hand, the implementation of option 2 is likely more brittle than 1. Many MultibodyPlant computations depends on contact solver results as well as other ingredients. For example, computing [contact results](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#aa6f63e059613961ba0abb2c1c4532e7c) depends on both the contact solver results and the geometry query results. If we were to freeze the computation of contact solver results to depend on (xᵈ⁻(t), uᵈ⁺(t)), we need to carefully resolve the discrepancy between it and the geometry query results that depend on xᵈ⁺(t) instead of xᵈ⁻(t). The same applies to any current and future MultibodyPlant cache entries and output ports that depend on contact solver results.

@Xining-Du (OP of the slack threads)
@sherm1 @amcastro-tri @jwnimmer-tri @calderpg-tri @EricCousineau-TRI for feedback/thoughts.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #20545.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21597)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21597)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.h` line 271 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O-rFw9-1v2IO3dXUicA:-O-rFw9-1v2IO3dXUicB:b-3lj6ka) ([raw file](https://github.com/RobotLocomotion/drake/blob/6155bf565831e0fe8f173ab6e80e7ca30008e538/multibody/plant/multibody_plant.h#L271)):*
> ```objc
> - body_spatial_velocities
> - body_spatial_accelerations
> - <em style="color:purple">body_spatial_accelerations_feedthrough</em>
> ```

Is "feedthrough" the best suffix here".  Other ideas: "instantaneous" or "unsampled" or ...?
___
*[`multibody/plant/multibody_plant.h` line 272 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O-rFkqW4m3e9YiFHOav:-O-rFkqW4m3e9YiFHOaw:bwyanwx) ([raw file](https://github.com/RobotLocomotion/drake/blob/6155bf565831e0fe8f173ab6e80e7ca30008e538/multibody/plant/multibody_plant.h#L272)):*
> ```objc
> - body_spatial_accelerations
> - <em style="color:purple">body_spatial_accelerations_feedthrough</em>
> - generalized_acceleration
> ```

Working

For now, only one new unsampled (purple) port is shown above.  We'll need to do likewise for all other dynamics-related output ports.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 6 files at r2, 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21597)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

___
*[`multibody/plant/multibody_plant.h` line 271 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O-rFw9-1v2IO3dXUicA:-O-rvaD0ED9N-IPIpuVK:b-hj8qzw) ([raw file](https://github.com/RobotLocomotion/drake/blob/6155bf565831e0fe8f173ab6e80e7ca30008e538/multibody/plant/multibody_plant.h#L271)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is "feedthrough" the best suffix here".  Other ideas: "instantaneous" or "unsampled" or ...?
</blockquote></details>

OK After filling our more user docs, I've decided on "unsampled" for now as probably the best option.
___
*[`multibody/plant/multibody_plant.h` line 272 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O-rFkqW4m3e9YiFHOav:-O-rvezsA0jSvhEqXngw:b-2oe0za) ([raw file](https://github.com/RobotLocomotion/drake/blob/6155bf565831e0fe8f173ab6e80e7ca30008e538/multibody/plant/multibody_plant.h#L272)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

For now, only one new unsampled (purple) port is shown above.  We'll need to do likewise for all other dynamics-related output ports.
</blockquote></details>

OK I added all of them to the summary here now.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21597)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O-s2taRBPIMBJsxfDqU:-O-s2taRBPIMBJsxfDqV:b-iajxs1) (no related file):*
Working

This will need a story for copying a `Context<double>` into a `Context<AutoDiffXd>`.  In the naive implementation, the port sampling is scalar-dependent, so the memory-state cannot transmogrify.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21597)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O-s2taRBPIMBJsxfDqU:-O-s9KlBDlGQzy9m40w-:b-qfzlkz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

This will need a story for copying a `Context<double>` into a `Context<AutoDiffXd>`.  In the naive implementation, the port sampling is scalar-dependent, so the memory-state cannot transmogrify.
</blockquote></details>

OK Done.  Nothing that another layer of templates can't solve.

___

**Comment by sherm1** [comment]
A minor comment: I don't think we should add new ports. A better way to deal with discrete ports (IMO) would be to add a "ForceSample()" function that would cause the ports to be recalculated.

**Comment by jwnimmer-tri** [comment]
If you have comments about the code, go ahead and place there here.  Requirements questions are not effectively discussed in this medium, so please save them for elsewhere.

**Comment by amcastro-tri** [comment]
As far as I can tell parts of this do match at least my mental picture of the solution while others do not. I'll write them down here to double check with you, lots of stuff in this last single commit.
The ones I believe match my mental picture are:
 1. You have an addional state for `ContactSolverResults` (buried inside `DiscreteStepMemory`). I am pretty certain here you can get away with just `ContactSolverResults` as the additional state.
 2. I like that now we can depend on the new state (`memory_ticket`)

The ones that do not:
 1. The ability to chose a "mode". IMO this should always behave as "sampled" in your lingo. That's the one that matches the math (I'll write down separately and link here)

The ones I do not even understand:
 1. Usage of a comgination of periodic and forced unrestricted updates. I am pretty certain here we can accomplish what we need with a single discrete update event. But TBH, I am not as familiar with unrestricted updates so maybe there are as good. Still I find it strange we needed two of these instead of just one.
 2. As an example, body spatial accelerations output port depends on `memory_ticket` only. On a first read, that seems the right thing to do. What I do find difficult to reconciliate is how to handle parameters. Say someone does change a paramter, how does the invalidation go? A user won't see the effect of parameter change untile the next discrete update step. Maybe that's the right thing, but I wanted to double check your thoughts on this.

**Review by xuchenhan-tri — COMMENTED** [review]
@jwnimmer-tri, 

I've made a pass over the implementation. It matches well with my mental picture. I don't have an opinion yet on whether it's a good idea to keep duplicated ports or we should use sampled ports all the way for discrete plant. I'll defer that to Sherm and Alejandro who have thought more about the issue. I will comment though that it seems to me that most of the complexities introduced in this PR stems from trying to keep the duplicated ports. I'll sprinkle some comments below if my browser doesn't blow up expanding the files.

@amcastro-tri,

> I am pretty certain here you can get away with just `ContactSolverResults` as the additional state

I think that's incorrect. For example, to compute the contact results, you would need the contact surface from query object, which is not stored in solver results.

> I am pretty certain here we can accomplish what we need with a single discrete update event...

The reason we need to use unrestricted updates is because we can't touch abstract state in a discrete update.

> What I do find difficult to reconciliate is how to handle parameters. Say someone does change a paramter, how does the invalidation go?

I don't think the sampled ports should reflect the change in parameters instantaneously. That's the nature of "sampling". In fact, all "sampled ports" should *only* depend on the memory ticket IMO. If that fails to work, that means that we need to put more stuff into the "memory data structure".

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-:-O0BePlzB0Iiq6xzsUzT:bca267l)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> I will comment though that it seems to me that most of the complexities introduced in this PR stems from trying to keep the duplicated ports.

The complexity isn't from the new "unsampled"-named ports alone.  If we allow `SetUseSampledOutputPorts` as public API, or if we add "foo_unsampled" output ports, or both -- then in those cases we need the `template <bool sampled>` on calc functions.  Only if we provide _no mechanism whatsoever_ for feedthrough output do we get to shave the code down a little bit.

Our agreement with Russ from this spring / last fall about adding more State to MbP was that we need an opt-out so that planning and analysis code is not polluted by the extra memory.  The default can be memory (since that is the primary use case), but we need an opt-in way to not add more State.  My proposal is that `SetUseSampledOutputPorts(false)` will be that opt-out, and so we need to implement a feedthrough `CalcFooOutput<sampled=false>` one way or another.

In any case, the current hard work of making a Memory-only implementation of the Calc functions remains no matter what, so for now I'm still going to focus on that (and landing the preparatory cleanups so that the Memory work is crisp and clear).

**Comment by jwnimmer-tri** [comment]
> I don't think the sampled ports should reflect the change in parameters instantaneously.

I could probably go either way on that.  I agree with Xuchen that it would be OK to say "sampled output ports never reflect changes to parameters until after the next sample".  However, I would also be OK saying "sampled output ports **do not necessarily** reflect changes to parameters until after the next sample".  The entire premise of a Parameter is that it's not time-varying, so how it interacts with time stepping is somewhat of a moot point.  If it's easy to implement "never" then we should do that, to that it's simple to document and test.  If it's easier to implement "some parameters might leak out, even without a step" then that might be okay too.

**Comment by jwnimmer-tri** [comment]
> ... need to implement a feedthrough `CalcFooOutput<sampled=false>` one way or another.

Hmm, I wonder -- if sampling was turned off in the Russ example, maybe the Memory is just a cache entry?  You could imagine that if someone asks for an output port value from an unsampled discrete plant, the right thing to do is to calculate the unrestricted update event into a temporary, and call the calc output function on that scratch Memory.  I might try that in my code later on.

**Review by xuchenhan-tri — COMMENTED** [review]
> Only if we provide _no mechanism whatsoever_ for feedthrough output do we get to shave the code down a little bit.

Yes, that was what I was suggesting, but obviously I forgot about the deal with Russ.

> Hmm, I wonder -- if sampling was turned off in the Russ example, maybe the Memory is just a cache entry?

Not sure if I'm following here. If sampling is turned off, then "memory" isn't necessary at all for any computation; i.e. any computation result can be recovered from the input port values and the discrete states. Therefore, in that case, "memory" shouldn't be a state. I'm not sure how much value it provides as a cache entry in addition to solver results that we already cache.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-:-O0Brb8UBaD3PYqnrjET:bqmm3xu)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`multibody/plant/discrete_update_manager.h` line 117 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O0BmIkq0i3bP8-xA5g-:-O0BmIkq0i3bP8-xA5g0:b-32hq0) ([raw file](https://github.com/RobotLocomotion/drake/blob/73364d1f2b2b24d32768384a872f991b97266713/multibody/plant/discrete_update_manager.h#L117)):*
> ```objc
>   std::vector<geometry::PenetrationAsPointPair<T>> point_pairs;
>   std::vector<geometry::ContactSurface<T>> surfaces;
>   // TODO(jwnimmer-tri) It seems to me like DeformableContact<T> should be
> ```

BTW, yes, that is correct.
___
*[`multibody/plant/multibody_plant.cc` line 3220 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O0BkT5r3CE6lKCm-6Nf:-O0BkT5r3CE6lKCm-6Ng:b-6p59n8) ([raw file](https://github.com/RobotLocomotion/drake/blob/73364d1f2b2b24d32768384a872f991b97266713/multibody/plant/multibody_plant.cc#L3220)):*
> ```cpp
> 
>   // Output "spatial_accelerations" (deprecated).
>   // XXX wrong deps?
> ```

BTW, I don't see the wrong deps here.
___
*[`multibody/plant/multibody_plant.cc` line 3263 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O0BpR-c9s79IqzMYWdL:-O0BpR-c9s79IqzMYWdM:b-b5ulps) ([raw file](https://github.com/RobotLocomotion/drake/blob/73364d1f2b2b24d32768384a872f991b97266713/multibody/plant/multibody_plant.cc#L3263)):*
> ```cpp
>     contact_results_prerequisites.insert(this->all_input_ports_ticket());
>     contact_results_prerequisites.insert(this->all_parameters_ticket());
>   }
> ```

BTW, I think you need the input ports and the parameters in both continuous and discrete mode?



_Code quote:_
```cpp
  // XXX WTF is this correct?
  std::set<DependencyTicket> contact_results_prerequisites = {state_ticket};
  if (is_discrete()) {
    contact_results_prerequisites.insert(this->all_input_ports_ticket());
    contact_results_prerequisites.insert(this->all_parameters_ticket());
  }
```
___
*[`multibody/plant/multibody_plant.cc` line 3345 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O0BnXk1EM-ZJeSP0uam:-O0BnXk1EM-ZJeSP0uan:b-l83n4n) ([raw file](https://github.com/RobotLocomotion/drake/blob/73364d1f2b2b24d32768384a872f991b97266713/multibody/plant/multibody_plant.cc#L3345)):*
> ```cpp
>       this->DeclareCacheEntry(std::string("GeometryContactSummary"),
>                               &MultibodyPlant::CalcGeometryContactSummary,
>                               {this->configuration_ticket()});
> ```

BTW, First, the dependency is wrong and it should depend on the query object port. Second, though it's very tempting, we should make sure that any downstream sampled ports doesn't depend on this. Otherwise extra geometry queries may be triggered.



_Code quote:_
```cpp
{this->configuration_ticket()});
```
___
*[`multibody/plant/multibody_plant.cc` line 3855 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O0BqEcd3549xZKdb7SO:-O0BqEcd3549xZKdb7SP:b-7tf0pg) ([raw file](https://github.com/RobotLocomotion/drake/blob/73364d1f2b2b24d32768384a872f991b97266713/multibody/plant/multibody_plant.cc#L3855)):*
> ```cpp
>   auto& tau_applied = applied_forces.mutable_generalized_forces();
>   if (is_discrete()) {
>     DRAKE_DEMAND(sampled == false);  // XXX bad context no biscuit
> ```

BTW, not sure what you mean here. Is it still unfinished? Surely we don't want to abort as soon as someone yank on this port.
Ditto for contact results port.

**Comment by jwnimmer-tri** [comment]
> Not sure if I'm following here. If sampling is turned off, then "memory" isn't necessary at all for any computation; i.e. any computation result can be recovered from the input port values and the discrete states.

The idea would that that for `CalcFooOutput` (for dynamics output ports), the first thing it does it obtain `const Memory& memory ...` somehow -- when sampled, get it from State; when unsampled, evaluate the cache entry.  Now, implement the Calc code in terms of `const Memory& memory` instead of `const Context& context`.  The important logic inside of CalcFooOutput is the same now , no more extra branching.  I could probably even declare the member function to take `const Memory&` only -- no Context -- and use the port-declaration sugar to decide how the Memory reaches it, with a few little shims.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21597)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`multibody/plant/multibody_plant.cc` line 3220 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O0BkT5r3CE6lKCm-6Nf:-O0CC6y2BxeHRdiBvI32:bczpavu) ([raw file](https://github.com/RobotLocomotion/drake/blob/73364d1f2b2b24d32768384a872f991b97266713/multibody/plant/multibody_plant.cc#L3220)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I don't see the wrong deps here.
</blockquote></details>

OK A lot of what was here was a WIP, and still needed a lot of fine-tuning.  A bunch of these things are notes to myself, to check before I put up for a code review.
___
*[`multibody/plant/multibody_plant.cc` line 3263 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O0BpR-c9s79IqzMYWdL:-O0CCIp-45VfnWTJZ6UX:b-mqybls) ([raw file](https://github.com/RobotLocomotion/drake/blob/73364d1f2b2b24d32768384a872f991b97266713/multibody/plant/multibody_plant.cc#L3263)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I think you need the input ports and the parameters in both continuous and discrete mode?
</blockquote></details>

OK A lot of what was here was a WIP, and still needed a lot of fine-tuning.  A bunch of these things are notes to myself, to check before I put up for a code review.  But yes, I think you are right but I'm going to redo all of the tickets from a clean slate after the code settles down.
___
*[`multibody/plant/multibody_plant.cc` line 3855 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21597#-O0BqEcd3549xZKdb7SO:-O0CCkH2D_nUeu01cTVi:b-ischab) ([raw file](https://github.com/RobotLocomotion/drake/blob/73364d1f2b2b24d32768384a872f991b97266713/multibody/plant/multibody_plant.cc#L3855)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, not sure what you mean here. Is it still unfinished? Surely we don't want to abort as soon as someone yank on this port.
Ditto for contact results port.
</blockquote></details>

Still a WIP.  The "no biscuit" are places I haven't finished writing the code.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 857 of 879 files at r15, 857 of 867 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21597)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Comment by jwnimmer-tri** [comment]
Hmm, even after rebasing away the 800 files thing, the review page is still pretty slow.  I'll probably need to open a new PR number.  I'll wait until a couple more cleanups land before I do that.

**Comment by jwnimmer-tri** [comment]
Okay, unfortunately it's time to close this PR number down and get a fresh one.  The temporary 800 files in the review has clogged things up.  I'll open a new PR number (with the same branch name) shortly, and edit this comment to point there.

**Pull request closed without merging**
