### PR TITLE
Remove link to rtedrake's personal dropbox inadvertently included here

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2581)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@russtedrake for verification.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2581#-:-KKV92jr3g2tlnGdmzIA:1386667035)*

**Comment by RussTedrake** [comment]
lgtm.  thanks.

**Comment by ggould-tri** [comment]
In order to force this trivial change through, I am going to violate policy and :lgtm: this myself.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2581#-:-KKVB5H-abtB2QfsBUzk:667382433)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2581#-:-KKVCkyfjuDZVmjAOL_f:-1868698381)*

**Pull request merged**
