### PR TITLE
Update llvm source

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Fixes issue reported in #4748

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4800)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by BetsyMcPhail** [comment]
Provisioning script installed clang 3.9! The script still fails due to missing packages. See #4782.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4800#-:-Kah4LveqA_kO8__2AEq:bnfp4nl)*

**Comment by david-german-tri** [comment]
+@david-german-tri :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4800#-:-Kah4eK_LY8wxgm0ATC9:b-vdolsb)*

**Pull request merged**
