### PR TITLE
Update prerequisites 

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.  The full WIP branch is https://github.com/jwnimmer-tri/drake/tree/build-drake-folder-6996.

Note that possibly more packages are also forthcoming into `install_prereqs.sh`s.  I will see if we can batch them into a single round of new AMI / VM images.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7221)

### CODE REVIEW

**Comment by jamiesnape** [comment]
FYI You totally read my mind with this PR. If we can combine updates with a bump of Bazel to 0.5.3 or 0.5.4, it would be really helpful.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7221#-:-Kw0E0qIgqctB3dbtzSs:bajbi0c)*

**Comment by jwnimmer-tri** [comment]
Yeah.  FYI I am also hoping to have a guess about `libompl-dev` and/or Boost additions to the base image before we re-spin.

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@soonho-tri for apple feature review and platform review, please.

Obviously CI is not going to pass yet, but I want to get sign-off on the idea before we schedule a (coordinated) CI image revamp.

**Comment by jwnimmer-tri** [comment]
FYI I don't think we're going to have a solid OMPL-related answer very soon.  If we want to add `libboost-all-dev` into the new images for future-proofing that's OK by me.  If not, it can just be `libtinyxml2-dev` and Bazel 0.5.4.

**Comment by soonho-tri** [comment]
platform & :apple: :lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7221#-:-Kw5UDBCvp-fZqr3ontU:b-fr82oc)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7221#-:-Kw5gwhbe42hyrAIBpnf:bnfp4nl)*

**Comment by jamiesnape** [comment]
Let's add `libboost-all-dev` as well. It basically syncs the amount of Boost available to both Linux and Mac.

**Comment by jwnimmer-tri** [comment]
SGTM.  Do you want to do that only in the AMIs, or also have `install_prereqs.sh` grab it locally for everyone too?  (If the latter, I can add a commit to this PR.)

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7221)*

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7221)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7221#-Kw6RmZajQR1dIE8D1oO:-Kw6RmZajQR1dIE8D1oP:b-orkvyu) (no related file):*
I need to rebase this, but will wait for the `unprovisioned` smoke tests to finish first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7221)*

**Comment by jamiesnape** [comment]
Unprovisioned are all good.

**Comment by jamiesnape** [comment]
Do you want to update the Bazel version in [supported configurations](https://github.com/RobotLocomotion/drake/blob/master/drake/doc/developers.rst#supported-configurations) in this PR too?

**Comment by jwnimmer-tri** [comment]
I've pushed a rebase (with doc fixes -- thanks!).  I think we're ready to move on to AMI / VM provisioning changes?

**Comment by jamiesnape** [comment]
Yes, @BetsyMcPhail is working on it now.

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7221)*

**Comment by BetsyMcPhail** [comment]
Linux AMI has been updated, working on Macs now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by BetsyMcPhail** [comment]
Mac images have also been updated

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
```

```CMake Error at CMakeLists.txt:43 (add_subdirectory):   add_subdirectory given source "thirdParty/zlib/tinyxml2" which is not an   existing directory.```

**Comment by jwnimmer-tri** [comment]
That's right, I knew I was forgetting something.  I'll let the mac builds finish before re-pushing with that fix.

**Comment by jamiesnape** [comment]
You can fix it now, I can see an issue with the Mac images, so we will need to restart them anyway.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
All green.

**Pull request merged**
