### PR TITLE
[math] Use highway instead of intrinsics

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Another attempt at #21571.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),sherm1(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 216 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0AwKcf5-G0A9FCpv4F:-O0AwKcg8Fpjz_xTdNxu:bt43o4c) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L216)):*
> ```cpp
>   const auto efgh = hn::LoadU(tag, R_BA + 4);
>   const auto iiii = hn::Set(tag, R_BA[8]);
>   const auto abgh = hn::ConcatUpperLower(tag, efgh, abcd);  // ..gh|ab.. => abgh
> ```

BTW This mirrors the comment I put in #21571.

This function is the sole source of name and API weirdness.

1) This is where the admonition of "beware the blocks" best belongs.
2) I'd still hope for an explicit comment here helping readers of the hump of  the *parameter* order.  I.e., `ConcatUpperLower(tag, efgh, abcd)` doesn't give us `ghab`, but `abgh`. The reader may intuit the "upper" block correctly, but nothing in the call site suggests that the parameters are interpreted as "higher" and "lower", respectively.

If you contrast that with the `Interleave*` operations, where it behaves far more intuitively w.r.t. the name and the parameter order.

**Review by sherm1 — COMMENTED** [review]
:lgtm: -- this (the old spellings) is definitely better. IMO needs a few more comments around the problematic Concat and Interleave calls but is otherwise much easier to follow (and probably easier to write as well).

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-:-O0B18tY1G4EhxOSuV8b:bdjxzd2)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 216 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0AwKcf5-G0A9FCpv4F:-O0Ay-UV7DyP9x8XX55V:b-ud45tx) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L216)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This mirrors the comment I put in #21571.

This function is the sole source of name and API weirdness.

1) This is where the admonition of "beware the blocks" best belongs.
2) I'd still hope for an explicit comment here helping readers of the hump of  the *parameter* order.  I.e., `ConcatUpperLower(tag, efgh, abcd)` doesn't give us `ghab`, but `abgh`. The reader may intuit the "upper" block correctly, but nothing in the call site suggests that the parameters are interpreted as "higher" and "lower", respectively.

If you contrast that with the `Interleave*` operations, where it behaves far more intuitively w.r.t. the name and the parameter order.
</blockquote></details>

Agreed -- some extra verbosity here could go a long way. Maybe something like
```c++
// Highway sees this as: ConcatUpperLower(ghef, cdab) -> ghab.
// Then C++(ghab) -> abgh
```
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0B-_WW5iqv0clTG7y3:-O0B-_WW5iqv0clTG7y4:b-r7z7bx) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L217)):*
> ```cpp
>   const auto iiii = hn::Set(tag, R_BA[8]);
>   const auto abgh = hn::ConcatUpperLower(tag, efgh, abcd);  // ..gh|ab.. => abgh
>   const auto adgf = hn::InterleaveLower(tag, abgh, defg);   // a.g.|d.f. => adgf
> ```

BTW I think this can be described more consistently as
```c++
// InterleaveLower(ghab, fgde) -> gfad -> adgf
```
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 220 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0Azbfa24Buc094qprW:-O0Azbfb9zQqytBGH0SZ:b-itx8pj) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L220)):*
> ```cpp
>   const auto behg = hn::InterleaveUpper(tag, abgh, defg);   // .b.h|.e.g => behg
>   const auto adcf = hn::InterleaveLower(abcd, defg);        // a.c.|d.f. => adcf
>   const auto cfii = hn::ConcatUpperUpper(tag, iiii, adcf);  // ..ii|..cf => cfii
> ```

BTW similarly
```c++
// Highway sees this as: ConcatUpperUpper(iiii, cfad) ->iicf.
// Then C++(iicf) -> cfii
```
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 386 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0B0soDCM9GmGbSBAO4:-O0B0soDCM9GmGbSBAO5:bior0xe) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L386)):*
> ```cpp
>   <jkl_> =   <abc_> * <AAA_>
>            + <def_> * <BBB_>
>            + <dghi_> * <CCC_>
> ```

typo: dghi_ -> ghi_

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 216 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0AwKcf5-G0A9FCpv4F:-O0B5kFj7OKSnWHx5P9L:bo5xyk) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L216)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Agreed -- some extra verbosity here could go a long way. Maybe something like
```c++
// Highway sees this as: ConcatUpperLower(ghef, cdab) -> ghab.
// Then C++(ghab) -> abgh
```
</blockquote></details>

Possibly the mental model was still not crystal clear.  I tried adding another comment to help it along.
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0B-_WW5iqv0clTG7y3:-O0B5rOBDIdCHs9gv7vA:bme67uz) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L217)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I think this can be described more consistently as
```c++
// InterleaveLower(ghab, fgde) -> gfad -> adgf
```
</blockquote></details>

I realized that for 8-byte lanes, InterleaveEven and InterleaveOdd are synonyms for InterleaveLower and InterleavesUpper, and probably more clear.

Better now, with that rename + comments?

**Comment by jwnimmer-tri** [comment]
We'll plan to use this PR for reviews and merging.

I'll also push the old PR to match this one, in case you want to compare the older drafts to this.

**Review by sherm1 — COMMENTED** [review]
Still struggling with the explanation, ptal.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-:-O0BJj4CC-ejIRKIIbGp:bbvycgi)* status: 5 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 216 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0AwKcf5-G0A9FCpv4F:-O0BIjxS2GTON9Y_EGi_:b3btntc) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L216)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Possibly the mental model was still not crystal clear.  I tried adding another comment to help it along.
</blockquote></details>

So far that hasn't helped me. I think I'm more confused now -- I thought I had a workable model but now I don't think so! (Maybe that's progress?)
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0B-_WW5iqv0clTG7y3:-O0BHn9d04igfOPmLsoD:b7gsuxd) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I realized that for 8-byte lanes, InterleaveEven and InterleaveOdd are synonyms for InterleaveLower and InterleavesUpper, and probably more clear.

Better now, with that rename + comments?
</blockquote></details>

I couldn't find [Highway documentation](https://google.github.io/highway/en/master/) for Interleave{Even,Odd}. Where did you find those?

But no, I don't feel I have a better grasp now than before. For example, I don't understand why I can interpret the even part of abcd as "a.c." since those indices (0, 2) are offsets into _our_ C++ array ordering which if reversed to match the Highway model (I think) would be indices (3,1) so would be odd.
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 225 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0BEWcE4sej2ZvpkkMo:-O0BEWcE4sej2ZvpkkMp:bnhye6g) ([raw file](https://github.com/RobotLocomotion/drake/blob/329c208f0d8ce03a1ba12ac0f2ad08685dfe9f90/math/fast_pose_composition_functions_avx2_fma.cc#L225)):*
> ```cpp
>   //                       on top of the Lower half of `lo`, and
>   //         ConcatUpperUpper stacks the Upper half of `hi`
>   //                       on top of the Upper half of `lo`.
> ```

BTW I can't reliably reconcile this line:
```
hn::ConcatUpperLower(tag, efgh, abcd);  // ..gh|ab.. => abgh
```
with the above description. The assortment upper/lower/hi/lo/"stacks on" and our variable notation each imply some kind of ordering, as yet undefined. Here hi=efgh, lo=abcd, upper_half(hi) is apparently gh, but "stacking it on" lower_half(lo) puts it at the higher addresses in abgh.

All these terms seem ambiguous to me. I can invent definitions for them that make the symbols match but I still don't have a model I can use reliably. 

Also I'm not sure I understand how the blockwise operation of Interleave and the non-blockwise operation of Concat factor in here. Why don't we have to mention blocks for the explanation of Interleave?
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 227 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0BCY0P2eGhH_bybkG8:-O0BCY0P2eGhH_bybkG9:bl6utjz) ([raw file](https://github.com/RobotLocomotion/drake/blob/329c208f0d8ce03a1ba12ac0f2ad08685dfe9f90/math/fast_pose_composition_functions_avx2_fma.cc#L227)):*
> ```cpp
>   //                       on top of the Upper half of `lo`.
>   //
>   // - InterleaveEven(a, b) interleaves the even-numbered names of `a` and `b`
> ```

typo: names -> lanes
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 231 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0BC_Dx66GaFNdJnTfJ:-O0BC_Dx66GaFNdJnTfK:b-w8uof9) ([raw file](https://github.com/RobotLocomotion/drake/blob/329c208f0d8ce03a1ba12ac0f2ad08685dfe9f90/math/fast_pose_composition_functions_avx2_fma.cc#L231)):*
> ```cpp
>   //   of `a` are replaced the even-numbered lanes of `b`.
>   //
>   // - InterleaveEven(a, b) interleaves the odd-numbered names of `a` and `b`
> ```

typo: Even -> Odd, names -> lanes

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: 5 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0B-_WW5iqv0clTG7y3:-O0BK-x83ciFjg7am83y:b-k4u1qd) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L217)):*
Nothing about the highway model is "reversed".  The lowest-order lane is still lane number 0, and counts up from there.

Always in our code (and semantics) for a variable named "abcd" we have lane zero as "a" and C array element 0 as "a".

> I couldn't find Highway documentation ...

Working

I found then in the source code.  I'll see if I can find a better source.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0B-_WW5iqv0clTG7y3:-O0BM20h9tFFJ4q_Gkim:b-obx9sa) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ed3f881284772eb05548af337bbb51c59fa552e/math/fast_pose_composition_functions_avx2_fma.cc#L217)):*
I'm still working on improving the clarity / comments, but one update in the meantime:

> I couldn't find Highway documentation ...

Apparently the rendered HTML page isn't kept fresh anymore.  I changed the link (atop this file) to github directly.  Slightly less pretty, but at least it's fresh.

**Comment by jwnimmer-tri** [comment]
I gave it another shot.  Maybe call me if it's still unclear and we can co-design the best language f2f.

**Review by sherm1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 235 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0BVdXYB9LDL5i0WjWk:-O0BVdXYB9LDL5i0WjWl:b-vdnxnn) ([raw file](https://github.com/RobotLocomotion/drake/blob/378d4ac619716b9dd26110cd5d2a55e5f01f1b43/math/fast_pose_composition_functions_avx2_fma.cc#L235)):*
> ```cpp
>   //     ConcatUpperUpper(0123, 4567) => 6723
>   //     ConcatLowerUpper(0123, 4567) => 6701
>   //     ConcatUpperLower(0123, 4567) => 4523
> ```

This is helping. What I really need is a drawing. Maybe I understand enough to draw one now. Here's a shot:
```
The only data structure we use here is a 256 bit array of four doubles. Each double is a lane and they are numbered like this

Lanes:   |    0    |    1    |    2    |   3   |
                 lower half       upper half
Blocks:   |         0          |          1        |

Some Highway functions operate on blocks of 128 bits rather than individual lanes; in those cases the blocks are numbered as shown. Note that "half" and "block" are synonymous here.

When in memory, lane 0 has the lowest memory address. We'll use a four-character notation like abcd where the letters correspond to the lanes in order.

One quirk of the Highway function set is that the ConcatFooBar(hi, lo) family take their arguments in hi,lo order although "hi" is the source for the _upper_ half while "lo" is the source for the lower half. Thus ConcatLowerUpper(hi,lo) produces lo[2:3] hi[0:1] which is the reverse of what you might expect.
```

WDYT?  
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 241 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0BUG4-6-EzyPGCI6Zl:-O0BUG4-6-EzyPGCI6Zm:bqiw8n) ([raw file](https://github.com/RobotLocomotion/drake/blob/378d4ac619716b9dd26110cd5d2a55e5f01f1b43/math/fast_pose_composition_functions_avx2_fma.cc#L241)):*
> ```cpp
>   //   of `a` are replaced the even-numbered lanes of `b`.
>   //
>   // - InterleaveEven(a, b) interleaves the odd-numbered lanes of `a` and `b`
> ```

typo: Even -> Odd

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 235 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0BVdXYB9LDL5i0WjWk:-O0BYbui0xVElXo8k0WX:b-dvic44) ([raw file](https://github.com/RobotLocomotion/drake/blob/378d4ac619716b9dd26110cd5d2a55e5f01f1b43/math/fast_pose_composition_functions_avx2_fma.cc#L235)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This is helping. What I really need is a drawing. Maybe I understand enough to draw one now. Here's a shot:
```
The only data structure we use here is a 256 bit array of four doubles. Each double is a lane and they are numbered like this

Lanes:   |    0    |    1    |    2    |   3   |
                 lower half       upper half
Blocks:   |         0          |          1        |

Some Highway functions operate on blocks of 128 bits rather than individual lanes; in those cases the blocks are numbered as shown. Note that "half" and "block" are synonymous here.

When in memory, lane 0 has the lowest memory address. We'll use a four-character notation like abcd where the letters correspond to the lanes in order.

One quirk of the Highway function set is that the ConcatFooBar(hi, lo) family take their arguments in hi,lo order although "hi" is the source for the _upper_ half while "lo" is the source for the lower half. Thus ConcatLowerUpper(hi,lo) produces lo[2:3] hi[0:1] which is the reverse of what you might expect.
```

WDYT?
</blockquote></details>

As it turns out *none* of the functions we use anymore here operate on blocks. If we called ConcatUpperUpper on a 16-lane vector, the "half" splits would be lanes 0--7 and 8--15, not the blocks 0-1, 2-3, 4-5, etc. So the "blocks" thing (pairs of lanes) is a distraction.  (See [#blockwise](https://github.com/google/highway/blob/master/g3doc/quick_reference.md#blockwise) if you want the details on blockwise things.)

I think the only confusion we have here is that we write our variables with lower lanes on the left, and upper lanes on the right, but this one hwy function in particular takes `hi` as the first arg and `lo` and the second arg, so the obvious left-to-right skim doesn't work right away.  If the function arguments were named `(lo, hi)` this would have been easier.

First change -- I moved the Even/Odd discussion first in the comment.  It's the easier one to understand, do might as well get it out of the way first.

Then, I took your "One quirk" and reworked it a bit, and tried to add a more helpful figures vs my prior examples.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 235 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0BVdXYB9LDL5i0WjWk:-O0BdES932tHAEz4OywA:bdydofo) ([raw file](https://github.com/RobotLocomotion/drake/blob/378d4ac619716b9dd26110cd5d2a55e5f01f1b43/math/fast_pose_composition_functions_avx2_fma.cc#L235)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As it turns out *none* of the functions we use anymore here operate on blocks. If we called ConcatUpperUpper on a 16-lane vector, the "half" splits would be lanes 0--7 and 8--15, not the blocks 0-1, 2-3, 4-5, etc. So the "blocks" thing (pairs of lanes) is a distraction.  (See [#blockwise](https://github.com/google/highway/blob/master/g3doc/quick_reference.md#blockwise) if you want the details on blockwise things.)

I think the only confusion we have here is that we write our variables with lower lanes on the left, and upper lanes on the right, but this one hwy function in particular takes `hi` as the first arg and `lo` and the second arg, so the obvious left-to-right skim doesn't work right away.  If the function arguments were named `(lo, hi)` this would have been easier.

First change -- I moved the Even/Odd discussion first in the comment.  It's the easier one to understand, do might as well get it out of the way first.

Then, I took your "One quirk" and reworked it a bit, and tried to add a more helpful figures vs my prior examples.
</blockquote></details>

OK, this is great -- thanks!

**Review by sherm1 — COMMENTED** [review]
:lgtm: again!

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-:-O0BdSLj7LDMwB4ZRNjR:butqos0)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
Thanks!  I think it's a lot better now than when it started.

I imagine we'll learn more about the hwy "programming language" as we use it in more places.

I'll re-ping @SeanCurtis-TRI for a final review / platform review LGTM, please.

**Comment by jwnimmer-tri** [comment]
I pinged upstream about the HTML docs going stale, and the problem is fixed now.  I changed the link back to the HTML.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-:-O0EtVI65BMpBOeX6-Wd:bmxilld)* status: 6 unresolved discussions

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 173 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0EpoqpDhq2xHyKNusU:-O0EpoqqEk9dPaweFYMW:b-d5wap0) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L173)):*
> ```cpp
>   const auto abc_ = hn::LoadU(tag, R_AB);      // (d is loaded but unused)
>   const auto def_ = hn::LoadU(tag, R_AB + 3);  // (g is loaded but unused)
>   const auto ghi_ = hn::LoadN(tag, R_AB + 6, 3);
> ```

BTW I'm curious; while the import of not *writing* outside of the bounds is clear, what's the risk in *reading* outside of the array's bounds? It's the difference between having a zero in the high lane vs whatever garbage 8 bytes are next in memory interpreted as a double, but as it's officially a "don't care", do we have to care? (On the other hand, the cost "benefit" of  using a `LoadU` instead of a `LoadN` may be so small, that avoiding even the smallest of risk is worth it.)
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 221 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0Eoq6T7ombHjB8kdhG:-O0Eoq6T7ombHjB8kdhH:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L221)):*
> ```cpp
>   // - InterleaveEven(a, b) interleaves the even-numbered lanes of `a` and `b`
>   //   (and discards the odd-numbered lanes), i.e., the odd-numbered lanes
>   //   of `a` are replaced the even-numbered lanes of `b`.
> ```

nit: typo



_Suggestion:_
```cpp
are replaced by the
```
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 225 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0EofutDWt4L9rNPuCQ:-O0EofutDWt4L9rNPuCR:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L225)):*
> ```cpp
>   // - InterleaveOdd(a, b) interleaves the odd-numbered lanes of `a` and `b`
>   //   (and discards the even-numbered lanes), i.e., the even-numbered lanes
>   //   of `b` are replaced the odd-numbered lanes of `a`.
> ```

nit: typo



_Suggestion:_
```cpp
replaced by the
```
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 227 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0EpPJx88osAf0cT-a1:-O0EpPJx88osAf0cT-a2:b-kjf5dp) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L227)):*
> ```cpp
>   //   of `b` are replaced the odd-numbered lanes of `a`.
>   //
>   // - ConcatFooBar(hi, lo) combines half of `hi` with half of `lo`.
> ```

BTW I really appreciate the text here. Simply calling out that this one function is *weird* is incredibly helpful. The concrete examples work well in support. So, thanks for this effort.
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 234 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0EpDaJ9Cdr54aPvmJH:-O0EpDaJ9Cdr54aPvmJI:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L234)):*
> ```cpp
>   //
>   //     The upper half of the result comes from the Foo part of `hi`. The lower
>   //     half of the result comes from the Bar half of `lo`. One noteable quirk
> ```

nit: typo



_Suggestion:_
```cpp
notable
```
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 332 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0Er6CF6dvTN3_Bb73k:-O0Er6CF6dvTN3_Bb73l:b-l9j1dc) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L332)):*
> ```cpp
>   LoadMatrix3Inv(R_BA, &adg_, &beh_, &cfi_);
> 
>   // Load R_BC.
> ```

BTW From here to the end of the function, the code is identical to `ComposeRRAvx`. Is there any reason to to refactor the common code and trust it to be inlined? 

(Similar, but not identical, questions could be posed about transform concatenations.)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: 1 unresolved discussion

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 173 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0EpoqpDhq2xHyKNusU:-O0Eu0Y97YQNLjlmnLZY:bliwjum) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L173)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm curious; while the import of not *writing* outside of the bounds is clear, what's the risk in *reading* outside of the array's bounds? It's the difference between having a zero in the high lane vs whatever garbage 8 bytes are next in memory interpreted as a double, but as it's officially a "don't care", do we have to care? (On the other hand, the cost "benefit" of  using a `LoadU` instead of a `LoadN` may be so small, that avoiding even the smallest of risk is worth it.)
</blockquote></details>

Reading past the end of allocated memory is UB, and might segfault.
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 332 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0Er6CF6dvTN3_Bb73k:-O0EuTxrDGXClbR49rFi:b-jgz2hb) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L332)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW From here to the end of the function, the code is identical to `ComposeRRAvx`. Is there any reason to to refactor the common code and trust it to be inlined? 

(Similar, but not identical, questions could be posed about transform concatenations.)
</blockquote></details>

I'm going to defer that to another day, maybe next time we work to speed up this code.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 173 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0EpoqpDhq2xHyKNusU:-O0EvG0f96uvdFB03Wgr:b-n6ju9t) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L173)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Reading past the end of allocated memory is UB, and might segfault.
</blockquote></details>

(On Intel, LoadU has a latency of 7 cycles, LoadN has 8.  So not a giant penalty either.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21600)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 173 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21600#-O0EpoqpDhq2xHyKNusU:-O0F7NZvEvHaUUUyfpvH:b4if05j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4517a152ad8ed52e8fec0a04cfa0131b32c89f76/math/fast_pose_composition_functions_avx2_fma.cc#L173)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(On Intel, LoadU has a latency of 7 cycles, LoadN has 8.  So not a giant penalty either.)
</blockquote></details>

Safe and more or less free (particularly compared to everything else that happens).

**Pull request merged**
