### PR TITLE
adds a helper utility to wire up random input ports on a DiagramBuilder

### PR DESCRIPTION
**Pull request by RussTedrake**
Also makes default seeds for RandomSource blocks unique  …
(resolves nasty "feature" where all of our random source blocks were accidentally perfectly correlated)

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7149)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@seancurtis-tri for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-:-KvMLJECPGVCHweYX5TD:b-t5m2ic)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with some cosmetic stuff.

+(status: curate commits before merging) 

---

Reviewed 5 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/primitives/random_source.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSWzI6OgqYacW-mRax:-KvSWzI7vA9l-8KZmaFO:b-ie7w8b) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.cc#L9)):*
> ```cpp
>                     DiagramBuilder<double>* builder) {
>   int count = 0;
>   for (const auto system : builder->GetMutableSystems()) {
> ```

BTW This struck me as a bit odd for two reasons:

1. The type of `const auto` could be made more clear with `const auto*`.
2. It seems *really* unfortunate that we have to call a get mutable method just to iterate through const systems. Given the `DiagramBuilder` API, it's clear there's no other ready resolution. (A `GetSystems()` would look much like the mutable version, much to my dissatisfaction.) To help alleviate future confusion, perhaps a note explaining invocation of mutable and assignment to const?

---

*[drake/systems/primitives/random_source.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSflFUcB4gqBcrRMA9:-KvSflFUcB4gqBcrRMAA:b2fxoj1) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.cc#L21)):*
> ```cpp
>       // Check if the input is already wired up.
>       PortIdentifier id{port.get_system(), port.get_index()};
>       if (builder->dependency_graph_.find(id) !=
> ```

FYI @jwnimmer-tri is an advocate of `builder->dependency_graph_.count(id) > 0` as an alternative, arguably more readable form.

---

*[drake/systems/primitives/random_source.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSgIBnj6bcVhaBmvh-:-KvSgIBnj6bcVhaBmvh0:b-jz4k9u) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.cc#L30)):*
> ```cpp
>       switch (port.get_random_type().value()) {
>         case RandomDistribution::kUniform: {
>           const auto uniform = builder->AddSystem<UniformRandomSource>(
> ```

BTW I'd also advocate `const auto*` on these  as well. (And in the test.)

---

*[drake/systems/primitives/random_source.cc, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSw1k5KWIbP6brkpI9:-KvSw1k6nqvI4sNpYV9X:b1q8kkq) ([raw file](https://github.com/robotlocomotion/drake/blob/471330ce21eef5ada4f95c82c499f9d9d449f722/drake/systems/primitives/random_source.cc#L9)):*
> ```cpp
> template<typename Generator>
> typename Generator::result_type generate_unique_seed() {
>   static typename Generator::result_type seed = Generator::default_seed;
> ```

BTW Probably should use `never_destroyed` for this static field.

---

*[drake/systems/primitives/random_source.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSQ3yjwj4T8tQn7hew:-KvSQ3yjwj4T8tQn7hex:b15mxpf) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L73)):*
> ```objc
> 
>   /// Initializes the random number generator.  This must be set before
>   /// the (abstract) state is allocated to take effect.
> ```

BTW Might be worth enforcing this (via an internal flag that detects when `AllocateAbstractState()` is called).

---

*[drake/systems/primitives/random_source.h, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSROhkB8lQZrgvSWA-:-KvSROhkB8lQZrgvSWA0:bs5g90o) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L83)):*
> ```objc
>       State<double>* state) const override {
>     unused(context);
>     unused(events);
> ```

You can remove the dependency on `unused` (the `#include`, in the `BUILD` file, and here) by eliminating the names of the unused parameters.

---

*[drake/systems/primitives/random_source.h, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSRf1Ip4nfwY9lTI_Q:-KvSRf1Ip4nfwY9lTI_R:b-xfsgw1) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L128)):*
> ```objc
> /// For each subsystem input port in @p builder that is (a) not yet connected
> /// and (b) labeled as random in the InputPortDescriptor, this method will Add a
> /// new RandomSource system of the appropriate type and Connect it to the
> ```

FYI "Add" and "Connect" references feel like "neither-one-thing-nor-the-other". If you're referring to the method, a trailing `()` would help make that clear, otherwise lower-case. It's convenient short-hand, but I don't know that it's stylistically consistent with Drake's documentation. I also suspect that doxygen won't be able to link these names to the appropriate method as is.

---

*[drake/systems/primitives/test/random_source_test.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSuckC0NGi3-GyJgBb:-KvSuckC0NGi3-GyJgBc:brjke0f) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/test/random_source_test.cc#L130)):*
> ```cpp
> };
> 
> GTEST_TEST(RandomSourceTest, AddToDiagramBuilderTest) {
> ```

FYI This test would be more easily consumable with some rockin' ascii art illustrating the diagram.

---

*[drake/systems/primitives/test/random_source_test.cc, line 154 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSuBjrLV2V4CamXadv:-KvSuBjrLV2V4CamXadw:b-dj0z10) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/test/random_source_test.cc#L154)):*
> ```cpp
>   auto context = diagram->CreateDefaultContext();
> 
>   // Check that new Uniform source was created properly.
> ```

BTW Meta: this confirms the input port is connected, it doesn't confirm type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-:-KvSx3Z8PYZf1FiuVBJV:b-4a23z6)*

**Comment by RussTedrake** [comment]
the two commits are logically independent (I worked to keep them distinct).  i don't want to curate further...?

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/primitives/random_source.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSWzI6OgqYacW-mRax:-KvUFm-YwiM9YZhdc80d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.cc#L9)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This struck me as a bit odd for two reasons:

1. The type of `const auto` could be made more clear with `const auto*`.
2. It seems *really* unfortunate that we have to call a get mutable method just to iterate through const systems. Given the `DiagramBuilder` API, it's clear there's no other ready resolution. (A `GetSystems()` would look much like the mutable version, much to my dissatisfaction.) To help alleviate future confusion, perhaps a note explaining invocation of mutable and assignment to const?
</blockquote></details>

Done.

---

*[drake/systems/primitives/random_source.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSflFUcB4gqBcrRMA9:-KvUG0LuppPmIRjwpWaf:b-lrrh8u) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.cc#L21)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI @jwnimmer-tri is an advocate of `builder->dependency_graph_.count(id) > 0` as an alternative, arguably more readable form.
</blockquote></details>

love it.  done.

---

*[drake/systems/primitives/random_source.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSgIBnj6bcVhaBmvh-:-KvUG6__KzZmBs-key1m:b-y15bfc) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.cc#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'd also advocate `const auto*` on these  as well. (And in the test.)
</blockquote></details>

Done.  Wow.  Probably a lot of code throughout drake where I could have been doing that.

---

*[drake/systems/primitives/random_source.cc, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSw1k5KWIbP6brkpI9:-KvUF1SrbQf5RPMF79Gw:b-9114pq) ([raw file](https://github.com/robotlocomotion/drake/blob/471330ce21eef5ada4f95c82c499f9d9d449f722/drake/systems/primitives/random_source.cc#L9)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Probably should use `never_destroyed` for this static field.
</blockquote></details>

feels like overkill for an int :) ,  but done.

---

*[drake/systems/primitives/random_source.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSQ3yjwj4T8tQn7hew:-KvUGnr9c_pjwC0o1Ep2:b2n9qyg) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L73)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Might be worth enforcing this (via an internal flag that detects when `AllocateAbstractState()` is called).
</blockquote></details>

i don't think i can?  it is valid to create the system, allocate a context, set the seed, then allocate another context... (this will only impact the last context).

---

*[drake/systems/primitives/random_source.h, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSROhkB8lQZrgvSWA-:-KvUH1IgQFM-cwBTpkGw:blbdlno) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L83)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You can remove the dependency on `unused` (the `#include`, in the `BUILD` file, and here) by eliminating the names of the unused parameters.
</blockquote></details>

I did not know that.  but why not do that always, then?  is this unused form more clear?

---

*[drake/systems/primitives/random_source.h, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSRf1Ip4nfwY9lTI_Q:-KvUHcKQV8MtuA23_3Pp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L128)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI "Add" and "Connect" references feel like "neither-one-thing-nor-the-other". If you're referring to the method, a trailing `()` would help make that clear, otherwise lower-case. It's convenient short-hand, but I don't know that it's stylistically consistent with Drake's documentation. I also suspect that doxygen won't be able to link these names to the appropriate method as is.
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/random_source_test.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSuckC0NGi3-GyJgBb:-KvUHe8ama1hp4Wi-PmQ:buii5ly) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/test/random_source_test.cc#L130)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI This test would be more easily consumable with some rockin' ascii art illustrating the diagram.
</blockquote></details>

is there a recommended tool for it?

---

*[drake/systems/primitives/test/random_source_test.cc, line 154 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSuBjrLV2V4CamXadv:-KvUI7ztQTQNW3OAJLPM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/test/random_source_test.cc#L154)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Meta: this confirms the input port is connected, it doesn't confirm type.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-:-KvUDIzQXUF0jkhC98qb:byw2j7d)*

**Comment by sherm1** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/random_source.cc, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSw1k5KWIbP6brkpI9:-KvUU2d83PlqNCk4lHVB:b-rgs8hm) ([raw file](https://github.com/robotlocomotion/drake/blob/471330ce21eef5ada4f95c82c499f9d9d449f722/drake/systems/primitives/random_source.cc#L9)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

feels like overkill for an int :) ,  but done.
</blockquote></details>

FYI per [styleguide](https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables) you don't have to use `never_destroyed` for a POD object (no destructor to worry about). Not obvious from the code that `Generator::result_type` is a POD, but if it is you could add a comment promising that and skip the `never_destroyed`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149)*

**Comment by sherm1** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/random_source.h, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSROhkB8lQZrgvSWA-:-KvUUjeeSAtsZsC-hEij:b-349tt0) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L83)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I did not know that.  but why not do that always, then?  is this unused form more clear?
</blockquote></details>

FYI the names are part of the doxygen documentation so are needed for public and protected method signatures. Since this method is private prefer just to nuke the argument names.

FYI2 `unused` takes a list so you could write `unused(context, events)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149)*

**Comment by RussTedrake** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/random_source.h, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSROhkB8lQZrgvSWA-:-KvUml-Qyc-kIZZmSrP2:b-rmx70l) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L83)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI the names are part of the doxygen documentation so are needed for public and protected method signatures. Since this method is private prefer just to nuke the argument names.

FYI2 `unused` takes a list so you could write `unused(context, events)`.
</blockquote></details>

TIL.

Done.  (will push after the next round from Sean, just to conserve build server cycles).  

Bonus question: Why did gcc not complain about it before this PR, but started complaining as soon as there was a non-trivial random_source.cc ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149)*

**Comment by SeanCurtis-TRI** [comment]
-(status: curate commits before merging) Sounds good -- it wasn't 100% clear to me that such was the case (re: curating). 

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/random_source.cc, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSw1k5KWIbP6brkpI9:-KvXQ0FBekVkBwO6Hew3:b3m4rpi) ([raw file](https://github.com/robotlocomotion/drake/blob/471330ce21eef5ada4f95c82c499f9d9d449f722/drake/systems/primitives/random_source.cc#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI per [styleguide](https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables) you don't have to use `never_destroyed` for a POD object (no destructor to worry about). Not obvious from the code that `Generator::result_type` is a POD, but if it is you could add a comment promising that and skip the `never_destroyed`. 
</blockquote></details>

FYI I felt the same; but I found a case where it was used and inferred from example.

---

*[drake/systems/primitives/random_source.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSQ3yjwj4T8tQn7hew:-KvXQIYcsh1Oc2iqml8L:bz8dxg2) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L73)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i don't think i can?  it is valid to create the system, allocate a context, set the seed, then allocate another context... (this will only impact the last context).
</blockquote></details>

Right. As I re-read the comment, I realize my first pass was a misinterpretation. There's nothing here to be enforced, *per se*. Merely user instructions. I'm satisfied.

---

*[drake/systems/primitives/random_source.h, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSROhkB8lQZrgvSWA-:-KvXSFqyh0RbcKd7Yvnk:be84a91) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/random_source.h#L83)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

TIL.

Done.  (will push after the next round from Sean, just to conserve build server cycles).  

Bonus question: Why did gcc not complain about it before this PR, but started complaining as soon as there was a non-trivial random_source.cc ?
</blockquote></details>

Buggered if I know.

---

*[drake/systems/primitives/test/random_source_test.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSuckC0NGi3-GyJgBb:-KvXQtziw8xUMhdFXH3H:b-tniwi7) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/test/random_source_test.cc#L130)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

is there a recommended tool for it?
</blockquote></details>

FYI I've been known to use: http://asciiflow.com/. You can see the fruits of my labors at https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/test/diagram_builder_test.cc#L84
It's definitely optional but it does amazing things for communicating the test.

---

*[drake/systems/primitives/test/random_source_test.cc, line 152 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvXRLj_cAEfFu7Kv0CU:-KvXRLj_cAEfFu7Kv0CV:b4vb91e) ([raw file](https://github.com/robotlocomotion/drake/blob/55c393667dfd5e7316d293dcad62c10804d5a4bb/drake/systems/primitives/test/random_source_test.cc#L152)):*
> ```cpp
>   EXPECT_EQ(AddRandomInputs(1e-3, &builder), 3);
> 
>   const auto diagram = builder.Build();
> ```

FYI If I were to be particularly pedantic, I'd note that you `const`'d this, but left off the `*`. I guess that means I *am* being pedantic. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-:-KvXSZnCBZX1cNhp-B0w:bbtojsw)*

**Comment by RussTedrake** [comment]
+@ggould-tri for platform review, please.

---

Review status: 1 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/primitives/test/random_source_test.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSuckC0NGi3-GyJgBb:-Kvb5g5a-MMyQNpKFJaC:bn03et8) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/test/random_source_test.cc#L130)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I've been known to use: http://asciiflow.com/. You can see the fruits of my labors at https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/test/diagram_builder_test.cc#L84
It's definitely optional but it does amazing things for communicating the test.
</blockquote></details>

Done.  Also added a link to asciiflow in sphinx.

---

*[drake/systems/primitives/test/random_source_test.cc, line 152 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvXRLj_cAEfFu7Kv0CU:-Kvb1pOVz4_DNU2qk_uM:b8gy06p) ([raw file](https://github.com/robotlocomotion/drake/blob/55c393667dfd5e7316d293dcad62c10804d5a4bb/drake/systems/primitives/test/random_source_test.cc#L152)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI If I were to be particularly pedantic, I'd note that you `const`'d this, but left off the `*`. I guess that means I *am* being pedantic. :)
</blockquote></details>

sorry -- Build() returns a unique_ptr.  it's const auto, not const auto*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-:-Kvb5rMZGL38D4CO526C:bcav8r0)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 4 of 4 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-:-KvbfTULfBdE6L4TPE6c:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 5 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/primitives/random_source.cc, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSw1k5KWIbP6brkpI9:-KvbiHucm6QEWiW2Z7TQ:bjd7ntl) ([raw file](https://github.com/robotlocomotion/drake/blob/471330ce21eef5ada4f95c82c499f9d9d449f722/drake/systems/primitives/random_source.cc#L9)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I felt the same; but I found a case where it was used and inferred from example.
</blockquote></details>

@sherm1 This isn't my fault this time; but somehow it seems you're blocking again.

---

*[drake/systems/primitives/test/random_source_test.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvSuckC0NGi3-GyJgBb:-Kvbi_dH_Hj4IFHol7Ht:b-acyj90) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef54400a6b62915e8f4701e9731840c6f2e4f61/drake/systems/primitives/test/random_source_test.cc#L130)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  Also added a link to asciiflow in sphinx.
</blockquote></details>

Beautiful

---

*[drake/systems/primitives/test/random_source_test.cc, line 152 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7149#-KvXRLj_cAEfFu7Kv0CU:-KvbibMMHNorjIZeTVnn:bg3lh97) ([raw file](https://github.com/robotlocomotion/drake/blob/55c393667dfd5e7316d293dcad62c10804d5a4bb/drake/systems/primitives/test/random_source_test.cc#L152)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

sorry -- Build() returns a unique_ptr.  it's const auto, not const auto*
</blockquote></details>

What can I say, but 'D'oh'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7149)*

**Pull request merged**
