### PR TITLE
Use shards for multilane_road_curve_accuracy_test.

### PR DESCRIPTION
**Pull request by avalenzu**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8880)

### CODE REVIEW

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8880#-:-LDMgR-O91JyaK3yPfFw:b82xwss)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8880#-:-LDMgbX1-IbNdf8n0CD9:bnfp4nl)*

**Comment by avalenzu** [comment]
+@sherm1 for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8880#-:-LDMi5YwC-ocW9-PfAU-:bfvx2sg)*

**Comment by soonho-tri** [comment]
Given the `priority:emergency`, please allow me to do the platform-review, :lgtm: 

-@sherm1 
+@soonho-tri 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8880#-:-LDMmo1A5OpIrEPyXFSb:bo7sxf4)*

**Comment by soonho-tri** [comment]
All Passed.

**Pull request merged**
