### PR TITLE
Remove many MATLAB-only examples

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The full list is:
- Airplane2D
- CartPole
- CompassGait
- DubinsCar
- Glider
- HolonomicDrive
- PlanarMonopodHopper
- PlanarNLink
- RimlessWheel
- SimpleDoublePendulum
- SimplePulleys
- SpringLoadedInvertedPendulum
- Strandbeest
- TwoWheeledInvertedPendulum
- Wingeron
- grasping

These do not have any matching C++ code yet, so we are not keeping the data files on master; they will be easy to retrieve from git if and when we want them.

Relates #6369.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6268)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I'll need to make sure CI passes first.
+(status: do not review)
+(status: do not merge)

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please. I'll wait to assign feature / platform review until after that.

**Comment by jwnimmer-tri** [comment]
In #6243, @rdeits suggested:
> ... readme in the relevant deleted example folders, just so that things a new user might do (like a github repo search for "quadrotor" or just browsing to the examples folder) will still point them to the right SHA.

I'll do that for `examples/Quadrotor/README`, which will retain a folder under `drake/examples/` anyway so it's an obvious win.

I wonder if we can find a good way to do that with other examples who might not otherwise have any directory staying around, as in this PR.  Maybe they should just hang around with _only_ a README?  Maybe there should be `examples/README` with an itemized list of fully-removed folders and background story?

For the record, we already have a http://drake.mit.edu/matlab_bindings.html#original-matlab citation in general, and #6273 changes the gallery to use the tag.

I'm open to suggestions.

**Comment by jwnimmer-tri** [comment]
In #6305, I've placed an examples-wide README that covers this PR's removals.

**Comment by RussTedrake** [comment]
:lgtm:  lots of good examples here that should be ported.  but this is the right thing to do.

---

Review status: 0 of 226 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6268#-:-KmQl-FoR3iMK6MAcjrw:b-hmvvz9)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge) 
+@soonho-tri for all review, please.  (I'm manually cycling the MATLAB PRs through platform review, off-schedule.)

---

Review status: 0 of 226 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6268#-:-KmRYjA4qwhLCcpDwEua:b988208)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 226 of 226 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6268#-:-KmnJs9nuxyoGHZy913J:bnfp4nl)*

**Pull request merged**
