### PR TITLE
[py containers] Add nuance on `np.asarray()` for namedview

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relating #18809

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@RussTedrake for feature review, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831#-:-NOl76Bn5NPtFwtafgGR:b-cb1jfb)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18831#-NOl74wr0Jyanj4LXjoM:-NOl74wr0Jyanj4LXjoN:bvd7g62) (no related file):*
Working: Confirming doc preview.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18831#-NOl74wr0Jyanj4LXjoM:-NOl7z6P4qvHHg64XOHy:br0e777) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Confirming doc preview.
</blockquote></details>

Working: Will rescope this to focus on `np.[as]array` docs only, and leave formatting changes to #18825

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18831#-NOl74wr0Jyanj4LXjoM:-NOl8nnt6WhtO9Z68fkG:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will rescope this to focus on `np.[as]array` docs only, and leave formatting changes to #18825
</blockquote></details>

Done.

___

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  nice!  thanks!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831#-:-NOl9cZc1Vwxz9yIBrLI:brl1gmd)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18831#-NOl74wr0Jyanj4LXjoM:-NOlDzFJ8A2nLnd5Wr5v:b-wd0zq7) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI 18825 has merged.

___

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831#-:-NOlEzWk-KQXQk6WXyow:b-ruv0ff)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18831#-NOl74wr0Jyanj4LXjoM:-NOlFjqb7KdlvQFwdUQd:bn47c4j) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI 18825 has merged.
</blockquote></details>

Rebased and fixed up rendering, thanks!

___

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

+(release notes: none) for docs/test-only change.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831#-:-NOlGF-j7pK4BsNmHrj2:b-b1nzk9)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18831)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
