### PR TITLE
[geometry] Add MeshcatParams option for initial_properties

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20927.

This works with Python YAML loading, but not yet C++ YAML loading.  C++ loading support will appear in a follow-up.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20920)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20920)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20920#-:-NqTOmUj7tIMgFAe0mqy:b-gpqagm)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With documentation elaboration request.

+@rpoyner-tri for out of band platform review, please.

> Reviewed 3 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20920#-:-NqTQ44IDBD2LUJaI-WP:b1ksvii)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/meshcat_params.h` line 70 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20920#-NqTP0Qh4tNlNzCUhaRg:-NqTP0Qh4tNlNzCUhaRh:b-vbjbn8) ([raw file](https://github.com/RobotLocomotion/drake/blob/aef09f94c24f408b369f8544e9779be995927734/geometry/meshcat_params.h#L70)):*
> ```objc
>   };
> 
>   /** Configures the initial conditions for Meshcat. These properties will be
> ```

nit: I suspect this documentation needs to offer more. It seems that the average user is not one who has looked at either `meshcat` or `drake::...::Meshcat` so, understanding the semantics of this particular set of fields may be overly opaque.

Ideally a cross reference to "setting properties for meshcat" would be best. But, for now, I suspect people won't even have a hint of how they would successfully use this.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20920)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/meshcat_params.h` line 70 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20920#-NqTP0Qh4tNlNzCUhaRg:-NqTV7ee1GpZ-0cQRiuI:b-endaq4) ([raw file](https://github.com/RobotLocomotion/drake/blob/aef09f94c24f408b369f8544e9779be995927734/geometry/meshcat_params.h#L70)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I suspect this documentation needs to offer more. It seems that the average user is not one who has looked at either `meshcat` or `drake::...::Meshcat` so, understanding the semantics of this particular set of fields may be overly opaque.

Ideally a cross reference to "setting properties for meshcat" would be best. But, for now, I suspect people won't even have a hint of how they would successfully use this.
</blockquote></details>

I added more words.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20920)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/meshcat_params.h` line 70 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20920#-NqTP0Qh4tNlNzCUhaRg:-NqThqGtBkFUktPbAsJN:b-3a8fv3) ([raw file](https://github.com/RobotLocomotion/drake/blob/aef09f94c24f408b369f8544e9779be995927734/geometry/meshcat_params.h#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I added more words.
</blockquote></details>

I like the change - it tightens Drake's meshcat ecosystem, but it doesn't quite touch the heart of my concern. But I realized that the heart of my concern belongs outside this PR. As ever, how does a user discover what a meaningful *tuple* would be?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20920)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20920#-:-NqYV3hsADTlrmLXQAZt:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
