### PR TITLE
[workspace] Build yaml-cpp from source

### LINKED ISSUE #15868: Remove yaml-cpp as public dependency
In #7451 and #15815 we discuss the public header file dependencies of Drake.  In general, it's to our advantage to keep our public header footprint small, to maximize compatibility with our users who might want to use different version of those dependencies (e.g., #1183 or #14967).  For most libraries we depend on, we should build them with private symbols that only we can see, so that downstream users can build their own, different version if they need to.

For vocabulary types like Eigen, it's appropriate to have a public dependency.  However, for yaml-cpp, we mostly only use it for parsing, not as an abstract syntax tree (AST), so there is no great reason why it's currently a public dependency.  Furthermore, it is a C++ library and does not try to handle ABI compatibility carefully, so has a somewhat higher chance of causing trouble than other, simpler libraries.  (It's upstream maintainer is also no longer very active, and is seeking volunteers to take over.)

We should implement a minimal AST on our own that we can code against (in both our h and cc files), and only rely on yaml-cpp for it's parsing front-end, private to our cc files.

This will also enable us to easily pull in newer revisions of yaml-cpp with parser fixes.  As it stands now, because it's a public dependency, we are stuck being pinned to the Ubuntu version.

Relatedly, it's AST uses a confusing form of value syntax that actually has mutable reference semantics, so the readability of our code that's written against that API is a constant struggle.  Using our own AST will be an improvement on that front as well.

- [x] #15865
  - [x] #15910
  - [x] #15934
    - [x] #15940
  - [x] #15894 
- [x] #15866
- [x] #15867
  - [x] #15890
- [x] #16000
- [x] #15902
- [x] Port all of Drake to the new sugar
  - [x] #15998
  - [x] #16049
  - [x] #16050
- [x] Port all of Anzu to the new sugar
  - [x] #16059
  - [ ] Add option to specify ignored keys.
- [x] #16083
- [x] #16057
- [x] The "Archive" classes are all marked "Advanced".  Should they just be internal, instead? => deferred to #16706.
- [x] After the deprecations die on 2022-03-01, make the dependency actually private:
   - [x] #16701 Remove yaml-cpp from `drake-config.cmake` and the related installation infrastructure.
   - [x] #16701 Switch yaml-cpp to build from source with hidden symbols and upgrade to the latest tagged source release, and remove our one vendored upstream file from Drake.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #15868.

Upgrade to use 0.7.0 on all platforms.

This will enable us to patch some I/O bugs, down the road:

https://github.com/RobotLocomotion/drake/blob/06e1deb12539f05eff968c5bd9e11d259916f268/common/yaml/yaml_write_archive.h#L275-L282

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16701)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please?  My goal for this low-priority review would be by next Tuesday.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  +@ggould-tri for platform review per rotation

> Reviewed 16 of 17 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16701#-:-MxGgVTWDAwjQP2g5z9B:b3380xd)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 16 of 17 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16701#-:-MxZjcyW7mFxZ77c4Tlx:bnfp4nl)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[tools/workspace/yaml_cpp/emit-local-tag.patch, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16701#-MxZkNph60ZLZl4EFloU:-MxZkNph60ZLZl4EFloV:bvxzdu4) ([raw file](https://github.com/robotlocomotion/drake/blob/7e27f11223aef45273b08882f5f728bcfba6c498/tools/workspace/yaml_cpp/emit-local-tag.patch#L17)):*
> ```Diff
> -  if (!tag.empty() && tag != "?" && tag != "!")
> -    m_emitter << VerbatimTag(tag);
> +  if (!tag.empty() && tag != "?" && tag != "!") {
> ```

nit:  Inconsistent brace style with the rest of this file.
Author's discretion but I'd opt for consistency with the third-party underlay.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-documentation please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-snopt-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16701)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16701#-MxFfYwnBeA5tjPMQpkc:-MxZvEQHDtBrpTs_gMyA:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

After fixes from the first review pass, I need to re-run a bunch of non-default CI builds.
</blockquote></details>

Done.

---

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Pull request merged**
