### PR TITLE
[py sensors] Bind all image types

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20447.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20502)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for both reviews per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20502#-:-NikdqhS2DWhEMV4s_iA:byjyn3d)* status: LGTM missing from assignee sherm1(platform)

___
*[`bindings/pydrake/systems/test/sensors_test.py` line 352 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20502#-Nikdc1HC9C7Yyt7f9PO:-Nikdc1HC9C7Yyt7f9PP:bhpvkiv) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd7e485e273b7adba240f4b62ebcd4284a3a9c3c/bindings/pydrake/systems/test/sensors_test.py#L352)):*
> ```Python
>                     pt.kDepth32F: lcmt_image.PIXEL_FORMAT_DEPTH,
>                     pt.kLabel16I: lcmt_image.PIXEL_FORMAT_LABEL,
>                     pt.kGrey8U: lcmt_image.PIXEL_FORMAT_GRAY,
> ```

FYI yay https://www.grammarly.com/blog/gray-grey/

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20502)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform)

___
*[`bindings/pydrake/systems/sensors_py_image.cc` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20502#-NikhnFi2CNt_q7eSaVW:-NikhnFi2CNt_q7eSaVX:bvnn6o7) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd7e485e273b7adba240f4b62ebcd4284a3a9c3c/bindings/pydrake/systems/sensors_py_image.cc#L24)):*
> ```cpp
>   // `__str__` that looks more Pythonic than our C++ `to_string`.
> 
>   // Expose only types that are used.
> ```

Working

Oops, possibly I need to fix this spot also?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20502)* status: LGTM missing from assignee sherm1(platform)

___
*[`bindings/pydrake/systems/sensors_py_image.cc` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20502#-NikhnFi2CNt_q7eSaVW:-Nikjnkv9ecNbGk0Osmw:b-3ebzpn) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd7e485e273b7adba240f4b62ebcd4284a3a9c3c/bindings/pydrake/systems/sensors_py_image.cc#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Oops, possibly I need to fix this spot also?
</blockquote></details>

Done.  Yup, the documentation was missing information until I added the missing items here.  Unit test added as well, now.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 with one ignorable suggestion

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20502#-:-NikvNPdCxYE3tCGd17e:b-ck4afu)* status: 1 unresolved discussion

___
*[`bindings/pydrake/systems/sensors_py_image.cc` line 31 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20502#-NikuEuQ4UoQRutv0PWD:-NikuEuQ4UoQRutv0PWE:b-dv2rah) ([raw file](https://github.com/RobotLocomotion/drake/blob/777f6dc4813ca7bca72355a43e6d79af219c1729/bindings/pydrake/systems/sensors_py_image.cc#L31)):*
> ```cpp
>       .value("kGrey", PixelFormat::kGrey)
>       .value("kDepth", PixelFormat::kDepth)
>       .value("kLabel", PixelFormat::kLabel);
> ```

BTW not sure if there is significance to this ordering. If not, consider using the same ordering you used elsewhere: Rgba, Rgb, Bgra, Bgr, Depth, Label, Grey.
___
*[`bindings/pydrake/systems/test/sensors_test.py` line 352 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20502#-Nikdc1HC9C7Yyt7f9PO:-Nikv1juCi4JC4Inv3jE:b-8l93n3) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd7e485e273b7adba240f4b62ebcd4284a3a9c3c/bindings/pydrake/systems/test/sensors_test.py#L352)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI yay https://www.grammarly.com/blog/gray-grey/
</blockquote></details>

Yeah, should be the American spelling everywhere :(

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20502)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

___
*[`bindings/pydrake/systems/sensors_py_image.cc` line 31 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20502#-NikuEuQ4UoQRutv0PWD:-NikzKhc2v36rK8BmUOb:b-1gxa0k) ([raw file](https://github.com/RobotLocomotion/drake/blob/777f6dc4813ca7bca72355a43e6d79af219c1729/bindings/pydrake/systems/sensors_py_image.cc#L31)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW not sure if there is significance to this ordering. If not, consider using the same ordering you used elsewhere: Rgba, Rgb, Bgra, Bgr, Depth, Label, Grey.
</blockquote></details>

This listing already matches the order of the `PixelFormat` enum items in the C++ header, as is typical for writing out bindings.

It's the other one which is the oddball (in the sensors_py.h).  That one has real effects (templated bindings in the docs match its order) so there we keep the most common and useful type (Rgba8U) as the first one.

**Pull request merged**
