### PR TITLE
Start to use SystemScalarConverter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Individual commits are curated and have more detailed messages.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6684)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@sherm1 I think you get first right of refusal on feature review. Let me know if you'd like to do a full feature pass, or do only high-level comments, or skip this PR entirely.

**Comment by sherm1** [comment]
Thanks, Jeremy! +@sherm1 for feature review.

---

Reviewed 1 of 11 files at r1.
Review status: 1 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-:-KqPCehN9HQ2Sy6JRiNJ:b-pgxt4l)*

**Comment by sherm1** [comment]
Feature review: :lgtm:, with a few BTWs. PTAL.

---

Reviewed 10 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPJWlTlVqy-3GSEtzJ:-KqPJWlTlVqy-3GSEtzK:bzd6592) ([raw file](https://github.com/robotlocomotion/drake/blob/449059cc433ac60056bd4f736113abfb74065d1c/drake/systems/framework/leaf_system.h#L218)):*
> ```objc
>   /// events, nor scalar-type conversion support (i.e., AutoDiff, etc.).  To
>   /// enable AutoDiff support, either use the constructor that takes a
>   /// SystemTypeTag or call SetSystemScalarConverter() directly.
> ```

BTW currently there is no unit test for option 2 here (direct call to SetSystemScalarConverter()). Unless there is some reason that using the provided constructor wouldn't always work, I would prefer that we provide only One True Way to create these convertible systems and keep the implementation a secret. Then I think SetSystemScalarConverter() could be private. We could always upgrade it later under duress but I think we would be doing users a favor to provide only one option. I much prefer that route to documenting and unit testing option 2.

---

*[drake/systems/framework/leaf_system.h, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPGN_BYUUszY0o4b4A:-KqPGN_BYUUszY0o4b4B:b-fa2oqt) ([raw file](https://github.com/robotlocomotion/drake/blob/449059cc433ac60056bd4f736113abfb74065d1c/drake/systems/framework/leaf_system.h#L235)):*
> ```objc
>   /// for the `S` tag passed to this constructor.  Refer to that method's
>   /// documentation for additional details.
>   template <template <typename> class S>
> ```

BTW should say explicitly that S must be the most-derived concrete System class.

---

*[drake/systems/framework/leaf_system.h, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPG3GiC2pVte4_8tra:-KqPG3GiC2pVte4_8trb:b-ac1234) ([raw file](https://github.com/robotlocomotion/drake/blob/449059cc433ac60056bd4f736113abfb74065d1c/drake/systems/framework/leaf_system.h#L240)):*
> ```objc
>   }
> 
>   /// Declares scalar-type conversion support (for AutoDiff, etc.) based the
> ```

BTW based the -> based on the

---

*[drake/systems/framework/vector_system.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPHcHog-A4QYmyXmlX:-KqPHcHog-A4QYmyXmlY:buxugnh) ([raw file](https://github.com/robotlocomotion/drake/blob/449059cc433ac60056bd4f736113abfb74065d1c/drake/systems/framework/vector_system.h#L95)):*
> ```objc
>   /// AutoDiff or symbolic form.  Subclasses that wish to support conversion to
>   /// other scalar types should either use this constructor or else directly
>   /// call LeafSystem<T>::SetSystemScalarConverter.
> ```

BTW Same comment as above -- I think "use the right constructor" would be sufficient and everyone will be better off if we don't mention the alternate approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-:-KqPKuGO8GKoBXbCKiE-:b-sixlrp)*

**Comment by jwnimmer-tri** [comment]
Good point on `SetSystemScalarConverter`.  In the full Drake port to these APIs, there is only one consumer of that method.  I will see if I can shoehorn it to use the constructor directly -- I agree that would be superior.

**Comment by jwnimmer-tri** [comment]
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPJWlTlVqy-3GSEtzJ:-KqPMO4Z-XMGqnuvCLtQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/449059cc433ac60056bd4f736113abfb74065d1c/drake/systems/framework/leaf_system.h#L218)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW currently there is no unit test for option 2 here (direct call to SetSystemScalarConverter()). Unless there is some reason that using the provided constructor wouldn't always work, I would prefer that we provide only One True Way to create these convertible systems and keep the implementation a secret. Then I think SetSystemScalarConverter() could be private. We could always upgrade it later under duress but I think we would be doing users a favor to provide only one option. I much prefer that route to documenting and unit testing option 2.
</blockquote></details>

Done.

---

*[drake/systems/framework/leaf_system.h, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPGN_BYUUszY0o4b4A:-KqPMlFaL5UcnooSJfsE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/449059cc433ac60056bd4f736113abfb74065d1c/drake/systems/framework/leaf_system.h#L235)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should say explicitly that S must be the most-derived concrete System class.
</blockquote></details>

Done.

---

*[drake/systems/framework/leaf_system.h, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPG3GiC2pVte4_8tra:-KqPMVIS1BEuetyC93wu:b-fzj022) ([raw file](https://github.com/robotlocomotion/drake/blob/449059cc433ac60056bd4f736113abfb74065d1c/drake/systems/framework/leaf_system.h#L240)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW based the -> based on the
</blockquote></details>

Done (removed).

---

*[drake/systems/framework/vector_system.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPHcHog-A4QYmyXmlX:-KqPMXAbY0JbNhWEB2BC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/449059cc433ac60056bd4f736113abfb74065d1c/drake/systems/framework/vector_system.h#L95)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Same comment as above -- I think "use the right constructor" would be sufficient and everyone will be better off if we don't mention the alternate approach.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6684)*

**Comment by sherm1** [comment]
Nice -- one BTW.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/framework/vector_system.h, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPpRGbNiVsCLEl_1sl:-KqPpRGbNiVsCLEl_1sm:b-tadrjc) ([raw file](https://github.com/robotlocomotion/drake/blob/0ee9616ab0bceb00478209204fcba6847a62ea1e/drake/systems/framework/vector_system.h#L90)):*
> ```objc
>   /// AutoDiff or symbolic form.  Subclasses that wish to support conversion to
>   /// other scalar types should either use this constructor or else directly
>   /// call LeafSystem<T>::SetSystemScalarConverter.
> ```

BTW still has a mention of SetSystemScalarConverter() here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-:-KqPpksAaeGC7mdmMeEh:b-s9w1wb)*

**Comment by jwnimmer-tri** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/vector_system.h, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-KqPpRGbNiVsCLEl_1sl:-KqPrw33nMmgn8WL9yQ7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0ee9616ab0bceb00478209204fcba6847a62ea1e/drake/systems/framework/vector_system.h#L90)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW still has a mention of SetSystemScalarConverter() here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6684)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review rotation, please.

---

Review status: 10 of 11 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-:-KqPsKCcITy3JMH92y0_:bb6tnf3)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6684)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 9 of 11 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6684#-:-KqTcRuGIYkkZcVjfZBe:bnfp4nl)*

**Pull request merged**
