### PR TITLE
Remove calling prog solve

### PR DESCRIPTION
**Pull request by hongkai-dai**
As part of the deprecation process mentioned in #9633.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10420)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Ah, oops! Was dragging stuff in ZenHub... apparently, accidentally dropping stuff in `Closed` instead of `In Review` makes an actual change...

**Comment by jwnimmer-tri** [comment]
@hongkai-dai FYI the ergonomics of solvers unit tests will be greatly improved once #10635 is merged.  In resolving the merge conflicts here, perhaps you'd like to limit this PR to just be the changes outside of the solvers folder, to get it in earlier.  I might take over the solvers-folder changes anyway, as part of updating everything to use the new SolverBase class.

**Comment by jwnimmer-tri** [comment]
So #10635 has merged, but I would still advise waiting here until #10672 and another one after that have merged.  In other words, I think I will handle porting `//solvers/...` tests on my own, with some new sugars on the way.

**Comment by jwnimmer-tri** [comment]
FYI I think my interruptions are done; it's probably safe to update this PR now.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai This PR is one of the last two or three things before we pull the deprecation trigger.  Do you have a merge-resolution update pending, or would you like me to resolve the conflicts and push an update here?

**Comment by hongkai-dai** [comment]
No I don't have a commit to resolve the merge conflict. It would be great if you would like to resolve the conflicts. Thanks a lot!

**Comment by jwnimmer-tri** [comment]
I've done a first pass at the merge.  There are still some test failures, and I'll also be sure to look at the overall diffs.  I'll probably push again soon.

**Comment by jwnimmer-tri** [comment]
Ok, I think this should be ready to go now.  @EricCousineau-TRI PTAL.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both reviews please, per schedule (tomorrow).

**Pull request merged**
