### PR TITLE
[Multilane] Adds Builder::Connect to support lane-to-lane Connections

### PR DESCRIPTION
**Pull request by agalbachicar**
This PR is a follow up of #8676 and introduces `Builder::Connect` methods to support lane-to-lane connections.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)

### CODE REVIEW

**Comment by agalbachicar** [comment]
+@maddog-tri for feature review please.

@rpoyner-tri for awareness.

---

Review status: all discussions resolved, platform LGTM missing, labeled "do not merge"

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973#-:-LEpZv2qD4qZMBTz6Q0T:bgb8n8m)*

**Comment by agalbachicar** [comment]
@maddog-tri let me know if you prefer me to target #8676 instead of master to make your life easier.

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973#-:-LEpaB1c5OlQStVEchfk:b-ljz3wh)*

**Comment by rpoyner-tri** [comment]
i started looking yesterday, but didn't get far; various high-prio things landing on my desk. Here's a few comments; still reading.

---

Reviewed 5 of 14 files at r1, 1 of 6 files at r2.
Review status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri, LGTM missing from assignee maddog-tri, platform LGTM missing

---

*[automotive/maliput/multilane/test_utilities/multilane_types_compare.h, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LFSjwM13gdmsHhggTgV:-LFSjwM29JfUqDbgh4O0:b-xcy7ek) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc11d36f0f1625b9df1791fb25c0a718fbcb6a2/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L87)):*
> ```objc
> // @param cubic1 A CubicPolynomial object to compare.
> // @param cubic2 A CubicPolynomial object to compare.
> // @param tolernace An allowable absolute linear deviation for each coefficient.
> ```

typo 'tolernace'

---

*[automotive/maliput/multilane/test_utilities/multilane_types_compare.cc, line 237 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LFSv1a1DhNpUIOlVlny:-LFSv1a1DhNpUIOlVlnz:b-ui38jj) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc11d36f0f1625b9df1791fb25c0a718fbcb6a2/automotive/maliput/multilane/test_utilities/multilane_types_compare.cc#L237)):*
> ```cpp
>                     ", diff = " + std::to_string(delta) +
>                     ", tolerance = " + std::to_string(tolerance) + "\n";
>   }
> ```

BTW, The 4 stanzas above look like a lot of copy/paste that could be made more concise. I see that is similar in structure to other parts of the file; perhaps an even broader refactoring could be done?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973#-:-LFXlR041X3UgKVrTOPn:bbmsb2h)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 14 files at r1.
Review status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri, LGTM missing from assignee maddog-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 14 files at r1, 4 of 6 files at r2.
Review status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri, LGTM missing from assignee maddog-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Comment by agalbachicar** [comment]
Thanks for your comments and sorry for the delay. Comments were addressed, PTAL.

---

Review status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri, LGTM missing from assignee maddog-tri, platform LGTM missing

---

*[automotive/maliput/multilane/builder.h, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LF1ETX82eKkWdbIQNTV:-LG7JpvaEFQBpDjC6LGe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/508f991c1e10979e2d00de229c45fd6c48957eeb/automotive/maliput/multilane/builder.h#L124)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

I think that this needs to assert that the theta_dot of endpoint is nullopt.  Same for the corresponding EndLane::z_at().

I'm pretty sure that specifying the pose of a lane endpoint only works out if theta_dot is set to the magic value.  In other words:  the magic theta_dot value ensures that the surface orientation is invariant to `r`, so that is the only value that allows one to simply translate the endpoint pose along the r-axis.
</blockquote></details>

Done.

---

*[automotive/maliput/multilane/builder.h, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LF1FYnZDzEA_SYou5_t:-LG7K9ozEatHw9ww9gS7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/508f991c1e10979e2d00de229c45fd6c48957eeb/automotive/maliput/multilane/builder.h#L141)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

I think this needs to unset the theta_dot, like its StartReference.at() counterpart does.  Same for the similar EndLane::z_at().
</blockquote></details>

Done.

---

*[automotive/maliput/multilane/test_utilities/multilane_types_compare.h, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LFSjwM13gdmsHhggTgV:-LG7KM1mDGz_sUeEDR06:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc11d36f0f1625b9df1791fb25c0a718fbcb6a2/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L87)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo 'tolernace'
</blockquote></details>

Done.

---

*[automotive/maliput/multilane/connection.h, line 287 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LF1L-Ef2A0LwxOrXi3S:-LG7KOlD2rM6Uvdvf7E3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/508f991c1e10979e2d00de229c45fd6c48957eeb/automotive/maliput/multilane/connection.h#L287)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

I think the code will be more straightforward (and have less duplicated math) if these two new Connection constructors are eliminated, and Connections are only constructed based on the parameters of their reference-curve endpoints.

The relevant math from the new constructors (that figures out the reference-curve params from the lane-based params) would instead go into the corresponding Builder::Connect() methods.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973#-:-LG7L0aPC3qaQEkNpv44:b-d6n2hm)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 8 files at r3.
Review status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri, LGTM missing from assignee maddog-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r3.
Review status: 3 unresolved discussions, LGTM missing from assignee maddog-tri, platform LGTM missing

---

*[automotive/maliput/multilane/builder.h, line 129 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LGQL8O06r4cJWqtF8lH:-LGQL8O14L4EnmsT7AN6:bp13sww) ([raw file](https://github.com/robotlocomotion/drake/blob/cab7f1f8370d32ded4413fccd1949d7096725888/automotive/maliput/multilane/builder.h#L129)):*
> ```objc
>     return direction == Direction::kForward
>                ? Spec(endpoint, start_lane_)
>                : Spec(endpoint.reverse(), start_lane_);
> ```

BTW, the only hole I saw in test coverage was for exercising the Direction::kReverse parameter value. I think you have a TODO somewhere that kind-of covers that for future maintainers?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973#-:-LGQL2bv2P_oEu0bmxNt:bnfp4nl)*

**Comment by agalbachicar** [comment]
*[automotive/maliput/multilane/builder.h, line 129 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LGQL8O06r4cJWqtF8lH:-LGQNtLP7BqZdinpRSww:b-i4eyvq) ([raw file](https://github.com/robotlocomotion/drake/blob/cab7f1f8370d32ded4413fccd1949d7096725888/automotive/maliput/multilane/builder.h#L129)):*
> test coverage was for exercising the Direction::kReverse parameter value. I think you have a TODO somewhere that kind-of covers that for future maintainers
Yes, it's here --> https://github.com/RobotLocomotion/drake/blob/master/automotive/maliput/multilane/test/multilane_builder_test.cc#L24

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Comment by agalbachicar** [comment]
Thanks for your time @rpoyner-tri !

+@jwnimmer-tri for platform review please.

---

Review status: 3 unresolved discussions, LGTM missing from assignee maddog-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973#-:-LGQOTj0DkIKclkaieR3:bg0tsl7)*

**Comment by jwnimmer-tri** [comment]
FYI The `fmt` library used in Drake's logging (and more) is very good at string formatting.  In future PRs, it might be worth investigating it; https://github.com/fmtlib/fmt/.

:lgtm: I did my best, but this code is incredibly verbose and the PR is large, so I mostly only skimmed it for style errors.

---

Reviewed 5 of 14 files at r1, 7 of 8 files at r3.
Review status: 4 unresolved discussions, LGTM missing from assignee maddog-tri, platform LGTM from [jwnimmer-tri]

---

*[automotive/maliput/multilane/builder.cc, line 163 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LGR8jPPEAxQIn5Ie0_-:-LGR8jPPEAxQIn5Ie0_0:b-kmfpz0) ([raw file](https://github.com/robotlocomotion/drake/blob/cab7f1f8370d32ded4413fccd1949d7096725888/automotive/maliput/multilane/builder.cc#L163)):*
> ```cpp
>       -lane_layout.ref_r0() +
>       lane_width_ *
>           static_cast<double>(start_spec.lane_id() - lane_layout.ref_lane());
> ```

FYI for int-to-double promotion, I believe `double{my_int_value}` is best, because its shorter, and the compiler checks the domain.  No defect.

---

*[automotive/maliput/multilane/test/multilane_builder_test.cc, line 770 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LGR9Tpx1oA6nGFPKv2s:-LGR9Tpx1oA6nGFPKv2t:b-67r023) ([raw file](https://github.com/robotlocomotion/drake/blob/cab7f1f8370d32ded4413fccd1949d7096725888/automotive/maliput/multilane/test/multilane_builder_test.cc#L770)):*
> ```cpp
>   const EndpointZ kElevatedZ{5., 1., 0., {}};
>   const double kStartHeading{-M_PI / 4.};
>   const Endpoint start{{0., 0., kStartHeading}, kLowFlatZ};
> ```

FYI Surprising that its not `kStart` here, for consistency.

---

*[automotive/maliput/multilane/test_utilities/multilane_types_compare.cc, line 199 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LGR5Hfh94PmUpffFDtZ:-LGR5Hfh94PmUpffFDt_:b-r45cp2) ([raw file](https://github.com/robotlocomotion/drake/blob/cab7f1f8370d32ded4413fccd1949d7096725888/automotive/maliput/multilane/test_utilities/multilane_types_compare.cc#L199)):*
> ```cpp
>   bool fails = false;
>   std::string error_message{};
>   static const std::vector<std::string> coefficient_strs{"a", "b", "c", "d"};
> ```

This violates http://drake.mit.edu/styleguide/cppguide.html#Static_and_Global_Variables.  The best answer is probably just to drop the `static`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973#-:-LGR7G5YBQICdErWMUQ1:b7cw5hv)*

**Comment by agalbachicar** [comment]
*[automotive/maliput/multilane/builder.cc, line 163 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LGR8jPPEAxQIn5Ie0_-:-LGRHOCS7L_z2espdfaT:b-1q9kur) ([raw file](https://github.com/robotlocomotion/drake/blob/cab7f1f8370d32ded4413fccd1949d7096725888/automotive/maliput/multilane/builder.cc#L163)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI for int-to-double promotion, I believe `double{my_int_value}` is best, because its shorter, and the compiler checks the domain.  No defect.
</blockquote></details>

When using `double{my_int_value}` clang complains because of `-Wc++11-narrowing` and does not allow me to compile it. If I use `double(my_int_value)` cpplint complains about it too because it's a C-cast.

Do you think it's worth using another variable for this or shall I keep it as it is? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Comment by jwnimmer-tri** [comment]
*[automotive/maliput/multilane/builder.cc, line 163 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LGR8jPPEAxQIn5Ie0_-:-LGRL5KKDSrd1IPnRSan:by9q5ws) ([raw file](https://github.com/robotlocomotion/drake/blob/cab7f1f8370d32ded4413fccd1949d7096725888/automotive/maliput/multilane/builder.cc#L163)):*
<details><summary><i>Previously, agalbachicar (Agustin Alba Chicar) wrote…</i></summary><blockquote>

When using `double{my_int_value}` clang complains because of `-Wc++11-narrowing` and does not allow me to compile it. If I use `double(my_int_value)` cpplint complains about it too because it's a C-cast.

Do you think it's worth using another variable for this or shall I keep it as it is? 
</blockquote></details>

OK This is fine.  I don't know why the narrowing warning applies for int-to-double, but since brevity a goal, I don't think changing it makes sense anymore.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Comment by agalbachicar** [comment]
Thanks for the FYI, there's an issue already open for that --> #8530 . We are focusing on getting all the PRs that add core functionality to multilane and then will do a round of technical debt PRs. To avoid having duplicate styles, I kept using string concatenation.

Comments were addressed, PTAL.

 

---

Review status: 4 unresolved discussions, LGTM missing from assignee maddog-tri, platform LGTM from [jwnimmer-tri]

---

*[automotive/maliput/multilane/test_utilities/multilane_types_compare.cc, line 199 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8973#-LGR5Hfh94PmUpffFDtZ:-LGREQ-S8ka4z2Tal2cA:b-ryxpsv) ([raw file](https://github.com/robotlocomotion/drake/blob/cab7f1f8370d32ded4413fccd1949d7096725888/automotive/maliput/multilane/test_utilities/multilane_types_compare.cc#L199)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This violates http://drake.mit.edu/styleguide/cppguide.html#Static_and_Global_Variables.  The best answer is probably just to drop the `static`.
</blockquote></details>

Done. 

I missed it, thanks for pointing it out.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973#-:-LGRBItyALGRHInrBzcY:b-tx6twy)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 8 files at r3, 2 of 2 files at r4.
Review status: 3 unresolved discussions, LGTM missing from assignee maddog-tri, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Comment by jwnimmer-tri** [comment]
I've de-assigned @maddog-tri to unblock that LGTM from reviewable, but there are some feature-review discussions open that I will let @rpoyner-tri resolve as needed.

**Comment by rpoyner-tri** [comment]
Dismissed @maddog-tri from a discussion.
Review status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Comment by rpoyner-tri** [comment]
Dismissed @maddog-tri from a discussion.
Review status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Comment by rpoyner-tri** [comment]
Dismissed @maddog-tri from a discussion.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8973)*

**Pull request merged**
