### PR TITLE
geometry:optimization: Add Clone method to ConvexSet hierarchy.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266#-:-MdPdgpdBW3buSukuWxz:b-qf68jg)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @RussTedrake)

___
*[geometry/optimization/convex_set.h, line 134 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPrwh09ByhGG-6pYPJ:-MdPrwh1ET_C318gfaeg:b-nqwt1x) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/convex_set.h#L134)):*
> ```objc
>       return std::unique_ptr<ConvexSet>(new S(derived_set));
>     };
>   }
> ```

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

Code in header files leads to bloated compile times and intractable shared libraries.

Fixed via https://github.com/RussTedrake/drake/pull/41.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266#-:-MdPzof5Am3yILg_KKbb:b-n37teh)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPwpqi4BmqVTkADdQK:-MdPwpqi4BmqVTkADdQL:bd5occr) (no related file):*
Classes that don't need to access each other's private implementation details should generally live in separate h/cc file pairs, and have separate unit test files.  As each class grows larger over time, development velocity will slow down as we need to wade through the public/protected/private back-and-forths in the header, unrelated functions from other classes in the cc file, and compiler error messages from all translation units glommed together.

So far, it doesn't look like ConvexSet, HPolyhedron, nor HyperEllipsoid need to access private details of the other, and my quick peek at one future feature branch doesn't seem to add any private coupling.  Therefore, at least on first impression, it would be nice to split up the each class into its own files in a future PR, and not add any more new classes to these files until you do.

---
___
*[geometry/optimization/convex_set.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPyJp44bVJ3-SM8RN7:-MdPyJp44bVJ3-SM8RN8:b-9y4ja4) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/convex_set.cc#L25)):*
> ```cpp
> using std::sqrt;
> 
> std::unique_ptr<ConvexSet> ConvexSet::Clone() const { return cloner_(*this); }
> ```

nit This should DRAKE_DEMAND that the return value was non-null (before returning it), akin to an NVI post-condition.  We never want to accidentally return a null.
___
*[geometry/optimization/test/convex_set_test.cc, line 221 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPwIRW9W6iZ6dSWGt8:-MdPwIRW9W6iZ6dSWGt9:bre46vo) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/test/convex_set_test.cc#L221)):*
> ```cpp
>   std::unique_ptr<ConvexSet> clone = H.Clone();
>   EXPECT_EQ(clone->ambient_dimension(), H.ambient_dimension());
>   HPolyhedron* ptr = dynamic_cast<HPolyhedron*>(clone.get());
> ```

nit Abbreviation "ptr"
https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules

Ditto for HyperEllipsoid test below.
___
*[geometry/optimization/test/convex_set_test.cc, line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPwFBG6MdfaYp-fhwr:-MdPwFBG6MdfaYp-fhws:b-bk2b3r) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/test/convex_set_test.cc#L222)):*
> ```cpp
>   EXPECT_EQ(clone->ambient_dimension(), H.ambient_dimension());
>   HPolyhedron* ptr = dynamic_cast<HPolyhedron*>(clone.get());
>   EXPECT_NE(ptr, nullptr);
> ```

nit Prefer ASSERT_NE to fail fast instead of segfaulting on the next line.

Ditto for HyperEllipsoid test below.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[geometry/optimization/convex_set.h, line 134 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPrwh09ByhGG-6pYPJ:-MdRF99J7Ih9dFts2XLb:baqj1p9) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/convex_set.h#L134)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

Code in header files leads to bloated compile times and intractable shared libraries.

Fixed via https://github.com/RussTedrake/drake/pull/41.
</blockquote></details>

Done.  Merged. Thank you!
___
*[geometry/optimization/convex_set.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPyJp44bVJ3-SM8RN7:-MdRFtUfClGtoij7OLVH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/convex_set.cc#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This should DRAKE_DEMAND that the return value was non-null (before returning it), akin to an NVI post-condition.  We never want to accidentally return a null.
</blockquote></details>

Done.
___
*[geometry/optimization/test/convex_set_test.cc, line 221 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPwIRW9W6iZ6dSWGt8:-MdRGn7M8fUvaoLF3MbR:bu7dtko) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/test/convex_set_test.cc#L221)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Abbreviation "ptr"
https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules

Ditto for HyperEllipsoid test below.
</blockquote></details>

Done.  Though I would say that if std::unique_ptr and nullptr are present in these 7 lines, then it seems that ptr is already in the vernacular and not some new abbreviation.
___
*[geometry/optimization/test/convex_set_test.cc, line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPwFBG6MdfaYp-fhwr:-MdRHbIDEvo3RfwXmAQV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/test/convex_set_test.cc#L222)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Prefer ASSERT_NE to fail fast instead of segfaulting on the next line.

Ditto for HyperEllipsoid test below.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266#-:-MdRaZ7H0W2mAoD7FhIc:bz1t39v)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[geometry/optimization/test/convex_set_test.cc, line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPwFBG6MdfaYp-fhwr:-MdSEfPGD-6YY_9CTMPj:b-fn82qm) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/test/convex_set_test.cc#L222)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No change -- missing a push?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

___
*[geometry/optimization/test/convex_set_test.cc, line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15266#-MdPwFBG6MdfaYp-fhwr:-MdSQWNyEMFNmFHYKQ-s:b-8eh3pk) ([raw file](https://github.com/robotlocomotion/drake/blob/b061cd0f97ebd51cca9e70ae7453dde2cac41816/geometry/optimization/test/convex_set_test.cc#L222)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

No change -- missing a push?
</blockquote></details>

Done (again).  I must have curated my commits badly...

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15266#-:-MdTNvKW9H986sdj5Bvz:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
