### PR TITLE
[lcm] Allow handlers for Subscribe to throw exceptions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16027)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please.  See Anzu 7931 for context.

\CC @JShep-tri @naveenoid FYI

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

The code certainly does what it says on the box -- any thoughts as to the information that is lost between what the exception actually carries and the string produced by `what()`?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16027#-:-MnWoFqpAG2nFWoR3q31:bqpkyxe)* status: missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I'm not worried about losing the exception subtype.  It would be nice to record the backtrace somehow, but that's difficult to do.  The user will just need to make sure that their message string stands on its own.

**Review by SeanCurtis-TRI — COMMENTED** [review]
The backtrace is what I particularly had in mind.

On the subject of

> The user will just need to make sure that their message string stands on its own.

I note that we're not *advertising* the fact that the handler can throw. By design? Will we be advertising it in the future and, at that point, I assume the guidance to make sure that the exception message be as self-contained as possible will be given.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16027#-:-MnWpwnYDDlDFqauV4Ed:bjv0mx5)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
And related to that potential advertisement, we're intentionally only catching a portion of what can be thrown in C++. Also by design?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16027#-:-MnWqRhN9xaV6XvxF8BC:b-ci7xec)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> I note that we're not advertising the fact that the handler can throw. By design?

Yes.  The baseline is that all code can throw.  Having code that is `noexcept()` would need to be documented as a variation from the norm (possibly just via the signature), not the other way around.

> Will we be advertising it in the future ...

(No.)

> ... and, at that point, I assume the guidance to make sure that the exception message be as self-contained as possible will be given.

I don't think any of that noise is worthwhile, even for us to think about.  Users will figure out what kind of debugging affordances work for them via experience (or possibly tutorials), not obscure documentation.

> And related to that potential advertisement, we're intentionally only catching a portion of what can be thrown in C++. Also by design?

Yes.  If someone does `throw 10`, then they get to keep the pieces.

**Pull request merged**
