### PR TITLE
[solvers] De-boilerplate common solver option handling

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #12867.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15473)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15473)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/scs_solver.cc, line 570 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15473#-MfYi7v63uHWXihCgVus:-MfYi7v63uHWXihCgVut:btvqmrb) ([raw file](https://github.com/robotlocomotion/drake/blob/b2b34b033cee391499952ac18b7c5890185b3139/solvers/scs_solver.cc#L570)):*
> ```cpp
> void SetScsSettings(
>     std::unordered_map<std::string, int>* solver_options_int,
>     const bool print_to_console,
> ```

we don't need this `const` here?
___
*[solvers/solver_options.h, line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15473#-MfYhbn83gj2uv08vBwA:-MfYhbn83gj2uv08vBwB:b-b2pe94) ([raw file](https://github.com/robotlocomotion/drake/blob/b2b34b033cee391499952ac18b7c5890185b3139/solvers/solver_options.h#L112)):*
> ```objc
>   /** Returns the kPrintFileName set via CommonSolverOption, or else an empty
>    * string if the option has not been set. */
>   std::string get_print_file_name() const;
> ```

Maybe we can use `std::optional<std::string>` as the return type here, and use an empty optional value if the file name has not been set?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15473)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/scs_solver.cc, line 570 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15473#-MfYi7v63uHWXihCgVus:-MfYjJwH4iWAx2L6Z75V:bfowvkh) ([raw file](https://github.com/robotlocomotion/drake/blob/b2b34b033cee391499952ac18b7c5890185b3139/solvers/scs_solver.cc#L570)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

we don't need this `const` here?
</blockquote></details>

In some sense, we don't need `const` _anywhere_ -- we could purge it across the board and the compiler would still be (mostly) happy.  Here, the `const` clarifies to the reader that this function never alters its local copy of this input argument during the (very long) body of the function, even though it is altering the _other_ input argument's contents.
___
*[solvers/solver_options.h, line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15473#-MfYhbn83gj2uv08vBwA:-MfYjuGG5mvkaLiEcYWZ:b3rqwbo) ([raw file](https://github.com/robotlocomotion/drake/blob/b2b34b033cee391499952ac18b7c5890185b3139/solvers/solver_options.h#L112)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe we can use `std::optional<std::string>` as the return type here, and use an empty optional value if the file name has not been set?
</blockquote></details>

That's the question, really.

All common solver options have default values.  For these two new getters (and for all future getters for newly-added common options) here we could return either a `T` or an `optional<T>`.  The only difference between the two is that the optional flavor can disambiguate whether the user set the option to its default value explicitly, or whether the default came about implicitly.

My question is -- will a solver back-end ever _care_ whether the option was explicitly vs implicitly defaulted?  My sense is that no back-end will care -- it wants to know the current value for the option, no matter where it came from.  Replicating the defaulting behavior in every back-end seems more difficult to maintain, for no benefit.

WDYT?

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@seancurtis-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15473#-:-MfYnKU65ijcr__LyqFf:b-vthiex)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[solvers/scs_solver.cc, line 570 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15473#-MfYi7v63uHWXihCgVus:-MfYn09EDGAtkCB5yzD4:b-s622lo) ([raw file](https://github.com/robotlocomotion/drake/blob/b2b34b033cee391499952ac18b7c5890185b3139/solvers/scs_solver.cc#L570)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In some sense, we don't need `const` _anywhere_ -- we could purge it across the board and the compiler would still be (mostly) happy.  Here, the `const` clarifies to the reader that this function never alters its local copy of this input argument during the (very long) body of the function, even though it is altering the _other_ input argument's contents.
</blockquote></details>

I see, thanks
___
*[solvers/solver_options.h, line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15473#-MfYhbn83gj2uv08vBwA:-MfYn6hL5lVGwg0Q7KXY:bk4kqzr) ([raw file](https://github.com/robotlocomotion/drake/blob/b2b34b033cee391499952ac18b7c5890185b3139/solvers/solver_options.h#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That's the question, really.

All common solver options have default values.  For these two new getters (and for all future getters for newly-added common options) here we could return either a `T` or an `optional<T>`.  The only difference between the two is that the optional flavor can disambiguate whether the user set the option to its default value explicitly, or whether the default came about implicitly.

My question is -- will a solver back-end ever _care_ whether the option was explicitly vs implicitly defaulted?  My sense is that no back-end will care -- it wants to know the current value for the option, no matter where it came from.  Replicating the defaulting behavior in every back-end seems more difficult to maintain, for no benefit.

WDYT?
</blockquote></details>

I see, I think that makes sense.

My thought was that I am not sure if an empty string is a good default value. Now I think more about it I am convinced it is.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15473)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[solvers/solver_options.h, line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15473#-MfYhbn83gj2uv08vBwA:-MfYo1JjChseoVxf4XBn:b-s1ocnx) ([raw file](https://github.com/robotlocomotion/drake/blob/b2b34b033cee391499952ac18b7c5890185b3139/solvers/solver_options.h#L112)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, I think that makes sense.

My thought was that I am not sure if an empty string is a good default value. Now I think more about it I am convinced it is.
</blockquote></details>

Great!

We've documented `""` as 'no print' for a while now, so it would be difficult to change it at this point:

https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1solvers.html#ae07229124cd16e9d8b62fe359c7d0b40

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15473#-:-MfZOQ0dAXTapEEZLAXp:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @jwnimmer-tri)

**Pull request merged**
