### PR TITLE
Updated Drake-ROS System 1.0 Systems To Use model_instance_id

### PR DESCRIPTION
**Pull request by liangfok**
# Motivation

The `model_instance_id` abstraction within `RigidBodyTree` enables (1) less bookkeeping in Drake-ROS System 1.0 systems, and (2) better support for simulations that involve multiple vehicles. I'd like these to go into master so we can use them as a reference as we transition them into System 2.0 variants.

In addition to updated System 1.0 systems, this PR also includes an update to the previously existing `single_car_in_stata_garage` demo since it uses the new Drake-ROS system 1.0 systems. A unit test called `single_car_in_stata_garage_test.test` is included lock in the functional state of the demo. I didn't think it was necessary to include an individual unit test for each system since these are System 1.0 systems that will soon be deprecated by System 2.0 variants. Each System 2.0 version of these Drake-ROS systems will have dedicated unit test coverage.

This PR includes elements extracted from #3103.

# Usage Instructions

For instructions on how to run the `single_car_in_stata_garage` demo and unit test, see: https://github.com/liangfok/drake/tree/feature/multi_car_sim_2_8/ros/drake_cars_examples

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3609)

### CODE REVIEW

**Comment by liangfok** [comment]
Review status: 0 of 24 files reviewed at latest revision, 18 unresolved discussions.

---

*[ros/drake_cars_examples/README.md, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmASA6mcuie5sqS6fb:-KSmASA6mcuie5sqS6fc:b8oaem4) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/README.md#L4)):*
> ```Markdown
> =================================
> 
> This README provides details about and instructions on how to run Drake's car
> ```

Replace "Drake's" with "Drake / ROS's".

---

*[ros/drake_cars_examples/README.md, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmAsHSTnJXZvPI7Xil:-KSmAsHSTnJXZvPI7Xim:bvysjb1) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/README.md#L49)):*
Add the following to the end of the sentence:

> in `drake_cars_examples/launch/single_car_in_stata_garage_drake.xml`.

---

*[ros/drake_cars_examples/README.md, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmB9yHtQDt8mZtznUN:-KSmB9yHtQDt8mZtznUO:bvysjb1) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/README.md#L53)):*
Add the following to the end of the sentence:

> in `drake_cars_examples/launch/single_car_in_stata_garage_drake.xml`.

---

*[ros/drake_cars_examples/README.md, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmAmiAGb2-CZh1va91:-KSmAmiAGb2-CZh1va92:b6wuto9) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/README.md#L56)):*
> ```Markdown
> 
> The initial time step using by the simulation's "solver" is set by parameter
> "initial_step_size".
> ```

Missing newline.

---

*[ros/drake_cars_examples/launch/rviz.xml, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmBFASyHt7X2RPv_AP:-KSmBFASyHt7X2RPv_AQ:bouxsom) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/launch/rviz.xml#L12)):*
> ```XML
>     
> 
>     
> ```

Remove commented out code.

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage_drake.xml, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmMxTXzRKUsxyB13b8:-KSmMxTXzRKUsxyB13b9:bouxsom) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/launch/single_car_in_stata_garage_drake.xml#L37)):*
> ```XML
>   </group>
> 
>   
> ```

Remove commented out code.

---

*[ros/drake_cars_examples/rviz/single_car_in_stata_garage.rviz, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmB_1a9Y2T3rscr74b:-KSmB_1a9Y2T3rscr74c:b-yrujgf) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/rviz/single_car_in_stata_garage.rviz#L1)):*
> ```YAML
> Panels:
> ```

BTW: **Note to Reviewers:** This file is automatically generated by RViz. The only way to "review" it is to run the demo and verify that the RViz visualization looks good.

---

*[ros/drake_cars_examples/src/single_car_in_stata_garage.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmDZdd6jq83tS5Rth_:-KSmDZdd6jq83tS5Rtha:b-4h0rp3) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/src/single_car_in_stata_garage.cc#L4)):*
> ```cpp
> 
> #include "ros/ros.h"
> #include "ros/console.h"
> ```

Alpha sort.

---

*[ros/drake_cars_examples/src/single_car_in_stata_garage.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmDxmwoI9j_2iyM8t1:-KSmDxmwoI9j_2iyM8t2:b-4h0rp3) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/src/single_car_in_stata_garage.cc#L43)):*
> ```cpp
> 
> using drake::ros::systems::RosTfPublisher;
> using drake::ros::systems::RosClockPublisher;
> ```

Alpha sort.

---

*[ros/drake_cars_examples/test/README.md, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmN7Iqcw5oHurEoM2_:-KSmN7Iqcw5oHurEoM2a:b-ukc66b) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/test/README.md#L5)):*
> ```Markdown
>    $ rostest drake_cars_examples single_car_in_stata_garage_test.test
> 
> The above will store output in a log file and use a roscore on a random port
> ```

Replace "above will store output" with "output will be stored".

---

*[ros/drake_cars_examples/test/README.md, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmNIQlHZ_xkK_S8soL:-KSmNIQlHZ_xkK_S8soM:bahazu1) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/test/README.md#L5)):*
> ```Markdown
>    $ rostest drake_cars_examples single_car_in_stata_garage_test.test
> 
> The above will store output in a log file and use a roscore on a random port
> ```

Surround `roscore` with back ticks.

---

*[ros/drake_cars_examples/test/single_car_in_stata_garage_test.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmNh6rB0AQXYuQFYPY:-KSmNh6rB0AQXYuQFYPZ:b-p1bxfi) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/test/single_car_in_stata_garage_test.cc#L70)):*
> ```cpp
>   EXPECT_TRUE(drake_node_found);
> 
>   // Verifies that the Drake simulator is publishing `sensor_msgs::JointState`
> ```

Replace "the Drake simulator" with "Drake".

---

*[ros/drake_cars_examples/test/single_car_in_stata_garage_test.cc, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmNcDC2KedmhCVJ-1e:-KSmNcDC2KedmhCVJ-1f:b-vygaek) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/test/single_car_in_stata_garage_test.cc#L93)):*
> ```cpp
>     received_state = callback.received_state();
>     if (!received_state)
>       sleep_for(TimeDuration(1000));  // Sleeps for 1000 milliseconds.
> ```

Switch to use ROS' `WallDuration`.

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmNomLLUGPjI8s1CFc:-KSmNomLLUGPjI8s1CFd:bouxsom) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h#L3)):*
> ```objc
> #pragma once
> 
> // #include <stdexcept>
> ```

Remove commented out code.

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmNqQTi90uykLtCBn9:-KSmNqQTi90uykLtCBnA:bouxsom) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h#L12)):*
> ```objc
> // #include "drake/systems/System.h"
> // #include "drake/systems/plants/KinematicsCache.h"
> // #include "drake/systems/plants/RigidBodySystem.h"
> ```

Remove commented out code.

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmNsqtCYgff3Rs_4FM:-KSmNsqtCYgff3Rs_4FN:bpfof20) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h#L29)):*
> ```objc
> /**
>  * @brief A system that publishes the current simulation time on ROS topic
>  * /clock.takes the system state as the input and publishes
> ```

Grammar error. Delete second sentence.

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmO6L_VEDYNEGlxAgN:-KSmO6L_VEDYNEGlxAgO:boz2ebh) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h#L48)):*
> ```objc
> 
>   /**
>    * The constructor, which initializes the clock publisher.
> ```

Add more content to this description.

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KSmOH5gtqhKGjPGlsBZ:-KSmOH5gtqhKGjPGlsB_:b-xu3qd4) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h#L69)):*
> ```objc
>                               const InputVector<double>& u) {
>     // Computes the whole-second portion and the fractional-second portion of
>     // the current simulatoin time @p t.
> ```

typo: "simulation"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3609)*

**Comment by liangfok** [comment]
CI pre-merge passed. Now testing ROS:

@drake-jenkins-bot linux-clang-experimental-ros please.
@drake-jenkins-bot linux-gcc-experimental-ros please.
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please.

**Comment by liangfok** [comment]
+@naveenoid for feature review please.

---

Review status: 0 of 24 files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-:-KSpRZgiJ1Oc-qxe-tD_:b-jlfufc)*

**Comment by naveenoid** [comment]
@liangfok  Ive just began my review but I would like an f2f for you to describe to me a bit more about what the aims of this PR are. 

---

Review status: 0 of 24 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[drake/automotive/car_simulation.cc, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KT8lapwXeEAW18B3ImY:-KT8lapwXeEAW18B3ImZ:b-epucre) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/drake/automotive/car_simulation.cc#L174)):*
> ```cpp
> 
>   // Instantiates a N x 3 matrix called map_driving_cmd_to_x_d where N is the
>   // number position and velocity states in the rigid body tree. The three
> ```

nit: number "of"

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage.launch, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KT8z4JPSMXP2h4ye4OH:-KT8z4JQnfgTOTqfmNPj:b-6g7quj) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_cars_examples/launch/single_car_in_stata_garage.launch#L10)):*
> ```XML
> <launch>
>   <include file="$(find drake_cars_examples)/launch/single_car_in_stata_garage_drake.xml" />
>   <include file="$(find drake_cars_examples)/launch/single_car_in_stata_garage_rviz.xml" />
> ```

BTW: could you describe the need for this simplification?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-:-KT9AnElmDZTHzXka33m:b-6eckd3)*

**Comment by liangfok** [comment]
To summarize a F2F discussion with @naveenoid, the order I would approach this PR is as follows:

1. First look at the changes to the Drake + ROS systems in `ros/drake_ros_systems/include/drake/ros/systems/`. These systems have been updated to use the `model_instance_id` abstraction that was added to `RigidBodyTree` in #3043.
2. Second look at the updates to the `single_car_in_stata_garage` demo. It is located in `ros/drake_cars_examples/`.
3. Finally, look at the remaining files, which are basically configuration files that enable the demo to be easily launched.

---

Review status: 0 of 24 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-:-KT9d-UnIHVX3Fw9KSab:b-70quip)*

**Comment by naveenoid** [comment]
Reviewed 4 of 24 files at r1.
Review status: 4 of 24 files reviewed at latest revision, 30 unresolved discussions, some commit checks failed.

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTgSIhydKsiuGVnXbLf:-KTgSIhydKsiuGVnXbLg:b-siisbn) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_clock_publisher.h#L33)):*
> ```objc
>  *
>  * For convenience, the input is passed directly through as an output. This
>  * enables other systems to be cascaded after this system.
> ```

BTW: It seems this system was needed for a problem different to that of the model_instance_id. Could you perhaps explain here why it was needed? Im assuming its to achieve synchronisation with ROS?

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTgSyrq7EPNiLIcJrYZ:-KTgSyrq7EPNiLIcJrY_:b2h6tyh) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h#L102)):*
> ```objc
> 
>     // Creates a ROS topic publisher and a message for each model instance in
>     // `model_instance_table`.
> ```

typo : insert "the"

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTgTwsRcMgYqZBZSw31:-KTgTwsRcMgYqZBZSw32:bgoc7fp) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h#L143)):*
> ```objc
>     // The following code extracts the position and velocity vectors from
>     // system_state_vector and computes the kinematic properties of the system.
>     // These kinematic properties are stored in `cache`, which is then used to
> ```

Typo : insert "a" between "in" and "'cache'". 
Also perhaps its better to call it a 'KinematicCache' to avoid confusion with System2.0 cache concept (hence remove the word kinematic from the beginning of the sentence).

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h, line 220 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTgUwCIPq6Tq6Jogory:-KTgUwCIPq6Tq6Jogorz:bxy7aho) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h#L220)):*
> ```objc
>     model_state_info->message.reset(new sensor_msgs::JointState());
> 
>     // The message contains information in joint space. Thus it is unclear
> ```

Since this whole comment block is a discussion, I would suggest the TODO line to be relocated to the beginning of this block.

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTgVJJY-xmB8Cew3ii4:-KTgVJJZEh1hy3Lxe5sI:b-8pt9re) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h#L233)):*
> ```objc
>       if (joint.getNumPositions() > 0) {
>         if (joint.isFloating()) {
>           // Floating joints have unequal numbers of position (4) vs.
> ```

BTW: perhaps the word 'dimensionality' is a better substitute for 'number'

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h, line 355 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTgWadn8iF2JfD-wDvS:-KTgWadow_0QFRMAsORx:b-gzrxgc) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_joint_state.h#L355)):*
> ```objc
> 
>           // Updates joint_state_index to point to the position in the joint
>           // state message after the portion that stores this floating joint's
> ```

BTW: consider changing "after" to "subsequent to" or even consider rewriting this comment for clarity. 

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_lidar.h, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTh-4eMG3M8INtGnXTv:-KTh-4eMG3M8INtGnXTw:bmt7lzz) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_lidar.h#L111)):*
> ```objc
> 
>         // Verifies that the model instance name can be determined.
>         // Throws an error if it cannot.
> ```

BTW:nit : consider combining these sentences.

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_lidar.h, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTh-OWl2JO_jS6Qietq:-KTh-OWl2JO_jS6Qietr:b561igg) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_lidar.h#L169)):*
> ```objc
> 
>         // Since the RigidBodyDepthSensor does not include this information
>         // in the output and it is difficult to obtain this information
> ```

BTW: Which info are you referring to? If its the time_increment, scan_time etc, consider rewording this comment for clarity.

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_odometry.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTh1oBHgavWJ_PveArC:-KTh1oBHgavWJ_PveArD:b-5en5uc) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_odometry.h#L43)):*
> ```objc
>  * Takes the system state and publishes odometry information onto ROS topics.
>  *
>  * It publishes a odometry information for each model within the rigid body
> ```

remove "a"

---

*[ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_odometry.h, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-KTh1rHOaHxvl7Yhcwun:-KTh1rHOaHxvl7Yhcwuo:b-fe16vq) ([raw file](https://github.com/robotlocomotion/drake/blob/4b37d4b5e47bd64d496340b5476548fe5a8cef77/ros/drake_ros_systems/include/drake/ros/systems/ros_sensor_publisher_odometry.h#L44)):*
> ```objc
>  *
>  * It publishes a odometry information for each model within the rigid body
>  * system that connected to the world via a floating joint. The odometry
> ```

nit : insert "is" between "that" and "connected

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3609)*

**Comment by naveenoid** [comment]
Milestone 1 inside first pass. I will keep at it until its done. 

---

Review status: 4 of 24 files reviewed at latest revision, 30 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-:-KTh56xXCB8HpDLF0zEz:bm4mkz1)*

**Comment by liangfok** [comment]
@naveenoid, thank you very much for the review! I will be sure to address your comments in a future PR. @russtedrake decided we should purge all System 1.0-based systems as quickly as possible. Because of this, I will close this PR and submit a new PR that contains a System 2.0-based systems.

---

Review status: 4 of 24 files reviewed at latest revision, 30 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3609#-:-KTvQMABsqBjkH-_yFlD:b-o9bj0u)*

**Pull request closed without merging**
