### PR TITLE
[workspace] Upgrade petsc to latest release v3.17.1

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #17093.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
Something went sideways, removing reviewer for now -@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119#-:-N1PGd6SEqnDWWCOME-K:bh0qv20)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/petsc/patches/matrix.patch` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1PKaz-ACuCNz1fBgK3:-N1PKaz-ACuCNz1fBgK4:bfjkwy3) ([raw file](https://github.com/robotlocomotion/drake/blob/238dc416901af60f5b203840dd90637d3264adf4/tools/workspace/petsc/patches/matrix.patch#L20)):*
> ```Diff
>  
>    PetscFunctionBegin;
>    PetscValidHeaderSpecific(mat,MAT_CLASSID,1);
> ```

This is... odd? I would not expect the patch to need to gain an additional line of context.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail and @mwoehlke-kitware)

___
*[`tools/workspace/petsc/stubs/petscconf.h` line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1PugjC5d0YHOFpQn2B:-N1PugjC5d0YHOFpQn2C:bqrb7te) ([raw file](https://github.com/robotlocomotion/drake/blob/545d86630e23f4f2c329083a78adce928e0b29e2/tools/workspace/petsc/stubs/petscconf.h#L120)):*
> ```objc
> #define PETSC_HAVE_SNPRINTF 1
> #define PETSC_HAVE_SOCKET 1
> #define PETSC_HAVE_SOWING 1
> ```

Ack, this is my bad :flushed:. This line (`#define PETSC_HAVE_SOWING 1`) probably should not be added.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/petsc/stubs/petscconf.h` line 8 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1dOZ7g5GCppty_SvKv:-N1dOZ7h2ddjEKPpX4Dp:bd179mt) ([raw file](https://github.com/robotlocomotion/drake/blob/5b46661fe4a23e3d38c95b4496fea19e490af095/tools/workspace/petsc/stubs/petscconf.h#L8)):*
> ```objc
> //
> // This file can be (approximately) recreated using:
> //  ./configure --with-x=0 --with-mpi=0 --with-sowing 0 \
> ```

Nit (my bad!):



_Suggestion:_
```objc
--with-sowing=0
```

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
+@xuchenhan-tri for review please. Although the patch files look like a lot of changes, it is due to renaming within the Petsc code itself. The patch logic remained the same and applied easily.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119#-:-N1ek8NL53FVJQs4j4Zm:bnrqwfx)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware and @xuchenhan-tri)

___
*[`tools/workspace/petsc/stubs/petscconf.h` line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1PugjC5d0YHOFpQn2B:-N1ek5lS19zxdoreUZIl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/545d86630e23f4f2c329083a78adce928e0b29e2/tools/workspace/petsc/stubs/petscconf.h#L120)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Ack, this is my bad :flushed:. This line (`#define PETSC_HAVE_SOWING 1`) probably should not be added.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@jwnimmer-tri for review as well.

The patch rebasing is the easy part, it's the large number of petscconf.h changes are the more important part of this PR.

Across the version number change, if upstream added _new_ macros to is configure script then it's appropriate to add definitions for those here, or if upstream dropped macros from its configure script (perhaps `PETSC_HAVE_CXX_DIALECT_CXX03`?) then it's appropriate to remove those here.  Otherwise, there should be no other changes to petscconf.h, yet I see a ton of what appear to be changes to petscconf.h, unrelated to a version upgrade.  At a minimum, those changes need some explanation in the PR overview, but I suspect they are actually just unwanted.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119#-:-N1el4-C8XSJf5jjjGwV:b-1mva9o)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),xuchenhan-tri(platform), missing label for release notes (waiting on @jwnimmer-tri, @mwoehlke-kitware, and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
My plan is to re-do the petscconf.h changes myself and push a fixup here.  If you have specific information about added/removed config switches from your exploration, let me know.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119#-:-N1emeeo3Yajp1p5HW4J:bb9o1kp)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),xuchenhan-tri(platform), missing label for release notes (waiting on @jwnimmer-tri, @mwoehlke-kitware, and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @mwoehlke-kitware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),xuchenhan-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[`tools/workspace/petsc/stubs/petscconf.h` line 113 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1enm5l1C-Ec8w6lrXM:-N1enm5l1C-Ec8w6lrXN:b4gxa2a) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L113)):*
> ```objc
> #define PETSC_HAVE_SLEEP 1
> #define PETSC_HAVE_SNPRINTF 1
> #define PETSC_HAVE_SOCKET 1
> ```

Working

We do not let petsc talk to the network.
___
*[`tools/workspace/petsc/stubs/petscconf.h` line 185 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1enZ_p0RvlrqNO1wZ8:-N1enZ_p0RvlrqNO1wZ9:b-udxngh) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L185)):*
> ```objc
> #define PETSC_UINTPTR_T uintptr_t
> #define PETSC_UNUSED __attribute((unused))
> #define PETSC_USE_AVX512_KERNELS 1
> ```

Working

Drake must work on non-AVX512 machines.
___
*[`tools/workspace/petsc/stubs/petscconf.h` line 201 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1enQiWBKvDjgxSdpog:-N1enQiWBKvDjgxSdpoh:b16y8qy) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L201)):*
> ```objc
> #define PETSC_USING_DARWIN 1
> #endif
> #define PETSC_USING_F2003 1
> ```

Working

We don't use the Fortran build.

**Review by BetsyMcPhail — COMMENTED** [review]
@mwoehlke-kitware can you offer any insight into the changes in petscconf.h? 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119#-:-N1iHSoE1euZMPhyUJiV:b6ajzvx)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),xuchenhan-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
It's true that Xuchen and I need to improve the documentation and process around this file.  We have some assumptions in play that were not written down.  We'll work on improving that, as we take over this PR now.

It was not my intention for anyone else other than him and myself to try to edit this file without our guidance.  I'll be sure to document that more clearly as well.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119)* status: 8 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),xuchenhan-tri(platform), missing label for release notes (waiting on @BetsyMcPhail, @jwnimmer-tri, and @xuchenhan-tri)

___
*[`tools/workspace/petsc/stubs/petscconf.h` line 58 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1iY9CmCQj3ums1fNnu:-N1iY9CmCQj3ums1fNnv:b-izj5o3) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L58)):*
> ```objc
> #define PETSC_HAVE_FLOAT_H 1
> #define PETSC_HAVE_FORK 1
> #define PETSC_HAVE_FSTATAT 1
> ```

In general, why would we *not* use features available on the platform? I'll comment on specific exceptions, otherwise I think any additions of this nature should be kept unless there is specific justification otherwise.
___
*[`tools/workspace/petsc/stubs/petscconf.h` line 76 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1iY3Z78DexJujSlo0P:-N1iY3Z78DexJujSlo0Q:bucardh) ([raw file](https://github.com/robotlocomotion/drake/blob/4a3f872e90f3ad4ecd82bdcd4b94b405a99af761/tools/workspace/petsc/stubs/petscconf.h#L76)):*
> ```objc
> #define PETSC_HAVE_MMAP 1
> #define PETSC_HAVE_MPIUNI 1
> #define PETSC_HAVE_MPI_IN_PLACE 1
> ```

These three no longer appear in the PETSc code.
___
*[`tools/workspace/petsc/stubs/petscconf.h` line 100 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1iYVg07gZ3e2QuhCkC:-N1iYVg07gZ3e2QuhCkD:b-ktpiu) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L100)):*
> ```objc
> #define PETSC_HAVE_REALPATH 1
> #ifndef __APPLE__
> #define PETSC_HAVE_REAL___FLOAT128 1
> ```

This was not defined on x86 macOS. Possibly PETSc knows not to use it anyway, but explicitly removing it from macOS seems safer.
___
*[`tools/workspace/petsc/stubs/petscconf.h` line 113 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1enm5l1C-Ec8w6lrXM:-N1iYdkm6zdLLAxwcL3h:bvol3gz) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L113)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

We do not let petsc talk to the network.
</blockquote></details>

Okay. We might want to consider commenting these out rather than simply removing them, with a note, so that next time someone wants to update this, the knowledge is not lost.
___
*[`tools/workspace/petsc/stubs/petscconf.h` line 129 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1iacSv6So4-C2mGW0-:-N1iacSw815BAR012n7N:bjwcu2m) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L129)):*
> ```objc
> #define PETSC_HAVE_SYS_SOCKET_H 1
> #ifdef __APPLE__
> #define PETSC_HAVE_SYS_SYSCTL_H 1
> ```

It appears that this (and `PETSC_RTLD_DEFAULT`) are defined but never used. My inclination would be to keep them to minimize unnecessary differences vs. the generated version.
___
*[`tools/workspace/petsc/stubs/petscconf.h` line 161 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1icMKF1LzTv2aRhple:-N1icMKG-QoV6pRK_Hp4:b-wc894p) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L161)):*
> ```objc
> #define PETSC_MAX_PATH_LEN 4096
> #endif
> #define PETSC_MEMALIGN 16
> ```

This should be mostly harmless, at worst, and very possibly a performance improvement.

**Comment by mwoehlke-kitware** [comment]
I have the following (below) "latest" version, which should be "exactly" what comes out of `./configure`, with caveats:

- Some "obvious" changes from Drake have been silently retained. (`#pragma once`, whitespace changes, a `// NOLINT`, and the providence comment at the top.) I don't expect any confusion to arise from these.
- Host-specific stuff (e.g. `PETSC_VERSION_GIT`, `PETSC_LIB_DIR`) remains altered as before. Again, it should be obvious that these changes are intended to be retained.
  - That said, if we would *consistently* update this file when upadting the PETSc version, we might want to consider retaining the version information.
- Stuff that varies by platform is guarded by appropriate conditionals. (Except M1; the changes from #17121 should also be merged, but I'm deliberately keeping them separate.) Updating these will need some care, but otherwise they should be obvious.
- Anything that was deliberately removed is *commented out*. Several cases include an explanatory comment. This ensures that these changes are documented.
- It includes the options given to `configure`.

I think we should retain these changes; it brings us closer to upstream and makes it clear where we are making additional, non-obvious changes so that these can be retained. This should make it much easier to update the `petscconf.h` next time.

```c++
#pragma once

// TODO(jwnimmer-tri): This file is a lightly-edited version of what comes out
// of upstream's configure script that has been tweaked to work on all of our
// supported platforms, and to remove some unwanted bits. Commented out
// definitions indicate things present in the generated version which we have
// deliberately removed.
//
// This file can be (approximately) recreated using:
//  ./configure --with-log=0 --with-x=0 --with-mpi=0 --with-sowing 0 \
//              --with-fortran-bindings=0 --with-matlab-socket=0 \
//              --with-debugging=0

#define MPI_Comm_create_errhandler(p_err_fun, p_errhandler) \
  MPI_Errhandler_create((p_err_fun), (p_errhandler))
#define MPI_Comm_set_errhandler(comm, p_errhandler) \
  MPI_Errhandler_set((comm), (p_errhandler))
#define MPI_Type_create_struct(count, lens, displs, types, newtype) \
  MPI_Type_struct((count), (lens), (displs), (types), (newtype))
#define PETSC_ARCH "NO_PETSC_ARCH"
#define PETSC_ATTRIBUTEALIGNED(size) __attribute((aligned(size)))
#define PETSC_Alignx(a, b)
#ifdef __APPLE__
# define PETSC_BLASLAPACK_SDOT_RETURNS_DOUBLE 1
# define PETSC_BLASLAPACK_SNRM2_RETURNS_DOUBLE 1
#endif
#define PETSC_BLASLAPACK_UNDERSCORE 1
#define PETSC_CLANGUAGE_C 1
#define PETSC_CXX_RESTRICT __restrict
#define PETSC_DEPRECATED_ENUM(why) __attribute((deprecated))
#define PETSC_DEPRECATED_FUNCTION(why) __attribute((deprecated))
#define PETSC_DEPRECATED_MACRO(why) _Pragma(why)
#define PETSC_DEPRECATED_TYPEDEF(why) __attribute((deprecated))
#define PETSC_DIR "NO_PETSC_DIR"
#define PETSC_DIR_SEPARATOR '/'
#ifdef __APPLE__
# define PETSC_DO_NOT_SWAP_CHILD_FOR_DEBUGGER 1
#endif
//#define PETSC_FORTRAN_* - Not using Fortran, shouldn't need these.
#define PETSC_FUNCTION_NAME_C __func__
#define PETSC_FUNCTION_NAME_CXX __func__
#define PETSC_HAVE_ACCESS 1
#define PETSC_HAVE_ATOLL 1
#define PETSC_HAVE_ATTRIBUTEALIGNED 1
#define PETSC_HAVE_BUILTIN_EXPECT 1
#define PETSC_HAVE_BZERO 1
#define PETSC_HAVE_C99_COMPLEX 1
#define PETSC_HAVE_CLOCK 1
#ifdef __APPLE__
# define PETSC_HAVE_CLOSURE 1
#endif
#define PETSC_HAVE_CXX 1
#ifdef __APPLE__
# define PETSC_HAVE_CXXABI_H 1
#endif
#define PETSC_HAVE_CXX_COMPLEX 1
#define PETSC_HAVE_CXX_COMPLEX_FIX 1
#define PETSC_HAVE_CXX_DIALECT_CXX11 1
#define PETSC_HAVE_CXX_DIALECT_CXX14 1
#define PETSC_HAVE_CXX_DIALECT_CXX17 1
#define PETSC_HAVE_DLADDR 1
#define PETSC_HAVE_DLCLOSE 1
#define PETSC_HAVE_DLERROR 1
#define PETSC_HAVE_DLFCN_H 1
#define PETSC_HAVE_DLOPEN 1
#define PETSC_HAVE_DLSYM 1
#define PETSC_HAVE_DOUBLE_ALIGN_MALLOC 1
#define PETSC_HAVE_DRAND48 1
#define PETSC_HAVE_DYNAMIC_LIBRARIES 1
#define PETSC_HAVE_ERF 1
#define PETSC_HAVE_FCNTL_H 1
#define PETSC_HAVE_FENV_H 1
#define PETSC_HAVE_FLOAT_H 1
#define PETSC_HAVE_FORK 1
//#define PETSC_HAVE_FORTRAN_* - Not using Fortran, shouldn't need these.
#define PETSC_HAVE_GETCWD 1
#define PETSC_HAVE_GETDOMAINNAME 1
#define PETSC_HAVE_GETHOSTBYNAME 1
#define PETSC_HAVE_GETHOSTNAME 1
#define PETSC_HAVE_GETPAGESIZE 1
#define PETSC_HAVE_GETRUSAGE 1
#ifdef __APPLE__
# define PETSC_HAVE_GETWD 1
#endif
#define PETSC_HAVE_IMMINTRIN_H 1
#define PETSC_HAVE_INTTYPES_H 1
#define PETSC_HAVE_ISINF 1
#define PETSC_HAVE_ISNAN 1
#define PETSC_HAVE_ISNORMAL 1
#define PETSC_HAVE_LGAMMA 1
#define PETSC_HAVE_LOG2 1
#define PETSC_HAVE_LSEEK 1
#ifdef __APPLE__
# define PETSC_HAVE_MACHINE_ENDIAN_H 1
#else
# define PETSC_HAVE_MALLOC_H 1
# define PETSC_HAVE_MEMALIGN 1
#endif
#define PETSC_HAVE_MEMMOVE 1
#define PETSC_HAVE_MMAP 1
#define PETSC_HAVE_MPIUNI 1
#define PETSC_HAVE_NANOSLEEP 1
#define PETSC_HAVE_NETDB_H 1
#define PETSC_HAVE_NETINET_IN_H 1
#define PETSC_HAVE_PACKAGES ":blaslapack:mathlib:mpi:pthread:regex:"
#define PETSC_HAVE_POPEN 1
#define PETSC_HAVE_PTHREAD 1
#ifndef __APPLE__
# define PETSC_HAVE_PTHREAD_BARRIER_T 1
#endif
#define PETSC_HAVE_PTHREAD_H 1
#define PETSC_HAVE_PWD_H 1
#define PETSC_HAVE_RAND 1
#define PETSC_HAVE_READLINK 1
#define PETSC_HAVE_REALPATH 1
#ifndef __APPLE__
# define PETSC_HAVE_REALFLOAT128 1
#endif
#define PETSC_HAVE_REGEX 1
#define PETSC_HAVE_RTLD_GLOBAL 1
#define PETSC_HAVE_RTLD_LAZY 1
#define PETSC_HAVE_RTLD_LOCAL 1
#define PETSC_HAVE_RTLD_NOW 1
#ifndef __APPLE__
# define PETSC_HAVE_SCHED_CPU_SET_T 1
#endif
#define PETSC_HAVE_SETJMP_H 1
#define PETSC_HAVE_SLEEP 1
#define PETSC_HAVE_SNPRINTF 1
//#define PETSC_HAVE_SOCKET 1       - Don't allow network access.
//#define PETSC_HAVE_SO_REUSEADDR 1 - Don't allow network access.
#define PETSC_HAVE_STDINT_H 1
#define PETSC_HAVE_STRCASECMP 1
#define PETSC_HAVE_STRINGS_H 1
#define PETSC_HAVE_STRUCT_SIGACTION 1
#ifndef __APPLE__
# define PETSC_HAVE_SYSINFO 1
#endif
#define PETSC_HAVE_SYS_PARAM_H 1
#ifndef __APPLE__
# define PETSC_HAVE_SYS_PROCFS_H 1
#endif
#define PETSC_HAVE_SYS_RESOURCE_H 1
#define PETSC_HAVE_SYS_SOCKET_H 1
#ifdef __APPLE__
# define PETSC_HAVE_SYS_SYSCTL_H 1
#else
# define PETSC_HAVE_SYS_SYSINFO_H 1
#endif
#define PETSC_HAVE_SYS_TIMES_H 1
#define PETSC_HAVE_SYS_TIME_H 1
#define PETSC_HAVE_SYS_TYPES_H 1
#define PETSC_HAVE_SYS_UTSNAME_H 1
#define PETSC_HAVE_SYS_WAIT_H 1
#define PETSC_HAVE_TGAMMA 1
#define PETSC_HAVE_TIME 1
#define PETSC_HAVE_TIME_H 1
#define PETSC_HAVE_UNAME 1
#define PETSC_HAVE_UNISTD_H 1
#define PETSC_HAVE_USLEEP 1
#define PETSC_HAVE_VA_COPY 1
#define PETSC_HAVE_VSNPRINTF 1
#define PETSC_HAVE_XMMINTRIN_H 1
#define PETSC_IS_COLORING_MAX USHRT_MAX
#define PETSC_IS_COLORING_VALUE_TYPE short  // NOLINT
#define PETSC_IS_COLORING_VALUE_TYPE_F integer2
#ifdef __APPLE__
# define PETSC_LEVEL1_DCACHE_LINESIZE 32
#else
# define PETSC_LEVEL1_DCACHE_LINESIZE 64
#endif
#define PETSC_LIB_DIR "NO_PETSC_LIB_DIR"
#ifdef __APPLE__
# define PETSC_MAX_PATH_LEN 1024
#else
# define PETSC_MAX_PATH_LEN 4096
#endif
#define PETSC_MEMALIGN 16
#define PETSC_MPICC_SHOW "Unavailable"
#define PETSC_MPIU_IS_COLORING_VALUE_TYPE MPI_UNSIGNED_SHORT
#define PETSC_PREFETCH_HINT_NTA _MM_HINT_NTA
#define PETSC_PREFETCH_HINT_T0 _MM_HINT_T0
#define PETSC_PREFETCH_HINT_T1 _MM_HINT_T1
#define PETSC_PREFETCH_HINT_T2 _MM_HINT_T2
#define PETSC_PYTHON_EXE "NO_PETSC_PYTHON_EXE"
#define PETSC_Prefetch(a, b, c) _mm_prefetch((const char*)(a), (c))
#define PETSC_REPLACE_DIR_SEPARATOR '\\'
#ifdef __APPLE__
# define PETSC_RTLD_DEFAULT 1
#endif
#define PETSC_SIGNAL_CAST
#define PETSC_SIZEOF_ENUM 4
#define PETSC_SIZEOF_INT 4
#define PETSC_SIZEOF_LONG 8
#define PETSC_SIZEOF_LONG_LONG 8
#define PETSC_SIZEOF_SHORT 2
#define PETSC_SIZEOF_SIZE_T 8
#define PETSC_SIZEOF_VOID_P 8
#define PETSC_SLSUFFIX "so"
#define PETSC_UINTPTR_T uintptr_t
#define PETSC_UNUSED __attribute((unused))
//#define PETSC_USE_AVX512_KERNELS 1 - Disable for future-proofing.
#define PETSC_USE_BACKWARD_LOOP 1
#define PETSC_USE_CTABLE 1
//#define PETSC_USE_DEBUGGER "gdb"
#define PETSC_USE_INFO 1
#define PETSC_USE_ISATTY 1
#define PETSC_USE_MALLOC_COALESCED 1
#ifndef __APPLE__
# define PETSC_USE_PROC_FOR_SIZE 1
#endif
#define PETSC_USE_REAL_DOUBLE 1
//#define PETSC_USE_SHARED_LIBRARIES 1
#define PETSC_USE_SINGLE_LIBRARY 1
//#define PETSC_USE_SOCKET_VIEWER 1
#define PETSC_USE_VISIBILITY_C 1
#define PETSC_USE_VISIBILITY_CXX 1
#define PETSC_USING_64BIT_PTR 1
#ifdef __APPLE__
# define PETSC_USING_DARWIN 1
#endif
//#define PETSC_USING_F2003 1       - Not using Fortran, shouldn't need this.
//#define PETSC_USING_F90FREEFORM 1 - Not using Fortran, shouldn't need this.
#define PETSC_VERSION_BRANCH_GIT "NO_PETSC_VERSION_BRANCH_GIT"
#define PETSC_VERSION_DATE_GIT "NO_PETSC_VERSION_DATE_GIT"
#define PETSC_VERSION_GIT "NO_PETSC_VERSION_GIT"
#define PETSC__BSD_SOURCE 1
#define PETSC__DEFAULT_SOURCE 1
#define PETSC__GNU_SOURCE 1
```

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17119)* status: 8 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),xuchenhan-tri(platform), missing label for release notes (waiting on @BetsyMcPhail, @jwnimmer-tri, and @xuchenhan-tri)

___
*[`tools/workspace/petsc/stubs/petscconf.h` line 185 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1enZ_p0RvlrqNO1wZ8:-N1in97Z5_fJQ-oPbBpz:b-mnrlw4) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L185)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Drake must work on non-AVX512 machines.
</blockquote></details>

IIUC, *newer* processors may not have AVX-512? I removed this in my latest version. (Feel free to alter the explanatory comment.)
___
*[`tools/workspace/petsc/stubs/petscconf.h` line 201 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17119#-N1enQiWBKvDjgxSdpog:-N1inOin76WDsv_Xme9L:bo2rwq0) ([raw file](https://github.com/robotlocomotion/drake/blob/84cf71a02b9270fac3a054b0c1aa9318a4929648/tools/workspace/petsc/stubs/petscconf.h#L201)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

We don't use the Fortran build.
</blockquote></details>

I suspect these are harmless, but removed in my latest version.

**Comment by jwnimmer-tri** [comment]
Myself and @xuchenhan-tri will take over this upgrade.  It is not an efficient use of your time @mwoehlke-kitware while the process is in its current state.

We'll grab the rebased patch files from here, but we'll re-do the petscconf from scratch.  Most likely, we'll improve petscconf maintenance (without any version upgrade) first in its own PR, and then do the upgrade PR in a second pass.  Since this upgrade is blocked on maintainability changes, I'll close it.

**Pull request closed without merging**
