### PR TITLE
[geometry] Update document of QueryObject about gradients of signed distances

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Related to issue:
- #14789

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20679)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
This is how it looks from `bazel run //doc/doxygen_cxx:build -- --serve --quick drake.geometry`.

http://127.0.0.1:8000/doxygen_cxx/classdrake_1_1geometry_1_1_query_object.html#a0918d61334404a7680145cb882a18d52
 


> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20679#-:-NnBb6aqD_aGeq7ILGte:b-q9zwi)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
+@RussTedrake for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20679#-:-NnBc9bIEMREfmnmnWHM:b-cb1jey)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
:lgtm: thank you.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20679#-:-NncsDXB5UyzUIbMD6bs:bro309g)* status: needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
+@SeanCurtis-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20679#-:-NncsHXrDO02xiSuPN-Z:b-6cxuoj)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a small edit.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20679#-:-NneAcZp2VxQBJ7l0rH_:b-3qeslb)* status: 2 unresolved discussions

___
*[`geometry/query_object.h` line 616 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20679#-Nne8njcEStTR1vu437-:-Nne8njd4Z9hZOVZB6As:b-vkw1zh) ([raw file](https://github.com/RobotLocomotion/drake/blob/040ef2a9b8bec7480579df4453bda44c55df99f1/geometry/query_object.h#L616)):*
> ```objc
>    continuous family of directions.
> 
>

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20679)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform)

___
*[`geometry/query_object.h` line 616 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20679#-Nne8njcEStTR1vu437-:-NnfHNyx1S1iTJdJeSIt:b-9755fa) ([raw file](https://github.com/RobotLocomotion/drake/blob/040ef2a9b8bec7480579df4453bda44c55df99f1/geometry/query_object.h#L616)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I love this note. Very helpful.
</blockquote></details>

Thank you.
___
*[`geometry/query_object.h` line 638 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20679#-Nne9mxP6pGNl4xE7GQd:-NnfHQgP6dX1Cgeee65l:b-ioxi1u) ([raw file](https://github.com/RobotLocomotion/drake/blob/040ef2a9b8bec7480579df4453bda44c55df99f1/geometry/query_object.h#L638)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: The other tables have captions (e.g., the table prior to this is "**_Table 6_**: Support for `T` \= drake::symbolic::Expression." We would want that caption here.

This is particularly important because it's not immediately obvious that this table only applies *when objects are touching*. Without that clarification, a reader might think that they simply get NaN gradients between capsules (or some such thing).

Note: Because this is incredibly primitive, to add the caption "table 7" on this table, all subsequent tables need to have their number advanced (at this point, there's only one).
</blockquote></details>

Done. Thank you.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20679)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform)

**Pull request merged**
