### PR TITLE
Restructure cspace_free_path

### PR DESCRIPTION
**Pull request by AlexandreAmice**
Refactor cspace_free_path to use the cspace_free_structs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19395)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-:-NVA6RCRArD8sXiU6_Js:bctyfxh)* status: LGTM missing from assignee hongkai-dai, missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Checkpoint, sorry for the delay.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-:-NW48eSJ5ysakpMKiboj:b5eth1x)* status: 6 unresolved discussions, LGTM missing from assignee hongkai-dai, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_path.h` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3DOdE4L-YCDxccohz:-NW3DOdE4L-YCDxccoi-:bwywn9y) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.h#L76)):*
> ```objc
>    @param q_star Refer to RationalForwardKinematics for its meaning.
>    @param maximum_path_degree The maximum degree of the polynomial paths
>    this CspaceFreePath will certify.
> ```

Reorder the documentation list, now `plane_order` comes after `maximum_path_degree`.

Also for plane_order, would you like to mention it is order of `mu` in the polynomials?

For maximum_path_degree, is it the degree on the variable `mu`?
___
*[`geometry/optimization/dev/cspace_free_path.h` line 106 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3EP9pEVOhahG4Mc-K:-NW3EP9pEVOhahG4Mc-L:b-abp7bv) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.h#L106)):*
> ```objc
>         : SeparationCertificateProgramBase(),
>           //          certificate{},
>           path{m_path} {
> ```

BTW, since we just copy `m_path` into `path`, I think it is better to use pass-by-value here and then the move semantics
```cc
SeparationCertificaeProgram(std::unordered_map<symbolic::Variable, symbolic::Polynomial> m_path): path{std::move(m_path)} {}
```
___
*[`geometry/optimization/dev/cspace_free_path.h` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3Ekhq2zWkSHm5He4v:-NW3Ekhq2zWkSHm5He4w:b-dm80zi) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.h#L112)):*
> ```objc
>       }
>     }
>     //    SeparationCertificate certificate;
> ```

This line is unused?
___
*[`geometry/optimization/dev/cspace_free_path.cc` line 20 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3gpbQ8Iy0P2E7ey-t:-NW3gpbQ8Iy0P2E7ey-u:b9z8hab) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.cc#L20)):*
> ```cpp
>     const Eigen::Ref<const VectorX<symbolic::Variable>>& s_variables) {
>   std::unordered_map<symbolic::Variable, symbolic::Polynomial> ret;
>   Eigen::Matrix<symbolic::Monomial, Eigen::Dynamic, 1> basis =
> ```

This `basis` should be a const? BTW, we have `const VectorX<symbolic::Monomial> basis` which is shorter than writing out the full `Eigen::Matrix<symbolic::Monomial, Eigen::Dynamic, 1>`
___
*[`geometry/optimization/dev/cspace_free_path.cc` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3jE2cC1LqwRB9Bo2o:-NW3jE2cC1LqwRB9Bo2p:b76q6yv) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.cc#L25)):*
> ```cpp
> 
>   std::size_t i = 0;
>   for (int k = 0; k < s_variables.size(); ++k) {
> ```

Why not to loop over `i`? We could do
```cc
for (int i = 0; i < s_variables.size(); ++i) {
}
```
___
*[`geometry/optimization/dev/cspace_free_path.cc` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3rMI3BZNM0z2rSOPm:-NW3rMI3BZNM0z2rSOPn:b-2zs1m0) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.cc#L30)):*
> ```cpp
>     symbolic::Polynomial::MapType path_monomial_to_coeff;
>     for (int j = 0; j <= maximum_path_degree; ++j) {
>       const symbolic::Variable cur_var{fmt::format("s_{}_{}", i, j)};
> ```

Maybe not to name this variable as `s`? We use `s` for the tangent-configuration space variable, but here this `cur_var` is just the coefficient of the monomial μʲ. Maybe name it `fmt::format("s_{}(mu_{})_coeff", i, j)`?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19395)* status: 5 unresolved discussions, LGTM missing from assignee hongkai-dai, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_path.h` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3DOdE4L-YCDxccohz:-NW8fzjD5AjNLn58aLmW:bsloake) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.h#L76)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Reorder the documentation list, now `plane_order` comes after `maximum_path_degree`.

Also for plane_order, would you like to mention it is order of `mu` in the polynomials?

For maximum_path_degree, is it the degree on the variable `mu`?
</blockquote></details>

`plane_order` is the order of `mu` in the `a(mu)` and `b(mu)`. `maximum_path_degree` is the maximum degree of a polynomial trajectory that we will certify. How do you suggest I clarify the comment? 
___
*[`geometry/optimization/dev/cspace_free_path.h` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3Ekhq2zWkSHm5He4v:-NW8gclh5E7sS3foRWph:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.h#L112)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This line is unused?
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_path.cc` line 20 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3gpbQ8Iy0P2E7ey-t:-NW8gv6L0KJmJ_X6EtEK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.cc#L20)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This `basis` should be a const? BTW, we have `const VectorX<symbolic::Monomial> basis` which is shorter than writing out the full `Eigen::Matrix<symbolic::Monomial, Eigen::Dynamic, 1>`
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_path.cc` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3jE2cC1LqwRB9Bo2o:-NW8guPS1_en5f30tMWl:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.cc#L25)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why not to loop over `i`? We could do
```cc
for (int i = 0; i < s_variables.size(); ++i) {
}
```
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_path.cc` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3rMI3BZNM0z2rSOPm:-NW8gx8X1jRc1wES3cbM:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.cc#L30)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe not to name this variable as `s`? We use `s` for the tangent-configuration space variable, but here this `cur_var` is just the coefficient of the monomial μʲ. Maybe name it `fmt::format("s_{}(mu_{})_coeff", i, j)`?
</blockquote></details>

Done

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19395)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_path.h` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3DOdE4L-YCDxccohz:-NW8lX2M-8RzVp4lv2_p:b-3zp2il) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.h#L76)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

`plane_order` is the order of `mu` in the `a(mu)` and `b(mu)`. `maximum_path_degree` is the maximum degree of a polynomial trajectory that we will certify. How do you suggest I clarify the comment? 
</blockquote></details>

I think my point is that there is more than one possible indeterminate, namely it could be either `mu` or the tangent configuration variable `s`. So I think it would be more clear to clarify that we measure the order of these polynomials in terms of indeterminate `mu`.
___
*[`geometry/optimization/dev/cspace_free_path.h` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3Ekhq2zWkSHm5He4v:-NW8lqRUA25tlvRyKfPh:bxiriad) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.h#L112)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not fixed yet?

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-:-NW8vh4k3YUl8T4yF4aS:bnfp4nl)* status: missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19395)* status: :shipit: complete! all discussions resolved, LGTM from assignee hongkai-dai, exempt from platform review

___
*[`geometry/optimization/dev/cspace_free_path.h` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19395#-NW3Ekhq2zWkSHm5He4v:-NW8qF2v-tCoufycXSS7:b-urihqg) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1e27456c710586012460e8e49982a298dc1f066/geometry/optimization/dev/cspace_free_path.h#L112)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not fixed yet?
</blockquote></details>

Done. Sorry about that.

**Pull request merged**
