### PR TITLE
Provide a citation to last_sha_with_original_matlab

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6258)

### CODE REVIEW

**Comment by RussTedrake** [comment]
:lgtm: .  thanks!

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please (per rotation).

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6258#-:-KlzS1gS6pwvJtXPKOuL:bnfp4nl)*

**Pull request merged**
