### PR TITLE
Make drake_setup_matlab a macro so that Matlab_FOUND remains set

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3904)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Wow, does this really fix it?  

@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
Not quite, unfortunately:
```
Could NOT find Matlab: Found unsuitable version "unknown", but required is at least "7.12"
```

**Comment by david-german-tri** [comment]
Seems like we could just drop the whole minimum version thing.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3904#-:-KUxjKPgJi6zrq4iLaHj:b-dn1dod)*

**Comment by jamiesnape** [comment]
Yes.

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/config.cmake, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3904#-KUxkFwl9ILKBuzvgjCJ:-KUxkFwl9ILKBuzvgjCK:b7zbg7x) ([raw file](https://github.com/robotlocomotion/drake/blob/12930548e47bd686c2719d17c8ca60cfea6d7347/cmake/config.cmake#L34)):*
> ```CMake
>     message(STATUS "MATLAB is disabled.")
>     unset(MATLAB_EXECUTABLE CACHE)
>     unset(Matlab_FOUND CACHE)
> ```

While we're at it, this should not be `CACHE`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3904)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by david-german-tri** [comment]
Hooray, we have 508 tests again.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3904#-:-KUxxy6hxdUD9OntTiFo:bnfp4nl)*

**Pull request merged**
