### PR TITLE
setup: Add dependency on clang-format-9

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We will be switching to this version to re-align all of our supported platforms on a common version.

Towards #13259 and #13236.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13260)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for both reviews, please.

I didn't fire off a macOS CI build, I figured you'd test it locally instead of waiting for Unprovisioned.

Assuming it looks good, feel free to merge it when CI is updated.

**Comment by jwnimmer-tri** [comment]
I might have one more CI image change coming later today.  Maybe hold off on the images to see if we can fold them into one.

**Comment by jamiesnape** [comment]
Provisioning on mac works fine locally. Took a fair number of code changes beyond the obvious to get it actually running (but I figure that is the same on Ubuntu).

**Pull request merged**
