### PR TITLE
Update vendored files from protobuf

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11656)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
It seems to me like both of the first two commits change protobuf.bzl.  I don't understand the distinction of what is happening in each of them, from the commit messages.  Could you elaborate?

**Comment by jamiesnape** [comment]
We list a baseline in README.md, so we should at least be consistent in the history (or else nuke the README.md).

**Comment by jwnimmer-tri** [comment]
What I don't understand is that we mention two separate upstream commits of protobuf, and pull changes from each.  Why is there not just a single upstream commit that this PR upgrades us to?

**Comment by jamiesnape** [comment]
The code in `protobuf-ubsan-fixup.h` was removed from the repo.

**Pull request merged**
