### PR TITLE
Install ffmpeg dependency

### PR DESCRIPTION
**Pull request by tehbelinda**
- and enable html5 video conversion in the pyplot animation jupyter notebook

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12603)

### CODE REVIEW

**Comment by tehbelinda** [comment]
+@ericcousineau-tri for feature review please

**Comment by tehbelinda** [comment]
-@ericcousineau-tri maybe not yet, looks like CI still has trouble finding ffmpeg

**Comment by tehbelinda** [comment]
@ericcousineau-tri  I tried to do some digging, and it looks to me like CI also uses the install_preqs from drake-ci (https://github.com/RobotLocomotion/drake-ci/blob/master/setup/ubuntu/install_prereqs). Should I be adding it here instead?

**Comment by EricCousineau-TRI** [comment]
Ah, oops; did not [click the right publish button](https://drake.mit.edu/jenkins.html#rebuilding-via-reviewable) for Jenkins. Re-posting in GitHub:
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-continuous-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
This is a really, really heavyweight dependency.

**Comment by EricCousineau-TRI** [comment]
Do you think there might be a lighter weight version that would enable the desired workflow? (HTML5 video from matplotlib)

**Comment by EricCousineau-TRI** [comment]
(And just for measure, how heavyweight? How much slowdown will we incur?)

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
I am thinking system dependencies. On Mac alone it adds first order dependencies on  `aom`, `fontconfig``, `freetype, `frei0r, `gnutls, `lame, `libass, `libbluray, `libsoxr, `libvidstab, `libvorbis, `libvpx, `opencore-amr, `openjpeg, `opus, `rtmpdump, `rubberband, `sdl2, `snappy, `speex, `tesseract, `theora, `x264, `x265, `xvid, `xz`. I haven't checked Ubuntu yet.

**Comment by jwnimmer-tri** [comment]
Just glancing at the api -- does `to_jshtml` work, and if so is it less dependency-heavy?

I am also loathe to depend on ffmpeg for such a tiny tweak to an off-the-beaten-path notebook.

**Comment by EricCousineau-TRI** [comment]
Yes, `to_jshtml` works, both under `bazel test ...`, running it directly, and via Binder ([link to notebook](https://mybinder.org/v2/gh/RobotLocomotion/drake/master?filepath=tutorials/pyplot_animation_multibody_plant.ipynb)).

So yeah, our options could be to either conditionally try `to_html()` noting the dependency condition (e.g. `try / catch` with a comment), or just remove it outright. I'm leaning towards the first.

@tehbelinda Would you be OK with the first? If so, I can write the PR that would supersede this one.

**Comment by jwnimmer-tri** [comment]
> ... does to_jshtml work ...?

Oh duh, it's the next cell in the notebook.  And it works for me locally.

Why do we need HTML5 video, exactly?  I read the linked issues but couldn't discern the use case.

**Comment by EricCousineau-TRI** [comment]
Just to show the option, so not necessary, but still nice to indicate?

**Comment by EricCousineau-TRI** [comment]
As a side note, one thing that *is* kinda odd is that `to_html5_video()` requires `ffmpeg`, but `matplotlib`s `FuncAnimation.save("my_file.mp4")` doesn't, and is tested on CI:
https://github.com/RobotLocomotion/drake/blob/3b2c0ce495a540b457253c6c33ce4aecd12c441a/bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py#L58

Dunno why that is...

**Comment by jwnimmer-tri** [comment]
> Just to show the option, so not necessary, but still nice to indicate?

I certainly have no philosophical objection, just a practical one -- a "nice to have" doesn't seem to justify such bloat.

**Comment by EricCousineau-TRI** [comment]
Filed the alternative: #12615

As a follow-up, `to_html5_video()` cannot use `HTMLWriter` since it wants to save `*.m4v`:

And actually, `.save()` does *not* work, since it's not tested via the `--playback` argument (oops!). It errors out stating that `HTMLWriter` can only output `.html` files.

**Comment by tehbelinda** [comment]
Thanks @ericcousineau-tri! The conditional approach sounds reasonable to me. I'll take a look at the other one now and close this one

**Pull request closed without merging**
