### PR TITLE
Define `hash_append` for `drake::optional<T>`.

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8432)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-L8DlPKfTKWoe5XMkS27:-L8DlPKhEUsmmzcLO1Sz:bvdu7xz) (no related file):*
I was going to defect that the hash_append overload should live alongside the class its hashing, not in the area with our hashers for `std::` types.  However, right now drake_optional.h is `:essential` and hash.h is not, so I think that's a good reason to have the function live in hash.h.

So, how about adding a non-Doxygen comment to the function here explaining why this is an atypical situation, both for clarity to readers, and to prevent other classes from adding overloads here for the wrong reasons?

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-L8DmRqzkMN5ijXO1Afa:-L8DmRr0XaZHORkC-yyy:b-cbabqf) (no related file):*
Needs a unit test; not necessarily because we care what the hashed values are, but to ensure that everything compiles.  Testing that two equal wrapped values hash to the same thing seems worthwhile also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8432)*

**Comment by maddog-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-L8DmRqzkMN5ijXO1Afa:-L8DtmWbqoY5VvoUQyjV:b-zd2xct) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs a unit test; not necessarily because we care what the hashed values are, but to ensure that everything compiles.  Testing that two equal wrapped values hash to the same thing seems worthwhile also.
</blockquote></details>

Heh... I had added a `TODO This entire file needs unit-tests.` which I removed before submitting the PR.

Are there already unit-tests for any of `hash.h` somewhere, or should I break new ground with a new file in `common/test/`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8432)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-L8DmRqzkMN5ijXO1Afa:-L8E1H77rfVZ-e0yCcpP:b-m82mnc) (no related file):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Heh... I had added a `TODO This entire file needs unit-tests.` which I removed before submitting the PR.

Are there already unit-tests for any of `hash.h` somewhere, or should I break new ground with a new file in `common/test/`?
</blockquote></details>

 #7357 was where hash_append was added; I guess we didn't add tests directly for its methods in that, though some of the Drake classes that use the `std::` contain helpers did have / still have unit tests.

You could imagine adding the case to `optional_test.cc`, even though the function is in hash.h?  Or I think `hash_test.cc` would be fine also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8432)*

**Comment by maddog-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-L8DlPKfTKWoe5XMkS27:-L8EORhnEK8j1MqClSch:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was going to defect that the hash_append overload should live alongside the class its hashing, not in the area with our hashers for `std::` types.  However, right now drake_optional.h is `:essential` and hash.h is not, so I think that's a good reason to have the function live in hash.h.

So, how about adding a non-Doxygen comment to the function here explaining why this is an atypical situation, both for clarity to readers, and to prevent other classes from adding overloads here for the wrong reasons?
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-L8DmRqzkMN5ijXO1Afa:-L8EOTxUsT0sstJa_A5t:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

 #7357 was where hash_append was added; I guess we didn't add tests directly for its methods in that, though some of the Drake classes that use the `std::` contain helpers did have / still have unit tests.

You could imagine adding the case to `optional_test.cc`, even though the function is in hash.h?  Or I think `hash_test.cc` would be fine also.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8432)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/test/hash_test.cc, line 17 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8432#-L8ERKjTAmggkq2Ru445:-L8ERKjTAmggkq2Ru446:b3l72rc) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe6cd3325f647c512e0c398ffe78a56264bf1ad/common/test/hash_test.cc#L17)):*
> ```cpp
>     const uint8_t* const end = begin + length;
> 
>     std::vector<uint8_t> bytes;
> ```

FYI I'd think this should work, w/o a loop:
```c++
std::vector<uint8_t> bytes(begin, end);
```
via http://en.cppreference.com/w/cpp/container/vector/vector item (4).

---

*[common/test/hash_test.cc, line 37 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8432#-L8EQZl71CZ6qA_tTj_4:-L8EQZl71CZ6qA_tTj_5:btqc6ep) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe6cd3325f647c512e0c398ffe78a56264bf1ad/common/test/hash_test.cc#L37)):*
> ```cpp
>   drake::optional<int> nonempty1(99);
>   drake::optional<int> nonempty2(99);
>   MockHasher hne1;
> ```

BTW _Meta_ While I did figure out `hne` after a moment, its probably pushing GSG's abbreviation allowance a bit too far.

---

*[common/test/hash_test.cc, line 53 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8432#-L8ER0Yc95pNvpcj5COD:-L8ER0Yc95pNvpcj5COE:b-c2qqay) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe6cd3325f647c512e0c398ffe78a56264bf1ad/common/test/hash_test.cc#L53)):*
> ```cpp
>   EXPECT_EQ(he1.record().size(), 1);
> 
>   EXPECT_NE(he1.record(), hne1.record());
> ```

FYI Consider a disclaimer "// Not strictly guaranteed, but highly likely."?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8432#-:-L8ERZ-Z30EGc4lv5kAP:bnfp4nl)*

**Comment by maddog-tri** [comment]
+@soonho-tri for platform review, please.

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/test/hash_test.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-L8ERKjTAmggkq2Ru445:-L8EX7F_cyb1hVG04a9w:b-y651rp) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe6cd3325f647c512e0c398ffe78a56264bf1ad/common/test/hash_test.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I'd think this should work, w/o a loop:
```c++
std::vector<uint8_t> bytes(begin, end);
```
via http://en.cppreference.com/w/cpp/container/vector/vector item (4).
</blockquote></details>

Done --- so it does!

---

*[common/test/hash_test.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-L8EQZl71CZ6qA_tTj_4:-L8EYoL_nkvPFcTuHrwP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe6cd3325f647c512e0c398ffe78a56264bf1ad/common/test/hash_test.cc#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW _Meta_ While I did figure out `hne` after a moment, its probably pushing GSG's abbreviation allowance a bit too far.
</blockquote></details>

Done.

---

*[common/test/hash_test.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-L8ER0Yc95pNvpcj5COD:-L8EatekVtqK4TVxHdIm:ba5bukh) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe6cd3325f647c512e0c398ffe78a56264bf1ad/common/test/hash_test.cc#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider a disclaimer "// Not strictly guaranteed, but highly likely."?
</blockquote></details>

Done, or something to that effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8432#-:-L8EbK5q0j9FRdNEfCeC:bxwr5c8)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8432)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by soonho-tri** [comment]
Nice! :lgtm: 

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8432#-:-L8EpKq4E-lOYS4vbcNV:bfd61qr)*

**Pull request merged**
