### PR TITLE
Consolidate contact information into DiscreteContactPair

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Remove ContactPairKinematics and move its contents into DiscreteContactPair, removing duplicated data along the way.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-:-NqAcOvYBZyCrsXk4CMs:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
Excellent! I like this so much better. :lgtm: 
+@rpoyner-tri for platform review please.

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-:-NqZB5IC-yhhvrSty0tX:b9o7l2f)* status: 6 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`multibody/plant/deformable_driver.h` line 142 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ8zxA14fGF6TclNMO:-NqZ8zxA14fGF6TclNMP:bb7lc54) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.h#L142)):*
> ```objc
>                                   std::vector<MatrixX<T>>* A) const;
> 
>   /* Appends discrete contact pairs where at least one of the body in contact is
> ```

nit,



_Suggestion:_
```objc
 one of the bodies
```
___
*[`multibody/plant/discrete_contact_pair.h` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ1sZ87PcYHU4SHQHd:-NqZ1sZ87PcYHU4SHQHe:bvpu01q) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_contact_pair.h#L66)):*
> ```objc
>   int object_A;
>   /* The id of the second geometry in the contact. */
>   geometry::GeometryId id_B;
> ```

nit, for `id_B` and `object_B` you might want to say something like "Refer to object_A for details"
___
*[`multibody/plant/discrete_update_manager.cc` line 522 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ3aDj7nuSm7kkJSft:-NqZ3aDkA17VtKm3EQm6:blyad34) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_update_manager.cc#L522)):*
> ```cpp
> 
>   for (int icontact = 0; icontact < num_point_contacts; ++icontact) {
>     const DiscreteContactPair<T>& discrete_pair = contact_pairs[icontact];
> ```

minor, in `CalcHydroelasticContactInfo`, this reference is simply called `pair`. I personally like this shorter name. 
___
*[`multibody/plant/discrete_update_manager.cc` line 752 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ3tIF6OMr4T2WluLR:-NqZ3tIF6OMr4T2WluLS:b5ly9ow) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_update_manager.cc#L752)):*
> ```cpp
>   // TODO(xuchenhan-tri): Once we support deformable vs. deformable contact, we
>   // can no longer use this as an early exit criterion.
>   if (plant().num_collision_geometries() == 0) return;
> ```

is there a  way to `DRAKE_DEMAND` this assumption so that this point is easier to find when you add the new feature?
Here and below.
___
*[`multibody/plant/discrete_update_manager.cc` line 921 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ6Me88eu7ZrTiIOOf:-NqZ6Me88eu7ZrTiIOOg:b-gms1fp) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_update_manager.cc#L921)):*
> ```cpp
>           pair.id_A, pair.id_B, default_contact_stiffness(), inspector);
>       // Hunt & Crossley dissipation. Used by the Tamsi, Lagged, and Similar
>       // contact models. Ignored by Sap. See
> ```

minor,
I doubt it, but enumerating approximations can go out of sync if we ever add a new one. I'd leave the enumeration out.
Ditto below



_Code quote:_
```cpp
      // Hunt & Crossley dissipation. Used by the Tamsi, Lagged, and Similar
      // contact models. Ignored by Sap. See
```
___
*[`multibody/plant/sap_driver.cc` line 220 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ8HzH6HU_4MawGUyx:-NqZ8HzH6HU_4MawGUyy:b-av7zk4) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/sap_driver.cc#L220)):*
> ```cpp
>   R_WC.reserve(num_contacts);
>   for (int icontact = 0; icontact < num_contacts; ++icontact) {
>     const auto& contact_pair = contact_pairs[icontact];
> ```

minor, maybe just name `pair`?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typos, questions

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-:-NqZIgWc7tdWC9ZSsb9X:b-6fkc3r)* status: 10 unresolved discussions

___
*[`multibody/plant/deformable_driver.cc` line 218 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZDW885b2S-yzFXGwv:-NqZDW885b2S-yzFXGww:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.cc#L218)):*
> ```cpp
>         EvalFreeMotionTangentMatrixSchurComplement(context, index);
>     /* The schur complement is of the tangent matrix of the force balance
>      whereas the linear dyanmics matrix requires the tangnet matrix of the
> ```

typo



_Suggestion:_
```cpp
dynamics
```
___
*[`multibody/plant/deformable_driver.cc` line 218 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZDaicEdvCZqp-um_c:-NqZDaicEdvCZqp-um_d:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.cc#L218)):*
> ```cpp
>         EvalFreeMotionTangentMatrixSchurComplement(context, index);
>     /* The schur complement is of the tangent matrix of the force balance
>      whereas the linear dyanmics matrix requires the tangnet matrix of the
> ```

typo



_Suggestion:_
```cpp
tangent
```
___
*[`multibody/plant/deformable_driver.cc` line 372 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZDlvJ0MfajBv38bQb:-NqZDlvJ0MfajBv38bQc:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.cc#L372)):*
> ```cpp
>       /* While our discrete solvers might model constraints as compliant, an
>       infinite stiffness indicates to use the stiffest approximation possible
>       without sacrifycing numerical conditioning. SAP will use the "near rigid"
> ```

typo



_Suggestion:_
```cpp
sacrificing 
```
___
*[`multibody/plant/deformable_driver.cc` line 393 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZIOTn-NndGyJ2VKyY:-NqZIOTn-NndGyJ2VKyZ:b-o5fin0) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.cc#L393)):*
> ```cpp
>       // TODO(xuchenhan-tri): Give these fields meaningful values. They are
>       // needed in Lagged and Similar models.
>       const T fn0 = NAN;
> ```

minor I don't understand the pros and cons of injecting NANs here. Are we sure this won't be a future regret? Can we get a bit more explanation?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913)* status: 11 unresolved discussions

___
*[`multibody/plant/sap_driver.cc` line 270 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZQgxd4OeQboRhni3s:-NqZQgxd4OeQboRhni3t:b-ulngzs) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/sap_driver.cc#L270)):*
> ```cpp
>             make_sap_parameters()));
>       } else {
>         problem->AddConstraint(std::make_unique<SapHuntCrossleyConstraint<T>>(
> ```

per @rpoyner-tri's comment, maybe here you can DEMAND that phi0, vn0 and fn0 have non-NAN values?
This will go away with the next PR that enables lagged and similar for deformables, but at least an ok sanity check for now.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913)* status: 4 unresolved discussions

___
*[`multibody/plant/deformable_driver.h` line 142 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ8zxA14fGF6TclNMO:-NqZ_o6D-xTUJsALZTh8:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.h#L142)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit,
</blockquote></details>

Done
___
*[`multibody/plant/deformable_driver.cc` line 218 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZDW885b2S-yzFXGwv:-NqZ_qoK9tonL--IW_ht:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.cc#L218)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done
___
*[`multibody/plant/deformable_driver.cc` line 218 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZDaicEdvCZqp-um_c:-NqZ_xPRA8hlq-CXyYZ-:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.cc#L218)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done
___
*[`multibody/plant/deformable_driver.cc` line 372 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZDlvJ0MfajBv38bQb:-NqZa0CB97Q-VC_ocPDJ:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.cc#L372)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done
___
*[`multibody/plant/deformable_driver.cc` line 393 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZIOTn-NndGyJ2VKyY:-NqZa2jQAj9xXrF-3TiK:b5dvx09) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.cc#L393)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor I don't understand the pros and cons of injecting NANs here. Are we sure this won't be a future regret? Can we get a bit more explanation?
</blockquote></details>

The choice of NAN really comes from existing code. This PR merely moved it from a different location. Following @amcastro-tri's suggestion, I added  
This is going to go away in the next PR anyway.
___
*[`multibody/plant/discrete_contact_pair.h` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ1sZ87PcYHU4SHQHd:-NqZalVX7NKsooivF_Gz:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_contact_pair.h#L66)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, for `id_B` and `object_B` you might want to say something like "Refer to object_A for details"
</blockquote></details>

Done
___
*[`multibody/plant/discrete_update_manager.cc` line 522 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ3aDj7nuSm7kkJSft:-NqZasDuD3tN6-LSOTaJ:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_update_manager.cc#L522)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, in `CalcHydroelasticContactInfo`, this reference is simply called `pair`. I personally like this shorter name.
</blockquote></details>

Done
___
*[`multibody/plant/discrete_update_manager.cc` line 752 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ3tIF6OMr4T2WluLR:-NqZbReK75d50oAeF7yp:bckq8ze) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_update_manager.cc#L752)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

is there a  way to `DRAKE_DEMAND` this assumption so that this point is easier to find when you add the new feature?
Here and below.
</blockquote></details>

I removed it altogether. It doesn't save us much anyway.
___
*[`multibody/plant/discrete_update_manager.cc` line 921 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ6Me88eu7ZrTiIOOf:-NqZbk-b3pQ8Duj7mCmC:b-dz98jb) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_update_manager.cc#L921)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor,
I doubt it, but enumerating approximations can go out of sync if we ever add a new one. I'd leave the enumeration out.
Ditto below
</blockquote></details>

If this goes out of sync that means we have a bug (like we do now with deformable) and it's worth fixing.
___
*[`multibody/plant/sap_driver.cc` line 220 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ8HzH6HU_4MawGUyx:-NqZcDlN4PYBzN0wGIy4:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/sap_driver.cc#L220)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, maybe just name `pair`?
</blockquote></details>

Done
___
*[`multibody/plant/sap_driver.cc` line 270 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZQgxd4OeQboRhni3s:-NqZggc_7K8zqK6LFHRP:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/sap_driver.cc#L270)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

per @rpoyner-tri's comment, maybe here you can DEMAND that phi0, vn0 and fn0 have non-NAN values?
This will go away with the next PR that enables lagged and similar for deformables, but at least an ok sanity check for now.
</blockquote></details>

Done

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913)* status: 4 unresolved discussions

___
*[`multibody/plant/deformable_driver.cc` line 393 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZIOTn-NndGyJ2VKyY:-NqZu3W5-9fBPHDQOW2Z:bs6ixng) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/deformable_driver.cc#L393)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The choice of NAN really comes from existing code. This PR merely moved it from a different location. Following @amcastro-tri's suggestion, I added  
This is going to go away in the next PR anyway.
</blockquote></details>

The choice of NAN really comes from existing code. This PR merely moved it from a different location. Following [@amcastro-tri](https://github.com/amcastro-tri)'s suggestion, I added some guards to show that the NAN values aren't actually used.
This is going to go away in the next PR anyway.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913)* status: 3 unresolved discussions

**Review by xuchenhan-tri — COMMENTED** [review]
@amcastro-tri friendly reminder: this have a few blocking comments left in this PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-:-Nqc_V9m3DRt9iHao7LM:b-ukqgeg)* status: 3 unresolved discussions

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913)* status: 1 unresolved discussion

___
*[`multibody/plant/discrete_update_manager.cc` line 921 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ6Me88eu7ZrTiIOOf:-Nqd87fr1HN-dhOrM75D:b8wfso5) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_update_manager.cc#L921)):*
> such a bug would be fixed at the SapDriver level

Why would that be? In the case of deformable vs rigid with H&C, the bug is exactly at the point of injecting NAN to the DiscreteContactPair where we actually need meaningful values.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913)* status: 1 unresolved discussion

___
*[`multibody/plant/discrete_update_manager.cc` line 921 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ6Me88eu7ZrTiIOOf:-NqdC3g62mmqv-lOUcor:b-al65c3) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_update_manager.cc#L921)):*
I don't follow. My proposed comment here would be:

> Hunt & Crossley dissipation. Ignored, for instance, by Sap. See multibody::DiscreteContactApproximation for details about these contact models"

I believe that if for instance do add a new model that usese H&C dissipation, there'd be no need to make changes to any of this code nor the comment that comes with it.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri

___
*[`multibody/plant/discrete_update_manager.cc` line 921 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20913#-NqZ6Me88eu7ZrTiIOOf:-NqdJbk79BEIbcpUYWvW:bctpdcc) ([raw file](https://github.com/RobotLocomotion/drake/blob/54e5a01671a3d2bcad06d6f1d7cbac0b01d57906/multibody/plant/discrete_update_manager.cc#L921)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I don't follow. My proposed comment here would be:

> Hunt & Crossley dissipation. Ignored, for instance, by Sap. See multibody::DiscreteContactApproximation for details about these contact models"

I believe that if for instance do add a new model that usese H&C dissipation, there'd be no need to make changes to any of this code nor the comment that comes with it.
</blockquote></details>

Makes sense. Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20913)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri

**Pull request merged**
