### PR TITLE
add CspaceFreeRegion class constructor.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18384)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18384#-:-NIBM6xc6tGN4JYs9AF7:b4xbtza)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18384)* status: 10 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_region.h` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NID0YnXBnHrnjwN7c3t:-NID0YnXBnHrnjwN7c3u:by7xgte) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L19)):*
> ```objc
>  */
> enum class SeparatingPlaneOrder {
>   kAffine,  ///< a and b are affine function of s.
> ```

nit: you have an unnecessary `/<` in the comment
___
*[`geometry/optimization/dev/cspace_free_region.h` line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NID14am-wr6XQhYKFw0:-NID14am-wr6XQhYKFw1:b-y0chl) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L79)):*
> ```objc
>           (std::is_same_v<T, double> && std::is_same_v<U, double> &&
>            std::is_same_v<V, double>),
>       "CalcPlane: unsupported scalar type");
> ```

I would make this error more verbose. Perhaps:
`std::format("CalcPlane: unsupported scalar type. Received {},{},{} and expected one of (symbolic::Variable, symbolic::Variable, symbolic::Polynomial), (double, symbolic::Variable, symbolic::Polynomial), or (double, double double)", T, U, V);`
___
*[`geometry/optimization/dev/cspace_free_region.h` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIEwgLe3guJVJH9cN7V:-NIEwgLfAPBLw0YQx655:b-fjj1o1) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L98)):*
> ```objc
>       const T& b_constant = decision_variables(var_count);
>       var_count++;
>       if constexpr (std::is_same_v<T, double> && std::is_same_v<U, double> &&
> ```

Is it worth making this a switch statement for the supported cases?
___
*[`geometry/optimization/dev/cspace_free_region.h` line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIEwuF4-iUV6D7jfJbz:-NIEwuF4-iUV6D7jfJc-:b-v49hyq) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L104)):*
> ```objc
>         return;
>       }
>       if constexpr (std::is_same_v<U, symbolic::Variable> &&
> ```

If we don't incorporate a switch, we can just make this an `else` since we already performed the type check with the `static_assert`
___
*[`geometry/optimization/dev/cspace_free_region.h` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIEyOMr3PqZ4N2MPvXl:-NIEyOMr3PqZ4N2MPvXm:b-6gc3ur) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L146)):*
> ```objc
>    @param plant The plant for which we compute the C-space free regions. It must
>    outlive this CspaceFreeRegion object.
>    @param scene_graph The scene graph has been connected with `plant`. It must
> ```

nit grammar: The scene graph that has been connected with `plant`



_Code quote:_
```objc
The scene graph has been connected with `plant`
```
___
*[`geometry/optimization/dev/cspace_free_region.h` line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIEyrCZE9b5bB9ws4BD:-NIEyrCZE9b5bB9ws4BE:b-pb6ejz) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L160)):*
> ```objc
>   }
> 
>   /** separating_planes()[map_geometries_to_separating_planes.at(geometry1_id,
> ```

nit: this comment doesn't match the style of the other comments. Needs a new line after `/**`
___
*[`geometry/optimization/dev/cspace_free_region.cc` line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIEz8LIDw3CvHA8nKx_:-NIEz8LIDw3CvHA8nKxa:b-232jsg) ([raw file](https://github.com/robotlocomotion/drake/blob/f7d52b50bc23914fe1f7dbb09800a0b19805f882/geometry/optimization/dev/cspace_free_region.cc#L15)):*
> ```cpp
> namespace {
> // Returns true if all the bodies on the kinematics chain from `start` to `end`
> // is welded together (namely all the mobilizer in between are welded).
> ```

nit grammar: `are welded`
___
*[`geometry/optimization/dev/cspace_free_region.cc` line 46 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NII1xMm1pkBHtXNYe2o:-NII1xMm1pkBHtXNYe2p:b-arv2qe) ([raw file](https://github.com/robotlocomotion/drake/blob/f7d52b50bc23914fe1f7dbb09800a0b19805f882/geometry/optimization/dev/cspace_free_region.cc#L46)):*
> ```cpp
>   std::vector<std::pair<const CollisionGeometry*, const CollisionGeometry*>>
>       ret;
>   if (ChainIsWeld(plant, link1, link2)) {
> ```

Could you add a comment saying `\\two links cannot collide if there are only welds between them as they cannot move relative to each other.` I had to briefly pause when I saw this statement to think about why you were returning an empty list.
___
*[`geometry/optimization/dev/test/cspace_free_region_test.cc` line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIIA6uqDfgKUfCwXIC9:-NIIA6uqDfgKUfCwXICA:b-4ql1ks) ([raw file](https://github.com/robotlocomotion/drake/blob/f7d52b50bc23914fe1f7dbb09800a0b19805f882/geometry/optimization/dev/test/cspace_free_region_test.cc#L50)):*
> ```cpp
>   num_planes_expected +=
>       link_geometries.at(plant_->world_body().index()).size() *
>       (link_geometries.at(body_indices_[1]).size() +
> ```

Can you add a comment: `// don't include world_body to body0 as there is only a weld joint between them`
___
*[`geometry/optimization/dev/test/cspace_free_region_test.cc` line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIIAZi95OjlN_1p2tFH:-NIIAZi95OjlN_1p2tFI:bol7geu) ([raw file](https://github.com/robotlocomotion/drake/blob/f7d52b50bc23914fe1f7dbb09800a0b19805f882/geometry/optimization/dev/test/cspace_free_region_test.cc#L68)):*
> ```cpp
>     if (plane.positive_side_geometry->id() <
>         plane.negative_side_geometry->id()) {
>       EXPECT_EQ(geometry_pair.first(), plane.positive_side_geometry->id());
> ```

The docs as far as I recall don't enforce this invariant that the lower geometry id is on the positive side of the `plane`. Should we be testing this in this manner? Wouldn't a simple `||` test do the trick?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18384)* status: 7 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_region.h` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NID0YnXBnHrnjwN7c3t:-NIJO_H67_nGRT26AzDV:bttro98) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L19)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: you have an unnecessary `/<` in the comment
</blockquote></details>

That `/<` is actually required for documenting enum class. It will generate a table in doxygen. See https://github.com/RobotLocomotion/drake/blob/abe2e88df2a9b3d55bdc6c0e689650cb956a67db/solvers/mathematical_program.h#L478-L483
___
*[`geometry/optimization/dev/cspace_free_region.h` line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NID14am-wr6XQhYKFw0:-NIJTETf9onK2zp9M6xf:bm0t3ho) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L79)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would make this error more verbose. Perhaps:
`std::format("CalcPlane: unsupported scalar type. Received {},{},{} and expected one of (symbolic::Variable, symbolic::Variable, symbolic::Polynomial), (double, symbolic::Variable, symbolic::Polynomial), or (double, double double)", T, U, V);`
</blockquote></details>

Done.

static_assert expects string literals, so I cannot use std::format here.
___
*[`geometry/optimization/dev/cspace_free_region.h` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIEwgLe3guJVJH9cN7V:-NIJTQghC9GAyKo3y_z1:b3aswgy) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L98)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Is it worth making this a switch statement for the supported cases?
</blockquote></details>

Here we want to do SFINAE based on the static type (the code compiles differently based on the type of T, U, V). Hence you see the `constexpr` here.
___
*[`geometry/optimization/dev/cspace_free_region.h` line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIEwuF4-iUV6D7jfJbz:-NIJTrSB1MZsHi2brZ7J:b-6owzft) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L104)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

If we don't incorporate a switch, we can just make this an `else` since we already performed the type check with the `static_assert`
</blockquote></details>

This is SFINAE based on the template variable type, not the typical `if ... else ...` branch. Note we have `constexpr` after `if`, namely the compiler will generate different code based on the template type `T, U, V`, instead of generating the same code but jumping to different branches in the execution as in typical `if ... else`.
___
*[`geometry/optimization/dev/cspace_free_region.h` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIEyOMr3PqZ4N2MPvXl:-NIK6_G628-qFmJQBqHF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ec22aa0e4511c7b0b8accb6ae2c2ea214dbf7918/geometry/optimization/dev/cspace_free_region.h#L146)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit grammar: The scene graph that has been connected with `plant`
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_region.cc` line 46 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NII1xMm1pkBHtXNYe2o:-NIKCenh3aq-TULwmRdO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7d52b50bc23914fe1f7dbb09800a0b19805f882/geometry/optimization/dev/cspace_free_region.cc#L46)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Could you add a comment saying `\\two links cannot collide if there are only welds between them as they cannot move relative to each other.` I had to briefly pause when I saw this statement to think about why you were returning an empty list.
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/cspace_free_region_test.cc` line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIIA6uqDfgKUfCwXIC9:-NIKCpqw4GQ6KhmyTUQk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7d52b50bc23914fe1f7dbb09800a0b19805f882/geometry/optimization/dev/test/cspace_free_region_test.cc#L50)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can you add a comment: `// don't include world_body to body0 as there is only a weld joint between them`
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/cspace_free_region_test.cc` line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIIAZi95OjlN_1p2tFH:-NIKCz938Wr7cL0L9Y1D:b-6o8aa0) ([raw file](https://github.com/robotlocomotion/drake/blob/f7d52b50bc23914fe1f7dbb09800a0b19805f882/geometry/optimization/dev/test/cspace_free_region_test.cc#L68)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

The docs as far as I recall don't enforce this invariant that the lower geometry id is on the positive side of the `plane`. Should we be testing this in this manner? Wouldn't a simple `||` test do the trick?
</blockquote></details>

We don't enforce that the lower geometry id is on the positive side, we don't test that in this code either. As you see, there is an `if` statement above, and there is an `else` branch below.

`geometry_pair` is a `SortedPair` object, hence geometry_pair.first() alsways have lower id than geometry_pair.second. With this `if... else` branch we tested the two cases `positive_side_geometry->id() < negative_side_geometry->id()` and `positive_side_geometry->id() > negative_side_geometry->id()`.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: minus some spelling issues

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18384#-:-NINlBew-5wLAmYk3T8o:bn63sib)* status: 2 unresolved discussions, needs platform reviewer assigned (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 33 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NINjEBV6wwFlrkhou7u:-NINjEBV6wwFlrkhou7v:bi0c1lc) ([raw file](https://github.com/robotlocomotion/drake/blob/acffed4f374abc2cf99c9c0ccd7838da043d428c/geometry/optimization/dev/cspace_free_polytope.h#L33)):*
> ```objc
> 
>   /**
>    @param plant The plant for which we compute the C-space free regions. It must
> ```

nit: regions -> polytope
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 48 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NINjfWnBQ1esNU0f3-I:-NINjfWo87FL2SlAEWSP:b-2fhtrk) ([raw file](https://github.com/robotlocomotion/drake/blob/acffed4f374abc2cf99c9c0ccd7838da043d428c/geometry/optimization/dev/cspace_free_polytope.cc#L48)):*
> ```cpp
>   if (ChainIsWeld(plant, link1, link2)) {
>     // Two links cannot collide if there are only welded joints between them as
>     // they cannot ove relative to each other. Return an empty vector.
> ```

nit spelling: ove ->move

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18384)* status: needs platform reviewer assigned (waiting on @hongkai-dai)

**Comment by RussTedrake** [comment]
+@russtedrake for platform review

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18384)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai)

___
*[`multibody/rational/rational_forward_kinematics.h` line 123 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIOvs390nSGo9wrCoxd:-NIOvs390nSGo9wrCoxe:b-btmq2t) ([raw file](https://github.com/robotlocomotion/drake/blob/5b2edde0af74f0fa8b29bede7ec28e7cbf60dd7d/multibody/rational/rational_forward_kinematics.h#L123)):*
> ```objc
>    the weld joint), then the s index is set to -1.
>    */
>   [[nodiscard]] const std::vector<int> map_mobilizer_to_s_index() const {
> ```

needs a test.  it can be very simple, but we want to have something that calls it from outside of dev.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18384)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

___
*[`multibody/rational/rational_forward_kinematics.h` line 123 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18384#-NIOvs390nSGo9wrCoxd:-NIP5UWm0j1TH718paJn:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/5b2edde0af74f0fa8b29bede7ec28e7cbf60dd7d/multibody/rational/rational_forward_kinematics.h#L123)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

needs a test.  it can be very simple, but we want to have something that calls it from outside of dev.
</blockquote></details>

Done. Good call.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  I only carefully reviewed the non-dev components, as requested.  Great to see this coming along!

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18384#-:-NISDFFxB3tOVCLAieSt:b-tim2lw)* status: :shipit: complete! all discussions resolved, LGTM from assignees AlexandreAmice,RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
