### PR TITLE
multibodyplant: tell scenegraph my name when registering as a source

### PR DESCRIPTION
**Pull request by RussTedrake**
As discussed with @gizatt and @SeanCurtis-TRI in #13971.  The change does seem painless, and only an improvement.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14024)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14024#-:-MGXor5q4pgawgQ77faH:b-t5m2ic)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

One caveat -- I think it's worth calling out *somewhere* in documentation (probably the documentation for `RegisterAsSourceForSceneGraph`) that the plant's name will be passed to SceneGraph where it propagates through to other domains (e.g., visualization), therefore, it is highly recommended to give the plant a recognizable name; the default name won't always be convenient.

I also wonder about the utilities that generate the plant/scene graph pair and what those names look like.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14024#-:-MGdYnyl3-HU3vNB6jZ9:bcxhea4)* status: needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
Done (Added to the doc).  

Those utilities you refer to do explicitly set the names "plant" and "scene_graph".  https://github.com/RobotLocomotion/drake/blob/master/multibody/plant/multibody_plant.cc#L3039

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14024#-:-MGdeG0M6C70UFklXTio:b-od50ad)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14024)* status: needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
+@rpoyner-tri for platform review, please; per the schedule.  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14024#-:-MGdsdLn223HK5WOI62T:b8r32ql)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14024#-:-MGiVoCo5yLWtLmahplB:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
