### PR TITLE
Add support for lcm-java, lcm-spy, and custom lcm_structs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a checkpoint of working, incremental progress, and I think will meet the need for quite a while. Down the road, the lcm_foo_library calls in particular could be done more elegantly.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4684)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

+@soonho-tri are you able to feature review?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4684#-:-K_lmpfeWlafPhEBL1J9:bsybgrd)*

**Comment by soonho-tri** [comment]
> +@soonho-tri are you able to feature review?

Sure.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4684#-:-K_maYwJ6R-JpYK1176A:b-b9cph0)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4684)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4684#-:-K_oRYJDL2yOxE3iKy9z:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm.bzl, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4684#-K_oR__hOHriwiwx2uoL:-K_oR__irpfp1nRJvXO1:b-h4y0yk) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c74d6d0f1bea8f895c1cc082d4453a4a93247c/tools/lcm.bzl#L160)):*
> ```Python
>         lcm_structs=None,
>         **kwargs):
>     """Declares a java_library on message classes generated from `*.lcm` files.
> ```

META: what's our Python coding-style for the "descriptive vs. imperative" comment? (i.e. "Declares" vs. "Declare")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4684)*

**Comment by jwnimmer-tri** [comment]
*[tools/lcm.bzl, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4684#-K_oR__hOHriwiwx2uoL:-K_oSmK1f27TW561buC-:bd2p83g) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c74d6d0f1bea8f895c1cc082d4453a4a93247c/tools/lcm.bzl#L160)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META: what's our Python coding-style for the "descriptive vs. imperative" comment? (i.e. "Declares" vs. "Declare")
</blockquote></details>

#4663 would be authoritative, but it's not clear to me if it intends to incorporate PEP 257 via its reference in PEP 8.  So I don't think we have a rule yet.

PEP 257 mandates "Declare".  For C++, cppguide mandates "Declares".  Possibly being forced to use both will drive us insane?  Anyway, sounds like a new coding standards discussion / issue, not a PR topic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4684)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm.bzl, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4684#-K_oR__hOHriwiwx2uoL:-K_oTuPU-NLHJLeP1FSu:b-6fl7vk) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c74d6d0f1bea8f895c1cc082d4453a4a93247c/tools/lcm.bzl#L160)):*
> Anyway, sounds like a new coding standards discussion / issue, not a PR topic?

Sure. I just want to know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4684)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm.bzl, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4684#-K_oR__hOHriwiwx2uoL:-K_oV-xnIkhnS_C879P1:b-neua7m) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c74d6d0f1bea8f895c1cc082d4453a4a93247c/tools/lcm.bzl#L160)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> Anyway, sounds like a new coding standards discussion / issue, not a PR topic?

Sure. I just want to know.
</blockquote></details>

BTW I would personally be thrilled to eliminate the distinction from our style guides for every language.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4684#-:-K_oVwHo9nHr49PGhHor:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Oops.  I was just about to retest it, since the last build was 2 days old.  Probably fine, I'll just watch the Continuous builds.

**Comment by soonho-tri** [comment]
Oops. I thought you wanted this asap.

**Comment by jwnimmer-tri** [comment]
I thought I did, but then noticed the staleness.  No big deal.

**Pull request merged**
