### PR TITLE
Move pick and place configuration out of dev

### PR DESCRIPTION
**Pull request by sammy-tri**
Also adds the ability to specify the grasping force.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7699)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@avalenzu for feature review (the functional changes are in separate commits from the move if that helps)

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-:-L22K8g-ckGUVshJSYZu:b-n3jnz)*

**Comment by avalenzu** [comment]
:lgtm: +@sherm1 for platform review.

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/action.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L25ZMOX5-RGwk0oEcEN:-L25ZMOX5-RGwk0oEcEO:b-eqvvmf) ([raw file](https://github.com/robotlocomotion/drake/blob/af0d2ff9bbb8ece23aa59229bfa15fe9041a5063/examples/kuka_iiwa_arm/pick_and_place/action.cc#L77)):*
> ```cpp
>   msg->utime = est_state.get_wsg_time() * 1e6;
>   msg->target_position_mm = 100;  // Maximum aperture for WSG
>   msg->force = 40;  // Force in center of WSG range
> ```

BTW, why wasn't this 0 to begin with? It seems strange to ask for a force to be exerted when the gripper is open.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L25ZkpYQNZVTjPJtnf9:-L25ZkpYQNZVTjPJtnfA:b4f4x9x) ([raw file](https://github.com/robotlocomotion/drake/blob/a39988b6a51b5fbbd38d0db8210fad72a9fbc944/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L49)):*
> ```objc
>   /// inputs.
>   int num_tables{0};
>   /// Gripping force to apply (in newtons).
> ```

BTW s/newtons/Newtons

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L25ZuZK3Vj63F6jLqpv:-L25ZuZK3Vj63F6jLqpw:b4f4x9x) ([raw file](https://github.com/robotlocomotion/drake/blob/a39988b6a51b5fbbd38d0db8210fad72a9fbc944/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L65)):*
> ```protobuf
>     // The name of the end-effector body in the robot.
>     required string end_effector_name = 3;
>     // The gripping force to apply (in newtons).
> ```

BTW s/newtons/Newtons

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-:-L25a3H1aEjvGKf1lx1G:bol08qe)*

**Comment by jwnimmer-tri** [comment]
@avalenzu when tagging platform review for moving out of dev, it might be worth reminding the reviewer (@sherm1 today) to review the entire file (i.e., expanded in full in reviewable), not just its diffs.  When we platform reviewers have many PRs in our review queue, we might not immediately connect the dots for how the PR title relates to the reviewable File Matrix settings we need.

**Comment by avalenzu** [comment]
Good point, @jwnimmer-tri! Thanks.

@sherm1, as Jeremy mentioned, this PR moves files out of `dev/`. The following files need platform review on their entire contents
- `examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto`
- `examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration_parsing.cc`
- `examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_configuration_parsing_test.cc`
- `examples/kuka_iiwa_arm/pick_and_place/configuration/*` (These are configuration files though.)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-:-L25jVhtkmz1l6j-v9LN:b-sahdz9)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/action.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L25ZMOX5-RGwk0oEcEN:-L25mPc2nEYE5Dr62oLI:byf4p1k) ([raw file](https://github.com/robotlocomotion/drake/blob/af0d2ff9bbb8ece23aa59229bfa15fe9041a5063/examples/kuka_iiwa_arm/pick_and_place/action.cc#L77)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, why wasn't this 0 to begin with? It seems strange to ask for a force to be exerted when the gripper is open.
</blockquote></details>

When opening the gripper, the commanded force still controls how the motor is driven while moving to the target position.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L25ZkpYQNZVTjPJtnf9:-L25mJfn4udqDSJAodUY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a39988b6a51b5fbbd38d0db8210fad72a9fbc944/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L49)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW s/newtons/Newtons
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L25ZuZK3Vj63F6jLqpv:-L25mND0RRhZi1IomMr0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a39988b6a51b5fbbd38d0db8210fad72a9fbc944/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L65)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW s/newtons/Newtons
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699)*

**Comment by avalenzu** [comment]
Reviewed 1 of 26 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/kuka_iiwa_arm/pick_and_place/action.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L25ZMOX5-RGwk0oEcEN:-L25nXcqV3Dir0OLj0fw:b-4hvi0m) ([raw file](https://github.com/robotlocomotion/drake/blob/af0d2ff9bbb8ece23aa59229bfa15fe9041a5063/examples/kuka_iiwa_arm/pick_and_place/action.cc#L77)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

When opening the gripper, the commanded force still controls how the motor is driven while moving to the target position.
</blockquote></details>

Got it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699)*

**Comment by sherm1** [comment]
Thanks for pointing out the extra code to review -- I definitely wouldn't have noticed that.
Platform :lgtm: pending a few small BTWs -- ptal.

---

Reviewed 24 of 26 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/action.h, line 130 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27f4nTA-tVLAluHmic:-L27f4nUuacAMhvQA-SA:b-1bjdvf) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/action.h#L130)):*
> ```objc
>    */
>   void OpenGripper(const WorldState& est_state,
>                    double grip_force,
> ```

BTW why does the open command need a grip_force?

---

*[examples/kuka_iiwa_arm/pick_and_place/action.h, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27fDH7MT3r2TyeNYOf:-L27fDH7MT3r2TyeNYOg:btkbg7j) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/action.h#L137)):*
> ```objc
>    * driver to fully close.
>    */
>   void CloseGripper(const WorldState& est_state,
> ```

BTW comment should explain what is done here with the grip_force (not obvious to me). Is it a maximum?

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27fXspBXpnDen_dK0S:-L27fXspBXpnDen_dK0T:b-j0innx) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L50)):*
> ```objc
>   int num_tables{0};
>   /// Gripping force to apply (in Newtons).
>   double grip_force{40.};
> ```

BTW I believe I saw a lot of 42s elsewhere. Just want to mention that in case you meant to put that here as well.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27Lg_yTOuSk3fznVhK:-L27Lg_yTOuSk3fznVhL:b-63qmt0) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L9)):*
> ```protobuf
>  // without a default value are required.
> 
> // Next ID: 3
> ```

BTW why is this ID 3 (and the next two also)?

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27MVt9GBl3n94iIAVf:-L27MVt9GBl3n94iIAVg:b-fnlosq) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L13)):*
> ```protobuf
>     // Position.
>     // DEFAULT: (0, 0, 0)
>     repeated double xyz = 1;
> ```

BTW (sorry for protobuf ignorance) This appears to assume "repeated" means "0 or more" (i.e., optional), is that right?

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27Lo_iFTLliNW_WqRB:-L27Lo_iFTLliNW_WqRC:b-g7qbc) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L16)):*
> ```protobuf
>     // Orientation in SpaceXYZ Euler angles.
>     // DEFAULT: (0, 0, 0)
>     repeated double rpy = 2;
> ```

BTW is a 4-space indent our standard for protobuf? It's 2 spaces in code.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration_parsing.h, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27b6PO030vL_Kbge0a:-L27b6PO030vL_Kbge0b:b-5voac2) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration_parsing.h#L16)):*
> ```objc
> using TaskIndex = TypeSafeIndex<class TaskTag>;
> 
> pick_and_place::PlannerConfiguration ParsePlannerConfigurationOrThrow(
> ```

BTW the functions here need Doxygen comments (could be short ones).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-:-L27ZAbOdcjO6lRnPf7R:b-ggmfuo)*

**Comment by avalenzu** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27Lg_yTOuSk3fznVhK:-L2L8YccOqQsHShF3ucR:blsx6mr) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why is this ID 3 (and the next two also)?
</blockquote></details>

Each field in a protobuf message has a unique integer id (the number after the equals sign in the field definition). It's customary have these IDs be the natural numbers and to note the next available ID in the comment for each message definition. These messages have two fields each, so the next available ID is 3.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27MVt9GBl3n94iIAVf:-L2L9RKjuZdDfnDcArbu:b-87rmoq) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW (sorry for protobuf ignorance) This appears to assume "repeated" means "0 or more" (i.e., optional), is that right?
</blockquote></details>

That is correct.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L2L9JUjfCRHzumHMqAe:-L2L9JUjfCRHzumHMqAf:bvay1jb) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L55)):*
> ```protobuf
> }
> 
> // Next ID: 4
> ```

BTW This needs to be updated to 5. Maybe it's not worth following this convention?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699)*

**Comment by sammy-tri** [comment]
Comments addressed.

---

Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/action.h, line 130 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27f4nTA-tVLAluHmic:-L2LTgA6zXt5tAeKDFFb:bjcwam8) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/action.h#L130)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why does the open command need a grip_force?
</blockquote></details>

The commanded force still has an effect on how the motor is driven by the gripper firmware (since there's nothing being pushed against (I hope!) this really just affects the velocity of the fingers while opening).  (added comment)

---

*[examples/kuka_iiwa_arm/pick_and_place/action.h, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27fDH7MT3r2TyeNYOf:-L2LUfeuHoJzDOB223wO:b-bizqh8) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/action.h#L137)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW comment should explain what is done here with the grip_force (not obvious to me). Is it a maximum?
</blockquote></details>

Added comment.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27fXspBXpnDen_dK0S:-L2LUm2IeTE4ze1upnMw:b-e2a5iw) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I believe I saw a lot of 42s elsewhere. Just want to mention that in case you meant to put that here as well.
</blockquote></details>

The 42's were to validate in the test that the default (40) is properly overridden.  I think the default here is fine.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27Lo_iFTLliNW_WqRB:-L2LVFEWMNhX5nQPhfG4:b-9yt2cn) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is a 4-space indent our standard for protobuf? It's 2 spaces in code.
</blockquote></details>

All of the other `.proto` files in drake seem to use 4 space indents.  I believe this is also what we use for python code in drake.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L2L9JUjfCRHzumHMqAe:-L2LVNcSir8nkdYbEQoh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L55)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW This needs to be updated to 5. Maybe it's not worth following this convention?
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration_parsing.h, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-L27b6PO030vL_Kbge0a:-L2LXFpfub5wdEADLG38:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4784ad7164babdcf8a9e2fe78d6b7b87444f8810/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration_parsing.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the functions here need Doxygen comments (could be short ones).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699#-:-L2LXHRTixy6DrgvkPpB:bel95ya)*

**Comment by avalenzu** [comment]
Reviewed 2 of 26 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699)*

**Comment by sherm1** [comment]
Reviewed 2 of 26 files at r1, 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7699)*

**Pull request merged**
