### PR TITLE
redo the pid controller. 

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
0. cleaned up the pid controller. 
1. updated some comments in pid_controlled_systems. which I think was wrong.
2. updated the state_feedback_controller_base interface.

also the iiwa demo sim runs 3 times faster..

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6326)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature review. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-:-KmTEO7wgC_vrKPw72wU:b-6l9dh6)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-:-KmUo36LIqlhMxDzqvHf:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri for platform review.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-:-KmWXcyil1a1iBA-Bgy4:bpk00vl)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX1IvARC2SbnZqV6-_:-KmX1IvARC2SbnZqV6-a:bmhlql9) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h#L36)):*
> ```objc
> class ManipulatorInverseDynamicsController
>     : public systems::ModelBasedController<double>,
>       public systems::Diagram<double> {
> ```

This seems to violate https://google.github.io/styleguide/cppguide.html#Multiple_Inheritance

---

*[drake/systems/controllers/BUILD, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX0so77D1oX9XfnKuM:-KmX0so77D1oX9XfnKuN:bntcwu7) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/BUILD#L85)):*
> ```Python
>         "//drake/systems/primitives:adder",
>         "//drake/systems/primitives:constant_vector_source",
>         "//drake/systems/primitives:demultiplexer",
> ```

unused?  (it may be here because of an unused include in pid_controlled_system.h)

---

*[drake/systems/controllers/BUILD, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX11Pt784y1xQ-6t2f:-KmX11Puuh7t3NS21_be:bntcwu7) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/BUILD#L86)):*
> ```Python
>         "//drake/systems/primitives:constant_vector_source",
>         "//drake/systems/primitives:demultiplexer",
>         "//drake/systems/primitives:gain",
> ```

unused?  (it may be here because of an unused include in pid_controlled_system.h)

---

*[drake/systems/controllers/inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX0P0KzMMRn452Szjy:-KmX0P0LrD5YX3IrUEl2:bm6yryf) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/inverse_dynamics_controller.h#L36)):*
> ```objc
>  */
> template <typename T>
> class InverseDynamicsController : public ModelBasedController<T>,
> ```

This use of multiple inheritance seems to violate https://google.github.io/styleguide/cppguide.html#Multiple_Inheritance

---

*[drake/systems/controllers/pid_controller.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX-PONOb6ohDbz0NFV:-KmX-PONOb6ohDbz0NFW:b-p9lp16) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/pid_controller.cc#L67)):*
> ```cpp
>       (kd_.array() * controlled_state_diff.tail(num_controlled_q_).array())
>           .matrix() +
>       (ki_.array() * state_block.array()).matrix();
> ```

BTW I feel like a comment somewhere describing the system's continuous state would make what's happening with the I term significantly more obvious.

---

*[drake/systems/controllers/pid_controller.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmWyXJvmeKWVd5IKcGY:-KmWyXJwlkWyRSwMM1QA:bx948h7) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/pid_controller.h#L29)):*
> ```objc
>  */
> template <typename T>
> class PidController : public StateFeedbackController<T>, public LeafSystem<T> {
> ```

As noted elsewhere, this doesn't quite comply with https://google.github.io/styleguide/cppguide.html#Multiple_Inheritance (I think only do to the lack of the `Interface` suffix in the name of `StateFeedbackController`)

---

*[drake/systems/controllers/pid_controller.h, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmWylIAiyqq-RRVpAVT:-KmWylIAiyqq-RRVpAVU:bjvmcwr) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/pid_controller.h#L89)):*
> ```objc
> 
>   /**
>    * Returns the portional gain vector.
> ```

typo "portional"

---

*[drake/systems/controllers/pid_controller.h, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmWz5LpzZDE49U_YQzw:-KmWz5LrTjWCqUJvr3G3:b-6mwu7a) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/pid_controller.h#L151)):*
> ```objc
>   }
> 
>   PidController<symbolic::Expression>* DoToSymbolic() const override;
> ```

BTW it seems like the `DoFoo*` methods usually stay in the `protected` section of classes which inherit from `LeafSystem`.  I don't think this is a requirement, but it seems odd to me to move them to private when they will be called by the parent class.

---

*[drake/systems/controllers/state_feedback_controller_base.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmWyAMvo3eRZ9qhhaIr:-KmWyAMwf0yll0Px_XOS:b-nsqfeu) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/state_feedback_controller_base.h#L15)):*
> ```objc
>  */
> template <typename T>
> class StateFeedbackController {
> ```

I think we should rename the class and file to `StateFeedbackControllerInterface` to comply with the requirements in https://google.github.io/styleguide/cppguide.html#Multiple_Inheritance  (there are other ways to comply, like making this class inherit from `LeafSystem`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-:-KmX1Rk6Fdec_vVdS2IH:bvb1a6z)*

**Comment by siyuanfeng-tri** [comment]
Review status: 11 of 23 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX1IvARC2SbnZqV6-_:-KmX51HucNSbNKEb_TmC:bjhqxp8) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h#L36)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This seems to violate https://google.github.io/styleguide/cppguide.html#Multiple_Inheritance
</blockquote></details>

yeah, jeremy pointed this to me. But I can't think of a better way of doing this. Also I think this instance falls in the "one is pure interface".

---

*[drake/systems/controllers/BUILD, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX0so77D1oX9XfnKuM:-KmXA0guK1h3EYOFq3mb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/BUILD#L85)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?  (it may be here because of an unused include in pid_controlled_system.h)
</blockquote></details>

Done.

---

*[drake/systems/controllers/BUILD, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX11Pt784y1xQ-6t2f:-KmXDRPKPQfUXtbBie_5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/BUILD#L86)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?  (it may be here because of an unused include in pid_controlled_system.h)
</blockquote></details>

Done.

---

*[drake/systems/controllers/inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX0P0KzMMRn452Szjy:-KmX5g-0ONEMrqJEJkHm:brx2yk6) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/inverse_dynamics_controller.h#L36)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This use of multiple inheritance seems to violate https://google.github.io/styleguide/cppguide.html#Multiple_Inheritance
</blockquote></details>

same as above. 

---

*[drake/systems/controllers/pid_controller.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX-PONOb6ohDbz0NFV:-KmX7pYWRquCLT4ZOohQ:bj86wxb) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/pid_controller.cc#L67)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I feel like a comment somewhere describing the system's continuous state would make what's happening with the I term significantly more obvious.
</blockquote></details>

added a one liner above. 

---

*[drake/systems/controllers/pid_controller.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmWyXJvmeKWVd5IKcGY:-KmX8E8SqIgT8fCs-yUC:b-7tfmjp) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/pid_controller.h#L29)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

As noted elsewhere, this doesn't quite comply with https://google.github.io/styleguide/cppguide.html#Multiple_Inheritance (I think only do to the lack of the `Interface` suffix in the name of `StateFeedbackController`)
</blockquote></details>

added

---

*[drake/systems/controllers/pid_controller.h, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmWylIAiyqq-RRVpAVT:-KmX8NIbbNBgY9yXAyQV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/pid_controller.h#L89)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

typo "portional"
</blockquote></details>

Done.

---

*[drake/systems/controllers/pid_controller.h, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmWz5LpzZDE49U_YQzw:-KmX8TIiQD1OjjMvlWRE:b5ls4im) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/pid_controller.h#L151)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW it seems like the `DoFoo*` methods usually stay in the `protected` section of classes which inherit from `LeafSystem`.  I don't think this is a requirement, but it seems odd to me to move them to private when they will be called by the parent class.
</blockquote></details>

alright. 

---

*[drake/systems/controllers/state_feedback_controller_base.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmWyAMvo3eRZ9qhhaIr:-KmX8i3myr21fQR8r-f5:btwtkf5) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/systems/controllers/state_feedback_controller_base.h#L15)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think we should rename the class and file to `StateFeedbackControllerInterface` to comply with the requirements in https://google.github.io/styleguide/cppguide.html#Multiple_Inheritance  (there are other ways to comply, like making this class inherit from `LeafSystem`).
</blockquote></details>

added Interface. 
I can't make this from any system, because this will have both diagram and leafsystem derived versions. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326)*

**Comment by sammy-tri** [comment]
part way through second pass

---

Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-:-KmXRiE4dgzEcN57wUlN:b-owlmgn)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX1IvARC2SbnZqV6-_:-KmXTArKs2TWwcZ_gNaH:bnfcm9y) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h#L36)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

yeah, jeremy pointed this to me. But I can't think of a better way of doing this. Also I think this instance falls in the "one is pure interface".
</blockquote></details>

I'm not sure I would call ModelBasedController a pure interface (it's only got one public method and it's concrete).  You could have *InverseDynamicsController own a ModelBasedController and re-export get_robot_for_control if they had any users which cared about it, though I don't like that either.  Honestly, the whole class is maybe 10 lines of code, it's only got two users, and zero code seems to use the derived class through the base type.  Will think about it for a bit longer and update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX1IvARC2SbnZqV6-_:-KmXXkT2kFqB5yrG2jt8:bs0dwtr) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h#L36)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure I would call ModelBasedController a pure interface (it's only got one public method and it's concrete).  You could have *InverseDynamicsController own a ModelBasedController and re-export get_robot_for_control if they had any users which cared about it, though I don't like that either.  Honestly, the whole class is maybe 10 lines of code, it's only got two users, and zero code seems to use the derived class through the base type.  Will think about it for a bit longer and update.
</blockquote></details>

This thing is somewhat useful.
Now suppose I am on a multiple inheritance rampage, and I have the ModelBasedController be its own thing, and I have triple inheritance here, would that be totally insane? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX1IvARC2SbnZqV6-_:-KmXwrOZoEomkTIKatab:b-vh1v9i) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h#L36)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

This thing is somewhat useful.
Now suppose I am on a multiple inheritance rampage, and I have the ModelBasedController be its own thing, and I have triple inheritance here, would that be totally insane? 
</blockquote></details>

Adding more than one interface as a base class isn't itself in violation of the style guide, so making ModelBasedController no longer be a StateFeedbackControllerInterface wouldn't make things any worse...    was that the idea?

In my comment above I forgot that ModelBasedController inherited from StateFeedbackControllerInterface...   so the result would be that anything which inherited from ModelBasedController was actually claiming to be, basically, an implementer of StateFeedbackControllerInterface with some helper stuff for a ModelBasedController mixed in.

What's the useful part of ModelBasedController?  The ability for other classes to have a ref/ptr to a ModelBasedController and call `get_robot_for_control()` on it?  Or it helps with implementing model based controllers?  If it's the latter then the inverse dynamics controller could own a ModelBasedController as a member instead of it being the parent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX1IvARC2SbnZqV6-_:-KmY10Z2Bk3zwsjdUnrC:b-dc34wl) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h#L36)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Adding more than one interface as a base class isn't itself in violation of the style guide, so making ModelBasedController no longer be a StateFeedbackControllerInterface wouldn't make things any worse...    was that the idea?

In my comment above I forgot that ModelBasedController inherited from StateFeedbackControllerInterface...   so the result would be that anything which inherited from ModelBasedController was actually claiming to be, basically, an implementer of StateFeedbackControllerInterface with some helper stuff for a ModelBasedController mixed in.

What's the useful part of ModelBasedController?  The ability for other classes to have a ref/ptr to a ModelBasedController and call `get_robot_for_control()` on it?  Or it helps with implementing model based controllers?  If it's the latter then the inverse dynamics controller could own a ModelBasedController as a member instead of it being the parent?
</blockquote></details>

It's the second case, but having a "controller" own a ModelBasedController seems really odd to me. I'd rather get rid of ModelBasedController entirely, and just store the RBT unique_ptr independently. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX1IvARC2SbnZqV6-_:-KmY8pDYDLaOjAdCdmk8:b-m760x0) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h#L36)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

It's the second case, but having a "controller" own a ModelBasedController seems really odd to me. I'd rather get rid of ModelBasedController entirely, and just store the RBT unique_ptr independently. 
</blockquote></details>

I was leaning toward that idea too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326)*

**Comment by siyuanfeng-tri** [comment]
Review status: 15 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-KmX1IvARC2SbnZqV6-_:-KmYE3Lv9P8b61sOW3ju:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db1705a1f63983811904923ef91cfe32c6916517/drake/examples/QPInverseDynamicsForHumanoids/system/manipulator_inverse_dynamics_controller.h#L36)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I was leaning toward that idea too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326)*

**Comment by sammy-tri** [comment]
:lgtm: pending CI

@drake-jenkins-bot retest this please

---

Reviewed 11 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326#-:-KmYUxH7b-B1oFlpqXso:b7f5xib)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6326)*

**Pull request merged**
