### PR TITLE
Solve with first available solver

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15319)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15319#-:-Mds9qYgEow1L-vT-BT8:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
@russtedrake I think this PR can resolve the CI failure in #15315 , we can specify the solver to be gurobi/mosek/scs/csdp, which would not call IPOPT for an SOCP.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15319#-:-MdsABIE9vANzOys_3in:b-kwp6b9)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: I almost recommended a few small things, but always ended up deciding that I liked your version better.  Very nice.  Thanks!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15319#-:-MdwqBTf0j-PrtZhhseb:b-wm1lw7)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15319#-:-MdwqV5T6AOxHdv7ntbb:bppyoqq)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Comment by RussTedrake** [comment]
___
*[solvers/solve.h, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15319#-MdwtNqWEs0W87eM3tuc:-MdwtNqWEs0W87eM3tud:bilfv7h) ([raw file](https://github.com/robotlocomotion/drake/blob/450c7bb6c8479e94ffbfbe53fb0b533ee7cca2ad/solvers/solve.h#L55)):*
> ```objc
>     const MathematicalProgram& prog,
>     const std::vector<const SolverInterface*>& solvers,
>     const std::optional<Eigen::VectorXd>& initial_guess,
> ```

can you add std::nullopt as the default arguments for this and solver_options?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15319)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

___
*[solvers/solve.h, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15319#-MdwtNqWEs0W87eM3tuc:-Mdwv8WDC0g6fgEU0EHK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/450c7bb6c8479e94ffbfbe53fb0b533ee7cca2ad/solvers/solve.h#L55)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

can you add std::nullopt as the default arguments for this and solver_options?
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with some minor comments.

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15319#-:-Mdx3T3t4QSjY2DMTK4m:bu95ptd)* status: 4 unresolved discussions (waiting on @hongkai-dai and @RussTedrake)

___
*[solvers/solve.cc, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15319#-Mdx1RGXAACD8kAmFB4p:-Mdx1RGXAACD8kAmFB4q:b-itqvst) ([raw file](https://github.com/robotlocomotion/drake/blob/f87c0aa9cc3d6c8e67458f68e49283dd2f013bbd/solvers/solve.cc#L50)):*
> ```cpp
>   }
>   throw std::runtime_error("SolveWithFirstAvailableSolver: the solvers " +
>                            solver_names + "are not available or enabled.");
> ```

BTW consider `SolveWithFirstAvailableSolver(): `. Parentheses are conventional for functions and distinguishes them from classes. (Not a defect though.)

BTW consider rewording: "none of the solvers [solver_names] is available or enabled." (Side benefit is that the message reads better if there is only one solver on the list.)
___
*[solvers/test/solve_test.cc, line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15319#-Mdx2ORADrY6ysfoJbLQ:-Mdx2ORADrY6ysfoJbLR:buyiydh) ([raw file](https://github.com/robotlocomotion/drake/blob/f87c0aa9cc3d6c8e67458f68e49283dd2f013bbd/solvers/test/solve_test.cc#L73)):*
> ```cpp
>     if (gurobi_solver.available() && gurobi_solver.enabled()) {
>       EXPECT_EQ(result.get_solver_id(), gurobi_solver.solver_id());
>     } else if (scs_solver.available() && scs_solver.enabled()) {
> ```

nit: this test is not necessary since we're in a block where we know this to be true if gurobi is not there
___
*[solvers/test/solve_test.cc, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15319#-Mdx2tfk7_E325Y07HOy:-Mdx2tfk7_E325Y07HOz:b-mc3n2n) ([raw file](https://github.com/robotlocomotion/drake/blob/f87c0aa9cc3d6c8e67458f68e49283dd2f013bbd/solvers/test/solve_test.cc#L82)):*
> ```cpp
>         SolveWithFirstAvailableSolver(prog, {&gurobi_solver}, std::nullopt,
>                                       std::nullopt),
>         std::runtime_error, ".* are not available or enabled.");
> ```

BTW fix to match error message if you change it.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15319)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @hongkai-dai)

___
*[solvers/solve.cc, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15319#-Mdx1RGXAACD8kAmFB4p:-MdxC_FO0MwSWQbzPuwS:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/f87c0aa9cc3d6c8e67458f68e49283dd2f013bbd/solvers/solve.cc#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider `SolveWithFirstAvailableSolver(): `. Parentheses are conventional for functions and distinguishes them from classes. (Not a defect though.)

BTW consider rewording: "none of the solvers [solver_names] is available or enabled." (Side benefit is that the message reads better if there is only one solver on the list.)
</blockquote></details>

Done. Thanks!
___
*[solvers/test/solve_test.cc, line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15319#-Mdx2ORADrY6ysfoJbLQ:-MdxCmCa5Li5F-HZCE2b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f87c0aa9cc3d6c8e67458f68e49283dd2f013bbd/solvers/test/solve_test.cc#L73)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this test is not necessary since we're in a block where we know this to be true if gurobi is not there
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15319)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
A better partition of functionality would have been ...

```c++
SolverInterface* SelectFirstAvailableSolver(const std::vector<SolverInterface*>& solvers);
```

... which could live in `solver_interface.h`.

The new function as written here blends "Solve" into the picture, so must replicate the details of "Solve"'s optional arguments into the picture, and forces the user to use the return-by-value feature instead of the return-output-argument which is much more performant.

**Comment by hongkai-dai** [comment]
Makes sense. I will send a new PR to add `SelectFirstAvailableSolver` to `choose_best_solver.h`, and rewrite SolveWithFirstAvailableSolver with `SelectFirstAvailableSolver`.

**Comment by jwnimmer-tri** [comment]
If the better function gets added, then I think SolveWithFirstAvailableSolver continuing to exist does more harm than good.

**Comment by hongkai-dai** [comment]
Makes sense. I will send that PR in a minute

**Pull request merged**
