### PR TITLE
October 2022 updates

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #18023.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18028)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@BetsyMcPhail for feature review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18028#-:-NDYKQ9w2b2wdKvIsFGj:b-ykw85)* status: LGTM missing from assignee jwnimmer-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform +(release notes: fix).

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18028#-:-NDYcoTn33ml2jPWhp7y:b-96i86x)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Pull request merged**
