### PR TITLE
Port to new CMake-ified LCM, bot_core_lcmtypes

### LINKED ISSUE #2341: lcm-java: 'c' flag requires manifest or input files to be specified
Transcient issue with OS X builds.

**Command**: `"/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/jar" "-cf" "/Users/yosemite/workspace/mac-clang-continuous-matlab/pod-build/externals/lcm/lcm-prefix/src/lcm-build/lcm-java/lcm.jar" "@java_class_filelist"`

**Directory**: `/Users/yosemite/workspace/mac-clang-continuous-matlab/pod-build/externals/lcm/lcm-prefix/src/lcm-build/lcm-java/CMakeFiles/lcm-java.dir`

**Output**:
```
'c' flag requires manifest or input files to be specified!
Usage: jar {ctxui}[vfmn0PMe] [jar-file] [manifest-file] [entry-point] [-C dir] files ...
Options:
    -c  create new archive
    -t  list table of contents for archive
    -x  extract named (or all) files from archive
    -u  update existing archive
    -v  generate verbose output on standard output
    -f  specify archive file name
    -m  include manifest information from specified manifest file
    -n  perform Pack200 normalization after creating a new archive
    -e  specify application entry point for stand-alone application 
        bundled into an executable jar file
    -0  store only; use no ZIP compression
    -P  preserve leading '/' (absolute path) and ".." (parent directory) components from file names
    -M  do not create a manifest file for the entries
    -i  generate index information for the specified jar files
    -C  change to the specified directory and include the following file
If any file is a directory then it is processed recursively.
The manifest file name, the archive file name and the entry point name are
specified in the same order as the 'm', 'f' and 'e' flags.
```

https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=19421

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Replace use of `lcmtypes.cmake` with functions provided by upstream LCM Use file. Fix compilation of JAR (now requires specifying dependency JAR's rather than relying on modification of the global `CLASSPATH`). Remove references to `lcmtype_agg_hpp` target; the aggregate headers are created at configure time, and the per-type headers are generated at the same time as the C sources for the lcmtypes library (which, being itself a dependency of consumers of the C++ headers, should suffice to ensure that said headers exist before trying to build sources requiring them).

This isn't a complete fix for #2483 or #2486, as it doesn't address libbot (do we still care? should we just drop libbot?) or anything outside of the LCM chain, but it's a step in the right direction. Also note that, for now, both lcm and bot_core_lcmtypes are using drake repositories rather than upstream, although this was already the case for both.

This is expected to fix #2341.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2582)

### CODE REVIEW

**Comment by RussTedrake** [comment]
We still use libbot for lcmgl.  That's all -- but it's useful.  We could definitely consider extracting/replacing that functionality (possibly even moving it into the bot_core_lcmtypes repo?)

**Comment by david-german-tri** [comment]
This seems to be failing on CI.  (I have a number of  other questions, which I'll hold because you might resolve them in the course of fixing the build.)

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-:-KKi-mpLwVbqyYUEyvvs:-1593379611)*

**Comment by mwoehlke-kitware** [comment]
jenkins: retest this please

**Comment by mwoehlke-kitware** [comment]
There is a bug here that I didn't introduce... the errors like:

    In file included from /home/ubuntu/workspace/experimental/9111c4bf/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc:6:
    /home/ubuntu/workspace/experimental/9111c4bf/drake/../drake/systems/plants/RigidBodySystem.h:4:10: fatal error: 'drake/drakeRBSystem_export.h' file not found

...are occurring because LCM is "not found"¹, which causes the drakeRBSystem library to not be built. However, some artifacts that depend on it are not being disabled, as they should be in this case. I can't find where this test is coming from, however; everything works fine on my systems, which makes me suspect the problem(s) must be in an external repository not enabled in my configuration? (The file in the above example does not exist in the drake repository AFAICT.)

(¹ ...which is a different bug that I'll fix shortly.)

**Comment by jwnimmer-tri** [comment]
@mwoehlke-kitware Are you merged up to HEAD of master?  That test was added recently.

/cc @liangfok who was involved with adding that test IIRC.

**Comment by mwoehlke-kitware** [comment]
> Are you merged up to HEAD of master? That test was added recently.

Ack... I *looked* in current master! Somehow I added a `drake_` to my search (`drake_rigid_body_test`), however, and thus failed to find it :cry:.

Once my current build finishes, I'll look at rebasing and fixing the without-LCM case... (Meanwhile, I fixed the 'lcm "not found"' problem, so hopefully the CI will improve.)

**Comment by mwoehlke-kitware** [comment]
...of course, I wonder if we should just make LCM required...

**Comment by liangfok** [comment]
Yes, I added `rigid_body_system_test.cc` recently.

Even if I remove the line `#include "drake/drakeRBSystem_export.h"` from this file, `RigidBodySystem.h` contains this line.

Is `drake/drakeRBSystem_export.h` only generated when LCM is enabled?

**Comment by jwnimmer-tri** [comment]
I wonder if the `CMakeLists.txt` dependency from `drakeRBSystem` on `drakeLCMSystem` might be vestigial?  On first glance, I don't see why it would be needed.

**Comment by mwoehlke-kitware** [comment]
> Is drake/drakeRBSystem_export.h only generated when LCM is enabled?

Correct. Also, the corresponding library doesn't exist if LCM is not found.

> I wonder if the CMakeLists.txt dependency from drakeRBSystem on drakeLCMSystem might be vestigial?

Maybe; I can try (probably tomorrow) removing the dependency and see if things still build...

**Comment by mwoehlke-kitware** [comment]
> Even if I remove the line #include "drake/drakeRBSystem_export.h" from this file[...]

Actually, you (i.e. the test) probably should not be including that directly. Someone other than the [headers for the] library itself including a library's export headers seems either superfluous or fishy...

**Comment by liangfok** [comment]
Oops. I was mistaken `rigid_body_system_test.cc` is not including `drake/drakeRBSystem_export.h`. Instead, it is including `drake/systems/plants/RigidBodySystem.h`, which is then including it.

I'm now looking into _what_ in the `drakeRBSystem` library requires LCM.

**Comment by mwoehlke-kitware** [comment]
> Oops. I was mistaken; `rigid_body_system_test.cc` is not including `drake/drakeRBSystem_export.h`. Instead, it is including `drake/systems/plants/RigidBodySystem.h`, which is then including it.

Ah. That's fine, then :smile:.

> I'm now looking into what in the `drakeRBSystem` library requires LCM.

That dependency is removed in the current version of this branch (see 64ead6a621d1). Seems to be working okay...

**Comment by liangfok** [comment]
Nice! I will stop by investigation then. Thanks for the note.

**Comment by mwoehlke-kitware** [comment]
I may be pushing "scratch" commits for a while to try to get CI cleaned up; adding "do not merge" label as a note to not merge until I have a chance to clean these up.

**Comment by mwoehlke-kitware** [comment]
CI passing, ready for serious review...

**Comment by mwoehlke-kitware** [comment]
@jwnimmer-tri, don't know who's on review duty ATM; please review or assign to someone else who can review; thanks!

**Comment by jwnimmer-tri** [comment]
I believe that @david-german-tri said he was going to take a look.  David, you can bounce back to me if you want.

@mwoehlke-kitware Note that there are apparently git conflict that need to be resolved.

**Comment by david-german-tri** [comment]
I'm on it, thanks for the ping.

**Comment by liangfok** [comment]
I left some minor non-blocking comments and one minor question.

---

Reviewed 8 of 18 files at r4, 5 of 11 files at r5, 5 of 8 files at r7, 5 of 5 files at r8.
Review status: 16 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Acrobot/test/CMakeLists.txt, line 1 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMlRGAgpsSlDEMdDuj:-KLMlRGBzqrEcAOkLdJM:1036519133) ([raw file](https://github.com/robotlocomotion/drake/blob/3fc338ab09c1770bf39702771220300e4363459c/drake/examples/Acrobot/test/CMakeLists.txt#L1)):*
> ```CMake
> if(lcm_FOUND AND GTEST_FOUND)
> ```

BTW, since we're modifying this line, might as well remove the `and GTEST_FOUND` since Google Test is a required dependency.

---

*[drake/examples/Cars/test/CMakeLists.txt, line 1 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMlcqTrnChinng6rfM:-KLMlcqTrnChinng6rfN:1036519133) ([raw file](https://github.com/robotlocomotion/drake/blob/3fc338ab09c1770bf39702771220300e4363459c/drake/examples/Cars/test/CMakeLists.txt#L1)):*
> ```CMake
> if(GTEST_FOUND AND lcm_FOUND AND NOT WIN32)
> ```

BTW, since we're modifying this line, might as well remove the `and GTEST_FOUND` since Google Test is a required dependency.

---

*[drake/examples/Pendulum/test/CMakeLists.txt, line 1 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMlgop4T7agaGtrhp-:-KLMlgop4T7agaGtrhp0:1036519133) ([raw file](https://github.com/robotlocomotion/drake/blob/3fc338ab09c1770bf39702771220300e4363459c/drake/examples/Pendulum/test/CMakeLists.txt#L1)):*
> ```CMake
> if(lcm_FOUND AND GTEST_FOUND)
> ```

BTW, since we're modifying this line, might as well remove the `and GTEST_FOUND` since Google Test is a required dependency.

---

*[drake/examples/Quadrotor/test/CMakeLists.txt, line 1 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMljJC2hE8dU8QAKT2:-KLMljJC2hE8dU8QAKT3:1036519133) ([raw file](https://github.com/robotlocomotion/drake/blob/3fc338ab09c1770bf39702771220300e4363459c/drake/examples/Quadrotor/test/CMakeLists.txt#L1)):*
> ```CMake
> if(lcm_FOUND AND GTEST_FOUND)
> ```

BTW, since we're modifying this line, might as well remove the `and GTEST_FOUND` since Google Test is a required dependency.

---

*[drake/lcmtypes/CMakeLists.txt, line 1 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMm3q7itRWfeAy7NIz:-KLMm3q7itRWfeAy7NJ-:-2047899464) ([raw file](https://github.com/robotlocomotion/drake/blob/3fc338ab09c1770bf39702771220300e4363459c/drake/lcmtypes/CMakeLists.txt#L1)):*
> ```CMake
> include(${LCM_USE_FILE})
> ```

BTW, just curious: does this change https://github.com/RobotLocomotion/drake/pull/2671?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-:-KLMmME-OmxdnClpMSpH:177749663)*

**Comment by mwoehlke-kitware** [comment]
> BTW, just curious: does this change #2671?

Yes. LCM binding generation is quite different now (see added `lcmtypes/CMakeLists.txt`); effectively, this addresses the first part of that TODO. TBH I didn't understand the second part; in e.g. bot_core_lcmtypes, all LCM types are defined in one place. What would be the purpose of changing that? Having LCM types all over the place and in many libraries seems like it would be more complicated...?

> might as well remove the `GTEST_FOUND`...

I'm inclined to do that everywhere as a separate commit, since it is present in quite a few places. I did it locally; if that works for you, I'll push it as a separate PR once this lands.

**Comment by david-german-tri** [comment]
This looks like a huge improvement, but I need to understand the details better before we merge it.  Here's a first pass of questions.  

A complete build would help - I'm going to switch to `clang` locally to get one, but please do fix `gcc`.

---

Review status: 16 of 23 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 203 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMpYyyBzsDmP8w6Wyc:-KLMpYyyBzsDmP8w6Wyd:-144137622) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/CMakeLists.txt#L203)):*
> ```CMake
> set(lcm_ADDITIONAL_CMAKE_CONFIGURE_ARGS -DBUILD_SHARED_LIBS=ON)
> if(WITH_GTK)
>   set(lcm_ADDITIONAL_CMAKE_CONFIGURE_ARGS ${lcm_ADDITIONAL_CMAKE_CONFIGURE_ARGS} -DCMAKE_PREFIX_PATH=${CMAKE_CURRENT_SOURCE_DIR}/externals/gtk/gtk3)
> ```

Why is this needed?  As far as I can tell, there is no reference to `gtk3` in Drake previously.

---

*[drake/examples/Acrobot/test/CMakeLists.txt, line 1 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMlRGAgpsSlDEMdDuj:-KLMmn9Em6_RSy9SknD0:1260960) ([raw file](https://github.com/robotlocomotion/drake/blob/3fc338ab09c1770bf39702771220300e4363459c/drake/examples/Acrobot/test/CMakeLists.txt#L1)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, since we're modifying this line, might as well remove the `and GTEST_FOUND` since Google Test is a required dependency.
</details>
FYI, I disagree with @liangfok.  This PR is a high risk buildsystem change, let's keep it focused.

---

*[drake/examples/Cars/CMakeLists.txt, line 27 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMqVPCzS-nBJXlHZwj:-KLMqVPCzS-nBJXlHZwk:1792913383) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/examples/Cars/CMakeLists.txt#L27)):*
> ```CMake
>   add_dependencies(drakeCars drake_lcmtypes_hpp)
>   add_executable(simple_car_demo simple_car_demo.cc)
>   target_link_libraries(simple_car_demo drakeCars drakeRBSystem drakeLCMSystem threads)
> ```

Is it possible to get `threads` transitively from `drakeLCMSystem`, instead of directly declaring it everywhere?

---

*[drake/lcmtypes/CMakeLists.txt, line 54 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMz5WjWC87Q74MWDm1:-KLMz5WjWC87Q74MWDm2:-828718346) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/lcmtypes/CMakeLists.txt#L54)):*
> ```CMake
> 
> install(FILES ${c_install_headers} DESTINATION include/lcmtypes)
> install(FILES ${cpp_install_headers} DESTINATION include/lcmtypes/drake)
> ```

Locally, this (and the stuff below) doesn't seem to be happening for me.  That might be because the `gcc` build is bailing out early for other reasons (see CI).

---

*[drake/lcmtypes/CMakeLists.txt, line 67 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMuB_t0diH8-CJuYxT:-KLMuB_t0diH8-CJuYxU:1900317468) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/lcmtypes/CMakeLists.txt#L67)):*
> ```CMake
> if(JAVA_FOUND)
>   if(NOT TARGET lcm-java)
>     message(FATAL_ERROR "lcm-java not found; was LCM build with Java support?")
> ```

s/build/built

---

*[drake/systems/CMakeLists.txt, line 11 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMqnHLgJ9MzDYdOsqc:-KLMqnHLgJ9MzDYdOsqd:1065622612) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/systems/CMakeLists.txt#L11)):*
> ```CMake
>   target_link_libraries(drakeLCMSystem lcm)
>   if(WIN32)
>     target_link_libraries(drakeLCMSystem ws2_32)
> ```

How did we get by without this previously?

---

*[drake/systems/plants/CMakeLists.txt, line 161 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMr-QiiwjreE3iHvEW:-KLMr-QiiwjreE3iHvEX:-160416956) ([raw file](https://github.com/robotlocomotion/drake/blob/d57f429a75347ea58f7792be34585d39bd5a1063/drake/systems/plants/CMakeLists.txt#L161)):*
> ```CMake
> if(LCM_FOUND)
>   add_library_with_exports(LIB_NAME drakeRBSystem SOURCE_FILES RigidBodySystem.cpp)
>   target_link_libraries(drakeRBSystem drakeRBM drakeLCMSystem drakeOptimization drakeRigidBodyConstraint)
> ```

So this dependency on `drakeLCMSystem` was just extraneous?  Good catch!

---

*[externals/bot_core_lcmtypes, line 1 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLN-ht_9EWnQQ4Rp1DL:-KLN-ht_9EWnQQ4Rp1DM:2009228436) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/externals/bot_core_lcmtypes#L1)):*
> ```
> Subproject commit 0434090f6f54228c35514f7c9216e3bf1e003ea3
> ```

Just to confirm - this is the changes that openhumanoids rejected in https://github.com/openhumanoids/bot_core_lcmtypes/pull/18, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-:-KLN00C46TkS6LQWEFLK:-572634830)*

**Comment by liangfok** [comment]
> TBH I didn't understand the second part; in e.g. bot_core_lcmtypes, all LCM types are defined in one place. What would be the purpose of changing that? Having LCM types all over the place and in many libraries seems like it would be more complicated...?

I suppose this is a philosophical question of whether LCM types should be co-located with the code that uses it. I suppose either way is OK.

---

Review status: 16 of 23 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-:-KLN1vv-ocm4n8iDT4X3:1746662656)*

**Comment by mwoehlke-kitware** [comment]
> A complete build would help - I'm going to switch to clang locally to get one, but please do fix gcc.

Oh, for crying out... those errors are *not* caused by this branch. I already fixed one round of these (#2632)... sigh...

Okay, done venting... I'll look into them, but like #2632 I expect to fix them on a different branch. (I think the problem is that somehow, previously, gtest was being `-isystem`d, and isn't any more. IOW, they're latent, unrelated issues that are being revealed by this branch "by accident".

**Comment by mwoehlke-kitware** [comment]
Review status: 15 of 23 files reviewed at latest revision, 6 unresolved discussions.

---

*[CMakeLists.txt, line 203 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMpYyyBzsDmP8w6Wyc:-KLN3iThLLUoSlZoVCE8:-221021782) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/CMakeLists.txt#L203)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why is this needed?  As far as I can tell, there is no reference to `gtk3` in Drake previously.
</details>
I'm not actually sure how lcm built before on windows — specifically, how it was able to find glib2. This is how it finds it now that it isn't using pkg-config.

(Actually... I take that back, it might have been a hard-coded relative path in the lcm-pod repo. Which... well, no comment :smile:.)

---

*[drake/examples/Cars/CMakeLists.txt, line 27 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMqVPCzS-nBJXlHZwj:-KLN4LXiKekhYDbLfdSv:363658750) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/examples/Cars/CMakeLists.txt#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Is it possible to get `threads` transitively from `drakeLCMSystem`, instead of directly declaring it everywhere?
</details>
Suuuuure... I didn't do that originally because drakeLCMSystem isn't actually *using* it; it becomes needed when someone calls the (inline) `runLCM` function. If you're being strict about the actual users linking to the libraries they use...

That said, I did consider doing exactly that anyway. I could go either way.

(I'm also not sure why it's even *needed*; we aren't using pthread directly, but `std::thread`. This honestly feels to me like a bug in the standard library or even the compiler. Even more interestingly, it *isn't* needed on my Fedora 20 system...)

---

*[drake/lcmtypes/CMakeLists.txt, line 54 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMz5WjWC87Q74MWDm1:-KLN5UQplhATjt_aaLyG:830184297) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/lcmtypes/CMakeLists.txt#L54)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Locally, this (and the stuff below) doesn't seem to be happening for me.  That might be because the `gcc` build is bailing out early for other reasons (see CI).
</details>
Probably; if the build fails, the install won't happen.

---

*[drake/lcmtypes/CMakeLists.txt, line 67 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMuB_t0diH8-CJuYxT:-KLN6fszQ_VZ0w3-xaYU:-187432188) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/lcmtypes/CMakeLists.txt#L67)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> s/build/built
</details>
Fixed; thanks!

---

*[drake/systems/CMakeLists.txt, line 11 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMqnHLgJ9MzDYdOsqc:-KLN6kUhy5UsnjG5vcmU:-1807592080) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/systems/CMakeLists.txt#L11)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> How did we get by without this previously?
</details>
...because the pkg-config for lcm gives it a fairly large list of convenient-but-not-necessary link libraries. Current CMake best practice is to keep those to an absolute minimum to minimize overlinking; accordingly, the CMake-ified lcm has *no* interface link libraries.

---

*[externals/bot_core_lcmtypes, line 1 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLN-ht_9EWnQQ4Rp1DL:-KLN77xWsXAC6zPcPuYK:2101406455) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/externals/bot_core_lcmtypes#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Just to confirm - this is the changes that openhumanoids rejected in https://github.com/openhumanoids/bot_core_lcmtypes/pull/18, right?
</details>
Right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2582)*

**Comment by david-german-tri** [comment]
Yikes - great call!  `ninja.build` is rife with the following:

```
-isystem /media/davidgerman/ssd-build/drake-build/install/include
```
However, this PR causes CMake to generate `-I` instead of `-isystem` for some build targets, such as `n_ary_system_test`.  We need to figure out where that `-isystem` is coming from in the first place.  I'll open a separate issue.

**Comment by mwoehlke-kitware** [comment]
> this PR causes CMake to generate `-I` instead of `-isystem` for some build targets

One can argue either way which is "correct" :smile:. On the one hand, drake's own headers obviously shouldn't be "system", but stuff like gtest...?

>  We need to figure out where that `-isystem` is coming from in the first place.

The usual suspect is `include_directories(SYSTEM ...)`, but I don't see any of that.

I'm going to try to make a PR soon to fix the instances that are tripping. I'd be fine holding this until that lands and cleans up the CI.

**Comment by david-german-tri** [comment]
Review status: 15 of 23 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/Cars/CMakeLists.txt, line 27 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMqVPCzS-nBJXlHZwj:-KLNAWfZcImwtbtGAAfo:-1485318334) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/examples/Cars/CMakeLists.txt#L27)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Suuuuure... I didn't do that originally because drakeLCMSystem isn't actually *using* it; it becomes needed when someone calls the (inline) `runLCM` function. If you're being strict about the actual users linking to the libraries they use...
> 
> That said, I did consider doing exactly that anyway. I could go either way.
> 
> (I'm also not sure why it's even *needed*; we aren't using pthread directly, but `std::thread`. This honestly feels to me like a bug in the standard library or even the compiler. Even more interestingly, it *isn't* needed on my Fedora 20 system...)
</details>
That makes sense - I agree with leaving as-is.  Thanks for the explanation.

---

*[drake/systems/CMakeLists.txt, line 11 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMqnHLgJ9MzDYdOsqc:-KLND7jklW7VRjOlWbv3:367057188) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/systems/CMakeLists.txt#L11)):*
> because the pkg-config for lcm gives it a fairly large list of convenient-but-not-necessary link libraries

Just to confirm I'm understanding: this is true on Windows specifically?  `lcm.pc` seems pretty terse on Linux.

---

*[externals/bot_core_lcmtypes, line 1 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLN-ht_9EWnQQ4Rp1DL:-KLNDE_ZtYfOT-dOaS0U:191773374) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/externals/bot_core_lcmtypes#L1)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Right.
</details>
OK.  In a future change, we should move this repo from your personal fork into RobotLocomotion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2582)*

**Comment by mwoehlke-kitware** [comment]
> I suppose this is a philosophical question of whether LCM types should be co-located with the code that uses it. I suppose either way is OK.

Sure. FWIW, a big reason why I'm inclined to keep them all together is that the binding generation is moderately complex; you're not just generating some C++ headers, you're also generating a JAR and a Python package. Moreover, there are issues trying to generate LCM types for a single package piecemeal; in order to move them closer to point-of-use, you'd need to make each bundle use a separate package name.

**Comment by mwoehlke-kitware** [comment]
Review status: 15 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/CMakeLists.txt, line 11 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLMqnHLgJ9MzDYdOsqc:-KLNGxE1HwBEn2US2v61:70721871) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/drake/systems/CMakeLists.txt#L11)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> > because the pkg-config for lcm gives it a fairly large list of convenient-but-not-necessary link libraries
> 
> Just to confirm I'm understanding: this is true on Windows specifically?  `lcm.pc` seems pretty terse on Linux.
</details>
Sorry, previous comment was slightly misleading... `ws2_32` actually comes from `glib-2.0.pc`, but is picked up transitively through the `Requires: glib-2.0` in `lcm.pc`.

---

*[externals/bot_core_lcmtypes, line 1 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-KLN-ht_9EWnQQ4Rp1DL:-KLNHtfybzQe1G2-NcQ2:2002031514) ([raw file](https://github.com/robotlocomotion/drake/blob/5f8cd852e399d261871eb971e86fef5c868cdc7e/externals/bot_core_lcmtypes#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> OK.  In a future change, we should move this repo from your personal fork into RobotLocomotion.
</details>
NP; since the old repo was jhoare, it's at least no worse than before :smile:.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2582)*

**Comment by mwoehlke-kitware** [comment]
@david-german-tri, I just pushed #2685, which might be useful to you for local testing purposes.

**Comment by mwoehlke-kitware** [comment]
jenkins: retest this please

#2685 is merged, hopefully that will fix the CI.

**Comment by david-german-tri** [comment]
Fixes #2681

**Comment by mwoehlke-kitware** [comment]
CI pass! @david-german-tri, is the ws2_32 discussion satisfactorily resolved? Any other issues?

**Comment by david-german-tri** [comment]
I can build this locally, and it behaves the way I'd expect, so :lgtm:.  Nice PR!

---

Review status: 15 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2582#-:-KLNhLfteAQ663JYol2q:-1549187427)*

**Comment by jwnimmer-tri** [comment]
If I am reading the Continuous build output correctly, this PR broke all msvc builds except for ninja + release + non-matlab (i.e., Studio, Debug, and Matlab are all broken).

**Comment by liangfok** [comment]
Searching for "fatal error" in [this example Win32-continuous-matlab console log](https://drake-jenkins.csail.mit.edu/job/windows-msvc-32-continuous-matlab/185/consoleFull), it looks like the first fatal error is:

```
02:09:21 C:\projects\ReYFE7LH\drake\..\drake/systems/LCMSystem.h(9): fatal error C1083: Cannot open include file: 'lcmtypes/drake/lcmt_drake_signal.hpp': No such file or directory [C:\projects\ReYFE7LH\drake\pod-build\examples\Acrobot\test\acrobotURDFDynamicsTest.vcxproj]
```

I see the missing header file being generated in the same log file, though at a later time:

```
02:10:00   Generating drake_lcmt_drake_signal.h, drake_lcmt_drake_signal.c, drake/lcmt_drake_signal.hpp, drake/lcmt_drake_signal.java:
```
Thus, maybe this is a missing dependency bug that's exposed by a multi-threaded build.

**Comment by mwoehlke-kitware** [comment]
That's... odd. There is a custom target (`drake_lcmtypes_hpp`) that depends on the generated `.hpp` files, and `drakeLCMSystem` (along with quite a few other targets) depends on that. Apparently this works fine *except* on Visual Studio for some reason...? Investigating now...

(And, of course, the CI Windows builds are both ninja builds...)

**Comment by david-german-tri** [comment]
Since this is postsubmit breakage only, let's fix-forward instead of roll back if possible.  Please keep us posted!

**Comment by RussTedrake** [comment]
@mwoehlke-kitware This PR broke my current mac build.
```
Warning:By not providing "Findlcm.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "lcm", but CMake did not find one.
Could not find a package configuration file provided by "lcm" with any of the following names:
  lcmConfig.cmake   lcm-config.cmake
Add the installation prefix of "lcm" to CMAKE_PREFIX_PATH or set "lcm_DIR" to a directory containing one of the above files.  If "lcm" provides a separate development package or SDK, be sure it has been installed.
```
Where is FindLCM.cmake supposed to be coming from now?

**Comment by mwoehlke-kitware** [comment]
> Where is FindLCM.cmake supposed to be coming from now?

Answering this "for the record": there is no `Findlcm.cmake`; LCM is now providing a "CMake package configuration file", i.e. `lcmConfig.cmake`, per the CMake warning message. (Think of this as sort of the CMake equivalent of a `.pc` file.) The standard location for these is:

- `<prefix>/CMake` (Windows)
- `<prefix>/<libdir>/<package>/cmake` (not-Windows)

Normally, in order for CMake to find these without needing additional hints, it is sufficient to add `<prefix>` to `CMAKE_PREFIX_PATH` or to use one of the built-in roots (e.g. `/usr`, `/usr/local` on not-Windows; also, `CMAKE_INSTALL_PREFIX` is apparently included in the default roots).

Per my comment in #2730, I'm not sure why this isn't working for you...

**Pull request merged**
