### PR TITLE
common::polynomial : Add Subsitute(var, Polynomial)

### PR DESCRIPTION
**Pull request by RussTedrake**
Also generalizes Polynomial::IsApprox to support multivariate polynomials.
NOTE: The behavior of IsApprox has changed from the previous implementation for univariate polynomials in two ways:
  1) IsApprox will now fail if the polynomials have different variables.
  2) The comparison is now absolute instead of relative.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13108)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
The GSG is not written very clearly on this point, but https://drake.mit.edu/styleguide/cppguide.html#Enumerator_Names suggests to me that we want `kAbsolute` and `kRelative`, instead of `absolute` and `relative`?  Did we discuss this yet?  WDYT?

**Comment by jwnimmer-tri** [comment]
My GSG uncertainty was that it does not acknowledge the existence of `enum class` vs just `enum`.  Certainly for bare `enum` is clear.  But conceivably we could allow for different practices for `enum class`.

**Comment by jwnimmer-tri** [comment]
> Maybe I'm putting to much weight into this:
>
> >    Enumerators (for both scoped and unscoped enums) should be named either like constants or like macros: either kEnumName or ENUM_NAME.
>
> Seems pretty clear to me.

Thank you!  I read right over that -- I was looking for `class` and forgot that `scoped` was a synonym here.  I agree that it's clearly on the side of `kFoo` now.

**Comment by RussTedrake** [comment]
One more point - i even disagree with the statement about the previous version guarding on topology.  The polynomials x and x + 0*x^2 and topologically different but would have returned true.  (And they happen often).

**Pull request merged**
