### PR TITLE
pydrake doc: Add examples on `keep_alive`

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Follow-up to #11971

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11984)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@sherm1 This PR is six months stale.  May we close it?  It doesn't seem to be benefiting from either a partial review, or CI information.

**Comment by jwnimmer-tri** [comment]
Oops, I copy-pasta'd the wrong author.  I meant to ping @EricCousineau-TRI.

**Comment by SeanCurtis-TRI** [comment]
Given the lack of response to the lack ping, I'll reping.

@EricCousineau-TRI  -- This PR is six months stale. May we close it? It doesn't seem to be benefiting from either a partial review, or CI information.

**Comment by EricCousineau-TRI** [comment]
Would love to make it land, but yeah, don't have time for it for now. Closing for now, will re-open later.

**Pull request closed without merging**
