### PR TITLE
Do not generate (now-unused) drakeFoo_export.h headers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-on work from #3680.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3687)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both reviews.  If CMake is not your thing, we can bounce this to David.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3687#-:-KTL2WN3CJtsJjD3BHF8:b-6tgnq5)*

**Comment by sammy-tri** [comment]
I think (hope!) I understood the CMake well enough...  :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3687#-:-KTL85emPTELudHFaM_W:b-1utw7q)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot mac-clang-experimental please

**Comment by jwnimmer-tri** [comment]
Oops, I just noticed a comment typo.  Will bash on regardless.

**Pull request merged**
