### PR TITLE
Introduce FrameVelocity, and add a velocity output to SimpleCar.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jadecastro for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5421)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm: platform review, automotive design review.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/frame_velocity.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-KeZtd9di8AZ2TmSzgsI:-KeZtd9di8AZ2TmSzgsJ:bbw26oz) ([raw file](https://github.com/robotlocomotion/drake/blob/4f308a73bf22887b3b329bd81c702009f5e06abe/drake/systems/rendering/frame_velocity.cc#L52)):*
> ```cpp
> FrameVelocity<T>* FrameVelocity<T>::DoClone() const {
>   FrameVelocity<T>* clone = new FrameVelocity<T>();
>   clone->set_value(this->get_value());
> ```

BTW I wonder if we should change the `Clone` vs `DoClone` contract so that the `Clone` NVI method promises to call `result->set_value(this->get_value());` after `DoClone` returns a value of the correct type?  That seems like a clear win. Then the `DoClone` implementations only need to worry about additional metadata (which there shouldn't be any of anyway).

---

*[drake/systems/rendering/frame_velocity.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-KeZsfM10LOuiT94M6kH:-KeZsfM2TWnZROPv76qX:b-tzp93q) ([raw file](https://github.com/robotlocomotion/drake/blob/4f308a73bf22887b3b329bd81c702009f5e06abe/drake/systems/rendering/frame_velocity.h#L38)):*
> ```objc
> 
>  private:
>   /// Assigns the translational velocity pdot_WA.
> ```

BTW nit _Meta_ Prefer `//` for non-Doxygen-rendered comment blocks.

---

*[drake/systems/rendering/test/frame_velocity_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-KeZuLq0klE3snLowkm1:-KeZuLq11lfIxsDnPIim:b-5xknp7) ([raw file](https://github.com/robotlocomotion/drake/blob/4f308a73bf22887b3b329bd81c702009f5e06abe/drake/systems/rendering/test/frame_velocity_test.cc#L28)):*
> ```cpp
>                               vec.get_velocity().translational()));
> }
> ```

Missing unit test for `Clone()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-:-KeZvQ0HFcMOjFtMFOWp:bp48smt)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/frame_velocity.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-KeZtd9di8AZ2TmSzgsI:-KeZzuStWcXk-eFvq_0J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f308a73bf22887b3b329bd81c702009f5e06abe/drake/systems/rendering/frame_velocity.cc#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I wonder if we should change the `Clone` vs `DoClone` contract so that the `Clone` NVI method promises to call `result->set_value(this->get_value());` after `DoClone` returns a value of the correct type?  That seems like a clear win. Then the `DoClone` implementations only need to worry about additional metadata (which there shouldn't be any of anyway).
</blockquote></details>

Done.

---

*[drake/systems/rendering/frame_velocity.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-KeZsfM10LOuiT94M6kH:-KeZxTeCIqWX6O7uHt0Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f308a73bf22887b3b329bd81c702009f5e06abe/drake/systems/rendering/frame_velocity.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit _Meta_ Prefer `//` for non-Doxygen-rendered comment blocks.
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/frame_velocity_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-KeZuLq0klE3snLowkm1:-KeZyI8SFHxQmhbujy-j:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f308a73bf22887b3b329bd81c702009f5e06abe/drake/systems/rendering/test/frame_velocity_test.cc#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing unit test for `Clone()`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 12 files at r2.
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_0E6ict_DZD4vHXxB:-Ke_0E6ict_DZD4vHXxC:b-ifeisy) (no related file):*
Somehow some Kuka diffs has showed up in this PR.  Merge error?

---

*[drake/systems/framework/basic_vector.h, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_-ZK6g0hw0QnlpLqt:-Ke_-ZK6g0hw0QnlpLqu:brcsu5w) ([raw file](https://github.com/robotlocomotion/drake/blob/b3563bab9ab9c09401fb1f11083b87f825d138f8/drake/systems/framework/basic_vector.h#L125)):*
> ```objc
>   std::unique_ptr<BasicVector<T>> Clone() const {
>     auto clone = std::unique_ptr<BasicVector<T>>(DoClone());
>     clone->set_value(this->get_value());
> ```

BTW Does this deserve a specific unit test?  The `value_checker` would eventually find it if we lost this line, but not sure how direct the error message would be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421)*

**Comment by david-german-tri** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_0E6ict_DZD4vHXxB:-Ke_0v7QPR4L-2wZb9BX:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Somehow some Kuka diffs has showed up in this PR.  Merge error?
</blockquote></details>

Done.

---

*[drake/systems/framework/basic_vector.h, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_-ZK6g0hw0QnlpLqt:-Ke_0f6Nq1u1mDdhrxoc:bpyf0t0) ([raw file](https://github.com/robotlocomotion/drake/blob/b3563bab9ab9c09401fb1f11083b87f825d138f8/drake/systems/framework/basic_vector.h#L125)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Does this deserve a specific unit test?  The `value_checker` would eventually find it if we lost this line, but not sure how direct the error message would be.
</blockquote></details>

There are tests on `BasicVector::Clone` which cover this line locally.  I agree that subclasses should continue to test their DoClone overrides, as FrameVelocity does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421)*

**Comment by jadecastro** [comment]
Great to have this. Thanks! 
Just a few comments below.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/simple_car.cc, line 100 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_I-CVQubBbtOm8YjV:-Ke_I-CVQubBbtOm8YjW:b-xfgcoq) ([raw file](https://github.com/robotlocomotion/drake/blob/3ac89a52b7ba861df31ca57338ec1c3543d06252/drake/automotive/simple_car.cc#L100)):*
> ```cpp
> template <typename T>
> void SimpleCar<T>::ImplCalcVelocity(
>     const systems::Context<T>& context,
> ```

BTW, I'm not sure if there's any agreed-upon standard for how `Impl*` functions are put together, but it's nice to see things like `GetNumericParameter`, `EvalVectorInput,`, live outside `Impl*` in the caller (`DoCalcOutput`).  Consider doing that here too.

---

*[drake/automotive/simple_car.cc, line 107 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_HXQPhLQH4Q2ySc_a:-Ke_HXQQlO-Rq0u7rVwd:b-x35hs1) ([raw file](https://github.com/robotlocomotion/drake/blob/3ac89a52b7ba861df31ca57338ec1c3543d06252/drake/automotive/simple_car.cc#L107)):*
> ```cpp
> 
>   // Obtain the state.
>   const SimpleCarState<T>* const state = dynamic_cast<const SimpleCarState<T>*>(
> ```

BTW (and somewhat related to the above comment), It looks like `state` is declared in the same way in `DoCalcOutput`.  Any chance we could bring in `state` as an argument?

---

*[drake/systems/rendering/frame_velocity.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_my6gjxyWf4qqwaVi:-Ke_my6gjxyWf4qqwaVj:b5k22ww) ([raw file](https://github.com/robotlocomotion/drake/blob/4f308a73bf22887b3b329bd81c702009f5e06abe/drake/systems/rendering/frame_velocity.h#L38)):*
> ```objc
> 
>  private:
>   /// Assigns the translational velocity pdot_WA.
> ```

BTW, Should this be just `p_WA` (and should below be just `R_WA`), to be consistent with what's how the variables are defined above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-:-Ke_loaX1AcvxwqaC_HN:b-afn8yz)*

**Comment by jadecastro** [comment]
Reviewed 8 of 9 files at r1, 4 of 12 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/simple_car.cc, line 100 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_I-CVQubBbtOm8YjV:-KedF_G1mbwmM-v71ftr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ac89a52b7ba861df31ca57338ec1c3543d06252/drake/automotive/simple_car.cc#L100)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, I'm not sure if there's any agreed-upon standard for how `Impl*` functions are put together, but it's nice to see things like `GetNumericParameter`, `EvalVectorInput,`, live outside `Impl*` in the caller (`DoCalcOutput`).  Consider doing that here too.
</blockquote></details>

Done.

---

*[drake/automotive/simple_car.cc, line 107 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_HXQPhLQH4Q2ySc_a:-KedF_ab-k2cYGUypqgO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ac89a52b7ba861df31ca57338ec1c3543d06252/drake/automotive/simple_car.cc#L107)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW (and somewhat related to the above comment), It looks like `state` is declared in the same way in `DoCalcOutput`.  Any chance we could bring in `state` as an argument?
</blockquote></details>

Done.

---

*[drake/systems/rendering/frame_velocity.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-Ke_my6gjxyWf4qqwaVi:-KedFeSuHx-us2KTSowx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f308a73bf22887b3b329bd81c702009f5e06abe/drake/systems/rendering/frame_velocity.h#L38)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, Should this be just `p_WA` (and should below be just `R_WA`), to be consistent with what's how the variables are defined above?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421)*

**Comment by jadecastro** [comment]
:lgtm:!

---

Reviewed 1 of 12 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5421#-:-KedebbLz-B10ry5M62X:bg7igkw)*

**Pull request merged**
