### PR TITLE
Parallelize the Rounding Stage of GCS

### PR DESCRIPTION
**Pull request by cohnt**
This ended up being pretty simple -- solve all the restrictions in a parallel for loop, and override `options.parallelism` to set the number of threads to one if any not-thread-safe costs or constraints are included in the GCS.

Gonna test this with the various debug builds before I send it up for review.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222)

### CODE REVIEW

**Comment by cohnt** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-address-sanitizer please

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1618 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-OCEuxCo4_CyPiUKt3F0:-OCEuxCo4_CyPiUKt3F1:b1woes9) ([raw file](https://github.com/RobotLocomotion/drake/blob/6b5ffb3cadf95cffdea5589c231e79bf5cbe261c/geometry/optimization/graph_of_convex_sets.cc#L1618)):*
> ```cpp
> 
>     // If any costs or constraints aren't thread-safe, we can't parallelize.
>     bool is_thread_safe = true;
> ```

Don't forget to set `options.kMaxThreads = 1` and make sure to warn if `is_thread_safe == false && parallelism.num_threads() > 1`, otherwise users might be surprised if the extra threads aren't used.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1618 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-OCEuxCo4_CyPiUKt3F0:-OCF401T1Z5_YVUBDkNs:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6b5ffb3cadf95cffdea5589c231e79bf5cbe261c/geometry/optimization/graph_of_convex_sets.cc#L1618)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Don't forget to set `options.kMaxThreads = 1` and make sure to warn if `is_thread_safe == false && parallelism.num_threads() > 1`, otherwise users might be surprised if the extra threads aren't used.
</blockquote></details>

Done.

**Comment by cohnt** [comment]
+@RussTedrake for feature review, if you have the time?

**Review by RussTedrake — COMMENTED** [review]
we'll need some test coverage.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-:-OCzmMuf-pqD_gHsMTNo:bot7sli)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1662 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-OCzkwH44YXLeFbYEwbx:-OCzkwH44YXLeFbYEwby:bfk1j21) ([raw file](https://github.com/RobotLocomotion/drake/blob/de65fa161f4259efdc1312522fe1ce02fef6b7c3/geometry/optimization/graph_of_convex_sets.cc#L1662)):*
> ```cpp
>     if (n_threads_to_use < options.parallelism.num_threads()) {
>       log()->warn(
>           "GCS restriction has costs or constraints which are not thread-safe, "
> ```

perhaps "not declared thread-safe"?  i suspect most are thread safe, but might need to be marked appropriately since we have to assume the worst.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1690 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-OCzkA44-Pxh6Wwx1s4H:-OCzkA44-Pxh6Wwx1s4I:bdyoxd2) ([raw file](https://github.com/RobotLocomotion/drake/blob/de65fa161f4259efdc1312522fe1ce02fef6b7c3/geometry/optimization/graph_of_convex_sets.cc#L1690)):*
> ```cpp
>     using common_robotics_utilities::parallelism::DegreeOfParallelism;
>     using common_robotics_utilities::parallelism::DynamicParallelForIndexLoop;
>     using common_robotics_utilities::parallelism::ParallelForBackend;
> ```

btw -- i guess i thought that drake/common/parallelism.h was supposed to shield us from using CRU parallelism directly.  I guess you need more?
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1696 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-OCzlvtL3vmOJcQ5zpmd:-OCzlvtL3vmOJcQ5zpme:bo7iycg) ([raw file](https://github.com/RobotLocomotion/drake/blob/de65fa161f4259efdc1312522fe1ce02fef6b7c3/geometry/optimization/graph_of_convex_sets.cc#L1696)):*
> ```cpp
>     DynamicParallelForIndexLoop(
>         DegreeOfParallelism(n_threads_to_use), 0, ssize(candidate_paths),
>         solve_ith_convex_restriction, ParallelForBackend::BEST_AVAILABLE);
> ```

this whole glob of code is conceptually separable from the rest of SolveShortestPath, and it's adding a LOT of lines to an already enormous method. What do you think about pulling it out into it's own method?  It might even be useful by itself?  (e.g. SamplePaths got pulled out for this reason).

**Review by cohnt — COMMENTED** [review]
What would test coverage look like? Since the default is to use parallelism, we already have a ton of test cases that verify that parallelism works. I guess I could pick one of the test cases to run with and without parallelism, and verify that the solution is the same?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-:-OD7ehta1URztxSAZ_cJ:bop283k)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1662 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-OCzkwH44YXLeFbYEwbx:-OD7eGj3AJOLVZtm1Mqe:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/de65fa161f4259efdc1312522fe1ce02fef6b7c3/geometry/optimization/graph_of_convex_sets.cc#L1662)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

perhaps "not declared thread-safe"?  i suspect most are thread safe, but might need to be marked appropriately since we have to assume the worst.
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1690 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-OCzkA44-Pxh6Wwx1s4H:-OD7ea3A-OmBZ32YZRjF:bsbfjm7) ([raw file](https://github.com/RobotLocomotion/drake/blob/de65fa161f4259efdc1312522fe1ce02fef6b7c3/geometry/optimization/graph_of_convex_sets.cc#L1690)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i guess i thought that drake/common/parallelism.h was supposed to shield us from using CRU parallelism directly.  I guess you need more?
</blockquote></details>

I was trying to work within the current program structure, but now that I'm refactoring, I've been able to remove the CRU usage.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1696 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-OCzlvtL3vmOJcQ5zpmd:-OD7eZqh1pDmieNLpt4r:bqgd8lr) ([raw file](https://github.com/RobotLocomotion/drake/blob/de65fa161f4259efdc1312522fe1ce02fef6b7c3/geometry/optimization/graph_of_convex_sets.cc#L1696)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this whole glob of code is conceptually separable from the rest of SolveShortestPath, and it's adding a LOT of lines to an already enormous method. What do you think about pulling it out into it's own method?  It might even be useful by itself?  (e.g. SamplePaths got pulled out for this reason).
</blockquote></details>

I've done some refactoring to clean this up. Do you like this better?

**Review by RussTedrake — COMMENTED** [review]
Yes, that seems reasonable. Philosophically, if you are adding a new feature (especially one that changes this much code), then we want to make sure we have coverage.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-:-ODB8zhR1dbpF6wsBvOp:b62kqjh)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1696 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-OCzlvtL3vmOJcQ5zpmd:-ODB7DKr0WvPQ7mp-8QO:beyga9w) ([raw file](https://github.com/RobotLocomotion/drake/blob/de65fa161f4259efdc1312522fe1ce02fef6b7c3/geometry/optimization/graph_of_convex_sets.cc#L1696)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

I've done some refactoring to clean this up. Do you like this better?
</blockquote></details>

yes.  thank you!
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1662 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-ODB8EkI1r-0tRqi7yyH:-ODB8EkI1r-0tRqi7yyI:bawl0ol) ([raw file](https://github.com/RobotLocomotion/drake/blob/2155db1a0df4f7236b11259c06b7ef527e44251d/geometry/optimization/graph_of_convex_sets.cc#L1662)):*
> ```cpp
>     }
> 
>     std::optional<solvers::SolverId> maybe_solver_id = std::nullopt;
> ```

btw -- do you worry about calling ChooseBestSolver for every solve if solver_id is not set here?  I guess it's necessary in the current workflow, since there could be one program in progs that e.g. visits a vertex whom no other program visits which has a different (e.g. nonconvex) program.  
___
*[`geometry/optimization/graph_of_convex_sets.h` line 883 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-ODB57zK4Qn5hP1KCVnN:-ODB57zL-Xh5CpKcoyET:b-mwo9i9) ([raw file](https://github.com/RobotLocomotion/drake/blob/2155db1a0df4f7236b11259c06b7ef527e44251d/geometry/optimization/graph_of_convex_sets.h#L883)):*
> ```objc
>   // Add results for additional variables in `result` to make it comparable with
>   // other transcriptions.
>   void SubstituteAdditionalVariables(
> ```

The prefix "Substitute" here confused me, since you have placeholder variable substitution happening in various places. Can we find a more specific name?  This is only to make the convex restriction result look more like the MIP result?

fysa, in PRs like https://github.com/RobotLocomotion/drake/pull/21833, I've actually been trying to do less of this writing of extra stuff into the solution results, and instead making GetSolutionCost and friends more robust to missing information.

**Review by cohnt — COMMENTED** [review]
Added this for one of the test cases that does rounding.

> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-:-ODCALCtEDY18t0e4AQu:bfiffij)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 883 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-ODB57zK4Qn5hP1KCVnN:-ODCAzR74vutXIjOuVMm:b-d645el) ([raw file](https://github.com/RobotLocomotion/drake/blob/2155db1a0df4f7236b11259c06b7ef527e44251d/geometry/optimization/graph_of_convex_sets.h#L883)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The prefix "Substitute" here confused me, since you have placeholder variable substitution happening in various places. Can we find a more specific name?  This is only to make the convex restriction result look more like the MIP result?

fysa, in PRs like https://github.com/RobotLocomotion/drake/pull/21833, I've actually been trying to do less of this writing of extra stuff into the solution results, and instead making GetSolutionCost and friends more robust to missing information.
</blockquote></details>

How about this? A little verbose, but very specific.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1662 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-ODB8EkI1r-0tRqi7yyH:-ODCBej-45U7Y06XLQy7:b78tw6s) ([raw file](https://github.com/RobotLocomotion/drake/blob/2155db1a0df4f7236b11259c06b7ef527e44251d/geometry/optimization/graph_of_convex_sets.cc#L1662)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- do you worry about calling ChooseBestSolver for every solve if solver_id is not set here?  I guess it's necessary in the current workflow, since there could be one program in progs that e.g. visits a vertex whom no other program visits which has a different (e.g. nonconvex) program.
</blockquote></details>

For the reason you described, I think we have to call `ChooseBestSolver` each time. Not sure what the overhead looks like.

Presumably, the best practice is to set this solver if it's known -- do you want me to document that in `GraphOfConvexSetsOptions`?

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@rpoyner-tri for platform review, please.

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-:-ODDD4f47yn_WeL-_7FN:b-5mhjlt)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 883 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-ODB57zK4Qn5hP1KCVnN:-ODDCqV41_pog6XTPjKK:b-nt49iu) ([raw file](https://github.com/RobotLocomotion/drake/blob/2155db1a0df4f7236b11259c06b7ef527e44251d/geometry/optimization/graph_of_convex_sets.h#L883)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

How about this? A little verbose, but very specific.
</blockquote></details>

I like it. 
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1662 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-ODB8EkI1r-0tRqi7yyH:-ODDCy135BCkJ78shFpx:b-83sjo4) ([raw file](https://github.com/RobotLocomotion/drake/blob/2155db1a0df4f7236b11259c06b7ef527e44251d/geometry/optimization/graph_of_convex_sets.cc#L1662)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

FWIW, `ChooseBestSolver` is pretty fast since it is just a big lookup table. If you're worried about the cost of repeatedly **constructing** the best solver, then `SolveInParallel` already takes care of that by caching the constructed solvers as it solves.
</blockquote></details>

Nice.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: fix) 
:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 3 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-:-ODDIDGq5NNgM7jguMt7:bixlcei)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
-(release notes: fix) 
+(release notes: feature) 

> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22222#-:-ODDLcCI9dqkIxf2Ackk:b-53xymw)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Pull request merged**
