### PR TITLE
Notation clean-up (replace frame P with frame A).  Isolate calculation of canonical principal directions.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19726)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few nits
+@sammy-tri for platform review per schedule, please (or punt to Monday's reviewer if too late). This one is small, mostly code move.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19726#-:-NZhFfXB6oj035ZItwIA:b-769fgv)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform)

___
*[`multibody/tree/rotational_inertia.cc` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19726#-NZhDqE71H8AN1D_5zeK:-NZhDqE71H8AN1D_5zeL:bbgohvv) ([raw file](https://github.com/RobotLocomotion/drake/blob/e768e369288071e676cdeb30d5f219e6172e1d12/multibody/tree/rotational_inertia.cc#L14)):*
> ```cpp
> // Forms a canonical set of 3 principal moment of inertia directions from the
> // non-canonical principal moment of inertia axes directions in @p R_EA.
> // @param[in] principal_moments_inertia for `this` rotational inertia.
> ```

minor: should note that these must be sorted min to max
___
*[`multibody/tree/rotational_inertia.cc` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19726#-NZhEX_i8_ZXDbkaWaAU:-NZhEX_i8_ZXDbkaWaAV:b-o3xl83) ([raw file](https://github.com/RobotLocomotion/drake/blob/e768e369288071e676cdeb30d5f219e6172e1d12/multibody/tree/rotational_inertia.cc#L28)):*
> ```cpp
> // principal directions in various ways, particularly if two or three of the
> // principal moments of inertia are equal.
> math::RotationMatrix<double> CalcCanonicalPrincipalDirections(
> ```

minor: should say in the function comment that only the triaxially symmetric case is currently implemented
___
*[`multibody/tree/rotational_inertia.cc` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19726#-NZhEx8LAyOTlG-zpZ63:-NZhEx8LAyOTlG-zpZ64:b-a99fmq) ([raw file](https://github.com/RobotLocomotion/drake/blob/e768e369288071e676cdeb30d5f219e6172e1d12/multibody/tree/rotational_inertia.cc#L38)):*
> ```cpp
>   // Case: Triaxially symmetric principal moments of inertia (all 3 ≈ equal).
>   // Physical example: uniform-density sphere.
>   // For this case, body B's inertia matrix about-point P expressed in the
> ```

nit: "inertia about point P" rather than "inertia about-point P"

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19726)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`multibody/tree/rotational_inertia.cc` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19726#-NZhDqE71H8AN1D_5zeK:-NZhkXBZ7H_E10VG6RS5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e768e369288071e676cdeb30d5f219e6172e1d12/multibody/tree/rotational_inertia.cc#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should note that these must be sorted min to max
</blockquote></details>

Done.
___
*[`multibody/tree/rotational_inertia.cc` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19726#-NZhEX_i8_ZXDbkaWaAU:-NZhlcNo4ue_mw6oT88z:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e768e369288071e676cdeb30d5f219e6172e1d12/multibody/tree/rotational_inertia.cc#L28)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should say in the function comment that only the triaxially symmetric case is currently implemented
</blockquote></details>

Done.
___
*[`multibody/tree/rotational_inertia.cc` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19726#-NZhEx8LAyOTlG-zpZ63:-NZhliDI3UCfl_IZGFOi:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/e768e369288071e676cdeb30d5f219e6172e1d12/multibody/tree/rotational_inertia.cc#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: "inertia about point P" rather than "inertia about-point P"
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19726)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19726#-:-N_0SkTq2_fYSAueLmFs:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19726)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sammy-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19726#-:-N_0SpJY4pREW8zH2jO7:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform)

**Pull request merged**
