### PR TITLE
Switch to Python 3.10 on macOS

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17723)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-monterey-unprovisioned-clang-bazel-experimental-release please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.

**Review by BetsyMcPhail — COMMENTED** [review]
Need to coordinate merging this PR with updating provisioned Mac images 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17723#-:-N9ISiHfE9Bm-yG32Vvt:b-g3art0)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-m1-monterey-provisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-m1-monterey-provisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-monterey-unprovisioned-clang-cmake-experimental-release please.

**Comment by BetsyMcPhail** [comment]
Ignore the M1 provisioned job, should have been:

@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-everything-release please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Unprovisioned doesn't look happy either. 

In slack, @russtedrake suggested the following works:

https://github.com/RobotLocomotion/drake/commit/333e690a0c738c8e4c54d37e053a5e9e25abe203

I haven't compared that with this yet.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17723#-:-N9Mg7EeAgdiUlaXTZWE:boz1g9e)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Comment by BetsyMcPhail** [comment]
I confirmed that Russ' changes and this PR are equivalent. This PR also contains some documentation updates. 

Also, the M! job failing is still my error, the M! everything builds are still not passing and not part of the nightly jobs. These two are:

@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-m1-monterey-provisioned-clang-bazel-experimental-snopt-release please.

**Review by BetsyMcPhail — COMMENTED** [review]
M1 does have a real error:  `FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/bin/python3.10'` @svenevs any ideas?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17723#-:-N9RWeb58DqZWymklsPw:bbcxppu)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Comment by RussTedrake** [comment]
That should from the `brew 'python@3.10'` line in the Brewfile.  Sometimes the links get stuck on installation, and running `brew link python@3.10`could help?

**Review by BetsyMcPhail — COMMENTED** [review]
+@ggould-tri for review please. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17723#-:-N9WnaVeBTK2Ooq_LOtz:b-59r9od)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; CI is clearly in the driver's seat for correctness here, but the text all looks right to me.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17723#-:-N9WqN6m2HSDWC0dFWOo:bngcyru)* status: needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
+@svenevs for a feature review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17723#-:-N9WqmkJ2qAVy23nglYD:br20vce)* status: LGTM missing from assignee svenevs, missing label for release notes (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
:lgtm:

>  CI is clearly in the driver's seat for correctness here

Sort of, the failed jobs are expected to have failed (provisioned m1 jobs and unprovisioned everything).  We will be rebuilding things shortly.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17723#-:-N9WtP4D34ARCufsR7Lx:b-susygp)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),svenevs (waiting on @svenevs)

**Review by BetsyMcPhail — COMMENTED** [review]
The plan is to:
1. Merge this PR
2. Update Montery and Big Sur 
3. Update M1 (this will take ~1 hour or so)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17723#-:-N9WtcH4EgoPcrrDA1PF:b-ce46g1)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),svenevs (waiting on @svenevs)

**Pull request merged**
