### PR TITLE
Run drake/tools/clang-format-includes --all

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5689)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@jwnimmer-tri , FYI, there are build failures.

**Comment by jwnimmer-tri** [comment]
+@mitiguy for feature review of the `drake/math/*` changes (3 files), please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5689#-:-Kgb7r4TOSAthnhr8lzV:b-j3bnc6)*

**Comment by mitiguy** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5689#-:-KgpgG-qDiHv8oPuZP8i:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per rotation, please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5689#-:-KgpqILIbjIxZ55kPkN4:b-eb2cxg)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5689#-:-Kgtjavfl6rn-YRgsDQR:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Ah, I need a :car:.

**Pull request merged**
