### PR TITLE
github: Add issue template

### LINKED ISSUE #8812: Create an issue template?
At the very least bug reports should have the SHA of Drake to which the bug relates and the platform on which the bug occurred, maybe also Bazel and CMake versions. Potentially there could be checkboxes that reporters can use to affirm that they have done things like pull master and/or run the latest install_prereqs, or other such troubleshooting actions, though not sure how useful such things turn out to be.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8812 

Following GitHub instructions: https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/
The format is semi-cribbed from [bazel](https://github.com/bazelbuild/bazel/blob/f5280fd00f33321f7634251442ed4384ae6ca31c/ISSUE_TEMPLATE.md).

Since we use `doc/` and not `docs/`, I have placed the file in `.github/`. This is a single template for issues and enhancement requests; if desired, I can split them up.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851#-:-LD85hTj1Bi8zqC9U0wH:b-g5v4cm)*

**Comment by jwnimmer-tri** [comment]
Having _any_ template is likely better than nothing, but for any of the Q&A to ask about what the OS is, what versions are in use, etc. -- rather than the user self-reporting it, I'd prefer to have a script the user can run that provides something they can just paste into GitHub.  That could be a follow-up, but I thought I'd mention it here in case it makes more sense that iterating on the build-detail questions within this template.

**Comment by EricCousineau-TRI** [comment]
I think having a script to automate this would be great, but would be non-trivial effort to develop and qualify. I do not want to do it myself at this point (esp. figuring out how `drake` is being consumed, etc.), so my vote is to make it follow-up.

**Comment by jamiesnape** [comment]
I am happy for the script to be a follow up. Please create an issue.

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.github/issue_template.md, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8851#-LDHvCFqBNug5HEMd5Vx:-LDHvCFqBNug5HEMd5Vy:b-cno11i) ([raw file](https://github.com/robotlocomotion/drake/blob/25fac8fd63131162a87625bfa1f65f004c983716/.github/issue_template.md#L54)):*
> ```Markdown
>     * What build system are you using with `drake`? (Bazel, CMake)
> 
>         > Replace this with Bazel or CMake.
> ```

Version of Bazel/CMake? Compiler and version? Python executable and version?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851#-:-LDHvNBX6Qw2bSjvVsH-:b-9napew)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/issue_template.md, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8851#-LDHvCFqBNug5HEMd5Vx:-LDI6t911Xzf4W7Tf9Jt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25fac8fd63131162a87625bfa1f65f004c983716/.github/issue_template.md#L54)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Version of Bazel/CMake? Compiler and version? Python executable and version?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please.

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/issue_template.md, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8851#-LDMgNhUDNWZ4Ntadq1m:-LDMgNhVEK0fkkb0dmiF:b-7ddpkw) ([raw file](https://github.com/robotlocomotion/drake/blob/942bd1ebd70485076e30ade22aa8cbc9b6b5b8e3/.github/issue_template.md#L59)):*
> ```Markdown
> 
>     > If the above command does not reveal your compiler, please determine
>     which compiler is beign used, and print out its `--version`.
> ```

`being`

Also, in the current configuration using a custom `CROSSTOOL`, the environment variables `CC` and `CXX` are largely irrelevant for most Bazel builds.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[.github/issue_template.md, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8851#-LDMgNhUDNWZ4Ntadq1m:-LDMowAP8tkdcUCSbkcL:b-rxmiv7) ([raw file](https://github.com/robotlocomotion/drake/blob/942bd1ebd70485076e30ade22aa8cbc9b6b5b8e3/.github/issue_template.md#L59)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`being`

Also, in the current configuration using a custom `CROSSTOOL`, the environment variables `CC` and `CXX` are largely irrelevant for most Bazel builds.
</blockquote></details>

Done. (Initial attempt.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851)*

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8851#-LDqehoy6jkJycG7HjKT:-LDqehoy6jkJycG7HjKU:b8w3h8n) (no related file):*
Per f2f with @jamiesnape, need to add a test which runs `print_host_settings`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8851#-LDqehoy6jkJycG7HjKT:-LDt46e37U8dATGk5MF7:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per f2f with @jamiesnape, need to add a test which runs `print_host_settings`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851)*

**Comment by EricCousineau-TRI** [comment]
+@sherm1 for platform review, please. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851#-:-LDvalJCChypV_kqhsG-:b-efu58m)*

**Comment by EricCousineau-TRI** [comment]
(And if you'd like someone else to platform review, please let me know.)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851#-:-LDvnlU12Fka4qwNanXu:bw5ts2a)*

**Comment by sherm1** [comment]
I ran through markdown, checked the links, and tried the print_host_settings command. I don't know how to check for proper behavior in GitHub but I assume that's been checked already. All looks good but one typo, see below.
Platform :lgtm:.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.github/issue_template.md, line 62 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8851#-LDwCc1wAnnGlGFGs-Nr:-LDwCc1wAnnGlGFGs-Ns:bp4j80w) ([raw file](https://github.com/robotlocomotion/drake/blob/b9353820f83babaf90418eb3538e186c2d390196/.github/issue_template.md#L62)):*
> ```Markdown
>     project workspace:
> 
>         > In your workspkace, please copy the output of:
> ```

BTW workspkace -> workspace

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851#-:-LDwDbyoEwhl4RhGqQgl:b1ja6pn)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[.github/issue_template.md, line 62 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8851#-LDwCc1wAnnGlGFGs-Nr:-LE6WB7v0Xnf687o1Y2R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9353820f83babaf90418eb3538e186c2d390196/.github/issue_template.md#L62)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW workspkace -> workspace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8851)*

**Pull request merged**
