### PR TITLE
Trigpoly feature parity

### PR DESCRIPTION
**Pull request by ggould-tri**
Bring Trigpoly up to feature parity with Polynomial, so that I can write TrigPolyConstraint based on PolynomialConstraint in a subsequent PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2345) &emsp; Multiple assignees:&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>,&emsp;@sammy-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sammy-tri">sammy-tri</a>

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@jwnimmer-tri (platform)
+@sammy-tri (feature)

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> #### Trigpoly feature parity
> 
> Bring Trigpoly up to feature parity with Polynomial, so that I can write TrigPolyConstraint based on PolynomialConstraint in a subsequent PR.
> 
> 
> </details>


---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-:-KHfJWvLEh-cjMybJT8x:1954764806)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/util/TrigPoly.h, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtRIR3mnyJaRzcaQcL:-KHtRIR3mnyJaRzcaQcM:-483513912) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L51)):*
> ```objc
>   template <typename Rhs, typename Lhs>
>   struct Product {
>     typedef decltype((Rhs)0 * (Lhs)0) type;
> ```

Use `static_cast<>` not C-cast per styleguide.  (Unless there is some reason why that doesn't work here?)

---

*[drake/util/TrigPoly.h, line 74 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtWd2v8pzEaHNUs7vx:-KHtWd2weUqXfibnQsDm:690679338) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L74)):*
> ```objc
>       }
>     }
>   }
> ```

Is there also an invariant that at most one sin_cos_map entry can name a given variable in one of its `second.{s,c}` fields?  In other words, each variable must be a sin or cos of at most one other variable?

---

*[drake/util/TrigPoly.h, line 189 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtS84rsEjL_UBuUGF1:-KHtS84rsEjL_UBuUGF2:-873230777) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L189)):*
> ```objc
>   }
> 
>   /// Return all of the base (non-sin/cos) variables in this TrigPoly.
> ```

`Returns` per code_style_guide.

---

*[drake/util/TrigPoly.h, line 199 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtSB4C9wp2upV7lGk7:-KHtSB4C9wp2upV7lGk8:-1305197616) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L199)):*
> ```objc
>   }
> 
>   /// Given a value for every variable in this expression, evaluate it.
> ```

`evaluates` per code_style_guide.

---

*[drake/util/TrigPoly.h, line 220 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtSEGYZUff4cf7TqZx:-KHtSEGYZUff4cf7TqZy:-1305197616) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L220)):*
> ```objc
>   }
> 
>   /// Partially evaluate this expression, returning the resulting expression.
> ```

`evaluates` per code_style_guide.

---

*[drake/util/TrigPoly.h, line 243 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtSyTWYL2XtYqklxq9:-KHtSyTWYL2XtYqklxqA:-2082243418) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L243)):*
> ```objc
>   }
> 
>   /// Compare two TrigPolys for equality.
> ```

`Compares` per code_style_guide.

---

*[drake/util/test/testTrigPoly.cpp, line 7 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtT8H5KaCBE7bF03yq:-KHtT8H67sw2zZ1KKDAY:-723062243) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/test/testTrigPoly.cpp#L7)):*
> ```cpp
> 
> #include "drake/util/Polynomial.h"
> #include "drake/util/TrigPoly.h"
> ```

The "related header" should be the first include per cppguide.

---

*[drake/util/test/testTrigPoly.cpp, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtTVJyFCIyat7KnI1Y:-KHtTVJyFCIyat7KnI1Z:-825896002) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/test/testTrigPoly.cpp#L19)):*
> ```cpp
> const double kPi = 3.1415926535897;
> 
> void test_serialization(TrigPolyd dut, std::string expect) {
> ```

Is this "cheap" / would you call it in an inner loop?  Seems like `TestSerialization` is more appropriate?

---

*[drake/util/test/testTrigPoly.cpp, line 42 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtUyalr6iN66x-SqYO:-KHtUyamYep-OxCp9sbW:660299129) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/test/testTrigPoly.cpp#L42)):*
> ```cpp
>   test_serialization(cos(p), "c1");
>   test_serialization(sin(p) * p * p + cos(p), "s1*q1^2+c1");
>   test_serialization(sin(p + p), "s1*c1+c1*s1");
> ```

Question: is there any hazard of not canonicalizing the order of sin-cos multiplications, so that this folds down into one term?  In general, some poly-related code seems to have been relying on canonicalized representations?

---

*[drake/util/test/testTrigPoly.cpp, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtVEQHeRHodxQCvQvw:-KHtVEQHeRHodxQCvQvx:-1781282429) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/test/testTrigPoly.cpp#L102)):*
> ```cpp
> 
> }  // anonymous namespace
> }  // namespace test
> ```

`util`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2345)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/util/TrigPoly.h, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtRIR3mnyJaRzcaQcL:-KHtgQKui29A65aVUa7k:66773628) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Use `static_cast<>` not C-cast per styleguide.  (Unless there is some reason why that doesn't work here?)</details>
This is copypasta from Polynomial.  I believe that this is correctly a `static_cast`, and it seems to work as one, but zeroes are enough of a weird case in the C++ spec that I am not wholly confident.  I'm changing it, but not without worry.

---

*[drake/util/TrigPoly.h, line 74 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtWd2v8pzEaHNUs7vx:-KHtgb5EpCb57qhoSnWR:204567680) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Is there also an invariant that at most one sin_cos_map entry can name a given variable in one of its `second.{s,c}` fields?  In other words, each variable must be a sin or cos of at most one other variable?</details>
Yes, I believe that is an undocumented invariant.  I have added documented it and added assertions for it (pending of course resolution of what the right syntax for rep invariant assertions might be).

---

*[drake/util/TrigPoly.h, line 189 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtS84rsEjL_UBuUGF1:-KHuSOCUkVFDQFP998am:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L189)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `Returns` per code_style_guide.</details>
Done.

---

*[drake/util/TrigPoly.h, line 199 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtSB4C9wp2upV7lGk7:-KHuSSXRNBysHScYRp3H:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L199)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `evaluates` per code_style_guide.</details>
Done.

---

*[drake/util/TrigPoly.h, line 220 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtSEGYZUff4cf7TqZx:-KHuSVlqGrlK3MzEbkku:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L220)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `evaluates` per code_style_guide.</details>
Done.

---

*[drake/util/TrigPoly.h, line 243 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtSyTWYL2XtYqklxq9:-KHuSYR4v1bEPT3KGYiB:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/TrigPoly.h#L243)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `Compares` per code_style_guide.</details>
Done.

---

*[drake/util/test/testTrigPoly.cpp, line 7 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtT8H5KaCBE7bF03yq:-KHuSdgiy7UxYwAq1IBk:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/test/testTrigPoly.cpp#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The "related header" should be the first include per cppguide.</details>
Done.

---

*[drake/util/test/testTrigPoly.cpp, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtTVJyFCIyat7KnI1Y:-KHuSf1RImtCIom8cXUV:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/test/testTrigPoly.cpp#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Is this "cheap" / would you call it in an inner loop?  Seems like `TestSerialization` is more appropriate?</details>
Done.

---

*[drake/util/test/testTrigPoly.cpp, line 42 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtUyalr6iN66x-SqYO:-KHtgquKZGqJy_4YsyK0:-708940075) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/test/testTrigPoly.cpp#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Question: is there any hazard of not canonicalizing the order of sin-cos multiplications, so that this folds down into one term?  In general, some poly-related code seems to have been relying on canonicalized representations?</details>
An interesting question.

This test is an attempt to preserve the (useless) test that existed before I got to this.  But in fact all that test was really testing was the serialization did not crash, not that it had any sort of intelligible result.

In point of fact the serialization result here is a bug anyway -- the case you are commenting on is exactly the commutative variant of #2216 and at minimum I need to document that fact.

I believe that it is best to leave this test in place, but document it.  This way it will have to be consciously revisited if the behaviour changes.

---

*[drake/util/test/testTrigPoly.cpp, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHtVEQHeRHodxQCvQvw:-KHth_j7KxdwX064hPzX:-1169210608) ([raw file](https://github.com/robotlocomotion/drake/blob/54bb107263a94fd994424c81930b9e37b3af0bf0/drake/util/test/testTrigPoly.cpp#L102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `util`</details>
`}  // namespace lemonbars`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2345)*

**Comment by sammy-tri** [comment]
Reviewed 4 of 6 files at r1, 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/util/Polynomial.cpp, line 297 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHuWaSpUfEd-8p-tVUF:-KHuWaSpUfEd-8p-tVUG:1490572367) ([raw file](https://github.com/robotlocomotion/drake/blob/e74f014b310484ed3c70accd9c4b2d9397890c10/drake/util/Polynomial.cpp#L297)):*
> ```cpp
> bool Polynomial<CoefficientType>::operator==(
>     const Polynomial<CoefficientType>& other) const {
>   const std::set<Monomial> this_monomials(monomials.begin(), monomials.end());
> ```

Why do we need to make a complete copy of the data of both this and others to compare them?  If it is necessary, I think a comment is deserved.

---

*[drake/util/test/CMakeLists.txt, line 31 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHuXIVrFDPYO8fAsAK4:-KHuXIVrFDPYO8fAsAK5:1828483531) ([raw file](https://github.com/robotlocomotion/drake/blob/e74f014b310484ed3c70accd9c4b2d9397890c10/drake/util/test/CMakeLists.txt#L31)):*
> ```CMake
> 
> add_executable(testTrigPoly testTrigPoly.cpp)
> target_link_libraries(testTrigPoly drakePolynomial ${GTEST_BOTH_LIBRARIES})
> ```

Seems slightly odd to have GTEST_BOTH_LIBRARIES inside and outside of a GTEST_FOUND conditional

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2345)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2345)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2345)*

**Comment by ggould-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/Polynomial.cpp, line 297 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHuWaSpUfEd-8p-tVUF:-KHur0jjaBgQODtjDCuo:-1027834095) ([raw file](https://github.com/robotlocomotion/drake/blob/e74f014b310484ed3c70accd9c4b2d9397890c10/drake/util/Polynomial.cpp#L297)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Why do we need to make a complete copy of the data of both this and others to compare them?  If it is necessary, I think a comment is deserved.</details>
There is no efficient unordered comparison of const vectors.

Copying both into btrees and comparing the btrees (O(nlogn)) is more efficient than the C++11 `is_permutation` idiom (O(n^2)) for reasons I do not understand.

Adding comment, that will also document vulnerability to #2216

---

*[drake/util/test/CMakeLists.txt, line 31 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-KHuXIVrFDPYO8fAsAK4:-KHurs_fLYV2dAcTNPMf:-1234997557) ([raw file](https://github.com/robotlocomotion/drake/blob/e74f014b310484ed3c70accd9c4b2d9397890c10/drake/util/test/CMakeLists.txt#L31)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Seems slightly odd to have GTEST_BOTH_LIBRARIES inside and outside of a GTEST_FOUND conditional</details>
Good catch!

(at least, in a world where GTEST_FOUND is a thing.  Why is that a thing?  Oh well).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2345)*

**Comment by sammy-tri** [comment]
:lgtm:

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> +@jwnimmer-tri (platform)
> +@sammy-tri (feature)</details>


---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-:-KHuwHkNZcEgBMoNw4Az:1417088721)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2345#-:-KHw7nCUaJNtLmUwok8_:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to 'out of date with master'.

**Pull request merged**
