### PR TITLE
Allow moving the grasp frame offset

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7923)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@avalenzu for feature review

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-:-L4GvYcHqoM2Zs3cXrss:bvpmr17)*

**Comment by avalenzu** [comment]
:lgtm: with a few BTWs on comments.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4GwhiMaNbCyWAW1MkB:-L4GwhiNVWHO-UfA29uy:b-l87you) ([raw file](https://github.com/robotlocomotion/drake/blob/b020aa7d0d69bd6c788f14dcf68387d55680783c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L51)):*
> ```objc
>   /// Gripping force to apply (in Newtons).
>   double grip_force{40.};
>   // The distance from the end effector link to the grasp frame
> ```

BTW s/to the grasp frame/to the grasp frame's origin/

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4GxlBMwGmBmnvyj-hz:-L4GxlBMwGmBmnvyj-i-:bfvz0rt) ([raw file](https://github.com/robotlocomotion/drake/blob/b020aa7d0d69bd6c788f14dcf68387d55680783c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L7)):*
> ```protobuf
>  // Note: The default values listed below assume that the messages are parsed
>  // using the functions in pick_and_place_configuration_parsing.h. Fields
>  // without a default value are required.
> ```

BTW Given this comment, both `grip_force` and `grasp_frame_translational_offset` should list their defaults.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4Gx0OR8age-czShkGa:-L4Gx0OR8age-czShkGb:b-andl0p) ([raw file](https://github.com/robotlocomotion/drake/blob/b020aa7d0d69bd6c788f14dcf68387d55680783c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L55)):*
> ```protobuf
> }
> 
> // Next ID: 5
> ```

BTW Bump the Next ID. I'm really sorry that I put those in there.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4GwufgeyP7t8wARe-3:-L4GwufhNcW3YnGKq0an:b-l87you) ([raw file](https://github.com/robotlocomotion/drake/blob/b020aa7d0d69bd6c788f14dcf68387d55680783c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L67)):*
> ```protobuf
>     // The gripping force to apply (in Newtons).
>     optional double grip_force = 4;
>     // The distance from the end effector link to the grasp frame
> ```

BTW s/to the grasp frame/to the grasp frame's origin/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-:-L4GyHD_JsDph-Ue-lMV:bggaue1)*

**Comment by sammy-tri** [comment]
+@soonho-tri for platform review

---

Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4GwhiMaNbCyWAW1MkB:-L4H9qlbZ0LyQWP4ikJJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b020aa7d0d69bd6c788f14dcf68387d55680783c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L51)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW s/to the grasp frame/to the grasp frame's origin/
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4GxlBMwGmBmnvyj-hz:-L4HAAXndxLOFkBr7nyQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b020aa7d0d69bd6c788f14dcf68387d55680783c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L7)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW Given this comment, both `grip_force` and `grasp_frame_translational_offset` should list their defaults.
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4Gx0OR8age-czShkGa:-L4HA3HVAPR8lBMzfAHp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b020aa7d0d69bd6c788f14dcf68387d55680783c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L55)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW Bump the Next ID. I'm really sorry that I put those in there.
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4GwufgeyP7t8wARe-3:-L4HA8Mfg8npyNHJgtQ6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b020aa7d0d69bd6c788f14dcf68387d55680783c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L67)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW s/to the grasp frame/to the grasp frame's origin/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-:-L4HAWVF495jX6TrMx0T:bcjsslk)*

**Comment by avalenzu** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7923)*

**Comment by soonho-tri** [comment]
:lgtm: (with a couple of questions)

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4HBH3ct-oguLctqI8b:-L4HBH3ct-oguLctqI8c:b-shdhtw) ([raw file](https://github.com/robotlocomotion/drake/blob/9e1a91dbf9e38927f0664f11e428e84cf569512c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L70)):*
> ```protobuf
>     // The distance from the end effector link to the grasp frame's
>     // origin (position between the fingertips of the gripper).
>     // DEFAULT: 0.19
> ```

BTW, I'm wondering:
 - Why do we have `= 5` below while its default is `0.19`? (ditto for the above `DEFAULT:40` vs. `= 4`)
 - Why do we have `0.19` here but have `0.191` below (in other files)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-:-L4HBapPy8e5JUZMx-KE:bdhbop1)*

**Comment by avalenzu** [comment]
*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4HBH3ct-oguLctqI8b:-L4HBhPXVBb2uBiBoVPX:b-t0ubar) ([raw file](https://github.com/robotlocomotion/drake/blob/9e1a91dbf9e38927f0664f11e428e84cf569512c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L70)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I'm wondering:
 - Why do we have `= 5` below while its default is `0.19`? (ditto for the above `DEFAULT:40` vs. `= 4`)
 - Why do we have `0.19` here but have `0.191` below (in other files)?
</blockquote></details>

The number at the end of a protobuf field definition is the integer id of the field. The defaults are determined by the parsing logic - not the protobuf definition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7923)*

**Comment by soonho-tri** [comment]
*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4HBH3ct-oguLctqI8b:-L4HCbOIR29EL9bAzpV6:b-ej0d45) ([raw file](https://github.com/robotlocomotion/drake/blob/9e1a91dbf9e38927f0664f11e428e84cf569512c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L70)):*
> The number at the end of a protobuf field definition is the integer id of the field. 
:facepalm:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7923)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4HBH3ct-oguLctqI8b:-L4HCfilsreCwXRdC0kG:b-fmhn5g) ([raw file](https://github.com/robotlocomotion/drake/blob/9e1a91dbf9e38927f0664f11e428e84cf569512c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L70)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> The number at the end of a protobuf field definition is the integer id of the field. 
:facepalm:

</blockquote></details>

The default (0.19) is assigned in `pick_and_place_configuration.h`.  The use of 0.191 in the yellow post config (which is loaded by the test, and is the other place that value occurs) is to check that parsing the config file successfully overrides the default.   (we don't have the opposite test (that the default appears when the field isn't specified) afaict).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7923)*

**Comment by soonho-tri** [comment]
*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7923#-L4HBH3ct-oguLctqI8b:-L4HDBRbTCBUV1jE7vdX:b-ejqvkb) ([raw file](https://github.com/robotlocomotion/drake/blob/9e1a91dbf9e38927f0664f11e428e84cf569512c/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto#L70)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The default (0.19) is assigned in `pick_and_place_configuration.h`.  The use of 0.191 in the yellow post config (which is loaded by the test, and is the other place that value occurs) is to check that parsing the config file successfully overrides the default.   (we don't have the opposite test (that the default appears when the field isn't specified) afaict).
</blockquote></details>

Yup, now I got it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7923)*

**Pull request merged**
