### PR TITLE
doc: Ensure website favicons render correctly on all platforms

### PR DESCRIPTION
**Pull request by jamiesnape**
Really all the images should be at the root. The promise of using link/meta tags does not really work out for every browser, but this should be an improvement. IE/Edge and Safari actually want yet another file each, but we can probably manage without them. And yes, favicons and website metadata is a mess. The extra icons are just conversions and resizes of the most detailed image.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14761)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
FWIW, the complete version would be
```html
<meta name="msapplication-config" content="browserconfig.xml" />
<link rel="apple-touch-icon" sizes="76x76" type="image/png" href="apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon" sizes="120x120" type="image/png" href="apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon" sizes="152x152" type="image/png" href="apple-touch-icon-152x152.png" />
<link rel="apple-touch-icon" sizes="180x180" type="image/png" href="apple-touch-icon-180x180.png" />
<link rel="icon" sizes="16x16" type="image/png" href="favicon-16x16.png" />
<link rel="icon" sizes="32x32" type="image/png" href="favicon-32x32.png" />
<link rel="icon" sizes="192x192" type="image/png" href="favicon-192x192.png" />
<link rel="icon" sizes="194x194" type="image/png" href="favicon-194x194.png" />
<link rel="manifest" type="application/manifest+json" href="site.webmanifest" />
<link rel="mask-icon" color="#ff0000" type="image/svg+xml" href="safari-pinned-tab.svg" />
```
with `site.webmanifest` and `browserconfig.xml` adding another six icons of various sizes and colors. Fun.

**Comment by jamiesnape** [comment]
Looks like maybe the `.ico` is disappearing elsewhere, so I will amend this. It does override the png in its current state.

**Comment by jamiesnape** [comment]
SGTM.

**Comment by jamiesnape** [comment]
Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14761)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jamiesnape and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14761#-MVTT3wF9qwDOY0CcZPa:-MVTT3wF9qwDOY0CcZPb:be2mcxe) (no related file):*
When certain images are derivatives of others, we have been documenting those details, e.g., at `doc/images/favicon.README.txt` which is now a little stale.  I assume some of these other new files are derivatives of source material?  I would like to continue the habit of noting the manually reprocessing the documentation, for traceability.

Given the bespoke filename patterns required by various devices, perhaps the doc/BUILD.bazel target for the `:favicon` filegroup would be a good place to write such documentation (replacing the current text file)?  

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14761)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jamiesnape and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14761#-MVTT3wF9qwDOY0CcZPa:-MVTTkhR66JN8N0wy78A:b-rzoel7) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When certain images are derivatives of others, we have been documenting those details, e.g., at `doc/images/favicon.README.txt` which is now a little stale.  I assume some of these other new files are derivatives of source material?  I would like to continue the habit of noting the manually reprocessing the documentation, for traceability.

Given the bespoke filename patterns required by various devices, perhaps the doc/BUILD.bazel target for the `:favicon` filegroup would be a good place to write such documentation (replacing the current text file)?  
</blockquote></details>

Hrm, lots of grammar-o's there.  I rather meant:

I would like to continue the habit of capturing in comments any manually-required image reprocessing, for traceability.

---

**Comment by jamiesnape** [comment]
Sorry, I somehow pushed my conflict resolution to master. Reverted immediately.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 9 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14761#-:-MVb9Mqi731ReHERaDnn:b-n37teh)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14761#-MVTT3wF9qwDOY0CcZPa:-MVb6xIVDMHRXP4O8Pkd:b-5e807u) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hrm, lots of grammar-o's there.  I rather meant:

I would like to continue the habit of capturing in comments any manually-required image reprocessing, for traceability.
</blockquote></details>

The BUILD comments are good now, but I think there is still a dangling `doc/images/favicon.README.txt` hanging around that we need to rm.

---
___
*[doc/BUILD.bazel, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14761#-MVb8GbE62NIAswFHH5p:-MVb8GbE62NIAswFHH5q:b-tqdspd) ([raw file](https://github.com/robotlocomotion/drake/blob/32eb02fb52fe03a3828b732d8ae891d22ef80fbf/doc/BUILD.bazel#L60)):*
> ```Starlark
>         # Manual resizing and padding of "assets/drake-dragon.png" to 32x32px
>         # and conversion to ICO format.
>         "favicon.ico",
> ```

The `favicon.ico` file in the PR seems to be 48x48, not 32x32 per this comment.  As best I can tell with some quick searching, it seems like 32x32 would be what we want.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14761)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14761#-MVTT3wF9qwDOY0CcZPa:-MVbLDyh18sYd_J9Qb68:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The BUILD comments are good now, but I think there is still a dangling `doc/images/favicon.README.txt` hanging around that we need to rm.
</blockquote></details>

Done.

---
___
*[doc/BUILD.bazel, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14761#-MVb8GbE62NIAswFHH5p:-MVbLFV87cWkgOhO0QHY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32eb02fb52fe03a3828b732d8ae891d22ef80fbf/doc/BUILD.bazel#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `favicon.ico` file in the PR seems to be 48x48, not 32x32 per this comment.  As best I can tell with some quick searching, it seems like 32x32 would be what we want.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14761)* status: needs at least two assigned reviewers (waiting on @jamiesnape)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with nit on more active documentation (use `covert` for simple resizing please)

> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14761#-:-MVq9t3F4NXerB80ZFNd:b-kgbq2h)* status: 1 unresolved discussion (waiting on @jamiesnape)

___
*[doc/BUILD.bazel, line 47 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14761#-MVq9MIT58_33cflAiml:-MVq9MIT58_33cflAimm:bpw7ylk) ([raw file](https://github.com/robotlocomotion/drake/blob/b55b3115b2fe22757d49758baafe6bb49376b4d9/doc/BUILD.bazel#L47)):*
> ```Starlark
>         # Manual resizing and padding of "assets/drake-dragon.png" to
>         # 192x192px.
>         "android-chrome.png",
> ```

nit While these comments are nice to have for synchronizing, it'd be better to just write out the scripted steps.

Please add these resizing steps to the following file, using `../` of course. (except for `mask-icon.svg`, 'cause weird)
https://github.com/RobotLocomotion/drake/blob/178275cba6308ed8205712a72a7a57b4a8aee6e9/doc/images/drake-dragon.README.txt#L16-L19

From here, please refer to that file.

**Comment by jamiesnape** [comment]
FWIW I guess I consider using `convert` manual resizing (there are great tools that shoot out every format for every icon known to man and browser).

**Comment by jamiesnape** [comment]
(Also a script should be a script, not a text file?)

**Comment by jwnimmer-tri** [comment]
For me, it was enough that the comments noted which files are created from which other files -- that's the most relevant fact to help future maintainers.  I don't think we're going to update the logo frequently enough to merit optimizing the maintainer process.

**Comment by jamiesnape** [comment]
Yes, I feel like (hope) all of this was a one off. Any future web developers should do this for us as a matter of routine.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14761)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @jamiesnape)

___
*[doc/BUILD.bazel, line 47 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14761#-MVq9MIT58_33cflAiml:-MVqxjza8GQYQSOhhKFB:b48liwj) ([raw file](https://github.com/robotlocomotion/drake/blob/b55b3115b2fe22757d49758baafe6bb49376b4d9/doc/BUILD.bazel#L47)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit While these comments are nice to have for synchronizing, it'd be better to just write out the scripted steps.

Please add these resizing steps to the following file, using `../` of course. (except for `mask-icon.svg`, 'cause weird)
https://github.com/RobotLocomotion/drake/blob/178275cba6308ed8205712a72a7a57b4a8aee6e9/doc/images/drake-dragon.README.txt#L16-L19

From here, please refer to that file.
</blockquote></details>

OK SGTM per above.;

**Pull request merged**
