### PR TITLE
pydrake: Include lcm in `pydrake.all`; Bind RBT's `Clone`; Add AngleAxis

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Some miscellaneous bindings while tinkering in Anzu.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@naveenoid for feature review, please.
+@seancurtis-tri for platform review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956#-:-LEVFliI-_4lal0LDUMY:brt4rfo)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with some questions and comments.

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 159 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVZE001SaK9GnnDA7l:-LEVZE01-SveAcJkke5e:b47kghu) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/multibody/rigid_body_tree_py.cc#L159)):*
> ```cpp
>          py::arg("model_instance_id") = -1)
>     .def("Clone", &RigidBodyTree<double>::Clone)
>     .def("__copy__", &RigidBodyTree<double>::Clone);
> ```

BTW I was pleasantly surprised to see that we have a `__copy__` override that exactly mirrors our `Clone` semantics.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVZdz079M5cUkH20Dt:-LEVZdz079M5cUkH20Du:b-adaudc) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/eigen_geometry_py.cc#L68)):*
> ```cpp
> 
> template <typename T>
> void CheckAngleAxis(const Eigen::AngleAxis<T>& angax) {
> ```

Styleguide violation in this abbreviation

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEV_Bnu53F-Mu8uqpp3:-LEV_Bnu53F-Mu8uqpp4:b-v35gl7) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/eigen_geometry_py.cc#L72)):*
> ```cpp
>   DRAKE_THROW_UNLESS(
>       norm_error < kCheckTolerance &&
>       "Axis is not normalized");
> ```

BTW An inventive solution to getting messages into `DRAKE_THROW_UNLESS` (reminiscent of the old `assert` usage). Strongly underscores the need for a `DRAKE_THROW_MESSAGE_UNLESS` macro.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 237 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVcICN9nR0390_9b-X:-LEVcICN9nR0390_9b-Y:b-paiuq0) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/eigen_geometry_py.cc#L237)):*
> ```cpp
>             self->w(), self->x(), self->y(), self->z());
>       })
>       // Do not define an operator until we have the Python3 `@` operator so
> ```

nit: seems like you're missing a word between "an" and "operator". I'm assuming what's missing is `__mul__`.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 280 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVdQLI8Uvrw3zTJIXx:-LEVdOEa9vIqgf9peMKD:bh1wnhh) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/eigen_geometry_py.cc#L280)):*
> ```cpp
>         Class update(angle, self->axis());
>         update.angle() = angle;
>         CheckAngleAxis(update);
> ```

BTW For my own edification, I'm surprised to see this happens *explicitly* in the python binding and not in the C++ code (and then simply wrapped). Can you comment?

Also, given that `CheckAngleAxis` only checks unit length of the axis, calling it here seems redundant (unless self had an invalid axis).

---

*[bindings/pydrake/util/test/eigen_geometry_test.py, line 138 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVdrs3DFiv7RlzxWlf:-LEVdrs44AAxCP97nrE9:b-x3viw) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/test/eigen_geometry_test.py#L138)):*
> ```Python
> 
>     def test_angle_axis(self):
>         angax_I = mut.AngleAxis.Identity()
> ```

Again, abbreviation is not styleguide compliant.

---

*[bindings/pydrake/util/test/eigen_geometry_test.py, line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVe6dX9FiOefB7TSAP:-LEVe6dX9FiOefB7TSAQ:b-cpo6fr) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/test/eigen_geometry_test.py#L140)):*
> ```Python
>         angax_I = mut.AngleAxis.Identity()
>         self.assertEqual(angax_I.angle(), 0)
>         self.assertTrue(np.allclose(angax_I.axis(), [1, 0, 0]))
> ```

Given the default tolerance of `np.allclose()` is 1e-8, this test is doubly dissatisfying. They should be *perfectly* identical and, failing that, should be identical to double precision.

The comment on the default testing tolerance applies to all invocations of `np.allclose()`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956#-:-LEVfA62Cijex5S7WJOc:b-19qyrn)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVZdz079M5cUkH20Dt:-LEWUE_PE7Ufu0Yd6niY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/eigen_geometry_py.cc#L68)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Styleguide violation in this abbreviation
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 280 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVdQLI8Uvrw3zTJIXx:-LEWTjVQE0nhDNQHO2PX:b-chp0zq) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/eigen_geometry_py.cc#L280)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW For my own edification, I'm surprised to see this happens *explicitly* in the python binding and not in the C++ code (and then simply wrapped). Can you comment?

Also, given that `CheckAngleAxis` only checks unit length of the axis, calling it here seems redundant (unless self had an invalid axis).
</blockquote></details>

Done. Deferring to a separate issue: https://github.com/RobotLocomotion/drake/issues/8958
Definitely needed, but I don't yet have the cycles to address it.

---

*[bindings/pydrake/util/test/eigen_geometry_test.py, line 138 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVdrs3DFiv7RlzxWlf:-LEWTTHQECO2eZ-neiIT:bjuiw33) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/test/eigen_geometry_test.py#L138)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Again, abbreviation is not styleguide compliant.
</blockquote></details>

Done.
I'm thinking I may soon submit an edit for the style guide to this; I certainly don't like abbreviations when ambiguous, but prefer them if their meaning is clear (or documented).

---

*[bindings/pydrake/util/test/eigen_geometry_test.py, line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVe6dX9FiOefB7TSAP:-LEWRvK6AEX7kjFUHA0y:b-r3iytr) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/test/eigen_geometry_test.py#L140)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Given the default tolerance of `np.allclose()` is 1e-8, this test is doubly dissatisfying. They should be *perfectly* identical and, failing that, should be identical to double precision.

The comment on the default testing tolerance applies to all invocations of `np.allclose()`.
</blockquote></details>

Done in current code. Deferred to a separate issue #8959 for checking tolerances on existing code.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/util/test/eigen_geometry_test.py, line 138 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVdrs3DFiv7RlzxWlf:-LEWYRDs9sRYDMq34zoj:b-o07lmb) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/test/eigen_geometry_test.py#L138)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
I'm thinking I may soon submit an edit for the style guide to this; I certainly don't like abbreviations when ambiguous, but prefer them if their meaning is clear (or documented).
</blockquote></details>

Good luck with that.  :)

---

*[bindings/pydrake/util/test/eigen_geometry_test.py, line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVe6dX9FiOefB7TSAP:-LEWYdBBE-PeMhCvn2hu:btx4vdy) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/test/eigen_geometry_test.py#L140)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done in current code. Deferred to a separate issue #8959 for checking tolerances on existing code.
</blockquote></details>

FTR The issue is #8958.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956)*

**Comment by SeanCurtis-TRI** [comment]
In retrospect, it seems that there are two references to issues. They reference the same issue number, but seem to capture two different issues.

1) The question of angle axis validation
2) using appropriate tolerances in `np.allclose()`.

The issue in question #8958 doesn't clearly apply to either and will require some archaeology to figure out what is being touched upon.

Also, please note the *very interesting* semantics for `np.allclose()` including both relative and absolute tolerances.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956#-:-LEWZ7h601yEJtLe73dR:b-49quxa)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/util/test/eigen_geometry_test.py, line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVe6dX9FiOefB7TSAP:-LEWbRIk-nrMNWdCF5pV:b-46sy7q) ([raw file](https://github.com/robotlocomotion/drake/blob/574ea8874a91a820980984d4566cc785dbbeb651/bindings/pydrake/util/test/eigen_geometry_test.py#L140)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FTR The issue is #8958.
</blockquote></details>

Ah, oops! (both the issue number and the issue itself).
In this PR, I have attempted to address those semantics that NumPy elected, and tried to clarify the issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956)*

**Comment by naveenoid** [comment]
One issue.. PTAL.

---

Review status: 1 unresolved discussion, LGTM missing from assignee naveenoid, platform LGTM from [seancurtis-tri]

---

*[bindings/pydrake/util/test/eigen_geometry_test.py, line 164 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEkVzT44adzTeXaRzxk:-LEkVzT44adzTeXaRzxl:b4dnxfp) ([raw file](https://github.com/robotlocomotion/drake/blob/c6ce4d7af4e080ff27973495a592f1eae016d25b/bindings/pydrake/util/test/eigen_geometry_test.py#L164)):*
> ```Python
>         value.set_quaternion(mut.Quaternion.Identity())
>         self.assertTrue((value.quaternion().wxyz() == [1, 0, 0, 0]).all())
> ```

What about symmetry checks on the rotation. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956#-:-LEkWewwBPWuEN_-0Jha:b1k5ac9)*

**Comment by EricCousineau-TRI** [comment]
Spoke with @naveenoid, and he said he'd be fine being removed from review given the level of review Sean has provided.

-@naveenoid for feature review

---

Review status: 1 unresolved discussion, LGTM missing from assignee naveenoid, platform LGTM from [seancurtis-tri]

---

*[bindings/pydrake/util/test/eigen_geometry_test.py, line 164 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEkVzT44adzTeXaRzxk:-LEkZAA15lc1py8QsKY7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c6ce4d7af4e080ff27973495a592f1eae016d25b/bindings/pydrake/util/test/eigen_geometry_test.py#L164)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

What about symmetry checks on the rotation. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956#-:-LEkUGVQ8RylIx5SPDH4:br0feun)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r5.
Review status: 1 unresolved discussion, platform LGTM from [seancurtis-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956)*

**Comment by SeanCurtis-TRI** [comment]
Assigned or not, @naveenoid seems to be blocking on his symmetry concern.

---

Review status: 1 unresolved discussion, platform LGTM from [seancurtis-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956#-:-LEkgGCT3tPHVE1J0lrZ:b6orz45)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [seancurtis-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956#-:-LElHSaM0x6EpwfHgAj8:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Oh jeepers, I had totally meant to delete that comment and keep him assigned - sorry for the confusion!

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [seancurtis-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8956#-:-LElcBC4E-PvFIE9_H9u:b-64lt69)*

**Pull request merged**
