### PR TITLE
Changed Bazel visibility of pydrake to public

### PR DESCRIPTION
**Pull request by mposa**
- Changed visibility of pydrake binding to be public. 
- Added pydrake binding for RigidBodyTree.drawKinematicTree

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8963)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
You should already be able to say `deps = ["@drake//bindings/pydrake"]` in downstream projects; the visibility changes should not be necessary.  (Perhaps replace that change with a comment reminding readers of the correct spelling?)

**Comment by mposa** [comment]
Unless I'm doing something wrong, the visibility declaration explicitly prohibits using it as a `dep`

```ERROR: /home/mposa/workspace/dairlib/examples/Cassie/BUILD.bazel:152:1: target '@drake//bindings/pydrake/multibody:rigid_body_tree_py' is not visible from target '//examples/Cassie:draw_graphviz'. Check the visibility declaration of the former target if you think the dependency is legitimate```

**Comment by jwnimmer-tri** [comment]
You should not try to declare a dependency on a subset of pydrake externally.  (I assume your BUILD file said `deps = ["@drake//bindings/pydrake/multibody:rigid_body_tree_py"]`?).  Just depend on `deps = ["@drake//bindings/pydrake"]` only and always.

**Comment by EricCousineau-TRI** [comment]
Yup, just depending on `@drake/bindings/pydrake` is the best mechanism right now. Even if you want to build a smaller portion, all portions of `pydrake` presently depend on `libdrake` due to #6760, so you'll have a large build time regardless of the granularity of your `pydrake` dependencies.

Here's an example usage in `drake-shambhala`:
https://github.com/RobotLocomotion/drake-shambhala/blob/798d43f/drake_bazel_external/apps/BUILD.bazel#L102-L109

If build times start to become a major pain, or if you start having runtime dependency conflicts (e.g. `drake`s VTK version conflicting with `pcl`s VTK version when loading to Python libs), would you be able to post on #6760? That way, I can up its priority; when that is done, we could incorporate the visibility portion of this PR.

For the time being, would you be OK with submitting a separate PR with the `drawKinematicTree` you've made?

**Comment by mposa** [comment]
Got it, thanks.

**Pull request closed without merging**
