### PR TITLE
Remove almost all special casing for ccache

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Apparently we don't need this anymore?  Perhaps because of our `CROSSTOOL` specifying absolute paths, perhaps because `action_env=PATH` is the default now.  For `unsupported_crosstool`, we can use an `action_env` setting to nerf `ccache` entirely.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6922)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6922#-KsdHRsV3OOtASVrZ-Np:-KsdHRsV3OOtASVrZ-Nq:bfkqm7m) ([raw file](https://github.com/robotlocomotion/drake/blob/5dfaa84befc001379a77ab0c812068a7e5004905/setup/ubuntu/16.04/install_prereqs.sh#L63)):*
> ```Shell
> apt install --no-install-recommends $(tr '\n' ' ' <<EOF
> 
> alien
> ```

BTW Can we remove `alien` and `fakeroot` from this list now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6922)*

**Comment by jwnimmer-tri** [comment]
For anyone testing this: the test procedure would be to pull this PR locally, re-run the `setup/ubuntu/16.04/install_prereqs.sh` script (so that `/usr/lib/ccache/bazel` gets removed), ensure that `/usr/lib/ccache` is in your your `$PATH`, and then try running bazel builds using your desired options (clang, GCC, debug, etc.).

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6922#-KseN6HVv5_XJP49mDh9:-KseN6HW-WmImdioxjX0:beixnf8) (no related file):*
Ipopt needs `export CCACHE_DISABLE=1` in `tools/ipopt_build_with_autotools.sh` for this to work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6922)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6922#-KsdHRsV3OOtASVrZ-Np:-Ksf1TqdWKNjNdCgQLVw:b-l5r1db) ([raw file](https://github.com/robotlocomotion/drake/blob/5dfaa84befc001379a77ab0c812068a7e5004905/setup/ubuntu/16.04/install_prereqs.sh#L63)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Can we remove `alien` and `fakeroot` from this list now?
</blockquote></details>

Done.  Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6922)*

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please (I'm looking for code review, not necessarily local testing).

+@soonho-tri for OSX developer testing and platform review, please.

+@sammy-tri for Ubuntu developer testing, please (just looking for local test, not code review).  Let me know if your test is Xenial or Trusty and I'll find another recruit for whichever is still missing.

+(priority: low) 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6922#-:-Ksf1jLGYl3yLse3PYjY:bodb8nl)*

**Comment by soonho-tri** [comment]
:lgtm:  + :apple: tested

---

Reviewed 8 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6922#-:-KshgtWXZauLJELqbwPy:bmob7q5)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6922#-:-Ksi-y_pexZA1Lqkwi5l:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm: tested on Xenial 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6922#-:-Ksiabaw5JQXXW_FaVFS:b2fsa18)*

**Comment by jadecastro** [comment]
+@jadecastro for Trusty testing.

**Comment by jadecastro** [comment]
Worked for me on Trusty :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6922#-:-KsiqzdiJ09GY6vFZZ1B:b-eiltcg)*

**Pull request merged**
