### PR TITLE
[systems/lcm] Indicate LCM connections in System graphviz output

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #20203.  Here's a demo using the command line given in #20198.  See also #20270 for related Meshcat change.

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20310)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
:lgtm: feature.

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20310#-:-NgA5rt28UZqsMJSKvPG:b-n37teh)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`systems/lcm/lcm_system_graphviz.h` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20310#-Ng9hZaM33_B9f5631MB:-Ng9hZaM33_B9f5631MC:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3d78bb21653f6e30b1fe6d4a48df75b5129c135/systems/lcm/lcm_system_graphviz.h#L25)):*
> ```objc
>   LcmSystemGraphviz helper(...);
>   return helper.DecorateResult(
>       Parent::DoGetGraphvizFragment(helper.DecorateParams(paraams)));
> ```

nit.



_Suggestion:_
```objc
params
```
___
*[`systems/lcm/lcm_system_graphviz.h` line 34 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20310#-Ng9ixFM3MATq9Dtg0q0:-Ng9ixFM3MATq9Dtg0q1:b-f8fssr) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3d78bb21653f6e30b1fe6d4a48df75b5129c135/systems/lcm/lcm_system_graphviz.h#L34)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(LcmSystemGraphviz);
> 
>   /* Specifies how to customize the Graphviz for a LCM-using System.
> ```

BTW. I googled a bit, but I am not completely sure it should be `an or a` before LCM.



_Code quote:_
```objc
a
```
___
*[`systems/lcm/lcm_system_graphviz.h` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20310#-Ng9ieZI6PX9CzCCPCL_:-Ng9ieZJDAQyvfNH7UUt:b-qvo4m9) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3d78bb21653f6e30b1fe6d4a48df75b5129c135/systems/lcm/lcm_system_graphviz.h#L35)):*
> ```objc
> 
>   /* Specifies how to customize the Graphviz for a LCM-using System.
>   @param lcm The interface pointer the system communicated with.
> ```

nit. If I am not mistaken, we are passing a const reference of an LCM object?



_Code quote:_
```objc
pointer
```
___
*[`systems/lcm/lcm_system_graphviz.h` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20310#-Ng9gQkQ-0ifmKuzp-M-:-Ng9gQkRDzUz6696EOJf:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3d78bb21653f6e30b1fe6d4a48df75b5129c135/systems/lcm/lcm_system_graphviz.h#L39)):*
> ```objc
>   @param message_type (Optional) The `typeid(lcmt_foo_bar)` type the system
>    publishes (or receives).
>   @param subscribe True iff the system publishes messages to LCM.
> ```

nit.



_Suggestion:_
```objc
publish
```

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20310)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; one test request below.

> Reviewed 20 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20310#-:-NgJi1bT215YeaPLb8s9:b-2ucrp0)* status: 1 unresolved discussion

___
*[`systems/lcm/test/lcm_system_graphviz_test.cc` line 106 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20310#-NgJhULW5LmhW5VENi_F:-NgJhULXAH5Xwzw0wkOb:b-tc8uhp) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2452098e3f05dcdb56796e911e5d34672da9fcb/systems/lcm/test/lcm_system_graphviz_test.cc#L106)):*
> ```cpp
>   EXPECT_EQ(result.fragments, result_orig.fragments);
> }
> ```

minor:  There doesn't seem to be any coverage of connection routing with multiple `DrakeLcm`s.  This is a marginal use case in vanilla Drake but a very common case downstream, so IMO it would be worth a test verifying that the connections into `DrakeLcm`s don't get tangled.
(The code appears correct, this is just a future-proofing request since it would be easy for someone in the future to "clean up" the hexbake out of the graphviz in a way that broke things.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20310)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),zachfang

___
*[`systems/lcm/test/lcm_system_graphviz_test.cc` line 106 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20310#-NgJhULW5LmhW5VENi_F:-NgJqAu6-qdrF_zP84wv:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2452098e3f05dcdb56796e911e5d34672da9fcb/systems/lcm/test/lcm_system_graphviz_test.cc#L106)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  There doesn't seem to be any coverage of connection routing with multiple `DrakeLcm`s.  This is a marginal use case in vanilla Drake but a very common case downstream, so IMO it would be worth a test verifying that the connections into `DrakeLcm`s don't get tangled.
(The code appears correct, this is just a future-proofing request since it would be easy for someone in the future to "clean up" the hexbake out of the graphviz in a way that broke things.)
</blockquote></details>

Done

**Pull request merged**
