### PR TITLE
Install kcov in Mac install_prereqs script

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7772)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
Nice! :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7772#-:-L3-Qx5dUStoE_iwyQBO:bfd61qr)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm: in the "the doc and code changes basically make sense to me" way (and trusting the platform reviewer a bit here)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7772#-:-L3-l6QJ2PADQHLUYezA:b-88kdgm)*

**Pull request merged**
