### PR TITLE
Toward #3029: remove DOS-style line endings from more files.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Not adjusted were any files in the thirdParty/ sub-tree.

One author's name was converted from some old code page to UTF-8.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3076)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by rpoyner-tri** [comment]
+@david-german-tri for both levels of review

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3076#-:-KOR3IIk7bNopzLDkTpv:b-e3m029)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3076#-:-KORI-uTK3skDohaH5Hp:1417088721)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot: windows-msvc-ninja-64-experimental-matlab please

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3076#-:-KORIAvsWgyMP6_aTggH:-1875976305)*

**Comment by david-german-tri** [comment]
I can't imagine this will actually break MATLAB on Windows, but might as well check.

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3076#-:-KORIHTtJ8I4RyEEv3m5:-1370985718)*

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot: windows-msvc-ninja-64-experimental-matlab please

**Comment by rpoyner-tri** [comment]
latin-1 to utf8 conversion withdrawn; Windows had a fit.

**Pull request merged**
