### PR TITLE
python bindings for lqr

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8115)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for both reviews, please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8115#-:-L5otXcexmtRf9gPXi5u:bkzm1k4)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/controllers_py.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8115#-L5oxqN4o-KHyRQNy88X:-L5oxqN5c_C4nV4N-oKm:b-dgilaz) ([raw file](https://github.com/robotlocomotion/drake/blob/3bf5ecff0aee371c7ff0b14107458ba58f34db87/bindings/pydrake/systems/controllers_py.cc#L73)):*
> ```cpp
>            const Eigen::Ref<const Eigen::MatrixXd>& N) {
>           auto result = LinearQuadraticRegulator(A, B, Q, R, N);
>           return std::make_pair(result.K, result.S);
> ```

To python we return K, S but the C++ struct's order of fields is S, K.  This seems misleading.

I'd accept either the C++ struct changing its order, or a comment or py::doc here, or returning a py::object with `.K` and `.S` attributes, or returning a py::dict with `"K"` and `"S"` keys, or etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8115#-:-L5oyi6EIbxUyNe0Q5VM:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/controllers_py.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8115#-L5oxqN4o-KHyRQNy88X:-L5ozYt-H3YIQ4x8H34u:bb6hf33) ([raw file](https://github.com/robotlocomotion/drake/blob/3bf5ecff0aee371c7ff0b14107458ba58f34db87/bindings/pydrake/systems/controllers_py.cc#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To python we return K, S but the C++ struct's order of fields is S, K.  This seems misleading.

I'd accept either the C++ struct changing its order, or a comment or py::doc here, or returning a py::object with `.K` and `.S` attributes, or returning a py::dict with `"K"` and `"S"` keys, or etc.
</blockquote></details>

Done.

i changed the order of the c++ struct.  i think it must be K first, because of the precedent set by https://www.mathworks.com/help/control/ref/lqr.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8115)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8115)*

**Pull request merged**
