### PR TITLE
add PontryaginDifference to HPolyhedron

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17056)

### CODE REVIEW

**Comment by RussTedrake** [comment]
*[`geometry/optimization/hpolyhedron.h` line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0osvkv1B7_5EBO0glR:-N0osvkv1B7_5EBO0glS:bjft7if) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/hpolyhedron.h#L108)):*
> ```objc
>   /** Returns the Pontryagin (Minkowski) Difference of `this` and `other`.
>    * Requires that this and other both be bounded and
>    * have the same ambient dimension*/
> ```

can we add 
A ⊖ B = { a|a+ B ⊆ A }
to this doc string?

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17056)* status: 9 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/hpolyhedron.h` line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0huEedEd8Ykq8qlDlr:-N0huEedEd8Ykq8qlDls:b-kxi5gc) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/hpolyhedron.h#L107)):*
> ```objc
> 
>   /** Returns the Pontryagin (Minkowski) Difference of `this` and `other`.
>    * Requires that this and other both be bounded and
> ```

nit: the comment style here is different than in the rest of the header.  can you remove the leading * on the second and third lines?
___
*[`geometry/optimization/hpolyhedron.h` line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0osvkv1B7_5EBO0glR:-N0oxl0KAwizAiG0Dlwh:b-d4jjc1) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/hpolyhedron.h#L108)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

can we add 
A ⊖ B = { a|a+ B ⊆ A }
to this doc string?
</blockquote></details>

it might also be worth saying that the number of faces in the result is = to the number of faces in A?
___
*[`geometry/optimization/hpolyhedron.cc` line 274 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0otZWu4j-FNULg99RA:-N0otZWu4j-FNULg99RB:bu6u1w5) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/hpolyhedron.cc#L274)):*
> ```cpp
> HPolyhedron HPolyhedron::PontryaginDifference(const HPolyhedron& other) const {
>   /**
>    * The Pontryagin set difference of Polytope P = {x | Ax <= b_diff} and
> ```

why b_diff here instead of just b?
___
*[`geometry/optimization/hpolyhedron.cc` line 285 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0otkty3A_2XcY7NmH9:-N0otkty3A_2XcY7NmHA:b-3t4r56) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/hpolyhedron.cc#L285)):*
> ```cpp
> 
>   Eigen::VectorXd b_diff(b_.rows());
>   b_diff << b_;
> ```

surely you can write just the one line `Eigen::VectorXd b_diff(b_);`
___
*[`geometry/optimization/hpolyhedron.cc` line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0ouCgg5oKeClFqpknE:-N0ouCgg5oKeClFqpknF:b8ygxsd) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/hpolyhedron.cc#L289)):*
> ```cpp
>   solvers::VectorXDecisionVariable x =
>       prog.NewContinuousVariables(ambient_dimension_, "x");
>   prog.AddLinearConstraint(other.A(),
> ```

i normally write a comment line with the math version.  here
// -inf <= Ax <= b 
___
*[`geometry/optimization/hpolyhedron.cc` line 314 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0ovxC_AFnzGRqOpIAl:-N0ovxC_AFnzGRqOpIAm:bae0n2p) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/hpolyhedron.cc#L314)):*
> ```cpp
>           result.get_solver_id().name(), result.get_solution_result()));
>     }
>     b_diff(i) = b_diff(i) + result.get_optimal_cost();
> ```

seems like it would almost be more clear here to skip the initialization above and just write b_diff(i) = b_(i) + result.get_optimal_cost();
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 478 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0oxdcI7VLmdfKazaEf:-N0oxdcI7VLmdfKazaEg:b21g24q) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/test/hpolyhedron_test.cc#L478)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(H_C.A(), A_expected, 1e-8));
>   EXPECT_TRUE(CompareMatrices(H_C.b(), b_expected, 1e-8));
> }
> ```

can we add a small test (even in 2d) where the number of faces in H_A and H_B are different?  For instance the same test as this but where H_B is just a triangle instead of a box?  
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0oy0iT1jLbDrfTttJB:-N0oy0iT1jLbDrfTttJC:b-tsrjbd) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/test/hpolyhedron_test.cc#L491)):*
> ```cpp
>        -1,  1, -1,
>        -1, -1,  1,
>        -1, -1, -1;
> ```

seems like HPolyhedron::MakeBox would be cleaner?
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 500 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0oyOWHElaj5CucqF7E:-N0oyOWHElaj5CucqF7F:bl27m4g) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/test/hpolyhedron_test.cc#L500)):*
> ```cpp
> 
>   Matrix<double, 6, 3> A_expected;
>   Eigen::VectorXd b_expected = Eigen::VectorXd::Constant(6, 0.5);
> ```

again makebox could work.  (I just want the test to be even more legible)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: +@xuchenhan-tri for platform review, per rotation.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17056#-:-N0uzgNQBXpO36svm2Yz:b-dkmjbt)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

___
*[`geometry/optimization/hpolyhedron.h` line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0osvkv1B7_5EBO0glR:-N0uytDi8qEVW-uIgnCJ:b-k31fb4) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/hpolyhedron.h#L108)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

> A ⊖ B = { a|a+ B ⊆ A }

Done for the first comment. Is there a reason for the second comment beyond notifying the user of the resulting size of the return? For example in Intersect we don't make note of this.
</blockquote></details>

I just think it would be helpful.  I hadn't thought through the implications of this set difference before, and this seems a simple property to note that would be potentially informative for readers. 
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0oy0iT1jLbDrfTttJB:-N0uzT1m0S7WhrXZM_TA:baz7buo) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/test/hpolyhedron_test.cc#L491)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This is the L1 box scaled to have corners at 0.5 instead of 1. It is intentionally not axis aligned in this test.
</blockquote></details>

of course.  got it.

**Comment by jwnimmer-tri** [comment]
*[`geometry/optimization/test/hpolyhedron_test.cc` line 491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N0oy0iT1jLbDrfTttJB:-N0v3e7y0fbOIMEvYhO6:bs693rp) ([raw file](https://github.com/robotlocomotion/drake/blob/405716248d19b5b40b98c6ed6772663ad43908c2/geometry/optimization/test/hpolyhedron_test.cc#L491)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

of course.  got it.  
</blockquote></details>

If it didn't register with Russ upon first read, it's likely that it would also not register for others.  It's probably worth adding a comment _"L1 box scaled to have corners at 0.5 instead of 1; it is intentionally not axis aligned in this test."_ in this test case, to make it clear to future readers.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: with a few minor points and a binding error.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17056#-:-N11cgHpBaO9zR4-QvEt:b6d24o6)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/hpolyhedron.cc` line 276 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11acui8L5Z4hLgIifQ:-N11acui8L5Z4hLgIifR:blxodvk) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/geometry/optimization/hpolyhedron.cc#L276)):*
> ```cpp
>    * The Pontryagin set difference of Polytope P = {x | Ax <= b} and
>    * Q = {x | Cx <= d} can be computed P - Q = {x | Ax <= b - h}
>    * where h_i = max a_i^Tx subject to x \in Q
> ```

BTW, this line can read more nicely with 

where hᵢ = max aᵢᵀx subject to x ∈ Q.
___
*[`geometry/optimization/hpolyhedron.cc` line 302 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11b-7EEEGWzIN5jn_H:-N11b-7EEEGWzIN5jn_I:b7wp25w) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/geometry/optimization/hpolyhedron.cc#L302)):*
> ```cpp
>   Binding<solvers::LinearCost> program_cost_binding =
>       prog.AddLinearCost(A_.row(0), 0, x);
>   for (int i = 0; i < b_.rows(); i++) {
> ```

nit use ++i instead of i++.
___
*[`geometry/optimization/hpolyhedron.cc` line 308 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11bAa77GL_j11-XuNA:-N11bAa77GL_j11-XuNB:b-nbxud1) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/geometry/optimization/hpolyhedron.cc#L308)):*
> ```cpp
>     // always have an optimal solution
>     if (!result.is_success()) {
>       throw std::runtime_error(fmt::format(
> ```

nit, this throw condition should be documented.
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 465 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11c7to-ldd0VrNhNmt:-N11c7to-ldd0VrNhNmu:b-73s4wp) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/geometry/optimization/test/hpolyhedron_test.cc#L465)):*
> ```cpp
> 
> GTEST_TEST(HPolyhedronTest, PontryaginDifferenceTestAxisAligned) {
>   HPolyhedron H_A = HPolyhedron::MakeUnitBox(2);
> ```

nit, use `const` liberally in tests. For example, making `H_A` `const` would prevent someone making the function `PontryaginDifference` non-const without thinking.
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 498 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11cR801HPkzLpOqRyk:-N11cR801HPkzLpOqRyl:b5vhpjq) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/geometry/optimization/test/hpolyhedron_test.cc#L498)):*
> ```cpp
> }
> 
> GTEST_TEST(HPolyhedronTest, PontryaginDifferenceTest2) {
> ```

BTW, it'd be nice to comment on the testing strategy here. What's this test covering that the previous two aren't covering? Alternatively, a more descriptive name would also help.
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 517 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11bqJ15e9qt90j72f_:-N11bqJ15e9qt90j72fa:btfjui9) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/geometry/optimization/test/hpolyhedron_test.cc#L517)):*
> ```cpp
>   HPolyhedron H_C = H_A.PontryaginDifference(H_B);
> 
>   Matrix<double, 6, 3> A_expected;
> ```

Are A_expected and b_expected used at all?
___
*[`bindings/pydrake/geometry_py_optimization.cc` line 133 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11bKWv4345NYZsXptd:-N11bKWv4345NYZsXpte:be97cgf) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/bindings/pydrake/geometry_py_optimization.cc#L133)):*
> ```cpp
>             cls_doc.Intersection.doc)
>         .def("PontryaginDifference", &HPolyhedron::PontryaginDifference,
>             py::arg("other"), cls_doc.Intersection.doc)
> ```

This seems like a copy-pasta error. We surely don't want the doc of the `Intersection` function.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17056)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

___
*[`geometry/optimization/hpolyhedron.cc` line 308 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11bAa77GL_j11-XuNA:-N141Q_0369YMkqo6KIV:brtsu2c) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/geometry/optimization/hpolyhedron.cc#L308)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this throw condition should be documented.
</blockquote></details>

What is the proper way to document such a throw condition. This should only happen due to some numerical issue in the description of the polytope?
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 517 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11bqJ15e9qt90j72f_:-N148WhS85ymEs8EhEFy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/geometry/optimization/test/hpolyhedron_test.cc#L517)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Are A_expected and b_expected used at all?
</blockquote></details>

Done.
___
*[`bindings/pydrake/geometry_py_optimization.cc` line 133 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11bKWv4345NYZsXptd:-N148SHh0ZD5zDCdWwQf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/bindings/pydrake/geometry_py_optimization.cc#L133)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This seems like a copy-pasta error. We surely don't want the doc of the `Intersection` function.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17056)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/hpolyhedron.cc` line 308 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17056#-N11bAa77GL_j11-XuNA:-N14Zw6O41NuwnEoqHhU:bfbtms6) ([raw file](https://github.com/robotlocomotion/drake/blob/5613be2bf63f271c0dfb5cf5245f06b8d20a680c/geometry/optimization/hpolyhedron.cc#L308)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

What is the proper way to document such a throw condition. This should only happen due to some numerical issue in the description of the polytope?
</blockquote></details>

I'd just document this as is -- It may throw due to numerical issues if the polytope is ill conditioned. It'd be even better if we can quantify what "ill-conditioned" means here, but that may be hard.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17056)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17056#-:-N15Wf42-WQUeFcpgXCM:b-c7f1bi)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17056)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Comment by xuchenhan-tri** [comment]
+(status: squashing now)

**Pull request merged**
