### PR TITLE
Small fix in SLIP example

### PR DESCRIPTION
**Pull request by sheim**
In the stance2flight transition, the jacobian dxpdxm gets a bogus additional dimension with the line `dxpdxm(2,6)=1;` which shouldn't be there. There are similar lines in the flight2stance transition, which are commented out, so I'm guessing someone had an additional state and just forgot to uncomment the line. 
(Either way doesn't affect the simulation).

I just commented the line, but if whoever originally wrote this doesn't need the reminder, imho it would be cleaner to just delete them.

### CODE REVIEW

**Comment by RussTedrake** [comment]
Then let's zap it.  Thx

**Comment by sheim** [comment]
Btw, there's also an error being thrown flight2stance, `error('still need to update this last one:');`, but I've gone through the jacobian and everything seems to check out. Mind if I zap that too?

**Comment by RussTedrake** [comment]
Yes

**Comment by sheim** [comment]
Sorry, but is that a "yes I mind" or "yes, zap it"?

**Comment by RussTedrake** [comment]
Yes, zap it.  :)

**Comment by RussTedrake** [comment]
test this please

**Comment by sheim** [comment]
I was getting the same errors as Twan in #1687 (out of heap memory etc.,) just checking if those are resolved.

**Comment by RussTedrake** [comment]
test this please

**Comment by RussTedrake** [comment]
The current thinking is that they will not be resolved, except by taking that
aging build server offline. We’re working on bringing up a newer win32 build
server as a replacement.

**Pull request merged**
