### PR TITLE
Refactor SuperNodalSolver to allow alternative implementation

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Move the original `supernodal_solver.h/.cc` to `conex_supernodal_solver.h/.cc` and rename the class from `SuperNodalSolver` to `ConexSuperNodalSolver`.

Introduce a new base class that assumes the name `SuperNodalSolver` that the new `ConexSuperNodalSolver` derives from.

Some of the free helper functions in the *old* `supernodal_solver.cc` are moved to the *new* `supernodal_solver.h` file so that all derived class can make use of them.

The unit tests are also changed to to `TYPED_TEST` in anticipation of an alternative implementation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19654)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) +(status: commits are properly curated) +(release notes: none) 
+@joemasterjohn for feature review please. Here's another piece that can be reviewed while we wait for #19535.
The diffs appears daunting but it's mostly moving code around.

I broke the PR into two commits to preserve git history and make reviewing easier. The first commit is purely file renaming. All meaningful changes are in the second commit.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-:-NYVEQMXDa__e87GNyXA:bl9f4mu)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
@amcastro-tri fyi this is the supernodal refactor PR I mentioned in our f2f.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-:-NYZwUqv10hCGxVg5rmo:b3uvqz8)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by joemasterjohn — COMMENTED** [review]
Sorry for the delay. Looking at this now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-:-NYxO4VQ2zu6oNkiJIT8:b-b0hzsf)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: a few nits sprinkled here and there. +@sammy-tri for platform review, please.

> Reviewed 2 of 9 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-:-NYy3CtH8s_uhtPd0Ygc:bgwb7cx)* status: 7 unresolved discussions, LGTM missing from assignee sammy-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

___
*[`multibody/contact_solvers/supernodal_solver.h` line 83 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYxWbR5-UCe8n_vLRy7:-NYxWbR5-UCe8n_vLRy8:b-wuf0cw) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L83)):*
> ```objc
>   SuperNodalSolver() = default;
> 
>   // @group NVI implementations. Specific constraints must implement these
> ```

nit: comment copy/pasta



_Suggestion:_
```objc
  // @group NVI implementations. Specific solvers must implement these
```
___
*[`multibody/contact_solvers/supernodal_solver.h` line 87 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYxXFdR8fzOTaZ8yMFw:-NYxXFdR8fzOTaZ8yMFx:b-5enm3m) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L87)):*
> ```objc
>   // @{
> 
>   // Returns true iff the weight matrix is compatible with the jacobian matrix
> ```

nit: I tend to capitalize "Jacobian" if writing it in text/comment. I don't think we have a standardization of this though, so feel free to ignore.



_Suggestion:_
```objc
Jacobian
```
___
*[`multibody/contact_solvers/supernodal_solver.h` line 92 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYxXiEt7-xHViuWIn4M:-NYxXiEt7-xHViuWIn4N:b-bmqi7w) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L92)):*
> ```objc
>       const std::vector<Eigen::MatrixXd>& block_diagonal_G) = 0;
> 
>   virtual Eigen::MatrixXd DoMakeFullMatrix() const = 0;
> ```

nit: maybe just a small comment for back reference:
```
@see MakeFullMatrix()
```
___
*[`multibody/contact_solvers/supernodal_solver.h` line 101 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYxXoopE1g2TusbO_3I:-NYxXoopE1g2TusbO_3J:b-tnoc8t) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L101)):*
> ```objc
>   virtual void DoSolveInPlace(Eigen::VectorXd* b) const = 0;
> 
>   virtual int DoGetSize() const = 0;
> ```

nit: maybe just a small comment for back reference:
```
// @see GetSize()
```
___
*[`multibody/contact_solvers/supernodal_solver.h` line 117 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYy-VsCCmR_Sw2g84pG:-NYy-VsCCmR_Sw2g84pH:b-aum8l4) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L117)):*
> ```objc
> // sparse Jacobian. The entries in `jacobian_blocks` must satisfy the
> // following property:
> //  1.  {T.i|T∈`jacobian_blocks`}  = {0, 1, ..., num_row_blocks-1}, and
> ```

nit: maybe slightly more readable formatting



_Suggestion:_
```objc
//  1. {T.i | T ∈ `jacobian_blocks`} = {0, 1, ..., num_row_blocks-1} and
```
___
*[`multibody/contact_solvers/supernodal_solver.h` line 118 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYy0BgT4QVFMh_oBap1:-NYy0BgT4QVFMh_oBap2:b-ayq4en) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L118)):*
> ```objc
> // following property:
> //  1.  {T.i|T∈`jacobian_blocks`}  = {0, 1, ..., num_row_blocks-1}, and
> //  2.  for each k in {0, 1, ..., num_row_blocks - 1}, |{T|T.i==k}| <= 2.
> ```

nit: to match the pre-condition you state below.



_Suggestion:_
```objc
//  2. For each k in {0, 1, ..., num_row_blocks - 1}, 1 <= |{T|T.i==k}| <= 2.
```
___
*[`multibody/contact_solvers/supernodal_solver.h` line 131 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYy0tR99C8FqJbikc_e:-NYy0tR99C8FqJbikc_f:bp6tzvy) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L131)):*
> ```objc
> // Verifies the entries in `jacobian_blocks` are valid in the sense that they
> // satisfy:
> //  1. {T.j|T∈`jacobian_blocks`}  = {0, 1, ..., max T.j}, and
> ```

nit: slightly more readable formatting.



_Suggestion:_
```objc
//  1. { T.j | T ∈ `jacobian_blocks`} = {0, 1, ..., max T.j}, and
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19654)* status: LGTM missing from assignee sammy-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

___
*[`multibody/contact_solvers/supernodal_solver.h` line 83 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYxWbR5-UCe8n_vLRy7:-NYy_3n1CJ_ZaJCaK7Yu:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L83)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: comment copy/pasta
</blockquote></details>

Done
___
*[`multibody/contact_solvers/supernodal_solver.h` line 87 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYxXFdR8fzOTaZ8yMFw:-NYy_9-y0sOQv6nM2exw:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L87)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: I tend to capitalize "Jacobian" if writing it in text/comment. I don't think we have a standardization of this though, so feel free to ignore.
</blockquote></details>

Done
___
*[`multibody/contact_solvers/supernodal_solver.h` line 92 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYxXiEt7-xHViuWIn4M:-NYy_FqT4mpS_HgljJO9:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L92)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: maybe just a small comment for back reference:
```
@see MakeFullMatrix()
```
</blockquote></details>

Done
___
*[`multibody/contact_solvers/supernodal_solver.h` line 101 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYxXoopE1g2TusbO_3I:-NYy_GwQ6-XLzAya0S1e:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L101)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: maybe just a small comment for back reference:
```
// @see GetSize()
```
</blockquote></details>

Done
___
*[`multibody/contact_solvers/supernodal_solver.h` line 117 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYy-VsCCmR_Sw2g84pG:-NYy_e24-y6C3V3_VhPs:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L117)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: maybe slightly more readable formatting
</blockquote></details>

Done
___
*[`multibody/contact_solvers/supernodal_solver.h` line 118 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYy0BgT4QVFMh_oBap1:-NYy_er019lp6lt8GGjE:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L118)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: to match the pre-condition you state below.
</blockquote></details>

Done
___
*[`multibody/contact_solvers/supernodal_solver.h` line 131 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-NYy0tR99C8FqJbikc_e:-NYy_pBW-objglGok4rA:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1de0c587e25dbf3cb88fdf6a2e02863631dcdb7/multibody/contact_solvers/supernodal_solver.h#L131)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: slightly more readable formatting.
</blockquote></details>

Done

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 9 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-:-NYysz39BmVXO79GRqNc:bnfp4nl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Rebased on master.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19654#-:-NYyw9h4-sCYf12Jc15X:bc65pbk)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),joemasterjohn, base commit is latest master

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19654)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),joemasterjohn, base commit is latest master

**Pull request merged**
