### PR TITLE
[py symbolic] Enable matrix inversions

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates investigations in #18816

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18823)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai for feature review, please!

\cc @RussTedrake @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-:-NOglBu57-JQ3BsAHfyQ:bx1u1ta)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for platform review

Cool!  I didn't realize it worked up to 4x4.  Nice.

:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-:-NOgqBKo3WmtT3WONqdE:bm5h6s8)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[`common/symbolic/expression/test/expression_matrix_test.cc` line 576 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-NOgpl5pAlhPQi2PDis7:-NOgpl5pAlhPQi2PDis8:b-1phfas) ([raw file](https://github.com/RobotLocomotion/drake/blob/c859809a879caa380e39d4bd08585a31debf16ee/common/symbolic/expression/test/expression_matrix_test.cc#L576)):*
> ```cpp
> // Matrix<double>::inverse() is used.
> // Also that it fails for matrices larger than 4x4 and any dynamically-sized
> // matrix.
> ```

nit: you don't show that it fails for dynamically-sized matrices (though I wouldn't be surprised).

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-:-NOjsG2S3ekM-sfQj28E:bg7igkv)* status: 2 unresolved discussions, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`common/symbolic/expression/test/expression_matrix_test.cc` line 561 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-NOjs7o0CTIkZ2AKYjbk:-NOjs7o1EkfxV4pGzj_4:b-h5o15o) ([raw file](https://github.com/RobotLocomotion/drake/blob/c859809a879caa380e39d4bd08585a31debf16ee/common/symbolic/expression/test/expression_matrix_test.cc#L561)):*
> ```cpp
>                               Substitute(M, subst).inverse(), 1e-10));
>   // Show that the dynamically-sized variant fails.
>   Eigen::MatrixX<Expression> Mdyn = M;
> ```

CI complains this, change `Eigen::MatrixX` to `MatrixX`

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18823)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai and @RussTedrake)

___
*[`common/symbolic/expression/test/expression_matrix_test.cc` line 561 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-NOjs7o0CTIkZ2AKYjbk:-NOkHPuyAqWFOud7Qwo1:b-zgypm5) ([raw file](https://github.com/RobotLocomotion/drake/blob/c859809a879caa380e39d4bd08585a31debf16ee/common/symbolic/expression/test/expression_matrix_test.cc#L561)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

CI complains this, change `Eigen::MatrixX` to `MatrixX` 
</blockquote></details>

Done, thanks! Didn't realize newer Eigen (on Jammy) had this alias and older version (on Focal) did not.
___
*[`common/symbolic/expression/test/expression_matrix_test.cc` line 576 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-NOgpl5pAlhPQi2PDis7:-NOkHVEq1UDG_T-FJtnb:b1uz5uj) ([raw file](https://github.com/RobotLocomotion/drake/blob/c859809a879caa380e39d4bd08585a31debf16ee/common/symbolic/expression/test/expression_matrix_test.cc#L576)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: you don't show that it fails for dynamically-sized matrices (though I wouldn't be surprised).  
</blockquote></details>

Done. It actually was there, but may've not been obvious. Shuffled comments around to try and make it more indicative.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18823)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai and @RussTedrake)

___
*[`common/symbolic/expression/test/expression_matrix_test.cc` line 579 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-NOkHt0l2FHzY2_AXxQS:-NOkHt0l2FHzY2_AXxQT:b-atr0la) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb6fe9b14a72833d8807970765e85b24e655bf09/common/symbolic/expression/test/expression_matrix_test.cc#L579)):*
> ```cpp
> // Positive tests for symbolic inversion of 1x1, 2x2, 3x3, and 4x4 matrices.
> // Shows negative case for 5x5 matrix.
> TEST_F(SymbolicExpressionMatrixTest, Inverse) {
> ```

Working: Should show that dynamically sized float-convertible symbolic matrices are doable.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18823)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai and @RussTedrake)

___
*[`common/symbolic/expression/test/expression_matrix_test.cc` line 579 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-NOkHt0l2FHzY2_AXxQS:-NOkLB9I72LdLTCwt2DA:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb6fe9b14a72833d8807970765e85b24e655bf09/common/symbolic/expression/test/expression_matrix_test.cc#L579)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should show that dynamically sized float-convertible symbolic matrices are doable.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18823)* status: missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`common/symbolic/expression/test/expression_matrix_test.cc` line 576 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18823#-NOgpl5pAlhPQi2PDis7:-NOkvvhdD32fn3p9yjOI:b-gfmdqa) ([raw file](https://github.com/RobotLocomotion/drake/blob/c859809a879caa380e39d4bd08585a31debf16ee/common/symbolic/expression/test/expression_matrix_test.cc#L576)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. It actually was there, but may've not been obvious. Shuffled comments around to try and make it more indicative.
</blockquote></details>

Oops.  sorry i missed it.

**Comment by EricCousineau-TRI** [comment]
Thanks!

**Pull request merged**
