### PR TITLE
replace bool in SystemConstraint constructor with enum SystemConstraintType

### PR DESCRIPTION
**Pull request by RussTedrake**
to improve readability
(and leave room for other constraint types in the future)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7146)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for both levels of review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7146#-:-KvK74GMM_M-BNjxFwea:bdxk4pd)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system_constraint.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7146#-KvSYgS7-rA5cIGGVaC8:-KvSYgS8pDyl7aoP6OkQ:b2io6tm) ([raw file](https://github.com/robotlocomotion/drake/blob/ea1cbdeede9949e03084ea1ac32c7fe542213286/drake/systems/framework/system_constraint.h#L70)):*
> ```objc
>   ///
>   /// @param count the number of constraints (size of the value vector).
>   /// @param type the SystemConstraintType.
> ```

BTW super minor nit Specifying the same type as what's in the signature with nothing else seems a tad redundant. Could this be described as a phrase, "the system constraint type"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7146#-:-KvSZ0cTnsxLhRrFvR9b:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system_constraint.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7146#-KvSYgS7-rA5cIGGVaC8:-KvT4LbBgSd2ApdeRzZu:b-d1scwy) ([raw file](https://github.com/robotlocomotion/drake/blob/ea1cbdeede9949e03084ea1ac32c7fe542213286/drake/systems/framework/system_constraint.h#L70)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW super minor nit Specifying the same type as what's in the signature with nothing else seems a tad redundant. Could this be described as a phrase, "the system constraint type"?
</blockquote></details>

that seems actually less informative?  hope it's ok...   i'll click this one through (that line wasn't touched on this PR)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7146)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system_constraint.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7146#-KvSYgS7-rA5cIGGVaC8:-KvT4ec9OX2zc0i6o8sh:bcdi388) ([raw file](https://github.com/robotlocomotion/drake/blob/ea1cbdeede9949e03084ea1ac32c7fe542213286/drake/systems/framework/system_constraint.h#L70)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

that seems actually less informative?  hope it's ok...   i'll click this one through (that line wasn't touched on this PR)?
</blockquote></details>

ah... got my PRs mixed.  it was touched.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7146)*

**Pull request merged**
