### PR TITLE
Add bazel coverage option, add --config=kcov_everything to bazel.rc

### PR DESCRIPTION
**Pull request by KyleFromKitware**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7823)

### CODE REVIEW

**Comment by KyleFromKitware** [comment]
+@jamiesnape for feature review
+@ericcousineau-tri for platform review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7823#-:-L3U68b3O44vierWS-my:b-v3v1wa)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7823#-L3UERZFEHSRpElbN1DI:-L3UERZGgs1QuTPz8C_k:bwzwtnn) (no related file):*
Meta: Could this PR be renamed to specify that it adds `--config=kcov-everything` to `bazel.rc`?

---

*[examples/kuka_iiwa_arm/BUILD.bazel, line 128 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7823#-L3UE2njG7MvNEllluJG:-L3UE2nlK4YiJY7rt_E8:brc4ex2) ([raw file](https://github.com/robotlocomotion/drake/blob/1edf1db3a415192923c802d3df4af7c380ab3324/examples/kuka_iiwa_arm/BUILD.bazel#L128)):*
> ```Python
>         "//drake/manipulation/models/iiwa_description:models",
>     ],
>     # TODO This flaky test is disabled under kcov because it causes timeouts.
> ```

Would you be OK  with using the GSG-style TODO here, and include your name?
http://drake.mit.edu/styleguide/cppguide.html#TODO_Comments

---

*[tools/dynamic_analysis/bazel.rc, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7823#-L3U6tCK-99ILYGNOn_S:-L3UEEkVR7Ek-TOXJEB9:bcbo2ix) ([raw file](https://github.com/robotlocomotion/drake/blob/0d2fcce244d055e41297e24b8f613b7571157d09/tools/dynamic_analysis/bazel.rc#L12)):*
<details><summary><i>Previously, KyleFromKitware wrote…</i></summary><blockquote>

@betsymcphail came up with these numbers through experimentation. That said, running a program under kcov slows down a program significantly due to the fact that the OS has to context-switch between the program and the kcov process every time a line is hit. So, we would expect that we would have to increase the timeouts.
</blockquote></details>

Ah, that makes sense! Could this be added to the source as a comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7823)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7823#-:-L3UFAkvI5x9DXiZGEzh:b-2l0s3s)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7823)*

**Comment by KyleFromKitware** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/kuka_iiwa_arm/BUILD.bazel, line 128 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7823#-L3UE2njG7MvNEllluJG:-L3UqDgEJwsQS90_mfb4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1edf1db3a415192923c802d3df4af7c380ab3324/examples/kuka_iiwa_arm/BUILD.bazel#L128)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Would you be OK  with using the GSG-style TODO here, and include your name?
http://drake.mit.edu/styleguide/cppguide.html#TODO_Comments
</blockquote></details>

Done.

---

*[tools/dynamic_analysis/bazel.rc, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7823#-L3U6tCK-99ILYGNOn_S:-L3UqEeCinSfol2plUli:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0d2fcce244d055e41297e24b8f613b7571157d09/tools/dynamic_analysis/bazel.rc#L12)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Ah, that makes sense! Could this be added to the source as a comment?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7823)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7823)*

**Pull request merged**
