### PR TITLE
Add missing tools relating to LLVM 9

### PR DESCRIPTION
**Pull request by jamiesnape**
Needed for sanitizer builds (e.g., for `llvm-symbolizer`). Needs CI update, but no reason it cannot merge beforehand.

Relates #13434 and  #13650.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13656)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Comment by jwnimmer-tri** [comment]
:lgtm: both +(status: single reviewer ok)

**Comment by jwnimmer-tri** [comment]
(Bionic still needs some love.)

**Comment by jamiesnape** [comment]
I feel like this is not the first time we have seen an lldb apt issue.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
Punting on `lldb-9` for now. CI does not actually need it.

**Comment by jwnimmer-tri** [comment]
LGTM.

**Pull request merged**
