### PR TITLE
fixed a bug in DARE solver

### PR DESCRIPTION
**Pull request by weiqiao**
The repo for the previous pull request was deleted. So I'm opening a new pull request.

(Edit: Related to #8034.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11118)

### CODE REVIEW

**Comment by weiqiao** [comment]
Replace https://github.com/RobotLocomotion/drake/pull/8469 
Please review
@hongkai-dai @sadraddini

**Comment by jwnimmer-tri** [comment]
Happy New Year, and thanks for your interest in contributing to Drake!  Since this PR has not received any updates over the past 6+ months, we are closing it automatically.  To resume the PR again, you may reopen it with updates, or open a new one.

**Comment by RussTedrake** [comment]
@hongkai-dai this is still and important fix, but it died in your code review.  Could you try to help us land it?

**Review by hongkai-dai — COMMENTED** [review]
I reopened the PR #14865, since this branch has been removed by Weiqiao on his repo.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11118#-:-MXYjMy8D8xMJHkuLwtS:bpzyqmt)* status: 4 unresolved discussions, LGTM missing from assignees soonho-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request closed without merging**
