### PR TITLE
Revert "Use NumTraits::Literal rather than ::Real"

### PR DESCRIPTION
**Pull request by david-german-tri**
Reverts RobotLocomotion/drake#4431

This may have broken OS X nightly debug builds.  Reverting to test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4438)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-minimal please

**Comment by david-german-tri** [comment]
I can reproduce the failure from CI locally on my Mac.  Investigating now.

**Comment by david-german-tri** [comment]
Sayeth valgrind: `Conditional jump depends on uninitialized value`

**Comment by david-german-tri** [comment]
-> #4440

**Pull request closed without merging**
