### PR TITLE
Copy Parallelism code from TRI and adapt for Drake

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@calderpg-tri for feature review, please.

This isn't quite 100% polished yet, but it's close and probably good enough to begin review.

Note that the commits are curated, so the File Matrix ranges might help with review.

> Reviewed 3 of 3 files at r1, 8 of 10 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-:-Nd3VppoDTEQYibtodE5:b-n2h0k7)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/parallelism.h` line 40 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd3UUYVAjFRjkDd3x13:-Nd3UUYW9vqvuiIy7mgl:b-t075q8) ([raw file](https://github.com/RobotLocomotion/drake/blob/cdf3fd32b61b71c277eb92f0c79a99c96966bcdd/common/parallelism.h#L40)):*
> ```objc
> less than `hardware_concurrency()`, the `num_threads` will be that value.
> 
> 3. If the environment variable `DRAKE_NUM_THREADS` is not set but the
> ```

BTW This is the new logic, compared to Anzu.

If the user has not attempted to set DRAKE_NUM_THREADS, but has otherwise specified the (somewhat common) OMP_NUM_THREADS (e.g., for pytorch or multiprocessing), I think it's helpful to obey it.  That seems like smoother onboarding for new users who might already have set that up in their robotics environment for other reasons.

It did not seem proper to me to have many dozens of calls to OpenMP par-for inside Drake, yet not obey OMP_NUM_THREADS at all.  (Our typical use of the spelling `omp parallel for num_threads(parallelism.num_threads()` trumps the omp library's internal governance of OMP_NUM_THREADS.)

If the user specifies DRAKE_NUM_THREADS (even as the empty string), we will ignore OMP_NUM_THREADS.

**Review by calderpg-tri — COMMENTED** [review]
Looks good so far. Are you planning to incorporate either of the macros on this PR, or do you intend those to be in a follow up?

> Reviewed 10 of 10 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-:-Nd6eqlI5lK1CCluNa7z:b-rlxcq2)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`perception/point_cloud.h` line 345 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd6dGhP2mIw2CLWp7tN:-Nd6dGhQ2aXZA-QLNsUp:bwy1z27) ([raw file](https://github.com/RobotLocomotion/drake/blob/cdf3fd32b61b71c277eb92f0c79a99c96966bcdd/perception/point_cloud.h#L345)):*
> ```objc
>   /// @throws std::exception if voxel_size <= 0.
>   PointCloud VoxelizedDownSample(
>       double voxel_size, Parallelism parallelize = false) const;
> ```

btw I prefer being more explicit with `Parallelism::None()` instead of`false`, but it's not a big loss here

**Comment by jwnimmer-tri** [comment]
> Are you planning to incorporate either of the macros on this PR, or do you intend those to be in a follow up?

I was thinking in a follow-up, just so I can at least get this class in ASAP.  There's pending PRs that already need it (#20057).  There's also more porting to be done to use this instead of bools/custom args across Drake, which I'm also planning as a follow-up.

**Review by calderpg-tri — COMMENTED** [review]
:thumbsup:  :lgtm: feature

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-:-Nd6fsC11S7Nm7UtSGPP:b-3ztlxt)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> Reviewed 2 of 10 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-:-Nd6j8urBTbjKgjXY9MV:bybe5xg)* status: LGTM missing from assignee sherm1(platform)

___
*[`perception/point_cloud.h` line 345 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd6dGhP2mIw2CLWp7tN:-Nd6irAV4b-ZMM5TyRjG:bsdfdii) ([raw file](https://github.com/RobotLocomotion/drake/blob/cdf3fd32b61b71c277eb92f0c79a99c96966bcdd/perception/point_cloud.h#L345)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

btw I prefer being more explicit with `Parallelism::None()` instead of`false`, but it's not a big loss here
</blockquote></details>

Given the kwarg name `parallelize`, it seemed to me that keeping the boolean was a tiny bit better.  Variables named `parallelism` would accept `None` a bit more naturally.

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few comments

> Reviewed 7 of 10 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-:-Nd7MMxr4ZNXlr6K4A0e:b-tv2fmf)* status: 8 unresolved discussions

___
*[`common/parallelism.h` line 16 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7ECWv5ATMxrpI043-:-Nd7ECWv5ATMxrpI0430:b-hahem9) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L16)):*
> ```objc
> user-specified value (any number >= 1), or the maximum number. For convenience,
> conversion from `bool` is provided so that `false` is no parallelism and `true`
> is maximum parallelism.
> ```

BTW that implicit conversion is surprising -- is it really worth having? Wouldn't Parallelism::None() or Parallelism::Max() be clearer than false or true at the call site?
___
*[`common/parallelism.h` line 53 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7FmSY2diXcXM70ftY:-Nd7FmSY2diXcXM70ftZ:b-csed0) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L53)):*
> ```objc
> 
> In Drake's unit tests, `DRAKE_NUM_THREADS` is set to "1" by default. If your
> unit requires actual parallelism, use the `num_threads = N` attribute in the
> ```

typo: unit -> unit test
___
*[`common/parallelism.h` line 61 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7DCKR57_fmb7oNG59:-Nd7DCKR57_fmb7oNG5A:b60tijp) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L61)):*
> ```objc
>   /** Constructs a %Parallelism with no parallelism (i.e., num_threads=1).
>   Python note: This function is not bound in pydrake (due to its name); instead,
>   pass either `1` or `False` to the constructor. */
> ```

BTW why not suggest calling the default constructor? Seems simpler.
___
*[`common/parallelism.h` line 62 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7CQnHDjYpWfmicW_s:-Nd7CQnHDjYpWfmicW_t:b4jvmfa) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L62)):*
> ```objc
>   Python note: This function is not bound in pydrake (due to its name); instead,
>   pass either `1` or `False` to the constructor. */
>   static Parallelism None() { return Parallelism(); }
> ```

BTW if having the C++ and Python APIs match is a goal, we could rename this to something like "Nope" or "Zilch()" or "SingleThread()"
___
*[`common/parallelism.h` line 73 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7BpuHAhZlPs9MLfkS:-Nd7BpuHAhZlPs9MLfkT:bt8xf8u) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L73)):*
> ```objc
>   /** Constructs a %Parallelism with either no parallelism (i.e., num_threads=1)
>   or the maximum number of threads (Max()), as selected by `parallelize`. */
>   Parallelism(bool parallelize) {  // NOLINT(runtime/explicit)
> ```

minor: please note in the member comment that this is an implicit conversion.
___
*[`common/parallelism.cc` line 63 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7Hyxg4Xo8ndBl1IvY:-Nd7Hyxh3cEfS7SEnNlc:b-ib8rvu) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.cc#L63)):*
> ```cpp
>     const std::optional<int> parsed = ParsePositiveInt(omp_num_threads);
>     if (!parsed || parsed > hardware_concurrency) {
>       drake::log()->debug(
> ```

BTW should this be a `warn()`? I'm thinking user might be expecting use of OMP variable if they set it.
___
*[`common/test/parallelism_test.cc` line 89 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7JdBn2vEOP5Bl6M9I:-Nd7JdBoCTvNqys_iNSM:brkxrvp) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/test/parallelism_test.cc#L89)):*
> ```cpp
>       {"-1", fallback},
>       {"0", fallback},
>       {"999999999", fallback},
> ```

BTW consider something like `{"4,3,2", fallback}` to show that this form of OMP setting is ignored.
___
*[`common/test/parallelism_test.cc` line 100 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7KZ261518lG7GLY3U:-Nd7KZ261518lG7GLY3V:brnkwcj) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/test/parallelism_test.cc#L100)):*
> ```cpp
>   EXPECT_EQ(ConfigureMaxNumThreads("", "1"), fallback);
>   EXPECT_EQ(ConfigureMaxNumThreads("-1", "1"), fallback);
> }
> ```

BTW consider adding test to make sure we actually get the DRAKE value when it _is_ parseable and the OMP value is also present.



_Suggestion:_
```cpp
  EXPECT_EQ(ConfigureMaxNumThreads("5", "3"), 5);
```

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093)* status: 8 unresolved discussions

___
*[`common/parallelism.h` line 16 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7ECWv5ATMxrpI043-:-Nd7Muw9BNOTvBthiXJv:b47yatt) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW that implicit conversion is surprising -- is it really worth having? Wouldn't Parallelism::None() or Parallelism::Max() be clearer than false or true at the call site?
</blockquote></details>

Implicit conversion from bool does make many call sites simple, and we think having users be able to do `result = Operation(params, parallelize=True)` is a useful convenience. It also maintains compatibility with existing `bool parallelize` arguments.

For some broader context/examples of use, see anzu#10833.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093)* status: 1 unresolved discussion

___
*[`common/parallelism.h` line 16 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7ECWv5ATMxrpI043-:-Nd7VPeNAgHjUaHp6K4Q:bnf0fb9) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L16)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Implicit conversion from bool does make many call sites simple, and we think having users be able to do `result = Operation(params, parallelize=True)` is a useful convenience. It also maintains compatibility with existing `bool parallelize` arguments.

For some broader context/examples of use, see anzu#10833.
</blockquote></details>

Yup.

Some call sites might not be readable with just a bare `true` or `false`, but other call sites are extremely awkward without the implicit conversion.  My hope is that we can allow the conversion to make the latter cases better, and that people will just need to use good judgment as to whether a literal `true` or `false` is good enough.  They still have the option to spell it out if they like.
___
*[`common/parallelism.h` line 62 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7CQnHDjYpWfmicW_s:-Nd7UjjEECBsCNt_7wbP:bncaecr) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L62)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW if having the C++ and Python APIs match is a goal, we could rename this to something like "Nope" or "Zilch()" or "SingleThread()"
</blockquote></details>

I took a tiny poll in slack, and this way was the winner.  My expectation is that Python users will mostly eschew the factory names anyway.
___
*[`common/parallelism.h` line 73 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7BpuHAhZlPs9MLfkS:-Nd7V1n_0XqT7c1rGTmw:bus6tpn) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L73)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: please note in the member comment that this is an implicit conversion.
</blockquote></details>

I think by "member comment" you mean the constructor docstring?
___
*[`common/parallelism.cc` line 63 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7Hyxg4Xo8ndBl1IvY:-Nd7W4_1EtKqGmXdqmrG:b2si3tl) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.cc#L63)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should this be a `warn()`? I'm thinking user might be expecting use of OMP variable if they set it.
</blockquote></details>

It's borderline.  What decided it for me was that we don't want to spam them about a variable that isn't "ours".  If they are having trouble, we can talk them through "turn on debug logs".

In most cases, it _will_ work fine.  Only the nested parallelism comma-separated list would be a problem, and I think almost nobody uses that feature.

End of the day, the answer is still the same: If they really care about drake thread count, set the drake-specific env var directly.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20093)* status: :shipit: complete! all discussions resolved, LGTM from assignees calderpg-tri,sherm1(platform), base commit is latest master

___
*[`common/parallelism.h` line 73 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20093#-Nd7BpuHAhZlPs9MLfkS:-Nd7bVbBCQcO4Z8WzpLM:bxywk8w) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a166281db5abba35dffd844e6db4f24ceb7466/common/parallelism.h#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think by "member comment" you mean the constructor docstring?
</blockquote></details>

Yes, that's what I meant. Looks good.

**Pull request merged**
