### PR TITLE
expose parameters in QuadrotorPlant

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17402)

### CODE REVIEW

**Review by naveenoid — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17402#-:-N4hewndAO_kHuP2fifn:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17402#-:-N4hfKwD78wDazaXUVE0:bi4se7j)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
+(release notes: feature) 
:lgtm: platform

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17402#-:-N4hwhpB2wJRZaVL6Ax3:b2vream)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),naveenoid (waiting on @hongkai-dai)

___
*[`examples/quadrotor/quadrotor_plant.h` line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17402#-N4hwcg-0XKC06GM-zol:-N4hwcg-0XKC06GM-zom:b-g60un9) ([raw file](https://github.com/robotlocomotion/drake/blob/040a16b82f6ad20b0c4894d89c7af91837a990a2/examples/quadrotor/quadrotor_plant.h#L47)):*
> ```objc
>   double g() const { return g_; }
> 
>   [[nodiscard]] double length() const { return L_; }
> ```

BTW Why `[[nodiscard]]` here and not for other properties (`m()`, `g()`)?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17402)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),naveenoid (waiting on @EricCousineau-TRI and @naveenoid)

___
*[`examples/quadrotor/quadrotor_plant.h` line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17402#-N4hwcg-0XKC06GM-zol:-N4hxlk6A5lhhbK4n6uA:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/040a16b82f6ad20b0c4894d89c7af91837a990a2/examples/quadrotor/quadrotor_plant.h#L47)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Why `[[nodiscard]]` here and not for other properties (`m()`, `g()`)?
</blockquote></details>

Done. Good call.

**Pull request merged**
