### PR TITLE
CartesianProduct Getters for A and b Properties

### PR DESCRIPTION
**Pull request by cohnt**
`CartesianProduct` has optional members `A_` and `b_`, which are essential to the properties of the set, but can only be accessed indirectly (i.e., via checking if a point is in the set, or calculating its volume). Currently, we can't even determine if these values have been set, let alone what the values actually are. This PR adds methods to get the values.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21827)

### CODE REVIEW

**Comment by cohnt** [comment]
+@rhjiang for feature review

**Review by rhjiang — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21827#-:-O4lVy462KwxfXJqVlV3:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by cohnt** [comment]
+@ggould-tri for platform review, please

**Comment by cohnt** [comment]
-@ggould-tri
+@rpoyner-tri

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21827#-:-O5K9yaF4xFnRyJuESgY:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21827#-:-O5KA5O_7cqv7gtRMeNM:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),rhjiang

**Pull request merged**
