### PR TITLE
Turbo implicit integrator

### PR DESCRIPTION
**Pull request by edrumwri**
Simple modification to recompute Jacobian matrices only when necessary. Jacobian matrices are still refactored regularly.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6265)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-KlzTwelk6A6_A5Y7qo2:b1tu4a9)*

**Comment by sherm1** [comment]
The 140 commits here are disturbing, if ultimately harmless. Please clean these things up locally before review so that us reviewers don't have to face them to figure out if anything bad is happening!

Per f2f, a more robust solution is needed. Maybe kill this PR and resubmit without the commit cruft? 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 345 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-Km2keG5gWMWIrDrcSJA:-Km2keG6n_CG_KsWnx5W:bf0kjwn) ([raw file](https://github.com/robotlocomotion/drake/blob/71ae1c895b3d716297e791fdabfeefc30efa04f6/drake/systems/analysis/implicit_euler_integrator-inl.h#L345)):*
> ```objc
>   T last_dx_norm = std::numeric_limits<double>::infinity();
> 
>   // Compute the initial Jacobian matrix (or retrieve it from the cache).
> ```

BTW, probably better to avoid overloading "cache" here since we use it to refer to the cache in the Context. How about "saved Jacobian"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Km2j8sCsMD_TFPPmXY3:b9gy91h)*

**Comment by edrumwri** [comment]
Success! But the Robertson test is still slow as a dog (I suspect CI is going to have major trouble with it). The obvious solutions are (a) remove the test (but this test is definitely doing its job as a pathological case!) or (b) give the integrator an optional "always reform Jacobian and always factor mode" (which I'm not crazy about, because such an option is really only useful for such tiny test problems). 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 345 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-Km2keG5gWMWIrDrcSJA:-KmNd6PX2MApz40K8wx1:b-rx2q2x) ([raw file](https://github.com/robotlocomotion/drake/blob/71ae1c895b3d716297e791fdabfeefc30efa04f6/drake/systems/analysis/implicit_euler_integrator-inl.h#L345)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, probably better to avoid overloading "cache" here since we use it to refer to the cache in the Context. How about "saved Jacobian"?
</blockquote></details>

BTW Point is now moot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-KmNhwea6iwzxHm6tig1:brgb7la)*

**Comment by sherm1** [comment]
Review pass made. I could use an f2f explanation. I'm concerned this doesn't achieve a lot of reuse and does extra work because it doesn't separate the two differently-scaled iteration matrices or the step size at which they were computed. It doesn't reuse the start-of-step Jacobian when a step fails -- why not save that along with the start-of-step derivatives? In general I couldn't get a good grasp on how the existence of the 1st and 2nd-order pair interacts with re-use.

---

Reviewed 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 318 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSGqpFxheKLxpyZY7b:-KmSGqpFxheKLxpyZY7c:bdsj5a7) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L318)):*
> ```objc
> //        return (assuming that h > 0)
> // @param trial the attempt for this approach (1-4). StepAbstract() uses more
> //        computationally methods as the trial numbers increase.
> ```

BTW word missing here?

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 328 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSMBmP6b0vrJAA4_Wv:-KmSMBmP6b0vrJAA4_Ww:brqhc1a) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L328)):*
> ```objc
> //       unsuccessful exit (indicated by this function returning `false`).
> template <class T>
> bool ImplicitEulerIntegrator<T>::StepAbstract(const T& dt,
> ```

BTW this method has gotten very long -- closing in on 200 lines. Are there some logical chunks that could be split out? I would nominate the block of code that chooses the level of desperation for Jacobian and iteration matrix recomputation.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 334 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSKZP9IE9mnYt19g4h:-KmSKZPAJmkykch2dYuq:b-s595dw) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L334)):*
> ```objc
>   using std::min;
> 
>   // Verify the trial number is correct.
> ```

BTW correct --> legal or in-range or whatever.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 374 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSJAIc2Oq-McRW4MnW:-KmSJAIc2Oq-McRW4MnX:bldq7po) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L374)):*
> ```objc
>   }
> 
>   // For the first trial, we do nothing special.
> ```

BTW consider switch(trial) here. Would be easier to follow, I think.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 380 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSJRPLVdu0_hkjTSRY:-KmSJRPM8rpS7cu_tXyu:b-olew9x) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L380)):*
> ```objc
>       const int n = xtplus->size();
>       neg_iteration_matrix_ = J_ * (dt / scale) - MatrixX<T>::Identity(n, n);
>       Factor(neg_iteration_matrix_);
> ```

BTW seems unnecessary in the common case of steady step size. Why not check what factor was used for the saved iteration matrix?

Also doesn't this get trashed every step since you need two different iteration matrices for the 1st and 2nd-order calculations?

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 388 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSKI9ryx4DsCoJwVk0:-KmSKI9ryx4DsCoJwVk1:bt6et0u) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L388)):*
> ```objc
>         // done.
>         if (last_call_failed_) {
>           return false;
> ```

BTW I'm confused here. This flag gets set in trial #4 so why would it need to be checked in trial #3?

---

*[drake/systems/analysis/implicit_euler_integrator.h, line 318 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSHtjmw9Dqn9rd8OD0:-KmSHtjmw9Dqn9rd8OD1:bwegjm9) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator.h#L318)):*
> ```objc
>   // However, we assume any time-dependent dynamics have minimal effects and
>   // cache using the state only.
>   VectorX<T> last_jacobian_x_;
> ```

BTW is this comment out of date now?

---

*[drake/systems/analysis/implicit_euler_integrator.h, line 325 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSHz-lsTJz4IpwuU0V:-KmSHz-lsTJz4IpwuU0W:bpwwew0) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator.h#L325)):*
> ```objc
>   // this data in the class definition serves to minimize heap allocations
>   // and deallocations.
>   MatrixX<T> neg_iteration_matrix_;
> ```

BTW I'm surprised (a) that there aren't two of these, for the two different iteration matrices at h and h/2, and (b) that h is not saved. Otherwise I don't see how the iteration matrix can be re-used even for steady step sizes. 

---

*[drake/systems/analysis/test/implicit_euler_integrator_test.cc, line 40 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSHGm62WQ-sBZ2nmoc:-KmSHGm62WQ-sBZ2nmod:bgs3p87) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/test/implicit_euler_integrator_test.cc#L40)):*
> ```cpp
> 
>   // Robertson will run a LONG time if we reuse Jacobian matrices.
>   integrator.set_reuse(false);
> ```

BTW why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-KmSMdfBUUJQjIlDfHnk:b-iurxzz)*

**Comment by edrumwri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 318 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSGqpFxheKLxpyZY7b:-KmSw0vaOGPMEKCjDtvk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L318)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW word missing here?
</blockquote></details>

Done.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 334 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSKZP9IE9mnYt19g4h:-KmSw6z3uLkMUlMs4-Yn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L334)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW correct --> legal or in-range or whatever.
</blockquote></details>

Done.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 374 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSJAIc2Oq-McRW4MnW:-KmTZR4xb4bwJOShL4zf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L374)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider switch(trial) here. Would be easier to follow, I think.
</blockquote></details>

Done.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 380 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSJRPLVdu0_hkjTSRY:-KmTZSsC_cAdIUhXBxR0:b5civjr) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L380)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW seems unnecessary in the common case of steady step size. Why not check what factor was used for the saved iteration matrix?

Also doesn't this get trashed every step since you need two different iteration matrices for the 1st and 2nd-order calculations?
</blockquote></details>

BTW Resolved via f2f discussion?

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 388 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSKI9ryx4DsCoJwVk0:-KmTZVz9HxoOkxduWYEP:b5civjr) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L388)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm confused here. This flag gets set in trial #4 so why would it need to be checked in trial #3?
</blockquote></details>

BTW Resolved via f2f discussion?

---

*[drake/systems/analysis/implicit_euler_integrator.h, line 318 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSHtjmw9Dqn9rd8OD0:-KmSwMSLeXFirY4M8TAv:btglcov) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator.h#L318)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this comment out of date now?
</blockquote></details>

BTW Yes- I thought I had removed it.

---

*[drake/systems/analysis/implicit_euler_integrator.h, line 325 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSHz-lsTJz4IpwuU0V:-KmTZa1MR5oaWFNYIpj6:b5civjr) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator.h#L325)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm surprised (a) that there aren't two of these, for the two different iteration matrices at h and h/2, and (b) that h is not saved. Otherwise I don't see how the iteration matrix can be re-used even for steady step sizes. 
</blockquote></details>

BTW Resolved via f2f discussion?

---

*[drake/systems/analysis/test/implicit_euler_integrator_test.cc, line 40 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSHGm62WQ-sBZ2nmoc:-KmSwPYHial1cy2zonto:bmdkg67) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/test/implicit_euler_integrator_test.cc#L40)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why?
</blockquote></details>

BTW PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265)*

**Comment by edrumwri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 328 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmSMBmP6b0vrJAA4_Wv:-KmXDifOzXySAUH0zzB5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70561f1d3895da0a732acc48d9749ec058c2ab/drake/systems/analysis/implicit_euler_integrator-inl.h#L328)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this method has gotten very long -- closing in on 200 lines. Are there some logical chunks that could be split out? I would nominate the block of code that chooses the level of desperation for Jacobian and iteration matrix recomputation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265)*

**Comment by sherm1** [comment]
:lgtm: (still needs another reviewer)

---

Reviewed 4 of 4 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 309 at r11](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmZ2bDlT5bDgVR3OKis:-KmZ2bDm7Klsl6lyPIs6:b-olmfmc) ([raw file](https://github.com/robotlocomotion/drake/blob/e77dd83a3660040e86070fe273d1c92c3e32206f/drake/systems/analysis/implicit_euler_integrator-inl.h#L309)):*
> ```objc
> // Computes any necessary matrices for the Newton-Raphson iteration in
> // StepAbstract().
> // @returns `false` if the calling StepAbstract method should indicate failure;
> ```

BTW also needs some short documentation to define the parameters, whose meaning is definitely not clear (to me anyway).

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 368 at r11](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmZ36Z3jA07A7ISscs6:-KmZ36Z4it9HsRRDcufz:bp6l8oj) ([raw file](https://github.com/robotlocomotion/drake/blob/e77dd83a3660040e86070fe273d1c92c3e32206f/drake/systems/analysis/implicit_euler_integrator-inl.h#L368)):*
> ```objc
>     }
>   }
> }
> ```

BTW this code looks great reorganized like this -- thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-KmZ3PgCOiYVruB7Wksu:b-mbn9l9)*

**Comment by edrumwri** [comment]
+@ggould-tri for platform review please (per regular rotation)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-KmcbGWk6h8hmGyO_e84:b-760zoq)*

**Comment by ggould-tri** [comment]
All of the code looks good as it stands, but the lack of test coverage of the new flippable reuse bit is unfortunate.  I would suggest wrapping the existing tests such that each runs with and without reuse to ensure that reuse does not change the solution.

---

Reviewed 4 of 4 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kml9di3g4Ja1kRcME2T:b-oxerxu)*

**Comment by jwnimmer-tri** [comment]
FYI googletest has great tools for running parameterized tests (the same test code, run with different parameters and/or typenames).

**Comment by edrumwri** [comment]
Done- thanks for the tip @jwnimmer-tri (it was really helpful!).

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 309 at r11](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-KmZ2bDlT5bDgVR3OKis:-KmvxZ-Sjbgp7ScNHtX1:b-eq8lr9) ([raw file](https://github.com/robotlocomotion/drake/blob/e77dd83a3660040e86070fe273d1c92c3e32206f/drake/systems/analysis/implicit_euler_integrator-inl.h#L309)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW also needs some short documentation to define the parameters, whose meaning is definitely not clear (to me anyway).
</blockquote></details>

PTAL- I pointed to the StepAbstract() documentation to keep from having to keep them consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kmvx7jwhmKsJ1NkgqHm:b5bs2jq)*

**Comment by sherm1** [comment]
Nice! @ggould-tri are you happy with this now?

---

Reviewed 2 of 2 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-KmyUI3s4Gry56rEJHoA:b-qcztel)*

**Comment by ggould-tri** [comment]
That is awesomely clear and straightforward; :lgtm_strong:.  Not sure why it doesn't lgtJenkins, though. 

---

Reviewed 2 of 2 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kn-lFocWumRd46KO8bF:b-4ors1z)*

**Comment by sherm1** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
Issue persisted across retest, looks real.  The complaint seems to be that a witness function didn't change sign across the point the isolation logic said it did (the assert in question is marked with a perhaps over-hopeful "This check is expensive. Remove it once we are confident.").

This leads me to suspect that there is a correctness issue with the new integrator logic; @sherm1, as feature reviewer, can you take a second look at the correctness here?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kn0Lat4i26VBYVyTB1V:bg9umsx)*

**Comment by sherm1** [comment]
Will do, @ggould-tri -- thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kn0NqYxPhCMf3f2BSMe:b-o5048s)*

**Comment by sherm1** [comment]
I have confirmed that the change to the implicit integrator here breaks simulator_test.cc. Not sure why yet ...

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kn0_fO9A1IRSvpiqsiA:bcsr4q)*

**Comment by sherm1** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kn0ad_aLaep-UDSSgKz:b8b79qu)*

**Comment by sherm1** [comment]
Succeeds with set_reuse(false), fails with set_reuse(true). However, I'm not convinced that is the root cause. The problem is that a witness that triggered by crossing zero to -1e-8 when re-integrated to the same time came out +1e-8 (approx) and hence triggered the bug catcher. That seems too touchy to be reliable.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kn1JTVIeU8_aSi_XGv-:b-lx5e4)*

**Comment by ggould-tri** [comment]
Ouch!  So does this mean that `set_reuse(true)` introduces a new correctness issue in integration with witness functions, or that it exposes an existing issue?  I don't know what level of behaviour change we would expect from reuse; I would say "minimal" but clearly 2e-8 is not minimal enough in this case :-/

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kn5H0FtnkddEJboYlbt:b-h1qgjt)*

**Comment by sherm1** [comment]
Right, there is a bug in the witness function code exposed by the slightly-nondeterministic behavior of an integrator that is required to converge only to a tolerance. The witness function bugcatcher is depending on every calculation being done to machine precision, which is not right. I'll file an issue and see if I can untangle the integrator in this PR from the witness function bug.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kn5OxFW1Pd9KaH1vE0w:bzfmhyj)*

**Comment by ggould-tri** [comment]
Cool.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-Kn5VlJA88fWKMUxJBbQ:b-89q77k)*

**Comment by ggould-tri** [comment]
Looked at #6396 and I agree with description there.  This workaround is adequate until that lands, since anyone else who hits that issue will be doing so because they opted in to the risk. :lgtm:

---

Reviewed 2 of 2 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-KnAUZhcoryFQBs1SWM-:b-kisytp)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265)*

**Comment by sherm1** [comment]
Thanks, @ggould-tri. :lgtm: pending CI.

---

Reviewed 2 of 2 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265#-:-KnAnCdjabm3ri6BGS43:b5i1grb)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6265)*

**Pull request merged**
