### PR TITLE
[SAP] Implements limit constraint

### PR DESCRIPTION
**Pull request by amcastro-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051#-:-N0gXb0J8kYGUUYWXK14:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Comment by amcastro-tri** [comment]
pumping priority to "high" given now this is a pre-requisite for my next PR (the goal is to enable SAP for the next release).

**Review by joemasterjohn — COMMENTED** [review]
Checkpoint, just looking at the test now.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051#-:-N191y2F9S1Bq0AXsdTM:bkx5cm2)* status: 8 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @joemasterjohn)

___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N18x26mA1KJ0UeKUvbl:-N18x26mA1KJ0UeKUvbm:b98hwfv) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L52)):*
> ```objc
>   stiffness (in N/m), d is the dissipation (in N⋅s/m) and (x)₊ = max(0, x),
>   componentwise. Dissipation is parameterized as d = tau_d⋅k, where tau_d is the
>   "dissipation time scale". Notice that this impulses are positive when the
> ```

nit grammar



_Suggestion:_
```objc
this impulse is
```
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 54 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N18xIKW5ZidpzpuSRM2:-N18xIKW5ZidpzpuSRM3:b-yka7x6) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L54)):*
> ```objc
>   "dissipation time scale". Notice that this impulses are positive when the
>   constraint is active and zero otherwise.
>   For this constraint the components of γ = [γₗ, γᵤ]ᵀ are constrined to live in
> ```

nit spelling



_Suggestion:_
```objc
constrained
```
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 80 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N1905xL76RQSWQtdNIr:-N1905xM0gSrAmGQn884:b-nq72eo) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L80)):*
> ```objc
>     // Constructs a valid set of parameters.
>     // @pre lower_limit < +∞
>     // @pre upper_limit > -∞
> ```

Isn't the condition: `lower_limit < +∞ || upper_limit > -∞`?



_Code quote:_
```objc
    // @pre lower_limit < +∞
    // @pre upper_limit > -∞
```
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N18y-ni0hVPMt_QPYMH:-N18y-ni0hVPMt_QPYMI:b-i0lmyv) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L97)):*
> ```objc
>       DRAKE_DEMAND(lower_limit <= upper_limit);
>       DRAKE_DEMAND(stiffness > 0);
>       DRAKE_DEMAND(dissipation_time_scale > 0);
> ```

nit: code doesn't match the documentation



_Suggestion:_
```objc
DRAKE_DEMAND(dissipation_time_scale >= 0);
```
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 98 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N18yDcNCcJgTlBYZ5F2:-N18yDcNCcJgTlBYZ5F3:b-hxp4sk) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L98)):*
> ```objc
>       DRAKE_DEMAND(stiffness > 0);
>       DRAKE_DEMAND(dissipation_time_scale > 0);
>     }
> ```

nit: missing `DRAKE_DEMAND(beta > 0`?
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 156 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N18zWBG5TuVzvlAKWUg:-N18zWBG5TuVzvlAKWUh:bmpq2x9) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L156)):*
> ```objc
> 
>  private:
>   // Computes the constraint function g(q0) as a function of q0 for given lower
> ```

nit: you're switching between `//` and `/* */` for your doc comments here and elsewhere, I'd stick to one for consistency.
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 163 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N190MEP4jW6RLqGCS2P:-N190MEP4jW6RLqGCS2Q:b-anuyry) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L163)):*
> ```objc
>                                            const T& qu) {
>     constexpr double kInf = std::numeric_limits<double>::infinity();
>     DRAKE_DEMAND(ql < kInf);
> ```

Again, here you're requiring that both the limits be finite, but the code and comments imply that one may be infinite.
I think the condition should be: `ql < kInf || qu > -kInf`



_Code quote:_
```objc
    DRAKE_DEMAND(ql < kInf);
    DRAKE_DEMAND(qu > -kInf);
```
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.cc` line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N191ZtH7UFHEUV5V9L9:-N191ZtH7UFHEUV5V9LA:b-5lt4zs) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.cc#L58)):*
> ```cpp
>                                     EigenPtr<VectorX<T>> gamma,
>                                     MatrixX<T>* dPdy) const {
>   DRAKE_DEMAND(gamma->size() == this->num_constraint_equations());
> ```

nit: maybe you want a `DRAKE_DEMAND(gamma != nullptr)` here.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with some nits left over. +@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051#-:-N1981CZ4Fmy9orUpw7p:b-87g60w)* status: 8 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @amcastro-tri, @joemasterjohn, and @rpoyner-tri)

___
*[`multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc` line 123 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N197J6j-TDytyPx7Tg4:-N197J6j-TDytyPx7Tg5:b-snf6nh) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc#L123)):*
> ```cpp
> // Unit tests SapLimitConstraintTest::CalcRegularizationSoft() in the "soft"
> // regime, as defined in [Castro et al., 2021].
> TEST_P(SapLimitConstraintTest, CalcRegularizationSoft) {
> ```

nit: Since this test case doesn't rely on the the varying test parameters (lower_limit/upper_limit) or the fixture at all (constructs its own `Parameters` object, it would be nice to turn this into just a `GTEST_TEST` so it isn't repeated 3 times. Ditto for `CalcRegularizationNearRigid`



_Code quote:_
```cpp
TEST_P(SapLimitConstraintTest, CalcRegularizationSoft) {
```

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)* status: 8 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @amcastro-tri and @rpoyner-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)* status: 2 unresolved discussions (waiting on @amcastro-tri, @joemasterjohn, and @rpoyner-tri)

___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N19ddND2MEALdWhfmot:-N19hDcFB4OSKhAc95Gu:bs31cl4) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L15)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

btw this is another delightful piece of doc that will mostly go unread because it lives in internal::. Maybe not now, but consider later lifting this to a freestanding piece of doc somewhere, and possibly have the future version of this file refer to the full doc.
</blockquote></details>

Good idea. I will write a follow up paper of SAP where constraints and the particular implementation in Drake is properly documented, discussed and characterized. I could add a reference in the C++ modules for SAP when it's ready.
I created #17088 to track progress in this regard.
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 98 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N19cU748GEdhKnLkSRu:-N19ijonEtdK2ksZTL3w:bltcls8) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L98)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit consider moving the Parameters constructor to the cc file.  https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions
</blockquote></details>

The instantiation becomes annoying if I do so. Can I still use `DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS` for this nested class?
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 174 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N19cf9o5opxl8v9NyCU:-N19iz-t2-17DbupDdOV:b9nd2d9) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L174)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit consider moving this private method to the cc file. https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions
</blockquote></details>

ditto, same question. here and below.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)* status: 2 unresolved discussions (waiting on @amcastro-tri, @joemasterjohn, and @rpoyner-tri)

___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 163 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N190MEP4jW6RLqGCS2P:-N19nVraEKrMThHzMASp:bdgici0) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L163)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Misread the signs, retracting. 
</blockquote></details>

BTW Drive by: shouldn't the condition include qu >= ql?

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)* status: 2 unresolved discussions (waiting on @amcastro-tri and @rpoyner-tri)

___
*[`multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc` line 123 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N197J6j-TDytyPx7Tg4:-N1AQhvlBS5j57TZ3C97:b-54avio) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc#L123)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

The size of the constraint depends on the supplied upper/lower limits. I added comment here and below.
</blockquote></details>

Ok, thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)* status: 2 unresolved discussions (waiting on @amcastro-tri and @rpoyner-tri)

___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 98 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N19cU748GEdhKnLkSRu:-N1AV6XB2nML6PNVxndB:blchkbg) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L98)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

The instantiation becomes annoying if I do so. Can I still use `DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS` for this nested class?
</blockquote></details>

I think it should work, but I don't know that I have an example or other evidence to point to. I'll let you choose.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)* status: 2 unresolved discussions (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 98 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N19cU748GEdhKnLkSRu:-N1Ag3VS08mqdJL7OyRV:be4dq4c) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L98)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I think it should work, but I don't know that I have an example or other evidence to point to. I'll let you choose.
</blockquote></details>

My local experiments suggest that `Parameters` methods are getting expanded already by virtue of the enclosing class, so no more macro goo should be needed.
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 174 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N19cf9o5opxl8v9NyCU:-N1AgJRK51ToaiQfCWvF:b-w2bdpm) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L174)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto, same question. here and below.
</blockquote></details>

These are just methods on the templated class, so should be able to just move to cc without any extra template macro goo.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)* status: 2 unresolved discussions (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn (waiting on @joemasterjohn and @rpoyner-tri)

___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 98 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17051#-N19cU748GEdhKnLkSRu:-N1AlFeSBgHfuwmnvHpC:bylh31) ([raw file](https://github.com/robotlocomotion/drake/blob/70d242bf913096975f7abe8e566b7db8c4c81dd4/multibody/contact_solvers/sap/sap_limit_constraint.h#L98)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

My local experiments suggest that `Parameters` methods are getting expanded already by virtue of the enclosing class, so no more macro goo should be needed.
</blockquote></details>

excellent! pushed you diff

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17051)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn (waiting on @amcastro-tri)

**Pull request merged**
