### PR TITLE
Update TrajectorySource to optionally create derivatives of the trajectory.

### PR DESCRIPTION
**Pull request by Lucy-tri**
Add getters for start/end time to Trajectory class.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5386)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@siyuanfeng-tri for feature review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-:-KeG-92ftn3h4uAEiwtV:b-rnxo84)*

**Comment by siyuanfeng-tri** [comment]
thanks for doing this :)  :lgtm: minus minor comments. i'd like to get some input on whoever's platform reviewing this about whether TrajectorySource should take ownership of trajectory. 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/trajectories/trajectory.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGyfdNU54dZsgrEMTh:-KeGyfdNU54dZsgrEMTi:b-6dqc2i) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/common/trajectories/trajectory.h#L35)):*
> ```objc
>    * @return The number of rows in the matrix returned by value().
>    */
>   virtual Eigen::Index rows() const = 0;
> ```

BTW, just curious why are we doing Eigen::Index instead of int here? i found it easier if it were int, since everything else in drake returns int for size anyway. 

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGz3y-PHF0VB9yyduU:-KeGz3y-PHF0VB9yyduV:brdzfgj) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L43)):*
> ```cpp
>   EXPECT_EQ(kPpTrajFromVec.cols(), 1);
>   EXPECT_EQ(kPpTrajFromVec.get_start_time(), times[0]);
>   EXPECT_EQ(kPpTrajFromVec.get_end_time(), times[times.size() - 1]);
> ```

BTW, you could do times.back(). 

---

*[drake/systems/primitives/trajectory_source.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGzKbuQnTZNYie8TWn:-KeGzKbuQnTZNYie8TWo:brovtd4) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/trajectory_source.cc#L10)):*
> ```cpp
> template <typename T>
> TrajectorySource<T>::TrajectorySource(const Trajectory& trajectory,
>                                       int output_derivative_order,
> ```

can you add a check for derivative order >= 0?

---

*[drake/systems/primitives/trajectory_source.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGznTyQG-M1662_2Qk:-KeGznTzVjY_ZWlBPDnW:b-hov6yb) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/trajectory_source.h#L55)):*
> ```objc
> 
>  private:
>   const Trajectory& trajectory_;
> ```

BTW, I am slightly leaning towards just deep copy the trajectory here, to be consistent with the derivatives. 
or have a constructor that takes a unique_ptr. 

---

*[drake/systems/primitives/test/trajectory_source_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeH-cmgmzVHQzinjJv8:-KeH-cmgmzVHQzinjJv9:b-3347op) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/test/trajectory_source_test.cc#L34)):*
> ```cpp
>   }
> 
>   std::unique_ptr<PiecewisePolynomialTrajectory> kppTraj;
> ```

i think you need to _ this. 

---

*[drake/systems/primitives/test/trajectory_source_test.cc, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeH0Kxa5iOpvUYbfipW:-KeH0Kxa5iOpvUYbfipX:bmt8h22) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/test/trajectory_source_test.cc#L63)):*
> ```cpp
> 
>   for (size_t i = 1; i <= kDerivativeOrder; ++i) {
>     EXPECT_EQ(kppTraj->derivative(i)->value(kTestTime),
> ```

BTW, probably better switch to the compare matrix version. i don't think EXPECT_EQ works when len != 1. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-:-KeH0_Y97EfKNqGh5aHL:borwfpt)*

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/trajectories/trajectory.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGyfdNU54dZsgrEMTh:-KeKQNoPVX7gtZteZSy_:bxjoipw) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/common/trajectories/trajectory.h#L35)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, just curious why are we doing Eigen::Index instead of int here? i found it easier if it were int, since everything else in drake returns int for size anyway. 
</blockquote></details>

I don't know, but rows() has the same return type in PiecewisePolynomial and PiecewiseFunction, so I wanted to stay consistent with those.

---

*[drake/systems/primitives/trajectory_source.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGzKbuQnTZNYie8TWn:-KeKS2kUGT-Bt4S3yIPu:b-jaglbc) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/trajectory_source.cc#L10)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

can you add a check for derivative order >= 0?
</blockquote></details>

Already there: output_derivative_order >= 0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386)*

**Comment by Lucy-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGz3y-PHF0VB9yyduU:-KeKYIBUYxnEy3niMMip:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L43)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, you could do times.back(). 
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/trajectory_source_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeH-cmgmzVHQzinjJv8:-KeKYDDVOAgsDURnRRiL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/test/trajectory_source_test.cc#L34)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i think you need to _ this. 
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/trajectory_source_test.cc, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeH0Kxa5iOpvUYbfipW:-KeKYPbiQyv5LU2Amquc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/test/trajectory_source_test.cc#L63)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, probably better switch to the compare matrix version. i don't think EXPECT_EQ works when len != 1. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386)*

**Comment by Lucy-tri** [comment]
+@ggould-tri for platform review, and see open question from @siyuanfeng-tri, above . Thanks.

---

Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-:-KeKZCLKpeVr8GcBoEfJ:b-99m2ol)*

**Comment by Lucy-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/primitives/trajectory_source.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGznTyQG-M1662_2Qk:-KeKa0IEkWEwTLKPVW0N:b-xdxjdp) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/trajectory_source.h#L55)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, I am slightly leaning towards just deep copy the trajectory here, to be consistent with the derivatives. 
or have a constructor that takes a unique_ptr. 
</blockquote></details>

@ggould-tri can you advise? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386)*

**Comment by ggould-tri** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/trajectory_source.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGznTyQG-M1662_2Qk:-KeKarbfv2jj-p-k7jfD:b-smt4oa) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/trajectory_source.h#L55)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

@ggould-tri can you advise? 
</blockquote></details>

Holding it as a reference is definitely a weird thing.  (1) it forces the caller to retain it, which is annoying; (2) it confuses users as what looks like call-by-value is really call-by-reference, necessitating the doc comment at 33.

I would definitely favor doing a copy if it is cheap.  The argument for the current arrangement would be if copying is expensive and this ctor gets called very frequently; I expect neither is true.

As noted above if you wanted to save the caller the trouble of hanging on to the trajectory forever but also avoid the expense of the copy, you could take the argument via `unique_ptr`.  But since this is a System and so its constructor will probably only be called once per run, spending a few cycles on a copy to save developer confusion seems clearly right.

---

*[drake/systems/primitives/test/trajectory_source_test.cc, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeKdF4iZu1VTo-72WMG:-KeKdF4jS5eh0bqfi9ds:b4382kz) ([raw file](https://github.com/robotlocomotion/drake/blob/8fc99b1dbdb2e4cad5dd1396f64ae67450023a64/drake/systems/primitives/test/trajectory_source_test.cc#L70)):*
> ```cpp
>   }
> 
>   // Test first derivative (first segment) f`(y^4) = 4 * y^3.
> ```

FYI -- This would be clearer if you noted that `y` here means `kTestTime`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/trajectories/trajectory.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGyfdNU54dZsgrEMTh:-KeKlj2UyHl8XZHOKV2P:b-m5pwxv) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/common/trajectories/trajectory.h#L35)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

I don't know, but rows() has the same return type in PiecewisePolynomial and PiecewiseFunction, so I wanted to stay consistent with those.
</blockquote></details>

ok. fine not a big deal. 

---

*[drake/systems/primitives/trajectory_source.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGzKbuQnTZNYie8TWn:-KeKlsJQ8LsUgUIlULtO:bjgmnxy) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/trajectory_source.cc#L10)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

Already there: output_derivative_order >= 0
</blockquote></details>

my bad. missed that. 

---

*[drake/systems/primitives/trajectory_source.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGznTyQG-M1662_2Qk:-KeKm-KyAbf_lOQR1KqJ:b-5nlqsx) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/trajectory_source.h#L55)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Holding it as a reference is definitely a weird thing.  (1) it forces the caller to retain it, which is annoying; (2) it confuses users as what looks like call-by-value is really call-by-reference, necessitating the doc comment at 33.

I would definitely favor doing a copy if it is cheap.  The argument for the current arrangement would be if copying is expensive and this ctor gets called very frequently; I expect neither is true.

As noted above if you wanted to save the caller the trouble of hanging on to the trajectory forever but also avoid the expense of the copy, you could take the argument via `unique_ptr`.  But since this is a System and so its constructor will probably only be called once per run, spending a few cycles on a copy to save developer confusion seems clearly right.
</blockquote></details>

for all the current Trajectory (which is really just pp trajectory), copying is not expensive at all. i'd vote for saving a copy internally then. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-:-KeKmb8D0qAbDAnMpWTe:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm_cancel:  sorry, that was a typo.  I mean to say lgtm after the copy question is resolved.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-:-KeKmdAshSzmyQ4N0gyh:bnwsety)*

**Comment by Lucy-tri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/trajectory_source.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeGznTyQG-M1662_2Qk:-KeZynpJvoukXDoIdAc5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b98bfba0e0952ab6b4b2083483dd157069913530/drake/systems/primitives/trajectory_source.h#L55)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

for all the current Trajectory (which is really just pp trajectory), copying is not expensive at all. i'd vote for saving a copy internally then. 
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/trajectory_source_test.cc, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-KeKdF4iZu1VTo-72WMG:-KeZypXWWDlV_AFq2_Gn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8fc99b1dbdb2e4cad5dd1396f64ae67450023a64/drake/systems/primitives/test/trajectory_source_test.cc#L70)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- This would be clearer if you noted that `y` here means `kTestTime`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5386#-:-Ke_1Z-dQblwbA78Jl5O:bnfp4nl)*

**Pull request merged**
