### PR TITLE
Rename ContextBase -> Context (part 2 of 2).

### LINKED ISSUE #3200: Rename ContextBase to Context and Context to LeafContext
cc @sherm1

### PR DESCRIPTION
**Pull request by sherm1**
This PR along with #3354 fixes #3200.

After this we have:
```
Context
    LeafContext
    DiagramContext
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3377)

### CODE REVIEW

**Comment by sherm1** [comment]
+@david-german-tri for feature & platform review, please (or reassign). Should be nothing by renames here of ContextBase and context_base.*.

---

Review status: 0 of 53 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3377#-:-KR5JLxhDhRcBHLP221I:b-t96fj3)*

**Comment by david-german-tri** [comment]
:lgtm: Thanks for doing this!  FYI, I renamed context_test.cc to leaf_context_test.cc in #3376 (which is mostly not about that, and is pending your review).

---

Review status: 0 of 53 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3377#-:-KR5JYo8wJZX-ciec-uP:byeh2v3)*

**Comment by david-german-tri** [comment]
Reviewed 54 of 54 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3377)*

**Comment by sherm1** [comment]
Oh, I should have done that here. Would you prefer I do it to make this PR complete, or that I not do it so you don't have to merge?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3377#-:-KR5MrFgx2Yi39F7Wi2M:bm3b46h)*

**Comment by david-german-tri** [comment]
Since you're about to have to redo CI for a handful of lurking `ContextBase`s anyway, I vote for renaming the test in this PR as well, and I'll suffer through the merge.  (-:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3377#-:-KR5RpinITou4DI9m8CD:by88cms)*

**Comment by david-german-tri** [comment]
Also, the impact to `examples/Cars` means you should ask Jenkins to run `linux-clang-experimental-ros`, AIUI.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3377#-:-KR5SI5xgLF32gom-uam:bsimdg6)*

**Comment by jwnimmer-tri** [comment]
> ... examples/Cars means you should ask Jenkins to run linux-clang-experimental-ros, AIUI.

Yup.  If you change examples/Cars, we recommend you opt-in to that test pre-merge, or risk having buildcop revert your PR once it hits master (Continuous).  Liang is working on getting pre-merge coverage.

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by sherm1** [comment]
All good now, including the ROS build. BTW, the reason I missed those three `examples/Cars` was that they were disabled on Windows and therefore didn't show up in the IDE as part of the project when I did the big rename.

---

Review status: 52 of 57 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3377#-:-KR6pF5UFHPacDHXoAzQ:bopf4wg)*

**Comment by jwnimmer-tri** [comment]
> ... reason I missed those three examples/Cars was that they were disabled on Windows ...

FYI, I've (mostly) fixed this now in #3386.  Only two files remain disabled.

**Pull request merged**
