### PR TITLE
Enable if-then-else in DrealSolver

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8180)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for both-reviews, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8180#-:-L6ISBAhcDynE40Y46jo:bi7y8gn)*

**Comment by jamiesnape** [comment]
BTW you can cleanup https://github.com/RobotLocomotion/drake/blob/fd4c235a3f5e9fe69bddacbaa86940e316c1bc30/tools/workspace/dreal/repository.bzl#L16-L17 now (does not have to be in this PR, though).

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8180#-:-L6IXc6Itk4gPXfPxD0X:bu5yo9j)*

**Comment by soonho-tri** [comment]
=> https://github.com/RobotLocomotion/drake/pull/8185

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8180#-:-L6I_F2RfgAeZb4oQoAk:b-uf0lo2)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/test/dreal_solver_test.cc, line 422 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8180#-L6Ia0apqyGcW282RCxb:-L6Ia0apqyGcW282RCxc:b-lv605u) ([raw file](https://github.com/robotlocomotion/drake/blob/e51a7db9748d163a8b60d0751f8c13f5b9774812/solvers/test/dreal_solver_test.cc#L422)):*
> ```cpp
> }
> 
> TEST_F(DrealSolverTest, UnsupportedFormulaIfThenElse1) {
> ```

BTW Is this test case name still appropriate.  I don't see "Unsupported"'s meaning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8180#-:-L6IaMRexpevlHR-BfDU:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/test/dreal_solver_test.cc, line 422 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8180#-L6Ia0apqyGcW282RCxb:-L6IbCPcnI9Fsw0jd_bz:bu9g7cx) ([raw file](https://github.com/robotlocomotion/drake/blob/e51a7db9748d163a8b60d0751f8c13f5b9774812/solvers/test/dreal_solver_test.cc#L422)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is this test case name still appropriate.  I don't see "Unsupported"'s meaning.
</blockquote></details>

Done. Thanks for catching them!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8180)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8180)*

**Pull request merged**
