### PR TITLE
Fix the pick and place configuration parsing to use proto2

### PR DESCRIPTION
**Pull request by jamiesnape**
Broken out from #7323, rebased on master, and merge conflicts fixed. FYI @clalancette.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7534)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@avalenzu for feature review.

**Comment by clalancette** [comment]
@jamiesnape Thanks for getting this done.

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-L-8K87xKE7JYzjG8sIH:-L-8K87yOc7HJNLq-yUa:b-ipel0k) ([raw file](https://github.com/robotlocomotion/drake/blob/977ab51bb482445da83cf2ef407d72ae29283ddd/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto#L26)):*
> ```protobuf
>     // The unique identifier assigned to this object by the motion-capture
>     // system.
>     optional int32 id = 1;
> ```

BTW Do we need all of these to be `optional`? I know that they're implicitly optional in proto3, but the intention here was that anything that didn't have a `DEFAULT` in the comment was required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-:-L-8LvKx0VXK_Hrgpx9n:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-L-8K87xKE7JYzjG8sIH:-L-8Nzxt2H41ITtCai_k:b-iro92l) ([raw file](https://github.com/robotlocomotion/drake/blob/977ab51bb482445da83cf2ef407d72ae29283ddd/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto#L26)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW Do we need all of these to be `optional`? I know that they're implicitly optional in proto3, but the intention here was that anything that didn't have a `DEFAULT` in the comment was required.
</blockquote></details>

BTWS Not especially. How is the latest revision?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7534)*

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for platform review.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: modulo some apparent copying. Am I missing something?

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-L-8dhOTpGmtoAxHw0G8:-L-8dhOTpGmtoAxHw0G9:b7wz9v9) ([raw file](https://github.com/robotlocomotion/drake/blob/1e84777a67723e1213ddac936a8393434ba4197f/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L54)):*
> ```cpp
>     const proto::PickAndPlaceConfiguration& configuration,
>     const proto::ModelInstance& model_instance) {
>   auto items = configuration.model().items();
> ```

BTW Is this intentionally copying (i.e., instead of `const auto& items`?

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-L-8dt03hB2wvYbPk-h6:-L-8dt03hB2wvYbPk-h7:bb3c8py) ([raw file](https://github.com/robotlocomotion/drake/blob/1e84777a67723e1213ddac936a8393434ba4197f/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L56)):*
> ```cpp
>   auto items = configuration.model().items();
>   for (int i = 0; i < items.size(); i++) {
>     auto current_item = items.Get(i);
> ```

BTW Likewise copying.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-L-8e75ypavMvgNH-VNj:-L-8e75ypavMvgNH-VNk:burrulc) ([raw file](https://github.com/robotlocomotion/drake/blob/1e84777a67723e1213ddac936a8393434ba4197f/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L61)):*
> ```cpp
>     }
>     if (current_item.key() == model_instance.name()) {
>       return configuration.model().items().Get(i).value();
> ```

BTW while this works (and is necessary due to the other copying), if the copying is removed, this would become `return current_item.value();`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-:-L-8eX6Qf09IXDjLlbSL:bfthv7l)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7534)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-L-8dhOTpGmtoAxHw0G8:-L-8fRdFV6p5AGu5EdN0:b-t6ak6s) ([raw file](https://github.com/robotlocomotion/drake/blob/1e84777a67723e1213ddac936a8393434ba4197f/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is this intentionally copying (i.e., instead of `const auto& items`?
</blockquote></details>

BTW I will defer to @clalancette to answer that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7534)*

**Comment by clalancette** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-L-8dhOTpGmtoAxHw0G8:-L-8kp54vO7hB2tzvsHp:btvxgat) ([raw file](https://github.com/robotlocomotion/drake/blob/1e84777a67723e1213ddac936a8393434ba4197f/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L54)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I will defer to @clalancette to answer that.
</blockquote></details>

No, that was a mistake.  You are right, this should be a const reference instead, and then the problem below would disappear as well.  @jamiesnape, do you want to change it, or should I?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7534)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-L-8dhOTpGmtoAxHw0G8:-L-8lDfTzmkYp52V5kWD:b-e58r6u) ([raw file](https://github.com/robotlocomotion/drake/blob/1e84777a67723e1213ddac936a8393434ba4197f/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L54)):*
<details><summary><i>Previously, clalancette (Chris Lalancette) wrote…</i></summary><blockquote>

No, that was a mistake.  You are right, this should be a const reference instead, and then the problem below would disappear as well.  @jamiesnape, do you want to change it, or should I?
</blockquote></details>

I can do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7534)*

**Comment by jamiesnape** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-L-8dhOTpGmtoAxHw0G8:-L-8mAhYlrPQE_zVhWqa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e84777a67723e1213ddac936a8393434ba4197f/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L54)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I can do it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7534)*

**Comment by SeanCurtis-TRI** [comment]
Great thanks.

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7534#-:-L-909NplDgygJeXaDTt:bo3nnql)*

**Pull request merged**
