### PR TITLE
Use std::isinf to fix compile error on Xenial builds

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Example of failing build: https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=159748

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3926)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-experimental please

**Comment by BetsyMcPhail** [comment]
+@hongkai-dai  for feature review (updating code introduced in #3834)  and +@jwnimmer-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3926#-:-KV5wgFmMd0MjAuZwy7c:bizvv0x)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/gurobi_solver.cc, line 338 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3926#-KV5yq5brrVuhnLBTLch:-KV5yq5brrVuhnLBTLci:b13xkl) ([raw file](https://github.com/robotlocomotion/drake/blob/d664085d9df6ea608a15b272919335c71d30853c/drake/solvers/gurobi_solver.cc#L338)):*
> ```cpp
>         }
>       }
>       if (!std::isinf(lb(i))) {
> ```

BTW Relatedly, missing an `#include <cmath>` atop this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3926#-:-KV5ykdSyNYn9DEAz9MV:bnfp4nl)*

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by BetsyMcPhail** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/gurobi_solver.cc, line 338 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3926#-KV5yq5brrVuhnLBTLch:-KV6-JrFuCVWtZJiFHAz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d664085d9df6ea608a15b272919335c71d30853c/drake/solvers/gurobi_solver.cc#L338)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Relatedly, missing an `#include <cmath>` atop this file.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3926)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3926)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
I'll assert no feature review needed for this.  @hongkai-dai if you have comments we can follow-up PR this.

**Pull request merged**
