### PR TITLE
Load joint limit parameters from SDF

### PR DESCRIPTION
**Pull request by ggould-tri**
Load limit penetration parameters from SDF (`joint::axis::limit::stiffness` and `joint::axis::limit::dissipation` in the XML) and apply them in `RigidBodyPlant::EvalTimeDerivatives`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3746)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
+@sherm1 for platform review
+@liangfok for feature reivew

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTjuw-_rzC2MJI3ALvR:bc1eji5)*

**Comment by sherm1** [comment]
A few issues (comments below, PTAL):
- these per-axis parameters won't work on joints with quaternions, and don't mean much on joints with roll-pitch-yaw parameterization either, except near rpy=000. Not sure there is anything to do about that but a comment mentioning it would be helpful.
- dissipation != damping. Dissipation has units of 1/v, damping is force/v. A few names need fixing and the limit-force formula needs an adjustment.
- limits are unilateral so need min(force,0) and max(force,0) treatment to avoid "sucking" forces

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/joints/DrakeJoint.cpp, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTjqePqbC1g3lTpyiyC:-KTjqePrS-rgWk6-YyAJ:b-ny7aoc) ([raw file](https://github.com/robotlocomotion/drake/blob/29617f052827123a7b57e07657951f69479702f6/drake/systems/plants/joints/DrakeJoint.cpp#L18)):*
> ```cpp
>           _num_positions, 150. /* Historic default from RigidBodyPlant. */)),
>       joint_limit_dissipation_(VectorXd::Constant(
>           _num_positions, 15. /* Historic default from RigidBodyPlant. */)),
> ```

Since dissipation (units of 1/v) is very different from damping (units of force/v), shouldn't use the historic value here. I would suggest a default of 1 which would be fairly large.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTjsCjahlb116cAKOk_:-KTjsCjbL5rAGY8XPN98:b-51tyqx) ([raw file](https://github.com/robotlocomotion/drake/blob/29617f052827123a7b57e07657951f69479702f6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L232)):*
> ```cpp
>         // tau = k * (qlimit-q) - b(qdot)
>         const double joint_stiffness = joint.get_joint_limit_stiffness()(0);
>         const double joint_damping = joint.get_joint_limit_dissipation()(0);
> ```

Should be `joint_dissipation`.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 236 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTjsQ5gycpAly5y4tI6:-KTjsQ5gycpAly5y4tI7:b-pfywjk) ([raw file](https://github.com/robotlocomotion/drake/blob/29617f052827123a7b57e07657951f69479702f6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L236)):*
> ```cpp
>           right_hand_side(b->get_velocity_start_index()) -=
>               joint_stiffness * (qmin - q(b->get_position_start_index()))
>                   - joint_damping * v(b->get_velocity_start_index());
> ```

Should be `kx(1+d xdot)` where d is dissipation (not damping) constant.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTjtVlye9JIqTO2yp-e:-KTjtVlye9JIqTO2yp-f:b2ta89l) ([raw file](https://github.com/robotlocomotion/drake/blob/29617f052827123a7b57e07657951f69479702f6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L240)):*
> ```cpp
>           right_hand_side(b->get_velocity_start_index()) -=
>               joint_stiffness * (qmax - q(b->get_position_start_index()))
>                   - joint_damping * v(b->get_velocity_start_index());
> ```

Joint limits are unilateral, so the two expressions above should be prevented from generating "pulling" forces, which is possible with these formulas. The lower limit should only generate positive forces, and the upper limit should only generate negative forces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTjvFnw2k8o0qXg6f4O:b-pjld6d)*

**Comment by ggould-tri** [comment]
Excellent comments!  I couldn't find a good definition of dissipation for this context; can you point me at a good reference?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTjx02-BCTnWjWzSWtj:b-z1yl88)*

**Comment by sherm1** [comment]
[Here](https://simtk.org/api_docs/simbody/latest/classSimTK_1_1Force_1_1MobilityLinearStop.html#details) is a good writeup of how these limits should work. That is the actual Simbody force model that the SDF stiffness/dissipation parameters were added to represent -- ours should do the same thing so that they will have the same meaning.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTjwrpUX7eXpLuBkH8Y:bx0ddt8)*

**Comment by ggould-tri** [comment]
Great.  I'm flagging this as +(status: do not merge) +(status: do not review) in the meantime.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTjxSZ21GX0Fl8pGm3S:b-kqtv2a)*

**Comment by sherm1** [comment]
(Caution: note the definition of `x`, the violation, in Simbody vs that definition in current Drake code.)

Would be good to have a unit test making sure the signs make sense!

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTjx_ayXqjQabqmhz-x:bukrwwi)*

**Comment by liangfok** [comment]
OK. I'll feature review this once the "do not review" label is removed.

**Comment by ggould-tri** [comment]
Wow do I wish that SDF actually had that documentation for its parameter!

So as I read it, dissipation is a velocity-dependent increase in the spring constant, making the spring harder against movements out of bounds and softer against movements back in-bounds.

The existing code already only applies limits on single-DoF joints (see `rigid_body_plant.cc:225`) so I'm not worried about the rpy/quaternion cases.

Updated code coming soon.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTk2bZ5cpiFus9PAcUt:b6sjpvj)*

**Comment by sherm1** [comment]
> So as I read it, dissipation is a velocity-dependent increase in the spring constant

That's an interesting way to think about it. I'm not sure whether it's a useful way to think of it though since "stiffness" is usually thought of as a displacement-only, conservative effect. Dissipation OTOH is about rate-dependent energy loss to heat, sound, vibration, and plasticity and the effect depends on the current state of the material, approximated here by the amount of force it is producing due to displacement.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTk7vgmKMTZbYzVbtlS:bidgrg8)*

**Comment by ggould-tri** [comment]
Interesting.  I was mentally factoring it to (k + k*v*d)*x.

Anyway, I have implemented the new formula in `EvalTimeDerivatives` on my branch but alarmingly no tests fail, leading me to suspect that it is a test coverage vacuum.  So this is all going to hold up while I figure out how to get some coverage on this -- I'm definitely not landing it until I can be sure I didn't flip a sign somewhere.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTkD65SpcgJ0qQ42hCq:bdboevm)*

**Comment by ggould-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
As the message above notes:  I implemented your formula, factored it into a separate static method, and added a test case for that method to be sure it behaved in the described way. -(status: do not merge)  -(status: do not review) 

---

Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/joints/DrakeJoint.cpp, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTjqePqbC1g3lTpyiyC:-KToQp_kyEtMtA8n4HUE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/29617f052827123a7b57e07657951f69479702f6/drake/systems/plants/joints/DrakeJoint.cpp#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Since dissipation (units of 1/v) is very different from damping (units of force/v), shouldn't use the historic value here. I would suggest a default of 1 which would be fairly large.
</details>
Done.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTjsCjahlb116cAKOk_:-KToQuiZF1VK-EQwytKu:bx5wcx5) ([raw file](https://github.com/robotlocomotion/drake/blob/29617f052827123a7b57e07657951f69479702f6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L232)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should be `joint_dissipation`.
</details>
Done, but also factored to `JointLimitForce` below.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 236 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTjsQ5gycpAly5y4tI6:-KToQzZpqC_g5lWIHaTz:bx5wcx5) ([raw file](https://github.com/robotlocomotion/drake/blob/29617f052827123a7b57e07657951f69479702f6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L236)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should be `kx(1+d xdot)` where d is dissipation (not damping) constant.
</details>
Done, but also factored to `JointLimitForce` below.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTjtVlye9JIqTO2yp-e:-KToR-mfNZ6-X4MkFyAd:bx5wcx5) ([raw file](https://github.com/robotlocomotion/drake/blob/29617f052827123a7b57e07657951f69479702f6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L240)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Joint limits are unilateral, so the two expressions above should be prevented from generating "pulling" forces, which is possible with these formulas. The lower limit should only generate positive forces, and the upper limit should only generate negative forces.
</details>
Done, but also factored to `JointLimitForce` below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KToRBWcyunOq9YFLIN0:b-eoah2j)*

**Comment by liangfok** [comment]
I will review this soon.

---

Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTouuEC9Ku2jfCADBGa:bggua6f)*

**Comment by liangfok** [comment]
I completed my first round of review. Looks great overall. Just one blocking comment and few minor non-blocking comments.

---

Reviewed 5 of 7 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 377 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTp7X8U4hdxqKRAf_zK:-KTp7X8U4hdxqKRAf_zL:bhpl8k7) ([raw file](https://github.com/robotlocomotion/drake/blob/335ee75f3376287f0513c2bc547d58cf370bfbe6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L377)):*
> ```cpp
>                                      const T& position, const T& velocity) {
>   // Joint stop formula (and definition of "dissipation") from:
>   // https://simtk.org/api_docs/simbody/latest/classSimTK_1_1Force_1_1MobilityLinearStop.html#details
> ```

BTW, I found this URL very useful. How about let's move into this method's Doxygen description in the `rigid_body_plant.h`?

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTp5QknCWlW8b3k9aKQ:-KTp5QknCWlW8b3k9aKR:b-fee9b2) ([raw file](https://github.com/robotlocomotion/drake/blob/335ee75f3376287f0513c2bc547d58cf370bfbe6/drake/systems/plants/rigid_body_plant/rigid_body_plant.h#L172)):*
> ```objc
>   }
> 
>   /// Compute the force exerted by a joint limit.  Exposed for unit testing of
> ```

"Compute" should be "Computes".

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTp9_aNt2mFXVXb9ub3:-KTp9_aNt2mFXVXb9ub4:bk64k6f) ([raw file](https://github.com/robotlocomotion/drake/blob/335ee75f3376287f0513c2bc547d58cf370bfbe6/drake/systems/plants/rigid_body_plant/rigid_body_plant.h#L172)):*
> ```objc
>   }
> 
>   /// Compute the force exerted by a joint limit.  Exposed for unit testing of
> ```

BTW, consider replacing "by a joint limit" with "when a joint hits its limit".

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 383 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTp80p_YiCFo5D5bU7s:-KTp80p_YiCFo5D5bU7t:bb1j01s) ([raw file](https://github.com/robotlocomotion/drake/blob/335ee75f3376287f0513c2bc547d58cf370bfbe6/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L383)):*
> ```cpp
>   typedef RigidBodyPlant<double> RBP;
>   const double left_limit = 10.;
>   const double right_limit = 20.;
> ```

BTW, I find "left_limit" and "right_limit" strange since it assumes a certain orientation of the joint w.r.t to observer. Consider using "lower_limit" and "upper_limit".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTp9LHOUItKBpLJ73eA:b4szc4b)*

**Comment by ggould-tri** [comment]
Review status: 6 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 377 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTp7X8U4hdxqKRAf_zK:-KTpKdSRWMWytCWkyhEM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/335ee75f3376287f0513c2bc547d58cf370bfbe6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L377)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, I found this URL very useful. How about let's move into this method's Doxygen description in the `rigid_body_plant.h`?
</details>
Done.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTp5QknCWlW8b3k9aKQ:-KTpKeouZLl9qGwXvdIi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/335ee75f3376287f0513c2bc547d58cf370bfbe6/drake/systems/plants/rigid_body_plant/rigid_body_plant.h#L172)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "Compute" should be "Computes".
</details>
Done.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTp9_aNt2mFXVXb9ub3:-KTpKf9qio67dEBwmVvl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/335ee75f3376287f0513c2bc547d58cf370bfbe6/drake/systems/plants/rigid_body_plant/rigid_body_plant.h#L172)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider replacing "by a joint limit" with "when a joint hits its limit".
</details>
Done.

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 383 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTp80p_YiCFo5D5bU7s:-KTpKgFLJMP-FNmjuFR1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/335ee75f3376287f0513c2bc547d58cf370bfbe6/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L383)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, I find "left_limit" and "right_limit" strange since it assumes a certain orientation of the joint w.r.t to observer. Consider using "lower_limit" and "upper_limit".
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTpLzEhnDPNqbBr60nT:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm_strong: -- this is great, Grant! A few ignorable BTWs, PTAL. One thought: this is a particular joint limit model (linear stiffness). Other models are common such as exponential ones that get steeply stiffer with penetration. We could call this one something more specific like "LinearJointLimit" to leave room for more. OTOH, it would be fine to leave it as-is until we have an actual problem to solve.

---

Reviewed 1 of 4 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 377 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTpOMP3ZqH7issXDmYv:-KTpOMP3ZqH7issXDmYw:b6lsrll) ([raw file](https://github.com/robotlocomotion/drake/blob/11b514660f83e1855e9a31d39b0b41e88420b3d6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L377)):*
> ```cpp
>                                      const T& position, const T& velocity) {
>   const T qmin = joint.getJointLimitMin()(0);
>   const T qmax = joint.getJointLimitMax()(0);
> ```

BTW, I suggest a `DRAKE_DEMAND(qmin<=qmax)` here for sanity checking. Might also want to assert that stiffness>=0 and dissipation>=0.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 392 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTpPq-rAZ4wCxwmNZ2p:-KTpPq-rAZ4wCxwmNZ2q:bdkakzy) ([raw file](https://github.com/robotlocomotion/drake/blob/11b514660f83e1855e9a31d39b0b41e88420b3d6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L392)):*
> ```cpp
>   }
>   return 0;
> }
> ```

BTW, this looks great! I hand checked a pair of +/- violations and the forces seemed right. Minor suggestion: might be slightly clearer to write this with a single return:
```c++
limit_force = std::max(0, limit_force);
// ...
return limit_force;
```

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 403 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTpRdVEmJPlZsZa6jnu:-KTpRdVEmJPlZsZa6jnv:b-jxcbm0) ([raw file](https://github.com/robotlocomotion/drake/blob/11b514660f83e1855e9a31d39b0b41e88420b3d6/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L403)):*
> ```cpp
>               0, epsilon);
>   EXPECT_NEAR(RBP::JointLimitForce(joint, upper_limit + delta, 0),
>               0, epsilon);
> ```

BTW, maybe check that the force is non-zero as well as being smaller than epsilon?

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 431 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTpSFn-iH90GGwu3phW:-KTpSFn-iH90GGwu3phX:b-74ncb6) ([raw file](https://github.com/robotlocomotion/drake/blob/11b514660f83e1855e9a31d39b0b41e88420b3d6/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L431)):*
> ```cpp
>             0);
>   EXPECT_EQ(RBP::JointLimitForce(joint, upper_limit + 1, -10),
>             0);
> ```

BTW, awesome -- very convincing!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTpSRHynxSn2Owz2jET:b-qz8c8)*

**Comment by ggould-tri** [comment]
Added a mention of linear stiffness to the doxygen.  I think even if/when we have multiple stiffness models, we'll still want the top-level entry point to be called `JointLimitForce`, so factoring individual stiffness formulae can happen as needed without adding jargon to the API just yet.

---

Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 377 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTpOMP3ZqH7issXDmYv:-KTpV6d1NqtvYKIzFDjf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11b514660f83e1855e9a31d39b0b41e88420b3d6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L377)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I suggest a `DRAKE_DEMAND(qmin<=qmax)` here for sanity checking. Might also want to assert that stiffness>=0 and dissipation>=0.
</details>
Done.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 392 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTpPq-rAZ4wCxwmNZ2p:-KTpVgweOtYkSTFF9Cwl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11b514660f83e1855e9a31d39b0b41e88420b3d6/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L392)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, this looks great! I hand checked a pair of +/- violations and the forces seemed right. Minor suggestion: might be slightly clearer to write this with a single return:
> ```c++
> limit_force = std::max(0, limit_force);
> // ...
> return limit_force;
> ```
</details>
Done.

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 403 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-KTpRdVEmJPlZsZa6jnu:-KTpVzuyJZPP4Ddi1OlO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11b514660f83e1855e9a31d39b0b41e88420b3d6/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L403)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, maybe check that the force is non-zero as well as being smaller than epsilon?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746#-:-KTpW6McUShpCLoYgpYx:bq6zytn)*

**Comment by sherm1** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3746)*

**Pull request merged**
