### PR TITLE
Update release playbook

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This is from my experience with v1.14.0.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19008)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@sammy-tri for platform review, please.

CC @jwnimmer-tri @BetsyMcPhail 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19008#-:-NQbYB3E9EEnevNNrOel:b-3955yd)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19008)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy and @sammy-tri)

___
*[`doc/_pages/release_playbook.md` line 190 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19008#-NQbZrCV2Bbma0cT7A9C:-NQbZrCV2Bbma0cT7A9D:bigd39t) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e18623191ef9154f75b9394f30f0186bc82ce13/doc/_pages/release_playbook.md#L190)):*
> ```Markdown
>    3. Notify `@BetsyMcPhail` by creating a GitHub issue asking her to manually 
>       tag docker images and upload the releases to S3. Be sure to provide her 
>       with the binary date, commit SHA, and release tag in the same ping.
> ```

nit I no longer need the binary date, just the commit SHA and release tag. I appreciate a new GitHub issue,  it's easier for me to track on the project board.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19008)* status: 1 unresolved discussion, LGTM missing from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @DamrongGuoy, @jwnimmer-tri, and @sammy-tri)

___
*[`doc/_pages/release_playbook.md` line 190 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19008#-NQbZrCV2Bbma0cT7A9C:-NQeAgTLAXL_6fIy1CYL:b-yq61h8) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e18623191ef9154f75b9394f30f0186bc82ce13/doc/_pages/release_playbook.md#L190)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

nit I no longer need the binary date, just the commit SHA and release tag. I appreciate a new GitHub issue,  it's easier for me to track on the project board.
</blockquote></details>

Sorry, I commented without referring to the script. The information needed is actually binary date and release tag. The script no longer requires the commit SHA.

**Review by sammy-tri — COMMENTED** [review]
:lgtm: but +@BetsyMcPhail for feature review (because you've read it already and I've never actually run the release playbook)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19008#-:-NQek9sr9tBGr6RDqTtu:bndcb5x)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),BetsyMcPhail (waiting on @DamrongGuoy and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19008#-:-NQerfsv8GZMdm6VfegV:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee BetsyMcPhail (waiting on @DamrongGuoy)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19008#-:-NQf3t079qEZvbgWq6pm:bnfp4nl)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19008#-:-NQgMP2QBbP-RrnlQaHz:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19008#-:-NQgZt3s0WCufZEAHaqu:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform),BetsyMcPhail (waiting on @DamrongGuoy)

**Pull request merged**
