### PR TITLE
Scope the non-const arguments to SetDefault{State,Parameters} more narrowly.

### LINKED ISSUE #4385: SetDefaultState(Context*) should be SetDefaultState(const Context&, State*)
same for SetDefaultParameters()

requires a little implementation work to deal with diagrams.  this is a followup to the discussion here:
https://reviewable.io/reviews/robotlocomotion/drake/4357#-KYEg0EsZ88XJCHnJgVB

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #4385.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4489)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Pinging CI, please don't review yet.

**Comment by david-german-tri** [comment]
+@jadecastro for feature review (it has to do with parameters), and +@jwnimmer-tri for platform review, out of turn since he identified the original defect

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-:-KYuDIxvn9x9ZZR7a9i5:b9fylsp)*

**Comment by jwnimmer-tri** [comment]
Wow, talk about negative incentives ;).  But of course I am most happy to review and will do so tonight.

**Comment by david-german-tri** [comment]
> Wow, talk about negative incentives ;).

Look at it this way - I'm giving you the opportunity to take credit for it in your weekly summaries.

**Comment by jwnimmer-tri** [comment]
Heh, _right_.  Well, points for finding defects would be good, except then you get voting rings.  Metrics are hard, let's go shopping.

**Comment by jwnimmer-tri** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/automotive/idm_planner.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYuuIhAkNKFPGRm19UE:-KYuuIhAkNKFPGRm19UF:b-xjwiwe) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/automotive/idm_planner.cc#L106)):*
> ```cpp
>   auto idm_params = dynamic_cast<IdmPlannerParameters<T>*>(
>       params->get_mutable_numeric_parameter(0));
>   DRAKE_DEMAND(params != nullptr);
> ```

This seems wrong, or at a minimum in the wrong place.  Our men are already dead.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_world_demo.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYuw-ycmdqG5VvOth4V:-KYuw-ycmdqG5VvOth4W:b-92an4h) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_world_demo.cc#L80)):*
> ```cpp
> 
>   systems::Context<double>* context = simulator->get_mutable_context();
>   demo_plant->SetDefaultState(*context, context->get_mutable_state());
> ```

BTW Should the old method signature remain intact as sugar (with this two-line idiom as its body)?  I guess this being the only call site suggests "no, or at least not yet".

---

*[drake/systems/framework/diagram.h, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYuo6HvOMa1xPo4l524:-KYuo6HvOMa1xPo4l525:b-u5ioso) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/diagram.h#L227)):*
Here, I originally wrote to myself
> I think this method body is missing a call to `this->SetDefaultState(.)`?  Or at least, I can't figure out how a `Diagram::CreateDefaultContext` and/or `Diagram::SetDefaults` ends up calling any subsystems' `SetDefaultState` by any means.

However, on further reading, I see that `SetDefaults` is applied by composite to all children in the loop below, and the children do their own `SetDefaultState`.

I think that`System::SetDefaults` has an implementation that is only ever called from `LeafSystem`.  This is a surprise to the reader, who expects it to be used for all `System` types.

Perhaps `System::SetDefaults` should be a pure virtual (or a public NVI wrapper for a protected pure virtual), that is implemented (as final) in Leaf and Diagram?  That might be clearer to future readers.

---

*[drake/systems/framework/diagram_context.h, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYuxITJL7qNxW_vicPc:-KYuxITJL7qNxW_vicPd:b-km21gm) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/diagram_context.h#L28)):*
> ```objc
>  public:
>   /// Constructs a DiagramState consisting of @p size substates.
>   explicit DiagramState<T>(int size) : State<T>(), substates_(size) {}
> ```

TIL `vector(size_t)` does value-initialization these days.  Neat!

---

*[drake/systems/framework/leaf_system.h, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYuquZCmK7VXeEj2zOW:-KYuquZCmK7VXeEj2zOX:btc8uzi) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/leaf_system.h#L102)):*
> ```objc
>     SetDefaultParameters(*leaf_context, leaf_context->get_mutable_parameters());
>     // Implementations of SetDefaultParameters must not change the number of
>     // parameters.
> ```

Should this be an API comment on `SetDefaultParameters`?

---

*[drake/systems/framework/system.h, line 197 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYumCEsRBvMHWwblWfs:-KYumCEsRBvMHWwblWft:b-s7t9j9) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/system.h#L197)):*
> ```objc
> 
>     // Implementations of SetDefaultState are not allowed to change the number
>     // of State elements.
> ```

Should this be an API comment on `SetDefaultState`?

---

*[drake/systems/framework/test/leaf_system_test.cc, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYutUokAs1_UXxbu9wm:-KYutUolK3A8_A5P5Cj-:b-ogjcbg) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/test/leaf_system_test.cc#L66)):*
> ```cpp
>   void SetDefaultParameters(const LeafContext<T>& context,
>                             Parameters<T>* params) const override {
>     auto p = params->get_mutable_numeric_parameter(0);
> ```

BTW This `auto` might not be consistent with cppguide.  The type as returned by the method is not super-clear, perhaps?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4489)*

**Comment by liangfok** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/Quadrotor/run_quadrotor_dynamics.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYxdKFTKXNfWd_Cmu3t:-KYxdKFTKXNfWd_Cmu3u:b5mjdvf) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/examples/Quadrotor/run_quadrotor_dynamics.cc#L69)):*
> ```cpp
>   void SetDefaultState(const systems::Context<T>& context,
>                        systems::State<T>* state) const override {
>     systems::Diagram<T>::SetDefaultState(context, state);
> ```

BTW, in the spirit of failing fast, should there be a `DRAKE_DEMAND(state != nullptr);` before this line?

(Same comment to all other instances in this PR.)

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.h, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYxeO7EpHmoerzw6p5F:-KYxeO7FeGcpNJgPoM9G:b-vx030c) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/multibody/rigid_body_plant/rigid_body_plant.h#L129)):*
> ```objc
>                         const Eigen::Ref<const VectorX<T>> x) const;
> 
>   /// Sets the continuous state vector of the system to be @p x.
> ```

BTW, should "the system" be "this system"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4489)*

**Comment by jadecastro** [comment]
A couple comments below.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYxnSDz8UajCtHlQifV:-KYxnSDz8UajCtHlQifW:b-86yxez) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/test/diagram_context_test.cc#L150)):*
> ```cpp
> // substates in the subsystem contexts.
> TEST_F(DiagramContextTest, DiagramState) {
>   auto diagram_state = dynamic_cast<DiagramState<double>*>(
> ```

Do we need a `DRAKE_DEMAND(diagram_state != nullptr);`?  I wasn't sure if this is optional in unit tests, but did notice we have nullptr checks in other unit tests, like what you have in `diagram_test`.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYxlgDxvpwcyHn5-80L:-KYxlgDygIczmlvSXANm:b3hx5dh) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/test/diagram_context_test.cc#L152)):*
> ```cpp
>   auto diagram_state = dynamic_cast<DiagramState<double>*>(
>       context_->get_mutable_state());
>   for (int i = 0; i < 5; ++i) {
> ```

You might consider replacing `5` with `kNumSystems`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-:-KYxqU98ymmfYBnDM1kn:bv6a0bx)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/idm_planner.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYuuIhAkNKFPGRm19UE:-KYxnQWkB7V20NVnW15a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/automotive/idm_planner.cc#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems wrong, or at a minimum in the wrong place.  Our men are already dead.
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/run_quadrotor_dynamics.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYxdKFTKXNfWd_Cmu3t:-KYxpeKPDRKtwcLlTZFC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/examples/Quadrotor/run_quadrotor_dynamics.cc#L69)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, in the spirit of failing fast, should there be a `DRAKE_DEMAND(state != nullptr);` before this line?

(Same comment to all other instances in this PR.)
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram.h, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYuo6HvOMa1xPo4l524:-KYxotwhKFyTRuLWTL8Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/diagram.h#L227)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here, I originally wrote to myself
> I think this method body is missing a call to `this->SetDefaultState(.)`?  Or at least, I can't figure out how a `Diagram::CreateDefaultContext` and/or `Diagram::SetDefaults` ends up calling any subsystems' `SetDefaultState` by any means.

However, on further reading, I see that `SetDefaults` is applied by composite to all children in the loop below, and the children do their own `SetDefaultState`.

I think that`System::SetDefaults` has an implementation that is only ever called from `LeafSystem`.  This is a surprise to the reader, who expects it to be used for all `System` types.

Perhaps `System::SetDefaults` should be a pure virtual (or a public NVI wrapper for a protected pure virtual), that is implemented (as final) in Leaf and Diagram?  That might be clearer to future readers.
</blockquote></details>

Done.

---

*[drake/systems/framework/leaf_system.h, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYuquZCmK7VXeEj2zOW:-KYxp31ZGoB-ijPTCNb8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/leaf_system.h#L102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Should this be an API comment on `SetDefaultParameters`?
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 197 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYumCEsRBvMHWwblWfs:-KYxp47eK-9ILrPQpv7O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/system.h#L197)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Should this be an API comment on `SetDefaultState`?
</blockquote></details>

Done.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYxnSDz8UajCtHlQifV:-KYxuMBxOO1voWVfdml-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/test/diagram_context_test.cc#L150)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Do we need a `DRAKE_DEMAND(diagram_state != nullptr);`?  I wasn't sure if this is optional in unit tests, but did notice we have nullptr checks in other unit tests, like what you have in `diagram_test`.
</blockquote></details>

Done.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYxlgDxvpwcyHn5-80L:-KYxuIirygtOyrpUJZuh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/test/diagram_context_test.cc#L152)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

You might consider replacing `5` with `kNumSystems`.
</blockquote></details>

Done.

---

*[drake/systems/framework/test/leaf_system_test.cc, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-KYutUokAs1_UXxbu9wm:-KYxpYVvDDU0xK_-CTtN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e3924bf47ef944ed353146be435434c177a0146/drake/systems/framework/test/leaf_system_test.cc#L66)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This `auto` might not be consistent with cppguide.  The type as returned by the method is not super-clear, perhaps?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4489)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: 13 of 22 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-:-KYxygSAZ_8VzT6ExNfP:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4489#-:-KYy3lGvTaZu1P-Ne-ky:bnfp4nl)*

**Pull request merged**
