### PR TITLE
wip: first sketch of hydro-inferred mode and plumbing

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
FYI @DamrongGuoy @SeanCurtis-TRI @jwnimmer-tri 

Note that this so far is just the earliest possible sketch -- no real commitments to form or spelling yet, just trying to see what can work at all. In particular the mountain of `{set,get}_hydro_inferred` methods is not awesome, but it gets me the bare minimum of initialization-time communication along the plant<=>scene-graph<=>geometry-state<=>proximity-engine<=>hydro-geometries chain.

Note there are no docs, tests, or examples yet. I may look into some minimal python binding support, so perhaps we can experiment with models/sims/scenarios via notebooks.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-:-NbGcsjx3VWGWQ8jWWNI:b-ih7p6s)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
Looks OK to me.  At first I was surprised to see the SceneGraphInspector offer a getter for this, but I suppose it makes sense because its a property of the GeometryState, not the SceneGraph.  The setter on SceneGraph should probably make it clear that it will not affect already-created contexts.

**Review by rpoyner-tri — COMMENTED** [review]
I suppose we could have context-accepting setters and getters...but I'm happy to wait until there is a reason to want them, and we have a design we like for that communication to begin with.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-:-NbGj6GL3N5e57LGeKya:bxsfbza)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/scene_graph.cc` line 376 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-NbHrxgl6DY5h7xmIAv3:-NbHrxgn4xrL_dcG8v_Y:b3qcz6s) ([raw file](https://github.com/RobotLocomotion/drake/blob/349426f40e78dee9664f57cb59d824c0e7ed7f96/geometry/scene_graph.cc#L376)):*
> ```cpp
> template <typename T>
> void SceneGraph<T>::set_hydro_inferred(bool value) {
>     model_.set_hydro_inferred(value);
> ```

When this changes, I think we probably need to re-spin the `MaybeAddGeometry` logic, to adjust the emboded model.

It that change-handling becomes difficult to implement in the MVP, this could move to be a `SceneGraph` constructor argument, with no setter.

**Review by RussTedrake — COMMENTED** [review]
btw -- :heart:  Thanks for pushing this!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-:-NbJYGhw8zx3meEry6GY:b-6ax6dx)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Motivating issue is #19709, FTR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-:-NbKJLaSEWOrUanxVzDq:b84a847)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/scene_graph.cc` line 376 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-NbHrxgl6DY5h7xmIAv3:-Nc-6lIr98AnM8OLEP1C:b8ez9rv) ([raw file](https://github.com/RobotLocomotion/drake/blob/349426f40e78dee9664f57cb59d824c0e7ed7f96/geometry/scene_graph.cc#L376)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When this changes, I think we probably need to re-spin the `MaybeAddGeometry` logic, to adjust the emboded model.

It that change-handling becomes difficult to implement in the MVP, this could move to be a `SceneGraph` constructor argument, with no setter.
</blockquote></details>

I think the SceneGraph constructor argument is either (a) a non-starter, or (b) a clue that the new feature should not be a ContactModel enum value, but instead something else.

The difficulty is that we create mbps and scenegraphs early, and (often) only set the contact model in the last moment before calling Finalize(). Adding to this, we have any number of convenience workflows for creating mbp/sg pairs, and threading through some extra parameter all of those sounds hardly worthwhile.

**Review by rpoyner-tri — COMMENTED** [review]
The mods to rolling_sphere have been helpful to give (non-crashing) proof of "life" for kHydroelasticInferred, but do nothing to demonstrate that we can actually operate on naive assets. That work is still ongoing.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-:-Nc-8-DQ0uaRZhzNN1t4:b-s3wdwe)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/scene_graph.cc` line 376 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-NbHrxgl6DY5h7xmIAv3:-Nc-9Ja5-NUtoKEbU3DC:basvtk0) ([raw file](https://github.com/RobotLocomotion/drake/blob/349426f40e78dee9664f57cb59d824c0e7ed7f96/geometry/scene_graph.cc#L376)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I think the SceneGraph constructor argument is either (a) a non-starter, or (b) a clue that the new feature should not be a ContactModel enum value, but instead something else.

The difficulty is that we create mbps and scenegraphs early, and (often) only set the contact model in the last moment before calling Finalize(). Adding to this, we have any number of convenience workflows for creating mbp/sg pairs, and threading through some extra parameter all of those sounds hardly worthwhile.
</blockquote></details>

s/before calling Finalize/even after calling Finalize/

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/scene_graph.cc` line 376 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-NbHrxgl6DY5h7xmIAv3:-Nc-B-8dD2ysQgDKtcjF:bji8i82) ([raw file](https://github.com/RobotLocomotion/drake/blob/349426f40e78dee9664f57cb59d824c0e7ed7f96/geometry/scene_graph.cc#L376)):*
My point is that **either** we need to carefully implement the "update anything that would be impacted" logic here, **or else** we need to demand that the user choose right away with a constructor argument (and no setter).  Possibly the "right away" caveat would just be for MVP, and we could later on implement the more complicated change tracking.

> The difficulty is that we create mbps and scenegraphs early, and (often) only set the contact model in the last moment before calling Finalize().

Sure, but ... why do people need to do that that way?  Isn't that all just historical cruft?  Are there any important use cases where they cannot decide, up front, how they plan to simulate their world?  Would it not be plausible to say "If you want nice things, you need to call the canonical function `AddMultibodyPlant(const MultibodyPlantConfig& config, systems::DiagramBuilder<double>* builder);` to instantiate your plant."?

In the original days, we expected that users would carefully write a lot of code to handle the setup boilerplate, which is where the kind habit you're talking about comes from.  That is no longer the preferred style, and we don't really care about making that easy.  The workflow we should be laser focused on is the Config / Params / YAML workflow.  Sim setup should be declarative, not imperative.  New users should always be using `Config` structs, never calling those weird legacy factory functions.

For my part, I would be satisfied if _only_ the config workflow got this nice-hydro-fallback-by-default feature.  If we can take a shortcut to make that happen faster (i.e., the constructor arg; no setter), that's my vote.  The setter function can be an add-on, if we later find a need for it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/scene_graph.cc` line 376 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-NbHrxgl6DY5h7xmIAv3:-Nc-xB2R1AiAjJmPzQCR:b-or0092) ([raw file](https://github.com/RobotLocomotion/drake/blob/349426f40e78dee9664f57cb59d824c0e7ed7f96/geometry/scene_graph.cc#L376)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My point is that **either** we need to carefully implement the "update anything that would be impacted" logic here, **or else** we need to demand that the user choose right away with a constructor argument (and no setter).  Possibly the "right away" caveat would just be for MVP, and we could later on implement the more complicated change tracking.

> The difficulty is that we create mbps and scenegraphs early, and (often) only set the contact model in the last moment before calling Finalize().

Sure, but ... why do people need to do that that way?  Isn't that all just historical cruft?  Are there any important use cases where they cannot decide, up front, how they plan to simulate their world?  Would it not be plausible to say "If you want nice things, you need to call the canonical function `AddMultibodyPlant(const MultibodyPlantConfig& config, systems::DiagramBuilder<double>* builder);` to instantiate your plant."?

In the original days, we expected that users would carefully write a lot of code to handle the setup boilerplate, which is where the kind habit you're talking about comes from.  That is no longer the preferred style, and we don't really care about making that easy.  The workflow we should be laser focused on is the Config / Params / YAML workflow.  Sim setup should be declarative, not imperative.  New users should always be using `Config` structs, never calling those weird legacy factory functions.

For my part, I would be satisfied if _only_ the config workflow got this nice-hydro-fallback-by-default feature.  If we can take a shortcut to make that happen faster (i.e., the constructor arg; no setter), that's my vote.  The setter function can be an add-on, if we later find a need for it.
</blockquote></details>

However, if you main point was that this might not be a new `contact_mode` option but rather some kind of geometry-only option, that might be true.  I think it would probably still live in `MultibodyPlantConfig` at the top level, but how that gets plumbed down into the API might make more sense to go into SceneGraph directly.

**Review by rpoyner-tri — COMMENTED** [review]
The mods so far to ball_plate are fairly ridiculous (plate and ball fall down to infinity). I've kinda got the hydro-internal inferred rep going, but I've clearly broken something else (probably some compliance type usage elswhere). \cc @DamrongGuoy  if you have any insight into current brokenness.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-:-Nc4TCQs6hvjff4XwFty:b83yip5)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
`r4` mostly works against the deliberately dis-annotated ball-plate example. So we can regard it as the "minimum blast radius" estimate of changes. Of course, many things are still wrong with it:

* deliberate `const` flouting to write back discovered proximity properties
* arbitrary hard-coded default properties -- should be configurable, or at least public?
* defective geometry construction workflow as noted in ongoing discussions

Minor points:

* ContactModel (if we go that route) probably wants some helper predicates to help tame some of the splatter of finding and patching specific hard-coded predicates (perhaps `uses_hydroelastic_contact()`, `uses_point_contact()`?).
* obviously the current deliberate hobbling of ball_plate assets should be undone.
* usual caveats about missing doc and tests.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-:-Nc9JKbwBwV5nDgSNrwk:bc567f3)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
`r5` addresses a major (`const` flouting) problem, and a minor (`ContactModel` predicates) problem. Everything is else is still bad. Probably the workflow problem is what to address next -- may need a more complicated example.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-:-NcDuPNJB2dR0CKcpbpT:b-9eeywm)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/scene_graph.cc` line 376 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-NbHrxgl6DY5h7xmIAv3:-NcOSDcnDUqsSYmp4MIX:btuni9s) ([raw file](https://github.com/RobotLocomotion/drake/blob/349426f40e78dee9664f57cb59d824c0e7ed7f96/geometry/scene_graph.cc#L376)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

However, if you main point was that this might not be a new `contact_mode` option but rather some kind of geometry-only option, that might be true.  I think it would probably still live in `MultibodyPlantConfig` at the top level, but how that gets plumbed down into the API might make more sense to go into SceneGraph directly.
</blockquote></details>

Here is one kind of difficulty with the current sketch. Even if it's rarely done in practice, the expectation of `set_contact_model()` is that we could iteratively set different models on the same diagram/context and get more or less the same sim results for each run with a contact model. As currently hacked, the inferred model **destroys information** (the original, perhaps naive, results of model parsing or api construction), so we can't just switch to some other model and get its characteristic result afterward. 

I suppose we could treat hydro-inferred geometries as a distinct set at the lowest level (hydroelastic_internal's Geometries class), but I wonder if I'm missing a simpler plan.

\cc @SeanCurtis-TRI is you have time to consider hydro geometry metaphysics.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19956)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/scene_graph.cc` line 376 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19956#-NbHrxgl6DY5h7xmIAv3:-NcSyE5A8ECzT95R0nfu:bwtvj59) ([raw file](https://github.com/RobotLocomotion/drake/blob/349426f40e78dee9664f57cb59d824c0e7ed7f96/geometry/scene_graph.cc#L376)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Here is one kind of difficulty with the current sketch. Even if it's rarely done in practice, the expectation of `set_contact_model()` is that we could iteratively set different models on the same diagram/context and get more or less the same sim results for each run with a contact model. As currently hacked, the inferred model **destroys information** (the original, perhaps naive, results of model parsing or api construction), so we can't just switch to some other model and get its characteristic result afterward. 

I suppose we could treat hydro-inferred geometries as a distinct set at the lowest level (hydroelastic_internal's Geometries class), but I wonder if I'm missing a simpler plan.

\cc @SeanCurtis-TRI is you have time to consider hydro geometry metaphysics.
</blockquote></details>

My thought today (no code yet), is to just make "hydro inferred" a scene graph parameter, and drop all connection with ContactModel. Then I would have no real qualms about making it constructor-only, and would have no need to modify multibody code at all, except perhaps to pass through the new configuration data.

**Comment by rpoyner-tri** [comment]
Bailing on this approach. New attempt shortly.

**Comment by rpoyner-tri** [comment]
new attempt is up as a draft at #20059 .

**Pull request closed without merging**
