### PR TITLE
solvers: Improve documentation of available() vs enabled()

### LINKED ISSUE #15106: solvers: `MosekSolver::enabled()` binding appears to be broken
```
from pydrake.all import MosekSolver
solver = MosekSolver()
solver.enabled()
```
returns 
```
     30 solver = MosekSolver()
---> 31 solver.enabled()
     32 result = solver.Solve(prog)
     33 assert result.is_success()

AttributeError: 'pydrake.solvers.mosek.MosekSolver' object has no attribute 'enabled'
```

Per slack convo, it would also be good to add a note to the docstring for `available` to remind users that they might also need to check `enabled`.  Or better, if it's true that checking `enabled` also confirms `available`, then can we document that?

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Also improve error messages in case either of them are false.

Closes #15106.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15114)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.
+@RussTedrake for platform review, please.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15114#-:-Mb8Y4JJ8znH8ppiOaf1:bg7igkv)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
thanks!  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15114#-:-Mb9B-5X8XG3AfntlZzn:b-1bjpil)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @jwnimmer-tri)

___
*[solvers/solver_interface.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15114#-Mb99vkg9q4rr1utKbsm:-Mb99vkg9q4rr1utKbsn:b-rhwc2k) ([raw file](https://github.com/robotlocomotion/drake/blob/5d7bd19f1ae2bb5e7447fc6fd313ace9f4847063/solvers/solver_interface.h#L41)):*
> ```objc
>   /// or disabled at runtime (and which choice is the default when unspecified)
>   /// is specific to the solver in question, but typically uses an environment
>   /// variable.
> ```

i think most people won't understand why you would ever disable a solver at runtime.  Can we say something like "for example, we might disable a solver to avoid checking out a license from a license server"? 

I suspect most people who read this, though, will be doing it because they got an error message after trying to use a solver (e.g. Mosek), and are trying to debug why the solver doesn't work.  In my case this weekend, I had set up a new IDE and hadn't shared my license environment variable.  
___
*[solvers/solver_interface.h, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15114#-Mb99sZH8Dd-Ip6ipKY2:-Mb99sZH8Dd-Ip6ipKY3:b-2gjtww) ([raw file](https://github.com/robotlocomotion/drake/blob/5d7bd19f1ae2bb5e7447fc6fd313ace9f4847063/solvers/solver_interface.h#L46)):*
> ```objc
>   /// incorporated into Drake at compile-time (and has nothing to do with the
>   /// runtime configuration). A solver that has been disabled at compile time
>   /// (i.e., it is not available()) may still be configured to be available at
> ```

second "available" => "enabled"

**Comment by RussTedrake** [comment]
___
*[solvers/solver_interface.h, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15114#-Mb9B9OsA01sbI-6Fewn:-Mb9B9OsA01sbI-6Fewo:b1tiwyp) ([raw file](https://github.com/robotlocomotion/drake/blob/5d7bd19f1ae2bb5e7447fc6fd313ace9f4847063/solvers/solver_interface.h#L45)):*
> ```objc
>   /// Contrast this with available(), which reflects whether a solver has been
>   /// incorporated into Drake at compile-time (and has nothing to do with the
>   /// runtime configuration). A solver that has been disabled at compile time
> ```

nit: using "disabled" here is perhaps confusing.

**Comment by jwnimmer-tri** [comment]
Possibly a contributing factor here is that prior to #13279, when trying to solve the user would get an error message `Could not locate MOSEK license file because MOSEKLM_LICENSE_FILE environment variable was not set`.  Now, the error message is from `SolverBase` and only says `MosekSolver::is_enabled() is false; see its documentation for how to enable`, so does not directly mention the environment variable.  I'll take another pass at clarifications tomorrow.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15114)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[solvers/solver_interface.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15114#-Mb99vkg9q4rr1utKbsm:-MbgWObk8gAVzowGO24m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5d7bd19f1ae2bb5e7447fc6fd313ace9f4847063/solvers/solver_interface.h#L41)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i think most people won't understand why you would ever disable a solver at runtime.  Can we say something like "for example, we might disable a solver to avoid checking out a license from a license server"? 

I suspect most people who read this, though, will be doing it because they got an error message after trying to use a solver (e.g. Mosek), and are trying to debug why the solver doesn't work.  In my case this weekend, I had set up a new IDE and hadn't shared my license environment variable.  
</blockquote></details>

Done.
___
*[solvers/solver_interface.h, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15114#-Mb99sZH8Dd-Ip6ipKY2:-Mbg81tGBCqW9kJbq72Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5d7bd19f1ae2bb5e7447fc6fd313ace9f4847063/solvers/solver_interface.h#L46)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

second "available" => "enabled"
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15114)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  A big improvement.  thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15114#-:-Mbi7nAf5C4mAYJaCe2x:bxj69dc)* status: :shipit: complete! all discussions resolved, LGTM from assignees hongkai-dai,RussTedrake(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
