### PR TITLE
Compare LinearSolve result x with Eigen

### PR DESCRIPTION
**Pull request by hongkai-dai**
As explained in https://gitlab.com/libeigen/eigen/-/issues/2313. Eigen actually computed the right result when differentiating its solver Ax = b.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045#-:-Mngc_v60sPMU0rRPGgz:bkz6hi4)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16045#-MnlQ4jF5jEdkRQhB-W5:-MnlQ4jG3aPKHkpHIju6:b19zntv) (no related file):*
The test segfaults at r2 appear to be a bad combination of clang -O2 optimizer and the PartialPivLU solver with double-valued inputs. Injecting --copt=-O0 causes the test to pass; --copt=-O1 causes the test to fail with numeric tolerance errors. I haven't found any deeper cause yet.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16045#-MnlQ4jF5jEdkRQhB-W5:-MnlTHeK37o8CFN985mE:b-jkt8n) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

The test segfaults at r2 appear to be a bad combination of clang -O2 optimizer and the PartialPivLU solver with double-valued inputs. Injecting --copt=-O0 causes the test to pass; --copt=-O1 causes the test to fail with numeric tolerance errors. I haven't found any deeper cause yet.
</blockquote></details>

Hm, can't manage to repeat any failures with clang --copt=-O1, but segfaults at --copt=-O2 persist.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16045#-MnlQ4jF5jEdkRQhB-W5:-Mo01Fo_AKsD0C93_j0J:b-4i3k4z) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Hm, can't manage to repeat any failures with clang --copt=-O1, but segfaults at --copt=-O2 persist.
</blockquote></details>

Here is a patch that can isolate and suppress the symptom. I'm not really thinking it is a great idea. Maybe it will give us more insight into what is going wrong.

```diff --git a/math/test/linear_solve_test.cc b/math/test/linear_solve_test.cc
index ae8b5c3dc8..2ee1ee60ec 100644
--- a/math/test/linear_solve_test.cc
+++ b/math/test/linear_solve_test.cc
@@ -12,6 +12,14 @@ namespace drake {
 namespace math {
 namespace {
 
+// The clang optimizer breaks some code. This symbol can turn it off for the
+// scope of a function or lambda.
+#ifdef __clang__
+#define DRAKE_CLANG_OPTNONE __attribute__((optnone))
+#else
+#define DRAKE_CLANG_OPTNONE
+#endif
+
 template <template <typename, int...> typename LinearSolverType,
           typename DerivedA, typename DerivedB>
 typename std::enable_if<internal::is_autodiff_v<typename DerivedA::Scalar> ||
@@ -130,11 +138,20 @@ TestSolveLinearSystem(const Eigen::MatrixBase<DerivedA>& A,
       }
     } else if constexpr (std::is_same_v<typename DerivedA::Scalar, double> &&  // NOLINT
                          std::is_same_v<typename DerivedB::Scalar, double>) {
-      const auto x_eigen =
-          LinearSolverType<Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
-                                         DerivedA::ColsAtCompileTime>>(A)
-              .solve(b);
-      EXPECT_TRUE(CompareMatrices(x_eigen, x));
+      using MatrixType = Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
+                                       DerivedA::ColsAtCompileTime>;
+      using SolverType = LinearSolverType<MatrixType>;
+      using PplType = Eigen::PartialPivLU<MatrixType>;
+      if constexpr (std::is_same_v<SolverType, PplType>) {
+        auto no_opt = [&]() DRAKE_CLANG_OPTNONE {
+          const auto x_eigen = SolverType(A).solve(b);
+          EXPECT_TRUE(CompareMatrices(x_eigen, x));
+        };
+        no_opt();
+      } else {
+        const auto x_eigen = SolverType(A).solve(b);
+        EXPECT_TRUE(CompareMatrices(x_eigen, x));
+      }
     }
   }
 }
@@ -452,6 +469,8 @@ TEST_F(LinearSolveTest, GetLinearSolver) {
   CheckGetLinearSolver<Eigen::PartialPivLU>(A_ad_);
   CheckGetLinearSolver<Eigen::ColPivHouseholderQR>(A_ad_);
 }
+
+#undef DRAKE_CLANG_OPTNONE
 }  // namespace
 }  // namespace math
 }  // namespace drake

```

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16045#-MnlQ4jF5jEdkRQhB-W5:-Mo9fqZUC2kSIIp374WS:bws1ha5) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Here is a patch that can isolate and suppress the symptom. I'm not really thinking it is a great idea. Maybe it will give us more insight into what is going wrong.

```diff --git a/math/test/linear_solve_test.cc b/math/test/linear_solve_test.cc
index ae8b5c3dc8..2ee1ee60ec 100644
--- a/math/test/linear_solve_test.cc
+++ b/math/test/linear_solve_test.cc
@@ -12,6 +12,14 @@ namespace drake {
 namespace math {
 namespace {
 
+// The clang optimizer breaks some code. This symbol can turn it off for the
+// scope of a function or lambda.
+#ifdef __clang__
+#define DRAKE_CLANG_OPTNONE __attribute__((optnone))
+#else
+#define DRAKE_CLANG_OPTNONE
+#endif
+
 template <template <typename, int...> typename LinearSolverType,
           typename DerivedA, typename DerivedB>
 typename std::enable_if<internal::is_autodiff_v<typename DerivedA::Scalar> ||
@@ -130,11 +138,20 @@ TestSolveLinearSystem(const Eigen::MatrixBase<DerivedA>& A,
       }
     } else if constexpr (std::is_same_v<typename DerivedA::Scalar, double> &&  // NOLINT
                          std::is_same_v<typename DerivedB::Scalar, double>) {
-      const auto x_eigen =
-          LinearSolverType<Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
-                                         DerivedA::ColsAtCompileTime>>(A)
-              .solve(b);
-      EXPECT_TRUE(CompareMatrices(x_eigen, x));
+      using MatrixType = Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
+                                       DerivedA::ColsAtCompileTime>;
+      using SolverType = LinearSolverType<MatrixType>;
+      using PplType = Eigen::PartialPivLU<MatrixType>;
+      if constexpr (std::is_same_v<SolverType, PplType>) {
+        auto no_opt = [&]() DRAKE_CLANG_OPTNONE {
+          const auto x_eigen = SolverType(A).solve(b);
+          EXPECT_TRUE(CompareMatrices(x_eigen, x));
+        };
+        no_opt();
+      } else {
+        const auto x_eigen = SolverType(A).solve(b);
+        EXPECT_TRUE(CompareMatrices(x_eigen, x));
+      }
     }
   }
 }
@@ -452,6 +469,8 @@ TEST_F(LinearSolveTest, GetLinearSolver) {
   CheckGetLinearSolver<Eigen::PartialPivLU>(A_ad_);
   CheckGetLinearSolver<Eigen::ColPivHouseholderQR>(A_ad_);
 }
+
+#undef DRAKE_CLANG_OPTNONE
 }  // namespace
 }  // namespace math
 }  // namespace drake

```
</blockquote></details>

Having spent a bit more time trying to debug the optimizer failure (see for example https://llvm.org/docs/OptBisect.html), I'm convinced that test program as currently organized is not going to be stable. Either some functions or the or whole module seem to be "too big" for the clang optimizer to handle safely. I have some ideas to try for a reorganization -- will start on that today.

FWIW, the opt-bisect limit numbers have no stable meaning, but the sheer size of them surprised me. Experiments on this PR led to several phase boundaries at quite high numbers. Here's a paste from my notes:

```
We use --copt=-mllvm --copt=-opt-bisect-limit=<value> to find the offending pass.

correct: <= 381937
segfault: 381938+

complete-with-errors:500000-ish to 1096505
segfault: 1096506+
```

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16045#-MnlQ4jF5jEdkRQhB-W5:-MoGeTz4-mpfyTQnb-oX:bjqdc6d) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Having spent a bit more time trying to debug the optimizer failure (see for example https://llvm.org/docs/OptBisect.html), I'm convinced that test program as currently organized is not going to be stable. Either some functions or the or whole module seem to be "too big" for the clang optimizer to handle safely. I have some ideas to try for a reorganization -- will start on that today.

FWIW, the opt-bisect limit numbers have no stable meaning, but the sheer size of them surprised me. Experiments on this PR led to several phase boundaries at quite high numbers. Here's a paste from my notes:

```
We use --copt=-mllvm --copt=-opt-bisect-limit=<value> to find the offending pass.

correct: <= 381937
segfault: 381938+

complete-with-errors:500000-ish to 1096505
segfault: 1096506+
```
</blockquote></details>

Here's another patch that "fixes" the problem, this time without  coercing compiler settings:

```
diff --git a/math/test/linear_solve_test.cc b/math/test/linear_solve_test.cc
index ae8b5c3dc8..87efeb9191 100644
--- a/math/test/linear_solve_test.cc
+++ b/math/test/linear_solve_test.cc
@@ -18,6 +18,15 @@ typename std::enable_if<internal::is_autodiff_v<typename DerivedA::Scalar> ||
                         std::is_same_v<typename DerivedA::Scalar, double>>::type
 TestSolveLinearSystem(const Eigen::MatrixBase<DerivedA>& A,
                       const Eigen::MatrixBase<DerivedB>& b) {
+  Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
+                DerivedB::ColsAtCompileTime> x_eigen_d;
+  if constexpr (std::is_same_v<typename DerivedA::Scalar, double> &&
+                std::is_same_v<typename DerivedB::Scalar, double>) {
+    x_eigen_d = LinearSolverType<
+      Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
+                    DerivedA::ColsAtCompileTime>>(A)
+                .solve(b);
+  }
   for (const bool use_deprecated : {true, false}) {
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
@@ -130,11 +139,7 @@ TestSolveLinearSystem(const Eigen::MatrixBase<DerivedA>& A,
       }
     } else if constexpr (std::is_same_v<typename DerivedA::Scalar, double> &&  // NOLINT
                          std::is_same_v<typename DerivedB::Scalar, double>) {
-      const auto x_eigen =
-          LinearSolverType<Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
-                                         DerivedA::ColsAtCompileTime>>(A)
-              .solve(b);
-      EXPECT_TRUE(CompareMatrices(x_eigen, x));
+      EXPECT_TRUE(CompareMatrices(x_eigen_d, x));
     }
   }
 }
```

You might be moved to ask, "Why does this work?". Answer: I don't know. I do know that whatever optimizer badness happens is much more likely when the eigen double-valued solve and the matrix compare are directly in sequence. Bad hypothesis: the optimizer is more aggressive/effective on double-valued computations than on autodiff, and somehow it inlines and subsequently damages both the solve and the matrix comparison. The only solver that has this symptom is PartialPivLU (as before).

I'm not super happy with this, but I feel like we are dodging simultaneous bugs in Eigen and clang, and we may have to take what we can get.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16045#-MnlQ4jF5jEdkRQhB-W5:-MoZyUyu08lRbeV4aPHn:b-n1laeb) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Here's another patch that "fixes" the problem, this time without  coercing compiler settings:

```
diff --git a/math/test/linear_solve_test.cc b/math/test/linear_solve_test.cc
index ae8b5c3dc8..87efeb9191 100644
--- a/math/test/linear_solve_test.cc
+++ b/math/test/linear_solve_test.cc
@@ -18,6 +18,15 @@ typename std::enable_if<internal::is_autodiff_v<typename DerivedA::Scalar> ||
                         std::is_same_v<typename DerivedA::Scalar, double>>::type
 TestSolveLinearSystem(const Eigen::MatrixBase<DerivedA>& A,
                       const Eigen::MatrixBase<DerivedB>& b) {
+  Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
+                DerivedB::ColsAtCompileTime> x_eigen_d;
+  if constexpr (std::is_same_v<typename DerivedA::Scalar, double> &&
+                std::is_same_v<typename DerivedB::Scalar, double>) {
+    x_eigen_d = LinearSolverType<
+      Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
+                    DerivedA::ColsAtCompileTime>>(A)
+                .solve(b);
+  }
   for (const bool use_deprecated : {true, false}) {
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
@@ -130,11 +139,7 @@ TestSolveLinearSystem(const Eigen::MatrixBase<DerivedA>& A,
       }
     } else if constexpr (std::is_same_v<typename DerivedA::Scalar, double> &&  // NOLINT
                          std::is_same_v<typename DerivedB::Scalar, double>) {
-      const auto x_eigen =
-          LinearSolverType<Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
-                                         DerivedA::ColsAtCompileTime>>(A)
-              .solve(b);
-      EXPECT_TRUE(CompareMatrices(x_eigen, x));
+      EXPECT_TRUE(CompareMatrices(x_eigen_d, x));
     }
   }
 }
```

You might be moved to ask, "Why does this work?". Answer: I don't know. I do know that whatever optimizer badness happens is much more likely when the eigen double-valued solve and the matrix compare are directly in sequence. Bad hypothesis: the optimizer is more aggressive/effective on double-valued computations than on autodiff, and somehow it inlines and subsequently damages both the solve and the matrix comparison. The only solver that has this symptom is PartialPivLU (as before).

I'm not super happy with this, but I feel like we are dodging simultaneous bugs in Eigen and clang, and we may have to take what we can get.
</blockquote></details>

FWIW, I tried `--config ubsan` on this PR and my "fix" above. No errors were detected. I *think* that gives us justification to declare this an optimizer bug. Not sure what prizes we win.

---

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

___
*[math/test/linear_solve_test.cc, line 21 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16045#-Mo_693FAxXCqyoueo9w:-Mo_693FAxXCqyoueo9x:b2wqlaf) ([raw file](https://github.com/robotlocomotion/drake/blob/525929fc9ddbe43b90fa729f40a22ae0bf0c7446/math/test/linear_solve_test.cc#L21)):*
> ```cpp
> TestSolveLinearSystem(const Eigen::MatrixBase<DerivedA>& A,
>                       const Eigen::MatrixBase<DerivedB>& b) {
>   Eigen::Matrix<double, DerivedA::RowsAtCompileTime,
> ```

BTW it's probably a good idea to add a comment here explaining why (side-step clang optimizer problems) this solve is so far from its eventual use. On the plus side, we only solve it once (compared to twice inside the for loop). On the downside, it's maybe a bit less readable, and has to repeat some `if constexpr` goo.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045#-:-Mo_99mX2Dfkdy3HMMWp:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16045#-MnlQ4jF5jEdkRQhB-W5:-Mo_5uMO9SA5m8HYF8bs:b-6vykus) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

FWIW, I tried `--config ubsan` on this PR and my "fix" above. No errors were detected. I *think* that gives us justification to declare this an optimizer bug. Not sure what prizes we win.
</blockquote></details>

Thank you so much @rpoyner-tri for looking into this! I have no idea how much time you spent on finding this solution. I would like to salute to your effort.

---
___
*[math/test/linear_solve_test.cc, line 21 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16045#-Mo_693FAxXCqyoueo9w:-Mo_8mHt09jN9IXD6uDq:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/525929fc9ddbe43b90fa729f40a22ae0bf0c7446/math/test/linear_solve_test.cc#L21)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW it's probably a good idea to add a comment here explaining why (side-step clang optimizer problems) this solve is so far from its eventual use. On the plus side, we only solve it once (compared to twice inside the for loop). On the downside, it's maybe a bit less readable, and has to repeat some `if constexpr` goo.
</blockquote></details>

Done, good call.

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045#-:-Mo_AM7uA3xTTWqoxeLO:b-qsst0j)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16045#-MnlQ4jF5jEdkRQhB-W5:-Mo_H2pH5bsJ9ATCtvLA:b3otjbt) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thank you so much @rpoyner-tri for looking into this! I have no idea how much time you spent on finding this solution. I would like to salute to your effort.
</blockquote></details>

Glad to help; I'm focused on this code as well, from the cppad research side. Spent longer than I probably needed to, but maybe learned something as well.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045#-:-Mo_UHEv-K2NgBOnup1C:bmxilld)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16045#-MnlQ4jF5jEdkRQhB-W5:-Mo_SazS57uxY2kPX_NN:b-3m63r) (no related file):*
> I would like to salute to your effort.

Amen to that!

---
___
*[math/test/linear_solve_test.cc, line 131 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16045#-Mo_TJ2W3Vt4NnFvtxDv:-Mo_TJ2W3Vt4NnFvtxDw:blvtt42) ([raw file](https://github.com/robotlocomotion/drake/blob/8fd5edf9111dc480dbc87e10491a411c69b142bb/math/test/linear_solve_test.cc#L131)):*
> ```cpp
>                                     ExtractGradient(x.col(i)), tol));
>       }
>     } else if constexpr (std::is_same_v<typename DerivedA::Scalar, double> && // NOLINT
> ```

BTW This could also be:

`std::is_floating_point_v<typename DerivedA::Scalar>`

Probably not any shorter.  :) True, it allows for `float` and `long double`, but otherwise *very* native to what the C++ authors seemed to have in mind. Completely your tasted if you feel one is better than the other (for any arbitrary definition of "better" you like).

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045#-:-Mo_UJWY6mbtS2tAX7qx:b-safpmt)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@hongkai-dai I'll defer to you on how you want to curate the commits.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045#-:-Mo_UQDIEb9VTeOtu4Td:bdbhtl3)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16045)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[math/test/linear_solve_test.cc, line 131 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16045#-Mo_TJ2W3Vt4NnFvtxDv:-Mo_kvkLDj9vNf63a99h:blzh969) ([raw file](https://github.com/robotlocomotion/drake/blob/8fd5edf9111dc480dbc87e10491a411c69b142bb/math/test/linear_solve_test.cc#L131)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This could also be:

`std::is_floating_point_v<typename DerivedA::Scalar>`

Probably not any shorter.  :) True, it allows for `float` and `long double`, but otherwise *very* native to what the C++ authors seemed to have in mind. Completely your tasted if you feel one is better than the other (for any arbitrary definition of "better" you like).
</blockquote></details>

I would still use `std::is_same_v` version in this code, since we have used this check both in this file and `linear_solve.h`. I would like to keep them consistent.

**Pull request merged**
