### PR TITLE
[planning] Clean up ZMPPlanner

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Originally inspired by observed errors in doxygen formatting (erroneous comments in `@param foo, bar` led to incorrect documentation). However, the clean up expanded to the following:

1. Correct the doxygen formatting error.
2. Update doxygen to use the current practice of /** */ comments without leading * on each line.
3. References to other methods include terminal ().
4. Add `@pre` to functions that require `Plan()` to have been called.
5. Rename the class to conform with current standards.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18845)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: newly deprecated) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18845#-:-NOpo16G-wbmOYK6snkm:b-dngdyv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18845#-:-NOqBAwSCAh_BptXISbz:b-81zjv5)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@jwnimmer-tri for platform review please.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18845#-:-NOqQ_ed-HMKwN6Xbn-d:b-os5xp3)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform; -@jwnimmer-tri timed out.

**Review by sherm1 — COMMENTED** [review]
-@sherm1 +@EricCousineau-TRI per schedule please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18845#-:-NOqcRut8zO-yWwOqe6n:bazkv5m)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, thanks!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18845#-:-NOtDEq8CHll26tjQQeW:bhm0jc2)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @SeanCurtis-TRI)

**Pull request merged**
