### PR TITLE
[workspace] Upgrade rules_pkg to latest release 0.6.0

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Working towards #16481

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16485)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@jwnimmer-tri for feature review or reassignment, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16485#-:-MuspdAnEqPpUx4pngUM:b-oouro9)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri +(status: do not review) until CI is ready.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16485)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[tools/workspace/rules_pkg/repository.bzl, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16485#-MuxPgI58j-1EruG9uq7:-MuxPgI58j-1EruG9uq8:b-khbvs4) ([raw file](https://github.com/robotlocomotion/drake/blob/276ea7e29ee931ab27ebfb303a66ed63f9a18e42/tools/workspace/rules_pkg/repository.bzl#L14)):*
> ```Starlark
>         name = name,
>         repository = "bazelbuild/rules_pkg",  # License: Apache-2.0
>         extra_strip_prefix = "pkg",
> ```

Removing this line (extra_strip_prefix) seems like enough to get the build working again.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16485)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[tools/workspace/rules_pkg/repository.bzl, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16485#-MuxPgI58j-1EruG9uq7:-Mv-qoQR9Jw3FIhRc2Mh:bxguh3r) ([raw file](https://github.com/robotlocomotion/drake/blob/276ea7e29ee931ab27ebfb303a66ed63f9a18e42/tools/workspace/rules_pkg/repository.bzl#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Removing this line (extra_strip_prefix) seems like enough to get the build working again.
</blockquote></details>

Thanks for the suggestion, it is looking a lot happier now

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16485#-:-Mv-uViaCUFMjpMfw3Fb:b8qd208)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16485#-:-Mv-vPMN0WVoTRNJuYKm:b9krqcj)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @BetsyMcPhail)

**Pull request merged**
