### PR TITLE
[planning] Add CollisionCheckerContext

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18428)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@seancurtis-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18428#-:-NIssgvZADK6UmUkvkTU:bax1t9m)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

And now time to fishing for another platform reviewer.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18428#-:-NJ6SPs3BK36u_HjMXM_:buf0p30)* status: 1 unresolved discussion, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @rpoyner-tri)

___
*[`planning/collision_checker_context.h` line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18428#-NJ6RCFrBPPte4KE5ZAv:-NJ6RCFrBPPte4KE5ZAw:b-3ku3gj) ([raw file](https://github.com/robotlocomotion/drake/blob/84fe5f900fd5c4f92893a6689b4cc04450fa3a48/planning/collision_checker_context.h#L62)):*
> ```objc
>   const geometry::QueryObject<double>& GetQueryObject() const;
> 
>   // TODO(sean.curtis) Eliminate these public members that provide access to
> ```

nit; Now that we're in drake, I need you to change `sean.curtis` (my anzu identity) to `SeanCurtis-TRI` (my drake identity).

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18428#-:-NJCoj0l2zFq9yTDoiBM:bt1x5ma)* status: LGTM missing from assignee xuchenhan-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18428#-:-NJD3ugB6101Tn9ELWOV:bg7igkv)* status: 1 unresolved discussion, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @rpoyner-tri)

___
*[`planning/BUILD.bazel` line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18428#-NJD-zhnEsfzYxXzrk70:-NJD-zhnEsfzYxXzrk71:be4wapv) ([raw file](https://github.com/robotlocomotion/drake/blob/3442b8acce857bdf5353b9b3818af90a29a0a127/planning/BUILD.bazel#L31)):*
> ```Starlark
>     deps = [
>         ":robot_diagram",
>         "@drake//common:essential",
> ```

nit, this can now just be



_Suggestion:_
```Starlark
        "//common:essential",
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18428)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @rpoyner-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Sorry I forgot about this double commit PR and let another PR in before merging. Please rebase again, I'll hold up other PRs for now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18428#-:-NJGvuHe4ZdwfvbkXUVu:bmtoazr)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
rebased. now we play build-racer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18428#-:-NJH1fYxDjv59HbKLFEn:b43xwd9)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform), base commit is latest master (waiting on @rpoyner-tri)

**Pull request merged**
