### PR TITLE
Extract documentation for pydrake APIs from C++ headers

### PR DESCRIPTION
**Pull request by jamiesnape**
This is all the tooling that is necessary. Actual documentation will follow in later PR's.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9510)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review. FYI @RussTedrake.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by RussTedrake** [comment]
Hoorah!

A few questions:
What does python3 have to do with it?  Is mkdoc etc only in 3?
Is the tangible outcome of this (only) that i have docstrings available for multibody in the python console?

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
> What does python3 have to do with it? Is mkdoc etc only in 3?

Yes, the tool that extracts the docstrings is Python 3. The docstrings themselves are still inserted into Python 2 bindings.

> Is the tangible outcome of this (only) that i have docstrings available for multibody in the python console?

Yes, but I will PR something for Sphinx generation using the `sphinx.ext.autodoc` plugin next.

**Comment by RussTedrake** [comment]
Great.  Thank you!

**Comment by jamiesnape** [comment]
>  Or is this change on the critical path, because even if we don't feed these directly to mkdoc, they still need to function when transitively included by other headers?

I will again check, but it was last time I tried.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Still hitting `-Werror=unused-variable`, somewhat confusingly.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Looks like there is a bug with `#pragma GCC diagnostic push ... #pragma GCC diagnostic pop` on GCC just to add to the issues.

**Comment by EricCousineau-TRI** [comment]
@jamiesnape I think I've fixed both the `#pragma once` shenanigans, as well as sped things up (takes about 25s to generate all docstrings now, vs. minutes as it were before).

Will indicate the branch once I've cleaned it up; will also see see if this perhaps fixes the `#pragma ... push` stuff, since this fixes `#pramga once` too.

**Comment by jamiesnape** [comment]
You are going with a temporary source file rather than parsing the header?

**Comment by EricCousineau-TRI** [comment]
I make a temporary source file which `#include`s the other headers files; this reduces the need to re-parse each translation unit, and completely removes the need for any multithreading, as it's fast to just go through and parse everything.

Here's the branch:
https://github.com/jamiesnape/drake/compare/clang-cindex-python3-pydrake-multibody...EricCousineau-TRI:clang-cindex-python3-pydrake-multibody?expand=1

Specific `mkdoc` change:
https://github.com/jamiesnape/drake/commit/10f592dc29bb59e65284a5f1e010ea14df20b71c#diff-b291a2fd777a9ae84e3726d844d1af51

Doesn't workaround the `unused-variable` bug though :(

**Comment by EricCousineau-TRI** [comment]
For the `-Wunused-variable` shindig, perhaps we can just add `__attribute__(unused)`?
https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-unused-function-attribute

**Comment by jamiesnape** [comment]
Or we could switch that flag off just for pybind libraries on GCC and rely on Clang to catch issues.

**Comment by EricCousineau-TRI** [comment]
My preference is to keep on `unused` for other cases; the following seems simple and works:
https://github.com/jamiesnape/drake/commit/dbe3793dc9d931aafe7a1cbb7804c9afa8429171

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Formally +@jwnimmer-tri for a second feature review since @EricCousineau-TRI is now also a contributor to this PR.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
___
*[tools/workspace/pybind11/run_mkdoc_with_python3.py, line 1 at r8](https://reviewable.io/reviews/robotlocomotion/drake/9510#-LNHjNYb8oIMVykrm3Mm:-LNHjNYb8oIMVykrm3Mn:bcoeydh) ([raw file](https://github.com/robotlocomotion/drake/blob/9c2376eef263b1ada9ffb71db589cb3d3720d7ed/tools/workspace/pybind11/run_mkdoc_with_python3.py#L1)):*
> ```Python
> import os
> ```

Do we know that this is the best way to incorporate Python3 targets in a Python2 codebase?

If we're not sure, could we defer using Python3? (From looking at the code, it seems super easy to convert it to Python2, assuming it's easy to pull `clang-index` from `clang` itself:
https://github.com/llvm-mirror/clang/blob/master/bindings/python/clang/cindex.py

**Comment by EricCousineau-TRI** [comment]
FYI I'm cleaning up a bit more of `mkdoc.py` - just for making flow a little bit easier to trace, and adding line-based sorting.

**Comment by jamiesnape** [comment]
> FYI I'm cleaning up a bit more of mkdoc.py - just for making flow a little bit easier to trace, and adding line-based sorting.

Can you fix or suppress the lint issues too while you are working on it?

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/multibody/benchmarks_py.cc, line 21 at r13](https://reviewable.io/reviews/robotlocomotion/drake/9510#-LNL4KKc0vNBK3zLhbGh:-LNL4KKd9uStcjMqwOX-:buu91bf) ([raw file](https://github.com/robotlocomotion/drake/blob/f98b46e60894d35926d9500e756f9980612faa1a/bindings/pydrake/multibody/benchmarks_py.cc#L21)):*
> ```cpp
> void init_acrobot(py::module m) {
>   // NOLINTNEXTLINE(build/namespaces): Emulate placement in namespace.
>   using namespace drake::multibody::benchmarks::acrobot;
> ```

Here, we behave as-if we're already in `acrobot` namespace -- but the `DOC` macro above stops at `benchmarks`.  This seems inconsistent, but I guess the question is what is the habit we should use?

I guess in general, if we are going to use DOC macro pervasively in the bindings, then `bindings/pydrake/pydrake_pybind.h` must contain a tutorial-level description of how to apply this tool consistently throughout the bindings.

Not having yet read through all of the uses of DOC, my inclination is that the DOC definition should appear directly below this line, so that its easy to keep them in sync.

**Comment by jwnimmer-tri** [comment]
The file matrix is getting large.  Please everyone use "Combine commits for review" in your reviewable setting.  We can look at the curation later, but for now I think the "show push-to-push diffs" is what we need.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Ready for platform review now, I think.

**Comment by EricCousineau-TRI** [comment]
@jamiesnape I think `ibex` may be making `libclang` complain; when I build on my machine, I get the following printouts:
```
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:142:36: error: too few arguments provided to function-like macro invocation
/usr/include/x86_64-linux-gnu/sys/param.h:102:9: note: macro 'MIN' defined here
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:144:4: error: expected expression
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:152:36: error: too few arguments provided to function-like macro invocation
/usr/include/x86_64-linux-gnu/sys/param.h:103:9: note: macro 'MAX' defined here
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:544:18: error: too few arguments provided to function-like macro invocation
/usr/include/x86_64-linux-gnu/sys/param.h:103:9: note: macro 'MAX' defined here
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:578:19: error: too few arguments provided to function-like macro invocation
/usr/include/x86_64-linux-gnu/sys/param.h:103:9: note: macro 'MAX' defined here
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:304:12: error: use of undeclared identifier 'POS_INFTY'
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:544:14: error: use of undeclared identifier 'MAX'
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:559:12: error: use of undeclared identifier 'NEG_INFTY'
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:578:15: error: use of undeclared identifier 'MAX'
external/dreal/opt/libibex/2.6.5/include/ibex/3rd/ieee/primitive.hpp:593:12: error: use of undeclared identifier 'POS_INFTY'
```

I still get a file; however, on CI, it's failing?

\cc @soonho-tri

**Comment by soonho-tri** [comment]
@EricCousineau-TRI , I'll fix the issue and update ibex package.

**Comment by jwnimmer-tri** [comment]
I don't think its a bug in ibex or dreal.  I think `sys/param.h` is evil, and should not be (transitively) included.

**Comment by soonho-tri** [comment]
> I think sys/param.h is evil, and should not be (transitively) included.

I agree. But I'm not sure how easy/difficult to exclude this header.

ibex depends on an interval package, [filib++](http://www2.math.uni-wuppertal.de/~xsc/software/filib.html). It provides a class which has member function `MAX`/`MIN`. https://github.com/dreal-deps/filibxx/blob/master/ieee/primitive.hpp#L152-L155
I'm checking if I can rename them safely (without breaking ibex and dReal).

**Comment by jamiesnape** [comment]
The workaround for now is to exclude more of the targets for now to avoid the transitive dependency on dreal. The previous list was curated to be the minimal set needed to get all the headers for the current Python bindings (aside: we are missing a handful of headers from examples now).

**Comment by EricCousineau-TRI** [comment]
Will revert; for future PRs, we just need to pull from @jamiesnape's original list:
```
    targets = [
        "//attic/multibody:approximate_ik",
        "//attic/multibody:inverse_kinematics",
        "//attic/multibody:rigid_body_actuator",
        "//attic/multibody:rigid_body_tree_construction",
        "//attic/multibody:rigid_body_tree",
        "//attic/multibody:rigid_body",
        "//attic/multibody/collision",
        "//attic/multibody/joints",
        "//attic/multibody/parsers",
        "//attic/multibody/rigid_body_plant:drake_visualizer",
        "//attic/multibody/rigid_body_plant",
        "//attic/multibody/shapes",
        "//automotive",
        "//automotive/maliput/api",
        "//automotive/maliput/dragway",
        "//common",
        "//common/trajectories",
        "//examples/acrobot:acrobot_plant",
        "//examples/compass_gait",
        "//examples/pendulum:pendulum_plant",
        "//examples/rimless_wheel",
        "//examples/van_der_pol",
        "//geometry",
        "//lcm",
        "//manipulation/planner",
        "//math",
        "//multibody/benchmarks/acrobot",
        "//multibody/inverse_kinematics",
        "//multibody/multibody_tree",
        "//multibody/multibody_tree/math",
        "//multibody/multibody_tree/multibody_plant",
        "//multibody/multibody_tree/parsing",
        "//solvers",
        "//systems/analysis",
        "//systems/controllers",
        "//systems/framework",
        "//systems/lcm",
        "//systems/primitives",
        "//systems/rendering",
        "//systems/sensors",
        "//systems/trajectory_optimization",
    ],
```

**Comment by jwnimmer-tri** [comment]
So to keep the File Matrix under control in the future, the lesson from the reviewable issue cited above is to either (1) have a single, homogeneous author for all commits in a PR, or (2) don't rebase multi-author PRs -- instead push single `fixup! Original commit message` additional commits incrementally, and then squash them at the end prior to hitting master.  Pushing rebases with multiple authors will always bloat the file matrix.

**Comment by EricCousineau-TRI** [comment]
Er... Seems that just using `//:drake_shared_library` in the generation target works just fine at present, with or without resolution of #9530 via #9539...

**Comment by jamiesnape** [comment]
Latest revision just removes the `[[gnu::unused]]` from the commit message, no code changes.

**Pull request merged**
