### PR TITLE
Replace T=int with T=double in various framework tests.

### LINKED ISSUE #4658: Stop implying support for ScalarType = int
Some of our `systems/framework` code (and more?) implies support for using a `ScalarType` of `int`, due to its unit tests or otherwise.  We don't want to support `int`, because it mostly doesn't make sense for our framework.

We should replace that code (whose purpose is often to test a variety of types) with a different type that better represents what we actually want to support.

Note that integer parameters and such are actually supported (as abstract values) and should remain so -- we just shouldn't use `int` directly as a `ScalarType`.

Related: #4652 and #4657.

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #4658.

@sammy-tri for all review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5733)

### CODE REVIEW

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/subvector_test.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5733#-Kgzl5qA4_sM2ubpGk5L:-Kgzl5qB-x_SkElNLoX3:b-bjhxvw) ([raw file](https://github.com/robotlocomotion/drake/blob/a75ee51bd1a7509758dbac40005409751a5e9e53/drake/systems/framework/test/subvector_test.cc#L112)):*
> ```cpp
>   Eigen::Vector2d expected;
>   expected << 102, 1003;
>   EXPECT_EQ(expected, target);
> ```

BTW there's a lot of EXPECT_EQ in this test which is now looking at the results of floating point operations...   though if CI doesn't mind, I suppose I don't.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5733#-:-Kgzm84cYYpfg74pP4S5:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5733)*

**Comment by david-german-tri** [comment]
The integers are small enough :)

http://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5733#-:-Kgzma5eK03jiFcdjnAf:bdht7qu)*

**Comment by david-german-tri** [comment]
Merging without waiting for MATLAB CI.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5733#-:-Kgzmk2YX2BFHmz-2tj5:b-o85int)*

**Pull request merged**
