### PR TITLE
moves model_name out of RigidBody and into RigidBodyTree

### LINKED ISSUE #3088: Modify RigidBodyTree to Assign World Body a Model Instance ID of Zero
# Motivation

The "world" is a distinct model instance. It should not be considered part of any other model in the `RigidBodyTree`. It currently assumes a model instance ID of zero, which is the same as the first non-world model that is added to the `RigidBodyTree`. Ideally, the first non-world model added to the `RigidBodyTree` should have a model instance ID of 1.
# How?

Modify the constructor of `RigidBodyTree` to set the model instance ID of the `RigidBody` representing the world using the following code:

```
b->set_model_instance_id(add_model_instance());
```

The above change was done in the following commit, but it was later reverted (see next section).

https://github.com/liangfok/drake/commit/a06dc46c17a33756746f610482962bf896c83978#diff-ee5d6cc174ba2facc00f41699e58eab6R82

Here is the actual revert commit: https://github.com/liangfok/drake/commit/8ff1bf85183e1cb7c9094dfb24d3788015089c44
# Why Wasn't the Above Change Merged Into Master Already?

For some reason, setting the world to have its own model instance ID [broke some unit tests](https://drake-jenkins.csail.mit.edu/job/experimental/3454/). One example is:

```
$ ctest -VV -R testIKMoreConstraints
...
153: Restoration phase is called at point that is almost feasible,
153:   with constraint violation 2.220446e-16. Abort.
153: x = -0.026      0  0.844      0      0      0      0      0      0   0.27      0  0.055  -0.57   1.13  -0.55 -0.055  -1.33  2.153    0.5 0.0985      0 0.0008  -0.27      0 -0.055  -0.57   1.13  -0.55  0.055   1.33  2.153   -0.5 0.0985      0 0.0008 0.2564
153: qsc = 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125
153: info = 100
153: /home/liang/dev/drake_catkin_workspace/src/drake/drake/systems/plants/test/testIKMoreConstraints.cpp:189: Failure
153:       Expected: info
153:       Which is: 100
153: To be equal to: 1
153: 0.000000
153: 0.000000
153: 0.000000
153: /home/liang/dev/drake_catkin_workspace/src/drake/drake/systems/plants/test/testIKMoreConstraints.cpp:198: Failure
153: Value of: CompareMatrices(com, Vector3d(0.074890, -0.037551, 1.008913), 1e-4, MatrixCompareType::absolute)
153:   Actual: false
153: Expected: true
153: [  FAILED  ] testIKMoreConstraints.IKMoreConstraints (99 ms)
```

### PR DESCRIPTION
**Pull request by RussTedrake**
(where it belongs).

related to #3053
resolves #3088

unfortunately contains a lot of clang-format changes, in addition to the few essential changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4492)

### CODE REVIEW

**Comment by liangfok** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/rigid_body_tree.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4492#-KYx43K3LweFY1pfNlGf:-KYx0mIsAsC89qO_kP1f:bko3lro) ([raw file](https://github.com/robotlocomotion/drake/blob/cbee242fcad84e953bf5a485ad2102dbdbb921d5/drake/multibody/rigid_body_tree.cc#L115)):*
> ```cpp
>   std::unique_ptr<RigidBody<T>> world_body(new RigidBody<T>());
>   world_body->set_name(RigidBodyTree<T>::kWorldName);
>   world_body->set_model_instance_id(0);
> ```

BTW, consider combining the above two changes as follows:

```
world_body->set_model_instance_id(add_model_instance(
    world_body->get_name());
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4492)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/multibody/parser_urdf.cc, line 435 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4492#-KYxqTkXDthb7vuU1c0O:-KYxqTkXDthb7vuU1c0P:b-qlfomc) ([raw file](https://github.com/robotlocomotion/drake/blob/7410382aa4d338f93b0d1804c747118b8e8ef518/drake/multibody/parser_urdf.cc#L435)):*
> ```cpp
>           << std::endl
>           << "  - model name: "
>           << tree->get_model_name(body->get_model_instance_id()) << std::endl
> ```

BTW Would it make sense to provide a utility method such as `RigidBodyTree:get_model_name(const RigidBody* body)`?  It would make code that needs to extract model name from bodies easier to read.  This crops up a number of places.

---

*[drake/multibody/rigid_body.cc, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4492#-KYxptPBsfYaUVgujNWN:-KYxptPBsfYaUVgujNWO:b-88edi0) ([raw file](https://github.com/robotlocomotion/drake/blob/7410382aa4d338f93b0d1804c747118b8e8ef518/drake/multibody/rigid_body.cc#L58)):*
> ```cpp
>     throw runtime_error("ERROR: RigidBody<T>::getJoint(): Rigid body \"" +
>                         name_ + "\" in model " +
>                         std::to_string(model_instance_id_) +
> ```

BTW Is there a concern about the loss of functionality?  The old message printed a model name -- something a human could ostensibly understand.  Now it's being replaced with an encoded model id.  It weakens the value of this particular exception message.  Does it weaken it too much?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4492)*

**Comment by liangfok** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/multibody/rigid_body.cc, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4492#-KYxptPBsfYaUVgujNWN:-KYxs7xAeuW9ny4tslF0:b-8ltpbv) ([raw file](https://github.com/robotlocomotion/drake/blob/7410382aa4d338f93b0d1804c747118b8e8ef518/drake/multibody/rigid_body.cc#L58)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is there a concern about the loss of functionality?  The old message printed a model name -- something a human could ostensibly understand.  Now it's being replaced with an encoded model id.  It weakens the value of this particular exception message.  Does it weaken it too much?
</blockquote></details>

Since there may be multiple instances of the same model in the `RigidBodyTree`, we'll need to include the `model_instance_id_` to distinguish between them. Thus, I suggest that this error message concatenate the model name with the model instance ID.

To get the model name, we'll need to save it as a member variable within `RigidBody`, which this PR removes.

Maybe the model name can be passed as an input parameter to `RigidBody`'s constructor, which is then saved as a member variable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4492)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/multibody/rigid_body.cc, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4492#-KYxptPBsfYaUVgujNWN:-KYxuYXuOAoe9pM_C4mQ:b-76hw7) ([raw file](https://github.com/robotlocomotion/drake/blob/7410382aa4d338f93b0d1804c747118b8e8ef518/drake/multibody/rigid_body.cc#L58)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Since there may be multiple instances of the same model in the `RigidBodyTree`, we'll need to include the `model_instance_id_` to distinguish between them. Thus, I suggest that this error message concatenate the model name with the model instance ID.

To get the model name, we'll need to save it as a member variable within `RigidBody`, which this PR removes.

Maybe the model name can be passed as an input parameter to `RigidBody`'s constructor, which is then saved as a member variable?
</blockquote></details>

btw I'm aware of all of those points.  I was just pointing out one of the costs we are paying in this change, viz, a loss of clarity of this message.  So, we either need to decide we're fine with it or do something about it.  I was just worried that we were, perhaps, not explicitly making that decision.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4492)*

**Comment by liangfok** [comment]
*[drake/multibody/rigid_body.cc, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4492#-KYxptPBsfYaUVgujNWN:-KYy1bqXj0vcsPtY-Ytf:bb04ssn) ([raw file](https://github.com/robotlocomotion/drake/blob/7410382aa4d338f93b0d1804c747118b8e8ef518/drake/multibody/rigid_body.cc#L58)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw I'm aware of all of those points.  I was just pointing out one of the costs we are paying in this change, viz, a loss of clarity of this message.  So, we either need to decide we're fine with it or do something about it.  I was just worried that we were, perhaps, not explicitly making that decision.
</blockquote></details>

You raised a valid concern. I think from a user experience perspective, it would be better to provide both the model name and instance ID in the error message. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4492)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by jwnimmer-tri** [comment]
@RussTedrake  This has conflicts and no updates since 3+ weeks.  Should it be closed?

**Pull request closed without merging**
