### PR TITLE
[workspace] Upgrade curl_internal to latest release curl-8_7_1

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #21211

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21265)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I think this one might be a simple fix.  In `drake/tools/workspace/nlohmann_internal/package.BUILD.bazel` the hdrs should list both `json.hpp` and json_fwd.hpp`.

**Comment by jwnimmer-tri** [comment]
Sorry, posted in the wrong PR.

**Comment by jwnimmer-tri** [comment]
I can look at this next week, but not this week.

The solution tactic is to take the files that CI is complaining about and add them to either `_SRCS` (like `lib/altsvc.c`) or `glob_exclude` (like `lib/amigaos.c`).  Putting them in "exclude" is better, if it works (saves build time).

**Review by rpoyner-tri — COMMENTED** [review]
I've got a patch to offer.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21265#-:-Nv2pQMW0UkP7inz07R0:bjnvsla)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
The build failures look very strange to me. Maybe flukes?
```
[1:15:25 PM]  ERROR: /media/ephemeral0/ubuntu/workspace/linux-jammy-clang-bazel-experimental-leak-sanitizer/src/geometry/optimization/BUILD.bazel:201:17: Compiling geometry/optimization/iris_internal.cc failed: unable to finalize action: Missing digest: 217471cfcf071dcfe38ba9ecd3654629091f81d78fdd6f42a52c289a8e67792f/76462 for bazel-out/k8-dbg/bin/geometry/optimization/_objs/iris_internal/iris_internal.pic.d
```
Similar messages in both failed builds, on apparently random object files.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21265#-:-Nv32VGW9YwktVX5ZNGW:b-7p9z02)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @BetsyMcPhail)

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-leak-sanitizer please.

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: feature) 
+@jwnimmer-tri for at least one review, role of your choice, since I'm now a co-author.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21265#-:-Nv34lL09jxhU3fvvVif:b-rfu0in)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21265#-:-Nv35uTb4s7xUHeRgX5l:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Pull request merged**
