### PR TITLE
Add power function to Polynomial class

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4816)

### CODE REVIEW

**Comment by soonho-tri** [comment]
I need this for https://github.com/RobotLocomotion/drake/issues/4755.

**Comment by soonho-tri** [comment]
+@ggould-tri , could you do feature-review this?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-:-Kamz0hEcBUiHA16N0bF:b-n9bn2x)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/polynomial.h, line 471 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-Kan0F8ZsaeMsOVT_N_H:-Kan0F8_dTZMZv3QXLzd:b-ux2f9k) ([raw file](https://github.com/robotlocomotion/drake/blob/c4843b6359c385e1966eff9841d5a02001e6cb93/drake/common/polynomial.h#L471)):*
> ```objc
> Polynomial<CoefficientType> pow(
>     const Polynomial<CoefficientType>& p,
>     typename Polynomial<CoefficientType>::PowerType n) {
> ```

How does it work for negative `n`? The PowerType is `int`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/polynomial.h, line 471 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-Kan0F8ZsaeMsOVT_N_H:-Kan1ahstvw7yeZroOvd:b-hohuge) ([raw file](https://github.com/robotlocomotion/drake/blob/c4843b6359c385e1966eff9841d5a02001e6cb93/drake/common/polynomial.h#L471)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

How does it work for negative `n`? The PowerType is `int`.
</blockquote></details>

It only works if `n` is non-negative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/polynomial.h, line 471 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-Kan0F8ZsaeMsOVT_N_H:-Kan1kF_9xHpk-nQ70ke:bqghbnw) ([raw file](https://github.com/robotlocomotion/drake/blob/c4843b6359c385e1966eff9841d5a02001e6cb93/drake/common/polynomial.h#L471)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

It only works if `n` is non-negative.
</blockquote></details>

Better change the below `DRAKE_ASSERT` to `DRAKE_DEMAND`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/polynomial.h, line 471 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-Kan0F8ZsaeMsOVT_N_H:-Kan1rckO-eUur7-3iAH:b-4cnqp) ([raw file](https://github.com/robotlocomotion/drake/blob/c4843b6359c385e1966eff9841d5a02001e6cb93/drake/common/polynomial.h#L471)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Better change the below `DRAKE_ASSERT` to `DRAKE_DEMAND`?
</blockquote></details>

Yes, DRAKE_DEMAND sounds better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/polynomial.h, line 471 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-Kan0F8ZsaeMsOVT_N_H:-Kan246Q37Z3GWjIJkXl:b4tv7de) ([raw file](https://github.com/robotlocomotion/drake/blob/c4843b6359c385e1966eff9841d5a02001e6cb93/drake/common/polynomial.h#L471)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes, DRAKE_DEMAND sounds better.
</blockquote></details>

Sorry I was not pointing to this PR, but I was just surprised that we set `PowerType` to be `int` instead of `unsigned int`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[drake/common/polynomial.h, line 471 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-Kan0F8ZsaeMsOVT_N_H:-Kan6MdD7p_wbkjgH8Xb:b-g9d9hx) ([raw file](https://github.com/robotlocomotion/drake/blob/c4843b6359c385e1966eff9841d5a02001e6cb93/drake/common/polynomial.h#L471)):*
Done.

> but I was just surprised that we set PowerType to be int instead of unsigned int.

Our style guide, http://drake.mit.edu/code_style_guide.html, does not allow us to use `unsigned int` in general.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by soonho-tri** [comment]
@hongkai-dai , since you're here anyway. Could you do feature-review this?

-@ggould-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-:-Kan6tNllZsfDOgwUZxK:b6zw6r3)*

**Comment by soonho-tri** [comment]
forget '+' sign.. +@hongkai-dai 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-:-Kan717bwl7sBV1MY-AU:br8ufp7)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/polynomial_test.cc, line 100 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-Kan8DaAqlpz8cZtB4oc:-Kan8DaAqlpz8cZtB4od:b-urgl0x) ([raw file](https://github.com/robotlocomotion/drake/blob/fb490cba8bae97c469e8c9a36178251751a3f55e/drake/common/test/polynomial_test.cc#L100)):*
> ```cpp
>                 poly1.EvaluateUnivariate(t) * poly1.EvaluateUnivariate(t),
>                 1e-8);
>     EXPECT_NEAR(pow_poly1_3.EvaluateUnivariate(t),
> ```

This test is for univariate polynomial, could you add the tests for multiple variables also?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by ggould-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/polynomial.h, line 484 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-KanB0HcFmONydOWEtAV:-KanB0HcFmONydOWEtAW:b-d67qe7) ([raw file](https://github.com/robotlocomotion/drake/blob/fb490cba8bae97c469e8c9a36178251751a3f55e/drake/common/polynomial.h#L484)):*
> ```objc
>     return p_half * p_half;  // Even n case.
>   }
> }
> ```

BTW -- Might this same method apply to the repeated-multiplication implementation of pow() immediately above it?  It would be nice if they could be combined, or at least made to agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/polynomial.h, line 484 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-KanB0HcFmONydOWEtAV:-KanBgPuaEoA-2wLDGqt:bhafbq) ([raw file](https://github.com/robotlocomotion/drake/blob/fb490cba8bae97c469e8c9a36178251751a3f55e/drake/common/polynomial.h#L484)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- Might this same method apply to the repeated-multiplication implementation of pow() immediately above it?  It would be nice if they could be combined, or at least made to agree.
</blockquote></details>

How's this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/polynomial_test.cc, line 100 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-Kan8DaAqlpz8cZtB4oc:-KanEX_uB_fiLR6lT9R0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb490cba8bae97c469e8c9a36178251751a3f55e/drake/common/test/polynomial_test.cc#L100)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This test is for univariate polynomial, could you add the tests for multiple variables also?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by soonho-tri** [comment]
+@ggould-tri, platform-review please?

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-:-KanE_mKlOShpxc7pIgN:b9ohefx)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/polynomial.h, line 459 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-KanEhCpHn01YgtqsTmK:-KanEhCpHn01YgtqsTmL:b-qk2pw6) ([raw file](https://github.com/robotlocomotion/drake/blob/123bb800ea80d7b9d1cd2add50c617a1517ca415/drake/common/polynomial.h#L459)):*
> ```objc
>   template <typename Base>
>   static Base Pow(const Base& base, const PowerType& exponent) {
>     DRAKE_DEMAND(exponent >= 0);
> ```

@ggould-tri , do we need this restriction here, or do you want me to move it to the below, non-member `pow` function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by ggould-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/polynomial.h, line 484 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-KanB0HcFmONydOWEtAV:-KanEekffEhpIDB-2_B1:b-83sjoh) ([raw file](https://github.com/robotlocomotion/drake/blob/fb490cba8bae97c469e8c9a36178251751a3f55e/drake/common/polynomial.h#L484)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

How's this change?
</blockquote></details>

Nice!

---

*[drake/common/polynomial.h, line 459 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-KanEhCpHn01YgtqsTmK:-KanEtY1PQGHlw2Xl9El:b-3mww02) ([raw file](https://github.com/robotlocomotion/drake/blob/123bb800ea80d7b9d1cd2add50c617a1517ca415/drake/common/polynomial.h#L459)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@ggould-tri , do we need this restriction here, or do you want me to move it to the below, non-member `pow` function?
</blockquote></details>

This local Pow was, iirc, only used by `EvaluateUnivariate`, and the exponents are documented (but possibly not well enforced) to be positive integers.  If you can prove that no monomial will ever have negative exponent, it can be removed entirely; if not, it probably has to stay here to ensure that `EvaluateUnivariate` remains safe.

(This file is a mix of legacy and newer code, and the legacy code was super sloppy about invariants, so you really need to prove through to a previous assertion to be sure of anything)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/polynomial.h, line 459 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-KanEhCpHn01YgtqsTmK:-KanGZuc0BF_QUbEPXj6:bneke6m) ([raw file](https://github.com/robotlocomotion/drake/blob/123bb800ea80d7b9d1cd2add50c617a1517ca415/drake/common/polynomial.h#L459)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This local Pow was, iirc, only used by `EvaluateUnivariate`, and the exponents are documented (but possibly not well enforced) to be positive integers.  If you can prove that no monomial will ever have negative exponent, it can be removed entirely; if not, it probably has to stay here to ensure that `EvaluateUnivariate` remains safe.

(This file is a mix of legacy and newer code, and the legacy code was super sloppy about invariants, so you really need to prove through to a previous assertion to be sure of anything)
</blockquote></details>

I'd change it to `DRAKE_ASSERT`. @hongkai-dai , what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/polynomial.h, line 459 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-KanEhCpHn01YgtqsTmK:-KanGnH4-ZZ5kSHxtGYC:bayh8rh) ([raw file](https://github.com/robotlocomotion/drake/blob/123bb800ea80d7b9d1cd2add50c617a1517ca415/drake/common/polynomial.h#L459)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'd change it to `DRAKE_ASSERT`. @hongkai-dai , what do you think?
</blockquote></details>

Hmm... never mind. Let's keep it as it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816)*

**Comment by ggould-tri** [comment]
Heh, I guess I asked for that.  :lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-:-KanGeXoC0Qao-sb90S8:bf2wrj7)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4816#-:-KanOT3kZcZ109ngaHz7:bnfp4nl)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Pull request merged**
