### PR TITLE
Update drake-visualizer and vtk pre-compiled binaries

### LINKED ISSUE #7740: "Illegal instruction (core dumped)" when running drake_visualizer
$ bazel build //tools:drake_visualizer
INFO: Analysed target //tools:drake_visualizer (0 packages loaded).
INFO: Found 1 target...
Target //tools:drake_visualizer up-to-date:
  bazel-bin/tools/drake_visualizer
INFO: Elapsed time: 1.000s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

$ bazel-bin/tools/drake_visualizer
Illegal instruction (core dumped)

I also had to manually install lcm

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #7740.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7851)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
This PR would also get us the RobotLocomotion/director#562 fix, which recently bit us when working with the `drake/multibody/rigid_body_plant/visualization/contact_viz.py` script; that script doesn't work when using the current `//tools:drake_visualizer`.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang mac-highsierra-clang-bazel-experimental please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@kunimatsu-tri and +@soonho-tri for feature review.

**Comment by soonho-tri** [comment]
:lgtm: also checked that I can build the changed targets on Mac.

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7851#-L75Cf3P8ntFp-ROgdBB:-L75Cf3P8ntFp-ROgdBC:b5n9gmn) ([raw file](https://github.com/robotlocomotion/drake/blob/612e4a2f08ff4db503558890e18e0c1f29078c4d/systems/sensors/rgbd_renderer_vtk.cc#L127)):*
> ```cpp
>   // NOLINTNEXTLINE(runtime/int): To match pre-existing APIs.
>   void Execute(vtkObject*, unsigned long, void* callback_object) VTK_OVERRIDE {
>     vtkShaderProgram* program =
> ```

@kunimatsu-tri , could you check if these changes are due to the upgrade from `vtk-8.0` to `vtk-8.1` or because of something else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7851#-:-L75DElH7838GZDMn-cA:bl8ma0o)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

This might fix #7908 as well.

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7851#-L75Cf3P8ntFp-ROgdBB:-L75FOnjOowCm_jrqxpV:b-jbes4t) ([raw file](https://github.com/robotlocomotion/drake/blob/612e4a2f08ff4db503558890e18e0c1f29078c4d/systems/sensors/rgbd_renderer_vtk.cc#L127)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@kunimatsu-tri , could you check if these changes are due to the upgrade from `vtk-8.0` to `vtk-8.1` or because of something else?
</blockquote></details>

Yes, this is due to the upgrade and looks correct to me.

FYI, the change happens here: https://github.com/Kitware/VTK/commit/41d80c542269995033a5b76271719e29d264a188

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7851#-:-L75I6D7a6PazvDW2aZr:b-8jf8ye)*

**Pull request merged**
