### PR TITLE
install: Add drake_bazel_installed support

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In support of https://github.com/RobotLocomotion/drake-external-examples/pull/152.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12402)

### CODE REVIEW

**Comment by jamiesnape** [comment]
I know this a rough draft, so ignore me, if necessary.

* I wonder if it would really be a problem create symlinks in advance and remove the need for any sort of loader. We already create symlinks for other reasons in the install tree. 

* We know exactly which files are in our install tree, so we can minimize globs (a good thing since the user could chose an arbitrary prefix which may contain other headers and libraries). 

* Alternatively, if we require the user use a clean prefix (which in practical terms is almost the case now due to potentially conflicting headers) then maybe we may as well put the bazel files at the prefix itself and have no symlinks.

**Comment by jwnimmer-tri** [comment]
I did attempt symlinks instead of a loader, but it doesn't work -- we need to have the `@drake` repository root at `prefix/share/drake` so that runfiles paths resolve correctly, but we can't symlink out of there to get to the `lib` folder.

I guess we could `prefix/common -> prefix/share/drake/common` (+ etc for every top-level package) but that seems like quite the pollution of the prefix.

**Comment by jamiesnape** [comment]
Runfiles paths? Not sure I follow. Maybe I was just lucky on Mac. I guess I will wait for the final version.

**Comment by jwnimmer-tri** [comment]
We need `Rlocation("drake/examples/pendulum/Pendulum.urdf")` to resolve to the correct file, so for a loader-less `local_repository(path = ...)` we would need `path` to be either (1) `prefix/share/drake`, or (2) `prefix/something` with a symlink `prefix/something/examples -> prefix/share/drake/examples`.

We also need the `lib` items to be available, so we need `prefix/lib/**` also available.

The `local_repository` does not traverse symlinks that reach outside of its children.  Since we need both share and lib, the WORKSPACE would have to be `prefix/WORKSPACE` (so "something" above is "."), and we have
```
prefix/WORKSPACE
prefix/examples -> prefix/share/drake/examples
...
```
which seems like an abuse of the prefix concept.

**Comment by jamiesnape** [comment]
So a Drake limitation related to finding resources. Regardless, you are right, we definitely should not symlinking all those files into the prefix.

**Comment by jwnimmer-tri** [comment]
Other than need a boatload more documentation, I think this PR + the `drake-external-examples` PR are about ready.

**Comment by jwnimmer-tri** [comment]
I removed the globs (generating a manifest at built-time instead), and added some documentation.  This should be readyish for review now.

**Comment by jwnimmer-tri** [comment]
We will need a volunteer to start review on this, @jamiesnape or @EricCousineau-TRI or ...?

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI PTAL at recent changes and currently blocking discussions.

**Pull request merged**
