### PR TITLE
Switches back to upstream VTK5 and adds injection GLX_GLXEXT_LEGACY flag.

### PR DESCRIPTION
**Pull request by liangfok**
Forward-fixes a defect introduced in #4901.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4930)

### CODE REVIEW

**Comment by liangfok** [comment]
I just confirmed that this works on an Ubuntu 16.04 + ROS Kinetic system.

+@jwnimmer-tri for both levels of review please. Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4930#-:-KbTPDvB7Lfpz09JoNj7:bfy8m7v)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4930#-:-KbUngiZwxS-Np62PmI6:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by liangfok** [comment]
Oh no! I just realized that @jwnimmer-tri asked Jenkins to do a `mac-clang-experimental` build. Oops.

**Comment by liangfok** [comment]
Here is the status if the still-running build: https://drake-jenkins.csail.mit.edu/job/mac-clang-experimental/321/. Since this PR is already merged, I'll keep an eye on it and revert if it detects a problem.

**Comment by liangfok** [comment]
Nevermind. The above build was aborted b/c I merged this PR. Looks like the best I can do now is monitor the mac builds in [continuous production](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/) to see if any turn yellow / red.

**Pull request merged**
