### PR TITLE
[C-IRIS] move FindPolytopeGivenLagrangian out of dev.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18963)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@EricCousineau-TRI for Thursday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18963#-:-NQ2SpdI2GFqI5mrDQTr:b-3olowb)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with request for documentation on mutation-during-solve, and som small nits
+(status: single reviewer ok) 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18963#-:-NQ5h5skBnLVfeey06nG:b-qsy8rd)* status: 4 unresolved discussions (waiting on @hongkai-dai)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 252 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18963#-NQ5eibn6zoj3_NLiDlC:-NQ5eibn6zoj3_NLiDlD:b-r5rg51) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd614f683bdff7f68cdfed7b9ef1cfe034d9f20a/geometry/optimization/cspace_free_polytope.cc#L252)):*
BTW "Solves" for active voice
https://drake.mit.edu/styleguide/cppguide.html#Function_Comments

> [...] for example, "Opens the file", rather than "Open the file". [...]
___
*[`geometry/optimization/cspace_free_polytope.cc` line 257 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18963#-NQ5fKEL1h18HsrsXQwB:-NQ5fKEL1h18HsrsXQwC:blj9rfo) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd614f683bdff7f68cdfed7b9ef1cfe034d9f20a/geometry/optimization/cspace_free_polytope.cc#L257)):*
> ```cpp
> // only finds a strictly feasible solution in the strict interior of the
> // feasible set. This helps the next iteration of the bilinear alternation.
> solvers::MathematicalProgramResult SolveWithBackoff(
> ```

This seems to mutate the original problem without restoring it.

If that is the case, is that OK? If so, can you briefly mention that here?
___
*[`geometry/optimization/cspace_free_polytope.cc` line 903 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18963#-NQ5flsu6YAQZ1KGbL26:-NQ5flsu6YAQZ1KGbL27:bfdhfxs) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd614f683bdff7f68cdfed7b9ef1cfe034d9f20a/geometry/optimization/cspace_free_polytope.cc#L903)):*
> ```cpp
>     std::unordered_map<int, SeparationCertificate>* new_certificates_map)
>     const {
>   auto prog = std::make_unique<solvers::MathematicalProgram>();
> ```

nit Should `DRAKE_DEMAND(new_certiifcates_map ! = nullptr)` for public function.
___
*[`geometry/optimization/cspace_free_polytope.cc` line 1052 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18963#-NQ5ggJz0dKnslY07bV9:-NQ5ggJz0dKnslY07bVA:br4eyg3) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd614f683bdff7f68cdfed7b9ef1cfe034d9f20a/geometry/optimization/cspace_free_polytope.cc#L1052)):*
> ```cpp
> 
> void CspaceFreePolytope::AddEllipsoidContainmentConstraint(
>     solvers::MathematicalProgram* prog, const Eigen::MatrixXd& Q,
> ```

BTW Even if private, consider adding `DRAKE_DEMAND(prog != nullptr)`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18963)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 257 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18963#-NQ5fKEL1h18HsrsXQwB:-NQ6K-bJ090dSOC7q7ZU:bnhnh7x) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd614f683bdff7f68cdfed7b9ef1cfe034d9f20a/geometry/optimization/cspace_free_polytope.cc#L257)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This seems to mutate the original problem without restoring it.

If that is the case, is that OK? If so, can you briefly mention that here?
</blockquote></details>

Done. Good call. Yes, mutating the original program is intentional.
___
*[`geometry/optimization/cspace_free_polytope.cc` line 903 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18963#-NQ5flsu6YAQZ1KGbL26:-NQ6KAj-4mBrt6V9t6HB:b87qtr8) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd614f683bdff7f68cdfed7b9ef1cfe034d9f20a/geometry/optimization/cspace_free_polytope.cc#L903)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should `DRAKE_DEMAND(new_certiifcates_map ! = nullptr)` for public function.
</blockquote></details>

It is actually not required. This is documented in the header https://github.com/RobotLocomotion/drake/blob/e161fb76b974be42ed7df3c3755ad0d11bbf6847/geometry/optimization/cspace_free_polytope.h#L445-L450

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18963)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 903 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18963#-NQ5flsu6YAQZ1KGbL26:-NQ6OES08zuRPVGGTpco:bt5rqz5) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd614f683bdff7f68cdfed7b9ef1cfe034d9f20a/geometry/optimization/cspace_free_polytope.cc#L903)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I mean we allow new_certificates = nullptr

Is it because in the header I use the variable name `new_certificates` but in the `cc` file I use `new_certificates_map`? If that is the case, I have changed them to the same name.
</blockquote></details>

OK Ah, gotcha, thanks for clarifying!

**Pull request merged**
