### PR TITLE
WIP: Use libjchart2d-java from apt on Ubuntu

### LINKED ISSUE #13778: Use libjchart2d-java from apt on Ubuntu
Seems to be the same version that we currently use:

* https://packages.ubuntu.com/bionic/libjchart2d-java
* https://packages.ubuntu.com/focal/libjchart2d-java

Relates in part #12783.

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Resolves #13778

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14786)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please.

**Comment by jwnimmer-tri** [comment]
FYI in contrast to #14784, here macOS notably does not seem to have jchart2d packaged anywhere, so Ubuntu can use the host but macOS will still download the jar per our workspace rules.  Given the licensing of jchart2d, the low rate of change of lcm-spy, and not having any lcm-spy regression tests in CI anyway, I think that's a fine split.  So :+1: on this PR.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please.

**Comment by jwnimmer-tri** [comment]
Given my understanding from offline chats, I believe our plan is to abandon this PR for now, because trying to split hairs here on Ubuntu vs macOS is too difficult vs the value we're getting on Ubuntu.  Thus, I'll close this for now, but please reopen if I've misunderstood.

**Pull request closed without merging**
