### PR TITLE
pydrake: Improve diagnostic text for failing optimization_test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This might help diagnose https://drake-jenkins.csail.mit.edu/view/Production/job/mac-catalina-clang-bazel-nightly-everything-release/592 or similar.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15074)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

We expected this to fail, but possibly more usefully now.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

That test is very prone to failure on Mac, it is a hard nonlinear optimization problem, and requires some careful initialization.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15074#-:-MaLuY45E8S_LWRrMC4_:bxi7sfx)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
-@EricCousineau-TRI +(status: do not merge)  Our revised plan is to remove this test case entirely.

**Pull request closed without merging**
