### PR TITLE
Simplify compiler checks

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Rewrite the logic in `cc/repository.bzl` to use a helper function for testing if the compiler is of a supported version, based on a dictionary of supported compilers. This replaces the previous logic which was heavily redundant and required the supported compiler version to be specified in multiple places.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17146)

### CODE REVIEW

**Comment by sherm1** [comment]
@mwoehlke-kitware is this ready for feature review? If so please assign one.

**Comment by mwoehlke-kitware** [comment]
+@svenevs for feature review, please.

**Review by svenevs — COMMENTED** [review]
:lgtm: with some minor change requests.  Tested `GNU`, `Clang`, and `AppleClang` work as expected as well as locally modified `supported_compilers` to higher numbers to make sure errors are reported as expected.

+@jwnimmer-tri for platform review per schedule please.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17146#-:-N2D391_5bTI6uV2YCEB:bscgy1t)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[`tools/workspace/cc/repository.bzl` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2D0fJiB_ZQDR_WSsAu:-N2D0fJiB_ZQDR_WSsAv:b-fjjy75) ([raw file](https://github.com/robotlocomotion/drake/blob/3d3f89db4046b94d38abdcf116a78ced7c84a355/tools/workspace/cc/repository.bzl#L39)):*
> ```Starlark
> def _check_compiler_version(compiler_id, actual_version, supported_version):
>     """
>     Check if compiler version is supported and report an error if not.
> ```

Nit: grammar, Check if **the** compiler version... (+`the`)
___
*[`tools/workspace/cc/repository.bzl` line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2D24xh1rpbLYylj3n3:-N2D24xh1rpbLYylj3n4:bp9932m) ([raw file](https://github.com/robotlocomotion/drake/blob/3d3f89db4046b94d38abdcf116a78ced7c84a355/tools/workspace/cc/repository.bzl#L49)):*
> ```Starlark
> 
>     elif actual_version[0] == supported_version[0]:
>         if len(supported_version) == 1:
> ```

FYI tested on a local mac and this works as expected for the AppleClang switch, I don't think it's worth waiting for a mac CI job to run :wink:
___
*[`tools/workspace/cc/repository.bzl` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2D2YhRATGIAuoyQ4d1:-N2D2YhSEf9CMB_-bPO0:b-rkjxqz) ([raw file](https://github.com/robotlocomotion/drake/blob/3d3f89db4046b94d38abdcf116a78ced7c84a355/tools/workspace/cc/repository.bzl#L127)):*
> ```Starlark
>     # The minimum compiler versions should match those listed in both the root
>     # CMakeLists.txt and doc/_pages/from_source.md.
>     # TODO(jwnimmer-tri) Set supported_compilers["Clang"]=12 on 2022-09-01.
> ```

Nit: this `TODO` should move down to the `else` block on the line above where it is relevant like in the previous setup.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17146)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @svenevs)

___
*[`tools/workspace/cc/repository.bzl` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2D0fJiB_ZQDR_WSsAu:-N2D9MHjEQn2Wn-VsP_Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d3f89db4046b94d38abdcf116a78ced7c84a355/tools/workspace/cc/repository.bzl#L39)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Nit: grammar, Check if **the** compiler version... (+`the`)
</blockquote></details>

Done.
___
*[`tools/workspace/cc/repository.bzl` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2D2YhRATGIAuoyQ4d1:-N2D9O9A7nruE8E3n0z_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d3f89db4046b94d38abdcf116a78ced7c84a355/tools/workspace/cc/repository.bzl#L127)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Nit: this `TODO` should move down to the `else` block on the line above where it is relevant like in the previous setup.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17146#-:-N2MZ-G_4w0WHkoypJZ6:bnfp4nl)* status: 3 unresolved discussions (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/cc/repository.bzl` line 42 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2MYgVF78dEYEL5M--m:-N2MYgVG9Myc6pXoM8-k:b9qr0o8) ([raw file](https://github.com/robotlocomotion/drake/blob/f682efbd3ea91a37c832e34285bd625309635d85/tools/workspace/cc/repository.bzl#L42)):*
> ```Starlark
> 
>     The actual_version must be a 2-tuple of the (major, minor) version. The
>     supported_version may be a 1-tuple (only major version is checked) or
> ```

nit Do we actually need 1-tuple support as a special case?  I would think that passing a minor==0 (e.g., `(12, 0)`) would be just as good, and allow us to simplify the logic and the need for special-case commentary throughout this change.
___
*[`tools/workspace/cc/repository.bzl` line 136 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2DBMO38F9gxfG0G_a_:-N2DBMO41_9xb7fUA3N3:b-29ttvf) ([raw file](https://github.com/robotlocomotion/drake/blob/f682efbd3ea91a37c832e34285bd625309635d85/tools/workspace/cc/repository.bzl#L136)):*
> ```Starlark
>     # We do not fail outright here since even though we do not officially
>     # support them, Drake may happily compile with new enough versions of
>     # compilers that are compatible with GNU flags such as -std=c++17.
> ```

nit This comment paragraph was explaining the "print WARNING" stanza, which is now no longer here.  Thus, this comment is left stranded and is thus confusing.
___
*[`tools/workspace/cc/repository.bzl` line 139 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2MXy0pDSek9eE4p33P:-N2MXy0q6NTvJ_RPGhlJ:b-d7kp05) ([raw file](https://github.com/robotlocomotion/drake/blob/f682efbd3ea91a37c832e34285bd625309635d85/tools/workspace/cc/repository.bzl#L139)):*
> ```Starlark
> 
>     compiler_version_major = int(output[1])
>     compiler_version_minor = int(output[2])
> ```

nit Now that we're doing name + version checks at all once, it might make most sense to do this parsing immediately following the `compiler_id = output[0]` on line 123, so that parsing the output format of `identify_compiler` is all in once place?

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17146)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),svenevs (waiting on @jwnimmer-tri and @svenevs)

___
*[`tools/workspace/cc/repository.bzl` line 42 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2MYgVF78dEYEL5M--m:-N2MhsUi2zFQoiRYL8XR:b-38o3gn) ([raw file](https://github.com/robotlocomotion/drake/blob/f682efbd3ea91a37c832e34285bd625309635d85/tools/workspace/cc/repository.bzl#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Do we actually need 1-tuple support as a special case?  I would think that passing a minor==0 (e.g., `(12, 0)`) would be just as good, and allow us to simplify the logic and the need for special-case commentary throughout this change.
</blockquote></details>

Done. (Was trying to preserve exactly the original logic, but yeah, if you're okay having to always specify a major *and minor* version for minimum support, that's indeed cleaner.)
___
*[`tools/workspace/cc/repository.bzl` line 136 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2DBMO38F9gxfG0G_a_:-N2MiDv61wh9LXld-jb2:b-8sly3c) ([raw file](https://github.com/robotlocomotion/drake/blob/f682efbd3ea91a37c832e34285bd625309635d85/tools/workspace/cc/repository.bzl#L136)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This comment paragraph was explaining the "print WARNING" stanza, which is now no longer here.  Thus, this comment is left stranded and is thus confusing.
</blockquote></details>

Done. (If I understood correctly.)
___
*[`tools/workspace/cc/repository.bzl` line 139 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2MXy0pDSek9eE4p33P:-N2Mhqsw-UuuJB8N6XHD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f682efbd3ea91a37c832e34285bd625309635d85/tools/workspace/cc/repository.bzl#L139)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Now that we're doing name + version checks at all once, it might make most sense to do this parsing immediately following the `compiler_id = output[0]` on line 123, so that parsing the output format of `identify_compiler` is all in once place?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17146)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),svenevs (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/cc/repository.bzl` line 136 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17146#-N2DBMO38F9gxfG0G_a_:-N2MpTuK9JBhYfpSiUW_:bjgw6wm) ([raw file](https://github.com/robotlocomotion/drake/blob/f682efbd3ea91a37c832e34285bd625309635d85/tools/workspace/cc/repository.bzl#L136)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Done. (If I understood correctly.)
</blockquote></details>

OK Yup looks good.  I actually intended to my message for clarity before posting it, but you figured it out anyway.

**Pull request merged**
