### PR TITLE
[py tools] Vastly improve stubgen wrapper

### LINKED ISSUE #18119: CI failure: stubgen timeout
In https://drake-jenkins.csail.mit.edu/view/Production/job/linux-focal-gcc-bazel-weekly-snopt-release/4/ the invocation of `stubgen` timed out, resulting in several failures:
```
[3:49:18 AM]  ERROR: /media/ephemeral0/ubuntu/workspace/linux-focal-gcc-bazel-weekly-snopt-release/src/bindings/pydrake/BUILD.bazel:789:22: GenerateMypyStubs bindings/pydrake/pydrake/__init__.pyi failed: (Exit 1): stubgen failed: error executing command bazel-out/k8-opt/bin/bindings/pydrake/stubgen --quiet '--package=pydrake' '--output=bazel-out/k8-opt/bin/bindings/pydrake'
[3:49:18 AM]  
[3:49:18 AM]  Use --sandbox_debug to see verbose messages from the sandbox
[3:49:18 AM]  Traceback (most recent call last):
[3:49:18 AM]    File "/media/ephemeral0/ubuntu/workspace/linux-focal-gcc-bazel-weekly-snopt-release/_bazel_ubuntu/cdb0f36101f07a70b5208b088ff281a2/sandbox/linux-sandbox/4355/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/stubgen.runfiles/drake/bindings/pydrake/stubgen.py", line 13, in <module>
[3:49:18 AM]      sys.exit(stubgen.main())
[3:49:18 AM]    File "/media/ephemeral0/ubuntu/workspace/linux-focal-gcc-bazel-weekly-snopt-release/_bazel_ubuntu/cdb0f36101f07a70b5208b088ff281a2/sandbox/linux-sandbox/4355/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/stubgen.runfiles/mypy_internal/mypy/stubgen.py", line 1831, in main
[3:49:18 AM]      generate_stubs(options)
[3:49:18 AM]    File "/media/ephemeral0/ubuntu/workspace/linux-focal-gcc-bazel-weekly-snopt-release/_bazel_ubuntu/cdb0f36101f07a70b5208b088ff281a2/sandbox/linux-sandbox/4355/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/stubgen.runfiles/mypy_internal/mypy/stubgen.py", line 1652, in generate_stubs
[3:49:18 AM]      py_modules, c_modules = collect_build_targets(options, mypy_opts)
[3:49:18 AM]    File "/media/ephemeral0/ubuntu/workspace/linux-focal-gcc-bazel-weekly-snopt-release/_bazel_ubuntu/cdb0f36101f07a70b5208b088ff281a2/sandbox/linux-sandbox/4355/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/stubgen.runfiles/mypy_internal/mypy/stubgen.py", line 1418, in collect_build_targets
[3:49:18 AM]      py_modules, c_modules = find_module_paths_using_imports(
[3:49:18 AM]    File "/media/ephemeral0/ubuntu/workspace/linux-focal-gcc-bazel-weekly-snopt-release/_bazel_ubuntu/cdb0f36101f07a70b5208b088ff281a2/sandbox/linux-sandbox/4355/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/stubgen.runfiles/mypy_internal/mypy/stubgen.py", line 1452, in find_module_paths_using_imports
[3:49:18 AM]      result = find_module_path_and_all_py3(inspect, mod, verbose)
[3:49:18 AM]    File "/media/ephemeral0/ubuntu/workspace/linux-focal-gcc-bazel-weekly-snopt-release/_bazel_ubuntu/cdb0f36101f07a70b5208b088ff281a2/sandbox/linux-sandbox/4355/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/stubgen.runfiles/mypy_internal/mypy/stubutil.py", line 83, in find_module_path_and_all_py3
[3:49:18 AM]      mod = inspect.get_package_properties(module)
[3:49:18 AM]    File "/media/ephemeral0/ubuntu/workspace/linux-focal-gcc-bazel-weekly-snopt-release/_bazel_ubuntu/cdb0f36101f07a70b5208b088ff281a2/sandbox/linux-sandbox/4355/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/stubgen.runfiles/mypy_internal/mypy/moduleinspect.py", line 138, in get_package_properties
[3:49:18 AM]      res = self._get_from_queue()
[3:49:18 AM]    File "/media/ephemeral0/ubuntu/workspace/linux-focal-gcc-bazel-weekly-snopt-release/_bazel_ubuntu/cdb0f36101f07a70b5208b088ff281a2/sandbox/linux-sandbox/4355/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/stubgen.runfiles/mypy_internal/mypy/moduleinspect.py", line 164, in _get_from_queue
[3:49:18 AM]      raise RuntimeError("Timeout waiting for subprocess")
[3:49:18 AM]  RuntimeError: Timeout waiting for subprocess
[3:49:40 AM]  [10,498 / 10,526] 568 / 5885 tests, 1 failed; Compiling geometry/proximity/test/mesh_half_space_intersection_test.cc; 32s remote-cache, linux-sandbox ... (27 actions, 26 running)
[3:52:16 AM]  [13,386 / 13,412] 898 / 5885 tests, 1 failed; Compiling geometry/test/geometry_state_test.cc; 26s remote-cache, linux-sandbox ... (28 actions running)
[3:55:22 AM]  [17,661 / 17,686] 1879 / 5885 tests, 2 failed; Compiling geometry/proximity/test/triangle_surface_mesh_test.cc; 24s remote-cache, linux-sandbox ... (28 actions running)
[3:58:44 AM]  [23,153 / 23,182] 3051 / 5885 tests, 2 failed; Compiling multibody/contact_solvers/sap/test/sap_model_test.cc; 15s remote-cache, linux-sandbox ... (28 actions running)
[4:02:35 AM]  [28,235 / 28,261] 4276 / 5885 tests, 3 failed; Testing //multibody/fem:petsc_symmetric_block_sparse_matrix_test; 132s remote-cache ... (28 actions, 27 running)
[4:06:57 AM]  [34,093 / 34,119] 5710 / 5885 tests, 3 failed; Testing //multibody/fem:petsc_symmetric_block_sparse_matrix_test; 402s remote-cache ... (27 actions, 25 running)
[4:07:36 AM]  INFO: Elapsed time: 2102.846s, Critical Path: 464.62s
[4:07:36 AM]  INFO: 34728 processes: 17466 internal, 17228 linux-sandbox, 27 local, 7 worker.
[4:07:36 AM]  FAILED: Build did NOT complete successfully
[4:07:36 AM]  //:py/install_test                                              FAILED TO BUILD
[4:07:36 AM]  //bindings/pydrake:py/pyi_sanity_test                           FAILED TO BUILD
[4:07:36 AM]  //tools/install:py/install_test_helper_test                     FAILED TO BUILD
```
Opening and immediately closing this bug as possibly a one-off (we haven't seen this failure before in tests, although we have had relatively few runs to see it in, and it cleared on a re-run).  Reopen this issue if it recurs.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #18119 -- at least we hope so.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20403)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for feature review (at least we hope so).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-:-NhCh6MBAkCUKqKH4y0O:b3tuuh7)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

This certainly seems reasonable to me. I've got some cosmetic comments, but otherwise, there's reason to hope.

+@xuchenhan-tri based on slack conversation.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-:-NhCvDqWE1JdxiDFiJ9d:b-1pjsn2)* status: 8 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`bindings/pydrake/stubgen.py` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCoVfg6KTCj2C4oT-t:-NhCoVfg6KTCj2C4oT-u:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L27)):*
> ```Python
>     """Returns the list[str] of all pydrake module names."""
>     # This import should (as a side effect) load all pydrake modules. We have
>     # it as a function-local import because don't want `_wrapper_main` to pay
> ```

nit: typo



_Suggestion:_
```Python
because we don't
```
___
*[`bindings/pydrake/stubgen.py` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCookOEJ0yKEppqgzy:-NhCookOEJ0yKEppqgzz:b-9cstd0) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L47)):*
> ```Python
> 
> def _pyi_generated(directory: Path):
>     """Returns a list[Path] of all *.pyi files in the given directory."""
> ```

nit: This phrase doesn't seem consistent with using `os.walk`. Is it simply the understanding that there are no subdirectories?

The use of `full.relative_to` implies that you expect a tree, so, the documentation is misleading?  Or do you interpret "in a directory" as "in the tree rooted at a directory"?



_Code quote:_
```Python
in the given directory
```
___
*[`bindings/pydrake/stubgen.py` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCpBpq9m9cV5Q9nPHc:-NhCpBpq9m9cV5Q9nPHd:b-uhz8p2) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L50)):*
> ```Python
>     result = []
>     for dirpath, dirnames, filenames in os.walk(directory):
>         for one_filename in filenames:
> ```

nit: We're assuming the only files present *are* .pyi files? Worth being clear about that?

Admittedly, if this *isn't* true, it'll come out in the wash when copying, because that file won't be listed in `PYI_FILES`. The error message would be a bit odd, however.
___
*[`bindings/pydrake/stubgen.py` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCrcQp57FgfoPcFbCA:-NhCrcQp57FgfoPcFbCB:b2zu0ca) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L70)):*
> ```Python
>             "The PYI_FILES = ... in the BUILD.bazel file specified that the "
>             f"{missing_pyi} should have been created, but they were not. "
>             "Possibly PYI_FILES should not have listed those items.")
> ```

BTW Is it also possible that they forgot to add things to `_all_everything.py` or `all.py`?
___
*[`bindings/pydrake/stubgen.py` line 90 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCr9vc5RlHXhEOqhM5:-NhCr9vc5RlHXhEOqhM6:b-lx8p0t) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L90)):*
> ```Python
> 
> def _actual_main():
>     # Our arguments are the list of *.pyi outputs wanted from stubgen.bzl. They
> ```

BTW "wanted from stubgen.bzl" is correct. Is it also worth noting where that list is actually instantiated? `PYI_FILES` in `pydrake/BUILD.bazel`?

On the other hand, the error messages in `_copy_pyi` are pretty clear about that. So, I can go either way.



_Code quote:_
```Python
wanted from stubgen.bzl
```
___
*[`bindings/pydrake/stubgen.py` line 94 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCsCdO1T4kIDG6yOTc:-NhCsCdO1T4kIDG6yOTd:bybuibw) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L94)):*
> ```Python
>     # for the parent of "pydrake" lives, and then a list of relative paths
>     # under that.
>     output_root = Path(sys.argv[1].rsplit("/pydrake/")[0]).absolute()
> ```

BTW For my own edification, why prefer `rsplit` here when you're not using any limits on the number of splits?
___
*[`bindings/pydrake/stubgen.py` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCtSUsBJ8K3SJF53UN:-NhCtSUsBJ8K3SJF53UO:b5v7o95) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L102)):*
> ```Python
>     # Find all native modules in pydrake (i.e., excluding pure python modules).
>     native_modules = _pydrake_modules()
>     for name in list(native_modules):
> ```

BTW When I first saw `list` I was thinking....wait, wasn't this already a list? Then I realized that you were simply iterating through a copy so you could do erase on the original. Is there a more obvious idiom for that? (Or am I simply out of phase with common python practices?)
___
*[`bindings/pydrake/stubgen.py` line 108 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCtiGZ42nBRNZ1-eMj:-NhCtiGZ42nBRNZ1-eMk:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L108)):*
> ```Python
> 
>     # Run stubgen. It writes junk in the current directory, so we need to run
>     # it from safe place.
> ```

nit



_Suggestion:_
```Python
from a safe place
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20403)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`bindings/pydrake/stubgen.py` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCpBpq9m9cV5Q9nPHc:-NhD24xX51mFLQ2J8pOp:b53q2mv) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L50)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: We're assuming the only files present *are* .pyi files? Worth being clear about that?

Admittedly, if this *isn't* true, it'll come out in the wash when copying, because that file won't be listed in `PYI_FILES`. The error message would be a bit odd, however.
</blockquote></details>

Added fail-fast (and docs).
___
*[`bindings/pydrake/stubgen.py` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCrcQp57FgfoPcFbCA:-NhD2eTwE5MmB-8YKsHg:bb77ufg) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L70)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is it also possible that they forgot to add things to `_all_everything.py` or `all.py`?
</blockquote></details>

Yes.
___
*[`bindings/pydrake/stubgen.py` line 94 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCsCdO1T4kIDG6yOTc:-NhD0aiA2ZpaGLXGYxY2:b179c1u) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L94)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW For my own edification, why prefer `rsplit` here when you're not using any limits on the number of splits?
</blockquote></details>

The string has `/pydrake/pydrake/` in it.  Passing maxsplit=1 is clearer, though.
___
*[`bindings/pydrake/stubgen.py` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCtSUsBJ8K3SJF53UN:-NhD0YBv9iOaIuX4Ku8e:bjj6nvh) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L102)):*
> Is there a more obvious idiom for that?

Yes!  I'd just forgotten about it.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20403)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`bindings/pydrake/stubgen.py` line 94 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCsCdO1T4kIDG6yOTc:-NhD5bts2KHOZm8EVcJ5:b-5hcj1q) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L94)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The string has `/pydrake/pydrake/` in it.  Passing maxsplit=1 is clearer, though.
</blockquote></details>

Right.

So, for `this/is/a/pydrake/pydrake/path/to/foo` you want to extract `this/is/a/pydrake`.

The comment that you "need the _last_ '/pydrake/'" seems confusing. You "need" the last /pydrake/ in what sense? Because the one thing this invocation does is eliminate the last instance of /pydrake/ entirely. 
___
*[`bindings/pydrake/stubgen.py` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhCtSUsBJ8K3SJF53UN:-NhD6NwjDfVRiiLukdHz:b6cgqof) ([raw file](https://github.com/RobotLocomotion/drake/blob/99e3877092b9b375751ed8c3d0e6f23cf91ed0a6/bindings/pydrake/stubgen.py#L102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Is there a more obvious idiom for that?

Yes!  I'd just forgotten about it.
</blockquote></details>

Oh, yeah. And as soon as I saw it, I thought. Yeah. That's the one.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

Nice documentation and commit message. They help with understanding a lot.

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-:-NhDk3gVAbR9c-E2QGs3:b-s4fq1y)* status: 3 unresolved discussions

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhDjT3g544WChDKKf7o):*
BTW There are many nice improvements in this PR, but I believe the number one goal here is to alleviate the time out issue from stubgen. Am I correct in understanding that the only source of speed-up we should expect is from skipping pure python modules? Do you have an idea how much it alleviates the problem?
___
*[`tools/workspace/mypy_internal/patches/no_retry.patch` line 13 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhDkqpM6L8XV1w2H8_i:-NhDkqpM6L8XV1w2H8_j:bowpdym) ([raw file](https://github.com/RobotLocomotion/drake/blob/46ae2f0b9eb7368c766d188b295be7d71cfcc8b4/tools/workspace/mypy_internal/patches/no_retry.patch#L13)):*
> ```Diff
>              # Error importing module
> -            if self.counter > 0:
> +            if False:
> ```

BTW, I'm curious what could have caused this? Do we know if this ever happened in our stubgen timeouts?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20403)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhDjT3g544WChDKKf7o):*
> I believe the number one goal here is to alleviate the time out issue from stubgen.

Yes.

> Am I correct in understanding that the only source of speed-up we should expect is from skipping pure python modules?

I've been unable to get a full handle on what's going on, but my best guess is that skipping pure python is _not_ the most important factor.

My best guess that that `--module` vs `--package` is probably a big win (at least, under strace it's a _lot_ less filesystem syscalls) to reduce the time spent pawing through the filesystem trying to find modules, or maybe also fixing the `os.chdir` to avoid corrupting the runfiles is important (which might explain the non-reproducibility, in case the order of build actions matters).
___
*[`tools/workspace/mypy_internal/patches/no_retry.patch` line 13 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhDkqpM6L8XV1w2H8_i:-NhDp3AL8psYR_PYgJok:b-xz70d3) ([raw file](https://github.com/RobotLocomotion/drake/blob/46ae2f0b9eb7368c766d188b295be7d71cfcc8b4/tools/workspace/mypy_internal/patches/no_retry.patch#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm curious what could have caused this? Do we know if this ever happened in our stubgen timeouts?
</blockquote></details>

TBH I don't fully understand when this might happen.  Perhaps it can happen if our `deps = []` for the stubgen tool are incorrect (e.g., missing `@gymnasium_py`, if we were generating stubs for `pydrake.gym`).  I do know that on master prior to this PR, we would see ~3-4 retries (leading to re-forking several times in the strace logs), which could be a source of delays or unreliability.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20403)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhDjT3g544WChDKKf7o):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I believe the number one goal here is to alleviate the time out issue from stubgen.

Yes.

> Am I correct in understanding that the only source of speed-up we should expect is from skipping pure python modules?

I've been unable to get a full handle on what's going on, but my best guess is that skipping pure python is _not_ the most important factor.

My best guess that that `--module` vs `--package` is probably a big win (at least, under strace it's a _lot_ less filesystem syscalls) to reduce the time spent pawing through the filesystem trying to find modules, or maybe also fixing the `os.chdir` to avoid corrupting the runfiles is important (which might explain the non-reproducibility, in case the order of build actions matters).
</blockquote></details>

Ok, thanks for the explanation. Looking forward to seeing the result of tonight's nightly.
___
*[`tools/workspace/mypy_internal/patches/no_retry.patch` line 13 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhDkqpM6L8XV1w2H8_i:-NhDtNM661NZyUAYndCt:be67fkp) ([raw file](https://github.com/RobotLocomotion/drake/blob/46ae2f0b9eb7368c766d188b295be7d71cfcc8b4/tools/workspace/mypy_internal/patches/no_retry.patch#L13)):*
> I do know that on master prior to this PR, we would see ~3-4 retries

Interesting. Do those retries eventually succeed or do they eventually end with the same raised error? If the former, should we be concerned about more errors importing modules (that are potentially false positive?)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20403)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`tools/workspace/mypy_internal/patches/no_retry.patch` line 13 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20403#-NhDkqpM6L8XV1w2H8_i:-NhDwqz21i1BuwDv8v1W:bpu0w4f) ([raw file](https://github.com/RobotLocomotion/drake/blob/46ae2f0b9eb7368c766d188b295be7d71cfcc8b4/tools/workspace/mypy_internal/patches/no_retry.patch#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> I do know that on master prior to this PR, we would see ~3-4 retries

Interesting. Do those retries eventually succeed or do they eventually end with the same raised error? If the former, should we be concerned about more errors importing modules (that are potentially false positive?)
</blockquote></details>

The build was passing even with the retries.  Possibly what was happening was during `--package` search it eventually got to a module like `pydrake.gym` that included something missing, got an error, tried again, got the same error, and decided that the module doesn't exist and silently skipped it.

So many things were wrong with the old code that I gave up trying to fully understand it, and just repaved it with a better approach from scratch.  Since I happened to notice the unwanted retry here, I decided to plug the hole in case we start leaking again later.

**Pull request merged**
