### PR TITLE
[solvers] implement Display for Lorentz cone constraints

### PR DESCRIPTION
**Pull request by RussTedrake**
also touch the documentation and remove a stale detail that is no longer true.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15475)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15475#-:-MfUYajA19n4mKNUuRlk:b-81zjv5)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/constraint.h, line 293 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfUYgxkB1cuNsgm163w:-MfUYgxkB1cuNsgm163x:b-1fvh6m) ([raw file](https://github.com/robotlocomotion/drake/blob/a777aa9c320f97685c741e8c1eb93ffb917d5e6d/solvers/constraint.h#L293)):*
> ```objc
>     z₀ ≥ 0
>     This constraint is differentiable everywhere, but z₀²-(z₁²+...+zₙ₋₁²) ≥ 0 is
>  non-convex. The default is to use the first formulation. For more information
> ```

btw -- this was changed (so was invalid).  i decided to simply remove it, because it's clearly a danger for going stale.
___
*[solvers/evaluator_base.cc, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfUYqiB52fODR5QKmzy:-MfUYqiB52fODR5QKmzz:b-zgprk8) ([raw file](https://github.com/robotlocomotion/drake/blob/5f9d3aa44b4a6cdb7793345bc99a414e5328e7c5/solvers/evaluator_base.cc#L49)):*
> ```cpp
>     os << " " << vars(i).get_name();
>   }
>   os << "\n";
> ```

btw -- the lack of a line feed here was inconsistent with the rest of the cost/constraint displays, and led to multiple constraints getting printed on the same line in the recommended workflows (like the printing of all infeasible constraints as recommended in the debugging tutorial)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@seancurtis-tri for platform review please, thanks!

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15475#-:-MfVMTm30ikBGkikH4Po:b-vthiex)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[solvers/constraint.h, line 293 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfUYgxkB1cuNsgm163w:-MfVMI937wgWM7rKUeAj:bh43om1) ([raw file](https://github.com/robotlocomotion/drake/blob/a777aa9c320f97685c741e8c1eb93ffb917d5e6d/solvers/constraint.h#L293)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- this was changed (so was invalid).  i decided to simply remove it, because it's clearly a danger for going stale.
</blockquote></details>

Thanks for fixing it.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Pass done -- I have issue with the trailing whitespace in `EvaluatorBase` -- I dug a bit, but wasn't able to really understand the value of the change. But the tests made the cost crystal clear.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15475#-:-MfYIWs2Dpfr00WeTmyj:b-vebsfy)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

___
*[solvers/evaluator_base.cc, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfUYqiB52fODR5QKmzy:-MfYGaLfEjOBxzEdFuWr:bednvyx) ([raw file](https://github.com/robotlocomotion/drake/blob/5f9d3aa44b4a6cdb7793345bc99a414e5328e7c5/solvers/evaluator_base.cc#L49)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- the lack of a line feed here was inconsistent with the rest of the cost/constraint displays, and led to multiple constraints getting printed on the same line in the recommended workflows (like the printing of all infeasible constraints as recommended in the debugging tutorial)
</blockquote></details>

Unfortunately, it *forces* a new line onto the end (as illustrated in your test). If I do `fmt::format("{} -- {}", binding, "some label");`, I should *not* get a newline between binding and "-- some label".

The newlines should be introduced by whatever code is writing multiple constraints to the stream.

Finally, I don't see any tests that show the benefit of this change, only modifications that show the detriment.
___
*[solvers/test/binding_test.cc, line 199 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfYHpq11jmz0GW7N8MP:-MfYHpq11jmz0GW7N8MQ:b-molieu) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/binding_test.cc#L199)):*
> ```cpp
>   EXPECT_EQ(fmt::format("{}", binding),
>             "DummyEvaluator described as 'dummy' with 3 decision variables "
>             "x1 x2 x3\n");
> ```

BTW This is one of the newlines I was alluding to. `"{}"` is not a format string that implies "end in newline".
___
*[solvers/test/evaluator_base_test.cc, line 276 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfYIFjc3C220jJ9YZ_b:-MfYIFjc3C220jJ9YZ_c:b-hv983v) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/evaluator_base_test.cc#L276)):*
> ```cpp
>   EXPECT_EQ(fmt::format("{}", evaluator),
>             "DynamicSizedEvaluator with 1 decision variables "
>             "dynamic_sized_variable\n");
> ```

btw And again here.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15475)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

___
*[solvers/test/constraint_test.cc, line 164 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfYJ7XyB6m9BIiQ8yS9:-MfYJ7XyB6m9BIiQ8ySA:b672aju) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/constraint_test.cc#L164)):*
> ```cpp
>   cnstr1.Display(
>       os, symbolic::MakeVectorContinuousVariable(cnstr1.num_vars(), "x"));
>   EXPECT_THAT(os.str(), HasSubstr("LorentzConeConstraint\n"));
> ```

nit: The previous test (`testQuadraticConstraintHessian`) does an exact test on the string. In #15472, you likewise do exact string matching. If there's a good reason for this to be different, the reason should be documented.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15475)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[solvers/evaluator_base.cc, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfUYqiB52fODR5QKmzy:-Mf_7ralAL46x8E0j4tR:b331gc6) ([raw file](https://github.com/robotlocomotion/drake/blob/5f9d3aa44b4a6cdb7793345bc99a414e5328e7c5/solvers/evaluator_base.cc#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Unfortunately, it *forces* a new line onto the end (as illustrated in your test). If I do `fmt::format("{} -- {}", binding, "some label");`, I should *not* get a newline between binding and "-- some label".

The newlines should be introduced by whatever code is writing multiple constraints to the stream.

Finally, I don't see any tests that show the benefit of this change, only modifications that show the detriment.
</blockquote></details>

i don't have a great way to check for all of the callers of this method, in particular because it was recommended in the tutorial... e.g.:
```
for c in infeasible_constraints:
    print(f"infeasible constraint: {c}")
```
is in https://github.com/RobotLocomotion/drake/blob/master/tutorials/debug_mathematical_program.ipynb
I can add a `\n` to that call site and the few I know about.  But admittedly I  don't share your concern.
___
*[solvers/test/constraint_test.cc, line 164 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfYJ7XyB6m9BIiQ8yS9:-Mf_788Q4jzu8irqgxNU:b-bbnorn) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/constraint_test.cc#L164)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: The previous test (`testQuadraticConstraintHessian`) does an exact test on the string. In #15472, you likewise do exact string matching. If there's a good reason for this to be different, the reason should be documented.
</blockquote></details>

This is in a method that gets called for multiple cone constraints.  there is not a unique string to test against.  i think that is very clear from the context (just not in the 6 line view you see here.) 
___
*[solvers/test/evaluator_base_test.cc, line 276 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfYIFjc3C220jJ9YZ_b:-Mf_7PCS5aAo8rd0wynI:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/evaluator_base_test.cc#L276)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw And again here.
</blockquote></details>

ditto

**Review by RussTedrake — COMMENTED** [review]
On reflection, i don't want to spend the time required to chase this down for you.  We have bigger fish to fry.  Two options:
1) i will remove the EvaluatorBase change, leaving known bad printing in a handful of cases, or 
2) i can leave the PR as is, fixing the cases I know about, and possibly offending a hypothetical future user with an extra line break.
You pick.
If you want to chase down the root cause, I'd be happy to review a follow-up PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15475#-:-Mf_fOAt9RQ_jcyBm6vX:b-qpw5lf)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Consistent is better than inconsistent.

:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15475#-:-Mfc-g8D2A6Xjy5CJ-yQ:b-pkjxg9)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @RussTedrake)

___
*[solvers/test/constraint_test.cc, line 164 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfYJ7XyB6m9BIiQ8yS9:-Mfc00VB8CpYgLRot5MR:bxgt1bg) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/constraint_test.cc#L164)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This is in a method that gets called for multiple cone constraints.  there is not a unique string to test against.  i think that is very clear from the context (just not in the 6 line view you see here.) 
</blockquote></details>

I don't understand your point. I looked at more than the six lines here. I noted that *every* other call to `Display` in this test (prior to this PR) tests against exact strings. Further tests (as shown in #15472) *likewise* test the result of `Display` against a fully specified string.

It is simply *not* clear to me why this merely searches for substrings rather than explicit strings. The LorentzCone (both versions) Display methods are treated differently from all the other constraints that I'm able to see and I don't understand why.

However, you're confident its correct and to reduce friction I'm marking myself satisified.

**Comment by RussTedrake** [comment]
___
*[solvers/test/constraint_test.cc, line 143 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfcRcDx9OfeunpA-SES:-MfcRcDyEXN2K1i5oJVl:bats25g) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/constraint_test.cc#L143)):*
> ```cpp
> void TestLorentzConeEvalConvex(const Eigen::Ref<const Eigen::MatrixXd>& A,
>                                const Eigen::Ref<const Eigen::VectorXd>& b,
>                                const VectorXd& x_test) {
> ```

@seancurtis-tri .  See here?  this is a helper method.  It is called more than once (with different values of A and b).  So the string will be different each time.  i could reconstruct the exact value-dependent string here but it would add little value, i think, and make the test unnecessarily brittle.  (In fact, I tend to think matching the entire string always is brittle in the other sites, too... this test confirms that the proper display method gets called and successfully creates a string)

**Comment by RussTedrake** [comment]
___
*[solvers/test/constraint_test.cc, line 304 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfcRxMKBsj2q_o9kA_t:-MfcRxMKBsj2q_o9kA_u:bv15gp4) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/constraint_test.cc#L304)):*
> ```cpp
>   // clang-format on
>   Eigen::Vector4d b2(2, -2, 0, 6);
>   TestLorentzConeEvalConvex(A2, b2, x2);
> ```

called from here

**Comment by RussTedrake** [comment]
___
*[solvers/test/constraint_test.cc, line 290 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfcRw0_Bv3kHhtrcuQ8:-MfcRw0_Bv3kHhtrcuQ9:bv15gp4) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/constraint_test.cc#L290)):*
> ```cpp
>   Eigen::Vector3d x1(3.0, 1.0, 1.0);
>   TestLorentzConeEvalConvex(Eigen::Matrix3d::Identity(),
>                             Eigen::Vector3d::Zero(), x1);
> ```

called from here

**Comment by RussTedrake** [comment]
___
*[solvers/test/constraint_test.cc, line 316 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15475#-MfcRyRgE8LOHdguWMjC:-MfcRyRgE8LOHdguWMjD:b-66npuy) ([raw file](https://github.com/robotlocomotion/drake/blob/64d8ae566a10a55c7c4c0212ff68982de96c7ffc/solvers/test/constraint_test.cc#L316)):*
> ```cpp
>   // clang-format on
>   Eigen::Vector3d b3 = Eigen::Vector3d(3, 3, 1) - A3 * x3;
>   TestLorentzConeEvalConvex(A3, b3, x3);
> ```

called from here, etc.

**Pull request merged**
