### PR TITLE
Add OSQP

### LINKED ISSUE #5071: add open-source QP solvers
per discussion with @edrumwri , we should consider moby, quadprog++, etc.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #5071 

@rdeits .

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8029)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@siyuanfeng-tri for feature review please.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L4yWRV6U9BYUD4lXHH4:bakb6i6)*

**Comment by hongkai-dai** [comment]
+(status: do not review) 

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L4ymNlYisrPXiseYEbr:b7ovtzr)*

**Comment by hongkai-dai** [comment]
The failure in `integer_optimization_program_util_test` is due to an error in the original `OSQP` solver. I submitted a PR https://github.com/oxfordcontrol/osqp/pull/45 to fix the bug in the source code.

There is another segfault on `scs_solver_test`, which I do not quite understand. Her is the valgrind output, when running `scs_solver_test`.
```
==6624== Invalid read of size 4
==6624==    at 0x402FFC3: ldl_l_perm (ldl.c:424)
==6624==    by 0x4030985: LDLSolve (suitesparse_ldl.c:284)
==6624==    by 0x4045288: solveLinSys (private.c:214)
==6624==    by 0x4048103: updateWork (scs.c:798)
==6624==    by 0x4047DA6: scs_solve (scs.c:818)
==6624==    by 0xDB22E8: drake::solvers::ScsSolver::Solve(drake::solvers::MathematicalProgram&) const 
```
and
```
==2744==    at 0x4031D00: ldl_l_perm (in /home/hongkai/.cache/bazel/_bazel_hongkai/73d4664077a79d787c1bbab18e01ebc7/execroot/drake/bazel-out/k8-opt/bin/external/osqp/libosqp.so)
==2744==    by 0x4032B65: LDLSolve (in /home/hongkai/.cache/bazel/_bazel_hongkai/73d4664077a79d787c1bbab18e01ebc7/execroot/drake/bazel-out/k8-opt/bin/external/osqp/libosqp.so)
==2744==    by 0x404BC78: solveLinSys (in /home/hongkai/.cache/bazel/_bazel_hongkai/73d4664077a79d787c1bbab18e01ebc7/execroot/drake/bazel-out/k8-opt/bin/external/scs/libscsdir.so)
```
Notice that it tries to call `libosqp.so` from `libscsdir.so`. 

I am confused that scs would link to osqp here. I know both solvers ship with their `suitesparse_ldl.c` and `ldl_l_perm`, but they should be built separately.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L52u44B_ipoxZgzCncT:b-u3kszd)*

**Comment by hongkai-dai** [comment]
Sorry I was wrong when I say `scs` ships with `suitesparse_ldl.c` and `ldl_l_perm.c`. Only `OSQP` ships with these two files, `SCS` does not. Why `scs` would want to call functions from these two files in `OSQP`?

@jwnimmer-tri and @jamiesnape how can I make sure that `libscsdir.so` does not call functions in `libosqp.so`?

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L53-0i45jNsN75iXNX3:bvheot7)*

**Comment by jwnimmer-tri** [comment]
If the functions have the same signature (and namespace iff C++), then they are most likely going to contaminate each other without any easy fixes.  We could build their `linear` libraries with `copts = ["-fvisibility-hidden"]` and try to disentagle them, but if what's going on (I haven't looked in detail) is that they are both trying to use suitesparse, then the correct answer is to add suitesparce to the workspace as is own library, pulled in from Ubuntu, and then have both scs and osqp link that copy and not compile their own vendored copy.

**Comment by hongkai-dai** [comment]
Thanks Jeremy.

These functions are all in C.

The problem is that in SCS/linsys/direct/private.c https://github.com/cvxgrp/scs/blob/master/linsys/direct/private.c#L224, where it wants to call the `LDLSolve` function defined in the same file https://github.com/cvxgrp/scs/blob/master/linsys/direct/private.c#L137-L155, it instead calls the `LDLSolve` function defined in `OSQP` https://github.com/oxfordcontrol/osqp/blob/master/lin_sys/direct/suitesparse/suitesparse_ldl.c#L279-L290. Neither `private.c` in `SCS` or `suitesparse_ldl.c` in `OSQP` are in suitesparse package, both files are created by the authors of the solver, as a wrapper to call suitesparse functions. So I think it is not the problem with `suitesparse` package, but the directories `scs/linsys/direct` and `osqp/lin_sys/direct/suitesparse` should be compiled with hidden visibility.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L551vHrji6tQX0rf9TR:b-s2bvdu)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.
-(status: do not review) 

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5G3qnXoOdiANY7bcF6:bo4e6w4)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5G5D_pKeIfpeV7TYy0:b7d2d3u)*

**Comment by jamiesnape** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/workspace/osqp/BUILD.bazel, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5GQ-bTgv4vLbJMIm_h:-L5GQ-bTgv4vLbJMIm_i:ba3dfmt) ([raw file](https://github.com/robotlocomotion/drake/blob/e53002654a5f263febe6598fa4b5c36a0e56fda9/tools/workspace/osqp/BUILD.bazel#L8)):*
> ```Python
>     ["package-create-cps.py"],
>     visibility = ["@osqp//:__pkg__"],
> )
> ```

Remove.

---

*[tools/workspace/osqp/package.BUILD.bazel, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5GQ8tOquCLPvEcjQgl:-L5GQ8tOquCLPvEcjQgm:b-ao0k29) ([raw file](https://github.com/robotlocomotion/drake/blob/e53002654a5f263febe6598fa4b5c36a0e56fda9/tools/workspace/osqp/package.BUILD.bazel#L11)):*
> ```
>     "cmake_config",
>     "install",
>     "install_cmake_config",
> ```

Remove (and cmake_config).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/osqp/BUILD.bazel, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5GQ-bTgv4vLbJMIm_h:-L5GZ-2tAVoRuXmLnMD2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e53002654a5f263febe6598fa4b5c36a0e56fda9/tools/workspace/osqp/BUILD.bazel#L8)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

---

*[tools/workspace/osqp/package.BUILD.bazel, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5GQ8tOquCLPvEcjQgl:-L5GZYmu0kycA8EdIbfX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e53002654a5f263febe6598fa4b5c36a0e56fda9/tools/workspace/osqp/package.BUILD.bazel#L11)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Remove (and cmake_config).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

---

Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5GZdS_9k4UXDCVQLJB:b7d2d3u)*

**Comment by jamiesnape** [comment]
Add `osqp_solver` to https://github.com/RobotLocomotion/drake/blob/master/tools/install/libdrake/build_components.bzl (after #8073 would be easiest).

**Comment by hongkai-dai** [comment]
-@siyuanfeng-tri +@jamiesnape for feature review please.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5R-jitp1UvwqSviY0O:bi9i5v0)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
I guess we need to address the MATLAB segfault, but I do not have any particular suggestions. That test is MATLAB calling Python calling C/C++, so really difficult to debug. If it is a conflict with some MATLAB library, we could disable this solver for MATLAB as we do IPOPT.

**Comment by jamiesnape** [comment]
Reviewed 19 of 24 files at r1, 2 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[solvers/BUILD.bazel, line 1153 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5U-47fT3La_2P-nK2U:-L5U-47fT3La_2P-nK2V:bcg60zo) ([raw file](https://github.com/robotlocomotion/drake/blob/0f5ba0b791dc989f39df8ac50b9fe585bbd2933f/solvers/BUILD.bazel#L1153)):*
> ```Python
> # The extra_srcs are required here because add_lint_tests() doesn't understand
> # how to extract labels from select() functions yet.
> add_lint_tests(cpplint_extra_srcs = [
> ```

Add the OSQP related source files to this list.

---

*[solvers/osqp_solver.cc, line 18 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5U-PxI3KOfVrSl1CBa:-L5U-PxJe5huhX473jR2:b-9eo0yn) ([raw file](https://github.com/robotlocomotion/drake/blob/0f5ba0b791dc989f39df8ac50b9fe585bbd2933f/solvers/osqp_solver.cc#L18)):*
> Hessiagn

Hessian?

---

*[solvers/osqp_solver.cc, line 37 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5U1P0_RV3BTMPCxUT9:-L5U1P0_RV3BTMPCxUTA:bvbngik) ([raw file](https://github.com/robotlocomotion/drake/blob/0f5ba0b791dc989f39df8ac50b9fe585bbd2933f/solvers/osqp_solver.cc#L37)):*
> ```cpp
>     }
> 
>     // Add quadratic_cost.b to the linear cost term q
> ```

BTW Some comments have periods at the end, others don't. It would be nice to be consistent.

---

*[solvers/test/integer_optimization_util_test.cc, line 76 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5U70GPXjJH-yVtUz47:-L5U6iW09ioVmn8-G7Kw:b48i7iu) ([raw file](https://github.com/robotlocomotion/drake/blob/0f5ba0b791dc989f39df8ac50b9fe585bbd2933f/solvers/test/integer_optimization_util_test.cc#L76)):*
> ```cpp
>       auto result = prog_.Solve();
>       EXPECT_EQ(result, SolutionResult::kSolutionFound);
>       double tol = 3E-3;
> ```

`1E-3`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029)*

**Comment by hongkai-dai** [comment]
@ericcousineau-tri and I think the problem is that `OSQP` uses `suitesparse`, while MATLAB also uses `suitesparse` for the sparse matrix manipulation. So `OSQP` causes `suitesparse` to segfault.

I just removed `osqp` from `libdrake.so` in `tools/install/libdrake/BUILD.bazel`

https://github.com/RobotLocomotion/drake/issues/7482

---

Review status: 20 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[solvers/BUILD.bazel, line 1153 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5U-47fT3La_2P-nK2U:-L5WBKKyLgNZq-yBpmV2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f5ba0b791dc989f39df8ac50b9fe585bbd2933f/solvers/BUILD.bazel#L1153)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Add the OSQP related source files to this list.
</blockquote></details>

Done.

---

*[solvers/osqp_solver.cc, line 18 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5U-PxI3KOfVrSl1CBa:-L5WBQVpI0j-PIXVhla6:b-yh10tr) ([raw file](https://github.com/robotlocomotion/drake/blob/0f5ba0b791dc989f39df8ac50b9fe585bbd2933f/solvers/osqp_solver.cc#L18)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> Hessiagn

Hessian?

</blockquote></details>

Done. Good catch

---

*[solvers/osqp_solver.cc, line 37 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5U1P0_RV3BTMPCxUT9:-L5WBnaf1EJLp4ebWd2Z:bu3k1xy) ([raw file](https://github.com/robotlocomotion/drake/blob/0f5ba0b791dc989f39df8ac50b9fe585bbd2933f/solvers/osqp_solver.cc#L37)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Some comments have periods at the end, others don't. It would be nice to be consistent.
</blockquote></details>

Done. Added period in the comments.

---

*[solvers/test/integer_optimization_util_test.cc, line 76 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5U70GPXjJH-yVtUz47:-L5WBxKqCG9s928XFhdT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f5ba0b791dc989f39df8ac50b9fe585bbd2933f/solvers/test/integer_optimization_util_test.cc#L76)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`1E-3`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5W9leb_-k3wu8DDWjX:bjnzu2e)*

**Comment by hongkai-dai** [comment]
@jamiesnape could you add `no_osqp` flag to the CI with matlab test?

---

Review status: 21 of 24 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5WGlaPYFbGCp_cP8uL:b2n7cdy)*

**Comment by jamiesnape** [comment]
You can exclude it in this PR. Add another define here: https://github.com/RobotLocomotion/drake/blob/5b5d80bc8718fa4783ba86a1751e06adc4713741/CMakeLists.txt#L90

---

Review status: 21 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5JjPr6zZiBxqjxpx_l:bked7g)*

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029)*

**Comment by jamiesnape** [comment]
:lgtm: (once the define is added and the MATLAB build passes)

BTW I agree with your hypothesis about MATLAB and suitesparse. It is on my radar to deal with the many library conflicts, but the potential fix is really complicated and difficult to make work for multiple versions of MATLAB.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5WLUSO_XSwLSWJdk3F:b-f607fs)*

**Comment by jamiesnape** [comment]
Review status: 24 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 89 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5aF6jJYjme3h-gWyMA:-L5aF6jJYjme3h-gWyMB:brr23gv) ([raw file](https://github.com/robotlocomotion/drake/blob/8cc3632cc39c8f92ca9b1cae1c029377e4a13b6a/CMakeLists.txt#L89)):*
> ```CMake
> 
> if(WITH_MATLAB)
>   list(APPEND BAZEL_ARGS --define=NO_IPOPT=ON  --define=NO_OSQP=ON)
> ```

BTW Can you reformat this as

```
list(APPEND BAZEL_ARGS
  --define=NO_IPOPT=ON
  --define=NO_OSQP=ON
)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 24 of 25 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5aFWq970FFgQ2Ue4Kp:bnfp4nl)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 89 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5aF6jJYjme3h-gWyMA:-L5bGKsW2Vo6VUh3G_xz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8cc3632cc39c8f92ca9b1cae1c029377e4a13b6a/CMakeLists.txt#L89)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Can you reformat this as

```
list(APPEND BAZEL_ARGS
  --define=NO_IPOPT=ON
  --define=NO_OSQP=ON
)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 16 of 24 files at r1, 2 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[solvers/osqp_solver.cc, line 154 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oQxhSgu6Nu50izxjC:-L5oQxhSgu6Nu50izxjD:bz69b3u) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/osqp_solver.cc#L154)):*
> ```cpp
> // Convert an Eigen::SparseMatrix to csc_matrix, to be used by osqp.
> // Make sure the input Eigen sparse matrix is compressed, by calling
> // makeCompressed() function.
> ```

BTW I think it would be helpful to document that the caller of this function is responsible for freeing the memory allocated here.

---

*[solvers/osqp_solver.cc, line 214 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oSjjAB0Oy5ZZ_sPfg:-L5oSjjAB0Oy5ZZ_sPfh:bg43dw) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/osqp_solver.cc#L214)):*
> ```cpp
> 
>   // OSQP structures.
>   OSQPWorkspace* work;  // Workspace
> ```

BTW consider moving this declaration closer to it's first use.

---

*[solvers/osqp_solver.cc, line 256 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oS-TYeAqq7DZvXvbv:-L5oS-TYeAqq7DZvXvbw:b-vrrxss) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/osqp_solver.cc#L256)):*
> ```cpp
>   c_int osqp_exitflag = osqp_solve(work);
>   if (osqp_exitflag) {
>     return SolutionResult::kInvalidInput;
> ```

This case will leak memory (we don't run the calls to `c_free` below).  Avoid early returns or ensure the cleanup code is called (some kind of RAII wrapper, set `solution_result` here and put the switch in an `else` block, `goto finish`, something).

---

*[solvers/test/osqp_solver_test.cc, line 68 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oTmLCJtbgCAFXa76Z:-L5oTmLEx0BN5hnYKKmL:b-uxw7xz) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/test/osqp_solver_test.cc#L68)):*
> ```cpp
> }
> 
> GTEST_TEST(QuadraticProgramTest, TestUnbounded) {
> ```

Should this actually say "QuadraticProgramTest"?  That's the name of another class which doesn't seem to be involved here.   (also the next test and "LinearProgramTest" below).

---

*[solvers/test/osqp_solver_test.cc, line 109 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oUkVxiyha_5C1s0eS:-L5oUkVzLYuLVKhrPeDu:bhfevdr) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/test/osqp_solver_test.cc#L109)):*
> ```cpp
> }
> 
> GTEST_TEST(LinearProgramTest, TestUnbounded) {
> ```

BTW is there a reason we wrote a new test here instead of using the unbounded tests from `linear_program_examples.h`?

---

*[tools/install/libdrake/build_components.bzl, line 202 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oNzpU6JCOKJ-VpwV7:-L5oNzpWLJO7ycUjWKYM:b-yu2vvo) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/tools/install/libdrake/build_components.bzl#L202)):*
> ```Python
>     "//drake/solvers:nlopt_solver",
>     "//drake/solvers:non_convex_optimization_util",
>     "//solvers:osqp_solver",
> ```

BTW consider using the redundant `//drake` prefix just so the list looks consistent.  It'll get cleaned up when the rest of the file does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5oUzkv0zP9pxMbBADL:bvb1a6z)*

**Comment by hongkai-dai** [comment]
Review status: 24 of 25 files reviewed at latest revision, 6 unresolved discussions.

---

*[solvers/osqp_solver.cc, line 154 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oQxhSgu6Nu50izxjC:-L5pH9pHF0jH_ulemwxs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/osqp_solver.cc#L154)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I think it would be helpful to document that the caller of this function is responsible for freeing the memory allocated here.
</blockquote></details>

Done.

---

*[solvers/osqp_solver.cc, line 214 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oSjjAB0Oy5ZZ_sPfg:-L5pHNmO0UzaxRNT7TII:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/osqp_solver.cc#L214)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW consider moving this declaration closer to it's first use.
</blockquote></details>

Done.

---

*[solvers/osqp_solver.cc, line 256 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oS-TYeAqq7DZvXvbv:-L5pHOP9t0I0cyMsMq-r:b-dx5hso) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/osqp_solver.cc#L256)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This case will leak memory (we don't run the calls to `c_free` below).  Avoid early returns or ensure the cleanup code is called (some kind of RAII wrapper, set `solution_result` here and put the switch in an `else` block, `goto finish`, something).
</blockquote></details>

Good call, thanks!

---

*[solvers/test/osqp_solver_test.cc, line 68 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oTmLCJtbgCAFXa76Z:-L5pIukwqCxmcm0HbfND:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/test/osqp_solver_test.cc#L68)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this actually say "QuadraticProgramTest"?  That's the name of another class which doesn't seem to be involved here.   (also the next test and "LinearProgramTest" below).
</blockquote></details>

Done.

---

*[solvers/test/osqp_solver_test.cc, line 109 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oUkVxiyha_5C1s0eS:-L5pJ1KkHeJ_QcFfczeZ:b-8byoka) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/solvers/test/osqp_solver_test.cc#L109)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW is there a reason we wrote a new test here instead of using the unbounded tests from `linear_program_examples.h`?
</blockquote></details>

Yes, I want to test an unconstrained QP, while the one in `linear_program_examples` is an unconstrained LP.

---

*[tools/install/libdrake/build_components.bzl, line 202 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-L5oNzpU6JCOKJ-VpwV7:-L5pJ_0vB_vmCKQH_cI4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d08e5b1f931042c994351a06b0d3ef4c8a84c87/tools/install/libdrake/build_components.bzl#L202)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW consider using the redundant `//drake` prefix just so the list looks consistent.  It'll get cleaned up when the rest of the file does.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5pPvsGatYV39laDzxv:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8029#-:-L5pZR4-QqVCQ2F_MvVF:b-l70wzf)*

**Pull request merged**
