### PR TITLE
Add simple USD test file

### PR DESCRIPTION
**Pull request by hong-nvidia**
Adding a simple test file to be used by USD Parser.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21086)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review / steering, please.  (Or delegate to Sean, either way.)

**Review by rpoyner-tri — COMMENTED** [review]
Welcome, @hong-nvidia ! I haven't gotten to meet you yet, and I hope you don't find the rigors of Drake code review too off-putting.  Feel free to reach out to me on Drake Slack as well: `@rpoyner-tri` there too.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21086#-:-NsJgXzs9gY27bf3FC-V:b-be567p)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hong-nvidia)

___
*[`multibody/parsing/test/usd_parser_test/box_plane.usda` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21086#-NsJhSV41j5xmOxAlY7S:-NsJhSV5-qEMwsisMWT5:b-3d9lev) ([raw file](https://github.com/RobotLocomotion/drake/blob/71c0bd6bcce7405e33c896bd045e6005bdfc8057/multibody/parsing/test/usd_parser_test/box_plane.usda#L1)):*
> ```
> #usda 1.0
> ```

This all looks legit to the untutored eye, but we try hard to observe the [Beyonce rule](https://abseil.io/resources/swe-book/html/ch11.html) (search "Beyonce" in the linked page) in Drake patches. Is there a way we can test (in CI, or possibly manually, with comments telling how?) the important property of this file -- that it is a conforming usda file? I know we are in a tricky spot, with the build system still coming on-line. 
___
*[`multibody/parsing/test/usd_parser_test/box_plane.usda` line 31 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21086#-NsJi1OY6k1SAaxJJylm:-NsJi1OY6k1SAaxJJyln:b-p6m9kx) ([raw file](https://github.com/RobotLocomotion/drake/blob/71c0bd6bcce7405e33c896bd045e6005bdfc8057/multibody/parsing/test/usd_parser_test/box_plane.usda#L31)):*
> ```
>         uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:orient", "xformOp:scale"]
>     }
>     
> ```

nit We don't like trailing whitespace -- it just invites noise into source control.

**Review by hong-nvidia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21086)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`multibody/parsing/test/usd_parser_test/box_plane.usda` line 31 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21086#-NsJi1OY6k1SAaxJJylm:-NsKHd3u0_euObExVnyV:b-wrceuf) ([raw file](https://github.com/RobotLocomotion/drake/blob/71c0bd6bcce7405e33c896bd045e6005bdfc8057/multibody/parsing/test/usd_parser_test/box_plane.usda#L31)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit We don't like trailing whitespace -- it just invites noise into source control.
</blockquote></details>

Thanks Rick for pointing this out. Is there a bazel command to detect these kind of styling issues?  ```bazel test --config lint //... ``` doesn't seem to check the USD files.

**Review by hong-nvidia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21086)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`multibody/parsing/test/usd_parser_test/box_plane.usda` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21086#-NsJhSV41j5xmOxAlY7S:-NsKIAm_-YHnB7AndVKo:bua84nd) ([raw file](https://github.com/RobotLocomotion/drake/blob/71c0bd6bcce7405e33c896bd045e6005bdfc8057/multibody/parsing/test/usd_parser_test/box_plane.usda#L1)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This all looks legit to the untutored eye, but we try hard to observe the [Beyonce rule](https://abseil.io/resources/swe-book/html/ch11.html) (search "Beyonce" in the linked page) in Drake patches. Is there a way we can test (in CI, or possibly manually, with comments telling how?) the important property of this file -- that it is a conforming usda file? I know we are in a tricky spot, with the build system still coming on-line.
</blockquote></details>

We can potentially leverage the `usdchecker` program that came with USD build and write a test case to ensure that it is a conforming usda file. Let me look into how to implement that.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21086)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hong-nvidia)

___
*[`multibody/parsing/test/usd_parser_test/box_plane.usda` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21086#-NsJhSV41j5xmOxAlY7S:-NsKe-MU6P1FgvRui-xQ:bo6wjpo) ([raw file](https://github.com/RobotLocomotion/drake/blob/71c0bd6bcce7405e33c896bd045e6005bdfc8057/multibody/parsing/test/usd_parser_test/box_plane.usda#L1)):*
<details><summary><i>Previously, hong-nvidia wrote…</i></summary><blockquote>

We can potentially leverage the `usdchecker` program that came with USD build and write a test case to ensure that it is a conforming usda file. Let me look into how to implement that.
</blockquote></details>

meta Reviewable tip: when you are planning to do work toward resolving a conversation, you can click on the little pile of circles to the right, find your avatar, click it, and then set your status as "Working". This will mean that you get red highlights in your dashboard for that discussion, but no one else does until your change your status again.
___
*[`multibody/parsing/test/usd_parser_test/box_plane.usda` line 31 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21086#-NsJi1OY6k1SAaxJJylm:-NsKccpd0ZLXOTeKIjbl:bbu1k3r) ([raw file](https://github.com/RobotLocomotion/drake/blob/71c0bd6bcce7405e33c896bd045e6005bdfc8057/multibody/parsing/test/usd_parser_test/box_plane.usda#L31)):*
<details><summary><i>Previously, hong-nvidia wrote…</i></summary><blockquote>

Thanks Rick for pointing this out. Is there a bazel command to detect these kind of styling issues?  ```bazel test --config lint //... ``` doesn't seem to check the USD files.
</blockquote></details>

I don't know of one in our `bazel` world. You can use something like `git show --check` on your commits locally; it will complain about trailing whitespace.

I use `emacs` editor tricks in my own work. 

As for prospects of implementing new linters? I'm not sure. We are pretty tough on code formatting (C, Python), but we have not put as much emphasis on data files.

**Comment by hong-nvidia** [comment]
This particular test file is included as a part of another upcoming MR, which covers some of the issues discussed here (e.g., test case to check the validity of the file itself). Therefore, I'm closing this one. Thanks all for the help!

**Pull request closed without merging**
