### PR TITLE
workspace: Add dependency on pygame

### LINKED ISSUE #13379: Add dependency on pygame
We landed `end_effector_teleop_sliders` (#10632) when Drake still supported python2 and python3, so we had CI coverage of the code in the python2 builds.  Since that point, we've dropped python2 support.  And so, this comment becomes relevant:

> For my part, I [Jeremy] would be okay if the end_effector_teleop_mouse landed on master with a disclaimer that it only works on python2 on Ubuntu + an error message if the user tries to run it on Ubuntu with python3 anyway. In a year(?) from now when we drop support for python2 we'll have to remove the program if nobody steps up to upgrade it to python3, but we can cross that bridge when we come to it. There's every chance someone gets python3-pygame working in Drake in the meantime.

-- https://github.com/RobotLocomotion/drake/pull/10632#issuecomment-463290730

As far as I can tell from a quick look, we still have no pygame in Drake, and its not available in Ubuntu.

I'd like to avoid untested, dead code living on master.  We could imagine stubbing `import pygame` with an inert fill, so that the code still runs but receives no input -- then at least we'd have some statement coverage in the `--test` mode.  However, that doesn't let users actually use it, it just helps mitigate bitrot.

Does macOS offer pygame?  Maybe we could enable for users it there, and have only the test work on Ubuntu.

\CC @RussTedrake @sammy-tri @peteflorence looking for your suggestions here.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #13379.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13381)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@jamiesnape Am I inferring correctly in #13031 that homebrew python 3.8 does not have pygame?  Is there anything we should do in this PR to enable mouse teleop on macOS?  Or should we defer it to a follow-up once homebrew settles down with 3.8 as the default?

**Comment by jamiesnape** [comment]
There was not a wheel for pygame for Python 3.8  on macOS in PyPI and and compiling from source brought in some heavyweight dependencies and took a long time.

We should defer to work out a solution. Homebrew switching to Python 3.8 may prompt them to support it, but no guarantee.

**Comment by jamiesnape** [comment]
`2.0.0.dev8` does have 3.8 wheels, it appears.

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Pull request merged**
