### PR TITLE
Add error guidance to Get*Port methods.

### PR DESCRIPTION
**Pull request by ggould-tri**
Relates #14426

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17255)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@rpoyner-tri for feature review, since he's had to sit through me ranting so much about this in the past.

Sample text before:
```
unknown file: Failure
C++ exception with description "System hub does not have an input port named lcmt_iiwa_status" thrown in the test body.
```
after:
```
unknown file: Failure
C++ exception with description "System hub does not have an input port named lcmt_iiwa_status (valid port names:  iiwa.position iiwa.torque jaco.state jaco.position jaco.velocity panda.position)" thrown in the test body.
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17255#-:-N2qdRA90NnGF5BTM2Yt:b-jmhbwz)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review by schedule.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17255#-:-N2rTI6H-y2smU5W_9Ys:brisyb)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17255)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @ggould-tri)

___
*[`systems/framework/system.cc` line 650 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17255#-N2rUh9X6VZ0p1UEszZp:-N2rUh9X6VZ0p1UEszZq:bvifb4j) ([raw file](https://github.com/robotlocomotion/drake/blob/154dff3407a44df6962e0fc4edd7083d181dae47/systems/framework/system.cc#L650)):*
> ```cpp
>     }
>   }
>   std::string error = ("System " + GetSystemName()
> ```

Even though error messages are not performance-critical, I don't think it's valid to have a quadratic runtime here.  If there's a user with a lot of port names (e.g., a lot of model instances in an MbP), this could easily accidentally take several seconds or minutes.

Here's a rough cut at half of the fix:

```patch
--- a/systems/framework/system.cc
+++ b/systems/framework/system.cc
@@ -4,6 +4,8 @@
 #include <ios>
 #include <regex>
 #include <set>
+#include <string_view>
+#include <vector>
 
 #include "drake/common/unused.h"
 #include "drake/systems/framework/system_visitor.h"
@@ -647,18 +649,18 @@ const InputPort<T>& System<T>::GetInputPort(
       return get_input_port(i);
     }
   }
-  std::string error = ("System " + GetSystemName()
-                       + " does not have an input port named " + port_name);
-  if (num_input_ports() == 0) {
-    error += " (it has no input ports)";
-  } else {
-    error += " (valid port names: ";
-    for (InputPortIndex i{0}; i < num_input_ports(); i++) {
-      error += " " + get_input_port_base(i).get_name();
-    }
-    error += ")";
+  std::vector<std::string_view> port_names;
+  port_names.reserve(num_input_ports());
+  for (InputPortIndex i{0}; i < num_input_ports(); i++) {
+    port_names.push_back(get_input_port_base(i).get_name());
   }
-  throw std::logic_error(error);
+  if (port_names.empty()) {
+    port_names.push_back("it has no input ports");
+  }
+  throw std::logic_error(fmt::format(
+      "System {} does not have an input port named {}"
+      " (valid port names: {})",
+      GetSystemName(), port_name, fmt::join(port_names, ", ")));
 }
 
 template <typename T>
--- a/systems/framework/test/system_test.cc
+++ b/systems/framework/test/system_test.cc
@@ -470,7 +470,7 @@ TEST_F(SystemTest, PortNameTest) {
 TEST_F(SystemTest, PortNameNoPortsTest) {
   DRAKE_EXPECT_THROWS_MESSAGE(
       system_.GetInputPort("not_my_input"),
-      ".* \\(it has no input ports\\)");
+      ".*it has no input ports.*");
   DRAKE_EXPECT_THROWS_MESSAGE(
       system_.GetOutputPort("not_my_output"),
       ".* \\(it has no output ports\\)");
```
___
*[`systems/framework/test/system_test.cc` line 464 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17255#-N2rUO2RBW09Gka7t3ue:-N2rUO2SCXZlAr2zGI64:bbdtotf) ([raw file](https://github.com/robotlocomotion/drake/blob/154dff3407a44df6962e0fc4edd7083d181dae47/systems/framework/test/system_test.cc#L464)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       system_.GetInputPort("not_my_input"),
>       ".*my_input.*");
> ```

nit This regex is brittle.  If the DUT said "Could not find not_my_input", the regex would still pass.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17255)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`systems/framework/system.cc` line 650 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17255#-N2rUh9X6VZ0p1UEszZp:-N2rdiLk9RRCLGGcNBuM:b-t2eklp) ([raw file](https://github.com/robotlocomotion/drake/blob/154dff3407a44df6962e0fc4edd7083d181dae47/systems/framework/system.cc#L650)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Even though error messages are not performance-critical, I don't think it's valid to have a quadratic runtime here.  If there's a user with a lot of port names (e.g., a lot of model instances in an MbP), this could easily accidentally take several seconds or minutes.

Here's a rough cut at half of the fix:

```patch
--- a/systems/framework/system.cc
+++ b/systems/framework/system.cc
@@ -4,6 +4,8 @@
 #include <ios>
 #include <regex>
 #include <set>
+#include <string_view>
+#include <vector>
 
 #include "drake/common/unused.h"
 #include "drake/systems/framework/system_visitor.h"
@@ -647,18 +649,18 @@ const InputPort<T>& System<T>::GetInputPort(
       return get_input_port(i);
     }
   }
-  std::string error = ("System " + GetSystemName()
-                       + " does not have an input port named " + port_name);
-  if (num_input_ports() == 0) {
-    error += " (it has no input ports)";
-  } else {
-    error += " (valid port names: ";
-    for (InputPortIndex i{0}; i < num_input_ports(); i++) {
-      error += " " + get_input_port_base(i).get_name();
-    }
-    error += ")";
+  std::vector<std::string_view> port_names;
+  port_names.reserve(num_input_ports());
+  for (InputPortIndex i{0}; i < num_input_ports(); i++) {
+    port_names.push_back(get_input_port_base(i).get_name());
   }
-  throw std::logic_error(error);
+  if (port_names.empty()) {
+    port_names.push_back("it has no input ports");
+  }
+  throw std::logic_error(fmt::format(
+      "System {} does not have an input port named {}"
+      " (valid port names: {})",
+      GetSystemName(), port_name, fmt::join(port_names, ", ")));
 }
 
 template <typename T>
--- a/systems/framework/test/system_test.cc
+++ b/systems/framework/test/system_test.cc
@@ -470,7 +470,7 @@ TEST_F(SystemTest, PortNameTest) {
 TEST_F(SystemTest, PortNameNoPortsTest) {
   DRAKE_EXPECT_THROWS_MESSAGE(
       system_.GetInputPort("not_my_input"),
-      ".* \\(it has no input ports\\)");
+      ".*it has no input ports.*");
   DRAKE_EXPECT_THROWS_MESSAGE(
       system_.GetOutputPort("not_my_output"),
       ".* \\(it has no output ports\\)");
```
</blockquote></details>

Done.
TIL:  `fmt::join`  :-)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17255#-:-N2rgLIw8ulp3Q8qXjfh:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @ggould-tri)

**Comment by jwnimmer-tri** [comment]
+(release notes: yes) "Improve error messages for incorrect port names" is a notable UX improvement.

**Pull request merged**
