### PR TITLE
MosekSolver sets logging using CommonSolverOption

### PR DESCRIPTION
**Pull request by hongkai-dai**
This is a re-submission of the reverted PR #15360

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15382)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-continuous-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-continuous-everything-leak-sanitizer please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-continuous-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-continuous-everything-leak-sanitizer please

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri could you do both the feature and the platform review (since you did the platform review for the previous PR #15360)? This PR hasn't made any feature change from #15360

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15382#-:-MeTQdA87YyvawjkNG6U:b-66ymgv)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15382#-:-MeUqGxAB_u4rMiKEmmH:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Pull request merged**
