### PR TITLE
Pull in the `fmt` string formatting library as a proper external dependency... again.

### PR DESCRIPTION
**Pull request by maddog-tri**
This is a resubmission of #5607, which was reverted due to failing MacOS builds in CI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5669)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm: as a resubmit without re-review.  Be sure to check the OSX build.

**Comment by maddog-tri** [comment]
What is the magic invocation to "check the OSX build"?

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5669#-:-KgVEFeWzTPSJaYCsY8P:b-cz0o38)*

**Comment by maddog-tri** [comment]
And, does your LGTM count for both 'feature' and 'platform', or just one or the other?

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5669#-:-KgVELHYdheXgjK9mBi_:b-vdf50f)*

**Comment by liangfok** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please.

**Comment by jwnimmer-tri** [comment]
http://drake.mit.edu/jenkins.html#running-an-on-demand-build is the broad info; here we just post like this:

@drake-jenkins-bot mac-clang-experimental please

**Comment by jwnimmer-tri** [comment]
I don't think we need any more reviewers on this PR, once builds pass it's okay.

**Comment by maddog-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5669#-:-KgVNEFU31KVzlkTOI9J:b-1hejgk)*

**Comment by maddog-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5669#-:-KgVXUHS67MwqMYRnGc1:bp1laq6)*

**Comment by maddog-tri** [comment]
-(status: do not review) -(status: curate commits before merging) 

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5669#-:-KgVaPin9Kefr2X1n5--:bwsw6p)*

**Pull request merged**
