### PR TITLE
refactor and update LQR interface

### PR DESCRIPTION
**Pull request by RussTedrake**
per the design doc discussion

@siyuanfeng-tri for feature review
@sammy-tri for platform

@siyuanfeng-tri -- I know you want S to come out, too.  happy to have you add it on top of this (couldn't quite get to it this morning).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4308)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
gladly, will review after we put val together.

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/linear_quadratic_regulator.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4308#-KXpsVkQEPC-gyBAsMDw:-KXpsVkQEPC-gyBAsMDx:bxwk2cs) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e63a4561f0fdebe55c27e76daddd59a7a57f7f/drake/systems/controllers/linear_quadratic_regulator.cc#L15)):*
> ```cpp
>     const Eigen::Ref<const Eigen::MatrixXd>& Q,
>     const Eigen::Ref<const Eigen::MatrixXd>& R) {
>   const auto& S = ContinuousAlgebraicRiccatiEquation(A, B, Q, R);
> ```

BTW, since I need to touch this again soon, I am proposing to do chol only once, and maybe have that passed in. it's also easier to check R being psd. 

---

*[drake/systems/controllers/linear_quadratic_regulator.cc, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4308#-KXptOciy-co-uee7n5C:-KXptOciy-co-uee7n5D:bp8nny8) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e63a4561f0fdebe55c27e76daddd59a7a57f7f/drake/systems/controllers/linear_quadratic_regulator.cc#L72)):*
> ```cpp
> }
> 
> Eigen::MatrixXd ContinuousAlgebraicRiccatiEquation(
> ```

BTW, i will also add a version with A, B, Q, R, N. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4308#-:-KXpunRPal5gKpCURfaE:bnfp4nl)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm: pending commit curation and resolution of outstanding issues

---

Reviewed 10 of 11 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/linear_quadratic_regulator.cc, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4308#-KXuq9HXJ2nonOp2jno-:-KXuq9HXJ2nonOp2jno0:b-ae824f) ([raw file](https://github.com/robotlocomotion/drake/blob/8f38b011e8e9c87f286edefc741e7eae86593c7b/drake/systems/controllers/linear_quadratic_regulator.cc#L15)):*
> ```cpp
>     const Eigen::Ref<const Eigen::MatrixXd>& Q,
>     const Eigen::Ref<const Eigen::MatrixXd>& R) {
>   const auto& S = ContinuousAlgebraicRiccatiEquation(A, B, Q, R);
> ```

I don't think this should be a ref since ContinuousAlgebraicRiccatiEquation returns a matrix by value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4308#-:-KXupdD8Hbu69VU8KGk-:b5riplm)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/controllers/linear_quadratic_regulator.cc, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4308#-KXuq9HXJ2nonOp2jno-:-KXurjtT0t_GnVUeIaN9:bdegoy) ([raw file](https://github.com/robotlocomotion/drake/blob/8f38b011e8e9c87f286edefc741e7eae86593c7b/drake/systems/controllers/linear_quadratic_regulator.cc#L15)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think this should be a ref since ContinuousAlgebraicRiccatiEquation returns a matrix by value.
</blockquote></details>

BTW A _const ref_ works okay (due to temporary capture) but if that's the desire it should be `MatrixXd` and not `auto` for clarity, because its important that the captured temporary is a value (Matrix) not pseudo-reference (Eigen::Ref, CWiseOp, etc.).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4308)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please

**Comment by RussTedrake** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/linear_quadratic_regulator.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4308#-KXpsVkQEPC-gyBAsMDw:-KY0xU-lRSYqzLNX9vzp:b-dc9xm1) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e63a4561f0fdebe55c27e76daddd59a7a57f7f/drake/systems/controllers/linear_quadratic_regulator.cc#L15)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, since I need to touch this again soon, I am proposing to do chol only once, and maybe have that passed in. it's also easier to check R being psd. 
</blockquote></details>

I wouldn't force the user to pass the chol in to the LQR methods.  that seems like a violation of the clean API.  perhaps it's ok to pass that into CARE?  not sure if I like that, either...

We might have cheaper checks for PSD, but since we need the inverse anyhow, this seemed reasonable.

---

*[drake/systems/controllers/linear_quadratic_regulator.cc, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4308#-KXptOciy-co-uee7n5C:-KY0xy2wbNURdrJGRDi8:bba7uhv) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e63a4561f0fdebe55c27e76daddd59a7a57f7f/drake/systems/controllers/linear_quadratic_regulator.cc#L72)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, i will also add a version with A, B, Q, R, N. 
</blockquote></details>

awesome!

---

*[drake/systems/controllers/linear_quadratic_regulator.cc, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4308#-KXuq9HXJ2nonOp2jno-:-KY0wtXDFtX2QFHZNxn5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8f38b011e8e9c87f286edefc741e7eae86593c7b/drake/systems/controllers/linear_quadratic_regulator.cc#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW A _const ref_ works okay (due to temporary capture) but if that's the desire it should be `MatrixXd` and not `auto` for clarity, because its important that the captured temporary is a value (Matrix) not pseudo-reference (Eigen::Ref, CWiseOp, etc.).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4308)*

**Pull request merged**
