### PR TITLE
[multibody] Tidy up attorney declaration order

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Noted while adding one more forwarded function dur #15161.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15193)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for feature review, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:  thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15193#-:-McFiH0Y3WHpFTsY3iEu:btapcqv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15193)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15193#-:-McG3tp-2PpESa-Alff2:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15193)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Sufficient builds has passed, so I'm forcing in now -- this is a merge conflict hazard I've had to rebase a few times already.

**Pull request merged**
