### PR TITLE
Some infrastructure to work with cache entries.

### PR DESCRIPTION
**Pull request by amcastro-tri**
This is an excerpt from #5947 with a number of refinements based on the reviewers comments.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5984)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@sherm1 for feature please since you are working on system's caching.
+@jwnimmer-tri for platform/feature please since you provided a number of good pointers in #5947 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-Kj3_EJD5dg5plyqghON:b-aeqs5a)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri I refuse to participate in this fiasco without a design document front and center.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-Kj3a2oc17ajVRbe96n_:bf3gocu)*

**Comment by sherm1** [comment]
I will make a design doc for discussion of upcoming caching changes after the output port separation, which is a prerequisite. @amcastro-tri  is not trying to redesign the existing cache system here. This adds some missing methods to the *existing* partial implementation so he can proceed with the MultibodyTree implementation using an actual Context rather than having to mock one up himself. The existing cache pieces were already designed and reviewed; these are not significant changes.  @amcastro-tri, is this the minimal change to the existing cache you need?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-Kj3fdx14k1ed3o-izDQ:bxn10ql)*

**Comment by jwnimmer-tri** [comment]
> the existing partial implementation ... existing cache pieces were already designed and reviewed ...

... and to me the existing pieces seem broken, so I need a design document before I'm convinced that we should be using them in any way.

**Comment by sherm1** [comment]
> to me the existing pieces seem broken

Well yes, I agree. But there are some basic caching features that the MultibodyTree code needs to assume and the existing code has some of that in workable form -- there will be abstract valued cache entries stored in the Context, it will be possible to obtain mutable reference to that data, and there will be a need to mark the cache entry valid after an extended computation has been performed to bring it up to date. A set() method alone will not be adequate for large cache entries like the ones MBTree needs. We have had considerable design discussion around the MultibodyContext (used everywhere in the API) and wanted to use the existing Context for it rather than have @amcastro-tri mock up a separate implementation. We don't need any actual caching to make progress on MBTree; just the very basic data access stuff so that we can get the cached data structures out of the MBContext and put results back there.

I think there is much repair needed to the handling of dependencies and that deserves a good discussion. But Alejandro is not doing anything with that here. I would really like to be able to move forward on MBTree with cache details decoupled.

**Comment by jwnimmer-tri** [comment]
I have not posted any defects; you all are free to move ahead.  You just need to find a platform reviewer willing to believe the above arguments.

**Comment by amcastro-tri** [comment]
@jwnimmer-tri, I have to say that I am highly disappointed in the way you addressed your comments in both #5947 and in this PR (among others). On the one hand you seem to be interested on the success of these endeavours but on the other hand the sometimes even aggressive tone you use in your comments suggests quite the opposite. I'd be happy to work with you on making this happen, but please lets do so within the collaborative and cooperative environment that this research institution is trying to build upon.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-Kj3zR0e8dysZqTztZgU:b-2n1v7m)*

**Comment by sherm1** [comment]
Feature review: this is all consistent with the existing cache implementation and looks fine to me for purposes of getting the MultibodyTree code working. We will revisit with the bigger-picture caching project that includes ports, time, derivatives, etc. :lgtm: except for one small bug, PTAL.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/cache.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj4n_qII7EfA9c5lcWr:-Kj4n_qII7EfA9c5lcWs:b-ug7z06) ([raw file](https://github.com/robotlocomotion/drake/blob/8c84cf988eb2bb0ae9838a47fe816b16fef2321f/drake/systems/framework/cache.cc#L57)):*
> ```cpp
>   DRAKE_DEMAND(ticket >= 0 && ticket < static_cast<int>(store_.size()));
>   store_[ticket].set_is_valid(true);
>   InvalidateRecursively(store_[ticket].dependents());
> ```

You should not call invalidate here. All invalidation must have been performed at the time you obtained mutable access to the cache entry. Here it is only necessary to say you are done with the computation -- the downstream dependents are already invalid.

---

*[drake/systems/framework/leaf_context.h, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj4sl4mfxc4gTchCg3c:-Kj4sl4nqXYtPldWgITV:b-s81zt0) ([raw file](https://github.com/robotlocomotion/drake/blob/8c84cf988eb2bb0ae9838a47fe816b16fef2321f/drake/systems/framework/leaf_context.h#L163)):*
> ```objc
> 
>   /// Validates the cache entry corresponding to the provided @p ticket and
>   /// recursively invalidates all dependents.
> ```

Should not invalidate anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-Kj4u_4n0sAV6XutPS_-:b-gc8kzy)*

**Comment by amcastro-tri** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/cache.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj4n_qII7EfA9c5lcWr:-Kj9POSU_1WW9OUh2Zpm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c84cf988eb2bb0ae9838a47fe816b16fef2321f/drake/systems/framework/cache.cc#L57)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

You should not call invalidate here. All invalidation must have been performed at the time you obtained mutable access to the cache entry. Here it is only necessary to say you are done with the computation -- the downstream dependents are already invalid.
</blockquote></details>

Done.

---

*[drake/systems/framework/leaf_context.h, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj4sl4mfxc4gTchCg3c:-Kj9PcAE8Lhew7PxrvLr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c84cf988eb2bb0ae9838a47fe816b16fef2321f/drake/systems/framework/leaf_context.h#L163)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Should not invalidate anything.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984)*

**Comment by sherm1** [comment]
:lgtm: but added a few BTWs, ptal.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/cache.h, line 189 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj9UINkgy2JS0iwWeBb:-Kj9UINkgy2JS0iwWeBc:b-17yw5h) ([raw file](https://github.com/robotlocomotion/drake/blob/1bf92b3af126a82f8a3fc02faa546966217acae1/drake/systems/framework/cache.h#L189)):*
> ```objc
>   /// invalid if the ticket's prerequisites are modified.
>   ///
>   /// @warning It is responsability of the caller to call validate() on this
> ```

BTW responsability->responsibility 

---

*[drake/systems/framework/cache.h, line 192 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj9UdMInuGGOZg9NONr:-Kj9UdMInuGGOZg9NONs:bajlvyz) ([raw file](https://github.com/robotlocomotion/drake/blob/1bf92b3af126a82f8a3fc02faa546966217acae1/drake/systems/framework/cache.h#L192)):*
> ```objc
>   /// entry once done with the necessary updates. Failure to do so will have no
>   /// effect on the final result of the computation, but it might have an impact
>   /// on efficiency since the entry will be recomputed every time is accessed.
> ```

BTW I think we will be able to detect failure to validate in many cases and blow up the simulation. I suggest being less specific here.

---

*[drake/systems/framework/leaf_context.h, line 153 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj9UtALF17XI_BztB1U:-Kj9UtALF17XI_BztB1V:bv883f) ([raw file](https://github.com/robotlocomotion/drake/blob/1bf92b3af126a82f8a3fc02faa546966217acae1/drake/systems/framework/leaf_context.h#L153)):*
> ```objc
>   /// have no effect on the final result of the computation, but it might have
>   /// an impact on efficiency since the entry will be recomputed every time is
>   /// accessed.
> ```

BTW typo, and same comment as before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-Kj9V9aZaVKpRdD3YwSc:bh0mefc)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/cache.h, line 189 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj9UINkgy2JS0iwWeBb:-Kj9icvG7U_1mWwxEujj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1bf92b3af126a82f8a3fc02faa546966217acae1/drake/systems/framework/cache.h#L189)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW responsability->responsibility 
</blockquote></details>

Done.

---

*[drake/systems/framework/cache.h, line 192 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj9UdMInuGGOZg9NONr:-KjEi6wq1R38dLe4ljLw:b-lhck3w) ([raw file](https://github.com/robotlocomotion/drake/blob/1bf92b3af126a82f8a3fc02faa546966217acae1/drake/systems/framework/cache.h#L192)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I think we will be able to detect failure to validate in many cases and blow up the simulation. I suggest being less specific here.
</blockquote></details>

BTW. True, this warning will go out of date when we have a validation mechanism in place. I therefore removed it.

---

*[drake/systems/framework/leaf_context.h, line 153 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-Kj9UtALF17XI_BztB1U:-KjEiKkf9cnV-qkEXkbU:b-lhck3w) ([raw file](https://github.com/robotlocomotion/drake/blob/1bf92b3af126a82f8a3fc02faa546966217acae1/drake/systems/framework/leaf_context.h#L153)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW typo, and same comment as before.
</blockquote></details>

BTW. True, this warning will go out of date when we have a validation mechanism in place. I therefore removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984)*

**Comment by amcastro-tri** [comment]
+@ggould-tri for platform please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-KjF3tPEq4tJEqJsMgt3:b-z1mnxk)*

**Comment by ggould-tri** [comment]
I cannot make head or tail of what is going on here.  I will try to review this, but it may take me some time.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-KjIWWp-C8DnU9oxOrKR:be8cqo8)*

**Comment by ggould-tri** [comment]
Some comments below that amount to an alternative design proposal for the cache change.  As I understand it, the pattern you envision is (skipping over some casting details):
```
Thingy* scratchpad = cache.GetMutable(my_ticket);
scratchpad->frobnicate();
cache.validate(my_ticket);
```
As you note, this is dangerous -- notably (1) if the frobbing step is complicated you could validate while mistaken about what is in place in the cache and (2) you are left holding a mutable alias to a valid cache entry, which is pretty much a stick of dynamite with a lit fuse.

I propose instead:
```
unique_ptr<Thingy> scratchpad = cache.GetMutable(my_ticket);  // I propose that GetMutable returns a unique_ptr.
scratchpad->frobnicate();  // No change to the update semantics.
cache.Init(my_ticket, scratchpad);  // unique_ptr(unique_ptr) ctor invalidates your mutable reference.  Or use std::move().
```
This saves you a method (`validate()` goes away) and eliminates or discourages the two most obvious usage errors.  It is a bit wordier, but as you say this is an experts-only pattern anyway (and also it might clean up a bit with `auto`).

How does this sound to you?

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/cache.cc, line 86 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-KjIcWn10V-bsajq3f1n:-KjIcWn2V3L8ucJ7QrI8:b-exiylr) ([raw file](https://github.com/robotlocomotion/drake/blob/cb3dba6c5c9c58899284c4d3dd539b61d07e7cb6/drake/systems/framework/cache.cc#L86)):*
> ```cpp
> }
> 
> AbstractValue* Cache::GetMutable(CacheTicket ticket) {
> ```

This should demand that the ticket is valid or return null on an invalid ticket like `Get()` does.

---

*[drake/systems/framework/cache.h, line 135 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-KjIe52tLPh5QjcDWQ9u:-KjIe52udsogxEXVpHYU:bp4eike) ([raw file](https://github.com/robotlocomotion/drake/blob/cb3dba6c5c9c58899284c4d3dd539b61d07e7cb6/drake/systems/framework/cache.h#L135)):*
> ```objc
>   /// the necessary updates to the entry and finally, validate it with a call to
>   /// this method.
>   ///
> ```

A user could retain a mutable pointer to the item across a call to `validate()` and there is no way for the cache to detect this and re-invalidate.

At minimum you need to comment here that callers *MUST* discard the mutable pointer when calling validate.

However if that is the case then, see below, `Init()` is probably better in all cases.

---

*[drake/systems/framework/cache.h, line 137 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-KjIe6I0vHUeZQ9zFh6I:-KjIe6I0vHUeZQ9zFh6J:baukjfk) ([raw file](https://github.com/robotlocomotion/drake/blob/cb3dba6c5c9c58899284c4d3dd539b61d07e7cb6/drake/systems/framework/cache.h#L137)):*
> ```objc
>   ///
>   /// @warning Only advanced, careful users should call this method since
>   /// validating cache entries by hand can be error prone. Use with care.
> ```

Can you be more specific about the sorts of problems that need to be avoided?

Also, "error-prone" is a compound modifier that should be spelled with a hyphen.

---

*[drake/systems/framework/cache.h, line 138 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-KjIerW_gt8mmL6WL30e:-KjIerWauxuUXWMHw0OV:b2afhof) ([raw file](https://github.com/robotlocomotion/drake/blob/cb3dba6c5c9c58899284c4d3dd539b61d07e7cb6/drake/systems/framework/cache.h#L138)):*
> ```objc
>   /// @warning Only advanced, careful users should call this method since
>   /// validating cache entries by hand can be error prone. Use with care.
>   void validate(CacheTicket ticket);
> ```

BTW -- I wonder if it would not make more sense for callers to use Init() in all cases.  Presumably the caller has the value pointer at hand, and passing it as a `unique_ptr` would force them to relinquish it.  Moreover a lot of possible errors resulting from the caller being wrong about what value was being validated would become impossible.

---

*[drake/systems/framework/cache.h, line 188 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-KjIfS92z2Xz1op-7DrI:-KjIfS92z2Xz1op-7DrJ:b-5dgub3) ([raw file](https://github.com/robotlocomotion/drake/blob/cb3dba6c5c9c58899284c4d3dd539b61d07e7cb6/drake/systems/framework/cache.h#L188)):*
> ```objc
>   /// @warning The bare pointer should not be held, because the data may become
>   /// invalid if the ticket's prerequisites are modified.
>   AbstractValue* GetMutable(CacheTicket ticket);
> ```

Why not return a `unique_ptr<AbstractValue>` here?  The cache entry is going to be invalid anyway, and you could then require that the value be returned to the cache later, discouraging retention of the mutable alias.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-KjIgOvbSdAnHSfMCyG5:bfyasfy)*

**Comment by amcastro-tri** [comment]
Very nice analysis @ggould-tri, thanks! I really like this usage of `unique_ptr` you are suggesting. Now going through the codebase I see David had a `CacheEntry::release_value()` (unused so far) which makes me think he was considering this workflow already. I will try these ideas and see how they play out.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5984#-:-KjIqWUOJiFSmgmmYPSg:b-undd0l)*

**Comment by amcastro-tri** [comment]
Per discussion with @jwnimmer-tri, @ggould-tri and @sherm1; System's caching is still in its infancy and probably it is not wise to start using it as is now. For MBT I will just focus on API's and correctness, recomputing these (soon to become) cache structures when needed.

**Pull request closed without merging**
