### PR TITLE
[multibody] Fix dmd default_free_body_pose vs offset frames

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Noticed while developing #21765.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21854)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With requests for notes to future maintainers.

+@sherm1 for platform, please.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21854#-:-O5PGpGdAV7B-okgdWbb:ba9uh5f)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`multibody/parsing/detail_dmd_parser.cc` line 100 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21854#-O5PCwzF8tfe1EkV5uDp:-O5PCwzF8tfe1EkV5uDq:b-v94r62) ([raw file](https://github.com/RobotLocomotion/drake/blob/3942e68700ed361e800cde30889b866f0a199ab0/multibody/parsing/detail_dmd_parser.cc#L100)):*
> ```cpp
>           // If the parent frame is the world and the child frame is coincident
>           // with the body frame, then we can use the function to posture a body
>           // without first adding a joint.
> ```

nit: This is where I'd like a comment that acknowledges that if the frame's offset pose gets subsequently changed, the default pose will no longer be correct, but we consider the risk of that small compared to the cost of injecting largely unhelpful joints in the name of eliminating the risk.

In other words, we're not suggesting this code is "correct", we're suggesting it's "reasonable".
___
*[`multibody/parsing/test/detail_dmd_parser_test.cc` line 251 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21854#-O5PGCWx8VbIrlnU_giy:-O5PGCWx8VbIrlnU_giz:byp6i9g) ([raw file](https://github.com/RobotLocomotion/drake/blob/3942e68700ed361e800cde30889b866f0a199ab0/multibody/parsing/test/detail_dmd_parser_test.cc#L251)):*
> ```cpp
>        "WorldModelInstance::world",
>        "pose_frame_to_world_9::base_offset"},
>       // All other joints were added during Finalize.
> ```

BTW The joints instantiated by finalize are in a non-intuitive order (in contrast to those created as part of the directives). It might be worth noting how that order was determined and what it would take to maintain its correctness.

I assume, it was derived empirically and if construction of the tree changes ordering under the hood, it is sufficient to re-order these to match.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21854)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21854#-:-O5Pud-X-sfu7SJzqWBE:b8qx53o)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Pull request merged**
