### PR TITLE
Update lcm submodule

### LINKED ISSUE #2924: Every build is failing during LCM checkout
```
fatal: reference is not a tree: 9c9e22cf23663ef9cd0e5ec83932ff7f70cd7b18
Unable to checkout '9c9e22cf23663ef9cd0e5ec83932ff7f70cd7b18' in submodule path 'externals/lcm'
```

https://drake-jenkins.csail.mit.edu/view/Continuous/

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #2924.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2928)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2928#-:-KNYp0cODQzoKq7WchSF:1417088721)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2928#-:-KNYphuHqiFBOEeH3MLQ:-1868698381)*

**Comment by jamiesnape** [comment]
Looks like at least one build has successful checked out and built the new hash, so in the interests of unblocking every single build, merging now.

**Comment by mwoehlke-kitware** [comment]
Argh, stupid github... deleting the branch that was merged upstream made it disappear *entirely* because I hadn't pushed upstream's master into my repo (done now; anyone on older drake should be able to access the old SHA again).

Ah, well, this brings in lcm-proj/lcm#90 also, which is useful.

Sorry for the trouble!

**Pull request merged**
