### PR TITLE
Simplify PoseAggregator transmogrification

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This implementation should make the invariants more clear and be slightly less brittle.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5920)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

Is this PR an improvement?  It wasn't quite as elegant as I'd expected, but hopefully its an incremental bit better.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-:-KiKXvhLRlKb5Snw0Jl5:bun1ia)*

**Comment by liangfok** [comment]
:lgtm: Yes, I think this is an improvement.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/rendering/pose_aggregator.h, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-KiKyee6aXNd7a37EdJg:-KiKyee6aXNd7a37EdJh:bhkyay1) ([raw file](https://github.com/robotlocomotion/drake/blob/36f36563dbe1aae4e3eaf585304e8cc2d9dfc14b/drake/systems/rendering/pose_aggregator.h#L144)):*
> ```objc
> namespace pose_aggregator_detail {
> 
> // A private data structure of PoseAggrecator.  It is not nested within
> ```

Typo: PoseAggregator

---

*[drake/systems/rendering/pose_aggregator.h, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-KiKyhyENCz3z0pIW2t_:-KiKyhyENCz3z0pIW2ta:btmgrwj) ([raw file](https://github.com/robotlocomotion/drake/blob/36f36563dbe1aae4e3eaf585304e8cc2d9dfc14b/drake/systems/rendering/pose_aggregator.h#L145)):*
> ```objc
> 
> // A private data structure of PoseAggrecator.  It is not nested within
> // PoseAggregator because does not (and should not) depend on the type
> ```

BTW, missing "it" before "does".

---

*[drake/systems/rendering/pose_aggregator.h, line 148 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-KiKyZglWuCzliWRdZpS:-KiKyZglWuCzliWRdZpT:b-bm8o09) ([raw file](https://github.com/robotlocomotion/drake/blob/36f36563dbe1aae4e3eaf585304e8cc2d9dfc14b/drake/systems/rendering/pose_aggregator.h#L148)):*
> ```objc
> // parameter @p T.
> struct InputRecord {
>   enum PoseInputType {
> ```

BTW, should this be `enum class PoseInputType`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-:-KiKzKSCB-tAz0fqxU72:b-70e5kq)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/rendering/pose_aggregator.h, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-KiKyee6aXNd7a37EdJg:-KiN1Ei7dypwy2v2xlfu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36f36563dbe1aae4e3eaf585304e8cc2d9dfc14b/drake/systems/rendering/pose_aggregator.h#L144)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Typo: PoseAggregator
</blockquote></details>

Done.

---

*[drake/systems/rendering/pose_aggregator.h, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-KiKyhyENCz3z0pIW2t_:-KiN1JgZ7VBkVSyGN5Ot:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36f36563dbe1aae4e3eaf585304e8cc2d9dfc14b/drake/systems/rendering/pose_aggregator.h#L145)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing "it" before "does".
</blockquote></details>

Done.

---

*[drake/systems/rendering/pose_aggregator.h, line 148 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-KiKyZglWuCzliWRdZpS:-KiN1KDeWEx0_R5bIAuO:b-hvuc9) ([raw file](https://github.com/robotlocomotion/drake/blob/36f36563dbe1aae4e3eaf585304e8cc2d9dfc14b/drake/systems/rendering/pose_aggregator.h#L148)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should this be `enum class PoseInputType`?
</blockquote></details>

It wasn't originally, and I kept it this way because otherwise there is even more ceremony around referring to the values.  Since its already enclosed within a `struct`, the fact that its constant names leak out one level seemed okay to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5920)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.  (I'm on call for Monday, and I've already jumped one onto Sam.)

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-:-KiN2PxCNrZ0jjqE2Thw:b-3h6dig)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5920)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5920#-:-KiVA2Xh6iBhd77_s7hT:bnfp4nl)*

**Pull request merged**
