### PR TITLE
Install net_sf_jchart2d_jchart2d

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6320)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[BUILD.bazel, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6320#-KmSjfBQfBVTSz4Xfk4-:-KmSjfBQfBVTSz4Xfk40:b777b5q) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b449724cc2c610b20797a1eb5e874dfbb2e464/BUILD.bazel#L37)):*
> ```
>     name = "install_net_sf_jchart2d_jchart2d",
>     doc_strip_prefix = ["tools/third_party"],
>     license_docs = ["//tools:third_party/jchart2d/LICENSE"],
> ```

BTW, can we do this for BCT also? (Not necessarily in this PR)

---

*[BUILD.bazel, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6320#-KmSjkw4n6EkkAIYE3q2:-KmSjkw4n6EkkAIYE3q3:b-udh4r3) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b449724cc2c610b20797a1eb5e874dfbb2e464/BUILD.bazel#L38)):*
> ```
>     doc_strip_prefix = ["tools/third_party"],
>     license_docs = ["//tools:third_party/jchart2d/LICENSE"],
>     java_strip_prefix = ["external/net_sf_jchart2d_jchart2d/jar"],
> ```

BTW, does `**` work? (Might also want to use that for docs...)

---

*[tools/third_party/jchart2d/LICENSE, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6320#-KmSkLZ9ssecHqESXp53:-KmSkLZ9ssecHqESXp54:bet0fii) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b449724cc2c610b20797a1eb5e874dfbb2e464/tools/third_party/jchart2d/LICENSE#L1)):*
> ```
> JChart2D is published under the OSI-approved GNU Lesser General Public License
> ```

BTW and FTR, I am "taking your word" that this is correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6320#-:-KmSkWzGg3743j7iny84:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[BUILD.bazel, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6320#-KmSjkw4n6EkkAIYE3q2:-KmSviXU6yFXzjink3rs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b449724cc2c610b20797a1eb5e874dfbb2e464/BUILD.bazel#L38)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, does `**` work? (Might also want to use that for docs...)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6320)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/third_party/jchart2d/LICENSE, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6320#-KmTM7YsZvt_bv61T3YZ:-KmTM7Yt6VkWCHCSWFKO:b6w56sq) ([raw file](https://github.com/robotlocomotion/drake/blob/db68437fc7498443e9bd6576c5d05e75e59253c3/tools/third_party/jchart2d/LICENSE#L1)):*
> ```
> JChart2D is published under the OSI-approved GNU Lesser General Public License
> ```

FYI Would it make sense to amend the commit message (of this file, or just the whole PR) to specify where this LICENSE content comes from?  (Was it hand-made, or downloaded from upstream at some URL, or ...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6320#-:-KmTM_NhiR_nQ8N-Z0PE:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/third_party/jchart2d/LICENSE, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6320#-KmTM7YsZvt_bv61T3YZ:-KmTPPkPU2Ssot0Tb5jK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/455c21f36bab9c4a228e0e89a75bb01ebf293913/tools/third_party/jchart2d/LICENSE#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Would it make sense to amend the commit message (of this file, or just the whole PR) to specify where this LICENSE content comes from?  (Was it hand-made, or downloaded from upstream at some URL, or ...)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6320)*

**Comment by jwnimmer-tri** [comment]
The usual git failures flake.
@drake-jenkins-bot linux-gcc-experimental-ros please

**Pull request merged**
