### PR TITLE
Fix MOSEK builds on macOS

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8702)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8702#-:-LB6AT5g6z96gsFVTQxp:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm: but I need to go to the office to test it. (It turns out that my VPN has a DNS issue to connect the MOSEK server).

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8702#-:-LB6C2juAUixb51zElZW:b-cd0bhi)*

**Comment by jamiesnape** [comment]
> (It turns out that my VPN has a DNS issue to connect the MOSEK server).

I tested locally. You should get a license error rather than a dynamic loader problem if this works.

**Comment by jamiesnape** [comment]
```
$ git describe 
v0.9.11-13957-gf584f3e672
$ bazel test --config mosek --test_tag_filters=mosek //...
INFO: Analysed 8747 targets (0 packages loaded).
INFO: Found 8736 targets and 11 test targets...
INFO: Elapsed time: 972.831s, Critical Path: 187.47s
INFO: Build completed successfully, 796 total actions
```

**Comment by soonho-tri** [comment]
Confirmed! (@TRI)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8702#-:-LB6IrxQ6pUBC1mMKGSr:b-vii0c1)*

**Pull request merged**
