### PR TITLE
Remove more redundant PODs code

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3844)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
:lgtm: Ever closer... 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/pods.cmake, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3844#-KUYyWc3xHeuSPruC9kC:-KUYyWc3xHeuSPruC9kD:b-niti3y) ([raw file](https://github.com/robotlocomotion/drake/blob/e15ac7a0392bfba8f9013dec83ba29c8f34b32d8/cmake/pods.cmake#L145)):*
> ```CMake
>         ${CMAKE_INSTALL_PREFIX}/lib/python${pyversion}/dist-packages)
> 
>     if(EXISTS "${py_src_dir}/__init__.py")
> ```

Why drop this condition?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3844#-:-KUZ-byzgGToCGvV80vE:b-a6epmp)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/pods.cmake, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3844#-KUYyWc3xHeuSPruC9kC:-KUZ-qwRgA3oJX3ZMARK:b-xgtr1s) ([raw file](https://github.com/robotlocomotion/drake/blob/e15ac7a0392bfba8f9013dec83ba29c8f34b32d8/cmake/pods.cmake#L145)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why drop this condition?  
</details>
Mostly because the function is no longer general purpose. I probably should have deleted it last prune. It used to be able to install scripts as well as packages. Also seems kind of arbitrary that we check for that and not a million other things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3844)*

**Pull request merged**
