### PR TITLE
Remove deprecated code 2022-02

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16479)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for both reviews per schedule (tomorrow), please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16479#-:-MunNdYrBOL4tCzMZE3s:byjkz4r)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

___
*[manipulation/models/ycb/package.xml, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16479#-MunNj7x2OsGUSmy2fyi:-MunNj7x2OsGUSmy2fyj:b-d8oam7) ([raw file](https://github.com/robotlocomotion/drake/blob/bbfeb3533dbad6861f7615943fe671eb8a187a5d/manipulation/models/ycb/package.xml#L19)):*
> ```XML
>     <deprecated>
>       The 'package://ycb' URI spelling is deprecated, and will be removed from
>       Drake on or around 2022-03-01. Please spell the URI as
> ```

FYI This was a typo in the original PR.  All of the other files in that PR used 2022-03-01 as the date.  This one had a typo that got missed during review.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 with one comment

> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16479#-:-MunSozZ59jy1FpE0gJf:b-wv85io)* status: 1 unresolved discussion, missing label for release notes (waiting on @jwnimmer-tri)

___
*[multibody/parsing/process_model_directives.cc, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16479#-MunRbkIE6jOEOr-Yjln:-MunRbkIE6jOEOr-Yjlo:b-o4oe7g) ([raw file](https://github.com/robotlocomotion/drake/blob/bbfeb3533dbad6861f7615943fe671eb8a187a5d/multibody/parsing/process_model_directives.cc#L61)):*
> ```cpp
>   // TODO(#14084): This hack really shouldn't belong in model
>   // directives. Instead, it should live externally as a transformation on
>   // ModelDirectives (either flattened or recursive).
> ```

minor: I believe this TODO can be removed now.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16479)* status: missing label for release notes (waiting on @sherm1)

___
*[multibody/parsing/process_model_directives.cc, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16479#-MunRbkIE6jOEOr-Yjln:-MunXvpr7D8AH9LEeY-9:bjlj37j) ([raw file](https://github.com/robotlocomotion/drake/blob/bbfeb3533dbad6861f7615943fe671eb8a187a5d/multibody/parsing/process_model_directives.cc#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I believe this TODO can be removed now.
</blockquote></details>

That's right!  Done.

**Comment by jwnimmer-tri** [comment]
Merging now...

```
jwnimmer@call-cps:~$ date -u
Tue 01 Feb 2022 05:24:09 AM UTC

```

**Pull request merged**
