### PR TITLE
Rewrite Bazel's GetDrakePath to use FindResource

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6212)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.
+(status: do not merge) until I find a feature reviewer.

**Comment by sammy-tri** [comment]
+@sammy-tri for feature review 
-(status: do not merge) as a feature reviewer has been found

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6212#-:-KlTgHk7CXeCAZ_5wu5F:b-yov1dg)*

**Comment by sammy-tri** [comment]
:lgtm: tested locally, WORKSFORME

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6212#-:-KlTkIEZOtvbVUzskpPF:be8zs5n)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/drake_path_bazel.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6212#-KlTnAcSQW4U556_mDSn:-KlTsrGWPtt3KvGxX1Jy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84041345b382a862055eb7f7ef3c18ace74618ee/drake/common/drake_path_bazel.cc#L14)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Single source of truth is nice and all, but do we really want bazel referring to cmake like this?  I thought our plan was the opposite direction.
</blockquote></details>

Done.

---

*[drake/common/drake_path_bazel.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6212#-KlTnMy98Kpx64STYfy-:-KlTsrvHhDNhHY3rud-5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84041345b382a862055eb7f7ef3c18ace74618ee/drake/common/drake_path_bazel.cc#L20)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- given that you are not using i, and are doing this only twice, this loop might be more readable unrolled.  Author's discretion.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6212)*

**Comment by ggould-tri** [comment]
:lgtm:

Also I love reviewable's syntax highlighting of the sentinel file :-)

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6212#-:-KlTt8r1Rn2pvKNa-FF0:btb80v2)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-cpplint-experimental please
@drake-jenkins-bot linux-clang-experimental-memcheck-lsan please
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-cpplint-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

**Pull request merged**
