### PR TITLE
Upgrade Externals January 2023

### LINKED ISSUE #17910: usockets and uwebsockets needs update to latest
uwebsockets needs to be updated to the latest release. The build is failing:
```
external/uwebsockets/src/App.h:90:62: error: static assertion failed: Mismatching uSockets/uWebSockets ABI
   90 |     static_assert(sizeof(struct us_socket_context_options_t) == sizeof(SocketContextOptions), "Mismatching uSockets/uWebSockets ABI");
```

It looks like the latest µWebSockets may depend on an unreleased µSockets? (The latest µSockets release is Sept 2021. There should perhaps also be a note that these packages should update in tandem in the relevant `repository.bzl`(s)?)

Note also that `new_release.py` is not currently working on usockets due to sigmavirus24/github3.py#1105.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #18510. Fixes #17910.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18516)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews +(status: single reviewer ok).

+(release notes: fix) +(status: commits are properly curated) 

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18516#-:-NKynAmf7ONoWnsE1Cpi:b24dbys)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please.

---

The https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades document says:

> Once the all Jenkins builds of the pull request have passed, additionally launch a macOS build, per
>
> https://drake.mit.edu/jenkins.html#scheduling-an-on-demand-build
>
> Once the macOS build passes, assign the pull request for review.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18516)* status: 1 unresolved discussion, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/robotlocomotion/drake/18516#-NKylXl15AiVujhbyzgF):*
The README instructions say "add the commit using the instructions that were printed by new_release".  The commit instructions printed by the tool do _not_ include the git commit sha in the subject like (e.g., for `abseil_cpp_internal`):

```console
...
Done.  Be sure to review and commit the changes:
  git add tools/workspace/abseil_cpp_internal/repository.bzl
  git commit -m'[workspace] Upgrade abseil_cpp_internal to latest commit'
```

Since we need to rebase this PR anyway prior to merge, during the rebase we might as well remove the commit sha's from the three subject lines where it crept in.  That will save the release manager the effort of editing them out later on.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18516)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/robotlocomotion/drake/18516#-NKylXl15AiVujhbyzgF):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The README instructions say "add the commit using the instructions that were printed by new_release".  The commit instructions printed by the tool do _not_ include the git commit sha in the subject like (e.g., for `abseil_cpp_internal`):

```console
...
Done.  Be sure to review and commit the changes:
  git add tools/workspace/abseil_cpp_internal/repository.bzl
  git commit -m'[workspace] Upgrade abseil_cpp_internal to latest commit'
```

Since we need to rebase this PR anyway prior to merge, during the rebase we might as well remove the commit sha's from the three subject lines where it crept in.  That will save the release manager the effort of editing them out later on.
</blockquote></details>

The README also gives an example of what to do, which includes the new "version". Maybe that example should either be more complete, or should not exist. (Although, as the script knows how to make the commit, *why doesn't it just do so?*)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18516)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/robotlocomotion/drake/18516#-NKylXl15AiVujhbyzgF):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

The README also gives an example of what to do, which includes the new "version". Maybe that example should either be more complete, or should not exist. (Although, as the script knows how to make the commit, *why doesn't it just do so?*)
</blockquote></details>

Per f2f: yup, a command-line option to run the `git` commands on behalf of the user sounds find.  That would reduce manual steps.  (Users who are particular about how they invoke git could still commit manually.)  In that case, the README could switch to use it, which would remove the misleading example commands.

**Comment by jwnimmer-tri** [comment]
This is just waiting on a rebase.  Shall I push that on your behalf?

**Comment by mwoehlke-kitware** [comment]
Done. Didn't I already do that once, though? IIRC, usually someone with force-merge permission does the final rebase, because otherwise the rebase needs to be coordinated with said person actually doing the merge. (Or get lucky that CI completes without master changing out from under the PR.)

**Comment by jwnimmer-tri** [comment]
> Didn't I already do that once, though?

Not since review was assigned, at least according to my interpretation of the github timeline.

> IIRC, usually someone with force-merge permission does the final rebase, because otherwise the rebase needs to be coordinated with said person actually doing the merge.

That's probably a valid way to do it, but I don't know if we've ever done it that way.  My advice is to do the rebase and then immediately ping one of the two super-admins (myself and sherm) and we can override CI to merge immediately.

**Comment by mwoehlke-kitware** [comment]
(Rebased or not?) Huh. I could've sworn I rebased it when I removed the SHAs from the commit messages. Maybe I forgot to update my local master first. :stuck_out_tongue:

(Who rebases?) Hmm, I thought that was how it usually happened. Maybe I'm misremembering. :shrug:

**Comment by mwoehlke-kitware** [comment]
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/robotlocomotion/drake/18516#-NKylXl15AiVujhbyzgF):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Per f2f: yup, a command-line option to run the `git` commands on behalf of the user sounds find.  That would reduce manual steps.  (Users who are particular about how they invoke git could still commit manually.)  In that case, the README could switch to use it, which would remove the misleading example commands.
</blockquote></details>

(This thread is resolved. Also, see #18548.)

**Comment by jwnimmer-tri** [comment]
I wonder if GitHub has a "rebase this PR onto the tip of master" button on the web somewhere.  That would probably be the easiest (especially if platform reviewers could just click it).

**Comment by mwoehlke-kitware** [comment]
*Github* has an option to rebase a PR. (I believe it doesn't create a merge commit, though, just adds the commits directly to master.)

**Pull request merged**
