### PR TITLE
[multibody] Add AddModelsFromUrl function to Parser

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Overload in pydrake as `AddModels(url=...)` sugar.

Port all examples and tutorials to use this spelling.

Users are constantly confused by the drake-specific `FindResourceOrThrow` in our code when their go to write their own software with non-Drake model files. For parsing, the better answer is always the `PackageMap`, so we should make it easy to load models via `package://` URLs.

Here's a representative change:
```patch
--- a/examples/pendulum/test/urdf_dynamics_test.cc
+++ b/examples/pendulum/test/urdf_dynamics_test.cc
@@ -2,7 +2,6 @@
 
 #include <gtest/gtest.h>
 
-#include "drake/common/find_resource.h"
 #include "drake/common/test_utilities/eigen_matrix_compare.h"
 #include "drake/examples/pendulum/pendulum_plant.h"
 #include "drake/multibody/parsing/parser.h"
@@ -15,8 +14,8 @@ namespace {
 
 GTEST_TEST(UrdfDynamicsTest, AllTests) {
   multibody::MultibodyPlant<double> mbp(0.0);
-  multibody::Parser(&mbp).AddModels(
-      FindResourceOrThrow("drake/examples/pendulum/Pendulum.urdf"));
+  multibody::Parser(&mbp).AddModelsFromUrl(
+      "package://drake/examples/pendulum/Pendulum.urdf");
   mbp.Finalize();
   PendulumPlant<double> p;
 
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @rpoyner-tri @RussTedrake @SeanCurtis-TRI for any input on the new API.

I still need to write unit tests, but all of the example call site porting is done.

**Review by RussTedrake — COMMENTED** [review]
I think this is a great change.  Thank you!

> Reviewed 9 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-:-NN1T2KE5W7tn316zFTa:buvms06)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NN1SNP4ALlCT8uATsB9):*
i wonder if it should be "url" => "uri".  I at first thought you were fetching remote resources!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @RussTedrake)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NN1SNP4ALlCT8uATsB9):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i wonder if it should be "url" => "uri".  I at first thought you were fetching remote resources!
</blockquote></details>

I am also considering `parser.SetRemote(true)` for #9498, in which case this _would_ fetch remotely.

But my main thought behind the choice was some mix of (1) URL is actually correct, it is a locator; and (2) modern consensus appears to be that the "URI" formalism is a considered to be a failed experiment and everyone should just say "URL" in casual use for simplicity.

**Review by rpoyner-tri — COMMENTED** [review]
:thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-:-NN2ahcUBIo8mmjsB9cF:b4c9lyr)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`examples/allegro_hand/run_allegro_constant_load_demo.cc` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NN2_Vjf1xzd64WFfO0_:-NN2_Vjg5zjmHImfKj8l:b78xf43) ([raw file](https://github.com/RobotLocomotion/drake/blob/94bfda7762839ae412447f221b9b76551a7f9b0b/examples/allegro_hand/run_allegro_constant_load_demo.cc#L66)):*
> ```cpp
>       "allegro_hand_description/sdf/allegro_hand_description_left.sdf";
>   }
>   multibody::Parser(&plant).AddModels(hand_url);
> ```

Was this call site supposed to be `AddModelsFromUrl`?

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

+(release notes: feature)
-(status: do not merge)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-:-NN3n1wM41cqVvzq36xM:b5qfdho)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri, @rpoyner-tri, and @RussTedrake)

___
*[`examples/allegro_hand/run_allegro_constant_load_demo.cc` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NN2_Vjf1xzd64WFfO0_:-NN2bNDm8noJJg7cKMPR:bpfys53) ([raw file](https://github.com/RobotLocomotion/drake/blob/94bfda7762839ae412447f221b9b76551a7f9b0b/examples/allegro_hand/run_allegro_constant_load_demo.cc#L66)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Was this call site supposed to be `AddModelsFromUrl`?
</blockquote></details>

Yup.  As they say, "Untested code is broken code"

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 50 of 55 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-:-NNIv9z67QiAkqzixorP:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`examples/manipulation_station/manipulation_station.cc` line 149 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNItGmy4yhtscwKOS70:-NNItGmy4yhtscwKOS71:bzbxbky) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1092166f427383ea7ef0971730f9f4d06956ced/examples/manipulation_station/manipulation_station.cc#L149)):*
> ```cpp
>   const auto models = ProcessModelDirectives(directives, &parser);
>   DRAKE_THROW_UNLESS(models.size() == 1);
>   const multibody::ModelInstanceIndex new_model = models[0].model_instance;
> ```

BTW You're welcome. =P

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-:-NNIwA8ZBBnUOeNfvo-i:b-1krawd)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @RussTedrake and @sammy-tri)

**Comment by jwnimmer-tri** [comment]
-@sammy-tri +@SeanCurtis-TRI bumping over to Monday on-call review, load-balancing.

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done. The only real question is that it seems that some call sites were missed. (Everything else is largely superficial.)

> Reviewed 50 of 55 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-:-NNbLT0MDchRoi0DIBsl:bn7pn4b)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNb7NjT7xNN5aVWVMzZ:-NNb7NjT7xNN5aVWVMz_:bepuc7v) (no related file):*
BTW Examples carry pedagogical duties -- they implicitly encode how we recommend things should be done. There's a subjective line to draw about how many details of the examples should be interpreted as such (e.g., API calls, yes. White space formatting, not necessarily.)

In the examples there is a mixture of naming practices of what we call the local variable containing a model url. I've seen three patterns:

- file_type_url
- model_url
- model_file_type_url

The use of any particular pattern doesn't seem correlated with the context (i.e., if there's only ever a single file loaded, the `file_type_url` might make sense. But this isn't universal.)

I'm not calling this out as a defect. I'm merely pointing out an inconsistent pattern in the examples. Certainly, naming this particular value is probably not something Drake is going to be opinionated about. But I thought I'd point it out in for the sake of completeness.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNbCcST83EKH4x4DFOp:-NNbCcST83EKH4x4DFOq:b-a976ls) (no related file):*
Seems we've missed some examples. As the comment says "all examples", I thought I'd call these out.

- bindings/pydrake/
    - example/
        - multibody/
            - cart_pole_passive_simulation.py
            - pendulum_lqr_monte_carlo_analysis.py`
            - run_planar_scenegraph_visualizer.py
    - multibody/
        - examples/jupyter_widgets_examples.ipynb

This ignores all the other cases that lie outside the scope of this PR because they have bespoke semantics on the resource they're finding the path for.

___
___
*[`common/find_resource.h` line 100 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNb4VPq2JFzh7SrG3gO:-NNb4VPq2JFzh7SrG3gP:bg43dji) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1092166f427383ea7ef0971730f9f4d06956ced/common/find_resource.h#L100)):*
> ```objc
> /// FindResourceResult::get_absolute_path_or_throw().
> ///
> /// Do NOT use this function to feed into a drake::multibody::parsing::Parser;
> ```

BTW By convention, wouldn't it make sense to add one of the (Advanced) or (Internal only) suffixes so prevalent in Drake documentation?
___
*[`multibody/parsing/parser.h` line 150 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNb96SM5mzP5wIXb-H6:-NNb96SM5mzP5wIXb-H7:b3vaipp) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1092166f427383ea7ef0971730f9f4d06956ced/multibody/parsing/parser.h#L150)):*
> ```objc
>       const std::filesystem::path& file_name);
> 
>   /// Parses the input file named in @p url and adds all of its model(s) to
> ```

BTW "(s)" isn't truly optional because the grammar of the rest of the sentence requires the plural to scan.
___
*[`multibody/parsing/parser.h` line 158 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNbACis-5hdMEEk0V75:-NNbACitEUN7Bwj6XH3M:b-46h2ke) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1092166f427383ea7ef0971730f9f4d06956ced/multibody/parsing/parser.h#L158)):*
> ```objc
>   /// @returns The set of model instance indices for the newly added models,
>   /// including nested models.
>   /// @throws std::exception in case of errors.
> ```

FYI: (This is the thought that jumped out at me when I first read the comment) Is this strictly true? It registers errors/warnings with the diagnostic policy, but, surely, the truth of this statement depends on someone not mucking about with the policy.

------------------------------

Follow up: Nevermind. I see that the user can't actually set the diagnostic policy. In the future, when they can, this will no longer be obviously true. But it's certainly true for now.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNb7NjT7xNN5aVWVMzZ:-NNbPV_9CAA4TSF0BUty:b-tdpsbg) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Examples carry pedagogical duties -- they implicitly encode how we recommend things should be done. There's a subjective line to draw about how many details of the examples should be interpreted as such (e.g., API calls, yes. White space formatting, not necessarily.)

In the examples there is a mixture of naming practices of what we call the local variable containing a model url. I've seen three patterns:

- file_type_url
- model_url
- model_file_type_url

The use of any particular pattern doesn't seem correlated with the context (i.e., if there's only ever a single file loaded, the `file_type_url` might make sense. But this isn't universal.)

I'm not calling this out as a defect. I'm merely pointing out an inconsistent pattern in the examples. Certainly, naming this particular value is probably not something Drake is going to be opinionated about. But I thought I'd point it out in for the sake of completeness.
</blockquote></details>

I don't think consistency in whether "sdf" appears in the local variable name is important.  In some situations it might be important to underline which file type we're using (e.g., if there are both sdf and urdf models around nearby), and in other cases not.

If we were going for a pattern, the one I'd elect is "don't give it name in the first place" -- pass a literal to the function.  It was just easier to keep the names for now in the older code.

(Fundamentally, most C++ code in `examples` is old and bad and should be replaced with 5-line python program.  I'll defer that for the future. I double-checked the python changes here and I am OK with them as-is.)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNbCcST83EKH4x4DFOp:-NNbQK-HA2-1sy0sSO8a:bsnq7v2) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Seems we've missed some examples. As the comment says "all examples", I thought I'd call these out.

- bindings/pydrake/
    - example/
        - multibody/
            - cart_pole_passive_simulation.py
            - pendulum_lqr_monte_carlo_analysis.py`
            - run_planar_scenegraph_visualizer.py
    - multibody/
        - examples/jupyter_widgets_examples.ipynb

This ignores all the other cases that lie outside the scope of this PR because they have bespoke semantics on the resource they're finding the path for.
</blockquote></details>

Good catch.  Working.

___
___
*[`common/find_resource.h` line 100 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNb4VPq2JFzh7SrG3gO:-NNbP4SS2L0x_pFUvvL3:b-71esg2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1092166f427383ea7ef0971730f9f4d06956ced/common/find_resource.h#L100)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW By convention, wouldn't it make sense to add one of the (Advanced) or (Internal only) suffixes so prevalent in Drake documentation?
</blockquote></details>

There are valid uses for this (e.g., locating drake/package.xml) so it can't be Internal.  I could possibly get behind Advanced... will think about it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri, @RussTedrake, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNbCcST83EKH4x4DFOp:-NNd0ehh9aYQkz5iwACe:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Good catch.  Working.
</blockquote></details>

Done.

___
___
*[`common/find_resource.h` line 100 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-NNb4VPq2JFzh7SrG3gO:-NNd6rQQ3hG0ZN63v2Jp:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1092166f427383ea7ef0971730f9f4d06956ced/common/find_resource.h#L100)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There are valid uses for this (e.g., locating drake/package.xml) so it can't be Internal.  I could possibly get behind Advanced... will think about it.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18692#-:-NNgEh_U1zBMHMEzinch:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
