### PR TITLE
moved /examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer to manipulation/tools

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6519)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature +@sammy-tri for platform. thanks guys. 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6519#-:-KoNiB3VBjk4xorq6Hsi:b48shvx)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6519#-:-KoNjV7tQC7JRrbgoNpQ:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6519#-KoS_bAHclIqOFUmxgsE:-KoS_bAHclIqOFUmxgsF:b-kythp4) (no related file):*
How is the new manipulation/tools different than manipulation/util (which already exists)?

---

*[drake/manipulation/tools/BUILD, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6519#-KoS_tshZuonb1AQGA1H:-KoS_tsiJUl_ayc0YfE_:bghyh4b) ([raw file](https://github.com/robotlocomotion/drake/blob/6e852f0a37cefae3a9af2ad2a44c416eece02853/drake/manipulation/tools/BUILD#L35)):*
> ```Python
>     add_test_rule = 1,
>     data = [
>         "//drake/examples/kuka_iiwa_arm:models",
> ```

The demo doesn't appear to use anything from kuka_iiwa_arm?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6519)*

**Comment by siyuanfeng-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6519#-KoS_bAHclIqOFUmxgsE:-KoSe9o6tuxTunbiuihG:bkl5yi7) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

How is the new manipulation/tools different than manipulation/util (which already exists)?
</blockquote></details>

mostly because it was tools before. i can move it to util. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6519)*

**Comment by siyuanfeng-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/manipulation/tools/BUILD, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6519#-KoS_tshZuonb1AQGA1H:-KoSfzZZMzR1ZT3GVNMn:b-7jxcwh) ([raw file](https://github.com/robotlocomotion/drake/blob/6e852f0a37cefae3a9af2ad2a44c416eece02853/drake/manipulation/tools/BUILD#L35)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The demo doesn't appear to use anything from kuka_iiwa_arm?
</blockquote></details>

rmed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6519)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 11 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6519#-:-KoSpwguWaGULWB3FU4z:bnfp4nl)*

**Pull request merged**
