### PR TITLE
Change UniformlyRandomQuat so it returns Eigen::Quaternion

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8564)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 
Platform review +@seancurtis-tri 
Note: To reviewers:  Ignore labels on the previous commits.
This PR seeks to replace calls to rotmat2quat with their RotationMatrix equivalents.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-:-L9qY4R5Ey_Hgr4AQXeI:begd3nq)*

**Comment by SeanCurtis-TRI** [comment]
Waiting on feature review; this should probably bump to @soonho-tri after feature review.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-:-L9rnjZ8A-7s_P5WA0fD:b-dpabf9)*

**Comment by hongkai-dai** [comment]
:lgtm: +@soonho-tri for platform review please.

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/rotation_matrix.h, line 464 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9uvC-d4_BtNPIQyYAp:-L9uvC-d4_BtNPIQyYAq:bv2lzvv) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/math/rotation_matrix.h#L464)):*
> ```objc
>   // @internal This implementation is adapted from simbody at
>   // https://github.com/simbody/simbody/blob/master/SimTKcommon/Mechanics/src/Rotation.cpp
>   static Eigen::Quaternion<T> ToQuaternion(const Matrix3<T>& M)  {
> ```

You may consider to change `Matrix3<T>` to `Eigen::Ref<const Matrix3<T>>`, so that `M` can be an eigen expression, like `Mat.topLeftCorner<3, 3>()`.

---

*[util/test/testDrakeGeometryUtil.cpp, line 101 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9uwrTe-Irm06Mw3W8Y:-L9uwrTe-Irm06Mw3W8Z:b4rd4ho) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/util/test/testDrakeGeometryUtil.cpp#L101)):*
> ```cpp
> 
>   for (int testnr = 0; testnr < ntests; testnr++) {
>     Eigen::Quaterniond quat = drake::math::UniformlyRandomQuaternion(generator);
> ```

const Eigen::Quaterniond

---

*[util/test/testDrakeGeometryUtil.cpp, line 124 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9uwoU74Y_AzF1IP-9h:-L9uwoU74Y_AzF1IP-9i:b4rd4ho) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/util/test/testDrakeGeometryUtil.cpp#L124)):*
> ```cpp
> 
>   for (int testnr = 0; testnr < ntests; testnr++) {
>     Eigen::Quaterniond quat = drake::math::UniformlyRandomQuaternion(generator);
> ```

const Eigen::Quaterniond

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-:-L9uxLh54fsjN9AjpPGF:b-mkkz8q)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9uy4W3C1O3DNVnGVii:-L9uy4W3C1O3DNVnGVij:bwwlm5x) (no related file):*
Running :apple: tests: `bazel test //manipulation/... //math/... //multibody/... //systems/... //util/... -c dbg --config asan`. I will mark this resolved when all passed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564)*

**Comment by soonho-tri** [comment]
:lgtm: (aside very minor comments)

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[manipulation/util/test/bot_core_lcm_encode_decode_test.cc, line 28 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9v7s4z3ENasCCP9NNi:-L9v7s4z3ENasCCP9NNj:bp2h1cv) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/manipulation/util/test/bot_core_lcm_encode_decode_test.cc#L28)):*
> ```cpp
>   std::default_random_engine generator;
>   generator.seed(0);
>   Eigen::Quaterniond q = drake::math::UniformlyRandomQuaternion(generator);
> ```

BTW, nit, -> `const Eigen::Quaterniond`

---

*[math/test/rotation_conversion_test.cc, line 412 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9v8Zvu4wN6c4yOFme0:-L9v8Zvu4wN6c4yOFme1:b-irzvoe) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/math/test/rotation_conversion_test.cc#L412)):*
> ```cpp
>     // rpy2quat should be the inversion of QuaternionToSpaceXYZ().
>     const Vector4d quat4 = rpy2quat(rpy);
>     Eigen::Quaterniond q_expected(quat4(0), quat4(1), quat4(2), quat4(3));
> ```

BTW, nit, `const Eigen::Quaterniond`

---

*[math/test/rotation_conversion_test.cc, line 473 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9v9DcI6BX2pSZUicIq:-L9v9DcI6BX2pSZUicIr:b-irzvoe) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/math/test/rotation_conversion_test.cc#L473)):*
> ```cpp
>     Eigen::Quaterniond q = SpaceXYZAnglesToEigenQuaternion(rpyi);
>     const Vector4d quat4 = rpy2quat(rpyi);
>     Eigen::Quaterniond quat(quat4(0), quat4(1), quat4(2), quat4(3));
> ```

BTW, nit, `const Eigen::Quaterniond`

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.cc, line 96 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9v9vypDYgg1WiCVsVa:-L9v9vypDYgg1WiCVsVb:b-h2aae9) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/multibody/multibody_tree/quaternion_floating_mobilizer.cc#L96)):*
> ```cpp
>   auto q = this->get_mutable_positions(&mbt_context);
>   DRAKE_ASSERT(q.size() == kNq);
>   Vector4<T> v4 = drake::math::RotationMatrix<T>::ToQuaternionAsVector4(R_FM);
> ```

BTW, nit1, `const Vector4`
BTW, nit2, `drake::` is not necessary here.

---

*[multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 391 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9vB3Q9BXmGmzOukM8s:-L9vB3Q9BXmGmzOukM8t:bc12kjz) ([raw file](https://github.com/robotlocomotion/drake/blob/7ad36b9df59a11f234ad48e1e4f0b050ecd1d428/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L391)):*
> ```cpp
>     // same way Drake currently aligns them. See issue #3470.
>     // When solved we will not need to instantiate a temporary Quaternion below
>     // just to perform a comparison.
> ```

Is it safe to remove this comment block? (#3470 is still open). Just in case, paging @amcastro-tri who wrote it 2 years ago.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-:-L9vBg7M4yZLqMkjimEA:b-hds9sv)*

**Comment by soonho-tri** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564)*

**Comment by hongkai-dai** [comment]
Reviewed 4 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564)*

**Comment by mitiguy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[math/rotation_matrix.h, line 464 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9uvC-d4_BtNPIQyYAp:-L9vNUgxCg9glmi9dhFn:bmfxq1z) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/math/rotation_matrix.h#L464)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

You may consider to change `Matrix3<T>` to `Eigen::Ref<const Matrix3<T>>`, so that `M` can be an eigen expression, like `Mat.topLeftCorner<3, 3>()`.
</blockquote></details>

Done.  

---

*[multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 391 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9vB3Q9BXmGmzOukM8s:-L9vVlKR4KlSPdAcR8El:bdzhkul) ([raw file](https://github.com/robotlocomotion/drake/blob/7ad36b9df59a11f234ad48e1e4f0b050ecd1d428/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L391)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Is it safe to remove this comment block? (#3470 is still open). Just in case, paging @amcastro-tri who wrote it 2 years ago.
</blockquote></details>

I think all is well.  Alejandro may be busy.  Perhaps the removal of this comment should not block this PR.  I need to merge it in order to get to the next PR which is to make RotationMatrix symbolic (per Alejandro's request).

---

*[util/test/testDrakeGeometryUtil.cpp, line 101 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9uwrTe-Irm06Mw3W8Y:-L9vPESe2yZSooKcJviE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/util/test/testDrakeGeometryUtil.cpp#L101)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

const Eigen::Quaterniond
</blockquote></details>

Done.

---

*[util/test/testDrakeGeometryUtil.cpp, line 124 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9uwoU74Y_AzF1IP-9h:-L9vPFxv0-qRKA5Qzt3b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/863d9350d2aaa7893d179f908b6c2a2236ae8f9f/util/test/testDrakeGeometryUtil.cpp#L124)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

const Eigen::Quaterniond
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564)*

**Comment by mitiguy** [comment]
Hi Soonho and Hongkai,

Can you take a quick look at PR# 8564 -- as I think you have given an LGTM
but still have blocking comments.

Thanks,

Paul

-- 

Confidential or protected information may be contained in this email 
and/or attachment. Unless otherwise marked, all TRI email communications 
are considered "PROTECTED" and should not be shared or distributed. Thank 
you.

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[math/random_rotation.h, line 57 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9zYqOR63mLcGivtn6e:-L9zYqOR63mLcGivtn6f:b-dydyxe) ([raw file](https://github.com/robotlocomotion/drake/blob/5d19debd4e08b1c14be44de68920dadf02f2c894/math/random_rotation.h#L57)):*
> ```objc
> /// distribution over the sphere.
> template <class Generator>
> // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> ```

BTW maybe worth fixing these TODO's since you are modifying the API in this PR?

---

*[multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 391 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9vB3Q9BXmGmzOukM8s:-L9zZbxO2xiH80u8mdQ5:bcod96c) ([raw file](https://github.com/robotlocomotion/drake/blob/7ad36b9df59a11f234ad48e1e4f0b050ecd1d428/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L391)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

I think all is well.  Alejandro may be busy.  Perhaps the removal of this comment should not block this PR.  I need to merge it in order to get to the next PR which is to make RotationMatrix symbolic (per Alejandro's request).
</blockquote></details>

I think is better now since now the details of the specific in-memory layout are abstracted within an actual class (Quaternion). 
I do not see the connection with symbolic rotation matrices @mitiguy (I didn't need to touch this code in #8561), but I'll trust you.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564)*

**Comment by soonho-tri** [comment]
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[math/random_rotation.h, line 23 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-LA-Kzr5AEfiVJ3ptpBj:-LA-Kzr5AEfiVJ3ptpBk:bcutqvo) ([raw file](https://github.com/robotlocomotion/drake/blob/1505c3ac2ea186ba82a408e3e71f53109cb9f105/math/random_rotation.h#L23)):*
> ```objc
> /// DOI=http://dx.doi.org/10.1145/377939.377946
> template <class Generator>
> Eigen::AngleAxisd UniformlyRandomAngleAxis(const Generator& generator) {
> ```

FYI, CI is unhappy with this change because `generator` has a state that changes in every call. I think we need to pass `Generator* const` here.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564)*

**Comment by soonho-tri** [comment]
Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 391 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-L9vB3Q9BXmGmzOukM8s:-LA0-hlA-wtSOM-klLPx:b-iomrkf) ([raw file](https://github.com/robotlocomotion/drake/blob/7ad36b9df59a11f234ad48e1e4f0b050ecd1d428/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L391)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think is better now since now the details of the specific in-memory layout are abstracted within an actual class (Quaternion). 
I do not see the connection with symbolic rotation matrices @mitiguy (I didn't need to touch this code in #8561), but I'll trust you.
</blockquote></details>

I believe this issue is/will be properly addressed by Paul, in order to merge this PR so that Paul can send his next PR, I will remove @amcastro-tri 's blocking comment.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564)*

**Comment by hongkai-dai** [comment]
-@seancurtis-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8564#-:-LA02LDHEE6t-WOir_RM:bkwkkkt)*

**Pull request merged**
