### PR TITLE
Report filename and line in drakelint error messages

### LINKED ISSUE #6767: Drake lint produce line error output
When drake lint detects out-of-order header includes, it would be good if it could enumerate them in the output. Specifically, if it had a format that was:

```
[Full File Path]:[line_no] 
```

Those two pieces of data can be followed by arbitrary messages. This will enable clickable links in CLion.  It is important that they be absolute paths; CLion doesn't handle relative paths at all.  :(

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #6767.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6978)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

1. I have a nit on your code. PTAL
2. Somehow, in the past, I'd missed the semantics of this test. That it reports the first error of an arbitrary set. So, there may be multiple badly ordered include files, but this stops at the first one it finds. In light of that semantics, this provides slightly less value. The value of jumping to the first of an unknown set of errors pales in comparison to simply fixing it. I think the CLion integration documentation should be upgraded to emphasize these semantics.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/formatter.py, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-KtMW9YuhHjSKxcOa76t:-KtMW9YuhHjSKxcOa76u:b-sbbc1n) ([raw file](https://github.com/robotlocomotion/drake/blob/16f00dea72b8b597717d4c2de0485006445fb19a/drake/tools/formatter.py#L65)):*
> ```Python
>         if self.is_same_as_original():
>             return None
>         lengths = [len(x) for x in [self._working_lines, self._original_lines]]
> ```

BTW nit: I'm not a big fan of this code.

- `lengths` seems misleading. Given that this is ultimately about string comparisons, this is suggestive of string lengths. `line_counts` might be more representative.
- You're calling `min(lengths)` over and over. Admittedly, it's a list of length 2, so it's not the most expensive operation in the world, but that still obfuscates what is happening here.

Alternatively, this might be clearer:
```py
line_counts = [len(x) for x in [self._working_lines, self._original_lines]]
for i in xrange(min(line_counts)):
   if self._working_lines[i] != self._original_lines[i]:
      return i
if line_counts[0] != line_counts[1]:
   return min(line_counts)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-:-KtMYc7RoA501fI8HZeR:b-y8aeuf)*

**Comment by jwnimmer-tri** [comment]
My hope was that by actually showing the filename & a single line number, at least the "jump to error" feature would work at all, whereas it didn't before.  Possibly if its a small error on a single new line this would still be useful.  It wouldn't be _that_ hard to read out all of the wrong lines, but really people should just run the fixer-upper, not fix by hand.  If CLion has a save hook (or format-on-demand hook), you could just put it there.

I've enabled pushes to this branch, if you want to push a docs update here that's OK by me.  Otherwise it can be a different PR.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/formatter.py, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-KtMW9YuhHjSKxcOa76t:-KtMaiuVv1-gwNwhl-aC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16f00dea72b8b597717d4c2de0485006445fb19a/drake/tools/formatter.py#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW nit: I'm not a big fan of this code.

- `lengths` seems misleading. Given that this is ultimately about string comparisons, this is suggestive of string lengths. `line_counts` might be more representative.
- You're calling `min(lengths)` over and over. Admittedly, it's a list of length 2, so it's not the most expensive operation in the world, but that still obfuscates what is happening here.

Alternatively, this might be clearer:
```py
line_counts = [len(x) for x in [self._working_lines, self._original_lines]]
for i in xrange(min(line_counts)):
   if self._working_lines[i] != self._original_lines[i]:
      return i
if line_counts[0] != line_counts[1]:
   return min(line_counts)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-:-KtMZsoyVUlOXV6G1VTv:b-s8k7vm)*

**Comment by SeanCurtis-TRI** [comment]
I agree; something clickable that points to *an* error is better than some opaque message.  I'll go ahead and do a follow-up PR on the docs.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/tools/formatter.py, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-KtMW9YuhHjSKxcOa76t:-KtMbUc_5ZNDlhvdYyDz:b-mzpy8i) ([raw file](https://github.com/robotlocomotion/drake/blob/16f00dea72b8b597717d4c2de0485006445fb19a/drake/tools/formatter.py#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW I'm not sure how the fact that the two lists are of different lengths implies that the line number is _de facto_ the length of the original lines. That implies we know that `len(self._original_lines) <= len(self._working_lines[i]`. If we know that, then we don't need the `min` in the for loop declaration. And I'm assuming that the `self._working_lines` could have added lines or *removed* too much white space, yes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-:-KtMb7aGjYpwHpRqcHk3:b3lv9ms)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/tools/formatter.py, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-KtMW9YuhHjSKxcOa76t:-KtMd3zP_nbuYj6_ZBhC:bg490n4) ([raw file](https://github.com/robotlocomotion/drake/blob/16f00dea72b8b597717d4c2de0485006445fb19a/drake/tools/formatter.py#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm not sure how the fact that the two lists are of different lengths implies that the line number is _de facto_ the length of the original lines. That implies we know that `len(self._original_lines) <= len(self._working_lines[i]`. If we know that, then we don't need the `min` in the for loop declaration. And I'm assuming that the `self._working_lines` could have added lines or *removed* too much white space, yes?
</blockquote></details>

Done.

Ugh, I had this correct and then thought "Wait, no that'll never happen" and changed it.  And I decided not to write a unit test, because hey, its a line number in a user diagnostic that will never be hit in practice.  Sigh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6978)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/formatter.py, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-KtMW9YuhHjSKxcOa76t:-KtMf0liOv9YbktTZZaj:b81qpby) ([raw file](https://github.com/robotlocomotion/drake/blob/16f00dea72b8b597717d4c2de0485006445fb19a/drake/tools/formatter.py#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

Ugh, I had this correct and then thought "Wait, no that'll never happen" and changed it.  And I decided not to write a unit test, because hey, its a line number in a user diagnostic that will never be hit in practice.  Sigh.
</blockquote></details>

Thanks for humoring me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6978)*

**Comment by jwnimmer-tri** [comment]
*[drake/tools/formatter.py, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-KtMW9YuhHjSKxcOa76t:-KtMfvztMLRi_aeM5jNh:b-yqkeb0) ([raw file](https://github.com/robotlocomotion/drake/blob/16f00dea72b8b597717d4c2de0485006445fb19a/drake/tools/formatter.py#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Thanks for humoring me.
</blockquote></details>

Thanks for finding it!  My sigh was for me; the review is great.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6978)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6978#-:-KtMgZx_71W3bRgxgKE9:bnfp4nl)*

**Pull request merged**
