### PR TITLE
Port sensors to model-based port declarations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #5431.

Note that I did not port the RGBD camera, because it only builds under CMake.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5513)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5513#-:-KfJvseIfstEHprd2mqD:bltds52)*

**Comment by liangfok** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5513#-:-KfMLVX-ZoqfKrGdro7o:b-jbsf8z)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5513#-:-KfMNN9U-ruPYAgmLXqH:bxwr5c8)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5513#-:-KfMcDCGetnQTUedGjQC:bnfp4nl)*

**Pull request merged**
