### PR TITLE
Prefer Eval over Calc in SapDriver

### PR DESCRIPTION
**Pull request by zeshunzong**
We should use the EvalContactKinematics in SapDriver::AddContactConstraint as the value may have been pre-computed elsewhere.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19970)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19970#-:-NbQgKvo75vgykA512SP:b1kntn7)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
Thank you @zeshunzong! this is great. 
I did a search of `CalcContactKinematics()` and I see we perform the same call in `tamsi_driver.cc` as well. Would you mind making your fix to this file as well in this PR? Thanks!

btw, I believe the CI failure is not related to this PR. But lest see how it goes after you push again.

:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19970#-:-Nboyptb9cjVqEoDcg-i:b-tr2lqy)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Hmm, this got lost.

+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19970#-:-NcOBfNxDhjgql8QhD8b:b-cxwtpw)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zeshunzong)

**Comment by xuchenhan-tri** [comment]
+(status: squashing now)

**Pull request merged**
