### PR TITLE
Add nlopt to Bazel

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5407)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-:-KeR0_QRa0kGBbD-CEir:b-e9da63)*

**Comment by rpoyner-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/nlopt-gen-hpp.sh, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-KeZJCrO9ETWKEAIuMRa:-KeZJCrPLg5F8Zgzwpht:b-po5f2f) ([raw file](https://github.com/robotlocomotion/drake/blob/326adeb6cf16485a5091bb1567a9ba3d6f5d6f3a/tools/nlopt-gen-hpp.sh#L1)):*
> ```Shell
> #/bin/bash
> ```

This line is weird/misleading. Is it a broken shebang, or unnecessary, or a poorly spelled editor hint?

---

*[tools/nlopt-gen-hpp.sh, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-KeZN9JPNerZueXT6oro:-KeZN9JQXUBjCam7BLDy:bhuqlcf) ([raw file](https://github.com/robotlocomotion/drake/blob/326adeb6cf16485a5091bb1567a9ba3d6f5d6f3a/tools/nlopt-gen-hpp.sh#L30)):*
> ```Shell
> # ... lines matching "    NLOPT_FOO..." become "    FOO...".
> # ... stop printing algorithms after "NUM_ALGORITHMS" ...
> sed -n 's/^\(     *\)NLOPT_\([A-Z0-9_][A-Z0-9_]*\)/\1\2/p; /^ *NUM_ALGORITHMS/q' "$nlopt_h" > algorithms.inc
> ```

BTW, This sed-fest and the next one could be made slightly simpler by using `[A-Z0-9_]\+` instead of `[A-Z0-9_][A-Z0-9_]*`

---

*[tools/nlopt-gen-hpp.sh, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-KeZNf8y_tDKzBTm3rje:-KeZNf8y_tDKzBTm3rjf:b-d3geh1) ([raw file](https://github.com/robotlocomotion/drake/blob/326adeb6cf16485a5091bb1567a9ba3d6f5d6f3a/tools/nlopt-gen-hpp.sh#L44)):*
> ```Shell
> echo "enum result {" >> enums.inc
> cat results.inc >> enums.inc
> echo "};" >> enums.inc
> ```

BTW, consider a here document formulation:

```
cat <<EOF >enums.inc
enum algorithm {
$(cat algorithms.inc)
};
enum result {
$(cat results.inc)
};
EOF
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5407)*

**Comment by jwnimmer-tri** [comment]
*[tools/nlopt-gen-hpp.sh, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-KeZN9JPNerZueXT6oro:-KeZXRZzTfRHphw2qZ_p:b-9gopmd) ([raw file](https://github.com/robotlocomotion/drake/blob/326adeb6cf16485a5091bb1567a9ba3d6f5d6f3a/tools/nlopt-gen-hpp.sh#L30)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, This sed-fest and the next one could be made slightly simpler by using `[A-Z0-9_]\+` instead of `[A-Z0-9_][A-Z0-9_]*`
</blockquote></details>

I could not find a switch to enable extended regular expressions that is spelled the same on both Linux and OSX.  Do you know of one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5407)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/nlopt-gen-hpp.sh, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-KeZN9JPNerZueXT6oro:-KeZjSbePWnUg-4Z4qnt:b2if28i) ([raw file](https://github.com/robotlocomotion/drake/blob/326adeb6cf16485a5091bb1567a9ba3d6f5d6f3a/tools/nlopt-gen-hpp.sh#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I could not find a switch to enable extended regular expressions that is spelled the same on both Linux and OSX.  Do you know of one?
</blockquote></details>

sigh, it's always the OSX, isn't it. Well, that's why it was 'BTW' to start with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5407)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/nlopt-gen-hpp.sh, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-KeZJCrO9ETWKEAIuMRa:-KeZWyDJEGrpRvxFbxdt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/326adeb6cf16485a5091bb1567a9ba3d6f5d6f3a/tools/nlopt-gen-hpp.sh#L1)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This line is weird/misleading. Is it a broken shebang, or unnecessary, or a poorly spelled editor hint?
</blockquote></details>

Done.

---

*[tools/nlopt-gen-hpp.sh, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-KeZNf8y_tDKzBTm3rje:-KeZXiJhchizUXlSPvg_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/326adeb6cf16485a5091bb1567a9ba3d6f5d6f3a/tools/nlopt-gen-hpp.sh#L44)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, consider a here document formulation:

```
cat <<EOF >enums.inc
enum algorithm {
$(cat algorithms.inc)
};
enum result {
$(cat results.inc)
};
EOF
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5407)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-:-KeZrM7N2aXjIyrUra8d:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review please (tomorrow is okay).

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-:-Ke_GSzTzWx6SFLsTU_3:b-v26fjz)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5407)*

**Comment by david-german-tri** [comment]
Ugh.  :lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5407#-:-Ke_nJkn05YA2BuDjOPW:b-h4q31z)*

**Comment by jwnimmer-tri** [comment]
There was one OS X compilation error, but it was #5417.  I am going to merge anyway, since it looks like this PR is clean.

**Pull request merged**
