### PR TITLE
[geometry] Speed up ClipPolygonbyHalfSpace

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This patch harvests a small performance win, as suggested by a TODO in the code.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21691)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

This helps a bit, but is overshadowed by slowness further up the call stack. We could land this for a tiny gain, or perhaps instead pursue some theories from @joemasterjohn for more ambitious rework of mesh intersection.

FYI @SeanCurtis-TRI @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21691#-:-O1IFhoMEZnFymBNE_Cf:b-e76g61)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@joemasterjohn for feature review; is this still relevant?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21691#-:-O1I_VJc0V34J_PI8Ygv:bsjat03)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by SeanCurtis-TRI** [comment]
*[`geometry/proximity/mesh_intersection.cc` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21691#-O1Ia9Q08hqY8N3xLaX7:-O1Ia9Q08hqY8N3xLaX8:b-5swuxy) ([raw file](https://github.com/RobotLocomotion/drake/blob/975413c7b5dcab5b6f1e5daa9565b088cdd541ff/geometry/proximity/mesh_intersection.cc#L87)):*
> ```cpp
>   const int size = static_cast<int>(input_vertices_F.size());
> 
>   // TODO(SeanCurtis-TRI): If necessary, this can be made more efficient:
> ```

BTW I was thinking more in terms of doing it with a single for loop.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21691)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/mesh_intersection.cc` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21691#-O1Ia9Q08hqY8N3xLaX7:-O1IaqZT2Qw0m9UaCGyQ:b-ep8vu6) ([raw file](https://github.com/RobotLocomotion/drake/blob/975413c7b5dcab5b6f1e5daa9565b088cdd541ff/geometry/proximity/mesh_intersection.cc#L87)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I was thinking more in terms of doing it with a single for loop.
</blockquote></details>

I couldn't figure out a nice way to do that and not end up with N+1 signed distance calls. This formulation does N signed distance; the code in master does 2N signed distance.

The single loop could get rid of the array-size assumption, but we are making that elsewhere already.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21691)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/mesh_intersection.cc` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21691#-O1Ia9Q08hqY8N3xLaX7:-O1IfFiZ4Y_PH8iduSNQ:bv616eb) ([raw file](https://github.com/RobotLocomotion/drake/blob/975413c7b5dcab5b6f1e5daa9565b088cdd541ff/geometry/proximity/mesh_intersection.cc#L87)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I couldn't figure out a nice way to do that and not end up with N+1 signed distance calls. This formulation does N signed distance; the code in master does 2N signed distance.

The single loop could get rid of the array-size assumption, but we are making that elsewhere already.
</blockquote></details>

Yeah. Looking at your code, I wasn't sure that it would be an obvious win. I figured I'd just clarify my TODO note to myself.  :)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: still relevant. This code is used for rigid-compliant intersection as well, so will also receive the benefit.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21691#-:-O1XPmAnEiwh4i0gm26B:b99d607)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
+@EricCousineau-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21691#-:-O1XQ0hY-CcbvLHY5rsz:b-r34yat)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21691#-:-O1XTBfH23EMjCMgRt15:bcpz082)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn

**Pull request merged**
