### PR TITLE
Add bazel install rules for tinyobjloader and yaml_cpp

### PR DESCRIPTION
**Pull request by fbudin69500**
Toward #3129.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6291)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/tinyobjloader-create-cps.py, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km7zdZOC-2N7PpXRgQ-:-Km7zdZOC-2N7PpXRgQ0:b-esmcic) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/tinyobjloader-create-cps.py#L6)):*
> ```Python
> 
> defs = read_version_defs("set\(TINYOBJLOADER_VERSION\s+([0-9]+).([0-9]+).([0-9]+)")
> ```

BTW (only since I'm nit-picking the license anyway), unnecessary blank line :smile:

---

*[tools/tinyobjloader-create-cps.py, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km7zZBgVXHEUgdjtsRp:-Km7zZBgVXHEUgdjtsRq:b-tht7q2) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/tinyobjloader-create-cps.py#L13)):*
> ```Python
>   "Name": "tinyobjloader",
>   "Description": "Tiny but powerful single file wavefront obj loader",
>   "License": ["MIT"],
> ```

BTW, superfluous `[]`s again :smile:

---

*[tools/tinyobjloader.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km7zPC1JaC44im9i956:-Km7zPC28PWXqHPs6_EX:b-qz8yr8) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/tinyobjloader.BUILD#L3)):*
> ```
> # -*- python -*-
> 
> load("@drake//tools:cmake_configure_file.bzl", "cmake_configure_file")
> ```

unneeded?

---

*[tools/yaml_cpp-create-cps.py, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km7zqH5kn8WQGNwCxUF:-Km7zqH6KgqclAo4JCkT:bgn8e41) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/yaml_cpp-create-cps.py#L12)):*
> ```Python
>   "Name": "yaml_cpp",
>   "Description": "A YAML parser and emitter in C++",
>   "License": ["MIT"],
> ```

BTW... well, you know :wink:

---

*[tools/yaml_cpp.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8--OXUbQ5KtlvuHrv:-Km8--OXUbQ5KtlvuHrw:b-qz8yr8) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/yaml_cpp.BUILD#L3)):*
> ```
> # -*- python -*-
> 
> load("@drake//tools:cmake_configure_file.bzl", "cmake_configure_file")
> ```

unneeded?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by fbudin69500** [comment]
Review status: 2 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/tinyobjloader-create-cps.py, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km7zdZOC-2N7PpXRgQ-:-Km81hTih3cRauB8hYE_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/tinyobjloader-create-cps.py#L6)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW (only since I'm nit-picking the license anyway), unnecessary blank line :smile:
</blockquote></details>

Done.

---

*[tools/tinyobjloader-create-cps.py, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km7zZBgVXHEUgdjtsRp:-Km81gmXOAcmsgWuHMy2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/tinyobjloader-create-cps.py#L13)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, superfluous `[]`s again :smile:
</blockquote></details>

Done.

---

*[tools/tinyobjloader.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km7zPC1JaC44im9i956:-Km81iNlpy0zxie9mRHY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/tinyobjloader.BUILD#L3)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

unneeded?
</blockquote></details>

Done.

---

*[tools/yaml_cpp-create-cps.py, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km7zqH5kn8WQGNwCxUF:-Km81j6b75jQY_Lu1vaX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/yaml_cpp-create-cps.py#L12)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW... well, you know :wink:
</blockquote></details>

Done.

---

*[tools/yaml_cpp.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8--OXUbQ5KtlvuHrv:-Km81jh8p_2j7m7KHFhy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e840d3f480601bd6272b8a47ff4345754d739238/tools/yaml_cpp.BUILD#L3)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

unneeded?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-:-Km83yRj-wJy_2HTRzmo:bnfp4nl)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/yaml_cpp-create-cps.py, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8Ad5RN6In7O4yjPZM:-Km8Ad5RN6In7O4yjPZN:b-xv2tme) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/yaml_cpp-create-cps.py#L10)):*
> ```Python
> {
>   "Cps-Version": "0.8.0",
>   "Name": "yaml_cpp",
> ```

Should be `yaml-cpp` and file should be `yaml-cpp-create-cps.py`, unless I am mistaken.

---

*[tools/yaml_cpp-create-cps.py, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km89uDUIs7zNxjJBq0W:-Km89uDUIs7zNxjJBq0X:bizx4h4) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/yaml_cpp-create-cps.py#L18)):*
> ```Python
>   "Components": {
>     "yaml_cpp": {
>       "Type": "interface",
> ```

Is this correct? I see `.cpp` files in the glob creating the `cc_library` for yaml_cpp.

---

*[tools/yaml_cpp.BUILD, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8AGLKcDXHdO7kfHkJ:-Km8AGLKcDXHdO7kfHkK:b-rby4xs) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/yaml_cpp.BUILD#L32)):*
> ```
>     doc_dest = "share/doc/yaml_cpp",
>     guess_hdrs = "PACKAGE",
>     hdr_dest = "include",
> ```

This is the default, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/tinyobjloader.BUILD, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8HuG4JdhZ_yML1lY4:-Km8HuG523AOELvYsZM5:b-gs22mm) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/tinyobjloader.BUILD#L20)):*
> ```
>     includes = ["."],
>     linkstatic = 0,
>     visibility = ["//visibility:public"],
> ```

FYI _Meta_ for the whole PR -- We usually remove these visibility markings on existing targets when the whole package is marked public by default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-:-Km8I45BxMI1K68bI-HO:bcpz082)*

**Comment by fbudin69500** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/tinyobjloader.BUILD, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8HuG4JdhZ_yML1lY4:-Km8MlYZzQeDWCRA4Q1Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/tinyobjloader.BUILD#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI _Meta_ for the whole PR -- We usually remove these visibility markings on existing targets when the whole package is marked public by default.
</blockquote></details>

Done.

---

*[tools/yaml_cpp-create-cps.py, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8Ad5RN6In7O4yjPZM:-Km8Mz25uen7lD0CiGeo:bcupuxn) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/yaml_cpp-create-cps.py#L10)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Should be `yaml-cpp` and file should be `yaml-cpp-create-cps.py`, unless I am mistaken.
</blockquote></details>

It is correct that in theory it should be yaml-cpp, as ignition_math and ignition_rndf should respectively be ignition-math and ignition_rndf. I could rename everything, files and targets, if this is what the reviewers prefer.

---

*[tools/yaml_cpp-create-cps.py, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km89uDUIs7zNxjJBq0W:-Km8OBEhGhanzOfeZk-F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/yaml_cpp-create-cps.py#L18)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Is this correct? I see `.cpp` files in the glob creating the `cc_library` for yaml_cpp.
</blockquote></details>

Done.

---

*[tools/yaml_cpp.BUILD, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8AGLKcDXHdO7kfHkJ:-Km8MyPLMIHJAo5dVe-P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/yaml_cpp.BUILD#L32)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

This is the default, I think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/yaml_cpp-create-cps.py, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8Ad5RN6In7O4yjPZM:-Km8RWn3V7tAZBkvE-lA:bujqph5) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/yaml_cpp-create-cps.py#L10)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

It is correct that in theory it should be yaml-cpp, as ignition_math and ignition_rndf should respectively be ignition-math and ignition_rndf. I could rename everything, files and targets, if this is what the reviewers prefer.
</blockquote></details>

You don't need to rename everything. Just the CPS. What Bazel calls it or what the library `.so` is called is irrelevant. The CPS for ignition_math should be ignition-math3, but the Bazel does not need to change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/yaml_cpp-create-cps.py, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8Ad5RN6In7O4yjPZM:-Km8SRKmn0da8ZY_CfT2:b6thou8) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/yaml_cpp-create-cps.py#L10)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

You don't need to rename everything. Just the CPS. What Bazel calls it or what the library `.so` is called is irrelevant. The CPS for ignition_math should be ignition-math3, but the Bazel does not need to change.
</blockquote></details>

Agreed. I was just trying to be consistent in the naming, but indeed it makes sense to rename the cmake package name for find_package()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/yaml_cpp-create-cps.py, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-Km8Ad5RN6In7O4yjPZM:-KmBkfjZGm91rw-JME_F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b167385f20d87657cc6cb58eaf7fd656f2bf7d70/tools/yaml_cpp-create-cps.py#L10)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Agreed. I was just trying to be consistent in the naming, but indeed it makes sense to rename the cmake package name for find_package()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/yaml_cpp-create-cps.py, line 17 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-KmC5cq8HlQ5mpjz9vEF:-KmC5cq8HlQ5mpjz9vEG:b-upb5dg) ([raw file](https://github.com/robotlocomotion/drake/blob/d3a7e50c6bd676e9d28aa3a189a8d2826f8b6303/tools/yaml_cpp-create-cps.py#L17)):*
> ```Python
>   "Default-Components": [ ":yaml_cpp" ],
>   "Components": {
>     "yaml_cpp": {
> ```

I believe that this needs to be `yaml-cpp` too and in the `Default-Components` above. The generated file needs the same target names as upstream, so remember to double check for all the install scripts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by fbudin69500** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/yaml_cpp-create-cps.py, line 17 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-KmC5cq8HlQ5mpjz9vEF:-KmC7TZ4tAYk2rqoLtQv:b6zrrk4) ([raw file](https://github.com/robotlocomotion/drake/blob/d3a7e50c6bd676e9d28aa3a189a8d2826f8b6303/tools/yaml_cpp-create-cps.py#L17)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I believe that this needs to be `yaml-cpp` too and in the `Default-Components` above. The generated file needs the same target names as upstream, so remember to double check for all the install scripts.
</blockquote></details>

Good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291#-:-KmCeHTDxnV13YEvhXXI:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6291)*

**Comment by jwnimmer-tri** [comment]
Build error is just the usual golang flake.  Using override-merge.

**Pull request merged**
