### PR TITLE
add link to michael posa's dircon implementation in the drake gallery

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8932)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@mposa for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8932#-:-LEF4HXv0smcgsa_kHEH:b6usaon)*

**Comment by mposa** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8932#-:-LEFaPbv6S6N4tdDVpHy:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@sammy-tri for platform review, please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8932#-:-LEFekZ1B-fnX7wnY4RB:bo1ktrv)*

**Comment by sammy-tri** [comment]
neat!  :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8932#-:-LEKIoVmAwqK4-uMGUl4:bp9froe)*

**Pull request merged**
