### PR TITLE
Revert "Use clang-format-4.0 on Ubuntu"

### PR DESCRIPTION
**Pull request by liangfok**
Dear @jwnimmer-tri,

The on-call build cop, @liangfok, believes that your PR #7477 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
* https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/RobotLocomotion/job/drake-shambhala/job/master/56/execution/node/18/log/
* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/RobotLocomotion/job/drake-shambhala/job/master/56/execution/node/18/log/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7506)

### CODE REVIEW

**Comment by liangfok** [comment]
I'm not sure how to run the following CI on this PR: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/RobotLocomotion/job/drake-shambhala/job/master/56/execution/node/18/log/

**Comment by liangfok** [comment]
+@jwnimmer-tri for all review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7506#-:-KzH9prs-9a_iIxPf3n8:bspmb6t)*

**Comment by jwnimmer-tri** [comment]
Shambhala needs its dependences updated; there is no problem with Drake.

**Comment by jwnimmer-tri** [comment]
Relates to RobotLocomotion/drake-shambhala#61.

**Pull request closed without merging**
