### PR TITLE
setup: Upgrade to Bazel 0.23

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
https://github.com/bazelbuild/bazel/releases/tag/0.23.0
https://github.com/bazelbuild/bazel/releases/tag/0.23.1

~I don't see this out at https://github.com/Homebrew/homebrew-core yet.  I'm okay waiting to bump Ubuntu until macOS is ready, assuming that's in the next few days.~  Ah, but we use https://github.com/bazelbuild/homebrew-tap perhaps, which _has_ been updated.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10772)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python3-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for all review, please (:lgtm: platform rubber stamp for trivial change).  You can let me know if / when we want to merge this, or push it yourself.

**Comment by jwnimmer-tri** [comment]
Would https://github.com/bazelbuild/bazel/issues/7555 impact our CI?

**Comment by jamiesnape** [comment]
On first glance, I don’t think so, but I need to look into it further.

**Comment by jamiesnape** [comment]
Let's bump this to 0.23.1 and then I think we are good to update the images.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python3-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Comment by jamiesnape** [comment]
@BetsyMcPhail Can you update the Ubuntu images?

**Comment by BetsyMcPhail** [comment]
All set

**Pull request merged**
