### PR TITLE
Move drake_find_package calls to the top level

### PR DESCRIPTION
**Pull request by jamiesnape**
To fix current and avoid future instances of using `*_FOUND` variables out of scope.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3996)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab pleas

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot  linux-clang-ninja-experimental-minimal  please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
Failures are due to #4000. So merging this is going to be blocked.

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm: aside from trivial style point

---

Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/packages.cmake, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3996#-KVaccEu3RAXq57PP13N:-KVaccF4WLgkCx2BnVIz:bb9xtlt) ([raw file](https://github.com/robotlocomotion/drake/blob/ad7e8e7a875c02b8c266ea8cf2fad5839571158f/cmake/packages.cmake#L73)):*
> ```CMake
> endmacro()
> 
> macro(drake_setup_packages)
> ```

BTW, maybe something like drake_find_packages would be more clear?

---

*[cmake/packages.cmake, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3996#-KVabb5BfCdWyZ4P1x8a:-KVabb5F9F0ByAyKcJPh:bdxwivt) ([raw file](https://github.com/robotlocomotion/drake/blob/ad7e8e7a875c02b8c266ea8cf2fad5839571158f/cmake/packages.cmake#L86)):*
> ```CMake
> 
>   drake_find_package(avl CONFIG)
>   drake_find_package(bot2-core CONFIG)
> ```

BTW, not guarding this with `if(lcm_FOUND)` will make this (newly) noisy if LCM is not in use

---

*[cmake/packages.cmake, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3996#-KVa_3ruA7Dgae972V7q:-KVa_3rywGMU4M2YNm3F:b-nw4o96) ([raw file](https://github.com/robotlocomotion/drake/blob/ad7e8e7a875c02b8c266ea8cf2fad5839571158f/cmake/packages.cmake#L100)):*
> ```CMake
> 
>   # END optional packages
>   #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

pedantic: too many `~`s (doesn't match above lines, which are correct)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3996#-:-KVacmEd-gMfeBuBXBZP:b1dbctn)*

**Comment by jamiesnape** [comment]
Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/packages.cmake, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3996#-KVaccEu3RAXq57PP13N:-KVaeGk0x9glAnZ6W1Gy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad7e8e7a875c02b8c266ea8cf2fad5839571158f/cmake/packages.cmake#L73)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> BTW, maybe something like drake_find_packages would be more clear?
</details>
Done.

---

*[cmake/packages.cmake, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3996#-KVabb5BfCdWyZ4P1x8a:-KVadAypQJ0hJnItb1wM:b6tkbqn) ([raw file](https://github.com/robotlocomotion/drake/blob/ad7e8e7a875c02b8c266ea8cf2fad5839571158f/cmake/packages.cmake#L86)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> BTW, not guarding this with `if(lcm_FOUND)` will make this (newly) noisy if LCM is not in use
</details>
`drake_find_package` should prevent that. I will double check a minimal build.

---

*[cmake/packages.cmake, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3996#-KVa_3ruA7Dgae972V7q:-KVaeG8NHOvE-yilmzUM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad7e8e7a875c02b8c266ea8cf2fad5839571158f/cmake/packages.cmake#L100)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> pedantic: too many `~`s (doesn't match above lines, which are correct)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3996)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by david-german-tri** [comment]
Yikes.  Let's disable the test in #4000 to unblock.  Will review momentarily.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by david-german-tri** [comment]
I would really like to know how the number of tests has changed vs. continuous, but CDash is not helping.

**Comment by david-german-tri** [comment]
All right, from the raw Jenkins log, there are 164 non-MATLAB tests with this change: https://drake-jenkins.csail.mit.edu/job/linux-clang-experimental/318/consoleFull

**Comment by david-german-tri** [comment]
vs 163 in the last continuous run: https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-clang-continuous-release/1209/consoleFull

**Comment by jamiesnape** [comment]
Problems `valkyrie_balancing_test` too.

**Comment by david-german-tri** [comment]
> Problems valkyrie_balancing_test too.

Indeed.  Too slow in debug mode, apparently.  And that's the other AWOL test in the previous Continuous.  Yay.

**Comment by jamiesnape** [comment]
I will add it to #4000 for now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot  linux-gcc-experimental-matlab please

**Comment by david-german-tri** [comment]
:lgtm: pending CI

---

Review status: 0 of 21 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3996#-:-KVbSKRHlU7Acrpn4FeM:b3cfjge)*

**Comment by jamiesnape** [comment]
Same issues with `runAtlasManip` and `runAtlasBalancingPerturb`. Any objections to disabling those too. They are disabled on `APPLE` and/or debug builds anyway. I suspect `runAtlasWalking` will fail post-merge.

**Comment by david-german-tri** [comment]
No, go for it.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Pull request merged**
