### PR TITLE
[workspace] Make classes with final dtors final

### PR DESCRIPTION
**Pull request by svenevs**
Relates: #16937 (clang-12 will start aggressively warning on this).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17086)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please.

The above test may be overkill but it will identify if the big sur toolchain is able to treat this as an error.

**Review by svenevs — COMMENTED** [review]
+@mwoehlke-kitware for feature review please, re: https://github.com/RobotLocomotion/drake/pull/16937#pullrequestreview-959783304

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17086#-:-N18dFyv7tdOL4nMvUFz:bakovbm)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware)

**Comment by svenevs** [comment]
> [7:21:46 AM]  warning: unknown warning option '-Werror=final-dtor-non-final-class'; did you mean '-Werror=abstract-final-class'? [-Wunknown-warning-option]

Without the clang-12 changes this does not work.

**Comment by jwnimmer-tri** [comment]
> Without the clang-12 changes this does not work.

Right.  This PR should only fix the C++ bugs, not try to change the build settings to enforce it.

**Comment by mwoehlke-kitware** [comment]
*[`tools/skylark/drake_cc.bzl` line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17086#-N19KYecDYpgUzm6jqRc:-N19KYecDYpgUzm6jqRd:b-1dhppi) ([raw file](https://github.com/robotlocomotion/drake/blob/75e16bafce33fd65f3f73fb8b78a2aa08e52054e/tools/skylark/drake_cc.bzl#L25)):*
> ```Starlark
>     "-Werror=absolute-value",
>     "-Werror=inconsistent-missing-override",
>     "-Werror=final-dtor-non-final-class",
> ```

Should this move to #16937?

**Comment by jwnimmer-tri** [comment]
*[`tools/skylark/drake_cc.bzl` line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17086#-N19KYecDYpgUzm6jqRc:-N19yf8gADacRm72_CT-:b55wycm) ([raw file](https://github.com/robotlocomotion/drake/blob/75e16bafce33fd65f3f73fb8b78a2aa08e52054e/tools/skylark/drake_cc.bzl#L25)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Should this move to #16937?
</blockquote></details>

Yes.  Feel free to push the fixup and then assign platform review.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17086)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @svenevs)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17086#-:-N1AToAOE3Q0a75ptAkC:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),mwoehlke-kitware (waiting on @svenevs)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17086)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),mwoehlke-kitware (waiting on @svenevs)

**Pull request merged**
