### PR TITLE
Upgrade documentation for SpatialVector to be more consistent with its subclasses.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16870)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16870#-:-MzXMnT68CZ93p0S3JJv:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few nits

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16870#-:-MzXR1bhDVgUHY7npety:bo87v7a)* status: 3 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/math/spatial_vector.h, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16870#-MzXNPQ980T2nIppuJGF:-MzXNPQ980T2nIppuJGG:brgfn1p) ([raw file](https://github.com/robotlocomotion/drake/blob/e021f855a5666764bf69f3f6725a6b878a9cbf0d/multibody/math/spatial_vector.h#L22)):*
> ```objc
> /// Important subclasses of %SpatialVector include SpatialVelocity,
> /// SpatialAcceleration, SpatialForce, and SpatialMomentum.
> /// Each of the 3-element vectors are assumed to be expressed in the same
> ```

nit: Each ... _is_
___
*[multibody/math/spatial_vector.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16870#-MzXO3TM4wP4oyb1r1OU:-MzXO3TM4wP4oyb1r1OV:bycqmnu) ([raw file](https://github.com/robotlocomotion/drake/blob/e021f855a5666764bf69f3f6725a6b878a9cbf0d/multibody/math/spatial_vector.h#L82)):*
> ```objc
> 
>   /// Const access to the i-th element of this spatial vector. In Debug
>   /// builds, this function throws an exception if i is out-of-bounds whereas
> ```

nit: "function asserts that i is in bounds ..." (here and elsewhere) because DRAKE_ASSERT & _DEMAND abort rather than throwing an exception.
___
*[multibody/math/spatial_vector.h, line 272 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16870#-MzXQqW5AgPkfB7QFARJ:-MzXQqW5AgPkfB7QFARK:bo3am2f) ([raw file](https://github.com/robotlocomotion/drake/blob/e021f855a5666764bf69f3f6725a6b878a9cbf0d/multibody/math/spatial_vector.h#L272)):*
> ```objc
> 
>   /// Expresses a spatial vector in another frame.
>   /// @param[in] RF_E RotationMatrix relating a frame F to a frame E.
> ```

nit: typo RF_E -> R_FE

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16870)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/math/spatial_vector.h, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16870#-MzXNPQ980T2nIppuJGF:-MzXp5kN7HJDpTH1nxf0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e021f855a5666764bf69f3f6725a6b878a9cbf0d/multibody/math/spatial_vector.h#L22)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: Each ... _is_
</blockquote></details>

Done.
___
*[multibody/math/spatial_vector.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16870#-MzXO3TM4wP4oyb1r1OU:-MzXpQx7EYfmIgI5k55s:bkf7hwe) ([raw file](https://github.com/robotlocomotion/drake/blob/e021f855a5666764bf69f3f6725a6b878a9cbf0d/multibody/math/spatial_vector.h#L82)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: "function asserts that i is in bounds ..." (here and elsewhere) because DRAKE_ASSERT & _DEMAND abort rather than throwing an exception.
</blockquote></details>

Done in two places.
___
*[multibody/math/spatial_vector.h, line 272 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16870#-MzXQqW5AgPkfB7QFARJ:-MzXpZ010JWaW1SJPf9t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e021f855a5666764bf69f3f6725a6b878a9cbf0d/multibody/math/spatial_vector.h#L272)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: typo RF_E -> R_FE
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
+@rpoyner-tri for platform review (Monday) per rotation, please

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16870#-:-MzYZd6m2jGtrAnJ0dTy:b-l8zqlp)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16870#-:-Mzp4p3CAe901U1zoJpO:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16870#-:-MzpMr6-9u2sM9YX8lqO:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @rpoyner-tri)

**Pull request merged**
