### PR TITLE
Adds ability to specify x-offset of vehicle visualization to ensure it matches the model's origin.

### LINKED ISSUE #5341: Automotive demo cars rendering has wrong origin for rotation
(This is just from watching the demo, but I'm pretty sure I'm right.  Someone who does a code / model dive can confirm.)

The automotive demo's cars rendering uses the wrong yaw-rotation origin.  We are using the prius SDF model and mapping x,y,yaw to a floating joint.  A turning car should curve around the center of the rear axle, but to my eye we are pivoting around the rear bumper (approximately).

It's possible that this isn't worth fixing until PoseAggregator is in place, depending on how much rework is RigidBodyTree specific vs applicable to the PoseAggregator design as well.

/CC @david-german-tri @liangfok

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #5341. This is an alternative to #5457.

Here's what `SimpleCar` looks like with the correct x-offset applied:

https://youtu.be/iDpAANTiuPU

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5470)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jadecastro for feature review please.
+@jwnimmer-tri for car and platform reviews please.

Thanks.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-KexazcT1Ab-b6A1S7CG:b-bn7sl2)*

**Comment by liangfok** [comment]
In this design, the visualization's x-axis offset is hard coded into `SimpleCarToEulerFloatingJoint`. An alternative design would be to create a new system dedicated to implementing the offset. Something like:

```
[vehicle model] --> [FooToEulerFloatingJoint] --> [VisualizationModelXOriginShifter] --> [DrakeVisualizer]
```

An advantage of this alternate design is I believe it will work with both `SimpleCarToEulerFloatingJoint` and `EndlessRoadCarToEulerFloatingJoint`.

However, we're also planning on eliminating the `FooToEulerFloatingJoint` systems and instead switch to use the `PoseVector` outputs of the various vehicle models. Thus, perhaps the long term solution is to implement a `PoseVectorXOriginShifter` that works with `PoseVector` objects.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-Kez0yxUX4ZM5bZxu03I:b-ttpt2l)*

**Comment by jadecastro** [comment]
Checkpoint. 
Some comments/questions to help me understand the design choices a bit better:
1. I understand this is an initial step for visualization of the Prius, but translating to the rear axle is technically only true for "no-slip" models like Ackermann vehicles. So if we were to model the Prius as a bicycle (for instance) we would be stuck with visuals of the the car rotating about the incorrect axis. Is there a plan to generalize this? 
2. The video does not help me at all understand how the behavior/positioning is any different than an offset at the rear fender. A better/more descriptive representation would probably help.
3. Is there any reason why `VehicleVisualization` cannot support any general `x`-`y`-`z` offsets rather than just `x`-offsets? Is this because `sdf` files are always aligned symmetrically? 

---

Reviewed 6 of 6 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-Kez8FCiEAMas-aFp52x:-Kez-jTdVUcCpYqs_GuH:b3v9qxy) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.cc#L52)):*
> ```cpp
>     : prius_visualization_(
>           GetDrakePath() + "/automotive/models/prius/prius_with_lidar.sdf",
>           1.40948 /* kP_MoVo*/),
> ```

BTW, it seems to me to make more sense for demo-specific code (such as anything Prius-related) to live in `automotive_demo.cc`rather than in `automotive_simulator.{cc,h}`?  In this case, you can probably do away with the `prius_parameters` member field (and getters) and remove cryptic parameters in the `AutomotiveSimulator` constructor, and placing them instead in `AddVehicles`?

---

*[drake/automotive/automotive_simulator.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-Key6mVfMqHAudZOw0Cq:-Key6mVfMqHAudZOw0Cr:b-9y3c0o) ([raw file](https://github.com/robotlocomotion/drake/blob/502e17661f19cb20060a3768f8a4b65fa2e32b1a/drake/automotive/automotive_simulator.h#L34)):*
> ```objc
> 
>   /// Fully parameterized constructor.
>   VehicleVisualization(std::string _filename, double _P_MoVo)
> ```

BTW, I don't think the preceding underscore is allowed in constructors?

---

*[drake/automotive/automotive_simulator.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezHeVREZnOjuvASRY_:-KezHeVREZnOjuvASRYa:bezk1a2) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L43)):*
> ```objc
>   /// The name of the SDF file to load as the vehicle's visualization. This file
>   /// must contain one free-floating model of a vehicle (i.e., a model that's
>   /// connected to the world).
> ```

BTW, could you elaborate on what is meant by the statement in parenthesis?

---

*[drake/automotive/automotive_simulator.h, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezJJw0aoonLoyEkcWK:-KezJJw0aoonLoyEkcWL:bn8l1s2) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L48)):*
> ```objc
>   /// The vector from `Mo` (the model's origin) to `Vo` (the
>   /// visualization's origin). It is used to ensure the visualization rotates
>   /// about the middle of its rear axle when the vehicle's yaw-state changes.
> ```

This is not always strictly true, in general. How about: 
```
It is used to ensure that the visualized vehicle rotates about a position offset in the model origin's x-direction by `P_MoVo`.
```

---

*[drake/automotive/automotive_simulator.h, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezKmPoAFzy9Xrhzdri:-KezKmPp8R70_Fz1ohtX:b-sbqo5s) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L50)):*
> ```objc
>   /// about the middle of its rear axle when the vehicle's yaw-state changes.
>   ///
>   /// <b>NOTE: `M` and `V` must have the same orientation. They can only be
> ```

I'm having a bit of trouble parsing this statement. It sounds as if both `M` and `V` are offset by this amount, which doesn't make sense.

---

*[drake/automotive/automotive_simulator.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezKXmz-il03xgc2xDS:-KezKXmz-il03xgc2xDT:b-98ybef) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L52)):*
> ```objc
>   /// <b>NOTE: `M` and `V` must have the same orientation. They can only be
>   /// offset by `P_MoVo` along `M`'s X-axis.</b>
>   double P_MoVo{};
> ```

Could we qualify `P_MoVo` as, for instance, `X_MoVo` to help understand that it only affects `x`-offsets?

---

*[drake/automotive/simple_car_to_euler_floating_joint.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezOBRW8_0IUg7P8Rhm:-KezOBRW8_0IUg7P8Rhn:b-xrgl4w) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/simple_car_to_euler_floating_joint.h#L23)):*
> ```objc
>   ///
>   /// @param p_MoVo See the documentation of VehicleVisualization.
>   explicit SimpleCarToEulerFloatingJoint(double p_MoVo = 0.) : p_MoVo_(p_MoVo) {
> ```

BTW, is there a reason why we have to store a new member field `p_MoVo_`? It looks like it's only used locally.

---

*[drake/automotive/dev/dev_demo.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezF4eXL3KqnZIcrATl:-KezF4eXL3KqnZIcrATm:b-i6sby4) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/dev/dev_demo.cc#L88)):*
> ```cpp
>   auto simulator = std::make_unique<AutomotiveSimulator<double>>();
>   const auto& prius = simulator->get_prius_visualization();
>   const std::string kSdfFile =
> ```

BTW, you should be able to access this from `VehicleVisualization` now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-Key7bilJI00i725Jtq_:bn0q4ay)*

**Comment by liangfok** [comment]
@jadecastro: Thanks for the review. I created separate discussion threads for each of your questions. See below.

---

Review status: 5 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-Kezeca5t4XPFaffQgYz:-Kezeca6tU7nfaati9LP:b-waeht1) (no related file):*
> I understand this is an initial step for visualization of the Prius, but translating to the rear axle is technically only true for "no-slip" models like Ackermann vehicles. So if we were to model the Prius as a bicycle (for instance) we would be stuck with visuals of the the car rotating about the incorrect axis. Is there a plan to generalize this?

Thinking about this some more, I think the ideal solution is to support non-identity `X_BM` as defined by @sherm1's figure below.

image

That would allow us to position the floating joint anywhere on the visualization, and thus accurately visualize the model. 

@sherm1 or @amcastro-tri, will `MultiBodyTree` support non-identity `X_BM` values?

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezefdPG8u2WVs_Gss4:-KezefdPG8u2WVs_Gss5:be7ij30) (no related file):*
> The video does not help me at all understand how the behavior/positioning is any different than an offset at the rear fender. A better/more descriptive representation would probably help.

Perhaps the following two videos are more clear?

# Original (incorrect) Yaw

https://youtu.be/iVKZXIhxBgQ

# Fixed Yaw After Applying `P_MoVo` Offset

https://youtu.be/RlaHXj1TeiE

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-Kezf2hxZap0IuCwBGuj:-Kezf2hxZap0IuCwBGuk:b-ekadnu) (no related file):*
> Is there any reason why VehicleVisualization cannot support any general x-y-z offsets rather than just x-offsets? Is this because sdf files are always aligned symmetrically?

There is no fundamental reason. I didn't do that in this PR simply because it wasn't required to fix the Prius visualization. As mentioned in an earlier discussion above, I think the ideal general solution is to support joints with non-identity `X_BM` transforms.

---

*[drake/automotive/automotive_simulator.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezHeVREZnOjuvASRY_:-KezfpRHxvbzNWs6Pkac:b-q0ow18) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L43)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, could you elaborate on what is meant by the statement in parenthesis?
</blockquote></details>

I'll update the documentation. As a quick explanation, SDF models can include a "world" link and explicitly connect the model to the world. See: #1821. This statement simply states that the model in the SDF cannot be connected to the world. It's required because AutomotiveSimulator internally connects the model to the world using an RPY floating joint.

---

*[drake/automotive/automotive_simulator.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezKXmz-il03xgc2xDS:-Kezg_v179C6ISHRRjtP:b-uqw6rw) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L52)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Could we qualify `P_MoVo` as, for instance, `X_MoVo` to help understand that it only affects `x`-offsets?
</blockquote></details>

Good question! Looking at the following website, I don't see the syntax for restricting the vector to be only in the x-axis of `M`.

http://drake.mit.edu/doxygen_cxx/group__multibody__quantities.html

@sherm1 is there a way to express using monogram notation a "position vector that's restricted to be along a single axis"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-Kezf3p6RCCL8kxQqZOK:b-sibrlc)*

**Comment by sherm1** [comment]
Answered a few questions -- ptal.

---

Review status: 5 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-Kezeca5t4XPFaffQgYz:-KezvPGxXaNCNbIueZza:bp6t6w3) (no related file):*
> will MultiBodyTree support non-identity X_BM values?

Yes! Side note -- although osrf has prototyped it, I believe current `.sdf` does not provide away to specify both X_PF and X_BM. MBTree's API will definitely support that but we will need to work with @clalancette to get the extra frame specification added in to `.sdf`.

---

*[drake/automotive/automotive_simulator.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezKXmz-il03xgc2xDS:-Kezx6n5YRec5ESu-AeC:b-sxfgqn) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L52)):*
> is there a way to express using monogram notation a "position vector that's restricted to be along a single axis"?

No, and that is the kind of specific detail that should be explained in comments -- trying to do it with notation will obfuscate rather than clarify. A position vector is always just a vector between two points -- some other part of your code apparently restricts those two points to separation along the x axis which is a great thing to know but not something there is any standard notation for.

---

*[drake/automotive/automotive_simulator.h, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezwJJiDNsBfYiD_fd1:-KezwJJiDNsBfYiD_fd2:boxte9m) ([raw file](https://github.com/robotlocomotion/drake/blob/c85d8d503da259463ca48ba70414d3fb61fa0b33/drake/automotive/automotive_simulator.h#L28)):*
> ```objc
> namespace automotive {
> 
> /// The vehicle visualization's filename and `P_MoVo`.
> ```

BTW, if this symbol is intended to the the position vector from frame M's origin to frame V's origin (expressed in frame M), it should be `p_MoVo` or `p_MV` because we use a lower case "p" to mean "position vector". (Optional note: if you want to emphasize the expressed-in frame you can add it with `_M` at the end; however the default is that it is expressed in the frame mentioned for the "from" end of the vector.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-KezyA6vhhtgnHIa3MJb:b-q5833d)*

**Comment by liangfok** [comment]
Review status: 5 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-Kezeca5t4XPFaffQgYz:-KezyjHUmbQdcgt-msJs:bpqy4c0) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

> will MultiBodyTree support non-identity X_BM values?

Yes! Side note -- although osrf has prototyped it, I believe current `.sdf` does not provide away to specify both X_PF and X_BM. MBTree's API will definitely support that but we will need to work with @clalancette to get the extra frame specification added in to `.sdf`.
</blockquote></details>

Yay! I'm now leaning towards closing this PR and waiting for non-identity `X_BM` to be supported.

---

*[drake/automotive/automotive_simulator.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezKXmz-il03xgc2xDS:-KezzZ8he2yRu5Db6J38:bc8ysd6) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

> is there a way to express using monogram notation a "position vector that's restricted to be along a single axis"?

No, and that is the kind of specific detail that should be explained in comments -- trying to do it with notation will obfuscate rather than clarify. A position vector is always just a vector between two points -- some other part of your code apparently restricts those two points to separation along the x axis which is a great thing to know but not something there is any standard notation for.
</blockquote></details>

OK thanks! Good to know.

---

*[drake/automotive/automotive_simulator.h, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezwJJiDNsBfYiD_fd1:-KezzihwSkS4wVGKWACg:bw0h90d) ([raw file](https://github.com/robotlocomotion/drake/blob/c85d8d503da259463ca48ba70414d3fb61fa0b33/drake/automotive/automotive_simulator.h#L28)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, if this symbol is intended to the the position vector from frame M's origin to frame V's origin (expressed in frame M), it should be `p_MoVo` or `p_MV` because we use a lower case "p" to mean "position vector". (Optional note: if you want to emphasize the expressed-in frame you can add it with `_M` at the end; however the default is that it is expressed in the frame mentioned for the "from" end of the vector.)
</blockquote></details>

Thanks. I will switch to lowercase `p`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-Kezeca5t4XPFaffQgYz:-Kf6sk4EB9LwSpzI1uSZ:b-yo8e6a) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yay! I'm now leaning towards closing this PR and waiting for non-identity `X_BM` to be supported.
</blockquote></details>

There's nothing wrong with having this PR fix a glaring error in the current automotive simulator.  When the dynamics team produces something useful, we can consider refactoring this code to use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470)*

**Comment by jwnimmer-tri** [comment]
Part of the reason this turned into a bikeshed is that `VechicleVisualization` is premature generalization.  We don't have multiple models to render right now.  Fixing the issue should have been as simple as adding a small magic number into the simulator, that only works for our Prius model.  Instead, we have a non-design-reviewed new concept, that rightly is getting pushback at PR-time.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-Kf6ugfV0IhpXXXyfEET:br8n0hj)*

**Comment by liangfok** [comment]
Got it. I will update this PR to remove `VehicleVisualization`.

---

Review status: 5 of 7 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-Kf6zmnCGTeQXa5EeX4I:b-2af1s3)*

**Comment by jadecastro** [comment]
Reviewed 1 of 5 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/automotive_simulator.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezHeVREZnOjuvASRY_:-Kf6xux-hGnnRvXvgHAJ:b-o4rn8i) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L43)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I'll update the documentation. As a quick explanation, SDF models can include a "world" link and explicitly connect the model to the world. See: #1821. This statement simply states that the model in the SDF cannot be connected to the world. It's required because AutomotiveSimulator internally connects the model to the world using an RPY floating joint.
</blockquote></details>

I'm still a bit confused, sorry. Based on what you've said above, would the following be more accurate to describe the `sdf` file itself?
```
(i.e., an unconnected model that will be connected to the world by AutomotiveSimulator)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470)*

**Comment by liangfok** [comment]
Review status: 6 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/automotive_simulator.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezHeVREZnOjuvASRY_:-Kf77e5Vet0U2RdfNCJ0:bpbch11) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L43)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

I'm still a bit confused, sorry. Based on what you've said above, would the following be more accurate to describe the `sdf` file itself?
```
(i.e., an unconnected model that will be connected to the world by AutomotiveSimulator)
```
</blockquote></details>

Yes, assuming readers will not be confused by the phrase "unconnected model".

Ah! I just realized that there's a missing "not" in front of "connected"!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470)*

**Comment by jadecastro** [comment]
Review status: 6 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/automotive/automotive_simulator.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezHeVREZnOjuvASRY_:-Kf78Kv-rMtnDmSfEWQJ:bi7zrnq) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L43)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yes, assuming readers will not be confused by the phrase "unconnected model".

Ah! I just realized that there's a missing "not" in front of "connected"!
</blockquote></details>

Got it.  Then `... a model that's not connected ...` should suffice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470)*

**Comment by jadecastro** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470)*

**Comment by liangfok** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-Kez8FCiEAMas-aFp52x:-Kf8KwWfnq2uy5MxF6qh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.cc#L52)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, it seems to me to make more sense for demo-specific code (such as anything Prius-related) to live in `automotive_demo.cc`rather than in `automotive_simulator.{cc,h}`?  In this case, you can probably do away with the `prius_parameters` member field (and getters) and remove cryptic parameters in the `AutomotiveSimulator` constructor, and placing them instead in `AddVehicles`?
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-Key6mVfMqHAudZOw0Cq:-Kf8L5ks9X0KlHfwZhLL:b8yh4wd) ([raw file](https://github.com/robotlocomotion/drake/blob/502e17661f19cb20060a3768f8a4b65fa2e32b1a/drake/automotive/automotive_simulator.h#L34)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, I don't think the preceding underscore is allowed in constructors?
</blockquote></details>

Done. (Reverted.)

---

*[drake/automotive/automotive_simulator.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezHeVREZnOjuvASRY_:-Kf8L8gtD-zNefoF-UGj:b8yh4wd) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L43)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Got it.  Then `... a model that's not connected ...` should suffice.
</blockquote></details>

Done. (Reverted.)

---

*[drake/automotive/automotive_simulator.h, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezJJw0aoonLoyEkcWK:-Kf8LAn1aTPYOma7D-RM:bm5lmqj) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L48)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

This is not always strictly true, in general. How about: 
```
It is used to ensure that the visualized vehicle rotates about a position offset in the model origin's x-direction by `P_MoVo`.
```
</blockquote></details>

Done (Removed this `struct` entirely.)

---

*[drake/automotive/automotive_simulator.h, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezKmPoAFzy9Xrhzdri:-Kf8LB_UhIs4VoCuoXL1:b8yh4wd) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/automotive_simulator.h#L50)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

I'm having a bit of trouble parsing this statement. It sounds as if both `M` and `V` are offset by this amount, which doesn't make sense.
</blockquote></details>

Done. (Reverted.)

---

*[drake/automotive/automotive_simulator.h, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezwJJiDNsBfYiD_fd1:-Kf8L-fDropKms3alpuQ:b8yh4wd) ([raw file](https://github.com/robotlocomotion/drake/blob/c85d8d503da259463ca48ba70414d3fb61fa0b33/drake/automotive/automotive_simulator.h#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Thanks. I will switch to lowercase `p`.
</blockquote></details>

Done. (Reverted.)

---

*[drake/automotive/simple_car_to_euler_floating_joint.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezOBRW8_0IUg7P8Rhm:-Kf8LpKfLBc-aLkzThia:b8yh4wd) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/simple_car_to_euler_floating_joint.h#L23)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, is there a reason why we have to store a new member field `p_MoVo_`? It looks like it's only used locally.
</blockquote></details>

Done. (Reverted.)

---

*[drake/automotive/dev/dev_demo.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-KezF4eXL3KqnZIcrATl:-Kf8MRALCmAZ7MS8aFd9:b8yh4wd) ([raw file](https://github.com/robotlocomotion/drake/blob/bec2e3bbb00128d5f791e1ca39b671db9a2fdea1/drake/automotive/dev/dev_demo.cc#L88)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, you should be able to access this from `VehicleVisualization` now.
</blockquote></details>

Done. (Reverted.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470)*

**Comment by liangfok** [comment]
Done. PTAL. 

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-Kf8VG1beU_XhLptsqiC:bli39tm)*

**Comment by jadecastro** [comment]
Thanks for the discussion @liangfok - :lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-Kf8_tr0pUf_DUA3xXVA:bi666pm)*

**Comment by jadecastro** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5470#-:-Kf98S2iXnsLv9sT7JlL:bnfp4nl)*

**Pull request merged**
