### PR TITLE
[SAP] SapSolver uses SapModel

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR updates the internal workings of `SapSolver` to use the better unit tested `SapModel`.

Things to note:
 1. We do not unit test for pre-processed data anymore. PreProcessedData is effectively replaced by SapModel, which is much better tested elsewhere.
 2. We do not unit test for number of evaluations, since SapModel now uses the `systems::` framework caching, which is also much better tested elsewhere.
 3. This PR is mostly a refactor, and removes more code than what it adds new!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930#-:-N-PDGhU7Su4rXT2ozWS:bzgdhpr)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Nice improvements! :lgtm: 
+@sherm1 for platform review on Tuesday per rotation please.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930#-:-N-PzjX6Crqbf6KnEYQ8:bqva08i)* status: 8 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @amcastro-tri and @sherm1)

___
*[multibody/contact_solvers/sap/sap_solver.h, line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PJWPw9FGxsdU5CDJX:-N-PJWPx4nRqv7yn_xD-:b-wz664g) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.h#L169)):*
> ```objc
>   // is supported. An exception is thrown if `T != double`.
>   //
>   // @pre dynamics_data must contain data for inverse dynamics, i.e.
> ```

minor, this comment is out of date.
___
*[multibody/contact_solvers/sap/sap_solver.h, line 216 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PlqyM4EJbPA7i8Iek:-N-PlqyM4EJbPA7i8Iel:b-7vdykg) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.h#L216)):*
> ```objc
>   // generalized velocities, vc is the vector of contact velocities and gamma is
>   // the vector of generalized contact impulses.
>   void PackSapSolverResults(const systems::Context<T>& context,
> ```

minor, it would be nice to mention where the function expects the context to come from.
___
*[multibody/contact_solvers/sap/sap_solver.h, line 236 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PvQd-ANkc_dR6ULbQ:-N-PvQd-ANkc_dR6ULbR:b-qqguwf) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.h#L236)):*
> ```objc
>   T CalcCostAlongLine(const systems::Context<T>& context,
>                       const SearchDirectionData& search_direction_data,
>                       const T& alpha, systems::Context<T>* scratch) const;
> ```

BTW, it'd be nice to mention where the context and the scratch come from (both from model).
___
*[multibody/contact_solvers/sap/sap_solver.h, line 280 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PmE589wEcEvrkRU-w:-N-PmE589wEcEvrkRU-x:b-qzi3h0) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.h#L280)):*
> ```objc
> 
> template <>
> SapSolverStatus SapSolver<double>::SolveWithGuess(
> ```

Could you remind me why this is needed?
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PnhAQ491LdMEi4x99:-N-PnhAQ491LdMEi4x9A:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.cc#L43)):*
> ```cpp
>   // Constraints equations are clustered (essentially their order is permuted
>   // for a better sparsity structure). Therefore constraint velocities and
>   // impulses and impulses are evaluated in this clustered order and permuted
> ```

nit



_Suggestion:_
```cpp
 // impulses are evaluated in this clustered order and permuted
```
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PqoSBDm-LZPaHazap:-N-PqoSBDm-LZPaHazaq:ba4jegh) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.cc#L85)):*
> ```cpp
>                                              SapSolverResults<T>*) {
>   throw std::logic_error(
>       "SapSolver::SolveWithGuess(): Only T = double is supported.");
> ```

I don't think the two specializations are needed. We have `@tparam_double_only` for now.
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-Pr9D-Dmstxk_JIYpd:-N-Pr9D-Dmstxk_JIYpe:bs8benz) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.cc#L99)):*
> ```cpp
>     results->Resize(problem.num_velocities(),
>                     problem.num_constraint_equations());
>     results->v = problem.v_star();
> ```

What about the rest of the data in results? are they just garbage?
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PumagAv9D5NhL1mx4:-N-PumagAv9D5NhL1mx5:bdfgmpe) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.cc#L345)):*
> ```cpp
> 
>   // Make dense dynamics matrix.
>   const std::vector<MatrixX<T>> Acliques = model_->dynamics_matrix();
> ```

We surely don't want a copy here?
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 401 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-Pwme50nOrBNgcGhty:-N-Pwme50nOrBNgcGhtz:b-pw16j6) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.cc#L401)):*
> ```cpp
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS(
> ```

This doesn't follow the `tparam_double_only` specified in documentation.
___
*[multibody/contact_solvers/sap/test/sap_solver_test.cc, line 265 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PyyoL8y6P2PY85sU_:-N-PyyoL8y6P2PY85sUa:b-4fz2ot) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/test/sap_solver_test.cc#L265)):*
> ```cpp
>   params.rel_tolerance = 1.0e-6;
>   params.ls_max_iterations = 40;
>   const double beta = kEps;  // No near-rigid regime.
> ```

BTW, could you explain why this change is necessary?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/contact_solvers/sap/sap_solver.h, line 280 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PmE589wEcEvrkRU-w:-N-T1Lj2-5Pv772EcIOA:bw57ycj) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.h#L280)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Could you remind me why this is needed?
</blockquote></details>

it is required by the `DRAKE_DECLARE_` at the end of the file. Without it (I honestly do not know why) the compiler barks at you.
I decided to DECLARE/DEFINE on non-symbolic scalars since that's what we want in the long term, with an exception on T!=double for now. In the future we'd specialize DoSolve for the case AutoDiffXd to compute gradients analytically.
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PqoSBDm-LZPaHazap:-N-T1vjwErPyryJwntvb:b-5jsrr0) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.cc#L85)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't think the two specializations are needed. We have `@tparam_double_only` for now.
</blockquote></details>

I decided to keep the specialization and update the long term API contract. See previous comment.
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-Pr9D-Dmstxk_JIYpd:-N-SvtiqE7jkBo3ZsuZW:b-c5dddg) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.cc#L99)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

What about the rest of the data in results? are they just garbage?
</blockquote></details>

gamma and vc have zero size. I forgot j. I added unit test.
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PumagAv9D5NhL1mx4:-N-T-OgVCEqJJyenzPTH:bd30coi) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.cc#L345)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We surely don't want a copy here?
</blockquote></details>

good call.
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 401 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-Pwme50nOrBNgcGhty:-N-T25Gc4fanGS3bfiB5:bep0mdr) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.cc#L401)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This doesn't follow the `tparam_double_only` specified in documentation.
</blockquote></details>

It does now.
___
*[multibody/contact_solvers/sap/test/sap_solver_test.cc, line 265 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PyyoL8y6P2PY85sU_:-N-T-dwTApd-DtVh6bQm:bp3qvop) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/test/sap_solver_test.cc#L265)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, could you explain why this change is necessary?
</blockquote></details>

that's because SapFrictionConeConstranint requires beta to be strictly positive. That is, it is trying to enforce that we always have strictly positive regularization. Zero regularization is not possible.
I think this is better than the previous version that did allow zero beta.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-T2GR7-g_dSl6QRo3n:-N-T2GR7-g_dSl6QRo3o:bydl17a) (no related file):*
FYI @xuchenhan-tri (and @sherm1). In one of our f2f @xuchenhan-tri gave me really good suggestions on how to test the Newton solver in a unit test. I'll PR that separately next.

---

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/contact_solvers/sap/sap_solver.h, line 280 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PmE589wEcEvrkRU-w:-N-T2j_92auFOoeqPjy1:b-1g2ktj) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.h#L280)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

it is required by the `DRAKE_DECLARE_` at the end of the file. Without it (I honestly do not know why) the compiler barks at you.
I decided to DECLARE/DEFINE on non-symbolic scalars since that's what we want in the long term, with an exception on T!=double for now. In the future we'd specialize DoSolve for the case AutoDiffXd to compute gradients analytically.
</blockquote></details>

@sherm1, do you recall the nuances of these DECLARE/DEFINE and when/why these forward declarations are needed?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-T2GR7-g_dSl6QRo3n:-N-TYP78DxlilQzKYYBF:b-y3wgk0) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

FYI @xuchenhan-tri (and @sherm1). In one of our f2f @xuchenhan-tri gave me really good suggestions on how to test the Newton solver in a unit test. I'll PR that separately next.
</blockquote></details>

FYI, this is the next follow up PR: #16940

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @amcastro-tri and @sherm1)

___
*[multibody/contact_solvers/sap/sap_solver.cc, line 373 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-UYCFT8ACmv2WML8MT:-N-UYCFT8ACmv2WML8MU:b-c22e4j) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc77f2285819d4d1779c5920117053434720e48/multibody/contact_solvers/sap/sap_solver.cc#L373)):*
> ```cpp
>   // TODO(amcastro-tri): Make use of mat::SolveLinearSystem() for a quick and
>   // dirty way to support AutoDiffXd, at least to build unit tests.
>   const Eigen::LDLT<MatrixX<T>> Hldlt(H);
> ```

nit, we should use LLT for slightly better performance.

**Review by sherm1 — COMMENTED** [review]
Punting to +@sammy-tri for Wednesday platform review (sorry Sammy!)
-@sherm1

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930#-:-N-VuTpCEgNLpo-7brZx:b4zl4os)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri, @sammy-tri, and @sherm1)

**Review by sammy-tri — COMMENTED** [review]
No issues from me, waiting for the remaining unresolved issues to be settled before final approval.

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930#-:-N-Zz3VZ4jy-8o7DqjJl:b-hqtor5)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri and @sherm1)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/sap_solver.h, line 280 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-PmE589wEcEvrkRU-w:-N-ciX5jCb4t7zpnm1B6:bpfwa8y) ([raw file](https://github.com/robotlocomotion/drake/blob/b65b3f64b2ffbcea56ef54e5572c6f006517a312/multibody/contact_solvers/sap/sap_solver.h#L280)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

With double only, you shouldn't need any specialization at all. With (fake) autodiff support, see [here](https://stackoverflow.com/questions/21112148/specialization-of-member-function-template-after-instantiation-error-and-order) for an explanation of the compiler error.
</blockquote></details>

nice, thanks!
___
*[multibody/contact_solvers/sap/sap_solver.cc, line 373 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-UYCFT8ACmv2WML8MT:-N-cibkI-wnMftjsBePU:b-gnt2qi) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc77f2285819d4d1779c5920117053434720e48/multibody/contact_solvers/sap/sap_solver.cc#L373)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, we should use LLT for slightly better performance.
</blockquote></details>

I am not going for performance here, I am going for stability.
Notice this is the dense version, which I am mostly providing for testing purposes. We already lost in performance when computing the dense H.

**Review by amcastro-tri — COMMENTED** [review]
no unresolved issues @sammy-tri, PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930#-:-N-cwdpF-b73pAd-P-GM:b-bhrjhr)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/sap_solver.cc, line 373 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16930#-N-UYCFT8ACmv2WML8MT:-N-cywRK6tCWclDqZbif:bg5tsot) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc77f2285819d4d1779c5920117053434720e48/multibody/contact_solvers/sap/sap_solver.cc#L373)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I am not going for performance here, I am going for stability.
Notice this is the dense version, which I am mostly providing for testing purposes. We already lost in performance when computing the dense H.
</blockquote></details>

Fair. A note to explain this choice would be appreciated.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16930#-:-N-czIUJC---ngVqkalm:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Pull request merged**
