### PR TITLE
Add numerical validation for shape specifications

### LINKED ISSUE #12038: [geometry]Shape specifications should validate themselves upon construction
The various shapes (`Sphere`, `Cylinder`, `Box`, `Mesh`, and `Convex`) defined in `shape_specification.h` all take numerical parameters that are only meaningful over a portion of the number line. Upon construction, they should validate those values such that once constructed, every consumer can rely on them being "correct".

### PR DESCRIPTION
**Pull request by tehbelinda**
Closes #12038

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12172)

### CODE REVIEW

**Comment by tehbelinda** [comment]
+@damrongguoy for feature review please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please

**Comment by tehbelinda** [comment]
oh neat, I'd prefer that too

**Comment by tehbelinda** [comment]
___
*[geometry/test/shape_specification_test.cc, line 320 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12172#-LqmkinmCgM5xhUfpNEg:-LqnitaO1RLh-hOMZpYb:b-4plnjz) ([raw file](https://github.com/robotlocomotion/drake/blob/ce0f36b2af4d5b02c2384cb4dcc306368aff4145/geometry/test/shape_specification_test.cc#L320)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Nit, use `DRAKE_EXPECT_THROWS_MESSAGE()` instead of `EXPECT_THROW` please. 
We don't have `DRAKE_EXPECT_NO_THROW`, so I guess `EXPECT_NO_THROW` is ok, depending on the platform reviewer.
</blockquote></details>

Ok, converted the EXPECT_THROWs

**Comment by tehbelinda** [comment]
___
*[geometry/test/shape_specification_test.cc, line 327 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12172#-Lqq_8WxD1FFq1XmmeJv:-LqqvrKM5iK697-cSsKv:butlcfa) ([raw file](https://github.com/robotlocomotion/drake/blob/d9773faff681373e5206795307954a40a4ae3ea4/geometry/test/shape_specification_test.cc#L327)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, you can use regular expression if it helps.  For example:
```C++
"Box width, depth and height should be > 0.*"
```
The `.*` means any strings.

Using the exact string is fine too.  It's completely optional.
</blockquote></details>

I see, thanks! 
Yeah I figure in this case the numbers were created just there and it's clear what the exact string should be so I might as well

**Comment by tehbelinda** [comment]
___
*[geometry/shape_specification.h, line 149 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12172#-Lqqadzy1osUi3Lq0DTg:-LqrZzWr5CyIprhmpH4y:bs4l8zj) ([raw file](https://github.com/robotlocomotion/drake/blob/d9773faff681373e5206795307954a40a4ae3ea4/geometry/shape_specification.h#L149)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Per f2f discussion, we'll check with users who use zero-volume boxes and see whether they really need them.

Set status to `resolved` for now.
</blockquote></details>

sounds good, I've talked to Evan about the plane/box one now too

**Comment by tehbelinda** [comment]
___
*[multibody/plant/test/block_on_halfspace.sdf, line 42 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12172#-LqrGYr4AD-UgK4VTebU:-Lqr_4pZ37CDBZtD5xjj:b-xagjwf) ([raw file](https://github.com/robotlocomotion/drake/blob/8866f2e0d2cd75bffc3afdd0480e456266759ff3/multibody/plant/test/block_on_halfspace.sdf#L42)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Nit, extra "since".
</blockquote></details>

ah thanks ><

**Comment by tehbelinda** [comment]
___
*[geometry/shape_specification.h, line 245 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12172#-LqmjyEQEQ5QUdbeZdS3:-Lqn0z9zAQ43OaXK09sM:ba77j41) ([raw file](https://github.com/robotlocomotion/drake/blob/ce0f36b2af4d5b02c2384cb4dcc306368aff4145/geometry/shape_specification.h#L245)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

One less space in front of `@throws` please.  Right now it's not aligned with other parameters.
</blockquote></details>

oops thanks

**Comment by tehbelinda** [comment]
___
*[multibody/plant/test/block_on_halfspace.sdf, line 43 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12172#-LqreANLBy_xp4eIxj-7:-LqreANLBy_xp4eIxj-8:bw65m2w) ([raw file](https://github.com/robotlocomotion/drake/blob/638caffafc375c8b0c7479d1fdf4727a54ac8d64/multibody/plant/test/block_on_halfspace.sdf#L43)):*
> ```
>                we need to set the box at -0.1/2=-0.05 along the z-axis. Since
>                the link itself has a pose of position '0 0 -1', the total offset
>                is thus '0 0 0.95'.
> ```

fyi +@edrumwri let me know if this is unclear

**Comment by tehbelinda** [comment]
-@edrumwri umm didn't mean to add you as assignee - just fyi for the inline comment

**Comment by tehbelinda** [comment]
I ran the Anzu build and it failed, though it looks like the same test fails in Anzu master + Drake master - should I wait till that is fixed or is there anything in Anzu I should look at?

**Comment by tehbelinda** [comment]
___
*[geometry/shape_specification.h, line 149 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12172#-Lqqadzy1osUi3Lq0DTg:-Lqw96ziEw1J5XCtRgfy:b-sz89yw) ([raw file](https://github.com/robotlocomotion/drake/blob/d9773faff681373e5206795307954a40a4ae3ea4/geometry/shape_specification.h#L149)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I note that there was a change to `bock_on_halfspace.sdf`. Is that the only site that required zero-volume boxes? If so, this should be updated.
</blockquote></details>

as per f2f discussion, this was the only one left besides the ones that could be converted to zero spheres

**Comment by tehbelinda** [comment]
___
*[multibody/plant/test/block_on_halfspace.sdf, line 43 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12172#-LqreANLBy_xp4eIxj-7:-Lqw9G1J99SAHhsZ4IIX:b-xzwm4m) ([raw file](https://github.com/robotlocomotion/drake/blob/638caffafc375c8b0c7479d1fdf4727a54ac8d64/multibody/plant/test/block_on_halfspace.sdf#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: As I look at the test; this comment seems misleading. There's a lot of detail that really doesn't matter. All that really matters is that the pose of this geometry in the world frame is fixed (the test assumes the geometry of the plane). In fact the test doesn't seem to be affected by *any* of the geometric details.  All it cares about is:

- There be a single collision geometry for "ground" and "box".
- The pose of "ground-collision" in world have an identity rotation and origin at <0, 0, 1>.

All other geometric details are hard-coded in the test. Updating the documentation to make this clear would represent an definite improvement in this file.
</blockquote></details>

ok, simplifying this

**Comment by tehbelinda** [comment]
while you're at it +@seancurtis-tri for platform review please!

**Comment by tehbelinda** [comment]
redid the Anzu build and it's all good now :+1:

**Comment by tehbelinda** [comment]
___
*[geometry/shape_specification.cc, line 31 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12172#-LrAP4MYCh8nCYjcmURn:-LrFcvCzAvkIRqBKN8tH:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/46919d6e1ca7a17a776309bc3269d131c4f6f8cf/geometry/shape_specification.cc#L31)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: "...should __*both*__ be..." and then "...(__*were*__ {} and {}, __*respectively*__).

Same note applies to the box dimensions.
</blockquote></details>

done

**Pull request merged**
