### PR TITLE
Use a more recent Pybind11 fork

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Updates Pybind11 [to this.](https://github.com/RobotLocomotion/pybind11/tree/drake)

[Modifies deprecated syntax.](http://pybind11.readthedocs.io/en/stable/upgrade.html)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7494)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab  please.  (Flake)

**Comment by jamiesnape** [comment]
:lgtm: (please run a Mac build, though)

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7494#-:-Kz6M8cFmdvRPprnjtts:b8saufi)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please.

**Comment by m-chaturvedi** [comment]
+@sherm1 for platform review, please.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7494#-:-KzAOxSW9oURR-53-7v1:bnfp4nl)*

**Pull request merged**
