### PR TITLE
Add sos2 constraint without logarithmic binning

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6759)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@gizatt for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-:-Kqa3UQ7TaKBNKJg8F-h:biagjkq)*

**Comment by gizatt** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-KqaGbrE64X1__o8-cmV:-KqaGbrE64X1__o8-cmW:b-92lici) ([raw file](https://github.com/robotlocomotion/drake/blob/9117fd4acb999dc5e27be917498f0b803c0af015/drake/solvers/mixed_integer_optimization_util.h#L91)):*
> ```objc
> 
> /**
>  * Adds the special ordered set 2 (SOS2) constraint. y(i) takes binary values
> ```

Maybe refer to the above, more complete definition of the SOS2 constraint?

---

*[drake/solvers/mixed_integer_optimization_util.h, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-KqaGWALEdrvw1pPV67U:-KqaGWALEdrvw1pPV67V:b2qu994) ([raw file](https://github.com/robotlocomotion/drake/blob/9117fd4acb999dc5e27be917498f0b803c0af015/drake/solvers/mixed_integer_optimization_util.h#L97)):*
> ```objc
>  * </pre>
>  * @param prog The optimization program to which the SOS2 constraint is added.
>  * @param lambda At most two entries in λ can be strictly positive, and these
> ```

Might as well point out that`\lambda.sum() = 1`.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-KqaF_FurCYo6aPTFqjX:-KqaF_FurCYo6aPTFqjY:b-6mcpzj) ([raw file](https://github.com/robotlocomotion/drake/blob/9117fd4acb999dc5e27be917498f0b803c0af015/drake/solvers/test/mixed_integer_optimization_util_test.cc#L60)):*
> ```cpp
>   auto y_assignment = prog.AddBoundingBoxConstraint(0, 1, y);
> 
>   // We assign the binary variables y with value i, expressed in Gray code.
> ```

This comment is only correct in the `logarithmic_binning == True` case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6759)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-KqaGbrE64X1__o8-cmV:-KqaKYffUaT626bdoyYl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9117fd4acb999dc5e27be917498f0b803c0af015/drake/solvers/mixed_integer_optimization_util.h#L91)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Maybe refer to the above, more complete definition of the SOS2 constraint?
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-KqaGWALEdrvw1pPV67U:-KqaKZ9Gwb0pUCh2ppGD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9117fd4acb999dc5e27be917498f0b803c0af015/drake/solvers/mixed_integer_optimization_util.h#L97)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Might as well point out that`\lambda.sum() = 1`.
</blockquote></details>

Done.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-KqaF_FurCYo6aPTFqjX:-KqaKZh1Xw28Sudb62nG:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/9117fd4acb999dc5e27be917498f0b803c0af015/drake/solvers/test/mixed_integer_optimization_util_test.cc#L60)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

This comment is only correct in the `logarithmic_binning == True` case
</blockquote></details>

Done. Good call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6759)*

**Comment by gizatt** [comment]
:lgtm: Looks great!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-:-KqcuaDrPwPcLlBzlGv0:b-2t11ox)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-:-KqcvEL02JC5NXsY4q78:b-vt9vbo)*

**Comment by soonho-tri** [comment]
Platform :lgtm: (aside a BTW/typo)

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 103 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-Kqd14VHhAtHt-vbOVeA:-Kqd14VHhAtHt-vbOVeB:b-gbq5pi) ([raw file](https://github.com/robotlocomotion/drake/blob/39d21390eca0891eae5635ec7d978257735375f8/drake/solvers/mixed_integer_optimization_util.h#L103)):*
> ```objc
>  * two entries should sum up to 1.
>  * @param y y(i) takes binary value, and determines which two entries in λ can
>  * be strictly positive. Throw a runtime error is y.rows() != lambda.rows() - 1.
> ```

BTW, nit,  a typo: `Throw a runtime error *is*` -> `Throw a runtime error *if*`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-:-Kqd26WBaVftwvKT3S1v:b4x7pug)*

**Comment by soonho-tri** [comment]
Also tested locally on a mac. The test passed.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-:-Kqd2SdkjWqTXpbjJgil:bccblsz)*

**Comment by hongkai-dai** [comment]
Thanks for testing it on Mac!

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 103 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-Kqd14VHhAtHt-vbOVeA:-Kqd30xLXSj9NwJwWdeJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/39d21390eca0891eae5635ec7d978257735375f8/drake/solvers/mixed_integer_optimization_util.h#L103)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit,  a typo: `Throw a runtime error *is*` -> `Throw a runtime error *if*`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6759#-:-Kqd32Pl_EM-fvqpOq_t:b-wi48ll)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6759)*

**Pull request merged**
