### PR TITLE
Port drake_assert unit tests to Bazel

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #5268.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6151)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@sammy-tri for platform review, please.

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/drake_assert_test_compile.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6151#-KkpUdsgh1FonRbqH1Pw:-KkpUdsgh1FonRbqH1Px:b-rcpgu9) ([raw file](https://github.com/robotlocomotion/drake/blob/eed6c398dc2357af540a3bcc4cb481403bd8ddeb/drake/common/test/drake_assert_test_compile.cc#L7)):*
> ```cpp
> int main(int argc, const char* argv[]) {
> // The build system toggles this guard.  The program should compile
> // and pass when undefined, and should fail to compile when defined.
> ```

BTW, huh. looks like reviewable is mis-formatting the diff somehow. I had to look at r1 expanded by itself to figure out the final result.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6151#-:-KkpVfoEDEY41lPD-X35:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/test/drake_assert_test_compile.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6151#-KkpUdsgh1FonRbqH1Pw:-Kkp_npflqcIcb328rgN:bxew7wl) ([raw file](https://github.com/robotlocomotion/drake/blob/eed6c398dc2357af540a3bcc4cb481403bd8ddeb/drake/common/test/drake_assert_test_compile.cc#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, huh. looks like reviewable is mis-formatting the diff somehow. I had to look at r1 expanded by itself to figure out the final result.
</blockquote></details>

Weird.  My rbottom..r1 diff looks okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6151)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/drake_assert_test_compile.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6151#-Kkpd5axJVaymRkpVIOn:-Kkpd5ayvWKFnkGF9Mzq:b-12gwzb) ([raw file](https://github.com/robotlocomotion/drake/blob/eed6c398dc2357af540a3bcc4cb481403bd8ddeb/drake/common/test/drake_assert_test_compile.cc#L7)):*
> ```cpp
> int main(int argc, const char* argv[]) {
> // The build system toggles this guard.  The program should compile
> // and pass when undefined, and should fail to compile when defined.
> ```

aha. i may be a victim of poor color perception and bad monitor settings. This line appears white to me on one computer, and barely pink on another.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6151)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6151#-:-KkqCOY3wyJz7uxhzqnR:bnfp4nl)*

**Pull request merged**
