### PR TITLE
MBT defaults bodies to be free

### PR DESCRIPTION
**Pull request by amcastro-tri**
Bodies that are not connected by any joint are defaulted to be free.
This PR updates the `floating_body_test` to use MBP instead, which greatly reduces boilerplate already implemented in MBP.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8371)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@hongkai-dai for feature review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-:-L7aXoJEASiW-jQOpDBL:bltox9h)*

**Comment by hongkai-dai** [comment]
:lgtm: A few minor comments +@soonho-tri for platform review please.

---

Reviewed 8 of 16 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[multibody/multibody_tree/multibody_tree.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eIAMlVAKQcbLE4FEM:-L7eIAMlVAKQcbLE4FEN:b32ervc) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.cc#L61)):*
> ```cpp
> void MultibodyTree<T>:: AddQuaternionFreeMobilizerToAllBodiesWithNoMobilizer() {
>   DRAKE_DEMAND(!topology_is_valid());
>   // Skip the world.
> ```

I see, so it skips the world. Maybe mention this in the method documentation in the header file?

---

*[multibody/multibody_tree/multibody_tree.cc, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eKg8IOk4pFGLoNUWq:-L7eKg8IOk4pFGLoNUWr:b-1jqqa3) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.cc#L81)):*
> ```cpp
>   const BodyTopology& body_topology = get_topology().get_body(body.index());
>   const QuaternionFloatingMobilizer<T>* mobilizer =
>       dynamic_cast<const QuaternionFloatingMobilizer<T>*>(
> ```

Not sure if we want to use RTTI here. Maybe add a TODO to remove RTTI in the future?

---

*[multibody/multibody_tree/multibody_tree.h, line 908 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eGMrYuO0QnBlXhK6a:-L7eGMrYuO0QnBlXhK6b:baxxgjo) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.h#L908)):*
> ```objc
> 
>   /// Alternative signature of SetFreeBodyPoseOrThrow() to store the pose
>   /// `X_WB` of `body` in the provided `state`.
> ```

`context` is not described in the documentation, consider to include it?

---

*[multibody/multibody_tree/multibody_tree.h, line 1788 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eH0k9lCn8luVmo9O4:-L7eH0k9lCn8luVmo9O5:b3qcgfc) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.h#L1788)):*
> ```objc
>   // have a mobilizer. The mobilizer is between each body and the world. To be
>   // called at Finalize().
>   void AddQuaternionFreeMobilizerToAllBodiesWithNoMobilizer();
> ```

Does the world body have a mobilizer? If not, will a quaternion free mobilizer be added to the world body?

---

*[multibody/multibody_tree/multibody_tree.h, line 1793 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eHOhohG6OF2QQV0CW:-L7eHOhohG6OF2QQV0CX:b-mdiueh) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.h#L1793)):*
> ```objc
>   // If `body` is a free body in the model, this method will return the
>   // QuaternionFloatingMobilizer for the body. If the body is not free but it
>   // is connected to the model by a Joint, this method will throw an exception.
> ```

throw a logic error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-:-L7eMM3pqnVHvDU0idYx:bgjnpki)*

**Comment by amcastro-tri** [comment]
The CI failure report is trange [here](https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=969397). It shows a call to `.cast()` while in reality the codes spells `.cast<T>()`. What am I missing?

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by amcastro-tri** [comment]
ok, tested locally. gcc for some reason does need us to spell out `.template cast<T>()`.

**Comment by amcastro-tri** [comment]
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eIAMlVAKQcbLE4FEM:-L7efk-7gyhp-m0rgACX:b-10fgcx) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.cc#L61)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, so it skips the world. Maybe mention this in the method documentation in the header file?
</blockquote></details>

Done. Added notes in the header.

---

*[multibody/multibody_tree/multibody_tree.cc, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eKg8IOk4pFGLoNUWq:-L7eg4LUZ95y_SN4ot03:b-60yhfs) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.cc#L81)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not sure if we want to use RTTI here. Maybe add a TODO to remove RTTI in the future?
</blockquote></details>

It's an implementation detail and it really costs nothing in this method. How else would you do it? maybe make mobilizers have a method `is_floating_mobilizer()`? or something of the like?
What would the TODO say?

---

*[multibody/multibody_tree/multibody_tree.h, line 908 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eGMrYuO0QnBlXhK6a:-L7eh8NMhnLm0uNSzxpJ:b-3xvqmt) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.h#L908)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`context` is not described in the documentation, consider to include it?
</blockquote></details>

Done. I was trying to simplify the docs and probably over did it. `Context` must always be passed around since not only contains the state but also things like parameters (not yet, but it will).

---

*[multibody/multibody_tree/multibody_tree.h, line 1788 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eH0k9lCn8luVmo9O4:-L7ehZM2oeEONpnv3zCb:b6qdnov) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.h#L1788)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Does the world body have a mobilizer? If not, will a quaternion free mobilizer be added to the world body?
</blockquote></details>

Added clarification.

---

*[multibody/multibody_tree/multibody_tree.h, line 1793 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eHOhohG6OF2QQV0CW:-L7ehzo3Dh31ovyF5aai:b-v7fjaf) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.h#L1793)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

throw a logic error?
</blockquote></details>

I gave them a more generic `std::exception`, but done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8371)*

**Comment by hongkai-dai** [comment]
Review status: 6 of 9 files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/multibody_tree.cc, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eKg8IOk4pFGLoNUWq:-L7evPTjxG9lqLdW0zfz:b-r6jd6j) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.cc#L81)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

It's an implementation detail and it really costs nothing in this method. How else would you do it? maybe make mobilizers have a method `is_floating_mobilizer()`? or something of the like?
What would the TODO say?
</blockquote></details>

I was thinking about `static_cast`, but I think `dynamic_cast` is also good here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8371)*

**Comment by soonho-tri** [comment]
First-pass completed. A few questions + BTWs. PTAL.

---

Reviewed 7 of 16 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.cc, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eKg8IOk4pFGLoNUWq:-L7f90or29lAULmB8fpf:bftgbyp) ([raw file](https://github.com/robotlocomotion/drake/blob/08e9975731b030ac27dd077afc7ba9531fbd8dc0/multibody/multibody_tree/multibody_tree.cc#L81)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I was thinking about `static_cast`, but I think `dynamic_cast` is also good here.
</blockquote></details>

FYI, `static_cast` is not going to work unless we have a knowledge that the casting works all the time. `is_floating_mobilizer` is basically re-implementing RTTI which is recommended not to do in our C++ guide.

---

*[multibody/multibody_tree/multibody_tree.h, line 888 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7eyZBymajC_C__n0CQ:-L7eyZBymajC_C__n0CR:b-655psx) ([raw file](https://github.com/robotlocomotion/drake/blob/f22c2e8c9080ca2ca0d21e5de3017ec7b289eef6/multibody/multibody_tree/multibody_tree.h#L888)):*
> ```objc
>   /// frame W.
>   /// @note In general setting the pose and/or velocity of a body in the model
>   /// would involve a complex inverse kinematics problem. This method allow us
> ```

BTW, META, This method `allow` -> This method `allows`.

---

*[multibody/multibody_tree/multibody_tree.h, line 1812 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7f0VLF4Z14p_LblXcS:-L7f0VLF4Z14p_LblXcT:bwhvhtq) ([raw file](https://github.com/robotlocomotion/drake/blob/f22c2e8c9080ca2ca0d21e5de3017ec7b289eef6/multibody/multibody_tree/multibody_tree.h#L1812)):*
> ```objc
>   // @throws std::exception if called pre-finalize.
>   // @throws std::exception if called on the world body.
>   const QuaternionFloatingMobilizer<T>& GetFreeBodyMobilizerOrThrow(
> ```

Is it too bad to make this method `public` and get rid of `friend class MultibodyTreeTester`?

---

*[multibody/multibody_tree/multibody_tree.h, line 1821 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7f0n1PsEqM6at88mXg:-L7f0n1PsEqM6at88mXh:b4d06w2) ([raw file](https://github.com/robotlocomotion/drake/blob/f22c2e8c9080ca2ca0d21e5de3017ec7b289eef6/multibody/multibody_tree/multibody_tree.h#L1821)):*
> ```objc
> 
>   // Helper method for throwing an exception within public methods that should
>   // not be called pre-finalize. The invoking method should pass it's name so
> ```

BTW, `it's` -> `its`.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 153 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7fGmRadOBupR7LruUy:-L7fGmRadOBupR7LruUz:b-ylqc4s) ([raw file](https://github.com/robotlocomotion/drake/blob/91cf850e1fe0298270e7069de50256d283419b5f/multibody/multibody_tree/multibody_plant/multibody_plant.h#L153)):*
> This PR updates the floating_body_test to use MBP instead, which greatly reduces boilerplate already implemented in MBP.

BTW, the price is that this class is not `final` anymore. Can you double-check if this property is something you want to give up to implement a test-only class?

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 645 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7fIg9DRYiy4nMsFXSf:-L7fIg9DRYiy4nMsFXSg:b-69brmw) ([raw file](https://github.com/robotlocomotion/drake/blob/f22c2e8c9080ca2ca0d21e5de3017ec7b289eef6/multibody/multibody_tree/multibody_plant/multibody_plant.h#L645)):*
> ```objc
>       systems::VectorBase<T>* generalized_velocity) const override;
> 
>   void DoMapVelocityToQDot(
> ```

Are these new methods covered by existing test cases?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-:-L7fImDaaLfDiK1JfFX0:bap3uqo)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.h, line 1812 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7f0VLF4Z14p_LblXcS:-L7fJ_Z6H46WshWYhUG6:b65eixb) ([raw file](https://github.com/robotlocomotion/drake/blob/f22c2e8c9080ca2ca0d21e5de3017ec7b289eef6/multibody/multibody_tree/multibody_tree.h#L1812)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Is it too bad to make this method `public` and get rid of `friend class MultibodyTreeTester`?
</blockquote></details>

I am trying to keep the `Mobilizer` classes as an implementation detail so that users only need to specify bodies and joints. I actually like the tester idea since I think in the future it'll allow me to test even more internals. To answer your question; yes, I do want this to be private. I feel users might get confused if they see it in the public API.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 153 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7fGmRadOBupR7LruUy:-L7fK0ZW9FcVSf1M9Vcu:b3o2wi5) ([raw file](https://github.com/robotlocomotion/drake/blob/91cf850e1fe0298270e7069de50256d283419b5f/multibody/multibody_tree/multibody_plant/multibody_plant.h#L153)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> This PR updates the floating_body_test to use MBP instead, which greatly reduces boilerplate already implemented in MBP.

BTW, the price is that this class is not `final` anymore. Can you double-check if this property is something you want to give up to implement a test-only class?
</blockquote></details>

BTW yes, I did double-check. Right now for this PR I am using this to write a test class. However, I think it'll be very common for users to write their specific systems inheriting from MBP, which would allow them to add whatever sugar they might want. Something it is more difficult to get right by placing the MBP inside a Diagram (I tried. It gets awful because you'd need to extract your sub-system context, state, etc and is very error prone).

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 645 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7fIg9DRYiy4nMsFXSf:-L7fKcs-aCH4j2cPDEai:b-l7tktj) ([raw file](https://github.com/robotlocomotion/drake/blob/f22c2e8c9080ca2ca0d21e5de3017ec7b289eef6/multibody/multibody_tree/multibody_plant/multibody_plant.h#L645)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Are these new methods covered by existing test cases?
</blockquote></details>

The numerical integration in `floating_body_test.cc` covers them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8371)*

**Comment by amcastro-tri** [comment]
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 645 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-L7fIg9DRYiy4nMsFXSf:-L7fT_MM03MgQJp0s9w4:bv1aqdz) ([raw file](https://github.com/robotlocomotion/drake/blob/f22c2e8c9080ca2ca0d21e5de3017ec7b289eef6/multibody/multibody_tree/multibody_plant/multibody_plant.h#L645)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

The numerical integration in `floating_body_test.cc` covers them.
</blockquote></details>

Added new unit tests in `multibody_plant_test.cc`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8371)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8371#-:-L7fXV2xjHFYDNZERVnv:bnfp4nl)*

**Pull request merged**
