### PR TITLE
[geometry] Detect problems in hydroelastic tetrahedral meshes

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This PR is a prequel to #19550. We work on detect_zero_simplex in this PR, and 19550 will use detect_zero_simplex in volume_mesh_refiner.

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@joemasterjohn for feature review, please.

Thanks to @mitiguy and @SeanCurtis-TRI for helping me with documentation.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-:-NZ3WjVTD6hAo2t-XZ1h:bkptnco)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
@DamrongGuoy sorry I missed this one before I took PTO. Taking a look today.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-:-N_-2g188M3b1fS60yYI:b8mmbw1)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
Feature pass done. From a correctness standpoint, everything looks great. But from a readability and efficiency standpoint I think this could be improved a bit. I took a crack at restructuring the code in a more efficient/readable way. Try it out and see what you think. If you hard disagree with how I rewrote it, feel free to let me know and I can lgtm this as is with 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-:-N_bP0VjBJg70DxB_jGx:b-whycvx)* status: 6 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/detect_zero_simplex.h` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_b4OxCCApDPvI4Gq1l:-N_b4OxCCApDPvI4Gq1m:b3yha3q) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.h#L7)):*
> ```objc
>  on a mesh with this defect will have zero pressure in its interior.
>  Because signed distance is defined at vertices and interpolated everywhere
>  else, detection focuses on simplices (tetrahedra, triangles, edges).
> ```

We could say "positve dimensional simplices" to be a bit more accurate and specific about not including 0-simplices (vertices).
___
*[`geometry/proximity/detect_zero_simplex.h` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_bARzs9-Wk9Wknz2D4:-N_bARzs9-Wk9Wknz2D5:b18lpp6) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.h#L33)):*
> ```objc
>          mesh.
>  */
> std::vector<int> DetectZeroTetrahedron(const VolumeMesh<double>& mesh_M);
> ```

nit: We're using the terms "problematic" and "zero" here and they both aren't very informative unless you look up the definitions in this documentation. I would be explicit at the cost of being verbose. This way a reader is relatively informed at the call sight:



_Suggestion:_
```objc
std::vector<int> DetectTetrahedronWithAllBoundaryVertices(const VolumeMesh<double>& mesh_M);
```
___
*[`geometry/proximity/detect_zero_simplex.h` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_bAAGNBLL38gI-k1sK:-N_bAAGNBLL38gI-k1sL:b-atz3tu) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.h#L44)):*
> ```objc
>          tetrahedral mesh.
>  */
> std::vector<SortedTriplet<int>> DetectZeroInteriorTriangle(
> ```

nit: similarly



_Suggestion:_
```objc
std::vector<SortedTriplet<int>> DetectInteriorTrianglesWithAllBoundaryVertices(
```
___
*[`geometry/proximity/detect_zero_simplex.h` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_bAK9w1qYBpJuJMUdU:-N_bAK9w1qYBpJuJMUdV:b-atz3tu) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.h#L56)):*
> ```objc
>          tetrahedral mesh.
>  */
> std::vector<SortedPair<int>> DetectZeroInteriorEdge(
> ```

nit: similarly



_Suggestion:_
```objc
std::vector<SortedPair<int>> DetectInteriorEdgesWithAllBoundaryVertices(
```
___
*[`geometry/proximity/detect_zero_simplex.cc` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_b8gNu-D5itrZWM0JN:-N_b8gNu-D5itrZWM0JO:b-i8o8rb) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.cc#L2)):*
> ```cpp
> #include "drake/geometry/proximity/detect_zero_simplex.h"
> ```

My intuition about this code is to actually squash it down into one big function, reasoning:
1) Will you ever need just one of either "problematic" tets, faces, edges? My understancding is that the code fixing the meshes will always use all of them.
2) Considering (1) to be true and the typical use case being to call all 3 DetectFoo functions every time, then there is wasted overhead in re-computing the boundary faces, edges, vertices.
3) There's no reason to allocate dynamic storage for all of the interior edges/faces, they're only used in a single loop to ask if they are null and the vast majority are NOT null.

My suggestion (not compiled or tested):
```
// Data to store tets, faces, edges and verts that pass a particular query
struct MeshQueryData {
  std::set<int> tetrahedra;
  std::set<SortedTriplet<int>> faces;
  std::set<SortedPair<int>> edges;
  std::set<int> vertices;
}

MeshQueryData
GetBoundaryElements(const VolumeMesh<double> &mesh_M) {
  MeshQueryData data;

  const std::vector<std::array<int, 3>> boundary_unordered_faces =
      IdentifyBoundaryFaces(mesh_M.tetrahedra());

  for (const auto &face : boundary_unordered_faces) {
    data.faces.insert(SortedTriplet<int>(face[0], face[1], face[2]));
    data.edges.insert(SortedPair<int>(face[0], face[1]));
    data.edges.insert(SortedPair<int>(face[1], face[2]));
    data.edges.insert(SortedPair<int>(face[2], face[0]));
    data.vertices.insert(face[0]);
    data.vertices.insert(face[1]);
    data.vertices.insert(face[2]);
  }

  return data;
}

MeshQueryData DetectInteriorSimplicesWithAllBoundaryVertices(
    const VolumeMesh<double> &mesh_M) {
  MeshQueryData data;

  // Get boundary data
  const MeshQueryData boundary_data = GetBoundaryElements(mesh_M);

  const auto &is_boundary_vert =
      [boundary_data](int i) { return boundary_data.count(i) > 0; }

  for (int i = 0; i < mesh_M.num_elements(); ++i) {
    const VolumeElement &tet = mesh_M.element(i);

    // Store boundary query for verts of this tet.
    std::array<bool, 4> is_boundary(
        is_boundary_vert(tet.vertex(0)), is_boundary_vert(tet.vertex(1)),
        is_boundary_vert(tet.vertex(2)), is_boundary_vert(tet.vertex(3)));

    // If all vertices of this tet are boundary, include it.
    if (std::all_of(is_boundary.begin(), is_boundary.end(),
                    [](bool v) { return v; })) {
      data.tetrahedra.insert(i);
    }

    // Check the faces of this tet, if one is interior and all vertices on
    // boundary, include it.
    const int faces[4][3] = {{1, 2, 3}, {3, 2, 0}, {2, 1, 0}, {1, 3, 0}};

    for (int i = 0; i < 4; ++i) {
      SortedTriplet<int> face(tet.vertex(faces[i][0]), tet.vertex(faces[i][1]),
                              tet.vertex(faces[i][2]));
      if (boundary_data.faces.count(face) == 0 && is_boundary(faces[i][0]) &&
          is_boundary(faces[i][1]) && is_boundary(faces[i][2])) {
        data.faces.insert(face);
      }
    }

    // Check the edges of this tet, if one is interior and all vertices on
    // boundary, inclue it.
    const int edges[6][2] = {{0, 1}, {0, 2}, {0, 3}, {1, 2}, {1, 3}, {2, 3}};

    for (int i = 0; i < 6; ++i) {
      SortedPair<int> edge(tet.vertex(edges[i][0]), tet.vertex(edges[i][1]));
      if (boundary_data.edges.count(edge) == 0 && is_boundary(edges[i][0]) &&
          is_boundary(edges[i][1])) {
        data.edges.insert(edge);
      }
    }
  }

  return data;
}
```
___
*[`geometry/proximity/test/detect_zero_simplex_test.cc` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_bNsUXDtXUKFdjXkTb:-N_bNsUXDtXUKFdjXkTc:bn9s3nn) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/test/detect_zero_simplex_test.cc#L2)):*
> ```cpp
> #include "drake/geometry/proximity/detect_zero_simplex.h"
> ```

nit: With the proposed code restructuring I wrote above, you could refactor this test into just three GTEST_TESTs that test the null output of all simplices:
1) Nominal case, no null tet/face/edge, (i.e. v4 = (v0+v1+v2+v3) / 4)
2) Your one null interior triangle case (will also have 2 null tets, but 0 null edges).
3) Your one null interior edge case.

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699)* status: 6 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
*as is with some renaming and code shuffling nits.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-:-N_bQSQD3c-a2sTj7JEE:bsqzrk6)* status: 6 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/detect_zero_simplex.h` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_b4OxCCApDPvI4Gq1l:-NcxxusKDVipIOHNln5Y:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.h#L7)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

We could say "positve dimensional simplices" to be a bit more accurate and specific about not including 0-simplices (vertices).
</blockquote></details>

Done.
___
*[`geometry/proximity/detect_zero_simplex.h` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_bARzs9-Wk9Wknz2D4:-Ncxz1Qx7QDRmaojyNQB:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.h#L33)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: We're using the terms "problematic" and "zero" here and they both aren't very informative unless you look up the definitions in this documentation. I would be explicit at the cost of being verbose. This way a reader is relatively informed at the call sight:
</blockquote></details>

Done.
___
*[`geometry/proximity/detect_zero_simplex.h` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_bAAGNBLL38gI-k1sK:-NcxzzhJ8aEJJjOMtHbb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.h#L44)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: similarly
</blockquote></details>

Done.
___
*[`geometry/proximity/detect_zero_simplex.h` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_bAK9w1qYBpJuJMUdU:-Ncy-uPl91QdTrGdDJKd:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.h#L56)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: similarly
</blockquote></details>

Done.
___
*[`geometry/proximity/detect_zero_simplex.cc` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_b8gNu-D5itrZWM0JN:-Ncywy4V9sSe3w4CWz46:b2k37jq) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/detect_zero_simplex.cc#L2)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

My intuition about this code is to actually squash it down into one big function, reasoning:
1) Will you ever need just one of either "problematic" tets, faces, edges? My understancding is that the code fixing the meshes will always use all of them.
2) Considering (1) to be true and the typical use case being to call all 3 DetectFoo functions every time, then there is wasted overhead in re-computing the boundary faces, edges, vertices.
3) There's no reason to allocate dynamic storage for all of the interior edges/faces, they're only used in a single loop to ask if they are null and the vast majority are NOT null.

My suggestion (not compiled or tested):
```
// Data to store tets, faces, edges and verts that pass a particular query
struct MeshQueryData {
  std::set<int> tetrahedra;
  std::set<SortedTriplet<int>> faces;
  std::set<SortedPair<int>> edges;
  std::set<int> vertices;
}

MeshQueryData
GetBoundaryElements(const VolumeMesh<double> &mesh_M) {
  MeshQueryData data;

  const std::vector<std::array<int, 3>> boundary_unordered_faces =
      IdentifyBoundaryFaces(mesh_M.tetrahedra());

  for (const auto &face : boundary_unordered_faces) {
    data.faces.insert(SortedTriplet<int>(face[0], face[1], face[2]));
    data.edges.insert(SortedPair<int>(face[0], face[1]));
    data.edges.insert(SortedPair<int>(face[1], face[2]));
    data.edges.insert(SortedPair<int>(face[2], face[0]));
    data.vertices.insert(face[0]);
    data.vertices.insert(face[1]);
    data.vertices.insert(face[2]);
  }

  return data;
}

MeshQueryData DetectInteriorSimplicesWithAllBoundaryVertices(
    const VolumeMesh<double> &mesh_M) {
  MeshQueryData data;

  // Get boundary data
  const MeshQueryData boundary_data = GetBoundaryElements(mesh_M);

  const auto &is_boundary_vert =
      [boundary_data](int i) { return boundary_data.count(i) > 0; }

  for (int i = 0; i < mesh_M.num_elements(); ++i) {
    const VolumeElement &tet = mesh_M.element(i);

    // Store boundary query for verts of this tet.
    std::array<bool, 4> is_boundary(
        is_boundary_vert(tet.vertex(0)), is_boundary_vert(tet.vertex(1)),
        is_boundary_vert(tet.vertex(2)), is_boundary_vert(tet.vertex(3)));

    // If all vertices of this tet are boundary, include it.
    if (std::all_of(is_boundary.begin(), is_boundary.end(),
                    [](bool v) { return v; })) {
      data.tetrahedra.insert(i);
    }

    // Check the faces of this tet, if one is interior and all vertices on
    // boundary, include it.
    const int faces[4][3] = {{1, 2, 3}, {3, 2, 0}, {2, 1, 0}, {1, 3, 0}};

    for (int i = 0; i < 4; ++i) {
      SortedTriplet<int> face(tet.vertex(faces[i][0]), tet.vertex(faces[i][1]),
                              tet.vertex(faces[i][2]));
      if (boundary_data.faces.count(face) == 0 && is_boundary(faces[i][0]) &&
          is_boundary(faces[i][1]) && is_boundary(faces[i][2])) {
        data.faces.insert(face);
      }
    }

    // Check the edges of this tet, if one is interior and all vertices on
    // boundary, inclue it.
    const int edges[6][2] = {{0, 1}, {0, 2}, {0, 3}, {1, 2}, {1, 3}, {2, 3}};

    for (int i = 0; i < 6; ++i) {
      SortedPair<int> edge(tet.vertex(edges[i][0]), tet.vertex(edges[i][1]));
      if (boundary_data.edges.count(edge) == 0 && is_boundary(edges[i][0]) &&
          is_boundary(edges[i][1])) {
        data.edges.insert(edge);
      }
    }
  }

  return data;
}
```
</blockquote></details>

Per f2f discussion, the answer to your question (1) is false.  The next PR will use one of the three functions at a time and change the mesh in between those calls.

Instead of the proposed restructure, I tried to make the code easier to read and added a TODO to create a class to store and update information as needed.
___
*[`geometry/proximity/test/detect_zero_simplex_test.cc` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-N_bNsUXDtXUKFdjXkTb:-Ncz-mwQ8FbBH5q1DMqD:b-efo8od) ([raw file](https://github.com/RobotLocomotion/drake/blob/344330267d403d6d0307b34a1c4c45d636ba4225/geometry/proximity/test/detect_zero_simplex_test.cc#L2)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: With the proposed code restructuring I wrote above, you could refactor this test into just three GTEST_TESTs that test the null output of all simplices:
1) Nominal case, no null tet/face/edge, (i.e. v4 = (v0+v1+v2+v3) / 4)
2) Your one null interior triangle case (will also have 2 null tets, but 0 null edges).
3) Your one null interior edge case.
</blockquote></details>

I kept the same structure of the test because we can't do the code restructuring.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: thanks! +@xuchenhan-tri for platform, if you still have time today.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-:-NdgQzIt2q0N2qCEDx0X:b-wgifjy)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`geometry/proximity/detect_zero_simplex.cc` line 100 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-NdgPgoq9SiPYGT5gASj:-NdgPgor7U5sp_ldYQGs:b-w454ee) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6121e3bf9525f0eca1a234198cf2881883a6b01/geometry/proximity/detect_zero_simplex.cc#L100)):*
> ```cpp
>   const std::unordered_set<int> boundary_vertex_set =
>       GetBoundaryVertexSet(mesh_M);
> ```

Totally optional, but could write a small lambda to improve readability:
```
auto is_boundary_tet = [&boundary_vertex_set](const VolumeElement& tet) {
  for (int i = 0; i < 4; ++i) {
    if (boundary_vertex_set.count(tet.vertex(i)) < 1) return false;
  }
  return true;
}
```
then below
```
if (is_boundary_tet(tetrahedron)) {
  null_tetrahedra.push_back(tetrahedron_index);
}
```

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-:-NdgeTRY6XQIaHFr_4xw:bzus18)* status: 2 unresolved discussions

___
*[`geometry/proximity/detect_zero_simplex.h` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-NdgZ87P9zow2_1LSY3v:-NdgZ87Q2b2insYrciVJ:br2fo4m) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6121e3bf9525f0eca1a234198cf2881883a6b01/geometry/proximity/detect_zero_simplex.h#L5)):*
> ```objc
> /* @file Detects if a tetrahedral mesh evaluates to zero signed-distance
>  anywhere in its interior. A hydroelastic pressure field built
>  on a mesh with this defect will have zero pressure in its interior.
> ```

BTW, is having zero pressure the only type of problem we care about for a hydro tet? What about a tet with its vertices on the same equi-pressure surface that consequently has constant pressure in the tet. Are we worried about those too?



_Code quote:_
```objc
will have zero pressure in its interior
```
___
*[`geometry/proximity/detect_zero_simplex.cc` line 41 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-NdgaOad8SpMrjDCG5j_:-NdgaOad8SpMrjDCG5ja:bjn238m) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6121e3bf9525f0eca1a234198cf2881883a6b01/geometry/proximity/detect_zero_simplex.cc#L41)):*
> ```cpp
> }
> 
> std::set<SortedTriplet<int>> GetInteriorFaceSet(
> ```

nit missing documentation. This function requires the input `boundary_face_set` and `mesh_M` to be compatible to work properly.

Also, why not just make the signature simply `std::set<SortedTriplet<int>> GetInteriorFaceSet(const VolumeMesh<double>& mesh_M)`?



_Code quote:_
```cpp
std::set<SortedTriplet<int>> GetInteriorFaceSet(
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699)* status: :shipit: complete! all discussions resolved, LGTM from assignees joemasterjohn,xuchenhan-tri(platform)

___
*[`geometry/proximity/detect_zero_simplex.h` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-NdgZ87P9zow2_1LSY3v:-NdgjF0R1hvOy_P51pYl:bchkkxo) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6121e3bf9525f0eca1a234198cf2881883a6b01/geometry/proximity/detect_zero_simplex.h#L5)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is having zero pressure the only type of problem we care about for a hydro tet? What about a tet with its vertices on the same equi-pressure surface that consequently has constant pressure in the tet. Are we worried about those too?
</blockquote></details>

Thank you.  I added a description below that we are not detecting other problems yet.
___
*[`geometry/proximity/detect_zero_simplex.cc` line 41 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-NdgaOad8SpMrjDCG5j_:-NdgmnHD99KRjHFfqnGw:bxxelu4) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6121e3bf9525f0eca1a234198cf2881883a6b01/geometry/proximity/detect_zero_simplex.cc#L41)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit missing documentation. This function requires the input `boundary_face_set` and `mesh_M` to be compatible to work properly.

Also, why not just make the signature simply `std::set<SortedTriplet<int>> GetInteriorFaceSet(const VolumeMesh<double>& mesh_M)`?
</blockquote></details>

Done. I also did it for GetInteriorEdgeSet().
___
*[`geometry/proximity/detect_zero_simplex.cc` line 100 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19699#-NdgPgoq9SiPYGT5gASj:-NdgpVfi8rmQuCHe2arl:b-yvqcly) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6121e3bf9525f0eca1a234198cf2881883a6b01/geometry/proximity/detect_zero_simplex.cc#L100)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Totally optional, but could write a small lambda to improve readability:
```
auto is_boundary_tet = [&boundary_vertex_set](const VolumeElement& tet) {
  for (int i = 0; i < 4; ++i) {
    if (boundary_vertex_set.count(tet.vertex(i)) < 1) return false;
  }
  return true;
}
```
then below
```
if (is_boundary_tet(tetrahedron)) {
  null_tetrahedra.push_back(tetrahedron_index);
}
```
</blockquote></details>

Done. I used slightly different names.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19699)* status: :shipit: complete! all discussions resolved, LGTM from assignees joemasterjohn,xuchenhan-tri(platform)

**Pull request merged**
