### PR TITLE
[workspace] Upgrade gz_math_internal to latest release gz-math7_7.2.0

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #19715

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19776)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
See https://github.com/gazebosim/gz-math/pull/521.  The fix might be as simple as removing `COPYING` from our `package.BUILD.bazel`.

**Comment by jwnimmer-tri** [comment]
:lgtm: co-author / co-feature.  +@EricCousineau-TRI for platform review per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19776)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19776#-:-N_GQ6SO51arHHGzMMTH:bcpz082)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri (to appease reviewable completion condition)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19776#-:-N_GQEBRDmMJZGah2GkS:bcbhyn9)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by EricCousineau-TRI — COMMENTED** [review]
Er, completion condition still not accepting. Odd.
Trying one more time on my user name: +@EricCousineau-TRI 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19776#-:-N_GQuDZ5FWUcOdFKLYY:b7deshf)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
