### PR TITLE
[trajectories] Add StackedTrajectory

### LINKED ISSUE #17990: Trajectory stacking
Given more than one [`Trajectory`](https://drake.mit.edu/doxygen_cxx/classdrake_1_1trajectories_1_1_trajectory.html) objects, it would be convenient to allow for stacking them.

For vstack semantics, imagine one trajectory for a left arm and one trajectory for a right arm, and we want to stack them into a single trajectory with twice the number of dofs.  Both would require the same num_cols in their output, and would stack the rows.

For hstack semantics, imagine running two trajectories back-to-back.  In this case, the output must have the same rows and cols for both.  Probably there needs to be an affordance for remapping the times to sequence correctly.

For specific kinds of trajectory subclasses, there are work-arounds for now but for stacking heterogenous types, I think the only solution is to implement a `Trajectory` subclass on your own.  We should just provide one.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #17990.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18192)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for feature review.

> Reviewed 2 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18192#-:-NGYHiOP3CuRDj0reVml:b95uado)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18192)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18192#-:-NGYPhwI7YusLzk8XSoR:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18192)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

___
*[`common/trajectories/test/stacked_trajectory_test.cc` line 124 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18192#-NGbCU_c2QsAH8h3l0wL:-NGbCU_c2QsAH8h3l0wM:b-jmepyd) ([raw file](https://github.com/robotlocomotion/drake/blob/57dd0ed549a6ce3f4c8905d2015935dfd11dfbb2/common/trajectories/test/stacked_trajectory_test.cc#L124)):*
> ```cpp
>   const double t0 = 0.2;
>   const double tf = 0.8;
>   const Vector2d value_start_top(1, 2);
> ```

unused
___
*[`common/trajectories/test/stacked_trajectory_test.cc` line 145 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18192#-NGbCfW79rjg7fFy0g9M:-NGbCfW79rjg7fFy0g9N:b-jmepyd) ([raw file](https://github.com/robotlocomotion/drake/blob/57dd0ed549a6ce3f4c8905d2015935dfd11dfbb2/common/trajectories/test/stacked_trajectory_test.cc#L145)):*
> ```cpp
>   const double t0 = 0.2;
>   const double tf = 0.8;
>   const RowVector2d value_start_top(1, 2);
> ```

unused

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18192)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

___
*[`common/trajectories/test/stacked_trajectory_test.cc` line 124 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18192#-NGbCU_c2QsAH8h3l0wL:-NGbFEEL6yU768VOmmvx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57dd0ed549a6ce3f4c8905d2015935dfd11dfbb2/common/trajectories/test/stacked_trajectory_test.cc#L124)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.
___
*[`common/trajectories/test/stacked_trajectory_test.cc` line 145 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18192#-NGbCfW79rjg7fFy0g9M:-NGbFEWC9QN-ckk5hzSn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57dd0ed549a6ce3f4c8905d2015935dfd11dfbb2/common/trajectories/test/stacked_trajectory_test.cc#L145)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18192#-:-NGbINwx64HKfrSKgnN2:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
