### PR TITLE
Upgrade to Bazel 0.12.0 on Ubuntu

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8641)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@SeanCurtis-TRI for feature and platform review, please.

I have tested CLion at these versions locally, including Ctrl-B to jump around symbols, and also running a unit googletest under the debugger with breakpoints and variable inspection.

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[CMakeLists.txt, line 20 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8641#-LAUVzMl7rPl-VUIo0J-:-LAUVzMl7rPl-VUIo0J0:b-b6w3p1) ([raw file](https://github.com/robotlocomotion/drake/blob/54dab1b38ada36637e5ed8b5afee4441588c8137/CMakeLists.txt#L20)):*
> ```CMake
>   set(MINIMUM_BAZEL_VERSION 0.12.0)
> else()
>   set(MINIMUM_BAZEL_VERSION 0.12.0)
> ```

@jamiesnape Hmm, should I do this change in a separate PR, for better CI transition ergonomics?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8641)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 20 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8641#-LAUVzMl7rPl-VUIo0J-:-LAUaq9r3SVd8SxDUoI-:b-ozsr5l) ([raw file](https://github.com/robotlocomotion/drake/blob/54dab1b38ada36637e5ed8b5afee4441588c8137/CMakeLists.txt#L20)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We can work it either way. The new image is ready so we just need to click a button in Jenkins.
</blockquote></details>

OK Then I guess once we have LGTMs and expected Jenkins builds are passing, we can click Jenkins button and then I'll merge this PR sometime after that (probably forcing a rebuild of Required builds first to make sure it's kosher).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8641)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: 

I ended up (lazily) testing it against 2017.3.3 and plugin 2018.03.12.0.6. But it all looked good there as well. So, it won't punish people who don't immediately upgrade.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8641#-:-LAV2eimA0VvbgqFXD8i:b-z66zfw)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
