### PR TITLE
allegro_hand: Add README for joint_control sub-package

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Follow-up to #14204, motivated by Drake Developers discussion

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Video w/ full repro steps:
https://user-images.githubusercontent.com/26719449/105071388-83346800-5a52-11eb-8e46-6b2e591d8030.mp4

**Review by EricCousineau-TRI — COMMENTED** [review]
+@amcastro-tri for review, please!

\cc @joemasterjohn @sherm1 @seancurtis-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542#-:-MRQhPdT1VI94CABEft9:blqmunu)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14542#-MRSJP4410qpNmzvZtHP:-MRSJP4410qpNmzvZtHQ:b7yojjx) (no related file):*
@amcastro-tri or @joemasterjohn: I saw the word "stable" fly around a bit in some docs.

Can I ask what the intent of "stable" means in this context?
The video (please see link above) shows a few finger gaits manipulating the mug, but eventually it "slips" (or bumps?) out and flies off.

Is that expected? Or is there tuning necessary for y'all's definition of stable?

---

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14542#-MRSJP4410qpNmzvZtHP:-MRWDZ-v2OyIJYghfMPX:b-nfnfsz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@amcastro-tri or @joemasterjohn: I saw the word "stable" fly around a bit in some docs.

Can I ask what the intent of "stable" means in this context?
The video (please see link above) shows a few finger gaits manipulating the mug, but eventually it "slips" (or bumps?) out and flies off.

Is that expected? Or is there tuning necessary for y'all's definition of stable?
</blockquote></details>

I don't see "stable" anywhere in the docs for the allegro hand example. But I can probably safely say that what you read was referring to the numerical stability of the integration relative to the discrete timestep. Before reflected inertia was added to this example, 1e-2 was too large of a timestep for the system and made it unstable either by the joint velocities exploding from integration error or by the discrete solver failing to converge (which would throw an exception I believe). 

The joint control in here is a pretty simple position control based on some heuristic. I don't think it intends the mug to remain "stable" in the hand for more than a few seconds. BUT it doesn't fly off to infinity.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14542#-MRSJP4410qpNmzvZtHP:-MRWJ5c75SMEkAojhSO8:b-gkm7kq) (no related file):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I don't see "stable" anywhere in the docs for the allegro hand example. But I can probably safely say that what you read was referring to the numerical stability of the integration relative to the discrete timestep. Before reflected inertia was added to this example, 1e-2 was too large of a timestep for the system and made it unstable either by the joint velocities exploding from integration error or by the discrete solver failing to converge (which would throw an exception I believe). 

The joint control in here is a pretty simple position control based on some heuristic. I don't think it intends the mug to remain "stable" in the hand for more than a few seconds. BUT it doesn't fly off to infinity.
</blockquote></details>

Is the instability of the grasp an artifact of the time step? Or, if you shrink the time step, does it likewise lose hold of the cup?  Certainly, if the behavior of the simulation changes significantly with a change in step size, then it's hard to argue that the simulation is stable in any sense. It *might* just be that the joints don't blow up *as fast*.  What's the largest time step we can use such that we get the same qualitative behavior as when we use a reference time step?

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14542#-MRSJP4410qpNmzvZtHP:-MRWrXfk6g7Qi_UspDz2:bimgj5n) (no related file):*
> Is the instability of the grasp an artifact of the time step? Or, if you shrink the time step, does it likewise lose hold of the cup?

I checked in 6d56ea0bf7, and yeah, it looks it does about the same thing (note that sim time is about ~180s, similar to video):
image

> I don't see "stable" anywhere in the docs for the allegro hand example.

I was moreso speaking to recent presentations ;) But yes, knowing that "stable" in this sense means just stability of the joint controllers w.r.t. time step seems A-OK.

And the fact that there is no intent of keeping the mug in the same place means there's no regression, so I'm A-OK on that too. I want to make sure we clarify that, because I myself had no clear expectation on what to see in this simulation.

> It might just be that the joints don't blow up as fast. What's the largest time step we can use such that we get the same qualitative behavior as when we use a reference time step?

The joints themselves seem stable w.r.t. time (at the time steps pre- and post-Ale's PR).
I'm also not too curious about the exact time step that yields stability, I just wanted to know what "stable" meant, and if Ale's PR made a regression (which is not the case).

> BUT it doesn't fly off to infinity.

Er... it does? The mug at least.

---

Will update the README to reflect the expectations of stability.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14542#-MRSJP4410qpNmzvZtHP:-MRWtqNy7xkXP9cXTyeX:bu052e) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> Is the instability of the grasp an artifact of the time step? Or, if you shrink the time step, does it likewise lose hold of the cup?

I checked in 6d56ea0bf7, and yeah, it looks it does about the same thing (note that sim time is about ~180s, similar to video):
image

> I don't see "stable" anywhere in the docs for the allegro hand example.

I was moreso speaking to recent presentations ;) But yes, knowing that "stable" in this sense means just stability of the joint controllers w.r.t. time step seems A-OK.

And the fact that there is no intent of keeping the mug in the same place means there's no regression, so I'm A-OK on that too. I want to make sure we clarify that, because I myself had no clear expectation on what to see in this simulation.

> It might just be that the joints don't blow up as fast. What's the largest time step we can use such that we get the same qualitative behavior as when we use a reference time step?

The joints themselves seem stable w.r.t. time (at the time steps pre- and post-Ale's PR).
I'm also not too curious about the exact time step that yields stability, I just wanted to know what "stable" meant, and if Ale's PR made a regression (which is not the case).

> BUT it doesn't fly off to infinity.

Er... it does? The mug at least.

---

Will update the README to reflect the expectations of stability.
</blockquote></details>

OK Sprayed some text at the README about what to expect for the simulation.

---

**Comment by jwnimmer-tri** [comment]
@amcastro-tri please have a look at this PR, we're waiting on you.  (Or if you don't have time, you can withdraw from review and ask for someone else to take over.)

**Review by amcastro-tri — COMMENTED** [review]
no idea why this one fell down the cracks. This looks like a good improvement, :lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542#-:-Me67O0L0_giGSFgST2y:bunbpwn)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by amcastro-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542#-:-Me67nAz8WIYuITBLkca:b-trzqz1)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14542#-:-Me69l-4EbaP3o2F0-TS:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @EricCousineau-TRI)

**Pull request merged**
