### PR TITLE
WIP: Use AVX instructions in Obb::HasOverlap() to compose rigid transforms.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
First step of the umbrella PR #14623, which is a superset of this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14626)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
The focus of this PR is `geometry/proximity/obb.cc`.  All the other files (geometry/benchmarking/... and tools/performance/...) are result of rebasing on other branches (for #14621, #14624).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14626#-:-MSoLvNQCTxgOlc9chJQ:ba5chrx)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
@sherm1 @rpoyner-tri .  Please see `obb.cc` below.  Please ignore all the other files since they were dragged from other PRs.

I think we have a good start.  Using AVXs to compose rigid transforms, we improve (with `broadwell`) about 10% from:
```
$ tail -n12 ~/project/ObbBench/2021-02-05_1400_broadwell/summary.txt 
-------------------------------------------------------------------------------------
Benchmark                                           Time             CPU   Iterations
-------------------------------------------------------------------------------------
BM_ObbHasOverlap_31_Cases_mean                   3498 ns         3498 ns            9
BM_ObbHasOverlap_31_Cases_median                 3490 ns         3490 ns            9
BM_ObbHasOverlap_31_Cases_stddev                 12.7 ns         12.7 ns            9
BM_ObbHasOverlap_16_OverlapCases_mean            1874 ns         1874 ns            9
BM_ObbHasOverlap_16_OverlapCases_median          1875 ns         1875 ns            9
BM_ObbHasOverlap_16_OverlapCases_stddev          9.21 ns         9.20 ns            9
BM_ObbHasOverlap_15_NonOverlapCases_mean         1512 ns         1512 ns            9
BM_ObbHasOverlap_15_NonOverlapCases_median       1504 ns         1504 ns            9
BM_ObbHasOverlap_15_NonOverlapCases_stddev       9.11 ns         9.11 ns            9
```
to
```
tail -n12 ~/project/ObbBench/2021-02-05_1435_AVXTransformOnly/summary.txt 
-------------------------------------------------------------------------------------
Benchmark                                           Time             CPU   Iterations
-------------------------------------------------------------------------------------
BM_ObbHasOverlap_31_Cases_mean                   3120 ns         3120 ns            9
BM_ObbHasOverlap_31_Cases_median                 3116 ns         3116 ns            9
BM_ObbHasOverlap_31_Cases_stddev                 9.11 ns         9.12 ns            9
BM_ObbHasOverlap_16_OverlapCases_mean            1686 ns         1686 ns            9
BM_ObbHasOverlap_16_OverlapCases_median          1689 ns         1689 ns            9
BM_ObbHasOverlap_16_OverlapCases_stddev          11.6 ns         11.6 ns            9
BM_ObbHasOverlap_15_NonOverlapCases_mean         1337 ns         1337 ns            9
BM_ObbHasOverlap_15_NonOverlapCases_median       1330 ns         1330 ns            9
BM_ObbHasOverlap_15_NonOverlapCases_stddev       8.70 ns         8.70 ns            9
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14626#-:-MSoN66bDysXSnvKDMgL:blzbakc)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by mitiguy** [comment]
Added a comment to related document: https://docs.google.com/document/d/1e8wGEkvTg3Lqke91P0UNFZzF7IRnlgtqKrquwYhfLaM/edit?pli=1#

GTEST_TEST(RigidTransform, TestMemoryLayoutOfRigidTransformDouble) {
  // If it helps optimization to leverage a continuous memory layout of
  // RigidTransform<double> as 12 sequential doubles starting with a 3x3
  // RotationMatrix<double> immediately followed by a 3x1 position vector,
  // Sean/Paul recommend addinging a test (such as the following) where
  // optimization is needed (not necessarily in rigid_transform_test).
  // The test below currently passes on Sean Curtis's computer.
  // So, we may already have the memory layout we need for optimization.
  // Perhaps, all that is needed is a reinterpret_cast where necessary.
  RigidTransform<double> X;
  const double* X_address = reinterpret_cast<const double*>(&X);
  const double* R_address = reinterpret_cast<const double*>(&X.rotation());
  const double* p_address = reinterpret_cast<const double*>(&X.translation());
  EXPECT_EQ(X_address, R_address);
  EXPECT_EQ(X_address + 9, p_address);
}

**Comment by sherm1** [comment]
Per f2f: apparently all we really need is a static_assert that (if T==double) sizeof(RigidTransform)==12 and sizeof(RotationMatrix)==9, ideally placed in the relevant header files. Then we can have our low-level simd methods depend on that packed layout.

**Comment by DamrongGuoy** [comment]
The experiment has concluded. Sherm already had #15119 merged into master.

Close now.

**Pull request closed without merging**
