### PR TITLE
Python bindings for Monte Carlo analysis

### PR DESCRIPTION
**Pull request by gizatt**
Not quite ready for full review yet, but it's definitely build server time. Never tried the magic WrapCallbacks thing before!

@RussTedrake (or anyone else) -- any preference if that Pendulum test should maybe live as an example instead? It's maybe a little involved (and long-ish running) for a unit test...

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11256)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Not sure why the experimental tests failed, guessing it may have been due to some maintenance.

**Comment by gizatt** [comment]
Yeah, looks like maintenance. I think I'm ready for you to take a look -- I'm pretty sure I'm missing at least one ownership switch somewhere and would totally appreciate another set of eyes...

**Comment by gizatt** [comment]
OK maybe I'm not missing a keepalive... I thought Simulator took ownership of the system being simulated, but it doesn't, so I'm back down to 0 unexplained errors using this code :)

**Comment by EricCousineau-TRI** [comment]
Ah, nutz... Filed #13816 because I think I forgot to ask for tests in the `set_random*` methods. Oops!

**Pull request merged**
