### PR TITLE
gitattributes: Treat svg files as binaries

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #14657

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14666)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@soonho-tri for both reviews, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14666#-:-MTlcBItCoY2pmlG_MAm:bfw3koa)* status: LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @soonho-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14666#-:-MTlcEmiEYn1s4RfdZ0C:b3dcro0)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14666#-:-MTldCnB5rtduBAvtOIg:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform)

**Comment by EricCousineau-TRI** [comment]
A few CI builds passed; this is a simple Git flag. Merging.

**Pull request merged**
