### PR TITLE
Fixes the revert in 3636

### PR DESCRIPTION
**Pull request by amcastro-tri**
cc'ing  @betsymcphail, @mwoehlke-kitware, @jwnimmer-tri.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3639)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Confirm that the revert actually fixes it:
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by amcastro-tri** [comment]
I am using `EXPECT_NEAR` to compare two floating point numbers that come from solving a polynomial equation of second order which requires some square roots. Originally I performed the comparison to machine (`epsilon`) which in linux works. However as you can see [here](https://drake-cdash.csail.mit.edu/testDetails.php?test=3175927&build=131970) in OS X the result from these square roots differ from more than machine precision (about 3.5^-15).
I just solved the problem by using a bigger tolerance for the comparison.

**Comment by liangfok** [comment]
:lgtm: Just one BTW consideration.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/test/simulator_test.cc, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-KSvZv_C_mLHeFJA8pEV:-KSvZv_C_mLHeFJA8pEW:bcmwjk8) ([raw file](https://github.com/robotlocomotion/drake/blob/10c1df2815ffb056dee7a38bbdafdf732e29dd60/drake/systems/analysis/test/simulator_test.cc#L224)):*
> ```cpp
>   // Roots should be the complex conjugate of each other.
>   // The factor of 20 is needed for OS X builds where the comparison needs a
>   // looser tolerance.
> ```

BTW: Consider citing #3636 in this comment. so readers will have more context information.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-:-KSv_6-Vw7WGARBwlXK4:bb70sek)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/analysis/test/simulator_test.cc, line 225 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-KSv_ApiHiNUzH4o3a-C:-KSv_ApiHiNUzH4o3a-D:bx6bhjv) ([raw file](https://github.com/robotlocomotion/drake/blob/10c1df2815ffb056dee7a38bbdafdf732e29dd60/drake/systems/analysis/test/simulator_test.cc#L225)):*
> ```cpp
>   // The factor of 20 is needed for OS X builds where the comparison needs a
>   // looser tolerance.
>   EXPECT_NEAR(lambda1.real(),  lambda2.real(), 20*NumTraits<double>::epsilon());
> ```

BTW: nit: missing spaces before and after "*". (Same comment below.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3639)*

**Comment by mwoehlke-kitware** [comment]
Can you please provide a better description in both the PR and commit than "fixes the revert"? Grammatically, that doesn't even make sense; you are not fixing "the revert", you are fixing the problem that the revert would "avoid".

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/test/simulator_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-KSvZasSfS6rU5IRtwwk:-KSvZasVlPV9t19Vl5EW:b-qmgciw) ([raw file](https://github.com/robotlocomotion/drake/blob/10c1df2815ffb056dee7a38bbdafdf732e29dd60/drake/systems/analysis/test/simulator_test.cc#L223)):*
> ```cpp
> 
>   // Roots should be the complex conjugate of each other.
>   // The factor of 20 is needed for OS X builds where the comparison needs a
> ```

This immediately makes me think the code should be more like:

```c++
#ifdef __APPLE__
auto tol = 20.0 * NumTraits<double>::epsilon();
#else
auto tol = NumTraits<double>::epsilon();
#endif
EXPECT_NEAR(lambda1.real(),  lambda2.real(), tol);
EXPECT_NEAR(lambda1.imag(), -lambda2.imag(), tol);
```

Perhaps better, do we not have something like qFuzzyCompare (i.e. accept two values as "equal" if there differences is small compared to their magnitude, rather than comparing vs. an unscaled epsilon)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-:-KSva01FuK1zCV-3JMBE:b-hefpn0)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/test/simulator_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-KSvZasSfS6rU5IRtwwk:-KSvaZRd-qbXbvZCPlgo:b1thizt) ([raw file](https://github.com/robotlocomotion/drake/blob/10c1df2815ffb056dee7a38bbdafdf732e29dd60/drake/systems/analysis/test/simulator_test.cc#L223)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> This immediately makes me think the code should be more like:
> 
> ```c++
> #ifdef __APPLE__
> auto tol = 20.0 * NumTraits<double>::epsilon();
> #else
> auto tol = NumTraits<double>::epsilon();
> #endif
> EXPECT_NEAR(lambda1.real(),  lambda2.real(), tol);
> EXPECT_NEAR(lambda1.imag(), -lambda2.imag(), tol);
> ```
> 
> Perhaps better, do we not have something like qFuzzyCompare (i.e. accept two values as "equal" if there differences is small compared to their magnitude, rather than comparing vs. an unscaled epsilon)?
</details>
@sherm1, do you have any experience with this? I wonder if you've done something like this in the past.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3639)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/test/simulator_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-KSvZasSfS6rU5IRtwwk:-KSvasRYvm9kK371u-uc:b4q6oze) ([raw file](https://github.com/robotlocomotion/drake/blob/10c1df2815ffb056dee7a38bbdafdf732e29dd60/drake/systems/analysis/test/simulator_test.cc#L223)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> @sherm1, do you have any experience with this? I wonder if you've done something like this in the past.
</details>
The closest things to a fuzzy compare that I'm aware of is `CompareMatrices()` in `drake-distro/drake/common/eigen_matrix_compare.h`.

:+1: for adding a fuzzy compare for `doubles`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3639)*

**Comment by jwnimmer-tri** [comment]
Can we please fix master before we gold-plate it?  Yes, this PR is deeply unsatisfying.  But we either need to merge this (and promise to do better in a follow-up PR), or else merge #3636 and resubmit the earlier PR with the tolerance fix.

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/test/simulator_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-KSvZasSfS6rU5IRtwwk:-KSvbgBZx8gBL52ZBZNM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/10c1df2815ffb056dee7a38bbdafdf732e29dd60/drake/systems/analysis/test/simulator_test.cc#L223)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> The closest things to a fuzzy compare that I'm aware of is `CompareMatrices()` in `drake-distro/drake/common/eigen_matrix_compare.h`.
> 
> :+1: for adding a fuzzy compare for `doubles`.
</details>
Done.

---

*[drake/systems/analysis/test/simulator_test.cc, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-KSvZv_C_mLHeFJA8pEV:-KSvbgdxWsBMnSVdXZA8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/10c1df2815ffb056dee7a38bbdafdf732e29dd60/drake/systems/analysis/test/simulator_test.cc#L224)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: Consider citing #3636 in this comment. so readers will have more context information.
</details>
Done.

---

*[drake/systems/analysis/test/simulator_test.cc, line 225 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-KSv_ApiHiNUzH4o3a-C:-KSvbgzXavKPHsOx_S5v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/10c1df2815ffb056dee7a38bbdafdf732e29dd60/drake/systems/analysis/test/simulator_test.cc#L225)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: missing spaces before and after "*". (Same comment below.)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3639)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3639)*

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by mwoehlke-kitware** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3639)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
:lgtm:.  Sometimes platforms are just like that.

Note that Eigen simply resuses the numeric_limits epsilon of the representation type, which is just the difference between 1.0 and the next representable number.  There is no reason to expect that this is similar to the numeric error of any nontrivial computation.  We should not be surprised that complex sqrt exceeds the NumTraits epsilon, as it is a chain of computations and may not be at the 0 radix anyway.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3639#-:-KSwAQlORccDzgQYSLwG:b1bvv9n)*

**Comment by jwnimmer-tri** [comment]
Using override-merge because reasons.

**Pull request merged**
