### PR TITLE
Added isinf() and isnan() overloads to AutoDiffScalar 

### PR DESCRIPTION
**Pull request by edrumwri**
Addresses issue #4005

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4008)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@david-german-tri for feature reviewer, +@jwnimmer-tri for platform review (treating 8pm EDT as Thursday!) please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-:-KVbY0W_215i_HMVf1zs:btatw93)*

**Comment by jwnimmer-tri** [comment]
:lgtm: pending open discussions.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/math/autodiff_overloads.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc5ixq53l5gTbYWTDZ:-KVc5ixq53l5gTbYWTD_:b-1jtp98) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/autodiff_overloads.h#L26)):*
> ```objc
> /// Overloads isinf to mimic std::isinf from <cmath>.
> template <typename DerType>
> double isinf(const Eigen::AutoDiffScalar<DerType>& x) {
> ```

The `std::` flavor of this returns `bool`; shouldn't this overload also do that?

---

*[drake/math/autodiff_overloads.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc5mq0Nnxi_2hn34wx:-KVc5mq0Nnxi_2hn34wy:b-1jtp98) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/autodiff_overloads.h#L33)):*
> ```objc
> /// Overloads isnan to mimic std::isnan from <cmath>.
> template <typename DerType>
> double isnan(const Eigen::AutoDiffScalar<DerType>& x) {
> ```

The `std::` flavor of this returns `bool`; shouldn't this overload also do that?

---

*[drake/math/test/autodiff_overloads_test.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc6SS_PVNqHFRGeGJB:-KVc6SS_PVNqHFRGeGJC:b18tx98) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/test/autodiff_overloads_test.cc#L19)):*
> ```cpp
> // Tests correctness of isinf
> GTEST_TEST(AutodiffOverloadsTest, IsInf) {
>   Eigen::AutoDiffScalar<Eigen::Vector2d> x;
> ```

BTW This leaves the derivatives uninitialized (at least, I think that's how Eigen usually works?).  Consider if we should set them to non-garbage values here and (in the NaN test below).

---

*[drake/math/test/autodiff_overloads_test.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc68EunhdnMNA3EzHt:-KVc68EunhdnMNA3EzHu:b-zetohg) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/test/autodiff_overloads_test.cc#L22)):*
> ```cpp
>   x.value() = 1.0 / 0.0;
>   EXPECT_EQ(isinf(x), true);
> }
> ```

Please also test a `false` example.

---

*[drake/math/test/autodiff_overloads_test.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc6AbVCK9ZlYNC-sTB:-KVc6AbVCK9ZlYNC-sTC:b-zetohg) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/test/autodiff_overloads_test.cc#L29)):*
> ```cpp
>   x.value() = 0.0 / 0.0;
>   EXPECT_EQ(isnan(x), true);
> }
> ```

Please also test a `false` example.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-:-KVc6mi8dSCHb28T9TpQ:buvdl6p)*

**Comment by edrumwri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/math/autodiff_overloads.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc5ixq53l5gTbYWTDZ:-KVeN6l5xmzULk0Y-5FE:b-k01xzj) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/autodiff_overloads.h#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The `std::` flavor of this returns `bool`; shouldn't this overload also do that?
</details>
Good catch (copy and paste error).

---

*[drake/math/autodiff_overloads.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc5mq0Nnxi_2hn34wx:-KVeN9DFXURD5IxvJrcE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/autodiff_overloads.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The `std::` flavor of this returns `bool`; shouldn't this overload also do that?
</details>
Done.

---

*[drake/math/test/autodiff_overloads_test.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc68EunhdnMNA3EzHt:-KVeNBXqwEfHZHYSBZKh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/test/autodiff_overloads_test.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Please also test a `false` example.
</details>
Done.

---

*[drake/math/test/autodiff_overloads_test.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc6AbVCK9ZlYNC-sTB:-KVeNC2xLaIZXSLXepb8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/test/autodiff_overloads_test.cc#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Please also test a `false` example.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4008)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/math/test/autodiff_overloads_test.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc6SS_PVNqHFRGeGJB:-KVeVkDMkDBCjooAMqmZ:b-5ym9ru) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/test/autodiff_overloads_test.cc#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW This leaves the derivatives uninitialized (at least, I think that's how Eigen usually works?).  Consider if we should set them to non-garbage values here and (in the NaN test below).
</details>
FYI I don't really think this matters for the purposes of the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-:-KVeVnFG-UScYPivpiDp:bnfp4nl)*

**Comment by edrumwri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/math/test/autodiff_overloads_test.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4008#-KVc6SS_PVNqHFRGeGJB:-KVeW1EOvhXMMxY-kqgi:b23twj8) ([raw file](https://github.com/robotlocomotion/drake/blob/18e89be9d3dcd789ee27ecf44c5f256b8c31576f/drake/math/test/autodiff_overloads_test.cc#L19)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> FYI I don't really think this matters for the purposes of the test.
</details>
I didn't really like keeping those unitialized, but couldn't readily find documentation on the derivatives() function or the m_derivatives class variable in AutoDiffScalar. But David's right- it won't affect the outcome of the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4008)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4008)*

**Pull request merged**
