### PR TITLE
[math] Improve printing of symbolic RollPitchYaw and RigidTransform

### LINKED ISSUE #14926: Compile/run-time check of whether type T can resolve itself to a real number (double)
While working on PR #14816 and PR #14910, it would have been helpful to be able to know whether it was possible for a quantity that was templatized on type T to be evaluated to a real number (double).

It seems this would have helped in a variety of ways.  
* Streamline coding.  
* Not have to deal with unused arguments to methods.
* Allow better output from the ostream << operator for symbolic::expressions that can resolve to real numbers (doubles).
* Allow better exception messages for symbolic::expressions that can resolve to real numbers.

Ideally, this would be a no-op (compiler time optimization) for type T of double and AutoDiffXd, whereas it may need to be a runtime cost for type T of symbolic::expression. 

This issue is mentioned in rigid_transform_test.cc, within
GTEST_TEST(RigidTransform, StreamInsertionOperatorForRigidTransform)

I imagine that whether or not a symbolic::expression can be resolved to a real number is an evolving Kaizen target (fine for my purposes).   In a vague way, this relates to ExtractDoubleOrThrow() -- except not wanting to throw.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #14926.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16097)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@mitiguy for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for extra feature review, please.  If Paul doesn't reply by the time you're finished, we'll un-assign him and move straight to platform review.

**Comment by mitiguy** [comment]
@jwnimmer-tri  @rpoyner-tri @sherm1   -- I am reviewing this now.

**Comment by jwnimmer-tri** [comment]
In that case @rpoyner-tri can be platform reviewer (per on-call schedule anyway).

**Review by mitiguy — COMMENTED** [review]
Suggestions made -- all as FYI.  PTAL.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16097#-:-MoePmoo9HAVq7ATLsCI:b5hqfc3)* status: LGTM missing from assignees rpoyner-tri(platform),mitiguy (waiting on @rpoyner-tri)

___
*[math/roll_pitch_yaw.cc, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-MoeFJ6Z9hA-ROspX3Z0:-MoeFJ6Z9hA-ROspX3Z1:b-rzvaqa) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/roll_pitch_yaw.cc#L144)):*
> ```cpp
>   T q3 = zA + zB;  // Third angle in rotation sequence.
> 
>   // If necessary, modify angles q1 and/or q3 to be between -pi and pi.
> ```

FYI  I am less familiar with cond() than if().  Because you made the change, I assume that  cond() has a benefit here (perhaps with symbolic expressions).  I read documentation in cond.h and saw:

For example, @c symbolic::Expression can be used as a @p
  ScalarType because it provides <tt>symbolic::Formula
  operator<(symbolic::Expression, symbolic::Expression)</tt>.

If the spirit moves you to inform my ignorance: In Drake/C++, is cond() superior to if/else?   I read online LISP discussion of cond()  vs. if() in LISP -- but it was not immediately obvious why I care as I am not a LISP programmer (and this is C++ code).
___
*[math/roll_pitch_yaw.cc, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-Moe9_iB4wRqNueGCIQ2:-Moe9_iB4wRqNueGCIQ3:b-hac3vp) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/roll_pitch_yaw.cc#L177)):*
> ```cpp
>   SetOrThrowIfNotValidInDebugBuild(rpy);
> 
> #ifdef DRAKE_ASSERT_IS_ARMED
> ```

FYI Consider creating an outer "if" statement.

if (scalar_predicate<T>::is_bool) {
  ...
}

The 3 lines of code that currently precedes 

  if (scalar_predicate<T>::is_bool &&
      !R_quaternion.IsNearlyEqualTo(R, tolerance)) 

seems relevant only when scalar_predicate<T>::is_bool == true.
___
*[math/roll_pitch_yaw.cc, line 241 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-MoeBiyp8HMp34C-aH7U:-MoeBiyp8HMp34C-aH7V:byuw6hq) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/roll_pitch_yaw.cc#L241)):*
> ```cpp
> 
> template <typename T>
> std::ostream& operator<<(std::ostream& out, const RollPitchYaw<T>& rpy) {
> ```

FYI Consider changing this comment to something more explicit, like:
// Helper function to represent an angle as a string, or if the 
// underlying type is a symbolic expression that would create a
// long string, a short standard placeholder string is used instead.
___
*[math/roll_pitch_yaw.cc, line 244 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-MoeBLVK0hYg3N2ElePc:-MoeBLVK0hYg3N2ElePd:b-swts8f) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/roll_pitch_yaw.cc#L244)):*
> ```cpp
>   // Helper to represent an angle as a terse string.
>   auto repr = [](const T& angle) {
>     std::string result = fmt::format("{}", angle);
> ```

FYI For clarity, consider adding (and then using). 
const int max_length = 30;
___
*[math/test/rigid_transform_test.cc, line 803 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-MoeOPY694gznrzhW4rT:-MoeOPY694gznrzhW4rU:b2m4vq4) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/test/rigid_transform_test.cc#L803)):*
> ```cpp
>   const char* cstring = stream_string.c_str() + 6;  // Start of double value.
>   double roll, pitch, yaw;
>   int match_count = sscanf(cstring, "%lf %lf %lf ", &roll, &pitch, &yaw);
> ```

FYI.  I understand the ASSERT_EQ(match_count, 3).
I am unsure as to why this is tied to stream_string (which is used below with xyz_expected_string). 
I'll defer this to Rico in Platform review or feel free to dismiss the comment.
___
*[math/test/roll_pitch_yaw_test.cc, line 489 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-Modzw4H4LskZBmvri4o:-Modzw4H4LskZBmvri4p:boztg5w) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/test/roll_pitch_yaw_test.cc#L489)):*
> ```cpp
> 
>   // Test stream insertion for RollPitchYaw<symbolic::Expression>.
>   const symbolic::Variable r("r"), p("p"), y("y");
> ```

FYI  It is unclear to me why variable names "r", "p", 'y" is an improvement.  In the original code, the longer names "roll", "pitch", "yaw" were chosen to differentiate the start of the string "rpy = " from its variable names.  If "roll", "pitch", "yaw" are not great, perhaps let's use   "theta0", "theta1", "theta2"  or  "fred", "sue", "joe".

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16097)* status: LGTM missing from assignees rpoyner-tri(platform),mitiguy (waiting on @mitiguy and @rpoyner-tri)

___
*[math/roll_pitch_yaw.cc, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-MoeFJ6Z9hA-ROspX3Z0:-MoeUGmK7V4_f8zq5Zdr:b-n6qaux) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/roll_pitch_yaw.cc#L144)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

FYI  I am less familiar with cond() than if().  Because you made the change, I assume that  cond() has a benefit here (perhaps with symbolic expressions).  I read documentation in cond.h and saw:

For example, @c symbolic::Expression can be used as a @p
  ScalarType because it provides <tt>symbolic::Formula
  operator<(symbolic::Expression, symbolic::Expression)</tt>.

If the spirit moves you to inform my ignorance: In Drake/C++, is cond() superior to if/else?   I read online LISP discussion of cond()  vs. if() in LISP -- but it was not immediately obvious why I care as I am not a LISP programmer (and this is C++ code).
</blockquote></details>

Done.

Some changed here is required, because the test will fail with an exception if we use plain C++ `if`.  We need either `if_then_else` or `cond`.

My original thought had been that `cond` would be clearer that we're doing a case analysis, of which at most one would match (and this does result in slightly smaller expression trees), but upon refection probably `if_then_else` should be okay too, and probably easier to read.
___
*[math/roll_pitch_yaw.cc, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-Moe9_iB4wRqNueGCIQ2:-MoeTHU0-ixWYudS_Tn9:bbuh2qr) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/roll_pitch_yaw.cc#L177)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

FYI Consider creating an outer "if" statement.

if (scalar_predicate<T>::is_bool) {
  ...
}

The 3 lines of code that currently precedes 

  if (scalar_predicate<T>::is_bool &&
      !R_quaternion.IsNearlyEqualTo(R, tolerance)) 

seems relevant only when scalar_predicate<T>::is_bool == true.
</blockquote></details>

OK I'm content to let the compiler optimize that or not.
___
*[math/roll_pitch_yaw.cc, line 241 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-MoeBiyp8HMp34C-aH7U:-MoeTnMQEnRUI6Lfe7Zx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/roll_pitch_yaw.cc#L241)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

FYI Consider changing this comment to something more explicit, like:
// Helper function to represent an angle as a string, or if the 
// underlying type is a symbolic expression that would create a
// long string, a short standard placeholder string is used instead.
</blockquote></details>

Done.
___
*[math/test/rigid_transform_test.cc, line 803 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-MoeOPY694gznrzhW4rT:-MoeSRHxCFZmwoXENg8-:b-7l905v) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/test/rigid_transform_test.cc#L803)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

FYI.  I understand the ASSERT_EQ(match_count, 3).
I am unsure as to why this is tied to stream_string (which is used below with xyz_expected_string). 
I'll defer this to Rico in Platform review or feel free to dismiss the comment.
</blockquote></details>

OK When we left-shift additional text (here, "When scanning [stream_string]") into a googletest EXPECT_FOO or ASSERT_FOO macro, that text is displayed alongside the test failure message in case the comparison failed.  It's a way to provide extra detail.  Here, I found it useful to see the string output produced by the device, while debugging (sscanf is not a particularly helpful parser in terms of error messages).
___
*[math/test/roll_pitch_yaw_test.cc, line 489 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16097#-Modzw4H4LskZBmvri4o:-MoeRvFO9GhlHeRtoK9T:bsdfzc7) ([raw file](https://github.com/robotlocomotion/drake/blob/191b8365127ede376b8302cf7e418aec9846b85b/math/test/roll_pitch_yaw_test.cc#L489)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

FYI  It is unclear to me why variable names "r", "p", 'y" is an improvement.  In the original code, the longer names "roll", "pitch", "yaw" were chosen to differentiate the start of the string "rpy = " from its variable names.  If "roll", "pitch", "yaw" are not great, perhaps let's use   "theta0", "theta1", "theta2"  or  "fred", "sue", "joe".
</blockquote></details>

Done.  A fair point, using nonsense names will be much better.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16097)* status: LGTM missing from assignees rpoyner-tri(platform),mitiguy (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16097#-:-MoedveK27k47_YhcKKx:bnfp4nl)* status: LGTM missing from assignee mitiguy (waiting on @jwnimmer-tri)

**Review by mitiguy — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16097#-:-Moem1ou9Ar3No7RK0SL:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),mitiguy (waiting on @jwnimmer-tri)

**Pull request merged**
