### PR TITLE
Implements SAP constraint to model PD controllers

### PR DESCRIPTION
**Pull request by amcastro-tri**
Towards #19067.

cc'ing @joemasterjohn, since I'll ask you to review the next PR that wires this up in the plant.

cc'ing @JoseBarreiros-TRI, since you need this feature for your project.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review please (Tuesday)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-:-NdWl2MeBSbcDW8I3YWi:b-766dx9)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm: with a few minor comments.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-:-NdbIbre9qsIQm4TqT4d:b-anrp9p)* status: 16 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdaYWuVBc18zPDXd2Mu:-NdaYWuVBc18zPDXd2Mv:bb752ax) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L24)):*
> ```objc
> 
>   /* Constructs data for a SapPdControllerConstraintData.
>     Refer to SapPdControllerConstraintData's documentation for further details.
> ```

Typo



_Suggestion:_
```objc
  /* Constructs data for a SapPdControllerConstraint.
    Refer to SapPdControllerConstraint's documentation for further details.
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdaYaP59DKaeHNHi0Vb:-NdaYaP59DKaeHNHi0Vc:b18y69m) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L28)):*
> ```objc
>     @param Kd Derivative gain.
>     @param time_step Discrete simulation time step. */
>   SapPdControllerConstraintData(T Kp, T Kd, T time_step)
> ```

minor, consider passing by const reference or move the input into the object.
BTW, do we ever have derivatives on the time step?



_Code quote:_
```objc
SapPdControllerConstraintData(T Kp, T Kd, T time_step)
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdaZ2AD6OlodNrqvvnt:-NdaZ2AD6OlodNrqvvnu:b-qgvjo) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L51)):*
> ```objc
>   // Values stored in this struct remain const after construction.
>   struct ConstParameters {
>     T Kp;
> ```

minor, these T typed data need default initialization, here and below.
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-Nda_MYV-6THH2Euxayq:-Nda_MYV-6THH2Euxayr:b-s1n6ni) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L69)):*
> ```objc
>  function such that it models the actuation force u from a PD controller
>  according to:
>    ũ = -Kp⋅(q − qd) - Kd⋅(v − vd) + u_ff
> ```

nit, should define qd, vd, and u_ff.



_Code quote:_
```objc
ũ = -Kp⋅(q − qd) - Kd⋅(v − vd) + u_ff
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 100 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-Ndb5Y8wAuRErwuNyIE2:-Ndb5Y8x1XCivo3oPAoA:b-w5ith1) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L100)):*
> ```objc
>     /* Constructs a valid set of parameters.
>      @param Kp Proportional gain. It must be non-negative.
>      @param Kd Derivative gain. It must be non-negative.
> ```

minor, I was confused for a moment about why there are two different classes that store seemingly similar data. Then I realized `SapPdContrillerConstraint::Parameters` and `SapPdControllerConstraintData` both store kp and kd, but one stores the "desired" stiffness and damping whereas the other stores the "effective" stiffness and damping. I think the distinction is worth mentioning somewhere in the documentation and not left to figure out from the implementation.



_Code quote:_
```objc
     @param Kp Proportional gain. It must be non-negative.
     @param Kd Derivative gain. It must be non-negative.
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbCjQL7HqYDM96R0C9:-NdbCjQL7HqYDM96R0CA:b-eyjrj7) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L123)):*
> ```objc
>     int clique;
>     /* PD controlled dof within the given clique. */
>     int clique_dof;
> ```

BTW, IIUC, `clique_dof` is an index into [0, clique_nv). Probably worth a comment confirming that's the case.
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 173 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdayVNt3QYL3e_qICfQ:-NdayVNt3QYL3e_qICfR:brf8gg5) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L173)):*
> ```objc
>   /* Return x clamped in the interval [-e; e].
>    In other words, Clamp(x, e) = max(min(x, e), -e). */
>   static T Clamp(const T& x, const T& e) {
> ```

nit, documentation missing the precondition `e>=0`
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 184 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-Ndb0cMm8TfBsSRnduKu:-Ndb0cMn4yUwNoyFYPcX:b-iyhf83) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L184)):*
> ```objc
>   }
> 
>   /* Computes the antiderivative of the Clamp() function. */
> ```

nit, the antiderivative isn't unique and it'd be nice to characterize it with more precision



_Suggestion:_
```objc
/* Computes the antiderivative F of the Clamp() function such that F(0) = 0. */
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.cc` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-Ndb7FZZ2EdqNofuzsb-:-Ndb7FZZ2EdqNofuzsb0:bcn0qf2) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.cc#L21)):*
> ```cpp
>       effort_limit_(std::move(effort_limit)) {
>   DRAKE_DEMAND(Kp_ >= 0.0);
>   DRAKE_DEMAND(Kd_ >= 0.0);
> ```

There are a couple of places where you put linear combinations of Kp and Kd in the denominator. So you probably don't want both of them to be zero?



_Code quote:_
```cpp
  DRAKE_DEMAND(Kp_ >= 0.0);
  DRAKE_DEMAND(Kd_ >= 0.0);
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-Ndb43ls1wXLqzoUa-Sf:-Ndb43ls1wXLqzoUa-Sg:b-mjss40) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.cc#L53)):*
> ```cpp
>   // "Near-rigid" regularization, [Castro et al., 2021].
>   const T& w = delassus_estimation[0];
>   const T Rnr = beta_factor * w;
> ```

nit, this is pushing on the GSG for variable name a bit. Consider expanding the acronym "nr"



_Code quote:_
```cpp
Rnr
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.cc` line 96 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-Ndb6l5YApdRGuJX_yNU:-Ndb6l5Z-YPGuMpSWJC8:b-2uwt6f) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.cc#L96)):*
> ```cpp
>   // Update data as a function of v.
>   const T y = -Kp * (q - qd) - Kd * (v - vd) + u0;
>   const T Kd_discrete = dt * Kp + Kd;
> ```

nit, this name confuses me. I read it as the negative derivative of y, but don't understand why it's called "Kd_discrete". Worth a comment in the code.



_Code quote:_
```cpp
 const T Kd_discrete = dt * Kp + Kd
```
___
*[`multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc` line 52 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbDxnR-IGn1HfpzdKm:-NdbDxnR-IGn1HfpzdKn:bqvzs9l) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc#L52)):*
> ```cpp
> /* SapPdControllerConstraint models (without considering effort limits) the
>  actuation u at the next time step as:
>    u = −Kp⋅(q−qd) − Kd⋅v + u₀
> ```

nit missing terms? The Kd vd term is also missing in the expression for v a few lines below.



_Suggestion:_
```cpp
u = −Kp⋅(q−qd) − Kd⋅(v-vd) + u₀
```
___
*[`multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc` line 58 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbDfu_1tYr4nWANriT:-NdbDfu_1tYr4nWANriU:byg2kui) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc#L58)):*
> ```cpp
>  achieve that effort, as:
>    v = (u₀ − u − Kp⋅(q₀-qd)) / (δt⋅Kp + Kd)
>  This value of velocity might exceed effort limits. */
> ```

nit consider rewording



_Suggestion:_
```cpp
The actuation required to achieve this value of velocity might exceed effort limits.
```
___
*[`multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc` line 72 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbEgnm5HF37hLPKr0i:-NdbEgnm5HF37hLPKr0j:b-463wf7) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc#L72)):*
> ```cpp
> }
> 
> bool AreConfigurationsEqual(const Configuration& a, const Configuration& b) {
> ```

BTW, why not use operator ==? Then at the call site you can just use EXPECT_EQ.



_Code quote:_
```cpp
AreConfigurationsEqual
```
___
*[`multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc` line 165 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbH3kI9dkRJDgdXZBr:-NdbH3kI9dkRJDgdXZBs:b-2z2rub) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc#L165)):*
> ```cpp
> // Unit test SapPdControllerConstraint::MakeData() outside the near-rigid
> // regime.
> GTEST_TEST(SapPdControllerConstraint, MakeData_OutsideTheNearRigidRegime) {
> ```

nit, the test name is unconventional



_Suggestion:_
```cpp
MakeDataOutsideTheNearRigidRegime
```
___
*[`multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc` line 171 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbHoDR0fq9WinP7IYm:-NdbHoDR0fq9WinP7IYn:b-fsf9j2) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc#L171)):*
> ```cpp
>   const Configuration k = MakeArbitraryConfiguration();
>   const SapPdControllerConstraint<double> c(k, p);
>   // Zero Delassus, will always lead to be outside the near-rigid regime.
> ```

nit comment out of sync with code.



_Code quote:_
```cpp
// Zero Delassus, will always lead to be outside the near-rigid regime.
```

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdaYaP59DKaeHNHi0Vb:-NdeoSgj3iMIvEdIQd19:b-nqczr4) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L28)):*
> do we ever have derivatives on the time step

We do not, yet. Not sure If it'll ever happen though, that's a good point. However now, at least in SAP code, even the time step is type `T`. 
We might need to revisit that with @joemasterjohn as we works on getting derivatives through SAP. For that project it might even make sense to make SAP work with `double` only.
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 100 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-Ndb5Y8wAuRErwuNyIE2:-Ndet1UP2J7Aw3POjXhp:b-7jag0v) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L100)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, I was confused for a moment about why there are two different classes that store seemingly similar data. Then I realized `SapPdContrillerConstraint::Parameters` and `SapPdControllerConstraintData` both store kp and kd, but one stores the "desired" stiffness and damping whereas the other stores the "effective" stiffness and damping. I think the distinction is worth mentioning somewhere in the documentation and not left to figure out from the implementation.
</blockquote></details>

Good point. I changed the name of these variables in the problem data and documented this observation. PTAL.
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbCjQL7HqYDM96R0C9:-Ndeu7SaBk__YoZm8_rS:b67pd5y) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L123)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, IIUC, `clique_dof` is an index into [0, clique_nv). Probably worth a comment confirming that's the case.
</blockquote></details>

good point. done
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.cc` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-Ndb7FZZ2EdqNofuzsb-:-NdewzGH8MxS-pZDwczz:b-1h2e1m) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.cc#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There are a couple of places where you put linear combinations of Kp and Kd in the denominator. So you probably don't want both of them to be zero?
</blockquote></details>

Good point. I could extend this to support zero gain values, but for now I restricted for strictly positive Kp.
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.cc` line 96 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-Ndb6l5YApdRGuJX_yNU:-NdexfO3B6uYgi-NSfpl:bf50uhk) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.cc#L96)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this name confuses me. I read it as the negative derivative of y, but don't understand why it's called "Kd_discrete". Worth a comment in the code.
</blockquote></details>

just a value that shows several times. I couldn't come up with a good name. See if you like `common_factor` better.
___
*[`multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc` line 52 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbDxnR-IGn1HfpzdKm:-Ndey96b-g6Xfyp6IX-i:btjme7) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc#L52)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit missing terms? The Kd vd term is also missing in the expression for v a few lines below.
</blockquote></details>

nice, thanks
___
*[`multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc` line 72 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbEgnm5HF37hLPKr0i:-Ndf-Y0w1gv3ECDMjEV0:bltpuo6) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc#L72)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, why not use operator ==? Then at the call site you can just use EXPECT_EQ.
</blockquote></details>

I like that. Done.

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for off-cycle platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-:-NdfAU1v8iJi2R5z7_Xr:b-1n4snz)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @amcastro-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typos

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-:-NdfIonoCxYqYDCj5ZKB:b-7vdkkg)* status: 5 unresolved discussions, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 197 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdfCTY29J4k6Qx6XBY8:-NdfCTY29J4k6Qx6XBY9:b7ppw2j) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b53d3be2cf62ef69d29e5634706c3e32288f990/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L197)):*
> ```objc
>    implementation chooses the antiderivative that is zero at x = 0.
>    @pre e ≥ 0. */
>   static T ClampAntiDerivative(const T& x, const T& e) {
> ```

I will claim that "antiderivative" is an English word (though of course very technical), and so only gets one capital letter. Certainly the "Antiderivative" spelling is more popular in contemporary Drake code. The only other CamelCase incidence is in old release notes by me, which I believe was also a typo :facepalm: .



_Suggestion:_
```objc
ClampAntiderivative
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.cc` line 32 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdfBGJo9Y_Zyd2a6cAF:-NdfBGJo9Y_Zyd2a6cAG:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b53d3be2cf62ef69d29e5634706c3e32288f990/multibody/contact_solvers/sap/sap_pd_controller_constraint.cc#L32)):*
> ```cpp
>       parameters_(std::move(parameters)) {}
> 
> /* N.B. This method makes a SapPdControllerConstraintData witt "effective"
> ```

typo



_Suggestion:_
```cpp
with
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.cc` line 37 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdfBYKTBjDHSl7JLjQ7:-NdfBYKTBjDHSl7JLjQ8:b-7ilvfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b53d3be2cf62ef69d29e5634706c3e32288f990/multibody/contact_solvers/sap/sap_pd_controller_constraint.cc#L37)):*
> ```cpp
>  cannot resolve the fast dynamics introduced by the model of the controller.
>  Since in this case the implicit scheme will unavoidably dampen the dynamics,
>  the solver decides clamp stiff values to condition the problem numerics better,
> ```

typo?



_Suggestion:_
```cpp
decides to clamp stiff
```
___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.cc` line 46 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdfBkEn3E3P1Amfcn7r:-NdfBkEo7Qql9aMJ-516:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b53d3be2cf62ef69d29e5634706c3e32288f990/multibody/contact_solvers/sap/sap_pd_controller_constraint.cc#L46)):*
> ```cpp
>     const T& dt,
>     const Eigen::Ref<const VectorX<T>>& delassus_estimation) const {
>   // TODO(amcastrot-tri): consider exposing the near rigid parameter.
> ```

typo



_Suggestion:_
```cpp
amcastro-tri
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110)* status: 4 unresolved discussions, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdaYaP59DKaeHNHi0Vb:-NdfISdq91d7dGQ04g3M:bgzdlde) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L28)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> do we ever have derivatives on the time step

We do not, yet. Not sure If it'll ever happen though, that's a good point. However now, at least in SAP code, even the time step is type `T`. 
We might need to revisit that with @joemasterjohn as we works on getting derivatives through SAP. For that project it might even make sense to make SAP work with `double` only.
</blockquote></details>

Good to know, thanks!
___
*[`multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc` line 171 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbHoDR0fq9WinP7IYm:-NdfJb6y5_EsvvIEiOy5:b7ei8u0) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc#L171)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit comment out of sync with code.
</blockquote></details>

Hmm, I would have thought the right thing to do is to change the code implement the comment, not the other way around. Here we want a zero delassus to ensure things are not near-rigid, right?

**Review by amcastro-tri — COMMENTED** [review]
Thank you for volunteering @rpoyner-tri!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-:-NdfO0wh1t73ZW-1kF7s:b-qq1qat)* status: 1 unresolved discussion, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_pd_controller_constraint.h` line 197 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdfCTY29J4k6Qx6XBY8:-NdfMwjFCiCyRB3j6U7V:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b53d3be2cf62ef69d29e5634706c3e32288f990/multibody/contact_solvers/sap/sap_pd_controller_constraint.h#L197)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I will claim that "antiderivative" is an English word (though of course very technical), and so only gets one capital letter. Certainly the "Antiderivative" spelling is more popular in contemporary Drake code. The only other CamelCase incidence is in old release notes by me, which I believe was also a typo :facepalm: .
</blockquote></details>

Done.
___
*[`multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc` line 171 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20110#-NdbHoDR0fq9WinP7IYm:-NdfNwJw8Hm0EWH_rLfC:b-s5l0sw) ([raw file](https://github.com/RobotLocomotion/drake/blob/de84ecafd3ae5539889c28de30421967d7df2ab1/multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc#L171)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Hmm, I would have thought the right thing to do is to change the code implement the comment, not the other way around. Here we want a zero delassus to ensure things are not near-rigid, right?
</blockquote></details>

that'd do it also. In these tests I wanted non-zero values for `w`. 
I updated the comments.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110)* status: missing label for release notes (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20110)* status: missing label for release notes (waiting on @amcastro-tri)

**Pull request merged**
