### PR TITLE
Add no_dreal configuration to make the dReal solver optional

### LINKED ISSUE #11941: dreal: Make it optional (seal dependencies)
Brief tracking issue for sealing dreal API to make it optional.

Steps:
- [x] #11940 Seal API usage (do not publicly include `dreal/dreal.h`)
- [ ] Add `no_dreal.cc`, perhaps add `WITH_DREAL=0`?

\cc @RussTedrake

### PR DESCRIPTION
**Pull request by jamiesnape**
Per request from @RussTedrake.

EDIT (eric): Resolves #11941 

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11942)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review and +@EricCousineau-TRI for platform review.

Please verify `bazel test --define=NO_DREAL=ON  ...` locally.

**Comment by soonho-tri** [comment]
I also have the following error:

```
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'dreal' which is a dreal_repository (rule definition at /private/var/tmp/_bazel_soonhokong/a4335dbcde3364a0e15ec055b5277118/external/drake/tools/workspace/dreal/repository.bzl:80:20):
 - /Users/soonhokong/work/drake/tools/workspace/default.bzl:126:9
 - /Users/soonhokong/work/drake/WORKSPACE:10:1
ERROR: An error occurred during the fetch of repository 'dreal':
   Unable to complete setup for @dreal repository: error 1 from [/usr/local/bin/pkg-config, "dreal"]:
INFO: Call stack for the definition of repository 'mosek' which is a mosek_repository (rule definition at /private/var/tmp/_bazel_soonhokong/a4335dbcde3364a0e15ec055b5277118/external/drake/tools/workspace/mosek/repository.bzl:180:20):
 - /Users/soonhokong/work/drake/tools/workspace/default.bzl:192:9
 - /Users/soonhokong/work/drake/WORKSPACE:10:1
ERROR: /Users/soonhokong/work/drake/solvers/BUILD.bazel:728:1: no such package '@dreal//': Unable to complete setup for @dreal repository: error 1 from [/usr/local/bin/pkg-config, "dreal"]:  and referenced by '//solvers:dreal_solver'
ERROR: Analysis of target '//solvers:library_lint_missing_deps' failed; build aborted: no such package '@dreal//': Unable to complete setup for @dreal repository: error 1 from [/usr/local/bin/pkg-config, "dreal"]:
```

when I ran the following on a mac:
```
brew rm dreal
bazel clean --expunge
bazel test --define=NO_DREAL=ON //solvers/...
```

**Comment by jamiesnape** [comment]
Ok, that's strange. Worked fine here. I will get back to you both.

**Comment by jamiesnape** [comment]
@soonho-tri Does
```
brew rm ipopt ipopt@3.12
bazel clean --expunge
bazel test --define=NO_IPOPT=ON //solvers/...
```
work for you?

**Comment by jamiesnape** [comment]
@EricCousineau-TRI Try again with the latest version. There was a typo.

**Comment by jamiesnape** [comment]
OK, looks like there is a pre-existing issue with the library lint either on the latest Bazel or on Mac.

**Comment by jamiesnape** [comment]
Also broken:

```
sudo apt remove coinor-libipopt1v5 coinor-libipopt-dev
bazel clean --expunge
bazel test --define=NO_IPOPT=ON ...

INFO: Call stack for the definition of repository 'ipopt' which is a pkg_config_repository (rule definition at /home/user/.cache/bazel/_bazel_user/d5431b62a76e6a0517d3a4b0dac18bf7/external/drake/tools/workspace/pkg_config.bzl:262:25):
 - /home/user/.cache/bazel/_bazel_user/d5431b62a76e6a0517d3a4b0dac18bf7/external/drake/tools/workspace/ipopt/repository.bzl:20:5
 - /home/user/GitHub/RobotLocomotion/drake/tools/workspace/default.bzl:158:9
 - /home/user/GitHub/RobotLocomotion/drake/WORKSPACE:10:1
ERROR: An error occurred during the fetch of repository 'ipopt':
   Unable to complete pkg-config setup for @ipopt repository: error 1 from [/usr/bin/pkg-config, "ipopt"]: 
INFO: Call stack for the definition of repository 'mosek' which is a mosek_repository (rule definition at /home/user/.cache/bazel/_bazel_user/d5431b62a76e6a0517d3a4b0dac18bf7/external/drake/tools/workspace/mosek/repository.bzl:180:20):
 - /home/user/GitHub/RobotLocomotion/drake/tools/workspace/default.bzl:192:9
 - /home/user/GitHub/RobotLocomotion/drake/WORKSPACE:10:1
ERROR: /home/user/GitHub/RobotLocomotion/drake/solvers/BUILD.bazel:869:1: no such package '@ipopt//': Unable to complete pkg-config setup for @ipopt repository: error 1 from [/usr/bin/pkg-config, "ipopt"]:  and referenced by '//solvers:ipopt_solver'
ERROR: Analysis of target '//solvers:py/library_lint' failed; build aborted: no such package '@ipopt//': Unable to complete pkg-config setup for @ipopt repository: error 1 from [/usr/bin/pkg-config, "ipopt"]: 
```

**Comment by jamiesnape** [comment]
I think `install_lint` is probably broken too.

**Comment by jamiesnape** [comment]
@EricCousineau-TRI Having trouble reproducing that one on my Linux box.

**Comment by jamiesnape** [comment]
(kind of see why it could fail, but would have though that would have happened on Mac, not Linux)

**Comment by jamiesnape** [comment]
The `library_lint`/`install_lint` issue is a problem with `pkg_config.bzl`. Since it is pre-existing, if I can punt that to another PR (this afternoon or tomorrow morning), it would be great.

**Comment by jamiesnape** [comment]
(Linux does not use `pkg-config` for dreal, so it does not run into problems with `genquery`)

**Comment by soonho-tri** [comment]
I see.

> OK, looks like there is a pre-existing issue with the library lint either on the latest Bazel or on Mac.

Do we have an issue for this? If not, can you create one?

**Comment by jamiesnape** [comment]
We do not, though the question is whether we care that it works, given the boilerplate comments saying unsupported in `tools/BUILD.bazel`.

**Comment by jamiesnape** [comment]
(We also have unrelated failing tests under `NO_CSDP` and `NO_SCS`, so those configurations really are use at own risk.)

**Pull request merged**
