### PR TITLE
[tutorials] Avoid kPrintToConsole in online notebooks

### LINKED ISSUE #17023: Solver options `kPrintToConsole` does not cause any output to be visible on Deepnote
To reproduce: run the `debug_mathematical_program` notebook on Deepnote (as linked from the Drake page).
Expected result: I expect to see solver output after the second cell of the `Enable solver verbosity` section.  Currently I see nothing.

My understanding, based on student questions, is that this is a problem for other solvers as well.

I expect that using `kPrintToFile` is a reasonable work-around until this issue is fixed.  But I do think our tutorial as written, hosted on Deepnote, is not working as advertised.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Requires:
- [x] #17034

Closes #17023.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17035)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17035#-:-N0bKCUZ-aW-FvmYzn6V:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule (tomorrow), please.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17035#-:-N0griJA7YE0Fl2Kn1HR:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
