### PR TITLE
Add missing resources to wheel

### LINKED ISSUE #16069: pip install: AddModelFromFile fails due to missing `drake/package.xml`
Was trying to write up example (inline def. of SDFormat file, parsing it, etc.), but found the following error (min. repro for Ubuntu 18.04, CPython 3.6.9):

```sh
$ python3 -m venv .
$ source ./bin/activate
$ pip install -U pip wheel
$ pip install drake==0.35.0

$ python3 <<EOF
from pydrake.all import MultibodyPlant, Parser
Parser(MultibodyPlant(0.0)).AddModelFromFile("/this/file/does/not/exist")
EOF

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Could not find Drake resource_path 'drake/package.xml' because Drake CMake install
marker specified a resource root of '{venv}/lib/python3.6/site-packages/pydrake/lib/../share'
but that root did not contain the expected file
'{venv}/lib/python3.6/site-packages/pydrake/lib/../share/drake/package.xml'.

$ find . -name 'package.xml'
./lib/python3.6/site-packages/pydrake/share/drake/manipulation/models/iiwa_description/package.xml
./lib/python3.6/site-packages/pydrake/share/drake/manipulation/models/wsg_50_description/package.xml
./lib/python3.6/site-packages/pydrake/share/drake/manipulation/models/realsense2_description/package.xml
./lib/python3.6/site-packages/pydrake/share/drake/manipulation/models/jaco_description/package.xml
./lib/python3.6/site-packages/pydrake/share/drake/manipulation/models/ycb/package.xml
./lib/python3.6/site-packages/pydrake/share/drake/manipulation/models/allegro_hand_description/package.xml
./lib/python3.6/site-packages/pydrake/share/drake/manipulation/models/franka_description/package.xml
./lib/python3.6/site-packages/pydrake/share/drake/examples/manipulation_station/models/package.xml
```

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Fixes #16069.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16071)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

p.s. I'm not sure how to test this? (Passes `test-wheels.sh`, but otherwise...?)

**Comment by jwnimmer-tri** [comment]
My guess would be that a test-wheel addition that would catch this would be to call the `PackageMap` constructor, so something like `print(pydrake.all.PackageMap())`.

**Comment by mwoehlke-kitware** [comment]
> something like `print(pydrake.all.PackageMap())`

```
<pydrake.multibody.parsing.PackageMap object at 0x7f99997d7b30>
```

So... not crashing, but maybe there's a modification to that that makes it more human-readable?

**Comment by jwnimmer-tri** [comment]
Ah, it doesn't have a good printer yet.  That's sad.  The "not crashing" was the most important part, so we could just skip the `print()` part, but I suppose printing `PackageMap().GetPath("drake")` would be even better.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: on the change.  Probably good to push the test line here as well, but I'm OK to merge even without it yet.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16071#-:-MoAdLVYDOzFTMHj_aFR:b-p3wbg9)* status: missing label for release notes (waiting on @mwoehlke-kitware)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16071)* status: missing label for release notes (waiting on @mwoehlke-kitware)

**Comment by EricCousineau-TRI** [comment]
Just to check, will `drake==0.35.0` remain as-is? (I'd assume so, since 0.36.0 may be coming out soon?)

**Comment by jwnimmer-tri** [comment]
At the moment, that's correct --  I don't plan on making an 0.35.1 point release.

**Pull request merged**
