### PR TITLE
Cleanup gradientUtil

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Roughly:
- Move one function into its better home
- Move files from util to math
- Fix filename lint
- Add namespaces
- Finish Bazel rules for drake/math

This is a prereq of getting RBT under Bazel.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4230)

### CODE REVIEW

**Comment by david-german-tri** [comment]
+@david-german-tri 

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4230#-:-KXCxuv1qkfGjfGVjQ9g:bqmdn1l)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4230#-:-KXCyGKMss_Wd0dk3lGu:bsf2vkf)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/matlab/util/drakeMexUtil.h, line 313 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4230#-KXCytzt9fP2gdNHkDNN:-KXCytzuCcI-7mpRqBWV:b4w0kf7) ([raw file](https://github.com/robotlocomotion/drake/blob/84cea3e38ec916ece40cd2515274093747d35531/drake/matlab/util/drakeMexUtil.h#L313)):*
> ```objc
>       matlabToEigenMap<GradientType::type::RowsAtCompileTime,
>                        GradientType::type::ColsAtCompileTime>(mxGetCell(df, 0));
>   math::gradientMatrixToAutoDiff(gradient_matrix, ret);
> ```

CI thinks this should be `drake::math`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4230)*

**Comment by jwnimmer-tri** [comment]
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/util/drakeMexUtil.h, line 313 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4230#-KXCytzt9fP2gdNHkDNN:-KXCztIKEwfsZWf-DrUv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84cea3e38ec916ece40cd2515274093747d35531/drake/matlab/util/drakeMexUtil.h#L313)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> CI thinks this should be `drake::math`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4230)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4230)*

**Pull request merged**
