### PR TITLE
integrators: add python bindings for dense integration

### LINKED ISSUE #13056: pybind: Should fix "RuntimeError: Instance is registered" when handling unique_ptr release workflows
See `pybind11` fork PR:
* https://github.com/RobotLocomotion/pybind11/pull/33

Related places where we got bit in Drake:
* https://github.com/RobotLocomotion/drake/pull/12368
* https://github.com/robotlocomotion/drake/pull/13044#pullrequestreview-391764183 - [commit and line](https://github.com/RobotLocomotion/drake/commit/bf5c7d4e7#diff-9653887cfeeee8b4c97590560ff361aeR44)

---

Basically, I think this happens when you get a non-owning reference to something in C++, but then try to own it afterwards.
e.g.
```cc
class Stuff {
 public:
  T* get_thing();
  unique_ptr<T> release_thing();
};
```

```py
obj = Stuff()
thing = obj.get_thing()
obj.release_thing()
```

### PR DESCRIPTION
**Pull request by RussTedrake**
EDIT(eric): Resolves #13056

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13044)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/test/analysis_test.py, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13044#-M4dIGHT2UNaijKPHojK:-M4p4FYUD9qMA_bpadva:b-uestge) ([raw file](https://github.com/robotlocomotion/drake/blob/bf5c7d4e7e9b158cc35b20d1b4ce9b005b6e50b6/bindings/pydrake/systems/test/analysis_test.py#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Will look into this shortly.
</blockquote></details>

(Will investigate later in the PM)

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/analysis_py.cc, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13044#-M4oRAjT2nPrzW-uIP3u:-M4uAcLdCrW8lY8El8Kw:bum3e29) ([raw file](https://github.com/robotlocomotion/drake/blob/bf5c7d4e7e9b158cc35b20d1b4ce9b005b6e50b6/bindings/pydrake/systems/analysis_py.cc#L67)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Transitive ownership is necessary to decorate when it's an indirect chain of ownership (in the case of `DiagramBuilder.Build()`.
In this case, it's a direct chain of ownership, so I think it's fine to keep it as `py_reference_internal`.
</blockquote></details>

FTR All this being said, these issues can become moot if/when we ever decide to migrate to using `shared_ptr` instead of `unique_ptr` as our primary smart-ptr interface.

I may consider starting an issue, because people complain about the lifetime weirdness of pybind (understandably), but it has a reason.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Ah, oops, should not have used unprovisioned Mac.

@drake-jenkins-bot mac-catalina-clang-bazel-everything-release please

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Pull request merged**
