### PR TITLE
Switch back to VTK 8.0.1

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8325)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI and +@soonho-tri for feature review. FYI @avalenzu and @sammy-tri.

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

Do you happen to have an idea of what was going awry in VTK 8.1?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-:-L7Bq6ek0pXiD8HBOnFj:bp4d5b7)*

**Comment by jamiesnape** [comment]
CI is not happy at all.

**Comment by jamiesnape** [comment]
It appears offscreen rendering with OSMesa was broken in 8.0 and fixed in 8.1. Our previous way of offscreen rendering in 8.0 was not correct and broken for many, though somehow worked on CI.

**Comment by soonho-tri** [comment]
:lgtm:

FTR, related PR: https://github.com/RobotLocomotion/drake/pull/7851

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-:-L7CY8FW6VgT9LsyAb2A:b-4p389t)*

**Comment by EricCousineau-TRI** [comment]
Also relates https://github.com/RobotLocomotion/drake/issues/8322

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
Reviewers, please test the latest binaries. Off-screen rendering of the unit tests may be broken (again), since I rolled back enabling OSMesa, but drake-visualizer should be good for everyone.

**Comment by soonho-tri** [comment]
On mac, I have:
```bash
./bazel-bin/tools/drake_visualizer
dyld: Library not loaded: @rpath/libddApp.dylib
  Referenced from: /Users/soonho.kong/work/drake/bazel-bin/tools/drake_visualizer.runfiles/drake/external/drake_visualizer/bin/drake-visualizer
  Reason: image not found
[1]    93484 abort      ./bazel-bin/tools/drake_visualizer
```

I've done the following to make sure that I have installed the dependencies and build the target:
```bash
./setup/mac/install_prereqs.sh
rm ~/Library/Caches/Homebrew/vtk@8.*
brew reinstall vtk@8.0
bazel build //tools:drake_visualizer -c dbg
```

FYI,
```bash
otool -L /Users/soonho.kong/work/drake/bazel-bin/tools/drake_visualizer.runfiles/drake/external/drake_visualizer/bin/drake-visualizer | grep "libdd"
	@rpath/libddApp.dylib (compatibility version 0.0.0, current version 0.0.0)
```

---

Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-:-L7RlefsuzccnhCTJZPT:b-oex6xy)*

**Comment by EricCousineau-TRI** [comment]
This commands worked for me on Ubuntu:

```
$ git log -n 1 --oneline
4409820 Switch back to VTK 8.0.1
$ bazel run //tools:drake_visualizer
...
$ ./bazel-bin/tools/drake_visualizer
...
```

---

Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-:-L7S0Zmd03gAJMLnEpuB:b-b3j2rz)*

**Comment by jamiesnape** [comment]
@soonho-tri At the moment, I cannot reproduce your error locally.

**Comment by soonho-tri** [comment]
I just tested it on a TRI mac and was able to reproduce it:

```
$ ./bazel-bin/tools/drake_visualizer
dyld: Library not loaded: @rpath/libddApp.dylib
  Referenced from: /Users/soonhok/work/drake/bazel-bin/tools/drake_visualizer.runfiles/drake/external/drake_visualizer/bin/drake-visualizer
  Reason: image not found
[1]    70109 abort      ./bazel-bin/tools/drake_visualizer
```

**Comment by jamiesnape** [comment]
@soonho-tri Can you test this latest binary?

@EricCousineau-TRI The Linux binary is unchanged, but I zapped the `LD_LIBRARY_PATH` in the launcher so can you test again?

**Comment by soonho-tri** [comment]
@jamiesnape , it works now. Thank you.

---

Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-:-L7VjoOn9bKHrYfUxJrp:btehvm2)*

**Comment by EricCousineau-TRI** [comment]
Worked for me! Same steps as above, with the commit change:
```
$ git log -n 1 --oneline                                                                                                                                                    
0222a0d Switch back to VTK 8.0.1 with no OSMesa support
```

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/drake_visualizer/drake_visualizer.py, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-L7VjzqYljwxR4cxaNIi:-L7VjzqYljwxR4cxaNIj:b-icop8s) ([raw file](https://github.com/robotlocomotion/drake/blob/0222a0ddcefe3cb02c162cf2b40c28f1ebe44ff7/tools/workspace/drake_visualizer/drake_visualizer.py#L12)):*
> ```Python
> 
> 
> def set_path(key, relpath):
> ```

BTW, `set_env` is a better name for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/drake_visualizer/drake_visualizer.py, line 51 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-L7Vk765mdK0405T5GR0:-L7Vk765mdK0405T5GR1:b-z0u4zb) ([raw file](https://github.com/robotlocomotion/drake/blob/0222a0ddcefe3cb02c162cf2b40c28f1ebe44ff7/tools/workspace/drake_visualizer/drake_visualizer.py#L51)):*
> ```Python
> if sys.platform.startswith("linux"):
>     # Ensure that we handle LD_LIBRARY_PATH and PYTHONPATH for `@vtk`.
>     set_path("LD_LIBRARY_PATH", "external/vtk/lib")
> ```

Er, sorry, when you mentioned zapping `LD_LIBRARY_PATH`, I thought you had RPATH'd things.

Can you explain why prepending is insufficient in this case?
(this may break other things that want `LD_LIBRARY_PATH`, so I'm a tad concerned)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/drake_visualizer/drake_visualizer.py, line 51 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-L7Vk765mdK0405T5GR0:-L7Vsk-Lh3XKt6BW4EIc:b-m595aw) ([raw file](https://github.com/robotlocomotion/drake/blob/0222a0ddcefe3cb02c162cf2b40c28f1ebe44ff7/tools/workspace/drake_visualizer/drake_visualizer.py#L51)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Nothing should need LD_LIBRARY_PATH. It would be more concerning if it did.
</blockquote></details>

In an ideal world, yes, but for things like ROS, they depend on `LD_LIBRARY_PATH`.
Additionally, the only workaround I can think of for Bazel Python externals is using `LD_LIBRARY_PATH`, which I don't want to let go of.

Is it possible for us to defer this change to a separate issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/drake_visualizer/drake_visualizer.py, line 51 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-L7Vk765mdK0405T5GR0:-L7VtF_TU5bCatnesiA1:budx0mb) ([raw file](https://github.com/robotlocomotion/drake/blob/0222a0ddcefe3cb02c162cf2b40c28f1ebe44ff7/tools/workspace/drake_visualizer/drake_visualizer.py#L51)):*
> In an ideal world, yes, but for things like ROS, they depend on LD_LIBRARY_PATH.
Additionally, the only workaround I can think of for Bazel Python externals is using LD_LIBRARY_PATH, which I don't want to let go of.

But then they would not be using the launcher. ROS is irrelevant in this instance.

> Is it possible for us to defer this change to a separate issue?

Possible, but I do not see why we should.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/drake_visualizer/drake_visualizer.py, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-L7VjzqYljwxR4cxaNIi:-L7VtdB5XAI_rgHKfkKD:b4019v2) ([raw file](https://github.com/robotlocomotion/drake/blob/0222a0ddcefe3cb02c162cf2b40c28f1ebe44ff7/tools/workspace/drake_visualizer/drake_visualizer.py#L12)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `set_env` is a better name for this?
</blockquote></details>

Everything else is `_path` here, so I will continue to match that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/drake_visualizer/drake_visualizer.py, line 51 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8325#-L7Vk765mdK0405T5GR0:-L7VtybUJGvgOoKrZ67L:b-qhh8pn) ([raw file](https://github.com/robotlocomotion/drake/blob/0222a0ddcefe3cb02c162cf2b40c28f1ebe44ff7/tools/workspace/drake_visualizer/drake_visualizer.py#L51)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> In an ideal world, yes, but for things like ROS, they depend on LD_LIBRARY_PATH.
Additionally, the only workaround I can think of for Bazel Python externals is using LD_LIBRARY_PATH, which I don't want to let go of.

But then they would not be using the launcher. ROS is irrelevant in this instance.

> Is it possible for us to defer this change to a separate issue?

Possible, but I do not see why we should.
</blockquote></details>

OK Fine for now, but I'm most likely have to rediscover and undo this when I finish
https://github.com/RobotLocomotion/drake/pull/8240 (unless the upstream Bazel bug gets fixed)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8325)*

**Pull request merged**
