### PR TITLE
Use GRB_LICENSE_FILE and MOSEKLM_LICENSE_FILE explicitly to locate license files

### PR DESCRIPTION
**Pull request by jamiesnape**
Removes the need to add `$HOME` to the environment and improves remote caching between different jobs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8619)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

Worth testing on macOS CI to make sure the license files work out okay there, also?

+@EricCousineau-TRI for platform review per schedule, please.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[doc/bazel.rst, line 184 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOlt6RBI4zd4nd3WoY:-LAOlt6RBI4zd4nd3WoZ:b-yhbyvi) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L184)):*
> ```reStructuredText
> ``export MOSEKLM_LICENSE_FILE=/path/to/mosek.lic``
> 
> To confirm that your setup was successful, run the tests that require MOSEK:
> ```

BTW This . vs : should probably be consistent for the Gurobi and Snopt sections as well?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-:-LAOmyA347tIHqET3CD8:bev78wf)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor BTW.

@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/bazel.rst, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOoS0dCs60ZOiBdwQP:-LAOoS0dCs60ZOiBdwQQ:b-q10b34) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L154)):*
> ```reStructuredText
> 1. Register for an account on https://www.gurobi.com.
> 2. Set up your Gurobi license file in accordance with Gurobi documentation.
> 3. ``export GRB_LICENSE_FILE=/path/to/gurobi.lic``.
> ```

BTW Is there any (easy) way to fail-fast in `bazel test` if these environment variables are not set, such that it can print a link to these updated README instructions?

(I can't think of anything under ~10 lines...)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-:-LAOpBZl-DDgx9SpftO9:bozor2a)*

**Comment by jwnimmer-tri** [comment]
*[doc/bazel.rst, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOoS0dCs60ZOiBdwQP:-LAOpr6v2XvPIkDKtfS1:b-3ymzyj) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L154)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Is there any (easy) way to fail-fast in `bazel test` if these environment variables are not set, such that it can print a link to these updated README instructions?

(I can't think of anything under ~10 lines...)
</blockquote></details>

The place to do that would be `::getenv()` in `solvers/{mosek,gurobi}_solver.cc`.  That _seems_ like a worthwhile addition?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/bazel.rst, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOoS0dCs60ZOiBdwQP:-LAOq7ST5rSbayx3A9Rq:b8gnwj5) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L154)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The place to do that would be `::getenv()` in `solvers/{mosek,gurobi}_solver.cc`.  That _seems_ like a worthwhile addition?
</blockquote></details>

`std::getenv` these days, I think, but I agree that C++ is the place to check.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/bazel.rst, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOoS0dCs60ZOiBdwQP:-LAPQOf3ANNQxJ91mBT0:b-pzi8vf) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L154)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I will follow up with another PR.
</blockquote></details>

If this is worth doing, its worth doing in this PR.  Its purpose would be to help guide users across the transition to the new requirement when they pull the latest master or nightly release.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/bazel.rst, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOoS0dCs60ZOiBdwQP:-LAPQtew5LtCBP-CQEON:bupedy8) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L154)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If this is worth doing, its worth doing in this PR.  Its purpose would be to help guide users across the transition to the new requirement when they pull the latest master or nightly release.
</blockquote></details>

I disagree quite strongly with mixing pure build system changes and code, but I guess I am blocked now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jwnimmer-tri** [comment]
*[doc/bazel.rst, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOoS0dCs60ZOiBdwQP:-LAPS-2yDDddPin4Krrz:b-fgvkpj) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L154)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I disagree quite strongly with mixing pure build system changes and code, but I guess I am blocked now.
</blockquote></details>

It could be a separate commit, or even a separately-reviewed PR that we choose to merge "merge" on concurrently.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jwnimmer-tri** [comment]
*[doc/bazel.rst, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOoS0dCs60ZOiBdwQP:-LAPSVQmAVOgmHoOylXM:b-mf5xj0) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L154)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It could be a separate commit, or even a separately-reviewed PR that we choose to merge "merge" on concurrently.
</blockquote></details>

(The other option would be to decide its not worth doing, unless / until we see user complaints.  It's Eric's defect to decide.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/bazel.rst, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOoS0dCs60ZOiBdwQP:-LAPT42yChFY-IU4crl4:bvcr6c2) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L154)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(The other option would be to decide its not worth doing, unless / until we see user complaints.  It's Eric's defect to decide.)
</blockquote></details>

I will follow up in this PR tonight or tomorrow, I guess.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jamiesnape** [comment]
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/bazel.rst, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LAOoS0dCs60ZOiBdwQP:-LATcdYTCms7WkCWabLS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6ae22f38a8882e47fd3c847888c23516ef9a3d/doc/bazel.rst#L154)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I will follow up in this PR tonight or tomorrow, I guess.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/BUILD.bazel, line 872 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LATeqIu5ZB2ZklZejPw:-LATeqIu5ZB2ZklZejPx:bal53xn) ([raw file](https://github.com/robotlocomotion/drake/blob/d2413d2de4de4d92c831b9eb89a48bced5bd98de/solvers/BUILD.bazel#L872)):*
> ```Python
>     tags = gurobi_test_tags() + [
>         # Modifies global state (environment variable GRB_LICENSE_FILE) so
>         # must not run simultaneously with other tests that use Gurobi.
> ```

The test only changes the value within its own process, I think?  That would not appear to ever interfere with other processes.  (Ditto below.)

---

*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 18 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LATfVoqCSrcLYlSy1oj:-LATfVoqCSrcLYlSy1ok:biocajg) ([raw file](https://github.com/robotlocomotion/drake/blob/d2413d2de4de4d92c831b9eb89a48bced5bd98de/solvers/test/gurobi_solver_grb_license_file_test.cc#L18)):*
> ```cpp
>   const char* grb_license_file = std::getenv("GRB_LICENSE_FILE");
> 
>   if (grb_license_file != nullptr) {
> ```

FYI If this were null, something would be wrong with the test_env, I think?  Perhaps it would be clearer to fail here, instead of allowing the nullptr?

---

*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 26 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LATfAl35kauSl7uLvpR:-LATfAl35kauSl7uLvpS:b-l6jt08) ([raw file](https://github.com/robotlocomotion/drake/blob/d2413d2de4de4d92c831b9eb89a48bced5bd98de/solvers/test/gurobi_solver_grb_license_file_test.cc#L26)):*
> ```cpp
>   GurobiSolver solver;
> 
>   EXPECT_THROW(solver.Solve(program), std::runtime_error);
> ```

Somehow we should prove that this is due to a licensing problem.  For example, by testing no-throw when the environment is unperturbed and/or inspecting the exception text.

Ditto for mosek.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/BUILD.bazel, line 872 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LATeqIu5ZB2ZklZejPw:-LATgMXz9A49djGOB8lj:byf8i7e) ([raw file](https://github.com/robotlocomotion/drake/blob/d2413d2de4de4d92c831b9eb89a48bced5bd98de/solvers/BUILD.bazel#L872)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The test only changes the value within its own process, I think?  That would not appear to ever interfere with other processes.  (Ditto below.)
</blockquote></details>

That is true, not sure what I was thinking  there.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 26 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619#-LATfAl35kauSl7uLvpR:-LATimawEvbHeSo1aTz1:bthg676) ([raw file](https://github.com/robotlocomotion/drake/blob/d2413d2de4de4d92c831b9eb89a48bced5bd98de/solvers/test/gurobi_solver_grb_license_file_test.cc#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Somehow we should prove that this is due to a licensing problem.  For example, by testing no-throw when the environment is unperturbed and/or inspecting the exception text.

Ditto for mosek.
</blockquote></details>

To be clear, by "prove due to a licensing problem" I mean "prove that the new code we added was the thing that threw the exception" (I don't care what `libmosek` does).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8619)*

**Pull request merged**
