### PR TITLE
Teach new_release to use upgrade scripts

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Teach new_release to be able to upgrade things that need an external script to perform the update. Right now this is crate_universe. Add crate_universe to a cohort with clarabel_cpp_internal. Hack metadata.py to supply metadata for a 'fake' crate_universe, since Bazel-side breaks it down into individual crates.

See also #20741.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20855)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20855)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`tools/workspace/clarabel_cpp_internal/repository.bzl` line 8 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20855#-Npa7IVH7ex_cDgPh__b:-Npa7IVH7ex_cDgPh__c:bo6e4nk) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed4ca615cd8b87819a5db99229da4f5ada5b185e/tools/workspace/clarabel_cpp_internal/repository.bzl#L8)):*
> ```Starlark
>     github_archive(
>         name = name,
>         # This dependency is part of a "cohort" defined in
> ```

nit This comment _seems_ to duplicate the `upgrade_advice`.  Is it trying to say something beyond the advice that's already there?

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/clarabel_cpp_internal/repository.bzl` line 8 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20855#-Npa7IVH7ex_cDgPh__b:-NpaMW9z-ROhk1N1z3Hv:b-8b1am6) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed4ca615cd8b87819a5db99229da4f5ada5b185e/tools/workspace/clarabel_cpp_internal/repository.bzl#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This comment _seems_ to duplicate the `upgrade_advice`.  Is it trying to say something beyond the advice that's already there?
</blockquote></details>

Good catch, thanks! The `upgrade_advice` is from when `crate_universe` needed to be updated manually. Now that `new_release` can do it, it also knows that they are cohorts and will automatically keep them together. So the `upgrade_advice` is no longer needed, but I neglected to remove it.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok)

I ran it locally, works fine.

Running it reminded how many awful crate dependencies we've been accumulating (http and curl? really? sigh.), so I'm going to try to separately try to prune some of that away.

> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20855#-:-NpagXjz1bd2gKR1sYMw:b7ciyju)* status: 2 unresolved discussions

___
*[`tools/workspace/new_release.py` line 224 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20855#-Npadzq_6nnNYSVj9DAC:-NpadzqaEE4WMS1fZOO8:b-n2go12) ([raw file](https://github.com/RobotLocomotion/drake/blob/d90d4c13a0365fa291406881aec492aa4741d266/tools/workspace/new_release.py#L224)):*
> ```Python
>             old_commit, new_commit = _handle_github(workspace_name, gh, data)
>         elif rule_type == "crate_universe":
>             # Crates are not updated individually.
> ```

BTW Perhaps a more clear phrasing than "Crates are not updated individually" would be more in the affirmative than the negative. Something like `# Repositories of type crate_universe are individual *output* repositories generated by the master repository rule named create_universe_repositories(); upgrades are grouped under that master rule (via its "scripted" rule type), not performed one by one on the individual outputs."`
___
*[`tools/workspace/new_release.py` line 225 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20855#-Npa_19qB0KOaeXJoYSL:-Npa_19r3aRtkAyZWkNR:bwp7xwo) ([raw file](https://github.com/RobotLocomotion/drake/blob/d90d4c13a0365fa291406881aec492aa4741d266/tools/workspace/new_release.py#L225)):*
> ```Python
>         elif rule_type == "crate_universe":
>             # Crates are not updated individually.
>             print(f"Ignoring {workspace_name} from rules_rust")
> ```

BTW Would you like to remove this `print` now?  Now that we have the automation, we don't need any caution for this.  Or if you plan to demote it to `logging.debug` in a future PR that's fine, too.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20855)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

___
*[`tools/workspace/new_release.py` line 224 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20855#-Npadzq_6nnNYSVj9DAC:-NpamRudExnPvXOR_J33:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d90d4c13a0365fa291406881aec492aa4741d266/tools/workspace/new_release.py#L224)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Perhaps a more clear phrasing than "Crates are not updated individually" would be more in the affirmative than the negative. Something like `# Repositories of type crate_universe are individual *output* repositories generated by the master repository rule named create_universe_repositories(); upgrades are grouped under that master rule (via its "scripted" rule type), not performed one by one on the individual outputs."`
</blockquote></details>

Done.
___
*[`tools/workspace/new_release.py` line 225 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20855#-Npa_19qB0KOaeXJoYSL:-NpalGuC6xvFR-FwSQin:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d90d4c13a0365fa291406881aec492aa4741d266/tools/workspace/new_release.py#L225)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Would you like to remove this `print` now?  Now that we have the automation, we don't need any caution for this.  Or if you plan to demote it to `logging.debug` in a future PR that's fine, too.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20855)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Comment by jwnimmer-tri** [comment]
> Running it reminded how many awful crate dependencies we've been accumulating (http and curl? really? sigh.), so I'm going to try to separately try to prune some of that away.

Ah, my mistake.  All of that clutter appears in the Cargo lockfile, but the list of archives we actually download and depend on is much smaller, and fairly reasonable.

**Pull request merged**
