### PR TITLE
Fix the link in in build-cop docs to indicate Nightly Production.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* ... which is what we actually care about.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3541)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
+@jadecastro for feature review
+@david-german-tri  for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3541#-:-KSCT2qCEWMtp5ziOcde:b-k3ky77)*

**Comment by david-german-tri** [comment]
:lgtm: thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3541#-:-KSCVJteZb2aGQOAsxRx:brfqlux)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3541#-:-KSCWMP0ZJVcKR_C38DK:bnfp4nl)*

**Comment by jadecastro** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3541)*

**Pull request merged**
