### PR TITLE
[doc] Fix a wording defect in parsing doc

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17064)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17064#-:-N0lWZmd8LYss5ccK4du:bbdyukq)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Wow, I''ll need to put on my laywer hat to try to parse this verbiage into logical formulae.  I'll circle back here a bit later.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17064#-:-N0lkuPJ6kNuwKA_FPvU:b-6hrmpp)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Based on f2f with Calder, a real exposition requires examples. My intent in this patch was just fix a lapse in the existing text. I'm fine to come back around to this more fully in later patches connected to the ongoing collision filter work.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17064#-:-N0ppUz74lXl1uQxfJdc:bk2x6nj)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
It wasn't intended to fix a logic error. It was literally a typo, for which the fix is s/with/within/. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17064#-:-N0q5O7906hDKyqNDPv-:b-ogo2rg)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

OK, I read it over enough times that think I can see what it's trying to say now.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17064#-:-N0qffD4BmzA3fYrbR4f:bp3gxpc)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
