### PR TITLE
Use spx to provide drake::optional

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is intended to give us better support across our toolchains for `optional<T>`.  We still need to test in CI and other configs before merging.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6262)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-lsan please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-lsan please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please.
+@soonho-tri for platform review, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending one discussion item.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_optional.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6262#-Km-D1YoVpUStlEm5CHW:-Km-D1YqRDPZucA_Uky1:b6arku5) ([raw file](https://github.com/robotlocomotion/drake/blob/355f44652e90841782b51cda2910eb7195fe5534/drake/common/drake_optional.h#L8)):*
> ```objc
> /// @file
> /// Provides drake::optional as an alias for the appropriate implementation of
> /// std::optional or std::experimental::optional on the given platform.
> ```

nit Would it be possible to update this comment to reflect `stx::`, and mention that this could be changed back to `std::` once we drop GCC 4.8?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6262#-:-Km-DD8aJJzOLrLqgOYZ:b-6dhrit)*

**Comment by jwnimmer-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_optional.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6262#-Km-D1YoVpUStlEm5CHW:-Km-FQ9fEB__ydzEV8O_:bwkzuxm) ([raw file](https://github.com/robotlocomotion/drake/blob/355f44652e90841782b51cda2910eb7195fe5534/drake/common/drake_optional.h#L8)):*
Done.

> Would it be possible to update this comment to reflect `stx::` ...

Good point! I'd fixed this #6260 but lost it in this PR's rewrite.  Fixed.

> ... this could be changed back to std:: once we drop GCC 4.8?

Actually this needs to stay intact until Apple ships a working `std::optional` in its `libc++`, which won't be anytime soon it seems.

But I've clarified the comment -- if you are on a platform with a working optional, Drake will use it, so you'll be able to (for example) assign a `drake::optional` to a `std::optional` in some other modern library without hassle.  That's why tcbrindle's implementation is great -- it aliases the system library iff the system library is correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6262)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_optional.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6262#-Km-D1YoVpUStlEm5CHW:-Km-KHQhaAFgONOig6RP:b-ujm5x1) ([raw file](https://github.com/robotlocomotion/drake/blob/355f44652e90841782b51cda2910eb7195fe5534/drake/common/drake_optional.h#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

> Would it be possible to update this comment to reflect `stx::` ...

Good point! I'd fixed this #6260 but lost it in this PR's rewrite.  Fixed.

> ... this could be changed back to std:: once we drop GCC 4.8?

Actually this needs to stay intact until Apple ships a working `std::optional` in its `libc++`, which won't be anytime soon it seems.

But I've clarified the comment -- if you are on a platform with a working optional, Drake will use it, so you'll be able to (for example) assign a `drake::optional` to a `std::optional` in some other modern library without hassle.  That's why tcbrindle's implementation is great -- it aliases the system library iff the system library is correct.
</blockquote></details>

BTW Sounds good - thanks for the explanation!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6262)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6262#-:-Km1dqp31N3Ln00gG4oy:bnfp4nl)*

**Comment by sherm1** [comment]
Does this mean we can use optional without the value_or(999) hack?

**Comment by jwnimmer-tri** [comment]
Yes, we can now call `optional<T>::value()`.

**Pull request merged**
