### PR TITLE
YAML loading for SimpleRulebook.

### PR DESCRIPTION
**Pull request by maddog-tri**
Also, provide SimpleRulebook with a RemoveAll() method.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8525)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok, as promised, your bonus feature review.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-:-L9MI4-42B0e9NahO2IZ:bmxmufq)*

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/simplerulebook/yaml_io.h, line 5 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9MM97p7i4nfsONqbj_:-L9MM97p7i4nfsONqbja:b-ofltsy) ([raw file](https://github.com/robotlocomotion/drake/blob/4682fd62d11221d547545d0f421786ae3b7eb7d1/automotive/maliput/simplerulebook/yaml_io.h#L5)):*
> ```objc
> #include <string>
> 
> #include "yaml-cpp/yaml.h"
> ```

`yaml-cpp` is only a private dependency of drake at present so either this header should be excluded from the install or logic needs to be added to the install so that `yaml-cpp` can be used in public headers.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525)*

**Comment by maddog-tri** [comment]
*[automotive/maliput/simplerulebook/yaml_io.h, line 5 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9MM97p7i4nfsONqbj_:-L9MevhO1qyta5Z2U-Yb:b-nat4vu) ([raw file](https://github.com/robotlocomotion/drake/blob/4682fd62d11221d547545d0f421786ae3b7eb7d1/automotive/maliput/simplerulebook/yaml_io.h#L5)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`yaml-cpp` is only a private dependency of drake at present so either this header should be excluded from the install or logic needs to be added to the install so that `yaml-cpp` can be used in public headers.
</blockquote></details>

What does "logic needs to be added to the install" entail?  (Is there documentation, or a good example to crib from?)

I think that providing a method that simply takes a YAML::Node -- rather than multiple methods to load from strings, files, etc, that hide the yaml-cpp code -- is the right thing to do, and the other maliput YAML consumers (monolane, multilane) should follow suit.  One reason in particular is to allow collecting multiple types of content (e.g., a multilane road geometry and its associated road-rules) to be loaded from the same document, without having to reparse it for every consumer.  So, might as well do this now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525)*

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/maliput/simplerulebook/yaml_io.h, line 5 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9MM97p7i4nfsONqbj_:-L9Mt9jB723C96grA9nZ:bk1g9y5) ([raw file](https://github.com/robotlocomotion/drake/blob/4682fd62d11221d547545d0f421786ae3b7eb7d1/automotive/maliput/simplerulebook/yaml_io.h#L5)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

What does "logic needs to be added to the install" entail?  (Is there documentation, or a good example to crib from?)

I think that providing a method that simply takes a YAML::Node -- rather than multiple methods to load from strings, files, etc, that hide the yaml-cpp code -- is the right thing to do, and the other maliput YAML consumers (monolane, multilane) should follow suit.  One reason in particular is to allow collecting multiple types of content (e.g., a multilane road geometry and its associated road-rules) to be loaded from the same document, without having to reparse it for every consumer.  So, might as well do this now.
</blockquote></details>

I would agree, but for the fact it brings in a dependency on boost headers for the install on Ubuntu and that we deliberately removed yaml-cpp from public headers. For that reason, I would ask you to reconsider.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525)*

**Comment by jwnimmer-tri** [comment]
*[automotive/maliput/simplerulebook/yaml_io.h, line 5 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9MM97p7i4nfsONqbj_:-L9Q6_fNCCnhNy7eCXa1:b-586nwh) ([raw file](https://github.com/robotlocomotion/drake/blob/4682fd62d11221d547545d0f421786ae3b7eb7d1/automotive/maliput/simplerulebook/yaml_io.h#L5)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I would agree, but for the fact it brings in a dependency on boost headers for the install on Ubuntu and that we deliberately removed yaml-cpp from public headers. For that reason, I would ask you to reconsider.
</blockquote></details>

Indeed.  So the background is:
1. yaml-cpp 0.5.x uses boost (e.g., for shared_ptr).
2. yaml-cpp 0.6.x was refactored to use C++11 instead of boost.
2. Ubuntu Xenial (and Bionic) ships yaml-cpp 0.5.x.
3. As part of better compatibility with the host OS in general, and ROS in particular, we've set up Drake to use the OS version of yaml-cpp.
4. Drake's install avoids dependencies on boost.

While we could revisit those decisions, I agree that in this case there is not enough good reason to change the status quo.

I would suggest in this case that the _installed_ headers should not include yaml, and thus not mention YAML::Node.  The public API should just be file and string.

If there is an internal API header that offers a Node, so that parsed documents can be (re)used, that would be fine.  Sugar that parses a file once and then calls multiple internal APIs on the Node(s) could work.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525)*

**Comment by maddog-tri** [comment]
*[automotive/maliput/simplerulebook/yaml_io.h, line 5 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9MM97p7i4nfsONqbj_:-L9QU7n83nf2sYEb7UyZ:b-ohpaep) ([raw file](https://github.com/robotlocomotion/drake/blob/4682fd62d11221d547545d0f421786ae3b7eb7d1/automotive/maliput/simplerulebook/yaml_io.h#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Indeed.  So the background is:
1. yaml-cpp 0.5.x uses boost (e.g., for shared_ptr).
2. yaml-cpp 0.6.x was refactored to use C++11 instead of boost.
2. Ubuntu Xenial (and Bionic) ships yaml-cpp 0.5.x.
3. As part of better compatibility with the host OS in general, and ROS in particular, we've set up Drake to use the OS version of yaml-cpp.
4. Drake's install avoids dependencies on boost.

While we could revisit those decisions, I agree that in this case there is not enough good reason to change the status quo.

I would suggest in this case that the _installed_ headers should not include yaml, and thus not mention YAML::Node.  The public API should just be file and string.

If there is an internal API header that offers a Node, so that parsed documents can be (re)used, that would be fine.  Sugar that parses a file once and then calls multiple internal APIs on the Node(s) could work.
</blockquote></details>

Well, I didn't realize there was so much drama surrounding yaml-cpp.  I'll change it to a file/string API, and anyone who wants to load multiple types of things from the same document can just parse it multiple times, until the yaml-cpp/ubuntu/drake/boost situation evolves favorably.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525)*

**Comment by maddog-tri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/maliput/simplerulebook/yaml_io.h, line 5 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9MM97p7i4nfsONqbj_:-L9QnNJ9353QPApgxHns:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4682fd62d11221d547545d0f421786ae3b7eb7d1/automotive/maliput/simplerulebook/yaml_io.h#L5)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Well, I didn't realize there was so much drama surrounding yaml-cpp.  I'll change it to a file/string API, and anyone who wants to load multiple types of things from the same document can just parse it multiple times, until the yaml-cpp/ubuntu/drake/boost situation evolves favorably.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 3 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RQ-Ou20KbrkoDZEqH:-L9RQ-Ou20KbrkoDZEqI:b-ciom1o) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L3)):*
> ```cpp
> #include "drake/automotive/maliput/simplerulebook/yaml_io.h"
> 
> #include <cmath>
> ```

Unused?

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 6 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RPCCHCCnRLySeFzLB:-L9RPCCI-DBFDBKPkJtb:b-zcofhc) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L6)):*
> ```cpp
> #include <map>
> #include <memory>
> #include <string>
> ```

Don't need this since it's in the .h file.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 65 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RPJMg73aqxNUQJ7La:-L9RPJMg73aqxNUQJ7Lb:bqzprvw) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L65)):*
> ```cpp
>   const auto it = map.find(s);
>   if (it == map.end()) {
>     throw std::runtime_error(
> ```

Should include `<stdexcept>`.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 132 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RPnCO6X6AZyLVBEfI:-L9RPnCO6X6AZyLVBEfJ:bxzl17n) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L132)):*
> ```cpp
> 
> 
> void LoadYaml(std::istream* istream, SimpleRulebook* rulebook) {
> ```

BTW, for `std::istream`, you might need to `#include <istream>` since the header only includes `<iosfwd>`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525)*

**Comment by maddog-tri** [comment]
Comments addressed, PTAL.

---

Review status: 4 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 3 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RQ-Ou20KbrkoDZEqH:-L9RpCd8-9PHl5_J6Xwl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Unused?
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 6 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RPCCHCCnRLySeFzLB:-L9RpLab5Tw-QwQcLgn7:bjp9gt8) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L6)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Don't need this since it's in the .h file.
</blockquote></details>

Done (i.e., it should not have been in the .h file!).

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 23 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RCGw3-luDp_kONLk4:-L9RPFR2CK4pt6akgz1p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should include `drake/automotive/maliput/api/rules/regions.h` per style guide.

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 24 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RD30T9ot5oCTP8huf:-L9RPG7T7ZOTDHE44-ov:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L24)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider alpha sorting.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 26 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RD9GHBtKPTGgw1GNN:-L9RPSl5735bJLMSeC4c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should include `drake/automotive/maliput/api/rules/right_of_way_rule.h` per style guide.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 27 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RDGyG6Z7VuPVkZGmk:-L9RPTQ9AU0LDlR87PZz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L27)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should include `drake/automotive/maliput/api/rules/speed_limit_rule.h` per style guide.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 65 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RPJMg73aqxNUQJ7La:-L9RpeB0ExzipI613WWi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L65)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should include `<stdexcept>`.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 66 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RFeOI2nZEkg3vIMqy:-L9Rqz854SfqWlGdwvus:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L66)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this can be simplified:

```c++
throw std::runtime_error("Unknown SpeedLimitRule::Severity: " + s);
```
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 108 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RGTIE-pvHgeUx6WPT:-L9Rr-Lc8lZhzKVRGf8U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/yaml_io.cc#L108)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this can be simplified:

```c++
throw std::runtime_error("Unknown RightOfWayRule::Type: " + s);
```
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/test/yaml_io_test.cc, line 21 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RHgyQA-zmasRwTxhI:-L9RrkuK1Rh_W3qAuY74:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/test/yaml_io_test.cc#L21)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should include `drake/automotive/maliput/api/lane.h`.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/test/yaml_io_test.cc, line 22 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RHUHP3JGUDs2lELrE:-L9RrlmK-fy2J77G5qMZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/test/yaml_io_test.cc#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider alpha sorting.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/test/yaml_io_test.cc, line 26 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9ROKqa1Rt8z21AbuA7:-L9Rrrvg-qARL1jgF9Ug:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/test/yaml_io_test.cc#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/test/yaml_io_test.cc, line 74 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9RNJiO9FrsucNPHly2:-L9RrzhT0_oEkHK2aOjl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5de51244d4afbcf7c235561e32dea739983277c6/automotive/maliput/simplerulebook/test/yaml_io_test.cc#L74)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-:-L9RsNrd12Hbu2pmnKSq:b-idmig1)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-:-L9SAlq62vJZSkq4CRKd:bnfp4nl)*

**Comment by maddog-tri** [comment]
+@sherm1 for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-:-L9SDTBmBDShX88GXJP5:bppyoqq)*

**Comment by sherm1** [comment]
Well done! Platform :lgtm: pending a few BTWs.

---

Reviewed 4 of 7 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/simplerulebook/yaml_io.h, line 12 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9STmYS4q26X76TxFAR:-L9STmYS4q26X76TxFAS:b-5ypctd) ([raw file](https://github.com/robotlocomotion/drake/blob/65fdc1aac651588b50213b7ad1c7f0a7392daeab/automotive/maliput/simplerulebook/yaml_io.h#L12)):*
> ```objc
> 
> /// @file
> /// YAML IO for SimpleRulebook.
> ```

BTW consider adding this YAML description to the LoadYaml() function instead of the `@file` level. Doxygen doesn't make it easy to find file-level comments, and I think splitting up the information in two pieces makes it less likely that someone will find everything they need. You could also include a short `@file` comment that would inform someone who stumbled upon it to go look at LoadYaml().

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 110 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9SWiUl5EVUkYd0BgCV:-L9SWiUl5EVUkYd0BgCW:b-limi67) ([raw file](https://github.com/robotlocomotion/drake/blob/65fdc1aac651588b50213b7ad1c7f0a7392daeab/automotive/maliput/simplerulebook/yaml_io.cc#L110)):*
> ```cpp
>   const auto it = map.find(s);
>   if (it == map.end()) {
>     throw std::runtime_error("Unknown RightOfWayRule::Type: " + s);
> ```

BTW kcov says this line has not been unit tested.

---

*[automotive/maliput/simplerulebook/test/yaml_io_test.cc, line 98 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9SSiFMEqvHlcdbQyg9:-L9SSiFMEqvHlcdbQygA:b9y7i2q) ([raw file](https://github.com/robotlocomotion/drake/blob/65fdc1aac651588b50213b7ad1c7f0a7392daeab/automotive/maliput/simplerulebook/test/yaml_io_test.cc#L98)):*
> ```cpp
> something_after: other-stuff
> )R");
>   EXPECT_THROW(LoadYaml(&yaml, &dut), std::runtime_error);
> ```

BTW please consider using DRAKE_EXPECT_THROWS_MESSAGE throughout to make sure the message that gets thrown is the right one (takes a regular expression so the match doesn't have to be exact). (In common/test_utilities).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-:-L9SY7EY2r8GexOaVpzM:b3kygzf)*

**Comment by maddog-tri** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/maliput/simplerulebook/yaml_io.h, line 12 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9STmYS4q26X76TxFAR:-L9kfXUGBraPtD4tenhG:b-9njhk2) ([raw file](https://github.com/robotlocomotion/drake/blob/65fdc1aac651588b50213b7ad1c7f0a7392daeab/automotive/maliput/simplerulebook/yaml_io.h#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider adding this YAML description to the LoadYaml() function instead of the `@file` level. Doxygen doesn't make it easy to find file-level comments, and I think splitting up the information in two pieces makes it less likely that someone will find everything they need. You could also include a short `@file` comment that would inform someone who stumbled upon it to go look at LoadYaml().
</blockquote></details>

Done.

You make a good point (about difficulty in finding file-level docs), but I want the general syntax docs at the file level, in anticipation of more functions (e.g., yaml-emitting functions). So, instead I placed a reference to the file in the function's docstring, and that seems to do the trick nicely (e.g., doxygen turns it into a convenient hyperlink).

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 110 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9SWiUl5EVUkYd0BgCV:-L9k106q2q86OAiKWr8D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65fdc1aac651588b50213b7ad1c7f0a7392daeab/automotive/maliput/simplerulebook/yaml_io.cc#L110)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW kcov says this line has not been unit tested.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/test/yaml_io_test.cc, line 98 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9SSiFMEqvHlcdbQyg9:-L9k0J_d-imX03Xx_dkj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65fdc1aac651588b50213b7ad1c7f0a7392daeab/automotive/maliput/simplerulebook/test/yaml_io_test.cc#L98)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please consider using DRAKE_EXPECT_THROWS_MESSAGE throughout to make sure the message that gets thrown is the right one (takes a regular expression so the match doesn't have to be exact). (In common/test_utilities).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525)*

**Comment by sherm1** [comment]
Looks great - thanks for the tweaks, @maddog-tri.

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[automotive/maliput/simplerulebook/yaml_io.h, line 12 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-L9STmYS4q26X76TxFAR:-L9krSyWAPqeiuW7pSBR:b4f6d2m) ([raw file](https://github.com/robotlocomotion/drake/blob/65fdc1aac651588b50213b7ad1c7f0a7392daeab/automotive/maliput/simplerulebook/yaml_io.h#L12)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done.

You make a good point (about difficulty in finding file-level docs), but I want the general syntax docs at the file level, in anticipation of more functions (e.g., yaml-emitting functions). So, instead I placed a reference to the file in the function's docstring, and that seems to do the trick nicely (e.g., doxygen turns it into a convenient hyperlink).
</blockquote></details>

Oh, that's a neat idea!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8525#-:-L9krnGfAWHk0DggrUCR:b2hdfz9)*

**Pull request merged**
