### PR TITLE
Use matlab_add_mex from FindMatlab instead of mex.cmake 

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3681)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@linux-gcc-ninja-experimental-matlab

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature review.

**Comment by david-german-tri** [comment]
Reviewed 2 of 125 files at r1.
Review status: 2 of 125 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/mex.cmake, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-KUJjQ68mfGQuEL2T_YI:-KUJjQ68mfGQuEL2T_YJ:b-b1ixqk) ([raw file](https://github.com/robotlocomotion/drake/blob/839393d34fcca6643285ac1f703681ebd3d840c0/cmake/mex.cmake#L4)):*
> ```CMake
> # Add a MATLAB MEX target to the drake project.
> #
> #  matlab_add_mex(<name> [EXECUTABLE | MODULE | SHARED] <src1> [<src2> ...]
> ```

`drake_add_mex`?

---

*[cmake/mex.cmake, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-KUJkDgbOyYp_Vdkq9rR:-KUJkDgbOyYp_Vdkq9rS:b-mxps1) ([raw file](https://github.com/robotlocomotion/drake/blob/6643b636f4375c1c5b9a144527f7d604419e3113/cmake/mex.cmake#L20)):*
> ```CMake
> 
>   set(svalue "")
>   foreach (name ${ARG_NAMES})
> ```

BTW, I'm not sure I fully understand this PR yet, but getting rid of this stuff can't be bad!

---

*[drake/examples/Acrobot/@AcrobotPlantCpp/manipulatorDynamics.cpp, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-KUJlyvcDqSbbfGz4g65:-KUJlyvcDqSbbfGz4g66:b-dkacdt) ([raw file](https://github.com/robotlocomotion/drake/blob/839393d34fcca6643285ac1f703681ebd3d840c0/drake/examples/Acrobot/@AcrobotPlantCpp/manipulatorDynamics.cpp#L71)):*
> ```cpp
> }
> 
> DLL_EXPORT_SYM
> ```

What necessitated these?

---

*[drake/util/CMakeLists.txt, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-KUJk-8_HH8w1WKGqXHV:-KUJk-8_HH8w1WKGqXHW:b-nk2suz) ([raw file](https://github.com/robotlocomotion/drake/blob/839393d34fcca6643285ac1f703681ebd3d840c0/drake/util/CMakeLists.txt#L20)):*
> ```CMake
> endif()
> 
> add_library(drakeUtil OBJECT drakeUtil.cpp)
> ```

Why this change (and the consequent `$<TARGET_OBJECTS` goop)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681)*

**Comment by jamiesnape** [comment]
Review status: 2 of 125 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Acrobot/@AcrobotPlantCpp/manipulatorDynamics.cpp, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-KUJlyvcDqSbbfGz4g65:-KUMqnDBAvXVlPqA3Q3z:b2l7lz0) ([raw file](https://github.com/robotlocomotion/drake/blob/839393d34fcca6643285ac1f703681ebd3d840c0/drake/examples/Acrobot/@AcrobotPlantCpp/manipulatorDynamics.cpp#L71)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> What necessitated these?
</details>
Basically Boost. Symbols are hidden by default, so you need to make the entry point visible. This should have been done before (the mex compiler defines DLL_EXPORT_SYM).

https://github.com/Kitware/CMake/blob/master/Modules/FindMatlab.cmake#L948-L965
https://github.com/Kitware/CMake/blob/master/Modules/FindMatlab.cmake#L938

---

*[drake/util/CMakeLists.txt, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-KUJk-8_HH8w1WKGqXHV:-KUMrR6tGGxUpFSrPP7L:b-84m9xu) ([raw file](https://github.com/robotlocomotion/drake/blob/839393d34fcca6643285ac1f703681ebd3d840c0/drake/util/CMakeLists.txt#L20)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why this change (and the consequent `$<TARGET_OBJECTS` goop)?
</details>
There was a TODO in the removed comment, but this makes life easier here too. Basically less matlab_add_mex and linker calls to worry about. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681)*

**Comment by jamiesnape** [comment]
Review status: 2 of 125 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/mex.cmake, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-KUJjQ68mfGQuEL2T_YI:-KUMsMwoYliNMcQRZjnI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/839393d34fcca6643285ac1f703681ebd3d840c0/cmake/mex.cmake#L4)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> `drake_add_mex`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681)*

**Comment by david-german-tri** [comment]
Sigh...This is failing the `addpath_drake; checkDependency('lcm');` smoke test locally for me, and as usual I have no idea why.  

```
>> addpath_drake
Adding /Users/davidgerman/3681/drake-distro/drake/../build/install/matlab to the matlab path.
WARNING: Your JVM may crash if you do not set it to prefer IPv4 over IPv6.
This may cause any dependencies that involve the JVM (including LCM) to crash at runtime.
Please see bug report and solution here: https://github.com/RobotLocomotion/drake/issues/558.
(It just involves adding one line to your java.opts file for Matlab.)
Make sure to restart Matlab after editing your java.opts file.
>> checkDependency('lcm');
 Added the lcm jar to your javaclasspath (found via pkg-config)
 
 LCM not found.  LCM support will be disabled.
 To re-enable, add lcm-###.jar to your matlab classpath
 (e.g., by putting javaaddpath('/usr/local/share/java/lcm-0.9.2.jar') into your startup.m .
 
Error using checkDependency (line 440)
Cannot find required dependency: lcm
```

`/Users/davidgerman/3681/drake-distro/drake/../build/install/matlab/../share/java/lcm.jar` is on the `javaclasspath`.  More likely a local problem than a problem with this PR, but I have to prove that before this can merge.  MATLAB...

**Comment by jamiesnape** [comment]
@david-german-tri Which version of MATLAB?

**Comment by david-german-tri** [comment]
R2016a

---

Review status: 1 of 125 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-:-KUNuuZ0UeI0lsrrsWoJ:bxvvggh)*

**Comment by jamiesnape** [comment]
Thought so. There is an easy fix for that problem for R2015b, but IIRC, it does not work for R2016a/b.

**Comment by david-german-tri** [comment]
Oh, this is known?  I swear it worked for me as recently as last week.  Is there already a writeup?

---

Review status: 1 of 125 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-:-KUNvpB2gkpTXG14j-Fe:b-xgtsef)*

**Comment by jamiesnape** [comment]
I think #558 still applies. There is also lcm-proj/lcm#59.

**Comment by jamiesnape** [comment]
Also https://www.mathworks.com/help/matlab/matlab_env/java-opts-file.html, but like most things MATLAB, it does not always work.

**Comment by david-german-tri** [comment]
Er, OK.  I am concerned about the failure to find LCM, not the IPv4 warning.  If you're suggesting that the latter causes the former, I'll start poking at it, but that doesn't make much sense...

---

Review status: 1 of 125 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-:-KUNzOUux_eKvvKO0D5M:bpmyzum)*

**Comment by jamiesnape** [comment]
That is my only guess. Are 10 distinct CI MATLAB builds not sufficient?

**Comment by jamiesnape** [comment]
Resolved merge conflict.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by david-german-tri** [comment]
> Are 10 distinct CI MATLAB builds not sufficient?

Nope, because based on prior breakages, I do not trust Mac+MATLAB CI to be adequately representative of Russ's environment and workflow.  This can't land until it works for me locally.

---

Review status: 1 of 124 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-:-KUO0Aro2ZiuBhdzPAlK:b24lic6)*

**Comment by jamiesnape** [comment]
We need to work on that then, since it is the essence of CI, but that is another issue.

---

Review status: 1 of 124 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-:-KUO2wym353fKEiAMiAx:b-pj9twl)*

**Comment by david-german-tri** [comment]
Maybe.  I haven't made it a priority because I hold out hope that MATLAB will be walking the plank soon.

---

Review status: 1 of 124 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-:-KUO4Yd4feWWhlD7Su7_:byqrn3k)*

**Comment by jamiesnape** [comment]
Me too, though if there is anything obvious we can change, let me know.

---

Review status: 1 of 124 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-:-KUO4y61NU6pNKbWyPHS:b-8bpdp6)*

**Comment by david-german-tri** [comment]
Sigh.  MATLAB wasn't on my path, because of the symlink issue from #3186.  Resolved now, and works just fine.  :lgtm:

---

Review status: 1 of 124 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3681#-:-KUOFFc-9HqHyVofpB0-:b7aexlb)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please

**Comment by jamiesnape** [comment]
I hate to merge such a big commit late in the day, but if anyone is blocked feel free to hit the merge/revert buttons.

**Comment by jwnimmer-tri** [comment]
Yup, I figured overnight we'd keep it quiet, but let's get this in first thing now, so we can triage immediately and keep my other PRs chugging along later today.

**Comment by jamiesnape** [comment]
Cool, thanks.

**Pull request merged**
