### PR TITLE
Add bindings for MultibodyPlant::CalcGeneralizedForce()

### PR DESCRIPTION
**Pull request by RussTedrake**
and a comment to help find it. This came up in
https://stackoverflow.com/questions/77003297/how-to-initialize-a-multibody-force-object-for-calcforceelementscontribution

+@amcastro-tri for feature review, please. (to make sure you agree with the comment I added)
+@jwnimmer-tri for platform/binding review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20102)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.  Ideally, we would have a story for how to phrase API documentation for C++ outputs that become return values in Python, but we don't really have any tooling for that.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20102#-:-Nd8U1Iu-hps3lqoJ9B-:b-hctpgp)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 2545 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20102#-Nd8TyLm52bKt8nLNrOV:-Nd8TyLnCQNzKEkfrH0m:b-4kx7cu) ([raw file](https://github.com/RobotLocomotion/drake/blob/6782777a64de095dc4b7d7dba014a89dbf6959cb/bindings/pydrake/multibody/test/plant_test.py#L2545)):*
> ```Python
>         forces = MultibodyForces(plant=plant)
>         plant.CalcForceElementsContribution(context=context, forces=forces)
>         tau = plant.CalcGeneralizedForces(context=context, forces=forces)
> ```

nit unused



_Suggestion:_
```Python
plant.Calc
```

**Review by amcastro-tri — COMMENTED** [review]
Thanks @RussTedrake! :lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20102#-:-NdAfBNoDe8RmRBaGpHv:b-ftsqty)* status: 1 unresolved discussion

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 2545 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20102#-Nd8TyLm52bKt8nLNrOV:-NdAf67l4vOe5IayMCm-:b-c603li) ([raw file](https://github.com/RobotLocomotion/drake/blob/6782777a64de095dc4b7d7dba014a89dbf6959cb/bindings/pydrake/multibody/test/plant_test.py#L2545)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit unused
</blockquote></details>

maybe at least assert it has the right type and size?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20102)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20102)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 2545 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20102#-Nd8TyLm52bKt8nLNrOV:-NdBFq8dASGLp-Qi63V8:b-tswh5a) ([raw file](https://github.com/RobotLocomotion/drake/blob/6782777a64de095dc4b7d7dba014a89dbf6959cb/bindings/pydrake/multibody/test/plant_test.py#L2545)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

maybe at least assert it has the right type and size?
</blockquote></details>

WDYT @amcastro-tri ?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20102)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 2545 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20102#-Nd8TyLm52bKt8nLNrOV:-NdBi7aV4It2VBHdRbvD:b-ucfknh) ([raw file](https://github.com/RobotLocomotion/drake/blob/6782777a64de095dc4b7d7dba014a89dbf6959cb/bindings/pydrake/multibody/test/plant_test.py#L2545)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

WDYT @amcastro-tri ?
</blockquote></details>

Thanks!

**Pull request merged**
