### PR TITLE
Use dReal-4.18.05.3

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8903)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for platform-review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8903#-:-LDrG6LVAE48MvyrtQgW:b4fwciw)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8903#-LDrGogJDvpUhRm9L3YL:-LDrGogJDvpUhRm9L3YM:by55z4) (no related file):*
Needs `-unprovisioned` CI testing on macOS, since there we use pkg-config to obtain dReal.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8903#-:-LDrGfvyBZxg1EBm0kAO:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8903#-LDrGogJDvpUhRm9L3YL:-LDrHERm4GR4ymcipVPE:b-h6h49h) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs `-unprovisioned` CI testing on macOS, since there we use pkg-config to obtain dReal.
</blockquote></details>

@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8903)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8903#-:-LDrHX2VCjtMKRGIcbSP:bnfp4nl)*

**Comment by soonho-tri** [comment]
All the unprovisioned builds passed:
 - https://drake-jenkins.csail.mit.edu/job/mac-highsierra-unprovisioned-clang-bazel-experimental/54/
 - https://drake-jenkins.csail.mit.edu/job/mac-sierra-unprovisioned-clang-bazel-experimental/78/

**Pull request merged**
