### PR TITLE
Exclude the installation of vtk_util.h

### PR DESCRIPTION
**Pull request by j-rivero**
This PR is motivated by the need of supporting the case of a system providing `VTK6` (Ubuntu Xenial default one) and Drake using the current `VTK8` version. Since both `VTK6` and `VTK8` [don't conflict in the binary symbols present in their public ABIs](https://github.com/sankhesh/MultipleVTKVersions/blob/master/README.md) the risk present would be to mix both libraries in a compilation unit with vtk headers present in the mix. There is no guarantee about which version will be chosen since both libraries have the same names for headers. 

The only header in Drake including vtk headers is `vtk_util.h` and this file is only used in `.cc` files inside Drake. This PR excludes the `vtk_util.h` file from being installed in the system so Drake users are safe about not including any vtk header at all.

I've tested the [build in Jenkins](https://build.osrfoundation.org/view/All/job/drake-ci-pr_any-xenial-amd64/34/consoleFull) and the `vtk_util.h` file seems not to be present anymore (there is a final error when building `drake-shambhala` to test third party software using Drake but I think it is unrelated to this PR).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7258)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot add to whitelist

**Comment by jwnimmer-tri** [comment]
@j-rivero Thanks for your contribution; our apologies for the botspam -- that's a known problem with Drake, filed as issue #3537.  I've added you to the approved PR list with the above message, so it shouldn't happen again.

+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@EricCousineau-tri for platform review per rotation, please.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-KwQBqKYf8Shled24mAc:-KwQBqKZkaQqr_nsqAWO:b4crwgf) (no related file):*
Please take a look at some proposed additions below.  If they seem good to you, then I think they would strengthen this PR's durability to future changes, and you might consider adding them.

(Even better would be a regression test that inspects the installed copy for vtk include defects, but I don't think that need to block this PR.)

```diff
diff --git a/drake/build_components.bzl b/drake/build_components.bzl
index e78afe4..1e67af2 100644
--- a/drake/build_components.bzl
+++ b/drake/build_components.bzl
@@ -311,7 +311,6 @@
     "//drake/systems/sensors:rgbd_camera",
     "//drake/systems/sensors:rotary_encoders",
     "//drake/systems/sensors:sensors",
-    "//drake/systems/sensors:vtk_util",
     "//drake/systems/trajectory_optimization:direct_collocation",
     "//drake/systems/trajectory_optimization:direct_transcription",
     "//drake/systems/trajectory_optimization:multiple_shooting",
diff --git a/drake/systems/sensors/BUILD.bazel b/drake/systems/sensors/BUILD.bazel
index 1a9ab9e..fe48602 100644
--- a/drake/systems/sensors/BUILD.bazel
+++ b/drake/systems/sensors/BUILD.bazel
@@ -166,6 +166,8 @@
     name = "vtk_util",
     srcs = ["vtk_util.cc"],
     hdrs = ["vtk_util.h"],
+    # We must not expose `#include <vtk/...>` in any of our installed headers.
+    visibility = [],
     deps = [
         "//drake/common:essential",
         "@eigen",
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-:-KwQCM8o78kLFTHfLH6Y:b-39l4fc)*

**Comment by j-rivero** [comment]
> Please take a look at some proposed additions below. If they seem good to you, then I think they would strengthen this PR's durability to future changes, and you might consider adding them.

They look good to me, thanks Jeremy.

Just one question about how bazel works: if we add the visibility empty value, I understand that no other component can use `vtk_util` (library and header). While this will prevent of using vtk headers, are we also preventing other components of using the `vtk_util` library and `vtk_util` header? If that is the case, link against `libvtk_util` is perfectly fine from any component and use `vtk_util.h` is ok for .cc files.

> (Even better would be a regression test that inspects the installed copy for vtk include defects, but I don't think that need to block this PR.)

Fully agree. I can add this to my list of tasks.

**Comment by j-rivero** [comment]
> Please take a look at some proposed additions below. If they seem good to you, then I think they would strengthen this PR's durability to future changes, and you might consider adding them.

They look good to me, thanks Jeremy.

Just one question about how bazel works: if we add the visibility empty value, I understand that no other component can use `vtk_util` (library and header). While this will prevent of using vtk headers, are we also preventing other components of using the `vtk_util` library and `vtk_util` header? If that is the case, link against `libvtk_util` is perfectly fine from any component and use `vtk_util.h` is ok for .cc files.

> (Even better would be a regression test that inspects the installed copy for vtk include defects, but I don't think that need to block this PR.)

Fully agree. I can add this to my list of tasks.

**Comment by jwnimmer-tri** [comment]
> Just one question about how bazel works: if we add the visibility empty value, I understand that no other component can use vtk_util (library and header).  While this will prevent of using vtk headers, are we also preventing other components of using the vtk_util library and vtk_util header? If that is the case, link against libvtk_util is perfectly fine from any component and use vtk_util.h is ok for .cc files.

Empty means private visibility, which is to say that only components _within the same package_ can refer to it.  So within the `//drake/systems/sensors` it can be used freely, but elsewhere inside or outside of Drake cannot use it.

In the future, it would be fair to consider allow vtk_util use from other places inside Drake, but this way we'll have to list them out specifically, to make sure we are using them only within `.cc` files.  On the other hand, there would also be a fair argument that vtk_util should stay private, and any general helpers should be extracted into a different place before sharing them publicly -- for example, CreateSquarePlane probably shouldn't be public, but maybe MakeVtkPointerArray could be.

So the intent here isn't to forever forbid using it more widely, but just to put a reminder into the build system to opt-in before doing so.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-:-KwR12JN1HA3vO6hSBsx:bac63w8)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor comment on a potential TODO.

Also, there may be `buildifier` errors on CI.
Can you run `bazel build //tools/lint:buildifier` and `bazel-bin/tools/lint/buildifier`?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/BUILD.bazel, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-Kw_aeUaZVxO3GOPLEFf:-Kw_aeUcQ7wksXgQhicm:bwyx22d) ([raw file](https://github.com/robotlocomotion/drake/blob/6b729aa6ea0f27161a107b351cc1f273286e8a44/drake/BUILD.bazel#L29)):*
> ```
>     hdr_dest = "include/drake",
>     guess_hdrs = "WORKSPACE",
>     guess_hdrs_exclude = [ "systems/sensors/vtk_util.h" ]
> ```

BTW Could a `TODO` be added to figure out how to attach this directly to the corresponding rule / label?
(I am not sure how to add features onto an existing target in Bazel that can be parsed later, but perhaps there is a way at some point?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-:-Kw_aqSvwqDvZDjSgjS0:b442b80)*

**Comment by kunimatsu-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-KwQBqKYf8Shled24mAc:-KwuRwDd7qT0nmQZnUOk:bf6g05o) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please take a look at some proposed additions below.  If they seem good to you, then I think they would strengthen this PR's durability to future changes, and you might consider adding them.

(Even better would be a regression test that inspects the installed copy for vtk include defects, but I don't think that need to block this PR.)

```diff
diff --git a/drake/build_components.bzl b/drake/build_components.bzl
index e78afe4..1e67af2 100644
--- a/drake/build_components.bzl
+++ b/drake/build_components.bzl
@@ -311,7 +311,6 @@
     "//drake/systems/sensors:rgbd_camera",
     "//drake/systems/sensors:rotary_encoders",
     "//drake/systems/sensors:sensors",
-    "//drake/systems/sensors:vtk_util",
     "//drake/systems/trajectory_optimization:direct_collocation",
     "//drake/systems/trajectory_optimization:direct_transcription",
     "//drake/systems/trajectory_optimization:multiple_shooting",
diff --git a/drake/systems/sensors/BUILD.bazel b/drake/systems/sensors/BUILD.bazel
index 1a9ab9e..fe48602 100644
--- a/drake/systems/sensors/BUILD.bazel
+++ b/drake/systems/sensors/BUILD.bazel
@@ -166,6 +166,8 @@
     name = "vtk_util",
     srcs = ["vtk_util.cc"],
     hdrs = ["vtk_util.h"],
+    # We must not expose `#include <vtk/...>` in any of our installed headers.
+    visibility = [],
     deps = [
         "//drake/common:essential",
         "@eigen",
```
</blockquote></details>

I've just noticed this PR now.

Just to give heads up, `drake/systems/sensors/rgbd_renderer.h` also provides VTK headers.

I'll work on moving those VTK headers from `.h` to `.cc` using pimpl pattern since the class API doesn't depend on VTK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7258)*

**Comment by stonier** [comment]
Thanks @kunimatsu-tri

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/libdrake/BUILD.bazel, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-KyS5pnhxqvlwMDqw4M-:-KyS5pniUGkFxyFn2klF:b-nwserp) ([raw file](https://github.com/robotlocomotion/drake/blob/7bb5aeb9d78d8919322c822e4d7904285a3a85ea/tools/install/libdrake/BUILD.bazel#L42)):*
> ```
>     targets = ["libdrake.so"],
>     guess_hdrs = "WORKSPACE",
>     guess_hdrs_exclude = ["drake/systems/sensors/vtk_util.h"],
> ```

It too me forever to figured out where the comment that used to be here on master went.  I'd forgotten that the yaml_cpp PR got reverted.

In any case, I think the comment in the yaml_cpp PR still makes sense to introduce here, as Eric's other discussion alludes to:
```python
# This is private visibility; we don't want to have a vtk dependency
# in our published headers.  TODO(jwnimmer-tri) Update the guess_hdrs
# logic to exclude non-public headers by default.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7258)*

**Comment by jwnimmer-tri** [comment]
:lgtm: again
+(status: curate commits before merging) 
http://drake.mit.edu/reviewable.html#curated-commits

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-:-KySuMH2aABDrGMRWh94:bfzsi4e)*

**Comment by j-rivero** [comment]
@jwnimmer-tri should I proceed with the git squash or do you guys prefer to do it directly from the github interface?

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI please take another look, you have one open discussion.  Eric or I can do the squash via GitHub ourselves once its ready.

**Comment by EricCousineau-TRI** [comment]
Closed out the discussion - thanks for the head s up!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/BUILD.bazel, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-Kw_aeUaZVxO3GOPLEFf:-KyXfSUUopo4WnY21qF_:b-m9cd21) ([raw file](https://github.com/robotlocomotion/drake/blob/6b729aa6ea0f27161a107b351cc1f273286e8a44/drake/BUILD.bazel#L29)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could a `TODO` be added to figure out how to attach this directly to the corresponding rule / label?
(I am not sure how to add features onto an existing target in Bazel that can be parsed later, but perhaps there is a way at some point?)
</blockquote></details>

I believe Jeremy's `TODO` covers this use case (whether it is guessed or tagged does not matter to me at this point), so will mark this discussion as resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7258#-:-KyXgjl5BDVBZ9DFrWFB:b-9lrxet)*

**Pull request merged**
