### PR TITLE
implements fitted value iteration on a barycentric mesh

### PR DESCRIPTION
**Pull request by RussTedrake**
fitted_value_iteration

The plot on the left is the value iteration solution of the cost-to-go for the LQR problem for the double integrator.  The plot on the right is the LQR solution.  The remaining differences are primarily due to the boundary conditions (in the positive and negative orthants) and the increased cost due to the discretized action space.  

The value iteration code uses the full simulation stack, so should be accurate and easily generalizable to more complex systems. 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8036)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@frankpermenter and/or +@hongkai-dai for feature review, please.
/cc @peteflorence @gizatt 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-:-L564jT6dsDhZkZl35b3:bh0etdl)*

**Comment by peteflorence** [comment]
@RussTedrake how are plots generated?  Looks nice

**Comment by RussTedrake** [comment]
@peteflorence -- CallMatlab today. pydrake bindings tomorrow.

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[systems/controllers/dynamic_programming.cc, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L56Mu-VwiK3UNpyuQ7g:-L56Mu-VwiK3UNpyuQ7h:b-p9pmpg) ([raw file](https://github.com/robotlocomotion/drake/blob/e684a6b30e7342e420de1ded4ad3a19dec3d06d2/systems/controllers/dynamic_programming.cc#L50)):*
> ```cpp
>   const int kNumStates = state_mesh.get_num_mesh_points();
>   const int kNumInputs = input_mesh.get_num_mesh_points();
>   const int kNumIndices = state_mesh.get_num_interpolants();
> ```

Rename this to `kNumStateIndices` to avoid confusion with the input mesh?

---

*[systems/controllers/dynamic_programming.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L56NYxwLpvKGWhj7397:-L56NYxwLpvKGWhj7398:btqu9l3) ([raw file](https://github.com/robotlocomotion/drake/blob/e684a6b30e7342e420de1ded4ad3a19dec3d06d2/systems/controllers/dynamic_programming.cc#L52)):*
> ```cpp
>   const int kNumIndices = state_mesh.get_num_interpolants();
> 
>   std::vector<Eigen::MatrixXi> Tind(kNumInputs);
> ```

Document `Tind` and `T`?

---

*[systems/controllers/dynamic_programming.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L56SpdpksGSN01rWO5N:-L56SpdpksGSN01rWO5O:b-a8bdb) ([raw file](https://github.com/robotlocomotion/drake/blob/e684a6b30e7342e420de1ded4ad3a19dec3d06d2/systems/controllers/dynamic_programming.cc#L112)):*
> ```cpp
>       for (int input = 0; input < kNumInputs; input++) {
>         double Jinput = cost[input](state);
>         for (int index = 0; index < kNumIndices; index++) {
> ```

Could you document this update? I think it is
`J(x, u) = g(x, u) + α*J(f(x, u))`
where `α` is the discount factor.
and the summation over `index` is for the interpolation to get `J(f(x, u))`

---

*[systems/controllers/dynamic_programming.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L56IwUNU5A72yO386UT:-L56IwUNU5A72yO386UU:bfsbr0m) ([raw file](https://github.com/robotlocomotion/drake/blob/e684a6b30e7342e420de1ded4ad3a19dec3d06d2/systems/controllers/dynamic_programming.h#L27)):*
> ```objc
> /// Implements Fitted Value Iteration on a (triangulated) Barycentric Mesh, as
> /// described in
> /// http://underactuated.csail.mit.edu/underactuated.html?chapter=dp .
> ```

The notes in the dynamic programming chapter does not include the discount factor yet. Maybe we should write out what is the cost for the dynamic programming in this documentation, with the discount factor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-:-L56TtQT2DFXGHwokwne:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[systems/controllers/dynamic_programming.cc, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L56Mu-VwiK3UNpyuQ7g:-L56UM7cWUm-6pFhzxKR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e684a6b30e7342e420de1ded4ad3a19dec3d06d2/systems/controllers/dynamic_programming.cc#L50)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Rename this to `kNumStateIndices` to avoid confusion with the input mesh?
</blockquote></details>

Done.

---

*[systems/controllers/dynamic_programming.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L56NYxwLpvKGWhj7397:-L56V5uf9CqRehFHijhr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e684a6b30e7342e420de1ded4ad3a19dec3d06d2/systems/controllers/dynamic_programming.cc#L52)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Document `Tind` and `T`?
</blockquote></details>

Done.

---

*[systems/controllers/dynamic_programming.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L56SpdpksGSN01rWO5N:-L56WWjp80GIAJ_s0MJ4:b-7rl0jd) ([raw file](https://github.com/robotlocomotion/drake/blob/e684a6b30e7342e420de1ded4ad3a19dec3d06d2/systems/controllers/dynamic_programming.cc#L112)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you document this update? I think it is
`J(x, u) = g(x, u) + α*J(f(x, u))`
where `α` is the discount factor.
and the summation over `index` is for the interpolation to get `J(f(x, u))`
</blockquote></details>

done.

---

*[systems/controllers/dynamic_programming.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L56IwUNU5A72yO386UT:-L56XIP3q_WTwQwwtPAq:b-v4sesn) ([raw file](https://github.com/robotlocomotion/drake/blob/e684a6b30e7342e420de1ded4ad3a19dec3d06d2/systems/controllers/dynamic_programming.h#L27)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The notes in the dynamic programming chapter does not include the discount factor yet. Maybe we should write out what is the cost for the dynamic programming in this documentation, with the discount factor?
</blockquote></details>

done.  and flushed out the notes a bit more throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 9 files at r1, 1 of 2 files at r2.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review please.

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-:-L56YJ2UxUAMhiCjfPVE:b-qxjhdt)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 6 of 9 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[systems/controllers/dynamic_programming.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59NGeugp_e_eYdX7xY:-L59NGevRGmbrpOhMu7n:bo3lfwj) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.cc#L48)):*
> ```cpp
>   math::BarycentricMesh<double> input_mesh(input_grid);
> 
>   const int kNumStates = state_mesh.get_num_mesh_points();
> ```

_META_ Not allowed to use kFoo unless the value is constant for all time (within a single process).  Since these are user inputs and won't be that, we want `const int num_states` etc.

---

*[systems/controllers/dynamic_programming.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59NWzOzJ54oskUAJe5:-L59NWzOzJ54oskUAJe6:bnjhhp2) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.cc#L61)):*
> ```cpp
> 
>   {  // Build transition matrices.
>     std::cout << "Computing transition and cost matrices";
> ```

BTW Use Drake's logging APIs, or else remove.  Ditto for other couts below.  (The defect is that with cout, the caller can't easily redirect or throttle the output.)

---

*[systems/controllers/dynamic_programming.cc, line 104 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59NmIEDurE32WOF00V:-L59NmIEDurE32WOF00W:bgrzhq2) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.cc#L104)):*
> ```cpp
>   }
> 
>   // Perform value iteration loop
> ```

BTW punc

---

*[systems/controllers/dynamic_programming.h, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59ItqZWwW9XTidDIfE:-L59ItqZWwW9XTidDIfF:b-7a9l24) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.h#L17)):*
> ```objc
> 
> /// Consolidates the many possible options to be passed to the dynamic
> /// programming algorithms.
> ```

I don't see anywhere (either here, or in the FittedValueIteration) that explains the semantics of these three options.  They should be documented, under the "all non-obvious function arguments require documentation" rule.

At least to include:
- discount_factor in (0, 1].

---

*[systems/controllers/dynamic_programming.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59JeECFCRNB3rfwn-h:-L59JeEDoEDsK1Z3unBY:bixddk7) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.h#L39)):*
> ```objc
> /// a Context for that system, which may contain non-default Parameters, etc.
> /// The @p simulator is run for @p timestep seconds from every point on the mesh
> /// in order to approximate the dynamics.. all of the simulation parameters
> ```

BTW Typo `..`?  Seems like `.` or `...` is wanted.

---

*[systems/controllers/dynamic_programming.h, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59MLtILsjGnaxggauw:-L59MLtILsjGnaxggaux:b-l8rqsz) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.h#L48)):*
> ```objc
> /// the cost-to-go function and the resulting policy.
> /// @param input_grid defines the discrete action space used in the value
> /// iteraiton update.
> ```

BTW `iteration` typo.

---

*[systems/controllers/dynamic_programming.h, line 66 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59LtSf2YupCrL25Mvt:-L59LtSf2YupCrL25Mvu:b-g7qde6) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.h#L66)):*
> ```objc
>     const math::BarycentricMesh<double>::MeshGrid& state_grid,
>     const math::BarycentricMesh<double>::MeshGrid& input_grid,
>     const double timestep,
> ```

`const` here (in the _declaration_) not allowed:
http://drake.mit.edu/styleguide/cppguide.html#Use_of_const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-:-L59NpfQxIpq_KaqMQae:by96gdd)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[systems/controllers/test/dynamic_programming_test.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59i40FWlhLakb9QI4g:-L59i40FWlhLakb9QI4h:b-o9x3tr) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/test/dynamic_programming_test.cc#L42)):*
> ```cpp
>   const double timestep = 1.0;
> 
>   auto soln = FittedValueIteration(&simulator, cost_function, state_grid,
> ```

BTW avoid abbreviation (ditto for all uses of soln).
http://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-:-L59jfb8J_2qyUUt-ktI:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[systems/controllers/dynamic_programming.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59NGeugp_e_eYdX7xY:-L5AJNT_fGCoXDwpYd1n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.cc#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_META_ Not allowed to use kFoo unless the value is constant for all time (within a single process).  Since these are user inputs and won't be that, we want `const int num_states` etc.
</blockquote></details>

Done.

---

*[systems/controllers/dynamic_programming.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59NWzOzJ54oskUAJe5:-L5AKgnevjAvVg2xrYS7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.cc#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Use Drake's logging APIs, or else remove.  Ditto for other couts below.  (The defect is that with cout, the caller can't easily redirect or throttle the output.)
</blockquote></details>

Done.

---

*[systems/controllers/dynamic_programming.cc, line 104 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59NmIEDurE32WOF00V:-L5ALGWzf3a5yG1hy4ia:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.cc#L104)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW punc
</blockquote></details>

Done.

---

*[systems/controllers/dynamic_programming.h, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59ItqZWwW9XTidDIfE:-L5AMXxgJ3Mo7oQxQzXH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.h#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't see anywhere (either here, or in the FittedValueIteration) that explains the semantics of these three options.  They should be documented, under the "all non-obvious function arguments require documentation" rule.

At least to include:
- discount_factor in (0, 1].
</blockquote></details>

Done.

---

*[systems/controllers/dynamic_programming.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59JeECFCRNB3rfwn-h:-L5AMbaYsUxVhJ0hktmB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.h#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Typo `..`?  Seems like `.` or `...` is wanted.
</blockquote></details>

Done.

---

*[systems/controllers/dynamic_programming.h, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59MLtILsjGnaxggauw:-L5AMeD5WNhYrOCY-wu2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.h#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `iteration` typo.
</blockquote></details>

Done.

---

*[systems/controllers/dynamic_programming.h, line 66 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59LtSf2YupCrL25Mvt:-L5AMtG96U213SlOai5v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/dynamic_programming.h#L66)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

`const` here (in the _declaration_) not allowed:
http://drake.mit.edu/styleguide/cppguide.html#Use_of_const
</blockquote></details>

Done.

---

*[systems/controllers/test/dynamic_programming_test.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-L59i40FWlhLakb9QI4g:-L5AN6jDw2jalPGQeoZ7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f15952f989b18b7c9e796166274887b74d618c3/systems/controllers/test/dynamic_programming_test.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW avoid abbreviation (ditto for all uses of soln).
http://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036)*

**Comment by frankpermenter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8036#-:-L5AWU765vlzVm0VJvtZ:bnfp4nl)*

**Pull request merged**
