### PR TITLE
Promoted UpdateOutputs and ApplyLimits to protected

### PR DESCRIPTION
**Pull request by nikos-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6266)

### CODE REVIEW

**Comment by liangfok** [comment]
+@liangfok 

@nikos-tri, the above magical incantation needs to be done for this PR to show up in my Reviewable dashboard under the "assigned to me" section. Otherwise, it shows up in a lower priority "involving me" section.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6266#-:-Km4dkqM7Lah350C6GX0:b-v61nak)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6266#-:-Km4eSrtt9isXTGHYm7B:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
-@liangfok for now. Please feel free to tag me again once this PR is ready for another round of review.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6266#-:-KuKdSHw_vu8cX_YM-Di:b-sbdw0m)*

**Comment by jwnimmer-tri** [comment]
@nikos-tri This PR seems to be stale?  Consider closing it until it's going to be worked again.

**Pull request closed without merging**
