### PR TITLE
SDF parsing: Warn about unsupported elements

### LINKED ISSUE #16785: SDFormat parser: warn about unsupported tags
Split from #16229. The SDFormat parser should issue an explicit warning for documented SDFormat tags that it ignores. Best implemented after #16784 is complete.

Victory condition: given a list of SDFormat tags for whatever version we claim to support, demonstrate that the SDFormat parser either implements the tag by constructing relevant plant features, or warns that the tag is being ignored.

### PR DESCRIPTION
**Pull request by sammy-tri**
Also cleans up some models which had been incorporated into drake with
unsupported elements.

Fixes #16785

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101)

### CODE REVIEW

**Review by sammy-tri — COMMENTED** [review]
+@rpoyner-tri for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101#-:-N1EpU2G0eX_JJBI28Bc:b9gl8pu)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
\CC @zachfang FYI

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101)* status: 5 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @sammy-tri)

___
*[`multibody/parsing/detail_sdf_diagnostic.h` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FIXKm7lIzgPKQMinb:-N1FIXKm7lIzgPKQMinc:b-q1rqlt) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.h#L26)):*
> ```objc
>     const std::set<std::string>& supported_elements);
> 
> /// Checks that, for elements where there  is only one supported  value, that
> ```

nit weird double-space occurrences in this line?
___
*[`multibody/parsing/detail_sdf_diagnostic.h` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FOy7tCZ4rHLEElvlH:-N1FOy7tCZ4rHLEElvlI:b4vutgz) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.h#L28)):*
> ```objc
> /// Checks that, for elements where there  is only one supported  value, that
> /// the element matches that value.
> void CheckSupportedElementValue(
> ```

btw all the call sites of this function are wrapped in a somewhat repetitive HasElement() check. Maybe that should get integrated into this function to make the common case more ergonomic?
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FM8l51bx7e9YanW6k:-N1FM8l51bx7e9YanW6l:bg2jpme) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L22)):*
> ```cpp
>     const std::set<std::string>& supported_elements) {
> 
>   sdf::ElementPtr element = root_element->GetFirstElement();
> ```

nit consider `DRAKE_DEMAND(root_element != nullptr);` near here.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FM_Fi7nIVxwiC9d3G:-N1FM_Fi7nIVxwiC9d3H:b14pjz2) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L33)):*
> ```cpp
>       detail.line = element->LineNumber();
>       detail.message =
>           std::string("Unsupported SDF element in ") +
> ```

iirc we are always supposed to say "SDFormat" rather than "SDF". Ditto for message text throughout.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FN91r-Xz0EmZg_PEa:-N1FN91r-Xz0EmZg_PEb:b-k9bu44) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L35)):*
> ```cpp
>           std::string("Unsupported SDF element in ") +
>           root_element->GetName() + std::string(": ") + element_name;
>       // Unsupported elements in the drake namespace are errors.
> ```

nit this distinction should probably be in the header file documentation.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FNSSB-tipLwIMjkIk:-N1FNSSB-tipLwIMjkIl:b-whb4us) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L39)):*
> ```cpp
>         diagnostic.Error(detail);
>       } else {
>         diagnostic.Warning(detail);
> ```

btw food for thought (or perhaps more later PRs or something). The URDF side currently warns about "spec" documented els/attrs that Drake does not support; it currently passes silently over completely random or misspelled data. With this PR, it appears that SDFormat will warn about both spec-but-unsupported and random stuff (excepting drake:) in the same way. I don't have answers, but I do have questions:

* should we care about a distinction between spec-but-unsupported and random data?
* should random data error instead of warning? or maybe just have different warning text?
* should I go back through URDF and implement a pseudo schema like the one presented here, to capture/handle random typo data? I had intended to, but was treating it as lower priority than other work for now.
___
*[`multibody/parsing/detail_sdf_geometry.cc` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FJOrO1Imb1OEADVxJ:-N1FJOrO1Imb1OEADVxK:b43bs3a) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_geometry.cc#L98)):*
> ```cpp
> 
>   const std::set<std::string> supported_geometry_elements{
>     "drake:capsule",
> ```

btw consider alpha-sort on this list and similar ones throughout?
___
*[`multibody/parsing/test/diagnostic_policy_test_base.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FKZ38CYDeZHHswzjg:-N1FKZ391OByc-AfSxyn:be8oymh) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/test/diagnostic_policy_test_base.h#L32)):*
> ```objc
>     diagnostic_policy_.SetActionForWarnings(
>         [this](const DiagnosticDetail& detail) {
>           std::cerr << "a warning " << detail.FormatWarning() << "\n";
> ```

is this debug cruft?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: some assorted grumbling and musing

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101#-:-N1FPc7Z91brxbIf48cR:b2s7cfz)* status: 5 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FNSSB-tipLwIMjkIk:-N1FQHOa256FVuwr8jhp:b1qyhp1) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L39)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

btw food for thought (or perhaps more later PRs or something). The URDF side currently warns about "spec" documented els/attrs that Drake does not support; it currently passes silently over completely random or misspelled data. With this PR, it appears that SDFormat will warn about both spec-but-unsupported and random stuff (excepting drake:) in the same way. I don't have answers, but I do have questions:

* should we care about a distinction between spec-but-unsupported and random data?
* should random data error instead of warning? or maybe just have different warning text?
* should I go back through URDF and implement a pseudo schema like the one presented here, to capture/handle random typo data? I had intended to, but was treating it as lower priority than other work for now.
</blockquote></details>

FYI the linked issue for this PR lays out my thoughts for diagnostic severity classification.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101)* status: 5 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @sammy-tri)

___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FNSSB-tipLwIMjkIk:-N1FRcz29WvirkI5DsZh:bnpwtdd) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI the linked issue for this PR lays out my thoughts for diagnostic severity classification.
</blockquote></details>

Ah, yes. Forgot that sdformat has its schema-like phase.

**Review by sammy-tri — COMMENTED** [review]
+(release notes: yes) +@xuchenhan-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101#-:-N1FhkKd6CrsMA-vJUuK:b-vzofch)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[`multibody/parsing/detail_sdf_diagnostic.h` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FOy7tCZ4rHLEElvlH:-N1FeeV3CZxrl2m9yG6h:b-ym0osx) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.h#L28)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

btw all the call sites of this function are wrapped in a somewhat repetitive HasElement() check. Maybe that should get integrated into this function to make the common case more ergonomic?
</blockquote></details>

Done.  We can worry about the case where we have an element but not it's parent if it ever comes up.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FM8l51bx7e9YanW6k:-N1Ff2XL3gsvDX75is38:bxixmx8) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L22)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit consider `DRAKE_DEMAND(root_element != nullptr);` near here.
</blockquote></details>

I think it's probably appropriate to continue executing in this case.  The `while (element)` check should keep from dereferencing the pointer, and I think it's potentially valid to have an element with no children.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FM_Fi7nIVxwiC9d3G:-N1FfpMg7RoN8CR_Lp61:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L33)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

iirc we are always supposed to say "SDFormat" rather than "SDF". Ditto for message text throughout.
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FN91r-Xz0EmZg_PEa:-N1Fg6fW6A5TzugMHRq2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L35)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit this distinction should probably be in the header file documentation.
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_sdf_geometry.cc` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FJOrO1Imb1OEADVxJ:-N1Fh6Jm52lSJtOXHmVA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_geometry.cc#L98)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

btw consider alpha-sort on this list and similar ones throughout?
</blockquote></details>

Done.
___
*[`multibody/parsing/test/diagnostic_policy_test_base.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FKZ38CYDeZHHswzjg:-N1FhAaK7DC_7CaDncVc:b-x6osxx) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/test/diagnostic_policy_test_base.h#L32)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

is this debug cruft?
</blockquote></details>

Done.  (yes it was)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FM8l51bx7e9YanW6k:-N1Fm-_h3Yv_V_6ezvwE:b-qgh6j8) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L22)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think it's probably appropriate to continue executing in this case.  The `while (element)` check should keep from dereferencing the pointer, and I think it's potentially valid to have an element with no children.
</blockquote></details>

Uhm doesn't the indicated line dereference `root_element` by calling its `GetFirstElement` method? I feel confident that no call site will pass null, but i'd rather have a message than bare SEGV.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1Fn-ulDcmD5dsuJA6j:-N1Fn-ulDcmD5dsuJA6k:b-smeeob) ([raw file](https://github.com/robotlocomotion/drake/blob/d2ce07e753434dc421411445a3a4c247a4df9ea1/multibody/parsing/detail_sdf_diagnostic.cc#L51)):*
> ```cpp
>     const std::string& element_name,
>     const std::string& expected) {
>   if (!root_element->HasElement(element_name)) {
> ```

nit what happens with sdf::ElementPtr if we deref a null-containing one?

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: with a few nits and questions.

> Reviewed 16 of 21 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101#-:-N1FvKZyDVCjIi69Ae_a:bqfmxp7)* status: 4 unresolved discussions (waiting on @rpoyner-tri, @sammy-tri, and @xuchenhan-tri)

___
*[`manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FuNPo68SJ_5X17hQ-:-N1FuNPp7ZwXYX4UOR7i:bugnlh9) ([raw file](https://github.com/robotlocomotion/drake/blob/009fc1ba0557496a2a93b268ba720586173d6c53/manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf#L33)):*
> ```
>         </material>
>       </visual>
>       <gravity>1</gravity>
> ```

BTW, why is the `gravity` tag removed. It's supported, right? Ditto throughout the changed SDF files.
(Similarly, a few `kinematic` tags have been dropped).
___
*[`multibody/parsing/detail_sdf_diagnostic.h` line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FlSel6a2gBJ_J3z3i:-N1FlSel6a2gBJ_J3z3j:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/d2ce07e753434dc421411445a3a4c247a4df9ea1/multibody/parsing/detail_sdf_diagnostic.h#L29)):*
> ```objc
>     const std::set<std::string>& supported_elements);
> 
> /// Checks that, for elements where there is only one supported value, that
> ```

nit



_Suggestion:_
```objc
/// Checks, for elements where there is only one supported value, that
```
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FM8l51bx7e9YanW6k:-N1FmDT73ZP5b9E3Bu7Z:b-pm2yeq) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L22)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think it's probably appropriate to continue executing in this case.  The `while (element)` check should keep from dereferencing the pointer, and I think it's potentially valid to have an element with no children.
</blockquote></details>

Even in case, checking `root_element` (instead of `element`) still seems like the prudent thing to do.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FncZ87s7I7f-vrbiH:-N1FncZ87s7I7f-vrbiI:bytfkcz) ([raw file](https://github.com/robotlocomotion/drake/blob/d2ce07e753434dc421411445a3a4c247a4df9ea1/multibody/parsing/detail_sdf_diagnostic.cc#L55)):*
> ```cpp
>   }
> 
>   sdf::ElementPtr element = root_element->GetElement(element_name);
> ```

nit can `element` be null?

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[`manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FuNPo68SJ_5X17hQ-:-N1Fw3Sj2UfC_2CB-fU0:bjd8y6w) ([raw file](https://github.com/robotlocomotion/drake/blob/009fc1ba0557496a2a93b268ba720586173d6c53/manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, why is the `gravity` tag removed. It's supported, right? Ditto throughout the changed SDF files.
(Similarly, a few `kinematic` tags have been dropped).
</blockquote></details>

I started sanitizing this file before I decided to allow through elements with supported default values like `gravity` and `kinematic` and I never put those elements back.  I can if you'd prefer it.
___
*[`multibody/parsing/detail_sdf_diagnostic.h` line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FlSel6a2gBJ_J3z3i:-N1FwNaK3CwWVM7CycBW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2ce07e753434dc421411445a3a4c247a4df9ea1/multibody/parsing/detail_sdf_diagnostic.h#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FM8l51bx7e9YanW6k:-N1FwQ6iDZWsTADZMW7z:bfie0oj) ([raw file](https://github.com/robotlocomotion/drake/blob/34a9bf04d02d36876a947ad504f1fd5b1f19a16e/multibody/parsing/detail_sdf_diagnostic.cc#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Even in case, checking `root_element` (instead of `element`) still seems like the prudent thing to do.
</blockquote></details>

Done.  I accidentally read `element` instead of `root_element` in the original comment.
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1Fn-ulDcmD5dsuJA6j:-N1G-Zk05Bd9bAfCoozj:b6d7rnp) ([raw file](https://github.com/robotlocomotion/drake/blob/d2ce07e753434dc421411445a3a4c247a4df9ea1/multibody/parsing/detail_sdf_diagnostic.cc#L51)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit what happens with sdf::ElementPtr if we deref a null-containing one?
</blockquote></details>

Done (added a check to avoid finding out the answer).
___
*[`multibody/parsing/detail_sdf_diagnostic.cc` line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FncZ87s7I7f-vrbiH:-N1G-hTw0-b3lzkSm4wJ:b-d7ugui) ([raw file](https://github.com/robotlocomotion/drake/blob/d2ce07e753434dc421411445a3a4c247a4df9ea1/multibody/parsing/detail_sdf_diagnostic.cc#L55)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit can `element` be null?
</blockquote></details>

I don't believe so, since we checked `HasElement` above before calling `GetElement).

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17101)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @sammy-tri)

___
*[`manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17101#-N1FuNPo68SJ_5X17hQ-:-N1G9JzY4lstWEZXbtw3:b34z4bb) ([raw file](https://github.com/robotlocomotion/drake/blob/009fc1ba0557496a2a93b268ba720586173d6c53/manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf#L33)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I started sanitizing this file before I decided to allow through elements with supported default values like `gravity` and `kinematic` and I never put those elements back.  I can if you'd prefer it.
</blockquote></details>

I see. Thanks for the explanation. I'm all for removing tags with no effects.

**Pull request merged**
