### PR TITLE
[controllers] Use descriptive InverseDynamics port names

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See also #20080 and #20082.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20079)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for design review -- please check the header file and see if you agree with the updated port names.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20079)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

___
*[`systems/controllers/inverse_dynamics.h` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20079#-Ncv9OYXDV8R74ITzHha:-Ncv9OYY1v4ezIq1BZ5s:b-1w0h9n) ([raw file](https://github.com/RobotLocomotion/drake/blob/3bb0ea1396e075a0d4f718e98b78f1d2c554144c/systems/controllers/inverse_dynamics.h#L47)):*
> ```objc
>  * - <span style="color:gray">desired_acceleration</span>
>  * output_ports:
>  * - force
> ```

see https://manipulation.mit.edu/force.html#toolbox for a design sketch (including decisions about port names)  that I iterated on before with @EricCousineau-TRI . 
See also https://drake.mit.edu/doxygen_cxx/group__control__systems.html for the current state of affairs. 

Request: change the output port to `generalized_force`. 
(and I'd love to follow-up with the other port renames, now that we have the port-deprecation capability).

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20079)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

___
*[`systems/controllers/inverse_dynamics.h` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20079#-Ncv9OYXDV8R74ITzHha:-NcvAVhU3zhRRrWdwqva:b-qtfse9) ([raw file](https://github.com/RobotLocomotion/drake/blob/3bb0ea1396e075a0d4f718e98b78f1d2c554144c/systems/controllers/inverse_dynamics.h#L47)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

see https://manipulation.mit.edu/force.html#toolbox for a design sketch (including decisions about port names)  that I iterated on before with @EricCousineau-TRI . 
See also https://drake.mit.edu/doxygen_cxx/group__control__systems.html for the current state of affairs. 

Request: change the output port to `generalized_force`. 
(and I'd love to follow-up with the other port renames, now that we have the port-deprecation capability).
</blockquote></details>

cc @AdityaBhat-TRI in case he wants to weigh in, too.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20079)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

___
*[`systems/controllers/inverse_dynamics.h` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20079#-Ncv9OYXDV8R74ITzHha:-NcvVdwJ8pDT982PGSnl:biy09sh) ([raw file](https://github.com/RobotLocomotion/drake/blob/3bb0ea1396e075a0d4f718e98b78f1d2c554144c/systems/controllers/inverse_dynamics.h#L47)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

cc @AdityaBhat-TRI in case he wants to weigh in, too.
</blockquote></details>

Great, thanks.  I think I've updated everything in InverseDynamics and InverseDynamicsController to match the toolbox design.

**Review by RussTedrake — COMMENTED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20079#-:-Ncva-o58X3Xpaz3NUbq:bg7igkv)* status: needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> Reviewed 10 of 10 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20079#-:-Ncwdedp07nZq1WO3UO9:b4mx0my)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 10 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20079#-:-Ncx2f9P5pdb40aehFCR:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform)

**Comment by RussTedrake** [comment]
It did not occur to be before, but the port-name deprecation does not protect users who were calling the `get_output_port()` sugar (e.g. they were assuming just one output port).  My manipulation CI this morning has a number of instances of 
```
    controller.get_output_port(), plant.get_actuation_input_port()
RuntimeError: Cannot use the get_output_port() convenience method unless there is exactly one output port. num_output_ports() = 2
```

**Comment by jwnimmer-tri** [comment]
I have https://github.com/RobotLocomotion/drake/issues/20082 filed for making that better.

**Comment by RussTedrake** [comment]
fwiw -- i just rendered a graphviz diagram that has the tombstones from the deprecated ports.  I get the text:
```
WARNING:drake:OutputPort[1] (force) of System ::with iiwa controller::iiwa_controller (InverseDynamicsController<double>) is deprecated: The output port name 'force' is deprecated and will be removed from Drake on or after 2024-01-01. Use the name 'generalized_force' instead.
```

but I see the image
output

Expected: the second output port of the InverseDynamicsController block should say `force`.
Actual: It says `y0` (with a cute little tombstone)

**Comment by RussTedrake** [comment]
Note also that the SharedPointerSystem drops odd little empty ellipsoids into the Diagrams (and it happens always now that I'm using HardwareStation).

**Pull request merged**
