### PR TITLE
Enable OSQP for LP.

### LINKED ISSUE #14602: Osqp in Drake requires a quadratic cost
OSQP in the upstream code claim to solve LP also (without a quadratic cost). Previously I disabled solving LP with OSQP as I didn't get good answer, but with the newer version of OSQP things might have changed.

We should either
1. Allow OSQP to solve LP in drake if it could.
2. Throw a more meaningful error message and update the doc page.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #14602

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14604)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
I assume that this was meant to be a WIP PR; adding tags to reflect that.

Can you also provide context for this change? (was it on Slack? if so, can you provide a link at a minimum, a summary at a maximum?)

**Review by hongkai-dai — COMMENTED** [review]
It was from a slack discussion with Russ and his students at MIT. They want to use OSQP to solve LP. I will see if I can change the code to pass the CI, otherwise I will close this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14604#-:-MSWeGK_1pd8vWF1Hak1:b-q4u4x0)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Comment by jwnimmer-tri** [comment]
@hongkai-dai Given some recent conversations in other PRs, I wonder if you're decided that OSQP should not be allowed to solve LP, and so we close this one?  What do you think?

**Comment by hongkai-dai** [comment]
Ah you are right. I forgot I have this dangling PR. I introduced CLP in order to replace OSQP for solving LP.

**Pull request closed without merging**
