### PR TITLE
doxygen: add 1.8.15 binary for Focal

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #13102.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13266)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
___
*[tools/workspace/doxygen/.gitignore, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13266#-M737WbM1k0W6p5-smIK:-M737WbM1k0W6p5-smIL:b32wpx) ([raw file](https://github.com/robotlocomotion/drake/blob/e8a75283ef566c94233e6d244b2f318fd5d311d0/tools/workspace/doxygen/.gitignore#L2)):*
> ```ignore
> doxygen-*-x86_64.tar.gz
> doxygen-*-x86_64.tar.gz.sha256
> ```

kk

**Comment by jamiesnape** [comment]
Need to remove obsolete fields from the Doxyfile.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
Let's try 3.8.16. I see a few 3.8.16 to 3.8.17 regressions in the bug tracker.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
Auto-brief seems to only work in `@defgroup` blocks like this: https://github.com/RobotLocomotion/drake/blob/574cafdc9a0d7b22f760ac54321681f4e1d7ac7f/multibody/plant/contact_model_doxygen.h#L311-L312 (which in this case is bad, unfortunately).

Kind of surprised it ever worked in `@ingroup`, etc.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
Back to 1.8.15...

**Comment by jamiesnape** [comment]
I think this should be ready for review again now.

**Comment by jwnimmer-tri** [comment]
+@sherm1 do you want to take platform on this one?  Or else kick it to Monday.

**Comment by jwnimmer-tri** [comment]
Yup, all good.

**Pull request merged**
