### PR TITLE
Add issue component for graphs of convex sets

### PR DESCRIPTION
**Pull request by RussTedrake**
+@hongkai-dai for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22000)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: Thanks for taking care of this.

+@SeanCurtis-TRI for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22000#-:-O8b64uI32AcKr-L9TS3:b-nr1a3z)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22000#-:-O8bJGpABtCEfyIWnNLE:bmxilld)* status: missing label for release notes (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22000#-:-O8bJIQlE3B0ejwf6a03:b-safpmt)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai

**Comment by SeanCurtis-TRI** [comment]
Who adds the github tag?

**Comment by SeanCurtis-TRI** [comment]
*[`doc/_pages/issues.md` line 175 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22000#-O8bJqFEDwljfiidFMSt:-O8bJqFEDwljfiidFMSu:b-5d7xhr) ([raw file](https://github.com/RobotLocomotion/drake/blob/93b1922e65c526cbbb0e2bb1be1bf02ae3fdd1ce/doc/_pages/issues.md#L175)):*
> ```Markdown
> 
> <tr>
> <td><code>graphs of convex sets</code></td>
> ```

Oops. I should've looked at the larger context. All of the rows in this table are *alphabetized*. This one is now out of order.

**Comment by SeanCurtis-TRI** [comment]
*[`doc/_pages/issues.md` line 175 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22000#-O8bJqFEDwljfiidFMSt:-O8bLPIT1tdmMgZBqVDD:bx1rxug) ([raw file](https://github.com/RobotLocomotion/drake/blob/93b1922e65c526cbbb0e2bb1be1bf02ae3fdd1ce/doc/_pages/issues.md#L175)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Oops. I should've looked at the larger context. All of the rows in this table are *alphabetized*. This one is now out of order.
</blockquote></details>

#22001 moves it.

**Comment by SeanCurtis-TRI** [comment]
I went ahead and added it.

**Pull request merged**
