### PR TITLE
py mpb: Add bindings for LinearBushingRollPitchYaw

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Would like to use this in Anzu.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14070)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for platform review, please!
\cc @joemasterjohn 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14070#-:-MHI74uI9brs0t_3lA6v:b-i4ak6e)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by EricCousineau-TRI — COMMENTED** [review]
Er, both, I meant both reviews, please!
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14070#-:-MHIBPEu1D2cywOYxBgs:b-bwuusv)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 with a minor request to take advantage of our abundant supply of integers :)

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14070#-:-MHIS_Bd3nOlHZYA6FfB:b2oc5hf)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/multibody/tree_py.cc, line 587 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14070#-MHIQ5XY5YVYRZfcWsvQ:-MHIQ5XY5YVYRZfcWsvR:bb4nxqs) ([raw file](https://github.com/robotlocomotion/drake/blob/ae3d7c4c3ded3bb0fd2094fa8156965aa05483d0/bindings/pydrake/multibody/tree_py.cc#L587)):*
> ```cpp
>             py::arg("context"), cls_doc.GetForceDampingConstants.doc)
>         .def("GetTorqueStiffnessConstants", &Class::GetTorqueStiffnessConstants,
>             py::arg("context"), cls_doc.GetTorqueStiffnessConstants.doc)
> ```

minor: this method was already defined above
___
*[bindings/pydrake/multibody/test/plant_test.py, line 576 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14070#-MHIRr2Z7yjX1FJR4PJS:-MHIRr2Z7yjX1FJR4PJT:bjnwg95) ([raw file](https://github.com/robotlocomotion/drake/blob/ae3d7c4c3ded3bb0fd2094fa8156965aa05483d0/bindings/pydrake/multibody/test/plant_test.py#L576)):*
> ```Python
>         numpy_compare.assert_float_equal(
>             bushing.GetForceDampingConstants(context=context),
>             [2.0, 2.0, 2.0])
> ```

Minor: the tests above would be more convincing if each of the numbers was unique. As written get_force could be returning the get_torque values.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14070)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @sherm1)

___
*[bindings/pydrake/multibody/tree_py.cc, line 587 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14070#-MHIQ5XY5YVYRZfcWsvQ:-MHIZT96Bz6xNxV39D_F:b-y1zffl) ([raw file](https://github.com/robotlocomotion/drake/blob/ae3d7c4c3ded3bb0fd2094fa8156965aa05483d0/bindings/pydrake/multibody/tree_py.cc#L587)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this method was already defined above
</blockquote></details>

Done. Oops, thanks for catching that!
___
*[bindings/pydrake/multibody/test/plant_test.py, line 576 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14070#-MHIRr2Z7yjX1FJR4PJS:-MHIZV2S1-2brx4qXPHe:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/ae3d7c4c3ded3bb0fd2094fa8156965aa05483d0/bindings/pydrake/multibody/test/plant_test.py#L576)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Minor: the tests above would be more convincing if each of the numbers was unique. As written get_force could be returning the get_torque values.
</blockquote></details>

Done. Thanks!

**Comment by EricCousineau-TRI** [comment]
Skipping slow builds

**Pull request merged**
