### PR TITLE
Rename Binding::constraint() to Binding::Evaluator()

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8257)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for both reviews, since most the the change in this PR is just replacing `constraint()` with `evaluator()`

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-:-L6scaM6xO7Dt99SsMX3:b-3u421h)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-L6wKf0Trc-Sr4EInK6L:-L6wKf0UzIYiSw6LOvH9:bad4l24) ([raw file](https://github.com/robotlocomotion/drake/blob/8bcc746ca5e1595a7280f9be7b633e53d4e19e98/bindings/pydrake/solvers/mathematicalprogram_py.cc#L70)):*
> ```cpp
>   string pyname = "Binding_" + name;
>   auto binding_cls = py::class_<B>(scope, pyname.c_str())
>     .def("evaluator", &B::evaluator)
> ```

Should we consider keeping the deprecated accessor?
If you'd like, I can whip up something that would print out a deprecation warning whenever `.constraint` is accessed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-:-L6wK_4jLKpYu1TbHVTt:bpqxd5f)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-L6wKf0Trc-Sr4EInK6L:-L6w_WUu-wKVnMdSfbY8:b6ep4kb) ([raw file](https://github.com/robotlocomotion/drake/blob/8bcc746ca5e1595a7280f9be7b633e53d4e19e98/bindings/pydrake/solvers/mathematicalprogram_py.cc#L70)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Should we consider keeping the deprecated accessor?
If you'd like, I can whip up something that would print out a deprecation warning whenever `.constraint` is accessed.
</blockquote></details>

Good idea, would you commit the change to print out the deprecation warning?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257)*

**Comment by EricCousineau-TRI** [comment]
BTW Depending on which merges first, this PR may have to accommodate https://github.com/RobotLocomotion/drake/pull/8248

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-:-L6w_qGv6U-9ne9oPAoy:b-c47ija)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-L6wKf0Trc-Sr4EInK6L:-L6wxrYayTbH_cR3L1M1:b-ce4m8n) ([raw file](https://github.com/robotlocomotion/drake/blob/8bcc746ca5e1595a7280f9be7b633e53d4e19e98/bindings/pydrake/solvers/mathematicalprogram_py.cc#L70)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good idea, would you commit the change to print out the deprecation warning?
</blockquote></details>

It looks like it may take a bit more than a day to get this done, as I'd like to submit it as a separate PR.

If you'd like to get this merged in before then, would you just be able to add in `.def("constraint", ...)`, and add a TODO for me?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257)*

**Comment by hongkai-dai** [comment]
Review status: 36 of 37 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-L6wKf0Trc-Sr4EInK6L:-L6x9qsQWlzo2HtbxE_D:bqlq91f) ([raw file](https://github.com/robotlocomotion/drake/blob/8bcc746ca5e1595a7280f9be7b633e53d4e19e98/bindings/pydrake/solvers/mathematicalprogram_py.cc#L70)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

It looks like it may take a bit more than a day to get this done, as I'd like to submit it as a separate PR.

If you'd like to get this merged in before then, would you just be able to add in `.def("constraint", ...)`, and add a TODO for me?
</blockquote></details>

Sure! Just add back the python binding for `constraint`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-L6xQc527THBR4bzUNzV:-L6xQc527THBR4bzUNzW:b-svp31a) ([raw file](https://github.com/robotlocomotion/drake/blob/6df5cc3acd83c7eb810233e2f0cc270dba3979c7/bindings/pydrake/solvers/mathematicalprogram_py.cc#L78)):*
> ```cpp
>       py::class_<B>(scope, pyname.c_str())
>           .def("evaluator", &B::evaluator)
>           .def("constraint",
> ```

BTW Rather than refer to `B::constraint`, could you refer to `B::evaluator`, so that our builds to not encounter deprecation warnings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257)*

**Comment by hongkai-dai** [comment]
Review status: 36 of 37 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-L6xQc527THBR4bzUNzV:-L6xS0PpekHKvgjGNSjc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6df5cc3acd83c7eb810233e2f0cc270dba3979c7/bindings/pydrake/solvers/mathematicalprogram_py.cc#L78)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Rather than refer to `B::constraint`, could you refer to `B::evaluator`, so that our builds to not encounter deprecation warnings?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-L6xedF5ruIXeFUFo6t8:-L6xedF66MjADOr2vVZk:b41ahdt) (no related file):*
BTW spelling nit Can you rename this PR? "Evalautor" should be "Evaluator"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-L6xedF5ruIXeFUFo6t8:-L6xizbFVImPSE5sgSaW:b-376vyb) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW spelling nit Can you rename this PR? "Evalautor" should be "Evaluator"
</blockquote></details>

Done. Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8257#-:-L6xj5a_VWq-zwd6jYdb:b-l70wzf)*

**Pull request merged**
