### PR TITLE
[lcm] Notice errors during message encoding

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a bit more relevant with #20761 on the horizon.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20760)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please (tomorrow is OK).
+@sherm1 for platform review per schedule, please.

\CC @sammy-tri @ggould-tri FYI

**Review by sherm1 — COMMENTED** [review]
Out of order platform :lgtm: pending Eric's feature review stamp

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20760#-:-NnpiVCu741RYegq5UgJ:b-jry4v6)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`lcm/lcm_messages.h` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20760#-NnphILxDSxegFAcjVz6:-NnphILxDSxegFAcjVz7:b-vw0c2o) ([raw file](https://github.com/RobotLocomotion/drake/blob/09ed2eeb8de4f22030290f9bca2dd75ce2c4383e/lcm/lcm_messages.h#L25)):*
> ```objc
>   DRAKE_THROW_UNLESS(num_bytes >= 0);
>   const size_t size_bytes = static_cast<size_t>(num_bytes);
>   std::vector<uint8_t> bytes(size_bytes);
> ```

BTW size_bytes has outlived its utility now that num_bytes is int64_t
___
*[`lcm/test/lcm_messages_test.cc` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20760#-NnpiLKC1lvqpKLb8Ic7:-NnpiLKDCqmV9V4saOG_:b-8bxuyt) ([raw file](https://github.com/RobotLocomotion/drake/blob/09ed2eeb8de4f22030290f9bca2dd75ce2c4383e/lcm/test/lcm_messages_test.cc#L39)):*
> ```cpp
>       EncodeLcmMessage(bad),
>       "Error encoding message of type.*BuggyLcmMessage.*");
> }
> ```

BTW if feasible, please consider a bad decode test as well

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20760)* status: LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`lcm/test/lcm_messages_test.cc` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20760#-NnpiLKC1lvqpKLb8Ic7:-NnpjliM55VXOrkZ-3Uo:b-kb54rv) ([raw file](https://github.com/RobotLocomotion/drake/blob/09ed2eeb8de4f22030290f9bca2dd75ce2c4383e/lcm/test/lcm_messages_test.cc#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW if feasible, please consider a bad decode test as well
</blockquote></details>

It's the next test case, below.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20760)* status: LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`lcm/test/lcm_messages_test.cc` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20760#-NnpiLKC1lvqpKLb8Ic7:-Nnpkb4nEtopY9ge-HPw:b-3cyhl4) ([raw file](https://github.com/RobotLocomotion/drake/blob/09ed2eeb8de4f22030290f9bca2dd75ce2c4383e/lcm/test/lcm_messages_test.cc#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's the next test case, below.
</blockquote></details>

:+1:  (Reviewable only showed me the changes so I missed that!)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20760#-:-NnpyaFc8TP9FGm--xhD:b-vtj4w1)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform)

**Pull request merged**
