### PR TITLE
render_engine_gl: Minor cleanup

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Mutate PerceptionProperties for all geometries
Sprinkle some const here and there

Follow-up to #14396

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14400)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for feature review when you have the time!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14400#-:-MNVmULtC6Tqnl28XAT4:b-62z688)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14400)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14400#-MNZDmHn75DQIIjKQpFP:-MNZDmHn75DQIIjKQpFQ:b-xbrk2w) (no related file):*
What I'd actually had in mind is to perform the properties copy [here](https://github.com/RobotLocomotion/drake/blob/master/geometry/render/gl_renderer/render_engine_gl.cc#L585-L592). The `user_data` now contains a reference to the properties defined as a local to that function (guaranteeing its scope) with the intent that any of the functions invoked in that scope can add to the properties to communicate...whatever.

That means we don't have to change any of the other function signature. The change would be:

1. `RegistrationData` stores a pointer to a non-`const` `PerceptionProperties` (instead of the `const&`.)
2. `DoRegisterVisual` performs the copy and adds a comment explaining the intent of the copy.
3. Current sites where we add to the properties should test to make sure they are adding a *novel* property (and not overwriting something set outside of `RenderEngineGl`).
4. The implementation of the various shaders should *document* which properties they depend on (and how they handle missing properties).

I'd suggest you simply retire this PR and I'll take care of this internal clean up when I get back.
    

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14400)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14400#-MNZDmHn75DQIIjKQpFP:-MNa1h1tB5hfDsj4hByC:b-uxbfx0) (no related file):*
Ah... My main (but minor) concern was what piggy-backing `RenderEngineGl::ImplementMesh()` would have to do (e.g. two copies). But I see - mutable copied `Properties` admits mutation right then and there.

> I'd suggest you simply retire this PR and I'll take care of this internal clean up when I get back.

I'm 100% down for this!
Please let me know if you'd like me to create a tracking issue as follow-up.

Closing.

---

**Comment by SeanCurtis-TRI** [comment]
A tracking issue would be marvelous -- particularly as I'm still a month away from being "back".

**Comment by EricCousineau-TRI** [comment]
Done! https://github.com/RobotLocomotion/drake/issues/14407

**Pull request closed without merging**
