### PR TITLE
Update to gurobi9.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13049)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Please assign a priority label to this PR.  There is a ton of work going on currently, so we need to decide if we need to suspend any of that work for this upgrade request.

**Comment by hongkai-dai** [comment]
@jwnimmer-tri  As gurobi 8 (the current version supported by Drake) only supports python 3.7 (https://www.gurobi.com/news/gurobi-optimizer-v8-1/), and on Mac Drake only supports python 3.8, I think upgrading to gurobi 9 becomes more urgent? @wualbert tried python 3.8 with gurobi 8 on his Mac machine and he mentions they don't work.

**Comment by jwnimmer-tri** [comment]
Are two two gurobi versions co-installable on macOS?  That is, install G9 and call it directly from python, but keep G8 installed for use by C++ drake?  Drake itself doesn't use gurobi's python support, does it?

**Comment by hongkai-dai** [comment]
Good point. Drake doesn't use gurobi's python interface. So Drake can continue to support gurobi 8 with Mac python 3.8.

I had ran into problem when I have both Gurobi 8 and Gurobi 9 on my machine. Gurobi requires to set the environment variable $GUROBI_HOME as explained in https://www.gurobi.com/documentation/9.0/quickstart_linux/software_installation_guid.html. So I cannot have both gurobi 8 and 9 and use them simultaneously. To use gurobi 8, I had to set $GUROBI_HOME guruboi8 folder. If I switch to gurobi 9, I had to change $GUROBI_HOME.

**Comment by jwnimmer-tri** [comment]
So not an emergency blocker but definitely annoying.

**Comment by jwnimmer-tri** [comment]
It looks like Drake doesn't use GUROBI_HOME though?  It uses GUROBI_PATH.

If setting GUROBI_HOME to 9 breaks Drake, then something is breaking bazel's hermiticity and we should investigate.

**Comment by hongkai-dai** [comment]
On my computer, I have
```
export GUROBI_PATH=PATH_TO_GUROBI8
export GUROBI_HOME=$GUROBI_PATH
```
so it works with `GUROBI_PATH` and Drake.

Maybe we should follow Gurobi's convention, to only use `GUROBI_HOME`?

**Comment by jamiesnape** [comment]
Do we want 9.0.0 or 9.0.2? I already have 9.0.2 in the pre-provisioning scripts on CI: https://github.com/RobotLocomotion/drake-ci/blob/56bdc6d84966cb4c1749676516a776bd47f18ca3/setup/ubuntu/install_prereqs#L113-L120

**Comment by jwnimmer-tri** [comment]
Let's stick with the newer (9.0.2) one.  So @hongkai-dai we just need a small tweak to this PR and it'll likely pass CI already?

**Comment by jwnimmer-tri** [comment]
> Maybe we should follow Gurobi's convention, to only use GUROBI_HOME?

Yes, and in particular right now Drake CI hard-codes `GUROBI_PATH` to 8.0.1 which is breaking this PR.

I have the TODO
```python
# TODO(jwnimmer-tri) The Gurobi docs use /opt/gurobi801/linux64, so we should
# probably look in that location as a reasonable default guess.
```

... which I think now we should do in this PR.  Then, it should pass CI.

So in short:
- Rename GUROBI_PATH to GUROBI_HOME everywhere in code and docs.  Document it as "You may set this on Ubuntu to override the default installation path; only use when necessary" or simliar.
- Default GUROBI_HOME to the correct value (in repository.bzl) for Ubuntu.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@jamiesnape We still need 9.0 installed on macOS images: https://github.com/RobotLocomotion/drake-ci/blob/56bdc6d84966cb4c1749676516a776bd47f18ca3/setup/mac/Brewfile#L41

**Comment by jamiesnape** [comment]
Yes, however versions technically do not coexist on macOS so I cannot do so in advance. Once this is ready I have to do a quick switch of images.

**Comment by jwnimmer-tri** [comment]
I am :lgtm: modulo macOS CI being ready.

**Pull request merged**
