### PR TITLE
Rotation constraint combining box-sphere intersection and bilinear product

### PR DESCRIPTION
**Pull request by hongkai-dai**
This is the first step to clean up our mixed-integer relaxation on SO(3) rotation constraint.

Previously we have two formulations on the relaxation

1. Consider the intersection region between a box and and sphere surface.
2. Consider the McCormick Envelope of the bilinear product w = x * y, in the SO(3) constraint RᵀR = I

In this PR, we provide the option, that these two formulations can be imposed jointly on a matrix `R`. Potentially this should tighten our relaxation.

@gizatt this could affect your pose estimation work, if you call `AddRotationMatrixBilinearMcCormickMilpConstraints`, with `add_mccormick_for_sphere_box_intersection` set to true.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8694)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[solvers/rotation_constraint.cc, line 1184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8694#-LB33l6I4Dsq380kZFjp:-LB33l6J76mNzKfEXr35:b-qdgeon) ([raw file](https://github.com/robotlocomotion/drake/blob/c3f25b40426411d5da86ae4e0772147ab3778319/solvers/rotation_constraint.cc#L1184)):*
> ```cpp
>                                                                limits);
> 
>   // Add constraints to the column and row vectors.
> ```

To reviewers: this deleted code block is moved into `AddMcCormickVectorConstraintsForR`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8694)*

**Comment by gizatt** [comment]
:lgtm: Gray codes still make my head spin, but I think I follow, and the refactors make sense.

BTW, I feel like the hierarchy here is getting a little weird, given the significant crosstalk between the two styles of SO(3) relaxation added here. By which I mean, to combine both styles of constraints, you take the bilinear mccormick envelope approx, and then add the box-sphere intersection constraints to it. If this road keeps being followed, would it be more natural to have a single SO(3)-relaxation-constructor that allows you to toggle on each of these different parts of the relaxation, rather than having multiple entry points with their own options? I could see this being tricky because the different relaxations share only some of their binary variables...

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8694#-:-LB7cTcP009rH6Wk-o3u:b8dwlko)*

**Comment by hongkai-dai** [comment]
I totally agree that the hierarchy is weird. I am trying to refactor this `rotation_constraint` file.

What I plan to do in my next few PRs
1. Create a class `RotationConstraintFactory`, which has different options for adding constraint, such as
  i. Using box-sphere versus bilinear McCormick envelope.
  ii. Using logarithmic binning or linear binning.
  iii. Use Gurobi's sos2 constraint (http://www.gurobi.com/documentation/7.5/refman/py_sos.html), or our implementation of sos2 constraint.
2. Currently when adding SO(3) relaxation, we solve an SOCP inside `AddBilinearMcCormickEnvelopeSOS2`. When we have multiple rotation matrices, and we want to relax all of them, that SOCP is solved repeatedly, for each relaxation. But the result of that SOCP is the same. So I will store that SOCP result inside the class `RotationConstraintFactory`, and then reuse it for every rotation matrix.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8694#-:-LB7gmhjAtYUTXJEPUGd:b7nntvp)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8694#-:-LB7iZpgAgoRIz33Wfjb:b6vi582)*

**Comment by sherm1** [comment]
If you haven't already, please run kcov to make sure the unit tests cover all the variants. Assuming yes: platform :lgtm: (with a minor BTW).

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[solvers/rotation_constraint.h, line 197 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8694#-LB7mgQv31L2JAh6pOBe:-LB7mgQv31L2JAh6pOBf:bk2xq8q) ([raw file](https://github.com/robotlocomotion/drake/blob/2c668d208a80c4db0b53e1ab43066475b505b2a0/solvers/rotation_constraint.h#L197)):*
> ```objc
>  * variable when NumIntervalsPerHalfAxis is dynamic.
>  * @param add_mccormick_for_sphere_box_intersection Set to true if we add some
>  * constraint to tighten the relaxation, that can be obtained by considering
> ```

BTW sounds like an output argument the way it is described. How about "If set to true, we add a constraint to tighten the relaxation ..."

---

*[solvers/rotation_constraint.cc, line 1388 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8694#-LB7quaI1cZ1_rsY4mw9:-LB7quaI1cZ1_rsY4mwA:b4dlvei) ([raw file](https://github.com/robotlocomotion/drake/blob/2c668d208a80c4db0b53e1ab43066475b505b2a0/solvers/rotation_constraint.cc#L1388)):*
> ```cpp
>   // B[i][j](0) = 1 => R(i, j) >= 0
>   // We can thus impose constraints on B[i][j](0).
>   if (is_power_of_two(num_intervals_per_half_axis)) {
> ```

Much nicer!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8694#-:-LB7rlPYAz6xs4MDD237:b-qn3sy2)*

**Comment by hongkai-dai** [comment]
Thanks for the reminder! Yes I just ran `kcov` and all the new code has been covered.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/rotation_constraint.h, line 197 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8694#-LB7mgQv31L2JAh6pOBe:-LB8QkWN28WmOhtl0wqf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c668d208a80c4db0b53e1ab43066475b505b2a0/solvers/rotation_constraint.h#L197)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW sounds like an output argument the way it is described. How about "If set to true, we add a constraint to tighten the relaxation ..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8694#-:-LB8NUWR8P_liu-Qy5oT:b-egrl6b)*

**Comment by sherm1** [comment]
Great, thanks. Just needs a squash-merge now with a nice commit message.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8694#-:-LB8lCbU5lCddQclDMfa:bmulhs5)*

**Pull request merged**
