### PR TITLE
Demo of changes needed to wrap our C++ library in Python and matlab

### PR DESCRIPTION
**Pull request by rdeits**
This should not be merged, but I wanted to open a pull request to show what would need to happen to support Python and Matlab bindings for our C++ code (the short answer is "not much"). 

This adds two external projects: swig_matlab, which is swig with added matlab support, and swigmake, which is my own collection of helper files to build swig modules with cmake. All of the code to generate the bindings lives in `bindings/CMakeLists.txt` and `bindings/*.i`

I had to make a few small changes for compatibility:

* I make SimulationOptions a standalone class instead of being nested
* I added #ifdef guards around our calls to EIGEN_MAKE_ALIGNED_OPERATOR_NEW which the swig parser doesn't like for some reason. That just makes sure swig doesn't try to bind the result of the eigen macros; it should not affect the actual c++ code that gets compiled
* I made a modified interface to inverseKin to make wrapping it easier

All of these changes should be pretty flexible. I'm sure this will probably break somehow when the DrakeSystem redesign comes in, but hopefully it won't take much effort to fix it (there's almost nothing drake-specific in the way I'm doing the SWIG wrappers). 

The python bindngs are pretty functional, and I have notebooks demonstrating LQR with simulation, and very basic IK. 

The matlab bindings don't work right now. The shared_ptr magic that lets me ignore the fact our interfaces require shared pointers doesn't work in matlab. So we can't use most of the methods unless we write our own C++ wrappers to make shared pointers to the classes we need. That's not hard, but I haven't done it yet.

### CODE REVIEW

**Comment by rdeits** [comment]
Basic gradientvar support now works, so we can do some kinematics with gradients in python: https://github.com/rdeits/drake/blob/rd-swig-matlab/drake/bindings/rbm.ipynb

**Comment by rdeits** [comment]
I'd really like to bring this into drake, even just as a demonstration, since I think people in the group (myself included) will want to try it out. The only issue that's actually *blocking* this is #1295

**Comment by RussTedrake** [comment]
I thought you didn’t want it in…(yet)  :)  

#1295 is simple enough.  will do it soon (maybe wed?)

**Comment by rdeits** [comment]
Good point :). But I think that it's usable enough now to be worth bringing in, as long as we don't count on the API not changing as the new drake systems come in.

**Comment by rdeits** [comment]
this now works with the new KinematicsCache interface, although I have only wrapped forwardKin and centerOfMass so far. Check out https://github.com/rdeits/drake/blob/rd-swig-matlab/drake/bindings/testRBM.m and https://github.com/rdeits/drake/tree/rd-swig-matlab/drake/bindings/pydrake/test

**Pull request closed without merging**
