### PR TITLE
Hot fix on 22223

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
fmt::join requires #include <fmt/ranges.h>.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22273)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: fix) 
+(priority: emergency) 
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22273#-:-ODMEZkU1gRjDB61mVid:bnryvku)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @SeanCurtis-TRI)

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22273#-:-ODMFFEb5KpinLybSDKO:bnfp4nl)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Blech. #22223 had new usage of `fmt::join` in two places. 

Later today, I'm going to augment our include linters to include `fmt::join`. I've seen enough issues with this in the last couple of months that there's no longer an good reason to defer automating this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22273#-:-ODMTP6u9gLV2en2PVvt:b-2s6jyc)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22273)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22273)* status: 1 unresolved discussion

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22273#-ODMnURXCNED0TOKHCBI:-ODMnURXCNED0TOKHCBJ:b1a1qrk) (no related file):*
Blocking on the unprovisioned sonoma build.

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22273)* status: 1 unresolved discussion

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22273#-ODMnURXCNED0TOKHCBI:-ODN2WDFBUgmrlApTVUw:be5jx3o) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Blocking on the unprovisioned sonoma build.
</blockquote></details>

The old request got stuck in the queue for almost three hours. Tried retriggering to see if that made any difference.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22273)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22273#-ODMnURXCNED0TOKHCBI:-ODNVi3bEzxQHORaV7LG:b-l28nif) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The old request got stuck in the queue for almost three hours. Tried retriggering to see if that made any difference.
</blockquote></details>

Passed.

**Pull request merged**
