### PR TITLE
Rename to AddMaximizeLogDeterminantCost.

### PR DESCRIPTION
**Pull request by hongkai-dai**
The old name is too verbose.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16309)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16309#-:-Msfhx0l8VaR8j4D5Lyg:ba7uda8)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Jenkins is failing.

**Review by hongkai-dai — COMMENTED** [review]
Thanks! Now CI is happy

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16309#-:-MsgJP178VfKRPosyawM:b8gnjt9)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16309#-:-Msgc4enA8w00RJOQ5Mf:b3dcro0)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16309#-Msgaz3p6in0KJEpo1y9:-Msgaz3p6in0KJEpo1yA:b-sm4mz) (no related file):*
nit By convention, the nominal date target would be 2022-05-01 (add three months, then round up).  It's fine if you want to use a sooner date, but your PR overview should mention that the divergence is on purpose (rather than accidental) so that your intention is clear.

---
___
*[solvers/mathematical_program.h, line 1236 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16309#-MsgbCPV5XMx65TDujqJ:-MsgbCPV5XMx65TDujqK:bo1z0y8) ([raw file](https://github.com/robotlocomotion/drake/blob/376c03f1badd71596feaca5d7e7c8a4203d18314/solvers/mathematical_program.h#L1236)):*
> ```objc
>              MatrixX<symbolic::Expression>>
>   AddMaximizeLogDeterminantSymmetricMatrixCost(
>       const Eigen::Ref<const MatrixX<symbolic::Expression>>& X);
> ```

Where does the definition of this function appear?
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1504 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16309#-Msgc0NO5SFpSpq-Pm8N:-Msgc0NO5SFpSpq-Pm8O:b-jcbwuf) ([raw file](https://github.com/robotlocomotion/drake/blob/376c03f1badd71596feaca5d7e7c8a4203d18314/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1504)):*
> ```cpp
>           MatrixX<symbolic::Expression>> (MathematicalProgram::*)(
>           const Eigen::Ref<const MatrixX<symbolic::Expression>>& X)>(
>           &MathematicalProgram::AddMaximizeLogDeterminantCost),
> ```

This should bind to the deprecated function pointer, not the new one.
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1505 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16309#-MsgboY-DW3EvS9OaBYh:-MsgboY-DW3EvS9OaBYi:b-nj3b81) ([raw file](https://github.com/robotlocomotion/drake/blob/376c03f1badd71596feaca5d7e7c8a4203d18314/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1505)):*
> ```cpp
>           const Eigen::Ref<const MatrixX<symbolic::Expression>>& X)>(
>           &MathematicalProgram::AddMaximizeLogDeterminantCost),
>       py::arg("X"), doc.MathematicalProgram.AddMaximizeLogDeterminantCost.doc);
> ```

nit The "doc" constant here should refer to the deprecation function docs, not the new function name.  That way, pydrake help and website will disclaim it as deprecated.
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 692 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16309#-MsgbPeD0nLSUP0NRG2P:-MsgbPeD0nLSUP0NRG2Q:b-ihcs9q) ([raw file](https://github.com/robotlocomotion/drake/blob/376c03f1badd71596feaca5d7e7c8a4203d18314/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L692)):*
> ```Python
>         self.assertAlmostEqual(a_val[1], 2)
> 
>     def test_log_determinant(self):
> ```

We need a unit test for the deprecated binding (with catch_drake_warnings around the "add cost" call).

The easy way to do that is to copy-paste the entire test case with a new name like `test_log_determinant_deprecated` that calls the old one, rather than trying to weave it into the existing test as a few new lines.  Then on removal day, we can just mindlessly remove the entire test method.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16309)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16309#-Msgaz3p6in0KJEpo1y9:-Msgsq4v24yYunjhmyTK:bhfz7bj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit By convention, the nominal date target would be 2022-05-01 (add three months, then round up).  It's fine if you want to use a sooner date, but your PR overview should mention that the divergence is on purpose (rather than accidental) so that your intention is clear.
</blockquote></details>

Done. I changed the deprecation date to 05-01.

---
___
*[solvers/mathematical_program.h, line 1236 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16309#-MsgbCPV5XMx65TDujqJ:-Msgt8Ty0ELI85ox-Kx9:b-u41ibe) ([raw file](https://github.com/robotlocomotion/drake/blob/376c03f1badd71596feaca5d7e7c8a4203d18314/solvers/mathematical_program.h#L1236)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Where does the definition of this function appear?
</blockquote></details>

Done. facepalm.
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1504 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16309#-Msgc0NO5SFpSpq-Pm8N:-MsgtHxTEky1uwAWMrrh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/376c03f1badd71596feaca5d7e7c8a4203d18314/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1504)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This should bind to the deprecated function pointer, not the new one.
</blockquote></details>

Done.
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 692 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16309#-MsgbPeD0nLSUP0NRG2P:-Msh-N5t2GXWFTwfIpfv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/376c03f1badd71596feaca5d7e7c8a4203d18314/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L692)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We need a unit test for the deprecated binding (with catch_drake_warnings around the "add cost" call).

The easy way to do that is to copy-paste the entire test case with a new name like `test_log_determinant_deprecated` that calls the old one, rather than trying to weave it into the existing test as a few new lines.  Then on removal day, we can just mindlessly remove the entire test method.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16309#-:-Msh2p6P2N5Gwg5i4wXk:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16309)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
