### PR TITLE
[tools] Fix kcov_tool to work with Bazel 7

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
This is a revival of #21188.
+@jwnimmer-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-:-O5UB6Wl4iGlBoUzfBaY:b-55c4fg)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
See also `drake-ci#288`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-:-O5UBra59UQe-Yjo-sNF:b14vzfg)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+(status: do not merge) +(status: do not review) while CI is still failing. in experiments.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-:-O5VKLHy2DhwTn19Jq1X:b-jbtuh7)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-O5VZx3G649ar6RQU3-j:-O5VZx3G649ar6RQU3-k:blaszqe) (no related file):*
Hm, ok. Local kcov builds and CI kcov builds are failing to produce coverage output for two different reasons. This PR only fixes the local build problems.

* local builds fail because the bazel file management of undeclared outputs got a bit tighter in Bazel 7. This patch fixes that, and also a pre-existing bug in checking zip file contents.
* CI builds fail because the images do not have `zip`. When `zip` is absent, the logic in [test-setup.sh](https://github.com/bazelbuild/bazel/blob/master/tools/test/test-setup.sh#L428-L433) fails to make output.zip, but then just blindly deletes all of the undeclared output files anyway. Possible fixes include adding `zip` to our images, or proposing patches to `bazel_tools`.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-O5VZx3G649ar6RQU3-j:-O5YrRnu3gNhqEi6hEF5:bxf58ja) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Hm, ok. Local kcov builds and CI kcov builds are failing to produce coverage output for two different reasons. This PR only fixes the local build problems.

* local builds fail because the bazel file management of undeclared outputs got a bit tighter in Bazel 7. This patch fixes that, and also a pre-existing bug in checking zip file contents.
* CI builds fail because the images do not have `zip`. When `zip` is absent, the logic in [test-setup.sh](https://github.com/bazelbuild/bazel/blob/master/tools/test/test-setup.sh#L428-L433) fails to make output.zip, but then just blindly deletes all of the undeclared output files anyway. Possible fixes include adding `zip` to our images, or proposing patches to `bazel_tools`.
</blockquote></details>

I think we should add `zip` to our prereqs.  Maybe as part of testonly, if it's only needed during testing and not cmake build+install?

https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/source_distribution/packages-jammy-test-only.txt
https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/source_distribution/packages-noble-test-only.txt

I believe previously we got `zip` as a side-effect of `dpkg -i bazel.deb`, but now that we're using bazelisk, we no longer do.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-O5VZx3G649ar6RQU3-j:-O5Yrobv4k0bYwltOEUh:bsp5fs6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think we should add `zip` to our prereqs.  Maybe as part of testonly, if it's only needed during testing and not cmake build+install?

https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/source_distribution/packages-jammy-test-only.txt
https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/source_distribution/packages-noble-test-only.txt

I believe previously we got `zip` as a side-effect of `dpkg -i bazel.deb`, but now that we're using bazelisk, we no longer do.
</blockquote></details>

Do images need to be respun as well?

FWIW, I did reproduce the symptoms locally by removing `zip`.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-O5VZx3G649ar6RQU3-j:-O5YsVtMAfWoyG_uN_VN:b4lzxgp) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Do images need to be respun as well?

FWIW, I did reproduce the symptoms locally by removing `zip`.
</blockquote></details>

Yes, changes to `setup/...` scripts in git are only reflected in CI either:
(1) in Unprovisioned builds, and
(2) after the Provisioned snapshot images are respun and deployed.

If you want to gate merging on CI proof, then the tactic would be to open a new PR that just adds zip, merge that, file a ticket for new Ubuntu provisioned images, and wait for those before testing your drake-ci again.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-O5VZx3G649ar6RQU3-j:-O5Yt1ge9GjhqRfHQaxB:bod7g4x) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, changes to `setup/...` scripts in git are only reflected in CI either:
(1) in Unprovisioned builds, and
(2) after the Provisioned snapshot images are respun and deployed.

If you want to gate merging on CI proof, then the tactic would be to open a new PR that just adds zip, merge that, file a ticket for new Ubuntu provisioned images, and wait for those before testing your drake-ci again.
</blockquote></details>

Yup, separate PR train sounds good. I'd like to land this one to reduce the amount of bespoke developer support I'm currently doing.

___

**Review by rpoyner-tri — COMMENTED** [review]
-(status: do not merge) -(status: do not review) Ready for review as original patch.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-:-O5YtQpa7XiP_Rt3B3s4:b-yi2uhq)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) if you are willing.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-:-O5YugnK51IpBRZMjpDR:bnrz25a)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(status: single reviewer ok) 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21859#-:-O5YuicGBo0rTSbglPub:b-fl40at)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
