### PR TITLE
[framework] Fix physical dependencies for InputPort::Allocate

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #18431.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18525)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

\CC @EricCousineau-TRI FYI

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending some CI healing

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18525#-:-NKtydt76mEAxLwO32lu:b-e1rx42)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule (later this week), please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18525#-:-NKzJFVkDKuyzXB2QRu0:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
