### PR TITLE
Improve buildifier

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update to a version of buildifier that allows overriding `NamePriority` per rule. Add custom tables for ordering the install framework rules, and use these when running buildifier. Apply the changes that these trigger.

This is split into two commits. The first commit has the "interesting" changes and results in the `bazel_lint` tests being broken as of that commit. The second applies the results of running `buildifier.sh` after the changes, and consists entirely of changes made by the same.

See also bazelbuild/buildtools#113.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6482)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

FYI With this mechanism now in place, I suspect we'll have the means to add `WORKSPACE` to the list of files that `./tools/buildifier.sh` reformats by default -- by teaching it how our github-specific macros should look.

---

Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/buildifier-tables.json, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KnqTDbEavmoFK0LSdH1:-KnqTDbEavmoFK0LSdH2:bh68zjh) ([raw file](https://github.com/robotlocomotion/drake/blob/27527645698af01f00e9ef19219c36ad7026d793/tools/buildifier-tables.json#L8)):*
> ```JSON
>   "IsSortableListArg": {
>     "allowed_externals": true,
>     "data": true,
> ```

The `data` setting seems to duplicate the built-in tables.  Oversight, or something tricky going on?

Ditto for "files".

---

*[tools/buildifier-tables.json, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KnqUrZ4Qi7NJpEgmPML:-KnqUrZ4Qi7NJpEgmPMM:b-ep77kq) ([raw file](https://github.com/robotlocomotion/drake/blob/27527645698af01f00e9ef19219c36ad7026d793/tools/buildifier-tables.json#L37)):*
> ```JSON
>     "install.guess_data_exclude": 426,
>     "install.docs": 440,
>     "install.license_docs": 440,
> ```

BTW Stale?

---

*[tools/buildifier-tables.json, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KnqUGRzzgoc29DGIiRe:-KnqUGRzzgoc29DGIiRf:be6k6pu) ([raw file](https://github.com/robotlocomotion/drake/blob/27527645698af01f00e9ef19219c36ad7026d793/tools/buildifier-tables.json#L42)):*
> ```JSON
>     "install.rename": 460,
>     "install_files.rename": 460,
>     "allowed_externals": 465,
> ```

BTW On purpose not to list this twice with `install.` and `install_files.`?  The `rename` seems to choose to be listed twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-:-KnqRyJF3RMRlJYyqct6:bdbx1l6)*

**Comment by mwoehlke-kitware** [comment]
> With this mechanism now in place, I suspect we'll have the means to add `WORKSPACE` to the list of files that `./tools/buildifier.sh` reformats by default

Yes, that may be. I haven't tried that to know what issues arise, but I seem to recall guessing at some point that it was "horrible rearranging of parameters that shouldn't be rearranged". If that's the case, I would indeed hope we will be able to rectify it with appropriate additions to `buildifier-tables.json`.

**Comment by mwoehlke-kitware** [comment]
Review status: 31 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/buildifier-tables.json, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KnqTDbEavmoFK0LSdH1:-KntI4coZxewMHtzKCSr:b-h86o6r) ([raw file](https://github.com/robotlocomotion/drake/blob/27527645698af01f00e9ef19219c36ad7026d793/tools/buildifier-tables.json#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `data` setting seems to duplicate the built-in tables.  Oversight, or something tricky going on?

Ditto for "files".
</blockquote></details>

More like paranoia... I want to make sure they get sorted for `install`. Moved to `SortableWhitelist` instead; hopefully that is more clear about the intent.

---

*[tools/buildifier-tables.json, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KnqUrZ4Qi7NJpEgmPML:-KntID-PZ_pd6UcC_lGA:b-c3n2o1) ([raw file](https://github.com/robotlocomotion/drake/blob/27527645698af01f00e9ef19219c36ad7026d793/tools/buildifier-tables.json#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Stale?
</blockquote></details>

Yes, thanks. Removed.

---

*[tools/buildifier-tables.json, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KnqUGRzzgoc29DGIiRe:-KntIKa5JH0VpSDbQ2EZ:b-8l9isg) ([raw file](https://github.com/robotlocomotion/drake/blob/27527645698af01f00e9ef19219c36ad7026d793/tools/buildifier-tables.json#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW On purpose not to list this twice with `install.` and `install_files.`?  The `rename` seems to choose to be listed twice.
</blockquote></details>

Semi-arbitrary paranoia... I figure `allowed_externals` is unlikely to be used by anything else. For `rename`, it is rule-qualified so as to avoid possibly being applied to some other rule that also uses `rename`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6482)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/buildifier-tables.json, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KnqUGRzzgoc29DGIiRe:-KntMl9adLAy_v5MGIWS:bqb0ro7) ([raw file](https://github.com/robotlocomotion/drake/blob/27527645698af01f00e9ef19219c36ad7026d793/tools/buildifier-tables.json#L42)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Semi-arbitrary paranoia... I figure `allowed_externals` is unlikely to be used by anything else. For `rename`, it is rule-qualified so as to avoid possibly being applied to some other rule that also uses `rename`.
</blockquote></details>

OK I probably would have chosen consistency over catching possible-future uses of allowed_externals, but this is fine too.  I wish there were a way to add a comment "# This is unlikely to be used by Bazel, so we don't need a qualifier", but that's JSON for you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6482)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 31 of 32 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 265 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KntNhZMb-8FahZngeDz:-KntNhZMb-8FahZngeE-:b-rqquol) ([raw file](https://github.com/robotlocomotion/drake/blob/74d5c813f7611508bab8f03cef7f2a8c94823407/WORKSPACE#L265)):*
> ```Python
>     repository = "bazelbuild/buildtools",
>     commit = "7ce605fb1585076ed681e37d82d0ef529244b23a",
>     sha256 = "c6210992d328212a7752a2c888a15f5c597dbf31f03ac0d59457ceff2928a30b",
> ```

BTW Personally, I would add a TODO to bump to the next tagged commit when it appears.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-:-KntNYNBmdsvc3u4vO5Q:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Review status: 30 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 265 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KntNhZMb-8FahZngeDz:-KntPyjpkC4X9YhTPbLn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74d5c813f7611508bab8f03cef7f2a8c94823407/WORKSPACE#L265)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Personally, I would add a TODO to bump to the next tagged commit when it appears.
</blockquote></details>

Done.

---

*[tools/buildifier-tables.json, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6482#-KnqUGRzzgoc29DGIiRe:-KntQ3XEsLYUIL6xReZW:bgydbc6) ([raw file](https://github.com/robotlocomotion/drake/blob/27527645698af01f00e9ef19219c36ad7026d793/tools/buildifier-tables.json#L42)):*
> I wish there were a way to add a comment [...] but that's JSON for you.

Agreed :smile:.

> I probably would have chosen consistency

Okay; the duplication isn't horrible anyway. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6482)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6482)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6482)*

**Comment by jwnimmer-tri** [comment]
Ready to merge.  I wasn't sure if you wanted it squashed or not, so I'll leave it to you @mwoehlke-kitware.

**Comment by jwnimmer-tri** [comment]
Good timing!

**Pull request merged**
