### PR TITLE
[pydrake] Add test case for PythonMessageSource

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This illustrates how to use a Python leaf system to output messages.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15220)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please.

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15220)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[bindings/pydrake/systems/test/lcm_test.py, line 174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15220#-Mck4tCS89YS_d4X5SPP:-Mck4tCS89YS_d4X5SPQ:b-v7pjj0) ([raw file](https://github.com/robotlocomotion/drake/blob/d324dd94f58d2df752898d395f18cfc136e105e7/bindings/pydrake/systems/test/lcm_test.py#L174)):*
> ```Python
> 
>         def CalcOutput(self, context, output):
>             output.utime = int(context.get_time() * 1e6)
> ```

Running and advancing simulator on the diagram told me `output` is no longer `lcmt`. Replacing with this works:

'''
msg = output.get_mutable_value()
msg.utime = int(context.get_time() * 1e6)
msg.frame_name = "frame_name"
'''

Everything shows up normal in `lcm-spy` afterwards so I think this fixes things for good.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15220)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[bindings/pydrake/systems/test/lcm_test.py, line 174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15220#-Mck4tCS89YS_d4X5SPP:-Mck5zFd0m3Uk0So_b5g:b-c1kzb4) ([raw file](https://github.com/robotlocomotion/drake/blob/d324dd94f58d2df752898d395f18cfc136e105e7/bindings/pydrake/systems/test/lcm_test.py#L174)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

Running and advancing simulator on the diagram told me `output` is no longer `lcmt`. Replacing with this works:

'''
msg = output.get_mutable_value()
msg.utime = int(context.get_time() * 1e6)
msg.frame_name = "frame_name"
'''

Everything shows up normal in `lcm-spy` afterwards so I think this fixes things for good. 
</blockquote></details>

Sounds like I should incorporate that and make sure the test catches that I missed it.  I'll work on it.

I also want to dig around to confirm that a Python leaf system is supposed to be explicitly aware that it needs to type-erase (and un-erase) its alloc and calc function's arguments, or whether that's supposed to happen automatically.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15220)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hjsuh94)

___
*[bindings/pydrake/systems/test/lcm_test.py, line 174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15220#-Mck4tCS89YS_d4X5SPP:-MckeEdC1Q7aY2BJ7tKW:bsqr52i) ([raw file](https://github.com/robotlocomotion/drake/blob/d324dd94f58d2df752898d395f18cfc136e105e7/bindings/pydrake/systems/test/lcm_test.py#L174)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sounds like I should incorporate that and make sure the test catches that I missed it.  I'll work on it.

I also want to dig around to confirm that a Python leaf system is supposed to be explicitly aware that it needs to type-erase (and un-erase) its alloc and calc function's arguments, or whether that's supposed to happen automatically.
</blockquote></details>

Done.

Also, I confirmed that it's conventional for Python's Calc methods to call `get_mutable_value()` to access the output data.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature - sweet!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15220#-:-McklG5T7p2DpkYulta0:beqe4t9)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hjsuh94)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15220#-:-McklSRV6uDGQ1hYNuEE:bppyoqd)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @hjsuh94 and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @hjsuh94 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15220)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15220#-:-McpI5EA7XrAbqviRkzQ:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/systems/test/lcm_test.py, line 171 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15220#-McpG9435o5Yw8MGYiFe:-McpG9435o5Yw8MGYiFf:bxw58bu) ([raw file](https://github.com/robotlocomotion/drake/blob/eca061831048c1594a002352c8fa837f53852263/bindings/pydrake/systems/test/lcm_test.py#L171)):*
> ```Python
> 
>         def AllocateOutput(self):
>             return AbstractValue.Make(lcmt_header())
> ```

BTW can Python make use of the new templatized flavor of this method for default-constructible types?

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/systems/test/lcm_test.py, line 171 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15220#-McpG9435o5Yw8MGYiFe:-McpIy8s4E-40m5Pqmk_:bo9cu35) ([raw file](https://github.com/robotlocomotion/drake/blob/eca061831048c1594a002352c8fa837f53852263/bindings/pydrake/systems/test/lcm_test.py#L171)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW can Python make use of the new templatized flavor of this method for default-constructible types?
</blockquote></details>

pydrake doesn't really support the idea of a template function when the list of instantiation types is unbounded.  Templates instantiations are predefined in the bindings, not implicitly instantiated by call sites like they are in C++.  The most similar alternative in Python would be to pass the type as an argument (`AbstractValue.Make(type=lcmt_header)`) but that ends up being more verbose that just calling the type's constructor anyway.

**Pull request merged**
