### PR TITLE
adds the exponential distribution as a fully supported random signal type

### PR DESCRIPTION
**Pull request by RussTedrake**
also hit the rule of three in my unit tests, so cleaned those up, too.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7106)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@soonho-tri for feature review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-:-KuxexXocojb4FWNtz2N:b-vawmhb)*

**Comment by soonho-tri** [comment]
:lgtm:

+@sammy-tri for platform review, please.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/test/random_source_test.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-Kuz41-CQqBtaivQlqXs:-Kuz41-CQqBtaivQlqXt:b-3lx9ep) ([raw file](https://github.com/robotlocomotion/drake/blob/e35588cc84d3a096079987c937f8d0077743ac0b/drake/systems/primitives/test/random_source_test.cc#L53)):*
> ```cpp
>   const int N = x.size();
> 
>   // Evaluate all subintervals (a,a+h) in (-2,2).
> ```

BTW, `(-2, 2)` -> `[min_value, max_value]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-:-Kuz3PJQfK_yjPqyi5eS:b-3v5mxt)*

**Comment by sammy-tri** [comment]
First pass complete, just one minor issue.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/test/random_source_test.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-Kuz8ScW5qJzi3tM7sF1:-Kuz8ScXt4BrRfPZXIyf:b-sryyng) ([raw file](https://github.com/robotlocomotion/drake/blob/e35588cc84d3a096079987c937f8d0077743ac0b/drake/systems/primitives/test/random_source_test.cc#L79)):*
> ```cpp
> }
> 
> GTEST_TEST(TestSignalLogger, UniformWhiteNoise) {
> ```

Naming the tests in this file "TestSignalLogger" seems odd.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-:-Kuz8klsCmNDBNFwuQ_a:bmgs57r)*

**Comment by amcastro-tri** [comment]
Pardon my ignorance on the subject, but this is super cool and I had to ask; how does this relate to the integration of an SDE say by the Euler–Maruyama method? can we guarantee that a given expectation E converges as we decrease the step size?
I believe this might be related to the sampling time `Ts` below? could you add a comment on how we'd usually choose this sampling time? or add a reference?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-:-KuzeiK1ZIH9-nkoOioV:but8x65)*

**Comment by RussTedrake** [comment]
@amcastro-tri 
> Re: Euler–Maruyama
I haven't looked closely, but I don't believe we're doing Euler-Maruyama.  The variance of our random input is fixed, not scaled by Δt.  I've been thinking of it instead as band-limited white noise (e.g. https://www.mathworks.com/help/simulink/slref/bandlimitedwhitenoise.html)

Would be happy to look more carefully at numerical SDE integration techniques (in the future).

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/test/random_source_test.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-Kuz41-CQqBtaivQlqXs:-Kv-_U3S0zFcm13n8rcC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e35588cc84d3a096079987c937f8d0077743ac0b/drake/systems/primitives/test/random_source_test.cc#L53)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `(-2, 2)` -> `[min_value, max_value]`
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/random_source_test.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-Kuz8ScW5qJzi3tM7sF1:-Kv-_eFzEwV88UjW96jH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e35588cc84d3a096079987c937f8d0077743ac0b/drake/systems/primitives/test/random_source_test.cc#L79)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Naming the tests in this file "TestSignalLogger" seems odd.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-:-Kv-ZhEutRyRwxKovyns:bc20rvw)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7106)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7106#-:-Kv2pwFAhDjn4yCCk6V9:bnfp4nl)*

**Comment by amcastro-tri** [comment]
@RussTedrake.
I love the description in the link provided! it's sound.

> Theoretically, continuous white noise has a correlation time of 0, a flat power spectral density (PSD), and a total energy of infinity. In practice, physical systems are never disturbed by white noise, although white noise is a useful theoretical approximation when the noise disturbance has a correlation time that is very small relative to the natural bandwidth of the system.

> In Simulink® software, you can simulate the effect of white noise by using a random sequence with a correlation time much smaller than the shortest time constant of the system. The Band-Limited White Noise block produces such a sequence. The correlation time of the noise is the sample rate of the block. For accurate simulations, use a correlation time much smaller than the fastest dynamics of the system. You can get good results by specifying

> tc≈1/100 * 2π/f_max, where fmax is the bandwidth of the system in rad/sec.

I think it'd be very nice if `RandomSource` had a similar documentation.

**Pull request merged**
