### PR TITLE
Add Generic Binding<Cost> and Binding<Constraint> to vertices and edges within a GcsTrajectoryOptimization::Subgraph

### PR DESCRIPTION
**Pull request by cohnt**
Towards #21981.

The use of templates gets a little messy, but allows a ton of code reuse. Note that in the test cases, we use `solvers::internal::ParseCost` and `solvers::internal::ParseConstraint` to convert `Expression` and `Formula` to `Binding<Cost>` and `Binding<Constraint>`, respectively.

+@Russtedrake for feature review, please! cc @wrangelvid

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22179)

### CODE REVIEW

**Review by cohnt — COMMENTED** [review]
I went ahead and added the python bindings while I'm here, since we had to change the old bindings to use `py::overload_cast`.

Also, we were using "used_in_transcription" throughout, which doesn't match GCS (it has "use_in_transcription"). I've gone through and fixed all instances -- since this is tagged `@experimental`, we should be able to get away without the standard deprecation timeline? I'll be more careful about matching naming conventions in the future.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-:-OBlVmDeEVrIv7B7bLZZ:bwgpgnj)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 340 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OBjP4ljBcM2bMHJr6xu:-OBlWDrw4Jkwl_1fegE1:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/87f7f479ed15fd886984a1bfbd83f73b8a7a3272/planning/trajectory_optimization/gcs_trajectory_optimization.h#L340)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i would recommend that the public API has the two specific entry points (with Expression and Binding<Cost>) and no template -- but you can certainly delegate via a single line to a private (or cc only method) that uses templates to keep the code clean.  Then the types are explicit in the signature, and don't have to be described in the docstring.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 936 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OBjQUZeENb1NWiyUygU:-OBlWGXn-Q3ZdHShqw8L:blegy6n) ([raw file](https://github.com/RobotLocomotion/drake/blob/87f7f479ed15fd886984a1bfbd83f73b8a7a3272/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L936)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

these would go away when you explicitly declare the correct entry points in the class.  (also all of the other explicit instantiations below)
</blockquote></details>

I found that I still got errors if I removed the explicit instantiations, but maybe I did something slightly different than what you were thinking.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@sammy-tri for platform review, please.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-:-OBz5FVb6CQwW3QLxPs9:b-ws0fkp)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 936 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OBjQUZeENb1NWiyUygU:-OBz4UDu5HxaFZccW6Yc:bm4peih) ([raw file](https://github.com/RobotLocomotion/drake/blob/87f7f479ed15fd886984a1bfbd83f73b8a7a3272/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L936)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

I found that I still got errors if I removed the explicit instantiations, but maybe I did something slightly different than what you were thinking.
</blockquote></details>

I see.  I'm pretty sure that's because you inlined the AddVertexCost etc methods (which call the explicit DoAddVertexCost) by having their implementation in the header.  If you move those (admittedly one line) implementations to the cc file, then you could drop these.  For my taste, it would be slightly more elegant to make this change rather than carry around the explicit instantiations.
___
*[`bindings/pydrake/planning/test/trajectory_optimization_test.py` line 408 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OBz55UD1SUjoh9w1iJI:-OBz55UD1SUjoh9w1iJJ:b8b3h2p) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce4ebb676bc0411455c23a86bfc46921380c802d/bindings/pydrake/planning/test/trajectory_optimization_test.py#L408)):*
> ```Python
>         regions.AddEdgeConstraint(binding=Binding[Constraint](
>                 to_bind_edge_constraint, to_bind_edge_constraint.vars()),
>                 use_in_transcription=restriction_only)
> ```

nit: could you spell out all of the argument names?  it's just a way to provide coverage on the spellings.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 554 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OBz4-Ud22K-SI41ZpL0:-OBz4-Ud22K-SI41ZpL1:byc6zwx) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce4ebb676bc0411455c23a86bfc46921380c802d/planning/trajectory_optimization/gcs_trajectory_optimization.h#L554)):*
> ```objc
>             use_in_transcription);
> 
>     // Compatible with Eexpression and Binding<Cost>.
> ```

nit: typo for expression

**Review by cohnt — COMMENTED** [review]
FYI this issue doesn't close #21981, since we still need the analogous methods for `EdgesBetweenSubgraphs` (see #22199), so I've removed that indicator in the pull request.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-:-OBzxWKO3HOtAcldF8fJ:b-5kzn6r)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 936 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OBjQUZeENb1NWiyUygU:-OC-0Unu7px6h3bVnmFy:bgez6ki) ([raw file](https://github.com/RobotLocomotion/drake/blob/87f7f479ed15fd886984a1bfbd83f73b8a7a3272/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L936)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I see.  I'm pretty sure that's because you inlined the AddVertexCost etc methods (which call the explicit DoAddVertexCost) by having their implementation in the header.  If you move those (admittedly one line) implementations to the cc file, then you could drop these.  For my taste, it would be slightly more elegant to make this change rather than carry around the explicit instantiations.
</blockquote></details>

Done throughout
___
*[`bindings/pydrake/planning/test/trajectory_optimization_test.py` line 408 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OBz55UD1SUjoh9w1iJI:-OC-0aK_7Rlo2AdyzYAk:b-g1zbh9) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce4ebb676bc0411455c23a86bfc46921380c802d/bindings/pydrake/planning/test/trajectory_optimization_test.py#L408)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: could you spell out all of the argument names?  it's just a way to provide coverage on the spellings.
</blockquote></details>

The arguments that aren't spelled out are the ones passed into the `Binding[Constraint](...)` constructor -- do we need to spell those ones out too? (The arguments to `AddEdgeConstraint` are `binding=...` and `use_in_transcription=...`.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22179)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 936 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OBjQUZeENb1NWiyUygU:-OC0VbqcEC-xYaKV__y7:bqfk5fz) ([raw file](https://github.com/RobotLocomotion/drake/blob/87f7f479ed15fd886984a1bfbd83f73b8a7a3272/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L936)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Done throughout
</blockquote></details>

There are still explicit instantiations of `DoAddEdgeConstraint` below.  Does this comment apply to them?
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 469 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OC0_cjdC_eEBdx1Xv-3:-OC0_cjeBW2xjVdsXX5E:b60usdl) ([raw file](https://github.com/RobotLocomotion/drake/blob/57794fd55e50763a5e8eacc1d0cd0b06244c9376/planning/trajectory_optimization/gcs_trajectory_optimization.h#L469)):*
> ```objc
>                     kRestriction});
> 
>     /** Convenience overload of AddEdgeCost to take in a Binding<Constraint>. */
> ```

nit: this should probably sat AddEdgeConstraint

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22179)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 469 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OC0_cjdC_eEBdx1Xv-3:-OC0a9T28ry2h_nEAFS0:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/57794fd55e50763a5e8eacc1d0cd0b06244c9376/planning/trajectory_optimization/gcs_trajectory_optimization.h#L469)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: this should probably sat AddEdgeConstraint
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 936 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-OBjQUZeENb1NWiyUygU:-OC0aEHc1EzQ5iDzM-7i:b-a5pz0l) ([raw file](https://github.com/RobotLocomotion/drake/blob/87f7f479ed15fd886984a1bfbd83f73b8a7a3272/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L936)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

There are still explicit instantiations of `DoAddEdgeConstraint` below.  Does this comment apply to them?
</blockquote></details>

I thought I had done so throughout. Done for real now :smile:

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22179#-:-OC44uaa5YN79Xtj9KPg:bnfp4nl)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22179)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Pull request merged**
