### PR TITLE
MJCF parser supports mesh defaults and assetdir

### PR DESCRIPTION
**Pull request by RussTedrake**
Mesh defaults can be used to set the scale of the assets globally. "assetdir" is another way to set the "meshdir".

Towards #20444.

+@joemasterjohn for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
Feature pass done, PTAL.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-:-NlRh7Ic7CiBkDaYVX2M:b-7uzwif)* status: 3 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NlRgEtwAuQw0SCilkxI:-NlRgEtwAuQw0SCilkxJ:b-gzl6fy) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ff285496b7b80fc3b3f9c9056da183136f571fa/multibody/parsing/detail_mujoco_parser.cc#L1148)):*
> ```cpp
>     std::string assetdir;
>     if (ParseStringAttribute(node, "assetdir", &assetdir)) {
>       // assetdir sets both meshdir and texturedir.
> ```

Seems like a few lines down below we're still marking `texturedir` as unsupported. Did you mean to add support, or is the comment out of sync?



_Code quote:_
```cpp
      // assetdir sets both meshdir and texturedir.
```
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1377 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NlRgTz1BuOs8hCodUsT:-NlRgTz1BuOs8hCodUsU:bhkpznn) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ff285496b7b80fc3b3f9c9056da183136f571fa/multibody/parsing/detail_mujoco_parser.cc#L1377)):*
> ```cpp
>     }
> 
>     // Parses the assets.
> ```

nit: Should add a dev warning in the comments that the assets now must be parsed *after* defaults so the order of execution of the above for loop and this one should not change.



_Code quote:_
```cpp
    // Parses the assets.
```
___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 587 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NlRfHhT4-DelatPDvks:-NlRfHhT4-DelatPDvkt:b-8fnpf7) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ff285496b7b80fc3b3f9c9056da183136f571fa/multibody/parsing/test/detail_mujoco_parser_test.cc#L587)):*
> ```cpp
>   TestBoxMesh(box_obj_, mesh_asset, compiler);
> }
> ```

nit: It would be useful to have a case that confirms a sane error pops out for an invalid/non-existent path for `meshdir` or `assetdir`.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NlRgEtwAuQw0SCilkxI:-Nn44XT44YO68rnhgtva:b-o6l57q) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ff285496b7b80fc3b3f9c9056da183136f571fa/multibody/parsing/detail_mujoco_parser.cc#L1148)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Seems like a few lines down below we're still marking `texturedir` as unsupported. Did you mean to add support, or is the comment out of sync?
</blockquote></details>

Done. Based on the slack discussion, we decided to NOT support mujoco's explicit texture elements (and rely instead on e.g. the mtl files).  I've clarified the comment.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1377 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NlRgTz1BuOs8hCodUsT:-Nn457_m-RQhzNYE8O0m:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ff285496b7b80fc3b3f9c9056da183136f571fa/multibody/parsing/detail_mujoco_parser.cc#L1377)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Should add a dev warning in the comments that the assets now must be parsed *after* defaults so the order of execution of the above for loop and this one should not change.
</blockquote></details>

Done.
___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 587 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NlRfHhT4-DelatPDvks:-Nn46ZV02vu4DyYBx1El:bu3ayw6) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ff285496b7b80fc3b3f9c9056da183136f571fa/multibody/parsing/test/detail_mujoco_parser_test.cc#L587)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: It would be useful to have a case that confirms a sane error pops out for an invalid/non-existent path for `meshdir` or `assetdir`.
</blockquote></details>

Done.  Added the test.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: feature. +@rpoyner-tri for platform review, please.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-:-Nn7x5WEB19ap8r2sRDn:b4jjfsv)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NlRgEtwAuQw0SCilkxI:-Nn7wlYp23RtbAzpQX0m:b-hhdp2p) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ff285496b7b80fc3b3f9c9056da183136f571fa/multibody/parsing/detail_mujoco_parser.cc#L1148)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done. Based on the slack discussion, we decided to NOT support mujoco's explicit texture elements (and rely instead on e.g. the mtl files).  I've clarified the comment.
</blockquote></details>

Got it, thanks for the clarification.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-:-NnAMucr0h_nYMjtSxFJ:bnfp4nl)* status: 1 unresolved discussion

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 910 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NnAKi5s8Z3KUlIdhDJp:-NnAKi5s8Z3KUlIdhDJq:b-nsfpid) ([raw file](https://github.com/RobotLocomotion/drake/blob/277714a7a89d3e4937b690de9dbf3b49d5f3607f/multibody/parsing/detail_mujoco_parser.cc#L910)):*
> ```cpp
>     }
> 
>     // Parse default mesh.
> ```

minor: consider making this stanza and its two predecessors into a method/subroutine; they only differ by the element's name, and the receiving map object, and contain spam copies of a pretty critical piece of default value inheritance logic.

We've reached the rule of 3, and likely implementation of the next group of unsupported elements will need the same logic.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 910 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NnAKi5s8Z3KUlIdhDJp:-NnH7b5pBbUeENKxHJT0:bwxutid) ([raw file](https://github.com/RobotLocomotion/drake/blob/277714a7a89d3e4937b690de9dbf3b49d5f3607f/multibody/parsing/detail_mujoco_parser.cc#L910)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor: consider making this stanza and its two predecessors into a method/subroutine; they only differ by the element's name, and the receiving map object, and contain spam copies of a pretty critical piece of default value inheritance logic.

We've reached the rule of 3, and likely implementation of the next group of unsupported elements will need the same logic.
</blockquote></details>

Done.  But I'm not sure it's better (it seems a bit less readable to me).

**Comment by rpoyner-tri** [comment]
*[`multibody/parsing/detail_mujoco_parser.cc` line 910 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NnAKi5s8Z3KUlIdhDJp:-NnKGC1f9-Z6BtM5LZeL:bqobayl) ([raw file](https://github.com/RobotLocomotion/drake/blob/277714a7a89d3e4937b690de9dbf3b49d5f3607f/multibody/parsing/detail_mujoco_parser.cc#L910)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  But I'm not sure it's better (it seems a bit less readable to me).
</blockquote></details>

Hm, interesting. Mind if I take a shot at improving readability?

**Comment by RussTedrake** [comment]
that's great.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621)* status: 1 unresolved discussion

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 910 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NnAKi5s8Z3KUlIdhDJp:-NnKM5cd-QxO3Rkm3AVO:bqnsjy) ([raw file](https://github.com/RobotLocomotion/drake/blob/277714a7a89d3e4937b690de9dbf3b49d5f3607f/multibody/parsing/detail_mujoco_parser.cc#L910)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Hm, interesting. Mind if I take a shot at improving readability?
</blockquote></details>

working on a different draft

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 910 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-NnAKi5s8Z3KUlIdhDJp:-NnKR9RWBlkwLqctVsHX:bb71pro) ([raw file](https://github.com/RobotLocomotion/drake/blob/277714a7a89d3e4937b690de9dbf3b49d5f3607f/multibody/parsing/detail_mujoco_parser.cc#L910)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

working on a different draft
</blockquote></details>

PTAL

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
I will let this wait a bit to get a last look from @RussTedrake for `r4`, then I think I can squash and merge.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-:-NnKeNUk8rdssGdfHlPu:bjilnjy)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Looks aok to me.  (to be honest, I don't see it as real improvement, and still think the original loops were more succinct), but I did get the camel case wrong on the lambda.  I'm aok with any of these versions.  Thank you.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-:-NnMWTu4Bt9dHGul_f6O:bsno606)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
Perhaps it's debatable now, but should pay of as we implement the remaining default subnodes (5 or 6 remaining?).

+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20621#-:-NnPOD6H4Ltv8VPSCUSS:bc4bnoh)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn

**Pull request merged**
