### PR TITLE
pydrake: Clarify tests for SolverInterface::Solve

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The prior unit test was pretending an argument-mismatch exception was a "cannot solve" message.  Here instead, we try to slightly more carefully illustrate what a solver back-end in Python should maybe look like.

Amends #12866.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15036)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@seancurtis-tri for platform review since Today's platform reviewer is Jeremy.

Sorry for the delay in reviewing.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15036#-:-M_aRpNfAY8utZBq9kUF:bm77boh)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 1023 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15036#-M_aRcdS4piwOnWiKLI_:-M_aRcdS4piwOnWiKLIa:b-1c7ob6) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d492b4f97cb88cf20e80b99d76c61d4e014dbe/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1023)):*
> ```Python
>         if not self.can_solve:
>             raise Exception("Dummy solver cannot solve")
>         # TODO(jwnimmer-tri) We should be setting the result here, but the
> ```

Should we file a github issue? I thought `MathematicalProgramResult` has the setter in C++, but not in python binding. Maybe we should add the python binding for MPResult setter?

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15036#-:-M_aUtqq4FW2oFmq_f6e:bmxilld)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15036)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 1023 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15036#-M_aRcdS4piwOnWiKLI_:-M_aaNcX6vUNy0KtdGvg:b5uwqka) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d492b4f97cb88cf20e80b99d76c61d4e014dbe/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1023)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should we file a github issue? I thought `MathematicalProgramResult` has the setter in C++, but not in python binding. Maybe we should add the python binding for MPResult setter?
</blockquote></details>

I think at the point when someone articulates the desire to implement a solver in Python, then we can open a feature request issue in Drake to capture that desire.  (I think supporting that would involve more than just binding one more function.)  Prior to someone having such a request, an issue seems like clutter with low value.

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 996 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15036#-M_abj111Gs-JDPYpZOl:-M_abj12DRh1mTmjWTTO:b-y070ur) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d492b4f97cb88cf20e80b99d76c61d4e014dbe/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L996)):*
> ```Python
>     def __init__(self):
>         SolverInterface.__init__(self)
>         self._id = SolverId("dummy")
> ```

I did the ID mnemonics wrong here and it's bugging me, even though it doesn't really matter much.  I'll push a fix in a moment.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15036)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 1023 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15036#-M_aRcdS4piwOnWiKLI_:-M_ae423B-msIVW79YXa:b-dxcbts) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d492b4f97cb88cf20e80b99d76c61d4e014dbe/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1023)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think at the point when someone articulates the desire to implement a solver in Python, then we can open a feature request issue in Drake to capture that desire.  (I think supporting that would involve more than just binding one more function.)  Prior to someone having such a request, an issue seems like clutter with low value.
</blockquote></details>

Makes sense.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15036)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 1023 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15036#-M_aRcdS4piwOnWiKLI_:-M_agnv6E-suXhpVyXN6:bkqin6w) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d492b4f97cb88cf20e80b99d76c61d4e014dbe/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1023)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Makes sense.
</blockquote></details>

FYI In my mind, the most likely use case would be if we found some promising mixed-integer (or something) solver from pypi, and wanted to wrap it for python only.

**Comment by hongkai-dai** [comment]
I think that makes sense. Someone has implemented a python version of mixed-integer optimization with OSQP. https://github.com/oxfordcontrol/miosqp

On the other hand, I plan to add CBC into drake in the near term, which solves MILP in C++.

**Comment by jwnimmer-tri** [comment]
Right.  Broadly, I've come across many Python bindings for the solvers that we already have in C++.  The more complicated and performant solvers tend to be written in C or C++ anyway, in many cases.

**Pull request merged**
