### PR TITLE
Update document

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
To clearly mention that `RgbdCamera` uses `visual` elements while `DepthSensor` uses `collision` elements.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6373)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@liangfok feature review please.
+@jwnimmer-tri platform review please.

cc @RussTedrake

Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6373#-:-KmrITQrhAj4HbjtLMyz:b-v5506l)*

**Comment by RussTedrake** [comment]
thanks kuni.  i've also confirmed that the raycast uses the collision geometry:
https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/rigid_body_tree.cc#L833
(and the collision model gets populated in a complicated way from the collision elements in the rigid body).  

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6373#-:-KmrYW-7fpcQX733xVuv:b24h6fz)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6373#-:-KmrZvtYKbsOX7jMIXtV:bnfp4nl)*

**Comment by RussTedrake** [comment]
cc @seancurtis-tri and @avalenzu .  one small improvement on your changes here might be to avoid mentioning sdf / urdf directly.  the raycast uses the collision model of rigid body tree, which is normally loaded with the collision elements of the file, but technically need not be.  presumably the same is true for the rgb-d?  

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6373#-:-Kmr_2KjA1dxKLiVCmX4:b4esx75)*

**Comment by kunimatsu-tri** [comment]
Thanks @RussTedrake for your looking at it.  Alright, then I will remove URDF and SDF from the docs.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6373#-:-Kmrd0p7Muc1a1TM49Lf:bwg0h64)*

**Comment by kunimatsu-tri** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6373#-:-KmrtXq7m3Pfl1kqqFxF:b-896fix)*

**Comment by kunimatsu-tri** [comment]
-@jwnimmer-tri -@liangfok since this is document only change and I believe LGTM from @RussTedrake fulfills the condition for merge.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6373#-:-Kms1bIp_AUIokQO5gPQ:b1tvj95)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6373#-:-Kms461S8q_CXFjC5G0I:bnfp4nl)*

**Pull request merged**
