### PR TITLE
Add a Drake build cop playbook.

### PR DESCRIPTION
**Pull request by david-german-tri**
+@jamiesnape, +@BetsyMcPhail for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3045)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 125 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZOCbiHzGGZtd1wHt:-KOGZOCcp16anCJf6zbu:-1150622346) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L125)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^^^
> Check either your CI failure notification e-mail list, or the
> `post-submit <https://drake-jenkins.csail.mit.edu/view/Continuous/>`_ build
> ```

post-merge, not post-submit

Also need to check Nightly each morning.

---

*[drake/doc/buildcop.rst, line 137 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZZhGrIctyClQt-Gd:-KOGZZhGrIctyClQt-Ge:500764129) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L137)):*
> ```reStructuredText
> own judgment.
> 
> In almost any build breakage, thehe first information-gathering step is to
> ```

the, not thehe

---

*[drake/doc/buildcop.rst, line 147 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZhrgJ2L_TWpNSYuQ:-KOGZhrgJ2L_TWpNSYuR:-899503216) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L147)):*
> ```reStructuredText
> This can happen for several reasons:
> 
> * The platform or test case only runs post-submit.
> ```

post-merge

---

*[drake/doc/buildcop.rst, line 149 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZjo-37HMP4fy4AC2:-KOGZjo-37HMP4fy4AC3:498885929) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L149)):*
> ```reStructuredText
> * The platform or test case only runs post-submit.
> * A administrator performed an override-merge of the culprit PR,
>   circumventing pre-submit checks.
> ```

pre-merge

---

*[drake/doc/buildcop.rst, line 160 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOG__1WGFBvwomlzutb:-KOG__1WGFBvwomlzutc:-834265371) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L160)):*
> ```reStructuredText
> communicate with the author.
> 
> If the failing build passes on the rollback PR, the odds are good that you have
> ```

Not if the failure was in long-running tests or OS X / MATLAB, etc. Need to manually schedule an experimental build on Jenkins to trigger long-running tests.

---

*[drake/doc/buildcop.rst, line 183 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGagnWmjBwVVoho01A:-KOGagnWmjBwVVoho01B:1863316190) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L183)):*
> ```reStructuredText
> the `drake-ci <https://github.com/RobotLocomotion/drake-ci>`_ repo as well as
> Drake proper. Consider whether those changes are possible culprits.  If you
> believe so, contact the author, and also alert Kitware via GitHub issue. If they
> ```

Ping @RobotLocomotion/kitware, I guess.

---

*[drake/doc/buildcop.rst, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZzSmzZrIUrGn8VH6:-KOGZzSmzZrIUrGn8VH7:1453460130) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L194)):*
> ```reStructuredText
> * Unable to obtain a MATLAB license.
> * Broken connection to a Mac build VM.
> * Broken connection to a Windows build VM.
> ```

agent, not VM (also Windows builds are not virtualized).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 125 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZOCbiHzGGZtd1wHt:-KOGmcNZlog3G_rsYjJ8:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L125)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> post-merge, not post-submit
> 
> Also need to check Nightly each morning.
</details>
Done.

---

*[drake/doc/buildcop.rst, line 137 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZZhGrIctyClQt-Gd:-KOGmelnGnUI5QVX2wRG:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L137)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> the, not thehe
</details>
Done.

---

*[drake/doc/buildcop.rst, line 147 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZhrgJ2L_TWpNSYuQ:-KOGmfmeFBzUDvh9jdOl:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L147)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> post-merge
</details>
Done.

---

*[drake/doc/buildcop.rst, line 149 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZjo-37HMP4fy4AC2:-KOGmkIJi8_8EW3dhBCz:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L149)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> pre-merge
</details>
Done.

---

*[drake/doc/buildcop.rst, line 160 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOG__1WGFBvwomlzutb:-KOGnAeAn4eh28CkaoVG:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L160)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Not if the failure was in long-running tests or OS X / MATLAB, etc. Need to manually schedule an experimental build on Jenkins to trigger long-running tests.
</details>
Done.

---

*[drake/doc/buildcop.rst, line 183 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGagnWmjBwVVoho01A:-KOGnLnkNh6cxUqoDClu:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L183)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Ping @RobotLocomotion/kitware, I guess.
</details>
Done.

---

*[drake/doc/buildcop.rst, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZzSmzZrIUrGn8VH6:-KOGpmDpbWIEqk6K2c8h:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L194)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> agent, not VM (also Windows builds are not virtualized).
</details>
Done.

---

*[drake/doc/buildcop.rst, line 134 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGpoqz7-x-0MFQ5fvJ:-KOGpoqz7-x-0MFQ5fvK:-1841004160) ([raw file](https://github.com/robotlocomotion/drake/blob/f85165553ff0fcaee468085faf76c35adc6e8d42/drake/doc/buildcop.rst#L134)):*
> ```reStructuredText
> category, and therefore require build cop action if they fail:
> 
> * mac-clang-nightly-matlab
> ```

@jamiesnape Anything else you'd put in this list?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 120 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGmp0DsSN8vvWX6Zok:-KOGmp0DsSN8vvWX6Zol:1776763680) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L120)):*
> ```reStructuredText
> Build Cop Playbook
> ------------------
> This section is a quick-reference manual for the oncall build-cop.
> ```

pedantic: "on-call" (multiple instances)

Also, "build cop"?

---

*[drake/doc/buildcop.rst, line 148 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGnMoU3DW0_XohWvSj:-KOGnMoU3DW0_XohWvSk:1350515971) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L148)):*
> ```reStructuredText
> 
> * The platform or test case only runs post-submit.
> * A administrator performed an override-merge of the culprit PR,
> ```

pedantic: "An administrator"

---

*[drake/doc/buildcop.rst, line 181 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGntAfhw4IqQSXJpg6:-KOGntAfhw4IqQSXJpg7:-998062228) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L181)):*
> ```reStructuredText
> Sometimes people merge changes to the Drake CI scripts that result in spurious
> CI failures. The list of commits in Jenkins for each continuous build includes
> the `drake-ci <https://github.com/RobotLocomotion/drake-ci>`_ repo as well as
> ```

*extremely* pedantic: I'd probably say "repository" rather than abbreviate, but that may be just me...

---

*[drake/doc/buildcop.rst, line 185 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGoDjauHZB5u-8Tcgn:-KOGoDjauHZB5u-8Tcgo:1603919589) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L185)):*
> ```reStructuredText
> believe so, contact the author, and also alert Kitware via GitHub issue. If they
> are not responsive, revert the commit yourself and see what happens on the next
> continuous build.  (CI script changes cannot be tested before merge.)
> ```

pedantic: "fully tested"? Hopefully anyone submitting a PR to CI has used the `run_local` scripts on at least one platform. "cannot be tested" sounds a little like someone just made changes and crossed their fingers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZzSmzZrIUrGn8VH6:-KOGs6H6D40zxrc-JtEc:-1035156189) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L194)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Done.
</details>
Mac is also an agent.

---

*[drake/doc/buildcop.rst, line 134 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGpoqz7-x-0MFQ5fvJ:-KOGr8-0c9B9MjkFcyCv:-887360991) ([raw file](https://github.com/robotlocomotion/drake/blob/f85165553ff0fcaee468085faf76c35adc6e8d42/drake/doc/buildcop.rst#L134)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> @jamiesnape Anything else you'd put in this list?
</details>
Looks like everything (other than ones that have a corresponding continuous build, which would imply a preceding continuous build failed or a test was flaky).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-:-KOGsQ4NipGHMr5MjYLb:1417088721)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/buildcop.rst, line 120 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGmp0DsSN8vvWX6Zok:-KOGvVplE7oUa91Qgemf:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L120)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> pedantic: "on-call" (multiple instances)
> 
> Also, "build cop"?
</details>
Done.

---

*[drake/doc/buildcop.rst, line 148 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGnMoU3DW0_XohWvSj:-KOGv_pguZIdMdk8HAnO:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L148)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> pedantic: "An administrator"
</details>
Done.

---

*[drake/doc/buildcop.rst, line 181 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGntAfhw4IqQSXJpg6:-KOGvi46debeox_0FG6h:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L181)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> *extremely* pedantic: I'd probably say "repository" rather than abbreviate, but that may be just me...
</details>
Done.

---

*[drake/doc/buildcop.rst, line 185 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGoDjauHZB5u-8Tcgn:-KOGwLo2AzmBbp_wq7K5:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L185)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> pedantic: "fully tested"? Hopefully anyone submitting a PR to CI has used the `run_local` scripts on at least one platform. "cannot be tested" sounds a little like someone just made changes and crossed their fingers.
</details>
Done.

---

*[drake/doc/buildcop.rst, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGZzSmzZrIUrGn8VH6:-KOGwXpmiOZYbgyaZyQ8:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/edc34c44c236b3f5f90d0d034f49cbab06855422/drake/doc/buildcop.rst#L194)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Mac is also an agent.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for platform review and merge

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-:-KOGwdg9oK4gPzYYD1mI:494780586)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 201 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGznauyxwOQ6t1H6-S:-KOGznauyxwOQ6t1H6-T:838088544) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L201)):*
> ```reStructuredText
> 
> If you believe a CI script change is the culprit, contact the author, and also
> alert ``@RobotLocomotion/kitware`` via GitHub issue. If they are not responsive,
> ```

For me at least, I'm not sure that `@RobotLocomotion/kitware` does anything in a github comment -- it doesn't autocomplete.  Are we sure it works?

---

*[drake/doc/buildcop.rst, line 229 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGzx8FrLZVm7HvY-CO:-KOGzx8GADcdy4lbpKSv:1398514130) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L229)):*
> ```reStructuredText
> 
> Attempt to figure out which piece of infrastructure collapsed. If it's under
> our control, alert Kitware via GitHub issue. If it's under a vendor's control,
> ```

"alert Kitware via GitHub issue" -- is merely filing an issue enough (someone is watching the firehouse), or is there specific tags, beetlejuices, or assignments that buildcop should be doing?

---

*[drake/doc/buildcop.rst, line 230 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH-7ZdckvPU02iQ36G:-KOH-7ZdckvPU02iQ36H:-809855472) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L230)):*
> ```reStructuredText
> Attempt to figure out which piece of infrastructure collapsed. If it's under
> our control, alert Kitware via GitHub issue. If it's under a vendor's control,
> spread the news as widely as you can and simply wait it out.
> ```

Missing newline at end of file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by liangfok** [comment]
I marked all my comments "BTW" to not excessively stall this PR.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 122 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH0B83FD4FZTCe2B95:-KOH0B83FD4FZTCe2B96:1157658740) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L122)):*
> ```reStructuredText
> This section is a quick-reference manual for the on-call build cop.
> 
> Monitor the Build
> ```

BTW consider adding named anchors for these subsections as well. For example:

```
.. _build_cop_playbook_monitor_the_build:
```

---

*[drake/doc/buildcop.rst, line 172 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH0wEl9mtDOERS060g:-KOH0wEl9mtDOERS060h:1896161486) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L172)):*
> ```reStructuredText
> PRs. Try to rule out some of those PRs by comparing their contents to the
> specifics of the failure. For any PRs you cannot rule out, create a rollback
> by clicking "Revert" in the GitHub UI. Use the template message above to
> ```

BTW consider making "template message above" a reference link:

```
:ref:`template message above <revert_template>`
```

---

*[drake/doc/buildcop.rst, line 175 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH15DSKqSsYowWiUXI:-KOH15DSKqSsYowWiUXJ:1822921681) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L175)):*
> ```reStructuredText
> communicate with the author.
> 
> Manually schedule the failing build as an experimental build on the rollback
> ```

BTW consider making "Manually schedule" a link:

```
:ref:`Manually schedule <run_specific_build>`
```

---

*[drake/doc/buildcop.rst, line 190 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH1awPH5MNOJh_nh5_:-KOH1awPH5MNOJh_nh5a:773556997) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L190)):*
> ```reStructuredText
> test.  Look through earlier commits one-by-one for plausible culprits.
> After you identify one, create a rollback by clicking "Revert" in the
> GitHub UI. Use the template message above to communicate with the author, and
> ```

BTW, consider making "template message above" a link:

```
:ref:`template message above <revert_template>`
```

---

*[drake/doc/buildcop.rst, line 219 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH1wg_gYeJwpKg0gD1:-KOH1wg_gYeJwpKg0gD2:1976883698) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L219)):*
> ```reStructuredText
> definitely looking at an infrastructure flake, and no further action is
> required. If you believe the rate of a particular infrastructure flake has
> increased, alert Kitware via GitHub issue.
> ```

BTW consider rewording "via Github issue" to be "by submitting a Github issue"

---

*[drake/doc/buildcop.rst, line 228 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH2KJ53U6neqcl3DDx:-KOH2KJ6JEGtqN3f4hrU:-2000538946) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L228)):*
> ```reStructuredText
> will turn red and stay red.
> 
> Attempt to figure out which piece of infrastructure collapsed. If it's under
> ```

BTW consider changing "piece" to be "piece(s)"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-:-KOH2U1aI6QelxT-nEHY:-2125643140)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 201 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGznauyxwOQ6t1H6-S:-KOH1nP40c47z0z02BYX:-1490375927) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L201)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> For me at least, I'm not sure that `@RobotLocomotion/kitware` does anything in a github comment -- it doesn't autocomplete.  Are we sure it works?
</details>
I guess you do not have permissions to see the group. It would work if you did, so I guess we need another solution, see also below.

---

*[drake/doc/buildcop.rst, line 229 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGzx8FrLZVm7HvY-CO:-KOH277oNFvcbxe9KWQc:-116641163) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L229)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> "alert Kitware via GitHub issue" -- is merely filing an issue enough (someone is watching the firehouse), or is there specific tags, beetlejuices, or assignments that buildcop should be doing?
</details>
Not really and tags do not trigger notifications.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 172 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH0wEl9mtDOERS060g:-KOH6ysOCkdU1QNOCGuz:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L172)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW consider making "template message above" a reference link:
> 
> ```
> :ref:`template message above <revert_template>`
> ```
</details>
Done.

---

*[drake/doc/buildcop.rst, line 175 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH15DSKqSsYowWiUXI:-KOH7FfbuZeHPk_AmMD1:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L175)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW consider making "Manually schedule" a link:
> 
> ```
> :ref:`Manually schedule <run_specific_build>`
> ```
</details>
Done.

---

*[drake/doc/buildcop.rst, line 190 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH1awPH5MNOJh_nh5_:-KOH77A3r_nML8HErP9h:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L190)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider making "template message above" a link:
> 
> ```
> :ref:`template message above <revert_template>`
> ```
</details>
Done.

---

*[drake/doc/buildcop.rst, line 201 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGznauyxwOQ6t1H6-S:-KOH7vXcraseyIuGJHf-:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L201)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> I guess you do not have permissions to see the group. It would work if you did, so I guess we need another solution, see also below.
</details>
Done.

---

*[drake/doc/buildcop.rst, line 219 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH1wg_gYeJwpKg0gD1:-KOH7uW3_TYRAKUZUAyX:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L219)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW consider rewording "via Github issue" to be "by submitting a Github issue"
</details>
Done.

---

*[drake/doc/buildcop.rst, line 228 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH2KJ53U6neqcl3DDx:-KOH7YsRlEeUa0Epz3KQ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L228)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW consider changing "piece" to be "piece(s)"
</details>
Done.

---

*[drake/doc/buildcop.rst, line 229 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOGzx8FrLZVm7HvY-CO:-KOH7tTavYQ9ix-XJRyl:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L229)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Not really and tags do not trigger notifications.
</details>
Done.

---

*[drake/doc/buildcop.rst, line 230 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOH-7ZdckvPU02iQ36G:-KOH7Zxuz__qdpur1EDq:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d731161b0b482762b63927146158367c9a5938b7/drake/doc/buildcop.rst#L230)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing newline at end of file.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-:-KOH8KSVZWqeNj3KWbnU:1417088721)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 231 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOHM-xA-iKH9eXlPamK:-KOHM-xBAKiNO4HitobS:-448897190) ([raw file](https://github.com/robotlocomotion/drake/blob/41acd5c25da4dbdfb3f1f5c8b26723a0812f7e01/drake/doc/buildcop.rst#L231)):*
> ```reStructuredText
> Attempt to figure out what infrastructure collapsed. If it's under our control,
> alert Kitware by assigning a GitHub issue to both @BetsyMcPhail and @jamiesnape.
> If it's under a vendor's control, spread the news as widely as you can and simply
> ```

BTW Line too long.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-:-KOHM4qw9dDcupOx4V6a:1417088721)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 231 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-KOHM-xA-iKH9eXlPamK:-KOHNQe41e0JVwjaP7Sb:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/41acd5c25da4dbdfb3f1f5c8b26723a0812f7e01/drake/doc/buildcop.rst#L231)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Line too long.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by david-german-tri** [comment]
@jamiesnape @BetsyMcPhail I'll wait to merge until at least one of you confirms that putting your names in this doc directly is an acceptable interim solution.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-:-KOHd625gcdQOWPb7gHt:-330004050)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3045#-:-KOLx8EyU6HogqynFU_7:1417088721)*

**Pull request merged**
