### PR TITLE
[workspace] Temporarily disable OpenUSD testing

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends https://github.com/RobotLocomotion/drake/pull/20923.

[linux-jammy-unprovisioned-gcc-bazel-nightly-everything-release](https://drake-jenkins.csail.mit.edu/view/Production/job/linux-jammy-unprovisioned-gcc-bazel-nightly-everything-release/)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20994)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please

**Review by BetsyMcPhail — COMMENTED** [review]
+@ggould-tri for both reviews please

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20994#-:-Nr6L7Pd44UcJp340WP5:b-286903)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20994#-:-Nr6NvTl-fwYeCoUcO4s:bnfp4nl)* status: 1 unresolved discussion

___
*[`tools/workspace/openusd_internal/BUILD.bazel` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20994#-Nr6NktkE2WsS3pVLJ6Z:-Nr6NktkE2WsS3pVLJ6_:b-4sbxrc) ([raw file](https://github.com/RobotLocomotion/drake/blob/c6dce3730f4e5aafd48ce698da6695db8970c4fb/tools/workspace/openusd_internal/BUILD.bazel#L32)):*
> ```Starlark
>     args = ["--help"],
>     tags = [
>         # TODO(jwnimmer-tri) Re-enable this once we fix Boost problems.
> ```

minor:  I don't know what "Boost problems" this means; should this be TODO to an issue or is this something that's going to be resolved very quickly and so there's no chance of losing context?



_Code quote:_
```Starlark
Boost problems
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20994)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

___
*[`tools/workspace/openusd_internal/BUILD.bazel` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20994#-Nr6NktkE2WsS3pVLJ6Z:-Nr6_Rf31ceDKTupcL6A:brs83t6) ([raw file](https://github.com/RobotLocomotion/drake/blob/c6dce3730f4e5aafd48ce698da6695db8970c4fb/tools/workspace/openusd_internal/BUILD.bazel#L32)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  I don't know what "Boost problems" this means; should this be TODO to an issue or is this something that's going to be resolved very quickly and so there's no chance of losing context?
</blockquote></details>

I don't anticipate any meaningful confusion or loss.

**Pull request merged**
