### PR TITLE
Revert "TorqueFreeCylinderIntegrateFixedStepRungeKutta2"

### PR DESCRIPTION
**Pull request by liangfok**
Dear @mitiguy,

The on-call build cop, @liangfok, believes that your PR #5055 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-clang-nightly-ros-debug/241/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-clang-nightly-ros-debug/240/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-gcc-nightly-ros-debug/240/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-gcc-nightly-ros-debug/241/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5611)

### CODE REVIEW

**Comment by sherm1** [comment]
Do we need to reduce the run time for this test?

**Comment by SeanCurtis-TRI** [comment]
Can we fix forward this by increasing the test size?

**Comment by liangfok** [comment]
Hopefully this revert can be avoided by increasing the test size: #5612.

Skimming through `drake/multibody/benchmarks/cylinder_torque_free_analytical_solution/test/cylinder_torque_free_analytical_solution.cc`, it was not obvious to me how to decrease its run time. Maybe it can be done by decreasing the number of initial normalized quaternions?

**Comment by liangfok** [comment]
This revert PR was avoided by #5612.

**Pull request closed without merging**
