### PR TITLE
MathematicalProgram::NewSosPolynomial takes degree=0

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16983)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16983#-:-N-pWFzE7ydeYX7k7RGL:b4xbtza)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16983)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @AlexandreAmice and @hongkai-dai)

___
*[solvers/test/mathematical_program_test.cc, line 3326 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16983#-N-xAbFC9lcvXaiqZ_33:-N-xAbFC9lcvXaiqZ_34:b-7m67c6) ([raw file](https://github.com/robotlocomotion/drake/blob/924ec63914119d7174de88c45c66e439f648f926/solvers/test/mathematical_program_test.cc#L3326)):*
> ```cpp
>                           MathematicalProgram::NonnegativePolynomial::kSdsos,
>                           MathematicalProgram::NonnegativePolynomial::kDsos}) {
>     solvers::MathematicalProgram prog;
> ```

Is there a way for the compiler to raise a warning if this doesn't go through all the Sos Polynomial types? Just in case we add any in the future.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16983)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @AlexandreAmice)

___
*[solvers/test/mathematical_program_test.cc, line 3326 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16983#-N-xAbFC9lcvXaiqZ_33:-N-xQ8py6ZtTBKppb8m4:b93aqyu) ([raw file](https://github.com/robotlocomotion/drake/blob/924ec63914119d7174de88c45c66e439f648f926/solvers/test/mathematical_program_test.cc#L3326)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Is there a way for the compiler to raise a warning if this doesn't go through all the Sos Polynomial types? Just in case we add any in the future.
</blockquote></details>

I don't know a good solution to enumerate all the enum class here. I think mostly we will rely on the developer to make sure all the cases are covered.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16983#-:-N01urcd8FUSoU71eg1j:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16983#-:-N01yIZc9pHnLNFNI9zt:b8asji7)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16983)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),AlexandreAmice

___
*[solvers/test/mathematical_program_test.cc, line 3330 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16983#-N02DFlO8AQKNcYbYY07:-N02IvVoEms9_EOaqOVK:bunodv8) ([raw file](https://github.com/robotlocomotion/drake/blob/924ec63914119d7174de88c45c66e439f648f926/solvers/test/mathematical_program_test.cc#L3330)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW you could use structured binding instead of std::tie().

```
     solvers::MathematicalProgram prog;
     const auto x = prog.NewIndeterminates<2>();
-    symbolic::Polynomial p;
-    MatrixXDecisionVariable gram;
-    std::tie(p, gram) = prog.NewSosPolynomial(symbolic::Variables(x), 0, type);
+    const auto& [p, gram] =
+        prog.NewSosPolynomial(symbolic::Variables(x), 0, type);
     EXPECT_EQ(prog.bounding_box_constraints().size(), 1u);

```
No obligation, though.
</blockquote></details>

Ah I missed this comment. I will fix it in my next PR.

**Pull request merged**
