### PR TITLE
Switch to using the system version of libccd

### PR DESCRIPTION
**Pull request by clalancette**
This PR splits out the libccd system changes from #7347 into a separate pull request.  The changes are larger than might be expected because the libccd packages on both Ubuntu 16.04 and macOS homebrew do *not* contains a cmake configuration file.  Thus, this PR also ends up adding functionality to the `pkg.config.bzl` module so that it can properly generate cmake files (through CPS) when requested.  Tested against https://github.com/RobotLocomotion/drake-shambhala/tree/master/drake_cmake_installed on both Linux and macOS.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7371)

### CODE REVIEW

**Comment by jamiesnape** [comment]
We do have a `pc2cps` tool. It needs some improvement, though.

**Comment by clalancette** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by clalancette** [comment]
> We do have a pc2cps tool. It needs some improvement, though.

Right.  The way I've done it here is kind of nice, I think.  It is less efficient than directly parsing the `.pc` file, but it is using the "standard" pkg-config way to grab a bunch of variables, and seems to work on both Linux and macOS.

On a side note, the reason most of the Jenkins builds failed is because they are missing the `libccd-dev` package.  I've done a docker build locally and determined that this PR does indeed contain the correct things to get it working.  I just asked the drake-jenkins-bot to build the unprovisioned versions, but I'm not sure if I have permissions or that is going to work.

**Comment by jamiesnape** [comment]
> Right. The way I've done it here is kind of nice, I think. It is less efficient than directly parsing the .pc file, but it is using the "standard" pkg-config way to grab a bunch of variables, and seems to work on both Linux and macOS.

Not disagreeing.

> On a side note, the reason most of the Jenkins builds failed is because they are missing the libccd-dev package. I've done a docker build locally and determined that this PR does indeed contain the correct things to get it working. I just asked the drake-jenkins-bot to build the unprovisioned versions, but I'm not sure if I have permissions or that is going to work.

Can you split the install_prereqs changes into a separate PR and then ping @BetsyMcPhail to update the Mac and Xenial images?

**Comment by clalancette** [comment]
> Can you split the install_prereqs changes into a separate PR and then ping @BetsyMcPhail to update the Mac and Xenial images?

Done: #7376

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please.

**Comment by jamiesnape** [comment]
Looks like there are lint issues.

**Comment by avalenzu** [comment]
Sorry to be late to the party, but is switching to system libccd _absolutely_ necessary? This will make upstreaming bug-fixes much harder. I'm guessing it is necessary (since otherwise you probably wouldn't be doing it), but I wanted to speak up here before it's a done deal.

**Comment by clalancette** [comment]
> Sorry to be late to the party, but is switching to system libccd absolutely necessary? This will make upstreaming bug-fixes much harder (I have one at this point). I'm guessing it is necessary (since otherwise you probably wouldn't be doing it), but I wanted to speak up here before it's a done deal.

My understanding is that it is required for a program to link against both drake and ROS, but I'm going to defer to @stonier, @nuclearsandwich, and @j-rivero on this one.  I'm merely the messenger :).

**Comment by stonier** [comment]
Talked to @avenlenzu. Given that we have critical patches going upstream and in our fork that ensure contact simulation is working, we need this development branch. i.e. fallback to system is not an option.

To make sure we don't conflict (and it is a common library in robotics development), then we'll upstream and modify our fork to be statically linked with privatised headers and hidden symbols like we're doing with libfcl. This shouldn't be too hard - it's a relatively simple library.

**Comment by stonier** [comment]
Closing this, expect a new PR to come in with the aforementioned approach.

**Comment by jamiesnape** [comment]
(don't forget to rollback the changes to `install_prereqs.sh`)

**Comment by stonier** [comment]
Good point, thanks.

**Comment by clalancette** [comment]
Done in: https://github.com/RobotLocomotion/drake/pull/7398

**Pull request closed without merging**
