### PR TITLE
Revert "Added Maliput's RNDF implementation Loader class. (#7107)"

### PR DESCRIPTION
**Pull request by m-chaturvedi**
This reverts commit dac68810961daef59a87335d319717df59d83bfa.
Dear @hidmic,

The on-call build cop, @m-chaturvedi, believes that your PR 7107 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind/150/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind-everything/149/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind-snopt/71/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7179)

### CODE REVIEW

**Comment by hidmic** [comment]
@m-chaturvedi it seems that not defining a stream operator for a struct I use to parameterize tests is the root cause. Gtest is attempting to print it in binary form and that triggers Valgrind complaints. 

How should we proceed? Do you want me to PR a fix or to PR the whole thing fixed again?

**Comment by m-chaturvedi** [comment]
PR'ing a fix should be fine, if you think it would be a quick one.

**Comment by hidmic** [comment]
@m-chaturvedi 11 additional lines, mostly comments explaining the need for this overload. I'll open a PR.

**Comment by liangfok** [comment]
#7180 was merged and fix-forwards this issue.

**Pull request closed without merging**
