### PR TITLE
Enable autobrief in doxygen

### PR DESCRIPTION
**Pull request by sherm1**
Per discussion in issue #2051, this PR enables `JAVADOC_AUTOBRIEF` in the Drake Doxyfiles for C++ and Matlab.

What this means is that the first sentence of every doxygen comment will automatically be used as though it were preceded by `@brief` and followed by a blank line. This provides a one-line brief for every class and method that has even a short doxygen comment.

Doxygen considers a sentence to end at the first period -- use `\.` if you want a period included in the brief or want to have a multi-sentence brief. An explicit `@brief` will be harmlessly ignored, but those can be removed as code is updated.

Possible source of trouble: explicit `@brief`s that were previously multi-sentence will be reduced to just their first sentence if no `\.` is used, although the rest of the brief will still appear in the `More...` section.

Reviews, please:
Feature: @liangfok 
Platform: @jwnimmer-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2359) &emsp; Multiple assignees:&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri platform.

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> #### Enable autobrief in doxygen
> 
> Per discussion in issue #2051, this PR enables `JAVADOC_AUTOBRIEF` in the Drake Doxyfiles for C++ and Matlab.
> 
> 
> 
> What this means is that the first sentence of every doxygen comment will automatically be used as though it were preceded by `@brief` and followed by a blank line. This provides a one-line brief for every class and method that has even a short doxygen comment.
> 
> 
> 
> Doxygen considers a sentence to end at the first period -- use `\.` if you want a period included in the brief or want to have a multi-sentence brief. An explicit `@brief` will be harmlessly ignored, but those can be removed as code is updated.
> 
> 
> 
> Possible source of trouble: explicit `@brief`s that were previously multi-sentence will be reduced to just their first sentence if no `\.` is used, although the rest of the brief will still appear in the `More...` section.
> 
> 
> 
> Reviews, please:
> 
> Feature: @liangfok 
> 
> Platform: @jwnimmer-tri
> 
> 
> </details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2359#-:-KHtGUOiEKsoULDQexdX:1088834024)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@jwnimmer-tri platform.</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2359#-:-KHtHaIxL0cSz4W7HwBN:1417088721)*

**Comment by liangfok** [comment]
+@liangfok feature. Sorry I did not see this PR being assigned to me until now. Still review it shortly.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> :lgtm:</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2359#-:-KHttbrejRW-VdExrshl:-1198760716)*

**Comment by liangfok** [comment]
Quick question in case someone knows and can respond before I actually test this on my local machine: What happens if the first sentence of a comment block spans multiple lines? Will `AUTOBRIEF` truncate it?

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@liangfok feature. Sorry I did not see this PR being assigned to me until now. Still review it shortly.</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2359#-:-KHtvl0M4T6SrPI81LIJ:-2102573837)*

**Comment by sherm1** [comment]
@liangfok: AUTOBRIEF doesn't pay attention to line breaks, it just looks for a period. So multiline briefs work fine, but multi-sentence ones (or sentences with abbreviations like `Ph.D.`) need to escape the period with a backslash.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Quick question in case someone knows and can respond before I actually test this on my local machine: What happens if the first sentence of a comment block spans multiple lines? Will `AUTOBRIEF` truncate it?</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2359#-:-KHu82hlblcS_ammPVrn:-692377529)*

**Comment by liangfok** [comment]
@sherm1: Thanks! I actually just verified your statement on my local machine. Thus, this PR :lgtm_strong: .

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> @liangfok: AUTOBRIEF doesn't pay attention to line breaks, it just looks for a period. So multiline briefs work fine, but multi-sentence ones (or sentences with abbreviations like `Ph.D.`) need to escape the period with a backslash.</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2359#-:-KHu96LLjrAv2T7qQVZv:-617963128)*

**Comment by sherm1** [comment]
Merging although build hasn't completed yet since this doesn't affect the build.

**Pull request merged**
