### PR TITLE
Add drake_cc_package_library and library_lint

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This should be substantially easier to maintain correct lists, and document for authors the purpose of the package-level library without repeating identical comments everywhere.

This is also a step along the way to #6464, where libdrake will depend on just these package-summary libraries, instead of listing out each individual component.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8582)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for design review (or as much code review as you wish also), please.
+@EricCousineau-TRI for feature review, please (waiting until Monday review day is fine).

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything  please

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/skylark/drake_cc.bzl, line 346 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-LAExKZY7HSILm58kJjD:-LAExKZY7HSILm58kJjE:b-4q21o7) ([raw file](https://github.com/robotlocomotion/drake/blob/c30a3299f5246d68fe15c9c232d219e442665f07/tools/skylark/drake_cc.bzl#L346)):*
> ```Python
> 
> def _check_package_library_name(name):
>     # Assert that :name is the default libarary for native.package_name().
> ```

BTW Spelling `libarary` should be `library`

---

*[tools/skylark/drake_cc.bzl, line 360 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-LAExSyU7oTwXTV2kaq1:-LAExSyU7oTwXTV2kaq2:b-qdeoza) ([raw file](https://github.com/robotlocomotion/drake/blob/c30a3299f5246d68fe15c9c232d219e442665f07/tools/skylark/drake_cc.bzl#L360)):*
> ```Python
>     name matches the current package and whose dependencies are (usually) all
>     of the other drake_cc_library targets in the current package.  In short, a
>     library named //foo/bar (short for //foo/bar:bar) that convenient provides
> ```

BTW Grammar "convenient" should be "conveniently"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-:-LAExndOBNcfkfhXaHkl:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@jamiesnape any thoughts?

+@sammy-tri for platform review per schedule (tomorrow), please.
-(status: do not merge) 

---

Review status: 39 of 41 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-:-LAFGowP3aDK42y7lCi0:bh9ojjd)*

**Comment by sammy-tri** [comment]
:lgtm:  modulo minor typo issue.  I can't say I love the `everything` idiom for when you only have a single `drake_cc_library` which was already well formed, but it seems worth it for the lint check.

---

Reviewed 38 of 41 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/api/BUILD.bazel, line 4 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-LAFKQnY35p6q85EsZp5:-LAFKQnY35p6q85EsZp6:b34yu7f) ([raw file](https://github.com/robotlocomotion/drake/blob/a767d4e8e1bdc199238ac5700bf5d6584d860a83/automotive/maliput/api/BUILD.bazel#L4)):*
> ```Python
> 
> load(
>     "@drake//tools/skylark:drake_cc.bzl",
> ```

BTW Why do we respell this `load()` to use `@drake//tools` but not the one below for `//tools/lint:lint.bzl"?

---

*[tools/lint/library_lint.bzl, line 15 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-LAFJ0w6BKqco8RqS4Tl:-LAFJ0w6BKqco8RqS4Tm:b-a0rj4u) ([raw file](https://github.com/robotlocomotion/drake/blob/a767d4e8e1bdc199238ac5700bf5d6584d860a83/tools/lint/library_lint.bzl#L15)):*
> ```Python
> 
>     Note that //examples/... packages are excluded from some checks, because
>     then should generally not use drake_cc_package_library.
> ```

typo "then" instead of "they"?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-:-LAFMNTz5Aew3Sdax19b:bms77i4)*

**Comment by jwnimmer-tri** [comment]
Review status: 40 of 41 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-LAFQ5RS1ROSAVQlDeAi:-LAFQ5RS1ROSAVQlDeAj:b-r4nu5w) (no related file):*
> I can't say I love the everything idiom for when you only have a single drake_cc_library which was already well formed, but it seems worth it for the lint check.

FYI @sammy-tri In an earlier local draft of this change, I actually had a way to bless the existing cc_library into a cc_package_library without creating an `:everything` name.  However, I felt like the UX of keeping the two ideas separate like I have it here now would be easier for developers to understand in the future.  (Build system macros should be relatively more KISS than regular code, I think.)

---

*[automotive/maliput/api/BUILD.bazel, line 4 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-LAFKQnY35p6q85EsZp5:-LAFOxHO46ass_ZEK62F:b-corphw) ([raw file](https://github.com/robotlocomotion/drake/blob/a767d4e8e1bdc199238ac5700bf5d6584d860a83/automotive/maliput/api/BUILD.bazel#L4)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW Why do we respell this `load()` to use `@drake//tools` but not the one below for `//tools/lint:lint.bzl"?
</blockquote></details>

The `//tools:drake.bzl` file is deprecated, and it does not offer a drake_cc_package_library forwarding macro.  So we need to switch to using the bzl files that its forwarding to, which is `//tools/skylark:drake_cc_bzl`.  That file uses the `@drake//` spelling to forward into, because unfortunately, due to bazelbuild/bazel#3115 we would get two different and incompatible providers using `@drake//tools` vs `//tools`, so we have to carefully use `@drake//` everywhere.

I don't change `lint.bzl` load path because there is no need in this PR, and it seems like something I should do globally if I do it.

---

*[tools/lint/library_lint.bzl, line 15 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-LAFJ0w6BKqco8RqS4Tl:-LAFOrtO4-Qfgg-CL6yr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a767d4e8e1bdc199238ac5700bf5d6584d860a83/tools/lint/library_lint.bzl#L15)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

typo "then" instead of "they"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 41 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8582#-:-LAGDEja9RHt6CL86197:bnfp4nl)*

**Pull request merged**
