### PR TITLE
Fix "dyld: Symbol not found" errors in OSX+bazel build

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4952)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , both reviews please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4952#-:-Kbb7On7hMX7nouoS1VY:b-mbs47t)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/BUILD, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4952#-KbbBa9I4kFx_7KWd6IJ:-KbbBa9Juct56CI_Wb1K:bnjkql1) ([raw file](https://github.com/robotlocomotion/drake/blob/e044293839cac293cdbbab412b4074407d9cef6d/drake/examples/Pendulum/BUILD#L21)):*
> ```Python
>     srcs = ["pendulum_plant.cc"],
>     hdrs = ["pendulum_plant.h"],
>     deps = [
> ```

I was expecting the linkstatic=1 here (and ...swing_up), not in the cc_googletest.  Does that fix it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4952)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/BUILD, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4952#-KbbBa9I4kFx_7KWd6IJ:-KbbEkko2qRbhTVyPrse:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e044293839cac293cdbbab412b4074407d9cef6d/drake/examples/Pendulum/BUILD#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was expecting the linkstatic=1 here (and ...swing_up), not in the cc_googletest.  Does that fix it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4952)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4952#-:-KbbFp4Kkfq3pcKqOqVh:bnfp4nl)*

**Comment by david-german-tri** [comment]
This is troubling.  Possibly related: https://github.com/bazelbuild/bazel/issues/507#issuecomment-275128269

**Comment by soonho-tri** [comment]
@david-german-tri , do you think it's better revert this commit and disable two pendulum tests on OSX?

**Comment by david-german-tri** [comment]
No, I think this PR is OK, I'm just troubled that I don't understand what's going on.

**Pull request merged**
