### PR TITLE
add a function to turn eigen sparse matrix to triplets

### PR DESCRIPTION
**Pull request by hongkai-dai**
This is useful in mathematical optimization, when we want to use the non-zero entries.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3774)

### CODE REVIEW

**Comment by tkoolen** [comment]
Isn't this essentially what [`makeCompressed`](https://eigen.tuxfamily.org/dox-devel/classEigen_1_1SparseMatrix.html#ad9b10bd4b327e69bac9a95c885a633f3) does?

**Comment by tkoolen** [comment]
(Perhaps a better reference: https://eigen.tuxfamily.org/dox-devel/group__TutorialSparse.html, search for `makeCompressed`)

**Comment by hongkai-dai** [comment]
@tkoolen, thanks for the pointer, but I do not think `makeCompressed` gives the desired result. I want a function to return the rows, the columns and the values of the non-zero entries in a sparse matrix. For example, for a matrix
```
0	3	0	0	0
22	0	0	0	17
7	5	0	1	0
0	0	0	0	0
0	0	14	0	8
```
I want to return
```
row = [ 1 2 0 2 4 2 1 4]
col = [ 0 0 1 1 2 3 4 4]
val = [22 7 3 5 14 1 17 8]
```
such that `matrix(row(i), col(i)) = val(i)`. Notice that we want the length of `row`, `col` and `val` to be the same.

I believe `Eigen::SparseMatrix` uses a different approach to store the non-zero entries, It uses the CRS format (https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_.28CSR.2C_CRS_or_Yale_format.29).  So for the matrix above, it stores the matrix as
```
Values      :	22	7	_	3	5	14	_	_	1	_	17	8
InnerIndices:	1	2	_	0	2	4	_	_	2	_	1	4
OuterStarts:	0	3	5	8	10	12
InnerNNZs:	2	2	1	1	2
```
Notice that the length of `OuterStarts` can be different from `Values` and `InnerIndices`. `_` means a space reserved in the storage for future insertion.

`makeCompressed` just eliminates these space `_` in the internal storage, and `InnerNNZs` becomes redundant. But it still uses the CRS format. So I still need a function to return the rows, column and values of the non-zero entries.

**Comment by hongkai-dai** [comment]
+@tkoolen for feature review. +@sammy-tri for platform review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-:-KTtj-B0W8GDVAT_l7w8:bp31wvv)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-:-KTtn3iNFO9JuX4qzg_R:bnfp4nl)*

**Comment by tkoolen** [comment]
Sorry to nag, but is that really necessary? It sounds to me like you're basically creating a new, makeshift sparse matrix type. Shouldn't the methods that operate on sparse matrices just be made to work with `Eigen::SparseMatrix` directly, using the `InnerIterator` pattern you used in this pull request? Can you give me an example where this is needed?

**Comment by hongkai-dai** [comment]
@tkoolen , this is like a utility function. One case is in the gurobi solver, that when we add the constraints or quadratic costs, the solver wants the row indices, the column indices and the values of both the linear matrices and quadratic matrices. 

This function is supposed to be like `[row, col] = find(A)` in matlab. We use this `find` function a lot in MATLAB programming

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-:-KTuEKCR83LiH6RB4T0n:b-9ttgxr)*

**Comment by tkoolen** [comment]
Alright, OK. Added some comments.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/math/eigen_sparse_triplet.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuH51BaTBD-iEJIYHw:-KTuH51CdowD1roB25_P:b9oonzo) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L10)):*
> ```objc
> namespace math {
> /**
>  * For a sparse matrix, return the triplet, such that we can reconstruct the
> ```

But the function returns a vector of triplets.

---

*[drake/math/eigen_sparse_triplet.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuHYvZ9lR9D95HJySi:-KTuHYv_udxlxMTQrCae:b-cyzy38) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L21)):*
> ```objc
>     const Derived& matrix) {
>   using Scalar = typename Derived::Scalar;
>   std::vector<Eigen::Triplet<Scalar>> triplet;
> ```

triplets.
Also, use `triplets.reserve(matrix.nonZeros());` here to prevent reallocations in the loop.

---

*[drake/math/eigen_sparse_triplet.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuIPOKN_H-2GFUQ2vd:-KTuIPOKN_H-2GFUQ2ve:b-jlw699) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L32)):*
> ```objc
> /**
>  * For a sparse matrix, return the row index, the column index, and value of
>  * the non-zero entries.
> ```

row index --> row indices
column index --> column indices

---

*[drake/math/eigen_sparse_triplet.h, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuIJpvtOxiWWOqM01h:-KTuIJpvtOxiWWOqM01i:b58v9ld) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L59)):*
> ```objc
> template <typename Derived>
> void SparseMatrixToRowColumnValueVectors(
>     const Derived& matrix, std::vector<int>& row, std::vector<int>& col,
> ```

row --> row_indices
col --> col_indices

---

*[drake/math/eigen_sparse_triplet.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuJimmiIGtwDS3FFIE:-KTuJimmiIGtwDS3FFIF:bg6gmh2) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L72)):*
> ```objc
>     for (typename Derived::InnerIterator it(matrix, i); it; ++it) {
>       row[nnz_count] = it.row();
>       col[nnz_count] = it.col();
> ```

`row()` and `col()` return `Eigen::Index` (`ptrdiff_t` by default, bigger than `int`). Either make the `row` and `col` arguments `vector<Eigen::Index>` or perform a `static_cast` here.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuKECfC28IBH7HAET_:-KTuKECgwb1ln6ZCJdkm:b-r22f59) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/test/eigen_sparse_triplet_test.cc#L11)):*
> ```cpp
> template <typename T, int options>
> void checkTriplet(const Eigen::SparseMatrix<T, options>& sp_mat) {
>   auto triplet1 = SparseMatrixToTriplets(sp_mat);
> ```

rename triplet --> triplets throughout this file whenever a bunch of triplets is meant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-:-KTuKy1ihoI6hgGMHqgT:b-z7idk4)*

**Comment by jwnimmer-tri** [comment]
*[drake/math/eigen_sparse_triplet.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuJimmiIGtwDS3FFIE:-KTuLP-NC0G4NndoxjQ5:bvzi4cz) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L72)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> `row()` and `col()` return `Eigen::Index` (`ptrdiff_t` by default, bigger than `int`). Either make the `row` and `col` arguments `vector<Eigen::Index>` or perform a `static_cast` here.
</details>
FYI I am not sure what defect this is proposing.  TTBOMK there is no compiler diagnostic from this assignment (that we have enabled), and there is no cppguide or code_style_guide rule for this (that I can recall).  I thought perhaps some kind of loss of precision defect, but the cast won't matter for that -- I believe the cast just makes explicit what the compiler is already required to do implicitly.  Perhaps the defect is that its unclear to a reader of the code that we are narrowing?  Though that would seem to be implied by this function's overall signature.  We can only express ints in this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774)*

**Comment by tkoolen** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/math/eigen_sparse_triplet.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuJimmiIGtwDS3FFIE:-KTuNoygEVUh8vAb1w8K:b-9i43z3) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L72)):*
> no compiler diagnostic from this assignment (that we have enabled)

I thought there was. Maybe that was just on MSVC.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774)*

**Comment by hongkai-dai** [comment]
Thanks @tkoolen for the review. I have addressed the comments, PTAL

---

Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/math/eigen_sparse_triplet.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuH51BaTBD-iEJIYHw:-KTue87ywOjZ8DJgKszh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L10)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> But the function returns a vector of triplets.
</details>
Done.

---

*[drake/math/eigen_sparse_triplet.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuHYvZ9lR9D95HJySi:-KTue9DQLxO2QT6wSSKO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L21)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> triplets.
> Also, use `triplets.reserve(matrix.nonZeros());` here to prevent reallocations in the loop.
</details>
Done.

---

*[drake/math/eigen_sparse_triplet.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuIPOKN_H-2GFUQ2vd:-KTueA1P_FjMNTA3XsqP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L32)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> row index --> row indices
> column index --> column indices
</details>
Done.

---

*[drake/math/eigen_sparse_triplet.h, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuIJpvtOxiWWOqM01h:-KTueL5qzCOzNSR4oWef:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L59)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> row --> row_indices
> col --> col_indices
</details>
Done.

---

*[drake/math/eigen_sparse_triplet.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuJimmiIGtwDS3FFIE:-KTug1lCUVESwIrf1qk8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/eigen_sparse_triplet.h#L72)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> > no compiler diagnostic from this assignment (that we have enabled)
> 
> I thought there was. Maybe that was just on MSVC.
</details>
Done.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-KTuKECfC28IBH7HAET_:-KTugCkxOa5ylhGjF35Z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ff5acaef36825680769a8938972adcdd430ae8b/drake/math/test/eigen_sparse_triplet_test.cc#L11)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> rename triplet --> triplets throughout this file whenever a bunch of triplets is meant.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-:-KTugQ2utvc5c1dO-RDm:b-r9ley4)*

**Comment by tkoolen** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-:-KTuhGWHaNoeIoy3BwUs:bnfp4nl)*

**Comment by hongkai-dai** [comment]
@tkoolen there is one comment not resolved, could you acknowledge it? Thanks

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-:-KTuuJg69_wORC8H3Dy-:bfdzb3e)*

**Comment by tkoolen** [comment]
That's blocking on @jwnimmer, not me.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-:-KTyid2u8RecDCQuA5cp:b-9xcmpu)*

**Comment by hongkai-dai** [comment]
@jwnimmer-tri  , could you acknowledge the comment if it is resolved? Thanks!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3774#-:-KTykKJCsF1V7-JuTwX4:b8v6ktt)*

**Comment by jwnimmer-tri** [comment]
Done.  (Sorry, I thought I clicked Satisfied, but must have been "discussing".)

**Pull request merged**
