### PR TITLE
Making PoseVector copyable/moveable

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This changes the PoseVector to be a final class. This allows us to make
it copyable/movable. However, it can't use the default operations because
it inherits from a parent class that *isn't* default copyable/movable.

Extends test to cover this new functionality.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6018)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@liangfok for feature review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-:-KjFB6bOQN1KtwrN16HF:b-ui3opy)*

**Comment by liangfok** [comment]
:lgtm: Just one cpplint issue, which was caught by CI.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-:-KjFvllOtDk31VczsN5F:bof5cdx)*

**Comment by jwnimmer-tri** [comment]
FYI the discussion in #4939 (which at one point had final classes codegen'd) relates to this PR, but by my quick read this PR is consistent with the lessons during the evolution of that one.

**Comment by SeanCurtis-TRI** [comment]
@jwnimmer-tri thanks for the link. Reviewable makes past conversations *very* difficult to follow. Careful reading of github allows me to piece the conversation (although, largely without code-defined context).

+@soonho-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-:-KjIpgN-09G5ZR3tWq9f:b-l2za2p)*

**Comment by jwnimmer-tri** [comment]
(When a github comment seems relevant, I usually just click through to reviewable to read the discussion in threaded mode.)

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by SeanCurtis-TRI** [comment]
(I've always assumed links were useless. I need to revise that. In Reviewable, it seems links are the only way to find anything concrete. Thanks for the pointer.)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-:-KjJ5KywBymm7aXTgwzp:b-cb4hji)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/rendering/pose_vector.cc, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJ2jFR5W8J_Mm6-5nR:-KjJ2jFR5W8J_Mm6-5nS:bi0h99r) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L26)):*
> ```cpp
> 
> template <typename T>
> PoseVector<T>::PoseVector(const PoseVector<T>& vec) : BasicVector<T>(kSize) {
> ```

How about the following for this one?
```c++
template <typename T>
PoseVector<T>::PoseVector(const PoseVector<T>& vec)
    : BasicVector<T>(vec.get_value()) {}
```

---

*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjJDH9aysyYBpsooeu7:b-iaty6y) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
> ```cpp
> template <typename T>
> PoseVector<T>& PoseVector<T>::operator=(PoseVector<T>&& vec) {
>   this->set_value(vec.get_value());
> ```

This definition of move-assign operator is somewhat unusual to me. First, it doesn't move `vec.get_value()` but copy it. So this operation is (at most) as efficient as copy-assign operator. The only difference between this move-assign and copy-assign is that this move-assign resets the argument `vec` while copy-assign does not.

Do I miss something? If not, could you add a comment section why we do this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/rendering/pose_vector.cc, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJ2jFR5W8J_Mm6-5nR:-KjJNG3phRkcf6MljOdS:bhykxhi) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L26)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

How about the following for this one?
```c++
template <typename T>
PoseVector<T>::PoseVector(const PoseVector<T>& vec)
    : BasicVector<T>(vec.get_value()) {}
```
</blockquote></details>

Done  I like that.  Thanks. :)

---

*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjJGUd4VMq1MU5Aw4oS:bmn73ou) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
The definition of "move" is an interesting one. 

Citing from here: http://en.cppreference.com/w/cpp/language/move_constructor

> Move constructors typically "steal" the resources held by the argument (e.g. pointers to dynamically-allocated objects, file descriptors, TCP sockets, I/O streams, running threads, etc), rather than make copies of them, and leave the argument in some valid but otherwise indeterminate state.

The key there is that it must be in a *valid* state. What is the appropriate "I've-had-my-data-stolen" valid state for a `PoseVector`? 

One can't remove the source's underlying `VectorX` because `PoseVector` inherits from `BasicVector` and is subject to the invariant that it is a fixed size. Technically, one could simply leave the values alone (certainly valid). However, inspired by this comment: https://reviewable.io/reviews/robotlocomotion/drake/5908#-KiXMrzEcnf1o_48GURs
it seems to make more sense to change it such that it is clear that any user-set state has been removed -- returning it to its default (or, in some sense, uninitialized state).

For example, if I move a `std::vector`, the source is reverted to the state it would have upon default constructing it. I can immediately start pushing values into that vector as if it were created anew. This move implementation has the same feel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjJQP7guM258NsPspO6:b5mx34b) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The definition of "move" is an interesting one. 

Citing from here: http://en.cppreference.com/w/cpp/language/move_constructor

> Move constructors typically "steal" the resources held by the argument (e.g. pointers to dynamically-allocated objects, file descriptors, TCP sockets, I/O streams, running threads, etc), rather than make copies of them, and leave the argument in some valid but otherwise indeterminate state.

The key there is that it must be in a *valid* state. What is the appropriate "I've-had-my-data-stolen" valid state for a `PoseVector`? 

One can't remove the source's underlying `VectorX` because `PoseVector` inherits from `BasicVector` and is subject to the invariant that it is a fixed size. Technically, one could simply leave the values alone (certainly valid). However, inspired by this comment: https://reviewable.io/reviews/robotlocomotion/drake/5908#-KiXMrzEcnf1o_48GURs
it seems to make more sense to change it such that it is clear that any user-set state has been removed -- returning it to its default (or, in some sense, uninitialized state).

For example, if I move a `std::vector`, the source is reverted to the state it would have upon default constructing it. I can immediately start pushing values into that vector as if it were created anew. This move implementation has the same feel.
</blockquote></details>

1. It doesn't steal anything. As a result, the passed argument `vec` is intact and in a "valid" state (by the invariant).
2. As a result, the reset part is not necessary.
3. Without the reset part, this definition is identical to copy-assign.

My suggestion: Let's not provide move-constructor and move-assign operator. That is, we don't need the following ones.

```c++
 PoseVector(PoseVector&& vec);
 PoseVector& operator=(PoseVector&& vec); 
```

We also need to change the expected outputs in the testcases if we go to this direction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjJTbQC45Raks6r7V0k:b4txfn6) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

1. It doesn't steal anything. As a result, the passed argument `vec` is intact and in a "valid" state (by the invariant).
2. As a result, the reset part is not necessary.
3. Without the reset part, this definition is identical to copy-assign.

My suggestion: Let's not provide move-constructor and move-assign operator. That is, we don't need the following ones.

```c++
 PoseVector(PoseVector&& vec);
 PoseVector& operator=(PoseVector&& vec); 
```

We also need to change the expected outputs in the testcases if we go to this direction.
</blockquote></details>

1. It does "steal" things: it steals the *values*. I think there's a reason that the reference I linked had "steal" in quotes.
2. The reset is necessary to return it to an untouched state.
3. If this gets used in something that *does* have move semantics, it can't use default move semantics. This way, it can propagate naturally into other objects that *do* have more interesting move semantics. And, as you might infer, I've got a concrete requirement of this having move semantics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjJV2RmAOOB1KMLo2qM:bvu33e0) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
> It does "steal" things: it steals the values. I think there's a reason that the reference I linked had "steal" in quotes.

I still think that it doesn't steal the `values`. In `basic_vector.h`, we only have the following function:

```
  void set_value(const Eigen::Ref<const VectorX<T>>& value)
```

It takes `value` as a `const T&`. Am I missing something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjJcRxwyED1Jwy6yO8L:b-80pdy8) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> It does "steal" things: it steals the values. I think there's a reason that the reference I linked had "steal" in quotes.

I still think that it doesn't steal the `values`. In `basic_vector.h`, we only have the following function:

```
  void set_value(const Eigen::Ref<const VectorX<T>>& value)
```

It takes `value` as a `const T&`. Am I missing something?
</blockquote></details>

Sorry, the stealing is *implicit* in resetting the source to identity. You are right, invoking `set_value` doesn't do stealing. It's the resetting that does. So, the whole thing, taken together, is move semantics.

So, I guess we ended up talking about two different things.  I would posit the following ideas:

1. We need move semantics for this class.
2. Given the properties of the `PoseVector` (via the `BasicVector`) this is an appropriate set of move semantics.

I felt you were initially disagreeing with 2 and then advocated making 2 go away by disagreeing with 1. So, with this restatement, I hope my position is abundantly clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjJre_kjhIp3MNRmKmO:b-2dm81s) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
> 1. We need move semantics for this class.

I'm not convinced for this one, yet. I'd like to know why it's the case.

FYI, if we don't provide move-constr. and move-assign for `PoseVector`, copy-constr and copy-assign will be used instead and I don't see a problem in that. Here, I assume that the resetting part is only required when a data is stolen, which is not the case here.

I think if there is a reason to reset an instance of `PoseVector`, it's better to have a method `.reset()` and we call it explicitly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by jwnimmer-tri** [comment]
Soonho asked me to look at this.  I will give it a read this evening; today is meeting-full day.

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by SeanCurtis-TRI** [comment]
I'll defer the removal of the move constructor/assignment operator then. @soonho-tri has persuaded me to remove it (as per the conversation below). I'm not 100% satisfied, but sufficiently persuaded.  However, as part of my dissatisfaction arises from other comments @jwnimmer-tri has made, I'll look forward to hearing your opinion. I'll go either direction as I feel either way has pros and cons.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjK43zemI9DrbNMMGB9:boek70o) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> 1. We need move semantics for this class.

I'm not convinced for this one, yet. I'd like to know why it's the case.

FYI, if we don't provide move-constr. and move-assign for `PoseVector`, copy-constr and copy-assign will be used instead and I don't see a problem in that. Here, I assume that the resetting part is only required when a data is stolen, which is not the case here.

I think if there is a reason to reset an instance of `PoseVector`, it's better to have a method `.reset()` and we call it explicitly.
</blockquote></details>

I'm persuaded by the argument against implementing an explicit move constructor.  Certainly, leaving the source `PoseVector` unchanged when a containing class is moved is a valid, indeterminate state. Although, it means any data explicitly set by users will persist (which counters the previous platform review recommendations I cited.)

I also agree with the `reset()` method. I briefly considered refactoring it and invoking both in the default constructor and the move operator. But that is rendered moot for now.

Based on the rule of five, I'm assuming you'd want me to explicitly delete the move semantics?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-:-KjK5ghYC0MG37vQakhA:bwz9ren)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjKHPmex2FGxRhcIO-o:b-4avbdg) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

One additional thought: my use case requires me to resize vectors of `PoseVector`. I'm using the `reserve()` method which requires the object to be "MoveInsertable". So, there is a *hard* requirement for move semantics. Or, I really need to revisit what I'm doing with these PoseVectors.
</blockquote></details>

I haven't read the whole discussion yet, but: when we want to use copy methods to realize MoveConstructible, we should _not_ do `= delete` on them; just leave them unmentioned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Comment by SeanCurtis-TRI** [comment]
This whole thing is now moot.  I thought I'd save myself some time and effort by re-using the `PoseVector`. However, in some further experimentation, I've realized that this isn't a good thing. So, I'm just closing this PR.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjKL35soTC4CM5LRqPr:bixn0bc) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I haven't read the whole discussion yet, but: when we want to use copy methods to realize MoveConstructible, we should _not_ do `= delete` on them; just leave them unmentioned.
</blockquote></details>

Also good to know. I assumed that leaving it implicit would be considered a code defect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-:-KjKL7BVw8yCC5UyRRcc:b6sk1qu)*

**Comment by SeanCurtis-TRI** [comment]
After further experimentation, the motivation for doing this has proven to be an error. So, I'm closing this for lack of sufficient justification.

**Comment by jwnimmer-tri** [comment]
*[drake/systems/rendering/pose_vector.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6018#-KjJDH9aysyYBpsooeu6:-KjKVZvKy5XZwqXcwQLK:bf9hc5u) ([raw file](https://github.com/robotlocomotion/drake/blob/579d261c44189353305c3bc38cd1b636b8d581e5/drake/systems/rendering/pose_vector.cc#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Also good to know. I assumed that leaving it implicit would be considered a code defect.
</blockquote></details>

It's important to be clear to readers (so would need some explanation somewhere), but TTBOMK there is literally no way to do it except for omitting all (non-comment) mention of the two functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6018)*

**Pull request closed without merging**
