### PR TITLE
Implements LQR for System 2.0 and updates the Pendulum example to use it

### PR DESCRIPTION
**Pull request by RussTedrake**
includes #4012, which should be merged first.
also updates remaining examples and to completely purge System1.0 version of Pendulum (towards #3975)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4041)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@david-german-tri  for feature review and +@sherm1 for platform

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-:-KVyv9XqawlMXh_o1z0u:b-gewyve)*

**Comment by RussTedrake** [comment]
fyi - #4012 has landed, and I've curated the commits on this branch to get a clean history.  @david-german-tri and @sherm1 , PTAL?

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Jenkins is completely broken tonight.  Don't expect any builds to happen.

**Comment by david-german-tri** [comment]
Reviewed 2 of 20 files at r3, 16 of 18 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_lqr.cc, line 38 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3r-rlYibQfDrzN_xb:-KW3r-rlYibQfDrzN_xc:b-d6bamb) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/examples/Pendulum/pendulum_run_lqr.cc#L38)):*
> ```cpp
> 
>   Eigen::MatrixXd Q(2, 2);
>   Q << 10, 0, 0, 1;
> ```

BTW, preexisting complaint: Where do these numbers come from?

---

*[drake/examples/Pendulum/test/pendulum_urdf_dynamics_test.cc, line 14 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3rsmo1GBXoXxnF-2w:-KW3rsmo1GBXoXxnF-2x:bbiqu7l) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/examples/Pendulum/test/pendulum_urdf_dynamics_test.cc#L14)):*
> ```cpp
> namespace {
> 
> GTEST_TEST(urdfDynamicsTest, AllTests) {
> ```

BTW pre-existing complaints - this test uses randomness, has a spammy loop in it, and doesn't assert very much.  Seems like the dynamics could just be compared at three or four points of interest.  (Unrelated to this PR, though.)

---

*[drake/systems/controllers/linear_optimal_control.cc, line 28 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3pWx4xHbWGs-FNpf_:-KW3pWx4xHbWGs-FNpfa:bpcyckn) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/controllers/linear_optimal_control.cc#L28)):*
> ```cpp
>   DRAKE_ASSERT(
>       CompareMatrices(R, R.transpose(), 1e-10, MatrixCompareType::absolute));
>   // Note: the lqr method will throw an exception of Q is not PSD or R is not
> ```

Please document that in the `.h` as well.

---

*[drake/systems/controllers/linear_optimal_control.cc, line 33 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3prLItmwZvUussnDv:-KW3prLJ3IldGiQE0SI3:b-w95wo0) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/controllers/linear_optimal_control.cc#L33)):*
> ```cpp
>   auto linear_system = Linearize(system, context);
> 
>   Eigen::MatrixXd K(num_inputs, num_states), S(num_states, num_states);
> ```

BTW, consider a comment explaining that `K` and `S` are outputs of `lqr()`, and therefore uninitialized.  (Since `lqr()` uses non-const reference arguments, this isn't obvious.)

---

*[drake/systems/controllers/linear_optimal_control.h, line 8 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3oPWCmpSDXwzNdv7E:-KW3oPWCmpSDXwzNdv7F:b2jby6w) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/controllers/linear_optimal_control.h#L8)):*
> ```objc
> namespace systems {
> 
> /// Linearizes the System around the specified Context, computes the optimal
> ```

Unit test for this library?

---

*[drake/systems/controllers/linear_optimal_control.h, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3pJ1sZinETJPBy0cT:-KW3p2WNiBFDq6Mljdjv:b-kl268q) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/controllers/linear_optimal_control.h#L19)):*
> ```objc
> /// system to.  Note that this state/input must be an equilibrium point of the
> /// system.  See drake::systems::Linearize for more details.
> /// @param Q A symmetric positive semi-definite matrix of size num_states x
> ```

BTW, are Q and R cost coefficients?  Might be worth saying more about their actual semantics.

---

*[drake/systems/framework/context.h, line 147 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3nOX8FLYxL2dQIidt:-KW3nOXADaG7kocMtYRI:b-t7gxee) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/framework/context.h#L147)):*
> ```objc
>   /// sets the input port (disconnecting whatever input port was previously
>   /// there).
>   BasicVector<T>* SetInputPortToConstantValue(int index,
> ```

BTW, I was going to call this `FixInputPort`.  I don't feel strongly either way.

---

*[drake/systems/framework/context.h, line 148 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3ni7iDG-yMtRSPNlY:-KW3ni7iDG-yMtRSPNlZ:b-w5guwj) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/framework/context.h#L148)):*
> ```objc
>   /// there).
>   BasicVector<T>* SetInputPortToConstantValue(int index,
>                                    const Eigen::Ref<const VectorX<T>>& data) {
> ```

nit: clang-format

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 18 files at r4, 4 of 7 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_lqr.cc, line 38 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3r-rlYibQfDrzN_xb:-KW7y-xqnx-1bfpG2nuZ:b-5e3ojp) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/examples/Pendulum/pendulum_run_lqr.cc#L38)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, preexisting complaint: Where do these numbers come from?
</details>
these are the cost function for LQR.  the 10-to-1 ratio essentially comes from the unit conversion between radians and radians/sec (given a natural frequency of sqrt(g/l) ), but it's not a hard-fast rule.  Typically these are set and tuned somewhat heuristically for each robot.  

it feels a bit to hand-wavy of an explanation to merit an in-code comment.  what do you think?

---

*[drake/examples/Pendulum/test/pendulum_urdf_dynamics_test.cc, line 14 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3rsmo1GBXoXxnF-2w:-KW7ymDbTK-d-iO2kCKM:b-ahvfad) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/examples/Pendulum/test/pendulum_urdf_dynamics_test.cc#L14)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW pre-existing complaints - this test uses randomness, has a spammy loop in it, and doesn't assert very much.  Seems like the dynamics could just be compared at three or four points of interest.  (Unrelated to this PR, though.)
</details>
the randomness is the same on every run (because the seed is not set).  

i think it asserts rather a lot, it will catch any dynamics mismatch.

agreed that 1000 is more than necessary for this system, but we've been in the habit of making it a large number for higher dimensional systems where it is warranted.  plus it's cheap.  have changed it to 100.

---

*[drake/systems/controllers/linear_optimal_control.cc, line 28 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3pWx4xHbWGs-FNpf_:-KW803KsPjRqxBCuMOXv:bhsyqau) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/controllers/linear_optimal_control.cc#L28)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please document that in the `.h` as well.
</details>
working on testing it.

---

*[drake/systems/controllers/linear_optimal_control.cc, line 33 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3prLItmwZvUussnDv:-KWI6m717UDA-rzWiQKz:b1kla1w) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/controllers/linear_optimal_control.cc#L33)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, consider a comment explaining that `K` and `S` are outputs of `lqr()`, and therefore uninitialized.  (Since `lqr()` uses non-const reference arguments, this isn't obvious.)
</details>
actually, I've done a more substantial refactor now to not only address this, but avoid the unnecessary allocation (and generally purify the code)

---

*[drake/systems/controllers/linear_optimal_control.h, line 8 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3oPWCmpSDXwzNdv7E:-KWI6vRf-nvo5NkD-pp_:b-qt3ufc) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/controllers/linear_optimal_control.h#L8)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Unit test for this library?
</details>
does coverage from the examples count?

---

*[drake/systems/controllers/linear_optimal_control.h, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3pJ1sZinETJPBy0cT:-KWI74Kj82HUMAMHkgx3:b-sqtao0) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/controllers/linear_optimal_control.h#L19)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, are Q and R cost coefficients?  Might be worth saying more about their actual semantics.
</details>
yes.  done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041)*

**Comment by david-german-tri** [comment]
The new tests are failing in CI, and there are some cpplint problems as well.

---

Reviewed 2 of 18 files at r4, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[drake/examples/Pendulum/pendulum_run_lqr.cc, line 38 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3r-rlYibQfDrzN_xb:-KWKaTp0IG8MxMXGDTOG:b-c4p4ud) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/examples/Pendulum/pendulum_run_lqr.cc#L38)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> these are the cost function for LQR.  the 10-to-1 ratio essentially comes from the unit conversion between radians and radians/sec (given a natural frequency of sqrt(g/l) ), but it's not a hard-fast rule.  Typically these are set and tuned somewhat heuristically for each robot.  
> 
> it feels a bit to hand-wavy of an explanation to merit an in-code comment.  what do you think?
</details>
I think the comment would be an improvement over no explanation at all.

---

*[drake/examples/Pendulum/pendulum_run_lqr.cc, line 43 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKaX2gVP-dpva5-hZE:-KWKaX2gVP-dpva5-hZF:b-145ie4) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/examples/Pendulum/pendulum_run_lqr.cc#L43)):*
> ```cpp
> 
>   auto controller =
>       builder.AddSystem(LinearQuadraticRegulator(*pendulum, *pendulum_context, Q, R));
> ```

btw, gt-80

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 10 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKc2AZfQlYKMCCBlhz:-KWKc2AZfQlYKMCCBli-:b-i283q9) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L10)):*
> ```cpp
> GTEST_TEST(TestLQR, DoubleIntegrator) {
>   using namespace Eigen;
>   using namespace drake;
> ```

https://google.github.io/styleguide/cppguide.html#Namespaces

Recommended approach is to wrap the whole file in 

```
namespace  drake {
namespace {
```

and using-decl just the specific names from `Eigen` that you need, at the file level.

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 12 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKdQ2sSUJTN3QrObjb:-KWKdQ2tg3x_2exb4X0n:b-nc25dx) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L12)):*
> ```cpp
>   using namespace drake;
> 
>   // Double integrator dynamics: qddot = u.
> ```

should this have read `yddot = u`?

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 33 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKcyVMzGlFnR7WOsZ2:-KWKcyVMzGlFnR7WOsZ3:b87iz9q) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L33)):*
> ```cpp
> 
>   // Test LinearSystem version of the LQR
>   auto linear_lqr = LinearQuadraticRegulator(sys, Q, R);
> ```

btw, I think no `auto` would be clearer, given the emphasis on type

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 47 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKd-Mjnmypjf4uHaPU:-KWKd-Mjnmypjf4uHaPV:b-lr0xth) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L47)):*
> ```cpp
>   // Should get the same result, but as an affine system.
>   auto context = sys.CreateDefaultContext();
>   auto lqr = LinearQuadraticRegulator(sys, *context, Q, R);
> ```

ditto here

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 60 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKbdyet62Gcex9wcTW:-KWKbdyfeoN9rmAid_dY:b-lgp3kq) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L60)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(lqr->y0(), Matrix<double, 1, 1>::Zero(), tol,
>                               MatrixCompareType::absolute));
> }
> ```

btw, missing newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-:-KWKduph3NH2yosFyPiA:bcbfscj)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/context.h, line 147 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3nOX8FLYxL2dQIidt:-KWKe4VdgYsbyU1RbA5h:b-vgxwqm) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/framework/context.h#L147)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, I was going to call this `FixInputPort`.  I don't feel strongly either way.
</details>
#4031 actually introduced `FixInputPort`, so this should probably be renamed to match, or vice versa

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041)*

**Comment by RussTedrake** [comment]
Review status: 5 of 18 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_lqr.cc, line 38 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3r-rlYibQfDrzN_xb:-KWr-pyU5rXpwYLoFxJq:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/examples/Pendulum/pendulum_run_lqr.cc#L38)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I think the comment would be an improvement over no explanation at all.
</details>
done

---

*[drake/examples/Pendulum/pendulum_run_lqr.cc, line 43 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKaX2gVP-dpva5-hZE:-KWr-s8tQYpVyunZ5kGL:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/examples/Pendulum/pendulum_run_lqr.cc#L43)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> btw, gt-80
</details>
done

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 10 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKc2AZfQlYKMCCBlhz:-KWr0cU6SRHIMh5k1UY3:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L10)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> https://google.github.io/styleguide/cppguide.html#Namespaces
> 
> Recommended approach is to wrap the whole file in 
> 
> ```
> namespace  drake {
> namespace {
> ```
> 
> and using-decl just the specific names from `Eigen` that you need, at the file level.
> 
> 
</details>
done

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 12 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKdQ2sSUJTN3QrObjb:-KWr0dg14xOWfaA0X1k1:b-mpvtjj) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L12)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> should this have read `yddot = u`?
</details>
no.  q is the convention for the positions in a second-order system.

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 33 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKcyVMzGlFnR7WOsZ2:-KWr12znEjuGtjEM3-Sf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L33)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> btw, I think no `auto` would be clearer, given the emphasis on type
</details>
Done.

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 47 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKd-Mjnmypjf4uHaPU:-KWr19NiODEYrY0XEaTv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L47)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> ditto here
</details>
Done.

---

*[drake/systems/controllers/test/linear_optimal_control_test.cc, line 60 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWKbdyet62Gcex9wcTW:-KWr1BaU-AhNaZ39Ak-g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9ad9a1d2845b18e63f72c42d98d2ad797297f7c/drake/systems/controllers/test/linear_optimal_control_test.cc#L60)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> btw, missing newline
</details>
Done.

---

*[drake/systems/framework/context.h, line 147 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3nOX8FLYxL2dQIidt:-KWr1l9HJzITLo8vcR5c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/framework/context.h#L147)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> #4031 actually introduced `FixInputPort`, so this should probably be renamed to match, or vice versa
</details>
Done.

---

*[drake/systems/framework/context.h, line 148 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KW3ni7iDG-yMtRSPNlY:-KWr1mwzFqRCQZZ_BPUv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c911d31a3d676859bdc7f8448347ecee67b74cf3/drake/systems/framework/context.h#L148)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> nit: clang-format
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041)*

**Comment by RussTedrake** [comment]
fyi - plan to squash merge (rebase -i was non-trivial given all of the merging with master).

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 2 of 18 files at r4, 10 of 13 files at r7, 3 of 3 files at r8.
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/controllers/linear_optimal_control.cc, line 69 at r8](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWsj598WAiLL7prZzsc:-KWsj598WAiLL7prZzsd:b-2gpoud) ([raw file](https://github.com/robotlocomotion/drake/blob/910b62284edb010a704a5558b604eacf0070f750/drake/systems/controllers/linear_optimal_control.cc#L69)):*
> ```cpp
>                                    const Eigen::Ref<const Eigen::MatrixXd>& Q,
>                                    const Eigen::Ref<const Eigen::MatrixXd>& R) {
>   const size_t n = B.rows(), m = B.cols();
> ```

This leads to signed/unsigned comparison failures below in CI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-:-KWshy3v9Mv01hXficBo:b-s794vx)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 13 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041)*

**Comment by sherm1** [comment]
This looks really good and is an amazing amount of functionality for a modest amount of code. System2 is looking really powerful! CI is still whining about signed/unsigned mismatch. I added one non-blocking request for documentation, PTAL. With those addressed, :lgtm:.

---

Reviewed 1 of 20 files at r3, 4 of 18 files at r4, 1 of 6 files at r6, 11 of 13 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/context.h, line 156 at r8](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWstSLTX9JeJvcrwuBl:-KWstSLTX9JeJvcrwuBm:b-ocw4kp) ([raw file](https://github.com/robotlocomotion/drake/blob/910b62284edb010a704a5558b604eacf0070f750/drake/systems/framework/context.h#L156)):*
> ```objc
>   /// Connects a FreestandingInputPort with the given @p value at the given
>   /// @p index. Asserts if @p index is out of range.
>   BasicVector<T>* FixInputPort(int index,
> ```

BTW, this signature returns live access to the input port's value but the other signature does not. Please document the return parameter here and consider whether the previous method should be modified to match.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-:-KWsu6jK1QsjiMoygI2e:b-wumnpa)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/context.h, line 156 at r8](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWstSLTX9JeJvcrwuBl:-KWsvcl4B6wNXe08dpbW:b-wn177b) ([raw file](https://github.com/robotlocomotion/drake/blob/910b62284edb010a704a5558b604eacf0070f750/drake/systems/framework/context.h#L156)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, this signature returns live access to the input port's value but the other signature does not. Please document the return parameter here and consider whether the previous method should be modified to match.
</details>
Oh, good catch.  I actually think this should return void, and `FixInputPort` should be called repeatedly as needed.  If you decide to keep it as-is, I think the comment should be especially clear about the lifetime of the returned pointer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041)*

**Comment by RussTedrake** [comment]
Review status: 15 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/linear_optimal_control.cc, line 69 at r8](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWsj598WAiLL7prZzsc:-KWw13YBZ9heOV3dSNzs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/910b62284edb010a704a5558b604eacf0070f750/drake/systems/controllers/linear_optimal_control.cc#L69)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This leads to signed/unsigned comparison failures below in CI
</details>
Done.

---

*[drake/systems/framework/context.h, line 156 at r8](https://reviewable.io:443/reviews/robotlocomotion/drake/4041#-KWstSLTX9JeJvcrwuBl:-KWw2QPPLN1ZFuDkvNlr:bhboapn) ([raw file](https://github.com/robotlocomotion/drake/blob/910b62284edb010a704a5558b604eacf0070f750/drake/systems/framework/context.h#L156)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Oh, good catch.  I actually think this should return void, and `FixInputPort` should be called repeatedly as needed.  If you decide to keep it as-is, I think the comment should be especially clear about the lifetime of the returned pointer.
</details>
There are some important use cases where we need to repeatedly evaluate the system at e.g., millions of different inputs.  i'd prefer to avoid dynamic allocation there if possible.  will add a note.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4041)*

**Pull request merged**
