### PR TITLE
Preserve the mosek environment across calls to Solve().

### PR DESCRIPTION
**Pull request by sammy-tri**
Most importantly, this holds the lock from the license server (which
can take a while to get) and significantly improves performance on
longer lived problems using remote licenses.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6054)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ericcousineau-tri for feature review (and design discussion if he's been thinking of other uses/application for keeping solver specific data between calls to Solve())

+(status: do not merge) since the design is still under discussion.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6054#-:-KjdRLKrtI9ROaKZKfVA:bex7hm0)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

For the time being, I believe keeping the session-persistent solver data tied to the specific solver class is a good route. All else, if we want to always have this piped through `SolverData`, it should be a simple change.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6054#-:-Kji1m845gXJzxee-P_y:bhdrgqk)*

**Comment by sammy-tri** [comment]
+@ggould-tri (tomorrow's platform reviewer (for a real review this time...))

-(status: do not merge) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6054#-:-KjioL2kj1MqtKBVU_tL:b-b08dlo)*

**Comment by ggould-tri** [comment]
I will get to this tomorrow morning.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6054#-:-KjisPXtTfIiXP-IqZUR:b-p9wyno)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6054#-:-KjmYQ9cOdey-qcMWtDS:bnfp4nl)*

**Pull request merged**
