### PR TITLE
Add nlopt in setup scripts

### PR DESCRIPTION
**Pull request by soonho-tri**
Related issue: #7335.

When this PR is merged and CI images are updated, I will open another PR to use system nlopt in Drake.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7358)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jamiesnape for feature-review, please.
+@jwnimmer-tri for platform-review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7358#-:-KxYXCAnkNqsPAIOWm4W:btqyp8w)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7358#-:-KxYjBXk6mpFwH-mJ6ga:bnfp4nl)*

**Comment by jamiesnape** [comment]
:lgtm: (create an issue for the CI updates, I think we have `protobuf` on Mac to add as well)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs.sh, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7358#-Kx_OKK0eNendRsW7wf1:-Kx_OKK0eNendRsW7wf2:bmpe7z5) ([raw file](https://github.com/robotlocomotion/drake/blob/dbced0be25f7aa5afe1806201b31ae838fb9d37f/setup/mac/install_prereqs.sh#L47)):*
> ```Shell
> lz4
> numpy
> nlopt
> ```

BTW Alphabetize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7358#-:-Kx_OPCRLvCyJKdJW6vb:b-791pyy)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs.sh, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7358#-Kx_OKK0eNendRsW7wf1:-Kx_R-HRTj8bc4FuiykC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbced0be25f7aa5afe1806201b31ae838fb9d37f/setup/mac/install_prereqs.sh#L47)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Alphabetize
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7358)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7358)*

**Pull request merged**
