### PR TITLE
Let runPendulumEnergyShaping run in the visualizer

### PR DESCRIPTION
**Pull request by ggould-tri**

### CODE REVIEW

**Comment by Lucy-tri** [comment]
Looks good.

**Comment by sammy-tri** [comment]
+1 looks good to me

**Comment by ggould-tri** [comment]
(for gripes about command-line parsing see #1768 )

**Comment by ggould-tri** [comment]
drake005 seems to be in matlab license fail.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
@jwnimmer-tri tells me the travis failure is ignorable for this change.  Labeling as ready.

**Comment by jwnimmer-tri** [comment]
LGTM per second code review.  I'm not going to ding you for leaving a cappunc error in a refactored comment.

**Pull request merged**
