### PR TITLE
Clarified that implementation comments should be imperative.

### PR DESCRIPTION
**Pull request by liangfok**
# Motivations

1. Being consistent is good.
2. Reduce probability and cost of bike shedding.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3479)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@ggould-tri for platform review please.

Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3479#-:-KRnNifZNqGcMr2YGAJM:bu7u2d7)*

**Comment by jwnimmer-tri** [comment]
I don't mind this rule, since it's the way that I write.  But I am unconvinced that it matters enough to force authors to do it.

**Comment by liangfok** [comment]
I just updated this PR's original description with two motivations.

**Comment by jwnimmer-tri** [comment]
> 2. Reduce probability and cost of bike shedding.

We can achieve this by just... stopping talking about it?

**Comment by liangfok** [comment]
> > (2.) Reduce probability and cost of bike shedding.
>
> We can achieve this by just... stopping talking about it?

For me, yes, but it'll be nice not to go through the whole review / author discussion for everyone else.

**Comment by ggould-tri** [comment]
It seems to me that so long as they are grammatically correct in _some_ mood and reduce rather than increase confusion, implementation comments ought to be author's discretion -- they are implementation details, after all.  And I don't see much value in consistency at this level of detail.

If we need an explicit statement of author's-discretion to shut down out-of-control discussions, we could do that.  But it would probably be better for people to just not defect clear and and complete implementation comments.

Finally I'm not at all sure what "platform review" consists of for a proposal like this.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3479#-:-KRnaY1HjYyIJ7aC328-:bfflds6)*

**Comment by liangfok** [comment]
OK. I shall close this PR.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3479#-:-KRnc22EA_k1qNdi5K9B:bwimwnk)*

**Pull request closed without merging**
