### PR TITLE
Revert "MultibodyPlant (internally) starts using DFT ordering."

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Reverts RobotLocomotion/drake#16035

It broke `mac-big-sur-clang-bazel-continuous-release`.
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-big-sur-clang-bazel-continuous-release/909/
```
[4:13:51 PM]  ERROR: /Users/bigsur/workspace/mac-big-sur-clang-bazel-continuous-release/src/multibody/plant/BUILD.bazel:400:20: Compiling multibody/plant/test/multibody_plant_test.cc failed: (Aborted): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' ... (remaining 522 argument(s) skipped)
[4:13:51 PM]  
[4:13:51 PM]  Use --sandbox_debug to see verbose messages from the sandbox
[4:13:51 PM]  multibody/plant/test/multibody_plant_test.cc:3142:44: error: no viable overloaded '='
[4:13:51 PM]               left_finger_actuator.index()) = 1;
[4:13:51 PM]               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
[4:13:51 PM]  external/eigen/include/_usr_local_Cellar_eigen_3.4.0_1_include_eigen3/Eigen/src/Core/MatrixBase.h:139:14: note: candidate function not viable: no known conversion from 'int' to 'const Eigen::MatrixBase<Eigen::IndexedView<Eigen::Matrix<double, -1, -1, 0>, Eigen::internal::SingleRange, drake::TypeSafeIndex<drake::multibody::JointActuatorElementTag>>>' for 1st argument
```

It will need fixes similar to #15335.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16113)

### CODE REVIEW

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by sherm1** [comment]
FYI that's likely the TypeSafeIndex failing to convert to int on the LHS, not the int on the RHS. Fix in #15335 is
```
///    some_vector(foo_index) = 0.0;       // Fails to compile.
///    some_vector(int{foo_index}) = 0.0;  // Compiles OK.
```

**Review by DamrongGuoy — COMMENTED** [review]
Thank you.  Since it's a late evening for @amcastro-tri now, I'll fix that for him.  I'll make sure I can do that before the Nightly CI starts (a few hours).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16113#-:-MofQia_5gOv65CLHFkd:b8p2uar)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Comment by DamrongGuoy** [comment]
The fix forward PR #16114 has landed.  There is no need for this revert PR. Close it now.

**Pull request closed without merging**
