### PR TITLE
Optitrack LCM types added

### PR DESCRIPTION
**Pull request by naveenoid**
Brings in a robotlocomotion repo with the Optitrack driver and its LCM types. The actual test code is a dummy for now to make sure its brought in correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5966)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-KiqE7K1c1Vqn1GQ03j5:-KiqE7K2DZJunSoIPbrJ:b-u50pnr) ([raw file](https://github.com/robotlocomotion/drake/blob/d112c7d1f8725f3deb7790d016943700430f5b57/WORKSPACE#L174)):*
> ```Python
>     name = "optitrack_driver",
>     repository = "RobotLocomotion/optitrack-driver",
>     commit = "e78b74ce2b9afface6b811c0f9496730773a48a7",
> ```

FYI The LICENSE for this commit reads "Copyright (c) 2017, Sam Creasey".  That is not correct -- at a minimum, TRI owns the copyright, not Sam.  I won't block this PR on it, but please ensure that it gets fixed.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 285 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-KiqDEZSOUcXGYWB6DXe:-KiqDEZT800Ctb0NCgom:bnasy20) ([raw file](https://github.com/robotlocomotion/drake/blob/d112c7d1f8725f3deb7790d016943700430f5b57/drake/examples/kuka_iiwa_arm/BUILD#L285)):*
> ```Python
>     deps = [
>         "@optitrack_driver//lcmtypes:optitrack_lcmtypes",
>         "@gflags//:gflags",
> ```

`gflags` is not used by this test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-:-KiqHTL62rPJrhRi1Kqa:bnfp4nl)*

**Comment by naveenoid** [comment]
Who shall I tag for platform review? Or do you think this is simple enough for you to take care of it as well?

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-KiqE7K1c1Vqn1GQ03j5:-KiqQTQThBIJzfAfM7Pj:bagzck9) ([raw file](https://github.com/robotlocomotion/drake/blob/d112c7d1f8725f3deb7790d016943700430f5b57/WORKSPACE#L174)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The LICENSE for this commit reads "Copyright (c) 2017, Sam Creasey".  That is not correct -- at a minimum, TRI owns the copyright, not Sam.  I won't block this PR on it, but please ensure that it gets fixed.
</blockquote></details>

Tagging @sammy-tri  

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 285 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-KiqDEZSOUcXGYWB6DXe:-Kiw465BakyTjCc_K78X:b-wnfmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/d112c7d1f8725f3deb7790d016943700430f5b57/drake/examples/kuka_iiwa_arm/BUILD#L285)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

`gflags` is not used by this test.
</blockquote></details>

Done. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-:-KiwAEF5hv1OTRp4FB2f:bud3p3y)*

**Comment by jwnimmer-tri** [comment]
Probably fine, but worth having +@sammy-tri do a review if we can wait.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-:-KiwHlyAbSGHoItNaa9B:bv3bgie)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-KiqE7K1c1Vqn1GQ03j5:-Kj3MHtZLM8FRl4dpWhQ:bu97kj) ([raw file](https://github.com/robotlocomotion/drake/blob/d112c7d1f8725f3deb7790d016943700430f5b57/WORKSPACE#L174)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Tagging @sammy-tri  
</blockquote></details>

Wow.   That's both autogenerated and completely wrong.  Will dig into license rathole now.

This is one of the many times I wish we didn't do some things on Drake master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5966)*

**Comment by jwnimmer-tri** [comment]
It should be as simple as changing it to approximately "Copyright the optitrack-driver authors" instead of "Copyright Sam".

**Comment by sammy-tri** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-KiqE7K1c1Vqn1GQ03j5:-Kj3SKhvOUF4csGp9f2I:b-7dog0t) ([raw file](https://github.com/robotlocomotion/drake/blob/d112c7d1f8725f3deb7790d016943700430f5b57/WORKSPACE#L174)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Wow.   That's both autogenerated and completely wrong.  Will dig into license rathole now.

This is one of the many times I wish we didn't do some things on Drake master.
</blockquote></details>

Updated LICENSE file.   We could update the SHA here to  3a5da8d7c66c95ca98cda4dc7ca604f681464168 if we want to point to the new version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5966)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-:-Kj3TZH2xXQ7g10bDuwv:bnfp4nl)*

**Comment by naveenoid** [comment]
Updated SHA. Will merge once CI is happy.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[WORKSPACE, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-KiqE7K1c1Vqn1GQ03j5:-Kj4-T46oz0yODm8tUBZ:b-q1o062) ([raw file](https://github.com/robotlocomotion/drake/blob/d112c7d1f8725f3deb7790d016943700430f5b57/WORKSPACE#L174)):*
> 3a5da8d7c66c95ca98cda4dc7ca604f681464168
updated PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5966#-:-Kj4-VRNWhhJndVUmZso:b-7lfxx5)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5966)*

**Pull request merged**
