### PR TITLE
Don't use @gtest//:main from a drake_cc_library

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Discovered during #6159 work.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6538)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6538#-:-KohSFNzQj2Bq6ei5vYZ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review (tomorrow) per rotation, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6538#-:-KohdqHwR0WVgVHaK_7n:bnfp4nl)*

**Pull request merged**
