### PR TITLE
[ad] Add Eigen trait specializations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17492.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19622)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with some minor comments.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19622#-:-NY9hUQq-akIgfTTEBW8:b-el9g94)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`common/ad/internal/eigen_specializations.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19622#-NY9eK4YEUxHh1dALwa0:-NY9eK4YEUxHh1dALwa1:b-x3kpqj) ([raw file](https://github.com/RobotLocomotion/drake/blob/3d2a2cbfd16c7145f45f35d6b8d8f42c97ac4982/common/ad/internal/eigen_specializations.h#L29)):*
> ```objc
>   // Inherit the constants from `double`, but be sure to fatten a few types up
>   // to full AutoDiff where necessary.
>   using Real = drake::ad::AutoDiff;
> ```

BTW this surprised me (was expecting `using Real = double`) but I see this is how Eigen uses it for AutoDiffScalar. A note to that effect could be helpful here.
___
*[`common/ad/test/matrix_test.cc` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19622#-NY9gZMW0ttNXqFY0AMl:-NY9gZMW0ttNXqFY0AMm:b-g1vulo) ([raw file](https://github.com/RobotLocomotion/drake/blob/3d2a2cbfd16c7145f45f35d6b8d8f42c97ac4982/common/ad/test/matrix_test.cc#L28)):*
> ```cpp
>   // Check the NumTraits by multiplying mixed-type scalars.
>   MatrixX<AutoDiff> A2 = A * 2.0;
>   MatrixX<AutoDiff> B2 = 2.0 * B;
> ```

minor: This is testing ScalarBinaryOpTraits rather than NumTraits. Also I think it would be more convincing as `auto A2 = A * 2.0;` with a subsequent check on the type. Otherwise we could be seeing a MatrixX conversion constructor acting on a (possibly wrong) return type of `A * 2.0`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19622)* status: needs at least two assigned reviewers

___
*[`common/ad/test/matrix_test.cc` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19622#-NY9gZMW0ttNXqFY0AMl:-NYDvA-q5n4AMyxbDeAI:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/3d2a2cbfd16c7145f45f35d6b8d8f42c97ac4982/common/ad/test/matrix_test.cc#L28)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: This is testing ScalarBinaryOpTraits rather than NumTraits. Also I think it would be more convincing as `auto A2 = A * 2.0;` with a subsequent check on the type. Otherwise we could be seeing a MatrixX conversion constructor acting on a (possibly wrong) return type of `A * 2.0`.
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for platform

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19622#-:-NYF_BE8Ayj9BuIZAGFj:b-kwmbor)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19622#-:-NYFaS_B8bdoUaHRLbGI:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19622)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19622)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Pull request merged**
