### PR TITLE
Updated inertias for the iiwa 7

### PR DESCRIPTION
**Pull request by AdityaBhat-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20420)

### CODE REVIEW

**Comment by AdityaBhat-TRI** [comment]
Before

**Comment by AdityaBhat-TRI** [comment]
After:

**Comment by AdityaBhat-TRI** [comment]
+@EricCousineau-TRI For review

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: fix) 

I don't have access to the referenced book so I'll have to rely on the feature reviewer and the author for accuracy of the newly added data. 

The CI failure seems to be caused by the added rotor inertia. The added inertia is significantly large: 160 * 160 * 0.0001737109 = 4.44699904. So the feedforward torque in the failing test needs to be larger to make an noticeable effect.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20420#-:-NhXzPnJ1TT9s0toF6Bv:b7gkdn5)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`manipulation/models/iiwa_description/README.md` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20420#-NhXwjrUDdT8E0Q0Op3x:-NhXwjrUDdT8E0Q0Op3y:b-hzjquc) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f12d80e8c33b27082bb5f5ef1deb149f7cf0e9/manipulation/models/iiwa_description/README.md#L87)):*
> ```Markdown
> by Christan Ott.
> (URL:
> <https://link.springer.com/book/10.1007/978-3-540-69255-3>, Accessed on 2023-10-24)
> ```

BTW, if the source is a book instead of a link to a pdf online, you can cite it like a book.



_Suggestion:_
```Markdown
The values for the rotor inertias are obtained from [Ott 2008].

[Ott 2008] Ott, Christian. Cartesian impedance control of redundant and flexible-joint robots. Springer, 2008.
```
___
*[`manipulation/models/iiwa_description/test/iiwa_variants_parsing_test.cc` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20420#-NhXymGZ6mMANlU3A9WQ:-NhXymGZ6mMANlU3A9WR:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f12d80e8c33b27082bb5f5ef1deb149f7cf0e9/manipulation/models/iiwa_description/test/iiwa_variants_parsing_test.cc#L33)):*
> ```cpp
> }
> 
> // Read the common robot model files for IIWA7
> ```

nit



_Suggestion:_
```cpp
// Read the common robot model files for IIWA14
```

**Comment by AdityaBhat-TRI** [comment]
I just fixed that. Increased the feedforward torque to 10N and the test started passing locally

**Review by EricCousineau-TRI — COMMENTED** [review]
> The added inertia is significantly large [...]

Double-checked that this is the intended value.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20420#-:-NhY8ezY34oxGZYR_MZ-:b-ou7wg)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`manipulation/models/iiwa_description/README.md` line 86 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20420#-NhY8Yle0Vr36CdhvZEq:-NhY8Yle0Vr36CdhvZEr:b-bm9vf3) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff51d5c195700ca21c66b3b60cb68d826dd87a3c/manipulation/models/iiwa_description/README.md#L86)):*
> ```Markdown
> The values for the rotor inertias are obtained from [Ott 2008].
> 
> [Ott 2008] Ott, Christian. Cartesian impedance control of redundant and flexible-joint robots. Springer, 2008.
> ```

nit Could you add page and figure? i.e. `Table A.2 on page 188`?

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20420#-:-NhYD07m1zekySFlnHJ1:bg7igkv)* status: 1 unresolved discussion

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20420)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AdityaBhat-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20420)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri(platform)

**Pull request merged**
