### PR TITLE
Python bindings for ConvexHull

### PR DESCRIPTION
**Pull request by sadraddini**
Addresses https://github.com/RobotLocomotion/drake/issues/21835

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21849)

### CODE REVIEW

**Comment by sadraddini** [comment]
+@cohnt for feature review, please!

**Comment by sadraddini** [comment]
+@rpoyner-tri for platform review please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: minor test requests

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21849#-:-O5KBwziDoLRg4Lw7lEd:b6f22zc)* status: 2 unresolved discussions

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 565 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21849#-O5KAusmDjIVTZxevCDd:-O5KAusmDjIVTZxevCDe:b-nzuc4r) ([raw file](https://github.com/RobotLocomotion/drake/blob/2caf84c3b946f8631a60e4ff73f3df9038ed0ae7/bindings/pydrake/geometry/test/optimization_test.py#L565)):*
> ```Python
>         empty_hpolyhedron = mut.HPolyhedron(np.array([[1, 0], [-1, 0]]),
>                                             np.array([1, -2]))
>         convex_hull = mut.ConvexHull([point, h_box, empty_hpolyhedron],
> ```

nit one of the constructor calls should use the `sets` parameter name, to ensure it is spelled right in bindings.
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 571 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21849#-O5KBLsK8S7ymm3EYIgo:-O5KBLsL2y2IYE1nG4I5:bbzpbhv) ([raw file](https://github.com/RobotLocomotion/drake/blob/2caf84c3b946f8631a60e4ff73f3df9038ed0ae7/bindings/pydrake/geometry/test/optimization_test.py#L571)):*
> ```Python
>         self.assertEqual(convex_hull.ambient_dimension(), 2)
>         self.assertEqual(convex_hull.num_elements(), 3)
>         self.assertIsInstance(convex_hull.element(0), mut.Point)
> ```

nit one of the `element` calls should use the `index` parameter name -- same reasoning as above.

**Review by cohnt — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21849)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

**Comment by jwnimmer-tri** [comment]
@sadraddini please remember that you need to clean up the commit message when you're merging and using the "squashing now" label.  We don't want "test argument name in binding" spam in the commit body.

**Comment by sadraddini** [comment]
I thought I just removed the excessive message lines in Reviewable. How can I fix now?

**Comment by jwnimmer-tri** [comment]
After the merge happens, it's not possible to edit it.

**Pull request merged**
