### PR TITLE
Fixing TSan Bug in drake_lcm_test

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Two threads are accessing channel_ variable, i.e. the channel name.  The listener thread is writing it using callback ( 153 )  and the main thread is reading it [ return channel_;  ] :

https://github.com/RobotLocomotion/drake/blob/master/drake/lcm/test/drake_lcm_test.cc#L153-L168

The data race seems benign and TSan seems to let us be if we make sure that the reading of the variable is mutually exclusive.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5796)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot  linux-clang-experimental-memcheck-tsan please

**Comment by david-german-tri** [comment]
:lgtm: nice

FYI, Reviewable runs on the "Assignees" field.  "Reviewers" is for GitHub reviews, which we don't use.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-:-KhT5x0CEfuwCkb4Ca91:bqht6vh)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796)*

**Comment by david-german-tri** [comment]
:lgtm_cancel: @jwnimmer-tri points out that I was sloppy here, see comments below.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/lcm/test/drake_lcm_test.cc, line 154 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhT85LEu3SHwns5Enx5:-KhT85LEu3SHwns5Enx6:bveknna) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc28840e117bb40ec34b64348adb667e0ee089a/drake/lcm/test/drake_lcm_test.cc#L154)):*
> ```cpp
>       int message_size) override {
>     channel_ = channel;
>     std::lock_guard<std::mutex> lock(message_mutex_);
> ```

Move up one line?

---

*[drake/lcm/test/drake_lcm_test.cc, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhT80BZK-YKlOq5-Bd8:-KhT80BZK-YKlOq5-Bd9:b-xcl0l) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc28840e117bb40ec34b64348adb667e0ee089a/drake/lcm/test/drake_lcm_test.cc#L168)):*
> ```cpp
>   // Returns the channel on which the most recent message was received.
>   const std::string& get_receive_channel() {
>     std::lock_guard<std::mutex> lock(message_mutex_);
> ```

Since this method returns a reference, this lock isn't actually effective; would recommend returning a value instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-:-KhT7xMaoYVPkTfRsahq:b-2eopje)*

**Comment by m-chaturvedi** [comment]
I had tried it with moving the mutex one line and returning by value.  Individually they didn't seem to work.  Let me try them together.

**Comment by m-chaturvedi** [comment]
I tried it after shifting the mutex and returning by value.  As is indicated here:
https://gist.github.com/m-chaturvedi/6dbcc3aa10d75ef86777dd9a2d4ccfbf/revisions

I still see TSan complaining.  The mutex(es) at 153 and 161 seem somewhat extraneous as well, if my understanding is right, since we are spawning only one listener thread, correct?  So, if we need to have mutex(es) for one listener thread for TSan to pass then why wouldn't we for the main thread...

**Comment by david-german-tri** [comment]
The remaining tsan complaints don't appear related to `channel_`.  I'm trying to debug them now.

**Comment by david-german-tri** [comment]
@m-chaturvedi, are you on Ubuntu Trusty?  From Slack: At least one of the remaining tsan complaints that I'm experiencing comes from the COW string implementation in libstdc++ prior to gcc5.  

There's another complaint I haven't investigated yet, which may or may not be the same thing.

Regardless of all of that, I think this PR is a strict improvement as revised, so I'll LGTM it once you confirm you are not seeing `channel_` related errors anymore either.

BTW, the `--runs_per_test` flag to Bazel is useful for nondeterministic bugs, e.g.

```
bazel test --copt "-g" --runs_per_test=100 --config=tsan  //drake/lcm:drake_lcm_test
```

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri  :lgtm: pending one nit.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/lcm/test/drake_lcm_test.cc, line 167 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhUcqgimfLIFthVofMU:-KhUcqgjTvDq7fJtvhL7:b-4zv7u8) ([raw file](https://github.com/robotlocomotion/drake/blob/805af3d087be624bf5fe295640786ea6f0a6b291/drake/lcm/test/drake_lcm_test.cc#L167)):*
> ```cpp
> 
>   // Returns the channel on which the most recent message was received.
>   const std::string get_receive_channel() {
> ```

BTW Don't put `const` on return-by-value; its meaningless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-:-KhUcnOj3VBdyLiMmgRT:b2gtuhr)*

**Comment by david-german-tri** [comment]
> There's another complaint I haven't investigated yet, which may or may not be the same thing.

Update: it's not.

So, to summarize, it appears there are at least three distinct thread safety problems in this file:

- The `channel_` locking issue, which this PR fixes.

- The `coord` string COW issue, which appears on Trusty and not Xenial, and should probably be suppressed.

- Some as yet undiagnosed issue, which appears on both Trusty and Xenial.

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-clang-experimental-memcheck-tsan please

**Comment by david-german-tri** [comment]
FYI - when you've addressed individual comments, you can reply `Done` in the reviewable.io UI.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/lcm/test/drake_lcm_test.cc, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-Khgk8qRQgjSy2sFEysO:-Khgk8qRQgjSy2sFEysP:b-yj57ii) ([raw file](https://github.com/robotlocomotion/drake/blob/d0554427e7fb495cf03e3f70fee50457548718e4/drake/lcm/test/drake_lcm_test.cc#L55)):*
> ```cpp
>     // COW is not followed by g++-5 and the loop may be removed when Trusty
>     // support is terminated.
>     for(size_t i =0; i < received_message_.coord.size(); ++i)
> ```

BTW weird formatting here.

---

*[drake/lcm/test/drake_lcm_test.cc, line 171 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhgkJhH7T5omHgTylel:-KhgkJhH7T5omHgTylem:b-dhhkk8) ([raw file](https://github.com/robotlocomotion/drake/blob/d0554427e7fb495cf03e3f70fee50457548718e4/drake/lcm/test/drake_lcm_test.cc#L171)):*
> ```cpp
>     std::lock_guard<std::mutex> lock(message_mutex_);
>     message_copy = received_message_;
> ```

Please duplicate the comment here.

---

*[drake/lcm/test/drake_lcm_test.cc, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhgkEeorwF-zKBx5xYv:-KhgkEeorwF-zKBx5xYw:b-yj57ii) ([raw file](https://github.com/robotlocomotion/drake/blob/d0554427e7fb495cf03e3f70fee50457548718e4/drake/lcm/test/drake_lcm_test.cc#L172)):*
> ```cpp
>     message_copy = received_message_;
> 
>     for(size_t i =0; i < received_message_.coord.size(); ++i)
> ```

BTW weird formatting here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-:-KhgkMrOBuekv01k8-YC:bbsgv2o)*

**Comment by m-chaturvedi** [comment]
*[drake/lcm/test/drake_lcm_test.cc, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-Khgk8qRQgjSy2sFEysO:-Khgy_1oum9kHdTnIm04:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0554427e7fb495cf03e3f70fee50457548718e4/drake/lcm/test/drake_lcm_test.cc#L55)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW weird formatting here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796)*

**Comment by m-chaturvedi** [comment]
*[drake/lcm/test/drake_lcm_test.cc, line 154 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhT85LEu3SHwns5Enx5:-Khgykwhhyh-CFSIHQ6p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc28840e117bb40ec34b64348adb667e0ee089a/drake/lcm/test/drake_lcm_test.cc#L154)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Move up one line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796)*

**Comment by m-chaturvedi** [comment]
*[drake/lcm/test/drake_lcm_test.cc, line 171 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhgkJhH7T5omHgTylel:-KhgynOqZ03R4Ch-1jMP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0554427e7fb495cf03e3f70fee50457548718e4/drake/lcm/test/drake_lcm_test.cc#L171)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Please duplicate the comment here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796)*

**Comment by m-chaturvedi** [comment]
*[drake/lcm/test/drake_lcm_test.cc, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhT80BZK-YKlOq5-Bd8:-Khgyrf5FNtq6r4ObYky:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc28840e117bb40ec34b64348adb667e0ee089a/drake/lcm/test/drake_lcm_test.cc#L168)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Since this method returns a reference, this lock isn't actually effective; would recommend returning a value instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796)*

**Comment by m-chaturvedi** [comment]
*[drake/lcm/test/drake_lcm_test.cc, line 167 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhUcqgimfLIFthVofMU:-Khgyt-ZHEfp6fIVPvqR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/805af3d087be624bf5fe295640786ea6f0a6b291/drake/lcm/test/drake_lcm_test.cc#L167)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Don't put `const` on return-by-value; its meaningless.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796)*

**Comment by m-chaturvedi** [comment]
*[drake/lcm/test/drake_lcm_test.cc, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-KhgkEeorwF-zKBx5xYv:-Khgyub_Z2LCCFH-Sny_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0554427e7fb495cf03e3f70fee50457548718e4/drake/lcm/test/drake_lcm_test.cc#L172)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW weird formatting here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796)*

**Comment by david-german-tri** [comment]
:lgtm: - :shipit: once CI passes!

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5796#-:-Khh-nDRWecKe2ntpbjl:b2kdt7m)*

**Pull request merged**
