### PR TITLE
pybind: Synchronize with RobotLocomotion/pybind11#9.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
See RobotLocomotion/pybind11#9

~NOTE: This will be updated once the above PR merges.~

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7890)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for feature and platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7890#-:-L4rK84snn03Eg8klItu:b-waowit)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by soonho-tri** [comment]
:lgtm: (Please check the CI and merge it when it's ready)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7890#-:-L4rKcLMT_fNDzrY9KoE:b-80gve1)*

**Comment by soonho-tri** [comment]
CI All passed.

**Pull request merged**
