### PR TITLE
Deprecate the numpy repository

### LINKED ISSUE #8544: Remove `@numpy` repository
From what I understand, `pybind11` does not need `numpy` headers as it a separate ABI (not through `ld.so`), which effectively "links" the functions via dictionaries in Python that store the relevant pointers in capsules, and locks constants by an API guarantee in the documentation.

Because of this, we don't really need `@numpy` as a C++ dependency; it's existence is effectively guaranteed by `install_prereqs.sh`.

@rdeits Can I ask if there was any reason in particular for keeping these headers around? Since @m-chaturvedi submitted an updated patch which uses the above ABI style, it shouldn't be needed for `dtype=object` stuff.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #8544.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14116)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

+@sammy-tri for platform review, please!

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14116#-:-MI-YEIV5OmQPMiHbI-E:b-3v5my6)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14116#-:-MI-vYfaAE0_E91eCXlN:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),EricCousineau-TRI(platform)

**Comment by jwnimmer-tri** [comment]
@sammy-tri or @EricCousineau-TRI could you patch Anzu for this deprecation?

**Comment by EricCousineau-TRI** [comment]
I've got it!

**Pull request merged**
