### PR TITLE
Improve error message for unsupported geometries in proximity engine.

### PR DESCRIPTION
**Pull request by RussTedrake**
Now it points users to the supported geometry tables. Also fixes up a few errant footnotes in those geometry tables.

+@damrongguoy for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19275)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
I'm reviewing it now.  

Summon @SeanCurtis-TRI for more eyes.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-:-NTubQ3N19E0asshvnXM:bh0g8u3)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-:-NTukxYv9O0xT1GiMMSU:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`geometry/query_object.h` line 544 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-NTudJOUBJb-DMoN5Bv2:-NTudJOUBJb-DMoN5Bv3:b29ct5q) ([raw file](https://github.com/RobotLocomotion/drake/blob/080fd4cb9c8e720c8a46ca6d295b0e5b1ff907b7/geometry/query_object.h#L544)):*
> ```objc
>    | HalfSpace | throwsᵃ |  throwsᵃ | throwsᵃ |  throwsᵃ  |  throwsᵃ   |   throwsᵃ  |  ░░░░░  |  ░░░░░  |
>    | Mesh      |    ᶜ    |    ᶜ     |    ᶜ    |     ᶜ     |      ᶜ     |      throwsᵃ  |    ᶜ    |  ░░░░░  |
>    | Sphere    |  2e-15  |  throwsᵇ | throwsᵇ |  throwsᵇ  |  throwsᵇ   |    2e-15   |    ᶜ    |  5e-15  |
> ```

spacing



_Suggestion:_
```objc
   | HalfSpace | throwsᵃ |  throwsᵃ | throwsᵃ |  throwsᵃ  |  throwsᵃ   |   throwsᵃ  |  ░░░░░  |  ░░░░░  |
   | Mesh      |    ᶜ    |    ᶜ     |    ᶜ    |     ᶜ     |      ᶜ     |   throwsᵃ  |    ᶜ    |  ░░░░░  |
   | Sphere    |  2e-15  |  throwsᵇ | throwsᵇ |  throwsᵇ  |  throwsᵇ   |    2e-15   |    ᶜ    |  5e-15  |
```
___
*[`geometry/query_object.h` line 558 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-NTudkjpDKL5679JKvhL:-NTudkjpDKL5679JKvhM:b29ct5q) ([raw file](https://github.com/RobotLocomotion/drake/blob/080fd4cb9c8e720c8a46ca6d295b0e5b1ff907b7/geometry/query_object.h#L558)):*
> ```objc
>    | HalfSpace | throwsᵃ | throwsᵃ  | throwsᵃ |  throwsᵃ  |   throwsᵃ  |   throwsᵃ  |  ░░░░░  |  ░░░░░  |
>    | Mesh      |    ᶜ    |    ᶜ     |    ᶜ    |     ᶜ     |      ᶜ     |      throwsᵃ     |    ᶜ    |  ░░░░░  |
>    | Sphere    | throwsᵈ | throwsᵈ  | throwsᵈ |  throwsᵈ  |   throwsᵈ  |    throwsᵈ  |    ᶜ    | throwsᵈ |
> ```

spacing



_Suggestion:_
```objc
   | HalfSpace | throwsᵃ | throwsᵃ  | throwsᵃ |  throwsᵃ  |   throwsᵃ  |   throwsᵃ  |  ░░░░░  |  ░░░░░  |
   | Mesh      |    ᶜ    |    ᶜ     |    ᶜ    |     ᶜ     |      ᶜ     |   throwsᵃ  |    ᶜ    |  ░░░░░  |
   | Sphere    | throwsᵈ | throwsᵈ  | throwsᵈ |  throwsᵈ  |   throwsᵈ  |   throwsᵈ  |    ᶜ    | throwsᵈ |
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19275)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`geometry/proximity/penetration_as_point_pair_callback.cc` line 155 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-NTun_Ih4OzZs-jSJghZ:-NTun_Ih4OzZs-jSJgh_:b-z0ox0j) ([raw file](https://github.com/RobotLocomotion/drake/blob/080fd4cb9c8e720c8a46ca6d295b0e5b1ff907b7/geometry/proximity/penetration_as_point_pair_callback.cc#L155)):*
> ```cpp
>   throw std::logic_error(fmt::format(
>       "PenetrationAsPointPair() cannot be evaluated for shapes '{}' and '{}' "
>       "for scalar type {}",
> ```

BTW, want this one too or not?



_Suggestion:_
```cpp
      "PenetrationAsPointPair() cannot be evaluated for shapes '{}' and '{}' "
      "for scalar type {}. See the documentation for "
        "QueryObject::ComputePointPairPenetration() for the full status of "
        "supported geometries.",
```

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-:-NTxHfLl2y_h5Sg1-kkf:bppyoqq)* status: LGTM missing from assignee sherm1(platform) (waiting on @DamrongGuoy and @sherm1)

___
*[`geometry/query_object.h` line 544 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-NTudJOUBJb-DMoN5Bv2:-NTxEgiV93tlAVykcwe9:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/080fd4cb9c8e720c8a46ca6d295b0e5b1ff907b7/geometry/query_object.h#L544)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

spacing
</blockquote></details>

Done.
___
*[`geometry/query_object.h` line 558 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-NTudkjpDKL5679JKvhL:-NTxEm2p2aw0SeyoEJ9m:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/080fd4cb9c8e720c8a46ca6d295b0e5b1ff907b7/geometry/query_object.h#L558)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

spacing
</blockquote></details>

Done.
___
*[`geometry/proximity/penetration_as_point_pair_callback.cc` line 155 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-NTun_Ih4OzZs-jSJghZ:-NTxF-9h6Dn-uYtD5XRI:b-l5r1cy) ([raw file](https://github.com/RobotLocomotion/drake/blob/080fd4cb9c8e720c8a46ca6d295b0e5b1ff907b7/geometry/proximity/penetration_as_point_pair_callback.cc#L155)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, want this one too or not?
</blockquote></details>

Done.  Thanks.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm; -- one unresolved discussion

> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-:-NTyLmE4Ap55GGYjc3yd:b-djv7ug)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake)

**Review by sherm1 — COMMENTED** [review]
Whoops :lgtm: I meant!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-:-NTyPeVg46GICR3Klzsu:b-hxznd6)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Given Russ's limited availability and the fact that the discussion is a cosmetic one. I'm content to dismiss it and allow merging.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-:-NTyQGmEDA_cWxYeRhyJ:b-w6vx7z)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks, @jwnimmer-tri. I thought such was the case, but a quick google didn't reveal it.  :-/

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19275#-:-NTz6eRK7wb85IaThqTe:b-8xjgdg)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
In the PR page, click on **Files changed** tab.  Then, on the file you want to edit use the **...*** and chose **Edit**.

image

image

**Comment by SeanCurtis-TRI** [comment]
Ahhhh....right. Thanks!

**Pull request merged**
