### PR TITLE
[examples] Move punyo files into drake_models

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Ditch the "models" subdir (moving spatula up one level).

Remove unwanted install rules for these files.

Fix image naming for consistency.

[workspace] Upgrade drake_models to latest commit.

Twin PR: https://github.com/RobotLocomotion/models/pull/53

Towards #13942.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21231)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy for feature review, please.

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

CC: @joemasterjohn 

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21231#-:-NuQTM4D4WJooP9uEjPd:b50aja4)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`examples/hydroelastic/spatula_slip_control/BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21231#-NuQQ1f332HCmnMys-Ah:-NuQQ1f44tzq28RSiKKQ:bh0dj2r) ([raw file](https://github.com/RobotLocomotion/drake/blob/669f15f1ff7c3481bf22fd1dd24d03facad14a10/examples/hydroelastic/spatula_slip_control/BUILD.bazel#L26)):*
> ```Starlark
>     data = [
>         ":models",
>         "//manipulation/models/wsg_50_description:models",
> ```

BTW, we don't need this line anymore.

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per schedule (tomorrow), please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21231#-:-NuQbyl4Ej4MDC7c3Ct6:b-75o053)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
-@rpoyner-tri +@ggould-tri for platform review per schedule (tomorrow), please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21231#-:-NuQdwgb3S5VQzqPu6GY:b-g87720)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21231#-:-NuU6zac61yTEiu6uRIu:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),DamrongGuoy

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21231)* status: 1 unresolved discussion

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21231#-NuU84eYBbhOTFPws849:-NuU84eYBbhOTFPws84A:b-ebd2w7) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f88e34b1dedbc36a629533d9b237245ed0bd339/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "b2f1a5de046d0b0d27dd5b8f09020addc9a19280",
> ```

Working

Needs real sha

**Pull request merged**
