### PR TITLE
Minimal distance constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10456)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
___
*[multibody/inverse_kinematics/inverse_kinematics.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10456#-LWppt_-8ZZEgh9l9Xei:-LWppt_-8ZZEgh9l9Xej:b-ubahvd) ([raw file](https://github.com/robotlocomotion/drake/blob/34fce3c01933c6e99e679e12d2ec870a7c8f00a6/multibody/inverse_kinematics/inverse_kinematics.h#L62)):*
> ```objc
>    * plant->Finalize(scene_graph);
>    * // 7. Connect plant to SceneGraph, and vice versa
>    * builder.Connect(
> ```

Can you replace all of this boilerplate with `AddPlantAndSceneGraph`?

**Comment by EricCousineau-TRI** [comment]
Sorry - sputtering comments here and there:
In the overview, is there an issue that this relates or will resolve? If so, can you add it?
(If not, meh for now.)

**Comment by jwnimmer-tri** [comment]
___
*[multibody/inverse_kinematics/minimal_distance_constraint.cc, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10456#-LWpq4Qw8v9L838PAZ-R:-LWprG5m3QiYlfscyPCP:b-p8v819) ([raw file](https://github.com/robotlocomotion/drake/blob/34fce3c01933c6e99e679e12d2ec870a7c8f00a6/multibody/inverse_kinematics/minimal_distance_constraint.cc#L53)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Is there a way to ensure that `geometry_query_input_port_` is actually registered as well?

If there is / isn't, I'd be happy to try and write a function, something like `HasSceneGraphConnected(plant)`, that will return true if both it has a scene graph and the query port is connected.
\cc @sherm1
</blockquote></details>

Do we expect it to be a common problem that the user would fail to connect this port and when they fail to do so the error message would be too obscure without a fail-fast check during construction?

You can't (and shouldn't) really interrogate the Diagram to check.  Perhaps you could call `EvalAbstractInput` here to make sure its non-nullptr, but then you need to UpdateContextFromConfiguration first and I'm not sure how tractable that is to do in general (without being given y).  I'll posit that adding a nullptr check and diagnostic during DoEvalGeneric would be plenty good enough.

**Comment by EricCousineau-TRI** [comment]
ah, I think it's just lagging behind #10494.
@drake-jenkins-bot retest this please.

**Pull request merged**
