### PR TITLE
Added dictionary of LCM translators that's indexed by channel name.

### PR DESCRIPTION
**Pull request by liangfok**
The translator to use can now be determined based on the channel name using a dictionary that the user defines.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2871)

### CODE REVIEW

**Comment by liangfok** [comment]
Since @jwnimmer-tri came up with this idea, +@jwnimmer-tri for feature review.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-:-KN9NF26zNhhtOCZlL9b:1164091523)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9jgO9ODLzMCdhxXRY:-KN9jgO9ODLzMCdhxXRZ:384470636) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L3)):*
> ```objc
> #pragma once
> 
> #include <map>
> ```

Missing include `<memory>` and `<string>`.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 8 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9hM8w4nOItChdd9Qk:-KN9hM8w4nOItChdd9Ql:585793570) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L8)):*
> ```objc
> 
> #include "drake/drakeLCMSystem2_export.h"
> #include "drake/systems/framework/basic_vector.h"
> ```

Unused, I think.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 9 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9j_jYdafUiU2OmgxH:-KN9j_jYdafUiU2OmgxI:585793570) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L9)):*
> ```objc
> #include "drake/drakeLCMSystem2_export.h"
> #include "drake/systems/framework/basic_vector.h"
> #include "drake/systems/framework/context.h"
> ```

Unused, I think.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 10 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9j_PlbHmZ4wQ7Q5fd:-KN9j_PlbHmZ4wQ7Q5fe:585793570) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L10)):*
> ```objc
> #include "drake/systems/framework/basic_vector.h"
> #include "drake/systems/framework/context.h"
> #include "drake/systems/framework/system_interface.h"
> ```

Unused, I think.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 12 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9jYaTz5cOU7Of22yC:-KN9jYaTz5cOU7Of22yD:585793570) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L12)):*
> ```objc
> #include "drake/systems/framework/system_interface.h"
> #include "drake/systems/lcm/lcm_and_vector_interface_translator.h"
> #include "drake/systems/lcm/lcm_receive_thread.h"
> ```

Unused, I think.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 35 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9hbAKTXqD8sH4FuqI:-KN9hbAKTXqD8sH4FuqJ:-1180745160) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L35)):*
> ```objc
>    *
>    * @param[in] channel_name The name of the LCM channel. Messages sent on and
>    * received from this channel are assumed to be compatibl with @p translator.
> ```

Typo _compatibl_.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 53 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9hWh5hc1ZPUhg9XZe:-KN9hWh5hc1ZPUhg9XZf:-1294514769) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L53)):*
> ```objc
> 
>   /**
>    * Returns a reference to the translator to use with the specified channel.
> ```

In API docs here, please reassure the caller that the reference remains valid for the lifetime of this class.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 54 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9jA_zFykrzYXDkgDO:-KN9jA_zFykrzYXDkgDP:975063837) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L54)):*
> ```objc
>   /**
>    * Returns a reference to the translator to use with the specified channel.
>    */
> ```

In API docs here, please promise what happens when the name is unknown.

---

*[drake/systems/lcm/test/lcm_publisher_system_test.cc, line 188 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9ko4yZEH2ZvTjzVn2:-KN9ko4yZEH2ZvTjzVn3:715772240) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/test/lcm_publisher_system_test.cc#L188)):*
> ```cpp
>   ::lcm::LCM lcm;
>   std::string channel_name = "drake_system2_lcm_test_publisher_channel_name";
>   TranslatorBetweenLcmtDrakeSignal translator(kDim);
> ```

Unused variable?.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks.

---

Review status: 6 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9jgO9ODLzMCdhxXRY:-KN9nml70xfNbtgDcMn4:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing include `<memory>` and `<string>`.
</details>
Done.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 8 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9hM8w4nOItChdd9Qk:-KN9noqJW-f6yCLvCaFi:1740281843) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused, I think.
</details>
Removed.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 9 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9j_jYdafUiU2OmgxH:-KN9nqgIriTNUab2gzL5:1740281843) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused, I think.
</details>
Removed.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 10 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9j_PlbHmZ4wQ7Q5fd:-KN9ns50JU_CQNQw7Cxv:1740281843) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused, I think.
</details>
Removed.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 12 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9jYaTz5cOU7Of22yC:-KN9nu1L6XY4i4XVzPB6:1740281843) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused, I think.
</details>
Removed.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 35 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9hbAKTXqD8sH4FuqI:-KN9nyv4L4fOhNGumGBG:676635175) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Typo _compatibl_.
</details>
Done

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 53 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9hWh5hc1ZPUhg9XZe:-KN9oyhuRZkMVwFbGgyr:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> In API docs here, please reassure the caller that the reference remains valid for the lifetime of this class.
</details>
Done.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 54 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9jA_zFykrzYXDkgDO:-KN9pP7TxNeXLpsuewrE:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/lcm_translator_dictionary.h#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> In API docs here, please promise what happens when the name is unknown.
</details>
Done.

---

*[drake/systems/lcm/test/lcm_publisher_system_test.cc, line 188 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KN9ko4yZEH2ZvTjzVn2:-KN9piCMqR-QeoQL9WMu:1740281843) ([raw file](https://github.com/robotlocomotion/drake/blob/4e7c1a72c14fe54bc932620f974f31d774acb8bb/drake/systems/lcm/test/lcm_publisher_system_test.cc#L188)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused variable?.
</details>
Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-:-KN9pjeOPGqVMTcuBC25:701516011)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-:-KN9taKrAmWrgTsjS703:1417088721)*

**Comment by liangfok** [comment]
Since this PR touches System 2.0 components +@david-german-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-:-KN9tjzZ2UlVoewfNFT3:1236739691)*

**Comment by liangfok** [comment]
@jwnimmer-tri I made one change to the constructor of `LcmPublisherSystem`. PTAL.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871)*

**Comment by liangfok** [comment]
Thanks. Now waiting for @david-german-tri for platform review / merge.

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 2 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KND98ld1EOS3C_8xgz7:-KND98lexuFTiOBdManb:383335428) ([raw file](https://github.com/robotlocomotion/drake/blob/123e7c746af3eb1643844a6fab199af4be89cbc0/drake/systems/lcm/lcm_translator_dictionary.h#L2)):*
> ```objc
> #pragma once
> ```

Why no test coverage for this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/lcm/lcm_translator_dictionary.h, line 2 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KND98ld1EOS3C_8xgz7:-KND9KRkikCCdqWwXsYx:2094027660) ([raw file](https://github.com/robotlocomotion/drake/blob/123e7c746af3eb1643844a6fab199af4be89cbc0/drake/systems/lcm/lcm_translator_dictionary.h#L2)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why no test coverage for this file?
</details>
The non-exceptional cases are covered by unit tests for the related publisher / subscriber classes (including direct calls to e.g. HasTranslator).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 2 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KND98ld1EOS3C_8xgz7:-KND9jkar5io_RfYuOvG:924016368) ([raw file](https://github.com/robotlocomotion/drake/blob/123e7c746af3eb1643844a6fab199af4be89cbc0/drake/systems/lcm/lcm_translator_dictionary.h#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The non-exceptional cases are covered by unit tests for the related publisher / subscriber classes (including direct calls to e.g. HasTranslator).
</details>
OK.  I'd consider adding some anyway, but will leave it to the author.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-:-KND9qE1KAhMcMt1wR8W:1417088721)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 2 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KND98ld1EOS3C_8xgz7:-KNDB1WooSXC6BYcZSTz:2029842852) ([raw file](https://github.com/robotlocomotion/drake/blob/123e7c746af3eb1643844a6fab199af4be89cbc0/drake/systems/lcm/lcm_translator_dictionary.h#L2)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> OK.  I'd consider adding some anyway, but will leave it to the author.
</details>
Adding unit test now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871)*

**Comment by liangfok** [comment]
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/lcm/lcm_translator_dictionary.h, line 2 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-KND98ld1EOS3C_8xgz7:-KNDHgewYoirDcqxDx1o:646442410) ([raw file](https://github.com/robotlocomotion/drake/blob/123e7c746af3eb1643844a6fab199af4be89cbc0/drake/systems/lcm/lcm_translator_dictionary.h#L2)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Adding unit test now.
</details>
I added the unit test. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2871#-:-KNDQSxj7_VH6LQhXgNe:1417088721)*

**Comment by jwnimmer-tri** [comment]
The matlab build shows a failure in `examples/Acrobot/runPassiveURDF`, which is unrelated to this PR.  Using override-merge to push this in.

**Pull request merged**
