### PR TITLE
Adding *_everything For Test Configs

### PR DESCRIPTION
**Pull request by m-chaturvedi**
In order to be able to ignore tests for specific test configurations.
Perhaps there's a more succinct solution.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6180)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review. If anyone can propose a better solution, it would it great. The `bazel.rc` file is very limited.

**Comment by jwnimmer-tri** [comment]
Probably we can move forward this way for the moment, but a refactor to consider would be to have a small python script that generated most of this boilerplate content, and then `import generated-bazel.rc` from within our `tools/bazel.rc`, and commit the `generated-bazel.rc` with a note on how to regenerate it.  (We could even have a test that confirmed the committed file and script output matched.)

I will look at these diffs tomorrow; out of steam for tonight.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6180#-:-Kl1ToBX0r-L6Avvx0-i:b-vwximf)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

Even besides a generative script, I have a few ideas to reduce copypasta, but they can wait.  I'll PR them if I find ones I like.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6180#-:-Kl5CfZw5i7n1VL0a0O3:b-ia9px3)*

**Comment by jwnimmer-tri** [comment]
I think single review is OK.

**Pull request merged**
