### PR TITLE
Textured objects

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Previously, the only textured objects allowed were for mesh objects and the texture had to be the same name as the mesh file.

This opens the door to applying textures to any of the primitives. Furthermore, the texture can be specified in either URDF or SDF (via a custom drake tag).

The textures are used *only* in rendering (RenderEngine*). Currently, arbitrary textures are *not* communicated to drake visualizer. The concept is tested in examples/scene_graph/bouncing_ball_run_dynamics.cc -- the balls now have rainbow textures.

Updates MBP so that when a "visual" geometry is introduced, pre-existing ('phong', 'diffuse_map') properties get passed along.

Finally, parsing infrastructure was modified to support deferred image validation. (After all, an image can be specified in URDF/SDF but if it isn't consumed in the system, missing the image isn't actually a problem.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12423)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
> Finally, parsing infrastructure was modified to support deferred image validation. (After all, an image can be specified in URDF/SDF but if it isn't consumed in the system, missing the image isn't actually a problem.)

For my part, it seems like if I have a broken URDF/SDF file, I want the loading operation to tell me about that up front, not hit me with it later after I'm already up and running.  What is the thought process behind deferring the error reporting?

**Comment by jwnimmer-tri** [comment]
> As noted above, just because you specified it in the URDF does not mean it's actually going to be consumed. So, should that be a failure?

Yes, it should be a failure because the file is wrong.  My normal expectation is that when I ask my software to open a data file, it tells me if there was something wrong with it right away.  In the extreme, we could avoid even opening the URDF file to start parsing its XML into the MultibodyPlant until `simulator.Initialize()` happens, but why would we do that?  The user asked us to parse a file.  If there was something wrong with it, we should tell them immediately during `AddModelFromFile`, especially when the wrongness is something directly related to the `Parser` class (i.e., package paths).

> We're not doing a real job of validating URDFs more generally (although we do implicitly get that with SDFs).

But we should be.

> It simplified my tests by making it so I didn't actually have to have files to test my parsing. I could just make sure that the resultant properties had the expected string.

It seems like there should be many other easy solutions to this, none of which involve worsening the user experience.  Either test a lower layer (where parsing is not even in effect), or for an acceptance test where parsing matters, make the input be well-formed for clarity and consistency.  I haven't looked at the new code here, but I could do that and offer specific advice if you wish.

**Comment by SeanCurtis-TRI** [comment]
To be pedantic: parsing is about syntax, not semantics. Making sure that the URDF/SDF is well structured is one thing. Making sure that the *values* make sense is something else and goes *way* beyond parsing. When I *parse* URDF, I don't expect for it to tell me I've necessarily given it a singular inertial matrix (or do I? That may be a poor example.) 

That said, I understand the appeal of validating anything that can be reasonably validated as close to the act of creation as possible. I would note that microseconds later, this unvalidated file name is fed to `SceneGraph` which promptly validates it (assuming it's used). After all, `SceneGraph` always has to validate the file name because parsing is not the only way to feed it data. It's also worth noting that I haven't "worsened" the experience for any pre-existing feature. All other URIs that we resolve are resolved with the same validation.

To be honest, the real justification for this was testing. Currently, the parsing tests are formulated in terms of of parsing the whole damn file and looking at some of the resulting artifacts. I really didn't want to create a directory structure with dummy files just to test the parsing logic. Whatever other changes I might make to the testing infrastructure to make more targeted unit tests, this tree of dummy files would be required.

So, if you feel sufficiently strongly enough about *never* reading a file attribute/value without validating that it references something valid, I will revisit the semantics, the testing, and add the dummy tree.

**Comment by jwnimmer-tri** [comment]
(I think having good mock test data is a win in any case.  It's a nice reference, at least for sunny-day cases.)

But to the point -- if the effect of calling public APIs is still to get an error, I don't mind which component throws it.  If the only change here is to change which code throws the error, I have no UX objection, as long as all reasonably-expected user call sequences still throw it.  At that point it's just a question of implementation robustness (will a future change open the door to forgetting to finish the deferred check), which I am happy to defer to a feature reviewer.

**Comment by jwnimmer-tri** [comment]
I feel strongly enough about it that I would myself PR the unit test cleanups to make it happen.

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_vtk.cc, line 232 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12423#-LuikUG7CFBEbBnWtV35:-LuikUG7CFBEbBnWtV36:bs42r03) ([raw file](https://github.com/robotlocomotion/drake/blob/9c29b01ef704166056657c2300792172fd685e0a/geometry/render/render_engine_vtk.cc#L232)):*
> ```cpp
>   // TODO(SeanCurtis-TRI): Provide control for smoothness/tessellation.
>   vtk_sphere->SetPhiResolution(50);
>   vtk_sphere->SetThetaResolution(50);
> ```

btw if you're not going to use a common SetSphereOptions anymore then you should probably also remove it from render_engine_vtk_base?

**Comment by tehbelinda** [comment]
checkpoint, still getting through the models/tests

**Comment by tehbelinda** [comment]
first pass done

**Pull request merged**
