### PR TITLE
[geometry] Parameter to select output format from mesh intersection.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Another step for issue #14579.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@rpoyner-tri for feature review please.

Changes to the code itself is minimal, but I spent so much time in refactoring GTEST into TEST_F.  I'll welcome advice on my refactoring exercise. 

I also removed many unnecessary lines from "over testing" in the past when I still learn the art of unit testing.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131#-:-MbnMBse0Up2NmZzfjEQ:b-eypkk4)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

___
*[geometry/proximity/test/mesh_intersection_test.cc, line 806 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbnNd_KDbO4nW6Z5uCa:-MbnNd_KDbO4nW6Z5uCb:bl06a5s) ([raw file](https://github.com/robotlocomotion/drake/blob/4e3fcc12c6e55017aa2bebcc94bf556fd8361029/geometry/proximity/test/mesh_intersection_test.cc#L806)):*
> ```cpp
>   auto volume_field_M = TrivialVolumeMeshField<double>(volume_M.get());
>   auto rigid_N = TrivialSurfaceMesh<double>();
>   const Bvh<Obb, SurfaceMesh<double>> bvh_rigid_N(*rigid_N);
> ```

I tried to refactor two GTEST_TEST functions to share the same test fixture. Unfortunately they use different naming schemes. This one uses `volume_M, rigid_N`, while the other one uses `mesh_S, surface_R`.  As a result, later in the code, there are many lines with tiny changes like `M` becomes `S`, and `N` becomes `R`.  I apologize to the reviewers.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 1014 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbnPZRm4vYBFZKinKzy:-MbnPZRm4vYBFZKinKzz:buns9zp) ([raw file](https://github.com/robotlocomotion/drake/blob/4e3fcc12c6e55017aa2bebcc94bf556fd8361029/geometry/proximity/test/mesh_intersection_test.cc#L1014)):*
> ```cpp
> // that some good results are correlated with all good results based on the
> // unit tests for ContactSurface.
> template<typename T>
> ```

It's used to be a template, so we can check that AutoDiffXd can compile.  Not anymore, because last month we had another test fixture specifically for AutoDiffXd.  Now this test is only `double`.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[geometry/proximity/mesh_intersection.h, line 376 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbrOkShCGBcZGV_67Ks:-MbrOkShCGBcZGV_67Kt:bvugbdh) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/mesh_intersection.h#L376)):*
> ```objc
>     const Bvh<Obb, SurfaceMesh<double>>& bvh_R,
>     const math::RigidTransform<T>& X_WR,
>     bool triangulate_polygon = true);
> ```

BTW, I'm not a huge fan of optional parameters ([GSG is grumpy on this point](https://drake.mit.edu/styleguide/cppguide.html#Default_Arguments)), nor of bool parameters (can make call sites mysterious). Since this is internal, at least we are on the hook to make the call sites legible.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 852 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbrXkd17IHxBroWFmXa:-MbrXkd28fkw0aiXRuda:bxbuhnh) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L852)):*
> ```cpp
>   RigidTransformd X_SR_;
> 
>   static constexpr double kEps_ = std::numeric_limits<double>::epsilon();
> ```

I don't think static const variables need the trailing underscore. See recent PR https://github.com/RobotLocomotion/drake/pull/15172 .
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 882 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbryQsX1wZATbYeUp9Y:-MbryQsX1wZATbYeUp9Z:btiyexb) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L882)):*
> ```cpp
> }
> 
> void MeshIntersectionFixture::VerifySampleVolumeFieldOnSurface(
> ```

BTW, it's unusual to  define fixture methods outside the declaration, but I dont' think it's necessarily wrong.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 886 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-Mbryi2U8dHx9YP3YbA9:-Mbryi2U8dHx9YP3YbAA:b-bzcihl) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L886)):*
> ```cpp
>     const unique_ptr<SurfaceMeshFieldLinear<double, double>>& e_field,
>     const vector<Vector3<double>>& grad_eS_S, bool triangulate_polygon) {
>   if (triangulate_polygon) {
> ```

BTW, consider whether i it is clearer to pack these face count checks inside this function, or do them outside, where you already know by context whether, triangulating is on or not.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 896 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-Mbrz3qF8vMLH2hzeR8t:-Mbrz3qF8vMLH2hzeR8u:bklpu84) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L896)):*
> ```cpp
>   // total area is 2 * 0.25**2 / 2 = 0.25**2.
>   const double expect_area = 0.25 * 0.25;
>   EXPECT_NEAR(expect_area, surface_S->total_area(), kEps_);
> ```

All of the assertions in this function can now potentially fire in one of two situations: triangulation on, or off. Consider using [SCOPED_TRACE()](https://google.github.io/googletest/advanced.html#adding-traces-to-assertions) to add some context information. 
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 992 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-Mbs69guCoALzl1K1_b6:-Mbs69guCoALzl1K1_b7:b-h67hz3) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L992)):*
> ```cpp
>         id_A, *field_S_, *bvh_mesh_S_, X_WS, id_B, *surface_R_,
>         *bvh_surface_R_, X_WR, triangulate_polygon);
>     EXPECT_EQ(contact_SR->id_M(), id_A);
> ```

All of the test clauses in this loop body, including those in the helper method, need disambiguation with SCOPED_TRACE() similar to the case above.

**Review by DamrongGuoy — COMMENTED** [review]
I moved the definitions of VerifySampleVolumeFieldOnSurface() and VerifyComputeContactSurfaceFromSoftRigid() into the fixture declaration.  Unfortunately it caused so many diff lines.  Sorry for inconvenience.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131#-:-Mc6zs3OAogr4QF3pbJX:b9e4t2g)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[geometry/proximity/mesh_intersection.h, line 376 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbrOkShCGBcZGV_67Ks:-Mc6ut5i5QJ9XLoALC7T:b-yz2o3b) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/mesh_intersection.h#L376)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, I'm not a huge fan of optional parameters ([GSG is grumpy on this point](https://drake.mit.edu/styleguide/cppguide.html#Default_Arguments)), nor of bool parameters (can make call sites mysterious). Since this is internal, at least we are on the hook to make the call sites legible.
</blockquote></details>

Ok. It's not an optional parameter anymore.

However, it's still bool, and I put a TODO to change bool to enum class. In addition to mesh_intersection.h, we also have mesh_plane_intersection.h and mesh_half_space_intersection.h.  I'd like to think more carefully how to share the enum class among them. 
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 852 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbrXkd17IHxBroWFmXa:-Mc6f4w513uzmdxv-kE_:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L852)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I don't think static const variables need the trailing underscore. See recent PR https://github.com/RobotLocomotion/drake/pull/15172 .
</blockquote></details>

Done. Thanks.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 882 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbryQsX1wZATbYeUp9Y:-Mc6fNvz4RS14X_4blT_:b-9dca7h) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L882)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, it's unusual to  define fixture methods outside the declaration, but I dont' think it's necessarily wrong.
</blockquote></details>

Done.  Now I define fixture methods inside the declaration.  Previously I was trying to minimize the "diff".
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 886 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-Mbryi2U8dHx9YP3YbA9:-Mc6jj3QAyBd0vP3ShkH:bp3gall) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L886)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, consider whether i it is clearer to pack these face count checks inside this function, or do them outside, where you already know by context whether, triangulating is on or not.
</blockquote></details>

Done.  Do them outside now.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 896 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-Mbrz3qF8vMLH2hzeR8t:-Mc6nF7I8uBlsk4e1XCV:b-tz1bz8) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L896)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

All of the assertions in this function can now potentially fire in one of two situations: triangulation on, or off. Consider using [SCOPED_TRACE()](https://google.github.io/googletest/advanced.html#adding-traces-to-assertions) to add some context information. 
</blockquote></details>

Done. I added SCOPE_TRACE() in the caller to this function.

Thanks for pointing me to the doc of SCOPED_TRACE().  It's very useful.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 992 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-Mbs69guCoALzl1K1_b6:-Mc6osRg9ccMy7vsyvty:b-yk4nmq) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L992)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

All of the test clauses in this loop body, including those in the helper method, need disambiguation with SCOPED_TRACE() similar to the case above.
</blockquote></details>

Done.  I added SCOPED_TRACE(). Thanks.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: some typos remain

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131#-:-McA6wiF--2BViOth5zd:b-8wwmhy)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[geometry/proximity/mesh_intersection.h, line 376 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbrOkShCGBcZGV_67Ks:-McA2ske4a4y4uB1mQ_e:b-fb4xz7) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/mesh_intersection.h#L376)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Ok. It's not an optional parameter anymore.

However, it's still bool, and I put a TODO to change bool to enum class. In addition to mesh_intersection.h, we also have mesh_plane_intersection.h and mesh_half_space_intersection.h.  I'd like to think more carefully how to share the enum class among them. 

</blockquote></details>

I think bool is ok in this case, given that you have decorated all the call sites wit a function name.. What I meant in my original comment is that external clients should not have to touch that function, so the burden of getting the signature perfect is perhaps a bit lower.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 882 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15131#-MbryQsX1wZATbYeUp9Y:-McA3Jzs3PCQNipstKuX:b-b2wx2c) ([raw file](https://github.com/robotlocomotion/drake/blob/484a009d425625a78152e25413a08bd0ea83aced/geometry/proximity/test/mesh_intersection_test.cc#L882)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  Now I define fixture methods inside the declaration.  Previously I was trying to minimize the "diff".
</blockquote></details>

It certainly made the first rev more readable, but we should be also thinking about how it will look to readers who saw only the file and not the history. Maybe this is a useful tactic for reviews of code moving?
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 932 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McA6Vcf1pV1D3sVHZ2T:-McA6Vcf1pV1D3sVHZ2U:b-gebsbf) ([raw file](https://github.com/robotlocomotion/drake/blob/23071c486ec7c16ddb90a9cd6c7f4c9bd06df60b/geometry/proximity/test/mesh_intersection_test.cc#L932)):*
> ```
> expresssed
> ```
typo
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 967 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McA6_VW25VB8rJoP8O-:-McA6_VW25VB8rJoP8O0:b-61gpyd) ([raw file](https://github.com/robotlocomotion/drake/blob/23071c486ec7c16ddb90a9cd6c7f4c9bd06df60b/geometry/proximity/test/mesh_intersection_test.cc#L967)):*
> ```
> Trianguate
> ```
typo
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 978 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McA6cqR6m0ZPcec3qzU:-McA6cqR6m0ZPcec3qzV:b-lgi2qd) ([raw file](https://github.com/robotlocomotion/drake/blob/23071c486ec7c16ddb90a9cd6c7f4c9bd06df60b/geometry/proximity/test/mesh_intersection_test.cc#L978)):*
> ```
> triangualte
> ```
typo

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[geometry/proximity/test/mesh_intersection_test.cc, line 932 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McA6Vcf1pV1D3sVHZ2T:-McARFm221mKdVP4Ihkh:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/23071c486ec7c16ddb90a9cd6c7f4c9bd06df60b/geometry/proximity/test/mesh_intersection_test.cc#L932)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> expresssed
> ```
typo
</blockquote></details>

Done. Thanks.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 967 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McA6_VW25VB8rJoP8O-:-McARLXiDP5kx-TPlBA0:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/23071c486ec7c16ddb90a9cd6c7f4c9bd06df60b/geometry/proximity/test/mesh_intersection_test.cc#L967)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> Trianguate
> ```
typo
</blockquote></details>

Done. Thanks.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 978 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McA6cqR6m0ZPcec3qzU:-McARToh6J_c83Nj9PBs:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/23071c486ec7c16ddb90a9cd6c7f4c9bd06df60b/geometry/proximity/test/mesh_intersection_test.cc#L978)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> triangualte
> ```
typo
</blockquote></details>

Done. Thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131)* status: needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, with nit about ambiguity of "triangulate" when both options involve triangles.

> Reviewed 1 of 4 files at r1, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131#-:-McB1cDh12fur5YrcUp9:b-8qzx9b)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McB1gZ2Ev_y4hKPmGhy:-McB1gZ2Ev_y4hKPmGhz:b-m3t97p) (no related file):*
nit The flag `triangulate_polygon` is super ambiguous to me.
My "internal prior" says it means decomposing polygon into triangles, but the NCH flavor turns a polygon into a "contact-equivalent" triangle, so "triangle-ifying" is present in both situations.
(Using abbreviations from here: https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-829550816)

 I had to read the code, and assume by context surrounding ` AddPolygonToMeshDataAsOneTriangle` that `triangulate_polygon = true` means that you decompose 1 polygon into 1 or more triangles (CH "regime", slower), whereas `triangulate_polygon = false` means that you transform 1 polygon into contact-equivalent triangle.

Can you choose a less ambiguous term, or just go ahead and use the enum now?

---
___
*[geometry/proximity/mesh_intersection.h, line 315 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McB0BLp-WCPWNZXx9ql:-McB0BLp-WCPWNZXx9qm:b-k2y0l4) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5c2c5d7f1019481efecbe882514040f71e0381/geometry/proximity/mesh_intersection.h#L315)):*
> ```objc
> };
> 
> // TODO(DamrongGuoy): Change the bool parameter triangulate_polygon to an
> ```

BTW +1.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 911 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McB0ULT0PmEcJiUwbv1:-McB0ULUD4xU5p8x9kC9:br48f01) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5c2c5d7f1019481efecbe882514040f71e0381/geometry/proximity/test/mesh_intersection_test.cc#L911)):*
> ```cpp
>       const RigidTransformd& X_WS) {
>     // Mesh invariants:
>     //   Meshes are the same "size" (topologically).
> ```

BTW Pure whitespace indentation on these comments are a tad distracting (odd).

Consider using `// - Indented case`, or itemize, or just remove indentation.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McB1gZ2Ev_y4hKPmGhy:-McBpVR45H10p9gjnmaE:b-npl251) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit The flag `triangulate_polygon` is super ambiguous to me.
My "internal prior" says it means decomposing polygon into triangles, but the NCH flavor turns a polygon into a "contact-equivalent" triangle, so "triangle-ifying" is present in both situations.
(Using abbreviations from here: https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-829550816)

 I had to read the code, and assume by context surrounding ` AddPolygonToMeshDataAsOneTriangle` that `triangulate_polygon = true` means that you decompose 1 polygon into 1 or more triangles (CH "regime", slower), whereas `triangulate_polygon = false` means that you transform 1 polygon into contact-equivalent triangle.

Can you choose a less ambiguous term, or just go ahead and use the enum now?
</blockquote></details>

Sorry for the confusion.  I use the enum now.

Please let me know if I should improve more documentation or anything to make it clearer.

---
___
*[geometry/proximity/mesh_intersection.h, line 315 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McB0BLp-WCPWNZXx9ql:-McBpxN6BeDSG9x88Wm2:b-j0tde2) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5c2c5d7f1019481efecbe882514040f71e0381/geometry/proximity/mesh_intersection.h#L315)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW +1.
</blockquote></details>

Done. Use the enum now.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 911 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McB0ULT0PmEcJiUwbv1:-McBqNxF693hwct1CdKD:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5c2c5d7f1019481efecbe882514040f71e0381/geometry/proximity/test/mesh_intersection_test.cc#L911)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Pure whitespace indentation on these comments are a tad distracting (odd).

Consider using `// - Indented case`, or itemize, or just remove indentation.
</blockquote></details>

Done. Thanks.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15131)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McB1gZ2Ev_y4hKPmGhy:-McCIS8A7oYLhvfnUs1R:b-b2gf1u) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Sorry for the confusion.  I use the enum now.

Please let me know if I should improve more documentation or anything to make it clearer.
</blockquote></details>

OK Looks great, thank you!

---
___
*[geometry/proximity/mesh_intersection.h, line 315 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15131#-McB0BLp-WCPWNZXx9ql:-McCIE7SE2GjqPIMnwC9:b-88e6a9) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5c2c5d7f1019481efecbe882514040f71e0381/geometry/proximity/mesh_intersection.h#L315)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done. Use the enum now.
</blockquote></details>

OK Beautiful!

**Pull request merged**
