### PR TITLE
libdrake: Add test to ensure `-ffast-math` is not present

### LINKED ISSUE #10253: Different behavior with subnormal numbers between static and shared linking (-ffast-math)
Relates #10244 - the solution there is to avoid using subnormal numbers, but I still want to understand why we have a difference in computations due to linking modality.

---
Summary: It's because of `-ffast-math` (on my machine, at least). Final repro commit:
10d2e77

---

From that discussion:
> [...] it's because something in GetNextSampleTime has markedly different between static linking and shared library linking:
> EricCousineau-TRI@f2027d6#diff-dfc5081278527b906fd0f3245d73dfd4R23

Here's the most minimal repro, which boils down to a difference in floating-point comparison between static and shared linking:
```c++
#include <cmath>

#include <iostream>
#include <limits>

int main() {
  std::cout.precision(std::numeric_limits<double>::max_digits10);
  const double zero = 0.;
  const double inf = std::numeric_limits<double>::infinity();
  const double slightly_less = std::nexttoward(0., -inf);
  const bool is_less = slightly_less < zero;
  std::cout
      << "zero: " << zero << "\n"
      << "slightly_less: " << slightly_less << "\n"
      << "is_less: " << (is_less ? "true" : "false") << "\n";
  if (!is_less) {
    std::cout << "BAD\n";
    return 1;
  }
  return 0;
}

/*
[ Output ]

$ bazel run //bindings/pydrake/systems:issue_10255_min_repro_static 
zero: 0
slightly_less: -4.9406564584124654e-324
is_less: true

$ bazel run //bindings/pydrake/systems:issue_10255_min_repro_shared 
zero: 0
slightly_less: -4.9406564584124654e-324
is_less: false
BAD

*/
```

\cc @edrumwri @sherm1 @jamiesnape

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #10253

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10764)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
Has anyone tested that when #10262 is reverted this test reports a true negative (i.e., the test fails)?

**Comment by EricCousineau-TRI** [comment]
Reverting causes a merge conflict... (`git revert --no-commit -m 1 bee6b68a`)...

Now trying to do `git checkout bee6b68a~ && git cherry-pick issue/10253`)...

**Comment by EricCousineau-TRI** [comment]
Yup, it fails. Full repro:
```
$ cd drake
$ git checkout bee6b68a~
$ git cherry-pick 7c28841c
$ bazel test //tools/install/libdrake:fast_math_test 
...
[ RUN      ] FastMathTest.SubnormalNumbers
tools/install/libdrake/test/fast_math_test.cc:18: Failure
Value of: slightly_less < zero
  Actual: false
Expected: true
```

**Comment by jwnimmer-tri** [comment]
Sounds good.  I think this is ready.

**Pull request merged**
