### PR TITLE
Revert "Google Benchmark 2-step update"

### PR DESCRIPTION
**Pull request by svenevs**
Reverts RobotLocomotion/drake#18447

Dear @rpoyner-tri CC @BetsyMcPhail @xuchenhan-tri,

 The on-call build cop, @svenevs, believes that your PR #18447 may have
 broken one or more of Drake's continuous integration builds [1]. It is
 possible to break a build even if your PR passed continuous integration
 pre-merge because additional platforms are tested post-merge.

 The specific build failures under investigation are:

- https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-continuous-mirror-to-s3/2544/consoleFull
- https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-continuous-mirror-to-s3/2545/console

```
[8:03:21 PM]  ERROR: /media/ephemeral0/ubuntu/workspace/linux-focal-unprovisioned-gcc-bazel-continuous-mirror-to-s3/_bazel_ubuntu/a6fb4949675e82424dd70d4d91d1d400/external/googlebenchmark/BUILD.bazel:29:11: no such package '@libpfm//': The repository '@libpfm' could not be resolved: Repository '@libpfm' is not defined and referenced by '@googlebenchmark//:benchmark'
```

 Therefore, the build cop has created this revert PR and started a complete
 post-merge build to determine whether your PR was in fact the cause of the
 problem. If that build passes, this revert PR will be merged 60 minutes from
 now. You can then fix the problem at your leisure, and send a new PR to
 reinstate your change.

 If you believe your original PR did not actually break the build, please
 explain on this thread.

 If you believe you can fix the break promptly in lieu of a revert, please
 explain on this thread, and send a PR to the build cop for review ASAP.

 If you believe your original PR definitely did break the build and should be
 reverted, please review and LGTM this PR. This allows the build cop to merge
 without waiting for CI results.

 For advice on how to handle a build cop revert, see [2].

 Thanks!
 Your Friendly On-call Build Cop

 [1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
 [2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18449)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
It's past Rico's working hours. Here's :lgtm: stamp. 
+(status: single reviewer ok) +(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18449#-:-NJDACFn8AdN0mGz6cFL:b8yz2kl)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Comment by xuchenhan-tri** [comment]
+@xuchenhan-tri

**Comment by svenevs** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-continuous-mirror-to-s3/2546/

I _believe_ I got this running against this PR, this special job isn't parameterized in Jenkins.

**Comment by svenevs** [comment]
Status confirmed: revert works as expected, unclear why `bazel  build --config=gcc --compilation_mode=opt //tools/workspace:mirror_to_s3` was broken by the changes (not sure what the effect of running that job locally does, it works on the commit that jenkins fails on).

I can help create jenkins jobs for future PRs to test or give directions via DM on slack (possible privacy concerns) on how to "Replay" it against a PR.

I think once CI passes we should probably just merge it.

**Comment by xuchenhan-tri** [comment]
My (very crude) understanding is that the lastest version of googlebenchmark needs `libpfm` as a dependency, which #18447 added along with its googlebenchmark upgrade. Not sure why this particular CI is failing.

**Review by BetsyMcPhail — COMMENTED** [review]
There is an experimental version of the failing job: `linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3` that can be used to test instead of the Continuous version.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18449#-:-NJDF2RE5zIt0hTtPntE:b-c4j9f5)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3 please.

**Pull request merged**
