### PR TITLE
Add value_checker and use it in Leaf classes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5303)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/BUILD, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5303#-KdkZIiySpSH_al623is:-KdkZIiySpSH_al623it:b-6vhnpx) ([raw file](https://github.com/robotlocomotion/drake/blob/560f1754b78a1c2a10d989398212220ba781f4b0/drake/systems/framework/BUILD#L68)):*
> ```Python
>     srcs = [],
>     hdrs = ["value_checker.h"],
>     linkstatic = 1,
> ```

BTW delete

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5303#-:-KdkaAz-jKafyDf64hhv:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/BUILD, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5303#-KdkZIiySpSH_al623is:-KdkbH1MDWn4XffThMH6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/560f1754b78a1c2a10d989398212220ba781f4b0/drake/systems/framework/BUILD#L68)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW delete
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5303#-:-KdkbHVQ81kPHnZMKpPx:bcav8r0)*

**Comment by ggould-tri** [comment]
:lgtm: pending one confusion below.
I am especially fond of `value_checker_test` which is awesomely clear.

---

Reviewed 4 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/leaf_system.h, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5303#-KdkrIrXxMb7Q6pqo27X:-KdkrIrYKf8aZXI3v8hb:b-2byehd) ([raw file](https://github.com/robotlocomotion/drake/blob/193d7e09aa56b61d9668aa0965db95266508a2c7/drake/systems/framework/leaf_system.h#L72)):*
> ```objc
> 
>     // Enforce some requirements on the fully-assembled Context.
>     // -- The continuous state must be contiguous, i.e., a valid BasicVector.
> ```

I am not sure what you mean by "contiguous" here, or where it is checked in the code below.

---

*[drake/systems/framework/leaf_system.h, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5303#-KdkoxLKK6ByV03v8ZCL:-KdkoxLLizAqssEkM-mC:b-xihhik) ([raw file](https://github.com/robotlocomotion/drake/blob/193d7e09aa56b61d9668aa0965db95266508a2c7/drake/systems/framework/leaf_system.h#L83)):*
> ```objc
>     // -- The numeric parameters must all be valid BasicVectors.
>     const int num_numeric_parameters = context->num_numeric_parameters();
>     for (int i = 0; i < num_numeric_parameters; ++i) {
> ```

So sad that this can't be a range-based for loop :-(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5303#-:-KdksmCHdtvaYlQMqtTQ:b-99714r)*

**Comment by jwnimmer-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/leaf_system.h, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5303#-KdkrIrXxMb7Q6pqo27X:-KdkwEmmR5VpxHg8JEMQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/193d7e09aa56b61d9668aa0965db95266508a2c7/drake/systems/framework/leaf_system.h#L72)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I am not sure what you mean by "contiguous" here, or where it is checked in the code below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5303)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/leaf_system.h, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5303#-KdkrIrXxMb7Q6pqo27X:-KdkwQ69wFbcyikreaq9:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/193d7e09aa56b61d9668aa0965db95266508a2c7/drake/systems/framework/leaf_system.h#L72)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5303)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Pull request merged**
