### PR TITLE
Implements BezierCurve::ElevateOrder()

### PR DESCRIPTION
**Pull request by RussTedrake**
A Bezier curve of degree n can be converted into a Bézier curve of degree n + 1 with the same shape. This method implements the degree/order elevation.

+@AlexandreAmice for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/test/bezier_curve_test.cc` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-NYJpwq7-70W-dXPihV8:-NYJpwq7-70W-dXPihV9:b-ooylup) ([raw file](https://github.com/RobotLocomotion/drake/blob/18830e15688013fb2ba68c7cf3a7cf7d54516cd5/common/trajectories/test/bezier_curve_test.cc#L17)):*
> ```cpp
> void CheckConvexHullProperty(const BezierCurve<double>& curve,
>                              int num_samples) {
>   return;
> ```

This return seems spurious? It ensures the method does nothing.
___
*[`common/trajectories/test/bezier_curve_test.cc` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-NYJqE2T3SqoAy8QMieb:-NYJqE2T3SqoAy8QMiec:b2ef8xu) ([raw file](https://github.com/RobotLocomotion/drake/blob/18830e15688013fb2ba68c7cf3a7cf7d54516cd5/common/trajectories/test/bezier_curve_test.cc#L63)):*
> ```cpp
>   EXPECT_TRUE(
>       CompareMatrices(curve.value(2.5), Eigen::Vector2d(1.5, 5), 1e-14));
>   EXPECT_TRUE(CompareMatrices(curve.value(0), Eigen::Vector2d(1, 3), 1e-14));
> ```

Could you check the endpoint as well?

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-:-NYO-x224PT04kULQp1y:bg7igkv)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: modulo missing test of elevating an empty curve.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-:-NYOH-AaAy3dq-1zcL86:b-q4o1x0)* status: 3 unresolved discussions

___
*[`common/trajectories/bezier_curve.cc` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-NYOFPhA5nxB0lgBZwO5:-NYOFPhA5nxB0lgBZwO6:b-wvnc0) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc8b82335b02499c6dea9f5e01e8ecbcb1d95287/common/trajectories/bezier_curve.cc#L88)):*
> ```cpp
>   }
> 
>   control_points_ = Q;
> ```

nit We can avoid some copying here.



_Suggestion:_
```cpp
control_points_ = std::move(Q);
```
___
*[`common/trajectories/bezier_curve.cc` line 89 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-NYOFTgl6-RdqEe5Gi6e:-NYOFTgl6-RdqEe5Gi6f:b-35lbgx) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc8b82335b02499c6dea9f5e01e8ecbcb1d95287/common/trajectories/bezier_curve.cc#L89)):*
> ```cpp
> 
>   control_points_ = Q;
>   order_++;
> ```

nit GSG



_Suggestion:_
```cpp
 ++order_;
```
___
*[`common/trajectories/test/bezier_curve_test.cc` line 233 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-NYOG_d572Lk0cUcpIWF:-NYOG_d572Lk0cUcpIWG:bbikhzg) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc8b82335b02499c6dea9f5e01e8ecbcb1d95287/common/trajectories/test/bezier_curve_test.cc#L233)):*
> ```cpp
>   EXPECT_TRUE(quadratic_curve_expression(1).EqualTo(pow(t, 2)));
> }
> ```

I'd like to see a unit test of ElevateOrder when called on a default-constructed BezierCurve, to check handling of the zero-size boundary condition.

As a bonus, it also seems like the default ctor doesn't have any unit tests in the first place, so it would be a kindness if you wanted to add the full set tests for that as well (calling all of the public functions on a default-constructed object).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620)* status: 1 unresolved discussion

___
*[`common/trajectories/bezier_curve.cc` line 79 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-NYPLEBb2bLyyafZ7duU:-NYPLEBb2bLyyafZ7duV:b-h4qecc) ([raw file](https://github.com/RobotLocomotion/drake/blob/08c7dfff8050827b79b887fdea7ef330c8aa0acb/common/trajectories/bezier_curve.cc#L79)):*
> ```cpp
> void BezierCurve<T>::ElevateOrder() {
>   if (order_ < 0) {
>     control_points_ = Eigen::MatrixX<T>::Zero(rows(), cols());
> ```

nit Consistency within the file (e.g., ~5 lines below).



_Suggestion:_
```cpp
MatrixX<T>
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),AlexandreAmice

___
*[`common/trajectories/bezier_curve.cc` line 79 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-NYPLEBb2bLyyafZ7duU:-NYPUtzA2dLpnFkeCtve:b-d53s0v) ([raw file](https://github.com/RobotLocomotion/drake/blob/08c7dfff8050827b79b887fdea7ef330c8aa0acb/common/trajectories/bezier_curve.cc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Consistency within the file (e.g., ~5 lines below).
</blockquote></details>

Done.  Fixed not only for consistency -- CI will fail with this spelling.  (it's one of the things I trip over regularly when developing on mac clang).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),AlexandreAmice

**Comment by jwnimmer-tri** [comment]
@RussTedrake I'll let you decide whether to let @AlexandreAmice check the new base case logic before you merge it.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620)* status: 1 unresolved discussion

___
*[`common/trajectories/bezier_curve.cc` line 78 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-NYPxZRc5JyTXs2eEb_F:-NYPxZRc5JyTXs2eEb_G:b-fiweab) ([raw file](https://github.com/RobotLocomotion/drake/blob/705ff3201f6ee59c8c8159e90826dc706dfb16d9/common/trajectories/bezier_curve.cc#L78)):*
> ```cpp
> template <typename T>
> void BezierCurve<T>::ElevateOrder() {
>   if (order_ < 0) {
> ```

I suppose the only way one could reach this is if an empty array of control points were passed? Should the constructor even allow this in the first place?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620)* status: 1 unresolved discussion

___
*[`common/trajectories/bezier_curve.cc` line 78 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-NYPxZRc5JyTXs2eEb_F:-NYPyQGBAxp2n2nB_xk9:b-8aobrh) ([raw file](https://github.com/RobotLocomotion/drake/blob/705ff3201f6ee59c8c8159e90826dc706dfb16d9/common/trajectories/bezier_curve.cc#L78)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I suppose the only way one could reach this is if an empty array of control points were passed? Should the constructor even allow this in the first place?
</blockquote></details>

FYI The default constructor does this.  See the header file:

```c++
  /** Default initializer. Constructs an empty Bézier curve over the interval
   t ∈ [0, 1].*/
  BezierCurve() : BezierCurve<T>(0, 1, MatrixX<T>()) {}
```

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19620#-:-NYVbsho9NvfgtT7xdzj:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),AlexandreAmice

**Pull request merged**
