### PR TITLE
Handle when the optimization program is empty

### PR DESCRIPTION
**Pull request by hongkai-dai**
@jamiesnape

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8647)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

---

Review status: 0 of 36 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8647#-:-LAYwsjc7lt_j0FQr5we:b-vzpjc1)*

**Comment by hongkai-dai** [comment]
+@jamiesnape for feature review please. @jwnimmer-tri for platform review please.

---

Review status: 0 of 36 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8647#-:-LAYwue7AyHfyFGtcacu:bgcuivz)*

**Comment by jamiesnape** [comment]
:lgtm:

Do we need API documentation anywhere to say the expected behavior is to return `kSolutionFound` for an empty program?

---

Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8647#-:-LAYxHx56Tp4jQpJ_g-Z:b-dym4v9)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8647)*

**Comment by jwnimmer-tri** [comment]
My apologies, this got lost in my review queue.

This proposal has a couple problems.  I will ponder other alternatives and post back here.

---

Reviewed 33 of 36 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8647#-LAuHEPG-AX2E25LTbWa:-LAuHEPG-AX2E25LTbWb:b-x0ofy2) (no related file):*
For developer convenience, we should have a test for solving an empty program which does not rely on a proprietary solver.  Perhaps a test of MP::Solver directly itself in mathematical_program_test might make sense?

---

*[solvers/mathematical_program_solver_interface.h, line 114 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8647#-LAuGP0n5S0biwz-Xd47:-LAuGP0n5S0biwz-Xd48:b-6ctqsw) ([raw file](https://github.com/robotlocomotion/drake/blob/36a1ef2f881f14b9a746bcfb7eadbf78d90372b6/solvers/mathematical_program_solver_interface.h#L114)):*
> ```objc
>   /// then return kSolutionFound directly, without calling the solver.
>   // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
>   SolutionResult Solve(MathematicalProgram& prog) const;
> ```

Classes named `Interface` are only allowed to have constructor, destructor, and pure virtual methods.  We cannot use NVI here.

I think even using a Base class here instead of Interface would also have linking problems.  I'll think and post back more.

---

*[solvers/mathematical_program_solver_interface.cc, line 38 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8647#-LAuJ-yU4tIFQHr1orG1:-LAuJ-yW0hMb862DNIIJ:bfs3e69) ([raw file](https://github.com/robotlocomotion/drake/blob/36a1ef2f881f14b9a746bcfb7eadbf78d90372b6/solvers/mathematical_program_solver_interface.cc#L38)):*
> ```cpp
> SolutionResult MathematicalProgramSolverInterface::Solve(
>     MathematicalProgram& prog) const {
>   if (prog.num_vars() == 0) {
> ```

This is a build-time dependency cycle, we're only lucking out now because the num_vars is apparently always being inlined.

(In any case, given the header file defect, this is unlikely to matter since it will move anyway.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8647#-:-LAuJPp42SOKTIpw0vGr:bwe2u5u)*

**Comment by jwnimmer-tri** [comment]
*[solvers/mathematical_program_solver_interface.cc, line 38 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8647#-LAuJ-yU4tIFQHr1orG1:-LAuLI0U0md3s826XA9n:b15jamm) ([raw file](https://github.com/robotlocomotion/drake/blob/36a1ef2f881f14b9a746bcfb7eadbf78d90372b6/solvers/mathematical_program_solver_interface.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is a build-time dependency cycle, we're only lucking out now because the num_vars is apparently always being inlined.

(In any case, given the header file defect, this is unlikely to matter since it will move anyway.)
</blockquote></details>

(Withdrawn.  Because the method is defined in the header file, its linkage is actually okay.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8647)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program_solver_interface.h, line 114 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8647#-LAuGP0n5S0biwz-Xd47:-LAuLQTKC8FoHuSw8rch:bfg33mr) ([raw file](https://github.com/robotlocomotion/drake/blob/36a1ef2f881f14b9a746bcfb7eadbf78d90372b6/solvers/mathematical_program_solver_interface.h#L114)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Classes named `Interface` are only allowed to have constructor, destructor, and pure virtual methods.  We cannot use NVI here.

I think even using a Base class here instead of Interface would also have linking problems.  I'll think and post back more.
</blockquote></details>

On second thought, I think a base class here would work.  In the library named `":mathematical_program_api"`, add files `mathematical_program_solver_base.h` and `.cc` with `class MathematicalProgramSolverBase : public MathematicalProgramSolverInterface` which has `Solve() final` and `virtual DoSolve() = 0`.  I think that the compilation and linking would still work out fine.  For this file MPSI.h, keep the comment changes but remove all code changes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8647)*

**Comment by jwnimmer-tri** [comment]
@hongkai-dai Perhaps you'd like to roll this into the future rework of MP as in #9633, instead of trying to rework this fix within the current design?

**Comment by jwnimmer-tri** [comment]
@hongkai-dai should we close this PR now?

**Pull request closed without merging**
