### PR TITLE
doc: Add `Getting Help` section

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Following up on a Slack conversation regarding the `drake` tag (which now [has a description](https://stackoverflow.com/tags/drake/info)).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8520)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@russtedrake and +@jwnimmer-tri for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-:-L9IVHnA0WVNmK9ZfulZ:bf541l5)*

**Comment by RussTedrake** [comment]
LGTM.  I paused at the mention of the drake developers slack channel, but I think it's probably ok.  
I did not build the sphinx and don't know enough about the serve_sphinx change to qualify as a reviewer for it.
Thanks!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[doc/getting_help.rst, line 33 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9IiAv70urmoCTsnd3U:-L9IiAv70urmoCTsnd3V:b-np5osa) ([raw file](https://github.com/robotlocomotion/drake/blob/91bfd223ce47c4a8df968c7bf487f1d3c456b1d9/doc/getting_help.rst#L33)):*
> ```reStructuredText
> 
> If you are actively developing with Drake and may need more active discussions,
> consider asking for access to the Drake Developers Slack Channel. Please note
> ```

how should they ask for access?  email me?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-:-L9Ii4Yd7gKqEaxCHutN:b-bfrpff)*

**Comment by RussTedrake** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/developers.rst, line 11 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9IiXfA05F1q0_KwVSi:-L9IiXfA05F1q0_KwVSj:b-7u9hi3) ([raw file](https://github.com/robotlocomotion/drake/blob/91bfd223ce47c4a8df968c7bf487f1d3c456b1d9/doc/developers.rst#L11)):*
> ```reStructuredText
>    :local:
> 
> .. _pull_request:
> ```

btw, i assume this links to the pull request?  (it looks slightly dangling here)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/developers.rst, line 11 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9IiXfA05F1q0_KwVSi:-L9IwCRPB3bq_e-YEizL:b8t83lq) ([raw file](https://github.com/robotlocomotion/drake/blob/91bfd223ce47c4a8df968c7bf487f1d3c456b1d9/doc/developers.rst#L11)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw, i assume this links to the pull request?  (it looks slightly dangling here)
</blockquote></details>

OK Yup, this anchors the reference to `` :ref:`pull_request` `` in `getting_help.rst`. I'm a little hesitant to change the heading in `developers` itself or introduce a sub-heading, though.

---

*[doc/getting_help.rst, line 33 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9IiAv70urmoCTsnd3U:-L9IwJ2H3mYQo2OAl1y0:b-63qfp4) ([raw file](https://github.com/robotlocomotion/drake/blob/91bfd223ce47c4a8df968c7bf487f1d3c456b1d9/doc/getting_help.rst#L33)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

how should they ask for access?  email me?
</blockquote></details>

Done. I've stated that they should email you, but wanted to withhold an email address (as it should be easy for them to get). Does this look OK?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[doc/getting_help.rst, line 23 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9Kwb7758rzMdzLOmf5:-L9Kwb7758rzMdzLOmf6:bc1el8h) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L23)):*
> ```reStructuredText
> ====================
> 
> If you do not find anything in these sources and your question is more usage 
> ```

BTW trailing whitespace

---

*[doc/getting_help.rst, line 25 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9KwIMH32yZMG-vRNb-:-L9KwIMH32yZMG-vRNb0:b-gajfgb) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L25)):*
> ```reStructuredText
> If you do not find anything in these sources and your question is more usage 
> oriented (e.g. asking for a tutorial or an example), or if you are unsure if it
> is due to a bug or a feature request, please
> ```

This phrasing is unclear (confused me the first time I read it).  When I originally read this, I parsed it as "your question is either a bug xor a feature request, and you don't know which of the two it is".  Reading the next stuff, I think what you meant was "your question is either (a bug or a feature request) xor (a request for user assistance").

---

*[doc/getting_help.rst, line 27 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9KwlE3AdNY2etQGowP:-L9KwlE3AdNY2etQGowQ:bnfhjzq) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L27)):*
> ```reStructuredText
> is due to a bug or a feature request, please
> `post a question on StackOverflow <https://stackoverflow.com/questions/ask?tags=drake>`_
> with the ``drake`` tag.
> ```

What is the plan for noticing and responding to questions in this forum?

(For example, should we ensure that some minimum number of developers get emailed when a new question is posted?  Should we have a sheriff that actively manages the response to questions on a rotating schedule?)

I think that the plan should be communicated to Drake developers prior to, or concurrent with, this PR merging.

---

*[doc/getting_help.rst, line 30 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9KwhKi67c9iSZFafU0:-L9KwhKi67c9iSZFafU1:bckmbwz) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L30)):*
> ```reStructuredText
> 
> If you know your question is related to a bug or a feature request, please
> `post a GitHub issue <https://github.com/RobotLocomotion/drake/issues/new>`_.
> ```

FYI To me, if this sentence was the first thing in this section, the flow would read more clearly, since it's the more conventional thing ("use issues") -- everyone understands that workflow.  The user assistance stuff takes longer to explain, so can be phrased as exceptions to the baseline of "open an issue".

---

*[doc/getting_help.rst, line 42 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9Kx_ww3MfEOgVUZmb9:-L9Kx_ww3MfEOgVUZmbA:b-e21k72) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L42)):*
> ```reStructuredText
> If you wish to contribute a bugfix or a feature, please do
> :ref:`submit a pull request <pull_request>`!
> If you are daunted by the review process, do not hestitate to ask for help!
> ```

This seems more like text that belongs in the pull_request section, rather than here.

FYI I think this text is net-negative in its value.  My intuition is that it will cause more unease than it alleviates.

---

*[doc/getting_help.rst, line 52 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9Ky1kg3c4j2AO7iOQ8:-L9Ky1kg3c4j2AO7iOQ9:bw07sob) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L52)):*
> ```reStructuredText
> page and a
> `mailing list <http://mailman.mit.edu/mailman/listinfo/drake-users>`_.
> Please use the previously listed resources for searching for and ask questions
> ```

BTW "previously listed" could be misinterpreted to refer to the "immediately previously listed" faq and mailing list.

It might be simpler to just say "Don't use these anymore" directly?

---

*[doc/serve_sphinx.py, line 19 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9Ku4dV4YqL1fZ0ILFy:-L9Ku4dV4YqL1fZ0ILFz:bixcafs) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/serve_sphinx.py#L19)):*
> ```Python
> 
> parser = argparse.ArgumentParser()
> parser.add_argument(
> ```

I'll posit that boolean options in`args` should be positive-sense.  So dest="browser" action="store_false" default=True.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[doc/getting_help.rst, line 23 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9Kwb7758rzMdzLOmf5:-L9_mXZpAnVoHNv9tn4r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW trailing whitespace
</blockquote></details>

Done.

---

*[doc/getting_help.rst, line 25 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9KwIMH32yZMG-vRNb-:-L9_mYBU5vfCOFNLGwEe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This phrasing is unclear (confused me the first time I read it).  When I originally read this, I parsed it as "your question is either a bug xor a feature request, and you don't know which of the two it is".  Reading the next stuff, I think what you meant was "your question is either (a bug or a feature request) xor (a request for user assistance").
</blockquote></details>

Done.

---

*[doc/getting_help.rst, line 27 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9KwlE3AdNY2etQGowP:-L9_mYqxCYn8ByrJINuO:bwchxpc) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What is the plan for noticing and responding to questions in this forum?

(For example, should we ensure that some minimum number of developers get emailed when a new question is posted?  Should we have a sheriff that actively manages the response to questions on a rotating schedule?)

I think that the plan should be communicated to Drake developers prior to, or concurrent with, this PR merging.
</blockquote></details>

Done. I've added some tentative policies. Would I be able to pass it by you and Russ first, and then involve the rest of the platform reviewers once we've gone through a couple iterations of it?

---

*[doc/getting_help.rst, line 30 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9KwhKi67c9iSZFafU0:-L9_mgTM5yKQ5yO-8f4a:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI To me, if this sentence was the first thing in this section, the flow would read more clearly, since it's the more conventional thing ("use issues") -- everyone understands that workflow.  The user assistance stuff takes longer to explain, so can be phrased as exceptions to the baseline of "open an issue".
</blockquote></details>

Done. Thanks!

---

*[doc/getting_help.rst, line 42 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9Kx_ww3MfEOgVUZmb9:-L9_mhkf7e4jjX647BWY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems more like text that belongs in the pull_request section, rather than here.

FYI I think this text is net-negative in its value.  My intuition is that it will cause more unease than it alleviates.
</blockquote></details>

Done.

---

*[doc/getting_help.rst, line 52 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9Ky1kg3c4j2AO7iOQ8:-L9_miux0e9lymtntUqW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/getting_help.rst#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW "previously listed" could be misinterpreted to refer to the "immediately previously listed" faq and mailing list.

It might be simpler to just say "Don't use these anymore" directly?
</blockquote></details>

Done.

---

*[doc/serve_sphinx.py, line 19 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9Ku4dV4YqL1fZ0ILFy:-L9_mpz60QO0Z7nje58c:bffaptp) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/serve_sphinx.py#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'll posit that boolean options in`args` should be positive-sense.  So dest="browser" action="store_false" default=True.
</blockquote></details>

Done. Preferred using a `bool`ish type, as I don't think `store_false` will attempt to read the value on the command-line.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/developers.rst, line 215 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9b-2pH5mDze3XTCrYK:-L9b-2pH5mDze3XTCrYL:bxa0dqu) ([raw file](https://github.com/robotlocomotion/drake/blob/7dcd9355c4f99c86df394ead239a5756caf74803/doc/developers.rst#L215)):*
> ```reStructuredText
> new link on the GitHub issue, and close the issue.
> 
> Handling User StackOverflow Questions
> ```

I don't think *all* developers should be accountable for answering newbie questions.  We *should* all be ready accept well-written bug reports or feature requests that relate to our focus areas, but I think its beyond our scope to onboard internet randos who are not part of our well-known family.

---

*[doc/developers.rst, line 221 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9b-72F8UQUD34zyCg-:-L9b-72H8dqdxAK0ckfx:b-olpo6h) ([raw file](https://github.com/robotlocomotion/drake/blob/7dcd9355c4f99c86df394ead239a5756caf74803/doc/developers.rst#L221)):*
> ```reStructuredText
> `these general instructions <https://meta.stackoverflow.com/a/336515/7829525>`_.
> 
> As an additional check, the Platform Reviewer should check
> ```

I especially don't think platform reviewers should suffer the additional burden of checking the forum.  If we want to pay people to answer Q&A, we should make it the explicit responsibility of some set of people, not to be conflated with the already-overloaded code reviewers.

I'd suggest that you take a poll and find volunteers.  If you find enough people, then that's the folks who can respond to questions (and sometime turn them into bug reports, probably).

---

*[doc/issues.rst, line 26 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9b-nlV6F_NS8CTda-c:-L9b-nlV6F_NS8CTda-d:b-8k8oqh) ([raw file](https://github.com/robotlocomotion/drake/blob/7dcd9355c4f99c86df394ead239a5756caf74803/doc/issues.rst#L26)):*
> ```reStructuredText
> 
> All GitHub issues should have an owner. The Platform Reviewer should check at
> least once per day that `all unassigned issues
> ```

FYI Maybe nixing "at least" would be okay?  I think exactly once is enough, and probably not worth accelerating?

---

*[doc/serve_sphinx.py, line 19 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520#-L9Ku4dV4YqL1fZ0ILFy:-L9b1ayP1osWlpaleriO:b6hyaf8) ([raw file](https://github.com/robotlocomotion/drake/blob/a41a171690b645128f0938481342af73a7eb27c0/doc/serve_sphinx.py#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Preferred using a `bool`ish type, as I don't think `store_false` will attempt to read the value on the command-line.
</blockquote></details>

OK I tend to agree with https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse#15008806 as a more universally understood idiom for booleans, but I guess we can live with this just as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8520)*

**Comment by RussTedrake** [comment]
Can we decide on this and make it happen?  The 6.832 piazza channel is getting some very valuable questions / highlighting usability issues that most of the developers are missing out on.  I'm going to recommend StackOverFlow to them now.  

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8520#-:-LAr_91m3yVGlhRZNVWg:b-ec9ltc)*

**Comment by jwnimmer-tri** [comment]
So I think the PR text is good enough for now.

In the hypothetical that we merge this PR, which directs users to post questions on SO, but the Drake developers are not subscribed there and/or do not respond in a timely manner, I am not sure why that is better than the status quo.  In order to merge this PR, I think we need to have confidence that SO is going to be monitored and responded to assiduously.  If the answer is that Eric and Russ have agreed to keep up with the monitoring task on their own, then I am fine to merge.  Both of them affirmatively stating here that they accept that responsibility would satisfy me.

@EricCousineau-TRI and @RussTedrake is it each your intent to monitor SO no less than once daily, and to respond to and/or facilitate answers for questions posted there?

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8520#-:-LAsGw_A6TbCXY-JrFMr:b-s4ktpr)*

**Comment by EricCousineau-TRI** [comment]
Yes, I agree to it, and can list my name in the documentation.

@RussTedrake Can I ask if you're up for the same?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8520#-:-LAt3aZZ2f9_KYORBGsE:b1br8ha)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Comment by EricCousineau-TRI** [comment]
Added our names to it. Russ, can I ask if I can get your LGTM?

And given that these changes namely affect Russ and me, do we need all platform reviewers to review, or can we merge it with the current set of reviewers?

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8520#-:-LAthWZb6DTT27oQnaCJ:b-61apnq)*

**Comment by jwnimmer-tri** [comment]
I think its OK with current reviewers only.

I already added an agenda item to the next platform reviewer monthly to discuss the "Monitor for unassigned issues" new requirement documented this PR.  We can revert that portion later if the meeting doesn't like it for some reason.

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8520#-:-LAtziMlAky8SYhAdH17:bnfp4nl)*

**Pull request merged**
