### PR TITLE
Add velocity support to PoseAggregator and PoseBundle.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jadecastro for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5609)

### CODE REVIEW

**Comment by jadecastro** [comment]
A couple comments. :lgtm: 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/rendering/frame_velocity.h, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-KfxTviaA07txD7XtZnh:-KfxTviaA07txD7XtZni:byfk6i6) ([raw file](https://github.com/robotlocomotion/drake/blob/46783292335c2a8d245a988a7e92e8a4a0198fac/drake/systems/rendering/frame_velocity.h#L30)):*
> ```objc
>   // fear of object slicing. This is useful for including FrameVelocity in an
>   // AbstractValue, such as PoseBundle.
>   FrameVelocity(const FrameVelocity<T>& other);
> ```

BTW, could the `DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN` macro be used here instead? 

---

*[drake/systems/rendering/pose_bundle.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-KfxWvVFyPKNIugnxt-W:-KfxWvVFyPKNIugnxt-X:b-yl3zrq) ([raw file](https://github.com/robotlocomotion/drake/blob/46783292335c2a8d245a988a7e92e8a4a0198fac/drake/systems/rendering/pose_bundle.h#L19)):*
> ```objc
> // GeometryWorld/GeometrySystem when they become available.
> 
> /// PoseBundle is a container for a set of poses, represented by an Isometry3,
> ```

BTW, Perhaps a similar `TODO` (as with `PoseAggregator`) to revisit the class name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-:-KfzmtNlvk7vHGbIQNQM:bes598y)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/rendering/frame_velocity.h, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-KfxTviaA07txD7XtZnh:-Kg0aJhaeA640nkbH72o:b-tkj61d) ([raw file](https://github.com/robotlocomotion/drake/blob/46783292335c2a8d245a988a7e92e8a4a0198fac/drake/systems/rendering/frame_velocity.h#L30)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, could the `DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN` macro be used here instead? 
</blockquote></details>

No, note the non-default implementations.

---

*[drake/systems/rendering/pose_bundle.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-KfxWvVFyPKNIugnxt-W:-Kg0a_QFFQ1CrDE_wan4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46783292335c2a8d245a988a7e92e8a4a0198fac/drake/systems/rendering/pose_bundle.h#L19)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, Perhaps a similar `TODO` (as with `PoseAggregator`) to revisit the class name?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5609)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for out of turn platform review and hopefully merge.  It's pretty small, automotive related, and needs to land in the next hour or so.

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-:-Kg0akEVN8CNxpYQSvdx:bi1q19i)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/rendering/frame_velocity.cc, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-Kg0bm7peYQhrLSzn2Zk:-Kg0bm7peYQhrLSzn2Zl:b-u6gyqh) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ef5ae33ae516a41c6503cc756b6d71982ec530/drake/systems/rendering/frame_velocity.cc#L31)):*
> ```cpp
> template <typename T>
> void FrameVelocity<T>::operator=(const FrameVelocity<T>& other) {
>   this->set_value(other.get_value());
> ```

Does `Eigen::Ref` defend against self-assignment?  If so, document here.  If not, add self-assignment guard.

Consider a unit test of self-assignment in any case.

---

*[drake/systems/rendering/frame_velocity.h, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-Kg0bZuFk4WUm8G9ukgv:-Kg0bZuGrMUx1YJbdoyT:boqo4zg) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ef5ae33ae516a41c6503cc756b6d71982ec530/drake/systems/rendering/frame_velocity.h#L31)):*
> ```objc
>   // AbstractValue, such as PoseBundle.
>   FrameVelocity(const FrameVelocity<T>& other);
>   void operator=(const FrameVelocity<T>& other);
> ```

Why doesn't this return a reference?

---

*[drake/systems/rendering/pose_aggregator.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-Kg0d4sEMfEBUUVGdH_U:-Kg0d4sEMfEBUUVGdH_V:b-6ky947) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ef5ae33ae516a41c6503cc756b6d71982ec530/drake/systems/rendering/pose_aggregator.cc#L50)):*
> ```cpp
>   input_records_.push_back(MakeSinglePoseInputRecord(name, model_instance_id));
>   const InputPortDescriptor<T>& pose_descriptor =
>       this->DeclareInputPort(kVectorValued, PoseVector<T>::kSize);
> ```

Does this (and the DeclareInput below) correctly set the input types for AllocateInput?  Maybe use model-based DeclareVectorInputPort instead?

---

*[drake/systems/rendering/pose_aggregator.h, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-Kg0cR4oLvce_jQFYHFD:-Kg0cR4oLvce_jQFYHFE:bsfc767) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ef5ae33ae516a41c6503cc756b6d71982ec530/drake/systems/rendering/pose_aggregator.h#L102)):*
> ```objc
>   ///         input, and the second element is the descriptor for the velocity
>   ///         input.
>   std::pair<const InputPortDescriptor<T>&, const InputPortDescriptor<T>&>
> ```

BTW I seem to recall that pairs of references have dangerous semantics, but maybe that's only for non-const references?  Did you look into that at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-:-Kg0dR83GpndzBJ2pSat:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/rendering/frame_velocity.cc, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-Kg0bm7peYQhrLSzn2Zk:-Kg0iOGR2RN7_zh7E4vC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ef5ae33ae516a41c6503cc756b6d71982ec530/drake/systems/rendering/frame_velocity.cc#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Does `Eigen::Ref` defend against self-assignment?  If so, document here.  If not, add self-assignment guard.

Consider a unit test of self-assignment in any case.
</blockquote></details>

Done.

---

*[drake/systems/rendering/frame_velocity.h, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-Kg0bZuFk4WUm8G9ukgv:-Kg0iOy8FA4FAVpdGlue:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ef5ae33ae516a41c6503cc756b6d71982ec530/drake/systems/rendering/frame_velocity.h#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why doesn't this return a reference?
</blockquote></details>

Done.

---

*[drake/systems/rendering/pose_aggregator.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-Kg0d4sEMfEBUUVGdH_U:-Kg0iwuupKvyVKzDHt7r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ef5ae33ae516a41c6503cc756b6d71982ec530/drake/systems/rendering/pose_aggregator.cc#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Does this (and the DeclareInput below) correctly set the input types for AllocateInput?  Maybe use model-based DeclareVectorInputPort instead?
</blockquote></details>

Done.

---

*[drake/systems/rendering/pose_aggregator.h, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5609#-Kg0cR4oLvce_jQFYHFD:-Kg0l2nsaoMHEX7kXzyS:bn7t6o3) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ef5ae33ae516a41c6503cc756b6d71982ec530/drake/systems/rendering/pose_aggregator.h#L102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I seem to recall that pairs of references have dangerous semantics, but maybe that's only for non-const references?  Did you look into that at all?
</blockquote></details>

Added better test coverage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5609)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5609)*

**Comment by jadecastro** [comment]
Reviewed 1 of 1 files at r2, 4 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5609)*

**Pull request merged**
