### PR TITLE
Remove divide by zero from UBSan

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Reverting the changes due to: https://github.com/RobotLocomotion/drake/pull/6610, https://github.com/RobotLocomotion/drake/pull/6769 and https://github.com/RobotLocomotion/drake/pull/6561.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6905)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by m-chaturvedi** [comment]
+@jamiesnape for feature review, please.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6905#-:-KsKfCKRRqypQ45n6TcW:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@soonho-tri for platform review, please.

**Comment by soonho-tri** [comment]
@m-chaturvedi , could you check the CI failures?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6905#-:-KsKm4gK1iTNph5Xo_pg:bk70xwz)*

**Comment by soonho-tri** [comment]
Other than that, :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6905#-:-KsKmCCeJqkZB0P2mO6a:b4tf03z)*

**Comment by jamiesnape** [comment]
CI failures on the UBSan jobs are expected. @m-chaturvedi Can you ensure there are GitHub issues for each of the remaining defects.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6905#-:-KsKmkIiRlSex4CYx5VM:b-bb9rp0)*

**Comment by m-chaturvedi** [comment]
Created https://github.com/RobotLocomotion/drake/issues/6910 and https://github.com/RobotLocomotion/drake/issues/6908.

**Pull request merged**
