### PR TITLE
[wheel] Add an option for --snopt-path

### LINKED ISSUE #21574: Wheel builder option for SNOPT_PATH
**Is your feature request related to a problem? Please describe.**

When building wheels using GitHub actions, I need to support a different way of accessing the secret snopt code.  As of today, the builder assumes that `git` credentials are available directly.  This ends up being a struggle to provide as part of GitHub actions.

**Describe the solution you'd like**

When running `bazel run //tools/wheel:builder`, there should be an option to configure `SNOPT_PATH` to point to a file.  This is the current work-around I'm using:

```patch
From a076627438435c08c202a7d0c7a1e4ba1a5d1a50 Mon Sep 17 00:00:00 2001
From: Jeremy Nimmer <jeremy.nimmer@tri.global>
Date: Sun, 21 Apr 2024 15:22:42 -0700
Subject: [PATCH] SNOPT_PATH

---
 tools/wheel/image/build-drake.sh | 2 +-
 tools/wheel/macos/build-wheel.sh | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/tools/wheel/image/build-drake.sh b/tools/wheel/image/build-drake.sh
index 30c947d2bd84..72175d93e345 100755
--- a/tools/wheel/image/build-drake.sh
+++ b/tools/wheel/image/build-drake.sh
@@ -16,7 +16,7 @@ cat > /opt/drake-wheel-build/drake-build/drake.bazelrc << EOF
 build --disk_cache=/var/cache/bazel/disk_cache
 build --repository_cache=/var/cache/bazel/repository_cache
 build --repo_env=DRAKE_OS=manylinux
-build --repo_env=SNOPT_PATH=git
+build --repo_env=SNOPT_PATH=/tmp/snopt.tar.gz
 build --config=packaging
 build --define=LCM_INSTALL_JAVA=OFF
 EOF
diff --git a/tools/wheel/macos/build-wheel.sh b/tools/wheel/macos/build-wheel.sh
index f43a97b6861a..4788e91bd2cb 100755
--- a/tools/wheel/macos/build-wheel.sh
+++ b/tools/wheel/macos/build-wheel.sh
@@ -79,7 +79,7 @@ cat > "$build_root/drake.bazelrc" << EOF
 build --disk_cache=$HOME/.cache/drake-wheel-build/bazel/disk_cache
 build --repository_cache=$HOME/.cache/drake-wheel-build/bazel/repository_cache
 build --repo_env=DRAKE_OS=macos_wheel
-build --repo_env=SNOPT_PATH=git
+build --repo_env=SNOPT_PATH=/tmp/snopt.tar.gz
 build --config=packaging
 build --define=LCM_INSTALL_JAVA=OFF
 # See tools/wheel/wheel_builder/macos.py for more on this env variable.
```

Instead of hard-coding that with a patch file, I'd like to pass a flag on the command line.

Note that this flag only needs to work when `--no-provision` is in effect.  There is no need to add logic to copy the `SNOPT_PATH` file from outside to inside of Docker.  (However, if it makes it easier to test locally by support the docker-aware file copying as part of this work, that's fine too.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This puts the git credentials step up-front in the build (prior to Docker or running as root) the same as any normal local build would need.  This makes automating wheel builds easier, e.g., in GitHub Actions.  The wheel's inner CMake build step always uses a `snopt.tar.gz` archive provided by our wrapper scripts.

Closes #21574.

I tested this PR using GitHub actions here: https://github.com/jwnimmer-tri/drake_github_workflow_prototype/commits/main/

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21647)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.  No particular hurry, the only goal is to land this before the next release.

(I'll squash the commits when I next push, or else when we merge.)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review, please (as you have at least some build-system experience).

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with the caveat that I have very little understanding of how the wheel stuff works.

> Reviewed 3 of 7 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21647#-:-O1TFq5O1S41LtBCc6Rb:bte0mse)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/wheel/wheel_builder/common.py` line 120 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21647#-O1TFYEd4WISgC5L-g6n:-O1TFYEd4WISgC5L-g6o:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae116347601292214472d22520654da1a6fc74b3/tools/wheel/wheel_builder/common.py#L120)):*
> ```Python
>             # them again inside of the container. If we see filenames 'foo' and
>             # 'foo.orig', we should skip 'foo' and add 'foo.orig' as 'foo'.
>             # we should skip 'foo'
> ```

nit

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21647)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21647)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
