### PR TITLE
[pydrake] Add missing LeafSystem and State bindings

### PR DESCRIPTION
**Pull request by RussTedrake**
Along with #16190 , these bindings were required to enable the following simple example:

```
from pydrake.all import (AbstractValue, EventStatus, LeafSystem, PiecewisePolynomial, Simulator)

# This simple planner stores it's plan (trajectory) as state, and replans at time ≈ 1.

class MySimplePlanner(LeafSystem):
    def __init__(self, traj):
        LeafSystem.__init__(self)
        assert traj.cols() == 1
        self.DeclareVectorOutputPort("value", traj.rows(), self.CalcOutput)

        self.DeclareAbstractState(AbstractValue.Make(traj)) # The trajectory.
        self.DeclareDiscreteState(1) # Add one more state to denote whether the trajectory been updated yet...
        self.DeclarePeriodicUnrestrictedUpdateEvent(
            period_sec=0.1, offset_sec=0.0, update=self.MaybeUpdatePlan)

    def MaybeUpdatePlan(self, context, state):
        # Note: you can add input ports and read their values here.
        updated = state.get_mutable_discrete_state(0)
        if not updated[0] and context.get_time() > 1.0:
            traj = state.get_mutable_abstract_state(0)
            traj.set_value(PiecewisePolynomial.FirstOrderHold([0, 1, 2], [[-2,-1,-3],[-4,-5,-6]]))
            updated[0] = True
            print("Replanning; outputs should now be negative values")
        return EventStatus.Succeeded()

    def CalcOutput(self, context, output):
        traj = context.get_abstract_state(0).get_value()
        output.SetFromVector(traj.value(context.get_time()))


print("Initial plan: outputs should be positive values")        
traj = PiecewisePolynomial.FirstOrderHold([0, 1, 2], [[2,1,3],[4,5,6]])
source = MySimplePlanner(traj)
simulator = Simulator(source)
simulator.AdvanceTo(0.5)
print(f"Output at time 0.5: {source.get_output_port().Eval(simulator.get_context())}")

simulator.AdvanceTo(1.5) 
print(f"Output at time 1.5: {source.get_output_port().Eval(simulator.get_context())}")
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16207)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16207#-:-Mqgd0bf6-ImXFox3xqz:b7dve2f)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending one comment.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16207#-:-MqokrzMA8V1TDx80Jpg:byktktz)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/framework_py_systems.cc, line 627 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16207#-Mqoj9QK6Ngcbde2pYJd:-Mqoj9QK6Ngcbde2pYJe:b6kmqqr) ([raw file](https://github.com/robotlocomotion/drake/blob/3a835de60a6fb7946a43e28f2a70ff5b13b7f06b/bindings/pydrake/systems/framework_py_systems.cc#L627)):*
> ```cpp
>                                 context, &*x);  // Ignore return status for now.
>                           }));
>                 }),
> ```

A few comments here:
- this API isn't just a Python version of one of the C++ methods but has its own implementation. Is that because there wasn't a C++ one that takes a free function? If that's needed here maybe it would be better to add it in C++ and then just wrap it here? If not, please add a comment to clarify why this has to have a separate Python implementation.
- it's not clear to me why `WrapCallbacks()` is required here -- the function doesn't seem to match the conditions described in WrapCallbacks' documentation. But I don't understand this well enough to say for sure -- can you explain why it is needed here?

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 627 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16207#-Mqoj9QK6Ngcbde2pYJd:-Mr7-91cAmHb1sw9Kl8L:bdg6mub) ([raw file](https://github.com/robotlocomotion/drake/blob/3a835de60a6fb7946a43e28f2a70ff5b13b7f06b/bindings/pydrake/systems/framework_py_systems.cc#L627)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

A few comments here:
- this API isn't just a Python version of one of the C++ methods but has its own implementation. Is that because there wasn't a C++ one that takes a free function? If that's needed here maybe it would be better to add it in C++ and then just wrap it here? If not, please add a comment to clarify why this has to have a separate Python implementation.
- it's not clear to me why `WrapCallbacks()` is required here -- the function doesn't seem to match the conditions described in WrapCallbacks' documentation. But I don't understand this well enough to say for sure -- can you explain why it is needed here?
</blockquote></details>

My inclination is that we shouldn't add the std::function variant in c++ until/unless there is a use case for it?  This is a pretty this wrapper.  In any case, I've added a TODO.

My understanding is that it *does* match the description in WrapCallbacks' documentation.  I don't want the system and context copied?  And I think it matches the pattern (e.g. in `MakeWitnessFunction` just below).

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16207#-:-Mr7vctb9PHwN7-jNWTP:b-vtj4vo)* status: 2 unresolved discussions (waiting on @RussTedrake and @sherm1)

___
*[bindings/pydrake/systems/test/custom_test.py, line 569 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16207#-Mr7vT3Z6iBEx6eftni5:-Mr7vT3Z6iBEx6eftni6:b-de4gpy) ([raw file](https://github.com/robotlocomotion/drake/blob/840a7575a4f72038dc58c3bf192b41cb1b7841f3/bindings/pydrake/systems/test/custom_test.py#L569)):*
> ```Python
>             context.get_abstract_state(0).get_value(), model_value.get_value())
> 
>         # Check state API
> ```

nit Missing punctuation.



_Suggestion:_
```Python
API.
```

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16207)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/framework_py_systems.cc, line 627 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16207#-Mqoj9QK6Ngcbde2pYJd:-Mr8DrvME-wAE4Y29JDO:b-y9zm57) ([raw file](https://github.com/robotlocomotion/drake/blob/3a835de60a6fb7946a43e28f2a70ff5b13b7f06b/bindings/pydrake/systems/framework_py_systems.cc#L627)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

My inclination is that we shouldn't add the std::function variant in c++ until/unless there is a use case for it?  This is a pretty this wrapper.  In any case, I've added a TODO.

My understanding is that it *does* match the description in WrapCallbacks' documentation.  I don't want the system and context copied?  And I think it matches the pattern (e.g. in `MakeWitnessFunction` just below).
</blockquote></details>

Thanks, I misunderstood WrapCallbacks() condition.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16207)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Pull request merged**
