### PR TITLE
multibody_py: Ensure `__init__` is installed.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Missed this during review, sorry about that!

\cc @RussTedrake @gizatt

Will follow-up with a `pydrake:all_install_test`  following suite with Francois's install tests in #7774. (Will just do a quick version of it, though.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7936)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@sherm1 for feature and platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7936#-:-L4MBeyiJYWEHVXj1gWk:b22o28l)*

**Comment by EricCousineau-TRI** [comment]
Kicked off experimental packaging: https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging/12 (job still allocating, so URL may be invalid)

**Comment by sherm1** [comment]
:lgtm: pending CI

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7936#-:-L4MKPhN1Tmy55AzqMxd:b3cfjge)*

**Comment by EricCousineau-TRI** [comment]
@RussTedrake Downloaded and tested experimental archive; I am able to execute `import pydrake.rbtree`.

**Pull request merged**
