### PR TITLE
A new strategy for GitHub issue management.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2254)

### CODE REVIEW

**Comment by sherm1** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/issues.rst, line 63 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGsW2UNQwGIApZ-M-qt:-KGsW2UNQwGIApZ-M-qu:981716843) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L63)):*
I'm not clear on the difference between `do not review` and `do not merge`. I presume the former implies the latter. But does `do not merge` status mean that a review is being requested? Please clarify.

I would still prefer an affirmative `please review` or `being reviewed` status.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2254)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-:-KGsXddlprE7Sr2ve4xK:1417088721)*

**Comment by liangfok** [comment]
Left some comments.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[drake/doc/index.rst, line 97 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtEdFIoByFitt_RaQ0:-KGtEdFIoByFitt_RaQ1:978670232) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/index.rst#L97)):*
Should the link to issues be under `developers.rst`?

---

*[drake/doc/issues.rst, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtFD65rBZklo3-EgLC:-KGtFD65rBZklo3-EgLD:-1587845356) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L5)):*
Consider making "Github issues" a hyperlink to https://guides.github.com/features/issues/.

---

*[drake/doc/issues.rst, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtEsdsgIT8fG3qZrRm:-KGtEsdtMl8fVnhto8gH:2068308648) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L6)):*
The sentence "There are typically a large number of open issues." reflects bad on Drake because it implies that Drake as _issues_. Consider deleting this sentence and modifying the next sentence to be as follows:

```
To keep the open issues organized, they are tagged with labels.
```

---

*[drake/doc/issues.rst, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtFi61ltBFZ4DHjvb1:-KGtFi61ltBFZ4DHjvb2:-1366634215) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L12)):*
Hmm, I think PRs could also have priorities. For example, if I have some free time and want to contribute by reviewing a PR, I can select the highest priority PR to review.

---

*[drake/doc/issues.rst, line 15 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtGoLe8bgHmteqssjz:-KGtGoLe8bgHmteqssk-:2023808749) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L15)):*
Consider adding a sentence saying the author of the issue may opt to not apply any labels in which case the Drake development team will assign labels as appropriate.

---

*[drake/doc/issues.rst, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtHaJ7p8hPfFvRS07q:-KGtHaJ7p8hPfFvRS07r:750116716) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L18)):*
``team`` -> ``team`` label.

---

*[drake/doc/issues.rst, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtG4Lw8lFmOgPgNlWv:-KGtG4Lw8lFmOgPgNlWw:495505292) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L19)):*
duplicate word "issue".

Consider changing "closed" to be "closed with an explanation and suggestion of how to submit an acceptable issue."  This is to sound more friendly.

---

*[drake/doc/issues.rst, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtGT0Wyzwoah_4-k6k:-KGtGT0Wyzwoah_4-k6l:1153788703) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L23)):*
Considering adding a brief 1-2 sentence explanation of the scope each team covers. To an external person, it will likely not be obvious from the team's name.

---

*[drake/doc/issues.rst, line 40 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtHnc6lworzkPB2Es2:-KGtHnc6lworzkPB2Es3:-1261776693) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L40)):*
engineers -> team

---

*[drake/doc/issues.rst, line 41 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtHtaeS59eUkgDap92:-KGtHtaeS59eUkgDap93:-586865043) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L41)):*
Should the document be version controlled in Drake's git repo? Ideally on Drake's wiki?

---

*[drake/doc/issues.rst, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtI3GzBKMTJEhUkcX_:-KGtI3GzBKMTJEhUkcXa:10223651) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L43)):*
How can a postmortem document be created at the same time as the emergency issue? Isn't a postmortem document by definition created _after_ the issue is resolved?

---

*[drake/doc/issues.rst, line 52 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtIM18iD-HTzgK24Ez:-KGtIM18iD-HTzgK24F-:546013429) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L52)):*
"be planned." -> "be planned for completion by a certain time frame and will instead be handled _ad hoc_ as time permits."

---

*[drake/doc/issues.rst, line 57 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtIjD-d2HJ1WtNdqtk:-KGtIjD0BELxFE0O91QU:1307709535) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L57)):*
Why separate ``matlab`` from the rest of the configuration list? Is it to denote an AND vs OR relationship?

---

*[drake/doc/issues.rst, line 63 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGsW2UNQwGIApZ-M-qt:-KGtJS8FGe-VFEsY6-k3:-1842443965) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L63)):*
+1 for being affirmative; it brings positive energy.

---

*[drake/doc/issues.rst, line 64 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtJ8ape-3b5XzHhhAv:-KGtJ8ape-3b5XzHhhAw:1516172448) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L64)):*
I would like another status: ``Waiting on Another PR``. It seems nicer and more informative than ``do not merge``.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-:-KGtJORSkh0OVtJ7xudJ:343397506)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[drake/doc/index.rst, line 97 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtEdFIoByFitt_RaQ0:-KGwmi-bvf3xzK3n1aQE:345863459) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/index.rst#L97)):*
I considered that and decided no, because: (a) issues are also of some interest to non-developers and (b) they are not an essential step in contributing code to Drake.

---

*[drake/doc/issues.rst, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtFD65rBZklo3-EgLC:-KGwn7xC8bXozCVJ5agL:-1473123085) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L5)):*
Link is a good idea.  I went with https://github.com/RobotLocomotion/drake/issues instead.

---

*[drake/doc/issues.rst, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtEsdsgIT8fG3qZrRm:-KGwmvhuVUf-nVh__vo4:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L6)):*
Done.

---

*[drake/doc/issues.rst, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtFi61ltBFZ4DHjvb1:-KGwnDoEL-q29R25Faj3:-225492675) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L12)):*
Done (although we won't enforce it in the scrub).

---

*[drake/doc/issues.rst, line 15 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtGoLe8bgHmteqssjz:-KGwnUk4dATcHxcriqbD:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L15)):*
Done.

---

*[drake/doc/issues.rst, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtHaJ7p8hPfFvRS07q:-KGwnZVOkcWGJ-k87nA-:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L18)):*
Done.

---

*[drake/doc/issues.rst, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtG4Lw8lFmOgPgNlWv:-KGwneje8Wzu66kBgezR:-1873812730) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L19)):*
I split the difference: "closed with an explanation".

---

*[drake/doc/issues.rst, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtGT0Wyzwoah_4-k6k:-KGwq9NOBfy8QPmrbRzu:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L23)):*
Done.

---

*[drake/doc/issues.rst, line 40 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtHnc6lworzkPB2Es2:-KGwvER8hw06OIFRuliN:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L40)):*
Done.

---

*[drake/doc/issues.rst, line 41 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtHtaeS59eUkgDap92:-KGwqAKVUT5XbWx5ixos:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L41)):*
Done.

---

*[drake/doc/issues.rst, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtI3GzBKMTJEhUkcX_:-KGwqB0gGdEMHD2DWITQ:-1481154048) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L43)):*
No.  As soon as an emergency is detected, you should start logging the entire sequence of events in a postmortem document. Important things will happen, and they will be impossible to reconstruct after the fact. Clarified this sentence.

---

*[drake/doc/issues.rst, line 52 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtIM18iD-HTzgK24Ez:-KGwqb8rYjcaTPoW5ig8:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L52)):*
Done.

---

*[drake/doc/issues.rst, line 57 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtIjD-d2HJ1WtNdqtk:-KGwqlRNmPg51N4Nm9Tc:1617127409) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L57)):*
Not really - it would be logically equivalent to have just one list, but I'd find it jarring since one of these things is not like the others.

---

*[drake/doc/issues.rst, line 63 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGsW2UNQwGIApZ-M-qt:-KGwrLL6Du-t00reae2z:1260292872) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L63)):*
Added some clarifying text.  

---

*[drake/doc/issues.rst, line 64 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGtJ8ape-3b5XzHhhAv:-KGwqy3Zpe9F1QW5if2-:-1012953147) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L64)):*
I really do not want the `status` labels to proliferate, as it further decreases the chance they'll be used in a consistent way.  `do not merge` gets straight to the point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2254)*

**Comment by liangfok** [comment]
I haven't actually generated the Sphinx documentation, so I trust another reviewer will do so to verify it looks right before merging this PR. I'm particularly interested in whether the list of teams turns out correctly formatted.

Otherwise, :lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-:-KGwx4h1ccxJ6M9MNH0B:-458869536)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/issues.rst, line 63 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-KGsW2UNQwGIApZ-M-qt:-KGwxcMxPuACyuLxixua:590999569) ([raw file](https://github.com/robotlocomotion/drake/blob/e8c9c0035e56370ef670cb5d1d775a05dbe9ba31/drake/doc/issues.rst#L63)):*
@sherm1 this is still blocked on you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2254)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot test this please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2254)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2254#-:-KGydRLIx6vGOxeqP3j7:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to jenkins flake.

**Pull request merged**
