### PR TITLE
Add mutable getters for the two MobilPlanner Parameters groups

### PR DESCRIPTION
**Pull request by jadecastro**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7716)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@maddog-tri for feature review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-:-L2RDJDVlS00R4KOHs-L:bftbl15)*

**Comment by maddog-tri** [comment]
Reviewed, PTAL.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[automotive/mobil_planner.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2RwRXjFn5vFgklKIdt:-L2RwRXjFn5vFgklKIdu:b37mk4m) ([raw file](https://github.com/robotlocomotion/drake/blob/add6a3dd9086498f4401b87a6bd750b3a3bb6a9d/automotive/mobil_planner.cc#L91)):*
> ```cpp
> IdmPlannerParameters<T>& MobilPlanner<T>::get_idm_params(
>     systems::Context<T>& context) const {
>   return dynamic_cast<IdmPlannerParameters<double>&>(
> ```

Here, and below:  should the `double` be `T` instead?

Or, better yet:  use `GetMutableNumericParameter()`, following the model in `CalcLaneDirection()` below?

---

*[automotive/mobil_planner.h, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2RvoqOVvk1Bng_7I7y:-L2RvoqOVvk1Bng_7I7z:b-h7r2o2) ([raw file](https://github.com/robotlocomotion/drake/blob/add6a3dd9086498f4401b87a6bd750b3a3bb6a9d/automotive/mobil_planner.h#L109)):*
> ```objc
>   IdmPlannerParameters<T>& get_idm_params(systems::Context<T>& context) const;
>   MobilPlannerParameters<T>& get_mobil_params(
>       systems::Context<T>& context) const;
> ```

Won't that doxygen docstring attach/apply to only the first method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-:-L2Ry06SkRV9pkZOQsIq:b3xc18v)*

**Comment by jadecastro** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[automotive/mobil_planner.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2RwRXjFn5vFgklKIdt:-L2UcgJbssQ_7_KDUKa2:b-7yg9o6) ([raw file](https://github.com/robotlocomotion/drake/blob/add6a3dd9086498f4401b87a6bd750b3a3bb6a9d/automotive/mobil_planner.cc#L91)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Here, and below:  should the `double` be `T` instead?

Or, better yet:  use `GetMutableNumericParameter()`, following the model in `CalcLaneDirection()` below?
</blockquote></details>

Thanks for catching. done.

---

*[automotive/mobil_planner.h, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2RvoqOVvk1Bng_7I7y:-L2UdNINOMPuGiAwrQH8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/add6a3dd9086498f4401b87a6bd750b3a3bb6a9d/automotive/mobil_planner.h#L109)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Won't that doxygen docstring attach/apply to only the first method?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-:-L2VUom3aTeHHm2p8Uhv:bnfp4nl)*

**Comment by jadecastro** [comment]
+@seancurtis-tri platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-:-L2VYKD4Wqox-uFFqiLF:be0uhpw)*

**Comment by SeanCurtis-TRI** [comment]
It isn't clear to me why a `const` method is providing mutable access to data. Particularly as the method names don't indicate mutability. Could you elaborate on that?

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[automotive/mobil_planner.h, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2VdRLinQlyWLcOxe7t:-L2VdRLinQlyWLcOxe7u:b-pd4a99) ([raw file](https://github.com/robotlocomotion/drake/blob/7337682fd02c46679e8e38ca0d08e6a4cacb0236/automotive/mobil_planner.h#L108)):*
> ```objc
>   /// Parameters groups.
>   /// @{
>   IdmPlannerParameters<T>& get_idm_params(systems::Context<T>* context) const;
> ```

BTW The standard for acquiring mutable references tends towards the `get_*_mutable()` pattern. It would probably be good to add "mutable" to this function name as well.

---

*[automotive/mobil_planner.h, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2VddHiKRCz_v5wxYx-:-L2VddHiKRCz_v5wxYx0:b-7pqvdj) ([raw file](https://github.com/robotlocomotion/drake/blob/7337682fd02c46679e8e38ca0d08e6a4cacb0236/automotive/mobil_planner.h#L109)):*
> ```objc
>   /// @{
>   IdmPlannerParameters<T>& get_idm_params(systems::Context<T>* context) const;
>   MobilPlannerParameters<T>& get_mobil_params(
> ```

BTW Is there a reason for these getters not to be inlined (e.g., providing the definition here in the declaration?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-:-L2VebpMN8m_e6FDC4Mf:bkjgbxi)*

**Comment by SeanCurtis-TRI** [comment]
I retract my previous stupid statement. There is *no* confusion about const methods returning non-const members. (That's what happens when you're the first review of the morning.) But I do stand by the function *name* comment.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-:-L2VsWZw5yvkAkJoYiVJ:b-n6tpf)*

**Comment by jadecastro** [comment]
No worries ;) 
I agree about the naming and have updated those- ptal.  

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[automotive/mobil_planner.h, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2VdRLinQlyWLcOxe7t:-L2Vr2Jf0RbKAyhCP5br:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7337682fd02c46679e8e38ca0d08e6a4cacb0236/automotive/mobil_planner.h#L108)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The standard for acquiring mutable references tends towards the `get_*_mutable()` pattern. It would probably be good to add "mutable" to this function name as well.
</blockquote></details>

Done.

---

*[automotive/mobil_planner.h, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2VddHiKRCz_v5wxYx-:-L2VsfYeTqtA3PiMi1I1:b-50b6fb) ([raw file](https://github.com/robotlocomotion/drake/blob/7337682fd02c46679e8e38ca0d08e6a4cacb0236/automotive/mobil_planner.h#L109)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is there a reason for these getters not to be inlined (e.g., providing the definition here in the declaration?)
</blockquote></details>

I think it makes sense, even though we don't usually see `inline` methods in LeafSystems. And, it motivated me to compactify the implementation. Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-:-L2VownhaG5zmgDsQEg8:byrxh17)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: (with one thought for your consideration...)

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/mobil_planner.h, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2VddHiKRCz_v5wxYx-:-L2W8PdMIo20L4or1vNy:b6xzj3h) ([raw file](https://github.com/robotlocomotion/drake/blob/7337682fd02c46679e8e38ca0d08e6a4cacb0236/automotive/mobil_planner.h#L109)):*
FYI The inline keyword isn't strictly required.
> A function defined entirely inside a class/struct/union definition, whether it's a member function or a non-member friend function, is implicitly an inline function.
(http://en.cppreference.com/w/cpp/language/inline)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-:-L2W9TNoWXtVFeG4vkE0:bt5fmar)*

**Comment by jadecastro** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[automotive/mobil_planner.h, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7716#-L2VddHiKRCz_v5wxYx-:-L2WBtCKpxasbq2oxfLG:b-z7ddpg) ([raw file](https://github.com/robotlocomotion/drake/blob/7337682fd02c46679e8e38ca0d08e6a4cacb0236/automotive/mobil_planner.h#L109)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI The inline keyword isn't strictly required.
> A function defined entirely inside a class/struct/union definition, whether it's a member function or a non-member friend function, is implicitly an inline function.
(http://en.cppreference.com/w/cpp/language/inline)
</blockquote></details>

Ah, right. Probably explains why the lack of `inline`s. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7716)*

**Pull request merged**
