### PR TITLE
Fix remaining ELF visivility issues on OS X

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Fix problems with export decorations in `drakeMexUtil.{cpp,h}` (see 44bd7b0c3fec). Add some more missing export decorations.

This should fix the remaining breakage from #3065.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3210)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
Note: [mac-clang-ninja-experimental-matlab-open-source](https://drake-jenkins.csail.mit.edu/job/mac-clang-ninja-experimental-matlab-open-source/5/) and [mac-clang-experimental-matlab](https://drake-jenkins.csail.mit.edu/job/mac-clang-experimental-matlab/79/) passed as of the previous version of this PR; the current version (as of this comment) just edits a commit message.

**Comment by jonathan-owens** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3210)*

**Comment by jonathan-owens** [comment]
Looks good to me

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3210#-:-KPrfIv4UxIiw9LeCxGR:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
TY, @david-german-tri!

**Pull request merged**
