### PR TITLE
rename trajectory optimization test

### PR DESCRIPTION
**Pull request by RussTedrake**
trajectory_optimization_test => multiple_shooting_test

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6876)

### CODE REVIEW

**Comment by RussTedrake** [comment]
trivial change.  +@ericcousineau-tri for both levels of review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6876#-:-Ks-3l_VmLmv9kS2XoH7:b-6k59wa)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: for both feature and platform review (with one minor BTW). Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/test/multiple_shooting_test.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6876#-Ks43EtzSJtz8W1f91Q3:-Ks43Eu-zE_k5-255-_x:bx52600) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0f41e8d8d68b7db4b1661855bc4afef2614e0d/drake/systems/trajectory_optimization/test/multiple_shooting_test.cc#L53)):*
> ```cpp
> };
> 
> GTEST_TEST(TrajectoryOptimizationTest, FixedTimestepTest) {
> ```

BTW Would it be possible to change the test name as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6876#-:-Ks43KyJ13NZLpUBV9Yw:b-e2m718)*

**Comment by RussTedrake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/test/multiple_shooting_test.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6876#-Ks43EtzSJtz8W1f91Q3:-Ks48XWf5VMB5_q-aPGq:bf6pfes) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0f41e8d8d68b7db4b1661855bc4afef2614e0d/drake/systems/trajectory_optimization/test/multiple_shooting_test.cc#L53)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Would it be possible to change the test name as well?
</blockquote></details>

Good catch.  Done.  Please go ahead and merge if/when you and the servers are happy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6876)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please.

**Comment by EricCousineau-TRI** [comment]
There's to be a merge conflict with `BUILD` on `master` due to removing the constraint test.
Here's the [merge](https://github.com/EricCousineau-TRI/drake/commit/a7db0477b091a96d43f3e6d232d8b44dd1c05518#diff-ed994c1dd9cd94bf4218b06fd2ddb256L39).

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6876#-:-Ks5GqEBfZNfl6npfAuO:bgb66qx)*

**Pull request merged**
