### PR TITLE
Factor out Context<T>::CloneState.

### PR DESCRIPTION
**Pull request by david-german-tri**
Should be useful for #4382.  It's simpler than the LOC suggest (mostly moving code).

@edrumwri for feature review, @sherm1 for platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4544)

### CODE REVIEW

**Comment by sherm1** [comment]
Platform: :lgtm: -- looks very useful, thanks! A couple of BTW questions, PTAL.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/diagram_context.h, line 279 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-KZOpf1bK2JbeLvW5j3S:-KZOpf1cvf4qXaRsKmkL:b-a99oid) ([raw file](https://github.com/robotlocomotion/drake/blob/fb937d44ac89b8386f89a96621ee7690b4f48902/drake/systems/framework/diagram_context.h#L279)):*
> ```objc
>       }
>     }
>     // The wrapper states do not own the constituent state.
> ```

BTW, I don't understand the comment because I can't figure out exactly what you mean by "wrapper states" or "constituent state". I couldn't discern how to map those terms to the variables here. And I'm not sure how the next three statements fix that problem? Please clarify terminology.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-KZOqrKYsCGUDqZWqFT2:-KZOqrKZwx3e04qCmp9z:bq81ze1) ([raw file](https://github.com/robotlocomotion/drake/blob/fb937d44ac89b8386f89a96621ee7690b4f48902/drake/systems/framework/test/diagram_context_test.cc#L97)):*
> ```cpp
>   const BasicVector<double>* xd_vec =
>       clone.get_discrete_state()->get_discrete_state(0);
>   EXPECT_EQ(44.0, xd_vec->GetAtIndex(0));
> ```

BTW, should this include a test that diagram abstract state variables are cloned also?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-:-KZOrOtkruS4fieWAkY1:bccop6v)*

**Comment by edrumwri** [comment]
:lgtm: (w/some small issues)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram_context.h, line 260 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-KZPrhQPc-igFnQ9wOt0:-KZPrhQQbEiVGdtLX3t4:b-3a8y0q) ([raw file](https://github.com/robotlocomotion/drake/blob/fb937d44ac89b8386f89a96621ee7690b4f48902/drake/systems/framework/diagram_context.h#L260)):*
> ```objc
>   std::unique_ptr<DiagramState<T>> BuildState() const {
>     auto state = std::make_unique<DiagramState<T>>(num_subsystems());
>     std::vector<ContinuousState<T>*> sub_xcs;
> ```

BTW David, wouldn't it be better to allocate your sub_xcs vector ahead of time, so that you're not having to resize multiple times?

---

*[drake/systems/framework/diagram_context.h, line 279 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-KZOpf1bK2JbeLvW5j3S:-KZPw_Jf7mHildtVQpWF:byr6uw2) ([raw file](https://github.com/robotlocomotion/drake/blob/fb937d44ac89b8386f89a96621ee7690b4f48902/drake/systems/framework/diagram_context.h#L279)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I don't understand the comment because I can't figure out exactly what you mean by "wrapper states" or "constituent state". I couldn't discern how to map those terms to the variables here. And I'm not sure how the next three statements fix that problem? Please clarify terminology.
</blockquote></details>

BTW, agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-:-KZPx1NU39GZSDocJ8c_:b-ibhet)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram_context.h, line 279 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-KZOpf1bK2JbeLvW5j3S:-KZRe79Fj_-SMCMYCBs0:b-1fn5i6) ([raw file](https://github.com/robotlocomotion/drake/blob/fb937d44ac89b8386f89a96621ee7690b4f48902/drake/systems/framework/diagram_context.h#L279)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW, agreed.
</blockquote></details>

Oh.  Wow.  This reveals a significant flaw in this PR.  Let me rethink.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4544)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram_context.h, line 260 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-KZPrhQPc-igFnQ9wOt0:-KZRxWjT4e-6CkoYHgr8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb937d44ac89b8386f89a96621ee7690b4f48902/drake/systems/framework/diagram_context.h#L260)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW David, wouldn't it be better to allocate your sub_xcs vector ahead of time, so that you're not having to resize multiple times?
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram_context.h, line 279 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-KZOpf1bK2JbeLvW5j3S:-KZRxXoJwQpokNgJw4Px:b-ixv1ic) ([raw file](https://github.com/robotlocomotion/drake/blob/fb937d44ac89b8386f89a96621ee7690b4f48902/drake/systems/framework/diagram_context.h#L279)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Oh.  Wow.  This reveals a significant flaw in this PR.  Let me rethink.
</blockquote></details>

Ah, I already had the right seam, I just had to think a little differently.  I've added tests and improved this comment, PTAL.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-KZOqrKYsCGUDqZWqFT2:-KZRyLMa7DTOF1GILFpc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb937d44ac89b8386f89a96621ee7690b4f48902/drake/systems/framework/test/diagram_context_test.cc#L97)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, should this include a test that diagram abstract state variables are cloned also?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4544)*

**Comment by david-german-tri** [comment]
OK, I'm going to go ahead and merge this.  If any tweaks are needed, I promise a prompt follow-up.

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4544#-:-KZSXigXa8T-S8X-Vk-k:bxpqrhc)*

**Pull request merged**
