### PR TITLE
MBPs RigidTransform migration.

### PR DESCRIPTION
**Pull request by amcastro-tri**
I spiked tested the proposal I made in #9865. 
The updates in `RigidTransform` include:
- `operator Isometry3()`
- `linear()` (const only) for compatibility with `Isometry3`.
- `RigidTransform(const Isometry3&)` is now implicit.

~~This WIP PR includes:~~
~~- Position kinematics (and thus `EvalFooPose()` methods) migrated to use `RigidTransform`.~~
~~- `tree_from_joints_test.cc` runs successfully.~~
~~- `multibody_plant_test.cc` runs successfully.~~
~~- Notice the use of explicit conversion here. (allowing users to pass their `RigidTransforms` while we update APIs.~~
~~- Notice const reference return from an `Eval()` into an `Isometry3` here.~~

~~Note: in this spike test I only focused on getting `tree_from_joints_test` and `multibody_plant_test` since they are very representative of all use cases. There might be places I broke and CI I'm sure will bark. But I'm confident they should be fixable.~~

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10959)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
cc'ing @mitiguy, @sherm1

**Comment by SeanCurtis-TRI** [comment]
This seems to be predicated on the hypothesis that we can do this relatively locally and not have a flag day. It seems that hypothesis can only be validated when this PR passes CI. Then we can see what changes would be required to effect this. While CI is failing, some unconsidered subtlety may be lurking.

This would *also* benefit from some performance regression. Obviously, eveywhere someone does an implicit conversion (even if they *think* they're getting a const reference) is going to lead to a copy. Given all the noise of late about performance, it would be good to see if the before/after affects Anzu applications.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/multibody/plant_py.cc, line 113 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10959#-LaQLvhdDZ03DikBQUnY:-LaQSqgL4VoZJyOAS4gX:b-py4w3j) ([raw file](https://github.com/robotlocomotion/drake/blob/b1593027de27ab7ac3a25e2b7acb2f330f6b3c7c/bindings/pydrake/multibody/plant_py.cc#L113)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Rather than binding `RigidTransform` as well, can we make `Isometry3 <-> RigidTransform` implicitly convertible, and switch bindings to purely `RigidTransform`?

(I will test this out and see if it's possible - stay tuned!)
</blockquote></details>

Yup, it's possible:
https://github.com/EricCousineau-TRI/drake/commit/b98a64e92d0c33e612d69521dcec0fab0594f965

If you want, you can defer that, and I can come in later and scoop `Isometry3` out of the `multibody` bindings.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/multibody/plant_py.cc, line 113 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10959#-LaQLvhdDZ03DikBQUnY:-LaVNAag4TMsjOBkBNlF:b-qf9d4i) ([raw file](https://github.com/robotlocomotion/drake/blob/b1593027de27ab7ac3a25e2b7acb2f330f6b3c7c/bindings/pydrake/multibody/plant_py.cc#L113)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Sounds good! It seems like this will be dependent on how we handle `Isometry3 -> RigidTransform` implicit conversions.
(forgot that we can't distinguish explicit ctors from implicit conversions... d'oh!)
</blockquote></details>

(Well, actually, I can still achieve this in Python regardless... So yeah, will file the follow-up issue.)

**Comment by EricCousineau-TRI** [comment]
___
*[math/rigid_transform.h, line 122 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10959#-LaTJvNg25lTRvd57uMc:-LaVNdQh6GEJ84FbjIB2:b4bri5g) ([raw file](https://github.com/robotlocomotion/drake/blob/cd24a6e0f073932d93427b86eb8ae6a8ad2f795a/math/rigid_transform.h#L122)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This might be opening up a can of worms.  I am not sure if (in the future) we could deprecate the converting constructor form, but have the explicit constructor (overload?) not be deprecated.  Have you tried any experiments with this?  Maybe with an extra default argument on the explicit constructor, though I suspect that's ambiguous.

If we can't use a deprecation tag, aren't we inviting users to author code that will have a hard API break in the future?  They will start passing their Isometry3 objects into our RigidTransform-taking APIs, all of which will disappear in a heartbeat.

How bad is it if you remove this?  Can we put some (deprecateable) shims elsewhere easily, instead?
</blockquote></details>

Honestly, if this buys us the initial transition without a huge flag day, and then we just make a semi-huge flag day in the future, I'm down for that.

**Comment by amcastro-tri** [comment]
>  IMO the question of "should a future PR change this code" can be happily deferred to ... a future PR! That's what PRs are for -- code on the table.

I misunderstood what you meant then, sry. So, what do you mean?

**Comment by jwnimmer-tri** [comment]
Lesson learned: This PR made substantial API edits, with the hypothesis that calling code would be unharmed.  That was partially validated by the minimal scope of required Drake edits.  However, given the risk factors we should have _also_ tested this PR against Anzu call sites.  It turns out that we missed a few shims here, like `RigidTransform::operator*(Eigen::Translation3d)` or some such.  @amcastro-tri will deal with those follow-ups soon enough.

**Comment by amcastro-tri** [comment]
yeap, ditto that. Thanks for the help @jwnimmer-tri and @EricCousineau-TRI

**Pull request merged**
