### PR TITLE
workspace: Upgrade scs to latest release 2.1.3

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14970)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Tested locally on macsim.

+@SeanCurtis-TRI for both reviews, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

Mac test?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14970#-:-MZTKUwWCwNEa8TOf6rb:b-u4uwol)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> Tested locally on macsim.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please

Jenkins was not going brrrrrr very fast on this one; maybe a retry will help.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please

**Pull request merged**
