### PR TITLE
Addition of ROS-Compatible SensorVisualizerLidar and Car Demo That Uses It

### PR DESCRIPTION
**Pull request by liangfok**
Contributes to https://github.com/RobotLocomotion/drake/issues/1733.

I'm creating this PR to use the CI and to solicit early feedback because the code is still very messy.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2126) &emsp; Multiple assignees:&emsp;@RussTedrake&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/RussTedrake">RussTedrake</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>

### CODE REVIEW

**Comment by liangfok** [comment]
One big issue is the CI is currently not configured to cover ROS-related code, which are conditionally built based on whether `roscpp` is found by CMake. See: https://github.com/RobotLocomotion/drake/issues/2116

**Comment by RussTedrake** [comment]
i think the way that you're integrating ros (RosInputSystem, the message type directories, etc) all looks great.  but I would not choose the botvisualizer as the first thing to port.  in fact, I would never port that.  much better to port the signals going between the pendulum dynamics and the pendulum control, for instance.

---

Reviewed 1 of 3 files at r1, 4 of 10 files at r2, 2 of 7 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/CMakeLists.txt, line 2 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KFoadrg3hg29Kd7YOgv:-KFoadrg3hg29Kd7YOgw:20139240) ([raw file](https://github.com/robotlocomotion/drake/blob/93c8c643c93fc0b5a7006b01e6a47c021486057b/drake/CMakeLists.txt#L2)):*
this happens already in pods.cmake 

---

*[drake/examples/Pendulum/run_pendulum_dynamics_ros.cc, line 15 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KFob0cvknnQm7n7AIwy:-KFob0cwDm8leCjVLQ_V:-43722617) ([raw file](https://github.com/robotlocomotion/drake/blob/93c8c643c93fc0b5a7006b01e6a47c021486057b/drake/examples/Pendulum/run_pendulum_dynamics_ros.cc#L15)):*
seems like BotVisualizer should only ever be LCM (it's talking to drake-visualizer, which speaks LCM).  

---

*[drake/rostypes/rost_viewer_draw.msg, line 1 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KFobKyV9ToXWivAi38b:-KFobKyV9ToXWivAi38c:1940952305) ([raw file](https://github.com/robotlocomotion/drake/blob/93c8c643c93fc0b5a7006b01e6a47c021486057b/drake/rostypes/rost_viewer_draw.msg#L1)):*
again.  i wouldn't think you'd want to ros-ify these

---

*[drake/systems/ros_system.h, line 28 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KFobTPm8ydhuLT6agHk:-KFobTPm8ydhuLT6agHl:199470566) ([raw file](https://github.com/robotlocomotion/drake/blob/93c8c643c93fc0b5a7006b01e6a47c021486057b/drake/systems/ros_system.h#L28)):*
obviously update from lcm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-:-KFobqKepHapMer0z8SX:-357232765)*

**Comment by liangfok** [comment]
Thanks for the feedback. My immediate plan is to add LIDAR sensors to the Prius (https://github.com/RobotLocomotion/drake/issues/1654) and then to publish the LIDAR data as [sensor_msgs/LaserScan](http://docs.ros.org/api/sensor_msgs/html/msg/LaserScan.html) messages on ROS topics. Once done, I think the next step is to publish the car's position and orientation in the world on ROS topic `/tf`. Please let me know if I'm going down the wrong path.

---

Review status: 12 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/CMakeLists.txt, line 2 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KFoadrg3hg29Kd7YOgv:-KFogNBQV22tK-BQXLc9:-1175214079) ([raw file](https://github.com/robotlocomotion/drake/blob/93c8c643c93fc0b5a7006b01e6a47c021486057b/drake/CMakeLists.txt#L2)):*
OK. Removed.

---

*[drake/examples/Pendulum/run_pendulum_dynamics_ros.cc, line 15 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KFob0cvknnQm7n7AIwy:-KFogxF8jkG7NFqeIe6f:2019426442) ([raw file](https://github.com/robotlocomotion/drake/blob/93c8c643c93fc0b5a7006b01e6a47c021486057b/drake/examples/Pendulum/run_pendulum_dynamics_ros.cc#L15)):*
I agree and will leave the `BotVisualizer` to remain LCM-only.

---

*[drake/rostypes/rost_viewer_draw.msg, line 1 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KFobKyV9ToXWivAi38b:-KFohu17G_FbSo6bzqq-:-1421144086) ([raw file](https://github.com/robotlocomotion/drake/blob/93c8c643c93fc0b5a7006b01e6a47c021486057b/drake/rostypes/rost_viewer_draw.msg#L1)):*
I agree, and will remove them soon.

---

*[drake/systems/ros_system.h, line 28 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KFobTPm8ydhuLT6agHk:-KFohRp6TjCwyoj-z9F1:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/93c8c643c93fc0b5a7006b01e6a47c021486057b/drake/systems/ros_system.h#L28)):*
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-:-KFof2bhMWozs0243Dwd:-1451301463)*

**Comment by liangfok** [comment]
I'm going to close this PR to prevent needless CI builds. I will re-open it when ready.

**Comment by liangfok** [comment]
I'm reopening this PR because I got the LIDAR data to publish. The next step is to publish the transform information, which I would like to do as part of a future PR (I believe this PR is big enough). I created https://github.com/RobotLocomotion/drake/issues/2211 to track its progress.

**Comment by liangfok** [comment]
Review status: 1 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/CMakeLists.txt, line 226 \[r10\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KGTgGhX-1RzB_7XfFxg:-KGTgGhY3op93356sJ1-:-1323467982) ([raw file](https://github.com/robotlocomotion/drake/blob/49c6d1758492458ea0c80e3f5a3148e5cd2799fe/drake/CMakeLists.txt#L226)):*
Note: I commented this out b/c it is incompatible with LCM, see: https://github.com/RobotLocomotion/drake/issues/2187

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2126)*

**Comment by liangfok** [comment]
Review status: 1 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/rostypes/rost_viewer_draw.msg, line 1 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KFobKyV9ToXWivAi38b:-KGTgvcPMyE_Elnm7hGT:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/93c8c643c93fc0b5a7006b01e6a47c021486057b/drake/rostypes/rost_viewer_draw.msg#L1)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2126)*

**Comment by liangfok** [comment]
Failure in [CI Build 1108](https://drake-jenkins.csail.mit.edu/job/experimental/1108/) appear to be due to https://github.com/RobotLocomotion/drake/issues/2199.

Thus, +@russtedrake, this PR is ready for another round of review.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-:-KGUkcwixoUJ6KqVtfr9:1415616427)*

**Comment by liangfok** [comment]
[CI Build 1108](https://drake-jenkins.csail.mit.edu/job/experimental/1108/) passed except for Win64, which suffered https://github.com/RobotLocomotion/drake/issues/2199. 

Thus, @RussTedrake, this PR is ready for another round of review.

**Comment by liangfok** [comment]
I wonder if sensor_visualizer_lidar.h should be renamed `laser_scanner_to_ros_topic.h` since (1) it is not a visualizer and (2) it is specific to ROS.

---

Reviewed 1 of 1 files at r10.
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/sensor_visualizer_lidar.h, line 83 \[r11\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KGbIIZy9vlHnnro3EzO:-KGbIIZy9vlHnnro3EzP:1992251302) ([raw file](https://github.com/robotlocomotion/drake/blob/e93441ad1b7e628b23aee52dc13edf2bc4e47479/drake/systems/plants/sensor_visualizer_lidar.h#L83)):*
Could / should this be replaced with the following?

```
lidar_publishers_[depth_sensor->get_name()] = nh.advertise<sensor_msgs::LaserScan>(topic_name, 1)));
```

---

*[drake/systems/plants/sensor_visualizer_lidar.h, line 85 \[r11\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-KGbIb06msq-Mi-cnz8Y:-KGbIb06msq-Mi-cnz8Z:1614597823) ([raw file](https://github.com/robotlocomotion/drake/blob/e93441ad1b7e628b23aee52dc13edf2bc4e47479/drake/systems/plants/sensor_visualizer_lidar.h#L85)):*
Remove magic number 1.

```C++
static const int kQueueSize = 1;
//...
nh.advertise<sensor_msgs::LaserScan>(topic_name, kQueueSize)));
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2126#-:-KGbI-z26XRO9PUTt9EF:-366398778)*

**Comment by liangfok** [comment]
[CI Build 1163](https://drake-jenkins.csail.mit.edu/job/experimental/1163/) reported the following five cpplint errors:

```
14:19:47 /home/ubuntu/workspace/experimental/ae7636ba/drake/systems/plants/RigidBodyTree.cpp:85: warning: Lines should be <= 80 characters long  [whitespace/line_length] [2]
14:19:49 /home/ubuntu/workspace/experimental/ae7636ba/drake/systems/plants/sensor_visualizer_lidar.h:53: warning: Single-parameter constructors should be marked explicit.  [runtime/explicit] [5]
14:19:49 /home/ubuntu/workspace/experimental/ae7636ba/drake/systems/plants/sensor_visualizer_lidar.h:63: warning: Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
14:19:49 /home/ubuntu/workspace/experimental/ae7636ba/drake/systems/plants/sensor_visualizer_lidar.h:170: warning: Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
14:19:54 /home/ubuntu/workspace/experimental/ae7636ba/drake/examples/Cars/simulateLCMandROS.cpp:23: warning: Single-parameter constructors should be marked explicit.  [runtime/explicit] [5]
```

**Comment by liangfok** [comment]
@RussTedrake: This PR passed [CI Build 1182](https://drake-jenkins.csail.mit.edu/job/experimental/1182/) and is thus ready for feature review.

**Comment by liangfok** [comment]
I am going to close this PR since it is superseded by https://github.com/RobotLocomotion/drake/pull/2253.

**Pull request closed without merging**
