### PR TITLE
detail_sdf_parser_test: Make ParseTestString use string, not file

### LINKED ISSUE #15294: mac ci: Filesystem can be flaky?
From Drake Slack: https://drakedevelopers.slack.com/archives/C270MN28G/p1625161505072200

Not sure if there's an issue already pointing to this, but we had a CI failure:
https://drake-jenkins.csail.mit.edu/view/Production/job/mac-big-sur-clang-bazel-nightly-everything-release/145/
```
Test: //multibody/parsing:detail_sdf_parser_test (Failed)
...

Using drake_cc_googletest_main.cc

[==========] Running 36 tests from 4 test suites.
...
Error [parser.cc:495] Error parsing XML in file [/Users/bigsur/workspace/mac-big-sur-clang-bazel-nightly-everything-release/_bazel_bigsur/875ba5f0e66adafd774ba53730bf009d/sandbox/darwin-sandbox/7488/execroot/drake/_tmp/8171ba7a8c554b337ee0df98cc1f46c2/test_string.sdf]: Error=XML_ERROR_EMPTY_DOCUMENT ErrorID=13 (0xd) Line number=0
unknown file: Failure
C++ exception with description "From AddModelFromSdfFile():
Error: Unable to read file:/Users/bigsur/workspace/mac-big-sur-clang-bazel-nightly-everything-release/_bazel_bigsur/875ba5f0e66adafd774ba53730bf009d/sandbox/darwin-sandbox/7488/execroot/drake/_tmp/8171ba7a8c554b337ee0df98cc1f46c2/test_string.sdf" thrown in the test body.
[  FAILED  ] SdfParser.StaticModelSupported (45 ms)
...
[==========] 36 tests from 4 test suites ran. (4709 ms total)
[  PASSED  ] 35 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SdfParser.StaticModelSupported
```

Code in question:
https://github.com/RobotLocomotion/drake/blob/2d737e4b4251132d5a907da31f8f18a2b012abf7/multibody/parsing/test/detail_sdf_parser_test.cc#L268-L282

This is used in multiple test cases, so it's most likely a flake on our Mac instance as to why this happened?

\cc @jwnimmer-tri

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This helps to avoid spurious Mac CI failures

Resolves #15294 (as a workaround)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15295)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for both reviews, please!
+(status: single reviewer ok) 

\cc @azeey 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15295#-:-MdYUVs59hdVV9Ol5_E0:be9ijwk)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15295#-MdYUXk26NHS08U0I2B2:-MdYUXk26NHS08U0I2B3:b-rzx1pp) ([raw file](https://github.com/robotlocomotion/drake/blob/fc8fce8889b257e3fd0d871adbd20dffb74e92da/multibody/parsing/test/detail_sdf_parser_test.cc#L60)):*
> ```cpp
>     MultibodyPlant<double>* plant,
>     geometry::SceneGraph<double>* scene_graph = nullptr) {
>   const DataSource data_source{&file_name, {}};
> ```

FYI I changed these away from designated initializers b/c it doesn't work for `file_contents` in isolation (I guess since it ain't the first field).

At least on my system, compiler (`g++ 7.5.0` on Ubuntu) doesn't support designated initializer.
Code:
```cc
  return AddModelsFromSdf(
      { .file_contents = &file_contents },
      package_map, plant, scene_graph);
```
Error:
```
multibody/parsing/test/detail_sdf_parser_test.cc:80:38: sorry, unimplemented: non-trivial designated initializers not supported
       package_map, plant, scene_graph);
```

**Comment by EricCousineau-TRI** [comment]
> doesn't support designated initializer.

Soz, it doesn't support *non-trivial* designated initializer

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15295#-:-MdYVvql2rmOvN_ElhR0:bnfp4nl)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15295#-MdYVhXX9iZa8jE4xSgB:-MdYVhXX9iZa8jE4xSgC:b-w85tiy) ([raw file](https://github.com/robotlocomotion/drake/blob/fc8fce8889b257e3fd0d871adbd20dffb74e92da/multibody/parsing/test/detail_sdf_parser_test.cc#L3)):*
> ```cpp
> #include "drake/multibody/parsing/detail_sdf_parser.h"
> 
> #include <fstream>
> ```

nit Unused fstream.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15295)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15295#-MdYVhXX9iZa8jE4xSgB:-MdYZuDOD8cxyWdftr5w:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/fc8fce8889b257e3fd0d871adbd20dffb74e92da/multibody/parsing/test/detail_sdf_parser_test.cc#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unused fstream.
</blockquote></details>

Done, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15295)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

**Review by azeey — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15295#-:-MdYkq603ujy3QpO0Uch:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
