### PR TITLE
adds Diagram tutorial

### PR DESCRIPTION
**Pull request by RussTedrake**
+@jwnimmer-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18873)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature review.

Note I've pushed some lint-like fixes.  Be sure you pull them locally so they don't get overwritten.  I'm fine if you squash and force-push, or we can just "squashing now" while merging at the very end.

+@ggould-tri for platform review per schedule, please.
\CC @rpoyner-tri for tomorrow in case Grant times out today.

> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-:-NPJQrI_1UOTBiKB_RDI:bgej0pu)* status: 4 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @RussTedrake)

___
*[`tutorials/authoring_leaf_systems.ipynb` line 365 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJTgcZ5Y4uuUmTZB2Y:-NPJTgcZ5Y4uuUmTZB2Z:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/authoring_leaf_systems.ipynb#L365)):*
> ```
>     "## Systems can \"publish\"\n",
>     "\n",
>     "In addition to methods that update the state, and methods the evaluate an output port, another supported method in a `LeafSystem` is a callback to \"publish\". A \"publish\" method can modify no state: they are useful for broadcasting data outside of the systems framework (e.g. via a message-passing protocol like ROS), for terminating a simulation, for detecting errors, and for forcing boundaries between integration steps. They are declared in much the same way as other system callbacks."
> ```

typo



_Suggestion:_
```
that
```
___
*[`tutorials/authoring_leaf_systems.ipynb` line 365 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJTmuL3ZVj-DoDXPAW:-NPJTmuL3ZVj-DoDXPAX:b-cxut9l) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/authoring_leaf_systems.ipynb#L365)):*
> ```
>     "## Systems can \"publish\"\n",
>     "\n",
>     "In addition to methods that update the state, and methods the evaluate an output port, another supported method in a `LeafSystem` is a callback to \"publish\". A \"publish\" method can modify no state: they are useful for broadcasting data outside of the systems framework (e.g. via a message-passing protocol like ROS), for terminating a simulation, for detecting errors, and for forcing boundaries between integration steps. They are declared in much the same way as other system callbacks."
> ```

nit I stumbled on this the first read-though.



_Suggestion:_
```
cannot modify any state
```
___
*[`tutorials/working_with_diagrams.ipynb` line 212 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJYtYvCQgI87OzlpJW:-NPJYtYvCQgI87OzlpJX:bly1sid) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/working_with_diagrams.ipynb#L212)):*
> ```
>    "metadata": {},
>    "source": [
>     "More interesting is the subsystem `Context`s. You should understand that a diagram's `Context` is just an organized collection of the subsystem's `Context`s. You can access those subsystem `Context`s directly, most often using [`GetMyContextFromRoot()`](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system.html#ae7fa91d2b2102457ced3361207724e52). Note that since diagrams can be subsystems in other diagrams, this method will recurse through the potentially nested diagram to recover the correct sub-`Context`.\n",
> ```

BTW The first time I read this, I had a difficult time making it through the text.  Once I read the code and and came back here again, it seemed OK the second time around.

I don't have many good suggestions for improvements, though.  Pictures would help a lot (depicting the storage of nested contexts) but that might be a lot of work.

The one suggestion I do have is where you talk about "brittle" above, we could be more direct.  It is _almost always wrong_ to operate on a diagram context's "get state" or "get parameters" or anything like that.  (The exception is SetTime.) The rule of thumb should be first to obtain the LeafContext that you want using GetMyContextFromRoot, and then operate on that.
___
*[`tutorials/working_with_diagrams.ipynb` line 239 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJXr7XBILTTeXG7rKu:-NPJXr7Y549SUdUaqBXA:btlogcj) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/working_with_diagrams.ipynb#L239)):*
> ```
>     "pendulum_state = pendulum.get_state(pendulum_context)\n",
>     "print(\n",
>     "    f\"θ={pendulum_state.theta()}, θ̇={pendulum_state.thetadot()}\"\n",
> ```

nit For me both here in the raw text, and in the notebook preview, the dot renders on the `=` character, not the theta character.  Is that as-intended?



_Code quote:_
```
θ̇=
```

**Review by ggould-tri — COMMENTED** [review]
Looks like I'm not going to finish this one before EOB today.
-@ggould-tri +@rpoyner-tri 
It looked fine as far as I read, though :-)

> Reviewed 2 of 6 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-:-NPJo12E9XMJQ0dis5O1:b-axic67)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18873)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri, @jwnimmer-tri, and @rpoyner-tri)

___
*[`tutorials/authoring_leaf_systems.ipynb` line 365 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJTgcZ5Y4uuUmTZB2Y:-NPKuleL-oVim373qMz8:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/authoring_leaf_systems.ipynb#L365)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`tutorials/authoring_leaf_systems.ipynb` line 365 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJTmuL3ZVj-DoDXPAW:-NPKur1KCfyAO61HytqK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/authoring_leaf_systems.ipynb#L365)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I stumbled on this the first read-though.
</blockquote></details>

Done.
___
*[`tutorials/working_with_diagrams.ipynb` line 212 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJYtYvCQgI87OzlpJW:-NPKvHSK-Txwdv2_tDgW:b-v7f5eu) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/working_with_diagrams.ipynb#L212)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The first time I read this, I had a difficult time making it through the text.  Once I read the code and and came back here again, it seemed OK the second time around.

I don't have many good suggestions for improvements, though.  Pictures would help a lot (depicting the storage of nested contexts) but that might be a lot of work.

The one suggestion I do have is where you talk about "brittle" above, we could be more direct.  It is _almost always wrong_ to operate on a diagram context's "get state" or "get parameters" or anything like that.  (The exception is SetTime.) The rule of thumb should be first to obtain the LeafContext that you want using GetMyContextFromRoot, and then operate on that.
</blockquote></details>

Done. I tried to do something like a picture using html to indicate the structure of the nexted contexts.  WDYT?

Re: "almost always wrong".  There are times when it's correct to operate directly on the diagram context data, via get_state, get_parameters.  (e.g. when I'm writing an algorithm that treats the diagram as a System). So I'm not sure I would go so far as saying "almost always wrong"?
___
*[`tutorials/working_with_diagrams.ipynb` line 239 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJXr7XBILTTeXG7rKu:-NPKw-se4I1-VDSfzQD1:b-inibj9) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/working_with_diagrams.ipynb#L239)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For me both here in the raw text, and in the notebook preview, the dot renders on the `=` character, not the theta character.  Is that as-intended?
</blockquote></details>

hrm.  everything looks correct to me in chrome (including the version your code quote).  The dot is over the theta.  I've added a space, does that help?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18873)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[`tutorials/working_with_diagrams.ipynb` line 212 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJYtYvCQgI87OzlpJW:-NPL-nl898VdbiqzrlMN:b-7mxakq) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/working_with_diagrams.ipynb#L212)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done. I tried to do something like a picture using html to indicate the structure of the nexted contexts.  WDYT?

Re: "almost always wrong".  There are times when it's correct to operate directly on the diagram context data, via get_state, get_parameters.  (e.g. when I'm writing an algorithm that treats the diagram as a System). So I'm not sure I would go so far as saying "almost always wrong"?
</blockquote></details>

That's true.  Treating the entire diagram State all at once makes sense.  Where things go wrong is trying to access fractions of that state without using `GetMyContextFromRoot`.  I'll take a look at the new text.
___
*[`tutorials/working_with_diagrams.ipynb` line 239 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPJXr7XBILTTeXG7rKu:-NPL00yEDsnL-EOB5pxu:bj46y23) ([raw file](https://github.com/RobotLocomotion/drake/blob/cffa4d22864382cf90ed7f102a7db5c6443884c4/tutorials/working_with_diagrams.ipynb#L239)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

hrm.  everything looks correct to me in chrome (including the version your code quote).  The dot is over the theta.  I've added a space, does that help?  
</blockquote></details>

Yes, it's mostly better now.  The dot is over the space, but that's easy enough to associate with the prior; the dotted equals sign was the awkward part.

(FYI on github.com the original also looked fine.  It must be a fonts thing.)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18873)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @RussTedrake)

___
*[`tutorials/working_with_diagrams.ipynb` line 218 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPL25Y9E0JzjZcZ3IUl:-NPL25YAEd-3Bgh0iz1r:b-40fij5) ([raw file](https://github.com/RobotLocomotion/drake/blob/1502a5d42b69369ef828673be570d78d62fbc517/tutorials/working_with_diagrams.ipynb#L218)):*
> ```
>     "<li>PID-controlled Pendulum (with θ shifted by π) Context (of a Diagram)</li>\n",
>     "  <ul style=\"list-style:none\">\n",
>     "    <li>⮑ PID-controlled Pendulum Context (of a Diagram)</li>\n",
> ```

nit My computer doesn't have "return right" in any font.  This might be too special of a character to use.

Maybe ↳ would work instead.  That one _is_ on my computer.



_Code quote:_
```
⮑
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18873)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`tutorials/authoring_leaf_systems.ipynb` line 627 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPNa5WX1e7DBvltiKe1:-NPNkhTyB9QBxjRtnWkj:b-ug5dsj) ([raw file](https://github.com/RobotLocomotion/drake/blob/1502a5d42b69369ef828673be570d78d62fbc517/tutorials/authoring_leaf_systems.ipynb#L627)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

btw Do these changes (version, hash) matter at all? More discussion below.
</blockquote></details>

Nope.  They are diff spam that comes from saving a notebook.  We haven't yet written any tooling to automatically purge this data (and then enforce its absence via lint).
___
*[`tutorials/working_with_diagrams.ipynb` line 475 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPNYwi65TXYU_hdxL0p:-NPNkp5AA8OGrrarLkQj:bdi5ung) ([raw file](https://github.com/RobotLocomotion/drake/blob/1502a5d42b69369ef828673be570d78d62fbc517/tutorials/working_with_diagrams.ipynb#L475)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW I'm not sure if this metadata is a good or bad thing. Perhaps the more experienced tutorial maintainers know. Most questionable looking to me are `metadata.version` and `vscode.interpreter.hash`.  Are they just noisy hints, or do they cause warnings or errors in some environments? However, it looks like we have a couple of existing examples and no complaints, so maybe it's fine?
</blockquote></details>

See above.  It doesn't hurt anything (other than my feelings).

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18873)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`tutorials/working_with_diagrams.ipynb` line 475 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPNYwi65TXYU_hdxL0p:-NPNlYB89HkXpSu1fh57:bg92dp5) ([raw file](https://github.com/RobotLocomotion/drake/blob/1502a5d42b69369ef828673be570d78d62fbc517/tutorials/working_with_diagrams.ipynb#L475)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

See above.  It doesn't hurt anything (other than my feelings).
</blockquote></details>

Mine too. :shrug:

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18873)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`tutorials/working_with_diagrams.ipynb` line 218 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18873#-NPL25Y9E0JzjZcZ3IUl:-NPNxCugEAy7erDmJ2DN:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1502a5d42b69369ef828673be570d78d62fbc517/tutorials/working_with_diagrams.ipynb#L218)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit My computer doesn't have "return right" in any font.  This might be too special of a character to use.

Maybe ↳ would work instead.  That one _is_ on my computer.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
(Forcing in now, not waiting for Debug builds.)

**Pull request merged**
