### PR TITLE
[workspace] Upgrade googlebenchmark to latest release 1.5.6

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
https://github.com/google/benchmark/releases/tag/v1.5.6

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15718)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15718)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
FYI @rpoyner-tri still needs your emoji.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15718#-:-Mj0HAMhAQlwVWPZJksP:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
