### PR TITLE
Add AngleBetweenVectorsCost

### PR DESCRIPTION
**Pull request by hongkai-dai**
As requested on https://stackoverflow.com/questions/73571388/request-for-addanglebetweenvectorscost

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17821)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17821#-:-NAz2_5IBPYiMwfdVu8d:b-w629gj)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @aykut-tri)

**Review by hongkai-dai — COMMENTED** [review]
Just realized that Aykut is in Turkey.

-@aykut-tri for feature review
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17821#-:-NBSr9J63qJDvvgy5vGd:b-a9p0ca)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@ggould-tri for platform review, per rotation.  (@ggould-tri, it might help to know that the code here closely parallels e.g. the `PositionCost` / `OrientationCost` implementations)

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17821#-:-NBcwy4_84Sz1Uy_0Y_f:b-n3wiux)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[`multibody/inverse_kinematics/angle_between_vectors_cost.cc` line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBcw5bg3O1Np2SIMXeR:-NBcw5bg3O1Np2SIMXeS:b-3ld3li) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/angle_between_vectors_cost.cc#L52)):*
> ```cpp
>   AutoDiffVecXd cos_theta;
>   constraint_.Eval(x, &cos_theta);
>   (*y)(0) = c_ * (1 - cos_theta(0));
> ```

btw -- hoorah.  i was hoping you'd implemented it this way.
___
*[`multibody/inverse_kinematics/test/angle_between_vectors_cost_test.cc` line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBcwjwy4ZdzFAvFlM-S:-NBcwjwy4ZdzFAvFlM-T:boewebg) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/test/angle_between_vectors_cost_test.cc#L112)):*
> ```cpp
>   cos_theta = a_W.dot(b_W) / (a_W.norm() * b_W.norm());
>   CheckCases(*cost, *cost_ad, q, c * (1 - cos_theta));
> }
> ```

btw -- this all looks familiar.  thanks!

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17821)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[`multibody/inverse_kinematics/test/angle_between_vectors_cost_test.cc` line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBcwjwy4ZdzFAvFlM-S:-NBej6w3CFtNyqx2dfpE:b-y1i8jl) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/test/angle_between_vectors_cost_test.cc#L112)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- this all looks familiar.  thanks!
</blockquote></details>

Yeah, thanks for providing the template, it is very easy to follow and migrate!

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; nits.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17821#-:-NBmYGHt3aw1YF8zPnGq:b-tq5ici)* status: 3 unresolved discussions (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/angle_between_vectors_cost.h` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBmWL8NEIf74tIVqiVp:-NBmWL8NEIf74tIVqiVq:b-287arv) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/angle_between_vectors_cost.h#L39)):*
> ```objc
>    * @throws std::exception if `b_B` is close to zero.
>    * @throws std::exception if `angle_lower` is negative.
>    * @throws std::exception if `angle_upper` ∉ [`angle_lower`, π].
> ```

minor:  `angle_lower` and `angle_upper` are not defined, nor does this restriction appear to exist.



_Code quote:_
```objc
   * @throws std::exception if `angle_lower` is negative.
   * @throws std::exception if `angle_upper` ∉ [`angle_lower`, π].
```
___
*[`multibody/inverse_kinematics/angle_between_vectors_cost.h` line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBmXjvGDwkwpovswTGr:-NBmXjvGDwkwpovswTGs:bq59vui) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/angle_between_vectors_cost.h#L75)):*
> ```objc
>               VectorX<symbolic::Expression>*) const override;
> 
>   const AngleBetweenVectorsConstraint constraint_;
> ```

minor:  It might be slightly clearer to comment that this is not really a constraint on the program but instead is just being used to avoid duplicating the math.
___
*[`multibody/inverse_kinematics/inverse_kinematics.h` line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBmX13K3g1Relkp6Fwl:-NBmX13K3g1Relkp6Fwm:bqddcvz) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/inverse_kinematics.h#L276)):*
> ```objc
>       const Eigen::Ref<const Eigen::Vector3d>& na_A,
>       const Frame<double>& frameB,
>       const Eigen::Ref<const Eigen::Vector3d>& nb_B, double c);
> ```

nit:  This is a somewhat counterintuitive line breaking choice; the one in the .cc file is visually clearer.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17821)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/angle_between_vectors_cost.h` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBmWL8NEIf74tIVqiVp:-NBrfLFe-1XZpbQpa-DU:b-l2tt7p) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/angle_between_vectors_cost.h#L39)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  `angle_lower` and `angle_upper` are not defined, nor does this restriction appear to exist.
</blockquote></details>

Done, good catch.
___
*[`multibody/inverse_kinematics/inverse_kinematics.h` line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBmX13K3g1Relkp6Fwl:-NBrfvryD8lAqVMv1hGO:bhylnu2) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/inverse_kinematics.h#L276)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  This is a somewhat counterintuitive line breaking choice; the one in the .cc file is visually clearer.
</blockquote></details>

I can't do the line break as the cc file. Here this function is inside the `InverseKinematics` class in the header file, so it has two indentations, one from InverseKinematics class, one from this function. On the other hand, the cc file only has one level of indentation from the function. Hence in cc file it can put both the frame and the vector in the same line without exceeding 80 LOC, while it can't do that in the .h file.

**Comment by jwnimmer-tri** [comment]
*[`multibody/inverse_kinematics/inverse_kinematics.h` line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBmX13K3g1Relkp6Fwl:-NBrgi0p2xJr34okIXXc:b-uk40gy) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/inverse_kinematics.h#L276)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I can't do the line break as the cc file. Here this function is inside the `InverseKinematics` class in the header file, so it has two indentations, one from InverseKinematics class, one from this function. On the other hand, the cc file only has one level of indentation from the function. Hence in cc file it can put both the frame and the vector in the same line without exceeding 80 LOC, while it can't do that in the .h file.
</blockquote></details>

I think all ggould was saying was that `double c` would be more visually clear if it were on the next line, all by itself:

```c++
  solvers::Binding<solvers::Cost> AddAngleBetweenVectorsCost(
      const Frame<double>& frameA,
      const Eigen::Ref<const Eigen::Vector3d>& na_A,
      const Frame<double>& frameB,
      const Eigen::Ref<const Eigen::Vector3d>& nb_B,
      double c);
```

With all of the other arguments each on their own line, a reader will not necessarily notice the little `double c` tucked away at the end of the line.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17821)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/inverse_kinematics.h` line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17821#-NBmX13K3g1Relkp6Fwl:-NBri1tx7PBVJ6uWtHSF:bxj872y) ([raw file](https://github.com/robotlocomotion/drake/blob/f9ed1c4e70d79bdd71d56fa760b1c6786433b8b5/multibody/inverse_kinematics/inverse_kinematics.h#L276)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think all ggould was saying was that `double c` would be more visually clear if it were on the next line, all by itself:

```c++
  solvers::Binding<solvers::Cost> AddAngleBetweenVectorsCost(
      const Frame<double>& frameA,
      const Eigen::Ref<const Eigen::Vector3d>& na_A,
      const Frame<double>& frameB,
      const Eigen::Ref<const Eigen::Vector3d>& nb_B,
      double c);
```

With all of the other arguments each on their own line, a reader will not necessarily notice the little `double c` tucked away at the end of the line.
</blockquote></details>

Yes, `c` hanging out there is making a diligent attempt to slip away unnoticed.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17821)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
