### PR TITLE
Add mccormick envelope for bilinear product, with or without logarithmic binning

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6775)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@gizatt for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-KqeV0APIBHpaabI6alr:biagjkq)*

**Comment by gizatt** [comment]
Apologies for delay, still out of town! Single trivial typo noted, otherwise looks great. Gonna go ahead and give :lgtm: to not hold you up since I won't be near a computer for most of tomorrow.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 156 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KquNXfPl2dxCbP9u29d:-KquNXfQNeWA0VUsrtON:b-gsyeso) ([raw file](https://github.com/robotlocomotion/drake/blob/35118ae8710c59388c26a88174c27c1647962bb0/drake/solvers/mixed_integer_optimization_util.h#L156)):*
> ```objc
>  * @param Bx Bx(i) can only take binary values. Bx indicate which interval is
>  * activated. Depending on whether we use logarithmic binning or not, Bx has
>  * different meanning. If `logarithmic_binning` = true, and Bx represents
> ```

"meanning" -> "meaning", here and below

---

*[drake/solvers/mixed_integer_optimization_util.h, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KquNaUm59z2xjpOPzpj:-KquNaUm59z2xjpOPzpk:b9wa8j0) ([raw file](https://github.com/robotlocomotion/drake/blob/35118ae8710c59388c26a88174c27c1647962bb0/drake/solvers/mixed_integer_optimization_util.h#L163)):*
> ```objc
>  * @param By By(i) can only take binary values. By indicate which interval is
>  * activated. Depending on whether we use logarithmic binning or not, By has
>  * different meanning. If `logarithmic_binning` = true, and By represents
> ```

"meanning" -> "meaning"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-KquOZSXQnHaPdM4_btI:btbehmk)*

**Comment by hongkai-dai** [comment]
Thanks for reviewing it! Don't worry, I am not blocked by this PR. Hope you have fun in your trip.

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 156 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KquNXfPl2dxCbP9u29d:-KqxgcOZszbB5iiaMdk-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35118ae8710c59388c26a88174c27c1647962bb0/drake/solvers/mixed_integer_optimization_util.h#L156)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

"meanning" -> "meaning", here and below
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KquNaUm59z2xjpOPzpj:-Kqxgciq3q_eoNgy7x6V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35118ae8710c59388c26a88174c27c1647962bb0/drake/solvers/mixed_integer_optimization_util.h#L163)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

"meanning" -> "meaning"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-Kqxe-dQn8DIMnoUm0ir:b-hywll8)*

**Comment by hongkai-dai** [comment]
+@seancurtis-tri for platform review please.

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-KqxjqbhbvtmC7svtUQm:b-tnzbcp)*

**Comment by SeanCurtis-TRI** [comment]
First pass.  PTAL.

---

Reviewed 2 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 154 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqxmTdGxcNaOzJX0tcm:-KqxmTdHKm1AGuto8Ia9:bqx60as) ([raw file](https://github.com/robotlocomotion/drake/blob/ffa2e4e7e706be2b8e8a04a1272e777fef9bb58e/drake/solvers/mixed_integer_optimization_util.h#L154)):*
> ```objc
>  * @param phi_x The end points of the intervals for `x`.
>  * @param phi_y The end points of the intervals for `y`.
>  * @param Bx Bx(i) can only take binary values. Bx indicate which interval is
> ```

BTW The documentation for `Bx` and `By` is almost verbatim duplicated (modulo a couple of symbols). It also leads to really long @param descriptions. Furthermore, the overall description doesn't even allude to the encoding of the binary variables. 

I'd recommend the following:

1. Move the discussion of bin encoding and the relationships of `Bx`, `By`, and `logarithmic_binning` into the overall function summary. (I.e., the intervals can be encoded linearly or logarithmically...)
2. Shorten the docs for `Bx` and `By` as, "The binary variable for the interval in which `x|y` stays encoded as described above."
3. Shorten the `logarithmic_binning` doc to allude to the overall discussion.

Finally, see the comments on `By` for grammar tweaks.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 161 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqxos2pFken9rbZaUXD:-Kqxos2q63ca-yJDTZ46:bocrsru) ([raw file](https://github.com/robotlocomotion/drake/blob/ffa2e4e7e706be2b8e8a04a1272e777fef9bb58e/drake/solvers/mixed_integer_optimization_util.h#L161)):*
> ```objc
>  * Bx(j) = 0 j ≠ i, then the interval [φx(i), φx(i + 1)] is activated.
>  * If Bx(i) = 1, then `x` is in the interval [φx(i), φx(i + 1)].
>  * @param By By(i) can only take binary values. By indicate which interval is
> ```

1) Because `By` looks just like the word "By" this is an *incredibly* confusing sentence. To prevent the confusion, you could either include back ticks on `By` or not start a sentence with it (so the capitalization doesn't look like the sentence capital).
2) Verb conjugation "indicate" implies `By` is plural (i.e., the values). Subsequent verbs suggest singular ("By *has* different meanings", "By *represents* integer", etc.)

---

*[drake/solvers/mixed_integer_optimization_util.h, line 167 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqxqfzipPFg6myn8wzi:-KqxqfzjFn212i8ZAx3a:bp0ori1) ([raw file](https://github.com/robotlocomotion/drake/blob/ffa2e4e7e706be2b8e8a04a1272e777fef9bb58e/drake/solvers/mixed_integer_optimization_util.h#L167)):*
> ```objc
>  * is activated. If `logarithmic_binning` = false, and By(i) is 1, all other
>  * By(j) = 0, j ≠ i, then the interval [φy(i), φy(i + 1)] is activated.
>  * @param logarithmic_binning Determines the meaning of the binary Bx and By. If
> ```

BTW As a bool, this makes call sites seem a bit inscrutable. (See `rotation_constraint.cc`).  Have you considered an enum instead? At the very least, the call sites would be documented so there aren't bare `true`s and `false`s.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 294 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqxr6kofY1qJHGK4qWI:-Kqxr6kofY1qJHGK4qWJ:bmia9vy) ([raw file](https://github.com/robotlocomotion/drake/blob/ffa2e4e7e706be2b8e8a04a1272e777fef9bb58e/drake/solvers/test/mixed_integer_optimization_util_test.cc#L294)):*
> ```cpp
>   // We fix x and y to each intervals.
>   // We expect the optimum obtained at one of the vertices of the tetrahedron.
>   MatrixXDecisionVariable lambda;
> ```

For RAII you should probably do:

```C++
MatrixXDecisionVariable lambda =
    AddBilinear...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-Kqy1AoyxhdbfuyG8i0w:bv0wqc7)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 154 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqxmTdGxcNaOzJX0tcm:-KqyLR4swWskJQiUUAFX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ffa2e4e7e706be2b8e8a04a1272e777fef9bb58e/drake/solvers/mixed_integer_optimization_util.h#L154)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The documentation for `Bx` and `By` is almost verbatim duplicated (modulo a couple of symbols). It also leads to really long @param descriptions. Furthermore, the overall description doesn't even allude to the encoding of the binary variables. 

I'd recommend the following:

1. Move the discussion of bin encoding and the relationships of `Bx`, `By`, and `logarithmic_binning` into the overall function summary. (I.e., the intervals can be encoded linearly or logarithmically...)
2. Shorten the docs for `Bx` and `By` as, "The binary variable for the interval in which `x|y` stays encoded as described above."
3. Shorten the `logarithmic_binning` doc to allude to the overall discussion.

Finally, see the comments on `By` for grammar tweaks.
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 161 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqxos2pFken9rbZaUXD:-Kqy3rTr5_U7NGAon-Ul:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ffa2e4e7e706be2b8e8a04a1272e777fef9bb58e/drake/solvers/mixed_integer_optimization_util.h#L161)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

1) Because `By` looks just like the word "By" this is an *incredibly* confusing sentence. To prevent the confusion, you could either include back ticks on `By` or not start a sentence with it (so the capitalization doesn't look like the sentence capital).
2) Verb conjugation "indicate" implies `By` is plural (i.e., the values). Subsequent verbs suggest singular ("By *has* different meanings", "By *represents* integer", etc.)

</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 167 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqxqfzipPFg6myn8wzi:-Kqy5zHE4f9g-m2Dlfcz:b62cdjb) ([raw file](https://github.com/robotlocomotion/drake/blob/ffa2e4e7e706be2b8e8a04a1272e777fef9bb58e/drake/solvers/mixed_integer_optimization_util.h#L167)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As a bool, this makes call sites seem a bit inscrutable. (See `rotation_constraint.cc`).  Have you considered an enum instead? At the very least, the call sites would be documented so there aren't bare `true`s and `false`s.
</blockquote></details>

Done. Good call. Switched to using enum class.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 294 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqxr6kofY1qJHGK4qWI:-KqyLKeRdlw2aVVfEze9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ffa2e4e7e706be2b8e8a04a1272e777fef9bb58e/drake/solvers/test/mixed_integer_optimization_util_test.cc#L294)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

For RAII you should probably do:

```C++
MatrixXDecisionVariable lambda =
    AddBilinear...
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Basically content (modulo a typo). I've got a BTW about compiling against gcc. Otherwise +@jwnimmer-tri for final review.

---

Reviewed 2 of 3 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 154 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqyP6tyr9h_rx6dCTuo:-KqyP6tzZVC_oqJnom4D:b-7ixshv) ([raw file](https://github.com/robotlocomotion/drake/blob/8b10802f085de324ee327b57c1fd494417e925ee/drake/solvers/mixed_integer_optimization_util.h#L154)):*
> ```objc
>  * [φx(i+1), φy(j+1), φx(i+1)*φy(j+1)]
>  * We use two different encoding schemes on the binary variables, to determine
>  * which interval is active. We can choose either linear orlogarithmic binning.
> ```

typo: missing space

---

*[drake/solvers/mixed_integer_optimization_util.h, line 159 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqyPEKYfdiXFJyV0_1E:-KqyPEKYfdiXFJyV0_1F:b-hxdy8q) ([raw file](https://github.com/robotlocomotion/drake/blob/8b10802f085de324ee327b57c1fd494417e925ee/drake/solvers/mixed_integer_optimization_util.h#L159)):*
> ```objc
>  * interval. When using logarithmic binning, we use ⌈log₂(N)⌉ binary variables.
>  * If these binary variables represent integer M in the reflected Gray code,
>  * then the continuous variable is in the M'th interval.
> ```

BTW This is *beautiful* documentation.  So perfectly clear.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 203 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqyPZaOSoTurSR9n3Xu:-KqyPZaOSoTurSR9n3Xv:byzue2l) ([raw file](https://github.com/robotlocomotion/drake/blob/8b10802f085de324ee327b57c1fd494417e925ee/drake/solvers/mixed_integer_optimization_util.h#L203)):*
> ```objc
>       DRAKE_ASSERT(Bx.rows() == phi_x.rows() - 1);
>       DRAKE_ASSERT(By.rows() == phi_y.rows() - 1);
>       break;
> ```

BTW I suspect if you build against gcc you're going to get a compiler error. It doesn't seem to do a very good job of recognizing you've accounted for all of the enumeration values. Please confirm that this builds with gcc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-KqyQ2GqcFipdS29rsW1:b-af96or)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) And given @gizatt vacation status, you should go ahead and remove him from the discussion he's implicitly keeping open.

---

Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-KqyQEdlBfiLNnGTmULr:bv0ftpo)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 154 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqyP6tyr9h_rx6dCTuo:-Kqy_DHnMJTRxbbTHN-b:b-376vyo) ([raw file](https://github.com/robotlocomotion/drake/blob/8b10802f085de324ee327b57c1fd494417e925ee/drake/solvers/mixed_integer_optimization_util.h#L154)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

typo: missing space
</blockquote></details>

Done. Good catch!

---

*[drake/solvers/mixed_integer_optimization_util.h, line 203 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqyPZaOSoTurSR9n3Xu:-Kqy_Gk2rTksd_q2cyP_:b8t2dtx) ([raw file](https://github.com/robotlocomotion/drake/blob/8b10802f085de324ee327b57c1fd494417e925ee/drake/solvers/mixed_integer_optimization_util.h#L203)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I suspect if you build against gcc you're going to get a compiler error. It doesn't seem to do a very good job of recognizing you've accounted for all of the enumeration values. Please confirm that this builds with gcc.
</blockquote></details>

Good call! I built it with gcc-5 and the compiler is happy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775)*

**Comment by SeanCurtis-TRI** [comment]
I tried removing @gizatt from the two outstanding discussions. Now it's been "short-handed". We'll need @jwnimmer-tri to ack those discussions so they can go away.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-Kqytj5OGl8V-DSFj1PD:b-eukn92)*

**Comment by jwnimmer-tri** [comment]
You can usually solve "short-handed" by marking yourself "satisfied" instead of "discussing" or "neutral".

**Comment by jwnimmer-tri** [comment]
FYI @soonho-tri Do you want to examine whether ll of the `.template cast<Expression>` here are warranted?

:lgtm: 

---

Reviewed 1 of 4 files at r2, 1 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 143 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz86Iy814umMyP3eLU:-Kqz86Iy814umMyP3eLV:b-eapyve) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/mixed_integer_optimization_util.h#L143)):*
> ```objc
>   kLogarithmic,
>   kLinear
> };
> ```

Feature reviewers, are you happy to have `drake::solvers::Binning` (specifically, that its placed directly in `drake::solvers` namespace) magically come from `mixed...util.h`?  Is the term "Binning" likely to conflict with other desires to mention "Binning" that would not have only these two cases?

---

*[drake/solvers/mixed_integer_optimization_util.h, line 196 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz7mH8OzASorrFXmJK:-Kqz7mH9UWXOpmlf_3EI:b-6wgk2n) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/mixed_integer_optimization_util.h#L196)):*
> ```objc
>     const DerivedBy& By, Binning binning) {
>   switch (binning) {
>     case Binning::kLogarithmic :
> ```

BTW nit No space before final `:`.

---

*[drake/solvers/rotation_constraint.cc, line 954 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz8_vh_Nq1Vwldx5MT:-Kqz8_vi7AAqS0jAN6de:b8yz0kd) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/rotation_constraint.cc#L954)):*
> ```cpp
> // in the form x * y, we relax (x, y, w) to be in the convex hull of the
> // curve w = x * y, and replace all the bilinear term x * y with w. For more
> // details, @see AddBilinearProductMcCormickEnvelopeLogarithmicSos2.
> ```

I think this comment change is a lie (stale)?

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 212 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz93LqguCWFZfUpo46:-Kqz93LqguCWFZfUpo47:b-2q5ghy) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/test/mixed_integer_optimization_util_test.cc#L212)):*
> ```cpp
> GTEST_TEST(TestBilinearProductMcCormickEnvelopeSos2, AddConstraint) {
>   // Test if the return argument from
>   // AddBilinearProductMcCormickEnvelopeLogarithmicSos2 has the right type.
> ```

Also a stale comment?

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 272 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz9SMMJxHbpjrQSups:-Kqz9SMMJxHbpjrQSupt:b-5mwlys) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/test/mixed_integer_optimization_util_test.cc#L272)):*
> ```cpp
>         phi_x_{Eigen::VectorXd::LinSpaced(num_interval_x_ + 1, 0, 1)},
>         phi_y_{Eigen::VectorXd::LinSpaced(num_interval_y_ + 1, 0, 1)},
>         Bx_size_{binning_ == Binning::kLogarithmic? CeilLog2(num_interval_x_)
> ```

BTW nit Missing whitespace before `?`.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 340 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz9ctq7j8cnP_qBK-G:-Kqz9ctq7j8cnP_qBK-H:beylkdg) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/test/mixed_integer_optimization_util_test.cc#L340)):*
> ```cpp
> 
>     Bx_cnstr.constraint()->UpdateLowerBound(Bx_val);
>     Bx_cnstr.constraint()->UpdateUpperBound(Bx_val);
> ```

FYI Not a new defect but `cnstr` is not an allowed type of abbreviation per GSG.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-Kqz9Ak91DnArxfN-SUt:b8gicag)*

**Comment by soonho-tri** [comment]
I think the use of `.cast()` is necessary. 
 - We have an implicit conversion from `symbolic::Variable` to `symbolic::Expression`
 - We can pass an `Eigen::Matrix<Variable>` where `Eigen::Matrix<Expression>` is expected.

However, we *can't* pass an `Eigen::Matrix<Variable>` where `Eigen::Ref<Eigen::Matrix<Expression>>` is expected AFAIK. We are hitting this case here. Please correct me if I'm wrong.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-KqzFEbtcZzuQnGjmxuv:b-a63vrv)*

**Comment by jwnimmer-tri** [comment]
Sure.  The unit test in particular caught my eye, where no `Ref` is involved:
```c++
Vector1<symbolic::Expression> Bx =
    prog.NewBinaryVariables<1>().cast<symbolic::Expression>();
```

The assignment operator seems like it could work (promote), though perhaps not yet supported.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-KqzO_ewnyqMO0JqF-aR:b-ji1afo)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 225 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqzPuOHBCdRQR33OhPd:-KqzPuOHBCdRQR33OhPe:b-1e4eic) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/test/mixed_integer_optimization_util_test.cc#L225)):*
> ```cpp
>       prog.NewBinaryVariables<1>().cast<symbolic::Expression>();
>   Vector2<symbolic::Expression> By =
>       prog.NewBinaryVariables<2>().cast<symbolic::Expression>();
> ```

As @jwnimmer-tri , you can reduce these lines into:
```c++
  Vector1<symbolic::Expression> Bx = prog.NewBinaryVariables<1>();
  Vector2<symbolic::Expression> By = prog.NewBinaryVariables<2>();
```
(but I haven't tested with `gcc-4.9` though).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 143 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz86Iy814umMyP3eLU:-Kr1lme9kRlyWL4NoSRM:b-dlh1a0) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/mixed_integer_optimization_util.h#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Feature reviewers, are you happy to have `drake::solvers::Binning` (specifically, that its placed directly in `drake::solvers` namespace) magically come from `mixed...util.h`?  Is the term "Binning" likely to conflict with other desires to mention "Binning" that would not have only these two cases?
</blockquote></details>

Done. I changed the name to `IntervalBinning` to make it more specific.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 196 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz7mH8OzASorrFXmJK:-Kr1lvbPnO9r5haFyBXd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/mixed_integer_optimization_util.h#L196)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit No space before final `:`.
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.cc, line 954 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz8_vh_Nq1Vwldx5MT:-Kr1m3oImEAcEV1DF0gE:b-376vyo) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/rotation_constraint.cc#L954)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this comment change is a lie (stale)?
</blockquote></details>

Done. Good catch!

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 212 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz93LqguCWFZfUpo46:-Kr1mChFefaBXdSAzGHd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/test/mixed_integer_optimization_util_test.cc#L212)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Also a stale comment?
</blockquote></details>

Done.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 225 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-KqzPuOHBCdRQR33OhPd:-Kr1mMWPFekVpLoPYYeT:b-x9tmwj) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/test/mixed_integer_optimization_util_test.cc#L225)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

As @jwnimmer-tri , you can reduce these lines into:
```c++
  Vector1<symbolic::Expression> Bx = prog.NewBinaryVariables<1>();
  Vector2<symbolic::Expression> By = prog.NewBinaryVariables<2>();
```
(but I haven't tested with `gcc-4.9` though).
</blockquote></details>

Done. I compiled and tested it with gcc-4.9

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 272 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz9SMMJxHbpjrQSups:-Kr1mSEPYxhRaYpkf4nJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/test/mixed_integer_optimization_util_test.cc#L272)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit Missing whitespace before `?`.
</blockquote></details>

Done.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 340 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-Kqz9ctq7j8cnP_qBK-G:-Kr1m_dXmZkd2L4xEiRL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d17dbc72bd6c30cf5f5f0969369a3249033b4ec8/drake/solvers/test/mixed_integer_optimization_util_test.cc#L340)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Not a new defect but `cnstr` is not an allowed type of abbreviation per GSG.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6775#-:-Kr26P-j94THlCvM1xOI:b-l70wzf)*

**Pull request merged**
