### PR TITLE
[pydrake] Add verbosity option to configure_logging

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Motivated by #16901.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16941)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16941)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/common/__init__.py, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16941#-N-TbgCF9Y69PUEhPTLd:-N-TbgCF9Y69PUEhPTLe:bad14s7) ([raw file](https://github.com/robotlocomotion/drake/blob/c8e357595c60338af56dd2d1b97ea9330add0c19/bindings/pydrake/common/__init__.py#L35)):*
> ```Python
>     logger = _logging.getLogger("drake")
>     if verbose:
>         set_log_level("trace")
> ```

Working

This branch still needs unit testing.

**Review by EricCousineau-TRI — COMMENTED** [review]
İ like it! Just a small nit below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16941#-:-N-TmU1lDitW2NdTQCYX:bm6uvpu)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[bindings/pydrake/common/__init__.py, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16941#-N-TpCOx6jwjrxuW51mX:-N-TpCOx6jwjrxuW51mY:b-1ekpwp) ([raw file](https://github.com/robotlocomotion/drake/blob/c8e357595c60338af56dd2d1b97ea9330add0c19/bindings/pydrake/common/__init__.py#L34)):*
> ```Python
>     _logging.basicConfig(level=_logging.INFO, format=format)
>     logger = _logging.getLogger("drake")
>     if verbose:
> ```

nit `verbose` is a bit ambiguous. Initially, I thought it meant "tell me what this function is doing" rather than "set the output to be verbose".

Consider qualifying as `set_level_to_verbose` (or something better)?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16941)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[bindings/pydrake/common/__init__.py, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16941#-N-Tpb2L5B3FvqZU2LJx:-N-UDxOE5tTnbMtpdYW_:b-e8izys) ([raw file](https://github.com/robotlocomotion/drake/blob/c8e357595c60338af56dd2d1b97ea9330add0c19/bindings/pydrake/common/__init__.py#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For developers, the rationale of this statement may not be clear (lack of synchrony between C++ and Python logging levels).

Consider adding a code comment below, perhaps pointing to #16942 for context?
</blockquote></details>

I've tried rewriting the description to be more clear, but I'm not sure what you're getting at.  Maybe you can explain more what you're thinking about?

To me, this function is simply: "Set up logging to not suck.  By default, it will use a reasonable level of detail ('info' only).  If you want more spam, you may opt-in".
___
*[bindings/pydrake/common/__init__.py, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16941#-N-TpCOx6jwjrxuW51mX:-N-UDozTDvG6PHZqKvva:b-896fig) ([raw file](https://github.com/robotlocomotion/drake/blob/c8e357595c60338af56dd2d1b97ea9330add0c19/bindings/pydrake/common/__init__.py#L34)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `verbose` is a bit ambiguous. Initially, I thought it meant "tell me what this function is doing" rather than "set the output to be verbose".

Consider qualifying as `set_level_to_verbose` (or something better)?
</blockquote></details>

Done?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16941)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[bindings/pydrake/common/__init__.py, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16941#-N-Tpb2L5B3FvqZU2LJx:-N-UHUXRBY7qN89r6ESu:b-ac3spa) ([raw file](https://github.com/robotlocomotion/drake/blob/c8e357595c60338af56dd2d1b97ea9330add0c19/bindings/pydrake/common/__init__.py#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I've tried rewriting the description to be more clear, but I'm not sure what you're getting at.  Maybe you can explain more what you're thinking about?

To me, this function is simply: "Set up logging to not suck.  By default, it will use a reasonable level of detail ('info' only).  If you want more spam, you may opt-in".
</blockquote></details>

The above messages don't talk about lack of synchrony between C++ and Python logging levels; "set it up to not suck" is semi-helpful, but may not help users trying to debug why their log messages aren't appearing.
If a user uses this function w/ `spammy=False`, then later uses `getLogger("drake").setLevel(5)`, they won't get the messages they want. They will have to be familiar with `set_log_level`.
Consider stating here (as well) that this method is preferred over `set_log_level`; also consider moving code example here.
For development traceability, cite #16942
___
*[bindings/pydrake/common/__init__.py, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16941#-N-TpCOx6jwjrxuW51mX:-N-UGPvL1-zx6XoMsVHm:bjgugnk) ([raw file](https://github.com/robotlocomotion/drake/blob/c8e357595c60338af56dd2d1b97ea9330add0c19/bindings/pydrake/common/__init__.py#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

Er, at this point, I prefer `verbose`, but will mark myself satisfied

**Comment by jwnimmer-tri** [comment]
My goal in this PR was to agree on some small band-aid to help make the easy thing easy and well-supported (opting-in to debugging), but not to tumble into the weeds of documenting all of the `set_log_level` related arcana.  None of that mess should exist at all, never mind have paragraphs of confusing documentation related to it.  Given the review discussions, I doesn't not seem like there is any overlap between the two of us on what an acceptable band-aid looks like.

Therefore, my plan is to pause this PR and try to finish the robust solution (#16942) instead of trying to negotiate a compromise here.  You're welcome to de-assign yourself in the meantime if you like; I'll be sure to tag you again in case this unpauses.

**Comment by EricCousineau-TRI** [comment]
Sounds good, a resolution of #16942 would be awesome!
Despite my above comments, I think present state of this or #16901 is still a strict improvement over what is on `master`, but yeah, will defer to you. Thanks!

**Comment by jwnimmer-tri** [comment]
Given #17069, I don't think this sugar is sufficiently useful to carry over the finish line.

**Pull request closed without merging**
