### PR TITLE
Solver symmetry check

### PR DESCRIPTION
**Pull request by edrumwri**
This PR corrects two index-related bugs with the constraint solver.  The first is the placement of the F_iM_LT block in the LCP matrix (its starting indices were incorrect). The second is the starting index of the generic unilateral constraint forces/impulses in the solution vector. Both of these index problems can only be identified in certain circumstances: non-sliding contacts and unilateral constraints must be present (for acceleration-based problems), for instance.

The PR also adds a function that checks the symmetry of the Delassus matrix. The matrix is constructed in such a manner that symmetry is automatically enforced; this function verifies that, if constructed manually, the Delassus matrix would be symmetric.

Unit tests are added that expose the uncorrected bugs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7310)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@amcastro-tri for feature review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-:-Kwvg07YlOphg_dSi1rq:brbsdox)*

**Comment by amcastro-tri** [comment]
I'll need an f2f @edrumwri. I haven't looked at this code for a long while and I find names like `nk` very difficult to track. 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 318 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE5fTthh2r6PfE6F_1:-KxE5fTuoqzXW0iqA3t5:by7bjs0) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/constraint_solver.h#L318)):*
> ```objc
>       ProblemData* modified_problem_data) const;
> 
>   mutable drake::solvers::MobyLCPSolver<T> lcp_;
> ```

why is it we did not need mutable before?

---

*[drake/multibody/constraint/constraint_solver.h, line 637 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE5lnY66aK5zxktaoH:-KxE5lnY66aK5zxktaoI:b-cqxgc2) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/constraint_solver.h#L637)):*
> ```objc
>   const int num_spanning_vectors = std::accumulate(problem_data.r.begin(),
>                                                    problem_data.r.end(), 0);
>   const int nk = num_spanning_vectors * 2;
> ```

what's `nk`? would you add a more `style guide naming` or add a comment on what it is?

---

*[drake/multibody/constraint/constraint_solver.h, line 1223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE79Ijvi0kKSIMadC8:-KxE79Ijvi0kKSIMadC9:b-z0e0mt) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/constraint_solver.h#L1223)):*
> ```objc
> void ConstraintSolver<T>::CheckAccelConstraintMatrix(
>     const ConstraintAccelProblemData<T>& problem_data,
>     const MatrixX<T>& MM) const {
> ```

I forget, is this for you the Delassus operator?

---

*[drake/multibody/constraint/constraint_solver.h, line 1226 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE7HGQZ2jH86WBMq7N:-KxE7HGQZ2jH86WBMq7O:bgt82q) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/constraint_solver.h#L1226)):*
> ```objc
>   // Get numbers of types of contacts.
>   const int num_spanning_vectors = std::accumulate(problem_data.r.begin(),
>                                  problem_data.r.end(), 0);
> ```

BTW odd indent?

---

*[drake/multibody/constraint/constraint_solver.h, line 1237 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE7_V8dmmudSW8RG0a:-KxE7_V8dmmudSW8RG0b:b-zg6g00) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/constraint_solver.h#L1237)):*
> ```objc
>   const int ngv = problem_data.tau.size();  // generalized velocity dimension.
>   const int nr = num_spanning_vectors;
>   const int nk = nr * 2;
> ```

I forget here again. This is because your "spanning vectors" are mirrored to consider plus and minus directions right?

---

*[drake/multibody/constraint/constraint_solver.h, line 1245 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE7vUiDZYIvNh42BFq:-KxE7vUiDZYIvNh42BFr:bmbf9nh) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/constraint_solver.h#L1245)):*
> ```objc
>   // Get the block of M that was set through a transposition operation.
>   Eigen::Ref<const MatrixX<T>> L_iM_FT =
>       MM.block(num_contacts + nk + num_non_sliding, num_contacts, nl, nr);
> ```

I forget again what your `MM` has. Why `nk + num_non_sliding` and not just `nk`?

---

*[drake/multibody/constraint/constraint_solver.h, line 1251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE8Y4LUhcVyvOOw2lq:-KxE8Y4LUhcVyvOOw2lr:b-wiuli0) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/constraint_solver.h#L1251)):*
> ```objc
>   MatrixX<T> iM_FT(ngv, nr);
>   ComputeInverseInertiaTimesGT(iM, FT, nr, &iM_FT);
>   ComputeConstraintSpaceComplianceMatrix(L, nl, iM_FT, L_iM_FT_true);
> ```

Isn't this verification chasing its tail? I mean, isn't this the same code we use to compute this `MM` block in the first place?

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1495 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxDzQVNk3aYj1FW5zwF:-KxDzQVNk3aYj1FW5zwG:b-j0a7he) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1495)):*
> ```cpp
> }
> 
> // Tests the rod in a two-point contact configuration with both sticking and
> ```

Does this comment still apply to the newly modified test? 
Would it be worth having two tests? one with two and one with one contact so that you do not get rid of this test?
On a second read, why are you modifying this test at all?

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1503 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxDyvhr0OBmTyxARfL9:-KxDyvhr0OBmTyxARfLA:b-ffn1q4) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1503)):*
> ```cpp
>   SetRodToRestingHorizontalConfig();
> 
>   // Set the velocity on the rod to move to the right.
> ```

should this comment be here? or did  you actually forget to set something?

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1551 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4fXyGFfcf7NQ9HP2:-KxE4fXyGFfcf7NQ9HP3:b-6ploo0) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1551)):*
> ```cpp
> 
> // Tests that the cross-term interaction between contact forces and generic
> // unilateral constraints is computed correctly.
> ```

BTW .... at the acceleration level

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1559 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4FUpFKewrrn2ELtD:-KxE4FUpFKewrrn2ELtE:b-bflr1g) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1559)):*
> ```cpp
>   // static coefficient of friction to frictionless as well.
>   rod_->set_mu_coulomb(0.0);
>   rod_->set_mu_static(0.0);
> ```

could you comment on why it is important for this test that these friction coefficients are zero? wouldn't the test work for non-zero coefficients as well?

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1578 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE2zzQyTtafHVt-zbM:-KxE2zzQyTtafHVt-zbN:b80syrm) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1578)):*
> ```cpp
>   // upward direction.
>   const int ngc = get_rod_num_coordinates();
>   accel_data_->kL.resize(1);
> ```

why not to place these below after you define `num_limit_constraints`?
and then you'd have:
```
accel_data_->kL.resize(num_limit_constraints);
accel_data_->gammaL.setZero(num_limit_constraints);
```

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1586 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE3c4K6mYGunR51Y2-:-KxE3c4K6mYGunR51Y20:biopjrk) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1586)):*
> ```cpp
>   MatrixX<double> L(accel_data_->kL.size(), ngc);
>   L.setZero();
>   L(0, 1) = -1;
> ```

BTW, maybe add comment saying why is "minus" one? I assume it is because it is a unilateral constraint with a normal pointing downwards?

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1615 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4bvnYuKyAGfXX6NQ:-KxE4bvor4pZGtPacytH:b-9cu1s3) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1615)):*
> ```cpp
> 
> // Tests that the cross-term interaction between contact forces and generic
> // unilateral constraints is computed correctly.
> ```

BTW .... at the velocity level

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1623 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4jKtMAqtpR22byUP:-KxE4jKtMAqtpR22byUQ:b-uc8acf) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1623)):*
> ```cpp
>   // static coefficient of friction to frictionless as well.
>   rod_->set_mu_coulomb(0.0);
>   rod_->set_mu_static(0.0);
> ```

BTW ditto about why zero friction coefficients.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1639 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4obQVLQpJOx6HGL6:-KxE4obQVLQpJOx6HGL7:bhnpc9b) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1639)):*
> ```cpp
>   // downward direction.
>   const int ngc = get_rod_num_coordinates();
>   vel_data_->kL.resize(1);
> ```

ditto about using hard coded ones here

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1640 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE50W3DWU0acKVJQgH:-KxE50W3DWU0acKVJQgI:b-wwwk7v) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1640)):*
> ```cpp
>   const int ngc = get_rod_num_coordinates();
>   vel_data_->kL.resize(1);
>   vel_data_->gammaL.setOnes(1) *= cfm_;
> ```

BTW, `setConstant(cfm_)`?

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1659 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE5N9RD6DQfwuNYvuk:-KxE5N9RD6DQfwuNYvul:budt3mt) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1659)):*
> ```cpp
>   // Reverse the velocity, which will make the contact constraints inactive;
>   // the limit constraint should be the only active constraint.
>   vel_data_->v *= -1;
> ```

I would place this line right after `SetRodToSlidingImpactingHorizontalConfig(true);` so it is clear where the original `v` came from.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-:-KxE8nIJTASE3w1aGocz:b-mj6yt7)*

**Comment by amcastro-tri** [comment]
Lots of comments resolved per f2f. Just a few small ones remain. :lgtm: 

---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-:-KxEhR0ZkWxkJGqOMNpE:b-acnvdy)*

**Comment by edrumwri** [comment]
Thank you for the excellent feature review, Alejandro. +@sammy-tri for platform review (per regular rotation) please.

---

Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 318 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE5fTthh2r6PfE6F_1:-KxEyiahTL2bY_eM4Kkn:b-tnle9q) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/constraint_solver.h#L318)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why is it we did not need mutable before?
</blockquote></details>

Done. (I had removed this but had forgot to push).

---

*[drake/multibody/constraint/constraint_solver.h, line 1226 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE7HGQZ2jH86WBMq7N:-KxF-2GBzQLcmKY8q_J8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/constraint_solver.h#L1226)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW odd indent?
</blockquote></details>

Done.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1495 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxDzQVNk3aYj1FW5zwF:-KxF4QJRHXqUsjIwcmsi:b-c87w92) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1495)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Does this comment still apply to the newly modified test? 
Would it be worth having two tests? one with two and one with one contact so that you do not get rid of this test?
On a second read, why are you modifying this test at all?
</blockquote></details>

It never should have been modified. Fixed.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1503 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxDyvhr0OBmTyxARfL9:-KxF4Q26N2QaNhvptPyi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1503)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

should this comment be here? or did  you actually forget to set something?
</blockquote></details>

Done.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1551 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4fXyGFfcf7NQ9HP2:-KxF4_v7T5U_a-AHkxzt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1551)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW .... at the acceleration level
</blockquote></details>

Done.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1559 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4FUpFKewrrn2ELtD:-KxF9xV34d0R9ogcBMjG:bnq3mm7) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1559)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could you comment on why it is important for this test that these friction coefficients are zero? wouldn't the test work for non-zero coefficients as well?
</blockquote></details>

FYI They're no longer zero. I had them be zero (and the force reversed) because I wanted the test to ensure that the limit forces were nonzero, but that occurs anyway since the rod is in a horizontal configuration.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1578 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE2zzQyTtafHVt-zbM:-KxF4jTFv3oD_-0njgiq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1578)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why not to place these below after you define `num_limit_constraints`?
and then you'd have:
```
accel_data_->kL.resize(num_limit_constraints);
accel_data_->gammaL.setZero(num_limit_constraints);
```
</blockquote></details>

Done.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1586 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE3c4K6mYGunR51Y2-:-KxF6nAN-dg0nmHVEQIQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1586)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, maybe add comment saying why is "minus" one? I assume it is because it is a unilateral constraint with a normal pointing downwards?
</blockquote></details>

Done.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1615 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4bvnYuKyAGfXX6NQ:-KxF4w-K0PAex2rYeGhD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1615)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW .... at the velocity level
</blockquote></details>

Done.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1623 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4jKtMAqtpR22byUP:-KxF9os_wMFxm9T3GvEG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1623)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW ditto about why zero friction coefficients.
</blockquote></details>

Done.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1639 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE4obQVLQpJOx6HGL6:-KxF5W8QijvSN7xu3wrO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1639)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto about using hard coded ones here
</blockquote></details>

Done.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1640 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE50W3DWU0acKVJQgH:-KxF5Jta4Rrx5Ch2bJi-:b-3wx9se) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1640)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, `setConstant(cfm_)`?
</blockquote></details>

I don't like that, because it throws away the sizing information. Still, thanks for pointing out the existence of this function to me.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1659 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxE5N9RD6DQfwuNYvuk:-KxF626wETQZ55W8x9Nf:b-ywi4f5) ([raw file](https://github.com/robotlocomotion/drake/blob/bf21ebf1b9c9fa0c663a4ca98d98e337ef445c11/drake/multibody/constraint/test/constraint_solver_test.cc#L1659)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I would place this line right after `SetRodToSlidingImpactingHorizontalConfig(true);` so it is clear where the original `v` came from.
</blockquote></details>

I moved it upward, but the "v" isn't created until CalcImpactProblemData().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-:-KxFAUPadxtcaHsEs13I:b-w7l5e6)*

**Comment by sammy-tri** [comment]
This one may take me a little while.  Apologies in advance if I don't get to it until tomorrow.

---

Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-:-KxFS16lxVc0gwwtwaA9:b-r4jnfc)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1553 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxG1dFZ_JkDMizpyYOQ:-KxG1dFZ_JkDMizpyYOR:bm2mna3) ([raw file](https://github.com/robotlocomotion/drake/blob/b8a20ccfeee6c3f06bcce48f2666879434e8c04a/drake/multibody/constraint/test/constraint_solver_test.cc#L1553)):*
> ```cpp
>   // Set the sliding coefficient of friction to zero (it won't be used) and the
>   // static coefficient of friction to a relatively large value.
>   rod_->set_mu_coulomb(0.0);
> ```

BTW this one still is zero in case you meant to change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310)*

**Comment by edrumwri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1553 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxG1dFZ_JkDMizpyYOQ:-KxG7anDx8XEqZUTd39h:b-k5kpmd) ([raw file](https://github.com/robotlocomotion/drake/blob/b8a20ccfeee6c3f06bcce48f2666879434e8c04a/drake/multibody/constraint/test/constraint_solver_test.cc#L1553)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW this one still is zero in case you meant to change it.
</blockquote></details>

BTW No, I did not (PTAL at the comment).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 1124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxJ6ltK9kpI7JCRW45E:-KxJ6ltK9kpI7JCRW45F:b-eglvhx) ([raw file](https://github.com/robotlocomotion/drake/blob/b8a20ccfeee6c3f06bcce48f2666879434e8c04a/drake/multibody/constraint/constraint_solver.h#L1124)):*
> ```objc
>   }
> 
>   // Alias constraint force segments.
> ```

BTW I don't know why this feels weird to me, but the previous version of this file had two code sections which began with this comment and then created the same aliases.  After this change, they're creating `fL` differently.  Feel free to ignore if the reason would be obvious to someone familiar with the state of the art here, but perhaps a comment is warranted if the reason for the difference is non-obvious.

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1517 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxJ82ruVMZT9nF1cfc3:-KxJ82rvJi1C7cgh2Liq:b3ho4ql) ([raw file](https://github.com/robotlocomotion/drake/blob/b8a20ccfeee6c3f06bcce48f2666879434e8c04a/drake/multibody/constraint/test/constraint_solver_test.cc#L1517)):*
> ```cpp
>   // Modify the tangent velocity on the left contact to effect a sliding
>   // contact. This modification can be imagined as the left end of the rod
>   // is touching a conveyer belt moving to the belt.
> ```

"conveyer belt moving to the belt" seems like a strange phrase (also typo "conveyor")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-:-KxJ8ajgOziV-y_aERVf:bvb1a6z)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 1124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxJ6ltK9kpI7JCRW45E:-KxJBF-WjPdWETCg6fas:b-p6k6yb) ([raw file](https://github.com/robotlocomotion/drake/blob/b8a20ccfeee6c3f06bcce48f2666879434e8c04a/drake/multibody/constraint/constraint_solver.h#L1124)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I don't know why this feels weird to me, but the previous version of this file had two code sections which began with this comment and then created the same aliases.  After this change, they're creating `fL` differently.  Feel free to ignore if the reason would be obvious to someone familiar with the state of the art here, but perhaps a comment is warranted if the reason for the difference is non-obvious.
</blockquote></details>

BTW Sammy, I'm missing what you're saying by "creating fL differently". Would you mind elaborating?

---

*[drake/multibody/constraint/test/constraint_solver_test.cc, line 1517 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxJ82ruVMZT9nF1cfc3:-KxJBS1uD82DdjqU31Yc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8a20ccfeee6c3f06bcce48f2666879434e8c04a/drake/multibody/constraint/test/constraint_solver_test.cc#L1517)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

"conveyer belt moving to the belt" seems like a strange phrase (also typo "conveyor")
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310)*

**Comment by sammy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 1124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxJ6ltK9kpI7JCRW45E:-KxJCig9CKCcrOVVNFMm:b-r7hlr) ([raw file](https://github.com/robotlocomotion/drake/blob/b8a20ccfeee6c3f06bcce48f2666879434e8c04a/drake/multibody/constraint/constraint_solver.h#L1124)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW Sammy, I'm missing what you're saying by "creating fL differently". Would you mind elaborating?
</blockquote></details>

Prior to this change, both `SolveConstraintProblem` (above) and `SolveImpactProblem` (here) had the same code creating aliases for `fN`, `fD_plus`, `fD_minus`, `fL`, and `fF`.  After this change, the code aliasing `fL` in `SolveConstraintProblem` is `const auto fL = zz.segment(num_contacts + num_non_sliding + nk, num_limits)` vs `const auto fL = zz.segment(num_contacts * 2 + num_spanning_vectors * 2, num_limits)` here (the other aliases remain the same).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/constraint/constraint_solver.h, line 1124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-KxJ6ltK9kpI7JCRW45E:-KxJE7UslOeYiDDt4HIL:bwnv6sx) ([raw file](https://github.com/robotlocomotion/drake/blob/b8a20ccfeee6c3f06bcce48f2666879434e8c04a/drake/multibody/constraint/constraint_solver.h#L1124)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Prior to this change, both `SolveConstraintProblem` (above) and `SolveImpactProblem` (here) had the same code creating aliases for `fN`, `fD_plus`, `fD_minus`, `fL`, and `fF`.  After this change, the code aliasing `fL` in `SolveConstraintProblem` is `const auto fL = zz.segment(num_contacts + num_non_sliding + nk, num_limits)` vs `const auto fL = zz.segment(num_contacts * 2 + num_spanning_vectors * 2, num_limits)` here (the other aliases remain the same).
</blockquote></details>

Ah- got it! Yes, that was a bug that this PR corrected. In the acceleration-level case, the sliding and non-sliding contacts must be treated separately. In the velocity-level case, both are treated identically. This means that the problem vectors and also the starting offset for the limit forces/impulses differ.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-:-KxJI5oFLnvE4HGoPIgZ:bnfp4nl)*

**Comment by edrumwri** [comment]
Thanks Sammy!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7310#-:-KxJJGQm-SZjaYyarOnc:be4ycjs)*

**Pull request merged**
