### PR TITLE
Move wheel creation to Jammy, drop older Python

### LINKED ISSUE #20953: Switch Ubuntu wheel builds to Jammy
Here in the list of targets ...

https://github.com/RobotLocomotion/drake/blob/295eb0f07591f932e06ffd5c3576b51409ebfd7d/tools/wheel/wheel_builder/linux.py#L30-L34

... we drop 3.8 and 3.9 from the list entirely, and for 3.10 and up we change to build the wheel on jammy, and test it on jammy (except 3.12, which I guess we'll still test on Mantric for now.

Note that this will also probably involve changes to `download_release_candidate`, the release playbook, and drake-ci.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Change Linux wheel builds to use Jammy, rather than Focal, as the build host. Remove Python targets that are older than Jammy. Remove Focal-specific hacks from wheel builds.

Fixes #20953.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20961)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: none) -- we'll count on #20952 to announce the user-facing changes.

+@jwnimmer-tri for both reviews :lgtm: -- I've tested this locally, and all three wheels come out fine.

I think it's OK to merge this, even with CI using Focal's docker configuration to run a Jammy wheel builder.  We'll want to clean that up eventually, but I don't think its on the critical path and this PR on its own unblocks some other work.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20961#-:-Nqrklgo-tM1zqVMX7H9:bf22cb3)* status: 1 unresolved discussion, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20961#-NqrkWk99KGBcvkAEP_h:-NqrkWk99KGBcvkAEP_i:b-6xelcr) (no related file):*
nit These docs also need some updates as par of this PR:
- doc/_pages/release_playbook.md (regarding the number of `.whl` files to anticipate)
- tools/release_engineering/download_release_candidate.py (the list of`.whl` files to download)

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20961)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20961#-NqrkWk99KGBcvkAEP_h:-NqxJEUCBvVFMWK3mKGM:b-2god7d) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit These docs also need some updates as par of this PR:
- doc/_pages/release_playbook.md (regarding the number of `.whl` files to anticipate)
- tools/release_engineering/download_release_candidate.py (the list of`.whl` files to download)
</blockquote></details>

Done (I pushed fixes).

___

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
The CI wheel came out fine:

```
jwnimmer@call-cps:~/tmp$ env/bin/pip install https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.2024.2.18.17.54.18%2Bgit8c1253c5-cp310-cp310-manylinux_2_35_x86_64.whl
Collecting drake==0.0.2024.2.18.17.54.18+git8c1253c5
  Downloading https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.2024.2.18.17.54.18%2Bgit8c1253c5-cp310-cp310-manylinux_2_35_x86_64.whl (77.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.6/77.6 MB 12.3 MB/s eta 0:00:00
Collecting matplotlib
...
Successfully installed PyYAML-6.0.1 contourpy-1.2.0 cycler-0.12.1 drake-0.0.2024.2.18.17.54.18+git8c1253c5 fonttools-4.49.0 kiwisolver-1.4.5 matplotlib-3.8.3 numpy-1.26.4 packaging-23.2 pillow-10.2.0 pydot-2.0.0 pyparsing-3.1.1 python-dateutil-2.8.2 six-1.16.0
jwnimmer@call-cps:~/tmp$ env/bin/python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydrake.all import *
>>> Expression(22.0)
<Expression "22">
```

**Comment by jwnimmer-tri** [comment]
Pro forma we should have someone double-check the release playbook and tools edits I made, but let's do that after-the-fact (i.e., during the next release) so that we can get this unblocked.

LMK post-merge if anyone sees any problems here.

**Review by mwoehlke-kitware — COMMENTED** [review]
Edits :lgtm: (just eyeballing; I think it's probably okay to wait until next release to try them in anger).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20961#-:-Nr16pS46xi_8ETSnX0R:btqp44x)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
