### PR TITLE
Add Bazel support for Sphinx

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #3129.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5404)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Feature review TBD.
+@soonho-tri for platform review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-:-KeMKfpQg1-nRkhN3KLG:bwgvlxw)*

**Comment by liangfok** [comment]
+@liangfok for feature review since I'm interested in using this feature.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-:-KeMXlq7ltLyN3Qfs56w:b-1xjf43)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/_serve_sphinx.py, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KeOI6dzRUGR_m3_LYih:-KeOI6dzRUGR_m3_LYii:b-xzlt0r) ([raw file](https://github.com/robotlocomotion/drake/blob/3d122a1297311d1890c8d0d61d41ab937f67a5b8/drake/doc/_serve_sphinx.py#L33)):*
> ```Python
> 
> # Try the default browser, then wait.
> print >>sys.stderr, "Serving sphix docs ... use Ctrl-C to exit."
> ```

BTW, typo of `sphinx`.

---

*[drake/doc/_serve_sphinx.py, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KeOGJxNbBiXn_y-gHr9:-KeOGJxNbBiXn_y-gHrA:b-bf69ov) ([raw file](https://github.com/robotlocomotion/drake/blob/3d122a1297311d1890c8d0d61d41ab937f67a5b8/drake/doc/_serve_sphinx.py#L35)):*
> ```Python
> print >>sys.stderr, "Serving sphix docs ... use Ctrl-C to exit."
> try:
>     subprocess.check_call(["sensible-browser", file_url])
> ```

FYI, `sensible-browser` doesn't work in OSX. 
How about the following?
```python
import webbrowser
...
# Try the default browser, then wait.
try:
    webbrowser.open(file_url)
```

Reference: https://docs.python.org/3/library/webbrowser.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404)*

**Comment by soonho-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/_serve_sphinx.py, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KeOGJxNbBiXn_y-gHr9:-KeOIUzFVpO7301QWC_L:b7oro0z) ([raw file](https://github.com/robotlocomotion/drake/blob/3d122a1297311d1890c8d0d61d41ab937f67a5b8/drake/doc/_serve_sphinx.py#L35)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, `sensible-browser` doesn't work in OSX. 
How about the following?
```python
import webbrowser
...
# Try the default browser, then wait.
try:
    webbrowser.open(file_url)
```

Reference: https://docs.python.org/3/library/webbrowser.html

</blockquote></details>

Accidentally shared python3 doc. Here is python2 doc of the module: https://docs.python.org/2/library/webbrowser.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 6 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KeOIlNerhoX1fRXH88K:-KeOIlNerhoX1fRXH88L:b87drv8) ([raw file](https://github.com/robotlocomotion/drake/blob/3d122a1297311d1890c8d0d61d41ab937f67a5b8/drake/doc/documentation_instructions.rst#L30)):*
> ```reStructuredText
> 
> This will rebuild the website content and serve it to your web browser for
> preview.  On Ubuntu, it will open a web browser tab using ``sensible-browser``;
> ```

FYI, if you choose to use `webbrowser`, this part needs an update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/_serve_sphinx.py, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KeOI6dzRUGR_m3_LYih:-KeOLUmfs8WvnGTZVaOD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d122a1297311d1890c8d0d61d41ab937f67a5b8/drake/doc/_serve_sphinx.py#L33)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, typo of `sphinx`.
</blockquote></details>

Done.

---

*[drake/doc/_serve_sphinx.py, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KeOGJxNbBiXn_y-gHr9:-KeON_ocoyu8xEsrXbor:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d122a1297311d1890c8d0d61d41ab937f67a5b8/drake/doc/_serve_sphinx.py#L35)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Accidentally shared python3 doc. Here is python2 doc of the module: https://docs.python.org/2/library/webbrowser.html
</blockquote></details>

Done.

---

*[drake/doc/documentation_instructions.rst, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KeOIlNerhoX1fRXH88K:-KeONa_k28jkwHy1PgRK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d122a1297311d1890c8d0d61d41ab937f67a5b8/drake/doc/documentation_instructions.rst#L30)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, if you choose to use `webbrowser`, this part needs an update.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/_serve_sphinx.py, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KeOGJxNbBiXn_y-gHr9:-KeOPVIHU1YysM-MWmv4:b-b8grh5) ([raw file](https://github.com/robotlocomotion/drake/blob/3d122a1297311d1890c8d0d61d41ab937f67a5b8/drake/doc/_serve_sphinx.py#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI, `webbrowser.open("./index.html")` doesn't work while `webbrowser.open(http_url)` works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/_serve_sphinx.py, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KeOGJxNbBiXn_y-gHr9:-KeOYAS_0TITgGnXA9Mn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d122a1297311d1890c8d0d61d41ab937f67a5b8/drake/doc/_serve_sphinx.py#L35)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, `webbrowser.open("./index.html")` doesn't work while `webbrowser.open(http_url)` works.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404)*

**Comment by soonho-tri** [comment]
:lgtm: (also tested on a Mac)

---

Reviewed 4 of 6 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-:-KeP6tnxA4NgpI2f_9hY:b1nxauj)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KePFkqiVARmVY-NQ8R9:-KePFkqiVARmVY-NQ8RA:b-7pqnu) (no related file):*
BTW, @jwnimmer-tri , do you think it's worth documenting our policy on having files with leading underscore (`_`)? I remember Grant asked about it in another PR and we have another instance here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-KePFkqiVARmVY-NQ8R9:-KePKEZxszvhWQ-s1EKr:b8m6ypm) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, @jwnimmer-tri , do you think it's worth documenting our policy on having files with leading underscore (`_`)? I remember Grant asked about it in another PR and we have another instance here.
</blockquote></details>

Done.  I don't think it was warranted here, so I just removed the leading underscore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by liangfok** [comment]
:lgtm: I tested and verified that this works. Thanks!

---

Reviewed 3 of 7 files at r1, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-:-KeQP1GLdCb-jPxAtg9p:bhc3iyb)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform mentor.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-:-KeQQZxTB3HCnhQD-PCm:bdeul1z)*

**Comment by sherm1** [comment]
:lgtm: (one ignorable BTW)

---

Reviewed 3 of 7 files at r1, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/documentation_instructions.rst, line 25 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-Kea-o0rJJg7PwTOqHp7:-Kea-5SE0cAp_F-dRv0O:b-ms322g) ([raw file](https://github.com/robotlocomotion/drake/blob/e7cefcce5fcb6e629935d84847ef69392fa12484/drake/doc/documentation_instructions.rst#L25)):*
> ```reStructuredText
> 
> At the moment, only the website (Sphinx) documentation is supported via the
> Bazel build::
> ```

BTW, mention explicitly that you mean "not Doxygen"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5404#-:-Kea-xH-pANFmlpyk7GG:b-zbf0dy)*

**Pull request merged**
