### PR TITLE
Separate DiagramBuilder from Diagram.

### LINKED ISSUE #3068: Split DiagramBuilder out from Diagram
All pre-finalize operations should be in `DiagramBuilder`, the Build method of which should return a Diagram.

cc @bradking

### PR DESCRIPTION
**Pull request by david-german-tri**
Update some legacy methods in DiagramBuilder to use SystemPortDescriptor.

Fixes #3068.

@bradking for feature review, @jwnimmer-tri for platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3188)

### CODE REVIEW

**Comment by sherm1** [comment]
:+1: this seems cleaner. BTW reminder -- there is still an ownership issue to address (discussed elsewhere but I don't think there is a separate issue filed). In System 1 users can (and do) write methods like CreatePriusSystem() that return a shared_ptr to a System object that can be arbitrarily complex internally but owns everything it contains. That can be "cascaded" or whatever to make fancier Systems. We should have equivalent capability (with unique_ptr rather than shared_ptr). Currently there has to be some other object that owns the sub-systems in a Diagram. :lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUDUZdp5s-okJI3t6J:-KPUDUZdp5s-okJI3t6K:b-nd365t) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L48)):*
> ```objc
> 
> /// Diagram is a System composed of one or more constituent Systems, arranged
> /// in a directed graph where the vertices are the constituent Systems
> ```

BTW with multiple input and output ports I believe there are now multiple directed graphs formed within a system diagram.

---

*[drake/systems/framework/test/diagram_test.cc, line 33 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUEjQ1QBg-JQkwLne6:-KPUEjQ1QBg-JQkwLne7:bmugehw) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/test/diagram_test.cc#L33)):*
> ```cpp
>     builder.Connect(adder0_->get_output_port(0), adder1_->get_input_port(0));
>     builder.Connect(adder0_->get_output_port(0), adder2_->get_input_port(0));
>     builder.Connect(adder1_->get_output_port(0), adder2_->get_input_port(1));
> ```

BTW nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-:-KPUGCTpGDE-0kg0gP44:bvwdwg2)*

**Comment by david-german-tri** [comment]
Yep, fully agree.  I'm not certain where the correct moment in the lifecycle to transfer ownership is; will circle back to it at some point.

---

Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram.h, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUDUZdp5s-okJI3t6J:-KPUKzZyup_gqHeeErD2:blmykfx) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L48)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW with multiple input and output ports I believe there are now multiple directed graphs formed within a system diagram.
</details>
Definitely true.  This should be addressed as part of (or immediately after) #2890.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-:-KPULGYmdOMDwWJP6zDN:b-jv90a9)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions, all commit checks successful.

---

*[drake/systems/framework/diagram.h, line 57 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUA7O4klN14AYeQ1yJ:-KPUA7O4klN14AYeQ1yK:bptdhgh) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L57)):*
> ```objc
> 
>   /// Unless you know what you're doing, use a DiagramBuilder instead of
>   /// calling this constructor directly.
> ```

This is good, but I believe the input arguments still need some kind of explanation, if nothing else of the invariants 

---

*[drake/systems/framework/diagram.h, line 75 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUDsbs7hrv7zjMeMge:-KPUDsbtFVLu38imsslv:b-rz3umx) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L75)):*
> ```objc
>       ExportOutput(id);
>     }
>   }
> ```

It seems to me like there are several invariants here that aren't being checked.  That sorted_systems had no duplicates; that the dependency_graph, input_port_ids_, and output_port_ids all refer to systems within the sorted_systems set; that the port indexes throughout are within range (currently only the exported ones are checked); and that the dependency_graph order is consistent with sorted_systems (should be very cheap to check here, versus computing it originally).

---

*[drake/systems/framework/diagram.h, line 77 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUEjnUnRsRypd1mBXo:-KPUEjnUnRsRypd1mBXp:be3xnp5) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L77)):*
> ```objc
>   }
> 
>   virtual ~Diagram() {}
> ```

I think `override` not `virtual`?

---

*[drake/systems/framework/diagram.h, line 183 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUFeqvW2QQwdSFC3L_:-KPUFeqwEc6EI-H1ZiGK:bmn94aw) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L183)):*
> ```objc
>   // Expose the given port as an input of the Diagram.
>   void ExportInput(const PortIdentifier& port) {
>     const System<T>* sys = port.first;
> ```

BTW consider `const System<T>* const sys` pervasively, if you like.

---

*[drake/systems/framework/diagram.h, line 247 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUDg6xe5BHJWSKLRcz:-KPUDg6xe5BHJWSKLRd-:b80thu7) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L247)):*
> ```objc
> 
>   // The topologically sorted list of Systems in this Diagram. Only computed
>   // when Finalize is called.
> ```

No more `Finalize`.

---

*[drake/systems/framework/diagram_builder.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUILJj_HOOYPZorsy4:-KPUILJj_HOOYPZorsy5:beaeqdo) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L26)):*
> ```objc
>   /// Declares that input port @p dest is connected to output port @p src.
>   void Connect(const SystemPortDescriptor<T>& src,
>                const SystemPortDescriptor<T>& dest) {
> ```

Sanity check that src and dest have the correct face?

For the check, consider ABORT_UNLESS; its really important, probably easy to screw up, and cheap to check.

---

*[drake/systems/framework/diagram_builder.h, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJe4GFQbiXnxOT3h4:-KPUJe4GFQbiXnxOT3h5:b-yn0pht) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L31)):*
> ```objc
>     PortIdentifier dest_id{dest.get_system(), dest.get_index()};
>     PortIdentifier src_id{src.get_system(), src.get_index()};
>     ThrowIfInputAlreadyWired(dest_id);
> ```

BTW Consider doing this first, before making any other state edits?

---

*[drake/systems/framework/diagram_builder.h, line 38 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJDSPsL3-ZYRAuFVw:-KPUJDSQalIO8JaA8Mr0:bpedtug) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L38)):*
> ```objc
>   /// to the entire Diagram.
>   void ExportInput(const SystemPortDescriptor<T>& input) {
>     DRAKE_ASSERT(input.get_face() == kInputPort);
> ```

BTW consider ABORT_UNLESS; its really important, probably easy to screw up, and cheap to check.

---

*[drake/systems/framework/diagram_builder.h, line 41 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJhq0XuTkiJNsUXYk:-KPUJhq0XuTkiJNsUXYl:b-yn0pht) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L41)):*
> ```objc
>     Register(input.get_system());
>     PortIdentifier id{input.get_system(), input.get_index()};
>     ThrowIfInputAlreadyWired(id);
> ```

BTW Consider doing this first, before making any other state edits?

---

*[drake/systems/framework/diagram_builder.h, line 44 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJZc5p-z55bzulFsi:-KPUJZc6hSx0u-S9x-ci:b-aifldh) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L44)):*
> ```objc
>     input_port_ids_.push_back(id);
>     diagram_input_set_.insert(id);
>     systems_.insert(input.get_system());
> ```

This appears to duplicate the `Register` call above?

---

*[drake/systems/framework/diagram_builder.h, line 50 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJE4n-AW1Ttz-SCiL:-KPUJE4n-AW1Ttz-SCiM:bpedtug) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L50)):*
> ```objc
>   /// output of the entire diagram.
>   void ExportOutput(const SystemPortDescriptor<T>& output) {
>     DRAKE_ASSERT(output.get_face() == kOutputPort);
> ```

BTW consider ABORT_UNLESS; its really important, probably easy to screw up, and cheap to check.

---

*[drake/systems/framework/diagram_builder.h, line 93 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUKP_Zf06Mps_Sdw2N:-KPUKP_Zf06Mps_Sdw2O:b4ucick) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L93)):*
> ```objc
>   // produce a separate execution order for each output of the DiagramBuilder.
>   std::vector<const System<T>*> SortSystems() const {
>     std::vector<const System<T>*> output;
> ```

BTW it took me a moment to realize `output` was not about the Diagram's output, but rather just the `result` of this method.

---

*[drake/systems/framework/diagram_builder.h, line 109 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUKtCIhnsELOSGck8-:-KPUKtCIhnsELOSGck80:b-rx439r) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L109)):*
> ```objc
> 
>     // Find the systems that have no inputs within the DiagramBuilder.
>     std::set<const System<T>*> nodes_with_in_degree_zero;
> ```

BTW Using a set of pointers likely makes this method non-deterministic across runs.  It would be best to have the sequence of API calls to Connect and Export imply a consistent sort order.

---

*[drake/systems/framework/diagram_builder.h, line 159 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPULDnn8nCGuqCal-fj:-KPULDno7EvPYp3qkd70:b-k748j1) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L159)):*
> ```objc
> 
>   // The unsorted set of Systems in this DiagramBuilder.
>   std::set<const System<T>*> systems_;
> ```

BTW Using a set of pointers likely makes it very challenging to have this class's built results be deterministic across runs.  It would be best to have the sequence of API calls to Connect and Export imply a consistent sort order.

---

*[drake/systems/framework/test/CMakeLists.txt, line 67 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPU8sGhky3McndGJkPH:-KPU8sGiuOqOn2fZCJM6:bz6q6q1) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/test/CMakeLists.txt#L67)):*
> ```CMake
> add_test(NAME diagram_builder_test COMMAND diagram_builder_test)
> ```

Second blank line seems unnecessary?

---

*[drake/systems/framework/test/diagram_builder_test.cc, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPULwe9teuKOfgHrnc2:-KPULwe9teuKOfgHrnc3:b-ciom1o) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/test/diagram_builder_test.cc#L6)):*
> ```cpp
> #include "gtest/gtest.h"
> 
> #include "drake/systems/framework/basic_vector.h"
> ```

Unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[drake/systems/framework/diagram_builder.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUILJj_HOOYPZorsy4:-KPUEMtOZYOwR5mNGU1N:b-twd78u) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Sanity check that src and dest have the correct face?
> 
> For the check, consider ABORT_UNLESS; its really important, probably easy to screw up, and cheap to check.
</details>
These repeated "face" checks would not be necessary if there were InputPortDescriptor and OutputPortDescriptor classes. That is always known at compile time, would eliminate the possibility of mixing these up, and remove the need to check everywhere. I like keeping the class count down, but I think this is a place where two is better than one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/diagram_builder.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUILJj_HOOYPZorsy4:-KPUYvRsqnjKyfaip8sH:b-my11p1) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> These repeated "face" checks would not be necessary if there were InputPortDescriptor and OutputPortDescriptor classes. That is always known at compile time, would eliminate the possibility of mixing these up, and remove the need to check everywhere. I like keeping the class count down, but I think this is a place where two is better than one.
</details>
FTR, I am indifferent to that solution vs an assertion (I don't have enough of the design in my head).  Either one is good by me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188)*

**Comment by david-german-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 16 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 57 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUA7O4klN14AYeQ1yJ:-KPUOKYgKLt4bbEv_WWV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This is good, but I believe the input arguments still need some kind of explanation, if nothing else of the invariants 
</details>
Done.

---

*[drake/systems/framework/diagram.h, line 75 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUDsbs7hrv7zjMeMge:-KPUaBd6QzH4gkqhGUIK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> It seems to me like there are several invariants here that aren't being checked.  That sorted_systems had no duplicates; that the dependency_graph, input_port_ids_, and output_port_ids all refer to systems within the sorted_systems set; that the port indexes throughout are within range (currently only the exported ones are checked); and that the dependency_graph order is consistent with sorted_systems (should be very cheap to check here, versus computing it originally).
</details>
Done.

---

*[drake/systems/framework/diagram.h, line 77 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUEjnUnRsRypd1mBXo:-KPUOm_aaJRoHxHJbkUS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I think `override` not `virtual`?
</details>
Done.

---

*[drake/systems/framework/diagram.h, line 183 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUFeqvW2QQwdSFC3L_:-KPUP6AOM2x1XzvoHOG2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L183)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW consider `const System<T>* const sys` pervasively, if you like.
</details>
Done.

---

*[drake/systems/framework/diagram.h, line 247 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUDg6xe5BHJWSKLRcz:-KPUP9S2uj6GKCwYwT97:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L247)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> No more `Finalize`.
</details>
Done.

---

*[drake/systems/framework/diagram_builder.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUILJj_HOOYPZorsy4:-KPUPNk6ETFLqo54UAbe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Sanity check that src and dest have the correct face?
> 
> For the check, consider ABORT_UNLESS; its really important, probably easy to screw up, and cheap to check.
</details>
Done.

---

*[drake/systems/framework/diagram_builder.h, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJe4GFQbiXnxOT3h4:-KPUPRS2j1v1uwHS8mny:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider doing this first, before making any other state edits?
</details>
Done.

---

*[drake/systems/framework/diagram_builder.h, line 38 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJDSPsL3-ZYRAuFVw:-KPUPSJTlbGYxaKL7ssH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW consider ABORT_UNLESS; its really important, probably easy to screw up, and cheap to check.
</details>
Done.

---

*[drake/systems/framework/diagram_builder.h, line 41 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJhq0XuTkiJNsUXYk:-KPUPUou0VfNrXI8GD38:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider doing this first, before making any other state edits?
</details>
Done.

---

*[drake/systems/framework/diagram_builder.h, line 44 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJZc5p-z55bzulFsi:-KPUPXoLWf9ChFOrdbcg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This appears to duplicate the `Register` call above?
</details>
Done.

---

*[drake/systems/framework/diagram_builder.h, line 50 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUJE4n-AW1Ttz-SCiL:-KPUPYzyGsoSotlwKC6q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW consider ABORT_UNLESS; its really important, probably easy to screw up, and cheap to check.
</details>
Done.

---

*[drake/systems/framework/diagram_builder.h, line 93 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUKP_Zf06Mps_Sdw2N:-KPUPec7CDmqofRWzbqy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L93)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW it took me a moment to realize `output` was not about the Diagram's output, but rather just the `result` of this method.
</details>
Done.

---

*[drake/systems/framework/diagram_builder.h, line 109 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUKtCIhnsELOSGck8-:-KPUYHVxqe4BVtGFXHx1:b-hck6m5) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Using a set of pointers likely makes this method non-deterministic across runs.  It would be best to have the sequence of API calls to Connect and Export imply a consistent sort order.
</details>
Great point!  Done.

---

*[drake/systems/framework/diagram_builder.h, line 159 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPULDnn8nCGuqCal-fj:-KPUYJPqsXUphYW5za97:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L159)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Using a set of pointers likely makes it very challenging to have this class's built results be deterministic across runs.  It would be best to have the sequence of API calls to Connect and Export imply a consistent sort order.
</details>
Done.

---

*[drake/systems/framework/test/CMakeLists.txt, line 67 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPU8sGhky3McndGJkPH:-KPUPmToydCWsa-0tOxU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/test/CMakeLists.txt#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Second blank line seems unnecessary?
</details>
Done.

---

*[drake/systems/framework/test/diagram_builder_test.cc, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPULwe9teuKOfgHrnc2:-KPUPqB8RnObJsUOF068:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/test/diagram_builder_test.cc#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188)*

**Comment by david-german-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/framework/diagram_builder.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUILJj_HOOYPZorsy4:-KPUg3deBRWOeHi--loi:b99j0e6) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram_builder.h#L26)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Done.
</details>
Also, I agree with @sherm1, but it's out of scope for this PR.  Opened #3189.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 75 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUDsbs7hrv7zjMeMge:-KPUtRKJ13DsrhIN7RBg:bvnjb8t) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L75)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Done.
</details>
From what I perceive here, for both the keys and values of dependency_graph, the second item of each PortIdentifier (the port index) does not seem to be validated against the number of ports in that system.  That's fine if you'd prefer not to check that, but I wanted to ask to be sure.

---

*[drake/systems/framework/diagram.h, line 264 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUuQOBv1wCPyqSuWKq:-KPUuQOCTgKf3Iw9klPz:b-ciom1o) ([raw file](https://github.com/robotlocomotion/drake/blob/5f92bbf689ea646bd40dccfbd818f059b8398db7/drake/systems/framework/diagram.h#L264)):*
> ```objc
>   // sorted_systems_.
>   bool SortOrderIsCorrect() const {
>     std::map<const System<T>*, const System<T>*> prerequisites;
> ```

Unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188)*

**Comment by david-german-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 75 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUDsbs7hrv7zjMeMge:-KPYBNj-1wtlHf3SdWQu:b-7mzpcu) ([raw file](https://github.com/robotlocomotion/drake/blob/57ee773caa8a753a6356b4849716a8488f00f8f6/drake/systems/framework/diagram.h#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> From what I perceive here, for both the keys and values of dependency_graph, the second item of each PortIdentifier (the port index) does not seem to be validated against the number of ports in that system.  That's fine if you'd prefer not to check that, but I wanted to ask to be sure.
</details>
Done.  (Thanks for all of this, great catches.)

---

*[drake/systems/framework/diagram.h, line 264 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPUuQOBv1wCPyqSuWKq:-KPYBY4WostIQObuXA_m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f92bbf689ea646bd40dccfbd818f059b8398db7/drake/systems/framework/diagram.h#L264)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/framework/diagram.h, line 271 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPYEPHlaaQsuzfTS_bQ:-KPYEPHmkg7QF9W9iXnD:bghb932) ([raw file](https://github.com/robotlocomotion/drake/blob/75de855921daabe4aa3e7db92ac2339dec353200/drake/systems/framework/diagram.h#L271)):*
> ```objc
>         return false;
>       }
>       if (src.second < 0 || src.second >= src.first->get_num_input_ports()) {
> ```

ITYM number of output ports?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram.h, line 271 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-KPYEPHlaaQsuzfTS_bQ:-KPYFwCJY17nX4Bf25_L:b-n4jmtu) ([raw file](https://github.com/robotlocomotion/drake/blob/75de855921daabe4aa3e7db92ac2339dec353200/drake/systems/framework/diagram.h#L271)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> ITYM number of output ports?
</details>
Yikes!  Yes, done.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3188#-:-KPZF4C08wL5YuBx7vGK:bnfp4nl)*

**Pull request merged**
