### PR TITLE
 Move into tools/dynamic_analysis some build details

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7165)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-tsan-everything please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please

**Comment by jwnimmer-tri** [comment]
I think the CI failure is a timing flake.

+@sammy-tri for platform review per rotation, please.  Let me know if you advice a second reviewer or not.

**Comment by sammy-tri** [comment]
I think you're right about the timing fluke (asking the bot to try again anyway, because something something same thing and expecting a different result).

:lgtm: 

I don't think a second review is necessary.

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please

---

Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/dynamic_analysis/bazel.rc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7165#-KvYI9WVitUfc4kiuRsk:-KvYI9WWx6-p-XZkjakH:bktqw5k) ([raw file](https://github.com/robotlocomotion/drake/blob/1586915420267f3b608e7a65d38fce0f1bb2f4e4/tools/dynamic_analysis/bazel.rc#L1)):*
> ```
> # This is a portion of Drake's bazel.rc defaults.
> ```

BTW I'm assuming this content is verbatim from it's previous location in `tools/bazel.rc` (lines added/removed supports this theory)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7165#-:-KvYJA4uwQNyHEt-aCSI:b-vcyhef)*

**Comment by jwnimmer-tri** [comment]
*[tools/dynamic_analysis/bazel.rc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7165#-KvYI9WVitUfc4kiuRsk:-KvYM-XuJK4R4YeLAiq-:b-aw3byj) ([raw file](https://github.com/robotlocomotion/drake/blob/1586915420267f3b608e7a65d38fce0f1bb2f4e4/tools/dynamic_analysis/bazel.rc#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I'm assuming this content is verbatim from it's previous location in `tools/bazel.rc` (lines added/removed supports this theory)
</blockquote></details>

OK Yup, the new lines here (after these first two) were cut-n-paste from the `tools/bazel.rc` -- with the exception of the `run_under` paths changing.  For some reason gitk shows that to be correctly, but reviewable isn't.  Shrug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7165)*

**Comment by jwnimmer-tri** [comment]
The CI failure happened a second time, investigating ... I see the problem.  (Thanks for pushing on it, Sam.)

For the `...memcheck-asan-everything` configurations (both experimental, continuous, etc.), CI is using `--config=everything --config=asan` on the Bazel command line.  The correct spelling is `--config asan_everything`.  Because this PR changes the declaration order of `--config asan` and `--config everything`, it changes which of the `test_tags` settings from a config wins.  In this PR, we run 520 tests (including, e.g., gurobi & mosek based tests like rotation_contraint_test that is timing out).  On master (continuous), we only run 492 tests -- the asan-everything build is buliding with the commercial solvers enabled, but still excluding tests that depend on them.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please

**Comment by jwnimmer-tri** [comment]
For now, I've moved the rc import to the end of the file, so that this PR is a non-functional change, and filed #7176 to fix up the CI configs.

**Comment by jwnimmer-tri** [comment]
Hmm, its still failing.  I must have misunderstood exactly how the `test_tag_filter` ordering is happening.  I will work on iterating locally before pushing again.

**Comment by jwnimmer-tri** [comment]
Now waiting on #7204 and then RobotLocomotion/drake-ci#83.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please

**Comment by jwnimmer-tri** [comment]
The only CI failure here is already happening on master, and will be fixed by #7211.

**Pull request merged**
