### PR TITLE
Update latest Drake-compatible CLion and Bazel versions

### PR DESCRIPTION
**Pull request by sherm1**
Update the Drake website instructions for CLion.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16081)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@damrongguoy for feature review, please (as a fellow CLion user)
+@jwnimmer-tri for platform review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16081#-:-MoGHIz7D9gnvP0Iw7KR:b-gkfpiw)* status: LGTM missing from assignees DamrongGuoy,jwnimmer-tri(platform) (waiting on @DamrongGuoy and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

-(release notes: yes) +(release notes: none) for website-only change.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16081#-:-MoGPkMS5rjtfQC9jZj8:bwdmh98)* status: LGTM missing from assignee DamrongGuoy (waiting on @DamrongGuoy)

**Comment by sherm1** [comment]
(Oddly reviewable is not showing me your LGTM and comment above.)

The reason I put `release notes:yes` is that I think it will be worthwhile to mention that a newer version of CLion has been vetted against that release. Otherwise I don't think someone upgrading will think to go look at the CLion instructions on the web site. I'll put that back but LMK if you don't think that's useful.

**Comment by jwnimmer-tri** [comment]
(:lgtm: in case prior one got lost.)

I suppose that erring on the side of more information is fine, sure.

Perhaps the PR number in a bullet point in the middle of the document isn't what you want though?  If you just want an announcement in the release notes with a hyperlink to the https://drake.mit.edu/clion.html, you can push that yourself to the notes branch with the phrasing you want, or you could leave a review comment with your desired text.

**Review by DamrongGuoy — COMMENTED** [review]
I have upgraded to CLion 2021.2.3 successfully following the instruction.

:lgtm: with cosmetic requests.

By the way, if you'd like to test the doc locally, the instructions [here](https://drake.mit.edu/documentation_instructions.html) say you can:
```
$ sudo setup/ubuntu/install_prereqs.sh --with-doc-only
$ bazel run //doc:build -- --serve pages
```
I did that to see how it looked.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16081#-:-MoGuRIT3E7m3Y-2y1mZ:b-lmg5m)* status: 3 unresolved discussions (waiting on @jwnimmer-tri and @sherm1)

___
*[doc/_pages/clion.md, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16081#-MoGf_Wl9CauqBl3IXng:-MoGf_Wl9CauqBl3IXnh:bliyctp) ([raw file](https://github.com/robotlocomotion/drake/blob/8d4b39ad9b8cad54e2177706a4d03a7dee3ca70c/doc/_pages/clion.md#L53)):*
> ```Markdown
>    in your user directory, typically ``~/.local/share/applications``.
> 2. Uninstall the previous version of the Bazel plugin and update to the latest
>    version. See [Installing the Bazel Plugin](#installing-the-bazel-plugin).
> ```

Does `latest version` mean the latest one that Jetbrains or Google provide?  Perhaps we want to say "*the version specified above*" instead?

```
2. Uninstall the previous version of the Bazel plugin and update to the version specified above.
```
___
*[doc/_pages/clion.md, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16081#-MoGlVfw3H1VnPrmvCwA:-MoGlVfw3H1VnPrmvCwB:b-iwr67y) ([raw file](https://github.com/robotlocomotion/drake/blob/8d4b39ad9b8cad54e2177706a4d03a7dee3ca70c/doc/_pages/clion.md#L54)):*
> ```Markdown
> 2. Uninstall the previous version of the Bazel plugin and update to the latest
>    version. See [Installing the Bazel Plugin](#installing-the-bazel-plugin).
> 3. Run Bazel->Sync->Non-incrementally Sync Project with BUILD Files
> ```

At first, I thought it was talking about running bazel on the command line:
```
drake $ bazel sync ...
```
Now I understand it's the menu in CLion.  Please change to:

```
3. Run ``Bazel > Sync > Non-Incrementally Sync Project with BUILD Files`` in 
   CLion.
```

It will look like this:


___
*[doc/_pages/clion.md, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16081#-MoGizpF3feu8zAyPTew:-MoGizpF3feu8zAyPTex:buryotz) ([raw file](https://github.com/robotlocomotion/drake/blob/8d4b39ad9b8cad54e2177706a4d03a7dee3ca70c/doc/_pages/clion.md#L68)):*
> ```Markdown
> install the plugin, open ``Settings`` (either ``Welcome > Configure >
> Settings`` or ``File > Settings``), select ``Plugins``, and press the ``Browse
> repositories`` button.  Locate and install the ``Bazel`` plugin. You will be
> ```

I do not see `Browse repositories` anymore.  I think they changed it to `Marketplace` tab as shown in this picture. There are two tabs: `Marketplace` and `Installed`


Please change 
```
and press the ``Browse repositories`` button.
```
to
```
and choose the ``Marketplace`` tab.
```

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16081)* status: 3 unresolved discussions (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16081)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),DamrongGuoy (waiting on @DamrongGuoy and @jwnimmer-tri)

___
*[doc/_pages/clion.md, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16081#-MoGf_Wl9CauqBl3IXng:-MoZNA6EB4yg00eHk917:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d4b39ad9b8cad54e2177706a4d03a7dee3ca70c/doc/_pages/clion.md#L53)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Does `latest version` mean the latest one that Jetbrains or Google provide?  Perhaps we want to say "*the version specified above*" instead?

```
2. Uninstall the previous version of the Bazel plugin and update to the version specified above.
```
</blockquote></details>

Done.
___
*[doc/_pages/clion.md, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16081#-MoGlVfw3H1VnPrmvCwA:-MoZNBXj3dtOig223gP_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d4b39ad9b8cad54e2177706a4d03a7dee3ca70c/doc/_pages/clion.md#L54)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

At first, I thought it was talking about running bazel on the command line:
```
drake $ bazel sync ...
```
Now I understand it's the menu in CLion.  Please change to:

```
3. Run ``Bazel > Sync > Non-Incrementally Sync Project with BUILD Files`` in 
   CLion.
```

It will look like this:



</blockquote></details>

Done.
___
*[doc/_pages/clion.md, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16081#-MoGizpF3feu8zAyPTew:-MoZNrAN3FpQ-Bq071E_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d4b39ad9b8cad54e2177706a4d03a7dee3ca70c/doc/_pages/clion.md#L68)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I do not see `Browse repositories` anymore.  I think they changed it to `Marketplace` tab as shown in this picture. There are two tabs: `Marketplace` and `Installed`


Please change 
```
and press the ``Browse repositories`` button.
```
to
```
and choose the ``Marketplace`` tab.
```

</blockquote></details>

Done.

**Pull request merged**
