### PR TITLE
Adding Bug Report for a Suppression

### PR DESCRIPTION
**Pull request by m-chaturvedi**
re https://github.com/RobotLocomotion/drake/issues/6910

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7019)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7019#-:-Ku0W-2S1_JzVVcnQWOV:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@soonho-tri, platform review, please.

**Comment by soonho-tri** [comment]
:lgtm:

Good to know that the problem is fixed in the upstream.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7019#-:-Ku0WpXewHLetyXpafFz:blr7z2c)*

**Comment by m-chaturvedi** [comment]
BTW, the "fix" might have been inadvertent though.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7019#-:-Ku0XI2hsKuNhyUe-rN1:b-nerggk)*

**Pull request merged**
