### PR TITLE
Update Luenberger observe to use derived type of the observed system

### PR DESCRIPTION
**Pull request by RussTedrake**
... where possible.  Baby steps towards #6938.

Also needed to add the gunit hack to be able to debug the acrobot example in CLion.  Yuck.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6999)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@seancurtis-tri for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-:-KtiScngNAXKfyPzN0G4:b-t5m2ic)*

**Comment by sherm1** [comment]
> needed to add the gunit hack to be able to debug the acrobot example in CLion. Yuck.

PR #6990 merged to master on Friday with the gunit hack built in.

**Comment by RussTedrake** [comment]
Yes, I replicated the code from #6990 ... because #6990 doesn't solve the problem for me here since this example is a binary not a gtest.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-:-KtiaimBKjhwUyQR-09M:by35oj7)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with some cosmetic quibbling.

+@jwnimmer-tri for platform review.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtlXQKkbhRc0fqutHsy:-KtlW1DwcOVW39aqpC7o:bylr65s) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc#L47)):*
> ```cpp
> int do_main(int argc, char* argv[]) {
>   gflags::ParseCommandLineFlags(&argc, &argv, true);
>   unused(FLAGS_gunit_color);
> ```

FYI I'm surprised this is necessary. @jwnimmer-tri do you have particular insight on why flagging this as `unused` is necessary here but not `drake_cc_googletest_main.cc`?

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtlUNGJWy-blBOkxFBp:-KtlUNGJWy-blBOkxFBq:b-edkaik) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/systems/estimators/test/luenberger_observer_test.cc#L88)):*
BTW I'd like the comment extended slightly. The next test has nice parallel: "input of the plant" and `PendulumInput` pair. This has the pair "output" and `PendulumState`. As such, my recommended change:

> // The first input is the output of the plant (i.e., the plant state).

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtlU2G75ifoZZMXiX73:-KtlU2G75ifoZZMXiX74:b-li5t7g) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/systems/estimators/test/luenberger_observer_test.cc#L90)):*
> ```cpp
>   // The first input is the output of the plant.
>   auto input0 = observer->AllocateInputVector(observer->get_input_port(0));
>   EXPECT_TRUE(
> ```

BTW You should use `is_dynamic_castable` on this (and the next).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-:-KtlYvlZGrLsoI7hfdlz:b3g9s9h)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtlXQKkbhRc0fqutHsy:-Ktlb9vO6bNjd4NhDeg9:b6rp8a7) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc#L47)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I'm surprised this is necessary. @jwnimmer-tri do you have particular insight on why flagging this as `unused` is necessary here but not `drake_cc_googletest_main.cc`?
</blockquote></details>

OK Test code is exempted from unused-parameter per https://github.com/RobotLocomotion/drake/blob/9230f99f0da4e0723ab4535b826745c05df7cded/tools/drake.bzl#L34-L38, though I don't think `drake_cc_googletest_main.cc` is covered by that whitelist, so really I have no idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6999)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtlenUHE6UoHP8amBWV:-KtlenUHE6UoHP8amBWW:b-281811) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc#L39)):*
> ```cpp
> //    Bazel plugin: 2017.07.05.0.2
> // Related issue: https://github.com/bazelbuild/intellij/issues/131
> DEFINE_string(gunit_color, "", "");
> ```

FYI Strictly speaking, this is not platform-review defective because it is only the second instance of copied code, and the code is trivially short.  However, it is perhaps too encouraging for other Drake developers to copy this a third time, so in the sense of it setting others up for failure, perhaps its not the best choice to try to add this work-around in here.

It is probably past time to factor the main / do_main pattern into a reusable helper, which could then embed the work-around for 131.

Thus, I would encourage you to rip out the work-around here, but won't block the PR on it if you think this is better.

---

*[drake/systems/estimators/luenberger_observer.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtldXDXfqQE_-WVG3k4:-KtldXDYqV3qxbTufiwV:bpg770u) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/systems/estimators/luenberger_observer.cc#L37)):*
> ```cpp
>   // but the best we can do for now is to allocate a similarly-sized
>   // BasicVector (see #6998).
>   const auto& xc = observed_system_context_->get_continuous_state();
> ```

Using `const auto&` to denote a pointer is misleading.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-:-Ktlfl6SFvSw151Zzg7m:bcpz082)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtlenUHE6UoHP8amBWV:-KtlyHRfVlduaKjMsP_4:b9ehi6g) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Strictly speaking, this is not platform-review defective because it is only the second instance of copied code, and the code is trivially short.  However, it is perhaps too encouraging for other Drake developers to copy this a third time, so in the sense of it setting others up for failure, perhaps its not the best choice to try to add this work-around in here.

It is probably past time to factor the main / do_main pattern into a reusable helper, which could then embed the work-around for 131.

Thus, I would encourage you to rip out the work-around here, but won't block the PR on it if you think this is better.
</blockquote></details>

Done.  (i agree... i ended up adding it to a bunch more files while debugging this weekend.  it's important to know how, but not worth mucking with master).

---

*[drake/systems/estimators/luenberger_observer.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtldXDXfqQE_-WVG3k4:-KtlyaA36iD-2rykyjKm:blcm83t) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/systems/estimators/luenberger_observer.cc#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Using `const auto&` to denote a pointer is misleading.
</blockquote></details>

Done.  Good catch (it was originally doing an additional `get_vector`)

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtlUNGJWy-blBOkxFBp:-Ktlz1SgDfk2DJ-1jYGQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/systems/estimators/test/luenberger_observer_test.cc#L88)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'd like the comment extended slightly. The next test has nice parallel: "input of the plant" and `PendulumInput` pair. This has the pair "output" and `PendulumState`. As such, my recommended change:

> // The first input is the output of the plant (i.e., the plant state).
</blockquote></details>

Done.

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtlU2G75ifoZZMXiX73:-Ktlzo2Br97-40vhRzNq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/584f53d349fe08bfa6968d673e89a88ef0ff951c/drake/systems/estimators/test/luenberger_observer_test.cc#L90)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW You should use `is_dynamic_castable` on this (and the next).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6999)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6999)*

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this, please

**Comment by jwnimmer-tri** [comment]
*[drake/systems/estimators/test/luenberger_observer_test.cc, line 91 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6999#-KtpwXNYqn9BicdaturV:-KtpwXNZIrARW8E5lc4B:bypio7k) ([raw file](https://github.com/robotlocomotion/drake/blob/6a2d4b3e2fddf06e79605733627ff75a7728dc72/drake/systems/estimators/test/luenberger_observer_test.cc#L91)):*
> ```cpp
>   // The first input is the output of the plant (here the pendulum state).
>   auto input0 = observer->AllocateInputVector(observer->get_input_port(0));
>   EXPECT_TRUE(is_dynamic_castable<examples::pendulum::PendulumState<double>*>(
> ```

FYI CI is complaining because you don't need the `*` here, and below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6999)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6999)*

**Pull request merged**
