### PR TITLE
Fix Wunused-parameter in QPInverseDynamicsForHumanoids

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6030)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.  This repairs unused parameters using the guidelines in [drake::unused's documentation](http://drake.mit.edu/doxygen_cxx/namespacedrake.html#ade20b7bf635eecb13adbaac4df980af0).

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6030#-KjLeriTyT1jUeQSchle:-KjLeriTyT1jUeQSchlf:bi96221) ([raw file](https://github.com/robotlocomotion/drake/blob/35b823a2273af6f0f430fd8aea094f72f862b537/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L17)):*
> ```cpp
>     const HumanoidStatus& robot_status, const param_parsers::ParamSet& paramset,
>     const param_parsers::RigidBodyTreeAliasGroups<T>& alias_groups) {
>   unused(paramset);  // TODO(jwnimmer-tri) This seems bad.
> ```

BTW. if it's not used yet, but could be in the future. what do i do? get rid of the param? or mark it unused? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6030#-:-KjLfierzT42Ltvvk2Zz:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6030#-KjLeriTyT1jUeQSchle:-KjNKRGlp-jijetRouo8:b-cib9hd) ([raw file](https://github.com/robotlocomotion/drake/blob/35b823a2273af6f0f430fd8aea094f72f862b537/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L17)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW. if it's not used yet, but could be in the future. what do i do? get rid of the param? or mark it unused? 
</blockquote></details>

The guidelines in drake::unused's documentation are intended to handle that.

We can't do (1) because this is a virtual API used in several places, some of which do use the paramset, right?  So the default here would be to change the signature about in the cc file here to be (`... robot_status, const param_parsers::ParamSet&, const ...`) i.e. remove the `paramset` name.

I didn't do that here because I wasn't sure if ignoring parameters was intentional, so I wanted to place a TODO about it, thus the new line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6030)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6030#-KjLeriTyT1jUeQSchle:-KjNfgXhCoE8j6ZZzUgP:bhavnfc) ([raw file](https://github.com/robotlocomotion/drake/blob/35b823a2273af6f0f430fd8aea094f72f862b537/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The guidelines in drake::unused's documentation are intended to handle that.

We can't do (1) because this is a virtual API used in several places, some of which do use the paramset, right?  So the default here would be to change the signature about in the cc file here to be (`... robot_status, const param_parsers::ParamSet&, const ...`) i.e. remove the `paramset` name.

I didn't do that here because I wasn't sure if ignoring parameters was intentional, so I wanted to place a TODO about it, thus the new line.
</blockquote></details>

oh, by getting rid of it, i mean ```const param_parsers::ParamSet&``` here. the same params are parsed in the base class. this is good. thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6030)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Comment by sherm1** [comment]
Drop parameter names rather than use unused() here? PTAL

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6030#-KjLeriTyT1jUeQSchle:-KjOoKqcGq2xATCcGj77:b-4sd9if) ([raw file](https://github.com/robotlocomotion/drake/blob/35b823a2273af6f0f430fd8aea094f72f862b537/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L17)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

oh, by getting rid of it, i mean ```const param_parsers::ParamSet&``` here. the same params are parsed in the base class. this is good. thanks!
</blockquote></details>

BTW I'm unclear on the resolution here. Sounds like @siyuanfeng-tri wanted to drop the parameter name to show it is intentionally unused. But the code still has the parameter name + unused(). Why not just remove the name here? (and below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6030#-:-KjOoaRlFdDjKiPSuiqT:b-pvu1lm)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6030#-KjLeriTyT1jUeQSchle:-KjOpIwtMG0R1yckYxjp:bpzr6ld) ([raw file](https://github.com/robotlocomotion/drake/blob/35b823a2273af6f0f430fd8aea094f72f862b537/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L17)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm unclear on the resolution here. Sounds like @siyuanfeng-tri wanted to drop the parameter name to show it is intentionally unused. But the code still has the parameter name + unused(). Why not just remove the name here? (and below)
</blockquote></details>

My belief is that the code is buggy (or at least confusing), such that we need a TODO to fix it.  It seemed more specific to me to put the TODO on an `unused` declaration, than just a comment alone on its own line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6030)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6030#-KjLeriTyT1jUeQSchle:-KjOuhNx8D10fayy85yc:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/35b823a2273af6f0f430fd8aea094f72f862b537/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My belief is that the code is buggy (or at least confusing), such that we need a TODO to fix it.  It seemed more specific to me to put the TODO on an `unused` declaration, than just a comment alone on its own line.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6030#-:-KjOujz1P9ud55oTCbuy:bnfp4nl)*

**Pull request merged**
