### PR TITLE
Adds FrameVelocity output to MaliputRailcar.

### PR DESCRIPTION
**Pull request by liangfok**
This is an incremental step towards supporting an IDM-controlled `MaliputRailcar`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5755)

### CODE REVIEW

**Comment by liangfok** [comment]
+@maddog-tri for feature review please.
+@david-german-tri for platform review please.

Thanks!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-:-Kh3hBv6bRECnmms2aPh:b-j8upp9)*

**Comment by david-german-tri** [comment]
Please ping me once feature review is complete.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-:-Kh8iDNF_4kiuU1EYoZH:b8z9cix)*

**Comment by maddog-tri** [comment]
Feature pass done; two (small) comments...

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 217 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhLk7zMFe5C9rPDUibV:-KhLk7zN9uecdN4mvR26:b-po4wxl) ([raw file](https://github.com/robotlocomotion/drake/blob/d802e99be3c9a5ca39f97c77ec592b52a90eb1fe/drake/automotive/maliput_railcar.cc#L217)):*
> ```cpp
>   // TODO(liang.fok) Add support for non-zero rotational velocity. See #5751.
>   const Vector3<T> w(T(0), T(0), T(0));
>   const Vector3<T> v(Vt_W(0), Vt_W(1), Vt_W(2));
> ```

Why create a `v` (a copy of `Vt_W`) instead of simply using `Vt_W` itself?

---

*[drake/automotive/maliput_railcar.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhLiK-240x5fRhLQ2N5:-KhLiK-3-wLy-UPQLuyc:baivoj7) ([raw file](https://github.com/robotlocomotion/drake/blob/d802e99be3c9a5ca39f97c77ec592b52a90eb1fe/drake/automotive/maliput_railcar.h#L48)):*
> ```objc
> ///     and `W` is the world frame.
> ///
> ///   - velocity_output(): Contains FrameVelocity `V_WC_W`, where `C` is the car
> ```

Can someone translate `V_WC_W` for me?  I'm not familiar with the nomenclature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-:-KhLnFeiEeWdnGsTgX2W:byf0cp)*

**Comment by liangfok** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 217 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhLk7zMFe5C9rPDUibV:-KhMXHXDV1g0jEmfLUQL:bwpbkyj) ([raw file](https://github.com/robotlocomotion/drake/blob/d802e99be3c9a5ca39f97c77ec592b52a90eb1fe/drake/automotive/maliput_railcar.cc#L217)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Why create a `v` (a copy of `Vt_W`) instead of simply using `Vt_W` itself?
</blockquote></details>

Oops! Good catch. Done.

---

*[drake/automotive/maliput_railcar.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhLiK-240x5fRhLQ2N5:-KhMVYbRKxZLw-FcBjKS:b-7vendf) ([raw file](https://github.com/robotlocomotion/drake/blob/d802e99be3c9a5ca39f97c77ec592b52a90eb1fe/drake/automotive/maliput_railcar.h#L48)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Can someone translate `V_WC_W` for me?  I'm not familiar with the nomenclature.
</blockquote></details>

`V_WC_W` stands for "the car frame's spatial velocity with respect to the world frame expressed in the world frame." For a detailed explanation of this notation, see: http://drake.mit.edu/doxygen_cxx/group__multibody__spatial__vectors.html.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755)*

**Comment by liangfok** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 217 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhLk7zMFe5C9rPDUibV:-KhM_M22BccqeRGUf3ic:btm4fym) ([raw file](https://github.com/robotlocomotion/drake/blob/d802e99be3c9a5ca39f97c77ec592b52a90eb1fe/drake/automotive/maliput_railcar.cc#L217)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Oops! Good catch. Done.
</blockquote></details>

I updated the variable name to use the standard "monogram" notation to match the class description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755)*

**Comment by maddog-tri** [comment]
:lgtm:  --- logic is fine; I'm still a bit puzzled by variable names (see BTW below).  But, no point in holding up platform-review for that.  Pinging @david-german-tri.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/automotive/maliput_railcar.cc, line 206 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhOcw_1Wm6j0t88VHRa:-KhOcw_2KT5wu-RGwOCU:b-di0k6k) ([raw file](https://github.com/robotlocomotion/drake/blob/253be3b99fb12928acceccf8399e364c9df1ad74/drake/automotive/maliput_railcar.cc#L206)):*
> ```cpp
>   //  - R is a rotation matrix.
> 
>   const Vector3<T> v_WC_L(lane_direction.with_s ? state.speed() :
> ```

BTW: Why isn't this called `v_LC_L`, i.e. "velocity of car-origin with respect to lane origin, expressed in lane basis" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-:-KhOejHX5IYMIgPU8x1E:b-mfmxc1)*

**Comment by liangfok** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 206 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhOcw_1Wm6j0t88VHRa:-KhOiWg8B0mBh6sfUL-4:b-d5q2ho) ([raw file](https://github.com/robotlocomotion/drake/blob/253be3b99fb12928acceccf8399e364c9df1ad74/drake/automotive/maliput_railcar.cc#L206)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

BTW: Why isn't this called `v_LC_L`, i.e. "velocity of car-origin with respect to lane origin, expressed in lane basis" ?
</blockquote></details>

Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755)*

**Comment by maddog-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/test/maliput_railcar_test.cc, line 454 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhTEN71qZ_TQdswE62x:-KhTEN71qZ_TQdswE62y:b-mtjnzf) ([raw file](https://github.com/robotlocomotion/drake/blob/9a302d21d37324a56d61fde6f652c0543c7f1095/drake/automotive/test/maliput_railcar_test.cc#L454)):*
> ```cpp
> 
>   auto velocity = velocity_output();
>   const Vector6<double> expected_velocity =
> ```

BTW, would it be worth testing a point where the velocity isn't axis-aligned?

---

*[drake/automotive/test/maliput_railcar_test.cc, line 739 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhTEhq-m-QRZMxP_EKK:-KhTEhq0igTmbzPyr7Jt:bcluxjz) ([raw file](https://github.com/robotlocomotion/drake/blob/9a302d21d37324a56d61fde6f652c0543c7f1095/drake/automotive/test/maliput_railcar_test.cc#L739)):*
> ```cpp
>   // each other.
>   EXPECT_TRUE(CompareMatrices(against_s_spatial_velocity.translational() +
>                                   with_s_spatial_velocity.translational(),
> ```

BTW weird indent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-:-KhTEjnt5ealBqyguuoX:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/test/maliput_railcar_test.cc, line 454 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhTEN71qZ_TQdswE62x:-KhTRn4i-MvRTrnnTq98:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a302d21d37324a56d61fde6f652c0543c7f1095/drake/automotive/test/maliput_railcar_test.cc#L454)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, would it be worth testing a point where the velocity isn't axis-aligned?
</blockquote></details>

Done.

---

*[drake/automotive/test/maliput_railcar_test.cc, line 739 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5755#-KhTEhq-m-QRZMxP_EKK:-KhTHfWwsfJHQNX-drTn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a302d21d37324a56d61fde6f652c0543c7f1095/drake/automotive/test/maliput_railcar_test.cc#L739)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW weird indent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755)*

**Comment by maddog-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5755)*

**Pull request merged**
