### PR TITLE
mbp, sdformat: Remember link initial poses

### LINKED ISSUE #10713: MultibodyPlant doesn't have a way to set the default pose for free bodies
While some joints provide a way to set the default position for newly created contexts (`RevoluteJoint::set_default_angle`, `PrismaticJoint:: set_default_translation`) there is no equivalent facility for setting the default pose for a free body (as `SetFreeBodyPose` only works after the context has been created).

This facility does exist for setting distributions for use in `SetRandomState`, but as pointed out in #10693 we should be able to set defaults too.

### LINKED ISSUE #12227: mbp parsing: //model/static is not properly supported, workflows are now confusing
At present, we do not support `//model/static` in MBP. It's relatively easy to tell the MBP SDFormat parsing to check this flag, and then just weld those links together at a fixed pose.

However, things really break when *posturing* the object. In MBP parsing API, there is no provision to posture the model; instead, the MBP workflows tend to add weld frames to  "snap" an object to a pose.

For now, I may just get rid of usages `//model/static` when reposturing a model is necessary.

I don't particularly care about this tag, but it's getting in my way for what I do care about, which is pose frame semantics + SDFormat-based model composition (#4641).

\cc @amcastro-tri @sherm1

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #4641, taken from #12061

Resolves #10713
Resolves #12227 (but with limited usage)

~Also disables usage of `//model/static`. Currently, we just ignore the tag and don't error out. This just errors out, pending a real fix (which should happen after this PR).~

\cc @hidmic

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12226)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 277 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12226#-Lrt5cQr0z1UgwsaGNum:-LryMLLp1mKDH3NsYPsf:bms0vrw) ([raw file](https://github.com/robotlocomotion/drake/blob/a286f22827dcaf18e502b0637990dabcb5985730/multibody/parsing/test/detail_sdf_parser_test.cc#L277)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

so this call is not testing anything now? I mean, there are no EXPECT_ANYTHING inside that method and we do nothing with the return.
</blockquote></details>

Correct.

I've found that I hate `EXPECT_NO_THROW`, as it's crappy for debugging as I don't get any info about the exception, whereas I do get information if I just let it throw.
For example, this code:
```
auto stuff = []() { throw std::runtime_error("Blarghhh"); };
EXPECT_NO_THROW(stuff());
```
Produces this wonderfully opaque error message:
```
multibody/parsing/test/detail_sdf_parser_test.cc:283: Failure
Expected: stuff() doesn't throw an exception.
  Actual: it throws.
```
Nothing about the type of exception, or the message itself.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI This appears to substantial change Drake's loading and interpretation of `*.sdf` input files.  Please provide (either below, or re-edit of top post) the release notes details that should appear alongside this change.

**Comment by EricCousineau-TRI** [comment]
Done. Thanks for the reminder!

**Pull request merged**
