### PR TITLE
Changeable dev/rgbd_camera extrinsics

### PR DESCRIPTION
**Pull request by gizatt**
@kunimatsu-tri Would you mind taking a look? I've been using this in Spartan to make our sim cameras match reality.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10491)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
___
*[systems/sensors/dev/rgbd_camera.h, line 146 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10491#-LX0nUesCoZ5DYvHeoOX:-LX0oqTQDbvHA0ILVEh3:b-hcydon) ([raw file](https://github.com/robotlocomotion/drake/blob/a751d7df2410f4edd463caa424bb9d3523725f87/systems/sensors/dev/rgbd_camera.h#L146)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

IIRC, in drake system land, all the mutable values have to come from either system input or state.
In that sense, this is violating the principle.

@jeremmy.nimmer Please you correct if I'm wrong because it's been a long time since I've done something with Drake system last time.

If my statement would be correct, I suggest setting these values via the constructor instead.
</blockquote></details>

Oops. @jwnimmer-tri

**Comment by kunimatsu-tri** [comment]
___
*[systems/sensors/dev/rgbd_camera.h, line 146 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10491#-LX0nUesCoZ5DYvHeoOX:-LX0qZXRDoTK1ny91tpo:b3mconi) ([raw file](https://github.com/robotlocomotion/drake/blob/a751d7df2410f4edd463caa424bb9d3523725f87/systems/sensors/dev/rgbd_camera.h#L146)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This is reasonable -- it is a "parameter" of the system. And setting that parameter after construction is not unreasonable. We certainly have systems that require configuration *after* construction (in which ports are added, for example). In that vein, these could be made `Parameter`s, proper if we wanted to be able to really experiment with the effect of the sensor locations. But for this, it seems harmless. These are certainly "immutable" in the sense that nothing in the analytical process will change them -- it would require an agency outside of the framework to actively choose to change them.
</blockquote></details>

Thanks, Sean. 

I have a concern with this way because people can now write their own diagram that has RgbdCamera system in it and actively changes these parameters while running simulation.

**Comment by EricCousineau-TRI** [comment]
___
*[systems/sensors/dev/rgbd_camera.h, line 146 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10491#-LX0nUesCoZ5DYvHeoOX:-LX0u-pP4Nvc5bsllAD3:b5506sx) ([raw file](https://github.com/robotlocomotion/drake/blob/a751d7df2410f4edd463caa424bb9d3523725f87/systems/sensors/dev/rgbd_camera.h#L146)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

But that would require them to interrupt the simulation to change it. I.e., 

```c++
simulator.StepTo(10);
camera->set_XBC(new_pose);
simulator.StepTo(20);
```

That's pretty overt. They couldn't do it by accident and would have to be aware that they are doing it. Protecting users from this happening due to code that *isn't* theirs would be my primary concern.

That said, moving it to the constructor is *perfectly* reasonable and precludes that use case.
</blockquote></details>

Per f2f with Kuni, I personally would also prefer it be passed in via the constructor, via an argument struct (not as individual arguments).

However, primarily since this is `dev/` code, I'd be fine with it living as setters.
Also, I agree with Sean in that these are more-or-less parameters, so it's kind-of OK there too (e.g. we have `set_publish_period` on other systems).

To counter Sean's example, though, nothing prevents the user from doing stupid things in a system during simulation. Looking at the code in `system.h` and `system_base.h`, if I were to do `DeclareOutputPort` with a functor that has mutable access to the class, I could easily change this parameter, or do something even more dumb like declare a new input port in the middle of a simulation (which I guess would fail somewhere else in the chain, not at that call site).

**Comment by kunimatsu-tri** [comment]
___
*[systems/sensors/dev/rgbd_camera.h, line 146 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10491#-LX0nUesCoZ5DYvHeoOX:-LX1IXck5xhOpmDy3PTV:b50aedi) ([raw file](https://github.com/robotlocomotion/drake/blob/a751d7df2410f4edd463caa424bb9d3523725f87/systems/sensors/dev/rgbd_camera.h#L146)):*
<details><summary><i>Previously, gizatt (Greg Izatt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I’m ok with leaving TODO here considering the fact that this is a dev code as Eric pointed out.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
