### PR TITLE
Add shoe to gallery

### PR DESCRIPTION
**Pull request by mntan3**
https://mntan3.github.io/
https://github.com/RobotLocomotion/gym/tree/master/gym/envs/robot_locomotion_group/drake/shoe

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) +@seancurtis-tri for both reviews.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044#-:-M_uxDBaCAa5hFg9eLyA:b-5i8dhh)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @mntan3)

___
*[doc/_pages/gallery.md, line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15044#-M_uwf8X9VPodJlqYk8p:-M_uwf8X9VPodJlqYk8q:b-rbwq5h) ([raw file](https://github.com/robotlocomotion/drake/blob/f9c40a7e006adf2497c0e9c992ca61b7d6a7a954/doc/_pages/gallery.md#L128)):*
> ```Markdown
> 
> 
> ## Shoe simulation
> ```

As the name gallery implies, you probably want some picture. A screen grab from your meshcat session would be enough.
___
*[doc/_pages/gallery.md, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15044#-M_uwRjQAU-FHFgdE6wK:-M_uwRjQAU-FHFgdE6wL:b-u9fg5t) ([raw file](https://github.com/robotlocomotion/drake/blob/f9c40a7e006adf2497c0e9c992ca61b7d6a7a954/doc/_pages/gallery.md#L129)):*
> ```Markdown
> 
> ## Shoe simulation
> *Meshcat animation:* [https://mntan3.github.io/](https://mntan3.github.io/)
> ```

BTW: `Meshcat` will mean a lot to pydrake users, but won't mean much to someone who happens across this page. Calling it "Interactive visualization" or "3D visualization" or some such thing might accessible to more readers.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @mntan3)

___
*[doc/_pages/gallery.md, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15044#-M_wMjXyEazJ_7Etl7kf:-M_wMjXyEazJ_7Etl7kg:b-1g2dh4) ([raw file](https://github.com/robotlocomotion/drake/blob/f9c40a7e006adf2497c0e9c992ca61b7d6a7a954/doc/_pages/gallery.md#L129)):*
> ```Markdown
> 
> ## Shoe simulation
> *Meshcat animation:* [https://mntan3.github.io/](https://mntan3.github.io/)
> ```

Another thought -- I'm not sure what the inner workings are that keeps the meshcat session running, but capturing a video of it, putting that video on youtube, and linking to it here might give a more accessible, long-lasting medium for end users to consume (e.g., on phones, tablets, etc.)

**Review by mntan3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[doc/_pages/gallery.md, line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15044#-M_uwf8X9VPodJlqYk8p:-M_wVtHg2EeqEFc52Df0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f9c40a7e006adf2497c0e9c992ca61b7d6a7a954/doc/_pages/gallery.md#L128)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

As the name gallery implies, you probably want some picture. A screen grab from your meshcat session would be enough.
</blockquote></details>

Done.
___
*[doc/_pages/gallery.md, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15044#-M_wMjXyEazJ_7Etl7kf:-M_wVu_uDD37zi7HiRzK:byb4n2o) ([raw file](https://github.com/robotlocomotion/drake/blob/f9c40a7e006adf2497c0e9c992ca61b7d6a7a954/doc/_pages/gallery.md#L129)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Another thought -- I'm not sure what the inner workings are that keeps the meshcat session running, but capturing a video of it, putting that video on youtube, and linking to it here might give a more accessible, long-lasting medium for end users to consume (e.g., on phones, tablets, etc.)
</blockquote></details>

Done. Thanks for the tip! Didn't think about the phone thing.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Video looks great. One last thing.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044#-:-Ma-8VbG05KPRC1PFqxh:b-4ofnvd)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @mntan3)

___
*[doc/_pages/gallery.md, line 128 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15044#-Ma-8ETvE37scr5GXnJP:-Ma-8ETwBfeVap34qLg3:b-yi5efb) ([raw file](https://github.com/robotlocomotion/drake/blob/ad9dac7f239a352b617f2bd43984b4acc534992c/doc/_pages/gallery.md#L128)):*
> ```Markdown
> 
> 
> ## Shoe simulation
> ```

After building the page, I realize the one thing you're missing is a blurb describing it -- all other gallery entries have a brief introduction. I'd say cover the following things:

1. Credit for who created the work.
2. The *point* of the example -- what makes it unique/interesting.
3. Indicate whether it is done in python or C++.

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI perhaps you could try pushing a few improvements here, to get it over the finish line?  It's a great gallery entry, so I've love to see this land.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'll push it through.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044#-:-Me67YQPBI_UxyD1Ewj6:b-2785nv)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @mntan3)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@mntan3 I've added a blurb. See my comment below about attribution. If you don't weigh in by Monday, I'll merge it without credit.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044#-:-MeAqGSAEiMXvGnh38D2:b-4lpc90)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mntan3 and @SeanCurtis-TRI)

___
*[doc/_pages/gallery.md, line 128 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15044#-Ma-8ETvE37scr5GXnJP:-MeApu1D9Ya1hbFIs_NA:b-kvrp83) ([raw file](https://github.com/robotlocomotion/drake/blob/ad9dac7f239a352b617f2bd43984b4acc534992c/doc/_pages/gallery.md#L128)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

After building the page, I realize the one thing you're missing is a blurb describing it -- all other gallery entries have a brief introduction. I'd say cover the following things:

1. Credit for who created the work.
2. The *point* of the example -- what makes it unique/interesting.
3. Indicate whether it is done in python or C++.
</blockquote></details>

I've made an attempt to address those comments. The one thing I'm unsure of is the attribution. My instinct would be to attribute it to @mntan3, but the link to the source code doesn't include her. So, if you have a minute and can weigh in, I'd appreciate it.

**Review by mntan3 — COMMENTED** [review]
Hi, sorry I graduated and forgot about this PR. Yeah, I was the main author, but I got lots of help from Mark, Terry, Russ, and people at TRI. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044#-:-MeDGB0Y7AxXRxbRYKqS:b-ckrwhi)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mntan3 and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@mntan3 Sooooo close. If you'd written that with full names, I could've simply added it to the PR.  :)

I don't suppose you could quickly just type some attribution text into a comment, and I'll add it to the PR?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044#-:-MePlQ8b-LLA99Sh3Tpq:b-6nkvvy)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mntan3 and @SeanCurtis-TRI)

**Review by mntan3 — COMMENTED** [review]
Authored by Michelle Tan, with help from Terry Suh, Mark Peterson, Russ Tedrake, and the team at TRI

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044#-:-MeT1FTtCs3YjDvPY7KP:b1vq12a)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mntan3 and @SeanCurtis-TRI)

**Review by mntan3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[doc/_pages/gallery.md, line 128 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15044#-Ma-8ETvE37scr5GXnJP:-MeT1Sg8BfC7LbU92Ye_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad9dac7f239a352b617f2bd43984b4acc534992c/doc/_pages/gallery.md#L128)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I've made an attempt to address those comments. The one thing I'm unsure of is the attribution. My instinct would be to attribute it to @mntan3, but the link to the source code doesn't include her. So, if you have a minute and can weigh in, I'd appreciate it.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Authored by Michelle Tan, with help from Terry Suh, Mark Peterson, Russ Tedrake, and the team at TRI
Great. Thanks.

Self stamping this. :LGTM:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15044#-:-MeV3zt6A0arN5jFJyB4:b8xfij3)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mntan3)

**Pull request merged**
