### PR TITLE
Implements a low pass first order filter system

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implements a very simple low pass filter into `drake/systems/primitives`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5502)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@siyuanfeng-tri for feature review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-:-KfHky7GLhd9XpC3N1VN:bakb6i6)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: minor comments. 

---

Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/first_order_low_pass_filter.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHtD8Jr4jjudX4kL2A:-KfHtD8Jr4jjudX4kL2B:b-1rynyd) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.cc#L22)):*
> ```cpp
>     : SisoVectorSystem<T>(time_constants.size(), time_constants.size()),
>       time_constants_(time_constants) {
>   DRAKE_ASSERT(time_constants.size() > 0);
> ```

BTW add a check for time_constants are valid? 

---

*[drake/systems/primitives/first_order_low_pass_filter.cc, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHt4aQbcFczn3z8w2I:-KfHt4aQbcFczn3z8w2J:bmxbsw6) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.cc#L59)):*
> ```cpp
>     const Eigen::VectorBlock<const VectorX<T>>& state,
>     Eigen::VectorBlock<VectorX<T>>* derivatives) const {
>   derivatives->array() = (input -state).array() / time_constants_.array();
> ```

BTW space

---

*[drake/systems/primitives/first_order_low_pass_filter.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHtykyWuz2zin-wiXw:-KfHtykzCWJRpj0W5hCC:b-74k4s1) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.h#L12)):*
> ```objc
> 
> /// An element-wise first order low pass filter system that filters the i-th
> /// input uᵢ into the i-th output zᵢ. This system has one continuous state per
> ```

BTW _i? why 1? 

---

*[drake/systems/primitives/first_order_low_pass_filter.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHrNoQPWAjSRu3rNG4:-KfHrNoQPWAjSRu3rNG5:b-m3gbge) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.h#L91)):*
> ```objc
> 
>   // System<T> override. Returns a FirstOrderLowPassFilter<symbolic::Expression>
>   // with the same time constants and dimensions as this Integrator.
> ```

Filter?

---

*[drake/systems/primitives/test/first_order_low_pass_filter_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHrHlUyygd2oc-HZhV:-KfHrHlUyygd2oc-HZhW:b-6fapwp) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/test/first_order_low_pass_filter_test.cc#L26)):*
> ```cpp
>     output_ = filter_->AllocateOutput(*context_);
> 
>     // Set the state to zero initially.
> ```

BTW, sets. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-:-KfHyE_lp8NUsOMCyveU:bv8upnk)*

**Comment by amcastro-tri** [comment]
I addressed the reviews @siyuanfeng-tri. PTAL.

---

Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/first_order_low_pass_filter.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHtD8Jr4jjudX4kL2A:-KfI0WRfwZFNoSpKnyRf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.cc#L22)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW add a check for time_constants are valid? 
</blockquote></details>

Done.

---

*[drake/systems/primitives/first_order_low_pass_filter.cc, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHt4aQbcFczn3z8w2I:-KfI0bNXVOeP1QLGhHrB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.cc#L59)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW space
</blockquote></details>

Done.

---

*[drake/systems/primitives/first_order_low_pass_filter.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHtykyWuz2zin-wiXw:-KfI-TWxpkaWMjxRJmBl:b6dt1yq) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.h#L12)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW _i? why 1? 
</blockquote></details>

BTW, it actually is `i`, just a very small one. Increase the font size and you'll see. I guess this is the best we can do with Unicode?

---

*[drake/systems/primitives/first_order_low_pass_filter.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHrNoQPWAjSRu3rNG4:-KfI-gLhyasHqGYXGjef:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.h#L91)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Filter?
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/first_order_low_pass_filter_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHrHlUyygd2oc-HZhV:-KfI-ne-jPQbIItRxzHB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/test/first_order_low_pass_filter_test.cc#L26)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, sets. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-:-KfIBgq2sneO2fDmkbzg:bolimph)*

**Comment by amcastro-tri** [comment]
+@sammy-tri for platform review please.

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-:-KfIBsX7VMSWbW5Zj1Ur:b-1zm1j3)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/first_order_low_pass_filter.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHtykyWuz2zin-wiXw:-KfIBvXppPMA4Hs7hXqa:bh3k6u8) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.h#L12)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, it actually is `i`, just a very small one. Increase the font size and you'll see. I guess this is the best we can do with Unicode?
</blockquote></details>

sigh.. i would just get rid of the subscript in this case then. this is simple enough, and it only adds confusion. no bodies is going to increase test font to read a header file. 

---

*[drake/systems/primitives/test/first_order_low_pass_filter_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHrHlUyygd2oc-HZhV:-KfIBo6CjX2YHOLAsqXT:bs8hkh3) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/test/first_order_low_pass_filter_test.cc#L26)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW there are other sets further down... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502)*

**Comment by amcastro-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/first_order_low_pass_filter.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHtykyWuz2zin-wiXw:-KfICfZQ6yhdGXe7Oqok:b8zj0fp) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.h#L12)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

sigh.. i would just get rid of the subscript in this case then. this is simple enough, and it only adds confusion. no bodies is going to increase test font to read a header file. 
</blockquote></details>

So how would you write the doc below? like:  ż_i = -1/τ_i (z_i - u_i)
@edrumwri, maybe you have a better suggestion on how to write these indexes? in this case the unicode caused more confusion instead of being useful. 
It does look a bit better in the Doxygen but I do agree it still is too small. 

---

*[drake/systems/primitives/test/first_order_low_pass_filter_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHrHlUyygd2oc-HZhV:-KfIDm-510NQHN_WudwI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/test/first_order_low_pass_filter_test.cc#L26)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW there are other sets further down... 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502)*

**Comment by sherm1** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/first_order_low_pass_filter.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfHtykyWuz2zin-wiXw:-KfIKGscPgS4KilWa426:ba19ksc) ([raw file](https://github.com/robotlocomotion/drake/blob/cfebbc1c6963b15481b7006bcae35932b06c3117/drake/systems/primitives/first_order_low_pass_filter.h#L12)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

So how would you write the doc below? like:  ż_i = -1/τ_i (z_i - u_i)
@edrumwri, maybe you have a better suggestion on how to write these indexes? in this case the unicode caused more confusion instead of being useful. 
It does look a bit better in the Doxygen but I do agree it still is too small. 

</blockquote></details>

BTW, the subscript `i` in `zᵢ` looked fine to me in Reviewable, not at all like a 1. Maybe I use a larger font?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 1 of 2 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/primitives/first_order_low_pass_filter.h, line 68 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfIGCYcsgq2SlNgo_ak:-KfIGCYdfo5Ribomg1PR:b-ucew1x) ([raw file](https://github.com/robotlocomotion/drake/blob/10091c9ad6f2d27fc21f92d5939a33cc18bf476a/drake/systems/primitives/first_order_low_pass_filter.h#L68)):*
> ```objc
>   /// This method aborts if called on filters if with different time constants
>   /// per input signal. @see get_time_constants_vector().
>   double get_time_constant() const;
> ```

BTW I slightly question the need for this helper to even exist since depending on the constructor form it'll probably abort most of the time (or are systems with the same constant for each element an expected case?).  It's probably harmless if a bit bloaty though.

---

*[drake/systems/primitives/test/first_order_low_pass_filter_test.cc, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfIH500bEVGGNzdw5dH:-KfIH501T-sdSsezWj9w:b-i2iifr) ([raw file](https://github.com/robotlocomotion/drake/blob/10091c9ad6f2d27fc21f92d5939a33cc18bf476a/drake/systems/primitives/test/first_order_low_pass_filter_test.cc#L8)):*
> ```cpp
> #include "drake/systems/framework/basic_vector.h"
> 
> #include "gtest/gtest.h"
> ```

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes indicates that gtest should be before the drake includes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502)*

**Comment by amcastro-tri** [comment]
I addressed the reviews. PTAL.
@siyuanfeng-tri, there still is a conversation blocked on you. I am actually happy with how the subindexes render and it looks like noone else has anything against them. Happy to change but only if there is a reasonable substitute. 

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-:-KfIehtK-jAz0b3oqhYA:bdtufsa)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/first_order_low_pass_filter.h, line 68 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-KfIGCYcsgq2SlNgo_ak:-KfIetdnOqE1FoxeKdKX:b-lwghyc) ([raw file](https://github.com/robotlocomotion/drake/blob/10091c9ad6f2d27fc21f92d5939a33cc18bf476a/drake/systems/primitives/first_order_low_pass_filter.h#L68)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW. The case I am interested in is when the signal being processed is a scalar function of time, i.e. the size of the input/output vectors is one. I'd like that case to behave as if this class was written for scalars.
Now, I did exactly that in a previous PR for the `Gain` system and later on its interface got updated to this. So I thought I would provide a similar API for consistency. Happy to change if you think like this is a bad idea.
</blockquote></details>

Nah, I'm fine with it how it is.  I was nitpicking for no particularly good reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5502#-:-KfIf-e3xHiVm_n6-vi_:bnfp4nl)*

**Pull request merged**
