### PR TITLE
Add symbolic::Expression::Substitute

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5016)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Related issue: https://github.com/RobotLocomotion/drake/issues/4877

**Comment by soonho-tri** [comment]
FWIW, I already implemented `symbolic::Formula::Substitute` but had to exclude it from this PR to make it `<500` loc.

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-:-KbvNEjcmE4Z9TgMeLhu:b-utjvo1)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 269 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-Kbvcpm4fLY0-Mz9LX2G:-Kbvcpm4fLY0-Mz9LX2H:b-udthk2) ([raw file](https://github.com/robotlocomotion/drake/blob/3067523246391211955bf059485966ae90f30b7f/drake/common/symbolic_expression_cell.cc#L269)):*
> ```cpp
> 
> Expression ExpressionConstant::Substitute(const Substitution& s) const {
>   DRAKE_ASSERT(!std::isnan(v_));
> ```

If this is not expensive, can we change it to `DRAKE_DEMAND`?

---

*[drake/common/symbolic_expression_cell.cc, line 418 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-KbvrShpiyMrEjUtYg7a:-KbvrShqDLUTJILeIVM8:bbsi324) ([raw file](https://github.com/robotlocomotion/drake/blob/3067523246391211955bf059485966ae90f30b7f/drake/common/symbolic_expression_cell.cc#L418)):*
> ```cpp
>   return accumulate(
>       exp_to_coeff_map_.begin(), exp_to_coeff_map_.end(), Expression::Zero(),
>       [&s](const Expression& init, const pair<Expression, double>& p) {
> ```

BTW. This is not a comment for this PR, but the name `exp_to_coeff_map_` can be confusing, since we also use `exp` to mean `exponent`, such as in `base_to_exp_map_`. I think it is better not to use `exp` as the abbreviation. I personally think we can use`expr` for `expression`, and `expnt` for `exponent`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-:-Kbw194EGLbDe7ikkINP:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 269 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-Kbvcpm4fLY0-Mz9LX2G:-KbzO4yr-1iXPg2HEkI_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3067523246391211955bf059485966ae90f30b7f/drake/common/symbolic_expression_cell.cc#L269)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If this is not expensive, can we change it to `DRAKE_DEMAND`?
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression_cell.cc, line 418 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-KbvrShpiyMrEjUtYg7a:-KbwJFZIMimnna4RnWOF:b-c30u6v) ([raw file](https://github.com/robotlocomotion/drake/blob/3067523246391211955bf059485966ae90f30b7f/drake/common/symbolic_expression_cell.cc#L418)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW. This is not a comment for this PR, but the name `exp_to_coeff_map_` can be confusing, since we also use `exp` to mean `exponent`, such as in `base_to_exp_map_`. I think it is better not to use `exp` as the abbreviation. I personally think we can use`expr` for `expression`, and `expnt` for `exponent`.
</blockquote></details>

I see. I'll open another PR doing these renaming.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5016)*

**Comment by soonho-tri** [comment]
+@david-german-tri , platform-review please.

---

Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-:-KbzPQvzZW4FvM-8Ko03:b-qoa6av)*

**Comment by david-german-tri** [comment]
Reviewed 3 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_substitution_test.cc, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-Kbzii_FuY8iAfKAz6BA:-Kbzii_FuY8iAfKAz6BB:bwyc83b) ([raw file](https://github.com/robotlocomotion/drake/blob/6e2aef9ab8444cb52ce8e915c84233449327e9a4/drake/common/test/symbolic_substitution_test.cc#L96)):*
> ```cpp
>   fns.push_back([&](const Expression& x) { return x * z_; });
>   fns.push_back([&](const Expression& x) { return z_ * x; });
>   fns.push_back([&](const Expression& x) { return x / y_; });
> ```

Suppose you simultaneously substitute `y_ = x` and `x = 0`.  What happens?  I note there's already a TODO for the unsound `E / E` simplification, but now I wonder if whether that's tickled would depend on the order of the Substitution map.

(Similar questions apply elsewhere.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5016)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_substitution_test.cc, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-Kbzii_FuY8iAfKAz6BA:-KbzlQXYESUiF4h2Y8Lb:bftd1xx) ([raw file](https://github.com/robotlocomotion/drake/blob/6e2aef9ab8444cb52ce8e915c84233449327e9a4/drake/common/test/symbolic_substitution_test.cc#L96)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Suppose you simultaneously substitute `y_ = x` and `x = 0`.  What happens?  I note there's already a TODO for the unsound `E / E` simplification, but now I wonder if whether that's tickled would depend on the order of the Substitution map.

(Similar questions apply elsewhere.)
</blockquote></details>

The order in a substitution map only matters if we do successive substitution (i.e. `N`-pass when there are `N` entries in a map). Please note that we do simultaneous substitution, which visits each node only once.

For example, with a given substitution map `y |-> x` and `x |-> 0`, we have `x / y` -> `0 / x`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5016)*

**Comment by david-german-tri** [comment]
:lgtm: great stuff, as always.

---

Reviewed 3 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_substitution_test.cc, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-Kbzii_FuY8iAfKAz6BA:-KbzsUEG-PfC8GrOjUv8:b-1ysnm8) ([raw file](https://github.com/robotlocomotion/drake/blob/6e2aef9ab8444cb52ce8e915c84233449327e9a4/drake/common/test/symbolic_substitution_test.cc#L96)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

The order in a substitution map only matters if we do successive substitution (i.e. `N`-pass when there are `N` entries in a map). Please note that we do simultaneous substitution, which visits each node only once.

For example, with a given substitution map `y |-> x` and `x |-> 0`, we have `x / y` -> `0 / x`.
</blockquote></details>

OK.  Cool.  And `0 / x` then simplifies to `0`, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-:-Kbzt303vCisHYqf9tWt:b-a6v0yx)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/common/test/symbolic_substitution_test.cc, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-Kbzii_FuY8iAfKAz6BA:-KbzxMS27rUnLjjn7Lf9:b-m282zx) ([raw file](https://github.com/robotlocomotion/drake/blob/6e2aef9ab8444cb52ce8e915c84233449327e9a4/drake/common/test/symbolic_substitution_test.cc#L96)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

OK.  Cool.  And `0 / x` then simplifies to `0`, right?
</blockquote></details>

I think we keep `0 / x` as it is for now. I'll be back after checking it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5016)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_substitution_test.cc, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5016#-Kbzii_FuY8iAfKAz6BA:-Kc-4yZUt5Rrx7QU6ty0:b9p2c3p) ([raw file](https://github.com/robotlocomotion/drake/blob/6e2aef9ab8444cb52ce8e915c84233449327e9a4/drake/common/test/symbolic_substitution_test.cc#L96)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think we keep `0 / x` as it is for now. I'll be back after checking it.
</blockquote></details>

Just checked. `0 / x` is not further simplified, and I think this is good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5016)*

**Comment by david-german-tri** [comment]
> `0 / x` is not further simplified, and I think this is good.

Having thought about this more, it seems pretty strange to me that I would specify a substitution for `x`, and still get `x` back in the result.  Is it possible that we should consider a substitution ill-formed if the same variable appears in both a key and a value?

**Comment by david-german-tri** [comment]
Also, if I'm understanding correctly, `0 / x` does not further simplify because there is no rule for it [here](https://github.com/RobotLocomotion/drake/blob/master/drake/common/symbolic_expression.cc#L436).  If the substitution instead resulted in `x / 1`, it would simplify, right?

**Comment by soonho-tri** [comment]
> Having thought about this more, it seems pretty strange to me that I would specify a substitution for x, and still get x back in the result. Is it possible that we should consider a substitution ill-formed if the same variable appears in both a key and a value?

AFAIK, this is allowed in substitution. For example, https://en.wikipedia.org/wiki/Substitution_(logic)#First-order_logic is using an example `{x ↦ z, z ↦ h(a,y)}` where `z` appears in both a key and a value.

One practical application is to implement a swap operation (i.e. `{x ↦ y, y ↦ x}`) using substitution.

I think it's OK as long as a user understand the semantics of 'simultaneous' substitution clearly.

**Comment by soonho-tri** [comment]
> Also, if I'm understanding correctly, 0 / x does not further simplify because there is no rule for it here. If the substitution instead resulted in x / 1, it would simplify, right?

That is correct.

**Pull request merged**
