### PR TITLE
pydrake: Rename pybind utility headers.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This renames C++ `pybind` header libraries from `file="*_py.h", target="*_py_h"` (ambiguous w.r.t. to other libraries) to `file="*_pybind.h", target="*_pybind"`.

This is meant to ease the porting of [`cpp_types` from here](https://github.com/EricCousineau-TRI/repro/tree/6659e31cf1d1234ee0f8b51e54bcd30ca264c6b6/python/bindings/pymodule/tpl) as `cpp_types_pybind` and `cpp_types_py`, to facilitate binding template classes / functions.

This also adds a quick blurb about conventions in the `BUILD` file.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7684)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@seancurtis-tri for feature and platform review, please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7684#-:-L1t8PcjvF2b9Bn2LQy-:b-ctnouu)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: One minor request for documentation clarification.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/BUILD.bazel, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7684#-L1whI5prCPyjUi6iSCv:-L1whI5prCPyjUi6iSCw:b-1dzztt) ([raw file](https://github.com/robotlocomotion/drake/blob/b655c3c7e42fe022128f94b9894868922f211326/bindings/pydrake/BUILD.bazel#L28)):*
> ```Python
> # N.B. Any common headers should be shared via a HEADER ONLY library.
> 
> # File/Target Naming Conventions:
> ```

BTW This comment seems a bit ambiguous, or perhaps over-overloaded. Some of these conventions apply to build target *names* and some seem to apply to source files. Can you clarify this further?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7684#-:-L1whlIVHkeUXcpp9bby:b4fwxcc)*

**Comment by EricCousineau-TRI** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/BUILD.bazel, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7684#-L1whI5prCPyjUi6iSCv:-L1x4WzPyOvay96rYc97:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b655c3c7e42fe022128f94b9894868922f211326/bindings/pydrake/BUILD.bazel#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This comment seems a bit ambiguous, or perhaps over-overloaded. Some of these conventions apply to build target *names* and some seem to apply to source files. Can you clarify this further?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7684)*

**Comment by SeanCurtis-TRI** [comment]
King of the quibble -- one last thing.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[bindings/pydrake/BUILD.bazel, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7684#-L1whI5prCPyjUi6iSCv:-L1x5FflMfnftqoglzOJ:b-vy6a3n) ([raw file](https://github.com/robotlocomotion/drake/blob/b655c3c7e42fe022128f94b9894868922f211326/bindings/pydrake/BUILD.bazel#L28)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW You're going to hate this. But can you move the "C++." onto the same line, or indent it. Right now, its current indentation seems to slightly obfuscate otherwise effective documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7684#-:-L1x5Zb_jq0sG5XSJH4h:b-r5gpkq)*

**Comment by EricCousineau-TRI** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[bindings/pydrake/BUILD.bazel, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7684#-L1whI5prCPyjUi6iSCv:-L1x8I6y6nGQk0-lLmE-:b-voil5r) ([raw file](https://github.com/robotlocomotion/drake/blob/b655c3c7e42fe022128f94b9894868922f211326/bindings/pydrake/BUILD.bazel#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW You're going to hate this. But can you move the "C++." onto the same line, or indent it. Right now, its current indentation seems to slightly obfuscate otherwise effective documentation.
</blockquote></details>

Done. Was actually a little pained by what I had, but didn't realize I still had space left on that line as I was moving stuff to different indents. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7684)*

**Comment by SeanCurtis-TRI** [comment]
Thanks

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7684#-:-L1x8iG_iE_X8yza1Ldj:b-zcjvte)*

**Pull request merged**
