### PR TITLE
Rename files to match coding conventions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Rename simulateLCM to car_sim_lcm.
- Rename publishDrivingCommand to publish_driving_command.
- Add "no window support" caveat to bash script.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2278) &emsp; Multiple assignees:&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok Please do a feature code review, if you have a moment.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2278#-:-KH18wmFcl0dpG4nnL4D:-585267707)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2278#-:-KH1ARJC5mrVuZKRZeob:1417088721)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri Platform review and merge?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2278#-:-KH1CCGyeGKrbOChJ27S:205856660)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2278#-:-KH1DWNt-S8y3xsKcSPz:1417088721)*

**Comment by david-german-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2278)*

**Comment by jwnimmer-tri** [comment]
The only jenkins error is #2257 flake. Using override-merge.

**Pull request merged**
