### PR TITLE
Compute volume of a VPolytope.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Use qhull to compute the volume

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
@mpetersen94 . I tried to do the similar thing for HPolyhedron, namely I first construct a qhull object from HPolyhedron, using your implementation in https://github.com/RobotLocomotion/drake/blob/92da26c177fad108fdd00c6d8c112d96a5970174/geometry/optimization/vpolytope.cc#L52-L82, and then call `qhull.volume()`. Strangely it doesn't return me the right volume. Do you know if there is some caveat in constructing qhull using h-representation, which would prevent it computing the volume? Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409#-:-MtqMnl-7EFvOk_Av2ad:b9f1i)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Comment by mpetersen94** [comment]
Honestly, I don't think qhull is intuitive (and maybe not even super helpful) in the halfspace setting.  If you look at the Hpoly->Vpoly conversion, I mostly just use it to find the faces incident on a vertex.  I think if you want to find the volume of a HPolyhedron, you might be better served by converting it to a VPolytope and then calculating its volume.

**Review by hongkai-dai — COMMENTED** [review]
@mpetersen94 Thanks Mark! I did exactly the same thing in one of my dev branch, namely to convert the HPolyhedron to a VPolytope and then calculate its volume. I will include it in this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409#-:-MtskMmH5X17U1QhYhX9:bjr4q0e)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409#-:-Mtt6QUn8r629ahDwpRC:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
nice!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409#-:-MuBCKckD95KX3b9AYp4:b-7m74ox)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[geometry/optimization/test/vpolytope_test.cc, line 409 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuBBwmV70VZmJ6e6ys2:-MuBBwmV70VZmJ6e6ys3:b-ryyvut) ([raw file](https://github.com/robotlocomotion/drake/blob/abf3f8279872a1ef707f8dad0dbc715aa35ab9fd/geometry/optimization/test/vpolytope_test.cc#L409)):*
> ```cpp
>   // clang-format off
>   vertices_2d << 1, -1, 0, 0,
>                  0, 0, 1, -1;
> ```

perhaps throw in another point in here (e.g. in the interior) to make the test a little more thorough?  I just want to make sure we get the volume of the convex hull.
___
*[geometry/optimization/test/vpolytope_test.cc, line 417 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuBC8F27UmLAtFj8g1-:-MuBC8F27UmLAtFj8g10:b-sjbsc8) ([raw file](https://github.com/robotlocomotion/drake/blob/abf3f8279872a1ef707f8dad0dbc715aa35ab9fd/geometry/optimization/test/vpolytope_test.cc#L417)):*
> ```cpp
>   vertices_3d << 1, 0, 0, 0, 0.25,
>                  0, 1, 0, 0, 0.25,
>                  0, 0, 1, 0, 0.25;
> ```

can we add a test with that is rank deficient?  Eg a 2d polytope in 3d?  The volume should be zero?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[geometry/optimization/test/vpolytope_test.cc, line 409 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuBBwmV70VZmJ6e6ys2:-MuCMg7nEItRfTNu-vE4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/abf3f8279872a1ef707f8dad0dbc715aa35ab9fd/geometry/optimization/test/vpolytope_test.cc#L409)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

perhaps throw in another point in here (e.g. in the interior) to make the test a little more thorough?  I just want to make sure we get the volume of the convex hull.
</blockquote></details>

Done.
___
*[geometry/optimization/test/vpolytope_test.cc, line 417 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuBC8F27UmLAtFj8g1-:-MuCqR2W2D4oGgBRxcT5:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/abf3f8279872a1ef707f8dad0dbc715aa35ab9fd/geometry/optimization/test/vpolytope_test.cc#L417)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

can we add a test with that is rank deficient?  Eg a 2d polytope in 3d?  The volume should be zero?
</blockquote></details>

Done. Good call.

**Review by RussTedrake — COMMENTED** [review]
:lgtm: 
+@ggould-tri for platform review, please.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409#-:-MuCrwNR0tfiFIEiTEc2:b-7r1296)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri)

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri and @hongkai-dai)

___
*[geometry/optimization/vpolytope.h, line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuCx5uY5hQ4WOp6-15w:-MuCx5uY5hQ4WOp6-15x:b-qf35f0) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/vpolytope.h#L73)):*
> ```objc
>    * @note this function calls qhull to compute the volume.
>    */
>   [[nodiscard]] double CalcVolume() const;
> ```

Can you add the HPolyhedron flavor of this?

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409#-:-MuD4To63fP4dKeswjgu:bnfp4nl)* status: 7 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[geometry/optimization/test/vpolytope_test.cc, line 404 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuD4IlhEu325bioynUl:-MuD4IlhEu325bioynUm:b214xlz) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/test/vpolytope_test.cc#L404)):*
> ```cpp
> GTEST_TEST(VPolytopeTest, CalcVolume) {
>   const double tol{1E-6};
>   EXPECT_NEAR(VPolytope::MakeUnitBox(3).CalcVolume(), 8, tol);
> ```

nit:  Our coding standards require decimals for doubles, e.g. `0.0`, `1.0`, etc.



_Suggestion:_
```cpp
8.0
```
___
*[geometry/optimization/test/vpolytope_test.cc, line 409 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuD45uL-8_IX1gQYWAy:-MuD45uL-8_IX1gQYWAz:b214xlz) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/test/vpolytope_test.cc#L409)):*
> ```cpp
>   // clang-format off
>   vertices_2d << 1, -1, 0, 0, 0,
>                  0, 0, 1, -1, 0;
> ```

nit:  Our coding standards require decimals for doubles, e.g. `0.0`, `1.0`, etc.
___
*[geometry/optimization/test/vpolytope_test.cc, line 411 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuD4NEGAoDF7TrZMVjm:-MuD4NEGAoDF7TrZMVjn:b214xlz) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/test/vpolytope_test.cc#L411)):*
> ```cpp
>                  0, 0, 1, -1, 0;
>   // clang-format on
>   EXPECT_NEAR(VPolytope(vertices_2d).CalcVolume(), 2, tol);
> ```

nit:  Our coding standards require decimals for doubles, e.g. `0.0`, `1.0`, etc.



_Suggestion:_
```cpp
2.0
```
___
*[geometry/optimization/test/vpolytope_test.cc, line 417 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuD4DF7AYeaT2Besj0X:-MuD4DF7AYeaT2Besj0Y:b214xlz) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/test/vpolytope_test.cc#L417)):*
> ```cpp
>   vertices_3d << 1, 0, 0, 0, 0.25,
>                  0, 1, 0, 0, 0.25,
>                  0, 0, 1, 0, 0.25;
> ```

nit:  Our coding standards require decimals for doubles, e.g. `0.0`, `1.0`, etc.
___
*[geometry/optimization/test/vpolytope_test.cc, line 421 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuD3xWG69ZZmjjAt9Qw:-MuD3xWG69ZZmjjAt9Qx:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/test/vpolytope_test.cc#L421)):*
> ```cpp
>   EXPECT_NEAR(VPolytope(vertices_3d).CalcVolume(), 1.0 / 6, tol);
> 
>   // A degenerated case where al the 3d vertices are on a 2d plane.
> ```

typo



_Suggestion:_
```cpp
degenerate
```
___
*[geometry/optimization/test/vpolytope_test.cc, line 426 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuD4PTZE_ii9y2ZSNW1:-MuD4PTZE_ii9y2ZSNW2:b214xlz) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/test/vpolytope_test.cc#L426)):*
> ```cpp
>   vertices_3d_planar << 1, -1, 0, 0,
>                         0, 0, 1, -1,
>                         0, 0, 0, 0;
> ```

nit:  Our coding standards require decimals for doubles, e.g. `0.0`, `1.0`, etc.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[geometry/optimization/test/vpolytope_test.cc, line 404 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuD4IlhEu325bioynUl:-MuD5jze7mt2we_NaiI2:b-taw34) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/test/vpolytope_test.cc#L404)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  Our coding standards require decimals for doubles, e.g. `0.0`, `1.0`, etc.
</blockquote></details>

This comment was wrong; retracting.

**Comment by ggould-tri** [comment]
Apologies for some noise below; I misremembered a style rule.  Comments retracted.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409)* status: 1 unresolved discussion, missing label for release notes (waiting on @mpetersen94 and @RussTedrake)

___
*[geometry/optimization/vpolytope.h, line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuCx5uY5hQ4WOp6-15w:-MuE1IFs1Ey17T5GH_Vt:birvnyp) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/vpolytope.h#L73)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Can you add the HPolyhedron flavor of this?
</blockquote></details>

Would you mind if I do it in a separate PR? The HPolyhedron volume is more complicated, I need to consider the following special cases
1. The H-polyhedron is empty, so the volume should be 0.
2. The H-polyhedron is unbounded, the volume can be either infinity (think of the halfspace space along the x-axis in 3D) or 0 (think of the xy plane in 3D).

I have a dev branch on this, but haven't found a good solution yet.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16409)* status: missing label for release notes (waiting on @RussTedrake)

___
*[geometry/optimization/vpolytope.h, line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16409#-MuCx5uY5hQ4WOp6-15w:-MuECT1A903mUheB_xKE:bdt6osm) ([raw file](https://github.com/robotlocomotion/drake/blob/0228cc02a2cc4ca2ea244648b2f19c97e3218cd6/geometry/optimization/vpolytope.h#L73)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Would you mind if I do it in a separate PR? The HPolyhedron volume is more complicated, I need to consider the following special cases
1. The H-polyhedron is empty, so the volume should be 0.
2. The H-polyhedron is unbounded, the volume can be either infinity (think of the halfspace space along the x-axis in 3D) or 0 (think of the xy plane in 3D).

I have a dev branch on this, but haven't found a good solution yet.
</blockquote></details>

That makes sense. Sounds good.

**Pull request merged**
