### PR TITLE
Add method to parallel MakeColumnsFromOrthonormalBasis.  Improve efficiency.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9812)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
___
*[math/rotation_matrix.h, line 25 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9812#-LQ0_Yky6oiZPUdkKJUo:-LQ0mYwhDYx41COzV3ln:bxoadil) ([raw file](https://github.com/robotlocomotion/drake/blob/01c8c0742e3cefccc1a67df6937b2d89660b947b/math/rotation_matrix.h#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW While it may not *technically* be a defect, naming a type with `Enum` feels like it *should* be.  I'd propose:

```c++
enum class InitializePolicy {
  kIdentity,
  kNoInitialize
};
```

Then invocations look like: `InitializePolicy::kIdentity` or `InitializePolicy::kNoInitialize`. It's also good to have a default value that you like so that if it is ever default used, you've got the value you want.

The second enumerated value may be a bridge too far, but I'd definitely pick something that is more compact and readable than what you currently have.
</blockquote></details>

FYI Personally I would just use an empty nested private tag struct.
```c++
static RotationMatrix<T> Factory() {
RotationMatrix<T> result(DoNotInitializeMemberFields{});
...
private:
struct DoNotInitializeMemberFields{};
RotationMatrix<T>(DoNotInitializeMemberFields) {}

```
... and then everyone who _does_ want to initialize them can retain the current default -- only the special case is flagged.

**Comment by sherm1** [comment]
I believe the problem @mitiguy was trying to avoid is that private types can't be referenced from a preceding implementation in the public section (that's right isn't it?). Our GSG prohibits declaring those private types earlier (like just before `public:`), so the method definition has to be moved to after the class declaration, with suitable `inline` shenanigans. Probably better to do that, but it is ugly for small methods.

**Comment by sherm1** [comment]
Nope -- my bad. Forward referencing the private type works fine.

**Comment by jwnimmer-tri** [comment]
I fixed the assignments.  The only thing left is the squash, either with a new push, or using the big green button.

**Pull request merged**
