### PR TITLE
Modifies drake::NiceTypeName::Canonicalize() to throw exception when compiled with gcc 4.8 or below.

### LINKED ISSUE #6247: nice_type_name.cc Defines Regular Expressions that are Incompatible with gcc 4.8.5
`drake::NiceTypeName::Canonicalize(const string& demangled)` currently defines several regular expressions that are incompatible with the `std::regex` provided by gcc 4.8.5. This results in a `std::regex_error` being thrown.

[Here is the current code.](https://github.com/RobotLocomotion/drake/blob/ee75498908a078a4d641757af870ce351bd51a71/drake/common/nice_type_name.cc#L52-L69)

We should update the code to gracefully handle this situation.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #6247.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6248)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please.
@drake-jenkins-bot mac-clang-experimental please.
@drake-jenkins-bot mac-clang-ninja-experimental please.

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please since you have experience placating gcc 4.8's version of `std::regex`. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-:-Kln2sfv1K_ZJTikMX2f:b-d8p8f9)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-Kln7Hn7rEmERsrUaOWz:-Kln7Hn8z3WcmTKTqLG4:b-q1ircs) (no related file):*
Please explain why back-porting Drake master is a better choice than changing TRI's GCC-4.8-based software to avoid calling `NiceTypeName`?

My impression from a quick skim of Drake code is that the only place `NiceTypeName` will be called is (1) to populate exception detail messages, or (2) when a System is added to a diagram without first setting its name.  For (1) we don't care (we're going to abort anyway), and for (2) it's easy to just provide the name (perhaps with a TODO) until TRI's GCC 4.8 requirement is dropped.

But of course, that's from only 5 minutes of looking.  If there is some other reason, please explain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248)*

**Comment by liangfok** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-Kln7Hn7rEmERsrUaOWz:-KlrlpBO5o8_hks_ihwY:b-tcg9zg) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please explain why back-porting Drake master is a better choice than changing TRI's GCC-4.8-based software to avoid calling `NiceTypeName`?

My impression from a quick skim of Drake code is that the only place `NiceTypeName` will be called is (1) to populate exception detail messages, or (2) when a System is added to a diagram without first setting its name.  For (1) we don't care (we're going to abort anyway), and for (2) it's easy to just provide the name (perhaps with a TODO) until TRI's GCC 4.8 requirement is dropped.

But of course, that's from only 5 minutes of looking.  If there is some other reason, please explain.
</blockquote></details>

Upon further investigation, modifying `MaliputRailcar` to provide a constructor that allows a user to specify a name avoids the `std::regex` issue. I have thus updated this PR as follows:

1. Adds new constructor to MaliputRailcar to allow name to be specified.
2. Modifies `drake::NiceTypeName::Canonicalize()` to throw an exception if a user attempts to call it when it is compiled in gcc 4.8 or below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@sammy-tri for platform review, please (on call for tomorrow).

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/nice_type_name.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-KlsGfydNuk8y1ogcxPZ:-KlsGfydNuk8y1ogcxP_:b-ge3uej) ([raw file](https://github.com/robotlocomotion/drake/blob/6f31ee820a1df9ae98a7fd9363cb15dc29c0a61a/drake/common/nice_type_name.cc#L58)):*
> ```cpp
>   throw std::runtime_error("drake::NiceTypeName::Canonicalize() is not "
>       "compatible with with gcc < 4.9 due to its use of std::regex.");
> #endif
> ```

BTW Consider `#undef GCC_VERSION` here; macros should have as small scope as possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-:-KlsHPzz_5xUCg0XCREi:b1karmh)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/nice_type_name.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-KlsGfydNuk8y1ogcxPZ:-KlsaCy6h4LR8eDtdfrO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f31ee820a1df9ae98a7fd9363cb15dc29c0a61a/drake/common/nice_type_name.cc#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Consider `#undef GCC_VERSION` here; macros should have as small scope as possible.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248)*

**Comment by sammy-tri** [comment]
:lgtm: pending CI (which doesn't immediately appear to be to actually be a problem with this PR)

---

Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput_railcar.cc, line 75 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-KlswI3eyxd-0RskhYfI:-KlswI3fWD-SYwMIenQD:b-ipnt6m) ([raw file](https://github.com/robotlocomotion/drake/blob/23836ae104980d39d0e02e49a790b6880babde19/drake/automotive/maliput_railcar.cc#L75)):*
> ```cpp
>     const LaneDirection& initial_lane_direction)
>     : MaliputRailcar(initial_lane_direction) {
>   systems::System<T>::set_name(name);
> ```

BTW this seems a little more fancy than needed when the construction code could just call set_name after the constructor, but I don't think this is technically defective.  

---

*[drake/automotive/maliput_railcar.h, line 105 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-KlsvjdsSqquyIRBiDua:-KlsvjduWnZKfUdm9cL-:b-214upk) ([raw file](https://github.com/robotlocomotion/drake/blob/23836ae104980d39d0e02e49a790b6880babde19/drake/automotive/maliput_railcar.h#L105)):*
> ```objc
>   ///
>   MaliputRailcar(const std::string& name,
>       const LaneDirection& initial_lane_direction);
> ```

BTW Indentation here is inconsistent with the rest of the file which uses a 4 space indent if there are no arguments on the same line as the function name and aligns the arguments if there is one present on the first line.  See DoCalcOutput and DoCalcTimeDerivatives immediately below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-:-Klswj4GTY0pITpudqgy:bmj7fmk)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput_railcar.cc, line 75 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-KlswI3eyxd-0RskhYfI:-KlsxSroQvHw0y7G-bDu:bkahmm7) ([raw file](https://github.com/robotlocomotion/drake/blob/23836ae104980d39d0e02e49a790b6880babde19/drake/automotive/maliput_railcar.cc#L75)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this seems a little more fancy than needed when the construction code could just call set_name after the constructor, but I don't think this is technically defective.  
</blockquote></details>

FYI The (undocumented) reason this constructor is useful is when [DiagramBuilder::AddSystem](http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_diagram_builder.html#a3bd42ae34dbf6a06f89bc73425f8e499) is being called -- it jointly creates and then adds a System, and the name can no longer be changed after the System added to the builder.

Though that does merit a question -- perhaps the better fix would have been to add a new method `DiagramBuild::AddSystemWithName(std::string, Args&& args...)` and put the name-assignment into the Diagram step.  (That seems much better to me, FWIW.)  Then, the fix works for all Systems, not just this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 75 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-KlswI3eyxd-0RskhYfI:-KltidI8mGcPDfL038dn:b2bajs4) ([raw file](https://github.com/robotlocomotion/drake/blob/23836ae104980d39d0e02e49a790b6880babde19/drake/automotive/maliput_railcar.cc#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The (undocumented) reason this constructor is useful is when [DiagramBuilder::AddSystem](http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_diagram_builder.html#a3bd42ae34dbf6a06f89bc73425f8e499) is being called -- it jointly creates and then adds a System, and the name can no longer be changed after the System added to the builder.

Though that does merit a question -- perhaps the better fix would have been to add a new method `DiagramBuild::AddSystemWithName(std::string, Args&& args...)` and put the name-assignment into the Diagram step.  (That seems much better to me, FWIW.)  Then, the fix works for all Systems, not just this one.
</blockquote></details>

Good idea. I reverted the change to `MaliputRailcar` in this PR to focus it on the UX improvement to `drake::NiceTypeName::Canonicalize()`. I'll submit a separate PR with the suggested `DiagramBuilder` change.

---

*[drake/automotive/maliput_railcar.h, line 105 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6248#-KlsvjdsSqquyIRBiDua:-Kltl8L4Bio1attqDToJ:b-7l0ulg) ([raw file](https://github.com/robotlocomotion/drake/blob/23836ae104980d39d0e02e49a790b6880babde19/drake/automotive/maliput_railcar.h#L105)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW Indentation here is inconsistent with the rest of the file which uses a 4 space indent if there are no arguments on the same line as the function name and aligns the arguments if there is one present on the first line.  See DoCalcOutput and DoCalcTimeDerivatives immediately below.
</blockquote></details>

Done (reverted in this PR).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6248)*

**Pull request merged**
