### PR TITLE
RgbdCamera: Add depth range arguments to the constractor

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This allows users to create `RgbdCamera` that has arbitrary depth measurement range.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6851)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@ericcousineau-tri feature review please. With this change, the usage like dense contact sensor becomes much easy. Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-:-Krfk9WUefMUC4kM5XSN:bleva9o)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with minor BTWs. Thanks!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-KrgWg0GMQkJ-S8ZTVJb:-KrgWg0GMQkJ-S8ZTVJc:b-bfm6hv) ([raw file](https://github.com/robotlocomotion/drake/blob/4122622d029914efa6c41279c7654e92cccedc95/drake/systems/sensors/test/rgbd_camera_test.cc#L113)):*
> ```cpp
>     const double kDynamicFriction = 0.5;
>     const double kStictionSlipTolerance = 0.01;
>     plant_->set_normal_contact_parameters(kPenetrationStiffness,
> ```

BTW Are these necessary for this test? Or could the default values be used?

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 531 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-KrgYUf6KdJTstm8XGbG:-KrgYUf6KdJTstm8XGbH:b7kwogn) ([raw file](https://github.com/robotlocomotion/drake/blob/4122622d029914efa6c41279c7654e92cccedc95/drake/systems/sensors/test/rgbd_camera_test.cc#L531)):*
> ```cpp
>       depth_image_(kWidth, kHeight, 1) {}
> 
>   void VerifyTooFarTooClose() {
> ```

BTW Could you add a comment pointing to the documentation for point cloud conversion, using PCL's convention that depth == "too far" / "too close" will yield "too far" in the point cloud?

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 535 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-KrgX6xXsh18drdkwMkK:-KrgX6xXsh18drdkwMkL:b-6bej5y) ([raw file](https://github.com/robotlocomotion/drake/blob/4122622d029914efa6c41279c7654e92cccedc95/drake/systems/sensors/test/rgbd_camera_test.cc#L535)):*
> ```cpp
>       for (int u = 0; u < depth_image_.width(); ++u) {
>         const int i = v * depth_image_.width() + u;
>         Eigen::Vector3f actual(Eigen::Map<Eigen::Vector3f>(
> ```

BTW I believe this could be simplified to `Vector3f actual = actual_point_cloud_.col(i)`, since a copy seems suitable.
Otherwise, you could use `Eigen::Ref<Vector3d> actual = actual_point_cloud_.col(i)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-:-KrgZH2pDfUTOIf7GNhh:b-i0lovc)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 512 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-KrgZdXCVttiUypLFw87:-KrgZdXD-J1rOqM88WkP:b-8cjy98) ([raw file](https://github.com/robotlocomotion/drake/blob/4122622d029914efa6c41279c7654e92cccedc95/drake/systems/sensors/test/rgbd_camera_test.cc#L512)):*
> ```cpp
> 
> // Verifies the case that a model has multiple visuals.
> TEST_F(ImageTest, MultipleVisualsTest) {
> ```

Sorry, follow-up - would it be possible to place objects outside of the view frustum, to verify that they indeed disappear?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6851)*

**Comment by kunimatsu-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-KrgWg0GMQkJ-S8ZTVJb:-KrkYzDcqNl7YeXKmhkh:bqwypk5) ([raw file](https://github.com/robotlocomotion/drake/blob/4122622d029914efa6c41279c7654e92cccedc95/drake/systems/sensors/test/rgbd_camera_test.cc#L113)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Are these necessary for this test? Or could the default values be used?
</blockquote></details>

Deleted all. Done.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 512 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-KrgZdXCVttiUypLFw87:-KrkbsNR6DV5VdHfgtye:b-6f9qgd) ([raw file](https://github.com/robotlocomotion/drake/blob/4122622d029914efa6c41279c7654e92cccedc95/drake/systems/sensors/test/rgbd_camera_test.cc#L512)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Sorry, follow-up - would it be possible to place objects outside of the view frustum, to verify that they indeed disappear?
</blockquote></details>

I'm fine to add the new test case, but not sure how to verify it. Do you have any idea?

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 531 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-KrgYUf6KdJTstm8XGbG:-Krka6mTQrn9YJz3jrIp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4122622d029914efa6c41279c7654e92cccedc95/drake/systems/sensors/test/rgbd_camera_test.cc#L531)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could you add a comment pointing to the documentation for point cloud conversion, using PCL's convention that depth == "too far" / "too close" will yield "too far" in the point cloud?
</blockquote></details>

Done.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 535 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-KrgX6xXsh18drdkwMkK:-KrkZgYThgGmVNUKefSW:b4855pb) ([raw file](https://github.com/robotlocomotion/drake/blob/4122622d029914efa6c41279c7654e92cccedc95/drake/systems/sensors/test/rgbd_camera_test.cc#L535)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I believe this could be simplified to `Vector3f actual = actual_point_cloud_.col(i)`, since a copy seems suitable.
Otherwise, you could use `Eigen::Ref<Vector3d> actual = actual_point_cloud_.col(i)`.
</blockquote></details>

Thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6851)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/test/rgbd_camera_test.cc, line 512 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-KrgZdXCVttiUypLFw87:-KrkhAgVJxmB6ArYF1M0:b-v53u6a) ([raw file](https://github.com/robotlocomotion/drake/blob/4122622d029914efa6c41279c7654e92cccedc95/drake/systems/sensors/test/rgbd_camera_test.cc#L512)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I'm fine to add the new test case, but not sure how to verify it. Do you have any idea?
</blockquote></details>

Never mind.  I place an object outside of the view at LabelRenderingTest, instead of MultipleVisualsTest, and verify that we don't get id from that object.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6851)*

**Comment by kunimatsu-tri** [comment]
+@soonho-tri platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-:-KrkiHl0j0jt38MlyUBR:b-gzl4jp)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-:-KrlCCLxSD9TbItR6KkB:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6851#-:-KrlHdIeTEksjuYW2WjF:bg0xcbm)*

**Pull request merged**
