### PR TITLE
[tutorials] Install tutorials in binary releases

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #12461.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16644)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
There's still more work to do to clean up our landing page's tutorials copy and to get Deepnote up and running, but I think shipping the tutorials in the release (especially the wheels) is a huge win.

image

+@rpoyner-tri for feature review, please?

FYI @RussTedrake @EricCousineau-TRI as you've touched this area in the past.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:, nittery, testing questions

> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16644#-:-MwXECgo0w7AJTw2rJDZ:b-xybtsz)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwXDqZZ8SIH6OEKxcAf:-MwXDqZZ8SIH6OEKxcAg:b-2ci4wm) (no related file):*
Testing questions:

I'm unlikely to spend an hour on platform-review day building wheels to test this. Is there a shortcut, or can I trust your manual testing?

Has this been tested to work on 18.04? On mac?

---
___
*[tutorials/BUILD.bazel, line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwXAOr9CK16EG8gEGMY:-MwXAOr9CK16EG8gEGMZ:bxnncnn) ([raw file](https://github.com/robotlocomotion/drake/blob/624a25b6ca05439302f9b2b350a6d78ad85beb7c/tutorials/BUILD.bazel#L4)):*
> ```Starlark
> # vi: set ft=python :
> 
> load("//tools/jupyter:jupyter_py.bzl", "drake_jupyter_py_binary")
> ```

nit I can't figure out why the ordering of these statements changed, or if it means anything. Ought the be alphabetical, like includes/imports?
___
*[tutorials/BUILD.bazel, line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwXAmf_8WaZFt9vVcgS:-MwXAmf_8WaZFt9vVcgT:bfka2va) ([raw file](https://github.com/robotlocomotion/drake/blob/624a25b6ca05439302f9b2b350a6d78ad85beb7c/tutorials/BUILD.bazel#L5)):*
> ```Starlark
> 
> load("//tools/jupyter:jupyter_py.bzl", "drake_jupyter_py_binary")
> load("@drake//tools/install:install.bzl", "install", "install_files")
> ```

nit not sure why one load uses `@drake` and the others do not.

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule (tomorrow), please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16644#-:-MwXbQeUEPogwpOdxbGd:b-2gnyz2)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @rpoyner-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwXHfIc0nKNdaILH3VG:-MwXbADwEQO_QoGTRRjp:bekhs0t) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'll build and this on `macsim`, run the install target, and then see if I can browse the tutorial notebooks over ssh forwarding of the http server.
</blockquote></details>

Done.

Tested on macsim:

```sh
bazel run //:install -- /Users/jwnimmer/tmpinstall
env PYTHONPATH=/Users/jwnimmer/tmpinstall/lib/python3.9/site-packages \
  /usr/local/opt/python@3.9/bin/python3 -m pydrake.tutorials
```

---

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with one clarification request.

> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16644#-:-MwYP80y4ycJ20Kk90yJ:b-ei5rds)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tutorials/README.md, line 80 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwYKWUp2xUa53FKbVBN:-MwYKWUp2xUa53FKbVBO:b-y1a9yw) ([raw file](https://github.com/robotlocomotion/drake/blob/624a25b6ca05439302f9b2b350a6d78ad85beb7c/tutorials/README.md#L80)):*
> ```Markdown
> - To rebuild from source and run tutorials using Bazel, use:
> ```
> bazel run //tutorials:mathematical_program
> ```

BTW, is the mathematical program tutorial special in any way? Or is this just to illustrate an example?
___
*[bindings/pydrake/tutorials.py, line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwYOHun-qRoMH_fQyEI:-MwYOHun-qRoMH_fQyEJ:b-g4e512) ([raw file](https://github.com/robotlocomotion/drake/blob/624a25b6ca05439302f9b2b350a6d78ad85beb7c/bindings/pydrake/tutorials.py#L9)):*
> ```Python
> ``python3 -m pydrake.tutorials`` to launch a Jupyter browser.
> 
> Be sure your ``PYTHONPATH`` has been set per the installation instructions.
> ```

I tried following the instruction here and it took me a minute to figure out where the instruction to set `PYTHONPATH` is -- It's not in the linked page https://drake.mit.edu/installation.html. Instead, it's only mentioned in apt installment page.  This should be made more clear.

Even after I followed the instructions of the installment page. I still get the following error 
"/usr/bin/python3: No module named pydrake.tutorials" when I run `python3 -m pydrake.tutorials`. Any thoughts on where I have messed up?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16644)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[tutorials/README.md, line 80 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwYKWUp2xUa53FKbVBN:-MwYY0gs-3w1rl0EycEW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/624a25b6ca05439302f9b2b350a6d78ad85beb7c/tutorials/README.md#L80)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is the mathematical program tutorial special in any way? Or is this just to illustrate an example?
</blockquote></details>

Done.
___
*[bindings/pydrake/tutorials.py, line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwYOHun-qRoMH_fQyEI:-MwYYXWT977wv0ZvHKDT:bg7r6ig) ([raw file](https://github.com/robotlocomotion/drake/blob/624a25b6ca05439302f9b2b350a6d78ad85beb7c/bindings/pydrake/tutorials.py#L9)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I tried following the instruction here and it took me a minute to figure out where the instruction to set `PYTHONPATH` is -- It's not in the linked page https://drake.mit.edu/installation.html. Instead, it's only mentioned in apt installment page.  This should be made more clear.

Even after I followed the instructions of the installment page. I still get the following error 
"/usr/bin/python3: No module named pydrake.tutorials" when I run `python3 -m pydrake.tutorials`. Any thoughts on where I have messed up?
</blockquote></details>

We can try to debug via slack if you like.  I've also added text here to help clarify the common case (when using pip).

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16644)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/tutorials.py, line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwYOHun-qRoMH_fQyEI:-MwY_C7fBRm4e4BCnKMd:b-ncis0x) ([raw file](https://github.com/robotlocomotion/drake/blob/624a25b6ca05439302f9b2b350a6d78ad85beb7c/bindings/pydrake/tutorials.py#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We can try to debug via slack if you like.  I've also added text here to help clarify the common case (when using pip).
</blockquote></details>

I think that'd be helpful (in case the trap I fell into is a common one).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16644)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tutorials/README.md, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwYbZEMBUbHjq7-4N3k:-MwYbZEMBUbHjq7-4N3l:b-7bmva9) ([raw file](https://github.com/robotlocomotion/drake/blob/089636045047a89aa2aac2b5ba1798b6faca617d/tutorials/README.md#L12)):*
> ```Markdown
> (e.g., [pip install drake](https://drake.mit.edu/pip.html)),
> be sure your `PYTHONPATH` has been set per the installation instructions,
> and then run `python3 -m pydrake.tutorials` to launch a Jupyter browser.
> ```

Working

This will be misleading until we do the next stable release after this PR.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16644)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16644)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[tutorials/README.md, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16644#-MwYbZEMBUbHjq7-4N3k:-MwYhVrU3tyjK0WC4ixK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/089636045047a89aa2aac2b5ba1798b6faca617d/tutorials/README.md#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

This will be misleading until we do the next stable release after this PR.
</blockquote></details>

Done.

**Pull request merged**
