### PR TITLE
[examples] Update spatula_slip_control README about visualization

### LINKED ISSUE #20559: Update spatula_slip_control README
### What happened?

I recently built and installed Drake from source, and I have been trying some of its new features. As I wanted to test the Meshcat's animation API, I found that Acrobot's `Spatula Slip Control` examples had some interesting c++ demonstration of it.

While following its internal [README](https://github.com/RobotLocomotion/drake/blob/master/examples/acrobot/README.md) to execute the example, I used the following command:
```
bazel run //tools:meldis -- --open-window &
bazel run //examples/acrobot:run_passive
```
The problem in this example is that while using `meldis`, the visualizer will not show the Playback control exposed after `PublishRecording()`.

Later, I was told by @DamrongGuoy (thanks) that I should just run the example without the meldis, and access its `localhost:7000`.

### Version

Nightly

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Fix #20559

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20596)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@joemasterjohn for feature review, please.

I do not know why Reviewable didn't let me assign @Vinggui as a reviewer.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-:-NkIKPDn5_5uVRoLGgd6:bfzb9il)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @DamrongGuoy)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: as is, but I gave some additional doc suggestions that might preempt some further user confustion. 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-:-NkL_5zwD8oR9dV12Uvu:b-74m9tu)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @DamrongGuoy)

___
*[`examples/hydroelastic/spatula_slip_control/README.md` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-NkLXvjFEEJuZQT6KKf6:-NkLXvjFEEJuZQT6KKf7:b-m39ao0) ([raw file](https://github.com/RobotLocomotion/drake/blob/58cdeab705fb109986bbaf2d166859d4cccffb43/examples/hydroelastic/spatula_slip_control/README.md#L29)):*
> ```Markdown
> 
> Use the MeshCat URL from the log messages for visualization.  For example, 
> it is `http://localhost:7002` at the last line of these log messages:
> ```

nit: Just some language clarification.



_Suggestion:_
```Markdown
Use the MeshCat URL from the console log messages for visualization. In
the example console output below, the last line contains the log message
with the MeshCat URL `http://localhost:7002`.
```
___
*[`examples/hydroelastic/spatula_slip_control/README.md` line 45 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-NkLYvbm0k0UXl4EY5To:-NkLYvbm0k0UXl4EY5Tp:b-eg9dtp) ([raw file](https://github.com/RobotLocomotion/drake/blob/58cdeab705fb109986bbaf2d166859d4cccffb43/examples/hydroelastic/spatula_slip_control/README.md#L45)):*
> ```Markdown
> 
> Please note that other examples may instruct users to run `meldis` for 
> visualization. However, this example recommends using MeshCat URL from 
> ```

nit: Just to clarify to the user unfamiliar with meldis vs. in-process meshcat, I would talk about them explicitly here. Maybe even add a snippet of the lines from the example where the in-process `MeshcatVisualizer` system is added to the diagram. That can also link to [MeshcatVisualizer docs](https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_meshcat_visualizer.html).



_Suggestion:_
```Markdown
 However, this example recommends using the in-process MeshCat URL from
```

**Review by joemasterjohn — COMMENTED** [review]
+@xuchenhan-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-:-NkL_QMj5Ge6Gar8gw9-:b223nro)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @DamrongGuoy)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform
+(release notes: none) 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-:-NkLxc888iHMv_UMT_MP:brrxvi0)* status: 3 unresolved discussions

___
*[`examples/hydroelastic/spatula_slip_control/README.md` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-NkLxks33Kn5dpUAYyBk:-NkLxks33Kn5dpUAYyBl:b-wvbojb) ([raw file](https://github.com/RobotLocomotion/drake/blob/58cdeab705fb109986bbaf2d166859d4cccffb43/examples/hydroelastic/spatula_slip_control/README.md#L44)):*
> ```Markdown
> ```
> 
> Please note that other examples may instruct users to run `meldis` for 
> ```

nit white space at the end of the line in a couple of places.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20596)* status: :shipit: complete! all discussions resolved, LGTM from assignees joemasterjohn,xuchenhan-tri(platform)

___
*[`examples/hydroelastic/spatula_slip_control/README.md` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-NkLXvjFEEJuZQT6KKf6:-NkNGi0i4j-NblHSEC5v:bronz8k) ([raw file](https://github.com/RobotLocomotion/drake/blob/58cdeab705fb109986bbaf2d166859d4cccffb43/examples/hydroelastic/spatula_slip_control/README.md#L29)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Just some language clarification.
</blockquote></details>

Done. Thanks for being explicit.
___
*[`examples/hydroelastic/spatula_slip_control/README.md` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-NkLxks33Kn5dpUAYyBk:-NkNKqaOC7xyaD_T5zLS:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/58cdeab705fb109986bbaf2d166859d4cccffb43/examples/hydroelastic/spatula_slip_control/README.md#L44)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit white space at the end of the line in a couple of places.
</blockquote></details>

Done. Thanks.
___
*[`examples/hydroelastic/spatula_slip_control/README.md` line 45 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20596#-NkLYvbm0k0UXl4EY5To:-NkNKtPdBMDmoSRZquW4:bvooq11) ([raw file](https://github.com/RobotLocomotion/drake/blob/58cdeab705fb109986bbaf2d166859d4cccffb43/examples/hydroelastic/spatula_slip_control/README.md#L45)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Just to clarify to the user unfamiliar with meldis vs. in-process meshcat, I would talk about them explicitly here. Maybe even add a snippet of the lines from the example where the in-process `MeshcatVisualizer` system is added to the diagram. That can also link to [MeshcatVisualizer docs](https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_meshcat_visualizer.html).
</blockquote></details>

Done.  Thanks. I chose to add a snippet of code about recording animation to explain the story.

**Pull request merged**
