### PR TITLE
[geometry] Add array-based getters and setters to Rgba

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Rewrite serialization to add python bindings.

Towards https://github.com/RobotLocomotion/drake/pull/18566 (and therefore https://github.com/RobotLocomotion/drake/issues/17112).

Requires #18572 first.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

Note that this will not pass all of its tests until #18572 merges.  I'm OK if you want to wait for that to land, but in case you'd like to get started now the code should be in practically its final form.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLanRkK4Awa7hOwnb_r:-NLanRkK4Awa7hOwnb_s:b-cxrucs) (no related file):*
Working

Check Anzu CI.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
A few small clarity things.

:LGTM:

> Reviewed 4 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-:-NLbFGGtBDq7at3BB1p2:bjvda3o)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/yaml/yaml_read_archive.h` line 379 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbCIek--PQnRbbsauN:-NLbCIek--PQnRbbsauO:b-rqro89) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/common/yaml/yaml_read_archive.h#L379)):*
> ```objc
>     if (max_size.has_value() && size > *max_size) {
>       ReportError(fmt::format(
>           "has too many array elements ({}); the maximum size is {} in the",
> ```

nit: Confused about the trailling "in the". The other `ReportError` usages have complete error descriptions without any trailing artifacts.
___
*[`geometry/rgba.h` line 94 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLb9W1n9x5iKn0_56YD:-NLb9W1n9x5iKn0_56YE:bpso7e5) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/geometry/rgba.h#L94)):*
> ```objc
>     // We want to be sure that value_ remains well-formed even if set() throws,
>     // so we'll clear it and then reset it.
>     auto new_value = value_;
> ```

nit: This `auto` feels dubious. Is this simply to avoid typing the whole templated declaration?
___
*[`geometry/rgba.h` line 105 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbCp0677O3l-rMkker:-NLbCp0677O3l-rMkkes:b-to9c96) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/geometry/rgba.h#L105)):*
> ```objc
>   // need to declare it as Eigen::Dynamic for compatibility with Serialize.
>   // As documented above, default-constructed Rgba is opaque white.
>   Eigen::Matrix<double, Eigen::Dynamic, 1, 0, 4, 1> value_{
> ```

nit: This particular incantation will be hard to grok. *What* is being done and *why* it is being done requires sleuthing.

Figuring out the "what" requires exploring the semantics of the template parameters that few drake developers ever look at and recognizing we've set max rows.

Figuring out *why* we're doing that requires understanding how it plays with yaml.

As this second point is *particularly* baroque, I think it'll help maintainers to be pointed in that direction.
___
*[`geometry/test/rgba_test.cc` line 112 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbAEbQ2u7Nqo8WhEX-:-NLbAEbQ2u7Nqo8WhEX0:b6lz9z9) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/geometry/test/rgba_test.cc#L112)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       yaml::LoadYamlString<Rgba>("rgba: [1, 1, 1, 1, 1]"),
>       ".*maximum size is 4.*");
> ```

BTW This error message in this test file may surprise readers (it surprised me). Given that `Rgba` explicitly validates vector size in `set()` and `set()` is called in archiving, one would not expect *this* message. Probably a comment saying indicating that the yaml error mechanism got first whack at the problem might help.

Exacerbated by the fact that for a vector that is too small, we get the expected response.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`common/yaml/yaml_read_archive.h` line 379 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbCIek--PQnRbbsauN:-NLbHZom9IitOlS1pFBU:b-9olzfw) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/common/yaml/yaml_read_archive.h#L379)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Confused about the trailling "in the". The other `ReportError` usages have complete error descriptions without any trailing artifacts.
</blockquote></details>

Here is an example error message when the array is too big (taken from the rgba unit test):

`YAML node of type Mapping (with size 1 and keys {rgba}) has too many array elements (5); the maximum size is 4 in the entry for Eigen::Matrix<double,-1,1,0,4,1> rgba.`

So two questions:

(1) Is the message on its own a good one?

(2) Should the source code here somehow be made more clear about what's going on?
___
*[`geometry/rgba.h` line 94 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLb9W1n9x5iKn0_56YD:-NLbFrd04x1KN47zs6ZJ:b-ni9wxb) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/geometry/rgba.h#L94)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This `auto` feels dubious. Is this simply to avoid typing the whole templated declaration?
</blockquote></details>

Yes.  Typing it again longform would be too brittle, which means we'd need a typedef, and that seemed like overkill.  My hypothesis was that a typical reader would not struggle too much to understand this formulation.
___
*[`geometry/rgba.h` line 105 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbCp0677O3l-rMkker:-NLbJGqd71o-MiJ64-Kv:bbgm45i) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/geometry/rgba.h#L105)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This particular incantation will be hard to grok. *What* is being done and *why* it is being done requires sleuthing.

Figuring out the "what" requires exploring the semantics of the template parameters that few drake developers ever look at and recognizing we've set max rows.

Figuring out *why* we're doing that requires understanding how it plays with yaml.

As this second point is *particularly* baroque, I think it'll help maintainers to be pointed in that direction.
</blockquote></details>

Hopefully this rewrite is more clear?
___
*[`geometry/test/rgba_test.cc` line 112 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbAEbQ2u7Nqo8WhEX-:-NLbGuaf0Ai0VnULXFKl:b24ttf1) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/geometry/test/rgba_test.cc#L112)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This error message in this test file may surprise readers (it surprised me). Given that `Rgba` explicitly validates vector size in `set()` and `set()` is called in archiving, one would not expect *this* message. Probably a comment saying indicating that the yaml error mechanism got first whack at the problem might help.

Exacerbated by the fact that for a vector that is too small, we get the expected response.
</blockquote></details>

Done.

I also reordered the tests a bit, hopefully improved clarity as well.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLanRkK4Awa7hOwnb_r:-NLbNlUgBPwT71i2HSHM:b-l28nif) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Check Anzu CI.
</blockquote></details>

Passed.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`common/yaml/yaml_read_archive.h` line 379 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbCIek--PQnRbbsauN:-NLbLHgn1n9gzwFdqbpM:b-s4glz1) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/common/yaml/yaml_read_archive.h#L379)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here is an example error message when the array is too big (taken from the rgba unit test):

`YAML node of type Mapping (with size 1 and keys {rgba}) has too many array elements (5); the maximum size is 4 in the entry for Eigen::Matrix<double,-1,1,0,4,1> rgba.`

So two questions:

(1) Is the message on its own a good one?

(2) Should the source code here somehow be made more clear about what's going on?
</blockquote></details>

When we visit array, we would return something like:

```
YAML node of type Mapping (with size 1 and keys {foo") has
7-size entry (wanted 5-size) entry for Sometype bar.
```
(I think.) The flow into the word entry is clunky. I imagine it could be the same for vector.

```
YAML node of type Mapping (with size 1 and keys {rgba}) has
5-size entry (wanted up to 4-size) entry for
Eigen::Matrix<double,-1,1,0,4,1> rgba.
```
That doesn't flow any better than for array, but doesn't seem to flow any worse either.

I suspect that the `ReportError` function wasn't optimized for discussing array elements and we're running into that.

So, regarding the current state:

1. I believe that the resulting message given the current code is superior to what I understand we'd get for a malformed array. (So, making max-size vector match array in some sense would be a step backwards in message quality). 
2. Tweaking error reporting so that it flows better across the various types seems reasonably outside the scope of this PR.
3. The simplest solution is a note at this site indicating why it looks aberrant and that's ok.
___
*[`geometry/rgba.h` line 105 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbCp0677O3l-rMkker:-NLbKmUr9CvRMXmiHoIZ:b-4z13qv) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/geometry/rgba.h#L105)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hopefully this rewrite is more clear?
</blockquote></details>

Works for me.  Thanks.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`common/yaml/yaml_read_archive.h` line 379 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbCIek--PQnRbbsauN:-NLbQ-X58Q-sirwCcOUG:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/70f8512fb0d37bf17ece7546e530481c37bcd1bb/common/yaml/yaml_read_archive.h#L379)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

When we visit array, we would return something like:

```
YAML node of type Mapping (with size 1 and keys {foo") has
7-size entry (wanted 5-size) entry for Sometype bar.
```
(I think.) The flow into the word entry is clunky. I imagine it could be the same for vector.

```
YAML node of type Mapping (with size 1 and keys {rgba}) has
5-size entry (wanted up to 4-size) entry for
Eigen::Matrix<double,-1,1,0,4,1> rgba.
```
That doesn't flow any better than for array, but doesn't seem to flow any worse either.

I suspect that the `ReportError` function wasn't optimized for discussing array elements and we're running into that.

So, regarding the current state:

1. I believe that the resulting message given the current code is superior to what I understand we'd get for a malformed array. (So, making max-size vector match array in some sense would be a step backwards in message quality). 
2. Tweaking error reporting so that it flows better across the various types seems reasonably outside the scope of this PR.
3. The simplest solution is a note at this site indicating why it looks aberrant and that's ok.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with two nits
- concern about non-parity bindings with C++ in terms of `.set(rgba=...)` and `.rgba = property()` vs. `.rgba()`.
- Making `value_` a type of `Vec3or4` seems not as good as `Vector4 value_` and `Vec3or4 temp`.

Will not block if y'all think it's better this way, though.

> Reviewed 3 of 7 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-:-NLbvJa5DjiP63MNcVF7:b-cdmzu7)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`geometry/rgba.h` line 109 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbvaNV2SFY8kJ5xi1a:-NLbvaNW8VmnlXX1d-VS:bic7hb4) ([raw file](https://github.com/RobotLocomotion/drake/blob/9d5f0e4849f703fef2b116ed558bcaef3b1ecea8/geometry/rgba.h#L109)):*
> ```objc
>   // We'll also set the template argument `MaxRowsAtCompileTime == 4` so that
>   // our data is stored inline as part of this object, instead of on the heap.
>   Eigen::Matrix<double, Eigen::Dynamic, 1, 0, 4, 1> value_ =
> ```

nit Unclear why we want to the direct storage to be `Vec3or4`-ish and then add in the "canoicalizing" / "re-validating" step.

Why not use a direct temporary in serialization? e.g.
```
Vec3or4 temp = value_;
a->Visit(MakeNameValue("rgba", &temp));
value_.setZero();
set(temp);
```
___
*[`bindings/pydrake/geometry_py_common.cc` line 342 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbuxq40dTe5P9firU7:-NLbuxq40dTe5P9firU8:b-w9ize4) ([raw file](https://github.com/RobotLocomotion/drake/blob/9d5f0e4849f703fef2b116ed558bcaef3b1ecea8/bindings/pydrake/geometry_py_common.cc#L342)):*
> ```cpp
>         });
>     DefAttributesUsingSerialize(&cls);
>     cls.def_property("rgba",
> ```

nit Not sure if I've seen a more Pythonic approach used in lieu of the exact same C++ API. I believe I've seen it used in addition to, instead.

Consider explicitly binding `.set(rgba=...)`?
Additionally, concerned that this is not the exact same as C++ `my_color.rgba()`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`geometry/rgba.h` line 109 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbvaNV2SFY8kJ5xi1a:-NLby5Zx7QHnPu1fN5v9:b4aajpe) ([raw file](https://github.com/RobotLocomotion/drake/blob/9d5f0e4849f703fef2b116ed558bcaef3b1ecea8/geometry/rgba.h#L109)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why we want to the direct storage to be `Vec3or4`-ish and then add in the "canoicalizing" / "re-validating" step.

Why not use a direct temporary in serialization? e.g.
```
Vec3or4 temp = value_;
a->Visit(MakeNameValue("rgba", &temp));
value_.setZero();
set(temp);
```
</blockquote></details>

The `DefAttributesUsingSerialize` is incompatible with temporaries, it must only ever use member fields.  (I'll add a comment here.)
___
*[`bindings/pydrake/geometry_py_common.cc` line 342 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbuxq40dTe5P9firU7:-NLbyIbs9v9oBJLszZVb:b-94aqxw) ([raw file](https://github.com/RobotLocomotion/drake/blob/9d5f0e4849f703fef2b116ed558bcaef3b1ecea8/bindings/pydrake/geometry_py_common.cc#L342)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Not sure if I've seen a more Pythonic approach used in lieu of the exact same C++ API. I believe I've seen it used in addition to, instead.

Consider explicitly binding `.set(rgba=...)`?
Additionally, concerned that this is not the exact same as C++ `my_color.rgba()`.
</blockquote></details>

I guess I can bind the `set` overload.

But for deserialization we _need_ to have the settable property, that's how deserialization works (using setattr).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`geometry/rgba.h` line 109 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbvaNV2SFY8kJ5xi1a:-NLc-DIA4g7o7rjSzCJ_:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9d5f0e4849f703fef2b116ed558bcaef3b1ecea8/geometry/rgba.h#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `DefAttributesUsingSerialize` is incompatible with temporaries, it must only ever use member fields.  (I'll add a comment here.)
</blockquote></details>

Done.
___
*[`bindings/pydrake/geometry_py_common.cc` line 342 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLbuxq40dTe5P9firU7:-NLc-Eu98zmFVSEpX41F:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9d5f0e4849f703fef2b116ed558bcaef3b1ecea8/bindings/pydrake/geometry_py_common.cc#L342)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I guess I can bind the `set` overload.

But for deserialization we _need_ to have the settable property, that's how deserialization works (using setattr).
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18571)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`geometry/rgba.h` line 91 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/18571#-NLc2_TFABoMrbvTplfV:-NLc2_TFABoMrbvTplfW:bwpziyt) ([raw file](https://github.com/RobotLocomotion/drake/blob/cc25d3791253e5010b65df6b01123d54687696db/geometry/rgba.h#L91)):*
> ```objc
>     //
>     // N.B. For the Python binding use of DefAttributesUsingSerialize, this
>     // must refer a member field; we cannot use a stack temporary here.
> ```

nit:  "...must refer __*to*__ a member field...

**Comment by EricCousineau-TRI** [comment]
Ah, didn't realize that about serialization + property/attr. Thanks!
And derp on the temporary setup as well :facepalm:

**Pull request merged**
