### PR TITLE
Upgrade Mosek patch from 10.0.18 to 10.0.46

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19798)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
Do you want me to fix the checksums?  They are all wrong -- they're not even the right number of digits.

**Review by hongkai-dai — COMMENTED** [review]
I incorrectly used `shasum` command hence the number of digits was wrong.

I now used `sha256sum`, but the compilation still complains that the  sha isn't correct. Could you help me with that? Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19798#-:-N___5hq6D-i7M14wLJG:bvti9w0)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Comment by jwnimmer-tri** [comment]
(Aside: be sure to remove the spurious lint whitespace in the file.)

Here's the checksums:

```console
jwnimmer@call-cps:~/Downloads$ wget https://download.mosek.com/stable/10.0.46/mosektools{linux64x86,osx64x86,osxaarch64}.tar.bz2
...
Downloaded: 3 files, 118M in 4.0s (29.3 MB/s)

jwnimmer@call-cps:~/Downloads$ sha256sum mosektools*.tar.bz2
a6862954137493b74f55c0f2745b7f1672e602cfe9cd8974a95feaf9993f06bf  mosektoolslinux64x86.tar.bz2
16885bbee2c1d86e0a3f9d9a2c60bbab1bb88e6f1b843ac1fb8da0c62292344f  mosektoolsosx64x86.tar.bz2
85724bd519d5fe120b4e8d2676b65143b9ce6dce666a07ca4f44ec54727b5ab5  mosektoolsosxaarch64.tar.bz2
```

It looks like the two macOS checkums were right; only the linux was wrong for some reason.

**Review by hongkai-dai — COMMENTED** [review]
Thanks Jeremy.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19798#-:-N_aRVQs-e9N7JA20dp2:bo0c70i)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: pending CI.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19798#-:-N_acEJc-OrocynYp4tB:bwo9p68)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please

**Pull request merged**
