### PR TITLE
Implements a workaround for using contact visualization with drake_visualizer

### PR DESCRIPTION
**Pull request by rcory**
Implements a workaround for using contact visualization with drake's pre-compiled drake_visualizer, which needs to be updated per #7851.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8195)

### CODE REVIEW

**Comment by rcory** [comment]
@jwnimmer-tri  for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8195#-:-L6O5-f-pqWmTAKZRLgi:b-823iol)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8195#-:-L6O5UKxbxiLfqVe4Qsv:bnfp4nl)*

**Comment by rcory** [comment]
+@sammy-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8195#-:-L6O7gveYOWuYkbI1GSg:b-1zm1j3)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8195#-:-L6PFV1WxIEYJT9FZXKY:bnfp4nl)*

**Pull request merged**
