### PR TITLE
[doc] Add release notes v0.39.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
This release might ship as soon as tomorrow, so +@rpoyner-tri for feature review officially, please.

FYI in case you'd like to check on portions related to you \CC @amcastro-tri @DamrongGuoy @EricCousineau-TRI @hongkai-dai @joemasterjohn @sherm1 @mitiguy @rpoyner-tri @sammy-tri @svenevs @xuchenhan-tri.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v0.39.0.md, line 163 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16537#-MvPaCql3jiyPLeck96n:-MvPaCql3jiyPLeck96o:b-lt1is) ([raw file](https://github.com/robotlocomotion/drake/blob/ada4502062cf7ecf1bbdb206f9d05057e0ff0ea5/doc/_release-notes/v0.39.0.md#L163)):*
> ```Markdown
> * drake::math::autoDiffToGradientMatrix ([#15699][_#15699], [#16479][_#16479])
> * drake::math::autoDiffToValueMatrix ([#15699][_#15699], [#16479][_#16479])
> * drake::math::initializeAutoDiffGivenGradientMatrix ([#15699][_#15699]
> ```

missing close paren.

BTW, is it a new practice to ref both the deprecation and removal PRs?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: removals questions

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537#-:-MvPa_8cA9nXCJY7hzIT:b-teerbx)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @sherm1)

___
*[doc/_release-notes/v0.39.0.md, line 163 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16537#-MvPaCql3jiyPLeck96n:-MvPcvrL3cwtn6zhJV7K:b-p9h0kx) ([raw file](https://github.com/robotlocomotion/drake/blob/ada4502062cf7ecf1bbdb206f9d05057e0ff0ea5/doc/_release-notes/v0.39.0.md#L163)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

missing close paren.

BTW, is it a new practice to ref both the deprecation and removal PRs?
</blockquote></details>

Done.

Yes, I have started linking to both the deprecation PR and removal PR; it seemed like a nice bonus for users.

It's actually really easy for me to do, because for the "removal of deprecated" section, I copy-paste portions of the "newly deprecated" section from 3 or 4 releases prior, rather than trying to re-discover the symbol names to list here.  Since I'm copying them anyway, it's easy to keep the number.

I don't know that I'd insist that anyone else do this yet, but I so far, I'm a fan.  More automation would be nice.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: 2 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @rpoyner-tri, and @sherm1)

___
*[doc/_release-notes/v0.39.0.md, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16537#-MvPmPxD80qz5L2X2pFB:-MvPmPxE2Bo7nnNPF-iq:b-mdbhuc) ([raw file](https://github.com/robotlocomotion/drake/blob/2d7b993e4c6dc823fcd3d456f6825f4a96764e03/doc/_release-notes/v0.39.0.md#L63)):*
> ```Markdown
> * Add MultibodyPlant back-pointer into the ContactResults struct ([#16478][_#16478])
> * Add unit inertia calculation for a capsule ([#16357][_#16357])
> * New hydroelastic contact model in progress ([#16365][_#16365], [#16366][_#16366], [#16367][_#16367], [#16374][_#16374], [#16458][_#16458], [#16471][_#16471])
> ```

I wonder whether only PRs are allowed here, or issue is ok too.  The umbrella issue [16040](https://github.com/RobotLocomotion/drake/issues/16040) is solved by these PRs.

I did not label issue 16040 for either release-note yes or release-note no. Should I label it? Sorry for the confusion.

Action item: should we do this?
```
* New hydroelastic contact model in progress ([#16040][_#16040], [#16365][_#16365], [#16366][_#16366], [#16367][_#16367], [#16374][_#16374], [#16458][_#16458], [#16471][_#16471])
```

**Review by DamrongGuoy — COMMENTED** [review]
I've reviewed `hydroelastic contact model` and have one minor question. Yes or no, it looks good to me :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537#-:-MvPoMNY-DbvWRpQO8k-:b-zc5o7l)* status: 2 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @rpoyner-tri, and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @sherm1)

___
*[doc/_release-notes/v0.39.0.md, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16537#-MvPmPxD80qz5L2X2pFB:-MvPoxkSB7UQ4FR1dOI9:b3yb6h6) ([raw file](https://github.com/robotlocomotion/drake/blob/2d7b993e4c6dc823fcd3d456f6825f4a96764e03/doc/_release-notes/v0.39.0.md#L63)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I wonder whether only PRs are allowed here, or issue is ok too.  The umbrella issue [16040](https://github.com/RobotLocomotion/drake/issues/16040) is solved by these PRs.

I did not label issue 16040 for either release-note yes or release-note no. Should I label it? Sorry for the confusion.

Action item: should we do this?
```
* New hydroelastic contact model in progress ([#16040][_#16040], [#16365][_#16365], [#16366][_#16366], [#16367][_#16367], [#16374][_#16374], [#16458][_#16458], [#16471][_#16471])
```

</blockquote></details>

Usually we don't link to issue numbers (and the release notes labels have no effect when applied to issues) because the user can click through from the PR number to the linked issue number easily.  However, for something like this hydro point, I'm happy to also link to the issue number.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @sherm1)

___
*[doc/_release-notes/v0.39.0.md, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16537#-MvPmPxD80qz5L2X2pFB:-MvPsAvR8UHhlUfL6Wz1:b-3rnfvy) ([raw file](https://github.com/robotlocomotion/drake/blob/2d7b993e4c6dc823fcd3d456f6825f4a96764e03/doc/_release-notes/v0.39.0.md#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Usually we don't link to issue numbers (and the release notes labels have no effect when applied to issues) because the user can click through from the PR number to the linked issue number easily.  However, for something like this hydro point, I'm happy to also link to the issue number.
</blockquote></details>

Thank you for the explanation!  I agree PRs already point to the issue.  That is true.

Set to Satisfied.  Thank you for adding it!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v0.39.0.md, line 142 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16537#-MvPyMiY04aixokmqyPC:-MvPyMiY04aixokmqyPD:b9eh6rk) ([raw file](https://github.com/robotlocomotion/drake/blob/06d39687dfb691188451859dc906fdd529cafb7a/doc/_release-notes/v0.39.0.md#L142)):*
FYI it may be worth calling to attention [some summary of this slack #build thread](https://drakedevelopers.slack.com/archives/C0KDGF4V9/p1643734806963559).  Something like

> * Upgrade vtk to release 9.0 ([#16132][_#16132], [#16419][_#16419])
>     * As a reminder, linking drake-visualizer with drake and/or pydrake in the same process is not supported.  As of this update, doing so will result in a segfault.

My recollection is you said this was not supported for quite some time, but it may be helpful to call it out directly?  Nonblocking because I don't know how long this has been forbidden or how appropriate / relevant this is.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537#-:-MvPap7m0e7_B1zCe8HP:bnfp4nl)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[doc/_release-notes/v0.39.0.md, line 142 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16537#-MvPyMiY04aixokmqyPC:-MvQ9AS870-9QM5hBYLu:b-80ti91) ([raw file](https://github.com/robotlocomotion/drake/blob/06d39687dfb691188451859dc906fdd529cafb7a/doc/_release-notes/v0.39.0.md#L142)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI it may be worth calling to attention [some summary of this slack #build thread](https://drakedevelopers.slack.com/archives/C0KDGF4V9/p1643734806963559).  Something like

> * Upgrade vtk to release 9.0 ([#16132][_#16132], [#16419][_#16419])
>     * As a reminder, linking drake-visualizer with drake and/or pydrake in the same process is not supported.  As of this update, doing so will result in a segfault.

My recollection is you said this was not supported for quite some time, but it may be helpful to call it out directly?  Nonblocking because I don't know how long this has been forbidden or how appropriate / relevant this is.
</blockquote></details>

Done (up top, with the announcements).

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy, @jwnimmer-tri, and @rpoyner-tri)

___
*[doc/_release-notes/v0.39.0.md, line 3 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16537#-MvQOWfE-4Xw2HZ-e4IP:-MvQOWfE-4Xw2HZ-e4IQ:b-am2jkn) ([raw file](https://github.com/robotlocomotion/drake/blob/f57d2beeb0a5563261746279c932feaaf78188b5/doc/_release-notes/v0.39.0.md#L3)):*
> ```Markdown
> ---
> title: Drake v0.39.0
> released: YYYY-MM-DD
> ```

Working

Needs date markers (and related) finalized per the playbook, once we choose a release date to ship.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
-(status: do not merge) 

The nightlies are clean; my plan is to release today.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16537#-:-MvU-HjHEmuXQVFRjJST:b-3yfnef)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[doc/_release-notes/v0.39.0.md, line 3 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16537#-MvQOWfE-4Xw2HZ-e4IP:-MvU-JAV1dKTX6efoDzt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f57d2beeb0a5563261746279c932feaaf78188b5/doc/_release-notes/v0.39.0.md#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs date markers (and related) finalized per the playbook, once we choose a release date to ship.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail we're ready for the next steps here:
tag docker images
upload the releases to S3
Debian packages

Details:
Binary date: 20220209
Commit SHA: c95ac12807375c61d9426802570a9fc635e377c1
Release tag: v0.39.0

**Comment by BetsyMcPhail** [comment]
Docker images and S3 are complete. See [slack conversation](https://drakedevelopers.slack.com/archives/C01JSGRR1QS/p1644957428407759) for a discussion on apt packages.

**Comment by BetsyMcPhail** [comment]
Apt packages are also ready!

**Pull request merged**
