### PR TITLE
Remove Boost from drake.cps

### LINKED ISSUE #7783: Boost should not be referenced by drake.cps
Since `yaml-cpp` headers are no longer public, we do not need the workaround.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #7783.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7804)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab  please

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7804#-:-L3FLNbA1UUvLUXvJ882:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7804#-:-L3FPLjtej5G6gwFYBgo:bnfp4nl)*

**Pull request merged**
