### PR TITLE
[multibody] Fix typo in CalcHydroelasticContactForces

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This was most certainly a bug. I am still scratching my head figuring out how to write a test to demonstrate the fix.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: do not merge) +(status: do not review) +@joemasterjohn for regression test advice.
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-:-Nc8boXqD5BAqatPva-1:bwft4s2)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-Nc8mOGy7njczdejKrcO:-Nc8mOGy7njczdejKrcP:b-sed3dv) (no related file):*
FWIW, I always kinda hate these runs of code that do the same exact step on each of a pair of objects. In retrospect, it would have maybe been better to factor out some error-prone boilerplate. Perhaps like this?
```
diff --git a/multibody/plant/multibody_plant.cc b/multibody/plant/multibody_plant.cc
index a0c12dbccb..729d3d2493 100644
--- a/multibody/plant/multibody_plant.cc
+++ b/multibody/plant/multibody_plant.cc
@@ -1987,28 +1987,23 @@ void MultibodyPlant<T>::CalcHydroelasticContactForces(
     const GeometryId geometryM_id = surface.id_M();
     const GeometryId geometryN_id = surface.id_N();
 
-    const ProximityProperties* propM =
-        inspector.GetProximityProperties(geometryM_id);
-    const ProximityProperties* propN =
-        inspector.GetProximityProperties(geometryN_id);
-    DRAKE_DEMAND(propM != nullptr);
-    DRAKE_DEMAND(propN != nullptr);
-    DRAKE_THROW_UNLESS(propM->HasProperty(geometry::internal::kMaterialGroup,
-                                          geometry::internal::kFriction));
-    DRAKE_THROW_UNLESS(propN->HasProperty(geometry::internal::kMaterialGroup,
-                                          geometry::internal::kFriction));
-
-    const CoulombFriction<double>& geometryM_friction =
-        propM->GetProperty<CoulombFriction<double>>(
-            geometry::internal::kMaterialGroup, geometry::internal::kFriction);
-    const CoulombFriction<double>& geometryN_friction =
-        propN->GetProperty<CoulombFriction<double>>(
-            geometry::internal::kMaterialGroup, geometry::internal::kFriction);
-
+    auto get_friction = [&](auto id) {
+      const ProximityProperties* prop = inspector.GetProximityProperties(id);
+      DRAKE_DEMAND(prop != nullptr);
+      if (!prop->HasProperty(geometry::internal::kMaterialGroup,
+                             geometry::internal::kFriction)) {
+        throw std::logic_error(fmt::format(
+            "geometry id '{}' for contact surface between geometry ids ({},{})"
+            " has no friction property",
+            id, geometryM_id, geometryN_id));
+      }
+      return prop->GetProperty<CoulombFriction<double>>(
+          geometry::internal::kMaterialGroup, geometry::internal::kFriction);
+    };
     // Compute combined friction coefficient.
     const CoulombFriction<double> combined_friction =
-        CalcContactFrictionFromSurfaceProperties(geometryM_friction,
-                                                 geometryN_friction);
+        CalcContactFrictionFromSurfaceProperties(get_friction(geometryM_id),
+                                                 get_friction(geometryN_id));
     const double dynamic_friction = combined_friction.dynamic_friction();
 
     // Get the bodies that the two geometries are affixed to. We'll call these
```
Even with the fancy exception message, the code is shorter, and much less prone to copypasta errors.

___

**Review by joemasterjohn — COMMENTED** [review]
I can write the proper regression test today. Working.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-:-NcNY0jY21PafdVdhfc3:b-uh908j)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

**Review by joemasterjohn — COMMENTED** [review]
Ok I wrote the regression test, you can verify that it fails with the typo and succeeds with the fix. It might be overkill but I'll let +@amcastro-tri decide. I wish I could just look at the combined friction that is passed to the traction calculator, but it's just a temp so I had to work with something like hydroelastic forces or (what I found to be easier) contact forces.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-:-NcP1I544BNLyuWPCvPL:b-ou5py7)* status: 3 unresolved discussions, LGTM missing from assignees joemasterjohn,amcastro-tri, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-Nc8mOGy7njczdejKrcO:-NcP0tOqDIUJIoFuoaEq:byopskc) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

FWIW, I always kinda hate these runs of code that do the same exact step on each of a pair of objects. In retrospect, it would have maybe been better to factor out some error-prone boilerplate. Perhaps like this?
```
diff --git a/multibody/plant/multibody_plant.cc b/multibody/plant/multibody_plant.cc
index a0c12dbccb..729d3d2493 100644
--- a/multibody/plant/multibody_plant.cc
+++ b/multibody/plant/multibody_plant.cc
@@ -1987,28 +1987,23 @@ void MultibodyPlant<T>::CalcHydroelasticContactForces(
     const GeometryId geometryM_id = surface.id_M();
     const GeometryId geometryN_id = surface.id_N();
 
-    const ProximityProperties* propM =
-        inspector.GetProximityProperties(geometryM_id);
-    const ProximityProperties* propN =
-        inspector.GetProximityProperties(geometryN_id);
-    DRAKE_DEMAND(propM != nullptr);
-    DRAKE_DEMAND(propN != nullptr);
-    DRAKE_THROW_UNLESS(propM->HasProperty(geometry::internal::kMaterialGroup,
-                                          geometry::internal::kFriction));
-    DRAKE_THROW_UNLESS(propN->HasProperty(geometry::internal::kMaterialGroup,
-                                          geometry::internal::kFriction));
-
-    const CoulombFriction<double>& geometryM_friction =
-        propM->GetProperty<CoulombFriction<double>>(
-            geometry::internal::kMaterialGroup, geometry::internal::kFriction);
-    const CoulombFriction<double>& geometryN_friction =
-        propN->GetProperty<CoulombFriction<double>>(
-            geometry::internal::kMaterialGroup, geometry::internal::kFriction);
-
+    auto get_friction = [&](auto id) {
+      const ProximityProperties* prop = inspector.GetProximityProperties(id);
+      DRAKE_DEMAND(prop != nullptr);
+      if (!prop->HasProperty(geometry::internal::kMaterialGroup,
+                             geometry::internal::kFriction)) {
+        throw std::logic_error(fmt::format(
+            "geometry id '{}' for contact surface between geometry ids ({},{})"
+            " has no friction property",
+            id, geometryM_id, geometryN_id));
+      }
+      return prop->GetProperty<CoulombFriction<double>>(
+          geometry::internal::kMaterialGroup, geometry::internal::kFriction);
+    };
     // Compute combined friction coefficient.
     const CoulombFriction<double> combined_friction =
-        CalcContactFrictionFromSurfaceProperties(geometryM_friction,
-                                                 geometryN_friction);
+        CalcContactFrictionFromSurfaceProperties(get_friction(geometryM_id),
+                                                 get_friction(geometryN_id));
     const double dynamic_friction = combined_friction.dynamic_friction();
 
     // Get the bodies that the two geometries are affixed to. We'll call these
```
Even with the fancy exception message, the code is shorter, and much less prone to copypasta errors.
</blockquote></details>

I believe this boiler plate "get identical quantites for two bodies/geometries" is not unique to this piece of code and can be found around most of the hydro/point contact code. Perhaps a cleanup of this pattern is due.

___
___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 91 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcP-l3u0dSM_LAnp6ud:-NcP-l3u0dSM_LAnp6ue:be6vfqi) ([raw file](https://github.com/RobotLocomotion/drake/blob/488691af22b4271563b616c91a31d7cefbeddeeb/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L91)):*
> ```cpp
>     // Create a context for this system:
>     diagram_context_ = diagram_->CreateDefaultContext();
>     diagram_context_->DisableCaching();
> ```

Per #20014, we are missing some input port dependencies on some of plant's cache entries. In this case, the query object input port which proper dependency on will trigger recomputation of the hydroelastic forces when proximity properties change. Since this is wrong right now, I disabled caching here in order to obtain different contact results as a result of changing the friction coefficient. Trying to dig down the rabbit hole of which dependencies are missing might be hard to do in this PR and would also block this important fix from going in, so perhaps leaving this cache disabling in now with a "TODO(#20014): Enable caching when input port dependencies are fixed."?
___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 378 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcP1wugCyjpetd2S0TT:-NcP1wugCyjpetd2S0TU:bdmhhff) ([raw file](https://github.com/RobotLocomotion/drake/blob/488691af22b4271563b616c91a31d7cefbeddeeb/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L378)):*
> ```cpp
>     ASSERT_EQ(old_contact_info.quadrature_point_data().size(),
>               new_contact_info.quadrature_point_data().size());
>     for (int j = 0; j < ssize(new_contact_info.quadrature_point_data()); ++j) {
> ```

We probably only have to look at a single quadrature point, but I wrote it testing all of them just as a sanity check.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022)* status: 3 unresolved discussions, LGTM missing from assignees amcastro-tri,joemasterjohn, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-Nc8mOGy7njczdejKrcO:-NcP9DI98vJMLme9ZU0l:b7qevfl) (no related file):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I believe this boiler plate "get identical quantites for two bodies/geometries" is not unique to this piece of code and can be found around most of the hydro/point contact code. Perhaps a cleanup of this pattern is due.
</blockquote></details>

I'd buy it, but I don't want to necessarily do it :) . Would you be willing to pick this up?

___
___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 91 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcP-l3u0dSM_LAnp6ud:-NcP8SDKENHTNB--JLtQ:bps73zh) ([raw file](https://github.com/RobotLocomotion/drake/blob/488691af22b4271563b616c91a31d7cefbeddeeb/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L91)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Per #20014, we are missing some input port dependencies on some of plant's cache entries. In this case, the query object input port which proper dependency on will trigger recomputation of the hydroelastic forces when proximity properties change. Since this is wrong right now, I disabled caching here in order to obtain different contact results as a result of changing the friction coefficient. Trying to dig down the rabbit hole of which dependencies are missing might be hard to do in this PR and would also block this important fix from going in, so perhaps leaving this cache disabling in now with a "TODO(#20014): Enable caching when input port dependencies are fixed."?
</blockquote></details>

I'd buy covering those issues with a TODO in this PR.
___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 378 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcP1wugCyjpetd2S0TT:-NcP9QO12oBBKeDTjybs:b-bk5ip0) ([raw file](https://github.com/RobotLocomotion/drake/blob/488691af22b4271563b616c91a31d7cefbeddeeb/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L378)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

We probably only have to look at a single quadrature point, but I wrote it testing all of them just as a sanity check.
</blockquote></details>

Works for me.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022)* status: 4 unresolved discussions, LGTM missing from assignees amcastro-tri,joemasterjohn, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcP9Zh8-YzPvBVFv5hA:-NcP9Zh8-YzPvBVFv5hB:b-4dizlh) (no related file):*
Thanks for the test. I will experiment with it locally to convince myself of what it covers -- like a lot of MbP tests, it's a bit hard to tell what internals are reached.

In particular, I intend to try both the original typo (too many M's) and also a mutation in the other direction (too many N's).

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022)* status: 3 unresolved discussions, LGTM missing from assignees amcastro-tri,joemasterjohn, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcP9Zh8-YzPvBVFv5hA:-NcPGNINAEFXyQNIDv--:be5wz9l) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Thanks for the test. I will experiment with it locally to convince myself of what it covers -- like a lot of MbP tests, it's a bit hard to tell what internals are reached.

In particular, I intend to try both the original typo (too many M's) and also a mutation in the other direction (too many N's).
</blockquote></details>

I did the tests described above, and both mutations (surplus M's, surplus N's) fail. I'm satisfied, but of course we want review from a subject matter expert as well.

___

**Review by rpoyner-tri — COMMENTED** [review]
Maybe not clear from above, @amcastro-tri can you feature review this?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-:-NcShlMM6BqHzNo21Ap1:b-ay3b6i)* status: 3 unresolved discussions, LGTM missing from assignees amcastro-tri,joemasterjohn, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
I will rebase this, squash, and add some comments suggested by Joe's discussions below, and add co-author credit.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-:-NcSiQ_G0ADodNsyhU2O:bqnnf5e)* status: 2 unresolved discussions, LGTM missing from assignees amcastro-tri,joemasterjohn, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022)* status: 1 unresolved discussion, LGTM missing from assignees amcastro-tri,joemasterjohn, needs platform reviewer assigned

___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 378 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcP1wugCyjpetd2S0TT:-NcSvNlWD4Z1kHxdkTkL:b-gsg2fu) ([raw file](https://github.com/RobotLocomotion/drake/blob/488691af22b4271563b616c91a31d7cefbeddeeb/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L378)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Works for me.
</blockquote></details>

I guess since the box is rigid the contact surface is planar and we can get away with just look at the tangential (xy) component of full accumulate body force `F_BBo_W` from `EvalHydroelasticContactForces()`. WDYT, @amcastro-tri ?

**Review by amcastro-tri — COMMENTED** [review]
I love the test, thanks @joemasterjohn.
Thanks @rpoyner-tri for spotting this!
:lgtm_strong: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-:-NcTdc4p-HNSBKRQeKP9:be0przx)* status: 4 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned

___
*[`multibody/plant/multibody_plant.cc` line 1993 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcTav742J_iNl-XIdiR:-NcTav742J_iNl-XIdiS:b-qnsd7u) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cd073169e7774b4861582739f40778c28fd1de6/multibody/plant/multibody_plant.cc#L1993)):*
> ```cpp
>         inspector.GetProximityProperties(geometryM_id);
>     const ProximityProperties* propN =
>         inspector.GetProximityProperties(geometryM_id);
> ```

this is amazing! thank you for finding this @rpoyner-tri!
___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 91 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcP-l3u0dSM_LAnp6ud:-NcTbSNv62997tAFI9OU:b-84ugn6) ([raw file](https://github.com/RobotLocomotion/drake/blob/488691af22b4271563b616c91a31d7cefbeddeeb/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L91)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'd buy covering those issues with a TODO in this PR.
</blockquote></details>

@joemasterjohn , please add a summary of your observations as a comment in #20014. And, if you do happen to know the fix, please also document and/or advise there. I can follow up with a PR that fixes this problem and removes this TODO.
___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 378 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcP1wugCyjpetd2S0TT:-NcTdF4M4QY3OKv_tKJR:bwttjdy) ([raw file](https://github.com/RobotLocomotion/drake/blob/488691af22b4271563b616c91a31d7cefbeddeeb/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L378)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I guess since the box is rigid the contact surface is planar and we can get away with just look at the tangential (xy) component of full accumulate body force `F_BBo_W` from `EvalHydroelasticContactForces()`. WDYT, @amcastro-tri ?
</blockquote></details>

I think this is great as-is. 
___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 351 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcTcRQfDMXmEndQuIWh:-NcTcRQfDMXmEndQuIWi:b-fklmld) ([raw file](https://github.com/RobotLocomotion/drake/blob/899198988368181d204f54203e398f2b71bc0707/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L351)):*
> ```cpp
>           .template Eval<ContactResults<double>>(*plant_context_);
>   // Make a deep copy of the old contact results.
>   const ContactResults<double> old_contact_results(contact_results);
> ```

nit, couldn't just we eval into a copy? (i.e. remove `&`?)
___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 360 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcTcd-EE4ED5Kk9CwKR:-NcTcd-FCiseDJ1-lz7O:b-3w7pey) ([raw file](https://github.com/RobotLocomotion/drake/blob/899198988368181d204f54203e398f2b71bc0707/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L360)):*
> ```cpp
>   const CoulombFriction<double> mu_combined =
>       CalcContactFrictionFromSurfaceProperties(mu_box, mu_sphere);
>   ProximityProperties new_props(*old_props);
> ```

nit, maybe assert `old_propos` is not nullptr?

**Review by joemasterjohn — COMMENTED** [review]
Thanks @amcastro-tri! +@jwnimmer-tri for platform review, please. Also, I'm pretty sure this is technically a breaking change and should be marked as so?

> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-:-NcTmGHd9FFVpcu5VtvI:bhkkzfy)* status: 2 unresolved discussions, LGTM missing from assignees joemasterjohn,jwnimmer-tri(platform)

___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 351 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcTcRQfDMXmEndQuIWh:-NcTl47KBbxyZQJQlUw0:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/899198988368181d204f54203e398f2b71bc0707/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L351)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, couldn't just we eval into a copy? (i.e. remove `&`?)
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Also, I'm pretty sure this is technically a breaking change and should be marked as so?

If the change is "MultibodyPlant now meets its documented specification", that [isn't a breaking change](https://drake.mit.edu/stable.html#behavioral-changes).  It's just a [space bar heater](https://xkcd.com/1172/).  You're still welcome to add whatever helpful information you want to the release notes (commit message) to help inform users of anything you think is important, but it doesn't seem like a violation of stable API to me.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-:-NcTnnhz08UgQBm_b6Sh:b-fdg2wg)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn

___
*[`multibody/plant/test/multibody_plant_hydroelastic_test.cc` line 360 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-NcTcd-EE4ED5Kk9CwKR:-NcTokziBrrhBZ6z0Mrm:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/899198988368181d204f54203e398f2b71bc0707/multibody/plant/test/multibody_plant_hydroelastic_test.cc#L360)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, maybe assert `old_propos` is not nullptr?
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
How is it a breaking change?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20022#-:-NcToxRzAP_zikvWSaQH:ba81zvp)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri

**Comment by jwnimmer-tri** [comment]
Ready to merge now (once CI passes).  I'll let y'all do the merge, in case you want to tweak the commit message.

**Pull request merged**
