### PR TITLE
initial bindings for pendulum example

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7766)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for feature review, please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-:-L2wZihfX67b-gDxAKpj:b-di4bjk)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/examples/BUILD.bazel, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L2zkgW2XQMi953yv-2v:-L2ztSJ2Ocslx4uyuUM4:b-xexrx9) ([raw file](https://github.com/robotlocomotion/drake/blob/59c9f29cd87881cb69af60fc49d6f1139ddef826/bindings/pydrake/examples/BUILD.bazel#L36)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW The comment about `all.py` may not apply here - should it be removed?
</blockquote></details>

Done.  Is that what you meant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[bindings/pydrake/examples/BUILD.bazel, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L2zkgW2XQMi953yv-2v:-L2zvxQy3gf7YnsF9ArE:bb7867m) ([raw file](https://github.com/robotlocomotion/drake/blob/59c9f29cd87881cb69af60fc49d6f1139ddef826/bindings/pydrake/examples/BUILD.bazel#L36)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  Is that what you meant?
</blockquote></details>

Yup!

---

*[bindings/pydrake/examples/BUILD.bazel, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L2zw5XDGspL1l1WC4Kn:-L2zw5XDGspL1l1WC4Ko:b1unbjy) ([raw file](https://github.com/robotlocomotion/drake/blob/d843b619d729af2889521a29abcbfeaa1c0eb10b/bindings/pydrake/examples/BUILD.bazel#L79)):*
> ```Python
>     deps = [
>         ":pendulum_py",
>         "//drake/bindings/pydrake/systems:systems",
> ```

BTW Is the `:systems` add here redundant?

---

*[bindings/pydrake/examples/test/pendulum_test.py, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L2zwB1yBamGmadyb0wn:-L2zwB1yBamGmadyb0wo:b-mezzwr) ([raw file](https://github.com/robotlocomotion/drake/blob/d843b619d729af2889521a29abcbfeaa1c0eb10b/bindings/pydrake/examples/test/pendulum_test.py#L47)):*
> ```Python
>         self.assertFalse((state == initial_state).all())
>         
>         
> ```

Whitespace and comments from WIP commit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766)*

**Comment by RussTedrake** [comment]
doh.  i just force-pushed some old code and blew away some changes.  will push my clean copy from home tonight.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-:-L3-0tRj20zeLB7RXFbl:b-n8mjaw)*

**Comment by RussTedrake** [comment]
ok.  fixed now.  ptal?

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/examples/BUILD.bazel, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L2zw5XDGspL1l1WC4Kn:-L30TAKG6g4NN7dlF48T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d843b619d729af2889521a29abcbfeaa1c0eb10b/bindings/pydrake/examples/BUILD.bazel#L79)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Is the `:systems` add here redundant?
</blockquote></details>

Done.

---

*[bindings/pydrake/examples/test/pendulum_test.py, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L2zwB1yBamGmadyb0wn:-L30Up3QRhJq7eJcOFzs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d843b619d729af2889521a29abcbfeaa1c0eb10b/bindings/pydrake/examples/test/pendulum_test.py#L47)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Whitespace and comments from WIP commit?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-:-L30UaPoMdG_FBbjPvRU:bq7lie7)*

**Comment by RussTedrake** [comment]
+@ggould-tri for platform review.

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-:-L30uSu4aTf2E7VpPUg8:b-8qo47q)*

**Comment by ggould-tri** [comment]
:lgtm:; one state access style question below.

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/examples/test/pendulum_test.py, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L33ST2au5gE6sZ9ouF8:-L33ST2au5gE6sZ9ouF9:bbp9zs) ([raw file](https://github.com/robotlocomotion/drake/blob/6f45d056932f937e69f40314d761f2700f97b207/bindings/pydrake/examples/test/pendulum_test.py#L37)):*
> ```Python
>         simulator.Initialize()
>         state = simulator.get_mutable_context().get_mutable_state()\
>                          .get_mutable_continuous_state().get_mutable_vector()
> ```

Given that people will frequently copy-paste from example code, is this the state access pattern we want to encourage?  It seems like if more than one of your diagram's systems has state, this will be very obscure.  Extracting the pendulum state in particular would be clearer, even if in this example it is unnecessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-:-L33SnrzNB7Ho7xwPf0l:bbvxw4r)*

**Comment by RussTedrake** [comment]
Completely agree.  This was a function of the systems bindings that were in place so far.  Cleanup is a priority for me and will come in follow-up PRs.  (No way i want state access like this in my inline textbook examples :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-:-L33_R3srM-jBknQIM5U:b-l7pa0p)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/examples/test/pendulum_test.py, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L33ST2au5gE6sZ9ouF8:-L33_uw6d9ocsrBUjHjL:bo2kf5g) ([raw file](https://github.com/robotlocomotion/drake/blob/6f45d056932f937e69f40314d761f2700f97b207/bindings/pydrake/examples/test/pendulum_test.py#L37)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Given that people will frequently copy-paste from example code, is this the state access pattern we want to encourage?  It seems like if more than one of your diagram's systems has state, this will be very obscure.  Extracting the pendulum state in particular would be clearer, even if in this example it is unnecessary.
</blockquote></details>

See comment above.  Cleanup coming soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/examples/test/pendulum_test.py, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L33ST2au5gE6sZ9ouF8:-L33aIM0LnXGi6FKTGQA:b-5xw33g) ([raw file](https://github.com/robotlocomotion/drake/blob/6f45d056932f937e69f40314d761f2700f97b207/bindings/pydrake/examples/test/pendulum_test.py#L37)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

See comment above.  Cleanup coming soon.
</blockquote></details>

Can you put in a TODO comment for now?  If the cleanup gets missed or delayed, it would be good to have a breadcrumb.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/examples/test/pendulum_test.py, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L33ST2au5gE6sZ9ouF8:-L33cChqR8M3jXu8Nky5:bl39r8h) ([raw file](https://github.com/robotlocomotion/drake/blob/6f45d056932f937e69f40314d761f2700f97b207/bindings/pydrake/examples/test/pendulum_test.py#L37)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Can you put in a TODO comment for now?  If the cleanup gets missed or delayed, it would be good to have a breadcrumb.
</blockquote></details>

FYI. With MBT code we've been leaning towards an API  provided by the system like the one [here](https://github.com/RobotLocomotion/drake/blob/master/examples/multibody/pendulum/passive_simulation.cc#L113). So that reads `pendulum.SetAngle(&pendulum_context, M_PI / 3.0);`. I believe that would allow future uses where setting the state in this case could depend on system parameters or even cached computations. If we fiddle with the state by hand as in this example we might limit these future extensions. Just a thought, mainly looking for your feedback @russtedrake given our conversations on using MBT for your class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/examples/test/pendulum_test.py, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L33ST2au5gE6sZ9ouF8:-L33wvvh5xSdyqXSFLh9:b-uafec5) ([raw file](https://github.com/robotlocomotion/drake/blob/6f45d056932f937e69f40314d761f2700f97b207/bindings/pydrake/examples/test/pendulum_test.py#L37)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

FYI. With MBT code we've been leaning towards an API  provided by the system like the one [here](https://github.com/RobotLocomotion/drake/blob/master/examples/multibody/pendulum/passive_simulation.cc#L113). So that reads `pendulum.SetAngle(&pendulum_context, M_PI / 3.0);`. I believe that would allow future uses where setting the state in this case could depend on system parameters or even cached computations. If we fiddle with the state by hand as in this example we might limit these future extensions. Just a thought, mainly looking for your feedback @russtedrake given our conversations on using MBT for your class.
</blockquote></details>

If we connectivity information in each System locally, could we simplify this API further and have a system resolve it's context from *any* parent context (and avoid the need to call `Diagram::GetSubSystemContext<>`)?
This seems like it would also drastically simplify access (such that something nested deep (say 3 levels) does not have to go through a whole slew of manually changed `Get*Context()` calls.

(I'm not sure what information is actually stored, but this is my impression when discussing Systems Python bindings, and how to handle stale pointers, which was part of the influence for using `keep_alive` versus something more conservative.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/examples/test/pendulum_test.py, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L33ST2au5gE6sZ9ouF8:-L34IzFD7vaKbNSMxkIS:b-rsqu3b) ([raw file](https://github.com/robotlocomotion/drake/blob/6f45d056932f937e69f40314d761f2700f97b207/bindings/pydrake/examples/test/pendulum_test.py#L37)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

If we connectivity information in each System locally, could we simplify this API further and have a system resolve it's context from *any* parent context (and avoid the need to call `Diagram::GetSubSystemContext<>`)?
This seems like it would also drastically simplify access (such that something nested deep (say 3 levels) does not have to go through a whole slew of manually changed `Get*Context()` calls.

(I'm not sure what information is actually stored, but this is my impression when discussing Systems Python bindings, and how to handle stale pointers, which was part of the influence for using `keep_alive` versus something more conservative.)
</blockquote></details>

We intentionally restricted leaf systems to get only their own leaf contexts to provide a clear message and near-bulletproof guarantee that a leaf can access and modify only its own context. The intervention of a diagram is required to extract the appropriate leaf context from the diagram context. I still think that is a good idea, even if it requires some extra API calls. I think it aids clarity of code & thought.

OTOH all those chained get_mutables are awful and unnecessary!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766)*

**Comment by RussTedrake** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/examples/test/pendulum_test.py, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L33ST2au5gE6sZ9ouF8:-L351ymVuus-C7IKLzoY:b-j026pr) ([raw file](https://github.com/robotlocomotion/drake/blob/6f45d056932f937e69f40314d761f2700f97b207/bindings/pydrake/examples/test/pendulum_test.py#L37)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there a way that an explicit API entrypoint could be introduced, something like `ResolveSubContext(parent_context)`, that will let the system rifle through whatever levels needed, to localize the information needed to get its own context from the parent, something that's less strict?
Some disclaimers could be made to say that this code should only be used *external* to the Systems framework, as sugar.

For the chain of `get_mutable_*`, totally agree! That, I could see as satisfied by Alejandro's example.
(Sorry if I'm conflating state type access with context hierarchy access, just chimed in for general convenience.)

One minor note: `pybind` has no mechanisms to enforce `const` access, as that's not something present in Python, so this could be changed to `simulator.get_context().get_state().get_continuous_state().get_vector()` (caveat: numpy does have enforcements for const-ness, but `state` is a `BasicVector`).
</blockquote></details>

great discussion.  i've added the TODO.  can i get an ok?  :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766)*

**Comment by RussTedrake** [comment]
*[bindings/pydrake/examples/test/pendulum_test.py, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7766#-L33ST2au5gE6sZ9ouF8:-L37g1p6vDIbe6eMWMvN:b-rhzre1) ([raw file](https://github.com/robotlocomotion/drake/blob/6f45d056932f937e69f40314d761f2700f97b207/bindings/pydrake/examples/test/pendulum_test.py#L37)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

great discussion.  i've added the TODO.  can i get an ok?  :-)
</blockquote></details>

@amcastro-tri -- regarding your `pendulum.SetAngle()` comment/question... here are a few quick thoughts.  
- this is essentially the API that we use already for named vectors (that are autogenerated from the python scripts).  so we should make sure we match the existing format.  
- the only(?) advantage of putting it at the system level (instead of the vector level), I guess, is that the system knows whether to re-direct to continuous state or discrete state.  but that is indeed valuable information.  the disadvantage is that it increases the burden on the system author, so I think it definitely makes sense for MBP, but perhaps not for every system?

@ericcousineau-tri -- I'm torn about walking the line with `const` access.  I like the idea of the python code being simpler to read, but are we playing with fire?  And even if python can't enforce it, how do the actual pybind bindings get away with writing to a const reference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7766)*

**Comment by amcastro-tri** [comment]
@RussTedrake. The reason I prefer the system level API is because by passing the context you have access to caching and also to parameters. The autgen vectors assume you can actually place this info in an array format. Consider the case in which the joint actually was model as a constraint for a "loop-joint". There is no angle in the state vector in that case but it is the result of a computation. Of course, in the general case we could copy the output (as we already do by the way) to a named vector with a set of useful numbers to the user, say joint angles. This is what I am doing for the energy shaping example. I'll send you a link when I push it so you can see it.

**Pull request merged**
