### PR TITLE
Fix urdf transmissions

### PR DESCRIPTION
**Pull request by steinachim**
After a change in the URDF specification, the transmission type is no longer an attribute but a child of the `Transmission` node. This leads to crashes with newer URDF models (see http://wiki.ros.org/urdf/XML/Transmission).

Now both variations should be supported.

### CODE REVIEW

**Comment by RussTedrake** [comment]
excellent.  code looks good to me.  will just wait for unit tests.

this was on my radar, but i hadn't gotten to it yet.  resolves #873

**Comment by RussTedrake** [comment]
It occurred to me that we should update the matlab parser, too, so that they stay in sync

**Comment by steinachim** [comment]
Makes sense. I'll work on it first thing tomorrow. No more free time left today.

**Comment by avalenzu** [comment]
If we make eigen required, we'll always have a C++ manipulator, right?
Perhaps we could reverse the information flow in constructModelMex and zap
the matlab parser?

**Comment by steinachim** [comment]
I have updated the MATLAB parser the same way as the C++ parser - no major refactoring for now ;)

**Comment by RussTedrake** [comment]
Thanks!

**Comment by RussTedrake** [comment]
@psiorx - any idea what happened on the build servers here?

**Comment by RussTedrake** [comment]
just checked.  there are definitely new segfaults on the build servers due to this.  can't accept until their resolved.

**Comment by steinachim** [comment]
This latest build says 0 unknown failures, so does this mean the problem was resolved? I am a bit confused here. In the meantime, I looked through the code again and didn't see anything that might cause a segfault...

**Comment by RussTedrake** [comment]
Drake003 and drake004 are windows machines and don't run all the unit tests.  I don't think it's been resolved

**Comment by psiorx** [comment]
The missing mesh errors were due to the corresponding .wrl (or the .stl that can generate the .wrl) not being present alongside the .obj.  That should be fixed in master now.

**Comment by RussTedrake** [comment]
the printout said it was looking for obj's, not wrls.  but i think the printouts (probably?) weren't the actual problem... the c++ parser was segfaulting.

**Comment by steinachim** [comment]
A broken Makefile? I didn't touch any Makefile?!
On a more positive note, I fixed the segfault.

**Comment by RussTedrake** [comment]
drake005 is misbehaving; you can ignore it for now.  drake006 looks good.  will make sure we're good on the mac (drake001), and then merge.  thanks!

**Pull request merged**
