### PR TITLE
Match Bazel gtest defines to drake/CMakeLists.txt

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4528)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by ggould-tri** [comment]
:lgtm: yeah okay whatever.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4528#-:-KZ7r15-E5_8drOX8C9l:b-o1218i)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Once bazel CI build passed; the other bazel CI failure is just CI being totally broken.  Using override-merge for bazel-only change.

**Pull request merged**
