### PR TITLE
Change /// to // within internal namespace in mobilizer.h

### PR DESCRIPTION
**Pull request by mitiguy**
This PR addresses the  mobilizer.h part of issue #13738.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14461)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Thanks, Paul! :lgtm: x 2. Merge when CI is all green.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14461#-:-MOhiqNGD4RcuAwcAZay:b4kx443)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by mitiguy — COMMENTED** [review]
Thanks @sherm1  for the quick review.
For some reason, CI seems to be still working on this (2 hours).
If nothing good happens, I'll try a "please" later.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14461#-:-MOi5IsTEcumH6KlyKyO:b-apr1cp)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by mitiguy — COMMENTED** [review]
Also @sherm1  before I merge this, please take a look at your comments is issue #11229.
I do not want us to need to revert to adding back the /// -- which may be more delicate search/replace work than.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14461#-:-MOiBqpQDBXmdB2ANseg:b8yn4jm)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Thanks, I took a look -- that's a separate issue (about creating a Doxygen technical note containing some of this implementation info). That would require reformatting anyway, so the change here is good.
I'll merge this doc-only change without waiting for the one remaining slow poke.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14461#-:-MOiGnm1AS2x6r-rdt4d:b-9dcodc)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
