### PR TITLE
Update supported Gurobi version to 7.5.2

### LINKED ISSUE #7484: Support Gurobi 7.5.2
Our CI uses gurobi 7.0.2, but gurobi has a new version 7.5.2 that is faster. Our bazel build code hardcodes gurobi 7.0.2 in https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/gurobi/gurobi.bzl#L15

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #7484.

This will fail Linux CI initially since GUROBI_PATH is still set to 7.0.2.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7540)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@hongkai-dai for feature review. Please test locally.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by hongkai-dai** [comment]
I tested this branch on my machine (Ubuntu 16.04) with bazel and clang. The tests all pass.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7540#-:-L-CsVlR0Fp7vJUkLxVa:b-hltqjw)*

**Comment by jamiesnape** [comment]
Is that an LGTM?

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7540#-:-L-DmyiV7bQXKnZkJT3T:b-sor3mo)*

**Comment by hongkai-dai** [comment]
Almost, I sent a PR to your repo on this branch, to relax one of the tolerance. Without which the CI fails on MAC https://drake-jenkins.csail.mit.edu/job/mac-highsierra-clang-bazel-experimental-everything/5/

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7540#-:-L-DqhQ5XnPIv0nwnzOu:b3i96to)*

**Comment by jamiesnape** [comment]
Missed that somehow. Merged now.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7540#-:-L-HYAn3eEy4u8uhxqya:b-et1g6h)*

**Comment by hongkai-dai** [comment]
:lgtm: +@soonho-tri for platform review please.

---

Reviewed 11 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7540#-:-L-HtlOn8Xfommruwuec:b-mkkz8q)*

**Comment by soonho-tri** [comment]
BTW, there is a CI failure, `linux-xenial-clang-bazel-experimental-everything`.

---

Reviewed 11 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7540#-:-L-HwML0z3tL_6NHEGXL:b-ro1waz)*

**Comment by jamiesnape** [comment]
Yes, it is expected. I have to change over CI immediately before I merge.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7540#-:-L-HxSi_scFh7eQhM3wy:b-4je4ul)*

**Comment by soonho-tri** [comment]
:lgtm: (:apple: tested as well)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7540#-:-L-HyK_Br8-w0vG8NV2-:b3epk59)*

**Pull request merged**
