### PR TITLE
Add pow to GenericPolynomial.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
@ericcousineau-tri and @jwnimmer-tri is it OK if I ask for your help on the CI failure? I don't quite understand the error
```
[9:12:29 PM]  bazel-out/k8-opt/bin/bindings/pydrake/_virtual_includes/symbolic_types_pybind/drake/bindings/pydrake/symbolic_types_pybind.h:43:74: error: no match for call to '(const pybind11::detail::overload_cast_impl<const drake::symbolic::Expression&, const drake::symbolic::Expression&>) (<unresolved overloaded function type>)'
[9:12:29 PM]         .def("pow", py::overload_cast<const Expression&, const Expression&>(
[9:12:29 PM]                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
[9:12:29 PM]                         &symbolic::pow))
```
As far as I can see, the newly added `pow` function in C++ should not cause this error in the python binding, as this new `pow` function has the SFINAE `GenericPolynomialEnable<BasisElement>`, which should only be instantiated when `BasisElement` is a derived class of `PolynomialBasisElement`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158#-:-MIdoOXr774uPD9-nWSY:bnav44j)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by EricCousineau-TRI — COMMENTED** [review]
My superficial analysis is :shrug: probably not worth investigating, as you have alternatives as are listed here:
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeOverloads

`py::overload_cast` gets really finicky with templates.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158#-:-MIf2v2C-SF_tKE272vS:bseurfw)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by EricCousineau-TRI — COMMENTED** [review]
(I've got a back-of-the-mind task to root-cause it, but it hasn't been that important to me, and its importance probably won't change for me any time soon)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158#-:-MIf3PWs2zoUyP16nbpn:b-7ys978)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
Thanks Eric, using lambda fixes the template overloading problem.

+@soonho-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158#-:-MIgK76oCY4cccgzjl4J:b-jsnzf7)* status: LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

+@seancurtis-tri for platform-review, please.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158#-:-MItiHOnBESWkL_apqT3:b-3cjmgc)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[common/symbolic_generic_polynomial.h, line 481 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14158#-MIti4XCDClbB3lKLV9f:-MIti4XCDClbB3lKLV9g:b-iexzyk) ([raw file](https://github.com/robotlocomotion/drake/blob/b1148af1f14ab886b31ed277a4b4436305842da8/common/symbolic_generic_polynomial.h#L481)):*
> ```objc
> }
> 
> /** Returns polynomial @p raised to @p n.*/
> ```

nit, let's mention "the degree should be non-negative" in the doc?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158#-:-MItm38CEQ89MnnrZp0t:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai and @SeanCurtis-TRI)

**Comment by soonho-tri** [comment]
-@SeanCurtis-TRI

**Comment by soonho-tri** [comment]
+@EricCousineau-TRI as platform-reviewer.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @soonho-tri)

___
*[common/symbolic_generic_polynomial.h, line 481 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14158#-MIti4XCDClbB3lKLV9f:-MItyOkF3kqiAZCOhL-U:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/b1148af1f14ab886b31ed277a4b4436305842da8/common/symbolic_generic_polynomial.h#L481)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, let's mention "the degree should be non-negative" in the doc?
</blockquote></details>

Done. Good call.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[common/symbolic_generic_polynomial.h, line 482 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14158#-MItzZc_0zpCbMQs-r34:-MItzZc_0zpCbMQs-r35:b3yslht) ([raw file](https://github.com/robotlocomotion/drake/blob/443ea903c065280267dc5b19ec9229a7244364d6/common/symbolic_generic_polynomial.h#L482)):*
> ```objc
> 
> /** Returns polynomial @p raised to @p n.
>  * @param The base polynomial
> ```

nit, missing `p`?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),EricCousineau-TRI(platform) (waiting on @soonho-tri)

___
*[common/symbolic_generic_polynomial.h, line 482 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14158#-MItzZc_0zpCbMQs-r34:-MIu37dDEUR-o7rJKHCT:b4g0byo) ([raw file](https://github.com/robotlocomotion/drake/blob/443ea903c065280267dc5b19ec9229a7244364d6/common/symbolic_generic_polynomial.h#L482)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, missing `p`?
</blockquote></details>

oops, done.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14158)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
