### PR TITLE
Use non-POD eigen

### LINKED ISSUE #3326: Use upstream Eigen instead of POD wrapper
Yes: https://bitbucket.org/eigen/eigen/ (hg repo)
No: https://github.com/RobotLocomotion/eigen-pod

(Current archive used is https://bitbucket.org/eigen/eigen/get/5a47e5a.tar.gz)

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #3326.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3439)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
Passing on OS X and Windows, not on Linux. Very unusual.

**Comment by jamiesnape** [comment]
Which of course means case sensitivity issues. The moral of this story is do not convert a Mercurial repo to a Git repo on a case insensitive filesystem like most OS X installations.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
Some request for clarification because I don't trust `find_package`, but :lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/CMakeLists.txt, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3439#-KRnhBBVYgkoF5i9ZP6W:-KRnhBBWo_D1emvEdS0U:b82fgi3) ([raw file](https://github.com/robotlocomotion/drake/blob/15ea0ba5a0ceec320cab16014b4311006fbf91a6/drake/CMakeLists.txt#L223)):*
> ```CMake
> 
> find_package(Eigen3 REQUIRED)
> include_directories(SYSTEM "${EIGEN3_INCLUDE_DIRS}")
> ```

BTW, what's the difference between `_DIR` and `_DIRS`?

---

*[drake/CMakeLists.txt, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3439#-KRnhPuLuRESVtmn19EC:-KRnhPuLuRESVtmn19ED:b8fk3m0) ([raw file](https://github.com/robotlocomotion/drake/blob/15ea0ba5a0ceec320cab16014b4311006fbf91a6/drake/CMakeLists.txt#L223)):*
> ```CMake
> 
> find_package(Eigen3 REQUIRED)
> include_directories(SYSTEM "${EIGEN3_INCLUDE_DIRS}")
> ```

BTW, why `SYSTEM`?  Just to quash compiler warnings?

---

*[drake/CMakeLists.txt, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3439#-KRnhT4R3-UZbTAJru7P:-KRnhT4R3-UZbTAJru7Q:b-kavm62) ([raw file](https://github.com/robotlocomotion/drake/blob/0be1d5bfd3a17797a4463fbbb0d24076c2af9e97/drake/CMakeLists.txt#L228)):*
> ```CMake
> else()
>   # then use the traditional approach to finding Eigen3
>   find_package(Eigen3 3.2.92)
> ```

BTW, why drop the version number?  Are we assuming it always comes out of `externals`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3439#-:-KRnhbYDTk4i3h5kn10l:b2bnzub)*

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[drake/CMakeLists.txt, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3439#-KRnhBBVYgkoF5i9ZP6W:-KRniZ91ObhSMb0Bz_tJ:b4h4k9v) ([raw file](https://github.com/robotlocomotion/drake/blob/15ea0ba5a0ceec320cab16014b4311006fbf91a6/drake/CMakeLists.txt#L223)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, what's the difference between `_DIR` and `_DIRS`?
</details>
In this case, nothing. Usually `_DIR` is for internal use `_DIRS` for external use.

---

*[drake/CMakeLists.txt, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3439#-KRnhPuLuRESVtmn19EC:-KRnimj6Dwhkt_JmdPfZ:bb77ufg) ([raw file](https://github.com/robotlocomotion/drake/blob/15ea0ba5a0ceec320cab16014b4311006fbf91a6/drake/CMakeLists.txt#L223)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, why `SYSTEM`?  Just to quash compiler warnings?
</details>
Yes.

---

*[drake/CMakeLists.txt, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3439#-KRnhT4R3-UZbTAJru7P:-KRnjMqig5uEXgFyFx2G:b-ovuvb8) ([raw file](https://github.com/robotlocomotion/drake/blob/0be1d5bfd3a17797a4463fbbb0d24076c2af9e97/drake/CMakeLists.txt#L228)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, why drop the version number?  Are we assuming it always comes out of `externals`?
</details>
Yes, and in reality that code was never triggered and did not work. We would need to upstream a fix. Eigen is missing a package version file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3439)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
