### PR TITLE
Change ContactInfo::contact_details_ from unique_ptr to copyable_unique_ptr

### LINKED ISSUE #5962: ContactInfo should make use of copyable_unique_ptr
`ContactInfo` has a non-default copy constructor because it has polymorphic members (`ContactDetails`). These non-default constructors are simply duplicating the underlying functionality that `copyable_unique_ptr` provides. Change from `unique_ptr` to `copyable_unique_ptr` and switch to default copy/move semantics.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
ContactInfo had a vector of unique_ptr to ContactDetail. To make this
copyable, it required non-default copy construct/assignment. By switching
this to copyable_unique_ptr, the ContactInfo class could use default copy
*and* move semantics.

It also required changing the interface from various upstrea/downstream
elements to use copyable_unique_ptr instead of unique_ptr where appropriate.

Resolves #5962

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5963)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@jwnimmer-tri for feature review

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-:-Kiox3fhT9uxT6k33q_-:b-982cs4)*

**Comment by sherm1** [comment]
Platform review: Oh, I love seeing all that ugly code get deleted! Something I don't love is the degree to which the copyable_unique_ptr leaked out into the API. I have been thinking of it as an internal detail that permits a class to use a default copy constructor. I don't think users from outside the class should notice. Can this be done in a way that keeps the use of the non-standard pointer internal?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-:-Kip5U_D6wxBm_lECwU2:bl0wskd)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/contact_info.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-KiusTeNso2RU3eJZtMM:-KiusTeNso2RU3eJZtMN:b-idiwqj) ([raw file](https://github.com/robotlocomotion/drake/blob/90146d3f81fa7b4cef9ae99cd337938278ea84a9/drake/multibody/rigid_body_plant/contact_info.h#L76)):*
> ```objc
> 
>   void set_contact_details(
>       std::vector<copyable_unique_ptr<ContactDetail<T>>>&& details) {
> ```

This API could (and probably should) remain unchanged -- the body turns into a for-loop that moves between containers one by one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5963)*

**Comment by SeanCurtis-TRI** [comment]
API addressed -- now accepts `unique_ptr` as input on all meaningful methods.

---

Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/contact_info.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-KiusTeNso2RU3eJZtMM:-Kj3FPkwl7Nb1RqcA93q:b-v1c8vn) ([raw file](https://github.com/robotlocomotion/drake/blob/90146d3f81fa7b4cef9ae99cd337938278ea84a9/drake/multibody/rigid_body_plant/contact_info.h#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This API could (and probably should) remain unchanged -- the body turns into a for-loop that moves between containers one by one.
</blockquote></details>

Done 

I'd considered that. Since the prevailing opinion seems to be maintain an interface with `unique_ptr`, I'll go ahead and do that. I've opted to *extend* the interface to allow both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-:-Kj3JphuAeTvRvbr2oGp:brh5enb)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/contact_info.h, line 82 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-Kj3QhtyDjXz5pr5mYbK:-Kj3QhtyDjXz5pr5mYbL:b-4cvl2a) ([raw file](https://github.com/robotlocomotion/drake/blob/7b5dbcee746be70e772f852225e8670308d7a1b3/drake/multibody/rigid_body_plant/contact_info.h#L82)):*
> ```objc
>   void set_contact_details(
>       std::vector<std::unique_ptr<ContactDetail<T>>>&& details) {
>     for (size_t i = 0; i < details.size(); ++i) {
> ```

Shouldn't this clear `contact_details_` first?  Missing unit test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-:-Kj3RECf3AhAde1YQWAN:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-:-Kj3VeYQLgJ5ni39C5s4:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Corrected and tested.

---

Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/contact_info.h, line 82 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-Kj3QhtyDjXz5pr5mYbK:-Kj3hP39VT3DEYOaomIj:bvohlt5) ([raw file](https://github.com/robotlocomotion/drake/blob/7b5dbcee746be70e772f852225e8670308d7a1b3/drake/multibody/rigid_body_plant/contact_info.h#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Shouldn't this clear `contact_details_` first?  Missing unit test?
</blockquote></details>

Done

You are 100% correct. Quick and dirty was too quick and dirty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5963#-:-Kj3hdHEmlTc9rzWXLMh:btov5fc)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5963)*

**Pull request merged**
