### PR TITLE
July 2022 upgrades

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #17494.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17496)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-undefined-behavior-sanitizer please

**Comment by jwnimmer-tri** [comment]
#17486 is already handling picosat.  It would be simpler to keep it out of this PR entirely.  The goal of the monthly upgrades is to ensure that no external gets left behind.  Since we're already paying attention to picosat separately, it's best to omit it here to reduce duplicate work.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews +(release notes: fix) .

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17496#-:-N6J51tM6pWTJKthNURZ:b-t7oaaq)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Pull request merged**
