### PR TITLE
Updated Sublime Text notes.

### PR DESCRIPTION
**Pull request by liangfok**
I wish @jwnimmer-tri, @amcastro-tri, or someone else with extensive `emacs` experience could create a similar page for `emacs`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2395)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature and platform review since this is just documentation.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Updated Sublime Text notes\.
> 
> I wish @jwnimmer-tri, @amcastro-tri, or someone else with extensive `emacs` experience could create a similar page for `emacs`.
> 
> 
> 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2395#-:-KI4_17aoBgGTsD_NEpR:-813810538)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@jwnimmer-tri for feature and platform review since this is just documentation.
</details>


---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/sublime_text.rst, line 75 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2395#-KI4ve-gpGOV46yKW_TA:-KI4ve-gpGOV46yKW_TB:-1312687039) ([raw file](https://github.com/robotlocomotion/drake/blob/94a4fff7b3b2eeabd6cf62cd33b29ba5a724ca09/drake/doc/sublime_text.rst#L75)):*
> ```reStructuredText
> default ``*.sdf`` does show up in the list.
> 
> Automatically show an 80-character Ruler
> ```

BTW Other section titles seem to be All Upper Case.  Do you want "Show" here?

(Notice the new reviewable keyword "BTW" here, which if I've used it correctly means that I don't need to sign off on any resolution here; author's discretion.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2395#-:-KI4vz87hd-6u1qCxjc-:1417088721)*

**Comment by liangfok** [comment]
:lgtm: 

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/doc/sublime_text.rst, line 75 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2395#-KI4ve-gpGOV46yKW_TA:-KI50_xSPWnEy5l2f40U:-733354857) ([raw file](https://github.com/robotlocomotion/drake/blob/94a4fff7b3b2eeabd6cf62cd33b29ba5a724ca09/drake/doc/sublime_text.rst#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Other section titles seem to be All Upper Case.  Do you want "Show" here?
> 
> (Notice the new reviewable keyword "BTW" here, which if I've used it correctly means that I don't need to sign off on any resolution here; author's discretion.)
</details>
Fixed. Thanks!

Looks like the BTW keyword worked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2395#-:-KI50iSncprQ46DnNngL:980077423)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2395)*

**Pull request merged**
