### PR TITLE
[multibody] remove joint locking from reaction forces test

### PR DESCRIPTION
**Pull request by joemasterjohn**
This PR refactors testing of joint locking by removing lock/unlock parameters from `multibody_reaction_forces_test` and adding a new test to `joint_locking_test` that verifies the physics of a locked joint matches that of a weld.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18051)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@amcastro-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18051#-:-NDiNh-t6HsIy5osbPE4:b5xll3r)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Excellent! only minor comments.
:lgtm: 

+@ericcousineau-tri for platform review please.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18051#-:-NDiT4Om-J7nMQ7c9MDl:b3vo5ux)* status: 8 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @joemasterjohn)

___
*[`multibody/plant/test/joint_locking_test.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiRpmK9kBRAh8lMbS9:-NDiRpmK9kBRAh8lMbSA:b-p5px5a) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L41)):*
> ```cpp
> const double kTimestep = 0.01;
> // Allow 6 bits of error.
> const double kEps = (1 << 6) * std::numeric_limits<double>::epsilon();
> ```

nit, considere moving kEps and kNumTimesteps local to the acceleration test scope since only used there thus far.
___
*[`multibody/plant/test/joint_locking_test.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiSg7MC8LolUKm6gfA:-NDiSg7MC8LolUKm6gfB:b-v0cd6d) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L41)):*
> ```cpp
> const double kTimestep = 0.01;
> // Allow 6 bits of error.
> const double kEps = (1 << 6) * std::numeric_limits<double>::epsilon();
> ```

nit, I find that thinking in terms of digits of precision lost is easier than thinking in terms of bits of precision lost.
I am fine either way, but could you add a comment on how this number is set? 
___
*[`multibody/plant/test/joint_locking_test.cc` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiR4xGEdL_ZWvwk6Yk:-NDiR4xGEdL_ZWvwk6Yl:b-kzxwcs) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L184)):*
> ```cpp
> // concentrated at the lower ends of the two links. The 0-configuration has the
> // upper arm sticking out horizontally in the x direction and the longer lower
> // arm oriented in the (0.1, 0, 0.1) direction from the end of the upper arm. If
> ```

nit, not sure I understand this. "oriented"? orientation makes me thing of a unit vector but this seems to be a 3D position? 



_Code quote:_
```cpp
 oriented in the (0.1, 0, 0.1) direction 
```
___
*[`multibody/plant/test/joint_locking_test.cc` line 217 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiRUKX1ydaNCCRvZbB:-NDiRUKX1ydaNCCRvZbC:b-o3rv2q) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L217)):*
> ```cpp
> // joint, we construct two plants. Each plant consists of a double pendulum with
> // the shoulder welded to the world. The elbow joint of `plant_welded` is a
> // WeldJoint fixed at the 0-configuration. The elbow joint of `plant_locked` is
> ```

for completeness, would it be better to lock the elbow at a non-zero configuration?
___
*[`multibody/plant/test/joint_locking_test.cc` line 219 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiRalnDyYnlUlrvnsv:-NDiRalnDyYnlUlrvnsw:b-eulkfq) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L219)):*
> ```cpp
> // WeldJoint fixed at the 0-configuration. The elbow joint of `plant_locked` is
> // a revolute joint that has been locked at the 0-configuration. We verify that
> // the generalized accelerations,
> ```

sentence is not complete.
___
*[`multibody/plant/test/joint_locking_test.cc` line 220 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiT1RjAmpruxahTIFA:-NDiT1Rk7_TLTH07o9aT:b-1b3uo0) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L220)):*
> ```cpp
> // a revolute joint that has been locked at the 0-configuration. We verify that
> // the generalized accelerations,
> GTEST_TEST(JointLockingTest, AccelerationTest) {
> ```

btw, nice test!
___
*[`multibody/plant/test/joint_locking_test.cc` line 278 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiSOlpCLDLTh3vkJSC:-NDiSOlpCLDLTh3vkJSD:b-kgzave) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L278)):*
> ```cpp
> 
>     // Check that the velocities and positions of corresponding dofs match.
>     const auto welded_positions_and_velocities =
> ```

nit, spell out return type.
___
*[`multibody/plant/test/joint_locking_test.cc` line 292 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiSb6H3JQSgo6iizox:-NDiSb6H3JQSgo6iizoy:b-9yd0ml) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L292)):*
> ```cpp
> 
>     // Position and velocity of the locked joint should be identically 0.
>     EXPECT_EQ(locked_positions_and_velocities[elbow_index_locked], 0);
> ```

nit, consider using a non-zero configuration for the locked elbow.

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18051)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[`multibody/plant/test/joint_locking_test.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiRpmK9kBRAh8lMbS9:-NDiVOir2t2bQuG5F0v9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L41)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, considere moving kEps and kNumTimesteps local to the acceleration test scope since only used there thus far.
</blockquote></details>

Done.
___
*[`multibody/plant/test/joint_locking_test.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiSg7MC8LolUKm6gfA:-NDiVPYh-rrLwHxzGdpt:byghzwb) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L41)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, I find that thinking in terms of digits of precision lost is easier than thinking in terms of bits of precision lost.
I am fine either way, but could you add a comment on how this number is set? 
</blockquote></details>

Done. Rephrased to digits of precision and added a comment below.
___
*[`multibody/plant/test/joint_locking_test.cc` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiR4xGEdL_ZWvwk6Yk:-NDiWDTHEl68XcXivAO8:b-91zhub) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L184)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, not sure I understand this. "oriented"? orientation makes me thing of a unit vector but this seems to be a 3D position? 
</blockquote></details>

Done. Rephrased to be clearer.
___
*[`multibody/plant/test/joint_locking_test.cc` line 217 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiRUKX1ydaNCCRvZbB:-NDidMqQ3ebJjjKVzbyP:b-1n328f) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L217)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

for completeness, would it be better to lock the elbow at a non-zero configuration?
</blockquote></details>

Done. Changed to a non-zero configuration.
___
*[`multibody/plant/test/joint_locking_test.cc` line 219 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiRalnDyYnlUlrvnsv:-NDidLQ8DMZrKXO2Z38n:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L219)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sentence is not complete.
</blockquote></details>

Done. Thanks.
___
*[`multibody/plant/test/joint_locking_test.cc` line 220 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiT1RjAmpruxahTIFA:-NDiWI59AZKBx5xdgN0y:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L220)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

btw, nice test!
</blockquote></details>

Thanks!
___
*[`multibody/plant/test/joint_locking_test.cc` line 278 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiSOlpCLDLTh3vkJSC:-NDiWb7G489sTBZD8sCg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L278)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, spell out return type.
</blockquote></details>

Done.
___
*[`multibody/plant/test/joint_locking_test.cc` line 292 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDiSb6H3JQSgo6iizox:-NDidQ3_DYCw0WSFWNID:b-1n328f) ([raw file](https://github.com/robotlocomotion/drake/blob/67d4ad97b2d715c5ba22407c8f490caf2be76a78/multibody/plant/test/joint_locking_test.cc#L292)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, consider using a non-zero configuration for the locked elbow.
</blockquote></details>

Done. Changed to a non-zero configuration.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform! Just some nits and q's

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18051#-:-NDihyMUEuGlryWtAqMz:b-7cerax)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri and @joemasterjohn)

___
*[`multibody/plant/test/joint_locking_test.cc` line 182 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDihTreEmXmJfEqWvnR:-NDihTrf4-ioKs-6GNuj:b-8grak4) ([raw file](https://github.com/robotlocomotion/drake/blob/29548b29c83354ba216f5bcd233f91ca05175a0a/multibody/plant/test/joint_locking_test.cc#L182)):*
> ```cpp
> // Create a plant with a XZ-planar double pendulum where the masses are
> // concentrated at the lower ends of the two links. The 0-configuration has the
> // upper arm sticking out horizontally at (-0.1, 0, 0) and the longer lower
> ```

nit Should make `0.1` a constant? e.g `kArmLength`?
___
*[`multibody/plant/test/joint_locking_test.cc` line 182 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDih_n9DMvssr32YXiq:-NDih_n9DMvssr32YXir:b-3cd2yn) ([raw file](https://github.com/robotlocomotion/drake/blob/29548b29c83354ba216f5bcd233f91ca05175a0a/multibody/plant/test/joint_locking_test.cc#L182)):*
> ```cpp
> // Create a plant with a XZ-planar double pendulum where the masses are
> // concentrated at the lower ends of the two links. The 0-configuration has the
> // upper arm sticking out horizontally at (-0.1, 0, 0) and the longer lower
> ```

nit How is the lower arm longer? They seem to have same CoM?

**Review by joemasterjohn — COMMENTED** [review]
Thanks for the quick reviews!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18051#-:-NDijBmZ5qfh5gr8MHJs:b-dfhtn3)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[`multibody/plant/test/joint_locking_test.cc` line 182 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDihTreEmXmJfEqWvnR:-NDiif8lDh9iKn6LRKFD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/29548b29c83354ba216f5bcd233f91ca05175a0a/multibody/plant/test/joint_locking_test.cc#L182)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should make `0.1` a constant? e.g `kArmLength`?
</blockquote></details>

Done.
___
*[`multibody/plant/test/joint_locking_test.cc` line 182 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18051#-NDih_n9DMvssr32YXiq:-NDiiggoESnkihTeT2K4:bi4e6t3) ([raw file](https://github.com/robotlocomotion/drake/blob/29548b29c83354ba216f5bcd233f91ca05175a0a/multibody/plant/test/joint_locking_test.cc#L182)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit How is the lower arm longer? They seem to have same CoM?
</blockquote></details>

Done. Whoops, left over from previous commit where I had it longer.

**Review by joemasterjohn — COMMENTED** [review]
> Dismissed @amcastro-tri from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18051)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
