### PR TITLE
Add solver_id accessor to MPSolverInterface

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The intention is to remove `solver_type()` and `SolverName()` once they are no longer used.

Relates #6159.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6433)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai are you interested in feature-review for this?

**Comment by hongkai-dai** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/ipopt_solver_common.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6433#-Knh29X1h--iFYSHrW8i:-Knh29X1h--iFYSHrW8j:b-boqxga) ([raw file](https://github.com/robotlocomotion/drake/blob/1e893d4ec7165a90c0248e218106000774760312/drake/solvers/ipopt_solver_common.cc#L1)):*
> ```cpp
> #include "drake/solvers/ipopt_solver.h"
> ```

ipopt is an open source solver, does it also needs a `xxx_common.cc` file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6433)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per on-call rotation, please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/ipopt_solver_common.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6433#-Knh29X1h--iFYSHrW8i:-KnieTOlFsFgngFqHBJQ:b-nbjmvu) ([raw file](https://github.com/robotlocomotion/drake/blob/1e893d4ec7165a90c0248e218106000774760312/drake/solvers/ipopt_solver_common.cc#L1)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

ipopt is an open source solver, does it also needs a `xxx_common.cc` file?
</blockquote></details>

OK Good question.  (I also had this misunderstanding when I first wrote this PR.)

The answer is yes (and ditto for NLopt), because we allow users to turn of IPOPT.  In the CMake build, it's just another one of `ccmake`'s usual `WITH_IPOPT` option (and is in fact disabled in the "-minimal-" variant in CI), and in Bazel we have an (unsupported) configuration option to disable it also.

Or more mechanically: any solver with a `no_myself.cc` file needs a `myself_solver_common.cc` file.

(FYI my long-term goal would be to stop using the `no_myself.cc` files, but that won't happen soon.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6433#-:-KnifsZbA3z6cFMahp8w:b-aop2ch)*

**Comment by ggould-tri** [comment]
This would all be so much more pleasant if C++ had virtual statics.  You're way past rule-of-three on the id.name boilerplate, but I will call that no-defect as you plan to remove it in the future.

:lgtm:

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6433#-:-KnirFldNJnZOIzQNNnP:byh6kz4)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/ipopt_solver_common.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6433#-Knh29X1h--iFYSHrW8i:-KnjT63gQHQJ32uX3jNj:b-nf0eir) ([raw file](https://github.com/robotlocomotion/drake/blob/1e893d4ec7165a90c0248e218106000774760312/drake/solvers/ipopt_solver_common.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Good question.  (I also had this misunderstanding when I first wrote this PR.)

The answer is yes (and ditto for NLopt), because we allow users to turn of IPOPT.  In the CMake build, it's just another one of `ccmake`'s usual `WITH_IPOPT` option (and is in fact disabled in the "-minimal-" variant in CI), and in Bazel we have an (unsupported) configuration option to disable it also.

Or more mechanically: any solver with a `no_myself.cc` file needs a `myself_solver_common.cc` file.

(FYI my long-term goal would be to stop using the `no_myself.cc` files, but that won't happen soon.)
</blockquote></details>

Thanks for the explanation! Then maybe we delete the comment `// This file contains implementations that are common to both the available and
// unavailable flavor of this class.` in the `dreal_solver_common.cc`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6433#-:-KnjTNc9GT9zhzBxklHx:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 23 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/ipopt_solver_common.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6433#-Knh29X1h--iFYSHrW8i:-KnjgyayjvW1McUtcwkA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e893d4ec7165a90c0248e218106000774760312/drake/solvers/ipopt_solver_common.cc#L1)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks for the explanation! Then maybe we delete the comment `// This file contains implementations that are common to both the available and
// unavailable flavor of this class.` in the `dreal_solver_common.cc`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6433)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6433)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Pull request merged**
