### PR TITLE
[common] Deprecate TrigPoly

### PR DESCRIPTION
**Pull request by RussTedrake**
Our symbolic::Expression can do this work, too, now, and with
Expression we can process trigonometric polynomials directly from
MultibodyPlant.

+@ggould-tri for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16741)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
:lgtm:
I'm glad to see this get swept up into the symbolic world.
I hope there aren't many or any downstream users to be affected by this.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16741#-:-MxjJLlzAItj106jTK05:b8iews2)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
+@xuchenhan-tri for platform review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16741#-:-MxjwwZrB0L_j2ztg5X5:bdtbcre)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16741#-:-Mxjz7T8-w-MY9zIsRDE:b-vtj4vo)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
apologies.  making both clang and gcc simultaneously happy was hard.  and i ended up needing to bring the deprecation of SystemIdentification into this commit/PR to achieve it.  Can you both confirm that you're ok with the system_identification changes, too?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16741#-:-Mxk2UofAauWR49ZRseG:b-6udpt0)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Still :lgtm: 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16741#-:-MxkG8waBY9xgiuYEXKF:b-dbkjmx)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @RussTedrake)

**Review by xuchenhan-tri — COMMENTED** [review]
@ggould-tri I believe this PR is waiting on your LGTM on the sys-id files to be merged.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16741#-:-MxmDVA955lfZ6kLB_08:b-uehucz)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @RussTedrake)

**Review by ggould-tri — COMMENTED** [review]
Ah, it wasn't red in my dashboard so I didn't see it.  Yes this is lgtm.

> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16741#-:-MxnxYFt3elHBcUVBdNU:b-ms29ar)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
