### PR TITLE
Merge testing into build-wheels script

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify the wheel building logic to expect the wheel version to be passed in via an argument to the `Dockerfile`, and add the wheel version as a required argument to the `build-wheels` script. Move the logic to set up containers for wheel testing and run the test script in the same into the `build-wheels` script.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16139)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please. Please don't squash.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16139)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @mwoehlke-kitware)

___
*[tools/wheel/dev/build-wheels, line 205 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16139#-MpgLRfsEiRS3bZ8Ile6:-MpgLRfsEiRS3bZ8Ile7:b9v8gwq) ([raw file](https://github.com/robotlocomotion/drake/blob/99f309be73d720048bc7871eae556b7b1838bb3c/tools/wheel/dev/build-wheels#L205)):*
> ```
>     parser.add_argument(
>         'version',
>         help='version number with which to label the wheels')
> ```

One question that regularly comes up is whether the version number should be spelled like "1.2.3" (as we do for whl files) or "v1.2.3" (as we do for everything else).  In this case, we want the "1.2.3" flavor.  That desired format should be documented in the help string (even if only by way of an example). We should probably also fail-fast here at runtime if the options.version starts with a "v".
___
*[tools/wheel/dev/build-wheels, line 43 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16139#-MpgNF10D-pfK0XEQls0:-MpgNF10D-pfK0XEQls1:be4068o) ([raw file](https://github.com/robotlocomotion/drake/blob/21d3c3494f591f9124d7a5f8117d1efef317424f/tools/wheel/dev/build-wheels#L43)):*
> ```
> 
> 
> def docker(*args, pipe=False):
> ```

The function docstring should explain what the "pipe" option does.
___
*[tools/wheel/dev/build-wheels, line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16139#-MpgNIu6BZO8vi0KbfBy:-MpgNIu6BZO8vi0KbfBz:bf916pk) ([raw file](https://github.com/robotlocomotion/drake/blob/21d3c3494f591f9124d7a5f8117d1efef317424f/tools/wheel/dev/build-wheels#L45)):*
> ```
> def docker(*args, pipe=False):
>     """
>     Runs a docker command; raises an exception on failure.
> ```

The promise to "raises an exception on failure" is not strictly true, when pipe=True.  Failures such as "no such executable foo" would still happen, but if the command fails while running, this function will not raise.  The documentation should be clear about what's happening in that case -- that its up to the the user to check the returncode.  The documentation should also explain what kind of object is returned in each case.
___
*[tools/wheel/dev/build-wheels, line 226 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16139#-MpgQX_g6uiqFRiM885K:-MpgQX_g6uiqFRiM885L:byv9k2e) ([raw file](https://github.com/robotlocomotion/drake/blob/25207ece5924f446507b65f2f7609543fd6935f9/tools/wheel/dev/build-wheels#L226)):*
> ```
>            '-v' f'{options.output_dir}:/wheel',
>            container, '/test/test-wheel.sh', f'/wheel/{wheel}',
>            target.python_version)
> ```

I'm unable to follow what the `target.python_version` argument is doing here (the test_wheel.sh script seems to use only `$1`, not `$2`?).

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16139)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @jwnimmer-tri)

___
*[tools/wheel/dev/build-wheels, line 205 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16139#-MpgLRfsEiRS3bZ8Ile6:-MpmBsjq1f534nKWV6n5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/99f309be73d720048bc7871eae556b7b1838bb3c/tools/wheel/dev/build-wheels#L205)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

One question that regularly comes up is whether the version number should be spelled like "1.2.3" (as we do for whl files) or "v1.2.3" (as we do for everything else).  In this case, we want the "1.2.3" flavor.  That desired format should be documented in the help string (even if only by way of an example). We should probably also fail-fast here at runtime if the options.version starts with a "v".
</blockquote></details>

Done.
___
*[tools/wheel/dev/build-wheels, line 43 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16139#-MpgNF10D-pfK0XEQls0:-MpmFmoH2rjqd-VNCqg0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/21d3c3494f591f9124d7a5f8117d1efef317424f/tools/wheel/dev/build-wheels#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The function docstring should explain what the "pipe" option does.
</blockquote></details>

Done.
___
*[tools/wheel/dev/build-wheels, line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16139#-MpgNIu6BZO8vi0KbfBy:-MpmFmQb1iL4oHivaKi3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/21d3c3494f591f9124d7a5f8117d1efef317424f/tools/wheel/dev/build-wheels#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The promise to "raises an exception on failure" is not strictly true, when pipe=True.  Failures such as "no such executable foo" would still happen, but if the command fails while running, this function will not raise.  The documentation should be clear about what's happening in that case -- that its up to the the user to check the returncode.  The documentation should also explain what kind of object is returned in each case.
</blockquote></details>

Done.
___
*[tools/wheel/dev/build-wheels, line 226 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16139#-MpgQX_g6uiqFRiM885K:-MplvGsh2CpdS5_Bg-9d:boq66sd) ([raw file](https://github.com/robotlocomotion/drake/blob/25207ece5924f446507b65f2f7609543fd6935f9/tools/wheel/dev/build-wheels#L226)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm unable to follow what the `target.python_version` argument is doing here (the test_wheel.sh script seems to use only `$1`, not `$2`?).
</blockquote></details>

Ah, that appears to be left over from when `test-wheel.sh` expected a pristine image and did the provisioning. When that changed, the second argument never got removed from `test-wheels.sh`, and I just blindly copied that here.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16139#-:-MpmHAJs6_NhFolAvbPW:bnfp4nl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
This will need a rebase onto the head of master before we can merge using a merge commit.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16139)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), exempt from platform review, base commit is latest master (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
FYI The "everything" builds (mosek / gurobi) were being slow and have no bearing here, so I've just forced this in now.

**Pull request merged**
