### PR TITLE
Disable //solvers:dreal_solver_test

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #7647

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7648)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@m-chaturvedi for feature-review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7648#-:-L0kVoxatFxwjJ2uZIVn:bin7ko7)*

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7648#-:-L0kW3njyzYDwQvrTYv_:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7648)*

**Comment by soonho-tri** [comment]
+@sammy-tri for platform-review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7648#-:-L0kWGwAWPbW7vrp5OZj:b-3ojlqy)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7648#-:-L0k__XMbA9OxJ6aCXHg:bnfp4nl)*

**Pull request merged**
