### PR TITLE
Remove drake geometry util

### LINKED ISSUE #3414: Finish carving out geometry and gradient from `drake/util` into new homes
The goal is for these include statements to go away, replaced by paths into `common` or `math` (or removed) as necessary:

```
./systems/plants/constraint/RigidBodyConstraint.cpp:11:#include "drake/util/drakeGeometryUtil.h"
./systems/plants/joints/FixedAxisOneDoFJoint.h:12:#include "drake/util/drakeGradientUtil.h"
./systems/plants/joints/QuaternionFloatingJoint.h:7:#include "drake/util/drakeGeometryUtil.h"
./systems/plants/joints/RollPitchYawFloatingJoint.h:7:#include "drake/util/drakeGeometryUtil.h"
./systems/plants/RigidBody.cpp:5:#include "drake/util/drakeGeometryUtil.h"
./systems/plants/RigidBodyTree.cpp:13:#include "drake/util/drakeGeometryUtil.h"
./systems/plants/RigidBodyTree.h:26:#include "drake/util/drakeGeometryUtil.h"
./systems/plants/test/testKinematicsCacheChecks.cpp:11:#include "drake/util/drakeGeometryUtil.h"
./systems/robotInterfaces/QPLocomotionPlan.cpp:19:#include "drake/util/drakeGeometryUtil.h"
```

This may involved relocating the helper functions.

This is a portion of #3278 and thus a prereq for #3253.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #3414. I moved `drakeGeometryUtil` to `math/geometry.h` and `math/geometry.cc`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3427)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for feature review, +@david-german-tri for platform review

---

Review status: 0 of 40 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-:-KRWre0RSjnlRi3JO4X3:b-7jqips)*

**Comment by david-german-tri** [comment]
:lgtm: aside from three minor comments below.  Thanks for doing this!

---

Reviewed 4 of 5 files at r1, 39 of 39 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/autodiff.h, line 169 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-KRYrakmc3TKNh3wi44r:-KRYrakmc3TKNh3wi44s:b-rydzig) ([raw file](https://github.com/robotlocomotion/drake/blob/d576ff5c45ff7512e6fe0c53d8e14a77e8bceb69/drake/math/autodiff.h#L169)):*
> ```objc
> }
> 
> namespace internal {
> ```

Consider consolidating the `namespace internal` stuff into one block.

---

*[drake/math/geometry.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-KRYs9_9CZSXhCV5fm3c:-KRYs9_AtLVbRI4vhIsO:b21bso7) ([raw file](https://github.com/robotlocomotion/drake/blob/d576ff5c45ff7512e6fe0c53d8e14a77e8bceb69/drake/math/geometry.cc#L38)):*
> ```cpp
> }
> 
> Eigen::Matrix3d uniformlyRandomRotmat(std::default_random_engine& generator) {
> ```

Is this dead code?

---

*[drake/math/geometry.h, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-KRYs_Glspi1dGwJkGsr:-KRYs_Glspi1dGwJkGss:b-ggn9gi) ([raw file](https://github.com/robotlocomotion/drake/blob/62027eac23c9391cf237026b7884a64a8a2debad/drake/math/geometry.h#L3)):*
> ```objc
> /// @file
> /// THIS FILE IS DEPRECATED.
> /// Its contents are moving into drake/math.
> ```

The goal was to break this up into smaller pieces, not just to rename it.  (See #2636, #2779, #2664.)  I'm fine with renaming it if that's useful for zapping `/util` quickly; this PR is a win for the namespace fixes in calling code alone.  However, under that plan, this file should still be deprecated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-:-KRYtuum2WVmVp23Yy-4:b-6jaqbb)*

**Comment by jwnimmer-tri** [comment]
*[drake/math/autodiff.h, line 169 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-KRYrakmc3TKNh3wi44r:-KRZP-5obcAXHt8V1put:b-gd2aim) ([raw file](https://github.com/robotlocomotion/drake/blob/d576ff5c45ff7512e6fe0c53d8e14a77e8bceb69/drake/math/autodiff.h#L169)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Consider consolidating the `namespace internal` stuff into one block.
</details>
This actually comes from #3415 I believe -- this PR builds atop that one.  If you can finish #3415's review, we can ask to merge/rebase this PR again and clean up the review here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3427)*

**Comment by hongkai-dai** [comment]
Thank @david-german-tri for the review! Sorry I was not aware that the goal is to break the code into smaller pieces. Will work on that.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-KRZPrqp5Jn6-AIjUt-Q:-KRZPrqp5Jn6-AIjUt-R:b-tenrto) (no related file):*
Several functions in geometry.h do not have standalone C++ tests; they are tested in mex,  with comparison to MATLAB counterparts. Do we want to create standalone test in C++?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-:-KRZFkJhpzXxZw4NTqxC:b-t4vwzu)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-KRZPrqp5Jn6-AIjUt-Q:-KRZR8ErjBAICIC-0doO:bkirtid) (no related file):*
> Several functions in geometry.h do not have standalone C++ tests ...

Yes, that it why the issue is challenging.  Some of the C++ code is only covered by matlab unit tests.  I think we need to have C++ test coverage directly.

I recommend pulling out the functions in smaller chunks, rather than this whole file at once.  That will make it clearer what is going on.  If each chunk ends up in a separate new file (e.g., if you can pre-group the functions now and I have a plan where they all should live), that's even better.

For example `dTransformSpatialMotion` is only used by mex code, so should _not_ be moved into `drake::math` -- it can be shuffled off into `drake/matlab/util` until we happen to want it for new C++ code, at which point we can port and unit test it.

The work here is going through the list of functions, figuring out where they are used, removing dead code (this is a good easy first PR), figuring out if the use is in C++ proper, or mablab mex, grouping into logical file split, then doing PRs for the chunks.

At least, that's one way to do it.  I'm sure there are other fine variants as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3427)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3427#-KRZPrqp5Jn6-AIjUt-Q:-KRZerliSQ7TqW09jymA:b-52rtr3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> > Several functions in geometry.h do not have standalone C++ tests ...
> 
> Yes, that it why the issue is challenging.  Some of the C++ code is only covered by matlab unit tests.  I think we need to have C++ test coverage directly.
> 
> I recommend pulling out the functions in smaller chunks, rather than this whole file at once.  That will make it clearer what is going on.  If each chunk ends up in a separate new file (e.g., if you can pre-group the functions now and I have a plan where they all should live), that's even better.
> 
> For example `dTransformSpatialMotion` is only used by mex code, so should _not_ be moved into `drake::math` -- it can be shuffled off into `drake/matlab/util` until we happen to want it for new C++ code, at which point we can port and unit test it.
> 
> The work here is going through the list of functions, figuring out where they are used, removing dead code (this is a good easy first PR), figuring out if the use is in C++ proper, or mablab mex, grouping into logical file split, then doing PRs for the chunks.
> 
> At least, that's one way to do it.  I'm sure there are other fine variants as well.
</details>
Sounds good. I will close this PR, and submit a series of PR instead. Each PR should contain a chunk of code pulling out from drakeGeometryUtil

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3427)*

**Pull request closed without merging**
