### PR TITLE
Fix find_package(NLopt) calls

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3626)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Look for the absence of
```
  By not providing "FindNLOPT.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NLOPT", but
  CMake did not find one.

  Could not find a package configuration file provided by "NLOPT" with any of
  the following names:

    NLOPTConfig.cmake
    nlopt-config.cmake
```
in the console output.

**Comment by jamiesnape** [comment]
+@david-german-tri  or +@jwnimmer-tri for feature and platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3626#-:-KSrTZKAopp4eNDng8hQ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
N.B. "Priority: Emergency" means "Everyone on the team stop what you're doing and work on this; host a post-mortem after it is resolved".  Please be sure that's what you actually mean when using that tag.

Looking now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3626#-:-KSrTdBFl24coCgW34WJ:b-g736t5)*

**Comment by jamiesnape** [comment]
A large batch of tests not running is my idea of an emergency.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3626#-:-KSrUBaMli0hf6vyhlHW:bnfp4nl)*

**Pull request merged**
