### PR TITLE
Remove some missed WIN32 CMake code

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4242)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
Platform :lgtm: pending CI, open discussions, and feature review.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4242#-KXHAtzLSpZAcAWm2nHS:-KXHAtzMgf6owOGhmNew:b-7h1a4c) ([raw file](https://github.com/robotlocomotion/drake/blob/2e064d9cf75d55885130423dcfb0aa42ab24127d/CMakeLists.txt#L47)):*
> ```CMake
>     -DPKGCONFIG_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/lib/pkgconfig
>     -DUSE_DOUBLE_PRECISION=ON
>     ${BULLET_EXTRA_CMAKE_ARGS})
> ```

I think the last line here is vestigial now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4242#-:-KXHAzJWLg8pWnWY_sT1:b-vo1d91)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4242#-KXHAtzLSpZAcAWm2nHS:-KXHBURmz10NztLB0lI7:b-gaify6) ([raw file](https://github.com/robotlocomotion/drake/blob/2e064d9cf75d55885130423dcfb0aa42ab24127d/CMakeLists.txt#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I think the last line here is vestigial now?
</details>
Yes. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4242)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4242)*

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4242#-:-KXHNBf5svegZKATRdtu:bnfp4nl)*

**Pull request merged**
