### PR TITLE
change to consistently use "breaks" instead of "segment_times".

### PR DESCRIPTION
**Pull request by RussTedrake**
the pp / pp trajectory classes use a mix of notation.  this is especially sensitive, since piecewise_function should not have any notion of time (while it would be ok for a trajectory).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5242)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@lucy-tri for feature review, please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-:-KdVnC45rX_Q-7u4UDC5:b-yxfyq)*

**Comment by Lucy-tri** [comment]
piecewise_function should not have any notion:  ok, that makes sense.  But you have left several vars and params that have "time" in the name, so those too should be renamed, I believe.

---

Reviewed 7 of 10 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/trajectories/piecewise_function.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-KdWFGjvcDURNknyeWC1:-KdWFGjvcDURNknyeWC2:b-c6mzyu) ([raw file](https://github.com/robotlocomotion/drake/blob/270852cd0f2689758681fb5f5fad7cd3fef61375/drake/common/trajectories/piecewise_function.h#L27)):*
> ```objc
>   int getNumberOfSegments() const;
> 
>   double getStartTime(int segment_number) const;
> ```

piecewise_function should not have any notion of time, but there are still plenty of methods like getStartTime() and params that have time in the name. I'm not sure what to call it instead of "time": just x?  

---

*[drake/common/trajectories/piecewise_function.h, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-KdWFfY-CiaoV_stFykY:-KdWFfY-CiaoV_stFykZ:bgwhf8y) ([raw file](https://github.com/robotlocomotion/drake/blob/270852cd0f2689758681fb5f5fad7cd3fef61375/drake/common/trajectories/piecewise_function.h#L56)):*
> ```objc
> 
>  private:
>   int GetSegmentIndexRecursive(double time, int start, int end) const;
> ```

Here is an arg called "time", which I suppose should have some different name. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-:-KdWGCWp3cVtM65QT-U0:b-krx0is)*

**Comment by Lucy-tri** [comment]
...notion *of time*, I meant to say

---

Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-:-KdWL4ACybs0h8H5pov9:b2mm64e)*

**Comment by Lucy-tri** [comment]
Reviewed 3 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242)*

**Comment by RussTedrake** [comment]
i agree.  further purging should happen going forward.  i felt these were ok to leave in for now.  Changing the API will take a slightly bigger PR, which I will do in pieces.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/trajectories/piecewise_function.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-KdWFGjvcDURNknyeWC1:-KdXmcIYzIOgNmN-J0En:b8owbh6) ([raw file](https://github.com/robotlocomotion/drake/blob/270852cd0f2689758681fb5f5fad7cd3fef61375/drake/common/trajectories/piecewise_function.h#L27)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

piecewise_function should not have any notion of time, but there are still plenty of methods like getStartTime() and params that have time in the name. I'm not sure what to call it instead of "time": just x?  
</blockquote></details>

future PR

---

*[drake/common/trajectories/piecewise_function.h, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-KdWFfY-CiaoV_stFykY:-KdXmda33mWdPvwqbJG6:b8owbh6) ([raw file](https://github.com/robotlocomotion/drake/blob/270852cd0f2689758681fb5f5fad7cd3fef61375/drake/common/trajectories/piecewise_function.h#L56)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

Here is an arg called "time", which I suppose should have some different name. 
</blockquote></details>

future PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-:-KdXmYj3U5CojJj3k2H2:b-4s2by3)*

**Comment by RussTedrake** [comment]
+@david-german-tri  , +@soonho-tri for platform review please

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-:-KdXmgprOrr9iO293Z2b:b-ci20sk)*

**Comment by Lucy-tri** [comment]
I think the direction this goes makes sense to me and is good, but it's incomplete without further changes; however, the incompleteness is harmless and actually improves things somewhat (making it more correct).  
:lgtm: 

---

Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-:-KdXo3Ob0vVT738WbwBn:b-sv8h67)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-:-KdY9F0Hdey3BvM7_SGj:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/piecewise_polynomial.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-KdYBm4dKV5oaGBrKvDD:-KdYBm4e2xg8HQFBgVMJ:bcjbodu) ([raw file](https://github.com/robotlocomotion/drake/blob/26179586a79ba515d542609fff6f1644790d9d71/drake/common/trajectories/piecewise_polynomial.cc#L2)):*
> ```cpp
> #include <algorithm>
> #include "drake/common/trajectories/piecewise_polynomial.h"
> ```

Per CPP Guide, https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes, we recommend:

```c++
#include "drake/common/trajectories/piecewise_polynomial.h"

#include <algorithm>

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-:-KdYCHBE42pG48mART4D:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/piecewise_polynomial.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-KdYBm4dKV5oaGBrKvDD:-KdYFCIbrfXqpgmgQXXw:b-1h39la) ([raw file](https://github.com/robotlocomotion/drake/blob/26179586a79ba515d542609fff6f1644790d9d71/drake/common/trajectories/piecewise_polynomial.cc#L2)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Per CPP Guide, https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes, we recommend:

```c++
#include "drake/common/trajectories/piecewise_polynomial.h"

#include <algorithm>

```

</blockquote></details>

Done.  fwiw - i didn't touch that line.  clang-format made that change.  sigh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242)*

**Comment by soonho-tri** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/common/trajectories/piecewise_polynomial.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5242#-KdYBm4dKV5oaGBrKvDD:-KdYGej6qh12gzrK2Juc:bv80924) ([raw file](https://github.com/robotlocomotion/drake/blob/26179586a79ba515d542609fff6f1644790d9d71/drake/common/trajectories/piecewise_polynomial.cc#L2)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  fwiw - i didn't touch that line.  clang-format made that change.  sigh.
</blockquote></details>

I think it's because there was no blank line between `piecewise_polynomial.h` and `algorithm` previously.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5242)*

**Pull request merged**
