### PR TITLE
Use test timeout instead of test size and various other timeout-related fixes

### LINKED ISSUE #8634: Tests should use timeout instead of size where appropriate
Looks like Bazel does some resource scheduling based on `size` for instance. We may also wish to profile the CPU, RAM, and I/O usage of the tests more thoroughly to assign appropriate sizes.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #8634.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8659)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by snape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
> @jamiesnape What do you think about a follow-up issue or PR to update drake/doc to explain the conventions that this PR is brining into alignment?

Yes, I was thinking about that too. I think there is also a follow up to create a `drake_sh_test` rather than adding `small` in quite so many places.

---

Review status: 45 of 49 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8659#-:-LAt6M6U-xKicavSG_Jp:bxrvg3h)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor comment on default test sizes for `cc_` rules, based on what we have for `py_` rules.

---

Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/skylark/drake_cc.bzl, line 508 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8659#-LAtA6fp4qExrFWDMC0s:-LAtA6fp4qExrFWDMC0t:bqqgil) ([raw file](https://github.com/robotlocomotion/drake/blob/b24b6c9b3dab5e2ceddfaf4d6e4816f9ac3b0a60/tools/skylark/drake_cc.bzl#L508)):*
> ```Python
>         use_default_main = True,
>         **kwargs):
>     """Creates a rule to declare a C++ unit test using googletest.
> ```

BTW Since we define a default timeout for Python unittests, should we do the same for `drake_cc_googletest`, as they generally imply unittest?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8659#-:-LAtAq3j1XWaPtt1Sn2H:bmih0ej)*

**Comment by jamiesnape** [comment]
Review status: 48 of 49 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/install.bzl, line 769 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8659#-LAt4X1u96KuzFff_b41:-LAtDU390AYI-TVdv6Pr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81219516a7347d58fd3ce2754282eacd198d3a75/tools/install/install.bzl#L769)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is an integration test (collects _all_ of the post-install tests as declared by the various install rules), and does lots of I/O.  Perhaps `size = "medium"` is a better semantic fit?
</blockquote></details>

Done.

---

*[tools/skylark/drake_cc.bzl, line 508 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8659#-LAtA6fp4qExrFWDMC0s:-LAtD5JZB7x6XrBmtoD6:b-55r3g9) ([raw file](https://github.com/robotlocomotion/drake/blob/b24b6c9b3dab5e2ceddfaf4d6e4816f9ac3b0a60/tools/skylark/drake_cc.bzl#L508)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Since we define a default timeout for Python unittests, should we do the same for `drake_cc_googletest`, as they generally imply unittest?
</blockquote></details>

BTW We already do, it is a `small` test, so `short` timeout since this wraps `drake_cc_test`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8659)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8659)*

**Pull request merged**
