### PR TITLE
Update support matrix

### PR DESCRIPTION
**Pull request by jamiesnape**
Formalizes the n, n-1 Mac version support, adds the Xenial MATLAB builds, removes the CMake minimal builds.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6980)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm: platform review and feature review except for OSX rows of the table.

+@soonho-tri for feature review of OSX rows of the table.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6980#-:-KtN_rvkO5wU6kpvwfRv:bbwyc1m)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/developers.rst, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6980#-KtNbKSSoeE0X91vX5MN:-KtNbKSSoeE0X91vX5MO:b-yy5ksu) ([raw file](https://github.com/robotlocomotion/drake/blob/0486ae823a747ebedbe8e96f857c12c9c7f0f066/drake/doc/developers.rst#L86)):*
> ```reStructuredText
> |                             | | CMake 3.5.1 | | GCC 5.4       |            |                   |        |
> +-----------------------------+---------------+-----------------+------------+-------------------+--------+
> | OS X 10.11 ("El Capitan")   | | Bazel 0.5.2 | Apple Clang 7.0 | Oracle 1.8 | Not Supported     | 2.7.13 |
> ```

FWIW, I've been using `bazel-0.5.4` (which is what we get `brew install bazel` as of 6 Sep 2017) without a problem. Can we update this entry? If not, to be consistent with this document, we need to update `setup/mac/install_prereqs.sh` to install the specific `bazel-0.5.2`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6980)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6980#-:-KtNcS7vg0B722ZyyL2C:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/developers.rst, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6980#-KtNbKSSoeE0X91vX5MN:-KtNcK1ntEbKOt2NTkIg:b-x6ly5r) ([raw file](https://github.com/robotlocomotion/drake/blob/0486ae823a747ebedbe8e96f857c12c9c7f0f066/drake/doc/developers.rst#L86)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FWIW, I've been using `bazel-0.5.4` (which is what we get `brew install bazel` as of 6 Sep 2017) without a problem. Can we update this entry? If not, to be consistent with this document, we need to update `setup/mac/install_prereqs.sh` to install the specific `bazel-0.5.2`.
</blockquote></details>

This documents the configuration used by CI which is pinned to 0.5.2. Installing a specific version means maintaining another set of bottles, which I would rather not do unless we run into specific issues.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6980)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/developers.rst, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6980#-KtNbKSSoeE0X91vX5MN:-KtNd92O8ZYw2nVsc3XU:bdpqx73) ([raw file](https://github.com/robotlocomotion/drake/blob/0486ae823a747ebedbe8e96f857c12c9c7f0f066/drake/doc/developers.rst#L86)):*
> which is pinned to 0.5.2.

Great. Thank you for the note!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6980)*

**Pull request merged**
