### PR TITLE
sensors::Image: Define a series of specific image types

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Defines a series of specific image types.

This change is beneficial because:
 (a) each image type will have clear semantic meanings so we can avoid unnecessary confusion and,
 (b) you won't need to pass the number of channel to Image's ctor when instantiating it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6107)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@ericcousineau-tri feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-:-KkDWn4Gc9w_eHDInOJp:b-6wg1k9)*

**Comment by EricCousineau-TRI** [comment]
*[drake/systems/sensors/image.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkDa7Eg_niWZbX6mSi7:-KkDa7Eh86JPcOojOxvA:b-3aiap9) ([raw file](https://github.com/robotlocomotion/drake/blob/c117dcd46b87e5cdac07b5acada5ebb6d5fb8b30/drake/systems/sensors/image.h#L43)):*
> ```objc
> 
> // Forward declaration of Image.
> template <typename T, int channel, PixelFormat pixelformat> class Image;
> ```

Looks good! Only thing is, it seems like this API may permit redundant / erroneous definitions, e.g.:

```c++
Image<uint8_t, 10, PixelFormat::kDepth32F> my_bad_image;
```

Would it be possible to store this in some sort of detail / traits class?
```c++
template<PixelFormat>
struct ImageTraits;

template<>
struct ImageTraits<kRgb8U> {
  typedef uint8_t ChannelType; // or just T
  static inline constexpr int channel = 3;
};

using ImageRgb8U = Image<ImageTraits<kRgb8U>>;

template <typename Traits>
class Image {
   // Convenience
   using T = typename Traits::ChannelType;
   static inline constexpr int channel = Trait::channel;
};
```

Templating on `ImageTraits` rather than `PixelFormat` could permit user-customization (if that is seen as applicable); however, `PixelFormat` could be used if there is no need for extension.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107)*

**Comment by EricCousineau-TRI** [comment]
*[drake/systems/sensors/image.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkDa7Eg_niWZbX6mSi7:-KkDcM_Y3NSnC-uYqJHo:b-tpwbxm) ([raw file](https://github.com/robotlocomotion/drake/blob/c117dcd46b87e5cdac07b5acada5ebb6d5fb8b30/drake/systems/sensors/image.h#L43)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Looks good! Only thing is, it seems like this API may permit redundant / erroneous definitions, e.g.:

```c++
Image<uint8_t, 10, PixelFormat::kDepth32F> my_bad_image;
```

Would it be possible to store this in some sort of detail / traits class?
```c++
template<PixelFormat>
struct ImageTraits;

template<>
struct ImageTraits<kRgb8U> {
  typedef uint8_t ChannelType; // or just T
  static inline constexpr int channel = 3;
};

using ImageRgb8U = Image<ImageTraits<kRgb8U>>;

template <typename Traits>
class Image {
   // Convenience
   using T = typename Traits::ChannelType;
   static inline constexpr int channel = Trait::channel;
};
```

Templating on `ImageTraits` rather than `PixelFormat` could permit user-customization (if that is seen as applicable); however, `PixelFormat` could be used if there is no need for extension.
</blockquote></details>

(Granted, templating on `ImageTraits` could also permit erroneous definitions, but at least at that point, it is solely the user's responsibility, rather than being able to specify conflicting traits w.r.t. the `PixelFormat`.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/image.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkDa7Eg_niWZbX6mSi7:-KkGSvowMkVSw5wwz2R_:b-9j5aul) ([raw file](https://github.com/robotlocomotion/drake/blob/c117dcd46b87e5cdac07b5acada5ebb6d5fb8b30/drake/systems/sensors/image.h#L43)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

(Granted, templating on `ImageTraits` could also permit erroneous definitions, but at least at that point, it is solely the user's responsibility, rather than being able to specify conflicting traits w.r.t. the `PixelFormat`.)
</blockquote></details>

Cool! Thanks for the suggestion. I'll change accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107)*

**Comment by kunimatsu-tri** [comment]
Addressed your comment. PTAL.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/image.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkDa7Eg_niWZbX6mSi7:-KkGgSHjKpZwJL1CJDH6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c117dcd46b87e5cdac07b5acada5ebb6d5fb8b30/drake/systems/sensors/image.h#L43)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Cool! Thanks for the suggestion. I'll change accordingly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-:-KkGgT2Sodjxqz8wlG9z:b-6y79zr)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 5 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/image.h, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkGjRH2d0sGDZ8kyzW-:-KkGjRH2d0sGDZ8kyzW0:b-dwsd98) ([raw file](https://github.com/robotlocomotion/drake/blob/90f39e4d45dabea42c29d3a8f79dea979f0ced60/drake/systems/sensors/image.h#L51)):*
> ```objc
> ///
> /// @tparam Traits The traits class that contains channel type and the number of
> /// channel for Image.
> ```

nit Grammar `s/channel/channels/`

---

*[drake/systems/sensors/image.h, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkGolD3B-n1BDsz692g:-KkGolD3B-n1BDsz692h:bsiwdyb) ([raw file](https://github.com/robotlocomotion/drake/blob/90f39e4d45dabea42c29d3a8f79dea979f0ced60/drake/systems/sensors/image.h#L137)):*
> ```objc
>   reinit_after_move<int> height_;
>   std::vector<T> data_;
>   static constexpr int channel_ = Traits::channel;
> ```

Per naming below, should also be something to the effect of:
```c++
static constexpr int kNumChannels = Traits::kNumChannels;
```

Also, would it make sense to make this public, since it is effectively an alias?

---

*[drake/systems/sensors/image_traits.h, line 85 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkGoMPRgQwXcBCBfPg-:-KkGoMPRgQwXcBCBfPg0:baq5b8s) ([raw file](https://github.com/robotlocomotion/drake/blob/90f39e4d45dabea42c29d3a8f79dea979f0ced60/drake/systems/sensors/image_traits.h#L85)):*
> ```objc
> struct ImageTraits<PixelFormat::kGrey8U> {
>   typedef uint8_t ChannelType;
>   static constexpr int channel = 1;
> ```

Sorry I didn't catch this earlier, but should this be named [as a constant](https://google.github.io/styleguide/cppguide.html#Constant_Names)?
```c++
static constexpr int kNumChannels = 1;
```
Same for other instances.

---

*[drake/systems/sensors/test/image_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkGjkvu3u6B5sZSzuKF:-KkGjkvvfm1-JA1sgZY_:b-6g03uu) ([raw file](https://github.com/robotlocomotion/drake/blob/c117dcd46b87e5cdac07b5acada5ebb6d5fb8b30/drake/systems/sensors/test/image_test.cc#L20)):*
> ```cpp
>   EXPECT_EQ(dut.size(), 0);
>   EXPECT_EQ(dut.num_channels(), 3);
>   EXPECT_EQ(dut.pixel_format(), PixelFormat::kRgb8U);
> ```

Might there still be a way to check at run-time (or even compile-time) to see what `ImageType` something is? As it stands, it seems the information in `ImageTraits<>` is not completely descriptive, in that it does not provide details on how the channels are interpreted (aside from somehow extracting the `enum` type).

This does prevent customization in the future (unless you can change the underlying `enum` type), so maybe it would be better to go the route of:
```c++
template <PixelFormat kPixelFormat>
class Image {
  using Traits = ImageTraits<kPixelFormat>;
...
  PixelFormat pixel_format() { return kPixelFormat; }
};
```

(Sorry for the back-and-forth!)

Also, I am checking to see what the right standards are for POD template parameters. My gut says it should reflect being a constant, thus `kPixelFormat`, but will check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107)*

**Comment by EricCousineau-TRI** [comment]
*[drake/systems/sensors/test/image_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkGjkvu3u6B5sZSzuKF:-KkGrFX0r0QEGgcK0fcq:b-a71wls) ([raw file](https://github.com/robotlocomotion/drake/blob/c117dcd46b87e5cdac07b5acada5ebb6d5fb8b30/drake/systems/sensors/test/image_test.cc#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Might there still be a way to check at run-time (or even compile-time) to see what `ImageType` something is? As it stands, it seems the information in `ImageTraits<>` is not completely descriptive, in that it does not provide details on how the channels are interpreted (aside from somehow extracting the `enum` type).

This does prevent customization in the future (unless you can change the underlying `enum` type), so maybe it would be better to go the route of:
```c++
template <PixelFormat kPixelFormat>
class Image {
  using Traits = ImageTraits<kPixelFormat>;
...
  PixelFormat pixel_format() { return kPixelFormat; }
};
```

(Sorry for the back-and-forth!)

Also, I am checking to see what the right standards are for POD template parameters. My gut says it should reflect being a constant, thus `kPixelFormat`, but will check.
</blockquote></details>

If you wanted, you could keep the existing structure and extract the parameter constant:
https://github.com/EricCousineau-TRI/repro/blob/7981ea0/cpp_quick/tpl_tpl_pod.cc#L13
However, I think this is less optimal, as it (a) also constrains form of `Traits` to be templated, and (b) may muddle the waters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107)*

**Comment by kunimatsu-tri** [comment]
Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/image.h, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkGjRH2d0sGDZ8kyzW-:-KkHG0PDLJs1OmjdRAin:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90f39e4d45dabea42c29d3a8f79dea979f0ced60/drake/systems/sensors/image.h#L51)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Grammar `s/channel/channels/`
</blockquote></details>

Done.

---

*[drake/systems/sensors/image.h, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkGolD3B-n1BDsz692g:-KkHFJKEIYG1ktYkt1Cd:baeoy0b) ([raw file](https://github.com/robotlocomotion/drake/blob/90f39e4d45dabea42c29d3a8f79dea979f0ced60/drake/systems/sensors/image.h#L137)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Per naming below, should also be something to the effect of:
```c++
static constexpr int kNumChannels = Traits::kNumChannels;
```

Also, would it make sense to make this public, since it is effectively an alias?
</blockquote></details>

Yeah, after changing `channel_`  to `kNumChannels`, it makes sense to make this public.

---

*[drake/systems/sensors/test/image_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkGjkvu3u6B5sZSzuKF:-KkHba4svzumJY7D3Svy:bnceiqv) ([raw file](https://github.com/robotlocomotion/drake/blob/c117dcd46b87e5cdac07b5acada5ebb6d5fb8b30/drake/systems/sensors/test/image_test.cc#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

If you wanted, you could keep the existing structure and extract the parameter constant:
https://github.com/EricCousineau-TRI/repro/blob/7981ea0/cpp_quick/tpl_tpl_pod.cc#L13
However, I think this is less optimal, as it (a) also constrains form of `Traits` to be templated, and (b) may muddle the waters.
</blockquote></details>

Done in a different way.

---

*[drake/systems/sensors/image_traits.h, line 85 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkGoMPRgQwXcBCBfPg-:-KkHEcdhmsy_WFrZw9N6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90f39e4d45dabea42c29d3a8f79dea979f0ced60/drake/systems/sensors/image_traits.h#L85)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Sorry I didn't catch this earlier, but should this be named [as a constant](https://google.github.io/styleguide/cppguide.html#Constant_Names)?
```c++
static constexpr int kNumChannels = 1;
```
Same for other instances.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, aside from minor BTW and build failures.
Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-:-KkLvVfqKSVn6_iHvH6a:b-yuxlw7)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/sensors/test/image_test.cc, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkLv8B_kg_8GE2TIWaR:-KkLv8B_kg_8GE2TIWaS:bqzijw7) ([raw file](https://github.com/robotlocomotion/drake/blob/74376ca63e486cd8cbaf229b1dda5f7283eac5f0/drake/systems/sensors/test/image_test.cc#L21)):*
> ```cpp
>   EXPECT_EQ(dut.size(), 0);
>   EXPECT_EQ(dut.kNumChannels, 3);
>   EXPECT_EQ(dut.kPixelFormat, PixelFormat::kRgb);
> ```

BTW Not sure if is standard to refer to a static class field via member access, but I will defer this to the platform reviewer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107)*

**Comment by kunimatsu-tri** [comment]
+@ggould-tri platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-:-KkMMzB0dn2Jtr3uxbrC:bdmqfp3)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/test/image_test.cc, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkLv8B_kg_8GE2TIWaR:-KkMWaaXWeFP28-H__zp:b-skcnw6) ([raw file](https://github.com/robotlocomotion/drake/blob/74376ca63e486cd8cbaf229b1dda5f7283eac5f0/drake/systems/sensors/test/image_test.cc#L21)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Not sure if is standard to refer to a static class field via member access, but I will defer this to the platform reviewer.
</blockquote></details>

This is legal if rare.  It is more common in tests where it is idiomatic to get to everything via `dut`.  It can cause errors with inheritance (fields are never virtual!) but that is not the case here.

lgtm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-:-KkMYaoSr-21za_fnRK9:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/test/image_test.cc, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6107#-KkLv8B_kg_8GE2TIWaR:-KkMdvlXdwFytuR3VjRS:bktko55) ([raw file](https://github.com/robotlocomotion/drake/blob/74376ca63e486cd8cbaf229b1dda5f7283eac5f0/drake/systems/sensors/test/image_test.cc#L21)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This is legal if rare.  It is more common in tests where it is idiomatic to get to everything via `dut`.  It can cause errors with inheritance (fields are never virtual!) but that is not the case here.

lgtm
</blockquote></details>

Thank you both. After reading the comments from you two, I'm now feeling like it's safer to hide these const variables behind getters than the bare use for the changes in the future. Maybe I'll do it in a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6107)*

**Pull request merged**
