### PR TITLE
[fem] Move matrix utilities out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Follow up of #16508.
Towards #16492.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16509)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for feature to finish up this mini PR train.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16509#-:-MvK9ZgN96B7IPR8iikm:bwhf3c1)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:
+@jwnimmer-tri for platform review per rotation, please

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16509#-:-MvKNnW74Lf0cs53bTuu:b-blmt2e)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
@jwnimmer-tri notice that this PR is a move out of dev and requires a full review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16509#-:-MvKRU3D4qud4JoobCva:b-68js8s)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform (on non-dev files).

> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16509#-:-MvKtWHn7PIZMb3qWRva:bmjvhx6)* status: 11 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fem/matrix_utilities.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKWamZB7OmBLmOjfKR:-MvKWamZB7OmBLmOjfKS:b-gqf6fn) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L14)):*
> ```objc
> namespace internal {
> 
> /* Some of the following methods involve calculations about a 4th order tensor
> ```

nit I assume this text is referring to "methods" as in code, rather than "methods" as in methodology?  If so, then the correct noun is "function".  There is no such thing as "method" in C++, and certainly using "method" to refer to free functions rather than member functions with an implicit `this` is misleading, even informally.



_Suggestion:_
```objc
functions
```
___
*[multibody/fem/matrix_utilities.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKXG6n3Ps73Opyfx8i:-MvKXG6n3Ps73Opyfx8j:b-ydxoce) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L40)):*
> ```objc
>  of A.
>  @note This function is intended to be used for testing and may be slow on large
>  matrices.
> ```

If its only objective is only for testing, should it be placed inside a separate test library target (with `testonly = True` in Bazel), rather than part of our production code?  Mixing testing code with production code in the same header makes it more difficult for developers to keep track of what's supposed to be used where.

Alternatively, if there are plausible production uses for this function (within some smallish size), instead of saying "for testing" we could give a rough estimate of what sizes this is good for (and not mention testing).
___
*[multibody/fem/matrix_utilities.h, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKYbXc6Hcxxqc4x7lq:-MvKYbXc6Hcxxqc4x7lr:b9tcdkz) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L52)):*
> ```objc
>  @tparam_nonsymbolic_scalar */
> template <typename T>
> void PolarDecompose(const Matrix3<T>& F, EigenPtr<Matrix3<T>> R,
> ```

nit By using the type `const Matrix3<T>&` directly here, any users that have only a 3x3 block (or similar kind of view) will induce a copy during the function call.  If there are ever any performance-sensitive callers that won't already have a `Matrix3<T>` exactly already in memory, consider using `Ref<>` here to avoid extra copies.

Ditto throughout the PR (for any matrices that are inputs).



_Suggestion:_
```objc
const Eigen::Ref<const Matrix3<T>>& F
```
___
*[multibody/fem/matrix_utilities.h, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKXnPFCScPJzYQizlM:-MvKXnPFCScPJzYQizlN:b-f1amco) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L55)):*
> ```objc
>                     EigenPtr<Matrix3<T>> S);
> 
> /* Some notes on derivation on the derivative of the rotation matrix from polar
> ```

Is the text appropriate for the header?  As it reads to me, it's describing the implementation technique found in the cc file, and a typical user who would be calling `AddScaledRotationalDerivative` has no need to wade through this derivation?

Or, if there is some element of this text that's important for the API docs on that function, then perhaps this text should be within the function API comment directly, instead?
___
*[multibody/fem/matrix_utilities.h, line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKli-M9guxJvx271F5:-MvKli-M9guxJvx271F6:bma8fnw) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L89)):*
> ```objc
>  @param[in] S            The symmetric matrix in the polar decomposition F = RS.
>  @param[in] scale        The scalar multiple of the result.
>  @param[out] scaled_dRdF The variable to which scale * dR/dF is added.
> ```

The meaning of `param[out]` is that the output argument is always fully overwritten.  In cases where it is merely modified (i.e., where the input value affects the computation in some way), we need to say `in,out` to make that clear.



_Suggestion:_
```objc
@param[in,out]
```
___
*[multibody/fem/matrix_utilities.h, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKlJvfB1ADmKLHVGL6:-MvKlJvfB1ADmKLHVGL7:b-ruw9ow) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L108)):*
> ```objc
>  @param[in] M            The input matrix.
>  @param[in] scale        The scalar multiple of the result.
>  @param[out] scaled_dCdF The variable to which scale * dC/dM is added.
> ```

nit Ditto.



_Suggestion:_
```objc
@param[in,out]
```
___
*[multibody/fem/matrix_utilities.h, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKmxJf9c4_7NnxQOAS:-MvKmxJf9c4_7NnxQOAT:bm0iuim) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L117)):*
> ```objc
> 
> /* Given a size 3N vector with block structure with size 3 block entries Bᵢ
>  where i ∈ V = {0, ..., N-1} and a permutation P on V, this method builds the
> ```

nit Ditto



_Suggestion:_
```objc
function
```
___
*[multibody/fem/matrix_utilities.cc, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKpejN3aWO0aAGZyVD:-MvKpejN3aWO0aAGZyVE:b-t77pb) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.cc#L20)):*
> ```cpp
>   const VectorX<T>& sigma = svd.singularValues();
>   /* Prevents division by zero for singular matrix. */
>   const T& sigma_min = sigma(sigma.size() - 1);
> ```

nit Possibly `@pre A is invertible` already guards this sufficiently, but here we could possibly be reading out-of-bounds of `sigma` if its empty?  That'd already be checked in Debug builds (by Eigen itself), but we could `DRAKE_DEMAND(sigma.size() > 0);` here also if it seemed worthwhile, even in Release?
___
*[multibody/fem/matrix_utilities.cc, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKq5PA0HFVLtxRgCGx:-MvKq5PB--CCOw5KKEjD:b-mif5bv) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.cc#L24)):*
> ```cpp
>   const T& sigma_max = sigma(0);
>   const T cond = sigma_max / sigma_min;
>   return ExtractDoubleOrThrow(cond);
> ```

nit I'm not sure whether it matter, but for `T = AutoDiffXd` this function is wasting a lot of math computing the derivatives, only to throw them away at the end.

If that performance tune-up is important, then one solution would be to only accept double-valued `A` in the first place to _force_ the caller to discard the derivatives before calling us.  That is probably best (in my opinion).

Alternatively, we could return a `T` here and let the caller cast away the derivatives of that result in case they wanted to.  That might encourage _them_ to pass only the double-valued `A` because the return-cast would show up in their calling code, making the types-mismatch clear.

Or, maybe just a TODO if you have no interested in AutoDiffXd performance at the moment.
___
*[multibody/fem/matrix_utilities.cc, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKnF0h4QxdwzjtW8xr:-MvKnF0h4QxdwzjtW8xs:bjtyx1l) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.cc#L147)):*
> ```cpp
>     (&CalcConditionNumberOfInvertibleMatrix<T>, &PolarDecompose<T>,
>      &AddScaledRotationalDerivative<T>, &CalcCofactorMatrix<T>,
>      &AddScaledCofactorMatrixDerivative<T>, &PermuteBlockVector<T>))
> ```

nit This list would be easier to visually compare and maintain over time vs the function bodies defined above if it had only one function name per line (and thus, probably "clang-format off" or "// BR" markers, if your editor is aggressively reformatting).
___
*[multibody/fem/test/matrix_utilities_test.cc, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKrwS37mBHqSePF5HM:-MvKrwS37mBHqSePF5HN:b6vta7x) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/test/matrix_utilities_test.cc#L23)):*
> ```cpp
>   for (int i = 0; i < rows; ++i) {
>     for (int j = 0; j < cols; ++j) {
>       A(i, j) = cols * i + j;
> ```

nit This has a zero in the upper left cell.  Does that turn into any kind of special-case in the math that would defeat the test cases?  Possibly `+ 1` here would help mitigate.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16509)* status: 6 unresolved discussions (waiting on @jwnimmer-tri and @sherm1)

___
*[multibody/fem/matrix_utilities.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKWamZB7OmBLmOjfKR:-MvL0DCiCjowAvjLScuj:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I assume this text is referring to "methods" as in code, rather than "methods" as in methodology?  If so, then the correct noun is "function".  There is no such thing as "method" in C++, and certainly using "method" to refer to free functions rather than member functions with an implicit `this` is misleading, even informally.
</blockquote></details>

Done, thanks!
___
*[multibody/fem/matrix_utilities.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKXG6n3Ps73Opyfx8i:-MvLJfqh2Fcw-kgfRAdu:blparpk) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If its only objective is only for testing, should it be placed inside a separate test library target (with `testonly = True` in Bazel), rather than part of our production code?  Mixing testing code with production code in the same header makes it more difficult for developers to keep track of what's supposed to be used where.

Alternatively, if there are plausible production uses for this function (within some smallish size), instead of saying "for testing" we could give a rough estimate of what sizes this is good for (and not mention testing).
</blockquote></details>

I reworded. Instead of giving an estimate on the size, I added a link to the Eigen benchmark. The caller can decide if the performance is adequate enough.
___
*[multibody/fem/matrix_utilities.h, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKYbXc6Hcxxqc4x7lq:-MvLKbQl7A5fWd8lxPIL:b-8vw1cl) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit By using the type `const Matrix3<T>&` directly here, any users that have only a 3x3 block (or similar kind of view) will induce a copy during the function call.  If there are ever any performance-sensitive callers that won't already have a `Matrix3<T>` exactly already in memory, consider using `Ref<>` here to avoid extra copies.

Ditto throughout the PR (for any matrices that are inputs).
</blockquote></details>

Is there any overhead of putting the Eigen::Ref<> wrapper? I remember learning that there's a small overhead, and I'd like to avoid that. These functions gets called in tight inner loops.
___
*[multibody/fem/matrix_utilities.h, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKXnPFCScPJzYQizlM:-MvLLzem2CfiFAXYCXvD:b-5wcwbj) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is the text appropriate for the header?  As it reads to me, it's describing the implementation technique found in the cc file, and a typical user who would be calling `AddScaledRotationalDerivative` has no need to wade through this derivation?

Or, if there is some element of this text that's important for the API docs on that function, then perhaps this text should be within the function API comment directly, instead?
</blockquote></details>

Done. I moved this to the cc file.
___
*[multibody/fem/matrix_utilities.h, line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKli-M9guxJvx271F5:-MvLMr1MD9c-a3dYIXQ9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The meaning of `param[out]` is that the output argument is always fully overwritten.  In cases where it is merely modified (i.e., where the input value affects the computation in some way), we need to say `in,out` to make that clear.
</blockquote></details>

Done.
___
*[multibody/fem/matrix_utilities.h, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKlJvfB1ADmKLHVGL6:-MvLMs1c0z0y9zbx9i9X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Ditto.
</blockquote></details>

Done.
___
*[multibody/fem/matrix_utilities.h, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKmxJf9c4_7NnxQOAS:-MvLMtAC2P-ujWseNmRU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Ditto
</blockquote></details>

Done.
___
*[multibody/fem/matrix_utilities.cc, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKpejN3aWO0aAGZyVD:-MvLNAsH8_EpE6gP94Nu:b56e9pc) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.cc#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Possibly `@pre A is invertible` already guards this sufficiently, but here we could possibly be reading out-of-bounds of `sigma` if its empty?  That'd already be checked in Debug builds (by Eigen itself), but we could `DRAKE_DEMAND(sigma.size() > 0);` here also if it seemed worthwhile, even in Release?
</blockquote></details>

Good catch. Done, thanks.
___
*[multibody/fem/matrix_utilities.cc, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKq5PA0HFVLtxRgCGx:-MvLNvPK8bFyqOMZLKs_:b-1o5meb) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.cc#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm not sure whether it matter, but for `T = AutoDiffXd` this function is wasting a lot of math computing the derivatives, only to throw them away at the end.

If that performance tune-up is important, then one solution would be to only accept double-valued `A` in the first place to _force_ the caller to discard the derivatives before calling us.  That is probably best (in my opinion).

Alternatively, we could return a `T` here and let the caller cast away the derivatives of that result in case they wanted to.  That might encourage _them_ to pass only the double-valued `A` because the return-cast would show up in their calling code, making the types-mismatch clear.

Or, maybe just a TODO if you have no interested in AutoDiffXd performance at the moment.
</blockquote></details>

Done via TODO.
___
*[multibody/fem/matrix_utilities.cc, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKnF0h4QxdwzjtW8xr:-MvLOJzW9RojF9VoTM6h:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.cc#L147)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This list would be easier to visually compare and maintain over time vs the function bodies defined above if it had only one function name per line (and thus, probably "clang-format off" or "// BR" markers, if your editor is aggressively reformatting).
</blockquote></details>

Done, thanks.
___
*[multibody/fem/test/matrix_utilities_test.cc, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKrwS37mBHqSePF5HM:-MvLOfc46f7CmOlp_Y_F:blbghwv) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/test/matrix_utilities_test.cc#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This has a zero in the upper left cell.  Does that turn into any kind of special-case in the math that would defeat the test cases?  Possibly `+ 1` here would help mitigate.
</blockquote></details>

It'd only be a special case if the matrix is 1-by-1, but I added a `+1` any way. Thanks for the suggestion.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16509)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

___
*[multibody/fem/matrix_utilities.h, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16509#-MvKYbXc6Hcxxqc4x7lq:-MvLZDUF03aEiu3dcsp1:b-heobjt) ([raw file](https://github.com/robotlocomotion/drake/blob/6eff57663e628e18613a81b27d21567abf258cde/multibody/fem/matrix_utilities.h#L52)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is there any overhead of putting the Eigen::Ref<> wrapper? I remember learning that there's a small overhead, and I'd like to avoid that. These functions gets called in tight inner loops.
</blockquote></details>

OK Yes, I think there is a very small overhead for `Ref`.  If the important callers already have `Matrix3<T>` in hand, then using that literally (as is already here) is the best spelling.

**Pull request merged**
