### PR TITLE
[fem] Prepare matrix utilities to move out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
- Remove unused PermuteBlockSparseMatrix.
- Move CalcConditionNumber to matrix_utilities.h/cc

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16508)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for sole review please. 
This is the first PR of fix-and-move "matrix_utilities.h/cc" out of dev. This PR is the "fix" part. #16509 is the "move" part.
-(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16508#-:-Mv0xuBu1Fc-AatKdqJ5:bovkihm)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm: with minor change discussed f2f

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16508#-:-Mv13ulS3u5rfhRLhZG6:bet59cv)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16508#-Mv123I13zFxu39AmUwR:-Mv123I13zFxu39AmUwS:b46w56k) ([raw file](https://github.com/robotlocomotion/drake/blob/3106ceb65b2ae6f02d190ee95a552d5f1bb151a6/multibody/fixed_fem/dev/matrix_utilities.h#L41)):*
> ```objc
>  @note This function is intended to be used for testing and may be slow on large
>  matrices.
>  @pre A is invertible.
> ```

minor: per f2f the routine currently calculates condition number correctly for any matrix of any shape except one that is all zero in which case it returns NaN rather than Inf. If you only want the contract to allow for square invertible matrices, consider renaming the method something more like
`CalcConditionNumberOfInvertibleMatrix()` ? Or at least add some comments.
___
*[multibody/fixed_fem/dev/matrix_utilities.cc, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16508#-Mv12vETC1TpWv2bTdfV:-Mv12vETC1TpWv2bTdfW:b-86nyjc) ([raw file](https://github.com/robotlocomotion/drake/blob/3106ceb65b2ae6f02d190ee95a552d5f1bb151a6/multibody/fixed_fem/dev/matrix_utilities.cc#L21)):*
> ```cpp
>   DRAKE_DEMAND(sigma_min > 0);
>   const T& sigma_max = sigma(0);
>   const T cond = sigma_max / sigma_min;
> ```

BTW per f2f NaN only if max=min=0, should be Inf in that case for a method that is supposed to handle any matrix, not a problem if the method is restricted.
___
*[multibody/fixed_fem/dev/test/matrix_utilities_test.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16508#-Mv13lxC-jhQwx-1giZj:-Mv13lxD-DAB46w2BuAb:bs5gvyi) ([raw file](https://github.com/robotlocomotion/drake/blob/3106ceb65b2ae6f02d190ee95a552d5f1bb151a6/multibody/fixed_fem/dev/test/matrix_utilities_test.cc#L47)):*
> ```cpp
> GTEST_TEST(MatrixUtilitiesTest, CalcConditionNumber) {
>   const Matrix3<double> A = Vector3<double>(1, 2, 3).asDiagonal();
>   EXPECT_DOUBLE_EQ(CalcConditionNumber<double>(A), 3);
> ```

BTW consider modifying the method to insist on a square matrix and add a test to make sure it barfs appropriately.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16508)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform), exempt from platform review (waiting on @sherm1)

___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16508#-Mv123I13zFxu39AmUwR:-Mv1IX1VAA3tU0RxLHnC:byfc4hw) ([raw file](https://github.com/robotlocomotion/drake/blob/3106ceb65b2ae6f02d190ee95a552d5f1bb151a6/multibody/fixed_fem/dev/matrix_utilities.h#L41)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: per f2f the routine currently calculates condition number correctly for any matrix of any shape except one that is all zero in which case it returns NaN rather than Inf. If you only want the contract to allow for square invertible matrices, consider renaming the method something more like
`CalcConditionNumberOfInvertibleMatrix()` ? Or at least add some comments.
</blockquote></details>

Done. I opted to restrict to square matrices as the main usage of this function is to scale tolerance right now, and infinity is probably a bad value for tolerance.
___
*[multibody/fixed_fem/dev/test/matrix_utilities_test.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16508#-Mv13lxC-jhQwx-1giZj:-Mv1JF3w1KehUPb2_wgb:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/3106ceb65b2ae6f02d190ee95a552d5f1bb151a6/multibody/fixed_fem/dev/test/matrix_utilities_test.cc#L47)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider modifying the method to insist on a square matrix and add a test to make sure it barfs appropriately.
</blockquote></details>

Done, thanks.

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16508#-Mv5-5dm-LPkkOOhDVL1:-Mv5-5dm-LPkkOOhDVL2:b-wa7qs) (no related file):*
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please.

---

**Review by sherm1 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16508)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform), exempt from platform review (waiting on @xuchenhan-tri)

**Pull request merged**
