### PR TITLE
Support standalone developer tools install on Mac

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6662)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6662#-:-KpvdqCXSZhAUVBfqI2T:bnfp4nl)*

**Pull request merged**
