### PR TITLE
Do not compile ospray binaries with -ffast-math enabled

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #10253.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10262)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Patch applied to ospray version 3.2.0.

```diff
diff --git a/components/ospcommon/cmake/gcc.cmake b/components/ospcommon/cmake/gcc.cmake
index 3463cd075..6b1c67130 100644
--- a/components/ospcommon/cmake/gcc.cmake
+++ b/components/ospcommon/cmake/gcc.cmake
@@ -30,8 +30,8 @@ ENDIF()
 
 SET(CMAKE_CXX_FLAGS "${OSPRAY_CXX_FLAGS} ${CMAKE_CXX_FLAGS}")
 SET(CMAKE_CXX_FLAGS_DEBUG          "-DDEBUG  -g     -Wstrict-aliasing=1")
-SET(CMAKE_CXX_FLAGS_RELEASE        "-DNDEBUG    -O3 -Wstrict-aliasing=1 -ffast-math -fno-finite-math-only ")
-SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-DNDEBUG -g -O3 -Wstrict-aliasing=1 -ffast-math -fno-finite-math-only ")
+SET(CMAKE_CXX_FLAGS_RELEASE        "-DNDEBUG    -O3 -Wstrict-aliasing=1 -fno-finite-math-only ")
+SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-DNDEBUG -g -O3 -Wstrict-aliasing=1 -fno-finite-math-only ")
 SET(CMAKE_C_FLAGS "-std=c99 ${CMAKE_C_FLAGS}")
 
 IF (APPLE)
diff --git a/components/ospcommon/cmake/ispc.cmake b/components/ospcommon/cmake/ispc.cmake
index 7d02f37c2..12f91aacd 100644
--- a/components/ospcommon/cmake/ispc.cmake
+++ b/components/ospcommon/cmake/ispc.cmake
@@ -186,7 +186,6 @@ MACRO (OSPRAY_ISPC_COMPILE)
       ${ISPC_OPT_FLAGS}
       --target=${ISPC_TARGET_ARGS}
       --woff
-      --opt=fast-math
       ${ISPC_ADDITIONAL_ARGS}
       -h ${ISPC_TARGET_DIR}/${fname}_ispc.h
       -MMM  ${outdir}/${fname}.dev.idep
```

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review and local testing of Drake Visualizer (Bionic and Xenial. +@soonho-tri for local testing of Drake Visualizer (Mac).

**Comment by sherm1** [comment]
@jamiesnape are you sure this is necessary? It is only the link-time setting of the "DAZ" fp mode that causes us trouble. The change here also affects the instruction selection when ospray is compiled which they may have chosen for good reason.

**Comment by sherm1** [comment]
(Ospray is _very_ slow already -- would hate to see it slowed down further if it isn't necessary.)

**Comment by jamiesnape** [comment]
I'm only following instructions. Personally, I would have thought not.

**Comment by EricCousineau-TRI** [comment]
Is it relatively easy to specify `-ffast-math` for compilation flags, but strip it out of linking flags?

**Comment by jamiesnape** [comment]
It is not specified explicitly for linker flags. I will have to look up the GCC docs to find out how it gets added.

**Comment by jamiesnape** [comment]
Qt version was bumped. Sorry.

**Comment by jamiesnape** [comment]
I don't have an answer to the linker question (yet), but which of the flags that `-ffast-math` enables is causing the issue here (`-fno-math-errno`, `-funsafe-math-optimizations`, <s>`-ffinite-math-only`</s> (ospray disables this), `-fno-rounding-math`, `-fno-signaling-nans`, or `-fcx-limited-range` are the choices)?

**Comment by sherm1** [comment]
I looked at each of those flags and _none_ of them seem to control denormalized numbers. That's a floating point mode rather than a compiler switch so has to be set at run time. I assume the linker swallows the `-ffast-math` flag and generates a call to `set_fast_math()` in the .so startup code, but I couldn't find anything in `man ld` that referred to that :(

**Comment by jwnimmer-tri** [comment]
Which per something like https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/gcc/config/i386/gnu-user-common.h#L48-L53 pulls in `crtfastmath.o` which has an `attribute((constructor))` on `set_fast_math`.

**Comment by sherm1** [comment]
That bug was initially filed in 2012! So I guess we shouldn't be expecting a fix any time soon.

As best I can tell the only run time fp modes that get hacked are the two flags that affect denormalized number behavior (DAZ and FTZ). [Here](https://github.com/gcc-mirror/gcc/blob/master/libgcc/config/i386/crtfastmath.c) is the offending code, I believe.

That suggests that an adequate defense on our part would be to make sure Drake's correctness doesn't depend on how denormalized numbers behave. Fixing ospray seems like a thumb-in-the-dike fix -- the next external we add might do the same thing. 

The touchy behavior in #10260 was due to us explicitly generating a denormalized number and then making substantial behavior changes depending on using it. That's easily avoided since we didn't need the denormalized number for anything. For numerical computations the DAZ and FTZ flags cause numbers in the range [-1e-308, +1e-308] to be (a) treated as zero, or (b) set to zero, resp. That should not causes us any trouble!

**Comment by sherm1** [comment]
I was going to say we ought just to leave ospray as it is after fixing Drake's sensitivity to denormals. One downside to that is the effect that Drake could now have on downstream users, whose code might not be similarly denorm-proof. Now that we know about this are we are obligated not to be the bad egg in the downstream user's basket?

**Comment by EricCousineau-TRI** [comment]
Agreed mostly with @jwnimmer-tri :The original issue is low priority, but ideally we shouldn't be the bad egg. Even if OSPRay gets a little slower, it at least means that people using `libdrake.so` (who may not be using OSPRay) will not have their FP registers clobbered by `-ffast-math`.

So I'd say that this PR is good as-is, and can be easily reverted if we find it really does impact performance. We can tune the optimization flags later if it becomes a huge pain point?

\cc @kunimatsu-tri

**Comment by jwnimmer-tri** [comment]
I can live with that.  (If I were @kunimatsu-tri I'd want to know if we lost on 2% or 20% before agreeing, but personally I don't mind either way.)

**Comment by jamiesnape** [comment]
That matches my understanding at the moment. I can switch on the remainder of `-ffast-math` other than `-funsafe-math-optimizations` and `-ffinite-math-only`, but not sure it will gain us a great deal.

**Comment by jamiesnape** [comment]
FWIW The `rgbd_renderer_ospray_test` actually ran quicker here than in the equivalent nightly last night. Not a conclusive test of course, but interesting...

**Comment by sherm1** [comment]
My vote now would be simply to remove the `-ffast-math` flag and not try to find a safe subset, provided @kunimatsu-tri is OK with the performance.

**Comment by EricCousineau-TRI** [comment]
___
*[tools/workspace/vtk/repository.bzl, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10262#-LTyw6-Q9ej9cOBNfu4E:-LTyw6-Q9ej9cOBNfu4F:bby3oc3) ([raw file](https://github.com/robotlocomotion/drake/blob/32ed3f318923d69cd91012a444041ddc27d34313/tools/workspace/vtk/repository.bzl#L28)):*
> ```Python
>         CMAKE_BUILD_TYPE=Release
>         OSPRAY_ENABLE_APPS=OFF
>         OSPRAY_ENABLE_TESTING=OFF
> ```

For traceability, can you put a link to this comment that contains the patch?
https://github.com/RobotLocomotion/drake/pull/10262#issuecomment-448006316

**Comment by kunimatsu-tri** [comment]
Just for the record, here is the runtime comparison.
I ran the same program to render 99 frames using `OSPRay` and average the numbers.

Before this PR: 0.96 fps
With this PR: 0.92 fps

So, it's roughly 4% performance drop which is not so bad.

**Pull request merged**
