### PR TITLE
Add some clang-format guards

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Also run clang-format-includes to catch a few other recent strays.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6651)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review, please.

**Comment by EricCousineau-TRI** [comment]
Reviewed 4 of 39 files at r1.
Review status: 4 of 39 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2JjWNDcCgO1nEB9q:-Kpu2JjXfbBFfxbyhSa1:bjp25i1) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L1)):*
> ```cpp
> /* clang-format off */
> ```

This doesn't appear to change after applying `clang-format-3.9`.
Can I ask why these guards are here?

---

*[drake/common/drake_assert_and_throw.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2pj1Yc6t2XXc-G_4:-Kpu2pj1Yc6t2XXc-G_5:b-vv8eze) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/common/drake_assert_and_throw.cc#L2)):*
> ```cpp
> // This file contains the implementation of both drake_assert and drake_throw.
> /* clang-format off */
> ```

Same thing here - if I remove the guards entirely, there are no changes (at least on my system, on the latest `master` (`d3314e8`)).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 39 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2JjWNDcCgO1nEB9q:-Kpu3bVfxr4PppQiMvDa:b-2mj6hv) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

This doesn't appear to change after applying `clang-format-3.9`.
Can I ask why these guards are here?
</blockquote></details>

Aha, I see now that my PR description was unclear.

The tool that presents a hazard is:
```
bazel build drake/tools/clang-format-includes
bazel-bin/drake/tools/clang-format-includes \
  drake/automotive/maliput/monolane/test/monolane_lanes_test.cc
```

The broader idea is that only if you have `foo.h` and `test/foo_test.cc` exactly can you rely on the "related header" heuristics to work.  If you do something weird where you have more than one unit test per header, or more than one header per unit test, then you have to put in the guards.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2JjWNDcCgO1nEB9q:-Kpu6R-l12gnvXT0Rtn-:b-ay6r3e) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Aha, I see now that my PR description was unclear.

The tool that presents a hazard is:
```
bazel build drake/tools/clang-format-includes
bazel-bin/drake/tools/clang-format-includes \
  drake/automotive/maliput/monolane/test/monolane_lanes_test.cc
```

The broader idea is that only if you have `foo.h` and `test/foo_test.cc` exactly can you rely on the "related header" heuristics to work.  If you do something weird where you have more than one unit test per header, or more than one header per unit test, then you have to put in the guards.
</blockquote></details>

Ah, I see.
Would it be possible to make an issue with a quick description of this (perhaps with the ideal solution making `clang-format-includes recognize these blocks), and briefly reference it in these guards?

Perhaps having something like this?
```c++
/* clang-format off - see #XXXX */
#include "headers.h"
/* clang-format on */
```

NOTE: It seems like having *any* comment surrounding these blocks causes `clang-format-includes` to leave the block alone. Example for `drake_assert_and_throw.cc`:
```c++
//
#include "drake/common/drake_assert.h"
#include "drake/common/drake_throw.h"
//
```
This is left untouched. If I remove the comment lines, then they get shifted down.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2JjWNDcCgO1nEB9q:-Kpu9hTkcPah0oFE54j_:btvc7iq) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Ah, I see.
Would it be possible to make an issue with a quick description of this (perhaps with the ideal solution making `clang-format-includes recognize these blocks), and briefly reference it in these guards?

Perhaps having something like this?
```c++
/* clang-format off - see #XXXX */
#include "headers.h"
/* clang-format on */
```

NOTE: It seems like having *any* comment surrounding these blocks causes `clang-format-includes` to leave the block alone. Example for `drake_assert_and_throw.cc`:
```c++
//
#include "drake/common/drake_assert.h"
#include "drake/common/drake_throw.h"
//
```
This is left untouched. If I remove the comment lines, then they get shifted down.
</blockquote></details>

I think the correct outcome is for developers to be required to annotate unusual cases, not to teach the tool how to heuristically identify them -- both because in general I think that's a good approach, and for "related header" vs "unit test" in particular, developers who have other than a 1:1 relationship between component and its unit test should have to suffer a little bit because they've made an unfortunate choice.  Requiring them to annotate the mistake might help bring it to their attention.

However, if you think the text in these comments should be improved, I am open to proposals.  The endgame will be "if you remove this comment, your `bazel test` will fail a lint check", but such a check is not enabled yet.

(My ideal outcome is for all of these tests to be repaired to have a 1:1 relationship with their component, and then we don't need any annotations or heuristics.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2JjWNDcCgO1nEB9q:-KpuMwBxe5VdMAMWA3f1:bmag1js) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the correct outcome is for developers to be required to annotate unusual cases, not to teach the tool how to heuristically identify them -- both because in general I think that's a good approach, and for "related header" vs "unit test" in particular, developers who have other than a 1:1 relationship between component and its unit test should have to suffer a little bit because they've made an unfortunate choice.  Requiring them to annotate the mistake might help bring it to their attention.

However, if you think the text in these comments should be improved, I am open to proposals.  The endgame will be "if you remove this comment, your `bazel test` will fail a lint check", but such a check is not enabled yet.

(My ideal outcome is for all of these tests to be repaired to have a 1:1 relationship with their component, and then we don't need any annotations or heuristics.)
</blockquote></details>

Gotcha. My suggestion would be to add a quick mention of the relevance, by a PR number, a closed issue, or something like that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2JjWNDcCgO1nEB9q:-KpuNS6Dsu6JLe5RPmN9:bg52xe1) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Gotcha. My suggestion would be to add a quick mention of the relevance, by a PR number, a closed issue, or something like that.
</blockquote></details>

To be clear, the defect is "A developer who encounters one of these comments will not easily be able to figure out why it is here."?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2JjWNDcCgO1nEB9q:-KpuNjZgtwlzLb-kSl0h:b-ch495x) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To be clear, the defect is "A developer who encounters one of these comments will not easily be able to figure out why it is here."?
</blockquote></details>

Yes, I think having the context will make it easier to digest where these guards will occur.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651)*

**Comment by jwnimmer-tri** [comment]
PTAL.  I've made all of the comments consistent, with a proposed phrasing.  I also had to (in a separate commit) add support to clang-format-includes for extra comment text to appear on the line.

---

Review status: 0 of 63 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2JjWNDcCgO1nEB9q:-KpzZTWTxsbvlu_YmsUa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Yes, I think having the context will make it easier to digest where these guards will occur.
</blockquote></details>

Done.

---

*[drake/common/drake_assert_and_throw.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-Kpu2pj1Yc6t2XXc-G_4:-KpzZXHB9w-NrAlh7aGS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c34d9f24e0c0403bd4736c12ad83bf3db85ca200/drake/common/drake_assert_and_throw.cc#L2)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Same thing here - if I remove the guards entirely, there are no changes (at least on my system, on the latest `master` (`d3314e8`)).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-:-KpzZYHVgbxdgOME8z-S:b-8vsn2u)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 8 of 54 files at r2.
Review status: 8 of 63 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-:-KpzeB9MjyrRuIsUwStd:bpqxd5f)*

**Comment by EricCousineau-TRI** [comment]
+@ggould-tri for follow-up platform review, please.

---

Review status: 8 of 63 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-:-KpzeEzkTo-mfZ1dRbyH:b-d1gz8r)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 10 of 39 files at r1, 45 of 54 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651)*

**Comment by ggould-tri** [comment]
Once again I admit bafflement in the face of clang-format's choices.  :lgtm: for these workarounds, with sorrow.

---

Reviewed 10 of 39 files at r1, 54 of 54 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6651#-:-KpzjT8ipWeCyTrSY7ug:bo9dxcc)*

**Pull request merged**
