### PR TITLE
Disable dreal_solver_test under LSan due to memory leak in IBEX

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8022)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please

**Comment by jamiesnape** [comment]
+@soonho-tri for feature and platform review.

**Comment by soonho-tri** [comment]
I think the magic spell doesn't work. Let's disable the test in ASan/LSan builds and merge it asap.

I'm packaging a new `libibex-dev`. Will open a PR when it's ready.

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Comment by jwnimmer-tri** [comment]
Ah, superseded by #8024 it seems like.

**Comment by soonho-tri** [comment]
Close by #8024

**Pull request closed without merging**
