### PR TITLE
show_model: Test composite model; also enable usage of world files

### LINKED ISSUE #17118: show_model does not work for worlds with multiple models
Show_model is currently not supporting composed models (e.g. those that use the `<include>` tag to include models defined in a separate file or have two models nested in the world). This is a powerful feature of the [SDFormat](http://sdformat.org/tutorials?tut=composition).

When testing it with a composed model, the following error is trow: `RuntimeError: File must have a single <model> element.`

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #17118

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17129)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for both reviews, please +(status: single reviewer ok) 

@josebarrios-tri please note that the first commit is proof that a composite model (not world) works on current master. (in the future, perhaps we should exchange a minimum reproducing example, so that we're fully aware of acute problem0

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17129#-:-N1aHwhKAYAU8uiYfq-4:b593eu)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Assuming +(release notes: none)  ?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17129#-:-N1e47wX58JhR9JSzxxI:b-2c618z)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
That's correct; this tool is not installed.

**Comment by EricCousineau-TRI** [comment]
Yup, thanks!

**Pull request merged**
