### PR TITLE
[config] Update examples to use AddDefaultVisualization where convenient

### LINKED ISSUE #17687: Update examples to use AddDefaultVisualization
Per the overall #13673 goal, we should port as many example programs as possible to use the `AddDefaultVisualization(&builder)` or `ApplyVisualizationConfig(config, &builder)` sugar.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Updates a number of examples visualization implementations to use `AddDefaultVisualization()`. There are two groups of such examples:

  - Those that used boilerplate to visualize illustration geometry and contacts.
  - Those that only visualized illustration geometry.

The first sort offer a direct mapping to `AddDefultVisualization()` without change to functionality. The second were mapped to `AddDefaultVisualization()` with the understanding that requesting visualization of contact is both meaningless and harmless.

In some cases, anachronistic examples were updated to use `AddMultibodySceneGraph()` to more closely hew to the recommended spelling.

This excludes numerous binaries in examples (and elsewhere) that defy a mechanical translation.

Closes #17687

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17823)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for feature review.

This should be the far less controversial change.

I've partitioned the changes into two tranches (by revision). The tranches are documented in the commit messages. You're not obliged to inspect them by that categorization. Ultimately, all of these use `AddDefaultVisualization()` in their final state and this will be squashed with the PR description as commit message.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17823#-:-NAytoE91QnfSa872TdF:b5uyixv)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 11 of 11 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17823#-:-NAzwspJ6Lp8AKI0ZHNj:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`bindings/pydrake/systems/BUILD.bazel` line 387 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17823#-NAzt5NT4s1DQG8zDRQ2:-NAzt5NT4s1DQG8zDRQ3:b-9stm8u) ([raw file](https://github.com/robotlocomotion/drake/blob/99a580dc34ce86ddb0e416d3334a0ea9846af6a3/bindings/pydrake/systems/BUILD.bazel#L387)):*
> ```Starlark
>         ":framework_py",
>         ":primitives_py",
>         "//bindings/pydrake:geometry_py",
> ```

nit Unused `geometry_py`.
___
*[`bindings/pydrake/systems/drawing_graphviz_example.py` line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17823#-NAzwY8n-LKXve5MwhS9:-NAzwY8n-LKXve5MwhSA:b-a8p8a4) ([raw file](https://github.com/robotlocomotion/drake/blob/99a580dc34ce86ddb0e416d3334a0ea9846af6a3/bindings/pydrake/systems/drawing_graphviz_example.py#L45)):*
> ```Python
> builder.ExportInput(cart_pole.get_actuation_input_port())
> 
> AddDefaultVisualization(builder=builder)
> ```

The extra dot clutter here is _probably_ okay?  Do you think it distracts from the purpose of the example?




___
*[`examples/quadrotor/run_quadrotor_dynamics.cc` line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17823#-NAzs9N71OL4d38Hxhpi:-NAzs9N71OL4d38Hxhpj:b-s2l4hy) ([raw file](https://github.com/robotlocomotion/drake/blob/99a580dc34ce86ddb0e416d3334a0ea9846af6a3/examples/quadrotor/run_quadrotor_dynamics.cc#L45)):*
> ```cpp
>         FindResourceOrThrow("drake/examples/quadrotor/warehouse.sdf"));
>     plant.Finalize();
>     visualization::AddDefaultVisualization(&builder);
> ```

nit For my taste, the DEMAND were checking the Finalize post-conditions, so it makes sense to put them directly after it (i.e., the visualization happens _after_ confirming the post-conditions of Finalize).

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks.

+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17823#-:-NBI6EnHA1wMOKpGKYPQ:bckyl46)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`bindings/pydrake/systems/drawing_graphviz_example.py` line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17823#-NAzwY8n-LKXve5MwhS9:-NBI5JrgBjFxC1c9ZxJ5:byyw42y) ([raw file](https://github.com/robotlocomotion/drake/blob/99a580dc34ce86ddb0e416d3334a0ea9846af6a3/bindings/pydrake/systems/drawing_graphviz_example.py#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The extra dot clutter here is _probably_ okay?  Do you think it distracts from the purpose of the example?





</blockquote></details>

My gut says it's fine. I'd argue that the `Diagram` constructed here is representative of the common case. So, in this example, they might as well see the contact artifacts as well. If anything, it'll help reinforce what "default visualization" means.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17823)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 12 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17823)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17823#-:-NBIS4yd91Cxf6nIbzyh:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
