### PR TITLE
Update dreal version to 4.18.02.4

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8157)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature and platform review.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8157#-:-L632hCbdvkKmyHpAN1C:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/dreal/repository.bzl, line 17 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8157#-L632cT-WUcxAWjKFSPb:-L632n1T3TFb-ynfsxfL:b-r0pu8n) ([raw file](https://github.com/robotlocomotion/drake/blob/1e32f779668860c76c953dcb1f7dfe2d3d62625f/tools/workspace/dreal/repository.bzl#L17)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, could you remove this one this time?
</blockquote></details>

Not without breaking the builds while I switch images.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8157)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/workspace/dreal/repository.bzl, line 17 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8157#-L632cT-WUcxAWjKFSPb:-L633jFJ252D3xd-RFcy:bbrx4za) ([raw file](https://github.com/robotlocomotion/drake/blob/1e32f779668860c76c953dcb1f7dfe2d3d62625f/tools/workspace/dreal/repository.bzl#L17)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

OK. I'll take care of it later. Thank you!
</blockquote></details>

Actually, I removed the wrong line, but I do need to leave the previous version in for now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8157)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8157)*

**Comment by jamiesnape** [comment]
No idea why Jenkins failed `linux-xenial-unprovisioned-gcc-bazel-experimental` since the result was listed as SUCCESS and CDash says no errors.

**Comment by soonho-tri** [comment]
I've checked that dReal-related tests all passed there.. I have no clue either.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Pull request merged**
