### PR TITLE
Increase acrobot_run_passive_test size to medium.

### PR DESCRIPTION
**Pull request by avalenzu**
Attempts to resolve the following failures:

- https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind/267/
- https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind-everything/263/

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7853)

### CODE REVIEW

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

**Comment by avalenzu** [comment]
+@soonho-tri for feature and platform review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7853#-:-L3huPIXeqsnfm6vNk7O:bcf8rnd)*

**Comment by soonho-tri** [comment]
:lgtm: (Added do_not_merge label to prevent accidental merging)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7853#-:-L3hv1Gdv69kksmOnDmB:bi3l4w8)*

**Comment by soonho-tri** [comment]
@avalenzu , please check the CI failures.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7853#-:-L3iVJegSWGirH6YeBJH:b-jkp5pp)*

**Pull request closed without merging**
