### PR TITLE
Rename output ports of SchunkWsgStatusReceiver to match sim

### PR DESCRIPTION
**Pull request by calderpg-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21832)

### CODE REVIEW

**Review by calderpg-tri — COMMENTED** [review]
Simulation and LCM receivers for the Schunk WSG (and thus the Anzu Panda Hand implementation) use incompatible port names. This change renames the state and force output ports of the `SchunkWsgStatusReceiver` to match the `_measured` naming convention used elsewhere.

See Anzu#13663 for corresponding changes.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-:-O4mDMRK6kwW80XDCMcN:b-2x9ih9)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

**Review by calderpg-tri — COMMENTED** [review]
+@sammy-tri for feature review, thanks!

cc @IanTheEngineer @jwnimmer-tri @ggould-tri

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-:-O4mESxW35lPF7XR0iFS:b5sihpv)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21832)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

___
*[`manipulation/schunk_wsg/schunk_wsg_lcm.cc` line 97 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-O4o19eeEB9FJ0QwYeur:-O4o19eeEB9FJ0QwYeus:b-76f3t1) ([raw file](https://github.com/RobotLocomotion/drake/blob/a6179740d1dfae8212207f7d9a3e5ce4c38c4b38/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L97)):*
> ```cpp
>       force_output_port_(
>           this->DeclareVectorOutputPort("force_measured", 1,
>                                         &SchunkWsgStatusReceiver::CopyForceOut)
> ```

fyi -- I think this should be marked as a breaking change, or you should deprecate the output ports using

https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#a3d1c491c558b95d5f171090a4248fa78

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21832)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

___
*[`manipulation/schunk_wsg/schunk_wsg_lcm.cc` line 97 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-O4o19eeEB9FJ0QwYeur:-O4qGkWxB6JEt1j4Psat:b-o24wwd) ([raw file](https://github.com/RobotLocomotion/drake/blob/a6179740d1dfae8212207f7d9a3e5ce4c38c4b38/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L97)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

fyi -- I think this should be marked as a breaking change, or you should deprecate the output ports using

https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#a3d1c491c558b95d5f171090a4248fa78
</blockquote></details>

Yes, one of those will be needed. My inclination is that the breaking change would be simpler, I suspect that we at TRI are the primary - and likely the only - user of the names of these output ports.

**Review by calderpg-tri — COMMENTED** [review]
-@sammy-tri +@EricCousineau-TRI for feature review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-:-O4quj8KD6w4p_ADUEpt:bf560bg)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

___
*[`manipulation/schunk_wsg/schunk_wsg_lcm.cc` line 97 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-O4o19eeEB9FJ0QwYeur:-O4qunWc9Z1PYuqUvra1:brmto7w) ([raw file](https://github.com/RobotLocomotion/drake/blob/a6179740d1dfae8212207f7d9a3e5ce4c38c4b38/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L97)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Yes, one of those will be needed. My inclination is that the breaking change would be simpler, I suspect that we at TRI are the primary - and likely the only - user of the names of these output ports.
</blockquote></details>

fyi @EricCousineau-TRI if you have preferences here

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature pending deprecation per Russ's point

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-:-O4qvzCh2UWMiIx7CQcc:bnk0xww)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

___
*[`manipulation/schunk_wsg/schunk_wsg_lcm.cc` line 97 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-O4o19eeEB9FJ0QwYeur:-O4qvkQ1Bq6jSPHhIDDT:b-payaf0) ([raw file](https://github.com/RobotLocomotion/drake/blob/a6179740d1dfae8212207f7d9a3e5ce4c38c4b38/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L97)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

fyi @EricCousineau-TRI if you have preferences here
</blockquote></details>

For simplicity, we should follow deprecation. Can you add a deprecated alias here?

**Comment by jwnimmer-tri** [comment]
I am having trouble following the explanatory text.

> Simulation and LCM receivers for the Schunk WSG (and thus the Anzu Panda Hand implementation) use incompatible port names.

It is not clear to me what pattern this is matching.  I assume this PR is referring to the "LCM receiver" part, which is being changed to match the "Simulation" part.  What "Simulation" code is this supposed to be matching?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21832)* status: 3 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-O4qxjUZ2VI-tY5gLLON:-O4qxjUZ2VI-tY5gLLOO:b7c8807) (no related file):*
The header file documents the port names.  Any renaming must also be reflected in the documentation.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21832#-O4qxqVr6mWEk1zzMdkI:-O4qxqVr6mWEk1zzMdkJ:bt94ll2) (no related file):*
The port getter names (e.g., `get_state_output_port`) should match the string names ("state").  With the new string names, those getters need adjustment (with deprecation) as well.

___

**Comment by calderpg-tri** [comment]
Closing for now with a simpler approach in Anzu#13680

**Pull request closed without merging**
