### PR TITLE
[pydrake] Bindings of Identifier types are not necessarily unique

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This draft PR serves the purpose to reproduce an existing bug and provide some insight.

The `Identifier` type has a static method `get_new_id()` that guarantees over the lifespan of the process that every invocation of that method returns a unique identifier that cannot be returned by any other invocation. This provides a process-global, typed unique identifier. This contract is backed up by a function-local static variable (the counter of ids produced which gets incremented and returned on each invocation).

The problem observed is that the python bindings have access to multiple instances of the same identifier type. This is illustrated by using two different public APIs that should draw from a common identifier pool, but, nevertheless draw from unique pools.

This PR introduces a throwaway unit test that exactly exposes this issue. It also includes some additional decoration of the `Identifier` type to clarify the issue.

Commit 1: Adds a print out on the invocation of each `Identifier::get_new_id()` which helps identify which identifier type is being queried.
Commit 2: Adds a documented unit test (and the commit message explains how to exercise it).

Running:

    bazel test //bindings/pydrake:py/sg_fid_test

will show failure on test_one (but test_two and test_three will pass). However, if you run either of those later tests individually, they will fail with the same error:

    bazel test bindings/pydrake:py/sg_fid_test --test_arg=TestFoo.test_two

or

    bazel test bindings/pydrake:py/sg_fid_test --test_arg=TestFoo.test_three

Relates #15846.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15845)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
Revisions divided on commits. If you were to cherry-pick the second commit onto master, you'd see the test failure. The first commit merely gives more information as part of the failure. But it doesn't change the outcome.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15845#-:-MkmFv6ACd34kwClzRv7:b7xnphx)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@ericcousineau-tri I've poked and prodded, but need your help in figuring this out.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15845#-:-MkmG3nr4_DwU_8SnrK3:b-vqk5yu)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jwnimmer-tri** [comment]
Here's the gist of the solution:
https://github.com/jwnimmer-tri/drake/commits/identifier-uses-private-globals

**Comment by SeanCurtis-TRI** [comment]
Groovy. I'll make the tweak!

**Comment by SeanCurtis-TRI** [comment]
I'm going to see if I can't come up with something that preserves the ability to define functional identifiers simply by doing:

```c++
   using MyIdentifier = drake::Identifier<class MyTag>;
```

It's a shame to have to jump through a bunch of extra hoops.

**Comment by jwnimmer-tri** [comment]
We could do `extern template class Identifier<MyTag>;` to extern the whole class instead of just the one function, but I think that runs the risk of no longer inlining the comparison operators, depending on what the compiler decides to do.

We could turn the id-maker function into a templated free function instead of a class function, and then extern that, but that's still going to be extra syntax.

I don't think there's a way to avoid some kind of extra syntax.

**Review by SeanCurtis-TRI — COMMENTED** [review]
@jwnimmer-tri Take a look at my changes to `Identifier` in my most recent commit. I believe it satisifes both design goals of keeping the never destroyed in a .cc file and keeps the declaration interface the same.

I'm curious to see if you think I'm doing something evil.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15845#-:-Mkn-vOACnV-a-gPLxJi:bcua11o)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jwnimmer-tri** [comment]
When I first glanced over this for a few seconds, I saw "unordered_map keyed on type_id" and thought: hey, that's neat, I never considered that; seems like it would work.  Coming back to it now, I see it has a mutex.  A mutex isn't really appropriate for a snake_case function, so I think this is a dead end.

I can think of a few other variations on my original theme above (with different ways for how to declare and initialize the storage), but they all involved once-per-class changes to a cc file, so aren't really any better or worse than my branch above.

**Comment by jwnimmer-tri** [comment]
Hmm, there's an outside chance that it would be legal to make the `std::atomic<int>` a static member field directly, assuming it doesn't generate any ctor object code.  (We would need to start with zero as default value, not one, and so use a pre-increment in the get_new_id.)  We can investigate tomorrow.

**Comment by jwnimmer-tri** [comment]
In the original push (with just the new test, without the fix), in CI only the Clang builds failed the test; the GCC builds passed.  Is that what you expected to see as well?  For me locally, it only fails under Clang.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I explored the "make `std::atomic<int>` a static member directly. I ran it through [godbolt](https://godbolt.org/z/jz1s6rMcf). While indications look good vis a vis the constructor overhead, sadly, it doesn't work. The static member still has to be defined in the header file which is the same as defining it as function local. I get different instances of the static member based on compilation paths and the test still fails.

So, let's go back to the map. If the true sticking point is the `mutex`, can we do something about that? Sadly, thread safety is documented on the `get_new_id()` method. However, that particular property was highly speculative at the time. In retrospect, generating ids is a start-up activity and not a "compute in parallel" activity. I feel the risk of "losing" that property is slight at best. Thoughts?

Finally, going back to your original proposal (because that might be the only option left to us), where the user is simply obliged to write more code. I'm unclear of what the strategy is (of if you have one yet). Given what you'd cobbled together, I'm inferring the following:

    - The default implementation of `get_new_id()` calling into `do_get_new_id()` is so ids are backwards compatible. I.e., any code that creates an ID but doesn't "externalize" the `get_new_id()` specialization will "work", although its bindings may suffer from the symptom in the bindings addressed here.
    - Is there a plan to wean people off of crippled identifiers such that the compiler will complain if they don't properly specialize the method (e.g., via putting a `static_assert` in the base implementation)? How would that transition work?

I certainly don't like the idea of generating id types that may or may not work in bindings such that the only distinction is that detected by a keen-eyed reviewer.

(Actually, I didn't investigate gcc. Clang is my default compiler and failure there was enough for me to start down this road.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15845#-:-MkqmuQa6mGYjKkE1PkN:b-4edgzw)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
One last option is to deprecate `get_new_id()` in favor of `GetNewId()` and throw out the snake case and maintain thread safety. That may be the winner.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15845#-:-Mkr03YH2M0lFxWbpSYn:b-9eaei7)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by sherm1** [comment]
Random thought: have you tried declaring the header file function as `inline static`? In theory inline linkage requires the linker to create just a single definition, while plain `static` is unique per compilation unit.

**Comment by jwnimmer-tri** [comment]
@sherm1 The root of the problem is that the way we link our pydrake modules does not comply with ODR 100% while linking and loading.  I have plans to eventually change that (probably concurrently with #11802), but it will be a large change to the build infrastructure, so it not happening soon.  Any language-level annotations on the code will just be playing games with whether or not they trip on our loader's ODR violations or not.  The only way to be _sure_ to pass is to emit global data in exactly one cc file; it can't ever be in a header (so long as we still have a broken pydrake build system).

@SeanCurtis-TRI I'll look over your other suggestions in a little while.

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/test/sg_fid_test.py, line 23 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15845#-Mkrud5i-r5TiV_r4ch3:-Mkrud5j7X6Sh1xBtm1u:b119xvu) ([raw file](https://github.com/robotlocomotion/drake/blob/ef189fc0c67eb32e6735741d606483f22f1b9c6c/bindings/pydrake/test/sg_fid_test.py#L23)):*
> ```Python
>         self.assertNotEqual(scene_graph.world_frame_id().get_value(),
>                             f.id().get_value())
>         self.assertNotEqual(scene_graph.world_frame_id().get_value(), f_id)
> ```

nit `f_id` here is wrong, we want `f_id.get_value()` so we're comparing int vs int, not int vs Id.  Ditto below.

**Comment by jwnimmer-tri** [comment]
I posted half of a fix to #15854.  The other half is a bit more interesting (don't inline the `get_new_id` function within pydrake), so I'll post it separately.

**Review by SeanCurtis-TRI — COMMENTED** [review]
The palliative patch is still very worthwhile.  It reminds me of the old joke:

Patient: Doctor. It hurts when I do this.
Doctor: Don't do that.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15845#-:-Mks-dZm9qCoxnIDYY94:bk6djl)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
FYI my proposal is that #15857 will subsume this PR.  (I'm happy to leave this one open until we're sure.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
It's got unit tests, that makes me happy. I'm good for closing this.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15845#-:-MksKekyCUgnhxxwx8qp:bek1ivd)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Comment by SeanCurtis-TRI** [comment]
Closed in favor of #15857.

**Pull request closed without merging**
