### PR TITLE
Suppressions from source code

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Valgrind's source code (git mirror):
https://github.com/svn2github/valgrind

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5682)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-experimental-memcheck-valgrind-open-source please

**Comment by jamiesnape** [comment]
This reduces the number of Valgrind defects ~5000 to ~3000, so the mac-clang-experimental-memcheck-valgrind-open-source build is expected to still fail.

**Comment by jwnimmer-tri** [comment]
Two questions below (note they are in separate threads).

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-KgtVNPvRuKgnucbGrKa:-KgtVNPvRuKgnucbGrKb:b-b2eznw) (no related file):*
@soonho-tri @jamiesnape For OSX, is it correct that the best practice is to vendor valgrind's supp file updates into our own tree, versus somehow upgrading valgrind itself?  I don't know the ecosystem well enough to judge.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-KgtYmcbFvvCwJcK1t6m:-KgtYmccLh2Hl8pMFS5q:b-uijd5u) (no related file):*
When I first looked at how our listfiles specified which `supp` file(s) to use, I thought it would equally well support reading suppressions from multiple `*.supp` files, instead of just one.

If that was true, I would like to consider breaking out these new items into their own file, for two reasons:

(1) They appear to be OSX specific -- in which case it would be epsilon cleaner to only enable then when testing on OSX.

(2) They appear to be copied from `valgrind`, and I would prefer not to have to reason about GPL compliance when they are blended into our own code.  I'm not sure if copyright attaches to this kind of work, but perhaps our job is easier if we keep the file separate and not worry.  I would prefer if the file could live in `drake/thirdParty/gpl`.

On second read, I can't tell if the `MEMORYCHECK_SUPPRESSIONS_FILE` is a single item, or some kind of semicolon-separated list.  I guess even if its a single item, we could have CMake concatenate many supp files into one and then pass that to memcheck.  That's extra work, but perhaps worth it?

I would welcome more thoughts on this topic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-:-KgtVxUvVFLLeslBUwec:b-j24wpj)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-KgtVNPvRuKgnucbGrKa:-Kgtb2rw3FU0z1gBbLMr:b-hwkrq0) (no related file):*
> somehow upgrading valgrind itself? 

Based on my experience, valgrind's OSX support is pretty poor. For example, it doesn't support OSX-10.12. As of 2017 Apr, the official website says `Mac OS X 10.10, with initial support for 10.11`. I'm mostly relying on clang's `ASAN` (or go to a linux box).

> vendor valgrind's supp file updates into our own tree

I think this is the way to go.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-KgtYmcbFvvCwJcK1t6m:-KgtcbKnLLzJCxMMtfUc:bfixeyk) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When I first looked at how our listfiles specified which `supp` file(s) to use, I thought it would equally well support reading suppressions from multiple `*.supp` files, instead of just one.

If that was true, I would like to consider breaking out these new items into their own file, for two reasons:

(1) They appear to be OSX specific -- in which case it would be epsilon cleaner to only enable then when testing on OSX.

(2) They appear to be copied from `valgrind`, and I would prefer not to have to reason about GPL compliance when they are blended into our own code.  I'm not sure if copyright attaches to this kind of work, but perhaps our job is easier if we keep the file separate and not worry.  I would prefer if the file could live in `drake/thirdParty/gpl`.

On second read, I can't tell if the `MEMORYCHECK_SUPPRESSIONS_FILE` is a single item, or some kind of semicolon-separated list.  I guess even if its a single item, we could have CMake concatenate many supp files into one and then pass that to memcheck.  That's extra work, but perhaps worth it?

I would welcome more thoughts on this topic.
</blockquote></details>

I like the idea of keeping platform-specific `.supp` files. But AFAIK `MEMORYCHECK_SUPPRESSIONS_FILE` is a single item (of course, one can concatenate it as you explained).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5682)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-KgtYmcbFvvCwJcK1t6m:-KgtdEuzNhXq9VMK2ZIL:bx1pfjq) (no related file):*
> concatenate it
"concatenate them into one"...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5682)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-KgtVNPvRuKgnucbGrKa:-KgthwgrmtEUnja3nco6:b-37fc9s) (no related file):*
> Based on my experience, valgrind's OSX support is pretty poor. For example, it doesn't support OSX-10.12. As of 2017 Apr, the official website says Mac OS X 10.10, with initial support for 10.11. I'm mostly relying on clang's ASAN (or go to a linux box).

This is very true. I am starting to wonder how much benefit we are gaining from the OS X build. Probably worth a little time to tweak the suppressions, but beyond that, I am not sure.

> I think this is the way to go.

I agree.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-KgtYmcbFvvCwJcK1t6m:-KgtjKbrAZ5gj_AqpKL_:bulaopm) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> concatenate it
"concatenate them into one"...
</blockquote></details>

We could quite possibly just use `CTEST_MEMORYCHECK_COMMAND_OPTIONS` to set the suppressions files, then we can pass multiple `--suppressions` flags.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5682)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-KgtVNPvRuKgnucbGrKa:-KgttfO1nqg3DsAbgGgS:bnftxq) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> Based on my experience, valgrind's OSX support is pretty poor. For example, it doesn't support OSX-10.12. As of 2017 Apr, the official website says Mac OS X 10.10, with initial support for 10.11. I'm mostly relying on clang's ASAN (or go to a linux box).

This is very true. I am starting to wonder how much benefit we are gaining from the OS X build. Probably worth a little time to tweak the suppressions, but beyond that, I am not sure.

> I think this is the way to go.

I agree.

</blockquote></details>

Sure.  If it were up to me, I would stop-work on OSX dynamic analysis until Xenial dynamic analysis is 100% working and in the hands of our developers.   Better to have one fully-working platform, than two half-working platforms, and Xenial wins the majority vote.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5682)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5682#-KgtVNPvRuKgnucbGrKa:-KgtufFzany7U61JsQR5:b-r5n26o) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sure.  If it were up to me, I would stop-work on OSX dynamic analysis until Xenial dynamic analysis is 100% working and in the hands of our developers.   Better to have one fully-working platform, than two half-working platforms, and Xenial wins the majority vote.
</blockquote></details>

@m-chaturvedi is currently working on an upstream fix to Eigen, and then there is one recurring defect related to MOSEK that I am 99% sure just needs a suppression, so the 100% working Xenial build should be very soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5682)*

**Pull request closed without merging**
