### PR TITLE
[Bazel] Add more BUILD rules

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4411)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
CI flake.
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

+@sammy-tri want to take a crack at platform review?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4411#-:-KYPjmZ0AY3sh9ly82_r:b-1krbjv)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4411#-:-KYPv0qS84qO778Gdvaf:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
>  linux-gcc-experimental-matlab — Jenkins build triggered 

Now _I_ am triggered.  Thanks, matlab!

Using override-merge due to Bazel-only changes and Bazel CI passed.

**Pull request merged**
