### PR TITLE
Bumped director submodule to be the latest version.

### LINKED ISSUE #3703: CMake Option -DUSE_SYTEM_VTK=OFF Causes Build to Fail
Per https://github.com/RobotLocomotion/drake/issues/2624#issuecomment-251937730, I modified `drake-distro/CMakeLists.txt` to not use the system's VTK (I'm doing this for testing purposes -- no intent on getting it merged into master):

https://github.com/liangfok/drake/commit/d810ee4e780562ee4cdc155c744879e569558f48

Unfortunately, with this modification, Drake's build fails with the following error:

```
[10/246] Generating moc_ddLCMThread.cxx
FAILED: cd /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters && /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters/depth_compose.cxx /home/liang/dev/drake-distro-1/externals/director/src/vtk/DRCFilters/edl_resources/Shaders/depth_compose.glsl depth_compose
/bin/sh: 1: /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters/depth_compose.cxx: not found
FAILED: cd /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters && /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters/bilateral_filter.cxx /home/liang/dev/drake-distro-1/externals/director/src/vtk/DRCFilters/edl_resources/Shaders/bilateral_filter.glsl bilateral_filter
/bin/sh: 1: /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters/bilateral_filter.cxx: not found
FAILED: cd /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters && /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters/edl_compose.cxx /home/liang/dev/drake-distro-1/externals/director/src/vtk/DRCFilters/edl_resources/Shaders/edl_compose.glsl edl_compose
/bin/sh: 1: /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters/edl_compose.cxx: not found
FAILED: cd /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters && /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters/edl_shade.cxx /home/liang/dev/drake-distro-1/externals/director/src/vtk/DRCFilters/edl_resources/Shaders/edl_shade.glsl edl_shade
/bin/sh: 1: /home/liang/dev/drake-distro-1/build/externals/director/src/director-build/src/vtk/DRCFilters/edl_shade.cxx: not found
```

It looks like there are some DRC filters missing from the source code.

### PR DESCRIPTION
**Pull request by liangfok**
This is necessary for Director to compile VTK5 from source on systems with ROS Kinetic installed. Note that this version of Director optionally uses a patched version of VTK5 that defines `GLX_GLXEXT_LEGACY`: https://github.com/RobotLocomotion/director/commit/38499093ba928a869bda48fb69437fa0f1a44189

Resolves #3703.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3738)

### CODE REVIEW

**Comment by liangfok** [comment]
+@patmarion for feature review please.
+@sherm1 for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3738#-:-KTfbvZkVvIyJqp5L-Ap:bmq12el)*

**Comment by sherm1** [comment]
Platform: :lgtm: (didn't try it though -- I'm depending on @patmarion to make sure it works).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3738#-:-KTfj1v88EknnLa-kRTK:b-dwto52)*

**Comment by liangfok** [comment]
Thanks @sherm1. This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/5567/ and is thus ready for feature review. Of course, CI doesn't cover the scenario where VTK5 is compiled from source.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3738#-:-KTgL8lfO-sDv17gSmZO:b-k4oy8h)*

**Comment by patmarion** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3738)*

**Comment by patmarion** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3738#-:-KTiNaWXtLoHutb0gWxV:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Merging now.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3738#-:-KTiNolJ1SVnQPyH8Svm:b4joi5f)*

**Pull request merged**
