### PR TITLE
Cassie bench gbench

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This PR subsumes a snapshot of #13770. I'm publishing it so we can compare the two benchmark programs and discuss how to go forward.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13782)

### CODE REVIEW

**Comment by sherm1** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13782#-MDadfoY6ApaYYUUwEPb:-MDaho0C-XZ6nrWsIDAP:b-2e0q6m) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Interesting. It appears that the number of malloc/free calls is greater when cassie_bench is built `-c dbg` than for release builds.
</blockquote></details>

Yes, that's true. The reason is a debug-only check in the caching system. I had to comment that out to get meaningful heap results in Debug mode. The offending method is CacheEntry::CheckValidAbstractValue(), invoked from CacheEntry::Calc() as `DRAKE_ASSERT_VOID(CheckValidAbstractValue(*value));` (line 50 in cache_entry.cc).

---

**Comment by sherm1** [comment]
Pulled r7 and ran it a few times on my Puget. Results were consistent and looked about like this:
```
Executing tests from //examples/multibody/cassie_benchmark:cassie_bench
-----------------------------------------------------------------------------
2020-08-04 22:21:52
Running /home/sherm/.cache/bazel/_bazel_sherm/e6c506c79a0a2d8ce8be77e2bf55a048/execroot/drake/bazel-out/k8-opt/bin/examples/multibody/cassie_benchmark/cassie_bench.runfiles/drake/examples/multibody/cassie_benchmark/cassie_bench
Run on (48 X 2900 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x24)
  L1 Instruction 32 KiB (x24)
  L2 Unified 256 KiB (x24)
  L3 Unified 30720 KiB (x2)
Load Average: 6.94, 8.42, 4.72
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
----------------------------------------------------------------------------------
Benchmark                                        Time             CPU   Iterations
----------------------------------------------------------------------------------
DoubleFixture/DoubleMassMatrix               36912 ns        36911 ns        17687
DoubleFixture/DoubleInverseDynamics          27253 ns        27252 ns        25657
DoubleFixture/DoubleForwardDynamics          54727 ns        54726 ns        12834
AutodiffFixture/AutodiffMassMatrix         5690328 ns      5690101 ns          122
AutodiffFixture/AutodiffInverseDynamics    6900442 ns      6900392 ns          100
AutodiffFixture/AutodiffForwardDynamics   10186423 ns     10186199 ns           69
```

**Comment by sherm1** [comment]
BTW you can get rid of the warning about CPU scaling with this command:
> sudo cpupower frequency-set --governor performance

(You might have to install a few things first but it will let you know.)

I ran that on my Puget after which the warning was gone but I didn't notice much effect on the timings.

**Comment by sherm1** [comment]
OK, a mystery here. I followed my advice above and deleted the unnecessary lines. No effect on the basic timings, but the autodiff times sped up by around 5X:
```
----------------------------------------------------------------------------------
Benchmark                                        Time             CPU   Iterations
----------------------------------------------------------------------------------
DoubleFixture/DoubleMassMatrix               38707 ns        38706 ns        18302
DoubleFixture/DoubleInverseDynamics          31065 ns        31056 ns        24359
DoubleFixture/DoubleForwardDynamics          57026 ns        57024 ns        12607
AutodiffFixture/AutodiffMassMatrix         1083479 ns      1083201 ns          678
AutodiffFixture/AutodiffInverseDynamics    2408663 ns      2408585 ns          302
AutodiffFixture/AutodiffForwardDynamics    2460056 ns      2459328 ns          277
```
(Same puget as before)

**Comment by sherm1** [comment]
With all the SetPositionAndVelocity calls present but pulled out of the loops I get this on my Puget:
```
Run on (48 X 2900 MHz CPU s)
Benchmark                                        Time             CPU   Iterations
DoubleFixture/DoubleMassMatrix               35967 ns        35967 ns        19403
DoubleFixture/DoubleInverseDynamics          26700 ns        26700 ns        26411
DoubleFixture/DoubleForwardDynamics          53406 ns        53406 ns        13062
AutodiffFixture/AutodiffMassMatrix         5711304 ns      5711067 ns          128
AutodiffFixture/AutodiffInverseDynamics    6830826 ns      6830669 ns          100
AutodiffFixture/AutodiffForwardDynamics   10280669 ns     10280533 ns           72
```
Between-run variation is 5%-ish.
Autodiffing gives a 150-200X slowdown. Approximating these with forward differencing would require one evaluation per derivative so 23X for mass matrix, 68X for inverse dynamics, 55X for forward dynamics.

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME3wJOi-lHq8t8LdLfQ:-ME3wJOi-lHq8t8LdLfR:b-ytnnd6) (no related file):*
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

---

**Comment by jwnimmer-tri** [comment]
___
*[examples/multibody/cassie_benchmark/BUILD.bazel, line 40 at r9](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME4XVHl7eh7jhIssp_v:-ME4yvuk9BDZhsaxELbS:b4u7ieq) ([raw file](https://github.com/robotlocomotion/drake/blob/ca14d918650115f99897473b9ba4fc4e9ce2b745/examples/multibody/cassie_benchmark/BUILD.bazel#L40)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@ericcousineau-tri review, advice, alternatives?

I would like to have a text file that captures the details of compilation end up in <blah>/test.outputs/ . Of course, after I hacked up what you see here, I discovered print_host_settings. I couldn't figure out how to use it as-offered for my purpose, so I continued hacking :/ .
</blockquote></details>

If you want the compiler version in the benchmark output, I'd suggest using the preprocessor giblets the compiler injects into your source and turn that into C++ literal strings to print out.

**Comment by jwnimmer-tri** [comment]
___
*[examples/multibody/cassie_benchmark/BUILD.bazel, line 40 at r9](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME4XVHl7eh7jhIssp_v:-ME4zT36COhBu-k5n1uu:b-lw920u) ([raw file](https://github.com/robotlocomotion/drake/blob/ca14d918650115f99897473b9ba4fc4e9ce2b745/examples/multibody/cassie_benchmark/BUILD.bazel#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you want the compiler version in the benchmark output, I'd suggest using the preprocessor giblets the compiler injects into your source and turn that into C++ literal strings to print out.
</blockquote></details>

See `drake/tools/workspace/cc/identify_compiler.cc` perhaps.

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME3wJOi-lHq8t8LdLfQ:-ME54MmK0cwbWPt2ztyL:b-e2oap8) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.
</blockquote></details>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

---

**Comment by jwnimmer-tri** [comment]
___
*[examples/multibody/cassie_benchmark/BUILD.bazel, line 40 at r9](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME4XVHl7eh7jhIssp_v:-ME58lBz7EZXQKXksUlJ:b-s4d60v) ([raw file](https://github.com/robotlocomotion/drake/blob/ca14d918650115f99897473b9ba4fc4e9ce2b745/examples/multibody/cassie_benchmark/BUILD.bazel#L40)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> review, advice, alternatives?

Gotcha! Just wanted to make sure it wasn't a TODO for me to then follow up on ;)

I've added some additional defects below.
</blockquote></details>

I was thinking we could just call a compiled `identify_compiler`, not inline it.

Anyway, it seems to me like labeling measurements is more of a "I compiled this tree at this revision with this compiler and ran it on this host" -- trying to put a tiny, half-baked fraction of that into the BUILD seems to me like a bridge too far for the first PR.

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME3wJOi-lHq8t8LdLfQ:-ME8q0198DQB54XlK8nu:b290f5e) (no related file):*
> @drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME3wJOi-lHq8t8LdLfQ:-ME9uVrmEdaXq-fTOgDZ:b290f5e) (no related file):*
> @drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME3wJOi-lHq8t8LdLfQ:-MEAJhg39kH2tO77XB5v:b-e2oap8) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> @drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.
</blockquote></details>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME3wJOi-lHq8t8LdLfQ:-MEPOr166RQpnjFyDBRt:b-e2oap8) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.
</blockquote></details>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME3wJOi-lHq8t8LdLfQ:-METbN0Q7ZKsjGMlZmAc:b-ytnnd6) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.
</blockquote></details>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13782#-ME3wJOi-lHq8t8LdLfQ:-METlIDnBoJjSLK-V4G_:b290f5e) (no related file):*
> @drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

---

**Pull request merged**
