### PR TITLE
[multibody] Support deformable free motion calculation

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) +@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955#-:-NCbdwoJ415TBggAk8eU:bgvwxyh)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955)* status: 8 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/plant/deformable_driver.h` line 101 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtomK3Ew4VNHgcoDNI:-NCtomK3Ew4VNHgcoDNJ:b-m2wy5b) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.h#L101)):*
> ```objc
>   void CalcNextFemState(const systems::Context<T>& context,
>                         DeformableBodyIndex index,
>                         fem::FemState<T>* next_fem_state) const;
> ```

I still need to look at the source, but I'd imagine that in general all deformable bodies will be coupled through contact. That is, to advance to the next state we need to perform the compuation for all bodies at the same time.
Does it make sense to have a Calc API specific for a single body index? 
___
*[`multibody/plant/deformable_driver.h` line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtpEs35UZZKQoH8OOa:-NCtpEs35UZZKQoH8OOb:b-40w7nq) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.h#L105)):*
> ```objc
>   /* Eval version of CalcNextFemState(). */
>   const fem::FemState<T>& EvalNextFemState(const systems::Context<T>& context,
>                                            DeformableBodyIndex index) const;
> ```

fyi, This sugar Eval where you pass the body index does make sense to me, in contrast to the Calc version, since the Eval can actually trigger the full computation for all bodies and only return the next state for the requested body index.
___
*[`multibody/plant/deformable_driver.h` line 111 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtpevqE6M5sgBRAsRR:-NCtpevr-2l8GPjdAGfi:buvotj2) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.h#L111)):*
> ```objc
>   const DeformableModel<T>* const deformable_model_;
>   const DiscreteUpdateManager<T>* const  manager_;
>   /* The integrator used to advance deformable body states in time. */
> ```

nit, maybe say "deformable body free motion states in time."
___
*[`multibody/plant/deformable_driver.cc` line 30 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtqbX65ZuurJaebCMP:-NCtqbX65ZuurJaebCMQ:bcivigz) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L30)):*
> ```cpp
>   DRAKE_DEMAND(manager != nullptr);
>   // Set the time integrator for advancing deformable states in time to be the
>   // midpoint rule, i.e., q = q₀ + δt/2 *(v₀ + v).
> ```

Is the plan to have an option for symplectic Euler/midpoint rule in DeformableBodyConfig? maybe add TODO to expose these?
___
*[`multibody/plant/deformable_driver.cc` line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtqu-u3yCfRp9GpJwg:-NCtqu-u3yCfRp9GpJwh:b-5wabrq) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L58)):*
> ```cpp
>         {systems::System<T>::xd_ticket()});
>     cache_indexes_.fem_states.emplace_back(fem_state_cache_entry.cache_index());
>     /* Cache entry for free motion FEM state. */
> ```

minor, my preference would be to have a space right after the DeclareCacheEntry call.
___
*[`multibody/plant/deformable_driver.cc` line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtsUoT3Z20PYUrIpqm:-NCtsUoT3Z20PYUrIpqn:b-ob10aq) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L79)):*
> ```cpp
>                 [this, i](const systems::Context<T>& context,
>                           fem::FemState<T>* next_fem_state) {
>                   this->CalcNextFemState(context, i, next_fem_state);
> ```

Since in general all states are copuled by constraints and need to be computed at once, I believe for CalcNextFemState the signature we'd want is something like `CalcNextFemState(const Context<T>&, std::vector<FemState<T>>* fem_states)`
___
*[`multibody/plant/deformable_driver.cc` line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtrevjDH828baiR-bw:-NCtrevjDH828baiR-bx:b-7y2mon) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L87)):*
> ```cpp
>     FemSolverScratchData scratch(fem_model);
>     const auto& scratch_entry = manager->DeclareCacheEntry(
>         fmt::format("FEM solver scratches for body with index {}", i),
> ```

minor, scratches -> scratch data? or scratch workspace?
___
*[`multibody/plant/deformable_driver.cc` line 163 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtsqTL86PL-hHW4zrl:-NCtsqTL86PL-hHW4zrm:b-yp3uqg) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L163)):*
> ```cpp
>   return manager_->plant()
>       .get_cache_entry(cache_indexes_.next_fem_states.at(index))
>       .template Eval<FemState<T>>(context);
> ```

I think here you'd need something like:
```c++
const std::vector<FemState<T>>& fem_states = plant().get_cache_entry(cache_indexes_.next_fem_states).Eval<std::vector<FemState<T>>>(context);
return fem_states[index];
```
___
*[`multibody/plant/test/deformable_driver_test.cc` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCttaqG6PXQkD50DFb2:-NCttaqG6PXQkD50DFb3:b-icxrld) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/test/deformable_driver_test.cc#L144)):*
> ```cpp
>   const VectorX<double> next_q = q + 0.5 * (v + next_v) * kDt;
>   // Tolerance has unit of velocity.
>   const double kTol = 1e-4;
> ```

for this case with no contact, why do we need such a loose tolerance? and why does it make sense to specify the tolerance with units of velocity?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955)* status: 6 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/plant/deformable_driver.h` line 101 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtomK3Ew4VNHgcoDNI:-NCvgIpBDuTTqsBW6W1S:b-g3ooou) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.h#L101)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I still need to look at the source, but I'd imagine that in general all deformable bodies will be coupled through contact. That is, to advance to the next state we need to perform the compuation for all bodies at the same time.
Does it make sense to have a Calc API specific for a single body index? 
</blockquote></details>

Since this is a private helper, I don't think it matters as much. 

Making the function per body makes allocation easier: FemState doesn't allow copying and instead requires compatibility the the FemModel. As a result, creating the model value for the cache entry in an `std::vector` is slightly awkward. So I simply mimic the functional form of `CalcFemState` and `CalcFreeMotionFemState` for simplicity. It says nothing about dependency of the cache entry. I can add a comment for clarification if it helps.
___
*[`multibody/plant/deformable_driver.h` line 111 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtpevqE6M5sgBRAsRR:-NCvhOv_9D694w2qac1D:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.h#L111)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, maybe say "deformable body free motion states in time."
</blockquote></details>

Done, thanks.
___
*[`multibody/plant/deformable_driver.cc` line 30 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtqbX65ZuurJaebCMP:-NCvhs6R9WyfAGTmdmlg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L30)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Is the plan to have an option for symplectic Euler/midpoint rule in DeformableBodyConfig? maybe add TODO to expose these?
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_driver.cc` line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtqu-u3yCfRp9GpJwg:-NCvi-ye6t_-IpoAzOhv:blx5sbh) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L58)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, my preference would be to have a space right after the DeclareCacheEntry call.
</blockquote></details>

I suppose you meant a blank line? Done.
___
*[`multibody/plant/deformable_driver.cc` line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtsUoT3Z20PYUrIpqm:-NCvlQnnBLdUJb56i6Zl:b-v85eh7) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L79)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Since in general all states are copuled by constraints and need to be computed at once, I believe for CalcNextFemState the signature we'd want is something like `CalcNextFemState(const Context<T>&, std::vector<FemState<T>>* fem_states)`
</blockquote></details>

See thread above.
___
*[`multibody/plant/deformable_driver.cc` line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtrevjDH828baiR-bw:-NCviJyQ6vyUGfMvrSCO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L87)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, scratches -> scratch data? or scratch workspace?
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_driver.cc` line 163 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtsqTL86PL-hHW4zrl:-NCvlP-480dYeZXVWsiy:b-v85eh7) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L163)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think here you'd need something like:
```c++
const std::vector<FemState<T>>& fem_states = plant().get_cache_entry(cache_indexes_.next_fem_states).Eval<std::vector<FemState<T>>>(context);
return fem_states[index];
```
</blockquote></details>

See thread above.
___
*[`multibody/plant/test/deformable_driver_test.cc` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCttaqG6PXQkD50DFb2:-NCvkP8l2pAX1ao__TVL:bqg6f2h) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/test/deformable_driver_test.cc#L144)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

for this case with no contact, why do we need such a loose tolerance? and why does it make sense to specify the tolerance with units of velocity?
</blockquote></details>

Loose tolerance: this is because of the default tolerance for the FemSolver. Unfortunately we don't yet have a DeformableDriver API to turn that knob yet (I added a TODO). But I verified that if we tighten the tolerance for FemSolver we can get stricter tolerance here.

Unit: because we are comparing calculated velocity vs. analytic velocity, I set kTol to unit of velocity.

**Comment by xuchenhan-tri** [comment]
*[`multibody/plant/test/deformable_driver_test.cc` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCttaqG6PXQkD50DFb2:-NCvqva6CaYkXURQV73n:b-fxklxx) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/test/deformable_driver_test.cc#L144)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Loose tolerance: this is because of the default tolerance for the FemSolver. Unfortunately we don't yet have a DeformableDriver API to turn that knob yet (I added a TODO). But I verified that if we tighten the tolerance for FemSolver we can get stricter tolerance here.

Unit: because we are comparing calculated velocity vs. analytic velocity, I set kTol to unit of velocity. 
</blockquote></details>

Also probably worth mentioning that the goal of the unit test here is to test invocation of the solver in deformable driver. The solver itself is tested in FemSolverTest and the physics is tested in model and element tests.

We will eventually have an integration test that combines all these components (including contact).

**Review by amcastro-tri — COMMENTED** [review]
Great to see the progress on this! :lgtm_strong: 

@rpoyner-tri for feature review please.

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955#-:-NCzLZgPC_o6VaMHZD81:bw3xlze)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/plant/deformable_driver.h` line 101 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtomK3Ew4VNHgcoDNI:-NCzLQRMAQ7DSQmoJc2o:brr0knj) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.h#L101)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Since this is a private helper, I don't think it matters as much. 

Making the function per body makes allocation easier: FemState doesn't allow copying and instead requires compatibility the the FemModel. As a result, creating the model value for the cache entry in an `std::vector` is slightly awkward. So I simply mimic the functional form of `CalcFemState` and `CalcFreeMotionFemState` for simplicity. It says nothing about dependency of the cache entry. I can add a comment for clarification if it helps.
</blockquote></details>

I see how the non-copyability of FemState make things awkward .
___
*[`multibody/plant/deformable_driver.cc` line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtqu-u3yCfRp9GpJwg:-NCzJvvH5RqIRt_0xRMr:b4un5z2) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.cc#L58)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I suppose you meant a blank line? Done.
</blockquote></details>

yes, a blank line. Thanks.
___
*[`multibody/plant/deformable_driver.cc` line 162 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCzL8kVCLTb5eaJMU1g:-NCzL8kWAhTfFW2J56yV:b-mjwo2c) ([raw file](https://github.com/robotlocomotion/drake/blob/6003b18f88c3d0883430334638d41b9e95cec7c5/multibody/plant/deformable_driver.cc#L162)):*
> ```cpp
>   next_fem_state->SetPositions(free_motion_state.GetPositions());
>   next_fem_state->SetVelocities(free_motion_state.GetVelocities());
>   next_fem_state->SetAccelerations(free_motion_state.GetAccelerations());
> ```

nvm, I believe I answered this to myself. The idea here is that you'll call something like EvalContactComputation() and this would only copy/paste updated values to the appropriate FemState objects.
___
*[`multibody/plant/test/deformable_driver_test.cc` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCttaqG6PXQkD50DFb2:-NCzKd_QACiwueyqMOap:b-xiif4) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/test/deformable_driver_test.cc#L144)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Also probably worth mentioning that the goal of the unit test here is to test invocation of the solver in deformable driver. The solver itself is tested in FemSolverTest and the physics is tested in model and element tests.

We will eventually have an integration test that combines all these components (including contact).
</blockquote></details>

Thank for the explanation. You might want to put a note here with these observations.

IMO 1e-4 m/s for a tolerance seems a bit loose, specially for a simple test with no contact. There might be a chance to tighten this tolerance in the physics test you mention above.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[`multibody/plant/deformable_driver.cc` line 162 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCzL8kVCLTb5eaJMU1g:-NCzd6YC44rYnPBS0dYB:b-s85pv4) ([raw file](https://github.com/robotlocomotion/drake/blob/6003b18f88c3d0883430334638d41b9e95cec7c5/multibody/plant/deformable_driver.cc#L162)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nvm, I believe I answered this to myself. The idea here is that you'll call something like EvalContactComputation() and this would only copy/paste updated values to the appropriate FemState objects.
</blockquote></details>

Yeah, that too. I forgot about this.
___
*[`multibody/plant/test/deformable_driver_test.cc` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCttaqG6PXQkD50DFb2:-NCzdJwQ9WWRyybgwOlL:bcnse58) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/test/deformable_driver_test.cc#L144)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Thank for the explanation. You might want to put a note here with these observations.

IMO 1e-4 m/s for a tolerance seems a bit loose, specially for a simple test with no contact. There might be a chance to tighten this tolerance in the physics test you mention above.
</blockquote></details>

Yes we should. That should happen when I address the TODO I added in r3.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955#-:-ND-c1fH4fcWtAmKlOG9:bnfp4nl)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/plant/deformable_driver.cc` line 43 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17955#-ND-RGlUCM2ygpc7QwSG:-ND-RGlUCM2ygpc7QwSH:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/6003b18f88c3d0883430334638d41b9e95cec7c5/multibody/plant/deformable_driver.cc#L43)):*
> ```cpp
>     DiscreteUpdateManager<T>* manager) {
>   DRAKE_DEMAND(manager_ == manager);
>   std::vector<fem::FemState<T>> foo;
> ```

unused?
___
*[`multibody/plant/deformable_driver.cc` line 59 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17955#-ND-T1tsBcFKNwX4uFui:-ND-T1tsBcFKNwX4uFuj:b-yowdkk) ([raw file](https://github.com/robotlocomotion/drake/blob/6003b18f88c3d0883430334638d41b9e95cec7c5/multibody/plant/deformable_driver.cc#L59)):*
> ```cpp
>                 }}),
>         {systems::System<T>::xd_ticket()});
> ```

nit this seems like an odd place to add the blank line, given the layout of similar stanzas here.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @rpoyner-tri)

___
*[`multibody/plant/deformable_driver.h` line 101 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17955#-NCtomK3Ew4VNHgcoDNI:-ND-pjfn5Lvnzu_5W888:b-l5gx4) ([raw file](https://github.com/robotlocomotion/drake/blob/5ceacc1bc22a089b1375e9c20f6315205fb23d7d/multibody/plant/deformable_driver.h#L101)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I see how the non-copyability of FemState make things awkward .
</blockquote></details>

I think this is resolved.
___
*[`multibody/plant/deformable_driver.cc` line 43 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17955#-ND-RGlUCM2ygpc7QwSG:-ND-pnt92L80EsIrbx2-:byn2o3b) ([raw file](https://github.com/robotlocomotion/drake/blob/6003b18f88c3d0883430334638d41b9e95cec7c5/multibody/plant/deformable_driver.cc#L43)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done (oops).
___
*[`multibody/plant/deformable_driver.cc` line 59 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17955#-ND-T1tsBcFKNwX4uFui:-ND-q1Qn9UiS0GfzkJXH:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/6003b18f88c3d0883430334638d41b9e95cec7c5/multibody/plant/deformable_driver.cc#L59)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit this seems like an odd place to add the blank line, given the layout of similar stanzas here.
</blockquote></details>

Done, thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri to satisfy reviewable.

> Dismissed @amcastro-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17955#-:-ND04w5cDJXeEQHK-141:b-xx4ukd)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Pull request merged**
