### PR TITLE
Move Parameters from LeafContext to Context.

### LINKED ISSUE #5072: Promote Parameters from LeafContext to Context
Contrary to my original belief, there are a few reasons we might want to reason about Parameters independent of a particular LeafSystem's semantics.  One of these is to measure symbolic sparsity.

I vaguely recall that @jadecastro had some other reasons.

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #5072.

@jadecastro for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5467)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Pushed some additional test coverage for Parameters on non-double scalartypes.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-:-KetcYkW3PLNO9uOxwlZ:bvenur9)*

**Comment by jadecastro** [comment]
Reviewed 9 of 14 files at r1.
Review status: 9 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467)*

**Comment by jadecastro** [comment]
Great! One comment but :lgtm: otherwise.

---

Reviewed 5 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/parameters.h, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf-2NkoY1wdt5aCx-g5:-Kf-2NkpczJiolQRXolW:buxuuak) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/parameters.h#L142)):*
> ```objc
>   /// Parameters<double>. All scalar types in Drake must support
>   /// initialization from doubles.
>   void SetFrom(const Parameters<double>& other) {
> ```

BTW, consider validity-checking `other`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-:-Kf-5nYrq6cFpS5md0K6:bqeq1ot)*

**Comment by david-german-tri** [comment]
+@sherm1 for platform review

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-:-Kf6xEkEN-IqDc15WarP:buasbda)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/parameters.h, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf-2NkoY1wdt5aCx-g5:-Kf7I6IP1W77xwpfzJhy:bp9z3bn) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/parameters.h#L142)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, consider validity-checking `other`.
</blockquote></details>

The `SetFrom` and `CopyFrom` calls do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467)*

**Comment by sherm1** [comment]
Platform: some BTWs to consider, then :lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/systems/framework/abstract_state.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf8zc4Pr-ULI51ajkF7:-Kf8zc4Pr-ULI51ajkF8:b-90olf8) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/abstract_state.h#L33)):*
> ```objc
>   explicit AbstractState(const std::vector<AbstractValue*>& data);
> 
>   /// Constructs a discrete state that owns a single @p datum.
> ```

BTW discrete->abstract

---

*[drake/systems/framework/context.h, line 314 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf9-Xc_nVaCjH7ZIY_2:-Kf9-Xc_nVaCjH7ZIY_3:bx4nmkh) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/context.h#L314)):*
> ```objc
>   /// Returns a const pointer to the vector-valued parameter at @p index.
>   /// Asserts if @p index doesn't exist.
>   const BasicVector<T>* get_numeric_parameter(int index) const {
> ```

BTW, is nullptr a possible return? If so should say that, otherwise return type should be const ref as for AbstractValue below.

---

*[drake/systems/framework/context.h, line 320 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf9-eHuvTR6V9-AAlER:-Kf9-eHuvTR6V9-AAlES:b4gzv0k) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/context.h#L320)):*
> ```objc
>   /// Returns a mutable pointer to element @p index of the vector-valued
>   /// parameters. Asserts if @p index doesn't exist.
>   BasicVector<T>* get_mutable_numeric_parameter(int index) {
> ```

BTW, is nullptr a possible return? If so should say that, otherwise return type should be mutable ref as for AbstractValue below.

---

*[drake/systems/framework/context.h, line 324 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf9-qi0sxLakFO4APLe:-Kf9-qi0sxLakFO4APLf:baqz5bt) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/context.h#L324)):*
> ```objc
>   }
> 
>   /// Returns a const pointer to the abstract-valued parameter at @p index.
> ```

BTW, pointer->reference (and method below).

---

*[drake/systems/framework/diagram_context.h, line 198 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf91g9Ujzb1LOVCbyqG:-Kf91g9Ujzb1LOVCbyqH:b-l81mb3) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/diagram_context.h#L198)):*
> ```objc
> 
>   /// Generates the parameters for the entire diagram by wrapping the parameters
>   /// of all the constituent diagrams.
> ```

BTW, took me a while to figure out (I think) that the wrapping here is indirect rather than copied. A comment saying that would help.

---

*[drake/systems/framework/diagram_context.h, line 212 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf91QS7nLjInHUfyovk:-Kf91QS7nLjInHUfyovl:bxkm6c3) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/diagram_context.h#L212)):*
> ```objc
>       for (int i = 0; i < subparams->num_abstract_parameters(); ++i) {
>         abstract_params.push_back(
>             &subparams->get_mutable_abstract_parameter(i));
> ```

BTW, "&" here seems good; would like to see that for the numeric parameters above as well. Seems unnecessarily inconsistent.

---

*[drake/systems/framework/diagram_context.h, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf91wiBLgTr8XOYmudI:-Kf91wiBLgTr8XOYmudJ:bchxtr0) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/diagram_context.h#L219)):*
> ```objc
>         std::make_unique<DiscreteState<T>>(numeric_params));
>     parameters_->set_abstract_parameters(
>         std::make_unique<AbstractState>(abstract_params));
> ```

BTW, ouch -- took me a while to remember that "State" here gets re-used for implementing parameters. A comment noting that would help.

---

*[drake/systems/framework/diagram_context.h, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf906B8wL41wnzAtAIx:-Kf906B8wL41wnzAtAIy:b-yjuebd) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/diagram_context.h#L282)):*
> ```objc
>   }
> 
>   Parameters<T>* get_mutable_parameters() final {
> ```

BTW, is there any reason this can't return a mutable reference instead of a pointer? That is preferable IMO. For one thing, if you have a function `f(Parameters<T>*)` that does something to the parameters, you can call it with `f(&get_mutable_parameters())` giving it that pretty output-parameter look that the style guide loves.

Otherwise should document under what conditions a nullptr is returned.

---

*[drake/systems/framework/leaf_context.h, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf92Jhhvcr0oX6JpJ8V:-Kf92JhiCzf-zS5R8mYg:b-t2n9rl) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/leaf_context.h#L125)):*
> ```objc
> 
>   /// Returns the entire Parameters object.
>   Parameters<T>* get_mutable_parameters() final {
> ```

BTW, mutable ref instead? Or doc when this will be nullptr.

---

*[drake/systems/framework/parameters.h, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf92nzIxwqWqYWeuCDe:-Kf92nzIxwqWqYWeuCDf:b-k8qvq6) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/parameters.h#L86)):*
> ```objc
>   }
> 
>   const DiscreteState<T>& get_numeric_parameters() const {
> ```

BTW, should document the odd return type here (and anywhere else it leaks through the API). (This should get renamed `DiscreteValues` or something like that eventually.)

I don't think this is unit tested, though I can live without it! But should it be private?

---

*[drake/systems/framework/parameters.h, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf937aoF_cBzBZ3QKYy:-Kf937aoF_cBzBZ3QKYz:b-vedqkd) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/parameters.h#L122)):*
> ```objc
>   }
> 
>   const AbstractState& get_abstract_parameters() const {
> ```

BTW, API doc for weird return type would be good.

Should this be private?

---

*[drake/systems/framework/test/abstract_state_test.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf93O9UCTV4rN0excq1:-Kf93O9UCTV4rN0excq2:bnlw575) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/test/abstract_state_test.cc#L40)):*
> ```cpp
> 
> TEST_F(AbstractStateTest, SingleValueConstructor) {
>   AbstractState xm(PackValue<int>(1000));
> ```

BTW, we've been using `xa` for these things ever since we stopped calling them "mode" variables.

---

*[drake/systems/framework/test/parameters_test.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf94wZb2bam9LiRzwa3:-Kf94wZckt_nXAIssFrE:b-4v72e5) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/test/parameters_test.cc#L91)):*
> ```cpp
>   const auto& p1 = *symbolic_params->get_numeric_parameter(1);
>   EXPECT_EQ("9", p1.GetAtIndex(0).to_string());
>   EXPECT_EQ("12", p1.GetAtIndex(1).to_string());
> ```

BTW, neat!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-:-Kf96-xYW-5zgCyu5LKL:bcmhau9)*

**Comment by david-german-tri** [comment]
Review status: 6 of 15 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/systems/framework/abstract_state.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf8zc4Pr-ULI51ajkF7:-KfDfldeNfgken0VqyJY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/abstract_state.h#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW discrete->abstract
</blockquote></details>

Done.

---

*[drake/systems/framework/context.h, line 314 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf9-Xc_nVaCjH7ZIY_2:-KfDgVbZQg_kaA0RTbSI:b-p6ngr) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/context.h#L314)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, is nullptr a possible return? If so should say that, otherwise return type should be const ref as for AbstractValue below.
</blockquote></details>

This is pre-existing (just moved from LeafContext), so I'm going to leave it as-is for now.

---

*[drake/systems/framework/context.h, line 320 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf9-eHuvTR6V9-AAlER:-KfDgZXyz54iIPbQDSk8:b-p6ngr) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/context.h#L320)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, is nullptr a possible return? If so should say that, otherwise return type should be mutable ref as for AbstractValue below.
</blockquote></details>

This is pre-existing (just moved from LeafContext), so I'm going to leave it as-is for now.

---

*[drake/systems/framework/context.h, line 324 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf9-qi0sxLakFO4APLe:-KfDglaMKHSBgUSlf02B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/context.h#L324)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, pointer->reference (and method below).
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram_context.h, line 198 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf91g9Ujzb1LOVCbyqG:-KfDhYW5nuC08NsVxM2O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/diagram_context.h#L198)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, took me a while to figure out (I think) that the wrapping here is indirect rather than copied. A comment saying that would help.
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram_context.h, line 212 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf91QS7nLjInHUfyovk:-KfDhdM0Lth7GpTmnltS:b1k5shj) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/diagram_context.h#L212)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, "&" here seems good; would like to see that for the numeric parameters above as well. Seems unnecessarily inconsistent.
</blockquote></details>

Same pre-existing thing as above.

---

*[drake/systems/framework/diagram_context.h, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf91wiBLgTr8XOYmudI:-KfDhpbyVofwLdZZX_dh:bebqyz0) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/diagram_context.h#L219)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, ouch -- took me a while to remember that "State" here gets re-used for implementing parameters. A comment noting that would help.
</blockquote></details>

#5490 - I'll do it in a follow-up PR.

---

*[drake/systems/framework/diagram_context.h, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf906B8wL41wnzAtAIx:-KfDlo1wxvt6D9KACSzW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/diagram_context.h#L282)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, is there any reason this can't return a mutable reference instead of a pointer? That is preferable IMO. For one thing, if you have a function `f(Parameters<T>*)` that does something to the parameters, you can call it with `f(&get_mutable_parameters())` giving it that pretty output-parameter look that the style guide loves.

Otherwise should document under what conditions a nullptr is returned.
</blockquote></details>

Done.

---

*[drake/systems/framework/leaf_context.h, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf92Jhhvcr0oX6JpJ8V:-KfDlpm41DVqWR_j-Gz1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/leaf_context.h#L125)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, mutable ref instead? Or doc when this will be nullptr.
</blockquote></details>

Done.

---

*[drake/systems/framework/parameters.h, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf92nzIxwqWqYWeuCDe:-KfDi7qoS6kF7pyG7AGj:b-gcuorl) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/parameters.h#L86)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, should document the odd return type here (and anywhere else it leaks through the API). (This should get renamed `DiscreteValues` or something like that eventually.)

I don't think this is unit tested, though I can live without it! But should it be private?
</blockquote></details>

Can't be private because it needs to work across scalar types.  Added a test.

---

*[drake/systems/framework/parameters.h, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf937aoF_cBzBZ3QKYy:-KfDiHhv1Lu9KkjjGEnP:b-gcuorl) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/parameters.h#L122)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, API doc for weird return type would be good.

Should this be private?
</blockquote></details>

Can't be private because it needs to work across scalar types.  Added a test.

---

*[drake/systems/framework/test/abstract_state_test.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-Kf93O9UCTV4rN0excq1:-KfDjWAhbtcKISTT2JmH:b-8sdwej) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d9e05d4f9ee5831be9be1397f4e51ca349282a/drake/systems/framework/test/abstract_state_test.cc#L40)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, we've been using `xa` for these things ever since we stopped calling them "mode" variables.
</blockquote></details>

#5491

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467)*

**Comment by sherm1** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467)*

**Comment by jadecastro** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for automotive

---

Review status: 15 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-:-KfE2H6csCpBcesnwv24:byljzen)*

**Comment by jadecastro** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467)*

**Comment by jwnimmer-tri** [comment]
:car: honk honk

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5467#-:-KfE6XleOjWiIh00tm29:b-93srut)*

**Pull request merged**
