### PR TITLE
[workspace] Fix cpplint vs Python 3.11

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18788)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please

+@svenevs for feature review, please.

**Comment by jwnimmer-tri** [comment]
-@svenevs  +@sammy-tri for both reviews per schedule, please.

**Review by svenevs — COMMENTED** [review]
+@svenevs sorry for being late to the party, this does :lgtm_strong: :interrobang:

FYI Sam this is a followup to #18786, the fact that mac-arm CI passed on this indicates the change is good.  Previously the test would fail:

```
==================== Test output for //tools/workspace/styleguide:cpplint_unittest:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/sandbox/darwin-sandbox/3/execroot/drake/bazel-out/darwin_arm64-opt/bin/tools/workspace/styleguide/cpplint_unittest.runfiles/styleguide/cpplint/cpplint_unittest.py", line 55, in <module>
    class ErrorCollector(object):
  File "/private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/sandbox/darwin-sandbox/3/execroot/drake/bazel-out/darwin_arm64-opt/bin/tools/workspace/styleguide/cpplint_unittest.runfiles/styleguide/cpplint/cpplint_unittest.py", line 57, in ErrorCollector
    _ERROR_CATEGORIES = cpplint._ERROR_CATEGORIES
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cpplint' has no attribute '_ERROR_CATEGORIES'
================================================================================
Target //tools/workspace/styleguide:cpplint_unittest up-to-date:
  bazel-bin/tools/workspace/styleguide/cpplint_unittest
INFO: Elapsed time: 1.656s, Critical Path: 0.13s
INFO: 2 processes: 2 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//tools/workspace/styleguide:cpplint_unittest                            FAILED in 0.1s
  /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/tools/workspace/styleguide/cpplint_unittest/test.log
```

With the changes here in CI and locally it works as expected :partying_face:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18788#-:-NOQejsb7U4XDFn-uZUM:b-rb41hs)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

___
*[`tools/workspace/styleguide/patches/test_paths.patch` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18788#-NOQfkSu3ONg0QRESHTY:-NOQfkSu3ONg0QRESHTZ:b-41gg3f) ([raw file](https://github.com/RobotLocomotion/drake/blob/b4b73a6443f1bc04b422f712b33fb1ceb36c40b6/tools/workspace/styleguide/patches/test_paths.patch#L18)):*
> ```Diff
>  
>  try:
>    xrange          # Python 2
> ```

nit: can we add a newline to the end of the file?  I did it locally and the patch still applies fine.

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (pending nit)

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18788#-:-NOR1sR_7DH3R8LcIg62:b-s4udou)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Pull request merged**
