### PR TITLE
add extra constraints to trajectory optimization example

### PR DESCRIPTION
**Pull request by RussTedrake**
was doing it to see if I could make IPOPT work for this example.  the change wasn't quite enough to re-enable IPOPT, but it did seem to help.  and I think the code is better.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6868)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jadecastro for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-:-Krm4SHej5Mt3yg2ia5-:b-5tror9)*

**Comment by jadecastro** [comment]
:lgtm:

Just a side note: I played a bit with increasing `max_iter`, `tol` and tightening the bounding box and knot-point constraints to see if anything would make IPOPT cough up the optimal solution.  Nothing I tried seemed to make a difference.  However, what did work was when I posed the problem as a steering-only problem (keeping acceleration zero - i.e. setting `prog.AddConstraintToAllKnotPoints(input.acceleration() == 0.0);`), and bumping the tolerance slightly:
```
prog.SetSolverOption(solvers::IpoptSolver::id(), "tol", 1e-7);
```
(note that this requires the header `#include "drake/solvers/ipopt_solver.h"`).

If you think it's worthwhile to have this solve the steering-only problem so that we can re-enable IPOPT, we can either change this implementation here, or else I can submit a new PR.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-:-KrmBTtpP-sflLpvj3LL:b-s5cql1)*

**Comment by RussTedrake** [comment]
thanks jon.  cc @frankpermenter -- as I was discussing this with him today.  

i'd personally rather have both steering and acceleration in the example, but your experiment convinces me that it's likely numerical conditioning that is giving IPOPT a hard time.  The units range from @ 450 (meters traveled) in `x` to very nearly zero (IPOPT's intermediate solutions were very small, maybe 1e-4?) for the acceleration input command.  

That makes me think that we could probably resolve the issue if we did some manual rescaling of the coordinates.  But wow, I wouldn't think that we should have to.  

i'll push this to platform to get it in, and we can improve from there.
+@jwnimmer-tri as Monday's platform reviewer (i think we've missed friday, and i'm happy to get your eyes on this one)

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-:-Krs1iFBIXcB89-3-0ee:b-z4cr5n)*

**Comment by RussTedrake** [comment]
cc @tkoolen (who had some ideas about IPOPT, too)

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-:-Krs4Onz42LQOWJaJfwu:b-2kes6)*

**Comment by soonho-tri** [comment]
@russtedrake : AFAIK, -@jwnimmer-tri is on vacation next week and +@EricCousineau-tri is on call next Monday.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-:-Krs6U5tUjwzDGYB1TJk:b-iqssik)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4DqrO7LbBVZkdju7j:-Ks4DqrO7LbBVZkdju7k:b-soojp7) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/automotive/test/trajectory_optimization_test.cc#L20)):*
> ```cpp
> GTEST_TEST(TrajectoryOptimizationTest, SimpleCarDircolTest) {
>   SimpleCar<double> plant;
>   auto context = plant.CreateDefaultContext();
> ```

BTW Return type may not be obvious at this call-site.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4Cr8oMGV1U7FVEVz1:-Ks4Cr8p2088HNVSjCe_:bl9yl33) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/automotive/test/trajectory_optimization_test.cc#L50)):*
> ```cpp
>           context->get_numeric_parameter(0));
>   DRAKE_DEMAND(params != nullptr);
>   const double kConstraintLimitScaling{
> ```

BTW If inverted, this could be renamed to `kConstraintSafetyFactor` (mayhaps `kInverseSafetyFactor`?)

---

*[drake/solvers/ipopt_solver.cc, line 179 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4D8SG-nN2-zm3qtSv:-Ks4D8SG-nN2-zm3qtSw:btiai8d) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/solvers/ipopt_solver.cc#L179)):*
> ```cpp
> 
>     // The IPOPT interface defines eval_f() and eval_grad_f() as
>     // ouputing a single Number for the result, and the size of the
> ```

BTW Spellling "ouputing" -> "outputting", and grammar, "Number" -> "number"?

---

*[drake/solvers/ipopt_solver.cc, line 404 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4DXhcabr_kuE8BKBU:-Ks4DXhcabr_kuE8BKBV:b-y03f4u) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/solvers/ipopt_solver.cc#L404)):*
> ```cpp
>       case Ipopt::MAXITER_EXCEEDED: {
>         result_ = SolutionResult::kIterationLimit;
>         std::cout << "Hint: Remember that IPOPT is an interior-point method "
> ```

BTW Could this be changed to `drake::log()->info()` or `warn()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with minor BTWs.

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-:-Ks5GVlBIC6N0TsnYhxL:b-715d9c)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4DqrO7LbBVZkdju7j:-Ks5qfQ_e3DOdDloTF4t:b677da0) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/automotive/test/trajectory_optimization_test.cc#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Return type may not be obvious at this call-site.
</blockquote></details>

we use auto on CreateDefaultContext throughout the codebase, no?  i think it's sufficiently clear.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4Cr8oMGV1U7FVEVz1:-Ks5tbgZgMKdVfsIDSUb:bcz27wk) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/automotive/test/trajectory_optimization_test.cc#L50)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW If inverted, this could be renamed to `kConstraintSafetyFactor` (mayhaps `kInverseSafetyFactor`?)
</blockquote></details>

Done.  (i think safety factor is ok without inverting anything)

---

*[drake/solvers/ipopt_solver.cc, line 179 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4D8SG-nN2-zm3qtSv:-Ks5t3twMRr6m-k9onM-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/solvers/ipopt_solver.cc#L179)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Spellling "ouputing" -> "outputting", and grammar, "Number" -> "number"?
</blockquote></details>

Done.

---

*[drake/solvers/ipopt_solver.cc, line 404 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4DXhcabr_kuE8BKBU:-Ks5sV8ICdTU0okhkuwV:b-ri2b7d) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/solvers/ipopt_solver.cc#L404)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could this be changed to `drake::log()->info()` or `warn()`?
</blockquote></details>

sigh.  yes.  that's definitely the right answer.  but i've never actually logged at a log file; it's not part of my workflow.  i guess i need to change my workflow.  (and we should suggest others do as well?  there are ZERO hits in the sphinx documentation when I search for it... i don't even know where the log files are?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4DqrO7LbBVZkdju7j:-Ks5yXCEsfBw97wIkb4f:b-ir01qk) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/automotive/test/trajectory_optimization_test.cc#L20)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

we use auto on CreateDefaultContext throughout the codebase, no?  i think it's sufficiently clear.
</blockquote></details>

Yup, we do. Sounds good!

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4Cr8oMGV1U7FVEVz1:-Ks5ykR519e74PCG4HPf:b-fo6o94) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/automotive/test/trajectory_optimization_test.cc#L50)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  (i think safety factor is ok without inverting anything)
</blockquote></details>

BTW Just a small concern is that a safety factor < 1 implies that you will definitely hit your failure modes (active constraint / constraint violation) within your working limits, at least according to `Safety Factor = Failure Bounds / Design Bounds`.

---

*[drake/solvers/ipopt_solver.cc, line 404 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4DXhcabr_kuE8BKBU:-Ks5zd75DIoPNqUSLv-g:bewualj) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/solvers/ipopt_solver.cc#L404)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

sigh.  yes.  that's definitely the right answer.  but i've never actually logged at a log file; it's not part of my workflow.  i guess i need to change my workflow.  (and we should suggest others do as well?  there are ZERO hits in the sphinx documentation when I search for it... i don't even know where the log files are?)
</blockquote></details>

TBH I've only really used console logging - I prefer using logging because at some point it would enable file logging, though.

I will create an issue for myself to add a quick tutorial to Sphinx on configuring `spdlog` within Drake to log to file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868)*

**Comment by RussTedrake** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4Cr8oMGV1U7FVEVz1:-Ks6c_FdCMeBOs0iVdSf:b-qssebl) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/automotive/test/trajectory_optimization_test.cc#L50)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Just a small concern is that a safety factor < 1 implies that you will definitely hit your failure modes (active constraint / constraint violation) within your working limits, at least according to `Safety Factor = Failure Bounds / Design Bounds`.
</blockquote></details>

fixed.

---

*[drake/solvers/ipopt_solver.cc, line 404 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4DXhcabr_kuE8BKBU:-Ks6bNIsDKH4j8I1IfFB:bcbxbs4) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/solvers/ipopt_solver.cc#L404)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

TBH I've only really used console logging - I prefer using logging because at some point it would enable file logging, though.

I will create an issue for myself to add a quick tutorial to Sphinx on configuring `spdlog` within Drake to log to file.
</blockquote></details>

oops.  sorry.  console logging is (probably) way better for me.  how do I enable it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868)*

**Comment by EricCousineau-TRI** [comment]
*[drake/solvers/ipopt_solver.cc, line 404 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6868#-Ks4DXhcabr_kuE8BKBU:-Ks9Ld6BImXPx5fKrZOK:b-sj34ep) ([raw file](https://github.com/robotlocomotion/drake/blob/33d9e899b29dc404858f9441281a21c906a93070/drake/solvers/ipopt_solver.cc#L404)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

oops.  sorry.  console logging is (probably) way better for me.  how do I enable it?
</blockquote></details>

I believe the default level is `info` (that should go to either `stderr` or `stdout`, I believe), but you can set it to `debug` or `trace` like what's used in `text_logging_gflags.h`:
https://github.com/RobotLocomotion/drake/blob/9a2041af0943fad09938e71db9d219b6bf382278/drake/common/text_logging_gflags.h#L32

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6868)*

**Pull request merged**
