### PR TITLE
Renamed "model_id" to be "model_instance_id".

### PR DESCRIPTION
**Pull request by liangfok**
Per discussion with @sherm1, @amcastro-tri, and @david-german-tri yesterday. This is the first of a long sequence of PRs with the end goal of enabling simulations that involve more than one model instance.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3037)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review (you're the only non-platform reviewer who attended yesterday's meeting)
+@sherm1 for platform review (it's not Monday but you have direct knowledge of yesterday's meeting)


@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOFpA1PzAkt7QDhGbeg:1457798467)*

**Comment by sherm1** [comment]
Thanks, Liang! Review pass done -- a few comments/questions.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGHU8pZXrtXT2t36i8:-KOGHU8qfY4YzudbxuzC:-1149237408) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L26)):*
> ```objc
> 
>   /**
>    * @returns The name of this rigid body.
> ```

Please check if this formats correctly in Doxygen. I think it might end up with no brief if there isn't an opening sentence. If so, just change this to "Returns the name of this rigid body." -- using the `@returns` command doesn't actually add anything useful here.

---

*[drake/systems/plants/RigidBody.h, line 36 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGHxK16Q9eR9SeSTLW:-KOGHxK16Q9eR9SeSTLX:-1580047692) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L36)):*
> ```objc
> 
>   /**
>    * @returns The name of the model containing this rigid body.
> ```

Two comments here: (1) doxygen formatting probably missing a brief. (2) Since this is the name of a *model* and not an *instance* I would prefer a different verb than "containing". How about "defining"?

---

*[drake/systems/plants/RigidBody.h, line 42 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGIKwRbzCgzHXyJPR-:-KOGIKwRbzCgzHXyJPR0:-676800101) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L42)):*
> ```objc
> 
>   /**
>    * Sets the name of the model to which this rigid body belongs.
> ```

"... the model defining this rigid body" ?

---

*[drake/systems/plants/RigidBody.h, line 44 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGJqpoHzcc2k9ZO9-o:-KOGJqpoHzcc2k9ZO9-p:-256455699) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L44)):*
> ```objc
>    * Sets the name of the model to which this rigid body belongs.
>    */
>   void set_model_name(const std::string& name);
> ```

BTW, separate question: is it necessary to store the model name here at all? Is that being done in every element? Since the `model_instance_id` is unique across all models it could map unambiguously to a particular model name without that having to be stored locally.

---

*[drake/systems/plants/RigidBody.h, line 296 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGJ-lQDu9Wo-isLPGv:-KOGJ-lQDu9Wo-isLPGw:-289535006) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L296)):*
> ```objc
>   std::string name_;
> 
>   // The name of the model to which this rigid body belongs.
> ```

"The name of the model that defined this rigid body." ?

---

*[drake/systems/plants/RigidBody.h, line 299 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGJ70pBgKsEeaAJez4:-KOGJ70pBgKsEeaAJez5:-391995654) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L299)):*
> ```objc
>   std::string model_name_;
> 
>   // A unique ID for each model. It uses 0-index, starts from 0.
> ```

"A unique ID for the model instance to which this body belongs."

Since this ID is generated elsewhere I wouldn't attempt to describe how it is generated here. However, I think it would be better to initialize it to something illegal if possible since a RigidBody isn't allowed to assign itself an instance ID.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 835 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGK_heyjTTfocZyZox:-KOGK_heyjTTfocZyZoy:-1573924442) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBodySystem.cpp#L835)):*
> ```cpp
>   // added to this RigidBodySystem multiple times. This is feasible since the
>   // rigid bodies that belong to a particular model are all assigned a model
>   // instance ID that's unique to that model.
> ```

Aren't the instance IDs unique across *all* models?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOGL_eCzkJEB4z_hu6h:1528583570)*

**Comment by amcastro-tri** [comment]
Reviewed 12 of 13 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGL9w1HtSJCyN4xwNO:-KOGL9w2xLHLTZpqNxsH:-2003057509) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBodyTree.h#L102)):*
> ```objc
>    * within this rigid body tree. Note that this method is not thread safe!
>    */
>   int get_next_model_instance_id() { return next_model_instance_id_++; }
> ```

This method should not be public API.
I'd prefer having a method `get_number_of_model_instances()` which by the way would return the same number and can be used in your logic to assign a new model instance ID when parsing. 

---

*[drake/systems/plants/RigidBodyTree.h, line 832 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGKu_7EyV9HpPKlUJk:-KOGKu_7EyV9HpPKlUJl:881837133) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBodyTree.h#L832)):*
> ```objc
>   // Remembers the ID that should be assigned to the next model instance that is
>   // added to this rigid body tree.
>   int next_model_instance_id_{};
> ```

Why not to call this `number_of_model_instantces_`? which by the way would be the same number as `next_model_instance_id_`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks.

---

Review status: 9 of 13 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGHU8pZXrtXT2t36i8:-KOHu-UdmOfsHMH6oGeM:837883774) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Please check if this formats correctly in Doxygen. I think it might end up with no brief if there isn't an opening sentence. If so, just change this to "Returns the name of this rigid body." -- using the `@returns` command doesn't actually add anything useful here.
</details>
Done.  See screenshot below.



---

*[drake/systems/plants/RigidBody.h, line 36 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGHxK16Q9eR9SeSTLW:-KOHbGiEZRIepAMeQbaC:-17903571) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L36)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Two comments here: (1) doxygen formatting probably missing a brief. (2) Since this is the name of a *model* and not an *instance* I would prefer a different verb than "containing". How about "defining"?
</details>
Done. I think "defining" is good. See above screenshot.

---

*[drake/systems/plants/RigidBody.h, line 42 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGIKwRbzCgzHXyJPR-:-KOHbZIDz62Q46RrMzPa:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "... the model defining this rigid body" ?
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 44 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGJqpoHzcc2k9ZO9-o:-KOHc_T3h--7Re1_4v_t:-1920422499) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L44)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, separate question: is it necessary to store the model name here at all? Is that being done in every element? Since the `model_instance_id` is unique across all models it could map unambiguously to a particular model name without that having to be stored locally.
</details>
I agree it's no longer necessary to store the model name in each modeling element. However, doing that in this PR will make this PR too big. Thus: #3053.

---

*[drake/systems/plants/RigidBody.h, line 296 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGJ-lQDu9Wo-isLPGv:-KOHd1sPmNzwtKbtsw0I:378976374) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L296)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "The name of the model that defined this rigid body." ?
</details>
Done. I also added a TODO comment saying this variable should be removed.

---

*[drake/systems/plants/RigidBody.h, line 299 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGJ70pBgKsEeaAJez4:-KOHdAgzjDUqn0a02bNi:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBody.h#L299)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "A unique ID for the model instance to which this body belongs."
> 
> Since this ID is generated elsewhere I wouldn't attempt to describe how it is generated here. However, I think it would be better to initialize it to something illegal if possible since a RigidBody isn't allowed to assign itself an instance ID.
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 835 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGK_heyjTTfocZyZox:-KOHdiaYU2nUsk5jWntt:-757288433) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBodySystem.cpp#L835)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Aren't the instance IDs unique across *all* models?
</details>
Correct. I polished the text some more.

---

*[drake/systems/plants/RigidBodyTree.h, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGL9w1HtSJCyN4xwNO:-KOHfDbngQCbVzPKtIZh:1263044385) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBodyTree.h#L102)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> This method should not be public API.
> I'd prefer having a method `get_number_of_model_instances()` which by the way would return the same number and can be used in your logic to assign a new model instance ID when parsing. 
</details>
Done. I renamed `get_current_model_instance_id()` to be `get_number_of_model_instances()` and `get_next_model_instance_id()` to be `get_new_model_instance_id()`.

---

*[drake/systems/plants/RigidBodyTree.h, line 832 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGKu_7EyV9HpPKlUJk:-KOHee55m2bOGTNu6T3J:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBodyTree.h#L832)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Why not to call this `number_of_model_instantces_`? which by the way would be the same number as `next_model_instance_id_`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOHegO7MJiuaM_Es36a:701516011)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOI4ybZYLIDzPYSdyqY:1417088721)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOI5MPfpXZtQf6tzhuP:670272675)*

**Comment by liangfok** [comment]
This PR passed all CI tests and is thus ready for feature review from @amcastro-tri.

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOKjxj4wD5FuTUwTarg:-KOKjxj4wD5FuTUwTarh:-1108591907) ([raw file](https://github.com/robotlocomotion/drake/blob/485882e689c852e80ccdde3f76f7c5102c864d87/drake/systems/plants/RigidBodyTree.h#L102)):*
> ```objc
>    * the model instance. This method is not thread safe!
>    */
>   int get_new_model_instance_id() { return number_of_model_instances_++; }
> ```

This effectively adds a model instance to the tree. Why not something like?
 ```C++
 /**
   * Adds a new model instance to this `RigidBoydTree`.
   * @returns the id of the newly added model instance.
   */
  int add_model_instance() { return number_of_model_instances_++; }
```

What I mean is that usually our get (`get_`) methods in drake usually are const so this could be a bad API for users.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGL9w1HtSJCyN4xwNO:-KOKpP290WLCvtW_xETA:1499093473) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBodyTree.h#L102)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. I renamed `get_current_model_instance_id()` to be `get_number_of_model_instances()` and `get_next_model_instance_id()` to be `get_new_model_instance_id()`.
</details>
@amcastro-tri this thread is awaiting your ack.

---

*[drake/systems/plants/RigidBodyTree.h, line 832 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOGKu_7EyV9HpPKlUJk:-KOKq23XBpNP8YunDtan:1499093473) ([raw file](https://github.com/robotlocomotion/drake/blob/c230d7449e512bf5baf82e5061d135ad3aab8e1c/drake/systems/plants/RigidBodyTree.h#L832)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
@amcastro-tri this thread is awaiting your ack.

---

*[drake/systems/plants/RigidBodyTree.h, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOKjxj4wD5FuTUwTarg:-KOKq-wDP_lV_0hIxvFQ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/485882e689c852e80ccdde3f76f7c5102c864d87/drake/systems/plants/RigidBodyTree.h#L102)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> This effectively adds a model instance to the tree. Why not something like?
>  ```C++
>  /**
>    * Adds a new model instance to this `RigidBoydTree`.
>    * @returns the id of the newly added model instance.
>    */
>   int add_model_instance() { return number_of_model_instances_++; }
> ```
> 
> What I mean is that usually our get (`get_`) methods in drake usually are const so this could be a bad API for users.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOKq5f19shCoq6sfZlR:-84625242)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOKqNUeI7ScVehX2dwt:670272675)*

**Comment by amcastro-tri** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOKjxj4wD5FuTUwTarg:-KOL4JDbyOSvLc2Dpe8C:-1456763855) ([raw file](https://github.com/robotlocomotion/drake/blob/485882e689c852e80ccdde3f76f7c5102c864d87/drake/systems/plants/RigidBodyTree.h#L102)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
Maybe update doc so that it reflects what it conceptually does? To my understanding the method "adds a new model" and returns something useful which is a sub-product of this action, the model id.

---

*[drake/systems/plants/RigidBodyTree.h, line 829 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOL4iNCZjMvdLt6AyxE:-KOL4iNCZjMvdLt6AyxF:1252824491) ([raw file](https://github.com/robotlocomotion/drake/blob/a43fd358ac7ad6438c1e961a78eb6bddbaf4e99b/drake/systems/plants/RigidBodyTree.h#L829)):*
> ```objc
>   int num_velocities_{};
> 
>   // Remembers the number of model instances in this rigid body tree. It's also
> ```

BTW, I would remove here "Remembers the".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOKjxj4wD5FuTUwTarg:-KOL8fQ7uwatdZDhupdy:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/485882e689c852e80ccdde3f76f7c5102c864d87/drake/systems/plants/RigidBodyTree.h#L102)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Maybe update doc so that it reflects what it conceptually does? To my understanding the method "adds a new model" and returns something useful which is a sub-product of this action, the model id.
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 829 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOL4iNCZjMvdLt6AyxE:-KOL82Qz8sdik6muHrZk:620278464) ([raw file](https://github.com/robotlocomotion/drake/blob/a43fd358ac7ad6438c1e961a78eb6bddbaf4e99b/drake/systems/plants/RigidBodyTree.h#L829)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, I would remove here "Remembers the".
</details>
Done. I also simplified the description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOL8parF2aK5q-C-Six:701515998)*

**Comment by amcastro-tri** [comment]
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 103 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOL9svfkQfH8Wxwee2K:-KOL9svfkQfH8Wxwee2L:722523138) ([raw file](https://github.com/robotlocomotion/drake/blob/ba3c07f66b55d7642523ec86f620dcfcd1eda938/drake/systems/plants/RigidBodyTree.h#L103)):*
> ```objc
>    * this method call.
>    *
>    * This method is not thread safe!
> ```

Are any of the methods in this file thread safe? is it worth polluting the public API doc with this comment? if important I would just have it as a developers comment and maybe have an issue for it. Only if important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037)*

**Comment by liangfok** [comment]
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 103 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOL9svfkQfH8Wxwee2K:-KOLAa6MJfpKQvav6Wwf:-1751053829) ([raw file](https://github.com/robotlocomotion/drake/blob/ba3c07f66b55d7642523ec86f620dcfcd1eda938/drake/systems/plants/RigidBodyTree.h#L103)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Are any of the methods in this file thread safe? is it worth polluting the public API doc with this comment? if important I would just have it as a developers comment and maybe have an issue for it. Only if important.
</details>
Good point. This was a comment I had originally added at @sherm1 's suggestion. @sherm1 - are you OK removing it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037)*

**Comment by sherm1** [comment]
Replied to one question (non blocking). :lgtm:

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 103 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOL9svfkQfH8Wxwee2K:-KOLIyUbmovvudIyZXFl:1094225300) ([raw file](https://github.com/robotlocomotion/drake/blob/ba3c07f66b55d7642523ec86f620dcfcd1eda938/drake/systems/plants/RigidBodyTree.h#L103)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Good point. This was a comment I had originally added at @sherm1 's suggestion. @sherm1 - are you OK removing it?
</details>
I agree with @amcastro-tri that having it in the Doxygen is probably more confusing than helpful. However I do think it should be retained as a developer's note (`//` comment) here. The reason is that methods that hand out unique resources are usually expected to be thread safe so that they won't ever accidentally hand out the same resource twice. I don't think the other methods here would carry that same expectation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOLJnWMR0IzVtm1WyRX:1726489758)*

**Comment by liangfok** [comment]
@sherm1 and @amcastro-tri: thanks for the reviews. I'm just waiting on CI now.

---

Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 103 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-KOL9svfkQfH8Wxwee2K:-KOLRT3z6q_VwvUM-VlB:-69702878) ([raw file](https://github.com/robotlocomotion/drake/blob/ba3c07f66b55d7642523ec86f620dcfcd1eda938/drake/systems/plants/RigidBodyTree.h#L103)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I agree with @amcastro-tri that having it in the Doxygen is probably more confusing than helpful. However I do think it should be retained as a developer's note (`//` comment) here. The reason is that methods that hand out unique resources are usually expected to be thread safe so that they won't ever accidentally hand out the same resource twice. I don't think the other methods here would carry that same expectation.
</details>
Thanks. I moved the note about real-time-safety into a developer's note.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOLRc-NQP-0lJltzZcY:-1523300013)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 12 of 13 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3037#-:-KOL_A89P2ShiKW6b-NH:1417088721)*

**Pull request merged**
