### PR TITLE
Make MosekSolver::License acquire the license

### LINKED ISSUE #7077: mosek license errors fail silently
Despite the code at:
https://github.com/RobotLocomotion/drake/blob/709171b00b92e79557920329346f5500718a2caf/drake/solvers/mosek_solver.cc#L588-L596._
when my mosek license expired, i was getting numerical errors in my multiple_shooting_test instead of an announcement of the license failing.  I verified that the above code DID get called, but that the return code was still `MSK_RES_OK`.  

To reproduce, simply move `~/mosek/mosek.lic` to `~/mosek/mosek.lic.bk` and run `multiple_shooting_test`.

### PR DESCRIPTION
**Pull request by sammy-tri**
Fixes #7077

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7079)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ericcousineau-tri for feature review

Cc: @russtedrake @jamiesnape 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-:-Kue_PBLPhFT1jvemuhl:b1v84bq)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: - did a quick negative test on a branch of this [here](https://github.com/EricCousineau-TRI/drake/commit/6ae4f4bc797e72cd18107353ab376a6eebdca86b), but for some reason, even if removing the "local" tag, I couldn't make the test failing.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/mosek_solver.cc, line 599 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-Kuec1cXp6IiAYoeihyR:-Kuec1cYq2KgsBi1JP2Q:bcupptc) ([raw file](https://github.com/robotlocomotion/drake/blob/bcca8b1d55a16d1bab700e9981222a2d1d4cad81/drake/solvers/mosek_solver.cc#L599)):*
> ```cpp
>     // Acquire the license for the base MOSEK system so that we can
>     // fail fast if the license file is missing or the server is
>     // unavailable.  Any additional features should be checked out
> ```

BTW minor nit - consistency, two spaces after period (one period used elsewhere).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-:-KuegGF0cEBFtY6JHpBy:b-qu7ec9)*

**Comment by jamiesnape** [comment]
MOSEK just needs to know the home directory and we explicitly allow that here: https://github.com/RobotLocomotion/drake/blob/master/tools/bazel.rc#L46

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-:-Kuej6VinBKFbRk5d7tQ:b-dkmp83)*

**Comment by EricCousineau-TRI** [comment]
Gotcha - so the sandboxing (even in testing) permits access outside of the repository?

I had thought that the [`"local"` keyword](https://github.com/RobotLocomotion/drake/blob/master/tools/mosek.bzl#L117) is what permitted a less-strictly sandboxed run, but I guess I must have mixed that up?
If so, should we change this comment, or remove the keyword?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-:-Kuejl_skZiaihEqsvGw:b-p8lkdu)*

**Comment by jamiesnape** [comment]
In practice, the sandbox has various leaks, depending on platform. It would complain if you directly referenced the license file, it does not block the MOSEK binary from indirectly reading the file.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-:-Kuel_pwI5gdxlujfOmD:b-4758a5)*

**Comment by jwnimmer-tri** [comment]
FWIW The keyword and comment seem OK to me.  We need the keyword in order to be correct (e.g., with respect to caching, and future Bazel that locks down the sandbox to its contract more programmatically).

**Comment by EricCousineau-TRI** [comment]
Gotcha. Thank y'all for the explanation!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-:-KuenQla_72PAWIXh0N5:b-me5i94)*

**Comment by sammy-tri** [comment]
+@sherm1 for platform review

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-:-Kuexr0ot3UfZayHssEc:buasbda)*

**Comment by sammy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mosek_solver.cc, line 599 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-Kuec1cXp6IiAYoeihyR:-Kuf4263IY1ZS3tiHfe9:bbuu843) ([raw file](https://github.com/robotlocomotion/drake/blob/bcca8b1d55a16d1bab700e9981222a2d1d4cad81/drake/solvers/mosek_solver.cc#L599)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor nit - consistency, two spaces after period (one period used elsewhere).
</blockquote></details>

 Done, but only because the rest of the file was completely consistent.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079)*

**Comment by RussTedrake** [comment]
*[drake/solvers/mosek_solver.cc, line 603 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-Kuf5DTafywucyZvAi-B:-Kuf5DTafywucyZvAi-C:b-zd4vu3) ([raw file](https://github.com/robotlocomotion/drake/blob/5edab6f7927310bf222311fb1476382cd6a4b063/drake/solvers/mosek_solver.cc#L603)):*
> ```cpp
>     // possiblity of later failure at that stage if the desired
>     // feature is unavailable or another error occurs).
>     rescode = MSK_checkoutlicense(mosek_env_, MSK_FEATURE_PTS);
> ```

FYI - I heard something before (perhaps from @soonho-tri?) about a dramatic change in performance if we can check out the license just once per exe... in other words the actual license checkout can be very expensive if it has to go to a remote server.  Do we need to be mindful of that here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079)*

**Comment by sammy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mosek_solver.cc, line 603 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-Kuf5DTafywucyZvAi-B:-KufEBxzkx63NfvCcLuH:b-w4szys) ([raw file](https://github.com/robotlocomotion/drake/blob/5edab6f7927310bf222311fb1476382cd6a4b063/drake/solvers/mosek_solver.cc#L603)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

FYI - I heard something before (perhaps from @soonho-tri?) about a dramatic change in performance if we can check out the license just once per exe... in other words the actual license checkout can be very expensive if it has to go to a remote server.  Do we need to be mindful of that here?
</blockquote></details>

With this change, a program which knew it was using Mosek and wanted to hold the license could call `MosekSolver::AcquireLicense` and by holding the returned static pointer, keep the license checked out for the desired scope (e.g. the length of the program).  If we wanted this behavior to be unconditional for every program to keep the mosek lock the first time mosek is used, we'd need to use something more persistent than `GetScopedSingleton` for the mosek environment (like keeping a `never_destroyed` in this class)...  but I think that's probably worth a separate issue rather than fixing in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079)*

**Comment by RussTedrake** [comment]
*[drake/solvers/mosek_solver.cc, line 603 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-Kuf5DTafywucyZvAi-B:-KufTX6QEQzqgkQabUEo:b-fdt6ox) ([raw file](https://github.com/robotlocomotion/drake/blob/5edab6f7927310bf222311fb1476382cd6a4b063/drake/solvers/mosek_solver.cc#L603)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

With this change, a program which knew it was using Mosek and wanted to hold the license could call `MosekSolver::AcquireLicense` and by holding the returned static pointer, keep the license checked out for the desired scope (e.g. the length of the program).  If we wanted this behavior to be unconditional for every program to keep the mosek lock the first time mosek is used, we'd need to use something more persistent than `GetScopedSingleton` for the mosek environment (like keeping a `never_destroyed` in this class)...  but I think that's probably worth a separate issue rather than fixing in this PR?
</blockquote></details>

Great.  I agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079)*

**Comment by RussTedrake** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-:-KufTcekSwEK5S7dlDzb:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7079#-:-Kufbq2_YqrteYp4Ubl4:bnfp4nl)*

**Pull request merged**
