### PR TITLE
Add -Werror=shadow to clang flags in Bazel, and ensure Bazel + CMake CXX flags are similar

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This address #6544, at least for GCC and `clang` versions near `AppleClang 7.3.0`.

This was verified on this dev branch:
https://github.com/RobotLocomotion/drake/compare/master...EricCousineau-TRI:c439e88

More explanation in this comment:
https://github.com/RobotLocomotion/drake/issues/6544#issuecomment-319159000

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6721)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature and platform review, please.

My follow-up action to this PR would be to close the original issue and make a new one to find a `-Werror=shadow` with similar strictness to GCC.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-KqOyXUdFLn8St3PXxy3:b6dlcbj)*

**Comment by jwnimmer-tri** [comment]
My recollection was that `Wshadow` had too many false positives on one of our supported configs, so I guess I'm going to wait to see the full CI results before signing off.  Hopefully it just all works fine.

Please also opt-in to some appropriate subset of pre-merge OS X builds.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake.bzl, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-KqP-Eo_ELRJ3iftDAna:-KqP-EoaXo5IMnP8JYGx:bf7n0hb) ([raw file](https://github.com/robotlocomotion/drake/blob/925891706cfb99cb5cef60ca2b0581a7aef366fc/tools/drake.bzl#L11)):*
> ```Python
>     "-Werror=non-virtual-dtor",
>     "-Werror=return-stack-address",
>     # TODO(eric.cousineau): See if there is a flag with the same level of strictness
> ```

Line too long (<= 79).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-KqP-MwBsmNGVWq0Y7dg:b-xb2ydj)*

**Comment by jwnimmer-tri** [comment]
Yeah.  CI is unhappy on several configs.

**Comment by EricCousineau-TRI** [comment]
Ah, gotcha.
So we we have conflicting build configurations: due to a bug in GCC which is overzealous when shadowing methods with local variables, and an issue for `clang` which appears to flat-out obvious shadowing conflicts.

In this case, should `-Werror=shadow` be removed entirely, then, in lieu of CMake soon disappearing?
Or should we try to promote one of the pre-merge OS X builds (one that had issues earlier) to be experimental?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-KqPXJqrliXF7PE0j26d:b6dneor)*

**Comment by jwnimmer-tri** [comment]
Let's see if I have this correct:
- Per drake/CMakeLists.txt., the CMake configuration for Clang uses Werror=shadow and the GCC configuration does not.
- Per tools/drake.bzl on master, no Bazel build flavors use Werror=shadow.
- This PR adds Werror=shadow to Bazel builds for both GCC and Clang.
- This PR breaks under some GCC and Clang configurations.

Given that the CMake build has never used Werror=shadow with GCC, I am not surprised that it doesn't pass in this PR.

On the other hand, if you look at the Clang build errors, they are few in number and seem to be true defects.

So I guess my proposal is to update this PR to turn on Werror=shadow for Clang only (for Bazel).  Also conceivably to add any other flags that we lost in the CMake to Bazel transition (if any).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-KqP_G6uXnbYiMc1Yp6v:b-h9hanc)*

**Comment by EricCousineau-TRI** [comment]
Yup, that's it! I have updated this PR per your suggestion to (a) add `-Werror=shadow` to `clang` builds, (b) ensure that Bazel and CMake use the same build flags (at least from `drake/CMakeLists.txt` + `tools/drake.bzl`), and (c) fix any issues that arise in the code due to these changes.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-KqPuvMiBGifUnLQE_xw:b-dyxt5x)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/drake.bzl, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-KqPxUEDrHdoY5IA3iJ5:-KqPxUEDrHdoY5IA3iJ6:b-57ezec) ([raw file](https://github.com/robotlocomotion/drake/blob/48462b8bae0df4c122587ee5a190662a4ce5f9da/tools/drake.bzl#L26)):*
> ```Python
>     "-Werror=extra",
>     "-Werror=return-local-addr",
>     "-Werror=non-virtual-dtor",
> ```

FYI I think this pre-existing warning is good, but I'm not seeing where the CMakeLists sets it.  If you intended to add Bazel's new errors into CMakeLists, perhaps you should add it there?  On the other hand, I don't think it really matters, as long as Bazel's Werrors are a superset of CMake's.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-KqPwiV1TNo7OmtT4JH2:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Once regular pre-merge checks are happy, we should also opt-in to all three mac builds to make sure the flags work there also, before merging.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/drake.bzl, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-KqQ3_Dwxk8oZ3CetPb7:-KqQ3_Dwxk8oZ3CetPb8:ban6xfc) ([raw file](https://github.com/robotlocomotion/drake/blob/bfba97adac11a2f7d6b61360b3e14f2551dfd2d3/tools/drake.bzl#L20)):*
> ```Python
>     "-Werror=return-local-addr",
>     "-Werror=non-virtual-dtor",
>     "-Wno-missing-field-initializers",
> ```

CI is unhappy.  It looks like this was important after all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-KqQ3d4IJBSr4N-jABLZ:bsptm5s)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/drake.bzl, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-KqQ3_Dwxk8oZ3CetPb7:-KqTHJiwrpsE8HhMOITn:bv666l4) ([raw file](https://github.com/robotlocomotion/drake/blob/bfba97adac11a2f7d6b61360b3e14f2551dfd2d3/tools/drake.bzl#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

CI is unhappy.  It looks like this was important after all.
</blockquote></details>

Added it back in. Thanks!

---

*[tools/drake.bzl, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-KqPxUEDrHdoY5IA3iJ5:-KqTGe2DC5er6kIbaCWW:b-7dwmsy) ([raw file](https://github.com/robotlocomotion/drake/blob/48462b8bae0df4c122587ee5a190662a4ce5f9da/tools/drake.bzl#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think this pre-existing warning is good, but I'm not seeing where the CMakeLists sets it.  If you intended to add Bazel's new errors into CMakeLists, perhaps you should add it there?  On the other hand, I don't think it really matters, as long as Bazel's Werrors are a superset of CMake's.
</blockquote></details>

BTW Not sure if I know precisely which flag you are mentioning, but I've gone ahead and ensured the bazel flags and CMake flags are the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[tools/drake.bzl, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-KqTKR2G41VJs6sJECD8:-KqTKR2HhyJgQ6im8n9Q:bazh6sm) ([raw file](https://github.com/robotlocomotion/drake/blob/dca541a224d89271da87b8714e5c0f8131cd6c55/tools/drake.bzl#L27)):*
> ```Python
>     "-Werror=return-local-addr",
>     "-Werror=non-virtual-dtor",
>     "-Wno-unused-parameter",
> ```

Adding `-Wno-unused-parameter` here disables some important error checking.  The CMake code has it enabled globally, but in Bazel we only enable it on tests.  Since CMake can't easily do that, we should leave it alone in CMake but nix this line for Bazel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721)*

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI reping on this.  I think its important to tune up the flags ASAP, and the remaining discussion is a tiny fix.

**Comment by EricCousineau-TRI** [comment]
Sorry, updating now. Thanks!

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake.bzl, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-KqTKR2G41VJs6sJECD8:-Kr1BUg7ZHA2pw9Bgqae:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dca541a224d89271da87b8714e5c0f8131cd6c55/tools/drake.bzl#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Adding `-Wno-unused-parameter` here disables some important error checking.  The CMake code has it enabled globally, but in Bazel we only enable it on tests.  Since CMake can't easily do that, we should leave it alone in CMake but nix this line for Bazel.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-Kr1BVM0EwiJUpZrZBB7:b4jd7z2)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per rotation, please.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-Kr1CU5-kOj7OigUKShk:bll33wd)*

**Comment by sherm1** [comment]
Platform :lgtm:.

---

Reviewed 1 of 4 files at r2, 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6721#-:-Kr2PjqdDUyIKRHFEc08:b-cxwtpi)*

**Pull request merged**
