### PR TITLE
Organized output port accessors of RigidBodyPlant. Added TODO to document bug in unit test.

### PR DESCRIPTION
**Pull request by liangfok**
This is some misc. cleanup in preparation for addressing #4697.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4698)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@sammy-tri for platform review please.

Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4698#-:-K_ni_9cpAQwT3lNjFD_:b-gmg4pt)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 508 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4698#-K_oPTpX0D-CRYeqv9A-:-K_oPTpX0D-CRYeqv9A0:bt6rvqd) ([raw file](https://github.com/robotlocomotion/drake/blob/8c97437919d0b96bb1493d81feb2ee3f44146dab/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L508)):*
> ```cpp
>   const std::map<std::string, int> position_name_to_index_map =
>       tree.computePositionNameToIndexMap();
>   const int joint4_world = position_name_to_index_map.at("joint4");
> ```

BTW, not a defect of this PR, but it'd be nice if this read more like `GetJointByName("joint4").get_index()` and `GetJointByName("joint4").get_index_in_model_instance()` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4698#-:-K_oQ3ceS7LFzbDArc5U:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. This PR is now awaiting platform review.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 508 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4698#-K_oPTpX0D-CRYeqv9A-:-K_oXt1vNlrorvKOb562:bqqo8we) ([raw file](https://github.com/robotlocomotion/drake/blob/8c97437919d0b96bb1493d81feb2ee3f44146dab/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L508)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, not a defect of this PR, but it'd be nice if this read more like `GetJointByName("joint4").get_index()` and `GetJointByName("joint4").get_index_in_model_instance()` 
</blockquote></details>

I agree this would be nice! → #4700

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4698#-:-K_oaqVpRsfYpA-5r28s:befoh09)*

**Comment by sammy-tri** [comment]
I must have picked "joint4" deliberately to dodge #4697, so I really should have said so there.  Thanks for the catch/cleanup!

I'm not actually sure why the new order in the .h file makes more sense than the old, but I'm not opposed to the change.

:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4698#-:-K_p-HbBpQKUhNLI1s2v:brbcvur)*

**Comment by liangfok** [comment]
> I'm not actually sure why the new order in the .h file makes more sense than the old, but I'm not opposed to the change.

Note that the output port descriptor accessor methods are now grouped with a nice heading and description. This appears more organized in the Doxygen-generated website. I was inspired to do this because I'm in the process of adding yet another output port to `RigidBodyPlant` that contains the derivative of the plant's output state vector.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4698#-:-K_p143rGVbpUz0GZs5i:b-sbph26)*

**Pull request merged**
