### PR TITLE
[doc] Add more relnotes and review assignment processes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI +@ggould-tri +@jwnimmer-tri +@rpoyner-tri +@SeanCurtis-TRI +@sherm1 +@soonho-tri +@RussTedrake for review, please.

(If you're busy, feel free to de-assign yourself and treat this like an FYI instead.)

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624#-:-MhQg-Bh-AQwynZbdFZJ:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),ggould-tri(platform),jwnimmer-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @jwnimmer-tri, @rpoyner-tri, @RussTedrake, @SeanCurtis-TRI, and @soonho-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624#-:-MhR4cGJ4bCKK2DRhFLP:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),ggould-tri(platform),jwnimmer-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @ggould-tri, @jwnimmer-tri, @rpoyner-tri, @RussTedrake, @SeanCurtis-TRI, and @soonho-tri)

___
*[doc/_pages/platform_reviewer_checklist.md, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15624#-MhR4MKKCzSa_Pu0gX9b:-MhR4MKL2E82npg1emem:b9lhoqw) ([raw file](https://github.com/robotlocomotion/drake/blob/01bcfa25c7e1728217adefa9e1020e48b3de3099/doc/_pages/platform_reviewer_checklist.md#L29)):*
BTW For better readability, consider using quotation, `> text`.

Example preview:
>

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624#-:-MhSe90_4CCd6Li8LizV:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),ggould-tri(platform),jwnimmer-tri(platform),SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @ggould-tri, @rpoyner-tri, @RussTedrake, and @SeanCurtis-TRI)

___
*[doc/_pages/platform_reviewer_checklist.md, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15624#-MhSdQOK-ir8LJ-3nsll:-MhSdQOK-ir8LJ-3nslm:b-1mujtu) ([raw file](https://github.com/robotlocomotion/drake/blob/01bcfa25c7e1728217adefa9e1020e48b3de3099/doc/_pages/platform_reviewer_checklist.md#L16)):*
> ```Markdown
> associated with the issue's ``team`` label.
> 
> Search for [pull requests that need review](https://github.com/RobotLocomotion/drake/pulls?q=is%3Aopen+is%3Apr+no%3Aassignee+-label%3A%22status%3A+do+not+review%22)
> ```

BTW, probably related to this discussion: from time to time, we have 'draft' PRs which are not ready for review by definition. I think it's better to update this filter to exclude them. What do you think?

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624#-:-MhTLFFe3CyVWWftTn5s:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @rpoyner-tri, @RussTedrake, and @SeanCurtis-TRI)

___
*[doc/_pages/platform_reviewer_checklist.md, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15624#-MhSdQOK-ir8LJ-3nsll:-MhTKD9DCU8a_x8HKkaV:bz2iluc) ([raw file](https://github.com/robotlocomotion/drake/blob/01bcfa25c7e1728217adefa9e1020e48b3de3099/doc/_pages/platform_reviewer_checklist.md#L16)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, probably related to this discussion: from time to time, we have 'draft' PRs which are not ready for review by definition. I think it's better to update this filter to exclude them. What do you think?
</blockquote></details>

This has already been proposed
here: https://github.com/RobotLocomotion/drake/pull/14368
and here: https://github.com/RobotLocomotion/drake/pull/15602
and is what led to this PR, I believe.

(I tend to agree with you, and indeed have several times made the mistake of flagging PRs "draft" instead of DNR'ing them.  But a PR comment thread is probably not the place to hunt consensus on this)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624#-:-MhTZksM5xcAyjzy6osO:bmxilld)* status: LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),RussTedrake(platform) (waiting on @rpoyner-tri and @RussTedrake)

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624)* status: LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),RussTedrake(platform) (waiting on @rpoyner-tri and @RussTedrake)

___
*[doc/_pages/platform_reviewer_checklist.md, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15624#-MhSdQOK-ir8LJ-3nsll:-MhTltmG4FPE45dC-HkU:b-ts6gx7) ([raw file](https://github.com/robotlocomotion/drake/blob/01bcfa25c7e1728217adefa9e1020e48b3de3099/doc/_pages/platform_reviewer_checklist.md#L16)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This has already been proposed
here: https://github.com/RobotLocomotion/drake/pull/14368
and here: https://github.com/RobotLocomotion/drake/pull/15602
and is what led to this PR, I believe.

(I tend to agree with you, and indeed have several times made the mistake of flagging PRs "draft" instead of DNR'ing them.  But a PR comment thread is probably not the place to hunt consensus on this)
</blockquote></details>

Thank you, @ggould-tri . I've added my comments at the slack thread.

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),RussTedrake(platform) (waiting on @jwnimmer-tri, @rpoyner-tri, and @RussTedrake)

___
*[doc/_pages/platform_reviewer_checklist.md, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15624#-MhTtxfSCaAtRs6PMeVn:-MhTtxfSCaAtRs6PMeVo:bewb08e) ([raw file](https://github.com/robotlocomotion/drake/blob/01bcfa25c7e1728217adefa9e1020e48b3de3099/doc/_pages/platform_reviewer_checklist.md#L16)):*
As a follow-up from the slack discussion, https://drakedevelopers.slack.com/archives/C2NN588UA/p1629384531048800?thread_ts=1628719140.033200&cid=C2NN588UA: we want to update this sentence.

@jwnimmer-tri 's wrote in Slack:

> We're assigning a helper from the Drake team to do whatever is necessary (if anything) to help the new contributor finish their contribution.  Perhaps the user needs help understanding how to add tests, for example.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @rpoyner-tri, @RussTedrake, @SeanCurtis-TRI, and @soonho-tri)

___
*[doc/_pages/platform_reviewer_checklist.md, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15624#-MhTtxfSCaAtRs6PMeVn:-MhU44AR6fAqJpOklcNW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/01bcfa25c7e1728217adefa9e1020e48b3de3099/doc/_pages/platform_reviewer_checklist.md#L16)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

As a follow-up from the slack discussion, https://drakedevelopers.slack.com/archives/C2NN588UA/p1629384531048800?thread_ts=1628719140.033200&cid=C2NN588UA: we want to update this sentence.

@jwnimmer-tri 's wrote in Slack:

> We're assigning a helper from the Drake team to do whatever is necessary (if anything) to help the new contributor finish their contribution.  Perhaps the user needs help understanding how to add tests, for example.

</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624#-:-MhU4kyn94BJfwC6K1F6:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @RussTedrake and @soonho-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake and @soonho-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform) (waiting on @jwnimmer-tri and @RussTedrake)

___
*[doc/_pages/platform_reviewer_checklist.md, line 38 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15624#-MhURzca-D7P2rAiMvrS:-MhURzca-D7P2rAiMvrT:bmjz7qi) ([raw file](https://github.com/robotlocomotion/drake/blob/9f83c8c2ebfe761c23f6257cd972a774139cdcc8/doc/_pages/platform_reviewer_checklist.md#L38)):*
> ```Markdown
>   > Good day, ``@AUTHOR``.  I'm assigning ``+@ASSIGNEE`` as the most relevant
>   > team member to assist with this pull request.  If you already had a
>   > different team member in mind, please let us know.  To the ``@ASSIGNEE``,
> ```

minor:  If `@ASSIGNEE` is meant to be expanded, the "the" here will read badly ("to the ``jwnimmer``, feel free...").

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @ggould-tri, @rpoyner-tri, @RussTedrake, and @SeanCurtis-TRI)

___
*[doc/_pages/platform_reviewer_checklist.md, line 38 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15624#-MhURzca-D7P2rAiMvrS:-MhUqCcv7g683Fj2fNbb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9f83c8c2ebfe761c23f6257cd972a774139cdcc8/doc/_pages/platform_reviewer_checklist.md#L38)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  If `@ASSIGNEE` is meant to be expanded, the "the" here will read badly ("to the ``jwnimmer``, feel free..."). 
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
-@RussTedrake you can ping me later on, if you find any problems with the new text.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15624)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
