### PR TITLE
Add short circuiting if-else support for Symbolic

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We thought that we could not implement short circuiting if-then-else with symbolic::Expression, but actually we can!  The caveat is that we need to ask the user to explicitly tell us which symbolic variables are mutated within the basic blocks, so that we can create phi nodes for them to restore the SSA form that Expression requires, after the if-elif-else chain concludes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11243)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Early results show that, at least for RotationMatrix::ToQuaternion, the `symbolic::cond_literals` if-else support compiles to the same object code as the double-native flavor.

**Comment by jwnimmer-tri** [comment]
I'm unsure whether this the ["ruby supports bare words"](https://www.destroyallsoftware.com/talks/wat) version of :drum: (awesome) or :duck: (wat).  Curious to hear others' reactions @soonho-tri @sherm1 @RussTedrake @EricCousineau-TRI.

**Comment by EricCousineau-TRI** [comment]
Per f2f, I'm more on the :duck: side at the moment... However, the structure of the usage looks good!
I suggested macros, not necessarily for the entire scope but just to capture some of the more, eh, symbol-heavy tokens; e.g. going from:
```c++
T a{0.0};
""_mutating_only(&a) =
""_if (a >= 0) ^[&]() {
  a -= 1.0;
  std::cout << "Side effect!\n";
} || ""_else ^[&]() {
  // This will be skipped, because `a` was >= 0.
  DRAKE_DEMAND(false);
};
```
to:
```c++
T a{0.0};
DRAKE_IF_MUTATES(&a)
DRAKE_IF (a >= 0) {
  a -= 1.0;
  std::cout << "Side effect!\n";
} DRAKE_ELSE {
  // This will be skipped, because `a` was >= 0.
  DRAKE_DEMAND(false);
}
```

Some add'l concerns:
The enforced usage of `std::function<void()>` implies required type erasure, which may introduce non-trivial overhead. We might want to keep some parts of this more template heavy, to permit `T = double, AutoDiff<>` to optimize to minimal expressions? (unless compilers can fully recognize constrained usages of `std::function<>`...)
Is there a standalone version of this that can be run through Godbolt's compiler for `T = double` to see what overhead it introduces?

**Comment by jwnimmer-tri** [comment]
>The enforced usage of std::function<void()> implies required type erasure, ...

There is a TODO to remove all std::function.  Currently the `double` case already doesn't use it.

> Is there a standalone version of this that can be run through Godbolt's compiler for T = double to see what overhead it introduces?

https://godbolt.org/z/NGBmA9 -- no overhead (for double) that I can tell.

**Comment by jwnimmer-tri** [comment]
As both Eric and Soonho point out, there are a few different ways we could craft the new, keyword-like names for `if`, `elif, `else` branches.  Currently they are UDLs; we could also do functions or classes or macros.  I think I'd like to decide if we want this feature in the first place, assuming that useful tokens can be found.  If yes (or maybe-yes-depending-on-tokens), then we can work through to the token-naming questions.

**Comment by EricCousineau-TRI** [comment]
> Currently the double case already doesn't use it, only Expression does.

In terms of a roadmap, will this code be optimized to permit quick evaluation for `T=double`, so that it can be used in generic code?

> I think the token after -> needs to be a method name and method parens [...]

There's always the existing abuse of bitshift operators `>>` :D

> That is an interesting proposal! I think it would go more like [...]

Nice! Just to add yet another proposal, for fluent-style stuff:

```c++
// All nested:
sym_if(foo > bar).can_affect({&w, &x, &y, &z}).then([&]() {
  ... then-block ...
}).sym_else_if(bar != 10).then([&]() {
  ... elseif then-block
}).sym_else([&]() {
  ... else-block ...
});

// Still with some operators
sym_if(foo > bar).which_affects({&w, &x, &y, &z}) && [&]() {
  ... then-block ...
} || [&]() {
  ... else-block ...
};

```

**Comment by jwnimmer-tri** [comment]
> In terms of a roadmap, will this code be optimized to permit quick evaluation for T=double, so that it can be used in generic code?

Yup, that's a fundamental goal.  (And, I think it already is.)

**Comment by jwnimmer-tri** [comment]
I think my next step here when I pick it up again will be to find more use cases throughout the code so that we have more data points to evaluate syntax options.

**Pull request closed without merging**
