### PR TITLE
added S into lqr's return, added lqr(a, b, q, r, n)

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
@RussTedrake for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4360)

### CODE REVIEW

**Comment by RussTedrake** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/linear_quadratic_regulator.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYArBizXMQLClK9VEi_:-KYArBizXMQLClK9VEia:bxgaasp) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.cc#L38)):*
> ```cpp
> 
>   Eigen::MatrixXd Q1 = Q - N * R_cholesky.solve(N.transpose());
>   Eigen::MatrixXd A1 = A - B * R_cholesky.solve(N.transpose());
> ```

BTW, did actually check these, but they look right at a glance.

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYAozlL6u-LNFMOfbqd:-KYAozlL6u-LNFMOfbqe:bcxtmw3) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.h#L8)):*
> ```objc
> namespace systems {
> 
> struct LinearQuadraticRegulartorResult {
> ```

Typo here (and everywhere that uses it. :)

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYAqIytB9EzkVVbmN8_:-KYAqIytB9EzkVVbmN8a:bze43qs) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.h#L77)):*
> ```objc
>     const LinearSystem<double>& system,
>     const Eigen::Ref<const Eigen::MatrixXd>& Q,
>     const Eigen::Ref<const Eigen::MatrixXd>& R);
> ```

will you please add N as an option here (and the nonlinear version below)?  presumably you kept the original matrix-only version without N because it was difficult to given a default value for N?  

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYApbhbBO1LtkhBqLZd:-KYApbhbBO1LtkhBqLZe:bmovflu) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.h#L116)):*
> ```objc
> /// http://www.engr.iupui.edu/~skoskie/ECE684/Riccati_algorithms.pdf
> ///
> Eigen::MatrixXd ContinuousAlgebraicRiccatiEquation(
> ```

BTW, Did you want to take this chance to move this out of lqr and into math or common?  

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYApRYsSVly_EcZOB6L:-KYApRYsSVly_EcZOB6M:b-90cxeo) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.h#L129)):*
> ```objc
>     const Eigen::Ref<const Eigen::MatrixXd>& B,
>     const Eigen::Ref<const Eigen::MatrixXd>& Q,
>     const Eigen::LLT<Eigen::MatrixXd>& R_cholesky);
> ```

BTW, nice.  I like that you added a method (instead of simply changing/removing the interface which i think is more standard)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/linear_quadratic_regulator.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYArBizXMQLClK9VEi_:-KYArO-SyiLVfPmv-V_r:b-tyvpb6) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.cc#L38)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

BTW, did actually check these, but they look right at a glance.
</blockquote></details>

BTW, that was "didn't actually check these"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/controllers/linear_quadratic_regulator.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYArBizXMQLClK9VEi_:-KYBN6BxSCmdBEMiJ-pJ:b-nggqnh) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.cc#L38)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

BTW, that was "didn't actually check these"
</blockquote></details>

https://en.wikipedia.org/wiki/Linear%E2%80%93quadratic_regulator
also agrees with this, should be correct. 

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYAozlL6u-LNFMOfbqd:-KYBNs9bNt8j1smM9iF1:bhkdskd) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.h#L8)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Typo here (and everywhere that uses it. :)
</blockquote></details>

fail.. 

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYAqIytB9EzkVVbmN8_:-KYBNt2FFTib_Ha5r7O3:b-irw0rw) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.h#L77)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

will you please add N as an option here (and the nonlinear version below)?  presumably you kept the original matrix-only version without N because it was difficult to given a default value for N?  
</blockquote></details>

i tried for a bit, but i couldn't figure out how to do it correctly for the general case. i tried ref* default to nullptr. any suggestions? 

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYApbhbBO1LtkhBqLZd:-KYBOO5CBf49qKTdt28n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.h#L116)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

BTW, Did you want to take this chance to move this out of lqr and into math or common?  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360)*

**Comment by RussTedrake** [comment]
Reviewed 6 of 8 files at r2, 1 of 1 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYApbhbBO1LtkhBqLZd:-KYGDIhsBYdwUOW5jOW1:b-bklh8c) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.h#L116)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you update the estimator cmake to link to drakeMath instead of linearcontrol?  Will also need to update the headers when you merge master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360)*

**Comment by siyuanfeng-tri** [comment]
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYApbhbBO1LtkhBqLZd:-KYHAARDC3EEFoppWU3j:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d7865527cd51651f9a6d98ccabf17317843bd65/drake/systems/controllers/linear_quadratic_regulator.h#L116)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Could you update the estimator cmake to link to drakeMath instead of linearcontrol?  Will also need to update the headers when you merge master.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 8 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360)*

**Comment by siyuanfeng-tri** [comment]
@david-german-tri for platform review. thanks!

---

Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-:-KYKQAEkDVsNCFsqSWQL:b-1b4dy8)*

**Comment by david-german-tri** [comment]
+@david-german-tri

**Comment by RussTedrake** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYKd1fG0X8mS8obUTTa:-KYKd1fGB2L2Y-w1k7nW:ba57vkb) ([raw file](https://github.com/robotlocomotion/drake/blob/02d509e86df0d5cdee30bd99b1244baff210b811/drake/systems/controllers/linear_quadratic_regulator.h#L77)):*
> ```objc
>     const LinearSystem<double>& system,
>     const Eigen::Ref<const Eigen::MatrixXd>& Q,
>     const Eigen::Ref<const Eigen::MatrixXd>& R);
> ```

now that you have the N as an optional argument, can you also allow it as an optional argument here and below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360)*

**Comment by david-german-tri** [comment]
Looks good other than the lack of tests, and the cpplint problems.  (If you want to push back on the tests because they were already missing, you have a point, but this seems like an opportune time to add them.)

---

Reviewed 5 of 8 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/math/continuous_algebraic_ricatti_equation.h, line 1 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYKsc-E6TJYY3bXLbZ8:-KYKsc-F8TbNVAyvbmDi:bfyo37l) ([raw file](https://github.com/robotlocomotion/drake/blob/0acb822032132af5e5aa6c48a0cd0980d5556380/drake/math/continuous_algebraic_ricatti_equation.h#L1)):*
> ```objc
> #pragma once
> ```

Please add unit tests for this new code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-:-KYKtmC8Bnnm0Yrj7m__:b-x2zuiv)*

**Comment by siyuanfeng-tri** [comment]
i added some tests for the system version of lqr(a,b,q,r,n), which involves refactoring Russ' original code a bit. 
i am not going to add unit tests for care.h for now. all of the lqr family of stuff depends on that, it would be very obvious if something went wrong. but i agree it should have unit test coverage. 

---

Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/math/continuous_algebraic_ricatti_equation.h, line 1 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYKsc-E6TJYY3bXLbZ8:-KYLT_i595LLz2tlrG3Y:b-c8rsev) ([raw file](https://github.com/robotlocomotion/drake/blob/3d38ba89ae268dd0fda94a57a0d309634404f0ce/drake/math/continuous_algebraic_ricatti_equation.h#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Please add unit tests for this new code.
</blockquote></details>

i am gonna push back on that for now :(
i am relying on the lqr code to test this..

---

*[drake/systems/controllers/linear_quadratic_regulator.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-KYKd1fG0X8mS8obUTTa:-KYLTjhZ61rfHtY5iaku:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/02d509e86df0d5cdee30bd99b1244baff210b811/drake/systems/controllers/linear_quadratic_regulator.h#L77)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

now that you have the N as an optional argument, can you also allow it as an optional argument here and below?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-:-KYLTmg94NfktMXi_hIu:b-av1l3o)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-:-KYLVycD6nZbxJmpQl5e:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4360#-:-KYOndiO1A-H8W5rdlqr:bnfp4nl)*

**Pull request merged**
