### PR TITLE
Update octomap dependency to 1.8.1 and remove octomap installation

### PR DESCRIPTION
**Pull request by j-rivero**
The PR updates octomap in Drake from 1.7.2 to 1.8.1 ([changelog](https://github.com/OctoMap/octomap/blob/v1.8.1/octomap/CHANGELOG.txt) and [changes](https://github.com/OctoMap/octomap/compare/v1.7.2...v1.8.1)). 1.8.1 is the version present in ROS Kinetic (`ros-kinetic-octomap`).

Octomap is only used in FCL and I was unable to find evidence that Drake is currently using FCL code that uses octomap.

I've [tested this PR in the osrf buildfarm](https://build.osrfoundation.org/view/All/job/drake-ci-pr_any-xenial-amd64/72/consoleFull), compiles, test passes and drake-shambala seems fine.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7492)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/workspace/octomap/octomap.BUILD.bazel, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7492#-Kz53kaJvhKxnthbL-E4:-Kz53kaJvhKxnthbL-E5:b-dzowxj) ([raw file](https://github.com/robotlocomotion/drake/blob/a4b95935b2e4eced4340279185231dda21fccd84/tools/workspace/octomap/octomap.BUILD.bazel#L52)):*
> ```
> )
> 
> install(
> ```

Commit says remove support for installing the library, but still installs it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7492)*

**Comment by jamiesnape** [comment]
I am assuming this is going to be merging after #7417? I would honestly not mind if this were part of #7417.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot 
linux-xenial-gcc-cmake-experimental-matlab please

**Comment by j-rivero** [comment]
> I am assuming this is going to be merging after #7417? I would honestly not mind if this were part of #7417.

Merged there. Closing.

**Pull request closed without merging**
