### PR TITLE
[multibody] Parse mujoco geometry (but not meshes)

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards #16369

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri feature.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378#-:-MtOYQm13Ji8_i5jbzlK:b5v0m1t)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtOaXto8-lF4AVMb_wI:-MtOaXto8-lF4AVMb_wJ:b-ausy95) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/test/detail_mujoco_parser_test.cc#L82)):*
> ```cpp
> )""";
> 
>   AddModelFromMujocoXml({.file_contents = &xml}, "test", std::nullopt, &plant);
> ```

Call sites like this are cool, sadly, still science fiction until we drop bionic/gcc. Instead we probably have to spell it `Function({.file_name = nullptr, .file_contents = &xml}, ...)` for now. I haven't tested that spelling, but I know the older compiler has to see explicit fields in order (later unneeded ones can be omitted).

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtOaXto8-lF4AVMb_wI:-MtOx_P15cDHPqPO4l3R:b-qxgfkt) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/test/detail_mujoco_parser_test.cc#L82)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Call sites like this are cool, sadly, still science fiction until we drop bionic/gcc. Instead we probably have to spell it `Function({.file_name = nullptr, .file_contents = &xml}, ...)` for now. I haven't tested that spelling, but I know the older compiler has to see explicit fields in order (later unneeded ones can be omitted).
</blockquote></details>

I checked, and the recommended spelling above does work.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: with some comment and message cleanup requests.

I suspect some later drake-adoption pass will try to make these parsers total (every element/attribute leads to a semantic output, or warning, or error), and probably add a bunch of negative tests. Given the current state of play, I think we can delay that additional test work.

+@sherm1 for platform review -- Monday schedule.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378#-:-MtP0cO37Q60UMKCyaFh:b-s958ea)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 161 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP-1RQCDiL54T17yV7:-MtP-1RQCDiL54T17yV8:b-4nt4gs) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_mujoco_parser.cc#L161)):*
> ```cpp
> 
>     if (type == "plane") {
>       // We interpret the MuJoCo infinite place as a half-space.
> ```

`place` looks suspicious; meant `plane` instead?



_Code quote:_
```cpp
 place
```
___
*[multibody/parsing/detail_mujoco_parser.cc, line 266 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP-NhU97q9F7Do90PO:-MtP-NhU97q9F7Do90PP:b4phiom) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_mujoco_parser.cc#L266)):*
> ```cpp
>         drake::log()->warn(
>             "The torsional and rolling friction specified in the friction "
>             "attribution of {} are unsupported and will be ignored.",
> ```

`attribution` looks suspicious; meant `attribute` or `attributes` instead?



_Code quote:_
```cpp
attribution
```
___
*[multibody/parsing/detail_mujoco_parser.cc, line 354 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP1sBT81lagcaeKIs4:-MtP1sBT81lagcaeKIs5:b-4u0apz) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_mujoco_parser.cc#L354)):*
> ```cpp
>       } else {
>         drake::log()->warn(
>             "Unknown value {} for the angle attribute will be ignored.", angle);
> ```

When this warning is issued, will all angles be ignored? will only some unit interpretation be ignored? are there default units that will be in force? Might help in debugging problems.

I didn't dig through and try to create a negative test case, or work out the semantics. Consider maybe:
"Unknown value raydians for the angle attribute will be ignored; angle values will be interpreted as degrees instead."
___
*[multibody/parsing/detail_tinyxml.h, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP1OBe2cnCSwJ-Madi:-MtP1OBe2cnCSwJ-Madj:b9foc63) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_tinyxml.h#L15)):*
> ```objc
> namespace internal {
> 
> std::vector<double> ConvertToDoubles(const std::string& str);
> ```

This should have at least a non-doxygen comment explaining what the function does.
___
*[multibody/parsing/detail_tinyxml.h, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtOy51d2km7OFxeVT4U:-MtOy51d2km7OFxeVT4V:b-ghm8gw) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_tinyxml.h#L39)):*
> ```objc
> //
> // @throws std::exception if the attribute doesn't contain
> // three numeric values.
> ```

i suspect the word `three` in the comment is stale.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP-xSs5QnD9jzpMPTI:-MtP-xSs5QnD9jzpMPTJ:b12yyl7) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/test/detail_mujoco_parser_test.cc#L27)):*
> ```cpp
> 
> GTEST_TEST(MujocoParser, GymModels) {
>   // Confirm that I can successfully parse the MuJoCo models in the
> ```

BTW I'm not a big fan of "I" in comments; subsequent maintenance will likely make the original author's identity obscure. Royal "we" is a bit better, but impersonal comments are probably best: "Confirm successful parse of models..."



_Code quote:_
```cpp
I 
```

**Review by RussTedrake — COMMENTED** [review]
Agreed.  Fwiw, I think this parser is actually closer to meeting that specification that our mainstream ones.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378#-:-MtP5Z_p1vZAQj5hTpoz:b1mc00c)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 161 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP-1RQCDiL54T17yV7:-MtP5lmR0gpEsyZgA7fD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_mujoco_parser.cc#L161)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

`place` looks suspicious; meant `plane` instead?
</blockquote></details>

Done.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 266 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP-NhU97q9F7Do90PO:-MtP5qtg21tVlcoWVdvy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_mujoco_parser.cc#L266)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

`attribution` looks suspicious; meant `attribute` or `attributes` instead?
</blockquote></details>

Done.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 354 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP1sBT81lagcaeKIs4:-MtP6M7QAUKOoVhDM3Bp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_mujoco_parser.cc#L354)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

When this warning is issued, will all angles be ignored? will only some unit interpretation be ignored? are there default units that will be in force? Might help in debugging problems.

I didn't dig through and try to create a negative test case, or work out the semantics. Consider maybe:
"Unknown value raydians for the angle attribute will be ignored; angle values will be interpreted as degrees instead."
</blockquote></details>

Done.
___
*[multibody/parsing/detail_tinyxml.h, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP1OBe2cnCSwJ-Madi:-MtP6rsw1DcZtgoTgWjW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_tinyxml.h#L15)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This should have at least a non-doxygen comment explaining what the function does.
</blockquote></details>

Done.
___
*[multibody/parsing/detail_tinyxml.h, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtOy51d2km7OFxeVT4U:-MtP7Ck9CHgTC7cptVDs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/detail_tinyxml.h#L39)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

i suspect the word `three` in the comment is stale.
</blockquote></details>

Done.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtP-xSs5QnD9jzpMPTI:-MtP7LWw3iEpm00Gx-4M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/test/detail_mujoco_parser_test.cc#L27)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW I'm not a big fan of "I" in comments; subsequent maintenance will likely make the original author's identity obscure. Royal "we" is a bit better, but impersonal comments are probably best: "Confirm successful parse of models..."
</blockquote></details>

Done.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtOaXto8-lF4AVMb_wI:-MtP7e79D82bIpf5yB3y:b-l5r1cy) ([raw file](https://github.com/robotlocomotion/drake/blob/45d6a1c64542f4a8d901f9d9c16d3c25a239df96/multibody/parsing/test/detail_mujoco_parser_test.cc#L82)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I checked, and the recommended spelling above does work.
</blockquote></details>

Done.  Thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few minor issues.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378#-:-MtVVBTOBQWsQQBY_IuK:b-8fu77w)* status: 8 unresolved discussions (waiting on @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVN6sdAONeulBnzbeV:-MtVMzge4yknVxuXAIa1:bvoc6pl) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L63)):*
> ```cpp
>   RigidTransformd ParseTransform(XMLElement* node) {
>     Vector3d pos{0, 0, 0};
>     ParseVectorAttribute(node, "pos", &pos);
> ```

BTW consider a comment noting that pos is given a default value in case there is not "pos" attribute. Wasn't obvious to me at first why you didn't have to check the return value here. (And seem my comment on ParseVectorAttribute()).
___
*[multibody/parsing/detail_mujoco_parser.cc, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVNawA-V40p0Ynjck-:-MtVNawA-V40p0Ynjck0:b-bxhrp4) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L68)):*
> ```cpp
>     if (ParseVectorAttribute(node, "quat", &quat)) {
>       return RigidTransformd(
>           Eigen::Quaternion<double>(quat[0], quat[1], quat[2], quat[3]), pos);
> ```

BTW because of the ugliness associated with wxyz or xyzw storage, consider documenting that you have determined that MuJoCo uses wxyz order (where w is the scalar part) assuming that's right.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 124 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVTU-V4Gopy8pfWYR1:-MtVTU-V4Gopy8pfWYR2:b-vf5emv) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L124)):*
> ```cpp
>     if (!ParseStringAttribute(node, "name", &geom.name)) {
>       // Use "geom#" as the default body name.
>       geom.name = fmt::format("geom{}", num_geom);
> ```

minor: kcov says this isn't unit tested
___
*[multibody/parsing/detail_mujoco_parser.cc, line 168 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVTyXu007OinIQU0oM:-MtVTyXu007OinIQU0oN:b-ffh9f5) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L168)):*
> ```cpp
>         throw std::logic_error(
>             "The size attribute for sphere geom must have at least one "
>             "element.");
> ```

minor: kcov says none of the error conditions and warnings are unit tested. Ideally they should be but I can see why you might want to do that work now. I'd accept a TODO noting that unit tests for error conditions ought to be added to make sure they keep working in the far future.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 245 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVUZ_y7wPKfo_vL9Ge:-MtVUZ_y7wPKfo_vL9Gf:b-shu02e) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L245)):*
> ```cpp
>       return geom;
>     } else {
>       throw std::runtime_error(fmt::format("Unrecognized geom type {}", type));
> ```

BTW consider adding a unit test for at least the unrecognized geometry case to make sure that stays functional.
___
*[multibody/parsing/detail_tinyxml.h, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVMkUg9n3NkywbJDXN:-MtVMkUg9n3NkywbJDXO:b91vx76) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_tinyxml.h#L38)):*
> ```objc
> // values into @p val.
> //
> // @returns false if the attribute is not present
> ```

minor: should document that in the case the attribute is missing, the output argument is left untouched (you depend on that in the parser).
___
*[multibody/parsing/detail_tinyxml.h, line 43 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVFOkrCS9Rq0mvE_1y:-MtVFOkrCS9Rq0mvE_1z:bmnneqw) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_tinyxml.h#L43)):*
> ```objc
> // @throws std::exception if the attribute doesn't contain `_Rows` numeric
> // values.
> template <int _Rows>
> ```

nit: name beginning with "_" not permitted by Drake [style guide](https://drake.mit.edu/styleguide/cppguide.html#Variable_Names) in C++. Maybe that's a Python thing? This should be just `rows`.

BTW names beginning with "_" followed by a capital letter are prohibited by the C++ standard. From the 2003 C++ standard:
```
17.4.3.1.2 Global names [lib.global.names]
Certain sets of names and function signatures are always
reserved to the implementation:

Each name that contains a double underscore (__) or begins with an
underscore followed by an uppercase letter (2.11) is reserved to the
implementation for any use.

Each name that begins with an underscore is reserved to the
implementation for use as a name in the global namespace.
```
___
*[multibody/parsing/detail_tinyxml.h, line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVV5Iw91-zqRmrTlc9:-MtVV5Iw91-zqRmrTlcA:b-4m4sx0) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_tinyxml.h#L53)):*
> ```objc
>       throw std::invalid_argument(
>           fmt::format("Expected {} values for attribute {} got {}", _Rows,
>                       attribute_name, attr));
> ```

minor: this is untested per kcov; there should be a unit test for it.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378)* status: 8 unresolved discussions (waiting on @RussTedrake and @sherm1)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 124 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVTU-V4Gopy8pfWYR1:-Mta-kXO2D3X-BF0Wf2U:bieehts) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L124)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: kcov says this isn't unit tested
</blockquote></details>

how are you running kcov?  I ran it and thought I'd gotten a clean report (which I was very suspicious of!)

**Comment by RussTedrake** [comment]
___
*[multibody/parsing/detail_mujoco_parser.cc, line 124 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVTU-V4Gopy8pfWYR1:-Mta2BbKCZx2XX4F21xs:bea3u5t) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L124)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

how are you running kcov?  I ran it and thought I'd gotten a clean report (which I was very suspicious of!)
</blockquote></details>

I suspect there is an output file that I didn't find!

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVNawA-V40p0Ynjck-:-Mta46lk9CkUpoIWfmfR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L68)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW because of the ugliness associated with wxyz or xyzw storage, consider documenting that you have determined that MuJoCo uses wxyz order (where w is the scalar part) assuming that's right.
</blockquote></details>

Done.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 124 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVTU-V4Gopy8pfWYR1:-Mta4LXy0OP69kTi9n_l:b-nz37jh) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L124)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I suspect there is an output file that I didn't find!
</blockquote></details>

Done.  Added a TODO in detail_mujoco_parser_test
___
*[multibody/parsing/detail_mujoco_parser.cc, line 168 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVTyXu007OinIQU0oM:-Mta4Pia1vvkui3TvTct:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L168)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: kcov says none of the error conditions and warnings are unit tested. Ideally they should be but I can see why you might want to do that work now. I'd accept a TODO noting that unit tests for error conditions ought to be added to make sure they keep working in the far future.
</blockquote></details>

Done.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 245 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVUZ_y7wPKfo_vL9Ge:-Mta5AoJ2u6ULCUY3Fve:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L245)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider adding a unit test for at least the unrecognized geometry case to make sure that stays functional.
</blockquote></details>

Done.
___
*[multibody/parsing/detail_tinyxml.h, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVMkUg9n3NkywbJDXN:-Mta5XP1A2X8LcWm7fJt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_tinyxml.h#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should document that in the case the attribute is missing, the output argument is left untouched (you depend on that in the parser).
</blockquote></details>

Done.
___
*[multibody/parsing/detail_tinyxml.h, line 43 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVFOkrCS9Rq0mvE_1y:-Mta5hWG41HFeZ7IBScZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_tinyxml.h#L43)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: name beginning with "_" not permitted by Drake [style guide](https://drake.mit.edu/styleguide/cppguide.html#Variable_Names) in C++. Maybe that's a Python thing? This should be just `rows`.

BTW names beginning with "_" followed by a capital letter are prohibited by the C++ standard. From the 2003 C++ standard:
```
17.4.3.1.2 Global names [lib.global.names]
Certain sets of names and function signatures are always
reserved to the implementation:

Each name that contains a double underscore (__) or begins with an
underscore followed by an uppercase letter (2.11) is reserved to the
implementation for any use.

Each name that begins with an underscore is reserved to the
implementation for use as a name in the global namespace.
```
</blockquote></details>

Done.
___
*[multibody/parsing/detail_tinyxml.h, line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVV5Iw91-zqRmrTlc9:-Mta6P0m04LjFukTjIqm:bpli7r5) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_tinyxml.h#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this is untested per kcov; there should be a unit test for it.
</blockquote></details>

Are you sure?  There appear to be lots of examples of this in detail_tiny_xml_test.cc?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16378)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 124 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVTU-V4Gopy8pfWYR1:-Mtd3KGj6_0aCP4nkttl:b-ackaeg) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_mujoco_parser.cc#L124)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  Added a TODO in detail_mujoco_parser_test
</blockquote></details>

I did this:
```
tools/dynamic_analysis/kcov_tool clean
bazel test --config=kcov multibody/parsing/detail_mujoco_parser_test
tools/dynamic_analysis/kcov_tool merge /tmp/mykcov
```
then looked at /tmp/mykcov/index.html in Chrome.
___
*[multibody/parsing/detail_tinyxml.h, line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16378#-MtVV5Iw91-zqRmrTlc9:-Mtd3tGA698qe4f4ODUA:b-uq9mw4) ([raw file](https://github.com/robotlocomotion/drake/blob/83347b2b26218f230fb6bad93ff42e075b0b91ba/multibody/parsing/detail_tinyxml.h#L53)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Are you sure?  There appear to be lots of examples of this in detail_tiny_xml_test.cc?
</blockquote></details>

Nope -- my bad, sorry! I had only run the mujoco parser test. Retracted.

**Pull request merged**
