### PR TITLE
[geometry] Select output format from mesh_half_space_intersection in hydroelastics.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Support the [development plan for 14579](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123). This PR for mesh_half_space_intersection is similar to PR #15310 for mesh_plane_intersection.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@joemasterjohn for feature review please.  Please let me know if you're too busy.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358#-:-Meg6__c7rdjlDBH46iZ:b-xlakqn)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

___
*[geometry/proximity/mesh_half_space_intersection.cc, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MeRwxi-7e5RUkToZ7n8:-MeRwxi-7e5RUkToZ7n9:bihx2sa) ([raw file](https://github.com/robotlocomotion/drake/blob/5f27da52d2fa0599cb0f573ca546e5b4bbd55bb0/geometry/proximity/mesh_half_space_intersection.cc#L34)):*
> ```cpp
>  */
> template <typename T>
> Vector3<T> CalcEdgePlaneIntersection(
> ```

I refactored this function out of the next function `GetVertexAddIfNeeded()`, so it can be called directly from `ConstructTriangleHalfspaceIntersectionPolygon()` in `case ContactPolygonRepresentation::kSingleTriangle`.

**Review by joemasterjohn — COMMENTED** [review]
Checkpoint.

> Reviewed 1 of 4 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358#-:-Mfcqh4H14FUQ1vSlkzf:by96gdd)* status: 4 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @joemasterjohn)

___
*[geometry/proximity/mesh_half_space_intersection.cc, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MeRwxi-7e5RUkToZ7n8:-MfcYat4EV4pGrltXU5A:b-4a4p6r) ([raw file](https://github.com/robotlocomotion/drake/blob/5f27da52d2fa0599cb0f573ca546e5b4bbd55bb0/geometry/proximity/mesh_half_space_intersection.cc#L34)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I refactored this function out of the next function `GetVertexAddIfNeeded()`, so it can be called directly from `ConstructTriangleHalfspaceIntersectionPolygon()` in `case ContactPolygonRepresentation::kSingleTriangle`.
</blockquote></details>

OK, looks good. Is this method only useful in the triangle mesh/halfspace intersection algorithm? Or could it be consolidated further?
___
*[geometry/proximity/mesh_half_space_intersection.cc, line 38 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfcYJ9p66HfTnw87tXV:-MfcYJ9p66HfTnw87tXW:b7oxidb) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/mesh_half_space_intersection.cc#L38)):*
> ```cpp
>     const std::vector<SurfaceVertex<double>>& vertices_F,
>     const math::RigidTransform<T>& X_WF) {
>   DRAKE_DEMAND(sgn(s_a) != sgn(s_b));
> ```

nit: You can also add `DRAKE_DEMAND(a != b)` as a sanity check.
___
*[geometry/proximity/mesh_half_space_intersection.cc, line 238 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfcfM59D3bEuJefVWmS:-MfcfM59D3bEuJefVWmT:bh6eyju) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/mesh_half_space_intersection.cc#L238)):*
> ```cpp
>         break;
>       }
>       case ContactPolygonRepresentation::kSingleTriangle:
> ```

nit: add `{` to this case to match the style you use above.
___
*[geometry/proximity/mesh_half_space_intersection.cc, line 239 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfcgBt1AsQM00ahihOP:-MfcgBt1AsQM00ahihOQ:b7zniq6) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/mesh_half_space_intersection.cc#L239)):*
> ```cpp
>       }
>       case ContactPolygonRepresentation::kSingleTriangle:
>         AddPolygonToMeshDataAsOneTriangle(
> ```

Correct me if I'm wrong, but this takes a triangle and spits out a new triangle (cannonical right triangle) in the same plane with the same centroid and area. Isn't this redundant and extra work? Why not just add this triangle as is to the contact surface?
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 158 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-Mfchwvt8IkmC0BYJiXa:-Mfchwvt8IkmC0BYJiXb:bphq3hf) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/test/mesh_half_space_intersection_test.cc#L158)):*
> ```cpp
>   std::vector<SurfaceFace> faces;
>   const RigidTransform<double>& X_WF_d = convert_to_double(X_WF);
>   for (const auto face : mesh_F.faces()) {
> ```

 nit: why not just loop through the vertices, transform them and store the transformed versions in the new vector at the same index?
Then you can just copy `mesh_F.faces()` to `faces` directly and have the same non-shared vertex status.

```
for (int i = 0; i < mesh_F.num_vertices(); ++i) {
  vertices_W.emplace_back(X_WF_d * mesh_F.vertex(SurfaceVertexIndex(i)));
}

std::vector<SurfaceFace> faces(mesh_F.faces());
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

___
*[geometry/proximity/mesh_half_space_intersection.cc, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MeRwxi-7e5RUkToZ7n8:-MfdBaPX2q7w2KPWIIQP:b-i9gw56) ([raw file](https://github.com/robotlocomotion/drake/blob/5f27da52d2fa0599cb0f573ca546e5b4bbd55bb0/geometry/proximity/mesh_half_space_intersection.cc#L34)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

OK, looks good. Is this method only useful in the triangle mesh/halfspace intersection algorithm? Or could it be consolidated further?
</blockquote></details>

That's a good question.  I believe right now it's only for mesh/halfspace.  It might be useful for other algorithm in the future.
___
*[geometry/proximity/mesh_half_space_intersection.cc, line 38 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfcYJ9p66HfTnw87tXV:-MfdCEyaEnl728SGCCe_:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/mesh_half_space_intersection.cc#L38)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: You can also add `DRAKE_DEMAND(a != b)` as a sanity check.
</blockquote></details>

Done. Thanks.
___
*[geometry/proximity/mesh_half_space_intersection.cc, line 238 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfcfM59D3bEuJefVWmS:-MfdCQCHAQmKisjRJaZh:b-alv9tg) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/mesh_half_space_intersection.cc#L238)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: add `{` to this case to match the style you use above.
</blockquote></details>

Done. Thanks.

BTW, the other block needs {} because it defines variables within `case`..., while this block does not. I didn't know that until the compiler complained.  I do agree that giving both of them `{}` looks cleaner. Thanks again.
___
*[geometry/proximity/mesh_half_space_intersection.cc, line 239 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfcgBt1AsQM00ahihOP:-MfdDDMJALK61tM1bUOy:b-p2ljd9) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/mesh_half_space_intersection.cc#L239)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Correct me if I'm wrong, but this takes a triangle and spits out a new triangle (cannonical right triangle) in the same plane with the same centroid and area. Isn't this redundant and extra work? Why not just add this triangle as is to the contact surface?
</blockquote></details>

Good question.  There is no extra work.  `AddPolygonToMeshDataAsOneTriangle()` will use the original triangle if the polygon is already a triangle.

I'll create a small PR to update the documentation of `AddPolygonToMeshDataAsOneTriangle()` and add its unit test to make it clear.  In the mean time, you can keep this comment blocking until I create that PR.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 158 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-Mfchwvt8IkmC0BYJiXa:-MfdGBugAFXProtZ7Mpz:b-x2lpiy) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/test/mesh_half_space_intersection_test.cc#L158)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

 nit: why not just loop through the vertices, transform them and store the transformed versions in the new vector at the same index?
Then you can just copy `mesh_F.faces()` to `faces` directly and have the same non-shared vertex status.

```
for (int i = 0; i < mesh_F.num_vertices(); ++i) {
  vertices_W.emplace_back(X_WF_d * mesh_F.vertex(SurfaceVertexIndex(i)));
}

std::vector<SurfaceFace> faces(mesh_F.faces());
```
</blockquote></details>

If we do that, this test will fail:
```
geometry/proximity/test/mesh_half_space_intersection_test.cc:452: Two triangles inside half space
geometry/proximity/test/mesh_half_space_intersection_test.cc:425: represenation = 1
[  FAILED  ] My/MeshHalfSpaceValueTest/0.InsideOrOnIntersection, where TypeParam = double (0 ms)
```

The reason is that for `ContactPolygonRepresentation::kSingleTriangle`, we are expecting all triangles to be independent sharing no vertices.

I added documentation and renamed the function.  Hopefully it's clearer now.  Thanks for asking.  Please let me know if there's something to improve clarity.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

___
*[geometry/proximity/mesh_half_space_intersection.cc, line 239 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfcgBt1AsQM00ahihOP:-MfdX3NF728I2QRhgrbN:b-8pphia) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/mesh_half_space_intersection.cc#L239)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Good question.  There is no extra work.  `AddPolygonToMeshDataAsOneTriangle()` will use the original triangle if the polygon is already a triangle.

I'll create a small PR to update the documentation of `AddPolygonToMeshDataAsOneTriangle()` and add its unit test to make it clear.  In the mean time, you can keep this comment blocking until I create that PR.
</blockquote></details>

Ok. It's PR #15494.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358#-:-MfdZ0of4CrWGAhxBGVs:bg7igkv)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfdZ1DDA8tNwGfYblZJ:-MfdZ1DDA8tNwGfYblZK:bx6ha7r) (no related file):*
The tests look good. There was a lot more "whitespace" changes than reviewable made it out to seem because of comment reformatting.

I think there is some redundancy in the tests that check the different cases for mesh/halfspace intersection with the two modes. You could possibly refactor so that the "expected meshes" are computed separately as data and passed into a more generic test that cleans up the repeated code. Not a suggestion for this PR, but merely for posterity and because you asked how you might shorten it.

---
___
*[geometry/proximity/mesh_half_space_intersection.cc, line 239 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfcgBt1AsQM00ahihOP:-Mfd_LOk0XiS2XxISjtu:b-w3d99j) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/mesh_half_space_intersection.cc#L239)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Ok. It's PR #15494.
</blockquote></details>

OK, I see now. I just got to the point in `AddPolygonToMeshDataAsOneTriangle()` where it calculates the polygon's area and thought: "why do we need to do this for a triangle?". But it doesn't calculate extra vertices, as you've said.

The documentation does say "the choice of representative triangle is arbitrary" so I should have read that as being enough. Thanks for clarifying in the doc though
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 158 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15358#-Mfchwvt8IkmC0BYJiXa:-MfdQgVX8FKatcQt6-u2:b5xruuw) ([raw file](https://github.com/robotlocomotion/drake/blob/06d08f88c2aa349dd0d47a4a875e2c8f21678fb6/geometry/proximity/test/mesh_half_space_intersection_test.cc#L158)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

If we do that, this test will fail:
```
geometry/proximity/test/mesh_half_space_intersection_test.cc:452: Two triangles inside half space
geometry/proximity/test/mesh_half_space_intersection_test.cc:425: represenation = 1
[  FAILED  ] My/MeshHalfSpaceValueTest/0.InsideOrOnIntersection, where TypeParam = double (0 ms)
```

The reason is that for `ContactPolygonRepresentation::kSingleTriangle`, we are expecting all triangles to be independent sharing no vertices.

I added documentation and renamed the function.  Hopefully it's clearer now.  Thanks for asking.  Please let me know if there's something to improve clarity.
</blockquote></details>

OK I see. As long as it is intentional then that works for me.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 725 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfdVNwb6JTrI9AmQeNL:-MfdVNwb6JTrI9AmQeNM:b-r21hm1) ([raw file](https://github.com/robotlocomotion/drake/blob/98656dd482f3406737b689391915fa6a2b1abff4/geometry/proximity/test/mesh_half_space_intersection_test.cc#L725)):*
> ```cpp
>       }
>       case ContactPolygonRepresentation::kSingleTriangle: {
>         ASSERT_EQ(this->new_faces().size(), 1);
> ```

nit: it might be helpful for short reminder comments at the end of these lines that reinforce the expected behavior. (1 new face per original polygon, each face is a triangle, all new vertices, etc.)
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1008 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfdYMr09vPO36GOhPlR:-MfdYMr11h7yaJZ0PcUY:b-ujjj80) ([raw file](https://github.com/robotlocomotion/drake/blob/98656dd482f3406737b689391915fa6a2b1abff4/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1008)):*
> ```cpp
>         // has one representative triangle.
>         ASSERT_EQ(intersection_mesh_W->num_faces(), 10);
>         // The ten representative triangles do not share vertices, so there
> ```

FYI: great comments, made it really easy to understand.

**Review by joemasterjohn — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358#-:-Mfd_Njn38TultjeRQvs:b-syrr9x)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @DamrongGuoy and @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @joemasterjohn and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfdZ1DDA8tNwGfYblZJ:-Mfdfj6l06jyZIlj8YQO:b38v9yq) (no related file):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

The tests look good. There was a lot more "whitespace" changes than reviewable made it out to seem because of comment reformatting.

I think there is some redundancy in the tests that check the different cases for mesh/halfspace intersection with the two modes. You could possibly refactor so that the "expected meshes" are computed separately as data and passed into a more generic test that cleans up the repeated code. Not a suggestion for this PR, but merely for posterity and because you asked how you might shorten it.
</blockquote></details>

That's a good idea. I'll think about it next time.  Separating data from code sounds reasonable.

---
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 725 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfdVNwb6JTrI9AmQeNL:-MfdeQoZBzpJHaO1vWt5:b-vskw98) ([raw file](https://github.com/robotlocomotion/drake/blob/98656dd482f3406737b689391915fa6a2b1abff4/geometry/proximity/test/mesh_half_space_intersection_test.cc#L725)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: it might be helpful for short reminder comments at the end of these lines that reinforce the expected behavior. (1 new face per original polygon, each face is a triangle, all new vertices, etc.)
</blockquote></details>

Done.  I hope it helps not hurts.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1008 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfdYMr09vPO36GOhPlR:-MfdeP2g-5gMTNkHxF4Z:b-9755fn) ([raw file](https://github.com/robotlocomotion/drake/blob/98656dd482f3406737b689391915fa6a2b1abff4/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1008)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

FYI: great comments, made it really easy to understand.
</blockquote></details>

Thank you!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @DamrongGuoy and @joemasterjohn)

___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 342 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfdeXWkBPuR9uOlKSvq:-MfdeXWl17iVmrAYP6hh:bwcr83o) ([raw file](https://github.com/robotlocomotion/drake/blob/98656dd482f3406737b689391915fa6a2b1abff4/geometry/proximity/test/mesh_half_space_intersection_test.cc#L342)):*
> ```
> represenation
> ```
typo

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358#-:-Mfdh5Hz7vBIUSnFOtyB:bnfp4nl)* status: 2 unresolved discussions (waiting on @DamrongGuoy and @joemasterjohn)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358)* status: 2 unresolved discussions (waiting on @DamrongGuoy, @joemasterjohn, and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358)* status: 2 unresolved discussions (waiting on @DamrongGuoy and @joemasterjohn)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 342 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15358#-MfdeXWkBPuR9uOlKSvq:-Mfdm5v67Yptnys6qhKf:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/98656dd482f3406737b689391915fa6a2b1abff4/geometry/proximity/test/mesh_half_space_intersection_test.cc#L342)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> represenation
> ```
typo
</blockquote></details>

Done. Thanks!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15358)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn (waiting on @DamrongGuoy)

**Pull request merged**
