### PR TITLE
[parsing] Remove forced_nesting_sdf unit test support

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
There's no need to have unit test coverage for codepaths that are dead as far as Drake users are concerned.

(Discussed at https://github.com/RobotLocomotion/drake/pull/16727#issuecomment-1145156575 initially.  Originally added in #15140.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17323)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review / discussion, please.  (Discussed at https://github.com/RobotLocomotion/drake/pull/16727#issuecomment-1145156575 initially.)

It's plausible that this lost some test coverage of frame pose offsets, if the sample model files aren't quite exercised enough anymore.  I'd appreciate if you could check on that and push any new test code, or else point out to me the missing concepts and I'll work on adding the test cases.

I'm also fine if you'd like to delegate any of the review or test work to OpenRobotics folks.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17323#-:-N3vBkWk1LBJq21XxhPM:bybe5xg)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @jwnimmer-tri and @sherm1)

___
*[`multibody/parsing/test/sdf_parser_test/interface_api_test/top.sdf` line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17323#-N3v0Qvi8-kbs2RKxZRh:-N3vBrFZESXcaesjVnHA:bn00yq8) ([raw file](https://github.com/robotlocomotion/drake/blob/0e66ab33d609068daeb167cf723f665a9da5577b/multibody/parsing/test/sdf_parser_test/interface_api_test/top.sdf#L36)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I see the decrease in testing you mentioned, but yeah, I think it's fine / possibly redundant.
If there is a lack of coverage at present, I believe we can restore it in or after @azeey's merge-include parsing PR.

@azeey Does that work for you?
</blockquote></details>

Setting myself to "Working" to block on @azeey's reply.

**Comment by azeey** [comment]
*[`multibody/parsing/test/sdf_parser_test/interface_api_test/top.sdf` line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17323#-N3v0Qvi8-kbs2RKxZRh:-N3vGR8fA4GMtcJA_l-6:b-ucdj9k) ([raw file](https://github.com/robotlocomotion/drake/blob/0e66ab33d609068daeb167cf723f665a9da5577b/multibody/parsing/test/sdf_parser_test/interface_api_test/top.sdf#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Setting myself to "Working" to block on @azeey's reply.
</blockquote></details>

Yes, that sounds good.

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17323#-:-N42z4SeE7g0D7qUEUgr:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
