### PR TITLE
workspace: Upgrade ignition_math to latest release 6.8.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14848)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews on Monday, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'd have expected that this went through a mac build already (as per https://drake.mit.edu/code_review_checklist.html).

:LGTM:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14848#-:-MXXDjAADFfRdPY6VQDV:b-xqub1i)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
The OSRC code, especially minor releases, have historically been low risk so I sometimes skip them -- but since I'm not in a hurry, we can check anyway:

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
Sounds good.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14848#-:-MXZJPVaB-CKX_oiwd80:brxp9sq)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
