### PR TITLE
[sensors] Migrate CameraConfig from anzu

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This introduces the `CameraConfig` class into Drake. This is predominantly a copy and clean up operation from Anzu.

Relates #17112

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
Note to reviewer:

- R1: Is simply the copy of the anzu files.
- R2: contains the tweaks to make it happy in Drake land.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787#-:-NAe671aCUBpK2-K4mz3:bf2k4z3)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe6CIM4P50UmD3kn5c:-NAe6CIM4P50UmD3kn5d:bjuqv7k) (no related file):*
There is a disappointing artifact in the rendered doxygen. The best way to observe it is to build the doxygen yourself. But to help direct your eye, I'll attempt to summarize.

The documentation for `CameraConfig` makes liberal use of `/** @name ...*/` grouping to cluster the attributes (camera intrinsics, extrinsics, publishing, etc.) Each group should be an equal sibling. However, they aren't *rendered* that way. See the attached snippet contrasting "Publishing properties" and "Camera intrinsics" (N.B. the rendering for "Publishing properties" is representative of all of the other groups; camera intrinsics is the outlier.)



The *cause* of this is that "Camera intrinsics" is the only group that includes *functions*. All of the other groups include only attributes. Doxygen does its own categorization and grouping based on this. I'm open to some thoughts on this:

1. Simply shrug and say, "Don't care".
2. Exclude the functions from the group. Although, the getters for focal length and principal point *are* the preferred APIs for accessing those quantities robustly.
3. Shuffle things up and put the helper functions in their own group and add some documentation to the header making sure we call out those helper functions.

Thougts?

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe7_Oe9A3eUW5wi-Ms:-NAe7_Oe9A3eUW5wi-Mt:b-7qvwdk) (no related file):*
On a wholly unrelated topic, am I the only person that *hates* what doxygen does with long return types?



I tried using the doxygen macro to shrink it (removing namespaces). It was nice in terms of reducing the width, but the class names no longer linked. Has anyone else had thoughts for resolving this kind of thing? It's trickier when it's a putative part of the signature.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@zachfang for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787#-:-NAe8463-2XXUUTayvDl:b98akcj)* status: 2 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
:lgtm: Most of the nits are dependency-related. For the Doxygen long return type, I don't hate it enough (although I think it's ugly) to object it :shrug: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787#-:-NAearh_6QYmJHT1KtP_:b-rnjk7d)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI and @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe6CIM4P50UmD3kn5c:-NAe_aoSAAgmJ1AOjtQ8:bfh7xmm) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

There is a disappointing artifact in the rendered doxygen. The best way to observe it is to build the doxygen yourself. But to help direct your eye, I'll attempt to summarize.

The documentation for `CameraConfig` makes liberal use of `/** @name ...*/` grouping to cluster the attributes (camera intrinsics, extrinsics, publishing, etc.) Each group should be an equal sibling. However, they aren't *rendered* that way. See the attached snippet contrasting "Publishing properties" and "Camera intrinsics" (N.B. the rendering for "Publishing properties" is representative of all of the other groups; camera intrinsics is the outlier.)



The *cause* of this is that "Camera intrinsics" is the only group that includes *functions*. All of the other groups include only attributes. Doxygen does its own categorization and grouping based on this. I'm open to some thoughts on this:

1. Simply shrug and say, "Don't care".
2. Exclude the functions from the group. Although, the getters for focal length and principal point *are* the preferred APIs for accessing those quantities robustly.
3. Shuffle things up and put the helper functions in their own group and add some documentation to the header making sure we call out those helper functions.

Thougts?
</blockquote></details>

For me, the introduced offset is not too terrible, so I vote for `maybe (1) but definitely not (2)`. I am not quite sure what option (3) means though.

___
___
*[`systems/sensors/BUILD.bazel` line 84 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAeDtVH2AiwUGXKl2hd:-NAeDtVH2AiwUGXKl2he:bmuw9h) ([raw file](https://github.com/robotlocomotion/drake/blob/af7be5cf18e83bd34b86082fbf9b8103ca522144/systems/sensors/BUILD.bazel#L84)):*
> ```Starlark
>         "//geometry:rgba",
>         "//geometry/render:render_camera",
>         "//systems/sensors:camera_info",
> ```

nit: this should be ":camera_info"?
___
*[`systems/sensors/camera_config.h` line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAeZsaWDsjSysWCKyH0:-NAeZsaXEQ2FK_pgZmZB:bvihjjo) ([raw file](https://github.com/robotlocomotion/drake/blob/af7be5cf18e83bd34b86082fbf9b8103ca522144/systems/sensors/camera_config.h#L3)):*
> ```objc
> #pragma once
> 
> #include <cmath>
> ```

nit: looks like `cmath` is only needed in the cc fil
___
*[`systems/sensors/camera_config.h` line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAeIV6C8JxdBeCrLRiV:-NAeIV6D5VBskzn1JGxj:b-fyjksk) ([raw file](https://github.com/robotlocomotion/drake/blob/af7be5cf18e83bd34b86082fbf9b8103ca522144/systems/sensors/camera_config.h#L10)):*
> ```objc
> 
> #include "drake/common/name_value.h"
> #include "drake/common/never_destroyed.h"
> ```

nit: is this used?
___
*[`systems/sensors/camera_config.h` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAeW6Yv0OxzadMnaUqA:-NAeW6Yv0OxzadMnaUqB:b-p8n8k9) ([raw file](https://github.com/robotlocomotion/drake/blob/af7be5cf18e83bd34b86082fbf9b8103ca522144/systems/sensors/camera_config.h#L144)):*
> ```objc
>    that undefined center_x and center_y place the principal point in the center
>    of the image. */
>   Vector2<double> principal_point() const {
> ```

nit: #include "drake/eigen_type.h"?
___
*[`systems/sensors/camera_config.h` line 241 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAeUB4G2x4mgJJMMq9G:-NAeUB4G2x4mgJJMMq9H:b9g008p) ([raw file](https://github.com/robotlocomotion/drake/blob/af7be5cf18e83bd34b86082fbf9b8103ca522144/systems/sensors/camera_config.h#L241)):*
> ```objc
> 
>   /** The camera name. This `name` is used as part of the corresponding
>    RgbdSensor system's name and serves as a suffix of the
> ```

nit: some of the `Lcm channel name` can move to the previous line after removing the namespace.



_Code quote:_
```objc
   RgbdSensor system's name and serves as a suffix of the
   LCM channel name.
```
___
*[`systems/sensors/camera_config.cc` line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAeGurY8UczYRp6h8Fh:-NAeGurY8UczYRp6h8Fi:buwlby8) ([raw file](https://github.com/robotlocomotion/drake/blob/af7be5cf18e83bd34b86082fbf9b8103ca522144/systems/sensors/camera_config.cc#L4)):*
> ```cpp
> 
> #include <cmath>
> #include <iostream>
> ```

BTW. An unrelated note- Jeremy had a PR before to remove all the `<iostream>` usage and I think the reason applies here as well?
Reference: https://github.com/RobotLocomotion/drake/pull/17415
___
*[`systems/sensors/test/camera_config_test.cc` line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAeVRGG2aVnbz1FZIb-:-NAeVRGG2aVnbz1FZIb0:bo0nx15) ([raw file](https://github.com/robotlocomotion/drake/blob/af7be5cf18e83bd34b86082fbf9b8103ca522144/systems/sensors/test/camera_config_test.cc#L3)):*
> ```cpp
> #include "drake/systems/sensors/camera_config.h"
> 
> #include <vector>
> ```

nit: should we be including `"drake/eigen_types.h"` or `<Eigen/Dense>` instead?
___
*[`systems/sensors/test/camera_config_test.cc` line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAeLEWM9yXFWvwbFQqG:-NAeLEWM9yXFWvwbFQqH:b3hmeia) ([raw file](https://github.com/robotlocomotion/drake/blob/af7be5cf18e83bd34b86082fbf9b8103ca522144/systems/sensors/test/camera_config_test.cc#L10)):*
> ```cpp
> 
> #include "drake/common/schema/transform.h"
> #include "drake/common/test_utilities/eigen_matrix_compare.h"
> ```

nit: looks like this is unused?



_Code quote:_
```cpp
"drake/common/test_utilities/eigen_matrix_compare.h"
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri for Tuesday platform review. This is code coming over from Anzu (code you're somewhat familiar with by now). Good luck putting your platform review hat on.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787#-:-NAfgTMj1nF7s2GVIuv-:b-pdxvgo)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe6CIM4P50UmD3kn5c:-NAfg-oG5lGlZAW_fcjG:b-cuds07) (no related file):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

For me, the introduced offset is not too terrible, so I vote for `maybe (1) but definitely not (2)`. I am not quite sure what option (3) means though.
</blockquote></details>

In the absence of a "solution", I'm leaving it alone with a sigh and a shrug.

___
___
*[`systems/sensors/test/camera_config_test.cc` line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAeVRGG2aVnbz1FZIb-:-NAffoYE4HkiTtJTxlHd:b893w14) ([raw file](https://github.com/robotlocomotion/drake/blob/af7be5cf18e83bd34b86082fbf9b8103ca522144/systems/sensors/test/camera_config_test.cc#L3)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: should we be including `"drake/eigen_types.h"` or `<Eigen/Dense>` instead?
</blockquote></details>

IWYU (include what you use) is always a good thing, even if we don't have automated enforcement (globally). So, calling me on this is for the good. Thanks.

**Review by zachfang — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @zachfang)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with question about default value of focal length(s) and its affect on future users (who may want things to "just work" with changing image dimensions).

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787#-:-NAjSyi53bWNHWPYp2Xf:b-gd2h6x)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe7_Oe9A3eUW5wi-Ms:-NAjCjhIATvMBb2_V2fv:b-kwo8s0) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

On a wholly unrelated topic, am I the only person that *hates* what doxygen does with long return types?



I tried using the doxygen macro to shrink it (removing namespaces). It was nice in terms of reducing the width, but the class names no longer linked. Has anyone else had thoughts for resolving this kind of thing? It's trickier when it's a putative part of the signature.
</blockquote></details>

I'd agree that it's annoying, but I'm not sure if I'd ever be annoyed enough to fix it myself hehe.
That being said, maybe Doxygen and/or CSS have an option to do work-wrap breaks in certain ways for this column.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe6CIM4P50UmD3kn5c:-NAjDiiC0c4MquLrBsrc:bh9im4q) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In the absence of a "solution", I'm leaving it alone with a sigh and a shrug.
</blockquote></details>

Is this because the grouping uses `//@{` instead of `///@{`?

___
___
*[`systems/sensors/camera_config.h` line 122 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAjFzZp8awBJWsEc2Ya:-NAjFzZp8awBJWsEc2Yb:bo0dr7o) ([raw file](https://github.com/robotlocomotion/drake/blob/cad1539b4f9961166b0185a5f6a6cece1dbcb254/systems/sensors/camera_config.h#L122)):*
> ```objc
>    lens is symmetric. Otherwise the anisotropic values are used in the x- and
>    y-directions. @pre focal length(s) is a/are finite, positive number(s). */
>   std::variant<double, Anisotropic, FovDegrees> focal{500};
> ```

Sorry for not bringing this up during earlier review in Anzu, but why not default to `FovDegrees{.y = 45}`?
This may be most logical for most users, as it will actually scale according to image size (height).

In Anzu, we could override this in config call-sites to avoid switching behavior.
___
*[`systems/sensors/test/camera_config_test.cc` line 121 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAjGPBVEyZ-T3ZMuFae:-NAjGPBVEyZ-T3ZMuFaf:b-z06tm4) ([raw file](https://github.com/robotlocomotion/drake/blob/cad1539b4f9961166b0185a5f6a6cece1dbcb254/systems/sensors/test/camera_config_test.cc#L121)):*
> ```cpp
>   const double kFovYDeg = intrinsics.fov_y() * 180 / M_PI;
>   {
>     // Just specifying fov_x a) computes the right focal length and the same
> ```

nit Unclear why `a)` enumeration is here. Not sure what it references, nor what it distinguishes itself against. (here and below)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe6CIM4P50UmD3kn5c:-NAjTVW71qJmVffN4nAp:b-3bku68) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is this because the grouping uses `//@{` instead of `///@{`?
</blockquote></details>

Nope. It's because of the *contents* of the group. When the whole group contains only fields, Doxygen puts it in as a *sub group* of a group called "Public attributes" (or some such thing). But when the group is of heterogeneous make up, it *can't* be a child of that group, and, instead, becomes a *sibling* of the attribute group.

So, perhaps I should add functions to *all* of the other groups so *none* of them get nested.  :D

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe7_Oe9A3eUW5wi-Ms:-NAjU121018TvT44rVsT:bokcmy4) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'd agree that it's annoying, but I'm not sure if I'd ever be annoyed enough to fix it myself hehe.
That being said, maybe Doxygen and/or CSS have an option to do work-wrap breaks in certain ways for this column.
</blockquote></details>

The worst is when you have a `std::enable_if` on the return type. Ka! Boom!

___
___
*[`systems/sensors/camera_config.h` line 122 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAjFzZp8awBJWsEc2Ya:-NAjUWXo5ZIwHuZEK72Q:b-vt536b) ([raw file](https://github.com/robotlocomotion/drake/blob/cad1539b4f9961166b0185a5f6a6cece1dbcb254/systems/sensors/camera_config.h#L122)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry for not bringing this up during earlier review in Anzu, but why not default to `FovDegrees{.y = 45}`?
This may be most logical for most users, as it will actually scale according to image size (height).

In Anzu, we could override this in config call-sites to avoid switching behavior.
</blockquote></details>

I agree. This seems very reasonable.
___
*[`systems/sensors/test/camera_config_test.cc` line 121 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAjGPBVEyZ-T3ZMuFae:-NAjVIcF-FpPYEJNzIiw:b-df4v5g) ([raw file](https://github.com/robotlocomotion/drake/blob/cad1539b4f9961166b0185a5f6a6cece1dbcb254/systems/sensors/test/camera_config_test.cc#L121)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why `a)` enumeration is here. Not sure what it references, nor what it distinguishes itself against. (here and below)
</blockquote></details>

Patched.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe6CIM4P50UmD3kn5c:-NAjVjm8BkuRqly9pd9j:b-pxxiuh) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Nope. It's because of the *contents* of the group. When the whole group contains only fields, Doxygen puts it in as a *sub group* of a group called "Public attributes" (or some such thing). But when the group is of heterogeneous make up, it *can't* be a child of that group, and, instead, becomes a *sibling* of the attribute group.

So, perhaps I should add functions to *all* of the other groups so *none* of them get nested.  :D
</blockquote></details>

Ah, gotcha.

Perhaps option (4) is to ditch Doxygen-based grouping altogether?

___
___
*[`systems/sensors/camera_config.h` line 120 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAjW0ad0Z7CbX8nldoB:-NAjW0ad0Z7CbX8nldoC:b84e31s) ([raw file](https://github.com/robotlocomotion/drake/blob/58da181d0bf12416e4ec0f9ef99efda1adae543d/systems/sensors/camera_config.h#L120)):*
> ```objc
> 
>   /** Focal length(s) of the camera (in pixels). If a single value is given, the
>    lens is symmetric. Otherwise the anisotropic values are used in the x- and
> ```

nit Docstring is missing description of FOV in degrees. Consider adding reference or inline the logic? e.g.
```
Focal length(s) of the camera.

If specified as scalar, symmetric focal length in pixels.
If specified as Anisotropic, then ...
If specified as FovDegrees, then ...
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe6CIM4P50UmD3kn5c:-NAjWWj89rl0td-ZyNjC:b-to76ky) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, gotcha.

Perhaps option (4) is to ditch Doxygen-based grouping altogether?
</blockquote></details>

("altogether" => "in this location where it may make things less clear")

___

**Comment by SeanCurtis-TRI** [comment]
*[`systems/sensors/camera_config.h` line 120 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAjW0ad0Z7CbX8nldoB:-NAjXHDA470FcmaQZNNl:b-mknhim) ([raw file](https://github.com/robotlocomotion/drake/blob/58da181d0bf12416e4ec0f9ef99efda1adae543d/systems/sensors/camera_config.h#L120)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Docstring is missing description of FOV in degrees. Consider adding reference or inline the logic? e.g.
```
Focal length(s) of the camera.

If specified as scalar, symmetric focal length in pixels.
If specified as Anisotropic, then ...
If specified as FovDegrees, then ...
```
</blockquote></details>

As I was writing this documentation, the thought occurred to me that this API represents inconsistent APIs.

Here's the proposal for your consideration:

1. It should be a variant of two types: `Length` and `FovDegrees` (although, one can make an argument for `LengthPixels` instead).
2. Both have the same semantics of being able to define only one value of the two so that the focal lengths are symmetric (the choice of which one is arbitrary).
3. We get rid of the single, unadorned scalar value entirely.

Thoughts?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`systems/sensors/camera_config.h` line 120 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAjW0ad0Z7CbX8nldoB:-NAjYSviAT-CVwaAx4sn:b5vlzqd) ([raw file](https://github.com/robotlocomotion/drake/blob/58da181d0bf12416e4ec0f9ef99efda1adae543d/systems/sensors/camera_config.h#L120)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

As I was writing this documentation, the thought occurred to me that this API represents inconsistent APIs.

Here's the proposal for your consideration:

1. It should be a variant of two types: `Length` and `FovDegrees` (although, one can make an argument for `LengthPixels` instead).
2. Both have the same semantics of being able to define only one value of the two so that the focal lengths are symmetric (the choice of which one is arbitrary).
3. We get rid of the single, unadorned scalar value entirely.

Thoughts?
</blockquote></details>

Sounds great!

(1) `LengthPixels` sounds good, for consistency w/ `FovDegrees`.
(2) Yes!
(3) Yes!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAe6CIM4P50UmD3kn5c:-NAjYg29685a3I95YrRz:b-81nlyp) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I feel the group adds value (clustering intrinsics) more than it loses value (separating it from other properties). So, meh.
</blockquote></details>

SGTM!

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @zachfang)

___
*[`systems/sensors/camera_config.h` line 120 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17787#-NAjW0ad0Z7CbX8nldoB:-NAjZfyu3nCxZFFV88Ea:b-8929qu) ([raw file](https://github.com/robotlocomotion/drake/blob/58da181d0bf12416e4ec0f9ef99efda1adae543d/systems/sensors/camera_config.h#L120)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sounds great!

(1) `LengthPixels` sounds good, for consistency w/ `FovDegrees`.
(2) Yes!
(3) Yes!
</blockquote></details>

Ok. Take a look.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787#-:-NAkCA4S3RnS71plU5pI:bm9o57a)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17787#-:-NAkCFM97rEGX4xQdAR_:b-l8xbmn)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),zachfang (waiting on @SeanCurtis-TRI)

**Pull request merged**
