### PR TITLE
Update std::shared_ptr argument passing to be closer to idiomatic C++.

### PR DESCRIPTION
**Pull request by jpieper-tri**
The CppCoreGuidelines recommend that std::shared_ptr only be passed as
an argument when the callee explicitly needs to manage the lifetime of
the argument, and that 'const std::shared_ptr<T>&' should only be used
if there is a chance that lifetime will not be shared.

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-smartptrparam

Many instances in drake were passing 'const std::shared_ptr<T>&'
around, often when no lifetime management was necessary, and otherwise
when lifetime sharing was unconditional.  This can be less efficient,
unnecessarily restrictive, and hides the intent of the API.

This patch converts those instances either to:
 * [const] T* if no lifetime sharing is required
 * std::shared_ptr<T> if lifetime sharing is always required

### CODE REVIEW

**Comment by tkoolen** [comment]
Nice, agree that this is better. I was wondering though: why use [const] T* instead of [const] T&?

**Comment by sherm1** [comment]
Nice! It's great to treat lifetime issues clearly.

> [const] T* if no lifetime sharing is required

Better if these could be `[const] T&` if the called method is really just expecting to use a T. Passing the pointer obligates the called routine to deal with null and makes it awkward to operate on temp objects.

**Comment by jpieper-tri** [comment]
There was no particularly principled reason for 'T*' instead of 'T&', other than it reduced the amount of churn in function bodies (which effectively already had to deal with the possibility of a null shared_ptr).  I agree that '[const] T&' is superior and will resubmit with that approach.

**Comment by david-german-tri** [comment]
:+1:

**Pull request closed without merging**
