### PR TITLE
Implements a drake::math method to shift time derivatives between different frames.

### PR DESCRIPTION
**Pull request by amcastro-tri**
This method is needed for acceleration kinematics. I am pushing it separately since there were some questions regarding notation in #6429. 
cc'in @sherm1, @mitiguy

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6451)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
@edrumwri for feature review please since this will help you understand what is going on in the SpatialAcceleration class.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-:-KnjXqGveFe7XiHb1c6L:baqaiww)*

**Comment by sherm1** [comment]
+@sherm1 reviewed -- PTAL. I like the notation!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/shift_time_derivative.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-Knjd4D9kLfXxpaDRcJ6:-Knjd4D9kLfXxpaDRcJ7:bb0ipji) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L31)):*
> ```objc
> /// Differentiation".
> ///
> /// [Mitiguy 2016] Mitiguy, P., 2016. Advanced Dynamics & Motion Simulation.
> ```

BTW This is a great comment and I like the notation!

---

*[drake/math/shift_time_derivative.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnjcIBHK_KUhUnu_nK3:-KnjcIBIEjXTH0-5ZzFs:b21cwva) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L32)):*
> ```objc
> ///
> /// [Mitiguy 2016] Mitiguy, P., 2016. Advanced Dynamics & Motion Simulation.
> template <typename v_Type, typename DB_v_Type, typename w_AB_Type>
> ```

BTW why have three different template arguments if they all have to be the same underneath? Could this be simplifed use Eigen::Ref?

If not, could you please explain why this method has this unusual structure?

---

*[drake/math/test/shift_time_derivative_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnjewLUX8so_Z4VynvK:-KnjewLUX8so_Z4VynvL:b-9vrdwe) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L55)):*
> ```cpp
> //          and C rotates according to the right-hand-rule around the z-axis.
> //   theta_dot: the rate of change of theta.
> void HorseOnCarousel(double horse_radius,
> ```

Cool test! 

The unit test isn't sufficient though because the horse has zero velocity in the moving frame. That means all the terms involving DC_p_CoHo get multiplied by zero, so if there was an error the test wouldn't catch it. Can you add one more test case where the horse has at least some simplified velocity in C?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-:-KnjfgFDh6Wnn54qOqJ1:bw1yxcm)*

**Comment by sherm1** [comment]
Discussed with @mitiguy & @seancurtis-tri. Paul has some comments coming ...

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-:-Knjju0yaz5qJq1KW5o1:brtpi6k)*

**Comment by amcastro-tri** [comment]
+@sherm1 for feature review. -@edrumwri 
+@ggould-tri for platform please. 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/math/shift_time_derivative.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnjcIBHK_KUhUnu_nK3:-Knjl4Pl6gY_CbltFgv1:bz8rpso) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L32)):*
BTW. 
> why have three different template arguments

So that you allow one of those be say a `Vector3`, another one to be a `Block` and another one say a `Map`.  The wacky template is the mechanism Eigen provides for this kind of things, [see Eigen's doc on this here](http://eigen.tuxfamily.org/dox/TopicFunctionTakingEigenTypes.html).

> Could this be simplifed use Eigen::Ref?

You cannot. The reason is that for Eigen::Ref to work you have to know the scalar type before hand (say double) or be within a scope where you can assume you know it (say inside a class templated on T). That is why here in math you'll see these free standing methods templated `<Derived>` while in `sytems::` you seem methods taking a `Eigen::Ref`. See for instance `cross_product.h` or `gradient.h`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-:-KnjmPkTKOK-XzlTmrCp:b8uglq)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by amcastro-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/test/shift_time_derivative_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnjewLUX8so_Z4VynvK:-KnjpjJqHix-MuQqnMDQ:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L55)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Cool test! 

The unit test isn't sufficient though because the horse has zero velocity in the moving frame. That means all the terms involving DC_p_CoHo get multiplied by zero, so if there was an error the test wouldn't catch it. Can you add one more test case where the horse has at least some simplified velocity in C?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-:-Knjs65VYBizN-Gp6-du:bnfp4nl)*

**Comment by mitiguy** [comment]
Review status: 2 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/math/shift_time_derivative.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkEku2tUOMiFc11nvK:-KnkEku2tUOMiFc11nvL:bgocjgt) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L31)):*
> ```objc
> /// Differentiation".
> ///
> /// [Mitiguy 2016] Mitiguy, P., 2016. Advanced Dynamics & Motion Simulation.
> ```

Please consider the following for documentation:

/// Given ᴮd/dt(v) (the time derivative in frame B of an arbitrary 3D vector v)
/// and given ᴬωᴮ (frame B's angular velocity in another frame A), this method 
/// computes ᴬd/dt(v) (the time derivative in frame A of v) by:
///  ᴬd/dt(v) = ᴮd/dt(v) + ᴬωᴮ x v
///
/// This mathematical operation is known as the "Transport Theorem" or the
/// "Golden Rule for Vector Differentiation" [Mitiguy 2016, §7.3].  It was
/// discovered by Euler in 1758.  Its explicit notation with superscript 
/// frames was invented by Thomas Kane in 1950.  Its use as the defining
/// property of angular velocity was by Mitiguy in 1993.
/// 
/// In source code and comments, we use the following monogram notations:
/// `DtA_v = ᴬd/dt(v)` denotes the time derivative in frame A of the vector v.
/// `DtA_v_E = [ᴬd/dt(v)]_E` denotes the time derivative in frame A of vector v,
///  with the resulting new vector quantity expressed in a frame E.
///
/// In source code, this mathematical operation is performed with all vectors
/// expressed in the same frame E as   [ᴬd/dt(v)]ₑ = [ᴮd/dt(v)]ₑ + [ᴬωᴮ]ₑ x [v]ₑ
/// which in monogram notation is: <pre>
///   DtA_v_E = DtB_v_E + w_AB_E x v_E
/// </pre>
///
/// [Mitiguy 2016] Mitiguy, P., 2016. Advanced Dynamics & Motion Simulation.

---

*[drake/math/shift_time_derivative.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkF69NNbWI9HV7nubh:-KnkF69NNbWI9HV7nubi:b-km6pgf) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L32)):*
> ```objc
> ///
> /// [Mitiguy 2016] Mitiguy, P., 2016. Advanced Dynamics & Motion Simulation.
> template <typename v_Type, typename DB_v_Type, typename w_AB_Type>
> ```

Everywhere in the code, please use Dt (not D), e.g., DtB_v_Type
This is particularly helpful to disambiguate the operator Dt
from the possibility of a frame D.

---

*[drake/math/shift_time_derivative.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkFPvc3D2wmphDS6jQ:-KnkFPvc3D2wmphDS6jR:b-q0heyb) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L36)):*
> ```objc
>     const Eigen::MatrixBase<v_Type>& v_E,
>     const Eigen::MatrixBase<DB_v_Type>& DB_v_E,
>     const Eigen::MatrixBase<w_AB_Type>& w_AB_E) {
> ```

The "Shift" word is typically used for calculations involving a shift in location.
Please change ShiftTimeDerivative to 
ConvertVectorTimeDerivativeToOtherFrame.

---

*[drake/math/shift_time_derivative.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkGKHS6h7lDDCTrsN7:-KnkGKHS6h7lDDCTrsN8:bi27m4q) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L40)):*
> ```objc
>   EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(Eigen::MatrixBase<v_Type>, 3);
>   EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(Eigen::MatrixBase<DB_v_Type>, 3);
>   EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(Eigen::MatrixBase<w_AB_Type>, 3);
> ```

DB_v_Type  to  DtB_v_Type

---

*[drake/math/test/shift_time_derivative_test.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkGcD6i25DmVw6nX89:-KnkGcD6i25DmVw6nX8A:b1al03a) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L17)):*
> ```cpp
> // Given an angular velocity w_AB of a frame B in A, verifies that the time
> // derivative of this angular velocity is the same in both frames. That is:
> //   d_A(w_AB)/dt = d_B(w_AB)/dt
> ```

Use unicode for at least the derivative, e.g.,  
ᴬd/dt(w_AB) = ᴮd/dt(w_AB)   or 
ᴬd/dt( ᴬωᴮ) = ᴮd/dt( ᴬωᴮ)   or 

---

*[drake/math/test/shift_time_derivative_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkH-zirWP5DsBpJbbF:-KnkH-zirWP5DsBpJbbG:b-x45y85) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L20)):*
> ```cpp
> // Input parameters:
> //   w_AB: angular velocity of B in A.
> //   DB_w_AB: Time derivative of w_AB in the B frame.
> ```

DtB_w_AB

---

*[drake/math/test/shift_time_derivative_test.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkHAVxgjCSd9XriDVE:-KnkHAVxgjCSd9XriDVF:b90grpn) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L21)):*
> ```cpp
> //   w_AB: angular velocity of B in A.
> //   DB_w_AB: Time derivative of w_AB in the B frame.
> void ShiftTimeDerivativeOfAngularVelocity(
> ```

ConvertAngularVectorTimeDerivativeToOtherFrame.

---

*[drake/math/test/shift_time_derivative_test.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkHDbCvRZ940o0hewq:-KnkHDbCvRZ940o0hewr:b-9xvavx) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L22)):*
> ```cpp
> //   DB_w_AB: Time derivative of w_AB in the B frame.
> void ShiftTimeDerivativeOfAngularVelocity(
>     const Vector3d& w_AB, const Vector3d& DB_w_AB) {
> ```

Change  DB_w_AB  to   DtB_w_AB.
Similarly for rest of code.

---

*[drake/math/test/shift_time_derivative_test.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkHRRFuIONtKsUNjuE:-KnkHRRFuIONtKsUNjuF:bxi0hbn) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L24)):*
> ```cpp
>     const Vector3d& w_AB, const Vector3d& DB_w_AB) {
>   const double kAbsoluteTolerance = 2 * std::numeric_limits<double>::epsilon();
>   Vector3d DA_w_AB = ShiftTimeDerivative(w_AB, DB_w_AB, w_AB);
> ```

  Vector3d DtA_w_AB = ConvertVectorTimeDerivativeToOtherFrame(w_AB, DtB_w_AB, w_AB); 

---

*[drake/math/test/shift_time_derivative_test.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkIDlNy4_c-fFPSRzw:-KnkIDlNy4_c-fFPSRzx:b-wggvq4) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L44)):*
> ```cpp
> // that its velocity in frame C is zero, that is v_CHo = DC_p_CoHo = 0.
> // This unit test verifies we can compute the velocity v_WHo in the world frame
> // by shifting the time derivative as:
> ```

Change:   by shifting the time derivative as:  
to: as 

---

*[drake/math/test/shift_time_derivative_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkIf80UNDHXDj0cCGG:-KnkIf80UNDHXDj0cCGH:ba2u3ye) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L64)):*
> ```cpp
>   const Matrix3d R_WC = AngleAxisd(theta, Vector3d::UnitZ()).matrix();
>   // Horse position in the carousel frame.
>   const Vector3d& p_CoHo_C = horse_radius * Vector3d::UnitX();
> ```

const Vector3d&   to   const Vector3d

---

*[drake/math/test/shift_time_derivative_test.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkIp4pa1cHgrjrHIsP:-KnkIp4pa1cHgrjrHIsQ:b-efic8a) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L67)):*
> ```cpp
> 
>   // Re-express horse position in the world frame.
>   Vector3d p_CoHo_W = R_WC * p_CoHo_C;
> ```

BTW:  Use the const keyword consistently? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451)*

**Comment by amcastro-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/math/shift_time_derivative.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkEku2tUOMiFc11nvK:-KnksqaghXGzqsSJjqYx:b-k0tsdh) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L31)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Please consider the following for documentation:

/// Given ᴮd/dt(v) (the time derivative in frame B of an arbitrary 3D vector v)
/// and given ᴬωᴮ (frame B's angular velocity in another frame A), this method 
/// computes ᴬd/dt(v) (the time derivative in frame A of v) by:
///  ᴬd/dt(v) = ᴮd/dt(v) + ᴬωᴮ x v
///
/// This mathematical operation is known as the "Transport Theorem" or the
/// "Golden Rule for Vector Differentiation" [Mitiguy 2016, §7.3].  It was
/// discovered by Euler in 1758.  Its explicit notation with superscript 
/// frames was invented by Thomas Kane in 1950.  Its use as the defining
/// property of angular velocity was by Mitiguy in 1993.
/// 
/// In source code and comments, we use the following monogram notations:
/// `DtA_v = ᴬd/dt(v)` denotes the time derivative in frame A of the vector v.
/// `DtA_v_E = [ᴬd/dt(v)]_E` denotes the time derivative in frame A of vector v,
///  with the resulting new vector quantity expressed in a frame E.
///
/// In source code, this mathematical operation is performed with all vectors
/// expressed in the same frame E as   [ᴬd/dt(v)]ₑ = [ᴮd/dt(v)]ₑ + [ᴬωᴮ]ₑ x [v]ₑ
/// which in monogram notation is: <pre>
///   DtA_v_E = DtB_v_E + w_AB_E x v_E
/// </pre>
///
/// [Mitiguy 2016] Mitiguy, P., 2016. Advanced Dynamics & Motion Simulation.

</blockquote></details>

Beautiful, thanks. Copy pasted as-is. Next time you can mark this BTW for faster resolution.

---

*[drake/math/shift_time_derivative.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkF69NNbWI9HV7nubh:-Knkt6zxmy3HNrHMVZ6O:bandtyw) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L32)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Everywhere in the code, please use Dt (not D), e.g., DtB_v_Type
This is particularly helpful to disambiguate the operator Dt
from the possibility of a frame D.
</blockquote></details>

Make sure you update your browser before pressing the green button Paul! I had already introduced the `Dt` version many hours ago. PTAL.

---

*[drake/math/shift_time_derivative.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkFPvc3D2wmphDS6jQ:-Knktyon4ZxGbuM2G5Fp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L36)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

The "Shift" word is typically used for calculations involving a shift in location.
Please change ShiftTimeDerivative to 
ConvertVectorTimeDerivativeToOtherFrame.
</blockquote></details>

Done.

---

*[drake/math/shift_time_derivative.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkGKHS6h7lDDCTrsN7:-Knku0j1SIvnUk56ZjIt:b-1g76uf) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/shift_time_derivative.h#L40)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

DB_v_Type  to  DtB_v_Type
</blockquote></details>

Same update browser problem. Done

---

*[drake/math/test/shift_time_derivative_test.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkGcD6i25DmVw6nX89:-KnkuGUprf6Xj6PZWQn8:bqqexxa) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L17)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Use unicode for at least the derivative, e.g.,  
ᴬd/dt(w_AB) = ᴮd/dt(w_AB)   or 
ᴬd/dt( ᴬωᴮ) = ᴮd/dt( ᴬωᴮ)   or 
</blockquote></details>

This is a unit test Paul, I don't think we should be that picky for documentation here. But if it makes you happy, Done.

---

*[drake/math/test/shift_time_derivative_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkH-zirWP5DsBpJbbF:-KnkuOPRVcHgi2i-7f7O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L20)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

DtB_w_AB
</blockquote></details>

Done.

---

*[drake/math/test/shift_time_derivative_test.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkHAVxgjCSd9XriDVE:-KnkuUnzHD5WMsV8KrGg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L21)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

ConvertAngularVectorTimeDerivativeToOtherFrame.
</blockquote></details>

Done.

---

*[drake/math/test/shift_time_derivative_test.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkHDbCvRZ940o0hewq:-KnkuWHO4rK4TiSAsMv0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L22)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Change  DB_w_AB  to   DtB_w_AB.
Similarly for rest of code.
</blockquote></details>

Done.

---

*[drake/math/test/shift_time_derivative_test.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkHRRFuIONtKsUNjuE:-KnkuXSbaTPHjhxcB1x2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L24)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

  Vector3d DtA_w_AB = ConvertVectorTimeDerivativeToOtherFrame(w_AB, DtB_w_AB, w_AB); 
</blockquote></details>

Done.

---

*[drake/math/test/shift_time_derivative_test.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkIDlNy4_c-fFPSRzw:-Knkv-7iJzqVVS9YTp4H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L44)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Change:   by shifting the time derivative as:  
to: as 
</blockquote></details>

Done.

---

*[drake/math/test/shift_time_derivative_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkIf80UNDHXDj0cCGG:-KnkujnwSlphvqhfAxep:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L64)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

const Vector3d&   to   const Vector3d
</blockquote></details>

Done

---

*[drake/math/test/shift_time_derivative_test.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkIp4pa1cHgrjrHIsP:-KnkunnNV1aRiWrqL3t0:brbcbw5) ([raw file](https://github.com/robotlocomotion/drake/blob/c9cdd4361310c1003fe88189fe54fe4e0d668fdd/drake/math/test/shift_time_derivative_test.cc#L67)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

BTW:  Use the const keyword consistently? 
</blockquote></details>

BTW, ??? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451)*

**Comment by sherm1** [comment]
:lgtm: pending a few BTWs.

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[drake/math/convert_time_derivative.h, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-Knl-a84hllIHnnszMbh:-Knl-a84hllIHnnszMbi:b-txhye3) ([raw file](https://github.com/robotlocomotion/drake/blob/cfdc810d542caec4074e94bc1cc45dea14c6ec0d/drake/math/convert_time_derivative.h#L37)):*
> ```objc
>     const Eigen::MatrixBase<v_Type> &v_E,
>     const Eigen::MatrixBase<DtB_v_Type> &DtB_v_E,
>     const Eigen::MatrixBase<w_AB_Type> &w_AB_E) {
> ```

BTW misplaced `&`s

---

*[drake/math/test/shift_time_derivative_test.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-Knl-uTJIQxZeN5S1VHo:-Knl-uTJIQxZeN5S1VHp:b-ecg2d5) ([raw file](https://github.com/robotlocomotion/drake/blob/cfdc810d542caec4074e94bc1cc45dea14c6ec0d/drake/math/test/shift_time_derivative_test.cc#L1)):*
> ```cpp
> #include "drake/math/convert_time_derivative.h"
> ```

BTW this test file should be named `convert_time_derivative_test.cc`

---

*[drake/math/test/shift_time_derivative_test.cc, line 22 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-Knl0H3AoIj2TbpbQmxK:-Knl0H3AoIj2TbpbQmxL:b-txhye3) ([raw file](https://github.com/robotlocomotion/drake/blob/cfdc810d542caec4074e94bc1cc45dea14c6ec0d/drake/math/test/shift_time_derivative_test.cc#L22)):*
> ```cpp
> //   DtB_w_AB: Time derivative of w_AB in the B frame.
> void ConvertTimeDerivativeOfAngularVelocity(
>     const Vector3d &w_AB, const Vector3d &DtB_w_AB) {
> ```

BTW misplaced `&`s

---

*[drake/math/test/shift_time_derivative_test.cc, line 77 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-KnkzUVMk1zv9sqtUIV-:-KnkzUVMk1zv9sqtUIV0:b-57htcq) ([raw file](https://github.com/robotlocomotion/drake/blob/cfdc810d542caec4074e94bc1cc45dea14c6ec0d/drake/math/test/shift_time_derivative_test.cc#L77)):*
> ```cpp
> 
>   // Compute the expected value. Note that since rotation is only along the
>   // z-axis, v_WHo = v_CHo
> ```

BTW only the z component of velocity is the same in both frames? (comment seems wrong)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-:-Knl0obn5U4at7_NgHhK:b1favup)*

**Comment by mitiguy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6451#-:-KnlRt_-MRukopcHLWln:bnfp4nl)*

**Pull request merged**
