### PR TITLE
Adding Fetch Mobile Robot Example

### PR DESCRIPTION
**Pull request by rcory**
Adding simple passive (zero-torques) simulation of Fetch floating base robot, including urdf and associated mesh files.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6417)

### CODE REVIEW

**Comment by rcory** [comment]
@siyuanfeng-tri  for feature review please

---

Review status: 0 of 109 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-:-KnMG50i9uGdRsMt1QWy:bu2hxgh)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 5 of 10 files at r3.
Review status: 5 of 109 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Fetch/BUILD, line 13 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMKCi9AaTKncQ58nfX:-KnMKCi9AaTKncQ58nfY:bkemkyn) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/BUILD#L13)):*
> ```Python
> filegroup(
>     name = "models",
>     srcs = glob([
> ```

BTW, I am not sure if we want to make everything here. up to the platform reviewer. 

---

*[drake/examples/Fetch/fetch_common.h, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMM28NKWhNPu320miH:-KnMM28NKWhNPu320miI:bowzkj7) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/fetch_common.h#L10)):*
> ```objc
> /// 1: base y-translation
> /// 2: base z-translation
> /// 3: quaternion element q0
> ```

BTW, I never remember this correctly.. this is w? in drake convention? 

---

*[drake/examples/Fetch/fetch_common.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMKsebdI0YJMZQJYMF:-KnMKsecqJ731_LBEKdJ:bi6uymb) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/fetch_common.h#L53)):*
> ```objc
> /// @see drake::parsers::urdf::AddModelInstanceFromUrdfFile
> void CreateTreeFromFloatingModelAtPose(
>     const std::string& model_file_name, RigidBodyTreed* tree,
> ```

You could just change the param to Isometry3d to avoid the confusion. Otherwise you need to say what orientation is. 

---

*[drake/examples/Fetch/run_passive_fetch_demo.cc, line 77 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMMee5sUlPxn3KU6dX:-KnMMee5sUlPxn3KU6dY:bhvqrda) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/run_passive_fetch_demo.cc#L77)):*
> ```cpp
>   // See the @file docblock in fetch_common.h for joint index descriptions.
>   VectorBase<double>* x0 = fetch_context->get_mutable_continuous_state_vector();
>   x0->SetAtIndex(9, 0.1);  // torso lift joint [m]
> ```

It would be better if you do const int kTorsoLiftJointIdx = 9; 

---

*[drake/examples/Fetch/run_passive_fetch_demo.cc, line 85 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMMrRTnk7q9sDC9onq:-KnMMrRTnk7q9sDC9onr:b8mupzm) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/run_passive_fetch_demo.cc#L85)):*
> ```cpp
>   simulator.StepTo(FLAGS_simulation_sec);
> 
>   // Ensures the simulation was successful.
> ```

I would just rm this entire section. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-:-KnMN5bQQExMHpzuAbUe:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
One overall comment, can you move this to test folder? and turn it into a unit test? Something like simulate for 1 sec and just check for states at the end is not nan / inf? 

This is also missing all the cmake stuff.  

---

Review status: 5 of 109 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-:-KnMNPXw3Mak2_yw0gk1:bg3nza)*

**Comment by sammy-tri** [comment]
Review status: 5 of 109 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-Kn_jpkj9AcUAvmyVLDv:-Kn_jpkkr_dtyfKYzESf:b-2v9a46) (no related file):*
Are we sure we have the ability to distribute any of the model data?  A quick look at   https://github.com/fetchrobotics/fetch_ros/blob/indigo-devel/fetch_description/package.xml (where I believe the original data came from) makes it look iffy.  Also we probably shouldn't strip out the original package.xml or other copyright/attribution items.

I'm also not crazy about  checking another 36M of meshes into Drake, but I'll defer that matter until I'm sure we can do this at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/Fetch/fetch_common.h, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-Kndz6SxJKT55vEXq--l:-Kndz6SxJKT55vEXq--m:b-heceku) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/fetch_common.h#L21)):*
> ```objc
> /// 12: shoulder_pan_joint
> /// 13: shoulder_lift_joint
> /// 14: shoulder_lift_joint
> ```

get rid of this line. the idx should stop at 20 (21 dof). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417)*

**Comment by siyuanfeng-tri** [comment]
also this is missing the transmission stuff, so no actuators in the model. @rcory i will send you an email with the stuff. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-:-Kne2K6c6FtF2pOqG-M6:bhc2fxi)*

**Comment by avalenzu** [comment]
Review status: 5 of 109 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-Kn_jpkj9AcUAvmyVLDv:-Kne-_whY_YynkPwHeIu:b-ybrkf3) (no related file):*
Yeah, the "no-derivatives" part of the [license](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode) looks problematic, given that we've modified `fetch.urdf`:

> You do not have permission under this Public License to Share Adapted Material.

where

> Adapted Material means material subject to Copyright and Similar Rights that is derived from or based upon the Licensed Material and in which the Licensed Material is translated, altered, arranged, transformed, or otherwise modified

Not sure what the best course of action is here. Could we pull in `fetch_description` as an external? Or would the "non-commercial use only" clause (2.a.1.A) be a no-go even in an external?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417)*

**Comment by sherm1** [comment]
Review status: 5 of 109 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-Kn_jpkj9AcUAvmyVLDv:-KneEbADV33nC8EnQes2:b-4wzsx7) (no related file):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Yeah, the "no-derivatives" part of the [license](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode) looks problematic, given that we've modified `fetch.urdf`:

> You do not have permission under this Public License to Share Adapted Material.

where

> Adapted Material means material subject to Copyright and Similar Rights that is derived from or based upon the Licensed Material and in which the Licensed Material is translated, altered, arranged, transformed, or otherwise modified

Not sure what the best course of action is here. Could we pull in `fetch_description` as an external? Or would the "non-commercial use only" clause (2.a.1.A) be a no-go even in an external?
</blockquote></details>

"Non-commercial" seems like a fatal flaw. I think the best approach is to talk with the Fetch vendor. I believe Arshan is doing that (per @rcory). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417)*

**Comment by rcory** [comment]
Updated the urdf and added zero input source. I'll work on moving this to a test folder shortly. Also, I'm planning on removing the excess unused mesh files to reduce the size of this commit.

---

Review status: 2 of 109 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-Kn_jpkj9AcUAvmyVLDv:-KnaWmueTKqRvyho81UF:b-obx5sm) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

"Non-commercial" seems like a fatal flaw. I think the best approach is to talk with the Fetch vendor. I believe Arshan is doing that (per @rcory). 
</blockquote></details>

Yup, we're coordinating with Arshan who is reaching out to the vendor, asking if there's a way to get a license that is compatible with Drake's BSD-3 clause license. Until then, we'll hold off on pushing to master.

---

*[drake/examples/Fetch/BUILD, line 13 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMKCi9AaTKncQ58nfX:-Kn_6is2DQivHhQvt7tE:b-c4l8pl) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/BUILD#L13)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, I am not sure if we want to make everything here. up to the platform reviewer. 
</blockquote></details>

Will remove excess mesh files, e.g., .STL, .dae, etc. before merging.

---

*[drake/examples/Fetch/fetch_common.h, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMM28NKWhNPu320miH:-KnMPyjSYhvl9KXmKD-T:b-z1a7fp) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/fetch_common.h#L10)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, I never remember this correctly.. this is w? in drake convention? 
</blockquote></details>

looks like quaternion elements in Drake are [w, x, y, z]. Updated these here.

---

*[drake/examples/Fetch/fetch_common.h, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-Kndz6SxJKT55vEXq--l:-KneNHwaY6ki070aSRu2:bo6yqbh) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/fetch_common.h#L21)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

get rid of this line. the idx should stop at 20 (21 dof). 
</blockquote></details>

Done. I realized that I had repeated a joint. All fixed now.

---

*[drake/examples/Fetch/fetch_common.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMKsebdI0YJMZQJYMF:-KnaMzz7-avhjbOT_ZKr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/fetch_common.h#L53)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

You could just change the param to Isometry3d to avoid the confusion. Otherwise you need to say what orientation is. 
</blockquote></details>

Done.

---

*[drake/examples/Fetch/run_passive_fetch_demo.cc, line 77 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMMee5sUlPxn3KU6dX:-KnaRLJen0mIDj5Hhbn_:b-a39cof) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/run_passive_fetch_demo.cc#L77)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

It would be better if you do const int kTorsoLiftJointIdx = 9; 
</blockquote></details>

Added constexpr for available indices in fetch_common.h

---

*[drake/examples/Fetch/run_passive_fetch_demo.cc, line 85 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnMMrRTnk7q9sDC9onq:-KnaRojdghESbfzPK7p9:bofvq4a) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/run_passive_fetch_demo.cc#L85)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I would just rm this entire section. 
</blockquote></details>

I'm inclined to leave it in, if only to simply illustrate an example of getting state information back after a simulation (after all, this is an example application).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-:-KneM4KugdoUZA8a_HzT:b-79ndtj)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 4 of 54 files at r4.
Review status: 5 of 59 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Fetch/fetch_common.cc, line 52 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnenMA_8JEKR69djywP:-KnenMAaQriKx9JHp-MC:b-iaxm2x) ([raw file](https://github.com/robotlocomotion/drake/blob/4fce2202e77c1ffb35085bffb36867e00d2bac31/drake/examples/Fetch/fetch_common.cc#L52)):*
> ```cpp
> void CreateTreeFromFloatingModelAtPose(const std::string& model_file_name,
>                                        RigidBodyTreed* tree,
>                                        const Eigen::Isometry3d& orientation) {
> ```

i'd change this to pose. 

---

*[drake/examples/Fetch/fetch_common.h, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnemTemkjA2xndUdMYa:-KnemTenWGGrxjZbFh5K:b-2eaco6) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/fetch_common.h#L4)):*
> ```objc
> /// @file
> ///
> /// This file assumes a 21-degree of freedom Fetch mobile robot. Joints are
> ```

also I think this is technically a 20 dof robot. the quaterinon thing should probably just count as 6 dof.

---

*[drake/examples/Fetch/fetch_common.h, line 40 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnemscrxoV7gFUffBl-:-KnemscrxoV7gFUffBl0:b-l2rxld) ([raw file](https://github.com/robotlocomotion/drake/blob/4fce2202e77c1ffb35085bffb36867e00d2bac31/drake/examples/Fetch/fetch_common.h#L40)):*
> ```objc
> namespace Fetch {
> 
> constexpr int kNumDofs = 21;  // DOFs available for the Fetch robot
> ```

BTW you realize for velocity these indices (rWheel and below) are not correct. because quaternion has 1 more position than vel. 

---

*[drake/examples/Fetch/fetch_common.h, line 75 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnemnqcKxRn8iqbXkFa:-KnemnqcKxRn8iqbXkFb:b-sryz5j) ([raw file](https://github.com/robotlocomotion/drake/blob/4fce2202e77c1ffb35085bffb36867e00d2bac31/drake/examples/Fetch/fetch_common.h#L75)):*
> ```objc
> void CreateTreeFromFloatingModelAtPose(
>     const std::string& model_file_name, RigidBodyTreed* tree,
>     const Eigen::Isometry3d& orientation = Eigen::Isometry3d::Identity());
> ```

I'd rename this to pose. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417)*

**Comment by siyuanfeng-tri** [comment]
also i suggest disable the collision shape for link: torso_lift_link

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-:-Knfan3k43O5uKgqmOgN:b-bn9jps)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-Kn_jpkj9AcUAvmyVLDv:-KnfomYF2sm7nimePbUE:b-njsqhv) (no related file):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Yup, we're coordinating with Arshan who is reaching out to the vendor, asking if there's a way to get a license that is compatible with Drake's BSD-3 clause license. Until then, we'll hold off on pushing to master.
</blockquote></details>

I am going to mark this discussion as hard-blocking (i.e., not dismissable) until licensing is resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417)*

**Comment by rcory** [comment]
Review status: 3 of 59 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/Fetch/fetch_common.cc, line 52 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnenMA_8JEKR69djywP:-KnfqsJnSD8dCc0sJfA7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4fce2202e77c1ffb35085bffb36867e00d2bac31/drake/examples/Fetch/fetch_common.cc#L52)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i'd change this to pose. 
</blockquote></details>

Done.

---

*[drake/examples/Fetch/fetch_common.h, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnemTemkjA2xndUdMYa:-KnfscTAcHFsXwYpAjP8:b-br23io) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab3dffc1179962894b7a720275bcd1fb2f6b30/drake/examples/Fetch/fetch_common.h#L4)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

also I think this is technically a 20 dof robot. the quaterinon thing should probably just count as 6 dof.
</blockquote></details>

Done. And added additional comments here regarding the quaternion vector.

---

*[drake/examples/Fetch/fetch_common.h, line 40 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnemscrxoV7gFUffBl-:-KnjNLmYWx9BYAE8JMK8:b-yr8hup) ([raw file](https://github.com/robotlocomotion/drake/blob/4fce2202e77c1ffb35085bffb36867e00d2bac31/drake/examples/Fetch/fetch_common.h#L40)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW you realize for velocity these indices (rWheel and below) are not correct. because quaternion has 1 more position than vel. 
</blockquote></details>

Fixed the numbering, and also updated to comment block.

---

*[drake/examples/Fetch/fetch_common.h, line 75 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnemnqcKxRn8iqbXkFa:-KnjNIJucS92Or9J885r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4fce2202e77c1ffb35085bffb36867e00d2bac31/drake/examples/Fetch/fetch_common.h#L75)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I'd rename this to pose. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 6 files at r5.
Review status: 1 of 59 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Fetch/fetch_common.h, line 4 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnpJF-goLRUovOJo720:-KnpJF-goLRUovOJo721:b-kffr9j) ([raw file](https://github.com/robotlocomotion/drake/blob/7f77c1e33a5315608d3963c1ab1ff111f74e9122/drake/examples/Fetch/fetch_common.h#L4)):*
> ```objc
> /// @file
> ///
> /// This file assumes a 20-degree of freedom Fetch mobile robot. Joints are
> ```

BTW I would add an additional () saying that the fingers are modeled as 2 linear actuators, but they are mechanically coupled. 

---

*[drake/examples/Fetch/fetch_common.h, line 13 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-KnpIvSoxA2cUdPeobvw:-KnpIvSp0gf_yjjFEhh-:btrc0so) ([raw file](https://github.com/robotlocomotion/drake/blob/7f77c1e33a5315608d3963c1ab1ff111f74e9122/drake/examples/Fetch/fetch_common.h#L13)):*
> ```objc
> /// the position and velocity indices differ.
> /// ---- Position indexing ---          ---- Velocity Indexing ----
> /// 0: base x-translation               0: base x-translation
> ```

hehe, this is actually not true... If you print out the velocity_names, the floating base is wx wy wz xd yd zd.... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417)*

**Comment by jwnimmer-tri** [comment]
This PR hasn't been touched in a while.  If it's no longer active, would it be worth closing until work resumes?

**Comment by rcory** [comment]
Let me follow up with Arshan today. Most likely will end up closing this out, but I'll confirm.

---

Review status: 1 of 59 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-:-Kx8mHPo-OyZdZFANK5E:b-6a9d2v)*

**Comment by rcory** [comment]
Update: We are currently exchanging emails with the vendor. Will post back with the resolution soon (hopefully).

---

Review status: 1 of 59 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6417#-:-KxAjnOwofC9Oyv-U7mS:b-xwmdn0)*

**Comment by jwnimmer-tri** [comment]
@rcory Are there any recent updates to this (notes from the vendor about the licensing, perhaps)?  Should this PR still be open?

**Comment by rcory** [comment]
Closing, for now. If the need for this comes back up I can re-open.

**Pull request closed without merging**
