### PR TITLE
Remove system1 deadwood

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #3960.  The parts of System 1.0 that are still valuable are just the RBS (multibody) stuff, so move the useful files into that subtree, stop installing their headers, and `git rm` the rest.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4553)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/system1/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4553#-KZPLlpiQ4tbftGgmjWS:-KZPLlpiQ4tbftGgmjWT:bpu32t8) ([raw file](https://github.com/robotlocomotion/drake/blob/ccefbbc6134428812aaff57e5496786b1e78948f/drake/system1/CMakeLists.txt#L1)):*
> ```CMake
> drake_install_headers(
> ```

FYI The `drake/system1/test` unit tests were no longer being compiled or run on master (oops?), but rather than resurrect them back into the build, I `rm`d them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4553)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for all review, please.

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4553#-:-KZS0uGacsVj35q5il8b:b-7ewwmf)*

**Comment by david-german-tri** [comment]
:lgtm: :shipit:

---

Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4553#-:-KZS1gMRngv1_fYURh9l:b-h79mc8)*

**Pull request merged**
