### PR TITLE
Mesh filename publishing

### PR DESCRIPTION
**Pull request by patmarion**
This addresses most of the discussion in #1636.

Note, this depends on the ability to check whether a path is relative or absolute.  The spruce third party library that drake uses for filename manipulation does not provide this capability.

This pull request implements a check for relative paths that assumes posix paths, *it does not work on Windows* (so maybe don't merge this).

Perhaps for issue #1718 we will find a better filesystem manipulation library.

### CODE REVIEW

**Comment by patmarion** [comment]
[copy and pasted comment from #1721]

In this pull request, mesh filenames are always published with absolute paths. Previously, mesh filenames were published as relative paths or absolute paths depending on whether the urdf command line argument was given as a relative or absolute path.

This pull request also converts prius.urdf to use package:// syntax. This makes lcm logs with DRAKE_VIEWER_LOAD messages portable between computers and verifies that drake-visualizer is handling package:// correctly.

Note, drake-visualizer imports pydrake in order to call pydrake.getDrakePath().  It uses the drake path to recursively search for packages (dirs with package.xml files).

**Comment by patmarion** [comment]
I think this pull request will have errors until #1718 is resolved.  should I leave open or close?

**Comment by RussTedrake** [comment]
it will have issues on windows, but should be fine everywhere else. correct?

On Wed, Feb 24, 2016 at 9:31 AM, Pat Marion <notifications@github.com> wrote:
I think this pull request will have errors until #1718 [https://github.com/RobotLocomotion/drake/issues/1718] is resolved. should I leave open or close?

—
Reply to this email directly or view it on GitHub
[https://github.com/RobotLocomotion/drake/pull/1736#issuecomment-188278344] .[https://github.com/notifications/beacon/AGJNNCpcSMI0Usjqukfz73xGVDtIl-NLks5pnbZRgaJpZM4HgDNC.gif]

**Comment by patmarion** [comment]
Actually, it looks like drake006 has a failing test when loading prius.urdf in matlab.  I guess the package:// stuff only works when parsing in c++ using RigidBodyTreeURDF because that c++ class is able to resolve package urls using the package map.

Here is the error message from the test:


testing /private/tmp/drake-1736-31487/drake/examples/Cars/prius/prius.urdf
Error using rospack (line 51)
couldn't find ROS package prius.
 ROS_ROOT=
 ROS_PACKAGE_PATH=


Error in RigidBodyGeometry.parseURDFNode (line 149)
              filename=[rospack(package),filename];

Error in RigidBodyManipulator/addRobotFromURDF>parseVisual (line 640)
         geometry = RigidBodyGeometry.parseURDFNode(geomnode,xyz,rpy,model,body.robotnum,options);

Error in RigidBodyManipulator/addRobotFromURDF>parseLink (line 182)
    body = parseVisual(body,node.getElementsByTagName('visual').item(visualItem),model,options);

Error in RigidBodyManipulator/addRobotFromURDF>parseRobot (line 95)
  model = parseLink(model,robotnum,links.item(i),options);

Error in RigidBodyManipulator/addRobotFromURDF (line 55)
model = parseRobot(model,robot,xyz,rpy,options);

Error in RigidBodyManipulator (line 75)
          obj = addRobotFromURDF(obj,filename,zeros(3,1),zeros(3,1),options);

Error in compareParsers (line 17)
    r = RigidBodyManipulator(urdffile,struct('floating','rpy'));

Error in fevalPackageSafe (line 21)
  feval(f);

**Comment by iamwolf** [comment]
@patmarion From what I see "packages" in the example folder that are not part of the ROS path are hard-coded in rospack.m (cf. https://github.com/RobotLocomotion/drake/blob/294bb83d3eb4061b6c12f24b6cdca0e4ba8f27cf/drake/util/rospack.m#L28-L33) - so would this PR require two lines to that file that "prius" is in examples/Cars/?

**Comment by RussTedrake** [comment]
@iamwolf -- wow.  thanks.  

I didn't actually realize that those lines had snuck into rospack.m .  I don't think they should be there at all.  examples/Atlas has a package.xml, which should be sufficient.  Valkyrie does not (didn't check IRB).  The better solution should be to add stub package.xml files to those directories, and remove the lines @iamwolf highlighted.

**Comment by RussTedrake** [comment]
and @patmarion -- it seems like the package searching in rospack.m must not be working as expected.  that seems like a bug.  it's probably the reason that the lines discussed above appeared, but the right solution is to fix the search is rospack.m.

**Pull request closed without merging**
