### PR TITLE
[doc] Add new pydrake header, footer, and style customizations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16993.

This incorporates css and html boilerplate as provided by our website contractors.

Local preview is available as:

```
bazel run //doc/pydrake:build -- --serve
```

---

Header:

image

Footer:

image

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17012)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both reviews, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17012)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[doc/BUILD.bazel, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17012#-N0CcL91CsIfgm_PehEI:-N0CcL91CsIfgm_PehEJ:bbevq8i) ([raw file](https://github.com/robotlocomotion/drake/blob/344c6a1b70802baa56a49f4cf01d665bbe0d414c/doc/BUILD.bazel#L25)):*
> ```Starlark
>     name = "defs",
>     srcs = ["defs.py"],
>     data = [
> ```

FYI These same changes are in #16960 already -- both pydrake and doxygen_cxx will use this feature.  Whichever PR merges first will win; the other one will need to be rebased.

**Review by EricCousineau-TRI — COMMENTED** [review]
Working: I did not review the source of `*.html` or `*.css` files beyond naive styling (below). Assuming it is only important to preview and "click around".

Previewing locally...

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17012#-:-N0Ck6-fAkVonagzyuPJ:b-58z97d)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17012#-N0Cjai7CeSVXsKued4n:-N0Cjai88GH1RiuZqW0p:bjbh1vh) (no related file):*
nit (naive styling) Whitespace is not always spaces; line wrap not at 80 characters.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17012)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17012#-N0Cjai7CeSVXsKued4n:-N0ClV22AxjcaI7lsqiG:b-68l5y5) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (naive styling) Whitespace is not always spaces; line wrap not at 80 characters.
</blockquote></details>

You're right, thanks!  I forgot to de-tabify the css (and one html nit) and clean up the roll-of-the-dice indentation habits.  I got distracted when fixing their broken jinja templates.

I'll work on that now.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: per local preview - just clicked through pydrake docs and confirmed that there weren't any (easily noticeable) bugs / artifacts. Nice!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17012#-:-N0CmFepE2gbuSzIeTeM:b-q0wq6l)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17012)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17012#-N0Cjai7CeSVXsKued4n:-N0CmwUV8DE-D2i95Dq0:b62ww8k) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

You're right, thanks!  I forgot to de-tabify the css (and one html nit) and clean up the roll-of-the-dice indentation habits.  I got distracted when fixing their broken jinja templates.

I'll work on that now.
</blockquote></details>

Done for the whitespace (I hope).  PTAL.

I'm not sure that wrapping to <80 is terribly useful here?

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17012)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17012#-N0Cjai7CeSVXsKued4n:-N0Cq_NpAA-PlhIHlo9E:b-or7jsb) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done for the whitespace (I hope).  PTAL.

I'm not sure that wrapping to <80 is terribly useful here?
</blockquote></details>

OK Thanks!

And no, <80 isn't terribly useful, just that >=80 makes this code even more an outlier.

---

**Pull request merged**
