### PR TITLE
solvers: Add MathematicalProgram::CheckSatisfied

### PR DESCRIPTION
**Pull request by RussTedrake**
This is very useful for writing unit tests on constraints, and parallels the existing EvalBinding methods.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15268)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15268#-:-MdRuN2e1okoSIdt7LeA:b-81zjv5)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15268#-MdRu9nfBC9ThX0StviB:-MdRu9nfBC9ThX0StviC:b-77z9v5) ([raw file](https://github.com/robotlocomotion/drake/blob/6b48a199d59b66c4e3cbe061e6a08676d77a3860/bindings/pydrake/solvers/mathematicalprogram_py.cc#L98)):*
> ```cpp
>   if (std::is_base_of_v<Constraint, C> && !std::is_same_v<C, Constraint>) {
>     py::implicitly_convertible<B, Binding<Constraint>>();
>   }
> ```

@ericcousineau-tri -- I thought this was what I needed, but I'm still getting
```
TypeError: CheckSatisfied(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, binding: drake::solvers::Binding<drake::solvers::Constraint>, prog_var_vals: numpy.ndarray[numpy.float64[m, 1]], tol: float = 1e-06) -> bool
    2. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, bindings: List[drake::solvers::Binding<drake::solvers::Constraint>], prog_var_vals: numpy.ndarray[numpy.float64[m, 1]], tol: float = 1e-06) -> bool

Invoked with: <pydrake.solvers.mathematicalprogram.MathematicalProgram object at 0x7f0f09fdb1b0>; kwargs: binding=<pydrake.solvers.mathematicalprogram.Binding_LinearConstraint object at 0x7f0f09fd69b0>, prog_var_vals=array([ 1.,  1.]), tol=1e-06

```
Might you be able to take a quick look?

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15268)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[solvers/mathematical_program.h, line 2995 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15268#-MdSumaDDjOREpk89vv0:-MdSumaDDjOREpk89vv1:b-rjpdve) ([raw file](https://github.com/robotlocomotion/drake/blob/6b48a199d59b66c4e3cbe061e6a08676d77a3860/solvers/mathematical_program.h#L2995)):*
> ```objc
>    * @pydrake_mkdoc_identifier{vector}
>    */
>   bool CheckSatisfied(const std::vector<Binding<Constraint>>& bindings,
> ```

Would it be helpful to also return the constraints that are not satisfied?
___
*[solvers/mathematical_program.cc, line 1218 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15268#-MdSufke0Z2gWohBrXR0:-MdSufke0Z2gWohBrXR1:bz5jkd2) ([raw file](https://github.com/robotlocomotion/drake/blob/6b48a199d59b66c4e3cbe061e6a08676d77a3860/solvers/mathematical_program.cc#L1218)):*
> ```cpp
>     const Binding<Constraint>& binding,
>     const Eigen::Ref<const Eigen::VectorXd>& prog_var_vals, double tol) const {
>   Eigen::VectorXd vals = GetBindingVariableValues(binding, prog_var_vals);
> ```

nit, const Eigen::VectorXd

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15268)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15268#-MdRu9nfBC9ThX0StviB:-MdTGzVB4LmPTZGZuABS:bdmk2c) ([raw file](https://github.com/robotlocomotion/drake/blob/6b48a199d59b66c4e3cbe061e6a08676d77a3860/bindings/pydrake/solvers/mathematicalprogram_py.cc#L98)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@ericcousineau-tri -- I thought this was what I needed, but I'm still getting
```
TypeError: CheckSatisfied(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, binding: drake::solvers::Binding<drake::solvers::Constraint>, prog_var_vals: numpy.ndarray[numpy.float64[m, 1]], tol: float = 1e-06) -> bool
    2. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, bindings: List[drake::solvers::Binding<drake::solvers::Constraint>], prog_var_vals: numpy.ndarray[numpy.float64[m, 1]], tol: float = 1e-06) -> bool

Invoked with: <pydrake.solvers.mathematicalprogram.MathematicalProgram object at 0x7f0f09fdb1b0>; kwargs: binding=<pydrake.solvers.mathematicalprogram.Binding_LinearConstraint object at 0x7f0f09fd69b0>, prog_var_vals=array([ 1.,  1.]), tol=1e-06

```
Might you be able to take a quick look?
</blockquote></details>

Took a quick look and tried out a few things; I unfortunately don't have a quick solution:
https://github.com/EricCousineau-TRI/drake/commit/79a260e5b7

Hypotheses:
- Some form of PEBKAC that we missed. With print statements, though, it seems like you're doing the right things? (order of registration, etc.)
- `py::implicitly_convertible<>` is broken on our fork for this workflow
- `py::implicitly_convertible<>` is broken on master for this workflow.

My guess is it'd take 1hr to fully diagnose, 1hr to fix (upstream or fork).

**Review by RussTedrake — COMMENTED** [review]
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15268#-:-MdTUTJ3E8z0zr_AAcPH:bz1t39v)* status: 2 unresolved discussions, LGTM missing from assignees hongkai-dai,sammy-tri(platform) (waiting on @EricCousineau-TRI, @hongkai-dai, and @sammy-tri)

___
*[solvers/mathematical_program.h, line 2995 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15268#-MdSumaDDjOREpk89vv0:-MdTCAU05IBEwyTKyQ3O:b-qivbex) ([raw file](https://github.com/robotlocomotion/drake/blob/6b48a199d59b66c4e3cbe061e6a08676d77a3860/solvers/mathematical_program.h#L2995)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Would it be helpful to also return the constraints that are not satisfied?
</blockquote></details>

I thought about that.  But it's so trivial for the users to iterate through the loop themselves, and this is really only a sugar method for checking a batch at once... so I prefer the cleaner return type.
___
*[solvers/mathematical_program.cc, line 1218 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15268#-MdSufke0Z2gWohBrXR0:-MdTCo5KAH3-_0cgFYfN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6b48a199d59b66c4e3cbe061e6a08676d77a3860/solvers/mathematical_program.cc#L1218)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit, const Eigen::VectorXd
</blockquote></details>

Done.
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15268#-MdRu9nfBC9ThX0StviB:-MdTUOU38bwkhms_j_Vp:b-izxdiw) ([raw file](https://github.com/robotlocomotion/drake/blob/6b48a199d59b66c4e3cbe061e6a08676d77a3860/bindings/pydrake/solvers/mathematicalprogram_py.cc#L98)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Took a quick look and tried out a few things; I unfortunately don't have a quick solution:
https://github.com/EricCousineau-TRI/drake/commit/79a260e5b7

Hypotheses:
- Some form of PEBKAC that we missed. With print statements, though, it seems like you're doing the right things? (order of registration, etc.)
- `py::implicitly_convertible<>` is broken on our fork for this workflow
- `py::implicitly_convertible<>` is broken on master for this workflow.

My guess is it'd take 1hr to fully diagnose, 1hr to fix (upstream or fork).
</blockquote></details>

opened https://github.com/RobotLocomotion/drake/issues/15272 and removed the python bindings from this PR.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15268#-:-MdTWQTv2HYl54f151ec:bg7igkv)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[solvers/mathematical_program.h, line 2995 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15268#-MdSumaDDjOREpk89vv0:-MdTWGn_2-K7B1UQDhVg:bg2j5h2) ([raw file](https://github.com/robotlocomotion/drake/blob/6b48a199d59b66c4e3cbe061e6a08676d77a3860/solvers/mathematical_program.h#L2995)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I thought about that.  But it's so trivial for the users to iterate through the loop themselves, and this is really only a sugar method for checking a batch at once... so I prefer the cleaner return type.
</blockquote></details>

Makes sense, thanks!

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15268#-:-MdU7ku4DhRT_lWCzkwZ:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
