### PR TITLE
Major clean-up of method names

### PR DESCRIPTION
**Pull request by ggould-tri**
This PR corrects method and in some cases field naming in a number of classes that I work with frequently, as well as the formatting and syntax of nearby comments.

The change is automatic (done with clion and perlpie) for the most part.  Human intervention was limited to fixing comments near the code I touched.

The change is NOT COMPREHENSIVE.  It leaves major nearby defects untouched, and does not correct names in files other than the ones in solver and util that caught my attention.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2971)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@jwnimmer-tri as the on-call platform reviewer
+@rpoyner-tri for feature review (the only other person in the office...)

---

Review status: 0 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-:-KNnKKc_PRID4lTtyHlX:1997186448)*

**Comment by jwnimmer-tri** [comment]
I am going to assume that the DNR label still being here is a mistake, and will begin my review soon.

**Comment by jwnimmer-tri** [comment]
Tip for any other reviewers: learn to love the `n` and `x` keys in reviewable.io.

Also: I breezed through the `cc` files a bit -- I focused mostly on the `h` files.

---

Reviewed 9 of 32 files at r1, 13 of 17 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/MobyLCP.cpp, line 1311 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-KNnU8guHea4aDU2RlaS:-KNnU8guHea4aDU2RlaT:-130982150) ([raw file](https://github.com/robotlocomotion/drake/blob/d8c9c3fee383efb58554a85ba4554dcc79789944/drake/solvers/MobyLCP.cpp#L1311)):*
> ```cpp
> 
> }  // namespace solvers
> }  // namespace drake
> ```

btw This file is too long and eyebleed to review.  I'll trust you did it all correctly.

---

*[drake/solvers/MosekWrapper.h, line 31 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-KNnUamCto74JQgt4qaw:-KNnUamCto74JQgt4qax:234083220) ([raw file](https://github.com/robotlocomotion/drake/blob/d8c9c3fee383efb58554a85ba4554dcc79789944/drake/solvers/MosekWrapper.h#L31)):*
> ```objc
>  * problem using the mosek solver.
>  *
>  * MosekLP solves a linear program when given a correctly formatted program.
> ```

Is this `MosekLP` rename (from `MosekWrapper`) in the comment intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-:-KNnUJFIQXjjesydF1So:-1299363210)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-:-KNnVa6nkLrQVMjRbHUr:1417088721)*

**Comment by ggould-tri** [comment]
Yeah, DNR is easy to lose track of.  I needed it while I was sussing out automation-only errors (of which, more than a few) but didn't see it from the reviewable interface when getting ready to submit.

And yes, the n/p/x commands are awesome.  Expect to use them more if I get around to namespace rectification this afternoon :)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/MobyLCP.cpp, line 1311 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-KNnU8guHea4aDU2RlaS:-KNqrKi8BkAwSRjTOLG4:-1811899518) ([raw file](https://github.com/robotlocomotion/drake/blob/d8c9c3fee383efb58554a85ba4554dcc79789944/drake/solvers/MobyLCP.cpp#L1311)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> btw This file is too long and eyebleed to review.  I'll trust you did it all correctly.
</details>
I reviewed it manually after I discovered clion broke all of our `Foo&

---

*[drake/solvers/MosekWrapper.h, line 31 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-KNnUamCto74JQgt4qaw:-KNrFfHKZS0qahMu3Qlr:-715352107) ([raw file](https://github.com/robotlocomotion/drake/blob/d8c9c3fee383efb58554a85ba4554dcc79789944/drake/solvers/MosekWrapper.h#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Is this `MosekLP` rename (from `MosekWrapper`) in the comment intentional?
</details>
Nope, it was a merge error on my part.  Fixing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-:-KNqr0Sz5zDmL4ySYmNX:1687272466)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2971)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 9 of 32 files at r1, 13 of 17 files at r2, 10 of 11 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/solvers/MobyLCP.cpp, line 136 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-KNrITj3VpkSqSRTbXdg:-KNrITj3VpkSqSRTbXdh:-452105677) ([raw file](https://github.com/robotlocomotion/drake/blob/988ded05c2063c099c79159076122887f21add83/drake/solvers/MobyLCP.cpp#L136)):*
> ```cpp
>   // Assert that the available LCPs cover the program and no two LCPs cover
>   // the same variable.
>   for (size_t i = 0; i < prog.num_vars(); i++) {
> ```

xNnnn

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2971#-:-KNrJkI0nbuYX46Ak9fn:1417088721)*

**Pull request merged**
