### PR TITLE
[fem] FemState supports cloning

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17686)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17686#-:-N8_zMS2BvXZj5O0448M:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 
+@sammy-tri for feature review please.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17686#-:-N8d9s_R6PXbapWqNu4q:b-75hkf0)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`multibody/fem/fem_state.cc` line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17686#-N8d8Xfx8q1XjnEeV4Pr:-N8d8Xfx8q1XjnEeV4Ps:b-8scy6x) ([raw file](https://github.com/robotlocomotion/drake/blob/a340e711fe50d85db1f0ed99421d61706fa30d7b/multibody/fem/fem_state.cc#L63)):*
> ```cpp
>   if (owned_context_ != nullptr) {
>     auto clone = std::make_unique<FemState<T>>(this->system_);
>     clone->owned_context_ = this->owned_context_;
> ```

fyi, this will trigger a `Context::Clone()`. Not sure if that is important for your application (placing this in an abstract value in the cache?) but maybe consider using `clone->owned_context_->SetTimeStateAndParametersFrom(*this->owned_context_)`?
___
*[`multibody/fem/fem_state.cc` line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17686#-N8d90KqBTNPqtimYTDP:-N8d90KqBTNPqtimYTDQ:b-u601xr) ([raw file](https://github.com/robotlocomotion/drake/blob/a340e711fe50d85db1f0ed99421d61706fa30d7b/multibody/fem/fem_state.cc#L67)):*
> ```cpp
>   }
>   DRAKE_DEMAND(context_ != nullptr);
>   return std::make_unique<FemState<T>>(this->system_, this->context_);
> ```

nit, probably worth documenting in the header that for a "shared" version of `FemState`, the clone will make reference to original data held by the source `FemState`, and thus care must be taken with the lifetime of objects.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17686)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri and @sammy-tri)

___
*[`multibody/fem/fem_state.cc` line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17686#-N8d8Xfx8q1XjnEeV4Pr:-N8dihSn9nQ2UidHyJKR:b6zqgfs) ([raw file](https://github.com/robotlocomotion/drake/blob/a340e711fe50d85db1f0ed99421d61706fa30d7b/multibody/fem/fem_state.cc#L63)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

fyi, this will trigger a `Context::Clone()`. Not sure if that is important for your application (placing this in an abstract value in the cache?) but maybe consider using `clone->owned_context_->SetTimeStateAndParametersFrom(*this->owned_context_)`?
</blockquote></details>

Done. I forgot I could do that, thanks.
___
*[`multibody/fem/fem_state.cc` line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17686#-N8d90KqBTNPqtimYTDP:-N8djhxZ2F8PjMEacqm5:bc7ui5m) ([raw file](https://github.com/robotlocomotion/drake/blob/a340e711fe50d85db1f0ed99421d61706fa30d7b/multibody/fem/fem_state.cc#L67)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, probably worth documenting in the header that for a "shared" version of `FemState`, the clone will make reference to original data held by the source `FemState`, and thus care must be taken with the lifetime of objects.
</blockquote></details>

Done, I added a note to refer to the class doc.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17686)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17686#-:-N8ds8DE2nxkFUuNeD3L:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Pull request merged**
