### PR TITLE
mkdoc: Work around a problematic deprecation_example header dep

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
When collecting the list of package headers, in the case of the deprecation example (which has no package library) we were ending up with two different copies of the header being passed to mkdoc:

```
  bazel-out/k8-opt/bin/bindings/pydrake/common/_virtual_includes/deprecation_example_class/drake/bindings/pydrake/common/test/deprecation_example/example_class.h
  bindings/pydrake/common/test/deprecation_example/example_class.h
```

The first one is the path we want -- the one used while compiling, and thus the one with a matching `-I` flag.  The second one is a correct dependency, but not used for compiling, so does not have any matching `-I` flag, so breaks mkdoc.

Here, we customize our skylark header collection to ignore the second file.

(Note that #15066 and #15068 are also required for Bazel 4.1 builds to succeed.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15069)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both reviews, please.

I've confirmed that with both Bazel 4.0.0 and Bazel 4.1.0, the contents of the generated `documentation_pybind.h` are identical between master vs this patch.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: 

'tis quite a wiggy behavior!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15069#-:-MaUDQ6uDj5jsBZuAH_N:b-934yq1)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tools/skylark/pybind.bzl, line 340 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15069#-MaUD083-OTu8jDxW3bA:-MaUD083-OTu8jDxW3bB:b-tck9e2) ([raw file](https://github.com/robotlocomotion/drake/blob/4637024555096a997cc188aafeca506abb62ba13/tools/skylark/pybind.bzl#L340)):*
> ```Starlark
> 
>             # Remove headers that are duplicated as both a virtual include path
>             # and a source path.  We'll to use the virtual include path, since
> ```

nit grammar missing verb btw "We'll ? to use"

Perhaps the `to` is redundant?

**Comment by EricCousineau-TRI** [comment]
___
*[tools/skylark/pybind.bzl, line 340 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15069#-MaUD083-OTu8jDxW3bA:-MaUExmhACzXTeAiL3Ph:b-1on7ka) ([raw file](https://github.com/robotlocomotion/drake/blob/4637024555096a997cc188aafeca506abb62ba13/tools/skylark/pybind.bzl#L340)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit grammar missing verb btw "We'll ? to use"

Perhaps the `to` is redundant?
</blockquote></details>

Demoting this to BTW.

**Comment by jwnimmer-tri** [comment]
Best guess, https://github.com/bazelbuild/bazel/commit/e3b7e17b05f13ff183a4d7efec8ec797f3f5eaa3 is what bit us.

**Pull request merged**
