### PR TITLE
[solvers] Increase tolerance for create_constraint_test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Necessary for macOS Ventura on arm64.

Towards #18327.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19423)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for both reviews, please.  \CC @hongkai-dai FYI

Note that the CI failure in mac-arm-ventura-clang-bazel-experimental-release doesn't indicate problem with this PR. The test case changed in this PR is passing in that build. It shows that one other test case is still failing as we work to spin up Ventura.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19423#-:-NVz2VHm8DIyOmzVHMHs:bg7igkv)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please (-@RussTedrake).

**Pull request merged**
