### PR TITLE
[wheel] Enable Bazel caching across rebuilds

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
(Resurrected from https://github.com/RobotLocomotion/pip-drake/pull/13.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16085)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware for review, please.

I was thinking to land #16084 before this one, but on second thought I suppose it doesn't really matter which order they happen.

In my local testing, the bazel cache ends up sharing most of the Drake build across the py36 and py37 builds; the parts that do get rebuilt fresh during py37 are the pybind11 bindings where we're actually including the CPython headers, so they do need to be different.  It seems to incorporate new Drake upstream changes fine as well.

**Review by mwoehlke-kitware — COMMENTED** [review]
Well... possibly RIP podman :finnadie:.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16085#-:-ModzPBA4jjXpy4A89oY:b-6bcdfi)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/wheel/dev/Dockerfile, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16085#-ModyYcJ81lb5cFNEQvv:-ModyYcJ81lb5cFNEQvw:b51jtuk) ([raw file](https://github.com/robotlocomotion/drake/blob/ae235df76c419783f544fcf8a5e894be7fcd47d3/tools/wheel/dev/Dockerfile#L51)):*
> ```Dockerfile
> 
> RUN --mount=type=ssh \
>     --mount=target=/var/cache/bazel,type=cache \
> ```

Just to make it prettier w.r.t. the previous line:
```
    --mount=type=cache,target=/var/cache/bazel \
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16085)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[tools/wheel/dev/Dockerfile, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16085#-ModyYcJ81lb5cFNEQvv:-Moe_gWg5smW6A2YvgS1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ae235df76c419783f544fcf8a5e894be7fcd47d3/tools/wheel/dev/Dockerfile#L51)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Just to make it prettier w.r.t. the previous line:
```
    --mount=type=cache,target=/var/cache/bazel \
```
</blockquote></details>

Done.

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16085#-:-MooevT_-y41I9BGF2dC:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Pull request merged**
