### PR TITLE
pybind11: Install headers and CMake config

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This reverts commit be30e9d026f4e42e9cfbc70b6ddcc8ee46ae1754, reversing
changes made to 82bf3c8a02678f553c746bdbbe0f8e5a345841b7.

Per discussion with @stonier and @jamiesnape, and confirming with @clalancette, this seems like a better route for easier downstream consumption, (especially since we may expose some developer APIs for leveraging `pydrake`'s `pybind` utility components, and these utilities are required for binding Drake-derived components).

Relates #7856

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8264)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
+@ggould-tri for platform review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-:-L6w4YgHbTwrHi_GfN4M:b-zd9orj)*

**Comment by ggould-tri** [comment]
:lgtm: Yup, looks like a revert to me.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8264#-:-L6w5c9x0Lv4VOauE0QZ:bbs5jai)*

**Comment by jwnimmer-tri** [comment]
I'd advocate that the subject line of commit messages should be phrased in the positive, as in "Install pybind11 headers and cmake config" or similar.  The detail that its a revert should appear in the elaborative paragraphs to follow.

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8264)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/pybind11/package-create-cps.py, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-L6wGbbdYxXGlSvNkUAM:-L6wGbbdYxXGlSvNkUAN:b-6htw6w) ([raw file](https://github.com/robotlocomotion/drake/blob/de96343cebc91bbfa0cb064b07ad5997aa1a30ee/tools/workspace/pybind11/package-create-cps.py#L18)):*
> ```Python
>     "module": {
>       "Type": "interface",
>       "Includes": ["@prefix@/include"],
> ```

We ensure each package's headers have unique prefixes now. Change this to `"@prefix@/include/pybind11"`

---

*[tools/workspace/pybind11/package.BUILD.bazel, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-L6wGhFVYjrSnmC1Xu4p:-L6wGhFVYjrSnmC1Xu4q:byv0tui) ([raw file](https://github.com/robotlocomotion/drake/blob/de96343cebc91bbfa0cb064b07ad5997aa1a30ee/tools/workspace/pybind11/package.BUILD.bazel#L69)):*
> ```
> )
> 
> install(
> ```

Install headers to `include/pybind11`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264)*

**Comment by EricCousineau-TRI** [comment]
> I'd advocate that the subject line of commit messages should be phrased in the positive, as in "Install pybind11 headers and cmake config" or similar. The detail that its a revert should appear in the elaborative paragraphs to follow.

Done.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/pybind11/package-create-cps.py, line 18 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8264#-L6wGbbdYxXGlSvNkUAM:-L6yAp241mhmHGA9nshY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de96343cebc91bbfa0cb064b07ad5997aa1a30ee/tools/workspace/pybind11/package-create-cps.py#L18)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We ensure each package's headers have unique prefixes now. Change this to `"@prefix@/include/pybind11"`
</blockquote></details>

Done.

---

*[tools/workspace/pybind11/package.BUILD.bazel, line 69 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8264#-L6wGhFVYjrSnmC1Xu4p:-L6yApSP4klb6c3xtZ2g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de96343cebc91bbfa0cb064b07ad5997aa1a30ee/tools/workspace/pybind11/package.BUILD.bazel#L69)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Install headers to `include/pybind11`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8264#-:-L6yAgYbEDn9iePQB8FC:bk8se6r)*

**Comment by EricCousineau-TRI** [comment]
I've submitted https://github.com/robotlocomotion/drake-shambhala/pull/98 as a motivating example for this.

For simplicity, I've added `pybind11` to the modules that `drake` brings in; the alternative is to require the user to specify that themselves, but I'd prefer not to make that required.

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8264)*

**Comment by jamiesnape** [comment]
> For simplicity, I've added pybind11 to the modules that drake brings in; the alternative is to require the user to specify that themselves, but I'd prefer not to make that required.

Actually, you haven't done so correctly, and even if you did I would not consider it acceptable.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/libdrake/drake.cps, line 46 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8264#-L7-pRng-qJnODkvumE6:-L7-pRng-qJnODkvumE7:b-tmqoms) ([raw file](https://github.com/robotlocomotion/drake/blob/f655e37d37d4899ec631270ef788ed7f3ba515b4/tools/install/libdrake/drake.cps#L46)):*
> ```delphi
>       "Hints": ["@prefix@/lib/cmake/pybind11"],
>       "X-CMake-Find-Args": ["CONFIG"]
>     },
> ```

Remove per my comment above.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8264#-:-L7-pPPE2L3x-2YC0TQ2:b5e563x)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/pybind11/package-create-cps.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-L7-tejj9vy4DkjHzFf1:-L7-tejj9vy4DkjHzFf2:bq7vi94) ([raw file](https://github.com/robotlocomotion/drake/blob/f655e37d37d4899ec631270ef788ed7f3ba515b4/tools/workspace/pybind11/package-create-cps.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

BTW `#!/usr/bin/env python` to save me having to fix this later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264)*

**Comment by EricCousineau-TRI** [comment]
> Actually, you haven't done so correctly, and even if you did I would not consider it acceptable.

Understood; can I ask for constructive advice on how to do it correctly? (could you mention this either here or in `drake-shambhala`?)
Specifically, what should the correct workflow be for including `pybind11`? Does the user have to manually specify `-Dpybind11_DIR`, or should they do something like `set(pybind11_DIR ...)` according to `drake_DIR`?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-:-L708FbcR6oHwv0M5uv6:b-7v0s8g)*

**Comment by jamiesnape** [comment]
In Shambhala, would say remove `drake_DIR` and use `CMAKE_PREFIX_PATH` instead (the value of the variable would be slightly different). Then that covers you for both. Alternatively, you can derive `pybind11_DIR` from `drake_DIR` (I think it is `${drake_DIR}/../pybind11`).

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-:-L709NyriMS_WmmSta1H:b-2m3bmg)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/pybind11/package-create-cps.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-L7-tejj9vy4DkjHzFf1:-L74wBHdUElI-VMxUiml:b-7oruxv) ([raw file](https://github.com/robotlocomotion/drake/blob/f655e37d37d4899ec631270ef788ed7f3ba515b4/tools/workspace/pybind11/package-create-cps.py#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW `#!/usr/bin/env python` to save me having to fix this later.
</blockquote></details>

(not a BTW anyone now that the linter has been switched on)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/pybind11/package-create-cps.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-L7-tejj9vy4DkjHzFf1:-L7R6ICtD8Pb5Uf4SQlu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f655e37d37d4899ec631270ef788ed7f3ba515b4/tools/workspace/pybind11/package-create-cps.py#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

(not a BTW anyone now that the linter has been switched on)
</blockquote></details>

Done.

---

*[tools/install/libdrake/drake.cps, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-L7-pRng-qJnODkvumE6:-L7R6LE-zC9nWKXBHH-G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f655e37d37d4899ec631270ef788ed7f3ba515b4/tools/install/libdrake/drake.cps#L46)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Remove per my comment above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264)*

**Comment by jamiesnape** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pybind11/package-create-cps.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-L7-tejj9vy4DkjHzFf1:-L7R8X3DTEQjv9Vu-enb:blhaqtp) ([raw file](https://github.com/robotlocomotion/drake/blob/f655e37d37d4899ec631270ef788ed7f3ba515b4/tools/workspace/pybind11/package-create-cps.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Such is the ever-changing fun with Homebrew, unfortunately now this needs to be `#!/usr/bin/env python2`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-:-L7R95uybaCsGvEFqwe-:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pybind11/package-create-cps.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8264#-L7-tejj9vy4DkjHzFf1:-L7S29nZ7WKwAD4zaB6i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f655e37d37d4899ec631270ef788ed7f3ba515b4/tools/workspace/pybind11/package-create-cps.py#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Such is the ever-changing fun with Homebrew, unfortunately now this needs to be `#!/usr/bin/env python2`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8264)*

**Pull request merged**
