### PR TITLE
workspace: Upgrade tinyobjloader to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15112)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15112)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15112#-Mb7J6S79t6mnatvDe-k:-Mb7J6S79t6mnatvDe-l:b8njvnk) (no related file):*
The selected commit didn't pass the upstream's CI. PTAL.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15112)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15112#-Mb7J6S79t6mnatvDe-k:-Mb7Jk8k-9U6WipUs-Nu:b7peig5) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

The selected commit didn't pass the upstream's CI. PTAL.
</blockquote></details>

The VC++ installation failed during the Windows flavor builds.  Doesn't seem like a blocker for Drake?

---

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15112#-:-Mb7P2IX5yZ6B86vRuAN:bnfp4nl)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

**Pull request merged**
