### PR TITLE
Fixed a bug where the Z-offset of prius.sdf was 2X what it should be.

### PR DESCRIPTION
**Pull request by liangfok**
Closes https://github.com/RobotLocomotion/drake/issues/2237

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2240)

### CODE REVIEW

**Comment by liangfok** [comment]
CI infrastructure appears to have tipped over in [build 1165](https://drake-jenkins.csail.mit.edu/job/experimental/1165/). I'll go ahead and retry after updating with the latest on master.

**Comment by jamiesnape** [comment]
If there is a merge or master or if there is a force push to the PR branch between the Jenkins build being requested and the build starting, then the hash of the merged commit will change and so the build will fail.

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/simulateLCM.cpp, line 114 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2240#-KGnBggXtqagP_kEB_ss:-KGnBggXtqagP_kEB_st:1495549529) ([raw file](https://github.com/robotlocomotion/drake/blob/6389f4f9c863749bc6d494f436e71a2d8973bc3d/drake/examples/Cars/simulateLCM.cpp#L114)):*
This number is specific to a particular URDF, right?  If so, can we check for that particular filename?

---

*[drake/examples/Cars/simulateLCM.cpp, line 114 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2240#-KGnBtKD_N8ip3rVLFAr:-KGnBtKEXVkDPJGEXnqu:642387221) ([raw file](https://github.com/robotlocomotion/drake/blob/6389f4f9c863749bc6d494f436e71a2d8973bc3d/drake/examples/Cars/simulateLCM.cpp#L114)):*
This PR is clearly an improvement, but in the long term, would it better to bake this offset into every link in the URDF?

---

*[drake/examples/Cars/simulateLCM.cpp, line 133 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2240#-KGnBL5sj5k5q67spT7n:-KGnBL5sj5k5q67spT7o:-1833813394) ([raw file](https://github.com/robotlocomotion/drake/blob/6389f4f9c863749bc6d494f436e71a2d8973bc3d/drake/examples/Cars/simulateLCM.cpp#L133)):*
sentence out of date - delete?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2240)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/simulateLCM.cpp, line 114 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2240#-KGnBtKD_N8ip3rVLFAr:-KGnJjJmCY0Kx9ED5E8k:1413384554) ([raw file](https://github.com/robotlocomotion/drake/blob/6389f4f9c863749bc6d494f436e71a2d8973bc3d/drake/examples/Cars/simulateLCM.cpp#L114)):*
Unfortunately, URDF requires that the root link of a model be at location (0, 0, 0) of the model's coordinate frame. Thus, there is currently no way to specify that the `chassis_floor` of the prius.urdf is at Z=0.378326m.

However, once https://github.com/RobotLocomotion/drake/pull/2171 is merged, we can add a world link into prius.urdf and properly offset its `chassis_floor` link. I've created issue https://github.com/RobotLocomotion/drake/issues/2247 to track this change.

---

*[drake/examples/Cars/simulateLCM.cpp, line 114 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2240#-KGnBggXtqagP_kEB_ss:-KGo3OyRaIF5pASfhynz:1502586973) ([raw file](https://github.com/robotlocomotion/drake/blob/6389f4f9c863749bc6d494f436e71a2d8973bc3d/drake/examples/Cars/simulateLCM.cpp#L114)):*
Good point. I've modified it to check for the particular file.

---

*[drake/examples/Cars/simulateLCM.cpp, line 133 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2240#-KGnBL5sj5k5q67spT7n:-KGo63bHvPOOmDPuh5Mt:-795674652) ([raw file](https://github.com/robotlocomotion/drake/blob/6389f4f9c863749bc6d494f436e71a2d8973bc3d/drake/examples/Cars/simulateLCM.cpp#L133)):*
Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2240)*

**Comment by liangfok** [comment]
[CI Build 1181](https://drake-jenkins.csail.mit.edu/job/experimental/1181/) passed. Thus, this PR is ready for review / merge.

**Comment by liangfok** [comment]
Oh wait. I just noticed a surrious `#include`. Will remove it now.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2240#-:-KGqUSVhHKhAfCNwO3Eb:-101392545)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2240#-:-KGqvaYzhRVfbg9GmMzN:1417088721)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2240)*

**Pull request merged**
