### PR TITLE
Meldis reload considers glTF content

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Relates #21194

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21297)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: fix) 
+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21297#-:-NvDH9O-EE-dSkEW87WE:b-t3cmrb)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature but note that I didn't test locally.  That's probably fine, the unit test should be good enough.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21297#-:-NvDRAve-vAc8BrPSKY8:b-kwdhrw)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 353 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21297#-NvDQt52-YxUwaXJz1Lh:-NvDQt52-YxUwaXJz1Li:bcyh0i0) ([raw file](https://github.com/RobotLocomotion/drake/blob/829b944d8627865d0922dca453f2e7b0cf9204aa/bindings/pydrake/visualization/test/meldis_test.py#L353)):*
> ```Python
> 
>         # Valid glTF file, but with no external files; the glTF's contents
>         # else matter.
> ```

nit typo "else"?
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 362 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21297#-NvDQzCE2MK3fZHfkm1s:-NvDQzCE2MK3fZHfkm1t:b4gtc9x) ([raw file](https://github.com/RobotLocomotion/drake/blob/829b944d8627865d0922dca453f2e7b0cf9204aa/bindings/pydrake/visualization/test/meldis_test.py#L362)):*
> ```Python
>         # Valid glTF file reference an external image.
>         with open(gltf_filename, "w") as f:
>             f.write(f'{{"images" :[{{"uri": "{png_filename}"}}]}}')
> ```

BTW Possibly this (and below) would read more clearly using `json.encode` instead of f-strings?  Not sure.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21297)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 362 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21297#-NvDQzCE2MK3fZHfkm1s:-NvDa_Wl5izazOZ0troZ:b-7cue5a) ([raw file](https://github.com/RobotLocomotion/drake/blob/829b944d8627865d0922dca453f2e7b0cf9204aa/bindings/pydrake/visualization/test/meldis_test.py#L362)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Possibly this (and below) would read more clearly using `json.encode` instead of f-strings?  Not sure.
</blockquote></details>

Definitely

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21297)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (also not tested locally)

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21297#-:-NvDjSpm19BSJSqhn3LX:b-d7mr65)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
