### PR TITLE
Evaluate polynomial (with affine coefficients) on a batch of indeterminates

### LINKED ISSUE #17333: Add constraints on evaluating a polynomial for a batch of data
I find that often I need to impose the constraint
```
lb(i) <= p(xⁱ) <= ub(i)
```
where xⁱ is the i'th sample for a batch of data, and p(x) is a polynomial whose coefficients are affine expressions of our decision variables.

I could loop through each xⁱ and impose this as a linear constraint, by evaluating p(xⁱ) as a symbolic expression. But since we already provide evaluating monomials for a batch of data, I think it would be faster to impose this constraint in a batch, which would involve less symbolic evaluation.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #17333

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

+@jwnimmer-tri for reviewing the build file change, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357#-:-N44vOm98p_fVm8_3q0n:bq9xy49)* status: LGTM missing from assignees aykut-tri,jwnimmer-tri(platform), missing label for release notes (waiting on @aykut-tri and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM on the build changes.

> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357#-:-N47vxU78BTVQKoZbZmX:bldakxy)* status: 2 unresolved discussions, LGTM missing from assignees aykut-tri,jwnimmer-tri(platform), missing label for release notes (waiting on @aykut-tri, @hongkai-dai, and @jwnimmer-tri)

___
*[`common/BUILD.bazel` line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N47viPcDheNisYfU_K-:-N47viPdEY5O8XymEF8R:b-wmdx5z) ([raw file](https://github.com/robotlocomotion/drake/blob/69c3e49a0bc054f85aef9483f3276752dfef5cc8/common/BUILD.bazel#L210)):*
> ```Starlark
>         "symbolic_codegen.h",
>         "symbolic_decompose.cc",
>         "symbolic_decompose.h",
> ```

This header is a public header file (not part of symbolic.h), so it should be in `hdrs = ...` not `srcs`.
___
*[`common/BUILD.bazel` line 263 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N47vRSQDy_uHFLTucys:-N47vRSQDy_uHFLTucyt:bx086mu) ([raw file](https://github.com/robotlocomotion/drake/blob/69c3e49a0bc054f85aef9483f3276752dfef5cc8/common/BUILD.bazel#L263)):*
> ```Starlark
> )
> 
> drake_cc_library(
> ```

nit This library looks unusual now -- a name with nothing but dependencies, no source code?  We need some kind of a comment here explaining / justifying this choice.

The TODO that I'd previously suggested would be one way to resolve this.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)* status: 1 unresolved discussion, LGTM missing from assignees aykut-tri,jwnimmer-tri(platform), missing label for release notes (waiting on @aykut-tri and @jwnimmer-tri)

___
*[`common/BUILD.bazel` line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N47viPcDheNisYfU_K-:-N4894jR4HssQrVRyy4g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69c3e49a0bc054f85aef9483f3276752dfef5cc8/common/BUILD.bazel#L210)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This header is a public header file (not part of symbolic.h), so it should be in `hdrs = ...` not `srcs`.
</blockquote></details>

Done.
___
*[`common/BUILD.bazel` line 263 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N47vRSQDy_uHFLTucys:-N489r-B-T8xO2Hnc9-H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69c3e49a0bc054f85aef9483f3276752dfef5cc8/common/BUILD.bazel#L263)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This library looks unusual now -- a name with nothing but dependencies, no source code?  We need some kind of a comment here explaining / justifying this choice.

The TODO that I'd previously suggested would be one way to resolve this.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)* status: LGTM missing from assignees aykut-tri,jwnimmer-tri(platform), missing label for release notes (waiting on @aykut-tri and @jwnimmer-tri)

**Review by aykut-tri — COMMENTED** [review]
:lgtm_strong: only a couple of suggestions

+@ericcousineau-tri for platform review please, thanks!

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357#-:-N49ZpIK7lFPTdUgLKyq:b-nmczxu)* status: LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`common/symbolic_polynomial.h` line 227 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N49R66i9tub2XRzRieL:-N49R66i9tub2XRzRieM:br03tx1) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7204455e0cb022c8d380d7a7c633ab1060d773/common/symbolic_polynomial.h#L227)):*
> ```objc
>   /// indeterminates_values.rows() == indeterminates.rows().
>   /// @param[out] A The evaluation at @p indeterminates_values.col(i) is the
>   /// affine expression A.row(i) * decision_variables + b(i).
> ```

BTW, in these parameter descriptions, there are three repetitions of the following statement. You may consider rewording, perhaps by moving this into the top description (if that is still visible in the documentation).



_Suggestion:_
```objc
  /// The evaluation at @p indeterminates_values.col(i) is the
  /// affine expression A.row(i) * decision_variables + b(i).
```
___
*[`common/symbolic_polynomial.cc` line 617 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N49W2iBB980sE9wjSE6:-N49W2iC3X0XYfaYZsHk:b-8n910i) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7204455e0cb022c8d380d7a7c633ab1060d773/common/symbolic_polynomial.cc#L617)):*
> ```cpp
>   b->setZero();
>   // Each term in the polynomial is m(x) * c, where m(x) is the
>   // monomial and c is the coefficient of the monomial. For each coefficient
> ```

BTW, consider rephrasing:



_Suggestion:_
```cpp
  // For each coefficient c, write it as c=a_coeff * decision_variables + b_coeff, hence this
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)* status: LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`common/symbolic_polynomial.h` line 227 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N49R66i9tub2XRzRieL:-N49damF0bn-RBmP6Sha:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7204455e0cb022c8d380d7a7c633ab1060d773/common/symbolic_polynomial.h#L227)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

BTW, in these parameter descriptions, there are three repetitions of the following statement. You may consider rewording, perhaps by moving this into the top description (if that is still visible in the documentation).
</blockquote></details>

Done.
___
*[`common/symbolic_polynomial.cc` line 617 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N49W2iBB980sE9wjSE6:-N49e3l51g76v06HZr6W:b-qdwyym) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7204455e0cb022c8d380d7a7c633ab1060d773/common/symbolic_polynomial.cc#L617)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

BTW, consider rephrasing:
</blockquote></details>

Sorry, could you explain why doing this rephrasing? Thanks!

**Review by aykut-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)* status: LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @aykut-tri and @EricCousineau-TRI)

___
*[`common/symbolic_polynomial.cc` line 617 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N49W2iBB980sE9wjSE6:-N49fBbiEpUw7tHayK8k:b-jhgq2c) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7204455e0cb022c8d380d7a7c633ab1060d773/common/symbolic_polynomial.cc#L617)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry, could you explain why doing this rephrasing? Thanks!
</blockquote></details>

Sorry for the confusion I accidentally sent the above comment with a suggestion instead of a quote. So, I meant replacing the above phrase by something like: "Since c=a_coeff * decision_variables + b_coeff, this term can be written as...". But I'm not sure which version is better :sweat_smile: Perhaps, the platform reviewer could have a suggestion here, or you can simply disregard this comment :smile:

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)* status: LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @aykut-tri and @EricCousineau-TRI)

___
*[`common/symbolic_polynomial.cc` line 617 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N49W2iBB980sE9wjSE6:-N49iKqK551S21GO-qZ6:b-sr3tin) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7204455e0cb022c8d380d7a7c633ab1060d773/common/symbolic_polynomial.cc#L617)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Sorry for the confusion I accidentally sent the above comment with a suggestion instead of a quote. So, I meant replacing the above phrase by something like: "Since c=a_coeff * decision_variables + b_coeff, this term can be written as...". But I'm not sure which version is better :sweat_smile: Perhaps, the platform reviewer could have a suggestion here, or you can simply disregard this comment :smile: 
</blockquote></details>

Do you mean to replace the block
```
  // Each term in the polynomial is m(x) * c, where m(x) is the
  // monomial and c is the coefficient of the monomial. For each coefficient
  // c, write it as c=a_coeff * decision_variables + b_coeff, hence this
  // term can be written as m(x)*a_coeff * decision_variables + m(x)*b_coeff.
```
with
```
Since c=a_coeff * decision_variables + b_coeff, this term can be written as m(x)*a_coeff * decision_variables + m(x)*b_coeff
```
?

IMHO this is less clear, as the reader might not know what `c` and `m(x)` means.

**Review by aykut-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`common/symbolic_polynomial.cc` line 617 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N49W2iBB980sE9wjSE6:-N4CyIs_8A3298eEAM0g:b-w3c5no) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7204455e0cb022c8d380d7a7c633ab1060d773/common/symbolic_polynomial.cc#L617)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do you mean to replace the block
```
  // Each term in the polynomial is m(x) * c, where m(x) is the
  // monomial and c is the coefficient of the monomial. For each coefficient
  // c, write it as c=a_coeff * decision_variables + b_coeff, hence this
  // term can be written as m(x)*a_coeff * decision_variables + m(x)*b_coeff.
```
with
```
Since c=a_coeff * decision_variables + b_coeff, this term can be written as m(x)*a_coeff * decision_variables + m(x)*b_coeff
```
?

IMHO this is less clear, as the reader might not know what `c` and `m(x)` means.
</blockquote></details>

Sorry for causing further confusion. I just had a minor concern about the part: "For each coefficient c, write it as c=a_coeff * decision_variables + b_coeff, hence ...".

So, I meant something like the following but it's completely up to you, I think either way is fine.

```
  // Each term in the polynomial is m(x) * c, where m(x) is the
  // monomial and c is the coefficient of the monomial. Since each coefficient
  // c is given by c=a_coeff * decision_variables + b_coeff, m(x) * c can
  // be written as m(x)*a_coeff * decision_variables + m(x)*b_coeff.
```

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with blocking comment on usage of `W`, as well as some other small nits. Nice!

> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357#-:-N4EHDX8AeLAOAkWG_S0:b840ca1)* status: 9 unresolved discussions (waiting on @hongkai-dai)

___
*[`common/symbolic_polynomial.h` line 211 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EFve55pKGmWf77Tj4:-N4EFve55pKGmWf77Tj5:b-s96iyv) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L211)):*
> ```objc
>   /// substituting indeterminates(i) in this polynomial with
>   /// indeterminates_values(i, j) for all i.
>   /// @throw error if any coefficient in this polynomial is not a constant.
> ```

nit (pre-existing) Unclear what "error" is here. Consider `std::exception`, consistent with above usages.

(Bringing this up because of nit below)
___
*[`common/symbolic_polynomial.h` line 216 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EFdZI7alfO-02_wTW:-N4EFdZJ4TU6j1tEulcp:blv8mew) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L216)):*
> ```objc
>       const Eigen::Ref<const Eigen::MatrixXd>& indeterminates_values) const;
> 
>   /// For a polynomial whose coefficients are affine expressions of decision
> ```

nit I liked your usage of the term "batch" in the issue and in above function.

Is it possible to briefly mention the term here?
___
*[`common/symbolic_polynomial.h` line 217 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EEPfK65hdGZ3V5lHG:-N4EEPfK65hdGZ3V5lHH:b-4es2jm) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L217)):*
> ```objc
> 
>   /// For a polynomial whose coefficients are affine expressions of decision
>   /// variables, we evaluate this polynomial on a batch of indeterminates
> ```

nit grammar "indeterminates values" => "intdeterminate values" ?
___
*[`common/symbolic_polynomial.h` line 226 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EFHEY-PyrckOmxUKt:-N4EFHEY-PyrckOmxUKu:b-7fmb43) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L226)):*
> ```objc
>   /// @param[in] indeterminates Must include all this->indeterminates()
>   /// @param[in] indeterminates_values Each column of `indeterminates_values`
>   /// stores one specific value of `indeterminates`.
> ```

nit For clarity, consider stating something like "A matrix representing a batch of values. Each column ..., meaning that each row implies a single instance of values."
___
*[`common/symbolic_polynomial.h` line 227 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EEzLp-DAsQgB0_nRS:-N4EEzLp-DAsQgB0_nRT:b-n04tam) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L227)):*
> ```objc
>   /// @param[in] indeterminates_values Each column of `indeterminates_values`
>   /// stores one specific value of `indeterminates`.
>   /// indeterminates_values.rows() == indeterminates.rows().
> ```

nit This expression makes sense, but its inclusion is a bit abrupt.

Consider saying ``value of `intdeterminates`, where ...` or stating this as `@pre` below.
___
*[`common/symbolic_polynomial.h` line 232 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EG3yA4Vr13_4qkhAo:-N4EG3yA4Vr13_4qkhAp:b-4gyb4r) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L232)):*
> ```objc
>   /// results.
>   /// @param[out] b The constant terms in the evaluation results.
>   /// @throw exception if the coefficients of this polynomial is not an affine
> ```

nit Usage of "exception" is inconsistent with `std::exception` above. Consider rewriting as `std::exception`
___
*[`common/symbolic_polynomial.h` line 236 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EEjii9uDbNlSCoSV2:-N4EEjii9uDbNlSCoSV3:b-n70xj8) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L236)):*
> ```objc
>   /// (2+sin(a)) * x² + 1 (where a is a decision variable and x is
>   /// indeterminate) doesn't have affine expression as its coefficient 2+sin(a).
>   void EvaluateWAffineCoefficients(
> ```

Unclear what `W` is here. Not sure if `WAffine` is special term, or you mean `WithAffine`.

Is it possible to clarify? Consider renaming to `WithAffine` if that is accurate.
___
*[`common/symbolic_polynomial.cc` line 618 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EGPLw2z06mEBkkwhI:-N4EGPLw2z06mEBkkwhJ:btbch6u) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.cc#L618)):*
> ```cpp
>   // Each term in the polynomial is m(x) * c, where m(x) is the
>   // monomial and c is the coefficient of the monomial. For each coefficient
>   // c, write it as c=a_coeff * decision_variables + b_coeff, hence this
> ```

nit Consider putting space around `=`.
___
*[`common/test/symbolic_polynomial_test.cc` line 989 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EGuFh4sW5CmF7HLLb:-N4EGuFh4sW5CmF7HLLc:b-44vvro) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/test/symbolic_polynomial_test.cc#L989)):*
> ```cpp
>   Eigen::Matrix<double, 2, 3> indeterminates_values;
>   // clang-format off
>     indeterminates_values << 1, 2, 3,
> ```

nit Unclear why this section of code has extra leading indentation.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`common/symbolic_polynomial.h` line 211 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EFve55pKGmWf77Tj4:-N4F0rvQ0h0JF9Jzw9ic:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L211)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (pre-existing) Unclear what "error" is here. Consider `std::exception`, consistent with above usages.

(Bringing this up because of nit below)
</blockquote></details>

Done.
___
*[`common/symbolic_polynomial.h` line 216 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EFdZI7alfO-02_wTW:-N4F1HhpC0xyVnWI7DMj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L216)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I liked your usage of the term "batch" in the issue and in above function.

Is it possible to briefly mention the term here?
</blockquote></details>

Done.
___
*[`common/symbolic_polynomial.h` line 217 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EEPfK65hdGZ3V5lHG:-N4F1L5j5kQe7-MXQ5k_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L217)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit grammar "indeterminates values" => "intdeterminate values" ?
</blockquote></details>

Done.
___
*[`common/symbolic_polynomial.h` line 226 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EFHEY-PyrckOmxUKt:-N4F1b179JT33Yj6loNS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L226)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For clarity, consider stating something like "A matrix representing a batch of values. Each column ..., meaning that each row implies a single instance of values."
</blockquote></details>

Done.
___
*[`common/symbolic_polynomial.h` line 227 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EEzLp-DAsQgB0_nRS:-N4F1tJ7DNWklg5iYrUu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L227)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This expression makes sense, but its inclusion is a bit abrupt.

Consider saying ``value of `intdeterminates`, where ...` or stating this as `@pre` below.
</blockquote></details>

Done.
___
*[`common/symbolic_polynomial.h` line 236 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EEjii9uDbNlSCoSV2:-N4F29P2Bg7og6Af5cZL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.h#L236)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unclear what `W` is here. Not sure if `WAffine` is special term, or you mean `WithAffine`.

Is it possible to clarify? Consider renaming to `WithAffine` if that is accurate.
</blockquote></details>

Done.
___
*[`common/symbolic_polynomial.cc` line 617 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N49W2iBB980sE9wjSE6:-N4F2h-W5ojJsu99xOLI:b-dc31ly) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7204455e0cb022c8d380d7a7c633ab1060d773/common/symbolic_polynomial.cc#L617)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Sorry for causing further confusion. I just had a minor concern about the part: "For each coefficient c, write it as c=a_coeff * decision_variables + b_coeff, hence ...".

So, I meant something like the following but it's completely up to you, I think either way is fine.

```
  // Each term in the polynomial is m(x) * c, where m(x) is the
  // monomial and c is the coefficient of the monomial. Since each coefficient
  // c is given by c=a_coeff * decision_variables + b_coeff, m(x) * c can
  // be written as m(x)*a_coeff * decision_variables + m(x)*b_coeff.
```
</blockquote></details>

Done.

I see, sorry I misunderstood it.

I reworded it a bit, change `c is given by` to `c can be  written as`. At the line of the documentation, c is not given  by a_coeff * decision_variables + b_coeff yet, since a_coeff and b_coeff haven't been assigned to the correct values yet.
___
*[`common/symbolic_polynomial.cc` line 618 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EGPLw2z06mEBkkwhI:-N4F36c8C-FvmoAm5LMp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/symbolic_polynomial.cc#L618)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider putting space around `=`.
</blockquote></details>

Done.
___
*[`common/test/symbolic_polynomial_test.cc` line 989 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4EGuFh4sW5CmF7HLLb:-N4F3BQf74tA0puaGpO5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b31997d0ef2b54052fe1bcb016186cc9980a2d45/common/test/symbolic_polynomial_test.cc#L989)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why this section of code has extra leading indentation.
</blockquote></details>

Done.

**Review by aykut-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)* status: 1 unresolved discussion (waiting on @aykut-tri, @EricCousineau-TRI, and @jwnimmer-tri)

___
*[`common/symbolic_polynomial.cc` line 617 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N49W2iBB980sE9wjSE6:-N4SFOgADFSUA-W4c0XS:b7ztyq0) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7204455e0cb022c8d380d7a7c633ab1060d773/common/symbolic_polynomial.cc#L617)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.

I see, sorry I misunderstood it.

I reworded it a bit, change `c is given by` to `c can be  written as`. At the line of the documentation, c is not given  by a_coeff * decision_variables + b_coeff yet, since a_coeff and b_coeff haven't been assigned to the correct values yet.
</blockquote></details>

Gotcha, thanks! One last thing: please remove either "since" at the beginning or "hence" at the second part.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17357)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,EricCousineau-TRI(platform) (waiting on @hongkai-dai)

___
*[`bindings/pydrake/test/symbolic_test.py` line 1564 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17357#-N4Sek2N9hSWoE5I3BUi:-N4Sek2O-DM_EaOs9hgc:b-ewe05p) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4fe9ced3107b990af4f2ddede293ac38a532a0/bindings/pydrake/test/symbolic_test.py#L1564)):*
BTW Per PEP8, prefer line break using parenthesis
https://peps.python.org/pep-0008/#maximum-line-length

> The preferred way of wrapping long lines is by using Python’s implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

**Pull request merged**
