### PR TITLE
Remove package_drake.sh

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is not part of our release workflow.  Right now, the `drake-ci` listfiles have shell commands to create the release tarballs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7157)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7157#-:-KvS3C3TC0n8mmLmvdj-:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per rotation, please.

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/README.md, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7157#-KvSYCIr_DTu47ZhVUhe:-KvSYCIsIksgmSrr4Tj1:b-7we3yc) ([raw file](https://github.com/robotlocomotion/drake/blob/eca66153352a9c0c7d5b738ba360d048f83b2153/tools/README.md#L13)):*
> ```Markdown
> 
> `drake.cps` is the Common Package Specification for Drake, that provides the
> necessary information for Drake to be consumed by other projects. Right now it
> ```

BTW minor nit Consistency, single space after period (two spaces below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7157)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: (with minor nit)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7157#-:-KvSYOnFSPS2QKZqsaYa:bwkqi70)*

**Comment by jwnimmer-tri** [comment]
Using override-merge to skip CI for README-only whitespace change.

**Pull request merged**
