### PR TITLE
[Multilane] Connection and Endpoint classes refactor.

### PR DESCRIPTION
**Pull request by agalbachicar**
As part of issue #7194 and #4934, and in order to do the necessary refactors to the `Builder` and `Connection` classes, this PR is made. The following list is a summary of the changes:

- `Connection`, `Endpoint` related classes, `ArcOffset` and `Group` are moved to `connection.cc` and `connection.h` files. This change will tidy up `builder.h` and `builder.cc` files.
- `operator<<` is provided for `Endpoint` related classes. It is needed for the following item.
- GTest comparisons for `Endpoint` related classes are provided.
- Test cases for `Connection`, `Endpoint` related classes and `ArcOffset` are provided.

A follow up PR will include methods under _Lane-to-lane version_ and _Reference-line version_ sections. Those are listed in this [comment](https://github.com/RobotLocomotion/drake/issues/7194#issuecomment-334848934)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7325)

### CODE REVIEW

**Comment by agalbachicar** [comment]
+@maddog-tri for feature review please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxEYp665K2c1jCUXyB0:b-5klkw7)*

**Comment by agalbachicar** [comment]
I made an update to the tests because end Endpoints of the Connections were wrong. However, no assertion was triggered and I noticed that there is some inconsistency in `Connection` class documentation. It states:

"Constructs a line/arc-segment connection joining `start` to `end`."

I think that we must enforce that when constructing the `Connection`s. As it was already there from monolane's code, I can differ this to next PR. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxJVrQsBnu5Z293HqXn:bmzyc1)*

**Comment by agalbachicar** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please.

**Comment by maddog-tri** [comment]
Review pass complete.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/multilane/connection.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxJZmZlzk1PiGH3C6r7:-KxJZmZmbzCzoaqFCGM2:b-qmz0af) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7776f350b1177f34b8cf605f6dd855117e46ae/drake/automotive/maliput/multilane/connection.cc#L4)):*
> ```cpp
> 
> #include "drake/automotive/maliput/multilane/arc_road_curve.h"
> #include "drake/automotive/maliput/multilane/line_road_curve.h"
> ```

Unused headers?  (arc_road_curve.h, line_road_curve.h)

---

*[drake/automotive/maliput/multilane/connection.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxJZjIqmFXme3zmHN3S:-KxJZjIrZ7Y2L3rDCqhG:b78yh65) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7776f350b1177f34b8cf605f6dd855117e46ae/drake/automotive/maliput/multilane/connection.h#L10)):*
> ```objc
> #include <vector>
> 
> #include "drake/automotive/maliput/multilane/road_curve.h"
> ```

Unused header?

---

*[drake/automotive/maliput/multilane/test/multilane_connection_test.cc, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxPI-_qNPy4facHAvv-:-KxPI-_rSyXCgdZX55fE:b-vjuy2c) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7776f350b1177f34b8cf605f6dd855117e46ae/drake/automotive/maliput/multilane/test/multilane_connection_test.cc#L88)):*
> ```cpp
>   const double kZeroTolerance{0.};
>   const double kLeftShoulder{1.};
>   const double kRightShoulder{1.};
> ```

Should test with asymmetric shoulder values....

---

*[drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxJaEGNenNPwGHZGOJ9:-KxJaEGNenNPwGHZGOJA:b-rjnsnv) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7776f350b1177f34b8cf605f6dd855117e46ae/drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L11)):*
> ```objc
> namespace multilane {
> namespace test {
> ```

BTW:  (META)  In this PR, these methods are only ever called with `kZeroTolerance == 0.`, so this comment is moot in the scope of this PR.  However, in general, these methods need multiple tolerance parameters because of mixed units in the `Endpoint*` types.
  * x, y, and z are lengths --- corresponding to `linear_tolerance()`.
  * `heading` and `theta` are radians, like `angular_tolerance()`.
  * `z_dot` is, uh, the tangent of an angle....
  * `theta_dot` is something else....

Maybe it is worth a TODO, but probably nothing more until there is a demonstrated need for different tolerances.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxPLOxS-nnRgB3P2A9R:b6pby4p)*

**Comment by maddog-tri** [comment]
I just noticed your comment about `start` and `end`.  Probably (in future PR), the `end` argument should just be removed from the arc-segment constructor for `Connection` (and perhaps both constructors).

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxPP3YBiZE2SzWI_kfL:b-q3l1d1)*

**Comment by agalbachicar** [comment]
>  noticed your comment about start and end.  Probably (in future PR), the end argument should just be removed from the arc-segment constructor for Connection (and perhaps both constructors

I've added a TODO in both constructors to avoid losing it.

---

Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/multilane/connection.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxJZmZlzk1PiGH3C6r7:-KxTcq3WE8EYy8Ii-QVJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7776f350b1177f34b8cf605f6dd855117e46ae/drake/automotive/maliput/multilane/connection.cc#L4)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Unused headers?  (arc_road_curve.h, line_road_curve.h)
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/connection.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxJZjIqmFXme3zmHN3S:-KxTcxurcO3kcmLdu1RA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7776f350b1177f34b8cf605f6dd855117e46ae/drake/automotive/maliput/multilane/connection.h#L10)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Unused header?
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test/multilane_connection_test.cc, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxPI-_qNPy4facHAvv-:-KxTd2ucxdQNCkZuDaUa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7776f350b1177f34b8cf605f6dd855117e46ae/drake/automotive/maliput/multilane/test/multilane_connection_test.cc#L88)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Should test with asymmetric shoulder values....
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxJaEGNenNPwGHZGOJ9:-KxTfPqXQeIIur_lq3Tf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7776f350b1177f34b8cf605f6dd855117e46ae/drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L11)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

BTW:  (META)  In this PR, these methods are only ever called with `kZeroTolerance == 0.`, so this comment is moot in the scope of this PR.  However, in general, these methods need multiple tolerance parameters because of mixed units in the `Endpoint*` types.
  * x, y, and z are lengths --- corresponding to `linear_tolerance()`.
  * `heading` and `theta` are radians, like `angular_tolerance()`.
  * `z_dot` is, uh, the tangent of an angle....
  * `theta_dot` is something else....

Maybe it is worth a TODO, but probably nothing more until there is a demonstrated need for different tolerances.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxTmwvVtfYOBglIYYgO:b8vgdux)*

**Comment by agalbachicar** [comment]
I've addressed all the comments. PTAL.

---

Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxTnC9KeLFlsuj09rfo:b76ci8)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxTsHCtN-uXDRIEioj0:bnfp4nl)*

**Comment by agalbachicar** [comment]
+@sherm1 for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxTsU593eU7jUSnlzcf:b6vi582)*

**Comment by sherm1** [comment]
Platform :lgtm: except for a few BTWs and FYIs, ptal.

---

Reviewed 4 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/maliput/multilane/connection.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUqZKjErzeegyjCXm_:-KxUqZKjErzeegyjCXma:bh5gp6x) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L23)):*
> ```objc
> ///  - x: x position
> ///  - y: y position
> ///  - heading: heading of reference path (radians, zero == x-direction)
> ```

BTW doesn't specify sign convention for heading. Maybe counter clockwise (right hand rule) around z=cross(x,y)? That would mean heading=π/2 -> y direction.

---

*[drake/automotive/maliput/multilane/connection.h, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUsELt3Kqz0qKUQ9OB:-KxUsELt3Kqz0qKUQ9OC:by4a1au) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L79)):*
> ```objc
>   /// Returns an EndpointZ with reversed direction.
>   EndpointZ reverse() const {
>     return EndpointZ(z_, -z_dot_, -theta_, -theta_dot_);
> ```

BTW is this right? I'm surprised by "-theta" here. I would have expected theta to be unchanged just as z is, with only the derivatives reversed. If this is correct as is, please add a comment explaining why.

---

*[drake/automotive/maliput/multilane/connection.h, line 230 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUti-wUIS9HrQWR56M:-KxUti-wUIS9HrQWR56N:bx3ty2x) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L230)):*
> ```objc
>              int num_lanes, double r0, double left_shoulder,
>              double right_shoulder, double cx, double cy, double radius,
>              double d_theta)
> ```

BTW this is a dangerously long argument list of identically-typed arguments (7 doubles in a row). That will be hard for callers to get right. Please consider adding a `struct` collecting these parameters to give this a more tractable signature.

---

*[drake/automotive/maliput/multilane/connection.h, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUwFVlvndGO7qllLt_:-KxUwFVlvndGO7qllLta:b-z7putk) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L326)):*
> ```objc
>   explicit Group(const std::string& id) : id_(id) {}
> 
>   /// Constructs a Group with `id`, populated by `connections`.
> ```

BTW is there any expectation that the id be unique?

---

*[drake/automotive/maliput/multilane/connection.h, line 327 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUw4T-VAeq8Y_ch5P2:-KxUuhKGfatx0xb97dZN:b-x2dcxc) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L327)):*
> ```objc
> 
>   /// Constructs a Group with `id`, populated by `connections`.
>   Group(const std::string& id,
> ```

BTW should specify that the connections must be unique.

---

*[drake/automotive/maliput/multilane/connection.h, line 336 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUw8qCLtSXL2VMJ5zo:-KxUw8qCLtSXL2VMJ5zp:b-oqha7h) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L336)):*
> ```objc
> 
>   /// Adds a Connection.
>   void Add(const Connection* connection) {
> ```

BTW should specify that connection must not already be in the Group.

---

*[drake/automotive/maliput/multilane/test/multilane_connection_test.cc, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxV-hvCEcAdr0-OH8jD:-KxV-hvCEcAdr0-OH8jE:b-yajpd9) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/test/multilane_connection_test.cc#L35)):*
> ```cpp
> GTEST_TEST(EndpointXyTest, Reverse) {
>   const EndpointXy dut{1., 2., M_PI / 4.};
>   const double kZeroTolerance{0.};
> ```

BTW I'm surprised this works at zero tolerance due to the atan2. I guess that's because these nice angles are special cases -- consider using an angle that is not so beautiful, like π/7. Would be good to check that this delivers reasonable tolerance for general angles.

---

*[drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxV-07FtK-lc3CyI13x:-KxV-07FtK-lc3CyI13y:bkpkuoo) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.cc#L38)):*
> ```cpp
>   }
>   delta = std::abs(xy1.heading() - xy2.heading());
>   if (delta > tolerance) {
> ```

FYI could be "scale*delta > tolerance" here using problem length scale to convert an angular error into a displacement error.

---

*[drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUwgotOwC6rtzYe90G:-KxUwgotOwC6rtzYe90H:bt98ecl) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L12)):*
> ```objc
> namespace test {
> 
> // Compares equality within @p tolerance deviation of two EndpointXy objects.
> ```

FYI elsewhere you used back ticks for parameters rather than `@p`.  Fine either way as long as consistent within file; just mentioning it in case you meant to use back ticks here too.

---

*[drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUx1x95c_hACv0AQeP:-KxUx1x95c_hACv0AQeQ:b-r3jafy) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L23)):*
> ```objc
> // TODO(agalbachicar)    Given that EndpointXy is composed of two lengths and
> //                       one angle, tolerance must be replaced into two distinct
> //                       values to match each magnitude.
> ```

FYI an alternative approach for this TODO is to assume a length scale to use to convert radians to length. For example, if s≜length scale in meters and ε≜tolerance in meters then we can require that s⋅θ ≤ ε and δ≤ ε where θ is the angular error and δ the length error.

As written, the code can be interpreted as s=1 meter, which might be a reasonable assumption for many roads.

I think using the problem scale to define appropriate tolerance interpretation is easier for most people to think about than a bunch of separate tolerances, because there is a physical basis for the choice. In my experience if you provide multiple tolerances people generally set them to the same value because they don't have a good basis for any other choice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxV10vUNhk9DENZC4my:b-81up10)*

**Comment by agalbachicar** [comment]
I've addressed all the comments. PTAL.

Thanks for the suggestion on tolerances. I took it for angle --> length comparisons. Later, we need to figure out which is the best way to compare derivatives with a value that makes physical sense.

---

Review status: 4 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/maliput/multilane/connection.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUqZKjErzeegyjCXm_:-KxhHZR_eeWNe42rj2ic:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW doesn't specify sign convention for heading. Maybe counter clockwise (right hand rule) around z=cross(x,y)? That would mean heading=π/2 -> y direction.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/connection.h, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUsELt3Kqz0qKUQ9OB:-Kxhjxz5AbHrVheoit3D:bzaxobl) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L79)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this right? I'm surprised by "-theta" here. I would have expected theta to be unchanged just as z is, with only the derivatives reversed. If this is correct as is, please add a comment explaining why.
</blockquote></details>

Done. I think you are right. I just moved the code from builder.h to this new header so I didn't noticed about it.

---

*[drake/automotive/maliput/multilane/connection.h, line 230 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUti-wUIS9HrQWR56M:-KxhXY2L26uYYc7IZJTi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L230)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is a dangerously long argument list of identically-typed arguments (7 doubles in a row). That will be hard for callers to get right. Please consider adding a `struct` collecting these parameters to give this a more tractable signature.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/connection.h, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUwFVlvndGO7qllLt_:-Kxhn5DrtLCd0MFs-iDO:b5duv7w) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L326)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is there any expectation that the id be unique?
</blockquote></details>

I think it is. I added a TODO to later enforce uniqueness.

---

*[drake/automotive/maliput/multilane/connection.h, line 327 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUw4T-VAeq8Y_ch5P2:-KxhZUf7TiNJt_WFdTxO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L327)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should specify that the connections must be unique.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/connection.h, line 336 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUw8qCLtSXL2VMJ5zo:-Kxhb1Om1kypPkL1RYil:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L336)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should specify that connection must not already be in the Group.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test/multilane_connection_test.cc, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxV-hvCEcAdr0-OH8jD:-Kxhf8saaM0HQiPorsnG:b-rjsfg5) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/test/multilane_connection_test.cc#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm surprised this works at zero tolerance due to the atan2. I guess that's because these nice angles are special cases -- consider using an angle that is not so beautiful, like π/7. Would be good to check that this delivers reasonable tolerance for general angles.
</blockquote></details>

Done. Thanks, I missed it.

---

*[drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxV-07FtK-lc3CyI13x:-Kxi-HX67OmbSqLYSWvM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.cc#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI could be "scale*delta > tolerance" here using problem length scale to convert an angular error into a displacement error.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUwgotOwC6rtzYe90G:-KxhnwHEhWKrXGvuHtYk:broxmc1) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI elsewhere you used back ticks for parameters rather than `@p`.  Fine either way as long as consistent within file; just mentioning it in case you meant to use back ticks here too.
</blockquote></details>

Done. I'd rather use `@p` instead of back ticks but I  left them on the previous file to ease the review process as that code was mostly reviewed.

---

*[drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUx1x95c_hACv0AQeP:-Kxhqx9Cdzky9aGTnC4o:b-r3otn0) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI an alternative approach for this TODO is to assume a length scale to use to convert radians to length. For example, if s≜length scale in meters and ε≜tolerance in meters then we can require that s⋅θ ≤ ε and δ≤ ε where θ is the angular error and δ the length error.

As written, the code can be interpreted as s=1 meter, which might be a reasonable assumption for many roads.

I think using the problem scale to define appropriate tolerance interpretation is easier for most people to think about than a bunch of separate tolerances, because there is a physical basis for the choice. In my experience if you provide multiple tolerances people generally set them to the same value because they don't have a good basis for any other choice.
</blockquote></details>

Thanks for the suggestion! I modified the TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxiibXzrr4EaHRjKgTs:b-4f3fj4)*

**Comment by sherm1** [comment]
Looks great, thanks @agalbachicar! One BTW left, ptal.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/automotive/maliput/multilane/connection.h, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUsELt3Kqz0qKUQ9OB:-KxjLQchWkB4B12GTOQw:b6gnjlr) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L79)):*
<details><summary><i>Previously, agalbachicar (Agustin Alba Chicar) wrote…</i></summary><blockquote>

Done. I think you are right. I just moved the code from builder.h to this new header so I didn't noticed about it.
</blockquote></details>

BTW If this is broken please file an issue saying so and at least leave a TODO referencing it here. (Or feel free to fix it!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxjNJ2gyvVMHIDeT2xQ:b-czt1xl)*

**Comment by agalbachicar** [comment]
*[drake/automotive/maliput/multilane/connection.h, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUsELt3Kqz0qKUQ9OB:-KxmNVsMHiBoj701TV-i:bmy8uox) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L79)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW If this is broken please file an issue saying so and at least leave a TODO referencing it here. (Or feel free to fix it!)
</blockquote></details>

Done. I think it is fixed and I also modified the test to be compliant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325)*

**Comment by agalbachicar** [comment]
Thanks for the reviews!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxmO22aIls618O0BcVO:b-hlc8bm)*

**Comment by maddog-tri** [comment]
Ugh... I neglected to hit the publish button for comments from Friday afternoon.

Unfortunately, a bug has been introduced in this code in the meantime.  (Word to the wise:  do not assume that a unit test is wrong just because it doesn't do what you expect.)

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[drake/automotive/maliput/multilane/connection.h, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUsELt3Kqz0qKUQ9OB:-KxV3hc1CxTlEIJJF97P:bjiirsh) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L79)):*
<details><summary><i>Previously, agalbachicar (Agustin Alba Chicar) wrote…</i></summary><blockquote>

Done. I think it is fixed and I also modified the test to be compliant.
</blockquote></details>

The idea here is "describe the same surface, but traveling in the opposite direction".  `theta` and `theta_dot` describe the superelevation --- the tilt of the road in the lateral direction --- so they get flipped just like `z_dot`.

In other words:  the original code and the test were correct.

---

*[drake/automotive/maliput/multilane/connection.h, line 230 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUti-wUIS9HrQWR56M:-KxV4qxE75Arv_EOu5L9:bg0bbg4) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L230)):*
<details><summary><i>Previously, agalbachicar (Agustin Alba Chicar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For what it's worth, the only practical caller of this constructor is `Builder::Connect()`, which has a more friendly argument list.

And (new comment on the revised code):  I don't think the changes to now introduce two structs to bundle the parameters has made the code any better.  Now there are extra structs for a reader to understand, and the docstring has more complex struct referencing, and the test code just added some `{...}` to wrap around the original arguments.

---

*[drake/automotive/maliput/multilane/connection.h, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUwFVlvndGO7qllLt_:-KxV5CWdOjmdhHsPH-1u:b-6j79w1) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/connection.h#L326)):*
<details><summary><i>Previously, agalbachicar (Agustin Alba Chicar) wrote…</i></summary><blockquote>

I think it is. I added a TODO to later enforce uniqueness.
</blockquote></details>

Not yet!  (There is currently no uniqueness requirement for any ID's in the API, though I anticipate one in the future.)

---

*[drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-KxUx1x95c_hACv0AQeP:-KxnDgdn_vYqDxI9_h4J:b-c6ejf5) ([raw file](https://github.com/robotlocomotion/drake/blob/2fa5e065179a6d2cf3dfdf970e8026fe3184ad99/drake/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L23)):*
<details><summary><i>Previously, agalbachicar (Agustin Alba Chicar) wrote…</i></summary><blockquote>

Thanks for the suggestion! I modified the TODO.
</blockquote></details>

The maliput API has independent `linear_tolerance` and `angular_tolerance` values, so that a backend can independently specify the precision of positions and orientations produced by the backend.  That was part of the motivation for my suggestion for the test predicates, to allow tests to pass in similar tolerances.

I'm not sure how a hidden constant scale factor, which is set to `1.`, has improved on the original code in any way.  (And, `z_dot` and `theta_dot` will still need more help, anyway.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxnGRI717ju7uERgFs2:but0mbr)*

**Comment by agalbachicar** [comment]
Sorry for the wrong assumptions.

Should I open a revert PR or create a new PR to solve the bugs this one introduced?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxnHqBUXIz3Ji4qHAsR:b-z8afrs)*

**Comment by sherm1** [comment]
BTW I defer to @maddog-tri as feature reviewer on all of the issues he raised.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxnMYLztxuNuTt7rytm:b-uriorc)*

**Comment by sherm1** [comment]
FWIW, I think a follow-up PR is preferable to a revert.

**Comment by maddog-tri** [comment]
I agree on preferring a follow-up PR.  (I know sherm is thinking "...because I probably won't have to review the follow-up PR".  :)

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7325#-:-KxnQCW-ymc_e_58nvNO:b2w9371)*

**Pull request merged**
