### PR TITLE
Adds utility to "balance" two quadratic forms

### PR DESCRIPTION
**Pull request by RussTedrake**
and uses it in RegionOfAttraction.
Rederived (much more carefully/thoroughly) from
https://github.com/RobotLocomotion/drake/blob/last_sha_with_original_matlab/drake/matlab/util/balanceQuadForm.m
with more documentation and testing.

adds python bindings for this and the main matrix_util methods.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12875)

### CODE REVIEW

**Comment by sherm1** [comment]
___
*[math/matrix_util.h, line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12875#-M2YKEbIAF-hpdlsGp-1:-M2dIi8-2IUKR-0hNb9A:brsi72x) ([raw file](https://github.com/robotlocomotion/drake/blob/4233f9fab880595807599693f53a8e134b89042b/math/matrix_util.h#L39)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK I think it's somewhat relevant since the `kwarg` is now being bound in Python, and would save the deprecation process. However, it's not that high of cost.
</blockquote></details>

@ericcousineau-tri, @russtedrake: FWIW I generally use "tolerance" as an absolute quantity with units, as in "constraint tolerance" which means the amount by which some error can deviate from zero. I use "accuracy" to mean a relative error for a quantity that is normally expected to be far from zero. Then "accuracy" can be used to estimate a tolerance: basically `tol=accuracy*|quantity_under_test|`. If the quantity under test happens to be near zero, we use a unit scaling to prevent an absurdly tight tolerance:
`tol=accuracy*max(unit_value, quantity_under_test)`. In practice the `unit_value` is almost always set to 1 or 0.1 due to our nice choice of units.

**Comment by RussTedrake** [comment]
@sherm1 -- should we capture something like this and add it to the developer / platform review guidelines?  It was triggered because the examples matrix_util.h do feel inconsistent -- one uses "precision" and the other uses "tolerance".

**Comment by sherm1** [comment]
@RussTedrake -- standardizing the terms and documenting them _somewhere_ seems like a great idea. Where should that go? This seems closer to a notational convention than a coding guideline. We could add it to [Modules/Multibody Kinematics and Dynamics/Terminology and Notation](https://drake.mit.edu/doxygen_cxx/group__multibody__notation.html). The conventions there are already used more broadly in Drake than just the multibody stuff.

**Comment by RussTedrake** [comment]
I could imagine it living in a "terminology and notation" section of doxygen instead of sphinx, I guess.  But I would never think to look for it there, precisely because it is not multibody related?

**Comment by EricCousineau-TRI** [comment]
I'd definitely be down for it living in a general notation section!
If we wanted, that section could then link to Multibody notation / terminology and other more specific areas.

**Comment by sherm1** [comment]
OK, see issue #12890 for standardizing accuracy and tolerance.

**Pull request merged**
