### PR TITLE
Add sugar for getting mutable vector parameters.

### LINKED ISSUE #4387: Add LeafSystem<T>::GetMutableNumericParameter
From #4357

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #4387.

@liangfok for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5874)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm: This sugar is wonderful. Just a couple minor comments.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 489 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5874#-Ki2Mphfuw0xGEAyjSB0:-Ki2Mphfuw0xGEAyjSB1:bi72x9) ([raw file](https://github.com/robotlocomotion/drake/blob/f68f330662ad2bc02cb7091f3e2207a014a86330/drake/systems/framework/leaf_system.h#L489)):*
> ```objc
>     static_assert(std::is_base_of<BasicVector<T>, U<T>>::value,
>                   "U must be a subclass of BasicVector.");
>     auto* leaf_context = dynamic_cast<systems::LeafContext<T>*>(context);
> ```

BTW, missing a `DRAKE_ASSERT(leaf_context != nullptr)` here.

---

*[drake/systems/framework/test/leaf_system_test.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5874#-Ki2R1Su9Gk-hCZFQyH9:-Ki2R1Su9Gk-hCZFQyHA:b-8cfffm) ([raw file](https://github.com/robotlocomotion/drake/blob/f68f330662ad2bc02cb7091f3e2207a014a86330/drake/systems/framework/test/leaf_system_test.cc#L91)):*
> ```cpp
>   BasicVector<T>* GetVanillaMutableNumericParameters(
>       Context<T>* context) const {
>     return this->GetMutableNumericParameter(context, 0 /* index */);
> ```

BTW, I found it odd how this method's name is plural and yet it calls `LeafSystem::GetMutableNumericParameter()`, which is singular. I suppose it depends on whether one considers a `BasicVector<T>` to be singular or plural.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5874#-:-Ki2POhKjcsApIH7Gka0:bop489z)*

**Comment by david-german-tri** [comment]
+@ggould-tri for platform review

---

Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 489 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5874#-Ki2Mphfuw0xGEAyjSB0:-Ki5jaaN4WIoFRynZ4rK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f68f330662ad2bc02cb7091f3e2207a014a86330/drake/systems/framework/leaf_system.h#L489)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing a `DRAKE_ASSERT(leaf_context != nullptr)` here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5874#-:-Ki5jjFPMJe-5fKoEG7Q:b-gbk9vg)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5874)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5874#-:-Ki5nExn-N4o7qxUE2TV:bnfp4nl)*

**Pull request merged**
