### PR TITLE
[render_vtk] Save test images to TEST_UNDECLARED_OUTPUTS_DIR

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19424.

This takes over from #20470.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 6 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6MiHLl2IsQLWF7LtCv:-O6MiHLl2IsQLWF7LtCw:b-7kemsv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6635f263b350859d12e0f5534dfa29ecc7f65277/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L6)):*
> ```cpp
> #include <limits>
> #include <optional>
> #include <source_location>
> ```

Working

Not available on Apple?!  Ugh!

I'll need to think about this a bit more, or maybe find a way to work around it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 6 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6MiHLl2IsQLWF7LtCv:-O6Mu-DY6Vi6OKDBvMVN:b-8lprz1) ([raw file](https://github.com/RobotLocomotion/drake/blob/6635f263b350859d12e0f5534dfa29ecc7f65277/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Looking at cppreference, it seems like we need XCode 15 to use `<source_location>`.  Let's see:

@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-release please
</blockquote></details>

Ah, but per discussion #21557 we need to support XCode 14 for another few months.  I'll need to figure out some respelling work-around.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 6 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6MiHLl2IsQLWF7LtCv:-O6O4dTCDnSkL3ijEpnL:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6635f263b350859d12e0f5534dfa29ecc7f65277/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, but per discussion #21557 we need to support XCode 14 for another few months.  I'll need to figure out some respelling work-around.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

+@xuchenhan-tri for platform review, please.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-:-O6RK4nS9NdC80p8xOeI:b-s6ko0)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 245 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6RGGA4Dxz4aPfeClsQ:-O6RGGA4Dxz4aPfeClsR:b-r88kzt) ([raw file](https://github.com/RobotLocomotion/drake/blob/e97c1d3ede3d6e33f1a9203af9a3eaad303fe1b2/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L245)):*
> ```cpp
> template <class Image>
> void SaveTestOutputImage(const Image& image, const std::string& filename) {
>   const std::string test_name =
> ```

BTW Locality would suggest not bothering to get the test name until *after* you've determined there's a root directory to write to.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 245 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6RHXn_28M_s05ZI5sk:-O6RHXn_28M_s05ZI5sl:b-hezt8y) ([raw file](https://github.com/RobotLocomotion/drake/blob/e97c1d3ede3d6e33f1a9203af9a3eaad303fe1b2/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L245)):*
> ```cpp
> template <class Image>
> void SaveTestOutputImage(const Image& image, const std::string& filename) {
>   const std::string test_name =
> ```

BTW This works because we don't have `GTEST_TEST(FooTest, Thing)` and `GTEST_TEST(BarTest, Thing)` in this file. I don't think we need to make this *more* robust, but putting a note here suggesting this fragility might not go amiss.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 648 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6RJwrW0g7S8KIKdKWt:-O6RJwrW0g7S8KIKdKWu:bw891c8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e97c1d3ede3d6e33f1a9203af9a3eaad303fe1b2/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L648)):*
> ```cpp
>         {}, Vector3d{bg.r / 255., bg.g / 255., bg.b / 255.}};
>     RenderEngineVtk engine(params);
>     Render(__LINE__, fmt::to_string(bg), &engine);
> ```

nit: This needs a `fmt_eigen()` in it, right?

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: mod CI failure Sean pointed out below.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-:-O6SKkG95q82qKMt2hGh:bo62t8b)* status: 3 unresolved discussions

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 245 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6RHXn_28M_s05ZI5sk:-O6SaHIZ4Y0te-xgmQpm:b-u0xj9d) ([raw file](https://github.com/RobotLocomotion/drake/blob/e97c1d3ede3d6e33f1a9203af9a3eaad303fe1b2/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L245)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This works because we don't have `GTEST_TEST(FooTest, Thing)` and `GTEST_TEST(BarTest, Thing)` in this file. I don't think we need to make this *more* robust, but putting a note here suggesting this fragility might not go amiss.
</blockquote></details>

I am satisfied that the "Multiple tests erroneously ..." exception will probably be sufficient guidance to future developers who fall into that trap or several others like it.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 648 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6RJwrW0g7S8KIKdKWt:-O6SavOq-La1NPCM6LkD:b-n0pxc5) ([raw file](https://github.com/RobotLocomotion/drake/blob/e97c1d3ede3d6e33f1a9203af9a3eaad303fe1b2/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L648)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This needs a `fmt_eigen()` in it, right?
</blockquote></details>

Almost.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 245 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6RHXn_28M_s05ZI5sk:-O6Sqrez3aN64hwYItQE:beb9su7) ([raw file](https://github.com/RobotLocomotion/drake/blob/e97c1d3ede3d6e33f1a9203af9a3eaad303fe1b2/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L245)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am satisfied that the "Multiple tests erroneously ..." exception will probably be sufficient guidance to future developers who fall into that trap or several others like it.
</blockquote></details>

I can accept that, but the test name doesn't affect the *file* name, only the directory name. Still, that probably be a problem. Two tests would get their files written to the same directory, but the odds that they'd *also* have the same line number and the same description is probably impossible.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 648 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6RJwrW0g7S8KIKdKWt:-O6Sr8r38y5YpNDCMe9-:bttj72e) ([raw file](https://github.com/RobotLocomotion/drake/blob/e97c1d3ede3d6e33f1a9203af9a3eaad303fe1b2/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L648)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Almost.
</blockquote></details>

Right...bg isn't Vector3d. I was seduced by the `Vector3d` in the previous line and wasn't thinking right.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21232)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 245 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21232#-O6RHXn_28M_s05ZI5sk:-O6Svjgp6DixHP6xcvIE:b-2eg67x) ([raw file](https://github.com/RobotLocomotion/drake/blob/e97c1d3ede3d6e33f1a9203af9a3eaad303fe1b2/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L245)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I can accept that, but the test name doesn't affect the *file* name, only the directory name. Still, that probably be a problem. Two tests would get their files written to the same directory, but the odds that they'd *also* have the same line number and the same description is probably impossible.
</blockquote></details>

(In case it wasn't clear, my thesis is that since this functions fails-fast in the case of unintended duplication, that's all we need.  Once the developer sees their test failing locally during development, they can dig in and deal with whatever adjustments are necessary.)

**Pull request merged**
