### PR TITLE
Remove 2021-12 geometry deprecation

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Remove `system::rendering::PoseVector`, `system::rendering::PoseVector`, `system::rendering::PoseAggregator`, `system::rendering::PoseBundleToDrawMessage`, `system::rendering::RenderPoseToGeometry`, `system::rendering::FrameVelocity`, `geometry::scene_graph::get_pose_bundle_output_port()`, `geometry::scene_graph::all_frame_ids()`, `systems::sensors::RgbdSensor::X_WB_output_port()`, and exported pose bundle output port in `ManipulationStation`.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16156)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for both reviews please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16156#-:-MpmlP2_Dbi9HHa0lF2W:b9hjj9j)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: do not merge) until tomorrow 12-1.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16156#-:-MpmosEG2bXEHyLuyEv2:b-ebousp)* status: LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16156#-:-MpmpeeTDbXr7WV0WWt7:bnfp4nl)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
Midnight UTC should be good enough =P.  Merging now.

**Comment by RussTedrake** [comment]
___
*[systems/sensors/rgbd_sensor.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16156#-MpppHR-AFj551bbKo9E:-MpppHR-AFj551bbKo9F:b-s91rc9) ([raw file](https://github.com/robotlocomotion/drake/blob/00917c5540f3fbe21741f20785ea05b5f897ebb6/systems/sensors/rgbd_sensor.h#L40)):*
> ```objc
>  - depth_image_16u
>  - label_image
>  - X_WB (2021-12-01 deprecated)
> ```

fyi -- port names are not truly deprecated (#12214).  I woke this morning to a CI failure on my manipulation repo:
```
    cam0_pose = cam0.GetOutputPort('X_WB').Eval(cam0_context)
RuntimeError: System camera0 does not have an output port named X_WB
```
despite raising deprecation warnings to errors.  So this removal is technically a breaking change.

**Comment by jwnimmer-tri** [comment]
While I agree that we should work on #12214, I've been reserving the phrase "breaking change" for changes that were not announced ahead of time with a transition period, and this one was announced in https://drake.mit.edu/release_notes/v0.33.0.html.  Note that "announced" means in the release notes, not via compile-time or runtime warnings.  Even if we fix #12214, there will always be some kinds of things where there is _no way_ to have the compiler or runtime provide a diagnostic.

**Comment by RussTedrake** [comment]
nit: I don't think that https://drake.mit.edu/release_notes/v0.33.0.html announced that the port named 'X_WB' is no longer available.  It says that the function drake::systems::sensors::RgbdSensor::X_WB_output_port is no longer available.

In practice, if my code breaks (despite me being fully immersed in the fire hose) and I have to go in and read the PRs/code changes to figure out what happened, then I would probably consider that a breaking change.

**Comment by jwnimmer-tri** [comment]
I'll work on prioritizing the policy documentation part of #10605 soon, so that we can have a constructive discussion about this and find consensus across the whole team.

**Pull request merged**
