### PR TITLE
[tutorials] Remove hard linebreaks in Hydroelastic Contact

### LINKED ISSUE #19641: Hydroelastic Contact: Basics images missing on Deepnote
### What happened?

Open our online hosted tutorials to the [Hydroelastic Contact: Basics](https://deepnote.com/workspace/Drake-0b3b2c53-a7ad-441b-80f8-bf8350752305/project/Tutorials-2b4fc509-aef2-417d-a40d-6071dfed9199/notebook/hydroelastic_contact_basics-1d03814005274062aad03a875aa5bd86) page.

There are two problems:

(1) Hard linebreaks.  Apparently Jupyter locally and Deepnote use different markdown conventions.  The hard linebreaks in the source Markdown are showing up in Deepnote and disrupting the flow.  In local Jupyter preview, all is fine.

(2) Missing images.  Apparently, Deepnote cannot handle image attachments.

### Version

1.18.0

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

dockerhub

### Relevant log output

Here's a screenshot:

---

image

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Towards #19641.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19643)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19643#-:-NYQ9fgtDJpRIwGDdaja:bxazayu)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Do you actually want a feature review separate from platform review?  If you only need one unified review, you can kick it over to Sherm as on-call for tomorrow.

**Review by DamrongGuoy — COMMENTED** [review]
No need for feature review: -@jwnimmer-tri 

+@sherm1 for platform review tomorrow (Wednesday), please.

+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19643#-:-NYQNq1M7ajMSyI6iuNr:b-ocu5g1)* status: LGTM missing from assignee sherm1(platform)

**Comment by DamrongGuoy** [comment]
Thank you @sherm1.  I have tested it by copying the file from Drake master to my temporary project in Deepnote.

https://github.com/RobotLocomotion/drake/issues/19641#issuecomment-1601570351

**Pull request merged**
