### PR TITLE
Add documentation explaining why we keep accuracy in the Context

### PR DESCRIPTION
**Pull request by sherm1**
Records for posterity discussions with @RussTedrake, @edrumwri, and @amcastro-tri regarding why it is useful to have user-requested accuracy stored in the Context.

+@edrumwri for feature review
+@RussTedrake for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6283)

### CODE REVIEW

**Comment by sherm1** [comment]
(Oh, I guess it doesn't work to make these assignments in the PR description.)
+@edrumwri for feature review
+@russtedrake for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-:-Km3kwmwDWFsQj03YnX-:b-f31y4u)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/context.h, line 353 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3oNKg8ihPaCPE14S9:-Km3oNKg8ihPaCPE14SA:bfvch5a) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L353)):*
> ```objc
> 
>   /// Records the user's requested accuracy. If no accuracy is requested,
>   /// suitable computation-dependent defaults will be used. Some
> ```

It's not clear where these defaults will be used.

---

*[drake/systems/framework/context.h, line 357 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3obB6QU0M6j_yTig5:-Km3obB6QU0M6j_yTig6:b-v4n01w) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L357)):*
> ```objc
>   /// 
>   /// Requested accuracy is stored in the %Context for two reasons:
>   /// - It permits all computations performed on a System to see the _same_
> ```

all computations, all algorithms, or both?

---

*[drake/systems/framework/context.h, line 358 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3ojC3kC4DKQrxqO1B:-Km3ojC3kC4DKQrxqO1C:bz5x221) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L358)):*
> ```objc
>   /// Requested accuracy is stored in the %Context for two reasons:
>   /// - It permits all computations performed on a System to see the _same_
>   ///   accuracy request, and
> ```

Can we say that it ensures that accuracy is stored and set in a single place? (You make the point explicitly below, but I don't think it would hurt to make it here too).

---

*[drake/systems/framework/context.h, line 362 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3ouN_BPJ4Rvqbk8cr:-Km3ouN_BPJ4Rvqbk8cs:b-lj23gc) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L362)):*
> ```objc
>   ///   the requested accuracy has changed.
>   ///
>   /// The accuracy of a complete simulation depends on _all_ contributing
> ```

Russ might balk at the focus on simulation here :)

---

*[drake/systems/framework/context.h, line 363 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3p0y54w4sMLspccnv:-Km3p0y54w4sMLspccnw:b-o2s43t) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L363)):*
> ```objc
>   ///
>   /// The accuracy of a complete simulation depends on _all_ contributing
>   /// computations, so it is important that they all work to the same end.
> ```

I'm not sure what you mean by "all work to the same end". I think what you're getting at- in a Simulation context, as well as others- is that as accuracy in a simulation is increased/decreased, all components of the simulation correspondingly should increase the accuracy of their computations accordingly. But that thought does not start to emerge until the examples below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6283)*

**Comment by sherm1** [comment]
Addressed your comment @edrumwri, ptal.

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/context.h, line 353 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3oNKg8ihPaCPE14S9:-Km4-S9VggFZwFoMB3ht:b-76w72y) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L353)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It's not clear where these defaults will be used.
</blockquote></details>

Done. Reworded but I can't be specific here, ptal.

---

*[drake/systems/framework/context.h, line 357 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3obB6QU0M6j_yTig5:-Km4-vfRjymmu75TYF0Y:bbj9e56) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L357)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

all computations, all algorithms, or both?
</blockquote></details>

I'm just using "computations" generically. An algorithm executed on a computer would count -- do you think that needs to be said explicitly?

---

*[drake/systems/framework/context.h, line 358 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3ojC3kC4DKQrxqO1B:-Km40vZ6cUBaEiXmYodj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L358)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Can we say that it ensures that accuracy is stored and set in a single place? (You make the point explicitly below, but I don't think it would hurt to make it here too).
</blockquote></details>

Done.

---

*[drake/systems/framework/context.h, line 362 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3ouN_BPJ4Rvqbk8cr:-Km41ICpZHjLE2bfOV5f:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L362)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Russ might balk at the focus on simulation here :)
</blockquote></details>

Done.

---

*[drake/systems/framework/context.h, line 363 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3p0y54w4sMLspccnv:-Km41na1b2XztqTF3b12:b4ytdtc) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L363)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I'm not sure what you mean by "all work to the same end". I think what you're getting at- in a Simulation context, as well as others- is that as accuracy in a simulation is increased/decreased, all components of the simulation correspondingly should increase the accuracy of their computations accordingly. But that thought does not start to emerge until the examples below.
</blockquote></details>

Done (I think). PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-:-Km421eK4VzAfOeTb0rB:b-tr9joc)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/context.h, line 363 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3p0y54w4sMLspccnv:-Km43EDV_TVK-aq5iPWW:b-63y527) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L363)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done (I think). PTAL.
</blockquote></details>

BTW Perfect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6283)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/context.h, line 357 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3obB6QU0M6j_yTig5:-Km43Ja9qVmhFTQ6HPdT:b-wwcz1x) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L357)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I'm just using "computations" generically. An algorithm executed on a computer would count -- do you think that needs to be said explicitly?
</blockquote></details>

How about "performed over a System"? Not verbose, not overly specific, but removes the cognitive dissonance of "computation on a System" (which Drake does not do).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6283)*

**Comment by sherm1** [comment]
All feature review comments addressed. Ready for platform review, @russtedrake. (Very short PR)

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/context.h, line 357 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-Km3obB6QU0M6j_yTig5:-Km7TxHV123sbvsCvs9n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a47f2e1a560bbc93fb5850a39b4c6cda110e1de/drake/systems/framework/context.h#L357)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

How about "performed over a System"? Not verbose, not overly specific, but removes the cognitive dissonance of "computation on a System" (which Drake does not do).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-:-Km7U-lE5W2llV4kIUPl:bnh5qlg)*

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6283#-:-Km7UW_gNz-VWcz2nZ93:bnfp4nl)*

**Comment by sherm1** [comment]
I'll deem this comment-only PR sufficiently reviewed to merge into master. @RussTedrake, if you have further thoughts we can address in a subsequent PR.

**Pull request merged**
