### PR TITLE
set_name used for Subsystems in IIWA World Diagram 

### PR DESCRIPTION
**Pull request by naveenoid**
This is to enable testing of the solution to https://github.com/RobotLocomotion/drake/issues/4026

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5530)

### CODE REVIEW

**Comment by naveenoid** [comment]
@david-german-tri : Would this be a useful set of diagrams to debug? I can add others if needed and / or even name nested diagrams within these..

**Comment by david-german-tri** [comment]
Trying this locally now with my #4026 WIP!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5530#-:-KfRShjVWgknSP37XS39:b9qapay)*

**Comment by david-german-tri** [comment]
CI objects, but :lgtm: otherwise

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5530#-:-KfTe7_irGeeNnRlngcb:b-qwcszy)*

**Comment by naveenoid** [comment]
@drake-jenkins-bot retest this please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5530#-:-KfVSIFoQ_jYWHKLcnc9:bzdwe9o)*

**Comment by naveenoid** [comment]
+@soonho-tri for platform review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5530#-:-Kfc8XvZHELLy9dB7JV4:bxw8cpy)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5530#-:-KffWvEnACVahD0js8FE:bnfp4nl)*

**Pull request merged**
