### PR TITLE
[workspace] Remove determine_os logic

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Centralize choice of C++20 to be project-wide, instead of OS-specific.

Simplify CMakeLists to use whatever OS codename it finds for the bazel customizations, with only warnings (not errors) when none is found.

Overall, these changes remove some barriers to building Drake on non-Ubuntu linuxen.

Towards #14967.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21089)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware or +@svenevs perhaps one of you has time for a feature review here?  If so, please go ahead (and un-assign the ).

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: aside from a stray `\t`.

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21089#-:-NsAC7qd51gaLIFbzzX0:b-de1scv)* status: 1 unresolved discussion, LGTM missing from assignee svenevs, needs platform reviewer assigned

___
*[`CMakeLists.txt` line 72 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21089#-NsABcgd-PzzgTcHRsRy:-NsABcgd-PzzgTcHRsRz:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/47a9f25e55fec3bf12fa0950aac920bb9b715f20/CMakeLists.txt#L72)):*
> ```CMake
>       set(MAYBE_RC "tools/ubuntu-${UNIX_DISTRIBUTION_CODENAME}.bazelrc")
>       if(NOT EXISTS "${PROJECT_SOURCE_DIR}/${MAYBE_RC}")
> 	message(WARNING "Could NOT find config file ${MAYBE_RC}")
> ```





_Suggestion:_
```CMake
        message
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review per schedule, please.

> Dismissed @mwoehlke-kitware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21089#-:-NsAFznrDeHtvdMmYLaA:bbnvyd5)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`CMakeLists.txt` line 72 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21089#-NsABcgd-PzzgTcHRsRy:-NsAFyjc9-deAZ2XBxl-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/47a9f25e55fec3bf12fa0950aac920bb9b715f20/CMakeLists.txt#L72)):*
> ```CMake
>       set(MAYBE_RC "tools/ubuntu-${UNIX_DISTRIBUTION_CODENAME}.bazelrc")
>       if(NOT EXISTS "${PROJECT_SOURCE_DIR}/${MAYBE_RC}")
> 	message(WARNING "Could NOT find config file ${MAYBE_RC}")
> ```

Done.

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21089)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21089#-:-NsAVKaI0vAs2ZzLR7Gw:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),mwoehlke-kitware

**Pull request merged**
