### PR TITLE
Add libbot support to Bazel

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5405)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review, please.

+@russtedrake for feature review please -- is this enough of libbot's features for what we need?
- bot-lcm-logfilter
- bot-lcm-logsplice
- bot-lcm-tunnel
- bot-spy
- lcmtypes_bot2-core-py

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5405#-:-KeP9aOr_I9OZe--jGz4:b-k6gi8i)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5405#-:-KePEVsdPzv23AYzcDxO:bnfp4nl)*

**Comment by sammy-tri** [comment]
BTW bot-procman-sheriff is part of my (near) daily workflow.  I don't have the slightest idea how miserable it will be to use in a "bazel run" world (due to my lack of experience with "bazel run").  If the cwd remains the same and args are passed directly through it shouldn't be too bad.  If cwd changes while under bazel we'll have to rewrite some .pmd files, but also livable I think.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5405#-:-KePy8x_kNtHlz3QpmLy:b8j4zj8)*

**Comment by jwnimmer-tri** [comment]
Probably the right answer is just to invoke the Bazel-compiled `bazel-bin/external/libbot/bot-procman-sheriff` directly, instead of via `bazel run`.  I will see if it makes sense to add that to this PR, or else a future one.

**Comment by jwnimmer-tri** [comment]
I am going to save the sheriff code for a future PR.

+@sherm1 for platform mentor.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5405#-:-KeQw5OHPyx_cqltSqtS:b2ilyy0)*

**Comment by RussTedrake** [comment]
:lgtm:  thanks for doing it.  

Re: @sammy-tri 's comment.  I think he was saying that adding support for https://github.com/RobotLocomotion/libbot2/tree/master/bot2-procman
to the list of libbot features compiled by bazel would help.  (depending on how easy it is).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5405#-:-KeW7GNtkOtla1xFu-u9:bsu9ixi)*

**Comment by jwnimmer-tri** [comment]
Yup, it shouldn't be too hard, but likely about the same size as this PR, so I will defer to another PR.   I've added it to the checklist.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5405#-:-KeWBhCELH0N7AhHqxNu:bauw0lx)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5405#-:-Kea1qovbrEK1X0KOWCn:bnfp4nl)*

**Pull request merged**
