### PR TITLE
Use DrakeVisualizerd instead of DrakeVisualizer.

### PR DESCRIPTION
**Pull request by hongkai-dai**
In the future PR we will templatize DrakeVisualizer class. This PR makes sure the code doesn't break, and is compatible with the future templated DrakeVisualizer class.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14547)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for feature review please, thanks!
+@jwnimmer-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14547#-:-MRS_k825R4gVjG8_ZRS:b-3jixr8)* status: LGTM missing from assignees SeanCurtis-TRI(platform),jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 44 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14547)* status: 4 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @hongkai-dai, @jwnimmer-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14547#-MRVHYBiD6whPguE9cO8:-MRVHYBiD6whPguE9cO9:bxoz1sl) (no related file):*
I left a few files unreviewed, because they have unrelated formatting changes within them.  Please limit the PR to be only the topical changes, and remove clang-format shrapnel.

---
___
*[geometry/drake_visualizer.h, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14547#-MRVHDjI6h-AKG-iatv3:-MRVHDjJAGuscgRttdBR:b8oyhjx) ([raw file](https://github.com/robotlocomotion/drake/blob/d9dd5297e2d851f2802d539c9e161c0aa6d8490b/geometry/drake_visualizer.h#L108)):*
> ```objc
>    - Evaluating multiple instances of %DrakeVisualizer in a single thread that
>      share the same lcm::DrakeLcmInterface.  */
> ```

nit I see no reason to have a blank line here.
___
*[geometry/drake_visualizer.h, line 109 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14547#-MRVHjXA0FE4kJt5CtGo:-MRVHjXA0FE4kJt5CtGp:b-exgp6n) ([raw file](https://github.com/robotlocomotion/drake/blob/d9dd5297e2d851f2802d539c9e161c0aa6d8490b/geometry/drake_visualizer.h#L109)):*
> ```objc
>      share the same lcm::DrakeLcmInterface.  */
> 
> class DrakeVisualizer : public systems::LeafSystem<double> {
> ```

The class overview should have an warning of the pending breaking change.
___
*[geometry/drake_visualizer.h, line 267 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14547#-MRVHGDl8pLBEVSLQYF5:-MRVHGDl8pLBEVSLQYF6:bwby9km) ([raw file](https://github.com/robotlocomotion/drake/blob/d9dd5297e2d851f2802d539c9e161c0aa6d8490b/geometry/drake_visualizer.h#L267)):*
> ```objc
> };
> 
> using DrakeVisualizerd = DrakeVisualizer;
> ```

This needs a Doxygen comment explaining what is going on.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I concur with all of @jwnimmer-tri's comments. Including about the shrapnel. It's better PR etiquette to make sure the PR contains only the changes necessary to the stated purpose.  :)

> Reviewed 48 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14547#-:-MRVKcIn1PfRvLtBnNpv:bfppot9)* status: 4 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
I pushed some fixes.  We need to land this to unblock a release.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14547#-:-MRW6JWr27C5qdcH2Xmq:b-w6wu7r)* status: LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14547#-MRVHYBiD6whPguE9cO8:-MRW6ZeCCd-rP60bKmkv:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I left a few files unreviewed, because they have unrelated formatting changes within them.  Please limit the PR to be only the topical changes, and remove clang-format shrapnel.
</blockquote></details>

Done.

---
___
*[geometry/drake_visualizer.h, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14547#-MRVHDjI6h-AKG-iatv3:-MRW6VET0zkl5GNRXz2S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9dd5297e2d851f2802d539c9e161c0aa6d8490b/geometry/drake_visualizer.h#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I see no reason to have a blank line here.
</blockquote></details>

Done.
___
*[geometry/drake_visualizer.h, line 109 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14547#-MRVHjXA0FE4kJt5CtGo:-MRW6U2w-YTeVvz8VEGK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9dd5297e2d851f2802d539c9e161c0aa6d8490b/geometry/drake_visualizer.h#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The class overview should have an warning of the pending breaking change.
</blockquote></details>

Done.
___
*[geometry/drake_visualizer.h, line 267 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14547#-MRVHGDl8pLBEVSLQYF5:-MRW6Sv02fmiZ_rvSMfS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9dd5297e2d851f2802d539c9e161c0aa6d8490b/geometry/drake_visualizer.h#L267)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This needs a Doxygen comment explaining what is going on.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14547#-:-MRWAU5j0uYfHuCVF3oa:bmxilld)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jwnimmer-tri** [comment]
:lgtm: platform.

**Comment by hongkai-dai** [comment]
Thanks Jeremy for the fixup commit!

**Pull request merged**
