### PR TITLE
WIP - Submit to new CDash instance

### PR DESCRIPTION
**Pull request by jamiesnape**

### CODE REVIEW

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
retest this please

**Comment by RussTedrake** [comment]
looks like this somehow broke my frail build server script...?

**Comment by jamiesnape** [comment]
Very unexpected. I will take a look shortly.

**Comment by RussTedrake** [comment]
Http vs https?  Is ctest encoding the test output differently?

**Comment by jamiesnape** [comment]
The new server is SSL only. The test output is encoded the same, but it is transmitted over HTTPS.

**Comment by RussTedrake** [comment]
Must be something silly with my parsing then :(

**Comment by jamiesnape** [comment]
`http://kobol.csail.mit.edu/cd/` is hard-coded in several places in `postProcessCTest.m`. It would need to be `https://drake-cdash.csail.mit.edu/` in this case.

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
retest this please

**Comment by RussTedrake** [comment]
I took a look. The hard-coded kobol references are only for the printouts that
give a link back into cdash. I can’t see how it would cause an error in the
decode lines. It looks like the xml parser for the ctest output file is not
finding anything inside the <Value> tag…?

**Comment by RussTedrake** [comment]
just looked into this, and I confirm that the problem is that the encoding of the test output is different in the Test.xml file.  In other pull requests, I see e.g.:

```
                        <Measurement>
                                <Value encoding="base64" compression="gzip">eJy\
1VF1r2zAUfS36FefRhjSp3a5JuyzQjg0CC4wupQ9jFCW6sUVsyUhyPv59r9KmpbQs3cNkbIR07r3nni\
NZ4C9jiAmuMMUP/l4juUkxEm9RX22zdbooA7KLwdlxfpLlmJaEiQzlnXVL38HYzLvvRAI3ET1DMuie8\
NMfnKY4Pzue6YCkqMxGnp+l78a9jKu2aH1AnncQcwkBMbUoKMAH6QKpDsK2IVjD7wKhJE+XKKlq1tp0\
dhNFftmBdVBU2674zrPGWdXOA7RZWFfLoC1jV9ozsfV63eWVch1b685tzZ2J30d30hltistYAePJLWw\
bmjZ4lHJFMDZgRmQQyDMnbJlfolpCsJi1BbJ+Pkj/HMVEI1YLN7rQ6tqq7diQC1pWE5K+dVSTCbdGh9\
EhQPcQAJJFO2dxx4+kDlaMoKtQSR8js08fj4z400f4glay+innS1nQL7mgHYks9v3NOZa99SzhweaRV\
JrdvEiFIdaSJWwbJQNhycvRrLmHrptqF7DzDovoaSWNdKil0U1byWCdR/IsPtvDIDak1B5rXVWIBosn\
YvqDIvFxaKSjXE3tqXri2R+kQtdtrvDlYGuJy/nAzhjQwYZf12zTz/9I4qks35xXbJJXid448RiUZ/G\
+7TaTRQyAGMaa90bWNPJbPry170Ulg+/Fjd5HGA17LzkwpMjhXqvRsPc83a/W5D0zGv13Y/e19wUhOH\
8lZ6ANKzi3in8SmXgAeKyw3Q==</Value>
                        </Measurement>
```

but in this pull requests, I'm seeing

```
                        <Measurement>
                                <Value>
                            &lt; M A T L A B (R) &gt;
                  Copyright 1984-2012 The MathWorks, Inc.
                    R2012b (8.0.0.783) 64-bit (glnxa64)
                              August 22, 2012


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

[[NON-XML-CHAR-0x8]Warning: the IMU outputs have not been tested yet (due to bu\
g 1728)][NON-XML-CHAR-0x8]
[[NON-XML-CHAR-0x8]&gt; In RigidBodyInertialMeasurementUnit&gt;RigidBodyInertia\
lMeasurementUnit.RigidBodyInertialMeasurementUnit at 26
  In testRigidBodyInertialMeasurementUnit&gt;testAtlas at 15
  In testRigidBodyInertialMeasurementUnit at 3
  In fevalPackageSafe at 21][NON-XML-CHAR-0x8]
Error using RigidBodyInertialMeasurementUnit (line 9)
need to update kinematics implementation for planar manipulators (bug 1728) bef\
ore this will work

Error in testRigidBodyInertialMeasurementUnit&gt;compare2dTo3d (line 78)
imu2d = RigidBodyInertialMeasurementUnit(r2d, body, xy, rpy);

Error in testRigidBodyInertialMeasurementUnit (line 4)
compare2dTo3d();

Error in fevalPackageSafe (line 21)
  feval(f);


&lt;test_name&gt;systems/plants/test/testRigidBodyInertialMeasurementUnit&lt;/t\
est_name&gt; &lt;error_id&gt;&lt;/error_id&gt; &lt;error_message&gt;need to upd\
ate kinematics implementation for planar manipulators (bug 1728) before this wi\
ll work&lt;/error_message&gt;
matlab exit code: 1
</Value>
                        </Measurement>
```

I can update the script to support either case, but I don't understand why your changes caused the different results on the same server (same version of ctest, etc).

**Comment by RussTedrake** [comment]
i've updated the build server scripts.  will close and reopen to kick my build servers.

**Comment by jamiesnape** [comment]
No too sure why that is happening either. You could try adding `--no-compress-output` to your `ctest` script.

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
Still errors with drake001, I think. Not too sure about drake006.

**Comment by RussTedrake** [comment]
Ah.  Forgot to update drake001. Drake006 looks fixed.

**Comment by RussTedrake** [comment]
Can you make this report to both cdash servers for now?

**Comment by jamiesnape** [comment]
Not easily, unfortunately.

**Comment by RussTedrake** [comment]
Ok.  Let's just do this then

**Pull request merged**
