### PR TITLE
rgbd_camera: Allow disabling of label port of RgbdCameraDiscrete

### LINKED ISSUE #8117: RgbdCameraDiscrete: Make label rendering optional
Per conversation with @kunimatsu-tri and @rcory

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
~Resolves first portion of #8117.~

Closes #8117.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8119)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8119#-:-L5pVTdYM6J5pj-auFp8:b-1actl4)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8119#-:-L5p_-zHfZGvfb7Iw0L-:b9benhj)*

**Comment by EricCousineau-TRI** [comment]
+@ggould-tri for platform review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8119#-:-L5p_iWP9WErCAz2UMsF:bcav8r0)*

**Comment by jwnimmer-tri** [comment]
FYI https://abseil.io/tips/94 shuns bool-valued options parameters.  When mixed with defaulted-but-non-zero "period" argument, its even more annoying at call sites.  Consider overloading the constructor (and using delegation), so that the period default goes into the cc file, and that we could have `LabelOutput::kEnabled` and `LabelOutput::kDisabled` (enum class) spellings at call sites.

**Comment by EricCousineau-TRI** [comment]
> FYI https://abseil.io/tips/94 shuns bool-valued options parameters. [...]

I'd prefer to defer changing this until (a) there are more discrete options for this argument or (b) a "named parameter" struct is merited (my preference). Thanks for the info, though!

**Comment by ggould-tri** [comment]
I agree with @jwnimmer-tri but am happy with leaving it at author's discretion, especially if this is expected to be an area of future change.
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8119#-:-L5smkU3Mjfig8kgBwlO:bf0szjv)*

**Comment by EricCousineau-TRI** [comment]
Filed follow-up issue: https://github.com/RobotLocomotion/drake/issues/8123

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8119#-:-L5t56vyePQJYbnOYwf9:baidqu4)*

**Pull request merged**
