### PR TITLE
[multibody] ContactResults no longer reports quadrature data

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards simplifying https://github.com/RobotLocomotion/drake/pull/21623 by reducing things we need to efficiently copy and memorize, and therefore towards https://github.com/RobotLocomotion/drake/issues/20545.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21683)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21683)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/hydroelastic_contact_info.h` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21683#-O1A3fJi2zaFQywXi1_Y:-O1A3fJi2zaFQywXi1_Z:bguk7jd) ([raw file](https://github.com/RobotLocomotion/drake/blob/5b43b4608fd05016fe80fa802f5830f5c1ca3681/multibody/plant/hydroelastic_contact_info.h#L68)):*
> ```objc
>      `ContactSurface::centroid()`.
>    @param[in] quadrature_point_data Ignored data that will be discarded, kept
>      here as an argument only for backwards compatibility.  */
> ```

FYI In my future PR train, I deprecate _both_ of these constructors in their entirety.  So here, I'm not bothering to deprecate the third argument, since it would be moot in a few days anyway.

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

**Review by amcastro-tri — COMMENTED** [review]
Excellent! easy to review. Thanks @jwnimmer-tri, I honesly do like getting rid of this code.

:lgtm_strong: 

+@SeanCurtis-TRI for platform review please

> Reviewed 10 of 15 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21683#-:-O1IjFg048dfvxl30nNd:blzt4lb)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm` line 45 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21683#-O1IgypM7UO8j7DqgzQk:-O1IgypNDk9nW76UuBGA:b9seev7) ([raw file](https://github.com/RobotLocomotion/drake/blob/b128c7da9e064f1db3c08b0397ad44ca3278b4ca/lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm#L45)):*
> ```
> 
>   // Vestigial. Always zero.
>   int32_t num_quadrature_points;
> ```

just for my own education here also, is there a mechanism to deprecate these?
___
*[`multibody/plant/hydroelastic_contact_info.h` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21683#-O1A3fJi2zaFQywXi1_Y:-O1IfIC139i841OgtJyy:bn8wsva) ([raw file](https://github.com/RobotLocomotion/drake/blob/5b43b4608fd05016fe80fa802f5830f5c1ca3681/multibody/plant/hydroelastic_contact_info.h#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI In my future PR train, I deprecate _both_ of these constructors in their entirety.  So here, I'm not bothering to deprecate the third argument, since it would be moot in a few days anyway.
</blockquote></details>

SGTM. For my own education, why not to deprecate in this PR? Is this used anywhere outside of our control?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21683)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm` line 45 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21683#-O1IgypM7UO8j7DqgzQk:-O1Iql4rEfWhSuLzUITr:bgfttro) ([raw file](https://github.com/RobotLocomotion/drake/blob/b128c7da9e064f1db3c08b0397ad44ca3278b4ca/lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm#L45)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

just for my own education here also, is there a mechanism to deprecate these?
</blockquote></details>

https://drake.mit.edu/stable.html#lcm-messages

In short, we could add new message `lcmt_hydroelastic_contact_surface_for_viz2` that doesn't have these fields.
___
*[`multibody/plant/hydroelastic_contact_info.h` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21683#-O1A3fJi2zaFQywXi1_Y:-O1IqY9M0yHFzDFg_7fo:bqpbto1) ([raw file](https://github.com/RobotLocomotion/drake/blob/5b43b4608fd05016fe80fa802f5830f5c1ca3681/multibody/plant/hydroelastic_contact_info.h#L68)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

SGTM. For my own education, why not to deprecate in this PR? Is this used anywhere outside of our control?
</blockquote></details>

Because any keystrokes I type in this PR to add deprecation, will be rewritten from scratch in the next PR when I repave this whole class with a completely new API.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21683)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm` line 45 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21683#-O1IgypM7UO8j7DqgzQk:-O1Ira03-f1jBY5zs3Tj:b-ww6i92) ([raw file](https://github.com/RobotLocomotion/drake/blob/b128c7da9e064f1db3c08b0397ad44ca3278b4ca/lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://drake.mit.edu/stable.html#lcm-messages

In short, we could add new message `lcmt_hydroelastic_contact_surface_for_viz2` that doesn't have these fields.
</blockquote></details>

Yuck, no need to do that. Thanks
___
*[`multibody/plant/hydroelastic_contact_info.h` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21683#-O1A3fJi2zaFQywXi1_Y:-O1IrkSo-x_wm1WLFaXI:b757rz5) ([raw file](https://github.com/RobotLocomotion/drake/blob/5b43b4608fd05016fe80fa802f5830f5c1ca3681/multibody/plant/hydroelastic_contact_info.h#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Because any keystrokes I type in this PR to add deprecation, will be rewritten from scratch in the next PR when I repave this whole class with a completely new API.
</blockquote></details>

SGTM. Thanks.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 10 of 15 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21683#-:-O1IwJ2VBEPT3nx9nF09:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees amcastro-tri,SeanCurtis-TRI(platform)

**Pull request merged**
