### PR TITLE
 Deprecated Body.get_default_mass() in favor of Body.default_mass().

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17528)

### CODE REVIEW

**Comment by mitiguy** [comment]
Together, PR #17528 and PR #17472 resolve issue [17277](https://github.com/RobotLocomotion/drake/issues/17277).

**Comment by mitiguy** [comment]
@drake-jenkins-bot   linux-focal-clang-bazel-experimental-release    please

**Review by mitiguy — COMMENTED** [review]
Feature review +@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17528#-:-N6iJBtj647os5HrkQ6t:boi75d2)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm: 

+(release notes: newly deprecated) 
+@seancurtis-tri for platform review per rotation please.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17528#-:-N6jEXla8TeDZXxfHYVa:b6ft5ye)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @mitiguy and @SeanCurtis-TRI)

___
*[`multibody/tree/body.h` line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jDQTjA5NBPlvtQEHz:-N6jDQTjA5NBPlvtQEI-:b-rqnivb) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/multibody/tree/body.h#L342)):*
> ```objc
>   }
> 
> DRAKE_DEPRECATED("2022-06-01", "Use Body::default_mass()")
> ```

nit wrong deprecation date and weird (non)indenting.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Close, but you have a couple of very small hiccups.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17528#-:-N6jOiyS4Cl1xtejeBp2:bw46cf5)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @mitiguy and @xuchenhan-tri)

___
*[`multibody/tree/body.h` line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jDQTjA5NBPlvtQEHz:-N6jJx0F3Mek1Zw2Sp5O:b3qe7lx) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/multibody/tree/body.h#L342)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit wrong deprecation date and weird (non)indenting.
</blockquote></details>

FTR The correct date would be 2022-11-01
___
*[`multibody/tree/body.h` line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jNX7u2dwBtxPMJyVh:-N6jNX7u2dwBtxPMJyVi:b-ruiq7p) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/multibody/tree/body.h#L342)):*
> ```objc
>   }
> 
> DRAKE_DEPRECATED("2022-06-01", "Use Body::default_mass()")
> ```

Also, to be a proper deprecation, you should copy and paste the documentation for `default_mass()` (below) back up here as well. Otherwise, this will change how the doxygen for this deprecated method renders (and how the python docs appear as well).
___
*[`multibody/tree/body.h` line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jOJQk1rVrzXWz-618:-N6jOJQk1rVrzXWz-619:b-17xhbg) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/multibody/tree/body.h#L342)):*
> ```objc
>   }
> 
> DRAKE_DEPRECATED("2022-06-01", "Use Body::default_mass()")
> ```

Nit. Also use a terminal period.
___
*[`bindings/pydrake/multibody/tree_py.cc` line 299 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jKoazCggGt2WcJxC1:-N6jKoazCggGt2WcJxC2:bl9vdx4) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/bindings/pydrake/multibody/tree_py.cc#L299)):*
> ```cpp
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
>     constexpr char doc_get_default_mass_deprecated[] =
> ```

nit: You shouldn't have to (and more generally, just shouldn't) create a bespoke doc string as a result of deprecating.

After you fix your indentation problem in `body.h`, this will simply become:

```c++
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
    cls.def("get_default_mass",
        WrapDeprecated(
            cls_doc.get_default_mass.doc_deprecated, &Class::get_default_mass),
        cls_doc.get_default_mass.doc_deprecated);
#pragma GCC diagnostic pop  // pop -Wdeprecated-declarations
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17528)* status: 5 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @mitiguy and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jOsET9B5TJzN0jR3s:-N6jOsET9B5TJzN0jR3t:b5punuo) (no related file):*
What is the breaking change?

___

**Comment by SeanCurtis-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jOsET9B5TJzN0jR3s:-N6jP0rG8VbHnkyI-h-5:bi0baw0) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

What is the breaking change?
</blockquote></details>

Is it that `RigidBody::default_mass()` is now `final`?

**Comment by jwnimmer-tri** [comment]
*[`multibody/tree/body.h` line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jNX7u2dwBtxPMJyVh:-N6jP5YW3v1dQ7KTDDAP:bw85m6u) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/multibody/tree/body.h#L342)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Also, to be a proper deprecation, you should copy and paste the documentation for `default_mass()` (below) back up here as well. Otherwise, this will change how the doxygen for this deprecated method renders (and how the python docs appear as well).
</blockquote></details>

That advice is not accurate.  The correct documentation for a deprecated function is just the deprecation notice.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17528)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @mitiguy, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[`multibody/tree/body.h` line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jNX7u2dwBtxPMJyVh:-N6jPNEI1Wd6zrZMaRI4:b-kp6z4d) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/multibody/tree/body.h#L342)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That advice is not accurate.  The correct documentation for a deprecated function is just the deprecation notice.
</blockquote></details>

Retracted.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17528#-:-N6jc6ju-W7WCcsbTHE-:bmxilld)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @xuchenhan-tri)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17528)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @mitiguy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jOsET9B5TJzN0jR3s:-N6jmNJ72PWxkzZF8nDe:bm9o57a) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Riiiight. That's the problem with side-by-side. If I forget to look at both sides, I miss the deletion. Thanks.
</blockquote></details>

+(status: squashing now) 

___
___
*[`multibody/tree/body.h` line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jDQTjA5NBPlvtQEHz:-N6jSSTW5V8dF8k2Z1Df:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/multibody/tree/body.h#L342)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FTR The correct date would be 2022-11-01
</blockquote></details>

Done.
___
*[`multibody/tree/body.h` line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jOJQk1rVrzXWz-618:-N6jSpb86srKZ9kB2rHO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/multibody/tree/body.h#L342)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Nit. Also use a terminal period.
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/tree_py.cc` line 299 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17528#-N6jKoazCggGt2WcJxC1:-N6j_kgK-875eYksqwrx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f1fcb5d84e949fae7e4289725d118cb3b4500c9/bindings/pydrake/multibody/tree_py.cc#L299)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: You shouldn't have to (and more generally, just shouldn't) create a bespoke doc string as a result of deprecating.

After you fix your indentation problem in `body.h`, this will simply become:

```c++
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
    cls.def("get_default_mass",
        WrapDeprecated(
            cls_doc.get_default_mass.doc_deprecated, &Class::get_default_mass),
        cls_doc.get_default_mass.doc_deprecated);
#pragma GCC diagnostic pop  // pop -Wdeprecated-declarations
```
</blockquote></details>

Done.

**Pull request merged**
