### PR TITLE
refactors dircol to use the system2.0 classes more completely

### PR DESCRIPTION
**Pull request by RussTedrake**
including DoToAutoDiffXd.

moved trajectory_optimization to systems/trajectory_optimization (from solvers/trajectory_optimization) to avoid circular dependencies.  

+@Lucy-tri for feature review
+@sammy-tri for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4399)

### CODE REVIEW

**Comment by sammy-tri** [comment]
Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOvnCe6BDKKiX9xuyP:-KYOvnCfAeLccUoJ1-o4:b-wrp62m) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/examples/Pendulum/pendulum_run_swing_up.cc#L12)):*
> ```cpp
> #include "drake/multibody/parser_urdf.h"
> #include "drake/multibody/rigid_body_plant/drake_visualizer.h"
> // NOLINTNEXTLINE(whitespace/line_length)
> ```

It doesn't look like we need to hit anything about the next line to cpplint anymore?

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOuzVEC3Sx2dGsGNAI:-KYOuzVF9hpRvNXbH1Ni:b-rd7wo3) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation.cc#L15)):*
> ```cpp
>     double trajectory_time_lower_bound, double trajectory_time_upper_bound)
>     : systems::DirectTrajectoryOptimization(
>           system.get_num_total_inputs(), context.get_continuous_state()->size(),
> ```

the dynamic constraint uses only the size of input port 0 here...  It seems like one of them is incorrect?  (or num_inputs means different things in different places?)

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOuGFG7bnITI-qfkVi:-KYOuGFH21gHda1RpL7M:blcwomj) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation_constraint.h#L64)):*
> ```objc
> /// Implements a dynamic constraint which uses the continuous dynamics
> /// of a system.
> class System2DirectCollocationConstraint : public DirectCollocationConstraint {
> ```

BTW the "System2" spelling here vs "System" is a legacy of when both System1 and System2 versions coexisted in this file.  I don't think we need to rename it in this PR (or maybe ever), just a quick note about history.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399)*

**Comment by Lucy-tri** [comment]
Checkpoint. More to come.

---

Reviewed 11 of 38 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOxSQ48rToCXtw9wnJ:-KYOxSQ486id__TnWNLZ:b-5vhq5u) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation.h#L16)):*
> g·
Spaces at end of lines (in this area). This will fail Clang.
But many thanks for documentation!  Very helpful to me and others. 

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOzPei5JBI7Lbwq_08:-KYOzPei9_Gr8SCuT4fS:b3y4cvu) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation.h#L29)):*
> ```objc
>  *    after calling this method will NOT impact the trajectory optimization.
>  * @param context Required to describe any parameters of the system.  The
>  *    values of the state in this context do not have any effect.  This 
> ```

"The values of the state in this context do not have any effect. "
I don't know what you mean by "state" - you do use the state within the context.  What values?  And don't have any effect on what (this function?)?
Thanks again for adding doc: so useful :100: 

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYP2vnj7PjLQnEy1-XS:-KYP2vnj0RmokeJDg0h0:b-9t6ulx) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation_constraint.h#L73)):*
>  ///  values of the state in this context do not have any effect.  This
>  
"The values of the state in this context do not have any effect. "
I don't know what you mean by "state" - you do use the state within the context.  What values?  And don't have any effect on what (this function?)?

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOvNMU0FYu1RmuEnLo:-KYOvNMU4vfUAzL5lhVf:b-ng25u5) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L61)):*
> // Note: Derived classes should call AddDynamicConstraints() in their
>   // constructors.
I don't think anyone is going to see this comment here. Or maybe you are trying to say something different.  It could go in the header file, if it's not obvious. Maybe there should be a usage section there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-:-KYP4RiE5C4up7u8F3DV:bmtdbbl)*

**Comment by Lucy-tri** [comment]
Reviewed 27 of 38 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399)*

**Comment by Lucy-tri** [comment]
@naveenoid wanted to take a look.  Looks good to me with a few questions in my comments below. 

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-:-KYPbsvaBIsmC2y93lx-:b15iy9d)*

**Comment by RussTedrake** [comment]
Review status: 21 of 28 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOvnCe6BDKKiX9xuyP:-KYQIJf6ApbEUAV7ZygP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/examples/Pendulum/pendulum_run_swing_up.cc#L12)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It doesn't look like we need to hit anything about the next line to cpplint anymore?
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOuzVEC3Sx2dGsGNAI:-KYQIRgQ6rYXayRjHkKj:b-5ecxyp) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation.cc#L15)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

the dynamic constraint uses only the size of input port 0 here...  It seems like one of them is incorrect?  (or num_inputs means different things in different places?)
</blockquote></details>

i would say it differently.  the constraint only supports a single input (and throws if there is more than one).  this method will support more, if and when the constraint can handle it.  seem reasonable?

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOxSQ48rToCXtw9wnJ:-KYQImRu1gEVBgyqKtz7:bh7xu0a) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation.h#L16)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

> g·
Spaces at end of lines (in this area). This will fail Clang.
But many thanks for documentation!  Very helpful to me and others. 
</blockquote></details>

didn't actually fail cpplint... but corrected regardless

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOzPei5JBI7Lbwq_08:-KYQIx3a3tbutINhRkyp:b-iak7fv) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation.h#L29)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

"The values of the state in this context do not have any effect. "
I don't know what you mean by "state" - you do use the state within the context.  What values?  And don't have any effect on what (this function?)?
Thanks again for adding doc: so useful :100: 
</blockquote></details>

the context is time, state, and parameters.  the state is part of the context.  it has values.  but the values of the state variables, as passed in, have no effect on the optimization.

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOuGFG7bnITI-qfkVi:-KYQJ43701vjI90bsu2m:bi2z9uo) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation_constraint.h#L64)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW the "System2" spelling here vs "System" is a legacy of when both System1 and System2 versions coexisted in this file.  I don't think we need to rename it in this PR (or maybe ever), just a quick note about history.
</blockquote></details>

I was going to rename it (realized right after my last push).  will do it now.

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYP2vnj7PjLQnEy1-XS:-KYQJQjF57aGya8J8o9-:b-qw9iwq) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation_constraint.h#L73)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

>  ///  values of the state in this context do not have any effect.  This
>  
"The values of the state in this context do not have any effect. "
I don't know what you mean by "state" - you do use the state within the context.  What values?  And don't have any effect on what (this function?)?
</blockquote></details>

same as above.  not sure how to make it more clear??

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOvNMU0FYu1RmuEnLo:-KYQJttB2u-KEJ7UvBdG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L61)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

> // Note: Derived classes should call AddDynamicConstraints() in their
>   // constructors.
I don't think anyone is going to see this comment here. Or maybe you are trying to say something different.  It could go in the header file, if it's not obvious. Maybe there should be a usage section there?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399)*

**Comment by RussTedrake** [comment]
i think i've addressed everything... PTAL

**Comment by Lucy-tri** [comment]
:lgtm:   tho I have one wording suggestion in a comment, I don't want to hold it up. I pinged Naveen again to see if he wants to take a look.  It's good to see this getting some attention.

---

Reviewed 5 of 38 files at r1, 5 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOzPei5JBI7Lbwq_08:-KYR49wqj1PdWE5U7l7z:b5nzr37) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation.h#L29)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

the context is time, state, and parameters.  the state is part of the context.  it has values.  but the values of the state variables, as passed in, have no effect on the optimization.
</blockquote></details>

How about:
"The values of the context's state do not have any effect on the optimization."

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYP2vnj7PjLQnEy1-XS:-KYR4hKPHWPgLI-Tw22M:b5nzr37) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation_constraint.h#L73)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

same as above.  not sure how to make it more clear??
</blockquote></details>

How about:
"The values of the context's state do not have any effect on the optimization."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-:-KYR5h3MhvHANADKg7wf:b-9t0ufr)*

**Comment by naveenoid** [comment]
I am starting my review now. Thanks!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-:-KYSu42-QMFOmA3Zdk5X:b7rigjw)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 38 files at r1, 5 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOuzVEC3Sx2dGsGNAI:-KYTuMRsLHYLuE84B91V:b-80tlqk) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation.cc#L15)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i would say it differently.  the constraint only supports a single input (and throws if there is more than one).  this method will support more, if and when the constraint can handle it.  seem reasonable?
</blockquote></details>

Sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-:-KYTudGi8oswMd1S2lA1:bnfp4nl)*

**Comment by naveenoid** [comment]
:lgtm: Im good too.

---

Reviewed 7 of 38 files at r1, 1 of 7 files at r2, 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-:-KYU6O4foxMjYHP6yn7m:b-niymfk)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYOzPei5JBI7Lbwq_08:-KYU_O4ITkfZwVsATnn2:b-rsf8yd) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation.h#L29)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

How about:
"The values of the context's state do not have any effect on the optimization."
</blockquote></details>

Will make that change for my next PR.  (instead of hitting and waiting for the build servers yet again).

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4399#-KYP2vnj7PjLQnEy1-XS:-KYU_THCkGAwfrPshK3l:bb7od0r) ([raw file](https://github.com/robotlocomotion/drake/blob/c5883adcb9eb79a5e5e44cedf96210bc1472b753/drake/systems/trajectory_optimization/direct_collocation_constraint.h#L73)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

How about:
"The values of the context's state do not have any effect on the optimization."
</blockquote></details>

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4399)*

**Pull request merged**
