### PR TITLE
Move director app (and related stuff) into its own subdir

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5994)

### CODE REVIEW

**Comment by sammy-tri** [comment]
In an earlier f2f discussion, there was talk of moving the stuff which is only relevant for the director sample app into a subfolder.  Since I may bloat this even further if I extend the sample app to have a dual-arm example, now seemed like a good time to move the clutter out of the top level.

+@naveenoid for feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5994#-:-Kj4XKliK39P7Mutb-17:brq8gra)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5994#-:-Kj4YOUMIcdh7D2VHnLi:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5994#-:-Kj4Z_94wJRBTazeVYv3:b-ykw85)*

**Comment by sammy-tri** [comment]
-@jwnimmer-tri for platform review.  There's test code in director which refers to director_config.json in its previous location and I'm not sure what to do about it yet.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5994#-:-Kj4bcPjsuZ_GJJ2kVKk:b-r8keic)*

**Comment by sammy-tri** [comment]
+(status: do not merge) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5994#-:-Kj4bnlnUQZJ2dLVHPq-:b-91mz89)*

**Comment by sammy-tri** [comment]
Closing instead of modifying director.

**Pull request closed without merging**
