### PR TITLE
[lcm] Eschew LCM C++ API (use C instead)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17231.
See also #20115.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20116)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm_strong:  Much simpler!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20116#-:-Nd_W5yT-7Kn4a2FLvIW:bht6yiv)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20116#-Nd_UZ8W2gDHvwz2zcbu):*
nit: Mention the alternative, since most people don't know LCM's full API buffet.



_Suggestion:_
```
- 2500a1e: [lcm] Eschew LCM C++ API (use C API instead)
```
___
*[`lcm/drake_lcm.cc` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20116#-Nd_UtBiE_w44fTvoJ4t:-Nd_UtBiE_w44fTvoJ4u:b-k5q22l) ([raw file](https://github.com/RobotLocomotion/drake/blob/2500a1e31c11c96fc84a59e8582170bfe7569c30/lcm/drake_lcm.cc#L10)):*
> ```cpp
> 
> #include <glib.h>
> #include <lcm/lcm-cpp.hpp>
> ```

BTW:  Took me a while to figure out why this was still here -- that styleguide prohibition on forward declaration really proves its point!  :-)

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20116#-:-Nd_izIu5ZY_dkA4-xz2:b-1krawd)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20116#-:-Nda0bjU2Wcwjpm7WYbH:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sammy-tri(platform)

**Comment by RussTedrake** [comment]
After this commit, every bazel test I run in the manipulation repo that calls ApplyDefaultVisualization now fails with 
```
connect: Network is unreachable

No route to 246.127.42.142

LCM requires a valid multicast route.  If this is a Linux computer and is
simply not connected to a network, the following commands are usually
sufficient as a temporary solution:

   sudo ifconfig lo multicast
   sudo route add -net 224.0.0.0 netmask 240.0.0.0 dev lo

For more information, visit:
   http://lcm-proj.github.io/lcm/multicast_setup.html
```

**Comment by jwnimmer-tri** [comment]
For reference, a probably-relevant detail here is that Russ's repositories block all kernel `socket()` calls by default:

https://github.com/RussTedrake/htmlbook/blob/bbc905e270eb4ca58bf059c812555b5a52d752b5/tools/python/defs.bzl#L19-L22

This was supposed to be a behavior-neutral change, so I'm reverting in #20136 until I understand why it changed.

**Pull request merged**
