### PR TITLE
[multibody] Add testing for scalar promotion from double to AutoDiffXd

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Alternative to current code in #18399.

This now tests the behavior of interaction w/ scalar conversion, and confirms behavior fix in #18397.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18403)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks good to me! I guess I preferred inline testing b/c it's easier to visually verify that each accessor has representative scalar conversion testing. However, that was coupled to my perception on the odd mechanisms to get there (as you denoted in the PR)

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18403#-:-NIZDgde9WaV0CWBH6Kb:b-o0nc1z)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`multibody/plant/test/contact_properties_test.cc` line 257 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18403#-NIZDZwABhBNFIX6jvcJ:-NIZDZwABhBNFIX6jvcK:b-yxjbac) ([raw file](https://github.com/robotlocomotion/drake/blob/047938d09a9151ad568d7d4e94396a923afef872/multibody/plant/test/contact_properties_test.cc#L257)):*
> ```cpp
>   // Where we need to pass *scalar-typed* parameters (rather than just double),
>   // we need a bit more infrastructure to do the parameter prep work.
>   auto combined_hunt_crossley = [this](auto T_dummy, const auto& inspector) {
> ```

nit Looked better up until this usage `T_dummy`.

For full simplicity, consider hoisting to member function?

**Review by SeanCurtis-TRI — COMMENTED** [review]
I agree. Your approach was nice in terms of keeping the scalar check with the general test.

Given how simple this can be, I think I'm going to try one more version of this.  Stay tuned.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18403#-:-NIZPywn5gztaM-fMDWW:bud81c8)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`multibody/plant/test/contact_properties_test.cc` line 257 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18403#-NIZDZwABhBNFIX6jvcJ:-NIZPo7b1rkCilVovbUr:b-e64qp8) ([raw file](https://github.com/robotlocomotion/drake/blob/047938d09a9151ad568d7d4e94396a923afef872/multibody/plant/test/contact_properties_test.cc#L257)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Looked better up until this usage `T_dummy`.

For full simplicity, consider hoisting to member function?
</blockquote></details>

Hmm...I'd left anything that wasn't just a straight-up call intact. Turns out I needn't have done that. That's what I get for being lazy. No need to disrupt the simple pattern.

Now they are in declaration order without interruption.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18403)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Ok, R3 addresses comments on what was reviewd. R4 pushes the tests back into each APIs test block.

Take a look at the TODO I've added with an aspect of incompleteness in this test (note: your test probably had a similar problem whereever implicit conversion from double-valued quantity to ~AutoDiffXd`-valued quantities.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18403#-:-NIZSdDs7IBs_9gkQS-F:b-n3fdle)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Heck yeah! +@ericcousineau-tri :lgtm_strong: 
+@rpoyner-tri for platform review, please

\cc @amcastro-tri @xuchenhan-tri 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18403#-:-NIZmufCCEu9xSzmOEtr:btf0t5e)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/plant/test/contact_properties_test.cc` line 257 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18403#-NIZDZwABhBNFIX6jvcJ:-NIZmoVk3Axh121KYJ-G:b-ck9uq7) ([raw file](https://github.com/robotlocomotion/drake/blob/047938d09a9151ad568d7d4e94396a923afef872/multibody/plant/test/contact_properties_test.cc#L257)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Hmm...I'd left anything that wasn't just a straight-up call intact. Turns out I needn't have done that. That's what I get for being lazy. No need to disrupt the simple pattern.

Now they are in declaration order without interruption.
</blockquote></details>

Oooh, beautimous - take my money!

**Review by EricCousineau-TRI — COMMENTED** [review]
It OK if I close my PR, and we let this PR be the winner (change the title)?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18403#-:-NIZnAEKBN1XWYWhoDvo:b-gj9sto)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18403#-:-NIcUhja02Yi4NXIo1pv:bnfp4nl)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18403#-:-NIcagb_4Kwij6RFwCuB:b-safpmt)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
