### PR TITLE
Extracted and updated cleanup instructions.

### PR DESCRIPTION
**Pull request by liangfok**
Separated instructions on how to switch build systems and clean your workspace into their own sections.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2950)

### CODE REVIEW

**Comment by liangfok** [comment]
+@ggould-tri for feature review since you recently did a "comprehensive nuke"
+@sammy-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2950#-:-KNhHYkDiqw8yh56-0KJ:1958848831)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2950#-:-KNhJFhmoXaNswGFOIxJ:1417088721)*

**Comment by liangfok** [comment]
Thanks. Waiting on @ggould-tri for feature review.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2950#-:-KNhpY9UqQCgSwRc_Ibd:-838870397)*

**Comment by ggould-tri** [comment]
This appears correct to me, and corresponds to what worked for me today. :lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2950#-:-KNi1de2_2lLLcxsylLZ:-115433510)*

**Pull request merged**
