### PR TITLE
Add drake_export.h and use it in drakeCommon

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3671)

### CODE REVIEW

**Comment by sherm1** [comment]
The Windows side of this is always using `dllexport` and never `dllimport` (with performance consequences of unknown significance). But it seems functional. The code is still about equally ugly this way :-(. 

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_export.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-KTGWUuh5NVxseZaz9I6:-KTGWUuh5NVxseZaz9I7:b-o1o7pi) ([raw file](https://github.com/robotlocomotion/drake/blob/1805390b4c54d9e475b901ed36a0b4f9b9798d14/drake/common/drake_export.h#L11)):*
> ```objc
> #endif
> 
> #if defined(WIN32) || defined(WIN64)
> ```

BTW, `WIN32` is always defined on Windows; despite appearances it doesn't mean "32 bit". So just `#if defined(WIN32)` is enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-:-KTGXIH-ZIlYOlHmiTL-:bqjvz3c)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_export.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-KTGWUuh5NVxseZaz9I6:-KTH0iKFHmw0i0XmTs91:b-lujlb0) ([raw file](https://github.com/robotlocomotion/drake/blob/1805390b4c54d9e475b901ed36a0b4f9b9798d14/drake/common/drake_export.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `WIN32` is always defined on Windows; despite appearances it doesn't mean "32 bit". So just `#if defined(WIN32)` is enough.
</details>
FWIW, I just copied this from some CMake something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_export.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-KTGWUuh5NVxseZaz9I6:-KTHI7wNG3SbjlQmNDKW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1805390b4c54d9e475b901ed36a0b4f9b9798d14/drake/common/drake_export.h#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FWIW, I just copied this from some CMake something.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jwnimmer-tri** [comment]
Looking good in Jenkins.
+@david-german-tri and +@sherm1 for review -- can we stand to use this solution as a compromise for now?

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-:-KTHS482kbrVUF_cTW6D:bc6qdad)*

**Comment by jwnimmer-tri** [comment]
For the record, all of the opt-in builds passed.

(I am about to push an update that amends the doxygen configuration, so they are about to disappear).

**Comment by billhoffman** [comment]
So, 

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_export.h, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-KTKAhQESwKyoJ7Nw9jP:-KTKAhQESwKyoJ7Nw9jQ:b4pwvgm) ([raw file](https://github.com/robotlocomotion/drake/blob/e89099a8242c520928fa96ea25bd070cc4384325/drake/common/drake_export.h#L8)):*
> ```objc
> 
> /// A macro that marks symbols as exported with default visibility.
> #define DRAKE_EXPORT __attribute__((visibility("default")))
> ```

Can we at least put in an if block for compilers that do not support this?  The original idea would be that Windows support would not be removed and that Kitware would make a go at maintaining the Windows build.    This is a gcc'ism only and is not part of C++.   I think we can get shared libraries to work without the decoration using the cmake dll .def file creation code.  Maybe this should have a #if __GNUC__ >= 4 around it and define DRAKE_EXPORT to empty if it is not defined.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-:-KTKAcWWH5VGGIGdOkVi:bb7467p)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_export.h, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-KTKAhQESwKyoJ7Nw9jP:-KTKCMAKsm4T1pi53exc:bg1e66z) ([raw file](https://github.com/robotlocomotion/drake/blob/e89099a8242c520928fa96ea25bd070cc4384325/drake/common/drake_export.h#L8)):*
<details><summary><i>Previously, billhoffman (Bill Hoffman) wrote…</i></summary>
> Can we at least put in an if block for compilers that do not support this?  The original idea would be that Windows support would not be removed and that Kitware would make a go at maintaining the Windows build.    This is a gcc'ism only and is not part of C++.   I think we can get shared libraries to work without the decoration using the cmake dll .def file creation code.  Maybe this should have a #if __GNUC__ >= 4 around it and define DRAKE_EXPORT to empty if it is not defined.  
</details>
The "Kitware has a go at maintaining Windows support" was shot down by Russ after we discussed it internally.  I thought that message had already percolated over to you folks, but apologies if it has not!

If CI passes in our supported platforms, I frankly don't care about a compiler guard.  But if, after this PR, someone wants to PR a guard that is enabled for gcc and clang, we could discuss its merits at that point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_export.h, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-KTKAhQESwKyoJ7Nw9jP:-KTKHvqOT4IMPld5LKWx:bg511f5) ([raw file](https://github.com/robotlocomotion/drake/blob/e89099a8242c520928fa96ea25bd070cc4384325/drake/common/drake_export.h#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The "Kitware has a go at maintaining Windows support" was shot down by Russ after we discussed it internally.  I thought that message had already percolated over to you folks, but apologies if it has not!
> 
> If CI passes in our supported platforms, I frankly don't care about a compiler guard.  But if, after this PR, someone wants to PR a guard that is enabled for gcc and clang, we could discuss its merits at that point.
</details>
As is, this change will *break all Windows builds*. Is it intended that we are actively removing Windows support?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/drake_export.h, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-KTKAhQESwKyoJ7Nw9jP:-KTKcGCiY_MJk4Mb4z0w:bb77ufg) ([raw file](https://github.com/robotlocomotion/drake/blob/e89099a8242c520928fa96ea25bd070cc4384325/drake/common/drake_export.h#L8)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> As is, this change will *break all Windows builds*. Is it intended that we are actively removing Windows support?
</details>
Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671)*

**Comment by sammy-tri** [comment]
+@sammy-tri at author's request

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-:-KTKedrRaCew6asTI8SJ:bjqb4ci)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/drake_export.h, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-KTKAhQESwKyoJ7Nw9jP:-KTKf-QpvG_1VV7PO_XW:bjvqtxy) ([raw file](https://github.com/robotlocomotion/drake/blob/e89099a8242c520928fa96ea25bd070cc4384325/drake/common/drake_export.h#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Yes.
</details>
FYI David is preparing a separate PR to update the sphinx documentation to reflect that choice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671)*

**Comment by sammy-tri** [comment]
:lgtm:  I continue to have mixed feelings, but I believe that this PR represents current consensus.

---

Reviewed 9 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-:-KTKh2RoKItLEL0PaQdn:bl6gv10)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-:-KTKjA6xQcMkW0zPkdzg:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
-@sherm1.

I'm happy to take further comments, either here or slack or whatever, but going to move forward with this merge to unblock other work.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3671#-:-KTKnBJUeJ_WMylNBmM1:b-kfy94m)*

**Pull request merged**
