### PR TITLE
Adjust test tolerance for GraphOfConvexSetsTest

### PR DESCRIPTION
**Pull request by RussTedrake**
+@BetsyMcPhail for review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19801)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-weekly-gurobi-valgrind-memcheck please

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19801#-:-N__48qg6tycULEdFrLR:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by BetsyMcPhail** [comment]
The `experiemental` version should work:

@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-valgrind-memcheck please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19801#-:-N_dgsAK6WSTH00uVlHy:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail

**Comment by rpoyner-tri** [comment]
-(release notes: fix)  +(release notes: none)

**Pull request merged**
