### PR TITLE
Re-organize drake/thirdParty based on license

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Big picture:
- Move thirdParty files to subdirectories based on their license.
- Add README.md files to clarify thirdParty copyright status.
- Remove unused pathmcp.

Note that this doesn't actually fix any license problems, just makes them evident.  That will be in follow-up PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2776)

### CODE REVIEW

**Comment by liangfok** [comment]
What is the "path" license? Why isn't there a README.md in `drake/thirdParty/path/`?

---

Reviewed 141 of 141 files at r1.
Review status: 76 of 81 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/thirdParty/README.md, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-KMQ1TyM3ohGI3NxjiE7:-KMQ1TyNvy25z_AucDS-:-21848398) ([raw file](https://github.com/robotlocomotion/drake/blob/41b69c9a594014b150d8571ee1d47f64a2071340/drake/thirdParty/README.md#L2)):*
> ```Markdown
> The thirdParty subdirectory within Drake contains software that is distributed
> alongside Drake, but has different copyright ownership and licence terms than
> ```

typo: license

---

*[drake/thirdParty/README.md, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-KMQ1ZXuun7_bP0VUDO8:-KMQ1ZXuun7_bP0VUDO9:-1249441820) ([raw file](https://github.com/robotlocomotion/drake/blob/41b69c9a594014b150d8571ee1d47f64a2071340/drake/thirdParty/README.md#L4)):*
> ```Markdown
> alongside Drake, but has different copyright ownership and licence terms than
> the rest of Drkae.  The software is grouped into subdirectories based on its
> license terms.
> ```

Consider plural: "The software packages are grouped into subdirectories based on their license terms."

---

*[drake/thirdParty/bsd/README.md, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-KMQ1irV1dEgFMJXv50c:-KMQ1irV1dEgFMJXv50d:-222914782) ([raw file](https://github.com/robotlocomotion/drake/blob/41b69c9a594014b150d8571ee1d47f64a2071340/drake/thirdParty/bsd/README.md#L3)):*
> ```Markdown
> See README.md in the parent diretory for an overview.
> 
> Software in this directory is licensed under either the BSD license,
> ```

Extra "either" before "the"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-:-KMQ2gBRkVQML8dLArfP:-738036426)*

**Comment by jwnimmer-tri** [comment]
I believe that directory has been removed by this PR?  (New location: thirdParty/misc/pathlcp.)

---

Review status: 76 of 81 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/thirdParty/README.md, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-KMQ1TyM3ohGI3NxjiE7:-KMQ3Wkp3pmSWbovR2Td:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/41b69c9a594014b150d8571ee1d47f64a2071340/drake/thirdParty/README.md#L2)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> typo: license
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-:-KMQ4-KkmqD7b7jxEPJP:896084563)*

**Comment by liangfok** [comment]
I'm seeing the following files in this PR in `drake/thirdParty/path/`:



---

Review status: 76 of 81 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-:-KMQ4fZ0NSa03cyk-5v2:1602016501)*

**Comment by jwnimmer-tri** [comment]
Yup.  The pink background indicates a deleted file, which is also confirmed by the https://github.com/RobotLocomotion/drake/pull/2776/files pull-down list of files.

---

Review status: 76 of 81 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-:-KMQ5FKIy2bqrKC2Y_Lu:-1527436885)*

**Comment by liangfok** [comment]
Oh OK, sorry, I was misreading Reviewable's color labeling.

---

Review status: 76 of 81 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-:-KMQ5gDx6eNGogyVGVbN:1734619711)*

**Comment by jwnimmer-tri** [comment]
However unlikely, this PR has passed jenkins the very first time around.  Unbelievable!

+@liangfok for feature review.
+@sherm1 for platform review.

**Comment by jwnimmer-tri** [comment]
Review status: 75 of 81 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/thirdParty/README.md, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-KMQ1ZXuun7_bP0VUDO8:-KMQ80s5QNU9mckVklCe:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/41b69c9a594014b150d8571ee1d47f64a2071340/drake/thirdParty/README.md#L4)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Consider plural: "The software packages are grouped into subdirectories based on their license terms."
</details>
Done.

---

*[drake/thirdParty/bsd/README.md, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-KMQ1irV1dEgFMJXv50c:-KMQ7cq1mnBzdLRszL10:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/41b69c9a594014b150d8571ee1d47f64a2071340/drake/thirdParty/bsd/README.md#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Extra "either" before "the"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2776)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 3 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-:-KMQ8Zxoek5NF-pLG5yR:-1868698381)*

**Comment by jwnimmer-tri** [comment]
/CC @RussTedrake you may want to look at the `drake/thirdParty/misc/pathlcp/README.md` wording in this PR.  I am happy to take any amendments if they arrive before this merges, otherwise you can post them and I'll do a new PR, or you can submit your own.

**Comment by sherm1** [comment]
I like this idea, with one concern: this should not be the *only* way that non-viral open source code can be used in Drake. One of the great things about bsd-, mit-, zlib-, and apache-licensed code is that you can snatch pieces of it and use it as you see fit. For example, I grabbed a little chunk of apache-licensed code that knows how to process typeid.name() into human readable form on various platforms and used it to make NiceTypeName. It would be very awkward (and completely unnecessary) to isolate that into a separate directory. However, I do like the `thirdParty/license` approach for complete 3rd-party code where we would have wanted to put that code in its own directory anyway. And it is essential for any badly-licensed code (god forbid) that we may be using in Drake.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-:-KMQFzJw8TELP7_VKssQ:-675783174)*

**Comment by jwnimmer-tri** [comment]
I actually disagree -- I think that all code not owned by "The Drake Authors" should be segregated in the source tree from the code owned by "The Drake Authors" (though perhaps not necessarily forced to be in `drake-distro/drake/thirdParty`).  But I think we can have that battle in a separate PR.  I think we agree that this `thirdParty` mechanism is good and should exist for full libraries like we have now.

Does that mean this PR is Platform LGTM?

**Comment by sherm1** [comment]
> Does that mean this PR is Platform LGTM?

Yep. :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2776#-:-KMQeockvOmzVw8xmqaw:-594030452)*

**Pull request merged**
