### PR TITLE
"Clean up" wheel scripts

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add slightly more strict error checking to the various Wheel scripts. It's unlikely this will actually catch anything "new", but it's mostly being done to increase consistency across various scripts of this nature, particularly with the (still in progress, as of writing) refactoring work being done to the VTK scripts.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16260)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature +(release notes: none).

+@ggould-tri for platform review per schedule, please.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16260#-:-MrO3j0H1l1qpfh_EuiA:b-b8c91y)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16260#-:-MrO7MIH7HYFoxTyx564:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16260#-MrO7MloDDg_DQXahTP7:-MrO7MloDDg_DQXahTP8:bls5c9f) (no related file):*
BTW:  I was going to make a nit comment about consistent formatting, but git convinced me otherwise:
```
$ git grep -h 'set -e' | sort | uniq -c
     10 set -e
      1 set -e -u
      2 set -e -u -o pipefail
      1 set -eu -o pipefail
      6 set -euo pipefail
      2 set -eux
      8 set -euxo pipefail
      3 set -ex
```
:laughing: :cry: 

---

**Pull request merged**
