### PR TITLE
Pose Extractor modifications

### PR DESCRIPTION
**Pull request by naveenoid**
Converts the output to use an Isometry3<double> on an AbstractOutputPort, updates the test and includes some other minor changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6875)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@sammy-tri for feature review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-:-Ks4W1adqau11AD0rN3m:bp61js4)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4hxHys0OjvIOys1qE:-Ks4hxHzUCuAEHSRRZfr:bf353mr) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L25)):*
> ```cpp
>     : object_id_(object_id),
>       measured_pose_output_port_{
>           this->DeclareAbstractOutputPort(
> ```

BTW this could still be a vector valued output port if it used PoseVector.  I have no idea if that's particularly desiraable...   Since we're extracting values from an LCM message I don't think support for other scalar types is a compelling feature, anyway...  (or what the intented use is for systems::rendering in general).

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4izg0tbSBB_aaQDIO:-Ks4izg1CQHDQuvZj9Eg:b4lmov8) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L36)):*
> ```cpp
> 
> std::unique_ptr<systems::AbstractValues>
> OptitrackPoseExtractor::AllocateAbstractState() const {
> ```

Could this overload (and possibly also `SetDefaultState` be replaced with calling `DeclareAbstractState` in the constructor like https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/test/leaf_system_test.cc#L582 ?

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4jam810vTNSF6mD-c:-Ks4jam810vTNSF6mD-d:b-t5qbbh) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L85)):*
> ```cpp
>       rigid_bodies[vector_index].quat[1], rigid_bodies[vector_index].quat[2]);
> 
>   drake::log()->info(
> ```

Info seems like a very verbose log level for a message which might be received at up to 360hz.

---

*[drake/manipulation/perception/test/optitrack_pose_extractor_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4k5ylbz367Mmx92yk:-Ks4k5ylbz367Mmx92yl:b-8y15xg) ([raw file](https://github.com/robotlocomotion/drake/blob/eec9c787e2f54f90c7c05c6a304276337a35bc7c/drake/manipulation/perception/test/optitrack_pose_extractor_test.cc#L80)):*
> ```cpp
>   Initialize(1 /* object_id */);
>   optitrack::optitrack_frame_t test_frame{};
>   optitrack::optitrack_rigid_body_t default_body{};
> ```

I'm not sure why these lost their `{}`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-:-Ks4kDyCwJj8PAasrCBy:bvb1a6z)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4hxHys0OjvIOys1qE:-Ks4t4fUDsj7h3tWYnb_:b-tlvsyl) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L25)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this could still be a vector valued output port if it used PoseVector.  I have no idea if that's particularly desiraable...   Since we're extracting values from an LCM message I don't think support for other scalar types is a compelling feature, anyway...  (or what the intented use is for systems::rendering in general).
</blockquote></details>

Actually it seems more likely  to me that some day `GeometryFrame` will be the answer.  This implementation is fine with me for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875)*

**Comment by naveenoid** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4hxHys0OjvIOys1qE:-Ks5uclGaitKOZ_Q_9ul:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L25)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Actually it seems more likely  to me that some day `GeometryFrame` will be the answer.  This implementation is fine with me for now.
</blockquote></details>

Done.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4izg0tbSBB_aaQDIO:-Ks5zj-iq7QMwyZtY7Dj:b-mmo8y0) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L36)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Could this overload (and possibly also `SetDefaultState` be replaced with calling `DeclareAbstractState` in the constructor like https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/test/leaf_system_test.cc#L582 ?
</blockquote></details>

Done, excellent suggestion!

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4jam810vTNSF6mD-c:-Ks5zsIwpFITOlc_37b9:borv1vy) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L85)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Info seems like a very verbose log level for a message which might be received at up to 360hz.
</blockquote></details>

Done. Leftover from a debug session.

---

*[drake/manipulation/perception/test/optitrack_pose_extractor_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4k5ylbz367Mmx92yk:-Ks6-WwhL9O3i5tUqbs_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eec9c787e2f54f90c7c05c6a304276337a35bc7c/drake/manipulation/perception/test/optitrack_pose_extractor_test.cc#L80)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure why these lost their `{}`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review (I'm today's on-call, so punting to tomorrow's) :lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-:-Ks9CJlZCjg6d1wiIPDE:bmslaf0)*

**Comment by ggould-tri** [comment]
Nice, this seems much clearer to me.
:lgtm:, nits below.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks9hoogRHjil3Mk5qTN:-Ks9hoogRHjil3Mk5qTO:b-1rzip0) ([raw file](https://github.com/robotlocomotion/drake/blob/63f218e2141f3bbd036789745dbc376282742389/drake/manipulation/perception/optitrack_pose_extractor.cc#L34)):*
> ```cpp
>           Isometry3<double>::Identity()));
>   this->DeclareAbstractInputPort();
>   // Internal state is an Isometry3d
> ```

FYI punctuate complete sentence.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks9hvm5gffLjy6KuLQh:-Ks9hvm5gffLjy6KuLQi:b-m5vdug) ([raw file](https://github.com/robotlocomotion/drake/blob/63f218e2141f3bbd036789745dbc376282742389/drake/manipulation/perception/optitrack_pose_extractor.cc#L46)):*
> ```cpp
>       state->get_mutable_abstract_state<Isometry3<double>>(0);
> 
>   /* Update world state from inputs. */
> ```

FYI mix of `/**/` and `//`-style comments; style guide prefers consistency.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks9jPUAAKIVK2QgScBw:-Ks9jPUAAKIVK2QgScBx:b-wcresp) ([raw file](https://github.com/robotlocomotion/drake/blob/63f218e2141f3bbd036789745dbc376282742389/drake/manipulation/perception/optitrack_pose_extractor.cc#L68)):*
> ```cpp
> 
>   // The optitrack quaternion ordering is X-Y-Z-W and this needs fitting into
>   // Eigens W-X-Y-Z ordering.
> ```

FYI typo, `Eigens` should have an apostrophe.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-:-Ks9jbvWxvJmeR6vrcRD:b-1854xc)*

**Comment by naveenoid** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks9hoogRHjil3Mk5qTN:-KsAfZ5IH8JaZIV6Ezo0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63f218e2141f3bbd036789745dbc376282742389/drake/manipulation/perception/optitrack_pose_extractor.cc#L34)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI punctuate complete sentence.
</blockquote></details>

Done.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks9hvm5gffLjy6KuLQh:-KsAfbQXL1z8SHCdatcL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63f218e2141f3bbd036789745dbc376282742389/drake/manipulation/perception/optitrack_pose_extractor.cc#L46)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI mix of `/**/` and `//`-style comments; style guide prefers consistency.
</blockquote></details>

Done.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks9jPUAAKIVK2QgScBw:-KsAfe_QBXaqndMncY6t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63f218e2141f3bbd036789745dbc376282742389/drake/manipulation/perception/optitrack_pose_extractor.cc#L68)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo, `Eigens` should have an apostrophe.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875)*

**Comment by sammy-tri** [comment]
:lgtm_cancel: it looks like some changes were reverted?  I started calling them out individually below but didn't bother with all of them.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4izg0tbSBB_aaQDIO:-KsEPXZQ4H2wmRgYxtGf:b-jvlh7k) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L36)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done, excellent suggestion!
</blockquote></details>

Did this somehow get reverted in the current iteration of this PR?  That's what reviewable seems to be showing me...

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4jam810vTNSF6mD-c:-KsEPh8ULVaP-kPJX48q:bitz9jc) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L85)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done. Leftover from a debug session.
</blockquote></details>

This code appears to be back?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-:-KsEPjj_9RrgWOt7sIlU:b-4uq1eg)*

**Comment by naveenoid** [comment]
Merge error. Fixing now.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-:-KsESkbHz9G5MUwDv7hr:bsvqe8u)*

**Comment by naveenoid** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4izg0tbSBB_aaQDIO:-KsESszKGD6w-LTYiYB_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L36)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Did this somehow get reverted in the current iteration of this PR?  That's what reviewable seems to be showing me...
</blockquote></details>

Done.

---

*[drake/manipulation/perception/optitrack_pose_extractor.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-Ks4jam810vTNSF6mD-c:-KsEStyROtq5-yaqx9by:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e6b6c339b2a98e8fe55be81a018d17c09ebebbf/drake/manipulation/perception/optitrack_pose_extractor.cc#L85)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This code appears to be back?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875)*

**Comment by sammy-tri** [comment]
:lgtm: +(status: curate commits before merging) 

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-:-KsEYQNC53t27U7FXv0f:b-pu9q93)*

**Comment by naveenoid** [comment]
-(status: curate commits before merging) 

moving to squash and merge.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6875#-:-KsE_n72zAcOlEker6GX:b7eufhk)*

**Pull request merged**
