### PR TITLE
Add Image class and the unit test

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
I implemented Image data format to be used as system output by camera simulators.

+@david-german-tri as feature reviewer and +@sammy-tri as platform reviewer, PTAL.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4904)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/sensors/CMakeLists.txt, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbLsqr9iDmA-WS4TCNo:-KbLsqr9iDmA-WS4TCNp:biwvyop) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/CMakeLists.txt#L20)):*
> ```CMake
> 
> add_library_with_exports(LIB_NAME drakeSensors SOURCE_FILES
>     ${drakeSensors_SRC_FILES} image.h)
> ```

Why is this necessary?

---

*[drake/systems/sensors/image.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM5tg0kvBL8I2T4My6:-KbM5tg0kvBL8I2T4My7:b-1se4nz) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L19)):*
> ```objc
> ///
> /// @ingroup sensor_systems
> template <typename T, int channel>
> ```

Why is `channel` a template parameter?

---

*[drake/systems/sensors/image.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM5673nNFQZ9_bVqyQ:-KbM5674yZn4TZ_F6Lem:b-f8c7jq) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L29)):*
> ```objc
>   Image(int width, int height) : width_(width), height_(height),
>                                  data_(width * height * channel, 0) {
>     DRAKE_ASSERT(width > 0);
> ```

This can delegate to the other constructor.

---

*[drake/systems/sensors/image.h, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM6cK-kv1MZUe1P1ed:-KbM6cK-kv1MZUe1P1ee:bea5fud) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L110)):*
> ```objc
>   /// uint8_t blue  = image.at(x, y)[2];
>   /// uint8_t alpha = image.at(x, y)[3];
>   T* at(int x, int y) {
> ```

This bare pointer access is frightening.  Please consider taking `channel` as an argument instead.

---

*[drake/systems/sensors/image.h, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM7-lOXbaWDvqm2rTg:-KbM7-lP6P_LexKLXJnj:bea5fud) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L118)):*
> ```objc
>   /// Const version of at() method.  See the document for the non-const version
>   /// for the detail.
>   const T* at(int x, int y) const {
> ```

This bare pointer access is frightening.  Please consider taking `channel` as an argument instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Comment by david-german-tri** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/sensors/CMakeLists.txt, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbMInMSOknxIROea-uk:-KbMInMTW-4d3HPo5891:b-ixfg3t) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/CMakeLists.txt#L11)):*
> ```CMake
>     depth_sensor_output.h
>     depth_sensor_specification.h
>     image.h
> ```

BTW namespacing for the class itself and include paths for this file should save us...  but "image.h" and Image feel to me a bit like we're risking a collision with another library.  maybe drake_image/DrakeImage?  (feel free to ignore, nitpicking at names for things is too easy sometimes)

---

*[drake/systems/sensors/image.h, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM6cK-kv1MZUe1P1ed:-KbMLhIm8-0dVyhU5bnY:b-wz5j39) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L110)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This bare pointer access is frightening.  Please consider taking `channel` as an argument instead.
</blockquote></details>

BTW I don't think it's that terrifying, at least in the const version.  Is the idea with the non-const version that each pixel is set in a loop of at() calls?  I could see doing block access with at() but I suspect that would frighten David even further.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Comment by kunimatsu-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/sensors/CMakeLists.txt, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbMInMSOknxIROea-uk:-KbMPnY4mxcoR555ZLSp:b-2ho2yd) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/CMakeLists.txt#L11)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW namespacing for the class itself and include paths for this file should save us...  but "image.h" and Image feel to me a bit like we're risking a collision with another library.  maybe drake_image/DrakeImage?  (feel free to ignore, nitpicking at names for things is too easy sometimes)
</blockquote></details>

Thanks for the suggestion.

Regarding class name, perhaps, it would be nice to be consistent with other cases like Trajectory (it's not DrakeTrajectory), and so let me leave Image as-is for now.

Regarding include path, I assume image.h will be put under drake/systems/sensors directory, so it should be OK. If my assumption is wrong or I'm missing something, please point it out.

I understand the importance of naming and it's sometimes hard to put the appropriate name from various aspects by my own.
So, I appreciate your comment and please feel free to point out from now on too.

---

*[drake/systems/sensors/CMakeLists.txt, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbLsqr9iDmA-WS4TCNo:-KbMCj1hD58Jl7ubHDXH:b8waply) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/CMakeLists.txt#L20)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

That was just my misunderstanding. will remove.

---

*[drake/systems/sensors/image.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM5tg0kvBL8I2T4My6:-KbMMt4XvkDFdylf0m5y:b-thcjqh) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L19)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Why is `channel` a template parameter?
</blockquote></details>

will replace with member variable. At first, I was thinking doing like typedef Pixel array<T, channel> in the class, but changed my mind and mistakenly left this.

---

*[drake/systems/sensors/image.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM5673nNFQZ9_bVqyQ:-KbMO5b17CLNEerDxCKa:b-dm5pei) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L29)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This can delegate to the other constructor.
</blockquote></details>

will do so.

---

*[drake/systems/sensors/image.h, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM6cK-kv1MZUe1P1ed:-KbMT33sKkDxlQyTrSoZ:bqifb8n) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L110)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I don't think it's that terrifying, at least in the const version.  Is the idea with the non-const version that each pixel is set in a loop of at() calls?  I could see doing block access with at() but I suspect that would frighten David even further.
</blockquote></details>

I was thinking to call at() in a loop to get/set value to each pixel.

If I would replace the bare pointer with T&, then your concern would disappear?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/image.h, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM6cK-kv1MZUe1P1ed:-KbMWngWxatnrdEVTC7k:bkgbxf6) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L110)):*
> get/set value to each pixel.

get/set value from/to each pixel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/sensors/image.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbMcWiD9MtaJ8sFhENo:-KbMcWiD9MtaJ8sFhENp:bz8h10g) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L91)):*
> ```objc
>   /// Change the sizes of the width and height for the image.  The values for
>   /// them should be greater than zero.
>   void resize(int width, int height) {
> ```

BTW should this also zero out the data?

---

*[drake/systems/sensors/image.h, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM6cK-kv1MZUe1P1ed:-KbMaCeu54qEjsFnYLoX:b-2cyc7o) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L110)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

> get/set value to each pixel.

get/set value from/to each pixel.
</blockquote></details>

Having thought about this some more, I'll withdraw my comment.

---

*[drake/systems/sensors/test/image_test.cc, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbMcbVUMKbhmClhD9XG:-KbMcbVUMKbhmClhD9XH:bujtfn) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/test/image_test.cc#L141)):*
> ```cpp
>   const int kHeightResized = 48;
>   ::testing::FLAGS_gtest_death_test_style = "threadsafe";
>   ASSERT_DEATH(dut.resize(kInvalidWidth, kHeightResized), ".*");
> ```

We try to avoid death tests in Drake.  Please either throw an exception and test that, or just don't test these behaviors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Comment by kunimatsu-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/sensors/image.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbMcWiD9MtaJ8sFhENo:-KbMdbe5Fqo1rzf9Xi0e:b-dm5pei) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L91)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW should this also zero out the data?
</blockquote></details>

will do so.

---

*[drake/systems/sensors/image.h, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM6cK-kv1MZUe1P1ed:-KbMdRiY3mAryYcFy1id:b-4hvi0z) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L110)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Having thought about this some more, I'll withdraw my comment.
</blockquote></details>

Got it!

---

*[drake/systems/sensors/test/image_test.cc, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbMcbVUMKbhmClhD9XG:-KbMdIUc26Q4NTsQN5nF:b-8w3nx0) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/test/image_test.cc#L141)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

We try to avoid death tests in Drake.  Please either throw an exception and test that, or just don't test these behaviors.
</blockquote></details>

will remove death tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Comment by kunimatsu-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/CMakeLists.txt, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbLsqr9iDmA-WS4TCNo:-KbMknQdR_B2Isz282OO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/CMakeLists.txt#L20)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

That was just my misunderstanding. will remove.
</blockquote></details>

Done.

---

*[drake/systems/sensors/image.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM5tg0kvBL8I2T4My6:-KbMkowcKTWuRjcDHaTB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L19)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

will replace with member variable. At first, I was thinking doing like typedef Pixel array<T, channel> in the class, but changed my mind and mistakenly left this.
</blockquote></details>

Done.

---

*[drake/systems/sensors/image.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbM5673nNFQZ9_bVqyQ:-KbMkq9FGKfHzNVKRhGY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L29)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

will do so.
</blockquote></details>

Done.

---

*[drake/systems/sensors/image.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbMcWiD9MtaJ8sFhENo:-KbMkquzhn4z3wA7olhT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/image.h#L91)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

will do so.
</blockquote></details>

Done.

---

*[drake/systems/sensors/test/image_test.cc, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-KbMcbVUMKbhmClhD9XG:-KbMkyNV9qEGmFRsPU6o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a52a71704d22750f0784b780548c26101793dd49/drake/systems/sensors/test/image_test.cc#L141)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

will remove death tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Comment by kunimatsu-tri** [comment]
Addressed all the reviewers' comments. PTAL.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-:-KbMl8b_duLMC49m3Yd9:b-ddye1a)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-:-KbQOtVcfMJuUltir8U2:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:, but CI has some complaints

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-:-KbQxy50Yg9BzdYQangt:bqrw3bs)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904#-:-KbR3lPo2PqEcTaDCfz2:bg0xcbm)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4904)*

**Pull request merged**
