### PR TITLE
Simplify drake build

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Simplify drake external project. Normalize build wrapping, requiring use of a Makefile generator. This should allow `make -j[N]` to actually build drake itself in parallel (fixing #1641).

### CODE REVIEW

**Comment by RussTedrake** [comment]
it looks like this also works on windows, even though we do not use a Makefile generator...?

**Comment by mwoehlke-kitware** [comment]
> it looks like this also works on windows, even though we do not use a Makefile generator...?

Do you use the root `Makefile` on Windows? Or do you manually invoke CMake?

The former can't work (not easily, at least) for other generators... it would require that the `Makefile` itself retains knowledge of what generator is used.

**Comment by mwoehlke-kitware** [comment]
Clarification:

> The former can't work [...]

...unless it uses `cmake --build` (as before this PR), which leads to #1641.

**Comment by RussTedrake** [comment]
we use the former (root Makefile) on Windows, too.

**Comment by RussTedrake** [comment]
but could potentially revisit that.

**Comment by mwoehlke-kitware** [comment]
> we use the former (root Makefile) on Windows, too

Hmm... interesting why that would work, then. The root `Makefile` should be using the default generator. On not-Windows, that's "Unix Makefiles", so it's more or less safe to assume we can use `$(MAKE)` to drive the builds. Not sure what's happening on Windows (I don't have a Windows build).

Or did you mean "it looks like this also works on windows" as a question, not an observation?

**Comment by RussTedrake** [comment]
We set a CMAKE_FLAGS environment variable which sets the generator.

**Comment by RussTedrake** [comment]
my earlier comment was "wow.  it seems to have passed the windows build server tests".  but i think the windows build servers are calling cmake directly.  i just tested locally, and indeed this breaks the existing workflow (which may admittedly be flawed):

```
Russ Tedrake@WIN-3BHCRIPNMMH MINGW64 /z/russt/drake-distro-win (mwoehlke-kitware-simplify-drake-build)
$ make
Configuring with CMAKE_FLAGS: -G Visual Studio 14 2015 Win64 -DCMAKE_BUILD_TYPE=Release
-- CMAKE_INSTALL_PREFIX=Z:/russt/drake-distro-win/build
-- Preparing to build cmake with dependencies:
-- Preparing to build eigen with dependencies:
-- Preparing to build gtk with dependencies:
-- Preparing to build lcm with dependencies: gtk
-- Preparing to build spotless with dependencies:
-- Preparing to build swigmake with dependencies:
-- Preparing to build drake with dependencies: cmake;eigen;lcm;swigmake
-- Preparing to install precompiled snopt
-- Configuring done
-- Generating done
-- Build files have been written to: Z:/russt/drake-distro-win/pod-build
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [all] Error 2
```

**Comment by RussTedrake** [comment]
If we agree that this is the only fix for re-enabling `make -j`, then I think we need to update the wiki instructions for installation on windows, telling people to manually create the pod-build directory and call cmake.  @billhoffman recommended that we do this for another reason -- most people who are comfortable with the visual studio workflow will actually be happier with this (calling make at the command line is not the normal workflow for them).

**Comment by mwoehlke-kitware** [comment]
> I think the windows build servers are calling cmake directly. I just tested locally, and indeed this breaks the existing workflow.

Okay, thanks for the information. That's about what I expected, in both cases.

I redid the middle commit so that the changes only affect not-Windows. Windows (when using NMake or VS generators) has its own setup for parallel builds anyway, so the change probably isn't helpful there. This should avoid breaking anything on Windows.

> If we agree that this is the only fix for re-enabling make -j, then I think we need to update the wiki instructions for installation on windows [...]. @billhoffman recommended that we do this for another reason -- most people who are comfortable with the visual studio workflow will actually be happier with this (calling make at the command line is not the normal workflow for them). 

That may be a good idea anyway for the reason mentioned. (Personally, I'd love if this happened for *every* platform. The preferred way to build a CMake-based project is:

- Create a build directory (anywhere)
- `cmake -G"Your Favorite Generator" path/to/source`
- Invoke chosen build tool

Related, if build times are a concern, it might be interesting to look at using ninja instead of make.)

**Comment by RussTedrake** [comment]
I’d like to continue to support the “cd and run make” use case, because that is
where we can from (part of the PODS packaging philosophy). Other projects which
include drake as a submodule might rely on that capability.
But I am aok with updating the instructions to the cmake-recommended strategy.

**Comment by mwoehlke-kitware** [comment]
@RussTedrake, is (with changes mentioned in previous comment) this approved?

**Comment by RussTedrake** [comment]
we need to update the instructions in the wiki and verify that they work for people.  also need to restore the ability to call make from the commandline on windows (perhaps with an if win32, call cmake --build).

**Comment by mwoehlke-kitware** [comment]
>  also need to restore the ability to call make from the commandline on windows (perhaps with an if win32, call cmake --build).

I did that already. That's what I was referring to when I mentioned "changes mentioned in previous comment".

**Comment by RussTedrake** [comment]
excellent.

On Mon, Feb 22, 2016 at 4:43 PM, Matthew Woehlke <notifications@github.com>
wrote:
also need to restore the ability to call make from the commandline on windows
(perhaps with an if win32, call cmake --build).

I did that already. That's what I was referring to when I mentioned "changes
mentioned in previous comment".

—
Reply to this email directly or view it on GitHub
[https://github.com/RobotLocomotion/drake/pull/1729#issuecomment-187399559] .[https://github.com/notifications/beacon/AGJNNFhIaKHXBEZEoEn4RAVppXAE7bPBks5pm3h0gaJpZM4HdX7g.gif]

**Comment by mwoehlke-kitware** [comment]
> we need to update the instructions in the wiki

Do we? In it's current form, no changes should be *required* (i.e. the current instructions should continue to work).

If we're going to recommend to people to use CMake directly, I'd like if that worked properly, i.e. the user can choose any generator and any build directory. The first *may* be working with (or without, also, I think) these changes, but the second definitely does not. I'd like to get there eventually (probably not in this PR), but it requires non-trivial changes to where the build artifacts are written, as the current system requires that they are in a `pod-build` subdirectory of the respective source directory of each external project. (I've played around with this some locally and have it mostly working except for libbot.)

**Comment by billhoffman** [comment]
@RussTedrake and @mwoehlke-kitware sounds like this is ready to merge.  The current instructions still work. 

I gave it a try on my windows machine and the issue seems to be fixed:

hoffman@quasar ~/Work/drakew/drake
$ make
Configuring with CMAKE_FLAGS: -DCMAKE_BUILD_TYPE=Release
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23026.0
-- The CXX compiler identification is MSVC 19.0.23026.0
-- Check for working C compiler using: Visual Studio 14 2015
-- Check for working C compiler using: Visual Studio 14 2015 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 14 2015
-- Check for working CXX compiler using: Visual Studio 14 2015 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_INSTALL_PREFIX=C:/Users/hoffman/Work/drakew/drake/build
-- Preparing to build cmake with dependencies: 
-- Preparing to build eigen with dependencies: 
-- Preparing to build swigmake with dependencies: 
-- Preparing to build drake with dependencies: cmake;eigen;swigmake
-- Preparing to install precompiled snopt
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/hoffman/Work/drakew/drake/pod-build
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/24/2016 5:08:00 PM.
Project "C:\Users\hoffman\Work\drakew\drake\pod-build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\Users\hoffman\Work\drakew\drake\pod-build\ALL_BUILD.vcxproj" (1) is building "C:\Users\hoffman\Work\drakew\drake\pod-build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).

....

**Pull request merged**
