### PR TITLE
Add comments to RotationMatrix constructor with AngleAxis argument.

### PR DESCRIPTION
**Pull request by mitiguy**
Simple comments to follow PR #21365.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21382)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature and platform review +@jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21382#-:-NwvcgbmBXTybv_RKYAw:b4gftad)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

\CC @sherm1 FYI

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21382#-:-Nx31CZyExIq_sbV3pLV:b-lcp6va)* status: 1 unresolved discussion

___
*[`math/rotation_matrix.h` line 121 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21382#-Nx30rtn91eS8QH6pWhC:-Nx30rtn91eS8QH6pWhD:b-r5wtkk) ([raw file](https://github.com/RobotLocomotion/drake/blob/c0cde9cce8ac6ae45651603611ea50aef7ffeb2d/math/rotation_matrix.h#L121)):*
> ```objc
>     const T c = cos(theta);
>     const T t = 1 - c;
>     const T sx = s * x;
> ```

BTW Should the commenting start here?  (Or maybe on the prior line.)

It seems to me like the consistent choice would either be only to comment the nine `R.coeffRef ...` lines, or those plus _all_ of the intermediate terms.  Here we only have comments on half of the intermediate terms.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21382)* status: 1 unresolved discussion

___
*[`math/rotation_matrix.h` line 121 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21382#-Nx30rtn91eS8QH6pWhC:-Nx3lYkwBXizKQ2YfnrD:b-4am97o) ([raw file](https://github.com/RobotLocomotion/drake/blob/c0cde9cce8ac6ae45651603611ea50aef7ffeb2d/math/rotation_matrix.h#L121)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should the commenting start here?  (Or maybe on the prior line.)

It seems to me like the consistent choice would either be only to comment the nine `R.coeffRef ...` lines, or those plus _all_ of the intermediate terms.  Here we only have comments on half of the intermediate terms.
</blockquote></details>

Wouldn't hurt to comment more but it's easy enough to see what the earlier terms are. But I appreciated the txx, tyy, etc comments -- I think just starting with the complicated coeffRef terms would be too hard to inspect for correctness.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21382)* status: 1 unresolved discussion

___
*[`math/rotation_matrix.h` line 121 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21382#-Nx30rtn91eS8QH6pWhC:-Nx3nT163XWzsT7D9AyN:b90825p) ([raw file](https://github.com/RobotLocomotion/drake/blob/c0cde9cce8ac6ae45651603611ea50aef7ffeb2d/math/rotation_matrix.h#L121)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Wouldn't hurt to comment more but it's easy enough to see what the earlier terms are. But I appreciated the txx, tyy, etc comments -- I think just starting with the complicated coeffRef terms would be too hard to inspect for correctness.
</blockquote></details>

As I see it, the only non-trivial thing to memorize (or cross-reference) is what `t` means, so either we EOL comment `t` in every place where it's used, or none of them.  If `tx * x` is unclear to the point where it needs an EOL comment, then surely `t * x` is likewise in need of a comment.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21382)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Pull request merged**
