### PR TITLE
Snopt solve fortran74

### PR DESCRIPTION
**Pull request by hongkai-dai**
Allow to compile SnoptSolver with fortran interface in snopt 7.4

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9896)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
What do you think about adding a method on `class SnoptSolver`, that reports capabilities such as this?  At least `class SnoptSolver { static bool is_threadsafe(); }`, could be used to guard the multi-threaded test.  The two backend `.cc` files could report this answer differently.

It's less satisfying to propose `class SnoptSolver { static bool is_unbounded_lp_broken(); }` but I'd actually go for that.

The underlying theme in both, is that _not only_ do the unit tests want to know about this, but downstream user code might also need to know, for the same reasons.

**Comment by hongkai-dai** [comment]
@jwnimmer-tri I added the two function `is_thread_safe` and `is_unbounded_lp_broken`.

Are we still waiting for snopt 7.4 from RobotLocomotion repo? Is it OK that we merge this PR before we get snopt 7.4?

**Comment by jwnimmer-tri** [comment]
> Are we still waiting for snopt 7.4 from RobotLocomotion repo?

Yes.  I haven't heard any updates since weeks ago.

> Is it OK that we merge this PR before we get snopt 7.4?

Yes, I don't think lack of public CI should hold this up any longer.  We should at least begin code review now.

**Comment by hongkai-dai** [comment]
+@avalenzu for feature review please, thanks!

**Comment by avalenzu** [comment]
That's correct.

**Comment by jwnimmer-tri** [comment]
> I'm unable to build ...

Yes, there were lots of merge errors.  I've PRd the fixes at hongkai-dai/drake#15.  You can pick the last commit from there, if you want to build locally before it's merged.

**Comment by hongkai-dai** [comment]
@jwnimmer-tri Thanks for the PR https://github.com/hongkai-dai/drake/pull/15. I rebased this branch on top of master, and applied part of your PR to this PR. I don't think I know how to keep the commit history clean with merge, so I used rebase instead.

@avalenzu Thanks for the comments!

> BTW, just to check that I'm reading this right, we're assuming that each constraint's Jacobian is dense?

That is right. We currently don't specify the sparsity pattern in each constraint. If the constraint depends on `y`, where `y` is a subset of all the decision variables `x`, we then suppose that the gradient is dense w.r.t `y`, but sparse w.r.t the variables in `x` but not in `y`.

> This seems like a pretty big jump in the tolerance, although 1.001e-6 is still pretty tight. Do you know why this change is necessary? Could the tolerance just be 1e-6?

I forgot why I increased the tolerance, probably I did that when I tried other versions of SNOPT. I reverted back to the previous tolerance 1E-9.

**Comment by jwnimmer-tri** [comment]
> ... commit history clean  ...

What you did is perfect -- squashing my commit into you own is great.  I used PR so you could choose whether / when / how to integrate it, not because I think my commit should be separated out.

**Comment by hongkai-dai** [comment]
@jwnimmer-tri I have addressed your comments. Could you take a look after Thanksgiving holiday? Thanks!

I still kept `//NOLINTNEXTLINE`, since the linter complains that I need to include the directory of the header file.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
I checked over the code again, and I don't see any hazard to macOS builds, so I'm not going to opt-in to those jenkins jobs.

I think this is ready to merge.  Since @hongkai-dai is offline today, I will plan to squash and merge myself once CI is happy.

**Pull request merged**
