### PR TITLE
Always run director test under xvfb on linux

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3539)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for feature and platform review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3539#-:-KSCBlXAx7cAM6EX8B2J:btbehdq)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3539#-:-KSCEllvw01dN1dVbeV0:bnfp4nl)*

**Comment by david-german-tri** [comment]
I didn't do this originally because xvfb does not play nicely with some nvidia drivers.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3539#-:-KSCSZR7ciQKIyC7r5iM:buenu8n)*

**Comment by jwnimmer-tri** [comment]
I plan on adding additional xvfb-based tests, and they won't be as subtle as the director window currently is.  Do you have pointers and/or history to those failure modes, so I can work on getting this approach to work?  Or would a `USE_XVFB` or something CMake toggle be good enough to opt out?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3539#-:-KSCeL6LUiosQA6Bub4f:bimciu3)*

**Comment by rpoyner-tri** [comment]
Build failure was  window BAD AGENT flake.

**Comment by david-german-tri** [comment]
>   Do you have pointers and/or history to those failure modes, so I can work on getting this approach to work?

http://askubuntu.com/questions/738283/xvfb-glx-error-when-using-nvidia-driver

> Or would a USE_XVFB or something CMake toggle be good enough to opt out?

Yeah, that would work.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3539#-:-KSCk4rWKUJ6fw8LAV1C:b-focwr8)*

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri When I thought it was going to be simple, this PR was my predecessor to running `automotive.demo.py` as a regression test.  Now that it's a bit more involved, would you like to take this over as part of your regression test work?

**Comment by rpoyner-tri** [comment]
sure, i'll take a look.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3539#-:-KSDGiKdLw5sT53nqzSC:ba7kaz)*

**Pull request closed without merging**
