### PR TITLE
MBP generalized contact forces output port

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR adds an output port for the vector of generalized contact forces per model instance.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9053)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@sammy-tri for feature review please.

---

Review status: all discussions resolved, platform LGTM missing, commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9053#-:-LFrfMXv6hLTKRhTG9ar:bjquaum)*

**Comment by sammy-tri** [comment]
:lgtm: with one typo.  +@ericcousineau-tri for platform review per rotation

---

Reviewed 6 of 6 files at r1.
Review status: 1 unresolved discussion, platform LGTM from [sammy-tri], commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 979 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9053#-LFrqBAW3sfrH7Is3L95:-LFrqBAX9rP2pbEp4Iqo:bom7hvs) ([raw file](https://github.com/robotlocomotion/drake/blob/0ab506cd6d072f6883d92a0bbaa7060bd607facf/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L979)):*
> ```cpp
>   }
> 
>   // Declare on output port for the entire state vector.
> ```

typo "on" -> "one"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9053#-:-LFrsKpQ6b4Go4es9LD2:b-vhld3o)*

**Comment by amcastro-tri** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM from [sammy-tri], commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 979 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9053#-LFrqBAW3sfrH7Is3L95:-LFrz0PHCiy5Z5fk3GZl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0ab506cd6d072f6883d92a0bbaa7060bd607facf/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L979)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

typo "on" -> "one"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9053)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: 1 unresolved discussion, platform LGTM from [sammy-tri, ericcousineau-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9053#-:-LFs-gQG45CcGH2NdSo7:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all discussions resolved, platform LGTM from [sammy-tri, ericcousineau-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9053)*

**Pull request merged**
