### PR TITLE
Platform conditional build of a skeleton OpenGL render engine

### PR DESCRIPTION
**Pull request by tehbelinda**
Relates to #12594

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12623)

### CODE REVIEW

**Comment by tehbelinda** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by tehbelinda** [comment]
hey @jwnimmer-tri is this along the lines of what you had in mind?

**Comment by jwnimmer-tri** [comment]
TBH I would rather spend as little as possible of my time on this, and let y'all suss it out (you, Sean, maybe Jamie for any build questions).  It needs to be clear and obvious to other Drake developers how to co-maintain this code, and be straightforward to add/remove helper files related to GL, change the APIs, etc.

Here's a few quick thoughts:

(1) In Anzu, the number of includes and API span render_engine_gl.h is pretty wide, even though this prototype isn't that complicated quite yet.  I think the prototype should also add in one (dummy) helper h/cc file pair, so we can see how ubuntu-only deps work in this scheme.

In any case, I don't think the stubbing technique here will scale to that level of complexity.  I think we should have a factory method `unique_ptr<RenderEngine> MakeRenderEngineGl()` as the only user-public API.  On macOS, it could return an always-throws render implementation (that stub renderer could even be public for other uses -- the error message could be a constructor argument).  Then on Ubuntu, we can write the class as normal with no stubs or special phrasing, and the only platform-specific glue we need is the implementation of the factory method, which is trivially simple.

(2) A sometimes-missing library is unique enough that I think it deserves its own dedicated package, not mixed in with other normal libraries.  Maybe `//geometry/gl_renderer/...`?

(3) The prototype should also address how this interacts with pydrake, in case conditional seams are needed there also.

(4) If we are going to `#include` gl headers, I suspect we need a `//tools/workspace/...` entry to help us declare that we depend on them.  The prototype should prove this out somehow.

**Comment by tehbelinda** [comment]
Ok thanks Jeremy, this is already much appreciated!

**Comment by tehbelinda** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by tehbelinda** [comment]
-@jwnimmer-tri

**Comment by tehbelinda** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
See https://drake.mit.edu/code_review_checklist.html#did-you-change-third-party-software (newly updated).  We only need to launch one macOS build these days.

**Comment by tehbelinda** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
Some quick tips:

(1) Enhance `@opengl` repository rule to mimic `@libblas` -- a pkg-config based dependency that is only present on Ubuntu.

(2) In the `gl_renderer` package, create a `defs.bzl` file that defines a macro to abstract the BUILD file pattern for targets that should only _exist_ on Ubuntu.  The cc_library for the factory should still use the select-based spelling similar to the current PR, but all Ubuntu-only targets can use the same macro.

(3) I believe the macro could `load("@drake_detected_os//:os.bzl", "DISTRIBUTION")` to know the OS at macro-evaluation-time, in which case it could actually declare _no_ target in that case and skip all of the fancy `select` business.

**Comment by tehbelinda** [comment]
Thanks for taking a look again, I'll try those!

**Comment by tehbelinda** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by tehbelinda** [comment]
@jamiesnape Would you mind taking a look at this, in particular from the build perspective?

**Comment by jamiesnape** [comment]
Sure.

FWIW macOS OpenGL support is going to be around a while yet. Whether we actually want to write the code is a different question. Does not affect this PR, as there is no reason Ubuntu could not land first regardless, but generally porting OpenGL code between the platforms is not difficult.

**Comment by tehbelinda** [comment]
___
*[geometry/render/gl_renderer/opengl_context.cc, line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12623#-M0TFcoXBN7_2M7CeR46:-M0Z5dvt6xTmG-wdyUTl:bvekvwn) ([raw file](https://github.com/robotlocomotion/drake/blob/f4bc07c2a18bab955429cedc81b00b2b96ee8f93/geometry/render/gl_renderer/opengl_context.cc#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Why is this not in `opengl_includes.h`?
</blockquote></details>

good point, it does make more sense there so I'll move it, unless @seancurtis-tri remembers if there was a reason for this?

**Comment by tehbelinda** [comment]
___
*[geometry/render/gl_renderer/opengl_includes.h, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12623#-M0TFjWn0ex9iwOEyTw4:-M0Z5sZn8XRmASfsinAy:b-1ey9li) ([raw file](https://github.com/robotlocomotion/drake/blob/f4bc07c2a18bab955429cedc81b00b2b96ee8f93/geometry/render/gl_renderer/opengl_includes.h#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Do you want to error out if this is included on macOS? There are (mostly unusual) circumstances where the includes below would actually work.
</blockquote></details>

hmm I don't think it matters if it does work, because the RenderEngineGl will still throw on macOS if they try to use it regardless of what happens here

**Comment by tehbelinda** [comment]
___
*[geometry/render/gl_renderer/opengl_includes.h, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12623#-M0TFIEv13PP46E9LKfi:-M0Z6WzW-opgXB4Q9W3G:b-3jcsnr) ([raw file](https://github.com/robotlocomotion/drake/blob/f4bc07c2a18bab955429cedc81b00b2b96ee8f93/geometry/render/gl_renderer/opengl_includes.h#L9)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Personally I would make this private and not installed, but I do not actually know the public API and whether it therefore needs to be public.

Also, if someone has already included `<GL/gl.h>` in this compilation unit, is the macro actually going to take effect?
</blockquote></details>

I think it can be private. also is it helpful to exclude the header, like we do with vtk, so something like `install_hdrs_exclude = ["opengl_includes.h"],`?

**Comment by tehbelinda** [comment]
___
*[geometry/render/gl_renderer/opengl_context.cc, line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12623#-M0TFcoXBN7_2M7CeR46:-M0ZS_m5E2dVph5J7NAx:b-7sb8r2) ([raw file](https://github.com/robotlocomotion/drake/blob/f4bc07c2a18bab955429cedc81b00b2b96ee8f93/geometry/render/gl_renderer/opengl_context.cc#L3)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

good point, it does make more sense there so I'll move it, unless @seancurtis-tri remembers if there was a reason for this?
</blockquote></details>

ah looks like this one also needs X11 - mind if I TODO it and fix it in a follow up PR? I have the next one, render-gl-port, that ports the rest of the actual code and adds in the required X11 dependency

**Comment by tehbelinda** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by tehbelinda** [comment]
updated now, ptal, thanks!

**Comment by tehbelinda** [comment]
Ok I can clear out the RenderEngine API part, but the reason for using the OpenGLContext class was to make sure the build system would handle a chain of dependencies

**Comment by tehbelinda** [comment]
However, I realised that no longer subclassing `RenderEngine` makes the the factory part less clean and abstract. The factory will need to return a unique pointer to`RenderEngineGl` directly instead. One of the benefits otherwise was that the no-OpenGL path didn't need to change, and the follow up PR would be purely related to the implementation of the real render engine.
I'm still happy to change it if you think that's worth it?

**Comment by tehbelinda** [comment]
Ok, I'll clear out a little bit of the fake implementation around RenderDepthImage since that's not really necessary but I think I'd rather leave the rest as is. I'll try and improve the organisation within the follow up PRs instead

**Comment by tehbelinda** [comment]
+@jamiesnape for feature review please

**Comment by tehbelinda** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by tehbelinda** [comment]
+@ggould-tri for platform review please

**Comment by jwnimmer-tri** [comment]
___
*[geometry/render/gl_renderer/defs.bzl, line 1 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12623#-M1fpz2g6ObgVvhBvdor:-M1fqrn91yDZrG6z-Rct:buupcpm) ([raw file](https://github.com/robotlocomotion/drake/blob/417dad98c016df74726e1a9bbfe2e7ff7f963fd9/geometry/render/gl_renderer/defs.bzl#L1)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor: This will be the first .bzl file in a source code directory.  @jwnimmer-tri , can I get a judgment on whether this is within the bazel layout design you have in mind, or whether this should live under `tools` instead?
</blockquote></details>

OK Yes, I think for macros that are private to just one BUILD file, keeping them adjacent to that BUILD file is better cohesion.  If we find a need to call this macro from other places, then at that point we should elevate it up into `tools`.

**Comment by jwnimmer-tri** [comment]
___
*[geometry/render/gl_renderer/BUILD.bazel, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12623#-M03Vz_nECnScqOExsWK:-M03Vz_oE2iZuJzgN1Hx:b-qrmy4o) ([raw file](https://github.com/robotlocomotion/drake/blob/f1fadd6e50be69a8b741f872d703b50f2d76aad1/geometry/render/gl_renderer/BUILD.bazel#L11)):*
> ```Starlark
> load("//tools/lint:lint.bzl", "add_lint_tests")
> 
> package(default_visibility = ["//visibility:public"])
> ```

Given that we expect that users should _only_ ever directly use the factory, maybe the default should be private here?  In that case, only `:gl_renderer` would be public (per drake_cc_package_library default).

**Comment by jwnimmer-tri** [comment]
___
*[geometry/render/gl_renderer/BUILD.bazel, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12623#-M03VPuc-No9qw5tzVTD:-M03VPuc-No9qw5tzVTE:b-zf2p1a) ([raw file](https://github.com/robotlocomotion/drake/blob/f1fadd6e50be69a8b741f872d703b50f2d76aad1/geometry/render/gl_renderer/BUILD.bazel#L25)):*
> ```Starlark
>     srcs = select({
>         "//tools/cc_toolchain:apple": [],
>         "//conditions:default": ["opengl_context.cc"],
> ```

_META_ any source code that appears _only_ within a select statement must be listed in `cpplint_extra_srcs = []` in the `add_lint_tests` below, or else the linter will miss it.

**Comment by tehbelinda** [comment]
___
*[geometry/render/gl_renderer/BUILD.bazel, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12623#-M03VPuc-No9qw5tzVTD:-M2AEf8JE62_yoWAOdpI:b3tx6go) ([raw file](https://github.com/robotlocomotion/drake/blob/f1fadd6e50be69a8b741f872d703b50f2d76aad1/geometry/render/gl_renderer/BUILD.bazel#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_META_ any source code that appears _only_ within a select statement must be listed in `cpplint_extra_srcs = []` in the `add_lint_tests` below, or else the linter will miss it.
</blockquote></details>

Ok I'll add that for the render_engine_gl target, but this one has been updated to use the macro. As in, it's no longer in a select statement, there's just no drake_cc_library at all if it's not on a supported platform. Does it still need to go in cpplint_extra_srcs if that's the case? It still catches lint errors locally, but I guess I'm running on Ubuntu so it's supported?

**Comment by jwnimmer-tri** [comment]
___
*[geometry/render/gl_renderer/BUILD.bazel, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12623#-M03VPuc-No9qw5tzVTD:-M2AKaXE3DesJV8cFzA4:b-ndzn6z) ([raw file](https://github.com/robotlocomotion/drake/blob/f1fadd6e50be69a8b741f872d703b50f2d76aad1/geometry/render/gl_renderer/BUILD.bazel#L25)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

Ok I'll add that for the render_engine_gl target, but this one has been updated to use the macro. As in, it's no longer in a select statement, there's just no drake_cc_library at all if it's not on a supported platform. Does it still need to go in cpplint_extra_srcs if that's the case? It still catches lint errors locally, but I guess I'm running on Ubuntu so it's supported?
</blockquote></details>

That is a good question, and I think the first time we've encountered it.  Perhaps best that targets that are absent on a given platform should not receive linting.  If the user had to edit the file due to a lint error, they could not test-compile it.  So no, not extra_srcs in that case.

**Pull request merged**
