### PR TITLE
[solvers] Add max_nodes_in_tree for branch_and_bound.

### LINKED ISSUE #19284: Maximum iteration / time option for BranchAndBound algorithm
As far as I can oversee the API there is currently no way to give the mixed integer branch and bound algorithm a maximum number of iterations or more importantly time. So it comes to the fact that it computes in difficult cases very long, uses a lot of resources and can hardly or not at all be stopped. 

I think a maximum time or iteration could solve this problem easily.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Early terminate the branch and bound process if the nodes in the tree exceeds this number.

Resolves #19284

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
@AlexandreAmice is it OK if I ask you to review this PR? Feel free to dismiss.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-:-NUguMQVDF4VWETqi5yf:b-6deuo4)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
Checkpoint. I think I am confused by the naming convention/what you are trying to count. From my understanding, you are attempting to count the number of nodes explored in a given subtree? If this is correct, I think I am misunderstanding how the current implementation marks a node as explored or not.

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-:-NUhledzAm18eIMW72OQ:b-1cvhp7)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/branch_and_bound.h` line 169 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhlV4R4w-l-zBTCsGr:-NUhlV4R4w-l-zBTCsGs:b79j86k) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/branch_and_bound.h#L169)):*
> ```objc
>    * (including this node).
>    */
>   [[nodiscard]] int NumNodesInSubtree() const;
> ```

I believe this is the number of nodes explored? I would make this `NumNodesExploredInSubtree`?
___
*[`solvers/branch_and_bound.h` line 287 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhfe9y8NQqyHoy86Sd:-NUhfe9y8NQqyHoy86Se:b82vpqw) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/branch_and_bound.h#L287)):*
> ```objc
>     // max_nodes_in_tree <= 0 means that we dont put an upper bound on the
>     // number of nodes.
>     int max_nodes_in_tree{-1};
> ```

I would name this "max_explored_nodes". This current name made me think that we don't bother solving the program if the total number of nodes possible in the tree was too high.
___
*[`solvers/branch_and_bound.cc` line 256 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhfHlR3ID99yng1up5:-NUhfHlR3ID99yng1up6:b-pwsxcd) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/branch_and_bound.cc#L256)):*
> ```cpp
> 
> int MixedIntegerBranchAndBoundNode::NumNodesInSubtree() const {
>   // First count this node as the roobt of the subtree.
> ```

nit: typo -> "roobt"
___
*[`solvers/test/branch_and_bound_test.cc` line 364 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhkex37s-ImwtsBULJ:-NUhkex37s-ImwtsBULK:b4cd5h4) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/test/branch_and_bound_test.cc#L364)):*
> ```cpp
>   // Branch on x(0)
>   root->Branch(x(0));
>   EXPECT_EQ(root->NumNodesInSubtree(), 3);
> ```

Why is this 3? I thought it would be 1+2+2 = 5 (one for the current node, two for each branch of `x2` and `x4`
___
*[`solvers/test/branch_and_bound_test.cc` line 377 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhkrTV4Q9F3m9maIsO:-NUhkrTV4Q9F3m9maIsP:b-89a4l7) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/test/branch_and_bound_test.cc#L377)):*
> ```cpp
>   // Branch on x(2)
>   root->Branch(x(2));
>   EXPECT_EQ(root->NumNodesInSubtree(), 3);
> ```

Ditto
___
*[`solvers/test/branch_and_bound_test.cc` line 390 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhl8LA57mhhB3A3AD6:-NUhl8LA57mhhB3A3AD7:bs4q9op) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/test/branch_and_bound_test.cc#L390)):*
> ```cpp
>   // Branch on x(4)
>   root->Branch(x(4));
>   EXPECT_EQ(root->NumNodesInSubtree(), 3);
> ```

Ditto.

**Review by hongkai-dai — COMMENTED** [review]
That's an excellent question. Sorry I was in a hurry yesterday when I submit the PR only had limited time during travel. I should have been more clear when I submit the PR.

I suppose by "explore a node" you mean that after we create a node, whether the optimization program in the node is solved or not. As far as I can recall from `branch_and_bound.cc`, the only function to create children node is through calling "Branch" function in the parent node, as in https://github.com/RobotLocomotion/drake/blob/8327b29738705689cc13265b16ac656ce0cea631/solvers/branch_and_bound.cc#L292-L314
As you can see in this code, within this function after we create the two children nodes, we immediately solve the mathematical program in the children nodes. Also in the root node, when we construct it through `ConstructRootNode`, we call the Solve() function to solve the mathematical program within the root node. So with the current implementation, whenever we create a node, within the function that the node is created, we always solve the mathematical program, hence the node is always explored.

This might not be the best approach to implement branch and bound. One might imagine another implementation that we create the children nodes, but only solve the mathematical program in one node. But with the current `MixedIntegerBranchAndBoundNode` class, we always keep the invariance that a node is always explored at construction.

Does this make sense to you?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-:-NUm0rwu0sw7NcE9BYWK:b-8hzran)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/branch_and_bound.h` line 169 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhlV4R4w-l-zBTCsGr:-NUm4BjI8-zDJg44I6Xq:b-6ar1ci) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/branch_and_bound.h#L169)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I believe this is the number of nodes explored? I would make this `NumNodesExploredInSubtree`?
</blockquote></details>

It is a little bit tricky here.

We have two classes, MixedIntegerBranchAndBoundNode and MixedIntegerBranchAndBound.

As explained above, in the class `MixedIntegerBranchAndBound`, whenever we create a node, we also solve the mathematical program inside that node, so each node is explored at the construction in MixedIntegerBranchAndBound class.

But in MixedIntegerBranchAndBoundNode, we do not guarantee that at the construction, MixedIntegerBranchAndBoundNode is explored.

This `NumNodesInSubtree` is a function of `MixedIntegerBranchAndBoundNode`, which doesn't guarantee to explore the node at construction, so it really just counts the number of nodes, not the number of explored nodes.

If we want to count `NumNodesExploredInSubtree`, then we should determine whether that node is explored or not, by checking if `MixedIntegerBranchAndBoundNode::result` contains a nullptr or not. Do you prefer this solution?
___
*[`solvers/test/branch_and_bound_test.cc` line 364 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhkex37s-ImwtsBULJ:-NUm5dLw88DMnKrlxlfj:bhv4k1h) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/test/branch_and_bound_test.cc#L364)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Why is this 3? I thought it would be 1+2+2 = 5 (one for the current node, two for each branch of `x2` and `x4`
</blockquote></details>

Ah, it is because if we have a node and call Branch() for twice, it erases the previously created subnodes.
```cc
MixedIntegerBranchAndBoundNode root;
// Creates two child nodes.
root.Branch(x(2));
// Erase the previously created child nodes, recreate two new child nodes
root.Branch(x(4));
```
This was previously commented in https://github.com/RobotLocomotion/drake/blob/8327b29738705689cc13265b16ac656ce0cea631/solvers/test/branch_and_bound_test.cc#L325-L327. I added the comment here now.

BTW, here in this line, the root only branches on x(0), it hasn't branched on the other variable x(2) yet (as you commented below), so there should be 3 nodes.
___
*[`solvers/test/branch_and_bound_test.cc` line 377 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhkrTV4Q9F3m9maIsO:-NUm6j685-eCKo4apPzT:b-8fg168) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/test/branch_and_bound_test.cc#L377)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done. As explained above.
___
*[`solvers/test/branch_and_bound_test.cc` line 390 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhl8LA57mhhB3A3AD6:-NUm6lxA2cmzl_nlOTAf:b-iudpjk) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/test/branch_and_bound_test.cc#L390)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done. I added some documentation.

**Review by AlexandreAmice — COMMENTED** [review]
I see. So is the objective of this PR to solve at most `max_nodes_in_tree`? If so, I will look carefully to be sure if this is actually what the PR does. Also, if this is the case, then perhaps `max_nodes_in_tree` is not quite the right name. 

Otherwise, I could use some more context to be sure I can go through this carefully!

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-:-NUmd1Rm707uu-Vdu0Hv:bcmuv3s)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Done. I changed it to `max_explored_nodes_in_tree`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-:-NUr9zr_4w1LwKTikSJF:b4ca1ix)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/branch_and_bound.h` line 287 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NUhfe9y8NQqyHoy86Sd:-NUrARKk7maAB3NOJfbq:b-g4mvxi) ([raw file](https://github.com/RobotLocomotion/drake/blob/736b72545f13740f9e9e143deeb2ff82f8133159/solvers/branch_and_bound.h#L287)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would name this "max_explored_nodes". This current name made me think that we don't bother solving the program if the total number of nodes possible in the tree was too high.
</blockquote></details>

Done. Goodcall.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-:-NUvEUjHCXfio_PSjlsq:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
+@AlexandreAmice assigned feature reviewer magic

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-:-NV14ntX6Cjt4SbOJRw7:bpeexnf)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-:-NV17X3z2RcM7y58evZG:bbq2qhu)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @hongkai-dai and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
+(release notes: feature) 

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-:-NV1j8JMCOjCgFSQq4Ko:b-dwz6iz)* status: 3 unresolved discussions

___
*[`solvers/branch_and_bound.h` line 175 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NV1gQLeCRP2lxl_p6qI:-NV1gQLeCRP2lxl_p6qJ:bxf6fpl) ([raw file](https://github.com/RobotLocomotion/drake/blob/76dc05c46e7bfdcf00d84c5d6be382663ab510fb/solvers/branch_and_bound.h#L175)):*
> ```objc
>   [[nodiscard]] int NumExploredNodesInSubtree() const;
> 
>  private:
> ```

nit Not part of the present patch, but I find it a little odd to see two `private:`access specifiers, and that the one method declaration in between has public-style comments. Is there a typo near here?
___
*[`solvers/branch_and_bound.h` line 289 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NV1itj_2gAtndJw5eWX:-NV1itj_2gAtndJw5eWY:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/76dc05c46e7bfdcf00d84c5d6be382663ab510fb/solvers/branch_and_bound.h#L289)):*
> ```objc
>     // The maximal number of explored nodes in the tree. The branch and bound
>     // process will terminate if the tree has explored this number of nodes.
>     // max_explored_nodes <= 0 means that we dont put an upper bound on
> ```

typo



_Suggestion:_
```objc
don't
```
___
*[`bindings/pydrake/solvers/test/branch_and_bound_test.py` line 36 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NV1i2aJ9aaD6Dnq2I47:-NV1i2aJ9aaD6Dnq2I48:b-uftbxx) ([raw file](https://github.com/RobotLocomotion/drake/blob/76dc05c46e7bfdcf00d84c5d6be382663ab510fb/bindings/pydrake/solvers/test/branch_and_bound_test.py#L36)):*
> ```Python
>         options = MixedIntegerBranchAndBound.Options()
>         options.max_explored_nodes = 1
>         dut2 = MixedIntegerBranchAndBound(
> ```

nit looks like the other parameter names ("prog", "solver_id") are not tested yet.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),AlexandreAmice

___
*[`solvers/branch_and_bound.h` line 175 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19366#-NV1gQLeCRP2lxl_p6qI:-NV5WzX73UIg278x91yM:b-g7iyip) ([raw file](https://github.com/RobotLocomotion/drake/blob/76dc05c46e7bfdcf00d84c5d6be382663ab510fb/solvers/branch_and_bound.h#L175)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Not part of the present patch, but I find it a little odd to see two `private:`access specifiers, and that the one method declaration in between has public-style comments. Is there a typo near here?
</blockquote></details>

Done. Good call, I removed the second `private" and changed the documentation type.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19366)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),AlexandreAmice

**Pull request merged**
