### PR TITLE
A few unit inertia factories.

### PR DESCRIPTION
**Pull request by amcastro-tri**
We identified in [this review comment](https://reviewable.io/reviews/robotlocomotion/drake/6723#-KqxrSq4WbfTdNKK8N4g) that we'd like to have some additional unit inertia factories.
This PR introduces the `UnitInertia` factories:
 - `AxiallySymmetric()`
 - `StraightLine()`
 - `ThinRod()`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6805)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@ericcousineau-tri for feature review please since you requested these.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-:-Kr7Ttj4Qbqqh7qglQgz:b1fgs5o)*

**Comment by EricCousineau-TRI** [comment]
Looks good, thank ya sir!

My main concern is that there still is not a clear example for people modeling in the planar world, where they may have `Izz` and not care about the other axes, and they may get lost / frustrated with, what to them, are unclear or obfuscated names from what they want. (I understand they're more theoretically succinct, but it still does not appear discoverable at the moment.)

Is there a way to make an easier-to-digest name, one that incorporates the name `Planar`, so that a non-expert could find something that works for their purpose without the need to consult expert knowledge?
If all else, could basic planar modeling in a 3d world be mentioned somewhere in the comments, an example, or in the doc, to provide them with an explanation of what they should do with just their Izz values? (Namely focusing on students who would like to stay in as much 2D as possible before they make the jump to 3D.)

If it is to be supplied in the doc, can we make a separate issue to address the planar-in-3d workflow at some point in the future? (I assume it would be related to #3089.)

Also, would it be possible to use these factories in the Acrobot dynamics example, once merged, as a TODO?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 304 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBNG8aV6RmNkUvOVxE:-KrBNG8bOyPyTkU2iWPM:b-hp8w9q) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/unit_inertia.h#L304)):*
> ```objc
>   /// perpendicular to L, the axially symmetric unit inertia G is computed as:
>   /// <pre>
>   ///   G = K * Id + (J - K) * b ⊗ b
> ```

`b` is not defined before usage here?

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 312 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBNNHXuDoz5Tqx8K45:-KrBNNHXuDoz5Tqx8K46:boslfc8) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/unit_inertia.h#L312)):*
> ```objc
>   ///   - J is negative. J can be zero.
>   ///   - K is negative. K can be zero.
>   ///   - J ≤ 2 * J, this corresponds to the triangle inequality, see
> ```

Did you mean `J ≤ 2 * K`?

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 325 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBNbGwUeE2ZrLxX0T6:-KrBNbGxrAO1_YhUw_Ek:b2i08f2) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/unit_inertia.h#L325)):*
> ```objc
>   /// @param[in] b_E
>   ///   Vector defining the symmetry axis, expressed in a frame E. `b_E` can
>   ///   have a norm different from one, however it will be normalized before
> ```

BTW Super minor grammar nit, "... from one; however, it will..."

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 337 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBOLSywJGbjW3KT1p1:-KrBOLSzDII0ygoD8mmq:b-3ogcgp) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/unit_inertia.h#L337)):*
> ```objc
>     DRAKE_DEMAND(J <= 2.0 * K);
>     // Normalize b_E before using it. Only direction matters:
>     Vector3<T> bhat_E = b_E.normalized();
> ```

Should there be a check for when `b_E.norm() < eps`?

---

*[drake/multibody/multibody_tree/test/unit_inertia_test.cc, line 285 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBOdvs8Lir5IlxeuIM:-KrBOdvt67ay6_Q_jbCA:bz6wk5z) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/test/unit_inertia_test.cc#L285)):*
> ```cpp
> 
>   // Unit inertia computed with StraightLine().
>   UnitInertia<double> G =
> ```

Can you incorporate the from into the variable names? G_E, G_E_expected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-:-KrBOxmbChpYZhDmeUO3:bgcojzq)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/multibody/multibody_tree/test/unit_inertia_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBR9qJG7NBfngsfgCb:-KrBR9qJG7NBfngsfgCc:b-693je1) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/test/unit_inertia_test.cc#L223)):*
> ```cpp
>   // Cylinder's moments about its longitudinal axis (I_axial) and about any
>   // other axis perpendicular to its longitudinal axis (I_perp).
>   const double I_perp = (3.0 * r * r + L * L) / 12.0;
> ```

nit `I` in the nomenclature represents a vector-valued non-unit inertias, while the `I`s here represent scalar-valued inertias.
Should `J` / `K` be used?
If so, could we stick to just one of those, and change the names in the above signatures to something like `J_perp` (`J_minor`) and `J_axial` (`J_principal`)?

BTW I've seen "inertia matrix"  refer to `D(q)` from the EOM, while "inertia tensor" refers to `I`. Do we make that distinction in the MBT / RBT code like that?

---

*[drake/multibody/multibody_tree/test/unit_inertia_test.cc, line 236 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBQxzQwiFu2sS2kNoe:-KrBQxzQwiFu2sS2kNof:bragzl4) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/test/unit_inertia_test.cc#L236)):*
> ```cpp
> 
>   // Unit inertia computed with AxiallySymmetric().
>   UnitInertia<double> G =
> ```

nit Can you express the frame here as well? `G_E`?

---

*[drake/multibody/multibody_tree/test/unit_inertia_test.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBR0d4m_ppnoWdyqb4:-KrBR0d4m_ppnoWdyqb5:b-z88122) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/test/unit_inertia_test.cc#L239)):*
> ```cpp
>       UnitInertia<double>::AxiallySymmetric(I_axial, I_perp, b_E);
> 
>   // The expected inertia is that of a cylinder of radius r and height L with
> ```

Can you explain that `SolidCylinder(r, L)` will be `G_Z`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805)*

**Comment by sherm1** [comment]
I would be very cautious about saying anything is "planar" in a 3d world. A flat plate in xy has inertia about x, y, and z. Whether the xy inertia matters depends on how other parts of the model are built -- that can't be determined by the inertia properties.

"Spatial" is our basic modeling mode; "planar" is a tightly-restricted subset requiring a lot of work to make sure nothing happens out of plane. Building 2d models in Drake is harder than building 3d models, so shouldn't be thought of as the "student" mode. Also we have no way of detecting that a claimed planar system actually has out-of-plane action.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-:-KrBozSBpUg0EI1hkOU8:bdcc1dx)*

**Comment by amcastro-tri** [comment]
> Is there a way to make an easier-to-digest name, one that incorporates the name Planar, so that a non-expert could find something that works for their purpose without the need to consult expert knowledge?

Eric, the reason I do not like "Planar" or something of the like here is because there would be the danger now of a 3D user using the "Planar" factory to instantiate a 3D inertia without properly knowing the consequences. I think this PR is a good step towards the 2D cases that is fully compatible with 3D. I think this PR plus 2D examples (properly document) would help those non-expert users. If I had the inverse dynamics PR in already I would even update the `double_pendulum_test.cc` as a first example!

I think we'll have a better idea of what a 2D case entails with these API's when we add more cases. My plan for this quarter is to have the pendulum and acrobot examples in MBT. Those are 2D.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 304 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBNG8aV6RmNkUvOVxE:-KrBqX87jlX51V2EASNJ:b-rjc75z) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/unit_inertia.h#L304)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

`b` is not defined before usage here?
</blockquote></details>

it actually is just two lines above.

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 312 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBNNHXuDoz5Tqx8K45:-KrBqf5RxYI04tzOrMSb:b-v9pu2c) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/unit_inertia.h#L312)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Did you mean `J ≤ 2 * K`?
</blockquote></details>

thanks. Done.

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 337 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBOLSywJGbjW3KT1p1:-KrBuiDbjF8ullNIb2Oy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/unit_inertia.h#L337)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Should there be a check for when `b_E.norm() < eps`?
</blockquote></details>

Done.

---

*[drake/multibody/multibody_tree/test/unit_inertia_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBR9qJG7NBfngsfgCb:-KrBuui2TqQVDjOsB6bP:b-84my8) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/test/unit_inertia_test.cc#L223)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit `I` in the nomenclature represents a vector-valued non-unit inertias, while the `I`s here represent scalar-valued inertias.
Should `J` / `K` be used?
If so, could we stick to just one of those, and change the names in the above signatures to something like `J_perp` (`J_minor`) and `J_axial` (`J_principal`)?

BTW I've seen "inertia matrix"  refer to `D(q)` from the EOM, while "inertia tensor" refers to `I`. Do we make that distinction in the MBT / RBT code like that?
</blockquote></details>

I think this is OK @ericcousineau-tri here for a unit test. I think I am providing enough documentation so that what each of these symbols are is clear. Also, I couldn't force users to call `J/K` their inertias just because they call these methods right?

---

*[drake/multibody/multibody_tree/test/unit_inertia_test.cc, line 236 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBQxzQwiFu2sS2kNoe:-KrBviYu_Dx5cb18sy7Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/test/unit_inertia_test.cc#L236)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Can you express the frame here as well? `G_E`?
</blockquote></details>

Done.

---

*[drake/multibody/multibody_tree/test/unit_inertia_test.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBR0d4m_ppnoWdyqb4:-KrBw5-kzNlTNxhTlg-t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/test/unit_inertia_test.cc#L239)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you explain that `SolidCylinder(r, L)` will be `G_Z`?
</blockquote></details>

Done.

---

*[drake/multibody/multibody_tree/test/unit_inertia_test.cc, line 285 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBOdvs8Lir5IlxeuIM:-KrBw8coa6i_YsaYVtLe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/test/unit_inertia_test.cc#L285)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you incorporate the from into the variable names? G_E, G_E_expected?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-:-KrBpVolB04r0BOhKon_:bi4h8mg)*

**Comment by amcastro-tri** [comment]
+@soonho-tri for platform review please

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-:-KrBwucAsQo-I0QHvc1b:b-10xzum)*

**Comment by EricCousineau-TRI** [comment]
@sherm1 and @amcastro-tri, I see your concerns about trying to address the planar case too early and engendering a dangerous mixture of 2D + 3D without proper constraints / checks, and I'll be more cautious about my usage of "planar". Thank you for the explanations!

:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 304 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBNG8aV6RmNkUvOVxE:-KrCQxZcL8oJbObkHsm8:b-hgwtgo) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/unit_inertia.h#L304)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

it actually is just two lines above.
</blockquote></details>

Ah, see it now. Thanks!

---

*[drake/multibody/multibody_tree/test/unit_inertia_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrBR9qJG7NBfngsfgCb:-KrCR8l5yb9QWdA0xpua:b-jp5b9e) ([raw file](https://github.com/robotlocomotion/drake/blob/9066549e03ab3192b9c7f41f78767900f336e884/drake/multibody/multibody_tree/test/unit_inertia_test.cc#L223)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think this is OK @ericcousineau-tri here for a unit test. I think I am providing enough documentation so that what each of these symbols are is clear. Also, I couldn't force users to call `J/K` their inertias just because they call these methods right?
</blockquote></details>

Sounds good, and yup!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-:-KrCRkoSIocqJ_rrtHpi:b-6oov7d)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805)*

**Comment by soonho-tri** [comment]
:lgtm: Please check some typos.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 300 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrCqNV4rvUzc_fRbkNG:-KrCqNV4rvUzc_fRbkNH:b-e2mtl8) ([raw file](https://github.com/robotlocomotion/drake/blob/310b089707451b1794442fb63fbbe5df834b2af3/drake/multibody/multibody_tree/unit_inertia.h#L300)):*
> ```objc
>   /// equal. Examples of bodies with an axially symmetric inertia include
>   /// axisymmetric objects such as cylinders and cones. Other commonly occurring
>   /// geometries with this property are, for intance, propellers with 3+ evenly
> ```

BTW, nit, s/intance/instance/

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrCqURg8zMXm9HIo42-:-KrCqURg8zMXm9HIo420:b7kmd7r) ([raw file](https://github.com/robotlocomotion/drake/blob/310b089707451b1794442fb63fbbe5df834b2af3/drake/multibody/multibody_tree/unit_inertia.h#L326)):*
> ```objc
>   ///   Unit inertia about axis b.
>   /// @param[in] K
>   ///   Unit inertia about any axis pependicular to b.
> ```

BTW, nit, META, s/pependicular/perpendicular/ ?

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 352 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrCqj6myRDX8_O4raQ5:-KrCqj6myRDX8_O4raQ6:b-q597o4) ([raw file](https://github.com/robotlocomotion/drake/blob/310b089707451b1794442fb63fbbe5df834b2af3/drake/multibody/multibody_tree/unit_inertia.h#L352)):*
> ```objc
>   /// along a straight, finite, line L with direction `b_E` and with moment of
>   /// inertia K about any axis perpendicular to this line. Since the mass of the
>   /// body is uniformly distribuited on this line L, its center of mass is
> ```

BTW, nit, s/distribuited/distributed/

---

*[drake/multibody/multibody_tree/unit_inertia.h, line 370 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-KrCr0zF2qV7RN1ksvs1:-KrCr0zF2qV7RN1ksvs2:b633yym) ([raw file](https://github.com/robotlocomotion/drake/blob/310b089707451b1794442fb63fbbe5df834b2af3/drake/multibody/multibody_tree/unit_inertia.h#L370)):*
> ```objc
>   /// @retval G_Bcm_E
>   ///   The unit inertia for a body B of unit mass uniformly distributed along a
>   ///   straigth line L, about its center of mass `Bcm` which is located at the
> ```

BTW, nit s/straigth/straight/ ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-:-KrCrVepUnJB3e8_nKte:bl19zg)*

**Comment by amcastro-tri** [comment]
Thanks, I ran `aspell` on this file.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805#-:-KrGWaYxegQu12L00Hhe:b3mf50)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6805)*

**Pull request merged**
