### PR TITLE
solvers: add doxygen group tags to more costs/constraints

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15246)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15246#-:-MdHVKDvBiMfp5wrI4Ff:b-qb6q7i)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:  (But for the trailing white space issue.)

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15246#-:-MdI-lEa5nN1y7_SLHIO:b-nibkbp)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[solvers/constraint.h, line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15246#-MdI-Yg6E4dyV_nZv-fT:-MdI-Yg7Dt6ImML885AZ:b6hk1dv) ([raw file](https://github.com/robotlocomotion/drake/blob/8d4adbde93fa10b9aba30c70c1510965a4bcfe75/solvers/constraint.h#L187)):*
> ```objc
>  * transpose of a scalar is the scalar itself. Hence we can always convert
>  * a non-symmetric matrix Q₀ to a symmetric matrix Q.
>  * 
> ```

The "empty" line has a trailing white space (and, in fact, this new empty line on all of the new comments).  This is what is choking CI. (Same in `cost.h`).

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15246)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[solvers/constraint.h, line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15246#-MdI-Yg6E4dyV_nZv-fT:-MdIK8LQ0qR5qDbF5FRj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d4adbde93fa10b9aba30c70c1510965a4bcfe75/solvers/constraint.h#L187)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The "empty" line has a trailing white space (and, in fact, this new empty line on all of the new comments).  This is what is choking CI. (Same in `cost.h`).
</blockquote></details>

Done.

**Comment by SeanCurtis-TRI** [comment]
Checking to see if CI failure is a fluke.

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15246)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

**Pull request merged**
