### PR TITLE
setup: Upgrade to bazel 0.19.2

### LINKED ISSUE #10081: Update CLion docs to bazel v0.18.0
## Description

CLion IDE setup docs [here](https://drake.mit.edu/clion.html) recommend an outdated version of bazel (v0.16.1). 

When trying the suggested setup:
- Ubuntu 16.04
- Bazel 0.16.1
- CLion 2018.1.6 with:
    - Bazel plug-in 2018.08.06.0.1.

I get the following error when CLion bazel plugin is syncing:

`Current Bazel version is 0.16.1, expected at least 0.18.0`

Which comes from `set(MINIMUM_BAZEL_VERSION 0.18.0)` in CMakeLists.txt

## Suggestions

Update the docs to include suggested setups that work with the Bazel version that is installed automatically by the drake setup scripts.

My working setup:
- Ubuntu 16.04
- Bazel 0.18.0
- CLion 2018.2.6 with:
    - Bazel plug-in 2018.10.22.0.2

I'd be happy to submit a pull request for this, but I'm not sure how to go about testing the full setup.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #10081.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10100)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@jamiesnape Thanks!  Once that's done, you or I can re-test the failed pre-merge builds.

FYI to @SeanCurtis-TRI @DamrongGuoy @ZackKnopp -- this proposes a new tested set of Bazel + CLion integration.  It seems to work for me, but you are welcome to test locally and chime in if you're interested.

**Comment by jamiesnape** [comment]
CI images are updated.

@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
OK Mac decided to fall back to the homebrew-core version. I will fix that now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review please, per schedule.

**Comment by jamiesnape** [comment]
It's fine not to wait for Mac to finish. We know that the build and test phases work with this version of Bazel from the nightly unprovisioned builds.

**Pull request merged**
