### PR TITLE
Python bind RotationalInertia::CalcPrincipalMomentsAndAxesOfInertia()

### PR DESCRIPTION
**Pull request by matheecs**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19521)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot ok to test

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for both reviews.  :lgtm: x 2.   Thanks!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19521#-:-NX2D4IgCeqCwZ9LkQOZ:by7un9y)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @matheecs)

**Comment by RussTedrake** [comment]
*[`bindings/pydrake/multibody/test/plant_test.py` line 604 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19521#-NX2FsYa4LAMsgeh_j-X:-NX2FsYa4LAMsgeh_j-Y:bgmlj2k) ([raw file](https://github.com/RobotLocomotion/drake/blob/a359dcca2ac6253a87751eb51e56dcbf983b91ba/bindings/pydrake/multibody/test/plant_test.py#L604)):*
> ```Python
>         self.assertEqual(len(dut.CalcPrincipalMomentsAndAxesOfInertia()), 2)
>         self.assertIsInstance(dut.CalcPrincipalMomentsAndAxesOfInertia()[0], np.ndarray)
>         self.assertIsInstance(dut.CalcPrincipalMomentsAndAxesOfInertia()[1], RotationMatrix)
> ```

to fix CI, this needs to be `RotationMatrix_[float]`.

you also need to run the code formatter on this file (lines 601, 603, and 604 are too long).

**Comment by matheecs** [comment]
Hi @RussTedrake I took your advice and used `RotationMatrix_[float]` instead of `RotationMatrix`, also run the code formatter by autopep8.

**Review by matheecs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19521)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @matheecs)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 604 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19521#-NX2FsYa4LAMsgeh_j-X:-NX4EH7I5aqUveg-yLKt:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a359dcca2ac6253a87751eb51e56dcbf983b91ba/bindings/pydrake/multibody/test/plant_test.py#L604)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

to fix CI, this needs to be `RotationMatrix_[float]`.

you also need to run the code formatter on this file (lines 601, 603, and 604 are too long). 
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19521)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @matheecs)

**Pull request merged**
