### PR TITLE
LinearSystemSolver returns wrong result

### LINKED ISSUE #6042: kLinearSystem does not check feasibility of solution.
I was toying with simple problems using the mathematical_program in c++ drake. I constructed the infeasible problem:

`  drake::solvers::MathematicalProgram prog_;
  drake::solvers::VectorDecisionVariable<1> x_;

  x_ = prog_.NewContinuousVariables(1);
  prog_.AddLinearEqualityConstraint(x_(0)==0);
  prog_.AddLinearEqualityConstraint(x_(0)==10);

  prog_.Solve();
  std::cout << prog_.GetSolution(x_);`

The problem is a) solver_result = 0,  b) solver_type = kLinearSystem and c) with solution x_= 5.

Adding an inequality `prog_.AddLinearConstraint(x_(0),1,5);` (i.e. 1 <= x_(0) <= 5) stops using kLinearSystem and uses Mosek instead which gives the expected infeasible return value. 

I did not dig deeper into it, but apparently KLinearSystem does not check feasibility   ##of its solutions as a final step.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #6042 . LinearSystemSolver returned `SolutionFound`, even when the problem is infeasible.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6737)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6737#-:-KqTmztgOvwPJfSNqpQ1:bvhsv4m)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/test/linear_system_solver_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6737#-KqTt5rqg52_DFToTuuh:-KqTt5rqg52_DFToTuui:b-1ee5cp) ([raw file](https://github.com/robotlocomotion/drake/blob/74893cd518a1bc31b951b31930680a90c4830ad9/drake/solvers/test/linear_system_solver_test.cc#L33)):*
> ```cpp
> 
> TEST_F(LinearSystemNoSolutionExample, testSolution) {
>   auto result = prog_.Solve();
> ```

BTW This may violate usage of `auto`, as the return-type is non-obvious from this call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6737#-:-KqTtJfZDqz1DrTkQp3r:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/linear_system_solver_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6737#-KqTt5rqg52_DFToTuuh:-KqZIMtsb-IoCwUwnjsW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74893cd518a1bc31b951b31930680a90c4830ad9/drake/solvers/test/linear_system_solver_test.cc#L33)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW This may violate usage of `auto`, as the return-type is non-obvious from this call.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6737)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6737)*

**Comment by hongkai-dai** [comment]
+@sherm1 for both feature and platform review, since you recommended the complete orthogonal decomposition.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6737#-:-KqZXOoThV0XLYK2034K:b5xnmzi)*

**Comment by sherm1** [comment]
Feature review pass: there are three independent features here:
- the bug fix to report infeasibility properly
- addition of unit tests to verify correct handling of under/overdetermined problems
- switch from SVD to Complete Orthogonal Decomposition (COD)

Each of these :lgtm: but per f2f @hongkai-dai will remove the COD and resubmit in a different PR. 

---

Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6737#-:-KqZgoajf5l5IdUkwAfP:baj66fp)*

**Comment by hongkai-dai** [comment]
This PR does two things now
1. Fix the bug on the infeasibility 
2. Addition of unit tests to verify correct handling of under/overdetermined problems.

I will submit a separate PR to switch from SVD to complete orthogonal decomposition. Currently using COD causes a pick and place demo to fail.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6737#-:-KqZhguNmY60H61oNAz2:bgpebb7)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6737)*

**Pull request merged**
