### PR TITLE
mkdoc: Add additional overload disambiguation

### LINKED ISSUE #10031: mkdoc: Make overload docs less fragile to source ordering
At present, `mkdoc` orders overloads according to source location, as documented here:
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html

@jwnimmer-tri suggested the following:
* If an overload has a unique number of arguments, just append `nargX`.
* If two or more overloads share the same amount, just append the nice type names of everything and call it a day.

I've assigned it to myself, will probably not get to it for the next week or two, so if someone else wants to do it before then they can. (Jeremy mentioned he may.)

\cc @sherm1 @edrumwri @mitiguy

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #10031.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10289)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
As the current record holder for writing bindings, I disagree with the first two points.
Cross-referencing isn't a bad thing. I don't like crowding the already hyper-redundant binding code with even more redundancy.

The only value I see in this is that it's easier to correspond `py::arg(...)` items, but I think we'd get more effort out of investing effort in automating bindings.

If we still need to hand craft bindings (which we will for a while), I personally don't want to type out excessive longhand.

**Comment by EricCousineau-TRI** [comment]
To follow-up, will soften my objections. I still personally don't prefer them. However, if it's judged to be trivial work to make the args explicit, then I guess I'm fine.

**Comment by jwnimmer-tri** [comment]
> "finding the generated documentation_pybind.h"

This is already documented in `pydrake_pybind.h`, as is some of the overload advice (and this PR tweaks that documentation slightly).  See "Documentation" at https://drake.mit.edu/doxygen_cxx/group__python__bindings.html.  However, I'll push a PR update here to be a little more prescriptive / have a recipe.

In my next push, I have also have rewritten the `no_pydrake` to all have a (mandatory) rationale.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-high-sierra-clang-cmake-experimental-release please

**Comment by jwnimmer-tri** [comment]
"All around the mulberry bush, ..."

@drake-jenkins-bot mac-high-sierra-clang-cmake-experimental-release please

**Pull request merged**
