### PR TITLE
Add limited, experimental Bazel support

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A first step toward #3129.  Replaces #3809 as the first PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3819)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for both reviews, please.

Proposed rules of engagement for Bazel PRs:
 1. Bazel PRs are linked to #3129 for tracking purposes.
 1. Bazel-specific source files undergo PR review by @david-german-tri and @jwnimmer-tri (whichever one of us isn't the author).  These are files like `BUILD`, `WORKSPACE`, `drake-distro/tools/*`, `drake-distro/drake/doc/bazel.rst`, etc.  This will serve as both feature and platform review.
 1. Bazel-specific sources and non-Bazel-specific sources are never mixed in the same PR.
 1. If and when we are ready to bleed Bazel influence onto folks other than the two of us, we seek review on the aggregate changes (all of the Bazel-specific files).

**Comment by rpoyner-tri** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUHnxrD_03ZYkLRpIjg:-KUHnxrEjNh_603trDGH:bcnhc5u) ([raw file](https://github.com/robotlocomotion/drake/blob/52f13c60dec4f5077f9a47d36f71f6f20b5d95e4/WORKSPACE#L6)):*
> ```
> # This file marks a workspace root for the Bazel build system. see
> # http://bazel.io/ .
> ```

BTW, consider adding a workspace(name = "drake") or so here. This can make it a bit easier for other projects to consume drake via bazel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3819)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-:-KUHoNkgVM1BjyCX-Yhg:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUHnxrD_03ZYkLRpIjg:-KUHphTJFzV-N7eIoe-A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52f13c60dec4f5077f9a47d36f71f6f20b5d95e4/WORKSPACE#L6)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> BTW, consider adding a workspace(name = "drake") or so here. This can make it a bit easier for other projects to consume drake via bazel.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3819)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3819)*

**Comment by david-german-tri** [comment]
Exciting!  I'll give it a try on Mac right now.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[WORKSPACE, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIXS_FZqFz_cdSgSmc:-KUIXS_FZqFz_cdSgSmd:b895hen) ([raw file](https://github.com/robotlocomotion/drake/blob/30f083a650c79877cbac2d5f3054d79d55013d5f/WORKSPACE#L2)):*
> ```
> # -*- python -*-
> # Copyright 2016 Toyota Research Institute.  All rights reserved.
> ```

This doesn't seem like what we want.  Surely it's licensed like the rest of Drake?

---

*[WORKSPACE, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIXpEu0rXn4zezZWc-:-KUIXpEvJbglBE0tHLGu:b-ebqxa7) ([raw file](https://github.com/robotlocomotion/drake/blob/30f083a650c79877cbac2d5f3054d79d55013d5f/WORKSPACE#L12)):*
> ```
>     name = "gtest",
>     url = "https://googletest.googlecode.com/files/gtest-1.7.0.zip",
>     sha256 = "247ca18dd83f53deb1328be17e4b1be31514cedfc1e3424f672bf11fd7e0d60d",
> ```

This is not the same SHA that the Drake external is pinned to.  What's up with that?

---

*[drake/math/BUILD, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIY2ook7QEJXL2Le4H:-KUIY2ook7QEJXL2Le4I:b-89a4l7) ([raw file](https://github.com/robotlocomotion/drake/blob/30f083a650c79877cbac2d5f3054d79d55013d5f/drake/math/BUILD#L2)):*
> ```Python
> # -*- python -*-
> # Copyright 2016 Toyota Research Institute.  All rights reserved.
> ```

Ditto

---

*[drake/systems/BUILD, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIY59OcFOK2lggxy4J:-KUIY59OcFOK2lggxy4K:b-89a4l7) ([raw file](https://github.com/robotlocomotion/drake/blob/30f083a650c79877cbac2d5f3054d79d55013d5f/drake/systems/BUILD#L2)):*
> ```Python
> # -*- python -*-
> # Copyright 2016 Toyota Research Institute.  All rights reserved.
> ```

Ditto

---

*[drake/systems/BUILD, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIYA7HjSiGSeEmUuEj:-KUIYA7HjSiGSeEmUuEk:b-sfqe7l) ([raw file](https://github.com/robotlocomotion/drake/blob/30f083a650c79877cbac2d5f3054d79d55013d5f/drake/systems/BUILD#L6)):*
> ```Python
> cc_library(
>     name = "systems_framework",
>     hdrs = glob(["framework/*.h"]),
> ```

Why enumerate elsewhere, but glob here?

---

*[tools/README.md, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIYT8xWLmX7m3FbmUi:-KUIYT8xWLmX7m3FbmUj:b-rrkl3l) ([raw file](https://github.com/robotlocomotion/drake/blob/30f083a650c79877cbac2d5f3054d79d55013d5f/tools/README.md#L3)):*
> ```Markdown
> [//]: # Copyright 2016 Toyota Research Institute.  All rights reserved.
> 
> This directory contains build system files related to the bazel build system.
> ```

Huh?  I don't think lcm_vector_gen answers to this description

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-:-KUIY_njAvzCvY9VgK_y:b48ll4n)*

**Comment by david-german-tri** [comment]
Doesn't seem to work on a system that only has Clang.  Poking around now to see if I can figure out why not.

```
$ bazel build ...
INFO: Found 5 targets...
ERROR: /Users/davidgerman/3819/drake-distro/drake/systems/BUILD:12:1: Linking of rule '//drake/systems:systems_analysis' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -shared -o bazel-out/local-opt/bin/drake/systems/libsystems_analysis.so ... (remaining 6 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
ccache: error: Could not find compiler "gcc" in PATH
INFO: Elapsed time: 86.319s, Critical Path: 56.96s
```

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[WORKSPACE, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIXS_FZqFz_cdSgSmc:-KUIazEuuJGbjgnS5E92:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7efa74efde681610e93fa659e76d61c687bde90/WORKSPACE#L2)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This doesn't seem like what we want.  Surely it's licensed like the rest of Drake?
</details>
Done.

---

*[WORKSPACE, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIXpEu0rXn4zezZWc-:-KUIYuLGQvPT5K91Z6Kc:b-vazq6v) ([raw file](https://github.com/robotlocomotion/drake/blob/f7efa74efde681610e93fa659e76d61c687bde90/WORKSPACE#L12)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This is not the same SHA that the Drake external is pinned to.  What's up with that?
</details>
In this PR, I wasn't yet trying to match the revisions of the externals.  The 1.7.0 is the version my downstream project happened to be using.

---

*[drake/math/BUILD, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIY2ook7QEJXL2Le4H:-KUIb-HO598hPtk-_EYE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7efa74efde681610e93fa659e76d61c687bde90/drake/math/BUILD#L2)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Ditto
</details>
Done.

---

*[drake/systems/BUILD, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIY59OcFOK2lggxy4J:-KUIb1oCCGaU6-LWATmy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7efa74efde681610e93fa659e76d61c687bde90/drake/systems/BUILD#L2)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Ditto
</details>
Done.

---

*[drake/systems/BUILD, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIYA7HjSiGSeEmUuEj:-KUI_yDOAAofCwwfHcyG:bl3xepm) ([raw file](https://github.com/robotlocomotion/drake/blob/f7efa74efde681610e93fa659e76d61c687bde90/drake/systems/BUILD#L6)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why enumerate elsewhere, but glob here?
</details>
(1) Some of the other subdirs are only subsets of the files.
(2) These ones seemed like they will evolve quickly enough that a glob would be the better trade-off, since these subdirs dependencies are kept clean.
(3) I wanted to demonstrate both ways of doing it.

---

*[tools/README.md, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3819#-KUIYT8xWLmX7m3FbmUi:-KUIZp1sLM1_yYPmS8Ew:b-y89392) ([raw file](https://github.com/robotlocomotion/drake/blob/f7efa74efde681610e93fa659e76d61c687bde90/tools/README.md#L3)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Huh?  I don't think lcm_vector_gen answers to this description
</details>
This file is `drake-distro/tools/README.md`, not `drake-distro/drake/tools/README.md`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3819)*

**Comment by david-german-tri** [comment]
Well, removing the ccache aliases for gcc prevents bazel from latching onto them.  That's a little annoying, but whatever.  :lgtm:

**Comment by jwnimmer-tri** [comment]
Oh yeah, you can't have `ccache` on your `$PATH` when using `bazel`.

**Comment by rpoyner-tri** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3819)*

**Pull request merged**
