### PR TITLE
[primitives] Promote RandomSource to be templated on scalar

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #15092.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15708)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15708#-:-MilzGkM5u6JnsovGXJW:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: deprecation question

> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15708#-:-Mj-ntwj24lbLvWepzFR:b-xww4xr)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/primitives/random_source.h, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15708#-Mj-nCvQ6TBna5-o18ey:-Mj-nCvQ6TBna5-o18ez:b757toi) ([raw file](https://github.com/robotlocomotion/drake/blob/2a24e3c7413dd08c132bae8423a29942acffe5ce/systems/primitives/random_source.h#L123)):*
> ```objc
> };
> 
> // TODO(jwnimmer-tri) On 2022-01-01 we should deprecate this vestigial alias.
> ```

Any reason not to use DRAKE_DEPRECATED here?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15708)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[systems/primitives/random_source.h, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15708#-Mj-nCvQ6TBna5-o18ey:-Mj-owOy1fhgxcZIBddD:b-t1fh03) ([raw file](https://github.com/robotlocomotion/drake/blob/2a24e3c7413dd08c132bae8423a29942acffe5ce/systems/primitives/random_source.h#L123)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Any reason not to use DRAKE_DEPRECATED here?
</blockquote></details>

Having both the old spelling and the new spelling available without any warnings in the same revision of Drake makes life simpler for downstream users.  They can adopt the new spelling at their leisure, without immediately being hit with deprecation warnings that might force their hand in case their policy is to resolve all warnings promptly.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15708)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),hongkai-dai (waiting on @jwnimmer-tri)

**Pull request merged**
