### PR TITLE
Revert "ChaoticBabyboot - unit test for accuracy of numerical integration."

### PR DESCRIPTION
**Pull request by liangfok**
Dear @mitiguy,

The on-call build cop, @liangfok, believes that your PR #7010 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
* https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-clang-bazel-continuous-everything-release/172/
* https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-clang-bazel-continuous-release/302/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7056)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please.
@drake-jenkins-bot mac-clang-bazel-experimental-everything please.

**Comment by sherm1** [comment]
@liangfok, @mitiguy This PR wouldn't have affected monolithic pick-and-place which I believe has been failing and is scheduled for removal. However, the other Mac failure is real - the Mac build didn't achieve as tight a tolerance as the other ones.

**Comment by liangfok** [comment]
Thanks @sherm1.  Can a fix-forward patch be submitted for the MG_chaotic_babyboot_test so this PR need not be merged?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7056#-:-KuUdlNVSR_wz3nF11uq:b-234mxz)*

**Comment by jwnimmer-tri** [comment]
A https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#temporarily-disabling-tests on ForwardDynamicsA would be an easy way to turn off the test.  Alternatively, `tags = ["manual"],` in the BUILD file for the test.

**Comment by liangfok** [comment]
OK. I'll submit a PR disabling the test. Thanks!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7056#-:-KuUgKnsZ67uapJg89W4:b-2uju56)*

**Pull request closed without merging**
