### PR TITLE
Rewrite the SimpleCar accleration model

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This version of the acceleration model should be gentler as we approach the limits.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5228)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jadecastro for feature review, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-:-KdO1WByFMxkMsnSvQiW:b-tkoxdn)*

**Comment by liangfok** [comment]
Reviewed 2 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/simple_car_test.cc, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdOHGHfp4tvHPdJL9LS:-KdOHGHfp4tvHPdJL9LT:b-hecth4) ([raw file](https://github.com/robotlocomotion/drake/blob/3a34c6868ce7eb53ee330cec2de36217b5f324b3/drake/automotive/test/simple_car_test.cc#L88)):*
> ```cpp
>   EXPECT_EQ(4.0, result->velocity());
> 
>   // If the integrator does a naughty, we don't let it bleed through.
> ```

BTW, I'm not sure what "does a naughty" means. Is that a commonly used phrase?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by jadecastro** [comment]
Just one minor item to consider, but otherwise :lgtm: 

---

Reviewed 6 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/test/simple_car_test.cc, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdOL9_XC1-C7l3Eh68W:-KdOL9_YBXCX1kFj1UcV:b6e71xm) ([raw file](https://github.com/robotlocomotion/drake/blob/3a34c6868ce7eb53ee330cec2de36217b5f324b3/drake/automotive/test/simple_car_test.cc#L232)):*
> ```cpp
>   EXPECT_EQ(0.0, result->y());
>   EXPECT_EQ(0.0, result->heading());
>   EXPECT_NEAR(-0.9293 * max_acceleration, result->velocity(), 0.001);
> ```

Consider computing the number explicitly via `tanh(20 * creeping)^2`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-:-KdOOtG2Ap0CZOoYJt9f:b-8ucvlc)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/simple_car_test.cc, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdOL9_XC1-C7l3Eh68W:-KdQZ38N-hIZzIPilAGN:b-2dwt) ([raw file](https://github.com/robotlocomotion/drake/blob/3a34c6868ce7eb53ee330cec2de36217b5f324b3/drake/automotive/test/simple_car_test.cc#L232)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Consider computing the number explicitly via `tanh(20 * creeping)^2`.
</blockquote></details>

To me, it was more important to demonstrate that there is a reduction, and its approximate magnitude, that to have an analytically exact expected value -- since we invented the smoothing out of thin air anyway.  Is there a way I could make that clearer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/simple_car_test.cc, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdOL9_XC1-C7l3Eh68W:-KdQfhMx4aZvHRat0KPI:be4w14r) ([raw file](https://github.com/robotlocomotion/drake/blob/3a34c6868ce7eb53ee330cec2de36217b5f324b3/drake/automotive/test/simple_car_test.cc#L232)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To me, it was more important to demonstrate that there is a reduction, and its approximate magnitude, that to have an analytically exact expected value -- since we invented the smoothing out of thin air anyway.  Is there a way I could make that clearer?
</blockquote></details>

To me, the best you can do without pulling concrete numbers is to check that the shape of the curve is what we expect: 1) in-band velocities are no closer to `{0, max_acceleration}` than some tolerance, e.g. `0.001`, and that 2) given that the chosen function is monotonic when `result->velocity() > 0`, it is indeed strictly increasing (in case the sign of the function is flipped).  Thus perhaps a two-point test,
```
const double kInBandTolerance = 0.001;
const double actual_creeping_velocity = result->velocity();
EXPECT_LE(actual_creeping_velocity, (1 - kInBandTolerance) * max_acceleration);  // N.B. Sufficiently less than one.

const double sub_creeping = 0.01;
continuous_state()->set_velocity(sub_creeping);
dut_->CalcTimeDerivatives(*context_, derivatives_.get());
EXPECT_EQ(0.1, result->x());
EXPECT_EQ(0.0, result->y());
EXPECT_EQ(0.0, result->heading());
EXPECT_LE(kInBandTolerance * max_acceleration, result->velocity());  // N.B. Sufficiently greater than zero.
EXPECT_LE(result->velocity(), actual_creeping_velocity);  // N.B. Increasing.
```
This would be adaptable so that `20` can be changed freely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/simple_car_test.cc, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdOL9_XC1-C7l3Eh68W:-KdR1A1Zboq8oY6R4vqF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a34c6868ce7eb53ee330cec2de36217b5f324b3/drake/automotive/test/simple_car_test.cc#L232)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

To me, the best you can do without pulling concrete numbers is to check that the shape of the curve is what we expect: 1) in-band velocities are no closer to `{0, max_acceleration}` than some tolerance, e.g. `0.001`, and that 2) given that the chosen function is monotonic when `result->velocity() > 0`, it is indeed strictly increasing (in case the sign of the function is flipped).  Thus perhaps a two-point test,
```
const double kInBandTolerance = 0.001;
const double actual_creeping_velocity = result->velocity();
EXPECT_LE(actual_creeping_velocity, (1 - kInBandTolerance) * max_acceleration);  // N.B. Sufficiently less than one.

const double sub_creeping = 0.01;
continuous_state()->set_velocity(sub_creeping);
dut_->CalcTimeDerivatives(*context_, derivatives_.get());
EXPECT_EQ(0.1, result->x());
EXPECT_EQ(0.0, result->y());
EXPECT_EQ(0.0, result->heading());
EXPECT_LE(kInBandTolerance * max_acceleration, result->velocity());  // N.B. Sufficiently greater than zero.
EXPECT_LE(result->velocity(), actual_creeping_velocity);  // N.B. Increasing.
```
This would be adaptable so that `20` can be changed freely.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by jadecastro** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
+@russtedrake for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-:-KdRf0RQGN04ryXdumwB:bddqu3n)*

**Comment by RussTedrake** [comment]
+@russtedrake for platform review.
a few other small comments, but otherwise :lgtm: 

---

Reviewed 3 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/simple_car.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRfscnAXd9I66ubW-c:-KdRfscnAXd9I66ubW-d:b31y3nt) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L102)):*
> ```cpp
> // If value is within [low, high] then return it; else return the boundary.
> template <class T>
> T clamp(const T& value, const T& low, const T& high) {
> ```

we typically call this a saturation.  
e.g. https://github.com/RobotLocomotion/drake/blob/ac80bde358ca384c10792645ddeada13575d2fa9/drake/systems/primitives/saturation.h

---

*[drake/automotive/simple_car.cc, line 132 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRgUgGmJa7cnRtBsnn:-KdRgUgGmJa7cnRtBsno:b-8wb7k1) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L132)):*
> ```cpp
>   // back toward the limit, but allow for the nominal_acceleration to win if it
>   // is stronger than the damping and has the desired sign.
>   const T underspeed = 0 - state.velocity();
> ```

T(0)?   there are also a bunch of places below that would appear to need T().  Or perhaps all of the implicit casts are correct, in which case we could remote T() from the DRAKE_DEMAND's above.  Feels inconsistent.

---

*[drake/automotive/simple_car.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRhrMoVAVa4nm2lax7:-KdRhrMoVAVa4nm2lax8:b-7g5or1) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L137)):*
> ```cpp
>       // If velocity is too low, use positive damping or nominal_acceleration.
>       underspeed > 0,
>       max(nominal_acceleration, T(config.velocity_limit_kp() * underspeed)),
> ```

shouldn't need T() here.  both are already type T?  same below.

---

*[drake/automotive/simple_car.cc, line 157 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRiL9X0mrhOsxR1m26:-KdRiL9YY0D2zo-5PY9G:bag66ij) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L157)):*
> ```cpp
>   const T clamped_steering_angle = clamp(
>       input.steering_angle(),
>       T(-config.max_abs_steering_angle()),
> ```

config is already type T.

---

*[drake/automotive/simple_car.cc, line 162 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRh2qWBFy25Pe2af5w:-KdRh2qWBFy25Pe2af5x:b-fsk48s) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L162)):*
> ```cpp
> 
>   // Don't allow small negative velocities to affect position or heading.
>   const T nonneg_velocity = std::max(T(0), state.velocity());
> ```

max, not std::max?  are the tests covering the autodiff and symbolic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-:-KdRerVuxPm-i0PNrdUD:b-r863ko)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/simple_car.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRfscnAXd9I66ubW-c:-KdRjUlXRxF87TZkh0Gx:bradodb) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L102)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

we typically call this a saturation.  
e.g. https://github.com/RobotLocomotion/drake/blob/ac80bde358ca384c10792645ddeada13575d2fa9/drake/systems/primitives/saturation.h
</blockquote></details>

I was going for http://en.cppreference.com/w/cpp/algorithm/clamp; is it worth changing to match systems practice?

---

*[drake/automotive/simple_car.cc, line 132 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRgUgGmJa7cnRtBsnn:-KdRjuK6cAoAKQdKbBae:b-wfd1br) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L132)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

T(0)?   there are also a bunch of places below that would appear to need T().  Or perhaps all of the implicit casts are correct, in which case we could remote T() from the DRAKE_DEMAND's above.  Feels inconsistent.
</blockquote></details>

I removed the ones above; the implicit conversion worked up there and also does here, so I've left this one alone.

---

*[drake/automotive/simple_car.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRhrMoVAVa4nm2lax7:-KdRkHOJEWwzmdI-hvYH:bo4omdc) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L137)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

shouldn't need T() here.  both are already type T?  same below.
</blockquote></details>

For autodiff, the `operator*` does not produce a `T` but rather some `BinaryOp` intermediary that doesn't implicitly convert into what `max` needs, so these ones are required.

It's possible that `max<T>(foo, bar)` would be another spelling we could start using, but I haven't chased that option to ground yet.

---

*[drake/automotive/simple_car.cc, line 157 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRiL9X0mrhOsxR1m26:-KdRku4vw24M-AIRebFC:bqvyziu) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L157)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

config is already type T.
</blockquote></details>

Again here, autodiff `operator-()` for negation doesn't return a `T` but some kind of "promise to be a T", which was confusing `clamp`.  I've changed the signature of `clamp` to deal, and removed these conversion hints.

---

*[drake/automotive/simple_car.cc, line 162 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRh2qWBFy25Pe2af5w:-KdRlUvMchG-6rWogJ6T:bhjnb4q) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L162)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

max, not std::max?  are the tests covering the autodiff and symbolic?
</blockquote></details>

Fixed.

There are no tests for autodiff or symbolic, I was going to leave that to a future PR (e.g. that also contained DoToAutoDiffXd).  I think actually the prior spelling of this was also correct, given that `operator<`-and-return-one-or-the-other is a correct formulation with any scalar type?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by RussTedrake** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/simple_car.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRfscnAXd9I66ubW-c:-KdRn5gn1kew03k0DniU:bl17s5u) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was going for http://en.cppreference.com/w/cpp/algorithm/clamp; is it worth changing to match systems practice?
</blockquote></details>

ugh.  that's a name clash for sure.  I do feel like we should be consistent, and personally prefer saturation.

---

*[drake/automotive/simple_car.cc, line 162 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRh2qWBFy25Pe2af5w:-KdRnaOfUfw7guVvBsV7:bww58pq) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L162)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Fixed.

There are no tests for autodiff or symbolic, I was going to leave that to a future PR (e.g. that also contained DoToAutoDiffXd).  I think actually the prior spelling of this was also correct, given that `operator<`-and-return-one-or-the-other is a correct formulation with any scalar type?
</blockquote></details>

i don't think it would have mysteriously called the method with the wrong type, but am surprised you didn't get an undefined error looking for std::max for e.g. autodiff.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/simple_car.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRfscnAXd9I66ubW-c:-KdRoNesueemmPEmYX7r:bkd2p7v) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L102)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

ugh.  that's a name clash for sure.  I do feel like we should be consistent, and personally prefer saturation.
</blockquote></details>

So `saturation(value, low, high)` or `saturate(value, low high)` in this case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/simple_car.cc, line 162 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRh2qWBFy25Pe2af5w:-KdRoZ6ieBbM7MbXmpNo:bbq7fcv) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L162)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i don't think it would have mysteriously called the method with the wrong type, but am surprised you didn't get an undefined error looking for std::max for e.g. autodiff.  
</blockquote></details>

I think the typical implementations at http://en.cppreference.com/w/cpp/algorithm/max might have worked for autodiff; and `SymbolicFormula::opreator bool` is defined (and can throw at runtime when indeterminate) so probably that would have been selected and turned into a runtime failure from the `std::` typo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by RussTedrake** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/simple_car.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRfscnAXd9I66ubW-c:-KdRqDAUcZO4k6yPN8s7:b1md9vc) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So `saturation(value, low, high)` or `saturate(value, low high)` in this case?
</blockquote></details>

i guess you `saturate(value, low, high)` here and end up with a `saturated_velocity_yada` below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/simple_car.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-KdRfscnAXd9I66ubW-c:-KdRqkVGae9GJPYZiXGw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/360e619abfdea3277cfc9ceec0afcf84cc10e214/drake/automotive/simple_car.cc#L102)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i guess you `saturate(value, low, high)` here and end up with a `saturated_velocity_yada` below?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-:-KdRrWuVzT68VxUqNBMK:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
For the record, a misplaced `std::max` vs `max` ADL in `ImplCalcOutput` is covered by (pending) unit tests for Symbolic sparsity providing `HasAnyDirectFeedthrough`.  On the other hand, `ImplTimeDerivatives` is not used symbolically (yet) so the misuse of `std::` there doesn't show up in the initial round of unit testing.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5228#-:-KdRw3w710V0Eojh9pn6:b-7inf2a)*

**Pull request merged**
