### PR TITLE
RgbdCamera: make use of color information given by VisualElement

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5604)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@liangfok feature review please. Thank you as always!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-:-Kfw3H4-bPYU2tj1tUxk:boz5myc)*

**Comment by liangfok** [comment]
Checkpoint. I left a question.

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 466 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-Kg-T-pPEhFjDBWRl8ZA:-Kg-T-pPEhFjDBWRl8ZB:b5a6z18) ([raw file](https://github.com/robotlocomotion/drake/blob/eb74a0d6de29bcba4c43207cf12d8e8946e8fa8e/drake/systems/sensors/rgbd_camera.cc#L466)):*
> ```cpp
>     // Registers actors.
>     if (shape_matched) {
>       if (!texture_found) {
> ```

Should this be `if (texture_found)`? I find it odd how `visual.getMaterial()` will return a valid color if no texture was found.

---

*[drake/systems/sensors/rgbd_camera.cc, line 474 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-Kg-SdK98hOy0Bkxw-9a:-Kg-SdKAPvg10cPEOTeP:b-el88qr) ([raw file](https://github.com/robotlocomotion/drake/blob/eb74a0d6de29bcba4c43207cf12d8e8946e8fa8e/drake/systems/sensors/rgbd_camera.cc#L474)):*
> ```cpp
>       const auto& color = color_palette_.get_normalized_color(body_id);
>       actor_for_label->GetProperty()->SetColor(color.r, color.g, color.b);
>       actor_for_label->GetProperty()->LightingOff();
> ```

BTW, can you add a comment explaining why the lighting needs to be turned off?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-:-Kg-THb5fD-m-2DKS9V2:b78bdl2)*

**Comment by kunimatsu-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 466 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-Kg-T-pPEhFjDBWRl8ZA:-Kg-ZbbJdv55vRx-01cV:b9miclw) ([raw file](https://github.com/robotlocomotion/drake/blob/eb74a0d6de29bcba4c43207cf12d8e8946e8fa8e/drake/systems/sensors/rgbd_camera.cc#L466)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should this be `if (texture_found)`? I find it odd how `visual.getMaterial()` will return a valid color if no texture was found.
</blockquote></details>

The current implementation is correct.  

If a texture would be found and a color from getMaterial would be also set, then the final color will be texture + color which is odd.

So, this condition means:
if texture found:
  use texture
otherwise:
  set color.

---

*[drake/systems/sensors/rgbd_camera.cc, line 474 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-Kg-SdK98hOy0Bkxw-9a:-Kg-_yhReyhKyQkfrIWd:bt0pvy5) ([raw file](https://github.com/robotlocomotion/drake/blob/eb74a0d6de29bcba4c43207cf12d8e8946e8fa8e/drake/systems/sensors/rgbd_camera.cc#L474)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, can you add a comment explaining why the lighting needs to be turned off?
</blockquote></details>

Alright. will add a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5604)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/rgbd_camera.cc, line 466 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-Kg-T-pPEhFjDBWRl8ZA:-Kg-aVlxlMpjyice6PMu:bsso7mq) ([raw file](https://github.com/robotlocomotion/drake/blob/eb74a0d6de29bcba4c43207cf12d8e8946e8fa8e/drake/systems/sensors/rgbd_camera.cc#L466)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

The current implementation is correct.  

If a texture would be found and a color from getMaterial would be also set, then the final color will be texture + color which is odd.

So, this condition means:
if texture found:
  use texture
otherwise:
  set color.

</blockquote></details>

I see. OK. Marking myself satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-:-Kg-ayS91-R1Ds4rMtcL:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
+@ggould-tri platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-:-Kg-mRMUgmT7dSEibtU9:bdmqfp3)*

**Comment by ggould-tri** [comment]
:lgtm: ; adding +(status: curate commits before merging) to force squash-merge of extra commits.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5604#-:-Kg-sWKylvB8yjzWlOw1:bkar1rm)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5604)*

**Pull request merged**
