### PR TITLE
Added library that is typically bundled with Matlab

### PR DESCRIPTION
**Pull request by nikos-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6322)

### CODE REVIEW

**Comment by nikos-tri** [comment]
+@jwnimmer feature review please

**Comment by soonho-tri** [comment]
I think we need to fix https://github.com/RobotLocomotion/drake/blob/master/drake/doc/ubuntu_trusty.rst as well?

**Comment by jwnimmer-tri** [comment]
BTW That's not my username.  -@jwnimmer +@jwnimmer-tri.

Anyway, +@jamiesnape for feature review please, as the prebuilt VTK expert.

I will do platform review once feature review is done.

**Comment by avalenzu** [comment]
Out of curiosity, what is this needed for? Were systems with MATLAB installed getting this library from the MATLAB installation?

**Comment by jamiesnape** [comment]
You are hit issues here? https://github.com/Kitware/VTK/blob/master/GUISupport/Qt/CMakeLists.txt#L69

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSfefD7O9b0YsmHnFM:-KmSfefD7O9b0YsmHnFN:b-suv37y) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd000d4dd26990ad0a795eb33888a27d189b113/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
> ```Shell
> zip
> zlib1g-dev
> libqt5x11extras5-dev
> ```

Alphabetize.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-:-KmSftcqp98DNP7rnqd4:b-l8tuia)*

**Comment by jwnimmer-tri** [comment]
The error was `external/director/bin/drake-visualizer: error while loading shared libraries: libQt5X11Extras.so.5: cannot open shared object file: No such file or directory`, from a Bazel-only user.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-:-KmSi5ZsJknGbGVP0cMM:b-d8uemk)*

**Comment by jamiesnape** [comment]
:lgtm:

(@soonho-tri Trusty builds use VTK 8 with Qt 4)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-:-KmSiFUaCuma3mciFfDu:b-naqlz5)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSjWqG982OeGkUdRjQ:-KmSjWqG982OeGkUdRjR:b-gp4f1e) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd000d4dd26990ad0a795eb33888a27d189b113/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
> ```Shell
> zip
> zlib1g-dev
> libqt5x11extras5-dev
> ```

Why do we need `libqt5x11extras5-dev` instead of just `libqt5x11extras5`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-:-KmSjayo50_5hd6jf5aI:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSjWqG982OeGkUdRjQ:-KmSsebX04JblVAAf9O7:b25gx6q) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd000d4dd26990ad0a795eb33888a27d189b113/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why do we need `libqt5x11extras5-dev` instead of just `libqt5x11extras5`?
</blockquote></details>

We probably don't. Looks like it uses `libQt5X11Extras.so.5`, not `libQt5X11Extras.so`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322)*

**Comment by nikos-tri** [comment]
Yes, systems with matlab installed were getting this from the matlab installation.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSjWqG982OeGkUdRjQ:-KmT2LJgcJhK41ayfhN6:b-qu7l2a) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We probably don't. Looks like it uses `libQt5X11Extras.so.5`, not `libQt5X11Extras.so`.
</blockquote></details>

I tried purging the *-dev and installing only libqt5x11extras5. It worked, so I am changing it.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSfefD7O9b0YsmHnFM:-KmT2p7_3HHlfHrjYOA-:bhy9ot6) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Alphabetize.
</blockquote></details>

Will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-:-KmT29ap6rzztX8j0-bJ:b-2j7rua)*

**Comment by jwnimmer-tri** [comment]
(Tip: in general, its not helpful to reply to a thread unless it's a resolution or a follow-up question -- in other words, something requiring reviewer to take action.  If you reply, it puts a red "action required" bubble in _our_ reviewable dashboard instead of yours, and then we have to reply in order to make the red bubble yours again.)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSfefD7O9b0YsmHnFM:-KmTItxHIsDxVaverhd_:b-ucfkn4) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Thanks.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSjWqG982OeGkUdRjQ:-KmTIuPG6aMyRDE6tlh7:b-ucfkn4) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

I tried purging the *-dev and installing only libqt5x11extras5. It worked, so I am changing it.
</blockquote></details>

Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-:-KmTIv74BV6xPk9DpUjI:b-9ebc3l)*

**Comment by nikos-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSfefD7O9b0YsmHnFM:-KmTMU10TG5h7GrGC9fz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Thanks.
</blockquote></details>

Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSjWqG982OeGkUdRjQ:-KmTMUiI_h7BNIeYW2Z3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Thanks.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322)*

**Comment by nikos-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSfefD7O9b0YsmHnFM:-KmTMaJnGjJZsxxwqewm:bqm8vy2) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
>  
>  
> valgrind
> valgrind
> zip
> zip
> zlib1g-dev
> zlib1g-dev
>  
> libqt5x11extras5-dev

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSfefD7O9b0YsmHnFM:-KmTMjjfd9s_q8KDWaSi:b6qud5y) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

>  
>  
> valgrind
> valgrind
> zip
> zip
> zlib1g-dev
> zlib1g-dev
>  
> libqt5x11extras5-dev

</blockquote></details>

Missing push?

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSjWqG982OeGkUdRjQ:-KmTMkS3SQlYroCzCrDo:b6qud5y) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Missing push?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSjWqG982OeGkUdRjQ:-KmTNoNAP1FAIaMNVlSo:b-9vx2vp) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing push?
</blockquote></details>

The (sorted) line still says `-dev`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322)*

**Comment by nikos-tri** [comment]
Looking to add it to the documentation files, but not sure which group of dependencies it should be with. Should it be with the ones required for Director (line 91) or just "Other" (line 81)?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSjWqG982OeGkUdRjQ:-KmTR_troUcueINlfL1r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The (sorted) line still says `-dev`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-:-KmTREDscLXyjdFwY-9s:b7pvhmc)*

**Comment by jwnimmer-tri** [comment]
If you're talking about Trusty -- you shouldn't add `libqt5x11extras5` to the docs, because:

Soonho wrote:
> I think we need to fix https://github.com/RobotLocomotion/drake/blob/master/drake/doc/ubuntu_trusty.rst as well?

Jamie replied:
> Trusty builds use VTK 8 with Qt 4.

If you want to set up a clean Trusty test environment (e.g., in Docker) and see if the `drake-visualizer` works, that's fine -- but until you've done that, you shouldn't try to guess whether anything is missing.

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-:-KmTVcWcYTSq8lLtEvsp:b96zgvz)*

**Comment by nikos-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6322#-KmSfefD7O9b0YsmHnFM:-KmTXHHRensjPLjjeyRW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af5fda2be0efb574d4f3f00284f15b8b7bcbebdc/setup/ubuntu/16.04/install_prereqs.sh#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing push?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6322)*

**Pull request merged**
