### PR TITLE
Share compiler arguments (not flags) with externals

### PR DESCRIPTION
**Pull request by tkoolen**
Add `CMAKE_C_COMPILER_ARG1` and `CMAKE_CXX_COMPILER_ARG1` to the list of variables that are shared with externals.

This was required to get `ccache` to work with OSX `clang` on my machine, as I have:
```bash
export CC="ccache clang -Qunused-arguments"
export CXX="ccache clang++ -Qunused-arguments"
```
in my `.bashrc`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3509)

### CODE REVIEW

**Comment by tkoolen** [comment]
@mwoehlke-kitware, could you review this?

**Comment by mwoehlke-kitware** [comment]
This should probably pass all defined arguments, not just the first. (I'd like @bradking's comments on a) if that will work and b) seems like a sane approach.)

That said, I wonder why you don't just pass the arguments to `CMAKE_<LANG>_FLAGS`?

**Comment by bradking** [comment]
> export CC="ccache clang -Qunused-arguments"
> export CXX="ccache clang++ -Qunused-arguments"

CMake doesn't support putting flags in the CC/CXX variables.  The `-Qunused-arguments` flag should go in `CFLAGS` and `CXXFLAGS` instead.

The `_ARG1` variables are left from a now-superseded hack to support `CC="ccache clang"`.  Since CMake 3.4, tools like ccache are better used through the [CMAKE_{C,CXX}_COMPILER_LAUNCHER](https://cmake.org/cmake/help/v3.6/variable/CMAKE_LANG_COMPILER_LAUNCHER.html) variable.  This allows `CMAKE_{C,CXX}_COMPILER` to refer to the actual compiler (`clang` and `clang++` in this example) and `ccache` to be used as its launcher.

It likely won't hurt to add `_ARG1` as proposed here because it will just be empty in normal use cases and can help to fix this not-officially-supported use case.

**Comment by tkoolen** [comment]
> This should probably pass all defined arguments, not just the first

Is `CMAKE_C_COMPILER_ARG${N}` actually a thing for N not equal to 1? It appeared that all of `clang++ -Qunused-arguments` ended up in `CMAKE_C_COMPILER_ARG1`.

> That said, I wonder why you don't just pass the arguments to CMAKE_<LANG>_FLAGS?

Because `ccache` itself is not a compiler, `ccache clang` is. Agree with @bradking  on the `-Qunused-arguments` thing, I just copied that from a how-to somewhere.

**Comment by bradking** [comment]
> Is CMAKE_C_COMPILER_ARG${N} actually a thing for N not equal to 1? 

No.  The `_ARG1` name is misleading.  It is actually all the arguments to the command.  See [here](https://gitlab.kitware.com/cmake/cmake/blob/v3.6.2/Modules/CMakeDetermineCCompiler.cmake#L52) where it uses [get_filename_component](https://cmake.org/cmake/help/v3.6/command/get_filename_component.html) with the `PROGRAM_ARGS` option to split off the arguments.

**Comment by mwoehlke-kitware** [comment]
MHO... especially after Brad's comment, this feels like a case of "don't do that". I'd prefer to not commit fixes for things you shouldn't be doing, even if they are Mostly Harmless¹.

(¹ Sorry, couldn't resist :wink:.)

>> That said, I wonder why you don't just pass the arguments to `CMAKE_<LANG>_FLAGS`?
>
> Because `ccache` itself is not a compiler, `ccache clang` is.

...but `-Qunused-arguments` is an argument to the compiler? Okay, I think I see; `clang`/`clang++` is showing up in the `_ARG1` stuff? That just seems broken :smile:. (As in... don't do that; use the `_LAUNCHER`s instead.)

...which suggests that this PR should instead pass the `_LAUNCHER` variables.

**Comment by tkoolen** [comment]
All I care about is that I can use `ccache` with `clang` on OSX. If this is not the right way to do it, feel free to submit a PR that does it the right way.

> but -Qunused-arguments is an argument to the compiler? 

See https://github.com/RobotLocomotion/drake/pull/3509#issuecomment-248054776.

**Comment by jwnimmer-tri** [comment]
FWIW, the TRI-internal instructions for using ccache on OS X are as follows:
```
OS X
    brew install ccache
    Add the following to your .bashrc: 
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
        export CACHE_CPP2=yes
    Make sure your .bash_profile is running your .bashrc:
        if [ -f ~/.bashrc ]; then . ~/.bashrc; fi 
```

We used to have that on a "tips" page in Drake docs, but it wasn't covered by CI, and got bikeshedded, so we removed it.

**Comment by RussTedrake** [comment]
i would like to see the ccache instructions back on the main page, even if they have a note saying it's not covered by CI.  otherwise there are too many places to look when setting up a new machine.

**Comment by jwnimmer-tri** [comment]
#2640 would be an opportunity to add in ccache instructions directly into a "developer-only" workflow.  Alternatively, we could have the `setup/ubuntu/16.04/install_prereqs.sh` do the right thing (and add OS X setup to match).

**Comment by jwnimmer-tri** [comment]
@bradking Assuming we want to explicitly document `ccache` setup for Drake developers again, is there a benefit to using `CMAKE_{C,CXX}_COMPILER_LAUNCHER` versus adding the magic `ccache` directory to the front of our `$PATH`?  When we last had this in Drake, we were recommending the magic path.

**Comment by tkoolen** [comment]
I somehow wasn't aware of this magic directory thing. FYI, that directory
is /usr/local/opt/ccache/libexec for homebrew-installed ccache on
OSX. Regardless of whether it's best practice, I'll switch to using the
magic directory instead of exporting CC/CXX so I don't have to wait for
code changes.

**Comment by bradking** [comment]
@jwnimmer-tri the magic directory approach is best IMO.  It presents a normal compiler to the build system that just happens to use additional optimizations internally.

**Pull request closed without merging**
