### PR TITLE
Rename DynamicConstraint to more specifically explain what it's doing.

### LINKED ISSUE #3117: Rename drake::systems::DynamicConstraint
From #3107 
"The Eval function at https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/constraint/dynamic_constraint.cc#L38 of DynamicConstraint is just for direct collocation method. This method assumes that the state trajectory is a piece-wise third order polynomial, and the control trajectory piece-wise first order polynomial. There can be other interpolation method for a different type of trajectory, and these interpolation method should also have a DynamicConstraint. So I am in favor of the name DynamicInterpolationConstraint or DynamicIntegrationConstraint. And the one in dynamic_constraint.cc should have a more specific name, like DirectCollocationConstraint."

### PR DESCRIPTION
**Pull request by sammy-tri**
Fixes #3117

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3123)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@hongkai-dai for feature review (holding off on platform review until I'm more certain that this is really what we want)

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-:-KOv5p3VqN1L4DscChib:bfnwo96)*

**Comment by hongkai-dai** [comment]
:lgtm: except a typo on collocation

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_swing_up.cc, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-KP-cif-5M6DSEndDz18:-KP-cif-5M6DSEndDz19:bfeedqo) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9df8fc5daa6e5fc08883cee08f7a332a678180/drake/examples/Pendulum/pendulum_swing_up.cc#L9)):*
> ```cpp
> #include "drake/examples/Pendulum/pendulum_swing_up.h"
> #include "drake/solvers/Function.h"
> #include "drake/systems/plants/constraint/direct_colocation_constraint.h"
> ```

collocation

---

*[drake/examples/Pendulum/pendulum_swing_up.cc, line 91 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-KP-cYB4OgeOELB9yIPu:-KP-cYB4OgeOELB9yIPv:bset41i) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9df8fc5daa6e5fc08883cee08f7a332a678180/drake/examples/Pendulum/pendulum_swing_up.cc#L91)):*
> ```cpp
>   dircol_traj->AddDynamicConstraint(
>       std::make_shared<
>       drake::systems::SystemDirectColocationConstraint<Pendulum>>(pendulum));
> ```

I think is it collocation, two "l". 

---

*[drake/examples/Pendulum/test/pendulum_dynamic_constraint_test.cc, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-KP-clbBIgJsRgQrI_zs:-KP-clbBIgJsRgQrI_zt:bnh2cma) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9df8fc5daa6e5fc08883cee08f7a332a678180/drake/examples/Pendulum/test/pendulum_dynamic_constraint_test.cc#L10)):*
> ```cpp
> #include "drake/core/Gradient.h"
> #include "drake/examples/Pendulum/Pendulum.h"
> #include "drake/systems/plants/constraint/direct_colocation_constraint.h"
> ```

collocation. Same for the rest of the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-:-KP-d183Gbcg3ir6FMwR:b-uh49jb)*

**Comment by sammy-tri** [comment]
Actually, I used the spelling from the class comment in MATLAB for DircolTrajectoryOptimization.  A quick search seems to indicate that the "ll" form seems to be the common spelling in this case (as you've pointed out)

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_swing_up.cc, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-KP-cif-5M6DSEndDz18:-KPDdX2W4KAVgmMbhUXV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9df8fc5daa6e5fc08883cee08f7a332a678180/drake/examples/Pendulum/pendulum_swing_up.cc#L9)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> collocation
</details>
Done.

---

*[drake/examples/Pendulum/pendulum_swing_up.cc, line 91 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-KP-cYB4OgeOELB9yIPu:-KPDdXkTGaioBECyeY-f:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9df8fc5daa6e5fc08883cee08f7a332a678180/drake/examples/Pendulum/pendulum_swing_up.cc#L91)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> I think is it collocation, two "l". 
</details>
Done.

---

*[drake/examples/Pendulum/test/pendulum_dynamic_constraint_test.cc, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-KP-clbBIgJsRgQrI_zs:-KPDdYM2wQrgcf8x0Rax:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9df8fc5daa6e5fc08883cee08f7a332a678180/drake/examples/Pendulum/test/pendulum_dynamic_constraint_test.cc#L10)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> collocation. Same for the rest of the PR.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-:-KPDaZma9kPYuYdY4xrJ:b-a4kml9)*

**Comment by sammy-tri** [comment]
+@sherm1 for platform review

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-:-KPDdb3MgzT--n3GtgyF:buasbda)*

**Comment by sherm1** [comment]
Platform review: :lgtm:

---

Reviewed 3 of 13 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3123#-:-KPGUVjOtrcOWUJ_uBo5:bhiddle)*

**Pull request merged**
