### PR TITLE
solvers: add some missing SDP bindings (LMI and diagonal dominance)

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-Mbi8cak9LpOv9uhiwhx:b-81zjv5)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Oops, I filed #15146 which also adds LinearMatrixInequalities. I will file a PR to this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-MbiC8E05Tia3H1K7k7S:b-x8rsnh)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Oops, my PR #15146 has been merged. Could you rebase this PR? Also it just needs a lint brush on mathematical_program.h

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-MbiSMJpCUX5-g45lYEV:baa8zi0)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
updated.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-MblvRWY7hUy1YwnZPhD:b-cypxrc)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: Thanks for the updates. +@soonho-tri for platform review please, thanks

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-MblwTCt55W9-rMsgoWv:b5xbo8m)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
FYI, `//solvers:py/mathematical_program_cpplint` failed.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-Mblyzb26efc3jUwfba4:b6joai4)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @RussTedrake)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-Mbm21f01ekt81uvNbq-:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
oops.  thanks soonho!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-Mbm5m637VJ_86g5Se3x:b-o3kays)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
the test failure looks like a flake (meshcat-visualizer timeout).  but i had to look at the raw console output as the cdash view seemed broken.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-Mbm8VKu7pCrTtiJXmo2:b-yf6mft)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15150#-:-MbmMLjDB-fmyoPphSgo:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Pull request merged**
