### PR TITLE
updated gurobi submodule

### PR DESCRIPTION
**Pull request by psiorx**
This should unbreak builds that include gurobi.

### CODE REVIEW

**Comment by psiorx** [comment]
@RussTedrake Any idea why this is failing on the mac build servers?  It worked on @DiitsGp's mac.

**Comment by RussTedrake** [comment]
i see this in the error log:

/bin/sh: line 0: cd: /tmp/drake-1413-18191/externals/gurobi/gurobi605/mac64: No such file or directory

**Comment by psiorx** [comment]
Hmm... looks like its using the old gurobi in your home directory.

**Comment by RussTedrake** [comment]
ah.  will update it (and the build server script)

**Comment by RussTedrake** [comment]
ok.  i’ve updated them.  give it another shot?

**Comment by psiorx** [comment]
It's throwing a python error on drake001 from the calling the `setup.py` that's included in the new gurobi tarball.  Drake005 seems to be fine with the python file.  I noticed the versions of python differ between the two build servers.

**Comment by RussTedrake** [comment]
I did `brew update` then got
```
drake001% brew upgrade python
Error: python 2.7.10_2 already installed
```

**Comment by RussTedrake** [comment]
all builds are broken until this is pulled.  but i need help resolving the drake001 issue.

**Pull request merged**
