### PR TITLE
update val qp controller to work with the val simulator

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
patched joint_level_controller_system.h to work with
valkyrie_simulation in exampls/Valkyrie
changed the nominal state to match the simulators.
removed dummy simulator.

@hongkai-dai for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4202)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_system.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4202#-KX7pLjnm9JwTN0_5Xdq:-KX7pLjnm9JwTN0_5Xdr:bez635g) ([raw file](https://github.com/robotlocomotion/drake/blob/db1f00ae21cf70a584a2708508e8c64e4bc17e11/drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_system.h#L61)):*
> ```objc
> 
>     Vector3<double> com_err = desired_com_ - robot_status->com();
>     Vector3<double> comd_err = -robot_status->comd();
> ```

I do not fully understand this part, why the desired com velocity is set to be zero? I thought when solving the linear inverted pendulum with desired ZMP location, we also get a non-zero desired CoM velocity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4202)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_system.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4202#-KX7pLjnm9JwTN0_5Xdq:-KX7y70J6z-fjYMz5Cpu:b2tww6f) ([raw file](https://github.com/robotlocomotion/drake/blob/db1f00ae21cf70a584a2708508e8c64e4bc17e11/drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_system.h#L61)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> I do not fully understand this part, why the desired com velocity is set to be zero? I thought when solving the linear inverted pendulum with desired ZMP location, we also get a non-zero desired CoM velocity.
</details>
Oooh, I should make this clearer, but this is a stationary thing. It's not supposed to move. 
I will need to make this proper with other plans. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4202)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_system.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4202#-KX7pLjnm9JwTN0_5Xdq:-KX7yu9qDGL4eNDwW9ZO:b-impiao) ([raw file](https://github.com/robotlocomotion/drake/blob/db1f00ae21cf70a584a2708508e8c64e4bc17e11/drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_system.h#L61)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> Oooh, I should make this clearer, but this is a stationary thing. It's not supposed to move. 
> I will need to make this proper with other plans. 
</details>
I see, could you add a TODO here, that in the future we will pass a `desired_comd_`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4202)*

**Comment by siyuanfeng-tri** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_system.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4202#-KX7pLjnm9JwTN0_5Xdq:-KX7zwNlDw18_fbyNQdB:b-q1jklj) ([raw file](https://github.com/robotlocomotion/drake/blob/db1f00ae21cf70a584a2708508e8c64e4bc17e11/drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_system.h#L61)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> I see, could you add a TODO here, that in the future we will pass a `desired_comd_`.
</details>
This will need to be major reworked. This is will probably be a skeleton interface thingy. I added a todo. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4202)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4202#-:-KX80tk5HT8YXpVvVdFi:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4202)*

**Comment by siyuanfeng-tri** [comment]
@ggould-tri for platform review, thanks

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4202#-:-KX86fVlj4xszqYSLiMp:b-gipf4u)*

**Comment by ggould-tri** [comment]
I don't quite follow the logic or math here, I'm afraid, but from a platform review perspective it certainly adheres to conventions as much as anything under `examples` does.  :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4202#-:-KXBTcmsOyf4Q-22LKYZ:b2p2mzu)*

**Comment by siyuanfeng-tri** [comment]
thanks grant, there isn't much math updates here. mostly just getting rid of the old dummy simulator, since we have a real one now :) 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4202#-:-KXBU43lV6VogaMDYCcR:bcv69z2)*

**Pull request merged**
