### PR TITLE
Update to Bazel 0.4.5

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5808)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by BetsyMcPhail** [comment]
+@david-german-tri for feature review and +@ggould-tri for platform review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5808#-:-KhYe4o-W-nlCQBMumtc:bq0v4di)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5808#-:-KhYgYOsF9NMAt-RJP-Y:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5808#-:-KhZJRUBRXSVLTb6ZgWW:bnfp4nl)*

**Pull request merged**
