### PR TITLE
Add python binding for static equlibrium problem.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Also use ComputeSignedDistancePairwiseClosestPoints() to avoid redundant computation.

EDIT(eric):
Towards #13473

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140#-:-MIPeFNt7zTqt7n4VldT:b-8hqkno)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
I've added a reference to #13473 - sweet!

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done, will come back tomorrow after deep-dive, if that's OK?

> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140#-:-MIPjEVX3WnYiYgJTvtU:bi3s1g)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/multibody/BUILD.bazel, line 156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIPiVq4EMoVMXHViZnH:-MIPiVq5DVZbvzhTcbVL:bsizr1l) ([raw file](https://github.com/robotlocomotion/drake/blob/4cd3775deb30a20523ebc6a8647f1ef38721162e/bindings/pydrake/multibody/BUILD.bazel#L156)):*
> ```Starlark
>         "//bindings/pydrake:documentation_pybind",
>         "//bindings/pydrake/common:default_scalars_pybind",
>         "//bindings/pydrake/common:sorted_pair_pybind",
> ```

nit This is unused?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIPipD0Eb0JA8eGhwBP:-MIPipD0Eb0JA8eGhwBQ:bc29mef) ([raw file](https://github.com/robotlocomotion/drake/blob/4cd3775deb30a20523ebc6a8647f1ef38721162e/bindings/pydrake/multibody/test/optimization_test.py#L86)):*
> ```Python
> 
> def quaternion_squared_norm(x):
>     return [x[0] * x[0] + x[1] * x[1] + x[2] * x[2] + x[3] * x[3]]
> ```

nit I think `[np.sum(x**2)]` should do the trick too, even for autodiff?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIPijLc9QV1DigX3ecT:-MIPijLc9QV1DigX3ecU:b-30olwz) ([raw file](https://github.com/robotlocomotion/drake/blob/4cd3775deb30a20523ebc6a8647f1ef38721162e/bindings/pydrake/multibody/test/optimization_test.py#L90)):*
> ```Python
> 
> class TestStaticEquilibriumProblem(unittest.TestCase):
>     def test1(self):
> ```

nit Can you rename these to `test_one_box` and `test_two_boxes`?

**Review by hongkai-dai — COMMENTED** [review]
Sure thing, take your time.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140#-:-MIRY9ElEkW4W6E6Q2tF:b77f7kh)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIPipD0Eb0JA8eGhwBP:-MIRXp513Cuj1L_IFORh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cd3775deb30a20523ebc6a8647f1ef38721162e/bindings/pydrake/multibody/test/optimization_test.py#L86)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I think `[np.sum(x**2)]` should do the trick too, even for autodiff?
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with namely some stylistic comments

> Reviewed 1 of 9 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140#-:-MIebPpD1vWxHaYly30d:b-etoo8d)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_7h05FTAI6OYM3YN:-MIe_7h05FTAI6OYM3YO:b-3p6cm3) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L25)):*
> ```Python
> 
> 
> def construct_environment(masses: list, box_sizes: list):
> ```

BTW `typing.List` may be more appropriate here
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 46 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeZ87538yXx4YX0Mfq:-MIeZ87538yXx4YX0Mfr:b-yy7c7q) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L46)):*
> ```Python
> 
>     # Add boxes
>     assert(isinstance(masses, list))
> ```

`assert(expr)` is a bit dangerous, because it may encourage `assert(expr, message)`.

Can you instead write `assert expr` here and everywhere else in this PR?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeZfzUCL96FvWrnn4_:-MIeZfzUCL96FvWrnn4a:b-am47ok) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L50)):*
> ```Python
>     assert(len(masses) == len(box_sizes))
>     num_boxes = len(masses)
>     boxes = [None] * num_boxes
> ```

BTW There's little cost saving to `[None] * N`.

Consider instead just using a local, e.g.` box, geometry_id`, and then appending at the end? `boxes.append(box)`, etc.?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeZs8U-MfUbS8lH1Ae:-MIeZs8VBgaaqGulWMbq:bdbsxh) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L59)):*
> ```Python
>         box_shape = Box(box_sizes[i][0], box_sizes[i][1], box_sizes[i][2])
>         boxes_geometry_id[i] = plant.RegisterCollisionGeometry(
>             boxes[i], RigidTransform(), box_shape, box_name + "_box",
> ```

nit Consider using f-strings here: `f"{box_name}_box"` (here and elsewhere)
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_Mc_5PJsUnFiknd3:-MIe_Mc_5PJsUnFiknd4:bo1dliv) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L68)):*
> ```Python
>             [1, 1, 1], [1, 1, -1], [1, -1, 1], [1, -1, -1], [-1, 1, 1],
>             [-1, -1, 1], [-1, 1, -1], [-1, -1, -1]]) *\
>             box_sizes[i].reshape((1, -1)).repeat(8, axis=0)/2
> ```

nit This smells a bit too cute.

Can you instead do something like this?
```
w, h, d = box_sizes[i]
vertices = 0.5 * np.array([
  [w, h, d],
  [w, h, -d],
  ...
])
```

That, or could you try to ensure you've shaped things correctly for broadcasting, and don't need `.repeat`?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 103 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_y48CjAGtKwC0tuF:-MIe_y48CjAGtKwC0tuG:b-1eldrt) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L103)):*
> ```Python
>         # Ignore the collision between box-box, since currently Drake doesn't
>         # support box-box collision with AutoDiffXd.
>         ignored_collision_pairs = {tuple((
> ```

nit `tuple((a, b))` is redundant. Can you instead write this as `(a, b)`?

Wrapped in the set: `{(a, b)}`?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 122 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeayeI8kNf70SLWEKn:-MIeayeI8kNf70SLWEKo:bwm5rlj) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L122)):*
> ```Python
>         result = mp.Solve(dut.prog())
>         self.assertTrue(result.is_success())
>         q_sol = result.GetSolution(dut.q_vars())
> ```

`q` is used sometimes to mean minimal coordinates for floating-body, or quaternion.

Can you instead use `q` to mean general coordinates, and `quat` to mean quaternion?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 124 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeaBbc0SQH0YONNDbC:-MIeaBbc0SQH0YONNDbD:b-96ia1a) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L124)):*
> ```Python
>         q_sol = result.GetSolution(dut.q_vars())
>         self.assertAlmostEqual(np.linalg.norm(q_sol[:4]), 1.)
>         np.testing.assert_allclose(q_sol[6], 0.05, atol=0.002)
> ```

nit For readability, can you add a helper function to split this up so you don't need raw indexing inline?

e.g.
```
def split_se3(q_se3):
    assert q_se3.shape == (7,)
    quat = q_se3[:4]
    xyz = q_se3[4:]
    return quat, xyz

...
quat0 = ...
xyz0 = ...
quat_vars, xyz_vars = split_se3(dut.q_vars())
SetInitialGuess(quat_vars, quat0)
SetInitialGuess(xyz_vars, [0, 0, 0.3])

...
quat_sol, xyz_sol = split_se3(result.GetSoltuion(dut.q_vars()))  # Or other way
self.assertAlmostEqual(norm(quat_sol), 1.0)
assert_allclose(xyz_sol[2], 0.05, atol=0.002)
```
___
*[multibody/optimization/contact_wrench.h, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeZPEI8dtHdbXEZRxW:-MIeZPEI8dtHdbXEZRxX:b2q2zjj) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/multibody/optimization/contact_wrench.h#L32)):*
> ```objc
>   BodyIndex bodyA_index;
>   BodyIndex bodyB_index;
>   // The position of the point Cb (where the wrench is
> ```

All of these members should have public docs (`///` and `/** */`).

Can you use public documentation here, and can you move the docstrings from the class to the members themselves?
___
*[multibody/optimization/static_equilibrium_constraint.cc, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIebH3K1yBvimcy1Q34:-MIebH3K1yBvimcy1Q35:b-r86xxp) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/multibody/optimization/static_equilibrium_constraint.cc#L69)):*
> ```cpp
>   const int lambda_start_index_in_x =
>       plant_->num_positions() + plant_->num_actuated_dofs();
>   for (const auto& [contact_pair, evaluator] :
> ```

BTW Structured bindings yay!

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_7h05FTAI6OYM3YN:-MIgR94o3RJWMExfXnu3:bixq1vb) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW `typing.List` may be more appropriate here
</blockquote></details>

Done. May I ask why `typing.List` is better than `list`?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 46 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeZ87538yXx4YX0Mfq:-MIgRLFN5Y_dBQc_cbeg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L46)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`assert(expr)` is a bit dangerous, because it may encourage `assert(expr, message)`.

Can you instead write `assert expr` here and everywhere else in this PR?
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeZfzUCL96FvWrnn4_:-MIgRbkaCcADNNMmNPcd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L50)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW There's little cost saving to `[None] * N`.

Consider instead just using a local, e.g.` box, geometry_id`, and then appending at the end? `boxes.append(box)`, etc.?
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_Mc_5PJsUnFiknd3:-MIgS32i0zbDclahfMVg:b-t0dwou) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L68)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This smells a bit too cute.

Can you instead do something like this?
```
w, h, d = box_sizes[i]
vertices = 0.5 * np.array([
  [w, h, d],
  [w, h, -d],
  ...
])
```

That, or could you try to ensure you've shaped things correctly for broadcasting, and don't need `.repeat`?
</blockquote></details>

May I ask why the existing code is not good?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 103 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_y48CjAGtKwC0tuF:-MIgWKMi-KQSfHObBl9r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L103)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `tuple((a, b))` is redundant. Can you instead write this as `(a, b)`?

Wrapped in the set: `{(a, b)}`?
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 122 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeayeI8kNf70SLWEKn:-MIgWQ9YD7gXIDf0C0Zz:bf1v5la) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L122)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`q` is used sometimes to mean minimal coordinates for floating-body, or quaternion.

Can you instead use `q` to mean general coordinates, and `quat` to mean quaternion?
</blockquote></details>

Here `q` is the general coordinates. It includes the position/quaternion of all the bodies.
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 124 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeaBbc0SQH0YONNDbC:-MIgXgOR1bM2Be4SXKJ7:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L124)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For readability, can you add a helper function to split this up so you don't need raw indexing inline?

e.g.
```
def split_se3(q_se3):
    assert q_se3.shape == (7,)
    quat = q_se3[:4]
    xyz = q_se3[4:]
    return quat, xyz

...
quat0 = ...
xyz0 = ...
quat_vars, xyz_vars = split_se3(dut.q_vars())
SetInitialGuess(quat_vars, quat0)
SetInitialGuess(xyz_vars, [0, 0, 0.3])

...
quat_sol, xyz_sol = split_se3(result.GetSoltuion(dut.q_vars()))  # Or other way
self.assertAlmostEqual(norm(quat_sol), 1.0)
assert_allclose(xyz_sol[2], 0.05, atol=0.002)
```
</blockquote></details>

Done. Thanks.
___
*[multibody/optimization/contact_wrench.h, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeZPEI8dtHdbXEZRxW:-MIgYNmwEGjNHw3_F7eF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/multibody/optimization/contact_wrench.h#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

All of these members should have public docs (`///` and `/** */`).

Can you use public documentation here, and can you move the docstrings from the class to the members themselves?
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_7h05FTAI6OYM3YN:-MIztEid2h3pJbVBxeqo:b-1ewuu4) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L25)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. May I ask why `typing.List` is better than `list`?
</blockquote></details>

OK Because it's actually used for type annotations, and can also contain the inner type.

In the original proposal, `List[...]` appears more frequently than `list`:
https://www.python.org/dev/peps/pep-0484/

That being said, in Drake, we have zero guidance on type annotations, and I myself don't plan on updating that soon, so this may all be inconsequential for the time being.
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_Mc_5PJsUnFiknd3:-MIztie2DvRCJpQqcugk:bz2b72s) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L68)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

May I ask why the existing code is not good?
</blockquote></details>

I find it hard to read (all the corners are squashed on one line, box_sizes reshaped and repeated, also on one line).

My suggestion above is less cute, and drives towards what is being done (and also has easier-to-read whitespace for me).

Alternatively, then, consider splitting off your resized stuff, and use `np.tile` for more brevity, e.g.:
```
box_size = np.tile((8, 1), box_sizes[i])
vertices = box_size * np.array([
  [ ... ]
])
```

Feel free to dimiss.
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 122 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIeayeI8kNf70SLWEKn:-MIzuQiBAJgzr_cwjxKk:brl1wuc) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L122)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Here `q` is the general coordinates. It includes the position/quaternion of all the bodies.
</blockquote></details>

OK Yeah, sorry - by that I meant "instead, use these symbols exclusively".

Thanks!
___
*[multibody/optimization/contact_wrench.h, line 17 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIzukgs066hN7vJSd5Y:-MIzukgs066hN7vJSd5Z:blrngqg) ([raw file](https://github.com/robotlocomotion/drake/blob/261b131a881c3911e603ae1c8de0203f9c00f503/multibody/optimization/contact_wrench.h#L17)):*
> ```objc
> struct ContactWrench {
>   /**
>    * @param bodyA_index_in The index of Body A.
> ```

BTW You may want to consider removing these docstrings too?

Or perhaps explicitly referring to the docstrings of the attributes?

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140#-:-MJ0B5R3AoVjn-2txBjV:b-c9pjop)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_7h05FTAI6OYM3YN:-MJ06orR4pYG1SXUIQaJ:b-lg05o9) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Because it's actually used for type annotations, and can also contain the inner type.

In the original proposal, `List[...]` appears more frequently than `list`:
https://www.python.org/dev/peps/pep-0484/

That being said, in Drake, we have zero guidance on type annotations, and I myself don't plan on updating that soon, so this may all be inconsequential for the time being.
</blockquote></details>

I see, thanks for the explanation.
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIe_Mc_5PJsUnFiknd3:-MJ0Aftc5g542_UtTvss:bnuxjhv) ([raw file](https://github.com/robotlocomotion/drake/blob/659287487b852a39e6f2e70e5f982a3b1cbe145e/bindings/pydrake/multibody/test/optimization_test.py#L68)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I find it hard to read (all the corners are squashed on one line, box_sizes reshaped and repeated, also on one line).

My suggestion above is less cute, and drives towards what is being done (and also has easier-to-read whitespace for me).

Alternatively, then, consider splitting off your resized stuff, and use `np.tile` for more brevity, e.g.:
```
box_size = np.tile((8, 1), box_sizes[i])
vertices = box_size * np.array([
  [ ... ]
])
```

Feel free to dimiss.
</blockquote></details>

Done. Thanks! I used `np.tile`.
___
*[multibody/optimization/contact_wrench.h, line 17 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MIzukgs066hN7vJSd5Y:-MJ0B41Z-r5iup0fRNpl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/261b131a881c3911e603ae1c8de0203f9c00f503/multibody/optimization/contact_wrench.h#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW You may want to consider removing these docstrings too?

Or perhaps explicitly referring to the docstrings of the attributes?
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 9 files at r1, 1 of 2 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140#-:-MJ3SVrH4WHCqr88STDp:bnfp4nl)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/optimization_py.cc, line 48 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MJ3JqNo1HYTZG1_6De5:-MJ3JqNo1HYTZG1_6De6:b-wiq8c7) ([raw file](https://github.com/robotlocomotion/drake/blob/21c874acf2ded91ce5e6bbeb7b52e14680281d8d/bindings/pydrake/multibody/optimization_py.cc#L48)):*
> ```cpp
>             py::arg("plant"), py::arg("context"),
>             py::arg("ignored_collision_pairs"),
>             // Keep alive, referece: `self` keeps `plant` and `context` alive.
> ```

nit typo "referece"
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 92 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MJ3RszM8Y0b8KVIFerK:-MJ3RszNAGb6mbQ-16gc:b-vs2kp6) ([raw file](https://github.com/robotlocomotion/drake/blob/21c874acf2ded91ce5e6bbeb7b52e14680281d8d/bindings/pydrake/multibody/test/optimization_test.py#L92)):*
> ```Python
> 
> class TestStaticEquilibriumProblem(unittest.TestCase):
>     def split_se3(self, q_se3):
> ```

It seems unusual for this to be a class member function when it doesn't use `self`.

**Review by sammy-tri — COMMENTED** [review]
(well, pending the couple of minor open issues, that is)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140#-:-MJ3SrQd25nIMgjQjR0r:bt08yzd)* status: 2 unresolved discussions (waiting on @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)* status: 2 unresolved discussions (waiting on @hongkai-dai and @sammy-tri)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 92 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MJ3RszM8Y0b8KVIFerK:-MJ3TLnr2MbdBs1FUc8Q:bs1d9me) ([raw file](https://github.com/robotlocomotion/drake/blob/21c874acf2ded91ce5e6bbeb7b52e14680281d8d/bindings/pydrake/multibody/test/optimization_test.py#L92)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems unusual for this to be a class member function when it doesn't use `self`.
</blockquote></details>

FWIW I don't think this comment should be blocking? It's just test code.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)* status: 2 unresolved discussions (waiting on @hongkai-dai and @sammy-tri)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 92 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MJ3RszM8Y0b8KVIFerK:-MJ3VlBL0ugMU_6nWFpc:b-54u86c) ([raw file](https://github.com/robotlocomotion/drake/blob/21c874acf2ded91ce5e6bbeb7b52e14680281d8d/bindings/pydrake/multibody/test/optimization_test.py#L92)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FWIW I don't think this comment should be blocking? It's just test code.
</blockquote></details>

Or maybe better stated:
I do this in other places, and I find it generally OK to have `self` for methods, esp. for test cases.
If you have an objection, I guess I'd like to know why so I can see if I should reconsider for myself.

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 92 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MJ3RszM8Y0b8KVIFerK:-MJ3Wlgr3A5ug0TKRDwe:b-npx495) ([raw file](https://github.com/robotlocomotion/drake/blob/21c874acf2ded91ce5e6bbeb7b52e14680281d8d/bindings/pydrake/multibody/test/optimization_test.py#L92)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Or maybe better stated:
I do this in other places, and I find it generally OK to have `self` for methods, esp. for test cases.
If you have an objection, I guess I'd like to know why so I can see if I should reconsider for myself.
</blockquote></details>

An unused function argument which isn't called out as deliberately unused strikes me as a readability defect in that it could confuse someone else who reads the code in the future.  If you still want to write `self.split_se3` at the call site, document the intention of the implementation with `@staticmethod`.

I probably should have written something more like that to begin with...  my original comment was not well phrased.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)* status: 1 unresolved discussion (waiting on @sammy-tri)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 92 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MJ3RszM8Y0b8KVIFerK:-MJ9Wac418Uzz6T7qb-u:bz8jjnd) ([raw file](https://github.com/robotlocomotion/drake/blob/21c874acf2ded91ce5e6bbeb7b52e14680281d8d/bindings/pydrake/multibody/test/optimization_test.py#L92)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

An unused function argument which isn't called out as deliberately unused strikes me as a readability defect in that it could confuse someone else who reads the code in the future.  If you still want to write `self.split_se3` at the call site, document the intention of the implementation with `@staticmethod`.

I probably should have written something more like that to begin with...  my original comment was not well phrased.
</blockquote></details>

Done. I moved this method outside of the class.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)* status: 1 unresolved discussion (waiting on @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Dismissed @sammy-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14140)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),EricCousineau-TRI(platform)

___
*[bindings/pydrake/multibody/test/optimization_test.py, line 92 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14140#-MJ3RszM8Y0b8KVIFerK:-MJCgEXV6r_4zM98gVi5:b-wsvasg) ([raw file](https://github.com/robotlocomotion/drake/blob/21c874acf2ded91ce5e6bbeb7b52e14680281d8d/bindings/pydrake/multibody/test/optimization_test.py#L92)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I moved this method outside of the class.
</blockquote></details>

Thanks for the explanation!

**Pull request merged**
