### PR TITLE
[C-IRIS] move c_iris_separating_plane out of dev.

### PR DESCRIPTION
**Pull request by hongkai-dai**
We define how to compute the separating plane as polynomial of configuration variable s.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18852)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@EricCousineau-TRI for platform review please, thanks!

This code previously lives in the dev folder and has been feature-reviewed. I move it out of dev folder so it requires platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-:-NOvBF4j0maoq2FBAcu2:bc5s6iy)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done, PTAL!

> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-:-NOwa_Ja9xVPKko_9NPq:b-v6scke)* status: 9 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`geometry/optimization/c_iris_separating_plane.h` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOw_drO-n3ZfAOSBGDj:-NOw_drO-n3ZfAOSBGDk:b-oijxg7) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L12)):*
> ```objc
> namespace optimization {
> /** The separating plane aᵀx + b ≥ δ, aᵀx+b ≤ −δ has parameters a and b. These
>  parameters a polynomial function of s with the specified degree.
> ```

nit "parameters" => "parameterize"?
___
*[`geometry/optimization/c_iris_separating_plane.h` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOw_s_oAGvrdaW1rhVs:-NOw_s_oAGvrdaW1rhVt:b-3lylv2) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L12)):*
> ```objc
> namespace optimization {
> /** The separating plane aᵀx + b ≥ δ, aᵀx+b ≤ −δ has parameters a and b. These
>  parameters a polynomial function of s with the specified degree.
> ```

From reading function, unittest, and docstrings, I'm still have trouble coming up with an example of `s`.

Can you briefly explain more what `s` could be, or perhaps cross-reference a paper or another function in Drake?
___
*[`geometry/optimization/c_iris_separating_plane.h` line 15 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOwZ7xl4Mv4APklyzJ-:-NOwZ7xl4Mv4APklyzJ0:b4bw2zz) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L15)):*
> ```objc
>  */
> enum class SeparatingPlaneOrder {
>   kAffine,  ///< a and b are affine function of s.
> ```

nit Why enum with only one value?

Is there a TODO missing here?
___
*[`geometry/optimization/c_iris_separating_plane.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOwZEdU3yx4fZ7tUx4x:-NOwZEdU3yx4fZ7tUx4y:b4gpsfj) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L19)):*
> ```objc
> 
> /**
>  One collision geometry is on the "positive" side of the separating plane,
> ```

Documentation a bit unclear - this is an incomplete sentence?

Should use GSG active voice? e.g.
```
Provides a way to determine when ...
```
___
*[`geometry/optimization/c_iris_separating_plane.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOwZUIX6IhSsfxRJ0yQ:-NOwZUIX6IhSsfxRJ0yR:bmlroep) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L29)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(CIrisSeparatingPlane)
> 
>   CIrisSeparatingPlane() = default;
> ```

I don't understand why this has a default constructor as well as a non-default constructor.

Why not just remove the constructor outright?
___
*[`geometry/optimization/c_iris_separating_plane.h` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOwZmc-CXOF9Vsc1bHA:-NOwZmc-CXOF9Vsc1bHB:b-f5aaxr) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L63)):*
> ```objc
> 
> /**
>  Computes the parameter a, b in the plane { x | aᵀx+b=0 }.
> ```

nit Missing plural? "parameters"
___
*[`geometry/optimization/c_iris_separating_plane.h` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOwZqOz3zzFQt129TIp:-NOwZqOz3zzFQt129TIq:b-j6t55i) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L64)):*
> ```objc
> /**
>  Computes the parameter a, b in the plane { x | aᵀx+b=0 }.
>  a and b are both polynomials of `s_for_plane`. The coefficient of these
> ```

nit "coefficients"?

(other missing plurals below, e.g. "coefficients")
___
*[`geometry/optimization/c_iris_separating_plane.h` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOw_3roE3U7cmY8okrC:-NOw_3roE3U7cmY8okrD:b-q5k5uk) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L66)):*
> ```objc
>  a and b are both polynomials of `s_for_plane`. The coefficient of these
>  polynomials are in `decision_variables`.
>  The possible combination of T, U, V are
> ```

nit `T, U, V` are a bit ambiguous, and I'm not sure if I've seen the generic 3-tuple elsewhere.

If wanting to stick w/ shorthand, consider using something like `D, S, V`? (decision, s for plane, value)
Otherwise, expand to `Decision, 
___
*[`geometry/optimization/c_iris_separating_plane.h` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOw_ici4-WkdLpPkMd-:-NOw_ici4-WkdLpPkMd0:bz2rcl0) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L73)):*
> ```objc
> template <typename T, typename U, typename V>
> void CalcPlane(const VectorX<T>& decision_variables,
>                const VectorX<U>& s_for_plane, SeparatingPlaneOrder order,
> ```

nit Above, in docstring, you say just `s`. However, you say `s_for_plane`. Why is the qualifier needed?

Consider removing, keeping just as `s`?
Alternatively, consider changing above docs to use `s_for_plane` as well.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18852)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[`geometry/optimization/c_iris_separating_plane.h` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOw_s_oAGvrdaW1rhVs:-NOwsWV6Dh8lQpClnUhR:b-8krdrn) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L12)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

From reading function, unittest, and docstrings, I'm still have trouble coming up with an example of `s`.

Can you briefly explain more what `s` could be, or perhaps cross-reference a paper or another function in Drake?
</blockquote></details>

Done. I added the reference at the top of the file.
___
*[`geometry/optimization/c_iris_separating_plane.h` line 15 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOwZ7xl4Mv4APklyzJ-:-NOwss2n43u6FpYUYO1z:bjsqpb) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why enum with only one value?

Is there a TODO missing here?
</blockquote></details>

Done. In the future we <i> might </i> support other form, like kConstant, kQuadratic etc. But in our paper we find that kAffine has the best performance.
___
*[`geometry/optimization/c_iris_separating_plane.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOwZEdU3yx4fZ7tUx4x:-NOwtjbC64kQPR44y65H:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Documentation a bit unclear - this is an incomplete sentence?

Should use GSG active voice? e.g.
```
Provides a way to determine when ...
```
</blockquote></details>

Done.
___
*[`geometry/optimization/c_iris_separating_plane.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOwZUIX6IhSsfxRJ0yQ:-NOwx7c37lYvmskwjCV9:b-e59tzh) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I don't understand why this has a default constructor as well as a non-default constructor.

Why not just remove the constructor outright?
</blockquote></details>

Done. Good call. I removed the default constructor.
___
*[`geometry/optimization/c_iris_separating_plane.h` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOw_3roE3U7cmY8okrC:-NOwxBCQ-KCRPUGuLiRQ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L66)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `T, U, V` are a bit ambiguous, and I'm not sure if I've seen the generic 3-tuple elsewhere.

If wanting to stick w/ shorthand, consider using something like `D, S, V`? (decision, s for plane, value)
Otherwise, expand to `Decision, 
</blockquote></details>

Done.
___
*[`geometry/optimization/c_iris_separating_plane.h` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOw_ici4-WkdLpPkMd-:-NOwy4smAZz8z9jrLDsV:b-dbyrei) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L73)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Above, in docstring, you say just `s`. However, you say `s_for_plane`. Why is the qualifier needed?

Consider removing, keeping just as `s`?
Alternatively, consider changing above docs to use `s_for_plane` as well.
</blockquote></details>

Done. I changed them all to `s_for_plane`.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform +(status: single reviewer ok) 

> Reviewed 1 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-:-NOyRXOgALhy8Ll0Wfmg:b-ve6qt3)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

___
*[`geometry/optimization/c_iris_separating_plane.h` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOw_s_oAGvrdaW1rhVs:-NOyQyh6BZNqD6731WkT:b-ucfknh) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L12)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I added the reference at the top of the file.
</blockquote></details>

Thanks!
___
*[`geometry/optimization/c_iris_separating_plane.h` line 15 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18852#-NOwZ7xl4Mv4APklyzJ-:-NOyQx8OAevrAxG7YnuX:b-t0hygb) ([raw file](https://github.com/RobotLocomotion/drake/blob/23e3c1f984a3969fd60c470ad88a3e26e83054d7/geometry/optimization/c_iris_separating_plane.h#L15)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. In the future we <i> might </i> support other form, like kConstant, kQuadratic etc. But in our paper we find that kAffine has the best performance.
</blockquote></details>

OK Gotcha, thanks!

**Comment by jwnimmer-tri** [comment]
*[`geometry/optimization/c_iris_separating_plane.h` line 83 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18852#-NX6OCVC-VjcOvvLeq1f:-NX6OCVDDXVyoHf97BnY:bjr535b) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b6a2a7d239cd521a36d0e14708e41482cee96/geometry/optimization/c_iris_separating_plane.h#L83)):*
> ```objc
>  */
> template <typename D, typename S, typename V>
> void CalcPlane(const VectorX<D>& decision_variables,
> ```

FYI @EricCousineau-TRI this function violated https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions.  (The template arguments are not open-ended.)

My plan is to have #19526 fix it.

**Pull request merged**
