### PR TITLE
Updating MovingAverageFilter to allow data access.

### PR DESCRIPTION
**Pull request by rcory**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8787)

### CODE REVIEW

**Comment by rcory** [comment]
+@naveenoid for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8787#-:-LC9yBXv98PuXeBZVfAV:b-jlfufc)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8787#-:-LCAFY8o2-xlSIydP4Co:bnfp4nl)*

**Comment by rcory** [comment]
Looks like Siyuan got to it first!

-@naveenoid +@siyuanfeng-tri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8787#-:-LCAIRTRBdaq6G9k8u1K:bjcejc4)*

**Comment by rcory** [comment]
+@seancurtis-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8787#-:-LCAw_xV9Vfem0qJyGtY:b-tnzbcp)*

**Comment by SeanCurtis-TRI** [comment]
First pass done

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[manipulation/util/moving_average_filter.h, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8787#-LCB0B6V-INdqYD4QbaV:-LCB0B6V-INdqYD4QbaW:bd8su8z) ([raw file](https://github.com/robotlocomotion/drake/blob/4a65767496d23fe90ec47cbc754f2be3a95a0be0/manipulation/util/moving_average_filter.h#L54)):*
BTW That's some extra white space in the doxygen. Probably don't need the extra blank line (or on the next one, either).

There's also the possibility that [this guidance](http://drake.mit.edu/styleguide/cppguide.html#Function_Comments) applies here. Specifically: 

> These comments may be omitted only if the function is simple and obvious (e.g. simple accessors for obvious properties of the class).

That seems it might easily apply to `window()`. Possibly less so to `Result`.

---

*[manipulation/util/moving_average_filter.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8787#-LCB0tSX47IkDEPBgOyS:-LCB0tSX47IkDEPBgOyT:bsvx9p8) ([raw file](https://github.com/robotlocomotion/drake/blob/4a65767496d23fe90ec47cbc754f2be3a95a0be0/manipulation/util/moving_average_filter.h#L62)):*
> ```objc
>    *
>    */
>   T Result();
> ```

BTW 
1. You might consider renaming this to `moving_average()`. It more directly reflects the interpretation of the value *and* given the body of this function, cheap isn't bad.
2. The function should be declared const.

---

*[manipulation/util/moving_average_filter.cc, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8787#-LCB16mA-r7yp0b_mN7o:-LCB16mA-r7yp0b_mN7p:b-15fe11) ([raw file](https://github.com/robotlocomotion/drake/blob/4a65767496d23fe90ec47cbc754f2be3a95a0be0/manipulation/util/moving_average_filter.cc#L46)):*
> ```cpp
> 
> template <typename T>
> T MovingAverageFilter<T>::Result() { return (1.0 / window_.size()) * sum_; }
> ```

BTW Is there a reason this isn't simply defined inline?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8787#-:-LCB0dDW461_DnXjuIWk:b1ccr98)*

**Comment by rcory** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[manipulation/util/moving_average_filter.h, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8787#-LCB0B6V-INdqYD4QbaV:-LCEgrn4C_hcEfQ6U0ff:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a65767496d23fe90ec47cbc754f2be3a95a0be0/manipulation/util/moving_average_filter.h#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW That's some extra white space in the doxygen. Probably don't need the extra blank line (or on the next one, either).

There's also the possibility that [this guidance](http://drake.mit.edu/styleguide/cppguide.html#Function_Comments) applies here. Specifically: 

> These comments may be omitted only if the function is simple and obvious (e.g. simple accessors for obvious properties of the class).

That seems it might easily apply to `window()`. Possibly less so to `Result`.

</blockquote></details>

Done.

---

*[manipulation/util/moving_average_filter.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8787#-LCB0tSX47IkDEPBgOyS:-LCEgu6g0ycJ5FYBelUm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a65767496d23fe90ec47cbc754f2be3a95a0be0/manipulation/util/moving_average_filter.h#L62)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW 
1. You might consider renaming this to `moving_average()`. It more directly reflects the interpretation of the value *and* given the body of this function, cheap isn't bad.
2. The function should be declared const.
</blockquote></details>

Done.

---

*[manipulation/util/moving_average_filter.cc, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8787#-LCB16mA-r7yp0b_mN7o:-LCEiLd36VrD1nhHXTf5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a65767496d23fe90ec47cbc754f2be3a95a0be0/manipulation/util/moving_average_filter.cc#L46)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is there a reason this isn't simply defined inline?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8787)*

**Pull request merged**
