### PR TITLE
[solvers] Fix Gurobi console logging config to happen first

### LINKED ISSUE #22107: Gurobi Always Printing to Console
### What happened?

I've recently observed that when Gurobi is used to solve a MathematicalProgram, the verbose output is always printed to the console. @wernerpe also observed this behavior. For methods that require solving many optimization problems, the output completely clogs the console, and can even crash a jupyter notebook.

### Version

16e7281bcd

### What operating system are you using?

Ubuntu 22.04, Other

### What installation option are you using?

compiled from source code using CMake, compiled from source code using Bazel

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #22107, again.

The bug was introduced subsequent to the most recent release, so we don't need a release note announcing the fix.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22134)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@cohnt could you check this again, please?  Thanks!

**Review by cohnt — COMMENTED** [review]
I confirmed that this removes the previously-present console spam. Thanks!

:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22134#-:-OB1BK_4AKgqBsGn35_e:b-zzeqw)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/gurobi_solver.cc` line 991 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22134#-OB1B6-k4wlKQyMpCuKk:-OB1B6-k4wlKQyMpCuKl:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/eebf2028d6cacfa8d9396d55d57a39c502aafa8b/solvers/gurobi_solver.cc#L991)):*
> ```cpp
> 
>   // Copy the remaining options into model_env. Set the logging level first, so
>   // that changes to any of the other options are uniformed logged (or not).
> ```

nit: grammar



_Suggestion:_
```cpp
any of the other options are uniformly logged (or not)
```

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22134#-:-OB2OWCQCcs7dqam3G_3:b8qx53o)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees cohnt,sherm1(platform)

**Pull request merged**
