### PR TITLE
Revert "[render] Deprecate CameraProperties and DepthCameraProperties"

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Dear @SeanCurtis-TRI,

The on-call build cop, $BUILD_COP, believes that your PR #14376 may have
broken one or more of Drake's continuous integration builds [1]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms are tested post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-catalina-clang-bazel-continuous-release/81/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly On-call Build Cop

[1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
[2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14384)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14384#-:-MMd6Q1_DhuYKpl1s35J:b-n9fr1a)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
:lgtm: rubber stamp.

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'm going to go ahead and make sure this is actually the cause.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14384#-:-MMd6re72sshQ7NSjkSB:b-4tcci3)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
:lgtm_cancel:  I just realized, as you did, that '75 is what broke CI, but this reverts '76.

**Comment by EricCousineau-TRI** [comment]
Huh... just curious - y'all know what the root cause is here?

Need like 15min of me checking?

**Comment by SeanCurtis-TRI** [comment]
Take a look at this slack barrage: https://drakedevelopers.slack.com/archives/C270MN28G/p1605922267180500

**Comment by SeanCurtis-TRI** [comment]
To be perfectly frank, I'm absolutely stymied on what the cause might be and two efforts to reproduce *outside* of CI has failed.

**Comment by SeanCurtis-TRI** [comment]
I re-ran the failing test and it's happy: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-catalina-clang-bazel-continuous-release/82/

Why did it fail twice in a row (in an inexplicably manner) but then pass? My bias prefers the pass being representative of a stable reality because the failures were absolutely bizarre.

**Comment by SeanCurtis-TRI** [comment]
I'm going to close this:

1. It doesn't seem necessary.
2. It was never necessary because the failure started on a different PR and this was the wrong revert anyways.

**Pull request closed without merging**
