### PR TITLE
Global ik update constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
1. Return `Binding<LinearConstraint>` for the added position and orientation constraint in global IK, so that we can update the constraint later.
2. Add a call to nonlinear IK for the infeasibility test in global IK test.
3. Split global_inverse_kinematics_test.cc to avoid the test taking too much time.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5811)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@siyuanfeng-tri for feature review. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-KhbPEg_N7UoColIZsBf:b3988e4)*

**Comment by siyuanfeng-tri** [comment]
checkpoint

---

Reviewed 6 of 11 files at r1.
Review status: 6 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbWr-rEj5jgpNbVyH_:-KhbWr-rEj5jgpNbVyHa:bhnol9c) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc#L39)):*
> ```cpp
> 
>     // Now update the constraint, the problem should still be feasible.
>     // TODO(hongkai.dai): do a warm start on the binary variables
> ```

this todo probably belongs to somewhere else?

---

*[drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbX-MGfal5xX9Wh6aW:-KhbX-MGfal5xX9Wh6aX:b-f59vll) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc#L41)):*
> ```cpp
>     // TODO(hongkai.dai): do a warm start on the binary variables
>     ee_pos_lb_W << 0.2, -1, 0.6;
>     ee_pos_ub_W << 0.4, 1, 1.0;
> ```

BTW, you really want -1 to 1?

---

*[drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbXECAwnJg1rY-yqr4:-KhbXECAwnJg1rY-yqr5:b-8mbb70) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc#L46)):*
> ```cpp
>     double angle_tol = 0.3 * M_PI;
>     ee_orient_cnstr.constraint()->UpdateLowerBound(
>         Vector1d(2 * cos(angle_tol) + 1));
> ```

BTW, it would be more intuitive if you do the 2cos + 1 thing internally, but that could wait. 

---

*[drake/multibody/dev/test/global_inverse_kinematics_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbY3-L1bGi-i-q-Sye:-KhbY3-L1bGi-i-q-Syf:brxr6xj) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_test.cc#L38)):*
> ```cpp
>                 sol_result == SolutionResult::kInfeasibleConstraints);
>   }
>   WorldPositionConstraint pos_cnstr(rigid_body_tree_.get(), ee_idx_,
> ```

BTW, i am not sure calling snopt on the infeasible is all that meaningful. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-KhbYU7Iogostj3aEC3c:b-vv2shf)*

**Comment by siyuanfeng-tri** [comment]
i only pattern matched for rotation_constraint.cc. i need to spend more time to understand it if @hongkai-dai you think that's necessary. 

it was not clear to me why the binary vars are also returned, do you use it anywhere? 

---

Reviewed 3 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/solvers/rotation_constraint.h, line 133 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbvN_aW42QSC0izoB1:-KhbvN_aW42QSC0izoB2:blyk3vi) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/solvers/rotation_constraint.h#L133)):*
> ```objc
>  *   CRneg[k](i, j) = 1 => -(k+1) / N <= R(i, j) <= -k / N
>  *   BRpos[k](i, j) = 1 => R(i, j) >= k / N
>  *   BRneg[k](i, j) = 1 => R(i, j) <= -k / n
> ```

BTW should this be <=> ? also n -> N

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-KhbyM7gCScbSpFEk3Pg:b-o7wdyk)*

**Comment by siyuanfeng-tri** [comment]
why does it run faster now? (smaller timeout in tests)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-Khbzjdja1bNvP3Wb4uu:b-7x687k)*

**Comment by hongkai-dai** [comment]
The reduction in timeout is because I take some tests in `global_inverse_kinematics_test` to `global_inverse_kinematics_reachable_test`.

---

Review status: 5 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbWr-rEj5jgpNbVyH_:-Khc9CXe6cNjTgnrhfWR:bs6fbns) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc#L39)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

this todo probably belongs to somewhere else?
</blockquote></details>

The TODO is actually for returning the binary variables (the comment you put in returning `Bpos` and `Bneg`). I plan to have a separate PR, so that I can set the initial values for the binary variables, as a warm start. 

---

*[drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbX-MGfal5xX9Wh6aW:-KhcM2MX8tvcOEqelgMu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc#L41)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, you really want -1 to 1?
</blockquote></details>

Done.

---

*[drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbXECAwnJg1rY-yqr4:-Khc9bZR8SZjNF58662Q:b-e7ps9w) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc#L46)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, it would be more intuitive if you do the 2cos + 1 thing internally, but that could wait. 
</blockquote></details>

Good idea, this problem would be resolved when the global IK accepts RigidBodyConstraint, such as `WorldQuatConstraint`. Then I can update the angle tolerance of the `WorldQuatConstraint`.

---

*[drake/multibody/dev/test/global_inverse_kinematics_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbY3-L1bGi-i-q-Sye:-Khc9iA2ZV2HL0FipF1H:b-ibu9aa) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_test.cc#L38)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, i am not sure calling snopt on the infeasible is all that meaningful. 
</blockquote></details>

I called SNOPT here to make sure that snopt also cannot find the solution. Just want to detect if there is a bug in the global IK code, that global IK cannot find the solution, but nonlinear IK can. If this happens, then for sure something would be wrong in the global IK. I am glad that snopt IK also cannot find the solution.

---

*[drake/solvers/rotation_constraint.h, line 133 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbvN_aW42QSC0izoB1:-KhcA2o7wmjk_LkeRIFD:b-zdqjvy) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/solvers/rotation_constraint.h#L133)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW should this be <=> ? also n -> N
</blockquote></details>

Good catch. But it is not <=>. For R(i,j) = k/n, BRpos[k](i,j) can be either 0 or 1, check out https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/rotation_constraint.cc#L927~#L929

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-KhcB3ieYQhgJv9pEPNJ:by9961c)*

**Comment by siyuanfeng-tri** [comment]
*[drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbXECAwnJg1rY-yqr4:-KhbzY6ZRYHmsDYDJlYQ:bluup1r) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc#L46)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, it would be more intuitive if you do the 2cos + 1 thing internally, but that could wait. 
</blockquote></details>

BTW, i was originally much more interested if you run snopt after the feasible ones to see if they are really feasible, and if so, how much does it differ. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 11 files at r1.
Review status: 6 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbWr-rEj5jgpNbVyH_:-KhcSF-jxoEP3a1MjKhG:bxmpv0c) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc#L39)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The TODO is actually for returning the binary variables (the comment you put in returning `Bpos` and `Bneg`). I plan to have a separate PR, so that I can set the initial values for the binary variables, as a warm start. 
</blockquote></details>

i see. that's why you are exposing them. kk 

---

*[drake/multibody/dev/test/global_inverse_kinematics_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbY3-L1bGi-i-q-Sye:-KhcSXmSxhPHzRTqc0CO:b-m8qur7) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_test.cc#L38)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I called SNOPT here to make sure that snopt also cannot find the solution. Just want to detect if there is a bug in the global IK code, that global IK cannot find the solution, but nonlinear IK can. If this happens, then for sure something would be wrong in the global IK. I am glad that snopt IK also cannot find the solution.
</blockquote></details>

sure, i know what you are trying to do here. i'd be slightly happier if the point you are reaching is like out of reach or something obvious like that.

---

*[drake/solvers/rotation_constraint.h, line 133 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbvN_aW42QSC0izoB1:-KhcTAtma5qZ6NZBtK-R:b-qhvpdj) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/solvers/rotation_constraint.h#L133)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good catch. But it is not <=>. For R(i,j) = k/n, BRpos[k](i,j) can be either 0 or 1, check out https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/rotation_constraint.cc#L927~#L929
</blockquote></details>

i see 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-KhcTX5MBm9eyLGfCHIO:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbXECAwnJg1rY-yqr4:-KhchmgGAa8WG75TiAct:bsxj10k) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_reachable_test.cc#L46)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, i was originally much more interested if you run snopt after the feasible ones to see if they are really feasible, and if so, how much does it differ. 
</blockquote></details>

Done. Call the nonlinear IK after the global IK call.

---

*[drake/multibody/dev/test/global_inverse_kinematics_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhbY3-L1bGi-i-q-Sye:-KhcTx0XtHn4b7B_NMDT:bt1t5zy) ([raw file](https://github.com/robotlocomotion/drake/blob/d5becaff59f74110bee52a5885673021c1304b12/drake/multibody/dev/test/global_inverse_kinematics_test.cc#L38)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

sure, i know what you are trying to do here. i'd be slightly happier if the point you are reaching is like out of reach or something obvious like that.
</blockquote></details>

The point is actually within reach, if we relax the orientation constraint. Personally I think it is more interesting, if the point is reachable with relaxed orientation constraint; but when we tighten the orientation constraint, the point is not reachable. I think this shows that we handle both position and orientation constraints.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811)*

**Comment by hongkai-dai** [comment]
+@david-german-tri for platform review please.

---

Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-KhciGDiZ1vVQb9rkpWm:b-buchxz)*

**Comment by david-german-tri** [comment]
:lgtm: I reviewed the code outside `dev`, and confirmed that this PR does not introduce new dependencies on `dev` code from outside `dev`.  I did not review the code inside `dev`.

---

Reviewed 3 of 11 files at r1, 2 of 5 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/global_inverse_kinematics.h, line 124 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-Khcom4RLUAhDqWzWK1b:-Khcom4RLUAhDqWzWK1c:bjrmyzl) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/multibody/global_inverse_kinematics.h#L124)):*
> ```objc
>    *     frame `W`. `p_WFo = X_WF.translation()`.
>    * @default is the identity transform.
>    * @retval binding The newly added constraint, together with the bounded
> ```

BTW here and below, do you mean "bound variables"?

---

*[drake/multibody/dev/test/global_inverse_kinematics_test_util.h, line 13 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhctIRerl_mb_f4L9m7:-KhctIRerl_mb_f4L9m8:b-8u8wrb) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/multibody/dev/test/global_inverse_kinematics_test_util.h#L13)):*
> ```objc
> class KukaTest : public ::testing::Test {
>  public:
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(KukaTest)
> ```

BTW this shouldn't be necessary for a test fixture.

---

*[drake/solvers/rotation_constraint.h, line 136 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-Khcst2tkd-yqPRcYefm:-Khcst2tkd-yqPRcYefn:b-6pdp2j) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/solvers/rotation_constraint.h#L136)):*
> ```objc
>  * </pre>
>  * where `N` is `num_binary_vars_per_half_axis`.
>  */
> ```

BTW this comment goes with the function, not the tuple, right?

---

*[drake/solvers/test/rotation_constraint_test.cc, line 629 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhcsjGmA20pMWGDCgtO:-KhcsjGmA20pMWGDCgtP:b-663c6g) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/solvers/test/rotation_constraint_test.cc#L629)):*
> ```cpp
>     DRAKE_DEMAND(orthant_ >= 0);
>     DRAKE_DEMAND(orthant_ <= 7);
>     const auto Cpos_Cneg_Bpos_Bneg =
> ```

BTW, `std::tie` might be convenient here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-KhcuRYs2ezaTD3GO1cn:b-kljenb)*

**Comment by hongkai-dai** [comment]
Review status: 8 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/global_inverse_kinematics.h, line 124 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-Khcom4RLUAhDqWzWK1b:-Khd0aNJlCJmAGVwveN9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/multibody/global_inverse_kinematics.h#L124)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW here and below, do you mean "bound variables"?
</blockquote></details>

Done.

---

*[drake/multibody/dev/test/global_inverse_kinematics_test_util.h, line 13 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhctIRerl_mb_f4L9m7:-Khd0inyYkp466-9bP7X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/multibody/dev/test/global_inverse_kinematics_test_util.h#L13)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW this shouldn't be necessary for a test fixture.
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.h, line 136 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-Khcst2tkd-yqPRcYefm:-Khd0rWJ34IM8dBVFKLX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/solvers/rotation_constraint.h#L136)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW this comment goes with the function, not the tuple, right?
</blockquote></details>

Done.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 629 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhcsjGmA20pMWGDCgtO:-Khd1bYEBSaf5Q8Vqq4p:b263g4q) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/solvers/test/rotation_constraint_test.cc#L629)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, `std::tie` might be convenient here.
</blockquote></details>

The returned argument `Cpos_Cneg_Bpos_Bneg` contains 4 element, `Cpos`, `Cneg`, `Bpos` and `Bneg`. I only used the first two here. Can I still use a `std::tie`, if I do not declare variables for each element in the tuple?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 629 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhcsjGmA20pMWGDCgtO:-Khd75v12hWBjjFfE7oV:b5iffa4) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/solvers/test/rotation_constraint_test.cc#L629)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The returned argument `Cpos_Cneg_Bpos_Bneg` contains 4 element, `Cpos`, `Cneg`, `Bpos` and `Bneg`. I only used the first two here. Can I still use a `std::tie`, if I do not declare variables for each element in the tuple?
</blockquote></details>

http://en.cppreference.com/w/cpp/utility/tuple/ignore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-Khd6yYqFj9p8I0BRNDk:bsm4ivv)*

**Comment by hongkai-dai** [comment]
Review status: 7 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 629 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-KhcsjGmA20pMWGDCgtO:-Khd8RHJ9VeuMhPFFYxO:b-k8sndk) ([raw file](https://github.com/robotlocomotion/drake/blob/b81a72d2dca760215e8dc48584a3969328135648/drake/solvers/test/rotation_constraint_test.cc#L629)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

http://en.cppreference.com/w/cpp/utility/tuple/ignore
</blockquote></details>

Done. Thanks! I learned something today.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-KhdWDwtWi-V2ZBCJ_HL:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5811#-:-KhhKs5b2y_F5MfIkChv:b-l70wzf)*

**Pull request merged**
