### PR TITLE
Rename all exports

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In all Drake code, stop using generated export headers.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3680)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jwnimmer-tri** [comment]
These all passed last time, but I've rebased onto master to make sure.

@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review please.  Note that in the commit history, one of the commits is a perl pie, so consider reviewing independently.  I've set up the revision markers in reviewable to support this.

---

Review status: 0 of 156 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3680#-:-KTKoen9sr90lKk5GDM-:b-flvc3t)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 153 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: 5 of 156 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3680#-:-KTKyOBBYXdlm33Up33r:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
All builds passed.  Even the OSX-matlab got through the build; I canceled it while it was on the tests.

**Pull request merged**
