### PR TITLE
[py all] Add Preferred Ordering mechanism and tests

### LINKED ISSUE #18353: from pydrake.all import Polynomial now imports polynomial.Polynomial instead of symbolic.Polynomial
### What happened?

An old notebook failed with an unexpected error, and I've realized that this was the problem.  I have not yet bisected to find the offending commit, but in addition to being a breaking change, I think symbolic is the Polynomial that we want.

We used to have 
```
from pydrake.all import Polynomial
```
was equivalent to 
```
from pydrake.symbolic import Polynomial
```
but now it gets
```
from pydrake.polynomial import Polynomial
```

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #18353

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18357)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@russtedrake for both reviews (if you're ok with that), please!
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18357#-:-NHZwpO9E9rXZviaQ6GA:btjrdc0)* status: LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18357)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/all.py` line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18357#-NH_FQD3-JdVogaVNQjE:-NH_FQD3-JdVogaVNQjF:b-ag5bj4) ([raw file](https://github.com/robotlocomotion/drake/blob/65417b4fde81ab3a77a68de70e3a8b255ad42ec1/bindings/pydrake/all.py#L63)):*
> ```Python
> # - Ensure .math imports win over less capable .symbolic or .autodiffutils
> # overloads.
> from .math import *
> ```

Do we know why re-importing was dispreferred before and is preferred now?
I don't have a strong preference either way.
___
*[`bindings/pydrake/test/all_test.py` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18357#-NH_FoDS19SphBcLQMJ9:-NH_FoDS19SphBcLQMJA:b7vbyl4) ([raw file](https://github.com/robotlocomotion/drake/blob/4c4b9f7c829f21822c57267f01916851bc7d15c9/bindings/pydrake/test/all_test.py#L83)):*
> ```Python
>         self.assertIsInstance(sin(AutoDiffXd(1, [1, 0])), AutoDiffXd)
>         self.assertIsInstance(sin(Expression(Variable('e'))), Expression)
>         self.assertIsInstance(sin(Variable('x')), Expression)
> ```

do we confirm elsewhere that math.sin works for float, autodiff, and expression?  these tests might be worth keeping here, too?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18357)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @RussTedrake)

___
*[`bindings/pydrake/all.py` line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18357#-NH_FQD3-JdVogaVNQjE:-NH_GzjVEb9x40zldDoa:b-od30po) ([raw file](https://github.com/robotlocomotion/drake/blob/65417b4fde81ab3a77a68de70e3a8b255ad42ec1/bindings/pydrake/all.py#L63)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Do we know why re-importing was dispreferred before and is preferred now?
I don't have a strong preference either way.
</blockquote></details>

When was it dispreferred? I think I just made `all.py` with a kinda arbitrary (but stable) ordering, and we didn't deviate.
___
*[`bindings/pydrake/test/all_test.py` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18357#-NH_FoDS19SphBcLQMJ9:-NH_H6EZ1B1pWCziTXoS:bvew4pt) ([raw file](https://github.com/robotlocomotion/drake/blob/4c4b9f7c829f21822c57267f01916851bc7d15c9/bindings/pydrake/test/all_test.py#L83)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

do we confirm elsewhere that math.sin works for float, autodiff, and expression?  these tests might be worth keeping here, too?
</blockquote></details>

Those are tested via usages of `ScalarAlgebra`
https://github.com/RobotLocomotion/drake/blob/4c4b9f7c829f21822c57267f01916851bc7d15c9/bindings/pydrake/test/algebra_test_util.py#L26-L58

If there are concerns about that functionality, they should be added in a place that concentrates on `pydrake.math.sin`, and I don't believe `all_test.py` is the best place for that.
Identity checks should be all this test really does.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18357)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @RussTedrake)

___
*[`bindings/pydrake/all.py` line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18357#-NH_FQD3-JdVogaVNQjE:-NH_JV2z2lU3OIg5ONzb:b-jx7zsy) ([raw file](https://github.com/robotlocomotion/drake/blob/65417b4fde81ab3a77a68de70e3a8b255ad42ec1/bindings/pydrake/all.py#L63)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I assumed that it was dispreferred by the author of the logic for selectively importing symbolic above, which you just removed.  This solves the same problem.
</blockquote></details>

I think it was just a preference not to deviate from convention.
However, I think "inline overloading" requires more complex logic (as evidenced above in base commit), when really we just want shadowing.
Plus, this consolidates the shadowing at the most influential place - the end.

**Review by RussTedrake — COMMENTED** [review]
:lgtm: x 2

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18357#-:-NH_LZnV86A35grhqT6O:b4xzgsb)* status: missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Thanks!

For future release managers: Adding `release notes: fix` as it's publicly accessible API. However, I'd still consider it unstable, so happy to have it changed if merited.

**Pull request merged**
