### PR TITLE
[tools] Collect python test coverage data with kcov

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtRftn35-qwSTp69_Vo:-MtRftn35-qwSTp69_Vp:b-qeq2xj) (no related file):*
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtRftn35-qwSTp69_Vo:-MtRioSl0Qjf7u_tHDSO:b-qeq2xj) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.
</blockquote></details>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.

---

**Review by rpoyner-tri — COMMENTED** [review]
-(status: do not review) +(priority: low) +(release notes: none) 
+@ericcousineau-tri for (extremely leisurely) feature review. 

I will probably use this bag of tricks locally for specific work; I don't know that its usefulness in master is all that great (yet). 

Have a poke around in the  completed coverage builds' CDash coverage output and see what you think.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392#-:-MtTnKJCBD34MbOPs1kg:bqtenwz)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Just so I know the right coverage to look at, any chance you could provide a link?

**Comment by EricCousineau-TRI** [comment]
Ah, from the builds :facepalm:

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature with some nits

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392#-:-MtjPutlDD_Cw6kV5Djt:bqs8lid)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPQ7--QZ0S8Hzs7HA:-MtjPQ705lQyeLefYj5x:b-tsm0gy) (no related file):*
nit There are some odd false negatives; e.g. `./bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py`
https://drake-cdash.csail.mit.edu/viewCoverageFile.php?buildid=1540724&fileid=7613960

Should upstream bugs be filed, if not already?

- Import lines are indicates uncovered, even though symbols are used
- Some assignment expressions are shown unused, even though they are? (L67, L68)
- Some concatenated strings are denoted as unused, even though they are? (L136, L154)

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPdAe5EAmMVUoestf:-MtjPdAfAgaTioe1_GSy:bd0xq3n) (no related file):*
nit Overarching goal / use case / audience not immediately clear (hard to judge how much to nit pick vs block on)

Is this for improving testing for pure Python code, for general Drake developers to use?

---
___
*[common/test_utilities/drake_py_unittest_main.py, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPLOf9mv5bWjKE-zI:-MtjPLOf9mv5bWjKE-zJ:b-865e87) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/common/test_utilities/drake_py_unittest_main.py#L27)):*
> ```Python
>     # Obtain the full path for this test case; it looks a bit like this:
>     # .../execroot/.../foo_test.runfiles/.../drake_py_unittest_main.py
>     # Also work around kcov#368 by consuming KCOV_LINK_PATH.
> ```

nit Should there be a TODO to fix this once we use the version of kcov incorporating your patch?
___
*[common/test_utilities/drake_py_unittest_main.py, line 203 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjO_wi2FmbygITPawy:-MtjO_wi2FmbygITPawz:bl4tc42) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/common/test_utilities/drake_py_unittest_main.py#L203)):*
> ```Python
>     # can simplify the custom parsing logic (e.g. not have to import source
>     # modules).
>     # Avoid re-executing if run under kcov.
> ```

nit Unclear why re-execution is bad. Consider adding rationale?
(e.g. it doubles line count for this unittest shell?)
___
*[tools/dynamic_analysis/kcov.sh, line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjNaiW0l2Ixa1U6WiT:-MtjNaiW0l2Ixa1U6WiU:b-fec59s) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/dynamic_analysis/kcov.sh#L40)):*
> ```Shell
> fi
> 
> read -d '' KCOV_COMMAND <<- eof
> ```

TIL `<<-`!
https://www.gnu.org/software/bash/manual/bash.html#Here-Documents
___
*[tools/dynamic_analysis/kcov.sh, line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjNvE3-8FRRsulwoyR:-MtjNvE448U5WS251akc:bktqpeb) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/dynamic_analysis/kcov.sh#L40)):*
> ```Shell
> fi
> 
> read -d '' KCOV_COMMAND <<- eof
> ```

BTW (pre-existing) Unclear why indentation needs consideration `<<-`.

GSG Bash guide doesn't seem to provide indication on redundant specifiers.
___
*[tools/dynamic_analysis/kcov.sh, line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjQpjP4bZbPrJ3FzOU:-MtjQpjP4bZbPrJ3FzOV:bmw1qez) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/dynamic_analysis/kcov.sh#L53)):*
> ```Shell
> if [[ $(file -b -i -L "$1") == *text/x-python* ]]; then
>     # Bazel's Python wrappers require extra treatment. PYTHON_COVERAGE and
>     # COVERAGE_DIR are consumed by the bazel wrapper.
> ```

nit "the bazel wrapper" is ambiguous.

Do you mean "Drake's custom unittest wrapper"?
___
*[tools/dynamic_analysis/kcoverage.py, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjOtYr4mE5tt3uaZDs:-MtjOtYr4mE5tt3uaZDt:bf2o6xi) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/dynamic_analysis/kcoverage.py#L2)):*
> ```Python
> #!/usr/bin/python3
> """kcoverage.py -- mimic coverage.py just enough to shim kcov into bazel
> ```

nit Unqualified `coverage.py` is a bit ambiguous (or possibly wrong); what file does this refer to?

(I don't readily see it in this PR or in drake master)
___
*[tools/jupyter/jupyter_py.bzl, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPEQy0sTCkO_7PiXG:-MtjPEQy0sTCkO_7PiXH:b-865e87) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/jupyter/jupyter_py.bzl#L18)):*
> ```Starlark
> 
> def main():
>     # Work around kcov#368 by consuming KCOV_LINK_PATH.
> ```

nit Should there be a TODO to fix this once we use the version of kcov incorporating your patch?

**Comment by EricCousineau-TRI** [comment]
(also - nice!!!)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 8 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPQ7--QZ0S8Hzs7HA:-MtjgrvDEJyKvG6Bh-Gs:b8ckl5x) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit There are some odd false negatives; e.g. `./bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py`
https://drake-cdash.csail.mit.edu/viewCoverageFile.php?buildid=1540724&fileid=7613960

Should upstream bugs be filed, if not already?

- Import lines are indicates uncovered, even though symbols are used
- Some assignment expressions are shown unused, even though they are? (L67, L68)
- Some concatenated strings are denoted as unused, even though they are? (L136, L154)
</blockquote></details>

I have no doubt we will find upstream bugs. I haven't tried to file any for actual covered/uncovered lines yet.

At the very least, the trampoline `kcov` itself triggers some deprecation warnings: "import imp" vs. "import importlib".

I guess the question is: is this  useful at this stage, or does it need more work to not be misleading?

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPdAe5EAmMVUoestf:-MtjhQP594GOGtYabmCD:b-ap7fe0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Overarching goal / use case / audience not immediately clear (hard to judge how much to nit pick vs block on)

Is this for improving testing for pure Python code, for general Drake developers to use?
</blockquote></details>

Initial audience is me.   This is something I have wanted ~forever (2017 maybe?), but had been blocked by either bazel or other things for some time.

Actual audience is drake developers, same as c++ coverage. Since drake proper has relatively little python, value proposition is maybe small.

Test coverage for notebooks might be interesting, but I have no idea how to accomplish that at this point.

---
___
*[common/test_utilities/drake_py_unittest_main.py, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPLOf9mv5bWjKE-zI:-MtjiOhW5YWgrT5r-ADz:bbo92tc) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/common/test_utilities/drake_py_unittest_main.py#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should there be a TODO to fix this once we use the version of kcov incorporating your patch?
</blockquote></details>

Maybe? the lag from kcov master to Ubuntu to drake is on the order of years, unless we commit to making kcov a dependency, or roll custom debs. (Driving used to do this; it's a bit painful.)
___
*[common/test_utilities/drake_py_unittest_main.py, line 203 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjO_wi2FmbygITPawy:-MtjiiAV1y1M_GvzNbkb:b-2p78z5) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/common/test_utilities/drake_py_unittest_main.py#L203)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why re-execution is bad. Consider adding rationale?
(e.g. it doubles line count for this unittest shell?)
</blockquote></details>

Re-execution prevents kcov gathering data at all. I'm a bit unclear on the deep details, but maybe they don't matter. Will clarify.
___
*[tools/dynamic_analysis/kcov.sh, line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjNvE3-8FRRsulwoyR:-MtjjAuxA-wudWqPlHqc:bxmfm7n) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/dynamic_analysis/kcov.sh#L40)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW (pre-existing) Unclear why indentation needs consideration `<<-`.

GSG Bash guide doesn't seem to provide indication on redundant specifiers.
</blockquote></details>

Yes, perhaps this could be less fancy.
___
*[tools/dynamic_analysis/kcov.sh, line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjQpjP4bZbPrJ3FzOU:-MtjjIme-Ra7Pt7Zkaa8:b-b62pyg) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/dynamic_analysis/kcov.sh#L53)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "the bazel wrapper" is ambiguous.

Do you mean "Drake's custom unittest wrapper"?
</blockquote></details>

In this case I am talking about the actual bazel wrapper; the thing that injects additional python path stuff, handles multiple python versions, deals with some weird windows cases, etc., and eventually does a re-exec. [This thing.](https://github.com/bazelbuild/bazel/blob/763dd0ce6e1644bf895231432f616427a11d385a/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt)

I can clarify. Somehow.
___
*[tools/dynamic_analysis/kcoverage.py, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjOtYr4mE5tt3uaZDs:-MtjlWAM8ba3xcpIOPic:bdtokm3) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/dynamic_analysis/kcoverage.py#L2)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unqualified `coverage.py` is a bit ambiguous (or possibly wrong); what file does this refer to?

(I don't readily see it in this PR or in drake master)
</blockquote></details>

Ned Batchelder's [coverage.py ](https://pypi.org/project/coverage/), for which the bazel hooks were "designed".

Again, I can clarify.
___
*[tools/jupyter/jupyter_py.bzl, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPEQy0sTCkO_7PiXG:-MtjlviV2-V16R7RtKE9:bmvc6wk) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/jupyter/jupyter_py.bzl#L18)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should there be a TODO to fix this once we use the version of kcov incorporating your patch?
</blockquote></details>

Maybe? see my answer in the other similar thread.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPQ7--QZ0S8Hzs7HA:-MtjrBea8OI5wOAbISRi:b-gb5kdh) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I have no doubt we will find upstream bugs. I haven't tried to file any for actual covered/uncovered lines yet.

At the very least, the trampoline `kcov` itself triggers some deprecation warnings: "import imp" vs. "import importlib".

I guess the question is: is this  useful at this stage, or does it need more work to not be misleading?
</blockquote></details>

I think it's definitely useful at this stage. It'd more useful if snafus are documented in discoverable way.
(Upstream issues are perhaps not required, but extra useful?)

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPdAe5EAmMVUoestf:-MtjrIlSBuX7PfFdZeqI:b-jr3fmo) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Initial audience is me.   This is something I have wanted ~forever (2017 maybe?), but had been blocked by either bazel or other things for some time.

Actual audience is drake developers, same as c++ coverage. Since drake proper has relatively little python, value proposition is maybe small.

Test coverage for notebooks might be interesting, but I have no idea how to accomplish that at this point.
</blockquote></details>

OK Gotcha, thanks for clarifying!

For notebooks, yeah, no idea.
Perhaps simplest is like `jupytext`, where sync is done between notebook and a source file

---
___
*[common/test_utilities/drake_py_unittest_main.py, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPLOf9mv5bWjKE-zI:-MtjrkNzDjEMHwpIfk0t:b-258osq) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/common/test_utilities/drake_py_unittest_main.py#L27)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Maybe? the lag from kcov master to Ubuntu to drake is on the order of years, unless we commit to making kcov a dependency, or roll custom debs. (Driving used to do this; it's a bit painful.)
</blockquote></details>

FWIW I have no qualms with a short TODO existing for years.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[common/test_utilities/drake_py_unittest_main.py, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPLOf9mv5bWjKE-zI:-Mtn6WVi82AyAPXn7_C7:bt36ie7) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/common/test_utilities/drake_py_unittest_main.py#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FWIW I have no qualms with a short TODO existing for years.
</blockquote></details>

will TODO.
___
*[tools/jupyter/jupyter_py.bzl, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPEQy0sTCkO_7PiXG:-Mtn6cTqDM6BEI1E2Pr-:bt36ie7) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/jupyter/jupyter_py.bzl#L18)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Maybe? see my answer in the other similar thread.
</blockquote></details>

will TODO.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPQ7--QZ0S8Hzs7HA:-MtnotMs5Id4YZk8FODT:b3ib5yk) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I think it's definitely useful at this stage. It'd more useful if snafus are documented in discoverable way.
(Upstream issues are perhaps not required, but extra useful?)
</blockquote></details>

Filing some upstream issues is a fine idea; I don't know that this level of detail needs to be documented within Drake.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[tools/dynamic_analysis/kcov.sh, line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjQpjP4bZbPrJ3FzOU:-Mto6lV_BarfOCxJThgy:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/784c78bae53644d1497cbabedc401b9ef6fdaae4/tools/dynamic_analysis/kcov.sh#L53)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

In this case I am talking about the actual bazel wrapper; the thing that injects additional python path stuff, handles multiple python versions, deals with some weird windows cases, etc., and eventually does a re-exec. [This thing.](https://github.com/bazelbuild/bazel/blob/763dd0ce6e1644bf895231432f616427a11d385a/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt)

I can clarify. Somehow.
</blockquote></details>

OK Thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-MtjPQ7--QZ0S8Hzs7HA:-Mto6sKv8AwZQt-fXAhE:bexaql2) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Filing some upstream issues is a fine idea; I don't know that this level of detail needs to be documented within Drake.
</blockquote></details>

I'd recommend something maintained by Drake that mentions what defects might be present. (Drake issue linked from kcov instructions, inline in the instructions themselves, etc.)
Upstream issues are a bonus, yup!

---

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for platform, please!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392#-:-MtsseE-CzH9u-jQABpW:b-845ja2)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 1 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392#-:-Mtt-AEWCbBDYV2O4ZzU:b-vtj4vo)* status: 5 unresolved discussions (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-4fR5bJW_2PLoHiv:-Mtt-4fR5bJW_2PLoHiw:b-hkik7e) (no related file):*
nit We need to run a kcov CI build prior to merging this.

---
___
*[common/test_utilities/drake_py_unittest_main.py, line 205 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-ayW86YMr-IlfDrl:-Mtt-ayW86YMr-IlfDrm:bxxmmij) ([raw file](https://github.com/robotlocomotion/drake/blob/1f15d5a364ad6a381c58ae1e9b08666cfbe6f19b/common/test_utilities/drake_py_unittest_main.py#L205)):*
> ```Python
>     # modules).
>     # Avoid re-executing if run under kcov; it defeats kcov's instrumentation.
>     is_kcov = 'KCOV_COMMAND' in os.environ
> ```

nit It's not ideal that we have `is_kcov` as a module-scoped variable now.  (Generally we try to never use variables in the dunder-name block.)
___
*[tools/dynamic_analysis/kcoverage.py, line 2 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt0bUd3FbllMj_WonC:-Mtt0bUd3FbllMj_WonD:b-f1ht0) ([raw file](https://github.com/robotlocomotion/drake/blob/1f15d5a364ad6a381c58ae1e9b08666cfbe6f19b/tools/dynamic_analysis/kcoverage.py#L2)):*
> ```Python
> #!/usr/bin/python3
> """kcoverage.py -- mimic coverage.py[1] just enough to shim kcov into bazel
> ```

nit This file probably isn't being linted?  Add it to the `BUILD.bazel` stanza using `python_lint_extra_srcs`.
___
*[tools/dynamic_analysis/kcoverage.py, line 34 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt17BU0W8D4JqbFIhC:-Mtt17BU0W8D4JqbFIhD:bshomcu) ([raw file](https://github.com/robotlocomotion/drake/blob/1f15d5a364ad6a381c58ae1e9b08666cfbe6f19b/tools/dynamic_analysis/kcoverage.py#L34)):*
> ```Python
>     the KCOV_COMMAND environment variable.
>     """
>     kcov_command = os.environ.get('KCOV_COMMAND', '')
> ```

nit It's unclear to me why we should silently bash on regardless when `KCOV_COMMAND` was not defined in the environment?  It seems like something would be horribly wrong for that to have gone missing?
___
*[tools/dynamic_analysis/kcoverage.py, line 40 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt1tZG2nYnJY-8vBed:-Mtt1tZH5TbKS-Lpntc1:b5nuuxd) ([raw file](https://github.com/robotlocomotion/drake/blob/1f15d5a364ad6a381c58ae1e9b08666cfbe6f19b/tools/dynamic_analysis/kcoverage.py#L40)):*
> ```Python
>     # kcov#368). Work around kcov#368 by exporting the original exe path in
>     # KCOV_LINK_PATH and handing the real path to kcov.
>     os.environ["KCOV_LINK_PATH"] = exe
> ```

nit Ah... finally getting here while reading the code, I see that `KCOV_LINK_PATH` is a Drake invention, not an upstream-relevant environment variable?  If so, we should name it `DRAKE_KCOV_...` to make that clear for future readers.  I thought it was coming from kcov itself.

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-4fR5bJW_2PLoHiv:-MttCl0pB7kU7YnP2SdA:btrriyg) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We need to run a kcov CI build prior to merging this.
</blockquote></details>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 5 unresolved discussions (waiting on @rpoyner-tri)

___
*[tools/dynamic_analysis/kcoverage.py, line 40 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt1tZG2nYnJY-8vBed:-MttDKbU49E1qBQ0QY0c:b-58s3sf) ([raw file](https://github.com/robotlocomotion/drake/blob/1f15d5a364ad6a381c58ae1e9b08666cfbe6f19b/tools/dynamic_analysis/kcoverage.py#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Ah... finally getting here while reading the code, I see that `KCOV_LINK_PATH` is a Drake invention, not an upstream-relevant environment variable?  If so, we should name it `DRAKE_KCOV_...` to make that clear for future readers.  I thought it was coming from kcov itself.
</blockquote></details>

good call. similarly for KCOV_COMMAND, which our code also creates?

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-4fR5bJW_2PLoHiv:-MttK11G3ESP5sR_Wy7H:btrriyg) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.
</blockquote></details>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-4fR5bJW_2PLoHiv:-MttKDyREC3nnjKZVpHT:btrriyg) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.
</blockquote></details>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-4fR5bJW_2PLoHiv:-MttKWlD4YMl-Ea2QkOF:b-59x08n) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.
</blockquote></details>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-4fR5bJW_2PLoHiv:-MttKffQ4J3saJ0eApsI:b-hsosdm) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
</blockquote></details>

@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-4fR5bJW_2PLoHiv:-MttKqn00OUHrQAIjgHB:bv74p89) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.
</blockquote></details>

My "build please" foo is failing.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-4fR5bJW_2PLoHiv:-MttLX8WEzKQSO6ULdT3:b-qhbev5) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

My "build please" foo is failing.
</blockquote></details>

Seems to me like it's running fine?  I see many builds at https://github.com/RobotLocomotion/drake/pull/16392, and PR status bar overview shows the one.

---
___
*[tools/dynamic_analysis/kcoverage.py, line 40 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt1tZG2nYnJY-8vBed:-MttLeYHD4JYgTsoE0xK:byr4flj) ([raw file](https://github.com/robotlocomotion/drake/blob/1f15d5a364ad6a381c58ae1e9b08666cfbe6f19b/tools/dynamic_analysis/kcoverage.py#L40)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

good call. similarly for KCOV_COMMAND, which our code also creates?
</blockquote></details>

Right.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16392)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16392#-Mtt-4fR5bJW_2PLoHiv:-MttNx60CpauiNIRWfFp:b-e0afo7) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Seems to me like it's running fine?  I see many builds at https://github.com/RobotLocomotion/drake/pull/16392, and PR status bar overview shows the one.
</blockquote></details>

Nice. Took some delay maybe to show up.

---

**Pull request merged**
