### PR TITLE
Add multi-process version of p&p demo.

### PR DESCRIPTION
**Pull request by avalenzu**
Description copied from the demo's README.md:
> This demo uses LCM ([Lightweight Communications and
> Marshalling](https://lcm-proj.github.io/)) for message passing between four
> executables:
> - Simulator (`lcm_pick_and_place_simulator`) - A physical simulation of the
>   demo scenario.
> - Planner (`lcm_pick_and_place_planner`) - A state-machine that outputs
>   joint-space trajectories and gripper commands.
> - Interpolator (`iiwa_controller`) - An interpolator that takes in joint-space
>   trajectories and outputs joint-space position commands.
> - Visualizer (`drake-visualizer`) - A 3D visualizer that displays the demo
>   scenario as it's being simulated.
> 
> The signal lines in the block diagram below represent LCM communication between
> the processes.
> 
> ```
>             ┌─────────┐ wsg command
> ┌──────────▶│         ├─────────┐      ┌───────────┐
> │           │         │         │      │           │
> │ ┌────────▶│ Planner │         │      │           │
> │ │         │         │plan     │      │           │            
> │ │ ┌──────▶│         ├─────┐   │      │           │ vis info   ┌────────────┐
> │ │ │       └─────────┘     │   └─────▶│           ├───────────▶│ Visualizer │
> │ │ │                       │          │           │            └────────────┘
> │ │ │    ┌──────────────────┘          │           │ optitrack
> │ │ │    │                             │ Simulator ├────────────────┐
> │ │ │    │  ┌──────────────┐    iiwa   │           │                │
> │ │ │    └─▶│              │ command   │           │ wsg_status     │
> │ │ │       │ Interpolator ├──────────▶│           ├──────────────┐ │
> │ │ │    ┌─▶│              │           │           │              │ │
> │ │ │    │  └──────────────┘           │           │ iiwa_status  │ │
> │ │ │    │                             │           ├────────────┐ │ │
> │ │ │    └──────────────┐              └───────────┘            │ │ │
> │ │ │                   │                                       │ │ │
> │ │ │                   │                                       │ │ │
> │ │ └───────────────────┴───────────────────────────────────────┘ │ │
> │ └───────────────────────────────────────────────────────────────┘ │
> └───────────────────────────────────────────────────────────────────┘
> ```
> The demo scenario consists of one or more Kuka iiwa arms surrounded by two or
> more tables. The arm will move a target object from one table to the next
> counter-clockwise about the base of the arm.
>

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7610)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@naveenoid for feature review

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-:-L0LYE7SB411xEPs6-4P:b-psw9ws)*

**Comment by naveenoid** [comment]
:lgtm: Only documentation related BTWs

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_planner.cc, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QXy4U0bglnx8-rbab:-L0QXy4U0bglnx8-rbac:bp1q0y0) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_planner.cc#L86)):*
> ```cpp
> 
>   // Connect subscribers to planner input ports.
>   builder.Connect(wsg_status_sub->get_output_port(0),
> ```

BTW: do you see any value at all in having named getters for these ports? Or is it dead obvious? Seems slightly obscure to use the port IDs, even if only the 0 ports.

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/README.md, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QWmxG_1QTLP4S92NP:-L0QWmxG_1QTLP4S92NQ:b-nwl0xl) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/README.md#L2)):*
> ```Markdown
> # Overview
> This demo uses LCM ([Lightweight Communications and
> ```

BTW: I know its repetition but a sentence here saying what this demo is for before launching into details will be good.

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QYbdg3N1f9_nLIECQ:-L0QYbdg3N1f9_nLIECR:b-6cy1l8) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/README.md#L9)):*
> ```Markdown
> - Planner (`lcm_pick_and_place_planner`) - A state-machine that outputs
>   joint-space trajectories and gripper commands.
> - Interpolator (`iiwa_controller`) - An interpolator that takes in joint-space
> ```

BTW: Just confirming - would each of these links take you directly to their respective Doxy page? I think it should but would be good if you could double check.

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/README.md, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QWYv6zZQa1F-mDdxQ:-L0QWYv6zZQa1F-mDdxR:bzaq7oe) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/README.md#L90)):*
> ```Markdown
> configuration files are text-format protobuf files that use the message types
> defined in `<drake
> root>/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto`. 
> ```

BTW: Excellent work with the documentation.

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/configuration/yellow_posts.pick_and_place_configuration, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QV5wc_n2CmfGevjfp:-L0QV5wc_n2CmfGevjfq:bck4ljo) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/configuration/yellow_posts.pick_and_place_configuration#L34)):*
> ```
> }
> 
> table {
> ```

BTW: Some sort of meta comment on each of these configuration files to explain the purpose, the source of the params listed within etc might help with maintenance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-:-L0QZR7ahRZfCy8zv1LU:bf1s1qm)*

**Comment by avalenzu** [comment]
+(status: curate commits before merging) 

---

Review status: 8 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_planner.cc, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QXy4U0bglnx8-rbab:-L0QZxZ9MKu3ejFDLfjQ:b-nkztyb) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_planner.cc#L86)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: do you see any value at all in having named getters for these ports? Or is it dead obvious? Seems slightly obscure to use the port IDs, even if only the 0 ports.
</blockquote></details>

The ones with indices are actually just the pub/sub blocks. I've created #7621 to capture this point. 

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/README.md, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QWmxG_1QTLP4S92NP:-L0QkKwBrlf698Q4xBfW:b567pae) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/README.md#L2)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: I know its repetition but a sentence here saying what this demo is for before launching into details will be good.
</blockquote></details>

Good call. I moved the "what happens in this demo" section up here.

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QYbdg3N1f9_nLIECQ:-L0QakogARoMJ9m_Bpsi:bmjdov8) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/README.md#L9)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Just confirming - would each of these links take you directly to their respective Doxy page? I think it should but would be good if you could double check.
</blockquote></details>

These aren't links actually, they're just the names of the executables. I tried adding links to the `.cc` files on github, but it makes the plain text view of this file way to hard to read.

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/README.md, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QWYv6zZQa1F-mDdxQ:-L0Qb1WQpsgsP4ZRTFMU:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/README.md#L90)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Excellent work with the documentation.
</blockquote></details>

Thanks!

---

*[examples/kuka_iiwa_arm/dev/pick_and_place/configuration/yellow_posts.pick_and_place_configuration, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-L0QV5wc_n2CmfGevjfp:-L0QeyaVcO6lp20thhKu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c312b5de8d4862371a1100c476da44a99e3ec89a/examples/kuka_iiwa_arm/dev/pick_and_place/configuration/yellow_posts.pick_and_place_configuration#L34)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Some sort of meta comment on each of these configuration files to explain the purpose, the source of the params listed within etc might help with maintenance.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-:-L0Qkhq9DtQq0lwXRPdG:b-s794vx)*

**Comment by avalenzu** [comment]
-(status: curate commits before merging) 

---

Review status: 8 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7610#-:-L0QusXIJ7qzbjesl9d8:b-l70wzf)*

**Pull request merged**
