### PR TITLE
Enable numpy math functions to work with symbolic variables.

### PR DESCRIPTION
**Pull request by soonho-tri**
https://github.com/RobotLocomotion/drake/issues/15038

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)

### CODE REVIEW

**Review by soonho-tri — COMMENTED** [review]
+@russtedrake for feature-review, please.
+@ericcousineau-tri for platform-review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039#-:-M_W5IvZ5mQDH0XRTCNH:b-15w3s0)* status: LGTM missing from assignees RussTedrake(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

**Comment by jwnimmer-tri** [comment]
FYI do you want `Expression` as well as `Variable` to have these methods?

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @RussTedrake and @soonho-tri)

___
*[bindings/pydrake/symbolic_py.cc, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_WAIhA5VMd2bROUqXg:-M_WAIhA5VMd2bROUqXh:bvkmq5k) ([raw file](https://github.com/robotlocomotion/drake/blob/02494e183fa1ecf5b40f6ac46c19593df926afe7/bindings/pydrake/symbolic_py.cc#L119)):*
> ```cpp
>           },
>           py::is_operator())
>       // We add the following methods (exp, sqrt, sin, cos, tan, arcsin, arccos,
> ```

Ah, sorry; if you see the following, it may be possible to retarget the following method to do what you want:
https://github.com/RobotLocomotion/drake/blob/da1d0d6c4977b31074e964085f833184832909f2/bindings/pydrake/symbolic_types_pybind.h#L28-L66

I'll see if I can do a quick PR

**Comment by soonho-tri** [comment]
> FYI do you want Expression as well as Variable to have these methods?

@jwnimmer-tri , FYI, we've already handled the case:

Screen Shot 2021-05-12 at 11 30 00 AM

**Comment by soonho-tri** [comment]
> I'll see if I can do a quick PR

@EricCousineau-TRI , OK. Please ping me when you open your PR.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[bindings/pydrake/symbolic_py.cc, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_WAIhA5VMd2bROUqXg:-M_WF4Vt5b8rFrgY6fzx:be15srb) ([raw file](https://github.com/robotlocomotion/drake/blob/02494e183fa1ecf5b40f6ac46c19593df926afe7/bindings/pydrake/symbolic_py.cc#L119)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, sorry; if you see the following, it may be possible to retarget the following method to do what you want:
https://github.com/RobotLocomotion/drake/blob/da1d0d6c4977b31074e964085f833184832909f2/bindings/pydrake/symbolic_types_pybind.h#L28-L66

I'll see if I can do a quick PR
</blockquote></details>

I've filed the following against this PR: https://github.com/soonho-tri/drake/pull/30

Didn't fully vet testing; please let me know if it's worth polishing this approach, and I can try to doc a bit more.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @RussTedrake and @soonho-tri)

___
*[bindings/pydrake/symbolic_py.cc, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_WAIhA5VMd2bROUqXg:-M_WFDzl-IpiwzfzB74O:b3phwv4) ([raw file](https://github.com/robotlocomotion/drake/blob/02494e183fa1ecf5b40f6ac46c19593df926afe7/bindings/pydrake/symbolic_py.cc#L119)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I've filed the following against this PR: https://github.com/soonho-tri/drake/pull/30

Didn't fully vet testing; please let me know if it's worth polishing this approach, and I can try to doc a bit more.
</blockquote></details>

"fully vet testing" => I ran `bazel test` and it passes; however, I didn't add new tests

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)* status: LGTM missing from assignees EricCousineau-TRI(platform),RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[bindings/pydrake/symbolic_py.cc, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_WAIhA5VMd2bROUqXg:-M_WOhla59hse8Po8Z7c:b-54elvc) ([raw file](https://github.com/robotlocomotion/drake/blob/d9074e3e562fe9989a8d2e19988a782a7c1185fb/bindings/pydrake/symbolic_py.cc#L119)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

"fully vet testing" => I ran `bazel test` and it passes; however, I didn't add new tests
</blockquote></details>

OK Sweet! I'll push a few more fixes (including fixing CI).

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @RussTedrake, and @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_WOm35-XHlHJ7R7zwn:-M_WOm363hmCFmEnPbMl:b-nl8cpv) (no related file):*
nit Does this close above referenced issue? (at present, this only references it)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)* status: 2 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @RussTedrake, and @soonho-tri)

___
*[bindings/pydrake/symbolic_types_pybind.h, line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_WRkrj5iBN7DL2NZbu:-M_WRkrj5iBN7DL2NZbv:b-kxifj2) ([raw file](https://github.com/robotlocomotion/drake/blob/9356274df55f8e7f2c290e388e8e22feb71f3390/bindings/pydrake/symbolic_types_pybind.h#L58)):*
> ```objc
>       .def("atan", &symbolic::atan, doc.atan.doc)
>       .def("arctan2", &symbolic::atan2, doc.atan2.doc)
>       .def("atan2", &symbolic::atan2, doc.atan2.doc)
> ```

Working: Significance of each separate overload is opaque. Trying to clarify with docs.

**Review by soonho-tri — COMMENTED** [review]
-@ericcousineau-tri 
+@soonho-tri . With Eric's commit, I've only added the test cases. So I'll play the role of platform-reviewer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039#-:-M_WVtoS4ALBNS-1NUQC:b-vxuues)* status: 2 unresolved discussions, LGTM missing from assignees soonho-tri(platform),RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @RussTedrake, and @soonho-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)* status: 1 unresolved discussion, LGTM missing from assignees soonho-tri(platform),RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @RussTedrake, and @soonho-tri)

___
*[bindings/pydrake/symbolic_types_pybind.h, line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_WRkrj5iBN7DL2NZbu:-M_WXoNABjqCPVi1Z0_P:bzcllpj) ([raw file](https://github.com/robotlocomotion/drake/blob/9356274df55f8e7f2c290e388e8e22feb71f3390/bindings/pydrake/symbolic_types_pybind.h#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Significance of each separate overload is opaque. Trying to clarify with docs.
</blockquote></details>

OK Further docs will pollute scope of this PR. Opened #15041

**Review by EricCousineau-TRI — COMMENTED** [review]
I've strictly timed out for this week; my suggestion is that this is a strict improvement. There's a mess underyling, but that can be resolved via follow-up such as #15041 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039#-:-M_WZREU6m7RWhPdVd-U:b28m6ot)* status: 1 unresolved discussion, LGTM missing from assignees soonho-tri(platform),RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @RussTedrake, and @soonho-tri)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039#-:-M_XcLJwBK4NDeF3KYaH:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @soonho-tri)

___
*[bindings/pydrake/symbolic_types_pybind.h, line 77 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_XcBaeDE_n62bc34hR:-M_XcBaeDE_n62bc34hS:b-3mw3sm) ([raw file](https://github.com/robotlocomotion/drake/blob/7869d6e6b869093c3100e8d1639046dfefa64689/bindings/pydrake/symbolic_types_pybind.h#L77)):*
> ```objc
>      // dtype=object. Deprecate and move solely into `pydrake.math`.
>       .def(
>           "inv",
> ```

nit: is this covered by a test?  (I couldn't see it)?

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake and @soonho-tri)

___
*[bindings/pydrake/symbolic_types_pybind.h, line 77 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_XcBaeDE_n62bc34hR:-M_fCNFLBwbpcX8x_CTH:b-g44aos) ([raw file](https://github.com/robotlocomotion/drake/blob/7869d6e6b869093c3100e8d1639046dfefa64689/bindings/pydrake/symbolic_types_pybind.h#L77)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: is this covered by a test?  (I couldn't see it)?
</blockquote></details>

OK Yup! Actually, failures from prior revision was b/c I accidentally dropped this from the bindings :sweat_smile:

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 4 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039#-:-M_fSAAmDWDWONKasStk:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_WOm35-XHlHJ7R7zwn:-M_fSDwx6LW8VGObnM_i:b-ylmap3) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Does this close above referenced issue? (at present, this only references it)
</blockquote></details>

I'll check it after merging this PR.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_fSMeN34iMbcYm1kyZ:-M_fSMeN34iMbcYm1ky_:b-uqj3s0) (no related file):*
@ericcousineau-tri , could you squash everything into a single commit and update this PR? Currently, if we squash this, I'm afraid I'll be the author of all the changes.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15039)* status: 1 unresolved discussion (waiting on @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15039#-M_fSMeN34iMbcYm1kyZ:-M_lszfhB_npPDDH63vH:b-896fja) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@ericcousineau-tri , could you squash everything into a single commit and update this PR? Currently, if we squash this, I'm afraid I'll be the author of all the changes.
</blockquote></details>

Done!

---

**Pull request merged**
