### PR TITLE
Improve color image rendering speed

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This PR improves color image (not depth nor label image) rendering speed from 130 ms to 80 ms on my local environment. The rest of 80 ms is mostly consumed during VTK rendering process.

[CAUTION] RgbdCamera now outputs ImageRgba8U instead of ImageBgra8U

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6361)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@ericcousineau-tri feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6361#-:-KmmPEqboK9DrSaBTVvK:b-6wg1k9)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6361#-:-KmmazHmJ0ON9ppt5dnN:bpqxd5f)*

**Comment by kunimatsu-tri** [comment]
+@sherm1 platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6361#-:-KmmbeFlTyOxlR7whEuE:bqs0osh)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6361#-:-Kmmg-J2rnLeFle1Y6CC:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
Thank you both @EricCousineau-TRI and @sherm1 for your quick review!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6361#-:-KmmgFDUg4Uev5c1iVEw:b3vaagv)*

**Pull request merged**
