### PR TITLE
Give RigidBodyPlant per-system input and output ports (take 2)

### PR DESCRIPTION
**Pull request by sammy-tri**
#4506 redux, with additional change to VerifyInputPort

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4570)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@david-german-tri for both levels of review on the Context::VerifyInputPort change (we'd discussed it f2f previously).  The rest of the changes already passed review in #4506.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4570#-:-KZXAunZrJR3APva_zCu:b3kf9hf)*

**Comment by david-german-tri** [comment]
:lgtm: for context.h, didn't look at the rest

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4570#-:-KZXYbl866A8B4oeV_LX:b-ajmltw)*

**Comment by liangfok** [comment]
Just to ensure I understand: Is it true that with this PR we are now allowed to _not_ connect a system's input port?

**Comment by david-german-tri** [comment]
> Is it true that with this PR we are now allowed to not connect a system's input port?

Yes.  That was never intended to be prohibited.

**Comment by liangfok** [comment]
I wonder if it'll be worthwhile to allow users to attach input port connection requirement semantics like "this port must be connected" or "one port within this set of ports must be connected" or "this port can optionally be connected", etc. Would such a feature be useful for ensuring a system's correctness, and debugging incorrectly wired up systems?

**Comment by sherm1** [comment]
> I wonder if it'll be worthwhile to allow users to attach input port connection requirement semantics like "this port must be connected" 

If anyone accesses an unconnected input port they'll still get a runtime error. I would propose that we wait to see if that is adequate before adding more to the API.

**Pull request merged**
