### PR TITLE
Add bazel support for gcc-6 in Linux

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5290)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@david-german-tri , I added it to test the `rotmat2quat` with `gcc-6` on a linux box. I think it's not bad to have it in Drake. Could you review it if you think so?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-Kdgo8SWTkQKKWocyFE6:b-12ri6e)*

**Comment by david-german-tri** [comment]
I can't test this locally right now; could you find someone else on Xenial or OS X to confirm?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-KdgogRq00CK7fqdlwqr:be576cj)*

**Comment by soonho-tri** [comment]
-@david-german-tri , sure.

+@jwnimmer-tri , could you take a look?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-KdgpNBBXm3F81G2Jf-b:b-x34feu)*

**Comment by soonho-tri** [comment]
>  on Xenial or OS X to confirm?

FWIW, `--compiler=gcc-X` only works on Linux.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-Kdgpdl2OnSB7MaeziaJ:b9ybxjm)*

**Comment by jwnimmer-tri** [comment]
*[tools/BUILD, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-Kdh0oeHvGMz2Z8FRJrR:-Kdh0oeHvGMz2Z8FRJrS:byq9z1y) ([raw file](https://github.com/robotlocomotion/drake/blob/22a3fc108bfa10a5b70fc42c2bc0409f6012f71d/tools/BUILD#L47)):*
> ```Python
> # wrapper script is needed for any of these compilers, so the
> # cc_toolchain rule does not provide one.
> cc_toolchain_suite(
> ```

This text needs to be clearer that GCC6 is a thing you can type in, but we make no promises that it will work -- that it is not "supported" in the sense of http://drake.mit.edu/developers.html#supported-configurations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/BUILD, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-Kdh0oeHvGMz2Z8FRJrR:-KdhfZQaU7uSp5XNu2qr:b-hi1da8) ([raw file](https://github.com/robotlocomotion/drake/blob/22a3fc108bfa10a5b70fc42c2bc0409f6012f71d/tools/BUILD#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This text needs to be clearer that GCC6 is a thing you can type in, but we make no promises that it will work -- that it is not "supported" in the sense of http://drake.mit.edu/developers.html#supported-configurations.
</blockquote></details>

I see. How about adding the following sentences at the end of the original paragraph?


"Support for "gcc-6" is experimental without any guarantees. Note that it is not in our supported configurations yet. See http://drake.mit.edu/developers.html#supported-configurations for more information". 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290)*

**Comment by jwnimmer-tri** [comment]
*[tools/BUILD, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-Kdh0oeHvGMz2Z8FRJrR:-Kdhmw0CRytPQ2IoxhFX:b-80tlqk) ([raw file](https://github.com/robotlocomotion/drake/blob/22a3fc108bfa10a5b70fc42c2bc0409f6012f71d/tools/BUILD#L47)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I see. How about adding the following sentences at the end of the original paragraph?


"Support for "gcc-6" is experimental without any guarantees. Note that it is not in our supported configurations yet. See http://drake.mit.edu/developers.html#supported-configurations for more information". 
</blockquote></details>

Sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/BUILD, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-Kdh0oeHvGMz2Z8FRJrR:-Kdhn8S_rgKVgoqX3qgf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/22a3fc108bfa10a5b70fc42c2bc0409f6012f71d/tools/BUILD#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290)*

**Comment by jwnimmer-tri** [comment]
:lgtm: pending open discussions.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-Kdhy21a2ZS_kEsAzz7b:-Kdhy21bvwVcg5FK7gSY:b-6nfhhk) (no related file):*
I haven't had a chance to test this yet, so someone should do that before we merge.

---

*[tools/BUILD, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-KdhxjBQr46imOAfHZEy:-KdhxjBQr46imOAfHZEz:b-bf26wy) ([raw file](https://github.com/robotlocomotion/drake/blob/531ec59fbd1ea04ebf7b2234d375b8a4137773b9/tools/BUILD#L44)):*
> ```Python
> # /usr/bin/gcc as well as /usr/bin/clang, and the wrapper script invokes the
> # former.
> #
> ```

Why did this comment go away?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-Kdhy5o149-KtpbDtUbz:buvdl6p)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/BUILD, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-KdhxjBQr46imOAfHZEy:-Kdi-vgzlVKWHIHLsmNs:b-pb64aq) ([raw file](https://github.com/robotlocomotion/drake/blob/531ec59fbd1ea04ebf7b2234d375b8a4137773b9/tools/BUILD#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why did this comment go away?
</blockquote></details>

Done. Thank you for catching this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-Kdhy21a2ZS_kEsAzz7b:-Kdi00pt3dr523BAn0_q:b-pucdnq) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I haven't had a chance to test this yet, so someone should do that before we merge.
</blockquote></details>

I've checked it on a Linux box running 14.04. I'll ask if anyone using 16.04 can check this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290)*

**Comment by liangfok** [comment]
I just ran into the following problem:

```
$ bazel build --compiler=gcc-6 ...
........
INFO: Found 1410 targets...
ERROR: /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/external/gtest/BUILD:3:1: C++ compilation of rule '@gtest//:main' failed: linux-sandbox failed: error executing command /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake-distro-1/_bin/linux-sandbox ... (remaining 51 argument(s) skipped).
src/main/tools/linux-sandbox-pid1.cc:595: "execvp(/usr/bin/gcc-6, 0xff6830)": No such file or directory
INFO: Elapsed time: 35.094s, Critical Path: 0.52s
```

Here is what I have installed:

```
$ dpkg -l | grep gcc-6
ii  gcc-6-base:amd64                            6.0.1-0ubuntu1                                              amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-6-base:i386                             6.0.1-0ubuntu1                                              i386         GCC, the GNU Compiler Collection (base package)
```
Any idea what's wrong?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-Kdi2jVWaF6L1NGBRSof:b9r0r1h)*

**Comment by liangfok** [comment]
Maybe there's some other package I need to install to get `/usr/bin/gcc-6`?

```
$ ls -lah /usr/bin/gcc*
lrwxrwxrwx 1 root root    5 Sep 22 09:37 /usr/bin/gcc -> gcc-5
-rwxr-xr-x 1 root root 895K Nov  2 22:00 /usr/bin/gcc-5
lrwxrwxrwx 1 root root    8 Sep 22 09:37 /usr/bin/gcc-ar -> gcc-ar-5
-rwxr-xr-x 1 root root  31K Nov  2 22:00 /usr/bin/gcc-ar-5
lrwxrwxrwx 1 root root    8 Sep 22 09:37 /usr/bin/gcc-nm -> gcc-nm-5
-rwxr-xr-x 1 root root  31K Nov  2 22:00 /usr/bin/gcc-nm-5
lrwxrwxrwx 1 root root   12 Sep 22 09:37 /usr/bin/gcc-ranlib -> gcc-ranlib-5
-rwxr-xr-x 1 root root  31K Nov  2 22:00 /usr/bin/gcc-ranlib-5
```

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-Kdi4M-pHgSGNuEfK0Xl:bdskr77)*

**Comment by soonho-tri** [comment]
I think `sudo apt-get install g++-6-multilib gfortran-6` should be good enough.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-Kdi4zQgvoIIAO4FTb0S:beg7xwk)*

**Comment by liangfok** [comment]
Does this require adding a new PPA?

```
$ sudo apt-get install g++-6-multilib gfortran-6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package g++-6-multilib
E: Couldn't find any package by regex 'g++-6-multilib'
E: Unable to locate package gfortran-6
```

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-Kdi8yJxgUdWGAjPZhmW:b-wsqej7)*

**Comment by soonho-tri** [comment]
Probably, yes. (I don't have 16.04 box yet).

If you don't mind, please try `sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test`.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-Kdi9J83B-KZnGWpBXjP:b-5mw9lj)*

**Comment by liangfok** [comment]
Thanks, the following worked:

```
$ sudo apt-get install g++-6-multilib gfortran-6
$ sudo apt-get update
$ sudo apt-get install g++-6-multilib gfortran-6
$ ls -lah /usr/bin/gcc-6*
-rwxr-xr-x 1 root root 931K Sep  4 17:17 /usr/bin/gcc-6
```

I'm building Drake now using `bazel build --compiler=gcc-6 ...`.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-KdiAiTDctunOYuwx0Zh:b-e38qoc)*

**Comment by soonho-tri** [comment]
Great!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-KdiBQ2veZ9Us5Y2x5DH:btojbfd)*

**Comment by liangfok** [comment]
The build was successful:

```
$ bazel build --compiler=gcc-6 ...
........
INFO: Elapsed time: 1174.033s, Critical Path: 1142.36s
```

And the tests were successful:

```
$ bazel test ...
...
Executed 1053 out of 1053 tests: 1053 tests pass.
```

Since all uint tests pass, this :lgtm:. Note, however, that I didn't actually check the contents of this PR. I can only confirm that I was able to build Drake on Ubuntu 16.04 using gcc-6 and sucessfully pass all unit tests.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5290#-:-KdiJEL9MF-aeifpqQLt:b-w4bofz)*

**Pull request merged**
