### PR TITLE
Refactors Kuka benchmark into an MBT factory

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR has two portions:
1. A pure refactor taking code out of the benchmark `DrakeKukaIIwaRobot` into a factory so that we can reuse the MBT model of the arm in MBT unit tests.
2. Implements functionality in MBT to retrieve components by name.

The refactored code is used in the kuka benchmarks as well.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7995)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
looks good, I am assuming #7947 will become much lighter? as the hardcoded model building part is moved to this pr. 
it's not clear to me "Per your request, and thanks to Jeremy, I was able to figure out a way to provide the API you like (which I actually do like much better!) without sacrificing caching and avoiding cyclic dependencies back to the system." yet, but this pr by itself makes a lot of sense anyway. 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h, line 128 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7995#-L4nZ0T2BLVDSO4EaomK:-L4nZ0T2BLVDSO4EaomL:bcwvroo) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b096395ee9f37b71f34f3757371a8bc5229400/multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h#L128)):*
> ```objc
>     PositionKinematicsCache<T> pc(model_->get_topology());
>     VelocityKinematicsCache<T> vc(model_->get_topology());
>     AccelerationKinematicsCache<T> ac(model_->get_topology());
> ```

is this unused? 

---

*[multibody/multibody_tree/multibody_tree.h, line 537 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7995#-L4nWDPr4d6_r3e1EVp2:-L4nWDPr4d6_r3e1EVp3:b-3d06ra) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b096395ee9f37b71f34f3757371a8bc5229400/multibody/multibody_tree/multibody_tree.h#L537)):*
> ```objc
>             *frame_on_parent, *frame_on_child,
>             std::forward<Args>(args)...));
>     joint_name_to_index_[name] = joint.get_index();
> ```

not sure if you need to check joint name uniqueness? 

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 33 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7995#-L4nUbfm-N0gdboIceIF:-L4nUbfm-N0gdboIceIG:b-lwz8iy) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b096395ee9f37b71f34f3757371a8bc5229400/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L33)):*
> ```cpp
> template<typename U>
> MultibodyPlant<T>::MultibodyPlant(const MultibodyPlant<U>& other) {
>   DRAKE_THROW_UNLESS(!is_finalized());
> ```

do you need other.is_finalized()?

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 104 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7995#-L4nX18H-QVD5NR_a1wq:-L4nX18H-QVD5NR_a1wr:b-xiegmb) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b096395ee9f37b71f34f3757371a8bc5229400/multibody/multibody_tree/test/multibody_tree_test.cc#L104)):*
> ```cpp
>                std::logic_error);
> }
> ```

i'd add some separate tests to just test the MBT.addJoint / addbody. there is some unique name logic not being tested here. i am happy if you put a todo here, since this is blocking #7947.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7995#-:-L4nZH0A7mvHmJJYXA_p:b-7c01bo)*

**Comment by amcastro-tri** [comment]
ha, yeah, I guess it doesn't without a bit of context. Essentially what I mean is that the plan thus far was that MBP would provide you with the `Calc` methods (since we wanted to leverage on system's caching). Now we realized (Jeremy did) that we can place those in MBT, still being able to use system's caching, but without having to introduce an MBT dependency on `systems::` (that would've meant: MBP (a system) depends on MBT and MBT depends on system (for caching) --> cyclic dependency). I can give you more details when you are back if you want.
The final result is: Everything `CalcTimeDerivatives()` goes through MBP, everything `CalcSomeMultibodyQuantity()` gets exposed through MBT.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4nZ0T2BLVDSO4EaomK:-L4q4-eoMIPLBVkxLCPf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b096395ee9f37b71f34f3757371a8bc5229400/multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h#L128)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

is this unused? 
</blockquote></details>

Done.

---

*[multibody/multibody_tree/multibody_tree.h, line 537 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4nWDPr4d6_r3e1EVp2:-L4pmK2G_y9kHk7TYuib:boj1qgt) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b096395ee9f37b71f34f3757371a8bc5229400/multibody/multibody_tree/multibody_tree.h#L537)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

not sure if you need to check joint name uniqueness? 
</blockquote></details>

Good catch. Done.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4nUbfm-N0gdboIceIF:-L4q3VfKJGIdJgPlUD-f:b-satcwl) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b096395ee9f37b71f34f3757371a8bc5229400/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L33)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

do you need other.is_finalized()?
</blockquote></details>

Good catch. I actually had fixed this in #7947 where I do scalar convert the plant. Done.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4nX18H-QVD5NR_a1wq:-L4q3kUFDftZjmzBQj6u:byy8g2l) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b096395ee9f37b71f34f3757371a8bc5229400/multibody/multibody_tree/test/multibody_tree_test.cc#L104)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i'd add some separate tests to just test the MBT.addJoint / addbody. there is some unique name logic not being tested here. i am happy if you put a todo here, since this is blocking #7947.
</blockquote></details>

I added a bunch more. But I might be missing more... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-:-L4pk1vioKvAHRCaXJjG:bo9l9l9)*

**Comment by amcastro-tri** [comment]
+@soonho-tri for platform review please.

---

Review status: 2 of 11 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-:-L4q5vo1ngsSZmHkdOfZ:b-vt9vbo)*

**Comment by siyuanfeng-tri** [comment]
lovely. :lgtm: 

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4nX18H-QVD5NR_a1wq:-L4q6sERO775F78CYRiP:b-61nefa) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b096395ee9f37b71f34f3757371a8bc5229400/multibody/multibody_tree/test/multibody_tree_test.cc#L104)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I added a bunch more. But I might be missing more... 
</blockquote></details>

yeah well.. i am imagining this file is going to be super long. marking myself happy here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-:-L4q6988mxljrAQYXC1Q:b-cp3e3m)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.h, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4q7qT9c8TKIwjN0Ek2:-L4q7qT9c8TKIwjN0Ek3:b-4dgifo) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0b9b07828395f52a386ad9ad62c2da3721ad9d/multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.h#L29)):*
> ```objc
> ///   If `true`, the model is finalized with MultibodyTree::Finalize().
> ///   A non-finalized model can be requested if adding more multibody elements
> ///   is desired.
> ```

BTW indent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7995)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 9 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.h, line 513 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4qa5nY7W_gBX0E16oS:-L4qa5nY7W_gBX0E16oT:b2ostfx) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0b9b07828395f52a386ad9ad62c2da3721ad9d/multibody/multibody_tree/multibody_tree.h#L513)):*
> ```objc
>   /// @throws if `this` model already contains a joint with the given `name`.
>   /// See HasJointNamed(), Joint::get_name().
>   ///
> ```

BTW, consider adding `@return` section as you did for `AddRigidBody` above.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 253 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4qeU4guzI8coWx1PzG:-L4qeU4guzI8coWx1PzH:b-pj4u3z) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0b9b07828395f52a386ad9ad62c2da3721ad9d/multibody/multibody_tree/multibody_plant/multibody_plant.h#L253)):*
> ```objc
>   /// @throws if `this` model already contains a joint with the given `name`.
>   /// See HasJointNamed(), Joint::get_name().
>   ///
> ```

BTW, similarly, consider adding `@return` section as you did for `AddRigidBody` above.

---

*[multibody/multibody_tree/test_utilities/expect_error_message.h, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4qemGdIQQvLVv0rH3V:-L4qemGdIQQvLVv0rH3W:b-jog99b) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0b9b07828395f52a386ad9ad62c2da3721ad9d/multibody/multibody_tree/test_utilities/expect_error_message.h#L3)):*
> ```objc
> #pragma once
> 
> // Remove this duplication once #8003 is addressed.
> ```

FYI, need `TODO(name): ` here.

---

*[multibody/multibody_tree/test_utilities/expect_error_message.h, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4qfFOJYbzSN0vlFPVq:-L4qfFOJYbzSN0vlFPVr:b-g65mqf) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0b9b07828395f52a386ad9ad62c2da3721ad9d/multibody/multibody_tree/test_utilities/expect_error_message.h#L9)):*
> ```objc
> // Helper macro for "expecting" an exception but *also* testing the error
> // message against the provided regular expression.
> #define EXPECT_ERROR_MESSAGE(expression, exception, reg_exp) \
> ```

I think the name of this macro is too general. How about making it `DRAKE_EXPECT_ERROR_MESSAGE`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-:-L4qkJRGQYLy0BRFWHPy:bnfp4nl)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/test_utilities/expect_error_message.h, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7995#-L4qfFOJYbzSN0vlFPVq:-L4r1vNsQYshQ_ta30TY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0b9b07828395f52a386ad9ad62c2da3721ad9d/multibody/multibody_tree/test_utilities/expect_error_message.h#L9)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think the name of this macro is too general. How about making it `DRAKE_EXPECT_ERROR_MESSAGE`? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7995)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7995)*

**Pull request merged**
