### PR TITLE
[install] Add lcm and autodiff support to drake_bazel_installed

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake-external-examples/pull/237.

Follow-up from #17968.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18008)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Ready for feature review in case @EricCousineau-TRI or @SeanCurtis-TRI wants to jump in.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18008#-:-NDTFM4oCrjS4VUzIfNN:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18008#-:-NDTJFV7DRLhE3lKJAeg:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
