### PR TITLE
Implements MBT method to compute geometric Jacobian.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implements `CalcPointsGeometricJacobianExpressedInWorld()` to compute the geometric Jacobian for a set of points attached to a given frame.
The implementation is tested on a model of the Kuka iiwa arm by computing Jacobians using `AutoDiffXd`. Topology tests are included as well on new functionality.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7510)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-:-KzrD7q5HasVN_7nWD6Z:bl5ccwd)*

**Comment by hongkai-dai** [comment]
Checkpoint. This looks great. 

---

Reviewed 3 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 633 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-KzwGzHB6lSHFupOhqsT:-KzwGzHB6lSHFupOhqsU:b-2ij4pv) ([raw file](https://github.com/robotlocomotion/drake/blob/562ddc292e327896acc607ec600be812bf58b315/drake/multibody/multibody_tree/multibody_tree.cc#L633)):*
> ```cpp
>     Eigen::Map<const MatrixUpTo6<T>> H_PB_W =
>         node.GetJacobianFromArray(H_PB_W_cache);
>     auto J_PBq_W = J_WQi->block(0, start_index_in_v, Jnrows, num_velocities);
> ```

It is better not to use `auto` for Eigen block matrix. See the issue in https://eigen.tuxfamily.org/dox/TopicPitfalls.html

---

*[drake/multibody/multibody_tree/multibody_tree.h, line 1062 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-KzwDGK8zU5eFBYpSuBK:-KzwDGK8zU5eFBYpSuBL:b3uhewm) ([raw file](https://github.com/robotlocomotion/drake/blob/562ddc292e327896acc607ec600be812bf58b315/drake/multibody/multibody_tree/multibody_tree.h#L1062)):*
> ```objc
>   /// @{
> 
>   /// Given a set of points `Qi` with position vectors `p_WQi` in the world
> ```

It would be more clear, if you could mention that `Qi` is fixed to the `B` frame, before we write the equation
```
J_WQi(q) = d(v_WQi(q, v))/dv
```
, instead of after this paragraph. When I saw the equation, I was wondering in which frame `Qi` is fixed to.

---

*[drake/multibody/multibody_tree/multibody_tree_topology.h, line 759 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-KzwFsXEtt7AERGDyi47:-KzwFsXEtt7AERGDyi48:b-bzuv97) ([raw file](https://github.com/robotlocomotion/drake/blob/562ddc292e327896acc607ec600be812bf58b315/drake/multibody/multibody_tree/multibody_tree_topology.h#L759)):*
> ```objc
> 
>   void GetKinematicPathToWorld(
>       BodyNodeIndex from, std::vector<BodyNodeIndex>* path_to_world) const {
> ```

Document this function?

---

*[drake/multibody/multibody_tree/multibody_tree_topology.h, line 761 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-KzwG1kYTx0VZioVQm1e:-KzwG1kYTx0VZioVQm1f:bhb63ik) ([raw file](https://github.com/robotlocomotion/drake/blob/562ddc292e327896acc607ec600be812bf58b315/drake/multibody/multibody_tree/multibody_tree_topology.h#L761)):*
> ```objc
>       BodyNodeIndex from, std::vector<BodyNodeIndex>* path_to_world) const {
>     const int path_size = get_body_node(from).level + 1;
>     DRAKE_DEMAND(static_cast<int>(path_to_world->size()) == path_size);
> ```

In the documentation, we should mention that the size of `path_to_world` needs to be pre-allocated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-:-KzwF-k2p9j-PulcSw2x:bvrwtsg)*

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental  please

**Comment by amcastro-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 633 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-KzwGzHB6lSHFupOhqsT:-Kzy9MMN6UcwYf8E8IhM:b1vnkqz) ([raw file](https://github.com/robotlocomotion/drake/blob/562ddc292e327896acc607ec600be812bf58b315/drake/multibody/multibody_tree/multibody_tree.cc#L633)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is better not to use `auto` for Eigen block matrix. See the issue in https://eigen.tuxfamily.org/dox/TopicPitfalls.html
</blockquote></details>

I think we'be been consistently using `auto` in most places where we expect some sort of `Eigen::Block` to avoid having to figure out all the parameters in the particular template for that block. The case link you mention talks about the danger of using `auto` when the result of your operation is (as in most cases) an expression representing an operation. 
I see your point (and in most cases I agree with on not using `auto`) but I think for the block returns we are safe and it really does help us avoid having to figure out a chain reactions of parameters.
BTW, in this case the "proper" return type that `auto` resolves to is an `Eigen::Block<Eigen::Ref<MatrixX<T>>>`. IMO adding it actually obscures what is going on. I will add it however if you think it does look better or is clearer.

---

*[drake/multibody/multibody_tree/multibody_tree.h, line 1062 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-KzwDGK8zU5eFBYpSuBK:-KzyJtgJpbCDz5w8Oq3q:b-qiop5z) ([raw file](https://github.com/robotlocomotion/drake/blob/562ddc292e327896acc607ec600be812bf58b315/drake/multibody/multibody_tree/multibody_tree.h#L1062)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It would be more clear, if you could mention that `Qi` is fixed to the `B` frame, before we write the equation
```
J_WQi(q) = d(v_WQi(q, v))/dv
```
, instead of after this paragraph. When I saw the equation, I was wondering in which frame `Qi` is fixed to.
</blockquote></details>

True. I updated the doc to include that info right before. I hope it is clearer now.

---

*[drake/multibody/multibody_tree/multibody_tree_topology.h, line 759 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-KzwFsXEtt7AERGDyi47:-KzyOs4uQwsbHijS8GOe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/562ddc292e327896acc607ec600be812bf58b315/drake/multibody/multibody_tree/multibody_tree_topology.h#L759)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Document this function?
</blockquote></details>

Done.

---

*[drake/multibody/multibody_tree/multibody_tree_topology.h, line 761 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-KzwG1kYTx0VZioVQm1e:-KzyOsRUUrNM2qaxsHBP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/562ddc292e327896acc607ec600be812bf58b315/drake/multibody/multibody_tree/multibody_tree_topology.h#L761)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

In the documentation, we should mention that the size of `path_to_world` needs to be pre-allocated.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510)*

**Comment by amcastro-tri** [comment]
Thank you @hongkai-dai! back to you.

---

Review status: 1 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-:-KzyPFF7SDngIEQaPCgF:b-3ly49k)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri for platform review please.

---

Reviewed 2 of 7 files at r1, 3 of 3 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_jacobian_test.cc, line 41 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-L-093VrivDTYwFUpXbp:-L-093VrivDTYwFUpXbq:b-ag6v4s) ([raw file](https://github.com/robotlocomotion/drake/blob/99c9ec8f2e70cd1fc4c22dfd4753f88330f42e29/drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_jacobian_test.cc#L41)):*
> ```cpp
>   // A set of values for the joint's angles chosen mainly to avoid in-plane
>   // motions.
>   double q30 = M_PI / 6, q60 = M_PI / 3;
> ```

BTW, `double` -> `const double`

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_jacobian_test.cc, line 158 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-L-0R9_1FDii5B3rkJzg:-L-0R9_1FDii5B3rkJzh:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/99c9ec8f2e70cd1fc4c22dfd4753f88330f42e29/drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_jacobian_test.cc#L158)):*
> ```cpp
>   // A set of values for the joint's angles chosen mainly to avoid in-plane
>   // motions.
>   double q30 = M_PI / 6, q60 = M_PI / 3;
> ```

ditto

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 633 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-KzwGzHB6lSHFupOhqsT:-L-05G873C92r-vPbYeq:bels5of) ([raw file](https://github.com/robotlocomotion/drake/blob/562ddc292e327896acc607ec600be812bf58b315/drake/multibody/multibody_tree/multibody_tree.cc#L633)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think we'be been consistently using `auto` in most places where we expect some sort of `Eigen::Block` to avoid having to figure out all the parameters in the particular template for that block. The case link you mention talks about the danger of using `auto` when the result of your operation is (as in most cases) an expression representing an operation. 
I see your point (and in most cases I agree with on not using `auto`) but I think for the block returns we are safe and it really does help us avoid having to figure out a chain reactions of parameters.
BTW, in this case the "proper" return type that `auto` resolves to is an `Eigen::Block<Eigen::Ref<MatrixX<T>>>`. IMO adding it actually obscures what is going on. I will add it however if you think it does look better or is clearer.
</blockquote></details>

I see, sounds good. I am OK with the current version.

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 647 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-L-06IAaF5KzWLfgZAvv:-L-06IAaF5KzWLfgZAvw:b-1aszp0) ([raw file](https://github.com/robotlocomotion/drake/blob/99c9ec8f2e70cd1fc4c22dfd4753f88330f42e29/drake/multibody/multibody_tree/multibody_tree.cc#L647)):*
> ```cpp
>       auto Hv_PBqi_W = J_PBq_W.block(3 * ipoint, 0, 3, num_velocities);
> 
>       // Aliases to translational and angular components in H_PB_W:
> ```

BTW, since `Hw_PB_W` comes before `Hv_PB_W`, it is better to mention "angular" before "translational" in the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-:-L-0RJDKECveUx69A9CZ:b-t6qajt)*

**Comment by amcastro-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_jacobian_test.cc, line 158 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-L-0R9_1FDii5B3rkJzg:-L-2BPd1RgWFStlmqlLY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/99c9ec8f2e70cd1fc4c22dfd4753f88330f42e29/drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_jacobian_test.cc#L158)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510)*

**Comment by sammy-tri** [comment]
:lgtm: with one minor nit

---

Reviewed 3 of 7 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/multibody_tree/multibody_tree_topology.h, line 781 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-L-2CXAyOiP80h3xGZru:-L-2CXAzJwEyILUWWtJI:b-ujm4f) ([raw file](https://github.com/robotlocomotion/drake/blob/99c9ec8f2e70cd1fc4c22dfd4753f88330f42e29/drake/multibody/multibody_tree/multibody_tree_topology.h#L781)):*
> ```objc
>     const int path_size = get_body_node(from).level + 1;
>     DRAKE_THROW_UNLESS(path_to_world != nullptr);
>     DRAKE_THROW_UNLESS(static_cast<int>(path_to_world->size()) == path_size);
> ```

If we know the correct size of the output vector, why are we forcing the user to size the vector appropriately before calling the function instead of resizing it here if it's incorrect?  (There could be a reason for not conditionally performing allocation inside this function, but it's not obvious to me...  then again lots of multibody code seems to do require the user to pre-allocate their outputs in the required shape and the reason for that isn't obvious to me either).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-:-L-2IR_yLAh_01YVmOOV:b90e215)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/multibody_tree/multibody_tree_topology.h, line 781 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-L-2CXAyOiP80h3xGZru:-L-2fVxFkaVvhjmhbJJ_:b-brwxwl) ([raw file](https://github.com/robotlocomotion/drake/blob/99c9ec8f2e70cd1fc4c22dfd4753f88330f42e29/drake/multibody/multibody_tree/multibody_tree_topology.h#L781)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Good point, Done.
</blockquote></details>

A couple of issues...   First, the comment about only reallocating if smaller than path_size is a little misleading, with the unconditional `clear()`, it might reallocate more often.  Also, `reserve()` only allocates space, you've still got a vector of zero size unless `resize()` or `push_back()` (or `insert()` or what have you) are called IIRC.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510)*

**Comment by amcastro-tri** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/multibody_tree/multibody_tree_topology.h, line 781 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-L-2CXAyOiP80h3xGZru:-L-3DjTPo_fQegigPgw5:b46lhco) ([raw file](https://github.com/robotlocomotion/drake/blob/99c9ec8f2e70cd1fc4c22dfd4753f88330f42e29/drake/multibody/multibody_tree/multibody_tree_topology.h#L781)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

A couple of issues...   First, the comment about only reallocating if smaller than path_size is a little misleading, with the unconditional `clear()`, it might reallocate more often.  Also, `reserve()` only allocates space, you've still got a vector of zero size unless `resize()` or `push_back()` (or `insert()` or what have you) are called IIRC.
</blockquote></details>

Sorry, quick an dirty push before boarding my airplane. PTAL now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510)*

**Comment by sammy-tri** [comment]
:lgtm: pending the issue which CI caught

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7510#-:-L-3ZZMUhAgZtvq3qynr:b-u7q1y3)*

**Pull request merged**
