### PR TITLE
Add syntactic sugar for abstract-valued I/O.

### LINKED ISSUE #3217: Add model values for LeafSystem abstract I/O
See discussion on #3164.

cc @sherm1 @amcastro-tri

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #3217.  Factored out from #4823.

@siyuanfeng-tri for feature review, @jwnimmer-tri for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4829)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
cool! :lgtm: 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/leaf_system_test.cc, line 299 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4829#-KarfKwuOzj4wcSEMfe1:-KarfKwuOzj4wcSEMfe2:b-yotl5y) ([raw file](https://github.com/robotlocomotion/drake/blob/48488ae34a52d3f14d3172c65cbcd5b7497c1e4c/drake/systems/framework/test/leaf_system_test.cc#L299)):*
> ```cpp
> }
> 
> // Tests that the abstract-valued output as been allocated with the correct
> ```

BTW, as -> has?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4829#-:-Karf91bgENbgz2igOBq:b-qwpmnt)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/context.h, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4829#-KaryGAVVVtNq46KfqK0:-KaryGAVVVtNq46KfqK1:b248dcf) ([raw file](https://github.com/robotlocomotion/drake/blob/48488ae34a52d3f14d3172c65cbcd5b7497c1e4c/drake/systems/framework/context.h#L192)):*
> ```objc
>   /// Connects a FreestandingInputPort with the given vector @p value at the
>   /// given @p index. Asserts if @p index is out of range.
>   void FixInputPort(int index, std::unique_ptr<BasicVector<T>> value) {
> ```

BTW _Meta_ for both this and the next function, I think they are not performance-sensitive, and really intended as user convenience.  As such, would passing by const-reference be perhaps easier for the caller (`const BasicVetor<T>& value`, here).  I seem to recall that calling code does a lot of move-gymnastics in order to move a unique thing in here.  I don't think doing a Clone here (and below) would be a big deal?  (Maybe for a future PR, if the prior API changes; the new API could use the new signature though, if you think its better.)

---

*[drake/systems/framework/value.h, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4829#-KarxgR2C-I6LtK59ZRD:-KarxgR38Ayd4h6TydJs:bm6tw2l) ([raw file](https://github.com/robotlocomotion/drake/blob/48488ae34a52d3f14d3172c65cbcd5b7497c1e4c/drake/systems/framework/value.h#L97)):*
> ```objc
>   }
> 
>   template <typename T>
> ```

BTW This is a pretty obvious function, but a small API comment to explain its convenience might be worthwhile?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4829#-:-KarzBVfsgqsZ7fRoqkT:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/context.h, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4829#-KaryGAVVVtNq46KfqK0:-Kas9sYsEnGej8lMY0Xo:bfk1bqb) ([raw file](https://github.com/robotlocomotion/drake/blob/48488ae34a52d3f14d3172c65cbcd5b7497c1e4c/drake/systems/framework/context.h#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW _Meta_ for both this and the next function, I think they are not performance-sensitive, and really intended as user convenience.  As such, would passing by const-reference be perhaps easier for the caller (`const BasicVetor<T>& value`, here).  I seem to recall that calling code does a lot of move-gymnastics in order to move a unique thing in here.  I don't think doing a Clone here (and below) would be a big deal?  (Maybe for a future PR, if the prior API changes; the new API could use the new signature though, if you think its better.)
</blockquote></details>

I don't think the call sites are really that bad, so I'm not going to do this now, but I wouldn't be opposed to an additional overload either.  

---

*[drake/systems/framework/value.h, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4829#-KarxgR2C-I6LtK59ZRD:-KasA4KnEkoEtz6ZUZyc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/48488ae34a52d3f14d3172c65cbcd5b7497c1e4c/drake/systems/framework/value.h#L97)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This is a pretty obvious function, but a small API comment to explain its convenience might be worthwhile?
</blockquote></details>

Done.

---

*[drake/systems/framework/test/leaf_system_test.cc, line 299 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4829#-KarfKwuOzj4wcSEMfe1:-KasA8m3EmuqTroa59qS:bisenzy) ([raw file](https://github.com/robotlocomotion/drake/blob/48488ae34a52d3f14d3172c65cbcd5b7497c1e4c/drake/systems/framework/test/leaf_system_test.cc#L299)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, as -> has?
</blockquote></details>

I swear my keyboard is defective.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4829)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4829)*

**Pull request merged**
