### PR TITLE
Use patchelf from pip for wheel builds

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Simplify wheel builds by using PyPI to supply patchelf rather than building it ourselves. This also provides a newer version than we were previously using, which fixes a bug that caused library corruption with the latest version of auditwheel.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18163)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

+@jwnimmer-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18163)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
I've filed #18165 with the minimal hotfixes, so I'll reduce the priority here.  Once CI is green again, we can rebase this to use the newer patchelf.

**Comment by mwoehlke-kitware** [comment]
Curious... this seems to work locally, but not in CI, and the cause of the CI failure is anything but obvious...

**Comment by jwnimmer-tri** [comment]
Your local build probably isn't rebased onto #18015.  The #18165 has a hotfix for both auditwheel and my error in the #18015 import-error test case.

**Comment by mwoehlke-kitware** [comment]
Ah, so your changes to #18015 broke CI? ...but I was looking at whatever happened at `[0:37:07.799]`; that might not have failed the build, but it doesn't look "right", either.

**Comment by jwnimmer-tri** [comment]
I can't seem to find that timestamp.  Could you excerpt the error message here to help me out?

**Comment by mwoehlke-kitware** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/86/console
```
[0:37:05.497]  sha256:ecd3060be0a5eef3fc3a316bebc1b73fe56433d32f56e761cf8473216d082972
[0:37:05.497]  pip-drake__test-20221024163813-095e6d50148336a5-focal-py38
[0:37:05.753]  /opt/drake-wheel-test/python/lib/python3.8/site-packages/pydrake/py.typed
[0:37:05.753]  /opt/drake-wheel-test/python/lib/python3.8/site-packages/pydrake/all.pyi
[0:37:06.678]  /opt/drake-wheel-test/python/lib/python3.8/site-packages/pydrake/share/drake
[0:37:06.678]  /opt/drake-wheel-test/python/lib/python3.8/site-packages/pydrake/common/../lib/../share/drake
[0:37:07.239]  drake-0.0.2022.10.24.16.37.48+gitd2a0615f-cp38-cp38-manylinux_2_31_x86_64.whl: 84.92 MiB
[0:37:07.799]  Traceback (most recent call last):
[0:37:07.799]    File "<stdin>", line 1, in <module>
[0:37:07.799]    File "/opt/drake-wheel-test/python/lib/python3.8/site-packages/pydrake/__init__.py", line 41, in <module>
[0:37:07.799]      from . import common
[0:37:07.799]    File "/opt/drake-wheel-test/python/lib/python3.8/site-packages/pydrake/common/__init__.py", line 8, in <module>
[0:37:07.799]      from ._module_py import *
[0:37:07.799]  ImportError: libdrake.so: cannot open shared object file: No such file or directory
[0:37:07.799]  
[0:37:07.799]  Drake failed to load a required library. This could indicate an installation
[0:37:07.799]  problem, or that your system is missing required distro-provided packages.
[0:37:07.799]  Please refer to the installation instructions to ensure that all required
[0:37:07.799]  dependencies are installed.
[0:37:07.799]  
[0:37:07.799]  For Ubuntu 20.04, install these additional libraries:
[0:37:07.799]  
[0:37:07.799]      sudo apt-get install --no-install-recommends \
[0:37:07.799]        libpython3.8 libx11-6 libsm6 libxt6 libglib2.0-0
[0:37:07.799]  
[0:37:07.799]  For Ubuntu 22.04, install these additional libraries:
[0:37:07.799]  
[0:37:07.799]      sudo apt-get install --no-install-recommends \
[0:37:07.799]        libx11-6 libsm6 libglib2.0-0
[0:37:07.799]  
[0:37:07.799]  For macOS, ensure that you're using Homebrew Python (not Apple's system Python).
[0:37:07.799]  
[0:37:07.799]  For more information, please see https://drake.mit.edu/installation.html
[0:37:07.799]  
[0:37:08.054]   done
[0:37:08.054]  [-] Build pip-drake:20221024163813-095e6d50148336a5-focal-py38 ['--ssh', 'default', '--build-arg', 'DRAKE_VERSION=0.0.2022.10.24.16.37.48+gitd2a0615f', '--build-arg', 'PLATFORM=ubuntu:20.04', '--build-arg', 'PYTHON=3.8', '--force-rm']
[0:37:08.054]  [-] Extracting wheel(s) from pip-drake:20221024163813-095e6d50148336a5-focal-py38
```

**Comment by jwnimmer-tri** [comment]
That's the output we see in case the import-error test case fails.  (It was failing due to the grep not matching INSTALLATION.)

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18163)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
:lgtm: both reviews.

**Pull request merged**
