### PR TITLE
Port Quadrotor to SystemScalarConverter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
FYI The Doxygen in #6982 (hopefully merged to master soon) helps explain what's going on here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7005)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jwnimmer-tri** [comment]
+@naveenoid for feature review, please.
+@sammy-tri for platform review, please.

**Comment by sammy-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/quadrotor/quadrotor_plant.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7005#-KtrcvBEypkju5EXMysE:-KtrcvBFCFYbkiwRTYdZ:be87udu) ([raw file](https://github.com/robotlocomotion/drake/blob/fb1e5b3161859d1c247cbe05f06d7e0df6dfa587/drake/examples/quadrotor/quadrotor_plant.h#L62)):*
> ```objc
> 
>  private:
>   template <typename> friend class QuadrotorPlant;
> ```

This seems unusual enough to deserve a comment...   (based on the fact that I can't figure out why it's there)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7005)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/quadrotor/quadrotor_plant.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7005#-KtrcvBEypkju5EXMysE:-KtroEVKZ4WsVQJQFOOA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb1e5b3161859d1c247cbe05f06d7e0df6dfa587/drake/examples/quadrotor/quadrotor_plant.h#L62)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This seems unusual enough to deserve a comment...   (based on the fact that I can't figure out why it's there)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7005)*

**Comment by sammy-tri** [comment]
:lgtm: pending CI issues

---

Reviewed 3 of 7 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7005#-:-Ktry73t9j5_T6a7ZiNh:b1yjwf0)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7005#-:-Kts3N4RR43ZVdzsO3xy:bnfp4nl)*

**Pull request merged**
