### PR TITLE
Do not use pods_use_pkg_config_packages with lcm

### PR DESCRIPTION
**Pull request by jamiesnape**
@mwoehlke-kitware for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3480)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3480#-:-KRoDY0f9lJ4L3say9Um:bnfp4nl)*

**Comment by jamiesnape** [comment]
@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3480#-:-KRoPTkKxbZ1UR8UqALk:bnfp4nl)*

**Pull request merged**
