### PR TITLE
Add resource to FindResourceOrThrow error message.

### PR DESCRIPTION
**Pull request by avalenzu**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7565)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@jwnimmer-tri for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7565#-:-L-cqPDOAGiwWmWgL4tg:b-1tks9q)*

**Comment by jwnimmer-tri** [comment]
:lgtm: both

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/find_resource.cc, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7565#-L-crq9NMc7ocl09y7wW:-L-crq9OCFh2JFgh1tkt:b3ahcyq) ([raw file](https://github.com/robotlocomotion/drake/blob/cea00090bf33701bc2531fea3cbd9f6d98b5308b/drake/common/find_resource.cc#L235)):*
> ```cpp
>   // Nothing found.
>   string error_message = "could not find resource: " + resource_path;
>   return Result::make_error( std::move(resource_path), error_message);
> ```

BTW nit Extra whitespace within `( std::`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7565#-:-L-cs0fHdjk9kcUZ2dqJ:bb6yyy8)*

**Comment by jwnimmer-tri** [comment]
Looks like tests are failing.

**Comment by avalenzu** [comment]
Yeah, I just updated the unit test.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/find_resource.cc, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7565#-L-crq9NMc7ocl09y7wW:-L-d5ntndnrg87gdIMfS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cea00090bf33701bc2531fea3cbd9f6d98b5308b/drake/common/find_resource.cc#L235)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit Extra whitespace within `( std::`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7565#-:-L-d5Y-fTQzPGL_peaRk:b1kirqd)*

**Pull request merged**
