### PR TITLE
multibody: Relocate many MbT method definitions to cc file

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is preparatory work for improving the error messages from these methods.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15078)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri would you like to feature review anything here?  Otherwise, we could just toss it to sole platform review, since it's (mostly) just code shuffle.

The only interesting change was refactoring the `GetJointByName` downcasting to use new helper functions.

**Review by amcastro-tri — COMMENTED** [review]
I trust the cc contents match the previous header contents (I looked through and that does seem the case + unit tests pass). Besides that, everything looks great, thank you @jwnimmer-tri. :lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15078#-:-MaUvs6c2cE1oOL7UxS3:b-oovidf)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Yup, the move was via copy-cut-paste and then a regex to de-indent, so it all should be identical (except for the `GetJointByName` refactor mentioned above).

+@sherm1 for platform review per schedule (tomorrow), please.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15078#-:-MaVYlLJ7LGs0IG0ahqj:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
