### PR TITLE
Remove `--with-doc-only` option from macOS setup scripts

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Also remove the `--without-doc-only` option from macOS setup scripts.

Update the Documentation Generation Instructions to indicate that
documentation generation and preview is supported on Ubuntu only.

Towards #13832

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14350)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14350#-:-MMLyqkv2983pxOs62og:b8qd208)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature review.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14350#-:-MMMEiQL6ibJLs30i0ur:beumc7x)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

___
*[setup/mac/install_prereqs.sh, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14350#-MMME_3pA2N-lRCcpjMg:-MMME_3pA2N-lRCcpjMh:bew095a) ([raw file](https://github.com/robotlocomotion/drake/blob/d5392979a94522c4bc6565c02ea581b1b0e9c179/setup/mac/install_prereqs.sh#L27)):*
> ```Shell
>     # { //doc:gen_sphinx, //bindings/pydrake/doc:gen_sphinx, //doc:doxygen }
>     --without-doc-only)
>       source_distribution_args+=(--without-doc-only)
> ```

nit In support of the deprecation date in the source prereqs, we should retain the `--without-doc-only` case match and args-append here.
___
*[setup/mac/source_distribution/install_prereqs.sh, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14350#-MMMEA7eCGEbX9mAzBYs:-MMMEA7f8NWBpOFzdXYI:bvvh0no) ([raw file](https://github.com/robotlocomotion/drake/blob/3d68391c7ec18f1854027de28e94ca47bd7a7eec/setup/mac/source_distribution/install_prereqs.sh#L10)):*
> ```Shell
> set -euxo pipefail
> 
> with_doc_only=0
> ```

nit Remove this default value also (it's dead code).
___
*[setup/mac/source_distribution/install_prereqs.sh, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14350#-MMMEFe3CTt-cWQNy5QX:-MMMEFe3CTt-cWQNy5QY:bhmt5yl) ([raw file](https://github.com/robotlocomotion/drake/blob/d5392979a94522c4bc6565c02ea581b1b0e9c179/setup/mac/source_distribution/install_prereqs.sh#L31)):*
> ```Shell
>     # { //doc:gen_sphinx, //bindings/pydrake/doc:gen_sphinx, //doc:doxygen }
>     --without-doc-only)
>       echo 'DEPRECATED: The --without-doc-only option is the default and will be deprecated on or after 2021-01-01' >&2
> ```

nit In support of the deprecation date, we should retain the `--without-doc-only` case match and echo statement here.  We should still nix the `=0` assignment, though.

**Review by BetsyMcPhail — COMMENTED** [review]
+@sammy-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14350#-:-MMRvuXz-bZzblc_Jax1:bq11ftp)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14350)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14350)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14350#-:-MMS24ZWBeiO_hzTjdRs:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
