### PR TITLE
Replaces pointer versions of get_integrator() and get_mutable_integrator()...

### PR DESCRIPTION
**Pull request by edrumwri**
...in Simulator to make the interface consistent with the rest of the API. This has been bugging me.

Needs a unit test but comments are welcome.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11197)

### CODE REVIEW

**Comment by sherm1** [comment]
It's worth pointing out for discussion that there is no way to deprecate the old signature since the revised one differs only by the return type.

**Comment by jwnimmer-tri** [comment]
> ... but can't be done with deprecation.

I think you could add a deprecation shim if you really wanted to, by defining `result->set_...` and `result.set_...` to both work using operator overloading.  So your case is "It's not worth it" not "It's not possible".

Anzu has three uses (to control step size and target accuracy).  Dairlib has two uses but they are commented out.  So I can buy "not worth it" from a very quick look -- though I will defer to others to make the call.

**Comment by sherm1** [comment]
> I think you could add a deprecation shim if you really wanted to, by defining result->set_... and result.set_... to both work using operator overloading. 

Clever! Definitely worth considering a deprecated `operator->()`, though "not worth it" might still be the right answer.

**Comment by jwnimmer-tri** [comment]
> ... shim would temporarily pollute the public API.

FYI My guess was that it could be a method on `IntegratorBase` (not a new return type), which we could exclude from Doxygen.

**Comment by EricCousineau-TRI** [comment]
Ah, yeah, that'd work. In that case, I've demoted my "not worth it" to "maybe worth it" - but still in the area of ambivalence given the current use cases.

**Pull request merged**
