### PR TITLE
Renamed "robotnum" to be "model_instance_id".

### PR DESCRIPTION
**Pull request by liangfok**
Per discussion with @sherm1, @amcastro-tri, and @david-german-tri yesterday. This is the second of a long sequence of PRs with the end goal of enabling simulations that involve more than one model instance. It builds upon #3037.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3043)

### CODE REVIEW

**Comment by liangfok** [comment]
I'm labeling this "Do not review" until after #3037 is merged.

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

**Comment by liangfok** [comment]
+@amcastro-tri for feature review (you're the only non-platform reviewer who attended yesterday's meeting)
+@sherm1 for platform review (it's not Monday but you have direct knowledge of yesterday's meeting)

@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-:-KOLbLdwzDLxJv9BiwPV:1805021823)*

**Comment by sherm1** [comment]
Platform: a few small comments.

---

Reviewed 5 of 9 files at r2, 1 of 6 files at r3, 2 of 6 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 832 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLtM9GqwAEWSOrzLnK:-KOLtM9GqwAEWSOrzLnL:640322443) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/RigidBodyTree.cpp#L832)):*
> ```cpp
>       int ncols_joint =
>           in_terms_of_qdot ? joint.getNumPositions() : joint.getNumVelocities();
>       if (isBodyPartOfRobot(body, model_instance_id)) {
> ```

BTW, make this `is_body_part_of_model_instance()`?

---

*[drake/systems/plants/RigidBodyTree.cpp, line 925 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLtbCwJTaYkMYWg3B2:-KOLtbCwJTaYkMYWg3B3:475988251) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/RigidBodyTree.cpp#L925)):*
> ```cpp
> }
> 
> bool RigidBodyTree::isBodyPartOfRobot(const RigidBody& body,
> ```

BTW, `is_body_part_of_model_instance()`?

---

*[drake/systems/plants/RigidBodyTree.h, line 193 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLtxOpBAqMtqE3pG3y:-KOLtxOpBAqMtqE3pG3z:-1308916975) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/RigidBodyTree.h#L193)):*
> ```objc
>   Eigen::Matrix<Scalar, drake::kSpaceDimension, 1> centerOfMass(
>       KinematicsCache<Scalar>& cache,
>       const std::set<int>& model_instance_id = default_model_instance_id_set)
> ```

Here and below these set arguments should be `model_instance_ids` (plural) to avoid confusion with the similarly-named `int`. (Or could be `model_instance_id_set`.)

---

*[drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp, line 51 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLuojxhO3EZdPhJ3-4:-KOLuojxhO3EZdPhJ3-5:-1384120889) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp#L51)):*
> ```cpp
>       RigidBodyTree* model = (RigidBodyTree*)getDrakeMexPointer(prhs[1]);
>       Vector2d tspan;
>       int* model_instance_id;
> ```

BTW, I think it is confusing to use this name. How about `model_instance_ids` since it is an array of them?

Also, should initialize to nullptr.

---

*[drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp, line 538 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLvE1XMPDtojeqaES0:-KOLvE1XMPDtojeqaES1:100463066) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp#L538)):*
> ```cpp
>       WorldCoMConstraint* cnst = nullptr;
>       Vector2d tspan;
>       int* model_instance_id;
> ```

BTW, model_instance_ids (plural) and initialize.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.cpp, line 92 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLvSY8iI9WJc8AfwAW:-KOLvSY8iI9WJc8AfwAX:-786998376) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/RigidBodyConstraint.cpp#L92)):*
> ```cpp
>     int nq = getRobotPointer()->number_of_positions();
>     dc.resize(2, nq + num_pts_);
>     auto com = getRobotPointer()->centerOfMass(cache, m_model_instance_id_set_);
> ```

BTW, no need for both the "m_" prefix and the "_" suffix. (No need to change in this PR.)

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 144 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLvrHNaa_jYysG4k5I:-KOLvrHNaa_jYysG4k5J:1868195311) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/RigidBodyConstraint.h#L144)):*
> ```objc
>  private:
>   static const std::set<int> defaultRobotNumSet;
>   std::set<int> m_model_instance_id_set_;
> ```

BTW, I'm assuming the "m_" here is the usual member convention, but the trailing "_" is our convention so is sufficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-:-KOLwCXZlgOyRZHkEikr:-1235125476)*

**Comment by liangfok** [comment]
@sherm1 I addressed your comments PTAL. Thanks.

@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 832 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLtM9GqwAEWSOrzLnK:-KOM1Ud3nuCVhnlK4t61:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/RigidBodyTree.cpp#L832)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, make this `is_body_part_of_model_instance()`?
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 925 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLtbCwJTaYkMYWg3B2:-KOLz7TX5R2DxOMVNuWC:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/RigidBodyTree.cpp#L925)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `is_body_part_of_model_instance()`?
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 193 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLtxOpBAqMtqE3pG3y:-KOLzMoNKLDsezHpnebS:1070069785) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/RigidBodyTree.h#L193)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Here and below these set arguments should be `model_instance_ids` (plural) to avoid confusion with the similarly-named `int`. (Or could be `model_instance_id_set`.)
</details>
Done. I decided to use `model_instance_id_set` since it's easier to see `_set` relative to just `s`.

---

*[drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp, line 51 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLuojxhO3EZdPhJ3-4:-KOM0_-02UOiJpp0VoSH:-1778035393) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp#L51)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I think it is confusing to use this name. How about `model_instance_ids` since it is an array of them?
> 
> Also, should initialize to nullptr.
</details>
Done. I used `model_instance_ids`.

---

*[drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp, line 538 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLvE1XMPDtojeqaES0:-KOM0kbs0jX6LmgnatRW:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp#L538)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, model_instance_ids (plural) and initialize.
</details>
Done.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.cpp, line 92 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLvSY8iI9WJc8AfwAW:-KOM1HtXIJGfWunZMCAP:62138528) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/RigidBodyConstraint.cpp#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, no need for both the "m_" prefix and the "_" suffix. (No need to change in this PR.)
</details>
OK. #3067.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 144 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLvrHNaa_jYysG4k5I:-KOM1Lv_zIpeWaH3-utB:-1814199712) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/RigidBodyConstraint.h#L144)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I'm assuming the "m_" here is the usual member convention, but the trailing "_" is our convention so is sufficient.
</details>
I think you're right (I'm guessing b/c I'm not the original author). #3067.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-:-KOM1VtHnbFIGaMZiozA:1248819526)*

**Comment by sherm1** [comment]
:lgtm: -- one BTW comment.

---

Reviewed 3 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp, line 538 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLvE1XMPDtojeqaES0:-KOMOifP8TjwehNw46sf:1949225788) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp#L538)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
BTW, did you want to initialize this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-:-KOMP2QzMTNZLRx_U31f:1865262933)*

**Comment by liangfok** [comment]
Thanks. Just waiting on CI now.

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp, line 538 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOLvE1XMPDtojeqaES0:-KOMPnhAKM6NavkRayYP:734464133) ([raw file](https://github.com/robotlocomotion/drake/blob/86913b6388fe80afd25969e0f77d1bd091a6e541/drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp#L538)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, did you want to initialize this?
</details>
Oops! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-:-KOMPphwqlc1ouK6RcAA:401150584)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 6 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[drake/systems/plants/RigidBodyTree.h, line 174 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOPyJhDfx4XsunSLvnz:-KOPyJhDfx4XsunSLvo-:b9yjanz) ([raw file](https://github.com/robotlocomotion/drake/blob/2faf1ceac6086c614848b4b9614c32f027286064/drake/systems/plants/RigidBodyTree.h#L174)):*
> ```objc
>                     bool compute_JdotV = false) const;
> 
>   bool is_body_part_of_model_instance(const RigidBody& body,
> ```

Since you are changing this API. Why not to call it by what it actually does? like `is_body_part_of_models_set`? (I opted here not for `is_body_part_of_model_instances_set` to shorten the methods name though.

---

*[drake/systems/plants/RigidBodyTree.h, line 178 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOPyq4dvg6nSkRPWqY8:-KOPyq4dvg6nSkRPWqY9:b6h6it1) ([raw file](https://github.com/robotlocomotion/drake/blob/2faf1ceac6086c614848b4b9614c32f027286064/drake/systems/plants/RigidBodyTree.h#L178)):*
> ```objc
> 
>   /**
>    * Computes the total mass of a set of models in this rigid body tree.
> ```

I would paraphrase to "Computes the total combined mass of a set of model instances."

---

*[drake/systems/plants/RigidBodyTree.h, line 184 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOPz2QyCDqVcmmY07dm:-KOPz2QyCDqVcmmY07dn:bnjljb8) ([raw file](https://github.com/robotlocomotion/drake/blob/2faf1ceac6086c614848b4b9614c32f027286064/drake/systems/plants/RigidBodyTree.h#L184)):*
> ```objc
>    * returned value.
>    *
>    * @returns The total mass of the model instances specified by
> ```

`@returns the total combined mass including the model instances in @p model_instance_id_set`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 174 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOPyJhDfx4XsunSLvnz:-KOQ9LAPx1EtvSD9D7pS:b-8evh29) ([raw file](https://github.com/robotlocomotion/drake/blob/2faf1ceac6086c614848b4b9614c32f027286064/drake/systems/plants/RigidBodyTree.h#L174)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Since you are changing this API. Why not to call it by what it actually does? like `is_body_part_of_models_set`? (I opted here not for `is_body_part_of_model_instances_set` to shorten the methods name though.
</details>
Done. I changed the name to be `is_part_of_model_instances()` and added Doxygen comments.

---

*[drake/systems/plants/RigidBodyTree.h, line 178 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOPyq4dvg6nSkRPWqY8:-KOQ8Mjm6cylY5BqIYlj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2faf1ceac6086c614848b4b9614c32f027286064/drake/systems/plants/RigidBodyTree.h#L178)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I would paraphrase to "Computes the total combined mass of a set of model instances."
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 184 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOPz2QyCDqVcmmY07dm:-KOQ8WwwMEd4ruNvqQMZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2faf1ceac6086c614848b4b9614c32f027286064/drake/systems/plants/RigidBodyTree.h#L184)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> `@returns the total combined mass including the model instances in @p model_instance_id_set`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-:-KOQDuR2ns74fFbeLCZx:bblnx7i)*

**Comment by amcastro-tri** [comment]
A small comment. Otherwise :lgtm: 

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 184 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOPz2QyCDqVcmmY07dm:-KOQID0HUNbr7EYuh54M:brxkkxm) ([raw file](https://github.com/robotlocomotion/drake/blob/2faf1ceac6086c614848b4b9614c32f027286064/drake/systems/plants/RigidBodyTree.h#L184)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
My bad on that one. The sentence following `@returns` should be capitalized so that it gets properly rendered in Doxygen. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-:-KOQIRvAa-pk48hMVtnI:b-1doch8)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 184 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-KOPz2QyCDqVcmmY07dm:-KOQJhrRFeDOIhAShtLD:b-2tlov9) ([raw file](https://github.com/robotlocomotion/drake/blob/2faf1ceac6086c614848b4b9614c32f027286064/drake/systems/plants/RigidBodyTree.h#L184)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> My bad on that one. The sentence following `@returns` should be capitalized so that it gets properly rendered in Doxygen. 
</details>
Done. Here's how the rendered Doxygen looks like:



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-:-KOQJoC4Psw3JoVtVUWZ:b-1edt96)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7, 1 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3043#-:-KOQSRn4rDRRHzeqnwTj:bnfp4nl)*

**Pull request merged**
