### PR TITLE
Install .pyi files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16987.

This reverts commit 9a0f31a706ffa4b8d77846d7629f0616b55ecc97 (#17746), effectively re-applying commit a61a1846ff3b0e49e66f3f92beac29121adb32dc (#17709).

The plan is to squash this on merge; the two commits are for review purposes only.

---

Add rules to generate (as part of the build) and install type stubs for pydrake. Modify wheel build to include these as well.

Note that this makes numpy and matplotlib build-time dependencies. (Previously they were only required to test/run pydrake.)

Note also that there are issues remaining with the .pyi's; in particular, they are completely unusable by mypy.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18074)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews per schedule, please.

Note that r1 contains an unrevert so hopefully can be mostly glossed over.  The r2 is the new fixes, just a few list-of-modules tweaks.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18074#-:-NE6sBDrArHlILvqP-E0:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18074)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
