### PR TITLE
Add drake "collision_filter_group" tags into sdf parsing

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
1. Refactor the parsing logic out of urdf into common to be re-used by sdf parser. Note: code was merely moved from urdf_parser.* into parser_common.h.
2. Add to sdf parser.
3. Extend unit tests
   a. Simplify original tests into a single, more compact urdf (removing an unnecessary URDF and simplifying the other).
   b. Create the sdf version.
4. Correct doxygen formatting errors (xml was getting lost).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8232)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@rcory for feature review, please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-:-L6d1_6Add3UnEacHij4:b-yvq8xq)*

**Comment by rcory** [comment]
Reviewed 6 of 10 files at r1.
Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/collision/collision_filter_doxygen.h, line 243 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-L6qxohe5ZJaf8rF-vrM:-L6qxohe5ZJaf8rF-vrN:blcrmf7) ([raw file](https://github.com/robotlocomotion/drake/blob/43221881f935278132cd5105ae93c1e7740567a8/multibody/collision/collision_filter_doxygen.h#L243)):*
> ```objc
> two members, `body1` and `body2` (although it could have any number of links).
> This is short-hand for communicating that the _collision elements_ of `body1`
> and `body2` belong to `group1`. Furthermore, `group1` ignores two groups:
> ```

BTW,  perhaps add a line explaining that if one wants to ignore self collisions within a group, one must explicitly define that behavior by adding the group's own name as an `ignored_collision_filter_group`? It may not be immediately obvious at first glance.

---

*[multibody/collision/test/filter_groups_in_file.sdf, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-L6r-hDLCdk1uHckqb45:-L6r-hDLCdk1uHckqb46:b342iew) ([raw file](https://github.com/robotlocomotion/drake/blob/43221881f935278132cd5105ae93c1e7740567a8/multibody/collision/test/filter_groups_in_file.sdf#L1)):*
> ```
>  This.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8232)*

**Comment by SeanCurtis-TRI** [comment]
Comments addressed.

---

Review status: 3 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/collision/collision_filter_doxygen.h, line 243 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-L6qxohe5ZJaf8rF-vrM:-L6rEd_B47uZNL2bHW95:bkmbjku) ([raw file](https://github.com/robotlocomotion/drake/blob/43221881f935278132cd5105ae93c1e7740567a8/multibody/collision/collision_filter_doxygen.h#L243)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

BTW,  perhaps add a line explaining that if one wants to ignore self collisions within a group, one must explicitly define that behavior by adding the group's own name as an `ignored_collision_filter_group`? It may not be immediately obvious at first glance.
</blockquote></details>

Done -- furthermore, I tweaked the documentation so that the user-facing API is more up front and center.

---

*[multibody/collision/test/filter_groups_in_file.sdf, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-L6r-hDLCdk1uHckqb45:-L6rElqLc1huhdoWeils:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/43221881f935278132cd5105ae93c1e7740567a8/multibody/collision/test/filter_groups_in_file.sdf#L1)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Reviewable tells me that `collision_filter_group_test_multi_ignore.urdf` has been deleted. Did you mean `filter_groups_in_file.urdf`?
</blockquote></details>

Done

---

*[multibody/collision/test/filter_groups_in_file.urdf, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-L6r3oOOTfA2AMSYxrJp:-L6rEquD-sDUN0TiAukc:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/43221881f935278132cd5105ae93c1e7740567a8/multibody/collision/test/filter_groups_in_file.urdf#L18)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Is this correct? It seems there are two variants, but they test the same aspects of collision filter groups. They merely differ in the type of file they define (i.e., `.sdf` vs `.urdf`).
</blockquote></details>

Done

---

*[multibody/collision/test/filter_groups_in_file.urdf, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-L6r2l6_6mWDJRFogJGn:-L6rF3_uh3X0xNgdn-5k:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/43221881f935278132cd5105ae93c1e7740567a8/multibody/collision/test/filter_groups_in_file.urdf#L102)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

BTW, typo. THis --> This.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-:-L6rFAfgFysaMLyriPbd:bel95ya)*

**Comment by rcory** [comment]
:lgtm: +@sammy-tri for platform review please.

---

Reviewed 3 of 3 files at r2.
Review status: 6 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-:-L6sAWhdLjoyEiESqSyp:b-t6qajt)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8232#-:-L6vzfH0TjHciLiAsBtN:bnfp4nl)*

**Pull request merged**
