### PR TITLE
[C-IRIS] search many separating planes in parallel.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18474)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18474#-:-NJTcK4O2nBsKgF7KJfX:b-kengf8)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
One major comment about class design. It seems that in order to get certification, the user will need to be intimately knowledgeable about the steps needed to generate the program. On the other hand, I feel like we should be striving for a class design that enables a user to say:
```
CspaceFreePolytope certifier = spaceFreePolytope(plant, scene_graph, plane_order)
std::vector<std::optional<CspaceFreePolytope::SeparationCertificateResult>> result = certifier.FindSeparationCertificateGivenPolytope(C, d, options);
```
This would require moving many things into private members of the certifier object.

In this case, I would also consider renaming the class `CspaceFreePolytope` to `CspaceFreePolytopeCertifier`, as the former seems like it would contain the polytope + certificate, while the later is clearly an object for performing the certification.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18474#-:-NJb0dC66wcQIPxEuPZT:b94q4ad)* status: 14 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJaqD6K5WDxmm6SS0ml:-NJaqD6K5WDxmm6SS0mm:b209nw0) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.h#L107)):*
> ```objc
>    @param filtered_collision_pairs
>    @param search_separating_margin If set to true, then when we search for the
>    separating planes, we will also consider to explicitly search for the
> ```

I am not sure I understand this comment. If this is set to true, does this mean we include the margin in objective? If so, consider simplifying the comment to
`If set to true, we will attempt to maximize the margin of the separating planes`
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 223 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJaqiSY6QRSt2Ccl8Se:-NJaqiSY6QRSt2Ccl8Sf:blysipa) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.h#L223)):*
> ```objc
>     // num_threads specifies how many threads we run in parallel. If num_threads
>     // <=0, then we use all available threads on the computer.
>     int num_threads;
> ```

Do we want to provide a default value for this? Perhaps 1?
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 344 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJarFIm72fXM9Qf8ckK:-NJarFIm72fXM9Qf8ckL:ba5mays) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.h#L344)):*
> ```objc
>    the separation for this pair, then certificates[i] contains std::nullopt.
>    Note that when we run this function in parallel, we will terminate all the
>    remaining certification that have been launched, so certificates[i] =
> ```

nit: "we will terminate all the remaining certification **programs**..."
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 349 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJarZuJCMeNt8cxGsVa:-NJarZuJCMeNt8cxGsVb:bv9mu4v) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.h#L349)):*
> ```objc
>    to find the certificate for another pair and haven't attempted to find the
>    certificate for this pair.
>    */
> ```

Would it be worth adding `terminate_early` as an option `FindSeparationCertificateGivenPolytopeOptions`, where `true` would imply exittng all the other certification programs if one fails to certify, but `false` still certifies those bodies we can certify?
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 532 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJb03TrB7kIJXXL0Sbn:-NJb03TrB7kIJXXL0Sbo:blkzzjg) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L532)):*
> ```cpp
> std::unordered_map<SortedPair<multibody::BodyIndex>,
>                    VectorX<symbolic::Monomial>>
> CspaceFreePolytope::CalcMonomialBasis(
> ```

Can we call this function from the constructor? It seems a little much to ask the user to have to call this manually before certifying?
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 767 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJaxcyaBLO0mNcsjCfw:-NJaxcyaBLO0mNcsjCfx:b-gux7tc) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L767)):*
> ```cpp
>     const Eigen::Ref<const Eigen::VectorXd>& d,
>     const VectorX<symbolic::Polynomial>& s_minus_s_lower,
>     const VectorX<symbolic::Polynomial>& s_upper_minus_s,
> ```

`s_minus_s_lower` and `s_lower` (resp. upper) seems to show up in a lot of places throughout the function calls in this class which seems rather unnecessary given that this should be fairly static. I would expect that this comes directly from the plant for which CspaceFreePolytope is constructed, and therefore I believe we should be able to just make `s_minus_s_lower` on construction and not have to carry it around in every function call. 

At construction the user could be given `s_lower` being type `std::optional` and therefore have the option to either get its value from the plant directly or specify one if they so choose



_Code quote:_
```cpp
    const VectorX<symbolic::Polynomial>& s_minus_s_lower,
    const VectorX<symbolic::Polynomial>& s_upper_minus_s,
    const Eigen::VectorXd& s_lower, const Eigen::VectorXd& s_upper,
```
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 805 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJayp1W4K2-oWLz8vXL:-NJayp1W4K2-oWLz8vXM:b-lwdffh) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L805)):*
> ```cpp
>           certificate.prog->AddBoundingBoxConstraint(
>               0, kInf, plane_geometries[plane_count].separating_margin.value());
>         }
> ```

I think this should move into `ConstructPlaneSearchProgram`



_Code quote:_
```cpp
        if (plane_geometries[plane_count].separating_margin.has_value()) {
          certificate.prog->AddLinearCost(
              -Vector1d(1),
              Vector1<symbolic::Variable>(
                  plane_geometries[plane_count].separating_margin.value()));
          certificate.prog->AddBoundingBoxConstraint(
              0, kInf, plane_geometries[plane_count].separating_margin.value());
        }
```
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 829 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJazXhHBf95ymu3LaTv:-NJazXhHBf95ymu3LaTw:b-sen5c0) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L829)):*
> ```cpp
>           : static_cast<int>(std::thread::hardware_concurrency());
>   // We implement the "thread pool" idea here, by following
>   // MonteCarloSimulationParallel class. This implementation doesn't use openMP
> ```

nit: grammar "doesn't use **the** openMP"
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 845 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJazejv2QgNELcoidnN:-NJazejw6BlBmTZV0KNF:b-oxx4tc) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L845)):*
> ```cpp
>       if (IsFutureReady(*operation)) {
>         // This call to future.get() is necessary to propagate any exception
>         // throw during SOS setup/solve.
> ```

nit grammar "throw" -> "thrown"
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 866 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJazrSJ0Xvoi9e5-2KQ:-NJazrSJ0Xvoi9e5-2KR:b-h7zpz5) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L866)):*
> ```cpp
>       active_operations.emplace_back(std::async(
>           std::launch::async, std::move(solve_small_sos), sos_dispatched));
>       drake::log()->debug("SOS {} dispatched", sos_dispatched);
> ```

Can we change this to `debug("SOS {}/{} dispatched", sos_dispatched, plane_geometries.size())` to give a better idea of time to go?



_Code quote:_
```cpp
SOS {} dispatched
```
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 879 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJb-7TV6LIxpNeY4jlK:-NJb-7TV6LIxpNeY4jlL:b-17argj) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L879)):*
> ```cpp
>                   })) {
>     if (options.verbose) {
>       drake::log()->info("Found Lagrangian multiplier and separating planes");
> ```

nit grammar "multiplier"->"multipliers"
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 901 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJb-Iap4t00mAuoqrl_:-NJb-IaqB99DajE2FVDw:b-17argj) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L901)):*
> ```cpp
> 
>       drake::log()->warn(fmt::format(
>           "Cannot find Lagrangian multiplier and separating planes for \n{}",
> ```

nit grammar "multiplier"->"multipliers"
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 794 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJb-brR5b88G4Lk3JHx:-NJb-brR5b88G4Lk3JHy:bigbz94) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L794)):*
> ```cpp
>   const auto plane_geometries = tester.cspace_free_polytope().GenerateRationals(
>       q_star, filtered_collision_pairs, true /* search_separating_plane */);
>   // This/ C-space polytope is collision free.
> ```

Is the backslash after `This` intentional?
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJb0NuX-Abdd9F4tOIX:-NJb0NuX-Abdd9F4tOIY:buhkjol) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L820)):*
> ```cpp
>                 &s_lower_redundant_indices, &s_upper_redundant_indices);
>   const Eigen::Vector3d s_lower =
>       tester.cspace_free_polytope().rational_forward_kin().ComputeSValue(
> ```

All of this seems like a lot to ask the user to do before being able to certify. See comment at beginning of review



_Code quote:_
```cpp
  VectorX<symbolic::Polynomial> d_minus_Cs;
  VectorX<symbolic::Polynomial> s_minus_s_lower;
  VectorX<symbolic::Polynomial> s_upper_minus_s;
  std::unordered_set<int> C_redundant_indices;
  std::unordered_set<int> s_lower_redundant_indices;
  std::unordered_set<int> s_upper_redundant_indices;
  SetupPolytope(tester, C, d, q_star, &d_minus_Cs, &s_minus_s_lower,
                &s_upper_minus_s, &C_redundant_indices,
                &s_lower_redundant_indices, &s_upper_redundant_indices);
  const Eigen::Vector3d s_lower =
      tester.cspace_free_polytope().rational_forward_kin().ComputeSValue(
          plant_->GetPositionLowerLimits(), q_star);
  const Eigen::Vector3d s_upper =
      tester.cspace_free_polytope().rational_forward_kin().ComputeSValue(
          plant_->GetPositionUpperLimits(), q_star);

  const auto map_body_to_monomial_basis =
      tester.CalcMonomialBasis(plane_geometries);
```

**Review by hongkai-dai — COMMENTED** [review]
Currently the user cannot compute the certificate. As you mentioned, all the functions needed for computing the certificate is private function of `CspaceFreePolytope`. Later I will add a public function that calls these private function in the right order, similar to the code
```cc
CspaceFreePolytope certifier = spaceFreePolytope(plant, scene_graph, plane_order)
std::vector<std::optional<CspaceFreePolytope::SeparationCertificateResult>> result = certifier.FindSeparationCertificateGivenPolytope(q_star, filtered_collision_pairs, C, d, options);
```

> In this case, I would also consider renaming the class CspaceFreePolytope to CspaceFreePolytopeCertifier, as the former seems like it would contain the polytope + certificate, while the later is clearly an object for performing the certification.

I sort of prefer the current name, as I also plan to add searching for the polytope `C*s<=d` as a function in this `CspaceFreePolytope` class, and add the bilinear alternation method to this class. So my intention is to make `CspaceFreePolytope` to contain both the polytope + certificate.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18474#-:-NJbt4n-A_u5I0NWl_k7:b-nopz2z)* status: 9 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJaqD6K5WDxmm6SS0ml:-NJbuNdh0Io_xbHAy4FZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.h#L107)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I am not sure I understand this comment. If this is set to true, does this mean we include the margin in objective? If so, consider simplifying the comment to
`If set to true, we will attempt to maximize the margin of the separating planes`
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 223 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJaqiSY6QRSt2Ccl8Se:-NJbuQsK7gEHaALvy1Cy:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.h#L223)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Do we want to provide a default value for this? Perhaps 1?
</blockquote></details>

Done. Good call.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 349 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJarZuJCMeNt8cxGsVa:-NJbw38r98ueuyCl1Nnc:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.h#L349)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Would it be worth adding `terminate_early` as an option `FindSeparationCertificateGivenPolytopeOptions`, where `true` would imply exittng all the other certification programs if one fails to certify, but `false` still certifies those bodies we can certify?
</blockquote></details>

Done. Good call.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 532 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJb03TrB7kIJXXL0Sbn:-NJbznDw8NQGgLm2Antf:b6ri8cy) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L532)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can we call this function from the constructor? It seems a little much to ask the user to have to call this manually before certifying?
</blockquote></details>

Currently we also generate the monomial basis for the pair (expressed_body, collision_geometry_body1) and (expressed_body, collision_geometry_body2), if the pair (collision_geometry1, collision_geometry2) is not contained in the collision filter. But the collision filter is not passed in the CspaceFreePolytope constructor, it is only passed in `CspaceFreePolytope::GenerateRationals()`. Hence I can't call this function `CalcMonomialBasis`.

I tried to restructure the code such that in the CspaceFreePolytope constructor it just generates the monomial basis for any pair of collision geometries, but that code restructure requires changing a lot of code, so I stopped the restructuring.

The user don't have to call this function. This function is a private function and the user won't be able to call it. Later I will provide a public function that wraps generating `plane_geometries`, computing monomial basis, construct program and then solve the program. The user won't need to worry about these private functions.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 767 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJaxcyaBLO0mNcsjCfw:-NJc0jYj5TspbZIYmMTG:bb3iapg) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L767)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

`s_minus_s_lower` and `s_lower` (resp. upper) seems to show up in a lot of places throughout the function calls in this class which seems rather unnecessary given that this should be fairly static. I would expect that this comes directly from the plant for which CspaceFreePolytope is constructed, and therefore I believe we should be able to just make `s_minus_s_lower` on construction and not have to carry it around in every function call. 

At construction the user could be given `s_lower` being type `std::optional` and therefore have the option to either get its value from the plant directly or specify one if they so choose
</blockquote></details>

Done.

Computing `s_minus_s_lower` and `s_upper_minus_s` requires knowing s_lower and s_upper, which depends on `q_star`. Currently the constructor doesn't take q_star as an input. Hence I changed the constructor to take in `q_star` as the input argument.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 805 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJayp1W4K2-oWLz8vXL:-NJcASc62znzBMK-K0ip:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L805)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I think this should move into `ConstructPlaneSearchProgram`
</blockquote></details>

Done. Good call.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 866 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJazrSJ0Xvoi9e5-2KQ:-NJcAlzP1xzk2QShVNmN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L866)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can we change this to `debug("SOS {}/{} dispatched", sos_dispatched, plane_geometries.size())` to give a better idea of time to go?
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 794 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJb-brR5b88G4Lk3JHx:-NJcB57N1PFPFOHegX8v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L794)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Is the backslash after `This` intentional?
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJb0NuX-Abdd9F4tOIX:-NJcB8Lk5c1DR50mOXc9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L820)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

All of this seems like a lot to ask the user to do before being able to certify. See comment at beginning of review
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
I see and understand better now. Thank you for that explanation.
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18474#-:-NJcIkcl-V1eeDvJauys:b-gllklk)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 532 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18474#-NJb03TrB7kIJXXL0Sbn:-NJcHSz71xZMGrejSoUh:b2353sn) ([raw file](https://github.com/robotlocomotion/drake/blob/a8d55b0a2c463ecae8160b6836c1387c1deb06f5/geometry/optimization/dev/cspace_free_polytope.cc#L532)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Currently we also generate the monomial basis for the pair (expressed_body, collision_geometry_body1) and (expressed_body, collision_geometry_body2), if the pair (collision_geometry1, collision_geometry2) is not contained in the collision filter. But the collision filter is not passed in the CspaceFreePolytope constructor, it is only passed in `CspaceFreePolytope::GenerateRationals()`. Hence I can't call this function `CalcMonomialBasis`.

I tried to restructure the code such that in the CspaceFreePolytope constructor it just generates the monomial basis for any pair of collision geometries, but that code restructure requires changing a lot of code, so I stopped the restructuring.

The user don't have to call this function. This function is a private function and the user won't be able to call it. Later I will provide a public function that wraps generating `plane_geometries`, computing monomial basis, construct program and then solve the program. The user won't need to worry about these private functions.
</blockquote></details>

Ahh yes the use of the collision filter would make this tricky. Good call keeping it this way then.

**Pull request merged**
