### PR TITLE
Call drake_setup_fortran() at superbuild level only

### PR DESCRIPTION
**Pull request by jamiesnape**
Drake itself does not contain Fortran code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4244)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4244#-:-KXHNKlDV_LGS2E91Ped:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by jwnimmer-tri** [comment]
This is at the border of what I could probably LGTM while relying only on CI, but I'm going to play it safe and let David test it locally on his boxen, rather than break something over the holidays.
-@jwnimmer-tri +@david-german-tri for platform.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4244#-:-KXHT8ywMdZlPOxlvE_j:b-9cbbjm)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
"Priority: High" due to mention in other high-priority issue.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4244#-:-KXfYX8De0pCc6irb0TA:bnfp4nl)*

**Pull request merged**
