### PR TITLE
Turn NLopt support back on for apple, updating revision to include upstream fix

### LINKED ISSUE #2019: NLopt should be enabled on OSX
While getting #1962 integrated, NLopt had to be disabled on apple builds, as it was working in the travis build and failing on drake005.  Once drake005 is out of the picture, retest under jenkins and re-enable (or fix the build).

### PR DESCRIPTION
**Pull request by sammy-tri**
NLopt has integrated my PR.  This fixes #2019.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2086)

### CODE REVIEW

**Comment by sammy-tri** [comment]
Waiting for drake005 to pass before actually trying to merge.

**Comment by sammy-tri** [comment]
Blocked on #2088, since drake005 is the only reproduction secnario in CI for the issue in  #2019.

**Comment by RussTedrake** [comment]
i've pushed this back onto the build queue for drake005, too.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2086#-:-KFK46_Ua0xWnFjXKo_O:1417088721)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Jenkins 864 (the retest) failed one test on linux_matlab, but passed on the original build of that same commit (Jenkins 861).  Thus, I'm going to merge even with the CI red.

**Pull request merged**
