### PR TITLE
[wheel] Improve usability for local development

### LINKED ISSUE #18934: gen/environment.bazelrc infects manylinux wheel builds
For a developer running a wheel build, their local `drake/gen/environment.bazelrc` file is copied into the Dockerfile when building the wheel.  This is bad!  We want the wheel build to be hermetic inside of Docker, not change depending on the platform we're running Docker _on_.  When creating the source tarball, the file needs to have the contents `import %workspace%/tools/ubuntu-focal.bazelrc` instead of whatever the user happens to be running locally.

We should also double-check that `drake/user.bazelrc` isn't making it through.  For that one, we should just omit the file (not replace it).

(Note that in contrast, for macOS wheels we _do_ need to keep the user's `environment.bazelrc`, because we are not containerized.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #18934.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18999)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware for feature review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
Sorry for the delay, somehow this got overlooked...

While you're at it, maybe you could fix:
```
$ flake8 main.py
main.py:7:1: F401 'drake.tools.wheel.wheel_builder.common.die' imported but unused
```

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-:-NR3VrUb3VBCB3vUZiHQ:bw7yjz8)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`tools/wheel/wheel_builder/common.py` line 109 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3VyOZ0aUikg7PHumN:-NR3VyOZ0aUikg7PHumO:b-l49154) ([raw file](https://github.com/RobotLocomotion/drake/blob/fac839efa389ac66a83a38fba41d6835f2d73450/tools/wheel/wheel_builder/common.py#L109)):*
> ```Python
>         help='directory into which to extract wheels (default: %(default)r)')
>     parser.add_argument(
>         '-n', '--no-extract', dest='extract', action='store_false',
> ```

What is the benefit of removing `-n`? Besides being a common spelling for "dry run", given that `--no-extract` implies `--no-test`, the argument for confusion doesn't seem very compelling.

"It's dangerous" is a poor argument. Since no artifacts are produced, no one is going to accidentally do anything with the non-existent, untested artifacts.
___
*[`tools/wheel/wheel_builder/common.py` line 116 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3WFXY8CjDA5rvY15q:-NR3WFXY8CjDA5rvY15r:b-snwylm) ([raw file](https://github.com/RobotLocomotion/drake/blob/3de7cd0f4eb5a4c0293785b0dd931ce1e232af25/tools/wheel/wheel_builder/common.py#L116)):*
> ```Python
>     parser.add_argument(
>         '-t', dest='_', action='store_true',
>         help='ignored for backwards compatibility')
> ```

Is there really significant value in preserving this? If it's only for CI compatibility, maybe there should be a TODO to remove it?
___
*[`tools/wheel/wheel_builder/common.py` line 141 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3Wm6l1stf8HdFwvyB:-NR3Wm6l1stf8HdFwvyC:bkt2dhk) ([raw file](https://github.com/RobotLocomotion/drake/blob/3de7cd0f4eb5a4c0293785b0dd931ce1e232af25/tools/wheel/wheel_builder/common.py#L141)):*
> ```Python
> 
>     if platform is not None:
>         returncode = platform.build(options)
> ```

```
$ flake8 common.py 
common.py:141:9: F841 local variable 'returncode' is assigned to but never used
```

Please fix this. Please also ensure changes to Python code, especially to the wheel builder, do not introduce new `flake8` reports.
___
*[`tools/wheel/wheel_builder/linux.py` line 147 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3Y95p4lJaDQNYrsZ9:-NR3Y95p4lJaDQNYrsZA:b-thk8je) ([raw file](https://github.com/RobotLocomotion/drake/blob/3de7cd0f4eb5a4c0293785b0dd931ce1e232af25/tools/wheel/wheel_builder/linux.py#L147)):*
> ```Python
>     # Add an rcfile that's compatible with our Dockerfile base.
>     rc_lines = [
>         "import %workspace%/tools/ubuntu.bazelrc",
> ```

With one exception, these are the only `"` strings in the entire wheel builder. Please consider using `'` strings for consistency's sake.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: (thanks!)

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-:-NR3p4et5qrS-frGHgz_:btsxb2i)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3o1Lw-ciw-rmS2VVu):*
FYI, this comment is now outdated.
___
*[`tools/wheel/image/setup.py` line 31 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3lTlk0uM-8I_qhMtS:-NR3lTll0XEL20rFcoC8:b-g5wbr8) ([raw file](https://github.com/RobotLocomotion/drake/blob/8ea43424a8f0069d227ba7ad59b57bb0a24bf925/tools/wheel/image/setup.py#L31)):*
> ```Python
>     result = find_packages()
>     result.extend([
>         "pydrake.examples",
> ```

Heh, I really just had `wheel_builder` in mind, but okay. :slightly_smiling_face: 
___
*[`tools/wheel/wheel_builder/common.py` line 109 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3VyOZ0aUikg7PHumN:-NR3lcQ92UaRHxg02EQi:b-ucfknh) ([raw file](https://github.com/RobotLocomotion/drake/blob/fac839efa389ac66a83a38fba41d6835f2d73450/tools/wheel/wheel_builder/common.py#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`tools/wheel/wheel_builder/common.py` line 116 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3WFXY8CjDA5rvY15q:-NR3lf8Y9IKieBsZPe7v:b-totzj4) ([raw file](https://github.com/RobotLocomotion/drake/blob/3de7cd0f4eb5a4c0293785b0dd931ce1e232af25/tools/wheel/wheel_builder/common.py#L116)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done (via TODO).

The benefit is that it allows us to merge this PR without coordinating a flag-day CI change.
</blockquote></details>

Right, that was my suspicion, but it would be nice to not leave cruft lying around unnecessarily. A TODO seems like the right approach; thanks!
___
*[`tools/wheel/wheel_builder/common.py` line 141 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3Wm6l1stf8HdFwvyB:-NR3m7vF0IfFEzGpzbY-:b-v2hscn) ([raw file](https://github.com/RobotLocomotion/drake/blob/3de7cd0f4eb5a4c0293785b0dd931ce1e232af25/tools/wheel/wheel_builder/common.py#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Please fix this.

Done.

> Please also ensure changes to Python code, especially to the wheel builder, do not introduce new flake8 reports.

Not as part of this PR.  If we think a certain linter's reports are valid, then we add that linter to Bazel & CI.  Developers should not be expected to set up bespoke linting tools to clear code review.
</blockquote></details>

Okay, but I also immediately noticed this particular issue just from eyeballs; I only ran `flake8` afterward for confirmation.

IMHO, adding `flake8` to automated testing would be valuable. I believe it overlaps somewhat with existing tests, but it also catches some non-style issues. I generally try to keep any Python *I* write flake8-clean, whether for Drake or anything else.

Thanks for the fix.
___
*[`tools/wheel/wheel_builder/linux.py` line 147 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3Y95p4lJaDQNYrsZ9:-NR3nwFV7LW8jGin8rVk:b-ucfknh) ([raw file](https://github.com/RobotLocomotion/drake/blob/3de7cd0f4eb5a4c0293785b0dd931ce1e232af25/tools/wheel/wheel_builder/linux.py#L147)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-:-NR3q1dq8SRPdZiEmVyz:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18999)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3qWU-Awavw3KrJhiB):*
nit



_Suggestion:_
```
  Change testing to be opt-out instead of opt-in; do not provide any
  one-letter option to disable testing of extracted wheels (too dangerous).
```

**Comment by mwoehlke-kitware** [comment]
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18999#-NR3qWU-Awavw3KrJhiB):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Okay; I suppose if the goal is to document that not adding a short form of `--no-test` is deliberate, that works. My original thought was that, as `-n` still exists and there was never a one-letter option for `--no-test` in the first place, everything after the `;` is unneeded. But your suggestion also works for me. :shrug:

**Pull request merged**
