### PR TITLE
Rename output port accessors 

### PR DESCRIPTION
**Pull request by sammy-tri**
(which had previously called themselves input ports)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8553)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@siyuanfeng-tri for feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8553#-:-L9fZaEtCXAviQY4L-d5:blt30i2)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8553#-:-L9f_jOg7gBySGwsejak:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8553#-:-L9fstNr3omxVNMO3PUu:b-ykw85)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8553#-:-L9ga5GfEQkx_Y3rOPPZ:bnfp4nl)*

**Pull request merged**
