### PR TITLE
Python bindings for ContactResults

### PR DESCRIPTION
**Pull request by gizatt**
These bindings enable construction of systems that subscribe to the contact results port of a RigidBodyPlant, for e.g. plotting and visualizing contact forces.

@EricCousineau-TRI, would you mind feature reviewing this one (or delegating it) once I get this through CI?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Yup, works for me!

+@ericcousineau-tri for feature review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736#-:-LBSqHtPEIbVPKmGug2v:b-ga2iw2)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending CI.

+@sammy-tri for platform review, please.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSq_qc0AUJwOnFyqsU:-LBSq_qc0AUJwOnFyqsV:bcezoz0) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L68)):*
> ```cpp
>         .def(
>             py::init<
>                 const Eigen::Vector3d&,
> ```

BTW Can you rewrite this as `Vector3<T>`? Will make it easier to define instantiations for `AutoDiffXd`.

If you're feeling adventurous, you can take a peek at this code for how to do it ;)
https://github.com/RobotLocomotion/drake/blob/c9a56a2cad79d823a58397071a8cc2f9fe2a0257/bindings/pydrake/systems/primitives_py.cc#L32

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736#-:-LBSrHjo0MNLqx6eLuWH:b3flqlk)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSsHPV0P6lXgQwwgCR:-LBSsHPV0P6lXgQwwgCS:b-tc7j74) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L54)):*
> ```cpp
>     py::class_<Class> cls(m, "ContactInfo");
>     cls
>         .def(py::init<const drake::multibody::collision::ElementId,
> ```

BTW This constructor is not tested. Can  you remove it, or test it if you think it may be needed in Python?

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrbf9EYKtPy0iKZZ6:-LBSrbf9EYKtPy0iKZZ7:bdx1mu6) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L94)):*
> ```cpp
>              &Class::get_contact_info, py_reference_internal)
>         .def("set_generalized_contact_force",
>             [](Class * cr,
> ```

BTW nit style Can you make this `Class* self` (spacing and name)?

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrqdRBX6Qar_P-9nj:-LBSrqdRBX6Qar_P-9nk:b-ug85rt) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L100)):*
> ```cpp
>         .def("get_generalized_contact_force",
>              &Class::get_generalized_contact_force, py_reference_internal)
>         .def("AddContact", &Class::AddContact, py_reference_internal)
> ```

BTW Can you add named `py::arg()`s here?

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSryBgC6TWpMAHdk-v:-LBSryBgC6TWpMAHdk-w:brsftlz) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L128)):*
> ```Python
>         id_1 = 42
>         id_2 = 43
>         info = results.AddContact(id_1, id_2)
> ```

BTW Can you use the named arguments when you add them?

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 130 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSsD1q36-KAeYRy3_q:-LBSsD1q36-KAeYRy3_r:b403yo5) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L130)):*
> ```Python
>         info = results.AddContact(id_1, id_2)
>         self.assertEquals(results.get_num_contacts(), 1)
>         self.assertEquals(results.get_contact_info(0), info)
> ```

BTW Can you add an instance check for `ContactInfo` on this?

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrvMs7QK5D1Io1h1y:-LBSrvMs7QK5D1Io1h1z:bdr3ga4) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L138)):*
> ```Python
>         force = np.array([0.9, 0.1, 0.9])
>         torque = np.array([0.6, 0.6, 0.6])
>         cf = mut.ContactForce(pt, normal, force, torque)
> ```

BTW Can you use the named constructor for this class?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736)*

**Comment by gizatt** [comment]
Thanks! Addressed first round.

---

Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSsHPV0P6lXgQwwgCR:-LBStW4o47sgfv9thmir:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L54)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW This constructor is not tested. Can  you remove it, or test it if you think it may be needed in Python?
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSq_qc0AUJwOnFyqsU:-LBStgPD-pwJgUVoDvTH:buibw20) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L68)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can you rewrite this as `Vector3<T>`? Will make it easier to define instantiations for `AutoDiffXd`.

If you're feeling adventurous, you can take a peek at this code for how to do it ;)
https://github.com/RobotLocomotion/drake/blob/c9a56a2cad79d823a58397071a8cc2f9fe2a0257/bindings/pydrake/systems/primitives_py.cc#L32
</blockquote></details>

Done, albeit I'm gonna opt for the non-adventurous route for now :).

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrbf9EYKtPy0iKZZ6:-LBSuDPxAweaazlb0Mnr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L94)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW nit style Can you make this `Class* self` (spacing and name)?
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrqdRBX6Qar_P-9nj:-LBSuQ1i5kprIKS-Zfms:b-w5ova1) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can you add named `py::arg()`s here?
</blockquote></details>

Done. I went with having their names not match the names of the args of the bound method exactly so that these names might better reflect the expected types (ids), but am happy to switch that back if you think it's unnecessary / bad style.

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSryBgC6TWpMAHdk-v:-LBSuoTA6B3N5w1pBDYt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L128)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can you use the named arguments when you add them?
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 130 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSsD1q36-KAeYRy3_q:-LBSv5v92LcDKuGdGdo8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L130)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can you add an instance check for `ContactInfo` on this?
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrvMs7QK5D1Io1h1y:-LBSvBao19or2ZN44e2x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L138)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can you use the named constructor for this class?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736#-:-LBSvJI3AO2vWWJSE6hH:b371tuy)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSq_qc0AUJwOnFyqsU:-LBSwCeiBw_o933kv0is:bylha9s) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L68)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done, albeit I'm gonna opt for the non-adventurous route for now :).
</blockquote></details>

OK Quite understandable!

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrbf9EYKtPy0iKZZ6:-LBSwIGc-lvUVxogR0A9:b-5p21zi) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L94)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW Can you reflow the line too?
```c++
  .def("set_generalized_contact_force",
       [](Class* self, Eigen::VectorXd& f) {
           self->set_generalized_contact_force(f);
       })
```

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrqdRBX6Qar_P-9nj:-LBSwhLa0BlDLOI-yMqB:bjo9rs6) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L100)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done. I went with having their names not match the names of the args of the bound method exactly so that these names might better reflect the expected types (ids), but am happy to switch that back if you think it's unnecessary / bad style.
</blockquote></details>

Yeah, would you be able to switch it back?
I believe if you look at `help()` for the given function, it'll indicate the C++ types for the `pybind11` overload functions.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736)*

**Comment by gizatt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrbf9EYKtPy0iKZZ6:-LBSyXYb9jpsmVEc18Xd:b-gk5vq9) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L94)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can you reflow the line too?
```c++
  .def("set_generalized_contact_force",
       [](Class* self, Eigen::VectorXd& f) {
           self->set_generalized_contact_force(f);
       })
```
</blockquote></details>

Done, I think?

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8736#-LBSrqdRBX6Qar_P-9nj:-LBSxmM17yf_6UAyyQBI:bch0nph) ([raw file](https://github.com/robotlocomotion/drake/blob/3a5e36134a85f14e1ffd0973b4c27a77bcf0375a/bindings/pydrake/multibody/rigid_body_plant_py.cc#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, would you be able to switch it back?
I believe if you look at `help()` for the given function, it'll indicate the C++ types for the `pybind11` overload functions.
</blockquote></details>

Oh that's neat. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736#-:-LBWLBnVAjecKIeqBhoA:bsf2vkf)*

**Comment by sammy-tri** [comment]
Actually, I'll just do the squash merge.

-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8736#-:-LBWLd8y57Daciu7jcKh:b-ikdr73)*

**Pull request merged**
