### PR TITLE
Move code from unit_inertia.h to unit_inertia.cc. TODO() for later possible breaking change.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19761)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 
Note: Mostly cut/paste from unit_inertia.h to unit_inertia.cc.
Added some TODO() to remind us of future need to handle unit_vector argument of some of the methods.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19761#-:-N_BwADi1JeWRCecoU7C:bv3jc91)* status: LGTM missing from assignee sherm1(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19761)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`multibody/tree/unit_inertia.h` line 285 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19761#-N_FC8yJ6_8jpYKlIp1v:-N_FEvW83lbjJbawIKGG:bi2878y) ([raw file](https://github.com/RobotLocomotion/drake/blob/94c72d366add47b93c669bf263b2af402ff6ee02/multibody/tree/unit_inertia.h#L285)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW in the past our Python documentation generator was confused if the Doxygen documentation was separated from the function it documents by an ordinary `//` comment. The fix is to put the TODO comment _above_ the Doxygen comment rather than below. I'm not certain whether we still have that problem but it's safer to assume it is still there unless we have confirmation that it isn't. Any word on that, @jwnimmer-tri ?
</blockquote></details>

If you're worried about it, you can either:
(1) Move the TODO to live somewhere else.
(2) Run https://drake.mit.edu/documentation_instructions.html and see if the documentation shows up correctly.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19761)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`multibody/tree/unit_inertia.h` line 285 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19761#-N_FC8yJ6_8jpYKlIp1v:-N_FHnr4-WjGZNP4EBMB:bi3w27r) ([raw file](https://github.com/RobotLocomotion/drake/blob/94c72d366add47b93c669bf263b2af402ff6ee02/multibody/tree/unit_inertia.h#L285)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you're worried about it, you can either:
(1) Move the TODO to live somewhere else.
(2) Run https://drake.mit.edu/documentation_instructions.html and see if the documentation shows up correctly.
</blockquote></details>

(3) Run `bazel run //tools/workspace/pybind11:py/sample_header_documentation_py_test` and modify `sample_header.h` to add that for all objects, and then test for all platforms.

My vote, though, is for (1) for this PR - much simpler!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19761#-:-N_FM10K0XvOkyOvkMqR:bcpz082)* status: 1 unresolved discussion

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19761)* status: 1 unresolved discussion

___
*[`multibody/tree/unit_inertia.h` line 285 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19761#-N_FC8yJ6_8jpYKlIp1v:-N_FOqai1lnXSf2kszj0:b-pn4810) ([raw file](https://github.com/RobotLocomotion/drake/blob/94c72d366add47b93c669bf263b2af402ff6ee02/multibody/tree/unit_inertia.h#L285)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(3) Run `bazel run //tools/workspace/pybind11:py/sample_header_documentation_py_test` and modify `sample_header.h` to add that for all objects, and then test for all platforms.

My vote, though, is for (1) for this PR - much simpler!
</blockquote></details>

see https://github.com/RobotLocomotion/drake/pull/19774

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19761#-:-N_GEgKS4-PMUJ9pfXNP:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform)

___
*[`multibody/tree/unit_inertia.h` line 285 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19761#-N_FC8yJ6_8jpYKlIp1v:-N_G57nc4dpQTC-fyo2Z:b-8a1iff) ([raw file](https://github.com/RobotLocomotion/drake/blob/94c72d366add47b93c669bf263b2af402ff6ee02/multibody/tree/unit_inertia.h#L285)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

see https://github.com/RobotLocomotion/drake/pull/19774
</blockquote></details>

Done.  Moved TODO to live elsewhere.

**Pull request merged**
