### PR TITLE
Added semi-explicit Euler integrator.

### PR DESCRIPTION
**Pull request by edrumwri**
Adds semi-explicit Euler integration (thereby adding symplectic integration for Hamiltonian systems) and also stresses the conversions between generalized coordinates and generalized velocities (when the two are distinct). 

_This PR relies upon the bugfix provided by PR #4965 to obtain the same result (to numerical tolerances) from integrating a rigid body using semi-explicit Euler integration and "standard" explicit Euler integration. Prior to #4965, the two answers would be distinct._

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5017)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review and +@sammy-tri for platform review (due to regular rotation), please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-:-KbvPQvNpULem0OofN-2:bkndczs)*

**Comment by sammy-tri** [comment]
Left a couple of BTW comments below.  :lgtm: from platform perspective

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kbzg2FmwhNYAVny1H2l:-Kbzg2FoJYqw4hgYuQX0:b-fk81ht) ([raw file](https://github.com/robotlocomotion/drake/blob/787fb0d91296d7e64eeaac5be04d9b89d01282eb/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L36)):*
> ```cpp
> 
>   // Test that setting the target accuracy or initial step size target fails.
>   EXPECT_THROW(int_dbl.set_target_accuracy(1.0), std::logic_error);
> ```

BTW These are also tested below and seem a little redundant here.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-KbzgmQPTMyRahYvOkHR:-KbzgmQRiMewpgb8e92u:b-oqg2lh) ([raw file](https://github.com/robotlocomotion/drake/blob/787fb0d91296d7e64eeaac5be04d9b89d01282eb/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L210)):*
> ```cpp
> 
>   // Verify that integrator statistics are valid
>   EXPECT_GE(integrator.get_previous_integration_step_size(), 0.0);
> ```

BTW Should this like and the next two be EXPECT_GT?  Or are these valuse allowed to be zero even after a step has been taken?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-:-Kbzgus6SfgTtgGYAb4p:b4l224j)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kbzg2FmwhNYAVny1H2l:-Kc-16aKopa8A09HjCPx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/787fb0d91296d7e64eeaac5be04d9b89d01282eb/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L36)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW These are also tested below and seem a little redundant here.
</blockquote></details>

Done.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-KbzgmQPTMyRahYvOkHR:-Kc-15gQeBN22qvMk6Zk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/787fb0d91296d7e64eeaac5be04d9b89d01282eb/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L210)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW Should this like and the next two be EXPECT_GT?  Or are these valuse allowed to be zero even after a step has been taken?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5017)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-:-Kc-5T0_mcSlfz7-8yCq:b-s794vx)*

**Comment by sherm1** [comment]
Nice! The API for adding new integrators is really clean. A few comment-related BTWs below, then :lgtm_strong:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-x3b1TNUy6ysh-5TS:-Kc-x3b1TNUy6ysh-5TT:brn0lpi) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/semi_explicit_euler_integrator.h#L25)):*
> ```objc
>  * are frequently used to transform between time derivatives of Euler 
>  * parameters (unit quaternions) and angular velocities (and vice versa), 
>  * [Nikravesh 1988].
> ```

FYI, also common to use N to translate between 3 rotation angle derivatives and angular velocity. Not sure if that adds anything here.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-yuTHU1zgnD9CbIAS:-Kc-yuTHU1zgnD9CbIAT:bq9stir) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/semi_explicit_euler_integrator.h#L34)):*
> ```objc
>  * When a mechanical system is Hamiltonian (informally meaning that the
>  * system is not subject to velocity-dependent forces), the semi-explicit
>  * Euler integrator is a symplectic (momentum conserving) integrator.
> ```

BTW, I would say "energy conserving" here instead.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-zLHV0lcuMmkLUjGl:-Kc-zLHV0lcuMmkLUjGm:b-pz1nqn) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/semi_explicit_euler_integrator.h#L39)):*
> ```objc
>  * are not Hamiltonian, even in the absence of externally applied
>  * velocity-dependent forces, due to the presence of both Coriolis and
>  * gyroscopic forces. 
> ```

BTW, add: For this integrator to be symplectic for those systems the velocity stage must be done implicitly. In that case the integrator is called "semi-*implicit* Euler" or "Symplectic Euler".

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc0-eTyOW4v403Suhss:-Kc0-eTzC9Amooo3_fGa:b-pbw0c3) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/semi_explicit_euler_integrator.h#L81)):*
> ```objc
>    */
>   SemiExplicitEulerIntegrator(const System<T>& system, const T& max_step_size,
>                           Context<T>* context = nullptr)
> ```

BTW, odd indenting.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-tHRwZfhCkVwkk113:-Kc-tHRwZfhCkVwkk114:b-p8h39i) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L17)):*
> ```cpp
> namespace {
> 
> GTEST_TEST(IntegratorTest, ContextAccess) {
> ```

BTW, needs a comment saying what this test case is testing.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-tTvrHbAThAnEvzFN:-Kc-tTvrHbAThAnEvzFO:b-9fam3k) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L39)):*
> ```cpp
> }
> 
> /// Verifies error estimation is unsupported.
> ```

BTW, Just `//`

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 86 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-ut2Jp2v2HZOVO9Wr:-Kc-ut2Jp2v2HZOVO9Ws:bc1oigq) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L86)):*
> ```cpp
>   Eigen::Vector3d w0(-4, 5, 6);  // Angular velocity in body's frame.
>   BasicVector<double> generalized_velocities(plant.get_num_velocities());
>   generalized_velocities.get_mutable_value() << w0, v0;
> ```

BTW, probably should have a comment that this code is dependent on QuatFloatJoint state layout.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 93 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-vJ8T3QqoznkBMJ1W:-Kc-vJ8T3QqoznkBMJ1X:bwnxk5v) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L93)):*
> ```cpp
> 
>   // Integrate for one second of virtual time using a RK2 integrator with
>   // large step size.
> ```

BTW, Comment doesn't match the code below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-:-Kc00DaL4wpMJS9F_Mvo:bl43yq)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-yuTHU1zgnD9CbIAS:-Kc0K-X8Twad4irAw8_g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/semi_explicit_euler_integrator.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I would say "energy conserving" here instead.
</blockquote></details>

Done.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-zLHV0lcuMmkLUjGl:-Kc0Kq--8pQiIYtjYzdv:bulfr66) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/semi_explicit_euler_integrator.h#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, add: For this integrator to be symplectic for those systems the velocity stage must be done implicitly. In that case the integrator is called "semi-*implicit* Euler" or "Symplectic Euler".
</blockquote></details>

PTAL at my updated text- I didn't want to go down that path of discussion too much, since we are not (yet) providing such an integrator, and I don't think it's wise to ask the user to do such implicit solves themselves.  

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc0-eTyOW4v403Suhss:-Kc0LP-MGS11CsADc7sA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/semi_explicit_euler_integrator.h#L81)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, odd indenting.
</blockquote></details>

Done.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-tHRwZfhCkVwkk113:-Kc0O-ctxDpdLz6sJ3as:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L17)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, needs a comment saying what this test case is testing.
</blockquote></details>

Done.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-tTvrHbAThAnEvzFN:-Kc0O4UEQnx6qnZl0fqz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, Just `//`
</blockquote></details>

Done.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 86 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-ut2Jp2v2HZOVO9Wr:-Kc0OLjW0OCNRicfD26u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L86)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, probably should have a comment that this code is dependent on QuatFloatJoint state layout.
</blockquote></details>

Done.

---

*[drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc, line 93 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-Kc-vJ8T3QqoznkBMJ1W:-Kc0OUx4ANcSjAjGH67v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18b8a67da92678c50ca6d7d5f30d3cc5a058f25b/drake/systems/analysis/test/semi_explicit_euler_integrator_test.cc#L93)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, Comment doesn't match the code below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5017)*

**Comment by sherm1** [comment]
All good -- ready to merge pending CI.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5017#-:-Kc0QI3mZWUOusrmQBjz:b-1d7xlc)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5017)*

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-clang-continuous-debug please

**Pull request merged**
