### PR TITLE
Ensure sanitizer environment variables are set during local testing

### PR DESCRIPTION
**Pull request by jamiesnape**
Split from #4699 as discussed F2F.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5379)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review (previously feature reviewed by @mwoehlke-kitware in #4699).

**Comment by david-german-tri** [comment]
:lgtm: but please let the following builds finish before merging, so that we have an easy way to compare to the status quo and see what actually got suppressed.

@drake-jenkins-bot linux-clang-experimental-memcheck-asan please
@drake-jenkins-bot linux-clang-experimental-memcheck-lsan please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5379#-:-KeEvQsiigSYNmMOS2qG:ben78xt)*

**Comment by david-german-tri** [comment]
Hang on, that's silly, those builds are already green.  Still worth running to make sure they stay green, though.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5379#-:-KeEvvey2Q4gdYl3L5dr:b-m122kj)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5379)*

**Pull request merged**
