### PR TITLE
update director external

### PR DESCRIPTION
**Pull request by patmarion**
This adds drakeCommon to the list of required link libraries.

This fixes a link error when linking against the debug version of
drake on mac, where linking to drakeCommon is required for the
drake::detail::Abort() function when assertions are enabled.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3935)

### CODE REVIEW

**Comment by patmarion** [comment]
+@BetsyMcPhail for review

This fixes the mac debug builds (hopefully).

**Comment by BetsyMcPhail** [comment]
:lgtm: (assuming mac debug builds pass!)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3935#-:-KV6_8fe7dn2RqzA4zP2:b-bisg5k)*

**Comment by patmarion** [comment]
I started a mac debug build on jenkins for this, I'll update when it finishes.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3935#-:-KV6_yAkfo0xH2tg0sQp:bnfp4nl)*

**Comment by patmarion** [comment]
build was successful, so I am going to merge.

https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-experimental/203/

**Pull request merged**
