### PR TITLE
Fix some cpplint readability warnings

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix several cpplint warnings and then stop suppressing their rules:
 - readability/fn_size
 - readability/function
 - readability/multiline_comment

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2059)

### CODE REVIEW

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/eiquadprog.h, line 167 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2059#-KF5aCNCKxDaRLYqvTet:-KF5aCND4-9wWfmvb3zO:1099072544) ([raw file](https://github.com/robotlocomotion/drake/blob/2bdf9def4d553fc580f4c923c5b862d2f43e02be/drake/systems/plants/eiquadprog.h#L167)):*
capppunc
(but I am giving this a checkmark anyway because this is a nit and carried over from old code; resolve iff you care.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2059#-:-KF5bFnhXSaqC8MruLZD:1417088721)*

**Comment by jwnimmer-tri** [comment]
The eiquadprog.h is such a style-junkpile that I'm going to leave well enough alone.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/eiquadprog.h, line 167 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2059#-KF5aCNCKxDaRLYqvTet:-KF5ygb3FZ5e04ZZo8vv:-875593624) ([raw file](https://github.com/robotlocomotion/drake/blob/2bdf9def4d553fc580f4c923c5b862d2f43e02be/drake/systems/plants/eiquadprog.h#L167)):*
(Skipped.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2059)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@david-german-tri Ready to merge.  Jenkins is just waiting on a test-results upload, but otherwise passed.  I tested the new cpplint rule on a local rebase-to-master and no regressions.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2059#-:-KF9cW8V3x98wQ5Jhb8I:1417088721)*

**Pull request merged**
