### PR TITLE
[systems/analysis] Implements RegionOfAttraction for implicit dynamics

### PR DESCRIPTION
**Pull request by RussTedrake**
This PR moves one step closer to support RegionOfAttraction analysis
of MultibodyPlant systems. MultibodyPlant systems introduce two
additional complexities: (1) the dynamics are trigonometric +
polynomial, and (2) the dynamics are rational.  This PR adds support
for (2).  Support for (1) will come in the follow-up, incorporating #16690.

+@hongkai-dai for feature review
+@shensquared for additional feature review, if you're available

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704)* status: 4 unresolved discussions, LGTM missing from assignees hongkai-dai,shensquared, needs platform reviewer assigned (waiting on @hongkai-dai, @RussTedrake, and @shensquared)

___
*[systems/analysis/region_of_attraction.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDbNE13ymt59aA_uGx:-MxDbNE13ymt59aA_uGy:baf7bqi) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L126)):*
> ```cpp
>     const solvers::VectorXIndeterminate& xdot, const Expression& V,
>     const Expression& Vdot, const VectorX<Expression>& g) {
>   // Check if the Hessian of Vdot is negative definite on the manifold.
> ```

Not sure if "manifold" is the right word here. I would think you mean that the Hessian of Vdot is locally negative definite around the equilibrium y=0 and on the tangent space Gy=0.
___
*[systems/analysis/region_of_attraction.cc, line 179 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDcbPRDtBU1A3NJiEq:-MxDcbPS0PnsdCxQtM0x:b9bq52h) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L179)):*
> ```cpp
>   // TODO(russt): Add this as an option once I have an example that needs it.
>   // This is a reasonable guess.
>   const int lambda_degree = Vdot_degree;
> ```

Not sure why we use Vdot_degree as the default value for lambda degree.

I would think we want lambda * Vdot to have degree as high as V * x'*x. So this should be lambda_degree = max(V_degree + 2 - Vdot_degree, 0)?
___
*[systems/analysis/region_of_attraction.cc, line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDdNyf56D6ETp4mH16:-MxDdNyf56D6ETp4mH17:b-7yxfao) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L186)):*
> ```cpp
>     // Want λ_g[i] * g[i] to have the same degree as λ * Vdot.
>     const int lambda_gi_degree =
>         lambda_degree + Vdot_degree - Polynomial(g[0]).TotalDegree();
> ```

Should take max(lambda_degree + Vdot_degree - Polynomial(g[0]).TotalDegree(), 0) here to make sure the degree is non-negative?
___
*[systems/analysis/region_of_attraction.cc, line 193 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDdp4t59VjU1Eaoa96:-MxDdp4t59VjU1Eaoa97:b-8hr495) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L193)):*
> ```cpp
>   const auto rho = prog.NewContinuousVariables<1>("rho")[0];
> 
>   // Want (V-rho)(x'x)^d and Lambda*Vdot to be the same degree.
> ```

The documentation at the start of the function doesn't raise x'x to the d'th power.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704)* status: 4 unresolved discussions, LGTM missing from assignees hongkai-dai,shensquared, needs platform reviewer assigned (waiting on @hongkai-dai and @shensquared)

___
*[systems/analysis/region_of_attraction.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDbNE13ymt59aA_uGx:-MxF6znWEwx1UFnyKtYF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L126)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not sure if "manifold" is the right word here. I would think you mean that the Hessian of Vdot is locally negative definite around the equilibrium y=0 and on the tangent space Gy=0.
</blockquote></details>

Done.
___
*[systems/analysis/region_of_attraction.cc, line 179 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDcbPRDtBU1A3NJiEq:-MxF73Pj4ST5XgyJYiHr:bc5qhe8) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L179)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not sure why we use Vdot_degree as the default value for lambda degree.

I would think we want lambda * Vdot to have degree as high as V * x'*x. So this should be lambda_degree = max(V_degree + 2 - Vdot_degree, 0)?
</blockquote></details>

it surprised me, too... but that was the default we had for the explicit ROA case.  I believe we had good reason for it then, and I regret not documenting it.  (Maybe it came up from @shensquared in code review?)
___
*[systems/analysis/region_of_attraction.cc, line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDdNyf56D6ETp4mH16:-MxF7Ky7DaKUJqbwORmp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L186)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should take max(lambda_degree + Vdot_degree - Polynomial(g[0]).TotalDegree(), 0) here to make sure the degree is non-negative?
</blockquote></details>

Done.
___
*[systems/analysis/region_of_attraction.cc, line 193 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDdp4t59VjU1Eaoa96:-MxF7WGWEA6bEzStzVXg:bavezyz) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L193)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The documentation at the start of the function doesn't raise x'x to the d'th power.
</blockquote></details>

Done. (I also forgot mention the multipliers for g!)

**Review by shensquared — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704)* status: 5 unresolved discussions, LGTM missing from assignees hongkai-dai,shensquared, needs platform reviewer assigned (waiting on @hongkai-dai, @RussTedrake, and @shensquared)

___
*[systems/analysis/region_of_attraction.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxF5glh9hUXABHVbsAB:-MxF5glh9hUXABHVbsAC:b-4vgf7u) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.h#L34)):*
> ```objc
>    * CalcImplicitTimeDerivativesResidual instead of CalcTimeDerivatives to
>    * obtain g(x,ẋ) = 0 (instead of ẋ = f(x)).  The Lyapunov conditions will
>    * also be evaluated in the implicit form. This is more expensive that
> ```

typo, that->than
___
*[systems/analysis/region_of_attraction.cc, line 179 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDcbPRDtBU1A3NJiEq:-MxFF3yA3bfXgXaZZcWr:bakoe04) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L179)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it surprised me, too... but that was the default we had for the explicit ROA case.  I believe we had good reason for it then, and I regret not documenting it.  (Maybe it came up from @shensquared in code review?)
</blockquote></details>

In this formulation: (V-rho)*(x'*x)ᵈ - Lambda * Vdot + Lambda_g * g, each of the three terms has a 'flexible' degree: d, degree of Lambda, and degree of Lambda_g. As Hongkai pointed out, we'd want the overall polynomial to come out having at least degree zero. 

But of course, if all three are left fluid without a default, it'd be circular relative references. So we choose to fix Lambda degree first (this is a bit arbitrary, more on it later), and we then derive, based on this fixed Lambda degree, the other two. Btw, this is exactly how the degree of Lambda_g and d are set in the code below.

The choice Lambda_degree=Vdot_degree itself actually came from the Matlab era https://github.com/RobotLocomotion/drake/blob/d7f3c011d37d471d7b9293ecf2066c98d88b2a05/drake/matlab/systems/%40PolynomialSystem/regionOfAttraction.m#L112 and was used as default for bilinear and other methods as well. Although the documentation says 'just a guess', I **think** the rationale for it is simply that, among all those we can't mess with, Vdot usually has the highest degree, so raising the multiplier Lambda to degree match it should be a safe (maybe a bit wasteful) choice to ensure overall poly has non-negative degree.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704)* status: 3 unresolved discussions, LGTM missing from assignees hongkai-dai,shensquared, needs platform reviewer assigned (waiting on @hongkai-dai, @RussTedrake, and @shensquared)

___
*[systems/analysis/region_of_attraction.cc, line 179 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDcbPRDtBU1A3NJiEq:-MxFehdS-hBYgiRq6JJa:b1rnjoz) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L179)):*
<details><summary><i>Previously, shensquared (Shen Shen) wrote…</i></summary><blockquote>

In this formulation: (V-rho)*(x'*x)ᵈ - Lambda * Vdot + Lambda_g * g, each of the three terms has a 'flexible' degree: d, degree of Lambda, and degree of Lambda_g. As Hongkai pointed out, we'd want the overall polynomial to come out having at least degree zero. 

But of course, if all three are left fluid without a default, it'd be circular relative references. So we choose to fix Lambda degree first (this is a bit arbitrary, more on it later), and we then derive, based on this fixed Lambda degree, the other two. Btw, this is exactly how the degree of Lambda_g and d are set in the code below.

The choice Lambda_degree=Vdot_degree itself actually came from the Matlab era https://github.com/RobotLocomotion/drake/blob/d7f3c011d37d471d7b9293ecf2066c98d88b2a05/drake/matlab/systems/%40PolynomialSystem/regionOfAttraction.m#L112 and was used as default for bilinear and other methods as well. Although the documentation says 'just a guess', I **think** the rationale for it is simply that, among all those we can't mess with, Vdot usually has the highest degree, so raising the multiplier Lambda to degree match it should be a safe (maybe a bit wasteful) choice to ensure overall poly has non-negative degree. 
</blockquote></details>

I see, thanks Shen. I think it is better to document it here, that because Vdot usually has the highest degree between V, Vdot, we choose lambda_degree = Vdot degree to make sure that lambda * Vdot has a degree higher than V.
___
*[systems/analysis/region_of_attraction.cc, line 202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxFf7xp56ytRffrG6a9:-MxFf7xp56ytRffrG6aA:b-vxwhuu) ([raw file](https://github.com/robotlocomotion/drake/blob/5cfdbc92993df7cb3074fe1c84c38cafd0225902/systems/analysis/region_of_attraction.cc#L202)):*
> ```cpp
>   // local stability.  Add "lambda(x) is SOS" to confirm this local stability.
>   if (!Vdot_is_locally_negative_definite) {
>     prog.AddSosConstraint(lambda);
> ```

If we want to make sure that lambda is SOS, I think it is better to make lambda_degree a n even integer?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704)* status: 2 unresolved discussions, LGTM missing from assignees hongkai-dai,shensquared, needs platform reviewer assigned (waiting on @hongkai-dai and @shensquared)

___
*[systems/analysis/region_of_attraction.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxF5glh9hUXABHVbsAB:-MxXK6oX8HoE5kDASnN7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.h#L34)):*
<details><summary><i>Previously, shensquared (Shen Shen) wrote…</i></summary><blockquote>

typo, that->than
</blockquote></details>

Done.
___
*[systems/analysis/region_of_attraction.cc, line 179 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDcbPRDtBU1A3NJiEq:-MxXOUTbBSvi4ots32sA:b5g4237) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L179)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, thanks Shen. I think it is better to document it here, that because Vdot usually has the highest degree between V, Vdot, we choose lambda_degree = Vdot degree to make sure that lambda * Vdot has a degree higher than V.
</blockquote></details>

Thank you both.  It was good to look back at the matlab code... though the default degree of L1 was chosen there the same way for algorithms that used it quite differently.  I do think it's a reasonable, guess, but I'm not sure I quite buy the arguments here.  I've written the justification that makes sense to me; and also updated it above.  PTAL.

(BTW -- I've also confirmed that making it smaller impacts at least the tightness of the bound in the Parrilo thesis example, so I'm inclined to keep it as is).  
___
*[systems/analysis/region_of_attraction.cc, line 202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxFf7xp56ytRffrG6a9:-MxXPmWA89dsdejltVwO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5cfdbc92993df7cb3074fe1c84c38cafd0225902/systems/analysis/region_of_attraction.cc#L202)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If we want to make sure that lambda is SOS, I think it is better to make lambda_degree a n even integer?
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@sammy-tri for platform review please, thanks!

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704#-:-MxYNrle62bCDy4Sr8dk:bptxe99)* status: LGTM missing from assignees shensquared,sammy-tri(platform) (waiting on @hongkai-dai, @sammy-tri, and @shensquared)

___
*[systems/analysis/test/region_of_attraction_test.cc, line 93 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxYNmjmAweimdS4hRl0:-MxYNmjmAweimdS4hRl1:buwuhoe) ([raw file](https://github.com/robotlocomotion/drake/blob/84cef96d29e0c861f1efa78e7d16dc2f341729d2/systems/analysis/test/region_of_attraction_test.cc#L93)):*
> ```cpp
> 
>   const Polynomial V_expected{(x * x + y * y) / gamma};
>   std::cout << "V = " << V.Expand() << std::endl;
> ```

BTW, remove this print out?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704)* status: LGTM missing from assignees sammy-tri(platform),shensquared (waiting on @hongkai-dai, @sammy-tri, and @shensquared)

___
*[systems/analysis/test/region_of_attraction_test.cc, line 93 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxYNmjmAweimdS4hRl0:-MxZ7tDLBzBnyYz-7j-J:b-l5r1cy) ([raw file](https://github.com/robotlocomotion/drake/blob/84cef96d29e0c861f1efa78e7d16dc2f341729d2/systems/analysis/test/region_of_attraction_test.cc#L93)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, remove this print out?
</blockquote></details>

Done.  Thanks.

**Review by shensquared — COMMENTED** [review]
:lgtm: (only minor comments on the documentation)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704#-:-MxZr0vR7Q96SSJbGw_B:b-nxfl53)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai, @RussTedrake, @sammy-tri, and @shensquared)

___
*[systems/analysis/region_of_attraction.cc, line 179 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxDcbPRDtBU1A3NJiEq:-MxZj8z0-2qrrnaeeYve:b4y8sj8) ([raw file](https://github.com/robotlocomotion/drake/blob/08552accabccccc8b2202d5724e6abafc6dba03c/systems/analysis/region_of_attraction.cc#L179)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Thank you both.  It was good to look back at the matlab code... though the default degree of L1 was chosen there the same way for algorithms that used it quite differently.  I do think it's a reasonable, guess, but I'm not sure I quite buy the arguments here.  I've written the justification that makes sense to me; and also updated it above.  PTAL.

(BTW -- I've also confirmed that making it smaller impacts at least the tightness of the bound in the Parrilo thesis example, so I'm inclined to keep it as is).  
</blockquote></details>

This is better and more clear. I like the word 'compete'; I think that's actually what I had in mind but I said it badly. 

(Maybe a do-over/elaboration for myself: In methods we use, inevitably, we'll have two ingredients L1*(V-rho) and L2*(Vdot), or their very close variants. The two have to be linearly combined to conform to convexity. Since Vdot have the dominating degree, we'd hope the multiplier(s) be able to compete.)
___
*[systems/analysis/region_of_attraction.cc, line 36 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxZiKZ16_-yH5FqUl6i:-MxZiKZ16_-yH5FqUl6j:b-so5he6) ([raw file](https://github.com/robotlocomotion/drake/blob/3b62aa64aaf8aade67fc3c7bfbcdbc3618e4df1a/systems/analysis/region_of_attraction.cc#L36)):*
> ```cpp
> // Vdot = 0 => V >= rho (or x=0) via
> //   maximize   rho
> //   subject to (V-rho)*(x'*x)^d - Lambda*Vdot is SOS.
> ```

missing the Lambda_g*g term
___
*[systems/analysis/region_of_attraction.cc, line 78 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxZiWr-40ujYMK-c9UD:-MxZiWr-40ujYMK-c9UE:bjidm4t) ([raw file](https://github.com/robotlocomotion/drake/blob/3b62aa64aaf8aade67fc3c7bfbcdbc3618e4df1a/systems/analysis/region_of_attraction.cc#L78)):*
> ```cpp
>   // This is a reasonable guess: we want the multiplier to be able to compete
>   // with terms in Vdot, and to be even (since it may be SOS below).
>   const int lambda_degree = std::ceil(Vdot_degree/2.0) * 2;
> ```

Just a quick comment, I think the even-ness is implied? (Coz Vdot should be even anyway?) Not an objection of course; actually better to be safe. 
___
*[systems/analysis/region_of_attraction.cc, line 108 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxZhlwy0O_2j8Kil-5L:-MxZhlwz0sniowdhbb3Y:biov87j) ([raw file](https://github.com/robotlocomotion/drake/blob/3b62aa64aaf8aade67fc3c7bfbcdbc3618e4df1a/systems/analysis/region_of_attraction.cc#L108)):*
> ```cpp
> // Vdot(x,z) = 0, g(x,z)=0 => V(x) >= rho (or x=0) via
> //   maximize   rho
> //   subject to (V-rho)*(x'*x)^d - Lambda*Vdot - Lambda_g*g is SOS.
> ```

code is  using **_+_** Lambda_g * g instead of minus (either is correct course, just might be confusing.)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  (the outstanding issues appear to be documentation related, I'll let the author/reviewer sort out the resolution on those)

> Reviewed 1 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704#-:-MxaYu1W98TkefGqoSTo:bc1jzbj)* status: 3 unresolved discussions (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16704)* status: 3 unresolved discussions (waiting on @hongkai-dai, @sammy-tri, and @shensquared)

___
*[systems/analysis/region_of_attraction.cc, line 36 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxZiKZ16_-yH5FqUl6i:-MxbMa9wAbjZ0coM3dMX:bmf1boj) ([raw file](https://github.com/robotlocomotion/drake/blob/3b62aa64aaf8aade67fc3c7bfbcdbc3618e4df1a/systems/analysis/region_of_attraction.cc#L36)):*
<details><summary><i>Previously, shensquared (Shen Shen) wrote…</i></summary><blockquote>

missing the Lambda_g*g term
</blockquote></details>

This is the explicit (aka not implicit) version that was there before. No g term here.
___
*[systems/analysis/region_of_attraction.cc, line 78 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxZiWr-40ujYMK-c9UD:-MxbMkoF3PgG0ntscd4k:b-dnpjzd) ([raw file](https://github.com/robotlocomotion/drake/blob/3b62aa64aaf8aade67fc3c7bfbcdbc3618e4df1a/systems/analysis/region_of_attraction.cc#L78)):*
<details><summary><i>Previously, shensquared (Shen Shen) wrote…</i></summary><blockquote>

Just a quick comment, I think the even-ness is implied? (Coz Vdot should be even anyway?) Not an objection of course; actually better to be safe. 
</blockquote></details>

Someone *could* put in an even f... but i admit it would be odd.  (pun intended).
___
*[systems/analysis/region_of_attraction.cc, line 108 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16704#-MxZhlwy0O_2j8Kil-5L:-MxbORLn6hyh4VB6c0Qc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b62aa64aaf8aade67fc3c7bfbcdbc3618e4df1a/systems/analysis/region_of_attraction.cc#L108)):*
<details><summary><i>Previously, shensquared (Shen Shen) wrote…</i></summary><blockquote>

code is  using **_+_** Lambda_g * g instead of minus (either is correct course, just might be confusing.)
</blockquote></details>

Done.

**Comment by RussTedrake** [comment]
Merging.

**Pull request merged**
