### PR TITLE
Add type to symbolic variable

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6101)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
Reviewed 3 of 10 files at r1.
Review status: 3 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/common/symbolic_expression.h, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCI2WotcrnkI6_lZn6:-KkCI2WotcrnkI6_lZn7:b-qaps7t) ([raw file](https://github.com/robotlocomotion/drake/blob/04c1b511b8470e5a74f4749072e87742a2b1b130/drake/common/symbolic_expression.h#L175)):*
> ```objc
>   Expression(double d);
>   /** Constructs a variable expression from Variable.
>    * @note Variable @p var should be of either CONTINUOUS type or INTEGER type.
> ```

Why the BINARY type is not allowed here?

---

*[drake/common/symbolic_variable.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCHcAVTDm2hOTEH2Oc:-KkCHcAVTDm2hOTEH2Od:blu5s14) ([raw file](https://github.com/robotlocomotion/drake/blob/04c1b511b8470e5a74f4749072e87742a2b1b130/drake/common/symbolic_variable.cc#L55)):*
> ```cpp
>       return os << "Binary";
>     case Variable::Type::INTEGER:
>       return os << "Integer";
> ```

Add a default case and throw an error, in case in the future we append some more type to `Variable::Type`, but forgot to update this function? Like
```C++
default:
  throw std::runtime_error("Unknown type");
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by soonho-tri** [comment]
Review status: 3 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/common/symbolic_expression.h, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCI2WotcrnkI6_lZn6:-KkCIXgweOl5UHtOCXva:b-zf48nw) ([raw file](https://github.com/robotlocomotion/drake/blob/04c1b511b8470e5a74f4749072e87742a2b1b130/drake/common/symbolic_expression.h#L175)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why the BINARY type is not allowed here?
</blockquote></details>

Just realized that we still need to support this in Expression. I'll relax the condition!

---

*[drake/common/symbolic_variable.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCHcAVTDm2hOTEH2Oc:-KkCIf82l6uIfg5eEFlT:b-rqhu7t) ([raw file](https://github.com/robotlocomotion/drake/blob/04c1b511b8470e5a74f4749072e87742a2b1b130/drake/common/symbolic_variable.cc#L55)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Add a default case and throw an error, in case in the future we append some more type to `Variable::Type`, but forgot to update this function? Like
```C++
default:
  throw std::runtime_error("Unknown type");
```
</blockquote></details>

I'll add it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/symbolic_variable.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCHcAVTDm2hOTEH2Oc:-KkCJ1bFAnqsDkhZpNgs:b-jjh0zt) ([raw file](https://github.com/robotlocomotion/drake/blob/04c1b511b8470e5a74f4749072e87742a2b1b130/drake/common/symbolic_variable.cc#L55)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'll add it.
</blockquote></details>

FYI Adding a `default` case is an anti-pattern.  It will turn compile-time errors into runtime errors.  Try adding a new enum type now (without a `default`) and see what happens.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by hongkai-dai** [comment]
Reviewed 7 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by soonho-tri** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_variable.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCHcAVTDm2hOTEH2Oc:-KkCJXSWigNMHesYrToB:bqa8ybf) ([raw file](https://github.com/robotlocomotion/drake/blob/04c1b511b8470e5a74f4749072e87742a2b1b130/drake/common/symbolic_variable.cc#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Adding a `default` case is an anti-pattern.  It will turn compile-time errors into runtime errors.  Try adding a new enum type now (without a `default`) and see what happens.
</blockquote></details>

@jwnimmer-tri is right. A compiler (at least clang>=3.9) detects an uncovered case for `enum class` and generates an error for that.

However, we need the following `DRAKE_ABORT` for `gcc-4.9`. 

---

*[drake/common/symbolic_expression.h, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCI2WotcrnkI6_lZn6:-KkCLXuiethA0MmsT_DY:btppmo6) ([raw file](https://github.com/robotlocomotion/drake/blob/04c1b511b8470e5a74f4749072e87742a2b1b130/drake/common/symbolic_expression.h#L175)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Just realized that we still need to support this in Expression. I'll relax the condition!
</blockquote></details>

Done. (This file is not changed anymore)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by soonho-tri** [comment]
@jwnimmer-tri , we had another option to have `Variable<double/int/bool>`. But @hongkai-dai and I decided not to go to that direction because there are many use-cases in MathematicalProgram where we need a vector of variables with different types.

+@hongkai-dai , feature-review please.

---

Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-:-KkCLxbJth7Qe0GnYHpX:bu6bvjm)*

**Comment by hongkai-dai** [comment]
:lgtm: +@jwnimmer-tri for platform review please.

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-:-KkCQ-GK0vpFM3HQ73LA:b-os5xp3)*

**Comment by jwnimmer-tri** [comment]
:lgtm: pending discussions

---

Reviewed 6 of 10 files at r1, 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_variable.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCkD5uWmMKwjbZMr9G:-KkCkD5uWmMKwjbZMr9H:b-swjwgs) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/common/symbolic_variable.h#L23)):*
> ```objc
> 
>   /** Supported types of symbolic variables. */
>   enum class Type { CONTINUOUS, INTEGER, BINARY };
> ```

Missing API comments on the semantics of each of the three choices.

---

*[drake/common/test/symbolic_variable_test.cc, line 173 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkClD0sgm03BgVCruf8:-KkClD0sgm03BgVCruf9:b1eln63) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/common/test/symbolic_variable_test.cc#L173)):*
> ```cpp
> }
> 
> TEST_F(VariableTest, CheckType) {
> ```

BTW Do you want to enforce `Variable{}.get_type() == CONTINUOUS` with any test?

---

*[drake/common/test/symbolic_variable_test.cc, line 187 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkClMBJB_rOVmGbNRPM:-KkClMBJB_rOVmGbNRPN:b-3d7yv1) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/common/test/symbolic_variable_test.cc#L187)):*
> ```cpp
>   EXPECT_EQ(v4.get_type(), Variable::Type::INTEGER);
> }
> }  // namespace
> ```

Probably worth adding test case(s) that variables of same name but different type are unequal?

---

*[drake/solvers/mathematical_program.h, line 2128 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCVtxGjfsbKZiXSTIn:-KkCVtxGjfsbKZiXSTIo:byfin22) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/solvers/mathematical_program.h#L2128)):*
> ```objc
>         required_capabilities_ |= kBinaryVariable;
>         break;
>       default:
> ```

FYI Do you want to add some TODOs about bad use of `default:`?

---

*[drake/solvers/mosek_solver.cc, line 557 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCjX1Uj5x80e7sgld1:-KkCjX1V3kZLHGlmB-it:b-187ne9) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/solvers/mosek_solver.cc#L557)):*
> ```cpp
>         }
>       }
>     }
> ```

FYI Is there any fail-fast for variables of incorrect type?  Should this code use a `switch` (or at least have a TODO)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-:-KkClXrirEA_-w3BQIWj:bktlvn7)*

**Comment by soonho-tri** [comment]
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_variable.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCkD5uWmMKwjbZMr9G:-KkGXTd2ss75n4gUDFmp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/common/symbolic_variable.h#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing API comments on the semantics of each of the three choices.
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_variable_test.cc, line 173 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkClD0sgm03BgVCruf8:-KkGXTEdJc1yo_4rvu5W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/common/test/symbolic_variable_test.cc#L173)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Do you want to enforce `Variable{}.get_type() == CONTINUOUS` with any test?
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_variable_test.cc, line 187 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkClMBJB_rOVmGbNRPM:-KkGdKac-gsvOBb8W7-O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/common/test/symbolic_variable_test.cc#L187)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Probably worth adding test case(s) that variables of same name but different type are unequal?
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 2128 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCVtxGjfsbKZiXSTIn:-KkGY09_FExq3FnNACPv:b9zn7y1) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/solvers/mathematical_program.h#L2128)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Do you want to add some TODOs about bad use of `default:`?
</blockquote></details>

Done.

Removed `default:` and added a case for `INTEGER`.

---

*[drake/solvers/mosek_solver.cc, line 557 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkCjX1Uj5x80e7sgld1:-KkGcZEUhdL7M-eXR4rI:bbuemsy) ([raw file](https://github.com/robotlocomotion/drake/blob/88af2bc0154976b85f1bf7036ec78dc0af32065e/drake/solvers/mosek_solver.cc#L557)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Is there any fail-fast for variables of incorrect type?  Should this code use a `switch` (or at least have a TODO)?
</blockquote></details>

Done.

Changed the code to use `switch`. @hongkai-dai , could you review the changes here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 4 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/common/symbolic_variable.h, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGkUMUw8wbARbQImjF:-KkGkUMUw8wbARbQImjG:b-72zzdw) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/common/symbolic_variable.h#L24)):*
> ```objc
>   /** Supported types of symbolic variables. */
>   enum class Type {
>     CONTINUOUS,  ///< continuous variable
> ```

Is there a citation for how the concepts `continuous` and `real number` differ?

---

*[drake/common/symbolic_variable.h, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGkOGCxDyQfg6ntaHF:-KkGkOGDS_cPBkc4eGFy:bcp1uah) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/common/symbolic_variable.h#L26)):*
> ```objc
>     CONTINUOUS,  ///< continuous variable
>     INTEGER,     ///< integer variable
>     BINARY       ///< binary variable
> ```

So all values must be given as `00101001`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by soonho-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_variable.h, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGkUMUw8wbARbQImjF:-KkGlMibkSn5GTFXT5zX:b85u430) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/common/symbolic_variable.h#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is there a citation for how the concepts `continuous` and `real number` differ?
</blockquote></details>

I prefer `REAL` but keep `CONTINUOUS` to be compatible with existing code in MathematicalProgram.

---

*[drake/common/symbolic_variable.h, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGkOGCxDyQfg6ntaHF:-KkGl_vruXIrOyzfCTJQ:b-9k286q) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/common/symbolic_variable.h#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So all values must be given as `00101001`?
</blockquote></details>

A binary variable `b` is an integer variable with a restricted domain {0, 1}.

I'll update the documentation part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/symbolic_variable.h, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGkUMUw8wbARbQImjF:-KkGqql6IBjkd9R37Klb:b-h4tpjr) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/common/symbolic_variable.h#L24)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I prefer `REAL` but keep `CONTINUOUS` to be compatible with existing code in MathematicalProgram.
</blockquote></details>

My point is that this enum seems like the fundamental place in Drake where we define these concepts, so they deserve at least a sentence, if not a paragraph with links to literature or something.

I guess this PR is just _moving_ things, so a TODO would be okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/solvers/mosek_solver.cc, line 530 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGrQmpA84ClBURrRLz:-KkGrQmpA84ClBURrRM-:bhh85mw) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/solvers/mosek_solver.cc#L530)):*
> ```cpp
>   for (int i = 0; i < num_vars && rescode == MSK_RES_OK; ++i) {
>     switch (prog.decision_variable(i).get_type()) {
>       case MathematicalProgram::VarType::INTEGER:
> ```

When one case body (BINARY) uses curlies, all of them must, per cppguide.  Ditto for CONTINUOUS below.

---

*[drake/solvers/mosek_solver.cc, line 560 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGrJhaigbuL5OOlY8o:-KkGrJhbE7rh4e0SaGY9:b-io6i05) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/solvers/mosek_solver.cc#L560)):*
> ```cpp
>       }
>       case MathematicalProgram::VarType::CONTINUOUS:
>         // Do nothing. */
> ```

BTW nit Weird end-comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by soonho-tri** [comment]
I was thinking about introducing `BINARY` type and using it to represent two different cases:

 - an integer variable with a restricted domain `{0, 1}`.
 - a Boolean variable whose domain is `{true, false}`.

However, it's actually a bad design and now I think it's clearer to have both of `BINARY` and `BOOLEAN` as types. It's because we need different sets of operator overloading for each. 

 - For a `BINARY` variable, we need to provide arithmetic operators (`+`, `-`, `*`, `/`).
 - For a `BOOLEAN` variable, we need to provide logical operators (`!`, `&&`, `||`)

---

Review status: 2 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_variable.h, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGkOGCxDyQfg6ntaHF:-KkHtdEJ5cPp_O1dJehG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/common/symbolic_variable.h#L26)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

A binary variable `b` is an integer variable with a restricted domain {0, 1}.

I'll update the documentation part.
</blockquote></details>

Done.

---

*[drake/solvers/mosek_solver.cc, line 530 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGrQmpA84ClBURrRLz:-KkH4R1xVpo55qLw3oQW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/solvers/mosek_solver.cc#L530)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When one case body (BINARY) uses curlies, all of them must, per cppguide.  Ditto for CONTINUOUS below.
</blockquote></details>

Done.

---

*[drake/solvers/mosek_solver.cc, line 560 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGrJhaigbuL5OOlY8o:-KkH4ROYvmwz8NQcUHM4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/solvers/mosek_solver.cc#L560)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit Weird end-comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-:-KkHtCNXMPCLZHgNQDWz:b-rzqgc5)*

**Comment by soonho-tri** [comment]
Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_variable.h, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkGkUMUw8wbARbQImjF:-KkHtjMRetu52YG63v1W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6115bf3a1076cb0a5177e5cdf5b962756549a86/drake/common/symbolic_variable.h#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My point is that this enum seems like the fundamental place in Drake where we define these concepts, so they deserve at least a sentence, if not a paragraph with links to literature or something.

I guess this PR is just _moving_ things, so a TODO would be okay.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by soonho-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_variable_test.cc, line 183 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6101#-KkHu3aizy-7ZNpUDo__:-KkI9dWkxowADnBDDqwh:bu9g7cx) ([raw file](https://github.com/robotlocomotion/drake/blob/50a669047e4f4c04d05c36ece85828463fefff9d/drake/common/test/symbolic_variable_test.cc#L183)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI These string names are weird, but I guess no problem.
</blockquote></details>

Done. Thanks for catching them!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6101)*

**Pull request merged**
