### PR TITLE
ParseConstraint ignores formula being always true.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in https://github.com/RobotLocomotion/drake/pull/16761#pullrequestreview-911095580

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854#-:-MywShLO2zjCF-Ga638H:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854#-:-Mywdkpj5tf6daJSxZW3:b-n37teh)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/create_constraint.h, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16854#-Mywa2gHC3CSO5W-Zwk2:-Mywa2gI2lo01oy-2n8F:b-7l81i0) ([raw file](https://github.com/robotlocomotion/drake/blob/8859fac15522af8c4af5048d8f8d3cbac2fe813a/solvers/create_constraint.h#L60)):*
> ```objc
>  * Creates a constraint that should satisfy the formula `f`.
>  * @throws exception if `f` is always false (for example 1 >= 2).
>  * @note if `f` is always true, then return an empty BoundingBoxConstraint
> ```

nit GSG verb mood.

Ditto throughout.



_Suggestion:_
```objc
returns
```
___
*[solvers/create_constraint.cc, line 453 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywbDDh6IX1p0d6Auif:-MywbDDh6IX1p0d6Auig:b-pncqm1) ([raw file](https://github.com/robotlocomotion/drake/blob/8859fac15522af8c4af5048d8f8d3cbac2fe813a/solvers/create_constraint.cc#L453)):*
> ```cpp
>         std::make_shared<LinearEqualityConstraint>(
>             Eigen::Matrix<double, 0, 0>(), Eigen::Matrix<double, 0, 1>()),
>         Eigen::Matrix<symbolic::Variable, 0, 1>());
> ```

nit The constructor spelling for this empty LinearEqualityConstraint constructor differs from the one about 15 lines above.  If they are purposefully different, we might need a comment to explain, since I'm unable to figure out why they differ.  If they are different for no reason, then we should change them to be the same.

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854#-:-Mywgtk1CwFuqAFlKDD9:bi4se7j)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with some small nits - nice!

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854#-:-Mywj2949Uu_06JqFKAS:b-gd3a98)* status: 6 unresolved discussions (waiting on @hongkai-dai)

___
*[solvers/create_constraint.h, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywiyafDdc1Sl4skC2X:-MywiyafDdc1Sl4skC2Y:bv2emwn) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.h#L60)):*
> ```objc
>  * Creates a constraint that should satisfy the formula `f`.
>  * @throws exception if `f` is always false (for example 1 >= 2).
>  * @note if `f` is always true, then returns an empty BoundingBoxConstraint
> ```

nit grammar "then *this* returns"
___
*[solvers/create_constraint.h, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-Mywiwgj4WlezNQFXYyx:-Mywiwgj4WlezNQFXYyy:bv2emwn) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.h#L69)):*
> ```objc
>  * @throws exception if any of `formulas` is always false (for example 1 >= 2).
>  * @note If any entry in `formulas` is always true, then that entry is ignored.
>  * If all entries in `formulas` are true, then returns an empty
> ```

nit grammar "then *this* returns"
___
*[solvers/create_constraint.h, line 95 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywiuNG-Hhyp4EJ1_Kn:-MywiuNG-Hhyp4EJ1_Ko:bv2emwn) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.h#L95)):*
> ```objc
>  * @throws exception if any of `formulas` is always false (for example 1 == 2)
>  * @note If any entry in `formulas` is always true, then that entry is ignored;
>  * if all entries in `formulas` are always true, then returns an empty linear
> ```

nit grammar "then *this* returns"
___
*[solvers/create_constraint.h, line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywiqsM3rzK0CWtwb64:-MywiqsM3rzK0CWtwb65:bv2emwn) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.h#L105)):*
> ```objc
>  * Creates a linear equality constraint satisfying the formula `f`.
>  * @throws exception if `f` is always false (for example 1 == 2)
>  * @note if `f` is always true, then returns an empty linear equality constraint
> ```

nit grammar "then *this* returns"
___
*[solvers/create_constraint.cc, line 434 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywiNcm7oW4PVi5v94p:-MywiNcm7oW4PVi5v94q:b-ecl66) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.cc#L434)):*
> ```cpp
>   }
>   if (i == 0) {
>     return internal::CreateBinding(
> ```

nit Logic not immediately clear to naive onlooker (myself).

Consider adding comment, similar to what you did above:
```
// Create a no-op constraint given all formulas are unconditionally true.
```
___
*[solvers/create_constraint.cc, line 450 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywigD9Cwhh2BYMOmp3:-MywigD9Cwhh2BYMOmp4:b-ix42zs) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.cc#L450)):*
> ```cpp
>   }
>   if (symbolic::is_true(f)) {
>     return internal::CreateBinding(
> ```

nit Similar to above, consider adding comment here.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854)* status: 6 unresolved discussions (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[solvers/create_constraint.h, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywiyafDdc1Sl4skC2X:-MywjMfrEfKWsdh65C-0:b-10oedd) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.h#L60)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit grammar "then *this* returns"
</blockquote></details>

We don't open the API comment with "This creates a constraint..." we just say "Creates a constraint".  An implied "this" is pretty common in API docs, I don't think we need to nitpick this one?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854)* status: 4 unresolved discussions (waiting on @EricCousineau-TRI and @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @hongkai-dai)

___
*[solvers/create_constraint.h, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywiyafDdc1Sl4skC2X:-Myx7eiB2Ow8I0zkLQIz:bnl9g4s) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.h#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We don't open the API comment with "This creates a constraint..." we just say "Creates a constraint".  An implied "this" is pretty common in API docs, I don't think we need to nitpick this one?
</blockquote></details>

OK SGTM
___
*[solvers/create_constraint.h, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-Mywiwgj4WlezNQFXYyx:-Myx7fS4C_3O2DdDKktB:bnl9g4s) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.h#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit grammar "then *this* returns"
</blockquote></details>

OK SGTM
___
*[solvers/create_constraint.h, line 95 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywiuNG-Hhyp4EJ1_Kn:-Myx7g0oEcP_rLl3jek-:bnl9g4s) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.h#L95)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit grammar "then *this* returns"
</blockquote></details>

OK SGTM
___
*[solvers/create_constraint.h, line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16854#-MywiqsM3rzK0CWtwb64:-Myx7gaCBr88wJUPkxzM:bnl9g4s) ([raw file](https://github.com/robotlocomotion/drake/blob/e6186ca8d6d3dd4247d936b8c31fb58f86483858/solvers/create_constraint.h#L105)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit grammar "then *this* returns"
</blockquote></details>

OK SGTM

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16854)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
