### PR TITLE
Increased size of cylinder_torque_free_analytical_solution

### PR DESCRIPTION
**Pull request by liangfok**
This is an attempt to diagnose #5611.

Reslolves #5611.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5612)

### CODE REVIEW

**Comment by sherm1** [comment]
Thanks @liangfok. @mitiguy is out until Monday afternoon.

**Comment by sherm1** [comment]
:lgtm: (in case this works, to avoid revert)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5612#-:-Kg02vtFLgOauoQFrATV:b2s622f)*

**Comment by sherm1** [comment]
@liangfok -- is the ros failure related?

**Comment by liangfok** [comment]
No, that error was due to #3429.

@drake-jenkins-bot linux-gcc-experimental-ros please.

I started this CI run to test in debug mode: https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab-ros/72/

**Comment by liangfok** [comment]
Oops, looks like my previous test-run failed because enormous tests are not enabled:

```
[drake:make] -- Not running cylinder_torque_free_analytical_solution because enormous tests are not enabled
12:24:03 
```

Trying again: https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab-ros/73/

**Comment by sherm1** [comment]
@liangfok, is there an equivalent adjustment needed for the BUILD file also?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5612#-:-Kg0Q3OF4oh7X_-pm-0S:bp9mxk5)*

**Comment by liangfok** [comment]
Not in this case since ROS only uses the CMake-version of Drake, and the timeout appears to only be happening in the ROS-based CI.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5612#-:-Kg0QPIjVhDfhLBw1isg:bsbxj5p)*

**Comment by liangfok** [comment]
Looks like large tests are also not enabled:

```
[drake:make] -- Not running cylinder_torque_free_analytical_solution because large tests are not enabled
13:34:33 
```

Running the test on my local workstation, it takes 51.2 seconds to complete:

```
$ ctest -VV -R cylinder_torque_free_analytical_solution
UpdateCTestConfiguration  from :/home/liang/dev/drake_catkin_workspace/build/drake/drake/DartConfiguration.tcl
Parse Config file:/home/liang/dev/drake_catkin_workspace/build/drake/drake/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/liang/dev/drake_catkin_workspace/build/drake/drake/DartConfiguration.tcl
Parse Config file:/home/liang/dev/drake_catkin_workspace/build/drake/drake/DartConfiguration.tcl
Test project /home/liang/dev/drake_catkin_workspace/build/drake/drake
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 66
    Start 66: cylinder_torque_free_analytical_solution

66: Test command: /home/liang/dev/drake_catkin_workspace/build/drake/drake/multibody/benchmarks/cylinder_torque_free_analytical_solution/test/cylinder_torque_free_analytical_solution
66: Test timeout computed to be: 60
66: Running main() from gtest_main.cc
66: [==========] Running 1 test from 1 test case.
66: [----------] Global test environment set-up.
66: [----------] 1 test from uniformSolidCylinderTorqueFree
66: [ RUN      ] uniformSolidCylinderTorqueFree.testA
66: [       OK ] uniformSolidCylinderTorqueFree.testA (51147 ms)
66: [----------] 1 test from uniformSolidCylinderTorqueFree (51147 ms total)
66: 
66: [----------] Global test environment tear-down
66: [==========] 1 test from 1 test case ran. (51147 ms total)
66: [  PASSED  ] 1 test.
1/1 Test #66: cylinder_torque_free_analytical_solution ...   Passed   51.17 sec

The following tests passed:
	cylinder_torque_free_analytical_solution

100% tests passed, 0 tests failed out of 1

Label Time Summary:
small    =  51.17 sec (1 test)

Total Test time (real) =  51.20 sec
```

I'm thus going to try to set the size of this test to "medium".
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab-ros/74/

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5612#-:-Kg0VkGvRZhi8B7QvEEd:b-n4gr2c)*

**Comment by SeanCurtis-TRI** [comment]
I'll ask the inevitable question: since this particular test/benchmark has nothing to do with ROS, is omitting it implicitly from the ROS environment inherently bad?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5612#-:-Kg0YQO4OeMy4DP-yevP:b-cvszua)*

**Comment by liangfok** [comment]
That is another option, though the same argument could be made for most unit tests in Drake. Let's see how the "medium" test works. If it passes, we might as well just merge and close the revert PR.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5612#-:-Kg0_3KUEhiOgDJu8BdR:bu9wdrh)*

**Comment by SeanCurtis-TRI** [comment]
Amen.  This week's build cop seems to be all about tests that time out.  We've already excluded one test from mac evaluation entirely.  :)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5612#-:-Kg0a1etMjHNeEMvvoPA:bjmrypm)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5612)*

**Comment by liangfok** [comment]
The unit test passed in the ROS-debug CI run after 97.04 seconds:

```
14:34:47 313/655 Test  #66: cylinder_torque_free_analytical_solution ..............................................   Passed   97.04 sec
```
I believe this PR should now be merged to fix CI.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5612#-:-Kg0wk04A6jI7PpgYQ3k:b-3nwm3r)*

**Comment by sherm1** [comment]
Thanks, @liangfok!

**Pull request merged**
