### PR TITLE
Add methods to evaluate a binding in a program.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8161)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-:-L63fWqlwvrf9Ke4sp8z:bvhsv4m)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items. Thanks!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2313 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L63omNNaczJmgkW-Ec9:-L63omNOeTbdF7VNmMzm:bh0peza) ([raw file](https://github.com/robotlocomotion/drake/blob/05a3d2e2001a446a72c218e53de9da0a1d9e9eb2/solvers/mathematical_program.h#L2313)):*
> ```objc
> 
>   /**
>    * Evaluates the value of some constraint, for some input value for all
> ```

Can you replace `constraint` with `binding`? (since it looks like this would work for both `Cost` and `Constraint`?)

---

*[solvers/test/mathematical_program_test.cc, line 2703 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L63oy8XOktF37Ii9Cq4:-L63oy8XOktF37Ii9Cq5:b-24ekf6) ([raw file](https://github.com/robotlocomotion/drake/blob/05a3d2e2001a446a72c218e53de9da0a1d9e9eb2/solvers/test/mathematical_program_test.cc#L2703)):*
> ```cpp
>   // The linear constraint should evaluate to 5.
>   // The quadratic constraint should evaluate to 30.
>   EXPECT_TRUE(CompareMatrices(prog.EvalBinding(linear_constraint, x_val),
> ```

Can you add a test for evaluating a cost as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-:-L63p4Ur_V3HsWLTQv6W:b-lte0wg)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/test/mathematical_program_test.cc, line 2710 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L63pRBdFtVyhs9eEx4n:-L63pRBe2DJLMS7rN3q5:bl0w0pr) ([raw file](https://github.com/robotlocomotion/drake/blob/05a3d2e2001a446a72c218e53de9da0a1d9e9eb2/solvers/test/mathematical_program_test.cc#L2710)):*
> ```cpp
> 
>   // Pass in an incorrect size input.
>   EXPECT_THROW(prog.EvalBinding(linear_constraint, Eigen::Vector2d::Zero()),
> ```

Can you also test a Binding which has variables which are not registered in the problem?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8161)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2313 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L63omNNaczJmgkW-Ec9:-L647pwBoyxvVqkNQ095:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/05a3d2e2001a446a72c218e53de9da0a1d9e9eb2/solvers/mathematical_program.h#L2313)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you replace `constraint` with `binding`? (since it looks like this would work for both `Cost` and `Constraint`?)
</blockquote></details>

Done.

---

*[solvers/test/mathematical_program_test.cc, line 2703 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L63oy8XOktF37Ii9Cq4:-L648LZtftG3SBESeNcu:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/05a3d2e2001a446a72c218e53de9da0a1d9e9eb2/solvers/test/mathematical_program_test.cc#L2703)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you add a test for evaluating a cost as well?
</blockquote></details>

Done. Good call.

---

*[solvers/test/mathematical_program_test.cc, line 2710 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L63pRBdFtVyhs9eEx4n:-L64BChp55rBW1wERnNt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/05a3d2e2001a446a72c218e53de9da0a1d9e9eb2/solvers/test/mathematical_program_test.cc#L2710)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you also test a Binding which has variables which are not registered in the problem?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-:-L64BFBKiZPN_K2CIscB:b6vi582)*

**Comment by sherm1** [comment]
Platform :lgtm: with a few minor comments, ptal.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2328 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L64WCNIHJUTuC0c-urE:-L64WCNIHJUTuC0c-urF:b-ywmkzk) ([raw file](https://github.com/robotlocomotion/drake/blob/a5be670f1acba7c560d574b64f0557e35c3335ce/solvers/mathematical_program.h#L2328)):*
> ```objc
>     if (prog_var_vals.rows() != num_vars()) {
>       std::ostringstream oss;
>       oss << "The input binding variable is not in the right size. Expect "
> ```

BTW Expect -> Expected

---

*[solvers/mathematical_program.h, line 2331 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L64Xk0blxFO5KmLKgP7:-L64Xk0blxFO5KmLKgP8:b-u0ipwt) ([raw file](https://github.com/robotlocomotion/drake/blob/a5be670f1acba7c560d574b64f0557e35c3335ce/solvers/mathematical_program.h#L2331)):*
> ```objc
>           << num_vars() << " rows, but it actually has " << prog_var_vals.rows()
>           << " rows.\n";
>       throw std::runtime_error(oss.str());
> ```

FYI I would use `std::logic_error` here since the EvalBinding() method is being misused by a programmer (so should be fixed in the calling program). `std::runtime_error` is for errors that _can't_ be fixed in a program, such as errors due to a malformatted file supplied by the user at run time. (We have not been strict about this in Drake so far so it's not a defect to use runtime_error here.)

---

*[solvers/test/mathematical_program_test.cc, line 2704 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L64XW4bD7kZagIaqEiX:-L64XW4bD7kZagIaqEiY:b-63pcag) ([raw file](https://github.com/robotlocomotion/drake/blob/a5be670f1acba7c560d574b64f0557e35c3335ce/solvers/test/mathematical_program_test.cc#L2704)):*
> ```cpp
>   // The linear constraint should evaluate to 5.
>   // The quadratic constraint should evaluate to 30.
>   // The quadratic sots should evaluate to 7.
> ```

BTW sots -> cost?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-:-L64YJzvOXaJPadM-pkW:b-cb983t)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2328 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L64WCNIHJUTuC0c-urE:-L65H59K0dP7vghojTiZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a5be670f1acba7c560d574b64f0557e35c3335ce/solvers/mathematical_program.h#L2328)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Expect -> Expected
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 2331 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L64Xk0blxFO5KmLKgP7:-L65H7s0A-gp4P6nR73K:b-v130gt) ([raw file](https://github.com/robotlocomotion/drake/blob/a5be670f1acba7c560d574b64f0557e35c3335ce/solvers/mathematical_program.h#L2331)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI I would use `std::logic_error` here since the EvalBinding() method is being misused by a programmer (so should be fixed in the calling program). `std::runtime_error` is for errors that _can't_ be fixed in a program, such as errors due to a malformatted file supplied by the user at run time. (We have not been strict about this in Drake so far so it's not a defect to use runtime_error here.)
</blockquote></details>

I see, so I have been using `std::runtime_error` incorrectly in all my code. Thanks for the correction!

---

*[solvers/test/mathematical_program_test.cc, line 2704 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8161#-L64XW4bD7kZagIaqEiX:-L65HW7vqslxa_EvpomA:bgxamu) ([raw file](https://github.com/robotlocomotion/drake/blob/a5be670f1acba7c560d574b64f0557e35c3335ce/solvers/test/mathematical_program_test.cc#L2704)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW sots -> cost?
</blockquote></details>

Done. Hmm I really have some typing problem today.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8161)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8161)*

**Pull request merged**
