### PR TITLE
New joint design

### PR DESCRIPTION
**Pull request by tkoolen**
The new joint design according to https://github.com/RobotLocomotion/drake/issues/2235

Please let me know what you think.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2267)

### CODE REVIEW

**Comment by david-german-tri** [comment]
From a high level, I think this is beautiful.  The only substantive question I have is about test coverage - at first glance, it looks like there's a bunch of behavior in the specific joints without corresponding tests.  This may be easiest to address by reducing this code review to just the interface and a very simple concrete Joint (FixedJoint?), and adding the other joints in a series of follow-up PRs.  I pledge to review them quickly - probably more quickly than one 1000+ line PR.  But I leave it up to you.

I also have an assortment of minor style-guide things to point out, but we should probably wait for +@amcastro-tri to chime in before diving into those.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-:-KGxhZ6nRegtAsAh9msz:38311342)*

**Comment by tkoolen** [comment]
I'm going to push back on that a little bit, sorry. If you want to split this pull request up into multiple pull requests, feel free to do so; I feel that's unnecessarily burdensome for me.
What parts do you think need more testing? There's some trivial getters that I don't need testing, granted maybe the FrictionTorque method that I straight up copied from DrakeJoint, but I think that's it.
I'll be out of the office tomorrow by the way.

**Comment by david-german-tri** [comment]
Just to confirm, if someone else accidentally changes the behavior of one of those untested getters in the future, it's fine with you that CI won't catch it?

Added a few comments on non-getter things that I think might also not be tested.

---

Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h, line 44 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGy4nPHwQdN--okfQlU:-KGy4nPI_zJOXSfajc-I:1998976783) ([raw file](https://github.com/robotlocomotion/drake/blob/e62de98809f5c249e130c4d12c83c287dd255329/drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h#L44)):*
as you mentioned, this isn't tested

---

*[drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGy4s530AUX-eQ0HGOq:-KGy4s530AUX-eQ0HGOr:1335019861) ([raw file](https://github.com/robotlocomotion/drake/blob/e62de98809f5c249e130c4d12c83c287dd255329/drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h#L46)):*
as an aside, I think this is out-of-date?

---

*[drake/multibody_dynamics/joints/RollPitchYawFloatingJoint.h, line 76 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGy3fr0p2INRgMv9hKZ:-KGy3fr0p2INRgMv9hK_:1801605285) ([raw file](https://github.com/robotlocomotion/drake/blob/e62de98809f5c249e130c4d12c83c287dd255329/drake/multibody_dynamics/joints/RollPitchYawFloatingJoint.h#L76)):*
I may be missing it, but I don't think this function is exercised from the test cases.

---

*[drake/multibody_dynamics/joints/test/joint_test.cc, line 42 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGy4L31ViwavgWTwE03:-KGy4L31ViwavgWTwE04:-1457405867) ([raw file](https://github.com/robotlocomotion/drake/blob/e62de98809f5c249e130c4d12c83c287dd255329/drake/multibody_dynamics/joints/test/joint_test.cc#L42)):*
Do these have any properties of importance beyond that they're inverses?

---

*[drake/multibody_dynamics/joints/test/joint_test.cc, line 51 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGyAUnzZ4rXq2aLGxOH:-KGyAUnzZ4rXq2aLGxOI:1069961909) ([raw file](https://github.com/robotlocomotion/drake/blob/e62de98809f5c249e130c4d12c83c287dd255329/drake/multibody_dynamics/joints/test/joint_test.cc#L51)):*
Same question here, and I really don't know the answer - is this sufficient to prove that the JointTransform is correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-:-KGy50rvWN0QDxblgigg:1366711869)*

**Comment by tkoolen** [comment]
I personally don't see the point in testing that e.g. GetName actually returns the name property, and I'm not the only person in the world with that opinion. If you feel otherwise, feel free to submit a pull request against this branch with additional tests.

Also please keep in mind that I am not a paid TRI software engineer. I'm doing this for fun and to help fellow students.

---

Review status: 0 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGy4s530AUX-eQ0HGOq:-KGyJ7t0mt_u1aEdPZAb:-685994332) ([raw file](https://github.com/robotlocomotion/drake/blob/e62de98809f5c249e130c4d12c83c287dd255329/drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h#L46)):*
Ah yes, it is. Fixed.

---

*[drake/multibody_dynamics/joints/RollPitchYawFloatingJoint.h, line 76 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGy3fr0p2INRgMv9hKZ:-KGyJNhrFXPuZWKjXtur:-2017709435) ([raw file](https://github.com/robotlocomotion/drake/blob/e62de98809f5c249e130c4d12c83c287dd255329/drake/multibody_dynamics/joints/RollPitchYawFloatingJoint.h#L76)):*
Yeah, that one is missing, true. Fixed.

---

*[drake/multibody_dynamics/joints/test/joint_test.cc, line 42 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGy4L31ViwavgWTwE03:-KGyJUsiA_VCCsrkdLWR:-607811070) ([raw file](https://github.com/robotlocomotion/drake/blob/e62de98809f5c249e130c4d12c83c287dd255329/drake/multibody_dynamics/joints/test/joint_test.cc#L42)):*
They're also exercised in the last of those three test cases. I'd be surprised if you could change one of these methods without a test case breaking.

---

*[drake/multibody_dynamics/joints/test/joint_test.cc, line 51 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGyAUnzZ4rXq2aLGxOH:-KGyJmBAC3YjtSp7vhja:981359391) ([raw file](https://github.com/robotlocomotion/drake/blob/e62de98809f5c249e130c4d12c83c287dd255329/drake/multibody_dynamics/joints/test/joint_test.cc#L51)):*
I would say so, yes. I guess you could test some special cases for specific joints, but  even with the current tests I think it would not be possible to change MotionSubspace or JointTransform individually without breaking a test case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-:-KGyKYV5BIHIjaRsv8ui:-1299696232)*

**Comment by liangfok** [comment]
I agree that volunteers should not be held to the same level of rigor as full-time paid professionals. I recommend taking one of two routes:

1. Merge this PR but create an issue for each unaddressed review comment.
2. Transfer the source branch to someone who will address all review comments.

General comments:
1. There are many new files in this PR. Since they are new, their names should abide by the style guide, e.g., "joint.h" instead of "Joint.h"
2. There are many methods in need of more Doxygen comments. For example, it was not obvious to me what is a "postfix".
3. `#define` header guards should be replaced by `@pragma once`.
4. `TODO` should be `TODO(name of developer)`
5. Should run `cpplint` and `clang-format` on this code just in case.

---

Reviewed 11 of 14 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/multibody_dynamics/joints/Joint.h, line 65 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGyZClavQtOn0eyfStT:-KGyZClavQtOn0eyfStU:-1917003813) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/Joint.h#L65)):*
It's not clear what a name "postfix" means. Doxygen explanation required.

---

*[drake/multibody_dynamics/joints/Joint.h, line 67 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGyZQO7x-MJO2-iDQj4:-KGyZQO7x-MJO2-iDQj5:-604919019) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/Joint.h#L67)):*
Needs doxygen comment explaining what "postfix" means in this context.

---

*[drake/multibody_dynamics/joints/PrismaticJoint.h, line 35 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGye_n4_q-4-5nLmvP6:-KGye_n4_q-4-5nLmvP7:186225110) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/PrismaticJoint.h#L35)):*
`}  // namespace drake`

---

*[drake/multibody_dynamics/joints/QuaternionFloatingJoint.h, line 137 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGyeLBrIEkQ4CRdYT62:-KGyeLBrIEkQ4CRdYT63:186225110) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/QuaternionFloatingJoint.h#L137)):*
`}  // namespace drake`

---

*[drake/multibody_dynamics/joints/RevoluteJoint.h, line 33 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGyeGTvB13SRWIe_HNF:-KGyeGTvB13SRWIe_HNG:186225110) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/RevoluteJoint.h#L33)):*
`}  // namespace drake`

---

*[drake/multibody_dynamics/joints/RollPitchYawFloatingJoint.h, line 132 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGye9zlYmpFytvPfW1p:-KGye9zmrtjI61RnAcvO:186225110) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/RollPitchYawFloatingJoint.h#L132)):*
`}  // namespace drake`

---

*[drake/multibody_dynamics/joints/test/joint_test.cc, line 115 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KGydw7jsI9wj44uu1ee:-KGydw7kV49bEjuJS5hb:186225110) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/test/joint_test.cc#L115)):*
`}  // namespace drake`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-:-KGyUD3C1rpNwvto2heL:586335470)*

**Comment by tkoolen** [comment]
> I agree that volunteers should not be held to the same level of rigor as full-time paid professionals

Thanks for understanding. Sorry to be so resistive with regards to doing the necessary extra work to fill in the details and I don't mean to offend, but I need to get back to other things. Whichever of those two options works for you guys is fine by me.

**Comment by amcastro-tri** [comment]
I just did a very quick first pass. This looks great @tkoolen!, thank you for doing this!. I do agree that writing specifics test for something like `get_name` (Google style naming :-) ) is beyond what you should probably be working on. I think the tests should focus on the proper implementation of transformations and auto differentiability of the joints. 
I still need to work on the last two tests, to be honest I need to study them better in order to provide feedback. 
I agree with the comments provided by @liangfok especially since I think they don't require a lot of work. 
I din't provide any feedback on style guide yet since I am focusing on functionality and API but since you are doing this from scratch it would probably be worth following the style guide for naming methods?

Overall great work! I loved you took everybody's suggestions from multiple conversations/channels!

I'll focus on studying the last two unit tests now. I'll be back :-)

---

Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h, line 9 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KH08z0iagGfbbNsYNYa:-KH08z0iagGfbbNsYNYb:-740529350) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h#L9)):*
You can define the types you will need at the beginning of the class. Make them public.
```c++
public:
typedef typename T::Scalar Scalar;
typedef typename Eigen::NumTraits<Scalar>::Real Real;

// And some useful vector types specialized in the scalar type (don't add this line in the code, it's just for me to explain)
typedef VectorX<T> VectorXt;
typedef VectorX<Scalar> VectorXs;
typedef VectorX<Real> VectorXr;
typedef Transform3D<T> Transform3Dt;
typedef Transform3D<Scalar> Transform3Ds;
typedef Transform3D<Real> Transform3Dr;
// ... and so on if you need more ...
```
See #2255. We still didn't decide whether to use `S` or `T` but I after writing this snipet I realized I like `T` better (see the end of the convesation in #2255).
This kind of types definitions would happen at the beginning of every class in Drake. It's ok, it is how it usually goes with templated code. 

---

*[drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h, line 24 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KH08GTx0soq5iIA_x2o:-KH08GTx0soq5iIA_x2p:-208241239) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/FixedAxisOneDoFJoint.h#L24)):*
There should be no single `double` in this implementation.  If what you actually mean is a Real value (meaning in the field of real numbers) then this should read `VectorX<Real>`, see comment above where I define a number of types at the very beginning of the class. 

---

*[drake/multibody_dynamics/joints/FixedJoint.h, line 24 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KH0DR1aDYReAKEazxja:-KH0DR1bRgfN9klb7AgO:2045616763) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/FixedJoint.h#L24)):*
Remove `<double>` and replace for appropriate type according to intention (either `T`, `Scalar` or `Real`)

---

*[drake/multibody_dynamics/joints/Joint.h, line 71 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KH082EP7G99W2tXAfiE:-KH082EP7G99W2tXAfiF:-1319032955) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/Joint.h#L71)):*
Why `<double>` here? I think it should be `VectorX<Scalar>`?

---

*[drake/multibody_dynamics/joints/Joint.h, line 75 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KH0Dh8SAmqFvXGm9rR8:-KH0Dh8TGKmM90vG5GCe:2045616763) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/Joint.h#L75)):*
Remove `<double>` and replace for appropriate type according to intention (either `T`, `Scalar` or `Real`)

---

*[drake/multibody_dynamics/joints/test/joint_test.cc, line 12 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KH0ETKn4H4WSDYI4vDF:-KH0ETKn4H4WSDYI4vDG:452862837) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/test/joint_test.cc#L12)):*
Nice! you templated the method creating the joints! It looks very nice!

---

*[drake/multibody_dynamics/joints/test/joint_test.cc, line 41 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KH0FTE4BWVjkxY6SIgm:-KH0FTE4BWVjkxY6SIgn:471296571) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/test/joint_test.cc#L41)):*
Since in the implementation you specialized to `double` (and probably your intention was more like `Real`) I have a question here. Would we like to be able to call `RandomConfiguration` with an `AutoDiffScalar` return? (and then the specialization should rather be on `T` (see previous comments on this)

---

*[drake/multibody_dynamics/joints/test/joint_test.cc, line 45 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KH0GFZDQgDF6lYjyMb0:-KH0GFZEldgM2YYgZRrQ:-31019682) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/test/joint_test.cc#L45)):*
maybe `tmp_matrix` or `result_matrix`. 

---

*[drake/multibody_dynamics/joints/test/joint_test.cc, line 46 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-KH0G83FjCW_05wFWIc2:-KH0G83FjCW_05wFWIc3:-1288596817) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd6eeda25de54958d23055829257fc82eb7a8cc/drake/multibody_dynamics/joints/test/joint_test.cc#L46)):*
why not `identity_matrix`? name `zero` is misleading. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-:-KH0HrJxGEYrbr6imXSP:939023176)*

**Comment by amcastro-tri** [comment]
@sherm1, probably you'd like to take a look at this if you have the time

**Comment by liangfok** [comment]
@amcastro-tri what's the plan for taking care of this PR? Is this orthogonal to the planned revamp of RBS / RBT / RB?

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> @sherm1, probably you'd like to take a look at this if you have the time
</details>


---

Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2267#-:-KJl0aB1JUoR3wKB5lGm:1728734680)*

**Comment by amcastro-tri** [comment]
It is not and this will be considered in the design. Also I am trying to follow System 2.0 as close as I can to make sure they can coexist nicely. 
Next week @sherm1 is cumming and it will be a good chance to revisit this.

**Comment by tkoolen** [comment]
@RussTedrake was saying that you guys may be switching to an RTTI-based design. I'm a little out of the loop so correct me if that is outdated or just wrong information. If that is the case though, the previous iteration of this pull request, https://github.com/RobotLocomotion/drake/pull/2209, might be a better place to start.

**Comment by amcastro-tri** [comment]
If that is the case, then I am out of date. I strongly discourage the RTTI unless there is a good reason for this design.

**Comment by david-german-tri** [comment]
It's complicated, and currently up in the air.  I agree, another f2f conversation is needed while @sherm1 is here.  @tkoolen, if you'd like to attend, we'll make sure to find a time that works for you; shoot me an email.

**Comment by jwnimmer-tri** [comment]
@david-german-tri or others... I wonder if there is still benefit to leaving this PR open?  It's still here archived even if we close it.

In some sense clutter in the PR list doesn't matter because folks only look at what's assigned to them, but I guess personally I'd still like to see the PR list be a bit tidier when we can manage it.

**Comment by liangfok** [comment]
I'm OK closing it for now until someone is actively working on it.

**Comment by tkoolen** [comment]
Sounds good, I'll close it.

**Pull request closed without merging**
