### PR TITLE
[visualization] By default, Meshcat proximity geometry is hidden

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #18409.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19058)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @RussTedrake @trowell-tri in case either of you would like to review

**Review by trowell-tri — COMMENTED** [review]
+@trowell-tri for feature review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19058#-:-NRFzjad0MNHgTXver9u:b-oe72ui)* status: LGTM missing from assignee trowell-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for platform review.  :lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19058#-:-NRG7zrdE26Qtya-YPJZ:b4i9u19)* status: LGTM missing from assignee trowell-tri (waiting on @trowell-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19058#-NRG7oln6ME2QCQ8ttb2:-NRG7oln6ME2QCQ8ttb3:b6sv6sc) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed65deeed9b7577b2099ed8065bc03675dcb8dd1/geometry/meshcat_visualizer_params.h#L57)):*
> ```objc
>   /** Determines whether our meshcat path should be default to being visible
>   (i.e., checked) at initialiation-time. */
>   bool visible_by_default{true};
> ```

btw -- should we add coverage for this in visualizers_test.py, too?  (I think it does get bound via the `DefAttributesUsingSerialize`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19058)* status: LGTM missing from assignee trowell-tri (waiting on @RussTedrake and @trowell-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19058#-NRG7oln6ME2QCQ8ttb2:-NRGADkLA36z1IuGkuRO:bv1txw0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed65deeed9b7577b2099ed8065bc03675dcb8dd1/geometry/meshcat_visualizer_params.h#L57)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- should we add coverage for this in visualizers_test.py, too?  (I think it does get bound via the `DefAttributesUsingSerialize`.
</blockquote></details>

We've gone back and forth on that in platform review.  The minimum solution is that _only one_ field needs to be checked.  I added it anyway; it's a bit of a nice demo if nothing else.

**Review by trowell-tri — COMMENTED** [review]
:lgtm: aside from a misspelling (and a possible comment expansion).

> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19058#-:-NRGCmB433zDBkGMu58v:b7qiqev)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19058#-NRG8rkB2Q-U7kkUWfbq:-NRG8rkB2Q-U7kkUWfbr:bq9ddhd) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed65deeed9b7577b2099ed8065bc03675dcb8dd1/geometry/meshcat_visualizer_params.h#L56)):*
> ```objc
> 
>   /** Determines whether our meshcat path should be default to being visible
>   (i.e., checked) at initialiation-time. */
> ```

btw consider expanding the comment to indicate that "checked" means the GUI checkbox is ticked. Maybe "Determines whether the checkbox for our meshcat path is ticked (so the path is visible) by default." (Possibly the verb "checked" just has weirdly overloaded meaning for me specifically from prior jobs.)

Also, spelling of "initialization".



_Code quote:_
```objc
checked
```

**Review by trowell-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19058)* status: :shipit: complete! all discussions resolved, LGTM from assignees trowell-tri,RussTedrake(platform) (waiting on @jwnimmer-tri)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19058)* status: :shipit: complete! all discussions resolved, LGTM from assignees trowell-tri,RussTedrake(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
