### PR TITLE
Create better error message for invalid matrices in RotationMatrix class

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8497)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@sherm1 
Platform review +@jwnimmer-tri 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-:-L97FeoqAaiPnTutFGzZ:br553un)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/rotation_matrix.h, line 581 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-L97q7R74KRbwGfmnG1E:-L97q7R74KRbwGfmnG1F:b-771s6g) ([raw file](https://github.com/robotlocomotion/drake/blob/7cc93cbcad01b6ecc7809b94484312c5ea366a59/math/rotation_matrix.h#L581)):*
> ```objc
>       std::string measure_as_string = ss.str();
>       std::string message = "Error: Rotation matrix is not orthonormal."
>                   "  Measure of orthonormality error = " + measure_as_string +
> ```

FYI @sherm1 as feature review, you should probably run this and make sure the string looks good.  I think its fine not to unit test if you don't want to have one, but at least on review we should then do a manual test.

---

*[math/rotation_matrix.h, line 585 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-L97oZxX5gP3jnqHDIoo:-L97oZxX5gP3jnqHDIop:b-jq8wcr) ([raw file](https://github.com/robotlocomotion/drake/blob/7cc93cbcad01b6ecc7809b94484312c5ea366a59/math/rotation_matrix.h#L585)):*
> ```objc
>                   " use RotationMatrix::ProjectToRotationMatrix(), or if"
>                   " you are using quaternions, ensure you normalize them.";
>       throw std::logic_error(message);
> ```

FYI Using `fmt::format` (`format/format.h`) is the modern way to do this (variable substitution into strings), and will be required when we introduce the DRAKE_DEMAND_WITH_NICE_ERROR_MESSAGE sugar that will make Symbolic code and Python users happy.  You can look for examples in Drake to see, or http://fmtlib.net/latest/syntax.html is the manual.  No defect -- if this stays as is, someone will just port it to fmtlib later, once we introduce the helper macros.

---

*[math/test/rotation_matrix_test.cc, line 86 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-L97pP-g1TCRqgi1w8bd:-L97pP-g1TCRqgi1w8be:b-nnlnsh) ([raw file](https://github.com/robotlocomotion/drake/blob/7cc93cbcad01b6ecc7809b94484312c5ea366a59/math/test/rotation_matrix_test.cc#L86)):*
> ```cpp
>        4, 5,  6,
>        7, 8, -10;
>   DRAKE_EXPECT_THROWS_MESSAGE(RotationMatrix<double> R2(m), std::logic_error,
> ```

FYI I don't think you need the ` R2` name here, at all?  At least -- it seems brittle to encourage developers to increment a number for every new case.  Just `R` would be better, if you want a name.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-:-L97qJ7-03RcrVi7boNo:bcpz082)*

**Comment by sherm1** [comment]
:lgtm: feature pending a couple of BTWs.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[math/rotation_matrix.h, line 581 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-L97q7R74KRbwGfmnG1E:-L97zio21-w6W2XIL3NT:b-fn41en) ([raw file](https://github.com/robotlocomotion/drake/blob/7cc93cbcad01b6ecc7809b94484312c5ea366a59/math/rotation_matrix.h#L581)):*
BTW, here is the message I got:
> Error: Rotation matrix is not orthonormal.  Measure of orthonormality error = 2.120000e+02 (near-zero is good).  To orthonormalize a 3x3 matrix, use RotationMatrix::ProjectToRotationMatrix(), or if you are using quaternions, ensure you normalize them.

I have a few suggestions:
- The scientific notation is atypical in C++ (more like Fortran). Instead of this, I suggest the much simpler `ss << std::abs(measure);` (no setiosflags) which uses the C++ default format. Using just the default format, here's what I got for a "very bad" and "slightly bad" non-orthogonal matrix, less likely to be mis-read:
  > Measure of orthonormality error=212 (near-zero is good). 
  > Measure of orthonormality error=2.71185e-12 (near-zero is good).
- The extra spaces around "=" and between sentences makes the error message harder to read because it causes line wrapping. I suggest forgoing those.

---

*[math/test/rotation_matrix_test.cc, line 86 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-L97pP-g1TCRqgi1w8bd:-L97xu5QCJJJn1xiRwex:b-fooon9) ([raw file](https://github.com/robotlocomotion/drake/blob/7cc93cbcad01b6ecc7809b94484312c5ea366a59/math/test/rotation_matrix_test.cc#L86)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I don't think you need the ` R2` name here, at all?  At least -- it seems brittle to encourage developers to increment a number for every new case.  Just `R` would be better, if you want a name.
</blockquote></details>

BTW not sure why but the compiler is interpreting `RotationMatrix<double>(m)` as a re-declaration of m rather than as a constructor call. Paul, rather than adding a name there, use initializer syntax: `RotationMatrix<double>{m}` (curly braces rather than parentheses). The compiler can't interpret that as a declaration.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-:-L98VFYm1sOO6k1Q875H:b-u26w5m)*

**Comment by sherm1** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497)*

**Comment by mitiguy** [comment]
Here are examples of the improved error messages.

Error: Rotation matrix is not orthonormal.  Measure of orthonormality error: 212 (near-zero is good).  To orthonormalize a 3x3 matrix, use RotationMatrix::ProjectToRotationMatrix(), or if you are using quaternions, ensure you normalize them.

Error: Rotation matrix is not orthonormal.  Measure of orthonormality error: 2.71185E-12 (near-zero is good).  To orthonormalize a 3x3 matrix, use RotationMatrix::ProjectToRotationMatrix(), or if you are using quaternions, ensure you normalize them.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-:-L9BuVJiB1cZhrDAqBMH:bwslgve)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497)*

**Comment by jwnimmer-tri** [comment]
Still LGTM platform; will leave to @sherm1 whether we are okay with locking down the set of supported scalar types.  (There is no requirement that `fmt` use be hidden in cc files.)

---

Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/rotation_matrix.cc, line 32 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-L9CPLWc7-3F7TBVlKms:-L9CPLWc7-3F7TBVlKmt:bdl945b) ([raw file](https://github.com/robotlocomotion/drake/blob/e03b0aee838f17d9e7447bab29c95affba017a28/math/rotation_matrix.cc#L32)):*
> ```cpp
>   if (R.determinant() < 0)
>     throw std::logic_error("Error: Rotation matrix determinant is negative. "
>                                "It is possible a basis is left-handed");
> ```

BTW Needs curly brace block around multi-line `if` body, per styleguide.  (I guess this is a pre-existing defect, but might as well fix it now?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-:-L9CPV1w9T0aqnfRt_UC:bcciewx)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497)*

**Comment by sherm1** [comment]
I think the scalar lockdown pattern is so widespread now in Drake that there is no point restricting it now. So I'm fine with it here. Paul couldn't get fmt to work in his header.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497#-:-L9CY7Rv-Q9S7zlMZlsp:bvwx1na)*

**Comment by jwnimmer-tri** [comment]
For the record, `#include "fmt/format.h"` would have worked.  (Use quotes, not angles.)

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8497)*

**Pull request merged**
