### PR TITLE
Add multi-cam scenario for testing

### PR DESCRIPTION
**Pull request by zachfang**
Per the comment in #20221, moved the file and added comments to a new location.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20456)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review. My take on the comment is to add a new scenario file only, but let me know if I miss anything.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20456#-:-Ni2wdyY2Ze-fGypGf2l:bvnvc2g)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`bindings/pydrake/visualization/test/lcm_image_array_viewer_multicam_scenario.yaml` line 5 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20456#-Ni2vcvS4wAl4kfCuxze:-Ni2vcvS4wAl4kfCuxzf:b-hzsv3k) ([raw file](https://github.com/RobotLocomotion/drake/blob/5be74d2f8e961855b768c841ff3ede1dae87fa8e/bindings/pydrake/visualization/test/lcm_image_array_viewer_multicam_scenario.yaml#L5)):*
> ```YAML
> 
> # bazel run //examples/hardware_sim:demo_py -- \
> #     --scenario_file /PATH/TO/DRAKE/bindings/pydrake/visualization/test/lcm_image_array_viewer_multicam_scenario.yaml \
> ```

BTW. My understanding is those demo files are meant to be copied to the user's directory, so we don't have `Rlocation` logic to process file paths in those files. Therefore, this needs to be an absolute path instead of `drake/bindings/...`.



_Code quote:_
```YAML
/PATH/TO/DRAKE
```

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: none)

:lgtm: tested locally.

I think +(status: single reviewer ok) is OK to merge, if you like.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20456#-:-Ni5240Z2zhOvffnPzWy:bjs8mni)* status: 2 unresolved discussions

___
*[`bindings/pydrake/visualization/test/lcm_image_array_viewer_multicam_scenario.yaml` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20456#-Ni5ixSYDH6stanr8lk4:-Ni5ixSYDH6stanr8lk5:bt0g25t) ([raw file](https://github.com/RobotLocomotion/drake/blob/5be74d2f8e961855b768c841ff3ede1dae87fa8e/bindings/pydrake/visualization/test/lcm_image_array_viewer_multicam_scenario.yaml#L1)):*
> ```YAML
> # This scenario file with multiple sim cameras is mainly for manual LCM image
> ```

We need a regression test to find any typos in this file.  We should run the hardware sim with a (small) timeout to make sure it doesn't crash, similar to how we do in the examples folder.
___
*[`bindings/pydrake/visualization/test/lcm_image_array_viewer_multicam_scenario.yaml` line 5 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20456#-Ni2vcvS4wAl4kfCuxze:-Ni51P9v3x-g9uh_ZtgT:b-eql7bh) ([raw file](https://github.com/RobotLocomotion/drake/blob/5be74d2f8e961855b768c841ff3ede1dae87fa8e/bindings/pydrake/visualization/test/lcm_image_array_viewer_multicam_scenario.yaml#L5)):*
> My understanding is those demo files are meant to be copied to the user's directory ...

For the hardware_sim examples for end users, that's true.  For a Drake unit test or Drake-developer manual test, we can use runfiles without any problems.

Having the docs like this is fine -- developers will be able to figure it out easily -- but if you wanted to have a rule in the BUILD file to run this with a shorter command line it would be OK too.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20456)* status: 1 unresolved discussion

___
*[`bindings/pydrake/visualization/test/lcm_image_array_viewer_multicam_scenario.yaml` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20456#-Ni5ixSYDH6stanr8lk4:-NiHwia56t0kiI_JdOCe:b-iui2dl) ([raw file](https://github.com/RobotLocomotion/drake/blob/5be74d2f8e961855b768c841ff3ede1dae87fa8e/bindings/pydrake/visualization/test/lcm_image_array_viewer_multicam_scenario.yaml#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We need a regression test to find any typos in this file.  We should run the hardware sim with a (small) timeout to make sure it doesn't crash, similar to how we do in the examples folder.
</blockquote></details>

Done. A smoke test with `multicam_scenario.yaml` (I made the file name shorter) is added.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20456)* status: 2 unresolved discussions

___
*[`bindings/pydrake/visualization/test/multicam_scenario_test.py` line 6 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20456#-NiKPPv12scrpUdBz44X:-NiKPPv12scrpUdBz44Y:b-u7pguh) ([raw file](https://github.com/RobotLocomotion/drake/blob/e49c90439bb393d7b02d2ffe17a0ff28f3b0648d/bindings/pydrake/visualization/test/multicam_scenario_test.py#L6)):*
> ```Python
> 
> from bazel_tools.tools.python.runfiles.runfiles import Create as CreateRunfiles
> import yaml
> ```

nit Unused `yaml`
___
*[`bindings/pydrake/visualization/test/multicam_scenario_test.py` line 17 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20456#-NiKPlhg4y7Xwlpgoaee:-NiKPlhg4y7Xwlpgoaef:b-j7d3an) ([raw file](https://github.com/RobotLocomotion/drake/blob/e49c90439bb393d7b02d2ffe17a0ff28f3b0648d/bindings/pydrake/visualization/test/multicam_scenario_test.py#L17)):*
> ```Python
>         return result
> 
>     def test_smoke(self):
> ```

BTW This test fails CI on macOS, because it uses RenderEngineGl.

If you like, you could skip the test:

```python
@unittest.skipIf(sys.platform == "darwin", "Missing RenderEngineGl")
def test_smoke(self):
    ....
```

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20456)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

___
*[`bindings/pydrake/visualization/test/multicam_scenario_test.py` line 17 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20456#-NiKPlhg4y7Xwlpgoaee:-NiKTpaSA3hlQSGRTAdw:byr4fl6) ([raw file](https://github.com/RobotLocomotion/drake/blob/e49c90439bb393d7b02d2ffe17a0ff28f3b0648d/bindings/pydrake/visualization/test/multicam_scenario_test.py#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This test fails CI on macOS, because it uses RenderEngineGl.

If you like, you could skip the test:

```python
@unittest.skipIf(sys.platform == "darwin", "Missing RenderEngineGl")
def test_smoke(self):
    ....
```
</blockquote></details>

Right!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20456)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
