### PR TITLE
Update director submodule SHA

### LINKED ISSUE #4806: Build Problem on OS X - 'GL/glut.h' file not found
# The Error

I encountered the following error on OSX 10.11.6 using the latest on master (SHA e4c29605462fff36b5ba24ba1639f7299076ae65):

```
FAILED: src/vtk/DRCFilters/CMakeFiles/vtkDRCFilters.dir/vtkLCMGLProp.cxx.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DGLUT_AVAILABLE -DvtkDRCFilters_EXPORTS -I/usr/local/opt/vtk5/include/vtk-5.10 -I/Users/liang/dev/drake-distro-1/externals/director/src/vtk/DRCFilters -Isrc/vtk/DRCFilters -I/Users/liang/dev/drake-distro-1/build/install/include/eigen3 -I/Users/liang/dev/drake-distro-1/build/install/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -g -fPIC   -F/usr/local/Cellar/qt/4.8.7_2/lib -MMD -MT src/vtk/DRCFilters/CMakeFiles/vtkDRCFilters.dir/vtkLCMGLProp.cxx.o -MF src/vtk/DRCFilters/CMakeFiles/vtkDRCFilters.dir/vtkLCMGLProp.cxx.o.d -o src/vtk/DRCFilters/CMakeFiles/vtkDRCFilters.dir/vtkLCMGLProp.cxx.o -c /Users/liang/dev/drake-distro-1/externals/director/src/vtk/DRCFilters/vtkLCMGLProp.cxx
/Users/liang/dev/drake-distro-1/externals/director/src/vtk/DRCFilters/vtkLCMGLProp.cxx:27:10: fatal error: 'GL/glut.h' file not found
#include <GL/glut.h>
         ^
```

This was after updating my system based on [these instruction](http://drake.mit.edu/homebrew.html) and doing a clean build.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #4806.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4811)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4811#-:-Kam1W0NYXZ7nDpb5Uuk:bnfp4nl)*

**Comment by david-german-tri** [comment]
As soon as the Mac build passes, let's override-merge.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4811#-:-Kam49Z67nKDt42PeKuL:bnfp4nl)*

**Pull request merged**
