### PR TITLE
Install examples and manipulation data

### PR DESCRIPTION
**Pull request by fbudin69500**
---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6671)

### CODE REVIEW

**Comment by fbudin69500** [comment]
This is to address https://github.com/RobotLocomotion/drake/issues/6668

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 19 files at r1.
Review status: 2 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/BUILD, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3J1tmsOQ686HdJmva:-Kq3J1tnoLWcZTZx6-NP:b-7mil35) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/BUILD#L303)):*
> ```Python
>     deps = [
>     "//drake/bindings:install",
>     "//drake/examples:install_data",
> ```

Drake's pattern seems to be that `/BUILD.bazel` is what lists the top-level things to be installed, not `/drake/BUILD`.  I don't see a good reason to glom the install_data rules onto `libdrake.so`'s install rule.

---

*[drake/BUILD, line 306 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3Hx-F7qz6IBcYz3sb:-Kq3Hx-F7qz6IBcYz3sc:b-j5yc99) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/BUILD#L306)):*
> ```Python
>     "//drake/manipulation/models/iiwa_description:install_data",
>     "//drake/manipulation/models/jaco_description:install_data",
>     "//drake/manipulation/models/wsg_50_description:install_data",
> ```

FYI Consider adding `//drake/manipulation/models:install_data` rollup, to encourage developers not to forget to add rules when they add new models.

---

*[drake/examples/acrobot/BUILD, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3JTQyqj0PtFsHl5hj:-Kq3JTQyqj0PtFsHl5hk:btvm8x7) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/examples/acrobot/BUILD#L234)):*
> ```Python
> )
> 
> install_data("share/drake/drake/examples/acrobot")
> ```

_Meta_

Under the hood, this macro runs an independently-implemented glob from the one that the `:models` rule above uses.  However, `:models` is what all of the unit tests use, so is guaranteed to be correct.

To leverage that test coverage, it seems better to have only one filegroup that serves both to provide the models to tests, as well as to the install rule.  I think that goes for all of the examples too, not just ones that already have a filegroup -- if tests are born in those directories in the future, we want them to use the same filegroup as the install rules, too.

If the goal is to centralize the list of extensions to be globbed (which seems reasonable), then that should be its own macro, such as `models_filegroup(name = "models", root = ".")` that takes over for the `filegroup()` above, which the install rule is then given.

---

*[drake/examples/acrobot/BUILD, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3N-XMlWZdfl2rYhuA:-Kq3N-XMlWZdfl2rYhuB:bhfannv) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/examples/acrobot/BUILD#L234)):*
> ```Python
> )
> 
> install_data("share/drake/drake/examples/acrobot")
> ```

_Meta_ That the developer has to repeat the package name here is a DRY violation.  Please at least add a TODO (possibly inside the macro?) to have the build system automatically infer the destination (and thus remove this argument).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671)*

**Comment by fbudin69500** [comment]
Review status: 2 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/acrobot/BUILD, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3JTQyqj0PtFsHl5hj:-Kq4Jk0Wb7r_jjZw91kY:brr2kg3) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/examples/acrobot/BUILD#L234)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_

Under the hood, this macro runs an independently-implemented glob from the one that the `:models` rule above uses.  However, `:models` is what all of the unit tests use, so is guaranteed to be correct.

To leverage that test coverage, it seems better to have only one filegroup that serves both to provide the models to tests, as well as to the install rule.  I think that goes for all of the examples too, not just ones that already have a filegroup -- if tests are born in those directories in the future, we want them to use the same filegroup as the install rules, too.

If the goal is to centralize the list of extensions to be globbed (which seems reasonable), then that should be its own macro, such as `models_filegroup(name = "models", root = ".")` that takes over for the `filegroup()` above, which the install rule is then given.
</blockquote></details>

The rational to repeat the `filegroup(...glob...`) inside the macro is because in some of the examples the glob includes tests files that should most likely not be installed. The glob expression used in the macro excludes such files, but the one used in the `BUILD` file does not. One could consider creating one macro that would create two `*models*` variables (ideally complementing each other, i.e.one with only the tests, and one without the tests). @jwnimmer-tri Is this what you had in mind?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/acrobot/BUILD, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3JTQyqj0PtFsHl5hj:-Kq4LwG-uicJfVS3DMyH:bt2l2ix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/examples/acrobot/BUILD#L234)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

The rational to repeat the `filegroup(...glob...`) inside the macro is because in some of the examples the glob includes tests files that should most likely not be installed. The glob expression used in the macro excludes such files, but the one used in the `BUILD` file does not. One could consider creating one macro that would create two `*models*` variables (ideally complementing each other, i.e.one with only the tests, and one without the tests). @jwnimmer-tri Is this what you had in mind?
</blockquote></details>

My basic desire is that the list of installed files gets a reasonable best-effort at test coverage, and that filegroups mostly stay true to "don't repeat yourself".

More specifically, for any example file `foo.urdf` that is going to be installed, that it be named in exactly one filegroup, e.g.,
  ```
filegroup(
    name = "prod_models",
    srcs = ... something that globs or otherwise lists foo.urdf ...,
)
```
and that the way the install system installs it is by installing its containing filegroup, e.g.,
```
install(
    ...,
    data = [":prod_models"],
)
```


I think a macro that created two filesgroups (test and prod), of which only prod was installed, would be a great solution.  Using some hand-written filegroups in the meantime would also be a-ok by me.  There might be other solutions too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671)*

**Comment by fbudin69500** [comment]
Review status: 1 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/acrobot/BUILD, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3JTQyqj0PtFsHl5hj:-Kq56A_lfQXU_NiKCrC0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/examples/acrobot/BUILD#L234)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My basic desire is that the list of installed files gets a reasonable best-effort at test coverage, and that filegroups mostly stay true to "don't repeat yourself".

More specifically, for any example file `foo.urdf` that is going to be installed, that it be named in exactly one filegroup, e.g.,
  ```
filegroup(
    name = "prod_models",
    srcs = ... something that globs or otherwise lists foo.urdf ...,
)
```
and that the way the install system installs it is by installing its containing filegroup, e.g.,
```
install(
    ...,
    data = [":prod_models"],
)
```


I think a macro that created two filesgroups (test and prod), of which only prod was installed, would be a great solution.  Using some hand-written filegroups in the meantime would also be a-ok by me.  There might be other solutions too.
</blockquote></details>

Done.

---

*[drake/examples/acrobot/BUILD, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3N-XMlWZdfl2rYhuA:-Kq56C0-0xcp4lRJP7Oz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/examples/acrobot/BUILD#L234)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ That the developer has to repeat the package name here is a DRY violation.  Please at least add a TODO (possibly inside the macro?) to have the build system automatically infer the destination (and thus remove this argument).
</blockquote></details>

Done.

---

*[drake/BUILD, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3J1tmsOQ686HdJmva:-Kq564NoXgrvkozB6qIH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/BUILD#L303)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Drake's pattern seems to be that `/BUILD.bazel` is what lists the top-level things to be installed, not `/drake/BUILD`.  I don't see a good reason to glom the install_data rules onto `libdrake.so`'s install rule.
</blockquote></details>

Done.

---

*[drake/BUILD, line 306 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3Hx-F7qz6IBcYz3sb:-Kq5657to9kGaeTLOZoQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/BUILD#L306)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider adding `//drake/manipulation/models:install_data` rollup, to encourage developers not to forget to add rules when they add new models.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671)*

**Comment by jwnimmer-tri** [comment]
:lgtm: feature.  +@sherm1 for platform review on-call.

---

Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/acrobot/BUILD, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3N-XMlWZdfl2rYhuA:-Kq5dvHF7_g8F1S7NJV4:b-j7qk9g) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/examples/acrobot/BUILD#L234)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Very nice.

---

*[drake/examples/acrobot/BUILD, line 223 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq5fdL0PcucL4tzEwVj:-Kq5fdL1gYsN8gIKJ_Fz:bvni89t) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/drake/examples/acrobot/BUILD#L223)):*
> ```Python
> )
> 
> install_data()
> ```

FYI So while this macro is much better functionality, its slightly magical at the call site here.  Having documentation in `install_data.bzl` would help, but I wonder if changing the signature here would make it clearer to readers what's happening.  In particular, where the `:models` label comes from now is a bit hidden.

For example:
- `install_models()` would hint that it relates to where `:models` came from.
- `install_data(name = "models")` would let the user choose the name, and directly name where the `:models` label came from.

---

*[tools/install_data.bzl, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq5euQdxzNN0qWSfKZ2:-Kq5euQdxzNN0qWSfKZ3:b4z9vc1) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/tools/install_data.bzl#L3)):*
> ```Python
> load("//tools:install.bzl", "install")
> 
> def install_data():
> ```

The commit message has some nice documentation about this function.  I think that such documentation should (also) appear somewhere here in this file, where developers are more likely to see it.

---

*[tools/install_data.bzl, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq5ghmmocvTSvctCAyk:-Kq5ghmmocvTSvctCAyl:bquvcs1) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/tools/install_data.bzl#L18)):*
> ```Python
>     test_models_include = [
>         p + m for p in exclude_patterns for m in models_extensions
>     ]
> ```

FYI This is correct, but two things in the above made me have to pause to understand the code:

(1) For include, we have a string and `.format`; for exclude, we just concatenate.
(2) For include, the pattern is a string literal; for exclude, its a named list.

Having include vs exclude use the same constructions might make the code easier to follow.  No defect.

---

*[tools/install_data.bzl, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq5gGhSS4f9l98ugpG5:-Kq5gGhSS4f9l98ugpG6:b-e4c17s) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/tools/install_data.bzl#L34)):*
> ```Python
>         ),
>         visibility = ["//visibility:public"],
>     )
> ```

FYI If adding `testonly = 1` passes the build, I would suggest doing so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-:-Kq5hJYTgn_n3hkaMDYo:b-pxowdq)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 19 files at r1, 19 of 20 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[BUILD.bazel, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq8eeXjZZQQ0_NytvYO:-Kq8eeXjZZQQ0_NytvYP:b-4dj6z2) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/BUILD.bazel#L72)):*
> ```
>         "//drake/lcmtypes:install",
>         "//drake/examples:install_data",
>         "//drake/manipulation/models:install_data",
> ```

BTW, alphabetize?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-:-Kq8eigWX8Fql_nvjAfC:bnfp4nl)*

**Comment by sherm1** [comment]
This is a masterful work of Bazel-fu but clever code requires documentation to help those who will try to understand it later. Please add some.

---

Reviewed 1 of 19 files at r1, 19 of 20 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-:-Kq8i0N-kQRN27Xgnipq:bt0gi7z)*

**Comment by fbudin69500** [comment]
Review status: 1 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[BUILD.bazel, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq8eeXjZZQQ0_NytvYO:-KqZWEpP_4QC6pHYo2dK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/BUILD.bazel#L72)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW, alphabetize?
</blockquote></details>

Done.

---

*[drake/examples/acrobot/BUILD, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq3N-XMlWZdfl2rYhuA:-KqZPZC8mKp53EsipUke:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f046ee6a46f5619ca9856d99a044c06ce8f4910/drake/examples/acrobot/BUILD#L234)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Very nice.
</blockquote></details>

Done.

---

*[drake/examples/acrobot/BUILD, line 223 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq5fdL0PcucL4tzEwVj:-KqZPYfTjbCdIC3drIqL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/drake/examples/acrobot/BUILD#L223)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI So while this macro is much better functionality, its slightly magical at the call site here.  Having documentation in `install_data.bzl` would help, but I wonder if changing the signature here would make it clearer to readers what's happening.  In particular, where the `:models` label comes from now is a bit hidden.

For example:
- `install_models()` would hint that it relates to where `:models` came from.
- `install_data(name = "models")` would let the user choose the name, and directly name where the `:models` label came from.
</blockquote></details>

Done.

---

*[tools/install_data.bzl, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq5euQdxzNN0qWSfKZ2:-KqZWGMvVqdsSf_5IbVr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/tools/install_data.bzl#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The commit message has some nice documentation about this function.  I think that such documentation should (also) appear somewhere here in this file, where developers are more likely to see it.
</blockquote></details>

Done.

---

*[tools/install_data.bzl, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq5ghmmocvTSvctCAyk:-KqZQimnUhR0-TOu3nqc:b-bpr8c1) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/tools/install_data.bzl#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This is correct, but two things in the above made me have to pause to understand the code:

(1) For include, we have a string and `.format`; for exclude, we just concatenate.
(2) For include, the pattern is a string literal; for exclude, its a named list.

Having include vs exclude use the same constructions might make the code easier to follow.  No defect.
</blockquote></details>

1) I could rewrite the exclude line `exclude_pattern = ["**/{}*".format(x) for x in ["test/", "test"]]` but I am not sure it would make it easier to read.
2) I am not sure what you mean.

---

*[tools/install_data.bzl, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-Kq5gGhSS4f9l98ugpG5:-KqZSldFSZEx3wd2UDBn:bcxf7az) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5cdfea2272c0e2f6b5b19e3c1b5d9e0446c869/tools/install_data.bzl#L34)):*
> testonly = 1
This does not work because some `drake_cc_binary` use `models` as `data`, and these `models` are not defined with `testonly = 1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671)*

**Comment by jwnimmer-tri** [comment]
Reviewed 19 of 20 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671)*

**Comment by jwnimmer-tri** [comment]
Now just needs a re-look from @sherm1.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6671#-:-KqZj-QFl5fjhp6OWfX4:be8q8wg)*

**Pull request merged**
