### PR TITLE
[trajectory_optimization] MultipleShooting has-a MathematicalProgram

### PR DESCRIPTION
**Pull request by RussTedrake**
Previously the trajectory optimization base class MultipleShooting
derived from MathematicalProgram (MultipleShooting is-a
MathematicalProgram).  This PR changes that relationship to
MultipleShooting has-a MathematicalProgram (as a member variable).

This is the pattern used in much of our other optimization classes,
such as InverseKinematics and the Anzu
KinematicTrajectoryOptimization.  It has a number of advantages,
including the ability, for instance, create multiple trajectory
optimization problems in the same mathematical program.

This PR is a doozy, but it's almost entirely the deprecation
boilerplate. Yuck!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please.
+@jwnimmer-tri for platform review, please.
cc @mposa -- we discussed this on slack before, but I want to make sure you are aware in case it impacts your work.  let me know if there are changes that can make anything smooth for you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333#-:-MspkEGo0cHSBuoSxU5_:bfm3uen)* status: LGTM missing from assignees hongkai-dai,jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[bindings/pydrake/systems/test/trajectory_optimization_test.py, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MspkdR18GI1oFaRpLsf:-MspkdR18GI1oFaRpLsg:b1kg3or) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/bindings/pydrake/systems/test/trajectory_optimization_test.py#L103)):*
> ```Python
>                                        dircol.state(0), dircol.state(1),
>                                        dircol.input(0), dircol.input(1),
>                                        dircol.prog())
> ```

fyi -- this is an example of the breaking change described in the commit message.  I chose not to deprecate this one -- it was an absurd use case that only appeared here for convenience. You wouldn't add DirectCollocation constraints to an existing DirectColocation program.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 13 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @hongkai-dai, @jwnimmer-tri, and @RussTedrake)

___
*[systems/trajectory_optimization/multiple_shooting.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsppvQUEIwxVxLoPjRS:-MsppvQUEIwxVxLoPjRT:b3o92af) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L65)):*
> ```objc
> #define DRAKE_PERFECT_FORWARD_MATH_PROG(method_name, maybe_const) \
>   template <typename... Args> \
>   DRAKE_DEPRECATED("2022-04-01", "Use trajopt.prog()." #method_name) \
> ```

Just to confirm, that before 04-01, if we make any changes to the public API of `MathematicalProgram`, we should make the corresponding changes here as well?
___
*[systems/trajectory_optimization/multiple_shooting.h, line 592 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspr-sA-Z8PGABZonSl:-Mspr-sA-Z8PGABZonSm:b-7200af) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L592)):*
> ```objc
> 
>   const std::unique_ptr<solvers::MathematicalProgram> owned_prog_;
>   solvers::MathematicalProgram& prog_;
> ```

Curious why we have both `owned_prog_` and `prog_`.  I would think that we only need `owned_prog_`. Does it happen if prog_ != *owned_prog_?
___
*[systems/trajectory_optimization/multiple_shooting.h, line 615 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspqli17BqD6dcxO64a:-Mspqli17BqD6dcxO64b:bjiub08) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L615)):*
> ```objc
> };
> 
> /// Solves the MathematicalProgram defined by `trajopt.prog()`.
> ```

Just curious why we add these three `Solve` functions? They seem to just call `return solvers::Solve(trajopt.prog())`, which is just one line for the user.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[systems/trajectory_optimization/multiple_shooting.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsppvQUEIwxVxLoPjRS:-Msq4zuPDgxshblvpT_3:btluuau) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L65)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just to confirm, that before 04-01, if we make any changes to the public API of `MathematicalProgram`, we should make the corresponding changes here as well?
</blockquote></details>

I would say absolutely not.  Once this lands, then any new changes to MathematicalProgram will not exist in user's trajectory optimization code, and does not require deprecation.
___
*[systems/trajectory_optimization/multiple_shooting.h, line 592 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspr-sA-Z8PGABZonSl:-Msq5Qht6sFeW2UQH_wl:b-sr9bg1) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L592)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why we have both `owned_prog_` and `prog_`.  I would think that we only need `owned_prog_`. Does it happen if prog_ != *owned_prog_?
</blockquote></details>

It's not strictly necessary here, but I intend to offer a constructor that takes an existing prog as an argument.  Then you can add multiple trajectory optimizations to the same prog.
___
*[systems/trajectory_optimization/multiple_shooting.h, line 615 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspqli17BqD6dcxO64a:-Msq5lgP3KqUnQY8_F_8:b-vxdwiw) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L615)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just curious why we add these three `Solve` functions? They seem to just call `return solvers::Solve(trajopt.prog())`, which is just one line for the user.
</blockquote></details>

I definitely need to add them now in order to have existing code continue to work.  The question is whether we deprecate them.  I thought it was not bad to have this little bit of sugar available forevermore.  WDYT?

**Comment by RussTedrake** [comment]
fyi @avalenzu. i know you'll be happy to see this one happen.  :-)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333#-:-Msqp7vI3V6Utx8i57xi:bg7igkv)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai, @jwnimmer-tri, and @RussTedrake)

___
*[systems/trajectory_optimization/multiple_shooting.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsppvQUEIwxVxLoPjRS:-MsqnqxQ5OGLpU9Y40kk:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L65)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I would say absolutely not.  Once this lands, then any new changes to MathematicalProgram will not exist in user's trajectory optimization code, and does not require deprecation.
</blockquote></details>

Thanks!
___
*[systems/trajectory_optimization/multiple_shooting.h, line 592 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspr-sA-Z8PGABZonSl:-Msqnud_DYByQf1-XbGh:b-dazvu2) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L592)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

It's not strictly necessary here, but I intend to offer a constructor that takes an existing prog as an argument.  Then you can add multiple trajectory optimizations to the same prog.
</blockquote></details>

I see, then maybe add a documentation here with TODO: add constructor that takes an existing prog, so that we know why we have this `prog_` property.
___
*[systems/trajectory_optimization/multiple_shooting.h, line 615 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspqli17BqD6dcxO64a:-MsqoiMi9nSTvUiFgTWP:b-ox3iv) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L615)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I definitely need to add them now in order to have existing code continue to work.  The question is whether we deprecate them.  I thought it was not bad to have this little bit of sugar available forevermore.  WDYT?
</blockquote></details>

I see.

I think for simplicity, maybe after 04-01 we can deprecate these methods? Since they do almost the same thing as Solve(prog).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333)* status: 11 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuTcYE3JFqdr3_6qEV:-MsuTcYE3JFqdr3_6qEW:bogi68u) (no related file):*
nit By convention, the nominal date target would be 2022-05-01 (add three months, then round up).  Was the choice of the earlier date 2022-04-01 on purpose?  It's fine if you want to use an earlier date, but in that case the PR overview should mention that the divergence is on purpose (rather than accidental) to aid the reviewers.

---
___
*[examples/pendulum/trajectory_optimization_simulation.cc, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuRqvH77nmgJTINzyp:-MsuRqvH77nmgJTINzyq:b-mfvvoh) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/examples/pendulum/trajectory_optimization_simulation.cc#L62)):*
> ```cpp
> 
>   prog.AddLinearConstraint(dircol.initial_state() ==
>                              initial_state.value());
> ```

nit This needs an indentation fixup (to align with the prior line).
___
*[systems/controllers/linear_model_predictive_controller.cc, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MszXd5fBi04OCJuO8qj:-MszXd5fBi04OCJuO8qk:b-mfvvoh) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/controllers/linear_model_predictive_controller.cc#L96)):*
> ```cpp
> 
>   DirectTranscription dirtran(linear_model_.get(), *base_context_,
>                            kNumSampleTimes);
> ```

nit This needs an indentation fixup (to align with the prior line).
___
*[systems/trajectory_optimization/direct_collocation.cc, line 188 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuV-sCDQ8YBbsEbND8:-MsuV-sCDQ8YBbsEbND9:b-mfvvoh) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/direct_collocation.cc#L188)):*
> ```cpp
>   for (int i = 0; i < N() - 1; i++) {
>     prog().AddConstraint(constraint,
>                   {h_vars().segment<1>(i),
> ```

nit This needs an indentation fixup (to align with the prior line).
___
*[systems/trajectory_optimization/direct_collocation.cc, line 204 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuV1p-C3fNYu7Fch4d:-MsuV1p-C3fNYu7Fch4e:bv5aogx) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/direct_collocation.cc#L204)):*
> ```cpp
> 
>   prog().AddCost(SubstitutePlaceholderVariables(
>      g * h_vars()(0) / 2, 0));
> ```

nit This needs an indentation fixup.  (Should be +4 versus the prior line, not +3.)
___
*[systems/trajectory_optimization/multiple_shooting.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuTMkrB-i6REoaYLQD:-MsuTMkrB-i6REoaYLQE:b-acbu4k) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L62)):*
> ```objc
> // Hide the deprecation shims.
> #ifndef DRAKE_DOXYGEN_CXX
>   operator const solvers::MathematicalProgram&() { return prog(); }
> ```

I don't think our intention is to keep this conversion function around indefinitely (given the prior line)? In which case, this function should be marked with `DRAKE_DEPRECATED`.
___
*[systems/trajectory_optimization/multiple_shooting.h, line 615 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspqli17BqD6dcxO64a:-MsuSfy21haH05a7S0LL:b-742gar) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L615)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see.

I think for simplicity, maybe after 04-01 we can deprecate these methods? Since they do almost the same thing as Solve(prog).
</blockquote></details>

The main problem is that this induces a dependency from MultipleShooting onto _every_ specific solver back-end (Mosek, Gurobi, etc.) even if the user already knows which specific solver they are going to call to solve the program (Snopt).

If we keep this sugar long-term, then ideally it would appear in a separate header from this one, so that the user who doesn't want to use `solvers::Solve` doesn't need to pay for it.

I will go look into the call sites before I offer my opinion on whether or not we should deprecate these.

...

Pulling this locally, it turns out that nothing (except the direct unit tests in this folder) is using this sugar?  It seems like if the user has said `using solvers::Solve;` in their code, then the conversion operator defined on MultipleShooting gets invoked automatically and the program compiles successfully.

That says to me that we should take the easy way out here, and deprecate these helpers immediately in this PR.

Saying `result = Solve(trajopt.prog())` does not seem very awkward vs `result = Solve(trajopt)`, and I'd even argue that it's _more_ clear because it gives us uniformity of laying between the MultipleShooting vs MathematicalProgram concepts.
___
*[systems/trajectory_optimization/multiple_shooting.cc, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuUktF65zF165S5wl1:-MsuUktF65zF165S5wl2:b-mfvvoh) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.cc#L172)):*
> ```cpp
>   DRAKE_THROW_UNLESS(timesteps_are_decision_variables_);
>   return prog_.AddLinearConstraint(VectorXd::Ones(h_vars_.size()), lower_bound,
>                              upper_bound, h_vars_);
> ```

nit This needs an indentation fixup (to align with the prior line).
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1907 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuVuit6RW2pja3_Rr9:-MsuVuit6RW2pja3_RrA:b-6vwlcs) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1907)):*
The module-loading order here is inconsistent with our documented policy:

> Any symbol referenced in a module binding (even as function/method parameters) must either be bound in that compilation unit (with the binding evaluated before to the reference), or the module must import the pydrake module in which it is bound (e.g., py::module::import("pydrake.foo"))). Failure to do so can cause errors (unable to cast unregistered types from Python to C++) and can cause the generated docstring from pybind11 to render these types by their C++ typeid rather than the Python type name.

-- https://drake.mit.edu/doxygen_cxx/group__python__bindings.html

Ideally, the `PYBIND11_MODULE(trajectory_optimization, m)` should add this overload into the existing one.  I am not sure how practical that is, though.

On the other hand, when I render the help string, the type appears to be registered correctly, so perhaps it doesn't matter.

In any case, this is another reason to consider the `Solve(MultipleShooting)` as a transitional-only function that we should deprecate as part of this PR.

I don't think we should plan to add `Solve()` sugar for every class that has-a MathematicalProgram, which would be the policy established by keeping this kind of sugar as non-deprecated here.
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1911 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Msza5pj7nORouIQAsYY:-Msza5pk3wdOfNfTMiMX:bcja5eg) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1911)):*
> ```cpp
>           overload_cast_explicit<solvers::MathematicalProgramResult,
>               const systems::trajectory_optimization::MultipleShooting&>(
>               &systems::trajectory_optimization::Solve),
> ```

The `solvers::Solve` has multiple overloads in C++, but in pydrake (above) we've only bound the 3-argument overload, using `= py::none()` to default the optional arguments.

It seems to me like we should be consistent here and do the same (add only one binding, but with defaults) for the trajopt overload, so that pydrake's documentation of the overload set is clear and consistent (with just the two overloads, one for each of the two program types).

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuTcYE3JFqdr3_6qEV:-Mt0gfIL2hNHNM70_f00:b-806er) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit By convention, the nominal date target would be 2022-05-01 (add three months, then round up).  Was the choice of the earlier date 2022-04-01 on purpose?  It's fine if you want to use an earlier date, but in that case the PR overview should mention that the divergence is on purpose (rather than accidental) to aid the reviewers.
</blockquote></details>

Done. Updated to 2022-05-01.

---
___
*[examples/pendulum/trajectory_optimization_simulation.cc, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuRqvH77nmgJTINzyp:-Mt0h--24LAlT9sbm1W3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/examples/pendulum/trajectory_optimization_simulation.cc#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This needs an indentation fixup (to align with the prior line).
</blockquote></details>

Done.
___
*[systems/controllers/linear_model_predictive_controller.cc, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MszXd5fBi04OCJuO8qj:-Mt0h2Zf5za_XGW_dLzg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/controllers/linear_model_predictive_controller.cc#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This needs an indentation fixup (to align with the prior line).
</blockquote></details>

Done.
___
*[systems/trajectory_optimization/multiple_shooting.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuTMkrB-i6REoaYLQD:-Mt0hllI1gAfWcQ8HdDj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think our intention is to keep this conversion function around indefinitely (given the prior line)? In which case, this function should be marked with `DRAKE_DEPRECATED`.
</blockquote></details>

Done.
___
*[systems/trajectory_optimization/multiple_shooting.h, line 592 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspr-sA-Z8PGABZonSl:-Mt0i5h10bM1YcKEYRC-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L592)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, then maybe add a documentation here with TODO: add constructor that takes an existing prog, so that we know why we have this `prog_` property.
</blockquote></details>

Done.
___
*[systems/trajectory_optimization/multiple_shooting.h, line 615 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspqli17BqD6dcxO64a:-Mt0swrICM1piYkwf2U6:b-qc49og) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L615)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The main problem is that this induces a dependency from MultipleShooting onto _every_ specific solver back-end (Mosek, Gurobi, etc.) even if the user already knows which specific solver they are going to call to solve the program (Snopt).

If we keep this sugar long-term, then ideally it would appear in a separate header from this one, so that the user who doesn't want to use `solvers::Solve` doesn't need to pay for it.

I will go look into the call sites before I offer my opinion on whether or not we should deprecate these.

...

Pulling this locally, it turns out that nothing (except the direct unit tests in this folder) is using this sugar?  It seems like if the user has said `using solvers::Solve;` in their code, then the conversion operator defined on MultipleShooting gets invoked automatically and the program compiles successfully.

That says to me that we should take the easy way out here, and deprecate these helpers immediately in this PR.

Saying `result = Solve(trajopt.prog())` does not seem very awkward vs `result = Solve(trajopt)`, and I'd even argue that it's _more_ clear because it gives us uniformity of laying between the MultipleShooting vs MathematicalProgram concepts.
</blockquote></details>

Ok.  You're right.  I've removed the C++ Solve methods completely, and updated my pybind.
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1907 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-MsuVuit6RW2pja3_Rr9:-Mt0uUKc2AyURdqo9tiW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1907)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The module-loading order here is inconsistent with our documented policy:

> Any symbol referenced in a module binding (even as function/method parameters) must either be bound in that compilation unit (with the binding evaluated before to the reference), or the module must import the pydrake module in which it is bound (e.g., py::module::import("pydrake.foo"))). Failure to do so can cause errors (unable to cast unregistered types from Python to C++) and can cause the generated docstring from pybind11 to render these types by their C++ typeid rather than the Python type name.

-- https://drake.mit.edu/doxygen_cxx/group__python__bindings.html

Ideally, the `PYBIND11_MODULE(trajectory_optimization, m)` should add this overload into the existing one.  I am not sure how practical that is, though.

On the other hand, when I render the help string, the type appears to be registered correctly, so perhaps it doesn't matter.

In any case, this is another reason to consider the `Solve(MultipleShooting)` as a transitional-only function that we should deprecate as part of this PR.

I don't think we should plan to add `Solve()` sugar for every class that has-a MathematicalProgram, which would be the policy established by keeping this kind of sugar as non-deprecated here.
</blockquote></details>

Done.
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1911 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Msza5pj7nORouIQAsYY:-Mt0vqIICKY7T6GJ7zKm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1911)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `solvers::Solve` has multiple overloads in C++, but in pydrake (above) we've only bound the 3-argument overload, using `= py::none()` to default the optional arguments.

It seems to me like we should be consistent here and do the same (add only one binding, but with defaults) for the trajopt overload, so that pydrake's documentation of the overload set is clear and consistent (with just the two overloads, one for each of the two program types).
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 10 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

**Comment by RussTedrake** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mt3ZMs58QBSy-0jt6No:-Mt44N0w9kekqLDIvhXY:bb8mxtg) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For the python bindings, instead of binding Solve(trajopt), I suspect that we could bind the (deprecated) conversion operator from MultpleShooting to MathematicalProgram.  I don't think that's required -- this is a breaking change in any case, the only question is what specifically will break -- but wanted to toss it out there for consideration.
</blockquote></details>

I almost asked about it.  If we can make that happen with a reasonable amount of effort, I'd like to do it.

---

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333)* status: 2 unresolved discussions (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[systems/trajectory_optimization/multiple_shooting.h, line 615 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mspqli17BqD6dcxO64a:-Mt45qZiBE44oinK0O8J:b-7ztaov) ([raw file](https://github.com/robotlocomotion/drake/blob/19129d6c4fd37d0c8c25d58aa1603cb3c9546586/systems/trajectory_optimization/multiple_shooting.h#L615)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The commented-out code is still hanging around here.
</blockquote></details>

Done.  (I knew I lost some unsaved changes when I closed an editor tab after pushing yesterday, but couldn't for the life of me figure out what I missed!).
___
*[systems/trajectory_optimization/test/direct_transcription_test.cc, line 754 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mt3Yo8oBoctE08Bm4Zd:-Mt46O3bDSBpr-SjRTZF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20dc396bfe480734d4e61db6effd2b9abe383d97/systems/trajectory_optimization/test/direct_transcription_test.cc#L754)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Spurious blank line?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16333)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16333#-Mt3ZMs58QBSy-0jt6No:-Mt4GvDjE9oD36EwdyhX:b-3hz6nx) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I almost asked about it.  If we can make that happen with a reasonable amount of effort, I'd like to do it.
</blockquote></details>

OK I just took a look.  It seems like the type_caster infrastructure is predominantly used in cases where the conversion results in a copy, but here we would want the conversion to result in a reference.  I think the code as-is is probably the right way to go.

---

**Pull request merged**
