### PR TITLE
Polished LcmRecieveThread Comments and Switched to use Drake's logger.

### PR DESCRIPTION
**Pull request by liangfok**
Just some minor fixes as I prepare for the major surgery required by #3546.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3599)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@david-german-tri for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3599#-:-KSgUuid-O4mWGaPrf1c:b-1gbpvm)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3599#-:-KSgb_UxWZ6Q1hwAZAee:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3599#-:-KSgcNI5zag5FJ6St-PI:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Merging now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3599#-:-KSgcW_UjDKKPxczKREv:b4joi5f)*

**Pull request merged**
