### PR TITLE
[parsing] Route SDFormat warnings through DiagnosticPolicy

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This will allow us to more easily toggle their strictness.

Towards #16784.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16819)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typo

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16819#-:-MyPPGkdAp5sy8D-nNVG:bb7ao1f)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[tools/workspace/sdformat/patches/deprecation_unit_testing.patch, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16819#-MyPNrxV9VqaY6ZZxjb_:-MyPNrxV9VqaY6ZZxjba:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/bd9b62663496eb24ffbd87bb19f79f532d4faf1a/tools/workspace/sdformat/patches/deprecation_unit_testing.patch#L5)):*
> ```Diff
> When writing unit tests to excercise SDFormat deprecation notices, we can't
> rely on any _actually_ deprecated elements, because they will disappear in
> a future upstream release. Therefore, we inject a Drakep-specific element
> ```

typo



_Code quote:_
```Diff
Drakep
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16819)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16819#-:-MyhSx6Z3_D2UdRUFFJq:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[multibody/parsing/detail_sdf_parser.cc, line 166 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16819#-MyhEgDu7iiXZIpR3lRS:-MyhEgDv6yUIzpay-T5u:bs6ptip) ([raw file](https://github.com/robotlocomotion/drake/blob/b341ede8dce7f37312efbbf5ba9ad58d86619ea9/multibody/parsing/detail_sdf_parser.cc#L166)):*
> ```cpp
>     case sdf::ErrorCode::ELEMENT_INCORRECT_TYPE: {
>       // TODO(#15018): Change unrecognized elements to become an error on or
>       // after 2022-02-01. There is no error code dedicated solely to such
> ```

minor:  We're already after this date so it's odd/unnecessary to mention it.



_Suggestion:_
```cpp
      // TODO(#15018): Change unrecognized elements to become an error.
      // There is no error code dedicated solely to such
```
___
*[multibody/parsing/detail_sdf_parser.cc, line 1379 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16819#-MyhEz7j05_BLPmhtQGD:-MyhEz7j05_BLPmhtQGE:b-q4o0xo) ([raw file](https://github.com/robotlocomotion/drake/blob/b341ede8dce7f37312efbbf5ba9ad58d86619ea9/multibody/parsing/detail_sdf_parser.cc#L1379)):*
> ```cpp
>   // sdf::Errors collection later, we will categorize certain kinds of reports
>   // (e.g., deprecations) back to a DiagnosticPolicy::Warning instead of Error.
>   // That filter is specified in our IsError() helper, above.
> ```

BTW:  Thanks for this comment; it really helps make this comprehensible.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16819)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16819)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
