### PR TITLE
Scale the IPOPT build parallelism to suit the machine.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5107)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/ipopt.BUILD, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5107#-KcUrQpk7_uR0LipIkUr:-KcUrQpk7_uR0LipIkUs:b-xn8bib) ([raw file](https://github.com/robotlocomotion/drake/blob/4a67d88766fa81999fe6d15d5f260ee3b83387e5/tools/ipopt.BUILD#L103)):*
> ```
> BUILD_IPOPT_CMD = (
>     CDEXEC + " `pwd`/external/ipopt/configure --enable-shared=no 2> /dev/null" +
>     " && " + CDEXEC + " make -j $$[$$(nproc)+1/2] 2> /dev/null" +
> ```

Parentheses around nproc+1?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5107)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/ipopt.BUILD, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5107#-KcUrQpk7_uR0LipIkUr:-KcUsqpCwxqQczwGWIp9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a67d88766fa81999fe6d15d5f260ee3b83387e5/tools/ipopt.BUILD#L103)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Parentheses around nproc+1?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5107)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5107#-:-KcUtB56qCP5wToaR4NN:bnfp4nl)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5107)*

**Comment by david-german-tri** [comment]
Still running, but this looks likely to have made a big difference:

https://drake-jenkins.csail.mit.edu/job/mac-clang-bazel-experimental/21/

**Comment by jamiesnape** [comment]
``ERROR: /Users/elcapitan/workspace/mac-clang-bazel-experimental/_bazel_elcapitan/eb73579f384493bf373ed9fd07977c51/external/ipopt/BUILD:107:1: Couldn't build file external/ipopt/include/coin/AmplTNLP.hpp: Executing genrule @ipopt//:build_with_autotools failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f /Users/elcapitan/workspace/mac-clang-bazel-experimental/_bazel_elcapitan/eb73579f384493bf373ed9fd07977c51/bazel-sandbox/4c651b6a-da33-42fb-96a4-6216a04d5e78-789/sandbox.sb ... (remaining 3 argument(s) skipped).``

**Comment by jamiesnape** [comment]
I forgot, there is no `nproc` on Mac.

**Comment by jwnimmer-tri** [comment]
Maybe `nproc || echo 2` then?  :burn:

**Comment by david-german-tri** [comment]
Pushed another attempt.

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Seems to be taking 45 minutes to compile ipopt on Mac.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5107#-:-KcYCUpYkWXUX9DwjOQ_:bnfp4nl)*

**Comment by david-german-tri** [comment]
> Seems to be taking 45 minutes to compile ipopt on Mac.

That's not really an improvement.  I'll continue thinking about how to make this better.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-open-source please

**Comment by jamiesnape** [comment]
Since my quad-core Mac almost just died trying to compile ipopt, I think we should consider merging this even if it does not solve the original problem.

**Comment by david-german-tri** [comment]
Fair enough.  self :lgtm: and merging.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5107#-:-Kd2FYZqe6Q9ynt7dhAl:b-s2bqqf)*

**Pull request merged**
