### PR TITLE
[install] Promote unknown-path warnings to errors

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The build system should never just give up and print to the console.

Follow-up to prevent #19836 from slipping through next time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19861)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19861#-:-NaNGOLfBkqK3BmkAYMW:b919xhi)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19861#-NaNGOnS9ooRAl5fAwXO:-NaNGOnT-VeKdkYsqG9g:byzlyqp) (no related file):*
Working

Manually testing on macOS.  (The jar files there are handled differently than Ubuntu.)

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19861)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19861#-NaNGOnS9ooRAl5fAwXO:-NaNJe787zPVX0ORPRZH:b-osts2e) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Manually testing on macOS.  (The jar files there are handled differently than Ubuntu.)
</blockquote></details>

Looks good.  The installed files and their locations are identical on master vs this branch.

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19861#-:-NahgpsN0I7MMNVpTSmk:bnfp4nl)* status: needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
Recommending +@sherm1 for Wednesday platform review, since I'm on-call tomorrow.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19861#-:-NahgulA7956QKiq5GUu:bvswzkm)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Looks fine, if mysterious -- platform rubber stamp :lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19861#-:-Nam2FOT4WuX0pxCnBmN:b-9m8102)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Pull request merged**
