### PR TITLE
[fem] Support Schur complement in PETSc

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for sole review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230#-:-Mr0q6yB3yc02b-tJfnQ:b8oodom)* status: LGTM missing from assignee amcastro-tri, missing label for release notes (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/test/deformable_box_test.cc, line 156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr0yUI-DplvrR8irJJI:-Mr0yUI-DplvrR8irJJJ:bqevegr) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/test/deformable_box_test.cc#L156)):*
> ```cpp
>   const auto& plant_context = plant_->GetMyContextFromRoot(diagram_context);
>   /* Run simulation for long enough to reach steady state. */
>   simulator.AdvanceTo(1.0);
> ```

BTW, changing the internal data representation in `SchurComplement` rendered the original tolerance for this test too tight. I let the simulation settle down a bit more to satisfy the tolerance.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 3 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h, line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3X5lpBbdUiLHTxs6I:-Mr3X5lqE2BIIIFDNiBE:beulq2b) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h#L145)):*
> ```objc
>    "eliminated_indexes". */
>   SchurComplement<double> CalcSchurComplement(
>       const std::vector<int>& eliminated_indexes,
> ```

I believe this needs more documentation. The docs to ISCreateBlock() used in the source document idx as: "one for each block, the integers contain the index of the first entry of each block **divided by the block size**". Therefore clear `block_size` here is important and should show in the documentation. That is, the indexes stored by these vectors are "block indexes"?
___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3qDLZ-rVm2fNoh0VH:-Mr3qDLZ-rVm2fNoh0VI:b-ym7730) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L247)):*
> ```cpp
>     Mat matrix_dense;
>     AssembleIfNecessary();
>     MatConvert(owned_matrix_, MATSEQDENSE, MAT_INITIAL_MATRIX, &matrix_dense);
> ```

I wonder if we could skip all these conversions to dense matrices.

With MatGetRowIJ() and MatSeqAIJGetArray() I believe you could get all data you'd need to convert `this` matrix into an Eigen::SparseMatrix. From there you could use the utilities in `matrix_utilities.h`, as you did in DeformableRigidManager::CalcFreeMotionTangentMatrixSchurComplement() to get those Eigen blocks in SparseMatrix format. With that SchurComplement would not need to be updated and probably is more efficient?

I'd love to be able to use PETSc operations, but it seems like in this case it's not advantageous over using Eigen.

WDYT?
___
*[multibody/fixed_fem/dev/schur_complement.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3KbZz4UMKQjEpPRG-:-Mr3KbZz4UMKQjEpPRG0:b-6ajw84) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/schur_complement.h#L70)):*
> ```objc
>   // TODO(xuchenhan-tri): Investigate the sparsity pattern of D⁻¹Bᵀ with actual
>   //  meshes.
>   MatrixX<T> D_complement_{};          // A - BD⁻¹Bᵀ.
> ```

I wonder if you've been able to measure any impact on performance from this change in your dev branch.
___
*[multibody/fixed_fem/dev/test/deformable_box_test.cc, line 156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr0yUI-DplvrR8irJJI:-Mr3MJUc8mGER31Han3C:b-xfzc66) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/test/deformable_box_test.cc#L156)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, changing the internal data representation in `SchurComplement` rendered the original tolerance for this test too tight. I let the simulation settle down a bit more to satisfy the tolerance.
</blockquote></details>

It surprises me a bit that this change of "structure" would significantly affects the result of these tests since you are using direct solvers in both implementations. Are you saying that the very small round-off errors are enough to explain this? is it because the original tolerances used in these tests where tight to round-off errors?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3shK-1W5uitsXkTUN:-Mr3shK0-IAD9IAd0uQy:b-1fcueg) (no related file):*
It'd seem that PETSc is against building the Schur complement of a matrix directly (and yes, for good reasons). 
I wonder if you saw this documentation?: https://petsc.org/release/docs/manualpages/KSP/MatCreateSchurComplement.html

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3shK-1W5uitsXkTUN:-Mr4AWe0EHJrdt33cQI6:b-3ecqtn) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

It'd seem that PETSc is against building the Schur complement of a matrix directly (and yes, for good reasons). 
I wonder if you saw this documentation?: https://petsc.org/release/docs/manualpages/KSP/MatCreateSchurComplement.html

</blockquote></details>

Yes I saw this. That's why I hand-rolled my own schur complement.

---
___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h, line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3X5lpBbdUiLHTxs6I:-Mr4C3MI4TQ4QrQJDYuG:b9ki7jl) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h#L145)):*
> the index of the first entry of each block divided by the block size

This is exactly the block row/column index. The doc of this method explains that `eliminated_indexes` and `non_eliminated_indexes` corresponds to block row/column indexes of A,B and D. 

I agree the wording of the doc is awkward, but I believe it is accurate. Any suggestions on improvement would def be welcomed.
___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3qDLZ-rVm2fNoh0VH:-Mr4Dwes1XRsvIOPpnme:by0km7a) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L247)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I wonder if we could skip all these conversions to dense matrices.

With MatGetRowIJ() and MatSeqAIJGetArray() I believe you could get all data you'd need to convert `this` matrix into an Eigen::SparseMatrix. From there you could use the utilities in `matrix_utilities.h`, as you did in DeformableRigidManager::CalcFreeMotionTangentMatrixSchurComplement() to get those Eigen blocks in SparseMatrix format. With that SchurComplement would not need to be updated and probably is more efficient?

I'd love to be able to use PETSc operations, but it seems like in this case it's not advantageous over using Eigen.

WDYT?
</blockquote></details>

From my experience from doing the Eigen vs. PETSc benchmark, eigen sparse doesn't really provide any substantial gain over eigen dense on problems of the scale we care about right now. That puts a big question mark on the benefits of using Eigen here.

IMO, the drawbacks of using eigen sparse here is more clear:
1. More, harder to read code -- we'd have to extract the blocks and then assemble them, whereas right now it's three calls to MatCreateSubMatrix.
2. We can't use Cholesky with eigen sparse for license issues. We'd have to fall back to LU.
3. To use the permute utility, I'd need to make a copy of the eigen matrix. Not clear whether that's a win on performance even if sparsity helps.

I'd be happy to put a todo here to investigate this further in the future, but right now it seems the cons overweigh the pros.
___
*[multibody/fixed_fem/dev/schur_complement.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3KbZz4UMKQjEpPRG-:-Mr4BNjs5Qn7EwLmn3rG:bceo29v) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/schur_complement.h#L70)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I wonder if you've been able to measure any impact on performance from this change in your dev branch.
</blockquote></details>

I wasn't able to see a meaningful difference. Apparently, there's no much gain from using sparse matrix with the size of the problem we are dealing with.
___
*[multibody/fixed_fem/dev/test/deformable_box_test.cc, line 156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr0yUI-DplvrR8irJJI:-Mr4Bdo_5O2C9-AQPqi0:b31vcvo) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/test/deformable_box_test.cc#L156)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

It surprises me a bit that this change of "structure" would significantly affects the result of these tests since you are using direct solvers in both implementations. Are you saying that the very small round-off errors are enough to explain this? is it because the original tolerances used in these tests where tight to round-off errors?
</blockquote></details>

Yes, the original tolerance was quite tight. I think it's reasonable that the change from sparse to dense solver tip the error over the line.

**Review by xuchenhan-tri — COMMENTED** [review]
@amcastro-tri I'm hope to iterate on this PR some more today if that's possible. Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230#-:-Mr8qfb00PMTkr__qUx_:buljj5z)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 3 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h, line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3X5lpBbdUiLHTxs6I:-Mr95KF4Et-2NaQbvg1y:bm7dibj) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h#L145)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> the index of the first entry of each block divided by the block size

This is exactly the block row/column index. The doc of this method explains that `eliminated_indexes` and `non_eliminated_indexes` corresponds to block row/column indexes of A,B and D. 

I agree the wording of the doc is awkward, but I believe it is accurate. Any suggestions on improvement would def be welcomed.
</blockquote></details>

sorry, I totally missed the word "block" here. Not sure if it could be improved. 
Maybe the variable names could be improved? what about:
 - eliminated_indexes --> D_block_indexes.
 - non_eliminated_indexes --> A_block_indexes.

And maybe instead of using the wording eliminated/non-eliminated here, simply recall what system of equations this Schur complement helps us solve. That is, probably re-use the docs form the Schur complement here, specifically:
```
Given a linear system of equations Mz = c that can be written in block form
as:
    Ax + By  =  a     (1)
    Bᵀx + Dy =  0     (2)
where M = [A B; Bᵀ D], zᵀ = [xᵀ yᵀ], cᵀ = [aᵀ 0ᵀ]

```
___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3qDLZ-rVm2fNoh0VH:-Mr96jLz4JTVNQikSKjW:bs2gtlp) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L247)):*
> MatCreateSubMatrix() doesn't support matrix of type MATSEQSBAIJ.

Does it support MATSEQAIJ? could we convert to that instead?

I couldn't find the piece of docs that list the supported types for MatCreateSubMatrix(). Do you know how to find them?
___
*[multibody/fixed_fem/dev/schur_complement.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3KbZz4UMKQjEpPRG-:-Mr97m9R6gYBTYwztQdZ:b-dtfex4) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/schur_complement.h#L70)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I wasn't able to see a meaningful difference. Apparently, there's no much gain from using sparse matrix with the size of the problem we are dealing with.
</blockquote></details>

from your experiments, do you know when it starts to matter? I'm wondering if we could at least capture your knowledge in a TODO somewhere.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr98h9q2iWgqAEKT0fa:-Mr98h9q2iWgqAEKT0fb:b-r89a2y) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L174)):*
> ```cpp
>   unique_ptr<PetscSymmetricBlockSparseMatrix> A = MakeBlockSparseMatrix();
>   const vector<int> eliminated = {2};
>   const vector<int> rest = {0, 1};
> ```

minor, probably worth it to use non consecutive indexes:
eliminated = {1}, rest = {0, 2}

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 5 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr9Aby9-mPauOupB7m7:-Mr9Aby9-mPauOupB7m8:b-r7gz6y) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L286)):*
> ```cpp
>     ISDestroy(&is1);
> 
>     return SchurComplement(move(D_complement), move(neg_Dinv_B_transpose));
> ```

if somehow you manage to make PETSc deal with `neg_Dinv_B_transpose` as a sparse matrix, it might be worth to convert it to Eigen::SparseMatrix and instantiate the Schur complement with D_complement as dense and neg_Dinv_B_transpose as sparse.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h, line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3X5lpBbdUiLHTxs6I:-Mr9H_C7BlnLxzp7u16R:b-sc3okm) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h#L145)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sorry, I totally missed the word "block" here. Not sure if it could be improved. 
Maybe the variable names could be improved? what about:
 - eliminated_indexes --> D_block_indexes.
 - non_eliminated_indexes --> A_block_indexes.

And maybe instead of using the wording eliminated/non-eliminated here, simply recall what system of equations this Schur complement helps us solve. That is, probably re-use the docs form the Schur complement here, specifically:
```
Given a linear system of equations Mz = c that can be written in block form
as:
    Ax + By  =  a     (1)
    Bᵀx + Dy =  0     (2)
where M = [A B; Bᵀ D], zᵀ = [xᵀ yᵀ], cᵀ = [aᵀ 0ᵀ]

```
</blockquote></details>

Thanks for the suggestion. I rephrased. PTAL.
___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3qDLZ-rVm2fNoh0VH:-Mr9Hd5S2JMHk_nUhicp:b88mkjn) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L247)):*
I don't think so. Naturally, using SEQAIJ was the first thing I tried.

There's one step in the algorithm that doesn't support SEQAIJ, I think it's this step, but I'm not 100% sure.

> I couldn't find the piece of docs that list the supported types for MatCreateSubMatrix(). Do you know how to find them?

Nope, more often than not, I find out things like through an error message.
___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr9Aby9-mPauOupB7m7:-Mr9INjv5k0x1_Fz52-g:b-u3x9fe) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L286)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

if somehow you manage to make PETSc deal with `neg_Dinv_B_transpose` as a sparse matrix, it might be worth to convert it to Eigen::SparseMatrix and instantiate the Schur complement with D_complement as dense and neg_Dinv_B_transpose as sparse.
</blockquote></details>

See the thread above.
___
*[multibody/fixed_fem/dev/schur_complement.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3KbZz4UMKQjEpPRG-:-Mr9IRcX6bA6aLhTCBj1:bl4yaau) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/schur_complement.h#L70)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

from your experiments, do you know when it starts to matter? I'm wondering if we could at least capture your knowledge in a TODO somewhere.
</blockquote></details>

If we increase the size of the problem, operations like building and solving the tangent matrix become unreasonably slow for interactive simulation long before the schur complement step becomes a problem.
___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr98h9q2iWgqAEKT0fa:-Mr9Kfo-6i4jtxfOXlza:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L174)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, probably worth it to use non consecutive indexes:
eliminated = {1}, rest = {0, 2}
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
Comments addressed. PTAL, thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230#-:-Mr9MHGV5r6HZ3uQOO2-:b-pr0h6k)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230#-:-Mr9XJ4WEBOoMuF5mBHY:bg7igkv)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3qDLZ-rVm2fNoh0VH:-Mr9WB0B93IGhsiJtZEE:bfv6yhm) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L247)):*
> There's one step in the algorithm that doesn't support SEQAIJ

Meaning, your unit test does not pass. If you happen to know how it fails (unit test fails or exception is thrown) probably worth placing a note here.

> Naturally, using SEQAIJ was the first thing I tried.

It looks you tried it all then. We can always revisit when profiling reveals this to be a bottle neck. 
___
*[multibody/fixed_fem/dev/schur_complement.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3KbZz4UMKQjEpPRG-:-Mr9XCqQBniRehfef3o_:b-kufkx2) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/schur_complement.h#L70)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

If we increase the size of the problem, operations like building and solving the tangent matrix become unreasonably slow for interactive simulation long before the schur complement step becomes a problem.
</blockquote></details>

I see, thanks.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3qDLZ-rVm2fNoh0VH:-Mr9b2Bl4ccQEG1jA4_2:b-yzoj1y) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L247)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> There's one step in the algorithm that doesn't support SEQAIJ

Meaning, your unit test does not pass. If you happen to know how it fails (unit test fails or exception is thrown) probably worth placing a note here.

> Naturally, using SEQAIJ was the first thing I tried.

It looks you tried it all then. We can always revisit when profiling reveals this to be a bottle neck. 

</blockquote></details>

I revisited this to see why SEQAIJ is no good. It turns out it's because KSPMatSolve requires the dense right hand side.

That means we don't need dense matrices all the way. So I changed to SEQBAIJ (supposedly more efficient than SEQAIJ from my profiling) where possible. Not sure what the implication on performance is, but I think either way it doesn't matter much.
___
*[multibody/fixed_fem/dev/schur_complement.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr3KbZz4UMKQjEpPRG-:-Mr9b7_y1nZo7RqN8s0O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/04079dbc8dfdd0953d21b0a1cdde93dfe12a1c62/multibody/fixed_fem/dev/schur_complement.h#L70)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I see, thanks.
</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 246 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr9nSc59k_1k1o7a0ld:-Mr9nSc59k_1k1o7a0le:b26gn1m) ([raw file](https://github.com/robotlocomotion/drake/blob/2edc271f110436c924a7d967279d053c6fa2da67/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L246)):*
> ```cpp
>     AssembleIfNecessary();
>     Mat matrix_sparse;
>     MatConvert(owned_matrix_, MATSEQBAIJ, MAT_INITIAL_MATRIX, &matrix_sparse);
> ```

do we need convert now? isn't our owned_matrix_ of type MATSEQBAIJ already?



_Code quote:_
```cpp
MATSEQBAIJ
```
___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 177 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr9lwFqBw92EwjRBToL:-Mr9lwFqBw92EwjRBToM:b-tg45dx) ([raw file](https://github.com/robotlocomotion/drake/blob/2edc271f110436c924a7d967279d053c6fa2da67/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L177)):*
> ```cpp
>  We solve the same linear system with multiple right hand sides. The solution
>  from using threads should be the same as those from serial. */
> GTEST_TEST(PetscSymmetricBlockSparseMatrixTest, MultiThreadTest) {
> ```

is this part of this PR? should I review?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 2 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, line 246 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr9nSc59k_1k1o7a0ld:-Mr9nizJD27XJ13Fd9o8:bf11d0a) ([raw file](https://github.com/robotlocomotion/drake/blob/2edc271f110436c924a7d967279d053c6fa2da67/multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc#L246)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

do we need convert now? isn't our owned_matrix_ of type MATSEQBAIJ already?
</blockquote></details>

It's a subtle difference. 

owned_matrix_ is SEQSBAIJ where S stands for symmetric.
___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 177 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr9lwFqBw92EwjRBToL:-Mr9nsyH3nYw53CgO8A8:bruk73r) ([raw file](https://github.com/robotlocomotion/drake/blob/2edc271f110436c924a7d967279d053c6fa2da67/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L177)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

is this part of this PR? should I review?
</blockquote></details>

No, this is from rebasing off of master as the "rebase" icon indicates.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: 2 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 177 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr9lwFqBw92EwjRBToL:-Mr9oBBR0mH4oVCMET7Z:bdt3hvu) ([raw file](https://github.com/robotlocomotion/drake/blob/2edc271f110436c924a7d967279d053c6fa2da67/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L177)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

No, this is from rebasing off of master as the "rebase" icon indicates.
</blockquote></details>

These diffs only show up if you compare r2 and r3. If you compare base and r3, this goes away.

Honestly, IDK why reviewable shows diffs that aren't part of the PR.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 177 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr9lwFqBw92EwjRBToL:-Mr9ovFdB5Yys07KQZrw:blux19p) ([raw file](https://github.com/robotlocomotion/drake/blob/2edc271f110436c924a7d967279d053c6fa2da67/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L177)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

These diffs only show up if you compare r2 and r3. If you compare base and r3, this goes away.

Honestly, IDK why reviewable shows diffs that aren't part of the PR.
</blockquote></details>

I'm sure I was comparing with base, basic Reviewable 101 there. But also I wonder if it had to do with that the threads PR just merged and something was cached by Reviewable. In any case, I no longer see it.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16230)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 177 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16230#-Mr9lwFqBw92EwjRBToL:-Mr9pyc3DC1-IGjYNky0:b8rjhs4) ([raw file](https://github.com/robotlocomotion/drake/blob/2edc271f110436c924a7d967279d053c6fa2da67/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L177)):*
> I'm sure I was comparing with base, basic Reviewable 101 there. 

Oops. I didn't know that before =P

**Pull request merged**
