### PR TITLE
upgrade to gurobi 8.1.1

### LINKED ISSUE #9829: Use gurobi 8.0.1 or 8.1.0
Currently, Drake supports gurobi 8.0.0. But on gurobi website, they only provide download for gurobi 8.0.1 and 8.1.0 http://www.gurobi.com/downloads/gurobi-optimizer. We should upgrade our support on gurobi.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #9829

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11142)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-girder-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
https://github.com/RobotLocomotion/drake/blob/cf72b348e8a9bb9709286672904fc9512cf1036d/tools/dynamic_analysis/tsan.supp#L34 needs changing or removing (wait for CI or check locally).

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
Change https://github.com/RobotLocomotion/drake/blob/cf72b348e8a9bb9709286672904fc9512cf1036d/CMakeLists.txt#L312 to
`find_package(Gurobi 8.1.1 EXACT MODULE REQUIRED)`

Also update the `PATHS` in
https://github.com/RobotLocomotion/drake/blob/master/cmake/modules/FindGurobi.cmake.

**Comment by jamiesnape** [comment]
Looks like Mac CI has issues that I need to fix.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
`//attic/multibody/dev:global_inverse_kinematics_reachable_test` is not happy in various configurations (though not all).

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/job/mac-high-sierra-clang-bazel-experimental-everything-release/6/console is going to fail. Update
https://github.com/RobotLocomotion/drake/blob/4e15827d7078cf848757c7fce2a3f43fd4ac31bc/tools/workspace/gurobi/package-macos.BUILD.bazel.in#L33 and
https://github.com/RobotLocomotion/drake/blob/4e15827d7078cf848757c7fce2a3f43fd4ac31bc/tools/workspace/gurobi/package-macos.BUILD.bazel.in#L44

**Comment by jamiesnape** [comment]
Also `find_package(Gurobi 8.1.1 MODULE REQUIRED)` needs to ideally be `find_package(Gurobi 8.1.1 EXACT MODULE REQUIRED)`

**Comment by jamiesnape** [comment]
No need to run any Linux builds again. Just do the Mac ones once the PR is updated.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
Note that I need to merge this since we have to coordinate a change to CI.

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by jamiesnape** [comment]
Also https://github.com/RobotLocomotion/drake/blob/ee6c2e624fc1ec2e5c5fd12cbfd85c73ede4f496/solvers/solver_options.h#L34.

**Comment by jamiesnape** [comment]
`//solvers:mixed_integer_optimization_util_test` timed out on Mac. `TestMixedIntegerUtil/BilinearProductMcCormickEnvelopeMultipleChoiceTest.FeasiblePointTest/3` is taking seven minutes.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
BTW I am happy to put 8.0.1 on CI as well, if it helps.

**Comment by avalenzu** [comment]
I'll take a look. My guess is that I'll see improvements on the lower end of what they indicate, as the problems I was looking at solved in ~300 ms with 8.0.0.

**Comment by jamiesnape** [comment]
When we are 100% sure we want to upgrade, ping me and I will do the merge.

**Comment by avalenzu** [comment]
OK, I also see a performance degradation (albeit on a small problem) for the B-spline MIQP:
- Gurobi 8.0.0: ~150 ms
- Gurobi 8.1.1: ~260 ms

**Comment by jamiesnape** [comment]
Could I get an update on the status of this (so I know whether you are waiting on me to merge or if you are discussing whether to upgrade)?

**Comment by avalenzu** [comment]
Sorry, @jamiesnape! Per f2f with @hongkai-dai, we're not going to upgrade at this time.

**Pull request closed without merging**
