### PR TITLE
[doc] Add articles section to landing page

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17903)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.

If I've understood correctly, I've heard second-hand that you're interested in certain updates for Drake's main landing page, e.g., adding links to blog posts?  (\CC @ToffeeAlbina-TRI @EvelynDixon-TRI). This is my attempt to transcribe those ideas into a specific change, using my own taste.

In terms of edits or suggestions on this, if it's easier to communicate your own ideas by pushing an extra patch or two to this branch, please go ahead.

**Review by RussTedrake — COMMENTED** [review]
:lgtm: i like the articles section!  

The specific request that I made was to update the gallery with the examples we've been accumulating at TRI.  The current gallery does not reflect our state of the art.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17903#-:-NBtfT6ODPI3t_RFI02j:b-l7n916)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please (also as one of the article authors!).

**Review by sherm1 — COMMENTED** [review]
I built the pages and checked the links. All good! Platform :lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17903#-:-NBwidM0EyLxIE8zyrVt:b-idh6b)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
