### PR TITLE
[wheel] Enable ClarabelSolver on Linux

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See also https://github.com/oxfordcontrol/Clarabel.cpp/pull/29.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20802)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware for feature review, please.

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: modulo comments about comments.

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-:-NoqstG76yu89ym_Wod4:b-do9ru2)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`tools/wheel/image/build-drake.sh` line 21 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-NoqrGpVCxZOsoYcpgyS:-NoqrGpVCxZOsoYcpgyT:brp5hqs) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5d6b60756383e441ac7cbc5b03d215f517e4037/tools/wheel/image/build-drake.sh#L21)):*
> ```Shell
> build --repo_env=SNOPT_PATH=git
> build --config=packaging
> # Our wheel Eigen is new enough to undo the Focal-specific removal of Clarabel.
> ```

If this is Focal-specific, does it merit a "TODO: remove when we drop Focal" comment?
___
*[`tools/wheel/test/tests/sanity-test.py` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-NoqrYmN79pCVdMQzLcL:-NoqrYmN79pCVdMQzLcM:bo8x8er) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5d6b60756383e441ac7cbc5b03d215f517e4037/tools/wheel/test/tests/sanity-test.py#L14)):*
> ```Python
> assert pydrake.all.SnoptSolver().available(), 'Missing SNOPT'
> 
> # Once we drop Focal and its nerfs, we won't need this sanity-check anymore.
> ```

...although TBH I don't see the benefit to not just retaining the test indefinitely, if it's expected to always work. That would be in line with the assertions for MOSEK and SNOPT...



_Suggestion:_
```Python
# TODO: Once we drop Focal
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20802)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`tools/wheel/image/build-drake.sh` line 21 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-NoqrGpVCxZOsoYcpgyS:-Nor3qM269puAh3rknZ0:b-1wkf8h) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5d6b60756383e441ac7cbc5b03d215f517e4037/tools/wheel/image/build-drake.sh#L21)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

If this is Focal-specific, does it merit a "TODO: remove when we drop Focal" comment?
</blockquote></details>

When we drop an OS version, we grep the entire source tree for mentions of it and deal with each one in turn, so we don't necessarily need to TODO keyword every mention of the OS -- any mention of the OS implies a corrective action when we drop it, even without a TODO token.
___
*[`tools/wheel/test/tests/sanity-test.py` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-NoqrYmN79pCVdMQzLcL:-Nor4LvUBp5WDc-xCsNO:b-ydocja) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5d6b60756383e441ac7cbc5b03d215f517e4037/tools/wheel/test/tests/sanity-test.py#L14)):*
> That would be in line with the assertions for MOSEK and SNOPT...

If the point is about consistency, then I'd argue that keeping the test is not consistent.

Here is the status quo of the solvers:
- CLP: enabled by default, with an undocumented opt-out flag
- CSDP: "
- IPOPT: "
- NLOPT: "
- OSQP: "
- SCS: "
- CLARABEL: enabled by default, but disabled on non-wheel focal
- MOSEK: disabled by default, enabled in packaging
- SNOPT:  disabled by default, enabled in packaging
- GUROBI:  disabled by default

Right now CLARABEL is an outlier, so we have a special-purpose tests.

Once we drop Focal and CLARABEL joins its 6 other vanilla friends, it would be inconsistent to still have a test for it.  Either we have sanity checks for all 9 solvers that should be enabled, or we only have tests for the 2 that are sensitive to the build flavor.

Would you prefer that I add the check for all 9?  I could do that in this PR.

If not, then it seems to me like the current proposal is self-consistent.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20802)* status: needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`tools/wheel/test/tests/sanity-test.py` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-NoqrYmN79pCVdMQzLcL:-Norz4pZ2iNx33i1UA0b:bmzlqwi) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5d6b60756383e441ac7cbc5b03d215f517e4037/tools/wheel/test/tests/sanity-test.py#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> That would be in line with the assertions for MOSEK and SNOPT...

If the point is about consistency, then I'd argue that keeping the test is not consistent.

Here is the status quo of the solvers:
- CLP: enabled by default, with an undocumented opt-out flag
- CSDP: "
- IPOPT: "
- NLOPT: "
- OSQP: "
- SCS: "
- CLARABEL: enabled by default, but disabled on non-wheel focal
- MOSEK: disabled by default, enabled in packaging
- SNOPT:  disabled by default, enabled in packaging
- GUROBI:  disabled by default

Right now CLARABEL is an outlier, so we have a special-purpose tests.

Once we drop Focal and CLARABEL joins its 6 other vanilla friends, it would be inconsistent to still have a test for it.  Either we have sanity checks for all 9 solvers that should be enabled, or we only have tests for the 2 that are sensitive to the build flavor.

Would you prefer that I add the check for all 9?  I could do that in this PR.

If not, then it seems to me like the current proposal is self-consistent.
</blockquote></details>

Okay, so it would fall under "Basic sanity checks". I could go either way; it seems pretty harmless and inexpensive to ask if the solver(s) is (are) present, but up to you whether you think that's valuable.

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-:-NotxJTG0Zgu9N4u_qlG:bfqkacy)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`tools/wheel/test/tests/sanity-test.py` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-NoqrYmN79pCVdMQzLcL:-Notx7kBEISopzF0ibY7:b-lmqtm3) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5d6b60756383e441ac7cbc5b03d215f517e4037/tools/wheel/test/tests/sanity-test.py#L14)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Okay, so it would fall under "Basic sanity checks". I could go either way; it seems pretty harmless and inexpensive to ask if the solver(s) is (are) present, but up to you whether you think that's valuable.
</blockquote></details>

I'll stick with dropping it, but I amended the comment slightly.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-:-NowU0xS4MWtkX9C0IQk:bnfp4nl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
@jwnimmer-tri this PR needs a rebase.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20802#-:-NowU91p3tUhRV5qXkAK:b9hf52y)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Thanks!   I realized I failed to push yesterday when responding to feature review, so my comment fix actually only made it in to the most recent push, which therefore was more than just a bland rebase.

**Pull request merged**
