### PR TITLE
[common] Provide fmt helper for consistent floating point output

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19446.

See also https://github.com/fmtlib/fmt/issues/3456.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19454)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
Schweet. I'll use this in the inertia xml rewriter.
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19454#-:-NW3Cqyo0t26OFw5sc2k:bsa89mq)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19454#-:-NW3FmMI3IXalnk7jC27:b4mx0my)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[`solvers/sdpa_free_format.cc` line 893 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19454#-NW3FaeyBZg33_4jWUQC:-NW3Faf-64xmpVMoiaCO:b-yhotl3) ([raw file](https://github.com/RobotLocomotion/drake/blob/a4074d18db371a56c15e5180b69b7637fbe3ac93/solvers/sdpa_free_format.cc#L893)):*
> ```cpp
>       // ".0" when formatting integer-valued floating-point numbers. Force
>       // the ".0" in all cases by using the "#" option for floats, so that
>       // our output is consistent on all platforms.
> ```

nit I plan to fix this comment in the next push, but I want to let CI finish first.



_Suggestion:_
```cpp
      // Different versions of fmt disagree on whether to omit the trailing
      // ".0" when formatting integer-valued floating-point numbers, so we
      // must use a helper function that papers over it.
```

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19454#-:-NW3HP_w53LAtFQ6rOn5:bnfp4nl)* status: 2 unresolved discussions

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19454#-NW3GES92B4srwUvg1ca):*
BTW:  Should this go in the style guide?
___
*[`common/fmt.h` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19454#-NW3GtsI5FA1uYGffIAg:-NW3GtsI5FA1uYGffIAh:b-b0hmwg) ([raw file](https://github.com/RobotLocomotion/drake/blob/a4074d18db371a56c15e5180b69b7637fbe3ac93/common/fmt.h#L35)):*
> ```objc
> decimal point. Different versions of fmt disagree on whether to omit the
> trailing ".0" when formatting integer-valued floating-point numbers. */
> template <typename T>
> ```

minor:  Would it be better to bound T as `is_numeric` or even `is_floating_point`, to get the error at compile time rather than runtime?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19454)* status: 1 unresolved discussion

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19454#-NW3GES92B4srwUvg1ca):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  Should this go in the style guide?
</blockquote></details>

So far, we've been satisfied to notice in CI failures rather than the style guide.  I am OK with that.
___
*[`common/fmt.h` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19454#-NW3GtsI5FA1uYGffIAg:-NW3K8QhDWYNX9UqZc45:bqqptw3) ([raw file](https://github.com/RobotLocomotion/drake/blob/a4074d18db371a56c15e5180b69b7637fbe3ac93/common/fmt.h#L35)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Would it be better to bound T as `is_numeric` or even `is_floating_point`, to get the error at compile time rather than runtime?
</blockquote></details>

The validity of `fmt` syntax is already checked at compile-time, for sufficiently new versions of fmt (which our CI does cover).

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19454)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19454)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

**Pull request merged**
