### PR TITLE
State-feedback IiwaPlan

### PR DESCRIPTION
**Pull request by naveenoid**
First of the PR train needed for the monolithic pick_and_place demo. Refer to #3910

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5713)

### CODE REVIEW

**Comment by naveenoid** [comment]
@sammy-tri for feature and platform (since it is in dev). If you feel it can move out of dev I can move it too and go for the regular review.

**Comment by siyuanfeng-tri** [comment]
you are not really doing feedback, are you? i think you are just outputing q* and v*. and the measured state input port is only used to initialize the plan? 

i'd prefer a explicit init function that sets up the AbstractState part instead of doing this complicated check for uninitialized stuff in DoCalcUnrestrictedUpdate. but it's your call. also i feel like all three of us have written a version of this thing, and its doc, and its tests at least once somewhere... either we are stupid, or there is something very wrong with our setup. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KgtbENJ9uGumjIxYVyd:bmhpmbv)*

**Comment by naveenoid** [comment]
This is identical to IiwaPlanSource in logic..i.e maintain the current state if the previous plan is complete and dont replay plans. I need this component to overcome the direct feedthrough'ness of IiwaPlanSource. I agree this can be replaced. It was just the simplest debugged unit that I needed to keep sending plans intermittently from the state machine etc. 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-Kgu8YHb-HZHyvyKZHL4:b-ypgsz0)*

**Comment by siyuanfeng-tri** [comment]
sure. i know you have to get this through, but it pains me to see you have to put in so much effort into this... 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KguZi96IxwdrcfgDKl4:brfpyzp)*

**Comment by sammy-tri** [comment]
It does feel like a lot of effort to get to where we are...  I agree with Siyuan, it's a bit painful to see.  For your simulation, are the following items true?

(1) The initial configuration of the arm is known before simulation begins.
(2) The arm should remain in the initial configuration until a plan is generated and sent to the plan source.

If that's the case, I believe you could fix the input port of an unmodified IiwaPlanSource (or connect it to a ConstantValueSource) to an lcmt_iiwa_status which always reports the initial configuration (I think the result of this would be similar to Siyuan's suggestion to create an initialize method).

There are other options which could eliminate this duplication, like just deleting iiwa_controller and modifying IiwaPlanSource to speak (q,v) vectors for the state instead of lcmt_iiwa_status (and caching if in DoCalcUnrestrictedUpdate()), or modifying IiwaPlanSource to cache the value of the lcmt_iiwa_status message in DoCalcUnrestrictedUpdate().

A third option might be to finish reviewing and accept this PR and immediately open an issue on github to de-duplicate the implementations.  I think I could do it pretty quickly and keep iiwa_controller alive if I wanted to (not that I'm sure I want to).

I did a partial review and left some comments, but I think the meta-discussion here is more important right now.

---

Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KguYJUL5PjK_hC5q9lN:-KguYJUM9HGfIx0-RFsr:b-g2nzqs) ([raw file](https://github.com/robotlocomotion/drake/blob/ed0a7113d4c83fef9095ef871efb6eb1efcd4b20/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc#L51)):*
> ```cpp
>                    const std::vector<Eigen::VectorXd>& q,
>                    const std::vector<double>& wsg_positions)
>       : kIiwaTree(iiwa_tree),
> ```

I don't think const member variables should use the kConstant naming convention.  They're fixed for the lifetime of an object instance, not the duration of the program.  https://google.github.io/styleguide/cppguide.html#Constant_Names

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KguZ0QrEm-eKa8aYeva:-KguZ0Qstcq0QT0QPvrb:b-45870n) ([raw file](https://github.com/robotlocomotion/drake/blob/ed0a7113d4c83fef9095ef871efb6eb1efcd4b20/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc#L146)):*
> ```cpp
>       BuildCombinedPlant<double>(&iiwa_instance, &wsg_instance, &box_instance);
> 
>   auto plant_ =
> ```

This is a local variable and is named like a member variable (which happens throughout this function).

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KguZcHXFGzc6X9hnfRP:-KguZcHXFGzc6X9hnfRQ:bcyy7ze) ([raw file](https://github.com/robotlocomotion/drake/blob/ed0a7113d4c83fef9095ef871efb6eb1efcd4b20/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc#L160)):*
> ```cpp
>           Eigen::VectorXd::Zero(7));
>   builder.Connect(iiwa_zero_acceleration_source_->get_output_port(),
>                   plant_->get_iiwa_acceleration_input_port());
> ```

It's not clear to me why we use a zero source for acceleration instead of exposing the acceleration from the piecewise polynomial in the generated plan (from the plan source below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KguaPx168ZXhkRyhzYA:b-l3k5lo)*

**Comment by naveenoid** [comment]
So the key issue isnt the initial configuration itself. Its so that the arm stays in `a` configuration while some other part of the state machine is running. For instance, go to pre-grasp pose and then there is no plan for a bit while some other action is running. So this way I simply send a "empty" plan message and the plansource component I wrote holds the current configuration. I would strongly recommend the third option (that was what I wanted to do). I simply proceeded with this component to save the time in fixing downstream components affected by this change. 

---

Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KguiYNKe9sozQqXhFcV:bf5uobs)*

**Comment by sammy-tri** [comment]
If you send a plan to move to (for example) a pre-grasp pose, doesn't the existing IiwaPlanSource hold the arm at the final configuration of that plan until the next plan is received (without sending an empty message)?  I guess the empty plan message could create a "hold current position even if it's not the final state of the last received plan" command, which could be useful but wasn't an obvious use case to me from this code.  I'll admit if that is the case a fixed input status value wouldn't be sufficient.

---

Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KgulelWdjPfqcgEPQNa:b-fga13e)*

**Comment by siyuanfeng-tri** [comment]
er... this sounds increasingly fishy now. sending empty plan message sounds very wrong. 
i can't seem to grasp the bigger picture here. so naveen, feel free to tell me to shut up, and i will :) 
whatever you do, i want to make sure that each individual component can work independently of if they are wired together, or through lcm on different computers. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KgurySkxAuxgH7YlOeC:bklsnne)*

**Comment by sammy-tri** [comment]
If we switch the plan source to taking (q,v) instead of lcmt_iiwa_status we'd need an additional system in the Diagram to translate lcmt_iiwa_status into (q,v) when using LCM.   I don't think that bothers me much.

---

Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KguylSmzPBVTqeX61NS:b-7kd9zj)*

**Comment by naveenoid** [comment]
Im happy to talk to you both quickly on hangouts today if you need me to explain the need for this better. 

---

Review status: 1 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KguYJUL5PjK_hC5q9lN:-Kgy8gfUffWjkRgQmnCE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ed0a7113d4c83fef9095ef871efb6eb1efcd4b20/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc#L51)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think const member variables should use the kConstant naming convention.  They're fixed for the lifetime of an object instance, not the duration of the program.  https://google.github.io/styleguide/cppguide.html#Constant_Names
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KguZ0QrEm-eKa8aYeva:-Kgy8hLo_OQa_G7_pUlE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ed0a7113d4c83fef9095ef871efb6eb1efcd4b20/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc#L146)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This is a local variable and is named like a member variable (which happens throughout this function).
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KguZcHXFGzc6X9hnfRP:-Kgy8hrBNDJ3fvHHJomj:bgfjx45) ([raw file](https://github.com/robotlocomotion/drake/blob/ed0a7113d4c83fef9095ef871efb6eb1efcd4b20/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc#L160)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It's not clear to me why we use a zero source for acceleration instead of exposing the acceleration from the piecewise polynomial in the generated plan (from the plan source below).
</blockquote></details>

Fixed. Good point. Now the plan generator has an additional output port and that emits the second derivative of the plan as the acceleration input. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KgxbOGYs2FcY2ZQ6qmD:bwr7ua2)*

**Comment by naveenoid** [comment]
@siyuanfeng-tri : Short version - in a monolithic diagram, the plan generator is always given inputs from the previous component (the primitive system in my case). Hence when nothing is supposed to happen, the input ports basically receive an empty plan message. The ports always contain data here..

---

Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-Kgy9j9Ydo9WC6cSDA4z:bpws3bi)*

**Comment by sammy-tri** [comment]
The plan generator is always given an input in the LCM system too, though it's held to the previous message.  I'm not opposed to having a "stop" command to the plan source (at least, I don't think I am).  Does the primitive system know the position it wants the arm to hold at?  It could send a two-state plan with the same position which would achieve the same effect.

At any rate, the behavior of holding the current position on a zero state plan should be documented.  I'm leaning toward the "commit and immediately open an issue" course of action.  Will finish my review today as I can, but I'm in a lot of meetings so apologies if this drags on for a while.

---

Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KgyPjFDFgUWg0GGOmKd:b-pvmmw5)*

**Comment by siyuanfeng-tri** [comment]
i agree with sammy

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KgyXhR9xrenlCKXs0Hz:b-crn3b3)*

**Comment by sammy-tri** [comment]
Assuming we open an issue explaining that the source here needs to be back-merged with IiwaPlanSource and should never come out of dev/, the extra requirements which motivated the fork, and comments on the source and header noting the issue and not to move this as is, I think I'm good with it.  (I'd probably also be willing to take ownership of the issue).

Pending the other issues too.

---

Reviewed 1 of 7 files at r1, 2 of 3 files at r2.
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KgzHDIDI_mVhSlNM_Lr:-KgzHDIDI_mVhSlNM_Ls:bax0xfj) ([raw file](https://github.com/robotlocomotion/drake/blob/a3163d0e148e87cae9712a7ba30b2a2bf241cddc/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L25)):*
> ```Python
>     deps = [
>         "//drake/common/trajectories:piecewise_quaternion",
>         "//drake/examples/kuka_iiwa_arm:iiwa_plan_source",
> ```

This list looks *way* too long.  iiwa_plan_source seems particularly unlikely.  As do the schunk lcm types.  Can we pare it down a bit?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KgzHRtHwKf1sZEe3evo:-KgzHRtHwKf1sZEe3evp:b-od7bil) ([raw file](https://github.com/robotlocomotion/drake/blob/a3163d0e148e87cae9712a7ba30b2a2bf241cddc/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L52)):*
> ```Python
>     deps = [
>         "//drake/common/trajectories:piecewise_quaternion",
>         "//drake/examples/kuka_iiwa_arm:iiwa_plan_source",
> ```

This also seems longer than it needs to be.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/iiwa_state_feedback_plan.h, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KgzGVapmVtygJSh86Yu:-KgzGVapmVtygJSh86Yv:bx0asbv) ([raw file](https://github.com/robotlocomotion/drake/blob/a3163d0e148e87cae9712a7ba30b2a2bf241cddc/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/iiwa_state_feedback_plan.h#L21)):*
> ```objc
> /// state feedback.
> ///
> /// If no plan has been received, the system will create an initial
> ```

This should be clarified to indicate that this will happen any time a plan is received with no states (if that's the way this goes).

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc, line 153 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KgzGGYt98LWMuxVEvc5:-KgzGGYt98LWMuxVEvc6:b20i8ix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3163d0e148e87cae9712a7ba30b2a2bf241cddc/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc#L153)):*
> ```cpp
>   builder.Connect(plant->get_plant_output_port(),
>                   drake_visualizer->get_input_port(0));
>   auto iiwa_plan_source_ =
> ```

This is a local variable and is named like a member variable 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-KgzHYJdk6aMs4rHTlO1:b9c2ywt)*

**Comment by naveenoid** [comment]
Ive added some comments on this system filed #5736 (assigned to @sammy-tri for now). Hope that is ok for now.

---

Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KgzHDIDI_mVhSlNM_Lr:-Kgzr01_PZ4RaZNwvwbv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3163d0e148e87cae9712a7ba30b2a2bf241cddc/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L25)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This list looks *way* too long.  iiwa_plan_source seems particularly unlikely.  As do the schunk lcm types.  Can we pare it down a bit?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KgzHRtHwKf1sZEe3evo:-Kgzr0Xjcw3TsVO90ABA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3163d0e148e87cae9712a7ba30b2a2bf241cddc/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L52)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This also seems longer than it needs to be.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/iiwa_state_feedback_plan.h, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KgzGVapmVtygJSh86Yu:-KgzrZWzWAIpI06VXA1w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3163d0e148e87cae9712a7ba30b2a2bf241cddc/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/iiwa_state_feedback_plan.h#L21)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This should be clarified to indicate that this will happen any time a plan is received with no states (if that's the way this goes).
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc, line 153 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-KgzGGYt98LWMuxVEvc5:-Kgzghjm4bsIDgs_cinK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3163d0e148e87cae9712a7ba30b2a2bf241cddc/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/trajectory_generator_test.cc#L153)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This is a local variable and is named like a member variable 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-Kgzv3_EVTUoD0u9virc:b-q8emgz)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 1 of 7 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-Kh2hp4J1X54wr9E9X6J:bsf2vkf)*

**Comment by naveenoid** [comment]
-(status: curate commits before merging)  - moving to squash and merge.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5713#-:-Kh3IsRvuGIRPxhXxrmM:bgp0udb)*

**Pull request merged**
