### PR TITLE
Added FAQ entry for macOS build failure when Xcode's command line tools are not installed.

### PR DESCRIPTION
**Pull request by liangfok**
Since the error message does not immediately lend itself to the solution.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5978)

### CODE REVIEW

**Comment by liangfok** [comment]
+@soonho-tri for feature review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-:-KiuRtufH17P-oSkkv4l:bgak6vv)*

**Comment by soonho-tri** [comment]
I think this is related to the problem that @mwoehlke-kitware had. Please check https://drakedevelopers.slack.com/archives/C2PMBJVAN/p1493318666267154.

My understanding is that it happens because our OSX bazel-configuration only has the following `cxx_builtin_include_directory`: 

```
  cxx_builtin_include_directory: "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain"
  cxx_builtin_include_directory: "/usr/local/include"
  cxx_builtin_include_directory: "/usr/include"
  cxx_builtin_include_directory: "/System/Library/Frameworks"
  cxx_builtin_include_directory: "/Library/Frameworks"
```
(from https://github.com/RobotLocomotion/drake/blob/master/tools/CROSSTOOL#L362-L366)

while sometimes a user has a non-default active Xcode-developer directory which you can check by `xcode-select -p`. By default, it's `/Applications/Xcode.app/Contents/Developer` and that's what our OSX bazel-configuration expects.

My suggested solution to this problem is:

1. Ask users to install Xcode's command line tool. We can keep the current `xcode-select --install`.
2. Ask users to run `sudo xcode-select --reset`. We still need to explain what it does, "it resets to the default command line tools path, /Applications/Xcode.app/Contents/Developer".

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-:-KiuSBakLYk_kfVoID9g:bv7ptti)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978)*

**Comment by liangfok** [comment]
Done. Yes, it appears @mwoehlke-kitware ran into a similar issue. I updated the FAQ entry as suggested.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-:-Kiuh8J1HWAJSaVK8pRb:b-acv8oj)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-:-KiyrXtYL7bSqLG0cO3W:bnfp4nl)*

**Comment by soonho-tri** [comment]
It'd be great if we have another feature review from someone in Kitware. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-:-Kiyr_nHhMVCUOgwMcaw:b-2n68vb)*

**Comment by liangfok** [comment]
Sounds good. +@jamiesnape for a second feature review please. Thanks!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-:-KiytfhWSxeSNmhhresF:bff6308)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/faq.rst, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-Kj3D4bEh4uxIBZjMJgd:-Kj3D4bEh4uxIBZjMJge:b-miz1k0) ([raw file](https://github.com/robotlocomotion/drake/blob/5861c8ba329e4b06caacdba8b92107464613cb67/drake/doc/faq.rst#L13)):*
> ```reStructuredText
> .. _faq_osx_build_failure_missing_dependency_declarations:
> 
> Why Does Build Fail with "this rule is missing dependency declarations" on OSX?
> ```

BTW macOS now, not OSX, but no big deal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-:-Kj3DL5ZmaavxLLuO-01:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/faq.rst, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-Kj3IavcQyJH1JC7Cu2V:-Kj3IavcQyJH1JC7Cu2W:b-sbdlhs) ([raw file](https://github.com/robotlocomotion/drake/blob/5861c8ba329e4b06caacdba8b92107464613cb67/drake/doc/faq.rst#L20)):*
> ```reStructuredText
> 
>     $ bazel build ...
>     WARNING: /Users/liang/dev/drake-distro-1/drake/util/BUILD:63:1: target
> ```

FYI This WARNING line is not relevant to the failure, so might avoid some misleading questions if you removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978)*

**Comment by liangfok** [comment]
+@jwnimmer-tri for platform review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/faq.rst, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-Kj3D4bEh4uxIBZjMJgd:-Kj3KI0F9hirKsA8Wcus:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5861c8ba329e4b06caacdba8b92107464613cb67/drake/doc/faq.rst#L13)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW macOS now, not OSX, but no big deal.
</blockquote></details>

Done.

---

*[drake/doc/faq.rst, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-Kj3IavcQyJH1JC7Cu2V:-Kj3JewiFG7OO4LKjWhl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5861c8ba329e4b06caacdba8b92107464613cb67/drake/doc/faq.rst#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This WARNING line is not relevant to the failure, so might avoid some misleading questions if you removed it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-:-Kj3KJIXdTC8WqNTf41R:b-1bcdxl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5978#-:-Kj3LAeKUX7Z9N4ww-qL:bnfp4nl)*

**Pull request merged**
