### PR TITLE
Simplify divide-by-constant cases in Expression::Expand()

### PR DESCRIPTION
**Pull request by soonho-tri**
```
 Case Addition      : e =  (c₀ + ∑ᵢ (cᵢ * eᵢ)) / n
                        => c₀/n + ∑ᵢ (cᵢ / n * eᵢ)

 Case Multiplication: e =  (c₀ * ∏ᵢ (bᵢ * eᵢ)) / n
                        => c₀ / n * ∏ᵢ (bᵢ * eᵢ)

 Case Division      : e =  (e₁ / m) / n
                        => Recursively simplify e₁ / (n * m)

                      e =  (e₁ / e₂) / n
                        =  (e₁ / n) / e₂
                        => Recursively simplify (e₁ / n) and divide it by e₂
```

This is a part of the commits that we're migrating from the SOS (sum-of-squares) sprint.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6454)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6454#-:-KnjeZCRem-BnWFI6kdj:b7riqq)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6454#-:-Knjnnxh6Qvni3ilm8wU:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@ggould-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6454#-:-KnjnpBd8Z63Am4sjnTL:b-irfx5k)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by ggould-tri** [comment]
The logic and tests are clear and correct; :lgtm:.  One qualm, non-defect but a future consideration:

We now have a few "simplification" or "expansion" transforms (merging coefficients in addition, merging exponents in multiplication, this constant-pushdown operation).  I can still prove to myself that these transformations are acyclic, but that may not last.  If this goes further, we ought to assert some idempotency or fix-point condition for simplification and expansion operations.

(A conventional way to do this is to have a well-order over node types and count the number of times a depth-first traversal moves backward in that order; this count is then a nice total order on expressions.  We then assert that simplifying transforms are monotonic on this metric and are not reapplied at the same complexity; this provides an inductive proof of fixity, and is also testable.)

I don't think we are quite at the point where this is needed, but some time soon doing mental proofs of fixity on algebraic transforms is going to become a headache.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6454#-:-KnjulEepUcaZrhYO0Ix:bgttpw3)*

**Comment by soonho-tri** [comment]
Thanks for the point. I'll think about providing total ordering next time introducing non-trivial transformations.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6454#-:-KnkWgYBVK3X91-fM-qe:boqjc56)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please.
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please.

**Pull request merged**
