### PR TITLE
Fixes for Kuka IK demo

### LINKED ISSUE #3298: kuka_ik_demo does not run Debug builds
In Debug builds the `kuka_ik_demo` aborts with the message:
```
abort: failure at /home/amcastro/Drake/Master/drake-distro/drake/systems/trajectories/PiecewisePolynomial.cpp:13 in PiecewisePolynomial(): assertion 'segment_times.size() == (polynomials.size() + 1)' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by amcastro-tri**
Fixes #3298

I believe @sammy-tri said this demo would probably be removed. However I thought it'd be good to post this fix since I used @sammy-tri's code in simulation (#3290).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3304)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@sammy-tri for feature please.
+@david-german-tri for platform please (Tuesdays, though it's Monday night :-) ).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3304#-:-KQOGJul_swAUcDZUcA3:bf6c0fr)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 74 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3304#-KQQkoC9AzeX0Lzr3DPL:-KQQkoC9AzeX0Lzr3DPM:b-d75ftb) ([raw file](https://github.com/robotlocomotion/drake/blob/4088f6221b0942637d6629427d93790ce776ce41/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L74)):*
> ```cpp
>           // the next timestep at the time when we advance to the next
>           // piece.  In the event that we're at the end of the
>           // trajectory, this will be left 0.
> ```

I think this comment is at least out of date, since there's no special case for the end of the trajectory any more.  AFAICT, the code change itself is valid, since in PiecewisePolynomial::value(), it appears to clamp values of t such that the last polynomial will never be evaluated past the time at the back of the segment times vector.

I guess it might be nice to have an assert that like pp_traj.value(t[nT - 1] + 1.) is equal to pp_traj.value(t[nT - 1], but I'm not gonna block on that since it's not really this code's job to ensure PiecewisePolynomial.  The flip side is that if the last polynomial really did run off the end, the arm might hit something.

This has gotten pretty rambling for a note about an outdated comment.  I should stop now...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3304)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 74 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3304#-KQQkoC9AzeX0Lzr3DPL:-KQROE4c_sKPAoLy7e1P:bq6locj) ([raw file](https://github.com/robotlocomotion/drake/blob/4088f6221b0942637d6629427d93790ce776ce41/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L74)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I think this comment is at least out of date, since there's no special case for the end of the trajectory any more.  AFAICT, the code change itself is valid, since in PiecewisePolynomial::value(), it appears to clamp values of t such that the last polynomial will never be evaluated past the time at the back of the segment times vector.
> 
> I guess it might be nice to have an assert that like pp_traj.value(t[nT - 1] + 1.) is equal to pp_traj.value(t[nT - 1], but I'm not gonna block on that since it's not really this code's job to ensure PiecewisePolynomial.  The flip side is that if the last polynomial really did run off the end, the arm might hit something.
> 
> This has gotten pretty rambling for a note about an outdated comment.  I should stop now...
</details>
Good observation. This is my attempt to explaining that. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3304)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3304#-:-KQRQmvrN13MRDhseQqz:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3304#-:-KQRxsOOv8CY8wHx0Zmt:bnfp4nl)*

**Pull request merged**
