### PR TITLE
Include `-pthread` only for Linux build in Gurobi

### LINKED ISSUE #5183: Numerous Warnings Printed to Console When Building Drake on OSX Using Bazel
# Sample Output

```
INFO: From Linking drake/common/cond_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/trig_poly_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/double_overloads_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/trajectories/piecewise_polynomial_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/trajectories/exponential_plus_piecewise_polynomial_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/trajectories/piecewise_generation_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/math/autodiff_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/polynomial_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/math/cross_product_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/math/gradient_util_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/math/expmap_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/math/normalize_vector_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/autodiff_overloads_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/trajectories/qp_spline/spline_generation_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/math/rotation_conversion_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/math/jacobian_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/trajectories/piecewise_quaternion_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/collision/model_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/joints/joint_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/trajectories/piecewise_polynomial_trajectory_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/collision/fcl_model_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Compiling drake/automotive/automotive_simulator.cc:
drake/automotive/automotive_simulator.cc:337:20: warning: 'AddModelInstanceFromUrdfFile' is deprecated:
DRAKE DEPRECATED: Please use AddModelInstanceFromUrdfFileWithRpyJointToWorld(). [-Wdeprecated-declarations]
    parsers::urdf::AddModelInstanceFromUrdfFile(urdf_filepath,
                   ^
drake/automotive/automotive_simulator.cc:375:16: note: in instantiation of member function 'drake::automotive::AutomotiveSimulator<double>::Start' requested here
template class AutomotiveSimulator<double>;
               ^
./drake/multibody/parsers/urdf_parser.h:242:22: note: 'AddModelInstanceFromUrdfFile' has been explicitly marked deprecated here
ModelInstanceIdTable AddModelInstanceFromUrdfFile(
                     ^
1 warning generated.
INFO: From Linking drake/common/libcond.pic.a:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: bazel-out/osx-opt/bin/drake/common/_objs/cond/drake/common/cond.pic.o has no symbols
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for library: bazel-out/osx-opt/bin/drake/common/libcond.pic.a the table of contents is empty (no object file members in the library define global symbols)
INFO: From Linking drake/systems/framework/value_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/system_output_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/math/matrix_util_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/supervector_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/system_input_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/system_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/leaf_system_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/subvector_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/single_output_vector_source_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/parameters_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/continuous_state_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/leaf_context_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/discrete_state_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/cache_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/abstract_state_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/basic_vector_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_variables_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_variable_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_variable_overloading_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_substitution_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_mixing_scalar_types_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_formula_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_expression_differentiation_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_expression_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_environment_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/solvers/binding_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/symbolic_expression_matrix_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/common/monomial_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/examples/bouncing_ball/bouncing_ball_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/examples/bouncing_ball/ball_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/zero_order_hold_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/pass_through_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/multiplexer_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/integrator_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/linear_system_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/matrix_gain_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/gain_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/demultiplexer_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/constant_vector_source_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/constant_value_source_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/lcm/lcm_translator_dictionary_test:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/lcm/serializer_test:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/lcm/lcm_subscriber_system_test:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/lcm/lcm_publisher_system_test:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/affine_system_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/plants/spring_mass_system/spring_mass_system_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/sparsity_matrix_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/diagram_context_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/diagram_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/sensors/rotary_encoders_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/sensors/camera_info_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/framework/diagram_builder_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/trajectory_car_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/simple_car_to_euler_floating_joint_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/simple_car_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/single_lane_ego_and_agent_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/linear_car_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/idm_planner_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/simple_car_state_translator_test:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/endless_road_oracle_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/endless_road_car_to_euler_floating_joint_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/endless_road_car_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/curve2_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/adder_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/estimators/luenberger_observer_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/controllers/pid_controller_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/analysis/simulator_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/controllers/pid_controlled_system_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/estimators/kalman_filter_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/controllers/linear_quadratic_regulator_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/trajectory_source_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/signal_logger_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/analysis/explicit_euler_integrator_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/analysis/runge_kutta2_integrator_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/saturation_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/primitives/random_source_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/analysis/test/controlled_spring_mass_system/controlled_spring_mass_system_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/parsers/package_map_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rigid_body_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/controllers/gravity_compensator_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/rendering/pose_aggregator_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/sensors/depth_sensor_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/systems/sensors/gyroscope_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/test_kinematics_cache_checks:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rigid_body_frame_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rigid_body_tree_dynamics_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rigid_body_tree_kinematics_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rigid_body_tree_creation_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rbt_collisions_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rigid_body_constraint_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/collision/collision_filter_group_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rigid_body_plant/drake_visualizer_test:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rigid_body_plant/viewer_draw_translator_test:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/parsers/xml_util_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/parsers/urdf_parser_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/rigid_body_collision_clique_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/examples/QPInverseDynamicsForHumanoids/param_parsers/rigid_body_tree_alias_groups_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/parsers/parser_common_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/examples/QPInverseDynamicsForHumanoids/lcm_utils_test:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/benchmark_rigid_body_tree:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/automotive_simulator_test:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/debug_manipulator_dynamics:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/parsers/urdf_manipulator_dynamics_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/parsers/urdf_kinematics_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/multibody/parsers/urdf_collision_test:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Linking drake/automotive/automotive_demo:
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
```

### PR DESCRIPTION
**Pull request by soonho-tri**
Partially resolve #5183.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6605)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jamiesnape , feature-review please.
+@ericcousineau-tri , platform-review please (this is a small one so I ask for reviews simultaneously).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-:-KpR_fPrsIcH10XT-A2R:b-pjd9xl)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-:-KpRa_0Pp_uE2XqDlWKJ:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-:-KpRbJb8PPpdfO6Bg_8J:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
+@ggould-tri for final platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-:-KpRbRhQbFwlajLmWDd8:b-8oqncc)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-:-KpRdDn1M27cRkt5z_k6:bu0l6g6)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/gurobi.bzl, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-KpRkcYuYDvaVGVbXB7i:-KpRkcYuYDvaVGVbXB7j:bs27yzo) ([raw file](https://github.com/robotlocomotion/drake/blob/66922966b6eaf2b35a6456a5a43dd4b6dbe22aac/tools/gurobi.bzl#L58)):*
> ```Python
>         hdrs = hdrs,
>         includes = ["gurobi-distro/include"],
>         linkopts = {linkopts},
> ```

The error from `linux-xenial-clang-bazel-experimental-everything` is reproducible in CI. It's not reproducible on my Linux box though (probably due to different bazel-version?). Here is the error message:
```
ERROR: /home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-everything/_bazel_ubuntu/72006d3a037a9ba96fa2c794be82e69e/external/gurobi/BUILD:11:16: Traceback (most recent call last):
	File "/home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-everything/_bazel_ubuntu/72006d3a037a9ba96fa2c794be82e69e/external/gurobi/BUILD", line 6
		cc_library(name = "gurobi", srcs = ["gurobi-d..."], <4 more arguments>)
	File "/home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-everything/_bazel_ubuntu/72006d3a037a9ba96fa2c794be82e69e/external/gurobi/BUILD", line 11, in cc_library
		selector
name 'selector' is not defined (did you mean 'select'?).
```

@jamiesnape , I think a solution is to move the `select` from above to here. It will be:

```python
    BUILD = """
    hdrs = glob([
        "gurobi-distro/include/gurobi_c.h",
        "gurobi-distro/include/gurobi_c++.h",
    ])
    print("{warning}") if not hdrs else cc_library(
        name = "gurobi",
        srcs = {srcs},
        hdrs = hdrs,
        includes = ["gurobi-distro/include"],
        linkopts = select({
            "@drake//tools:linux": ["-pthread"],
            "@//conditions:default": [],
        })
        visibility = ["//visibility:public"],
    )
    """.format(warning = warning, srcs = srcs)
```

Do you think this is good?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-:-KpUdoIxNQ6hZqyD25Lu:b-rs4zsh)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[tools/gurobi.bzl, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-KpRkcYuYDvaVGVbXB7i:-KpUv78qbIeytQbRvd1j:bqun8l) ([raw file](https://github.com/robotlocomotion/drake/blob/66922966b6eaf2b35a6456a5a43dd4b6dbe22aac/tools/gurobi.bzl#L58)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

The error from `linux-xenial-clang-bazel-experimental-everything` is reproducible in CI. It's not reproducible on my Linux box though (probably due to different bazel-version?). Here is the error message:
```
ERROR: /home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-everything/_bazel_ubuntu/72006d3a037a9ba96fa2c794be82e69e/external/gurobi/BUILD:11:16: Traceback (most recent call last):
	File "/home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-everything/_bazel_ubuntu/72006d3a037a9ba96fa2c794be82e69e/external/gurobi/BUILD", line 6
		cc_library(name = "gurobi", srcs = ["gurobi-d..."], <4 more arguments>)
	File "/home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-everything/_bazel_ubuntu/72006d3a037a9ba96fa2c794be82e69e/external/gurobi/BUILD", line 11, in cc_library
		selector
name 'selector' is not defined (did you mean 'select'?).
```

@jamiesnape , I think a solution is to move the `select` from above to here. It will be:

```python
    BUILD = """
    hdrs = glob([
        "gurobi-distro/include/gurobi_c.h",
        "gurobi-distro/include/gurobi_c++.h",
    ])
    print("{warning}") if not hdrs else cc_library(
        name = "gurobi",
        srcs = {srcs},
        hdrs = hdrs,
        includes = ["gurobi-distro/include"],
        linkopts = select({
            "@drake//tools:linux": ["-pthread"],
            "@//conditions:default": [],
        })
        visibility = ["//visibility:public"],
    )
    """.format(warning = warning, srcs = srcs)
```

Do you think this is good?
</blockquote></details>

The new one is working.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605)*

**Comment by ggould-tri** [comment]
:lgtm: pending one item below.  @ericcousineau-tri take note as well.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/gurobi.bzl, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-KpV4jwt9ZoyNleVwry1:-KpV4jwt9ZoyNleVwry2:bm1p4pe) ([raw file](https://github.com/robotlocomotion/drake/blob/da3c49f863758de331ea81276a309558c9c183d8/tools/gurobi.bzl#L43)):*
> ```Python
>         srcs = ["gurobi-distro/lib/libgurobi70.so"]
> 
>         linkopts = """select({
> ```

FYI -- This logic really should have a comment -- it will not be clear to future readers either why it is necessary nor why it is correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-:-KpV51pzVmenz4RjO5tE:b-s0jg6q)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/gurobi.bzl, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-KpV4jwt9ZoyNleVwry1:-KpV6J_p_aWqObpkkeZD:b-fp2mwo) ([raw file](https://github.com/robotlocomotion/drake/blob/da3c49f863758de331ea81276a309558c9c183d8/tools/gurobi.bzl#L43)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- This logic really should have a comment -- it will not be clear to future readers either why it is necessary nor why it is correct.
</blockquote></details>

This code (i.e., everything in the `else:` block) should really only be evaluated when the OS is not Mac, so wondering why we are getting the warning here in the first place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/gurobi.bzl, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6605#-KpV4jwt9ZoyNleVwry1:-KpV9AGLD9P0I-QAuW-f:b-mys1ka) ([raw file](https://github.com/robotlocomotion/drake/blob/da3c49f863758de331ea81276a309558c9c183d8/tools/gurobi.bzl#L43)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

This code (i.e., everything in the `else:` block) should really only be evaluated when the OS is not Mac, so wondering why we are getting the warning here in the first place.
</blockquote></details>

@jamiesnape , you're right. I'll close this PR. Thanks for the point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6605)*

**Pull request closed without merging**
