### PR TITLE
Add an exception when a feedback system creates an algebraic loop

### LINKED ISSUE #2298: C++ FeedbackSystem should enforce isDirectFeedthrough constraint
The C++ implementation of `FeedbackSystem` should enforce the same `isDirectFeedthrough` constraint that matlab does -- namely, that both systems cannot claim `isDirectFeedthrough`.

Here's the relevant matlab code:
```matlab
      if (sys1.isDirectFeedthrough() && sys2.isDirectFeedthrough())
        error('Drake:FeedbackSystem:AlgebraicLoop','algebraic loop');
      end
```

While we're at it, we should improve the if-else comments that assume that `!!sys1->isDirectFeedthrough` implies that `!sys2->DirectFeedthrough`, so its clearer why we're passing uninitialized memory to sys2's `output()` methods.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #2298.

Benchmarked with runQuadrotorLQR with realtime_factor=0.0 (as fast as possible) for 1000 seconds of simulated time.  New performance is indistinguishable from prior.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2423) &emsp; Multiple assignees:&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by liangfok** [comment]
Did a quick pass on this.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### Add an exception when a feedback system creates an algebraic loop
> 
> Closes #2298.
> 
> 
> 
> Benchmarked with runQuadrotorLQR with realtime_factor=0.0 (as fast as possible) for 1000 seconds of simulated time.  New performance is indistinguishable from prior.
> 
> 
> 
</details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/feedback_system.h, line 115 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIpPNw2qb2fBD0hW6X:-KIIpPNw2qb2fBD0hW6Y:721713837) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/feedback_system.h#L115)):*
> ```objc
>   // u1 is the input to sys1 (u + y2).
>   //
>   // If want_y2_u1 is not set, y2 and u1 may or may not be computed.
> ```

Consider changing "not set" to be "false".
Consider changing "computed" to be "computed depending on whether system 1 is direct feedthrough.

---

*[drake/systems/feedback_system.h, line 121 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIoXNfOKWbarwZIWyG:-KIIoXNfOKWbarwZIWyH:1003506979) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/feedback_system.h#L121)):*
> ```objc
>                         const StateVector2<ScalarType>& x2,
>                         const InputVector<ScalarType>& u,
>                         bool want_y2_u1,
> ```

Consider changing `want_y2_u1` to be `compute_y2_u1` since, when true, it effectively commands the method to compute `y2` and `u1`.

The word "want" is a bit too soft in the sense that the method's body can say "it's great that you _want_ it but I'm still not going to give it to you".

---

*[drake/systems/feedback_system.h, line 128 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIpu2MqkOi2-kcIos4:-KIIpu2MqkOi2-kcIos5:-1793106619) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/feedback_system.h#L128)):*
> ```objc
>       // sys1->output doesn't use u1, so it's okay that it isn't filled in yet.
>       *y1 = sys1->output(t, x1, *u1);
>       if (want_y2_u1) {
> ```

Can you provide an explanation on under what circumstances will the user _not_ want to compute `y2` and `u1`? Maybe by adding it to the method description's comment block?

---

*[drake/systems/test/feedback_system_test.cc, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqKkxyzAgFaPyjnTx:-KIIqKkxyzAgFaPyjnTy:841900250) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/feedback_system_test.cc#L37)):*
> ```cpp
> TEST(FeedbackSystemTest, ConstantSizes) {
>   auto combined =
>       MakeFeedbackLoopOfAffineSystems<4, 2, 3, 5>(4, 2, 3, 5, true, false);
> ```

Consider adding some comments indicating what the various parameters mean do the reader need not refer to the API of `MakeFeedbackLoopOfAffineSystems`.

---

*[drake/systems/test/feedback_system_test.cc, line 50 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqXQYnNhe_IqyJxkW:-KIIqXQYnNhe_IqyJxkX:1530920911) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/feedback_system_test.cc#L50)):*
> ```cpp
>   auto combined =
>       MakeFeedbackLoopOfAffineSystems<Dynamic, Dynamic, Dynamic, Dynamic>(
>           4, 2, 3, 5, false, true);
> ```

Same comment here regarding need for brief description of parameters.

---

*[drake/systems/test/feedback_system_test.cc, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqcbSnx_6YfRfbD7G:-KIIqcbSnx_6YfRfbD7H:1530920911) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/feedback_system_test.cc#L60)):*
> ```cpp
> TEST(FeedbackSystemTest, AlgebraicLoop) {
>   EXPECT_THROW(
>       (MakeFeedbackLoopOfAffineSystems<1, 1, 1, 1>(1, 1, 1, 1, true, true)),
> ```

Same comment here regarding need for brief description of parameters.

---

*[drake/systems/test/system_test_util.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqggkiyxX1_7DN9Co:-KIIqggkiyxX1_7DN9Cp:1392438092) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/system_test_util.h#L17)):*
> ```objc
>                              EigenVector<OutputsAtCompileTime>::template type>>
> CreateRandomAffineSystem(size_t num_states, size_t num_inputs,
>                          size_t num_outputs, bool direct_feedthrough = true) {
> ```

Consider changing `direct_feedthrough` to be `is_direct_feedthrough`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-:-KIIqpVQSDzPgoLwmQnH:98383206)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/feedback_system.h, line 115 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIpPNw2qb2fBD0hW6X:-KIKcTy56ZkMAsBJdrb3:1542242186) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/feedback_system.h#L115)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Consider changing "not set" to be "false".
> Consider changing "computed" to be "computed depending on whether system 1 is direct feedthrough.
</details>
Done (slightly differently).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
+@sherm1 platform review please.
+@liangfok feature review please.

This isn't holding up any other work (its just a good-deed bugfix), so no hurry on the LGTMs.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Did a quick pass on this.
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-:-KISk9bMF7_5TN3I4_5B:-1551742112)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
Platform: a few minor comments, otherwise :lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@sherm1 platform review please.
> +@liangfok feature review please.
> 
> This isn't holding up any other work (its just a good-deed bugfix), so no hurry on the LGTMs.
</details>


---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/test/feedback_system_test.cc, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIT9gtv7mbx6jctw7My:-KIT9gtv7mbx6jctw7Mz:1420633933) ([raw file](https://github.com/robotlocomotion/drake/blob/af60388474a3d72fde332b51487b5ec095b79681/drake/systems/test/feedback_system_test.cc#L58)):*
> ```cpp
> 
> // Tests that algebraic loops are rejected.
> TEST(FeedbackSystemTest, AlgebraicLoop) {
> ```

Use `GTEST_TEST` per [style guide](http://drake.mit.edu/code_style_guide.html#id10).

---

*[drake/systems/test/system_test_util.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqggkiyxX1_7DN9Co:-KITAUmiWo2RaB0Cf4LY:-1240970620) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/system_test_util.h#L17)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Consider changing `direct_feedthrough` to be `is_direct_feedthrough`.
</details>
has_direct_feedthrough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-:-KITAcL3JFyudF3gLLxp:1405029456)*

**Comment by sherm1** [comment]
Reviewable didn't send my comments to GitHub! Will try to redo.

**Comment by sherm1** [comment]
Platform: minor comments, otherwise :lgtm:

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Reviewable didn't send my comments to GitHub! Will try to redo.
</details>


---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/test/feedback_system_test.cc, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIT9gtv7mbx6jctw7My:-KITBR-S1SQkWqmzZbtm:1964589214) ([raw file](https://github.com/robotlocomotion/drake/blob/af60388474a3d72fde332b51487b5ec095b79681/drake/systems/test/feedback_system_test.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Use `GTEST_TEST` per [style guide](http://drake.mit.edu/code_style_guide.html#id10).
</details>
Use `GTEST_TEST` per style guide.

---

*[drake/systems/test/system_test_util.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqggkiyxX1_7DN9Co:-KITBVUH949glgTF_Vnt:-1240970620) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/system_test_util.h#L17)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> has_direct_feedthrough?
</details>
has_direct_feedthrough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-:-KITBapH8_2IDESPLefS:-1617214743)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/feedback_system.h, line 121 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIoXNfOKWbarwZIWyG:-KITEYXDtHoxk5cOOL4H:-1538349216) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/feedback_system.h#L121)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Consider changing `want_y2_u1` to be `compute_y2_u1` since, when true, it effectively commands the method to compute `y2` and `u1`.
> 
> The word "want" is a bit too soft in the sense that the method's body can say "it's great that you _want_ it but I'm still not going to give it to you".
</details>
The sense of `want` is what the caller of the API wants.  Using `compute` would be worse, because the method would still sometimes compute  y2 and u2 even when `compute == false`.

---

*[drake/systems/feedback_system.h, line 128 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIpu2MqkOi2-kcIos4:-KIKbly6M-WoLhyG2URm:1546472145) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/feedback_system.h#L128)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Can you provide an explanation on under what circumstances will the user _not_ want to compute `y2` and `u1`? Maybe by adding it to the method description's comment block?
</details>
Its a private method, and I think the circumstances are pretty clear at the two call sites.  (In the case where want_y2_u1 is false, the caller doesn't want those two items because it the only thing it needs to do is return y1.)

---

*[drake/systems/test/feedback_system_test.cc, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqKkxyzAgFaPyjnTx:-KIKc0lwbShqzjE53DOL:-778427533) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/feedback_system_test.cc#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Consider adding some comments indicating what the various parameters mean do the reader need not refer to the API of `MakeFeedbackLoopOfAffineSystems`.
</details>
This entire file is only 66 lines long.  It fits on one screen.  To my estimation, the code is perfectly clear as-is.

---

*[drake/systems/test/feedback_system_test.cc, line 50 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqXQYnNhe_IqyJxkW:-KIKc315rFedPOgYytcx:-485711229) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/feedback_system_test.cc#L50)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Same comment here regarding need for brief description of parameters.
</details>
Same.

---

*[drake/systems/test/feedback_system_test.cc, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqcbSnx_6YfRfbD7G:-KIKc4NzVVNCsM42bQjl:-485711229) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/feedback_system_test.cc#L60)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Same comment here regarding need for brief description of parameters.
</details>
Same.

---

*[drake/systems/test/feedback_system_test.cc, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIT9gtv7mbx6jctw7My:-KITCWhpPSBECuZFiDms:2078437864) ([raw file](https://github.com/robotlocomotion/drake/blob/af60388474a3d72fde332b51487b5ec095b79681/drake/systems/test/feedback_system_test.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Use `GTEST_TEST` per style guide.
</details>
Done.  (Though FYI  github is currently laggy and hasn't noticed my push yet.)

---

*[drake/systems/test/system_test_util.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqggkiyxX1_7DN9Co:-KIKc5w-byeAitipmg60:1694670289) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/system_test_util.h#L17)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> has_direct_feedthrough?
</details>
The name conforms to the style guide and IMO is not confusing.  I guess I don't see the problem this is trying to solve.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423)*

**Comment by liangfok** [comment]
:lgtm: 

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Platform: minor comments, otherwise :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/test/system_test_util.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqggkiyxX1_7DN9Co:-KITKFO3fbRy0t-GG9IT:1927853443) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/system_test_util.h#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The name conforms to the style guide and IMO is not confusing.  I guess I don't see the problem this is trying to solve.
</details>
I believe "direct_feedthrough" is in violation of the "verb rule", which @david-german-tri previously mentioned, though I'm not sure if "is" is considered to be a verb.

Regardless, marking this as satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-:-KITKnG3gF57QLw-u4Y7:980077423)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/test/system_test_util.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqggkiyxX1_7DN9Co:-KITKze2-YxJkOAsF3VU:-461980805) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/system_test_util.h#L17)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I believe "direct_feedthrough" is in violation of the "verb rule", which @david-german-tri previously mentioned, though I'm not sure if "is" is considered to be a verb.
> 
> Regardless, marking this as satisfied.
</details>
I thought the verb rule was for methods (where they are performing an action, and so should be verbs), and did not apply to parameters?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/test/system_test_util.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqggkiyxX1_7DN9Co:-KITKZiY_7v8Y5r1IQ0x:1046951459) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/system_test_util.h#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I thought the verb rule was for methods (where they are performing an action, and so should be verbs), and did not apply to parameters?
</details>
I'm happy with the name as is. I was responding to Liang's proposal -- "has" makes more sense than "is" for direct feedthrough.

@liangfok, the "verb rule" applies to methods only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423)*

**Comment by sherm1** [comment]
Ready to merge but GitHub is freaking out at the moment.

**Comment by jwnimmer-tri** [comment]
Don't merge yet; we need to get the GTEST_TEST fix to show up first.

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/test/system_test_util.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2423#-KIIqggkiyxX1_7DN9Co:-KITPSaTqJ4fdeTI365D:745367290) ([raw file](https://github.com/robotlocomotion/drake/blob/13cb1a9d3c8f776be83b8dbee7ab4acdea8bc710/drake/systems/test/system_test_util.h#L17)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I'm happy with the name as is. I was responding to Liang's proposal -- "has" makes more sense than "is" for direct feedthrough.
> 
> @liangfok, the "verb rule" applies to methods only.
</details>
OK SGTM. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423)*

**Comment by sherm1** [comment]
GTEST_TEST fix showed up. Waiting for CI now.

**Comment by sherm1** [comment]
Reviewed 1 of 9 files at r3.
Review status: 3 of 11 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2423)*

**Comment by jwnimmer-tri** [comment]
For the record, the jenkins PR builder didn't actually build today's changes (it built master instead); see #2435.  However, it looks like Continuous was happy with this change, with the possible exception of mac-clang-continuous-matlab, which is filled with test explosions both before and after this PR merged.  Hopefully they are all just flakes, and not any problem with this PR.

**Pull request merged**
