### PR TITLE
Move ReconstructInputTrajectory() and ReconstructStateTrajectory() ou…

### PR DESCRIPTION
**Pull request by Lucy-tri**
…t of direct_trajectory_optimization.cc

This is more of a trajectory operation and not an optimization one, and
I need to remove the mention of a PP function out of that file.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3808)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@sammy-tri for feature review, please.

**Comment by Lucy-tri** [comment]
Oops, hold on, whitespace issues. I'll fix.

**Comment by hongkai-dai** [comment]
@lucy-tri thanks for the PR. 

My suggestion would be to leave the `ReconstructInputTrajectory` and `ReconstructStateTrajectory` inside `direct_trajectory_optimization`. These two methods are only meaningful in the context of direct collocation method, since they suppose the input trajectory is first order piecewise polynomial, and state trajectory is cubic Hermite spline. We should not put these methods in `trajectories`, since other systems can use different form of input and state trajectory.

Also I notice that in the previous implementation, `ReconstructStateTrajectory` uses first-order piecewise polynomial. That should not be correct. In direct collocation method, we used cubic Hermite spline. Would you like to fix it also? The formulation of the direct collocation method can be found in 
C. R. Hargraves and S. W. Paris. Direct trajectory optimization using nonlinear programming and collocation. J Guidance, 10(4):338-342, July-August 1987
I can send you the paper if you want.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 206 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3808#-KU8QezosoyI6EguFzsF:-KU8QezosoyI6EguFzsG:b-fgz9kz) ([raw file](https://github.com/robotlocomotion/drake/blob/0e59b2576e2d7563573fd33bd978b56ef4a140a3/drake/systems/trajectories/PiecewisePolynomial.h#L206)):*
> ```objc
>    * Get the input trajectory as a PiecewisePolynomial
>    */
>   static PiecewisePolynomial ReconstructInputTrajectory(
> ```

I am not sure if we want to call this function `ReconstructInputTrajectory`, since what it does it to compute a piecewise first-order hold trajectory. It is true that in our direct collocation approach, the input trajectory is first-order pp trajectory. But for system can use different input trajectory. For example, in time stepping simulation, we supposed the input is piecewise constant.

I would suggest to remove this method.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 214 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3808#-KU8R_WCfPpoja__F8Dh:-KU8R_WCfPpoja__F8Di:b-qw32i) ([raw file](https://github.com/robotlocomotion/drake/blob/0e59b2576e2d7563573fd33bd978b56ef4a140a3/drake/systems/trajectories/PiecewisePolynomial.h#L214)):*
> ```objc
> 
>   /**
>    * Get the state trajectory as a PiecewisePolynomial
> ```

The state trajectory can be in many forms. In direct collocation method, we used cubic Hermite spline. In Michael Posa's approach, we used backward Euler integration. So we should not call this method `ReconstructStateTrajectory`, as what it does is to form a first order piecewise polynomial trajectory. I would suggest to remove this method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3808#-:-KU8SJtfU9mQLc7WdCR4:b-w50gzz)*

**Comment by Lucy-tri** [comment]
@hongkai-dai thank you very much for the helpful feedback. 
Regarding `ReconstructStateTrajectory`, we realize that we should be using a cubic spline: see issue https://github.com/RobotLocomotion/drake/issues/3787.  We plan to fix this soon.
For the other problem, I was hoping to do this PR as an intermediate step.  Let me examine the code Monday. 
+(status: do not review) 

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3808#-:-KUEdMW6I3n6jTh0Ejy4:b-myiqt2)*

**Pull request closed without merging**
