### PR TITLE
Let drake_visualizer work outside sandbox on Mac

### PR DESCRIPTION
**Pull request by jamiesnape**
See also https://github.com/RobotLocomotion/drake/issues/5621#issuecomment-309044209.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6391)

### CODE REVIEW

**Comment by patmarion** [comment]
minor comment---some people might use commands like `drake-visualizer --script relative/path/to/script.py` which doesn't work if the launcher changes the current working directory.

**Comment by jamiesnape** [comment]
Indeed. Not a workflow we support on Linux either at the moment.

**Comment by sammy-tri** [comment]
I think this workflow may actually be encouraged in `drake/multibody/rigid_body_plant/visualization/README` (which uses relative paths to scripts)

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm: platform review.

We should find someone with native OSX to test this as feature review, perhaps +@soonho-tri?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6391#-:-KnBNbW9LsH4pgEeHsUl:b-o5le05)*

**Comment by soonho-tri** [comment]
> We should find someone with native OSX to test this as feature review, perhaps +@soonho-tri?

I'll do that today.

**Comment by soonho-tri** [comment]
:lgtm:

It works for me.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6391#-:-KnBTOFFrnDwjj6hrGo9:ba0ejml)*

**Pull request merged**
