### PR TITLE
[planning] Reorganize planning artifacts in planning (3 of 3)

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
- manipulation/planner/differential_inverse_dynamics* goes to multibody/inverse_dynamics.

Moving includes updating all references, namespaces, and bindings.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for feature review.

+(status: commits are properly curated) 
+(release notes: newly deprecated) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-:-NNJFM_94jVMnvcGpVMG:b3jw2i9)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-NNJFU---dDowC_YELXt:-NNJFU---dDowC_YELXu:b-l6holi) (no related file):*
Anzu build 179 passes with this and I have the anzu PR ready to go (anzu#10096).

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'll update the dates to 2023-06-01 upon the first review pass.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-:-NNJLak5AZF6feLTo1Eu:b65bw51)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-NNKDgSz4-s8x5CkO6EY:-NNbiabG0ukIeBoZljNs:b4qzs4m) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I plan to do local smoke testing of the deprecations, website, etc.
</blockquote></details>

I've addressed the current comments and rebased. Also, I updated the date in this PR to 2023-06-01. I also dragged the other elements pulled from `manipulation/planner` to the same date.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`manipulation/planner/stub/differential_inverse_kinematics.h` line 3 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-NNbqn55B0Y2L4YGMpA2:-NNbqn55B0Y2L4YGMpA3:b4geaqh) ([raw file](https://github.com/RobotLocomotion/drake/blob/c12a9d8de8636f092ba5cfdfe3d8c3859db1658b/manipulation/planner/stub/differential_inverse_kinematics.h#L3)):*
> ```objc
> #pragma once
> 
> #warning The include path drake/manipulation/planner/differential_inverse_kinematics.h is deprecated and will be removed on or after 2023-05-01; instead, use drake/multibody/inverse_kinematics/differential_inverse_kinematics.h.
> ```

nit Some of the date updates got missed, throughout the PR.



_Suggestion:_
```objc
2023-06-01
```

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-:-NNgPn70-gMtlEondfcV:b-n37teh)* status: 2 unresolved discussions, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-NNKDgSz4-s8x5CkO6EY:-NNgK2K855OujIkHS-6I:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I've addressed the current comments and rebased. Also, I updated the date in this PR to 2023-06-01. I also dragged the other elements pulled from `manipulation/planner` to the same date.
</blockquote></details>

Done.

___
___
*[`manipulation/planner/stub/differential_inverse_kinematics_integrator.h` line 7 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-NNgO4R3EVbnNYpeqpAV:-NNgO4R3EVbnNYpeqpAW:b10msym) ([raw file](https://github.com/RobotLocomotion/drake/blob/c12a9d8de8636f092ba5cfdfe3d8c3859db1658b/manipulation/planner/stub/differential_inverse_kinematics_integrator.h#L7)):*
> ```objc
> #include "drake/common/drake_deprecated.h"
> #include "drake/multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h"
> ```

nit We should include `"drake/manipulation/planner/differential_inverse_kinematics.h"`here for backwards compatibility -- so that this header file provides the deprecated names, since it used to do so previously.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@xuchenhan-tri for platform review (feel free to wait for your day).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-:-NNgVxWN0_NNpEglFU5q:b2l8s8f)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
platform  :lgtm: 

> Reviewed 20 of 20 files at r1, 1 of 7 files at r2, 10 of 12 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-:-NNmU5Vg72VfPlkpK7Hh:b-tm2yjo)* status: 1 unresolved discussion, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @SeanCurtis-TRI)

___
*[`bindings/pydrake/multibody/inverse_kinematics_py_differential.cc` line 5 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18715#-NNm0hIM7YjO6WogF8l5:-NNm0hIM7YjO6WogF8l6:b4np5x6) ([raw file](https://github.com/RobotLocomotion/drake/blob/552fd75dbaa4903477436b108286b6ec2da62fff/bindings/pydrake/multibody/inverse_kinematics_py_differential.cc#L5)):*
> ```cpp
> #include "pybind11/stl.h"
> 
> // #include "drake/bindings/pydrake/common/deprecation_pybind.h"
> ```

nit is this still needed?

**Pull request merged**
