### PR TITLE
[parsing] Restrict collision filters to models within a parse operation

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #14785

This patch implements a stronger enforcement of model encapsulation for
collision filters. Previously, filters defined outside any model could refer to
the world body or parts of the default model by scoped names, or to default
model bodies by unqualified names. Now, those references are parse errors, and
using a model index from outside the parse as a parameter is a programming
error.

There might ever be a reason (I couldn't think of one) to define collision
filters against the world body; I am fine for that to involve a special
privileged name and be future work.

I couldn't think of any reason why a model file should be able to refer to
bodies in the default model, which (in the current implementation of Parser),
could never be populated from model files.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: yes) +@jwnimmer-tri for feature review.
FYI @ericcousineau-tri @calderpg-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241#-:-N2XaT4h1sb_3_HTyvj0:b-kctogu)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17241#-N2lI5x_0I4XxtISEcnd:-N2lLMWX3p2Wkf_Gqhhn:b-vf26a0) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Can you clarify why "release notes: yes".  The class is internal so doesn't need notes -- the reason must be because of some user-visible change to loading sdf or urdf files.  Can you give an example of input file(s) where the parsing behavior is different now?
</blockquote></details>

To be clear, I'm not concerned about the label -- I just want to be sure a fully understand this change.

___

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241#-:-N2lvwiw90jZppQQ3euR:b-n37teh)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17241#-N2lI5x_0I4XxtISEcnd:-N2lvtLS2_OegTEy3iBL:bwc97p7) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Nope, I lied. It isn't currently possible to write the counterexample in SDFormat--the existing body name logic will just spit out "not found". Supporting collision filters defined at `//sdf/world`, or as model directives would want this checking, but they are not implemented yet.

In any case, this checking does resolve the question of world and default model semantics, as raised in previous discussions.
</blockquote></details>

Great, I'm on board with that.

___

**Review by rpoyner-tri — COMMENTED** [review]
+@ggould-tri for platform review, by schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241#-:-N2lwvflAi1-9kodyive:b-1k1i1m)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241#-:-N2lzRHe4T8zzNovv87c:bnfp4nl)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_collision_filter_group_resolver.h` line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17241#-N2lyjWC-okMWS-ySGXJ:-N2lyjWC-okMWS-ySGXK:b-7ilvfu) ([raw file](https://github.com/robotlocomotion/drake/blob/d224ead27ba38ee71669ee178bb2ccf4866b687c/multibody/parsing/detail_collision_filter_group_resolver.h#L42)):*
> ```objc
> // with in the range:
> //
> //  minimum_model_instance_index() >= valid_model < num_model_instances()
> ```

typo?



_Suggestion:_
```objc
<=
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241)* status: 1 unresolved discussion (waiting on @ggould-tri)

___
*[`multibody/parsing/detail_collision_filter_group_resolver.h` line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17241#-N2lyjWC-okMWS-ySGXJ:-N2mALzgBQwSHoONu2IJ:bu3sv5h) ([raw file](https://github.com/robotlocomotion/drake/blob/d224ead27ba38ee71669ee178bb2ccf4866b687c/multibody/parsing/detail_collision_filter_group_resolver.h#L42)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

The code as written says that the minimum is greater than or equal to a valid instance.
Line 33 of the cc file however says:
`DRAKE_DEMAND(*model_instance >= minimum_model_instance_index_);`
ie, it asserts that a valid instance is greater than or equal to the minimum.

Also if the comparison as written `minimum_model_instance_index() >= valid_model` were correct then the name "minimum" would be a naming defect.
</blockquote></details>

Maybe what's unclear here is that `valid_model` is a placeholder for the user's input model name via the xml file?  The name written down by the user must refer to a model that's no less than the minimum.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @ggould-tri and @jwnimmer-tri)

___
*[`multibody/parsing/detail_collision_filter_group_resolver.h` line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17241#-N2lyjWC-okMWS-ySGXJ:-N2mKEzJ66rgh_SqySuJ:b-4704wp) ([raw file](https://github.com/robotlocomotion/drake/blob/d224ead27ba38ee71669ee178bb2ccf4866b687c/multibody/parsing/detail_collision_filter_group_resolver.h#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe what's unclear here is that `valid_model` is a placeholder for the user's input model name via the xml file?  The name written down by the user must refer to a model that's no less than the minimum.
</blockquote></details>

Attempted to clarify. Better?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_collision_filter_group_resolver.h` line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17241#-N2lyjWC-okMWS-ySGXJ:-N2mLUvD-eIuQ-1YnrTX:b-vja09e) ([raw file](https://github.com/robotlocomotion/drake/blob/d224ead27ba38ee71669ee178bb2ccf4866b687c/multibody/parsing/detail_collision_filter_group_resolver.h#L42)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Attempted to clarify. Better?
</blockquote></details>

I am fine with this, but we should wait for @ggould-tri to weigh in.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_collision_filter_group_resolver.h` line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17241#-N2lyjWC-okMWS-ySGXJ:-N2mMKwX9XbOXULOIJXt:b-xylixn) ([raw file](https://github.com/robotlocomotion/drake/blob/d224ead27ba38ee71669ee178bb2ccf4866b687c/multibody/parsing/detail_collision_filter_group_resolver.h#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am fine with this, but we should wait for @ggould-tri to weigh in.
</blockquote></details>

What was unclear here, afaict, was that the inequality was typoed to describe a range unbounded below; the new text correctly reflects the code; thank you.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17241)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
