### PR TITLE
Add doc suggestions for how to fix Wunused-parameter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5999)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for first review, please.

+(status: do not merge) because I will want to add more reviewers later on.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5999#-:-Kj95wJG_mbD07yWNRxU:b-wgg9oa)*

**Comment by ggould-tri** [comment]
:lgtm:, one consider below.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/unused.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5999#-Kj96p6fXS_-xa7D8eR5:-Kj96p6fXS_-xa7D8eR6:bxscxw5) ([raw file](https://github.com/robotlocomotion/drake/blob/042f4d9bd28a8ea042d7c54fa662360e93260979/drake/common/unused.h#L47)):*
> ```objc
> ///   unused(state);
> ///   throw std::runtime_error("DoFoo must be overridden");
> /// }
> ```

FYI this example is slightly confusing as IMO it would almost always be defective to write this code instead of just using a pure virtual declaration.  Consider instead an example of how `unused()` can be useful in a more real context?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5999#-:-Kj96Xq9JjicaUUWBwkK:b2qkjp)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/unused.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5999#-Kj96p6fXS_-xa7D8eR5:-Kj98AVZEx3l0Zk3F4OS:by9qxqf) ([raw file](https://github.com/robotlocomotion/drake/blob/042f4d9bd28a8ea042d7c54fa662360e93260979/drake/common/unused.h#L47)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI this example is slightly confusing as IMO it would almost always be defective to write this code instead of just using a pure virtual declaration.  Consider instead an example of how `unused()` can be useful in a more real context?
</blockquote></details>

Let me tell you a story about `drake::systems::System`...  Anyway, good point.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5999)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5999)*

**Comment by SeanCurtis-TRI** [comment]
I like this. My only vague concern comes in the verbs "suppress" and "silence".  (And let me offer an *a priori* apology for how vague this is going to come across.)  When I think of "suppressing" warnings, I think in terms of pragmas that literally inform the compiler to not perform a particular analysis. This really seems to be about strategies for "resolving" unused-parameter warnings.  It's a small niggling detail, but it feels better to me.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5999#-:-Kj9Dr14Bz-8ynu5whEB:b-pbjg23)*

**Comment by jwnimmer-tri** [comment]
I went with "placate" the warning now.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5999#-:-Kj9M6nzgkRPe6ZBIDKh:b-sitf0b)*

**Comment by SeanCurtis-TRI** [comment]
Thanks for humoring me.  I can certainly accept "placate". Although, I would argue that it's still underselling the documentation. When the number one solution is to remove the unused parameter -- that feels a bit stronger than "placating". However, `drake::unused`, as a "solution", would be well categorized as "placating". :LGTM:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5999#-:-Kj9MrNKRZPAzP2gG5z6:b5pi26i)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5999#-:-Kj9P4VwsTkR0xAbij8Z:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
If others stumble on this later, I'm happy to take further suggestions for a follow-up (or PR something yourself).

**Pull request merged**
