### PR TITLE
[pydrake] Deprecate old Python-based meshcat implementation

### LINKED ISSUE #16978: Deprecation of pure-python MeshcatVisualizer
As it stands, we have two meshcat-based APIs in pydrake, which is a bit confusing for users.

Check the module https://drake.mit.edu/pydrake/pydrake.systems.meshcat_visualizer.html.  There are several classes there, namely `MeshcatVisualizer`, `MeshcatContactVisualizer`, etc.  That's older API, which I think we'd like to deprecate.

The https://drake.mit.edu/pydrake/pydrake.geometry.html#pydrake.geometry.MeshcatVisualizerCpp and related are the new API that we should prefer, instead.

I believe our plan was to finish adding those same features to the C++ code, ensure it's all bound in pydrake, port all of Drake's internal uses away from this module (#14702), and then deprecate it for eventual removal.  

Perhaps we should immediately add a disclaimer atop that module, to dissuade people from using it?

@RussTedrake could you comment whether you agree with the outline above?

Assuming yes, we'll need to make a feature inventory of the old API, and then check off whether the new API is sufficient.  I didn't see a tracking issue for any of this yet, so I made this one.  (If there is already a checklist, we can mark one as a duplicate of the other.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #16978.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17194)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @RussTedrake FYI (or feature review, if you like)

**Review by RussTedrake — COMMENTED** [review]
+@russtedrake as feature review.
:lgtm:
thanks for doing it.  I confirmed that the warning appeared for me in my `test_model_directives` (and have updated that test).

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17194#-:-N23Enks2DXOO-RXPmEf:bq8aoa2)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`manipulation/util/show_model.py` line 134 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17194#-N23764pEwWHr6bKEkhc:-N23764q77w2iP8zf45v:b48utrn) ([raw file](https://github.com/robotlocomotion/drake/blob/47da4c879ff98a5fb3ed5336b4b5e93573d3d441/manipulation/util/show_model.py#L134)):*
> ```Python
>     Adds argparse arguments for visualizers.
>     """
>     with warnings.catch_warnings(record=True) as w:
> ```

btw -- i was surprised there was no file-level documentation that needed to change for this.  :-(
___
*[`bindings/pydrake/systems/meshcat_visualizer.py` line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17194#-N23FUJu6rMEYWaxG5y5:-N23FUJv4PdztECMzltQ:b-vrkm39) ([raw file](https://github.com/robotlocomotion/drake/blob/47da4c879ff98a5fb3ed5336b4b5e93573d3d441/bindings/pydrake/systems/meshcat_visualizer.py#L106)):*
> ```Python
>             raise ValueError("nargs not allowed")
>         super().__init__(option_strings, dest, **kwargs)
>         _warn_deprecated(_DEPRECATION, date="2022-09-01", stacklevel=5)
> ```

btw -- i was surprised that you needed `stacklevel=5` here, 3 in the MeshcatVisualizer constructor, but only the default 2 everywhere else?  Would be nice for that to be proven with a small test constructing each method.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17194)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`manipulation/util/show_model.py` line 134 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17194#-N23764pEwWHr6bKEkhc:-N23RHRMCiUFClWc1VYC:b-w9gfv5) ([raw file](https://github.com/robotlocomotion/drake/blob/47da4c879ff98a5fb3ed5336b4b5e93573d3d441/manipulation/util/show_model.py#L134)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i was surprised there was no file-level documentation that needed to change for this.  :-(
</blockquote></details>

Developers will definitely see runtime warnings here if they use `--meshcat` with this tool.  It's not an installed tool though, so I wasn't too worried about that.

(Kitware also has a patch in flight to port this to MeshcatVisualizerCpp.)
___
*[`bindings/pydrake/systems/meshcat_visualizer.py` line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17194#-N23FUJu6rMEYWaxG5y5:-N23RZi76AsAJsImbSCW:b-i00b3g) ([raw file](https://github.com/robotlocomotion/drake/blob/47da4c879ff98a5fb3ed5336b4b5e93573d3d441/bindings/pydrake/systems/meshcat_visualizer.py#L106)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i was surprised that you needed `stacklevel=5` here, 3 in the MeshcatVisualizer constructor, but only the default 2 everywhere else?  Would be nice for that to be proven with a small test constructing each method.
</blockquote></details>

As I understood it, the stacklevel only affects the file/line number printed alongside the warning; the user would get a warning no matter what (so, a test case wouldn't tell us anything?).

I spent a few minutes trying to get the line numbers reported correctly, but given all of the self-calls in this module it seemed impossible to get it perfect.  (At least, not without using a ModuleShim, but I think nobody except Eric knows how to use that class.)

Given the documentation warnings in the API reference, and _some_ runtime warning (even with a wrong-line number), that seemed good enough for me.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17194)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/systems/meshcat_visualizer.py` line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17194#-N23FUJu6rMEYWaxG5y5:-N23VMEL8dJ1C8IddEqI:bb73djm) ([raw file](https://github.com/robotlocomotion/drake/blob/47da4c879ff98a5fb3ed5336b4b5e93573d3d441/bindings/pydrake/systems/meshcat_visualizer.py#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As I understood it, the stacklevel only affects the file/line number printed alongside the warning; the user would get a warning no matter what (so, a test case wouldn't tell us anything?).

I spent a few minutes trying to get the line numbers reported correctly, but given all of the self-calls in this module it seemed impossible to get it perfect.  (At least, not without using a ModuleShim, but I think nobody except Eric knows how to use that class.)

Given the documentation warnings in the API reference, and _some_ runtime warning (even with a wrong-line number), that seemed good enough for me.
</blockquote></details>

SGTM

**Review by RussTedrake — COMMENTED** [review]
:lgtm: again.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17194#-:-N29AOol7eXtFlw4QN8C:butqosd)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17194#-:-N2Cw_8T2PZSyyuRNvT4:bqljb9l)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17194#-:-N2Cxwgg9nDTkmelvBNo:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/_geometry_extra.py` line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17194#-N2Cws9F3X98ECPIN4KA:-N2Cws9F3X98ECPIN4KB:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/8b952391ba9c9d1b90c08f2419419b2e02cb6705/bindings/pydrake/_geometry_extra.py#L76)):*
> ```Python
> 
> 
> # TODO(jwnimmer-tri) Deprecate these legacy compatibility alises on or after
> ```

typo



_Code quote:_
```Python
alises
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17194)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),RussTedrake(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
