### PR TITLE
[workspace] Upgrade rust repositories to latest

### LINKED ISSUE #21073: Upgrade rules_rust to latest release
I omitted `@rules_rust` from #21072, because our local patch related to license file installation didn't apply cleanly.

It looks like upstream might do license files correctly now, so we will need to rework our integration.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Upgrade rules_rust to latest release 0.40.0
- Upgrade rust_toolchain to latest
- Upgrade crate_universe to latest
- Install crate_universe license docs using their rules_license badges

Closes #21073.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21083)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.  No particular hurry, but I'd say my goal is to have Xuchen do platform review (as aspiring build SME) so in the next couple days would be ideal.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21083#-:-NsED5mX-trJdGpG1Bkx:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review (tomorrow), please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21083#-:-NsFDKov9QEgKERZFgJE:bg7igkv)* status: 1 unresolved discussion

___
*[`tools/install/install.bzl` line 415 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21083#-NsFA8YS8W3WxEMDN4SK:-NsFA8YT2JMPnZFMt_iF:b-e2jinh) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5d325f6ce90ad68131352dbe9830e840a662e2d/tools/install/install.bzl#L415)):*
> ```Starlark
>         ))
>     return [
>         InstallInfo(
> ```

btw, I'm having a hard time parsing this. Where does the actual "installing" happen? It looks to me like this is packing a list of install actions and shoving them into a provider. Where are the actions specified in `install_actions` carried out?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21083)* status: 1 unresolved discussion

___
*[`tools/install/install.bzl` line 415 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21083#-NsFA8YS8W3WxEMDN4SK:-NsFHnHv4gRYnIIcg5gL:bkcrjms) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5d325f6ce90ad68131352dbe9830e840a662e2d/tools/install/install.bzl#L415)):*
> It looks to me like this is packing a list of install actions and shoving them into a provider.

Exactly so.  Anything with install-related steps reifies them into the InstallInfo provider.  Later, those infos are collated into the actual installation recipe.

> Where are the actions specified in `install_actions` carried out?

I'll tag some FYIs below to help illustrate.
___
*[`tools/install/install.bzl` line 438 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21083#-NsFICJdDv7Dv4MyeYLh:-NsFICJeCVIZvr0fxn19:b-9o5oys) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5d325f6ce90ad68131352dbe9830e840a662e2d/tools/install/install.bzl#L438)):*
> ```Starlark
>     rename = dict(ctx.attr.rename)
> 
>     # Collect install actions from dependencies.
> ```

FYI This the "part-whole" composition of install actions.  We concatenate any rule-specific install logic (e.g., `//lcmtypes:install` logic that installs the codegen'd messages) with the install logic of our dependencies (e.g., `@lcm//:install` to install the header files used by the codegen'd messages).
___
*[`tools/install/install.bzl` line 492 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21083#-NsFIheK13xXxgU6d4Ph:-NsFIheK13xXxgU6d4Pi:b1myjyc) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5d325f6ce90ad68131352dbe9830e840a662e2d/tools/install/install.bzl#L492)):*
> ```Starlark
>     installed_tests += _install_test_actions(ctx)
> 
>     # Generate code for install actions.
> ```

FYI Here is where we collate _all_ of the actions into the full recipe.
___
*[`tools/install/install.bzl` line 511 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21083#-NsFIuM834JDJ6TMhoif:-NsFIuM834JDJ6TMhoig:b-1t5efy) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5d325f6ce90ad68131352dbe9830e840a662e2d/tools/install/install.bzl#L511)):*
> ```Starlark
>                  "\n  dst = " + repr(a.dst))
> 
>     # Generate installer manifest.
> ```

FYI If you do `bazel build //:install` and then look at the file `bazel-bin/install_actions` you'll get a sense of what we're doing here.  The fully-collated recipe is written to a file here.
___
*[`tools/install/install.bzl` line 523 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21083#-NsFJ0PpD4fd1IOq_Sm8:-NsFJ0PpD4fd1IOq_Sm9:b-wvrr05) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5d325f6ce90ad68131352dbe9830e840a662e2d/tools/install/install.bzl#L523)):*
> ```Starlark
>         content = "\n".join([
>             "#!/bin/bash",
>             "tools/install/installer --actions '{}' \"$@\"".format(
> ```

FYI Here we create the actual exe program named `//:install`.  It's just a little shim that calls https://github.com/RobotLocomotion/drake/blob/master/tools/install/installer.py, passing it the `install_actions` recipe file.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21083)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

___
*[`tools/install/install.bzl` line 415 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21083#-NsFA8YS8W3WxEMDN4SK:-NsFZM7mCMGZ18f-LB4B:b-q8p81j) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5d325f6ce90ad68131352dbe9830e840a662e2d/tools/install/install.bzl#L415)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> It looks to me like this is packing a list of install actions and shoving them into a provider.

Exactly so.  Anything with install-related steps reifies them into the InstallInfo provider.  Later, those infos are collated into the actual installation recipe.

> Where are the actions specified in `install_actions` carried out?

I'll tag some FYIs below to help illustrate.
</blockquote></details>

They are helpful. Thanks!

**Pull request merged**
