### PR TITLE
[bindings] Add bindings for DeformableBodyConfig

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18308)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for feature review please.
\cc @russtedrake I carved out enough FEM namespace stuff to bind to python that people can run sim with, but stop short of binding FemModel which would allow introspecting things like stiffness/mass/damping matrix. I don't suppose students would need those for projects.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18308#-:-NGdkfmV2OIDMaeF5P5k:b-psgcz8)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by RussTedrake — COMMENTED** [review]
-@ericcousineau-tri , +@russtedrake for feature review.  

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18308#-:-NGh1VXd1F2poOQ1l2aY:baaxdim)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`bindings/pydrake/multibody/test/fem_test.py` line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18308#-NGh1hLH-QV8zGtByuRs:-NGh1hLH-QV8zGtByuRt:b-rtbq6s) ([raw file](https://github.com/robotlocomotion/drake/blob/7e65d5e28e8886f1d8a665b4ae84de1780e5b2b6/bindings/pydrake/multibody/test/fem_test.py#L36)):*
> ```Python
>         for model in models:
>             dut.set_material_model(model)
>             self.assertEqual(dut.material_model(), model)
> ```

I would have thought that you'd have to bind DeformableModel, too?  If this is enough to set up the type of simulation in deformable box, can you add a test_deformable_sim here which shows the very basic setup?

In addition to test coverage and confirmation that it works, this simple test will effectively serve as the minimal documentation to get people started.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18308)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`bindings/pydrake/multibody/test/fem_test.py` line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18308#-NGh1hLH-QV8zGtByuRs:-NGh6s2A-nhD0FhT00uN:bva9yf5) ([raw file](https://github.com/robotlocomotion/drake/blob/7e65d5e28e8886f1d8a665b4ae84de1780e5b2b6/bindings/pydrake/multibody/test/fem_test.py#L36)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I would have thought that you'd have to bind DeformableModel, too?  If this is enough to set up the type of simulation in deformable box, can you add a test_deformable_sim here which shows the very basic setup?

In addition to test coverage and confirmation that it works, this simple test will effectively serve as the minimal documentation to get people started.
</blockquote></details>

You are right. This by itself isn't enough. DeformableModel needs to be bound along with a few other things. 

Those are done in the follow up PR: https://github.com/RobotLocomotion/drake/pull/18310 that will rebase on top of this one (to keep this PR more or less self-contained).

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18308#-:-NGhFOP17Y-KNJk3Gtum:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri for platform, :lgtm_strong:, nice!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18308#-:-NGlgBqD2-wKt3vN8bXP:bdvnrth)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @xuchenhan-tri)

**Comment by EricCousineau-TRI** [comment]
Prior PRs have `release notes: feature`. Adding this tag (sorry for missing that)

**Comment by EricCousineau-TRI** [comment]
Per #18310, tagging `release notes: none` intentional based on it being deformable.

**Pull request merged**
