### PR TITLE
[multibody_doxygen] Remove incorrect statement about model frames

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
As mentioned in https://github.com/RobotLocomotion/drake/pull/14397#issuecomment-1879309659

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20749)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@mitiguy for feature and +@sherm1 for platform, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20749#-:-NnQepQq65cmJ-pe5_ci:bcr8cpq)* status: LGTM missing from assignees mitiguy,sherm1(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by sherm1 — COMMENTED** [review]
TIL -- I didn't realize model frames could move around! 
Out-of-order platform :lgtm:, should still wait for @mitiguy to comment.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20749#-:-NnV4V4t01ekD5_GiXPv:b-dofaf9)* status: LGTM missing from assignee mitiguy, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by mitiguy — COMMENTED** [review]
:lgtm: 
With FYI if we would like some mention of model frames.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20749#-:-NnfQFTp3yjBQO-tqj5r:ba55ssk)* status: missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`multibody/multibody_doxygen.h` line 200 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20749#-NnfEZ-G0B5Q6V457406:-NnfEZ-H7_Fd6ki1hW7P:be0oo6q) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d91d21102a75fe0f643c9fec8ee08757d348109/multibody/multibody_doxygen.h#L200)):*
> ```objc
> Newton's laws of motion are valid in a non-rotating, non-accelerating "inertial
> frame", herein called the _World_ frame W (also called _Ground_ frame G or
> _Newtonian Frame_ N).  Any frame with fixed pose in W is also an inertial frame.
> ```

FYI   Consider whether this may be a helpful alternative.

```
Drake supports _Model_ frames so a simulation can be built from multiple 
independent models, each defined with respect to its own Model frame. 
This corresponds to the SDFormat `<model>` tag (example below). 
http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&#canonical-link-and-model-frame
```

@EricCousineau-TRI thank you for adding the [comment to #14397](https://github.com/RobotLocomotion/drake/pull/14397#issuecomment-1879309659) and  hyperlink to [SDFormat "canonical link" / "model frame" ](http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&#canonical-link-and-model-frame).  Perhaps it may be helpful to provide some sense of Drake's meaning of "model frame". I queried Hongkai, and it seem he (like me) did not have a fully-formed meaning of "model frame".  

Related note to self: [Changes in SDFormat](http://sdformat.org/tutorials?tut=pose_frame_semantics&ver=1.5) due to a bug in SDFormat version before 1.5.

**Review by mitiguy — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20749)* status: missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20749)* status: missing label for release notes

___
*[`multibody/multibody_doxygen.h` line 200 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20749#-NnfEZ-G0B5Q6V457406:-NntJTmrEIzy9t98crza:b6sad07) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d91d21102a75fe0f643c9fec8ee08757d348109/multibody/multibody_doxygen.h#L200)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

FYI   Consider whether this may be a helpful alternative.

```
Drake supports _Model_ frames so a simulation can be built from multiple 
independent models, each defined with respect to its own Model frame. 
This corresponds to the SDFormat `<model>` tag (example below). 
http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&#canonical-link-and-model-frame
```

@EricCousineau-TRI thank you for adding the [comment to #14397](https://github.com/RobotLocomotion/drake/pull/14397#issuecomment-1879309659) and  hyperlink to [SDFormat "canonical link" / "model frame" ](http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&#canonical-link-and-model-frame).  Perhaps it may be helpful to provide some sense of Drake's meaning of "model frame". I queried Hongkai, and it seem he (like me) did not have a fully-formed meaning of "model frame".  

Related note to self: [Changes in SDFormat](http://sdformat.org/tutorials?tut=pose_frame_semantics&ver=1.5) due to a bug in SDFormat version before 1.5.
</blockquote></details>

OK Thanks! but I'm not sure if this is the best place to have that note.
At present, we cross-reference SDFormat documentation here: https://drake.mit.edu/doxygen_cxx/group__multibody__parsing.html
As some point, would be great to make a tutorial.

For now, I'll keep this PR simple and trending towards correctness.

**Comment by EricCousineau-TRI** [comment]
Ah, our docs say to label doc changes as `release notes: none`:
https://drake.mit.edu/reviewable.html

**Pull request merged**
