### PR TITLE
Clarifies style guide to allow const member variables to not be member initialized.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5519)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5519#-:-KfMoUcPySdHTrp9EDjr:bs3tquo)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

Once tidied up, please tag additional reviewers.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/doc/code_style_guide.rst, line 242 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5519#-KfNARYkZ-TJ94JS0u8E:-KfNARYlMts6un29aAKh:b-s2km0t) ([raw file](https://github.com/robotlocomotion/drake/blob/3b0da375351d5426d5e2ed02fa2024fd61dc5b77/drake/doc/code_style_guide.rst#L242)):*
> ```reStructuredText
>   requires that they be initialized in the constructor's initializer list. For
>   more information, see
>   `this Slack discussion <https://drakedevelopers.slack.com/archives/platform_review/p1489628407521372>`_.
> ```

I don't think a slack URL is useful as a permanent record.  Probably omitting a URL is fine, or else use the PR's URL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5519#-:-KfNAbi0EWhVyxR7EMef:b-47jz97)*

**Comment by liangfok** [comment]
Does this PR need by-in from all other platform reviewers?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 242 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5519#-KfNARYkZ-TJ94JS0u8E:-KfNBK2FzOkb9g4Uw35D:bxdc7fw) ([raw file](https://github.com/robotlocomotion/drake/blob/3b0da375351d5426d5e2ed02fa2024fd61dc5b77/drake/doc/code_style_guide.rst#L242)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think a slack URL is useful as a permanent record.  Probably omitting a URL is fine, or else use the PR's URL.
</blockquote></details>

Done. (Removed.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5519#-:-KfNBM9lif5NnvSJI_xW:b11j7m2)*

**Comment by liangfok** [comment]
/s/by-in/buy-in/

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5519#-:-KfNBVIA24v6ZC7ufwOk:b-6uigdz)*

**Comment by jwnimmer-tri** [comment]
I guess just see if there was anyone who didn't already upvote it in slack.

**Comment by david-german-tri** [comment]
+@david-german-tri :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5519#-:-KfNBzlURRANaKYtQwTO:b-vdolsb)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5519)*

**Comment by liangfok** [comment]
Alright, I believe this PR is ready to be merged once it passes CI.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5519#-:-KfNCP0bmMUpDYI4ZIyr:b-xqm72z)*

**Pull request merged**
