### PR TITLE
Adds MaliputRailcar::DoCalcNextUpdateTime().

### PR DESCRIPTION
**Pull request by liangfok**
This is another incremental step towards allowing `MaliputRailcar` to cross lane boundaries.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5532)

### CODE REVIEW

**Comment by liangfok** [comment]
+@rpoyner-tri for feature review please.
+@jwnimmer-tri for car review please.

\CC: @jadecastro since you reviewed all of the previous `MaliputRailcar` PRs and helped answer some questions related to this PR. (I'm just trying to better balance the PR review load as discussed.)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5532#-:-KfPGT2GIeFpNa6aTMdb:b-8op82q)*

**Comment by liangfok** [comment]
Also \CC: @maddog-tri since you also answered quite a few of my questions about this PR. Thanks again.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5532#-:-KfPHFBi8RIE8yER7bjS:b9m6t0m)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput_railcar.cc, line 358 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5532#-KfR-gJs5ACg9Ca4mvsa:-KfR-gJtEB07WGQvbS-X:b-yo6bbk) ([raw file](https://github.com/robotlocomotion/drake/blob/a9571a49aef45ddd7c9fe1d6ac3c0309cc45b085/drake/automotive/maliput_railcar.cc#L358)):*
> ```cpp
>   if (s_dot_dot == 0) {
>     t = distance / s_dot;
>   } else {
> ```

I'm unconvinced that using the second-order input to solve for reaching the end of the lane is worthwhile -- that the vanilla `distance / s_dot` would be fine instead.  What's the thought process for using the acceleration as well?

---

*[drake/automotive/maliput_railcar.cc, line 379 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5532#-KfR0N29Zsnl4Dxujz6X:-KfR0N29Zsnl4Dxujz6Y:brkeze7) ([raw file](https://github.com/robotlocomotion/drake/blob/a9571a49aef45ddd7c9fe1d6ac3c0309cc45b085/drake/automotive/maliput_railcar.cc#L379)):*
> ```cpp
>     } else {
>       throw std::runtime_error("MaliputRailcar::DoCalcNextUpdateTime: Failed "
>           "to find a positive time till vehicle reaches end of lane.");
> ```

BTW This seems like an internal assertion, not an exception?  When would it ever happen?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5532)*

**Comment by liangfok** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 358 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5532#-KfR-gJs5ACg9Ca4mvsa:-KfRBB9d8l9rMxfASlBC:b7z8v1v) ([raw file](https://github.com/robotlocomotion/drake/blob/a9571a49aef45ddd7c9fe1d6ac3c0309cc45b085/drake/automotive/maliput_railcar.cc#L358)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm unconvinced that using the second-order input to solve for reaching the end of the lane is worthwhile -- that the vanilla `distance / s_dot` would be fine instead.  What's the thought process for using the acceleration as well?
</blockquote></details>

If the acceleration is > 0, the vanilla `distance / s_dot` will result in an overestimate of when the vehicle will reach the end of its lane. This will result in the integrator missing the zero transition point.

I am not sure how "bad" this is. Maybe it will just result in the vehicle jerking backwards a little as it resets to the start of the next lane or it maybe it will require slightly more complicated logic to handle the fact that the vehicle may have already traveled past the end of the current lane by the time `CalcUnrestrictedUpdate()` is called?

---

*[drake/automotive/maliput_railcar.cc, line 379 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5532#-KfR0N29Zsnl4Dxujz6X:-KfRBcMOq6C96NM8r7JC:b-l8258g) ([raw file](https://github.com/robotlocomotion/drake/blob/a9571a49aef45ddd7c9fe1d6ac3c0309cc45b085/drake/automotive/maliput_railcar.cc#L379)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This seems like an internal assertion, not an exception?  When would it ever happen?
</blockquote></details>

Done. I changed it to be an abort.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5532)*

**Comment by liangfok** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 358 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5532#-KfR-gJs5ACg9Ca4mvsa:-KfRDN97JeCJ1w_1wyCS:be30tx7) ([raw file](https://github.com/robotlocomotion/drake/blob/a9571a49aef45ddd7c9fe1d6ac3c0309cc45b085/drake/automotive/maliput_railcar.cc#L358)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

If the acceleration is > 0, the vanilla `distance / s_dot` will result in an overestimate of when the vehicle will reach the end of its lane. This will result in the integrator missing the zero transition point.

I am not sure how "bad" this is. Maybe it will just result in the vehicle jerking backwards a little as it resets to the start of the next lane or it maybe it will require slightly more complicated logic to handle the fact that the vehicle may have already traveled past the end of the current lane by the time `CalcUnrestrictedUpdate()` is called?
</blockquote></details>

Similarly, if acceleration < 0, the estimated time of reaching the end of the lane will be an overestimate, meaning `CalcUnrestrictedUpdate()` will be called too early. Again, I'm not sure how bad the consequences of this is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5532)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput_railcar.cc, line 358 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5532#-KfR-gJs5ACg9Ca4mvsa:-KfROPVhAbfonbmyXLZI:b-vv8k79) ([raw file](https://github.com/robotlocomotion/drake/blob/a9571a49aef45ddd7c9fe1d6ac3c0309cc45b085/drake/automotive/maliput_railcar.cc#L358)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Similarly, if acceleration < 0, the estimated time of reaching the end of the lane will be an overestimate, meaning `CalcUnrestrictedUpdate()` will be called too early. Again, I'm not sure how bad the consequences of this is.
</blockquote></details>

If you think the simulator is going to give you exactly s == s_finish or s_start exactly (or even within numeric_limits::epsilon), you are in for a bad time.

I can explain in person how you should be thinking about this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5532)*

**Comment by liangfok** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 358 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5532#-KfR-gJs5ACg9Ca4mvsa:-KfRUW5fjfqw1orCDv-M:b-r1q9zs) ([raw file](https://github.com/robotlocomotion/drake/blob/a9571a49aef45ddd7c9fe1d6ac3c0309cc45b085/drake/automotive/maliput_railcar.cc#L358)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you think the simulator is going to give you exactly s == s_finish or s_start exactly (or even within numeric_limits::epsilon), you are in for a bad time.

I can explain in person how you should be thinking about this.
</blockquote></details>

Alright, I'll remove the second order logic. I figured there must be some tolerance for error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5532)*

**Comment by liangfok** [comment]
I'll close this PR and submit a new PR that contains only first-order logic.

**Pull request closed without merging**
