### PR TITLE
add velocity to iiwa_status_message.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7166)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri for feature and platform reviews. thanks. 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7166#-:-KvbhNlhSqwpZs4qOs96:b-to1u2y)*

**Comment by sammy-tri** [comment]
First pass complete

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7166#-Kvd9urqaWC8S3kU-Q8Y:-Kvd9ursPCsdad7l6VGH:b-ncvzz4) ([raw file](https://github.com/robotlocomotion/drake/blob/3359f4d83f6a312772c57bdb623a9106891eb69f/drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L183)):*
> ```cpp
>   ASSERT_EQ(status.num_joints, kNumJoints);
>   for (int i = 0; i < kNumJoints; i++) {
>     EXPECT_EQ(status.joint_position_commanded[i], command(i));
> ```

Should we check here that `joint_velocity_estimated` is populated correctly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7166#-:-KvdA00p6EopeM87VF--:ba6b0kz)*

**Comment by siyuanfeng-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7166#-Kvd9urqaWC8S3kU-Q8Y:-KvdBtvnLRMgr0Jn5tnO:b-s3p1tj) ([raw file](https://github.com/robotlocomotion/drake/blob/3359f4d83f6a312772c57bdb623a9106891eb69f/drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L183)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should we check here that `joint_velocity_estimated` is populated correctly?
</blockquote></details>

fail. done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7166)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7166)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7166#-:-Kvh-Yk51X8rYIS0Ojr3:bnfp4nl)*

**Pull request merged**
