### PR TITLE
Bump the snopt SHA for Bazel fixes.

### PR DESCRIPTION
**Pull request by david-german-tri**
In particular, this removes a snopt-provided `main()` that was defeating the `main()` in some Drake targets.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5135)

### CODE REVIEW

**Comment by david-german-tri** [comment]
To confirm the fix:
```
bazel build --config=snopt --build_tag_filters= //drake/multibody:test_ik_more_constraints && ./bazel-bin/drake/multibody/test_ik_more_constraints
```

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5135#-:-KcegsIgA7cSTIXdgaJC:bnfp4nl)*

**Comment by RussTedrake** [comment]
does this imply snopt-support for bazel is close?  not having it is a pain point for my migration to bazel.

**Comment by jwnimmer-tri** [comment]
We thought it was already working, but this PR fixes a bad bug.  With this PR, support for `snopt` is in pretty good shape, though I'd think we're still iterating a bit on good UX for opt-in in (or out?) of it.

I guess http://drake.mit.edu/bazel.html doesn't explain how to use snopt yet, maybe because the UX is still unstable.  Right now, it's `bazel build --config snopt ...` which makes `MathematicalProgram` have the real `snopt_solver` backend instead of the `no_snopt` stub.  Then `bazel test --config snopt ...` will run (only the) snopt-requiring unit tests.

Bazel porting status is general is kept at https://github.com/RobotLocomotion/drake/issues/3129#issuecomment-269377533 but for solvers is also in-tree at https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/BUILD#L54-L65.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5135#-:-Kcma39gWpxshnnmW5N2:bfp1h9q)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please
We can merge after this passes.

**Comment by RussTedrake** [comment]
thanks.  I got the same issues that hongkai had reported on slack
```
P50:~/drake-distro$ bazel build //...
WARNING: /home/hongkai/drake-distro/drake/util/BUILD:9:1: target '//drake/util:util' is deprecated: These utilities are moving to //drake/math.
ERROR: /home/hongkai/drake-distro/externals/snopt/BUILD:10:1: no such package 'cppsrc': BUILD file not found on package path and referenced by '//externals/snopt:snopt_cpp'.
ERROR: Analysis of target '//externals/snopt:snopt_cpp' failed; build aborted.
INFO: Elapsed time: 1.069s
```
at first.  but zapped externals/snopt, then ran bazel build successfully.  now adding --config snopt seems to have worked.  (but I'm not sure what would have happened, yet, if externals/snopt had stayed).

**Comment by david-german-tri** [comment]
The mac-clang-bazel-experimental failures are pre-existing - they show up in nightly builds on Saturday, Sunday, Monday.   That CI target doesn't actually exercise SNOPT, but at least confirms this PR didn't break anything else.  So, I'm going to override-merge, then buildcop the other problems.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5135#-:-KcryB7e-V13ASnAw81E:b-rdgaeh)*

**Comment by jwnimmer-tri** [comment]
Thanks -- I couldn't quite figure out what was going on and didn't spend time investigating.  Glad this PR could go in.

**Pull request merged**
