### PR TITLE
Updated run_kuka_iiwa_arm_dynamics to use System 2.0

### PR DESCRIPTION
**Pull request by liangfok**
In the process, I also created a new System 2.0 shared library for KUKA iiwa demos called `drakeKukaIiwaArmCommon`. I wasn't able to add the System 2.0 methods into the previously existing `drakeKukaIiwaArm` library (which is based on System 1.0) due to naming conflicts related to `Gain`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3745)

### CODE REVIEW

**Comment by liangfok** [comment]
+@naveenoid for feature review please.
+@sherm1 for platform review please.

CC: @amcastro-tri since I added a constructor to `RigidBodyPlant`. I know you don't want to expose the contact gains but I really need to be able to change them for the soon-to-exist System 2.0-based `car_sim_lcm` demo.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-:-KTjdM16fD1RWOqr0iPE:bhtawn5)*

**Comment by sherm1** [comment]
I'm punting on platform review to tomorrow's reviewer +@david-german-tri, but attempted to channel -@amcastro-tri since he isn't available. I don't want a new constructor added to RBPlant but some accessors would be OK. With that change :lgtm:.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.h, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTlmMdxtqYXiY5Z4IsW:-KTlmMdxtqYXiY5Z4IsX:b-ck53kb) ([raw file](https://github.com/robotlocomotion/drake/blob/2bf6865c90026554ada4aad5898966a329c49c97/drake/systems/plants/rigid_body_plant/rigid_body_plant.h#L80)):*
> ```objc
>   /// the world in @p tree.
>   explicit RigidBodyPlant(std::unique_ptr<const RigidBodyTree> tree,
>     T penetration_stiffness, T penetration_damping, T friction_coefficient);
> ```

@liangfok, please don't add a new constructor for these which I feel cements them in place just as they are about to be removed. For now, please just add accessors for the parameters, e.g. `set_penetration_stiffness()` and leave the old defaults in place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-:-KTlnWqhzknHEepU8ZuE:b-i2zzzn)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KToEvWfqLKQuws62HiV:-KToEvWfqLKQuws62HiW:boe1ghv) ([raw file](https://github.com/robotlocomotion/drake/blob/2bf6865c90026554ada4aad5898966a329c49c97/drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc#L129)):*
> ```cpp
>   const VectorBase<double>& velocity_vector = state->get_generalized_velocity();
> 
>   const int num_p = position_vector.size();
> ```

BTW, I think this would more conventionally be `num_q`.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.h, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTlmMdxtqYXiY5Z4IsW:-KToFXcHq8EIlu7Bebms:bon1te9) ([raw file](https://github.com/robotlocomotion/drake/blob/2bf6865c90026554ada4aad5898966a329c49c97/drake/systems/plants/rigid_body_plant/rigid_body_plant.h#L80)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> @liangfok, please don't add a new constructor for these which I feel cements them in place just as they are about to be removed. For now, please just add accessors for the parameters, e.g. `set_penetration_stiffness()` and leave the old defaults in place.
</details>
BTW, those seem about equally cement-flavored to me, but I will defer to @sherm1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-:-KToFbyXQuJY-blR-lRh:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 5 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KToEvWfqLKQuws62HiV:-KTonowtqVYxqABM8NNP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2bf6865c90026554ada4aad5898966a329c49c97/drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc#L129)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, I think this would more conventionally be `num_q`.
</details>
Done.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.h, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTlmMdxtqYXiY5Z4IsW:-KTonpfxz2kjslT78_tv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2bf6865c90026554ada4aad5898966a329c49c97/drake/systems/plants/rigid_body_plant/rigid_body_plant.h#L80)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, those seem about equally cement-flavored to me, but I will defer to @sherm1.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-:-KTonqduor8kEJ134gnJ:bblnx7v)*

**Comment by liangfok** [comment]
Since -@naveenoid may not be available, +@sammy-tri for feature review please.

---

Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-:-KTooMIKzBN8b4F0iZpL:b-r2towg)*

**Comment by sherm1** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTovRp5d3Py7JSIVrw1:-KTovRp5d3Py7JSIVrw2:bd1p97) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b286bb4007525ed835adfb0c562f94247fef14/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L11)):*
> ```CMake
>       drakeLCMSystem2
>       drakeTrajectories
>       GTest::GTest GTest::Main)
> ```

BTW, are those actual library names?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTovRp5d3Py7JSIVrw1:-KTow6HXi0tFDt6iFF_Z:b-2dr98u) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b286bb4007525ed835adfb0c562f94247fef14/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, are those actual library names?
</details>
Good question. I saw that they were added in #3748. I believe they are special keywords made available by `CMake`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 8 files at r1, 3 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTozSj6bJh7m6ozUhwm:-KTozSj6bJh7m6ozUhwn:b-jmepyd) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b286bb4007525ed835adfb0c562f94247fef14/drake/examples/kuka_iiwa_arm/iiwa_common.h#L3)):*
> ```objc
> #pragma once
> 
> #include <memory>
> ```

unused

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTozTWRZ8V4FH-lJAxZ:-KTozTWRZ8V4FH-lJAx_:b-jmepyd) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b286bb4007525ed835adfb0c562f94247fef14/drake/examples/kuka_iiwa_arm/iiwa_common.h#L5)):*
> ```objc
> #include <memory>
> 
> #include <Eigen/Geometry>
> ```

unused

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTozUF0DBQR7X0EAOK5:-KTozUF0DBQR7X0EAOK6:b-jmepyd) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b286bb4007525ed835adfb0c562f94247fef14/drake/examples/kuka_iiwa_arm/iiwa_common.h#L6)):*
> ```objc
> 
> #include <Eigen/Geometry>
> #include <lcm/lcm-cpp.hpp>
> ```

unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745)*

**Comment by liangfok** [comment]
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTozSj6bJh7m6ozUhwm:-KTpBXH6tMYhhJ4DK5yB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b286bb4007525ed835adfb0c562f94247fef14/drake/examples/kuka_iiwa_arm/iiwa_common.h#L3)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> unused
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTozTWRZ8V4FH-lJAxZ:-KTpBXsQlOCVvWagvg_3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b286bb4007525ed835adfb0c562f94247fef14/drake/examples/kuka_iiwa_arm/iiwa_common.h#L5)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> unused
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTozUF0DBQR7X0EAOK5:-KTpBYZwiVlBAuPn0mUA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b286bb4007525ed835adfb0c562f94247fef14/drake/examples/kuka_iiwa_arm/iiwa_common.h#L6)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> unused
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 2 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-:-KTpFEu66w4wn09XmJQB:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Now waiting on CI to complete.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-:-KTpGmgk5u4WirZpUioC:b3pc2w6)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3745#-KTovRp5d3Py7JSIVrw1:-KTpNwrXHrwPlzJY50-g:b84dgxo) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b286bb4007525ed835adfb0c562f94247fef14/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L11)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Good question. I saw that they were added in #3748. I believe they are special keywords made available by `CMake`.
</details>
@sherm1's comment was marked BTW. I'll thus dismiss him from this thread so this PR can be merged (it's blocking my pending `car_sim_lcm 2.0` PR)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3745)*

**Comment by amcastro-tri** [comment]
Late to the party but I feel a lot of this code is repeated in `https://github.com/RobotLocomotion/drake/tree/master/drake/examples/kuka_iiwa_arm/controlled_kuka` ? Probably your `KukaIiwaArmDynamicsSim` could be refactored to a `KukaPlant` that then the controlled kuka demo can also use? that way we'd avoid code duplication.

**Comment by liangfok** [comment]
@amcastro-tri: Good idea! I created a ticket to remind myself: https://github.com/RobotLocomotion/drake/issues/3865

**Pull request merged**
