### PR TITLE
Kuka demo (Sys2.0) + Director integration

### PR DESCRIPTION
**Pull request by naveenoid**
The integrated demo with the listener on the LCM to the plan from the Director and the KUKA IIWA Arm on Sys2.0

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3318)

### CODE REVIEW

**Comment by tkoolen** [comment]
I was trying out this branch. I'm running drake-visualizer and kuka_director_plan_control_demo, but I don't know how to send a plan. Could you help me out?

**Comment by liangfok** [comment]
Check out `drake/examples/kuka_iiwa_arm/kuka_director_ik_trajectory_publisher_standin.cc`, which  obtains a joint space trajectory by calling `GenerateIKDemoJointTrajectory()` and  sends it to `kuka_director_plan_control_demo` via LCM.

Note that the demo isn't working yet. There's at least one more segmentation fault to fix before we can run the demo. The code itself will need a _major_ cleanup before it can be merged into master.

**Comment by tkoolen** [comment]
OK, thanks for the heads up.

**Comment by naveenoid** [comment]
Going to close this PR in the light of several subsequent PRs which will effectively accomplish the same objective.

**Pull request closed without merging**
