### PR TITLE
Make some acrobot targets public

### PR DESCRIPTION
**Pull request by ggould-tri**
* The upstream repo that this code migrated from still needs direct
   access to these files to avoid duplication.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14596)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@jwnimmer-tri +(status: single reviewer ok)
Manually verified with my downstream acrobot migration branch https://github.shared-services.aws.tri.global/robotics/anzu/compare/master...grant-gould:remove_local_acrobot?expand=1

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14596#-:-MS9sruL1dgiIkm5main:brlf5pm)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I've been working on somewhat of an invariant in Drake, though at this point is is admittedly a leaky abstraction and not well-encoded into any documentation.  It goes something like this ...

For any artifact in Drake (a library component, sample program, data resource, or build script), it should either be part of our public deliverables and supported API, or else it should be marked as non-public and be used only for internal purposes within Drake; no middle ground.  Things that are on the public side of that coin should be equally well-accessible through either the CMake source build or the Bazel source build, should have some reasonable minimal docs, be covered by deprecation when practical, etc.  Public artifacts that are sensibly usable at runtime (i.e., everything except build scripts) should also appear in the binary releases.

In other words, Anzu should only use public Drake entry points, and anything that's marked public in Drake should follow deprecation conventions and should be installed.

I've found that things that are halfway between those extremes can lead to confusion, both for developers and for users.

Here, we're making more portions of the acrobot example _libraries_ publicly visible.  If we tried to follow the above rules, that would mean we also need to install those python sources.  We could choose to do that in this PR.

I wonder though, if given the above (idealized) invariant, if we'd be better off just keeping the files copied, with a hope to rely on copybara in the future.  I'm not sure that we want to play the game of shipping lots of Drake's examples in library form, so that we can use them as devices-under-test in Anzu.

(I've been hesitating to post this because it's posing a problem without any good solution yet, but I thought it was worth doing the brain dump at this point, instead of just remaining silent.)

**Comment by ggould-tri** [comment]
I share your misgivings about fudging the private/public difference but I come out on the other side -- almost nothing should ever be enforced-private (or final) because it is maddeningly irritating to a consumer when an upstream artifact exists but is inaccessible, or requires vendoring just to flip an access bit.

This also throws a wrench into anzu-to-drake workflows, because it is in effect saying that any code that you migrate but still depend on must become an installed artifact (or alternatively that anzu should vendor portions of drake, which is silly).  In effect it would make dependency-slicing, our hardest problem, harder by requiring us to slice some anzu dependencies on the migrated code in addition to the other direction.  Placing another speed bump in the already-slow migration process seems like a self-inflicted wound.

If Copybara solves all of this for us, great (and I'm happy to hold off on this PR until then - it has no urgency).  But if it does not then I counterpropose "everything in examples/ should always be default-public":
 * Examples exist to be reused and reusers should not have to care about our packaging decisions.
 * An example is typically not intended to be a meaningful library.

**Comment by ggould-tri** [comment]
Okay, I've thought this over a bit more, and here are my slightly more refined thoughts.

There are really only three right ways to consume an artifact from a repostitory:  You can consume the built artifacts, you can consume the repo as external sources you compile against, or you can vendor it with local changes and bear the cost of maintaining a de-facto local fork.

Your proposal is that the first two -- built artifacts and source -- are basically the same; consumable source (public bazel targets) should exactly mirror installed libraries/binaries.  This seems like a reasonable proposal that minimizes a potentially confusing support burden (docs, deprecation, etc.).  My argument against this is in effect that it only leaves vendoring available, and vendoring is unpleasant and, unless carefully done, unsound.  It's especially risky when you are in effect vendoring half a dozen source files between larger repos rather than vendoring to or from a whole repo.

The obvious reason I am wrong here is Copybara, which insofar as it manages syncing source between two locations in the presence of diffs, is basically a tool for automating sub-repo scoped vendoring.  I had been thinking of copybara as just a copying tool, but if I think of it as a vendoring tool then it breaks my objections quite neatly.

So I think I'm down to agreement:  Let's use these few files as a testbed for copybara and, if it works, make that the supported way to consume non-public drake material in other repos; that will let us pare back drake's use of public in random example artifacts.

I'll close this PR and its parent issue, and create a new issue for the duplicated code; we can then use that issue to track the copybara work.

**Pull request closed without merging**
