### PR TITLE
[multibody] Bump tolerance for compliant_contact_manager_test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
On Mac Ventura Arm, this comparison was [slightly beyond tolerance](https://drake-cdash.csail.mit.edu/test/1051757934).  Towards #18327.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19401)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@joemasterjohn for feature review, please (as original author).  If bumping the tolerance here is not the correct fix, please push the correct fix instead (either here, or in a new PR).

Note that the CI failure in `mac-arm-ventura-clang-bazel-experimental-release` doesn't indicate problem with this PR.  The test case changed in this PR is passing in that build.  It shows that other test cases are still failing as we work to spin up Ventura.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: I added a commit to future proof this test for numerical comparisons that *should* have originally been using a tolerance. 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19401#-:-NVUzvKf9mqBAKRfJne_:beronwt)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.  (We'll squash-and-merge once its ready.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19401#-:-NVV2MOkCE983rDH0Xiv:bmxilld)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
