### PR TITLE
[geometry] Add benchmark for internal::BoxesOverlap

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
Relates to #21526.

This patch is a start; we'll likely want either more cases or a different benchmark program to imitate typical statistics of poses.

+@SeanCurtis-TRI for feature review.
FYI @jwnimmer-tri 
+(release notes: feature) (??)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-:-O-qoZT05sbPZZNeUuX5:bmnoa22)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
The benchmark isn't installed, so it's +(release notes: none).

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a couple of questions.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-:-O09gXzR6qLQbidxKwOU:b-ti15gs)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 65 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O09fvS99fVfbGJGR2ky:-O09fvS99fVfbGJGR2kz:bmszyiy) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a4a0db13d41b81463a051bd0eca0fc06b66c4f/geometry/benchmarking/boxes_overlap_benchmark.cc#L65)):*
> ```cpp
>   a = Vector3d(2, 4, 3);
>   b = Vector3d(3.5, 2, 1.5);
>   SetupCase(state);
> ```

Question: How much time is spent setting up the case and inverting the transform relative to the execution of the for loop? By benchmark semantics are hazy at best. But it seems like we get two obb tests per setup, right?
___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O09gOAHCamB3XuDj7FL:-O09gOAHCamB3XuDj7FM:b-jht5qt) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a4a0db13d41b81463a051bd0eca0fc06b66c4f/geometry/benchmarking/boxes_overlap_benchmark.cc#L79)):*
> ```cpp
>     ->Unit(benchmark::kNanosecond)
>     ->ArgsProduct({{false, true}, {0, 1, 2}, {-1, 0, 1, 2}});
> ```

Do you have a plan for how you would respell this to provide a statistical distribution of test results?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 65 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O09fvS99fVfbGJGR2ky:-O09hxdn6CWJIIvB8ykM:b573kan) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a4a0db13d41b81463a051bd0eca0fc06b66c4f/geometry/benchmarking/boxes_overlap_benchmark.cc#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Question: How much time is spent setting up the case and inverting the transform relative to the execution of the for loop? By benchmark semantics are hazy at best. But it seems like we get two obb tests per setup, right?
</blockquote></details>

Two things to remember about gbench:

(1) Only the `for ... state` loop is timed -- the time of the setup code is not reported.  Thus the only downside of expensive setup code is a longer developer latency waiting for benchmark output.

(2) The `for auto state` is magic that loops until we it has "enough" samples.  Rule of thumb, imagine the loop runs thousands or millions of time.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 65 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O09fvS99fVfbGJGR2ky:-O09yotd4GD-akjUpQpp:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a4a0db13d41b81463a051bd0eca0fc06b66c4f/geometry/benchmarking/boxes_overlap_benchmark.cc#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Two things to remember about gbench:

(1) Only the `for ... state` loop is timed -- the time of the setup code is not reported.  Thus the only downside of expensive setup code is a longer developer latency waiting for benchmark output.

(2) The `for auto state` is magic that loops until we it has "enough" samples.  Rule of thumb, imagine the loop runs thousands or millions of time.
</blockquote></details>

Done.
___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O09gOAHCamB3XuDj7FL:-O09yLAWBXCfmt__Cagm:b-pvzr30) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a4a0db13d41b81463a051bd0eca0fc06b66c4f/geometry/benchmarking/boxes_overlap_benchmark.cc#L79)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Do you have a plan for how you would respell this to provide a statistical distribution of test results?
</blockquote></details>

Doing a distribution probably requires a bunch of new code. We likely want to capture some pseudo-random sequence of case inputs ahead of time, have different parameters, etc. It may be the case that the statistical distribution test is a poor fit for the google bench style.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596)* status: needs at least two assigned reviewers

___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 65 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O09fvS99fVfbGJGR2ky:-O0AxhZ463Zpa2ME8E0n:b-9xqqrg) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a4a0db13d41b81463a051bd0eca0fc06b66c4f/geometry/benchmarking/boxes_overlap_benchmark.cc#L65)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Riiiiiight.  The magic. I'd forgotten what the containing glyphs are.
___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O09gOAHCamB3XuDj7FL:-O0Axq-YCPAnEPZTrZyg:bdsfau1) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a4a0db13d41b81463a051bd0eca0fc06b66c4f/geometry/benchmarking/boxes_overlap_benchmark.cc#L79)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Doing a distribution probably requires a bunch of new code. We likely want to capture some pseudo-random sequence of case inputs ahead of time, have different parameters, etc. It may be the case that the statistical distribution test is a poor fit for the google bench style.
</blockquote></details>

Right. So, this benchmark can tell us if the underlying function gets faster, but it won't necessarily tell us how much faster any particular application gets.  It's not seeking to model that. Worth adding the caveat to the documentation at the top?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O09gOAHCamB3XuDj7FL:-O0BFjBV3dHJxW0HuR3R:bk2kvwq) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a4a0db13d41b81463a051bd0eca0fc06b66c4f/geometry/benchmarking/boxes_overlap_benchmark.cc#L79)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Right. So, this benchmark can tell us if the underlying function gets faster, but it won't necessarily tell us how much faster any particular application gets.  It's not seeking to model that. Worth adding the caveat to the documentation at the top?
</blockquote></details>

That seems tautologically true of any microbenchmark. I'd buy a TODO that says "let's consider adding a schedule that defeats branch prediction, and maybe has some relationship to observed branch execution statistics."

**Review by rpoyner-tri — COMMENTED** [review]
+@ggould-tri for platform review; Tuesday schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-:-O0BHUZC-2tTOI5dSSfv:b-5dbuyr)* status: LGTM missing from assignee ggould-tri(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596)* status: LGTM missing from assignee ggould-tri(platform)

___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O09gOAHCamB3XuDj7FL:-O0BVIFfC9zzCe9lrjwD:b-o6zxnu) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a4a0db13d41b81463a051bd0eca0fc06b66c4f/geometry/benchmarking/boxes_overlap_benchmark.cc#L79)):*
> tautologically true of any microbenchmark

Agreed. But I don't think the documentation overview makes it clear that this *is* (and is intended to remain) a microbenchmark.

That said, the TODO you added covers everything for me. So, I'm content.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; the implementation looks correct but the comments are thin on some of the more confusing code.

> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-:-O0EY5xF3ShaEB0xShNu:b-knoszp)* status: 7 unresolved discussions

___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 19 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O0EvXpT5W8tBcxtD611:-O0EvXpT5W8tBcxtD612:btwlx7q) ([raw file](https://github.com/RobotLocomotion/drake/blob/aa405e1f99ba235d0db5fca956832baacb74bc2a/geometry/benchmarking/boxes_overlap_benchmark.cc#L19)):*
> ```cpp
> namespace internal {
> 
> struct Case {
> ```

This struct very much needs a comment; it's hard to make sense of the rest of the code without understanding what is going on here.  If it's specific to `PosedCase` then it belongs there.

In particular the meaning of `b_axis.has_value` is unintuitive (to this reader at least)

Alternatively, it's not especially clear why this struct exists at all, since it is used only a single local of one particular function and then discarded.  Couldn't its members just be folded in there instead -- and even be const, in that case.
___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 30 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O0Ewcv82mVcAQMIP9lT:-O0Ewcv82mVcAQMIP9lU:bmw76hb) ([raw file](https://github.com/RobotLocomotion/drake/blob/aa405e1f99ba235d0db5fca956832baacb74bc2a/geometry/benchmarking/boxes_overlap_benchmark.cc#L30)):*
> ```cpp
> class BoxesOverlapBenchmark : public benchmark::Fixture {
>  public:
>   void SetupCase(const benchmark::State& state) {
> ```

minor:  This needs some comment as to when it should be used, since it's called by only one of the two test cases below which seems odd.

I think the answer may be that `ParallelContainedCase` should be passing its fixed values into `SetupCase` rather than setting them directly, for consistency?
___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 51 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O0ExRkADicTKbOysJBW:-O0ExRkADicTKbOysJBX:b-lxfmk0) ([raw file](https://github.com/RobotLocomotion/drake/blob/aa405e1f99ba235d0db5fca956832baacb74bc2a/geometry/benchmarking/boxes_overlap_benchmark.cc#L51)):*
> ```cpp
> };
> 
> BENCHMARK_DEFINE_F(BoxesOverlapBenchmark, ParallelContainedCase)
> ```

minor:  It would be good to have a comment explaining what is being tested here.
___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 57 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O0Ey9uED7c9fFr77AzY:-O0Ey9uFA3DR2Jo_fSOm:b-k0uqzr) ([raw file](https://github.com/RobotLocomotion/drake/blob/aa405e1f99ba235d0db5fca956832baacb74bc2a/geometry/benchmarking/boxes_overlap_benchmark.cc#L57)):*
> ```cpp
>   b = Vector3d(0.5, 1, 0.5);
>   X_AB = RigidTransformd{Vector3d{0.2, 0.4, 0.2}};
>   auto X_BA = X_AB.inverse();
> ```

nit:  `const` might slightly reduce the confusion here.
___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 58 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O0Eyp5F4e6QIOdGYTwg:-O0Eyp5G1c6pmqiji2XQ:bgsbu7q) ([raw file](https://github.com/RobotLocomotion/drake/blob/aa405e1f99ba235d0db5fca956832baacb74bc2a/geometry/benchmarking/boxes_overlap_benchmark.cc#L58)):*
> ```cpp
>   X_AB = RigidTransformd{Vector3d{0.2, 0.4, 0.2}};
>   auto X_BA = X_AB.inverse();
>   for (auto _ : state) {
> ```

BTW:  This idiom is going to be baffling to readers not already expert in `google/benchmark`.  Consider (author's discretion) explaining what the heck is going on.
___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 64 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O0ExT1dBLZV0bDqF1-I:-O0ExT1dBLZV0bDqF1-J:b-lxfmk0) ([raw file](https://github.com/RobotLocomotion/drake/blob/aa405e1f99ba235d0db5fca956832baacb74bc2a/geometry/benchmarking/boxes_overlap_benchmark.cc#L64)):*
> ```cpp
> }
> 
> BENCHMARK_DEFINE_F(BoxesOverlapBenchmark, PosedCase)
> ```

minor:  It would be good to have a comment explaining what is being tested here.
___
*[`geometry/test_utilities/boxes_overlap_transforms.h` line 10 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O0EzX9S2_fe2jj1HGwv:-O0EzX9T4YOyxsg_felC:bnkgh6o) ([raw file](https://github.com/RobotLocomotion/drake/blob/aa405e1f99ba235d0db5fca956832baacb74bc2a/geometry/test_utilities/boxes_overlap_transforms.h#L10)):*
> ```objc
> 
> // We want to compute X_AB such that B is posed relative to A as documented in
> // BoxesOverlapTest. We can do so by generating the rotation component, R_AB,
> ```

I'm not sure what "as documented in BoxesOverlapTest" means here.
I think you're referring to the implementation comments in `AllCases` perhaps?



_Suggestion:_
```objc
// We want to compute X_AB such that B is posed relative to A as documented in
// BoxesOverlapTest::AllCases. We can do so by generating the rotation component, R_AB,
```

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596)* status: 1 unresolved discussion

___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 19 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O0EvXpT5W8tBcxtD611:-O0FU45_-7o9neIiUvSk:b-lsnpun) ([raw file](https://github.com/RobotLocomotion/drake/blob/aa405e1f99ba235d0db5fca956832baacb74bc2a/geometry/benchmarking/boxes_overlap_benchmark.cc#L19)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This struct very much needs a comment; it's hard to make sense of the rest of the code without understanding what is going on here.  If it's specific to `PosedCase` then it belongs there.

In particular the meaning of `b_axis.has_value` is unintuitive (to this reader at least)

Alternatively, it's not especially clear why this struct exists at all, since it is used only a single local of one particular function and then discarded.  Couldn't its members just be folded in there instead -- and even be const, in that case.
</blockquote></details>

The google benchmark mechanism for passing parameters I find a bit opaque (state.range(0), etc.). My hope was to have something that those would map to; and as you point out, they still need more explaining. I suppose I could inline the struct or remove it, but I think with more commentary, the struct definition is justified as a locus for documentation. PTAL.
___
*[`geometry/benchmarking/boxes_overlap_benchmark.cc` line 58 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21596#-O0Eyp5F4e6QIOdGYTwg:-O0FXLpH3lO2v_9m3hxd:br7i3sl) ([raw file](https://github.com/RobotLocomotion/drake/blob/aa405e1f99ba235d0db5fca956832baacb74bc2a/geometry/benchmarking/boxes_overlap_benchmark.cc#L58)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  This idiom is going to be baffling to readers not already expert in `google/benchmark`.  Consider (author's discretion) explaining what the heck is going on.
</blockquote></details>

This is *the central idiom* of google benchmark; I don't know why one would would belabor it here, as opposed to the other 14 benchmark files that use it.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21596)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
