### PR TITLE
Detect dual infeasible for mosek.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Mosek doesn't detect unbounded problem, instead it only detects dual infeasibility, which can mean that the primal is infeasibe/unbounded/has a solution.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7675)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+(status: do not review) 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-:-L1pLe8IhNmJjNSPIAxE:b7ovtzr)*

**Comment by hongkai-dai** [comment]
-(status: do not review) +@ericcousineau-tri for feature review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-:-L3Ta2AYbsfa9N8cq2rZ:b-omwr12)*

**Comment by avalenzu** [comment]
A couple of questions below.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program_solver_interface.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3U_iqGebgCSSJ1py9c:-L3U_iqGebgCSSJ1py9d:b-kftue3) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/solvers/mathematical_program_solver_interface.h#L14)):*
> ///<

BTW Is this doxygen syntax?

---

*[solvers/mathematical_program_solver_interface.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3UaSabTs8H5hFVUrlF:-L3UaSabTs8H5hFVUrlG:b1m128v) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/solvers/mathematical_program_solver_interface.h#L23)):*
> ```objc
>   kIterationLimit = -6,  ///< Reaches the iteration limits.
>   kDualInfeasible = -7,  ///< Dual problem is infeasible. In this case we cannot
>                          /// infer the status of the primal problem.
> ```

Can the primal problem be bounded and feasible if the dual problem is infeasible? If not, then should `kDualInfeasible` and `kInfeasible_Or_Unbounded` be combined?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-:-L3Uat6Wqhos2NKQxYq-:b-r0kn4z)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program_solver_interface.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3UaSabTs8H5hFVUrlF:-L3Un5Z34wETo7sxrvrD:b-savxjj) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/solvers/mathematical_program_solver_interface.h#L23)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Can the primal problem be bounded and feasible if the dual problem is infeasible? If not, then should `kDualInfeasible` and `kInfeasible_Or_Unbounded` be combined?
</blockquote></details>

Yes, the primal problem can be bounded and feasible, if the dual problem is infeasible. Here is an example, that @frankpermenter cleverly came up with
```
Dual problem is infeasible
max 0 
[0  1
 1  y] >=0

The corresponding primal is neither infeasible or unbounded.  In fact, it has an optimal value of zero, attained by any point of the form:

[ x , 0
 0  , 0]  x>=0.
```
Frank also pointed this paper https://repub.eur.nl/pub/1412/ as a reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program_solver_interface.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3U_iqGebgCSSJ1py9c:-L3UpRqClThLH_u-aNMU:b-3r6xxk) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/solvers/mathematical_program_solver_interface.h#L14)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> ///<

BTW Is this doxygen syntax?
</blockquote></details>

Yes, you can check https://stackoverflow.com/questions/13752191/documenting-enum-values-with-doxygen

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program_solver_interface.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3U_iqGebgCSSJ1py9c:-L3UqF-NHTRHedIhzbfn:bfedqzl) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/solvers/mathematical_program_solver_interface.h#L14)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes, you can check https://stackoverflow.com/questions/13752191/documenting-enum-values-with-doxygen
</blockquote></details>

This is what the doxygen looks like


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675)*

**Comment by avalenzu** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program_solver_interface.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3U_iqGebgCSSJ1py9c:-L3YRQcxojh5mCr3GUZL:b-83sjoh) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/solvers/mathematical_program_solver_interface.h#L14)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This is what the doxygen looks like


</blockquote></details>

Nice!

---

*[solvers/mathematical_program_solver_interface.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3UaSabTs8H5hFVUrlF:-L3YRaO3oJadutKi7618:bi64uvo) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/solvers/mathematical_program_solver_interface.h#L23)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes, the primal problem can be bounded and feasible, if the dual problem is infeasible. Here is an example, that @frankpermenter cleverly came up with
```
Dual problem is infeasible
max 0 
[0  1
 1  y] >=0

The corresponding primal is neither infeasible or unbounded.  In fact, it has an optimal value of zero, attained by any point of the form:

[ x , 0
 0  , 0]  x>=0.
```
Frank also pointed this paper https://repub.eur.nl/pub/1412/ as a reference.
</blockquote></details>

Good to know! Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-:-L3YRfqgmS51eY8M3tfr:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-@EricCousineau-TRI for platform review. +@sammy-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-:-L3YnBo9NCGR2l7Um6k-:b9f0i65)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/inverse_kinematics_backend.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3Z5iUpCuKvm_TvBC3U:-L3Z5iUpCuKvm_TvBC3V:b8464vo) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/multibody/inverse_kinematics_backend.cc#L69)):*
> ```cpp
>       return 3;
>     }
>     case SolutionResult::kDualInfeasible: {
> ```

Should this actually be the same case as `kInfeasibleConstraints`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-:-L3Z6SXg6o_JYJuL3oXS:bnfp4nl)*

**Comment by sammy-tri** [comment]
(err, that lgtm was pending one issue)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-:-L3Z6XQjSLz1LGXdtqUA:bad56xf)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/inverse_kinematics_backend.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3Z5iUpCuKvm_TvBC3U:-L3Z7B8P7AkocH2VOpcj:bgzu6nn) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/multibody/inverse_kinematics_backend.cc#L69)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this actually be the same case as `kInfeasibleConstraints`
</blockquote></details>

For the nonlinear optimization solvers such as SNOPT, it does not report dual infeasibility, so according to the documentation below, dual infeasible is not a real SNOPT error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/inverse_kinematics_backend.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3Z5iUpCuKvm_TvBC3U:-L3ZAFAnKvLKLHnHgQIi:b2lfafc) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/multibody/inverse_kinematics_backend.cc#L69)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

For the nonlinear optimization solvers such as SNOPT, it does not report dual infeasibility, so according to the documentation below, dual infeasible is not a real SNOPT error.
</blockquote></details>

For a general nonlinear optimization problem, dual infeasibility says nothing about the primal problem. The primal problem can be optimal, unbounded or infeasible, when the dual is infeasible.

This is different from linear programming, where the dual infeasibility implies that the primal problem is either unbounded or infeasible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/inverse_kinematics_backend.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7675#-L3Z5iUpCuKvm_TvBC3U:-L3ZU3LdBd6Jf9Fp_zs0:b-gxztsp) ([raw file](https://github.com/robotlocomotion/drake/blob/72ef22a96b078296d102f34a3fbdbad4a3ca9b27/multibody/inverse_kinematics_backend.cc#L69)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

For a general nonlinear optimization problem, dual infeasibility says nothing about the primal problem. The primal problem can be optimal, unbounded or infeasible, when the dual is infeasible.

This is different from linear programming, where the dual infeasibility implies that the primal problem is either unbounded or infeasible.
</blockquote></details>

Fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7675)*

**Pull request merged**
