### PR TITLE
Add windows removal to CHANGELOG

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3688)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for both reviews, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3688#-:-KTL2cI2pb8cDfHlGh9n:btig81g)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3688#-KTL6SqRsUDDsNDsUtLp:-KTL6SqSXZABvnlt3SfK:b-7qfnzc) ([raw file](https://github.com/robotlocomotion/drake/blob/3aa6d88eb7884a27e371f302b6015470273e5da3/CHANGELOG.md#L146)):*
> ```Markdown
> [#3276]: https://github.com/RobotLocomotion/drake/issues/3276
> [#3566]: https://github.com/RobotLocomotion/drake/issues/3276
> [#3865]: https://github.com/RobotLocomotion/drake/issues/3865
> ```

This should be #3685.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3688)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3688#-KTL6SqRsUDDsNDsUtLp:-KTL7Bf_yACsfwnCoBPe:b-sr0vuv) ([raw file](https://github.com/robotlocomotion/drake/blob/3aa6d88eb7884a27e371f302b6015470273e5da3/CHANGELOG.md#L146)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This should be #3685.
</details>
Thanks!  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3688)*

**Comment by liangfok** [comment]
+@liangfok :lgtm_strong: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3688#-:-KTL7HxRlB9sShVs7yYU:bfb5efj)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3688)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3688#-:-KTLG-1zMoUYkZznhgme:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Don't need matlab.  Using override-merge for expediency.

**Pull request merged**
