### PR TITLE
cmake: Fix python3 search for CMake 3.10 (Ubuntu 18.04)

### LINKED ISSUE #14796: cmake build fails on commit b562211
When building on Ubuntu 18 with CMake, I get the following error:

(base) ryan@ryan-desktop:~/DR3/drake$ cmake -DCMAKE_BUILD_TYPE="Release" && make -j4
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Bazel: /usr/bin/bazel (found suitable version "4.0.0", minimum required is "3.0") 
CMake Error at CMakeLists.txt:229 (message):
  Could NOT find the python3 executable

-- Configuring incomplete, errors occurred!
See also "/home/ryan/DR3/drake/CMakeFiles/CMakeOutput.log".

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This was broken in #14605.

Closes #14796.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14798)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@seancurtis-tri for platform.

:LGTM:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14798#-:-MW67lGQC-G3t7OJ1a0v:b49azvp)* status: LGTM missing from assignee jamiesnape (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14798)* status: 1 unresolved discussion, LGTM missing from assignee jamiesnape (waiting on @jwnimmer-tri)

___
*[CMakeLists.txt, line 225 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14798#-MW67Nsf5QZjvmqrH0_Q:-MW67Nsf5QZjvmqrH0_R:bp85t9x) ([raw file](https://github.com/robotlocomotion/drake/blob/72f223ba0d93dadce9f0dbf7c92971e0fa123531/CMakeLists.txt#L225)):*
> ```CMake
>   find_program(PYTHON_EXECUTABLE NAMES "${FIND_PROGRAM_PYTHON3_NAMES}"
>     PATHS "${FIND_PROGRAM_PYTHON3_PATHS}"
>     NO_DEFAULT_PATH
> ```

What I intended was `NO_DEFAULT_PATH` to be removed. Somehow we ended up with some duplicate code in the two branches (obviously my fault).

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14798)* status: 1 unresolved discussion, LGTM missing from assignee jamiesnape (waiting on @jwnimmer-tri)

___
*[CMakeLists.txt, line 225 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14798#-MW67Nsf5QZjvmqrH0_Q:-MW68Js91eXBNz9j83NZ:bibgf9y) ([raw file](https://github.com/robotlocomotion/drake/blob/72f223ba0d93dadce9f0dbf7c92971e0fa123531/CMakeLists.txt#L225)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

What I intended was `NO_DEFAULT_PATH` to be removed. Somehow we ended up with some duplicate code in the two branches (obviously my fault).
</blockquote></details>

(semi-duplicated, I guess, the case is important, but maybe there is a better way to handle it)

**Review by jamiesnape — COMMENTED** [review]
So, it is unlikely Mac would be using an old version, but it would technically be broken too. My preference is just remove `NO_DEFAULT_PATH` below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14798#-:-MW68uzO07OLvKfDSpVd:bfr5gls)* status: 1 unresolved discussion, LGTM missing from assignee jamiesnape (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14798)* status: 1 unresolved discussion, LGTM missing from assignee jamiesnape (waiting on @jamiesnape and @SeanCurtis-TRI)

___
*[CMakeLists.txt, line 225 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14798#-MW67Nsf5QZjvmqrH0_Q:-MW6BHG38tdXQ6Y09qNx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/72f223ba0d93dadce9f0dbf7c92971e0fa123531/CMakeLists.txt#L225)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

(semi-duplicated, I guess, the case is important, but maybe there is a better way to handle it)
</blockquote></details>

Done.

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14798#-:-MW6BInW2Qs4hrQSvMjv:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),jamiesnape (waiting on @SeanCurtis-TRI)

**Pull request merged**
