### PR TITLE
Revert "Enable AutoDiff on various automotive planner/controller systems"

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Dear @jadecastro ,

The on-call build cop, @BetsyMcPhail, believes that your PR #7309  may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-elcapitan-clang-bazel-continuous-release/101/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7353)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
FYI, @jadecastro is working on a fix. He will open a PR soon.

**Comment by soonho-tri** [comment]
#7354 is created. @BetsyMcPhail , can we close this one?

**Comment by jadecastro** [comment]
And @BetsyMcPhail can I cancel the `mac-elcapitan-clang-bazel-continuous-release` CI job and start the same for #7354?

**Comment by BetsyMcPhail** [comment]
That sounds good to me @jadecastro. It's been cancelled.

**Comment by BetsyMcPhail** [comment]
Closing this PR in favor of https://github.com/RobotLocomotion/drake/pull/7354

**Pull request closed without merging**
