### PR TITLE
Fix -Werror-sign-compare in systems/plants

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix `-Werror-sign-compare` errors in `systems/plants`, and push the suppression down one more directory depth. Part of #2372.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2837)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri for feature review.

**Comment by rpoyner-tri** [comment]
/me whistles.

:lgtm: 

---

Reviewed 12 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2837#-:-KN3IjQKqKveHF4edAHo:271491717)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review.

---

Review status: 13 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2837#-:-KN3LPOiPFCpYAohBs6l:15284489)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 492 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2837#-KN3N9K_9va2O1Y-Vdzq:-KN3N9K_9va2O1Y-Vdzr:1004225016) ([raw file](https://github.com/robotlocomotion/drake/blob/e30f08a96d38c74fcbf60c55dfc56d91c6f9b10d/drake/systems/plants/RigidBodyTree.cpp#L492)):*
> ```cpp
>     const set<string>& active_element_groups, bool use_margins) {
>   vector<DrakeCollision::ElementId> ids_to_check;
>   for (const int& body_idx : bodies_idx) {
> ```

BTW, `&` seems superfluous

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2837#-:-KN3Nh8I38G2fFhsnFV6:1417088721)*

**Comment by jwnimmer-tri** [comment]
Review status: 13 of 16 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 492 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2837#-KN3N9K_9va2O1Y-Vdzq:-KN3P9uNp25iarnoYnMW:1728854942) ([raw file](https://github.com/robotlocomotion/drake/blob/e30f08a96d38c74fcbf60c55dfc56d91c6f9b10d/drake/systems/plants/RigidBodyTree.cpp#L492)):*
> const int&

I'd considered that.  What I was going for here was `const auto& foo` as the pattern, so if you have an int vector, your iteration is over int references.  Shrug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2837)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2837)*

**Pull request merged**
