### PR TITLE
Move examples/SimpleCar code and models into examples/Cars

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2241) &emsp; Multiple assignees:&emsp;@bmartin-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/bmartin-tri">bmartin-tri</a>,&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri PTAL.

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-:-KGmowUkSuyXuax83ty0:-213455146)*

**Comment by bmartin-tri** [comment]
+@bmartin-tri -@rpoyner-tri 
Taking over for rico

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-:-KGr0caMxcSjbwf6y03G:1903774963)*

**Comment by bmartin-tri** [comment]
Reviewed 31 of 35 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/steering_command_driver.py, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGr3QMPDWrGpnZ9nhiZ:-KGr3QMPDWrGpnZ9nhi_:964073333) ([raw file](https://github.com/robotlocomotion/drake/blob/1771cd5a53bdd18a75c9b417da0218f75d74d320/drake/examples/Cars/steering_command_driver.py#L1)):*
So, now we have steering_command_driver.py and SteeringCommandDriver.py in the same directory, with almost-but-not-quite the same content.  I don't think this makes it clear enough what the distinction between them is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241)*

**Comment by bmartin-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/Cars/steering_command_driver.py, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGr3QMPDWrGpnZ9nhiZ:-KGr6Zpuo8HV_l5Tn_lJ:902036021) ([raw file](https://github.com/robotlocomotion/drake/blob/1771cd5a53bdd18a75c9b417da0218f75d74d320/drake/examples/Cars/steering_command_driver.py#L1)):*
After offline discussion with jwnimmer, it seems this situation is only going to be temporary, and the TODO that was added to the older file is sufficient to describe this temporary state.  Resolving.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-:-KGr6xLyYjyQIUCifd5D:1417088721)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri Ready for platform review and merge.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-:-KGrJcqVU5_S8K2qLv6d:1431603223)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/Cars/SteeringCommandDriver.py, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGs8iVHMoICb2x4OKk0:-KGs8iVHMoICb2x4OKk1:-317172226) ([raw file](https://github.com/robotlocomotion/drake/blob/f30bccb1e7cd328b209bf60170a14488904561b1/drake/examples/Cars/SteeringCommandDriver.py#L1)):*
(nonblocking) Is "in lieu of" what you meant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-:-KGs9-_JQwNMs_ioky7-:1417088721)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-:-KGsSj1cZNchffd_xD_f:1417088721)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/examples/Cars/SteeringCommandDriver.py, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGs8iVHMoICb2x4OKk0:-KGsV_ygSFZy8z8oJ0wp:-2131199613) ([raw file](https://github.com/robotlocomotion/drake/blob/f30bccb1e7cd328b209bf60170a14488904561b1/drake/examples/Cars/SteeringCommandDriver.py#L1)):*
I think so?  I mean that StudlyDriver.py dies, and snake_driver.py lives.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241)*

**Comment by liangfok** [comment]
Reviewed 31 of 35 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/Cars/README.md, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGvhcNfcJ2gtCFj8oh6:-KGvhcNfcJ2gtCFj8oh7:1395619902) ([raw file](https://github.com/robotlocomotion/drake/blob/f30bccb1e7cd328b209bf60170a14488904561b1/drake/examples/Cars/README.md#L18)):*
FYI: I've completely revamped this README in PR https://github.com/RobotLocomotion/drake/pull/2253. I don't foresee a major conflict though.

---

*[drake/examples/Cars/README.md, line 61 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGvh6pizeaqRk9CveBl:-KGvh6pizeaqRk9CveBm:1105181949) ([raw file](https://github.com/robotlocomotion/drake/blob/f30bccb1e7cd328b209bf60170a14488904561b1/drake/examples/Cars/README.md#L61)):*
Have we verified that this works on Windows?

---

*[drake/examples/Cars/simple_car.cc, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGvi9UXh0wQx8mk3G_W:-KGvi9UXh0wQx8mk3G_X:1969988592) ([raw file](https://github.com/robotlocomotion/drake/blob/f30bccb1e7cd328b209bf60170a14488904561b1/drake/examples/Cars/simple_car.cc#L1)):*
Just curious: why not just define these constants in simple_car_demo.cc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/Cars/README.md, line 61 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGvh6pizeaqRk9CveBl:-KGwRPgTh07BaFuSuCr4:2121371096) ([raw file](https://github.com/robotlocomotion/drake/blob/f30bccb1e7cd328b209bf60170a14488904561b1/drake/examples/Cars/README.md#L61)):*
It's super unlikely that it works on Windows.

---

*[drake/examples/Cars/simple_car.cc, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGvi9UXh0wQx8mk3G_W:-KGwReCpOPT3dSFTEpwi:-1786881364) ([raw file](https://github.com/robotlocomotion/drake/blob/f30bccb1e7cd328b209bf60170a14488904561b1/drake/examples/Cars/simple_car.cc#L1)):*
I didn't write it, but my hypothesis is that so other code that uses `SimpleCar` can reuse the constants.  The demo program is unlikely to be the only user of this data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241)*

**Comment by jwnimmer-tri** [comment]
For the record: using override-merge to get around drake005 and out-of-date-with-master.

**Comment by liangfok** [comment]
*[drake/examples/Cars/README.md, line 61 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2241#-KGvh6pizeaqRk9CveBl:-KGwSEBIC_lfNQthLdY3:558595199) ([raw file](https://github.com/robotlocomotion/drake/blob/f30bccb1e7cd328b209bf60170a14488904561b1/drake/examples/Cars/README.md#L61)):*
If it doesn't work, we should add a quick note specifying which environments are supported. This might be a good opportunity to test the [cloud-based Windows instructions](https://sites.google.com/a/tri.global/internal/debugging-drake-on-windows-in-an-ec2-instance).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2241)*

**Pull request merged**
