### PR TITLE
Add notes in Buildcop doc on the buildcop retrospective, Slack channel, etc.

### PR DESCRIPTION
**Pull request by Lucy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4692)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@david-german-tri  for feature review.  Are you willing?
+@sammy-tri for platform review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-:-K_kqBKhw-iJ39gsf91y:bscfobg)*

**Comment by david-german-tri** [comment]
Thanks for doing this!  Here are a few comments.

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oWsCelR83uIXRWTlh:-K_oWsCelR83uIXRWTli:bhyjsvd) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L47)):*
> ```reStructuredText
> pass.
> 
> The build cop can use the `DrakeDevelopers' Slack channel
> ```

and other Drake contributors

---

*[drake/doc/buildcop.rst, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oX2ySVhV1a9CPuzvv:-K_oX2ySVhV1a9CPuzvw:b-uce620) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L47)):*
> ```reStructuredText
> pass.
> 
> The build cop can use the `DrakeDevelopers' Slack channel
> ```

BTW nit I don't think `DrakeDevelopers` has a trailing apostrophe (meta x2)

---

*[drake/doc/buildcop.rst, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oXojtvhi2c7K2Etg7:-K_oXojtvhi2c7K2Etg8:bgvueyc) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L156)):*
> ```reStructuredText
> own judgment.
> 
> The first step is to determine if an open Github Drake issue describes the
> ```

Consider moving this paragraph under "infrastructure flake"

---

*[drake/doc/buildcop.rst, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oXtQgXMCvVRkd1siS:-K_oXtQgXMCvVRkd1siT:b-7ll4zh) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L165)):*
> ```reStructuredText
> also describes current build issues. 
> 
> If no Drake issue is describing your break, the next step is to
> ```

Isn't this still the first step?  (Until you look at the broken build, how can you determine whether it matches an open GitHub issue?)

---

*[drake/doc/buildcop.rst, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oXLIZAyDXQf5JM1EB:-K_oXLI_dRVMTUce9P5S:bat4u40) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L234)):*
> ```reStructuredText
> @jamiesnape.
> 
> If you see "All nodes of label 'mac' are offline", this should disappear
> ```

This goes for any label (though it's most conspicuous with mac)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-:-K_oY58H6zFXnbmRnLoF:b-3c9fbs)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4692)*

**Comment by sammy-tri** [comment]
:lgtm: pending open items.  Thanks!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-:-K_ozInPjekzrk0z86Y5:bfmi1f0)*

**Comment by Lucy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oWsCelR83uIXRWTlh:-K_pAO6Q6HxXLMnZILqI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L47)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

and other Drake contributors
</blockquote></details>

Done.

---

*[drake/doc/buildcop.rst, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oX2ySVhV1a9CPuzvv:-K_pKvI_f8KeDkgHBiKP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L47)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW nit I don't think `DrakeDevelopers` has a trailing apostrophe (meta x2)
</blockquote></details>

Done.

---

*[drake/doc/buildcop.rst, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oXojtvhi2c7K2Etg7:-K_pCiZCR7g_qGo5mHzn:b-yej0f1) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L156)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Consider moving this paragraph under "infrastructure flake"
</blockquote></details>

I don't believe that its only infrastructure that flakes: it can also be flaky tests, or issues that are not fixed yet. So I want to leave the note here.

---

*[drake/doc/buildcop.rst, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oXtQgXMCvVRkd1siS:-K_pL3dGIXUCKddVRnzR:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L165)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Isn't this still the first step?  (Until you look at the broken build, how can you determine whether it matches an open GitHub issue?)
</blockquote></details>

Done. 

---

*[drake/doc/buildcop.rst, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_oXLIZAyDXQf5JM1EB:-K_pL6ITJxBQ4F2Jwoz1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b2e85c84ab1db86163091de81cf6d6c2cb1b866e/drake/doc/buildcop.rst#L234)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This goes for any label (though it's most conspicuous with mac)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4692)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-:-K_pM-DI06qndoO4bSlQ:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4692)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/doc/buildcop.rst, line 162 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_pPjHObyl4KfOdTIFq:-K_pPjHP79-tuYhPxWgQ:b-8il2xo) ([raw file](https://github.com/robotlocomotion/drake/blob/62174df15b1a4d53de903c56a927eb6bf0b52154/drake/doc/buildcop.rst#L162)):*
> ```reStructuredText
> in that particular run.
> 
> Determine if an open Github Drake issue describes the
> ```

BTW: nit: odd newline.

---

*[drake/doc/buildcop.rst, line 169 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_pPf_W41DUwepEdmiT:-K_pPf_W41DUwepEdmiU:b-gsnknp) ([raw file](https://github.com/robotlocomotion/drake/blob/62174df15b1a4d53de903c56a927eb6bf0b52154/drake/doc/buildcop.rst#L169)):*
> ```reStructuredText
> retrospective
> <https://docs.google.com/document/d/120AOAaamIMO-SM1UaJ6vfzpA15LnXHexDF4a7MLAS3o/edit#heading=h.sxk1djc2v0yg>`_
> also describes current build issues. 
> ```

BTW: nit: extraneous trailing space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4692)*

**Comment by Lucy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 162 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_pPjHObyl4KfOdTIFq:-K_pTEuC6exiMiOwllKa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/62174df15b1a4d53de903c56a927eb6bf0b52154/drake/doc/buildcop.rst#L162)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: odd newline.
</blockquote></details>

Done.

---

*[drake/doc/buildcop.rst, line 169 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4692#-K_pPf_W41DUwepEdmiT:-K_pTGOxGR1_7EAAWbCl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/62174df15b1a4d53de903c56a927eb6bf0b52154/drake/doc/buildcop.rst#L169)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: extraneous trailing space.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4692)*

**Pull request merged**
