### PR TITLE
"Fix" install RPATH for MOSEK

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify how we adjust RPATHs in installed libraries to rewrite two types of paths:

- Paths starting with `@loader_path`.
- Paths into Bazel's private build ares (`/private/var/tmp/_bazel_$USER`).

Previously, we only rewrote the former. However, for reasons which are unclear, MOSEK gets linked using the latter, which was resulting in the installed library containing a reference to the absolute path of MOSEK as found in the build tree (which is clearly not useful).

+@jwnimmer-tri for feature review, please. I suspect there won't be much to see from CI here, so I'm not sure what's the best way to go about testing this, other than locally. (I've already verified on KW's macbook that this produces `@loader_path/libmosek64.dylib` in the installed `libdrake.so`.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16985)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@svenevs -@jwnimmer-tri for feature review.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging please.

Running this job while doing local testing.

**Comment by svenevs** [comment]
I'm not sure what to make of this.  On our macbook I tested this branch as well as `master`.  For this branch:

```console
$ bazel run --config mosek //:install -- /tmp/drake_mosek
$ find /tmp/drake_mosek -type f -name "*.so" -exec otool -L {} \; | grep -i '.*mosek.*' | grep -v /tmp/drake_mosek | sort | uniq
	@loader_path/../../../../libmosek64.dylib (compatibility version 0.0.0, current version 9.2.33)
	@loader_path/../../../libmosek64.dylib (compatibility version 0.0.0, current version 9.2.33)
	@loader_path/libmosek64.dylib (compatibility version 0.0.0, current version 9.2.33)
	@rpath/mosek.cpython-39-darwin.so (compatibility version 0.0.0, current version 0.0.0)
```

Looks good.  From  `master`:

```console
$ bazel run --config mosek //:install -- /tmp/drake_mosek_master
$ find /tmp/drake_mosek_master -type f -name "*.so" -exec otool -L {} \; | grep -i '.*mosek.*' | grep -v /tmp/drake_mosek_master | sort | uniq
	/private/var/tmp/_bazel_sven.mcdowell/d000d204d2acabbeff06f3358e48000a/external/mosek/tools/platform/osx64x86/bin/libmosek64.dylib (compatibility version 0.0.0, current version 9.2.33)
	@rpath/mosek.cpython-39-darwin.so (compatibility version 0.0.0, current version 0.0.0)
```

Looks bad, AKA locally the PR seems to fix the rpath issues pointing to obscure locations rather than the `mosek` in  the install tree.

**However**, from the [mac mosek packaging job](https://drake-jenkins.csail.mit.edu/job/mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging/1/console) run on this PR:

```console
$ mkdir test && cd test
$ wget https://drake-packages.csail.mit.edu/drake/experimental/drake-20220418151244-66c5c884189559a13fbe2c340d89bfcab5169436-mac.tar.gz
$ tar -xf drake-20220418151244-66c5c884189559a13fbe2c340d89bfcab5169436-mac.tar.gz
$ find ./drake -type f -name "*.so" -exec otool -L {} \; | grep -i '.*mosek.*' | sort | uniq
	/Users/bigsur/workspace/mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging/_bazel_bigsur/763af06ee4f5779621a7fa3ee02e9aea/external/mosek/tools/platform/osx64x86/bin/libmosek64.dylib (compatibility version 0.0.0, current version 9.2.33)
	@rpath/mosek.cpython-39-darwin.so (compatibility version 0.0.0, current version 0.0.0)
./drake/lib/python3.9/site-packages/pydrake/solvers/mosek.cpython-39-darwin.so:
```

So locally it seems fixed, but there's something special about the CI packaging that is not working and the tarball from there still seems broken?

**Comment by jwnimmer-tri** [comment]
Oh, I just looked at the PR diffs now.  The bazel path `/private/var/tmp/_bazel` is under user-preference control.  I assume CI is setting it to something else.

https://bazel.build/docs/output_directories#layout-diagram

**Comment by mwoehlke-kitware** [comment]
Yup. I changed the check from `startswith("/private/var/tmp/_bazel")` to `contains("/_bazel_")`. I'm hesitant to simply transform *all* link paths...

**Comment by mwoehlke-kitware** [comment]
However, looking at the CI, it looks like even that is coincidence that it still works. I'd rather not literally make `"mosek"` the exception, but there are limited options how else to tell that the MOSEK path needs to be rewritten but these don't:
```
@rpath/libdrake_marker.so
/usr/lib/libc++.1.dylib
/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
/usr/lib/libobjc.A.dylib
/usr/lib/libSystem.B.dylib
```

Maybe the check should instead exclude system library locations?

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging please.

**Review by svenevs — COMMENTED** [review]
I will try and check in on [the mac packaging build](https://drake-jenkins.csail.mit.edu/job/mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging/2/console) later after it finishes, but this may not get resolved before the nightlies.  If it works should I make it "single-reviewer-ok" and merge it?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16985#-:-N-yPPnL7rBot4CEg51W:ba8bjzj)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware and @svenevs)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16985#-N-yOZ2j6lCmw-C7ceFw):*
- Spell: `ares` => `areas`
- Make this ``(e.g., `/private/var/tmp/_bazel_$USER`)`` adding `e.g.,` at the beginning since we're checking `contains` now as this is not necessarily the exact location.
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16985#-N-yP2yBBq4w_g5QagYC):*
Since we're force pushing the former approach, it probably is best to just condense this to:

```
For unknown reasons, MOSEK gets linked using the latter (private build area) approach.
This patch applies a band-aid to work around this until a proper solution is found.
```

or something.

**Review by svenevs — COMMENTED** [review]
The latest [mac packaging CI](https://drake-jenkins.csail.mit.edu/job/mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging/2/console) build artifact succeeds:

```console
$ mkdir test && cd test
$ wget https://drake-packages.csail.mit.edu/drake/experimental/drake-20220418175837-3fd392ebb1cac61299e72b84d4ec2c09fa17ba35-mac.tar.gz
$ tar -xf drake-20220418175837-3fd392ebb1cac61299e72b84d4ec2c09fa17ba35-mac.tar.gz
$ find ./drake -type f -name "*.so" -exec otool -L {} \; | grep -i '.*mosek.*' | sort | uniq
	@loader_path/../../../../libmosek64.dylib (compatibility version 0.0.0, current version 9.2.33)
	@loader_path/../../../libmosek64.dylib (compatibility version 0.0.0, current version 9.2.33)
	@loader_path/libmosek64.dylib (compatibility version 0.0.0, current version 9.2.33)
	@rpath/mosek.cpython-39-darwin.so (compatibility version 0.0.0, current version 0.0.0)
./drake/lib/python3.9/site-packages/pydrake/solvers/mosek.cpython-39-darwin.so:
```

I'm going to say that this :lgtm: and request +@sherm1 (pacific) for platform review please.  When squashing it may be a good idea to reword the commit message a bit, but I believe getting this in before nightlies so that [drake-external-examples starts to pass again](https://drakedevelopers.slack.com/archives/C270MN28G/p1650121636680049) (which installs https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-mac.tar.gz) is probably a good idea.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16985#-:-N-ymcko1AKCEZ2ARnCj:bmdlosv)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Punting to +@rpoyner-tri for platform review
-@sherm1

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16985#-:-N0-Eypi9mPdnYAz1h9y:bc3889c)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by mwoehlke-kitware** [comment]
If y'all had waited five minutes, I could have just updated this with the change that is now #16991 instead... which seems to be a correct fix, rather than this ugly hack.

**Comment by rpoyner-tri** [comment]
You can always put a blocking comment on your own PR if you know something that the reviewer doesn't.

**Pull request merged**
