### PR TITLE
Improve documentation for spatial forces.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18174)

### CODE REVIEW

**Comment by mitiguy** [comment]
This PR is meant to address confusing notation for spatial forces.  It would for @RussTedrake to comment on whether he sees this as an improvement on the current documentation that shows a backslash in a top-right superscript, e.g., as shown [here](https://drake.mit.edu/doxygen_cxx/group__multibody__spatial__vectors.html)

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18174#-:-NFFs1tv8FUmFqW_bWr3:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Nice, thanks.
+(status: single reviewer ok) 
:lgtm: x 2

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18174#-:-NFGGPhtEzsAoDRWLxJt:bu9dei)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
cc @russtedrake 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18174#-:-NFGGVcm1EcIG2mTQtDD:b-dzguok)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @mitiguy)

**Pull request merged**
