### PR TITLE
addes comments for SignalLogger

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6044)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@hongkai-dai for feature review. this is addressing https://github.com/RobotLocomotion/drake/issues/5940#event-1070910488

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6044#-:-KjOi8no5-QUJmVZtUkN:b-ytv0zu)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6044)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sherm1 for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6044#-:-KjOshxYTojGb42iUufh:bozh2sc)*

**Comment by sherm1** [comment]
Yay! Thanks for the extra comments, @hongkai-dai. One minor BTW below, then :lgtm:.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/signal_logger.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6044#-KjOvOuttH-fDoSWdFW1:-KjOvOuttH-fDoSWdFW2:b-cjgdtl) ([raw file](https://github.com/robotlocomotion/drake/blob/b126002342ece45ca69509f46c30a7732fd03830/drake/systems/primitives/signal_logger.h#L19)):*
> ```objc
> /// This class essentially holds a large Eigen matrix for data storage, where
> /// each column corresponds to a data point. This system saves a data point and
> /// the context time whenever it's Publish() method is called.
> ```

BTW "it's" means "it is". So "its" (possessive) here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6044#-:-KjOvppu8M7ZgONhSA8a:b6lzliu)*

**Comment by siyuanfeng-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/signal_logger.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6044#-KjOvOuttH-fDoSWdFW1:-KjP-UIc2dsT4raP86zH:b-5bquje) ([raw file](https://github.com/robotlocomotion/drake/blob/b126002342ece45ca69509f46c30a7732fd03830/drake/systems/primitives/signal_logger.h#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW "it's" means "it is". So "its" (possessive) here.
</blockquote></details>

opps. was typing during a meeting. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6044)*

**Comment by sherm1** [comment]
Oh, I had misinterpreted this as being from Hongkai -- thank *you* for the extra comments, @siyuanfeng-tri!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6044#-:-KjPAtmjXXvwzWEyn3gX:bytmcrm)*

**Pull request merged**
