### PR TITLE
Correct badly formatted XML

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Resolves #8269 

This corrects the XML. The XML has been validated via https://www.xmlvalidation.com/ as a preliminary test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8270)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri for mac testing.

**Comment by SeanCurtis-TRI** [comment]
@soonho-tri Thanks.  :)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8270#-:-L6wuQ1B5L0gH3hHEH9m:b-nsljm9)*

**Comment by soonho-tri** [comment]
:lgtm: as `bazel test  //multibody/collision:collision_filter_group_test -c dbg --config=everything` passed.

**Comment by SeanCurtis-TRI** [comment]
Huzzah!

Shall we count that as feature and platform review?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8270#-:-L6wuZipz3kUGujLgvTZ:b-gvejw7)*

**Comment by soonho-tri** [comment]
BTW, it'd be nice if we have tests validating XMLs.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8270#-:-L6wucIn20zay4pH0bnW:b88610j)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8270#-:-L6wunWx2UYYoFm-ZDgT:bnuwbvt)*

**Comment by soonho-tri** [comment]
> Shall we count that as feature and platform review?

Positive.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8270#-:-L6wunJx6pheCfXcfEjh:b9udu2z)*

**Comment by SeanCurtis-TRI** [comment]
Groovy. When CI is done, we'll merge it.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8270#-:-L6wurnnW5eC1YfsPNQr:bc4o069)*

**Pull request merged**
