### PR TITLE
Polished some documentation in RigidBodyTree.

### PR DESCRIPTION
**Pull request by liangfok**
For increased readability and understanding.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4898)

### CODE REVIEW

**Comment by liangfok** [comment]
+@seancurtis-tri for feature review since I believe I touched some of your code.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4898#-:-KbIMlQkBMgn5iET3Nj3:b-1dc635)*

**Comment by SeanCurtis-TRI** [comment]
Other than a couple of passing whims :LGTM:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.h, line 848 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4898#-KbLMEETyK1bPEX5BHv2:-KbLMEETyK1bPEX5BHv3:bo92hu0) ([raw file](https://github.com/robotlocomotion/drake/blob/571ca957269d204b70fcb3d5c24e2eb723bfc737/drake/multibody/rigid_body_tree.h#L848)):*
> ```objc
>       const std::string& group_name);
> 
>   /// Retrieve a (`const`) pointer to an element of the collision model.
> ```

BTW Why parentheses?  I know it was in the previous version, but as long as this is about improving documentation, it seems they can be tossed.

---

*[drake/multibody/rigid_body_tree.h, line 915 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4898#-KbLMVWof6s0NNWQsCdS:-KbLMVWof6s0NNWQsCdT:bmcumqu) ([raw file](https://github.com/robotlocomotion/drake/blob/571ca957269d204b70fcb3d5c24e2eb723bfc737/drake/multibody/rigid_body_tree.h#L915)):*
> ```objc
> 
>   /**
>    * Computes the (signed) distance from the given points to the nearest
> ```

BTW Similar note on these parentheses.  It doesn't seem they provide value.  In fact, I'd even advocate for *signed* over (signed).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4898#-:-KbLN4PzzdkYavwFFMZj:b-ut890x)*

**Comment by liangfok** [comment]
Thanks. +@sammy-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.h, line 848 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4898#-KbLMEETyK1bPEX5BHv2:-KbLWk_vfau39gSa0Jj1:b-ho5wpv) ([raw file](https://github.com/robotlocomotion/drake/blob/571ca957269d204b70fcb3d5c24e2eb723bfc737/drake/multibody/rigid_body_tree.h#L848)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Why parentheses?  I know it was in the previous version, but as long as this is about improving documentation, it seems they can be tossed.
</blockquote></details>

Agreed. Done.

---

*[drake/multibody/rigid_body_tree.h, line 915 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4898#-KbLMVWof6s0NNWQsCdS:-KbLX-bQWBN4Cmq_rhu7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/571ca957269d204b70fcb3d5c24e2eb723bfc737/drake/multibody/rigid_body_tree.h#L915)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Similar note on these parentheses.  It doesn't seem they provide value.  In fact, I'd even advocate for *signed* over (signed).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4898#-:-KbLXVbwnIivqX6RH9-b:b7jqb5y)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4898#-:-KbM-5FUs44ImW05QM3S:bnfp4nl)*

**Pull request merged**
