### PR TITLE
Added sub-header links.

### PR DESCRIPTION
**Pull request by liangfok**
This is in response to https://github.com/RobotLocomotion/drake/pull/2371#issuecomment-220197015.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2396) &emsp; Multiple assignees:&emsp;@amcastro-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/amcastro-tri">amcastro-tri</a>,&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by liangfok** [comment]
May I suggest:

+@david-german-tri for feature review
+@jwnimmer-tri for platform review (it's a Wednesday)

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Added C\+\+ &quot;dut&quot; recommendation and sub\-header links\.
> 
> This is in response to https://github.com/RobotLocomotion/drake/pull/2371#issuecomment-220197015.
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-:-KI5WqLXs0agnzk5z88H:1454495501)*

**Comment by jwnimmer-tri** [comment]
Well, I am certainly happy to LGTM this text, but since it's my meme I feel like at least two other unbiased people should actually sign off on it.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> May I suggest:
> 
> +@david-german-tri for feature review
> +@jwnimmer-tri for platform review (it's a Wednesday)
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-:-KI5YnJDG9xSdJL5Wg0I:2064394149)*

**Comment by liangfok** [comment]
OK may I suggest:

+@amcastro-tri and +@sherm1 

?

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Well, I am certainly happy to LGTM this text, but since it's my meme I feel like at least two other unbiased people should actually sign off on it.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-:-KI5_VXGxmLOuXzvXxMP:625172513)*

**Comment by jwnimmer-tri** [comment]
For reference, sample code at [trajectory_car_test.cc#L65](https://github.com/RobotLocomotion/drake/blob/4ec321bf323af43ab65d30a6ed687bcd19ad2713/drake/examples/Cars/test/trajectory_car_test.cc#L65).

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/doc/code_style_guide.rst, line 98 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-KI61QkV1etSrkfTznPF:-KI61QkV1etSrkfTznPG:1039294206) ([raw file](https://github.com/robotlocomotion/drake/blob/45de8c5281e789a4afebf00a26cd3f32b6d286dc/drake/doc/code_style_guide.rst#L98)):*
> ```reStructuredText
>   can be tested.
> 
> .. _code-style-guide-matlab:
> ```

+1 for the extra links.

Regarding `dut`, I like the idea of singling out the object being tested but I don't think we should advocate this particular name. I think it would have been clearer to call this object `car_under_test` or some such. However the `dut` abbreviation is standard in some circles, and is kind of cute so I think it's fine but out of courtesy to the naive it should be introduced with a comment like `// dut = device under test`. I don't see why we would need to skimp on the comment or attempt to train people on the acronym.

I would prefer a recommendation something like
> When writing unit tests that involve a lot of helper code, be sure to distinguish what *is* being tested from what *is not* being tested. In electronic manufacturing this is called the *device under test*, abbreviated *dut*. You may find that concept and abbreviation useful in your tests, and for understanding existing tests that use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2396)*

**Comment by amcastro-tri** [comment]
Thank you for improving our documentation @liangfok! my 0.5 cents on this

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> For reference, sample code at [trajectory_car_test.cc#L65](https://github.com/RobotLocomotion/drake/blob/4ec321bf323af43ab65d30a6ed687bcd19ad2713/drake/examples/Cars/test/trajectory_car_test.cc#L65).
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/doc/code_style_guide.rst, line 98 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-KI61QkV1etSrkfTznPF:-KI8FuBwZx1NFwvvy0bT:1631734635) ([raw file](https://github.com/robotlocomotion/drake/blob/45de8c5281e789a4afebf00a26cd3f32b6d286dc/drake/doc/code_style_guide.rst#L98)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> +1 for the extra links.
> 
> Regarding `dut`, I like the idea of singling out the object being tested but I don't think we should advocate this particular name. I think it would have been clearer to call this object `car_under_test` or some such. However the `dut` abbreviation is standard in some circles, and is kind of cute so I think it's fine but out of courtesy to the naive it should be introduced with a comment like `// dut = device under test`. I don't see why we would need to skimp on the comment or attempt to train people on the acronym.
> 
> I would prefer a recommendation something like
> > When writing unit tests that involve a lot of helper code, be sure to distinguish what *is* being tested from what *is not* being tested. In electronic manufacturing this is called the *device under test*, abbreviated *dut*. You may find that concept and abbreviation useful in your tests, and for understanding existing tests that use it.
</details>
I agree with @sherm1 here. To me something like `car_under_test` is a more natural choice. Especially if you are reading this test for the first time seeing a simple `dut` may take some brain power (for limited brain power programmers like me) until you understand that what you are actually testing is a car (or robot or collision model...). Probably we can recommend calling distinguish what you are testing just as in this example? like, `[whatever is under test]_under_test`?

And another question here? could I have more than one `dut` per unit test? (especially with lots of helper code) or should I just write two unit tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-:-KI8GnV7Vwf1Xh33fPTh:1885674905)*

**Comment by david-german-tri** [comment]
I think we all agree that using the `dut` notation is not a defect, and using some other notation (such as the ones proposed by @amcastro-tri and @sherm1) is also not a defect.  So, the only question here is whether `dut` is useful enough to justify the time that will be spent writing, maintaining, and reading the recommendation.  In my opinion, the answer to that is no.  I'm particularly concerned that low-impact recommendations like this one will obscure more important stuff in `code_style_guide.rst`.  Walls of text are hard to read!

**Comment by jwnimmer-tri** [comment]
FWIW, I also support minimalism in rules documentation, and avoiding walls of text.

**Comment by liangfok** [comment]
I think "walls of text" can be easily avoided by splitting it into sections / subsections / separate pages. I'll go ahead and update this PR to be more general and not so restrictive to the `dut` meme.

**Comment by jwnimmer-tri** [comment]
How about I back down from using an uncommented `dut` in my unit tests, and we can close this PR?  (This is essentially sherm1's suggestion.)

**Comment by liangfok** [comment]
OK sounds good.

**Comment by liangfok** [comment]
I updated this PR to just include the header / sub-header links. PTAL.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> OK sounds good.
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 98 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-KI61QkV1etSrkfTznPF:-KI8YAydyZieHBU6MK4v:-170220898) ([raw file](https://github.com/robotlocomotion/drake/blob/45de8c5281e789a4afebf00a26cd3f32b6d286dc/drake/doc/code_style_guide.rst#L98)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I agree with @sherm1 here. To me something like `car_under_test` is a more natural choice. Especially if you are reading this test for the first time seeing a simple `dut` may take some brain power (for limited brain power programmers like me) until you understand that what you are actually testing is a car (or robot or collision model...). Probably we can recommend calling distinguish what you are testing just as in this example? like, `[whatever is under test]_under_test`?
> 
> And another question here? could I have more than one `dut` per unit test? (especially with lots of helper code) or should I just write two unit tests?
</details>
I think by definition a "unit test" should only have one `dut`. Otherwise, it would be called "units test" :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-:-KI8Y3wfsi7CAys5NUho:-1161631255)*

**Comment by liangfok** [comment]
Huh. I think Reviewable is mixing up PRs again. The `core/CMakeLists.txt` is showing up for some reason. That was already merged from this PR: https://github.com/RobotLocomotion/drake/pull/2400

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I updated this PR to just include the header / sub-header links. PTAL.
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-:-KI8YN730-zPZ_OwNiGh:512655871)*

**Comment by jwnimmer-tri** [comment]
Weird.  I never have those problems (though I guess I always rebase instead of merge, so likely to have different failure modes).

:lgtm: 

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Huh. I think Reviewable is mixing up PRs again. The `core/CMakeLists.txt` is showing up for some reason. That was already merged from this PR: https://github.com/RobotLocomotion/drake/pull/2400
</details>


---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-:-KI8a3dkohzztX9guvF9:-1071120487)*

**Comment by liangfok** [comment]
I always merge instead of rebase because it's less destructive and thus more safe. Maybe I'll switch to rebasing to avoid this particular Reviewable failure mode.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Weird.  I never have those problems (though I guess I always rebase instead of merge, so likely to have different failure modes).
> 
> :lgtm: 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2396#-:-KI8aYtLEprBzh0-Q9MQ:-752909637)*

**Comment by liangfok** [comment]
I believe this PR is ready to be merged since all checks have passed.

**Comment by jwnimmer-tri** [comment]
Using override-merge due to out-of-date-with-master.

**Pull request merged**
