### PR TITLE
retrieve linear constraint dual from Mosek result.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As a step towards #13285

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14348)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@avalenzu for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14348#-:-MMK4ZN44TaMQyuRMYkR:b-uss1yj)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
Review pass done. One question and some nits.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14348#-:-MMM4KSY4N83KboekD4H:b958vwx)* status: 3 unresolved discussions, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/test/ipopt_solver_test.cc, line 159 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMM3Aqm6sllmDH3xkol:-MMM3Aqm6sllmDH3xkom:bn89n6c) ([raw file](https://github.com/robotlocomotion/drake/blob/51d474cbcfae307ab0d7c49630becc1ebcb4fdbe/solvers/test/ipopt_solver_test.cc#L159)):*
> ```cpp
>   IpoptSolver solver;
>   TestQPDualSolution1(solver, {}, 1e-5);
> }
> ```

nit: Could you make this `{} /* solver_options */,`? That way the reader doesn't have to go looking for what that second input argument is.
___
*[solvers/test/mosek_solver_test.cc, line 433 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMM3ffZ1qUoyXAPcX19:-MMM3ffZ1qUoyXAPcX1A:b86mapm) ([raw file](https://github.com/robotlocomotion/drake/blob/51d474cbcfae307ab0d7c49630becc1ebcb4fdbe/solvers/test/mosek_solver_test.cc#L433)):*
> ```cpp
>     // dual solution is in the order of 1E-4, that is too large.
>     solver_options.SetOption(solver.id(), "MSK_DPAR_INTPNT_QO_TOL_REL_GAP",
>                              1e-12);
> ```

Should we set this by default? Or reference it in the documentation for `MosekSolver`?
___
*[solvers/test/snopt_solver_test.cc, line 460 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMM4FUS1RgI4YnIhbFv:-MMM4FUT4-xe1sjckTMA:b-7nsssh) ([raw file](https://github.com/robotlocomotion/drake/blob/51d474cbcfae307ab0d7c49630becc1ebcb4fdbe/solvers/test/snopt_solver_test.cc#L460)):*
> ```cpp
> GTEST_TEST(SnoptSolverTest, QPDualSolution1) {
>   SnoptSolver solver;
>   TestQPDualSolution1(solver, {}, 1e-5);
> ```

nit: Same request here as for `ipopt_solver_test`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14348)* status: 1 unresolved discussion, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

___
*[solvers/test/ipopt_solver_test.cc, line 159 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMM3Aqm6sllmDH3xkol:-MMM7V3e7Nmp4N_cmPyN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/51d474cbcfae307ab0d7c49630becc1ebcb4fdbe/solvers/test/ipopt_solver_test.cc#L159)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Could you make this `{} /* solver_options */,`? That way the reader doesn't have to go looking for what that second input argument is.
</blockquote></details>

Done.
___
*[solvers/test/mosek_solver_test.cc, line 433 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMM3ffZ1qUoyXAPcX19:-MMM7Yir--EZZS_NZhyA:b-qrvqi) ([raw file](https://github.com/robotlocomotion/drake/blob/51d474cbcfae307ab0d7c49630becc1ebcb4fdbe/solvers/test/mosek_solver_test.cc#L433)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Should we set this by default? Or reference it in the documentation for `MosekSolver`?
</blockquote></details>

No we don't need to set it by default. In this particular case, one of the optimal solution is 0, so a 1E-8 tolerance on the squared norm `x*x` means 1E-4 error on the solution `x`. When the optimal solution is not 0, say `1`, then 1e-8 error on the cost means about 1e-8 error on the solution (since 1 + 1e-8 = (1 + eps)^2 = 1 + 2 * eps means eps is about 1e-8).

I added some documentation to make it more clear.
___
*[solvers/test/snopt_solver_test.cc, line 460 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMM4FUS1RgI4YnIhbFv:-MMM8K8uAbyDs2D4yXu7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/51d474cbcfae307ab0d7c49630becc1ebcb4fdbe/solvers/test/snopt_solver_test.cc#L460)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Same request here as for `ipopt_solver_test`.
</blockquote></details>

Done.

**Review by avalenzu — COMMENTED** [review]
:lgtm: +@rpoyner-tri for platform review.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14348#-:-MMMOFvQ7ZVqhrhCLJvL:bcpyunn)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[solvers/test/mosek_solver_test.cc, line 433 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMM3ffZ1qUoyXAPcX19:-MMMO9kR9ikv0-9WXSi1:b-jhyyta) ([raw file](https://github.com/robotlocomotion/drake/blob/51d474cbcfae307ab0d7c49630becc1ebcb4fdbe/solvers/test/mosek_solver_test.cc#L433)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

No we don't need to set it by default. In this particular case, one of the optimal solution is 0, so a 1E-8 tolerance on the squared norm `x*x` means 1E-4 error on the solution `x`. When the optimal solution is not 0, say `1`, then 1e-8 error on the cost means about 1e-8 error on the solution (since 1 + 1e-8 = (1 + eps)^2 = 1 + 2 * eps means eps is about 1e-8).

I added some documentation to make it more clear.
</blockquote></details>

Got it. Thanks!

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14348#-:-MMMum7R4YfkzoxkqvNV:bnfp4nl)* status: 1 unresolved discussion (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMMuMD1E_bTa9Njmdw_:-MMMuMD1E_bTa9Njmdwa:b7669k8) (no related file):*
Do we have any new numerical limit hazards here vs. mac builds? I tried it on `macsim` and it seemed fine, but would like your opinion, given the history of day-after adjustments to tests.

---

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14348)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMMuMD1E_bTa9Njmdw_:-MMO1zEt42xqSPkzhX6D:b-tnfz3y) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Do we have any new numerical limit hazards here vs. mac builds? I tried it on `macsim` and it seemed fine, but would like your opinion, given the history of day-after adjustments to tests.
</blockquote></details>

Thanks for testing it on macsim. I don't know if it works fine on mac CI. Mosek solver is known to behave differently on Mac versus Ubuntu. So we might need to change the numerical tolerance later if nightly build fails.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14348)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),avalenzu

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14348#-MMMuMD1E_bTa9Njmdw_:-MMRBl2gBRZv0S2nxVI7:b-pvarfm) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks for testing it on macsim. I don't know if it works fine on mac CI. Mosek solver is known to behave differently on Mac versus Ubuntu. So we might need to change the numerical tolerance later if nightly build fails.
</blockquote></details>

Well, I guess let's go find out :) .

---

**Pull request merged**
