### PR TITLE
[systems/framework] LeafSystem::DeclareVector*Port(name, size, ...)

### LINKED ISSUE #10751: offer LeafSystem::DeclareVectorInput(name, size, random_type)
We have `System::DeclareInputPort(name, PortDataType::kVectorValued, int)` and `LeafSystem::DeclareVectorInput(name, BasicVector(size), random_type)`.  In both cases, the unfortunate user has to understand something about the systems framework that they should not absolutely need (`PortDataType` or `BasicVector`).  It would be trivial to offer the default `BasicVector` option, and I think it would be popular!  (in my python code, it would mean that the file doesn't need to import `PortDataType` nor `BasicVector` at the top, which always confuses people.)

Ditto for output ports.

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #10751.  I've separated the PR into two commits (the new methods, then updating all of the uses).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538#-:-MfyWjLX0MWQ_gVBEBLx:b7dve2f)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Checkpoint.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538#-:-Mg7Euj_3Usj24aHV4it:by96gdd)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @RussTedrake and @sherm1)

___
*[systems/framework/leaf_system.h, line 1372 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-Mg7DsPD8iIuy0U_9k6v:-Mg7DsPD8iIuy0U_9k6w:b6nkypq) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.h#L1372)):*
> ```objc
> 
>   /** Declares a vector-valued output port with type BasicVector and size @p
>   size.  @p calc is a calculator function that is a class member function
> ```

minor: since there is no model_value here, the documentation should say how the BasicVector is initialized or explicitly say it is undefined. However, I believe it is guaranteed to be NaN-initialized in this case. (Same for other output port methods.)

**Review by sherm1 — COMMENTED** [review]
Gets rid of a lot of unnecessary fluff! Feature :lgtm:
+@ggould-tri for platform review if possible, otherwise punt to +@soonho-tri since I am Tuesday's.

> Reviewed 71 of 71 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538#-:-Mg7YWPY3TdB2HnaQrjP:b-r1dop9)* status: 2 unresolved discussions, LGTM missing from assignees ggould-tri(platform),soonho-tri(platform) (waiting on @ggould-tri, @RussTedrake, and @soonho-tri)

___
*[tutorials/dynamical_systems.ipynb, line 387 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15538#-Mg7YQyd4wbBBT4u1UuP:-Mg7YQyd4wbBBT4u1UuQ:b-jaxhl2) ([raw file](https://github.com/robotlocomotion/drake/blob/70624f363483928c6f0b8e355a672fa2cb6b1fdd/tutorials/dynamical_systems.ipynb#L387)):*
> ```
>  "nbformat": 4,
>  "nbformat_minor": 2
> }
> ```

BTW no newline at EOF

**Review by ggould-tri — COMMENTED** [review]
I don't seem to be likely to get through this in the next few minutes, so I'm handing it over as requested.  -@ggould-tri +@soonho-tri .

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538#-:-Mg7c1rY2GIv23ug1mN_:bltnel5)* status: 2 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @RussTedrake and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
Checkpoint, reviewed the first commit.

FYI, there is a merge conflict to resolve.

> Reviewed 4 of 5 files at r1, 1 of 71 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538#-:-MgDdW8k-rgNtzseUNWF:b-nzswdc)* status: 6 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @RussTedrake)

___
*[systems/framework/leaf_system.h, line 1387 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-MgDX6Ev31QJCBNz9c5s:-MgDX6Ev31QJCBNz9c5t:b2lsw8c) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.h#L1387)):*
> ```objc
>       std::set<DependencyTicket> prerequisites_of_calc = {
>           all_sources_ticket()}) {
>     return DeclareVectorOutputPort(name, BasicVector<T>(size), calc,
> ```

nit, 
  `name` => `std::move(name)`
  `calc` => `std::move(calc)`
___
*[systems/framework/leaf_system.h, line 1453 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-MgDWSBt0C-jw46GIki8:-MgDWSBt0C-jw46GIki9:bj1jb0a) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.h#L1453)):*
> ```objc
>       std::set<DependencyTicket> prerequisites_of_calc = {
>           all_sources_ticket()}) {
>     return DeclareVectorOutputPort(name, BasicVector<T>(size),
> ```

nit, `name` => `std::move(name)`
___
*[systems/framework/leaf_system.h, line 1454 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-MgDWbji3wri3OcmcIPB:-MgDWbji3wri3OcmcIPC:b-zb7x9u) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.h#L1454)):*
> ```objc
>           all_sources_ticket()}) {
>     return DeclareVectorOutputPort(name, BasicVector<T>(size),
>                                    vector_calc_function, prerequisites_of_calc);
> ```

nit, 
`vector_calc_function` => `std::move(vector_calc_function)`
`prerequisites_of_calc` => `std::move(prerequisites_of_calc)`
___
*[systems/framework/leaf_system.cc, line 652 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-MgDW7vs8peMtlv1EtLi:-MgDW7vs8peMtlv1EtLj:bj1jb0a) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.cc#L652)):*
> ```cpp
>     std::variant<std::string, UseDefaultName> name, int size,
>     std::optional<RandomDistribution> random_type) {
>   return DeclareVectorInputPort(name, BasicVector<T>(size), random_type);
> ```

nit, `name` => `std::move(name)`

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 70 of 71 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538)* status: 6 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Conflict resolved.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538#-:-MgG3VSrEV3rFWWoPYpO:b-g99cqb)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @RussTedrake)

___
*[systems/framework/leaf_system.h, line 1372 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-Mg7DsPD8iIuy0U_9k6v:-MgG1uvbA22agKAdbmCr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.h#L1372)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: since there is no model_value here, the documentation should say how the BasicVector is initialized or explicitly say it is undefined. However, I believe it is guaranteed to be NaN-initialized in this case. (Same for other output port methods.)
</blockquote></details>

Done.
___
*[systems/framework/leaf_system.h, line 1387 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-MgDX6Ev31QJCBNz9c5s:-MgG20O8CQYhzj9si0YW:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.h#L1387)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, 
  `name` => `std::move(name)`
  `calc` => `std::move(calc)`
</blockquote></details>

Done
___
*[systems/framework/leaf_system.h, line 1453 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-MgDWSBt0C-jw46GIki8:-MgG2U_SDZ5RKPRTVnl0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.h#L1453)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `name` => `std::move(name)`
</blockquote></details>

Done.
___
*[systems/framework/leaf_system.h, line 1454 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-MgDWbji3wri3OcmcIPB:-MgG2VWO2eNK79HviJQ_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.h#L1454)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, 
`vector_calc_function` => `std::move(vector_calc_function)`
`prerequisites_of_calc` => `std::move(prerequisites_of_calc)`
</blockquote></details>

Done.
___
*[systems/framework/leaf_system.cc, line 652 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15538#-MgDW7vs8peMtlv1EtLi:-MgG2gev4H_builhLHXG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76878f31fff8b34c58b06d192a6e620915d188b7/systems/framework/leaf_system.cc#L652)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `name` => `std::move(name)`
</blockquote></details>

Done.
___
*[tutorials/dynamical_systems.ipynb, line 387 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15538#-Mg7YQyd4wbBBT4u1UuP:-MgG3S8mDvCEx1L-2vvL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/70624f363483928c6f0b8e355a672fa2cb6b1fdd/tutorials/dynamical_systems.ipynb#L387)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW no newline at EOF
</blockquote></details>

Done.

**Comment by soonho-tri** [comment]
I'm afraid that the new version is not pushed to your branch yet?

**Review by RussTedrake — COMMENTED** [review]
sorry.. done now!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538#-:-MgGnZTK-dHDJg6Jw0UP:bfky0ox)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @sherm1 and @soonho-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @sherm1 and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 16 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @RussTedrake)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15538#-:-MgGtknTCq9zxTp0lVsR:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),sherm1(platform) (waiting on @RussTedrake)

**Pull request merged**
