### PR TITLE
[multibody] Parse mujoco inertial bodies

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards #16369

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@joemasterjohn for feature review, please (as recommended by @sherm1).  Please double check my logic on the SpatialInertia frames, etc.  The details can all be found at https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-inertial .

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466#-:-MubMPQ86VvJ4MK6EV1H:b9z3rfs)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: after resolving a question about how to interpret the MuJoCo doc. 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466#-:-Mul18ngEtgTDZl_uF1y:bh9znva)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukqKvG3Y_bhKZLG2hk:-MukqKvG3Y_bhKZLG2hl:bwd0qy8) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L157)):*
> ```cpp
>       Vector6d full;
>       if (ParseVectorAttribute(node, "fullinertia", &full)) {
>         I_BF_F = RotationalInertia<double>(full[0], full[1], full[2], full[3],
> ```

My interpretation of the MuJoCo docs is that the full intertia is expressed in the body frame, B, considering it *sets* the orientation of inertial frame `F` using the eigen decomposition of `fullinertia`. Would appreciate a second look to confirm/deny (@sherm1, @amcastro-tri)
___
*[multibody/parsing/detail_mujoco_parser.cc, line 441 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-Mukvmq_8QlKizgmxQ9D:-Mukvmq_8QlKizgmxQ9E:b-9vb52o) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L441)):*
> ```cpp
>       geometries.push_back(std::move(geom));
>     }
> ```

nit: I can foresee a common error being "user sets inertia_from_geom_ = true and then doesn't provide any geometries for a given body". In which case they'll get a nasty error about a bad spatial inertia when `AddRigidBody()` is called. Maybe throwing out a small warning here detecting that case might be good.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 454 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukzoRN2zDn64-imJ9K:-MukzoRN2zDn64-imJ9L:b-bwvlgn) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/test/detail_mujoco_parser_test.cc#L454)):*
> ```cpp
>   const SceneGraphInspector<double>& inspector = scene_graph.model_inspector();
> 
>   auto CheckBody = [&plant, &context, &inspector](
> ```

nit: inspector is unused here. That's what's causing the CI failure.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 465 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukzsWX2KlJdawOf2Ij:-MukzsWX2KlJdawOf2Ik:b-rt2vdl) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/test/detail_mujoco_parser_test.cc#L465)):*
> ```cpp
>   };
> 
>   auto CheckBodySpatial = [&plant, &context, &inspector](
> ```

nit: inspector is unused here.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake and @sherm1)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukqKvG3Y_bhKZLG2hk:-Mum1JMR6T3HEzC4G-AU:b-dcrfoo) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L157)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

My interpretation of the MuJoCo docs is that the full intertia is expressed in the body frame, B, considering it *sets* the orientation of inertial frame `F` using the eigen decomposition of `fullinertia`. Would appreciate a second look to confirm/deny (@sherm1, @amcastro-tri)
</blockquote></details>

I have two questions here:
1. Could any of you tell me what F is? where can I find the definition of F in MuJoCo's manual? Probably worth documenting F locally in here. 
2. would you point me @joemasterjohn to the documentation for MuJoCo's inertia properties that you are reading?

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake and @sherm1)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukqKvG3Y_bhKZLG2hk:-Mum2oM3BLNmbpUUTFMD:b-hzourn) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L157)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I have two questions here:
1. Could any of you tell me what F is? where can I find the definition of F in MuJoCo's manual? Probably worth documenting F locally in here. 
2. would you point me @joemasterjohn to the documentation for MuJoCo's inertia properties that you are reading?

</blockquote></details>

The MuJoCo doc for this element is here: https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-inertial

I assumed `F` to be what MuJoCo calls the "inertial frame"

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake and @sherm1)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MumDTAu84vU_MWVUtMh:-MumDTAu84vU_MWVUtMi:b-e8bcdg) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L142)):*
> ```cpp
> 
>   SpatialInertia<double> ParseInertial(XMLElement* node) {
>     RigidTransformd X_BF_B = ParseTransform(node);
> ```

per @joemasterjohn's answer below. This seems to specify the pose of the inertial frame F (please document as such if this is true) measured in the body frame B.
Comments here:
1. The trailing `_B` does not follow our monogram convention. Please use X_BF (unless I am missing something).
2. Mujocos [docs here](https://mujoco.readthedocs.io/en/latest/modeling.html#cframe) talk about "local" or "global" coordinate frames and it mentions a flag `coordinate to control which one is in use. Is this relevant here? that is, can we always safely assume that B is the body frame? or could it be the world frame?
___
*[multibody/parsing/detail_mujoco_parser.cc, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MumETDZCEi7FwJSLher:-MumETDZCEi7FwJSLhes:bnotauj) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L149)):*
> ```cpp
>     }
> 
>     RotationalInertia<double> I_BF_F;
> ```

minor, the monogram notation we'd typically use here is I_BFo_F (inertia computed about point Fo, expressed in frame F)
___
*[multibody/parsing/detail_mujoco_parser.cc, line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukqKvG3Y_bhKZLG2hk:-MumElVE7TralCsvVIXQ:bq8kg17) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L157)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

The MuJoCo doc for this element is here: https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-inertial

I assumed `F` to be what MuJoCo calls the "inertial frame"
</blockquote></details>

Thank you @joemasterjohn. TBH, MuJoCo's documentation is not explicit about this, we can only infer that if the full inertia is specified, then it is in the body frame B. The documentation does provide a clear documentation of the "inertial" frame:
"The inertial frame is such that its center coincides with the center of mass of the body, and its axes coincide with the principal axes of inertia of the body. Thus the inertia matrix is diagonal in this frame."

Therefore I personally infer from those docs that if `full` was provided in the inertial frame F, that inertia would be diagonal and there would be no reason to specify 6 coefficients. So I coincide with you, it'd seem these coefficients are expressed in the body frame B (and therefore it's a bug to re-express below).

Note: It is confusing for us coming from SDF/URDF where they use "inertial" to mean the frame in which the inertia properties are expressed, whether that inertial frame coincides with the principal axes of inertia or not.
However, here  MuJoCo seems to be different in that their "inertial" frame always is coincident with the principal directions.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn and @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukqKvG3Y_bhKZLG2hk:-MumW27y3qFtbyQI8bdt:bjbvcvm) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L157)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Thank you @joemasterjohn. TBH, MuJoCo's documentation is not explicit about this, we can only infer that if the full inertia is specified, then it is in the body frame B. The documentation does provide a clear documentation of the "inertial" frame:
"The inertial frame is such that its center coincides with the center of mass of the body, and its axes coincide with the principal axes of inertia of the body. Thus the inertia matrix is diagonal in this frame."

Therefore I personally infer from those docs that if `full` was provided in the inertial frame F, that inertia would be diagonal and there would be no reason to specify 6 coefficients. So I coincide with you, it'd seem these coefficients are expressed in the body frame B (and therefore it's a bug to re-express below).

Note: It is confusing for us coming from SDF/URDF where they use "inertial" to mean the frame in which the inertia properties are expressed, whether that inertial frame coincides with the principal axes of inertia or not.
However, here  MuJoCo seems to be different in that their "inertial" frame always is coincident with the principal directions.
</blockquote></details>

My interpretation is that either:
- user provides an "inertial basis F" (by providing R_BF) and 3 diagonal principal inertias, OR
- user provides full inertia in the body frame B, then MuJoCo calculates basis F by diagonalizing the full inertia to get R_BF

I suspect (with less certainty) that if only the 3 diaginertias are given without providing R_BF then MuJoCo will assume that B is already the inertial basis, i.e. R_BF = identity.

I think my interpretation is the same as @amcastro-tri's ?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn and @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukqKvG3Y_bhKZLG2hk:-MupdZDtC-IDKWEWWLY1:b-qtpzd3) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L157)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

My interpretation is that either:
- user provides an "inertial basis F" (by providing R_BF) and 3 diagonal principal inertias, OR
- user provides full inertia in the body frame B, then MuJoCo calculates basis F by diagonalizing the full inertia to get R_BF

I suspect (with less certainty) that if only the 3 diaginertias are given without providing R_BF then MuJoCo will assume that B is already the inertial basis, i.e. R_BF = identity.

I think my interpretation is the same as @amcastro-tri's ?
</blockquote></details>

yes, that's my understanding. I believe @joemasterjohn's understanding as well.

**Review by joemasterjohn — COMMENTED** [review]
+@sherm1 for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466#-:-MuquCYl2ib14RKoA2LU:bfvx2sg)* status: 6 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @amcastro-tri, @RussTedrake, and @sherm1)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukqKvG3Y_bhKZLG2hk:-MuqvQm88iSqiqHjxfk4:b8mk5li) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L157)):*
Yes I agree. 

There is a required `pos` tag, which would correspond in the notation used in this PR to be `p_BoFo`. 
Reading above in the doc, the `quat, axisangle, xyaxes, zaxis, euler` (corresponding to `R_BF` in this case) is always optional and will default to the unit quaternion.

Interestingly from the doc:
> See Frame orientations. Similar to position, the orientation specified here is interpreted in either local or global coordinates as determined by the coordinate attribute of compiler.

So these tags may be specifying either `X_BF` or `X_WF` depending on some MuJoCo compiler option. That might need to be taken in consideration in the parser if some users write their model files in global coordinates.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few open comments and a CI fix

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466#-:-MusodDg5ilTIVJizQW6:browrdh)* status: 8 unresolved discussions (waiting on @amcastro-tri, @RussTedrake, and @sherm1)

___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 456 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MusoAgr9RbDs9E-hQyv:-MusoAgr9RbDs9E-hQyw:b-owzchj) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/test/detail_mujoco_parser_test.cc#L456)):*
> ```cpp
>   auto CheckBody = [&plant, &context, &inspector](
>                        const std::string& body_name,
>                        const UnitInertia<double>& unit_M_BB_B) {
> ```

nit: per notation doc, inertias should specify the "about" point explicitly, i.e. M_BBo or M_BBo_B here.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 516 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MusoZ8M22YCPKO_S8rr:-MusoZ8M22YCPKO_S8rs:b-fcjj8e) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/test/detail_mujoco_parser_test.cc#L516)):*
> ```cpp
> 
>   // A cube rotating about its corner.
>   RotationalInertia<double> I_BF_F(2, 2, 2, -.75, -.75, -.75);
> ```

nit: I_BFo_F

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466)* status: 3 unresolved discussions (waiting on @joemasterjohn and @sherm1)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MumDTAu84vU_MWVUtMh:-MuuqArk-cpxnMeM66UE:b-3ym0c1) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L142)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

per @joemasterjohn's answer below. This seems to specify the pose of the inertial frame F (please document as such if this is true) measured in the body frame B.
Comments here:
1. The trailing `_B` does not follow our monogram convention. Please use X_BF (unless I am missing something).
2. Mujocos [docs here](https://mujoco.readthedocs.io/en/latest/modeling.html#cframe) talk about "local" or "global" coordinate frames and it mentions a flag `coordinate to control which one is in use. Is this relevant here? that is, can we always safely assume that B is the body frame? or could it be the world frame?

</blockquote></details>

Done.  
1. Removed the trailing B.
2. Yes -- we will have to support global coordinate eventually, but i currently throw an unsupported error if that flag is set.  So I consider it safe to limit our support to the local frame here.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MumETDZCEi7FwJSLher:-MuuqWXnC0q7Ae2xpazT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L149)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, the monogram notation we'd typically use here is I_BFo_F (inertia computed about point Fo, expressed in frame F)
</blockquote></details>

Done.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukqKvG3Y_bhKZLG2hk:-Muur7pt3UfhxQJSvIgb:bimyvxw) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L157)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Yes I agree. 

There is a required `pos` tag, which would correspond in the notation used in this PR to be `p_BoFo`. 
Reading above in the doc, the `quat, axisangle, xyaxes, zaxis, euler` (corresponding to `R_BF` in this case) is always optional and will default to the unit quaternion.

Interestingly from the doc:
> See Frame orientations. Similar to position, the orientation specified here is interpreted in either local or global coordinates as determined by the coordinate attribute of compiler.

So these tags may be specifying either `X_BF` or `X_WF` depending on some MuJoCo compiler option. That might need to be taken in consideration in the parser if some users write their model files in global coordinates.
</blockquote></details>

Nice.  Thanks all. This was precisely the place where I needed a second opinion.
PTAL.  I hope I've interpreted your interpretation correctly!

Re: local vs global coordinates -- answered above.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 441 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-Mukvmq_8QlKizgmxQ9D:-MuuvdTL-MHcOLbDjl0G:bwyqxqd) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L441)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: I can foresee a common error being "user sets inertia_from_geom_ = true and then doesn't provide any geometries for a given body". In which case they'll get a nasty error about a bad spatial inertia when `AddRigidBody()` is called. Maybe throwing out a small warning here detecting that case might be good.
</blockquote></details>

But what about for inertia-less fake joints (e.g. when we make a floating joint programmatically, to add actuators to it).  The inertia can be zero, and that's ok, so long as downstream bodies add inertia.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 454 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukzoRN2zDn64-imJ9K:-MuuwgEq5yixMaAS3cLD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/test/detail_mujoco_parser_test.cc#L454)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: inspector is unused here. That's what's causing the CI failure.
</blockquote></details>

Done.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 456 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MusoAgr9RbDs9E-hQyv:-MuuxfjU1lhWd3kq_3fF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/test/detail_mujoco_parser_test.cc#L456)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: per notation doc, inertias should specify the "about" point explicitly, i.e. M_BBo or M_BBo_B here.
</blockquote></details>

Done.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 465 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukzsWX2KlJdawOf2Ij:-MuupoSK67CrTTS6b7GI:b-l5r1cy) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/test/detail_mujoco_parser_test.cc#L465)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: inspector is unused here.
</blockquote></details>

Done.  Thanks.

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-MukqKvG3Y_bhKZLG2hk:-Muv8Y54-FWAHV9mtBvI:b-vs1prh) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L157)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Nice.  Thanks all. This was precisely the place where I needed a second opinion.
PTAL.  I hope I've interpreted your interpretation correctly!

Re: local vs global coordinates -- answered above.
</blockquote></details>

Looks good!
___
*[multibody/parsing/detail_mujoco_parser.cc, line 441 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16466#-Mukvmq_8QlKizgmxQ9D:-Muv8bBn6Nw3OLo00mCx:b-kv0u5f) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d59dd659dd6d281e5542cca1ff5b31b4b8538c/multibody/parsing/detail_mujoco_parser.cc#L441)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

But what about for inertia-less fake joints (e.g. when we make a floating joint programmatically, to add actuators to it).  The inertia can be zero, and that's ok, so long as downstream bodies add inertia.
</blockquote></details>

Ah you're right. Please ignore.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> Dismissed @amcastro-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16466)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),joemasterjohn (waiting on @RussTedrake)

**Pull request merged**
