### PR TITLE
Add drake_py_unittest helper

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8203)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI could you do the feature and platform review, looking carefully at every change?
+@EricCousineau-TRI could you give the idea a sniff test and see if the idea makes sense?

**Comment by SeanCurtis-TRI** [comment]
There are two files that still have `unittest.main()` invocations (see below). However, they've been declared as unittests in the bazel infrastructure. I would expect this to lead to CI failure. Do these not get exercised in PR CI?

---

Reviewed 71 of 71 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/BUILD.bazel, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6SQm1GChuxIeLfrTqF:-L6SQm1GChuxIeLfrTqG:b5qa9tb) ([raw file](https://github.com/robotlocomotion/drake/blob/5fd93594aab4003346f88eb5f360a6274751921a/bindings/pydrake/BUILD.bazel#L239)):*
> ```Python
> )
> 
> drake_py_unittest(
> ```

`symbolic_variables_test.py` still seems to have an invocation of `unittest.main()`.

---

*[bindings/pydrake/systems/BUILD.bazel, line 250 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6SRGP1pdCV33RbsTMC:-L6SRGP1pdCV33RbsTMD:bf63n2s) ([raw file](https://github.com/robotlocomotion/drake/blob/5fd93594aab4003346f88eb5f360a6274751921a/bindings/pydrake/systems/BUILD.bazel#L250)):*
> ```Python
> )
> 
> drake_py_unittest(
> ```

BTW `controllers_test.py` still invokes `unittest.main()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-:-L6ST4xxEibYkn2nQIe8:bxh8wsx)*

**Comment by jwnimmer-tri** [comment]
As of r1 the cross-checking is only one-way.  If you _don't_ declare `drake_py_unittest` but you _do_ `import unittest` then it bombs.  If you _do_ declare `drake_py_unittest` but _also_ declare a `__main__` then it lets you slip by.  The main is dead code and thus confusing, but we've not lost any testing.  I had a TODO in r1 to add the `__main__` cross-checking, assuming that problems there would be rare.  Having screwed it up twice in this PR, I'll pause and see if I can resolve that TODO right away now, since its clearly a more likely hazard than I'd anticipated.  Thanks for the detailed cross-check (shepherding this through merge conflicts has been a challenge).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-:-L6Ti9Q25zp7U_RWZOYq:b-6fknl8)*

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 69 of 72 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/BUILD.bazel, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6SQm1GChuxIeLfrTqF:-L6Tl5BhiKELNoek6euT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fd93594aab4003346f88eb5f360a6274751921a/bindings/pydrake/BUILD.bazel#L239)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

`symbolic_variables_test.py` still seems to have an invocation of `unittest.main()`.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/BUILD.bazel, line 250 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6SRGP1pdCV33RbsTMC:-L6Tl5vfF_xaYbvigxL4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fd93594aab4003346f88eb5f360a6274751921a/bindings/pydrake/systems/BUILD.bazel#L250)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW `controllers_test.py` still invokes `unittest.main()`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-:-L6Tl7oC0TfjI8A9aGYO:b-83330m)*

**Comment by SeanCurtis-TRI** [comment]
And sorry for continuing dragging this along (and prolonging the merge-conflict hell). Generally, :LGTM: (with a few conversation points).

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[common/test_utilities/drake_py_unittest_main.py, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6Tm0-H-ph9B20Cv4cc:-L6Tm0-H-ph9B20Cv4cd:bkdsspu) ([raw file](https://github.com/robotlocomotion/drake/blob/5fd93594aab4003346f88eb5f360a6274751921a/common/test_utilities/drake_py_unittest_main.py#L10)):*
> ```Python
> 
> # TODO(jwnimmer-tri) This helper should fail-fast when the test code has a
> # __main__ routine or a shebang line.
> ```

FYI I see addressing `__main__`, but I don't see the shebang.

---

*[common/test_utilities/drake_py_unittest_main.py, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6TlmJITQNuVS6k5Ybg:-L6TlmJITQNuVS6k5Ybh:bssvawb) ([raw file](https://github.com/robotlocomotion/drake/blob/54da5d2f592e1862d9bc014e8e61cfaef1e20963/common/test_utilities/drake_py_unittest_main.py#L24)):*
> ```Python
>     with open(found_filename, "r") as infile:
>         for line in infile.readlines():
>             if line.startswith("if __name__ =="):
> ```

FYI Which is worse? `if __name__ ==` or `unittest.main()`? Admittedly, we would hope no one would invoke `unittest.main()` anywhere *but* in a guarded block, but still.

---

*[common/test_utilities/drake_py_unittest_main.py, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6Tm7pOjfogytKnNlcL:-L6Tm7pOjfogytKnNlcM:b-e6x5t2) ([raw file](https://github.com/robotlocomotion/drake/blob/54da5d2f592e1862d9bc014e8e61cfaef1e20963/common/test_utilities/drake_py_unittest_main.py#L31)):*
> ```Python
>                       "if this test is not based on unittest, declare it " +
>                       "as drake_py_test instead of drake_py_unittest and " +
>                       "keep the main function intact")
> ```

FYI I *love* this error message. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-:-L6TmNjqKkHbdWGkftG6:ba3yjjj)*

**Comment by jwnimmer-tri** [comment]
Review status: 70 of 72 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test_utilities/drake_py_unittest_main.py, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6Tm0-H-ph9B20Cv4cc:-L6Tx8YLZzKv33QnuAst:bkz5cki) ([raw file](https://github.com/robotlocomotion/drake/blob/5fd93594aab4003346f88eb5f360a6274751921a/common/test_utilities/drake_py_unittest_main.py#L10)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I see addressing `__main__`, but I don't see the shebang.
</blockquote></details>

Done.  Good catch!

---

*[common/test_utilities/drake_py_unittest_main.py, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6TlmJITQNuVS6k5Ybg:-L6TwSYyfk9zo00NbTlk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/54da5d2f592e1862d9bc014e8e61cfaef1e20963/common/test_utilities/drake_py_unittest_main.py#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Which is worse? `if __name__ ==` or `unittest.main()`? Admittedly, we would hope no one would invoke `unittest.main()` anywhere *but* in a guarded block, but still.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203)*

**Comment by EricCousineau-TRI** [comment]
First pass done, PTAL. (Sorry for the delay!)

---

Reviewed 69 of 71 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[common/test/drake_cc_googletest_main_test_device.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XipUFhscm3ZUDpgAr:-L6XipUGOjYbc1awTTC8:b4xkztf) ([raw file](https://github.com/robotlocomotion/drake/blob/fa05b1edb9bd19ccce7e468627fcb34606897904/common/test/drake_cc_googletest_main_test_device.cc#L1)):*
> ```cpp
> /// @file
> ```

BTW This rename seems outside the scope of this PR - could it be deferred to elsewhere? (or at the least, made a separate commit?)

---

*[common/test_utilities/drake_py_unittest_main.py, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XetCTD1fXTw3544kR:-L6XetCU5tZNjVDDKhkM:b-sc2xzt) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/common/test_utilities/drake_py_unittest_main.py#L42)):*
> ```Python
> 
>     # Have unittest find the test_filename and load its tests.
>     tests = unittest.TestLoader().discover(".", pattern=test_filename)
> ```

As it stands, we can't trivially pass `unittest` command-line arguments through.
Is there a way to keep these calls simple, and just call `unittest.main()`? (rather than `unittest.run`?)

On `master`, I can do the following and get help (and thus pare down tests or whatnot):
```
$ cd tools/lint
$ bazel run :buildifier_test -- --help
...
Usage: buildifier_test.py [options] [test] [...]

Options:
  -h, --help       Show this message
  -v, --verbose    Verbose output
  -q, --quiet      Minimal output
  -f, --failfast   Stop on first failure
  -c, --catch      Catch control-C and display results
  -b, --buffer     Buffer stdout and stderr during test runs

Examples:
  buildifier_test.py                               - run default set of tests
  buildifier_test.py MyTestSuite                   - run suite 'MyTestSuite'
  buildifier_test.py MyTestCase.testSomething      - run MyTestCase.testSomething
  buildifier_test.py MyTestCase                    - run all 'test*' test methods
                                               in MyTestCase
```

However, on this branch, `sys.argv` is ignored by `unittest`:
```
$ cd tools/lint
$ bazel run :buildifier_test -- --help
...
OK
```

---

*[tools/skylark/drake_py.bzl, line 98 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XhTRe9C8sGDsXJlYt:-L6XhTRe9C8sGDsXJlYu:b16wx5b) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/tools/skylark/drake_py.bzl#L98)):*
> ```Python
> 
>     This macro should be preferred instead of the basic drake_py_test for tests
>     that use the unittest framework.  Tests that use this macro should *not*
> ```

BTW Can you quote `` `unittest` `` to disambiguate it from being a general word?

---

*[tools/skylark/drake_py.bzl, line 108 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XhgMw2SzwtVCM2UqJ:-L6XhgMw2SzwtVCM2UqK:bli2zpp) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/tools/skylark/drake_py.bzl#L108)):*
> ```Python
>         srcs = srcs + [helper],
>         main = helper,
>         args = ["%s.py" % name] + args,
> ```

Rather than pass the name as an argument, can the name just be inferred from `sys.argv[0]`?
This goes in line with the `sys.argv` request.

(This simplifies the workflow of running via `.runfiles`, which is something I'd like to preserve, even if there's interactive sandbox debugging available.)

---

*[tools/skylark/drake_py.bzl, line 118 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6Xgz4700CMPi6K4DjV:-L6Xgz4700CMPi6K4DjW:bbmebii) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/tools/skylark/drake_py.bzl#L118)):*
> ```Python
>         data = None,
>         isolate = True,
>         allow_import_unittest = False,
> ```

Can you document this? (presumable by moving the below comment to the docstring?)
Or if it's intended to be hidden, prefix it with `_`?

---

*[tools/skylark/pybind.bzl, line 259 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XjLFWzmv4iV-pRwq9:-L6XjLFYDxJg7ocO6R3e:b-j06f79) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/tools/skylark/pybind.bzl#L259)):*
> ```Python
>         # The C++ test isn't going to `import unittest`, but test dependencies
>         # such as numpy(!!) do so unconditionally.  We should allow that.
>         allow_import_unittest = True,
> ```

FYI Ewwww!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-:-L6Xjt6c4Q-g8A3NX_rF:b-no4tsl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[common/test/drake_cc_googletest_main_test_device.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XipUFhscm3ZUDpgAr:-L6Xx-dZ_TSfRT6tXHUl:by7bwfv) ([raw file](https://github.com/robotlocomotion/drake/blob/fa05b1edb9bd19ccce7e468627fcb34606897904/common/test/drake_cc_googletest_main_test_device.cc#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW This rename seems outside the scope of this PR - could it be deferred to elsewhere? (or at the least, made a separate commit?)
</blockquote></details>

Done.  The rename is required for the `srcs` change in the BUILD file to work.  I've amended the commit message to note this.

---

*[common/test_utilities/drake_py_unittest_main.py, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XetCTD1fXTw3544kR:-L6Y1Jz6MpWMm1oEafzO:bnpclwu) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/common/test_utilities/drake_py_unittest_main.py#L42)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

As it stands, we can't trivially pass `unittest` command-line arguments through.
Is there a way to keep these calls simple, and just call `unittest.main()`? (rather than `unittest.run`?)

On `master`, I can do the following and get help (and thus pare down tests or whatnot):
```
$ cd tools/lint
$ bazel run :buildifier_test -- --help
...
Usage: buildifier_test.py [options] [test] [...]

Options:
  -h, --help       Show this message
  -v, --verbose    Verbose output
  -q, --quiet      Minimal output
  -f, --failfast   Stop on first failure
  -c, --catch      Catch control-C and display results
  -b, --buffer     Buffer stdout and stderr during test runs

Examples:
  buildifier_test.py                               - run default set of tests
  buildifier_test.py MyTestSuite                   - run suite 'MyTestSuite'
  buildifier_test.py MyTestCase.testSomething      - run MyTestCase.testSomething
  buildifier_test.py MyTestCase                    - run all 'test*' test methods
                                               in MyTestCase
```

However, on this branch, `sys.argv` is ignored by `unittest`:
```
$ cd tools/lint
$ bazel run :buildifier_test -- --help
...
OK
```

</blockquote></details>

Which of these options do you use?  I will either find a way to pass them through, or reimplement them.

In my mind, passing positional arguments to test cases is more common than using the unittest.main helpers (since python unit tests are usually extremely small and fast), and passing positional arguments is annoying when unittest.main is used.

---

*[tools/skylark/drake_py.bzl, line 98 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XhTRe9C8sGDsXJlYt:-L6XxYEp1MuDVVb5191G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/tools/skylark/drake_py.bzl#L98)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you quote `` `unittest` `` to disambiguate it from being a general word?
</blockquote></details>

Done.

---

*[tools/skylark/drake_py.bzl, line 108 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XhgMw2SzwtVCM2UqJ:-L6Y1AkUkRKoi_7vRF9E:b-xzaaf5) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/tools/skylark/drake_py.bzl#L108)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Rather than pass the name as an argument, can the name just be inferred from `sys.argv[0]`?
This goes in line with the `sys.argv` request.

(This simplifies the workflow of running via `.runfiles`, which is something I'd like to preserve, even if there's interactive sandbox debugging available.)
</blockquote></details>

Tricksy!  Done.

---

*[tools/skylark/drake_py.bzl, line 118 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6Xgz4700CMPi6K4DjV:-L6XyOY4R6VlwkMiOJst:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/tools/skylark/drake_py.bzl#L118)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you document this? (presumable by moving the below comment to the docstring?)
Or if it's intended to be hidden, prefix it with `_`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test_utilities/drake_py_unittest_main.py, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XetCTD1fXTw3544kR:-L6YAtJbouWffUjaFrHa:bgd9h0p) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/common/test_utilities/drake_py_unittest_main.py#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Which of these options do you use?  I will either find a way to pass them through, or reimplement them.

In my mind, passing positional arguments to test cases is more common than using the unittest.main helpers (since python unit tests are usually extremely small and fast), and passing positional arguments is annoying when unittest.main is used.
</blockquote></details>

OK Mainly the test selection and `-v`.

I've made some quick hack options for extracting the arguments, but I'd say they look pretty crappy:
https://github.com/EricCousineau-TRI/drake/commit/825ef2e
https://github.com/EricCousineau-TRI/drake/commit/3be243b

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-:-L6YBYSwkQ0u5hlc6w7l:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[common/test_utilities/drake_py_unittest_main.py, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XetCTD1fXTw3544kR:-L6YFpwfD9ZpV5rcVdTr:b-9qhlfx) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/common/test_utilities/drake_py_unittest_main.py#L42)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

OK Mainly the test selection and `-v`.

I've made some quick hack options for extracting the arguments, but I'd say they look pretty crappy:
https://github.com/EricCousineau-TRI/drake/commit/825ef2e
https://github.com/EricCousineau-TRI/drake/commit/3be243b
</blockquote></details>

Thanks!  I think a variant of option 1 might be less crappy and meet both goals.  I'll give it a try locally (marking myself blocking here in the meantime).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203)*

**Comment by jwnimmer-tri** [comment]
Review status: 70 of 72 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test_utilities/drake_py_unittest_main.py, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XetCTD1fXTw3544kR:-L6YRrDvRmCP_Xe2istv:b-s11k70) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/common/test_utilities/drake_py_unittest_main.py#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Thanks!  I think a variant of option 1 might be less crappy and meet both goals.  I'll give it a try locally (marking myself blocking here in the meantime).
</blockquote></details>

Done.  I've tested this locally and it seems to work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[common/test_utilities/drake_py_unittest_main.py, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8203#-L6XetCTD1fXTw3544kR:-L6hUoLN9eU2h-g1edx2:b556ppi) ([raw file](https://github.com/robotlocomotion/drake/blob/aa868ec4707fd2fc43e58cddeb4cd0ffb134b01e/common/test_utilities/drake_py_unittest_main.py#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.  I've tested this locally and it seems to work.
</blockquote></details>

Awesome, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8203)*

**Pull request merged**
