### PR TITLE
[systems] Add tolerance to primitives/symbolic_vector_system_test

### PR DESCRIPTION
**Pull request by svenevs**
Relates: #18327.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19375)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please.

**Review by svenevs — COMMENTED** [review]
+@sherm1 for review or delegation via #12012 please, see also https://github.com/RobotLocomotion/drake/issues/18327#issuecomment-1535537588

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19375#-:-NUo9mspE67AbyZGLnvr:bgoclx1)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @sherm1 and @svenevs)

___
*[`systems/primitives/test/symbolic_vector_system_test.cc` line 695 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19375#-NUo9aKi9TrlQSF1tNuo:-NUo9aKi9TrlQSF1tNup:b-kgd20v) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83ee2365050b3022e20d9babf982b8b5111c7d9/systems/primitives/test/symbolic_vector_system_test.cc#L695)):*
> ```cpp
>       CompareMatrices(xdotval[0].derivatives(),
>                       expected_xdotval0_deriv_,
>                       1.0e-15));
> ```

working, success criteria is that these tests pass in CI

```
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //systems/primitives:symbolic_vector_system_test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //systems/primitives:symbolic_vector_system_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
FAIL: //systems/primitives:symbolic_vector_system_test (see /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/systems/primitives/symbolic_vector_system_test/test.log)
INFO: From Testing //systems/primitives:symbolic_vector_system_test:
==================== Test output for //systems/primitives:symbolic_vector_system_test:
Using drake_cc_googletest_main.cc

[==========] Running 21 tests from 6 test suites.
[----------] Global test environment set-up.
[----------] 13 tests from SymbolicVectorSystemTest
[ RUN      ] SymbolicVectorSystemTest.BuilderBasicPattern
[       OK ] SymbolicVectorSystemTest.BuilderBasicPattern (0 ms)
[ RUN      ] SymbolicVectorSystemTest.DanglingReferenceTest
[       OK ] SymbolicVectorSystemTest.DanglingReferenceTest (0 ms)
[ RUN      ] SymbolicVectorSystemTest.CubicPolyViaBuilder
[       OK ] SymbolicVectorSystemTest.CubicPolyViaBuilder (0 ms)
[ RUN      ] SymbolicVectorSystemTest.ScalarPassThrough
[       OK ] SymbolicVectorSystemTest.ScalarPassThrough (0 ms)
[ RUN      ] SymbolicVectorSystemTest.VectorPassThrough
[       OK ] SymbolicVectorSystemTest.VectorPassThrough (0 ms)
[ RUN      ] SymbolicVectorSystemTest.OutputScaledTime
[       OK ] SymbolicVectorSystemTest.OutputScaledTime (0 ms)
[ RUN      ] SymbolicVectorSystemTest.ContinuousStateOnly
[       OK ] SymbolicVectorSystemTest.ContinuousStateOnly (0 ms)
[ RUN      ] SymbolicVectorSystemTest.DiscreteStateOnly
[       OK ] SymbolicVectorSystemTest.DiscreteStateOnly (0 ms)
[ RUN      ] SymbolicVectorSystemTest.IntegratorNoFeedthrough
[       OK ] SymbolicVectorSystemTest.IntegratorNoFeedthrough (0 ms)
[ RUN      ] SymbolicVectorSystemTest.ContinuousTimeSymbolic
[       OK ] SymbolicVectorSystemTest.ContinuousTimeSymbolic (0 ms)
[ RUN      ] SymbolicVectorSystemTest.LinearizeDynamics
[       OK ] SymbolicVectorSystemTest.LinearizeDynamics (0 ms)
[ RUN      ] SymbolicVectorSystemTest.DiscreteTimeSymbolic
[       OK ] SymbolicVectorSystemTest.DiscreteTimeSymbolic (0 ms)
[ RUN      ] SymbolicVectorSystemTest.TestScalarConversion
[       OK ] SymbolicVectorSystemTest.TestScalarConversion (0 ms)
[----------] 13 tests from SymbolicVectorSystemTest (0 ms total)

[----------] 1 test from SymbolicVectorSystemTestUtil
[ RUN      ] SymbolicVectorSystemTestUtil.CalcRecorder
[       OK ] SymbolicVectorSystemTestUtil.CalcRecorder (0 ms)
[----------] 1 test from SymbolicVectorSystemTestUtil (0 ms total)

[----------] 1 test from InputEvaluationTest/0, where TypeParam = double
[ RUN      ] InputEvaluationTest/0.EvaluateOnlyWhenNecessary
[       OK ] InputEvaluationTest/0.EvaluateOnlyWhenNecessary (0 ms)
[----------] 1 test from InputEvaluationTest/0 (0 ms total)

[----------] 1 test from InputEvaluationTest/1, where TypeParam = Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1>>
[ RUN      ] InputEvaluationTest/1.EvaluateOnlyWhenNecessary
[       OK ] InputEvaluationTest/1.EvaluateOnlyWhenNecessary (0 ms)
[----------] 1 test from InputEvaluationTest/1 (0 ms total)

[----------] 1 test from InputEvaluationTest/2, where TypeParam = drake::symbolic::Expression
[ RUN      ] InputEvaluationTest/2.EvaluateOnlyWhenNecessary
[       OK ] InputEvaluationTest/2.EvaluateOnlyWhenNecessary (0 ms)
[----------] 1 test from InputEvaluationTest/2 (0 ms total)

[----------] 4 tests from SymbolicVectorSystemAutoDiffXdTest
[ RUN      ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdFullGradient
systems/primitives/test/symbolic_vector_system_test.cc:693: Failure
Value of: CompareMatrices(xdotval[0].derivatives(), expected_xdotval0_deriv_)
  Actual: false (Values at (1, 0) exceed tolerance: -1.3925 vs. -1.3924999999999998, diff = 2.220446049250313e-16, tolerance = 0
m1 =
      0
-1.3925
      0
      0
  -0.45
      0
m2 =
      0
-1.3925
      0
      0
  -0.45
      0
delta=
                     0
-2.220446049250313e-16
                     0
                     0
                     0
                     0)
Expected: true
[  FAILED  ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdFullGradient (0 ms)
[ RUN      ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToInput
[       OK ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToInput (0 ms)
[ RUN      ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToState
systems/primitives/test/symbolic_vector_system_test.cc:734: Failure
Value of: CompareMatrices(xdotval[0].derivatives(), expected_xdotval0_deriv_.head<2>())
  Actual: false (Values at (1, 0) exceed tolerance: -1.3925 vs. -1.3924999999999998, diff = 2.220446049250313e-16, tolerance = 0
m1 =
      0
-1.3925
m2 =
      0
-1.3925
delta=
                     0
-2.220446049250313e-16)
Expected: true
[  FAILED  ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToState (0 ms)
[ RUN      ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToParameter
[       OK ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToParameter (0 ms)
[----------] 4 tests from SymbolicVectorSystemAutoDiffXdTest (0 ms total)

[----------] Global test environment tear-down
[==========] 21 tests from 6 test suites ran. (2 ms total)
[  PASSED  ] 19 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdFullGradient
[  FAILED  ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToState

 2 FAILED TESTS
================================================================================
Target //systems/primitives:symbolic_vector_system_test up-to-date:
  bazel-bin/systems/primitives/symbolic_vector_system_test
INFO: Elapsed time: 0.192s, Critical Path: 0.04s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//systems/primitives:symbolic_vector_system_test                         FAILED in 0.0s

Executed 1 out of 1 test: 1 fails locally.
```

**Comment by jwnimmer-tri** [comment]
@sherm1 To clarify the procedure: if you're OK with the new tolerance, simple LGTM and we can merge.  If you are unhappy with the new tolerance, you can develop an alternative patch and either push it here or open a new PR.

**Review by svenevs — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19375)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`systems/primitives/test/symbolic_vector_system_test.cc` line 695 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19375#-NUo9aKi9TrlQSF1tNuo:-NUtpgsP38Pk60pE_SFi:bfeuozk) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83ee2365050b3022e20d9babf982b8b5111c7d9/systems/primitives/test/symbolic_vector_system_test.cc#L695)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, success criteria is that these tests pass in CI

```
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //systems/primitives:symbolic_vector_system_test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //systems/primitives:symbolic_vector_system_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
FAIL: //systems/primitives:symbolic_vector_system_test (see /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/systems/primitives/symbolic_vector_system_test/test.log)
INFO: From Testing //systems/primitives:symbolic_vector_system_test:
==================== Test output for //systems/primitives:symbolic_vector_system_test:
Using drake_cc_googletest_main.cc

[==========] Running 21 tests from 6 test suites.
[----------] Global test environment set-up.
[----------] 13 tests from SymbolicVectorSystemTest
[ RUN      ] SymbolicVectorSystemTest.BuilderBasicPattern
[       OK ] SymbolicVectorSystemTest.BuilderBasicPattern (0 ms)
[ RUN      ] SymbolicVectorSystemTest.DanglingReferenceTest
[       OK ] SymbolicVectorSystemTest.DanglingReferenceTest (0 ms)
[ RUN      ] SymbolicVectorSystemTest.CubicPolyViaBuilder
[       OK ] SymbolicVectorSystemTest.CubicPolyViaBuilder (0 ms)
[ RUN      ] SymbolicVectorSystemTest.ScalarPassThrough
[       OK ] SymbolicVectorSystemTest.ScalarPassThrough (0 ms)
[ RUN      ] SymbolicVectorSystemTest.VectorPassThrough
[       OK ] SymbolicVectorSystemTest.VectorPassThrough (0 ms)
[ RUN      ] SymbolicVectorSystemTest.OutputScaledTime
[       OK ] SymbolicVectorSystemTest.OutputScaledTime (0 ms)
[ RUN      ] SymbolicVectorSystemTest.ContinuousStateOnly
[       OK ] SymbolicVectorSystemTest.ContinuousStateOnly (0 ms)
[ RUN      ] SymbolicVectorSystemTest.DiscreteStateOnly
[       OK ] SymbolicVectorSystemTest.DiscreteStateOnly (0 ms)
[ RUN      ] SymbolicVectorSystemTest.IntegratorNoFeedthrough
[       OK ] SymbolicVectorSystemTest.IntegratorNoFeedthrough (0 ms)
[ RUN      ] SymbolicVectorSystemTest.ContinuousTimeSymbolic
[       OK ] SymbolicVectorSystemTest.ContinuousTimeSymbolic (0 ms)
[ RUN      ] SymbolicVectorSystemTest.LinearizeDynamics
[       OK ] SymbolicVectorSystemTest.LinearizeDynamics (0 ms)
[ RUN      ] SymbolicVectorSystemTest.DiscreteTimeSymbolic
[       OK ] SymbolicVectorSystemTest.DiscreteTimeSymbolic (0 ms)
[ RUN      ] SymbolicVectorSystemTest.TestScalarConversion
[       OK ] SymbolicVectorSystemTest.TestScalarConversion (0 ms)
[----------] 13 tests from SymbolicVectorSystemTest (0 ms total)

[----------] 1 test from SymbolicVectorSystemTestUtil
[ RUN      ] SymbolicVectorSystemTestUtil.CalcRecorder
[       OK ] SymbolicVectorSystemTestUtil.CalcRecorder (0 ms)
[----------] 1 test from SymbolicVectorSystemTestUtil (0 ms total)

[----------] 1 test from InputEvaluationTest/0, where TypeParam = double
[ RUN      ] InputEvaluationTest/0.EvaluateOnlyWhenNecessary
[       OK ] InputEvaluationTest/0.EvaluateOnlyWhenNecessary (0 ms)
[----------] 1 test from InputEvaluationTest/0 (0 ms total)

[----------] 1 test from InputEvaluationTest/1, where TypeParam = Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1>>
[ RUN      ] InputEvaluationTest/1.EvaluateOnlyWhenNecessary
[       OK ] InputEvaluationTest/1.EvaluateOnlyWhenNecessary (0 ms)
[----------] 1 test from InputEvaluationTest/1 (0 ms total)

[----------] 1 test from InputEvaluationTest/2, where TypeParam = drake::symbolic::Expression
[ RUN      ] InputEvaluationTest/2.EvaluateOnlyWhenNecessary
[       OK ] InputEvaluationTest/2.EvaluateOnlyWhenNecessary (0 ms)
[----------] 1 test from InputEvaluationTest/2 (0 ms total)

[----------] 4 tests from SymbolicVectorSystemAutoDiffXdTest
[ RUN      ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdFullGradient
systems/primitives/test/symbolic_vector_system_test.cc:693: Failure
Value of: CompareMatrices(xdotval[0].derivatives(), expected_xdotval0_deriv_)
  Actual: false (Values at (1, 0) exceed tolerance: -1.3925 vs. -1.3924999999999998, diff = 2.220446049250313e-16, tolerance = 0
m1 =
      0
-1.3925
      0
      0
  -0.45
      0
m2 =
      0
-1.3925
      0
      0
  -0.45
      0
delta=
                     0
-2.220446049250313e-16
                     0
                     0
                     0
                     0)
Expected: true
[  FAILED  ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdFullGradient (0 ms)
[ RUN      ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToInput
[       OK ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToInput (0 ms)
[ RUN      ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToState
systems/primitives/test/symbolic_vector_system_test.cc:734: Failure
Value of: CompareMatrices(xdotval[0].derivatives(), expected_xdotval0_deriv_.head<2>())
  Actual: false (Values at (1, 0) exceed tolerance: -1.3925 vs. -1.3924999999999998, diff = 2.220446049250313e-16, tolerance = 0
m1 =
      0
-1.3925
m2 =
      0
-1.3925
delta=
                     0
-2.220446049250313e-16)
Expected: true
[  FAILED  ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToState (0 ms)
[ RUN      ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToParameter
[       OK ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToParameter (0 ms)
[----------] 4 tests from SymbolicVectorSystemAutoDiffXdTest (0 ms total)

[----------] Global test environment tear-down
[==========] 21 tests from 6 test suites ran. (2 ms total)
[  PASSED  ] 19 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdFullGradient
[  FAILED  ] SymbolicVectorSystemAutoDiffXdTest.AutodiffXdGradientRelativeToState

 2 FAILED TESTS
================================================================================
Target //systems/primitives:symbolic_vector_system_test up-to-date:
  bazel-bin/systems/primitives/symbolic_vector_system_test
INFO: Elapsed time: 0.192s, Critical Path: 0.04s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//systems/primitives:symbolic_vector_system_test                         FAILED in 0.0s

Executed 1 out of 1 test: 1 fails locally.
```

</blockquote></details>

done, [test passes in CI](https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-everything-release/10/consoleFull)

```
[12:16:02 AM]  //systems/primitives:symbolic_vector_system_test                         PASSED in 0.2s
```

If we need to change the tolerance we should rerun CI :+1:

**Review by sherm1 — COMMENTED** [review]
Thanks, @svenevs -- :lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19375#-:-NUvt3af9J2O8_W0EI3J:b8fh42s)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
