### PR TITLE
[GCS] Support passing an initial_guess to SolveConvexRestriction

### PR DESCRIPTION
**Pull request by RussTedrake**
+@wrangelvid for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506)* status: 1 unresolved discussion, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1174 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-NzSxK2zBItUVrf2ha9m:-NzSxK2zBItUVrf2ha9n:b-9i2wa6) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9bda010031418e0732d4242bdb6e332b2b736c7/geometry/optimization/graph_of_convex_sets.cc#L1174)):*
> ```cpp
>           : " and no rounding");
> 
>   {  // Push the placeholder variables and excluded edge variables into the
> ```

note that this big code block simply moved up from it's previous location (since we need the placeholder variables before we call rounding now)

**Review by wrangelvid — COMMENTED** [review]
In my version, I have been solving the restriction along the edges with the relaxation constraints as an initial guess before incorporating the restriction. While this approach is certainly faster, I am not sure about the quality of the initial guess. Let me try this out on my nonlinear experiments.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-:-NzZlAhu8oJIonmSDPJm:bbcmlrc)* status: 3 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/graph_of_convex_sets.h` line 643 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-NzZkmrbC09aR17zyPys:-NzZkmrbC09aR17zyPyt:b-r601rq) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9bda010031418e0732d4242bdb6e332b2b736c7/geometry/optimization/graph_of_convex_sets.h#L643)):*
> ```objc
>   an exception.
> 
>   If a `initial_guess` is provided, the solution inside this result will be used
> ```

I just noticed that we don't haver use `[at]params` here, should we add them?
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1336 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-NzZjGKr33iZXCKMCLch:-NzZjGKr33iZXCKMCLci:b2yzf8m) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9bda010031418e0732d4242bdb6e332b2b736c7/geometry/optimization/graph_of_convex_sets.cc#L1336)):*
> ```cpp
>       // Optimize path
>       MathematicalProgramResult rounded_result =
>           SolveConvexRestriction(new_path, options, &result);
> ```

A user can decide when an initial guess is used through your new `SolveConvexRestriction` api. However, here that decision is pulled away from a user. For nonlinear programs it would make sense in most of the cases to provide a guess, but is that also true MOSEK on GCS problems? Is there a way we can benchmark runtimes to find out?

**Review by RussTedrake — COMMENTED** [review]
I'm going to wait for #21402 to land before I finish this one up.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-:-NzoWIca9fqq6DqrPOpd:b-wv86hd)* status: 3 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1336 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-NzZjGKr33iZXCKMCLch:-NzoWYAL0BRkZMGtDAyJ:b-faoxu1) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9bda010031418e0732d4242bdb6e332b2b736c7/geometry/optimization/graph_of_convex_sets.cc#L1336)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

A user can decide when an initial guess is used through your new `SolveConvexRestriction` api. However, here that decision is pulled away from a user. For nonlinear programs it would make sense in most of the cases to provide a guess, but is that also true MOSEK on GCS problems? Is there a way we can benchmark runtimes to find out?
</blockquote></details>

Mosek should be unaffected by the initial guess.

The user never had control here. We were passing an initial guess of all zeros.  Now we're passing a better initial guess. I don't think that causes any new inconsistency.

**Review by wrangelvid — COMMENTED** [review]
Thank you for the patience, Russ. I incorporated your changes into one of my branch and benchmarked the runtimes on most the experiments in my thesis. The following table shows the runtimes for the 2d, UAV and IIWA results in milliseconds where we solve the path with GcsTrajOpt twenty times each and report the mean runtime. We compare no initial guess, with resolving the restriction with the constraints of the relaxation in the rounding step before passing the solution as an initial guess (second column) and with your implementation where we pull the initial guess from relaxation result.
|          Experiment         | No Initial Guess | Re-Solved Guess | Relaxation Guess (this PR) |
|:---------------------------:|------------------|----------------|------------------|
| 2d Min Time (convex)        | 63               | 69             | **61**               |
| 2d Min Time + Acc           | 176               | **133**            | 149              |
| 2d Min Time + Acc + C2      | 421              | **265**            | 293              |
| 2d Multi Start              | 474              | 384            | **361**              |
| 2d Intermediate Planning    | 602              | **516**            | 774              |
| UAV Baseline (convex)       | 1664             | 1686           | **1659**             |
| UAV Min Time + Acc + C4     | 6262             | 5503           | **5254**             |
| IIWA Circle Task (convex)   | **10457**            | 11102          | 10621            |
| IIWA Circle Task + acc + C2 | **44086**            | 44322          | 44106            |
| IIWA IK pre-computed        | 2861             | **2438**          | 2659             |
| IIWA Planning + IK          | 4918             | **1987**           | 2948             |
| IIWA + Obstacle Avoidance   | 2379             | 1910           | **866**              |

In some cases, where the problem is convex we find that providing Mosek with an initial guess results in slight improvements.
Re-solving will yield a higher quality initial guess, but takes a toll on computation time since we have to solve twice per rounding step. In some cases, this still results in better runtimes, but in other cases your strategy wins. There might be a relationship between the tightness of the relaxation and which strategy wins here, but I haven't had time to dive into that. Overall, providing an initial guess is much better than not providing one, so I am in favor of supporting your solution :)

While you are at it, should we also expose the initial guess api in GcsTrajectoryOptimization::SolveConvexRestriction()?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-:-O-X0tei-TsEJszGEXWY:b-auxqh1)* status: 2 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-X--9P6qjdndj3pOHV:-O-X--9P6qjdndj3pOHW:bi99dk8) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9bda010031418e0732d4242bdb6e332b2b736c7/geometry/optimization/graph_of_convex_sets.cc#L1244)):*
> ```cpp
>         x_val[count++] = x_v[i];
>       }
>       for (int ii = 0; ii < v->ell_.size(); ++ii) {
> ```

nit: While we are at it, can we remove these ii's in favor of i?

**Review by wrangelvid — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-:-O-Y05g8Ds_ILDOrq4Lm:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
@wrangelvid awesome.  thank you for doing the benchmarking.  i'm happy to soon follow-up with the `GcsTrajectoryOptimization::SolveConvexRestriction()` but prefer to land this self-contained change first.

per slack with @bernhardpg ... i'm going to go ahead and land this one and let him handle the merge on his PR when he's able to get back to it.

+@xuchenhan-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-:-O-kGzqJ8uLtVT24rdtX:b-9458n7)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 643 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-NzZkmrbC09aR17zyPys:-O-kI31gDkuklRM2JXVK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9bda010031418e0732d4242bdb6e332b2b736c7/geometry/optimization/graph_of_convex_sets.h#L643)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

I just noticed that we don't haver use `[at]params` here, should we add them?
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-X--9P6qjdndj3pOHV:-O-kIe8QDtykQg9-_xiM:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9bda010031418e0732d4242bdb6e332b2b736c7/geometry/optimization/graph_of_convex_sets.cc#L1244)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

nit: While we are at it, can we remove these ii's in favor of i?
</blockquote></details>

Done.

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with a few comments.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-:-O-nq5VB13VyjM62uyOK:b-2cmql7)* status: 4 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-npo-L5ew28mga51Kt:-O-npo-L5ew28mga51Ku:b-988pqd) (no related file):*
There's no unit test for the added feature. Is there a good reason why?

___
___
*[`geometry/optimization/graph_of_convex_sets.h` line 643 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-nAYsT03MeNorLhKjR:-O-nAYsT03MeNorLhKjS:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/61906b732b6379d7774b1d041cd78e960102731d/geometry/optimization/graph_of_convex_sets.h#L643)):*
> ```objc
>   an exception.
> 
>   If a @p initial_guess is provided, the solution inside this result will be
> ```

typo



_Suggestion:_
```objc
If an @p initial_guess is provided, the solution inside this result will be
```
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1195 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-noDt15WFnFT1KZRjo:-O-noDt15WFnFT1KZRjp:b-o21dsm) ([raw file](https://github.com/RobotLocomotion/drake/blob/61906b732b6379d7774b1d041cd78e960102731d/geometry/optimization/graph_of_convex_sets.cc#L1195)):*
> ```cpp
>          vertices_) {
>       num_placeholder_vars += vpair.second->ambient_dimension();
>       num_placeholder_vars += vpair.second->ell_.size();
> ```

BTW, this pattern indicates there's a styleguide violation in the Vertex/Edge struct (should be without the trailing underscore).



_Code quote:_
```cpp
vpair.second->ell_
```
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1272 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-npPQ744SeTTyG2hI1:-O-npPQ744SeTTyG2hI2:b-cq2hnz) ([raw file](https://github.com/RobotLocomotion/drake/blob/61906b732b6379d7774b1d041cd78e960102731d/geometry/optimization/graph_of_convex_sets.cc#L1272)):*
> ```cpp
>       }
>     }
>     result.set_decision_variable_index(decision_variable_index);
> ```

BTW, is it true that we should expect `count == x_val.size()` here? If so consider a DRAKE_DEMAND here to confirm that. If not, then some values in `x_val` is uninitialized.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-npo-L5ew28mga51Kt:-O-or8GHDRREzWeTAxI4:b1go2s3) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There's no unit test for the added feature. Is there a good reason why?
</blockquote></details>

oops!  done.

___
___
*[`geometry/optimization/graph_of_convex_sets.h` line 643 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-nAYsT03MeNorLhKjR:-O-orPcE-kZ4TR7JRYg3:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/61906b732b6379d7774b1d041cd78e960102731d/geometry/optimization/graph_of_convex_sets.h#L643)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1195 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-noDt15WFnFT1KZRjo:-O-oromk7E1WFfy0klZU:blo63fc) ([raw file](https://github.com/RobotLocomotion/drake/blob/61906b732b6379d7774b1d041cd78e960102731d/geometry/optimization/graph_of_convex_sets.cc#L1195)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this pattern indicates there's a styleguide violation in the Vertex/Edge struct (should be without the trailing underscore).
</blockquote></details>

they aren't structs.  it's a friend class.
```
friend class GraphOfConvexSets;
```
(because we intentionally avoid making all of the member variables available in the public API; it's too easy to misuse them)
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1272 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21506#-O-npPQ744SeTTyG2hI1:-O-osSUK-N8E9exce3p0:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/61906b732b6379d7774b1d041cd78e960102731d/geometry/optimization/graph_of_convex_sets.cc#L1272)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is it true that we should expect `count == x_val.size()` here? If so consider a DRAKE_DEMAND here to confirm that. If not, then some values in `x_val` is uninitialized.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21506)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees wrangelvid,xuchenhan-tri(platform)

**Pull request merged**
