### PR TITLE
Remove MATLAB bouncing_ball example

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6369.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6370)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.
+(status: do not merge) until I've assigned additional review.

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6370#-:-Kn-k3A3r_2fD9xQu4ZO:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.
-(label: do not merge)

**Comment by ggould-tri** [comment]
Does @russtedrake 's previous comment (from the Atlas PR) about opening an issue for this (and thus my previous comment about noting it in the readme) apply here as well?

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6370#-:-Kn0RsLyMhAxkn5-2bPF:bmpd5pq)*

**Comment by jwnimmer-tri** [comment]
In this case, I believe the PR is fine as is -- with no issue filed, and no specific README.

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6370#-:-Kn0i9NQNFvqL9TYeKfk:bnfp4nl)*

**Pull request merged**
