### PR TITLE
[framework] DiagramBuilder fails-fast if used after Build

### LINKED ISSUE #11826: DiagramBuilder should be invalidated after Build()
Recently a user reached out with an obscure bug in which a system used as a source didn't seem to be connected even after adding it to the builder.

The pseudo code of the example looks like:
```c++
// Create an MBP plant.
auto plant = ...

// Add viz and build diagram:
geometry::ConnectDrakeVisualizer(&builder, scene_graph);
auto diagram = builder.Build();

// Create a source, AFTER DiagramBuilder::Build()!!!
auto source = builder.AddSystem(std::move(my_external_forces))

// Connect the source, AFTER DiagramBuilder::Build()!!!
builder.Connect(
        source->get_externally_applied_spatial_force_output_port(),
        plant.get_applied_spatial_force_input_port());

// Simulate. The simulation showed no signs of the external forces source, as if not connected!
systems::Simulator<double> simulator(*diagram);
simulator.StepTo(final_time);


```

Inspection of the example revealed that a user can call:
 - `DiagramBuilder::AddSystem()` and,
 - `DiagramBuilder::Connect()` (notably this did not fail even though one of the systems being connected was not owned by the builder anymore after the call to `Build()`)

after `DiagramBuilder::Build()` and the builder issues no error message. The user can still call the simulator and the executable runs successfully. Naturally, the actual diagram did not reflect the newly added and connected system.

Since our `DiagramBuilder` owns the systems until `Build()` transfers ownership to the new `Diagram`, I believe the quick, and possibly correct, solution would be to invalidate the builder after `Build()` and throw meaningful error messages if a user attempts to keep adding systems and connecting them.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #11826.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16082)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
`builder_.AddSystem(builder_.Build());`  :skull_and_crossbones:

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

+@seancurtis-tri for platform review

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16082#-:-Mo_JPbFEroMrsp1Dh6e:b1borz)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16082#-:-Mo_VWcg1Y43h9zjngfq:bmxilld)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/framework/test/diagram_builder_test.cc, line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16082#-Mo_V2BS8cZuOIaQOOV6:-Mo_V2BS8cZuOIaQOOV7:b-5erlu7) ([raw file](https://github.com/robotlocomotion/drake/blob/11898d6fe6e20085f653063257d8cdcf96bd3b91/systems/framework/test/diagram_builder_test.cc#L44)):*
> ```cpp
> }
> 
> // Tests one example of ThrowIfAlreadyBuilt().
> ```

BTW The one danger of this testing strategy is it requires no extension, so any modification to `DiagramBuilder` could easily forget to add the `throw` boilerplate. That said, I presume that

a) `DiagramBuilder` won't be changing much.
b) If it does change, the sheer number of invocation to throw are such that at least one of author, feature, or plpatform reviewers will notice the pattern inconsistency.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16082)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[systems/framework/test/diagram_builder_test.cc, line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16082#-Mo_V2BS8cZuOIaQOOV6:-Mo_eG1k-R87QkwcpuOA:b-wn9bfs) ([raw file](https://github.com/robotlocomotion/drake/blob/11898d6fe6e20085f653063257d8cdcf96bd3b91/systems/framework/test/diagram_builder_test.cc#L44)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The one danger of this testing strategy is it requires no extension, so any modification to `DiagramBuilder` could easily forget to add the `throw` boilerplate. That said, I presume that

a) `DiagramBuilder` won't be changing much.
b) If it does change, the sheer number of invocation to throw are such that at least one of author, feature, or plpatform reviewers will notice the pattern inconsistency.
</blockquote></details>

OK That was my thinking as well.  Plus (c) the liklihood that the user calls _only_ some (new) functions on the builder that omit these checks seems exceedingly low.

**Pull request merged**
