### PR TITLE
[math] Split up a test case to avoid a Clang 15 ICE

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21363)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-valgrind-memcheck please

**Review by SeanCurtis-TRI — COMMENTED** [review]
What's an ICE?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21363#-:-NwQ3D0t1mtvOzRr5lQ4:br1ht30)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
https://en.wikipedia.org/wiki/Compilation_error#Internal_Compiler_Errors

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks.  That was going to be my guess.  :)

BTW I thought I'd be able to reproduce the defect locally, but I failed. I thought:

`bazel test --config=lint --compilation_mode=dbg --config=memcheck  //math/...`

would be enough, but it wasn't. What have I missed? FTR I did pull current master and run `install_prereqs.sh` which reported success (and I *did* see clang-15 stuff go by).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21363#-:-NwQ42tvCqKbN7Uqr51V:b-3zlw1y)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
You want `--config=clang` not `--config=lint`.

**Comment by mwoehlke-kitware** [comment]
*[`math/test/rotation_matrix_test.cc` line 1161 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21363#-NwQ5HfKB9N2AdduWEbE:-NwQ5HfKB9N2AdduWEbF:b4cvpcb) ([raw file](https://github.com/RobotLocomotion/drake/blob/e0d77ba5ebc4cae3b8c886c574624bbc7068deae/math/test/rotation_matrix_test.cc#L1161)):*
> ```cpp
> }
> #ifdef __clang__
> #pragma clang optimize on
> ```

FYI, it might be awkward to use here (due to `GTEST_TEST` wrapping the function), but are you also aware of `[[clang::optnone]]`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21363)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

___
*[`math/test/rotation_matrix_test.cc` line 1161 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21363#-NwQ5HfKB9N2AdduWEbE:-NwQ7G_155u1cZRmQ393:b-3gugdd) ([raw file](https://github.com/RobotLocomotion/drake/blob/e0d77ba5ebc4cae3b8c886c574624bbc7068deae/math/test/rotation_matrix_test.cc#L1161)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, it might be awkward to use here (due to `GTEST_TEST` wrapping the function), but are you also aware of `[[clang::optnone]]`?
</blockquote></details>

I decided not to try to fight gtest on that battle.

**Review by SeanCurtis-TRI — COMMENTED** [review]
D'oh. That's what I get for being creative -- I should've just copied-and-pasted the parameters. 

:LGTM: X2

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21363#-:-NwQ7oVFCTzvoEmxc-T4:bi02hbx)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Setting "do not merge" for now.

This does work around the ICE, but while debugging the test failure it seems like Clang is mis-compiling AngleAxis so maybe we should try to fix that first.

**Pull request closed without merging**
