### PR TITLE
[visualization] Provide image-processing systems in C++

### LINKED ISSUE #20482: Port some image-processing systems from pydrake-only to C++ also
These systems are currently pydrake-only (no C++):
- ConcatenateImages
- ColorizeDepthImage
- ColorizeLabelImage

We should port them to C++ as well, so we can use them in native code.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Previously, these were a pydrake-only feature.

Closes #20482.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20488)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please.

**Comment by zachfang** [comment]
FYI. In case I am blocking anything, my plan is to review the PR today (probably the second half of the day).

**Review by zachfang — COMMENTED** [review]
Checkpoint with the .cc tests and the binding left. Will finish the review this afternoon. 

> Reviewed 14 of 21 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-:-NipKa3cEHxm4jvUEtrZ:bgm44xf)* status: 3 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`visualization/colorize_depth_image.cc` line 54 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-NipCSsN6Tm3EDQFwxYS:-NipCSsOB1Z89Ia-q7t5:b5mm8mv) ([raw file](https://github.com/RobotLocomotion/drake/blob/33a3c77ba53922f46000b483513f0762ec38d54a/visualization/colorize_depth_image.cc#L54)):*
> ```cpp
>     min_pixel = 0;
>     max_pixel = 0;
>   } else {
> ```

Should we error out in this case? `!min_pixel.has_value()` happens when we have an image with no valid pixel.



_Code quote:_
```cpp
  if (!min_pixel.has_value()) {
    min_pixel = 0;
    max_pixel = 0;
  } else {
```
___
*[`visualization/colorize_depth_image.cc` line 67 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-NipD5qkESDfq3CCGH91:-NipD5qkESDfq3CCGH92:by2165q) ([raw file](https://github.com/RobotLocomotion/drake/blob/33a3c77ba53922f46000b483513f0762ec38d54a/visualization/colorize_depth_image.cc#L67)):*
> ```cpp
> 
>   // Convert the depths to grayscale.
>   const double depth_scale = 1.0 / (*max_pixel - *min_pixel);
> ```

Continuing the above comment. If {min, max}_pixel=0, we will have a dividing-zero case here?



_Code quote:_
```cpp
const double depth_scale = 1.0 / (*max_pixel - *min_pixel);
```
___
*[`visualization/colorize_label_image.cc` line 68 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-NipGB7C4emZDLPxWwaC:-NipGB7D7RCW0TcuqQH-:bo6fl6x) ([raw file](https://github.com/RobotLocomotion/drake/blob/33a3c77ba53922f46000b483513f0762ec38d54a/visualization/colorize_label_image.cc#L68)):*
> ```cpp
>       const bool is_reserved = label > RenderLabel::kMaxUnreserved;
>       const std::array<uint8_t, 4>& color =
>           is_reserved ? background : palette[label % palette.size()];
> ```

nit. From the implementation, we will cycle through 10 different valid label colors even if we have more labels, i.e., some different labels will be mapped to the same color. Should we document that for clarity?



_Code quote:_
```cpp
palette[label % palette.size()]
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20488)* status: 2 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`visualization/colorize_depth_image.cc` line 54 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-NipCSsN6Tm3EDQFwxYS:-NipMqyi4BVP_ku4W7nY:bbi9lww) ([raw file](https://github.com/RobotLocomotion/drake/blob/33a3c77ba53922f46000b483513f0762ec38d54a/visualization/colorize_depth_image.cc#L54)):*
> Should we error out in this case?

My design intention is that _every_ input image produces some kind of output image.  It does not seem practical to ask users to vet every image they will be feeding into this input port.

In any case, showing an all-red image when there are no depth readings seems like a _good_ thing?
___
*[`visualization/colorize_depth_image.cc` line 67 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-NipD5qkESDfq3CCGH91:-NipN5Mk5aXPQiExMsZO:bssf4kr) ([raw file](https://github.com/RobotLocomotion/drake/blob/33a3c77ba53922f46000b483513f0762ec38d54a/visualization/colorize_depth_image.cc#L67)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Continuing the above comment. If {min, max}_pixel=0, we will have a dividing-zero case here?
</blockquote></details>

Yes, it will divide by zero in that case.  The output image is still correct, I think?  Or is the defect that the code is too unclear?
___
*[`visualization/colorize_label_image.cc` line 68 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-NipGB7C4emZDLPxWwaC:-NipMnIr1D9TVGbno58R:b64yywu) ([raw file](https://github.com/RobotLocomotion/drake/blob/33a3c77ba53922f46000b483513f0762ec38d54a/visualization/colorize_label_image.cc#L68)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. From the implementation, we will cycle through 10 different valid label colors even if we have more labels, i.e., some different labels will be mapped to the same color. Should we document that for clarity?
</blockquote></details>

Done (in header).

**Review by zachfang — COMMENTED** [review]
:lgtm: feature.

> Reviewed 5 of 21 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-:-NiprmXw2f_yHe5amva8:b-n37teh)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`visualization/colorize_depth_image.cc` line 54 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-NipCSsN6Tm3EDQFwxYS:-NippSzf4bh_h3XY0Luo:b-om5tqf) ([raw file](https://github.com/RobotLocomotion/drake/blob/33a3c77ba53922f46000b483513f0762ec38d54a/visualization/colorize_depth_image.cc#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Should we error out in this case?

My design intention is that _every_ input image produces some kind of output image.  It does not seem practical to ask users to vet every image they will be feeding into this input port.

In any case, showing an all-red image when there are no depth readings seems like a _good_ thing?
</blockquote></details>

OK. I agree with the design intention. (I was thinking `normalized_depth` will explode given an inf `depth_scale`, but it won't actually happen.)
___
*[`visualization/colorize_depth_image.cc` line 67 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-NipD5qkESDfq3CCGH91:-NipqqjM0yWgYm61SpK0:br64n0w) ([raw file](https://github.com/RobotLocomotion/drake/blob/33a3c77ba53922f46000b483513f0762ec38d54a/visualization/colorize_depth_image.cc#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, it will divide by zero in that case.  The output image is still correct, I think?  Or is the defect that the code is too unclear?
</blockquote></details>

OK. Right, I tested with an invalid depth image, and the returned image is filled with the invalid color value which is expected.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please (if you still have time).

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 18 of 21 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20488#-:-NipyD1nEuMQSWcTLdhb:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),zachfang

**Comment by jwnimmer-tri** [comment]
Oops.  The depth images were inverted (#20940).

**Pull request merged**
