### PR TITLE
[fem] Reconcile unknown variable and highest order state

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
* Remove all occurance of "highest order state" in favor of "unknown variable" because the unknown variable being solved for in FEM is *not* necessarily the highest order state. Relate RobotLocomotion#15349.
* Template StateUpdater on the scalar type instead of the State type and move it from state-templated FemModel to type-templated FemModelBase.
* Move the method State::get_highest_order_state() to StateUpdater::GetUnknowns() as the FemState by itself cannot determine which variable is the "unknown". That information is held by StateUpdater.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15357)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for sole review please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15357#-:-MeWwcCM1QxUUwAlPpCC:b-hq4nxl)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
just a few nits and comments. This is a very nice cleanup, thanks. :lgtm: 

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15357#-:-MezOcm57KXBoWqMFtRG:bfssdxo)* status: 5 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/fem_model.h, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezNjmO6ME8AaTY7sjX:-MezNjmO6ME8AaTY7sjY:b-4fdpk) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/fem_model.h#L64)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(FemModel);
> 
>   explicit FemModel(std::unique_ptr<internal::StateUpdater<T>> state_updater)
> ```

for my own education here. It looks like you decided to leave `FemModel` outside `internal::`. Is that true?
___
*[multibody/fixed_fem/dev/fem_model_base.h, line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezN44OBIe8u2vNuh-J:-MezN44OBIe8u2vNuh-K:bvjykcc) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/fem_model_base.h#L186)):*
> ```objc
>       Eigen::SparseMatrix<T>* tangent_matrix) const = 0;
> 
>   void increment_num_nodes(int num_new_nodes) { num_nodes_ += num_new_nodes; }
> ```

could you say something about this method here? who is the indented user? it is protected, so I imagine this is somehow useful to derived classes? could you say how here?
___
*[multibody/fixed_fem/dev/state_updater.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezLOtNBNRSLVAhrAIe:-MezLOtNBNRSLVAhrAIf:b92wr4) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/state_updater.h#L12)):*
> ```objc
> // TODO(xuchenhan-tri): Try to come up with a better name for this class. It
> //  does more than updating the states. It also defines the discretized equation
> //  that FEM solver solves.
> ```

what about something like:
- TimeSteppingMap (or Mapper)
___
*[multibody/fixed_fem/dev/state_updater.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezJ4Lz-DJDRWa4eRX9:-MezJ4Lz-DJDRWa4eRXA:b-7somfu) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/state_updater.h#L67)):*
> ```objc
>    form the tangent matrix (see FemModelBase). If q̇ or q̈ are not a part of the
>    state, their derivatives are set to 0. */
>   Vector3<T> weights() const { return do_get_weights(); }
> ```

there is an implicit assumption here, and that is that in general the map from unknowns z to state has the form:
q̈ = αₐ z + bₐ
q̇ = αᵥ z + bᵥ
q = αₚ z + bₚ
where the different b's are bias terms, independent of z.

Anyways, I found the description in terms of derivatives a bit clunky since you have to say that you do it for a simple component i, and that it is the same for each component, etc, etc.
If we place the lil equation above in the class's docs, you can simply state here that you return the vector of weights (αₐ, αᵥ, αₚ).
___
*[multibody/fixed_fem/dev/state_updater.h, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezInhj0_wS_O1ypR7R:-MezInhkCAbZlVTd_Htb:b-7fyvt9) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/state_updater.h#L121)):*
> ```objc
>    time-stepping scheme of the derived class. The `dz` provided here has
>    compatible size with the number of generalized positions in `state` and does
>    not need to be checked again.  */
> ```

nit, I typically document all of the `DoFoo()` methods as something like: "Implements the NVI Foo(). Refer to Foo() for details".
That avoids having to provide details here and in the NVI.
___
*[multibody/fixed_fem/dev/zeroth_order_state_updater.h, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezKzS71oCjYfrcdiZy:-MezKzS71oCjYfrcdiZz:b-o5ls61) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/zeroth_order_state_updater.h#L21)):*
> ```objc
> 
>  private:
>   /* Implements StateUpdater::weights(). */
> ```

nit, I don't think you need these "Implements foo" comments here since they don't add much. The signature "final" tells us exactly that.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15357)* status: 3 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/fem_model.h, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezNjmO6ME8AaTY7sjX:-MezdKxwB31oOrancg4M:bdmrcp) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/fem_model.h#L64)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

for my own education here. It looks like you decided to leave `FemModel` outside `internal::`. Is that true?
</blockquote></details>

No, I plan to have FemModel in `internal::` and `FemModelBase` outside of `internal::`. This will happen when they move out of dev. I'm also pondering a name change `FemModelBase` -> `FemModel` and `FemModel`->`FemModelImpl` (or something else) along the way.
___
*[multibody/fixed_fem/dev/fem_model_base.h, line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezN44OBIe8u2vNuh-J:-MezoVYP0FVrSV43sb0P:b-x7w65b) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/fem_model_base.h#L186)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could you say something about this method here? who is the indented user? it is protected, so I imagine this is somehow useful to derived classes? could you say how here?
</blockquote></details>

I added some comment. PTAL, thanks.
___
*[multibody/fixed_fem/dev/state_updater.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezLOtNBNRSLVAhrAIe:-Meze9S_CD_e8BuRNqcE:bdpckel) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/state_updater.h#L12)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

what about something like:
- TimeSteppingMap (or Mapper)

</blockquote></details>

Hmm, I like it better than `StateUpdater` but not so much I want to switch to that right away in this PR. Let's give it more thought and make the switch when moving out of dev?
___
*[multibody/fixed_fem/dev/state_updater.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezJ4Lz-DJDRWa4eRX9:-Mezkywm0HukKy7Ixpul:b-m8wm2e) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/state_updater.h#L67)):*
> there is an implicit assumption here, and that is that in general the map from unknowns z to state has the form:
> q̈ = αₐ z + bₐ
> q̇ = αᵥ z + bᵥ
> q = αₚ z + bₚ

Nicely characterized. I copypasted, thanks!

> since you have to say that you do it for a simple component i, and that it is the same for each component, etc, etc.

Technically I still have to say this since `(αₐ, αᵥ, αₚ)` really is a n-by-3 matrix. I'm happy to abuse notation here a little bit though.

**Review by amcastro-tri — COMMENTED** [review]
Thanks. I added a couple of comments, but they are all non-blocking.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15357#-:-Mf-XLvg4SxfaNZuwE-1:buuk9lo)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/fem_model.h, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezNjmO6ME8AaTY7sjX:-Mf-WiMVE0kniPUYIzWv:b13v9tp) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/fem_model.h#L64)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

No, I plan to have FemModel in `internal::` and `FemModelBase` outside of `internal::`. This will happen when they move out of dev. I'm also pondering a name change `FemModelBase` -> `FemModel` and `FemModel`->`FemModelImpl` (or something else) along the way.
</blockquote></details>

What about FemModelBase -> FemModel and FemModel -> FixedSizeFemModel? after all, when you inherit from FixedSizeFemModel (e.g. DynamicElasticityModel) you won't see `FixedSizeFemModel` anymore. Either you see the interface when you have a polymorphic pointer (i.e. a FemModel) or you see the most derived class when instantiating. 
___
*[multibody/fixed_fem/dev/state_updater.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezLOtNBNRSLVAhrAIe:-Mf-VCk_C53020nFtTcD:bkbe1ip) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/state_updater.h#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Hmm, I like it better than `StateUpdater` but not so much I want to switch to that right away in this PR. Let's give it more thought and make the switch when moving out of dev?
</blockquote></details>

yes, makes sense.
___
*[multibody/fixed_fem/dev/state_updater.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezJ4Lz-DJDRWa4eRX9:-Mf-VRZz-0fJGPjNKFTc:b-5ryrb5) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/state_updater.h#L67)):*
> (αₐ, αᵥ, αₚ) really is a n-by-3 matrix.

Humm... I always thought that each alpha was a scalar, and therefore (αₐ, αᵥ, αₚ) is always a 3d vector. 
___
*[multibody/fixed_fem/dev/state_updater.h, line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15357#-Mf-ViWF-IwUUJvMnWnj:-Mf-ViWF-IwUUJvMnWnk:bjfrfs2) ([raw file](https://github.com/robotlocomotion/drake/blob/df379596f3ec1ab47b848d8454de189e05cdb661/multibody/fixed_fem/dev/state_updater.h#L34)):*
> ```objc
>  With time discretization, one can express `q`, `q̇,` `q̈` in terms of a
>  single variable, which we dub the name "unknown" and denote it with `z`.
>  The mapping from `z` to the states usually takes the affine form
> ```

nit, You can remove the "usually" from here since we "always" assume this form.
___
*[multibody/fixed_fem/dev/state_updater.h, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15357#-Mf-VbUpB0Q-HH5JAHWf:-Mf-VbUpB0Q-HH5JAHWg:baz0v19) ([raw file](https://github.com/robotlocomotion/drake/blob/df379596f3ec1ab47b848d8454de189e05cdb661/multibody/fixed_fem/dev/state_updater.h#L69)):*
> If q̇ or q̈ are not a part of the state,
>  their derivatives are set to 0. 

sorry to pick on this. But saying "their derivatives are set to zero" is not quite correct. What happens is that they are no longer a function of z (since they are not even present in the state) and therefore the corresponding alpha coefficient is zero. But for cases where they do show up, e.g zero order hold, what happens is that alpha is zero because the particular state is no a function of z. Long story short, I think we can safely remove that last sentence since you already said everything in the constructor and here keep things simple to just stating "Returns (αₚ, αᵥ, αₐ)...)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15357)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/fem_model.h, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15357#-MezNjmO6ME8AaTY7sjX:-Mf-h1tv7ZlVZBvjJa_T:bkrelnw) ([raw file](https://github.com/robotlocomotion/drake/blob/2ba2a71096000cfb95e4959ade2f533d40975c58/multibody/fixed_fem/dev/fem_model.h#L64)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

What about FemModelBase -> FemModel and FemModel -> FixedSizeFemModel? after all, when you inherit from FixedSizeFemModel (e.g. DynamicElasticityModel) you won't see `FixedSizeFemModel` anymore. Either you see the interface when you have a polymorphic pointer (i.e. a FemModel) or you see the most derived class when instantiating. 
</blockquote></details>

Ok, SGTM.

**Pull request merged**
