### PR TITLE
Add RpyDtFromAngularVelocityInChild()

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19018)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR #19018 helps address issue #18984
[WIP] TODO(Mitiguy) : Add Python bindings for CalcRpyDtFromAngularVelocityInParent().

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-:-NQznnMx7JURnUqSQG2G:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending a few minor comments

Are you planning to add Python bindings here or in a separate PR?

+@ggould-tri for platform review per rotation, please

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-:-NR4AeLV7ovTv7lRySwj:b-5qdta5)* status: 7 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @mitiguy)

___
*[`math/roll_pitch_yaw.h` line 343 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR42BDCBE4p51DCI-nO:-NR42BDDCIhtm6A1gZtr:bltuagr) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L343)):*
> ```objc
>       const Vector3<T>& w_AD_D) const {
>     // Get the 3x3 M matrix containing the partial derivatives of [ṙ, ṗ, ẏ] with
>     // respect to [wx; wy; wz]ᴅ (which is w_AD_A expressed in "child" frame D).
> ```

typo: w_AD_A -> w_AD_D
___
*[`math/roll_pitch_yaw.h` line 348 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR44Cha2F3bvXUn12_y:-NR44Cha2F3bvXUn12_z:b-shjeyy) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L348)):*
> ```objc
>     // TODO(Mitiguy) Improve accuracy when `cos(p) ≈ 0`.
>     const Matrix3<T> M = CalcMatrixRelatingRpyDtToAngularVelocityInChild(
>         __func__, __FILE__, __LINE__);
> ```

BTW the FILE and LINE are irrelevant here and shouldn't have been included in the original code (they return internal file info, not the place in the user's code where the call was made). Only the `__func__` is user-meaningful. Please consider not propagating this error any further -- leave those out in new code and add a TODO to get rid of the old ones (or do it here).
___
*[`math/roll_pitch_yaw.h` line 622 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR43Wzt3D0muuTSg7-A:-NR43Wzt3D0muuTSg7-B:bfd3kfg) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L622)):*
> ```objc
>   // so it provides the ability to detect gimbal-lock and throws an error
>   // message that includes information from the calling function (rather than
>   // less useful information from within this method itself).
> ```

minor: this large block of text is repeated 8 times (I think, might have lost count). I see why you might want to repeat it for the similar public APIs, but it shouldn't be repeated again here. Just reference the public API comments instead. (Same for other private functions)
___
*[`math/roll_pitch_yaw.h` line 643 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR451iJ2mvMDKu6sHuZ:-NR451iJ2mvMDKu6sHu_:b-pukebm) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L643)):*
> ```objc
>   // so it provides the ability to detect gimbal-lock and throws an error
>   // message that includes information from the calling function (rather than
>   // less useful information from within this method itself).
> ```

minor: unnecessary rule-of-8 violation :) (don't need any of this repeated text)
___
*[`math/roll_pitch_yaw.h` line 645 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR45F6GE5jSkf-loFAB:-NR45F6GE5jSkf-loFAC:bg3ayim) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L645)):*
> ```objc
>   // less useful information from within this method itself).
>   Matrix3<T> CalcMatrixRelatingRpyDtToAngularVelocityInChild(
>       const char* function_name, const char* file_name, int line_number) const;
> ```

BTW don't propagate file/line mistake
___
*[`math/test/roll_pitch_yaw_test.cc` line 200 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR48jst59aJdiZ9gzgN:-NR48jst59aJdiZ9gzgO:bjzuty6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/test/roll_pitch_yaw_test.cc#L200)):*
> ```cpp
>   // ⌈ ṙ ⌉      ⌈ ωx ⌉          ⌈ cos(y)/cos(p)  sin(y)/cos(p)   0 ⌉
>   // | ṗ | = Np | ωy |     Np = |   −sin(y)          cos(y)      0 |
>   // ⌊ ẏ ⌋      ⌊ ωz ⌋ᴀ         ⌊ cos(y)*tan(p)   sin(y)*tan(p)  1 ⌋
> ```

minor: you spell out the details here for Np but not for Nc. Should treat both the same.
___
*[`math/test/roll_pitch_yaw_test.cc` line 207 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR49E9G8YWKhxItuAhU:-NR49E9G8YWKhxItuAhV:b-okm9k2) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/test/roll_pitch_yaw_test.cc#L207)):*
> ```cpp
> 
>   // Help verify Np by ensuring Np * Np_inv produces an identity matrix, where
>   // Np_inv is the matrix inverse of Np, (not just the pseudo inverse).
> ```

minor: this sounds like a tautology at first since M*M⁻¹=I for any M. But I see it might not be trivial here because you calculated the inverse separately. So I think you are double-checking that the computed Np is the inverse of a separately-computed Np_inv. Should explain that.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-:-NR4QUFA88TYMAxR0Sah:bnfp4nl)* status: 9 unresolved discussions (waiting on @mitiguy)

___
*[`math/roll_pitch_yaw.h` line 373 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR4Hx1L65t9GdEkia5e:-NR4Hx1L65t9GdEkia5f:blrq9j7) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L373)):*
> ```objc
>   /// For `this` %RollPitchYaw with roll-pitch-yaw angles `[r; p; y]` which
>   /// relate the orientation of two generic frames A and D, returns the 3x3
>   /// matrix M that contains the partial derivatives of [ṙ, ṗ, ẏ] with respect
> ```

typo possibly?  I'm confused as to why M would contain derivatives of ṙ, ṗ, ẏ, especially as two lines below we're talking about M relating rpyDt to w_AD_D.

Since this block is copy pasted a bunch, if it's not right then it's not right a whole lot.



_Suggestion:_
```objc
the partial derivatives [ṙ, ṗ, ẏ]
```
___
*[`math/roll_pitch_yaw.cc` line 172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR4Ij2770yXPrydNEfA:-NR4Ij2770yXPrydNEfB:b-n00gnd) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.cc#L172)):*
> ```cpp
>   const T sy_over_cp = sy * one_over_cp;
>   Matrix3<T> M;
>   // clang-format on
> ```

minor:  Was clang-format ever turned off, that it needs to be turned on here?
I'm a bit worried that clang-format isn't even running here (no `enable_clang_format_lint = True` in the BUILD file), but certainly the on-off sense seems to be a bit backward.



_Code quote:_
```cpp
clang-format on
```

**Comment by mitiguy** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please.

**Review by mitiguy — COMMENTED** [review]
@sherm1  and @ggould-tri   I think this may need another look as I subtracted a fair amount of comments and added some for clarification.

Note: I am getting a weird CI failure on one computer, so I am trying:
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please.

TODO(Mitiguy) : Add Python bindings for CalcRpyDtFromAngularVelocityInChild().

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-:-NRFgO0FCVrmpCcYneGL:b-el5lji)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @sherm1)

___
*[`math/roll_pitch_yaw.h` line 343 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR42BDCBE4p51DCI-nO:-NRAeSGoAUr-R2OGIlib:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L343)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: w_AD_A -> w_AD_D
</blockquote></details>

Done.
___
*[`math/roll_pitch_yaw.h` line 348 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR44Cha2F3bvXUn12_y:-NRAfuMB0Ig6QJcTk1Lb:b-pnkj6f) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L348)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the FILE and LINE are irrelevant here and shouldn't have been included in the original code (they return internal file info, not the place in the user's code where the call was made). Only the `__func__` is user-meaningful. Please consider not propagating this error any further -- leave those out in new code and add a TODO to get rid of the old ones (or do it here).
</blockquote></details>

Done (here and elsewhere).
___
*[`math/roll_pitch_yaw.h` line 373 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR4Hx1L65t9GdEkia5e:-NRAqCho10EaCyPwd4Wr:b-r1e7r) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L373)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

typo possibly?  I'm confused as to why M would contain derivatives of ṙ, ṗ, ẏ, especially as two lines below we're talking about M relating rpyDt to w_AD_D.

Since this block is copy pasted a bunch, if it's not right then it's not right a whole lot.
</blockquote></details>

I added text here and elsewhere which hopefully clarifies. 
___
*[`math/roll_pitch_yaw.h` line 622 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR43Wzt3D0muuTSg7-A:-NRAo7B04RMroEMXRkPs:bhv1ze8) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L622)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this large block of text is repeated 8 times (I think, might have lost count). I see why you might want to repeat it for the similar public APIs, but it shouldn't be repeated again here. Just reference the public API comments instead. (Same for other private functions)
</blockquote></details>

Done (fat reduction in a few places).
___
*[`math/roll_pitch_yaw.h` line 643 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR451iJ2mvMDKu6sHuZ:-NRAuJUs4vv2XmJ39zcB:b-q04d4h) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L643)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: unnecessary rule-of-8 violation :) (don't need any of this repeated text)
</blockquote></details>

Done.  Rule of "8" :)
___
*[`math/roll_pitch_yaw.h` line 645 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR45F6GE5jSkf-loFAB:-NRAuMRu8vWIoFycnFWj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.h#L645)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW don't propagate file/line mistake
</blockquote></details>

Done.
___
*[`math/roll_pitch_yaw.cc` line 172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR4Ij2770yXPrydNEfA:-NRFF5DX7k7Q6opKyTdB:b-j6y4z9) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/roll_pitch_yaw.cc#L172)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Was clang-format ever turned off, that it needs to be turned on here?
I'm a bit worried that clang-format isn't even running here (no `enable_clang_format_lint = True` in the BUILD file), but certainly the on-off sense seems to be a bit backward.
</blockquote></details>

Done.  I fixed the backward problem.  
I am unsure as to why clang-format did not catch this.
___
*[`math/test/roll_pitch_yaw_test.cc` line 200 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR48jst59aJdiZ9gzgN:-NRFGIif3HEJUvnSWe66:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/test/roll_pitch_yaw_test.cc#L200)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: you spell out the details here for Np but not for Nc. Should treat both the same.
</blockquote></details>

Done.
___
*[`math/test/roll_pitch_yaw_test.cc` line 207 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NR49E9G8YWKhxItuAhU:-NRFbtWe-ZCbyzydZaYo:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/20b955294732c256f5c76bbabdb66409f6114f07/math/test/roll_pitch_yaw_test.cc#L207)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this sounds like a tautology at first since M*M⁻¹=I for any M. But I see it might not be trivial here because you calculated the inverse separately. So I think you are double-checking that the computed Np is the inverse of a separately-computed Np_inv. Should explain that. 
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19018)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @mitiguy)

___
*[`math/roll_pitch_yaw.cc` line 235 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NRYp08f2tQqJyoT81h2:-NRYp08f2tQqJyoT81h3:b-rd4vwm) ([raw file](https://github.com/RobotLocomotion/drake/blob/25b6f6708b3c250fa4eb8b6b7a16fbfaf1472ebd/math/roll_pitch_yaw.cc#L235)):*
> ```cpp
>         " formed by the Quaternion passed to this method.  To avoid this"
>         " inconsistency, ensure the orientation of R and Quaternion align."
>         " ({}:{}).", __func__, tolerance);
> ```

This is apparently the source of the obscure CI error you're getting. There are four `{}` parameters in this format string but now only two arguments. (Thanks to Jeremy for showing me how to find this.)
___
*[`math/test/roll_pitch_yaw_test.cc` line 203 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NRYrGZoD2tMQXcQAFrC:-NRYrGZoD2tMQXcQAFrD:b-oeo1uz) ([raw file](https://github.com/RobotLocomotion/drake/blob/25b6f6708b3c250fa4eb8b6b7a16fbfaf1472ebd/math/test/roll_pitch_yaw_test.cc#L203)):*
> ```cpp
>       rpy.CalcMatrixRelatingRpyDtToAngularVelocityInParent();
> 
>   // Form the matrix Np relating ṙ, ṗ, ẏ to ω0, ω1, ω2, where frame D's angular
> ```

typo: Np -> Nc

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19018)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[`math/roll_pitch_yaw.cc` line 235 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NRYp08f2tQqJyoT81h2:-NRZk1DPDnzI8DDwnYHH:b-t7emem) ([raw file](https://github.com/RobotLocomotion/drake/blob/25b6f6708b3c250fa4eb8b6b7a16fbfaf1472ebd/math/roll_pitch_yaw.cc#L235)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This is apparently the source of the obscure CI error you're getting. There are four `{}` parameters in this format string but now only two arguments. (Thanks to Jeremy for showing me how to find this.)
</blockquote></details>

Done.  Thank you'all.
___
*[`math/test/roll_pitch_yaw_test.cc` line 203 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-NRYrGZoD2tMQXcQAFrC:-NRZjxt1CncfYHy_fFyD:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/25b6f6708b3c250fa4eb8b6b7a16fbfaf1472ebd/math/test/roll_pitch_yaw_test.cc#L203)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: Np -> Nc
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19018)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19018#-:-NRZwwzN4m5pUv4xiQrI:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @mitiguy)

**Pull request merged**
