### PR TITLE
First cut at some documentation for multibody notation

### PR DESCRIPTION
**Pull request by sherm1**
This adds a "Multibody Dynamics Concepts" module to Drake's Doxygen documentation, with subtopics covering terminology, notation, and spatial algebra.

My intention with this PR is just to create a place where we can accumulate and refine that material as we go. The initial text shows how to produce general documentation to which we can link from doxygen comments in code, and contains examples of tables and drawings that are readable in the source but still produce reasonable formatted output.

I don't want to haggle over the content in this PR -- if you want to make changes or additions, please do so in subsequent PRs. I would like to correct errors, and to know whether this seems like a good way to approach this kind of general documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4647)

### CODE REVIEW

**Comment by sherm1** [comment]
@amcastro-tri for feature review, @ggould-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-:-K_GdU9sNU-JF5McSfN8:b-bcw4im)*

**Comment by sherm1** [comment]
Er, I meant: +@amcastro-tri, +@ggould-tri!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-:-K_Gd_VPgl1S-rRiGIKU:bx5d45l)*

**Comment by sherm1** [comment]
BTW, by far the best way to review the text is to build the `documentation` target and then look at the formatted doxygen.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-:-K_GdoratfeQwg2hWFiI:b-iyitep)*

**Comment by amcastro-tri** [comment]
Wow! this looks very nice when built! Just a few BTW's. :lgtm_strong: 

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 94 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_H_oiCFu7iKxqi6TbO:-K_H_oiCFu7iKxqi6TbP:b-xd908i) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L94)):*
> that define how the quantity is to be defined

BTW, maybe "... that specify how the quantity is to be defined" so that "defined" is not repeated twice in the same sentence.

---

*[drake/multibody/multibody_doxygen.h, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HcfxDMogldmYARJG4:-K_HcfxDMogldmYARJG5:bqsx6q7) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L100)):*
> ```objc
> define that quantity we must know the target point P, and the reference frame F
> in which that point's velocity is to be measured. As a typeset symbol, we would
> write that quantity @f$ ^Fv^P @f$. Here v is the quantity type, the left
> ```

BTW, if you want to reduce the spacing between the left superscript and the main quantity, I've used in the past `\!` with good success (it reduces the horizontal spacing a bit).
Like so @f$ ^F\!v^P @f$

---

*[drake/multibody/multibody_doxygen.h, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HfZH0nvqR1rbAzLw_:-K_HfZH0nvqR1rbAzLwa:bijxgta) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L190)):*
> ```objc
> that body's frame or any other specified frame. Thus unambiguous notation for
> spatial vectors must specify both a point and an expressed-in frame. Motion
> quantities must also express the "fixed" frame with respect to which the motion
> ```

BTW, I dont thing "fixed" is needed here. Just "...the frame with respect to..."

---

*[drake/multibody/multibody_doxygen.h, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HiAg5zhZwiKfVbGtV:-K_HiAg5zhZwiKfVbGtW:b-5k9a1x) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L222)):*
> ```objc
>            ---------- ----------
>         3 |          |          |
>         4 |  -m c×   |    mE    |
> ```

BTW, I would personally prefer something like `Id` instead of `E`

---

*[drake/multibody/multibody_doxygen.h, line 229 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HiaOOAAu2lOg-rkyB:-K_HiaOPVCu73AbdcZ3e:b-yarxhx) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L229)):*
> ```objc
> The symbols in the figure have the following meanings, assuming we have a
> spatial inertia M for a body B, taken about a point P, and expressed in a
> frame F:
> ```

BTW, we don't need the "expressed in" notion when defining the spatial inertia. It is a physical quantity regardless of whether or not we decide to express it on a given frame.

---

*[drake/multibody/multibody_doxygen.h, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HiuF1lcKgO1f2emhQ:-K_HiuF2cWJ23g70CYna:b-q72nvr) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L240)):*
> ```objc
>    E   | 3×3 identity matrix
> 
> In practice the 36-element spatial inertia has only 10 unique elements, so we
> ```

10 independent elements

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-:-K_HjdJSBkyGUDjv8mOJ:b-j6pith)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647)*

**Comment by liangfok** [comment]
Overall this documentation is excellent. I do have one nit-picky comment: In the generated "Spatial Algebra" and "Terminology and Notation" modules, there is a "More..." link after the first sentence. This can be confusing because when a user clicks on this link, nothing appears to change.  In addition, it results in an odd reptition of text that shows up in the same screen, as shown below:

image3344


Can this "More..." link be disabled in these modules?

I also think it would be OK to disable the "More..." link after the first sentence in "Multibody Dynamics Concepts" and simply including the detailed description at the very top above the "Modules" section.

**Comment by liangfok** [comment]
Here is another nit-picky documentation-formatting comment: We cannot get a link to a subsection within a module without looking at the page's source, and once we get the link, it goes to the line just below the subsection's title resulting in the subsection's title not being visible in the browser. For example, suppose I want to get a direct link to the "Spatial Vectors" subsection of the "Spatial Algebra" module. I need to view the page's source to see that the direct link is `build/drake/doc/doxygen_cxx/html/group__multibody__spatial__algebra.html#multibody_spatial_vectors`. When I navigate to this section, the subsection's "Spatial Vectors" title is off the screen, as shown below.

screenshot from 2017-01-01 19-50-11

**Comment by sherm1** [comment]
Thanks, @liangfok. Regarding the unwanted `More...`, I agree it is awful. Any idea how to get Doxygen not to do that? It looks like we get that same effect everywhere but we only notice it for these pure-documentation things because there is no code documentation between the brief and the detailed description. Would it be reasonable to have all Doxygen display the detailed description first?

Regarding the links maybe I can place the anchors differently -- I'll play with it.

**Comment by sherm1** [comment]
@liangfok, I made more subgroups and I think that fixes the problem with links being hard to get (now you can just copy them from the Modules table of contents).

I still don't know what to do about the "More..."s though.

**Comment by sherm1** [comment]
Thanks you, @amcastro-tri! I have addressed all your comments and added a little more text, PTAL. 

Per your question about frame names a few days ago: writing this I was (mildly) sorry we didn't have "M" available for the "model" frame! In describing the left and right superscripts in the notation I called the left one the "reference" and the right one the "target". That made me wonder if we should be calling a joint's "fixed" frame its "reference" and its "moving" frame its "target" also. That would make frame "R" and "T" (with their own potential confusions) but would free up "F" and "M". I'm not suggesting a change, just mumbling at this point.

---

Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/doc/DoxygenLayout.xml, line 140 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_Swa2qebq6ld4Xa73n:-K_Swa2qebq6ld4Xa73o:b-5e5pcb) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba4a7510567e39057cd0a33717503e49b7f868a/drake/doc/DoxygenLayout.xml#L140)):*
> ```XML
>   
>   <group>
>     <briefdescription visible="no"/>
> ```

BTW, @liangfok this was the change I made -- "yes" to "no" for "group" (i.e. module) brief visibility.

---

*[drake/multibody/multibody_doxygen.h, line 94 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_H_oiCFu7iKxqi6TbO:-K_Qj1-6G3J9X7k3ymwJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L94)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> that define how the quantity is to be defined

BTW, maybe "... that specify how the quantity is to be defined" so that "defined" is not repeated twice in the same sentence.
</blockquote></details>

Done.

---

*[drake/multibody/multibody_doxygen.h, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HcfxDMogldmYARJG4:-K_Qo8-iRa1pJ8Lyqq6m:b-6lxywp) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L100)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, if you want to reduce the spacing between the left superscript and the main quantity, I've used in the past `\!` with good success (it reduces the horizontal spacing a bit).
Like so @f$ ^F\!v^P @f$
</blockquote></details>

Done -- thanks! I had mixed results where sometimes the symbols came out too close so I used it selectively.

---

*[drake/multibody/multibody_doxygen.h, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HfZH0nvqR1rbAzLw_:-K_QpBuKpLBBXrUsvvYk:b-552s2) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L190)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, I dont thing "fixed" is needed here. Just "...the frame with respect to..."
</blockquote></details>

Done. Changed to "reference" since I have been using that above.

---

*[drake/multibody/multibody_doxygen.h, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HiAg5zhZwiKfVbGtV:-K_Qp_deKzBF9NMS_orf:bc39c9w) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L222)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, I would personally prefer something like `Id` instead of `E`
</blockquote></details>

When "I" isn't available for an identity matrix I like "E" because it matches Matlab which uses "eye()" for identity and it is a fairly common choice. Wolfram [says](http://mathworld.wolfram.com/IdentityMatrix.html) "1", "I", or "E" and says E is an abbreviation for German Einheitsmatrix.

---

*[drake/multibody/multibody_doxygen.h, line 229 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HiaOOAAu2lOg-rkyB:-K_Qr7iY0rgiR2VSlAOA:bwpcfne) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L229)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, we don't need the "expressed in" notion when defining the spatial inertia. It is a physical quantity regardless of whether or not we decide to express it on a given frame.
</blockquote></details>

Done. (Clarified that expressed-in is only needed for numerical purposes.)

---

*[drake/multibody/multibody_doxygen.h, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HiuF1lcKgO1f2emhQ:-K_Qri8_JDJ-MrYh4fp8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L240)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

10 independent elements
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-:-K_Qrq5pyy7Y43ZYZtIG:b5ya0t4)*

**Comment by sherm1** [comment]
@liangfok, I believe I have fixed the "More..." problem. PTAL -- following Doxygen instructions I extracted its default "doxygen layout" file and modified "brief" visibility for groups. Please give this a try when you have a chance and let me know if you think it is fixed.

In general it is probably good for us to control the layout explicitly anyway. I don't know if this is the best way to do it but it seems functional.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-:-K_SwxsGxo93K96fnNWM:b-k3kk5g)*

**Comment by liangfok** [comment]
Yes, my comment about the "More..." link is resolved, thanks! Unfortunately, I am not a sufficiently experienced Doxygen guru to know whether your solution is "best practice", but it's certainly good enough for me. :smile:

Looking at the latest version, I have two new comments:

1. Can the collaboration diagram be disabled within the Multibody Dynamics Concepts module? It looks like the information it contains is now redundant with the Modules table that immediately follows it.

2. Can the Detailed Description section be positioned before the Modules section? Having the Detailed Description before the Modules section will provide better context for the information contained within the Modules section.

In addition to the above, I also noticed an odd set of characters at the bottom of the Spatial Algebra module, as shown below.



---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/DoxygenLayout.xml, line 140 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_Swa2qebq6ld4Xa73n:-K_UVn23cG1YWQzablcR:bksoznh) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba4a7510567e39057cd0a33717503e49b7f868a/drake/doc/DoxygenLayout.xml#L140)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, @liangfok this was the change I made -- "yes" to "no" for "group" (i.e. module) brief visibility.
</blockquote></details>

Great! This definitely resolves my "More..." link comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-:-K_UVzJSXcos2RLsq9yW:b-vcs8js)*

**Comment by ggould-tri** [comment]
:LGTM: This documentation is really excellently clear.  I confess I don't think I stand a chance of understanding the code written from this style, but I will at least have a clear, linkable reference in which to ground my confusion :smile:.

With regard to the formatting -- unfortunately, because we are in a boundary case, this is trying to use Doxygen to do Sphinx's job (that is, the tool we have that gives nice textbook-style presentation and formatting control is Sphinx) in order to get the pleasant `@ref`'ability of doxygen cross-links.  This is probably the best that can be done with this style.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 165 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_UdinszsE-VtKJZsOf:-K_Udint4rN4AoTmY9ZZ:b-zklpl) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba4a7510567e39057cd0a33717503e49b7f868a/drake/multibody/multibody_doxygen.h#L165)):*
> ```objc
> related rotational and translational quantities together than to treat them
> independently. We call such groupings *spatial* quantities.
>  
> ```

FYI, stray whitespace here.

---

*[drake/multibody/multibody_doxygen.h, line 176 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_Ud0-GicMeEdMzL4bm:-K_Ud0-GicMeEdMzL4bn:b-1iyqtu) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba4a7510567e39057cd0a33717503e49b7f868a/drake/multibody/multibody_doxygen.h#L176)):*
> ```objc
> 
> Spatial vectors are 6-element quantities that are pairs of ordinary 3-vectors.
> That is, Drake spatial vectors are logically elements of R³×R³, *not* R⁶; that
> ```

Huh, I hadn't realized Google style guide permitted utf-8 in source files.  Having re-read it -- I think this is one of the "rare" circumstances it is meant to permit.

I have verified that this is correctly handled by default by gcc.  I have not found recent clang documentation -- utf8 source was not supported by Clang in 2011, appears to have since become supported without being documented, and has minor open bugs related to error message generation.  I'm happy to call that good enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-:-K_U_YpRKcBKMFjv9Q7U:b-cenlc0)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647)*

**Comment by sherm1** [comment]
@liangfok, I fixed the spurious characters -- thanks! I *think* I prefer starting with the table of contents, and actually like the collaboration diagram at the top as a kind of visual TOC alternative, so will leave that for now. We can revisit doxygen formatting more globally later.

@ggould-tri, thank you very much for the holiday review!

All review comments addressed.

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_HiAg5zhZwiKfVbGtV:-K_VOm_uyH7mz5G3owje:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0485c3762a09ea55b23e2834e76978d18ca99bd/drake/multibody/multibody_doxygen.h#L222)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

When "I" isn't available for an identity matrix I like "E" because it matches Matlab which uses "eye()" for identity and it is a fairly common choice. Wolfram [says](http://mathworld.wolfram.com/IdentityMatrix.html) "1", "I", or "E" and says E is an abbreviation for German Einheitsmatrix.
</blockquote></details>

Done.

---

*[drake/multibody/multibody_doxygen.h, line 165 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-K_UdinszsE-VtKJZsOf:-K_VOWrIkyDUC479mFIl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba4a7510567e39057cd0a33717503e49b7f868a/drake/multibody/multibody_doxygen.h#L165)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI, stray whitespace here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4647#-:-K_VPrcyZfdofpur0MhV:b-uv67tm)*

**Pull request merged**
