### PR TITLE
Update LCM

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Towards #8155 
Getting [1](https://github.com/lcm-proj/lcm/pull/215), [2](https://github.com/lcm-proj/lcm/pull/222) in.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8788)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8788#-:-LCFWZdS0L96QArKEv1G:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@ggould-tri for platform review, please.

**Comment by ggould-tri** [comment]
I confirm that this is pulling HEAD from an upstream repository that has code review.
The upstream repository does not appear to have CI, so we can't wait for that and must rely on Drake CI.
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8788#-:-LCFaH_R0vELyS1RStNd:b-9f9mce)*

**Pull request merged**
