### PR TITLE
added systems::controllers:: namespace, moved zmp tests

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6658)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@ericcousineau-tri for feature and platform review, since it's strict git mv + namespace changes. thanks!

---

Review status: 0 of 47 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6658#-:-KpuSSnkyy0SknsNT0oS:b-f37vqc)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 50 of 50 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6658#-:-KpuZMv8bcWgXtOEi5BT:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for follow-up platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6658#-:-KpuZRWeMAQorLxddTfe:bb3gar8)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 50 of 50 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6658#-KpvLDlOdljz8UKJ3S0S:-KpvLDlQJA2TFveJG4zc:b-zgvvyt) ([raw file](https://github.com/robotlocomotion/drake/blob/c0cd73fb7cb6cfef90eed4f04d6ef61ab1b14d0e/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L101)):*
> ```cpp
>   systems::DiagramBuilder<double>* base_builder = builder.get_mutable_builder();
>   auto command_sub = base_builder->AddSystem(
>       systems::lcm::LcmSubscriberSystem::Make<lcmt_iiwa_command>("IIWA_COMMAND",
> ```

BTW this whole PR has more unrelated whitespace changes than I'd prefer to see.  I'll let it go here, but there's a point where I would block a PR for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6658#-:-KpvMcHz_XJoZmvjZ9yQ:bnfp4nl)*

**Pull request merged**
