### PR TITLE
[C-IRIS] Add bilinear alternation to CspaceFreePolytope.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18499)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18499#-:-NKPKSaW-ujY_xLt5Iel:b-kengf8)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18499#-:-NKQ6_1I1lQsFZcI1odR:bg7igkv)* status: 7 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 306 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18499#-NKQ3YOE3LFo6bNOqZ_t:-NKQ3YOF7Vx1otwo9drN:b-g8iy50) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c56afa1a5275376c87e692880907ef726bec2/geometry/optimization/dev/cspace_free_polytope.h#L306)):*
> ```objc
>   };
> 
>   /** Search the collision-free C-space polytope
> ```

nit grammar: Search for a collision-free C-space polytope
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 315 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18499#-NKQ3kgo7WS9SD8E637F:-NKQ3kgo7WS9SD8E637G:bigtyj1) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c56afa1a5275376c87e692880907ef726bec2/geometry/optimization/dev/cspace_free_polytope.h#L315)):*
> ```objc
>    @param C_init The initial value of C.
>    @param d_init The initial value of d.
>    @param search_margin If set to true, then we also maximize the separating
> ```

nit grammar: we also maximize the margin between the separating plane and the separated geometries
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 320 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18499#-NKQ3ube8FPdYuckSqtb:-NKQ3ube8FPdYuckSqtc:b-en455q) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c56afa1a5275376c87e692880907ef726bec2/geometry/optimization/dev/cspace_free_polytope.h#L320)):*
> ```objc
>    planes and Lagrangian multipliers.
>    @param options The options for the bilinear alternation.
>    @retval result If we successfully find the collision-free C-space polytope,
> ```

nit grammar: the -> a
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18499#-NKQ43go6lPZ9SjOX4G9:-NKQ43go6lPZ9SjOX4GA:b9hh00e) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c56afa1a5275376c87e692880907ef726bec2/geometry/optimization/dev/cspace_free_polytope.cc#L5)):*
> ```cpp
> #include <chrono>
> #include <future>
> #include <iostream>
> ```

I don't think you meant to keep this.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1340 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18499#-NKQ4Qq11efBzq4GbG2c:-NKQ4Qq11efBzq4GbG2d:blmmen6) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c56afa1a5275376c87e692880907ef726bec2/geometry/optimization/dev/cspace_free_polytope.cc#L1340)):*
> ```cpp
>     d_var(i) = symbolic::Variable("d" + std::to_string(i));
>     ellipsoid_margins(i) =
>         symbolic::Variable("ellip_margin" + std::to_string(i));
> ```

nit: spelling `ellipsoid_margin`
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1349 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18499#-NKQ4YOy5Nr5m05CofVI:-NKQ4YOy5Nr5m05CofVJ:b-6za75i) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c56afa1a5275376c87e692880907ef726bec2/geometry/optimization/dev/cspace_free_polytope.cc#L1349)):*
> ```cpp
>   const int gram_total_size_in_polytope_program =
>       this->GetGramVarSizeForPolytopeSearchProgram(ignored_collision_pairs);
>   // Find the inner ellipsoid.
> ```

nit: inner -> inscribed
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1397 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18499#-NKQ6To_0onwyg6JBGiy:-NKQ6To_0onwyg6JBGiz:b-hoy9nk) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c56afa1a5275376c87e692880907ef726bec2/geometry/optimization/dev/cspace_free_polytope.cc#L1397)):*
> ```cpp
>       ret->b = polytope_result->b;
>       ret->num_iter = iter;
>       // Now find the inner ellipsoid.
> ```

nit: inner ->inscribed

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18499)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18499#-NKQ43go6lPZ9SjOX4G9:-NKQSqvs6abJ2q3NaXGr:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c56afa1a5275376c87e692880907ef726bec2/geometry/optimization/dev/cspace_free_polytope.cc#L5)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I don't think you meant to keep this.
</blockquote></details>

Done. Good call.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18499)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
