### PR TITLE
[pydrake] Revert "Don't load native code upon 'import pydrake'"

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This partially reverts commits 9ff5cc1d (#15585) and 6d80c692 (#15589) -- some incidental improvements are kept intact (not reverted).

Since the time that code was written, our plans for how to deal with Drake's Python lcmtypes have evolved. The attempt to move lcmtypes into the same module as Drake itself is now much further down the line, and will be preceded by a much larger reorganization of the pydrake native code first (folding our modules down into a single shared library).

Maintaining the "no native code" invariant in the meantime is too difficult. In particular, we'd like to give better error messages when loading our native code fails, and having that in one place (in the top-level module) will make that job much easier. We can resurrect this test case (and invariant) when we circle back to changing the lcmtypes' packaging.

Remove the (internal use only) binding for `set_assertion_failure_to_throw_exception`.  We always want to do that as the first operation while loading pydrake.  We might as well just do that in the C++ code, no reason to weave it up into Python.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18141)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18141)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18141#-NElH1H90CapbL4fOyQS:-NElH1H90CapbL4fOyQT:b3fontx) (no related file):*
Working

Still needs a fix for the installed `drake-visualizer` module loading.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18141)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18141#-NElH1H90CapbL4fOyQS:-NElZg-NCTpeNoo8usoK:b9y6ish) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Still needs a fix for the installed `drake-visualizer` module loading.
</blockquote></details>

=> #18144

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18141)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18141#-NElH1H90CapbL4fOyQS:-NEpmyFz3gFb6WSsgoi5:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

=> #18144
</blockquote></details>

Done.

___

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please?  I'm OK if you want to defer review to someone else, but you get first refusal.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: on the feature - thanks for the explanation!

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18141#-:-NEqss7rBD5e7rJU7XqS:b-7yk8ft)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18141)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18141#-:-NErRX9EEnkgdQp4_Kyf:bnfp4nl)* status: missing label for release notes (waiting on @jwnimmer-tri)

**Pull request merged**
