### PR TITLE
Documentation on how to find and run a specific test

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR just adds documentation to the developers wiki on how to find and run a specific unit test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2186) &emsp; Multiple assignees:&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm: aside from minor comments, thanks for figuring this out and documenting it!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/developers.rst, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGINqsJ4TdEEDU0DfL0:-KGINqsJ4TdEEDU0DfL1:1457401801) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/developers.rst#L46)):*
not sure `how to find and run specific tests` needs to be boldface, but up to you.

---

*[drake/doc/developers.rst, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGINmovJwzgzct21Hl-:-KGINmovJwzgzct21Hl0:-1813268436) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/developers.rst#L48)):*
Extraneous - delete?

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOPEd3Fb7AdznIVjZ:-KGIOPEednR90GFOsojs:-685373897) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
Aha!  Awesome.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-:-KGIOSNxyWYAyGGK2_rc:2106480675)*

**Comment by liangfok** [comment]
Added my comments. Thanks for doing this.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/doc/developers.rst, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOBr05XdZGr845VNt:-KGIOBr05XdZGr845VNu:2019291845) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/developers.rst#L48)):*
Is the above line supposed to be there?

---

*[drake/doc/testing.rst, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOKJGhqnArFZCoTSL:-KGIOKJGhqnArFZCoTSM:1405441219) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L2)):*
Consider: "Detailed Notes on How to Run Unit Tests"

---

*[drake/doc/testing.rst, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOPjX06N3XITJdbdO:-KGIOPjX06N3XITJdbdP:-427301561) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L5)):*
"Test" --> "Unit Test"

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGIOUF2DoDhNbNxudaT:793458309) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
This will be be deprecated soon as we switch to out-of-source builds, which is necessary for compiling Drake on Windows.

Consider replacing with:

```
$ cd [drake build artifacts directory]
```

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOcxRR1Y9rpn1GYvW:-KGIOcxRR1Y9rpn1GYvX:450628067) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
I like to add a "$" in front of lines that represent commands.

---

*[drake/doc/testing.rst, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOl4nidoJsYgn-4KV:-KGIOl4nidoJsYgn-4KW:1610656790) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L13)):*
"clue about the unit test's name, which you can determine by looking at the CMakeLists.txt that included the unit test."

---

*[drake/doc/testing.rst, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOuTI7c0IDAOtcMSj:-KGIOuTI7c0IDAOtcMSk:-1851899018) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L19)):*
"Once you know the unit tests' name,..."

---

*[drake/doc/testing.rst, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOyoiQC41BHxsgjDl:-KGIOyoiQC41BHxsgjDm:1735232277) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L21)):*
Add "$" to beginning of line.

---

*[drake/doc/testing.rst, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIP2-oQSzc5UcG1Ivo:-KGIP2-oQSzc5UcG1Ivp:1465861364) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L26)):*
"test" --> "unit test named

---

*[drake/doc/testing.rst, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIP6SZmEXj00F-1Dng:-KGIP6SZmEXj00F-1Dnh:384210251) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L31)):*
Add "$" in front of commands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-:-KGIPIL7p9O7av8FlJ1V:-1316933938)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/doc/testing.rst, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIRib9X4MavOVsfnAd:-KGIRib9X4MavOVsfnAe:1491659638) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L23)):*
ouput->output

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/doc/developers.rst, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGINqsJ4TdEEDU0DfL0:-KGJCANmMucRPG01dItc:1073549054) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/developers.rst#L46)):*
I just thought it'd be useful to highlight it in case somebody was specifically looking how to do this (like me today). So yes, I do prefer bold

---

*[drake/doc/developers.rst, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGINmovJwzgzct21Hl-:-KGJDUvzGQfCuZxBMLwX:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/developers.rst#L48)):*
Done.

---

*[drake/doc/developers.rst, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOBr05XdZGr845VNt:-KGJDVo9sX81yYpp2Qn6:-727456343) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/developers.rst#L48)):*
You are both right. Sorry about that. Deleted

---

*[drake/doc/testing.rst, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOKJGhqnArFZCoTSL:-KGJE3K_w5xRTvi2Fjqs:-753974349) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L2)):*
Considered :-)

---

*[drake/doc/testing.rst, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOPjX06N3XITJdbdO:-KGJEinAYEnECki9eIQr:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L5)):*
Done.

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGJF05F9H7S3LqOuS3g:-937213694) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
I would leave it like this right now until that change happens. When next week I forget how to look for unit tests I can go to this page and see exactly how it is done. The same would apply to someone else with the same problem. When the out-of-source build kicks in my hope is that somebody using this deprecated documentation will then change it accordingly. Agree?

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOcxRR1Y9rpn1GYvW:-KGJFsKPstbYsZabJury:552053894) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
I think I agree however everywhere else in the wiki we don't use "$" for commands. Maybe worth considering the change in a separate PR?

---

*[drake/doc/testing.rst, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOl4nidoJsYgn-4KV:-KGJGcMPwB85jjApibv1:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L13)):*
Done.

---

*[drake/doc/testing.rst, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOuTI7c0IDAOtcMSj:-KGJGv8_JBTCq67NYTTw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L19)):*
Done.

---

*[drake/doc/testing.rst, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOyoiQC41BHxsgjDl:-KGJGpGJlrTFCCKhNuJo:-1180730276) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L21)):*
see answer to previous comment on this. 

---

*[drake/doc/testing.rst, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIRib9X4MavOVsfnAd:-KGJHMD0_AFmst87UZef:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L23)):*
Done.

---

*[drake/doc/testing.rst, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIP2-oQSzc5UcG1Ivo:-KGJH_wjpZswFx8Ygzh4:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L26)):*
Done.

---

*[drake/doc/testing.rst, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIP6SZmEXj00F-1Dng:-KGJHXuH08wWj-ioNmpE:-1532223715) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L31)):*
see previous answers on this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by amcastro-tri** [comment]
+@david-german-tri, actually +@liangfok figured it out, I just documented it :-). Thank you for the review guys!

---

Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-:-KGJIF4t2H91EQ7JS8Fk:2069033987)*

**Comment by liangfok** [comment]
:lgtm: Note that I just looked at the code without actually trying to compile it and view the compile results. Hopefully, the platform reviewer and/or gate keeper will do that before final acceptance.

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGJIhkqo1WJPhSCRxVV:-1014051775) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
Actually, the out-of-source builds already work. We just haven't documented it yet ;). But OK for updating this when we update the documentation on how to do out-of-source builds.

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOcxRR1Y9rpn1GYvW:-KGJIu84I1S9VeGDHYAi:160383661) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-:-KGJJLQXozecOKX09oJW:331182080)*

**Comment by sherm1** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGJv4Ai0M1yoAz3fFaC:400292936) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
On Windows there are no longer any pod-build directories at all; I don't think it is even an option. I didn't realize people were still using them on Linux. Better to put something generally applicable here I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGN8mJLvdEBfLCaj6El:-806474565) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
I agree with @sherm1. It's always better to post instructions that are generally applicable. Maybe another PR should be prepared that updates the build instructions to use out-of-source builds. Then both that PR and this PR can be merged in quick succession.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/doc/testing.rst, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGOPy0vkhIyJSFyW8Jl:-KGOPy0vkhIyJSFyW8Jm:-619694838) ([raw file](https://github.com/robotlocomotion/drake/blob/c0d6eb12bd735c3cdd2577bba991cd7d2a8694a9/drake/doc/testing.rst#L1)):*
Please add the following line at the top of this file so I can reference it from another file:

```
.. _unit-test-instructions:

```

Ideally, add similar anchor tags right before each section throughout this document.

See: http://docutils.sourceforge.net/docs/user/rst/quickref.html#internal-hyperlink-targets

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/doc/testing.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGOisXGZd2c5ohGJ9Hi:-36051301) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/testing.rst#L10)):*
I think @liangfok's original suggestion works, possibly along with a comment noting that the build artifact directory is `drake/pod-build` by default on Linux and Mac.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/unit_testing_instructions.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGS1WA888km0dUMzZ7P:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/unit_testing_instructions.rst#L10)):*
Done.

---

*[drake/doc/unit_testing_instructions.rst, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGOPy0vkhIyJSFyW8Jl:-KGS1VGVQIgq5Cx1i89f:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c0d6eb12bd735c3cdd2577bba991cd7d2a8694a9/drake/doc/unit_testing_instructions.rst#L1)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by sherm1** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/doc/unit_testing_instructions.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGSQTzC1h7E6HU2FnrC:-1755421651) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/unit_testing_instructions.rst#L10)):*
Still seems pod-build specific and doesn't mention what to do on Windows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/doc/unit_testing_instructions.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGSVlB_1OL37ZTs49hE:-799537771) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/unit_testing_instructions.rst#L10)):*
And it is. Correct me @liangfok if I am wrong but, are you going to updates this once your PR #2203 kicks in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by liangfok** [comment]
Reviewed 2 of 3 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/doc/unit_testing_instructions.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGSXNPqEocWVL2LqOe3:-1985567079) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/unit_testing_instructions.rst#L10)):*
Sure. I can issue another PR that completely wipes out the "pod-build" style of compiling.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/unit_testing_instructions.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGTbYfic-z37gPTWqHu:2041741139) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/unit_testing_instructions.rst#L10)):*
I just added some test regarding in/out of build. Hopefully this clarifies?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by liangfok** [comment]
Just one comment.

---

Reviewed 1 of 3 files at r3, 1 of 2 files at r4.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/unit_testing_instructions.rst, line 17 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGTeURzQhDtlNfdjU8Y:-KGTeURzQhDtlNfdjU8Z:576145161) ([raw file](https://github.com/robotlocomotion/drake/blob/538892156c26b4b9d2db23d3465e2f8bcb04339d/drake/doc/unit_testing_instructions.rst#L17)):*
I recommend moving this text to be immediately after where `path/to/your/build/artifacts/directory` is mentioned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-:-KGTedYbEbIJxXeB6uc8:-746171816)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/unit_testing_instructions.rst, line 17 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGTeURzQhDtlNfdjU8Y:-KGTsUEhxOIb5pdA3GYc:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/538892156c26b4b9d2db23d3465e2f8bcb04339d/drake/doc/unit_testing_instructions.rst#L17)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/unit_testing_instructions.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGIOUF2DoDhNbNxudaS:-KGTxOYcY80Fjeks6nZ4:-653996204) ([raw file](https://github.com/robotlocomotion/drake/blob/6f7cc9c6664809fbe00b73cbb9fbc6a7089e3dfb/drake/doc/unit_testing_instructions.rst#L10)):*
Yep. Looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-:-KGTxiK1UQDrLVhMH-Il:1417088721)*

**Comment by sherm1** [comment]
Ready to merge @david-german-tri.

**Comment by david-german-tri** [comment]
@amcastro-tri There are still some open Reviewable discussions.  I'll hold off merging until you've closed those and CI completes.

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/unit_testing_instructions.rst, line 15 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGU26RrBmOUN-Ht6BrZ:-KGU26RrBmOUN-Ht6Br_:803112354) ([raw file](https://github.com/robotlocomotion/drake/blob/f2fa0f01547ca94ee421e88a6e8ed02719821997/drake/doc/unit_testing_instructions.rst#L15)):*
Should there be a blank line between the line above and the line below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/unit_testing_instructions.rst, line 15 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGUeSlBoj9n2DH7ISuq:-KGUeSlBoj9n2DH7ISur:1692470971) ([raw file](https://github.com/robotlocomotion/drake/blob/f2fa0f01547ca94ee421e88a6e8ed02719821997/drake/doc/unit_testing_instructions.rst#L15)):*
To avid confusion between what's a real directory and what's not, change the paths to be:

In source builds:

```
[drake distro]/drake/pod-build
```

Out of source builds:

```
[drake build artifacts directory]/drake
```

I believe the use of square brackets to tell the user to fill in the blank is fairly common.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/unit_testing_instructions.rst, line 15 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGU26RrBmOUN-Ht6BrZ:-KGXgSSMgam_GTjM3OaL:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f2fa0f01547ca94ee421e88a6e8ed02719821997/drake/doc/unit_testing_instructions.rst#L15)):*
Done.

---

*[drake/doc/unit_testing_instructions.rst, line 15 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-KGUeSlBoj9n2DH7ISuq:-KGXhC7G8_0E9z0Lm2ZY:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f2fa0f01547ca94ee421e88a6e8ed02719821997/drake/doc/unit_testing_instructions.rst#L15)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 3 files at r3, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2186#-:-KGXkidm4F3Nub2u8LBN:-1868698381)*

**Comment by jwnimmer-tri** [comment]
Review is done (I override an un-ack'ed discussion from @david-german-tri that didn't seem like it should be a blocker) and jenkins passes; drake005 claims to be building, but is not relevant; I'm going to override-merge now due to out of date with master.

**Pull request merged**
