### PR TITLE
Add new constructor for symbolic::Monomial

### LINKED ISSUE #8977: New constructor for Monomial class
Take VectorX\<Variable\> and Eigen::VectorXi as input and construct a Monomial object.

Ex: 
```
Monomial( vars , exponent)

where vars = ("x", "y", "z") and exponent = (1,3,4).
```
The reverse operation (converting a Monomial to Eigen::VectorXi) would also be useful 
```
Ex:
x^2yz converts to (2,1,1)
```
as would the reverse operation that converts a Polynomial to a MatrixXi:
```
Ex:
xy^2z^3 + xz converts to    

(1, 2, 3
 1, 0, 1)
```

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #8977

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@frankpermenter for feature-review, please.

BTW, I think there is no performance gain of implementing the reverse operations inside of the classes (`Monomial`, `Polynomial`).

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983#-:-LEukCxB4i82Sqh31HjD:b223dta)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

---

Review status: all discussions resolved, LGTM missing from assignee frankpermenter, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983#-:-LExsyfE9HPBFHUN3Mbc:bwqgz7o)*

**Comment by frankpermenter** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee frankpermenter, platform LGTM missing

---

*[common/symbolic_monomial.cc, line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8983#-LEzCUTB7PSW4NyadzsH:-LEzCUTC9y4-D3cLoF1H:b7ceu98) ([raw file](https://github.com/robotlocomotion/drake/blob/47b93142977c2300e0d5e17f6cd334d4b7e0460b/common/symbolic_monomial.cc#L91)):*
> ```cpp
>   map<Variable, int> powers;
>   for (int i = 0; i < vars.size(); ++i) {
>     if (exponents[i] > 0.0) {
> ```

Slightly confusing to compare an integer with 0.0 instead of 0. I would update comparison to (exponents[i] > 0)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983)*

**Comment by soonho-tri** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee frankpermenter, platform LGTM missing

---

*[common/symbolic_monomial.cc, line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8983#-LEzCUTB7PSW4NyadzsH:-LEzL6wG4X_IukPcokR8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/47b93142977c2300e0d5e17f6cd334d4b7e0460b/common/symbolic_monomial.cc#L91)):*
<details><summary><i>Previously, frankpermenter wrote…</i></summary><blockquote>

Slightly confusing to compare an integer with 0.0 instead of 0. I would update comparison to (exponents[i] > 0)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983)*

**Comment by frankpermenter** [comment]
:lgtm:

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983#-:-LEzsiJh20FyJGpTqFGM:bnfp4nl)*

**Comment by sherm1** [comment]
Platform :lgtm: with a few "considers".

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: 1 unresolved discussion, platform LGTM from [sherm1]

---

*[common/symbolic_monomial.cc, line 94 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8983#-LF-PqlhCJ-0PYKGVtdR:-LF-Pqli1oDvZn9E4eEq:b31z7zw) ([raw file](https://github.com/robotlocomotion/drake/blob/bf120017f8ab9031f74a1fb8e787bf6a9ca64b5e/common/symbolic_monomial.cc#L94)):*
> ```cpp
>       powers.emplace(vars[i], exponents[i]);
>     } else if (exponents[i] < 0) {
>       throw std::runtime_error("The exponent is negative.");
> ```

FYI consider std::logic_error

---

*[common/test/symbolic_monomial_test.cc, line 154 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8983#-LF-QZVb3_TEbU7MO6Se:-LF-QZVb3_TEbU7MO6Sf:blhnm4t) ([raw file](https://github.com/robotlocomotion/drake/blob/bf120017f8ab9031f74a1fb8e787bf6a9ca64b5e/common/test/symbolic_monomial_test.cc#L154)):*
> ```cpp
>   // [x, y, z] * [2, 0, -1] => Exception!
>   EXPECT_THROW(Monomial(vars_xyz, Eigen::Vector3i(2, 0, -1)),
>                std::runtime_error);
> ```

Minor: consider using DRAKE_EXPECT_THROWS_MESSAGE() to make this test more specific.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983#-:-LF-QlTaEmgmYCSTQlo5:b82ur7d)*

**Comment by soonho-tri** [comment]
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sherm1]

---

*[common/symbolic_monomial.cc, line 94 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8983#-LF-PqlhCJ-0PYKGVtdR:-LF1V0GW-6WiK6wQNCCA:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/bf120017f8ab9031f74a1fb8e787bf6a9ca64b5e/common/symbolic_monomial.cc#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI consider std::logic_error
</blockquote></details>

Done

---

*[common/test/symbolic_monomial_test.cc, line 154 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8983#-LF-QZVb3_TEbU7MO6Se:-LF1V18C4yr2NnX9ZTxH:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/bf120017f8ab9031f74a1fb8e787bf6a9ca64b5e/common/test/symbolic_monomial_test.cc#L154)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Minor: consider using DRAKE_EXPECT_THROWS_MESSAGE() to make this test more specific.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983)*

**Comment by soonho-tri** [comment]
@sherm1 , thanks for the review!. Could you check the latest changes and merge it if they are good?

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [sherm1]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983#-:-LF2njLD9Q8ERbKPPgIY:bossiqj)*

**Comment by sherm1** [comment]
Reviewed 4 of 4 files at r3.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sherm1]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8983)*

**Pull request merged**
