### PR TITLE
Revert "Pull in the `fmt` string formatting library as a proper external dependency...."

### PR DESCRIPTION
**Pull request by liangfok**
Dear @maddog-tri,

The on-call build cop, @liangfok, believes that your PR #5607 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-clang-continuous-minimal-debug/1344/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-clang-continuous-minimal-release/1341/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-clang-ninja-continuous-minimal-debug/1328/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-clang-ninja-continuous-minimal-release/1334/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5616)

### CODE REVIEW

**Comment by liangfok** [comment]
Here is the error:

```
19:32:04 dyld: Library not loaded: libfmt.3.dylib
19:32:04   Referenced from: /Users/elcapitan/workspace/mac-clang-ninja-continuous-minimal-debug/build/drake/common/test/is_approx_equal_abstol_test
19:32:04   Reason: image not found
```

**Comment by liangfok** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please.

**Comment by jwnimmer-tri** [comment]
:lgtm: assuming the 60 minute timeout passes without a fix-forward.

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
All pre-merge checks passed and this PR was issued more than an hour ago. Merging...

**Pull request merged**
