### PR TITLE
Proposed: Require in-class member initializers to avoid uninitialized memory

### PR DESCRIPTION
**Pull request by sherm1**
Adds a second "additional rule" to the style guide requiring the use of in-class member initializers for non-static data members that would otherwise be left as uninitialized garbage. (Came up in [PR #2207 review](https://github.com/RobotLocomotion/drake/pull/2207#issuecomment-217664329).)

Also fixes some minor formatting errors and Sphinx whining.

Please comment if you don't think we should enforce this rule. Otherwise, @jwnimmer-tri platform review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2310)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHRFBlh9TWnBsUsxVWX:-KHRFBlh9TWnBsUsxVWY:-1955329219) ([raw file](https://github.com/robotlocomotion/drake/blob/8513c37e57a19cbf5af62bf102efe588fc76c678/drake/doc/code_style_guide.rst#L51)):*
> ```reStructuredText
> 
> * Use the ``GTEST`` prefix in unit test declarations.  For instance, use ``GTEST_TEST(Group, Name)`` instead of ``TEST(Group, Name)``. (`#2181 <https://github.com/RobotLocomotion/drake/issues/2181>`_)
> * Always use `in-class member initialization <http://www.stroustrup.com/C++11FAQ.html#member-init>`_ for data members that would otherwise be uninitialized, such as ints and pointers. The syntax ``int i{};`` (called "value initialization") ensures that numeric and pointers types are zero-initialized rather than left as garbage.
> ```

Please clarify what this means for types where the default constructor does not initialize its data, such as fixed-dimension Eigen members.  I think the two sensible choices are (1) _don't use {} on fixed-size Eigens because it's a misleading no-op_, or (2) _use {Zero} on Eigens to make them zero_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310)*

**Comment by sherm1** [comment]
*[drake/doc/code_style_guide.rst, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHRFBlh9TWnBsUsxVWX:-KHRgtVqS1GJFwxpe6k1:-264895003) ([raw file](https://github.com/robotlocomotion/drake/blob/8513c37e57a19cbf5af62bf102efe588fc76c678/drake/doc/code_style_guide.rst#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Please clarify what this means for types where the default constructor does not initialize its data, such as fixed-dimension Eigen members.  I think the two sensible choices are (1) _don't use {} on fixed-size Eigens because it's a misleading no-op_, or (2) _use {Zero} on Eigens to make them zero_.</details>
Clarified. This rule only need apply to built-in types because it will apply recursively to any classes we make ourselves. External class objects, including Eigen's, have their own initialization behavior that is necessarily exempt from this rule. I did explain how to get Eigen members zero-initialized, but we shouldn't require that.

I also figured out how to use 80 character lines in Sphinx which would make reviewing small changes much easier. I reformatted this section but no, sorry, I'm not going to reformat the rest of the file in this PR!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310)*

**Comment by liangfok** [comment]
Left some minor comments.

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> #### Proposed: Require in\-class member initializers to avoid uninitialized memory
> 
> Adds a second "additional rule" to the style guide requiring the use of in-class member initializers for non-static data members that would otherwise be left as uninitialized garbage. (Came up in [PR #2207 review](https://github.com/RobotLocomotion/drake/pull/2207#issuecomment-217664329).)
> 
> 
> 
> Also fixes some minor formatting errors and Sphinx whining.
> 
> 
> 
> Please comment if you don't think we should enforce this rule. Otherwise, @jwnimmer-tri platform review, please.
> 
> 
> </details>


---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/doc/code_style_guide.rst, line 53 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSCjXB1X7AHtToKrHg:-KHSCjXB1X7AHtToKrHh:718014150) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L53)):*
> ```reStructuredText
>   (`#2181 <https://github.com/RobotLocomotion/drake/issues/2181>`_)
> * Always use `in-class member initialization
>   <http://www.stroustrup.com/C++11FAQ.html#member-init>`_ for built-in data
> ```

Consider making "build-in data types" a link to: http://en.cppreference.com/w/cpp/language/types

That would be even more clear than the list at the end of this sentence, though I think the list is good and should stay.

---

*[drake/doc/code_style_guide.rst, line 57 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSCzknnJf1FtOR1t0j:-KHSCzknnJf1FtOR1t0k:-2062826241) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L57)):*
> ```reStructuredText
>   pointers, and enumerations. The syntax ``int count_{};`` (called `value
>   initialization`) ensures that these types are zero-initialized rather than
>   left as garbage. You may also provide explicit values such as
> ```

Should "left as garbage" be "left with unknown values initially"?

The word "garbage" is loaded since in languages that support garbage collection, memory containing "garbage data" will be freed so it can be reused by some other variable in the future.

---

*[drake/doc/code_style_guide.rst, line 61 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSDt7qk4gP6xJab-GT:-KHSDt7qk4gP6xJab-GU:697795584) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L61)):*
> ```reStructuredText
>   (because zero is the wrong initial value). You should always provide a
>   value for ``enum`` members since zero might not be one of the allowed
>   enumerations. Class objects are responsible for their own construction so
> ```

"so do" -> "so they do"

---

*[drake/doc/code_style_guide.rst, line 63 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSEcaSnPM26wfi5pF0:-KHSEcaSnPM26wfi5pF1:-849716046) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L63)):*
> ```reStructuredText
>   enumerations. Class objects are responsible for their own construction so
>   do not need to be member-initialized, but you can do so if the default
>   constructor does not provide the behavior you want. Note that fixed-size
> ```

What is the syntax for member initializing a class if not all of the class' member variables are initialized by parameters in the class' constructor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-:-KHSEyI6neXqG6UuDG2t:-938406953)*

**Comment by jwnimmer-tri** [comment]
Platform :lgtm: with 1 optional suggestion.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Left some minor comments.</details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/doc/code_style_guide.rst, line 56 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSmsev_4r6Sne1wrmN:-KHSmsev_4r6Sne1wrmO:-853860054) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L56)):*
> ```reStructuredText
>   types that would would otherwise be uninitialized, including numerical types,
>   pointers, and enumerations. The syntax ``int count_{};`` (called `value
>   initialization`) ensures that these types are zero-initialized rather than
> ```

Consider linking to http://en.cppreference.com/w/cpp/language/value_initialization for further reading.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-:-KHSn0YS_DEgi-kjb1Ni:592877319)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310)*

**Comment by sherm1** [comment]
All suggestions done or addressed.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Platform :lgtm: with 1 optional suggestion.</details>


---

Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 53 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSCjXB1X7AHtToKrHg:-KHTGZxhVZcXnrXOcghN:1881725921) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L53)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Consider making "build-in data types" a link to: http://en.cppreference.com/w/cpp/language/types
> 
> That would be even more clear than the list at the end of this sentence, though I think the list is good and should stay.</details>
Hmmm. That link looks exhaustive but actually doesn't include enums. I think I'll leave it slightly vague here unless there is a way to be precise. fundamental and enumerated types maybe?

---

*[drake/doc/code_style_guide.rst, line 56 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSmsev_4r6Sne1wrmN:-KHTFznFc0rY7RtQDW6V:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Consider linking to http://en.cppreference.com/w/cpp/language/value_initialization for further reading.</details>
Done.

---

*[drake/doc/code_style_guide.rst, line 57 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSCzknnJf1FtOR1t0j:-KHTEpj6Kot4LcUszgG7:1162401301) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L57)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should "left as garbage" be "left with unknown values initially"?
> 
> The word "garbage" is loaded since in languages that support garbage collection, memory containing "garbage data" will be freed so it can be reused by some other variable in the future.</details>
Sigh. Of course you're right, Liang -- it's just more fun to write like this! I changed it to something more civilized, while attempting to leave it a little fun.

---

*[drake/doc/code_style_guide.rst, line 61 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSDt7qk4gP6xJab-GT:-KHTFn2knOLF4BEEyvMJ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "so do" -> "so they do"</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-:-KHTH6UdUUTwrdSUggzC:-108486577)*

**Comment by liangfok** [comment]
:lgtm_strong: 

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> All suggestions done or addressed.</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 53 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSCjXB1X7AHtToKrHg:-KHUTZHoFnJtFTebmQlq:359715750) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Hmmm. That link looks exhaustive but actually doesn't include enums. I think I'll leave it slightly vague here unless there is a way to be precise. fundamental and enumerated types maybe?</details>
How about "primitive and enumerated types"?

Can structs also have in-class member initialization?

---

*[drake/doc/code_style_guide.rst, line 57 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSCzknnJf1FtOR1t0j:-KHUToSu2ZBUHpf9EvLI:-1924440368) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L57)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Sigh. Of course you're right, Liang -- it's just more fun to write like this! I changed it to something more civilized, while attempting to leave it a little fun.</details>
Sorry to be so boring! The new text :lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-:-KHUTzxFF3l20RN9eqT7:-1868698381)*

**Comment by jwnimmer-tri** [comment]
Platform :lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> :lgtm_strong: </details>


---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-:-KHUinejeqoi0y5pCjF0:528945684)*

**Comment by sherm1** [comment]
*[drake/doc/code_style_guide.rst, line 53 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSCjXB1X7AHtToKrHg:-KHVPIR_miHZ6THXS-WO:1121165177) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L53)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> How about "primitive and enumerated types"?
> 
> Can structs also have in-class member initialization?</details>
"primitive" doesn't appear to be part of the C++ standard terminology - [here](http://en.cppreference.com/w/cpp/language/type) is the classification. Looks like "fundamental", "enumeration", and probably "array" types should be included here. I think we have enough text for now; let's see how this plays out in practice and then revise.

structs and classes are the same thing in C++ except for private vs. public default  and style conventions. So yes, anything you can do in a class you can do in a struct. However, as for a class it should be up to the struct to handle its own initialization so that users of the struct don't have to do it repeatedly, and so that subsequent internal changes to the struct don't break user code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310)*

**Comment by liangfok** [comment]
*[drake/doc/code_style_guide.rst, line 53 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2310#-KHSCjXB1X7AHtToKrHg:-KHVSoTAZioeJN38vZFa:-267110867) ([raw file](https://github.com/robotlocomotion/drake/blob/c4622962710b44a22e16605387a3b4ed7431538a/drake/doc/code_style_guide.rst#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "primitive" doesn't appear to be part of the C++ standard terminology - [here](http://en.cppreference.com/w/cpp/language/type) is the classification. Looks like "fundamental", "enumeration", and probably "array" types should be included here. I think we have enough text for now; let's see how this plays out in practice and then revise.
> 
> structs and classes are the same thing in C++ except for private vs. public default  and style conventions. So yes, anything you can do in a class you can do in a struct. However, as for a class it should be up to the struct to handle its own initialization so that users of the struct don't have to do it repeatedly, and so that subsequent internal changes to the struct don't break user code.</details>
Ah, OK. I come from a Java background where the term "[primitive type](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html)" is used. I agree to go with the current text and revise as necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2310)*

**Pull request merged**
