### PR TITLE
Add Vim page to Sphinx documentation.

### PR DESCRIPTION
**Pull request by avalenzu**
Also adds a basic config file to get people up and running.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741)

### CODE REVIEW

**Comment by thduynguyen** [comment]
Thanks for the awesome PR!

Comments below. I failed to get `YouCompleteMe` working on my Mac. Haven't tested on Ubuntu yet.

In general, I think `YouCompleteMe` and any other packages/settings which are purposely tailored for `Drake` source code, e.g. `CtrlP`, are super useful. However, all other settings/themes/key mappings should not be enforced and should be omited as vim users usually have their own personal key mappings/settings, which they have been using for years, and it might be difficult to adapt to this `.vimrc`.

This current style of setup `.vimrc` is suitable for novice vim users, however. So I think `basic_init.vim` should still be there for those who prefer to use it. But I think there should be a specific section that highlights the settings that are needed and specifically tailored to work with `bazel` and `Drake` source code, e.g. `YouCompleteMe`, `CtrlP`, etc., so intermediate and expert users can pull them into their current vim setup easily. For that purpose, I think the `basic_init.vim` in `Drake` should be minimal, include `Drake` specific settings and only serve as a reference/example for people to copy/paste into their own `.vimrc`. If we decide to put the full complete `.vimrc` in there, at least the `Drake` specific parts should be highlighted better.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[doc/vim.rst, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LBZye7C9aUaLvRD-FGl:-LBZye7C9aUaLvRD-FGm:b-cra1pf) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L32)):*
> ```reStructuredText
> ===================
> 
> Save ``basic_init.vim`` (:download:`download <basic_init.vim>`) to ``~/.vimrc``
> ```

Should it be `drake/doc/basic_init.vim`?  It's not immediate for me at my first try.
Also, we should remind users to back-up their current `~/.vimrc`. 
I haven't tried with `neovim`. What's the `:download:` for? Is it a `neovim` command or something?

---

*[doc/vim.rst, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_-HGN0eiNMrRSWw41:-LB_-HGN0eiNMrRSWw42:bl6r9mw) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L38)):*
> ```reStructuredText
> Now we need to setup the plugins specified in ``.vimrc`` (``init.vim``). Open a
> terminal and run vim. (NOTE: You will get an error message about the color
> scheme not being found. This is because the plugin that supplies the color
> ```

The color scheme shouldn't be a default, so the error could be avoided.

---

*[doc/vim.rst, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_-Q3k32pEoVWpbqzi:-LB_-Q3k32pEoVWpbqzj:b-9fqzqp) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L40)):*
> ```reStructuredText
> scheme not being found. This is because the plugin that supplies the color
> scheme hasn't been installed yet. You're about to install it now.) In vim, type
> ``:PlugInstall`` and press Enter. The plugin manager (`VimPlug
> ```

There should be an instruction or some comments for uninstall. This is so that novice users like me feel confident to try `vim-plug`.

---

*[doc/vim.rst, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_1EQS1ZkoJAdK14gX:-LB_1EQS1ZkoJAdK14gY:b9leyp7) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L66)):*
> ```reStructuredText
> 
>    1. Download the bazel-compilation-database 0.2.2
>       `tarball <https://github.com/grailbio/bazel-compilation-database/archive/0.2.2.tar.gz>`_.
> ```

On Mac: `command not found: tarball`. Try Homebrew: `No formula found for tarball`.

---

*[doc/vim.rst, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_3_Gr1c0vda4BDSeL:-LB_3_Gs9HTUOUGbCa5-:b-s68auw) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L68)):*
> ```reStructuredText
>       `tarball <https://github.com/grailbio/bazel-compilation-database/archive/0.2.2.tar.gz>`_.
>    2. Extract the contents of the tarball to some directory. We will refer to
>       this directory as ``<bcd-location>``.
> ```

Can we extract to `drake/bazel/compilation_database` directly? This would help remove the `ln -s` step below.

---

*[doc/vim.rst, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_49tf9yktBkJR1-B6:-LB_49tf9yktBkJR1-B7:b4k82q9) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L79)):*
> ```reStructuredText
> 
> Now, when you open a Drake C++ file, you should get real-time linting,
> completion, and jump-to-declaration functionality. If it appears not to be
> ```

How do I tell if these functionalities works or not?  What behaviors should I expect?

---

*[doc/vim.rst, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_7-U69UzdhiPikd2R:-LB_7-U69UzdhiPikd2S:b9u5p0p) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L80)):*
> ```reStructuredText
> Now, when you open a Drake C++ file, you should get real-time linting,
> completion, and jump-to-declaration functionality. If it appears not to be
> working, try running `:YcmDiags` to force YouCompleteMe to compile the current
> ```

I tried `:YcmDiags` but it doesn't seem to pickup header files correctly. Lots of errors.

---

*[doc/vim.rst, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_7H87247Ck1SRRpQR:-LB_7H87247Ck1SRRpQS:b-1cwcjm) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L92)):*
> ```reStructuredText
> course, change <leader> to whatever you prefer in your ``.vimrc`` (``init.vim``) file.
> 
> Navigation Mappings
> ```

I don't think these are needed. Should it just be an optional recommendation?

---

*[doc/vim.rst, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_7inl0FLI1XkALeZg:-LB_7inl0FLI1XkALeZh:bnj7hl0) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L101)):*
> ```reStructuredText
>  - <leader>L switch to the window to the right of  the current window.
> 
> Git Mappings
> ```

same as above

---

*[doc/vim.rst, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_7z9CEGS-DyWyyl6n:-LB_7z9CEGS-DyWyyl6o:b25tgux) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L114)):*
> ```reStructuredText
>    commits, switch branches, cherry-pick, and more
> 
> Linting and Jump-to-Declaration Mappings
> ```

This should go right after the paragraph on line 81.

---

*[doc/vim.rst, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_84kdATa5enGenzQb:-LB_84kdATa5enGenzQc:b-s3hmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L126)):*
> ```reStructuredText
>    make it easy to go from one to the next.
> 
> File Tree Explorer Mappings
> ```

Not needed.

---

*[doc/vim.rst, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_861x6qLPSSSkOgvk:-LB_861x6qLPSSSkOgvl:b-s3hmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L136)):*
> ```reStructuredText
>    given source file.
> 
> Fuzzy Finder Mappings
> ```

Not needed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741#-:-LB_89pGBm4IasTo7z_E:b-nz1ngu)*

**Comment by avalenzu** [comment]
Thanks for the review, @thduynguyen! Two points before I respond to individual comments:

- Could I ask you to checkout the PR branch and run `bazel run //doc:serve_sphinx`? This will build and launch a local copy of our Sphinx documentation. From the home page that should show up in your browser click "For Developers" ,  then "IDE and Text Editor Notes", and finally "Vim/Neovim Notes." That will take you to the rendered version of `vim.rst`. I think this will address some of your comments (like what `:download:` is for).
- Re. how much should go in `basic_init.vim`: My take on this is that long-time vim users will be very comfortable cherry-picking whatever portions they want out of `basic_init.vim`, while novice users will want something that works out of the box. Therefore, I think it's appropriate that `basic_init.vim` be tailored to novice users. However, you're right that I've probably included too much in there.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741#-:-LBa0-HR3jzaGsC4juz1:bqo446v)*

**Comment by hongkai-dai** [comment]
My take is that we can put any useful settings in `basic_init.vim`, as long as they do not contradict to each other. I guess novice users would not choose vim as the editor for drake, but instead will choose CLion or other IDEs. So I personally treat `basic_init.vim` as a reference, and just cherry pick from it. Maybe @avalenzu could add a comment on top of `basic_init.vim`, that the experienced users can freely cherry-pick some portions to their `.vimrc`.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741#-:-LBaSnRfBiSbnipEiQcs:b-v9msk1)*

**Comment by ggould-tri** [comment]
Okay, I'll give this platform :lgtm: because it looks logically sound and well-formed; the question of whether it is actually a good feature is a feature review matter (and waaay beyond my expertise), and it seems like there's a good discussion underway for that.

Honor and glory to @thduynguyen for jumping in on this review with some great feedback!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741#-:-LBa_2Rw5N1Ln5byvfnL:b-l7vw9t)*

**Comment by avalenzu** [comment]
Addressed reviewer comments. This led to a fairly substantial re-ordering/re-commenting of the sample configuration file. @thduynguyen and @hongkai-dai PTAL.

---

Reviewed 1 of 4 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[doc/vim.rst, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LBZye7C9aUaLvRD-FGl:-LBayt5-5Gw32KoRMfbS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L32)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

Should it be `drake/doc/basic_init.vim`?  It's not immediate for me at my first try.
Also, we should remind users to back-up their current `~/.vimrc`. 
I haven't tried with `neovim`. What's the `:download:` for? Is it a `neovim` command or something?
</blockquote></details>

Done.

---

*[doc/vim.rst, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_-HGN0eiNMrRSWw41:-LBaz0gWAC1n6cZyOasU:b-fykgwe) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L38)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

The color scheme shouldn't be a default, so the error could be avoided.
</blockquote></details>

Error no longer occurs.

---

*[doc/vim.rst, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_-Q3k32pEoVWpbqzi:-LBaz7xa692cPG249kb8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L40)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

There should be an instruction or some comments for uninstall. This is so that novice users like me feel confident to try `vim-plug`.
</blockquote></details>

Done.

---

*[doc/vim.rst, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_1EQS1ZkoJAdK14gX:-LBa_UDg2-F5dYYOtiAb:b-hqc643) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L66)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

On Mac: `command not found: tarball`. Try Homebrew: `No formula found for tarball`.
</blockquote></details>

"tarball" is the link text when this file is rendered by Sphinx.

---

*[doc/vim.rst, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_3_Gr1c0vda4BDSeL:-LBaz9XI-8HmmCeHohNL:b-e361w8) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L68)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

Can we extract to `drake/bazel/compilation_database` directly? This would help remove the `ln -s` step below.
</blockquote></details>

You could,  and that would be more straightforward for working with a single repo. However, with this setup, you can do step 3 in *any* repo and automatically get YouCompleteMe up and running.

---

*[doc/vim.rst, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_49tf9yktBkJR1-B6:-LBazeV63HA_-6rlXn4s:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L79)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

How do I tell if these functionalities works or not?  What behaviors should I expect?
</blockquote></details>

Done.

---

*[doc/vim.rst, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_7-U69UzdhiPikd2R:-LBa_ngp5su8c7xSh5uX:b-63fffk) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L80)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

I tried `:YcmDiags` but it doesn't seem to pickup header files correctly. Lots of errors.
</blockquote></details>

Added a note that YouCompleteMe won't see the headers until the target that supplies them has been built.

---

*[doc/vim.rst, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_7H87247Ck1SRRpQR:-LBazonx8bvXjTpiPzuv:b4h8ugq) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L92)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

I don't think these are needed. Should it just be an optional recommendation?
</blockquote></details>

Removed from here, but kept in `sample_vimrc`. The comments there should make it clear that they're optional.

---

*[doc/vim.rst, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_7inl0FLI1XkALeZg:-LBb--Q68CRp1e-VP1B8:b5cckuf) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L101)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

I'm keeping these. I think the text makes it clear that users don't have to use `sample_vimrc`.

---

*[doc/vim.rst, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_7z9CEGS-DyWyyl6n:-LBazxGA20bOwyGPyi8V:b-wja6nl) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L114)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

This should go right after the paragraph on line 81.
</blockquote></details>

Added a link at the end of that paragraph.

---

*[doc/vim.rst, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_84kdATa5enGenzQb:-LBb-6Ew2fYKiCDJnYkg:baw3e87) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L126)):*
> I'm keeping these. I think the text makes it clear that users don't have to use `sample_vimrc`.
I'm keeping these. I think the text makes it clear that users don't have to use `sample_vimrc`.

---

*[doc/vim.rst, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LB_861x6qLPSSSkOgvk:-LBb-6l_2gvh_eCsnxDz:b5cckuf) ([raw file](https://github.com/robotlocomotion/drake/blob/ead94734200f4c1beedafdd44ce1d731526a78fd/doc/vim.rst#L136)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

I'm keeping these. I think the text makes it clear that users don't have to use `sample_vimrc`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741#-:-LBb-AQ_8gq7phm9H9QW:b435hoh)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 4 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[doc/sample_vimrc, line 282 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LBb0Ues45H4wcJJmWCv:-LBb0Ues45H4wcJJmWCw:b-bypx30) ([raw file](https://github.com/robotlocomotion/drake/blob/bb92c1259bf9cff449e8b513ec59b0eb41744467/doc/sample_vimrc#L282)):*
> ```
> " Edit this file.
> nnoremap <leader>ev :call EditVimrc()<CR>
> " Source this fil.e
> ```

`fil.e` -> `file.`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741)*

**Comment by thduynguyen** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741#-:-LBb7r2N8bPg6F6zBmSm:bnfp4nl)*

**Comment by avalenzu** [comment]
Reviewed 1 of 4 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/sample_vimrc, line 282 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8741#-LBb0Ues45H4wcJJmWCv:-LBbCoSvD-EaoDw9FlUQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bb92c1259bf9cff449e8b513ec59b0eb41744467/doc/sample_vimrc#L282)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`fil.e` -> `file.`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741)*

**Comment by avalenzu** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8741)*

**Pull request merged**
