### PR TITLE
[osqp_solver] Allow for primal-only warm-start

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Partial solution to #10048
Extracting primal-only warm starting from #19498

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19499)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai for feature review, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19499#-:-NWalr746CaJZqp5gPpU:b-81zjvi)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19499)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[`planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc` line 210 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19499#-NWbOXLmBJW7NQP9cHGC:-NWbOXLmBJW7NQP9cHGD:bwkuhuw) ([raw file](https://github.com/RobotLocomotion/drake/blob/059b8b83763aee3b9baf5f13bb968afbda996500/planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc#L210)):*
> ```cpp
>     // N.B. When providing an initial guess to OSQP, it's tolerances may allow
>     // for slight violation of its contraints.
>     tol = 1e-4;
> ```

FYI @russtedrake

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  sorry for the delay

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19499#-:-NWkRkmI28ODBXkwJr5V:b-1akpiv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19499#-:-NWkRsKPDxJ1gyPiNXYy:b-3lhrgq)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:  +(release notes: none) 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19499#-:-NWmhvEy9bM4hvCMVri4:b-fkbm35)* status: :shipit: complete! all discussions resolved, LGTM from assignees hongkai-dai,xuchenhan-tri(platform)

**Comment by jwnimmer-tri** [comment]
Putting the initial guess into effect (instead of ignoring it) seems like at least "notes: fix"?

**Comment by xuchenhan-tri** [comment]
My reading is that there's no visible change for the end user, but perhaps there's performance improvement associated with using warm-start? @EricCousineau-TRI could you advise?

**Comment by EricCousineau-TRI** [comment]
Aye, changed to `fix`.
There is a chance that this will have user-visible changes to code that was previously passing in `initial_guess`, e.g. the kinematic trajectory optimization.

**Pull request merged**
