### PR TITLE
Try MeshCat render_static() on jupyter notebook

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Use the[ docker image for Binder](https://github.com/RobotLocomotion/drake/tree/76956e194f/.binder#docker-image-for-binder) to try locally.

Relates to #12645

EDIT(eric): Updated docker-image-for-binder link to use latest commit on master, 76956e194f

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13498)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@EricCousineau-TRI let me know if this is what you were looking for or if I should try something else.

**Comment by EricCousineau-TRI** [comment]
FTR Here are the exact steps I followed:
```sh
$ git fetch upstream pull/13498/head && git checkout FETCH_HEAD
$ git log -n 1 --oneline --no-decorate
c484fe14ac Add MeshCat render_static() examples
$ docker build -f .binder/Dockerfile -t binder .
$ docker run -it --rm --name mybinder -p 8888:8888 binder
# In browser, open up link w/ token, then go to http://0.0.0.0:8888/notebooks/tutorials/rendering_multibody_plant.ipynb
# Cell > Run All
```

**Comment by EricCousineau-TRI** [comment]
But to check, how should I run this?
Or rather, how did you run it?

I've used the following steps (updated from above comment) with current rev, but it still breaks:

```sh
( set -eux;
git fetch upstream pull/13498/head
git checkout 8c89c1bd1
git log -n 1 --oneline --no-decorate
# 8c89c1bd1b Add MeshCat render_static() examples
docker build -f .binder/Dockerfile -t binder .
docker run -it --rm --name mybinder -p 8888:8888 binder
)
```

Can you try these steps, and then let me know if it did or did not work for you?

**Comment by EricCousineau-TRI** [comment]
Oh, should've done this first:

```
docker pull robotlocomotion/drake:latest
```

**Comment by BetsyMcPhail** [comment]
> Oh, should've done this first:
> 
> ```
> docker pull robotlocomotion/drake:latest
> ```

Ah yes, sorry I misread your Edit in the first post that you had already done this. Thanks for adding this step to the documentation.

**Comment by EricCousineau-TRI** [comment]
FYI @BetsyMcPhail As a heads up, @RussTedrake has an awesome version of showing animation for Meshcat in this PR:
https://github.com/RobotLocomotion/drake/pull/13513

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Given that #13513 landed, will close this for now and mark MeshCat static viz as done. Thanks, and lemme know if you'd like me to reopen it!

**Pull request closed without merging**
