### PR TITLE
Remove model instance restrictions in ComInPolyhedronConstraint

### PR DESCRIPTION
**Pull request by calderpg-tri**
@hongkai-dai Did you have a test case in mind for the non-empty model instances case?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15830)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
We can put a floating sphere next to the robot arm, and only constrain the CoM of the robot arm.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15830#-:-Mkdo8cx5Q4DJPs42rN9:blmi5mz)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Seems like +@hongkai-dai will be feature reviewer, so I'll assign that formally now.

**Review by hongkai-dai — COMMENTED** [review]
I think one test could be to add two spheres into MBP, each sphere with its own model instance, and then we constrain the CoM of one model instance. We should see that only one sphere moves to the desired region.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15830#-:-MkrRoyY4P8Xqf8dnMVe:b-qbhlzn)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
@calderpg or @hongkai-dai would you like any help here?  I could try to find a volunteer to push the unit test changes into this PR branch?

**Comment by hongkai-dai** [comment]
Thanks Jeremy, I can work on it over the weekend.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai I'll ping here to float it back up into your inbox as a reminder.

**Comment by jwnimmer-tri** [comment]
@calderpg @hongkai-dai I'll ping here to float it back up into your inbox as a reminder.

**Review by hongkai-dai — COMMENTED** [review]
@calderpg I had a PR https://reviewable.io/reviews/calderpg-tri/drake/1#- to add test into this PR, would you like to review it? Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15830#-:-N2D0kAq3tnI9fM3u1g_:b5yqvck)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@jwnimmer-tri for platform review please, thanks!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15830#-:-N2DWf7S7oQMoL2KvNNb:bp0q8hr)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15830#-:-N2HY4YRCRDXaBin3axr:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Pull request merged**
