### PR TITLE
optimization: resolve minor TODO in ManipulatorEquationConstraint

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15047)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@rcory for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15047#-:-M_jKrnG0uHmd4unnb-v:b-yvq8xq)* status: LGTM missing from assignee rcory, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rcory)

**Review by rcory — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15047#-:-M_t4x8z39tMnWUFI-HL:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15047#-:-M_tj2h04mWQnF4JEtT1:btfqah9)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15047#-:-M_udJ8x4CmmZNACaNki:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),rcory (waiting on @RussTedrake)

**Pull request merged**
