### PR TITLE
[doc] Document macOS EOL release tags

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20339.

+@svenevs or +@BetsyMcPhail for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20458)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
:lgtm: with a small organizational nit that I'm not attached to.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20458#-:-NiFjo0R4R2c0POU5673:b-b2xeig)* status: 1 unresolved discussion, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned

___
*[`doc/_release-notes/end_of_support.md` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20458#-NiFjZipBOUuhsiZFll-:-NiFjZipBOUuhsiZFll0:b-qrq9g6) ([raw file](https://github.com/RobotLocomotion/drake/blob/2db6c03ad4c74adea5a0bffd28d49d10ca39e7ec/doc/_release-notes/end_of_support.md#L10)):*
> ```Markdown
> If you need to use these, you can use an old release of Drake.
> 
> ## Python 3.10 (Wheel)
> ```

minor, the way the document headings read are a little confusing.  Do you think it's worth having two subsections?

```
## Python Wheels

### Python 3.10

...

## Distributions

## Ubuntu 18.04 (Bionic)

...
```

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20458)* status: 1 unresolved discussion, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned

___
*[`doc/_release-notes/end_of_support.md` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20458#-NiFjZipBOUuhsiZFll-:-NiFjv-NA9g44CIbgic-:b-n5p36z) ([raw file](https://github.com/RobotLocomotion/drake/blob/2db6c03ad4c74adea5a0bffd28d49d10ca39e7ec/doc/_release-notes/end_of_support.md#L10)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

minor, the way the document headings read are a little confusing.  Do you think it's worth having two subsections?

```
## Python Wheels

### Python 3.10

...

## Distributions

## Ubuntu 18.04 (Bionic)

...
```
</blockquote></details>

whoops, sorry, `### Ubuntu 18.04 (Bionic)` as an h3 under the `Distributions` h2, I cannot edit that

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20458#-:-NiFuZKZ5w68vn9onv6j:b2xa7ij)* status: LGTM missing from assignees BetsyMcPhail,EricCousineau-TRI(platform)

___
*[`doc/_release-notes/end_of_support.md` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20458#-NiFjZipBOUuhsiZFll-:-NiFuSzM1t4TmBKTxf0x:b-z3v3s) ([raw file](https://github.com/RobotLocomotion/drake/blob/2db6c03ad4c74adea5a0bffd28d49d10ca39e7ec/doc/_release-notes/end_of_support.md#L10)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

whoops, sorry, `### Ubuntu 18.04 (Bionic)` as an h3 under the `Distributions` h2, I cannot edit that
</blockquote></details>

Good point.  I ran with it even further and reworked the overall layout.  (I also moved Wheels down later on the page.)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20458#-:-NiFw1xh7wLxAQvUTbeF:bcpz082)* status: LGTM missing from assignee BetsyMcPhail

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20458)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),svenevs

**Pull request merged**
