### PR TITLE
Update openJDK installation to temurin

### PR DESCRIPTION
**Pull request by nicolecheetham**
Replaces the deprecated adoptOpenJDK with Temurin

Resolves RobotLocomotion/drake/issues/16779

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21776)

### CODE REVIEW

**Comment by nicolecheetham** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please

@BetsyMcPhail

**Comment by nicolecheetham** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21776#-:-O3bvGfyAdH9UsydAbze:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nicolecheetham)

**Comment by nicolecheetham** [comment]
+@ggould-tri for platform review

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21776#-:-O3cLCl1Etla4NrKK6W4:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nicolecheetham)

**Review by BetsyMcPhail — COMMENTED** [review]
+@betsymcphail for review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21776#-:-O3dakN81Sk-npfy334I:b9rse0m)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21776#-:-O3daomh0nu1BxEG43Uz:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by BetsyMcPhail — COMMENTED** [review]
+@ggould-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21776#-:-O3dctBZAfTx1ofeCjYN:b-who1rq)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),BetsyMcPhail

**Pull request merged**
