### PR TITLE
doc: Add direct styleguide publication

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14803.  (That PR contains more example uses of the new `defs.py` helpers.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@jamiesnape I still need to tidy up this PR a little bit, but while I'm doing that I wanted to understand from you how we might need to synchronize this PR with changes to https://github.com/RobotLocomotion/RobotLocomotion.github.io vs https://github.com/RobotLocomotion/styleguide pages publication.  I don't know how the https://drake.mit.edu/styleguide/ redirect is set up.

When I merge this, the https://github.com/RobotLocomotion/RobotLocomotion.github.io will end up with a `styleguide` folder in git.  Will that disturb anything?  After this PR is ready and we run the Publication pipeline to make the new folder, is there any challenge to just turning off the redirect at that time -- it's a few-line change, I hope?

**Comment by jamiesnape** [comment]
Yes, we cannot actually turn that redirect off, but we may be OK in the long run if GitHub Pages is disabled on the `styleguide` repo. I have never actually seen what the precedence with respect to which `/styleguide`  would be used in this situation, however. You could, of course, rename the repo slightly, or publish to a different folder and update links to be sure.

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811#-:-MWVBKrHDsNmkxH2kGb6:by4pfea)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCz3q4yPKkerL2V5w:-MWVCz3q4yPKkerL2V5x:b-yuz98f) (no related file):*
Working: Running locally per documented instructions.

---
___
*[doc/defs.py, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVBku04QNFNuYXGeKl:-MWVBku04QNFNuYXGeKm:bp7ai1n) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L1)):*
> ```Python
> """Common library to provide a reusable main() routine for all of our
> ```

BTW Can't say that I love the name `defs.py` and this having an entrypoint, but I have no better ideas.
___
*[doc/defs.py, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVBvBL89-B9nPuA-GF:-MWVBvBL89-B9nPuA-GG:b-8fdqvy) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L1)):*
> ```Python
> """Common library to provide a reusable main() routine for all of our
> ```

I'm not sure if I understand how this is intended to be used yet.

I see lines added for common / refactored code, but I don't see lines deleted.
Is there an TODO / checkbox that is missing, or that I missed?
___
*[doc/defs.py, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCQBeCe-WKpL16RaP:-MWVCQBeCe-WKpL16RaQ:b4ypgrm) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L43)):*
> ```Python
>     """
>     assert os.path.isdir(temp_dir)
>     r = runfiles.Create()
> ```

BTW Readabilty of `r` isn't great... but once again, I have no better suggestion.
___
*[doc/defs.py, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCYRjA5TwglXXHS45:-MWVCYRjA5TwglXXHS46:b-uojsjy) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L114)):*
> ```Python
>         pages = _call_build(build=build, out_dir=out_dir)
>         assert len(pages) > 0
>         os.chdir(scratch)
> ```

nit When doing scripting, it's nice to see `chdir` also be printed.

Example:
https://github.com/EricCousineau-TRI/repro/blob/37a42dc5a4/python/python_shell_example.py#L53-L55
___
*[doc/defs.py, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCsA95ljLMgwq12cI:-MWVCsA95ljLMgwq12cJ:b-e1qwoq) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L147)):*
> ```Python
>             on_error(f"--out_dir={out_dir} is not empty")
>     else:
>         os.makedirs(out_dir)
> ```

nit Same as above - for making directories, it's nice to trace it out.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/defs.py, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCd-G3eqrO4rlv45M:-MWVCd-G3eqrO4rlv45N:b-cgcx7s) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L27)):*
> ```Python
> 
> 
> def symlink_input(filegroup_resource_path, temp_dir, strip_prefix=None):
> ```

FYI Does this function deserve a unit test?  It would not be overly difficult to create one.
___
*[doc/defs.py, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCh-m05wU9n5W7_Xu:-MWVCh-m05wU9n5W7_Xv:b-cgcx7s) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L59)):*
> ```Python
> 
> 
> def check_call(args, *, cwd=None):
> ```

FYI Does this function deserve a unit test?  It would not be overly difficult to create one.
___
*[doc/defs.py, line 155 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCvWW02Q0lPiKUUSf:-MWVCvWW02Q0lPiKUUSg:b5fuocq) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L155)):*
> ```Python
> 
> def main(*, build, subdir, description, supports_quick=False,
>          supports_modules=False):
> ```

Working Oops, these =False options were rebase artifact; will remove.  They are coming in a future PR.
___
*[doc/defs.py, line 188 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCqQKB0QNv96-0jT7:-MWVCqQKB0QNv96-0jT8:btplw28) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L188)):*
> ```Python
>         _verbose = True
>     curried_build = build
>     if supports_quick:
> ```

Working Oops, this branch was a rebase artifact; will remove.  This is coming in a future PR.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: 6 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/defs.py, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCd-G3eqrO4rlv45M:-MWVDDUt1JdxFxWoBj2W:brg9goj) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Does this function deserve a unit test?  It would not be overly difficult to create one.
</blockquote></details>

IMO, nahhh. I think end-to-end is sufficient for utilities like this.
___
*[doc/defs.py, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCh-m05wU9n5W7_Xu:-MWVDKQN8yBjkc5GjBok:b-a6wxdm) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Does this function deserve a unit test?  It would not be overly difficult to create one.
</blockquote></details>

OK Same opinion as above.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/defs.py, line 155 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCvWW02Q0lPiKUUSf:-MWVDNNCAKZUvHUROUpZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L155)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working Oops, these =False options were rebase artifact; will remove.  They are coming in a future PR.
</blockquote></details>

Done.
___
*[doc/defs.py, line 188 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCqQKB0QNv96-0jT7:-MWVDO376TcAUXHepQLv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L188)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working Oops, this branch was a rebase artifact; will remove.  This is coming in a future PR.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/defs.py, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVBvBL89-B9nPuA-GF:-MWVDjAG-E7t3ZAzTw2T:bwz6ri1) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm not sure if I understand how this is intended to be used yet.

I see lines added for common / refactored code, but I don't see lines deleted.
Is there an TODO / checkbox that is missing, or that I missed?
</blockquote></details>

Does the follow-up patch in #14803 help paint the picture?  Indeed, this PR is the first and only user so far, but I have patches ready for Sphinx, Doxygen, and Jekyll to use this same library, so that build and preview are uniform everywhere.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: 5 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/styleguide/_layouts/default.html, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVDQ0d1yUUM7JEzflZ:-MWVDQ0d1yUUM7JEzfl_:b-wwo7lq) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/styleguide/_layouts/default.html#L6)):*
> ```HTML
>     <meta charset="utf-8"/>
>     <title>{{ page.title }}</title>
>     <link rel="stylesheet" href="https://google.github.io/styleguide/assets/css/style.css">
> ```

nit The styling for this page looks really weird; see image for concrete feedback

```
$ git log -n 1 --oneline --no-decorate
36d1b76f6e doc: Add direct styleguide publication
$ bazel run //doc/styleguide:build -- --serve
$ firefox http://127.0.0.1:8000/styleguide/
```



Similar issues for `http://127.0.0.1:8000/styleguide/pyguide.html`.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: as incremental improvement.

Nits on styling and some minor code stuff, but those can be dismissed for now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811#-:-MWVEcyCDoYf9cs-BZfv:b-r26orc)* status: 3 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCz3q4yPKkerL2V5w:-MWVEbbl3EHtJY9mH7fQ:b-vqddjo) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Running locally per documented instructions.
</blockquote></details>

OK See feedback below.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: 2 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI)

___
*[doc/defs.py, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVBvBL89-B9nPuA-GF:-MWVGp5t5mAGB0ddp1L8:b-5bskja) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Yup, looks perfect!

Is it possible to list your PR train in the issue w/ checkboxes? (not a huge deal, tho)
</blockquote></details>

There is no issue filed, and I don't have a tactical plan for the train other than what's open and cross-linked from #14803.  I am carving out bits that make sense one by one.  It's not easy to know which bits those will be ahead of time.
___
*[doc/defs.py, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCYRjA5TwglXXHS45:-MWVG7rX10ZDetFzz_Bo:b-ycohnu) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L114)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit When doing scripting, it's nice to see `chdir` also be printed.

Example:
https://github.com/EricCousineau-TRI/repro/blob/37a42dc5a4/python/python_shell_example.py#L53-L55
</blockquote></details>

That's true in general when the script is about to echo _more_ command lines to follow.  Here, we're not running anything else.  It seems like the `+ cd ...` would do more harm them good, for the typical user?
___
*[doc/defs.py, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVCsA95ljLMgwq12cI:-MWVGhb802_P0VXOXzds:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/defs.py#L147)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Same as above - for making directories, it's nice to trace it out.
</blockquote></details>

Done.
___
*[doc/styleguide/_layouts/default.html, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVDQ0d1yUUM7JEzflZ:-MWVH4GQEO2fIMw5EviS:bl3lm7h) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/styleguide/_layouts/default.html#L6)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit The styling for this page looks really weird; see image for concrete feedback

```
$ git log -n 1 --oneline --no-decorate
36d1b76f6e doc: Add direct styleguide publication
$ bazel run //doc/styleguide:build -- --serve
$ firefox http://127.0.0.1:8000/styleguide/
```



Similar issues for `http://127.0.0.1:8000/styleguide/pyguide.html`.
</blockquote></details>

Yeah, the index page looks dumb.  I almost left it out of this PR because it's fairly useless to publish onto the website in the first place, but since we currently publish it, I figured might as well keep it.  If you think its better to omit it, I'm happy to do that.  I don't particularly want to polish it though -- any useful content from that page should be in our `_pages` website anyway (along with all the rest of the documentation instructions).

I _did_ however try to make the pyguide look useful.  I don't actually _want_ it to look like the Google guide -- we are a fork and so using a custom Drake style is actually better IMO.  (Eventually we should adapt the color scheme to match the new marketing colors & logo & etc.)  If you have specific presentation defects about the pyguide, please let me know.  I'll either fix them here or catalog them for a follow-up.

**Comment by jamiesnape** [comment]
Just an FYI that the cpp and python style guides are the second and third most visited pages (from Google) on the Drake website. The index page shows up in a lot of irrelevant searches and getting minimal clicks, so it may be kinder to not publish it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: 2 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI)

___
*[doc/styleguide/_layouts/default.html, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVDQ0d1yUUM7JEzflZ:-MWVWBC66m9WYXLzj7M1:bdfzkyv) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/styleguide/_layouts/default.html#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah, the index page looks dumb.  I almost left it out of this PR because it's fairly useless to publish onto the website in the first place, but since we currently publish it, I figured might as well keep it.  If you think its better to omit it, I'm happy to do that.  I don't particularly want to polish it though -- any useful content from that page should be in our `_pages` website anyway (along with all the rest of the documentation instructions).

I _did_ however try to make the pyguide look useful.  I don't actually _want_ it to look like the Google guide -- we are a fork and so using a custom Drake style is actually better IMO.  (Eventually we should adapt the color scheme to match the new marketing colors & logo & etc.)  If you have specific presentation defects about the pyguide, please let me know.  I'll either fix them here or catalog them for a follow-up.
</blockquote></details>

I've yanked out the index page.

I'll leave this thread open to discuss any pyguide issues.

**Comment by EricCousineau-TRI** [comment]
___
*[doc/styleguide/_layouts/default.html, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVDQ0d1yUUM7JEzflZ:-MWVeRdy8dK_KECzmlfC:bh3lq14) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/styleguide/_layouts/default.html#L6)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

At present, still some (minor) defects; is it possible to use markdown css from main drake website? (it seems to render the kramdown-rendered stuff there just fine)

```
$ git log -n 1 --oneline --no-decorate
bdfde9e748 doc: Add direct styleguide publication
$ bazel run //doc/styleguide:build -- --serve
$ firefox http://127.0.0.1:8000/styleguide/pyguide.html
```

> 
</blockquote></details>

(Please let me know if you'd like me to take a stab at making adjustments that I'd find more aesthetic)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/styleguide/build.py, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVdGTE1VoG4cQXqNST:-MWVg2Q_BzVORIdinLnr:bgz399f) ([raw file](https://github.com/robotlocomotion/drake/blob/bdfde9e748f90038c25531cf983a63412f01730e/doc/styleguide/build.py#L59)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Is it possible to suppress printing of index page, `""`, for preview URLs via CLI?
</blockquote></details>

Done.  You're right, this line should have changed when I yanked the index page from the BUILD.
___
*[doc/styleguide/build.py, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVdKg4DvjD89pvYazP:-MWVgAZU7nylt5K6fpMC:b9yx0vk) ([raw file](https://github.com/robotlocomotion/drake/blob/bdfde9e748f90038c25531cf983a63412f01730e/doc/styleguide/build.py#L59)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit At present, index page shows unrendered markdown and `include/` directory, which can be a (very) minor distraction.

```
$ wget -q http://127.0.0.1:8000/styleguide/ -O - | tail -n 8
<li><a href="cppguide.html">cppguide.html</a></li>
<li><a href="include/">include/</a></li>
<li><a href="pyguide.html">pyguide.html</a></li>
<li><a href="README.md">README.md</a></li>
</ul>
<hr>
</body>
</html>
```
</blockquote></details>

Done (by removing the preview suggestion and the stray README.md from the BUILD file).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI)

___
*[doc/styleguide/_layouts/default.html, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVDQ0d1yUUM7JEzflZ:-MWVjJvk-qpMvIEMUcQO:b104fap) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/styleguide/_layouts/default.html#L6)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(Please let me know if you'd like me to take a stab at making adjustments that I'd find more aesthetic)
</blockquote></details>

OK I fixed the bullet indent -- that one did look pretty distracting.

I spike tested the main.css and it works pretty well: it gets us the red styling match the jekyll pages site; it adds back a tiny bit more padding so the page isn't so compacted -- but I'll propose deferring that edit to a follow-up PR so that we can work on changing pyguide, cppguide, pydrake, and (possibly) doxygen over to that sheet all at once, so one stylesheet to rule them all  I don't quite want to depend on it yet until we're sure that we want to use it everywhere.

I don't see any other acute layout problems; please post if you have any.

For adjusting vertical padding, I say let's defer until we can restyle the whole site -- or at worst, you could open a follow up PR if you really think is reduces the guide's usability too much.  It doesn't seem worth time to me.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 11 files at r1, 1 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811#-:-MWW2JrH0OZv66n3c4P0:bnfp4nl)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[doc/defs.bzl, line 54 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVwfDE1dXrJN2qtuXi:-MWVwfDF4lPRIXkXSR42:beuo5p) ([raw file](https://github.com/robotlocomotion/drake/blob/22ea9833a822c0f8a881e661591ce79444a5bb25/doc/defs.bzl#L54)):*
> ```Starlark
>     },
> )
> """Creates a text file of the transitive list of files in a filegroup.
> ```

BTW educate me (non-blocking): Why does this doc comment placement make sense?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[doc/styleguide/_layouts/default.html, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVDQ0d1yUUM7JEzflZ:-MWW36cvDXnvIkiceLTP:bgl4lbj) ([raw file](https://github.com/robotlocomotion/drake/blob/36d1b76f6e0433eb0dbead2faf5f24b6fcf49ced/doc/styleguide/_layouts/default.html#L6)):*
OK SGTM! Confirmed offset:

```
$ git log -n 1 --oneline --no-decorate
22ea9833a8 doc: Add direct styleguide publication
$ bazel run //doc/styleguide:build -- --serve
$  firefox http://127.0.0.1:8000/styleguide/pyguide.html
```

>

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: labeled "do not merge" (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[doc/defs.bzl, line 54 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14811#-MWVwfDE1dXrJN2qtuXi:-MWW3zV70dU4FZLwGRWL:b-m1e5bo) ([raw file](https://github.com/robotlocomotion/drake/blob/22ea9833a822c0f8a881e661591ce79444a5bb25/doc/defs.bzl#L54)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW educate me (non-blocking): Why does this doc comment placement make sense?
</blockquote></details>

Huh, TIL.  This is how bazel did it years ago using skydoc (see https://github.com/bazelbuild/skydoc/blob/master/skylark/skylark.bzl for an example), but as https://github.com/bazelbuild/skydoc/ notes this format is deprecated and we should be using the stardoc format now.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14811)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@jamiesnape Okay, I think this ready to test for deployment.  Maybe ping me on slack this week and we'll find a time to test and coordinate a rollout?

My guess is we try:
- merge this
- launch a nightly publication
- confirm that https://github.com/RobotLocomotion/RobotLocomotion.github.io got the right files
- disable https://github.com/RobotLocomotion/styleguide pages
- hope it all worked?

If we need to revert, we can adjust this change to publish to `styleguide2` instead for now, and either revert or repopulate the https://github.com/RobotLocomotion/RobotLocomotion.github.io changes.

**Comment by jwnimmer-tri** [comment]
FTR, it looks like the answer to my _"I don't know how the https://drake.mit.edu/styleguide/ redirect is set up"_ is:

> After the main site is set up, any additional repositories that have GitHub pages enabled on them will use a subdirectory structure.

-- https://samhermes.com/posts/deploying-repository-subdirectory-github-pages-site/

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Pull request merged**
