### PR TITLE
[manipulation] Add ZeroForceDriver for hardware_sim

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17112.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17694)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17694)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @ggould-tri and @jwnimmer-tri)

___
*[`manipulation/util/apply_driver_configs.h` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17694#-N8eFlp48w3b8ewVx3Ru:-N8eFlp48w3b8ewVx3Rv:b-y8mv08) ([raw file](https://github.com/robotlocomotion/drake/blob/3b77e68f95ecbed02fa15934a14f3ad00e7830d8/manipulation/util/apply_driver_configs.h#L14)):*
> ```objc
> 
> /// @file This file tracks methods we can use to stack Drake systems between
> /// an LCM interface and the unactuated ports of an MbP.
> ```

minor:  This is true, but drivers also typically convey telemetry back from the MBP ports as well.
___
*[`manipulation/util/zero_force_driver_functions.h` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17694#-N8eGMTm6dA14WKYdAW-:-N8eGMTm6dA14WKYdAW0:btlopmb) ([raw file](https://github.com/robotlocomotion/drake/blob/3b77e68f95ecbed02fa15934a14f3ad00e7830d8/manipulation/util/zero_force_driver_functions.h#L24)):*
> ```objc
>     const std::map<std::string, multibody::parsing::ModelInstanceInfo>&
>         models_from_directives,
>     const systems::lcm::LcmBuses& /* lcms */,
> ```

minor:  This comment conveys literally nothing.



_Suggestion:_
```objc
    const systems::lcm::LcmBuses&
```
___
*[`manipulation/util/zero_force_driver_functions.cc` line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17694#-N8eGRqL-GcDcr-8cTlJ:-N8eGRqL-GcDcr-8cTlK:b-mwcsfl) ([raw file](https://github.com/robotlocomotion/drake/blob/3b77e68f95ecbed02fa15934a14f3ad00e7830d8/manipulation/util/zero_force_driver_functions.cc#L21)):*
> ```cpp
>     const MultibodyPlant<double>& sim_plant,
>     const std::map<std::string, ModelInstanceInfo>& /* ... */,
>     const LcmBuses& /* lcms */,
> ```

minor:  This comment conveys nothing.



_Suggestion:_
```cpp
    const LcmBuses&,
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17694)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[`manipulation/util/apply_driver_configs.h` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17694#-N8eFlp48w3b8ewVx3Ru:-N8eK14d3ptddvyCajBg:b-896fig) ([raw file](https://github.com/robotlocomotion/drake/blob/3b77e68f95ecbed02fa15934a14f3ad00e7830d8/manipulation/util/apply_driver_configs.h#L14)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This is true, but drivers also typically convey telemetry back from the MBP ports as well.
</blockquote></details>

Done?

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please.
+@rpoyner-tri for platform review, please.

(I'll rebase away the merge conflict once I have my local build up and running again.)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17694)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),zachfang, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri and @zachfang)

___
*[`examples/hardware_sim/scenario.h` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17694#-N93EGGL7Xbr4vbDsXKQ:-N93EGGL7Xbr4vbDsXKR:b-ccczxy) ([raw file](https://github.com/robotlocomotion/drake/blob/3b77e68f95ecbed02fa15934a14f3ad00e7830d8/examples/hardware_sim/scenario.h#L64)):*
> ```objc
>   from, keyed on the ModelInstance name. */
>   using DriverVariant = std::variant<
>       // TODO(jwnimmer-tri) Add more kinds of robots here.
> ```

nit Robots? Drivers?



_Code quote:_
```objc
robots
```
___
*[`manipulation/util/apply_driver_configs.h` line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17694#-N93Fcht2p40rChtrs2f:-N93Fcht2p40rChtrs2g:b34z9ni) ([raw file](https://github.com/robotlocomotion/drake/blob/3b77e68f95ecbed02fa15934a14f3ad00e7830d8/manipulation/util/apply_driver_configs.h#L46)):*
> ```objc
>         models_from_directives,
>     const systems::lcm::LcmBuses& lcm_buses,
>     systems::DiagramBuilder<double>* builder) {
> ```

nit Consider pushing this function body to a .cc file; it more than fits the recommendations of https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions .

**Comment by jwnimmer-tri** [comment]
*[`manipulation/util/apply_driver_configs.h` line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17694#-N93Fcht2p40rChtrs2f:-N93I71j7DeAdDLC30nB:b-lcnb1d) ([raw file](https://github.com/robotlocomotion/drake/blob/3b77e68f95ecbed02fa15934a14f3ad00e7830d8/manipulation/util/apply_driver_configs.h#L46)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Consider pushing this function body to a .cc file; it more than fits the recommendations of https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions .
</blockquote></details>

It's an open template, so for the most part it can't go into the cc file.  Is it worth doing the vector-to-map function as a helper cc file function maybe?

**Review by zachfang — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17694#-:-N94QmwD9OFNirqLKpNJ:bg7igkv)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri and @zachfang)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17694#-:-N96i-180czJOmSG-_3O:bnfp4nl)* status: 1 unresolved discussion, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri and @zachfang)

**Pull request merged**
