### PR TITLE
Update CROSSTOOL for Mac to support Bazel 0.12.0 and above

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8588)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588#-L9vJPUvCbgCYLJpSY3P:-L9vJPUvCbgCYLJpSY3Q:b3bq87e) (no related file):*
FYI, with `bazel-0.11.1`, we have:

```
$ bazel build //common/... -c dbg
..................
INFO: Analysed 806 targets (45 packages loaded).
INFO: Found 806 targets...
ERROR: /Users/soonhok/work/drake/common/BUILD.bazel:119:1: C++ compilation of rule '//common:double' failed (Exit 1)
clang: error: cannot specify -o when generating multiple output files
INFO: Elapsed time: 6.938s, Critical Path: 0.41s
FAILED: Build did NOT complete successfully
```

Because it runs:
```
  /usr/bin/clang -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g '-std=c++14' -iquote . -iquote bazel-out/darwin-dbg/genfiles -iquote external/bazel_tools -iquote bazel-out/darwin-dbg/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -MD -MF bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.d '-frandom-seed=bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.o' -fPIC '-Werror=all' '-Werror=deprecated' '-Werror=deprecated-declarations' '-Werror=ignored-qualifiers' '-Werror=old-style-cast' '-Werror=overloaded-virtual' '-Werror=shadow' '-Werror=inconsistent-missing-override' '-Werror=non-virtual-dtor' '-Werror=return-stack-address' '-Werror=sign-compare' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c common/test/lib_is_real.cc -o bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.o -c common/test/lib_is_real.cc -o bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.o)
```

Note that the last part it has a duplicate of `-c common/test/lib_is_real.cc -o bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.o`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588)*

**Comment by soonho-tri** [comment]
+@soonho-tri (feature-reviewer)

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588#-L9vJPUvCbgCYLJpSY3P:-L9vUrwH-QDt2DFq-6oV:b-1ryjqg) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, with `bazel-0.11.1`, we have:

```
$ bazel build //common/... -c dbg
..................
INFO: Analysed 806 targets (45 packages loaded).
INFO: Found 806 targets...
ERROR: /Users/soonhok/work/drake/common/BUILD.bazel:119:1: C++ compilation of rule '//common:double' failed (Exit 1)
clang: error: cannot specify -o when generating multiple output files
INFO: Elapsed time: 6.938s, Critical Path: 0.41s
FAILED: Build did NOT complete successfully
```

Because it runs:
```
  /usr/bin/clang -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g '-std=c++14' -iquote . -iquote bazel-out/darwin-dbg/genfiles -iquote external/bazel_tools -iquote bazel-out/darwin-dbg/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -MD -MF bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.d '-frandom-seed=bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.o' -fPIC '-Werror=all' '-Werror=deprecated' '-Werror=deprecated-declarations' '-Werror=ignored-qualifiers' '-Werror=old-style-cast' '-Werror=overloaded-virtual' '-Werror=shadow' '-Werror=inconsistent-missing-override' '-Werror=non-virtual-dtor' '-Werror=return-stack-address' '-Werror=sign-compare' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c common/test/lib_is_real.cc -o bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.o -c common/test/lib_is_real.cc -o bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.o)
```

Note that the last part it has a duplicate of `-c common/test/lib_is_real.cc -o bazel-out/darwin-dbg/bin/common/_objs/lib_is_real.so/common/test/lib_is_real.pic.o`.
</blockquote></details>

Mark as satisfied since we decide to move on to `bazel>=0.12.0`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588#-:-L9vUxuL6FDQR0wXq7Mv:b-mg98ad)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/cc_toolchain/CROSSTOOL, line 1213 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588#-L9vVG8i1je_yFJfjhNN:-L9vVG8i1je_yFJfjhNO:b-vcdcij) ([raw file](https://github.com/robotlocomotion/drake/blob/d5837ae805f3c9db16d4828b84afb7404b0a01cf/tools/cc_toolchain/CROSSTOOL#L1213)):*
> ```
>     action_name: "c-compile"
>     tool {
>       tool_path: "/usr/bin/clang"  # Changed from "wrapped_clang" for Drake.
> ```

META, I'm wondering `/usr/bin/clang` is just good enough or `osx_cc_wrapper.sh` is required here. (same question for other places below).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588)*

**Comment by soonho-tri** [comment]
:lgtm:

Can you check `install` still works? I can do it this evening if that's fine with you.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588#-:-L9vXfDV6P6b3Ty0xGtV:bzieyx6)*

**Comment by jamiesnape** [comment]
Yes, I tested it locally. Everything is good.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588#-:-L9vYKwWB4G-Na9zevv-:bbjvg7l)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by soonho-tri** [comment]
:+1: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588#-:-L9vYX-u8ma2aybIBRTg:b-8fx2u7)*

**Comment by jwnimmer-tri** [comment]
I am happy to review as of early tomorrow morning, but I'm about to head out the door now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8588#-:-L9w1_6rEQYjfXnjArdI:bnfp4nl)*

**Pull request merged**
