### PR TITLE
Give external visibility and linkage to System2 abstract-valued IO

### PR DESCRIPTION
**Pull request by david-german-tri**
A lot of this stuff stopped being templates in d2a4d0c, and therefore needs export goop.  I also filled in some missing destructors, and began moving some code into .cc files.

+@jwnimmer-tri for both levels of review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3251)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm:  All comments are discretionary.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/system_input.h, line 111 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz2L2ggq-F_tZRq8Mm:-KPz2L2hiuAhOjU57-9o:b-x9gxur) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_input.h#L111)):*
> ```objc
>   /// Constructs an abstract-valued FreestandingInputPort.
>   /// Takes ownership of @p data.
>   explicit FreestandingInputPort(std::unique_ptr<AbstractValue> data)
> ```

BTW Consider moving this code to the `.cc` file?

---

*[drake/systems/framework/system_input.h, line 122 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz2vMObo5jCMD9GxPU:-KPz2vMPM3Kjpt-Wb_KM:b-n7nd7w) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_input.h#L122)):*
> ```objc
>   template <typename T>
>   explicit FreestandingInputPort(std::unique_ptr<Value<T>> data)
>       : output_port_(std::move(data)) {
> ```

BTW I don't understand why this constructor is needed -- wouldn't the prior constructor with AbstractValue be a suitable overload instead?   Or in any case, if this version must remain, perhaps it would be better for this constructor to merely forward to the AbstractValue version.

---

*[drake/systems/framework/system_input.h, line 141 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz3ZS7I7ERf0VlXOe-:-KPz3ZS7I7ERf0VlXOe0:b-y5drfo) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_input.h#L141)):*
> ```objc
>   /// possibility this FreestandingInputPort has been accessed since the last
>   /// time this method was called.
>   AbstractValue* GetMutableData() { return output_port_.GetMutableData(); }
> ```

FYI Up until this point, the PR was very consistent that `lowercase_methods` are inline and `BiggerMethods` were defined elsewhere.  I can fully support leaving these (trivial!) inline definitions here, but thought I'd point it out in case you thought the convention was worthwhile.

---

*[drake/systems/framework/system_output.h, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz-L2OirQe4uyuwvCn:-KPz-L2PC7VkFQteDGo8:bsjy015) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_output.h#L43)):*
> ```objc
>   explicit OutputPort(std::unique_ptr<V<T>> vec)
>       : data_(
>             new VectorValue<T>(std::unique_ptr<VectorBase<T>>(vec.release()))) {
> ```

BTW `data_(new VectorValue<T>(std::move(vec))) {}` is shorter.  See
http://en.cppreference.com/w/cpp/memory/unique_ptr/unique_ptr overload (6).

---

*[drake/systems/framework/system_output.h, line 56 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz41zngcNPZxkAQxWM:-KPz41zoPZodWOG_x6jT:b-9suuzy) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_output.h#L56)):*
> ```objc
>   /// @tparam T The type of the data.
>   template <typename T>
>   explicit OutputPort(std::unique_ptr<Value<T>> data)
> ```

BTW Same thing here -- unclear why this overload is needed vs AbstractValue above?  (Or at least consider delegating.)

---

*[drake/systems/framework/system_output.h, line 111 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz4MIiLkt7N-_dU2Ik:-KPz4MIiLkt7N-_dU2Il:bk5gk7l) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_output.h#L111)):*
> ```objc
>   /// Returns a clone of this OutputPort containing a clone of the data, but
>   /// without any dependents.
>   std::unique_ptr<OutputPort> Clone() const {
> ```

BTW Consider making non-inline?  This one doesn't seem to be inline-performance sensitive?

---

*[drake/systems/framework/value.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPyyHFVgCJsouss87SA:-KPyyHFVgCJsouss87SB:b2izwrm) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/value.h#L25)):*
> ```objc
>  public:
>   AbstractValue() {}
>   virtual ~AbstractValue();
> ```

FYI Hooray!  (On all of these `{}` to `;` changes.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-:-KPz5JeGY9QDImWiVq2K:by7wfbe)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/system_input.h, line 111 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz2L2ggq-F_tZRq8Mm:-KPzJBqw8n2T8PF05SXH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_input.h#L111)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider moving this code to the `.cc` file?
</details>
Done.

---

*[drake/systems/framework/system_input.h, line 122 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz2vMObo5jCMD9GxPU:-KPzJHnJ_-DNTrnUlkLy:bz7tkah) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_input.h#L122)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I don't understand why this constructor is needed -- wouldn't the prior constructor with AbstractValue be a suitable overload instead?   Or in any case, if this version must remain, perhaps it would be better for this constructor to merely forward to the AbstractValue version.
</details>
I don't think unique_ptr is covariant in that way, but I've made it forward.

---

*[drake/systems/framework/system_input.h, line 141 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz3ZS7I7ERf0VlXOe-:-KPzJac-qs_C-4OB6uyv:baen9tu) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_input.h#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI Up until this point, the PR was very consistent that `lowercase_methods` are inline and `BiggerMethods` were defined elsewhere.  I can fully support leaving these (trivial!) inline definitions here, but thought I'd point it out in case you thought the convention was worthwhile.
</details>
Yeah, I thought of that too, but I decided the triviality prevailed.

---

*[drake/systems/framework/system_output.h, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz-L2OirQe4uyuwvCn:-KPzJsY47-3Kw90zVkse:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_output.h#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW `data_(new VectorValue<T>(std::move(vec))) {}` is shorter.  See
> http://en.cppreference.com/w/cpp/memory/unique_ptr/unique_ptr overload (6).
</details>
Done.

---

*[drake/systems/framework/system_output.h, line 56 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz41zngcNPZxkAQxWM:-KPzK9p5sJUzSTbJIrHT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_output.h#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Same thing here -- unclear why this overload is needed vs AbstractValue above?  (Or at least consider delegating.)
</details>
Done.

---

*[drake/systems/framework/system_output.h, line 111 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz4MIiLkt7N-_dU2Ik:-KPzKIDPexYxSqqwq_ho:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_output.h#L111)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider making non-inline?  This one doesn't seem to be inline-performance sensitive?
</details>
Done.

---

*[drake/systems/framework/value.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPyyHFVgCJsouss87SA:-KPzKIt7m44OpaGBUJEX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/value.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI Hooray!  (On all of these `{}` to `;` changes.)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3251)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/framework/system_input.h, line 122 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3251#-KPz2vMObo5jCMD9GxPU:-KPzN9HRAfd_5m4AlgFZ:b-i5k34s) ([raw file](https://github.com/robotlocomotion/drake/blob/7b17fc61dce1d3f701e7b083d1e115f2c0e6d16b/drake/systems/framework/system_input.h#L122)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I don't think unique_ptr is covariant in that way, but I've made it forward.
</details>
Its not covariant, but it is implicitly convertible -- the (6) overload I linked upthread.  But I see why this is needed now: for overload resolution.  The first constructor here has `unique<V<T>>` with unqualified `V` (except by API comment).  The `Value<T>` matches there, instead of going through conversion to reach the second constructor -- so we need to declare this third one to clarify our intent.  We may at some point need to guard the first constructor more carefully to prevent this for other types (which would mean we could remove this third flavor), but for now the code is a-ok.  Resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3251)*

**Pull request merged**
