### PR TITLE
September external updates

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #21870.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21887)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Looks like either VTK or tinygltf is having issues; let's try without VTK first...

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-leak-sanitizer please

**Comment by mwoehlke-kitware** [comment]
+@sherm1 for review (both), please.

**Review by sherm1 — COMMENTED** [review]
Wow! There are so many changes here. I don't have any way to determine whether they are correct. Can you say why you have confidence that they are? Is this the result of an automated process?

I'd like someone with a better grasp of our build system to take a look at this also so it is less of a rubber stamp. I'll propose a reviewer but feel free to reassign.

+@rpoyner-tri for a second feature or platform review

> Reviewed 64 of 64 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21887#-:-O6XjWbp5FsDKfDHnvL5:b-k4w2nv)* status: 1 unresolved discussion, LGTM missing from assignees sherm1(platform),rpoyner-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/crate_universe/lock/Cargo.toml.lock` line 549 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21887#-O6XiDsw2Z7sRnVEZNeA:-O6XhoFT6OpASujMnegw:b-ci7ofb) ([raw file](https://github.com/RobotLocomotion/drake/blob/a671db03f3e79d6585ffd3f1b2ad12e57818a430/tools/workspace/crate_universe/lock/Cargo.toml.lock#L549)):*
> ```
> checksum = "c35da53b5a021d2484a7cc49b2ac7f2d840f8236a286f84202369bd338d761ea"
> dependencies = [
>  "equator-macro 0.2.1",
> ```

BTW this says "0.2.1" but the version above is "0.2.2". Just checking that this is intentional?

**Review by mwoehlke-kitware — COMMENTED** [review]
> Is this the result of an automated process?

Yes; see https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21887#-:-O6XmcfC0OCYKcLG87PV:b-os1b9u)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),sherm1(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/crate_universe/lock/Cargo.toml.lock` line 549 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21887#-O6XiDsw2Z7sRnVEZNeA:-O6Xmkuy2co7e7uu6cUG:bx08w5i) ([raw file](https://github.com/RobotLocomotion/drake/blob/a671db03f3e79d6585ffd3f1b2ad12e57818a430/tools/workspace/crate_universe/lock/Cargo.toml.lock#L549)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this says "0.2.1" but the version above is "0.2.2". Just checking that this is intentional?
</blockquote></details>

Uh... that's an interesting question. I know next to nothing about how the crate stuff works; maybe @jwnimmer-tri knows more?

Even more confusingly, just below this there is `equator 0.4.1`. Why does `equator` show up twice?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21887)* status: LGTM missing from assignees rpoyner-tri(platform),sherm1(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/crate_universe/lock/Cargo.toml.lock` line 549 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21887#-O6XiDsw2Z7sRnVEZNeA:-O6XoJh2E0y8ki0XXrwg:b-2vufdj) ([raw file](https://github.com/RobotLocomotion/drake/blob/a671db03f3e79d6585ffd3f1b2ad12e57818a430/tools/workspace/crate_universe/lock/Cargo.toml.lock#L549)):*
This looks fine to me.

https://crates.io/crates/equator and https://crates.io/crates/equator-macro are different crates, so it's fine for their version to vary independently (of course subject to whatever cross-compatibility constraints are declared by their metadata).

> Why does `equator` show up twice?

Rust accepts and embraces multiple different versions of its dependencies in use at once.  As long as CI is happy, we are happy.

**Review by sherm1 — COMMENTED** [review]
OK, thanks -- :lgtm: from me then.
Rico is away, -@rpoyner-tri +@jwnimmer-tri for final OK, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21887#-:-O6XuZAW1EB-l7yN33u0:b-aja6fb)* status: LGTM missing from assignee jwnimmer-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

(Apparently reviewable has a limit of 20 commits when showing them one by one, but reviewing using GitHub wasn't too bad.)

> Reviewed 64 of 64 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21887#-:-O6Xvaty2vr8ttUmXoze:b-96qf3i)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
> Apparently reviewable has a limit of 20 commits when showing them one by one

Yeah, I noticed. :slightly_smiling_face:  To be honest, I'm not sure how valuable reviewing individual commits is for these PRs, as the changed files almost never overlap.

**Comment by jwnimmer-tri** [comment]
Thanks for the rebase.  I'll force-merge as soon as one build passes.

> I'm not sure how valuable reviewing individual commits is for these PRs, as the changed files almost never overlap.

The idea is for the reviewer to cross-check that all commits are indeed independent.  If the person running the upgrade made some mistakes with git outside of the automation, then certain hunks of changes might end up mixed into the wrong commit such that the commit subject and the contents of the patch are at odds.

**Pull request merged**
