### PR TITLE
Make action not publish lcm directly and move out of dev/

### PR DESCRIPTION
**Pull request by sammy-tri**
For the platform reviewer:  The parts of this PR not in dev/ should be reviewed as-new, as they have not had proper platform review yet.

You may notice that there is not a unit test in this PR.  I wish I could say that there was one coming as part of the de-dev-ification of the pick and place test, but there's not.  IMO, the logic inside Action is pretty minimal, the unit test would be significantly longer than the code (which is itself part of a larger test), and it's use inside the state machine which will eventually come out of dev/ (probably in the next PR) tests it pretty thoroughly.  I'm willing to add a test if the reviewers think it's worth it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6213)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-:-KlU-qCrlQWLAJ80oqXk:b-ckwj5z)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-:-KlUTJ8CfjXWHG6tgSIy:b-j9ui69)*

**Comment by siyuanfeng-tri** [comment]
Is the monolithic stuff going to depend on this? I don't actually remember. 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlU_V3Cdc-mCjuotJYn:-KlU_V3Cdc-mCjuotJYo:bi4rxov) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.cc#L54)):*
> ```cpp
> 
>   if (get_time_since_action_start(est_state.get_iiwa_time()) > finish_time_ &&
>       est_state.get_iiwa_v().norm() < 1e-1) {
> ```

should probably const the magic number. 

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlU_fkWVuo1LjwO_T0i:-KlU_fkWVuo1LjwO_T0j:b1wncpf) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.cc#L69)):*
> ```cpp
>   msg->utime = est_state.get_wsg_time() * 1e6;
>   // Max aperture.
>   msg->target_position_mm = 110;
> ```

magic number. 

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlU_jFGK4qx49QSPgyr:-KlU_jFGK4qx49QSPgys:b1wncpf) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.cc#L85)):*
> ```cpp
>   if (!ActionStarted()) return false;
> 
>   if (std::abs(est_state.get_wsg_v()) < 1e-2 &&
> ```

magic number. 

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlUZ02nLUjHRrIpILLh:-KlUZ02nLUjHRrIpILLi:b61ab44) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L7)):*
> ```objc
> #include <vector>
> 
> #include "robotlocomotion/robot_plan_t.hpp"
> ```

maybe move this down. 

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlUaUDrMq3jedNHLvXG:-KlUaUDrMq3jedNHLvXH:b-3ytrxa) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L89)):*
> ```objc
>    * Populates @p plan with a robot plan that moves the iiwa arm
>    * described by @p iiwa through the joint positions in @p q at time
>    * @p time.
> ```

Assumes time and q's size matches, and q's dimension matches iiwa's plan cannot be null. 

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlU_-GnTfSJH4eZ5Z-4:-KlU_-GnTfSJH4eZ5Z-5:bjfeu0e) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L112)):*
> ```objc
> 
>  private:
>   double finish_time_;
> ```

my bad, but can you change this to duration? finish_time_ sounds like an absolute time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-:-KlUb2Odb-crGFT_v-LD:bc3nhbk)*

**Comment by sammy-tri** [comment]
It doesn't currently depend on this in master.  It does in my fork.

---

Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlU_V3Cdc-mCjuotJYn:-KlUeFY-75ARoFUts1n6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.cc#L54)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

should probably const the magic number. 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlU_fkWVuo1LjwO_T0i:-KlUeHE1TWqRd46-iE8E:bv8h01c) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.cc#L69)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

magic number. 
</blockquote></details>

I reflowed the documentation a bit...  I'm not sure it's worth making a constant ?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlU_jFGK4qx49QSPgyr:-KlUfW-mfJDaRe_91-qv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.cc#L85)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

magic number. 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlUZ02nLUjHRrIpILLh:-KlUfchCEXrqDBo5zmn1:b-4fhuya) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L7)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

maybe move this down. 
</blockquote></details>

I think this seems right according to https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes if you consider RobotLocomotion/lcmtypes "other libraries .h files"

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlUaUDrMq3jedNHLvXG:-KlUgJHpo4Mvs3mFX19h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L89)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Assumes time and q's size matches, and q's dimension matches iiwa's plan cannot be null. 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlU_-GnTfSJH4eZ5Z-4:-KlUgY-CXetRRS6xKW01:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L112)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

my bad, but can you change this to duration? finish_time_ sounds like an absolute time. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-:-KlUdtsHBSwqk45XVgNm:b-g52pel)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlUZ02nLUjHRrIpILLh:-KlUoTxsnE1f909SIIgY:b7uopjv) ([raw file](https://github.com/robotlocomotion/drake/blob/5550bb10167f745ed923af8c54d1d8cef66f9132/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L7)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think this seems right according to https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes if you consider RobotLocomotion/lcmtypes "other libraries .h files"
</blockquote></details>

ok fine. i usually put it under. i don't really care, up to the platform reviewer. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-:-KlUoiplEpf-0jZUx4j8:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-:-KlUw-Qp3M7EuF5yYSsK:b-gbk9vg)*

**Comment by ggould-tri** [comment]
Super good quality for recently ex-dev code.  I'm willing to settle for a forward promise of test coverage, but I can't judge the extent of that coverage from within this PR.  I assume that it will test MoveJoint, OpenGripper, CloseGripper, and all of the ActionFinished methods, but author should verity that and TODO any that are questionable.

:lgtm: pending minor nits below.

---

Reviewed 7 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlV1Gjz5j6Ief_SmZZk:-KlV1Gk-K8X-B_GAckZs:bn6ml8y) ([raw file](https://github.com/robotlocomotion/drake/blob/24cd16c7d4dcba526e3e264426fa5a1684bb96dc/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L47)):*
> ```objc
> 
>   /**
>    * Returns the time when the action has started.
> ```

FYI "has" here is awkward and unclear (ie, does it return the time only if the action has already started?).

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 73 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlV0DJjkoidIVGcXAUQ:-KlV0DJjkoidIVGcXAUR:bvtolle) ([raw file](https://github.com/robotlocomotion/drake/blob/24cd16c7d4dcba526e3e264426fa5a1684bb96dc/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L73)):*
> ```objc
> 
>  private:
>   double act_start_time_;
> ```

FYI Per Drake style guide, we need initialization here.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 113 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlV0LlEE6zd6nftqnDx:-KlV0LlFJMxbyR3yke8i:bvtolle) ([raw file](https://github.com/robotlocomotion/drake/blob/24cd16c7d4dcba526e3e264426fa5a1684bb96dc/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L113)):*
> ```objc
> 
>  private:
>   double duration_;
> ```

FYI Per Drake style guide, we need initialization here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-:-KlUztYpr5g1vl_ojiMW:b-4tstbz)*

**Comment by sammy-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlV1Gjz5j6Ief_SmZZk:-KlVDJDQM992g9jbpD-g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/24cd16c7d4dcba526e3e264426fa5a1684bb96dc/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L47)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI "has" here is awkward and unclear (ie, does it return the time only if the action has already started?).
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 73 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlV0DJjkoidIVGcXAUQ:-KlVDbJQsyJKSHiCsmaa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/24cd16c7d4dcba526e3e264426fa5a1684bb96dc/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L73)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI Per Drake style guide, we need initialization here.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.h, line 113 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-KlV0LlEE6zd6nftqnDx:-KlVDdH9fG38_T8G9Zi6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/24cd16c7d4dcba526e3e264426fa5a1684bb96dc/drake/examples/kuka_iiwa_arm/pick_and_place/action.h#L113)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI Per Drake style guide, we need initialization here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6213)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6213#-:-KlVOXNrEaP6NlIFsFwS:b-j9ui69)*

**Pull request merged**
