### PR TITLE
Adding single iiwa spheres collision urdf

### PR DESCRIPTION
**Pull request by rcory**
This is the single iiwa arm model, with spheres collision elements.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7141)

### CODE REVIEW

**Comment by rcory** [comment]
@sammy-tri for feature review please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7141#-:-KvECEHyttgizXCFygZt:bjpnywv)*

**Comment by sammy-tri** [comment]
:lgtm:  Seems to be exactly what's described...  :)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7141#-:-KvEF_pnULRRRCQuh-dr:bq4n68)*

**Comment by rcory** [comment]
+@sherm1 for platform review please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7141#-:-KvEG_1aKOH_Mx9Pwylj:bu0bkqk)*

**Comment by sherm1** [comment]
:lgtm: pending change to the urdf comments.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7141#-KvER3eTR3hNEpeQ0n54:-KvER3eTR3hNEpeQ0n55:bw7iijh) ([raw file](https://github.com/robotlocomotion/drake/blob/90e4e5bf2ec285642c4daa4d23c23fc4cffbdfbf/drake/manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf#L4)):*
> ```XML
> 
> 
> 
> ```

BTW per f2f, this comment isn't right because @seancurtis-tri edited it by hand. Please update for full disclosure!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7141#-:-KvERD6ZcRt9dQpBaVPc:b-djdfnv)*

**Comment by rcory** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7141#-KvER3eTR3hNEpeQ0n54:-KvEV93RoT1ea5j4Suis:bves986) ([raw file](https://github.com/robotlocomotion/drake/blob/90e4e5bf2ec285642c4daa4d23c23fc4cffbdfbf/drake/manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per f2f, this comment isn't right because @seancurtis-tri edited it by hand. Please update for full disclosure!
</blockquote></details>

Good catch! Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7141)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7141)*

**Pull request merged**
