### PR TITLE
Text logging using spdlog as an external or stubbed-out

### PR DESCRIPTION
**Pull request by ggould-tri**
This implements #1895 (and is actually just a fleshing out of @jwnimmer-tri 's proposed changeset there, complicated by spdlog deleting the API he implemented in the meantime).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2954)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm_strong: I wonder if we could add a unit test that verifies the logger actually prints stuff to `stdout`: http://stackoverflow.com/questions/3803465/how-to-capture-stdout-stderr-with-googletest

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-:-KNhwfP73lVGzGC4G60R:135978224)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-:-KNi-f657YnuUAZaWQjT:-1868698381)*

**Comment by ggould-tri** [comment]
+@jwnimmer for feature review (as @sammy-tri is about to go on vacation)

**Comment by jwnimmer-tri** [comment]
Derp.
-@jwnimmer @jwnimmer-tri

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-:-KNi0s84nk2evzj3nf8K:-1632421221)*

**Comment by jwnimmer-tri** [comment]
Checkpoint of partial review.

---

Reviewed 7 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 62 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi1YZEJfxmnvt3ZTVE:-KNi1YZFGN1unSF6YY39:1351447196) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/CMakeLists.txt#L62)):*
> ```CMake
> option(WITH_LCM "interprocess communications protocol for visualizers, etc" ON)
> option(WITH_BOT_CORE_LCMTYPES "required LCM types library. only disable if you have it already." ON)
> option(WITH_SPDLOG "spdlog text logging facility.  required for debug logging." ON)
> ```

I wonder if the _"required"_ within _"required for debug logging"_ would be misleading, since this library is not absolutely required?  Is there a way to rephrase that second half, or remove it?

---

*[drake/common/test/text_logging_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi2YyPNJbavyhLxCNs:-KNi2YyPNJbavyhLxCNt:682220232) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/test/text_logging_test.cc#L23)):*
> ```cpp
> GTEST_TEST(TextLoggingTest, SmokeTest) {
>   Streamable obj;
>   drake::log()->trace("drake::log()->trace test: {} {}", "OK", obj );
> ```

META Spurious whitespace before the closing paren.

---

*[drake/systems/controllers/LQR.h, line 48 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi1CexStppMzyVdvi0:-KNi1CeyymTwcVNA69Ez:-1804503909) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/systems/controllers/LQR.h#L48)):*
> ```objc
>   lqr(A, B, Q, R, K, S);
> 
>   SPDLOG_TRACE(drake::log(), "K = {} S = {}", K, S);
> ```

BTW Would we prefer something more like `DRAKE_TRACE("K = {} S = {}", K S);` here, as syntactic sugar?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-:-KNi3n4b7oCfj77HkOPS:-1457324415)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 9 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/common/text_logging.cc, line 14 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi6S2d6IiLv7MFQc9Q:-KNi6S2e5n85uPaMb8dn:-1320023778) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L14)):*
> ```cpp
>   if (!logger) {
>     std::lock_guard<std::mutex> guard(log_mutex);
>     logger = spdlog::stderr_logger_st("console");
> ```

After taking the lock, this code is missing the `if (!logger) { ... }` guard around re-assigning the logger pointer -- otherwise there is a race and two objects might be created accidentally.  That might happen to work with current code, but better safe-than-sorry, perhaps.

---

*[drake/common/text_logging.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi5XOnpLMwIIeDWq31:-KNi5XOnpLMwIIeDWq32:154658391) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L23)):*
> ```cpp
> // A do-nothing logger instance.
> namespace {
> const logger g_logger;
> ```

BTW This is fine as is, but if `logger` ever gained member fields or a vtable, cppguide would disallow this.  Consider moving `g_logger` into a static local in `log()`, which would be correct no matter what `class logger` ever evolved into.

---

*[drake/common/text_logging.cc, line 27 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi5z0CkOJKDF7jrQWe:-KNi5z0DjLTPLsV54M9R:654727767) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L27)):*
> ```cpp
> 
> const std::shared_ptr<logging::logger> log() {
>   return std::shared_ptr<logging::logger>(&g_logger);
> ```

With this `shared_ptr` ctor call, it takes over `g_logger` as the managed object, which means that it gets deleted once the reference count drops to zero.  This seems bad, but I guess happens to work because there is no member data or anything?

I wonder if everything is happier if we change `log()` to return an unowned pointer, instead of shared_ptr.

---

*[drake/common/text_logging.h, line 2 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi3vehy-ij1KIBEBXv:-KNi3vehy-ij1KIBEBXw:-1169807587) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L2)):*
> ```objc
> #pragma once
> ```

I suspect this file deserves a file-overview doxygen, e.g.:
```
@file
This is the entry point for all text logging within Drake.
Once you've included this file, the suggested ways you
should write log messages are:
<pre>
  SomeCode thing;
  log()->...;
</pre>
```

---

*[drake/common/text_logging.h, line 5 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi4ThI9vGOR0MiNrps:-KNi4ThI9vGOR0MiNrpt:-968396426) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L5)):*
> ```objc
> #include <memory>
> 
> #ifdef HAVE_SPDLOG
> ```

Suggest comment for readability "// Before including spdlog, turn on the SPDLOG_DEBUG and SPDLOG_TRACE macros if and only if Drake is being compiled in debug mode."

---

*[drake/common/text_logging.h, line 16 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi57vzSPDxSgJhlTh0:-KNi57vzSPDxSgJhlTh1:-875459886) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L16)):*
> ```objc
> #endif
> 
> #include "drake/drakeCommon_export.h"
> ```

This appears to be unused?

---

*[drake/common/text_logging.h, line 33 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi5mmrcRZZuQZ4jgJg:-KNi5mmrcRZZuQZ4jgJh:75056153) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L33)):*
> ```objc
> /// A stubbed-out version of `spdlog::logger`.  Implements only those methods
> /// that we expect to use, as spdlog's API does change from time to time.
> class logger {
> ```

Disable copy and assign?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/text_logging.cc, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi8Xtd2cXVt6BkccXX:-KNi8Xtd2cXVt6BkccXY:-1555938688) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L17)):*
> ```cpp
>   }
>   return logger;
> }
> ```

Actually, isn't this a more correct, terse, and useful implementation of the log method?

```
logging::logger* log() {
  static std::shared_ptr<logging::logger> logger = spdlog::get("console");
  return logger.get();
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*
<!-- Sent from Reviewable.io -->

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/common/text_logging.cc, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi8Xtd2cXVt6BkccXX:-KNi9IQ9XaCA4zQsnsg5:2104508051) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Actually, isn't this a more correct, terse, and useful implementation of the log method?
> 
> ```
> logging::logger* log() {
>   static std::shared_ptr<logging::logger> logger = spdlog::get("console");
>   return logger.get();
> }
</details>
BTW, do we permit non-POD scoped statics, like your shared ptr above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/text_logging.cc, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi8Xtd2cXVt6BkccXX:-KNiDs_jhK-c4Iu6aY9w:-1287270453) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L17)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> BTW, do we permit non-POD scoped statics, like your shared ptr above?
</details>
As of C++11 it is safe:
_"However, a static POD variable within function scope may be initialized with the result of a function, since its initialization order is well-defined and does not occur until control passes through its declaration."_
-- https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[drake/common/text_logging.cc, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi8Xtd2cXVt6BkccXX:-KNiESd9k_LHHKKnHydU:-594239063) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> As of C++11 it is safe:
> _"However, a static POD variable within function scope may be initialized with the result of a function, since its initialization order is well-defined and does not occur until control passes through its declaration."_
> -- https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables
</details>
but @rico was asking specifically about a non-POD static, which appears to be totally forbidden by that same style guide section, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/text_logging.cc, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi8Xtd2cXVt6BkccXX:-KNiFTjN3ImylT_LKcns:-280749832) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L17)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> but @rico was asking specifically about a non-POD static, which appears to be totally forbidden by that same style guide section, no?
</details>
Ah.  We need to be a bit trickier:
```
namespace {
logging::logger* onetime_create_log() {
  // See if enclosing code has already provided a logger.
  std::shared_ptr<logging::logger> item = spdlog::get("console");
  // If not, make our own default one.
  if (!item) {
    item = spdlog::stderr_logger_st("console");
  }
  // Leak a refcount to the logger forever, for Drake to use forever.
  return (new std::shared_ptr<logging::logger>(item)).get();
}
} // anonymous

logging::logger* log() {
  static logging::logger* g_result = onetime_create_log();
  return g_result;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by sherm1** [comment]
A few minor comments, otherwise :lgtm:.

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 198 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNjjN_sy9UQKB6Y84Ix:-KNjjN_sy9UQKB6Y84Iy:279074048) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/CMakeLists.txt#L198)):*
> ```CMake
> set(bot_core_lcmtypes_IS_PUBLIC TRUE)
> set(spdlog_IS_PUBLIC TRUE)
> set(spdlog_IS_CMAKE_POD TRUE)
> ```

Is this "POD" variable still needed?

---

*[drake/common/text_logging.cc, line 27 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi5z0CkOJKDF7jrQWe:-KNjfKXxe33qn0h_uNe6:-856515223) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> With this `shared_ptr` ctor call, it takes over `g_logger` as the managed object, which means that it gets deleted once the reference count drops to zero.  This seems bad, but I guess happens to work because there is no member data or anything?
> 
> I wonder if everything is happier if we change `log()` to return an unowned pointer, instead of shared_ptr.
</details>
BTW, +1 for using an unadorned pointer for the logger.

---

*[drake/common/text_logging.h, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNjfnwtUjqQPjZhOdrQ:-KNjfnwtUjqQPjZhOdrR:124185161) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L13)):*
> ```objc
> #include <spdlog/fmt/ostr.h>
> #undef SPDLOG_DEBUG_ON
> #undef SPDLOG_TRACE_ON
> ```

Undef'ing these means subsequent code can't check whether they were enabled. Since they are properly "namespaced" with `SPDLOG` I would rather they stayed defined in case there is some out of band debug/trace code needed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-:-KNjjX2V13YFEkI-1XUp:-1582842729)*

**Comment by sherm1** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 198 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNjjN_sy9UQKB6Y84Ix:-KNlQv8dQaxRGy61TxDM:1391871242) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/CMakeLists.txt#L198)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Is this "POD" variable still needed?
</details>
I have absolutely no idea what this actually does, so I don't know.  But I think it's required to get the build to invoke cmake inside spdlog?

---

*[drake/common/text_logging.cc, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi8Xtd2cXVt6BkccXX:-KNlSOOrE7ncQ35_z9_N:-1260611053) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Ah.  We need to be a bit trickier:
> ```
> namespace {
> logging::logger* onetime_create_log() {
>   // See if enclosing code has already provided a logger.
>   std::shared_ptr<logging::logger> item = spdlog::get("console");
>   // If not, make our own default one.
>   if (!item) {
>     item = spdlog::stderr_logger_st("console");
>   }
>   // Leak a refcount to the logger forever, for Drake to use forever.
>   return (new std::shared_ptr<logging::logger>(item)).get();
> }
> } // anonymous
> 
> logging::logger* log() {
>   static logging::logger* g_result = onetime_create_log();
>   return g_result;
> }
> ```
</details>
Slightly confused that you have omitted all of the mutex work there.  Is this because `spdlog::details::registry::instance` is mutexed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/text_logging.cc, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi8Xtd2cXVt6BkccXX:-KNlV01HgbkKgdZ1Qqga:-1567131772) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L17)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Slightly confused that you have omitted all of the mutex work there.  Is this because `spdlog::details::registry::instance` is mutexed?
</details>
C++11 guarantees that `onetime_create_log_` will only ever be called once.
http://en.cppreference.com/w/cpp/language/storage_duration#Static_local_variables

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[drake/common/text_logging.cc, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi8Xtd2cXVt6BkccXX:-KNlZoAZksmd91JnzhET:849236067) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> C++11 guarantees that `onetime_create_log_` will only ever be called once.
> http://en.cppreference.com/w/cpp/language/storage_duration#Static_local_variables
</details>
Wow, that is very pleasant.

---

*[drake/common/text_logging.cc, line 27 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi5z0CkOJKDF7jrQWe:-KNlZL8RpNpf6eDaxen0:517469153) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, +1 for using an unadorned pointer for the logger.
</details>
The logic for `shared_ptr` is that spdlog `get` and `basic_logger_` methods returned `shared_ptr`.  But clearly that does not create requirements on our API, since as is noted above we can simply statically leak a `shared_ptr` and never worry about it again.  I will fix this.

---

*[drake/common/text_logging.h, line 16 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi57vzSPDxSgJhlTh0:-KNlZwbxRbWyGS2R53Lc:554098608) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This appears to be unused?
</details>
... which is why the windows build broke.  Adding a use of it in a moment.

---

*[drake/common/text_logging.h, line 33 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi5mmrcRZZuQZ4jgJg:-KNl_6ATDUMHXBYdCp5p:-1252380979) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Disable copy and assign?
</details>
It seems like `spdlog::logger` does, so I will as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 62 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi1YZEJfxmnvt3ZTVE:-KNlcuxA8KxrcgSxXQvk:566770395) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/CMakeLists.txt#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I wonder if the _"required"_ within _"required for debug logging"_ would be misleading, since this library is not absolutely required?  Is there a way to rephrase that second half, or remove it?
</details>
Rephrased.

---

*[drake/common/text_logging.cc, line 14 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi6S2d6IiLv7MFQc9Q:-KNlcqRX0ppUiyUIVP0J:2051647803) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> After taking the lock, this code is missing the `if (!logger) { ... }` guard around re-assigning the logger pointer -- otherwise there is a race and two objects might be created accidentally.  That might happen to work with current code, but better safe-than-sorry, perhaps.
</details>
Per your suggestion below, this code is going away entirely.

---

*[drake/common/text_logging.h, line 2 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi3vehy-ij1KIBEBXv:-KNlciwgIAAAz_nwnYr7:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I suspect this file deserves a file-overview doxygen, e.g.:
> ```
> @file
> This is the entry point for all text logging within Drake.
> Once you've included this file, the suggested ways you
> should write log messages are:
> <pre>
>   SomeCode thing;
>   log()->...;
> </pre>
> ```
</details>
Done.

---

*[drake/common/text_logging.h, line 5 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi4ThI9vGOR0MiNrps:-KNl_qDDMBt6p63z-49n:662168636) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Suggest comment for readability "// Before including spdlog, turn on the SPDLOG_DEBUG and SPDLOG_TRACE macros if and only if Drake is being compiled in debug mode."
</details>
Done, and clarified in more detail that the macros remain available as no-ops regardless.

---

*[drake/common/text_logging.h, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNjfnwtUjqQPjZhOdrQ:-KNlckvC_c7sWxTRLwA8:1645350990) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.h#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Undef'ing these means subsequent code can't check whether they were enabled. Since they are properly "namespaced" with `SPDLOG` I would rather they stayed defined in case there is some out of band debug/trace code needed. 
</details>
I agree.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/text_logging.cc, line 27 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi5z0CkOJKDF7jrQWe:-KNlnKnqh7Us4EXilTSP:-99871613) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L27)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> The logic for `shared_ptr` is that spdlog `get` and `basic_logger_` methods returned `shared_ptr`.  But clearly that does not create requirements on our API, since as is noted above we can simply statically leak a `shared_ptr` and never worry about it again.  I will fix this.
</details>
It doesn't seem correct to still have a shared_ptr here in r3, while returning a bare pointer.  Shouldn't it just be `return &g_logger;`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/text_logging.cc, line 27 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi5z0CkOJKDF7jrQWe:-KNlpAyLllnpfHG8PmPT:1436907783) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> It doesn't seem correct to still have a shared_ptr here in r3, while returning a bare pointer.  Shouldn't it just be `return &g_logger;`?
</details>
Quite right.  I was killing off shared_ptrs and missed one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

Seems ready to merge, modulo other reviewers hitting the "Ack" button, and Jenkins finishing.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-:-KNlqfL2bRIY1Pxk7lcI:-1691941573)*

**Comment by sherm1** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by ggould-tri** [comment]
@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/text_logging.cc, line 22 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNmDa29_yk5o8iSxCL3:-KNmDa29_yk5o8iSxCL4:412036496) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7922f6f240e0d0e3ef151f373553d3a1e4652a/drake/common/text_logging.cc#L22)):*
> ```cpp
>   return result;
> }
> } // anonymous
> ```

BTW, TTBOMK, we've always marked this as:

```
}  // namespace
```

---

*[drake/common/text_logging.cc, line 26 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNmDl0tKInPjVxVOE_k:-KNmDl0uavCoiRZnAZUd:1038387988) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7922f6f240e0d0e3ef151f373553d3a1e4652a/drake/common/text_logging.cc#L26)):*
> ```cpp
> logging::logger* log() {
>   // The following line creates a static shared_ptr to the logger; this
>   // guarantees the underling logger object will not be dtor'ed.
> ```

BTW, Is "dtor'ed" a word? Why not "destructed"?

---

*[drake/common/text_logging.cc, line 37 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNmE-KnbDICYo4WlUNj:-KNmE-KorNmpSrhMli5Y:-1517326773) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7922f6f240e0d0e3ef151f373553d3a1e4652a/drake/common/text_logging.cc#L37)):*
> ```cpp
> namespace {
> const logger g_logger;
> }  // anon namespace
> ```

BTW, some comment here about:

```
}  // namespace
```

(for consistency with other files in Drake)

---

*[drake/common/text_logging.h, line 20 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNmEKKlZ7NDzN-4GoQ6:-KNmEKKlZ7NDzN-4GoQ7:1913218574) ([raw file](https://github.com/robotlocomotion/drake/blob/ca7922f6f240e0d0e3ef151f373553d3a1e4652a/drake/common/text_logging.h#L20)):*
> ```objc
> </pre>
> To log objects that are expensive to serialize, these macros will not be
> compiled if debug is not set:
> ```

BTW, can you clarify what "debug is not set" means? For example, does that mean the compile mode is not "Debug"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by ggould-tri** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/text_logging.cc, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2954#-KNi8Xtd2cXVt6BkccXX:-KNmcRTb_6H5NQDP_bak:2084204289) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef3f93c4fd903de68820247a0b00e5508591180/drake/common/text_logging.cc#L17)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Wow, that is very pleasant.
</details>
Pinging @david-german-tri who is blocking this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2954)*

**Pull request merged**
