### PR TITLE
[fem] Add discrete time integrator

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for feature review or delegation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714#-:-MxGpViD7no8dCi4e2vO:b-h69av2)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature checkpoint.

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714#-:-MxHkrvF47UDoBHZqgyS:bvpqlh3)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/fem/discrete_time_integrator.h, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHWVjB-JdNH6N23i2n:-MxHWVjB-JdNH6N23i2o:bllywgp) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L23)):*
> ```objc
>         aₙ₊₁ = αₐ z + bₐ
> 
>  For example, for the Newmark-beta scheme, if one chooses z = a, we get
> ```

BTW consider quickly summarizing Newmark-beta here so it is easy to see what's going on here. I had to wade through the [Wikipedia page](https://en.wikipedia.org/wiki/Newmark-beta_method) and change notation in order to check the algebra :(. Here is my attempt with your notation:



_Code snippet:_
```objc
qₙ₊₁ = qₙ + δt vₙ + δt² ((½ − β)aₙ + β aₙ₊₁)
vₙ₊₁ = vₙ + δt ((1 − γ)aₙ + γ aₙ₊₁)
aₙ₊₁ = f(qₙ₊₁,vₙ₊₁) 
```
___
*[multibody/fem/discrete_time_integrator.h, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHVglXB4KMUvslkMd3:-MxHVglXB4KMUvslkMd4:bjxf3v1) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L25)):*
> ```objc
>  For example, for the Newmark-beta scheme, if one chooses z = a, we get
> 
>         qₙ₊₁ = qₙ + dt ⋅ vₙ + dt² ⋅ [β ⋅ z + (0.5−β) ⋅ aₙ].
> ```

BTW consider using δt rather than dt to avoid having this look like a differential (e.g. dz used below, and if you had to define it q̇=dq/dt). (We had to change to δt in the papers to avoid confusion.)

You still have to use dt in the code but you can do better in comments.
___
*[multibody/fem/discrete_time_integrator.h, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHdBjk9Q77akA5Qqa1:-MxHdBjk9Q77akA5Qqa2:b-3ja9rt) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L31)):*
> ```objc
>  On the other hand, if one chooses z = v instead for the same scheme, we get
> 
>         qₙ₊₁ = xₙ + dt ⋅ (β/γ ⋅ z +  (1 - β/γ) ⋅ vₙ) + dt² ⋅ (0.5 − β/γ) ⋅ aₙ.
> ```

typo: xₙ -> qₙ
___
*[multibody/fem/discrete_time_integrator.h, line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHCz-kB0jyqzqMHjPC:-MxHCz-kB0jyqzqMHjPD:b-fj2t46) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L69)):*
> ```objc
>    value of the unknown variable z.
>    @param[in]  prev_state        The state at the previous time step.
>    @param[in]  unknown_variable  The unknown variable z.
> ```

BTW this seems an odd name here since the value of z is known, not unknown! How about `value_of_unknown` or just `z` (matches `dz` above)?
___
*[multibody/fem/discrete_time_integrator.h, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHkJVa72deZAmTEMKn:-MxHkJVbAI-7U7Vh18eN:b-ps5bjb) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L88)):*
> ```objc
>   /* Derived classes must override this method to implement the NVI
>    get_weights(). */
>   virtual Vector3<T> do_get_weights() const = 0;
> ```

minor: should call this DoGetWeights(). It can't be inlined since it's virtual and a user might do something expensive to calculate the returned vector. So it's not a great candidate for snake_case treatment.
___
*[multibody/fem/discrete_time_integrator.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHkmLFAtQ3yyaeq0ev:-MxHkmLFAtQ3yyaeq0ew:b-4j4hcb) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L102)):*
> ```objc
>    AdvanceOneTimeStep(). */
>   virtual void DoAdvanceOneTimeStep(const FemState<T>& prev_state,
>                                     const VectorX<T>& unknowns,
> ```

BTW `z` here?

**Review by xuchenhan-tri — COMMENTED** [review]
Comments in the header addressed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714#-:-MxHsWvZB88samxDfR-Y:bachvxn)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

___
*[multibody/fem/discrete_time_integrator.h, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHWVjB-JdNH6N23i2n:-MxHrEKw0YIhMAaS27gP:bc4ro68) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider quickly summarizing Newmark-beta here so it is easy to see what's going on here. I had to wade through the [Wikipedia page](https://en.wikipedia.org/wiki/Newmark-beta_method) and change notation in order to check the algebra :(. Here is my attempt with your notation:
</blockquote></details>

Done. Thanks for the code snippet.
___
*[multibody/fem/discrete_time_integrator.h, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHVglXB4KMUvslkMd3:-MxHqZyF9jAgD5zqNi85:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider using δt rather than dt to avoid having this look like a differential (e.g. dz used below, and if you had to define it q̇=dq/dt). (We had to change to δt in the papers to avoid confusion.)

You still have to use dt in the code but you can do better in comments.
</blockquote></details>

Done.
___
*[multibody/fem/discrete_time_integrator.h, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHdBjk9Q77akA5Qqa1:-MxHqRPwCKyGO8MX-_oS:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L31)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: xₙ -> qₙ
</blockquote></details>

Done, thanks.
___
*[multibody/fem/discrete_time_integrator.h, line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHCz-kB0jyqzqMHjPC:-MxHrl5o9xwklnxd2GNp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this seems an odd name here since the value of z is known, not unknown! How about `value_of_unknown` or just `z` (matches `dz` above)?
</blockquote></details>

Done.
___
*[multibody/fem/discrete_time_integrator.h, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHkJVa72deZAmTEMKn:-MxHrnUe5kVHcPrS6aW6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L88)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should call this DoGetWeights(). It can't be inlined since it's virtual and a user might do something expensive to calculate the returned vector. So it's not a great candidate for snake_case treatment.
</blockquote></details>

Done.
___
*[multibody/fem/discrete_time_integrator.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16714#-MxHkmLFAtQ3yyaeq0ev:-MxHrriN9aGJWyyeK4Q7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad5a23ee2d4c3c90723a2eec2dcc8ef3c5be9ac6/multibody/fem/discrete_time_integrator.h#L102)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `z` here?
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714#-:-MxWH5xL-BZJrPqyPeoS:b-n0m1lx)* status: needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
+@sammy-tri for platform review please, per rotation

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714#-:-MxWHC8z4an0Xf7J6tDk:buhbkki)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by amcastro-tri — COMMENTED** [review]
my 2 cents on the naming/semantics of this class. Feel free to ignore if you resonate stronger with "integrator"

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714#-:-Mx_HaKFCBO0VKu098cW:b-wtgcpk)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri and @xuchenhan-tri)

___
*[multibody/fem/discrete_time_integrator.h, line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16714#-Mx_GjvvEfrEbNiEskky:-Mx_GjvvEfrEbNiEskkz:b3jffhx) ([raw file](https://github.com/robotlocomotion/drake/blob/01f870f67742c81641edb206d78cfe85a2ec25d5/multibody/fem/discrete_time_integrator.h#L45)):*
> ```objc
>  @tparam_nonsymbolic_scalar */
> template <typename T>
> class DiscreteTimeIntegrator {
> ```

the word "integrator" overloads a pretty strong concept in our `systems::analysis` framework.
This class actually implements something quite different.
Per documentation, it's a map from the unknown variable z to the state variables q,v,a. 
What about another name? like `TimeIntegrationMap`? other alternatives?
___
*[multibody/fem/discrete_time_integrator.h, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16714#-Mx_HChL4pJDs1aFBYGp:-Mx_HChL4pJDs1aFBYGq:buuuqfx) ([raw file](https://github.com/robotlocomotion/drake/blob/01f870f67742c81641edb206d78cfe85a2ec25d5/multibody/fem/discrete_time_integrator.h#L79)):*
> ```objc
>    @pre next_state != nullptr.
>    @pre The sizes of `prev_state`, `z`, and `next_state` are compatible. */
>   void AdvanceOneTimeStep(const FemState<T>& prev_state, const VectorX<T>& z,
> ```

ditto here. This is not "advancing" the time step, but really applying the documented map:
 qₙ₊₁ = αₚ z + bₚ
vₙ₊₁ = αᵥ z + bᵥ
aₙ₊₁ = αₐ z + bₐ

Maybe the method could be renamed to consistently match method `UpdateStateFromChangeInUnknowns()` to something like `UpdateStateFromUnknowns()`?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri and @sammy-tri)

___
*[multibody/fem/discrete_time_integrator.h, line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16714#-Mx_GjvvEfrEbNiEskky:-Mx_N8-u0keEC32WlVpt:b6y79tt) ([raw file](https://github.com/robotlocomotion/drake/blob/01f870f67742c81641edb206d78cfe85a2ec25d5/multibody/fem/discrete_time_integrator.h#L45)):*
> the word "integrator" overloads a pretty strong concept in our systems::analysis framework.

The word "Discrete" and the fact that this is in `fem` name space differentiates this class from that in systems::analysis framework.

> Per documentation, it's a map from the unknown variable z to the state variables q,v,a.

This description is true for many common time integration schemes (e.g. Euler). Calling it `TimeIntegrationMap` instead of an integrator/integration scheme adds more confusion IMO. I took the name DiscreteTimeIntegrator from Simulink.
___
*[multibody/fem/discrete_time_integrator.h, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16714#-Mx_HChL4pJDs1aFBYGp:-Mx_Mbu-7pgEZ9rTPW6M:b-6n6q2g) ([raw file](https://github.com/robotlocomotion/drake/blob/01f870f67742c81641edb206d78cfe85a2ec25d5/multibody/fem/discrete_time_integrator.h#L79)):*
> This is not "advancing" the time step.

I don't follow this comment. This function takes a previous time step state and produces the state at the next time step. It's advancing time in that sense.

I'm indifferent about the proposed name here. I'm ok with changing to `UpdateStateFromUnknowns()`  if there's a compelling reason.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri and @sammy-tri)

___
*[multibody/fem/discrete_time_integrator.h, line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16714#-Mx_GjvvEfrEbNiEskky:-Mx_UrCr-Y9emsfpLDIo:b-4hc1y6) ([raw file](https://github.com/robotlocomotion/drake/blob/01f870f67742c81641edb206d78cfe85a2ec25d5/multibody/fem/discrete_time_integrator.h#L45)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> the word "integrator" overloads a pretty strong concept in our systems::analysis framework.

The word "Discrete" and the fact that this is in `fem` name space differentiates this class from that in systems::analysis framework.

> Per documentation, it's a map from the unknown variable z to the state variables q,v,a.

This description is true for many common time integration schemes (e.g. Euler). Calling it `TimeIntegrationMap` instead of an integrator/integration scheme adds more confusion IMO. I took the name DiscreteTimeIntegrator from Simulink.
</blockquote></details>

The Simulink block is actually an interesting example.
I am more from the school of [GSL](https://www.mathworks.com/help/simulink/slref/discretetimeintegrator.html) and similar packages, where integrators take some sort of functor. Our framework is in this family, where our glorified functor is a `System`.

In any case, my job is done here. I just wanted to bring the option to your attention now that you are taking these out of dev. The answer "it's my personal preference" is ok for me.


Interesting observation for @sherm1 (we can discuss on other venue): the [DiscreteTimeIntegrator](https://www.mathworks.com/help/simulink/slref/discretetimeintegrator.html) in Simulink, according to the equations in the docs, apparently can dissambigutate inputs evaluated at previous time step or current step? that sounds strange, but I wonder if something has to be done regarding "discrete input ports".

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[multibody/fem/discrete_time_integrator.h, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16714#-Mx_HChL4pJDs1aFBYGp:-Mx_W-Z534aEmECTzBS1:bt0koq5) ([raw file](https://github.com/robotlocomotion/drake/blob/01f870f67742c81641edb206d78cfe85a2ec25d5/multibody/fem/discrete_time_integrator.h#L79)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> This is not "advancing" the time step.

I don't follow this comment. This function takes a previous time step state and produces the state at the next time step. It's advancing time in that sense.

I'm indifferent about the proposed name here. I'm ok with changing to `UpdateStateFromUnknowns()`  if there's a compelling reason.
</blockquote></details>

Per comment above. When I think of "integrators" I think of a GSL framework or something like our won systems framework, where we take a functor and do whatever it takes to perform a "step" (that might entail computing Jacobians, using Newton's method, you name it).
Again, the analogy with the Simulink block above is good enough for me.

**Review by sammy-tri — COMMENTED** [review]
:lgtm: with a nit about a class member variable name

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714#-:-Mxa2-mfB2G23WpBRvUS:b-jkkc0c)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[multibody/fem/test/discrete_time_integrator_test.cc, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16714#-Mxa1s8QBc203r2zbJP2:-Mxa1s8QBc203r2zbJP3:b-upx6j) ([raw file](https://github.com/robotlocomotion/drake/blob/01f870f67742c81641edb206d78cfe85a2ec25d5/multibody/fem/test/discrete_time_integrator_test.cc#L63)):*
> ```cpp
> 
>   std::unique_ptr<internal::FemStateSystem<double>> fem_state_system_;
>   DummyScheme scheme{kDt};
> ```

nit: I think this should be named `scheme_` as a member variable.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform) (waiting on @sammy-tri and @sherm1)

___
*[multibody/fem/test/discrete_time_integrator_test.cc, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16714#-Mxa1s8QBc203r2zbJP2:-Mxa8nOx1rgvn-RGYdqU:ba4di8c) ([raw file](https://github.com/robotlocomotion/drake/blob/01f870f67742c81641edb206d78cfe85a2ec25d5/multibody/fem/test/discrete_time_integrator_test.cc#L63)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: I think this should be named `scheme_` as a member variable.
</blockquote></details>

Done thanks.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16714)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
