### PR TITLE
manipulation_station: Use LcmInterfaceSystem

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #10981.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11119)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@RussTedrake Here's the hero testing that I did on this PR (below).  It _seems_ like everything is working fine, but there is little-to-no test coverage of LCM message flow.  Is there something else I should test?  Or someone I should tag to do more testing?  (I couldn't get meshcat for this example working, either on master or with this PR.)

```console
$ bazel build //examples/manipulation_station/... //tools:drake_visualizer

$ bazel-bin/tools/drake_visualizer &
Drake Scripts:
  Specified: --use_builtin_scripts=all
  Available: --use_builtin_scripts=contact,frame,image,time
Contact Visualizer subscriber added.
DrakeLcmImageViewer: Defer setup until 'DRAKE_RGBD_CAMERA_IMAGES' is received

$ bazel-bin/examples/manipulation_station/mock_station_simulation &
[2019-04-01 21:54:57.116] [console] [warning] The IiwaCommandReceiver "command_message" port is deprecated and will be removed on 2019-05-01; use "lcmt_iiwa_command" instead.
Problem creating accessible interface for:  QVTKOpenGLWindow(0x36b3bd0) 
Make sure to deploy Qt with accessibility plugins.

$ bazel-bin/examples/manipulation_station/joint_teleop --hardware &
/home/jwnimmer/jwnimmer-tri/drake/bazel-bin/examples/manipulation_station/joint_teleop.runfiles/drake/examples/manipulation_station/joint_teleop.py:20: DrakeDeprecationWarning: 
Warning:
    Deprecated. Please use ``pydrake.common.eigen_geometry`` instead. This module
    will be removed on or after 2019-03-15.

    Please see `help(pydrake.common.deprecation)` for more information.
  from pydrake.util.eigen_geometry import Isometry3
Waiting for IIWA_STATUS message...Received!
Waiting for SCHUNK_WSG_STATUS message...Received!
/home/jwnimmer/jwnimmer-tri/drake/bazel-bin/examples/manipulation_station/joint_teleop.runfiles/drake/examples/manipulation_station/joint_teleop.py:100: DrakeDeprecationWarning: '_DoCalcTimeDerivatives' is deprecated and will be removed on or around 2019-06-15. Please call 'DoCalcTimeDerivatives' instead.
    Please see `help(pydrake.common.deprecation)` for more information.
  simulator.AdvanceTo(args.duration)

# ... move the sliders randomly and watch the robot dance ...

abort: Failure at multibody/plant/multibody_plant.cc:1529 in CalcImplicitStribeckResults(): condition 'info == ImplicitStribeckSolverResult::kSuccess' failed.
```

**Comment by kmuhlrad** [comment]
Sure, I can do it later this afternoon

**Comment by kmuhlrad** [comment]
Everything works fine for me. In order to test this, I rebuild the python bindings and run

```
~/drake$ python examples/manipulation_station/joint_teleop.py --meshcat --open_browser
```

I get a bunch of deprecation warnings, but the behavior hasn't changed.

**Comment by jwnimmer-tri** [comment]
Thanks @kmuhlrad!

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.  (I'll still wait for Russ to chime in, but extra eyes now seems good.)

**Comment by RussTedrake** [comment]
Haven’t gotten hands on keys, but i trust Katie’s test.  Please go ahead with this

**Pull request merged**
