### PR TITLE
Bump optitrack driver version for NatNet3/build fixes

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7142)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@sherm1 for all review per rotation   Cc: @jamiesnape who's had to deal with other changes to this library/driver lately.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7142#-:-KvEEVR24TO6u1ZQkbc7:b-c9lkyx)*

**Comment by sherm1** [comment]
Platform :lgtm:, assuming it works! Does this need a feature reviewer, @sammy-tri?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7142#-:-KvEQOOFofQ5nrmRWwKF:b-msna8w)*

**Comment by sammy-tri** [comment]
I was wavering back and forth on the feature review question...   but I don't really see the downside to it, so, sure, +@rcory for feature review (and with thanks for helping me test the changes!)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7142#-:-KvESTqMo8lw2NARNFkS:burigun)*

**Comment by rcory** [comment]
:lgtm:, tested and works. (Sorry I missed the review request on this earlier!)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7142#-:-KvYdS9DHmpCSXkpxdEX:bbetf9d)*

**Pull request merged**
