### PR TITLE
Remove the zero terms in the polynomial

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5364)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.cc, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeEj6gBme0UIdiN19QZ:-KeEj6gBme0UIdiN19Q_:b-405sz8) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L177)):*
> ```cpp
>   auto it = polynomial->find(monomial);
>   if (it == polynomial->end()) {
>     polynomial->emplace_hint(it, monomial, coefficient);
> ```

How about having the following code here?
```
  } else if (is_zero(it->second + coefficient)) {
    polynomial->erase(it);
```

---

*[drake/common/monomial.cc, line 405 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeEjJ2iDOLYEgoRa5sh:-KeEjJ2iDOLYEgoRa5si:bvrope6) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L405)):*
> ```cpp
>     bool is_zero_term(true);
>     if (is_constant(it->second) && is_zero(it->second)) {
>       is_zero_term = true;
> ```

Once we have the above code, this branch is not necessary. (We can have `DRAKE_ASSERT(!is_zero(it->second));` if you like)

---

*[drake/common/monomial.cc, line 406 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeEjWrOlJL5pYZl2oqw:-KeEjWrOlJL5pYZl2oqx:b-gvy21c) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L406)):*
> ```cpp
>     if (is_constant(it->second) && is_zero(it->second)) {
>       is_zero_term = true;
>     } else if (it->second.is_polynomial()) {
> ```

I found that all our testcases pass even if I remove this branch manually. Do we need more test cases? or is this part not necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.cc, line 405 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeEjJ2iDOLYEgoRa5sh:-KeEk7iRh-YFe6KHaisj:b9iqrpx) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L405)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Once we have the above code, this branch is not necessary. (We can have `DRAKE_ASSERT(!is_zero(it->second));` if you like)
</blockquote></details>

FYI, `is_zero` includes constant-check, so `is_constant` is unnecessary here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.cc, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeEj6gBme0UIdiN19QZ:-KeFTqSSqK5j6cYvD1xY:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L177)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

How about having the following code here?
```
  } else if (is_zero(it->second + coefficient)) {
    polynomial->erase(it);
```
</blockquote></details>

Done. Good call.

---

*[drake/common/monomial.cc, line 405 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeEjJ2iDOLYEgoRa5sh:-KeFUL09AviGEbuJDNKB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L405)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, `is_zero` includes constant-check, so `is_constant` is unnecessary here.
</blockquote></details>

Done.

---

*[drake/common/monomial.cc, line 406 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeEjWrOlJL5pYZl2oqw:-KeFUNZradkJ3RubzrMo:bh8zv1x) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L406)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I found that all our testcases pass even if I remove this branch manually. Do we need more test cases? or is this part not necessary?
</blockquote></details>

Done. Add a test that will cover this branch. Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/common/monomial.cc, line 410 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeFeA4aMiMHR6BlSyVm:-KeFeA4dd0YtxN37Rfbz:bv1o79f) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L410)):*
> ```cpp
>       // is a zero polynomial, by decomposing it->second into monomials,
>       // and check if the constant coefficient for each term is zero.
>       MonomialToCoefficientMap coeff_map = DecomposePolynomialVisitor().Visit(
> ```

I guess this should be a recursive call?
```c++
DecomposePolynomialIntoMonomial(it->second, it->second.GetVariables());
```

---

*[drake/common/monomial.cc, line 417 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeFeO2fjxdv9k6JKCCL:-KeFeO2fjxdv9k6JKCCM:bmih5qg) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L417)):*
> ```cpp
>           is_zero_term = false;
>           break;
>         }
> ```

Otherwise we need to worry about the case `p.second` is another zero-polynomial-after-expansion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/common/monomial.cc, line 410 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeFeA4aMiMHR6BlSyVm:-KeFebNCSnrhc_SS7q2N:b-gurwuq) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L410)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I guess this should be a recursive call?
```c++
DecomposePolynomialIntoMonomial(it->second, it->second.GetVariables());
```

</blockquote></details>

Or you can use one-liner `is_zero_term = is_zero(it->second.Expand());`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/common/monomial.cc, line 427 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeFjD-LR5AgUZUbXAjy:-KeFjD-LR5AgUZUbXAjz:bojiken) ([raw file](https://github.com/robotlocomotion/drake/blob/40303187012f42bbd0c1759d4d38a2153b6e5bc4/drake/common/monomial.cc#L427)):*
> ```cpp
>       // If the coefficient is a constant, then it cannot be zero, since we have
>       // deleted term with zero constant coefficient already.
>       DRAKE_ASSERT(!is_zero(it->second));
> ```

FYI, this assertion fails when `e = 0.0` and `it->first = {}` and we have the case in `mathematical_program_test`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/common/monomial.cc, line 417 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeFeO2fjxdv9k6JKCCL:-KeFiZ9vKXXpaACN3Sab:b-dxpj5t) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L417)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Otherwise we need to worry about the case `p.second` is another zero-polynomial-after-expansion.
</blockquote></details>

No that should not happen. The zero polynomial case only happens if we decompose a polynomial w.r.t a partial subset of its variables. If we decompose the polynomial w.r.t all its variables, then each coefficient should be a constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.cc, line 427 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeFjD-LR5AgUZUbXAjy:-KeFkgpnAY3qykEzfIkh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/40303187012f42bbd0c1759d4d38a2153b6e5bc4/drake/common/monomial.cc#L427)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this assertion fails when `e = 0.0` and `it->first = {}` and we have the case in `mathematical_program_test`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 417 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeFeO2fjxdv9k6JKCCL:-KeFm5bNOKoKyXqbM1dH:b-ldo9wk) ([raw file](https://github.com/robotlocomotion/drake/blob/36a329a1457c7bb3327b7346fd4b1bfdbedfdf03/drake/common/monomial.cc#L417)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

No that should not happen. The zero polynomial case only happens if we decompose a polynomial w.r.t a partial subset of its variables. If we decompose the polynomial w.r.t all its variables, then each coefficient should be a constant.
</blockquote></details>

I see. Got it, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by soonho-tri** [comment]
:lgtm: (aside a comment)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/decompose_polynomial_test.cc, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeFnmBFsQQiD5rvKBBk:-KeFnmBG41TjV5MzoHo2:b-fm3lwu) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe7db8a726c3a05a1ad94a7f781e41b0972838d/drake/common/test/decompose_polynomial_test.cc#L45)):*
> ```cpp
>   EXPECT_EQ(map.size(), map_expected.size());
>   symbolic::Expression e_expected(0);
>   if (map.size() != 0) {
> ```

FYI, I think this check is not necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-:-KeFnqi35K-zZvJ_2Yww:btfj096)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/decompose_polynomial_test.cc, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-KeFnmBFsQQiD5rvKBBk:-KeFoKMwkRoh-M_jbC96:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe7db8a726c3a05a1ad94a7f781e41b0972838d/drake/common/test/decompose_polynomial_test.cc#L45)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, I think this check is not necessary.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-:-KeFoppJMNH7pGwAC3y1:b-trzqz1)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 
:lgtm: 

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-:-KeFyTCPQoem480NWP08:b-kmrewj)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5364#-:-KeFyd7jia-F3obJ5srz:b-l70wzf)*

**Pull request merged**
