### PR TITLE
Do not error when downloading ibex on Focal

### PR DESCRIPTION
**Pull request by jamiesnape**
We do have a Focal package, but `setup_new_deb_archive` needs reworking to be able to use it. 

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13345)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
Looks like //solvers:dreal_solver_test passes so maybe this is good enough for now pending #13219.

**Comment by jwnimmer-tri** [comment]
SGTM.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Pull request merged**
