### PR TITLE
Add Python bindings to CalcRpyDtFromAngularVelocityInChild().

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19074)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR [19074](https://github.com/RobotLocomotion/drake/pull/19074) resolves issue [18984](https://github.com/RobotLocomotion/drake/issues/18984).

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19074#-:-NR_TZuQ1L5IclT0SWRZ:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
Feature review -@sherm1 
Feature review +@SeanCurtis-TRI 
Please do Platform review too?  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19074#-:-NRdXpQe76rCT2DiYuqg:b-p1hihr)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
My suggestion is that "add bindings" always just go to the on-call platform reviewer.  They don't need feature review, and by batching them into on-call we avoid interrupting people who are not on-call.

**Review by mitiguy — COMMENTED** [review]
Feature review -@SeanCurtis-TRI 
+@rpoyner-tri for both reviews

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19074#-:-NRdz14yCw0kti6ayDGP:b1y9pk)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19074#-:-NReKmw73awBDMc0bUef:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @mitiguy)

**Pull request merged**
