### PR TITLE
[solvers] Re-implement MakeSolver to enumerate over a table

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Inspired by #15325 as a way to avoid extra constructors.

\CC @hongkai-dai FYI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15327)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for commentary (and maybe review), please.

I am not 100% sure this extra complexity is warranted, but on balance defining the list of known solvers in _one_ place seems valuable.

As you rework the heuristics in #15320, perhaps it's possible that phrasing your priority lists in terms of SolverId will be easier than writing out `IsMatch<SomeSolver>`.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15327)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/choose_best_solver.cc, line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15327#-MdyVrpCDNyOuiyVZkWh:-MdyVrpCDNyOuiyVZkWi:bqzljwf) ([raw file](https://github.com/robotlocomotion/drake/blob/31349695935eb6b2e3bec883383d728c9bcee5a1/solvers/choose_best_solver.cc#L39)):*
> ```cpp
> 
>   template <typename SomeSolver>
>   static constexpr StaticSolverInterface Make() {
> ```

Curious why we need `constexpr` here? I understand using `static constexpr` for data member, but why we need it for a function?
___
*[solvers/choose_best_solver.cc, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15327#-MdyY9yj2B3R4mSwn-zu:-MdyY9yj2B3R4mSwn-zv:bdyzp5k) ([raw file](https://github.com/robotlocomotion/drake/blob/31349695935eb6b2e3bec883383d728c9bcee5a1/solvers/choose_best_solver.cc#L87)):*
> ```cpp
>     }
>     return accumulator;
>   }()};
> ```

Not sure if I entirely understand this block, so we create an anonymous lambda function to constructor `accumulator`, and does the parentheses `()` in this line mean calling this lambda?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15327)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/choose_best_solver.cc, line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15327#-MdyVrpCDNyOuiyVZkWh:-MdyYyU69Jp-_oRltiq6:bcrhnfn) ([raw file](https://github.com/robotlocomotion/drake/blob/31349695935eb6b2e3bec883383d728c9bcee5a1/solvers/choose_best_solver.cc#L39)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why we need `constexpr` here? I understand using `static constexpr` for data member, but why we need it for a function?
</blockquote></details>

Any function called in a constexpr context (in this case, the `kKnownSolvers` variable definition below) must itself be marked `constexpr`.
___
*[solvers/choose_best_solver.cc, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15327#-MdyY9yj2B3R4mSwn-zu:-MdyZKC9BPqc7QJIO-s4:bvkj8ff) ([raw file](https://github.com/robotlocomotion/drake/blob/31349695935eb6b2e3bec883383d728c9bcee5a1/solvers/choose_best_solver.cc#L87)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not sure if I entirely understand this block, so we create an anonymous lambda function to constructor `accumulator`, and does the parentheses `()` in this line mean calling this lambda?
</blockquote></details>

Yes, exactly!  It's a C++ trick that when we need a temporary lexical scope, we can do that with a lambda that is immediately created, called, and then destroyed.

The forcing function here is never_destroyed -- I should probably add to the `never_destroyed` API reference an example and explanation of the lambda trick?

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@soonho-tri for Wednesday's platform review please, thanks!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15327#-:-MdyaZAACCUISpB8cCq8:bwqrewe)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform) (waiting on @jwnimmer-tri and @soonho-tri)

___
*[solvers/choose_best_solver.cc, line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15327#-MdyVrpCDNyOuiyVZkWh:-Mdy_dVICCrIhftfVdd3:b-lg05o9) ([raw file](https://github.com/robotlocomotion/drake/blob/31349695935eb6b2e3bec883383d728c9bcee5a1/solvers/choose_best_solver.cc#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Any function called in a constexpr context (in this case, the `kKnownSolvers` variable definition below) must itself be marked `constexpr`.
</blockquote></details>

I see, thanks for the explanation.
___
*[solvers/choose_best_solver.cc, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15327#-MdyY9yj2B3R4mSwn-zu:-Mdy_kKD699O6Sqndr3N:bhhs0se) ([raw file](https://github.com/robotlocomotion/drake/blob/31349695935eb6b2e3bec883383d728c9bcee5a1/solvers/choose_best_solver.cc#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, exactly!  It's a C++ trick that when we need a temporary lexical scope, we can do that with a lambda that is immediately created, called, and then destroyed.

The forcing function here is never_destroyed -- I should probably add to the `never_destroyed` API reference an example and explanation of the lambda trick?
</blockquote></details>

Yeah I referred to the code example in `never_destroyed.h` to understand why we cannot first declare accumulator as empty and then use a for loop to insert entries. I think pointing to the code example in `never_destroyed.h` would be very helpful for future maintainers.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15327)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @hongkai-dai and @soonho-tri)

___
*[solvers/choose_best_solver.cc, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15327#-MdyY9yj2B3R4mSwn-zu:-MdyyvnE0RzCnDF353l7:b9y4n9p) ([raw file](https://github.com/robotlocomotion/drake/blob/31349695935eb6b2e3bec883383d728c9bcee5a1/solvers/choose_best_solver.cc#L87)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yeah I referred to the code example in `never_destroyed.h` to understand why we cannot first declare accumulator as empty and then use a for loop to insert entries. I think pointing to the code example in `never_destroyed.h` would be very helpful for future maintainers.
</blockquote></details>

=> #15329

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15327#-:-Me0YfbS9xPUzRCkfWSR:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),hongkai-dai (waiting on @jwnimmer-tri)

___
*[solvers/choose_best_solver.cc, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15327#-MdyY9yj2B3R4mSwn-zu:-Me0YR6-Dz75UoiEcPTB:b-8fx2u7) ([raw file](https://github.com/robotlocomotion/drake/blob/31349695935eb6b2e3bec883383d728c9bcee5a1/solvers/choose_best_solver.cc#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

=> #15329
</blockquote></details>

:+1:

**Pull request merged**
