### PR TITLE
[geometry:meshcat] Upgrade meshcat and meshcat-python versions

### LINKED ISSUE #15681: meshcat: Trying to upgrade to latest commit, but some primitives can no longer be visualized?
Trying to upgrade to https://github.com/rdeits/meshcat/pull/97 (in order to address https://github.com/rdeits/meshcat/issues/93), but seems like something broke, at least on MeshCat C++.

Boxes and the flat face of the cylinder aren't rendering. FWIW, I see the 2 errors with the following message on Firefox console:
```
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. 
Object { uuid: "c58960d9-4cac-4036-ad2e-1aef26946dae", name: "", type: "BoxGeometry", index: {…}, attributes: {…}, morphAttributes: {}, morphTargetsRelative: false, groups: (6) […], boundingBox: null, boundingSphere: {…}, … }
main.min.js:2:219650
```

Command to test:
```
$ bazel run //geometry:meshcat_manual_test
# Open URL
```

Before, on master, bd762ab5e3
> image

After, on branch, 04a4a1ed4d:
RobotLocomotion/drake@master...EricCousineau-TRI:issue-meshcat-93
> image

FYI @RussTedrake

### PR DESCRIPTION
**Pull request by RussTedrake**
meshcat changes the scaling of the background color
meshcat updated three.js, which required some non-trivial changes to my msgpack usage.

Resolves #15681

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@ericcousineau-tri for feature review.

Resolves #15681

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684#-:-MiMNlP94i-T5ZOIiYlY:b-plm0ij)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiN8qC-DkjkLyCxGeSJ:-MiN8qC06EXr0_8jvzkL:bum9tqm) (no related file):*
Tests are now failing due to `PIL` not being found:
https://drake-cdash.csail.mit.edu/test/365951468

We will need a provisioning PR before this to ensure we have PIL.
For Ubuntu, I think it's just `sudo apt install python3-pil`; not sure what's best spelling for Homebrew.

Is there someone can that can handle this? (I am doing hardware things today)
(this also requires Betsy or someone from Kitware to handle the provisioning)

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiN9PP9Cb8_YDs0VaQa:-MiN9PPAASSzETR4Cfqx:bcslj3t) (no related file):*
Working: Will test manually on my machine, given that I have PIL installed.

---
___
*[geometry/meshcat_types.h, line 132 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiN9fUx463mHRDTQJfO:-MiN9fUx463mHRDTQJfP:bnpicbq) ([raw file](https://github.com/robotlocomotion/drake/blob/657b9c824be665f005848c8101c1b350d37f3b4a/geometry/meshcat_types.h#L132)):*
> ```objc
>   // This method must be defined, but the implementation is not needed in the
>   // current workflows.
>   void msgpack_unpack(msgpack::object const&) {}
> ```

Unclear what workflows will silently break if this codepath is used.

Can you have this fail fast if called? e.g. `throw std::runtime_error("Not implemented")`.

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks good, pending provisioning.

FTR I moved "Resolves" statement to PR overview, a that's the only place it takes effect:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684#-:-MiNBnPL9elaqHlCKmJ0:b5m0yyi)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiN8qC-DkjkLyCxGeSJ:-MiNB--J3METMWUoWbkN:b-p35jhg) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Tests are now failing due to `PIL` not being found:
https://drake-cdash.csail.mit.edu/test/365951468

We will need a provisioning PR before this to ensure we have PIL.
For Ubuntu, I think it's just `sudo apt install python3-pil`; not sure what's best spelling for Homebrew.

Is there someone can that can handle this? (I am doing hardware things today)
(this also requires Betsy or someone from Kitware to handle the provisioning)
</blockquote></details>

(to clarify, I can help, but may need to wait until tomorrow; also, provisioning CI is something I'm not familiar, and if Jeremy & Betsy are OOO, I'm not sure of it's entirely feasible.)

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiN9PP9Cb8_YDs0VaQa:-MiNB9t227sTErsZEfFV:b-iif45t) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will test manually on my machine, given that I have PIL installed.
</blockquote></details>

OK Confirmed that `//geometry:meshcat_manual_test` (C++) and `//manipulation/util:show_model` (Python) appear to work as expected (with fixed semi-transparent bug!).

---
___
*[geometry/test/meshcat_manual_test.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiNAi3W8yEbvzp7qm8P:-MiNAi3W8yEbvzp7qm8Q:btrhvts) ([raw file](https://github.com/robotlocomotion/drake/blob/657b9c824be665f005848c8101c1b350d37f3b4a/geometry/test/meshcat_manual_test.cc#L63)):*
> ```cpp
>   std::cout
>       << "- The blue box should have disappeared\n"
>       << "- The lights should have dimmed."
> ```

nit Missing newline.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684)* status: 2 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),BetsyMcPhail (waiting on @BetsyMcPhail and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiN8qC-DkjkLyCxGeSJ:-MiNhhqeDXfvY4Cnqn2c:b-xpdep0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(to clarify, I can help, but may need to wait until tomorrow; also, provisioning CI is something I'm not familiar, and if Jeremy & Betsy are OOO, I'm not sure of it's entirely feasible.)
</blockquote></details>

Agreed.  I've added the installation bits, but we'll probably need Betsy to update CI.
+@betsymcphail for CI update.
Will mark the priority high to make that clear.

---
___
*[geometry/meshcat_types.h, line 132 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiN9fUx463mHRDTQJfO:-MiNh_Rc0RLy2Kc-BuXd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/657b9c824be665f005848c8101c1b350d37f3b4a/geometry/meshcat_types.h#L132)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unclear what workflows will silently break if this codepath is used.

Can you have this fail fast if called? e.g. `throw std::runtime_error("Not implemented")`.
</blockquote></details>

Done.
___
*[geometry/test/meshcat_manual_test.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiNAi3W8yEbvzp7qm8P:-MiNhgP_CstEnfcnKeCm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/657b9c824be665f005848c8101c1b350d37f3b4a/geometry/test/meshcat_manual_test.cc#L63)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Missing newline.
</blockquote></details>

Done.

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for tuesday platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684#-:-MiOuK4D4VI0s_RRlYs5:b-ak6pcb)* status: 2 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),BetsyMcPhail,sherm1(platform) (waiting on @BetsyMcPhail, @EricCousineau-TRI, and @sherm1)

**Review by RussTedrake — COMMENTED** [review]
Note: all three unprovisioned builds passed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684#-:-MiQfJMJ8uXvqdQogW3U:b-o7xh8a)* status: 2 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform),BetsyMcPhail (waiting on @BetsyMcPhail, @EricCousineau-TRI, and @sherm1)

**Review by sherm1 — COMMENTED** [review]
CI is failing with errors like this:
```
from PIL import Image        
ModuleNotFoundError: No module named 'PIL'
```

Platform :lgtm: pending CI fix and a nit.

> Reviewed 6 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684#-:-MiSo-gH5AqemKz-UNPt:b-rg7rnk)* status: 3 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),BetsyMcPhail (waiting on @BetsyMcPhail, @EricCousineau-TRI, and @RussTedrake)

___
*[geometry/meshcat_types.h, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiSr4nh6VuNnhS3q0Ww:-MiSr4ni0XScD1trFbuw:b2gwgjs) ([raw file](https://github.com/robotlocomotion/drake/blob/cf7ee37519c4e9a7755d4412a6af06782d54166d/geometry/meshcat_types.h#L69)):*
> ```objc
>   void msgpack_pack(Packer& o) const {
>     int size = 2;  // uuid and type are always sent.
>     if (width) size++;
> ```

nit: per [GSG, prefer preincrement](https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement) here and below

**Review by RussTedrake — COMMENTED** [review]
The CI failures are expected (that's what all of the conversations about adding the dependency, the unprovisioned builds, and having Betsy upgrade CI was about.  ;-)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684#-:-MiTxJIX517iRl_hqj4Y:b-odrque)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),BetsyMcPhail (waiting on @BetsyMcPhail, @EricCousineau-TRI, and @sherm1)

___
*[geometry/meshcat_types.h, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15684#-MiSr4nh6VuNnhS3q0Ww:-MiTy-Ey3MdnOP7nPGQA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cf7ee37519c4e9a7755d4412a6af06782d54166d/geometry/meshcat_types.h#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: per [GSG, prefer preincrement](https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement) here and below
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: pending CI provisioning

Confirmed unprovisioned jobs passed for cf7ee375

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684#-:-MiWdcBrAUwTLmu9RQLB:b-fk6qz5)* status: LGTM missing from assignee BetsyMcPhail (waiting on @BetsyMcPhail)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

**Review by BetsyMcPhail — COMMENTED** [review]
Linux CI images and Jenkins have been updated. On the Mac provisioned images, Pillow was already installed so those images have not been updated. I did launch the Mac experimental jobs just to make sure we're not missing anything.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684#-:-MiWpfYY3LJ3e8RwAxbw:b2aixur)* status: LGTM missing from assignee BetsyMcPhail (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: for CI

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15684#-:-MiWqZfJ-jUFQZcHKOsd:bxbmh58)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform),BetsyMcPhail (waiting on @BetsyMcPhail)

**Pull request merged**
