### PR TITLE
Change the linear term variable in non-convex quadratic constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
Now the variables in the linear term can be different from the variables in the quadratic term. Namely we support this type of constraint
```
lb <= x'Q1x - x'Q2x + p'y <= ub
```
The advantage of allowing `y` to be different from `x`, is that we only need to linearize the constraint about `x`, instead of about the union of `x` and `y`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7400)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-:-KxzeBzPojhcXIqJRGAZ:bll7v0f)*

**Comment by avalenzu** [comment]
Review pass done. PTAL.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/non_convex_optimization_util.h, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyR8RQkYax1cykS045I:-KyR8RQlLpxjGeTgU3Q7:b-lip57c) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/non_convex_optimization_util.h#L132)):*
> ```objc
>  * @param Q2 A positive semidefinite matrix.
>  * @param p A vector, the linear coefficients in the quadratic form.
>  * @param y A vector, the variables in the linear term in the quadratic form.
> ```

"in the quadratic form" -> "of the quadratic form"

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 187 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyR9EDQmW59-xTw13W-:-KyR9EDQmW59-xTw13W0:b-oif5zy) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L187)):*
> The variables y in the linear term is not the same as the variables in the quadratic term x.

Consider replacing this with

>  Check the case in which the variable y in the linear term are not the same as the variable x in the quadratic term.

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyRASLDszXu8tYqWIle:-KyRASLDszXu8tYqWIlf:b-4dsmk6) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L301)):*
> ```cpp
>   // The variables y in the linear term is not the same as the variables x in
>   // the quadratic term.
>   Eigen::Matrix2d Q1, Q2;
> ```

"variables" -> "variable" (2x)

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 455 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyRBrm7Fsyb0qe_bb-k:-KyRBrm7Fsyb0qe_bb-l:bcf1c6s) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L455)):*
>   const double z_coeff = Q1_is_zero ? -1 : 1;
>   const double Q_coeff = Q1_is_zero ? -1 : 1;

Could these be `z_sign` and `Q_sign` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-:-KyRCoyv_5ptE0LMFj3X:b837gv3)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/non_convex_optimization_util.h, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyR8RQkYax1cykS045I:-KyRaGEPV6uypG-wXT7W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/non_convex_optimization_util.h#L132)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

"in the quadratic form" -> "of the quadratic form"
</blockquote></details>

Done.

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 187 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyR9EDQmW59-xTw13W-:-KyRarlWKueJlMoZTwMN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L187)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> The variables y in the linear term is not the same as the variables in the quadratic term x.

Consider replacing this with

>  Check the case in which the variable y in the linear term are not the same as the variable x in the quadratic term.
</blockquote></details>

Done.

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyRASLDszXu8tYqWIle:-KyRb4YV68JJcJrPJUBV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L301)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

"variables" -> "variable" (2x)
</blockquote></details>

Done.

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 455 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyRBrm7Fsyb0qe_bb-k:-KyRbRVkzcq5PbY7YlSv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L455)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

>   const double z_coeff = Q1_is_zero ? -1 : 1;
>   const double Q_coeff = Q1_is_zero ? -1 : 1;

Could these be `z_sign` and `Q_sign` instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400)*

**Comment by avalenzu** [comment]
:lgtm: pending resolution of the typos introduced at my suggestion.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 187 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyR9EDQmW59-xTw13W-:-KySRxMFW6pGDzcBGUB4:b-3zl8ag) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L187)):*
Ok, so I blew it by going back and forth between different versions of my suggestion here. Sorry!  My suggestion should have been:

> Check the case in which the variable y in the linear term is not the same as the variable x in the quadratic term.

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyRASLDszXu8tYqWIle:-KySRsl44VJr1cdvmQgG:b-eh8wei) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L301)):*
I was suggesting that you change this to 

> The variable y in the linear term is not the same as the variable x in the quadratic term.

Sorry for the confusion caused by my previous comment!

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 569 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KySSiqZLwVX4zPXxEfL:-KySSiqZLwVX4zPXxEfM:b-abhcii) ([raw file](https://github.com/robotlocomotion/drake/blob/9b5bde2b316898b2b876d30b84a26110476a47fb/drake/solvers/test/non_convex_optimization_util_test.cc#L569)):*
> ```cpp
> 
> TEST_F(TestRelaxNonConvexQuadraticConstraintInTrustRegion, ZeroQ2Test3) {
>   // Check the case in which the variable y in the linear term are not the same
> ```

"are" -> "is"

Again, my apologies for the typo and ensuing confusion!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-:-KySSpoMIdxwcMWmM5K-:brk94l)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 187 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyR9EDQmW59-xTw13W-:-KyacWrRavsUPe5CGZwH:brpa3xt) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L187)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Ok, so I blew it by going back and forth between different versions of my suggestion here. Sorry!  My suggestion should have been:

> Check the case in which the variable y in the linear term is not the same as the variable x in the quadratic term.

</blockquote></details>

Done. No problem, thanks for checking it!

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KyRASLDszXu8tYqWIle:-Kyad0y2IJtS5vH0l2i1:b-77cgb7) ([raw file](https://github.com/robotlocomotion/drake/blob/f53ff58d42c4e2f7537f9cbc51d46d44e691dc43/drake/solvers/test/non_convex_optimization_util_test.cc#L301)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

I was suggesting that you change this to 

> The variable y in the linear term is not the same as the variable x in the quadratic term.

Sorry for the confusion caused by my previous comment!
</blockquote></details>

Done. No problem, thanks for the suggestion!

---

*[drake/solvers/test/non_convex_optimization_util_test.cc, line 569 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-KySSiqZLwVX4zPXxEfL:-KyadBjaAhz3GtA5V3Aa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9b5bde2b316898b2b876d30b84a26110476a47fb/drake/solvers/test/non_convex_optimization_util_test.cc#L569)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

"are" -> "is"

Again, my apologies for the typo and ensuing confusion!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-:-Kyafo61YjHMn7WSVZPb:b6vi582)*

**Comment by sherm1** [comment]
Platform :lgtm: with one BTW, ptal.

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/non_convex_optimization_util.h, line 161 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-Kyb3JJ-S4KIajYqwtTC:-Kyb3JJ-S4KIajYqwtTD:b9ns8yw) ([raw file](https://github.com/robotlocomotion/drake/blob/c16403fb15b71a250f08130c1bb368e1a158172f/drake/solvers/non_convex_optimization_util.h#L161)):*
> ```objc
>     const Eigen::Ref<const Eigen::MatrixXd>& Q2,
>     const Eigen::Ref<const Eigen::VectorXd>& p,
>     const Eigen::Ref<const VectorXDecisionVariable>& y, double lower_bound,
> ```

BTW the argument ordering seems odd to me. Consider putting x and y together, followed by the coefficient matrices `(prog, x, y, Q1, Q2, p)` or listing the variables before their coefficients consistently `(prog, x, Q1, Q2, y, p)`. No defect -- just want to make sure you've thought this through.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-:-Kyb4wP7V26g0QY8eN-u:b-h9m7oy)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/non_convex_optimization_util.h, line 161 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7400#-Kyb3JJ-S4KIajYqwtTC:-KybV4Kw8ErA-s1JtdDt:bjxtvdt) ([raw file](https://github.com/robotlocomotion/drake/blob/c16403fb15b71a250f08130c1bb368e1a158172f/drake/solvers/non_convex_optimization_util.h#L161)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the argument ordering seems odd to me. Consider putting x and y together, followed by the coefficient matrices `(prog, x, y, Q1, Q2, p)` or listing the variables before their coefficients consistently `(prog, x, Q1, Q2, y, p)`. No defect -- just want to make sure you've thought this through.
</blockquote></details>

Done. Thanks, I will use `(prog, x, Q1, Q2, y, p)` order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400)*

**Comment by sherm1** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400)*

**Comment by avalenzu** [comment]
Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7400)*

**Pull request merged**
