### PR TITLE
[render_gltf_client] Port to ImageIo

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20729)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please?

**Review by zachfang — COMMENTED** [review]
:lgtm: feature with a question regarding error messages.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20729#-:-NnIvOLP2cg84VWpaVrk:b7utkmr)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/render_gltf_client/internal_render_client.cc` line 88 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20729#-NnIIfHf3Hao97DF-bFK:-NnIIfHf3Hao97DF-bFL:bi7cmsk) ([raw file](https://github.com/RobotLocomotion/drake/blob/65d5dbde77e20945db7a9414f086ceae023f7a09/geometry/render_gltf_client/internal_render_client.cc#L88)):*
> ```cpp
> }
> 
> /* Throws an error when the loaded image doesnt' have the correct dimensions. */
> ```

nit. Typo.



_Suggestion:_
```cpp
doesn't
```
___
*[`geometry/render_gltf_client/internal_render_client.cc` line 96 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20729#-NnIJX7ZAFKrauz2xRRO:-NnIJX7ZAFKrauz2xRRP:b-vsai1y) ([raw file](https://github.com/RobotLocomotion/drake/blob/65d5dbde77e20945db7a9414f086ceae023f7a09/geometry/render_gltf_client/internal_render_client.cc#L96)):*
> ```cpp
>   const int actual_height = image->height();
>   if (actual_width != expected_width || actual_height != expected_height) {
>     // image->resize(expected_width, expected_height);
> ```

nit. I assume this line is left by accident.



_Code quote:_
```cpp
// image->resize(expected_width, expected_height);
```
___
*[`geometry/render_gltf_client/internal_render_client.cc` line 282 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20729#-NnIvCTT5I5kXv_851k1:-NnIvCTU4ahcOzkk7qLT:bs94d8q) ([raw file](https://github.com/RobotLocomotion/drake/blob/65d5dbde77e20945db7a9414f086ceae023f7a09/geometry/render_gltf_client/internal_render_client.cc#L282)):*
> ```cpp
>   std::visit(
>       [depth_image_out]<typename SomeImage>(SomeImage& image) {
>         if constexpr (std::is_same_v<SomeImage, ImageDepth16U>) {
> ```

BTW. TIL `constexpr-if` :exploding_head: 



_Code quote:_
```cpp
if constexpr
```
___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 583 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20729#-NnIt1yKBQbVL7zqgoHw:-NnIt1yKBQbVL7zqgoHx:bjlbvpb) ([raw file](https://github.com/RobotLocomotion/drake/blob/65d5dbde77e20945db7a9414f086ceae023f7a09/geometry/render_gltf_client/test/internal_render_client_test.cc#L583)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       RenderClient::LoadDepthImage(Touch(scratch_ / "fake.tiff"), &ignored),
>       ".*fake.*Unknown file type.*");
> ```

nit. The error message in this case is a bit misleading to me as a known file type is indeed supplied. My understanding is the content dictates the loading process, so the `unknown file type` message is emitted by the VTK library.

Similarly for the color image failure case 2.



_Code quote:_
```cpp
".*fake.*Unknown file type.*"
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20729#-:-NnKAJqvDp7_-M-XCREx:b-1krawd)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 583 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20729#-NnIt1yKBQbVL7zqgoHw:-NnK8pr7DIEllGcCeQlq:bonf5ro) ([raw file](https://github.com/RobotLocomotion/drake/blob/65d5dbde77e20945db7a9414f086ceae023f7a09/geometry/render_gltf_client/test/internal_render_client_test.cc#L583)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. The error message in this case is a bit misleading to me as a known file type is indeed supplied. My understanding is the content dictates the loading process, so the `unknown file type` message is emitted by the VTK library.

Similarly for the color image failure case 2.
</blockquote></details>

In practice, I think an empty file would never make it this far.  The RPC client would bail out in this stanza first:

```c++
  throw std::runtime_error(fmt::format(
      "RenderClient: while trying to render the scene '{}' with a sha256 hash "
      "of '{}', the file returned by the server saved in '{}' is not "
      "understood as an image type that is supported, i.e., PNG or TIFF.",
      scene_path, scene_sha256, bin_out_path));
```

So, I've clarified the test code to make it clear that the file is empty.

**Review by zachfang — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20729)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
-@sammy-tri +@SeanCurtis-TRI per rotation (sorry, I didn't make it on Thursday)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20729#-:-NndOVWuBRfcmKs7A0g8:b-n0yweh)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20729#-:-NneZDelD4rdvyzb1pXH:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),zachfang

**Pull request merged**
