### PR TITLE
[workspace] Add vtk_internal build from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19945 and #16502.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20068)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: I haven't thought about TGA files in literally decades.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-:-Ncx-i3c1QXg6bpCgHWw:blff3ci)* status: 7 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/workspace/vtk_internal/repository.bzl` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Ncwco7S4Z2V3cG0C5rj:-Ncwco7S4Z2V3cG0C5rk:bmbkl88) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/repository.bzl#L47)):*
> ```Starlark
>         key, values = tokens[0], tokens[1:]
>         if key.endswith("S"):
>             # Plural key.
> ```

This test happens to work with the keys documented, but the overall effect is somewhat misleading. 

The distinction in number is nothing to do with the incidental grammar status of the keys; its rather whether the key takes one or multiple values.

Perhaps instead:
```
multivalued_keys = ["DEPENDS", "PRIVATE_DEPENDS"]  # maybe others later?
if key in multivalued_keys:
    # Multi-valued key.
   # ... blah
else:
    # Single-valued key.
```

Or, if you are confident that no `=` characters will ever be embedded in values, just branch on the length of the token list?
___
*[`tools/workspace/vtk_internal/repository.bzl` line 65 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Ncw_3P-5PEClo_wyJI_:-Ncw_3P-5PEClo_wyJIa:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/repository.bzl#L65)):*
> ```Starlark
>     an loadable `modules.bzl` file in the root of the repository.
> 
>     This is necessary because BUILD files can't parse external metdata as part
> ```

typo



_Suggestion:_
```Starlark
metadata
```
___
*[`tools/workspace/vtk_internal/rules.bzl` line 59 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Ncw_VauD5EKMOGGOQrX:-Ncw_VauD5EKMOGGOQrY:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/rules.bzl#L59)):*
> ```Starlark
>             module_deps_private.remove(dep_name)
> 
>     # Generate the module header, ala CMake GenerateExportHeader.
> ```

typo



_Suggestion:_
```Starlark
a la
```
___
*[`tools/workspace/vtk_internal/rules.bzl` line 75 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Ncwio7bBDvFMnW_etRN:-Ncwio7bBDvFMnW_etRO:b570hnj) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/rules.bzl#L75)):*
> ```Starlark
>             ]).format(scream = scream),
>         )
>         hdrs_extra = hdrs_extra + [module_h]
> ```

nit does not `hdrs_extra.append(module_h)` work in Starlark?

At least one other instance below.
___
*[`tools/workspace/vtk_internal/rules.bzl` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Ncwjacq-S7UC--ByR1k:-Ncwjacq-S7UC--ByR1l:biw64yp) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/rules.bzl#L92)):*
> ```Starlark
>     ] + hdrs_glob_exclude)
>     gen_hdrs = [
>         "gen/" + x[:-3]
> ```

This slice is a masterpiece of obfuscation. What exactly is the goal here?
___
*[`tools/workspace/vtk_internal/rules.bzl` line 186 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Ncw_jXgC2QXoXMaEHM2:-Ncw_jXgC2QXoXMaEHM3:bwfi61v) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/rules.bzl#L186)):*
> ```Starlark
>             build this module, typically loaded from a `settings.bzl` file.
> 
>     Keys of module_metaata:
> ```

typo  (or https://www.youtube.com/watch?v=nbY_aP-alkw ?)



_Suggestion:_
```Starlark
metadata
```
___
*[`tools/workspace/vtk_internal/rules.bzl` line 309 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-NcwaNMq-wOQV2Tl_vMm:-NcwaNMq-wOQV2Tl_vMn:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/rules.bzl#L309)):*
> ```Starlark
> 
> def generate_abi_namespace():
>     """Generates vtkABINamespace.h, mimicing the Common/Core/CMakeLists.txt.
> ```

typo



_Suggestion:_
```Starlark
mimicking
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20068)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/workspace/vtk_internal/repository.bzl` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Ncwco7S4Z2V3cG0C5rj:-NcxqqBz0ge9jcdujX4u:b-cs3ekb) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/repository.bzl#L47)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This test happens to work with the keys documented, but the overall effect is somewhat misleading. 

The distinction in number is nothing to do with the incidental grammar status of the keys; its rather whether the key takes one or multiple values.

Perhaps instead:
```
multivalued_keys = ["DEPENDS", "PRIVATE_DEPENDS"]  # maybe others later?
if key in multivalued_keys:
    # Multi-valued key.
   # ... blah
else:
    # Single-valued key.
```

Or, if you are confident that no `=` characters will ever be embedded in values, just branch on the length of the token list?
</blockquote></details>

Possibly clearer now?
___
*[`tools/workspace/vtk_internal/rules.bzl` line 75 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Ncwio7bBDvFMnW_etRN:-Ncxp6PB3Rwor5fPlvtV:b806eoj) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/rules.bzl#L75)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit does not `hdrs_extra.append(module_h)` work in Starlark?

At least one other instance below.
</blockquote></details>

Nope.  Function arguments are immutable (readonly).  If I wanted to append, I'd need to copy it first.
___
*[`tools/workspace/vtk_internal/rules.bzl` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Ncwjacq-S7UC--ByR1k:-NcxqXGgBXtCKNFatSC5:b-cs3ekb) ([raw file](https://github.com/RobotLocomotion/drake/blob/baf4508cdbeb8d10969d41cd086a1b253d26b33b/tools/workspace/vtk_internal/rules.bzl#L92)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This slice is a masterpiece of obfuscation. What exactly is the goal here?
</blockquote></details>

Possibly clearer now?

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review, please.  Rico will be on-call tomorrow, and you're a good candidate for "a developer who might need to understand this stuff enough to make a small adjustment" so my goal is for you to be able to find your way around here.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20068)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a couple of typos.

> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-:-Nd0xVLrAkGkTP1DAivV:bqx6fle)* status: 4 unresolved discussions

___
*[`tools/workspace/vtk_internal/repository.bzl` line 66 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Nd0ox_X9Vav-eq8iWYd:-Nd0ox_X9Vav-eq8iWYe:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/5a5968b3099eba6ad7788dcb00ec17742efac407/tools/workspace/vtk_internal/repository.bzl#L66)):*
> ```Starlark
>             result[key] = 1
>         else:
>             fail("{}: Too may values for {}".format(subdir, key))
> ```

nit: typo



_Suggestion:_
```Starlark
many
```
___
*[`tools/workspace/vtk_internal/repository.bzl` line 66 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Nd0p4RWCbCe6ZnbBugo:-Nd0p4RWCbCe6ZnbBugp:byxp2o4) ([raw file](https://github.com/RobotLocomotion/drake/blob/5a5968b3099eba6ad7788dcb00ec17742efac407/tools/workspace/vtk_internal/repository.bzl#L66)):*
> ```Starlark
>             result[key] = 1
>         else:
>             fail("{}: Too may values for {}".format(subdir, key))
> ```

BTW It seems that this error message is a regression against the trailing "S" heuristic. The defect may not be that there are too many values, but that there are multiple values, but we weren't told to interpret it as a list. Is it worth rephrasing the error message accordingly?
___
*[`tools/workspace/vtk_internal/repository.bzl` line 71 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Nd0pOpgCgx5cpmZJU_r:-Nd0pOpgCgx5cpmZJU_s:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/5a5968b3099eba6ad7788dcb00ec17742efac407/tools/workspace/vtk_internal/repository.bzl#L71)):*
> ```Starlark
> def create_modules_bzl(repo_ctx):
>     """Finds all vtk.module files, parses them, and writes their content into
>     an loadable `modules.bzl` file in the root of the repository.
> ```

nit: typo



_Suggestion:_
```Starlark
a 
```
___
*[`tools/workspace/vtk_internal/patches/io_image_formats.patch` line 28 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20068#-Nd0xE7N8ApyT3AaoqpC:-Nd0xE7N8ApyT3AaoqpD:b-qosi9a) ([raw file](https://github.com/RobotLocomotion/drake/blob/5a5968b3099eba6ad7788dcb00ec17742efac407/tools/workspace/vtk_internal/patches/io_image_formats.patch#L28)):*
> ```Diff
>    reader->Delete();
> -  vtkImageReader2Factory::AvailableReaders->AddItem((reader = vtkHDRReader::New()));
> +  // vtkImageReader2Factory::AvailableReaders->AddItem((reader = vtkHDRReader::New()));
> ```

BTW This will be coming back soon, because we'll want to set the envirornment map in `RenderEngineVtk` via .hdr files.  You don't need to take any action now, I'm just flagging it to help log this into my own memory.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20068)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
