### PR TITLE
Snopt shadow repair

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Fix a bunch of snopt-mex variable shadowing problems, and apply clang-format afterward.

Another chunk of #2852.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2925)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
This is DNR/DNM until the magic mac-clang-matlab build passes, which I will have to launch by hand.

**Comment by rpoyner-tri** [comment]
The current build-that-matters is: https://drake-jenkins.csail.mit.edu/job/mac-clang-experimental-matlab/50/

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by rpoyner-tri** [comment]
Current build-that-matters is: https://drake-jenkins.csail.mit.edu/job/mac-clang-experimental-matlab/51/

**Comment by rpoyner-tri** [comment]
Current build-that-matters is: https://drake-jenkins.csail.mit.edu/job/mac-clang-experimental-matlab/52/
Apparently, 51 beat the merge of #2928.

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by rpoyner-tri** [comment]
+@jwnimmer-tri for feature review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2925#-:-KNZ_EnynmlgZTuQlfGW:-1597605820)*

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
:lgtm:

It's a bit of an eyebleed to review this detail online -- with such long methods and other cppguide violations, it's difficult to prove that we got this one right (local reasoning is defeated).  I am also unclear on how much, if any, automated testing these files are covered by.

I wonder if it's even perhaps best to just leave these files alone and keep a mex-specific warning suppression intact?  Or alternatively, to assign it to RLG for review (and manual testing) before merge?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/NonlinearProgramSnoptmex.cpp, line 165 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2925#-KNaueOcbF1wYgK-GL42:-KNaueOcbF1wYgK-GL43:789499411) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d9d23d2b10e3727da8f43cd2e5d529f137bc86/drake/solvers/NonlinearProgramSnoptmex.cpp#L165)):*
> ```cpp
>     // mysnseti("Major print level",
>     //   static_cast<snopt::integer>(11),&iPrint,&iSumm,&INFO_snopt,
>     //   cw,&lencw, iw,&leniw, rw,&lenrw);
> ```

Missing `g_` prefixes here in commented-out code (or remove it).

---

*[drake/solvers/NonlinearProgramSnoptmex.cpp, line 167 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2925#-KNauiCyFIWrKuNDnYRH:-KNauiCyFIWrKuNDnYRI:441109719) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d9d23d2b10e3727da8f43cd2e5d529f137bc86/drake/solvers/NonlinearProgramSnoptmex.cpp#L167)):*
> ```cpp
>     //   cw,&lencw, iw,&leniw, rw,&lenrw);
>     // mysnseti("Print file", iPrint,&iPrint,&iSumm,&INFO_snopt,
>     //   cw,&lencw, iw,&leniw, rw,&lenrw);
> ```

Missing `g_` prefixes here in commented-out code (or remove it).

---

*[drake/systems/trajectories/replanFunnels_mex.cpp, line 67 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2925#-KNZa0rXvZVrSSPXWa2-:-KNZa0rYyh9ecZN5XY6v:-1060369439) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d9d23d2b10e3727da8f43cd2e5d529f137bc86/drake/systems/trajectories/replanFunnels_mex.cpp#L67)):*
> ```cpp
> static const mxArray* g_funnelLibrary;  // Funnel library (pointer)
> static int g_funnelIdx;
> static const mxArray* x_current;
> ```

BTW Here, and in a few non-const globals below, and for the same in the other files, I'm a little bit worried about only marking some of the globals with `g_` and leaving others spelled like plain local variables.  Perhaps consider renaming everything to use a `g_` for consistency / readability.

---

*[drake/systems/trajectories/replanFunnels_mex.cpp, line 74 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2925#-KNave_5rXoUicxNwYEQ:-KNave_5rXoUicxNwYER:1072709088) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d9d23d2b10e3727da8f43cd2e5d529f137bc86/drake/systems/trajectories/replanFunnels_mex.cpp#L74)):*
> ```cpp
> static unique_ptr<snopt::doublereal[]> rw;
> static unique_ptr<snopt::integer[]> iw;
> static unique_ptr<char[]> cw;
> ```

BTW If nothing else, at least consider renaming these three arrays to have `g_` to match their corresponding `len` fields.

---

*[drake/systems/trajectories/shiftFunnel_snopt_mex.cpp, line 75 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2925#-KNaw9lj2JsXxxR5g83P:-KNaw9lk_F3w9DJ6wi3Q:-512858033) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d9d23d2b10e3727da8f43cd2e5d529f137bc86/drake/systems/trajectories/shiftFunnel_snopt_mex.cpp#L75)):*
> ```cpp
> static unique_ptr<snopt::doublereal[]> rw;
> static unique_ptr<snopt::integer[]> iw;
> static unique_ptr<char[]> cw;
> ```

BTW Consider renaming these three at least (`g_`...)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2925#-:-KNawK4qPfbnY1PZwmeK:-1616419982)*

**Comment by rpoyner-tri** [comment]
You have made me reconsider this. I can't be on the hook for testing this code, and the present patch is only skin deep; there are so many other problems here to address. I will withdraw this patch and look at whitelisting mex from shadow checks in the cmake.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2925#-:-KNbaQ-PWvJrFyqno0Y6:-1539895317)*

**Comment by rpoyner-tri** [comment]
Punting; this code can only become an ever-growing distraction.

**Pull request closed without merging**
