### PR TITLE
Add --config=fastmemcheck

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Possibly this should be the default, but for now it's at least an alternative.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4550)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri and +@rpoyner-tri for review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4550#-:-KZOySQ2wzQgulQkYK1A:bbwju7f)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4550#-:-KZS2aB6otxyI1EJnYJy:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4550)*

**Comment by jwnimmer-tri** [comment]
Re-ping @rpoyner-tri -- this one is small.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/bazel.rc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4550#-KZXwADc5LhvlgZq33h6:-KZXwADdsNEJmQdPKYl1:bxesaci) ([raw file](https://github.com/robotlocomotion/drake/blob/7bd02b7d5a7d7640f4be3d4b7d0de6d444b3d9ca/tools/bazel.rc#L56)):*
> ```
> # Fast memcheck.
> #
> # This build runs tests under valgind, but (unlike `--config memcheck`) does
> ```

typo valgind

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4550)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/bazel.rc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4550#-KZXwADc5LhvlgZq33h6:-KZXxm71MNhxRKDCCI76:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7bd02b7d5a7d7640f4be3d4b7d0de6d444b3d9ca/tools/bazel.rc#L56)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo valgind
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4550)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4550#-:-KZXz53lq_suZnufNcRc:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Bazel builds are done.  Using override-merge for tiny Bazel-only change.

**Pull request merged**
