### PR TITLE
[tools] Enable -Werror=missing-declarations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
While helping buildcop, I saw some console warnings scrolling by.  On Ubuntu, we aim to not have any console warnings in CI, so when we see them we either need to promote them to errors so that they get noticed (when the warnings are helpful) or suppress them entirely (when the warnings are noise).

For GCC, the general idea of `Wmissing-declarations` is to find linker-global functions (i.e, public code) whose definition did not have a preceding declaration.  This can either mean that:
- (1) The developer forgot to `#include` the header file.
- (2) The code should have been linker-private (anonymous namespace) instead of linker-global (internal namespace).
- (3) Rare corner case: purposefully calling a function without using its header file.

For Clang, the general idea is much narrower; e.g., it finds uses of `DRAKE_DEPRECATED()` that have a semicolon immediately afterward (which means that the macro call is a no-op).

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21775)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

**Review by sherm1 — COMMENTED** [review]
That caught a surprising amount of unused detritus!
Feature :lgtm: pending successful CI, one comment below

> Reviewed 70 of 70 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21775#-:-O3Zl0wt9j8Il1CS3ipK:b-hkn8m)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`common/drake_assert_and_throw.cc` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21775#-O3ZivOE1SU3ZSlw_Mg2:-O3ZivOE1SU3ZSlw_Mg3:br0ub32) ([raw file](https://github.com/RobotLocomotion/drake/blob/68eaea2a6282a7df2c5da157bd0e869e8b55d1f1/common/drake_assert_and_throw.cc#L84)):*
> ```cpp
> // This method is intended ONLY for use by pydrake bindings, and thus is not
> // declared here vs in any header file, to discourage anyone from using it.
> extern "C" void drake_set_assertion_failure_to_throw_exception();
> ```

minor: I don't understand this comment now. Did you mean "declared here rather than in a header file"?
___
*[`common/symbolic/expression/formula_cell.h` line 458 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21775#-O3ZjeU-Cy7WKcHSuexQ:-O3ZjeU-Cy7WKcHSuexR:b2nhbfk) ([raw file](https://github.com/RobotLocomotion/drake/blob/68eaea2a6282a7df2c5da157bd0e869e8b55d1f1/common/symbolic/expression/formula_cell.h#L458)):*
> ```objc
> /** Checks if @p f is a disjunction (∨). */
> bool is_disjunction(const FormulaCell& f);
> /** Checks if @p f is nary. */
> ```

BTW



_Suggestion:_
```objc
n-ary
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21775#-:-O3ZoqkOA_kkUAR86QD9:b4mx0my)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform)

___
*[`common/drake_assert_and_throw.cc` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21775#-O3ZivOE1SU3ZSlw_Mg2:-O3ZoZQZAh1vMUws67Dp:brvawwg) ([raw file](https://github.com/RobotLocomotion/drake/blob/68eaea2a6282a7df2c5da157bd0e869e8b55d1f1/common/drake_assert_and_throw.cc#L84)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I don't understand this comment now. Did you mean "declared here rather than in a header file"?
</blockquote></details>

Oops.  The "not" was in the wrong place.  Better now?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21775)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 68 of 70 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21775#-:-O3cNvqz0TEdA4uUumIy:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform)

**Pull request merged**
