### PR TITLE
Fix broken dependency

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Don't include the LCMSystem header in the Acrobat example; it isn't actually used anywhere, and it creates a broken dependency as the header requires the LCM type headers, but because the example doesn't actually use LCMSystem, there is no expressed dependency to ensure that these have been generated before the example is built.

This should fix the CI failures. This didn't break previously due to a (superfluous) dependence of drakeRBSystem (to which the example *does* link) on drakeLCMSystem (which depended on the LCM type headers, thus ensuring that they exist before the library or its dependees are built). AFAICT it's pure dumb luck that it only fails on MSVC.

See also comments near the end of #2582.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2701)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Experimental build: https://drake-jenkins.csail.mit.edu/view/Windows/job/windows-msvc-64-experimental/60/

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Acrobot/Acrobot.h, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2701#-KLSc-w3--yztJ8S0LhW:-KLSc-w3--yztJ8S0LhX:1262113042) ([raw file](https://github.com/robotlocomotion/drake/blob/076663348066c2bacda07d9807218a4db6a96abf/drake/examples/Acrobot/Acrobot.h#L12)):*
> ```objc
> class AcrobotState {  // models the Drake::Vector concept
>  public:
>   static std::string channel() { return "AcrobotState"; }
> ```

BTW The channel() should also be removed at some point also.

---

*[drake/examples/Acrobot/Acrobot.h, line 59 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2701#-KLSc8tey_S2TJRAmqS4:-KLSc8tey_S2TJRAmqS5:1262113042) ([raw file](https://github.com/robotlocomotion/drake/blob/076663348066c2bacda07d9807218a4db6a96abf/drake/examples/Acrobot/Acrobot.h#L59)):*
> ```objc
> class AcrobotInput {
>  public:
>   static std::string channel() { return "AcrobotInput"; }
> ```

BTW The channel() should also be removed at some point also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2701#-:-KLScBEOXG8HdpvzvVnZ:1417088721)*

**Comment by mwoehlke-kitware** [comment]
Experimental build passed!

FWIW, I can also reproduce this from a clean build on Linux/ninja by building only the `acrobotURDFDynamicsTest` target (thus confirming it's broken everywhere and only not showing up through dumb luck).

Now, if only IWYU caught this sort of thing...

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2701)*

**Comment by mwoehlke-kitware** [comment]
I'm not going to re-run the experimental build; the follow-on change isn't going to cause that level of esoteric breakage... if I botched it, it should break everywhere.

**Comment by jwnimmer-tri** [comment]
Agreed.  One of the jenkins builds of the new push has passed, so I'm going to assume they all will.  Using override-merge to get this fixed ASAP.

**Comment by mwoehlke-kitware** [comment]
jenkins: retest this please

**Comment by mwoehlke-kitware** [comment]
hehe... NM, jenkins refreshed before github :smile:

...thanks, @jwnimmer-tri!

**Pull request merged**
