### PR TITLE
[pydrake] Break out core geometry elements

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This required a double-merge game - it was the only way to avoid built-in merge conflicts.

When this gets into master, it'll introduce, yet another merge. The image below represents my simulation of what merging this PR would look like. Sorry for all of the local intermediate branch names.

image

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15871)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
@jwnimmer-tri I'd appreciate it if you could take a look at this and let me know if you want this kind of spaghetti bowl five times in master.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15871#-:-MlBLQxD88i_B8eU2MJi:b-h7f6uw)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jwnimmer-tri** [comment]
A different option might be to make just one PR to master to fix the history, and then the next five would be unremarkable.  That is, a PR that changes the history of `geometry_py.cc` but leaves the code net-unchanged.  In other words, in effect replay the how #15860 should have been, for just that one file -- restore it from a prior revision with history, then rm the optimization hunks.

**Comment by SeanCurtis-TRI** [comment]
Changing geometry_py.cc was my first attempt. I struck out. That was my *big* hope. The trick we use to moving the history doesn't seem to work because we don't have the ability to *overwrite* with heterogeneous history. (I can only overwrite in the most boring way we've already observed.)  Do you have any ideas for how this might be achieved?

**Comment by jwnimmer-tri** [comment]
If nothing else, maybe the resurrected file could be named `geometry_py_all.cc` or something, even on master?  It would no longer match the `.so` name, but maybe that's fine, or maybe we rename it back later it at the very end.

**Comment by SeanCurtis-TRI** [comment]
I like the idea of `geometry_py_all.cc`. The extra (ugly) PR means the subsequent PRs can go back to the "normal" pattern. I'll spin one up this morning.

**Comment by SeanCurtis-TRI** [comment]
Closing this in lieu of #15879 (which should re-enable this and its sibling PRs in a much more compact form).

**Pull request closed without merging**
