### PR TITLE
pydrake: Add internal instructions for installing via Bazel.

### LINKED ISSUE #7519: Update docs to show how to use Python bindings from a Bazel install
I tried to set the `PYTHONPATH` variable to the folder in drake, as suggested in http://drake.mit.edu/python_bindings.html. I can then do `import pydrake` using python3, but not python2.

Here is the screenshot
screenshot from 2017-11-26 20-22-00

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Closes #7519 (following from [this comment](https://github.com/RobotLocomotion/drake/issues/7519#issuecomment-349646032))

This is the internal version of #7598.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7891)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
+@jwnimmer-tri for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7891#-:-L3yZ7lcrrzhjRnK6myN:b-o8u9xy)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/pydrake_pybind.h, line 138 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7891#-L41Mh5IRyu8XX2-TUhg:-L41Mh5IRyu8XX2-TUhh:bklxd81) ([raw file](https://github.com/robotlocomotion/drake/blob/edc2f172431a6d05651b6f4e457436e3cd74fd30/bindings/pydrake/pydrake_pybind.h#L138)):*
> ```objc
>     bazel run //:install -- ~+/build_install
> 
> N.B. Ensure that you use the correcet `--config` flags; if you do not want your
> ```

`correct`

---

*[bindings/pydrake/pydrake_pybind.h, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7891#-L41MkpDuJJGt09bfIz1:-L41MkpDuJJGt09bfIz2:b-g6vaze) ([raw file](https://github.com/robotlocomotion/drake/blob/edc2f172431a6d05651b6f4e457436e3cd74fd30/bindings/pydrake/pydrake_pybind.h#L139)):*
> ```objc
> 
> N.B. Ensure that you use the correcet `--config` flags; if you do not want your
> `~/.bazelrc` flags leaking in, considuer using `bazel --bazelrc=/dev/null`.
> ```

`consider`

If you are going to have to `/dev/null` your `bazelrc` anyway you almost may as well use the CMake wrapper, but I guess this is fine internally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7891)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/pydrake_pybind.h, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7891#-L3zlqJH2OvBebzjSzkT:-L3zlqJH2OvBebzjSzkU:b-jqkjl4) ([raw file](https://github.com/robotlocomotion/drake/blob/edc2f172431a6d05651b6f4e457436e3cd74fd30/bindings/pydrake/pydrake_pybind.h#L125)):*
> ```objc
> If using CLion, consider using `gdbserver`.
> 
> # Installing Python Bindings from Bazel
> ```

This comment block gets published in Doxygen as http://drake.mit.edu/doxygen_cxx/python_bindings.html, i.e., for Drake users.

I agree with Jamie in #7519 that we should not instruct users for`run //:install`, because we don't want to support its direct use.  It seems to me like #7598 was good enough to close #7519.

If we want to add a private note for Drake developers about a workflow that doesn't involve CMake, then it could live somewhere else in the source tree.  However, I'm also skeptical that `run :install` is the best way for developers to manually explore the python bindings?  Surely that's not the best way.

I guess I would platform LGTM this new text if placed someone users won't find it, but I do wonder who the audience is.  I don't know of anyone who wants to work this way and doesn't already know how to find the answer without this text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7891)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/pydrake_pybind.h, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7891#-L3zlqJH2OvBebzjSzkT:-L41SzGtsJGWCVss1YrJ:bbpmi5y) ([raw file](https://github.com/robotlocomotion/drake/blob/edc2f172431a6d05651b6f4e457436e3cd74fd30/bindings/pydrake/pydrake_pybind.h#L125)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This comment block gets published in Doxygen as http://drake.mit.edu/doxygen_cxx/python_bindings.html, i.e., for Drake users.

I agree with Jamie in #7519 that we should not instruct users for`run //:install`, because we don't want to support its direct use.  It seems to me like #7598 was good enough to close #7519.

If we want to add a private note for Drake developers about a workflow that doesn't involve CMake, then it could live somewhere else in the source tree.  However, I'm also skeptical that `run :install` is the best way for developers to manually explore the python bindings?  Surely that's not the best way.

I guess I would platform LGTM this new text if placed someone users won't find it, but I do wonder who the audience is.  I don't know of anyone who wants to work this way and doesn't already know how to find the answer without this text.
</blockquote></details>

Yes, much of me wants to rename the `install` target something that screams do not call directly ever. By internal, I was assuming you had a wiki of sorts within TRI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7891)*

**Comment by EricCousineau-TRI** [comment]
The goal of this PR was to address #7519, but yeah, if we do not want to expose `bazel run //:install` to users, then I'll close this out and close out those other issues.

> However, I'm also skeptical that run :install is the best way for developers to manually explore the python bindings? Surely that's not the best way.

I think this would be useful if a developer wants to debug something failing in an `*_install_test`, but we could possible document this closer to those tests.

**Comment by jwnimmer-tri** [comment]
> I think this would be useful if a developer wants to debug something failing in an *_install_test, but we could possible document this closer to those tests.

Agreed.  FYI Since they are also going to collapse into a single test (with inversion-of-control injections from the InstallTest provider) in #7774, I suspect a simple config switch there would let the user get an interactive shell in the TEST_TMPDIR.

**Pull request closed without merging**
