### PR TITLE
Fbstab Dense data and variables classes

### PR DESCRIPTION
**Pull request by dliaomcp**
First files for an implementation of the FBstab quadratic programming solver (https://arxiv.org/pdf/1901.04046.pdf)

This commit contains classes for storing and manipulating problem data and primal-dual variables.

+@frankpermenter for feature review, please
+@soonho-tri for platform review, please

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11775)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot test this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-debug please

**Comment by dliaomcp** [comment]
___
*[solvers/fbstab/BUILD.bazel, line 17 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11775#-LjGxiJT18QxipGS2nWk:-LjH1vNZAFIV7HeWhbSJ:bmac8wm) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5999ffa183e41825fb293ae86d33f6dd1abb8a/solvers/fbstab/BUILD.bazel#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am skeptical that (even when complete) the new solver merits having a third level of directory nesting.  Could you post whatever prototype or final integration branch you have, so that I can understand the entirely landscape of this new solver, and help fit it into a directory and build structure?
</blockquote></details>

https://github.com/dliaomcp/drake/tree/fbstab_dev

The solver itself is templated on 5 classes, the Residual, Variable, LinearSolver, Feasibility, and Data classes. These are specific to a type of QP, e.g., this current commit deals with Dense QPs, i.e., those without any particular structure. After the dense QP PRs are in I'll starting working on the MPC objects which are designed to specifically handle optimal control problems. The objects are grouped by type, i.e., mpc_components, dense_components etc.

**Comment by dliaomcp** [comment]
___
*[solvers/fbstab/BUILD.bazel, line 11 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11775#-Lit4HzX2QX_KpEBY-EX:-LjSLiri-n5e8Qq25k54:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5999ffa183e41825fb293ae86d33f6dd1abb8a/solvers/fbstab/BUILD.bazel#L11)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META, I think we do not need comments (`# ...`) in this file.
</blockquote></details>

Done.

**Comment by dliaomcp** [comment]
___
*[solvers/fbstab/dense_components/dense_data.h, line 12 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11775#-LjMn_qz0ldkIqCk2my7:-LjSM2JM1LLlsB18hd7y:b-9nmeqb) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5999ffa183e41825fb293ae86d33f6dd1abb8a/solvers/fbstab/dense_components/dense_data.h#L12)):*
<details><summary><i>Previously, frankpermenter wrote…</i></summary><blockquote>

 I would also give the dual QP if this is intended to be a public header.  (In some cases, the dual problem will be the one of interest.)
</blockquote></details>

Its not meant to be part of the public API.

**Comment by dliaomcp** [comment]
___
*[solvers/fbstab/BUILD.bazel, line 17 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11775#-LjGxiJT18QxipGS2nWk:-LjSgdEv04aI1lOLaxFe:b-liofsb) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5999ffa183e41825fb293ae86d33f6dd1abb8a/solvers/fbstab/BUILD.bazel#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Given that the files within the subdirectory already  include the word "dense" in their basename, and I'm not sure that`fstab/dense_components/dense_linear_solver.h` vs just plain `fstab/dense_linear_solver.h` is a meaningful win for readability or maintainability.  And with the subfolders not even having their own tests or BUILD files, they are even more at odds with habits within Drake.

Are you open to removing the "dense_components" directory, and just keeping all of its files directly within fstab?
</blockquote></details>

Sure, if thats more in line with Drake conventions I'm OK with it. Its not ideal since I wanted a good way to mark or otherwise organize files to make it clear which are the main C++ API files for the solver. Even with only 2 types of QPs supported there are 20 component files... I can just add comments in the readme though.

An alternative proposal:
It would make sense to have a fbstab/components/ directory where I would dump the source code for all the component files. They all have their own tests so I could create a fbstab/components/BUILD.bazel  and fbstab/components/test/ .

fbstab/BUILD.bazel and fbstab/test would then be dedicated to integration testing of the entire solver.

**Pull request merged**
