### PR TITLE
Adds random source systems

### PR DESCRIPTION
**Pull request by RussTedrake**
for simulating with Gaussian or Uniform (band-limited) white noise

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4358)

### CODE REVIEW

**Comment by RussTedrake** [comment]
fwiw -- i'm going to use this PR to hammer on getting a random number generator that gives consistent values across all of the build servers.  expect a few pushes while I work that out.

**Comment by liangfok** [comment]
I left a few minor comments.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/primitives/random_source.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB7i3R0Gkbx_IcYLSp:-KYB7i3R0Gkbx_IcYLSq:bp0115w) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L24)):*
> ```objc
> /// Note: The hard-coding of (default) distribution parameters is imposed
> /// intentionally to simplify analysis (by forcing systems taking noise inputs
> /// to
> ```

BTW: Odd line break.

---

*[drake/systems/framework/primitives/random_source.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB7rcnTePBIsm8i147:-KYB7rcnTePBIsm8i148:b7f5l10) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L46)):*
> ```objc
>   RandomSource& operator=(const RandomSource<Distribution>&) = delete;
> 
>   /// Initialize the random number generator.
> ```

Per style guide, "Initialize" should be "Initializes".

---

*[drake/systems/framework/primitives/random_source.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB7yq3sTFmb81HlIKh:-KYB7yq3sTFmb81HlIKi:b8wo6ie) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L49)):*
> ```objc
>   void set_random_seed(double seed) { generator_.seed(seed); }
> 
>   /// Compute a random number and store it in the discrete state.
> ```

Per style guide, "Compute" should be "Computes", and "store" should be "stores".

---

*[drake/systems/framework/primitives/random_source.h, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB84iCDgebmkWGd4WN:-KYB84iCDgebmkWGd4WO:brs48xf) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L53)):*
> ```objc
>       const drake::systems::Context<double>& context,
>       drake::systems::DifferenceState<double>* updates) const override {
>     int N = updates->get_difference_state(0)->size();
> ```

For clarity, replace `int` with `const int`.

---

*[drake/systems/framework/primitives/random_source.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB8YB2_tsp5G4BbBPP:-KYB8YB2_tsp5G4BbBPQ:be97dmz) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L76)):*
> ```objc
> };
> 
> namespace internal {
> ```

BTW, it seems odd to have an "internal" namespace that's part of the public API. Is there a better name for this namespace?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-:-KYB8va0xvNaG6KSvvid:b786sh7)*

**Comment by liangfok** [comment]
Oops. Sorry, I just now notice the "do not review" label.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-:-KYB929MRVsWozLuF5YY:biaqs5z)*

**Comment by RussTedrake** [comment]
no worries.  it was ready.  +@liangfok for feature review, +@sherm1 for platform

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-:-KYBRQ-hvPwmCvmhbl74:b-m4qpfk)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYGHasl5RnD9-DPnYhl:-KYGHasl760adDIO8XEr:b-b1izdr) (no related file):*
BTW, consider adding a `random_source.cc` that simply includes a `random_source.h` to verify that it passes the transitive include-what-you-use test. For an example, see `drake-distro/drake/systems/framework/basic_vector.cc`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358)*

**Comment by sherm1** [comment]
Platform review: a few BTW comments, PTAL. :lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/framework/primitives/random_source.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYHSNwyAAkDpeNBihNV:-KYHSNwyDsqL0Jy8wZbY:bxxvrvn) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L35)):*
> ```objc
>   /// @param num_outputs The dimension of the (single) vector output port.
>   /// @param sampling_interval_sec The sampling interval in seconds.
>   explicit RandomSource(int num_outputs, double sampling_interval_sec) {
> ```

BTW, "explicit" superfluous here since there are two arguments.

---

*[drake/systems/framework/primitives/random_source.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB8YB2_tsp5G4BbBPP:-KYHTUm76eMxTPdc-J35:b-r9yitg) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L76)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, it seems odd to have an "internal" namespace that's part of the public API. Is there a better name for this namespace?
</blockquote></details>

BTW, I've seen `details` used as this kind of namespace but I think `internal` is OK too. I like the concept of getting this noise out of the API user's namespace.

---

*[drake/systems/framework/primitives/test/random_source_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYHVDFR2k63FEdCN3pp:-KYHVDFR8brtaU6CvvJA:b-4v4hbk) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/test/random_source_test.cc#L38)):*
> ```cpp
> 
>   for (double threshold = -2.0; threshold < 2.0; threshold += 0.5) {
>     double count = (x.array() < threshold).cast<double>().matrix().sum();
> ```

BTW, nice!

---

*[drake/systems/framework/primitives/test/random_source_test.cc, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYHW7JE4Mg7tucyNxCD:-KYHW7JE86_vu3WhJrbv:bl11hyk) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/test/random_source_test.cc#L71)):*
> ```cpp
>     double count = (x.array() < threshold).cast<double>().matrix().sum();
>     // Probability of x < threshold for this uniform distribution is
>     // (threshold-1)/2.
> ```

BTW, "threshold+1" not minus.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-:-KYHWG3oDI2kKoUpoHsK:brpcngd)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYGHasl5RnD9-DPnYhl:-KYHWX9G-8zRP86rmJxj:bx6h1hx) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding a `random_source.cc` that simply includes a `random_source.h` to verify that it passes the transitive include-what-you-use test. For an example, see `drake-distro/drake/systems/framework/basic_vector.cc`.
</blockquote></details>

:+1: That is also a good place for explicit instantiations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358)*

**Comment by amcastro-tri** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/primitives/test/random_source_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYHVDFR2k63FEdCN3pp:-KYJxF1FCgbFmnB-Zw_k:bwabqgp) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/test/random_source_test.cc#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, nice!
</blockquote></details>

BTW, I second that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358)*

**Comment by RussTedrake** [comment]
Review status: 3 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYGHasl5RnD9-DPnYhl:-KYK-XMvD8BSN_E-4gp2:b-896fix) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

:+1: That is also a good place for explicit instantiations.
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/random_source.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB7i3R0Gkbx_IcYLSp:-KYJzhFS0gVhCknkkBg3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L24)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: Odd line break.
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/random_source.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYHSNwyAAkDpeNBihNV:-KYJzkOWApXyyHHp4O6f:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, "explicit" superfluous here since there are two arguments.
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/random_source.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB7rcnTePBIsm8i147:-KYJzmog0Lns_zSCkntJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L46)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Per style guide, "Initialize" should be "Initializes".
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/random_source.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB7yq3sTFmb81HlIKh:-KYJzn8BBlBeEM4YnrEL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L49)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Per style guide, "Compute" should be "Computes", and "store" should be "stores".
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/random_source.h, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB84iCDgebmkWGd4WN:-KYJzplI2CD4IQWfGXWg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L53)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

For clarity, replace `int` with `const int`.
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/random_source.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYB8YB2_tsp5G4BbBPP:-KYJzqnX3RtyQXRKuIbq:b-md5hs7) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/random_source.h#L76)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I've seen `details` used as this kind of namespace but I think `internal` is OK too. I like the concept of getting this noise out of the API user's namespace.
</blockquote></details>

eigen also uses internal (and we've used it elsewhere in drake).  i prefer to leave it.

---

*[drake/systems/framework/primitives/test/random_source_test.cc, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYHW7JE4Mg7tucyNxCD:-KYK-Cgw5JKoLHGQTDNn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/test/random_source_test.cc#L71)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, "threshold+1" not minus.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358)*

**Comment by sherm1** [comment]
:lgtm: -- one new comment.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/primitives/test/random_source_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYHVDFR2k63FEdCN3pp:-KYKBn8P666iBGPwKDmJ:b-dy3u3z) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/test/random_source_test.cc#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, I second that!
</blockquote></details>

BTW, @seancurtis-tri pointed out that this would be simpler and somewhat clearer if `count` was computed as an int. You would have to add a cast to double below but that would be more obvious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-:-KYKCXFq7TO--CO8ESCg:bcs9jdm)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/primitives/test/random_source_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYHVDFR2k63FEdCN3pp:-KYKGiJG4ALpy1cN5Kdi:bwfpm6s) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/test/random_source_test.cc#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, @seancurtis-tri pointed out that this would be simpler and somewhat clearer if `count` was computed as an int. You would have to add a cast to double below but that would be more obvious.
</blockquote></details>

typing it in, i think it makes the code less readable to have the extra static casts in the way... I guess I find it more satisfying in it's current form..?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358)*

**Comment by sherm1** [comment]
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/primitives/test/random_source_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-KYHVDFR2k63FEdCN3pp:-KYKTNuaCYgXyLO3bWFH:b-2hqf97) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3423b2fbb8772bd2f2e64181290bcc55f1862/drake/systems/framework/primitives/test/random_source_test.cc#L38)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

typing it in, i think it makes the code less readable to have the extra static casts in the way... I guess I find it more satisfying in it's current form..?
</blockquote></details>

Definitely author's discretion and I liked it the way you wrote it but @seancurtis-tri does have a knack for finding simpler ways to do overly-clever things. Kind of a buzzkill though :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4358#-:-KYKXuqa0uUabpwkPYxK:bnfp4nl)*

**Pull request merged**
