### PR TITLE
Remove eiquadprog.h and its uses; its license is inappropriate for us

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2762)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I believe that @RussTedrake said @siyuanfeng-tri is the only potentially harmed / interested party by this change -- can I get a blessing on this concept from one or both of you before I seek to review and merge this PR?

**Comment by RussTedrake** [comment]
Confirmed.  Ok from me to remove it -- siyuan is the only (possible) user i know of.

**Comment by jwnimmer-tri** [comment]
Thanks.  I will wait to hear from @siyuanfeng-tri.

**Comment by RussTedrake** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2762)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2762#-:-KMLya16UtGT1fGXjR_T:1417088721)*

**Comment by jwnimmer-tri** [comment]
Siyuan says its okay to remove.

+@sherm1 for final review and merge.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2762#-:-KMPTr62zJjetX5GKciX:1417088721)*

**Pull request merged**
