### PR TITLE
Use drake::cars namespace for Cars software

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3357)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3357#-:-KR-7Nluypvi29yorWOK:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 34 of 35 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/Cars/car_simulation.cc, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3357#-KR-S83yf0rrE1qowJRE:-KR-S83yf0rrE1qowJRF:bpdo29l) ([raw file](https://github.com/robotlocomotion/drake/blob/43f4bc28c22e4922570d9cc4ec22a1d07e0bf804/drake/examples/Cars/car_simulation.cc#L13)):*
> ```cpp
> using Eigen::VectorXd;
> 
> using drake::parsers::ModelInstanceIdTable;
> ```

BTW, you could put this inside the `namespace drake` if you wanted.

---

*[drake/examples/Cars/test/car_simulation_test.cc, line 10 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3357#-KR-SWLZfqLq7ygXVxIy:-KR-SWLZfqLq7ygXVxIz:b-7ijzx1) ([raw file](https://github.com/robotlocomotion/drake/blob/1b0a3f2f3e8768002f431ba728449455f2e321aa/drake/examples/Cars/test/car_simulation_test.cc#L10)):*
> ```cpp
> namespace examples {
> namespace cars {
> namespace test {
> ```

BTW, the presence of this namespace was not a defect, but I consider it a mild antipattern and am happy to see it go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3357#-:-KR-SictgOSY4jP00kjP:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 34 of 34 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3357)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3357)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3357)*

**Pull request merged**
