### PR TITLE
Conditionally reset frames in show_frames.py.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This addresses issue #6894.

\cc @siyuanfeng-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6895)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Super simple change, I think. Tested on my machine.

+@sammy-tri for feature review, please.
+@ggould-tri for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6895#-:-KsFpuRyU4857ulXFxJ7:b-hcw7f6)*

**Comment by ggould-tri** [comment]
:lgtm:, one author's discretion issue noted below (@sammy-tri, feel free to override me on that item as you are more familiar with this code and its overall design)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/visualization/show_frames.py, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6895#-KsH57LnHE1H_GTym84-:-KsH57LnHE1H_GTym840:bj5xc5k) ([raw file](https://github.com/robotlocomotion/drake/blob/93a91f52caa68050bec6020489d86a30d808a31f/drake/multibody/rigid_body_plant/visualization/show_frames.py#L15)):*
> ```Python
>         self._name = "Frame Visualizer"
>         self._subscriber = None
>         self._frame_names_prev = []
> ```

FYI I found this name confusing -- it is not clear what it is previous to or why we call it previous.  If anything it is the current set of names for most of the time it carries any given value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6895#-:-KsH4kAMIcGuzk6otuIs:b-a8n3nq)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/visualization/show_frames.py, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6895#-KsH57LnHE1H_GTym84-:-KsJVorqkk-03TBQa3ld:b-uwrs9d) ([raw file](https://github.com/robotlocomotion/drake/blob/93a91f52caa68050bec6020489d86a30d808a31f/drake/multibody/rigid_body_plant/visualization/show_frames.py#L15)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI I found this name confusing -- it is not clear what it is previous to or why we call it previous.  If anything it is the current set of names for most of the time it carries any given value.
</blockquote></details>

FYI Sorry about that - at the beginning of each cycle, it is effectively the previous value, to then compare against the current frame names (and be updated afterward, where it would be unused after that update in the remainder of the cycle).

Would it be less confusing if it were called `link_names_prev`, or `link_names_published`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6895)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6895#-:-KsJY0KZCoGf6v-EMnx3:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6895)*

**Pull request merged**
