### PR TITLE
[workspace] Use libjchart2d-java from apt on Ubuntu

### LINKED ISSUE #13778: Use libjchart2d-java from apt on Ubuntu
Seems to be the same version that we currently use:

* https://packages.ubuntu.com/bionic/libjchart2d-java
* https://packages.ubuntu.com/focal/libjchart2d-java

Relates in part #12783.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Resolves #13778.  (This is a re-submission of #14786 with additional fixes.)

The CMake metadata files for jchart2d are no longer installed on any platform (not even on macOS, where we're installing the jar files).  They are not required by Drake anymore.
```
drake/lib/cmake/jchart2d/jchart2d-config-version.cmake
drake/lib/cmake/jchart2d/jchart2d-config.cmake
```

Even though the new classpath-searching code is untested, there is not any good way to test it here.  The only way to find jchart2d classpath errors is to run `lcm-spy` actually opening up a window.  The `--help` command line does not try to load jchart2d.  We would need to create a temporary headless `$DISPLAY` in order to test this, which doesn't seem worthwhile.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16185)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail most of this code was originally written by Kitware.  Is there anyone who could take a look here and serve as feature reviewer?

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for feature review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16185#-:-Mw2Qse630fCI32S0-5Q:bsxqb3)* status: LGTM missing from assignees BetsyMcPhail,mwoehlke-kitware, needs platform reviewer assigned (waiting on @BetsyMcPhail and @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
The `create_java_launcher` changes seem okay; I don't know that I'm qualified to review the new Bazel bits.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16185#-:-Mw2y-9B6wiHDDDVhvpy:bu4iin0)* status: 1 unresolved discussion, LGTM missing from assignees mwoehlke-kitware,BetsyMcPhail, needs platform reviewer assigned (waiting on @BetsyMcPhail, @jwnimmer-tri, and @mwoehlke-kitware)

___
*[tools/install/installer.py, line 358 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16185#-Mw2wqFR6ynluGY9Z1OD:-Mw2wqFR6ynluGY9Z1OE:b-z85met) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc4f5d743a09128588bb0e7127775e84ee9da1a/tools/install/installer.py#L358)):*
> ```Python
> # Seek our jar depencencies on the host system.
> prefix=/usr
> for jar_file in {classpath}; do
> ```

While I approve of this improvement in general, I wonder about going further and just making this an f-string?

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for extra feature review, local testing of lcm-spy, and platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16185#-:-Mw3FbRp2pOdZJ2MuaaW:b-mm0zwj)* status: LGTM missing from assignees mwoehlke-kitware,BetsyMcPhail,sammy-tri(platform) (waiting on @BetsyMcPhail, @mwoehlke-kitware, and @sammy-tri)

___
*[tools/install/installer.py, line 358 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16185#-Mw2wqFR6ynluGY9Z1OD:-Mw3FV5j2wxYZDCe9UCp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc4f5d743a09128588bb0e7127775e84ee9da1a/tools/install/installer.py#L358)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

While I approve of this improvement in general, I wonder about going further and just making this an f-string?
</blockquote></details>

Done.

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: Thank you for solving this one!

> Reviewed 16 of 22 files at r2, 6 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16185#-:-Mw3IxO10SJJeIQKxarL:blrdiak)* status: LGTM missing from assignees sammy-tri(platform),mwoehlke-kitware (waiting on @BetsyMcPhail, @mwoehlke-kitware, and @sammy-tri)

___
*[tools/install/install.bzl, line 346 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16185#-Mw3IpPp1vGJ1qSJPcKs:-Mw3IpPp1vGJ1qSJPcKt:b-ak9df2) ([raw file](https://github.com/robotlocomotion/drake/blob/163281e94e050a8557b64869b0d0442394c5d9d7/tools/install/install.bzl#L346)):*
> ```Starlark
>         # Adding double quotes around the generated scripts to avoid
>         # white-space problems when running the generated shell script. This
>         # string is used in a "for-loop" in the script.
> ```

BTW Double-checking that removing this comment was intentional?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16185)* status: LGTM missing from assignees sammy-tri(platform),mwoehlke-kitware (waiting on @BetsyMcPhail, @mwoehlke-kitware, and @sammy-tri)

___
*[tools/install/install.bzl, line 346 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16185#-Mw3IpPp1vGJ1qSJPcKs:-Mw3JIgSAs661ak1KnYM:brxrgfe) ([raw file](https://github.com/robotlocomotion/drake/blob/163281e94e050a8557b64869b0d0442394c5d9d7/tools/install/install.bzl#L346)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

BTW Double-checking that removing this comment was intentional?
</blockquote></details>

Yup -- as best I can tell, nothing either here or in the installer.py code is adding double-quotes anywhere.  It seemed like the comment was vestigial, from some earlier draft of the code that never got committed.

**Comment by mwoehlke-kitware** [comment]
___
*[tools/install/installer.py, line 358 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16185#-Mw2wqFR6ynluGY9Z1OD:-Mw3Qov72ux8JNfex5W7:b-83sjoh) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc4f5d743a09128588bb0e7127775e84ee9da1a/tools/install/installer.py#L358)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!

**Review by sammy-tri — COMMENTED** [review]
Ran `//lcmtypes:drake-lcm-spy` both from a `bazel-bin` invocation and a locally installed drake.  Worked in both cases.

:lgtm:

> Reviewed 9 of 22 files at r2, 6 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16185#-:-Mw3jtiA0FQaFRJGAVjW:bgbd2xq)* status: LGTM missing from assignee mwoehlke-kitware (waiting on @jwnimmer-tri)

**Pull request merged**
