### PR TITLE
[workspace] Upgrade ipopt to latest release 3.14.13

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20525)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20525#-:-Nj98ADZ-M5DihmB_gi5:bxqo58p)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
