### PR TITLE
[tutorials] Add linter for required styles choices

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Canonicalize the preamble text.

Towards #13683.

Requires:
- [x] #16837

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16838)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

As a nice demo, we'll see that this PR fails CI because of some existing lint.  Once #16837 merges, we should be happy here.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm:
+(release notes: none) ?

> Reviewed 14 of 16 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16838#-:-Myrtf0VBdFIrYpcn3aj:bcfpppx)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
(@rpoyner-tri only waiting on your LGTM.)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16838#-:-Mys1SLNBVYa6g4poawc:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16838)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
