### PR TITLE
doc: Add note about configuration management non-determinism

### LINKED ISSUE #7747: mac install_prereqs.sh results in obtaining newest bazel, but we only document support for a pinned version
This might be causing the problem in https://github.com/RobotLocomotion/drake-shambhala/issues/78.  

But really, I think it's more fundamental than a bazel problem.  These installation instructions are not pegging versions, so will move with homebrew.  Are the build servers running install_prereqs regularly?  If yes, then perhaps we primarily need to improve test coverage of the installed packages.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #7747

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10169)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Yes, "all incompatible changes" has been on the TODO list for a while, but we are way off that being clean, so it would not be good news for the canary.

Otherwise, it is not as bad as it seems. To a certain extent, we could just remove mentions of exact versions of most things other than Bazel, and even then, the truth is the prereqs script for Ubuntu.

The essential point is that if someone runs the prereqs script on any given day, Drake should work for them. What is documentation says and what we run on CI is really secondary.

**Comment by jwnimmer-tri** [comment]
Yup, agreed.

Also FWIW, I would also have been okay closing #7747 as "wontfix", for exactly those reasons.

**Comment by jwnimmer-tri** [comment]
@jamiesnape Any other suggestions, or else we need an LGTM emoji from you.

**Comment by EricCousineau-TRI** [comment]
Thanks! Will merge; can take out later if it's too much to maintain or clutters the other text.

**Pull request merged**
