### PR TITLE
[cmake] Remove incorrect warning on Jammy python version

### LINKED ISSUE #17892: CMake on Jammy erroneously warns about python versions
### What happened?

A user reported to me: Did anybody successfully build drake on Ubuntu 22.04?
https://drake.mit.edu/from_source.html advertises the support, but I get the following with cmake:
```
-- Found Python: /usr/bin/python3 (found suitable exact version "3.10.4") found components: Development Interpreter NumPy Development.Module Development.Embed 
CMake Warning at CMakeLists.txt:252 (message):
  Python version 3.10 is NOT supported.  Python code in project
  drake_cxx_python may fail at runtime.
```

Looking at CMakeLists.txt [here](https://github.com/RobotLocomotion/drake/blob/360133f6efe33e2606b31836d1dcd643e97aa7af/CMakeLists.txt#L251-L256), I see 
```
if(NOT PYTHON_VERSION_MAJOR_MINOR VERSION_EQUAL SUPPORTED_PYTHON_VERSION)
  message(WARNING
    "Python version ${PYTHON_VERSION_MAJOR_MINOR} is NOT supported. Python "
    "code in project drake_cxx_python may fail at runtime."
  )
endif()
```

and [just above](
https://github.com/RobotLocomotion/drake/blob/360133f6efe33e2606b31836d1dcd643e97aa7af/CMakeLists.txt#L204-L208)
I see
```
if(APPLE)
  set(SUPPORTED_PYTHON_VERSION 3.10)
else()
  set(SUPPORTED_PYTHON_VERSION 3.8)
endif()
```

It looks like we need to update this logic to include Jammy?

### Version

_No response_

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using CMake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by svenevs**
Closes #17892.

I've tested locally on focal and jammy, no warnings about python versions occur anymore.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17896)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17896#-:-NBnBYXu6ZIKogieaMZN:bs3ynz8)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-gcc-cmake-experimental-release please.
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-snopt-release please.

**Review by svenevs — COMMENTED** [review]
Focal CMake configure log:

```
[3:38:35 PM]  Run command: "/usr/bin/cmake" "--warn-uninitialized" "-DCMAKE_BUILD_TYPE:STRING=Release" "-GUnix Makefiles" "/media/ephemeral0/ubuntu/workspace/linux-focal-gcc-cmake-experimental-release/src"
[3:38:35 PM]  Warn about uninitialized values.
[3:38:35 PM]  -- The C compiler identification is GNU 9.4.0
[3:38:35 PM]  -- The CXX compiler identification is GNU 9.4.0
[3:38:35 PM]  -- Check for working C compiler: /usr/bin/gcc
[3:38:35 PM]  -- Check for working C compiler: /usr/bin/gcc -- works
[3:38:35 PM]  -- Detecting C compiler ABI info
[3:38:35 PM]  -- Detecting C compiler ABI info - done
[3:38:35 PM]  -- Detecting C compile features
[3:38:35 PM]  -- Detecting C compile features - done
[3:38:35 PM]  -- Check for working CXX compiler: /usr/bin/g++
[3:38:35 PM]  -- Check for working CXX compiler: /usr/bin/g++ -- works
[3:38:35 PM]  -- Detecting CXX compiler ABI info
[3:38:35 PM]  -- Detecting CXX compiler ABI info - done
[3:38:35 PM]  -- Detecting CXX compile features
[3:38:35 PM]  -- Detecting CXX compile features - done
[3:38:36 PM]  -- Found Bazel: /usr/bin/bazel (found suitable version "5.1.0", minimum required is "3.0") 
[3:38:36 PM]  -- Found Python: /usr/bin/python3 (found suitable exact version "3.8.10") found components: Development Interpreter NumPy 
[3:38:36 PM]  -- Found Git: /usr/bin/git (found version "2.25.1") 
[3:38:36 PM]  -- Configuring done
[3:38:36 PM]  -- Generating done
[3:38:36 PM]  -- Build files have been written to: /media/ephemeral0/ubuntu/workspace/linux-focal-gcc-cmake-experimental-release/_cmake_ubuntu
[3:38:36 PM]  Command exited with the value: 0
```

Jammy configure log:

```
[3:40:52 PM]  Run command: "/usr/bin/cmake" "--warn-uninitialized" "-DCMAKE_BUILD_TYPE:STRING=Release" "-GUnix Makefiles" "/media/ephemeral0/ubuntu/workspace/linux-jammy-gcc-cmake-experimental-snopt-release/src"
[3:40:53 PM]  Warn about uninitialized values.

[3:40:54 PM]  -- The C compiler identification is GNU 11.2.0
[3:40:54 PM]  -- The CXX compiler identification is GNU 11.2.0
[3:40:54 PM]  -- Detecting C compiler ABI info
[3:40:54 PM]  -- Detecting C compiler ABI info - done
[3:40:54 PM]  -- Check for working C compiler: /usr/bin/gcc - skipped
[3:40:54 PM]  -- Detecting C compile features
[3:40:54 PM]  -- Detecting C compile features - done
[3:40:54 PM]  -- Detecting CXX compiler ABI info
[3:40:54 PM]  -- Detecting CXX compiler ABI info - done
[3:40:54 PM]  -- Check for working CXX compiler: /usr/bin/g++ - skipped
[3:40:54 PM]  -- Detecting CXX compile features
[3:40:54 PM]  -- Detecting CXX compile features - done

[3:40:56 PM]  -- Found Bazel: /usr/bin/bazel (found suitable version "5.1.0", minimum required is "3.0") 

[3:41:00 PM]  -- Found Python: /usr/bin/python3 (found suitable exact version "3.10.4") found components: Development Interpreter NumPy Development.Module Development.Embed 

[3:41:03 PM]  -- The Fortran compiler identification is GNU 11.2.0
[3:41:03 PM]  -- Detecting Fortran compiler ABI info
[3:41:03 PM]  -- Detecting Fortran compiler ABI info - done
[3:41:03 PM]  -- Check for working Fortran compiler: /usr/bin/gfortran - skipped
[3:41:03 PM]  -- Found Git: /usr/bin/git (found version "2.34.1") 
[3:41:03 PM]  -- Configuring done
[3:41:03 PM]  -- Generating done
[3:41:03 PM]  -- Build files have been written to: /media/ephemeral0/ubuntu/workspace/linux-jammy-gcc-cmake-experimental-snopt-release/_cmake_ubuntu
[3:41:03 PM]  Command exited with the value: 0
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17896#-:-NBnCqbABfKmL6om4UPj:bccxyix)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17896#-:-NBsKZYn3ptp220bDeJT:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
+@sammy-tri for platform review please.  +(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17896#-:-NBsPm6U0s-0Os97_zrN:b-10ykhw)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17896#-:-NBsVUVP4bXlaRZj0Wkz:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),BetsyMcPhail (waiting on @svenevs)

**Pull request merged**
