### PR TITLE
Updated documentation of RigidBody's set/get position/velocity start index methods.

### PR DESCRIPTION
**Pull request by liangfok**
The old documentation for the velocity index was wrong. It is _not_ relative to the beginning of RigidBodyTree's state vector, but rather it is relative to the portion of the state vector that holds the joint velocity vector.

I fixed the documentation for set / get velocity start index methods, and also updated the set / get position start index methods for consistency.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3246)

### CODE REVIEW

**Comment by liangfok** [comment]
Since this touches `RigidBody*` and @amcastro-tri is busy with RBS2:

+@hongkai-dai for feature review please.
+@sherm1 for platform review please (to the best of my knowledge, you're the only platform reviewer in the dynamics team).

Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KPy3oytwo1Qe_M_kiwL:b-418hcy)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246)*

**Comment by sherm1** [comment]
Reviewed. BTW, since you wanted a dynamics-team reviewer this is really a feature review. But for this comment-only change I can serve as platform reviewer too. Some changes requested -- PTAL.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 81 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2WXDM_BfqBrx0tA3R:-KQ2WXDM_BfqBrx0tA3S:b3rdy6x) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L81)):*
> ```objc
>   const RigidBody* get_parent() const;
> 
>   bool hasParent() const;
> ```

BTW, this could use a comment I think.

---

*[drake/systems/plants/RigidBody.h, line 108 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2XD-47UYAQIn8afVT:-KQ2XD-47UYAQIn8afVU:bazghjb) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L108)):*
> ```objc
> 
>   /**
>    * Sets the start index of this rigid body's joint position state within the
> ```

I think it would be helpful to use more technical terms here, and keep the documentation focused on this body/joint. Consider: "Sets the start index of this body's contiguous generalized coordinates q (joint position state variables) within the full RigidBodyTree generalized coordinate vector. 

Also don't add commentary about how the RigidBodyTree organizes its overall state vector, unless you are saying RigidBody is depending on that. Otherwise a later change to RigidBodyTree might invalidate this comment but there would be no way to know the comment needs to be changed.

---

*[drake/systems/plants/RigidBody.h, line 123 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2Wol6-kOw3xS4IY_b:-KQ2Wol6-kOw3xS4IY_c:b-3bevbx) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L123)):*
> ```objc
>    * beginning of `RigidBodyTree`'s state vector, the actual starting index of
>    * this body's joint position state within `RigidBodyTree`'s state vector is
>    * equal to this method's return value.
> ```

This is too much duplication. Instead I suggest something like: "Returns the start index of this body's position states; see `set_position_start_index()` for more information."

---

*[drake/systems/plants/RigidBody.h, line 128 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2YskdvptyyA9jmZHi:-KQ2Yske8GfcafAYGe-l:bfjcyzc) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L128)):*
> ```objc
> 
>   /**
>    * Sets the start index of this rigid body's joint velocity state within the
> ```

Consider: "Sets the start index of this body's contiguous generalized velocity v (joint velocity state variables) within the full RigidBodyTree generalized velocity vector.  (And no need to extend the discussion to the whole tree.)

---

*[drake/systems/plants/RigidBody.h, line 143 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2Z7uN9MkR225bNCxZ:-KQ2Z7uN9MkR225bNCx_:brxfezg) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L143)):*
> ```objc
>    * follows the joint position state vector in `RigidBodyTree`'s state vector,
>    * the actual starting index of this body's joint velocity state is this
>    * method's return value plus RigidBodyTree::number_of_positions().
> ```

Refer to the `set` method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQ2ZCdE6UFniyvupVsj:bruh98j)*

**Comment by liangfok** [comment]
I responded to all reviewer commands and addressed some of them. PTAL. Thanks!

---

Review status: 0 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 81 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2WXDM_BfqBrx0tA3R:-KQCrSItfOa4Sslt1ei5:b-h8shh7) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L81)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, this could use a comment I think.
</details>
Done. I went ahead and also made it style guide compliant.

---

*[drake/systems/plants/RigidBody.h, line 108 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2XD-47UYAQIn8afVT:-KQDblDkXmN3x7UlEOdw:bx4i4l3) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L108)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I think it would be helpful to use more technical terms here, and keep the documentation focused on this body/joint. Consider: "Sets the start index of this body's contiguous generalized coordinates q (joint position state variables) within the full RigidBodyTree generalized coordinate vector. 
> 
> Also don't add commentary about how the RigidBodyTree organizes its overall state vector, unless you are saying RigidBody is depending on that. Otherwise a later change to RigidBodyTree might invalidate this comment but there would be no way to know the comment needs to be changed.
</details>
Thanks for the advice on technical terms. Since your description might be too technical for people who have not carefully studied rigid body mechanics, I also included a less technical description that I believe will be more digestible by general software engineers. I'm afraid, however, that it may violate your desire to hide the way `RigidBodyTree` organizes its state vector. 

Note that I originally decided to document the internal state organization because it is assumed by numerous other places in Drake's code base. See, for example:

https://github.com/RobotLocomotion/drake/blob/56ab439d74eb21a03751426400b1d78423d114d0/drake/examples/Cars/car_simulation.cc#L172

---

*[drake/systems/plants/RigidBody.h, line 123 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2Wol6-kOw3xS4IY_b:-KQDe4lhTwbT-WD0l1xB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L123)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is too much duplication. Instead I suggest something like: "Returns the start index of this body's position states; see `set_position_start_index()` for more information."
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 128 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2YskdvptyyA9jmZHi:-KQDiYyFq3J7cduG2iuY:bb26hnu) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L128)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Consider: "Sets the start index of this body's contiguous generalized velocity v (joint velocity state variables) within the full RigidBodyTree generalized velocity vector.  (And no need to extend the discussion to the whole tree.)
</details>
Done. Same comment here about wanting to also provide a less technical description and document the internal data organization.

---

*[drake/systems/plants/RigidBody.h, line 143 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2Z7uN9MkR225bNCxZ:-KQDii2nTYdQVu2a0wn0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L143)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Refer to the `set` method.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQDikAtifI2Co7aRSnv:b-smyq2r)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/4175/ and is thus ready for review.

---

Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQE7PMlZ18XI9m_A56D:bb0jr3z)*

**Comment by hongkai-dai** [comment]
I put a minor comment, otherwise :lgtm: 

---

Reviewed 14 of 15 files at r2.
Review status: 14 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 122 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQErSDf4JE-GV0HQsVQ:-KQErSDgJDvQWDOAIzS5:b-4crigr) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6baf1c0e06637e0d6171a5d66cce1e5c7cf4f2/drake/systems/plants/RigidBody.h#L122)):*
> ```objc
>   /**
>    * Sets the start index of this rigid body's parent joint's contiguous
>    * generalized coordinates `q` (joint position state variables) within the
> ```

Could you add a paragraph saying that if we have multiple models inside one RigidBodyTree, we will concatenate the position and velocities separately. It would look like
```
[vector of model 1 position states ; vector of model 2 position states;...]
[vector of model 1 velocity states; vector of model 2 velocity states;...]
```
This can rule out the possible confusion that the state could be
```
[vector of model 1 position states; vector of model 1 velocity states; vector of model 2 position states; vector of model 2 velocity states;...]
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQEsYUx5zN0oJk5oRWq:b-7azjas)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. 

---

Review status: 14 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 122 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQErSDf4JE-GV0HQsVQ:-KQGB3iGmHN5bGX6dIPK:b5muam0) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6baf1c0e06637e0d6171a5d66cce1e5c7cf4f2/drake/systems/plants/RigidBody.h#L122)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Could you add a paragraph saying that if we have multiple models inside one RigidBodyTree, we will concatenate the position and velocities separately. It would look like
> ```
> [vector of model 1 position states ; vector of model 2 position states;...]
> [vector of model 1 velocity states; vector of model 2 velocity states;...]
> ```
> This can rule out the possible confusion that the state could be
> ```
> [vector of model 1 position states; vector of model 1 velocity states; vector of model 2 position states; vector of model 2 velocity states;...]
> ```
</details>
Ah good point! That is indeed something that threw me off for a while. I verified that you're correct here:

https://github.com/liangfok/drake/blob/f769aaff2a4abced1dca6a7eaa4b55649f5e62ec/drake/examples/Cars/car_simulation.cc#L329

I've updated the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQGJi_kugnAyLMNTzVX:brn7v3u)*

**Comment by sherm1** [comment]
Platform review -- a few comments.

---

Reviewed 14 of 15 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 108 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2XD-47UYAQIn8afVT:-KQJEeWbrqUdn3a_10Gj:b-mmcqd3) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L108)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Thanks for the advice on technical terms. Since your description might be too technical for people who have not carefully studied rigid body mechanics, I also included a less technical description that I believe will be more digestible by general software engineers. I'm afraid, however, that it may violate your desire to hide the way `RigidBodyTree` organizes its state vector. 
> 
> Note that I originally decided to document the internal state organization because it is assumed by numerous other places in Drake's code base. See, for example:
> 
> https://github.com/RobotLocomotion/drake/blob/56ab439d74eb21a03751426400b1d78423d114d0/drake/examples/Cars/car_simulation.cc#L172
</details>
No, my point is you can't document this *here*. If you want to document how RigidBodyTree lays out its state vector, that has to be done in the RigidBodyTree class. You can document any assumptions that RigidBody is depending on here, but I don't see that there is a dependency on anything other than that the body's own q's will be contiguous and its v's will be contiguous.

The documentation you wrote looks nice, it is just in the wrong place.

---

*[drake/systems/plants/RigidBody.h, line 128 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2YskdvptyyA9jmZHi:-KQJHKPhf8qKrVgrZR1U:bd28d7x) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L128)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. Same comment here about wanting to also provide a less technical description and document the internal data organization.
</details>
Two problems here: (1)  as above, this documentation belongs with RigidBodyTree, and (2) this is duplicative and should be said only once. What you are doing here would lead to this description being repeated everywhere someone mentions a joint coordinate! That is not maintainable.

---

*[drake/systems/plants/RigidBody.h, line 84 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQJC3_jk-R4y0PsaAjZ:-KQJC3_kKyLlK2Db7Ud8:b17v9ue) ([raw file](https://github.com/robotlocomotion/drake/blob/bae074e7157bb6d8bcaca1ea2bcc57c8bc49b9bc/drake/systems/plants/RigidBody.h#L84)):*
> ```objc
>   /**
>    * Returns whether this rigid body has a parent joint. A parent joint is one
>    * that conncts this rigid body to the next rigid body up the tree. Thus,
> ```

Typo. Also, "up the tree" is ambiguous (typically a root is down!). The terms "inboard" (towards root) and "outboard" (away from root) are unambiguous.

Also, in multibody dynamics it is conventional to talk about the parent and child *bodies*, because those establish the coordinate frames in which we can define the joint coordinates. The unique joint that connects a body into the multibody tree is called the body's "inboard joint" or "mobilizer". In some mechanisms it is necessary for the parent/child sense (which sets the sign conventions for the joint) to be reversed from the inboard/outboard sense (which describes the tree topology). So it is potentially confusing to refer to the joint as a "parent"; let's reserve that term for bodies. I recommend the term "mobilizer" as the wholly unambiguous name for the unique, internal coordinate joint that attaches a body to its multibody tree.

However, I'm confused about the `has_parent()` method. If it really just distinguishes world from all other bodies then why not replace it with `is_world()` (or I guess `!is_world()`)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQJL5vs9oRh0yDueRaf:b-dwynwt)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 108 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2XD-47UYAQIn8afVT:-KQL0-UrWzrOFmbozwvx:b-ctf7tu) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L108)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> No, my point is you can't document this *here*. If you want to document how RigidBodyTree lays out its state vector, that has to be done in the RigidBodyTree class. You can document any assumptions that RigidBody is depending on here, but I don't see that there is a dependency on anything other than that the body's own q's will be contiguous and its v's will be contiguous.
> 
> The documentation you wrote looks nice, it is just in the wrong place.
</details>
OK I will move the description of the internal state organization into the class description of `RigidBodyTree`. Just a quick note that I provided the wrong URL above. The correct URL that shows an example assumption of the current internal state organization is here:


https://github.com/RobotLocomotion/drake/blob/56ab439d74eb21a03751426400b1d78423d114d0/drake/examples/Cars/car_simulation.cc#L205

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks.

---

Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 108 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2XD-47UYAQIn8afVT:-KQLhFVp7lgETzTa7sMn:b-uanmng) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L108)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> OK I will move the description of the internal state organization into the class description of `RigidBodyTree`. Just a quick note that I provided the wrong URL above. The correct URL that shows an example assumption of the current internal state organization is here:
> 
> 
> https://github.com/RobotLocomotion/drake/blob/56ab439d74eb21a03751426400b1d78423d114d0/drake/examples/Cars/car_simulation.cc#L205
</details>
Done. The description of how the internal state is organized within a `RigidBodyTree` is now in `RigidBodyTree`.

---

*[drake/systems/plants/RigidBody.h, line 128 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQ2YskdvptyyA9jmZHi:-KQLhNuCCYBHLKkgBgNY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e90326109987d44af22f10824ede22b37413a28c/drake/systems/plants/RigidBody.h#L128)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Two problems here: (1)  as above, this documentation belongs with RigidBodyTree, and (2) this is duplicative and should be said only once. What you are doing here would lead to this description being repeated everywhere someone mentions a joint coordinate! That is not maintainable.
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 84 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQJC3_jk-R4y0PsaAjZ:-KQLXJFRqLhBV3HH6f9j:b-m02uxk) ([raw file](https://github.com/robotlocomotion/drake/blob/bae074e7157bb6d8bcaca1ea2bcc57c8bc49b9bc/drake/systems/plants/RigidBody.h#L84)):*
> I recommend the term "mobilizer" as the wholly unambiguous name for the unique, internal coordinate joint that attaches a body to its multibody tree.

I renamed the method `has_mobilizer_joint()`.

> However, I'm confused about the has_parent() method. If it really just distinguishes world from all other bodies then why not replace it with is_world() (or I guess !is_world())?

After studying the various call sights of `has_parent()`, I believe it is mostly used to handle malformed `RigidBodyTree` objects that contain fragments of trees that have no kinematic path to the root. I believe this may be an over abundance of caution since such malformations can and should be detected when calling `RigidBodyTree::compile()`. I think enforcing such an invariant is too big for this PR and shall thus track its future change here: https://github.com/RobotLocomotion/drake/issues/3293

Another use of this method is to detect loop joints within the SDF parser. Thus, I don't think the method can be eliminated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQLlH3V9NAu1nBPQExC:bblnx7v)*

**Comment by liangfok** [comment]
I believe https://drake-jenkins.csail.mit.edu/job/experimental/4211/ contains a spurrious CI MATLAB flake.

---

Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQMcJ6K9qr9pY0UjrUg:bfawslm)*

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/4215/ and is thus ready for review.

**Comment by sherm1** [comment]
Reviewed; a few minor things left.

---

Reviewed 16 of 16 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 132 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQR-pqNz_JvbNFiPXjY:-KQR-pqNz_JvbNFiPXjZ:bxv65ac) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L132)):*
> ```objc
>    * Parameter @p position_start_index is the index relative to the beginning of
>    * `[vector of model instance 1's position states]` where the position states
>    * of this rigid body's parent joint begins.
> ```

you already said this above

---

*[drake/systems/plants/RigidBody.h, line 137 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQR-ruDMrRyiOSX8yp3:-KQR-ruDMrRyiOSX8yp4:bid5gl) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L137)):*
> ```objc
>    * beginning of the RigidBodyTree's full state vector, the starting index of
>    * this rigid body's parent joint's position state vector within the
>    * RigidBodyTree's full state vector is equal to @p position_start_index.
> ```

BTW, entangles RBTree full state layout with local RB coordinates -- is that necessary? Even if so, definitely doesn't need to introduce "model instance" concept here. Sufficient to say "RBTree position states begin at the start of the full state vector so the position_start_index also provides this RB's position state location within the full state."

---

*[drake/systems/plants/RigidBody.h, line 153 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQQyOmarCj9IGmHlEmC:-KQQyOmarCj9IGmHlEmD:b495sxi) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L153)):*
> ```objc
>    *
>    * In other words, the RigidBodyTree's generalized coordinate vector looks
>    * like the following:
> ```

delete above sentence

---

*[drake/systems/plants/RigidBody.h, line 160 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQQz2Kpb0WXpfp2kWjq:-KQQz2KqBGtKyqCTfqy0:bxv65ac) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L160)):*
> ```objc
>    * Parameter @p velocity_start_index is the index relative to the beginning of
>    * `[vector of model 1's velocity states]` where the velocity states of this
>    * body's parent joint begins.
> ```

you already said this above

---

*[drake/systems/plants/RigidBody.h, line 170 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQQyY-cxDmqtya9N0Gf:-KQQyY-cxDmqtya9N0Gg:b-hcejc4) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L170)):*
> ```objc
>    * <pre>
>    * velocity_start_index + RigidBodyTree::number_of_positions()
>    * </pre>
> ```

BTW, these two paragraphs entangle the RB velocity index with how the RBTree lays out its overall state vector. Is that necessary? Why isn't it enough to say that the velocity index is an offset from the start of RBTree's velocity states without having to specify how RBTree deals with unrelated state variables? If this is needed here, you can shorten it substantially since you already referred to the RBTree state documentation and don't need to repeat it here. You could replace these last 3 paragraphs with just: "If you need to locate this rigid body's velocity state within the full rigid body tree's state vector, it is RBTree::num_pos()+vel_start_index."

---

*[drake/systems/plants/RigidBodyTree.h, line 53 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQR1G6OrUf2NpY_n-wo:-KQR1G6OrUf2NpY_n-wp:b-k0o1l0) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBodyTree.h#L53)):*
> ```objc
>  *
>  * RigidBody objects maintain indices to their coordinate and velocity states
>  * within the above vector. These indeces can be obtained via
> ```

Typo. Also, I think you said that the velocity indexes start at the beginning of the velocity state variables, rather than at the beginning of the full state vector. If that's right it should say so here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQR1jyOvCci2WKSR57H:b-q48gw1)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks.

---

Review status: 14 of 16 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 132 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQR-pqNz_JvbNFiPXjY:-KQX6aiimvA_qW6ve33P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L132)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> you already said this above
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 137 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQR-ruDMrRyiOSX8yp3:-KQX6b_zeMPo9lEiWiDw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L137)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, entangles RBTree full state layout with local RB coordinates -- is that necessary? Even if so, definitely doesn't need to introduce "model instance" concept here. Sufficient to say "RBTree position states begin at the start of the full state vector so the position_start_index also provides this RB's position state location within the full state."
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 153 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQQyOmarCj9IGmHlEmC:-KQX6gGlr79rTsnPip8a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L153)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> delete above sentence
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 160 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQQz2Kpb0WXpfp2kWjq:-KQXD7mt9IXNnc43gfsg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L160)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> you already said this above
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 170 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQQyY-cxDmqtya9N0Gf:-KQXD8_ZbpWine-8IoiD:bena780) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBody.h#L170)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, these two paragraphs entangle the RB velocity index with how the RBTree lays out its overall state vector. Is that necessary? Why isn't it enough to say that the velocity index is an offset from the start of RBTree's velocity states without having to specify how RBTree deals with unrelated state variables? If this is needed here, you can shorten it substantially since you already referred to the RBTree state documentation and don't need to repeat it here. You could replace these last 3 paragraphs with just: "If you need to locate this rigid body's velocity state within the full rigid body tree's state vector, it is RBTree::num_pos()+vel_start_index."
</details>
Done. I moved this entire discussion to `RigidBodyTree`.

---

*[drake/systems/plants/RigidBodyTree.h, line 53 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-KQR1G6OrUf2NpY_n-wo:-KQXP5T-W__Ky8RA0PgK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/652f5078dd17fc1fa3b73a773114a9a1ddad3816/drake/systems/plants/RigidBodyTree.h#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Typo. Also, I think you said that the velocity indexes start at the beginning of the velocity state variables, rather than at the beginning of the full state vector. If that's right it should say so here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQXPU7OoLf_AUI90TXC:bblnx7v)*

**Comment by sherm1** [comment]
Thanks, Liang -- :lgtm:.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3246#-:-KQY1Oyy9ztBUSQ4DilD:ba8ukrr)*

**Pull request merged**
