### PR TITLE
[doc] Improve source install instructions

### LINKED ISSUE #19009: Mention setting PYTHONPATH for pydrake on Ubuntu 22.04
### What happened?

Currently our instruction on https://drake.mit.edu/from_source.html only mentions setting PYTHONPATH for Ubuntu 20.04, which uses python 3.8. On ubuntu 22.04 I think it uses python 3.10, so the PYTHONPATH should be 
```
export PYTHONPATH=${PWD}/install/lib/python3.10/site-packages:${PYTHONPATH}
```

### Version

_No response_

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using CMake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Prefer https shallow cloning for upstream.
Reduce prereqs page splatter.
Add a reminder about CMake behavior.

+@xuchenhan-tri for feature review, please.

Closes #19009.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19486)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 
+@sherm1 for platform review please

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-:-NWDvWeJA4WWoixvYVit:b-67470a)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`doc/_pages/from_source.md` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-NWDvDx-6Z6U9jWyyasR:-NWDvDx-6Z6U9jWyyasS:b-br4we8) ([raw file](https://github.com/RobotLocomotion/drake/blob/73adcb3e0805f0ad6cb77a67b53a7b69c7f31257/doc/_pages/from_source.md#L48)):*
> ```Markdown
> 
> ```
> git clone --filter=blob:none https://github.com/RobotLocomotion/drake.git
> ```

TIL.

I suppose this is for speed reason mostly? This is about twice as fast than the full clone on my Puget.
___
*[`doc/_pages/mac.md` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-NWDhzi21_qhFp_yMIdL:-NWDhzi21_qhFp_yMIdM:bxfrt77) ([raw file](https://github.com/RobotLocomotion/drake/blob/73adcb3e0805f0ad6cb77a67b53a7b69c7f31257/doc/_pages/mac.md#L6)):*
> ```Markdown
> 
> This content has been moved to [Source Installation](/from_source.html).
> ```

nit empty line

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19486)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`doc/_pages/from_source.md` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-NWDvDx-6Z6U9jWyyasR:-NWE57_o6_4GLmMkra8E:b-en6zjt) ([raw file](https://github.com/RobotLocomotion/drake/blob/73adcb3e0805f0ad6cb77a67b53a7b69c7f31257/doc/_pages/from_source.md#L48)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

TIL.

I suppose this is for speed reason mostly? This is about twice as fast than the full clone on my Puget.
</blockquote></details>

Yes.  It's faster, especially by not downloading long-since-deleted mesh files.

BTW the downside is that `git blame` is somewhat slower (since it needs to hit the server to get the old file contents).

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19486)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`doc/_pages/from_source.md` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-NWDvDx-6Z6U9jWyyasR:-NWE6-N17w2RvzyNrP1C:bi7r74i) ([raw file](https://github.com/RobotLocomotion/drake/blob/73adcb3e0805f0ad6cb77a67b53a7b69c7f31257/doc/_pages/from_source.md#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes.  It's faster, especially by not downloading long-since-deleted mesh files.

BTW the downside is that `git blame` is somewhat slower (since it needs to hit the server to get the old file contents).
</blockquote></details>

Makes sense. Thanks for the explanation.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one suggestion

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-:-NWEgx2C5p0Pn3cjPxxd:b-g6fn90)* status: 2 unresolved discussions

___
*[`doc/_pages/from_source.md` line 32 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-NWEdxnt6Jwt-Ul9YB5L:-NWEdxnt6Jwt-Ul9YB5M:br2ycni) ([raw file](https://github.com/RobotLocomotion/drake/blob/233960bfcbd4d433f18ad157292f11f06f21e4d8/doc/_pages/from_source.md#L32)):*
> ```Markdown
> report.
> 
> All else being equal, we would recommend developers use Ubuntu Jammy.
> ```

BTW above it says "Ubuntu 22.04" here "Jammy". Not clear to me that everyone will know those are the same thing. Consider "Ubuntu 22.04 (Jammy)"
___
*[`doc/_pages/from_source.md` line 48 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-NWEfUytDcK-4qhariJn:-NWEfUytDcK-4qhariJo:b-kyyabq) ([raw file](https://github.com/RobotLocomotion/drake/blob/233960bfcbd4d433f18ad157292f11f06f21e4d8/doc/_pages/from_source.md#L48)):*
> ```Markdown
> 
> ```
> git clone --filter=blob:none https://github.com/RobotLocomotion/drake.git
> ```

BTW if I understand correctly, this is trading off "clone" time now for later "as needed" downloads. It's not clear to me that this is the best tradeoff if it means a user would require network access in order to do a conceptually read-only activity like a build.

Consider saying a little more here so that the reader is equipped to make the tradeoff rather than us dictating it. Maybe something like: "The filter defers large downloads until they are needed; if you want all the source now leave that out."

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19486)* status: 2 unresolved discussions

___
*[`doc/_pages/from_source.md` line 48 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-NWEfUytDcK-4qhariJn:-NWF8o5lA9HOLFECbuIO:bwf10ci) ([raw file](https://github.com/RobotLocomotion/drake/blob/233960bfcbd4d433f18ad157292f11f06f21e4d8/doc/_pages/from_source.md#L48)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW if I understand correctly, this is trading off "clone" time now for later "as needed" downloads. It's not clear to me that this is the best tradeoff if it means a user would require network access in order to do a conceptually read-only activity like a build.

Consider saying a little more here so that the reader is equipped to make the tradeoff rather than us dictating it. Maybe something like: "The filter defers large downloads until they are needed; if you want all the source now leave that out."
</blockquote></details>

This fetches the entire head commit (the current revision).  The user can still run a build offline (modulo dependency downloads).

What is not fetched is past revisions, if they were to jump back in time or bisect or etc.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19486)* status: 1 unresolved discussion

___
*[`doc/_pages/from_source.md` line 48 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19486#-NWEfUytDcK-4qhariJn:-NWFS97H6riROMwAOE6l:b7k4pmf) ([raw file](https://github.com/RobotLocomotion/drake/blob/233960bfcbd4d433f18ad157292f11f06f21e4d8/doc/_pages/from_source.md#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This fetches the entire head commit (the current revision).  The user can still run a build offline (modulo dependency downloads).

What is not fetched is past revisions, if they were to jump back in time or bisect or etc.
</blockquote></details>

Oh, that does sound good then! Thanks.

**Pull request merged**
