### PR TITLE
[workspace] Improve qhull hidden visibility

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
When building C++ code, we should not use `-fvisibility=hidden` because it infects all `#include`d code, even the standard library. This causes a lot of console spam during macOS builds, and is a typeinfo (vtable) problem even on Ubuntu, potentially leading to ODR violation. Instead, we should wrap the third-party C++ code in a inline hidden namespace. That way, only the third-party code itself is hidden, not anything that it `#include`s.

We are substantially patching and subsetting this library to weave it into Drake. We shouldn't give the illusion to users that it's available for reuse downstream; therefore, we'll add an "_internal" suffix and deprecate the original repository name.

Towards #17231.

Requires:
- [x] #17278

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17229)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17229#-:-N3WVfOG6XIGxcJjIqRY:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17229)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17229)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/deprecation.bzl` line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17229#-N3_iTNS-XzbZQvPB4TB:-N3_iTNS-XzbZQvPB4TC:bfqgcs) ([raw file](https://github.com/robotlocomotion/drake/blob/0da69b03947cbf52f0b1b524c3f296a94ace50bf/tools/workspace/deprecation.bzl#L13)):*
> ```Starlark
>         " and will be removed from Drake on or after {}.".format(date),
>     ])
>     for label, actual in cc_aliases.items():
> ```

It doesn't look like "actual" is used here.   Does this still create an alias to the library, or just print a deprecation warning?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17229)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

___
*[`tools/workspace/deprecation.bzl` line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17229#-N3_iTNS-XzbZQvPB4TB:-N3_kY0l-37TbPjg6riu:b-7uuaj4) ([raw file](https://github.com/robotlocomotion/drake/blob/0da69b03947cbf52f0b1b524c3f296a94ace50bf/tools/workspace/deprecation.bzl#L13)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It doesn't look like "actual" is used here.   Does this still create an alias to the library, or just print a deprecation warning?
</blockquote></details>

Done.

Good find.  I'd tested with using `@qhull_internal` and `@qhull` both at once (and saw the deprecation) but failed to test just `@qhull` on its own.  Locally I've confirmed that r2 fails that manual test case, and now the change in r3 makes it pass again.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17229)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17229#-:-N3_vziA0-SUjRqp4CLY:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
