### PR TITLE
Remote tree viewer wrapper

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8378)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@gizatt for review please.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-:-L7f6yW8Dc3ufSO0l0TE:b-ptf1ao)*

**Comment by gizatt** [comment]
Pointed out a few things below. But you're welcome to pass on any set of them that you want -- the code overall seems functional enough to be useful to you and others in Drake, as long as you can find a drake-visualizer version that supports it.

Thanks for working on porting this!

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 19 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7fQuKK6U6a-UOhVghE:-L7fQuKK6U6a-UOhVghF:bbct66q) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L19)):*
> ```cpp
> namespace manipulation {
> namespace dev {
> static double getUnixTime(void) {
> ```

BTW Is there a Drake-ier way to do this? I've been carrying around this getUnixTime() function that I copy-paste into my code for years. (It exists as a Spartan common util header, for example.)

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 66 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7fRFRi2gJ9an76VPfU:-L7fRFRi2gJ9an76VPfV:b-322n7f) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L66)):*
> ```cpp
>   msg.format_version_minor = 0;
>   msg.data.clear();
>   for (auto& c : j.dump()) msg.data.push_back(c);
> ```

This seems really wasteful... would 

s = j.dump();
msg.data.copy(s.begin(), s.end())

be any more efficient? Likewise where this appears below.

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 67 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7fRxhTDkke4D1Q_3gw:-L7fRxhTDkke4D1Q_3gx:b-yjzj2m) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L67)):*
> ```cpp
>   msg.data.clear();
>   for (auto& c : j.dump()) msg.data.push_back(c);
>   msg.num_bytes = j.dump().size();
> ```

Calling dump twice is likely pretty wasteful, too.

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 235 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7fSp456NriU8m5gL8v:-L7fSp456NriU8m5gL8w:bqmmhi4) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L235)):*
> ```cpp
>   if (geometry.getShape() == DrakeShapes::MESH_POINTS) {
>     Eigen::Matrix3Xd pts;
>     geometry.getPoints(pts);
> ```

Hmm, should these pts at least be transformed using the supplied tf. And can the color passed through?

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 236 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7fT2WGDoNBeptAprzc:-L7fT2WGDoNBeptAprzd:bbpi7ru) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L236)):*
> ```cpp
>     Eigen::Matrix3Xd pts;
>     geometry.getPoints(pts);
>     PublishPointCloud(pts, path);
> ```

I think PublishGeometry needs to return after this call to PublishPointCloud returns; otherwise it'll falsely claim that it doesn't know how to publish MESH_POINTS.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-:-L7fTFAjDwzHed6cYri4:bolghz9)*

**Comment by hongkai-dai** [comment]
Review status: 9 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7fQuKK6U6a-UOhVghE:-L7fqcBig4knmRg317Td:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L19)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

BTW Is there a Drake-ier way to do this? I've been carrying around this getUnixTime() function that I copy-paste into my code for years. (It exists as a Spartan common util header, for example.)
</blockquote></details>

Done.

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7fRFRi2gJ9an76VPfU:-L7fnMLIj7buO9G4k0KB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L66)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

This seems really wasteful... would 

s = j.dump();
msg.data.copy(s.begin(), s.end())

be any more efficient? Likewise where this appears below.
</blockquote></details>

Done.

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7fRxhTDkke4D1Q_3gw:-L7fnMzeJsSl520Nyqdm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L67)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Calling dump twice is likely pretty wasteful, too.
</blockquote></details>

Done.

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7fSp456NriU8m5gL8v:-L7fqCvrJUYUlLWlIj9Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L235)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Hmm, should these pts at least be transformed using the supplied tf. And can the color passed through?
</blockquote></details>

Done.

---

*[manipulation/dev/remote_tree_viewer_wrapper.cc, line 236 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7fT2WGDoNBeptAprzc:-L7fqGNVqHLHcjaSNQtN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ad39e99012521874006deadaaf1e89356528175/manipulation/dev/remote_tree_viewer_wrapper.cc#L236)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

I think PublishGeometry needs to return after this call to PublishPointCloud returns; otherwise it'll falsely claim that it doesn't know how to publish MESH_POINTS.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378)*

**Comment by gizatt** [comment]
Thanks! :LGTM:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-:-L7gUAILgXyzNmRs2Fwl:b-gc6g6f)*

**Comment by hongkai-dai** [comment]
-@gizatt for review. 

---

Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-:-L7jGdsJypkdENPgAlps:b-gz88ow)*

**Comment by hongkai-dai** [comment]
+@gizatt for platform review please.

---

Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-:-L7jGkZkgrTihd4oZHtC:bnxnixh)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review. Some code in this PR are in the dev folder.

---

Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-:-L7jGtoZ351K-BaILOeA:bmb6ko7)*

**Comment by sherm1** [comment]
Code in dev doesn't require platform review so I'm looking the other way. Everything else :lgtm:, but the non-dev code (like the addition of json) needs to be feature reviewed if @gizatt hasn't already done that.

---

Reviewed 7 of 12 files at r1, 1 of 4 files at r2.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-:-L7jVVDYrSO_RppXCqq4:bqacu3m)*

**Comment by hongkai-dai** [comment]
+@jamiesnape could you feature review the build part, that add `json` to the externals?

---

Review status: 11 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-:-L7jWm6Bnh8zlADDgxKD:bylxkxe)*

**Comment by jamiesnape** [comment]
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---

*[tools/workspace/json/package-create-cps.py, line 22 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7jXFf02Ca22bEpIFH9:-L7jXFf10VmY3QVgVf_6:bhfln55) ([raw file](https://github.com/robotlocomotion/drake/blob/6a8b2c8258d15f1734caaac87aa19c729be61847/tools/workspace/json/package-create-cps.py#L22)):*
> JSON_HEADER_ONLY

I don't see any mention of this in the upstream code.

---

*[tools/workspace/json/package.BUILD.bazel, line 31 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7jXVEM2RWX7UfnQ_Ua:-L7jXVEM2RWX7UfnQ_Ub:b-ixa9aq) ([raw file](https://github.com/robotlocomotion/drake/blob/6a8b2c8258d15f1734caaac87aa19c729be61847/tools/workspace/json/package.BUILD.bazel#L31)):*
> ```
> install_cmake_config(package = CMAKE_PACKAGE)
> 
> install(
> ```

As it stands this is not used in a public header, so we could skip creating the CPS and installing anything but the license.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378)*

**Comment by hongkai-dai** [comment]
Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/json/package-create-cps.py, line 22 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7jXFf02Ca22bEpIFH9:-L7jkMuj6TsWAELczy42:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a8b2c8258d15f1734caaac87aa19c729be61847/tools/workspace/json/package-create-cps.py#L22)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> JSON_HEADER_ONLY

I don't see any mention of this in the upstream code.

</blockquote></details>

Done.

---

*[tools/workspace/json/package.BUILD.bazel, line 31 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7jXVEM2RWX7UfnQ_Ua:-L7jpaxXd6XUk-VkojYg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a8b2c8258d15f1734caaac87aa19c729be61847/tools/workspace/json/package.BUILD.bazel#L31)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

As it stands this is not used in a public header, so we could skip creating the CPS and installing anything but the license.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378)*

**Comment by jamiesnape** [comment]
Reviewed 7 of 12 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/workspace/json/BUILD.bazel, line 8 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7jrg766gpOU_sqgU1Y:-L7jrg766gpOU_sqgU1Z:b-p6qp4f) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/BUILD.bazel#L8)):*
> ```Python
>     ["package-create-cps.py"],
>     visibility = ["@json//:__pkg__"],
> )
> ```

Delete block.

---

*[tools/workspace/json/package-create-cps.py, line 1 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7jr_7a9suLg2NFBuHl:-L7jr_7a9suLg2NFBuHm:b-5c2w2m) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package-create-cps.py#L1)):*
> ```Python
> #!/usr/bin/env python2
> ```

Delete file.

---

*[tools/workspace/json/package.BUILD.bazel, line 5 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7jrL-t1Dr3WO_A39pq:-L7jrL-t1Dr3WO_A39pr:b-58s312) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package.BUILD.bazel#L5)):*
> ```
> load(
>     "@drake//tools/install:install.bzl",
>     "cmake_config",
> ```

Delete line.

---

*[tools/workspace/json/package.BUILD.bazel, line 7 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7jrMqg3huM9rGtDmCi:-L7jrMqg3huM9rGtDmCj:b-58s312) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package.BUILD.bazel#L7)):*
> ```
>     "cmake_config",
>     "install",
>     "install_cmake_config",
> ```

Delete line.

---

*[tools/workspace/json/package.BUILD.bazel, line 26 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7jrTY76A4CgTAaUBNr:-L7jrTY76A4CgTAaUBNs:b-p6qp4f) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package.BUILD.bazel#L26)):*
> ```
>     script = "@drake//tools/workspace/json:package-create-cps.py",
>     version_file = "single_include/nlohmann/json.hpp",
> )
> ```

Delete block.

---

*[tools/workspace/json/package.BUILD.bazel, line 29 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378#-L7jrOmIADkMv-vr532Q:-L7jrOmIADkMv-vr532R:b-p6qp4f) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package.BUILD.bazel#L29)):*
> ```
> 
> # Creates rule :install_cmake_config.
> install_cmake_config(package = CMAKE_PACKAGE)
> ```

Delete block.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8378)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r5.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378)*

**Comment by hongkai-dai** [comment]
Review status: 10 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[tools/workspace/json/BUILD.bazel, line 8 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7jrg766gpOU_sqgU1Y:-L7jxB6bxCx2rG5x8uJt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/BUILD.bazel#L8)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Delete block.
</blockquote></details>

Done.

---

*[tools/workspace/json/package.BUILD.bazel, line 5 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7jrL-t1Dr3WO_A39pq:-L7jxb3X3TPbM45D4P5S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package.BUILD.bazel#L5)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Delete line.
</blockquote></details>

Done.

---

*[tools/workspace/json/package.BUILD.bazel, line 7 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7jrMqg3huM9rGtDmCi:-L7jxbXLVmhN2JFeCRT4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package.BUILD.bazel#L7)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Delete line.
</blockquote></details>

Done.

---

*[tools/workspace/json/package.BUILD.bazel, line 26 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7jrTY76A4CgTAaUBNr:-L7jxc9o4iGBuJR5o08M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package.BUILD.bazel#L26)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Delete block.
</blockquote></details>

Done.

---

*[tools/workspace/json/package.BUILD.bazel, line 29 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7jrOmIADkMv-vr532Q:-L7jxck0iADlosiJ1JTi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package.BUILD.bazel#L29)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Delete block.
</blockquote></details>

Done.

---

*[tools/workspace/json/package-create-cps.py, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-L7jr_7a9suLg2NFBuHl:-L7jxAGDtSlpuLCCsg7W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a00df2e835adbb3ac5f69f81fc61cbd3df4ca69/tools/workspace/json/package-create-cps.py#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Delete file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8378#-:-L7jy-nfjujz9V23NHCa:bnfp4nl)*

**Pull request merged**
