### PR TITLE
pydrake: Readdress inconsistent storage duration btw g++ and clang

### LINKED ISSUE #9600: pydrake doc: gcc and clang disagree on need for lambda capture for `constexpr` vars
From here: https://github.com/RobotLocomotion/drake/pull/9571#issuecomment-426708850

Workarounds:
- Use `constexpr auto& doc`, rather than `auto& doc`
- Use `[&]` in lambda capture
- Add `copts = ["-Wno-unused-lambda-capture"]` for `pybind_py_library`

Action items:
- [x] Use a workaround in relevant sites (searching for `doc_lambda`)
- [x] Find or file upstream bug report:
   - clang: https://bugs.llvm.org/show_bug.cgi?id=39202
   - gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87559

\cc @m-chaturvedi @jamiesnape

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Closes #9600.
(Again)

\cc @jamiesnape 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9630)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
We missed `primitives_py.cc` and we can add a temporary fix to `framework_py_semantics.cc` by not capturing `[&]` but just `[m]` and using `pydrake_doc` inside the lambda, IIRC it was building on Bionic.  It's a but in GCC, I'll try to reproduce it with a small example and report it.

**Comment by EricCousineau-TRI** [comment]
Per Jeremy's suggestion, will briefly use `-Wno-unused-lambda-capture`, and see if passing it in works. (I like nested scope.)
If that fails, then yeah, I'll go with repetitive `pydrake_doc.*` approach.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 262 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9630#-LOPVxb71avZhsVF5lTW:-LOPVxb8634Iy2DYsQag:b-suv37h) ([raw file](https://github.com/robotlocomotion/drake/blob/cd4273f0d4e17bb5e0cd4badb09a9eea3000a92b/bindings/pydrake/multibody/rigid_body_tree_py.cc#L262)):*
> ```cpp
>   // Methods of type (b) are declared below methods of type (a).
>   // N.B. Capturing `&doc` should not be required; workaround per #9600.
>   auto add_rigid_body_tree_typed_methods = [m, &tree_cls, &doc](auto dummy) {
> ```

Alphabetize?

**Comment by m-chaturvedi** [comment]
[BTW, `s/re-address/readdress/` ?](https://en.oxforddictionaries.com/definition/readdress) [Sorry for the delay.]

**Comment by EricCousineau-TRI** [comment]
Done.

**Pull request merged**
