### PR TITLE
Switches to VTK submodule to upstream server and adds injection GLX_GLXEXT_LEGACY flag.

### PR DESCRIPTION
**Pull request by liangfok**
Forward-fixes a defect introduced in #4901.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4922)

### CODE REVIEW

**Comment by liangfok** [comment]
I tested this on an Ubuntu 16.04 machine with ROS Kinetic (and VTK6) installed. 

+@mwoehlke-kitware for feature review please.
+@jwnimmer-tri for platform review please.

Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4922#-:-KbRImHqUW76Xpxab4WR:b-mztjii)*

**Comment by liangfok** [comment]
Oh wait. A subsequent test failed. Let me look into the failure some more. I'm going to label this "do not review" in the mean time.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4922#-:-KbRJde6kURh-qgfiv6p:bq99d0s)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4922)*

**Comment by liangfok** [comment]
@mwoehlke-kitware: Help! I wasn't able to get this to work. Can you take a look?

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4922#-:-KbRWIClEz7qKufV2YCt:b-r0xk06)*

**Comment by jwnimmer-tri** [comment]
My guess is  `-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -DGLX_GLXEXT_LEGACY=1"` but will defer to Matthew when he can look at it.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4922#-:-KbRa9HJ_ZUB62IFgLJV:bp6jbed)*

**Comment by liangfok** [comment]
@jwnimmer-tri: Thanks for the suggestion. Here's the error I encounter when I try adding the double-quotes:

```
c++: error:  -DGLX_GLXEXT_LEGACY=1: No such file or directory
Utilities/kwsys/CMakeFiles/vtksys.dir/build.make:158: recipe for target 'Utilities/kwsys/CMakeFiles/vtksys.dir/Directory.cxx.o' failed
make[5]: *** [Utilities/kwsys/CMakeFiles/vtksys.dir/Directory.cxx.o] Error 1
CMakeFiles/Makefile2:305: recipe for target 'Utilities/kwsys/CMakeFiles/vtksys.dir/all' failed
make[4]: *** [Utilities/kwsys/CMakeFiles/vtksys.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/vtk.dir/build.make:111: recipe for target 'vtk-prefix/src/vtk-stamp/vtk-build' failed
make[2]: *** [vtk-prefix/src/vtk-stamp/vtk-build] Error 2
CMakeFiles/Makefile2:5658: recipe for target 'CMakeFiles/vtk.dir/all' failed
make[1]: *** [CMakeFiles/vtk.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4922#-:-KbRgUvpXzu4AE1w82tu:bc88tj5)*

**Comment by mwoehlke-kitware** [comment]
> My guess is `-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -DGLX_GLXEXT_LEGACY=1"`

Quotes should go around the whole thing:

```cmake
"-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DGLX_GLXEXT_LEGACY=1"
```

(I think I mentioned that on slack...)

Shell is a little odd allowing you to stick quotes in the middle of a token.

**Comment by liangfok** [comment]
Thanks. I just updated this PR with the suggested changes. Testing locally now.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4922#-:-KbRgv0M28r5cF9raje4:b-g6hxtv)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4922#-:-KbS-_ScpJG_7yZurMvW:bnfp4nl)*

**Comment by liangfok** [comment]
Oops! I just realized I pushed to the wrong remote. I'll close this issue and open a new one with the correct remote.

**Pull request closed without merging**
