### PR TITLE
Bumped test numbers for iris_from_clique_cover_test to prevent timeout on nightly build 

### PR DESCRIPTION
**Pull request by wernerpe**
see title

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21128)

### CODE REVIEW

**Review by wernerpe — COMMENTED** [review]
I set this up so I can double check that CI goes through smoothly.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21128#-:-NsnI5jy9rqzNQkhyqYW:b-scl00o)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @wernerpe)

**Review by wernerpe — COMMENTED** [review]
+@AlexandreAmice 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21128#-:-NsnJBry4HFA8v3LJYZD:bvkq9hv)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @wernerpe)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-everything-debug please

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

cc @BetsyMcPhail @svenevs for build cop. 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21128#-:-NsnNqBB0zW-dWTjDt3g:b-sxt7jf)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @wernerpe)

**Pull request merged**
