### PR TITLE
Moved ros_test into drake/ros since this is where all ROS-related cod…

### PR DESCRIPTION
**Pull request by liangfok**
…e will be located.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2509)

### CODE REVIEW

**Comment by liangfok** [comment]
Since tomorrow is Monday and this PR contains a relatively small change, +@sherm1 for both levels of review please.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Moved ros\_test into drake/ros since this is where all ROS\-related cod…
> 
> …e will be located.
> 
> 
> 
</details>


---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2509#-:-KJYSPGvs1ymBNjx5vFw:2132485738)*

**Comment by sherm1** [comment]
Feature review :lgtm:. Waiting for CI.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Since tomorrow is Monday and this PR contains a relatively small change, +@sherm1 for both levels of review please.
</details>


---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/ros/CMakeLists.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2509#-KJYVw4Tsp2C2ATzZd-t:-KJYVw4Tsp2C2ATzZd-u:1687216346) ([raw file](https://github.com/robotlocomotion/drake/blob/312594fc5f1b96bcb3ab4ab582987e6f24dbeceb/drake/ros/CMakeLists.txt#L1)):*
> ```CMake
> add_subdirectory(test)
> ```

missing newline at eof

---

*[drake/ros/test/CMakeLists.txt, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2509#-KJYVyM_B7yYdOZOVGUa:-KJYVyM_B7yYdOZOVGUb:1687216346) ([raw file](https://github.com/robotlocomotion/drake/blob/312594fc5f1b96bcb3ab4ab582987e6f24dbeceb/drake/ros/test/CMakeLists.txt#L5)):*
> ```CMake
>   target_link_libraries(ros_test ${GTEST_BOTH_LIBRARIES} ${roscpp_LIBRARIES})
>   add_test(NAME ros_test COMMAND ros_test)
> endif()
> ```

missing newline at eof

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2509#-:-KJYW5T7D49Ykr-xPgou:1973634247)*

**Comment by liangfok** [comment]
Added the missing newlines. Thanks for the review.

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Feature review :lgtm:. Waiting for CI.
</details>


---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/ros/CMakeLists.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2509#-KJYVw4Tsp2C2ATzZd-t:-KJYa8sSwSzvKNDWXzMe:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/312594fc5f1b96bcb3ab4ab582987e6f24dbeceb/drake/ros/CMakeLists.txt#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> missing newline at eof
</details>
Done.

---

*[drake/ros/test/CMakeLists.txt, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2509#-KJYVyM_B7yYdOZOVGUa:-KJYaA7pRpCtR9vKKtu5:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/312594fc5f1b96bcb3ab4ab582987e6f24dbeceb/drake/ros/test/CMakeLists.txt#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> missing newline at eof
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2509#-:-KJYaKrJldLPpAD5ts_Z:-995759368)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2509)*

**Comment by jwnimmer-tri** [comment]
In that build 38 log, I see:
> 01:38:04 FAILED: download-snopt-precompiled-prefix/src/download-snopt-precompiled-stamp/download-snopt-precompiled-download

**Comment by liangfok** [comment]
@jwnimmer-tri: Thanks!

I also notice that [windows-msvc-64-experimental-matlab-open-source/2](https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-64-experimental-matlab-open-source/2/) succeeded. Thus, I don't think this PR caused the failures in CI.

**Pull request merged**
