### PR TITLE
Remove unused code from mkdoc.py

### PR DESCRIPTION
**Pull request by m-chaturvedi**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12818)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot drake-external-examples please.

**Comment by jamiesnape** [comment]
Hold on this in case we need to revert #12040.

**Comment by jamiesnape** [comment]
Closes #12818.

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm: platform (having looked at this earlier today).

**Pull request merged**
