### PR TITLE
Update libibex-dev version in Linux install script

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8024)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature and platform review.

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please

**Comment by soonho-tri** [comment]
:lgtm:

Tested the following on my local Ubuntu-16.04 after upgrading `libibex-dev`.
```
bazel test //solvers:dreal_solver_test --compilation_mode=dbg  --config=asan_everything --keep_going
```

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8024#-:-L4wb4rV3Zu-gqCAHbxV:b-ifz93d)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by soonho-tri** [comment]
BTW, `-memcheck-lsan` tests are only meaningful when CI image is already updated. Is it the case?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8024#-:-L4wdxz1A5bvnvfZcwzi:b-360etn)*

**Comment by jamiesnape** [comment]
Yes.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8024#-:-L4weAu299sq9-6tDfit:bb77ufg)*

**Comment by soonho-tri** [comment]
Thanks!!!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8024#-:-L4weWANVXQdRbXxMqks:bvtka37)*

**Comment by soonho-tri** [comment]
CI All passed including
 - https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-memcheck-asan/24/

**Pull request merged**
