### PR TITLE
refactor PendulumSystem to PendulumPlant.  Use mathjax for doxygen

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3950)

### CODE REVIEW

**Comment by RussTedrake** [comment]
this is a simple refactor
+@hongkai-dai for feature review, +@sammy-tri for platform review

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3950#-:-KVFo4D3y5OW4HQ-_FZB:b9icy1s)*

**Comment by hongkai-dai** [comment]
:lgtm: except for on minor comment.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/pendulum_plant.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3950#-KVII1VbaaWY6ZdQxK_P:-KVII1VbaaWY6ZdQxK_Q:brxzhi8) ([raw file](https://github.com/robotlocomotion/drake/blob/705abbffe0976b00c0b24c0afa788649d523a588/drake/examples/Pendulum/pendulum_plant.h#L15)):*
> ```objc
> 
> /// A model of a simple pendulum
> /// @f[ ml^2 \ddot\theta + b\dot\theta + mgl\sin\theta = u @f]
> ```

May I suggest to also add the human readable formulation, in addition to the latex formulation? Probably we can add
```
<!-- m*l*l*theta_ddot + b*theta_dot + m*g*l*sin(theta) = u -->
```
The doxygen will not parse it as it is inside the `<!-- -->` tag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3950#-:-KVIJHeDtIOQCgQb6AYq:bmo0jak)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/pendulum_plant.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3950#-KVII1VbaaWY6ZdQxK_P:-KVIK6jaxab62ZcseJF6:b50fanw) ([raw file](https://github.com/robotlocomotion/drake/blob/705abbffe0976b00c0b24c0afa788649d523a588/drake/examples/Pendulum/pendulum_plant.h#L15)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> May I suggest to also add the human readable formulation, in addition to the latex formulation? Probably we can add
> ```
> 
> ```
> The doxygen will not parse it as it is inside the `<!-- -->` tag.
</details>
maybe i've spent too many years w/ latex, but that is less readable to me..?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3950)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/pendulum_plant.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3950#-KVII1VbaaWY6ZdQxK_P:-KVIKcxPhaQ8IWm_QUWi:b-jgb2ey) ([raw file](https://github.com/robotlocomotion/drake/blob/705abbffe0976b00c0b24c0afa788649d523a588/drake/examples/Pendulum/pendulum_plant.h#L15)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> maybe i've spent too many years w/ latex, but that is less readable to me..?
</details>
I guess until the developers reach a consensus on how we should document our code, I am OK with either way. Mark as resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3950)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3950#-:-KVQ6RXlVJzDeBIEWcGW:bnfp4nl)*

**Pull request merged**
