### PR TITLE
[py common] Fix GIL hazard in WrapDeprecated

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22195)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  +@rpoyner-tri for platform review (tomorrow, per schedule)

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22195#-:-OC-8C-8-7oYPIOVkp6e:b-n8a7gr)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22195)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22195#-:-OC4fYep-iz7U5K7Pr5J:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform)

**Pull request merged**
