### PR TITLE
Update pycps to quote INTERFACE_LINK_LIBRARIES property value

### PR DESCRIPTION
**Pull request by fbudin69500**
This update is required to build spartan when drake uses bazel.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6359)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
:lgtm:

I guess it would be helpful to have a basic unit test for `drake-config.cmake`...

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6359#-:-Kmm9ADM6sd56uD9ZeUt:b-dr9coc)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Comment by jwnimmer-tri** [comment]
Ready to merge except for @jamiesnape approval.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6359#-:-KmmM_vEFJGv-o-bnBg4:bnfp4nl)*

**Pull request merged**
