### PR TITLE
PathEnergyCost for GCSTrajectoryOptimization

### PR DESCRIPTION
**Pull request by rohanb-sony**
Creates AddPathEnergyCost() for GcsTrajectoryOptimization. Path energy cost is equivalent to the L2 squared distance between control points. Benefits of path energy cost include more even spacing between control points and faster solve times. The potential downside is that control points may visit additional regions.
Included with the AddPathEnergyCost are two unit tests. The first test, "QuadPathLengthCost," ensures that the cost has been properly constructed. The path spacing unit test determines that in a simple GCS Trajectory optimization problem the control points are evenly spaced.
Moreover, python bindings have been included.

(re-opening)

@sadraddini

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810)

### CODE REVIEW

**Comment by sadraddini** [comment]
+@sadraddini for feature

**Comment by rohbws** [comment]
@drake-jenkins-bot ok to test

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810)* status: 2 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rohanb-sony)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 400 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21810#-O4WCNRgDPPX2nIEJQfu:-O4WCNRhBSJRWcGfhlTL:b-1uibud) ([raw file](https://github.com/RobotLocomotion/drake/blob/ec724d00430bfa23e4ce2a6ae2bd1af033bc01a6/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L400)):*
> ```cpp
>   const auto path_squared_cost = std::make_shared<QuadraticCost>(Q, b);
> 
>   for (Vertex* v : vertices_) {
> ```

nit `const Vertex*`
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 417 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21810#-O4WC_3FBrygmuL-PlK3:-O4WC_3FBrygmuL-PlK4:b-v0tsbx) ([raw file](https://github.com/RobotLocomotion/drake/blob/ec724d00430bfa23e4ce2a6ae2bd1af033bc01a6/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L417)):*
> ```cpp
> 
> void Subgraph::AddPathEnergyCost(double weight) {
>   const MatrixXd weight_matrix =
> ```

nit Can you add a comment why 2 is here. A small explanation of the math would help.

**Review by sadraddini — COMMENTED** [review]
:lgtm: small comments - this was reviewed and closed in https://github.com/RobotLocomotion/drake/pull/21758 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810#-:-O4WDh1j73Rjx-3StOK6:b-wzo3c6)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rohanb-sony)

**Comment by rohanb-sony** [comment]
> nit `const Vertex*`

This is not possible. AddCost is called on each vertex and AddCost is a non const function. Moreover, const is not used in AddPathLengthCost.

> nit Can you add a comment why 2 is here. A small explanation of the math would help.

Fixed!

**Comment by RussTedrake** [comment]
BTW -- this is related to [#19308](https://github.com/RobotLocomotion/drake/issues/19308) -- in fact it's the last remaining TODO on that issue.  cc @wrangelvid 

+@jwnimmer-tri for platform review, please.

**Review by rpoyner-tri — COMMENTED** [review]
-@jwnimmer-tri +@rpoyner-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810#-:-O4fA39pEx50ZiPbBrOE:bqf6gr5)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rohanb-sony)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rohanb-sony)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 1424 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21810#-O4fIlaADFEF_v6GO39s:-O4fIlaADFEF_v6GO39t:b-29ol9y) ([raw file](https://github.com/RobotLocomotion/drake/blob/73759fc764951a6e57de46a119a97d3ca339bc8d/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1424)):*
> ```cpp
> 
>   if (order > 0) {
>     /// These costs and constraints rely on the derivative of the trajectory.
> ```

nit A three-slash comment is out of place here. Doxygen will never see it.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: contingent on open discussions

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810#-:-O4fJ2H_7LwSmjcX_FUO:b7rpns0)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rohanb-sony)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rohanb-sony)

**Comment by rohanb-sony** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810)_ status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rohanb-sony)
> 
> _[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 1424 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21810#-O4fIlaADFEF_v6GO39s:-O4fIlaADFEF_v6GO39t:b-29ol9y) ([raw file](https://github.com/RobotLocomotion/drake/blob/73759fc764951a6e57de46a119a97d3ca339bc8d/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1424)):_
> 
> > ```c++
> >   if (order > 0) {
> >     /// These costs and constraints rely on the derivative of the trajectory.
> > ```
> 
> nit A three-slash comment is out of place here. Doxygen will never see it.

Fixed!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rohanb-sony)

**Comment by rohanb-sony** [comment]
+release notes: feature

**Comment by rohanb-sony** [comment]
+label release notes: feature

**Comment by rohanb-sony** [comment]
+release notes: feature

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21810)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rohanb-sony)

**Comment by SeanCurtis-TRI** [comment]
@sadraddini For future reference, when you squash the commit for merging, you'll want to [clean up the commit message](https://github.com/RobotLocomotion/drake/commit/c9860cc08b6385876b5020d0bdd31a2b0f0422d9) to avoid committing all of the unhelpful history. The Reviewable interface makes it very easy; let me know if you're unsure how to do that.

**Pull request merged**
