### PR TITLE
Rip out drake/matlab/util from the drake/util directory

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A second portion of #3253.  Further commits in the PR train can be seen [here](https://github.com/jwnimmer-tri/drake/tree/the-great-matlab-relocation-of-aught-sixteen).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3832)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This PR relates to #3278 in that everything that remains in `drake/util` after this is a target for relocation per that issue.

**Comment by jwnimmer-tri** [comment]
For reference, the list of `util` and `matlab/util` files as a result of this PR:
https://gist.github.com/jwnimmer-tri/73c4d17e05aa7876f791f44f52448daf

**Comment by jamiesnape** [comment]
Any chance this can merge after #3681?

**Comment by jwnimmer-tri** [comment]
@jamiesnape probably.

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for both reviews, please.  Note that _the commits are sensibly staged_ so perhaps that will guide you.  It's going to be a pain to review no matter what.

**Comment by david-german-tri** [comment]
I'm going to work with @jamiesnape to get #3681 merged first, then review this by patch-and-manual-test.  I think it's impractical to actually look at every file.

---

Review status: 0 of 461 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3832#-:-KUNpqwNO1-ws4m2TQKw:bhcnzq7)*

**Comment by jwnimmer-tri** [comment]
I can also help figure out how to slice and review to get usefull eyeballs on the juicy bits.

**Comment by jwnimmer-tri** [comment]
Okay, since I'm going to rebase anyway for 3681, I'll plan to close this PR and open anew.  For now, I'm going to play with reviewable a bit to prep for the next PR.

**Pull request closed without merging**
