### PR TITLE
third_party: Import dracula, github-styling, and pylons

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #14657
In parallel with #14614

\cc @IanTheEngineer @ggould-tri 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jamiesnape and +@jwnimmer-tri for review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662#-:-MTlIr22BbBdIy6ZQYmo:btw85db)* status: LGTM missing from assignees jamiesnape,jwnimmer-tri(platform) (waiting on @jamiesnape and @jwnimmer-tri)

**Review by jamiesnape — COMMENTED** [review]
:lgtm: Licenses are fine. Attribution is above and beyond. The code seems reasonable. Difficult to say too much more without the rest of the site. Hopefully the CSS is going to be minified, but that is not for this PR.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662#-:-MTld4SiAanAcgHZXRw7:b1cri0l)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/third_party/pylons/pylons.css, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTlbXBWCuk_q8H-fA-4:-MTlbXBWCuk_q8H-fA-5:b9nzqqd) ([raw file](https://github.com/robotlocomotion/drake/blob/2fbfb3de994933f596b9555c9b2aa91d80dd57dc/doc/third_party/pylons/pylons.css#L5)):*
> ```CSS
> 
> Modifications:
> - 2021-02-17: Modified colors, margin, and updated background path.
> ```

Ideally we need an author name or initials (who is the "you" who caused the modification). Source control may be sufficient, but I can't tell from this.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jamiesnape and @jwnimmer-tri)

___
*[doc/third_party/pylons/pylons.css, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTlbXBWCuk_q8H-fA-4:-MTleavg1HZnLCiTicLk:b-rmwanq) ([raw file](https://github.com/robotlocomotion/drake/blob/2fbfb3de994933f596b9555c9b2aa91d80dd57dc/doc/third_party/pylons/pylons.css#L5)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Ideally we need an author name or initials (who is the "you" who caused the modification). Source control may be sufficient, but I can't tell from this.
</blockquote></details>

Done. Added name.

**Review by jamiesnape — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662#-:-MTm2HavBjxyl6FhYtfK:bnfp4nl)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTm1J4o92sR7z2CZd4M:-MTm1J4p4WcbmjW9AjiD:bpq0r67) (no related file):*
nit In the #14657 checklist, be sure to add an tickybox that we need to deploy these LICENSE files onto the production website, somehow.

---
___
*[doc/third_party/pylons/README.md, line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTm1vRlA_9WFRn9jF_T:-MTm1vRlA_9WFRn9jF_U:b-52gbtg) ([raw file](https://github.com/robotlocomotion/drake/blob/8516fade8c55257d183c3c0bdac82e6fe327e2d1/doc/third_party/pylons/README.md#L9)):*
> ```Markdown
> * `dialg-warning.png`
> * `dialog-note.png`
> * `pylons.css` - derived from `pylons_sphinx_themes/pylons/assets/pylons.css_t`
> ```

nit At that git hash at least, the folder is named "static" not "assets".

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTm1J4o92sR7z2CZd4M:-MTm9_7992iG64E4xNZW:b-f407pl) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit In the #14657 checklist, be sure to add an tickybox that we need to deploy these LICENSE files onto the production website, somehow.
</blockquote></details>

If the CSS is minified and concatenated, then we would not usually need too. Same with JavaScript. It is considered the same as compiled code. Images remain copyrighted whether or not the license is there.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI and @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTm1J4o92sR7z2CZd4M:-MTmBLDY43SBxZ3kKTZA:b-typ92w) (no related file):*
Ah, indeed only 1 of the 3 licenses is relevant for the compiled code.

From the pylons license:
> ```
> 2.  Redistributions in binary form must reproduce the accompanying
>     copyright notice, this list of conditions, and the following
> ```

---

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTm1J4o92sR7z2CZd4M:-MTmHFasD_YAGqZOuJ2b:b-8h52m9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, indeed only 1 of the 3 licenses is relevant for the compiled code.

From the pylons license:
> ```
> 2.  Redistributions in binary form must reproduce the accompanying
>     copyright notice, this list of conditions, and the following
> ```

</blockquote></details>

Aside, possibly relevant somewhere in this website: For instances when you need a license in minified JS or CSS, you use a `/*!` comment, which instructs the minifier to leave the text in place (it usually eats regular comments).

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTmMpaM3CamkKoZ_uTa:-MTmMpaO1cmbuw7u5LUS:bzas1jl) (no related file):*
nit Typo in commit message "github-sytling".

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTm1J4o92sR7z2CZd4M:-MTmbyYw5E9DBHSJftJT:b-7c1lt5) (no related file):*
OK Added checkbox in that PR:
> 

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),jamiesnape (waiting on @jamiesnape and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTmMpaM3CamkKoZ_uTa:-MTmcPbh26j48ibAkU7c:bxi94px) (no related file):*
Done. And oops!
> 

---
___
*[doc/third_party/pylons/README.md, line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14662#-MTm1vRlA_9WFRn9jF_T:-MTmcVJWALLkbzNq5BZt:bs6yzbj) ([raw file](https://github.com/robotlocomotion/drake/blob/8516fade8c55257d183c3c0bdac82e6fe327e2d1/doc/third_party/pylons/README.md#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit At that git hash at least, the folder is named "static" not "assets".
</blockquote></details>

Done. (Had too aggressive of a find/replace)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14662)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),jamiesnape

**Comment by EricCousineau-TRI** [comment]
Skipping remaining builds

**Pull request merged**
