### PR TITLE
Add /usr/local/include to Bazel header path during CMake builds

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #7403.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7404)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature and platform review

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-elcapitan-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7404#-:-Ky2IsfhhcVlMhRTXw8Q:bnfp4nl)*

**Comment by soonho-tri** [comment]
I'm checking the CI failures.

**Comment by soonho-tri** [comment]
```
ERROR: /Users/elcapitan/workspace/mac-elcapitan-clang-cmake-experimental/_bazel_elcapitan/810ffaf1ef096e9b06e7632a6b122d22/external/protobuf/BUILD:113:1: Couldn't build file external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/util/internal/utility.pic.o: C++ compilation of rule '@protobuf//:protobuf' failed (Exit 1).
external/protobuf/src/google/protobuf/util/internal/utility.cc:327:1: error: no template named 'set'; did you mean 'std::set'?
set<string>* well_known_types_ = NULL;
^~~
std::set

```

The error message in CI seems legitimate. The version that we're using is at https://github.com/google/protobuf/blob/a428e42072765993ff674fda72863c9f1aa2d268/src/google/protobuf/util/internal/utility.cc#L327 which does not have `std::` in the line.

```c++
set<string>* well_known_types_ = NULL;
```


I'm wondering how it is compiled with other configurations.

**Comment by soonho-tri** [comment]
I guess this problem will be resolved with https://github.com/RobotLocomotion/drake/pull/7323?

**Comment by jamiesnape** [comment]
Yes, though still puzzling.

**Comment by nuclearsandwich** [comment]
Since the pull request which introduced the yaml-cpp build changes this addresses (https://github.com/RobotLocomotion/drake/pull/7352) was reverted in https://github.com/RobotLocomotion/drake/pull/7403 should I open a new pull request re-introducing the changes? Should it block in this pull request or incorporate this pull request?

**Comment by jamiesnape** [comment]
This is not entirely the answer to the problem, it seems, due to protobuf issues.

**Pull request closed without merging**
