### PR TITLE
Fix an asan bug in CspaceFreePolytope.

### PR DESCRIPTION
**Pull request by hongkai-dai**
When finding the separating planes in parallel, the lambda function that actually solves the sos should return plane_count.

Resolves #19843

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19845)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review.
+(release notes: none) 
Platform :lgtm: pending CI. 
+(priority: high) 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19845#-:-NaD8fVk5e8phljIyTR0:b-hia5eo)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/optimization/cspace_free_polytope_base.cc` line 295 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19845#-NaD6pDi7pM4a42Pdntd:-NaD6pDi7pM4a42Pdnte:b-l6hw3m) ([raw file](https://github.com/RobotLocomotion/drake/blob/01a2823ffbf9dced3be2a985cc39feb10a79b24c/geometry/optimization/cspace_free_polytope_base.cc#L295)):*
> ```cpp
>         // This call to future.get() is necessary to propagate any exception
>         // thrown during SOS setup/solve.
>         const auto [sos_success, plane_count] = operation->get();
> ```

BTW, from the usage here, it seems like the semantic is closer to a index/identifier for the planes instead of the number/count of planes.



_Suggestion:_
```cpp
plane_index
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19845)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/optimization/cspace_free_polytope_base.cc` line 295 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19845#-NaD6pDi7pM4a42Pdntd:-NaDAMit3TR1eKL4NRUD:b-m6p3pd) ([raw file](https://github.com/RobotLocomotion/drake/blob/01a2823ffbf9dced3be2a985cc39feb10a79b24c/geometry/optimization/cspace_free_polytope_base.cc#L295)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, from the usage here, it seems like the semantic is closer to a index/identifier for the planes instead of the number/count of planes.
</blockquote></details>

We actually have `plane_index` variable, and it means a different thing.

For every pair of geometries in the SceneGraph, we assign a plane to separate that pair of geometries, and we given an index of the plane, we use `plane_index` for this index.

Inside this function, we don't need to find the separating planes for all pairs of geometries. Instead we only find the planes whose index is in `active_plane_indices`. And we use `plane_count` as the counting variable to loop through `active_plane_indices`.  So we want to find the plane with the index `active_plane_indices[plane_count]`, and then we record whether the plane is found or not in `is_success[plane_count]`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19845)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/optimization/cspace_free_polytope_base.cc` line 295 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19845#-NaD6pDi7pM4a42Pdntd:-NaDBkVe6D9Uig18lFz4:b-uqzml2) ([raw file](https://github.com/RobotLocomotion/drake/blob/01a2823ffbf9dced3be2a985cc39feb10a79b24c/geometry/optimization/cspace_free_polytope_base.cc#L295)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We actually have `plane_index` variable, and it means a different thing.

For every pair of geometries in the SceneGraph, we assign a plane to separate that pair of geometries, and we given an index of the plane, we use `plane_index` for this index.

Inside this function, we don't need to find the separating planes for all pairs of geometries. Instead we only find the planes whose index is in `active_plane_indices`. And we use `plane_count` as the counting variable to loop through `active_plane_indices`.  So we want to find the plane with the index `active_plane_indices[plane_count]`, and then we record whether the plane is found or not in `is_success[plane_count]`. 
</blockquote></details>

I added some documentation, is it more clear now?

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19845)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/optimization/cspace_free_polytope_base.cc` line 295 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19845#-NaD6pDi7pM4a42Pdntd:-NaDUJUkB5iT1ZUJjAcj:br06oxi) ([raw file](https://github.com/RobotLocomotion/drake/blob/01a2823ffbf9dced3be2a985cc39feb10a79b24c/geometry/optimization/cspace_free_polytope_base.cc#L295)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I added some documentation, is it more clear now?
</blockquote></details>

Looks good, thanks!

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19845#-:-NaDUaes96j0NugYrReJ:b3dcro0)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

**Pull request merged**
