### PR TITLE
[common] Add hash_append support for bare pointers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19243.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19248)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI 

:LGTM:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19248#-:-NTnc0qi6WrueDIU5BPN:by1gkon)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/hash.h` line 150 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19248#-NTncdQ_0oueJ7GlwPRN:-NTncdQ_0oueJ7GlwPRO:bq2zgrg) ([raw file](https://github.com/RobotLocomotion/drake/blob/89082176a9b31a937e510bdcecf83ee3059ad01b/common/hash.h#L150)):*
> ```objc
> ///
> /// Note that there is no `hash_append` overload for `std::unordered_map`, and
> /// such an overload must never appear.  See n3980.html#unordered for details.
> ```

BTW Several things:

1. My first thought as I saw this was that this truncated URL wasn't particularly helpful. Looking outside the scope of this PR I recognized that the full URL is given in the group documentation. That said, is it clear that the full URL is available in the "hash_append" link in the summary?
2. Looking at the doxygen for the current state of `hash.h`, the pre-existing instances of `n3890.html#unordered` is getting rendered as `n3890.html::unordered`; hash swapped for double colon.
3. This style of specifying `page.html#anchor` is not used consistently throughout this file. For example, the `hash_append` implementation for `std::basic_string` says, "See the `#hash_append_vector` anchor in N3980."

(All of this with the caveat that I recognize that this is just moved code...all of these defects -- such as they are -- predate this PR.)



_Code quote:_
```objc
n3980.html#unordered
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19248#-:-NTnnYKO0vpH10te2aVF:b4mx0my)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; one standards-lawyer inquiry.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19248#-:-NTo0J8wEaBc1H_34ixA:buf0zrw)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`common/hash.h` line 152 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19248#-NTnxdtb6zPzpPalzxi6:-NTnxdtb6zPzpPalzxi7:b-f05oin) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c4075d36fe845e73c3295f86c92f58e7259c44d/common/hash.h#L152)):*
> ```objc
> /// such an overload must never appear.  See
> /// [N3980](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3980.html#unordered)
> /// for details.
> ```

minor:  "must never appear" is not an obvious interpretation of the linked paper.  I certainly see how providing those overloads for only for T1, T2 of `class` kind would be anomalous, but it hardly seems "must never" rather than "we follow the standard's choice to not provide these".
What am I missing here?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19248)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @ggould-tri)

___
*[`common/hash.h` line 152 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19248#-NTnxdtb6zPzpPalzxi6:-NTo1fIB8_cAzJZJJ6hj:b6f9jbi) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c4075d36fe845e73c3295f86c92f58e7259c44d/common/hash.h#L152)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  "must never appear" is not an obvious interpretation of the linked paper.  I certainly see how providing those overloads for only for T1, T2 of `class` kind would be anomalous, but it hardly seems "must never" rather than "we follow the standard's choice to not provide these".
What am I missing here?
</blockquote></details>

If our goal was for `drake::hash_append` to be a polyfill for `std::hash_append`, having our copy provide different overloads for `std` types would be a problem.  I think that _used_ to be our goal, but since the paper was not adopted I don't think it's a goal anymore.

**Pull request merged**
