### PR TITLE
Basic descriptions of the Python and Julia bindings

### PR DESCRIPTION
**Pull request by rdeits**
@RussTedrake this is linked from the main index.rst. Let me know if it should live somewhere else.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5571)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@rpoyner-tri for feature review

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5571#-:-KfiBUogmNrVpo4Qheab:b9gl8pu)*

**Comment by rdeits** [comment]
@drake-jenkins-bot retest this please

**Comment by rpoyner-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/python_bindings.rst, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5571#-KflIyIh-R1DVU2WOWmq:-KflIyIk0M94jU_iEXyG:bsi58gl) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e8c115c54281cc1e9a1827d94157c06d40b240/drake/doc/python_bindings.rst#L14)):*
> ```reStructuredText
> To use the Drake Python bindings, you need to build Drake and then ensure that Python knows where to find the Drake bindings. When building with CMake, the ``pydrake`` package will be installed by default to ``build/install/lib/python2.7/dist-packages``. You will need to add this folder to your ``PYTHONPATH`` environment variable. For example, if you have Drake installed in ``/home/user/drake-distro/build/install``, then you should do::
> 
> 	export PYTHONPATH="$PYTHONPATH:/home/user/drake-distro/build/lib/python2.7/dist-packages"
> ```

missing a path component for `install/` -- `build/lib` should be `build/install/lib`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5571)*

**Comment by rdeits** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/python_bindings.rst, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5571#-KflIyIh-R1DVU2WOWmq:-KflkHf1HYb-U0fJdm_i:b-ghb5d3) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e8c115c54281cc1e9a1827d94157c06d40b240/drake/doc/python_bindings.rst#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

missing a path component for `install/` -- `build/lib` should be `build/install/lib`.
</blockquote></details>

Wow, thank you. Fixed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5571)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5571#-:-KflltyMq0D-ezFfMbIM:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5571)*

**Comment by rpoyner-tri** [comment]
still needs platform review -- perhaps +@jwnimmer-tri on monday?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5571#-:-Kg5B8uvj-CV6uVAGM5d:b10gs4a)*

**Comment by jwnimmer-tri** [comment]
:lgtm:  Thanks for this.  It looks good other than one nitpick below.  Once fixed, we can merge without re-review.

+(status: curate commits before merging) 

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5571#-Kg5LmQJmSePix6vheYu:-Kg5LmQJmSePix6vheYv:b-n7fazp) (no related file):*
BTW The new `*_bindings.txt` files contain literal tabs (in the sample shell code), and trailing whitespace (lines that end with a literal space prior to the newline).  (These show up as red symbols in reviewable.)  Please do a tidy pass to replace tabs and remove end-of-line whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5571#-:-Kg5LpYEeIuXuIDgCYTN:b9oin2i)*

**Comment by rdeits** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5571#-Kg5LmQJmSePix6vheYu:-KgAKH1x_1AmszUiEqqA:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The new `*_bindings.txt` files contain literal tabs (in the sample shell code), and trailing whitespace (lines that end with a literal space prior to the newline).  (These show up as red symbols in reviewable.)  Please do a tidy pass to replace tabs and remove end-of-line whitespace.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5571)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5571)*

**Pull request merged**
