### PR TITLE
[planning] Export ports from RobotDiagram by default

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
As of r1:

image

As of r2:

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
The only reasons I hadn't done this previously were:

(1) It was not on the critical path, and
(2) I'm not 100% sure about possible downsides.

Having worked my way through it now, I don't think there are any downsides?  Anything I've forgotten @calderpg-tri @rpoyner-tri @SeanCurtis-TRI?

Ready for feature review, if you like.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-:-Nex-mY62N7E7uEm7hBS:b2m5zfg)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-Nex-dap87RZcRFCUcFo:-Nex-dap87RZcRFCUcFp:bds5hkm) (no related file):*
Working

Don't auto-export `scene_graph_plant_configuration`.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238)* status: needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-Nex-dap87RZcRFCUcFo:-Nex7ejp3X6iy9NbzWum:bfssk3w) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Don't auto-export `scene_graph_plant_configuration`.
</blockquote></details>

Done in r2.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for feature

:LGTM: With some lawyerly nit picks.

> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-:-NexDeKL1Jn_GRMnTy1E:b57xgg)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`planning/robot_diagram.h` line 26 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-NexEEZ71lZ46uuYCOtO:-NexEEZ71lZ46uuYCOtP:b-f2ihsv) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e77eb1f9d8eab95f6320885aa97b6b5479da593/planning/robot_diagram.h#L26)):*
BTW As I read this sentence, I kept tripping over language obstacles. Each one, by themselves, weren't huge, but in aggregate it annoyed the lawyer in my mind. (1) Referring to "the superset" feels wrong ("union"? Simply "the set"?). (2) "all ports" isn't strictly true (we omit `scene_graph`'s input ports). (3) Customizing the diagram is insufficient, we could certainly add additional subsystems and the RobotDiagram will merely export that subsystem's ports as well.

> Unless the RobotDiagramBuilder was used to explicitly export ports, by default, the %RobotDiagram's ports will include all output ports and all *unconnected* input ports of its child subsystems (with the sole exception that no geometry::SceneGraph input ports are exported).



_Code quote:_
```objc
the ports exposed by a %RobotDiagram are the superset of all ports provided by
the plant and scene graph (excluding any already-connected internal ports beween
```
___
*[`planning/robot_diagram_builder.h` line 109 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-NexI8La9DqMMbEM6au4:-NexI8La9DqMMbEM6au5:b-hmclz) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e77eb1f9d8eab95f6320885aa97b6b5479da593/planning/robot_diagram_builder.h#L109)):*
nit: How about a cross reference:

> See RobotDiagram class documentation for details on the contract of what gets exported.
___
*[`systems/framework/diagram_builder.h` line 461 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-NexH5MrEyrzFhVtVcl4:-NexH5MrEyrzFhVtVcl5:bd9wu87) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e77eb1f9d8eab95f6320885aa97b6b5479da593/systems/framework/diagram_builder.h#L461)):*
> ```objc
>   bool IsConnectedOrExported(const InputPort<T>& port) const;
> 
>   /// Returns the current number of diagram input ports. The count may change
> ```

BTW bindings? Are they to come later?

**Review by jwnimmer-tri — COMMENTED** [review]
+@calderpg-tri for design review sanity check, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-:-Nexozat1x1cP6-VmJKx:b-7qom5t)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-Nexp4Hw7ZpnVgRj2O_g:-Nexp4Hw7ZpnVgRj2O_h:b8v1svl) (no related file):*
Working

Will need platform review.

___
___
*[`planning/robot_diagram.h` line 26 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-NexEEZ71lZ46uuYCOtO:-NexOGJJBejCaItJmxjS:b-bvcqo4) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e77eb1f9d8eab95f6320885aa97b6b5479da593/planning/robot_diagram.h#L26)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As I read this sentence, I kept tripping over language obstacles. Each one, by themselves, weren't huge, but in aggregate it annoyed the lawyer in my mind. (1) Referring to "the superset" feels wrong ("union"? Simply "the set"?). (2) "all ports" isn't strictly true (we omit `scene_graph`'s input ports). (3) Customizing the diagram is insufficient, we could certainly add additional subsystems and the RobotDiagram will merely export that subsystem's ports as well.

> Unless the RobotDiagramBuilder was used to explicitly export ports, by default, the %RobotDiagram's ports will include all output ports and all *unconnected* input ports of its child subsystems (with the sole exception that no geometry::SceneGraph input ports are exported).
</blockquote></details>

(1) I don't really follow why "superset" was poor, but anyway I'm just as happy with "set".

(2) It's true in the sense that matters.  The fact that our deformable wiring is broken by default should not leak onto the user.  I've updated the implementation comments to clarify.

(3) Even without importing or exporting anything, adding more systems _did_ change the set of ports that are created, so the sentence was accurate.  (The documentation said that by default only MbP and SG were exported.)

In any case, this made me reconsider what behavior we're promising, with some changes pushed now.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238)* status: 3 unresolved discussions, LGTM missing from assignee calderpg-tri

___
*[`planning/robot_diagram_builder.cc` line 89 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-NfD4XgfBzIwuwcu-Ibq:-NfD4XgfBzIwuwcu-Ibr:b-2q43cn) ([raw file](https://github.com/RobotLocomotion/drake/blob/69e37e62f4de9ed478dfc1a1527ad1689810b4a6/planning/robot_diagram_builder.cc#L89)):*
> ```cpp
>         // the deformable code resolves its messy "the configuration input port
>         // is disconnected by default" status quo.
>         continue;
> ```

nit: Surely if we're skipping all input ports for `SceneGraph`, this `continue` should be a `break`.
___
*[`planning/test/robot_diagram_test.cc` line 68 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-NfD5FBv1HdlbKrMa22S:-NfD5FBv1HdlbKrMa22T:b-2a224q) ([raw file](https://github.com/RobotLocomotion/drake/blob/69e37e62f4de9ed478dfc1a1527ad1689810b4a6/planning/test/robot_diagram_test.cc#L68)):*
> ```cpp
> 
> // If the user has exported an input port, nothing else gets exported.
> GTEST_TEST(RobotDiagramBuilderTest, NoDefaultExport_CustomInputPort) {
> ```

btw: Google [really doesn't want you using `_` in test names](https://github.com/google/googletest/blob/main/docs/faq.md). What you've done won't break things, but it's counter to the library's guidance.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238)* status: LGTM missing from assignees rpoyner-tri(platform),calderpg-tri

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-Nexp4Hw7ZpnVgRj2O_g:-NfDCkdr3vteDCUrz_r1:b-z0s7k5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Will need platform review.
</blockquote></details>

+@rpoyner-tri for platform review per schedule, please.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),calderpg-tri

___
*[`planning/robot_diagram_builder.cc` line 71 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-NfDD-fgAcohan4mH1Tn:-NfDD-fh2ciUs0Iggc6l:bruevs2) ([raw file](https://github.com/RobotLocomotion/drake/blob/37e6379df1a73c3f18585772c83cbd7dd5e0f646/planning/robot_diagram_builder.cc#L71)):*
> ```cpp
>                        systems[1] == &scene_graph_;
>   if (!is_good) {
>     throw std::logic_error(
> ```

BTW No this is hardening it. You're really getting into the mind of the self-destructive.  :) Nice.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 4 of 8 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-:-NfHL0Bt34sbLaTL1Vsp:bnfp4nl)* status: LGTM missing from assignee calderpg-tri

**Review by jwnimmer-tri — COMMENTED** [review]
Ping @calderpg-tri for any thoughts / LGTM?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-:-NfLyUz39oY7IwQi-diQ:bjpqki8)* status: LGTM missing from assignee calderpg-tri

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 4 of 8 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20238#-:-NfM5WYjDUs0dVQj1LQm:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform),calderpg-tri

**Pull request merged**
