### PR TITLE
Added a PR2 simulation in c++.

### PR DESCRIPTION
**Pull request by TristanThrush**
Professor Tedrake wanted to look over this simulation. Grippers and arms don't appear. I am told that there are also deeper problems with the simulator that can't model the PR2's omnidirectional base.

To run the simulation, run drake-visualizer and then run the binary built from examples/PR2/pr2_simulation.cc

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6328)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
You can get away without using sim_diagram_builder or world_sim_tree_builder. Those are only useful if you have multiple robot / objects. 
For single arm, drake/examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_demo.cc is a much simple example. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6328#-:-Kmb4mDTJ_FWeuvC7SvD:bsthj02)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
+@naveenoid has volunteered for feature review.

**Comment by naveenoid** [comment]
I guess some cleanup is needed to update this PR to current drake. Apologies for review delays but perhaps you can look into updates and cleanup of spurious comments and then continue review? Or you could cancel, update and submit new PR.

---

Reviewed 1 of 14 files at r1.
Review status: 1 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/PR2/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6328#-L23ybcQaZmcFu5NQNWP:-L23ybcRV3yK1yRceXqm:b5lpag6) ([raw file](https://github.com/robotlocomotion/drake/blob/386fcecaec68edf33a65dee6fa5c8ab04b391882/drake/examples/PR2/CMakeLists.txt#L1)):*
> ```CMake
> #drake_add_matlab_test(NAME examples/PR2/drawPR2 OPTIONAL bullet COMMAND drawPR2)
> ```

Unnecessary to have a CMakeLists.txt anymore.

---

*[drake/examples/PR2/pr2_simulation.cc, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6328#-L23ymREyYBSk5g-fYaJ:-L23ymRFElRdIsrN7I6a:bpbzrkg) ([raw file](https://github.com/robotlocomotion/drake/blob/386fcecaec68edf33a65dee6fa5c8ab04b391882/drake/examples/PR2/pr2_simulation.cc#L49)):*
> ```cpp
>         namespace pr2 {
>             namespace {
> /*
> ```

no need to have these backup comments in the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6328#-:-L23yvE6HmXA8ehnU7az:b8jktda)*

**Comment by naveenoid** [comment]
Reviewed 2 of 14 files at r1.
Review status: 3 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6328)*

**Pull request closed without merging**
