### PR TITLE
Use environment maps in RenderEngineVtk

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Use environment maps in RenderEngineVtk

 - Extend Drake's VTK build to include artifacts necessary for reading hdr images.
   - This also corrected a defect in a patch that was previously unused. We no longer attempt to delete image importers that
     don't exist.
 - Introduce EnvironmentMap and EquirectangularMap structs for configuring RenderEngineVtk (add bindings).
   - Add it to RenderEngineVtkParams
 - New lighting semantics
   - Specifying an environment map replaces the default lights in the engine. Lights can be added back in explicitly.
   - If a glTF is included or an environment map is included, all materials get converted to PBR.
     - In the future we may consider permanently making everything PBR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@joemasterjohn Can I persuade you to put on your graphics hat and do a feature review?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-:-Nh2ZJFfBLZkOpvK54pD:b-iivap8)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh2ZOYUEKlMUYHc65Xh:-Nh2ZOYV2r_1zAlHxFIV:bpy3wp9) (no related file):*
Note to reviewers:

The second commit is garbage. It is merely there to provide a quick and dirty recipe for seeing the impact of the feature in the wild. Follow the instructions in the second commit's message.

___

**Review by jwnimmer-tri — COMMENTED** [review]
I think landing the feature and unit testing now is a good checkpoint to get it into CI, but see below re: API stability.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-:-Nh3AmV_-VYceD2o0EwZ:bsxjcoa)* status: 4 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 38 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh3AJTAEFNUZWmboNhD:-Nh3AJTAEFNUZWmboNhE:bbqnprf) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b2f771a903535e8a5c9466ba60e7d592a15f435/geometry/render_vtk/render_engine_vtk_params.h#L38)):*
> ```objc
>   // TODO(SeanCurtis-TRI): It would be nice if this supported package. To that
>   // end proper URIs including file:// or even data://, I suppose.
>   /** The path to the map file. */
> ```

Because we anticipate with high probability that this will _not_ be a filesystem path soon enough (and that such a change will not be backwards compatible), we should somehow warn users about that in the documentation here, maybe with `@experimental` and/or extra commentary.
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 55 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh3Akjp4fx3L_jqCTEw:-Nh3Akjp4fx3L_jqCTEx:bu7yjhd) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b2f771a903535e8a5c9466ba60e7d592a15f435/geometry/render_vtk/render_engine_vtk_params.h#L55)):*
> ```objc
>   bool skybox{true};
> 
>   /* The texture to use for the environment map. If none is defined, there is
> ```

nit `/**` not `/*`.
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 64 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh3Ai0uDEss2Q3_O85J:-Nh3Ai0uDEss2Q3_O85K:bogf2r6) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b2f771a903535e8a5c9466ba60e7d592a15f435/geometry/render_vtk/render_engine_vtk_params.h#L64)):*
> ```objc
>        skybox: true
>        texture: !EquirectangularMap
>          path: [valid path URI]
> ```

nit Not a URI yet.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with a few nits sprinkled in. 

> Reviewed 14 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-:-NhawdNY9fufLRh2v0dk:b-3j8oa7)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.h` line 243 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhasF_Q2EGSD4gUo0e_:-NhasF_Q2EGSD4gUo0ea:bpxuc1v) ([raw file](https://github.com/RobotLocomotion/drake/blob/985689daff1b8ceb808ab93928834eddeb94d113/geometry/render_vtk/internal_render_engine_vtk.h#L243)):*
> ```objc
>   // interpolation. This can be mindlessly called repeatedly without harm.
>   // It should be invoked any time a necessary condition is encountered to
>   // insure proper materials:
> ```

nit: insure->ensure



_Suggestion:_
```objc
  // ensure proper materials:
```
___
*[`geometry/render_vtk/internal_render_engine_vtk.h` line 248 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhasVK34O6XIol0mdny:-NhasVK34O6XIol0mdnz:b-9kdsaj) ([raw file](https://github.com/RobotLocomotion/drake/blob/985689daff1b8ceb808ab93928834eddeb94d113/geometry/render_vtk/internal_render_engine_vtk.h#L248)):*
> ```objc
>   //   2) If an environment map has been added.
>   //
>   // Note: this effects *all* objects, whether or not a model has been
> ```

nit: effects->affects



_Suggestion:_
```objc
  // Note: this affects *all* objects
```
___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 733 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhau4Tv5nNUHHhw0mnE:-Nhau4Tv5nNUHHhw0mnF:b-1q9g61) ([raw file](https://github.com/RobotLocomotion/drake/blob/985689daff1b8ceb808ab93928834eddeb94d113/geometry/render_vtk/internal_render_engine_vtk.cc#L733)):*
> ```cpp
>       skybox->SetFloorRight(0, -1, 0);
>       skybox->SetProjection(vtkSkybox::Sphere);
>       skybox->SetGammaCorrect(!env_map.gamma_correct);
> ```

nit: seems odd to have the use the negated value. Does our parameter mean "needs gamma correction"?



_Code quote:_
```cpp
      skybox->SetGammaCorrect(!env_map.gamma_correct);
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1984 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhavZFO0TNxSw_VCSTL:-NhavZFO0TNxSw_VCSTM:b-8r4v7z) ([raw file](https://github.com/RobotLocomotion/drake/blob/985689daff1b8ceb808ab93928834eddeb94d113/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1984)):*
> ```cpp
>   // at the result, confirm it's what we expect to see, and encode those
>   // colors here. We don't have a closed-form solution for predicting the
>   // expected colors.
> ```

BTW thanks for this comment, I was curious about your methodology for finding the right illuminated color value.



_Code quote:_
```cpp
  // The expected colors are the *observed* colors. Perform the rendering, look
  // at the result, confirm it's what we expect to see, and encode those
  // colors here. We don't have a closed-form solution for predicting the
  // expected colors.
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2065 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhavwHt8WCWqayc20_d:-NhavwHu77Ijw4w_jL8f:b7jki5c) ([raw file](https://github.com/RobotLocomotion/drake/blob/985689daff1b8ceb808ab93928834eddeb94d113/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2065)):*
> ```cpp
>     const RgbaColor edge_color(image.at(ex, ey));
>     const RgbaColor bg_color = config.show_map ? config.bg_color : clear_color;
>     EXPECT_TRUE(IsColorNear(edge_color, bg_color, tolerance))
> ```

nit: Does the edge color need the same tolerance? I would expect it to just show the color it sampled from the texture (if no other lighting is present).



_Code quote:_
```cpp
    EXPECT_TRUE(IsColorNear(edge_color, bg_color, tolerance))
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed (you'd think English wasn't my native language).

+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-:-NhbEV3K787L6j4t2o1U:bxk5b8d)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh2ZOYUEKlMUYHc65Xh:-NhbE_7oD33vIIM4zvbU:bkeh8l4) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW For now I'm assuming the test failure on the mac is due to this second commit. After review is largely complete, I'll excise the commit and confirm.
</blockquote></details>

+(status: do not merge) Until we pop off the dummy commit and confirm CI passage.

___
___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 733 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhau4Tv5nNUHHhw0mnE:-NhbCFOVBonzPJkeSnOK:br885f7) ([raw file](https://github.com/RobotLocomotion/drake/blob/985689daff1b8ceb808ab93928834eddeb94d113/geometry/render_vtk/internal_render_engine_vtk.cc#L733)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: seems odd to have the use the negated value. Does our parameter mean "needs gamma correction"?
</blockquote></details>

Done

That was bothering me from the code I copied and pasted. Correlated parameters. I've simplified it down.
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 38 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh3AJTAEFNUZWmboNhD:-NhbCxid0_WsiP4PGUeF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b2f771a903535e8a5c9466ba60e7d592a15f435/geometry/render_vtk/render_engine_vtk_params.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Because we anticipate with high probability that this will _not_ be a filesystem path soon enough (and that such a change will not be backwards compatible), we should somehow warn users about that in the documentation here, maybe with `@experimental` and/or extra commentary.
</blockquote></details>

Done.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1984 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhavZFO0TNxSw_VCSTL:-NhbE17s-av97laQqyxE:bz8zoxk) ([raw file](https://github.com/RobotLocomotion/drake/blob/985689daff1b8ceb808ab93928834eddeb94d113/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1984)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

BTW thanks for this comment, I was curious about your methodology for finding the right illuminated color value.
</blockquote></details>

Short of cracking open VTK's shader code, I figured there wasn't any simpler way to do this. :)
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2065 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhavwHt8WCWqayc20_d:-NhbDdN1A65KzpgK9qbR:b-alsuc9) ([raw file](https://github.com/RobotLocomotion/drake/blob/985689daff1b8ceb808ab93928834eddeb94d113/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2065)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Does the edge color need the same tolerance? I would expect it to just show the color it sampled from the texture (if no other lighting is present).
</blockquote></details>

It can definitely pass with a smaller tolerance running locally, however, xvfb on focal may do different gamma correction on the background image. I don't think this loose tolerance particularly hurts us and its nice to not play with fire across the various platforms.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 38 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh3AJTAEFNUZWmboNhD:-NhbH6uL8FcHd2FusoAz:b6qud5y) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b2f771a903535e8a5c9466ba60e7d592a15f435/geometry/render_vtk/render_engine_vtk_params.h#L38)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Missing push?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 38 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh3AJTAEFNUZWmboNhD:-NhbLoPX-9V2cTVqKEKv:b-4u8dew) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b2f771a903535e8a5c9466ba60e7d592a15f435/geometry/render_vtk/render_engine_vtk_params.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing push?
</blockquote></details>

Nope. Definitely pushed. Might simply be a delay in reviewable.

But that's neither here nor there. I definitely had a CI error after rebasing onto master. So, now things are happy and pushed again.

**Review by sherm1 — COMMENTED** [review]
Lunch checkpoint

> Reviewed 7 of 14 files at r1, 2 of 7 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-:-Nhc6l0_D1llJxR5DxIX:bw5ecf7)* status: 7 unresolved discussions, LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh2ZOYUEKlMUYHc65Xh:-NhbrTWwEwulMwytEX18:bjmdxyv) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

+(status: do not merge) Until we pop off the dummy commit and confirm CI passage.
</blockquote></details>

With some f2f help from Sean, I ran the test case successfully and it looked great!

___
___
*[`geometry/render/test/meshes/fully_textured_pyramid.sdf` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhbruTk5ZhpnxqW9b4e:-NhbruTk5ZhpnxqW9b4f:bkwmorr) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render/test/meshes/fully_textured_pyramid.sdf#L9)):*
> ```
>         <geometry>
>           <mesh>
>             <uri>package://drake/geometry/render/test/meshes/mirror_ball.gltf</uri>
> ```

BTW this file is called "fully_textured_pyramid" but now has a mirrored ball in it instead. I presume this will get nuked with the 2nd commit but if not it should get renamed. 
___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 105 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhc-kVH739Ip7Moipix:-Nhc-kVI7m0OVellyYXq:bn868w5) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render_vtk/internal_render_engine_vtk.cc#L105)):*
> ```cpp
> struct EnvironmentTexture {
>   vtkSmartPointer<vtkTexture> texture;
>   bool is_hdr{};
> ```

BTW consider an explicit `{false}` here for clarity (as you did for use_pbr_materials_ above)
___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 114 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhc0kCOCJ_txzKvPxLn:-Nhc0kCOCJ_txzKvPxLo:bsamgul) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render_vtk/internal_render_engine_vtk.cc#L114)):*
> ```cpp
>   std::string extension =
>       std::filesystem::path(fileName).extension().generic_string();
>   std::transform(extension.begin(), extension.end(), extension.begin(),
> ```

BTW consider cbegin() and cend() for the source
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 21 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhc2ThDB9cUma1l0JEU:-Nhc2ThDB9cUma1l0JEV:bdjsrln) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render_vtk/render_engine_vtk_params.h#L21)):*
> ```objc
> /** (Internal use only) A place holder indicating that no texture has been
>  provided for environment map (and, therefore, no environment map). */
> struct NullTexture {
> ```

BTW could this struct actually be in `drake::geometry::internal::` namespace?
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 52 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhc2nlJ0vTg9PjCE0IB:-Nhc2nlJ0vTg9PjCE0IC:b-yc1nk6) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render_vtk/render_engine_vtk_params.h#L52)):*
> ```objc
> 
>   /** If true, the environment map will be rendered in a sky box. If false, it
>    wont' be visible in the background, but it will illuminate objects. */
> ```

typo: wont' -> won't
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 70 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhc35HK9-KIzSO2rnBO:-Nhc35HK9-KIzSO2rnBP:b-8xwi34) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render_vtk/render_engine_vtk_params.h#L70)):*
> ```objc
>    @note This will change from a simple file path to a more comprehensive URI
>    soon. So, be aware you will have to change /path/image.png to
>    file:///path/image.png in the near future. */
> ```

BTW is three slashes right?

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: w/a few nits

> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-:-NhcYMVk6YD8wheiFBZE:b-laki63)* status: 7 unresolved discussions, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`bindings/pydrake/geometry/geometry_py_render.cc` line 341 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhcXPCP1LJGNX5hL8OI:-NhcXPCP1LJGNX5hL8OJ:b-jzz284) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/bindings/pydrake/geometry/geometry_py_render.cc#L341)):*
> ```cpp
> 
>   {
>     using Class = geometry::NullTexture;
> ```

BTW does this internal-use-only struct need to be wrapped? If so it needs a test.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed. Waiting to remove "do not merge" until I confirm that CI is happy after the hack has been removed.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-:-NhgNPV2-aj3xXpY0dPZ:b-2feb9e)* status: labeled "do not merge" (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nh2ZOYUEKlMUYHc65Xh:-NhgNM4f99pUuo15fdLJ:b-l7evlf) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

With some f2f help from Sean, I ran the test case successfully and it looked great!
</blockquote></details>

Dummy commit popped off. We'll see how CI goes.

___
___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 105 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhc-kVH739Ip7Moipix:-NhgJz7N9OU_j9UHRltE:b-ohvlhg) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render_vtk/internal_render_engine_vtk.cc#L105)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider an explicit `{false}` here for clarity (as you did for use_pbr_materials_ above)
</blockquote></details>

I considered it; but the key is I don't have any code that relies on the default value and I don't want to imply that it does. In contrast, the `use_pbr_materials_` *definitely* makes use of the default value.
___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 114 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhc0kCOCJ_txzKvPxLn:-NhgKUOh6T_6p6BhEoLm:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render_vtk/internal_render_engine_vtk.cc#L114)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider cbegin() and cend() for the source
</blockquote></details>

Done
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 21 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhc2ThDB9cUma1l0JEU:-NhgKumn5bTz0hYA3Yc7:bngwy5z) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render_vtk/render_engine_vtk_params.h#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW could this struct actually be in `drake::geometry::internal::` namespace?
</blockquote></details>

Technically? Maybe. Sure. But see my note in the bindings below which is my reason to leave it in the same namespace as its eventual replacement but tagged as internal.
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 70 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-Nhc35HK9-KIzSO2rnBO:-NhgKYjYCp8KkE7ISaEm:brsi96s) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render_vtk/render_engine_vtk_params.h#L70)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is three slashes right?
</blockquote></details>

It is. The original path was an *absolute* path `/path/image.png`. When you attach the `file://` prefix to it, you get the triple slash.
___
*[`bindings/pydrake/geometry/geometry_py_render.cc` line 341 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhcXPCP1LJGNX5hL8OI:-NhgL9rD87SAKJyQoJCY:b-5r7ovv) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/bindings/pydrake/geometry/geometry_py_render.cc#L341)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW does this internal-use-only struct need to be wrapped? If so it needs a test.
</blockquote></details>

It does because it's the only way that the serialization-based bindings of the containing classes will work (for a variant to bind, all of its options must be bound).

Arguably, the fact that `EnvironmentMap` compiles at all is evidence that the wrapping is appropriate. However, if you look at `render_test.py`, you'll note that the newly added test confirms that an `EnvironmentMap` constructed without specifying the texture is confirmed to be an instance of `NullTexture`. So, to the extent that it has any functionality, that functionality is tested.
___
*[`geometry/render/test/meshes/fully_textured_pyramid.sdf` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-NhbruTk5ZhpnxqW9b4e:-NhgJCc-33ZC_jNL0zBB:bt7mr2v) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6eba0facfdf063bc74c304cf69995386b1702f6/geometry/render/test/meshes/fully_textured_pyramid.sdf#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this file is called "fully_textured_pyramid" but now has a mirrored ball in it instead. I presume this will get nuked with the 2nd commit but if not it should get renamed.
</blockquote></details>

This is part of the 2nd commit and will evaporate.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385)* status: labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not merge) 

Looks like everything is happy.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20385#-:-NhgdJZd3Yp37a6-oMwc:b-gisx1t)* status: labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Pull request merged**
