### PR TITLE
Adds style guide rule clarifying when aborts are OK.

### PR DESCRIPTION
**Pull request by liangfok**
Per Slack discussion.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4728)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sherm1, +@david-german-tri, +@sammy-tri, +@jwnimmer-tri, +@ggould-tri for platform review please. Thanks! :smile: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-:-Ka6tMVXGqz6mBYU8g7a:bo8v5e7)*

**Comment by ggould-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-Ka7xKbaBUATHQ2LCG78:-Ka7xKbaBUATHQ2LCG79:b-gt4qjw) ([raw file](https://github.com/robotlocomotion/drake/blob/faa1a9e5fabbfc5b18ad6ffe2e682cabff6e3910/drake/doc/code_style_guide.rst#L248)):*
> ```reStructuredText
>     `#3355 <https://github.com/RobotLocomotion/drake/issues/3355>`_.
> 
> * Aborts should only be used in Drake's numerical libraries to
> ```

I see no reason that this advice is specific to numerical libraries.  Precondition violations can reasonably be checked in any class or method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-:-Ka87JXGFudcz3UsoK24:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/code_style_guide.rst, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-Ka88_umtxUORS03W0Rq:-Ka88_unv7Uq3IsbLH9D:b-7lo1p) ([raw file](https://github.com/robotlocomotion/drake/blob/faa1a9e5fabbfc5b18ad6ffe2e682cabff6e3910/drake/doc/code_style_guide.rst#L248)):*
> ```reStructuredText
>     `#3355 <https://github.com/RobotLocomotion/drake/issues/3355>`_.
> 
> * Aborts should only be used in Drake's numerical libraries to
> ```

This first sentence makes approximately every use of assertions currently in Drake defective, because it implies that if users call a public method incorrectly, we cannot abort.  Surely we don't want that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-Ka7xKbaBUATHQ2LCG78:-Ka8C4sXV0U72M2qXNn_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/faa1a9e5fabbfc5b18ad6ffe2e682cabff6e3910/drake/doc/code_style_guide.rst#L248)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I see no reason that this advice is specific to numerical libraries.  Precondition violations can reasonably be checked in any class or method.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-Ka88_umtxUORS03W0Rq:-Ka8CDapNHnwfY260Jh0:b-r78hva) ([raw file](https://github.com/robotlocomotion/drake/blob/faa1a9e5fabbfc5b18ad6ffe2e682cabff6e3910/drake/doc/code_style_guide.rst#L248)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This first sentence makes approximately every use of assertions currently in Drake defective, because it implies that if users call a public method incorrectly, we cannot abort.  Surely we don't want that?
</blockquote></details>

Yeah, I see no harm in adopting a rule that defects existing code in Drake since having this rule will arguably make Drake's code more user-friendly since nicer messages can be provided within thrown exceptions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-Ka88_umtxUORS03W0Rq:-Ka8CViHbnOjyf1LGX0Q:b-plqpb2) ([raw file](https://github.com/robotlocomotion/drake/blob/faa1a9e5fabbfc5b18ad6ffe2e682cabff6e3910/drake/doc/code_style_guide.rst#L248)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yeah, I see no harm in adopting a rule that defects existing code in Drake since having this rule will arguably make Drake's code more user-friendly since nicer messages can be provided within thrown exceptions.
</blockquote></details>

Well, if the intent is to make all existing code defective, that's a strong :lgtm_cancel: from me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by liangfok** [comment]
*[drake/doc/code_style_guide.rst, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-Ka88_umtxUORS03W0Rq:-Ka8DJcHwDZU5y9kejDM:b-v7q33f) ([raw file](https://github.com/robotlocomotion/drake/blob/faa1a9e5fabbfc5b18ad6ffe2e682cabff6e3910/drake/doc/code_style_guide.rst#L248)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Well, if the intent is to make all existing code defective, that's a strong :lgtm_cancel: from me.
</blockquote></details>

Actually, this rule contains the words "should" and "consider", making it less strong than "defecting all existing code".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/code_style_guide.rst, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-Ka88_umtxUORS03W0Rq:-Ka8Dk3VH0FjIQh1zZzo:b-lee72a) ([raw file](https://github.com/robotlocomotion/drake/blob/faa1a9e5fabbfc5b18ad6ffe2e682cabff6e3910/drake/doc/code_style_guide.rst#L248)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Actually, this rule contains the words "should" and "consider", making it less strong than "defecting all existing code".
</blockquote></details>

"Should" in this the context of this document means an enforced rule.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by liangfok** [comment]
*[drake/doc/code_style_guide.rst, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-Ka88_umtxUORS03W0Rq:-Ka8DyXXic87z9eyvuCB:bnkvvgz) ([raw file](https://github.com/robotlocomotion/drake/blob/faa1a9e5fabbfc5b18ad6ffe2e682cabff6e3910/drake/doc/code_style_guide.rst#L248)):*
How about I reword as follows?

> Prefer to use aborts only to *catch bugs that are internal to Drake*.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/code_style_guide.rst, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4728#-Ka88_umtxUORS03W0Rq:-Ka8EFu7C-ssjMN5IAEH:b-new4kr) ([raw file](https://github.com/robotlocomotion/drake/blob/faa1a9e5fabbfc5b18ad6ffe2e682cabff6e3910/drake/doc/code_style_guide.rst#L248)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

How about I reword as follows?

> Prefer to use aborts only to *catch bugs that are internal to Drake*.
</blockquote></details>

Can we take this to slack?  I thought this PR was about fixing abuse of Death tests, but it sounds like you're trying to strongly suggest (to the point of BTW-nit mandating) an entirely new coding style.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4728)*

**Comment by liangfok** [comment]
Per [Slack discussion](https://drakedevelopers.slack.com/archives/platform_review/p1484066904000111), I've decided to close this PR until we decide it's necessary to gold-plate the error messages emitted by Drake.

**Pull request closed without merging**
