### PR TITLE
Drake util cleanup

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #3278.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3415)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please
(windows executor flake)

**Comment by hongkai-dai** [comment]
I just jump in Reviewable to say this PR is great! My PR to clean up the drakeGeometryUtil depends on this PR, so I hope it gets merged in very soon.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3415#-:-KRURL1Inht9BOeKeqlW:b-lqyb6x)*

**Comment by jwnimmer-tri** [comment]
@hongkai-dai The thing I was still considering was whether to leave `drakeUtil.h` still providing a deprecated `resizeDerivativesToMatchScalar` to out-of-tree code.  Do you have any sense if that's worthwhile?  Also, would you like to self-assign as feature reviewer?

**Comment by jwnimmer-tri** [comment]
I went ahead and preemptively added the deprecated forwarder.
+@david-german-tri for platform review (tomorrow is fine).

**Comment by hongkai-dai** [comment]
I do not think we should keep deprecated `resizeDerivativesToMatchScalar`. I would rather use the `drake::math::resizeDerivativesToMatchScalar`. As I can see, the openhumanoids project (the one for Valkyrie and Atlas) does not call the deprecated `resizeDerivativesToMatchScalar`. Is that the out-of-tree code you are thinking about?
 +@hongkai-dai for feature review.

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3415#-:-KRV2p_esWY3kMdLzHxU:bo5qtrz)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3415)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3415#-:-KRV3XkHQJCru1XbpOj6:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
> I do not think we should keep deprecated resizeDerivativesToMatchScalar. I would rather use the drake::math::resizeDerivativesToMatchScalar.

Done.  I've removed that (deprecation-adding) commit from the PR.

> As I can see, the openhumanoids project (the one for Valkyrie and Atlas) does not call the deprecated resizeDerivativesToMatchScalar. Is that the out-of-tree code you are thinking about?

Yes, though also any other users of Drake C++.  But if OH doesn't use it, perhaps unlikely that anyone else would.

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3415#-:-KRV5uQoeygDp0FJ7XDM:b5iyt3k)*

**Comment by jwnimmer-tri** [comment]
The only jenkins error was a windows flake.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/math/autodiff.h, line 169 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3415#-KRZQGmQ_dEy1pcHa6Ly:-KRZQGmQ_dEy1pcHa6Lz:b-iilfs5) ([raw file](https://github.com/robotlocomotion/drake/blob/446da667136ee0095377f265c30d2526c1f8295a/drake/math/autodiff.h#L169)):*
> ```objc
> }
> 
> namespace internal {
> ```

BTW, consider consolidating the two `internal` blocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3415#-:-KRZQRFuYwKRHvhx5bEt:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/math/autodiff.h, line 169 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3415#-KRZQGmQ_dEy1pcHa6Ly:-KRZqV0FfB_TVDBEMk7m:bfea487) ([raw file](https://github.com/robotlocomotion/drake/blob/446da667136ee0095377f265c30d2526c1f8295a/drake/math/autodiff.h#L169)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, consider consolidating the two `internal` blocks.
</details>
My intuition is to keep the helpers adjacent to their helpees.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3415)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to windows flake.

**Pull request merged**
