### PR TITLE
[geometry/dev] introduce HttpService helper interface

### PR DESCRIPTION
**Pull request by svenevs**
The HttpService interface serves as the primary mechanism for
facilitating client / server communications.  A given RenderClient
will maintain an HttpService for the lifetime of the application.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16702)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@zachfang for review please.

I have most of `HttpServiceCurl` implementation refactored out, which more or less is taking all curl related stuff from `RenderClient` and moving it there (so it will be another big diff, but it's mostly just moving code to a different class + some cleanup).

-----------

To build the doxygen documentation for reading convenience:

```diff
--- a/doc/doxygen_cxx/Doxyfile_CXX.in
+++ b/doc/doxygen_cxx/Doxyfile_CXX.in
@@ -130,11 +130,11 @@ FILE_PATTERNS          = *.h \
 RECURSIVE              = YES
 EXCLUDE                =
 EXCLUDE_SYMLINKS       = NO
-EXCLUDE_PATTERNS       = "@INPUT_ROOT@/*/dev/*" \
-                         "@INPUT_ROOT@/*/test/*" \
+# EXCLUDE_PATTERNS       = "@INPUT_ROOT@/*/dev/*"
+EXCLUDE_PATTERNS       = "@INPUT_ROOT@/*/test/*" \
                          "@INPUT_ROOT@/*/MG/*"
-EXCLUDE_SYMBOLS        = "*::internal" \
-                         "pybind11"
+# EXCLUDE_SYMBOLS        = "*::internal" \
+# EXCLUDE_SYMBOLS        = "pybind11"
 # Don't document our (obvious) Eigen overloads like "isinf", etc.
 EXCLUDE_SYMBOLS       += "Eigen"
 EXAMPLE_PATH           =
```

and `bazel run //doc/doxygen_cxx:build -- --serve drake.geometry.render drake.systems.sensors`

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16702#-:-MxBYhYP-6d28N9Pic_9:b-kdaxlb)* status: 4 unresolved discussions, LGTM missing from assignee zachfang (waiting on @zachfang)

___
*[geometry/render/dev/http_service.h, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxBYoT6AsxYxvnP50Qn:-MxBYoT6AsxYxvnP50Qo:bnarltk) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.h#L13)):*
> ```objc
> namespace geometry {
> namespace render {
> namespace internal {
> ```

FYI `RenderClient` will be moving to `drake::geometry::render::internal` as well.
___
*[geometry/render/dev/http_service.h, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxBYwC_4LTonlorgwO6:-MxBYwC_4LTonlorgwO7:bitda2t) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.h#L32)):*
> ```objc
>      for loading this file as the appropriate file type, **and** for deleting
>      the file when it is no longer needed. */
>   std::optional<std::string> data_path{std::nullopt};
> ```

We may or may not want to call this something else?  I'm satisfied with the name, but also open to change.  The main idea is that for a generic response, we have no idea if (a) something is going to get sent back, (b) if it is text, or (c) binary data.  So the caller is responsible for checking this member and deciding what to do if it exists, as well as deleting the file.
___
*[geometry/render/dev/http_service.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxBaFuABNyj_kuzCt3c:-MxBaFuABNyj_kuzCt3d:b-dfhouf) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.h#L58)):*
> ```objc
>   HttpService(HttpService&&) = delete;
>   HttpService& operator=(HttpService&&) = delete;
>   //@}
> ```

This may not be the right thing to do.  I tried to model after `RenderEngine`, the above is how `RenderEngineVtk` does things though.  It was not clear to me why `RenderEngine` does not explicitly define a copy constructor.  Is this the right thing to do, or should it be done with 

```
 protected:
  // Allow derived classes to implement Cloning via copy-construction.
  DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(HttpService)
```

?
___
*[geometry/render/dev/http_service.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxBZGZd3inNi-Utc2UB:-MxBZGZd3inNi-Utc2UC:b-dj9lio) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.h#L66)):*
> ```objc
>      drake::temp_directory().  File responses from a server will be stored here.
>      The %HttpService does **not** own this directory, and is not responsible
>      for deleting it.
> ```

The plan is to have

```cpp
class RenderEngineGltfClient : public RenderEngineVtk {
 private:
  std::unique_ptr<RenderClient> render_client_;
};

class RenderClient {
 private:
  std::unique_ptr<HttpService> http_service_;  // defaults to being the incoming HttpServiceCurl, changed in testing
};
```

The question here: who should be the official owner of `drake::temp_directory()`?  I was thinking it makes sense for the `RenderClient` to be the owner of it, and `HttpService` will share it to save responses as well as `RenderEngineGltfClient` to generate glTF files into.
___
*[geometry/render/dev/http_service.h, line 252 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxB_PQcBh1He8zmWqGD:-MxB_PQcBh1He8zmWqGE:butln28) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.h#L252)):*
> ```objc
>       const std::map<std::string,
>                      std::pair<std::string, std::optional<std::string>>>&
>           file_fields) const;
> ```

FYI as far as changes have revealed in refactoring out to `HttpServiceCurl`, these are the only helper methods that make sense in this class.  There may be new ones that need to get added in the future though.  `RenderClient` will still keep the helper methods for loading images to drake buffers.
___
*[geometry/render/dev/http_service.cc, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxB_iXm-vStakKH-RwT:-MxB_iXm-vStakKH-RwU:bo8yk58) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.cc#L22)):*
> ```cpp
> /* Throw an std::runtime_error if the directory does not exist, or cannot be
>  written to / read from. */
> void ThrowIfInvalidTempDirectory(const std::string& temp_directory) {
> ```

FYI relates to conversation above, one class will own the `temp_directory()`, everybody else shares it.  But in the scope of this class, it is a requirement that it already exists.
___
*[geometry/render/dev/http_service.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxB_rNbBAehYmzJtTos:-MxB_rNbBAehYmzJtTot:b-lceoxx) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.cc#L45)):*
> ```cpp
>     }
>     in.close();
>     fs::remove(test_txt);
> ```

I am not particularly thrilled about doing this to test if we can write to the directory, but I don't see a better option.  Checking the directory permissions may not always reveal whether you can _actually_ write to the directory. (?)
___
*[geometry/render/dev/http_service.cc, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxBa9kW-8_FHYQrOACY:-MxBa9kW-8_FHYQrOACZ:bcojbyz) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.cc#L96)):*
> ```cpp
>         NiceTypeName::Get(*this), NiceTypeName::Get(clone_ref),
>         NiceTypeName::Get(*this)));
>   }
> ```

FYI this is straight from the `RenderEngine` playbook.

**Review by svenevs — COMMENTED** [review]
I changed the `HttpResponse` struct here to gain two additional data members:

- `bool service_error`: let the underlying `HttpService` mark the response as failed.  For example, curl had an internal failure (that is, a service can error OR a server can error).
- `std::optional<std::string> service_error_message`: any messages that can be provided as to why service failed.  Note that they are separate because theoretically an `HttpService`  may not have a known message to provide, but did detect failure (e.g., this is why relying on `service_error_message.has_value()` over `bool service_error` is not a good idea).
- Renamed `HttpCodeOk()` to `Good()`, it checks http code and `service_error`.  Code usage looks better: `auto response = service_->PostForm(...);` and now checking `if (!response.Good()) { ... error handling ... }`

Restructure of the rest of the classes involved is complete now, this is better than having `HttpServiceCurl` throw execptions since calling class can provide more context on error (provide better exception to user).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16702#-:-MxI5pMUE6z2ko-vKd22:bwthw3x)* status: 4 unresolved discussions, LGTM missing from assignee zachfang (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
Sorry for the delayed review. Some of it takes me quite some time to comprehend.

> Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16702#-:-MxbNnY56-Cy_3MvcWo9:b-lqqkyx)* status: 5 unresolved discussions, LGTM missing from assignee zachfang (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/http_service.h, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxBYwC_4LTonlorgwO6:-MxbIhtv9vx6VHOPU82s:b6ll8sa) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.h#L32)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

We may or may not want to call this something else?  I'm satisfied with the name, but also open to change.  The main idea is that for a generic response, we have no idea if (a) something is going to get sent back, (b) if it is text, or (c) binary data.  So the caller is responsible for checking this member and deciding what to do if it exists, as well as deleting the file.
</blockquote></details>

LGTM. I don't have a preference either. And to your point, `data_path` is generic to me.
___
*[geometry/render/dev/http_service.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxBaFuABNyj_kuzCt3c:-MxbJY1u6yjldMuDoVYF:b-jaz37p) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.h#L58)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

This may not be the right thing to do.  I tried to model after `RenderEngine`, the above is how `RenderEngineVtk` does things though.  It was not clear to me why `RenderEngine` does not explicitly define a copy constructor.  Is this the right thing to do, or should it be done with 

```
 protected:
  // Allow derived classes to implement Cloning via copy-construction.
  DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(HttpService)
```

?
</blockquote></details>

OK. It's not obvious to me why it's structured this way. We can maybe punt that to the platform review.
___
*[geometry/render/dev/http_service.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxBZGZd3inNi-Utc2UB:-MxbKW1e5J8zqmPelJUD:b-elwd5y) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.h#L66)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

The plan is to have

```cpp
class RenderEngineGltfClient : public RenderEngineVtk {
 private:
  std::unique_ptr<RenderClient> render_client_;
};

class RenderClient {
 private:
  std::unique_ptr<HttpService> http_service_;  // defaults to being the incoming HttpServiceCurl, changed in testing
};
```

The question here: who should be the official owner of `drake::temp_directory()`?  I was thinking it makes sense for the `RenderClient` to be the owner of it, and `HttpService` will share it to save responses as well as `RenderEngineGltfClient` to generate glTF files into.
</blockquote></details>

LGTM. Alternatively, `RenderEngineGltfClient` can be the owner and pass down to `RenderClient` (and then `HttpService`) as an argument.
___
*[geometry/render/dev/http_service.h, line 99 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxavIQb1-G09FbDLOnE:-MxavIQb1-G09FbDLOnF:b-pxq42x) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca785596126044dff1dbb6c8a9c204394400cf2/geometry/render/dev/http_service.h#L99)):*
> ```objc
>    @throws std::logic_error
>      If the provided `url` is empty, or has any trailing slashes. */
>   explicit HttpService(const std::string& temp_directory,
> ```

nit: this is a C++ question. Do we need the `explicit` keyword here as there are multiple args and none of them have a default value? Can this constructor be used for implicit conversion?
___
*[geometry/render/dev/http_service.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxB_rNbBAehYmzJtTos:-MxbNDnA3Sc30mXdqgyZ:b-ja9g4f) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.cc#L45)):*
> Checking the directory permissions may not always reveal whether you can actually write to the directory. 
Is this true? I would agree if we can avoid doing this "manual" test in the code.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16702)* status: 1 unresolved discussion, LGTM missing from assignee zachfang (waiting on @zachfang)

___
*[geometry/render/dev/http_service.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxB_rNbBAehYmzJtTos:-MxeNDJzE61mImym1USF:b-pix3qc) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.cc#L45)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

There's a [good SO answer here](https://stackoverflow.com/a/12566600) explaining some of it, the answer below it is what I tend to agree with -- the best way to actually know if you can write to / read from somewhere is to just try and actually do it.  Otherwise, for this scenario, we need to check `-wx` or `rwx`, for owner, group, and others, and officially would need to verify whether our process running is owner, group, or other to validate against (the latter, what the permissions of our process is, being something I'm not sure how to do correctly).

The comment is poorly worded, I updated it to reflect my belief: actual creation / readback is the most straightforward to validate we can use the directory.  That said, if there is a preference to figure out the right way to do it using permissions checks I am happy to do so.
</blockquote></details>

We just met on this, the other possible alternative is to use the [`access()` function](https://pubs.opengroup.org/onlinepubs/009695299/functions/access.html) and check both `W_OK` and `X_OK` (since this is a directory, and `R_OK` is not relevant).  Permissions are only one component of the story, things like SELinux may also come into play.

Let me know whether you prefer the updated comment, or something different.

**Review by zachfang — COMMENTED** [review]
:lgtm: pending on the `ThrowIfInvalidTempDirectory` discussion.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16702#-:-MxezKdZ6dhLE2DS80ou:bkkhqh)* status: 1 unresolved discussion (waiting on @svenevs)

___
*[geometry/render/dev/http_service.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxB_rNbBAehYmzJtTos:-Mxeyz_92_wPO6Zrygpy:b-gb3jki) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.cc#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There are two valid approaches here:

(1) Something like the code as-written.  To check if a temp directory is valid, the best answer is to write to it.  We can nitpick a few style things above, but the overall approach is fine.

(2) Give up and don't try to fail-fast in the constructor.  Throw during http calls later on, in case the directory was invalid (or became invalid).  Since the value is always just a `drake::temp_directory` anyway, the chance that it's invalid at construction-time seems very low.
</blockquote></details>

LGTM. Either option works for me with my slight preference over the second option.

**Review by svenevs — COMMENTED** [review]
:lgtm: provided CI for latest push passes.

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16702#-:-MxfEDCW07h9YriTHuna:b-2naflt)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @svenevs)

___
*[geometry/render/dev/http_service.h, line 83 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxfDdXyASeA8gv8q-mB:-MxfDdXyASeA8gv8q-mC:b-lc3xo2) ([raw file](https://github.com/robotlocomotion/drake/blob/db9af898a3cd81f62cf301dce412e4b0cff6ad8c/geometry/render/dev/http_service.h#L83)):*
> ```objc
>      for deleting it.  No validity checks on this directory are performed,
>      concrete derived classes are responsible for verifying that any temporary
>      files needed can be created.
> ```

FYI `HttpServiceCurl` already validates that temporary files created before passing off to libcurl write callbacks are valid, throwing an exception if not usable.
___
*[geometry/render/dev/http_service.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16702#-MxB_rNbBAehYmzJtTos:-MxfDq4s-MUfmcVZPWdm:bz0livh) ([raw file](https://github.com/robotlocomotion/drake/blob/e70caaf315d39bd6be686169d0c6b83c2fd671d3/geometry/render/dev/http_service.cc#L45)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

LGTM. Either option works for me with my slight preference over the second option.
</blockquote></details>

Done, went with option (2) and removed the fail-fast.  Updated associated docs and removed related test cases.

**Review by svenevs — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16702#-:-MxfNXKW6P5dL0VoCu2X:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @svenevs)

**Pull request merged**
