### PR TITLE
add screw joint

### PR DESCRIPTION
**Pull request by wf34**
Adds a 1 dof screw joint that allows motion along and rotation about the z-axis of the parent frame.

Depends on  #15104
Towards #12404
@mpetersen94

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
Assigning +@sherm1 for either feature review, or delegation to another reviewer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105#-:-Mb8QhBuCarlYiYzyHgO:b7sru5l)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Same comments here as for #15104. Added "WIP" to the title and set do not review.
+(status: do not review) +(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105#-:-MbIGQr0AqBjfxD9wvpn:bebuwkl)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @sherm1)

**Comment by wf34** [comment]
Converted to 1 dof, ready for review.

**Comment by sherm1** [comment]
@drake-jenkins-bot ok to test

**Review by sherm1 — COMMENTED** [review]
Checkpoint. Thanks for doing this @wf34! Lots of comments but this is looking very good. Keep going!

I'll stop here for now, pending fixes to #15104 and here. Note CI failures -- GitHub will now run CI whenever you push a commit.

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105#-:-McHCY5iAZvUuo_GdzVA:b9un49k)* status: 17 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1 and @wf34)

___
*[multibody/tree/screw_joint.h, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH4J9E1BrsHef2xOxQ:-McH4J9E1BrsHef2xOxR:b-lue1fs) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L22)):*
> ```objc
> /// That is, given a frame F attached to the parent body P and a frame M
> /// attached to the child body B (see the Joint class's documentation), this
> /// joint allows frame M to translate (while rotating) along the z axis of frame F,
> ```

nit: line length
___
*[multibody/tree/screw_joint.h, line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH4Xbo6QElKLhpDwVA:-McH4Xbo6QElKLhpDwVB:b-inhkxk) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L50)):*
> ```objc
>   /// joint position, velocity and acceleration limits are the pair `(-∞, ∞)`.
>   /// These can be set using the Joint methods set_position_limits(),
>   /// set_velocity_limits() and set_acceleration_limits().
> ```

minor: need to be clear that these have angular units, not length units.
___
*[multibody/tree/screw_joint.h, line 56 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH7H3U5cXfqV2dqL4n:-McH7H3U5cXfqV2dqL4o:b-fgzoj0) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L56)):*
> ```objc
>   /// @param[in] screw_pitch
>   ///   Amount of translation in meters occuring over a one full revolution.
>   ///   See documentation of ScrewMobilizer for the details.
> ```

"Mobilizer" is an internal concept so can't be used in the Joint documentation. "Joint" is the user-visible concept.
___
*[multibody/tree/screw_joint.h, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH4rxFCG9OsM6YOA2j:-McH4rxFCG9OsM6YOA2k:b3amnpd) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L60)):*
> ```objc
>   ///   Viscous damping coefficient, N⋅m⋅s for
>   ///   rotation, used to model losses within the joint. See documentation of
>   ///   damping() for details on modelling of the damping torque.
> ```

minor: should make it clear that the damping coefficient applies to the rotation rate, not the translation rate.

Also, please consider mentioning (somewhere) that the screw pitch is given in meters / _revolution_ while the damping is given as torque / (_radian_ / s), **not** _revolution_ / s.
___
*[multibody/tree/screw_joint.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH57bPDrh_biTcZGZq:-McH57bPDrh_biTcZGZr:b-nqv2p9) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L65)):*
> ```objc
>               const Frame<T>& frame_on_child,
>               double screw_pitch, 
>               double damping)
> ```

Not clear to me why these are `double` rather than `T`. @amcastro-tri @joemasterjohn would T be better here?
___
*[multibody/tree/screw_joint.h, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH5X4R3_cWdj1FPnzw:-McH5X4R3_cWdj1FPnzx:b1bekj3) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L81)):*
> ```objc
>       , screw_pitch_{screw_pitch}
>       , damping_{damping} {
>     DRAKE_THROW_UNLESS(damping >= 0);
> ```

minor: looks like any pitch is OK here but the mobilizer is more restrictive. See my comments in the mobilizer PR -- I think it is better as you've done it here (but you have to be careful with pitch=0).
___
*[multibody/tree/screw_joint.h, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McHBJvB3pC_Ht27LEPf:-McHBJvB3pC_Ht27LEPg:b-p21uj0) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L94)):*
> ```objc
> 
>   /// Returns `this` joint's damping constant N⋅m⋅s for the rotational degree.
>   /// The damping torque (in N⋅m) is modeled as `τ = -damping₂⋅ω` i.e.
> ```

nit: spurious subscript 2 ?
___
*[multibody/tree/screw_joint.h, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH5udg43DedDfHUuJA:-McH5udg43DedDfHUuJB:b2fl5xb) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L103)):*
> ```objc
>   /// @{
> 
>   /// Gets the position of `this` joint from `context`.
> ```

nit: position -> translation
___
*[multibody/tree/screw_joint.h, line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH60_8CMb2YBKWjpEI:-McH60_8CMb2YBKWjpEJ:bhog1yn) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L106)):*
> ```objc
>   ///
>   /// @param[in] context The context of the model this joint belongs to.
>   /// @retval p_FoMo_F The position of `this` joint stored in the `context`
> ```

minor: this name isn't right -- that's a vector. This method returns a scalar. You could say pz_FoMo_F (the z coordinate of that vector). But consider using a simpler and more conventional name for the translation scalar, like `x` (or `z`?) so that the joint motion can be described with a rotation θ and translation x, with x=p θ / 2π. 
___
*[multibody/tree/screw_joint.h, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH8Lxm8aKMeLu2pw9s:-McH8Lxm8aKMeLu2pw9t:bhjbc39) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L115)):*
> ```objc
>   ///
>   /// @param[in] context The context of the model this joint belongs to.
>   /// @param[in] p_FoMo_F The desired position in meters to be stored in
> ```

This notation is wrong for a scalar (see other comment).
___
*[multibody/tree/screw_joint.h, line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH8cImBJoHBr8wXSuu:-McH8cImBJoHBr8wXSuv:b-84mqak) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L146)):*
> ```objc
>   }
> 
>   /// Gets the translational velocity v_FoMo_F, in meters per second, of `this`
> ```

Same comment -- this notation represents a vector but you are working with a scalar here. Should be parallel to your comments about the angle θ. I suggest a single-letter notation, `z` could be best and you did use that occasionally in the mobilizer documentation. 

This should be fixed everywhere but I won't write separate comments.
___
*[multibody/tree/screw_joint.h, line 205 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH9SGf2Xy3tkoghCGa:-McH9SGgAuTqb12sIXUr:b-au4ukh) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L205)):*
> ```objc
>   /// Sets the default position of this joint.
>   /// @param[in] p_FoMo_F The desired default position of the joint
>   void set_default_translation(const double& p_FoMo_F) {
> ```

minor: the comments need to make it clear that these methods are not independent. If someone calls set_default_translation() and then set_default_rotation() the translations will be overwritten.
___
*[multibody/tree/screw_joint.h, line 224 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH9fIvCqLL9o1B-80b:-McH9fIvCqLL9o1B-80c:bqwbgcs) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L224)):*
> ```objc
>   /// Sets the random distribution that the position and angle of this
>   /// joint will be randomly sampled from. See class documentation for details
>   /// on the definition of the position and angle.
> ```

minor: we use "position" generically to mean generalized coordinate q (could have any units). You should use translation and angle consistently instead. This method should be more specific about the distribution -- I presume it is applied only to the generalized coordinate, which is an angle?
___
*[multibody/tree/screw_joint.h, line 232 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McHA1MY0AB7ynJsn6aC:-McHA1MY0AB7ynJsn6aD:blld8tq) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L232)):*
> ```objc
> 
>  private:
>   /// Joint<T> override called through public NVI, Joint::AddInForce().
> ```

minor: don't use Doxygen `///` comments in a private section; we don't run those through Doxygen. Just use `//` or `/* ... */`.
___
*[multibody/tree/screw_joint.h, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McHAL4915grui16ugbz:-McHAL4915grui16ugc-:b-dc82fc) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L234)):*
> ```objc
>   /// Joint<T> override called through public NVI, Joint::AddInForce().
>   /// Therefore arguments were already checked to be valid.
>   /// For a ScrewJoint, we must always have `joint_dof < 1` since there is
> ```

BTW would be clearer to say `joint_dof == 0`
___
*[multibody/tree/screw_joint.h, line 236 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McHATe15PjPHP660ORL:-McHATe15PjPHP660ORM:b-dt4skp) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L236)):*
> ```objc
>   /// For a ScrewJoint, we must always have `joint_dof < 1` since there is
>   /// one degree of freedom (num_velocities() == 1). `joint_tau` is the torque
>   ///   about the z-axis of the parent frame F if `joint_dof = 0`.
> ```

nit: odd indent
___
*[multibody/tree/screw_joint.h, line 242 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McHAgU6C5KPQZbkpyP_:-McHAgU6C5KPQZbkpyPa:b-t1846q) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L242)):*
> ```objc
>   /// torque is defined to be positive according to the right hand rule about
>   /// the selected axis. That is, a positive force causes a positive
>   /// translational acceleration and a positive torque causes a positive angular
> ```

minor: add "(assuming positive pitch)"

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105)* status: 17 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @joemasterjohn, @sherm1, and @wf34)

___
*[multibody/tree/screw_joint.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McH57bPDrh_biTcZGZq:-McK3Uhp0PgEvYyfrZMp:b-xs7ovs) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef311c244b15c1822b2737ba02bff5abda3a08/multibody/tree/screw_joint.h#L65)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Not clear to me why these are `double` rather than `T`. @amcastro-tri @joemasterjohn would T be better here?
</blockquote></details>

from the very beginning every MultibodyElement in MultibodyPlant takes `<double>` constructor parameters that provide the "default" value (see RigidBody, RevoluteJoint, FixedOffsetFrame, etc). Parameter values in `Context<T>` can be set through specific APIs in each of these elements, that's @joemasterjohn's latest greatest addition.

**Comment by wf34** [comment]
> Not clear to me why these are double rather than T

I've addressed similar question with a greater detail in the mobilizer PR(#15104)

Other issues raised so far were attended to.

Thank you for you time, @sherm1!

**Review by sherm1 — COMMENTED** [review]
Checkpoint.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105#-:-McjuEq_92DnkEh7faK7:by96gdd)* status: 12 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @wf34)

___
*[multibody/tree/screw_joint.h, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-Mcjr__m52oo3dQLkJIq:-Mcjr__m52oo3dQLkJIr:b-dt4skp) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L23)):*
> ```objc
> /// attached to the child body B (see the Joint class's documentation), this
> /// joint allows frame M to translate (while rotating) along the z axis
> ///   of frame F, with M's z-axis Mz and F's z-axis Fz coincident at
> ```

nit: odd indent
___
*[multibody/tree/screw_joint.h, line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McjrfEOEptyIptLI45C:-McjrfEOEptyIptLI45D:b-dt4skp) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L49)):*
> ```objc
>   /// This constructor signature creates a joint with no joint limits, i.e. the
>   /// joint angular position, angular velocity and angular acceleration limits
>   ///   are the pair `(-∞, ∞)`.
> ```

nit: odd indent
___
*[multibody/tree/screw_joint.h, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McjrieV4GcUnIF7eYW3:-McjrieV4GcUnIF7eYW4:b-dt4skp) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L52)):*
> ```objc
>   /// These can be set using the Joint methods set_position_limits(),
>   /// set_velocity_limits() and set_acceleration_limits() in radians,
>   ///   radians/sec, radians/sec^2 units.
> ```

nit: odd indent
___
*[multibody/tree/screw_joint.h, line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McjsXHlCEu9X4t2R6qS:-McjsXHlCEu9X4t2R6qT:b-xweta6) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L58)):*
> ```objc
>   /// @param[in] screw_pitch
>   ///   Amount of translation in meters occuring over a one full
>   ///   screw revolution.
> ```

minor: now that you're allowing any value for screw_pitch, should document that and mention limitation when pitch ≈ 0.
___
*[multibody/tree/screw_joint.h, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-Mcjs-2ECQiupaQRnuAJ:-Mcjs-2ECQiupaQRnuAK:b-4suhty) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L60)):*
> ```objc
>   ///   screw revolution.
>   /// @param[in] damping
>   ///   Viscous damping coefficient, N⋅s/rad for
> ```

minor: this is a torque so should have units of N⋅m⋅s/rad.
___
*[multibody/tree/screw_joint.h, line 108 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-Mcjt-LEAidjimROJIEA:-Mcjt-LEAidjimROJIEB:b3poxko) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L108)):*
> ```objc
>   ///
>   /// @param[in] context The context of the model this joint belongs to.
>   /// @retval z        The translation of `this` joint stored in the `context`
> ```

nit: odd spacing
___
*[multibody/tree/screw_joint.h, line 117 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-Mcjt4Uo6wPf4FEbhVKa:-Mcjt4UpAoOCMHxP4fD4:b3poxko) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L117)):*
> ```objc
>   ///
>   /// @param[in] context The context of the model this joint belongs to.
>   /// @param[in] z        The desired translation in meters to be stored in
> ```

nit: odd spacing
___
*[multibody/tree/screw_joint.h, line 163 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McjtHkw5KeFTwUrefGw:-McjtHkw5KeFTwUrefGx:b3poxko) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L163)):*
> ```objc
>   /// @param[in] context The context of the model this joint belongs to.
>   /// @param[in] vz       The desired translational velocity of `this` joint in
>   ///                     meters per second along F frame's Z-axis.
> ```

nit: odd spacing
___
*[multibody/tree/screw_joint.h, line 199 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McjtK3A2JZyBtB55-k4:-McjtK3A2JZyBtB55-k5:bm9vx5r) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L199)):*
> ```objc
> 
>   /// Gets the default position for `this` joint.
>   /// @retval z        The default position of `this` joint.
> ```

nit: odd spacing (more below, I won't note them individually)
___
*[multibody/tree/screw_joint.h, line 205 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McjtXKr5W4quCSVMN4j:-McjtXKr5W4quCSVMN4k:b2fl5xb) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L205)):*
> ```objc
>   }
> 
>   /// Sets the default position of this joint. This will change
> ```

nit: position -> translation
___
*[multibody/tree/screw_joint.h, line 208 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-Mcjtb9MEg1jRXSjow8A:-Mcjtb9MEg1jRXSjow8B:b-4knkk7) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L208)):*
> ```objc
>   /// the `default_rotation` too, which are not independent in this joint.
>   /// @param[in] z        The desired default position of the joint
>   void set_default_translation(const double& z) {
> ```

nit: should note that this method will throw for near-zero pitch
___
*[multibody/tree/screw_joint.h, line 337 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-Mcju8m9975t5x_Ubp18:-Mcju8m9975t5x_Ubp19:bxntulw) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/screw_joint.h#L337)):*
> ```objc
>   // The amount of translation in meters occuring over a one full revolution.
>   double screw_pitch_;
>   // This joint's damping constant in N⋅s/rad for rotation.
> ```

minor: N⋅m⋅s/rad

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending a few comments.
@mpetersen94 do you want to take a look at this?

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105#-:-MckEOsO1WD1KNk5rHLW:b-xaxq63)* status: 13 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @wf34)

___
*[multibody/tree/test/screw_joint_test.cc, line 241 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15105#-MckEEFV0xOCkHsq8fLf:-MckEEFV0xOCkHsq8fLg:bfi1xe4) ([raw file](https://github.com/robotlocomotion/drake/blob/d641a648e22d21d566377520da5512f63976fcc2/multibody/tree/test/screw_joint_test.cc#L241)):*
> ```cpp
>   tree().SetRandomState(*context_, &context_->get_mutable_state(), &generator);
>   EXPECT_NE(mutable_joint_->get_translation(*context_), last_translation);
>   EXPECT_NE(mutable_joint_->get_rotation(*context_), last_rotation);
> ```

minor: these const methods shouldn't be using `mutable_joint_` (8 occurrences)

**Review by sherm1 — COMMENTED** [review]
CI failed due to minor lint stuff -- please fix.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105#-:-MckEqYD6H-FAbdikOpD:bt0r1du)* status: 13 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @wf34)

**Comment by wf34** [comment]
>#include "drake/multibody/tree/screw_mobilizer.h"

The CI's issue with this line won't arise, when PR #15104 is merged.

I'm ready to squash commits, when the review is finalized.

**Comment by sherm1** [comment]
FYI You can squash any time -- Reviewable keeps track of revisions independently of commits. I will be able to see just your new changes either way.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending CI success (apparently requires #15104 to merge first).
+@soonho-tri for platform review per revised rotation, please

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105#-:-Mcv7AUc7g1JhyL6bUzx:buimhnl)* status: 2 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @soonho-tri and @wf34)

___
*[multibody/tree/screw_joint.h, line 209 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-Mcv73lgCAJv5fxowq81:-Mcv73lgCAJv5fxowq82:b2fl5xb) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/screw_joint.h#L209)):*
> ```objc
>   /// Sets the default translation of this joint. This will change
>   /// the `default_rotation` too, which are not independent in this joint.
>   /// @param[in] z The desired default position of the joint
> ```

nit: position -> translation
___
*[multibody/tree/screw_joint.h, line 210 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-Mcv71NEBs7DGFgaFiE3:-Mcv71NF3DxcWkYP_KPr:b-dt4skp) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/screw_joint.h#L210)):*
> ```objc
>   /// the `default_rotation` too, which are not independent in this joint.
>   /// @param[in] z The desired default position of the joint
>   ///   @throws std::exception if pitch is very near zero.
> ```

nit: odd indent

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105)* status: 7 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @wf34)

___
*[multibody/tree/screw_joint.h, line 113 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McyOkvP1D8gBp0heYS3:-McyOkvQBHAbGC7JhP10:b-99soa4) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/screw_joint.h#L113)):*
> ```objc
>   /// @retval z The translation of `this` joint stored in the `context` as (z).
>   ///           See class documentation for details.
>   const T get_translation(const Context<T>& context) const {
> ```

nit, `const T` => `T` 
___
*[multibody/tree/screw_joint.h, line 135 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McyNdjvB6izb33_CXI6:-McyNdjvB6izb33_CXI7:ba83rhg) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/screw_joint.h#L135)):*
> ```objc
>   ///               documentation for details.
>   const T& get_rotation(const systems::Context<T>& context) const {
>     return get_mobilizer()->get_angle(context);
> ```

`ScrewMobilizer::get_angle`'s return type is `T` instead of `const T&`. As a result, this returns a reference to local temporary object, which should be fixed.
___
*[multibody/tree/screw_joint.h, line 155 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McyOvCe5-xnjUqnd7Vy:-McyOvCe5-xnjUqnd7Vz:b-99soa4) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/screw_joint.h#L155)):*
> ```objc
>   /// @retval vz The translational velocity of `this` joint as stored in the
>   ///            `context`.
> const T get_translational_velocity(
> ```

nit, `const T` => `T` 
___
*[multibody/tree/screw_joint.h, line 181 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McyNyt9A5go1WBy86NZ:-McyNyt9A5go1WBy86N_:b-lfzbc8) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/screw_joint.h#L181)):*
> ```objc
>   ///                   stored in the `context`.
>   const T& get_angular_velocity(const systems::Context<T>& context) const {
>     return get_mobilizer()->get_angular_rate(context);
> ```

`ScrewMobilizer::get_angular_rate`'s return type is `T` instead of `const T&`. As a result, this returns a reference to local temporary object, which should be fixed.
___
*[multibody/tree/test/screw_joint_test.cc, line 230 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McvFdPG1rGOvw0ZO7MM:-McvFdPG1rGOvw0ZO7MN:b-7rf23l) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/test/screw_joint_test.cc#L230)):*
> ```cpp
>   EXPECT_GE(joint_->get_rotation(*context_), 1.0);
>   EXPECT_LE(joint_->get_rotation(*context_), 2.0);
>   
> ```

nit, unnecessary whitespace.

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105)* status: 8 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @wf34)

___
*[multibody/tree/test/screw_joint_test.cc, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McyQ4YX3EpE4YuF3VPJ:-McyQ4YX3EpE4YuF3VPK:b-lx2suk) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/test/screw_joint_test.cc#L9)):*
> ```cpp
> #include "drake/common/eigen_types.h"
> #include "drake/multibody/tree/screw_joint.h"
> #include "drake/multibody/tree/rigid_body.h"
> ```

nit, you need to reorder this to make the Drake's linter happy:

```diff
 #include "drake/common/eigen_types.h"
-#include "drake/multibody/tree/screw_joint.h"
 #include "drake/multibody/tree/rigid_body.h"
+#include "drake/multibody/tree/screw_joint.h"
```

**Review by wf34 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105)* status: 2 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @soonho-tri)

___
*[multibody/tree/screw_joint.h, line 135 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McyNdjvB6izb33_CXI6:-MczLbJUDG1v76ZSxllT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/screw_joint.h#L135)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`ScrewMobilizer::get_angle`'s return type is `T` instead of `const T&`. As a result, this returns a reference to local temporary object, which should be fixed.
</blockquote></details>

Done.
___
*[multibody/tree/screw_joint.h, line 181 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15105#-McyNyt9A5go1WBy86NZ:-MczLrsm81sfeUuoIZqd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc079425d4434bd8d4b5f091a3d60d2478e1c4f/multibody/tree/screw_joint.h#L181)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`ScrewMobilizer::get_angular_rate`'s return type is `T` instead of `const T&`. As a result, this returns a reference to local temporary object, which should be fixed.
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
FYI, I'll revisit this one when #15104 is merged.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105#-:-MczMeFR-QRuVyf-7-Fe:bqg1xlb)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @wf34)

**Comment by soonho-tri** [comment]
@wf34 , I tried to rebase this PR on the latest `master` but made a mistake and this PR is closed by accident. Could you update your branch, `feature/wf34/screw_joint` and check if you can reopen this PR? (for now, it says I don't have permission to update your branch any more).

**Comment by wf34** [comment]
>Could you update your branch, and check if you can reopen this PR? 

Soonho, certainly!

**Comment by wf34** [comment]
@soonho-tri, I've updated the branch `feature/wf34/screw_joint` but the PR couldn't be reopened.
I can open a new, which will tag this one.
It is not the case that we had long and complex agruments in the review, so a disrupted discussion history seems not critical.

**Comment by soonho-tri** [comment]
No problem. Now I can re-open it! (just did).

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105#-:-Md1xD263n3mL8SdNgGA:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),sherm1(platform) (waiting on @wf34)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15105)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),sherm1(platform) (waiting on @wf34)

**Pull request merged**
