### PR TITLE
Changed Post-Increment to Pre-Increment in RigidBodyTree

### PR DESCRIPTION
**Pull request by liangfok**
This PR also adds a missing CHANGELOG entry.

This should not be reviewed until after #3157 is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3169)

### CODE REVIEW

**Comment by liangfok** [comment]
Since this PR passed pre-merge CI and it touches `RigidBody*`:

+@amcastro-tri for feature review.
+@sherm1 for platform review.

Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPV2tUpBls05N0mNXQ8:bws0ahi)*

**Comment by liangfok** [comment]
FTR, the motivation for using double characters to represent single character variables is given here: https://reviewable.io/reviews/robotlocomotion/drake/3157#-KPNkLF-DcM7eQxYC_SE

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPV3XFBcfkNW5qQU3pZ:bks9687)*

**Comment by sherm1** [comment]
I am opposed to this change. There is nothing more conventional in C-like code than `for (int i=0; i < something; ++i)`. Changing those to `ii` hurts my eye-eyes.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPV51V3cpecz9k1NVYK:b-w6y59f)*

**Comment by liangfok** [comment]
I assert that (1) the single letter loop counters hurt _my_ eyes, (2) `i` and `ii` are equally meaningless, and (3) this is a strict improvement since it enables more IDEs to work with the code.

However, since I jave a feeling I am being out voted here I will revert. :smiley: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPV8DXovPKc0vBs3PHO:b-ne63ry)*

**Comment by liangfok** [comment]
Actually, how about a compromise: what if I change the `i` to `loop_index`?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPV9YVbIxo13UVRKUXU:b3vdt2d)*

**Comment by jwnimmer-tri** [comment]
`loop_index` is even worse than `ii`; the point is to be short and meaningless.

**Comment by jwnimmer-tri** [comment]
I may also be informative to explain how Sublime suffers from one-letter variables?

(Maybe it doesn't parse C++, so can't do "show me all the places this is used in the function"?  In which case the problem is 300-line functions, not the loop indices.)

**Comment by liangfok** [comment]
You're right! Native Sublime Text does not "understand" C++ in terms of knowing what is a variable, function, class, etc. It can only guess what a variable is based on string comparison. That's why single-character variables are so problematic -- they match numerous places that aren't actually the variable resulting in too many false positives.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPVPHgaU1ewA__AylNT:b-kgo6ca)*

**Comment by jwnimmer-tri** [comment]
FWIW -- by default, emacs has the same behavior, and I survive.  If I'm really hurting, I'll use a regexp to isolate the `i`, e.g., `\Wi\W`, but mostly I just grumble at the overly-long function, and sometimes refactor it to either be smaller, or have more narrowly scoped variables, or something.  I fully admit that RBT is particularly awful in this regard, but I'm not sure that `ii` is really a good path to fixing it.

**Comment by liangfok** [comment]
OK I retreat. I'll revert the `ii` index variables to be `i`. 😃

**Comment by liangfok** [comment]
Despite great anguish :wink: , I removed the double-character solution to what I perceive to be a single-character-variable "problem". 

FTR, I picked up my ideology & solution from a previous project that strictly enforced a "no single character variable" policy.

PTAL.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPVdLWJD_9WeJQwXm3j:b4my579)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPVoi7wyq6tadAVurLs:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Now waiting on a feature review from @amcastro-tri.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPVq7wyXmz2ANs1uAmq:bu1h2zn)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r10.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169#-:-KPYt-Kd_-lCtQu2b0rk:bnfp4nl)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 2 files at r10.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3169)*

**Pull request merged**
