### PR TITLE
Allow incomplete derivatives, signaling with NaN at evaluation-time where possible

### PR DESCRIPTION
**Pull request by ggould-tri**
Relates #8648.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@soonho-tri 
FYI @avalenzu @sherm1 @jwnimmer-tri  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514#-:-MQmq4k89ICeqrSY60JF:brk3c9b)* status: LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @soonho-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 2 unresolved discussions, LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri and @soonho-tri)

___
*[common/symbolic_expression_cell.cc, line 1751 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmtJh681CPxeU1cRPd:-MQmtJh681CPxeU1cRPe:byrhl6g) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1751)):*
> ```cpp
>     const Expression& arg{get_argument()};
>     // FYI:  'ceil(x) - floor(x) == 0` is the same as `x % 1 == 0`.
>     return if_then_else(ceil(arg) - floor(arg) == 0,
> ```

nit Wouldn't `ceil(arg) == floor(arg)` be simpler and clearer?
___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQmsrs86npBgB3RNIXX:b8wv9cz) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
> ```cpp
>     // TODO(ggould-tri): This does not return NaN as promised when the
>     // condition is exactly on the boundary between true and false, and it's
>     // not clear how it would.
> ```

This is interesting.  I'd like to take a little time to ponder.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri, @jwnimmer-tri, and @soonho-tri)

___
*[common/symbolic_expression_cell.cc, line 1751 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmtJh681CPxeU1cRPd:-MQmvNb72zdoth3TXcuR:bnd3hag) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1751)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Wouldn't `ceil(arg) == floor(arg)` be simpler and clearer?
</blockquote></details>

OK: :facepalm:

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri and @soonho-tri)

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @soonho-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQmveO4DswBdV1qAZvu:b-tnn6kp) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is interesting.  I'd like to take a little time to ponder.
</blockquote></details>

I'd love to hear any ideas you have -- I hit a bit of a wall with this.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri and @soonho-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQn-7_yE1Nw6lodnW-A:bsx7754) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I'd love to hear any ideas you have -- I hit a bit of a wall with this.
</blockquote></details>

One simple answer is to only check `f_cond_.GetVariables().include(x)` instead of the larger `this->GetVariables.include(x)` -- we could allow `x` in the sub-expressions, but disallow it in the formula.  I think that doesn't lose us any correctness, but might solve some user complaints.

Would that be a sufficient change for now?

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @soonho-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQn0PCA7XyjEGwLJF07:b-7ggqbm) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

One simple answer is to only check `f_cond_.GetVariables().include(x)` instead of the larger `this->GetVariables.include(x)` -- we could allow `x` in the sub-expressions, but disallow it in the formula.  I think that doesn't lose us any correctness, but might solve some user complaints.

Would that be a sufficient change for now?
</blockquote></details>

That would break the implementations of all of the other functions in this PR (min, max, abs, etc.) that switch on their argument.

**Comment by jwnimmer-tri** [comment]
___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQn171o6ECkpvQm9I9o:b8bl5pm) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

That would break the implementations of all of the other functions in this PR (min, max, abs, etc.) that switch on their argument.
</blockquote></details>

Only for second derivatives, though?

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @soonho-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQn1uNG8JIG7TIQbmF4:bw789ly) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Only for second derivatives, though?
</blockquote></details>

Ah true.  It breaks my use case that motivated picking up this issue in the first place, but perhaps I can rewrite my use case in terms of min/max on Friday.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514#-:-MQn5rIZ5-lmsxEImtGI:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri and @jwnimmer-tri)

___
*[common/symbolic_expression_cell.cc, line 1271 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQn5ajr2KUM2g-224KR:-MQn5ajr2KUM2g-224KS:b-ycuo67) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1271)):*
> ```cpp
>   if (GetVariables().include(x)) {
>     const Expression& arg{get_argument()};
>     return if_then_else(arg < 0, -arg.Differentiate(x),
> ```

nit, `arg.Differentiate(x)` can be an expensive operation. Can we compute the result once and re-use it in both branches?

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri and @jwnimmer-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQn64RS0E-L6u9tnOxW:bk5p9tg) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Ah true.  It breaks my use case that motivated picking up this issue in the first place, but perhaps I can rewrite my use case in terms of min/max on Friday.
</blockquote></details>

Ah, I can do better!  If `Formula.is_relational` then the discontinuity is known!

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri and @jwnimmer-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQn6_2d2e9cIwyaI86z:b39i472) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
> If Formula.is_relational then the discontinuity is known!

:+1:

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri and @soonho-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQn2gnvBuhFrSPAweJd:b-6cuxh8) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> If Formula.is_relational then the discontinuity is known!

:+1: 
</blockquote></details>

I guess I don't object in principle to carving out special cases, since all of the "handle more situations" changes here are along those lines, but I don't particularly love the idea here of teaching Expression about Formula's discontinuities by peeking into one of its enumerated possible cases.  Fundamentally, we need a new method on Formula to assist this operation, by helping report where things have boundaries wrt `x`.  I'm working on writing up what that should be.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQn9D8dEiy3EK7KFvy0:b5sb99t) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I guess I don't object in principle to carving out special cases, since all of the "handle more situations" changes here are along those lines, but I don't particularly love the idea here of teaching Expression about Formula's discontinuities by peeking into one of its enumerated possible cases.  Fundamentally, we need a new method on Formula to assist this operation, by helping report where things have boundaries wrt `x`.  I'm working on writing up what that should be.
</blockquote></details>

Strong agree -- Formula knows best.  I'm inclined to implement the special case here for now and TODO to what you write up in order to keep this PR footprint small, though.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: needs at least two assigned reviewers (waiting on @soonho-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQnDMzcCy8Ql2ZmFs9T:b74nf0x) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Strong agree -- Formula knows best.  I'm inclined to implement the special case here for now and TODO to what you write up in order to keep this PR footprint small, though.
</blockquote></details>

I figured that's where we would end up in this PR.  But in that case, this PR should not close the issue.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514)* status: needs at least two assigned reviewers (waiting on @soonho-tri)

___
*[common/symbolic_expression_cell.cc, line 1873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14514#-MQmsrs86npBgB3RNIXW:-MQnGPNA3V8V2Z_LbDF7:b-b64dj) ([raw file](https://github.com/robotlocomotion/drake/blob/d6bbf6d6d872438d1cb9a03c0291de1e69bd934c/common/symbolic_expression_cell.cc#L1873)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I figured that's where we would end up in this PR.  But in that case, this PR should not close the issue.
</blockquote></details>

Roger roger.  Comment updated.

**Review by sherm1 — COMMENTED** [review]
:lgtm: (drive by)

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514#-:-MQo0W3L36nlh8rS4Bn6:b-zbexct)* status: needs at least two assigned reviewers

**Review by ggould-tri — COMMENTED** [review]
+@rpoyner-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514#-:-MQrGj333nXNyFvA-aZH:ba0u6f9)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14514#-:-MQrUf8k3insdAg2_mpD:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),soonho-tri(platform)

**Pull request merged**
