### PR TITLE
Modifies variable name to match Doxygen description in maliput::utility::GenerateUrdfFile.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5160)

### CODE REVIEW

**Comment by liangfok** [comment]
+@maddog-tri for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5160#-:-Kctxv8Wi6TehSEm5e2l:b-5klkw7)*

**Comment by maddog-tri** [comment]
:lgtm:  Thanks for catching this.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5160#-:-KcvaMcjNWVGxSCtJpt2:b-lbfl2k)*

**Comment by liangfok** [comment]
+@david-german-tri  for platform review please. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5160#-:-KcwHsd8qpm0SLbvlbws:b-agp6rf)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5160#-:-Kcx8JN3gaWEmsQOUqct:bnfp4nl)*

**Pull request merged**
