### PR TITLE
Combine drake_assert.cc and drake_throw.cc

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Having both implementations in a single file will allow them to mix and match what they need as the line between assertions and exceptions blurs.

This is a non-functional change; the cut-n-paste code is unchanged.

Towards #5268.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6158)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Hmm, I forgot to change CMakeLists, didn't I?  Will fix momentarily.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for all review, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6158#-:-Kkq3sA7kqNM0tGxiPRt:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
The build showing up as "in progress" has passed successfully; some update message must have gotten lost.  Using override-merge.

**Pull request merged**
