### PR TITLE
Make drake's buildifier wrapper compatible with vscode

### PR DESCRIPTION
**Pull request by ggould-tri**
vscode's bazel extension checks that its configured buildifier behaves correctly when passed content on stdin.  Drake's buildifier wrapper doesn't handle that case.

 * Make drake's buildifier wrapper handle taking its input on stdin
 * Add a test that mimics vscode's validity check at https://github.com/bazelbuild/vscode-bazel/blob/master/src/buildifier/buildifier_availability.ts

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21254)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Did you intend to assign anyone for review? @jwnimmer-tri, @sammy-tri, myself, or others?

**Comment by ggould-tri** [comment]
I solicited reviewers on the #vscode slack channel, but nobody has jumped on it.  Ideally the feature reviewer would be someone who uses vscode.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for feature.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21254#-:-Nueo0uX3J3SFcb_hsux:bebawnu)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @ggould-tri)

**Comment by jwnimmer-tri** [comment]
I don't think we should do this feature this way.  This particular command is intended for developers to run on the command line, not as a stand-in for the `buildifier` binary from upstream.

If we just need a little shell wrapper script that curries out dotfile onto the upstream `buildifier`, we should write that and teach VSCode how to call _that_.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'm going to defer review for the previous comment to be resolved.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21254#-:-NuyElH07o_xMiEJfSu2:b-r4tvh1)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @ggould-tri)

**Comment by ggould-tri** [comment]
Yeah, on "reviewer gets the benefit of the doubt" grounds, I'm closing this PR.  I've clearly misunderstood the design objective of this wrapper.

**Pull request closed without merging**
