### PR TITLE
Add SchunkWsgController

### PR DESCRIPTION
**Pull request by sammy-tri**
This still uses the trajectory generator to calculate desired motion
to a target position, but adds substantial P gains and a saturation
block to ramp up to maximum commanded force quickly if the gripper is
blocked on the way to the target.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6546)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-:-Koi_AaJmN6FNJMSEgRy:b-psw9ws)*

**Comment by sammy-tri** [comment]
I have no idea why Reviewable is showing maliput-related changes in this PR after my most recent rebase.  If you look at it on Github, only the 17 files I actually changed show up.  If you want to ignore the unrelated content, that works for me (it might go away?) or I can open a new PR and see if something reasonable happens.

---

Review status: 0 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-:-KowSzFhrXR-fPNmUHkz:b-1ltkys)*

**Comment by sammy-tri** [comment]
It seems mostly better now (rebased again).  Huh.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-:-KoxFJ4X5rFctwENc5g7:b9w0h3l)*

**Comment by naveenoid** [comment]
Checkpoint : Im ok with reviewing it here. The spurious stuff turned up again. I guess you need to fix it before merge? 

PR is mostly ok barring documentation requests.

---

Reviewed 20 of 30 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/manipulation/schunk_wsg/schunk_wsg_controller.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxFD3uyMHQOALil1aO:-KoxFD3uyMHQOALil1aP:bvug15m) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/manipulation/schunk_wsg/schunk_wsg_controller.h#L10)):*
> ```objc
> namespace schunk_wsg {
> 
> /// This class implements a controller for a schunk wsg.  It has two
> ```

BTW: nit - "schunk wsg" -> "Schunk WSG gripper"

---

*[drake/manipulation/schunk_wsg/schunk_wsg_controller.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxFk2pfUJim_ezdoGk:-KoxFk2pfUJim_ezdoGl:b-12tswk) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/manipulation/schunk_wsg/schunk_wsg_controller.h#L13)):*
> ```objc
> /// input ports which receive lcmt_schunk_wsg_command messages and the
> /// current state, and an output port which emits the target force for
> /// the actuated finger.
> ```

I think a comment is needed here stating that it wraps a PID controller and a Saturation. Also, perhaps the Saturation magnitude needs to be documented somewhere? It would affect the max force applied.

---

*[drake/manipulation/schunk_wsg/schunk_wsg_lcm.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxGpVwGMiAqR5PSejD:-KoxGpVwGMiAqR5PSejE:b1aq3t4) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/manipulation/schunk_wsg/schunk_wsg_lcm.h#L25)):*
> ```objc
> /// along with the current state of the simulated WSG (input port 1),
> /// and emits target position/velocity for the actuated finger to
> /// reach the commanded target.
> ```

Max force output might need to be documented here.

---

*[drake/common/BUILD, line 704 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxEuWmubR6BtO7rEdr:-KoxEuWmubR6BtO7rEds:bkpcefa) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/common/BUILD#L704)):*
> ```Python
> drake_cc_googletest(
>     name = "symbolic_polynomial_test",
>     # Test size increased to not timeout when run with Valgrind.
> ```

Was this change also part of this PR?

---

*[drake/common/test/CMakeLists.txt, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxEyvr0V5QtbtyeSRb:-KoxEyvr0V5QtbtyeSRc:bb8d2kj) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/common/test/CMakeLists.txt#L111)):*
> ```CMake
> target_link_libraries(symbolic_variable_overloading_test drakeCommon)
> 
> drake_add_cc_test(NAME symbolic_polynomial_test SIZE medium)
> ```

BTW: Probably not this PR right?

---

*[drake/systems/analysis/test/CMakeLists.txt, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxH4ZBqbPwtCssfgmn:-KoxH4ZBqbPwtCssfgmo:b-gnzos3) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/systems/analysis/test/CMakeLists.txt#L13)):*
> ```CMake
>         drakeSpringMassSystemPlant)
> 
> drake_add_cc_test(NAME implicit_euler_integrator_test SIZE large)
> ```

BTW : Again seems a spurious addition to this PR..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-:-KoxHsnaXxqIjQUSa3yz:b-6gurqd)*

**Comment by sammy-tri** [comment]
I don't think there's anything to fix according to git (or github).  Reviewable seems like the only confused party.

---

Review status: 15 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/manipulation/schunk_wsg/schunk_wsg_controller.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxFD3uyMHQOALil1aO:-KoxJZSi2gr75Tsr3gJ6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/manipulation/schunk_wsg/schunk_wsg_controller.h#L10)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: nit - "schunk wsg" -> "Schunk WSG gripper"
</blockquote></details>

Done.

---

*[drake/manipulation/schunk_wsg/schunk_wsg_controller.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxFk2pfUJim_ezdoGk:-KoxK6npVQUCPa4VZepR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/manipulation/schunk_wsg/schunk_wsg_controller.h#L13)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

I think a comment is needed here stating that it wraps a PID controller and a Saturation. Also, perhaps the Saturation magnitude needs to be documented somewhere? It would affect the max force applied.
</blockquote></details>

Done.

---

*[drake/manipulation/schunk_wsg/schunk_wsg_lcm.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxGpVwGMiAqR5PSejD:-KoxKNCsp6iBRkBmnl3x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/manipulation/schunk_wsg/schunk_wsg_lcm.h#L25)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Max force output might need to be documented here.
</blockquote></details>

Done.

---

*[drake/common/BUILD, line 704 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxEuWmubR6BtO7rEdr:-KoxKPFJ1OK_VKTgL-7G:bfc9her) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/common/BUILD#L704)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Was this change also part of this PR?
</blockquote></details>

Nope, spurious entry in Reviewable.  Does not appear in the git history for the branch or in Github's view.

---

*[drake/common/test/CMakeLists.txt, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxEyvr0V5QtbtyeSRb:-KoxKW0wpo-fUnwqFUB3:byimjgi) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/common/test/CMakeLists.txt#L111)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Probably not this PR right?
</blockquote></details>

Nope, spurious entry in Reviewable.

---

*[drake/systems/analysis/test/CMakeLists.txt, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-KoxH4ZBqbPwtCssfgmn:-KoxKXvoS_MQeTyjOnDm:b-ijfr84) ([raw file](https://github.com/robotlocomotion/drake/blob/1da254ed9ff7596a4f3b989367e598c8e58e53af/drake/systems/analysis/test/CMakeLists.txt#L13)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW : Again seems a spurious addition to this PR..
</blockquote></details>

Spurious entry in Reviewable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-:-KoxJFglsjyawhxBymY1:b-1q8wac)*

**Comment by sammy-tri** [comment]
+@soonho-tri for platform review per rotation

---

Review status: 15 of 17 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-:-KoxL2-gXrRyjivuKOcT:b-v3yl53)*

**Comment by sammy-tri** [comment]
-@soonho-tri +@jwnimmer-tri (per platform review rotation)

---

Review status: 15 of 17 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-:-Kp0afS3pg-CCYFeutbE:b-y06hcb)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 13 of 30 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/manipulation/schunk_wsg/BUILD, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-Kp0phZp6HeD8PKw42B3:-Kp0phZq-035JK0ooFH1:b-1wk1yp) ([raw file](https://github.com/robotlocomotion/drake/blob/3574bdfd307f32f08417c4f8b91f43a8acd830ee/drake/manipulation/schunk_wsg/BUILD#L51)):*
> ```Python
>     srcs = ["schunk_wsg_controller.cc"],
>     hdrs = ["schunk_wsg_controller.h"],
>     visibility = ["//visibility:public"],
> ```

FYI It looks like most of the targets here are being promoted to public.  Consider changing your `default_visibility` above.

---

*[drake/manipulation/schunk_wsg/schunk_wsg_controller.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-Kp0r-P8TXFKkfWqqwDI:-Kp0r-P8TXFKkfWqqwDJ:bn3ttqu) ([raw file](https://github.com/robotlocomotion/drake/blob/3574bdfd307f32f08417c4f8b91f43a8acd830ee/drake/manipulation/schunk_wsg/schunk_wsg_controller.cc#L53)):*
> ```cpp
>   // Create a gain block to negate the max force (to produce a minimum
>   // force).
>   auto gain = builder.AddSystem<systems::Gain<double>>(-1, 1);
> ```

FYI `-1.0` here instead of `-1` would have helped guide me to know that the gain constant was -1, versus some kind of no-index placeholder.  (I had to go look up what the positional args on Gain ctor were.)

---

*[drake/manipulation/schunk_wsg/schunk_wsg_controller.cc, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-Kp0qdsHW7lg2-QX5vRz:-Kp0qdsIqS3ZqlGo_yi_:bt1738i) ([raw file](https://github.com/robotlocomotion/drake/blob/3574bdfd307f32f08417c4f8b91f43a8acd830ee/drake/manipulation/schunk_wsg/schunk_wsg_controller.cc#L69)):*
> ```cpp
> }
> ```

FYI Do you want double-blank line here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-:-Kp0rxfBvQck2KV113vp:bcpz082)*

**Comment by sammy-tri** [comment]
Review status: 15 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/manipulation/schunk_wsg/BUILD, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-Kp0phZp6HeD8PKw42B3:-Kp0ssDZMTKCPYBD4SUB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3574bdfd307f32f08417c4f8b91f43a8acd830ee/drake/manipulation/schunk_wsg/BUILD#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It looks like most of the targets here are being promoted to public.  Consider changing your `default_visibility` above.
</blockquote></details>

Done.

---

*[drake/manipulation/schunk_wsg/schunk_wsg_controller.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-Kp0r-P8TXFKkfWqqwDI:-Kp0sy-Kcn3EdZlHihmK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3574bdfd307f32f08417c4f8b91f43a8acd830ee/drake/manipulation/schunk_wsg/schunk_wsg_controller.cc#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI `-1.0` here instead of `-1` would have helped guide me to know that the gain constant was -1, versus some kind of no-index placeholder.  (I had to go look up what the positional args on Gain ctor were.)
</blockquote></details>

Done.

---

*[drake/manipulation/schunk_wsg/schunk_wsg_controller.cc, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-Kp0qdsHW7lg2-QX5vRz:-Kp0syy633s0k_3jHU1_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3574bdfd307f32f08417c4f8b91f43a8acd830ee/drake/manipulation/schunk_wsg/schunk_wsg_controller.cc#L69)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Do you want double-blank line here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546)*

**Comment by sammy-tri** [comment]
-@naveenoid so I can merge this PR and open another.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6546#-:-Kp1A41w4-ePU-htI4Qc:b-28anum)*

**Pull request merged**
