### PR TITLE
Disable Atlas and Valkyrie tests that are flaky in continuous

### PR DESCRIPTION
**Pull request by ggould-tri**
See #2165, #2376.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2432) &emsp; Multiple assignees:&emsp;@RussTedrake&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/RussTedrake">RussTedrake</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@russtedrake (feature) (because he suggested this approach)
+@sherm1 (platform)

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> #### Disable Atlas and Valkyrie tests that are flaky in continuous
> 
> See #2165, #2376.
> 
> 
> 
</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2432#-:-KITkcUDpQptZiBABgDV:-2082353620)*

**Comment by sherm1** [comment]
Platform: :lgtm:
Mergeable after thumbs-up from @russtedrake

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> +@russtedrake (feature) (because he suggested this approach)
> +@sherm1 (platform)
</details>


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2432#-:-KIUH21M7RjiFEQOdT--:965878216)*

**Comment by RussTedrake** [comment]
:lgtm:  (with a heavy heart).  We must resolve those issues!!

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Platform: :lgtm:
> Mergeable after thumbs-up from @russtedrake
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2432#-:-KIUYKa0LILFifPQptbX:1575272566)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
