### PR TITLE
Handles QP with no equality constraint

### LINKED ISSUE #6557: Handling Unconstrained Problems in QP Solver
We are testing optimization problems without any constraints in `equality_constrained_qp_solver_test`[1].
Our code is not specifically handling optimization problems with lack of constraints (`num_constraints` = 0) [2].  Eigen seems to provide creation of zero sized matrix but doesn't seem to handle it very carefully, which gives way to undefined behavior [3] [4].

[1] 
https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/test/equality_constrained_qp_solver_test.cc#L37

[2]
https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/equality_constrained_qp_solver.cc#L105

[3]
https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=140896

[4]
https://gist.github.com/m-chaturvedi/9edd4c34de954cee1d91ab4f122d6ffc

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #6557

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6588)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@m-chaturvedi for feature review. +@ericcousineau-tri for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-:-KpJ2eV2hXkS-C9ujw3C:ba4uk1l)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
Are we testing for the case when the Hessian matrix is not positive-semidefinite but we have a non-unbounded least square solution?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-:-KpMGcOyCzryjBrjvpGI:bs3ge1n)*

**Comment by m-chaturvedi** [comment]
I'm sorry, I mean when G is not positive definite but is positive-semidefinite, and we have infinite solutions?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-:-KpMHzauLdH5OlnLFNbR:b8v6pq5)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/equality_constrained_qp_solver.cc, line 66 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpMf090KQIJNbKi-r7w:-KpMf091ASiAlJcWNBWj:b-a0wag5) ([raw file](https://github.com/robotlocomotion/drake/blob/048c119803708fdfe082c3419f853f4cc2faea18/drake/solvers/equality_constrained_qp_solver.cc#L66)):*
> ```cpp
>     const auto& Q = binding.constraint()->Q();
>     const auto& b = binding.constraint()->b();
>     constant_term += binding.constraint()->c();
> ```

BTW Sorry for not adding that in earlier!

---

*[drake/solvers/equality_constrained_qp_solver.cc, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpMfPmvFkyp2UAwQKR-:-KpMfPmvFkyp2UAwQKR0:b-d9o51p) ([raw file](https://github.com/robotlocomotion/drake/blob/048c119803708fdfe082c3419f853f4cc2faea18/drake/solvers/equality_constrained_qp_solver.cc#L123)):*
> ```cpp
>     } else {
>       // The following code assumes that the Hessian is not positive definite.
>       // It uses the singular value decomposition, which is generally overkill
> ```

BTW super nit Grammar: "generally overkill, but"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-:-KpMgEntgV2xWpyDBxYm:bnfp4nl)*

**Comment by hongkai-dai** [comment]
@m-chaturvedi yes, we tested min x(0) * x(0) - 2 * x(1). In this case the Hessian is 
[1 0]
[0 0]
a positive semidefinite matrix, but not strictly positive definite. And the problem is unbounded (x(1) can be negative infinity.)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-:-KpMo_8pj7Y1cvPPljh3:b-9g23yb)*

**Comment by hongkai-dai** [comment]
+@ggould-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-:-KpMrDMj_LmBpaeOaOGS:b-irfx5k)*

**Comment by ggould-tri** [comment]
:lgtm:, minor nits below.

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/equality_constrained_qp_solver.cc, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpQ4FTaGvWmXlNihz_f:-KpQ4FTaGvWmXlNihz_g:b-6t2s4y) ([raw file](https://github.com/robotlocomotion/drake/blob/59107c385e5a015f38b9005a14840be9d04efb88/drake/solvers/equality_constrained_qp_solver.cc#L26)):*
> ```cpp
>   // for problem variables x and Lagrange multiplier variables y. This
>   // corresponds to the QP:
>   // minimize 1/2 x'*G*x + c'*x + constant_term
> ```

BTW -- Not sure what it means to minimize a constant term.  Is the point just to pass it through from the problem to `optimal_cost`?

---

*[drake/solvers/test/equality_constrained_qp_solver_test.cc, line 133 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpQ6gNIlYhpZJe5aymB:-KpQ6gNJQuJ4UNdUYEyq:b4ev7yo) ([raw file](https://github.com/robotlocomotion/drake/blob/59107c385e5a015f38b9005a14840be9d04efb88/drake/solvers/test/equality_constrained_qp_solver_test.cc#L133)):*
> ```cpp
> 
> GTEST_TEST(testMathematicalProgram, testNonPositiveSemidefiniteHessianQP) {
>   // cost is x(0)² - x(1)²
> ```

FYI -- Capitalize and punctuate complete sentences.

---

*[drake/solvers/test/equality_constrained_qp_solver_test.cc, line 143 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpQ6kgHO-CURG4U91_E:-KpQ6kgI8TlNJglJLRzX:b4ev7yo) ([raw file](https://github.com/robotlocomotion/drake/blob/59107c385e5a015f38b9005a14840be9d04efb88/drake/solvers/test/equality_constrained_qp_solver_test.cc#L143)):*
> ```cpp
> 
> GTEST_TEST(testMathematicalProgram, testUnboundedQP) {
>   // cost is x(0)² - 2 * x(1)
> ```

FYI -- Capitalize and punctuate complete sentences.

---

*[drake/solvers/test/equality_constrained_qp_solver_test.cc, line 153 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpQ6lEX9I6sFu1wpbw-:-KpQ6lEX9I6sFu1wpbw0:b4ev7yo) ([raw file](https://github.com/robotlocomotion/drake/blob/59107c385e5a015f38b9005a14840be9d04efb88/drake/solvers/test/equality_constrained_qp_solver_test.cc#L153)):*
> ```cpp
> 
> GTEST_TEST(testMathematicalProgram, testNegativeDefiniteHessianQP) {
>   // cost is -x(0)² - 2 * x(1)
> ```

FYI -- Capitalize and punctuate complete sentences.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-:-KpQ5k_Yg70fEpkWkWkB:b-t4so99)*

**Comment by m-chaturvedi** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-:-KpQHIGuUiZFwlcHMlBO:bg7igkv)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/equality_constrained_qp_solver.cc, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpQ4FTaGvWmXlNihz_f:-KpQby4b1jIyMxN5ipX2:bv3enmt) ([raw file](https://github.com/robotlocomotion/drake/blob/59107c385e5a015f38b9005a14840be9d04efb88/drake/solvers/equality_constrained_qp_solver.cc#L26)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- Not sure what it means to minimize a constant term.  Is the point just to pass it through from the problem to `optimal_cost`?
</blockquote></details>

Exactly. It is just to make sure that the optimal cost is computed correctly.

---

*[drake/solvers/test/equality_constrained_qp_solver_test.cc, line 133 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpQ6gNIlYhpZJe5aymB:-KpQdbgeLC0VsVVnAuW7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59107c385e5a015f38b9005a14840be9d04efb88/drake/solvers/test/equality_constrained_qp_solver_test.cc#L133)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- Capitalize and punctuate complete sentences.
</blockquote></details>

Done.

---

*[drake/solvers/test/equality_constrained_qp_solver_test.cc, line 143 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpQ6kgHO-CURG4U91_E:-KpQdcHO_9V0KPyLcm3S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59107c385e5a015f38b9005a14840be9d04efb88/drake/solvers/test/equality_constrained_qp_solver_test.cc#L143)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- Capitalize and punctuate complete sentences.
</blockquote></details>

Done.

---

*[drake/solvers/test/equality_constrained_qp_solver_test.cc, line 153 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6588#-KpQ6lEX9I6sFu1wpbw-:-KpQdcgp4skqYjjM1hA6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59107c385e5a015f38b9005a14840be9d04efb88/drake/solvers/test/equality_constrained_qp_solver_test.cc#L153)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- Capitalize and punctuate complete sentences.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6588)*

**Pull request merged**
