### PR TITLE
Add Ignition RNDF external dependency

### PR DESCRIPTION
**Pull request by caguero**
This PR adds [`Ignition RNDF`](https://bitbucket.org/ignitionrobotics/ign-rndf) as a new dependency for loading RNDF files.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5831)

### CODE REVIEW

**Comment by caguero** [comment]
`+@jwnimmer-tri` for feature review

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-KhwyXU7-6Zk_3T7uAiA:b-lsc6ck)*

**Comment by sherm1** [comment]
@caguero from OSRF needs a feature reviewer for this PR. +@maddog-tri are you the right guy? If not would you assign this to someone please?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-KhyWtlxGUxYRggWILZW:b-kpahdv)*

**Comment by maddog-tri** [comment]
Reviewed; please take a look.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-Ki131RfJ90mApzl9al6:-Ki131RfJ90mApzl9al7:b-a0o9w0) (no related file):*
Hmm... it looks like `namespace monolane` also snuck into `test/ignition_math_test.cc` --- please change that to `namespace rndf` as well (see `ignition_rndf_test.cc` below).  Might as well fix it in this PR.

---

*[drake/automotive/maliput/rndf/test/ignition_rndf_test.cc, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-Ki11ssRglMwWAGD9iz2:-Ki11ssRglMwWAGD9iz3:bnvrn6b) ([raw file](https://github.com/robotlocomotion/drake/blob/6e61da247c6327eb70794fa85937bef86ff58311/drake/automotive/maliput/rndf/test/ignition_rndf_test.cc#L6)):*
> ```cpp
> namespace drake {
> namespace maliput {
> namespace monolane {
> ```

`namespace monolane` should (more plausibly) be `namespace rndf`.

---

*[drake/automotive/maliput/rndf/test/ignition_rndf_test.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-Ki124LJgMVj2T2ZoTA-:-Ki124LJgMVj2T2ZoTA0:b-64c7w5) ([raw file](https://github.com/robotlocomotion/drake/blob/6e61da247c6327eb70794fa85937bef86ff58311/drake/automotive/maliput/rndf/test/ignition_rndf_test.cc#L8)):*
> ```cpp
> namespace monolane {
> 
> GTEST_TEST(IgnitionRNDFTest, Test) {
> ```

I'm guessing that this test exists merely to exercise the bazel infrastructure and ensure that the ignition-rndf library can be built and linked.  Please add a comment that explains this (so future readers of the code don't have to guess).

---

*[drake/automotive/maliput/rndf/test/ignition_rndf_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-Ki12Z-R3KAkRQsEeTA6:-Ki12Z-R3KAkRQsEeTA7:b-96lz2j) ([raw file](https://github.com/robotlocomotion/drake/blob/6e61da247c6327eb70794fa85937bef86ff58311/drake/automotive/maliput/rndf/test/ignition_rndf_test.cc#L14)):*
> ```cpp
> 
> 
> }  // namespace monolane
> ```

Keep consistent with any namespace change (as requested above).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-Ki13QgMAUbvFbo6uzW6:b-bynpys)*

**Comment by caguero** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-Ki131RfJ90mApzl9al6:-Ki15QyCY5-ekpFe6LLU:b-v20aiy) (no related file):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Hmm... it looks like `namespace monolane` also snuck into `test/ignition_math_test.cc` --- please change that to `namespace rndf` as well (see `ignition_rndf_test.cc` below).  Might as well fix it in this PR.
</blockquote></details>

Good catch. Fixed in c27856e

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831)*

**Comment by caguero** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/rndf/test/ignition_rndf_test.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-Ki124LJgMVj2T2ZoTA-:-Ki16QPnkd3XvVw2EmeQ:b-kn4ft6) ([raw file](https://github.com/robotlocomotion/drake/blob/6e61da247c6327eb70794fa85937bef86ff58311/drake/automotive/maliput/rndf/test/ignition_rndf_test.cc#L8)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

I'm guessing that this test exists merely to exercise the bazel infrastructure and ensure that the ignition-rndf library can be built and linked.  Please add a comment that explains this (so future readers of the code don't have to guess).
</blockquote></details>

That's correct. Added comment in 1020601

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831)*

**Comment by caguero** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/rndf/test/ignition_rndf_test.cc, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-Ki11ssRglMwWAGD9iz2:-Ki16ZOxWVrZ9niz8c-F:bnd48a2) ([raw file](https://github.com/robotlocomotion/drake/blob/6e61da247c6327eb70794fa85937bef86ff58311/drake/automotive/maliput/rndf/test/ignition_rndf_test.cc#L6)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

`namespace monolane` should (more plausibly) be `namespace rndf`.
</blockquote></details>

Fixed in c27856e

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831)*

**Comment by caguero** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/rndf/test/ignition_rndf_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-Ki12Z-R3KAkRQsEeTA6:-Ki16sKS0t5QtaU0LFjw:bnd48a2) ([raw file](https://github.com/robotlocomotion/drake/blob/6e61da247c6327eb70794fa85937bef86ff58311/drake/automotive/maliput/rndf/test/ignition_rndf_test.cc#L14)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Keep consistent with any namespace change (as requested above).
</blockquote></details>

Fixed in c27856e

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-Ki174Y1Jh7eaT8lJXkc:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@caguero if you put the assignment in backticks, it doesn't work.  Just write +@jwnimmer-tri in plaintext and the magic will happen.  I'll self-assign for platform review since I'm on-call for tomorrow anyway.

**Comment by caguero** [comment]
Apparently I don't have permission to set labels or assignees in this repository. I was following the Reviewable recommendation with backticks. I'm member of the RobotLocomotion organization. Not sure what's wrong.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-KiBL0Pl33mUHdgJSUxs:b-9cegdb)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri Can you check on the permissions here, please?

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

:lgtm:

---

Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/rndf/BUILD, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-KiCnmW8uXLI4RJlsfWP:-KiCnmW9E1h7P2U2VYkt:b-fypdex) ([raw file](https://github.com/robotlocomotion/drake/blob/10206013f3240a0e5efb10cd8a5b507944f359db/drake/automotive/maliput/rndf/BUILD#L17)):*
> ```Python
> 
> drake_cc_googletest(
>     name = "ignition_math_test",
> ```

FYI If `ignition_rndf_test` ends up tickling `ignition_math` indirectly, I would be okay if this test was removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-KiCnzyLycUOKkNjKOCK:bwkpaz3)*

**Comment by caguero** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/rndf/BUILD, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-KiCnmW8uXLI4RJlsfWP:-KiCyEaGna8w8gQ95DWa:bi3ibzl) ([raw file](https://github.com/robotlocomotion/drake/blob/10206013f3240a0e5efb10cd8a5b507944f359db/drake/automotive/maliput/rndf/BUILD#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI If `ignition_rndf_test` ends up tickling `ignition_math` indirectly, I would be okay if this test was removed.
</blockquote></details>

True, `ignition_math_test` removed in 65abd0b .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-KiFwkIe7B0jK2TcTC4J:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@caguero The "curate" label means that you must either squash locally and `push -f` so there's only a single commit, or else remove the label and then manually choose "squash and merge" when pushing the green github button to merge.

**Comment by caguero** [comment]
Thanks, it should be OK now.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-KiGgHTvBumSa64eEiuj:btsd3i1)*

**Comment by jwnimmer-tri** [comment]
@caguero Do you have available the green merge button yet?  If not, tag stonier to fix your permissions so that you do.  You are welcome to push it anytime its green, on any PR.

**Comment by caguero** [comment]
I still can't see the merge button. I can't tag either. I'll ping stonier, thanks.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-KiHwE6rqjwj_qU8aLPK:b2jzcu5)*

**Comment by stonier** [comment]
It's fairly atypical to give external groups write access (which I guess is @caguero's surprise) and that is the way it is currently configured in the team settings. I don't have any objection since they are likely to be a frequent contributor though. You should be good to go now @caguero.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5831#-:-KiIu5o__RAi0GzXygRF:b-6atyj8)*

**Comment by jwnimmer-tri** [comment]
FTR -- I consider our OSRF contributors on par with all other Drake Developers at TRI, MIT, etc., so they should have the same bits.

**Pull request merged**
