### PR TITLE
IpoptSolver sets the sparsity parttern of the linear constraints.

### LINKED ISSUE #21485: Strange handling of constraints with IPOPT.
### What happened?

I was playing around with the mathematical program in both Casadi and Drake and I found some weird issues how linear constraints are evaluated. 

In particular it seems like putting a matrix into a linear constraint many non-zeros to appear in the Jacobian. This greatly slows down the ipopt solver. 

As a motivating example I've added a quick test file that compares two approaches in drake and then also an implementation in casadi.
[drake_ipopt_issue.py.zip](https://github.com/RobotLocomotion/drake/files/15448717/drake_ipopt_issue.py.zip)

The first version added the program constraints as such: 
```
    prog.AddLinearConstraint(-max_val - controls ,np.ones_like(controls)*-np.inf, -DATA)
    prog.AddLinearConstraint(eq(integral_val[1:],( integral_val[:-1] + controls*.25)))
```

Looking at the solver output this generated: 
```
...
This is Ipopt version 3.14.16, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:    80203
Number of nonzeros in inequality constraint Jacobian.:    40200
...
```

When we change those lines to use a loop instead as such: 

```
  for i in range(N):
        prog.AddLinearConstraint(integral_val[i+1]==integral_val[i] + controls[i]*.25)
        prog.AddLinearConstraint(-max_val- controls[i] ,[-np.inf], [-DATA[i]])
```

We get instead: 
```
Number of nonzeros in equality constraint Jacobian...:      603
Number of nonzeros in inequality constraint Jacobian.:      400
```

Casadi has the same number:
```
Number of nonzeros in equality constraint Jacobian...:      603
Number of nonzeros in inequality constraint Jacobian.:      400
```

Looking at solve times we see that the large number of nonzero greatly affect the solve time (though casadi is faster than either approach still by large margin)

Solve time First Program:  0.7652149200439453
Solve time Fixed Version:  0.11430883407592773
Casadi Solve Time: 0.012894868850708008

I saw a similar (though slightly different) issue mentioned in #18292. I took the liberty in using their values for IPOPT settings. 

### Version

_No response_

### What operating system are you using?

macOS 14 (Sonoma)

### What installation option are you using?

pip install drake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #21485

cc @jorgenin

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21492)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-:-Nz0W4JbA-V1380BOZVZ:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21492)* status: 10 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/BUILD.bazel` line 1455 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3dRS79p3heXhLLJ6Z:-Nz3dRS79p3heXhLLJ6_:b-70vo1) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/BUILD.bazel#L1455)):*
> ```Starlark
> 
> drake_cc_googletest(
>     name = "ipopt_solver_internal_test",
> ```

This is new Bazel syntax for me and so I can't confirm that it is all correct. Can the platform reviewer please give this a pass.
___
*[`solvers/ipopt_solver_internal.cc` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3iOTpBU05elTttMWr:-Nz3iOTqBYJ2q_qnYI51:b-2z0ujm) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L44)):*
> ```cpp
> int GetNumGradients(const LinearConstraint& c, Index* num_grad) {
>   const int num_constraints = c.num_constraints();
>   *num_grad = c.get_sparse_A().nonZeros();
> ```

I am confused by this. How is this the number of gradients in a linear constraint? Are you counting the non-zero entries of`d(constraint_{i})/dx_{j}`?
___
*[`solvers/ipopt_solver_internal.cc` line 148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3krz78-LaryLEVTXr:-Nz3krz78-LaryLEVTXs:b-4y2n0h) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L148)):*
> ```cpp
> /// Parameters @p iRow and @p jCol are used in the same manner as
> /// described in
> /// http://www.coin-or.org/Ipopt/documentation/node23.html for the
> ```

FYI: this link is dead



_Code quote:_
```cpp
http://www.coin-or.org/Ipopt/documentation/node23.html
```
___
*[`solvers/ipopt_solver_internal.cc` line 152 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3kmkx6EbetA2a9mDg:-Nz3kmkx6EbetA2a9mDh:b-4y2n0h) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L152)):*
> ```cpp
> /// sparsity structure of the Jacobian).  The triplet format is also
> /// described in
> /// http://www.coin-or.org/Ipopt/documentation/node38.html#app.triplet
> ```

FYI: this link is dead



_Code quote:_
```cpp
http://www.coin-or.org/Ipopt/documentation/node38.html#app.triplet
```
___
*[`solvers/ipopt_solver_internal.cc` line 172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3kP89EghZzYqtWb4r:-Nz3kP89EghZzYqtWb4s:b4uzlha) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L172)):*
> ```cpp
>   return grad_index;
> }
> ```

Could you add a doc string for this please. I do not understand what this code is doing, since I expected it to just return `Aᵀ`.
___
*[`solvers/ipopt_solver_internal.cc` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3j0Tg5pn4OZ47v47h:-Nz3j0Tg5pn4OZ47v47i:b7ky8zv) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L180)):*
> ```cpp
>   const Eigen::SparseMatrix<double>& A = c.get_sparse_A();
>   for (int i = 0; i < A.outerSize(); ++i) {
>     const int var_index = prog.FindDecisionVariableIndex(variables(i));
> ```

If `A` is stored in `RowMajor` (i.e. CRS) order instead of `ColumnMajor`(CCS) is this still accessing the correct variable?



_Code quote:_
```cpp
const int var_index = prog.FindDecisionVariableIndex(variables(i));
```
___
*[`solvers/test/ipopt_solver_internal_test.cc` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3nf9s0nzkhhFAk474:-Nz3nf9s0nzkhhFAk475:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/test/ipopt_solver_internal_test.cc#L41)):*
> ```cpp
>   auto x = prog.NewContinuousVariables<4>();
>   Eigen::Matrix<double, 2, 3> A;
>   A << 1, 0, 3, 2, -4, 0;
> ```

nit



_Suggestion:_
```cpp
// clang-format off
A << 1,  0, 3, 
     2, -4, 0;
// clang-format on
```
___
*[`solvers/test/ipopt_solver_internal_test.cc` line 67 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3n1gXBtfXOBYsR6r1:-Nz3n1gXBtfXOBYsR6r2:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/test/ipopt_solver_internal_test.cc#L67)):*
> ```cpp
>   GetConstraintJacobian(&dut, n, m, nnz_jac_g, x_init.data(), &jac);
>   Eigen::Matrix<double, 2, 4> jac_expected;
>   jac_expected << 0, 1, 0, 3, 0, 2, -4, 0;
> ```

nit



_Suggestion:_
```cpp
// clang-format off
jac_expected << 0, 1,  0, 3, 
                0, 2, -4, 0;
// clang-format on
```
___
*[`solvers/test/ipopt_solver_internal_test.cc` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3obmL4Xkm3bh2OMyc:-Nz3obmL4Xkm3bh2OMyd:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/test/ipopt_solver_internal_test.cc#L76)):*
> ```cpp
>   auto x = prog.NewContinuousVariables<4>();
>   Eigen::Matrix<double, 2, 3> A;
>   A << 1, 0, 3, 2, -4, 0;
> ```

nit



_Suggestion:_
```cpp
// clang-format off
A << 1,  0, 3, 
     2, -4, 0;
// clang-format on
```
___
*[`solvers/test/ipopt_solver_internal_test.cc` line 81 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3olGl50W--78bHmqr:-Nz3olGl50W--78bHmqs:btu27gh) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/test/ipopt_solver_internal_test.cc#L81)):*
> ```cpp
>   Eigen::Vector2d ub(2, 5);
>   prog.AddLinearConstraint(A, lb, ub, x.tail<3>());
>   prog.AddLinearConstraint(A, lb, ub, x.head<3>());
> ```

These are not linear equality constraints. I believe you meant to change these



_Suggestion:_
```cpp
  prog.AddLinearEqualityConstraint(A, lb, ub, x.tail<3>());
  prog.AddLinearEqualityConstraint(A, lb, ub, x.head<3>());
```
___
*[`solvers/test/ipopt_solver_internal_test.cc` line 107 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3oymi8KBhavSym_M-:-Nz3oymi8KBhavSym_M0:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/test/ipopt_solver_internal_test.cc#L107)):*
> ```cpp
>                   0, 2, -4, 0,
>                   1, 0, 3, 0,
>                   2, -4, 0, 0;
> ```

nit



_Suggestion:_
```cpp
  jac_expected << 0,  1,  0, 3,
                  0,  2, -4, 0,
                  1,  0,  3, 0,
                  2, -4,  0, 0;
```
___
*[`solvers/test/ipopt_solver_internal_test.cc` line 117 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3p4J06jhctvcoz5Yo:-Nz3p4J06jhctvcoz5Yp:bo75e30) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/test/ipopt_solver_internal_test.cc#L117)):*
> ```cpp
>   auto x = prog.NewContinuousVariables<4>();
>   Eigen::Matrix<double, 2, 3> A;
>   A << 1, 0, 3, 0, 3, 5;
> ```

nit: could you please format as a 2x3 matrix. It makes it much easier to read.



_Code quote:_
```cpp
A << 1, 0, 3, 0, 3, 5;
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21492)* status: 5 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/ipopt_solver_internal.cc` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3iOTpBU05elTttMWr:-Nz3quedDDYk9RdwCAmx:b8vg2yp) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L44)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I am confused by this. How is this the number of gradients in a linear constraint? Are you counting the non-zero entries of`d(constraint_{i})/dx_{j}`?
</blockquote></details>

The linear constraint is `lb <= A * x <= ub`, hence its gradient is `A = c.get_sparse_A()`. `num_grad` is the number of non-zero entries in the gradient matrix (I inherited this name from the function `GetNumGradients` above, implemented by other developers).
___
*[`solvers/ipopt_solver_internal.cc` line 148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3krz78-LaryLEVTXr:-Nz3vQYY947B2Sj5ufpz:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L148)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

FYI: this link is dead
</blockquote></details>

Done.
___
*[`solvers/ipopt_solver_internal.cc` line 152 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3kmkx6EbetA2a9mDg:-Nz3vRiz0Gp1GC4ROyEp:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L152)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

FYI: this link is dead
</blockquote></details>

Done.
___
*[`solvers/ipopt_solver_internal.cc` line 172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3kP89EghZzYqtWb4r:-Nz3ve2P2FsixtubnxcN:b-vk9fv0) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L172)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Could you add a doc string for this please. I do not understand what this code is doing, since I expected it to just return `Aᵀ`.
</blockquote></details>

Done.

It returns the number of non-zeros in this constraint. It overloads `GetGRadientMatrix` above, so the user can refer to the documentation above.
___
*[`solvers/ipopt_solver_internal.cc` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3j0Tg5pn4OZ47v47h:-Nz3vtsbCON3QfchA71e:b-5ws6y8) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/ipopt_solver_internal.cc#L180)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

If `A` is stored in `RowMajor` (i.e. CRS) order instead of `ColumnMajor`(CCS) is this still accessing the correct variable?
</blockquote></details>

This `A` is in column major, as seen in 
```cc
const Eigen::SparseMatrix<double>& A = c.get_sparse_A();
```
I added a comment here.
___
*[`solvers/test/ipopt_solver_internal_test.cc` line 81 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3olGl50W--78bHmqr:-Nz44MZS0JCoJIP19VZD:b-376vyb) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/test/ipopt_solver_internal_test.cc#L81)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

These are not linear equality constraints. I believe you meant to change these
</blockquote></details>

Done. Good catch.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 
+@EricCousineau-TRI for platform review. Thanks!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-:-Nz4UdbS9bcEx8spFZcJ:b-fajfx5)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/BUILD.bazel` line 1455 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3dRS79p3heXhLLJ6Z:-Nz4UmHC5n-GqcUr4vhG:b-884dlx) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/BUILD.bazel#L1455)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This is new Bazel syntax for me and so I can't confirm that it is all correct. Can the platform reviewer please give this a pass.
</blockquote></details>

@EricCousineau-TRI. Just flagging this so that you can check the Bazel syntax.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-:-Nz4bjAU3UlA2YngeOO5:bcpz082)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz4b_YCDjxiPmNPfod9:-Nz4b_YDATGMqsMBUJDX:b-gvrl5q) (no related file):*
BTW Do we have a sense of how much of a speedup we may get with this w.r.t. @jorgenin's benchmark (or some another benchmark)?

___
___
*[`solvers/BUILD.bazel` line 1455 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz3dRS79p3heXhLLJ6Z:-Nz4bBpx022zFeBvm2OA:b7la7q0) ([raw file](https://github.com/RobotLocomotion/drake/blob/288c9ef4a9befb70922c28f88973188c8e687a20/solvers/BUILD.bazel#L1455)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

@EricCousineau-TRI. Just flagging this so that you can check the Bazel syntax.
</blockquote></details>

Looks good to me. I'm not deeply familiar with `select()`, but pattern matching against existing code makes me thing this is good.

e.g.
https://github.com/RobotLocomotion/drake/blob/953694f4d224c148df12a6f42bfeb908071aebff/solvers/BUILD.bazel#L1454-L1479

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21492)* status: missing label for release notes (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz4b_YCDjxiPmNPfod9:-Nz4g0UlA2Gtjyo9Jk25:b-3coua5) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Do we have a sense of how much of a speedup we may get with this w.r.t. @jorgenin's benchmark (or some another benchmark)?
</blockquote></details>

Using 9d0810f3e5, running `bazel run //tmp:drake_ipopt_issue`

On my system, before this patch:
```
Solve time:  2.3416011333465576
Solve time 2 :  0.37572431564331055
```
After this patch:
```
Solve time:  0.4102346897125244
Solve time 2 :  0.3771522045135498
```

Conclusion is now much faster (~6x), and closer to second formulation using for-loops, but most likely still slower than casadi.

___

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21492)* status: missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21492#-Nz4b_YCDjxiPmNPfod9:-Nz5mKRk3P0DNWSPTGVk:bha53ji) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Using 9d0810f3e5, running `bazel run //tmp:drake_ipopt_issue`

On my system, before this patch:
```
Solve time:  2.3416011333465576
Solve time 2 :  0.37572431564331055
```
After this patch:
```
Solve time:  0.4102346897125244
Solve time 2 :  0.3771522045135498
```

Conclusion is now much faster (~6x), and closer to second formulation using for-loops, but most likely still slower than casadi.
</blockquote></details>

Thanks Eric for checking it!

There can be a number of reasons why drake is slower than Casadi. One possibility is that the autodiff inside Drake is not very efficient.

___

**Comment by hongkai-dai** [comment]
@EricCousineau-TRI BTW, I just tested your example. The reason why Drake's IpoptSolver runs slower than Casadi is because Drake was using the default initial guess (the zero vector), as opposed to the initial guess set in the Casadi example.

I changed the code to use the same initial guess. Now Drake actually runs slightly faster than Casadi. Here is the output. Notice that in the first iteration Drake and Casadi evaluates the same objective
```
Starting test 2

List of user-set options:

                                    Name   Value                used
              acceptable_constr_viol_tol = 0.01                  yes
                          acceptable_tol = 1e-06                 yes
                         constr_viol_tol = 0.0001                yes
                   hessian_approximation = limited-memory        yes
                           linear_solver = mumps                 yes
                             print_level = 5                     yes
                 print_timing_statistics = no                    yes
                      print_user_options = yes                   yes
                                      sb = yes                   yes
                                     tol = 1e-08                 yes
This is Ipopt version drake_vendor, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:      603
Number of nonzeros in inequality constraint Jacobian.:      400
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:      402
                     variables with only lower bounds:        1
                variables with lower and upper bounds:      201
                     variables with only upper bounds:        0
Total number of equality constraints.................:      202
Total number of inequality constraints...............:      200
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:      200

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0001005e+02 1.00e-02 9.98e-01   0.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.0003383e+02 4.27e-03 6.77e-01  -4.3 9.29e-01    -  9.70e-01 5.73e-01h  1
   2  1.0003591e+02 1.88e-03 8.73e-01  -5.8 4.38e-01    -  9.85e-01 5.61e-01h  1
   3  1.0004087e+02 1.69e-02 1.60e-01  -3.5 2.44e-01    -  9.96e-01 8.98e-01h  1
   4  1.0001832e+02 1.53e-04 1.89e-03  -4.0 1.41e-01    -  9.85e-01 9.90e-01h  1
   5  1.0000105e+02 3.11e-18 2.70e-09  -5.3 6.83e-02    -  9.92e-01 1.00e+00h  1
   6  1.0000000e+02 3.33e-19 3.07e-11 -11.0 4.49e-03    -  9.91e-01 9.97e-01f  1
   7  9.9999999e+01 3.86e-22 1.44e-13 -11.0 5.41e-05    -  1.00e+00 1.00e+00f  1

Number of Iterations....: 7

                                   (scaled)                 (unscaled)
Objective...............:   9.9999998952050731e+01    9.9999998952050731e+01
Dual infeasibility......:   1.4359591999896980e-13    1.4359591999896980e-13
Constraint violation....:   3.8624003168684547e-22    3.8624003168684547e-22
Variable bound violation:   9.9975046968107693e-09    9.9975046968107693e-09
Complementarity.........:   1.0178693716247555e-11    1.0178693716247555e-11
Overall NLP error.......:   1.0178693716247555e-11    1.0178693716247555e-11


Number of objective function evaluations             = 8
Number of objective gradient evaluations             = 8
Number of equality constraint evaluations            = 8
Number of inequality constraint evaluations          = 8
Number of equality constraint Jacobian evaluations   = 8
Number of inequality constraint Jacobian evaluations = 8
Number of Lagrangian Hessian evaluations             = 0
Total seconds in IPOPT                               = 0.030

EXIT: Optimal Solution Found.
-------------------------------------------
-------------------------------------------
-------------------------------------------
Casadi Sol

List of user-set options:

                                    Name   Value                used
              acceptable_constr_viol_tol = 0.01                  yes
                          acceptable_tol = 1e-06                 yes
                         constr_viol_tol = 0.0001                yes
                   hessian_approximation = limited-memory        yes
                           linear_solver = mumps                 yes
                             print_level = 5                     yes
                 print_timing_statistics = no                    yes
                      print_user_options = yes                   yes
                                      sb = yes                   yes
                                     tol = 1e-08                 yes
This is Ipopt version 3.14.11, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:      603
Number of nonzeros in inequality constraint Jacobian.:      400
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:      402
                     variables with only lower bounds:        1
                variables with lower and upper bounds:      201
                     variables with only upper bounds:        0
Total number of equality constraints.................:      202
Total number of inequality constraints...............:      200
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:      200

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0001005e+02 1.00e-02 9.98e-01   0.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.0003387e+02 4.26e-03 6.76e-01  -4.2 9.29e-01    -  9.70e-01 5.74e-01h  1
   2  1.0003594e+02 1.87e-03 8.71e-01  -5.7 4.38e-01    -  9.86e-01 5.62e-01h  1
   3  1.0001198e+02 1.01e-02 9.39e-02  -3.6 2.34e-01    -  9.94e-01 9.34e-01h  1
   4  1.0002131e+02 6.04e-04 3.54e-02  -4.0 1.13e-02    -  9.95e-01 9.49e-01h  1
   5  1.0001801e+02 2.44e-06 4.07e-03  -5.6 4.07e-03    -  1.00e+00 9.92e-01h  1
   6  1.0001347e+02 2.78e-18 4.76e-03  -7.2 4.76e-03    -  1.00e+00 1.00e+00f  1
   7  1.0001006e+02 2.41e-18 4.91e-03  -8.1 4.91e-03    -  1.00e+00 7.28e-01f  1
   8  1.0000789e+02 2.90e-18 4.28e-08  -5.8 8.62e+00    -  1.00e+00 3.50e-03f  1
   9  9.9999999e+01 2.88e-18 4.31e-10 -10.9 1.34e-02    -  9.89e-01 1.00e+00f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10  9.9999999e+01 1.85e-22 2.13e-14 -11.0 4.33e-06    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 10

                                   (scaled)                 (unscaled)
Objective...............:   9.9999998952050007e+01    9.9999998952050007e+01
Dual infeasibility......:   2.1315227499335333e-14    2.1315227499335333e-14
Constraint violation....:   1.8528845721187820e-22    1.8528845721187820e-22
Variable bound violation:   9.9975031213371835e-09    9.9975031213371835e-09
Complementarity.........:   1.0006376209779095e-11    1.0006376209779095e-11
Overall NLP error.......:   1.0006376209779095e-11    1.0006376209779095e-11


Number of objective function evaluations             = 11
Number of objective gradient evaluations             = 11
Number of equality constraint evaluations            = 11
Number of inequality constraint evaluations          = 11
Number of equality constraint Jacobian evaluations   = 11
Number of inequality constraint Jacobian evaluations = 11
Number of Lagrangian Hessian evaluations             = 0
Total seconds in IPOPT                               = 0.084

EXIT: Optimal Solution Found.
      solver  :   t_proc      (avg)   t_wall      (avg)    n_eval
       nlp_f  | 208.00us ( 18.91us)  31.16us (  2.83us)        11
       nlp_g  | 701.00us ( 63.73us) 106.61us (  9.69us)        11
  nlp_grad_f  | 391.00us ( 32.58us)  53.57us (  4.46us)        12
   nlp_jac_g  | 824.00us ( 68.67us) 124.28us ( 10.36us)        12
       total  | 543.93ms (543.93ms)  87.33ms ( 87.33ms)         1
Solve time:  2.076539993286133
Solve time 2 :  0.030740976333618164
Casadi Solve Time: 0.08748602867126465
Controls norm:  1.358751404045516e-07
Integral norm:  4.4793890387626446e-08
Max norm:  6.991740519879386e-12
Controls norm casadi:  1.3579234259034422e-07
Integral norm casadi:  4.4805843778744453e-08
Max norm casadi:  7.005951374594588e-12
```
The difference in the computation is probably due to different ordering of the constraints.

**Comment by EricCousineau-TRI** [comment]
awesome, thanks! and ftr, it was not my example, but just taking @jorgenin and putting it into Drake for quick testing.

**Pull request merged**
