### PR TITLE
Tidy up some contollers vs robotInterfaces deps details

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.  Relates #6464.

This came up in my 6996 feature branch.  I thought that the circular dependency was causing trouble, so I fixed that in the first commit.  It wasn't my real problem, but will end up being useful for 6464 anyway so I've included it here.

The real problem ended up being the last commit, so that's the import important part here.

The middle two commits are just small tidies that came up along the way.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7428)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.
+@soonho-tri for platform review per schedule, please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/BUILD.bazel, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7428#-KyVZE_yMqeqkcDCKZn4:-KyVZE_yMqeqkcDCKZn5:b-b0y0i) ([raw file](https://github.com/robotlocomotion/drake/blob/7e6f81eeea16965ca278b173511192529e3407a2/drake/systems/controllers/BUILD.bazel#L120)):*
> ```
>     srcs = ["side.cc"],
>     hdrs = ["side.h"],
>     deps = [],
> ```

BTW, this line can be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7428#-:-KyVZehhQ7nNY86-8I9X:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/BUILD.bazel, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7428#-KyVZE_yMqeqkcDCKZn4:-KyVcR7A9TD7PxmIfU5M:bx6vtt3) ([raw file](https://github.com/robotlocomotion/drake/blob/7e6f81eeea16965ca278b173511192529e3407a2/drake/systems/controllers/BUILD.bazel#L120)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this line can be removed?
</blockquote></details>

OK I have been leaving it to highlight the lack of any deps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7428)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: thanks Jeremy!

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7428#-:-KyVj09TImkIR03rN-pt:byu6rlr)*

**Pull request merged**
