### PR TITLE
Cleanup of IiwaWsgPlantWithStateEstimator

### PR DESCRIPTION
**Pull request by naveenoid**
Helps in the clarity of more complex diagrams encapsulating this diagram.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5714)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@siyuanfeng-tri for feature review.

**Comment by siyuanfeng-tri** [comment]
:lgtm: +@ggould-tri for platform review. thanks 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 197 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5714#-Kgz5t7zP1GNYVCPJksN:-Kgz5t7zP1GNYVCPJksO:b55hqdh) ([raw file](https://github.com/robotlocomotion/drake/blob/d8c2fb5e1742e33806b7d40ea6809e609515f9e8/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L197)):*
> ```cpp
>   builder.Connect(model->get_output_port_wsg_state(),
>                   wsg_status_sender->get_input_port(0));
>   std::cout << "model->get_output_port_wsg_state() :"
> ```

BTW you want to print these?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5714#-:-Kgz7CrNXwhxGGH6hpq1:bbn27yv)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 197 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5714#-Kgz5t7zP1GNYVCPJksN:-KgzEI5bQvuvSa5MlkOF:b-mujuu4) ([raw file](https://github.com/robotlocomotion/drake/blob/d8c2fb5e1742e33806b7d40ea6809e609515f9e8/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L197)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW you want to print these?
</blockquote></details>

It's not intrinsically defective to print in an example but it would be much better to use `text_logging` to do so.  Also the messages are misleading as they do not match the calls they print.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5714#-KgzEn-t3mwWs5sSyodA:-KgzEn-t3mwWs5sSyodB:b-lophq7) ([raw file](https://github.com/robotlocomotion/drake/blob/d8c2fb5e1742e33806b7d40ea6809e609515f9e8/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L16)):*
> ```objc
> using systems::PassThrough;
> namespace examples {
> // using schunk_wsg::SchunkWsgStatusSender;
> ```

FYI Commented-out code should be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5714)*

**Comment by naveenoid** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 197 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5714#-Kgz5t7zP1GNYVCPJksN:-KgzF17mjJboQw7U6EIJ:b-qwdd79) ([raw file](https://github.com/robotlocomotion/drake/blob/5cb4ea8dc614d1e1e8d9916f6e71aeaa88d44287/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L197)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

It's not intrinsically defective to print in an example but it would be much better to use `text_logging` to do so.  Also the messages are misleading as they do not match the calls they print.
</blockquote></details>

Oh removed these lines..and caught a bug few lines below. Done!

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5714#-KgzEn-t3mwWs5sSyodA:-KgzGiJZObXxA1ZqXoi_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5cb4ea8dc614d1e1e8d9916f6e71aeaa88d44287/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L16)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI Commented-out code should be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5714)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5714#-:-KgzL9hiMiHtyuZsfegw:bnfp4nl)*

**Pull request merged**
