### PR TITLE
Deprecation - All things geometry

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
While this deprecation effort contains the normal deletion of deprecated API and its tests, it comes with a number of special cases -- some transitionary code had to be injected during the deprecation period between the old and new APIs. The explicit examples are called out below:

 - `RenderEngine`
   - The old API and new API were entangled such that derived `RenderEngine` types could overload either API and invoking one would eventually invoke the other. That mechanism has been removed and the default implementation now simply throws "not implemented" exceptions.
 - `SceneGraph`
   - `SceneGraph` went from storing `GeometryState` as abstract state to as an abstract `Parameter`. During transition, one could request the old behavior. That facility is now removed as well as the infrastructure that enabled it.

Implicit is the removal of *two* headers (but the contents of those headers had already been completely deprecated).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri for review, please. Possibly single reviewer? I'll defer to your feeling on it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855#-:-MXXmutiA7Sy7BiXTWqi:b3rz8wz)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with minor nit on non-deprecated build target, and pending Anzu CI testing.
Also fine w/ single reviewer +(status: single reviewer ok) 

Yayyyy!!! Deleted lines!

> Reviewed 40 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855#-:-MXbQSRf1SJ65SLOA6Sa:b-y1hnbz)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPOUuCgCn-f50Eh7o:-MXbPOUuCgCn-f50Eh7p:b-5k9ayg) (no related file):*
Working: Requires Anzu Drake bump, and then Anzu CI test to ensure nothing got missed.

---
___
*[geometry/BUILD.bazel, line 242 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPJI05HluTN883x4G:-MXbPJI05HluTN883x4H:b-3vlo9c) ([raw file](https://github.com/robotlocomotion/drake/blob/8f367b4831ea6b4cb4819e6248fccf1808f9f36c/geometry/BUILD.bazel#L242)):*
> ```Starlark
>     srcs = ["geometry_visualization.cc"],
>     hdrs = ["geometry_visualization.h"],
>     deps = [
> ```

nit Uh oh... we forgot to deprecate this target.

Options:

- :shrug: 
- Keep target (but still delete code), add deprecation, but redirect to code to access `DrakeVisualizer`
- Keep target (but still delete code), add deprecation, and make this add nothing.
___
*[geometry/render/BUILD.bazel, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPwll6k-mzdJyFqNp:-MXbPwll6k-mzdJyFqNq:b-tddk2k) ([raw file](https://github.com/robotlocomotion/drake/blob/8f367b4831ea6b4cb4819e6248fccf1808f9f36c/geometry/render/BUILD.bazel#L30)):*
> ```Starlark
> drake_cc_library(
>     name = "camera_properties",
>     hdrs = ["camera_properties.h"],
> ```

nit Also no deprecation here.

Same options as for other target.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPOUuCgCn-f50Eh7o:-MXbTZnD4YXfOz1VlQFp:b-g5ih6j) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Requires Anzu Drake bump, and then Anzu CI test to ensure nothing got missed.
</blockquote></details>

(Requires first fixing things in Anzu due to https://github.com/RobotLocomotion/drake/pull/14842#issuecomment-814137711 - oops!)

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPOUuCgCn-f50Eh7o:-MXbUzGRCiYv51aEKg21:b63wpf7) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(Requires first fixing things in Anzu due to https://github.com/RobotLocomotion/drake/pull/14842#issuecomment-814137711 - oops!)
</blockquote></details>

From this, I'm inferring you're heading up the Anzu side of things. Do you need anything from me?

---
___
*[geometry/BUILD.bazel, line 242 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPJI05HluTN883x4G:-MXbUOI78-cV6T_pXRyV:byrb524) ([raw file](https://github.com/robotlocomotion/drake/blob/8f367b4831ea6b4cb4819e6248fccf1808f9f36c/geometry/BUILD.bazel#L242)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Uh oh... we forgot to deprecate this target.

Options:

- :shrug: 
- Keep target (but still delete code), add deprecation, but redirect to code to access `DrakeVisualizer`
- Keep target (but still delete code), add deprecation, and make this add nothing.
</blockquote></details>

I know what you mean. We also didn't deprecate the *header* files. I asked @jwnimmer-tri about the headers and he made an argument for not worrying about it. If all the contents of the file have been deprecated, they've had ample warning and the cost of *now* removing includes (or declared dependencies) is small enough, to simply stomp.

I definitely think in the future, we should be more cognizant and apply deprecations on headers and build targets, but can apply :shrug: as a "solution" today.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPOUuCgCn-f50Eh7o:-MXbVY9G6xP0cudSkc5W:b-udl13y) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

From this, I'm inferring you're heading up the Anzu side of things. Do you need anything from me?
</blockquote></details>

Yup, I'll be heading it up! And nope, nothing needed from you here!
(I'm assuming Anzu CI w.r.t. this PR should be pretty straightforward, once LCM shenanigans are sorted out.)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPOUuCgCn-f50Eh7o:-MXcC2zS82x2h2siRVyi:b8uxwtm) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yup, I'll be heading it up! And nope, nothing needed from you here!
(I'm assuming Anzu CI w.r.t. this PR should be pretty straightforward, once LCM shenanigans are sorted out.)

</blockquote></details>

Soz for delay; CI is now churning on Anzu PR 6663

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[geometry/BUILD.bazel, line 242 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPJI05HluTN883x4G:-MXcCQ2T00G_oLKPUUC5:b-g7sj07) ([raw file](https://github.com/robotlocomotion/drake/blob/8f367b4831ea6b4cb4819e6248fccf1808f9f36c/geometry/BUILD.bazel#L242)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I know what you mean. We also didn't deprecate the *header* files. I asked @jwnimmer-tri about the headers and he made an argument for not worrying about it. If all the contents of the file have been deprecated, they've had ample warning and the cost of *now* removing includes (or declared dependencies) is small enough, to simply stomp.

I definitely think in the future, we should be more cognizant and apply deprecations on headers and build targets, but can apply :shrug: as a "solution" today.
</blockquote></details>

OK Sweet! I'm totes happy w/ :shrug:

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPOUuCgCn-f50Eh7o:-MXd8CIQ2AA412qvja2C:bk2v99t) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Soz for delay; CI is now churning on Anzu PR 6663
</blockquote></details>

No worries; when Anzu is ready, we can pull the trigger here.

---
___
*[geometry/render/BUILD.bazel, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPwll6k-mzdJyFqNp:-MXd86mj4r8-tPczGklO:bpvmuef) ([raw file](https://github.com/robotlocomotion/drake/blob/8f367b4831ea6b4cb4819e6248fccf1808f9f36c/geometry/render/BUILD.bazel#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Also no deprecation here.

Same options as for other target.
</blockquote></details>

Done

Same as the other note. This gets a :shrug:.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14855)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPOUuCgCn-f50Eh7o:-MXdJmsV7Cu69p98A4T3:bbpz7ml) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

No worries; when Anzu is ready, we can pull the trigger here.
</blockquote></details>

OK Ready!

---
___
*[geometry/render/BUILD.bazel, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14855#-MXbPwll6k-mzdJyFqNp:-MXdJkww9xSila92CufH:b1a3ok2) ([raw file](https://github.com/robotlocomotion/drake/blob/8f367b4831ea6b4cb4819e6248fccf1808f9f36c/geometry/render/BUILD.bazel#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

Same as the other note. This gets a :shrug:.
</blockquote></details>

OK :shrug: x 100!

**Pull request merged**
