### PR TITLE
Decrease DrakeVisualizer load message delay window size

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This is related to #7205.

By reducing the window for performing the *discrete* update from 1e-4 to 1e-8 the odds that the simulation would prevent the drake visualizer from successfully dispatching its load robot message are significantly reduced. (Easily reproduced by running a simulation with a fixed-step integrator and a time step of 0.99e-4 or smaller.)

This is merely extending the hack to make it more robust. Something more rigorous is probably unnecessary because 
    a) We have plans for the system which will allow better evaluation of "now" events, and
    b) This will mostly be supplanted by geometry world functionality.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7207)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@siyuanfeng-tri for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KvmO81tD09kHxUniGnW:bfwkpuv)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KvnKX-3UFN7QAyIv96B:b-rm2p6t)*

**Comment by siyuanfeng-tri** [comment]
I am curious why you are patching this,  do you want to make absolute sure that draw happens after load? I think the current setup will just not draw and cout a warning if the order of execution is wrong. 
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KvnMuJVNx3vw-fQPzd0:b-1jam0l)*

**Comment by SeanCurtis-TRI** [comment]
Well, in addition to the fact that you don't get any visualization, your console ends up spewing a *bazillion* messages that publish is called before load (which also hurts performance). An issue was dispatched regarding this (#6949) and this was interfering with *my* ability to address my task. Hence the effort. Except for the fact that I'm failing CI....

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KvnQBJFH6RqdCWMLj5j:b-wdiusp)*

**Comment by siyuanfeng-tri** [comment]
I see why you are doing thing, but suppose some body decided to set simulation context time to start from 3s not 0? 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KvnUaZPHVW84nvcabmI:b7raeci)*

**Comment by SeanCurtis-TRI** [comment]
I was vaguely wondering about that concern -- it can be addressed. How likely is it that someone does so? 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxDbc2KICetdTheqnYJ:bua7eko)*

**Comment by SeanCurtis-TRI** [comment]
@siyuanfeng-tri we discussed this in this neck of the woods.  Given the event-based solution was a hack in lieu of missing functionality, we decided that this hack was more robust. Thoughts?

+(status: curate commits before merging) 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxE1femUJ9GF3nXWRCD:bw8ga19)*

**Comment by siyuanfeng-tri** [comment]
honestly this is how I would have done it in the very first place. :lgtm: if platform doesn't complain. 
But I think the correct way to do this would be an explicit initialization method in the System public API. I have requested a long time ago, and was turned down for reasons I can't recall @sherm1 and @edrumwri not sure if you still remember. The other more obscure but still correct way is to have a "now" time for these events. But do this right, the simulator should have a while loop to make sure all the now events are processed, since downstream now events could have been triggered and need to be handled by upstream now updates. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxFXCXyi_vKXutypQ0k:b-n7agzq)*

**Comment by sherm1** [comment]
I want both an explicit initialization method (driven off the Simulator::Initialize() method) and the "now" events. There are issues filed for both I believe; they just need to be designed and implemented (carefully!). That seemed out of scope for this PR.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxFZRW0Da_v9SiBudrt:bc7rv5y)*

**Comment by jwnimmer-tri** [comment]
@siyuanfeng-tri The "now" event feature request is #5725, which is cited by #7205 mentioned in the top post here.

@SeanCurtis-TRI I strongly encourage you to change this PR to _any_ other solution than a mutable member field.  It is about the worst possible outcome for code that lives in Drake, because it violates the fundamental principle of the Systems framework.  If users want to do stuff like that, we can't stop them, but I would really prefer not to provide even a single, semi-temporary example in-tree that does it.

If the goal is to hack things up to hold us over until new features are done, what would be the downside of changing `0.0001` to be a smaller number, like [nextafter](http://en.cppreference.com/w/cpp/numeric/math/nextafter) ala `std::nextafter(context.get_time(), INFINITY)`.  To me that seems like an appropriate surgical fix.  Would not work in certain cases?  Certainly you can imagine integrator implementations that would break it, but in the land of "temporary hack" that this PR already claims to be, if tweaking the magic number works, then :shipit:.

**Comment by SeanCurtis-TRI** [comment]
@jwnimmer-tri I appreciate your concern, 100%.

I can answer *exactly* the question of using a "smaller" number (as that was what this PR originally looked like). The problem is that many tests (scattered around) have results that ended up being sensitive to "sneaking in an arbitrary small step". So, it wouldn't pass CI without my investigating all the failures and making sure that tweaking the testing parameters was reasonably well principled. Blech. So, tweaking the magic number by itself doesn't "work" (for some definition of "work").

That led to the alternative of setting an *absolute* time stamp which falls down when the simulator doesn't start at some time prior to the absolute step. I considered having `DrakeVisualizer` throw an exception if time was past the hard-coded time stamp without having sent the load message and supporting this with documentation. (With the vague assumption that it probably doesn't happen -- in fact, I haven't curated the commits for the express purpose of keeping the ability to roll back to this option.) This option, at least, passed CI.

This current approach *does* alleviates *all* of those issues. It has absolutely no impact on the simulator's efforts to advance time and is guaranteed not to be skipped. (In fact, the mutable stuff shouldn't be happening in `DoCalcNextUpdate()`, but in `DoPublish()`). In my opinion, this hack is no worse than the outright abuse of the event system. Furthermore, this is a system that will be dying when `GeometrySystem` and `MultibodyTree` are fully in play.  Obviously, it's not passing CI, and I'll have to look into why. It may well prove that this solution doesn't work in practice as much as picking a smaller magic number didn't work. So, rolling back one pass seems the most promising.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxIgQ2cX94aokDom7_4:b-x9ju7v)*

**Comment by jwnimmer-tri** [comment]
Interesting!  So a tough problem.

Is the reason its being worked now just because of text log spam, or is the sliding-relative-step problem preventing small-step integrator changes from becoming the default or something (because relative-time events are not supported)?

What if LOAD_ROBOT turned into a periodic discrete update, at say 10 Hz (emitting LOAD_ROBOT only when the State said to do so, as we do now)?  That solves the creeping-relative-time problem.  We could curate the text log spam to be not-annoying in that case.  The downside would be you'd miss the first 100ms of every simulation until #5725 got solved.

But at some point, really, the hacks have to stop and either #5725 gets worked, or the GeometryWorld-based visualization nukes this code.  I would almost rather just add some (possibly-limited) support for #5725, than keep iterating on hacks.  Six months ago I posted a small patch for #5275 (since deleted -- I think it was about 10 LOC though).  That might still be the right hack, at this point.

**Comment by sherm1** [comment]
I don't find the mutable hack here that terrible short term since it is just a one-time initialization and doesn't really feel like internal state. This seems to be the only such problem we've encountered so far -- are there other use cases now for which a general solution would help? 

The right solution IMO is an initialization event that happens once at simulation start and invokes Publish() with that event so the load message can be sent.  The Simulator does currently have a `publish_at_initialization` option but that is likely to be too big a hammer here.

**Comment by SeanCurtis-TRI** [comment]
The reason is two-fold:
  1. The occasional scenario when load robot simply never gets called, and
  2. the text log spam which, in turn, leads to reduced simulation performance (something that might otherwise run lickety-split -- a technical term of art -- is now throttled by system calls for writing to the console).

As for #5725, there is a lasting concern about two systems getting caught in a feedback loop where they keep making changes that triggers the other to need a "now" event. Did you address that in your small patch?

Your 10Hz discrete update solution would work, but it feels like a heavy hammer.  Ultimately, it will interact/interfere with the integrator (because the integrator is going to *have* to stop every 100 ms to do no work, regardless of what time step it would've/could've taken).

Alternatively:
1. `System` could have an `Initialize()` method invoked by the (e.g.,) the `Simulator::Initialize()` method. The semantics of this need to be reasoned about carefully. But something in this direction would *definitely* address this particular issue. Generally, it feels like this is a missing logical feature.
2. Require the user to explicitly call a method on a `DrakeVisualizer` method  to load the robot. It becomes part of the boilerplate of setting of the simulator. (The problem being what if they've buried the `DrakeVisualizer` in some block that isn't immediately visible?)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxIu0wSJyzdK3igXn8M:b-2jgrz7)*

**Comment by SeanCurtis-TRI** [comment]
@sherm1 I'm not convinced that the solution you've outlined would work (in those details).  The problem is that `Publish` is overloaded. Generally, `Publish` sends `update` LCM messages, but the first time, it would send a `load` message. To distinguish those two cases we need changeable state. So, maybe, there should be a *set* of initialization events which could invoke any/all of the event handlers. In this case, `DrakeVisualizer` would use the event handler *type* to distinguish which type of message gets sent.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxJ0CP3JrVFOVvQPKG-:bf4cent)*

**Comment by jwnimmer-tri** [comment]
I think you could have the 10 Hz update stop once the LOAD has been sent?

That means that `DoCalcNextUpdate` would look like:
- if LOAD has been sent, do not schedule any updates;
- otherwise, schedule an update for the next integer multiple of `period` in the future (possibly re-using the current periodic update logic);

You could probably even do 1000 Hz still, like `master`.  The innovation is that the LOAD event is not "now + 1ms", but rather "the next integral millisecond after now".

**Comment by sherm1** [comment]
@seancurtis-tri and I came up with what we think is a good design for the initialize event: treat it exactly how we treat "every time step" events:
- add an "initialize" event trigger type
- add a method `System::GetInitializeEvents()` with the same interface as `System::GetPerStepEvents()`
- that allows subsystems to decide if they want initialize events, and if so which handler they want invoked
- Simulator then issues the initialize events from its Initialize() method

@siyuanfeng-tri, does that seem workable?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxJBa8iLRqlMhvIGedf:b-oh3fx6)*

**Comment by siyuanfeng-tri** [comment]
@sherm1 @seancurtis-tri I am back! the proposal sounds reasonable to me, albeit a bit more complicated. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxrhLTACjh2wC8iBI1y:b-58n7pe)*

**Comment by siyuanfeng-tri** [comment]
sure, sounds like the perfect thing to work on while recovering from jet lag :) 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7207#-:-KxsbJ4-KQ7LFLUaOu8V:b-1eykhb)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please

**Comment by SeanCurtis-TRI** [comment]
This is being replaced by #7397.

**Pull request closed without merging**
