### PR TITLE
Revert "Adds USE_SYSTEM_VTK Option to Drake's Superbuild"

### PR DESCRIPTION
**Pull request by liangfok**
Reverts RobotLocomotion/drake#4089

Motivation: https://github.com/RobotLocomotion/drake/pull/4089#issuecomment-259506405

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4096)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4096#-:-KW9dHnEbj4VSScQ-0Hf:bcv4nxl)*

**Comment by mwoehlke-kitware** [comment]
Before reverting entirely, I'd like to know how big of a problem this actually is (see also [my reply](https://github.com/RobotLocomotion/drake/pull/4089#issuecomment-259510398) to @patmarion in #4089).

It seems we do need to at least drop the version check, but I'd prefer that to entirely reverting #4089.

**Comment by jwnimmer-tri** [comment]
:lgtm:

Continuous Production is broken.  Continuous Production needs to be green.  If there's a 1-line fix instead of a revert queued up, then great.  If not, unreverting in a new form with some other fixes is cheap.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4096#-:-KW9gpfzLA0GRzdyiiuJ:b-cnpfuc)*

**Comment by patmarion** [comment]
Recommend going ahead with the revert now...

**Pull request merged**
