### PR TITLE
Remove ode4

### LINKED ISSUE #2788: arrow3D and ode4 are unlicensed
Drake distributes the files `drake/thirdParty/nonfree/arrow3D.m` and `drake/thirdParty/nonfree/ode4.m`, but neither file appears to come with a license grant.  Unless we can obtain a such a license, we will have to stop using these two files.

arrow3D is used here:
- examples/grasping/forceClosure/ForceClosureContacts.m:138
- examples/grasping/forceClosure/ForceClosureContactsFixedFaces.m:94
- ~~solvers/trajectoryOptimization/ContactWrenchVisualizer.m:138~~ _(edit: retracted)_
- ~~systems/robotInterfaces/FootstepPlan.m:120~~ _(edit: retracted)_

ode4 is used here:
- examples/ZMP/LinearInvertedPendulum.m:291
- examples/dev/SpringFlamingo/SpringFlamingoPlant.m:7
- examples/dev/SpringFlamingo/SpringFlamingoPlant.m:48

arrow3D appears to be sourced from here, but note that this post has no license granted:
http://www.mathworks.com/matlabcentral/fileexchange/12274-3d-arrow-with-many-color-parameter-options/content/arrow3D_pub/arrow3D.m

ode4 appears to be sourced from here, but I can't find any copyright or license information:
http://www.nt.ntnu.no/users/skoge/diplom/diplom12/hansen/OLGA_Model_Simulations/ode4.m

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #2788 . The other file `SpringFlamingoPlant.m` also calls `ode4`. It should be removed also, as mentioned in #2814 .

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2816)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@siyuanfeng-tri for feature review.
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/ZMP/LinearInvertedPendulum.m, line 293 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2816#-KMhxOJ7pajeWLu-JbCB:-KMhxOJ8FTX8ynZ5qpOp:577402915) ([raw file](https://github.com/robotlocomotion/drake/blob/961cf7495668ca61acdb0999d14b9c970d0bdeb5/drake/examples/ZMP/LinearInvertedPendulum.m#L293)):*
> ```objc
>           [t,y] = ode45(@s2dynamics,fliplr(breaks),0);
>           ydot = zeros(size(y));
>           for i = 1:length(t)
> ```

:OK: fwiw - i think s2 dynamics could be vectorized fairly efficiently if performance was an issue.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2816#-:-KMhwk-7knIolKxL_-w4:195096558)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/ZMP/LinearInvertedPendulum.m, line 293 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2816#-KMhxOJ7pajeWLu-JbCB:-KMjjGu7vnEKXF5e1RaC:1657126997) ([raw file](https://github.com/robotlocomotion/drake/blob/961cf7495668ca61acdb0999d14b9c970d0bdeb5/drake/examples/ZMP/LinearInvertedPendulum.m#L293)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> :OK: fwiw - i think s2 dynamics could be vectorized fairly efficiently if performance was an issue.  
</details>
I partially vectorized the s2dynamics function in 55ddb07 (It still has a for loop inside, as it requires 3D matrix multiplication to compute `zbar` if `t` is a vector). This version is a lot faster than using a for loop to compute s2dynamics at each t(i). In the following test
```
tic; ydot = s2dynamics(t,y); toc
Elapsed time is 0.68 ms
tic; ydot2 = zeros(size(y)); for i = 1:length(t) ydot2(i) = s2dynamics(t(i),y(i)); end; toc
Elapsed time is 16 ms
```
So the partially vectorized version is more than 20 times faster than the un-vectroized version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2816)*

**Comment by jwnimmer-tri** [comment]
I can't review the new math, but LGTM in terms of removing `ode4` and all the associated files and paths.  Thanks!

**Comment by RussTedrake** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2816)*

**Comment by hongkai-dai** [comment]
@siyuanfeng-tri , could you review this one? Thanks a lot!

**Comment by rdeits** [comment]
Reviewed 2 of 3 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2816)*

**Comment by rdeits** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2816#-:-KN-g8f0pqZjpO5nAYwu:1417088721)*

**Comment by david-german-tri** [comment]
Hi, I'm going to temporarily label this "status: do not merge" to test that Reviewable is correctly enforcing that label.  If all goes well, I'll remove it within 5 minutes.  Apologies in advance for any inconvenience.

**Comment by david-german-tri** [comment]
Test successful!  Removing label now.

**Pull request merged**
