### PR TITLE
Contact Queries Refactor

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR simply is a refactor of `MBP::CalcAndAddContactForcesByPenaltyMethod()`. This will help code reuse when incorporating the Implcit Stribeck solver from #8925/#8941.

@SeanCurtis-TRI, I believe this also addresses #8948.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8971)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for feature review please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8971#-:-LEoS2m-8DGjLJJrb4Q3:b-4269ug)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: (with some passing comments). Ready for platform review: +@sammy-tri (Better if you can squeeze this in today as I'm platform reviewer tomorrow.)

---

Reviewed 2 of 2 files at r1.
Review status: all discussions resolved, platform LGTM from [seancurtis-tri], commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8971#-LEpiS-TDhKmNwOMgtyT:-LEpiS-U1BApH3LdMs01:b-dx9yx1) ([raw file](https://github.com/robotlocomotion/drake/blob/6f119d69eca39a00dbd044f012dec57adbc2862f/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L491)):*
> ```cpp
> MultibodyPlant<T>::CalcPointPairPenetrations(
>     const systems::Context<T>&) const {
>   DRAKE_ABORT_MSG("This method only supports Only T = double.");
> ```

BTW Two things:

1. Typo: "...only supports __*Only*__ T = double"
2. Would it be better to replace "this method" with the method name?

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 498 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8971#-LEpinDE1MzgJovKEYrW:-LEpinDE1MzgJovKEYrX:b5i55z5) ([raw file](https://github.com/robotlocomotion/drake/blob/6f119d69eca39a00dbd044f012dec57adbc2862f/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L498)):*
> ```cpp
> MultibodyPlant<T>::CalcCombinedFrictionCoefficients(
>     const std::vector<PenetrationAsPointPair<T>>& point_pairs) const {
>   std::vector<CoulombFriction<double>> combined_frictions(point_pairs.size());
> ```

BTW You could do this instead:

```c++
std::vector<CoulombFriction<double>> combined_frictions;
combined_frictions.reserve(point_pairs.size());
for (const auto& pair : point_pairs) {
...
combined_frictions.push_back(CalcContactFriction....);
}
```

I personally think that the ranger iterator looks better than the index iterator and, as near as I can tell, the only reason you have an index is because of the pre-sizing the output vector.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8971#-:-LEpjsXSBy2mxZ7cwQjG:bwtta8x)*

**Comment by sammy-tri** [comment]
:lgtm: (I'll let you decide how to resolve the outstanding BTWs)

---

Reviewed 2 of 2 files at r1.
Review status: all discussions resolved, platform LGTM from [seancurtis-tri, sammy-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8971#-:-LEq7Q0zBT1sEWzwmx9O:bhnt4zq)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all discussions resolved, platform LGTM from [seancurtis-tri, sammy-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8971)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all discussions resolved, platform LGTM from [seancurtis-tri, sammy-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8971)*

**Pull request merged**
