### PR TITLE
[solvers] Port solver back-ends to use SpecificOptions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20967.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21345)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 42 of 45 files at r1, 6 of 7 files at r2, 8 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21345)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 45 files at r1, 4 of 30 files at r5, 3 of 3 files at r7, 1 of 4 files at r8, 3 of 3 files at r9, 2 of 11 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21345)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`solvers/specific_options.h` line 25 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-O88Z-uT2F7-z0KvmJPp:-O88Z-uT2F7-z0KvmJPq:b-tb6vkp) ([raw file](https://github.com/RobotLocomotion/drake/blob/34db3a17131b09ae6b0e70cc93b4afe6dce372c6/solvers/specific_options.h#L25)):*
> ```objc
> generic SolverOptions struct into the specific solver's options API.
> 
> This class is intended a short-lived helper. It aliases an immutable list of
> ```

nit:  Ambiguous.  "Short-lived" as in "soon to be deprecated" or "short-lived" as in "narrowly scoped in the control flow"?



_Code quote:_
```objc
short-lived
```
___
*[`solvers/test/solver_base_test.cc` line 165 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-O8c-6oI2PVm0pUEBwAK:-O8c-6oI2PVm0pUEBwAL:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/34db3a17131b09ae6b0e70cc93b4afe6dce372c6/solvers/test/solver_base_test.cc#L165)):*
> ```cpp
> 
>   // In SolverBase, we have two flavors of DoSolve to test here. (This is the
>   // only test case were testing both is relevant / important.)
> ```

typo



_Suggestion:_
```cpp
where
```

**Comment by jwnimmer-tri** [comment]
For the next feature review, I'll want a fresh set of eyes so removing -@ggould-tri for now.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 9 files at r3, 1 of 1 files at r4, 29 of 30 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, 4 of 4 files at r8, 3 of 3 files at r9, 11 of 11 files at r10, 5 of 6 files at r11, 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21345)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai are you available for feature review, please?

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 45 files at r1, 1 of 7 files at r2, 2 of 9 files at r3, 14 of 30 files at r5, 3 of 3 files at r7, 3 of 3 files at r9, 7 of 11 files at r10, 2 of 6 files at r11, 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-:-O9zKYn-98fpU_AHuSDg:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/csdp_solver.cc` line 418 at r13](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-O9zCtpECOZsktFNXNpC:-O9zCtpECOZsktFNXNpD:b-ti9jcb) ([raw file](https://github.com/RobotLocomotion/drake/blob/14a06ed78d4514aa3c1c39f67f850d9bd34b0afa/solvers/csdp_solver.cc#L418)):*
> ```cpp
>       options->template Pop<int>("drake::RemoveFreeVariableMethod")
>           .value_or(static_cast<int>(RemoveFreeVariableMethod::kNullspace));
>   if (!(method >= 1 && method <= 3)) {
> ```

1 and 3 are magic number here? Maybe document them?

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-:-O9zR_5Q1Ie63R8ScdL-:bbnvyd5)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`solvers/csdp_solver.cc` line 418 at r13](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-O9zCtpECOZsktFNXNpC:-O9zRZ7Z0HkEFOQHTRo-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/14a06ed78d4514aa3c1c39f67f850d9bd34b0afa/solvers/csdp_solver.cc#L418)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

1 and 3 are magic number here? Maybe document them?
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 13 of 45 files at r1, 1 of 7 files at r2, 2 of 9 files at r3, 14 of 30 files at r5, 3 of 3 files at r7, 3 of 3 files at r9, 6 of 11 files at r10, 2 of 6 files at r11, 5 of 6 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-:-OA-5woeDtDeL7yOAi7-:bmxilld)* status: 1 unresolved discussion

___
*[`solvers/nlopt_solver.cc` line 336 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-OA-4dIP5XtR2XyGKX-h:-OA-4dIP5XtR2XyGKX-i:b-5m4ivq) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a7e71d9b3c67b65843a129877d0015216824273/solvers/nlopt_solver.cc#L336)):*
> ```cpp
> }
> 
> nlopt::algorithm ParseNloptAlgorithm(const std::string& algorithm) {
> ```

BTW Blech....a `string` called `algorithm` and a type `nlopt::algorithm`.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21345)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai

___
*[`solvers/nlopt_solver.cc` line 336 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-OA-4dIP5XtR2XyGKX-h:-OA-74gABhqCbgb45tQQ:b1vhuak) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a7e71d9b3c67b65843a129877d0015216824273/solvers/nlopt_solver.cc#L336)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Blech....a `string` called `algorithm` and a type `nlopt::algorithm`.
</blockquote></details>

Buffalo buffalo buffalo ...

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21345)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai

___
*[`solvers/nlopt_solver.cc` line 336 at r14](https://reviewable.io/reviews/RobotLocomotion/drake/21345#-OA-4dIP5XtR2XyGKX-h:-OA-J_tpC-l1Q9AGDUJo:b-r0xzty) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a7e71d9b3c67b65843a129877d0015216824273/solvers/nlopt_solver.cc#L336)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Buffalo buffalo buffalo ...
</blockquote></details>

I didn't even broach the `nlopt_algorithm`. So, how about that for buffaloes?

**Pull request merged**
