### PR TITLE
Add AutoDiffXd supported version of Lane::ToGeoPosition

### PR DESCRIPTION
**Pull request by jadecastro**
Also:
- Adopt the implementation in `dragway::Lane`.
- (minor) Reduce the test time for `dragway_test.cc`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7268)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@maddog-tri feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-:-KwamTI0pVNRRIEWXFXN:bvhss2)*

**Comment by maddog-tri** [comment]
Pass complete, please take a look.  (Much easier than the last one. :) )

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/api/lane.h, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-Kwg0HfVB-pP_LzgWwzP:-Kwg0HfVB-pP_LzgWwzQ:b-4r4eds) ([raw file](https://github.com/robotlocomotion/drake/blob/61cf1a1cf34ab925ca17e63263f6ad47be564990/drake/automotive/maliput/api/lane.h#L111)):*
> ```objc
>   /// appearing in lane_pos.  The provided lane_pos must be
>   /// internally-consistent; the s, r, and h variables must have derivatives of
>   /// equal size.
> ```

equal size... and identical meaning.  If one is (d/da, d/db), then they all have to be that, right?  

(One can't sensibly mix (d/da, d/db) with (d/db, d/dc) anywhere in the system, but there is no way to enforce this.  I think this is another AutoDiff timebomb.)

---

*[drake/automotive/maliput/api/lane.h, line 290 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-Kwg-TCU9J_feA4V-4xN:-Kwg-TCU9J_feA4V-4xO:b-vs7am5) ([raw file](https://github.com/robotlocomotion/drake/blob/61cf1a1cf34ab925ca17e63263f6ad47be564990/drake/automotive/maliput/api/lane.h#L290)):*
> ```objc
>     throw std::runtime_error(
>         "DoToGeoPosition has been instantiated with AutoDiffXd arguments, "
>         "but a Lane back-end has not overrided its AutoDiffXd specialization.");
> ```

"overridden" (same thing in next method)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-:-Kwg2fNWctvDu5YpDGtz:bgp5z78)*

**Comment by jadecastro** [comment]
I agree :)  Comments addressed.

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/api/lane.h, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-Kwg0HfVB-pP_LzgWwzP:-KwkoK6nOHMwxf4eJclc:bmeayhj) ([raw file](https://github.com/robotlocomotion/drake/blob/61cf1a1cf34ab925ca17e63263f6ad47be564990/drake/automotive/maliput/api/lane.h#L111)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

equal size... and identical meaning.  If one is (d/da, d/db), then they all have to be that, right?  

(One can't sensibly mix (d/da, d/db) with (d/db, d/dc) anywhere in the system, but there is no way to enforce this.  I think this is another AutoDiff timebomb.)
</blockquote></details>

Agree with you on the ordering being a fragile part of AutoDiff. But we can do our best to make the API documentation more precise in that regard, which is what I've done here.

---

*[drake/automotive/maliput/api/lane.h, line 290 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-Kwg-TCU9J_feA4V-4xN:-Kwl6FO9uqRJX5-cb9dX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/61cf1a1cf34ab925ca17e63263f6ad47be564990/drake/automotive/maliput/api/lane.h#L290)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

"overridden" (same thing in next method)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-:-Kwkmg1xgInAKleZ6kbu:bspd1xk)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-:-KwpDQbQd3FmKu9VC8SR:bnfp4nl)*

**Comment by jadecastro** [comment]
+@soonho-tri for platform review, thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-:-KwpDjy3GguEepmZovyH:bjn2pj0)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7268#-:-Kwu8yIw7LtnVQJ8B83A:bnfp4nl)*

**Pull request merged**
