### PR TITLE
Introduce pose data into the state

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
1. Add representations of frame and geometry poses
2. Add operations on those poses
3. Incidentally, include previously missing `GeometryInstance` test --
   confirm that it is compatible with `copyable_unique_ptr`.

* NOTE: The has function on the `InternalFrame` was deleted as an anachronism. It shouldn't have been committed in the first place.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6873)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@avalenzu They just keep on comin'.  More feature review fun and games.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-:-Krr9q9w37ejH2VgDfua:bmfnuyb)*

**Comment by avalenzu** [comment]
Review pass done. PTAL. Thanks for your patience!

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/geometry/geometry_frame.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9LzjUYIAQpNg7gAyy:-Ks9LzjVjz999tknUjgk:b-egrmyu) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/geometry_frame.h#L43)):*
> ```objc
>       : name_(frame_name), X_PF_(X_PF), frame_group_(frame_group_id) {}
> 
>   const std::string& get_name() const { return name_; }
> ```

FYI (Really For My Information): Do we have any guidance on when to use `get_foo()` and when to use `foo()`? I notice that the example in the style guide uses the latter.

---

*[drake/geometry/geometry_state.cc, line 253 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9OXq_ZT4AD3GGjDbG:-Ks9OXq_ZT4AD3GGjDbH:b-bdk11x) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/geometry_state.cc#L253)):*
> ```cpp
>   // Transform pose relative to geometry, to pose relative to frame.
>   const InternalGeometry& new_geometry = geometries_[new_id];
>   Isometry3<T> X_GP = X_FG_[new_geometry.get_engine_index()];
> ```

This should be `X_PG` given your comment above.

---

*[drake/geometry/geometry_state.cc, line 403 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9OsMnZbgsxjWI-g_w:-Ks9OsMnZbgsxjWI-g_x:bdnbtcf) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/geometry_state.cc#L403)):*
> ```cpp
>   // frame with the last pose index and moving it to the newly vacated hold.
>   // We do *not* copy the values in X_PF_ because changes to the topology should
>   // require these values to be recomputed to be valid.
> ```

Does "to be valid" refer to the "changes to the topology" or the "values?"

---

*[drake/geometry/geometry_state.h, line 380 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9QvUJzsxaYeU7CIBE:-Ks9QvUJzsxaYeU7CIBF:b-2871tz) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/geometry_state.h#L380)):*
> ```objc
>   //   1. geometries_[geometry_index_id_map_[i]].get_engine_index() == i.
>   //   2. geometry_index_id_map_.size() == geometries_.size().
>   std::vector<GeometryId> geometry_index_id_map_;
> ```

What's the rationale for not using a map for these?

---

*[drake/geometry/test/geometry_state_test.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9U2SKGVCl90OujieN:-Ks9U2SKGVCl90OujieO:b49ngq1) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/test/geometry_state_test.cc#L702)):*
> Technically also X_WG_

Since you're not testing `X_WG_` at this point, should this be a TODO?

---

*[drake/geometry/test/geometry_state_test.cc, line 908 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9Ukt099bPaZ7b4HEj:-Ks9Ukt099bPaZ7b4HEk:bd50b4g) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/test/geometry_state_test.cc#L908)):*
> ```cpp
>   // Expected results: 1 remaining geometry. Geometry's engine index has moved
>   // to zero. NOTE: These expectations are predicated on an underlying engine
>   // that is actually shuffling last geometry into the gap (vis a vis engine
> ```

FYI - nit: s/vis a vis/vis-à-vis/

---

*[drake/geometry/test/geometry_state_test.cc, line 909 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9V3XDxugwFcrpjo5f:-Ks9V3XDxugwFcrpjo5g:bw4og5c) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/test/geometry_state_test.cc#L909)):*
> If the engine changes behavior

I'd change this to "If the engine behavior changes."

---

*[drake/geometry/test/geometry_system_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9SOpDCJaECIC01Kh3:-Ks9SOpDCJaECIC01Kh4:bndxfcj) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/test/geometry_system_test.cc#L11)):*
> ```cpp
> #include "drake/geometry/geometry_instance.h"
> #include "drake/geometry/query_handle.h"
> #include "drake/geometry/shape_specification.h"
> ```

Why does this need to be added? None of the other changes to this file use shape specifications.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-:-Ks9VRr9xfaHIVIs9d7i:blxxxgw)*

**Comment by SeanCurtis-TRI** [comment]
I figured since I didn't have it passing CI, you were off the hook.  :)  Thanks for reviewing anyways.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/geometry/geometry_frame.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9LzjUYIAQpNg7gAyy:-Ks9cZqJ6BZl3TdTJ8LL:b-a5az9v) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/geometry_frame.h#L43)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

FYI (Really For My Information): Do we have any guidance on when to use `get_foo()` and when to use `foo()`? I notice that the example in the style guide uses the latter.
</blockquote></details>

FYI `foo()` is not *required* but it is allowed. At one point I considered moving to `foo()` in the name of compactness, but I didn't want to have it mixed. After getting all the basic API in (and before it's integrated with other code), I might do a `get_*()` to `*()` pass.

---

*[drake/geometry/geometry_state.cc, line 253 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9OXq_ZT4AD3GGjDbG:-Ks9lXWjBeQtoVmcqLtU:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/geometry_state.cc#L253)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

This should be `X_PG` given your comment above.
</blockquote></details>

Done

---

*[drake/geometry/geometry_state.cc, line 403 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9OsMnZbgsxjWI-g_w:-Ks9ljyVbxSNcf3Xowg1:bmq2566) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/geometry_state.cc#L403)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Does "to be valid" refer to the "changes to the topology" or the "values?"
</blockquote></details>

Reworded PTAL

---

*[drake/geometry/geometry_state.h, line 380 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9QvUJzsxaYeU7CIBE:-Ks9d1oIOuLHSeprt8el:b-4i3l5f) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/geometry_state.h#L380)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

What's the rationale for not using a map for these?
</blockquote></details>

`Identifier`s always require maps because you have no guarantee as to the value of any given `id`. `TypeSafeIndex` types are intended to be used as index values in vectors. Given that distinction, why pay the map cost when the location *is* the mapping?

---

*[drake/geometry/test/geometry_state_test.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9U2SKGVCl90OujieN:-Ks9lvmxPQGlOL820-Rz:b-48puo1) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/test/geometry_state_test.cc#L702)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> Technically also X_WG_

Since you're not testing `X_WG_` at this point, should this be a TODO?
</blockquote></details>

Done 

That comment was an aborted comment that never got cleaned up. As the implementation documentation in `GeometryState::RemoveGeometryUnchecked` implies, there are no guarantees as to what is in `X_WG_` immediately after removal.

---

*[drake/geometry/test/geometry_state_test.cc, line 908 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9Ukt099bPaZ7b4HEj:-Ks9mI6wm1EGM85xKA0R:b1j68vr) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/test/geometry_state_test.cc#L908)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

FYI - nit: s/vis a vis/vis-à-vis/
</blockquote></details>

Done  (c'est la vie...:D)

---

*[drake/geometry/test/geometry_state_test.cc, line 909 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9V3XDxugwFcrpjo5f:-Ks9mO3bpwCknqYPJRYf:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/test/geometry_state_test.cc#L909)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> If the engine changes behavior

I'd change this to "If the engine behavior changes."
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_system_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9SOpDCJaECIC01Kh3:-Ks9kxF_qYMiVpF29Ky6:bnykgfd) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/test/geometry_system_test.cc#L11)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Why does this need to be added? None of the other changes to this file use shape specifications.
</blockquote></details>

This reflects a fix on the former code -- the "include what you use" rule. (https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes). Specifically, this file should not rely on the fact that `geometry_instance.h` includes `shape_specification.h`. It needs to include it itself. This is generally a hard rule to enforce, but I thought I'd sneak in the patch.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-:-Ks9cUx6nWjvirKU4yC2:b-x3aegb)*

**Comment by avalenzu** [comment]
:lgtm: +@sammy-tri for feature review.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/geometry/geometry_state.h, line 380 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-Ks9QvUJzsxaYeU7CIBE:-KsASRZzRwCpZ9xfR-sa:b-wsvas3) ([raw file](https://github.com/robotlocomotion/drake/blob/deed6ebe90f1c65c13740ff376903d42ebcdd620/drake/geometry/geometry_state.h#L380)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

`Identifier`s always require maps because you have no guarantee as to the value of any given `id`. `TypeSafeIndex` types are intended to be used as index values in vectors. Given that distinction, why pay the map cost when the location *is* the mapping?
</blockquote></details>

Thanks for the explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-:-KsAXCU_Jw0RzZmkp7Mc:b188ptm)*

**Comment by sammy-tri** [comment]
First pass complete, just one minor nit.

---

Reviewed 8 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/geometry/test/geometry_instance_test.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-KsAoBQWzrmVU_piPggz:-KsAoBQWzrmVU_piPgh-:b-ay0wkg) ([raw file](https://github.com/robotlocomotion/drake/blob/e6d6aea80d6a9efad4eca473705bcca7cd65ff4b/drake/geometry/test/geometry_instance_test.cc#L14)):*
> ```cpp
> namespace {
> 
> using Pose = Isometry3<double>;
> ```

I don't see where this using actually gets used?  (if it's not, presumably that extends to `eigen_types.h` too?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-:-KsArKUgwqzvOAH1BD5F:bvns8fb)*

**Comment by SeanCurtis-TRI** [comment]
Nit unknitted.

---

Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/geometry/test/geometry_instance_test.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-KsAoBQWzrmVU_piPggz:-KsB-tM4AbJBqkXbeNPC:b-enxatw) ([raw file](https://github.com/robotlocomotion/drake/blob/e6d6aea80d6a9efad4eca473705bcca7cd65ff4b/drake/geometry/test/geometry_instance_test.cc#L14)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't see where this using actually gets used?  (if it's not, presumably that extends to `eigen_types.h` too?)
</blockquote></details>

Done D'oh!  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-:-KsB0o9kD7rO1JY6gGaX:b-jdbxoy)*

**Comment by avalenzu** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6873)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6873#-:-KsEP5DxFYsRrzNMQ1Yw:bnfp4nl)*

**Pull request merged**
