### PR TITLE
workspace: Update externals to latest

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12014)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-cxx17-release please

(Nope; still requires the tiny button instead of the big one.)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please (low priority).
\CC @jamiesnape FYI

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-cxx17-release please

**Comment by jamiesnape** [comment]
(qdldl released a new version a few hours after you created this PR.)

**Comment by jwnimmer-tri** [comment]
I'm explicitly avoiding touching OSQP, SQS, QDLDL until #11883 tackles them all at once.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review tomorrow per schedule, please.

**Pull request merged**
