### PR TITLE
math: Deprecate expmap.h

### LINKED ISSUE #14058: drake::math::expmap2quat() should use std::pow().
After upgrading to Drake v0.16.0, my drake::math::expmap2quat() function call fails in compilation stage. Under this drake::math::expmap2quat() function, the [pow() function](https://github.com/RobotLocomotion/drake/blob/6bd5f8c25cdcbb4049e57ec0f49f6e2c136d864a/math/expmap.h#L68) should be std::pow(). 
After some look up, I think the cause is: the implementation of another pow() function (https://github.com/RobotLocomotion/drake/pull/12835) confuses the compiler.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #14058.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14099)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  Thanks Jeremy!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14099#-:-MHdWy-Q6eDvVZlZ1a11:b-mmbdvj)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14099#-:-MHl88LYBUPUlns6NwV7:bmxilld)* status: needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@hongkai-dai for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14099#-:-MHl8DRk-hrMtIvDu_D-:b-fcupkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai

**Pull request merged**
