### PR TITLE
Set tighter tolerances for finding fixed-point

### PR DESCRIPTION
**Pull request by sheim**
See #1563.

For my case, 'MajorFeasibilityTolerance' was the only tolerance required, but I'm assuming all three ('MajorOptimalityTolerance' and 'MinorFeasibilityTolerance' too) should be enforced.

### CODE REVIEW

**Comment by RussTedrake** [comment]
given @hongkai-dai 's comment on #1563, it seems like this isn't the right fix.  presumably what happened is that you called tilyap and had a mysterious failure, which you fixed by tightening the optimization tolerance.  Maybe a better solution is to check the tolerance in tilyap and throw a useful warning if it fails the test?

**Comment by sheim** [comment]
Indeed, I see that the case I tested on just happened to be lucky.

From page 76 of the SNOPT user guide (7.4) I found what @hongkai-dai is referring to, but since the solution should be 0 (fixedpoint), I'm confused how this applies...  
I might be missing something but even if the solution wasn't 0, how would we know the solution-norm a priori? My guess is that the norm should be put into the constraint definition, and not in the tolerance?

I've added a MWE, essentially the CubicPolynomialExample, without providing the fix-point and candidate Lyapunov function and instead having Drake find those for you. This is where, tilyap() wants a fixed-point that is <e-10, but the FixedPointProgram often delivers something less precise if the guess is not great (you can try for example CubicPolynomialExample.genericSOS(0.1)).

**Comment by hongkai-dai** [comment]
Is your fixed-point at the origin? If so, I do not know how SNOPT handles the feasibility tolerance. If it is not zero, and you know the range of the solution magnitude (you can find such range by setting the feasibility tolerance high in the first pass, retrieve the solution, and the compute its magnitude), then the feasibility tolerance can be adjusted according to the solution magnitude, and you could solve the problem again with a tighter tolerance. Here I assume that the solution with tighter tolerance is in the neighbourhood of the solution with larger tolerance.

**Comment by sheim** [comment]
Indeed, at the origin, sorry for the confusion. I'll look into how that should be handled and get back to you.

**Comment by hongkai-dai** [comment]
I think solving FPP iteratively makes sense. Let me know if SNOPT throws info 3, that means the required precision cannot be achieved.

**Comment by sheim** [comment]
Made a basic implementation with an optional tol that makes a second pass.

I haven't tested it extensively, but it it rarely improved the result for the CubicPolynomialExample: I _almost_ always got Warning 41: cannot improve solution (info 3) if the first pass wasn't good enough to start with.

FWIW, the tolerance is normalised by max(xNorm,1) where xNorm is the infinity norm, so that's how it handles solutions at/close to the origin.  
Also, some SNOPT guys mentioned that a tolerance of 1e-10 or smaller is really pushing it : ). Is there a specific reason most approximation methods in Drake (as far as I can tell) require fixed-points to be within that tolerance? Maybe that should be relaxed, or do you have some better way of getting good tolerances on fixed-points that I'm missing?

**Comment by anirudhamajumdar** [comment]
In this case it seems like you don't need to iteratively solve, right? Since we know that xNorm is 0, the normalization is always 1. So, in this case I think that setting the tolerance to 1e-10 is the right thing to do. I don't think this is too much to ask from snopt on this problem - this should be a very easy problem for snopt (I've used matlab's fzero function for this kind of problem before and have had no trouble setting tight tolerances).

As for error 41, in my experience it's typically caused by errors in the gradients. Could you confirm that the gradient checks are passed?

**Comment by RussTedrake** [comment]
@anirudhamajumdar — what about for more general problems?  i think this was a toy example, but in practice what tolerance do you think we need for the sdp solvers to be happy with the sos formulation?

**Comment by anirudhamajumdar** [comment]
For the sos problems I think it depends a lot on how the sos problem is posed. The sos linear equations typically are satisfied in the 1e-9 or 1e-10 range I believe (on a good day). So if a precision of 1e-10 on the snopt problem corresponds to a 1e-10 on the sdp linear equations, then this tolerance should probably be ok. But this correspondence may not always hold and will be problem dependent.

**Comment by RussTedrake** [comment]
I think the question is the other way around.  If i aim to demonstrate a lyapunov proof via sdp/sos where my fixed point is numerically not quite a perfect fixed point, then how much tolerance can I accept there?

**Comment by anirudhamajumdar** [comment]
What I was saying in the previous post addresses this question I think. If the fixed-point is not quite perfect, but the error is smaller than the tolerances to which sdp solvers solve their linear equations, this imperfection should be ok.

But the complicating factor is that an error of epsilon in f(x0) doesn't correspond directly to an error of epsilon in the sos linear equations. Things like scaling of the sos constraints and the scaling of the Lyapunov functions change the linear equations.

**Comment by sheim** [comment]
For the regular CubicPolynomialExample, no it isn't necessary. It came into effect and made a difference for cases when I shifted the CubicPolynomialExample far along the x-axis, i.e. xdot = -(x-10000)+(x-10000)^3.  

About the gradient checks, that seems to be the issue. Implementing the gradient by hand in the dynamicsRHS method just threw me the error "Assignment has more non-singleton rhs dimensions than non-singleton subscripts", I'll get back to you once I sort that out.

**Comment by sheim** [comment]
Sorry, last time I just edited my previous post without thinking it doesn't trigger a new email, and I've been travelling since.

Anyhow, the gradients check out, SNOPT still sometimes gets stuck with either warning 41 or 3, but it seems like it's actually hitting it's limit. Having tried it a bit more the second-pass does improve the solution more often than I thought, even when it doesn't need to be scaled.

I've included in the pull-request the gradients for Cubic-Polynomial, and how to set up the sosExample programmatically (in comments), which includes finding the fixpoint (which is how I came into this problem).

Btw, when no gradients are implemented in the model-class, what does Drake default to? I would have assumed numerical gradients, but if that's the case why does it not match up with checkGrad?

**Comment by hongkai-dai** [comment]
If no gradients are implemented, drake is default to do taylor expansion of the function, and then evaluate the taylor expansion. This taylor expansion approach is slower than user implemented gradient, but it should be accurate. On the other hand, numerical gradient is not accurate.

**Comment by RussTedrake** [comment]
code looks great.  (and i've added you to the build server whitelist for the future; thanks for the contributions).

**Comment by RussTedrake** [comment]
test this please

**Pull request merged**
