### PR TITLE
Add benchmark on symbolic polynomial.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17714)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17714#-:-N99eHds50XlOVIHZbvc:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17714#-:-N9Br75-2QZru0Ap7ABP:b-n37teh)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/benchmarking/benchmark_polynomial.cc` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9BmmPLA2myZoqwQors:-N9BmmPLA2myZoqwQort:bk0wn9e) ([raw file](https://github.com/robotlocomotion/drake/blob/3a82a7f85e1e007f060002d7dbe5857612034f71/common/benchmarking/benchmark_polynomial.cc#L10)):*
> ```cpp
> namespace symbolic {
> namespace {
> static void BenchmarkPolynomialEvaluatePartial(
> ```

nit In an anonymous namespace, no need for `static`.



_Suggestion:_
```cpp
void BenchmarkPolynomialEvaluatePartial(
```
___
*[`common/benchmarking/benchmark_polynomial.cc` line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9BpSogCOkmj-8n-s5g:-N9BpSogCOkmj-8n-s5h:b1ai8rc) ([raw file](https://github.com/robotlocomotion/drake/blob/3a82a7f85e1e007f060002d7dbe5857612034f71/common/benchmarking/benchmark_polynomial.cc#L15)):*
> ```cpp
>   for (int i = 0; i < 12; ++i) {
>     x(i) = symbolic::Variable("x" + std::to_string(i));
>   }
> ```

nit For setting up `x`, can we use `MakeVectorVariable` for clarity, instead of manually looping?
___
*[`common/benchmarking/benchmark_polynomial.cc` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9Bo63_DJT40DJozUkS:-N9Bo63_DJT40DJozUkT:b-4wktuv) ([raw file](https://github.com/robotlocomotion/drake/blob/3a82a7f85e1e007f060002d7dbe5857612034f71/common/benchmarking/benchmark_polynomial.cc#L39)):*
> ```cpp
>     }
>   }
>   Eigen::MatrixXd S_val = Eigen::MatrixXd::Ones(S.rows(), S.cols());
> ```

nit I think `S_val` is unused?
___
*[`common/benchmarking/benchmark_polynomial.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9BobFR4ZpyRbhtPUnb:-N9BobFR4ZpyRbhtPUnc:b7eutfb) ([raw file](https://github.com/robotlocomotion/drake/blob/3a82a7f85e1e007f060002d7dbe5857612034f71/common/benchmarking/benchmark_polynomial.cc#L41)):*
> ```cpp
>   Eigen::MatrixXd S_val = Eigen::MatrixXd::Ones(S.rows(), S.cols());
>   symbolic::Environment env;
>   env.insert(S_upper, Eigen::VectorXd::Ones(S_upper.rows()));
> ```

nit For the purposes of a benchmark, it's important that the `EvaluatePartial` below doesn't experience any atypical cancellation of terms, where the performance here would be unlike a real-world application. 

I'm pretty sure that using `Ones` here just ends up adding the basis(i)*basis(j) terms without any cancellation, so there is no problem, but it would be good if you could double-check me on that and maybe add a comment here helping explain to the next person reading this code why `Ones` is satisfactory (i.e., why we don't need something more complicated like LinSpaced or 1,2,4,8,16,... or etc).
___
*[`common/symbolic/polynomial.cc` line 566 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9BqnLVDhpTQCPJmA8v:-N9BqnLW47mizugkjVPF:bcppj3p) ([raw file](https://github.com/robotlocomotion/drake/blob/3a82a7f85e1e007f060002d7dbe5857612034f71/common/symbolic/polynomial.cc#L566)):*
> ```cpp
> Polynomial Polynomial::EvaluatePartial(const Environment& env) const {
>   MapType new_map;  // Will use this to construct the return value.
> ```

nit From your comment at https://github.com/RobotLocomotion/drake/pull/17701#pullrequestreview-1069112192, I think perhaps the changes to polynomial.cc here and mp_result.cc below are unintentional, for this PR?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17714)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/benchmarking/benchmark_polynomial.cc` line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9BpSogCOkmj-8n-s5g:-N9ChSLaBeDIwZGULZDB:b26lzj6) ([raw file](https://github.com/robotlocomotion/drake/blob/3a82a7f85e1e007f060002d7dbe5857612034f71/common/benchmarking/benchmark_polynomial.cc#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For setting up `x`, can we use `MakeVectorVariable` for clarity, instead of manually looping?
</blockquote></details>

Done. I didn't know we have this function before.
___
*[`common/benchmarking/benchmark_polynomial.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9BobFR4ZpyRbhtPUnb:-N9CiRCaCqrXeNIuyUQI:b-iudpjk) ([raw file](https://github.com/robotlocomotion/drake/blob/3a82a7f85e1e007f060002d7dbe5857612034f71/common/benchmarking/benchmark_polynomial.cc#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For the purposes of a benchmark, it's important that the `EvaluatePartial` below doesn't experience any atypical cancellation of terms, where the performance here would be unlike a real-world application. 

I'm pretty sure that using `Ones` here just ends up adding the basis(i)*basis(j) terms without any cancellation, so there is no problem, but it would be good if you could double-check me on that and maybe add a comment here helping explain to the next person reading this code why `Ones` is satisfactory (i.e., why we don't need something more complicated like LinSpaced or 1,2,4,8,16,... or etc).
</blockquote></details>

Done. I added some documentation.
___
*[`common/symbolic/polynomial.cc` line 566 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9BqnLVDhpTQCPJmA8v:-N9CixCNCz2zgXgdB5jg:baqlhe6) ([raw file](https://github.com/robotlocomotion/drake/blob/3a82a7f85e1e007f060002d7dbe5857612034f71/common/symbolic/polynomial.cc#L566)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit From your comment at https://github.com/RobotLocomotion/drake/pull/17701#pullrequestreview-1069112192, I think perhaps the changes to polynomial.cc here and mp_result.cc below are unintentional, for this PR?
</blockquote></details>

Done. Sorry I sneaked in this code in the PR.

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule, please.

+(priority: high) since we have other PRs on deck after this one lands.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17714#-:-N9CxvBGCqV-sMWccFce:b-fjnxym)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[`common/benchmarking/benchmark_polynomial.cc` line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9Cy82h2NZPnsKT_Ymj:-N9Cy82h2NZPnsKT_Ymk:bf2qgda) ([raw file](https://github.com/robotlocomotion/drake/blob/220dec1a168a0fcfe85a5091dd53d7a24d160f9f/common/benchmarking/benchmark_polynomial.cc#L12)):*
> ```cpp
> void BenchmarkPolynomialEvaluatePartial(
>     benchmark::State& state) {  // NOLINT
>   Eigen::Matrix<symbolic::Variable, 12, 1> x = MakeVectorContinuousVariable(12, "x");
> ```

nit >80 cols (linter failure)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17714)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`common/benchmarking/BUILD.bazel` line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17714#-N9D-jNoEo2-pSuZtL3G:-N9DFk9O4OLcIaChnpTz:b-yh10tr) ([raw file](https://github.com/robotlocomotion/drake/blob/220dec1a168a0fcfe85a5091dd53d7a24d160f9f/common/benchmarking/BUILD.bazel#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why `package()` is not at top.

(I assume `buildifier` will fix this?)
</blockquote></details>

Done. Good catch

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17714)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
