### PR TITLE
Add Dockerfile for Binder

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #11962.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12472)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Per f2f, would be good to try `.binder/` folder.

**Comment by jamiesnape** [comment]
Aside of debates about nightly tags this is ready. Before this merges, the magic URL is https://mybinder.org/v2/gh/jamiesnape/drake/binder?filepath=tutorials

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review.

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for platform review.

**Pull request merged**
