### PR TITLE
[multibody] Add output port for deformable configurations

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17972)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17972#-:-NCbfRLkEaGOTlj0YRG7:b-ec6d43)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with one optional suggestion.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17972#-:-NCv6NcR8SDVnSF-MtJh:b-qzfc07)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/plant/deformable_model.cc` line 189 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17972#-NCv5UMm8Oxf6glJG5xI:-NCv5UMm8Oxf6glJG5xJ:bmlkq2q) ([raw file](https://github.com/robotlocomotion/drake/blob/75cd83044191df2ec75d95511d33a8ccca70e0d3/multibody/plant/deformable_model.cc#L189)):*
> ```cpp
>               },
>               [this](const systems::Context<T>& context,
>                      AbstractValue* output) {
> ```

BTW this is awkward to read as a lambda. Consider making a private method named something like CollectVertexPostions() and then referencing that here. That way it would be easier to see at a glance what this output port is doing while hiding the details of how it does it.

**Review by sherm1 — COMMENTED** [review]
+@ggould-tri for platform review per rotation, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17972#-:-NCv6VtbE2RUv0lSVHCC:b-gat8md)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17972)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

___
*[`multibody/plant/deformable_model.cc` line 189 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17972#-NCv5UMm8Oxf6glJG5xI:-NCv6dS5D4rCAlwcOiCe:bvzcpn5) ([raw file](https://github.com/robotlocomotion/drake/blob/75cd83044191df2ec75d95511d33a8ccca70e0d3/multibody/plant/deformable_model.cc#L189)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is awkward to read as a lambda. Consider making a private method named something like CollectVertexPostions() and then referencing that here. That way it would be easier to see at a glance what this output port is doing while hiding the details of how it does it.
</blockquote></details>

Working.

This is not completely trivial to do. The `DeclareAbstractOutputPort()` function is exposed via `PhysicalModel` API. We have only exposed the most generic variant with the std::function callback. So we'd have to use `std::bind` if we go the member function route. But I guess that's still more readable than spilling the guts of the function here.

**Comment by jwnimmer-tri** [comment]
*[`multibody/plant/deformable_model.cc` line 189 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17972#-NCv5UMm8Oxf6glJG5xI:-NCv8vvz5JRFoT-xsqgp:b-bx51mn) ([raw file](https://github.com/robotlocomotion/drake/blob/75cd83044191df2ec75d95511d33a8ccca70e0d3/multibody/plant/deformable_model.cc#L189)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working.

This is not completely trivial to do. The `DeclareAbstractOutputPort()` function is exposed via `PhysicalModel` API. We have only exposed the most generic variant with the std::function callback. So we'd have to use `std::bind` if we go the member function route. But I guess that's still more readable than spilling the guts of the function here. 
</blockquote></details>

FYI the lambda here can directly call the newly-extracted member function (no need for `std::bind` hijkins).  (The objective is to move the logic elsewhere.  Using a lambda in the first place is not the defect.)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: pending resolution of discussion below
 (I agree with the consensus there:  A one-line lambda calling out to a private member or free function is the best choice -- tidies the code, makes the interface and const semantics explicit). 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17972#-:-NCvHvha1-__vxNaU9pA:b3wmguf)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @sherm1)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17972)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @ggould-tri and @sherm1)

___
*[`multibody/plant/deformable_model.cc` line 189 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17972#-NCv5UMm8Oxf6glJG5xI:-NCv_R4d6FhON3mZaYee:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/75cd83044191df2ec75d95511d33a8ccca70e0d3/multibody/plant/deformable_model.cc#L189)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Good idea, I will do that. Thanks!
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17972)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
