### PR TITLE
[workspace] Upgrade drake_models to latest commit

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21230)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21230)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21230#-NuPYQbW5XxVa70eIpyQ:-NuPYQbW5XxVa70eIpyR:brs0vgj) ([raw file](https://github.com/RobotLocomotion/drake/blob/cc11f07288b005425abccf9ee2974fb1a5a5f429/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "4693b86786a9708d6c6ba148a388ab9dca17be8d",
> ```

Working temporary SHA1 until the models PR [52](https://github.com/RobotLocomotion/models/pull/52) is merged.`

**Review by rpoyner-tri — COMMENTED** [review]
version bump to capture https://github.com/RobotLocomotion/models/pull/52 ; no functional changes.

+@jwnimmer-tri for both reviews, please. +(release notes: none) +(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21230#-:-NuPYtGoAvq5OZOWKciJ:b-h10sh8)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM pending fixed sha.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21230#-:-NuPnja118BgVf-ST50w:b-2lqdia)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
SHA is fixed; awaiting build results.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21230#-:-NuPupWR68TmKuH8KRta:b-yjz3oe)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21230#-:-NuQ3-mr9oNJqQOAacNc:bb6yyy8)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
