### PR TITLE
workspace: add patches and update vtk dockerfile

### PR DESCRIPTION
**Pull request by jamiesnape**
Also remove vestigial embree build script. Patches should have been commited when focal support was added, but they all date back to various revisions of the vtk homebrew formulae, so are not new.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14393)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Passing builds related to this are in #14395.

**Review by EricCousineau-TRI — COMMENTED** [review]
Given removal of `do not review` tag, assuming this is ready for review.
+@ericcousineau-tri for both reviews, assigning per platform reviewer rotation
+(status: single reviewer ok) 

Per above comment, confirmed passing unprovisioned builds here:
https://drake-jenkins.csail.mit.edu/job/mac-catalina-unprovisioned-clang-bazel-experimental-release/62/
https://drake-jenkins.csail.mit.edu/job/linux-bionic-unprovisioned-gcc-bazel-experimental-release/104/
https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-experimental-release/117/

:lgtm: given positive evidence and for the sake of moving forward.
Reservations on patches, but commented below.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14393#-:-MNxDMl94mq8GLa7HMdZ:bjyzo8z)* status: 1 unresolved discussion (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14393#-MNxEbko8m0voknJE45i:-MNxEbkpD8MQXHu5hCKR:b-nzwb2f) (no related file):*
nit It's unclear what the future is for these patches.

Are they something that lived in upstream, but got reverted (e.g. the 2017 patch)?
Or will they be merged?

Are there PR links that other maintainers can check against?

---

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14393#-:-MNxyWp984qOWqFgpPNR:b-n37teh)* status: 1 unresolved discussion (waiting on @jamiesnape)

**Comment by jamiesnape** [comment]
The patches should disappear with the VTK upgrade to 9.0. If, for some reason do not, they can be upstreamed, but VTK 8.2 is too old for anything to be fixed there.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14393)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14393#-MNxEbko8m0voknJE45i:-MNyAIH_9jALpsmza6-J:b-lyfssu) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It's unclear what the future is for these patches.

Are they something that lived in upstream, but got reverted (e.g. the 2017 patch)?
Or will they be merged?

Are there PR links that other maintainers can check against?
</blockquote></details>

The patches should disappear with the VTK upgrade to 9.0. If, for some reason do not, they can be upstreamed, but VTK 8.2 is too old for anything to be fixed there. As an example, he 2017 patch is no longer applicable with the new module system AFAIK.

VTK 9.0 upgrade is scheduled for very soon, also.

---

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14393#-MNxEbko8m0voknJE45i:-MNyBt4OCh6f_hJSwgaE:b-1rmnk4) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

The patches should disappear with the VTK upgrade to 9.0. If, for some reason do not, they can be upstreamed, but VTK 8.2 is too old for anything to be fixed there. As an example, he 2017 patch is no longer applicable with the new module system AFAIK.

VTK 9.0 upgrade is scheduled for very soon, also.
</blockquote></details>

OK Sounds good! Ideally this would be encoded in a README, but not a huge issue.

---

**Pull request merged**
