### PR TITLE
[geometry] Use Cylinder's meshes with medial axes in hydroelastics.

### LINKED ISSUE #12128: Improve tetrahedral mesh connectivity for cylinders and boxes.
We should improve mesh connectivity to support Hydroelastic contact model. There are two problems that I found after visualizing the tetrahedral meshes.

1. MakeBoxVolumeMesh() creates a tetrahedral mesh of a box that has some tetrahedra with all vertices on the box boundary. These tetrahedra will define zero extent field in their volume.  This picture shows some of these tetrahedra.
image

2. MakeCylinderMesh() creates a tetrahedral mesh of a cylinder that has some tetrahedra spanning two layers. The picture below shows the problematic tetrahedra when we set the clipping plane through the second layer. All other tetrahedra in the first layer were hidden, but the problematic tetrahedra are shown because they span both the first and the second layer. The problematic tetrahedra come in groups of four tetrahedra forming octahedra. I believe when MakeCylinderMesh() share the same SplitOctahedron() code as  MakeSphereVolumeMesh(), we won't have this problem (this task is scheduled in Q4 CY2019). It is not clear how these problematic tetrahedra would affect the discretized extent field.
image

CC: @sherm1 @SeanCurtis-TRI @amcastro-tri @joemasterjohn

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Fix #12128 "Improve tetrahedral mesh connectivity for cylinders and boxes."

This is how pressure fields would look on the new meshes (drake/geometry/proximity/images):

cylinder_mesh_medial_axis_pressure
cylinder_mesh_medial_axis_pressure_isosurface

I also verify that it is used in hydroelastics by `contact_surface_rigid_bowl_soft_ball --rigid=cylinder --soft=cylinder` like this:

https://user-images.githubusercontent.com/42557859/104261788-2970e400-543b-11eb-9bd1-37f2257c6e26.mp4

and `--rigid=box --soft=cylinder` like this:

https://user-images.githubusercontent.com/42557859/104261843-40173b00-543b-11eb-8106-ad6c8fc055ba.mp4

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@joemasterjohn for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506#-:-MQYojX31ZCQUVTnkk9e:bjjfqi0)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
First pass done. Just a few nits. PTAL.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506#-:-MQmWVxb0SyC7tZK9QN4:b-5mc96i)* status: 4 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[geometry/proximity/make_cylinder_field.h, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmTP4SDIch_dyAerKX:-MQmTP4SDIch_dyAerKY:bliz5n9) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/make_cylinder_field.h#L25)):*
> ```objc
>  boundary with maximum E in the interior.
> 
>  For hydroelastics, an optimal mesh, `mesh_C` parameter, for this field is from
> ```

nit: I think 'optimal' is a hard word to back up here. I think the main improvements of the medial axis mesh are:

- There are no tets with all four vertices on the boundary.
- Each tet has at least one vertex on the boundary and one on the medial axis.

The first making it a more accurate representation of the piecewise-linear field and the second making it a more "minimal" mesh in terms of number of tets. Maybe just saying something small along those lines instead of the word "optimal".
___
*[geometry/proximity/make_cylinder_field.h, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmVRqvBPxojp3Db-xr:-MQmVRqvBPxojp3Db-xs:b27l679) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/make_cylinder_field.h#L95)):*
> ```objc
>     // -min_half_size ⇝ 1, 0 ⇝ 0.
>     const T extent = -signed_distance / T(min_half_size);
>     pressure_values.push_back(elastic_modulus * extent);
> ```

nit: consider using min(elastic_modulus * extent, elastic_modulus) to truly bound the pressure values in [0, E]
___
*[geometry/proximity/test/make_cylinder_field_test.cc, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmVhEq7caRvIfcI3Np:-MQmVhEq7caRvIfcI3Nq:bd7c0hm) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/test/make_cylinder_field_test.cc#L23)):*
> ```cpp
>     const double elastic_modulus) {
>   // We pick the relative error 1e-14 of the elastic modulus empirically.
>   const double tolerance = 1e-14 * elastic_modulus;
> ```

nit: I made a comment above about truly restricting the allowable pressure values to [0, E]. If you choose to do that, you can change these comparisons back to exact.
___
*[geometry/proximity/test/make_cylinder_field_test.cc, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmWBcE6EahWjVc4v2Q:-MQmWBcE6EahWjVc4v2R:b-6g51pe) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/test/make_cylinder_field_test.cc#L53)):*
> ```cpp
> 
>   // If the mesh has a vertex at the origin of its canonical frame,
>   // check that the center (0,0,0) of the shape has the max_pressure.
> ```

nit: maybe a small note that this doesn't apply in general to any mesh.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

___
*[geometry/proximity/make_cylinder_field.h, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmTP4SDIch_dyAerKX:-MQnddbv2vJoJItn7B3H:byvl5cy) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/make_cylinder_field.h#L25)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: I think 'optimal' is a hard word to back up here. I think the main improvements of the medial axis mesh are:

- There are no tets with all four vertices on the boundary.
- Each tet has at least one vertex on the boundary and one on the medial axis.

The first making it a more accurate representation of the piecewise-linear field and the second making it a more "minimal" mesh in terms of number of tets. Maybe just saying something small along those lines instead of the word "optimal".
</blockquote></details>

Done.  I blended your suggestion with my changes.
___
*[geometry/proximity/make_cylinder_field.h, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmVRqvBPxojp3Db-xr:-MQneW531o-D7zc9Lyx-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/make_cylinder_field.h#L95)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: consider using min(elastic_modulus * extent, elastic_modulus) to truly bound the pressure values in [0, E]
</blockquote></details>

Done.
___
*[geometry/proximity/test/make_cylinder_field_test.cc, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmVhEq7caRvIfcI3Np:-MQnh-Fy2qli7nBQhOvF:b3p1vkz) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/test/make_cylinder_field_test.cc#L23)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: I made a comment above about truly restricting the allowable pressure values to [0, E]. If you choose to do that, you can change these comparisons back to exact.
</blockquote></details>

I agree with what you said, and I tested that setting tolerance=0 can pass now.

However, I'd like to keep the tolerance for flexibility of future code change please.
___
*[geometry/proximity/test/make_cylinder_field_test.cc, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmWBcE6EahWjVc4v2Q:-MQntIuG2aFvD-yblhfR:b-p2ukqc) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/test/make_cylinder_field_test.cc#L53)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: maybe a small note that this doesn't apply in general to any mesh.
</blockquote></details>

Would this sound better?

**Review by joemasterjohn — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506#-:-MQoHDk48StC5elFw0dm:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[geometry/proximity/make_cylinder_field.h, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmTP4SDIch_dyAerKX:-MQoGr0W3ZXtAWP5JCV_:bb6ywmx) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/make_cylinder_field.h#L25)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  I blended your suggestion with my changes.
</blockquote></details>

LGTM
___
*[geometry/proximity/test/make_cylinder_field_test.cc, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmVhEq7caRvIfcI3Np:-MQoH20N4VZpmC7Eiqb7:b2h0gno) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/test/make_cylinder_field_test.cc#L23)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I agree with what you said, and I tested that setting tolerance=0 can pass now.

However, I'd like to keep the tolerance for flexibility of future code change please.
</blockquote></details>

OK sounds good.
___
*[geometry/proximity/test/make_cylinder_field_test.cc, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQmWBcE6EahWjVc4v2Q:-MQoH6aO8LJrUJ7BdcTy:bmbfh2j) ([raw file](https://github.com/robotlocomotion/drake/blob/3445c7c3695f5c88eae5fa2a88d80663bf9a4f12/geometry/proximity/test/make_cylinder_field_test.cc#L53)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Would this sound better?
</blockquote></details>

This sounds good, yeah.

**Review by joemasterjohn — COMMENTED** [review]
+@rpoyner-tri for platform review tomorrow, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506#-:-MQoHjy96venny5RC1-I:b-25mxbk)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
@joemasterjohn Thank you for finishing it quickly!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506#-:-MQoNWFh3Yd4OjEt96OL:bczypbj)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: defects left from prior commits

> Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506#-:-MQrRXVb-qy8xVwJr6RT:b-nnkuys)* status: 2 unresolved discussions (waiting on @DamrongGuoy)

___
*[geometry/proximity/make_cylinder_mesh.h, line 225 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQrNTss2BbZR7SI3ZtQ:-MQrNTss2BbZR7SI3ZtR:b-oocmsr) ([raw file](https://github.com/robotlocomotion/drake/blob/4176092a98c98731260b81e0327afb938a7899e4/geometry/proximity/make_cylinder_mesh.h#L225)):*
> ```objc
> 
>   // Internal vertices can be projected in the same manner as cap vertices
>   // for better quality
> ```

BTW, quite a few comment sentences missing punctuation in this file.
___
*[geometry/proximity/make_cylinder_mesh.h, line 232 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQrKXCW0Jfp4D7eSLox:-MQrKXCX8QN2r8evsXfh:bm0vcog) ([raw file](https://github.com/robotlocomotion/drake/blob/4176092a98c98731260b81e0327afb938a7899e4/geometry/proximity/make_cylinder_mesh.h#L232)):*
> ```objc
>     case CylinderVertexType::kInternal:
>       return ProjectMidpointToMiddleCylinder(x, y);
>     default:
> ```

I know this is not part of the change set, but this default branch makes no sense. It should be unreachable unless (a) a client has played games to get an un-enumerated value into v_type, or (b) the enum type has been expanded without updating this switch block.

As for (a), bad client deserves the UB they get.

In the case of (b), actually having the default branch here suppresses the compiler's ability to check that the explicit cases cover the entire enum. Try it and see: if you keep the default and comment out an explicit case, you will get no error; if you remove the default and an explicit case, the file will not compile.

h/t to kcov for noticing the default branch was not reached by tests.
___
*[geometry/proximity/make_cylinder_mesh.h, line 235 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQrMUYk-ERXzMhM7gVs:-MQrMUYk-ERXzMhM7gVt:b2ri0iw) ([raw file](https://github.com/robotlocomotion/drake/blob/4176092a98c98731260b81e0327afb938a7899e4/geometry/proximity/make_cylinder_mesh.h#L235)):*
> ```objc
>       return v;
>   }
> }
> ```

It looks like you intend the switch block to always lead to a return. If that is the case, there should be a DRAKE_UNREACHABLE() after the switch block.

It is likely that you got tempted into the default branch above because the DRAKE_UNREACHABLE() was missing and the compiler complained about "control reaches the end of non-void function".

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506)* status: 2 unresolved discussions (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[geometry/proximity/make_cylinder_mesh.h, line 232 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQrKXCW0Jfp4D7eSLox:-MQr_a2g4QJ8funQREbH:b-wtujyl) ([raw file](https://github.com/robotlocomotion/drake/blob/4176092a98c98731260b81e0327afb938a7899e4/geometry/proximity/make_cylinder_mesh.h#L232)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I know this is not part of the change set, but this default branch makes no sense. It should be unreachable unless (a) a client has played games to get an un-enumerated value into v_type, or (b) the enum type has been expanded without updating this switch block.

As for (a), bad client deserves the UB they get.

In the case of (b), actually having the default branch here suppresses the compiler's ability to check that the explicit cases cover the entire enum. Try it and see: if you keep the default and comment out an explicit case, you will get no error; if you remove the default and an explicit case, the file will not compile.

h/t to kcov for noticing the default branch was not reached by tests.

</blockquote></details>

This would be a defect from my first implementation of the cylinder mesh (my first ever drake PR). @damrongguoy let me know if you'd like me to fix these things in a separate PR. 
___
*[geometry/proximity/make_cylinder_mesh.h, line 235 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQrMUYk-ERXzMhM7gVs:-MQr_wsGCKX5gX18-SH0:bnfub11) ([raw file](https://github.com/robotlocomotion/drake/blob/4176092a98c98731260b81e0327afb938a7899e4/geometry/proximity/make_cylinder_mesh.h#L235)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

It looks like you intend the switch block to always lead to a return. If that is the case, there should be a DRAKE_UNREACHABLE() after the switch block.

It is likely that you got tempted into the default branch above because the DRAKE_UNREACHABLE() was missing and the compiler complained about "control reaches the end of non-void function".
</blockquote></details>

That's exactly right. I didn't know about `DRAKE_UNREACHABLE()` at the time.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14506)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn

___
*[geometry/proximity/make_cylinder_mesh.h, line 232 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQrKXCW0Jfp4D7eSLox:-MQrcdL4DSfbVUU-e-dS:bwsla3h) ([raw file](https://github.com/robotlocomotion/drake/blob/4176092a98c98731260b81e0327afb938a7899e4/geometry/proximity/make_cylinder_mesh.h#L232)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

This would be a defect from my first implementation of the cylinder mesh (my first ever drake PR). @damrongguoy let me know if you'd like me to fix these things in a separate PR. 
</blockquote></details>

@joemasterjohn let's go ahead and do a separate fix PR. I'll unblock this one.
___
*[geometry/proximity/make_cylinder_mesh.h, line 235 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14506#-MQrMUYk-ERXzMhM7gVs:-MQrcmi0AP9VtVhoMncI:b-y4gwzw) ([raw file](https://github.com/robotlocomotion/drake/blob/4176092a98c98731260b81e0327afb938a7899e4/geometry/proximity/make_cylinder_mesh.h#L235)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

That's exactly right. I didn't know about `DRAKE_UNREACHABLE()` at the time.
</blockquote></details>

@joemasterjohn to address in separate PR; unblocking.

**Pull request merged**
