### PR TITLE
[workspace] Simplify several externals to be platform-agnostic

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14967.  We only want to lock ourselves to specific Ubuntu release numbers in cases where we acutely care.  In most cases, we only care about "linux" vs "darwin", not Ubuntu.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20606)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both(?) reviews, please.  If you'd like a separate feature reviewer, we could add Rico for that.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: x2

> Reviewed 1 of 1 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20606#-:-NkTFP_wEBKMpMLHRU1y:b-8n9n9v)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20606)* status: 1 unresolved discussion, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`tools/workspace/mosek/repository.bzl` line 33 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20606#-NkTFX1SAulSaygPlt69:-NkTFX1SAulSaygPlt6A:b-n1yg3y) ([raw file](https://github.com/RobotLocomotion/drake/blob/df6b0bac09d45a93afe6e6e857a5f2eae8912d3a/tools/workspace/mosek/repository.bzl#L33)):*
> ```Starlark
>     mosek_patch_version = 46
> 
>     os_name = repository_ctx.os.name  # 'linux' or 'mac os x'
> ```

nit (minor) This file does no mapping,but gurobi mapped from `mac os x` to `darwin`.

Is it useful for other if this were consistent?

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20606)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform), base commit is latest master

___
*[`tools/workspace/mosek/repository.bzl` line 33 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20606#-NkTFX1SAulSaygPlt69:-NkVsM9W6q5OzwXGEdSj:bj0c8t8) ([raw file](https://github.com/RobotLocomotion/drake/blob/df6b0bac09d45a93afe6e6e857a5f2eae8912d3a/tools/workspace/mosek/repository.bzl#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I went back and forth on different spellings in the various files (both here, and in other related PRs).  Your comment was enough to tip this one the other way.
</blockquote></details>

Aye, thanks!

**Pull request merged**
