### PR TITLE
Make @gtest//:main even harder to accidentally use incorrectly

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Note that the individual commits are curated, with more specific changes listed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6683)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review please, since you have helped fix gtest use previously.

**Comment by EricCousineau-TRI** [comment]
First pass, PTAL. Thanks!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/BUILD, line 545 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-Kq3RzvnECcUP1wcQjV0:-Kq3RzvpH_iPo4dTfDiw:b-849ub7) ([raw file](https://github.com/robotlocomotion/drake/blob/fd040562a2d8bfead58f8ca70c2a91f203b6a8fc/drake/multibody/BUILD#L545)):*
> ```Python
> 
> # This test is empty unless Gurobi is enabled.
> drake_cc_googletest(
> ```

nit Since this test is a complete no-op, can we just add `gurobi_tags()` to the tags, without having a slew of `select()` statements?

(If you want, you can make this a separate issue and assign it to me, in addition to GTest-ifying the existing test.)

---

*[tools/drake.bzl, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-Kq3RP7FVYXreLKVmqMp:-Kq3RP7GA6OYCOvC-uRS:b-xdu0g) ([raw file](https://github.com/robotlocomotion/drake/blob/fd040562a2d8bfead58f8ca70c2a91f203b6a8fc/tools/drake.bzl#L137)):*
> ```Python
> 
>     if "@gtest//:main" in (deps or []):
>         fail("Use drake_cc_googletest to declare %s as a test" % name)
> ```

I'm not sure if I am a fan of the fail-fast, as I had to hack around CLion's inability to parse `drake_cc_googletest` by making a `drake_cc_binary` with `@gtest//:main`.

Can this instead `print()` a warning? (such that it enables hacking without needing to break into other portions of the code?)

---

*[tools/drake.bzl, line 216 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-Kq3RmMr_qrGBYSK73vB:-Kq3RmMsit7gYoKtLl-c:bt2y3th) ([raw file](https://github.com/robotlocomotion/drake/blob/fd040562a2d8bfead58f8ca70c2a91f203b6a8fc/tools/drake.bzl#L216)):*
> ```Python
>         deps = []
>     if use_default_main:
>         deps = deps + ["@gtest//:main"]
> ```

BTW Is this a suggested format from `buildifier`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-:-Kq3SMEB0yTmTrLBmPKn:bkr5z3x)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/BUILD, line 545 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-Kq3RzvnECcUP1wcQjV0:-Kq3VCb2ODhgvwRW5hy-:b-9i3ij1) ([raw file](https://github.com/robotlocomotion/drake/blob/fd040562a2d8bfead58f8ca70c2a91f203b6a8fc/drake/multibody/BUILD#L545)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Since this test is a complete no-op, can we just add `gurobi_tags()` to the tags, without having a slew of `select()` statements?

(If you want, you can make this a separate issue and assign it to me, in addition to GTest-ifying the existing test.)
</blockquote></details>

Yes and no.

We can't remove the select because `approximate_ik.cc` calls Gurobi directly, not via the MathematicalProgram interface, so it doesn't even compile when Gurobi is absent.  I've added comments to help clarify that.

However, you're right that we should not even run the null test when Gurobi is absent, so I've also added the tag.

---

*[tools/drake.bzl, line 216 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-Kq3RmMr_qrGBYSK73vB:-Kq3UTAkILVW4qdD2yMZ:b-sw2wmp) ([raw file](https://github.com/robotlocomotion/drake/blob/fd040562a2d8bfead58f8ca70c2a91f203b6a8fc/tools/drake.bzl#L216)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Is this a suggested format from `buildifier`?
</blockquote></details>

This was the "Fix drake_cc_googletest for deps which are a select()" commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6683)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/drake.bzl, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-Kq3RP7FVYXreLKVmqMp:-Kq3YZB01-iRJyRSJoY7:b-os75hs) ([raw file](https://github.com/robotlocomotion/drake/blob/fd040562a2d8bfead58f8ca70c2a91f203b6a8fc/tools/drake.bzl#L137)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I'm not sure if I am a fan of the fail-fast, as I had to hack around CLion's inability to parse `drake_cc_googletest` by making a `drake_cc_binary` with `@gtest//:main`.

Can this instead `print()` a warning? (such that it enables hacking without needing to break into other portions of the code?)
</blockquote></details>

For that work-around, what is the meaningful part of the difference to CLion?  Is that it ends up with `native.cc_binary` instead of `native.cc_test`?  Or losing the`testonly = 1` attribute?  Or the name of the macro in the `BUILD` file somehow being pattern-matched?  I would like to figure out some other kind of compromise.  Perhaps I could add a `allow_gtest_main` argument to this macro?  Or perhaps we can fix whatever your root cause is?

I think users who accidentally use `:main` are also users who will ignore warnings, so I don't think that warnings will get the job done.  My goal here is to stop wasting _my_ time cleaning up other people's messes.  If it turns into a warning, then I'll just be cleaning up warnings instead of hunting down bad `deps`, but its cleanup nonetheless.  I need it to fail on the developer's workstation, so that it doesn't even make it to a PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6683)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake.bzl, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-Kq3RP7FVYXreLKVmqMp:-Kq4ROZkYt6ulXT4b3lh:b-9g5g3f) ([raw file](https://github.com/robotlocomotion/drake/blob/fd040562a2d8bfead58f8ca70c2a91f203b6a8fc/tools/drake.bzl#L137)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For that work-around, what is the meaningful part of the difference to CLion?  Is that it ends up with `native.cc_binary` instead of `native.cc_test`?  Or losing the`testonly = 1` attribute?  Or the name of the macro in the `BUILD` file somehow being pattern-matched?  I would like to figure out some other kind of compromise.  Perhaps I could add a `allow_gtest_main` argument to this macro?  Or perhaps we can fix whatever your root cause is?

I think users who accidentally use `:main` are also users who will ignore warnings, so I don't think that warnings will get the job done.  My goal here is to stop wasting _my_ time cleaning up other people's messes.  If it turns into a warning, then I'll just be cleaning up warnings instead of hunting down bad `deps`, but its cleanup nonetheless.  I need it to fail on the developer's workstation, so that it doesn't even make it to a PR.
</blockquote></details>

I did not dig too thoroughly into it, and I understand that you'd like this to be a hardstop.
I am fine with it failing fast in this case, and if I need the workaround, I will just take out the error in my local working copy.

I'll try for about 10 minutes to see if I can isolate what the root cause of this is.

---

*[tools/drake.bzl, line 216 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-Kq3RmMr_qrGBYSK73vB:-Kq4Rmz4NMh3vNJNcVO_:b-chz3ca) ([raw file](https://github.com/robotlocomotion/drake/blob/fd040562a2d8bfead58f8ca70c2a91f203b6a8fc/tools/drake.bzl#L216)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This was the "Fix drake_cc_googletest for deps which are a select()" commit.
</blockquote></details>

Ah, gotcha. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-:-Kq4SeT0wIPOoTDkZSgm:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-tri for platform on-call review, please.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[tools/drake.bzl, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-Kq3RP7FVYXreLKVmqMp:-Kq4Ue728XrszkQcpk3i:b-xye5og) ([raw file](https://github.com/robotlocomotion/drake/blob/fd040562a2d8bfead58f8ca70c2a91f203b6a8fc/tools/drake.bzl#L137)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I did not dig too thoroughly into it, and I understand that you'd like this to be a hardstop.
I am fine with it failing fast in this case, and if I need the workaround, I will just take out the error in my local working copy.

I'll try for about 10 minutes to see if I can isolate what the root cause of this is.
</blockquote></details>

FYI In thinking of fixes for this, I have several ideas for how to make CLion happy, depending on what the relevant facet seemed to be.  I can elaborate (on slack?) if you're able to diagnose the cause.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-:-Kq4UbSn6w2IqcKD6fM-:bo4j9h5)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: +@soonho-tri for final.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-:-Kq4qIsbVk8NtEttoGKw:bgzpmiz)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6683#-:-Kq64WF96e1HEmQ4to7R:bnfp4nl)*

**Pull request merged**
