### PR TITLE
Add support for PoseVector in PoseAggregator.

### PR DESCRIPTION
**Pull request by david-german-tri**
@SeanCurtis-TRI for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5314)

### CODE REVIEW

**Comment by david-german-tri** [comment]
-@SeanCurtis-TRI +@jadecastro 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-:-Ke-9f58aAFMO_2TgI-p:bqd3g5m)*

**Comment by jadecastro** [comment]
@david-german-tri: Just one BTW comment below. Otherwise, :lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_aggregator.h, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke0f6VjwLUn4H_Z0c-v:-Ke0f6VjwLUn4H_Z0c-w:b6k9c2u) ([raw file](https://github.com/robotlocomotion/drake/blob/684f69e5a68a38f751ecdad001ee5ce20689c09c/drake/systems/rendering/pose_aggregator.h#L122)):*
> ```objc
>     int num_poses{0};
>     // name is only valid if type is kSingle.
>     std::string name{};
> ```

BTW, I'm not sure why we need to maintain the two flavors `name` and `bundle_name`.  Could we not drop the `bundle_` appellation and maintain just the `name` member field?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-:-Ke0lI1zIyA0K8WFryYA:bfbv8f1)*

**Comment by jadecastro** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5314)*

**Comment by david-german-tri** [comment]
+@sherm1 for platform review

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_aggregator.h, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke0f6VjwLUn4H_Z0c-v:-Ke0ou0iAzdT1w4Fls-x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/684f69e5a68a38f751ecdad001ee5ce20689c09c/drake/systems/rendering/pose_aggregator.h#L122)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, I'm not sure why we need to maintain the two flavors `name` and `bundle_name`.  Could we not drop the `bundle_` appellation and maintain just the `name` member field?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-:-Ke0ouxweTtxkh3VIXHn:buasbda)*

**Comment by jadecastro** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5314)*

**Comment by sherm1** [comment]
:lgtm: pending a few BTWs.

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/system.h, line 277 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4rYyw8WyNZaPkXSf6:-Ke4rYyw8WyNZaPkXSf7:b-x045x2) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/framework/system.h#L277)):*
> ```objc
>   const Vec<T>* EvalVectorInput(const Context<T>& context,
>                                 int port_index) const {
>     DRAKE_ASSERT(0 <= port_index && port_index < get_num_input_ports());
> ```

BTW, can you static_assert that Vec is a subclass of BasicVector? I think it would be likely for someone to try `EvalVectorInput<VectorXd>`.

---

*[drake/systems/rendering/pose_aggregator.h, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4zyHTkS8zvDX8saz0:-Ke4zyHTkS8zvDX8saz1:b-j15n3o) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/rendering/pose_aggregator.h#L24)):*
> ```objc
> /// Supported sources are:
> /// - The state output of a RigidBodyPlant.
> /// - A PoseVector input, which is vector-valued.
> ```

BTW, I found this confusing because "PoseVector" sounds like a vector of poses. I realize now it is just a single pose. Please clarify that this is a single pose while bundle is a collection of poses.

BTW, I'm wondering if there is a better name for PoseVector. It is really just a Pose, but in a packed format rather than an Isometry3. ROS has [a message](http://docs.ros.org/kinetic/api/geometry_msgs/html/msg/Pose.html) with exactly this format and calls it a Pose. "Pose", "SinglePose", "PackedPose", ... ?

FYI, in MultibodyTree we are consistently representing all spatial quantities in the order (rotational,translation). RBTree is not consistent either way. The rotation-first ordering seems odd, but virtually all the multibody theory literature uses that ordering. There is no particular reason that PoseVector needs to follow that and it also makes sense for it to match ROS but I thought you might like to be aware of that! 

/cc @amcastro-tri 

---

*[drake/systems/rendering/pose_aggregator.h, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4tFBnYedGTcDJgc-0:-Ke4tFBoYGHLh4Q0eTvz:b-gaujlg) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/rendering/pose_aggregator.h#L33)):*
> ```objc
> /// each aggregated pose is in the same world frame of reference.
> ///
> /// The output poses are named in the form "source" or "<source>::<pose>".
> ```

BTW, is the lack of angle brackets in the first form significant? Or should this be `"<source>"`?

---

*[drake/systems/rendering/pose_aggregator.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4t_Z51b06Bq6hLTCh:-Ke4t_Z51b06Bq6hLTCi:b-52l4p0) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/rendering/pose_aggregator.h#L35)):*
> ```objc
> /// The output poses are named in the form "source" or "<source>::<pose>".
> /// - For poses derived from a RigidBodyPlant input, <source> is the name of
> /// the RigidBodyTree model, concatenated with the instance ID, and <pose>
> ```

BTW, doxygen has trouble at times with things that look like html tags. Just mentioning that in case you haven't checked that this is OK as is. You can escape with backtics.

---

*[drake/systems/rendering/pose_aggregator.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4twt3fVjZafRwXQkM:-Ke4twt4bGG55gC61Nqp:bgtktkd) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/rendering/pose_aggregator.h#L37)):*
> ```objc
> /// the RigidBodyTree model, concatenated with the instance ID, and <pose>
> /// is the name of the body.  For instance, if the model is named "model", the
> /// pose of the link named "foo" in the first insance of that model is
> ```

BTW, insance -> instance

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-:-Ke530H4M62Z_J_uAkPB:b1favup)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/rendering/pose_aggregator.h, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4zyHTkS8zvDX8saz0:-Ke54cBVsFN5qUU9f6L1:blr4okj) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/rendering/pose_aggregator.h#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I found this confusing because "PoseVector" sounds like a vector of poses. I realize now it is just a single pose. Please clarify that this is a single pose while bundle is a collection of poses.

BTW, I'm wondering if there is a better name for PoseVector. It is really just a Pose, but in a packed format rather than an Isometry3. ROS has [a message](http://docs.ros.org/kinetic/api/geometry_msgs/html/msg/Pose.html) with exactly this format and calls it a Pose. "Pose", "SinglePose", "PackedPose", ... ?

FYI, in MultibodyTree we are consistently representing all spatial quantities in the order (rotational,translation). RBTree is not consistent either way. The rotation-first ordering seems odd, but virtually all the multibody theory literature uses that ordering. There is no particular reason that PoseVector needs to follow that and it also makes sense for it to match ROS but I thought you might like to be aware of that! 

/cc @amcastro-tri 
</blockquote></details>

BTW. I'm thinking "Pose" might be a component we'd like to have in our multibody engine. I do agree with @sherm1 that `PoseVector` causes this confusion. What about calling it something along the lines of `PoseAsVector` or `PoseVectorRepresentation`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5314)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/system.h, line 277 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4rYyw8WyNZaPkXSf6:-Ke57NNbWR4NB7mxEiSU:bqqbert) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/framework/system.h#L277)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, can you static_assert that Vec is a subclass of BasicVector? I think it would be likely for someone to try `EvalVectorInput<VectorXd>`.
</blockquote></details>

Great idea, done.

---

*[drake/systems/rendering/pose_aggregator.h, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4zyHTkS8zvDX8saz0:-Ke582in1kkDJpLvtZ-W:b-k7z2x9) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/rendering/pose_aggregator.h#L24)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW. I'm thinking "Pose" might be a component we'd like to have in our multibody engine. I do agree with @sherm1 that `PoseVector` causes this confusion. What about calling it something along the lines of `PoseAsVector` or `PoseVectorRepresentation`?
</blockquote></details>

I clarified the comment, and will mull the name change in a separate PR.

---

*[drake/systems/rendering/pose_aggregator.h, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4tFBnYedGTcDJgc-0:-Ke586Ur7it8XJShdUXO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/rendering/pose_aggregator.h#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, is the lack of angle brackets in the first form significant? Or should this be `"<source>"`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/pose_aggregator.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4t_Z51b06Bq6hLTCh:-Ke586zFEnY-qy9TyzCJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/rendering/pose_aggregator.h#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, doxygen has trouble at times with things that look like html tags. Just mentioning that in case you haven't checked that this is OK as is. You can escape with backtics.
</blockquote></details>

Done.

---

*[drake/systems/rendering/pose_aggregator.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4twt3fVjZafRwXQkM:-Ke58AF3uf3QjG2EuTMO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/rendering/pose_aggregator.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, insance -> instance
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5314)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/systems/framework/system.h, line 277 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5314#-Ke4rYyw8WyNZaPkXSf6:-Ke5_QPUqHF-DhE6l493:bsqe8wd) ([raw file](https://github.com/robotlocomotion/drake/blob/5397088257c0e17e7f23f7d115ff62b1dd114346/drake/systems/framework/system.h#L277)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Great idea, done.
</blockquote></details>

Cool, I wondered how to do that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5314)*

**Pull request merged**
