### PR TITLE
Specify Separate Solver and SolverOptions for GCS Preprocessing

### LINKED ISSUE #21613: Specify Separate Solver and SolverOptions for GCS Preprocessing
Sometimes, when solving very large GCS problems, it's necessary to use a first-order method like SCS even when a solver like Mosek or Gurobi is available. However, this also leads to SCS being used for the preprocessing step -- these smaller optimization problems can still be handled by a second-order method even if the overall problem is too large. For those steps, it would be very helpful if we could specify a different solver (much like one can specify separate solvers for the relaxation and rounding stages).

### PR DESCRIPTION
**Pull request by cohnt**
+@hongkai-dai for feature review if you have the time.

Closes #21613.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21641)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

Sorry I didn't work on the issue. Glad that you implemented the feature.

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21641#-:-O0VBZEg891ESwxaaAE8:bmgaawm)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 599 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21641#-O0VBF1rEJ5vxIBgDcfZ:-O0VBF1s08jJHLRAIP9O:b9v97r7) ([raw file](https://github.com/RobotLocomotion/drake/blob/f3962bb86ac056883c181075e4db42943a0925cf/geometry/optimization/graph_of_convex_sets.cc#L599)):*
> ```cpp
> 
>     // Check if edge e = (u,v) could be on a path from start to goal.
>     auto result = Solve(prog, options, true);
> ```

BTW, it would be more clear if you write
```cc
auto result = Solve(prog, options, /* preprocessing= */ true);
```

**Review by hongkai-dai — COMMENTED** [review]
+@RussTedrake for platform review please?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21641#-:-O0VBgV5AFzpRYajCySN:b-ctes8u)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform)

**Review by cohnt — COMMENTED** [review]
Not a problem! I actually implemented the change shortly after making the issue (since I needed it somewhat urgently). It took me a lot longer to figure out how to test it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21641#-:-O0VUBo001UnAe8wiHa4:b-rag3h6)* status: LGTM missing from assignee RussTedrake(platform)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 599 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21641#-O0VBF1rEJ5vxIBgDcfZ:-O0VUL-N57Ez6AGeC4S0:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f3962bb86ac056883c181075e4db42943a0925cf/geometry/optimization/graph_of_convex_sets.cc#L599)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, it would be more clear if you write
```cc
auto result = Solve(prog, options, /* preprocessing= */ true);
```
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21641)* status: LGTM missing from assignee RussTedrake(platform)

**Review by hongkai-dai — COMMENTED** [review]
-@RussTedrake for platform review, +@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21641#-:-O0kGj6cCkOotKNw9e2x:b-f6d8u2)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21641#-:-O0kyFq64Qompcx6ndql:b8qx53o)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),hongkai-dai

**Pull request merged**
