### PR TITLE
[workspace] Upgrade gtest to latest release 1.11.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This re-applies #15291, which was previously reverted in #15306.

Fixes as of this new revision:

As of 1.11.0, googletest prints the values in for any value-parameterized test -- even if there is no printer defined, it will now print the raw bytes of the value.  This is a problem during memcheck when the default value contains uninitialized memory (e.g., the SBO buffer in a `std::string` or `std::function`).

We could tell valgrind to ignore gtest printers, but a better answer seems to be defining a proper printer so that `--gtest_list_tests` shows something useful, instead of hex dumps.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15544)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for both reviews per schedule (tomorrow), please.

**Comment by jwnimmer-tri** [comment]
I meant to say -- r1 shows the original commit that was reverted, in case that helps.  I'll squash when merging.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15544#-:-Mg7rgHZ3pAI8gV-vq3y:b4xzgsb)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
