### PR TITLE
Rb qdot to avel fix

### PR DESCRIPTION
**Pull request by edrumwri**
This fix addresses issue #4121, and reduces five digits of accuracy loss to slightly over two in converting between time derivatives of generalized coordinates and generalized velocities and back.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4214)

### CODE REVIEW

**Comment by edrumwri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KX93U1J4T1A03cBQWmM:-KX93U1J4T1A03cBQWmN:b-wdlrue) (no related file):*
+@tkoolen and +@mitiguy for feature review, +@david-german-tri for platform review (due to Tuesday's rotation) please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by sherm1** [comment]
Evan, this PR contains three externals (dreal,nlopt,swigmake). I doubt you wanted those here!

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-:-KX9YhIoHyfOa-Ln4xDA:b-y8mxjh)*

**Comment by david-german-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCc8FQjul8i85AMlS8:-KXCc8FQjul8i85AMlS9:b-wo9d59) (no related file):*
> Evan, this PR contains three externals (dreal,nlopt,swigmake). I doubt you wanted those here!
:+1:

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCa5j1QbTpV5WW8BC-:-KXCa5j1QbTpV5WW8BC0:b-1tgpj2) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L69)):*
> ```objc
>   }
> 
>   /**
> ```

As far as I can tell there is no direct test coverage for this method, which means (as someone who doesn't actually understand the math) it's hard for me to be comfortable that the only change is a precision improvement.  Could you please add one or two test cases for which you have a pencil-and-paper result, and check that you can assert tighter precision after this change than before?

BTW I see the tolerance reduction in `rigid_body_plant_test` and that's awesome, but a more local test will provide more protection going forward.  

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCZFoPXj4U7DalIKsT:-KXCZFoQMOKjaqGb_vk4:b2kkpho) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L96)):*
> ```objc
>     auto quat =
>         q.template middleRows<drake::kQuaternionSize>(drake::kSpaceDimension);
>     const auto qw = quat[0];
> ```

Can these be references?

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXC__f7R3ZlEo-G7Y1G:-KXC__f8rsJdIViOdfO3:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L150)):*
> ```objc
>     auto quat =
>         q.template middleRows<drake::kQuaternionSize>(drake::kSpaceDimension);
>     const auto qw = quat[0];
> ```

ditto

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCbxC-eikLiq0HX8oE:-KXCbxC0O72mva2aUXwj:b6kdbhd) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L73)):*
> ```cpp
> // derivatives for a free body with a quaternion base.
> GTEST_TEST(RigidBodyPlantTest, MapVelocityToConfigurationDerivativesAndBack) {
>   const double kTol = 2e-13;     // Test succeeds at one order of magnitude
> ```

Nice!  I think the pre-existing comment was never really helpful, and this seems like an opportune time to delete it.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCc4r3lW8n_U1IDDlz:-KXCc4r3lW8n_U1IDDm-:b-qgy7n4) ([raw file](https://github.com/robotlocomotion/drake/blob/78e755dd29cfa1f3ea83d5919b5641ab1a57e269/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L130)):*
> ```cpp
>                           &positions_derivatives);
> 
>   // For zero rotation the velocity vector in the body's frame and in the
> ```

Why is this no longer true?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by david-german-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by sherm1** [comment]
Please see my comment about frames [here](https://github.com/RobotLocomotion/drake/issues/4121#issuecomment-262417876).

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-:-KXDsXxH5KmHnPvSjS_q:b-ncc6db)*

**Comment by tkoolen** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXGzUODy4TW_ncGpPer:-KXGzUOED41uOu4_SbAA:bfr2854) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L104)):*
> ```objc
>     // from time derivative of generalized position to generalized velocity
>     // is just the identity matrix.
>     qdot_to_v.block(0, 0, 3, 3).setIdentity();
> ```

`qdot_to_v.block<3, 3>(0, 0)`. Here and throughout

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXH-nAx8L3QHEBtReOg:-KXH-nAx8L3QHEBtReOh:b8esfo5) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L112)):*
> ```objc
>     // world frame. This equation was taken from:
>     // - P. Nikravesh, Computer-Aided Analysis of Mechanical Systems. Prentice
>     //     Hall, New Jersey, 1988. Equation 105.
> ```

Prefer using a citation that is more easily accessible, e.g. http://bicycle.tudelft.nl/schwab/Publications/SchwabMeijaard2006.pdf, equation (35).

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXH00iv4CpbqQ_DItLZ:-KXH00iv4CpbqQ_DItL_:b-mwr6gg) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L117)):*
> ```objc
>                                     -qy,  qz,  qw, -qx,
>                                     -qz, -qy,  qx,  qw;
>     qdot_to_v.block(3, 3, 3, 4) *= 2.;
> ```

This looks wrong to me. The resulting angular velocity is supposed to be in body frame, and I believe this is in world frame. See the difference between (35) (what you want) and (33) (what I believe this is) in http://bicycle.tudelft.nl/schwab/Publications/SchwabMeijaard2006.pdf.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXH1HrsHYM88ut-YsGP:-KXH1HrsHYM88ut-YsGQ:bg61zkm) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L161)):*
> ```objc
>     // world frame. This matrix was taken from:
>     // - P. Nikravesh, Computer-Aided Analysis of Mechanical Systems. Prentice
>     //     Hall, New Jersey, 1988. Equation 106.
> ```

Same comment about reference being easily accessible.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXH1P9fn8dc5czVCIuM:-KXH1P9fn8dc5czVCIuN:bc1zjmb) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L167)):*
> ```objc
>                                     -qz,  qw,  qx,
>                                      qy, -qx,  qw;
>     v_to_qdot.block(3, 3, 4, 3) *= 0.5;
> ```

Same mistake as for qdot_to_v. See difference between (36) and (34) in http://bicycle.tudelft.nl/schwab/Publications/SchwabMeijaard2006.pdf.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by edrumwri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCa5j1QbTpV5WW8BC-:-KXHjbxx6eUeWQvIegd_:b-ddkq1x) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L69)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> As far as I can tell there is no direct test coverage for this method, which means (as someone who doesn't actually understand the math) it's hard for me to be comfortable that the only change is a precision improvement.  Could you please add one or two test cases for which you have a pencil-and-paper result, and check that you can assert tighter precision after this change than before?
> 
> BTW I see the tolerance reduction in `rigid_body_plant_test` and that's awesome, but a more local test will provide more protection going forward.  
</details>
There is now a test, though it's correctness will depend on resolving issue between global and body frame that @tkoolen alluded to, below.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCZFoPXj4U7DalIKsT:-KXHjAf4jaYL_wY-MC1Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L96)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Can these be references?
</details>
Done.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXH00iv4CpbqQ_DItLZ:-KXHkJnyKRRUi1MEf7jN:b-qnbtp6) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L117)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> This looks wrong to me. The resulting angular velocity is supposed to be in body frame, and I believe this is in world frame. See the difference between (35) (what you want) and (33) (what I believe this is) in http://bicycle.tudelft.nl/schwab/Publications/SchwabMeijaard2006.pdf.
</details>
Glad you are checking this, Twan. I've been concerned about which frame the angular velocities are computed/stored in (global, parent body of the quaternion joint, or child body of the quaternion joint). Is there documentation that specifies which it is with certainty?

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXC__f7R3ZlEo-G7Y1G:-KXHjIrknGM8abcdT3WX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L150)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> ditto
</details>
Done.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCbxC-eikLiq0HX8oE:-KXHjRia04uk9w7T8D-P:b-5lcsd2) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L73)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Nice!  I think the pre-existing comment was never really helpful, and this seems like an opportune time to delete it.
</details>
Which comment do you want me to delete, David?

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCc4r3lW8n_U1IDDlz:-KXHsavCdzWAxFjlIfVp:b-a10euv) ([raw file](https://github.com/robotlocomotion/drake/blob/78e755dd29cfa1f3ea83d5919b5641ab1a57e269/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L130)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why is this no longer true?
</details>
Not sure what happened there. Reinserted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by david-german-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCbxC-eikLiq0HX8oE:-KXkhxye4jDktwX6JB3z:b-d3amqt) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L73)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Which comment do you want me to delete, David?
</blockquote></details>

The "...on my machine" bit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by david-german-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[drake/multibody/kinematics_cache.h, line 189 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXkuWUsiI9MKq5C-6Zf:-KXkuWUsiI9MKq5C-6Zg:b8im71f) ([raw file](https://github.com/robotlocomotion/drake/blob/93cd9ca81a4fcf4b64696b90418c927156244c27/drake/multibody/kinematics_cache.h#L189)):*
> ```objc
>   template <typename Derived>
>   Eigen::Matrix<typename Derived::Scalar, Derived::RowsAtCompileTime, 1>
>   transformVelocityToQDot(
> ```

Unit tests for this also, please!

---

*[drake/multibody/kinematics_cache.h, line 189 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXkw0hBz2PeQBegA8Qm:-KXkw0hBz2PeQBegA8Qn:bg4k5d) ([raw file](https://github.com/robotlocomotion/drake/blob/93cd9ca81a4fcf4b64696b90418c927156244c27/drake/multibody/kinematics_cache.h#L189)):*
> ```objc
>   template <typename Derived>
>   Eigen::Matrix<typename Derived::Scalar, Derived::RowsAtCompileTime, 1>
>   transformVelocityToQDot(
> ```

BTW consider using the -inl.h pattern for consistency with `transformVelocityMappingToQDotMapping` etc.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCa5j1QbTpV5WW8BC-:-KXkwaIZUkI7tkb_IAdT:b-tyspa5) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L69)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

There is now a test, though it's correctness will depend on resolving issue between global and body frame that @tkoolen alluded to, below.
</blockquote></details>

So that's a start, but we really should have a test that's local, i.e. `quaternion_floating_joint_test.h`.  Also, did you check (locally) that you can have a tighter EXPECT_NEAR with this PR than without it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by amcastro-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[drake/multibody/kinematics_cache.h, line 189 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXmGXweeajd2TpATITh:-KXmGXweeajd2TpATITi:b-tvgcwv) ([raw file](https://github.com/robotlocomotion/drake/blob/93cd9ca81a4fcf4b64696b90418c927156244c27/drake/multibody/kinematics_cache.h#L189)):*
> ```objc
>   template <typename Derived>
>   Eigen::Matrix<typename Derived::Scalar, Derived::RowsAtCompileTime, 1>
>   transformVelocityToQDot(
> ```

I am actually working on getting the map convertion methods out of the cache in #4298. It'd make sense if you put these outside of the cache, in RBT. This is to break the dependency `KinematicsCache` --> `RigidBody`. This is an operation that can perfectly be performed by `RBT::transformVelocityToQDot(cache, v)`

---

*[drake/multibody/kinematics_cache.h, line 189 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXmH9ZejFv5-a78HIGI:-KXmH9ZejFv5-a78HIGJ:b-ebjyfj) ([raw file](https://github.com/robotlocomotion/drake/blob/93cd9ca81a4fcf4b64696b90418c927156244c27/drake/multibody/kinematics_cache.h#L189)):*
> ```objc
>   template <typename Derived>
>   Eigen::Matrix<typename Derived::Scalar, Derived::RowsAtCompileTime, 1>
>   transformVelocityToQDot(
> ```

Also follow style guide conventions for naming new methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by amcastro-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 329 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXmJvscc4z9XdmeP8u3:-KXmJvscc4z9XdmeP8u4:bqumcsu) ([raw file](https://github.com/robotlocomotion/drake/blob/93cd9ca81a4fcf4b64696b90418c927156244c27/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L329)):*
> ```cpp
>   auto kinsol = tree_->doKinematics(q);
> 
>   generalized_velocity->SetFromVector(kinsol.transformQDotToVelocity(qdot));
> ```

BTW, The previous implementation was wrong!!

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 361 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXmK0BND4W7tL9ofAvx:-KXmK0BND4W7tL9ofAvy:bqumcsu) ([raw file](https://github.com/robotlocomotion/drake/blob/93cd9ca81a4fcf4b64696b90418c927156244c27/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L361)):*
> ```cpp
>   auto kinsol = tree_->doKinematics(q, v);
> 
>   configuration_dot->SetFromVector(kinsol.transformVelocityToQDot(v));
> ```

BTW, The previous implementation was wrong!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by sherm1** [comment]
+@sherm1 I'm finding this PR somewhat terrifying. If I understand the conversation so far it has the frame wrong for the angular velocities in both qdot2v and v2qdot directions. That needs to be sorted out systematically, starting with documentation that defines which frame we want the angular velocities in -- other than @tkoolen's review comment I don't see anything that says one way or the other. Then there ought to be test cases that would fail if the frames are wrong -- I don't think the current ones do that? Please consider backing off to start with a PR that would just take the existing code and document in detail what it does, along with test cases that verify it. Then new code could be swapped in and would fail if wrong. Apologies if I'm missing something important.

---

Review status: 3 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-:-KXmTf9S21vYudJ9mmUv:b-310h86)*

**Comment by david-german-tri** [comment]
:100: for @sherm1's comment, and -@david-german-tri since Sherm is on the case.

---

Review status: 3 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-:-KXmaiL-0dNfOjpXvznq:b-kdgsia)*

**Comment by jwnimmer-tri** [comment]
Flagging as DNR DNM until Sherm's suggestion is addressed (to get this PR out of the "default" list of PRs in flight).  Feel free to remove the tags once progress resumes.

**Comment by edrumwri** [comment]
Review status: 3 of 9 files reviewed at latest revision, 15 unresolved discussions.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCa5j1QbTpV5WW8BC-:-KZduf2RzIElUQ3JiBHd:b-hm8g7v) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L69)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

So that's a start, but we really should have a test that's local, i.e. `quaternion_floating_joint_test.h`.  Also, did you check (locally) that you can have a tighter EXPECT_NEAR with this PR than without it?
</blockquote></details>

I'm involving Paul on this discussion, since he has a benchmark, but we may want to turn it into a proper test of the rigid body plant and/or of the quaternion floating joint.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXGzUODy4TW_ncGpPer:-KXHkE2_s3Oam7pbjnqi:b7iqh1a) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L104)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary><blockquote>

`qdot_to_v.block<3, 3>(0, 0)`. Here and throughout
</blockquote></details>

I'm no C++ template expert- the compiler chokes on that. 

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXCbxC-eikLiq0HX8oE:-KZdvIb-FNuOFLKt7EpY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/rigid_body_plant/test/rigid_body_plant_test.cc#L73)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

The "...on my machine" bit
</blockquote></details>

Done.

---

*[drake/multibody/kinematics_cache.h, line 189 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXkuWUsiI9MKq5C-6Zf:-KZduM6XQL61Ssb3ZikE:b-yc9av2) ([raw file](https://github.com/robotlocomotion/drake/blob/93cd9ca81a4fcf4b64696b90418c927156244c27/drake/multibody/kinematics_cache.h#L189)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Unit tests for this also, please!
</blockquote></details>

Done (with an updated version of Paul Mitiguy's test code).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by edrumwri** [comment]
Review status: 3 of 9 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4214#-KXH1P9fn8dc5czVCIuM:-KZe5IxeUFVhzNFGQIxS:b-ves3w2) ([raw file](https://github.com/robotlocomotion/drake/blob/58b7a50001c241ca09a9b588e5bb1b0a6e55f5a4/drake/multibody/joints/quaternion_floating_joint.h#L167)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary><blockquote>

Same mistake as for qdot_to_v. See difference between (36) and (34) in http://bicycle.tudelft.nl/schwab/Publications/SchwabMeijaard2006.pdf.
</blockquote></details>

I've modified this because I believe you are correct, but we have currently have no tests that break either way, even though this code is being exercised through existing testing routines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4214)*

**Comment by edrumwri** [comment]
Replacing with #4604 on @sherm1's advice.

**Pull request closed without merging**
