### PR TITLE
py deprecation: Ignore warnings for dtype=object operations

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Does not appear to impact functioning, but merits root-cause investigation

Towards #17898

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18017)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri and +@russtedrake for review, please

Please note that I am on vacation for most of next week, and may have higher Dex Manip priorities (as I perceive them), so I may be unable to service in-depth feedback for next couple of weeks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18017#-:-NDEOKqS1JCxDMd7cuA2:bbgymy5)* status: LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform), missing label for release notes (waiting on @jwnimmer-tri and @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform review +(release notes: fix).

I'll defer to Russ to test locally / assess as part of his feature review whether this addresses his concerns.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18017#-:-NDEPJ7IAThlMA18EpmA:bd0dn43)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[`bindings/pydrake/test/symbolic_test.py` line 2305 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18017#-NDEP28rD4iB50fjRfwo:-NDEP28rD4iB50fjRfwp:b-1y84dw) ([raw file](https://github.com/robotlocomotion/drake/blob/151589671620fbd87e532fed24c1bb960d802fbd/bindings/pydrake/test/symbolic_test.py#L2305)):*
> ```Python
> 
> class TestIssue17898(unittest.TestCase):
>     def test(self):
> ```

nit Maybe this is too much of a nitpick, buy my preference is that all test cases should have a helpful name.



_Suggestion:_
```Python
def test_matmul_no_warnings(self):
```

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
Tested locally.  I think this is a good short term bandaid.  Thank you.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18017#-:-NDGP48hCEbJgtJ8cRrO:brmxgot)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks!
@seancurtis-tri might you have time to briefly review this (on Monday)?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18017#-:-NDIkzA656H0lOiAF24h:b-polj9m)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`bindings/pydrake/test/symbolic_test.py` line 2305 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18017#-NDEP28rD4iB50fjRfwo:-NDIkurZBClwUVG-gZyL:b-ey2ija) ([raw file](https://github.com/robotlocomotion/drake/blob/151589671620fbd87e532fed24c1bb960d802fbd/bindings/pydrake/test/symbolic_test.py#L2305)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Maybe this is too much of a nitpick, buy my preference is that all test cases should have a helpful name.
</blockquote></details>

Done. This covers a bit more than `matmul`, so tried to expand just a bit.

**Pull request merged**
