### PR TITLE
Completes Migration of AutomotiveSimulator Architecture

### LINKED ISSUE #5541: AutomotiveSimulator Design That Includes PoseAggregator
This issue tracks the redesign of `AutomotiveSimulator` to support the `PoseAggregator`. It's also a solicitation for feedback comments.

# Current Design
The current design is shown in the image below. Multiple levels of multiplexers are used to stitch together `x_c`, which is then fed into `DrakeVisualizer`.

current

# Proposed Redesign - Version 3

In this version, the `VisualizationApplicator` is moved to be after `PoseAggregator`. The reason for this is it allows other systems to optionally subscribe to the `PoseBundle` outputted by `PoseAggregator`, which only contains a single pose for each vehicle. Other sensors that need to know the pose of every body in the simulation can subscribe to the `PoseBundle` outputted by `VisualizationApplicator`.

drake automotivesimulator poseaggregator v3-2

# Proposed Redesign - Version 2

In this version, all of the individual car visualization systems are merged into a single `VisualizationApplicator` system.

drake automotivesimulator poseaggregator v2

# Proposed Redesign - Version 1

Each vehicle model instance outputs a `PoseVector` and `FrameVelocity` that describes the pose and time-derivative-of-the-pose of its "root" body. For each model instance, its outputs are fed into a `CarVisualizer` that adds the poses of all of the other bodies that collectively represent the visualization of the model instance. It also adds any offsets necessary to ensure the visualization's origin is the same as the model's origin (see #5341). It outputs a `PoseBundle`. All of these `PoseBundle` outputs are then fed into the `PoseAggreagator`, whose output is fed into a `PoseBundleToDrawMessage` system. Note that each `CarVisualizer` system also outputs an `lcmt_viewer_load_robot` message that is then also sent to the visualizer.

new_v1

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #5541.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5664)

### CODE REVIEW

**Comment by liangfok** [comment]
+@rpoyner-tri for feature review please.
+@jwnimmer-tri for car review please.

Thanks!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5664#-:-KgTsRnxZzGHZe_ceke1:bi42rgl)*

**Comment by jwnimmer-tri** [comment]
:car: vroom

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5664#-KgTvSyIwD3YiXdj5JvP:-KgTvSyIwD3YiXdj5JvQ:b4dlpt0) ([raw file](https://github.com/robotlocomotion/drake/blob/f16e557023069cd85b6a05d61ac8cc6dac51c63c/drake/automotive/automotive_simulator.cc#L27)):*
> ```cpp
> #include "drake/multibody/joints/floating_base_types.h"
> #include "drake/multibody/parsers/sdf_parser.h"
> #include "drake/multibody/parsers/urdf_parser.h"
> ```

BTW Are any of the `#include` statements unused now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5664#-:-KgTvhbGg6BUx3J7yHCt:b-t5jufo)*

**Comment by liangfok** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5664#-KgTvSyIwD3YiXdj5JvP:-KgUNNFrFhvdAenu1Wp8:bjpkx1) ([raw file](https://github.com/robotlocomotion/drake/blob/f16e557023069cd85b6a05d61ac8cc6dac51c63c/drake/automotive/automotive_simulator.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Are any of the `#include` statements unused now?
</blockquote></details>

Done. I also went through the `.h` file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5664)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5664)*

**Comment by rpoyner-tri** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5664)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5664#-:-KgUd9S5KIkPTCKsivFl:bnfp4nl)*

**Comment by liangfok** [comment]
+@soonho-tri for platform review please. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5664#-:-KgUdfA-m8LLFuee3lib:b-lnsuqk)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5664)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5664#-:-KgV9m9PgQlzuRjUTwsY:bnfp4nl)*

**Pull request merged**
