### PR TITLE
[wheel] Pin numpy to 1.x

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
At the moment, pydrake fails during import with NumPy 2 (#21577).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21582)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21582#-:-O-cOaC_CTVldzn78Ig9:bg7igkv)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Comment by SeanCurtis-TRI** [comment]
> Error: Calling `brew upgrade --ignore-pinned` is disabled! There is no replacement.

**Comment by SeanCurtis-TRI** [comment]
Or is it `stubgen` generation failure?

**Comment by jwnimmer-tri** [comment]
The `AttributeError: itemset ...` indicates that NumPy 2.0 is still being used somewhere.  I'll investigate why/where.

**Comment by jwnimmer-tri** [comment]
Looks like the our `requirement.txt` dependency on `matplotlib` is pulling in a second copy of `numpy` that's not from Homebrew.

**Comment by jwnimmer-tri** [comment]
I'm out of time for today.  The wheels will be broken still for tonight, I guess.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
Well, I guess on macOS a pip-based numpy has been shadowing the Homebrew-based numpy since forever?

Anyway, CI is passing now, so I'll squash this in.

**Pull request merged**
