### PR TITLE
Update to address UBsan flag.

### PR DESCRIPTION
**Pull request by edrumwri**
Candidate fix for Mmanu's UBsan-flagged question.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6591)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@m-chaturvedi for feature review please

Mmanu, this should address the UBsan-flagged issue you broached with me a week ago or so. I failed to produce test code for it, so I'm hoping that UBsan will simply no longer flag it.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6591#-:-KpL4AQ1kpRMdAaMTm7R:btb2anu)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan-release please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by edrumwri** [comment]
+@sammy-tri for platform review please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6591#-:-KpLpu9bfPBze0xq93Yg:b-6xrt9v)*

**Comment by sammy-tri** [comment]
Holding off on platform review until `linux-xenial-clang-experimental-memcheck-ubsan` is passing in CI (haven't investigated in detail, is it expected to be failing at this stage?)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6591#-:-KpMfAI0sA7KJj5JIv_Q:b-wepzcu)*

**Comment by m-chaturvedi** [comment]
Yes, it is expected to be failing at this stage.  We are trying to clean it up.

**Comment by sammy-tri** [comment]
Thanks for the clarification.  Will monitor and review once CI passes.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6591#-:-KpMuoipcFck9m7Z3jaK:bs1vgw7)*

**Comment by sammy-tri** [comment]
Err, actually...  Does that mean that `linux-xenial-clang-experimental-memcheck-ubsan` isn't expected to pass, even when run on this PR, until this PR is merged into master?  Or that you're still working to get that test to pass on this PR?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6591#-:-KpMvG0uUbFXN9AZweQ8:b-svpbai)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri On both master and in this PR, the UBSan build reports many errors.  This PR's purpose is to report one(ish) fewer errors.  The way to see if this PR helps is to click through to the "Details" of the `...-ubsan` build and compare its list of failures with a comparable build of master, e.g., from Continuous or Nightly.

**Comment by m-chaturvedi** [comment]
@sammy-tri I apologize for the ambiguity, by cleaning it up I meant, this PR is an attempt towards getting this build clean.  Like Jeremy we are interested in the delta.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6591#-:-KpQE50hUzCsXw6MJDQS:bnfp4nl)*

**Comment by sammy-tri** [comment]
Does this mean I need to do an override merge?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6591#-:-KpQE95WcPAT5d8mEjsV:b7anmj4)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri Nope.  There is no `[Required]` badge on the failed build, so the normal merge buttons will work.

Though it looks like this PR needs a curate (squash and merge), so be careful.

**Pull request merged**
