### PR TITLE
[planning] Restore move semantics to BodyShapeDescription

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18472)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@calderpg-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18472#-:-NJR_GLQCxMKj1yzZtdf:b-mrbmvx)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @calderpg-tri)

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18472#-:-NJRaXfjDpqCQMD2CHoR:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri blind :lgtm: platform for progress fwd and given feature LGTM

I don't understand the value / motivation of this PR. Would be helpful to have paper trail against issue / slack / brief desc. in overview

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18472#-:-NJS57CaE-5QJZW8rcXF:bylbtrz)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),calderpg-tri (waiting on @rpoyner-tri)

**Comment by rpoyner-tri** [comment]
discussed here: https://tri-internal.slack.com/archives/C02KXJ6LM54/p1671216996031239

**Pull request merged**
