### PR TITLE
Add names to dynamics-related systems.

### PR DESCRIPTION
**Pull request by david-german-tri**
And also some miscellaneous systems.

@SeanCurtis-TRI for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5839)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
Easiest. Feature review. Ever.

:lgtm: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5839#-:-Khi0yjUYQgztqfDzj_e:bt9pn21)*

**Comment by david-german-tri** [comment]
+@soonho-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5839#-:-Khi3O0mK2LuF6J1z3cS:bcjsslk)*

**Comment by soonho-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5839)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5839#-:-KhlPv4kyqujcMBta5_r:bnfp4nl)*

**Pull request merged**
