### PR TITLE
Allow GetDowncastSubsystemByName to work with non-templatized system

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
`Diagram` already supports this. This gives `DiagramBuilder` the analogous functionality.

In contrast with `Diagram`, this uses the hypothesis that the extra C++ plumbing doesn't need to be documented in doxygen.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19925)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with one BTW
+@sammy-tri for platform review per schedule, please

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19925#-:-NatsSam9XsqN5EDXJ25:br4o73e)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`systems/framework/diagram_builder.h` line 329 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19925#-Natruk5EeX_Cpf192dH:-Natruk6Bw9H6gRx9uRR:b-6mokkv) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e1079bf5a528395ac1e53c19081da9ee52ab7ad/systems/framework/diagram_builder.h#L329)):*
> ```objc
>   /// We're omitting it from the doxygen as the details are unhelpful.
>   /// The requested LeafSystem must still have the same underlying scalar type
>   /// as this builder.
> ```

BTW consider using `//` comments here to avoid the implication that this goes to Doxygen.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19925)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: going with +(release notes: none) since if it's not documented in doxygen...

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19925#-:-NawBda70D3mkDznRM1z:b22ofcj)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform)

**Comment by jwnimmer-tri** [comment]
I would actually suggest "fix".  There is no new Doxygen because the documentation for the pre-existing overload was sufficient to cover the new overload.  This PR expands the kinds of arguments that the function accepts now, which is a notable improvement.

**Pull request merged**
