### PR TITLE
Fix Wunused-parameter in sensors

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6012)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.  This is using the new `unused` helper function ([docs](http://drake.mit.edu/doxygen_cxx/namespacedrake.html#ade20b7bf635eecb13adbaac4df980af0)).

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6012#-:-KjBCUSbXsWS-HbUmMbP:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6012#-:-KjDRQjeo5ZDiRLHM-hW:bnfp4nl)*

**Pull request merged**
