### PR TITLE
[tutorials] Cite new tools for OBJ loading

### LINKED ISSUE #17267: Parser support for obj files directly
When adding manipulands to a scene, the current workflow is to develop a mesh for the object, and then write an SDFormat file that refers to the mesh, then feed that SDFormat file to the parser.  Both the mesh and the SDFormat file go into source control.

The content of the SDFormat file is fairly boilerplate, and we often create it using semi-scripted methods.  Even with that, it's extra work to write and maintain that boilerplate.

We should update the `multibody::Parser` to accept `*.obj` files directly as an input format.

It should add a new model instance, floating body, visual and proximity geometry, and should compute the mass and inertia from the mesh itself, using approximations as necessary (e.g., assume uniform density, possibly even assume the density of water).

One problem will be the units of the mesh.  Mesh tools tend to operate on obj files in centimeters (millimeters?) by convention, but we also have meshes that use meters.  We might need a way for the user to specify their units, but I'm not sure how to do that.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #17267.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`tutorials/authoring_multibody_simulation.ipynb` line 388 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NR_FY0t5ZsJGQHkx3vw:-NR_FY0u-QXpV92xDzAA:b-8cbydf) ([raw file](https://github.com/RobotLocomotion/drake/blob/21197cd4f8f30ed2751b3a5469ab9653a005ca37/tutorials/authoring_multibody_simulation.ipynb#L388)):*
> ```
>     "    # Load a cracker box from Drake. \n",
>     "    parser.AddModels(\n",
>     "        url=\"package://drake/manipulation/models/ycb/sdf/003_cracker_box.sdf\")\n",
> ```

nit: Drive by. As long as we're loading a model and filling it with water, perhpas the `010_potted_meat_can.sdf` would be better? Or, the tomato soup can or mustard bottle? Of all of the ycb models we have in that directory, the cracker box is the *worst* candidate for this treatment.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`tutorials/authoring_multibody_simulation.ipynb` line 388 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NR_FY0t5ZsJGQHkx3vw:-NS6lkR3B5dvJiMYr9j9:b-6qxioe) ([raw file](https://github.com/RobotLocomotion/drake/blob/21197cd4f8f30ed2751b3a5469ab9653a005ca37/tutorials/authoring_multibody_simulation.ipynb#L388)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Drive by. As long as we're loading a model and filling it with water, perhpas the `010_potted_meat_can.sdf` would be better? Or, the tomato soup can or mustard bottle? Of all of the ycb models we have in that directory, the cracker box is the *worst* candidate for this treatment.
</blockquote></details>

The cracker box is loaded from SDFormat, not OBJ.  I only relocated a few lines of code for clarity.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NRcfvLvEUgIF6ZmRssj:-NS6tUhoEU-y0rfuPYAc:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Parser class overview should link the relevant tutorial.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NRcfssMCAve4DxLVcB1:-NS6y12kDs01fZLtL6if:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Add a citation to mesh_to_model.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NS6yE3SBa_IpDSfY2vD:-NS6yE3SBa_IpDSfY2vE:b-q3jwqy) (no related file):*
Working

Cite obj2mjcf.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NS6yE3SBa_IpDSfY2vD:-NS7NTY68klW1Xv4ExsG:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Cite obj2mjcf.
</blockquote></details>

Done.

___

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please.  Low priority.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070)* status: 1 unresolved discussion, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NS7zit52WBSnQHLYCkg:-NS7zit52WBSnQHLYCkh:b-w4lfm3) (no related file):*
Working

Investigating Debug build time.  On master on my computer, it takes 200 seconds.  With the PR, it's bombing after >600.

I think the problem is that we've set the MbP timestep to 100 microseconds (why?!).  I'll see if maybe 1ms is more sane.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NS7zit52WBSnQHLYCkg:-NS82URgExUjRt6ujC_t:bdklpvc) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Investigating Debug build time.  On master on my computer, it takes 200 seconds.  With the PR, it's bombing after >600.

I think the problem is that we've set the MbP timestep to 100 microseconds (why?!).  I'll see if maybe 1ms is more sane.
</blockquote></details>

Ok, the 100us does a good job of showing collision instability vs 1ms or 10ms.  I've kept it, but instead shortened the simulation from 5 sec to 2 sec.  Things settle out after ~1.5 seconds anyway.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NS7zit52WBSnQHLYCkg:-NS8BLopCLWEgphA-YjQ:b-nljjra) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ok, the 100us does a good job of showing collision instability vs 1ms or 10ms.  I've kept it, but instead shortened the simulation from 5 sec to 2 sec.  Things settle out after ~1.5 seconds anyway.
</blockquote></details>

Even 2 seconds was pushing it.  I switched to 0.1 seconds for CI test.

___

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-:-NSZMx1Y1lzuKWBuQHbf:b-uwkowd)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`tutorials/authoring_multibody_simulation.ipynb` line 238 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NSZBrPZ6qeiU9RdY2ms:-NSZBrPZ6qeiU9RdY2mt:by3qn7y) ([raw file](https://github.com/RobotLocomotion/drake/blob/5062d3ae13ad297f7dc4b45217992be0f6a9045a/tutorials/authoring_multibody_simulation.ipynb#L238)):*
> ```
>     "### Creating an SDFormat wrapper around a mesh file\n",
>     "\n",
>     "You might have a mesh file of an object to manipulate and want to add it to a simulation. The easiest option is to pass the OBJ filename to Parser.AddModels directly. Parsing it directly will use default assumptions for scale, mass, etc.\n",
> ```

BTW. Maybe we can do the backtick highlight for the function name for readability (the somehow confusing `.`).



_Suggestion:_
```
`Parser.AddModels`
```
___
*[`tutorials/authoring_multibody_simulation.ipynb` line 238 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NSZLH7oEfqcvk5xN2l2:-NSZLH7p0CRq6-2O4K4a:b367p0a) ([raw file](https://github.com/RobotLocomotion/drake/blob/5062d3ae13ad297f7dc4b45217992be0f6a9045a/tutorials/authoring_multibody_simulation.ipynb#L238)):*
> ```
>     "### Creating an SDFormat wrapper around a mesh file\n",
>     "\n",
>     "You might have a mesh file of an object to manipulate and want to add it to a simulation. The easiest option is to pass the OBJ filename to Parser.AddModels directly. Parsing it directly will use default assumptions for scale, mass, etc.\n",
> ```

BTW. Should we say OBJ file path or URL to be more explicit?



_Code quote:_
```
filename
```
___
*[`tutorials/rendering_multibody_plant.ipynb` line 296 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NSZFuWq3zbzs-ABQX6G:-NSZFuWq3zbzs-ABQX6H:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/5062d3ae13ad297f7dc4b45217992be0f6a9045a/tutorials/rendering_multibody_plant.ipynb#L296)):*
> ```
>    "source": [
>     "## Add depth and label colorizers.\n",
>     "The systems convert a depth (or label) image into color image, so we can easily preview it."
> ```

nit.



_Suggestion:_
```
into a color image
```
___
*[`tutorials/rendering_multibody_plant.ipynb` line 418 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NSZLX1PB4P5aBYovPWQ:-NSZLX1PB4P5aBYovPWR:b-j1b61m) ([raw file](https://github.com/RobotLocomotion/drake/blob/5062d3ae13ad297f7dc4b45217992be0f6a9045a/tutorials/rendering_multibody_plant.ipynb#L418)):*
> ```
>     "inspector = query_object.inspector()\n",
>     "for geometry_id in inspector.GetAllGeometryIds():\n",
>     "    properties = copy.copy(inspector.GetPerceptionProperties(geometry_id))\n",
> ```

BTW/question. From these two lines of replacing perception properties, should we make a deep copy instead of a shallow copy?
```
scene_graph.RemoveRole(scene_graph_context, source_id, geometry_id, Role.kPerception)
scene_graph.AssignRole(scene_graph_context, source_id, geometry_id, properties)
```



_Code quote:_
```
copy.copy
```
___
*[`tutorials/rendering_multibody_plant.ipynb` line 431 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NSZK_Vl94jyqh3npfqI:-NSZK_Vl94jyqh3npfqJ:b-z7u36l) ([raw file](https://github.com/RobotLocomotion/drake/blob/5062d3ae13ad297f7dc4b45217992be0f6a9045a/tutorials/rendering_multibody_plant.ipynb#L431)):*
> ```
>     "\n",
>     "label = colorize_label.get_output_port().Eval(\n",
>     "    colorize_label.GetMyContextFromRoot(diagram_context)).data    \n",
> ```

nit. Trailing spaces.



_Suggestion:_
```
data
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-:-NSfSyuW8F9EjyTE0Hss:b4mx0my)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @zachfang)

___
*[`tutorials/rendering_multibody_plant.ipynb` line 418 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NSZLX1PB4P5aBYovPWQ:-NSfRbyWA3oO888oGxtu:b520y5t) ([raw file](https://github.com/RobotLocomotion/drake/blob/5062d3ae13ad297f7dc4b45217992be0f6a9045a/tutorials/rendering_multibody_plant.ipynb#L418)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW/question. From these two lines of replacing perception properties, should we make a deep copy instead of a shallow copy?
```
scene_graph.RemoveRole(scene_graph_context, source_id, geometry_id, Role.kPerception)
scene_graph.AssignRole(scene_graph_context, source_id, geometry_id, properties)
```
</blockquote></details>

As it happens, copy and deepcopy are equivalent here (our bindings basically never bind a shallow copy).  But you're right that deepcopy is the intention.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-:-NSfa1NL4McTnAgtx_EQ:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tutorials/authoring_multibody_simulation.ipynb` line 240 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19070#-NSfZkQq1Z4FCXFCfIMi:-NSfZkQq1Z4FCXFCfIMj:b2wndc0) ([raw file](https://github.com/RobotLocomotion/drake/blob/a98f858c280846e3baa12ebaddc9c23f114f2cf0/tutorials/authoring_multibody_simulation.ipynb#L240)):*
> ```
>     "You might have a mesh file of an object to manipulate and want to add it to a simulation. The easiest option is to pass the OBJ file to `Parser.AddModels` directly. Parsing it directly will use default assumptions for scale, mass, etc.\n",
>     "\n",
>     "In case those defaults are insufficient, you should create an SDFormat wrapper file to specify the additional properties (mass, inertia, scale, compliance, etc.) and load that file instead. You can use the [pydrake.multibody.mesh_to_model](https://drake.mit.edu/pydrake/pydrake.multibody.mesh_to_model.html) command-line tool to generate a nominal SDFormat file that you can then further customize.\n",
> ```

nit, discretionary:  I'm not sure "nominal" is clear here -- it could mean "in name only" or "as designed" or "ideal" or plenty of other shades of not quite right; https://www.merriam-webster.com/dictionary/nominal

I'd suggest "basic" or "baseline" or "prototype" or something similar.



_Suggestion:_
```
baseline
```

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19070)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),zachfang (waiting on @jwnimmer-tri)

**Pull request merged**
