### PR TITLE
yaml: Fix parsing bugs with zero-sized matrices

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
As promised during #14327 review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14360)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: perfect; thank you

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14360#-:-MMVw3TzBM7ejB1iFRug:bunffly)* status: needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@seancurtis-tri for platform

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14360#-:-MMW6ilV8CyX_35ywwsi:b-drqrgr)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With two passing thoughts (as a very-much-*not*-a-feature reviewer).

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14360#-:-MMW8wdN4nV4UkStk2GS:b-sksui6)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[common/yaml/yaml_read_archive.h, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14360#-MMW7hgD8aJF57fhH3dY:-MMW7hgD8aJF57fhH3dZ:bd3l3ks) ([raw file](https://github.com/robotlocomotion/drake/blob/74233adebd538290ffc24855424821dc8c7d09cb/common/yaml/yaml_read_archive.h#L427)):*
> ```objc
>     size_t rows = sub_node.size();
>     size_t cols = (rows == 0) ? 0 : sub_node[0].size();
>     for (size_t i = 1; i < rows; ++i) {
> ```

BTW Would it be obvious to someone more versed in yaml why we're skipping the first row, even though we felt it was important enough to define the number of columns we have? Is it some kind of header?
___
*[common/yaml/yaml_read_archive.h, line 441 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14360#-MMW7H2HARG3cdjJGFMZ:-MMW7H2HARG3cdjJGFM_:b-c15j31) ([raw file](https://github.com/robotlocomotion/drake/blob/74233adebd538290ffc24855424821dc8c7d09cb/common/yaml/yaml_read_archive.h#L441)):*
> ```objc
>       }
>     }
>     if (cols == 0) {
> ```

BTW It seems that this will be really inscrutable. This handles the case where you're dealing with an Nx0 matrix, which is treated as a 0x0 matrix. It might help future readers if that were spelled out rather than having them infer it.

I spent a minute thinking, "Waitasec...isn't cols zero *because* rows was zero?"  and searching for possible changes to `rows` inside the loop. That's when I realized the unexpected Nx0 case.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14360)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[common/yaml/yaml_read_archive.h, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14360#-MMW7hgD8aJF57fhH3dY:-MMWG9xDCmT3V3UY7Dru:b-g5ow2o) ([raw file](https://github.com/robotlocomotion/drake/blob/74233adebd538290ffc24855424821dc8c7d09cb/common/yaml/yaml_read_archive.h#L427)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Would it be obvious to someone more versed in yaml why we're skipping the first row, even though we felt it was important enough to define the number of columns we have? Is it some kind of header?
</blockquote></details>

Oops.  I tried to get cute by because the size check was done above, but I forgot the Sequence check was here too.  I've put back the zero.
___
*[common/yaml/yaml_read_archive.h, line 441 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14360#-MMW7H2HARG3cdjJGFMZ:-MMWH2tR5HVufVu46TSg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74233adebd538290ffc24855424821dc8c7d09cb/common/yaml/yaml_read_archive.h#L441)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It seems that this will be really inscrutable. This handles the case where you're dealing with an Nx0 matrix, which is treated as a 0x0 matrix. It might help future readers if that were spelled out rather than having them infer it.

I spent a minute thinking, "Waitasec...isn't cols zero *because* rows was zero?"  and searching for possible changes to `rows` inside the loop. That's when I realized the unexpected Nx0 case.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14360)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14360)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

___
*[common/yaml/yaml_read_archive.h, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14360#-MMW7hgD8aJF57fhH3dY:-MMWJvr8CG2KLwplotwX:bj5x09x) ([raw file](https://github.com/robotlocomotion/drake/blob/74233adebd538290ffc24855424821dc8c7d09cb/common/yaml/yaml_read_archive.h#L427)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops.  I tried to get cute by because the size check was done above, but I forgot the Sequence check was here too.  I've put back the zero.
</blockquote></details>

Seems this points to a test coverage failure? If tests pass either way....

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14360)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

___
*[common/yaml/yaml_read_archive.h, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14360#-MMW7hgD8aJF57fhH3dY:-MMWOjoZ2lo5pa4YbD9j:b-v9i449) ([raw file](https://github.com/robotlocomotion/drake/blob/74233adebd538290ffc24855424821dc8c7d09cb/common/yaml/yaml_read_archive.h#L427)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Seems this points to a test coverage failure? If tests pass either way....
</blockquote></details>

By glass box, the zero'th row is no longer special, so the VisitEigenMatrixFoundNonSquare covers us.

**Pull request merged**
