### PR TITLE
framework_py: Enable overriding of `DoHasDirectFeedthrough`.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7930)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.
+@soonho-tri for platform review, please.

\cc @gizatt 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7930#-:-L4JI2ZZ9Q3Bhic2qiSC:bny6rm)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/framework_py.cc, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7930#-L4JqJJFSsrPKTFOR1gJ:-L4JqJJFSsrPKTFOR1gK:b-4qpul7) ([raw file](https://github.com/robotlocomotion/drake/blob/460d0c0dce5998cceefe8e1936b79d29de6f7b0c/bindings/pydrake/systems/framework_py.cc#L168)):*
> ```cpp
>         input_port, output_port);
>     return Base::DoHasDirectFeedthrough(input_port, output_port);
>   }
> ```

FYI I don't have a good mental model of what this is doing, so a question -- is this block of code covered by a unit test and/or should it be?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7930#-:-L4JqSjplqb37rI4_Nq6:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/framework_py.cc, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7930#-L4JqJJFSsrPKTFOR1gJ:-L4Jt7FuUE5A-kIaqYaj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/460d0c0dce5998cceefe8e1936b79d29de6f7b0c/bindings/pydrake/systems/framework_py.cc#L168)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I don't have a good mental model of what this is doing, so a question -- is this block of code covered by a unit test and/or should it be?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7930)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7930)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7930#-:-L4MB3upeYa5WFWVpScU:bnfp4nl)*

**Pull request merged**
