### PR TITLE
Reduce macOS console spam

### PR DESCRIPTION
**Pull request by williamjallen**
~Partially resolves~ Towards https://github.com/RobotLocomotion/drake/issues/17933.

This PR fixes the Pandas-related console spam which is currently appearing on macOS.  This PR only fixes the source of the existing spam and makes no attempt to suppress similar spam.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18573)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Howdy, @williamjallen! This PR does not yet have a reviewer assigned. Is it ready for review yet? If yes, then please assign a feature reviewer (maybe @jwnimmer-tri?). If not, then please label it “status: do not review”.

**Review by EricCousineau-TRI — COMMENTED** [review]
After inspecting issue and fix, looks relatively self-consistent and straightforward to evaluate fix; +@EricCousineau-TRI +(status: single reviewer ok) :lgtm_strong:, thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18573#-:-NLbHYBI7DQK62gPdeu3:b13u7jn)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @williamjallen)

**Comment by EricCousineau-TRI** [comment]
FYI I crossed modified "partial resolves {issue}" to "Towards {issue}", as the substring "resolves {issue}" will trigger GitHub PR linking: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Working to check appropriate release notes label.

**Comment by EricCousineau-TRI** [comment]
It's not immediately clear to me if this should be `fix` or `none`. For now, I will change to `none`.
@jwnimmer-tri Please let me know if this is incorrect.

**Comment by jwnimmer-tri** [comment]
I am OK with "notes: none".

**Pull request merged**
