### PR TITLE
Various docker-related fixes

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11530)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by jwnimmer-tri** [comment]
The fact that the docker instructions exclude portions of the source tree is brittle, and this failure was a consequence of that.  I can buy excluding `.git`, but even excluding `.gitattributes` and `.github` like we still do in this PR is pointless and hazards future breaks like this one.  A docker build should not use different source image than would come from downloading a source archive from github.com.

**Comment by jamiesnape** [comment]
That is the standard docker workflow. It is standard practice. The defect is use an IDE file for a purpose for which it was most certainly not defined.

**Comment by jwnimmer-tri** [comment]
Standard practice or not, if we want to use brittle techniques in the Dockerfile, then we need to have it under CI test.

**Comment by jamiesnape** [comment]
I disagree whether it is brittle in the same way that we disagree that using an IDE config file is bad practice. And yes, it should be under CI, but it is a matter of priorities, and clearly basically no-one is using Docker given this broke 5-6 months ago.

**Comment by ggould-tri** [comment]
https://drake.mit.edu/docker.html definitely gives a clear and definitive impression that Docker support is a gross and unsupported hack.  This PR seems in keeping with that spirit.  @jwnimmer-tri would it mollify you to make that  unsupporting language stronger and memorialize this discussion in an issue linked from that page?

**Comment by jwnimmer-tri** [comment]
#7654 already exists, where this has been discussed at length.

**Pull request merged**
