### PR TITLE
Fix Wunused-parameter in benchmarks

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6004)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@mitiguy for feature review, please.  This is using the new `unused` helper function ([docs](http://drake.mit.edu/doxygen_cxx/namespacedrake.html#ade20b7bf635eecb13adbaac4df980af0)).

My interpretation of the intent was to pass theta1 and theta2 all the time to every function for consistency, even if some functions didn't use the information.  If that was mistaken, or you'd prefer me to remove the parameters instead, just let me know.

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

@mitiguy Please take a look today if you have anything to add; otherwise I will plan to merge without your input and then fix any problems later.

**Comment by sherm1** [comment]
:lgtm: pending @mitiguy's approval. (My thought is that it would be better not to pass those arguments at all but I'm not sure.)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6004#-:-KjOJgAS_n1kvTatBYj8:b6kbocf)*

**Comment by jwnimmer-tri** [comment]
@sherm1 May I please have your permission to merge this even without any response from Paul?  It's been four days and I need this to go in.  I promise to change it later if Paul responds with a different request.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6004#-:-KjOg6x6muqXMvcPEJP7:bu83fbe)*

**Comment by sherm1** [comment]
Paul is looking at it right now ...

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6004#-:-KjOrKpyjFfMMjZkZdVt:b-7q3rag)*

**Comment by mitiguy** [comment]
:lgtm: 
Note: I did not write this code, but it seems reasonable to check it in.
However, I think passing unused parameters as odd.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6004#-:-KjOrfq4mqnZuxpdAuBA:b-vkhah5)*

**Comment by jwnimmer-tri** [comment]
Paul: Aha!  I thought all of the benchmarks were yours, but I see now only the `cylinder_torque_free_analytical_solution` is yours.  My mistake, sorry!  I should have checked git.

+@siyuanfeng-tri for feature review, please.  Please see upthread for my question on the intent of this code.
-(status: do not merge) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6004#-:-KjOsn5olKqvjFlkpq66:b-nuohyw)*

**Comment by sherm1** [comment]
Probably better without those extra parameters but fine with me to merge.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6004#-:-KjOtdAjK0jo3L-a9JBd:bc1zco9)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 
i agree with sherm, since the numbers are not needed in those computations ever. so might be better to take them out instead? 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6004#-:-KjP3_yNz_nScyADpjdd:bxycakv)*

**Comment by jwnimmer-tri** [comment]
No problem; if the author doesn't want them, I'll kill them.

**Comment by jwnimmer-tri** [comment]
@sherm1 PTAL please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6004#-:-KjQJOwcBc1zcA4mpJ3h:b-lcpjvy)*

**Comment by sherm1** [comment]
Great -- thanks!

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6004#-:-KjR5fwS5pXjKV1mTrwh:bo8g7m8)*

**Pull request merged**
