### PR TITLE
Add PoseAggregator within AutomotiveSimulator

### PR DESCRIPTION
**Pull request by jadecastro**
Connecting it to outputs of SimpleCar and TrajectoryCar.  Additionally, add `PoseVector` and `FrameVelocity` outputs to `TrajectoryCar`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5474)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@liangfok for feature review, please.

**Comment by liangfok** [comment]
Completed first pass.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7zdPq6B20gXcuEzg6:-Kf7zdPq6B20gXcuEzg7:b-kr4c4i) (no related file):*
Should we add unit tests for the changes to `AutomotiveSimulator`?

---

*[drake/automotive/automotive_simulator.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7xSFLr9rC3AhqaT0O:-Kf7xSFLr9rC3AhqaT0P:b-twlzs) ([raw file](https://github.com/robotlocomotion/drake/blob/04326c42a495618ca76cd46e4153831724364b76/drake/automotive/automotive_simulator.cc#L92)):*
> ```cpp
>       builder_->template AddSystem<SimpleCarToEulerFloatingJoint<T>>();
>   const auto& descriptor = aggregator_->AddSingleInput(
>       "simple_car" + std::to_string(vehicle_number));
> ```

BTW, is there a hazard here of `descriptor` referencing something on the stack of the previously called method? To alleviate this worry, consider only saving the port's index.

---

*[drake/automotive/automotive_simulator.cc, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7xq8vP1CPOUIsbPGo:-Kf7xq8vP1CPOUIsbPGp:b3d3s33) ([raw file](https://github.com/robotlocomotion/drake/blob/04326c42a495618ca76cd46e4153831724364b76/drake/automotive/automotive_simulator.cc#L118)):*
> ```cpp
>   auto coord_transform =
>       builder_->template AddSystem<SimpleCarToEulerFloatingJoint<T>>();
>   const auto& descriptor = aggregator_->AddSingleInput(
> ```

ditto re: just saving the index value instead of a reference to the whole descriptor.

---

*[drake/automotive/trajectory_car.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7zJy6kG-BG1cCEMAQ:-Kf7zJy6kG-BG1cCEMAR:b-m4guhw) ([raw file](https://github.com/robotlocomotion/drake/blob/04326c42a495618ca76cd46e4153831724364b76/drake/automotive/trajectory_car.h#L26)):*
> ```objc
> /// * none
> ///
> /// output port 0:
> ```

BTW, consider documenting the getter methods for obtaining each of these ports.

_(Feel free to punt.)_

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-:-Kf825zRPIG_Nphk117e:bl4rucz)*

**Comment by jadecastro** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7zdPq6B20gXcuEzg6:-KfBzHPhKUx7ifW4DRXR:b1ob5ww) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should we add unit tests for the changes to `AutomotiveSimulator`?
</blockquote></details>

There are no public accessors that expose the changes, so I did not include any new unit tests. I think it suffices that the unit test does not throw an error?

---

*[drake/automotive/automotive_simulator.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7xSFLr9rC3AhqaT0O:-KfEPf9RF5oaF-nF0Zes:b-dbilw8) ([raw file](https://github.com/robotlocomotion/drake/blob/04326c42a495618ca76cd46e4153831724364b76/drake/automotive/automotive_simulator.cc#L92)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is there a hazard here of `descriptor` referencing something on the stack of the previously called method? To alleviate this worry, consider only saving the port's index.
</blockquote></details>

I'm not sure what you mean. This is output from a `PoseAggregator` method, and it's `const`, so I can trust that calling `descriptor.get_index()` later on will give me the port for this particular system.

---

*[drake/automotive/automotive_simulator.cc, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7xq8vP1CPOUIsbPGo:-KfERli7sD1wxQ3Hb1Ge:byjlfh8) ([raw file](https://github.com/robotlocomotion/drake/blob/04326c42a495618ca76cd46e4153831724364b76/drake/automotive/automotive_simulator.cc#L118)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

ditto re: just saving the index value instead of a reference to the whole descriptor.
</blockquote></details>

(see above)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474)*

**Comment by jadecastro** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/automotive/trajectory_car.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7zJy6kG-BG1cCEMAQ:-KfEWe3pkHI2vCCnsElD:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/04326c42a495618ca76cd46e4153831724364b76/drake/automotive/trajectory_car.h#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider documenting the getter methods for obtaining each of these ports.

_(Feel free to punt.)_
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7zdPq6B20gXcuEzg6:-KfEdHsRdPmUUK_riopf:bqcmn80) (no related file):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

There are no public accessors that expose the changes, so I did not include any new unit tests. I think it suffices that the unit test does not throw an error?
</blockquote></details>

Good point. The lack of publisher accessors is one reason I resorted to checking LCM messages here:

https://reviewable.io/reviews/robotlocomotion/drake/5473#-Kf6rqzYNcsleRlX8uGA

I suppose since `PoseAggregator`'s output isn't actually being hooked up yet, we can punt on unit test coverage to the PR that makes use of the output.

---

*[drake/automotive/automotive_simulator.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-Kf7xSFLr9rC3AhqaT0O:-KfEejqNVa1J1n0Jx5C4:bi8kc50) ([raw file](https://github.com/robotlocomotion/drake/blob/04326c42a495618ca76cd46e4153831724364b76/drake/automotive/automotive_simulator.cc#L92)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

I'm not sure what you mean. This is output from a `PoseAggregator` method, and it's `const`, so I can trust that calling `descriptor.get_index()` later on will give me the port for this particular system.
</blockquote></details>

Nevermind. I see now that the returned value is actually `*input_ports_.back();` in system.h. Marking myself satisfied.

---

*[drake/automotive/trajectory_car.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfEhFmTqU7Q7b17QCia:-KfEhFmTqU7Q7b17QCib:b6u5t9b) ([raw file](https://github.com/robotlocomotion/drake/blob/d41a2b70abe5ed56f5f11d1dbe27dba2525a6962/drake/automotive/trajectory_car.h#L61)):*
> ```objc
>   }
> 
>   const systems::OutputPortDescriptor<T>& raw_pose_output() const {
> ```

BTW, consider adding a Doxygen comment here:

```
/// See class description for details about this port.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-:-KfEhiJD96ekAFYfLlNl:bnfp4nl)*

**Comment by jadecastro** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/trajectory_car.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfEhFmTqU7Q7b17QCia:-KfEo8ompxetYDtPCoO7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d41a2b70abe5ed56f5f11d1dbe27dba2525a6962/drake/automotive/trajectory_car.h#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding a Doxygen comment here:

```
/// See class description for details about this port.
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474)*

**Comment by jadecastro** [comment]
+@jwnimmer-tri for platform, automotive review, please.

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

@david-german-tri can you take a quick look at trajectory_car.h's output port 1 and 2 (the PoseAggregator-destined outputs) and see if they look okay to you?

---

Reviewed 1 of 4 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/trajectory_car.h, line 58 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfH_Njzz42DK8TcoDRQ:-KfH_Njzz42DK8TcoDRR:bdf1dd4) ([raw file](https://github.com/robotlocomotion/drake/blob/a758afa8c08a0e83b91acf68339d5647b3c81a40/drake/automotive/trajectory_car.h#L58)):*
> ```objc
>                             systems::rendering::PoseVector<T>::kSize);
>     this->DeclareOutputPort(systems::kVectorValued,
>                             systems::rendering::FrameVelocity<T>::kSize);
> ```

_Meta_ Please retain and continue using `DeclareVectorOutputPort` and provide a model value, and don't implement `AllocateOutputVector` override.

---

*[drake/automotive/trajectory_car.h, line 108 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfHeUchfChc-bnojUpV:-KfHeUchfChc-bnojUpW:b5ifno5) ([raw file](https://github.com/robotlocomotion/drake/blob/a758afa8c08a0e83b91acf68339d5647b3c81a40/drake/automotive/trajectory_car.h#L108)):*
> ```objc
>         return nullptr;
>     }
>   }
> ```

Remove this method, per above comment.

---

*[drake/automotive/trajectory_car.h, line 141 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfHi4uP7HeDLdBkvYwI:-KfHi4uQ2uk5IsEtuzru:bd0yuuu) ([raw file](https://github.com/robotlocomotion/drake/blob/a758afa8c08a0e83b91acf68339d5647b3c81a40/drake/automotive/trajectory_car.h#L141)):*
> ```objc
>     // Convert the state derivatives into a spatial velocity.
>     const T heading = std::atan2(raw_pose.position_dot[1],
>                                  raw_pose.position_dot[0]);
> ```

BTW Perhaps CalcRawPose should return the heading, since the computation of it is duplicated into a few places?.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-:-KfHiG5B52tWc_5jv8Cw:bjjhxcy)*

**Comment by david-german-tri** [comment]
Looks reasonable to me.  Did you have a particular concern?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-:-KfHqaO1PprTtCbS6XIi:b-87owyx)*

**Comment by jwnimmer-tri** [comment]
Nope, just not many examples yet so wanted a double-check on best practices using the pose / velocity ports.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-:-KfI8XLQnHY5y7Jzsp2d:b-aaw97)*

**Comment by jadecastro** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/trajectory_car.h, line 58 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfH_Njzz42DK8TcoDRQ:-KfIVU6BB0fZgJ0JiCaW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e090e1ec9b1011de622d166c5f6a14b05c9b28d3/drake/automotive/trajectory_car.h#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ Please retain and continue using `DeclareVectorOutputPort` and provide a model value, and don't implement `AllocateOutputVector` override.
</blockquote></details>

Done.

---

*[drake/automotive/trajectory_car.h, line 108 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfHeUchfChc-bnojUpV:-KfIVTVvFhM2zxC7i04X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e090e1ec9b1011de622d166c5f6a14b05c9b28d3/drake/automotive/trajectory_car.h#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Remove this method, per above comment.
</blockquote></details>

Done.

---

*[drake/automotive/trajectory_car.h, line 141 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfHi4uP7HeDLdBkvYwI:-KfIVZ6Girmb3f8jV7b2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e090e1ec9b1011de622d166c5f6a14b05c9b28d3/drake/automotive/trajectory_car.h#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Perhaps CalcRawPose should return the heading, since the computation of it is duplicated into a few places?.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/trajectory_car_test.cc, line 141 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfJCxCPS1SaVQfJlilS:-KfJCxCPS1SaVQfJlilT:bjx62hn) ([raw file](https://github.com/robotlocomotion/drake/blob/04391b24b63b1738f146c3c6545e0b195e154bb6/drake/automotive/test/trajectory_car_test.cc#L141)):*
> ```cpp
>       EXPECT_EQ(FrameVelocity<double>::kSize, velocity->size());
> 
>       std::cerr << it.speed << std::endl;
> ```

BTW Remove?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-:-KfJD5AHC5Y95iv10wEy:bnfp4nl)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/trajectory_car.h, line 155 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfJiZPVCqXB1TeND21M:-KfJiZPVCqXB1TeND21N:bc4au6m) ([raw file](https://github.com/robotlocomotion/drake/blob/04391b24b63b1738f146c3c6545e0b195e154bb6/drake/automotive/trajectory_car.h#L155)):*
> ```objc
>   const Curve2<double> curve_;
>   const double speed_;
>   const double start_time_;
> ```

BTW, these `double` member variables need to be initialized using `{}` per style guide.

http://drake.mit.edu/code_style_guide.html#additional-rules

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474)*

**Comment by jadecastro** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/automotive/trajectory_car.h, line 155 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfJiZPVCqXB1TeND21M:-KfLfCbIte1c2eRb4YHH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/04391b24b63b1738f146c3c6545e0b195e154bb6/drake/automotive/trajectory_car.h#L155)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, these `double` member variables need to be initialized using `{}` per style guide.

http://drake.mit.edu/code_style_guide.html#additional-rules
</blockquote></details>

Done.

---

*[drake/automotive/test/trajectory_car_test.cc, line 141 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5474#-KfJCxCPS1SaVQfJlilS:-KfLfDdL8e_9_DmGxmEs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/04391b24b63b1738f146c3c6545e0b195e154bb6/drake/automotive/test/trajectory_car_test.cc#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Remove?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474)*

**Comment by jadecastro** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please.

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5474)*

**Pull request merged**
