### PR TITLE
[pydrake] Bind some hydroelastic-related classes and functions

### LINKED ISSUE #16212: [bindings] Bind public APIs for hydroelastics in python
To make hydroelastic contact model useful for more users, we should have python bindings for relevant public APIs including:
- drake/bindings/pydrake/geometry_py_hydro.cc
  - PolygonSurfaceMesh
  - SurfacePolygon
- drake/bindings/pydrake/geometry_py_scene_graph.cc
  - QueryObject
    - ComputeContactSurfaces()
    - ComputeContactSurfacesWithFallback()
  - HydroelasticContactRepresentation
  - ContactSurface
      - poly_mesh_W()
      - is_triangle()

Relates #15796. 

I'm not sure yet how extensive the bindings should be.  It might depend on the python examples that we want to create.

@hongkai-dai, please let us know if you have a list of specific bindings that you'd like to see. You have more experience as python users of hydroelastics.

@amcastro-tri, I only list the items from `geometry`. Please let us know if there are items from `multibody` too (you can add to the list above or add a comment below).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #16212.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
This is almost ready for review.  One open question below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219#-:-MquN5tM5HpWrY_xwkGL:bkhh7no)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

___
*[bindings/pydrake/multibody/test/plant_test.py, line 2246 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquNANn7PP4g42AlSAU:-MquNANn7PP4g42AlSAV:b5nrvws) ([raw file](https://github.com/robotlocomotion/drake/blob/5847a802299fd26b0956b917b23a376dd72d8723/bindings/pydrake/multibody/test/plant_test.py#L2246)):*
> ```Python
>             dut.tri_mesh_W().centroid()
>         else:
>             # XXX This is dead code (dead branch).
> ```

@DamrongGuoy how to I set up a test case such that I get out a polygon representation instead of triangle?  See about for how `_sanity_check_contact_surface` is invoked.

Feel free to push a patch into this PR, if that's easiest.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 2249 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquNPpO1drngoSMuKC9:-MquNPpPBG59vL1nnYog:b-d4b0yr) ([raw file](https://github.com/robotlocomotion/drake/blob/5847a802299fd26b0956b917b23a376dd72d8723/bindings/pydrake/multibody/test/plant_test.py#L2249)):*
> ```Python
>             self.assertTrue(False)
>             dut.poly_mesh_W().centroid()
>         if dut.HasGradE_M():
> ```

@DamrongGuoy how to I set up a test case such that I get out a `GradE_M`?

Feel free to push a patch into this PR, if that's easiest.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @DamrongGuoy and @jwnimmer-tri)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 2246 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquNANn7PP4g42AlSAU:-Mquj3jI6zTMkWCHP4_d:b55yjdm) ([raw file](https://github.com/robotlocomotion/drake/blob/5847a802299fd26b0956b917b23a376dd72d8723/bindings/pydrake/multibody/test/plant_test.py#L2246)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@DamrongGuoy how to I set up a test case such that I get out a polygon representation instead of triangle?  See about for how `_sanity_check_contact_surface` is invoked.

Feel free to push a patch into this PR, if that's easiest.
</blockquote></details>

I'm new to python.  I'll have to fill in the details later.  In principle, if we create a continuous system, we'll get `dut.is_triangle()` true, and if we create a discrete system, we'll get `dut.is_triangle()` false, i.e., get the polygons.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 2249 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquNPpO1drngoSMuKC9:-Mquj_lyAmEjyWbcvn1_:b-kcgyvm) ([raw file](https://github.com/robotlocomotion/drake/blob/5847a802299fd26b0956b917b23a376dd72d8723/bindings/pydrake/multibody/test/plant_test.py#L2249)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@DamrongGuoy how to I set up a test case such that I get out a `GradE_M`?

Feel free to push a patch into this PR, if that's easiest.
</blockquote></details>

By switching the geometry ids, one call gives `GradE_M`, and another call gives `GradE_N`.  In any case, the geometry with `drake:soft_hydroelastic` in SDF is the one that will give the `GradE_*`.   I believe M is associated with the smaller id.

Unfortunately the setup is from a fixed SDF file (hydroelastic.sdf).  I would guess we can create another sdf file to switch the order of the rigid sphere and the compliant(soft) sphere? I really don't have a good solution right now.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @DamrongGuoy and @jwnimmer-tri)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 2246 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquNANn7PP4g42AlSAU:-Mquphsr5UfEc4tGNZHH:b-6xlimm) ([raw file](https://github.com/robotlocomotion/drake/blob/5847a802299fd26b0956b917b23a376dd72d8723/bindings/pydrake/multibody/test/plant_test.py#L2246)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'm new to python.  I'll have to fill in the details later.  In principle, if we create a continuous system, we'll get `dut.is_triangle()` true, and if we create a discrete system, we'll get `dut.is_triangle()` false, i.e., get the polygons.
</blockquote></details>

That's probably enough for me to figure it out.  I'll give it a try.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 2249 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquNPpO1drngoSMuKC9:-Mqupqv80SG-ltYJfKuw:b-6xlimm) ([raw file](https://github.com/robotlocomotion/drake/blob/5847a802299fd26b0956b917b23a376dd72d8723/bindings/pydrake/multibody/test/plant_test.py#L2249)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

By switching the geometry ids, one call gives `GradE_M`, and another call gives `GradE_N`.  In any case, the geometry with `drake:soft_hydroelastic` in SDF is the one that will give the `GradE_*`.   I believe M is associated with the smaller id.

Unfortunately the setup is from a fixed SDF file (hydroelastic.sdf).  I would guess we can create another sdf file to switch the order of the rigid sphere and the compliant(soft) sphere? I really don't have a good solution right now.
</blockquote></details>

That's probably enough for me to figure it out.  I'll give it a try.

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy for feature review of the changes in `//geometry/...`, please.

+@rpoyner-tri for platform review per schedule, including sole review of the changes in `//bindings/...` please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: with a perhaps-longshot request for better python doc

> Reviewed 2 of 3 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219#-:-MquyApC8mkQaqmI6_4R:b-qyz93k)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/geometry_py_scene_graph.cc, line 398 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquwYjU4ygCQCmdXq_W:-MquwYjU4ygCQCmdXq_X:b9l5jlj) ([raw file](https://github.com/robotlocomotion/drake/blob/65efd04aad168c4d35ef3e84402a207e5c023adc/bindings/pydrake/geometry_py_scene_graph.cc#L398)):*
> ```
> cls_doc.ComputeContactSurfacesWithFallback.doc)
> ```
is there any practical way to adjust the doc to account for the change in signature?

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquyteQ68pSFDQBWE8u:-MquyteQ68pSFDQBWE8v:b2h2kn6) (no related file):*
Working

I'd meant to preview the new pydrake docs locally, but it slipped my mind.  Will look now.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219)* status: LGTM missing from assignee DamrongGuoy (waiting on @DamrongGuoy and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquyteQ68pSFDQBWE8u:-Mqv566h98EIS1lo_OdP:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'd meant to preview the new pydrake docs locally, but it slipped my mind.  Will look now.
</blockquote></details>

Done.

---
___
*[bindings/pydrake/geometry_py_scene_graph.cc, line 398 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16219#-MquwYjU4ygCQCmdXq_W:-MquygR61DgIwsCcWO5D:bm3owtt) ([raw file](https://github.com/robotlocomotion/drake/blob/65efd04aad168c4d35ef3e84402a207e5c023adc/bindings/pydrake/geometry_py_scene_graph.cc#L398)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> cls_doc.ComputeContactSurfacesWithFallback.doc)
> ```
is there any practical way to adjust the doc to account for the change in signature?
</blockquote></details>

Done (on the C++ header side).

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: `//geometry/...` with a minor request.

> Reviewed 1 of 3 files at r1, 2 of 6 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219#-:-MqvA8b98MBhodP4--lf:b-s4bo5b)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[geometry/proximity/polygon_surface_mesh.h, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16219#-Mqv03yO7sMqgd-USTzb:-Mqv03yO7sMqgd-USTzc:b4pu3at) ([raw file](https://github.com/robotlocomotion/drake/blob/65efd04aad168c4d35ef3e84402a207e5c023adc/geometry/proximity/polygon_surface_mesh.h#L45)):*
> ```objc
>   /** (Internal use only) Returns a copy of this, wrapped in a unique_ptr.
>   This function is only intended for use by Drake's Python bindings. */
>   std::unique_ptr<SurfacePolygon> copy_to_unique() const;
> ```

I understand the fact that SurfacePolygon is `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN` pushes us into this `copy_to_unique()`.

Could we have a TODO to remove `copy_to_unique()` if we decide to make it copy-constructible in the future?

We might want to consider `DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN` in the future (and move the private constructor to become public).  On the other hand, the `const` and `const &` of the members index_ and mesh_face_data_ will probably need to change.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),DamrongGuoy (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[geometry/proximity/polygon_surface_mesh.h, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16219#-Mqv03yO7sMqgd-USTzb:-MqvEW_v2ZoYwyRA5XmV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65efd04aad168c4d35ef3e84402a207e5c023adc/geometry/proximity/polygon_surface_mesh.h#L45)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I understand the fact that SurfacePolygon is `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN` pushes us into this `copy_to_unique()`.

Could we have a TODO to remove `copy_to_unique()` if we decide to make it copy-constructible in the future?

We might want to consider `DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN` in the future (and move the private constructor to become public).  On the other hand, the `const` and `const &` of the members index_ and mesh_face_data_ will probably need to change.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16219)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),DamrongGuoy (waiting on @jwnimmer-tri)

**Pull request merged**
