### PR TITLE
Turn on -Werror=non-virtual-dtor.

### PR DESCRIPTION
**Pull request by david-german-tri**
We lost quite a few hours on Tuesday to a delete-slicing memory leak. Let's not do that again.

@soonho-tri for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5375)

### CODE REVIEW

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5375#-:-KeEakQTPQEu6ThsJaKm:bnfp4nl)*

**Comment by soonho-tri** [comment]
@hongkai-dai , please note that we added virtual destructors to `solvers/test/optimization_examples.h` file.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5375#-:-KeEalMhLiWkUSNNZld3:bhzg0ef)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5375#-KeEb8Fp78l1_2hxGAMY:-KeEb8Fp78l1_2hxGAMZ:b-wpkrwf) ([raw file](https://github.com/robotlocomotion/drake/blob/2622f53b725f49ffc6d841371f26baf37bfe1467/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L40)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(DirectTrajectoryOptimization)
> 
>   virtual ~DirectTrajectoryOptimization() {}
> ```

In derived classes, prefer `override` to `virtual`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5375#-:-KeEbG4-tcLUtPSyXf8w:bcpz082)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5375#-KeEb8Fp78l1_2hxGAMY:-KeEbSg6T7dyesutyqOS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2622f53b725f49ffc6d841371f26baf37bfe1467/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In derived classes, prefer `override` to `virtual`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5375)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5375)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5375)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5375)*

**Pull request merged**
