### PR TITLE
System identification wrapper

### PR DESCRIPTION
**Pull request by ggould-tri**
Creates a single convenience wrapper for system identification:
 * Does the needful to destructure and restructure TrigPolys.
 * Combines lumping, extraction, estimation, and rewriting in one interface.
 * Adds end-to-end test coverage of the above; bugfixes for issues uncovered by the same.
 * Improved serialization readability.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2937)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@sammy-tri feature review since he was in the review for the first parts of system ID.
+@david-german-tri draws the short straw as on-call platform reviewer.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-:-KNbvPZ_yRvGrCJrjPof:-1898180467)*

**Comment by sammy-tri** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/system_identification.cpp, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNc5m-_f77AXv8hwetG:-KNc5m-aPGdTs2Zo8v-C:1657647828) ([raw file](https://github.com/robotlocomotion/drake/blob/11667b246a8583dbc73a602f8df630ef0e1755fc/drake/solvers/system_identification.cpp#L5)):*
> ```cpp
> #include <algorithm>
> #include <cmath>
> #include <iostream>  // For LUMPED_SYSTEM_IDENTIFICATION_VERBOSE below.
> ```

BTW, thank you for commenting on deliberate usage of iostream so I didn't have to hunt it down.  :)

---

*[drake/solvers/system_identification.cpp, line 354 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNc79taALNyaDpKSSK2:-KNc79tbumnhsDTHA6l7:842411160) ([raw file](https://github.com/robotlocomotion/drake/blob/11667b246a8583dbc73a602f8df630ef0e1755fc/drake/solvers/system_identification.cpp#L354)):*
> ```cpp
>     polys.push_back(trigpoly.getPolynomial());
>     for (const auto& k_v_pair : trigpoly.getSinCosMap()) {
>       original_sin_cos_map[k_v_pair.first] = k_v_pair.second;
> ```

Is it OK (or even possible?) for this line to possibly replace an existing mapping if a variable appears in multiple trigpolys?

---

*[drake/util/TrigPoly.h, line 215 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNc4nRQS-Mw9Xiq00Ki:-KNc4nRQS-Mw9Xiq00Kj:803341059) ([raw file](https://github.com/robotlocomotion/drake/blob/11667b246a8583dbc73a602f8df630ef0e1755fc/drake/util/TrigPoly.h#L215)):*
> ```objc
>     std::set<VarType> vars = poly.getVariables();
>     for (const auto& sin_cos_item : sin_cos_map) {
>       vars.insert(sin_cos_item.first);
> ```

BTW, it seems strange to me that sin_cos_item.first wouldn't already be in vars...   What would it mean to have a mapping entry for a variable not in the Polynomial?  (I might be missing something here).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937)*

**Comment by ggould-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/system_identification.cpp, line 354 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNc79taALNyaDpKSSK2:-KNcF0Nwz3pbglkBzz-S:-719267080) ([raw file](https://github.com/robotlocomotion/drake/blob/11667b246a8583dbc73a602f8df630ef0e1755fc/drake/solvers/system_identification.cpp#L354)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> If multiple trigpolys have `sin_cos_map`s that disagree, we are well and truly screwed.  Which I suppose means I should assert or comment that fact.  Change to follow.
</details>
Updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-:-KNcH8BmQvvtnPaLboLC:1417088721)*

**Comment by david-german-tri** [comment]
I will get to this today, but it might be a couple of hours.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-:-KNcWpy4RHhQ03fSTp9P:2121988417)*

**Comment by david-german-tri** [comment]
I'm very glad I had the opportunity to read this!  It's nifty stuff, well executed.

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[drake/solvers/system_identification.cpp, line 341 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd7EzdeZPzMFOavfK8:-KNd7EzdeZPzMFOavfK9:-1641091007) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/system_identification.cpp#L341)):*
> ```cpp
>   // Tracing this method is a very useful way to debug otherwise-obscure
>   // system identification problems, so use a custom debug output idiom.
>   // This is a hack until #1895 is resolved.
> ```

BTW, I will be super happy when #1895 is resolved.

---

*[drake/solvers/system_identification.cpp, line 349 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd7QTFmpa1rAtHh18N:-KNd7QTFmpa1rAtHh18O:-21962533) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/system_identification.cpp#L349)):*
> ```cpp
>   TrigPolyd::SinCosMap original_sin_cos_map;
>   std::vector<Polynomiald> polys;
>   for (int i = 0; i < trigpolys.rows(); i++) {
> ```

BTW, couldn't this be a range-based for loop?

---

*[drake/solvers/system_identification.cpp, line 408 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNdDpN0XxQuQhxkW9ZM:-KNdDpN0XxQuQhxkW9ZN:1954638241) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/system_identification.cpp#L408)):*
> ```cpp
>   std::vector<PartialEvalType> augmented_values = active_var_values;
>   for (auto& partial_eval : augmented_values) {
>     for (const auto& k_v_pair : partial_eval) {
> ```

BTW, consider giving names and types to the halves of this pair to improve readability:

```
const Foo& foo = k_v_pair.first
...
```

---

*[drake/solvers/system_identification.cpp, line 409 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNdDhDmWZYEtXoxCUMx:-KNdDhDmWZYEtXoxCUMy:-1115665417) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/system_identification.cpp#L409)):*
> ```cpp
>   for (auto& partial_eval : augmented_values) {
>     for (const auto& k_v_pair : partial_eval) {
>       if (original_sin_cos_map.find(k_v_pair.first) !=
> ```

BTW, why not use that nice `count` trick you used elsewhere here as well?

---

*[drake/solvers/system_identification.cpp, line 426 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNdCVd350zuPQAK9d1O:-KNdCVd350zuPQAK9d1P:1954638241) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/system_identification.cpp#L426)):*
> ```cpp
>   std::tie(result.lumped_parameter_values, result.rms_error) =
>       EstimateParameters(polys_as_eigen, augmented_values);
>   for (const auto& k_v_pair : result.lumped_parameter_values) {
> ```

BTW, consider giving names and types to the halves of this pair to improve readability:

```
const Foo& foo = k_v_pair.first
...
```

---

*[drake/solvers/system_identification.h, line 210 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNcmojJwHc5N_-aLY3j:-KNcmojJwHc5N_-aLY3k:-1669210507) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/system_identification.h#L210)):*
> ```objc
>    * given) and the active values (those with values given).
>    *
>    * Currently only the second return (the parameter values) is used; the
> ```

BTW, I am inclined to think this sentence is not useful - it's practically self-expiring.

---

*[drake/solvers/test/system_identification_test.cpp, line 384 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd8NlsVJXBb5MuyR6l:-KNd8NlsVJXBb5MuyR6m:1178869609) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/test/system_identification_test.cpp#L384)):*
> ```cpp
>   const TrigPolyd tau(Polynomiald("tau"));  //< torque
> 
>   Eigen::Matrix<TrigPolyd, 2, 2> H;
> ```

Please, comments for those uninitiated in Single Letter Matrix Names.

---

*[drake/solvers/test/system_identification_test.cpp, line 405 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd8eaGsa3qrX0Fo5GP:-KNd8eaGsa3qrX0Fo5GQ:47778848) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/test/system_identification_test.cpp#L405)):*
> ```cpp
> 
>   // Create convenience variables for our q/qdot/u values.  Convenience vars
>   // have an underscore prefix for slightly easier understandability.
> ```

As @sherm1 recently reminded us, this violates the language spec.

---

*[drake/solvers/test/system_identification_test.cpp, line 422 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNdBhjDY4TxxpVNTUJc:-KNdBhjE4s614OxySzIR:-2047618830) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/test/system_identification_test.cpp#L422)):*
> ```cpp
>   const double kPi2 = kPi / 2;
> 
>   const std::vector<typename SID::PartialEvalType> pendula_data = {
> ```

Could you add as a comment the actual values of m, g, and l that give rise to this data?

---

*[drake/solvers/test/system_identification_test.cpp, line 464 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd9M6PnQZOE5Y8dZWW:-KNd9M6PnQZOE5Y8dZWX:-1142877441) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/test/system_identification_test.cpp#L464)):*
> ```cpp
>   Polynomiald mll1 = (m1 * l1 * l1).getPolynomial();
>   Polynomiald mll2 = (m2 * l2 * l2).getPolynomial();
>   Polynomiald::VarType mgl1_var = result.lumped_parameters.at(mgl1);
> ```

Is it implicitly verified somewhere that these are the only elements of lumped_parameters?

---

*[drake/util/Polynomial.h, line 444 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd4OptKUrmZCP8yVUd:-KNd4OptKUrmZCP8yVUe:296501478) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/util/Polynomial.h#L444)):*
> ```objc
>   //@{
>   /** Variable name/ID conversion facility. */
>   static bool isValidVariableName(const std::string name);
> ```

Now that these are public, should they have test coverage?

---

*[drake/util/test/testTrigPoly.cpp, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd4uChidfuBDS0oNfe:-KNd4uChidfuBDS0oNff:749209647) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/util/test/testTrigPoly.cpp#L23)):*
> ```cpp
>   std::stringstream test_stream;
>   test_stream << dut;
>   EXPECT_TRUE(test_stream.str().find(expect) != std::string::npos);
> ```

This seems like a pretty substantial relaxation in the test coverage - for instance, extra coefficients that previously would have caused failures may not anymore.  Did you consider writing a small lexer instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-:-KNdE5-bNp-VCZ99zmXw:845146798)*

**Comment by ggould-tri** [comment]
Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/system_identification.cpp, line 341 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd7EzdeZPzMFOavfK8:-KNgFvZoEkpZ1qMDDhNT:-1542441169) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/system_identification.cpp#L341)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, I will be super happy when #1895 is resolved.
</details>
That's my next task -- I hate this macro and want it to die.  I just have to work out the CMakeLists magic.

---

*[drake/solvers/test/system_identification_test.cpp, line 384 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd8NlsVJXBb5MuyR6l:-KNgGJk4PBzmjDsjPdH6:996600926) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/test/system_identification_test.cpp#L384)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please, comments for those uninitiated in Single Letter Matrix Names.
</details>
I thought I had been clear enough with the comment referring to the previous method.  But -- if it confuses, it is confusing.  Clarifying.

---

*[drake/solvers/test/system_identification_test.cpp, line 405 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd8eaGsa3qrX0Fo5GP:-KNgHIxmg1Y1YOoIxCMl:-816975625) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/test/system_identification_test.cpp#L405)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> As @sherm1 recently reminded us, this violates the language spec.
</details>
Holy heck, so it does.  I haven't hit that bit of the standard in seventeen years.  Fixing.

---

*[drake/solvers/test/system_identification_test.cpp, line 422 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNdBhjDY4TxxpVNTUJc:-KNgI9ZszY4Nl5AmxWns:833833190) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/test/system_identification_test.cpp#L422)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Could you add as a comment the actual values of m, g, and l that give rise to this data?
</details>
kG is defined four lines above.  I will clarify the comment at the beginning of the function, however, to include the other values.

---

*[drake/solvers/test/system_identification_test.cpp, line 464 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd9M6PnQZOE5Y8dZWW:-KNgIg-eqGJ5Tz0rz7QZ:-550730761) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/test/system_identification_test.cpp#L464)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Is it implicitly verified somewhere that these are the only elements of lumped_parameters?
</details>
It never hurts to make it explicit.  Doing so.

---

*[drake/util/Polynomial.h, line 444 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd4OptKUrmZCP8yVUd:-KNgIy6BO_HV8AEJHP2p:1635548271) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/util/Polynomial.h#L444)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Now that these are public, should they have test coverage?
</details>
`PolynomialTest.VariableIdGeneration` in `testPolynomial.cpp` is already testing the ID logic through the existing constructor and serializer interface.

---

*[drake/util/test/testTrigPoly.cpp, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd4uChidfuBDS0oNfe:-KNgJH4Pmm_2xEDpiVeG:-1333879635) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/util/test/testTrigPoly.cpp#L23)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This seems like a pretty substantial relaxation in the test coverage - for instance, extra coefficients that previously would have caused failures may not anymore.  Did you consider writing a small lexer instead?
</details>
I definitely did not consider writing a lexer :)  You're right about the coefficients, though.

I'm not inclined to write detailed test coverage for a serialization routine, which is usable only for human readability and no operational code -- particularly in the absence of the gmock features that might make it easier.

I've tightened it up a bit with a `FirstWord` assertion, so we can still do exact matches on the polynomial part of the serialization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/system_identification_test.cpp, line 464 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd9M6PnQZOE5Y8dZWW:-KNhGsQon8qfwXdcf0wu:-2054901920) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/solvers/test/system_identification_test.cpp#L464)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> It never hurts to make it explicit.  Doing so.
</details>
LGTM.  BTW, `4u` would also work here.

---

*[drake/util/test/testTrigPoly.cpp, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-KNd4uChidfuBDS0oNfe:-KNhH8yEaSMdG-S36IrR:561896330) ([raw file](https://github.com/robotlocomotion/drake/blob/410d8f2aaa4c6986c46abe63e436b90fdff599d7/drake/util/test/testTrigPoly.cpp#L23)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> I definitely did not consider writing a lexer :)  You're right about the coefficients, though.
> 
> I'm not inclined to write detailed test coverage for a serialization routine, which is usable only for human readability and no operational code -- particularly in the absence of the gmock features that might make it easier.
> 
> I've tightened it up a bit with a `FirstWord` assertion, so we can still do exact matches on the polynomial part of the serialization.
</details>
OK.  I think lexing it would be clearer (and not very much code, using `#include <regex>`), but I agree the first-word hack solves the coverage problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-:-KNhI3udUSnThhqVxSzd:1417088721)*

**Comment by mwoehlke-kitware** [comment]
Broke CI?

https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-continuous-matlab-open-source/281
https://drake-cdash.csail.mit.edu/testDetails.php?test=1653322&build=61680

**Comment by ggould-tri** [comment]
Failure looks to be unrelated to this code and to have gone away after the next commit ( https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-continuous-matlab-open-source/282/ ).  Cosmic rays?

---

Review status: 5 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-:-KNhyOwX2-NoHpVyWbeJ:-211218908)*

**Comment by mwoehlke-kitware** [comment]
> Cosmic rays?

Maybe...? :smile:

**Comment by liangfok** [comment]
FTR it's happened before: https://github.com/RobotLocomotion/drake/pull/2171#issuecomment-220471404

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2937#-:-KNhzmygWu3b7amRW1MX:-234565501)*

**Pull request merged**
