### PR TITLE
Install libbot, part I

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6340)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
Reviewed 8 of 10 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/bot2-core-lcmtypes.cps, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgEcXXyn-t935EE6N4:-KmgEcXZvTabo1qI-C07:b-z8ad0e) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/bot2-core-lcmtypes.cps#L15)):*
> ```delphi
>   "Components": {
>     "lcmtypes_bot2-core": {
>       "Type": "archive",
> ```

How come not a `dylib`?

---

*[tools/bot_core_lcmtypes.BUILD, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgFJTxrra-AKUHtJkj:-KmgFJTyGmZS57jBwGlZ:b-gdp8xy) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/bot_core_lcmtypes.BUILD#L13)):*
> ```
> load(
>     "@drake//tools:lcm.bzl",
>     "lcm_c_library",
> ```

BTW, while it would be a more invasive change, I wonder if there is a different way to do this that would either retain symmetry with Bazel's rule names, or not have partial symmetry.

---

*[tools/lcm.bzl, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgGI7ygFkM_cJAq5Io:-KmgGI80zfPyK8LT9HqW:bl9yoer) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/lcm.bzl#L47)):*
> ```Python
>     (extension in [".h", ".hpp", ".py", ".java"]) or fail(extension)
>     if extension == ".py":
>         outs.append(dirname + lcm_package + "/__init__.py")
> ```

BTW, it is maybe a little confusing that this might return a `struct` or a `list` depending on the `extension`

---

*[tools/lcm.bzl, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgH8BTCvgZPE7IwaRT:-KmgH8BUi-sUZR7xzOjI:b-wqp82f) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/lcm.bzl#L73)):*
> ```Python
>     if ctx.attr.language == "c":
>         arguments = ["--c", "--c-cpath=" + outpath, "--c-hpath=" + outpath]
>     elif ctx.attr.language == "cc":
> ```

BTW, since we're poking around here, "cc" isn't a language name... should probably be one of "cxx", "cpp" or "c++" ("cpp" being consistent with LCM's own options...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 2 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[tools/libbot.BUILD, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgMtNIpRzuhVe23SWl:-KmgMtNKMsCmxs8SPO3q:b-1k8zar) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.BUILD#L13)):*
> ```
> 
> BOT_CORE_PUBLIC_HDRS = [
>     "bot2-core/src/bot_core/bot_core.h",
> ```

Why not `glob`?

---

*[tools/libbot.BUILD, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgMwtKp726KiE68D1Y:-KmgMwtMD53kVyqDH7_A:b-1k8zar) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.BUILD#L44)):*
> ```
>     name = "bot2-core",
>     srcs = [
>         "bot2-core/src/bot_core/camtrans.c",
> ```

Why not `glob`?

---

*[tools/libbot.BUILD, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgNCAfEXQXIvYa-fk6:-KmgNCAgxypoHkxNAxsS:b9f8gkv) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.BUILD#L82)):*
> ```
>     name = "lcmspy_plugins_bot2",
>     srcs = [
>         "bot2-core/java/src/bot2_spy/ImagePlugin.java",
> ```

What was wrong with the `glob`?

---

*[tools/libbot.BUILD, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgOBMiqztTIKWBI1Lq:-KmgOBMlsffDLmPRFJ2Y:b42e6h6) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.BUILD#L195)):*
> ```
>     name = "bot-lcm-who",
>     srcs = [
>         "bot2-lcm-utils/src/who/lcm-who.c",
> ```

I am sensing a pattern...

---

*[tools/libbot.cps, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgOvvlMocmGPqmb8jd:-KmgOvvlMocmGPqmb8je:b-5g0s3v) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.cps#L10)):*
> ```delphi
>     "LGPL-3.0+",
>     "MIT",
>     "Radford-M-Neal"
> ```

What about `LGPL+Vincent-Roca`?

This mess might be a good time to use instead `Default-License`, and per-component `License` as needed... (In particular, I believe the bizarre licensing only applies to `bot-lcm-tunnel`?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by jamiesnape** [comment]
Review status: 3 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[tools/bot2-core-lcmtypes.cps, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgEcXXyn-t935EE6N4:-KmgcMfUF3TlSQCWyCZ8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/bot2-core-lcmtypes.cps#L15)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

How come not a `dylib`?
</blockquote></details>

Done.

---

*[tools/libbot.BUILD, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgMtNIpRzuhVe23SWl:-KmgcZc6hx9G6bhyMy1r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.BUILD#L13)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Why not `glob`?
</blockquote></details>

Done.

---

*[tools/libbot.BUILD, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgMwtKp726KiE68D1Y:-KmgcYRAV7dfUs8wDuuq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.BUILD#L44)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Why not `glob`?
</blockquote></details>

Done.

---

*[tools/libbot.BUILD, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgNCAfEXQXIvYa-fk6:-KmgcXidniEPrdQ1LfGB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.BUILD#L82)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

What was wrong with the `glob`?
</blockquote></details>

Done.

---

*[tools/libbot.BUILD, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgOBMiqztTIKWBI1Lq:-Kmgc_sbbVogTKfxcu3z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.BUILD#L195)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I am sensing a pattern...
</blockquote></details>

Done.

---

*[tools/libbot.cps, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgOvvlMocmGPqmb8jd:-KmgcdFCEEvfFywsotmb:bp7fkf1) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.cps#L10)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

What about `LGPL+Vincent-Roca`?

This mess might be a good time to use instead `Default-License`, and per-component `License` as needed... (In particular, I believe the bizarre licensing only applies to `bot-lcm-tunnel`?)
</blockquote></details>

Added Vincent Roca. Since we are not using the licenses for anything, I will pass on the rest for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 6 of 7 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/bot2-core-lcmtypes.cps, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgEcXXyn-t935EE6N4:-KmggH6ZKCQAVqxFrN3m:b-gkmxl) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/bot2-core-lcmtypes.cps#L15)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:tada: :smile:

---

*[tools/libbot.BUILD, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgOBMiqztTIKWBI1Lq:-KmggzRJ_4jI_GSTd0hD:b3ic3vu) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.BUILD#L195)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks... it is rather easier to read this way.

---

*[tools/libbot.BUILD, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-Kmgh71C-2NhmTTuSXQr:-Kmgh71Dj2IguLTDoJn5:b-4gpvps) ([raw file](https://github.com/robotlocomotion/drake/blob/45cb475140f2ebad4978dc8c333e53a29f38521e/tools/libbot.BUILD#L142)):*
> ```
>     name = "install",
>     hdrs = BOT_CORE_PUBLIC_HDRS,
>     doc_dest = "share/doc/" + CMAKE_PACKAGE,
> ```

BTW, at some point, I want to try to figure out how to make this more automatic... possibly by adding a placeholder string that gets replaced to the defaults.

---

*[tools/libbot.cps, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgOvvlMocmGPqmb8jd:-KmghSpaRYbUUXBwwEBf:b-i51d3r) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.cps#L10)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Added Vincent Roca. Since we are not using the licenses for anything, I will pass on the rest for now.
</blockquote></details>

Shouldn't it be `LGPL-<ver>+Vincent-Roca`, as it is LGPL with additional stipulations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by jamiesnape** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.cps, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgOvvlMocmGPqmb8jd:-Kmgmzr1VbF-QGbYLHiK:b73l4g4) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.cps#L10)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Shouldn't it be `LGPL-<ver>+Vincent-Roca`, as it is LGPL with additional stipulations?
</blockquote></details>

SPDX only says it must be unique and only use alphanumeric, hyphen, or period. You could argue `LGPL-<ver>+ WITH Vincent-Roca`, although that is usually used for exceptions rather than additions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:, though I am still on the fence re: the license stuff...

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.cps, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgOvvlMocmGPqmb8jd:-KmgpExEzmtW7lJFt7dB:b-ebohhy) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.cps#L10)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

SPDX only says it must be unique and only use alphanumeric, hyphen, or period. You could argue `LGPL-<ver>+ WITH Vincent-Roca`, although that is usually used for exceptions rather than additions.
</blockquote></details>

Er... right, that's what I meant; was forgetting that the operator is `WITH`, not `+`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-:-Kmgp_eHN2USSLasB0-A:brrdx3f)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review (or whoever happens to be available).

**Comment by jamiesnape** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.cps, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmgOvvlMocmGPqmb8jd:-KmgsK58k4QqJTftbpkk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3e985f689699719e090e6c9839c842fbdef659b/tools/libbot.cps#L10)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Er... right, that's what I meant; was forgetting that the operator is `WITH`, not `+`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-debug please

---

Review status: 7 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-:-KmjWhXsXHLIhs1H9B5U:b-9lzruo)*

**Comment by jwnimmer-tri** [comment]
-@soonho-tri +@jwnimmer-tri stealing platform.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 10 files at r1, 4 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lcm.bzl, line 156 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlEwN9j9ScPBy_P-Qa:-KmlEwNATI1fe1q57LYr:bkms79w) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/lcm.bzl#L156)):*
> ```Python
>         lcm_package,
>         lcm_structs=None,
>         **kwargs):
> ```

Compared to `lcm_cc_library`, this lacks `linkstatic = 1`.  That should either be made consistent, or commented as to why the distinction.

---

*[tools/libbot.BUILD, line 145 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlDFSF3UK3KqyYaPxs:-KmlDFSF3UK3KqyYaPxt:b5692qu) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/libbot.BUILD#L145)):*
> ```
>     hdr_dest = "include/" + CMAKE_PACKAGE,
>     hdr_strip_prefix = ["bot2-core/src"],
>     license_docs = ["LICENSE"],
> ```

I think we also want `bot2-lcm-utils/src/tunnel/ldpc/README` so we have `Radford-M-Neal` notice present?

Are there other files missing for `Vincent-Roca` specifically?

The `LICENSE` here is just `LGPL-3.0+`; do we also want to install the GPL and MIT documents for some kind of clarity or hint?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-:-KmlG7BLOVtItujBEyy0:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lcm.bzl, line 156 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlEwN9j9ScPBy_P-Qa:-KmlGPzcnqOKosEwuEVU:bkm7i0w) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/lcm.bzl#L156)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Compared to `lcm_cc_library`, this lacks `linkstatic = 1`.  That should either be made consistent, or commented as to why the distinction.
</blockquote></details>

Probably should remove the `linkstatic` for `lcm_cc_library` as the C++ bindings are always header only.

---

*[tools/libbot.BUILD, line 145 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlDFSF3UK3KqyYaPxs:-KmlG_-BzfcsJlF-VHQF:bczv5u1) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/libbot.BUILD#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think we also want `bot2-lcm-utils/src/tunnel/ldpc/README` so we have `Radford-M-Neal` notice present?

Are there other files missing for `Vincent-Roca` specifically?

The `LICENSE` here is just `LGPL-3.0+`; do we also want to install the GPL and MIT documents for some kind of clarity or hint?
</blockquote></details>

We do. I will add something for all those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by jwnimmer-tri** [comment]
*[tools/lcm.bzl, line 156 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlEwN9j9ScPBy_P-Qa:-KmlGyTyU_PF_bq1Pz1W:beea1tp) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/lcm.bzl#L156)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Probably should remove the `linkstatic` for `lcm_cc_library` as the C++ bindings are always header only.
</blockquote></details>

I'm not 100% confidence, but I _think_ Bazel produces an empty .a or empty .so even for header-only libraries.  If so, probably good to suppress the .so form at least, so tests don't end up with confusing dependency on it?  I guess no big deal either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lcm.bzl, line 156 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlEwN9j9ScPBy_P-Qa:-KmlGVd26BJZSuOClb1z:b-re0dk6) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/lcm.bzl#L156)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Probably should remove the `linkstatic` for `lcm_cc_library` as the C++ bindings are always header only.
</blockquote></details>

What @jamiesnape said... though, for some reason, it seems that Bazel insists on producing a library anyway... (I wonder however if that's an artifact of `linkstatic=1`, i.e. the `.a` it produces is "really" liblcm?)

---

*[tools/libbot.BUILD, line 145 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlDFSF3UK3KqyYaPxs:-KmlHCcWep_XbwX61Y8Q:b-sgmnk0) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/libbot.BUILD#L145)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We do. I will add something for all those.
</blockquote></details>

I found `Vincent-Roca` when I went looking for `Radford-M-Neal`; they're in the same file. Unfortunately, said file is not really formatted for distribution. (Is it worth writing a short file with explanatory/context text?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lcm.bzl, line 156 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlEwN9j9ScPBy_P-Qa:-KmlHXUj8XH_bKhNnKiQ:bfd7tih) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/lcm.bzl#L156)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

What @jamiesnape said... though, for some reason, it seems that Bazel insists on producing a library anyway... (I wonder however if that's an artifact of `linkstatic=1`, i.e. the `.a` it produces is "really" liblcm?)
</blockquote></details>

For Mac only, I think. If you iterate though the outputs, it is not added to the Bazel target, so it is never linked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lcm.bzl, line 156 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlEwN9j9ScPBy_P-Qa:-KmlI7sK8mnnFEKXjL9j:bmi1nes) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/lcm.bzl#L156)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

For Mac only, I think. If you iterate though the outputs, it is not added to the Bazel target, so it is never linked.
</blockquote></details>

(hence, it is also not linked into `bazel-bin` as far as I can tell)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by jamiesnape** [comment]
Review status: 4 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lcm.bzl, line 156 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlEwN9j9ScPBy_P-Qa:-KmlTHy0rP-k7exeG7dg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/lcm.bzl#L156)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

(hence, it is also not linked into `bazel-bin` as far as I can tell)
</blockquote></details>

Done.

---

*[tools/libbot.BUILD, line 145 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlDFSF3UK3KqyYaPxs:-KmlTGwx70xXsBqJSP11:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8b39b72633a1454099544342c6052b2fb5ce90d5/tools/libbot.BUILD#L145)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I found `Vincent-Roca` when I went looking for `Radford-M-Neal`; they're in the same file. Unfortunately, said file is not really formatted for distribution. (Is it worth writing a short file with explanatory/context text?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 6 of 7 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/libbot.BUILD, line 147 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-KmlYnNUNbutzHqOsUyi:-KmlYnNVvkC0qOcZJgX8:b-qta5eg) ([raw file](https://github.com/robotlocomotion/drake/blob/7ea81b54b0d402654cd2d669f7a5da68347e6c17/tools/libbot.BUILD#L147)):*
> ```
>     license_docs = [
>         "LICENSE",
>         "@drake//tools:third_party/libbot/ldpc/LICENSE",
> ```

This clobbers the other `LICENSE`. Maybe name it `LICENSE.ldpc` or something along those lines?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340)*

**Comment by mwoehlke-kitware** [comment]
:lgtm_cancel: until `LICENSE` issue fixed

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-:-Kml_YGbQZjuuRf5b9QV:b2ily7o)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6340#-:-Kmlpc4jvB_TgbM91ALK:bnfp4nl)*

**Pull request merged**
