### PR TITLE
[bindings] Add bindings for QuaternionFloatingJoint

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18420)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@joemasterjohn for feature review
+(release notes: feature) new python bindings

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18420#-:-NIivYGNCbN7KQnpcfO0:b-v56vbi)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with one small nit.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18420#-:-NIizJBE91KnHj8pWWac:b2tjc6r)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1870 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18420#-NIiyr4lCUJOE4KKNrvr:-NIiyr4lCUJOE4KKNrvs:bu1xpz9) ([raw file](https://github.com/robotlocomotion/drake/blob/e7cc1b3f4af674b681f2c447e65f8cfe8e03332f/bindings/pydrake/multibody/test/plant_test.py#L1870)):*
> ```Python
>                     q_FM=Quaternion_[Expression]())
>                 joint.set_random_quaternion_distribution_to_uniform()
>                 joint.set_default_position(p_FM=[0, 0, 0])
> ```

nit: missing some coverage for:
- `get_default_quaternion()`
- `get_default_position()`
- `get_default_pose()`
- `set_default_quaternion()`

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18420#-:-NIkBYAz3R32hxcgrQ4F:bfvx2sg)* status: LGTM missing from assignee sherm1(platform) (waiting on @joemasterjohn and @sherm1)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri :lgtm_strong: platform, thanks! -@sherm1 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18420#-:-NIlOR9-Bz6lsDzX7Hpv:b-wtl5lb)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn (waiting on @rpoyner-tri)

**Pull request merged**
