### PR TITLE
Initial integration of ModelElementId with RigidBody.

### LINKED ISSUE #2981: Generalize ModelElementId to support models where modeling elements of different types have the same name
Currently, Drake enforces that different modeling elements like `RigidBody` and `DrakeJoint` have different names. Standards like SDF and URDF do not enforce this, however. Thus, this issue tracks the generalization of Drake's ModelElementId to support identically named modeling elements that belong to the same model and can co-exist because they are of different types.

### PR DESCRIPTION
**Pull request by liangfok**
~~I also went ahead and added the element type to `ModelElementId1`.~~ I removed the element type due to the controversy it stirred up (see comments below).

Resolves #2981.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2995)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/3206/ and is thus ready for feature review.

+@sherm1 for feature review since this includes the requested `ModelElementType` within the `ModelElementId`.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KNttc_yRyy3vn2Waz6R:1981510430)*

**Comment by sherm1** [comment]
Platform review: @liangfok, I can't tell you how much I hate this class! It seemed bad before and now I feel it has crossed the line to completely unacceptable. The new type enum is an end-around the C++ type system. I don't get what this class is for or why every model element should be sitting on a whole package of strings vaguely relating it to some complicated taxonomy of modeling pieces. Perhaps you can get this by one of the platform reviewers who was involved in the design -- I can't accept it.

---

Reviewed 1 of 7 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBody.cpp, line 26 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-KNxICWyCYDT6vKmHr21:-KNxICWyCYDT6vKmHr22:253244091) ([raw file](https://github.com/robotlocomotion/drake/blob/f56b69c09bbf8e0e5bf59f48e58d9f0528928a89/drake/systems/plants/RigidBody.cpp#L26)):*
> ```cpp
>   com = Vector3d::Zero();
>   I << drake::SquareTwistMatrix<double>::Zero();
>   model_element_id_.set_element_type(ModelElementType::kBodyElement);
> ```

This seems like a complete end-around the C++ type system. Why does a RigidBody have to say it's a body?

---

*[drake/systems/plants/RigidBody.h, line 25 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-KNxIUm0C19xqMONKNdi:-KNxIUm0C19xqMONKNdj:678074825) ([raw file](https://github.com/robotlocomotion/drake/blob/f56b69c09bbf8e0e5bf59f48e58d9f0528928a89/drake/systems/plants/RigidBody.h#L25)):*
> ```objc
>  public:
>   // TODO(liang.fok) Define a constructor tha takes a ModelElementId as an input
>   // parameter.
> ```

typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KNxIkKFreA9ZA59gxVY:1495894986)*

**Comment by liangfok** [comment]
@sherm1 - Would you be willing to continue to serve as platform reviewer if I remove enumeration `ModelElementType`? (See my comment below.)

---

Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBody.cpp, line 26 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-KNxICWyCYDT6vKmHr21:-KNxe9bjsbzxXu4WWHd7:1722998672) ([raw file](https://github.com/robotlocomotion/drake/blob/f56b69c09bbf8e0e5bf59f48e58d9f0528928a89/drake/systems/plants/RigidBody.cpp#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This seems like a complete end-around the C++ type system. Why does a RigidBody have to say it's a body?
</details>
I would be happy to remove enumeration `ModelElementType` since I'm sure it's not needed for my immediate application (multi-model support in Drake).

FTR, this was added in response to this comment thread:

https://reviewable.io/reviews/robotlocomotion/drake/2976#-KNrS1YwrMZyNBUmrCMT

Which resulted in issue #2981.

The purpose of enumeration `ModelElementType` is to enable users to distinguish between two identically-named modeling elements when executing a search.

---

*[drake/systems/plants/RigidBody.h, line 25 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-KNxIUm0C19xqMONKNdi:-KNxioW6xb1O9zk7Pg4X:-795674652) ([raw file](https://github.com/robotlocomotion/drake/blob/f56b69c09bbf8e0e5bf59f48e58d9f0528928a89/drake/systems/plants/RigidBody.h#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> typo
</details>
Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KNxiF0Z5t5DrU2BUlI6:273838612)*

**Comment by sherm1** [comment]
No, I don't understand why this should exist at all. It seems to be completely lacking all the obvious abstractions, like "model", "instance", and "element" all of which have been represented as strings instead of meaningful objects. I don't get how the string representation is even adequate. Can't models be hierarchical, e.g. a hand model might contain 5 finger models? Then a symmetric robot might instantiate two of those hand models, resulting in 10 instantiated fingers? The names of the instantiated elements would all be be unique as path names like `robot/leftarm/hand/finger1/joint3`, `robot/rightarm/hand/finger2/joint3` but no combination of name, type, model name, instantiation name, etc. would uniquely identify an element. If there is a hierarchy (or could be), then it doesn't makes sense to think of an instantiated element as belonging to a single model, unless that means "closest enclosing model". That would all be clear if the abstractions were present but I can't discern the abstractions from what appears to be an ad hoc collection of strings.

I'm imagining that there was a design discussion I missed that would explain what the underlying abstractions are, what operations they must support, and so on, but working only from the PR it looks like a bad hack and I don't think it should be added to Drake. You may have better luck with a better-informed platform reviewer, but if so I'll be sad. Adding the `model_id` earlier was a modest piece of technical debt taken on for expedience; this is maxing out the credit card.

---

Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KNyP83RzYg8BsCxXlRz:1434386624)*

**Comment by liangfok** [comment]
Yes, there was a meeting a couple weeks ago. I'll send you some notes from that meeting via e-mail, which I hope will clarify things. 

We did discuss the need to support model hierarchy and the conclusion was that introducing the `ModelElementId` would not impede and would in fact enable the development of such a hierarchy.  Basically, the `ModelElementId` enables "atomic" models (i.e., models that are not composed of other models) like fingers in your example to be created since they can be used to obtain a "view" into a portion of the `RigidBodySystem`. Users could compose these "atomic" models into more sophisticated "compound" models like the hand in your example.

---

Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KNy_pKiJhLG4FQ3iwRS:-2058309675)*

**Comment by liangfok** [comment]
Since @jwnimmer-tri was the only platform reviewer present during the design meeting that discussed the introduction of this `ModelElementId` abstraction, +@jwnimmer-tri for platform review and -@sherm1 as platform reviewer.

Thanks!!

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KO0NpgILbIcj34GSumj:-1585975781)*

**Comment by liangfok** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBody.cpp, line 26 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-KNxICWyCYDT6vKmHr21:-KO0ODMullJf1CgjWgOC:-1175080064) ([raw file](https://github.com/robotlocomotion/drake/blob/f56b69c09bbf8e0e5bf59f48e58d9f0528928a89/drake/systems/plants/RigidBody.cpp#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I would be happy to remove enumeration `ModelElementType` since I'm sure it's not needed for my immediate application (multi-model support in Drake).
> 
> FTR, this was added in response to this comment thread:
> 
> https://reviewable.io/reviews/robotlocomotion/drake/2976#-KNrS1YwrMZyNBUmrCMT
> 
> Which resulted in issue #2981.
> 
> The purpose of enumeration `ModelElementType` is to enable users to distinguish between two identically-named modeling elements when executing a search.
</details>
I removed the `ModelElementIdType` since I do not need it for my immediate application and it was not discussed in the original meeting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KO0iM22wSF5eHBfGug9:-206704113)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KO0mEyb3LRef9ltaIRY:-206704113)*

**Comment by sherm1** [comment]
Further discussion is in simulation-archive [here](https://groups.google.com/a/tri.global/forum/?hl=en#!topic/simulation-archive/DjKnc-1RqmE).

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KO2LflG0sqUnk2H_4Me:-1916226101)*

**Comment by jwnimmer-tri** [comment]
@liangfok I am still tagged to review this -- is that assignment still accurate?  I wonder if this PR has been superseded by other PRs in flight now?

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KO5T2LpzjGb7OwMLbJ6:1848068054)*

**Comment by liangfok** [comment]
Yeah, I believe this PR is superseded by #3007 and #3008. I will close this PR unless a future meeting decides that this path is indeed we want to take long-term.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2995#-:-KO5UlPVPK4gK_e5MHN5:-724737757)*

**Pull request closed without merging**
