### PR TITLE
parsing: Add support for SDFormat 1.8 model composition (redo)

### PR DESCRIPTION
**Pull request by azeey**
This a redo of #14401 but does not create a frame for each model in the parent scope of the model. There is still a frame associated with each model, but it's named `__model__` and is found inside the model instance.

---
Description from #14401:

Changes in behavior:
* Models nested via the `<include>` tag are no longer flattened, which means each included model will have its own model instance.
* `drake::multibody::Parser::AddAllModelsFromFile` now returns all added models including nested models

Note: This does not use a custom parser for URDFs via libsdformat's Interface API, and thus may incur unexpected behavior when including URDF files from SDFormat pending the full resolution of #14295.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
Assigning +@ericcousineau-tri for feature review, or delegation to another reviewer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099#-:-Mb8R2uv9Hq3lQseOac1:b-aj8vpn)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Thanks for the ping!

I compared patch resulting from #14401 and this PR's current patch.
Saw relevant changes:
- No longer add model-named frame at enclosing scope
- Mitigation code added to handle mapping from SDFormat's reference to enclosing-scope frame name to the more explicit `__model__` frame.

```sh
cd drake
# 315334b  - old pr, merged
# 1041c6c - current pr, current rev
git diff 315334b~ 315334b > /tmp/patch-old.diff
git diff $(git merge-base 1041c6c upstream/master) 1041c6c > /tmp/patch-new.diff
meld /tmp/patch-{old,new}.diff
```

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: per patch-comparison comment above; also, pending CI failures.
Also, just a minor BTW on testing code.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099#-:-MbEweHz3XAd_YTlpfT_:b-xqsafg)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @azeey)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEvclS-e6ElrC-_SNC:-MbEvclTA4Rs8mTzw_mc:baj9dyg) (no related file):*
nit CI is failing due to lint failures.

Can you fix this?

---
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 498 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEvmVl53b9vCBxShJh:-MbEvmVl53b9vCBxShJi:btarrk5) ([raw file](https://github.com/robotlocomotion/drake/blob/1041c6ca119c8d7e4b94f2183a3d856a58618d62/multibody/parsing/test/detail_sdf_parser_test.cc#L498)):*
> ```cpp
>         "Verify that static models don't need to have a canonical link");
>     PlantAndSceneGraph pair;
>     DRAKE_ASSERT_NO_THROW(pair = ParseTestString(R"""(
> ```

BTW Still not sure if I see the value of `ASSERT_NO_THROW`. If this fails, I don't really care about subsequent code running. (In fact, future steps will prolly segfault?)

Consider removing?
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 498 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEvyTcBGqVXSPF3e5_:-MbEvyTcBGqVXSPF3e5a:bh3gc08) ([raw file](https://github.com/robotlocomotion/drake/blob/1041c6ca119c8d7e4b94f2183a3d856a58618d62/multibody/parsing/test/detail_sdf_parser_test.cc#L498)):*
> ```cpp
>         "Verify that static models don't need to have a canonical link");
>     PlantAndSceneGraph pair;
>     DRAKE_ASSERT_NO_THROW(pair = ParseTestString(R"""(
> ```

BTW Consider changing `PlantAndSceneGraph` to `std::pair<...>` so you could use a structured binding.

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sammy-tri for follow-up platform review (since you reviewed the first) - thank!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099#-:-MbEwrhTCSD2u9C2k2F8:bsf1b24)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @azeey and @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @azeey, @EricCousineau-TRI, and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEx35U4XD8hiBCh671:-MbEx35U4XD8hiBCh672:b9eeybt) (no related file):*
Working: Testing in Anzu CI.

---

**Comment by azeey** [comment]
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 498 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEvmVl53b9vCBxShJh:-MbHIT798ZWMnI42b59N:b-85exgj) ([raw file](https://github.com/robotlocomotion/drake/blob/1041c6ca119c8d7e4b94f2183a3d856a58618d62/multibody/parsing/test/detail_sdf_parser_test.cc#L498)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Still not sure if I see the value of `ASSERT_NO_THROW`. If this fails, I don't really care about subsequent code running. (In fact, future steps will prolly segfault?)

Consider removing?
</blockquote></details>

I'm used to CI infrastructure where tests with segfaults end up with different names on the dashboard than the test suite name, so we prefer to assert anything that might cause a segfault. I'll remove it if that's not an issue.

**Review by azeey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEvclS-e6ElrC-_SNC:-MbHcEy61eMCX5WdmZeF:b-7kcxqz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit CI is failing due to lint failures.

Can you fix this?
</blockquote></details>

Done in https://github.com/robotlocomotion/drake/commit/a1a1064fce25a7a75900b7385176460479f61c9d

---
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 498 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEvyTcBGqVXSPF3e5_:-MbHcK931BqqJkz0x3me:b-jm6y3t) ([raw file](https://github.com/robotlocomotion/drake/blob/1041c6ca119c8d7e4b94f2183a3d856a58618d62/multibody/parsing/test/detail_sdf_parser_test.cc#L498)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Consider changing `PlantAndSceneGraph` to `std::pair<...>` so you could use a structured binding.
</blockquote></details>

Done  in https://github.com/robotlocomotion/drake/commit/a1a1064fce25a7a75900b7385176460479f61c9d
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 498 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEvmVl53b9vCBxShJh:-MbHcTI9DksPqV1D56BH:b-7kcxqz) ([raw file](https://github.com/robotlocomotion/drake/blob/1041c6ca119c8d7e4b94f2183a3d856a58618d62/multibody/parsing/test/detail_sdf_parser_test.cc#L498)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I'm used to CI infrastructure where tests with segfaults end up with different names on the dashboard than the test suite name, so we prefer to assert anything that might cause a segfault. I'll remove it if that's not an issue.
</blockquote></details>

Done in https://github.com/robotlocomotion/drake/commit/a1a1064fce25a7a75900b7385176460479f61c9d

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 498 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEvmVl53b9vCBxShJh:-MbHdYUV9rExZei9-MpK:b-3btnd5) ([raw file](https://github.com/robotlocomotion/drake/blob/1041c6ca119c8d7e4b94f2183a3d856a58618d62/multibody/parsing/test/detail_sdf_parser_test.cc#L498)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done in https://github.com/robotlocomotion/drake/commit/a1a1064fce25a7a75900b7385176460479f61c9d
</blockquote></details>

OK Thanks! I don't think I've seen it cause an issue with `bazel`'s test logging, nor the jUnit stuff (either in Drake's CDash parsing, nor in Anzu Jenkin's jUnit parsing).

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15099#-MbEx35U4XD8hiBCh671:-MbHnyE5EYYYX2ZDZVIb:b-i64tk7) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Testing in Anzu CI.
</blockquote></details>

OK Testing passed! Anzu PR 7073

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (also based on reviewing the changes from the #14401 version)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099#-:-MbIQp4xCYQ6bYRJD_Ab:b-pq66p9)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15099#-:-MbIV4IL92p1SQKgMANy:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),EricCousineau-TRI(platform) (waiting on @sammy-tri)

**Pull request merged**
