### PR TITLE
Make Drake's PR line limit rules more specific

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
~This is in PR form in order to be specific about some proposed new wording -- discussing in an issue is often nebulous.  Probably we shouldn't immediately dive into reviewable discussions though; I'll try to figure out another good channel instead to discuss, possibly this Friday or next week.~

~_Edit: As of 2017-06-22, this is under discussion for consensus by platform reviewers, before seeking further buy-in from a wider audience of developers._~

Out of the most recent 1,358 PRs (CY 2017) this proposal would have affected 8 of them:
- Copyable unique pointers (round 2) #5820 (1778)
- Param parsing for the QP controller #4754 (1875)
- Refactor MathematicalProgram::Binding #4704 (1963)
- qp controller refactoring. #4835 (2146)
- Add utility code to automotive/maliput. #4694 (2183)
- Streamlined implicit euler integrator #5938 (2707)
- API update for event processing #6050 (3266)
- Separate output ports for independent allocation and calculation #6038 (3363)

My intention behind the changes are as follows:
- Switch from SLOC to LOC.  There are no good tools to compute SLOC for diffs, and its not easy to explain the difference to contributors.  Instead, we bump the soft limit from 500 SLOC to 750 LOC.
- More explicitly exclude things that we've been implicitly forgiving to date: data files, generated code, dev, etc.  A new tool `drake/tools/prsize` automatically excludes these from its report for developer convenience.
- Instead of suggesting that oversize PRs seek pre-approval (which in practice was rarely taken to heart), we place a clear hard limit that best approximates where we should say "no".

For rationale on the new hard limit...

When the concern was "how many hours am I willing to spend", then single person opt-in to oversize made sense.  However, my belief is that oversize PRs are not receiving satisfactory review, in part due to reviewer fatigue, but mostly because work of that scale should be receiving input from more than two people (on both the feature and platform axes).  If two platform reviewers can't see a better path forward, then it's good evidence that the PR is the best we can expect and we should override the hard limit.

For the soft limit, I haven't added any specific override text -- my hope is that if reviewers are given a >750 LOC PR, they'll individually first assess whether it's likely to receive a thorough review as-is, and if not to push back with a suggestion on how to rework it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6338)

### CODE REVIEW

**Comment by edrumwri** [comment]
I'm not going to be around in person to discuss either Friday or next week, but I vote that the current rules should be relaxed into guidelines, not strengthened and a _process_- a hallmark of bureaucracy- introduced. Reviewers have already made evident their displeasure at conducting large reviews, and a smart author knows it's in his/her best interest to minimize the size of a PR.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-Kmg7xwHxuQHfhKoP0u1:bkkoiro)*

**Comment by jwnimmer-tri** [comment]
I did a historical size survey.

Going back to PR4600 (around the start of this year), we have these deciles (in github LOC size):

      0% PR4617 0 LOC
     10% PR5135 2 LOC
     20% PR4853 5 LOC
     30% PR5351 11 LOC
     40% PR5484 22 LOC
     50% PR5593 46 LOC
     60% PR5684 86 LOC
     70% PR6290 157 LOC
     80% PR4770 281 LOC
     90% PR5463 522 LOC
    100% PR5531 6201 LOC

Files with extension `obj, sdf, urdf, cls` are excluded.

The PRs that have more than 1000 LOC in github diff size are:

#5055 has 1011 LOC github diff
#5316 has 1023 LOC github diff
#6071 has 1030 LOC github diff
#6043 has 1036 LOC github diff
#5419 has 1045 LOC github diff
#4819 has 1054 LOC github diff
#6021 has 1068 LOC github diff
#4859 has 1072 LOC github diff
#4653 has 1106 LOC github diff
#6064 has 1106 LOC github diff
#5945 has 1117 LOC github diff
#5881 has 1122 LOC github diff
#6264 has 1123 LOC github diff
#5175 has 1125 LOC github diff
#6262 has 1135 LOC github diff
#5133 has 1149 LOC github diff
#4613 has 1169 LOC github diff
#5701 has 1180 LOC github diff
#5272 has 1187 LOC github diff
#4773 has 1188 LOC github diff
#6192 has 1221 LOC github diff
#5455 has 1241 LOC github diff
#5038 has 1268 LOC github diff
#4979 has 1310 LOC github diff
#4980 has 1310 LOC github diff
#5786 has 1338 LOC github diff
#6208 has 1400 LOC github diff
#4682 has 1405 LOC github diff
#5273 has 1434 LOC github diff
#5434 has 1435 LOC github diff
#4778 has 1480 LOC github diff
#5771 has 1724 LOC github diff
#5028 has 1728 LOC github diff
#4866 has 1762 LOC github diff
#5820 has 1778 LOC github diff
#4992 has 1812 LOC github diff
#4754 has 1875 LOC github diff
#4704 has 1963 LOC github diff
#5753 has 1984 LOC github diff
#4835 has 2146 LOC github diff
#4694 has 2183 LOC github diff
#5575 has 2397 LOC github diff
#5937 has 2645 LOC github diff
#5938 has 2707 LOC github diff
#5574 has 2726 LOC github diff
#5032 has 3011 LOC github diff
#6050 has 3266 LOC github diff
#6038 has 3363 LOC github diff
#4845 has 3904 LOC github diff
#5531 has 6201 LOC github diff

Note that many of these would still be less than the proposed 1000 SLOC guideline, because we have to subtract whitespace and comments for the proposed metric.

**Comment by jwnimmer-tri** [comment]
Given the above survey, I'm going to change my proposal to:
- soft 500 SLOC limit (don't count comments and whitespace) -- same as now;
- hard 1500 LOC limit (the number reported by reviewable) -- revised new rule.

**Comment by SeanCurtis-TRI** [comment]
I have several concerns about *technicalities* which become more relevant as we attempt to harden guidelines to policies. Essentially, it seems to me we want to limit the qualitative judgment involved in policy conformance. 

1) Do we have a reliable method for determining compliance (i.e., something that can determine actual SLOC -- particularly on diffs)? 
2) Does the 1500 line count include only `+` changes or is it `+` and `-`? 

Finally, my last concern is not one of metrics, but of behavior. I'm worried that an unintended consequence of the 1500 LOC limit *may* be to limit documentation -- or at the very least, decouple documentation from code (e.g., tersely documented code in one PR and full documentation in a follow-up PR). But even in that latter case, deferred documentation is documentation that is unlikely to happen.

**Comment by jwnimmer-tri** [comment]
> Do we have a reliable method for determining compliance (i.e., something that can determine actual SLOC -- particularly on diffs)?

In the thread above I'd proposed SLOC -- but the proposed text doesn't use SLOC, its all just LOC.

> Does the 1500 line count include only + changes or is it + and -?

Just `+`.  I'd hoped that was obvious, but I'm open to wording suggestions.

> Finally, my last concern is not one of metrics, but of behavior. I'm worried that an unintended consequence of the 1500 LOC limit may be to limit documentation -- or at the very least, decouple documentation from code (e.g., tersely documented code in one PR and full documentation in a follow-up PR). But even in that latter case, deferred documentation is documentation that is unlikely to happen.

Maybe?  1500 LOC leaves a lot of room for documentation though, and I think gigantic documentation is similarly difficult to review as gigantic code.

So let's look empirically: of the PRs that were over the limit in the above list, please point to some (or one) that you think would have been susceptible to this outcome.

**Comment by RussTedrake** [comment]
is there an "override" option to get around the "hard limit" for exception circumstances?

**Comment by jwnimmer-tri** [comment]
> This rule may be overridden by agreement of at least three platform reviewers.

**Comment by ggould-tri** [comment]
I am less concerned with the numbers than with the mechanism -- we have already been ineffective at enforcing the previous policy, and IMO this is not because it has the wrong number but because we are (mostly) nice people and the policy requires the reviewer to be the bad guy.

I think if it were possible a superior approach would be to have an automated system warn the author and/or apply a shame tag to oversize reviews.  This would make CI the bad guy, which it already is, rather than making reviewers step up (or, more often, grumble but decide that a long review is less unpleasant than arguing about PR factoring).

Within the context of the current system, though, this proposal is a small improvement and so I am not opposed to it; I just don't think it will help.

**Comment by jwnimmer-tri** [comment]
I would be happy to add automated tagging / enforcement of some kind as a (concurrent) prerequisite of this PR.

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFSbFsPYk6v5L4eO4E:-KnFSbFsPYk6v5L4eO4F:b-bf4iwb) ([raw file](https://github.com/robotlocomotion/drake/blob/46308855ad4b00c97666012e66e7b59b107c3523/drake/doc/developers.rst#L144)):*
> ```reStructuredText
> 
> A PR generally *should not* include more than 750 lines of code, and *must not*
> include more than 1500 lines of code, with the following exemptions:
> ```

Needs a definition of "lines of code" -- that term is ambiguous to me at least. My understanding is that you are proposing: LOC=lines of source code and comments less white space; lines added but not lines subtracted (and not a net figure balancing the two). I remain unclear about code that simply moved from one place to another -- I guess that should count and people should do their code moving as a separate PR? 

---

*[drake/doc/developers.rst, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFSUngqWtXVFP8GyK4:-KnFSUnhyfFeRSdk1SZV:b-sv0fj) ([raw file](https://github.com/robotlocomotion/drake/blob/46308855ad4b00c97666012e66e7b59b107c3523/drake/doc/developers.rst#L153)):*
> ```reStructuredText
>     do not count towards the line limit.
> 
>   - This rule may be overridden by agreement of at least three platform
> ```

Agreement of two platform reviewers should be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by jwnimmer-tri** [comment]
>> Does the 1500 line count include only + changes or is it + and -?
 
> Just +.  I'd hoped that was obvious, but I'm open to wording suggestions.

@SeanCurtis-TRI I've posted new working.  PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFSbFsPYk6v5L4eO4E:-KnFVVBfHm6PV9ZCHk7q:b-4bks8p) ([raw file](https://github.com/robotlocomotion/drake/blob/46308855ad4b00c97666012e66e7b59b107c3523/drake/doc/developers.rst#L144)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Needs a definition of "lines of code" -- that term is ambiguous to me at least. My understanding is that you are proposing: LOC=lines of source code and comments less white space; lines added but not lines subtracted (and not a net figure balancing the two). I remain unclear about code that simply moved from one place to another -- I guess that should count and people should do their code moving as a separate PR? 
</blockquote></details>

Done.

The intent was github's report, which includes comments and blank lines.

That metric also counts relocated code _when git fails to recognize it as a rename_ (which should exactly match when reviewable decides to show the code as-new vs merely moved, which matches whether or not reviewers are a risk of struggling with it).

If that puts the PR over the hard limit, but the rename is clearly correct and easy to review (e.g. curated commits), then the platform reviewers should vote to allow it.  Examples of this in the historical record were few (I think just one -- 4866).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-KnFWEImDAbezggtaLok:b-apyurz)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by SeanCurtis-TRI** [comment]
@jwnimmer-tri Thanks for the re-wording. Very precise.  :)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-KnFZkpov1oRTd2in3rK:b-prmecv)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFhYdQXFoCqphPzLjz:-KnFhYdQXFoCqphPzLk-:bebrux1) ([raw file](https://github.com/robotlocomotion/drake/blob/17bf009a32885b29c6c47c9228bff91712d023c6/drake/doc/developers.rst#L145)):*
> ```reStructuredText
> A PR generally *should not* include more than 750 added or changed lines (the
> green ``+###`` number as reported by github), and *must not* include more than
> 1500 lines, with the following exemptions:
> ```

 - I think it's worth mentioning `git diff --stat` so that a developer can check the LOC locally without relying on Github.
 - AFAIK, `git diff` does not handle the special cases listed below. Probably we need to update `.gitattributes` file as explained in https://stackoverflow.com/a/10421385. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/developers.rst, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFhYdQXFoCqphPzLjz:-KnFjQ3HoPBG_SjUc0yh:b6pk2tp) ([raw file](https://github.com/robotlocomotion/drake/blob/17bf009a32885b29c6c47c9228bff91712d023c6/drake/doc/developers.rst#L145)):*
> I think it's worth mentioning git diff --stat so that a developer can check the LOC locally without relying on Github.

This doesn't feel important to me, but if you want to suggest specific new text (or better, a hyperlink to a relevant git tutorial) please feel free.  We would need a command-line suggestion that shows the diff vs the base-revision or something (to match github), not just the uncommitted diffs.

> AFAIK, git diff does not handle the special cases listed below.

I think that's appropriate, because neither does github.  Users should still see all of the diffs they are going to submit; we just don't want to count all of them against the review-burden tally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFhYdQXFoCqphPzLjz:-KnFk1VH_IoI4z6ncknC:bfun1h3) ([raw file](https://github.com/robotlocomotion/drake/blob/17bf009a32885b29c6c47c9228bff91712d023c6/drake/doc/developers.rst#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I think it's worth mentioning git diff --stat so that a developer can check the LOC locally without relying on Github.

This doesn't feel important to me, but if you want to suggest specific new text (or better, a hyperlink to a relevant git tutorial) please feel free.  We would need a command-line suggestion that shows the diff vs the base-revision or something (to match github), not just the uncommitted diffs.

> AFAIK, git diff does not handle the special cases listed below.

I think that's appropriate, because neither does github.  Users should still see all of the diffs they are going to submit; we just don't want to count all of them against the review-burden tally.
</blockquote></details>

iirc git diff --stat doesn't respect gitattributes, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/developers.rst, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFhYdQXFoCqphPzLjz:-KnFkh2KVsj-ua7SogQ3:bqmjxqk) ([raw file](https://github.com/robotlocomotion/drake/blob/17bf009a32885b29c6c47c9228bff91712d023c6/drake/doc/developers.rst#L145)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

iirc git diff --stat doesn't respect gitattributes, though.
</blockquote></details>

I guess another option would be to add a shell-script in-tree that reports the size (vs base) but excludes dev and datafiles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFhYdQXFoCqphPzLjz:-KnFu45xmhpSbxwf4bMF:bhitxly) ([raw file](https://github.com/robotlocomotion/drake/blob/17bf009a32885b29c6c47c9228bff91712d023c6/drake/doc/developers.rst#L145)):*
> I guess another option would be to add a shell-script in-tree that reports the size (vs base) but excludes dev and datafiles.

That'd be nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/developers.rst, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFhYdQXFoCqphPzLjz:-KnG6Ru_GOXtJ4aOaK2a:bi5w4k2) ([raw file](https://github.com/robotlocomotion/drake/blob/17bf009a32885b29c6c47c9228bff91712d023c6/drake/doc/developers.rst#L145)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> I guess another option would be to add a shell-script in-tree that reports the size (vs base) but excludes dev and datafiles.

That'd be nice.
</blockquote></details>

Try out the new helper script?  If we like it, I can tidy it up and refer to it here.

---

*[drake/tools/diffstat.sh, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnG6O_HHe2qZZ0I3ieZ:-KnG6O_IWsqLLSfuyX6y:b-n0mdhq) ([raw file](https://github.com/robotlocomotion/drake/blob/9561ae0544ac262bfc0d29f28e7b9c4da5f0195c/drake/tools/diffstat.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

This script is still WIP.  Do not merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/developers.rst, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFSUngqWtXVFP8GyK4:-KnGAurMxTq6jdP0A_iJ:b-kfaewy) ([raw file](https://github.com/robotlocomotion/drake/blob/46308855ad4b00c97666012e66e7b59b107c3523/drake/doc/developers.rst#L153)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Agreement of two platform reviewers should be enough.
</blockquote></details>

Does anyone feel strongly that 3 was an important part of this proposal?  I'm willing to compromise on 2 and then increase it later if need be.

I'll make this change if I don't hear an objection before end-of-week.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFSUngqWtXVFP8GyK4:-KnHLi0nVZezBUaoB1M0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46308855ad4b00c97666012e66e7b59b107c3523/drake/doc/developers.rst#L153)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Does anyone feel strongly that 3 was an important part of this proposal?  I'm willing to compromise on 2 and then increase it later if need be.

I'll make this change if I don't hear an objection before end-of-week.
</blockquote></details>

Done.

---

*[drake/doc/developers.rst, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnFhYdQXFoCqphPzLjz:-KnHLm_VTTgImTntKmXh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/17bf009a32885b29c6c47c9228bff91712d023c6/drake/doc/developers.rst#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Try out the new helper script?  If we like it, I can tidy it up and refer to it here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-KnHMCM-8_2b7xmWgGU_:b-83330m)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri +@ggould-tri +@soonho-tri +@sherm1 +@RussTedrake for platform review, please.  Note that I have updated the overview test atop this PR.

> I think if it were possible a superior approach would be to have an automated system warn the author and/or apply a shame tag to oversize reviews.

If this PR is accepted, then I'll open an issue to add such a nag-bot to the PR workflow.

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/tools/prstat, line 23 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnIA6YHlIS0rQE-DGsV:-KnIA6YHlIS0rQE-DGsW:bwnikzk) ([raw file](https://github.com/robotlocomotion/drake/blob/ebc3e76e433cf72f8f3637c7d6c03a644113d762/drake/tools/prstat#L23)):*
> ```
> toplevel=$(git rev-parse --show-toplevel)
> git_base_path=upstream/master
> for relpath in $(git diff $git_base_path | lsdiff $excludes --strip=1); do
> ```

BTW, in macOSX, `brew install patchutils` is required to have `lsdiff` and `filterdiff`.

---

*[drake/tools/prstat, line 24 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnIAjU35URccJYQzmAp:-KnIAjU35URccJYQzmAq:b-n6j5x7) ([raw file](https://github.com/robotlocomotion/drake/blob/ebc3e76e433cf72f8f3637c7d6c03a644113d762/drake/tools/prstat#L24)):*
> ```
> git_base_path=upstream/master
> for relpath in $(git diff $git_base_path | lsdiff $excludes --strip=1); do
>     if fgrep -q -e"$marker" $toplevel/$relpath; then
> ```

I had the following error messages:

```
fgrep: <path_to_drake-distro>/externals/gflags: Is a directory
fgrep: <path_to_drake-distro>/externals/nlopt: Is a directory
```

which I can suppress by passing `-s` option to `fgrep`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by ggould-tri** [comment]
Sanity check:  Of the big PRs I got in rotation today, this rule would just barely accept #6345 and would reject #6336.  I think that's pretty much the correct result.
:lgtm:

---

Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-KnK2KQD49XFNzDe23x3:b-culikb)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-KnKN4nzyr_tS1Tx7scg:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/tools/prstat, line 4 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnKmKfYWp4afkivItwc:-KnKmKfYWp4afkivItwd:b1y6ezg) ([raw file](https://github.com/robotlocomotion/drake/blob/ebc3e76e433cf72f8f3637c7d6c03a644113d762/drake/tools/prstat#L4)):*
> ```
> 
> # prstat -- Report the lines of code added or changed in the current tree vs
> # upsteam/master, excluding files that are known not to count againt the line
> ```

BTW againt->against

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-KnKpc3bfOXI_YOeCVa_:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/prstat, line 24 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-KnIAjU35URccJYQzmAp:-KnR32U52tdB0WCnlVWY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ebc3e76e433cf72f8f3637c7d6c03a644113d762/drake/tools/prstat#L24)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I had the following error messages:

```
fgrep: <path_to_drake-distro>/externals/gflags: Is a directory
fgrep: <path_to_drake-distro>/externals/nlopt: Is a directory
```

which I can suppress by passing `-s` option to `fgrep`.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-KnR77evuBfPP5G7FMaL:bnfp4nl)*

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-KnSDWjdg9O1LGd921gE:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri ping; please take a look when you have time.

**Comment by ggould-tri** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6338#-:-Kn_gA9qf4YRPGNvasSu:bnfp4nl)*

**Pull request merged**
