### PR TITLE
Add more iiwa LCM message classes

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5246)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-:-KdWxr6QIXr84GtrNjpA:b-psw9ws)*

**Comment by naveenoid** [comment]
Apart from some minor BTWs.. :lgtm: 

---

Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdbiAEDtOV5B8gQ_58G:-KdbiAEDtOV5B8gQ_58H:b-ky6gq0) ([raw file](https://github.com/robotlocomotion/drake/blob/e79adfa8def73a86430c082b29588c6aa990ee19/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L22)):*
> ```cpp
> // when initializing the FRI configuration on the iiwa's control
> // cabinet.
> const double kIiwaLcmStatusInterval = 0.005;
> ```

BTW: consider using the name Period instead of Interval. Its used to set the DiscreteUpdatePeriodSec after all..

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdbj2eM4vurok1YySPG:-Kdbj2eM4vurok1YySPH:bigk5zo) ([raw file](https://github.com/robotlocomotion/drake/blob/e79adfa8def73a86430c082b29588c6aa990ee19/drake/examples/kuka_iiwa_arm/iiwa_lcm.h#L15)):*
> ```objc
> namespace kuka_iiwa_arm {
> 
> extern const double kIiwaLcmStatusInterval;
> ```

BTW: same comment on the name of the variable.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.h, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdbje_j3PDWkMsehNUk:-Kdbje_j3PDWkMsehNUl:b-cvnbad) ([raw file](https://github.com/robotlocomotion/drake/blob/e79adfa8def73a86430c082b29588c6aa990ee19/drake/examples/kuka_iiwa_arm/iiwa_lcm.h#L58)):*
> ```objc
> /// a systems::lcm::LcmPublisherSystem that accepts a
> /// systems::Value object templated on type `lcmt_iiwa_command`.
> class IiwaCommandSender : public systems::LeafSystem<double> {
> ```

BTW: A super BTW, just that the words "CommandSender" seem slightly odd, would "CommandTransmitter" be a better fit along with the "StatusReceiver" counterpart? I leave it to you (also following LCM controlled system conventions)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-:-Kdbk-wJB2QbilM22GLg:b9jo450)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri who I suspect is tomorrow's platform reviewer

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdbiAEDtOV5B8gQ_58G:-KdbnbAlhZiLOecCll1R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e79adfa8def73a86430c082b29588c6aa990ee19/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L22)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: consider using the name Period instead of Interval. Its used to set the DiscreteUpdatePeriodSec after all..
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdbj2eM4vurok1YySPG:-KdbniOhqipvXtZGSsVW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e79adfa8def73a86430c082b29588c6aa990ee19/drake/examples/kuka_iiwa_arm/iiwa_lcm.h#L15)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: same comment on the name of the variable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-:-KdboXaBXxk6EtFhbsIC:by0116s)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdbs9moIKlHoZRFTvnN:-Kdbs9moIKlHoZRFTvnO:b8ufo7n) (no related file):*
This doesn't appear to introduce any _new_ test coverage.  Is there some existing test coverage that this PR ends up being covered by

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by sammy-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdbs9moIKlHoZRFTvnN:-Kdf4IvWKjN25JJo66-a:b-ls45f2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This doesn't appear to introduce any _new_ test coverage.  Is there some existing test coverage that this PR ends up being covered by
</blockquote></details>

Do you want me to split PR's?  Or do you want client code in at the same time as message parsing code?

Will add trivial test coverage, because I'm not sure what other kind there would be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 4 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdbs9moIKlHoZRFTvnN:-Kdf4zDg2x2MDH-5m0jw:b-c3ybjf) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Do you want me to split PR's?  Or do you want client code in at the same time as message parsing code?

Will add trivial test coverage, because I'm not sure what other kind there would be.
</blockquote></details>

I haven't even read the iiwa_lcm changes yet, I'm just trying to understand the big picture before I dive in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by sammy-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdbs9moIKlHoZRFTvnN:-Kdf4ubVqbd4r_w7tX-L:b-bcr4s0) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I haven't even read the iiwa_lcm changes yet, I'm just trying to understand the big picture before I dive in.
</blockquote></details>

I did not mean to imply said test coverage would be short.  zero_order_hold_test.cc is 126 lines, and of (slightly) reduced complex vs the code here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdbs9moIKlHoZRFTvnN:-Kdf5sciuXBMYbXUFeUk:b-84vomu) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I did not mean to imply said test coverage would be short.  zero_order_hold_test.cc is 126 lines, and of (slightly) reduced complex vs the code here.
</blockquote></details>

So I guess that still doesn't speak to helping me try to frame my review?  It sounds like "wait for a moment until a bit more code is added", so I should pause on the review now?

Related to what I am perceiving as a bloat complaint, there is also no reason the tests have to be florid.  For example, for testing `DoCalcDiscreteVariableUpdates` it would be reasonable to expose a helper function that went from `lcmt_iiwa_status` to `BasicVector<double>` and test the case-by-case correctness of that, rather than a test using the System APIs for DoCalcDiscreteVariableUpdates with all of the associated boilerplate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by sammy-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdbs9moIKlHoZRFTvnN:-KdfYBY3aF3YAuMFRBEv:b-pmmq2w) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So I guess that still doesn't speak to helping me try to frame my review?  It sounds like "wait for a moment until a bit more code is added", so I should pause on the review now?

Related to what I am perceiving as a bloat complaint, there is also no reason the tests have to be florid.  For example, for testing `DoCalcDiscreteVariableUpdates` it would be reasonable to expose a helper function that went from `lcmt_iiwa_status` to `BasicVector<double>` and test the case-by-case correctness of that, rather than a test using the System APIs for DoCalcDiscreteVariableUpdates with all of the associated boilerplate.
</blockquote></details>

+(status: do not review) Sorry, forgot to tag with DNR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri I've only put a couple minutes into this, it would be fine to shuffle it off to whoever's on call when its post-DNR again.  Or give it back to me then too, but in any case I'm going to take it off my itinerary for now.

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-:-KdigfE0JMD15D1e25hh:b-k7sc8u)*

**Comment by sammy-tri** [comment]
-(status: do not review) Test added.  +@jwnimmer-tri for platform again.

---

Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-:-Kdluc86n__lV9pxgxN-:b-zat1w1)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 6 files at r3.
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 4 files at r2, 2 of 6 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzsXBXwmM7PDdDAOaO:-KdzsXBXwmM7PDdDAOaP:b-8g7h4i) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L1)):*
> ```cpp
> 
> ```

BTW Leading blank line seems wrong.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdzvq41nsoxd9RQszZV:-Kdzvq41nsoxd9RQszZW:bj0w73z) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L1)):*
> ```cpp
> 
> ```

BTW _Meta_ For LCM to Eigen conversions, there are lots of helpers at, e.g., https://github.com/RobotLocomotion/drake/blob/master/drake/util/drakeUtil.h#L115, instead of rolling your own for-loops.  I think either one is fine, but investing in modernizing the `util` functions may well be worth our time (assuming we stick with the C++98 LCM backend).

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 148 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzumBoprF6V9ThnfJ6:-KdzumBoprF6V9ThnfJ7:b-4unq70) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L148)):*
> ```cpp
> 
>   // If we're using a default constructed message (haven't received
>   // status yet), keep using the initial state.
> ```

Please elaborate on why default-input means that we choose to do "xd[n+1] remains the same as xd[n]" versus "xd[n+1] is the default state".  The latter seems more consistent with a memory-less System, but perhaps the former is a better model of reality that we are attempting to model?

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 176 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzuNmTMK-VkN_wbmEH:-KdzuNmTMK-VkN_wbmEI:b-9sb2h3) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L176)):*
> ```cpp
>       state_value.head(kNumJoints * 2);
>   this->GetMutableOutputVector(output, commanded_position_output_port_) =
>       state_value.tail(kNumJoints);
> ```

This state_value index slicing seems like it could use some de-brittlement.  (Both here, and the method above.)  Either helper routines to pick out the sub-VectorBlock (measured, measured_rate, commanded) from the state VectorBlock, or assertions that the slices fully cover the state, or something.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.h, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzsIdKVuzSFie2gUZJ:-KdzsIdKVuzSFie2gUZK:b1vbtiz) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.h#L59)):*
> ```objc
> /// systems::Value object templated on type `lcmt_iiwa_command`.
> class IiwaCommandSender : public systems::LeafSystem<double> {
>  public:
> ```

_Meta_ "If you do not want to support copy/move operations on your type, explicitly disable them using = delete in the public: section:" -- https://google.github.io/styleguide/cppguide.html#Copyable_Movable_Types

The drake_copyable macro is a convenient way to do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by jwnimmer-tri** [comment]
First pass platform review is complete.  Just a few open items.

Please be sure that @naveenoid is marked up-to-date on all new changes before merging.

---

Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzxHpzITWogCPzkXZW:-KdzxHq-OI_V9b1SZzDl:bmlaabw) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L12)):*
> ```cpp
> 
> #include "drake/lcmt_iiwa_command.hpp"
> #include "drake/lcmt_iiwa_status.hpp"
> ```

_Meta_ the include statements from a single numbered group (of the 5 from https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) should not have blank lines between them.  (In this case, Eigen+gest should become adjacent, as should all of the drake/* items.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-:-KdzzZDyfrdidMGzzL5p:bto0xgi)*

**Comment by naveenoid** [comment]
Im reviewing newer changes now.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-:-Ke-5bSj0qfaLeSPAoUl:b-xzysh7)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Ke-5m8XIX7yEiI2NVVX:-Ke-5m8XIX7yEiI2NVVY:b-u6nmkv) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L19)):*
> ```cpp
> 
> static const int kNumJoints = 7;
> ```

I guess a short comment block explaining the purpose of the unit test is always useful..

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 79 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Ke-BujdSh1HQStEjjMH:-Ke-BujdSh1HQStEjjMI:b-ohs14x) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L79)):*
> ```cpp
>       tol, MatrixCompareType::absolute));
> }
> ```

Again, a comment here..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by sammy-tri** [comment]
Review status: 3 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzsXBXwmM7PDdDAOaO:-Ke-BXKhGJ28dVwRj_4B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Leading blank line seems wrong.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Kdzvq41nsoxd9RQszZV:-Ke-CO3xuv4bRFLScQ7P:b-94g6ap) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW _Meta_ For LCM to Eigen conversions, there are lots of helpers at, e.g., https://github.com/RobotLocomotion/drake/blob/master/drake/util/drakeUtil.h#L115, instead of rolling your own for-loops.  I think either one is fine, but investing in modernizing the `util` functions may well be worth our time (assuming we stick with the C++98 LCM backend).
</blockquote></details>

I had completely forgotten about those...  I looked into switching briefly, but it seemed like enough of the cases in this file were using the BasicVector operations that converting those to eigen vectors and then using the drakeUtil.h stuff wasn't much of a win.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 148 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzumBoprF6V9ThnfJ6:-Ke-CqOJIJ_lot0fUTZp:bkg2v8v) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L148)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please elaborate on why default-input means that we choose to do "xd[n+1] remains the same as xd[n]" versus "xd[n+1] is the default state".  The latter seems more consistent with a memory-less System, but perhaps the former is a better model of reality that we are attempting to model?
</blockquote></details>

I don't understand the difference in what you're describing.  xd at t == 0 (a.k.a prior to the first call to DoCalcDiscreteVariableUpdates) is the default state, so holding the current state (before receiving any incoming messages describing a new state) is the same as setting the default.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 176 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzuNmTMK-VkN_wbmEH:-Ke-EwwhOIJXWOZmvpI7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L176)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This state_value index slicing seems like it could use some de-brittlement.  (Both here, and the method above.)  Either helper routines to pick out the sub-VectorBlock (measured, measured_rate, commanded) from the state VectorBlock, or assertions that the slices fully cover the state, or something.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.h, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzsIdKVuzSFie2gUZJ:-Ke-FGdqtE0_-KD8gdfh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.h#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ "If you do not want to support copy/move operations on your type, explicitly disable them using = delete in the public: section:" -- https://google.github.io/styleguide/cppguide.html#Copyable_Movable_Types

The drake_copyable macro is a convenient way to do that.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzxHpzITWogCPzkXZW:-Ke-FXhn5uIPwtOEF8sF:b-hk05z4) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ the include statements from a single numbered group (of the 5 from https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) should not have blank lines between them.  (In this case, Eigen+gest should become adjacent, as should all of the drake/* items.)
</blockquote></details>

Done for the drake/ items.  A quick grep shows that splitting the drake/lcmt_* includes from the main body of drake includes and mixing them in alphabetically both occur in the tree now.

I'm going to need additional explanation on how/why Eigen which is included in Drake primarily with <> syntax belongs in the same group as gtest included with "" syntax.  One answer might be that we should not be using different include styles.  (gtest is occasionally but rarely included with <> in drake)

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Ke-5m8XIX7yEiI2NVVX:-Ke-GPDPjC_PzxhpSdMV:bqi6fzz) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L19)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

I guess a short comment block explaining the purpose of the unit test is always useful..
</blockquote></details>

It's going to say "Test the IiwaCommandReceiver" or "Test that IiwaCommandReceiver receives commands" or something similarly vacuous unless something better comes to me.  I can put that in if we think it's actually useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by naveenoid** [comment]
Review status: 3 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-Ke-5m8XIX7yEiI2NVVX:-Ke-HSYhwbLd40uhgnJ0:b-cdeb33) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L19)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It's going to say "Test the IiwaCommandReceiver" or "Test that IiwaCommandReceiver receives commands" or something similarly vacuous unless something better comes to me.  I can put that in if we think it's actually useful.
</blockquote></details>

Ok I concede ;) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 148 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzumBoprF6V9ThnfJ6:-Ke-Owgg1jc2lUF11-WP:btfkrrq) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L148)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That assumes that `status` will only ever appear as empty at the start of a simulation, but that's dependent on how the system is wired up, yes?
</blockquote></details>

Per f2f, we think the code as-is is desirable, but Sam will consider adding more comments.  Marking myself resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-:-Ke-P5Kth_x2A51qRR19:bnfp4nl)*

**Comment by naveenoid** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-:-Ke-VYtcbqd2KXtcm2_w:bg7igkv)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 148 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzumBoprF6V9ThnfJ6:-Ke-uhBPJlv1tjKdy44w:b-5bk73d) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L148)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Per f2f, we think the code as-is is desirable, but Sam will consider adding more comments.  Marking myself resolved.
</blockquote></details>

Slightly modified a header comment.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5246#-KdzxHpzITWogCPzkXZW:-Ke-u3hbCLndAJDp7rmR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f0096a29046c716a17ad276564de15765afa5a0/drake/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `""` vs `<>` for third-party includes is a lonstanding bikeshed in Drake, and I am happy to work it through again, but I don't think it bears on this discussion?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5246)*

**Pull request merged**
