### PR TITLE
[solvers] Fix a bug in GurobiSolver with duplicated variables in second-order cone constraints.

### LINKED ISSUE #18882: GurobiSolver fails with a degenerate Lorentz cone.
### What happened?

As reported in https://github.com/RobotLocomotion/drake/issues/18076#issuecomment-1445539047. When the Lorentz cone has the form ℓ ≥ sqrt((x-x)² + (y-y)²), it should be regarded as a linear constraint. But we pass it as a Lorentz cone constraint, which causes problem in Gurobi.

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #18882

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18890)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@mpetersen94 for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-:-NPKmdGb7Dl6ae3vvjbj:b3ej2ph)* status: LGTM missing from assignee mpetersen94, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
:lgtm: with a couple fixes. I don't really understand why this change to 'gurobi_solver.cc` resolves the bug but the new way of passing the Cone constraint is much more interpretable. 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-:-NPLMyP-9Uo2uWpX4Zr6:b-r9kanm)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/second_order_cone_program_examples.cc` line 624 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-NPLIeGR-v5Izhj3B5K4:-NPLIeGR-v5Izhj3B5K5:bdy5cyv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6e8770cc265e9b76dccb4e20341871f234b93a70/solvers/test/second_order_cone_program_examples.cc#L624)):*
> ```cpp
>     const std::optional<SolverOptions>& solver_options, double tol) {
>   MathematicalProgram prog;
>   auto dummy = prog.NewContinuousVariables<2>();
> ```

I don't think this dummy variable is needed.
___
*[`solvers/test/second_order_cone_program_examples.cc` line 627 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-NPLIIhSA9ACZsijjIPG:-NPLIIhT9sRde2myh2yK:b-ousbsk) ([raw file](https://github.com/RobotLocomotion/drake/blob/6e8770cc265e9b76dccb4e20341871f234b93a70/solvers/test/second_order_cone_program_examples.cc#L627)):*
> ```cpp
>   auto x = prog.NewContinuousVariables<2>();
>   // A * [x(0), x(1), x(0), x(1)] = [1; 2x(0); 3x(1)]
>   Eigen::Matrix<double, 3, 4> A;
> ```

This matrix size does not seem to agree with the values being pushed into it. Am I missing something?

**Review by hongkai-dai — COMMENTED** [review]
The issue before was that when we pass in the Lorentz cone constraint `A * x + b is in Cone`, we actually tell Gurobi to enforce this
```
z - A*x = b
z is in Cone
```
If the linear constraint `z - A * x = b` contains duplicate variables (for example x = [x(0), x(1), x(2), x(1), x(2)]) then Gurobi will throw an error and don't impose the linear constraints.

Now we explicitly account for the duplication of variables (`Eigen::SparseMatrix::setFromTriplets(triplets.begin(), triplets.end())` function will automatically group the entries in `triplets` that correspond to the same entries in the sparse matrix. Hence when we pass the linear matrix to Gurobi, it doesn't contain any duplicated entries, and Gurobi is happy then.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-:-NPLQ8nZ8WO6ZsvaSuY0:bux1mwq)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

___
*[`solvers/test/second_order_cone_program_examples.cc` line 624 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-NPLIeGR-v5Izhj3B5K4:-NPLRKR14ldUEtlwb0ee:b1xs7nc) ([raw file](https://github.com/RobotLocomotion/drake/blob/6e8770cc265e9b76dccb4e20341871f234b93a70/solvers/test/second_order_cone_program_examples.cc#L624)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I don't think this dummy variable is needed.
</blockquote></details>

This is intentional, to make sure that when I impose the Lorentz cone constraint, it will test that our code considers the shift of `x` in prog.decision_variables(). I added some documentation here.
___
*[`solvers/test/second_order_cone_program_examples.cc` line 627 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-NPLIIhSA9ACZsijjIPG:-NPLRdWtEzTOm0CkGnn9:b-376vyo) ([raw file](https://github.com/RobotLocomotion/drake/blob/6e8770cc265e9b76dccb4e20341871f234b93a70/solvers/test/second_order_cone_program_examples.cc#L627)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

This matrix size does not seem to agree with the values being pushed into it. Am I missing something? 
</blockquote></details>

Done. Good catch!

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-:-NPLZrQR5yVZNCWYcCdV:b8asji7)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @mpetersen94 and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: possible typo

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-:-NPNnLU7CDXRqtW9E3pN:be27vk4)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai and @mpetersen94)

___
*[`solvers/gurobi_solver.cc` line 530 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-NPNnCfvAlD5LcIyA6I1:-NPNnCfvAlD5LcIyA6I2:b-wis829) ([raw file](https://github.com/RobotLocomotion/drake/blob/20d3f60a0b7328ab05ab847fd57ee3d940446969/solvers/gurobi_solver.cc#L530)):*
> ```cpp
>     Eigen::SparseMatrix<double, Eigen::RowMajor> M(num_z, num_gurobi_vars);
>     // Eigen::SparseMatrix::setFromTriplets will automatically group the sum up
>     // the values in M_triplets that correspond to the same entry in the sparse
> ```

Maybe a typo here?



_Suggestion:_
```cpp
    // Eigen::SparseMatrix::setFromTriplets will automatically group the sum of
    // the values in M_triplets that correspond to the same entry in the sparse
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18890)* status: 2 unresolved discussions, missing label for release notes (waiting on @mpetersen94 and @rpoyner-tri)

___
*[`solvers/gurobi_solver.cc` line 530 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18890#-NPNnCfvAlD5LcIyA6I1:-NPO63HwBKL0quue3VyY:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/20d3f60a0b7328ab05ab847fd57ee3d940446969/solvers/gurobi_solver.cc#L530)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Maybe a typo here?
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18890)* status: 1 unresolved discussion, missing label for release notes (waiting on @mpetersen94)

**Pull request merged**
