### PR TITLE
[setup] Remove macOS auto-cleanup for drake_visualizer's removal

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
As a courtesy, we were uninstalling software that's no longer needed by Drake (#16945). We assume that enough users will have run this by now.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18229)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-big-sur-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@svenevs for feature review, please.

**Review by svenevs — COMMENTED** [review]
:LGTM:, CI got past the setup phase which is all that matters here.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18229#-:-NFoO3dN6XP7nTlRBCve:bz0cnql)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule (tomorrow), please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18229#-:-NFp1Mr_4xLYPDhVRlVK:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees svenevs,xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
