### PR TITLE
Updates MBP SDF parser to parse boxes for SG.

### PR DESCRIPTION
**Pull request by amcastro-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8800)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for feature review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8800#-:-LCGBWjhEi5nBDbKvW-g:b-4269ug)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: With two very minor thoughts.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8800#-LCZ0NoXEKkBdudhFEHH:-LCZ0NoY3YcD1oY7MO8m:b-w98o69) ([raw file](https://github.com/robotlocomotion/drake/blob/d2b9e8b87f6995e08b708867078257e9de871f1c/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L22)):*
> ```cpp
> std::unique_ptr<geometry::Shape> MakeShapeFromSdfGeometry(
>     const sdf::Geometry& sdf_geometry) {
>   switch (sdf_geometry.Type()) {
> ```

BTW It's good practice when switching on an enumeration to order the case statements in the same order as the enumeration declaration: EMPTY, BOX, CYLINDER, PLANE, SPHERE.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8800#-LCZ22r_BliU5aniPwbf:-LCZ22r_BliU5aniPwbg:b-9x0tbm) ([raw file](https://github.com/robotlocomotion/drake/blob/d2b9e8b87f6995e08b708867078257e9de871f1c/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L120)):*
> ```cpp
>       "</box>");
>   unique_ptr<Shape> shape = MakeShapeFromSdfGeometry(*sdf_geometry);
>   const Box& box = dynamic_cast<const Box&>(*shape);
> ```

BTW This test called this to my attention (although it applies to all the shapes). If, for whatever reason, this cast were to fail, the test would die without any useful messages. Instead if you did this:

```c++
const Box* box = dynamic_cast<const Box*>(shape);
ASSERT_NE(box, nullptr);
EXPECT_EQ(box->size(), Vector3d(1.0, 2.0, 3.0));
```

Then in that same failure condition, you'd get a useful GTEST message.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8800#-:-LCZ2h2Y2tWMVgXrcp9z:ba3pfoe)*

**Comment by amcastro-tri** [comment]
+@sammy-tri for platform review please.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8800#-:-LCZ67hs3-JxFKOIOlZ4:b-1zm1j3)*

**Comment by sammy-tri** [comment]
First pass complete.  I jumped in on the enum order issue, but nothing new from me.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8800#-LCZ0NoXEKkBdudhFEHH:-LCZULP5-5LAaUsXgrKh:btd51a6) ([raw file](https://github.com/robotlocomotion/drake/blob/d2b9e8b87f6995e08b708867078257e9de871f1c/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L22)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It's good practice when switching on an enumeration to order the case statements in the same order as the enumeration declaration: EMPTY, BOX, CYLINDER, PLANE, SPHERE.
</blockquote></details>

I agree.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8800#-:-LCZUPE98nIHOJZwBouB:b-8b1rjw)*

**Comment by amcastro-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8800#-LCZ0NoXEKkBdudhFEHH:-LCd7P9n9wqgDJhChaF_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2b9e8b87f6995e08b708867078257e9de871f1c/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L22)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I agree.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8800)*

**Comment by sammy-tri** [comment]
:lgtm: +(status: curate commits before merging) 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8800#-:-LCdMkJ70eE7UCyCJCDh:b-pu9q93)*

**Pull request merged**
