### PR TITLE
[pydrake] Improve unit test demo/coverage for lcmt_image_array

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A step towards #18237 and #16502.

The overall goal is to have Python test coverage of libjpeg image decoding (which we perform in Drake via VTK) so that we can be confident in our VTK build system updates.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18245)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI as the author of #10500, I think you get right of first refusal on this feature review.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature, thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18245#-:-NFt4xvT0aTiUoDyZMtR:bbi1qd9)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/systems/test/sensors_test.py` line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18245#-NFt4mAA-8wkVCgPCANm:-NFt4mAA-8wkVCgPCANn:b-e21d0r) ([raw file](https://github.com/robotlocomotion/drake/blob/302deb5bb131cddbedde1404804b7caa174b5a48/bindings/pydrake/systems/test/sensors_test.py#L310)):*
> ```Python
>         # into the Value[] template class), so to inspect it we'll need to
>         # serialize down into raw bytes and then back into a Python message.
>         serializer = _Serializer_[lcmt_image_array]()
> ```

BTW Nice! I believe this could be sugared up at some point, but not here.

Marginally relates https://github.com/RobotLocomotion/drake-ros/pull/169 (\cc @sloretz)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18245)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/systems/test/sensors_test.py` line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18245#-NFt4mAA-8wkVCgPCANm:-NFt5OgU3qJcUZGqm5XS:btv1ekq) ([raw file](https://github.com/robotlocomotion/drake/blob/302deb5bb131cddbedde1404804b7caa174b5a48/bindings/pydrake/systems/test/sensors_test.py#L310)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Nice! I believe this could be sugared up at some point, but not here.

Marginally relates https://github.com/RobotLocomotion/drake-ros/pull/169 (\cc @sloretz)
</blockquote></details>

Agreed.  I've toyed with having `port.Eval` or `Value[]` somehow handle it automatically (probably too magical?), or else yeah have something in `systems.lcm` that the user acutely calls but is clear and brief.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18245#-:-NFtE12Z950QTNN1E0LM:bzus18)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
