### PR TITLE
Google tests/contact and collision

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR creates a unit test from the PR #1944. Therefore #1944 is a prerequisite for this new PR. 
See the [README](https://github.com/amcastro-tri/drake/blob/GoogleTests/ContactAndCollision/drake/examples/SimpleCollisionTests/README.md) file for instructions and a description of the test. 

Find a summary of convergence tests within [convergence_test.md](https://github.com/amcastro-tri/drake/blob/GoogleTests/ContactAndCollision/drake/examples/SimpleCollisionTests/convergence_test.md)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2005)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@amcastro-tri I don't think it's useful to file this PR until #1944 gets merged.  As it stands, this PR contains the full commit set / diffs of #1944 all rolled up into one, so it's not really useful for anyone to review this PR yet.

Or perhaps you just wanted CI to test it?  In which case put that in note here, so that we know to ignore it.

**Comment by amcastro-tri** [comment]
I agree with you @jwnimmer-tri. That's what I meant by saying at the top of the page that #1944 is a prerequisite for this commit. Also notice I didn't assign anybody for this to be reviewed yet (as I did with #1944). I mentioned you in #1944 so that you knew I did consider the implementation of a unit test for this case. Also yes you are right, I wanted to see if this passed the CI. Thank you for following this!

**Comment by jwnimmer-tri** [comment]
Great!  I'll try to clarify for others by using this tag, perhaps...
This PR is just a CI test, not code to be reviewed / merged (yet).

**Comment by sherm1** [comment]
@amcastro-tri, this PR should get closed for now too until the replacement for #1944 is ready.

**Pull request closed without merging**
