### PR TITLE
[workspace] Upgrade CRU and VGT to latest commit

### PR DESCRIPTION
**Pull request by calderpg-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20374)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please

**Comment by calderpg-tri** [comment]
+@jwnimmer-tri for review, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews +(status: single reviewer ok).

+(release notes: fix) for the upgrade.

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20374#-:-Ngy3xaC6T6umc0J7FMt:b-b8htmn)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[`tools/workspace/common_robotics_utilities/package.BUILD.bazel` line 91 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20374#-Ngy3Zq05CkuclpUUihr:-Ngy3Zq1DAQVt4OqLfWa:b-h36rpq) ([raw file](https://github.com/RobotLocomotion/drake/blob/b470a74f3aa6131c825a6f288d90e3fdf1759760/tools/workspace/common_robotics_utilities/package.BUILD.bazel#L91)):*
> ```
>     deps = [
>         ":common_robotics_utilities",
>         "@eigen",
> ```

nit The deps on `@eigen` appears to be unused.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20374)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Pull request merged**
