### PR TITLE
Removes outdated xacro from Drake.

### LINKED ISSUE #4326: Add Xacro as build-dependency
_Edit: This issue was originally titled "Update Drake's version of Xacro"._

In #4218, the HSRb model is not being used in `hsrb_system_factories_test` because it is unable to generate the URDF model of the HSRb due to lack of a modern version of ROS `xacro`. This issue tracks the updating and integration of the latest version of `ROS xacro` with C++ Drake.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4326. Rather than maintain a separate copy of `xacro` within Drake that can become outdated, let's simply use the latest version provided by ROS, version control the generated URDFs, and provide detailed regeneration instructions.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5807)

### CODE REVIEW

**Comment by liangfok** [comment]
+@russtedrake for feature review since this touches drake-MATLAB.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5807#-:-KhYMs_DIK14NOGc8k0K:b8phvzs)*

**Comment by rdeits** [comment]
We originally included the `xacro.py` file within drake because many of us needed to use xacro but didn't have ROS installed (because it's a huge dependency which historically hasn't built well outside of a single Ubuntu version). Removing it would mean that, for example, most mac users won't be able to generate any models from xacro files. 

On the other hand, I haven't personally needed xacro since the end of the DRC, so maybe this isn't an important issue anymore.

**Comment by liangfok** [comment]
I see. Makes sense. I'll close this PR since some users may not be able to install ROS. Maybe a better solution is to update Drake's version of `xacro` to a more recent version: https://github.com/ros/xacro/blob/kinetic-devel/src/xacro/__init__.py

**Comment by rdeits** [comment]
Thanks! Yes, updating Drake's xacro definitely seems like a good idea.

**Pull request closed without merging**
