### PR TITLE
Generalize lorentz cone

### PR DESCRIPTION
**Pull request by hongkai-dai**
Now supports the (rotated) Lorentz cone constraint on a linear expression `A*x+b`. This is going to help writing symbolic expression for Lorentz cone constraint.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4436)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@siyuanfeng-tri for feature review.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-:-KYXmFQ-E92QZPUojuFo:b-y9j464)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[drake/solvers/constraint.h, line 245 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYYxjmDdO5gRF_9_yNt:-KYYxjmDdO5gRF_9_yNu:b-ouzlcv) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/constraint.h#L245)):*
> ```objc
> 
>   /// Getter for A.
>   const Eigen::MatrixXd& A() { return A_; }
> ```

A() const? 

---

*[drake/solvers/constraint.h, line 296 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYYy3eMN2-aI2p34fae:-KYYy3eMN2-aI2p34faf:b-jr9ge9) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/constraint.h#L296)):*
> ```objc
> 
>   /// Getter for A.
>   const Eigen::MatrixXd& A() { return A_; }
> ```

const? 

---

*[drake/solvers/gurobi_solver.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ4G4yTkibvzI0dZoc:-KYZ4G4zu3dnV0cs1dM6:bckpp6m) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L128)):*
> ```cpp
>     DRAKE_ASSERT(IsNumberOfVariablesAsExpected(model, is_new_variable->size()));
>     // TODO(hongkai.dai): Use a sparse A_lorentz matrix.
>     Eigen::MatrixXd A_lorentz(A.rows(), A.rows() + A.cols());
> ```

BTW, this is totally fine, but i'd change it to A_lorentz(A.rows(), A.cols() + Z.size()); so it's more obvious. or even better, make Z more explicit in this chunk of code. 

---

*[drake/solvers/gurobi_solver.cc, line 133 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ56uAjt8PGJGcUJvo:-KYZ56uAjt8PGJGcUJvp:b9xi6dy) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L133)):*
> ```cpp
>                                 GRB_EQUAL, sparseness_threshold);
> 
>     // Mosek uses a matrix Q to differentiate Lorentz cone and rotated Lorentz
> ```

i didn't get this section at all. can you explain it a bit more? i thought you are done with constraints at this point. 
also is this specific to mosek? and this is a gurobi solver?

---

*[drake/solvers/gurobi_solver.cc, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYYzKIskjktOYjFyx8m:-KYYzKIskjktOYjFyx8n:bhk5k4p) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L149)):*
> ```cpp
>     //           ...
>     //     [0  0 0 0 ... 1]
>     // We will store Q in a sparse format
> ```

. at end.

---

*[drake/solvers/gurobi_solver.cc, line 408 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ0IdXd4xtAdoj2U1z:-KYZ0IdXd4xtAdoj2U2-:bmnwpyo) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L408)):*
> ```cpp
>   // For example, for Lorentz cone and rotated Lorentz cone constraint,to impose
>   // that A*x+b lies in the (rotated) Lorentz cone, we add decision variable z
>   // to Gurobi, defined as z = A*x + b.
> ```

can you add a sentence saying is_new_variable is modified by AddSecondOrderConeConstraints. at a glance, its size looks the same as prog's var size. 

---

*[drake/solvers/gurobi_solver.cc, line 478 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ1LWNRwv1KqXTw5Ct:-KYZ1LWNRwv1KqXTw5Cu:bwmsx0p) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L478)):*
> ```cpp
>   }
> 
>   DRAKE_ASSERT(IsNumberOfVariablesAsExpected(model, is_new_variable.size()));
> ```

i would do demand here, this doesn't look too expensive, and is a good sanity check at runtime. 

---

*[drake/solvers/mathematical_program.h, line 1191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ5vJWkK7b2CYlLXB1:-KYZ5vJWkK7b2CYlLXB2:beehc3g) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/mathematical_program.h#L1191)):*
> ```objc
>   /**
>    * Adds a rotated Lorentz cone constraint referencing potentially a subset
>    * of decision variables, that the linear expression @f$ Ax+b @f$ is in the
> ```

such that? 

---

*[drake/solvers/mosek_solver.cc, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ6TQ5yc0vDBVMsMxF:-KYZ6TQ5yc0vDBVMsMxG:bo996m8) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/mosek_solver.cc#L181)):*
> ```cpp
>     const auto& A = binding.constraint()->A();
>     const auto& b = binding.constraint()->b();
>     const int num_new_vars = A.rows();
> ```

maybe just call it num_z. use z instead of new_vars. 

---

*[drake/solvers/mosek_solver.cc, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ89G5ez8TzmqZi2jo:-KYZ89G6-axBCouACN5D:by159tl) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/mosek_solver.cc#L213)):*
> ```cpp
>     // The first row of this constraint needs special treatment.
>     // If using Lorentz cone,
>     // Add the linear constraint z0 = a0^T*x+b0
> ```

these two lines are not obvious to me anymore. can you elaborate a bit more here? 

---

*[drake/solvers/test/constraint_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ8jjaAf4UEaKtfvUP:-KYZ8jjaAf4UEaKtfvUQ:bb6umlu) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/test/constraint_test.cc#L34)):*
> ```cpp
> 
>   bool is_in_cone_expected = (y(0) >= 0) & (y(1) >= 0);
>   EXPECT_TRUE(is_in_cone == is_in_cone_expected);
> ```

EQ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4436)*

**Comment by hongkai-dai** [comment]
Review status: 8 of 9 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[drake/solvers/constraint.h, line 245 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYYxjmDdO5gRF_9_yNt:-KYZOx1gxAz68xZrCgzP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/constraint.h#L245)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

A() const? 
</blockquote></details>

Done.

---

*[drake/solvers/constraint.h, line 296 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYYy3eMN2-aI2p34fae:-KYZOxReSD-5kFIyjSTC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/constraint.h#L296)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

const? 
</blockquote></details>

Done.

---

*[drake/solvers/gurobi_solver.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ4G4yTkibvzI0dZoc:-KYZPOd4TUyrIM_Ebq2n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L128)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, this is totally fine, but i'd change it to A_lorentz(A.rows(), A.cols() + Z.size()); so it's more obvious. or even better, make Z more explicit in this chunk of code. 
</blockquote></details>

Done.

---

*[drake/solvers/gurobi_solver.cc, line 133 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ56uAjt8PGJGcUJvo:-KYZP3TXbMQKB6UVfybv:b-o5dkyk) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L133)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i didn't get this section at all. can you explain it a bit more? i thought you are done with constraints at this point. 
also is this specific to mosek? and this is a gurobi solver?
</blockquote></details>

Done. Sorry should say `Gurobi` instead of `Mosek`.

---

*[drake/solvers/gurobi_solver.cc, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYYzKIskjktOYjFyx8m:-KYZPWVd6t8qf2_fvtkU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L149)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

. at end.
</blockquote></details>

Done.

---

*[drake/solvers/gurobi_solver.cc, line 408 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ0IdXd4xtAdoj2U1z:-KYZXfP-AUNVXK2JwKR6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L408)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

can you add a sentence saying is_new_variable is modified by AddSecondOrderConeConstraints. at a glance, its size looks the same as prog's var size. 
</blockquote></details>

Done.

---

*[drake/solvers/gurobi_solver.cc, line 478 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ1LWNRwv1KqXTw5Ct:-KYZQPiSAQMo-XjNssUc:bn7e6pi) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L478)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i would do demand here, this doesn't look too expensive, and is a good sanity check at runtime. 
</blockquote></details>

That is actually an expensive operator, it requires to update the Gurobi model. Gurobi uses this `lazy update` strategy, that it usually does not update the model until calling `GRBoptimize` function.  https://www.gurobi.com/documentation/7.0/refman/c_grbaddvars.html

I add documentation to `IsNumberOfVariablesAsExpected`, saying this function could be expensive.

---

*[drake/solvers/mathematical_program.h, line 1191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ5vJWkK7b2CYlLXB1:-KYZXrBul-XzbDaWpBCk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/mathematical_program.h#L1191)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

such that? 
</blockquote></details>

Done.

---

*[drake/solvers/mosek_solver.cc, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ6TQ5yc0vDBVMsMxF:-KYZZsLMZnvO-KH0IT2K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/mosek_solver.cc#L181)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

maybe just call it num_z. use z instead of new_vars. 
</blockquote></details>

Done.

---

*[drake/solvers/mosek_solver.cc, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ89G5ez8TzmqZi2jo:-KYZd6BEKA9AeGgHrqjj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/mosek_solver.cc#L213)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

these two lines are not obvious to me anymore. can you elaborate a bit more here? 
</blockquote></details>

Done.

---

*[drake/solvers/test/constraint_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ8jjaAf4UEaKtfvUP:-KYZdM9JXZ_PtPnMI47I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/test/constraint_test.cc#L34)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

EQ? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4436)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/solvers/gurobi_solver.cc, line 133 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ56uAjt8PGJGcUJvo:-KYZlfuHr00Y9YNzKtHz:b-yf0cnp) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L133)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. Sorry should say `Gurobi` instead of `Mosek`.
</blockquote></details>

So this Q thing is only for telling gurobi this part is quadratic constraint? 

---

*[drake/solvers/gurobi_solver.cc, line 478 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ1LWNRwv1KqXTw5Ct:-KYZmXp5OVpQPlILs3DI:baoiidk) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L478)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

That is actually an expensive operator, it requires to update the Gurobi model. Gurobi uses this `lazy update` strategy, that it usually does not update the model until calling `GRBoptimize` function.  https://www.gurobi.com/documentation/7.0/refman/c_grbaddvars.html

I add documentation to `IsNumberOfVariablesAsExpected`, saying this function could be expensive.
</blockquote></details>

i see. good to know. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4436)*

**Comment by hongkai-dai** [comment]
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/gurobi_solver.cc, line 133 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ56uAjt8PGJGcUJvo:-KY_1BjO_OgA49awH5NN:bm6926k) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L133)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

So this Q thing is only for telling gurobi this part is quadratic constraint? 
</blockquote></details>

The Q is used to generate a quadratic expression. If you have a vector `z`, and compute `z'*Q*z`, then for the Lorentz cone constraint, this expression is equal to
```
z(1)^2 + ... + z(n-1)^2 - z(0)^2 
```
For rotated Lorentz cone constraint, this expression equals to
```
z(2)^2 + ... + z(n-1)^2 - z(0)*z(1)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4436)*

**Comment by siyuanfeng-tri** [comment]
*[drake/solvers/gurobi_solver.cc, line 133 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-KYZ56uAjt8PGJGcUJvo:-KY_37_D_g3Lag-X0mkM:b-6nkgvy) ([raw file](https://github.com/robotlocomotion/drake/blob/352a297e7e29e0ec5ce8e34a034ac1c816f3dfe6/drake/solvers/gurobi_solver.cc#L133)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The Q is used to generate a quadratic expression. If you have a vector `z`, and compute `z'*Q*z`, then for the Lorentz cone constraint, this expression is equal to
```
z(1)^2 + ... + z(n-1)^2 - z(0)^2 
```
For rotated Lorentz cone constraint, this expression equals to
```
z(2)^2 + ... + z(n-1)^2 - z(0)*z(1)
```
</blockquote></details>

yep, i realized that afterwards, thanks for writing the ref down. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4436)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 

---

Review status: 6 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4436#-:-KY_3d9scnG4DniHF2kf:bg7igkv)*

**Comment by hongkai-dai** [comment]
I realized none of the solver (Gurobi, Mosek, SCS) supports the generalized lorentz cone constraint directly, that `A*x+b` lies within the cone. I will abort this change, and use the previous approach, that the user need to add a new variable `z` by him/herself, with the linear constraint `z = A*x+b`, and `z` lying within the cone.

**Pull request closed without merging**
