### PR TITLE
simulator_limit_malloc_test: Cover all event types

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #14543

This is the sixth of a long PR train to make heapless simulation
possible, with careful system construction. Inspired by @edrumwri's
draft PR #14707.

This patch expands heap-allocation testing to cover all event types and
schedules.

Subsequent patches will remove the heap allocations tracked here.

Subsequent patches will expand this technique (and test coverage) to the
other event types.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15010)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: do not merge) until #14969 has merged. This test will fail until then anyway. A rebase will be required.
+@joemasterjohn for feature review, having reviewed the last rev of this test.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15010#-:-MZxAwPM7pdK6JqhpENo:b-n0dy2k)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @joemasterjohn)

**Review by rpoyner-tri — COMMENTED** [review]
-(status: do not merge) rebase is done; test should pass.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15010#-:-MZyN-jEA7re0xblUi1K:bxtgcew)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: feature. +@ggould-tri for platform review, please.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15010#-:-M_2UF4O9Y9wmv7Z4lmW:bhyr7y0)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
FYI This is after EOD on my platform review so I will not get to it today.  I may get to it tomorrow but if not am out until Tuesday.  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15010#-:-M_2Ui6l8SVQgCLGeb2c:b-bl1fdn)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by rpoyner-tri — COMMENTED** [review]
-@ggould-tri +@ericcousineau-tri for Monday schedule platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15010#-:-M_2o7wMAWdOVzz5cooa:b-i8ywo7)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
