### PR TITLE
[workspace] Upgrade drake_models to latest commit

### PR DESCRIPTION
**Pull request by amcastro-tri**
Working temporary 40b7ce8 until the models PR [#72](https://github.com/RobotLocomotion/models/pull/72) is merged.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22321)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22321)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`tools/workspace/drake_models/repository.bzl` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22321#-OEKNuBD15wBUjepZyU1:-OEKNuBE36XkMWpORevt:b5780dk) ([raw file](https://github.com/RobotLocomotion/drake/blob/94b4e9ae4412bbc9a0fe2427562c47edde51e95a/tools/workspace/drake_models/repository.bzl#L10)):*
> ```Starlark
>         repository = "RobotLocomotion/models",
>         commit = "80a5d2609daaeb6f86a63545e6933e0edda06cda",
>         sha256 = "40b7ce8894c75ab8ec047d897fe1b423c1f119d3af8b293fda2232ff72ac4a7a",  # noqa
> ```

Working temporary 40b7ce8 until the models PR [#72](https://github.com/RobotLocomotion/models/pull/72) is merged.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22321)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`tools/workspace/drake_models/repository.bzl` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22321#-OEKNuBD15wBUjepZyU1:-OEKxZSi86f4h19mqjcy:b-96uiip) ([raw file](https://github.com/RobotLocomotion/drake/blob/94b4e9ae4412bbc9a0fe2427562c47edde51e95a/tools/workspace/drake_models/repository.bzl#L10)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Working temporary 40b7ce8 until the models PR [#72](https://github.com/RobotLocomotion/models/pull/72) is merged.
</blockquote></details>

BTW `78cad6a331aa0610e8f84e463d28103d096bdb83` is the new sha you want here now.

**Comment by jwnimmer-tri** [comment]
BTW I corrected the PR title.  Please use that subject when merging, not the commit message subject.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: fix) 
+(status: single reviewer ok) 

Need to update the sha.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22321#-:-OEL-4up41LEQykA88AP:b-8ep1bc)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`tools/workspace/drake_models/repository.bzl` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22321#-OEKNuBD15wBUjepZyU1:-OEL-1py6yZo-il_gz8C:b-igfsmf) ([raw file](https://github.com/RobotLocomotion/drake/blob/94b4e9ae4412bbc9a0fe2427562c47edde51e95a/tools/workspace/drake_models/repository.bzl#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `78cad6a331aa0610e8f84e463d28103d096bdb83` is the new sha you want here now.
</blockquote></details>

What he said.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22321)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`tools/workspace/drake_models/repository.bzl` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22321#-OEKNuBD15wBUjepZyU1:-OEL0-HTCvh3vlyUg7ns:b-u8uujy) ([raw file](https://github.com/RobotLocomotion/drake/blob/94b4e9ae4412bbc9a0fe2427562c47edde51e95a/tools/workspace/drake_models/repository.bzl#L10)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

What he said.
</blockquote></details>

I believe done?
I think you guys mean the commit? I used the commit from the merge and asked bazel for the new checksum

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22321#-:-OEL3PnU9LEfwygMn6vw:bxqo58p)* status: 1 unresolved discussion

___
*[`tools/workspace/drake_models/repository.bzl` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22321#-OEKNuBD15wBUjepZyU1:-OEL3Gss-t1eG_335Oaw:b-cy5t64) ([raw file](https://github.com/RobotLocomotion/drake/blob/94b4e9ae4412bbc9a0fe2427562c47edde51e95a/tools/workspace/drake_models/repository.bzl#L10)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I believe done?
I think you guys mean the commit? I used the commit from the merge and asked bazel for the new checksum
</blockquote></details>

Yep. THe commit is *also* a sha. Just to keep things fun.  :)

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @amcastro-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22321)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
