### PR TITLE
Rod2d state vector

### PR DESCRIPTION
**Pull request by edrumwri**
Adds named state vectors to 2D rod, using the newly created mechanism from PR #7342.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7379)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@jwnimmer-tri for feature review please (i.e., hoping to see I am using this new paradigm properly)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-:-KxtUStzr90Ynzsr3fgd:b-ojxh2l)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

:lgtm: for what's here.  Is there a future plan to update the rod2d-inl and unit test use the new helper, instead of the current hard-coded indices?

+@soonho-tri for platform review.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/rod2d/BUILD.bazel, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-KxtV0nWkAv7P0zIVstE:-KxtV0nWkAv7P0zIVstF:b-hzy16y) ([raw file](https://github.com/robotlocomotion/drake/blob/c492ce8326231c36162970bde4a8109519818323/drake/examples/rod2d/BUILD.bazel#L9)):*
> ```
>     "drake_cc_binary",
> )
> load("//tools/install:install_data.bzl", "install_data")
> ```

I think this line is unused.

---

*[drake/examples/rod2d/rod2d.h, line 238 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-KxtXOr6ZNHGpdrmXZDy:-KxtXOr7IWUUQX2ro9mR:b1h8i5v) ([raw file](https://github.com/robotlocomotion/drake/blob/c492ce8326231c36162970bde4a8109519818323/drake/examples/rod2d/rod2d.h#L238)):*
> ```objc
>     return dynamic_cast<Rod2dStateVector<T>&>(
>         context->get_mutable_continuous_state_vector());
>   }
> ```

FYI These new functions are probably fine (not defective), but may not be the best approach to provide useful sugar to code that uses them.  It's hard to say without having them be used anywhere yet.

---

*[drake/examples/rod2d/rod2d_state_vector.named_vector, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-KxtVGXpkIANvW0iwRsJ:-KxtVGXqwbs2j3eQOfNv:b2u7p2j) ([raw file](https://github.com/robotlocomotion/drake/blob/c492ce8326231c36162970bde4a8109519818323/drake/examples/rod2d/rod2d_state_vector.named_vector#L1)):*
> ```
> namespace: "drake::examples"
> ```

Perhaps you want `drake::examples::rod2d` to match the namespace of the System that uses it?  (Or else a comment about why its different.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-:-KxtUzygWieYphPe9MnG:b-3pu6m7)*

**Comment by edrumwri** [comment]
Thanks for the fast review Jeremy. This code is actually getting freshened quite a bit as I'm using it to prototype the piecewise DAE simulation, and I'm aiming to make extensive use of it there.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/rod2d/BUILD.bazel, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-KxtV0nWkAv7P0zIVstE:-KxtbPGszolkCnp7yEbu:b-5cmj2m) ([raw file](https://github.com/robotlocomotion/drake/blob/c492ce8326231c36162970bde4a8109519818323/drake/examples/rod2d/BUILD.bazel#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this line is unused.
</blockquote></details>

Done. (Cargo cult programming in action)

---

*[drake/examples/rod2d/rod2d_state_vector.named_vector, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-KxtVGXpkIANvW0iwRsJ:-KxtbSlZKF4pX2fpUg-h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c492ce8326231c36162970bde4a8109519818323/drake/examples/rod2d/rod2d_state_vector.named_vector#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Perhaps you want `drake::examples::rod2d` to match the namespace of the System that uses it?  (Or else a comment about why its different.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-:-Kxtb6X35Jf5rG5Lmgom:b9z1t53)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7379)*

**Comment by soonho-tri** [comment]
:lgtm: (aside a BTW)

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/rod2d/rod2d_state_vector.named_vector, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-KxxChqgE0JGcnA2Kv3n:-KxxChqgE0JGcnA2Kv3o:b-cb5b5z) ([raw file](https://github.com/robotlocomotion/drake/blob/aaf7609e4bb0b15109116fe842a197744c6c6335/drake/examples/rod2d/rod2d_state_vector.named_vector#L5)):*
> ```
> element {
>      name: "x"
>      doc: "Horizontal location of the center-of-mass in meters."
> ```

BTW, there is a systematic way of providing 'unit' information. For example,

```c++
     doc: "Horizontal location of the center-of-mass."
     doc_units: "m"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-:-KxxDrAnE-8Ct-Q8SeOr:b-i8gkkc)*

**Comment by edrumwri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/rod2d/rod2d_state_vector.named_vector, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-KxxChqgE0JGcnA2Kv3n:-Kxxngr7QCrhLS0J6dr7:b-v2m3u1) ([raw file](https://github.com/robotlocomotion/drake/blob/aaf7609e4bb0b15109116fe842a197744c6c6335/drake/examples/rod2d/rod2d_state_vector.named_vector#L5)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, there is a systematic way of providing 'unit' information. For example,

```c++
     doc: "Horizontal location of the center-of-mass."
     doc_units: "m"
```


</blockquote></details>

Done. (This is excellent- thanks!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7379)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7379)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7379)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please

**Comment by edrumwri** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7379#-:-KxyXWNubcIJbMIIlDoX:bks4c2c)*

**Comment by soonho-tri** [comment]
All check passed.

**Pull request merged**
