### PR TITLE
adds get_variable_vector to symbolic expression. 

### PR DESCRIPTION
**Pull request by RussTedrake**
needed this to take Jacobians of my state vector (which is naturally a symbolic::Expression)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8600)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@soonho-tri for feature review, please.  (N.B. assigning via github as reviewable is not really working for me)

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[common/symbolic_expression.cc, line 843 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-LABuZhvEp9rzYcW1XfU:-LABuZhvEp9rzYcW1XfV:b5ga1eh) ([raw file](https://github.com/robotlocomotion/drake/blob/7577e42b195485f5e355a531adf740303427c891/common/symbolic_expression.cc#L843)):*
> ```cpp
>     const Eigen::Ref<const VectorX<Expression>>& evec) {
>   VectorX<Variable> vec(evec.size());
>   for (int i=0; i<evec.size(); i++) {
> ```

BTW, I think clang-format will put space before and after `=` and `<`.

---

*[common/test/symbolic_expression_matrix_test.cc, line 82 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-LABum02E5NvnJC_e_6L:-LABum02E5NvnJC_e_6M:b7etxg5) ([raw file](https://github.com/robotlocomotion/drake/blob/7577e42b195485f5e355a531adf740303427c891/common/test/symbolic_expression_matrix_test.cc#L82)):*
> ```cpp
>   EXPECT_EQ(vec(0), x_);
>   EXPECT_EQ(vec(1), y_);
>   EXPECT_EQ(vec(2), z_);
> ```

BTW, I think we should also add a test, that when `evec` is not a vector of variable expression, but instead `evec(i)` contains more than variables, `get_variable_vector` will throw an error.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[common/symbolic_expression.cc, line 843 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-LABuZhvEp9rzYcW1XfU:-LAC8C2c5Wh0dWgyfAvh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7577e42b195485f5e355a531adf740303427c891/common/symbolic_expression.cc#L843)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, I think clang-format will put space before and after `=` and `<`.
</blockquote></details>

Done.

---

*[common/test/symbolic_expression_matrix_test.cc, line 78 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-LABsp8T5Xx7jx28SyxP:-LAC8Q9xDuCjxDMpUa8Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7577e42b195485f5e355a531adf740303427c891/common/test/symbolic_expression_matrix_test.cc#L78)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, CI is unhappy because of this line:

```
18:05:39 common/test/symbolic_expression_matrix_test.cc:78:  Missing space after ,  [whitespace/comma] [3]
18:05:39 Done processing common/test/symbolic_expression_matrix_test.cc
18:05:39 Total errors found: 1
```

Also, nit, 
```c++
const Vector3<Expression> evec(x_, y_, z_);
const VectorX<Variable> vec = get_variable_vector(evec);
```
</blockquote></details>

Done.

---

*[common/test/symbolic_expression_matrix_test.cc, line 82 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-LABum02E5NvnJC_e_6L:-LAC9deDDthIrCjynEZG:b-nsazog) ([raw file](https://github.com/robotlocomotion/drake/blob/7577e42b195485f5e355a531adf740303427c891/common/test/symbolic_expression_matrix_test.cc#L82)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, I think we should also add a test, that when `evec` is not a vector of variable expression, but instead `evec(i)` contains more than variables, `get_variable_vector` will throw an error.
</blockquote></details>

while I definitely agree, i think the error handling should be deeper in symbolic than at this function level.  (e.g. down at `to_variable()`).  There is no error handling nor unit tests down at that level, either.  Currently it segfaults if bad input is passed in.  @soonho-tri -- would you please add that to_variable?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[common/test/symbolic_expression_matrix_test.cc, line 82 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-LABum02E5NvnJC_e_6L:-LADD3zO9SNuN16G1Qid:bnpif6l) ([raw file](https://github.com/robotlocomotion/drake/blob/7577e42b195485f5e355a531adf740303427c891/common/test/symbolic_expression_matrix_test.cc#L82)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

while I definitely agree, i think the error handling should be deeper in symbolic than at this function level.  (e.g. down at `to_variable()`).  There is no error handling nor unit tests down at that level, either.  Currently it segfaults if bad input is passed in.  @soonho-tri -- would you please add that to_variable?
</blockquote></details>

```c++
/// \pre{@p evec is a vector of variable expressions.}
VectorX<Variable> get_variable_vector...
```

Isn't it the caller's responsibility to check if a precondition holds or not? (instead of a callee). I can add `bool is_variable_vector` if it helps.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test/symbolic_expression_matrix_test.cc, line 82 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-LABum02E5NvnJC_e_6L:-LAEzMic8Sj1v942T7TW:b54uj31) ([raw file](https://github.com/robotlocomotion/drake/blob/7577e42b195485f5e355a531adf740303427c891/common/test/symbolic_expression_matrix_test.cc#L82)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

```c++
/// \pre{@p evec is a vector of variable expressions.}
VectorX<Variable> get_variable_vector...
```

Isn't it the caller's responsibility to check if a precondition holds or not? (instead of a callee). I can add `bool is_variable_vector` if it helps.
</blockquote></details>

ok, but wouldn't you list the same defect on your get_variable method?  (which my method is only a small wrapper around)?  at least that method should be guarded and covered with tests?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600)*

**Comment by soonho-tri** [comment]
+@hongkai-dai, since you're here, can you be the feature-reviewer (so that I can be a platform)?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test/symbolic_expression_matrix_test.cc, line 82 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-LABum02E5NvnJC_e_6L:-LAF-zBv-YSnO6Dp823M:b-hkh32i) ([raw file](https://github.com/robotlocomotion/drake/blob/7577e42b195485f5e355a531adf740303427c891/common/test/symbolic_expression_matrix_test.cc#L82)):*
> at least that method should be guarded and covered with tests?

OK. I'll add them (as a separate PR)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-:-LAF09cT71VF17cUG_4k:b-6a9s7z)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-:-LAF1fQLBcpmwgvdzX6P:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[common/test/symbolic_expression_matrix_test.cc, line 82 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600#-LABum02E5NvnJC_e_6L:-LAF7IAyDsjRrvRPt-A4:bsvk6yy) ([raw file](https://github.com/robotlocomotion/drake/blob/7577e42b195485f5e355a531adf740303427c891/common/test/symbolic_expression_matrix_test.cc#L82)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> at least that method should be guarded and covered with tests?

OK. I'll add them (as a separate PR)
</blockquote></details>

FYI As a general rule, preconditions need not be unit tested.  That the symbolic casting methods assume you've checked the type before casting seems a-ok to me, and don't need any additional testing.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8600)*

**Pull request merged**
