### PR TITLE
geometry_visualization: Add optional prefix for LCM channels

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12702)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Counter-proposal: instead of offering only `DispatchLoadMessage` as the public API, also offer `BuildLoadMessage` as non-internal.  Then, downstream users can put the pieces together any way they want -- using completely different channel names instead of just prefixes, or logging the message for later transmission (replay), or changing the public frequency, etc.

Having an API in Drake without also providing the `class ModifiedDrakeVisualizer(DrakeVisualizer)` hack that makes it work correctly is just walking users off a cliff.

**Comment by jwnimmer-tri** [comment]
If `BuildLoadMessage` is available, then downstream we'd not call `ConnectDrakeVisualizer` but  instead write up the pieces.  The `ConnectDrakeVisualizer` is supposed to be sugar for the common case.  For bespoke use cases, we can copy those few extra lines expressing exactly what we want.

**Comment by EricCousineau-TRI** [comment]
I would prefer to timebox this, and not spend any more of my time on it. As a user, I'd personally prefer this slightly messy wrap-up, rather than end up implementing the same thing in Anzu.

I'd be up for doing a more proper version later and deprecating this, but not anytime in the near future.

**Comment by EricCousineau-TRI** [comment]
@naveenoid I may let this sit now, and we can wait til there's more pressure to either (a) merge in this hack version or (b) do the more principled form that Jeremy mentioned.

**Comment by EricCousineau-TRI** [comment]
Closing this for now.

**Pull request closed without merging**
