### PR TITLE
Improve RigidBodyTree template methods linking

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For transformPoints and transformPointsJacobian, we should support passing in any double-valued point(s) we want, without having to explicitly do a Map or Block dance.  By placing a Derived-to-Ref conversion into the header file, we only need to instantiate a couple concrete function types in the cc file.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8446)

### CODE REVIEW

**Comment by RussTedrake** [comment]
- the AutodiffUpTo73d is important to remember about, but i agree it is not currently used.  
- There is a chance that any/every use of Map is only a hold-over from the matlab bindings.  (We used to Map onto matlab-allocated memory).  Are we actually using them anywhere now?
- agree that using Ref instead of templates whenever possible is only good

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8446#-:-L8K5_NvoTQrWKSYwo43:bcktefe)*

**Comment by jwnimmer-tri** [comment]
> the AutodiffUpTo73d is important to remember about, but i agree it is not currently used.

Yeah.  I imagine that chunking autodiff will come to MultibodyTree.  That seems the place worth more investing in.

> There is a chance that any/every use of Map is only a hold-over from the matlab bindings. (We used to Map onto matlab-allocated memory). Are we actually using them anywhere now?

I have some vague memory that certain call sites were using them in a way similar to a Ref, in order to make things link without error.  In any case, the technique in (the last commit of) this PR removes them for any methods we port to over to it, because all inputs are always Ref's.

> agree that using Ref instead of templates whenever possible is only good

That's great.  I will let the AD73d change percolate in case there are objections and then merge next week, and then I can return here to get the Ref improvements landed.

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai could you feature review, please?

**Comment by hongkai-dai** [comment]
:lgtm: +@soonho-tri for platform review please.

---

Reviewed 2 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[multibody/rigid_body_tree.h, line 815 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-L8niVDV1-Z-2Lb_mpdb:-L8niVDV1-Z-2Lb_mpdc:b-13dmnr) ([raw file](https://github.com/robotlocomotion/drake/blob/cb353fdde398699de0fcb3a9c830e75047f75ddf/multibody/rigid_body_tree.h#L815)):*
> ```objc
>     return DoTransformPointsJacobian<Scalar, PointScalar>(
>         cache,
>         points.template cast<PointScalar>().eval(),
> ```

If we want to support `AutoDiffUpTo6d` or something alike in the future, how shall we handle it here? Now we can only support `double` and `AutoDiffXd`.

---

*[multibody/rigid_body_tree.h, line 845 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-L8nikvGBqSbie9azbAL:-L8nikvGBqSbie9azbAM:bch9ljv) ([raw file](https://github.com/robotlocomotion/drake/blob/cb353fdde398699de0fcb3a9c830e75047f75ddf/multibody/rigid_body_tree.h#L845)):*
> ```objc
>       int from_body_or_frame_ind, int to_body_or_frame_ind) const {
>     return DoTransformPointsJacobianDotTimesV<Scalar>(
>         cache, points, from_body_or_frame_ind, to_body_or_frame_ind);
> ```

So unlike `transformPointsJacobian`, we do not cast `points` to `PointScalar` type here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-:-L8njiy377r5jNLzM-KQ:b-mkkz8q)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[multibody/rigid_body_tree.h, line 815 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-L8niVDV1-Z-2Lb_mpdb:-L8o73VH0ye7qDx0Qt0d:bkmt34m) ([raw file](https://github.com/robotlocomotion/drake/blob/cb353fdde398699de0fcb3a9c830e75047f75ddf/multibody/rigid_body_tree.h#L815)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If we want to support `AutoDiffUpTo6d` or something alike in the future, how shall we handle it here? Now we can only support `double` and `AutoDiffXd`.
</blockquote></details>

If the, e.g., `points` here are passed in as AutoDiffUpTo6d, then as it stands in this PR we would copy them into AutoDiffXd (at least, I suspect Eigen forces a copy -- it might be smart enough to avoid it, but that would be a little bit magical), and then call the Do helper to do the computation using Xd.  So right now UpTo6d is "supported" but maybe not fast, maybe even slower.

If we wanted to do a speedup by using UpTo6d in the implementation, we would have to (1) add an explicit template method instantiation in the cc file and then (2) change this function body to have an if-statement that called either the UpTo6d or the Xd expansion of the Do helper, depending on which one was most appropriate.  Probably we'd do this with the ...AtCompileTime number, though you could imagine copying Xd points where all of their  `.derivatives.size()` fit in UpTo6d and then calling the UpTo6d helper for a speedup.

That all being said, with the sunsetting of RBT my hope is to never have to do that for this class, but rather to focus on the template signatures of MBT and friends in order to find the most appropriate speedups there.

---

*[multibody/rigid_body_tree.h, line 845 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-L8nikvGBqSbie9azbAL:-L8o6UWHDNK98XDCYGzA:b-s9alo3) ([raw file](https://github.com/robotlocomotion/drake/blob/cb353fdde398699de0fcb3a9c830e75047f75ddf/multibody/rigid_body_tree.h#L845)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

So unlike `transformPointsJacobian`, we do not cast `points` to `PointScalar` type here?
</blockquote></details>

In the prior explicit template method instantiations of TransformPointsJacobianDotTimesV, the points never had gradients -- always just doubles.  I've preserved that here -- the points must always be double-valued, without any gradients.

I assumed no-gradients was intrinsic to the nature of the computation's intended uses.  I could add support

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_tree.h, line 815 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-L8niVDV1-Z-2Lb_mpdb:-L8pZ6tU9JY5gnjBCcVF:bje2tdm) ([raw file](https://github.com/robotlocomotion/drake/blob/cb353fdde398699de0fcb3a9c830e75047f75ddf/multibody/rigid_body_tree.h#L815)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If the, e.g., `points` here are passed in as AutoDiffUpTo6d, then as it stands in this PR we would copy them into AutoDiffXd (at least, I suspect Eigen forces a copy -- it might be smart enough to avoid it, but that would be a little bit magical), and then call the Do helper to do the computation using Xd.  So right now UpTo6d is "supported" but maybe not fast, maybe even slower.

If we wanted to do a speedup by using UpTo6d in the implementation, we would have to (1) add an explicit template method instantiation in the cc file and then (2) change this function body to have an if-statement that called either the UpTo6d or the Xd expansion of the Do helper, depending on which one was most appropriate.  Probably we'd do this with the ...AtCompileTime number, though you could imagine copying Xd points where all of their  `.derivatives.size()` fit in UpTo6d and then calling the UpTo6d helper for a speedup.

That all being said, with the sunsetting of RBT my hope is to never have to do that for this class, but rather to focus on the template signatures of MBT and friends in order to find the most appropriate speedups there.
</blockquote></details>

Thanks for the explanation! All makes sense.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-:-L8pZFZC2v_LSGq-UEX4:b6vi582)*

**Comment by soonho-tri** [comment]
-@soonho-tri , punting it to @sherm1 (I'm on leave today).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-:-L8q7Dab9ys8luDz10NV:bfwa9dy)*

**Comment by sherm1** [comment]
Platform :lgtm: pending one BTW.

---

Reviewed 2 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_tree.h, line 1675 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-L8sV3iv57gt-1GlDuzz:-L8sV3iv57gt-1GlDv--:b13ncth) ([raw file](https://github.com/robotlocomotion/drake/blob/cb353fdde398699de0fcb3a9c830e75047f75ddf/multibody/rigid_body_tree.h#L1675)):*
> ```objc
>   RigidBodyTree& operator=(const RigidBodyTree&) { return *this; }
> 
>   template <typename Scalar, typename PointScalar>
> ```

BTW these private methods need a short `//` comment or self-documenting parameter names for the mysterious `int, int, bool` to allow eyeball inspection of the call sites above.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-:-L8sVcOY7-1PiqDE-py0:bwodqt4)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_tree.h, line 1675 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446#-L8sV3iv57gt-1GlDuzz:-L8sbYml7BZanTvQQYtm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cb353fdde398699de0fcb3a9c830e75047f75ddf/multibody/rigid_body_tree.h#L1675)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW these private methods need a short `//` comment or self-documenting parameter names for the mysterious `int, int, bool` to allow eyeball inspection of the call sites above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8446)*

**Pull request merged**
