### PR TITLE
Speedup MathematicalProgram::NewFreePolynomial.

### PR DESCRIPTION
**Pull request by hongkai-dai**
1. Construct the polynomial using map instead of adding each terms.
2. Use Variables.insert instead of += to avoid redundant copying

Before this PR, BenchmarkSosProgram3 takes 14.5s. After this PR it takes 7.1s on my Puget.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17011)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

This PR is not urgent at all, feel free to postpone it to next week.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17011#-:-N0CHgKiCg2BICEp2y8j:b-pko6se)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17011#-:-N0ChMEWDJld-xTCeS9l:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/benchmarking/benchmark_mathematical_program.cc, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17011#-N0CgkCgD814-ZIU4Fud:-N0CgkCh4sgE6RUbpNkx:bly1xoc) ([raw file](https://github.com/robotlocomotion/drake/blob/263ae965b8ef8351740a93df1c682e377f4ac4ac/solvers/benchmarking/benchmark_mathematical_program.cc#L81)):*
> ```cpp
> }
> 
> static void BenchmarkSosProgram3(benchmark::State& state) {  // NOLINT
> ```

It seems to me like this benchmark is a subset of case 1 or 2 above (i.e., that creating the free polynomials is already covered there), and that a user would not usually call this function on its own, rather only as part of an overall program set-up.  Is that correct?

If that's true, that I'd rather we keep only 1 and 2 around, and report the overall speed-up of this change on those two cases, even if it's modest.

If the speed-up from this change is on par with the measurement noise of those benchmarks, that would be a reason to give it its own micro-benchmark, but in that situation I wonder if we need a micro-benchmark in any case.  The code is obviously better via code inspection, even without benchmark results.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17011)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/benchmarking/benchmark_mathematical_program.cc, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17011#-N0CgkCgD814-ZIU4Fud:-N0CiRS6Bht5PwQaSQKB:b-ecxr9i) ([raw file](https://github.com/robotlocomotion/drake/blob/263ae965b8ef8351740a93df1c682e377f4ac4ac/solvers/benchmarking/benchmark_mathematical_program.cc#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems to me like this benchmark is a subset of case 1 or 2 above (i.e., that creating the free polynomials is already covered there), and that a user would not usually call this function on its own, rather only as part of an overall program set-up.  Is that correct?

If that's true, that I'd rather we keep only 1 and 2 around, and report the overall speed-up of this change on those two cases, even if it's modest.

If the speed-up from this change is on par with the measurement noise of those benchmarks, that would be a reason to give it its own micro-benchmark, but in that situation I wonder if we need a micro-benchmark in any case.  The code is obviously better via code inspection, even without benchmark results.
</blockquote></details>

Yes, it's true that we already call NewFreePolynomial in case 1 and 2, but that's for small size polynomials, and the time spent on NewFreePolynomial is negligible in case 1 and 2. In 3 we construct a large free polynomial which shows up the speed bottleneck within NewFreePolynomial.

I think it is a good idea to remove case 3.

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17011#-:-N0CjCzL2cLGRLTF1kP7:bi4se7j)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17011)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> BenchmarkSosProgram3

I see BenchmarkSosProgram{1,2}, but not 3. I didn't easily find it in your open PRs.
Is this in another PR, or in a dev branch?

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17011#-:-N0CpCmg3kVxPDhH4NWn:be3ctdn)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
> I see BenchmarkSosProgram{1,2}, but not 3. I didn't easily find it in your open PRs.
> Is this in another PR, or in a dev branch?

It was in r1 of this pull request, but we decided that is wasn't worth permanently committing.

**Pull request merged**
