### PR TITLE
Emulate discrete output ports for MbP

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #20545 
Closes #20531

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
cc @amcastro-tri @sherm1 related to our discussion.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-:-NjmvDbW-H0Cbl5YsBox:b-19u9gv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
This now clears both Drake and Anzu CI and I think it's ready for a design review. I can come back to round up my TODO's in the PR once we agree this is the right fix.
+@sherm1 for review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-:-Njofqo-1YQ4_Yc5V8wQ:b-3mx9ib)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
A few thoughts:
- thanks for tackling this, Xuchen!
- using the event system just to make a call to the Reset method seems awkward and unnecessary. My thought now would be just to add a bespoke API with a nice name and documentation.
- there are lots of dependency changes here including most notably removal of dependency on xd. I'm wondering what the consequences of that are? Is this a breaking change in the sense that someone setting xd manually in the Context previously would see it reflected in the outputs and now they won't?
- several instances of renaming and reordering made it a little hard to see exactly what changed. Consider doing the renaming and reordering in a separate yak shave PR so that the important changes are very clear in this one.

+@amcastro-tri for additional design/feature review

> Reviewed 4 of 8 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-:-NjsWPbL8desuR7lkaAa:bldyx3v)* status: 5 unresolved discussions, LGTM missing from assignees sherm1(platform),amcastro-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

___
*[`multibody/plant/discrete_update_manager.cc` line 45 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-NjsV2U52XvzZiHGrvQl:-NjsV2U52XvzZiHGrvQm:b90cn2i) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4c667c30530a9ee45376bbd1493eb81d96070bd/multibody/plant/discrete_update_manager.cc#L45)):*
> ```cpp
>   DoCalcDiscreteValues(context, updates);
> 
>   // Make sure the discrete ouput port values are sampled.
> ```

typo: ouput -> output
___
*[`multibody/plant/multibody_plant.h` line 5578 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-NjsRVYm-ATepNQjoPG1:-NjsRVYm-ATepNQjoPG2:b-pz31i4) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4c667c30530a9ee45376bbd1493eb81d96070bd/multibody/plant/multibody_plant.h#L5578)):*
> ```objc
>   // @pre `this` MultibodyPlant is discrete.
>   // @pre caching is enabled for the given `context`.
>   systems::EventStatus ResetDiscretePorts(
> ```

BTW consider a more descriptive name for this function, something like `InvalidateDependentsOfDiscretePorts()`
___
*[`multibody/plant/sap_driver.cc` line 94 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-NjsTUERE5kD6V6n_SIe:-NjsTUERE5kD6V6n_SIf:b-pakdzn) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4c667c30530a9ee45376bbd1493eb81d96070bd/multibody/plant/sap_driver.cc#L94)):*
> ```cpp
>   // the `plant().all_input_ports_ticket()`.
>   const std::set<systems::DependencyTicket> discrete_signal_and_parameters = {
>       discrete_signal_ticket, parameters_ticket};
> ```

BTW not obvious to me why there is no longer a dependency on xd. Is there a circumstance in which a manual change to xd would fail to cause an update? Or does the new discrete signal dependency cover all cases? Assuming this is correct, please add a comment explaining xd's absence like you did for the input port.
___
*[`multibody/plant/test/discrete_update_manager_test.cc` line 514 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-NjsVpB18E8w3xRX0Vv2:-NjsVpB18E8w3xRX0Vv3:bot170z) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4c667c30530a9ee45376bbd1493eb81d96070bd/multibody/plant/test/discrete_update_manager_test.cc#L514)):*
> ```cpp
>   EXPECT_EQ(net_u(0), 1.0);
>   // Since the plant is discrete, changing the input port value isn't
>   // immediately reflected in the output port.
> ```

Since dependencies on xd have also been removed, I'm expecting that manual changes to xd will also fail to be reflected in the output ports without manual invalidation. Is that correct? If so would be good to included that behavior in the test as well.
___
*[`multibody/plant/test/discrete_update_manager_test.cc` line 520 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-NjsUJXwCiIRBC-B3b5-:-NjsUJXwCiIRBC-B3b50:beg3m51) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4c667c30530a9ee45376bbd1493eb81d96070bd/multibody/plant/test/discrete_update_manager_test.cc#L520)):*
> ```cpp
>   // The force publish flushes discrete port values and the output port value
>   // should match the input port values again.
>   plant.ForcedPublish(*plant_context);
> ```

BTW this seems too obscure. All this is really accomplishing is to make a call to ResetDiscretePorts() in a roundabout way. My thought is that rather than using the event system, why not just add an API `plant.ResampleDiscretePorts()` or something like that?

**Comment by xuchenhan-tri** [comment]
*[`multibody/plant/sap_driver.cc` line 94 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-NjsTUERE5kD6V6n_SIe:-NkHw3sABwnXC9OTkKjw:bwwnvg4) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4c667c30530a9ee45376bbd1493eb81d96070bd/multibody/plant/sap_driver.cc#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW not obvious to me why there is no longer a dependency on xd. Is there a circumstance in which a manual change to xd would fail to cause an update? Or does the new discrete signal dependency cover all cases? Assuming this is correct, please add a comment explaining xd's absence like you did for the input port.
</blockquote></details>

The change of the dependency on xd is subtle. I should have made it more clear.

Dependency on xd prevents reuse of the expensive computation of contact solver results. In a discrete MbP in a simulator, we know that the contact solver result is computed at **least** once in the discrete update in a time step. If, for speed purpose, we also want to limit that computation to at **most** once per time step, then that computation can't happen anywhere else. As a corollary, contact solver result cannot depend on xd, because we need to control precisely when that computation happens with the `discrete_signal`.

Now the more interesting question is, should we label xd as a dependency for output ports that depends both on contact solver results and the discrete state. The prime example of that is contact results. In that particular case, we can't label xd as a dependency because the computation there depends heavily on the assumption that the discrete states and the contact solver results are compatible, and a slightly out-of-date contact solver results will usually cause a throw.

If we are dropping the dependency on xd for one output port, then the logical thing would be to drop it for all output ports that depend on both contact solver results and xd. But that of course, as you observed, would be a breaking change, because now modifying the discrete state does not trigger a recompute for the output port values.

**Comment by xuchenhan-tri** [comment]
Please see the thread below for a discussion on the removal of dependency on xd. It is subtle and I should have made the removal more clear.

I'm starting to think that we are introducing too much complexity/breaking change to achieve the goal of not triggering the contact solver computation when pulling on certain output port. Would it be better if we keep all the existing behavior (and the dependency on xd), and for now simply add a new "discrete" output port for contact results that promises not to trigger a contact solver result computation. Other "discrete" output ports can be added in the future as needed.

**Review by amcastro-tri — COMMENTED** [review]
> I'm starting to think that we are introducing too much complexity/breaking change

IMO, yes. Or at least this doesn't match the mental picture I had after last week's conversation.

> .. and for now simply add a new "discrete" output port for contact results

Could you ellaborate more on what you mean by that? do mean this idea of having a cached entry to emulate "output state"?
When inside the simulation, I think that'd work nicely. Outside simulation, users would need to call `ForcedPublish()` to see changes in the outputs due to changes in the inputs (say they did a `FixValue()`).

> Reviewed 1 of 8 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-:-NkQvh2A81XCWy67pA63:b-xjw2q5)* status: 5 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
btw, let me join Sherm on this. Thank you so much for working on this Xuchen, it's clearly a very difficult problem. I feel like we are finally making good progress though.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-:-NkQwzsj0wLJdCoRa1pj:b-u85pan)* status: 5 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Per f2f w/Xuchen, I like his idea of adding a "discrete" contact results port for simulation use that guarantees not to do unnecessary computation, but at the expense of being slightly out of date due to use of the result most recently calculated by SAP. The current port would remain the one users should Eval if they want an up-to-date result during out-of-simulator execution. This solves Amazon's problem, avoids breaking changes, and minimizes the necessary MbP changes.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-:-NkR8rST6Rop9u7PdfHA:blfvt7h)* status: 5 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
> ... but at the expense of being slightly out of date due to use of the result most recently calculated by SAP.

What do you mean by that @sherm1? as stated it'd seem like a breaking change. Could you ellaborate?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-:-NkRWCAdBqAT8oQM0krR:b-31lyde)* status: 5 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
It's not a breaking change because the "discrete" results port doesn't yet exist. The old "continuous" results port would continue to exist with the same name and implementation so anyone currently using that port won't see a change. But users could opt-in to the new behavior by connecting to the discrete port.  OTOH, we should switch the visualizer to use the new discrete port to avoid slowdowns caused by contact visualization. That could be viewed as a kind of breaking change but I don't think anyone would notice during visualization.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-:-NkRZTGD0jBg_mtgZM6P:b8658j2)* status: 5 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Comment by xuchenhan-tri** [comment]
@sherm1 thanks for the elaboration, that's exactly it. I'm working on a draft PR so we have concrete code to discuss over. I'm leaning towards a fresh PR so that the existing diffs aren't muddling the water.

**Review by xuchenhan-tri — COMMENTED** [review]
=>https://github.com/RobotLocomotion/drake/pull/20609

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20568#-:-NkSYimG9o15EEohPbvS:bpumx8d)* status: 5 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Pull request closed without merging**
