### PR TITLE
Polished AutomotiveSimulator some.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5671)

### CODE REVIEW

**Comment by liangfok** [comment]
+@rpoyner-tri for feature review please.
+@soonho-tri for platform review please.
+@jwnimmer-tri for car review please.

Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5671#-:-KgVfIvg9TBdXszXFivY:b-z86g00)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5671#-:-KgVpP6Ql3Ek-D-_ttCL:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:car: awoooooogah

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5671#-:-KgWmLh2RttCH_godA18:b-3yf25p)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5671#-:-KgX5zcZOwgAUeleQrlq:bnfp4nl)*

**Pull request merged**
