### PR TITLE
Add /tools/skylark folder; move drake_py and pathutils there

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.  Tweaks #7243.

The goal here is to make `/tools` itself relatively thin, putting most features into subdirectories.

We also don't want to have a single `drake.bzl` that has all `drake_*` macros, because then we get dependency bleeding: with a single bzl file, C++ code would need to have load-time access to Python helpers, which can induce extra load-time dependencies.  Keeping dependencies thin will help with #7259.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7277)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for feature review please, as a follow-up from #7243.
+@sammy-tri for platform review please, per rotation.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 13 of 13 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7277#-:-KwelrDajvyWNREOmaN9:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 13 of 13 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7277#-:-KwesoBuQMSUwsbi23nt:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Self-:car:-approved for boilerplate change.

**Pull request merged**
