### PR TITLE
[tools] Start a from-scratch Python reimplementation of lcm_gen

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For now, this is just the `*.lcm` file parser. The codegen is deferred to a future commit (#20761).

The book https://craftinginterpreters.com/ is a spectacularly good guide about how a recursive descent parser works.  Highly recommended.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20762)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20762)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Comment by sherm1** [comment]
Is this ready to have a feature reviewer assigned, @jwnimmer-tri ?

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please and thank you!  (If you can't finish by end of next week, LMK and I'll find a new recruit.)

**Comment by ggould-tri** [comment]
I'm surprised you didn't use `lark` or `lrparser` for this.  What's the reason (if it's other than "it's a lot of fun!") for rolling your own?

**Comment by jwnimmer-tri** [comment]
In #20761, I posted some background.  In particular, I'm aiming to depend only on the Python 3 standard library.

Also, broadly speaking a recursive descent parser should be easier to work with over the long term, e.g., to tweak it to provide more contextual error messages when things to wrong, compared to a parser generator.

**Review by jwnimmer-tri — COMMENTED** [review]
Oops, I didn't notice it was a discussion thread.  I'll re-post it there.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-:-Nnug6XZ7-xuQSw9FhB6:bowph3r)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NnuWa4C9_wS9z9RfnEp:-Nnug9Yq1d0aKd7ELgZf:bqsk92f) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I'm surprised you didn't use `lark` or `lrparser` for this.  What's the reason (if it's other than "it's a lot of fun!") for rolling your own?
</blockquote></details>

In #20761, I posted some background.  In particular, I'm aiming to depend only on the Python 3 standard library.

Also, broadly speaking a recursive descent parser should be easier to work with over the long term, e.g., to tweak it to provide more contextual error messages when things to wrong, compared to a parser generator.  The actual _parser_ part of this (the calls to "consume") is maybe 200 lines at most.  All of the other infra would still be needed even with a parser generator.

___

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; moderate quibbles mostly optional.

> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-:-NoIE8zDBfMu4Wzu84sM:b8u241u)* status: 7 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NnuWa4C9_wS9z9RfnEp:-NoI4vg91hccf_dcMpbC:b43kovw) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In #20761, I posted some background.  In particular, I'm aiming to depend only on the Python 3 standard library.

Also, broadly speaking a recursive descent parser should be easier to work with over the long term, e.g., to tweak it to provide more contextual error messages when things to wrong, compared to a parser generator.  The actual _parser_ part of this (the calls to "consume") is maybe 200 lines at most.  All of the other infra would still be needed even with a parser generator.
</blockquote></details>

Hmm, I guess that makes sense, even if it's not how I would have approached it.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoIDcBX7P9tsQI9U1J5:-NoIDcBX7P9tsQI9U1J6:b-jouhl7) (no related file):*
BTW:  Consider (maybe in a future PR) including the example LCM files in https://lcm-proj.github.io/lcm/content/lcm-type-ref.html and https://github.com/lcm-proj/lcm/tree/master/examples/types as a smoke test corpus.

___
___
*[`tools/lcm_gen/__init__.py` line 5 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoIAZq5AqlFGepo0dGL:-NoIAZq5AqlFGepo0dGM:b-i5d1m3) ([raw file](https://github.com/RobotLocomotion/drake/blob/a147f5eb1c6907d84bf75a9b0e6216702f29b647/tools/lcm_gen/__init__.py#L5)):*
> ```Python
> 
> For the LCM syntax and encoding specification, refer to:
>  https://lcm-proj.github.io/type_specification.html
> ```

minor:  This link is a 404.  I believe you want the one below.



_Suggestion:_
```Python
https://lcm-proj.github.io/lcm/content/lcm-type-ref.html
```
___
*[`tools/lcm_gen/__init__.py` line 20 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoI8kK4BerfYrU1-ELR:-NoI8kK4BerfYrU1-ELS:b-f9fdxz) ([raw file](https://github.com/RobotLocomotion/drake/blob/a147f5eb1c6907d84bf75a9b0e6216702f29b647/tools/lcm_gen/__init__.py#L20)):*
> ```Python
> #
> # Productions:
> #  root -> package_decl? struct_decl ;
> ```

afaict this disagrees with the lcmgen parser; see https://github.com/lcm-proj/lcm/blob/v1.4.0/lcmgen/lcmgen.c#L803-L806 that permits any number of "entity" (root-level) statements in a file.
___
*[`tools/lcm_gen/__init__.py` line 31 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoI9L7zEfXN_pHUX40O:-NoI9L7zEfXN_pHUX40P:bwg8swx) ([raw file](https://github.com/RobotLocomotion/drake/blob/a147f5eb1c6907d84bf75a9b0e6216702f29b647/tools/lcm_gen/__init__.py#L31)):*
> ```Python
> #  array_dim -> ( integer | identifier );
> #  qualified_identifier -> ( identifier DOT )? identifier ;
> #
> ```

This seems to omit the lcm "enum" construct, https://github.com/lcm-proj/lcm/blob/v1.4.0/lcmgen/lcmgen.c#L775-L779

Enum doesn't seem to be a documented feature, so a comment to that effect is probably quite adequate.
___
*[`tools/lcm_gen/__init__.py` line 49 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoI9tbgBJhmGFJqU7dq:-NoI9tbh-gZJN0q5GuPk:b-v89v4v) ([raw file](https://github.com/RobotLocomotion/drake/blob/a147f5eb1c6907d84bf75a9b0e6216702f29b647/tools/lcm_gen/__init__.py#L49)):*
> ```Python
> 
> 
> @dataclasses.dataclass(frozen=True)
> ```

minor:  For consistency, I believe the other construction classes can be frozen as well.
___
*[`tools/lcm_gen/__init__.py` line 132 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoIC8cu5lMjLc3sbWtA:-NoIC8cu5lMjLc3sbWtB:b56u7v7) ([raw file](https://github.com/RobotLocomotion/drake/blob/a147f5eb1c6907d84bf75a9b0e6216702f29b647/tools/lcm_gen/__init__.py#L132)):*
> ```Python
> 
>     @staticmethod
>     def _remove_c_comments(data):
> ```

BTW:  LCM saves off the last comment before an entity in order to re-emit it in the generated code (e.g. as a docstring)
https://github.com/lcm-proj/lcm/blob/v1.4.0/lcmgen/lcmgen.c#L742
It's probably worth commenting that you don't do that, or even todoing it.

(fwiw I'm very suspicious of the correctness of this logic in lcmgen in the multi-entity case, so I'm hesitant to say you should replicate it.)

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20762)* status: 7 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/lcm_gen/__init__.py` line 132 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoIC8cu5lMjLc3sbWtA:-NoIPLUp2_dEqGaxs56U:b-gw6lkf) ([raw file](https://github.com/RobotLocomotion/drake/blob/a147f5eb1c6907d84bf75a9b0e6216702f29b647/tools/lcm_gen/__init__.py#L132)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  LCM saves off the last comment before an entity in order to re-emit it in the generated code (e.g. as a docstring)
https://github.com/lcm-proj/lcm/blob/v1.4.0/lcmgen/lcmgen.c#L742
It's probably worth commenting that you don't do that, or even todoing it.

(fwiw I'm very suspicious of the correctness of this logic in lcmgen in the multi-entity case, so I'm hesitant to say you should replicate it.)
</blockquote></details>

Ah, afacit LCM no longer uses the saved comment, and the elaborate and sketchy logic to save it is dead code.  So this can be ignored.

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per schedule, please.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-:-NoIjoQG7NaWmcMwWTa-:b-z0s7k5)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoIDcBX7P9tsQI9U1J5:-NoIjV-z0C-i47yqT0Ca:bdxt3m9) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  Consider (maybe in a future PR) including the example LCM files in https://lcm-proj.github.io/lcm/content/lcm-type-ref.html and https://github.com/lcm-proj/lcm/tree/master/examples/types as a smoke test corpus.
</blockquote></details>

One of the goals here is to avoid LGPL infection, so I'm inclined instead to add our own novel test cases that cover everything we care about.  If you see anything missing in our tests, let me know.

___
___
*[`tools/lcm_gen/__init__.py` line 20 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoI8kK4BerfYrU1-ELR:-NoIj4oU4HC5q7diz_2Q:bfip4kf) ([raw file](https://github.com/RobotLocomotion/drake/blob/a147f5eb1c6907d84bf75a9b0e6216702f29b647/tools/lcm_gen/__init__.py#L20)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

afaict this disagrees with the lcmgen parser; see https://github.com/lcm-proj/lcm/blob/v1.4.0/lcmgen/lcmgen.c#L803-L806 that permits any number of "entity" (root-level) statements in a file.
</blockquote></details>

I wrote the my code using only the documentation, without looking at the existing C code, so I guess I missed that detail.

I've fixed the grammar here and added a comment to the parser to explain its 1-struct current limitation.
___
*[`tools/lcm_gen/__init__.py` line 31 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoI9L7zEfXN_pHUX40O:-NoIhQY48sCpsejnmC3O:b-zahftv) ([raw file](https://github.com/RobotLocomotion/drake/blob/a147f5eb1c6907d84bf75a9b0e6216702f29b647/tools/lcm_gen/__init__.py#L31)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This seems to omit the lcm "enum" construct, https://github.com/lcm-proj/lcm/blob/v1.4.0/lcmgen/lcmgen.c#L775-L779

Enum doesn't seem to be a documented feature, so a comment to that effect is probably quite adequate.
</blockquote></details>

The `enum` syntax was never documented, and anyway has been deprecated since 2008.  I added a comment.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20762)* status: LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-NoIDcBX7P9tsQI9U1J5:-NoIlOYC3bjle8rULVR1:b-9j7heh) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

One of the goals here is to avoid LGPL infection, so I'm inclined instead to add our own novel test cases that cover everything we care about.  If you see anything missing in our tests, let me know.
</blockquote></details>

Sounds good to me; I hadn't put together that we can't use the existing corpus.

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20762#-:-NoJ2KNb9eGWJP00BO9O:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

**Pull request merged**
