### PR TITLE
Remove has_any_direct_feedthrough.

### PR DESCRIPTION
**Pull request by david-german-tri**
@sherm1 and @soonho-tri for feature and platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5767)

### CODE REVIEW

**Comment by david-german-tri** [comment]
These last few cases were not friendly to symbolic transmogrification.  If you want to stipulate that all systems under observation are transmogrifiable, the LuenbergerObserver could be made to work with a lot of SFINAE.  I have an abandoned branch if anyone's interested.

**Comment by david-german-tri** [comment]
...I have discovered a landmine.  Tagging `do not review` for the moment.

**Comment by david-german-tri** [comment]
> ...I have discovered a landmine. Tagging do not review for the moment.

Never mind!   PR is fine.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5767#-:-Kh9xtLVTOSm_YpJOeMx:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5767#-:-KhNRKXY9_bMcHDwS09s:bnfp4nl)*

**Pull request merged**
