### PR TITLE
tools: Add xmlrunner and use it for Python unittests

### LINKED ISSUE #8821: Python unittests should write an XML_OUTPUT_FILE
We are currently getting very rudimentary output into `test.xml` from the default test runner provided by Bazel. Instead, it would be nice to do something like

```python
import os
import unittest
import xmlrunner

if __name__ == '__main__':
    with open(os.environ['XML_OUTPUT_FILE'], 'wb') as output:
        unittest.main(testRunner=xmlrunner.XMLTestRunner(output=output))
```

(or use a different test runner, there are lots of choices, Bazel for its own testing uses a shell script for whatever reason) to get a similar level of detail to the C++ GTests. This would be helpful for the next generation of Jenkins jobs.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Remove a stray print statement whose unicode defeats the xml runner's output scraping.

Closes #8821.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14560)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please.

\CC @jamiesnape FYI

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

+@seancurtis-tri for platform review, please

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14560#-:-MRug85IDR165WfXrnpL:b-jhaovn)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14560#-:-MRvRCds6-ZcigaCjHib:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

**Pull request merged**
