### PR TITLE
Quadrotor plant

### PR DESCRIPTION
**Pull request by naveenoid**
Adds a Quadrotor plant. First of 2 PRs towards resolving spiral2 of #3994 given that RigidBodyForceElements dont yet exist #4076.

On behalf of @foehnph. 

Feature review : +@sammy-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4540)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@sammy-tri somehow I wasn't showing up as assigned?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-:-KZMjm0n5rDx7kRPSABr:bnt330r)*

**Comment by naveenoid** [comment]
yeah thats weird..I keep managing to not get the attention of my reviewers :(

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-:-KZMuQ17jx6WkWa2vkzw:b-4jaywj)*

**Comment by liangfok** [comment]
BTW, I believe the assignment will only work as a comment that's _after_ the original post. 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-:-KZMz5tPEJksl48Km01D:bqtl4ux)*

**Comment by sammy-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNlgQG63eH0ZnSjxKq:-KZNlgQH8p-RarWA1i2d:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L3)):*
> ```objc
> #pragma once
> 
> #include <iostream>
> ```

unused?

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNls_74Dl5MWqKQpsb:-KZNls_74Dl5MWqKQpsc:b-tnajn5) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L7)):*
> ```objc
> #include <Eigen/Core>
> 
> #include "drake/math/gradient.h"
> ```

unused?  (in the header file anyway)

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNlzYZiZgcrgWqqvoU:-KZNlzYZiZgcrgWqqvoV:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L8)):*
> ```objc
> 
> #include "drake/math/gradient.h"
> #include "drake/math/roll_pitch_yaw.h"
> ```

unused?

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNm6EtdzyB87hlLyi7:-KZNm6EtdzyB87hlLyi8:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L11)):*
> ```objc
> #include "drake/systems/framework/basic_vector.h"
> #include "drake/systems/framework/leaf_system.h"
> #include "drake/util/drakeGeometryUtil.h"
> ```

unused?

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNmBOeMg_Tzpv7fxMs:-KZNmBOeMg_Tzpv7fxMt:b-qsv4qm) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L24)):*
> ```objc
>  public:
>   QuadrotorPlant();
>   QuadrotorPlant(const double m_arg, const double L_arg, const Matrix3<T> I_arg,
> ```

"const" for POD types passed by value seems a bit like overkill?

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNmFQmIM3gfpfbNyDD:-KZNmFQmIM3gfpfbNyDE:b-5fcrho) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L24)):*
> ```objc
>  public:
>   QuadrotorPlant();
>   QuadrotorPlant(const double m_arg, const double L_arg, const Matrix3<T> I_arg,
> ```

I think the Matrix3<T> should be const reference?

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNmQ1yqJO10A1V_M24:-KZNmQ1zJWVN3RUBy98I:b-917gol) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L41)):*
> ```objc
>       systems::ContinuousState<T>* derivatives) const override;
> 
>   int get_input_size() { return kInputDimension; }
> ```

BTW this could be marked const

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNmRr2Gei4XSlfOK79:-KZNmRr2Gei4XSlfOK7A:b-917gol) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L43)):*
> ```objc
>   int get_input_size() { return kInputDimension; }
> 
>   int get_num_states() { return kStateDimension; }
> ```

BTW this could be marked const

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNnJUyv9C9hploXytp:-KZNnJUzmqmv4sMmqnIk:bbc85l8) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L1)):*
> ```cpp
> #include <drake/common/eigen_matrix_compare.h>
> ```

Should this still use the "" form of #include like the other drake headers?

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 179 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNntRPmkt9eB8cZfTf:-KZNntRQU5EOAeN_rseO:b-7edmn9) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L179)):*
> ```cpp
>   Simulate(kSimulationDuration);
> 
>   VectorX<double> my_state =
> ```

BTW this get_state and CompareMatrices code happens several times in this file.  It's not long, but perhaps consider moving into a helper function.

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNnizIT2u1B_6ebQDV:-KZNnizIT2u1B_6ebQDW:b2yfcj2) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L191)):*
> ```cpp
> // Test comparing the state for of each kind of plant under passive behaviour
> // after a 1.0 second motion. Each plant is dropped from the origin with an
> // intial tranlatory velocity.
> ```

typos "intial tranlatory"?

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNo12b23c3xvsWZTYO:-KZNo12cFbOXPoFe9WbB:bbqco2a) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L210)):*
> ```cpp
> // Test comparing the state for of each kind of plant under passive behaviour
> // after a 1.0 second motion. Each plant is dropped from the origin with an
> // intial rotational velocity.
> ```

typo "intial"

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNo3wintEvM4g3T0YD:-KZNo3wj8mzCGzfJAQjU:bbqco2a) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L228)):*
> ```cpp
> 
> // Test comparing the state for of each kind of plant under passive behaviour
> // after a 1.0 second motion. Each plant is dropped from and arbitrary intial
> ```

typo "intial"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540)*

**Comment by naveenoid** [comment]
Review status: 2 of 5 files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNlgQG63eH0ZnSjxKq:-KZNrjXgNlWPjABFcAC1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L3)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNls_74Dl5MWqKQpsb:-KZNrt3RZZtRf0wgR_0J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L7)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?  (in the header file anyway)
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNlzYZiZgcrgWqqvoU:-KZNrv3axmpSPUb_xSP7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L8)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNm6EtdzyB87hlLyi7:-KZNrx49KBAZberwanyT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L11)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNmBOeMg_Tzpv7fxMs:-KZNsYXmikfuzIJ9db04:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L24)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

"const" for POD types passed by value seems a bit like overkill?
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNmFQmIM3gfpfbNyDD:-KZNsZ2DpbC82q9LfPy2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L24)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think the Matrix3<T> should be const reference?
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNmQ1yqJO10A1V_M24:-KZNse3uL_es_16SYnWg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L41)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this could be marked const
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNmRr2Gei4XSlfOK79:-KZNsel-tmdS-pMQWlzG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/quadrotor_plant.h#L43)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this could be marked const
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNnJUyv9C9hploXytp:-KZNt120OmtazBODh0oH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this still use the "" form of #include like the other drake headers?
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 179 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNntRPmkt9eB8cZfTf:-KZOKxioywdAjvOYVEOc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L179)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this get_state and CompareMatrices code happens several times in this file.  It's not long, but perhaps consider moving into a helper function.
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNnizIT2u1B_6ebQDV:-KZOX06Ulj5Crf9xLUUI:bl1i2xb) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L191)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

typos "intial tranlatory"?
</blockquote></details>

Done. Changed to "initial translation"

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNo12b23c3xvsWZTYO:-KZOX3jDEG9Q0H4hvduW:b2g0dok) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L210)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

typo "intial"
</blockquote></details>

Done. (Fixed)

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNo3wintEvM4g3T0YD:-KZOX5R1M2N3zhvAfrfX:b2g0dok) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L228)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

typo "intial"
</blockquote></details>

Done. (Fixed)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNo12b23c3xvsWZTYO:-KZRsqR_QUfHKrMutONn:bd4ewtq) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L210)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done. (Fixed)
</blockquote></details>

It looks the same?

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNo3wintEvM4g3T0YD:-KZRsv8umOItq2BIw9YH:b-3s0dxm) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L228)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done. (Fixed)
</blockquote></details>

It seems to still say "intial"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-:-KZRsReVhPUpo9PNPFsz:b-s794vx)*

**Comment by naveenoid** [comment]
+@david-german-tri for platform review

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNo12b23c3xvsWZTYO:-KZTRKvSRgIEDukuVjg4:b-t769f5) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L210)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It looks the same?
</blockquote></details>

Done now. 

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZNo3wintEvM4g3T0YD:-KZTRN-ZcI9cGwUPY3Cn:b-q59rpr) ([raw file](https://github.com/robotlocomotion/drake/blob/b8d1c09b8c2ee7662cd1c8b632ac87a9734a8bb8/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L228)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems to still say "intial"
</blockquote></details>

Done now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-:-KZTQjPt0dGfFM6PABM3:b-rhk18b)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-:-KZTUF6qNCXskYUFwlB8:bnfp4nl)*

**Comment by david-german-tri** [comment]
This is nifty!

---

Reviewed 2 of 5 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 36 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZTgokmka06dJK7uEF2:-KZTgokmka06dJK7uEF3:bpdd02g) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/quadrotor_plant.cc#L36)):*
> ```cpp
> template <typename T>
> std::unique_ptr<systems::BasicVector<T>>
> QuadrotorPlant<T>::AllocateOutputVector(
> ```

FYI this is redundant; it does exactly what LeafSystem would do by default.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZTghOijIqDTTYMQ0R4:-KZTghOj0dL6s8-fNUkr:b2de8xn) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/quadrotor_plant.cc#L44)):*
> ```cpp
> template <typename T>
> std::unique_ptr<systems::ContinuousState<T>>
> QuadrotorPlant<T>::AllocateContinuousState() const {
> ```

FYI this is fine, but you could also use `DeclareContinuousState` if you preferred.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 51 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZTgv9-KZlbJEgS02-V:-KZTgv9-KZlbJEgS02-W:b3ia4kr) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/quadrotor_plant.cc#L51)):*
> ```cpp
> 
> template <typename T>
> void QuadrotorPlant<T>::EvalOutput(const systems::Context<T>& context,
> ```

FYI @jwnimmer-tri another use case for your tailored LeafSystem subclasses.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 58 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZTh7ptGcA3bkRgtUyl:-KZTh7ptGcA3bkRgtUym:bxe8vcd) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/quadrotor_plant.cc#L58)):*
> ```cpp
> 
> template <typename T>
> void QuadrotorPlant<T>::EvalTimeDerivatives(
> ```

This is a lot of cryptic variable names that are doing math, with no comments.  Please add comments generously.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZTWuWb-yJdtYcE6Wwu:-KZTWuWc896kYuZQa3QQ:b-riy5vl) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/quadrotor_plant.h#L40)):*
> ```objc
>   int get_num_states() const { return kStateDimension; }
> 
>   void set_state(systems::Context<T>* context, const VectorX<T> x) const {
> ```

`x` should be a reference

---

*[drake/examples/Quadrotor/test/CMakeLists.txt, line 17 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZThEn-jZ1PdrYXClYa:-KZThEn-jZ1PdrYXClYb:bj0kwr6) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/test/CMakeLists.txt#L17)):*
> ```CMake
>       drakeSystemAnalysis
>       drakeSystemPrimitives)
> endif()
> ```

BTW needs a trailing newline

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZThoyfmjNvX8Q3-TYU:-KZThoygxHkCy6FD6tFo:b-oc1bg7) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L21)):*
> ```cpp
> namespace drake {
> namespace examples {
> namespace quadrotor {
> ```

BTW nit: use an anonymous namespace as well

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 176 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZThxjMmuKQrI_iztyd:-KZThxjMmuKQrI_iztye:b-kadl3b) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L176)):*
> ```cpp
> };
> 
> //  Test comparing the computation of derivatives for a fixed state.
> ```

Would it be practical to also crank the derivatives by hand and assert on them here?  If so, I think that strengthens the test a bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-:-KZTiCJ3JGqIgpHCRycR:bd61u96)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-:-KZTiFJrYwSq5hyybpm4:bzdwe9o)*

**Comment by naveenoid** [comment]
Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 36 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZTgokmka06dJK7uEF2:-KZaqPnx9ETpI4J2PFiO:b-xpx6ah) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/quadrotor_plant.cc#L36)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

FYI this is redundant; it does exactly what LeafSystem would do by default.
</blockquote></details>

Done. removed.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZTghOijIqDTTYMQ0R4:-KZc6uRGpmA1sFZP3IA4:b-lrz7c7) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/quadrotor_plant.cc#L44)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

FYI this is fine, but you could also use `DeclareContinuousState` if you preferred.
</blockquote></details>

Removed this method altogether. 

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 58 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZTh7ptGcA3bkRgtUyl:-KZcEVWjuF4HsjQZaQGh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/quadrotor_plant.cc#L58)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This is a lot of cryptic variable names that are doing math, with no comments.  Please add comments generously.
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZTWuWb-yJdtYcE6Wwu:-KZaqsjpSH4W2zfyAcEe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/quadrotor_plant.h#L40)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

`x` should be a reference
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/test/CMakeLists.txt, line 17 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZThEn-jZ1PdrYXClYa:-KZar-h5ZVOrIAymCoKn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/test/CMakeLists.txt#L17)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW needs a trailing newline
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZThoyfmjNvX8Q3-TYU:-KZar7lTn43AziDgpCqj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L21)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW nit: use an anonymous namespace as well
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 176 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZThxjMmuKQrI_iztyd:-KZcEXrqhBPVMaZjjzve:bpar71j) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L176)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Would it be practical to also crank the derivatives by hand and assert on them here?  If so, I think that strengthens the test a bit.
</blockquote></details>

Well the derivative computation is precisely what is in DoCalDerivatives..Which is why I think the test in this form is ideal..i.e. comparing a RigidBodyPlant that is obtained from URDF parsing to a manually computed version. I dont think that a repeat of the equations will add a novel test in this situation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540)*

**Comment by sammy-tri** [comment]
-@david-german-tri who is on vacation

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 176 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-KZThxjMmuKQrI_iztyd:-K_0xxz5Pc-Q-bSa2_-l:byk45xy) ([raw file](https://github.com/robotlocomotion/drake/blob/95110bbf1cf0ddd64d2066e80a02d759eb311b92/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L176)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Well the derivative computation is precisely what is in DoCalDerivatives..Which is why I think the test in this form is ideal..i.e. comparing a RigidBodyPlant that is obtained from URDF parsing to a manually computed version. I dont think that a repeat of the equations will add a novel test in this situation.
</blockquote></details>

FYI I think I agree with Naveen on this (I'll leave it to him to dismiss if that seems appropriate)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4540#-:-K_0yNiTqoTkVw0AtV8f:b-6hij6z)*

**Comment by naveenoid** [comment]
I will proceed and squash and merge. Thanks @sammy-tri

**Pull request merged**
