### PR TITLE
Install install_prereqs_binary_distribution.sh

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates RobotLocomotion/drake-shambhala#61.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7917)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm: feature for Ubuntu and platform, if that helps.

Note that the installed `install_prereqs` is missing executable bits for me.  (Not sure if you want those set or not.)

I didn't test if the script was minimal and/or sufficient starting from a clean Ubuntu, but I don't think that needs to be in scope here (and is likely already correct).

**Comment by jamiesnape** [comment]
> Note that the installed install_prereqs is missing executable bits for me. (Not sure if you want those set or not.)

I do. I will fix that.

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review on Mac.

**Comment by jwnimmer-tri** [comment]
> I will fix that.

Confirmed; its 775 now.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7917#-:-L4DYWVnSti1fkM8jECH:b-bo4q5p)*

**Comment by jamiesnape** [comment]
Yes, quick fix of setting the executable bits on the source file is in. Perhaps more robust would be to add the ability to set permissions in `install_files`. You could argue either way with whether `install_prereqs_binary_distribution.sh` should be executable in this repo. We have not really followed GSG with script naming and permissions so far.

**Comment by soonho-tri** [comment]
:lgtm: (checked the installation part on :apple: )

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7917#-:-L4Gw5s8i9d-TwyM-vDY:b9qae4q)*

**Pull request merged**
