### PR TITLE
Symbolic linear equality matrix constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4995)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri for feature review.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-:-KbqoLxpLqWf5qVgyhoQ:bp61js4)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-Kbv0Lv5eYRrfA0Et1DD:-Kbv0Lv5eYRrfA0Et1DE:b3gc5uh) ([raw file](https://github.com/robotlocomotion/drake/blob/72646cc20e8176604ac3166f02b812ae8f9d0b2d/drake/solvers/mathematical_program.h#L1157)):*
> ```objc
>                            : static_cast<int>(DerivedB::ColsAtCompileTime);
> 
>     const int V_triangular_size =
> ```

Consider moving inside the if(lower_triangle) block if that's the only place this variable is used.

---

*[drake/solvers/mathematical_program.h, line 1159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-Kbv0Vgwghr3LTAUsRT_:-Kbv0Vgwghr3LTAUsRTa:b-wbfi80) ([raw file](https://github.com/robotlocomotion/drake/blob/72646cc20e8176604ac3166f02b812ae8f9d0b2d/drake/solvers/mathematical_program.h#L1159)):*
> ```objc
>     const int V_triangular_size =
>         V_rows != Eigen::Dynamic ? (V_rows + 1) * V_rows / 2 : Eigen::Dynamic;
>     const int V_size = V_rows != Eigen::Dynamic && V_cols != Eigen::Dynamic
> ```

Consider moving inside the else block if that's the only place this is used.

---

*[drake/solvers/test/optimization_examples.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-Kbv3wOhSuYlV29GyaUC:-Kbv3wOhSuYlV29GyaUD:b8j3zqc) ([raw file](https://github.com/robotlocomotion/drake/blob/72646cc20e8176604ac3166f02b812ae8f9d0b2d/drake/solvers/test/optimization_examples.h#L87)):*
> ```objc
>   LinearMatrixEqualityExample();
> 
>   MathematicalProgram* prog() const {return prog_.get();}
> ```

https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace requires spaces between the braces and the function body.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-:-Kbuytr1lcw5lL1894d0:b-s794vx)*

**Comment by hongkai-dai** [comment]
-@sammy-tri for feature review. 

---

Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-Kbv0Lv5eYRrfA0Et1DD:-Kbv7TvQJTAkPBAHbwV0:b-py15jw) ([raw file](https://github.com/robotlocomotion/drake/blob/72646cc20e8176604ac3166f02b812ae8f9d0b2d/drake/solvers/mathematical_program.h#L1157)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Consider moving inside the if(lower_triangle) block if that's the only place this variable is used.
</blockquote></details>

Done. I did not know I can put a compile time constant (`V_triangular_size` and `V_size` in this case) inside an `if` block.

---

*[drake/solvers/mathematical_program.h, line 1159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-Kbv0Vgwghr3LTAUsRT_:-Kbv7ccISFpz6WSKtYPH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/72646cc20e8176604ac3166f02b812ae8f9d0b2d/drake/solvers/mathematical_program.h#L1159)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Consider moving inside the else block if that's the only place this is used.
</blockquote></details>

Done.

---

*[drake/solvers/test/optimization_examples.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-Kbv3wOhSuYlV29GyaUC:-Kbv6_AaUSaCdmaGMZMZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/72646cc20e8176604ac3166f02b812ae8f9d0b2d/drake/solvers/test/optimization_examples.h#L87)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace requires spaces between the braces and the function body.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-:-Kbv8ZPVUMozfsM__WYM:b3eohdm)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for both feature and platform review.

---

Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-:-Kbv8fw0-laibnUq_Rgq:b-wc7wzx)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-:-KbvCUYY68-udw9utRrP:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4995#-:-KbvMLE2ZQnoE1i8X1x0:b-l70wzf)*

**Pull request merged**
