### PR TITLE
Toward #2852: enforce -Werror=shadow in examples/.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* Remove excuse from examples/* cmake file.
 * Rename some private members with '_' suffix per style guide.
 * Fix some ctors of classes with protected/public data.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2956)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
Closes #2852.

**Comment by rpoyner-tri** [comment]
+@liangfok for feature review.
+@sammy-tri for platform review and merge.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2956#-:-KNi2KPYYK44GlRjNdol:-1638008589)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2956#-:-KNi38otJSZcos-nDKfu:1417088721)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2956#-:-KNi44ZN-gNWLc764MVy:1417088721)*

**Pull request merged**
