### PR TITLE
detail_sdf_parser: Shift date (error on bad elements) back to 2022-01-01

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Follow-up to #15672, per Slack discussion: https://drakedevelopers.slack.com/archives/C0JNB2E3S/p1630161461003200?thread_ts=1630095607.003100&cid=C0JNB2E3S

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15680)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@russtedrake for both reviews, please! +(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15680#-:-MiCozOl2KZpBUk9YWen:b-4q9esk)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15680#-:-MiCzdCeAi4L-AP9lPFa:brfqlux)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform) (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Welcome!

**Comment by jwnimmer-tri** [comment]
I'm proposing this as "release notes: none" -- in my opinion, making deprecation dates more generous does not need to be reflected in release notes.  (I'm not sure how I would mention it there, anyway.)  If you disagree, then please remove the label that I just added.

**Comment by EricCousineau-TRI** [comment]
Works for me, and sorry for not labeling it!

**Pull request merged**
