### PR TITLE
Collision model GTests

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR adds a number of Google tests to answer the following questions:
1. How is, in terms of capabilities, `Model::closestPointsAllToAll` (the O(N^2) strategy) different from `Model::collisionPointsAllToAll` (using the Bullet dispatcher) and from `Model::potentialCollisionPoints` which uses perturbation of the objects' pose to gather multiple contact points.
2. How many collision points are reported and in what frame.
3. What are Bullet manifolds and how they could be useful for physics simulations (unfortunately all tests return with only one point per manifold).
4. For cases that clearly have multiple contact points (or actually an entire contact surface), is Bullet able to report this: NO.

From these methods the one implemented in `Model::collisionPointsAllToAll` using Bullet's dispatcher is the closest to what is needed for #2004. Even groups seem to be properly setup (Google test for this coming up next) [here](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/collision/bullet_model.cc#L76) and [here](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/collision/bullet_model.cc#L39).

However `Model::collisionPointsAllToAll` seems to have a bug when `use_margins=true` (PR fix coming next).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2418) &emsp; Multiple assignees:&emsp;@ggould-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/ggould-tri">ggould-tri</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@ggould-tri for platform review.
+@sherm1 for feature review.

**Comment by ggould-tri** [comment]
On the whole very good, but I have one significant concern.

`model.h` and `point_pair.h` do not appear to document which body corresponds to `idA` and which to `idB` (or even that it will be consistent between the different methods) but this test relies on box always being A and sphere always being B (or similarly small and large box, and so forth).  You should either make the test general around the A/B choice or else document in `model.h` or `point_pair.h` that A and B are in some particular order.

My intuition from the code is that A and B are in order of `addElement` calls, in which case documentation and an assertion will suffice.  However if A and B are in allocation address order (because `id` is simply a pointer cast of `this`) or even `std::unordered_set` order, this test's assumption is a time bomb.  If that is the case then you will need to assert A and B in `std::set({...})`and add an absolute value check to the normal vector.

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> +@ggould-tri for platform review.
> 
> +@sherm1 for feature review.
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/test/model_test.cc, line 281 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIEiB8F_BWUv9wiDEcW:-KIEiB8G8bGUjJCo5qF_:-1982486957) ([raw file](https://github.com/robotlocomotion/drake/blob/458346fd016fcf2e221514e63746b46ae039bca0/drake/systems/plants/collision/test/model_test.cc#L281)):*
> ```cpp
>   // Unfortunately DrakeCollision::Model's manifold has one point for this case.
>   // Best for physics simulations would be DrakeCollision::Model to return at
>   // least the four
> ```

odd whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-:-KIEf8WTs4ggQ7TW6RMm:905788551)*

**Comment by amcastro-tri** [comment]
I agree with you on that, I was following the previous example. I am now accessing the solution by id in a map so that the test does not depend on a particular order of these ids

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> On the whole very good, but I have one significant concern.
> 
> `model.h` and `point_pair.h` do not appear to document which body corresponds to `idA` and which to `idB` (or even that it will be consistent between the different methods) but this test relies on box always being A and sphere always being B (or similarly small and large box, and so forth).  You should either make the test general around the A/B choice or else document in `model.h` or `point_pair.h` that A and B are in some particular order.
> 
> My intuition from the code is that A and B are in order of `addElement` calls, in which case documentation and an assertion will suffice.  However if A and B are in allocation address order (because `id` is simply a pointer cast of `this`) or even `std::unordered_set` order, this test's assumption is a time bomb.  If that is the case then you will need to assert A and B in `std::set({...})`and add an absolute value check to the normal vector.
</details>


---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/test/model_test.cc, line 281 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIEiB8F_BWUv9wiDEcW:-KISwDM1vdTG7P7B0jsF:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/458346fd016fcf2e221514e63746b46ae039bca0/drake/systems/plants/collision/test/model_test.cc#L281)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> odd whitespace
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-:-KISwEWPKA8dnuxNSehG:-855606634)*

**Comment by ggould-tri** [comment]
Is that change going to go into this PR or is it in an upcoming one?

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I agree with you on that, I was following the previous example. I am now accessing the solution by id in a map so that the test does not depend on a particular order of these ids
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-:-KIT0rpy2L9xGOoI2k8k:-558926940)*

**Comment by amcastro-tri** [comment]
It should be there, though github is being particularly slow this morning. I didn't even get a notification with your answer!

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Is that change going to go into this PR or is it in an upcoming one?
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-:-KITWb5ebzfZydSH-M_O:1067056281)*

**Comment by ggould-tri** [comment]
Oh, very nice.  I like the way you solved that.
:LGTM:

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> It should be there, though github is being particularly slow this morning. I didn't even get a notification with your answer!
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-:-KIUNKbjU2e42FlMWgN-:-1751835568)*

**Comment by sherm1** [comment]
This is really nice, @amcastro-tri! The test cases seem really useful for untangling the behavior quirks and the documentation is *really* helpful. A few small changes needed, then wait for CI to complete because it wasn't working earlier.

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Oh, very nice.  I like the way you solved that.
> :LGTM:
</details>


---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[drake/systems/plants/collision/test/model_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUUdH1Qx4_n9XWPIhF:-KIUUdH1Qx4_n9XWPIhG:356287277) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L23)):*
> ```cpp
>   SurfacePoint(Vector3d wf, Vector3d bf) : world_frame(wf), body_frame(bf) {}
>   Vector3d world_frame{};
>   Vector3d body_frame{};
> ```

This is being default initialized here but am I right that these are still actually uninitialized due to Eigen's behavior? If so this is misleading. You could initialize them explicitly to Zero or NaN, or leave them uninitialized and mention that in a comment.

---

*[drake/systems/plants/collision/test/model_test.cc, line 27 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUrYW0w5Q1y8YatoQ2:-KIUrYW0w5Q1y8YatoQ3:-272057087) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L27)):*
> ```cpp
> 
> // Solutions are accessed by collision element id using an std::unordered_set.
> // This is to avoid this checks depending on the particular order in which id's
> ```

Couldn't quite parse this sentence.

---

*[drake/systems/plants/collision/test/model_test.cc, line 145 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUt9nvjuBdcYvuFPpl:-KIUt9nvjuBdcYvuFPpm:-211636883) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L145)):*
> ```cpp
> 0.25 units into the box (negative distance). Only one contact point is expected
> when colliding with a sphere. **/
> TEST(ModelTest, Box_vs_Sphere) {
> ```

Use `GTEST_TEST` rather than `TEST` per style guide.

---

*[drake/systems/plants/collision/test/model_test.cc, line 211 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUsXY-4ReuR0bXIuSx:-KIUsXY0UJRCFhTTKhHz:-557242860) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L211)):*
> ```cpp
>   // which computes points in the local frame of the body.
>   // TODO(amcastro-tri): make these two conventions match? does this interfere
>   // with any Matlab functionality?
> ```

What a mess! Maybe leave all-to-all alone as a legacy (with documentation) and concentrate on making the new stuff behave sensibly?

---

*[drake/systems/plants/collision/test/model_test.cc, line 242 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUt2VrsVYGZSpk_V2F:-KIUt2VrsVYGZSpk_V2G:1819639760) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L242)):*
> ```cpp
> this was the corner at (0.5, 0.5, z) where z = 5.0 for the top of the large box
> and z = 4.9 for the bottom of the smaller box. **/
> TEST(ModelTest, SmallBoxSittingOnLargeBox) {
> ```

Use `GTEST_TEST` rather than `TEST` (per style guide).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-:-KIUu1I36tb6_kWZNB3v:656435061)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/plants/collision/test/model_test.cc, line 141 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUxK17Te6wxkrAky48:-KIUxK18L4BD2HFV8fTB:-1746927170) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L141)):*
> ```cpp
> }
> 
> /** A sphere of diameter 1.0 is placed on top of a box with sides of length 1.0.
> ```

This is a regular block comment rather than doxygen: `/*`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418)*

**Comment by amcastro-tri** [comment]
Thank you @ggould-tri.
@sherm1: hopefully now the comments are clearer? PTAL

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is really nice, @amcastro-tri! The test cases seem really useful for untangling the behavior quirks and the documentation is *really* helpful. A few small changes needed, then wait for CI to complete because it wasn't working earlier.
</details>


---

Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/plants/collision/test/model_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUUdH1Qx4_n9XWPIhF:-KIXpoU-YmwEbcsLwXhr:1434509398) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is being default initialized here but am I right that these are still actually uninitialized due to Eigen's behavior? If so this is misleading. You could initialize them explicitly to Zero or NaN, or leave them uninitialized and mention that in a comment.
</details>
Left uninitialized since that's the proper thing to do with Eigen vars (so that you can use `EIGEN_INITIALIZE_MATRICES_BY_NAN` when needed, e.g. debugging). I added a small comment on this but is that what we want to do every time with Eigen vars?  I feel this should be our default. 

---

*[drake/systems/plants/collision/test/model_test.cc, line 27 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUrYW0w5Q1y8YatoQ2:-KIXt0ExWy7SDJffH9Cz:-1349382130) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Couldn't quite parse this sentence.
</details>
added more details. 

---

*[drake/systems/plants/collision/test/model_test.cc, line 141 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUxK17Te6wxkrAky48:-KIXtjQW9z90Wf579cie:229767926) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L141)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is a regular block comment rather than doxygen: `/*`.
</details>
converted to regular block comment

---

*[drake/systems/plants/collision/test/model_test.cc, line 145 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUt9nvjuBdcYvuFPpl:-KIXu4kbYl_7TXlcScJO:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L145)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Use `GTEST_TEST` rather than `TEST` per style guide.
</details>
Done.

---

*[drake/systems/plants/collision/test/model_test.cc, line 211 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUsXY-4ReuR0bXIuSx:-KIXu9m9bdi0CgA5uRk8:-472598329) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L211)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> What a mess! Maybe leave all-to-all alone as a legacy (with documentation) and concentrate on making the new stuff behave sensibly?
</details>
agree

---

*[drake/systems/plants/collision/test/model_test.cc, line 242 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUt2VrsVYGZSpk_V2F:-KIXuC4LyL5Quw_5d9hQ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L242)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Use `GTEST_TEST` rather than `TEST` (per style guide).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-:-KIXubKItoFzmndVo5Pl:-835220115)*

**Comment by sherm1** [comment]
Looks good -- one typo and a discussion topic about initialization.

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Thank you @ggould-tri.
> @sherm1: hopefully now the comments are clearer? PTAL
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/collision/test/model_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUUdH1Qx4_n9XWPIhF:-KIZsMUKGVqF8gqkUqm4:382581535) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L23)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Left uninitialized since that's the proper thing to do with Eigen vars (so that you can use `EIGEN_INITIALIZE_MATRICES_BY_NAN` when needed, e.g. debugging). I added a small comment on this but is that what we want to do every time with Eigen vars?  I feel this should be our default. 
</details>
I think the choice of whether to initialize should be made case-by-case, just as it is for any other variables (like an array of doubles or whatever). Leaving things uninitialized should only be done after careful thought and deserves documenting. When there is no performance cost, small objects ought to be initialized (at least to NaN). That should be part of the definition of whatever class is using them. 

`double` and `int` values are also uninitialized by default but we don't allow that behavior in class members. Under tight performance constraints, we could allow it but we would expect it to be documented. The same should apply to small groupings of those values -- there is no physical difference between `double x,y,z;` and `Vector3d pt`.

I do like the idea of `EIGEN_INITIALIZE_MATRICES_BY_NAN`. I think we should enable that whenever we're debugging. I added that to issue #2276.

---

*[drake/systems/plants/collision/test/model_test.cc, line 29 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIZxs3A-82Vm5R6mzG5:-KIZxs3A-82Vm5R6mzG6:-596438165) ([raw file](https://github.com/robotlocomotion/drake/blob/2fd23fde7a25d2e505ecd08ca61e4e630f7f8c6e/drake/systems/plants/collision/test/model_test.cc#L29)):*
> ```cpp
> // Solutions are accessed by collision element id using an std::unordered_set.
> // DrakeCollision::Model returns the collision detection results as a vector of
> // DrakeCollision::PointPair entries. Each entry holds a references to the pair
> ```

"a references" -> "a reference"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-:-KIZyXjwvRAPNDDVHS-8:923339918)*

**Comment by amcastro-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/collision/test/model_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUUdH1Qx4_n9XWPIhF:-KIbvbh55NVXb1-csgo6:-49543332) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I think the choice of whether to initialize should be made case-by-case, just as it is for any other variables (like an array of doubles or whatever). Leaving things uninitialized should only be done after careful thought and deserves documenting. When there is no performance cost, small objects ought to be initialized (at least to NaN). That should be part of the definition of whatever class is using them. 
> 
> `double` and `int` values are also uninitialized by default but we don't allow that behavior in class members. Under tight performance constraints, we could allow it but we would expect it to be documented. The same should apply to small groupings of those values -- there is no physical difference between `double x,y,z;` and `Vector3d pt`.
> 
> I do like the idea of `EIGEN_INITIALIZE_MATRICES_BY_NAN`. I think we should enable that whenever we're debugging. I added that to issue #2276.
</details>
I think we do agree on this matter. As you said, you do wan to properly initialize Eigen types if that is part of the objects policy. For instance, I can see how you would like to initialize the object's center of mass to zero if the user expects this to be the default value (policy). However, many times you have Eigen type members in a class that are used as a temporal variable for computation (I did that a lot in my multibody code with joints). In that way I would ensure all "working" memory I needed was created at initialization and then I would not have the stack jumping around when calling something like "Joint::GetJacobian()". In those cases I would leave the "working array" uninitialized since if I didn't properly do so in the appropriate call clearly I had a bug.
As you said, these need to be documented properly in a case-by-case basis. 

---

*[drake/systems/plants/collision/test/model_test.cc, line 29 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIZxs3A-82Vm5R6mzG5:-KIbvTQ59ocSYi0KY5F-:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2fd23fde7a25d2e505ecd08ca61e4e630f7f8c6e/drake/systems/plants/collision/test/model_test.cc#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "a references" -> "a reference"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418)*

**Comment by liangfok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/collision/test/model_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUUdH1Qx4_n9XWPIhF:-KIbyWA1HQyu6CcaBwam:243434957) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L23)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I think we do agree on this matter. As you said, you do wan to properly initialize Eigen types if that is part of the objects policy. For instance, I can see how you would like to initialize the object's center of mass to zero if the user expects this to be the default value (policy). However, many times you have Eigen type members in a class that are used as a temporal variable for computation (I did that a lot in my multibody code with joints). In that way I would ensure all "working" memory I needed was created at initialization and then I would not have the stack jumping around when calling something like "Joint::GetJacobian()". In those cases I would leave the "working array" uninitialized since if I didn't properly do so in the appropriate call clearly I had a bug.
> As you said, these need to be documented properly in a case-by-case basis. 
> 
</details>
By "temporal variable" I assume you mean "temporary variable." One thing I'm learning from ex-JayBridge folks is that a key difference between "production grade software" and "research software" is determinism. Production grade software makes every attempt at reducing non-determistic behavior. I would argue that leaving any variable uninitialized is a source of non-determinism. I would further argue that dynamic allocation of temporary variables is another source of non-determinism. Thus, assuming our goal is towards "production grade software", I would outlaw the not initializing any variable. I would further outlaw temporary variables.

Another consideration: The argument of optimizing things by not initializing a matrix is an example of premature optimization. I would not do it until the need is proven to exist. What proof do we have other than intuition that it is actually a problem?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418)*

**Comment by amcastro-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/collision/test/model_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUUdH1Qx4_n9XWPIhF:-KIc0HpKtCqUimDrouyN:784463480) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> By "temporal variable" I assume you mean "temporary variable." One thing I'm learning from ex-JayBridge folks is that a key difference between "production grade software" and "research software" is determinism. Production grade software makes every attempt at reducing non-determistic behavior. I would argue that leaving any variable uninitialized is a source of non-determinism. I would further argue that dynamic allocation of temporary variables is another source of non-determinism. Thus, assuming our goal is towards "production grade software", I would outlaw the not initializing any variable. I would further outlaw temporary variables.
> 
> Another consideration: The argument of optimizing things by not initializing a matrix is an example of premature optimization. I would not do it until the need is proven to exist. What proof do we have other than intuition that it is actually a problem?
</details>
I did mean "temporary" variable, thanks. More like a "working space" variable. 
I do not agree with your "source of determinism" comment. Those "working space" variables are initialized/set with the proper values exactly when they are needed. If they are not, then your program has a bug and you better find it. We can talk more about it f2f. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418)*

**Comment by liangfok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/collision/test/model_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUUdH1Qx4_n9XWPIhF:-KIcCcw-4RfkvwmQp7up:-1214676320) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L23)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I did mean "temporary" variable, thanks. More like a "working space" variable. 
> I do not agree with your "source of determinism" comment. Those "working space" variables are initialized/set with the proper values exactly when they are needed. If they are not, then your program has a bug and you better find it. We can talk more about it f2f. 
</details>
Note that even if a temporary variable is set immediately after it is declared, there will be non-determinism in the latency of instantiation and there's even a slight chance that the operating system fails to allocate memory for the temporary variable. This is fundamentally a source of non-determinism.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418)*

**Comment by sherm1** [comment]
:lgtm:

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Looks good -- one typo and a discussion topic about initialization.
</details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/test/model_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUUdH1Qx4_n9XWPIhF:-KIcZAG9CPs8VhV6f1KW:907549244) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Note that even if a temporary variable is set immediately after it is declared, there will be non-determinism in the latency of instantiation and there's even a slight chance that the operating system fails to allocate memory for the temporary variable. This is fundamentally a source of non-determinism.
</details>
@liangfok, timing nondeterminism is unavoidable in anything but realtime code; we're not doing that here. This thread and our style guide advocate mandatory initialization to avoid memory-content nondeterminism. The broad field of scientific computation, with rigorous perfomance measurement a primary focus, supports the memory-dominated performance issues of large data structures and does not need to be reinvestigated by us when we're doing conventional work such as factoring matrices. This would be a good conversation to have f2f with an expert scientific programmer like Alejandro. I'm booting it out of this PR, though!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-:-KIcayQ_lRIDXHYBvY1A:1417088721)*

**Comment by sherm1** [comment]
This is ready to merge after CI.

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/test/model_test.cc, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2418#-KIUUdH1Qx4_n9XWPIhF:-KIceO9s2k-U74C2cZHW:-208326040) ([raw file](https://github.com/robotlocomotion/drake/blob/59d9c2d3ca0cd94cd038e2a763b3fe2c4ef95519/drake/systems/plants/collision/test/model_test.cc#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> @liangfok, timing nondeterminism is unavoidable in anything but realtime code; we're not doing that here. This thread and our style guide advocate mandatory initialization to avoid memory-content nondeterminism. The broad field of scientific computation, with rigorous perfomance measurement a primary focus, supports the memory-dominated performance issues of large data structures and does not need to be reinvestigated by us when we're doing conventional work such as factoring matrices. This would be a good conversation to have f2f with an expert scientific programmer like Alejandro. I'm booting it out of this PR, though!
</details>
OK. Fingers crossed we don't encounter many time-sucking [Heisenbugs](https://en.wikipedia.org/wiki/Heisenbug) in the future. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2418)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
