### PR TITLE
Weekly buildifier and clang-format-includes cleanup

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6492)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6492#-:-KntgxslfNaUg_ux5g2N:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6492#-:-KnthFnrPoYhAE0QU8Cf:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Maybe start adding `bazel_lint` in other places, so stuff can't drift out of "good" going forward? (Is there a reason we don't have similar enforcement for `clang-format-includes`?)

**Comment by jwnimmer-tri** [comment]
I just haven't had time to write / turn on the automation, and we need better user documentation on the fixup tools before we do.

**Comment by mwoehlke-kitware** [comment]
> I just haven't had time to write / turn on the automation,

Okay, just wondering / suggesting possible future direction.

> and we need better user documentation on the fixup tools before we do.

Heh, yeah... #6416 sounds relevant :smile:.

**Pull request merged**
