### PR TITLE
Add HSR model description files

### PR DESCRIPTION
**Pull request by huihuaTRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13153)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Large files (obj, etc.) go into a separate repository, not Drake.
See https://drake.mit.edu/model_version_control.html.

**Comment by jwnimmer-tri** [comment]
Or can we just use https://github.com/ToyotaResearchInstitute/hsr_description or https://github.com/ToyotaResearchInstitute/hsr_meshes directly?

**Comment by jwnimmer-tri** [comment]
Ah, I finally found the README.  So maybe we should refer to the TRI repository for the meshes, but fork the XML file(s) here so the description is compatible with Drake's parser?  I see no reason to copy the meshes?

However, that points out the bigger problem -- the hsr_meshes are not license-compatible with Drake.

**Comment by huihuaTRI** [comment]
So BSD is not license-compatible with Drake? Using the linked description is fine, we still need to add the convex decomposed objs though.

**Comment by sherm1** [comment]
The Clear BSD license looks fine to me. It is the same as our regular 3-clause BSD license except for the addition of the sentence "NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE". That is just a clarification since the plain BSD license also does not grant rights to patents. (In constrast to Apache 2.0 which explicitly _does_ grant patent rights.)

Why do you think that's not compatible, @jwnimmer-tri ?

**Comment by jwnimmer-tri** [comment]
The BSD-3-Clause used by https://github.com/ToyotaResearchInstitute/hsr_description is fine of course.

The https://github.com/ToyotaResearchInstitute/hsr_meshes is licensed under CC-BY-NC-ND-4.0 though.

**Comment by sherm1** [comment]
CC-BY-NC-ND-4.0: oh dear! The ND might as well stand for Non-Drake!

**Comment by jwnimmer-tri** [comment]
You could pursue re-licensing the meshes.

Are the meshes visual or collision?  You could perhaps still simulate without the nice visual meshes.

**Comment by huihuaTRI** [comment]
I see. Thanks.

The meshes are used for both visual and collision. I do not own the meshes. Can I still re-licensing them? Or you are talking about contact the HSR group to re-license them.

**Comment by jwnimmer-tri** [comment]
The copyright owner must be the one who re-licenses the files.

**Comment by sherm1** [comment]
Here are some possibilities I can think of:
- try to get the HSR group to agree the meshes can be released under BSD or compatible Creative Commons license (uncertain and could take a long time but worth a conversation)
- consider whether the meshes can be kept distinct enough from open source Drake that we can still use them in an installed example, with clear licensing restrictions
- ask props for help making a new set of original meshes for HSR that are not derived from the Toyota ones

You might want to pursue all of these -- I would start by asking for help from TRI legal (start with Phil Zackler) on the first two.

Any other ideas, @jwnimmer-tri ?

**Comment by jwnimmer-tri** [comment]
I think we're long past the point where you both and I should discuss this overall project on a video call so we all understand the scope and goals.

**Comment by huihuaTRI** [comment]
Closing this pull request since a new issue has been submitted: https://github.com/RobotLocomotion/drake/issues/13242. We are using PR2 for now.

**Pull request closed without merging**
