### PR TITLE
Switch EventData from abstract to std::variant

### PR DESCRIPTION
**Pull request by sherm1**
The optional data stored in an Event was a heap-allocated object derived from abstract class EventData. This PR converts the stored event data to an std::variant and enumerates the only two known use cases: PeriodicEventData and WitnessTriggeredEventData. The EventData name is gone.

### Background
This is a yak shave PR for WIP #18048 that provides CalcUniquePeriodicDiscreteUpdate() as requested in #10909.
18048 requires a further yak shave (to follow) where periodic events must be stored as an EventCollection (as is done for the other events), to deal properly with Diagrams where the uniquely-timed discrete update events may occur in different subsystems. That makes heavier use of the PeriodicEventData stored with Events which required runtime heap allocation and blew carefully-checked heap limit unit tests. Here we eliminate altogether heap use associated with EventData.

### Note
This is a potentially breaking change, since EventData is now gone. The actual data classes are unchanged, though the methods for extracting and setting them are now templatized. However, all the use cases I've been able to find so far are internal, or deal only with the concrete data types that haven't changed. I don't think there is a realistic use case where someone derived a new class from EventData other than the two we use internally. Jeremy confirmed that Anzu doesn't care about this change.

cc @edrumwri if anyone would care about this change I think it would be you. Any problem?

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@jwnimmer-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068#-:-NE3J8mg019vQ6MmoydS:bgy1vi6)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I ran Anzu CI on this PR and it was happy.

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint for the night.  I'll circle back tomorrow.

> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068#-:-NE3hvMN31x0N9ARf-kd:b-kassyb)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @sherm1)

___
*[`systems/framework/event.h` line 330 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE3hdkB4KTcPlZUKyfg:-NE3hdkB4KTcPlZUKyfh:bwwzemu) ([raw file](https://github.com/robotlocomotion/drake/blob/151836fed709c8f0721dc4286685ae33650d0dc5/systems/framework/event.h#L330)):*
> ```objc
> template <typename T>
> using EventData = std::variant<std::monostate, PeriodicEventData,
>                                WitnessTriggeredEventData<T>>;
> ```

On my first read, `EventData` is an implementation helper only (i.e., not part of our public API) so should be in the `internal` namespace.
___
*[`bindings/pydrake/systems/framework_py_semantics.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE3gjcp7QLgXWsF1kO3:-NE3gjcq1Mjot674QKNs:b7e0ovw) ([raw file](https://github.com/robotlocomotion/drake/blob/5c5d14e6982fe6e34fa2b18fff1a0bb31f535c8b/bindings/pydrake/systems/framework_py_semantics.cc#L146)):*
> ```cpp
> 
>   auto event_data = py::class_<EventData>(m, "EventData", doc.EventData.doc);
>   DefClone(&event_data);
> ```

This loses us the python `copy.copy` bindings.  That's probably not a big deal, but it's easy enough to keep intact.  Something like this:



_Suggestion:_
```cpp
  py::class_<PeriodicEventData> cls(
      m, "PeriodicEventData", doc.PeriodicEventData.doc);
  cls  // BR
      .def("period_sec", &PeriodicEventData::period_sec,
          doc.PeriodicEventData.period_sec.doc)
      .def("offset_sec", &PeriodicEventData::offset_sec,
          doc.PeriodicEventData.offset_sec.doc);
  DefCopyAndDeepCopy(&cls);
```
___
*[`bindings/pydrake/systems/test/general_test.py` line 293 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE3hA7k-kwLftMmnPzP:-NE3hA7k-kwLftMmnPzQ:b7v502f) ([raw file](https://github.com/robotlocomotion/drake/blob/5c5d14e6982fe6e34fa2b18fff1a0bb31f535c8b/bindings/pydrake/systems/test/general_test.py#L293)):*
> ```Python
>         periodic_data = system1.GetUniquePeriodicDiscreteUpdateAttribute()
>         self.assertIsInstance(periodic_data, PeriodicEventData)
>         self.assertIsInstance(periodic_data.Clone(), PeriodicEventData)
> ```

nit The new test case would be that `copy.copy(periodic_data)` doesn't throw.



_Suggestion:_
```Python
copy.copy(periodic_data)
```

**Review by jwnimmer-tri — COMMENTED** [review]
First pass complete.

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068#-:-NE6Sf4E2Z8dmXBt-ICd:bvb1a6z)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @sherm1)

___
*[`systems/framework/event.h` line 330 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE3hdkB4KTcPlZUKyfg:-NE6REPd5YLeV2RJP5kx:b53i69g) ([raw file](https://github.com/robotlocomotion/drake/blob/151836fed709c8f0721dc4286685ae33650d0dc5/systems/framework/event.h#L330)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On my first read, `EventData` is an implementation helper only (i.e., not part of our public API) so should be in the `internal` namespace.
</blockquote></details>

... or even just write the member field type directly and ditch the alias entirely.

In any case, we'll need some changes to the Doxygen stanzas to purge mention of `EventData`.
___
*[`systems/framework/event.h` line 445 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE6RheC2-UxCX0SKOFk:-NE6RheC2-UxCX0SKOFl:b-4wv895) ([raw file](https://github.com/robotlocomotion/drake/blob/151836fed709c8f0721dc4286685ae33650d0dc5/systems/framework/event.h#L445)):*
> ```objc
> 
>   /**
>    * Returns true if this event has associated data of the expected type.
> ```

nit I don't think this documentation is sufficiently clear for a user to pick up and understand what's happening.

(1) I'm not sure "expected" makes clear exactly what is going on here.  Something like "the given type" or "the requested type" would be more direct, though maybe "of the given EventDataType" or similar.

(2) I do think a `@tparam EventDataType` worth adding here; it could explain that the argument must be either `PeriodicEventData` or `WitnessTriggeredEventData<T>`, nothing else.

Ditto throughout (for the public functions).

**Review by edrumwri — COMMENTED** [review]
This looks to be a great change.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068#-:-NE6bsJtCqJP7jC0qRX-:bybr9fv)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Thanks. All feature review comments addressed, ptal. I added some missing unit tests also.
+@rpoyner-tri for platform review per rotation, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068#-:-NE7kD945sJ6ESz-jVb5:bqc3xwf)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`systems/framework/event.h` line 330 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE3hdkB4KTcPlZUKyfg:-NE7jqUv7dCKOKp-eDEZ:bc6ifjo) ([raw file](https://github.com/robotlocomotion/drake/blob/151836fed709c8f0721dc4286685ae33650d0dc5/systems/framework/event.h#L330)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

... or even just write the member field type directly and ditch the alias entirely.

In any case, we'll need some changes to the Doxygen stanzas to purge mention of `EventData`.
</blockquote></details>

Done. Removed EventData altogether.
___
*[`systems/framework/event.h` line 445 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE6RheC2-UxCX0SKOFk:-NE7jx9w3Jdra4aknZLM:b-opi4xi) ([raw file](https://github.com/robotlocomotion/drake/blob/151836fed709c8f0721dc4286685ae33650d0dc5/systems/framework/event.h#L445)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I don't think this documentation is sufficiently clear for a user to pick up and understand what's happening.

(1) I'm not sure "expected" makes clear exactly what is going on here.  Something like "the given type" or "the requested type" would be more direct, though maybe "of the given EventDataType" or similar.

(2) I do think a `@tparam EventDataType` worth adding here; it could explain that the argument must be either `PeriodicEventData` or `WitnessTriggeredEventData<T>`, nothing else.

Ditto throughout (for the public functions).
</blockquote></details>

Done, ptal
___
*[`bindings/pydrake/systems/framework_py_semantics.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE3gjcp7QLgXWsF1kO3:-NE7jhe71pX36xQpMw1W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5c5d14e6982fe6e34fa2b18fff1a0bb31f535c8b/bindings/pydrake/systems/framework_py_semantics.cc#L146)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This loses us the python `copy.copy` bindings.  That's probably not a big deal, but it's easy enough to keep intact.  Something like this:
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068#-:-NE7oGxA8ji5pcl9XxGq:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[`systems/framework/event.h` line 445 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE6RheC2-UxCX0SKOFk:-NE7njovDIY84ImsFpOu:b-f6t03g) ([raw file](https://github.com/robotlocomotion/drake/blob/151836fed709c8f0721dc4286685ae33650d0dc5/systems/framework/event.h#L445)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done, ptal
</blockquote></details>

The getters look good, but probably the `has_event_data` language still needs a tune-up?
___
*[`systems/framework/test/event_test.cc` line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE7o8IGCIHF4KpV7Heh:-NE7o8IGCIHF4KpV7Hei:bbx1gsh) ([raw file](https://github.com/robotlocomotion/drake/blob/8d78db5df1d8bf20d07fe5ff60ec6639eeb6e076/systems/framework/test/event_test.cc#L53)):*
> ```cpp
>   PeriodicEventData data;
>   data.set_period_sec(.125);
>   data.set_offset_sec(.5);
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals



_Suggestion:_
```cpp
  data.set_period_sec(0.125);
  data.set_offset_sec(0.5);
```

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068#-:-NE87Zfb2sa-FVddHtnV:bnfp4nl)* status: 2 unresolved discussions (waiting on @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @sherm1)

___
*[`systems/framework/event.h` line 445 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE6RheC2-UxCX0SKOFk:-NE88Scz-Ni2OFIr9I5M:b-k48aeq) ([raw file](https://github.com/robotlocomotion/drake/blob/151836fed709c8f0721dc4286685ae33650d0dc5/systems/framework/event.h#L445)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The getters look good, but probably the `has_event_data` language still needs a tune-up?
</blockquote></details>

Done (derp, sorry)
___
*[`systems/framework/test/event_test.cc` line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE7o8IGCIHF4KpV7Heh:-NE88Yv7EA1SZmzORhTN:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/8d78db5df1d8bf20d07fe5ff60ec6639eeb6e076/systems/framework/test/event_test.cc#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals
</blockquote></details>

Done
___
*[`bindings/pydrake/systems/test/general_test.py` line 293 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18068#-NE3hA7k-kwLftMmnPzP:-NE88ma8EARL9r3hZ5_O:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5c5d14e6982fe6e34fa2b18fff1a0bb31f535c8b/bindings/pydrake/systems/test/general_test.py#L293)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The new test case would be that `copy.copy(periodic_data)` doesn't throw.
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18068)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @sherm1)

**Pull request merged**
