### PR TITLE
Require SNOPT or IPOPT to run kuka_demo

### LINKED ISSUE #3710: kuka_demo fails during open source builds on OS X
```
Test command: /Users/elcapitan/workspace/mac-clang-ninja-nightly-matlab-open-source/build/drake/bin/kuka_demo
Welding joint iiwa_joint_ee
Welding joint tool0_joint
Welding joint iiwa_joint_ee
Welding joint tool0_joint
x = 0 0 0 0 0 0 0
x = 0 0 0 0 0 0 0
x = 0 0 0 0 0 0 0
x =    -0.384641     0.700006     0.400798     -1.92449     -1.40822     -1.07185 -7.25537e-12
x = 0 0 0 0 0 0 0
[2016-10-06 14:20:23.406] [console] [info] INFO[0] = 1 
[2016-10-06 14:20:23.407] [console] [info] INFO[1] = 100 
[2016-10-06 14:20:23.407] [console] [info] INFO[2] = 1 
[2016-10-06 14:20:23.407] [console] [info] INFO[3] = 1 
[2016-10-06 14:20:23.407] [console] [info] INFO[4] = 100 
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: inverseKinPointwise failed to compute a valid solution.

Test #kuka_demo .......................................................................***Exception: Other  3.32 sec
```

### PR DESCRIPTION
**Pull request by sammy-tri**
Fixes #3710 by disabling the test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3719)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please

**Comment by sammy-tri** [comment]
+@ggould-tri for feature aand platform review (assuming the mac jenkins passes, but I'm pretty confident)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3719#-:-KTVYT5UfBg-4o9O88l4:b-a3hgrz)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3719#-KTVZ2xf-c0IeBk6nz2F:-KTVZ2xf-c0IeBk6nz2G:bosn617) ([raw file](https://github.com/robotlocomotion/drake/blob/6c961dbb861dc6ed2d185e820de84c03750758a3/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L6)):*
> ```CMake
>     drakeSystemControllers drakeLCMSystem2 drakeIK drakeTrajectories
>     ${GTEST_BOTH_LIBRARIES})
>   # NLopt isn't sufficient to run the kuka_demo.
> ```

Please reference #3710 here and clarify that the specific insufficiency is that NLOPT's solution is numerically incorrect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3719)*

**Comment by sammy-tri** [comment]
Mac Jenkins has passed: https://drake-jenkins.csail.mit.edu/job/mac-clang-experimental-matlab-open-source/25/

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3719#-:-KTVjM-chDsBgJXWLmKP:bkrvqdk)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3719#-:-KTVjpn_ZyImKkMMkoe0:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3719)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3719#-KTVZ2xf-c0IeBk6nz2F:-KTVjxf8euxkVKBRiZ55:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6c961dbb861dc6ed2d185e820de84c03750758a3/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L6)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Please reference #3710 here and clarify that the specific insufficiency is that NLOPT's solution is numerically incorrect.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3719)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3719#-KTVlNniQF7pcu1GxlYe:-KTVlNnju2SSkUzN7DR5:bp68c0j) ([raw file](https://github.com/robotlocomotion/drake/blob/0932fd9cfea59627924c13d15439c84bcaa1c6e8/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L6)):*
> ```CMake
>     drakeSystemControllers drakeLCMSystem2 drakeIK drakeTrajectories
>     ${GTEST_BOTH_LIBRARIES})
>   # NLopt isn't sufficient to run the kuka_demo, as is unable to find
> ```

BTW: nit: Is there an "it" missing before "is"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3719)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3719#-KTVlNniQF7pcu1GxlYe:-KTVll7pQd7YwTwXEfrH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0932fd9cfea59627924c13d15439c84bcaa1c6e8/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L6)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: Is there an "it" missing before "is"?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3719)*

**Comment by jwnimmer-tri** [comment]
Using override-merge at @sammy-tri's request.

**Pull request merged**
