### PR TITLE
Tree visualizer namespace change

### PR DESCRIPTION
**Pull request by naveenoid**
A simple namespace change. It was kept annoying me.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6883)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@sammy-tri for feature and platform review. (Its a simple PR).

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6883#-:-Ks9MG6zupNKbl4mvd_k:b14fmuq)*

**Comment by sammy-tri** [comment]
I think I'm ok with forcing this into the extra namespace...  This PR still leaves a bunch of code in `manipulation/util` without the `util` namespace though.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6883#-:-Ks9NApLCbtfV84ZTtxN:b4amr42)*

**Comment by naveenoid** [comment]
I will upgrade that as well then. Its just a bit of ugliness that needs cleanup.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6883#-:-Ks9dZsGaf61lZcuIUtA:bniyrul)*

**Comment by naveenoid** [comment]
changed them all now. PTAL.

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6883#-:-KsEbYKBu1n9l6fqC87F:bubo4vd)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 20 files at r1.
Review status: 1 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6883#-KsFB0IQeu07LDfWG5wP:-KsFB0IQeu07LDfWG5wQ:b-veow32) ([raw file](https://github.com/robotlocomotion/drake/blob/9cdf5cceaa0b50277970328e5db6952bef3c28b7/drake/manipulation/util/robot_state_msg_translator.cc#L16)):*
> ```cpp
> // For every ith name in @p names, if it is present in @p name_to_index, set
> // msg_values[i] = values[name_to_index.find(names[i])]
> void EncodeValue(const std::unordered_map<std::string, int> &name_to_index,
> ```

These lines were previously compliant with http://drake.mit.edu/code_style_guide.html#clarifications which specifies that the `&`  or `*` symbols must appear next to the type, not the variable.  This revision of this PR breaks all lines where this change occurs.

Will resume review after this is fixed, it's visually confusing in the current state which blocks I should pay attention to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6883)*

**Comment by naveenoid** [comment]
Review status: 1 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6883#-KsFB0IQeu07LDfWG5wP:-KsFBapn4vB4fTtDm-Xf:bx612gh) ([raw file](https://github.com/robotlocomotion/drake/blob/9cdf5cceaa0b50277970328e5db6952bef3c28b7/drake/manipulation/util/robot_state_msg_translator.cc#L16)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

These lines were previously compliant with http://drake.mit.edu/code_style_guide.html#clarifications which specifies that the `&`  or `*` symbols must appear next to the type, not the variable.  This revision of this PR breaks all lines where this change occurs.

Will resume review after this is fixed, it's visually confusing in the current state which blocks I should pay attention to.
</blockquote></details>

Ugh..this was my clion making those mods. I will revisit this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6883)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please

**Comment by naveenoid** [comment]
Im going to reopen a new PR for namespace change once a few other PRs land.

---

Review status: 1 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6883#-:-Kvh8RWbLbO8BMExWx6t:bxd8sjy)*

**Pull request closed without merging**
