### PR TITLE
Remove the infinite / endless demo

### LINKED ISSUE #5704: village-demo broken on master?
after a clean build/install on xenial, running `bazel run drake/automotive:village-demo` resulted in 

```
...
[dev_demo] Welding joint front_lidar_joint
[dev_demo] Welding joint top_lidar_joint
[dev_demo] Welding joint rear_right_lidar_joint
[dev_demo] Welding joint rear_left_lidar_joint
[dev_demo] terminate called after throwing an instance of '
[dev_demo] std::runtime_error
[dev_demo] '
[dev_demo]   what():  
[dev_demo] CarVisApplicator::DoCalcOutput(): Input PoseBundle has 0poses. Expected 15.
[lcm-logger] Summary: lcmlog-2017-04-03.00 ti:   2sec Events: 5         (    0 MB )      TPS:     2.73       KB/s:    30.00
[automotive_demo.py] dev_demo exited -6
```

apologies in advance if it's user error!

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #5704.

This demo code's use of the "InifniteRoad" concept is inconsistent with the modeling choices we want to use moving forward, and our new railcar supplants the "endless" car.  I'd been hoping to get the new highway merge ready before removing this, but I guess the lack of testing here means its bitrotted anyway, so might as well just remove it now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5705)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri for feature review

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5705#-:-Kgo6Ch_IW9LZtZ3MBFN:b95uaco)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5705#-:-Kgo6ol65yVbAXSgDnYw:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:car: ready to merge once we get platform review.

+@ggould-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5705#-:-Kgo71aKcIA3jI1PdtOq:b-piav4w)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5705#-:-KgoP2CCJtmbaxkKt9TX:bnfp4nl)*

**Pull request merged**
