### PR TITLE
Add indeterminates to MathematicalProgram

### PR DESCRIPTION
**Pull request by FischerGundlach**
This commit adds indeterminates to drake::solvers:MathematicalProgram. Indeterminates are represented by an Eigen::Matrix<symbolic::Variables> (see indeterminates.h) Inside MathematicalProgram the indeterminates are saved in VectorXIndeterminateVariable indeterminate_variables_. The interface for creating and accessing indeterminates is the same as for decision variables.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6121)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6121#-:-KkI6zcxO2JZIsAjb4No:bltox9h)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot add to whitelist

**Comment by soonho-tri** [comment]
+@soonho-tri platform review.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6121#-:-KkI9TX_C5q9J7AuyG-8:bv2eajz)*

**Comment by soonho-tri** [comment]
+(status: curate commits before merging) 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6121#-:-KkI9Wj0zF3y8XB7n5lV:b-s794vx)*

**Comment by hongkai-dai** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/indeterminate_variable.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6121#-KkIA-opbfRSsAO3ddIc:-KkIA-opbfRSsAO3ddId:bhgug6z) ([raw file](https://github.com/robotlocomotion/drake/blob/434bac704cdf63767175a3882468e2e8706fe779/drake/solvers/indeterminate_variable.h#L29)):*
> ```objc
> /**
>  * Concatenates each element in \p var_list into a single Eigen vector of
>  * decision variables, returns this concatenated vector.
> ```

`decision variables` -> `indeterminates`. 

---

*[drake/solvers/mathematical_program.h, line 638 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6121#-KkI76p0BSI6uhJxnhSf:-KkI76p0BSI6uhJxnhSg:b-e7gpu1) ([raw file](https://github.com/robotlocomotion/drake/blob/434bac704cdf63767175a3882468e2e8706fe779/drake/solvers/mathematical_program.h#L638)):*
> ```objc
>    * Adds indeterminate variables, appending them to an internal vector of any
>    * existing vars.
>    * @param rows  The number of rows in the new indeterminates.
> ```

This should be `@tparam`, since it is a template parameter.

---

*[drake/solvers/mathematical_program.h, line 665 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6121#-KkI7JPAkaE8178y11y3:-KkI7JPAkaE8178y11y4:bn0fq8) ([raw file](https://github.com/robotlocomotion/drake/blob/434bac704cdf63767175a3882468e2e8706fe779/drake/solvers/mathematical_program.h#L665)):*
> ```objc
>   /**
>    * Adds indeterminate variables, appending them to an internal vector of any
>    * existing vars.
> ```

`existing indeterminates`? I think we should avoid using the word `variables`, but use `indeterminates` instead.

---

*[drake/solvers/mathematical_program.h, line 738 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6121#-KkI7ksd8ho2ESa0a3tA:-KkI7ksd8ho2ESa0a3tB:by57oga) ([raw file](https://github.com/robotlocomotion/drake/blob/434bac704cdf63767175a3882468e2e8706fe779/drake/solvers/mathematical_program.h#L738)):*
> ```objc
>   }
> 
> // TODO (MFG) Do I actually need the int row, or is the cast from size_t good enough?
> ```

Use full name instead of `MFG`? 

---

*[drake/solvers/mathematical_program.h, line 2279 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6121#-KkI7ym7kKlyJyPmnG9W:-KkI7ym7kKlyJyPmnG9X:bhibys5) ([raw file](https://github.com/robotlocomotion/drake/blob/434bac704cdf63767175a3882468e2e8706fe779/drake/solvers/mathematical_program.h#L2279)):*
> ```objc
>   VectorXIndeterminateVariable indeterminate_variables_;
> 
>   std::vector<Binding<Constraint>> generic_costs_;
> ```

Why this is changed? I think something sneaks in when you resolving the conflicts. Probably redo the rebasing/merging?

---

*[drake/solvers/mathematical_program.h, line 2460 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6121#-KkI8RDzoiPWKP8gWLJS:-KkI8RDzoiPWKP8gWLJT:b81u042) ([raw file](https://github.com/robotlocomotion/drake/blob/434bac704cdf63767175a3882468e2e8706fe779/drake/solvers/mathematical_program.h#L2460)):*
> ```objc
>   }
> 
>   Binding<LinearEqualityConstraint> DoAddLinearEqualityConstraint(
> ```

This `DoAddLinearEqualityConstraint` should not sneak in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6121)*

**Comment by RussTedrake** [comment]
fyi - i've added moritz to github to avoid future jenkins message spamming.

**Comment by RussTedrake** [comment]
also -- github thinks this PR changes > 1,600 files.  that's impressive, but probably worth fixing before merge.

**Comment by soonho-tri** [comment]
@FischerGundlach , I guess you plan to attend today's TRI+MIT group meeting at TRI? If so, how about working on this PR together after the meeting?

**Comment by soonho-tri** [comment]
@FischerGundlach and I had an f2f and resolved merge conflicts and bazel-specific issues. @FischerGundlach will open a new PR.

**Pull request closed without merging**
