### PR TITLE
Makes DepthSensorSpecification copiable.

### LINKED ISSUE #4675: Consider Making DepthSensorSpecification Copyable
# The Issue

In #4597, `DepthSensorSpecification` was made a non-copyable and non-movable based on this  comment:

https://reviewable.io/reviews/robotlocomotion/drake/4597#-K_aCdiWcUtE4UaeOHaj

However, this class is so simple that maybe we should consider making it copyable based on this comment:

https://reviewable.io/reviews/robotlocomotion/drake/4597#-K_aEJeNRL5hLebErlyO

This issue tracks a discussion about whether it would be appropriate / advantageous to make this class copyable.

# Thoughts

[Here's](https://google.github.io/styleguide/cppguide.html#Copyable_Movable_Types) what the style guide says:

> Provide the copy and move operations if their meaning is clear to a casual user and the copying/moving does not incur unexpected costs. If you define a copy or move constructor, define the corresponding assignment operator, and vice-versa. If your type is copyable, do not define move operations unless they are significantly more efficient than the corresponding copy operations. If your type is not copyable, but the correctness of a move is obvious to users of the type, you may make the type move-only by defining both of the move operations.
> 
> If your type provides copy operations, it is recommended that you design your class so that the default implementation of those operations is correct. Remember to review the correctness of any defaulted operations as you would any other code, and to document that your class is copyable and/or cheaply movable if that's an API guarantee.

Making the class copyable can be done without changing any of its existing usages, though it would allow API tweaks that reduce the lifetime requirements placed on the user. For example, `DepthSensor`'s constructor can be modified to save a copy of the specification instead of an alias to it.  The disadvantage of doing this, however, is it will consume more memory since multiple copies of the specification will remain resident in memory, and there can be multiple "sources of truth" given the multiple copies in memory.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4675.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5801)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for feature review please. Thanks.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5801#-:-KhWsjX7xxTSmQemZdRq:b-95jool)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5801#-:-KhXNXKIVDwYemOIWbrE:bnfp4nl)*

**Comment by liangfok** [comment]
+@ggould-tri for platform review please. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5801#-:-KhXOdaI9iO93h0S7Jnp:b-ddt3yg)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5801#-:-KhYCSAYB1O3DeDNoWpc:bnfp4nl)*

**Pull request merged**
