### PR TITLE
Add simple closed-form pose estimation methods.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Adds simple closed-form pose estimation methods.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6768)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.

\cc @hongkai-dai This addresses your earlier requests for (a) simple closed-form pose estimation, and (b) robustifying rotation matrix comparison.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-:-KqdN2lNCUgx9KTU290A:b2s8dwi)*

**Comment by kunimatsu-tri** [comment]
Done the first round. PTAL.

---

Reviewed 8 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/perception/estimators/dev/pose_closed_form.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdkuUkHHvQ-7UZnv0n:-KqdkuUkHHvQ-7UZnv0o:bodjc04) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/pose_closed_form.h#L16)):*
> ```objc
>  * @param y_W A 3xn matrix represent `n` measured points, fixed in body `B`
>  * (inferred via PCA), expressed in world coordinates.
>  * @param X_WB The pose of the inferred shape in the world frame.
> ```

BTW, is that OK for return value to use `@param` instead of `@return`?  If so, please just ignore this comment.

---

*[drake/perception/estimators/dev/pose_closed_form.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqduZlGF5y_lQeqs7rP:-KqduZlGF5y_lQeqs7rQ:baxtvzu) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/pose_closed_form.h#L29)):*
> ```objc
>  * which is implemented as a widely-used simplification of the quaternion-based
>  * formulation presented in:
>  *    Besl, Paul J., and Neil D. McKay. "A method for registration of 3-D
> ```

It's great to refer to the literature!

I think it's more suitable to refer to:
Arun, K. Somani, Thomas S. Huang, and Steven D. Blostein. "Least-squares fitting of two 3-D point sets." IEEE Transactions on pattern analysis and machine intelligence 5 (1987): 698-700.
since it's not performing ICP in this implementation.

---

*[drake/perception/estimators/dev/test/pose_closed_form_test.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqdvqm9D1eD8ZnkvhV9:-Kqdvqm9D1eD8ZnkvhVA:b-i35o) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/pose_closed_form_test.cc#L17)):*
> ```cpp
> namespace {
> 
> GTEST_TEST(Icp, PcaAndSvd) {
> ```

BTW, we might want to avoid using the term `Icp` here since it's not iterative in this implementation.
How about `PoseRegistration` instead?

---

*[drake/perception/estimators/dev/test/pose_closed_form_test.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqe-CM6AQ3B2N17UGYA:-Kqe-CM6AQ3B2N17UGYB:b8dov59) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/pose_closed_form_test.cc#L29)):*
> ```cpp
>   // Expect principal axes for PCA, where `Bp` is the body frame that aligns
>   // with the principal axes.
>   Isometry3d X_BB = Isometry3d::Identity();
> ```

BTW, how about defining this right before it's used? since this seems just for visualization.

---

*[drake/perception/estimators/dev/test/pose_closed_form_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqe4S9P9-oQH97i0eAc:-Kqe4S9P9-oQH97i0eAd:bhk08dr) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/pose_closed_form_test.cc#L33)):*
> ```cpp
>   X_BBp.linear() << Vector3d::UnitZ(), Vector3d::UnitX(), Vector3d::UnitY();
>   // Show the points in the world frame with identity transform.
>   // Note that `Bpi` is the body frame inferred by PCA in this instance.
> ```

BTW, how about renaming `Bpi` to `Bpb`?

---

*[drake/perception/estimators/dev/test/pose_closed_form_test.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqe4_s_-5yU8wDTjHo5:-Kqe4_saP9wryMTFh0N_:bjovctf) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/pose_closed_form_test.cc#L52)):*
> ```cpp
>   // Compute PCA for body. Note that frame `Bj` is also inferred by PCA, and
>   // may not represent the same frame as `Bi` due to axis sign permutations.
>   Isometry3d X_WBpj_pca = EstimatePcaBodyPose(points_B_W);
> ```

BTW, how about renaming `Bpj` to `Bpw`?

---

*[drake/perception/estimators/dev/test/test_util.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdaGc2SYJgphL2GQKl:-KqdaGc2SYJgphL2GQKm:b-grud0u) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L70)):*
> ```objc
> 
> /*
>  * Expect that R ∈ SO(3) => R'R = I, det(R) = 1
> ```

BTW, could the notation of `'` be clearer?
How about using `transpose()` instead?

---

*[drake/perception/estimators/dev/test/test_util.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqddYnpaNBHg4zu-1dH:-KqddYnpaNBHg4zu-1dI:b-os00vd) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L72)):*
> ```objc
>  * Expect that R ∈ SO(3) => R'R = I, det(R) = 1
>  */
> ::testing::AssertionResult ExpectRotation(const Eigen::Matrix3d& R,
> ```

BTW, how about `ExpectSO3`? This is more intuitive I think.

---

*[drake/perception/estimators/dev/test/test_util.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdidE561-ZOcPZo20k:-KqdidE561-ZOcPZo20l:b6vead0) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L73)):*
> ```objc
>  */
> ::testing::AssertionResult ExpectRotation(const Eigen::Matrix3d& R,
>                                           double tolerance = 0.0);
> ```

BTW, how about adding a comment for `tolerance`?

The same comment for all below.

---

*[drake/perception/estimators/dev/test/test_util.h, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdfKiifCFJr8YMv5M7:-KqdfKiifCFJr8YMv5M8:b-hqjjcn) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L85)):*
> ```objc
>  * Compare `R_actual` against `R_expected` to ensure that the axes are
>  * aligned, but may have different signs. This is done by checking:
>  *   tr(abs(R_expected' R_actual)) == 3
> ```

BTW, the same comment for `'` as above.

---

*[drake/perception/estimators/dev/test/test_util.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdfQ2Z_9finRikreMQ:-KqdfQ2Z_9finRikreMR:b-goknbk) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L87)):*
> ```objc
>  *   tr(abs(R_expected' R_actual)) == 3
>  */
> ::testing::AssertionResult CompareRotationWithoutAxisSign(
> ```

BTW, the same comment for `Rotation` as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-:-Kqe4q5-EmFsQDxDNysH:b-u0hirt)*

**Comment by kunimatsu-tri** [comment]
*[drake/perception/estimators/dev/pose_closed_form.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqe5CFC6J9Fx3Ta7K8W:-Kqe5CFC6J9Fx3Ta7K8X:bm6sfgx) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/pose_closed_form.h#L18)):*
> ```objc
>  * @param X_WB The pose of the inferred shape in the world frame.
>  */
> Eigen::Isometry3d EstimatePcaBodyPose(const Eigen::Matrix3Xd& y_W);
> ```

How about naming `Compute` instead of `Estimate` for the consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6768)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 12 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/perception/estimators/dev/pose_closed_form.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdkuUkHHvQ-7UZnv0n:-Kqy3hMprA_nnZfnwf3J:b2c2ps5) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/pose_closed_form.h#L16)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, is that OK for return value to use `@param` instead of `@return`?  If so, please just ignore this comment.
</blockquote></details>

Done. Nope, I had forgotten to change that when I swapped the signature. Thanks!

---

*[drake/perception/estimators/dev/pose_closed_form.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqe5CFC6J9Fx3Ta7K8W:-Kqy3mRxhypF2DlNwAeA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/pose_closed_form.h#L18)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

How about naming `Compute` instead of `Estimate` for the consistency?
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/pose_closed_form.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqduZlGF5y_lQeqs7rP:-Kqy6lNg9XXYmoWnZ-kB:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/pose_closed_form.h#L29)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

It's great to refer to the literature!

I think it's more suitable to refer to:
Arun, K. Somani, Thomas S. Huang, and Steven D. Blostein. "Least-squares fitting of two 3-D point sets." IEEE Transactions on pattern analysis and machine intelligence 5 (1987): 698-700.
since it's not performing ICP in this implementation.
</blockquote></details>

Done. Thanks!

---

*[drake/perception/estimators/dev/test/pose_closed_form_test.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqdvqm9D1eD8ZnkvhV9:-Kqy6niypbEfFsgUHZ31:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/pose_closed_form_test.cc#L17)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, we might want to avoid using the term `Icp` here since it's not iterative in this implementation.
How about `PoseRegistration` instead?
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/pose_closed_form_test.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqe-CM6AQ3B2N17UGYA:-Kqy7ai0e--0ajModSuZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/pose_closed_form_test.cc#L29)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, how about defining this right before it's used? since this seems just for visualization.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/pose_closed_form_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqe4S9P9-oQH97i0eAc:-Kqy7a5liF1X-mKkNhXb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/pose_closed_form_test.cc#L33)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, how about renaming `Bpi` to `Bpb`?
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/pose_closed_form_test.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-Kqe4_s_-5yU8wDTjHo5:-Kqy7_--gqkMQc6nSxIy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/pose_closed_form_test.cc#L52)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, how about renaming `Bpj` to `Bpw`?
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/test_util.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdaGc2SYJgphL2GQKl:-Kqy8VsiUv3dxU5L_eFn:bgtzj7a) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L70)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, could the notation of `'` be clearer?
How about using `transpose()` instead?


</blockquote></details>

Done (using LaTeX to Unicode).

---

*[drake/perception/estimators/dev/test/test_util.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqddYnpaNBHg4zu-1dH:-Kqy8ZpExsDLQKZz4Fp0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L72)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, how about `ExpectSO3`? This is more intuitive I think.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/test_util.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdidE561-ZOcPZo20k:-Kqy9VA2mNKlX-b0mxSh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L73)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, how about adding a comment for `tolerance`?

The same comment for all below.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/test_util.h, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdfKiifCFJr8YMv5M7:-Kqy9bQ6tIchIaSBlqqC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L85)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, the same comment for `'` as above.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/test_util.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdfQ2Z_9finRikreMQ:-KqyA9OWDgTqxNYTlS14:bo1up5j) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L87)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, the same comment for `Rotation` as above.
</blockquote></details>

Done.

Actually, not sure if I like SO3 more than rotation. Perhaps RotMat?
If I should stick with SO3, then should use SE3 rather than Transform?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6768)*

**Comment by kunimatsu-tri** [comment]
Thanks!

:lgtm: with some minor BTW comments.

---

Reviewed 10 of 10 files at r2.
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/perception/estimators/dev/test/test_util.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqyL8gwUNBrSAEqKQF9:-KqyL8gwUNBrSAEqKQFA:b-9mvh4l) ([raw file](https://github.com/robotlocomotion/drake/blob/33942d61d965de1a688f5eedbed234dff7a01a47/drake/perception/estimators/dev/test/test_util.cc#L88)):*
> ```cpp
> 
> AssertionResult ExpectSO3(const Eigen::Matrix3d& R,
>                                      double tolerance) {
> ```

BTW, indent is misaligned.

---

*[drake/perception/estimators/dev/test/test_util.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdidE561-ZOcPZo20k:-KqyM-mBMTc8XHXgxTTO:berwrx2) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L73)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, thanks! Would it be possible to write more precisely?

There are three types of comparison using the tolerance in this file:

1) the tolerance for determining equivalence of determinant,
2) the tolerance for determining element-wise equivalence between two matrices, and
3) the tolerance for determining equivalence of trace.

---

*[drake/perception/estimators/dev/test/test_util.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdfQ2Z_9finRikreMQ:-KqyItaH8ClKakTA8CYh:bprlca0) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L87)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.

Actually, not sure if I like SO3 more than rotation. Perhaps RotMat?
If I should stick with SO3, then should use SE3 rather than Transform?
</blockquote></details>

Sorry, my comment was unclear.

The point is that it was a bit unclear to me whether the name `ExpectRotation` is expecting the argument to be a rotation matrix or to have certain amount of rotation.  In that sense, `RotMat` is fine with me.

And, yes I agree,  the mixed use of SO3 and Transform is a bit weird.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-:-KqyQsEfp-lvSVtT6Caf:bvx9ta9)*

**Comment by EricCousineau-TRI** [comment]
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/perception/estimators/dev/test/test_util.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqyL8gwUNBrSAEqKQF9:-KqyS_jI61WWK1oeqzQq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/33942d61d965de1a688f5eedbed234dff7a01a47/drake/perception/estimators/dev/test/test_util.cc#L88)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, indent is misaligned.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/test_util.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdidE561-ZOcPZo20k:-KqyVIDxtWdDTYwfN1KG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L73)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, thanks! Would it be possible to write more precisely?

There are three types of comparison using the tolerance in this file:

1) the tolerance for determining equivalence of determinant,
2) the tolerance for determining element-wise equivalence between two matrices, and
3) the tolerance for determining equivalence of trace.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/test_util.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-KqdfQ2Z_9finRikreMQ:-KqyVHOIZQgfrfA1iiR-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91512e9dde3dfc157ac645d555107da9208f5fb9/drake/perception/estimators/dev/test/test_util.h#L87)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Sorry, my comment was unclear.

The point is that it was a bit unclear to me whether the name `ExpectRotation` is expecting the argument to be a rotation matrix or to have certain amount of rotation.  In that sense, `RotMat` is fine with me.

And, yes I agree,  the mixed use of SO3 and Transform is a bit weird.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6768)*

**Comment by EricCousineau-TRI** [comment]
+@seancurtis-tri for platform review on non-`dev/` portions.

---

Review status: 9 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-:-Kqyg2e6QfsEbfv-kwtq:b-45gdtg)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: on the cmake cleanup. Dev ignored. +@jwnimmer-tri for final review.

---

Review status: 9 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-:-KqyhWDiBG717PTmjKw3:bs8ub3k)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform on the CMake removal.

FYI Don't let  the sum total of `dev` get too big, or it will take _forever_ to push it through platform review later (roughly estimate it as however long as it took to get it into dev in the first place).  +1 to staying close to master, but don't defer technical debt too long.

---

Reviewed 3 of 10 files at r2.
Review status: 9 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6768#-:-Kqz2o2vgSp9p12nXkTX:bav7jom)*

**Pull request merged**
