### PR TITLE
Improve the warning message when the Hessian type is indefinite.

### LINKED ISSUE #21552: Getting `UpdateHessianType()` warnings in Drake 1.29.0
### What happened?

When I upgraded from Drake 1.28.0 to 1.29.0, I started getting these really loud warnings printed to my console:

```
WARNING:drake:UpdateHessianType(): Unable to determine Hessian type of the Quadratic Constraint.
Falling back to indefinite Hessian type.
```

Seems to be directly due to https://github.com/RobotLocomotion/drake/pull/21411

Nothing else seems to have been affected, but I'd like to be able to resolve these in some way. Are there any resources for what this may mean, and how to fix it?

My offending constraints look as follows:

```python
        for n in range(num_dofs):
           for k in range(num_waypoints - 1):
                prog.AddConstraint(
                    xc[k, n]
                    == 0.5 * (x[k, n] + x[k + 1, n])
                    + (h[k] / 8.0) * (x_d[k, n] - x_d[k + 1, n])
                )
```

Where `xc`, `x`, `x_d`, and `h` are all continuous variables in my program. By process of elimination, it seems that the issue is in the multiplication of `h[k]` by the sub-elements of `x_d`, since that is the quadratic term.

### Version

1.29.0

### What operating system are you using?

Ubuntu 24.04

### What installation option are you using?

pip install drake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #21552

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21553)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21553#-:-NzxvAm44VX1fQ4Hi9C6:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21553)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/constraint.cc` line 168 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21553#-Nzy7iyU7oFnkmqHZw4Q:-Nzy7iyU7oFnkmqHZw4R:b-63hmmh) ([raw file](https://github.com/RobotLocomotion/drake/blob/702ae4e648c87d8993698608223a02e569491079/solvers/constraint.cc#L168)):*
> ```cpp
>     // Fall back to an indefinite Hessian type if we cannot determine the
>     // Hessian type.
>     drake::log()->warn(
> ```

Should we bump from `drake::log()->warn` to `drake::log()->debug`? My hope was to avoid surprises where some thinks they are putting in something convex, and we are failing to detect it, but I think the LDLt solver fails mostly on indefinite quadratics.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21553)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/constraint.cc` line 168 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21553#-Nzy7iyU7oFnkmqHZw4Q:-O-D0MzR3bRcqEa6HM6k:b55s6jm) ([raw file](https://github.com/RobotLocomotion/drake/blob/702ae4e648c87d8993698608223a02e569491079/solvers/constraint.cc#L168)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Should we bump from `drake::log()->warn` to `drake::log()->debug`? My hope was to avoid surprises where some thinks they are putting in something convex, and we are failing to detect it, but I think the LDLt solver fails mostly on indefinite quadratics.
</blockquote></details>

I think this warning message helps. Often cases the user call AddQuadraticConstraint, expecting a convex constraint, so receiving this warning message would remind the user that there might be some numerical problem in the constraint. Besides, by telling the users how to mute this warning, the users can also speed up their code by setting the `hessian_type` explicitly.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21553#-:-O-IG3rzAoHgdVmX-gjc:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
+@EricCousineau-TRI for platform review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21553#-:-O-IG8aACptxvx_EP2NF:b-2ku30v)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21553#-:-O-IHc3aAafi0mlV_vsE:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21553)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/constraint.cc` line 171 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21553#-O-IHl1y93-fwhZ8HMKh:-O-IHl1z9k3viRXCGym6:b-cuu1qa) ([raw file](https://github.com/RobotLocomotion/drake/blob/702ae4e648c87d8993698608223a02e569491079/solvers/constraint.cc#L171)):*
> ```cpp
>         "UpdateHessianType(): Unable to determine Hessian type of the "
>         "Quadratic Constraint. Falling back to indefinite Hessian type. To get "
>         "rid of this warning, set hessian_type explicitly when you construct "
> ```

nit Sorry, small nit: Is it worth specifying the exact type here? e.g. `QuadraticConstraint.HessianType.kIndefinite`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21553)* status: 1 unresolved discussion, missing label for release notes

___
*[`solvers/constraint.cc` line 171 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21553#-O-IHl1y93-fwhZ8HMKh:-O1edXPQ9K8LroCWwb74:bp6lh13) ([raw file](https://github.com/RobotLocomotion/drake/blob/702ae4e648c87d8993698608223a02e569491079/solvers/constraint.cc#L171)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Sorry, small nit: Is it worth specifying the exact type here? e.g. `QuadraticConstraint.HessianType.kIndefinite`
</blockquote></details>

Sorry for the belated reply.

I reworded the error message. The users might specify other exact types, different from `kIndefinite`. Here ldlt failure might come from the numerical error of Eigen's LDLT solver, while the matrix is actually positive semidefinite.

**Pull request merged**
