### PR TITLE
Add Expression::Differentiate

### PR DESCRIPTION
**Pull request by soonho-tri**
Close https://github.com/RobotLocomotion/drake/issues/4879

It's over 565 LOC, but 300 out of 565 is in `test/symbolic_expression_differentiation_test.cc`

Related issue: https://github.com/RobotLocomotion/drake/issues/4421. `Jacobian` is a simple extension of `Differentiate` method.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5061)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-:-KcINMCfBSEyFHSn2Gxi:b-utjvo1)*

**Comment by jwnimmer-tri** [comment]
... also note that its 565 lines in github diff -- the SLOC (source lines of code) is likely under the rule of 500.

**Comment by hongkai-dai** [comment]
How about we add a test, to evaluate the differentiated expression, and compare the Eigen's autodiffscalar result?

---

Reviewed 3 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 676 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcJXCsxRlzc9voH5_65:-KcJXCsyIEJawgCtjYia:b-wcrn0r) ([raw file](https://github.com/robotlocomotion/drake/blob/135ca02778c29356a92e864adf5522c1d50b3318/drake/common/symbolic_expression_cell.cc#L676)):*
> ```cpp
>     //     d/dx pow(f, n) = n * pow(f, n - 1) * d/dx f
>     return n * pow(f, n - 1) * f.Differentiate(x);
>   } else {
> ```

A special case for `is_constant(f)`?

---

*[drake/common/symbolic_expression_cell.cc, line 693 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcJXtIgO4EEhmKpPB3M:-KcJXtIgO4EEhmKpPB3N:b-i1dsrx) ([raw file](https://github.com/robotlocomotion/drake/blob/135ca02778c29356a92e864adf5522c1d50b3318/drake/common/symbolic_expression_cell.cc#L693)):*
> ```cpp
>   const map<Expression, Expression>& m{base_to_expnt_map_};
>   Expression ret{Expression::Zero()};
>   for (auto it1 = m.begin(); it1 != m.end(); ++it1) {
> ```

Will it be faster, if we first first get `p = f1^g1 * f2^g2 * ... * fn^gn`, and then for each row of the documentation above, we compute `f1^g1 * ... * (d/dx fi^gi) * ... * fn&gn` as `p/(fi^gi) * (d/dx fi^gi)`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-:-KcJ_C7OI_BcmubUZpWA:bgm9kmg)*

**Comment by soonho-tri** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 676 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcJXCsxRlzc9voH5_65:-KcO3FTdQfZtTDrVjKWe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/135ca02778c29356a92e864adf5522c1d50b3318/drake/common/symbolic_expression_cell.cc#L676)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

A special case for `is_constant(f)`?
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression_cell.cc, line 693 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcJXtIgO4EEhmKpPB3M:-KcOAVZHAFcX7kvUkf5g:b-jv166h) ([raw file](https://github.com/robotlocomotion/drake/blob/135ca02778c29356a92e864adf5522c1d50b3318/drake/common/symbolic_expression_cell.cc#L693)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Will it be faster, if we first first get `p = f1^g1 * f2^g2 * ... * fn^gn`, and then for each row of the documentation above, we compute `f1^g1 * ... * (d/dx fi^gi) * ... * fn&gn` as `p/(fi^gi) * (d/dx fi^gi)`? 
</blockquote></details>

Done.

Note that I put ` * pow(base, -expnt)` instead of `/ pow(base, expnt)`. It's because the required simplification for `/` is not implemented yet. I'll added it later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061)*

**Comment by soonho-tri** [comment]
It already includes numerical tests using newton's difference quotient. I thought that these are enough..

---

Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcOBhtnjd4bOh4Nlf9T:-KcOBhtnjd4bOh4Nlf9U:b-qoa6av) (no related file):*
+@david-german-tri , platform-review please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-:-KcOB4p1FKUE4jzu6McL:b-tyc00b)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-:-KcObMJPBkPU8jSIl-2p:bnfp4nl)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by david-german-tri** [comment]
Reviewed 2 of 7 files at r1, 1 of 3 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 680 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcP56uF1PMUVyHjub0e:-KcP56uF1PMUVyHjub0f:b-8cutnv) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L680)):*
> ```cpp
>     // Special case where base is a constant:
>     //     d/dx pow(n, g) = log(n) * pow(n, g) * d/dx g
>     return log(n) * pow(n, g) * g.Differentiate(x);
> ```

BTW it is eternally confusing to me that `std::log` is the name for `ln`.  I have to look it up every time just to be sure.

---

*[drake/common/symbolic_expression_cell.cc, line 684 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcP7Ri6dSpusFzVbQHl:-KcP7Ri6dSpusFzVbQHm:b-z3i9gk) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L684)):*
> ```cpp
>     // General case:
>     //    d/dx pow(f, g)
>     // =  pow(f, g - 1) * (g * (d/dx f) + f * log(f) * (d/dx g))
> ```

BTW, this is correct, of course, but jumping straight here without spelling out the chain rule hurt my brain a little.  Consider inserting:

```
// = ∂/∂f pow(f, g) * d/dx f + ∂/∂g pow(f, g) * d/dx g
// = g * pow(f, g - 1) * d/dx f + log(f) * pow(f, g) * d/dx g
```

---

*[drake/common/symbolic_expression_cell.cc, line 702 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPErnowmrWFadIOS4W:-KcPErnowmrWFadIOS4X:b-p5ei9m) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L702)):*
> ```cpp
>   const Expression expr{
>       ExpressionMulFactory{1.0, base_to_expnt_map_}.GetExpression()};
>   for (auto it1 = m.begin(); it1 != m.end(); ++it1) {
> ```

BTW consider `for (const auto& term : m)` here.

---

*[drake/common/symbolic_expression_cell.cc, line 980 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPN6jfeh3jREvdWIcy:-KcPN6jgG1SiRoLuJcCX:b-hew65u) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L980)):*
> ```cpp
> 
> Expression ExpressionSqrt::Differentiate(const Variable& x) const {
>   // d/dx (sqrt(f)) = 1 / (2 * sqrt(f)) * (d/dx f')
> ```

BTW spurious apostrophe?

---

*[drake/common/symbolic_expression_cell.cc, line 1092 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPN_W0RpuCp3DBeShO:-KcPN_W0RpuCp3DBeShP:b-qjgkg4) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L1092)):*
> ```cpp
> 
> Expression ExpressionTan::Differentiate(const Variable& x) const {
>   // d/dx (tan f) = 1 / (cos f)^2 * (d/dx f)
> ```

BTW an extra set of parentheses, as below, would make this easier to read.

---

*[drake/common/symbolic_expression_cell.cc, line 1094 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPNcnr1umT-fKpWNtZ:-KcPNcnsuqzCUfJe4vPh:bjaszah) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L1094)):*
> ```cpp
>   // d/dx (tan f) = 1 / (cos f)^2 * (d/dx f)
>   const Expression& f{get_argument()};
>   return 1 / pow(cos(f), 2) * f.Differentiate(x);
> ```

BTW also here

---

*[drake/common/test/symbolic_expression_differentiation_test.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPPSJa-jAadkp882Yy:-KcPPSJa-jAadkp882Yz:b769md5) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/test/symbolic_expression_differentiation_test.cc#L61)):*
> ```cpp
>   check_list.emplace_back(x, var_x_, 1);
>   // d/dx (2 + x + y + z) = 1
>   check_list.emplace_back(2 + x, var_x_, 1);
> ```

I don't see how this squares with the comment

---

*[drake/common/test/symbolic_expression_differentiation_test.cc, line 293 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPVSDOM-AGRyt-Ncne:-KcPVSDP9r7CbfcsPThs:b-gswcoq) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/test/symbolic_expression_differentiation_test.cc#L293)):*
> ```cpp
>           EXPECT_NEAR(grad, diff, eps);
>         } catch (const exception&) {
>           // ignore domain_error/runtime_error
> ```

Instead, please `EXPECT_THROW` the specific combinations that should throw.  As written, this doesn't protect us from a regression where a combination that didn't throw begins to do so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061)*

**Comment by soonho-tri** [comment]
Review status: 2 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 680 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcP56uF1PMUVyHjub0e:-KcPWMjSgHsR6pAL-Deo:b-yctndq) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L680)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW it is eternally confusing to me that `std::log` is the name for `ln`.  I have to look it up every time just to be sure.
</blockquote></details>

:-) I know.. But we have to be consistent with the corresponding one in `std::` world..

---

*[drake/common/symbolic_expression_cell.cc, line 684 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcP7Ri6dSpusFzVbQHl:-KcQVNgOYY7ENtptsFEE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L684)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, this is correct, of course, but jumping straight here without spelling out the chain rule hurt my brain a little.  Consider inserting:

```
// = ∂/∂f pow(f, g) * d/dx f + ∂/∂g pow(f, g) * d/dx g
// = g * pow(f, g - 1) * d/dx f + log(f) * pow(f, g) * d/dx g
```
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression_cell.cc, line 702 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPErnowmrWFadIOS4W:-KcQVYaMEkHyv8ktg13t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L702)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW consider `for (const auto& term : m)` here.
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression_cell.cc, line 980 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPN6jfeh3jREvdWIcy:-KcQVbouuXRABPzfuYv4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L980)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW spurious apostrophe?
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression_cell.cc, line 1092 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPN_W0RpuCp3DBeShO:-KcQWLMNv06FjyOO6j80:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L1092)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW an extra set of parentheses, as below, would make this easier to read.
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression_cell.cc, line 1094 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPNcnr1umT-fKpWNtZ:-KcQWNQ661rxeu5gnsgD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/symbolic_expression_cell.cc#L1094)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW also here
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_expression_differentiation_test.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPPSJa-jAadkp882Yy:-KcQWYUGcTF5e5ELngxg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/test/symbolic_expression_differentiation_test.cc#L61)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I don't see how this squares with the comment
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_expression_differentiation_test.cc, line 293 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPVSDOM-AGRyt-Ncne:-KcQiJVpg7Fpj4vZ8nQT:b-4oengk) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/test/symbolic_expression_differentiation_test.cc#L293)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Instead, please `EXPECT_THROW` the specific combinations that should throw.  As written, this doesn't protect us from a regression where a combination that didn't throw begins to do so.
</blockquote></details>

I actually changed this part differently from your comment. But I think this is correct. 

We skip a combination only if `f.Evaluate(env)` throws a `domain_error`. Otherwise both `grad` and `diff` should be computed without an exception and the results should be close enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061)*

**Comment by david-german-tri** [comment]
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_differentiation_test.cc, line 293 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPVSDOM-AGRyt-Ncne:-KcTKYRttavDg-_xT8Y5:bh3lqu) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/test/symbolic_expression_differentiation_test.cc#L293)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I actually changed this part differently from your comment. But I think this is correct. 

We skip a combination only if `f.Evaluate(env)` throws a `domain_error`. Otherwise both `grad` and `diff` should be computed without an exception and the results should be close enough.
</blockquote></details>

Still, if more test cases start throwing `domain_error`, we won't know.  This should really be more precise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061)*

**Comment by soonho-tri** [comment]
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_differentiation_test.cc, line 293 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPVSDOM-AGRyt-Ncne:-KcT_zk9AnPnz0sI_UD1:b-cjqjf) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/test/symbolic_expression_differentiation_test.cc#L293)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Still, if more test cases start throwing `domain_error`, we won't know.  This should really be more precise.
</blockquote></details>

For the record, had f2f with @david-german-tri. Here is the action item: I'll split this test into two separate tests - one test with functions possibly throwing `domain_error`, another test with functions not throwing `domain_error`. The goal is to eliminate `catch` and `continue` that we have in the current code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 7 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061)*

**Comment by soonho-tri** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_differentiation_test.cc, line 293 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPVSDOM-AGRyt-Ncne:-KcU1L6tWEanHlFGk_BC:b-896fig) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/test/symbolic_expression_differentiation_test.cc#L293)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

For the record, had f2f with @david-german-tri. Here is the action item: I'll split this test into two separate tests - one test with functions possibly throwing `domain_error`, another test with functions not throwing `domain_error`. The goal is to eliminate `catch` and `continue` that we have in the current code.
</blockquote></details>

Done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_differentiation_test.cc, line 293 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-KcPVSDOM-AGRyt-Ncne:-KcU3HWbTZup1eSPOYpT:bgx6jg3) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b6d386ab736d25f66ea9749a48075245818206/drake/common/test/symbolic_expression_differentiation_test.cc#L293)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

Excellent, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5061#-:-KcU3R5Eja6D9XOrmmCw:bnfp4nl)*

**Pull request merged**
