### PR TITLE
Deprecate SeparatingPlaneOrder.

### LINKED ISSUE #19523: CIrisSeparatingPlane can cause copy slicing
### What happened?

In https://github.com/RobotLocomotion/drake/pull/19368 we introduced the child class [CIrisSeparatingPlane](https://github.com/RobotLocomotion/drake/blob/master/geometry/optimization/c_iris_separating_plane.h), derived from `CSpaceSeparatingPlane`. But this might cause copy slicing, as both the parent and the child class have default copy and move constructor, and they don't have the virtual destructor.

Now I wonder why we introduced this `CIrisSeparatingPlane` class. It has an additional `plane_order` member field. I would think that in both CspaceFreePath and CspaceFreePolytope, it would use the plane order? So why we do not put this `plane_order` in the parent class `CSpaceSeparatingPlane` class, remove the derived `CIrisSeparatingPlane` class, and use the parent class CspaceSeparatingPlane directly?

I do feel the class inheritance is a land mine in the cspace_free_xxx files. I think @jwnimmer-tri 's suggestion on using more "has-a" relationship makes a lot of sense, at least here in this CIrisSeparatingPlane class (because I like this class to be copyable). If we decide to keep it, I like it better to be has-a rather than is-a.

cc @AlexandreAmice for the class design.
cc @jwnimmer-tri for the discussion on the copy slicing.

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hongkai-dai**
Use an integer to denote the separating plane order instead of the enum SeparatingPlaneOrder. Also deprecate CIrisSeparatingPlane, and only uses the parent CSpaceSeparatingPlane class. This is a breaking change as the return type of CspaceFreePolytopeBase::separating_planes() is changed from CIrisSeparatingPlane to CSpaceSeparatingPlane.

Resolves #19523 

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_7_VypEwatWbvvAx0a:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
+(release notes: breaking change). 

Since this is a breaking change anyway I'll let the platform reviewer decide whether to deprecate the enum or simply rip the bandaid off immediately.

> Reviewed 13 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_EADn34VRqpr8vAGvQ:b-vwxx0h)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/cspace_free_box.h` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_EAp_y1fXzFu_m5cJB:-N_EAp_y1fXzFu_m5cJC:b8slqoo) ([raw file](https://github.com/RobotLocomotion/drake/blob/66890089e46fa358656c3151f97f24e208a37857/geometry/optimization/cspace_free_box.h#L162)):*
> ```objc
>    must outlive this CspaceFreeBox object.
>    @param scene_graph The scene graph that has been connected with `plant`. It
>    must outlive this CspaceFreeBox object.
> ```

Should this doc string stay in during the deprecation?
___
*[`geometry/optimization/cspace_free_polytope_base.cc` line 159 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_EBRMXCWT5mlUTjGLX:-N_EBRMXCWT5mlUTjGLY:buk3ha6) ([raw file](https://github.com/RobotLocomotion/drake/blob/66890089e46fa358656c3151f97f24e208a37857/geometry/optimization/cspace_free_polytope_base.cc#L159)):*
> ```cpp
>           throw std::runtime_error(
>               fmt::format("CspaceFreePolytopeBase: plane_degree={}, only "
>                           "support plane_degree=1.",
> ```

nit: typo "supports"

**Review by AlexandreAmice — COMMENTED** [review]
I am not sure I agree with getting rid of the enum entirely for `CspaceFreePolytope`. I believe that we only ever intend on supporting `kAffine`. Ambitiously, I think we would only support a very limited set and so it would be good if the user didn't have the flexibility to set this to anything more than the handful of enums.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_EBfVQ0_PGN627Iqt8:b-4q4v4f)* status: 4 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/cspace_free_box.h` line 146 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_EDkHLBzUNtGB6uE-z:-N_EDkHLBzUNtGB6uE0-:b1ojpuv) ([raw file](https://github.com/RobotLocomotion/drake/blob/66890089e46fa358656c3151f97f24e208a37857/geometry/optimization/cspace_free_box.h#L146)):*
> ```objc
>    @param scene_graph The scene graph that has been connected with `plant`. It
>    must outlive this CspaceFreeBox object.
>    @param plane_degree The degree of the polynomials in the plane to separate a
> ```

See comment in `CspaceFreePolytope` about `plane_degree`
___
*[`geometry/optimization/cspace_free_polytope.h` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_EDMW78Uow7v5VIuGE:-N_EDMW78Uow7v5VIuGF:bb9gtyw) ([raw file](https://github.com/RobotLocomotion/drake/blob/66890089e46fa358656c3151f97f24e208a37857/geometry/optimization/cspace_free_polytope.h#L84)):*
> ```objc
>    @param scene_graph The scene graph that has been connected with `plant`. It
>    must outlive this CspaceFreePolytope object.
>    @param plane_degree The degree of the polynomials in the plane to separate a
> ```

If we deprecate the enum, then this must document that we only support `plane_degree == 1`. Also I don't really like the "plane_degree" formulation here because in the multivariate setting this gets a little bit ambiguous. Do we **always** mean the dense, monomial basis of degree `plane_degree`?

**Review by hongkai-dai — COMMENTED** [review]
> I believe that we only ever intend on supporting `kAffine`. Ambitiously, I think we would only support a very limited set and so it would be good if the user didn't have the flexibility to set this to anything more than the handful of enums.

Right. Currently in our code, we throw an error if `plane_degree` is not 1. https://github.com/hongkai-dai/drake/blob/66890089e46fa358656c3151f97f24e208a37857/geometry/optimization/cspace_free_polytope_base.cc#L142-L162

We could keep the enum`SeparatingPlaneOrder` if you like, and only keep the constructor in CspaceFreePolytope that takes the `SeparatingPlaneOrder`, remove the constructor that takes the int `plane_degree`. Hence at the compile time the user can only use kAffine, instead of using an incorrect integer and get a runtime error. But I do want to get rid of the `CIrisSeparatingPlane` class as it is redundant. Would you prefer this version?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_F60uCBJDYePXb4RsG:bpdsesq)* status: 4 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by AlexandreAmice — COMMENTED** [review]
Yes I like the plan of keeping the `SeparatingPlaneOrder` enum, but getting rid of `CIrisSeparatingPlane`

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_H3q7S1dD1UR0z-SfH:bg9w105)* status: 4 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
Done. I changed the PR to keep SeparatingPlaneOrder.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_K9Uea4YZ4yq31y2f_:be8z3tf)* status: 3 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/cspace_free_box.h` line 146 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_EDkHLBzUNtGB6uE-z:-N_K9eIl5kHR4MUG9m9M:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/66890089e46fa358656c3151f97f24e208a37857/geometry/optimization/cspace_free_box.h#L146)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

See comment in `CspaceFreePolytope` about `plane_degree`
</blockquote></details>

Done.
___
*[`geometry/optimization/cspace_free_box.h` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_EAp_y1fXzFu_m5cJB:-N_K9fuU3vMJXXN_1pIw:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/66890089e46fa358656c3151f97f24e208a37857/geometry/optimization/cspace_free_box.h#L162)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Should this doc string stay in during the deprecation?
</blockquote></details>

Done.
___
*[`geometry/optimization/cspace_free_polytope.h` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_EDMW78Uow7v5VIuGE:-N_K9hbZE0oTn3f8MYQs:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/66890089e46fa358656c3151f97f24e208a37857/geometry/optimization/cspace_free_polytope.h#L84)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

If we deprecate the enum, then this must document that we only support `plane_degree == 1`. Also I don't really like the "plane_degree" formulation here because in the multivariate setting this gets a little bit ambiguous. Do we **always** mean the dense, monomial basis of degree `plane_degree`?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756)* status: 4 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/cspace_separating_plane.h` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_KAt4yBOFrHJZNILj6:-N_KAt4yBOFrHJZNILj7:b-t6mwsa) ([raw file](https://github.com/RobotLocomotion/drake/blob/9c4f961ea80df1a4fe028b0077e1e27d37e2bf49/geometry/optimization/cspace_separating_plane.h#L29)):*
> ```objc
> enum class SeparatingPlaneOrder {
>   kAffine = 1,  ///< a and b are affine function of s.
>   // N.B. Never add new enum values here!
> ```

Give Alex's request that we expand this set in the future (as the rationale for keeping this enum aroaund), this comment seems inappropriate and dangerous.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: modulo deciding whether to rip off the bandaid immediately for the deprecation considering that this is a breaking change anyway

> Reviewed 1 of 17 files at r1, 15 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_PISLo6ncLJtVDw4aH:b1ow65)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for Monday's platform review.

@ggould-tri what is our strategy for deprecation? As Alex mentioned, I have removed all usage of `CIrisSeparatingPlane` in our code. Since this PR is a breaking change, I could get rid of this class in this PR rather than waiting for 4 months.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_WYPnk4MbDR0iw10r3:b-qt00tv)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
My view:  If the old class is no longer used after a breaking change, it doesn't break anything additional to remove the class:  If a user was using that class for anything, the breaking change of not returning it any more already broke what they were doing.  Just kill it, with a clear commit message for the release engineer.

Marking this +(status: do not review) until you make the deletion so that I don't get confused in my workflow; remove it whenever is convenient.

> Reviewed 3 of 17 files at r1, 15 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_ZJa_m4eUu_rg7pi_c:b-l4isz0)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform)

___
*[`geometry/optimization/cspace_separating_plane.h` line 29 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_ZLIq2DNM9pq6BesJR:-N_ZLIq2DNM9pq6BesJS:b-h7si4w) ([raw file](https://github.com/RobotLocomotion/drake/blob/2a0e18e56dfc14713d134ada45efbb7796d87480/geometry/optimization/cspace_separating_plane.h#L29)):*
> ```objc
> enum class SeparatingPlaneOrder {
>   kAffine = 1,  ///< a and b are affine function of s.
> };
> ```

minor:  This whole comment is a bit of a mess, with inconsistent and odd whitespace, singular/plural, and degree-versus-order confusion.  Suggestion below.



_Suggestion:_
```objc
/** The separating plane aᵀx + b ≥ δ, aᵀx + b ≤ −δ has parameters a and b.
 These parameterize a polynomial function of `s_for_plane` with the
 specified order.  `s_for_plane` is a sub set of the configuration-space
 variable `s`, please refer to the RationalForwardKinematics class or
 the paper above on the meaning of s.
 */
enum class SeparatingPlaneOrder {
  kAffine = 1,  ///< a and b are affine functions of s.
};
```
___
*[`geometry/optimization/cspace_separating_plane.cc` line 105 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_ZLvpV6B7uVrj2ZQil:-N_ZLvpV6B7uVrj2ZQim:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/2a0e18e56dfc14713d134ada45efbb7796d87480/geometry/optimization/cspace_separating_plane.cc#L105)):*
> ```cpp
>   } else {
>     throw std::runtime_error(fmt::format(
>         "ToPlaneOrder: plane_degree={}, only support plane_degree = 1.",
> ```

typo



_Suggestion:_
```cpp
supports
```

**Review by hongkai-dai — COMMENTED** [review]
Done. I have removed the class CIrisSeparatingPlane.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_Znq9S2I1czz6M_Lsl:b8k2v55)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform)

**Comment by jwnimmer-tri** [comment]
The PR title seems out of date now.

**Review by ggould-tri — COMMENTED** [review]
-(release notes: newly deprecated) No deprecations here now.
Wow, this PR is much shorter and simpler this way :-)
:lgtm: pending PR message fix, comment fix noted below.

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-:-N_ZodgtCkniKFGg3Klh:b5e63cs)* status: 3 unresolved discussions

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19756#-N_Zoyt87-75fobLqY37):*
minor:  This is out of date, as is the title line.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19756)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice

**Pull request merged**
