### PR TITLE
PoseAggregator's AddSinglePoseAndVelocityInput() returns a struct

### LINKED ISSUE #8331: PoseAggregator Python binding trying to move an InputPortDescriptor
After a merge with master I am now getting this CI failure in my caching branch:
```
ERROR: test_pose_aggregator (rendering_test.TestRendering)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bindings/pydrake/systems/test/rendering_test.py", line 136, in test_pose_aggregator
    "pose_and_velocity", instance_id2)
RuntimeError: return_value_policy = move, but the object is neither movable nor copyable!
```
This binding was recently added in PR #8282, and is wrapping this method of PoseAggregator:
```c++
  std::pair<const InputPortDescriptor<T>&, const InputPortDescriptor<T>&>
  AddSinglePoseAndVelocityInput(const std::string& name, int model_instance_id);
```
That method creates a couple of input ports and returns references to them. I don't think it should be trying to move the InputPortDescriptors!

The reason this fails in the caching branch is that I removed the ability to move InputPortDescriptors, which is generally a bad thing to do.

@EricCousineau-TRI, @jadecastro does this actually make sense here?

### PR DESCRIPTION
**Pull request by jadecastro**
Resolves #8331.

Resurrecting #8343 (since we can no longer re-open that due to force-push)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8347)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@EricCousineau-TRI for feature review.
+@jwnimmer-tri for platform review (unless you'd prefer the on-call platform to take it)

/cc @sherm1

**Comment by jwnimmer-tri** [comment]
I am good to do it.

---

Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/rendering/pose_aggregator.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7URjKRmTFygJNv60Kj:-L7URjKRmTFygJNv60Kk:b-2ovz7s) ([raw file](https://github.com/robotlocomotion/drake/blob/53e24a70a6cb6b47362f75d87b703adfa936a7a8/systems/rendering/pose_aggregator.h#L3)):*
> ```objc
> #pragma once
> 
> #include <functional>
> ```

BTW Unused.

---

*[systems/rendering/pose_aggregator.h, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7URy4WYAMSkBi1nBxa:-L7URy4WYAMSkBi1nBxb:bad8wus) ([raw file](https://github.com/robotlocomotion/drake/blob/53e24a70a6cb6b47362f75d87b703adfa936a7a8/systems/rendering/pose_aggregator.h#L103)):*
> ```objc
>   /// @p model_instance_id.
>   ///
>   /// @return A PoseVelocityInputPortDescriptors container with descriptors for
> ```

FYI I'm not sure if `A PoseVelocityInputPortDescriptors container with ` prologue is adding much value when rendered?  I'd think the return type is already hyperlinked.  Maybe render it and see what you prefer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-:-L7URqegnKirNnC9iJWI:b-kg90bc)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/rendering_py.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7USmz0mehj0WqegXi4:-L7USmz0mehj0WqegXi5:bftcwc) ([raw file](https://github.com/robotlocomotion/drake/blob/53e24a70a6cb6b47362f75d87b703adfa936a7a8/bindings/pydrake/systems/rendering_py.cc#L76)):*
> ```cpp
>            const InputPortDescriptor<T>& {
>              return self->velocity_descriptor;
>            }, py_reference_internal);
> ```

FYI I know you're struggling with spelling on these, but if they could be attributes (to match C++) rather than methods that seems better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-:-L7USxlgWacs-QM_Ylp8:bnfp4nl)*

**Comment by jadecastro** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/rendering_py.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7USmz0mehj0WqegXi4:-L7UnE9RoxYg5N-jVwv2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53e24a70a6cb6b47362f75d87b703adfa936a7a8/bindings/pydrake/systems/rendering_py.cc#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I know you're struggling with spelling on these, but if they could be attributes (to match C++) rather than methods that seems better.
</blockquote></details>

Done.

---

*[systems/rendering/pose_aggregator.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7URjKRmTFygJNv60Kj:-L7UnGyWBeZDRR5gLf0D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53e24a70a6cb6b47362f75d87b703adfa936a7a8/systems/rendering/pose_aggregator.h#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Unused.
</blockquote></details>

Done.

---

*[systems/rendering/pose_aggregator.h, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7URy4WYAMSkBi1nBxa:-L7UndA4O4xqRWKhAb3A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53e24a70a6cb6b47362f75d87b703adfa936a7a8/systems/rendering/pose_aggregator.h#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I'm not sure if `A PoseVelocityInputPortDescriptors container with ` prologue is adding much value when rendered?  I'd think the return type is already hyperlinked.  Maybe render it and see what you prefer.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending some discussion items.

---

Reviewed 2 of 6 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/rendering_py.cc, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7UtGQhDJBo3zpwTrFK:-L7UtGQhDJBo3zpwTrFL:bnq6foc) ([raw file](https://github.com/robotlocomotion/drake/blob/dfeb15f4015ab2d6c34e7371219a03046ecf815f/bindings/pydrake/systems/rendering_py.cc#L67)):*
> ```cpp
>   py::class_<PoseVelocityInputPortDescriptors<T>>(
>       m, "PoseVelocityInputPortDescriptors")
>       .def_property_readonly("pose_descriptor",
> ```

Might it be possible to use `def_readonly` to shorten this code?
```
cls.def_readonly("pose_descriptor", &PoseVelocityInputPortDescriptor<T>::pose_descriptor, py_reference);
```

---

*[systems/rendering/pose_aggregator.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7UtkYEsl7OJnkktFJR:-L7UtkYEsl7OJnkktFJS:b-hefarz) ([raw file](https://github.com/robotlocomotion/drake/blob/dfeb15f4015ab2d6c34e7371219a03046ecf815f/systems/rendering/pose_aggregator.cc#L53)):*
> ```cpp
>   const auto& velocity_descriptor =
>       DeclareInput(MakeSingleVelocityInputRecord(name, model_instance_id));
>   return PoseVelocityInputPortDescriptors<T>{
> ```

BTW I don't believe you need to re-specify the struct, since you've specified the output value. I believe you can do:
```
return {pose_descriptor, velocity_descriptor};
```

(I don't believe this will attempt copying them as a `std::initializer_list`, because it will recognize that this is a trivial ctor.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-:-L7Uu3A_C6F2JI4yENIU:b-ii8o9k)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/systems/rendering_py.cc, line 67 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8347#-L7UtGQhDJBo3zpwTrFK:-L7Uwqxi9gsnCBEuj-73:bc5r01k) ([raw file](https://github.com/robotlocomotion/drake/blob/dfeb15f4015ab2d6c34e7371219a03046ecf815f/bindings/pydrake/systems/rendering_py.cc#L67)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Might it be possible to use `def_readonly` to shorten this code?
```
cls.def_readonly("pose_descriptor", &PoseVelocityInputPortDescriptor<T>::pose_descriptor, py_reference);
```
</blockquote></details>

D'oh, sorry, didn't see  your earlier comment in #8343. Will see if I can figure out why this breaks...

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8347)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 6 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/rendering_py.cc, line 67 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8347#-L7UtGQhDJBo3zpwTrFK:-L7UzOAb2GRDWBoOD1oU:bious6m) ([raw file](https://github.com/robotlocomotion/drake/blob/dfeb15f4015ab2d6c34e7371219a03046ecf815f/bindings/pydrake/systems/rendering_py.cc#L67)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

D'oh, sorry, didn't see  your earlier comment in #8343. Will see if I can figure out why this breaks...
</blockquote></details>

Gotcha, yup, didn't work: https://stackoverflow.com/a/8336479/7829525

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8347)*

**Comment by jadecastro** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/rendering_py.cc, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7UtGQhDJBo3zpwTrFK:-L7V3_CIiu4J-O20oh7a:b8boul3) ([raw file](https://github.com/robotlocomotion/drake/blob/dfeb15f4015ab2d6c34e7371219a03046ecf815f/bindings/pydrake/systems/rendering_py.cc#L67)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha, yup, didn't work: https://stackoverflow.com/a/8336479/7829525
</blockquote></details>

Yep, tried and failed on my end.

---

*[systems/rendering/pose_aggregator.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7UtkYEsl7OJnkktFJR:-L7V3WvHTPmG9eRRNt3Y:b4855pb) ([raw file](https://github.com/robotlocomotion/drake/blob/dfeb15f4015ab2d6c34e7371219a03046ecf815f/systems/rendering/pose_aggregator.cc#L53)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I don't believe you need to re-specify the struct, since you've specified the output value. I believe you can do:
```
return {pose_descriptor, velocity_descriptor};
```

(I don't believe this will attempt copying them as a `std::initializer_list`, because it will recognize that this is a trivial ctor.)
</blockquote></details>

Thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[bindings/pydrake/systems/rendering_py.cc, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7UtGQhDJBo3zpwTrFK:-L7V3rU6nHAKLuY1zspL:b-vf76d5) ([raw file](https://github.com/robotlocomotion/drake/blob/dfeb15f4015ab2d6c34e7371219a03046ecf815f/bindings/pydrake/systems/rendering_py.cc#L67)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Yep, tried and failed on my end.
</blockquote></details>

BTW Would you be able a quick comment saying `// N.B. Cannot use `def_readonly` with reference members.` or something like that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347)*

**Comment by jadecastro** [comment]
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[bindings/pydrake/systems/rendering_py.cc, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8347#-L7UtGQhDJBo3zpwTrFK:-L7VILzu92Wodx3qKcVV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfeb15f4015ab2d6c34e7371219a03046ecf815f/bindings/pydrake/systems/rendering_py.cc#L67)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Would you be able a quick comment saying `// N.B. Cannot use `def_readonly` with reference members.` or something like that?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8347)*

**Comment by sherm1** [comment]
Perfect! I rebased my caching branch on this and the binding tests now pass. Thanks, @jadecastro, @EricCousineau-TRI, and @jwnimmer-tri !

**Pull request merged**
