### PR TITLE
[multibody] Provide more feedback when MbP query object port is unconnected

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
relates #11448

In response to the problem where `MultibodyPlant` mysteriously, suddenly complains about an unconnected `QueryObject` port, this PR provides two tactics to lessen the pain.

1. The error message now provides a URL that can contain arbitrary guidance and checklists for understanding and addressing the error message.
2. Do our best to understand what computation is being evaluated that led to caring about the state of the input port.
    - Add a test that confirms a number of public APIs that can trigger the exception and confirm the conditions under which they are sent.
    - For those same APIs, fail fast on the unconnected port error condition, providing more message as to which API triggered it (e.g., evaluating an output port, asking for derivatives, etc.) Note: this effort is *imperfect*.
        - First, the public API on `MultibodyPlant` is not necessarily the most obvious button pushed from the user's perspective. It might have been triggered by something external (e.g., evaluating forward dynamics from some arbitrary function).
        - Second, not all APIs are equally accessible. Forward dynamics for a *discrete* `MultibodyPlant` can be immediately flagged. The same is not true for the *continuous* plant. In the latter case, the issue can only be detected when the time derivatives get evaluated.

The two tactics are largely orthogonal.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17471)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
Note to reviewers:

The two tactics listed above are split over revisions:

- R1 contains the first tactic. Please take a look at the decision on where the "trouble shooting" page is (location, structure, etc.)
- R2 provides a test that merely characterizes the *current* behavior (modulo the slight change in error message). It confirms the conditions under which exceptions are thrown. If you check out this commit and run the test, you'll see this passes. The goal here was to aid in assessing the tests correctness, independent of any new code.
- R3 introduces the new code for indicating the (more) root cause of the error and then updates the test to account for the new information.

@jwnimmer-tri @russtedrake I'd appreciate your thoughts on this before I switch out of draft mode.

(P.S. Updating examples will come in a separate PR.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17471#-:-N5gZ1776e7WBGYgxiqp:btocp87)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by SeanCurtis-TRI — COMMENTED** [review]
The rendered trouble-shooting page looks like this:



> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17471#-:-N5gZy6j8kG5rhQPsJD_:bwh7xa4)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by SeanCurtis-TRI — COMMENTED** [review]
@jwnimmer-tri and @russtedrake 

The CI failures are lint based. I'll clean up the lint after you've had the chance to get a sense for what's here without my messing up the revisions as documented above.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17471#-:-N5qAtyd1JfOKJJQfr73:b-gr20xb)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Comment by jwnimmer-tri** [comment]
Oops, this wasn't on my dashboard, and I lost track of it.  I've added it to my board now.

**Review by SeanCurtis-TRI — COMMENTED** [review]
A did a quick look and the revisions are *not* what I thought.  :( Somehow, I didn't push my curated commits so revisions 2 & 3 are messed up.

I'm inclined to close this, delint, and resubmit the properly curated commits. Sorry for the bother.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17471#-:-N5qGCiBCU6b7RP32q1f:b-y47bcc)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Comment by SeanCurtis-TRI** [comment]
Error submitting for review; bad commits.

**Pull request closed without merging**
