### PR TITLE
Disabled examples/PR2/runPassive test, see #3444

### PR DESCRIPTION
**Pull request by jhoare**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3465)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
How feasible is it to only disable in the failing subconfiguration(s)?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3465#-:-KRjVk-naS4q0uxh1X_H:b-wrkc9d)*

**Comment by jhoare** [comment]
> How feasible is it to only disable in the failing subconfiguration(s)?

I think if we know what about that configuration is causing the issue we could in theory check if those specific conditions exist and disable the test. It seems like we need to know more than we do now in order to do that though.

**Comment by jwnimmer-tri** [comment]
I agree that we can't write a perfect guard because we don't know the root cause.  But could we write a guard that, given our current build matrix, would only disable the test in the two builds where its failing?  In other words, could we enumerate all of the externals that "open source" toggles, and if any of them are enabled, then re-enable this test?  Or if any of them are disabled, then disable this test?  Or fire off some bespoke one-off configs at CI to determine which external(s) are relevant to the failure?

**Comment by jhoare** [comment]
I looked a little closer and I think there may be a chance, it will be brittle but may be enough to be good enough to get CI to pass.

**Comment by jwnimmer-tri** [comment]
:lgtm:

Please fire up one of the opt-in builds to make sure this fixes it?  (I think you'll have to use the Jenkins UI, since bot-triggered builds disable long-running tests, which I think this one is?)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3465#-:-KRjdlCZF9CfNYS-4SMn:bp4oud0)*

**Comment by jhoare** [comment]
I'm not actually sure if there is a way for us to trigger a build with long running tests enabled right now. It looks like we need to change our driver scripts. If there is a pull request associated with the build then it disables long running tests. 

I triggered these through the jenkins interface, but I believe they will have a pull request associated with them:

https://drake-jenkins.csail.mit.edu/view/MATLAB/job/linux-gcc-experimental-matlab-open-source/55/
https://drake-jenkins.csail.mit.edu/view/MATLAB/job/linux-gcc-experimental-matlab/103/

**Comment by jwnimmer-tri** [comment]
Last I checked, even though the git path uses a sha of the pull request, the ghprId (or whatever it's called) will be unset so our driver scripts will still run the log tests.

**Comment by jwnimmer-tri** [comment]
Both build passed.

**Pull request merged**
