### PR TITLE
Set the string option in GurobiSolver

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14930)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for both reviews please, thanks!

cc @amcastro-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14930#-:-MYkTsR49CR1ajwJOp1G:bkljw2i)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14930#-:-MYkW7rW4lCnrn8Ka788:b-85g6de)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/test/gurobi_solver_test.cc, line 397 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14930#-MYkVjNF56GsCY4HQVLu:-MYkVjNG8hoECtFCaNf1:b-zzw36) ([raw file](https://github.com/robotlocomotion/drake/blob/06cbdefd5377c9f2ddd3ef03c5f26757ad763d9a/solvers/test/gurobi_solver_test.cc#L397)):*
> ```cpp
>     // solutions.
>     solver_options.SetOption(solver.id(), "PoolSolutions", 3);
>     const std::string log_file = temp_directory() + "gurobi.log";
> ```

nit The result of `temp_directory()` does not end with a "/".  You need to add one here.
___
*[solvers/test/gurobi_solver_test.cc, line 402 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14930#-MYkVuXE-YIfAfhEGvL5:-MYkVuXE-YIfAfhEGvL6:bns8k1a) ([raw file](https://github.com/robotlocomotion/drake/blob/06cbdefd5377c9f2ddd3ef03c5f26757ad763d9a/solvers/test/gurobi_solver_test.cc#L402)):*
> ```cpp
>     MathematicalProgramResult result;
>     solver.Solve(prog, {}, solver_options, &result);
>     EXPECT_TRUE(filesystem::exists({log_file}));
> ```

Testing logging mixed in with a functional test is difficult to follow and debug.  Why not make it its own, distinctly-named test case?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14930)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/test/gurobi_solver_test.cc, line 402 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14930#-MYkVuXE-YIfAfhEGvL5:-MYk_e-X6Cqsagq_eHjh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/06cbdefd5377c9f2ddd3ef03c5f26757ad763d9a/solvers/test/gurobi_solver_test.cc#L402)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Testing logging mixed in with a functional test is difficult to follow and debug.  Why not make it its own, distinctly-named test case?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14930)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by amcastro-tri — COMMENTED** [review]
oh wow, I could've debugged this one myself, sorry. My suspicion was that I was doing something wrong. Thanks @hongkai-dai !

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14930#-:-MYkbHMp2vLhfNm5PNlJ:bx7tmmu)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by amcastro-tri — COMMENTED** [review]
fyi, I confirm this solves my problem. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14930#-:-MYkc4-876rjJfUNKhSq:b-eqxqrh)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
@amcastro-tri it was my fault in the first place that I forgot to set the string options. Sorry it caused problem in your workflow. Glad we can resolve it quickly.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14930#-:-MYkerL820K8Ru3rmhKR:b-hhpxwk)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Pull request merged**
