### PR TITLE
Add install logic for Gurobi and MOSEK

### LINKED ISSUE #7592: Add install logic for Gurobi and MOSEK
Not because it is going into the binary releases, but because running the CMake install is the current workflow for using MATLAB and Python bindings.

Relates #7583.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #7592. This is for the recommended workflow for third-party developers using the MATLAB and Python bindings.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7596)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Needs a change from `chrpath` to `patchelf` it seems.

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7596#-:-L0jfLHSOU8GLBczH_fr:bnfp4nl)*

**Comment by fbudin69500** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7596)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7596#-:-L0k2lEh5vgC5Ff53oVx:bnfp4nl)*

**Pull request merged**
