### PR TITLE
[models] Move realsense2 models into drake_models package

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/issues/13942.

Twin PR: https://github.com/RobotLocomotion/models/pull/43

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21191)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for both reviews per schedule, please.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21191#-:-NtsPeps9zLxPAXrmJvV:bp9q0eq)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21191)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21191#-NtscfXX5pfeXM7eQZ_W:-NtscfXX5pfeXM7eQZ_X:b-kdvzev) (no related file):*
Working

Needs a synchronous merge with Anzu.

___
___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21191#-Ntscdw2EJCfSCFVE6JX:-Ntscdw2EJCfSCFVE6JY:b-x66gi2) ([raw file](https://github.com/RobotLocomotion/drake/blob/faba06afc9de797a1f070571ed50cbea1f59485d/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "6f49d40d6b24074e1e5153a4f0238c511cec549f",
> ```

Working

Needs a real sha.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21191)* status: 1 unresolved discussion

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21191#-Ntscdw2EJCfSCFVE6JX:-NtwGO6rCHnxY7mAmbHw:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/faba06afc9de797a1f070571ed50cbea1f59485d/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs a real sha.
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21191)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21191)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21191#-NtscfXX5pfeXM7eQZ_W:-NtwMN5V-gJPPDyhb3Lk:b3yyfvc) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs a synchronous merge with Anzu.
</blockquote></details>

OK actually, actually this was a false alarm from grepping.  It _seemed_ like Anzu used this model, but in fact it doesn't even touch it.  Bash on regardless.

___

**Pull request merged**
