### PR TITLE
Add Valkyrie simulation with LCM communication

### PR DESCRIPTION
**Pull request by tkoolen**
Adds a `valkyrie_simulation` executable, which implements the following block diagram:
https://www.dropbox.com/s/ub1mn7ft0v855ju/val%20sim%20no%20state%20estimator.pdf?dl=0

This version is for simulation *without* a state estimator, i.e. directly publishing a `robot_state_t` message on the `EST_ROBOT_STATE` channel.

Here's a video of the simulator in action (at the actual speed of the simulation, in Release mode), with zero joint torques:
https://www.dropbox.com/s/4zo7wjb7mqexwdz/val_sim.mp4?dl=0

Obviously, the ground contact model needs a lot of work; see https://github.com/RobotLocomotion/drake/issues/1978 and https://github.com/RobotLocomotion/drake/issues/1594.

Contact wrenches aren't hooked up yet, pending https://github.com/RobotLocomotion/drake/pull/3821. The force/torque sensors in the diagram are currently just `ConstantVectorSource`s that output zero vectors.

It's quite a bit of code. I've structured my commits so that it would be possible to PR parts at a time, so if that is strongly preferred, let me know.

Note that the `RobotStateDecoder` isn't used for anything except testing `RobotStateEncoder` yet, but it should be useful pretty soon. Note also that `RobotStateDecoder` and `RobotStateEncoder` don't make as many assumptions as similar functionality in https://github.com/RobotLocomotion/drake/pull/3907: they work for fixed and quaternion-parameterized `RigidBodyTree`s as well.

Some questions:
* a lot of this stuff is not Valkyrie-specific. Where should it live?
* in what namespace should everything be? I initially chose `drake::systems` out of convenience.
* any ideas on testing the main in `valkyrie_simulation` (i.e. the whole shebang including LCM inputs and outputs)?

@siyuanfeng-tri for feature review.

Fixes https://github.com/RobotLocomotion/drake/issues/1595.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4004)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
some minor comments, looks very good! I can't wait to try it. 
How are collisions on the robot being specified? in the urdf? 
I had some concerns about having too many input ports, but that's not blocking if the sim speed isn't too slow. Do you have an idea what's the rt factor? 

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz9mAMQlZV4Dypparv:-KVz9mAMQlZV4Dypparw:b-hyft39) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h#L15)):*
> ```objc
> namespace systems {
> 
> // TODO(tkoolen): Currently just takes the effort part of the
> ```

Do we ever have a situation that there are more joints in robot_command_t than in the rbt? Maybe just state the assumption here. 

---

*[drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVytnxOXMJ9lMv28E2m:-KVytnxOXMJ9lMv28E2n:btbxnss) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h#L51)):*
> ```objc
>  private:
>   int robot_command_port_index_;
>   const std::map<const RigidBodyActuator*, int> desired_effort_port_indices_;
> ```

I am wondering why you are splitting each torque separately as opposed to send the entire vector (easier for actuator dynamics?). An issue I found out recently is that if you block B have 20 inputs, in B's eval output, it calls eval input recursively down for all 20 inputs regardless of whether the downstream's eval output has been called or not. So I believe this will be called # dof times from ActuatorEffortToRigidBodyPlantInputConverter.EvalInput 

I am poking david about this, but you should double check this as well. 
   

---

*[drake/examples/Valkyrie/robot_state_decoder.cc, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVzCHcMAsq-5jdveuOa:-KVzCHcMAsq-5jdveuOb:bpzyr7p) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_decoder.cc#L122)):*
> ```cpp
>   for (size_t i = 0; i < message.joint_name.size(); i++) {
>     const auto& name = message.joint_name[i];
>     const RigidBody& body = *joint_name_to_body_.at(name);
> ```

there are cases that est_robot_state has more joints than rbt, e.g. valkyrie's have finger joints and crap like that. 

---

*[drake/examples/Valkyrie/robot_state_decoder.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz-rMJJAsji40B5yQv:-KVz-rMJJAsji40B5yQw:brh0pbr) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_decoder.h#L19)):*
> ```objc
> class DRAKE_EXPORT RobotStateDecoder : public LeafSystem<double> {
>  public:
>   explicit RobotStateDecoder(const RigidBodyTree& tree);
> ```

BTW, maybe add a output port just for decoded q and v, in case people want to use raw state? 

---

*[drake/examples/Valkyrie/robot_state_encoder.cc, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz0zImcfrX3A2Pnwb_:-KVz0zImcfrX3A2Pnwba:bavd2eu) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_encoder.cc#L111)):*
> ```cpp
> 
> void RobotStateEncoder::SetStateAndEfforts(
>     robot_state_t* message, const Context<double>& context) const {
> ```

can you switch the order of the arguments? 

---

*[drake/examples/Valkyrie/robot_state_encoder.cc, line 171 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz2AfHnkHo89_fTp3O:-KVz2AfHnkHo89_fTp3P:bavd2eu) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_encoder.cc#L171)):*
> ```cpp
> 
> void RobotStateEncoder::SetForceTorque(robot_state_t* message,
>                                        const Context<double>& context) const {
> ```

can you switch the order of the arguments? 

---

*[drake/examples/Valkyrie/robot_state_encoder.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz2wNfZPTuCai2HifJ:-KVz2wNfZPTuCai2HifK:beh328j) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_encoder.h#L54)):*
> ```objc
> 
>  private:
>   std::map<const RigidBodyActuator*, int> DeclareEffortInputPorts();
> ```

BTW, Can you check if you disable all joint torque sensors all together, will it speed up the simulation? I am afraid you are calling lcm decoding robot command a gazillion times per tick.. 

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz3umXYCbEQtOfmxV5:-KVz3umXYCbEQtOfmxV6:b-8c1qhl) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L39)):*
> ```cpp
> using plants::joints::kRollPitchYaw;
> 
> // TODO(tkoolen) copied from car_simulation.cc. Where should this live?
> ```

i think this is the right place for now. 

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz8CvpVTD1etQ8lQj9:-KVz8CvqchqOxe2LreR1:bymw7ax) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L134)):*
> ```cpp
>   map<Side, System<double>*> hand_wrench_sensors;
>   map<Side, System<double>*> foot_wrench_sensors;
>   for (Side side : Side::values) {
> ```

plz add a todo here. say this is fake.

---

*[drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVzAZrOkL3GsQhGpedX:-KVzAZrOkL3GsQhGpedY:b-6s87p5) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc#L40)):*
> ```cpp
>   auto kinematics_results = make_unique<Value<KinematicsResults<double>>>(
>       KinematicsResults<double>(&tree));
>   //  auto kinematics_results = make_unique<KinematicsResults>(&tree);
> ```

remove this. 

---

*[drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVzCch0jInfxvR_-2jC:-KVzCch0jInfxvR_-2jD:bguyg3g) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc#L152)):*
> ```cpp
>   // Check left foot wrench.
>   const auto& left_foot_wrench = foot_wrenches.at(Side::LEFT);
>   EXPECT_NEAR(force_torque.l_foot_torque_x, left_foot_wrench[0], tolerance);
> ```

BTW, maybe just make 0 1 5 consts of robot state decoder or something like that? 

---

*[drake/systems/plants/rigid_body_plant/kinematics_results.h, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVzE5qgLhb6YRGEQ1NF:-KVzE5qgLhb6YRGEQ1NG:b-wpk7ey) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/systems/plants/rigid_body_plant/kinematics_results.h#L53)):*
> ```objc
>   /// Returns the twist of @p body with respect to the world, expressed in world
>   /// frame.
>   TwistVector<T> get_twist_with_respect_to_world(const RigidBody& body) const;
> ```

can you add another one for velocity / twist in world_aligned body frame?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-:-KVzFCPe32q0O4MRjCx4:b5wlsmm)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KW3MRqPnf-gQdrO6wex:-KW3MRqPnf-gQdrO6wey:bohe9ir) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L215)):*
> ```cpp
>   VectorX<double> initial_state = RPYValkyrieFixedPointState();
>   plant.set_state_vector(plant_context, initial_state);
> ```

add this to actually listen for lcm stuff. 
lcm.StartReceiveThread();

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KW3R_uJnam4LueWUfgT:-KW3R_uJnam4LueWUfgU:b-4fqcd1) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L84)):*
> ```cpp
> 
>   // Instantiate a RigidBodyPlant from the RigidBodyTree.
>   auto& plant = *builder.AddSystem<RigidBodyPlant<double>>(move(tree_ptr));
> ```

set contact spring damper. I made these up. Kp, Kd, mu. Just put a todo here. 
plant.set_contact_parameters(10000.0, 100, 10);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004)*

**Comment by tkoolen** [comment]
Thanks for the comments.

You tried it out for yourself already at this point, but for other people: check out the video in the description for a sense of the real-time rate. Collision geometry comes from the URDF, yes.

Any opinions on the questions from the PR description?

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz9mAMQlZV4Dypparv:-KW8q2LCEDLLno7KiNmH:bhy9ot6) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h#L15)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> Do we ever have a situation that there are more joints in robot_command_t than in the rbt? Maybe just state the assumption here. 
</details>
Will do.

---

*[drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVytnxOXMJ9lMv28E2m:-KW8qE7bGxIG1MvH733Y:b-7rbgdj) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h#L51)):*
> if you block B have 20 inputs, in B's eval output, it calls eval input recursively down for all 20 inputs regardless of whether the downstream's eval output has been called or not.

If that's true, that sounds like a defect in the System design to me and should not be used as an argument against this design.

I've of course considered just keeping everything as a vector, but I really feel this is a better design. My main reasons for this:
* It simplifies the implementation of future actuator dynamics / effort sensor Systems. Consider the (very much real) case of different joints having very different actuators. The proposed design allows you to create a simple System for each type of actuator and wire things up. If you instead keep the efforts as a vector, then that mean that the actuator models need to be implemented as a separate class hierarchy of not-quite-systems (that may very well be stateful!), and would place the burden of muxing/demuxing and handling the state of these heterogeneous actuators on the System that contains the separate actuator models. In the proposed design, the muxing/demuxing is already done for you, and state is handled automatically by virtue of the individual actuator models themselves being Systems.
* I think using an implicit indexing convention to get data from a big aggregate vector is generally a bad design. This design makes it impossible to confuse conventions while still being very efficient (once the issue you were talking about is resolved).

---

*[drake/examples/Valkyrie/robot_state_decoder.cc, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVzCHcMAsq-5jdveuOa:-KW8u5AQadgRZ9yat6VW:bqbko97) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_decoder.cc#L122)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> there are cases that est_robot_state has more joints than rbt, e.g. valkyrie's have finger joints and crap like that. 
</details>
Alright, I'll robustify this a bit.

---

*[drake/examples/Valkyrie/robot_state_decoder.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz-rMJJAsji40B5yQv:-KW8uFqyCwgpe7C85edY:b8gok15) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_decoder.h#L19)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> BTW, maybe add a output port just for decoded q and v, in case people want to use raw state? 
</details>
I'm not a fan of big raw `BasicVectors` + an indexing convention. Do you have a case in mind where having those outputs is better than having an object like `KinematicsCache`/`KinematicsResults`?

---

*[drake/examples/Valkyrie/robot_state_encoder.cc, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz0zImcfrX3A2Pnwb_:-KW8ubNlqygfCdQJw5fu:b-ou14dy) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_encoder.cc#L111)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> can you switch the order of the arguments? 
</details>
OK, will do.

---

*[drake/examples/Valkyrie/robot_state_encoder.cc, line 171 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz2AfHnkHo89_fTp3O:-KW8vElFTZpdcpDUmeZW:b-ou14dy) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_encoder.cc#L171)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> can you switch the order of the arguments? 
</details>
OK, will do.

---

*[drake/examples/Valkyrie/robot_state_encoder.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz2wNfZPTuCai2HifJ:-KW8vI4M_KJAHwvkk49u:bdf61v3) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_encoder.h#L54)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> BTW, Can you check if you disable all joint torque sensors all together, will it speed up the simulation? I am afraid you are calling lcm decoding robot command a gazillion times per tick.. 
</details>
Will check.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz3umXYCbEQtOfmxV5:-KW8vLvpRraMO1PBfbdt:b-11hobi) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L39)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> i think this is the right place for now. 
</details>
Alright.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KW3R_uJnam4LueWUfgT:-KW8vxjnOrGZJySP8t9B:bhy9ot6) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L84)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> set contact spring damper. I made these up. Kp, Kd, mu. Just put a todo here. 
> plant.set_contact_parameters(10000.0, 100, 10);
</details>
Will do.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz8CvpVTD1etQ8lQj9:-KW8v_kSpt2VcWsQW6zP:b-yps6ek) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L134)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> plz add a todo here. say this is fake.
</details>
See three lines earlier?

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KW3MRqPnf-gQdrO6wex:-KW8w-q2nNPFK0q1m1Gm:b-5hynej) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L215)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> add this to actually listen for lcm stuff. 
> lcm.StartReceiveThread();
> 
</details>
Ah, thanks.

---

*[drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVzAZrOkL3GsQhGpedX:-KW8w2Umd6bg7DjsqrA8:bhy9ot6) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc#L40)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> remove this. 
</details>
Will do.

---

*[drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVzCch0jInfxvR_-2jC:-KW8w64oowTVoWKhb8Kq:b-8erj7h) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc#L152)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> BTW, maybe just make 0 1 5 consts of robot state decoder or something like that? 
</details>
You're right. Will do.

---

*[drake/systems/plants/rigid_body_plant/kinematics_results.h, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVzE5qgLhb6YRGEQ1NF:-KW8wDFWO_MShF0kPzoY:b-80tlqk) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/systems/plants/rigid_body_plant/kinematics_results.h#L53)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> can you add another one for velocity / twist in world_aligned body frame?
</details>
Sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-:-KW8pY0F8RBNTRaqdV-v:bo1e1v2)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 15 of 17 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVytnxOXMJ9lMv28E2m:-KWHUUIHGZ80ZQLSkm0f:boijhp4) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h#L51)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> > if you block B have 20 inputs, in B's eval output, it calls eval input recursively down for all 20 inputs regardless of whether the downstream's eval output has been called or not.
> 
> If that's true, that sounds like a defect in the System design to me and should not be used as an argument against this design.
> 
> I've of course considered just keeping everything as a vector, but I really feel this is a better design. My main reasons for this:
> * It simplifies the implementation of future actuator dynamics / effort sensor Systems. Consider the (very much real) case of different joints having very different actuators. The proposed design allows you to create a simple System for each type of actuator and wire things up. If you instead keep the efforts as a vector, then that mean that the actuator models need to be implemented as a separate class hierarchy of not-quite-systems (that may very well be stateful!), and would place the burden of muxing/demuxing and handling the state of these heterogeneous actuators on the System that contains the separate actuator models. In the proposed design, the muxing/demuxing is already done for you, and state is handled automatically by virtue of the individual actuator models themselves being Systems.
> * I think using an implicit indexing convention to get data from a big aggregate vector is generally a bad design. This design makes it impossible to confuse conventions while still being very efficient (once the issue you were talking about is resolved).
</details>
I buy your arguments. It's better to have the joint level stuff separate since they are physically different. The multi input system thing is on David's radar, should be fixed relatively soon. 

---

*[drake/examples/Valkyrie/robot_state_decoder.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz-rMJJAsji40B5yQv:-KWHV1nofAt6rUapjbQm:bgob4ez) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_state_decoder.h#L19)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> I'm not a fan of big raw `BasicVectors` + an indexing convention. Do you have a case in mind where having those outputs is better than having an object like `KinematicsCache`/`KinematicsResults`?
</details>
Giving me a raw vector is a bit easier for me to hook up to my stuff, but on the other hand, I feel my thing will just merge with kinematics result at some point. Worst case I can always get q v from kinematics cache or result for now. 

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVz8CvpVTD1etQ8lQj9:-KWHWJGB2qi9jYSarfIN:b-mfo3fp) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L134)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> See three lines earlier?
</details>
opps. 

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KW3MRqPnf-gQdrO6wex:-KWHWSGR3Kg9h0FckFz_:b-2kd3od) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/valkyrie_simulation.cc#L215)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> Done.
</details>
I think you still need the  simulator->Initialize(); here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-:-KWHXciPwLEDafq1hpBt:bg7igkv)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KVytnxOXMJ9lMv28E2m:-KWIue_uPL858vas2E1s:btnyrf5) ([raw file](https://github.com/robotlocomotion/drake/blob/324c5ffbaeaf52fc2e7fa1ad4d28c37bab461094/drake/examples/Valkyrie/robot_command_to_desired_effort_converter.h#L51)):*
It is true that EvalOutput currently scales as N^2 in the number of I/O connections, and it's absolutely a defect.  Fixing it is my top priority right now.  (It also turns out to be harder than I expected, due to design shrapnel from #3455, so it might take a couple weeks to land.)

@tkoolen, I think your first argument for this design is compelling - case closed.  However, just to clarify, your second argument may have overlooked a useful feature of System2:

> I think using an implicit indexing convention to get data from a big aggregate vector is generally a bad design.

It's an encouraged practice to subclass `BasicVector` with semantically meaningful accessors.  So, the indexing convention over vector cells can be hidden entirely, just as it's hidden here over ports.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004)*

**Comment by amcastro-tri** [comment]
+@david-german-tri for platform review please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-:-KWndaVctkTx_qOSizCT:b-buchxz)*

**Comment by david-german-tri** [comment]
I've opened https://github.com/RobotLocomotion/drake/pull/4158 to document that `examples/Valkyrie` doesn't require platform review, as previously discussed on Slack.  I'll update the Reviewable enforcement script also.  Could you split the changes to Drake proper into a separate PR?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-:-KWod_I8mPnzhy1Zl6c_:bc75366)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KWpGBj8WwCVH1bZ6LDr:-KWpGBj8WwCVH1bZ6LDs:b478mi7) (no related file):*
BTW, I'm trying to get a feel for how much code will need to change if we attempt to simulate _two_ Valkyrie robots working in collaboration. Thoughts?

---

*[drake/examples/Valkyrie/robot_state_decoder.cc, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-KWp7omRSpvArE0vziYH:-KWp7omS8Rc4Xv-LS57q:b-frai69) ([raw file](https://github.com/robotlocomotion/drake/blob/3092e32ed83cb4adf9968c1bde012b5f60708539/drake/examples/Valkyrie/robot_state_decoder.cc#L13)):*
> ```cpp
> using std::make_unique;
> using std::move;
> using std::unique_ptr;
> ```

BTW: nit: alpha sort this section.

(Same comment to all subsequent `using` sections.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004)*

**Comment by david-german-tri** [comment]
-@david-german-tri since this PR has been superseded

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4004#-:-KWsQ4SZPMcdMo9zsF-3:bl9z3w7)*

**Comment by jwnimmer-tri** [comment]
Has #4152 superseded this PR, such that this should be closed?

**Pull request closed without merging**
