### PR TITLE
workspace: Update dreal,fmt,spdlog to latest release

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10576)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@soonho-tri and @jamiesnape we need to coordinate a rebuild of the dReal binary releases, to match the new fmt and spdlog revisions proposed here.  Can one or both of you work on that, please?

If you want to push patches here that's fine, or open a new PR, or just tell me the new details and I can push the edits here.

**Comment by soonho-tri** [comment]
FYI, I think the following error is not dreal-related one:
```
ERROR: /media/ephemeral0/ubuntu/workspace/linux-bionic-clang-bazel-experimental-leak-sanitizer/src/solvers/BUILD.bazel:634:1: Couldn't build file solvers/_objs/unrevised_lemke_solver/unrevised_lemke_solver.pic.o: C++ compilation of rule '//solvers:unrevised_lemke_solver' failed (Exit 1) clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g '-std=c++0x' -MD -MF ... (remaining 129 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
solvers/unrevised_lemke_solver.cc:857:8: error: unused variable 'to_string' [-Werror,-Wunused-variable]
  auto to_string = [](const std::vector<LCPVariable>& vars) -> std::string {
       ^
solvers/unrevised_lemke_solver.cc:977:29: note: in instantiation of member function 'drake::solvers::UnrevisedLemkeSolver<double>::SolveLcpLemke' requested here
    class ::drake::solvers::UnrevisedLemkeSolver)
                            ^
solvers/unrevised_lemke_solver.cc:857:8: error: unused variable 'to_string' [-Werror,-Wunused-variable]
  auto to_string = [](const std::vector<LCPVariable>& vars) -> std::string {
       ^
solvers/unrevised_lemke_solver.cc:977:29: note: in instantiation of member function 'drake::solvers::UnrevisedLemkeSolver<Eigen::AutoDiffScalar<Eigen::VectorXd> >::SolveLcpLemke' requested here
    class ::drake::solvers::UnrevisedLemkeSolver)
```

**Comment by soonho-tri** [comment]
@jamiesnape , could you download them and upload to the Drake mirror?

 - https://dl.bintray.com/dreal/ibex/libibex-dev_2.7.4.20181130120337.git65fc3b6c28ea49cb2da7e9b693add6ba7c5fc4ae~16.04_amd64.deb
 - https://dl.bintray.com/dreal/dreal/dreal_4.19.02.1_amd64.deb

@jwnimmer-tri , in the meantime, please cherry-pick e3d9fdd86a943342aa85d533bbd2b02de1ed965c to fix/test this PR locally.

**Comment by jamiesnape** [comment]
apt repos have been updated

**Comment by jamiesnape** [comment]
Wow.

```wget https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental-debug/1557/consoleText``` is your only hope. Jenkins is really not happy.

**Comment by jamiesnape** [comment]
It goes without saying that too many rebuilds with 4 GB logs will break Jenkins (this cluster of builds took 1.4% of free disk space), so please be 100% sure the log is manageable before rebuilding.

**Comment by jwnimmer-tri** [comment]
(The real problem may be that I've misunderstood how spdlog level defaults work, and that tracing is always enabled now.)

**Comment by jamiesnape** [comment]
> Using permanently-commited console trace statements, instead of a debugger or standalone binary log, is an anti-pattern anyway IMO (though others disagree).

I don't disagree.

I need to see investigate whether there is anything obvious we can set on Jenkins to catch this (there are several plugins, but bad plugins can be worse than no plugin).

**Comment by jamiesnape** [comment]
FWIW the build failures were the Bazel JVM running out of memory (at this location: https://github.com/bazelbuild/bazel/blob/984ffa050b6de40b1e46402eaa1a1def44e7e09b/src/main/java/com/google/devtools/build/lib/buildtool/BuildTool.java#L186).

CDash also (fortunately) rejected the build log, though that does cause a change to the build status.

**Comment by jwnimmer-tri** [comment]
(I'll be sure we test on macOS CI, before we merge.)

**Comment by jamiesnape** [comment]
> @jamiesnape , can you update the macOS CI images if needed?

Is this going to break `master` if I switch the images over early?

**Comment by soonho-tri** [comment]
> Is this going to break `master` if I switch the images over early?

Yes.

**Comment by jwnimmer-tri** [comment]
FYI From my point of view, Jamie or Soonho can push the merge button here anytime you want (only blocker is the reviewable thread, which you can dismiss).  Right now, with the homebrew PR merged, unprovisioned macOS nightlies (and thus fresh macOS installs) would fail.  This PR is a flag day change with respect to baking the new homebew dReal into our macOS CI images.  Only the old-flavor of both or new-flavor of both are compatible; mixing and matching will fail.

**Comment by jamiesnape** [comment]
Images have been updated.

**Pull request merged**
