### PR TITLE
Ignoring a Division by Zero in implicit_euler_integrator-inl.h

### PR DESCRIPTION
**Pull request by m-chaturvedi**
We have a division by zero when running `implicit_euler_integrator_test` when theta becomes 1.  It seems to me that it can be ignored because it's not numerically unexpected.

The UBSan defect: https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=140928
Stack: https://gist.github.com/m-chaturvedi/6b62d2403a8e14e3c60bec09548bb0ea

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6561)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-nightly-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-:-Kosm5tFOMmezia7uyRJ:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+ @edrumwri for additional feature review, please.

**Comment by m-chaturvedi** [comment]
+@edrumwri for additional feature review, please.

**Comment by edrumwri** [comment]
Agreed, existing code should prevent divide-by-zero from ever occurring.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 409 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-Kosv6_jFolFMmgAOCoC:-Kosv6_ktjNpAlBxjpgF:bpafdh7) ([raw file](https://github.com/robotlocomotion/drake/blob/f8f9acc6e553e52243bf063c2c5b0d4b80fd7379/drake/systems/analysis/implicit_euler_integrator-inl.h#L409)):*
> ```objc
> // theta could become 1, in line const T eta = theta / (1 - theta);
> // causing a divide by zero error when UBSan is used.
> __attribute__((no_sanitize("float-divide-by-zero")))
> ```

Since I am not familiar with the UBSan syntax (and I suspect others are not either), could you just put a comment that says what this syntax is accomplishing? Presumably not looking for div0 errors in the remainder of this function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-:-KosvVuHZnLVSxRH9b32:b-bbucz6)*

**Comment by jwnimmer-tri** [comment]
> Agreed, existing code should prevent divide-by-zero from ever occurring.

This is confusing, because UBSan is a runtime checker, so something was definitely dividing by zero.  Evan, take a look at the hyperlinks in the description and see if you can learn more?

**Comment by edrumwri** [comment]
Yes. And FWIW, the introduction of UBSan is yet another way that I see our development process strengthened. Nice job to whomever's fine idea this was!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-:-Kot3FrbqZQ8pCkYGWHQ:bc7ucau)*

**Comment by edrumwri** [comment]
(Per Jeremy's query):

A division by zero occurs but, as Mmanu noted, the division by zero is anticipated: the numerator and the denominator are always different, so the division by zero yields infinity, not NaN. And the ensuing test correctly identifies that the process failed to converge (true, since `norm(dx)` did not decrease at all).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-:-KotATFqjFtqKWzn_5ZX:beawh8y)*

**Comment by jwnimmer-tri** [comment]
Perhaps the way the suppression is phrased could be improved though, such as ...
```c++
__attribute__((no_sanitize("float-divide-by-zero")))
template <typename T>
T divide_allowing_by_zero(const T& n, const T& d) { return n / d; }
...
const T eta = divide_allowing_by_zero(theta, 1 - theta);
```
... in order to focus the detail to the site of interest, and catch any _other_ future divide-by-zero errors in that same method.

(The helper could also `DRAKE_ASSERT(d != T{0.0} || n != T{0.0});` though that doesn't seem worth it.)

**Comment by edrumwri** [comment]
I think that's a great idea.

I'm surprised you said `DRAKE_ASSERT(d != T{0.0} || n != T{0.0});` and not `DRAKE_ASSERT(!(d == T(0) && n == T(0)))` instead!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-:-KotTyyh0KVnuJk7vqFv:bsknyww)*

**Comment by jwnimmer-tri** [comment]
Yup.  I like the clarity of the second "not (both are zero)" phrasing, but "at least one is non-zero" phrasing catches NaNs.  Meh.

**Comment by edrumwri** [comment]
Nice point.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-:-Kotkv2qF1RloPXbDgf2:b-qirus)*

**Comment by edrumwri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-:-Kp1qoLkR8NgfNNMov28:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
+@jwnimmer-tri for platform review, please.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 393 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-Kp1wzfsA6EjXq936aQ1:-Kp1wzftwJvYCEo0mXGF:bhc8l27) ([raw file](https://github.com/robotlocomotion/drake/blob/6791c09f09b4b405a1d4a15688c6ba98d1de6542/drake/systems/analysis/implicit_euler_integrator-inl.h#L393)):*
> ```objc
>   DRAKE_ASSERT(!(d == T{0.0} && n == T{0.0}));
>   return n / d;
> }
> ```

FYI I would have put this into a `detail` namespace, but I don't think its defective to leave it here.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 504 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-Kp1weadz3upK2U2Mc4N:-Kp1weadz3upK2U2Mc4O:b-2a7ppd) ([raw file](https://github.com/robotlocomotion/drake/blob/6791c09f09b4b405a1d4a15688c6ba98d1de6542/drake/systems/analysis/implicit_euler_integrator-inl.h#L504)):*
> ```objc
>       const T theta = dx_norm / last_dx_norm;
>       // theta could become 1.
>       const T eta = divide_allowing_by_zero<T>(theta, 1-theta);
> ```

cppguide requires spaces around the subtraction operator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-:-Kp1x9stfnmQ5tbSkX01:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 504 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-Kp1weadz3upK2U2Mc4N:-Kp1yhmNzyvngRusploS:bej5rk2) ([raw file](https://github.com/robotlocomotion/drake/blob/6791c09f09b4b405a1d4a15688c6ba98d1de6542/drake/systems/analysis/implicit_euler_integrator-inl.h#L504)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

cppguide requires spaces around the subtraction operator.
</blockquote></details>

Sure.  Sorry for the oversight.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561)*

**Comment by m-chaturvedi** [comment]
*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 393 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6561#-Kp1wzfsA6EjXq936aQ1:-KpG7CvvUuM9a6aPwVub:b-11hobi) ([raw file](https://github.com/robotlocomotion/drake/blob/6791c09f09b4b405a1d4a15688c6ba98d1de6542/drake/systems/analysis/implicit_euler_integrator-inl.h#L393)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I would have put this into a `detail` namespace, but I don't think its defective to leave it here.
</blockquote></details>

Alright.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6561)*

**Comment by jwnimmer-tri** [comment]
@m-chaturvedi As it turns out, on GCC builds this presents a warning: `./drake/systems/analysis/implicit_euler_integrator-inl.h:390:49: warning: 'no_sanitize' attribute directive ignored [-Wattributes]`.  This is _not_ a build break so is not critical, but it would be nice to clean up the code so that developers do not see such a warning.  Could you please file a follow-up PR to remove the warning under GCC?

**Comment by m-chaturvedi** [comment]
I see, sure.

**Pull request merged**
