### PR TITLE
Renamed car_sim_lcm and multi_car_sim_lcm by Appending a 1

### PR DESCRIPTION
**Pull request by liangfok**
This is to make way for System 2.0 variants.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3722)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@ggould-tri for platform review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3722#-:-KTVp6LY2C4dcitgvna9:b-nvjamr)*

**Comment by ggould-tri** [comment]
Is the plan for these to eventually go away or are we retaining them?  If we are retaining them then the name is somewhat glyphic and should be explained in a readme somewhere.  If this is just a temporary home before they are deleted then :lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3722#-:-KTVpSIpt9qS0IhKzcim:b-e3slf4)*

**Comment by liangfok** [comment]
The plan is to delete them once System 1.0 is removed.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3722#-:-KTVpxgyrc731HNWg0Oc:b-7xd9cs)*

**Comment by jwnimmer-tri** [comment]
Reviewable doesn't work well on the train, but here's my question, based on the description:

Please confirm that we need to keep these `main` files around in-tree concurrently with their System 2.0 counterpart files at the same time?  My naive expectation is that we could delete the System 1.0 files concurrently in the PR that introduces the System 2.0 demo `main`.  Is that is difficult, then a temporary rename is good, but I don't immediately see the need.

**Comment by liangfok** [comment]
It's difficult because I was planning on naming the files for the System 2.0 variants `car_sim_lcm.cc` and `multi_car_sim_lcm.cc`. Thus, if I keep the "old" System 1.0 files, there will be a name clash.

**Comment by jwnimmer-tri** [comment]
(1) But on any given branch (dev branch for Sys2 porting, or master once merged), do we even have both `main` program files at once?  I don't understand in what case we need both committed at the same time.

(2) Having bespoke of demo programs is an anti-pattern (`main` is difficult to test).  I would like to see automotive_demo command-line be the place where the demo modality is chosen.  It's okay if that's a follow-on PR to the porting (so as not do to too much porting at once), but it seems like having `car_sim_lcm2` for a couple days between the System2 PR and the roll-up-demos PR would be okay also.

**Comment by liangfok** [comment]
I see. OK. I'll select a different name for the sys2 demos and leave the sys1 demos in place.

**Pull request closed without merging**
