### PR TITLE
Update swigmake submodule SHA

### PR DESCRIPTION
**Pull request by jamiesnape**
Adds a small fix for MEX output for multi-configuration generators.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3654)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3654#-:-KTFcQuYpdvJMOhG2HYR:bnfp4nl)*

**Pull request merged**
