### PR TITLE
Move KinematicsCache methods out to RigidBodyTree

### PR DESCRIPTION
**Pull request by amcastro-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4298)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Heads-up that this possibly relates to https://github.com/RobotLocomotion/drake/pull/4214 (which introduces some more velocity/qdot transformations).  @edrumwri

**Comment by edrumwri** [comment]
Alejandro, can you provide more detail as to why this PR is necessary?

---

Reviewed 1 of 7 files at r1, 3 of 5 files at r2.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 352 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KXq726VrDSj9llDjoNo:-KXq726VrDSj9llDjoNp:b74vund) ([raw file](https://github.com/robotlocomotion/drake/blob/a697ba3129f2b6cf7505973e53d19bb012dd210f/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L352)):*
> ```cpp
>   generalized_velocity->SetFromVector(
>       tree_->transformQDotMappingToVelocityMapping(
>           kinsol, configuration_dot.transpose().eval()).transpose());
> ```

This goes back to my issue- how do you know this is correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KXq7I0GSEBePoMR4JE_:b-z0u1ws)*

**Comment by amcastro-tri** [comment]
Per f2f discussion with @sherm1 today we determined that it does make sense to take any functionality out from `KinematicsCache`.  In that way we break the dependency of `KinematicsCahce` from multibody code. Think of `systems::Cache<T>` which does not depend on any other components but it is its own self-contained module. 
This goes along the direction of writing accessors as discussed in #4328 which would end up in a cyclic dependency if `KinematicsCache` knows about `RigidBody`'s. Even if we pass any other Proxy class as an arguement, that class will contain somehow a `KinematicsCache` object and we will end up with a cyclic dependency.
This also caused me trouble in the migration to `RBT<T>` (#3987 ).

---

Review status: 2 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 352 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KXq726VrDSj9llDjoNo:-KXw8EDvNaSWy8zT8CBO:b-7vtr4b) ([raw file](https://github.com/robotlocomotion/drake/blob/a697ba3129f2b6cf7505973e53d19bb012dd210f/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L352)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This goes back to my issue- how do you know this is correct?
</blockquote></details>

I am just refactoring code that already made it into master. The point of this PR is to make `KinematicsCache<T>` as small as possible with no dependencies on `rigid_body.h` or any other `multibody` component for that matter. Therefore that issue does not belong here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KXw8WyOShTnMjOLUAdL:b-h6msdm)*

**Comment by amcastro-tri** [comment]
+@sherm1 for feature review please.

---

Review status: 2 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KXwCfyap7dYohXOMXPd:b-ec6d43)*

**Comment by jwnimmer-tri** [comment]
In case this relates to the prior PR's discussion with me involved as well... to be clear, I am happy to have the methods leave the KC.  Clearly they don't need its private member state!  My objection is putting them into RBT, since they don't need its private member state either!  But it sounds like there's already interesting it breaking them our of RBT later anyway, and this is just a temporary throwaway transition to help get us from today to where we want to next year.  So, bash on regardless, I guess!

**Comment by sherm1** [comment]
:+1: This change is definitely a step in the direction we want to go! This will make it easier to switch to the Sys 2 caching scheme. A few non-blocking comments and questions below, PTAL. Also, why does this disable the inverse dynamics test? Otherwise pending successful CI, :lgtm:. 

---

Reviewed 4 of 7 files at r1, 2 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/multibody/rigid_body_tree.cc, line 1243 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KXxn7Csm7gP3V3lfUHx:-KXxn7Csm7gP3V3lfUHy:b-bxlf8l) ([raw file](https://github.com/robotlocomotion/drake/blob/14abc157a5caeaf2cb9f838af4d4a037c6d13bad/drake/multibody/rigid_body_tree.cc#L1243)):*
> ```cpp
> template <typename T>
> template <typename Scalar>
> MatrixX<Scalar> RigidBodyTree<T>::VelocityToPositionDotMapping(
> ```

BTW, as long as you're changing this name how about `GetVelocityToQDotMapping()` instead for consistency and clarity? (and below)

---

*[drake/multibody/rigid_body_tree.cc, line 2717 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KXxpxK5cMWP9t449hRm:-KXxpxK5cMWP9t449hRn:bejtinj) ([raw file](https://github.com/robotlocomotion/drake/blob/14abc157a5caeaf2cb9f838af4d4a037c6d13bad/drake/multibody/rigid_body_tree.cc#L2717)):*
> ```cpp
> 
> // Explicit template instantiations for VelocityToPositionDotMapping.
> template MatrixX<AutoDiffUpTo73d>
> ```

BTW, are these instantiations new? I don't see them anywhere in old code. If so why did you add them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KXxp7w-gJ3RD7lEaile:b-fmx6v3)*

**Comment by amcastro-tri** [comment]
+@ggould-tri for platform please.

---

Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 1243 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KXxn7Csm7gP3V3lfUHx:-KY-0GnJbXPLZ_rOyd9_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14abc157a5caeaf2cb9f838af4d4a037c6d13bad/drake/multibody/rigid_body_tree.cc#L1243)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, as long as you're changing this name how about `GetVelocityToQDotMapping()` instead for consistency and clarity? (and below)
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_tree.cc, line 2717 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KXxpxK5cMWP9t449hRm:-KY-0N5VMbyFo-bW72eL:bvof6om) ([raw file](https://github.com/robotlocomotion/drake/blob/14abc157a5caeaf2cb9f838af4d4a037c6d13bad/drake/multibody/rigid_body_tree.cc#L2717)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, are these instantiations new? I don't see them anywhere in old code. If so why did you add them?
</blockquote></details>

BTW, yes, these instantiations are new. Methods `VelocityToPositionDotMapping` and `PositionDotToVelocityMapping` where locally defined and used in `drake/matlab/systems/plants/rigidBodyTreeMexFuncionts.cpp` to provide that functionality to the Matlab side. If you take a look at that file you will see that all the other methods follow a different design pattern which is: There is an `RBT:MyMethod()` method that gets instantiated on its tree variants within a corresponding `MyMethodmex()`.
The in this PR fixes the `VelocityToPositionDotMapping` (and the inverse) to follow that pattern.
Since now those methods are moved to `RBT<T>`, they need to be explicitly instnatiated on all variants used throughout the code as any other template method in `RBT` is.
This will change to simple `Ref<VectorX<T>>` method arguments once I'm done with RBT!

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 352 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KXq726VrDSj9llDjoNo:-KY-2KuDuuDPXKjzn6wn:b-f2x6mb) ([raw file](https://github.com/robotlocomotion/drake/blob/a697ba3129f2b6cf7505973e53d19bb012dd210f/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L352)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I am just refactoring code that already made it into master. The point of this PR is to make `KinematicsCache<T>` as small as possible with no dependencies on `rigid_body.h` or any other `multibody` component for that matter. Therefore that issue does not belong here.
</blockquote></details>

@edrumwri, see discussion on the thread at the top. Could you please mark yourself satisfied here? (unless you are not?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KY-2WcWIz3-h8_VMiPG:b-z1mnxk)*

**Comment by ggould-tri** [comment]
I am sad to see a change of this magnitude that doesn't require any test changes -- presumably the items moved out of KC were and remain untested?

However I don't think a refactor is the place to solve that.  So :lgtm: as it stands, and maybe in the future we can do better.

---

Reviewed 3 of 7 files at r1, 2 of 5 files at r2, 1 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KY-Al2ifZvhASLnkXQc:b-5uxf23)*

**Comment by ggould-tri** [comment]
Sad to see all of those `const`s go :(

But still looks fine to me.

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KY0D2m8janFBtreDGAc:blm70se)*

**Comment by amcastro-tri** [comment]
I was just about to comment about that @ggould-tri. 
Notice that the `const`'s needed to go because I made those methods `static`!
The reason I had to do so is because Matlab provides a "static-like" interface from where methods are called without a reference to the "this" pointer to the model.
Therefore, to keep the Matlab API unchanged I made those methods static and I added the temporary fix "KinematicsCache::get_bodies()". I will get rid of "KinematicsCache::get_bodies()" once we can reference cache entries by unique body id's rather than `RigidBody` pointers.
Of course I could've just changed the Matlab API... 
PTAL.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KY0FSrcBjVHLQQSgEhY:b-qxuown)*

**Comment by amcastro-tri** [comment]
By the way, many thanks to @jwnimmer-tri to helping me figure out why the Matlab calls were not working!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KY0G9KjO-RVoin7aIBE:b-pceksd)*

**Comment by sherm1** [comment]
One new comment -- PTAL.

---

Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 1243 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KXxn7Csm7gP3V3lfUHx:-KY0KK5nEYPObgKY4ZWZ:b-rkp54b) ([raw file](https://github.com/robotlocomotion/drake/blob/14abc157a5caeaf2cb9f838af4d4a037c6d13bad/drake/multibody/rigid_body_tree.cc#L1243)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant "QDot" rather than "PositionDot" for consistency with `transformVelocityMappingToQDotMapping()` and System 2's `MapVelocityToQDot()` etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KY0KxlvhFEymAwsUNiD:b-64nfmp)*

**Comment by amcastro-tri** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 1243 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KXxn7Csm7gP3V3lfUHx:-KY0M_f7ADtaAysl6-iy:b-1gxqyj) ([raw file](https://github.com/robotlocomotion/drake/blob/14abc157a5caeaf2cb9f838af4d4a037c6d13bad/drake/multibody/rigid_body_tree.cc#L1243)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I meant "QDot" rather than "PositionDot" for consistency with `transformVelocityMappingToQDotMapping()` and System 2's `MapVelocityToQDot()` etc.
</blockquote></details>

Of course! sorry. Done now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 2 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r5, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/multibody/kinematics_cache.h, line 110 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KY0ksRULSvEf8SW3u1U:-KY0ksRVNLczMDOaMzwW:b-5oejiz) ([raw file](https://github.com/robotlocomotion/drake/blob/e54b16945b53eb5906e0b1050126fcf4d15dea6f/drake/multibody/kinematics_cache.h#L110)):*
> ```objc
>   // RigidBodyTree::transformQDotMappingToVelocityMapping() to be static
>   // methods. That is a requirement from velocityToPositionDotMappingmex()
>   // and positionDotToVelocityMappingmex() in rigidBodyTreeMexFunctions which
> ```

BTW, are these names still correct (did they change to QDot?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KY0oypD0aYpmL29YR4N:bnfp4nl)*

**Comment by sherm1** [comment]
One question, @amcastro-tri then ready to merge.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-:-KY0pBuTAV3uoG_3F2vw:b-c2gvjm)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/multibody/kinematics_cache.h, line 110 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/4298#-KY0ksRULSvEf8SW3u1U:-KY0uQnaTxTdNpS7Joks:bxk86oo) ([raw file](https://github.com/robotlocomotion/drake/blob/e54b16945b53eb5906e0b1050126fcf4d15dea6f/drake/multibody/kinematics_cache.h#L110)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, are these names still correct (did they change to QDot?).
</blockquote></details>

BTW. Yes, they still are correct. Those names define the Matlab API and that is why I didn't change them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4298)*

**Pull request merged**
