### PR TITLE
Analytical solution for spherically-symmetric sphere on horizontal plane

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9505)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@mitiguy This seems to be lagging without @hongkai-dai looking at it.  Would you like to add a "Priority" label?

**Comment by hongkai-dai** [comment]
I will look into this PR.

**Comment by jwnimmer-tri** [comment]
@mitiguy What's the priority on this PR?  It seems to be languishing.

**Comment by jwnimmer-tri** [comment]
Happy New Year, and thanks for your interest in contributing to Drake!  Since this PR has not received any updates over the past 6+ months, we are closing it automatically.  To resume the PR again, you may reopen it with updates, or open a new one.

**Pull request closed without merging**
