### PR TITLE
ubuntu: Upgrade to Bazel 0.18

### LINKED ISSUE #9863: ubuntu: Upgrade to Bazel >=0.18 - `~/.bazelrc` now ignored by Drake on Bazel 0.16.1
I believe this has been discussed on Slack already; long and short of it is, we have a newer version of Bazel on Mac (0.19 is what Homebrew will install), and due to that upgrade, had to put in a compatibility shim (#9849) that has now disconnected Bazel from reading `~/.bazelrc` (which to me is important, as it contains repository cache, remote cache, and possibly some usability options).

The fix should be to upgrade Xenial to Bazel >=0.18.

### LINKED ISSUE #9868: bazel: Use `try-import %workspace%/user.bazelrc`
Follow-up from #9864; super useful to not have to mutate `$HOME` dotfiles.
Can use once we have Bazel 0.18.

\cc @jamiesnape @sammy-tri

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #9863 
Resolves #9868

~Will be trying out Bazel 0.19 as well, to see if we can jump to this version; failing that, would like to have this resolves soon.~
Deferring 0.19.0 to a later point for simplicity.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9864)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
Do you want to add `try-import %workspace%/user.bazelrc` to the shim per https://github.com/bazelbuild/bazel/issues/6319 ? That was one of the main reasons for upgrading to 0.18.

**Comment by jwnimmer-tri** [comment]
That addition would fail the pre-merge CI.  I'm content to just get the binaries and AMIs upgraded first, and then clean up the try-import (and our `bazel.rst` documentation, and setup_user_environment, and etc.) in a future PR.

**Comment by EricCousineau-TRI** [comment]
Agreeing with Jeremy: Is it necessary for upgrading? If not, I'd like to defer, and add the sugar in after the fact.

**Comment by jamiesnape** [comment]
I don't see that pre-merge failing CI is relevant in the slightest.

**Comment by jamiesnape** [comment]
You are missing updates to minimum versions in the appropriate places in the Bazel and CMake code anyway, so it would be incorrect for this to pass CI.

**Comment by EricCousineau-TRI** [comment]
Gotcha; just to make sure, is that just in `CMakeLists.txt`?

**Comment by jamiesnape** [comment]
No, in WORKSPACE too.

**Comment by jwnimmer-tri** [comment]
Since Bazel 0.16.1 still correctly compiles the project, I think its okay to defer bumping the minimum, also.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
You will have the provisioned images ready by the time this passes or fails unprovisioned CI, so you are not buying yourself much.

**Comment by EricCousineau-TRI** [comment]
Per slack discussion with Jamie, #9868 should be required for the `drake-ci` CMake driver. Incorporated it here.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Your .gitignore has a typo.

**Comment by EricCousineau-TRI** [comment]
Yeah, saw that. I'll block myself on this PR, but wait for unprovisioned to pass first.

**Comment by jamiesnape** [comment]
All unprovisioned builds are good. Do we want to set a moratorium on merges before I switch the images?

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please.

**Comment by jwnimmer-tri** [comment]
The linux-xenial-gcc-bazel-experimental and linux-xenial-clang-bazel-experimental-cache have passed.  Would you like me to force this PR in now?

**Comment by jamiesnape** [comment]
Yes.

**Pull request merged**
