### PR TITLE
 YAML loading for SimpleRulebook (take 2).

### PR DESCRIPTION
**Pull request by maddog-tri**
Also, provide SimpleRulebook with a RemoveAll() method.

This was originally reviewed/merged as PR #8525.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8575)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@sherm1 for platform review --- since you're the guy who told me to use `DRAKE_EXPECT_THROWS_MESSAGE`.
(This should not require a separate new feature-review, correct?)

@drake-jenkins-bot mac-* please

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8575#-:-L9p_FcU6YRkP5JOifGY:b-igroqu)*

**Comment by sherm1** [comment]
Oh, so it's my fault! :) 
No feature review needed except for whatever changed -- can you highlight that for me?

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8575#-:-L9pdasYBWJlNhd5yIvu:bczwex)*

**Comment by sherm1** [comment]
OK, I see -- just the error message change in the second commit, right? Assuming that's all, :lgtm: for both.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8575#-:-L9pe0um0_Zy2sGZq60W:bvm0v2s)*

**Comment by jamiesnape** [comment]
> @drake-jenkins-bot mac-* please

If only that worked. One build should be sufficient:

@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by maddog-tri** [comment]
Thanks, all.  Hopefully this one will stick.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8575#-:-L9qeiyX828m6nGixXxj:b-k3568f)*

**Pull request merged**
