### PR TITLE
Add elevation (`h`) bounds to the maliput API.

### PR DESCRIPTION
**Pull request by maddog-tri**
This commit only defines an `HBounds` type and adds an accessor method
to the Lane API.  Implementations/use of this method will come in
forthcoming commits.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6207)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6207#-:-KlQVWmTZ6VROKCUKd7k:bltds52)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/api/lane_data.h, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6207#-KlZ08Q4Kx5sIXSCQImH:-KlZ08Q5kVx8tWKGKvOC:b-rquc92) ([raw file](https://github.com/robotlocomotion/drake/blob/7ff4eec54dbfac1b323d82eb4dabc4ad65beb1bc/drake/automotive/maliput/api/lane_data.h#L282)):*
> ```objc
> 
> /// Bounds in the elevation dimension (`h` component) of a `Lane`-frame,
> /// consisting of a pair of minimum and maximum `h` value.  The bounds
> ```

BTW: nit: "value" should be "values".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6207#-:-KlZ0UyFrVcXtumUNioK:bnfp4nl)*

**Comment by liangfok** [comment]
*[drake/automotive/maliput/api/lane_data.h, line 284 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6207#-KlZ0s-ppgBSWz2VtwU_:-KlZ0s-q7FakboJqrTTe:b9n3sxe) ([raw file](https://github.com/robotlocomotion/drake/blob/7ff4eec54dbfac1b323d82eb4dabc4ad65beb1bc/drake/automotive/maliput/api/lane_data.h#L284)):*
> ```objc
> /// consisting of a pair of minimum and maximum `h` value.  The bounds
> /// must straddle `h = 0`, i.e., the minimum must be `<= 0` and the
> /// maximum must be `>= 0`.
> ```

BTW, consider adding a hint to the reader explaining why the lower bound can be less than zero. For example, is it to model potholes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6207)*

**Comment by maddog-tri** [comment]
+@soonho-tri  for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6207#-:-KlZ5anx74WY2PJuvTpS:b27jspo)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6207#-:-KlZ99LzWDYt52a6Qa6x:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6207)*

**Pull request merged**
