### PR TITLE
Relative spatial acceleration methods to parallel relative spatial velocity.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17117)

### CODE REVIEW

**Comment by mitiguy** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please.

**Comment by mitiguy** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please.

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 (also for platform review).
Tolerances were changed and this passes Macintosh tests now. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17117#-:-N1M6cZk0Q7V_IlOfgrT:b3nhh40)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17117#-N1LU42V5UFjCw-d7COO:-N1LU42W6QHzr0TuGF0A:bcmw26l) (no related file):*
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please.

---

**Review by sherm1 — COMMENTED** [review]
Already reviewed as PR #17014 (reverted due to test tolerance on Mac, fixed here).
:lgtm: x 2

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17117#-:-N1Qu6WoAi5zI1xuulFl:bhxt9iu)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Dismissed @mitiguy from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17117)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Pull request merged**
