### PR TITLE
Made RigidBody::parent private. Renamed it to be parent_. Added accessors

### PR DESCRIPTION
**Pull request by liangfok**
Builds upon #2903 by making `RigidBody::private` private with get/set accessors. I also renamed the member variable to be `private_` to conform to style guide.

Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2904)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@david-german-tri for platform review please.

Thanks!

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-:-KNZjvJl9vDo94LeWRWY:-1870907801)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/3058/ and is thus ready for review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 6 of 15 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h, line 231 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-KNbTDGbJ3g_TWm6gxnA:-KNbTDGbJ3g_TWm6gxnB:160366737) ([raw file](https://github.com/robotlocomotion/drake/blob/284123d03373afe2527bd1935e58bfab247407d7/ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h#L231)):*
>80

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-:-KNbTGScLCY1BwBCpL5d:1417088721)*

**Comment by amcastro-tri** [comment]
Reviewed 6 of 15 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1299 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-KNbUiiYXjrr9UpU5mHE:-KNbUiiYXjrr9UpU5mHF:1136992393) ([raw file](https://github.com/robotlocomotion/drake/blob/284123d03373afe2527bd1935e58bfab247407d7/drake/systems/plants/RigidBodyTree.cpp#L1299)):*
> ```cpp
> 
>       // Hij
>       RigidBody* body_j(body_i.get_mutable_parent());
> ```

I think this should work with a const pointer to body_j(body_i). 
Would it compile if we do `const RigidBody* body_j = body_i.get_parent();` ?

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1308 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-KNbUvPC_287z598gAwQ:-KNbUvPC_287z598gAwR:829812696) ([raw file](https://github.com/robotlocomotion/drake/blob/284123d03373afe2527bd1935e58bfab247407d7/drake/systems/plants/RigidBodyTree.cpp#L1308)):*
> ```cpp
>         ret.block(v_start_i, v_start_j, nv_i, nv_j) = Hji.transpose();
> 
>         body_j = body_j->get_mutable_parent();
> ```

Same here: `body_j = body_j->get_parent();`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2904)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. @amcastro-tri PTAL.

---

Review status: 5 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1299 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-KNbUiiYXjrr9UpU5mHE:-KNbi_SO0DeGuA_pkNCe:-2048594082) ([raw file](https://github.com/robotlocomotion/drake/blob/284123d03373afe2527bd1935e58bfab247407d7/drake/systems/plants/RigidBodyTree.cpp#L1299)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I think this should work with a const pointer to body_j(body_i). 
> Would it compile if we do `const RigidBody* body_j = body_i.get_parent();` ?
</details>
You're right. Done.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1308 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-KNbUvPC_287z598gAwQ:-KNbibfgClU6za5hCHYA:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/284123d03373afe2527bd1935e58bfab247407d7/drake/systems/plants/RigidBodyTree.cpp#L1308)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Same here: `body_j = body_j->get_parent();`
</details>
Done.

---

*[ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h, line 231 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-KNbTDGbJ3g_TWm6gxnA:-KNbiiHo7AklptXlTCni:1508991532) ([raw file](https://github.com/robotlocomotion/drake/blob/284123d03373afe2527bd1935e58bfab247407d7/ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h#L231)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> >80
</details>
Done. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-:-KNbir7JKt6h7dUdn5qV:-1217529012)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/3075/ and is thus ready for @amcastro-tri's feature review.

---

Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-:-KNdy1DR9AB67JpP2TPs:632599815)*

**Comment by liangfok** [comment]
Still waiting on @amcastro-tri's feature review.

---

Review status: 5 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-:-KNhpdCruBXE0ZneBZBW:789502157)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r4.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2904#-:-KNlfLzDX4YXlPkpzY5U:1417088721)*

**Pull request merged**
