### PR TITLE
[solvers] MathematicalProgram AddDecisionVariables and AddIndeterminates allow duplicated variables.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: with a few nits

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-:-NRiDlurDuxOwlv-CS46:bhcznl8)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 819 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NRiCiCn0xghlAhybdIX:-NRiCiCn0xghlAhybdIY:bevldsa) ([raw file](https://github.com/RobotLocomotion/drake/blob/41851903d9c3d3b68a0c88faea38749f7f45c619/solvers/mathematical_program.h#L819)):*
> ```objc
>    * @param new_indeterminate The indeterminate to be appended to the
>    * program's old indeterminates.
>    * @return indeterminate_index prog.indeterminates()(indeterminate_index) =
> ```

Perhaps add an English sentence as documentation.
`@return indeterminate_index The index of the added indeterminate in the program's indeterminates. i.e.  prog.indeterminates()(indeterminate_index) = new_indeterminate`
___
*[`solvers/mathematical_program.cc` line 358 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NRiDJ48EsStz1EOJC_e:-NRiDJ49AJ0R4Ic2Zz6o:b297ys9) ([raw file](https://github.com/RobotLocomotion/drake/blob/41851903d9c3d3b68a0c88faea38749f7f45c619/solvers/mathematical_program.cc#L358)):*
> ```cpp
>   }
>   if (indeterminates_index_.find(new_indeterminate.get_id()) !=
>       indeterminates_index_.end()) {
> ```

We can delete this whole if clause now.



_Code quote:_
```cpp
  if (indeterminates_index_.find(new_indeterminate.get_id()) !=
      indeterminates_index_.end()) {
  }
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 819 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NRiCiCn0xghlAhybdIX:-NRi_ryc0qLXOv8TyoOF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/41851903d9c3d3b68a0c88faea38749f7f45c619/solvers/mathematical_program.h#L819)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Perhaps add an English sentence as documentation.
`@return indeterminate_index The index of the added indeterminate in the program's indeterminates. i.e.  prog.indeterminates()(indeterminate_index) = new_indeterminate`
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.cc` line 358 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NRiDJ48EsStz1EOJC_e:-NRi_tGL8bT8Fkjwr6f2:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/41851903d9c3d3b68a0c88faea38749f7f45c619/solvers/mathematical_program.cc#L358)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

We can delete this whole if clause now.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for Monday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-:-NS23I0XBlS3WRvJmfbj:b-kpkmak)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform with two minor points.

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-:-NS7KqQ2Eu5z9J3Jfb7i:bxdrbf4)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 827 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NS7IFYf2SdsxzEMAkoM:-NS7IFYgEg2aCOwaU2Fp:b-ty3tqi) ([raw file](https://github.com/RobotLocomotion/drake/blob/71e2dd34513e9fad8d0d2b7ae33a4760d34a0785/solvers/mathematical_program.h#L827)):*
> ```objc
>    * @pre new_indeterminate should be of CONTINUOUS type.
>    */
>   int AddIndeterminate(const symbolic::Variable& new_indeterminate);
> ```

BTW, is this going to be a breaking change? I vaguely remember this function only being introduced in this release cycle but want to check to make sure.
___
*[`solvers/mathematical_program.cc` line 137 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NS7IXdt2V5UN0MQ61W6:-NS7IXdt2V5UN0MQ61W7:b-tavozo) ([raw file](https://github.com/RobotLocomotion/drake/blob/71e2dd34513e9fad8d0d2b7ae33a4760d34a0785/solvers/mathematical_program.cc#L137)):*
> ```cpp
>       const int var_index = decision_variables_.size() - 1;
>       decision_variable_index_.insert(std::make_pair(var.get_id(), var_index));
>       new_var_count++;
> ```

nit, use pre-increment over post-increment.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice and @xuchenhan-tri)

___
*[`solvers/mathematical_program.h` line 827 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NS7IFYf2SdsxzEMAkoM:-NS7Nn_v0YGvsQ2w4iDp:bjn4i3y) ([raw file](https://github.com/RobotLocomotion/drake/blob/71e2dd34513e9fad8d0d2b7ae33a4760d34a0785/solvers/mathematical_program.h#L827)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is this going to be a breaking change? I vaguely remember this function only being introduced in this release cycle but want to check to make sure.
</blockquote></details>

This changes the behavior of the code. Previously the code would throw an error, now it doesn't throw an error and accepts the input that previously regarded erroneous. Would this count as breaking change?

Some of the functions, like `AddDecisionVariables` has been in MathematicalProgram a long time ago.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 827 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NS7IFYf2SdsxzEMAkoM:-NS7PJ5q7z-mPddrPCB_:byuqvdb) ([raw file](https://github.com/RobotLocomotion/drake/blob/71e2dd34513e9fad8d0d2b7ae33a4760d34a0785/solvers/mathematical_program.h#L827)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This changes the behavior of the code. Previously the code would throw an error, now it doesn't throw an error and accepts the input that previously regarded erroneous. Would this count as breaking change?

Some of the functions, like `AddDecisionVariables` has been in MathematicalProgram a long time ago.
</blockquote></details>

This PR changes the signature of the function `AddIndeterminate` from `void` to returning an int. I can imagine (unlikely) scenarios that this might break someone's code. 

But if `AddIndeterminate` is added within this cycle, any "breaking change" discussions are irrelevant.
___
*[`solvers/mathematical_program.cc` line 137 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NS7IXdt2V5UN0MQ61W6:-NS7PtVWBwAsvMTgQqVT:b-z9dd1h) ([raw file](https://github.com/RobotLocomotion/drake/blob/71e2dd34513e9fad8d0d2b7ae33a4760d34a0785/solvers/mathematical_program.cc#L137)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, use pre-increment over post-increment.
</blockquote></details>

missing a semicolon.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 827 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NS7IFYf2SdsxzEMAkoM:-NS7QwI62i_Ps8s7qF93:bz6mijb) ([raw file](https://github.com/RobotLocomotion/drake/blob/71e2dd34513e9fad8d0d2b7ae33a4760d34a0785/solvers/mathematical_program.h#L827)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This PR changes the signature of the function `AddIndeterminate` from `void` to returning an int. I can imagine (unlikely) scenarios that this might break someone's code. 

But if `AddIndeterminate` is added within this cycle, any "breaking change" discussions are irrelevant.
</blockquote></details>

git blame reveals that this overload of `AddIndeterminate` didn't make the cut for the previous release so we should be a-ok.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087)* status: missing label for release notes (waiting on @xuchenhan-tri)

___
*[`solvers/mathematical_program.h` line 827 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NS7IFYf2SdsxzEMAkoM:-NS7SIae403yc0yYWsWX:b-4fdnp6) ([raw file](https://github.com/RobotLocomotion/drake/blob/71e2dd34513e9fad8d0d2b7ae33a4760d34a0785/solvers/mathematical_program.h#L827)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

git blame reveals that this overload of `AddIndeterminate` didn't make the cut for the previous release so we should be a-ok.
</blockquote></details>

I see, so the breaking change here means that the API changes. Only `AddIndeterminate` changes the API (the return type). `AddDecisionVariable` doesn't change the API.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 827 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-NS7IFYf2SdsxzEMAkoM:-NS7VGNsDS9xljAehD1_:b-b78vu1) ([raw file](https://github.com/RobotLocomotion/drake/blob/71e2dd34513e9fad8d0d2b7ae33a4760d34a0785/solvers/mathematical_program.h#L827)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, so the breaking change here means that the API changes. Only `AddIndeterminate` changes the API (the return type). `AddDecisionVariable` doesn't change the API. 
</blockquote></details>

FWIW, Here is our stability guideline: https://drake.mit.edu/stable.html. See the "Exemptions" section.

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: fix) relates #18992.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19087#-:-NS7k5lq0dKfGzQABe_e:bf02y80)* status: :shipit: complete! all discussions resolved, LGTM from assignees AlexandreAmice,xuchenhan-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
