### PR TITLE
Generalizes PidControlledSystem To Support Gain Vector and Plants where # Outputs > 2 * # Inputs

### LINKED ISSUE #3899: Generalize PidControlledSystem<T> To Support Plants With More Outputs Than Actuator Inputs
The current implementation of `PidControlledSystem<T>` requires that the plant being controlled contain exactly twice as many output ports as input ports. This prevents `PidControlledSystem<T>` from working with `RigidBodyPlant` systems of models that have quaternion floating joints or are under-actuated. We need to somehow tell `PidControlledSystem<T>` which of the outputs should be used as part of the feedback control signal.

This issue is preventing the System 2.0 version of `car_sim_lcm` from passing CI in #3886 because the `RigidBodyPlant` has 6 inputs but 27 outputs.

### PR DESCRIPTION
**Pull request by liangfok**
This is necessary for the `car_sim_lcm` demo (towards: #3886).

Closes #3899.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3947)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR passed all CI pre-merge builds. Thus:

+@sammy-tri for feature review please since you were the original author of `PidControlledSystem`.
+@sherm1 for platform review please per rotation schedule.

Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-:-KVD-NPiN-zzh3S3OyKt:b-lflsbt)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVQlMomOCwOFtQH_Kcp:-KVQlMonolG9ib8evdUQ:b-xnbrvt) ([raw file](https://github.com/robotlocomotion/drake/blob/f47dfc3d7be8b2dbe7fde79a0c0bef55a6cadf78/drake/systems/controllers/pid_controlled_system.cc#L25)):*
> ```cpp
>   // existence of extra values in the output port which are discarded
>   // because they're not relevant to the control we're applying here
>   // (see PidControlledSpringMassSystem which discards the energy
> ```

BTW could this example actually be converted now?   (not necessary for this PR or maybe ever)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-:-KVQlWG07PS9F0e23wrn:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVQlMomOCwOFtQH_Kcp:-KVQvFhwGy47N6TnW8uY:b5h68u2) ([raw file](https://github.com/robotlocomotion/drake/blob/f47dfc3d7be8b2dbe7fde79a0c0bef55a6cadf78/drake/systems/controllers/pid_controlled_system.cc#L25)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW could this example actually be converted now?   (not necessary for this PR or maybe ever)
</details>
I'm not sure what you mean. Can you clarify please?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3947)*

**Comment by liangfok** [comment]
Thanks. Now waiting on a platform review from @sherm1.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVQlMomOCwOFtQH_Kcp:-KVQxUqdp348wLM2B48s:bzgqm8) ([raw file](https://github.com/robotlocomotion/drake/blob/e354069e36dec426b507237c10410e4d90e87ed3/drake/systems/controllers/pid_controlled_system.cc#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I'm not sure what you mean. Can you clarify please?
</details>
Oh, I now see you mean convert the `PidControlledSpringMassSystem` to use this new API.  I created #3966 to track this update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-:-KVQvKgeyDD43H9ZIwyB:b-5gadts)*

**Comment by sherm1** [comment]
Looks very nice. A few minor comments, PTAL. :lgtm: after those are dealt with.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVRUkHlbFrrnnIdj6-N:-KVRUkHlbFrrnnIdj6-O:b-zd37ab) ([raw file](https://github.com/robotlocomotion/drake/blob/46f7b8d0edbdcd289795d52e9ac705b990d1d985/drake/systems/controllers/pid_controlled_system.cc#L56)):*
> ```cpp
>   if (feedback_selector == nullptr) {
>     feedback_selector =
>         std::make_unique<MatrixGain<T>>(plant_->get_output_port(0).get_size());
> ```

BTW, a short comment would be helpful here. Does this make an "identity" MatrixGain?

---

*[drake/systems/controllers/pid_controlled_system.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVRTPUJv8UGeqjHIg1e:-KVRTPUJv8UGeqjHIg1f:b-6gw9bo) ([raw file](https://github.com/robotlocomotion/drake/blob/46f7b8d0edbdcd289795d52e9ac705b990d1d985/drake/systems/controllers/pid_controlled_system.h#L78)):*
> ```objc
>   /// @param[in] Kp the proportional vector constant.
>   /// @param[in] Ki the integral vector constant.
>   /// @param[in] Kd the derivative vector constant.
> ```

Param comments should clarify any restrictions on the vector lengths. Do these all have to be the same length? (Here and below.)

---

*[drake/systems/controllers/pid_controlled_system.h, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVRTrXnp49N9ln9ojF7:-KVRTrXnp49N9ln9ojF8:b-7erf81) ([raw file](https://github.com/robotlocomotion/drake/blob/46f7b8d0edbdcd289795d52e9ac705b990d1d985/drake/systems/controllers/pid_controlled_system.h#L89)):*
> ```objc
>   /// @param[in] plant The system to be controlled. This must not be `nullptr`.
>   /// @param[in] feedback_selector The system that selects which part of the
>   /// system's output port zero is fed back to the PID controller. For semantic
> ```

"system" used twice here -- did you mean "plant" the second time? (Here and below.)

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVRRp48eDJfqZ-eFlE6:-KVRRp48eDJfqZ-eFlE7:bb3xn35) ([raw file](https://github.com/robotlocomotion/drake/blob/46f7b8d0edbdcd289795d52e9ac705b990d1d985/drake/systems/controllers/test/pid_controlled_system_test.cc#L28)):*
> ```cpp
> };
> 
> class TestPlantWithMinOutputs : public TestPlant {
> ```

This test program needs some comments explaining what it is up to. Some kind of ascii representation of the diagram topology would also be nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-:-KVRWNdrKWtTe9Pw2MqN:b-hilfno)*

**Comment by liangfok** [comment]
@sherm1, thanks for the review. I addressed your comments. PTAL. 

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVRUkHlbFrrnnIdj6-N:-KVRd9PUpwolaOr26G2E:b-e20sjk) ([raw file](https://github.com/robotlocomotion/drake/blob/46f7b8d0edbdcd289795d52e9ac705b990d1d985/drake/systems/controllers/pid_controlled_system.cc#L56)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, a short comment would be helpful here. Does this make an "identity" MatrixGain?
</details>
Done. Yes, it uses an identity matrix gain.

---

*[drake/systems/controllers/pid_controlled_system.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVRTPUJv8UGeqjHIg1e:-KVRewwg8hG0ceepf5pO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46f7b8d0edbdcd289795d52e9ac705b990d1d985/drake/systems/controllers/pid_controlled_system.h#L78)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Param comments should clarify any restrictions on the vector lengths. Do these all have to be the same length? (Here and below.)
</details>
Done.

---

*[drake/systems/controllers/pid_controlled_system.h, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVRTrXnp49N9ln9ojF7:-KVSwE0PcJfBoXyKI5ep:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46f7b8d0edbdcd289795d52e9ac705b990d1d985/drake/systems/controllers/pid_controlled_system.h#L89)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "system" used twice here -- did you mean "plant" the second time? (Here and below.)
</details>
Done.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVRRp48eDJfqZ-eFlE6:-KVT3sHTFJgfNP4W0sjZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46f7b8d0edbdcd289795d52e9ac705b990d1d985/drake/systems/controllers/test/pid_controlled_system_test.cc#L28)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This test program needs some comments explaining what it is up to. Some kind of ascii representation of the diagram topology would also be nice.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-:-KVT3tYEgvidNyrvSRlC:b362ny)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-KVRRp48eDJfqZ-eFlE6:-KVVNpavI6achKUm_7Rm:b8vtwz3) ([raw file](https://github.com/robotlocomotion/drake/blob/46f7b8d0edbdcd289795d52e9ac705b990d1d985/drake/systems/controllers/test/pid_controlled_system_test.cc#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
Wow -- beautiful! Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3947#-:-KVVObF7fCOvy4wp7DQZ:bnfp4nl)*

**Pull request merged**
