### PR TITLE
Add tests for RigidFrame::SetCenterOfMassInBodyFrame

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18304)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please -- as an apparent follow-up from #18251.

**Review by sherm1 — COMMENTED** [review]
Great tests, thanks!
Feature :lgtm_strong: pending some nits.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18304#-:-NH0RcbX1XtqJpRbfHuY:b-vw3fd4)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/rigid_body.h` line 137 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18304#-NH0KbRBAk2xguGzUzdJ:-NH0KbRC0bgAqN4vDMmv:bcee0lv) ([raw file](https://github.com/robotlocomotion/drake/blob/6a33fa45be1103a3489ce5df64d38278bb376dcc/multibody/tree/rigid_body.h#L137)):*
> ```objc
>   /// Gets the mass stored in @p context.
>   /// @param[in] context contains the state of the multibody system.
>   /// @pre the context should make sense for use by `this` RigidBody.
> ```

BTW a precondition is a _condition_ (state of being) rather than a prescription or instruction, so it should be worded like this:
`@pre the context makes sense for use by this RigidBody`

Other examples:
`@pre the pointer is not null`
`@pre index is in range`
`@pre mass > 0`

Please consider rewording.
___
*[`multibody/tree/rigid_body.h` line 182 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18304#-NH0MkTa9EicKuCGoJt1:-NH0MkTa9EicKuCGoJt2:bmyw035) ([raw file](https://github.com/robotlocomotion/drake/blob/6a33fa45be1103a3489ce5df64d38278bb376dcc/multibody/tree/rigid_body.h#L182)):*
> ```objc
>   // SpatialInertia<T> as an abstract parameter.
> 
>   /// Gets this bodys spatial inertia about it origin that is stored in context.
> ```

typo bodys -> body's, it -> its

Also, the phrasing is inconsistent with the CalcCenterOfMassInBodyFrame() phrasing which says "Gets the center of mass stored in @p context" (with no period). When the meaning is identical, the phrasing should be identical to avoid implying to the user that there is some difference when there is not. Any of these would be fine if consistent. FYI my preference is something like:
`Gets this body's spatial inertia about its origin from the given context.` (That is, "from" seems to cover more ground with less text.)

**Review by sherm1 — COMMENTED** [review]
+@xuchenhan-tri for platform review per rotation, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18304#-:-NH0S7EV3mksMKQNjnrH:brlcbhf)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18304#-:-NH0Zm5G1_gyz7JHr-Yi:b-cxwtpw)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/test/rigid_body_test.cc` line 120 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18304#-NH0WQBv92PM60LZYn_S:-NH0WQBv92PM60LZYn_T:bz8rxlf) ([raw file](https://github.com/robotlocomotion/drake/blob/6a33fa45be1103a3489ce5df64d38278bb376dcc/multibody/tree/test/rigid_body_test.cc#L120)):*
> ```cpp
>   rigid_body_->SetMass(context_ptr, mass);
>   EXPECT_EQ(rigid_body_->get_mass(*context_ptr), mass);
>   M_BBo_B = rigid_body_->CalcSpatialInertiaInBodyFrame(*context_);
> ```

BTW, is the mixed use of `*context_` and `*context_ptr` intentional? If not, consider unifying them.
___
*[`multibody/tree/test/rigid_body_test.cc` line 159 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18304#-NH0YQ2M1jCREtxwJKPu:-NH0YQ2M1jCREtxwJKPv:b-j686mh) ([raw file](https://github.com/robotlocomotion/drake/blob/6a33fa45be1103a3489ce5df64d38278bb376dcc/multibody/tree/test/rigid_body_test.cc#L159)):*
> ```cpp
>   rigid_body_->SetCenterOfMassInBodyFrame(context_ptr, p_BoBcm_B);
>   M_BBo_B = rigid_body_->CalcSpatialInertiaInBodyFrame(*context_);
>   DRAKE_EXPECT_THROWS_MESSAGE(M_BBcm_B = M_BBo_B.Shift(p_BoBcm_B),
> ```

BTW, a potentially dumb question: is it true that `M_BBo_B` is already invalid when `CalcSpatialInertiaInBodyFrame` is called and the throw message is only triggered when `M_BBo_B.Shift(foo)` is invoked?

If that is the case, probably worth mentioning it. Just by reading the test itself, it seems like something goes wrong in `Shift`. Also btw assigning the result of `Shift` to M_BBcm_B` seems unnecessary.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18304)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[`multibody/tree/rigid_body.h` line 137 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18304#-NH0KbRBAk2xguGzUzdJ:-NH1Ock68842HoW8LKeD:b-snh328) ([raw file](https://github.com/robotlocomotion/drake/blob/6a33fa45be1103a3489ce5df64d38278bb376dcc/multibody/tree/rigid_body.h#L137)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW a precondition is a _condition_ (state of being) rather than a prescription or instruction, so it should be worded like this:
`@pre the context makes sense for use by this RigidBody`

Other examples:
`@pre the pointer is not null`
`@pre index is in range`
`@pre mass > 0`

Please consider rewording.

</blockquote></details>

Done here and elsewhere.
___
*[`multibody/tree/rigid_body.h` line 182 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18304#-NH0MkTa9EicKuCGoJt1:-NH1WvyYCPWWXrisl3Tn:b-42gwpf) ([raw file](https://github.com/robotlocomotion/drake/blob/6a33fa45be1103a3489ce5df64d38278bb376dcc/multibody/tree/rigid_body.h#L182)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo bodys -> body's, it -> its

Also, the phrasing is inconsistent with the CalcCenterOfMassInBodyFrame() phrasing which says "Gets the center of mass stored in @p context" (with no period). When the meaning is identical, the phrasing should be identical to avoid implying to the user that there is some difference when there is not. Any of these would be fine if consistent. FYI my preference is something like:
`Gets this body's spatial inertia about its origin from the given context.` (That is, "from" seems to cover more ground with less text.)
</blockquote></details>

Done here and elsewhere to make consistent.
___
*[`multibody/tree/test/rigid_body_test.cc` line 120 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18304#-NH0WQBv92PM60LZYn_S:-NH1ZYst75Nr6nLSsGR_:bpexes2) ([raw file](https://github.com/robotlocomotion/drake/blob/6a33fa45be1103a3489ce5df64d38278bb376dcc/multibody/tree/test/rigid_body_test.cc#L120)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is the mixed use of `*context_` and `*context_ptr` intentional? If not, consider unifying them.
</blockquote></details>

Unified to *context_ and context_ptr -- but no more *context_ptr.
___
*[`multibody/tree/test/rigid_body_test.cc` line 159 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18304#-NH0YQ2M1jCREtxwJKPu:-NH1ZfS_7P6Xwr-bgxBR:ber6pid) ([raw file](https://github.com/robotlocomotion/drake/blob/6a33fa45be1103a3489ce5df64d38278bb376dcc/multibody/tree/test/rigid_body_test.cc#L159)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, a potentially dumb question: is it true that `M_BBo_B` is already invalid when `CalcSpatialInertiaInBodyFrame` is called and the throw message is only triggered when `M_BBo_B.Shift(foo)` is invoked?

If that is the case, probably worth mentioning it. Just by reading the test itself, it seems like something goes wrong in `Shift`. Also btw assigning the result of `Shift` to M_BBcm_B` seems unnecessary.
</blockquote></details>

Done.  Good point Xuchen.  Updated -- hopefully addresses the question.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18304)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18304)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18304#-:-NH1pGLD97VQQL71uGEf:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @mitiguy)

**Pull request merged**
