### PR TITLE
[meshcat] Add a binding/doc/test for SetTriangleColorMesh

### LINKED ISSUE #18096: [meshcat] meshes set through SetTriangleMesh and SetTriangleColorMesh are all black
### What happened?

```
mu = 1.0
height = .3
N = 50
t = np.linspace(0, 2*np.pi, N)
vertices = np.vstack((height*mu*np.sin(t), height*mu*np.cos(t), height + 0*t))
vertices = np.append(np.array([[0], [0], [height]]), vertices, axis=1)
vertices = np.append(np.zeros((3,1)), vertices, axis=1)
faces = []
for i in range(N):
    faces.append([0, i+2, i+3])
    faces.append([0, i+3, i+2])
    faces.append([1, i+2, i+3])
    faces.append([1, i+3, i+2])
faces = np.asarray(faces, dtype=int).T
meshcat.SetTriangleMesh("my_cone", vertices, faces, rgba=Rgba(0, 0, 1, 1))
```
produces a black cone.  I was hoping for a blue one.

I was not able to resolve this using `SetTriangleColorMesh`.  These methods are not very welll covered in `meshcat_manual_test`.  And the units of the color matrix in `SetTriangleColorMesh` are not properly documented.  [0,1]?  [0, 255]?  (Sorry!  The fault is mine!)

There is a test that uses the `TriangleSurfaceMesh` (which calls these methods), and renders the color properly.  

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #18096.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18100)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
BTW How does this resolve #18096? The mistake made there (and the API used there) don't obviously apply to the bindings here.

**Comment by jwnimmer-tri** [comment]
There are three problems listed in the linked issue:

(1) The triangles were all black.

(2) "These methods are not very well covered in meshcat_manual_test."

(3) "And the units of the color matrix in SetTriangleColorMesh are not properly documented."

This PR fixes (2) and (3).

Part (1) appears to be user error, and it seems plausible to be to say that there's no need to add additional mitigation for that case into our code or docs.

Or are you saying that Drake _should_ try to detect the unwanted duplication?

**Comment by SeanCurtis-TRI** [comment]
Ah....I'd glossed over 2 & 3. Fair enough.

**Comment by jwnimmer-tri** [comment]
Maybe @joemasterjohn would like to feature-review this?

**Review by joemasterjohn — COMMENTED** [review]
+@joemasterjohn for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18100#-:-NEImfk12h48sJft670m:bjjfqi0)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: as is. +@jwnimmer-tri for platform review, if time permits.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18100#-:-NEgnu3o2NIPCQWVZRCx:b-rl1itx)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18100#-:-NEgv3LHEmj0fkRC9zCs:b-vtj4vo)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),joemasterjohn (waiting on @RussTedrake)

___
*[`geometry/test/meshcat_manual_test.cc` line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18100#-NEgvNiL1GrQKjdJrF55:-NEgvNiL1GrQKjdJrF56:blcv7et) ([raw file](https://github.com/robotlocomotion/drake/blob/3c577dff09afeac1f34cdd39f1d57f70b46e9e45/geometry/test/meshcat_manual_test.cc#L147)):*
> ```cpp
> 
> - The background should be grey.
> - From left to right along the x axis, you should see:
> ```

FYI Each time I run this, I find it a teeny bit annoying that I need to change the meshcat viewport with my mouse to see everything.  It would be nice if all of these objects fit on the screen by default, either with a different viewport or by splitting the formation into two rows instead of one long row.

Future work.

**Pull request merged**
