### PR TITLE
[doc] Add release notes v1.2.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16939)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16939)* status: LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm: with a couple of comments

> Reviewed 1 of 2 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16939#-:-N-xTIKU5G9WZ441B1lM:b-iwggwp)* status: 2 unresolved discussions, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v1.2.0.md, line 14 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16939#-N-xRyI_BYtpBU4-RkHL:-N-xRyI_BYtpBU4-RkHM:bbnyk8f) ([raw file](https://github.com/robotlocomotion/drake/blob/3e6f79e61d4ef37edbcc7896777cce1bebaca6ce/doc/_release-notes/v1.2.0.md#L14)):*
> ```Markdown
> * Drake no longer supports Ubuntu 18.04 "Bionic", Python 3.6, or Python 3.7
>   ([#13391][_#13391]).
> * Drake no longer supports drake-visualizer on macOS ([#16945][_#16945]).
> ```

BTW should mention here that meldis/meshcat is available on Mac (to avoid panic).
___
*[tools/workspace/cc/repository.bzl, line 38 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16939#-N-xTBjWEJt2RI92ilWw:-N-xTBjX1Fwq1cIYSM4P:bqez3t2) ([raw file](https://github.com/robotlocomotion/drake/blob/3e6f79e61d4ef37edbcc7896777cce1bebaca6ce/tools/workspace/cc/repository.bzl#L38)):*
> ```Starlark
> 
> def _impl(repository_ctx):
>     fail("Disable CI")
> ```

BTW does this need to be removed?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16939)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[tools/workspace/cc/repository.bzl, line 38 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16939#-N-xTBjWEJt2RI92ilWw:-N-xVBfGDo4nuJ4jz8rn:b2v3gey) ([raw file](https://github.com/robotlocomotion/drake/blob/3e6f79e61d4ef37edbcc7896777cce1bebaca6ce/tools/workspace/cc/repository.bzl#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW does this need to be removed?
</blockquote></details>

Yes.  It disables CI (just like it says on the tin), to save money on every push.  I won't be able to merge the PR until I revert this.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16939)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[doc/_release-notes/v1.2.0.md, line 14 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16939#-N-xRyI_BYtpBU4-RkHL:-N0197CH6Wnng9wZ-wei:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e6f79e61d4ef37edbcc7896777cce1bebaca6ce/doc/_release-notes/v1.2.0.md#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should mention here that meldis/meshcat is available on Mac (to avoid panic).
</blockquote></details>

Done.

**Pull request merged**
