### PR TITLE
[geometry] Replace collision filter legacy for collision filter (breaking)

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
We're changing the under-the-hood implementation of collision filters. Removing `CollisionFilterLegacy` has the following further implications:

  - Existing API on `GeometryState` has been re-expressed in terms of the new collision filter mechanism.
  - `ProximityEngine` has entirely lost its collision filtering logic. It now relies on the `CollisionFilter` class to do "apply" declarations.
  - (Breaking) The "sorted vectors have intersection" supporting code in the common directory is no longer used. Removing it is *technically* a breaking change, but it's code that never really belonged in common and is *highly* unlikely to be used by anyone else, ever.
  - All explicit references to "cliques" are removed
    - `InternalFrame` no longer tracks "frame cliques"
    - Testing is no longer expressed in terms of cliques.
    - `GeometryState` and `ProximityEngine` have lost clique-related APIs.
    - Removal of the attorney between geometry state and collision filters.
  - All callbacks that were dependent on `CollisionFilterLegacy` get touched. (This represents roughly two thirds of the changed files).
    - Their declared type has changed.
    - They no longer operate on `EncodedData::encoding()`, but on `id()`.

Relates #15089.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15297)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review, please. Welcome back!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15297#-:-MdxXrgKB6lk-KKoWhsh:b-itmra)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:sweat_smile: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15297#-:-MdxbnYW4c1GBJx-_UPo:be2l6su)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15297#-:-Mdy0-dj4gR_nDsrTr0j:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[geometry/BUILD.bazel, line 193 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15297#-Mdxw7wrAHOF6G7QpdS3:-Mdxw7wrAHOF6G7QpdS4:bnkvv4e) ([raw file](https://github.com/robotlocomotion/drake/blob/17821b87785f067da7b112a4a600096d004c9b6c/geometry/BUILD.bazel#L193)):*
> ```Starlark
>     hdrs = ["geometry_state.h"],
>     deps = [
>         ":collision_filter_declaration",
> ```

I suspect this dependency is unnecessary, since the included header appears to be unused.
___
*[geometry/geometry_state.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15297#-MdxrLqVApWVwuYW5RW2:-MdxrLqVApWVwuYW5RW3:buzc583) ([raw file](https://github.com/robotlocomotion/drake/blob/17821b87785f067da7b112a4a600096d004c9b6c/geometry/geometry_state.h#L14)):*
> ```objc
> #include "drake/common/autodiff.h"
> #include "drake/common/drake_copyable.h"
> #include "drake/geometry/collision_filter_declaration.h"
> ```

unused.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@soonho-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15297#-:-Me0UB5d8gV-OPgPe-2v:bxwr5c8)* status: 2 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @rpoyner-tri and @soonho-tri)

___
*[geometry/geometry_state.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15297#-MdxrLqVApWVwuYW5RW2:-Me0U9cxAX4Izo62I2mN:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/17821b87785f067da7b112a4a600096d004c9b6c/geometry/geometry_state.h#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done
___
*[geometry/BUILD.bazel, line 193 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15297#-Mdxw7wrAHOF6G7QpdS3:-Me0U4-V7YLkcdcHWaMn:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/17821b87785f067da7b112a4a600096d004c9b6c/geometry/BUILD.bazel#L193)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I suspect this dependency is unnecessary, since the included header appears to be unused.
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15297)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
>   - (Breaking) The "sorted vectors have intersection" supporting code in
    the common directory is no longer used. Removing it is *technically*
    a breaking change, but it's code that never really belonged in common
    and is *highly* unlikely to be used by anyone else, ever.

OK. I trust your judgment here.

Other than this one, the other API-level changes (such as the deletion of `CollisionFilterLegacy` class) occur in `internal` namespace so we do not need a separate deprecation step.

:lgtm:

> Reviewed 32 of 34 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15297#-:-Me0uCIP9gNfd-nK7apl:b-lq73fl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),soonho-tri(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
