### PR TITLE
Switch library name from drakeSimpleCar to drakeCars.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2343) &emsp; Multiple assignees:&emsp;@ggould-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/ggould-tri">ggould-tri</a>,&emsp;@rpoyner-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/rpoyner-tri">rpoyner-tri</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri feature review please.
+@ggould-tri platform review please.

**Comment by ggould-tri** [comment]
* `drake/examples/Cars/README.md` still references the `SimpleCar` directory.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@rpoyner-tri feature review please.
> 
> +@ggould-tri platform review please.
> 
> </details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2343#-:-KHtr9p7qtuFTmfrLNCZ:1152841140)*

**Comment by rpoyner-tri** [comment]
:lgtm:

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
>  * `drake/examples/Cars/README.md` still references the `SimpleCar` directory.
> </details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2343#-:-KHttTb1OBWKOKEdrM2-:1417088721)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
:lgtm:

<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2343#-:-KHttwVwgH0RXNjkrjVs:1417088721)*

**Comment by jwnimmer-tri** [comment]
Thanks.  All comments addressed (I fixed the README).  Now just need to wait for jenkins to pass after my rebase.

**Comment by liangfok** [comment]
:lgtm: 

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Thanks.  All comments addressed (I fixed the README).  Now just need to wait for jenkins to pass after my rebase.</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2343#-:-KHtymvRU8wU1gevIEIy:980077423)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
The only jenkins error is in cpplint build, and it has the same 23 warnings as master #2364 regression.   Also this branch is out-of-date-with-master.  Using override-merge to overcome both complaints.

**Pull request merged**
