### PR TITLE
Toward #3029: Fix DOS-style line endings in thirdParty/.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3084)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
the last mass file change for #3029.

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please

**Comment by rpoyner-tri** [comment]
+@sherm1 for both levels of review (it's Monday!)

If I did this right, the result of "git show -w" should be empty, since all the changes are white space.

---

Review status: 0 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3084#-:-KOfGHoB7d-RxEwdndco:b-phfoi3)*

**Comment by sherm1** [comment]
Platform/feature reviews: :lgtm:. Reviewable did a great job of suppressing diffs for whitespace-only changes so it was easy to verify that only whitespace changes were made.

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3084#-:-KOfrTmbXAiKPhh-QNyJ:byy3x0n)*

**Pull request merged**
