### PR TITLE
Added documentation to Rigidbody::getMass().

### PR DESCRIPTION
**Pull request by liangfok**
Updated implementation to use a range-based for loop (http://en.cppreference.com/w/cpp/language/range-for).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2938)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@david-german-tri for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-:-KNcSiUo3jnzhFxH9Y4g:1885263313)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 914 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-KNck2tA_9qhYV_QGw7l:-KNck2tBCe5l1B46ryaj:1886725586) ([raw file](https://github.com/robotlocomotion/drake/blob/b25f7615448489ff4d01714adae6e5cc6f2e30fe/drake/systems/plants/RigidBodyTree.cpp#L914)):*
> ```cpp
> double RigidBodyTree::getMass(const std::set<int>& model_ids) const {
>   double total_mass = 0.0;
>   for (auto& body : bodies) {
> ```

Can this be `const`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-:-KNckMOZiiftFlsq6quE:1417088721)*

**Comment by liangfok** [comment]
Waiting on @amcastro-tri for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 914 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-KNck2tA_9qhYV_QGw7l:-KNd91s2hIvuoMTbppHg:2109517944) ([raw file](https://github.com/robotlocomotion/drake/blob/b25f7615448489ff4d01714adae6e5cc6f2e30fe/drake/systems/plants/RigidBodyTree.cpp#L914)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Can this be `const`?
</details>
Yes. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-:-KNd93_oQxzqayC9JUrH:-977047214)*

**Comment by liangfok** [comment]
Still waiting on @amcastro-tri's feature review.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-:-KNhpnCuEHXccSiZjPxn:789502157)*

**Comment by amcastro-tri** [comment]
A few minor comments. Otherwise it :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 176 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-KNlkNURWZ-B5bgpi2TT:-KNlkNUSo2a80Ml2CXan:2016607208) ([raw file](https://github.com/robotlocomotion/drake/blob/1daba8dba23b0f616f910ca4d3e06b5b3756a614/drake/systems/plants/RigidBodyTree.h#L176)):*
> ```objc
> 
>   /**
>    * Returns the total mass of a set of models in this rigid body tree.
> ```

Consider: "Computes the total mass of a set of models in this rigid body tree." so that it looks different from the return statement below.

---

*[drake/systems/plants/RigidBodyTree.h, line 181 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-KNlkWnMJusWXXkHjxXT:-KNlkWnMJusWXXkHjxXU:1355340584) ([raw file](https://github.com/robotlocomotion/drake/blob/1daba8dba23b0f616f910ca4d3e06b5b3756a614/drake/systems/plants/RigidBodyTree.h#L181)):*
> ```objc
>    * whose masses should be included in the returned value.
>    *
>    * @return The total mass of the models specified by @p model_ids.
> ```

Consider: `@returns` instead so it'd read as it does now the brief description. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-:-KNlkcBs4aWALo6CBLq7:-932369688)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. Here is how the generated Doxygen webpage looks:



Now waiting on CI.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 176 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-KNlkNURWZ-B5bgpi2TT:-KNlmBGqUo4d9FS9Nm0K:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1daba8dba23b0f616f910ca4d3e06b5b3756a614/drake/systems/plants/RigidBodyTree.h#L176)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Consider: "Computes the total mass of a set of models in this rigid body tree." so that it looks different from the return statement below.
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 181 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-KNlkWnMJusWXXkHjxXT:-KNlqQOOJXDJnIvxvNMM:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1daba8dba23b0f616f910ca4d3e06b5b3756a614/drake/systems/plants/RigidBodyTree.h#L181)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Consider: `@returns` instead so it'd read as it does now the brief description. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-:-KNlqT03JdbsyGCUbqj-:912371577)*

**Comment by liangfok** [comment]
Also waiting on @david-german-tri and @amcastro-tri to acknowledge a few threads.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-:-KNlqkQZSckDnJ7sbiPc:1374965397)*

**Comment by amcastro-tri** [comment]
Excellent! 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2938#-:-KNlsB4vd_KdNydXkjr2:-1097384816)*

**Comment by david-german-tri** [comment]
@jamiesnape @BetsyMcPhail looks like Jenkins may have stalled on this PR somehow?  There are a zillion idle executors, and it doesn't appear in the queue, so I'm not sure what's going on.

**Comment by david-german-tri** [comment]
@drake-jenkins-bot: retest this please

**Pull request merged**
