### PR TITLE
Adds ability to clone a RigidBodyFrame.

### PR DESCRIPTION
**Pull request by liangfok**
This goes towards #4897.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5041)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@ggould-tri for platform review please.

Thanks!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-:-Kc3J-2mt5d_ArDXe4g2:b-l3hat4)*

**Comment by ggould-tri** [comment]
:lgtm: pending one blocking comment below (also one optional nit).

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_frame.h, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc3XmM6KiF28B9o-o9G:-Kc3XmM6KiF28B9o-o9H:bth91he) ([raw file](https://github.com/robotlocomotion/drake/blob/98613bd1961c306317a937d2db4c2d7b87b8cfc8/drake/multibody/rigid_body_frame.h#L74)):*
> ```objc
>    * Returns a clone of this RigidBodyFrame. Note that the body to which this
>    * frame is attached is not cloned. The body must later be set using
>    * set_rigid_body().
> ```

I'm not sure I see the use in these semantics.  If the body is not cloned, the clone isn't really a valid `RigidBodyFrame` (that is, many of its methods will segfault).  If a new body is needed, shouldn't this take that body as an argument?  Alternatively if we mean to permit `RigidBodyFrame`s with null bodies, should that not be asserted in the methods that dereference or otherwise act on `body_`, and these nullness semantics documented?

---

*[drake/multibody/rigid_body_frame.h, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc3Wrxq2TkK6SJvAEZ4:-Kc3Wrxq2TkK6SJvAEZ5:b479yk4) ([raw file](https://github.com/robotlocomotion/drake/blob/98613bd1961c306317a937d2db4c2d7b87b8cfc8/drake/multibody/rigid_body_frame.h#L85)):*
> ```objc
>    * as this %RigidBodyFrame.
>    */
>   virtual bool CompareToClone(const RigidBodyFrame& other) const;
> ```

FYI -- `CompareToClone` is an odd name for a method that is just testing elementwise equality.  Consider `is_identical` or something similar?  This is not a defect as it stands, so feel free to ignore me on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-:-Kc3XS9aYrsBn94Zf53A:b-hbima6)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_frame.h, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc3Wrxq2TkK6SJvAEZ4:-Kc3_Wq-TkbZ10vaUWga:b5bcc0o) ([raw file](https://github.com/robotlocomotion/drake/blob/98613bd1961c306317a937d2db4c2d7b87b8cfc8/drake/multibody/rigid_body_frame.h#L85)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- `CompareToClone` is an odd name for a method that is just testing elementwise equality.  Consider `is_identical` or something similar?  This is not a defect as it stands, so feel free to ignore me on this.
</blockquote></details>

@amcastro-tri what do you think? Should I change all instances of `CompareToClone()` , like those in `RigidBody`, `DrakeJoint`, etc., to `is_identical()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_frame.h, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc3Wrxq2TkK6SJvAEZ4:-Kc3cGo_ZVZ0iXxGPiLa:b6x3bfc) ([raw file](https://github.com/robotlocomotion/drake/blob/98613bd1961c306317a937d2db4c2d7b87b8cfc8/drake/multibody/rigid_body_frame.h#L85)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

@amcastro-tri what do you think? Should I change all instances of `CompareToClone()` , like those in `RigidBody`, `DrakeJoint`, etc., to `is_identical()`?
</blockquote></details>

I was not aware that this was a common pattern; if it is, it is likely best to leave it as-is in this PR and make any comprehensive changes later/separately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. Now waiting on @amcastro-tri's review and CI.

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_frame.h, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc3XmM6KiF28B9o-o9G:-Kc3caIbtEhsWq9HGtUM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/98613bd1961c306317a937d2db4c2d7b87b8cfc8/drake/multibody/rigid_body_frame.h#L74)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I'm not sure I see the use in these semantics.  If the body is not cloned, the clone isn't really a valid `RigidBodyFrame` (that is, many of its methods will segfault).  If a new body is needed, shouldn't this take that body as an argument?  Alternatively if we mean to permit `RigidBodyFrame`s with null bodies, should that not be asserted in the methods that dereference or otherwise act on `body_`, and these nullness semantics documented?
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_frame.h, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc3Wrxq2TkK6SJvAEZ4:-Kc3cfHDNRUv3kOk_QDP:bf318t7) ([raw file](https://github.com/robotlocomotion/drake/blob/98613bd1961c306317a937d2db4c2d7b87b8cfc8/drake/multibody/rigid_body_frame.h#L85)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I was not aware that this was a common pattern; if it is, it is likely best to leave it as-is in this PR and make any comprehensive changes later/separately.
</blockquote></details>

SGTM. I will leave it as-is for now. FTR, the suggestion to use `CompareToClone` was first mentioned here: https://reviewable.io/reviews/robotlocomotion/drake/4982#-Kbq7LZxuGVoMx31_4v3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-:-Kc3dHt6ganGnv1kWCDb:b-9e1fe8)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041)*

**Comment by amcastro-tri** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/rigid_body_frame.cc, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4QN_JMB5jYh6pynrg:-Kc4QN_K07PYc-uzyn8X:b-njp3n5) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.cc#L54)):*
> ```cpp
>         "  - this: {}\n"
>         "  - other: {}",
>         get_rigid_body().get_name(),
> ```

BTW, A better way to compare would be to use `id`'s

---

*[drake/multibody/rigid_body_frame.cc, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4QULRYfUELVSduXTJ:-Kc4QULRYfUELVSduXTK:b-2gk78t) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.cc#L58)):*
> ```cpp
>     return false;
>   }
>   if (get_rigid_body().get_model_instance_id() !=
> ```

Not needed if the body has the same id.

---

*[drake/multibody/rigid_body_frame.h, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc3Wrxq2TkK6SJvAEZ4:-Kc4PRlkuOrHq_L_k_6m:b-w1724g) ([raw file](https://github.com/robotlocomotion/drake/blob/98613bd1961c306317a937d2db4c2d7b87b8cfc8/drake/multibody/rigid_body_frame.h#L85)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

SGTM. I will leave it as-is for now. FTR, the suggestion to use `CompareToClone` was first mentioned here: https://reviewable.io/reviews/robotlocomotion/drake/4982#-Kbq7LZxuGVoMx31_4v3.
</blockquote></details>

`is_identical` SGTM if you feel strong about it. I personally don't like the `is_identical()` flavor since actually they are not, they both contain pointers to different things for instance. That is why I suggested (maybe a bad idea?) the name `CompareToClone()`

---

*[drake/multibody/rigid_body_frame.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4OwJeQUrkm6pAcmsk:-Kc4OwJeQUrkm6pAcmsl:b-25ojc3) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.h#L77)):*
> ```objc
>    * This pointer must remain valid for the duration of the clone's lifetime.
>    */
>   virtual std::shared_ptr<RigidBodyFrame<T>> Clone(RigidBody<T>* body) const;
> ```

BTW, this is odd. I don't think I've ever seen a `Clone()` method with arguments. 
If you need to change something it is no longer a `Clone()`. For `RigidBody` you left the joint pointer uninitialized. Couldn't you do the same here for the body pointer? 

---

*[drake/multibody/rigid_body_frame.h, line 86 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4NxxFdczQpDSJsYIK:-Kc4NxxFdczQpDSJsYIL:b-8xo19j) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.h#L86)):*
> ```objc
>    * as this %RigidBodyFrame.
>    */
>   virtual bool CompareToClone(const RigidBodyFrame& other) const;
> ```

virtual?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/rigid_body_frame.cc, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4QN_JMB5jYh6pynrg:-Kc4SDMYrILJV6hpC4iU:b-n6im9c) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.cc#L54)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, A better way to compare would be to use `id`'s
</blockquote></details>

Do you mean index as in `RigidBody::get_body_index()`?

---

*[drake/multibody/rigid_body_frame.cc, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4QULRYfUELVSduXTJ:-Kc4SGiq-015SZT89nWr:b7b74k9) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.cc#L58)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Not needed if the body has the same id.
</blockquote></details>

Ditto regarding `index` instead of `id`?

---

*[drake/multibody/rigid_body_frame.h, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc3Wrxq2TkK6SJvAEZ4:-Kc4SmqRmR4s1RLXMKNy:byohx8w) ([raw file](https://github.com/robotlocomotion/drake/blob/98613bd1961c306317a937d2db4c2d7b87b8cfc8/drake/multibody/rigid_body_frame.h#L85)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`is_identical` SGTM if you feel strong about it. I personally don't like the `is_identical()` flavor since actually they are not, they both contain pointers to different things for instance. That is why I suggested (maybe a bad idea?) the name `CompareToClone()`
</blockquote></details>

OK I'll keep it `CompareToClone()` for now.

---

*[drake/multibody/rigid_body_frame.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4OwJeQUrkm6pAcmsk:-Kc4SNhjwdtPQhYCUmBo:b4u4sdc) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.h#L77)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, this is odd. I don't think I've ever seen a `Clone()` method with arguments. 
If you need to change something it is no longer a `Clone()`. For `RigidBody` you left the joint pointer uninitialized. Couldn't you do the same here for the body pointer? 

</blockquote></details>

This was done based on @ggould-tri's comment here:

https://reviewable.io/reviews/RobotLocomotion/drake/5041#-Kc3XmM6KiF28B9o-o9G

By passing in the `RigidBody<T>*`, we guarantee that the returned `RigidBodyFrame` is fully initialized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/rigid_body_frame.cc, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4QN_JMB5jYh6pynrg:-Kc4VK5ji-uTRjljHtw5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.cc#L54)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Do you mean index as in `RigidBody::get_body_index()`?
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_frame.cc, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4QULRYfUELVSduXTJ:-Kc4VKaWKJYdmaybFmNs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.cc#L58)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Ditto regarding `index` instead of `id`?
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_frame.h, line 86 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4NxxFdczQpDSJsYIK:-Kc4T-43_hFQuglUrp1x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.h#L86)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

virtual?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-:-Kc4VN3xugRrgRxwRBzk:b-1edt96)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/rigid_body_frame.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4OwJeQUrkm6pAcmsk:-Kc4YqSmeTvRPeiDFDB8:b-iyacjb) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.h#L77)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This was done based on @ggould-tri's comment here:

https://reviewable.io/reviews/RobotLocomotion/drake/5041#-Kc3XmM6KiF28B9o-o9G

By passing in the `RigidBody<T>*`, we guarantee that the returned `RigidBodyFrame` is fully initialized.
</blockquote></details>

@amcastro-tri The alternative would be for methods that require a `body_` to document and assert on the uninitialized behaviour.  But returning an object that is not valid for its own methods would not be a reasonable outcome.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_frame.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-Kc4OwJeQUrkm6pAcmsk:-Kc4uQCgvQ35dL7YxHxK:buzfu7r) ([raw file](https://github.com/robotlocomotion/drake/blob/781ea7180267cabd5b260fb727e7ef4e4a3fe1c8/drake/multibody/rigid_body_frame.h#L77)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

@amcastro-tri The alternative would be for methods that require a `body_` to document and assert on the uninitialized behaviour.  But returning an object that is not valid for its own methods would not be a reasonable outcome.
</blockquote></details>

I was just curious on how that looked. I realize fixing this is not part of this PR. I'll mark myself satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5041#-:-Kc4uhxryiDZFNxjOpGM:bnfp4nl)*

**Pull request merged**
