### PR TITLE
Changes for ROS builds in CI.

### PR DESCRIPTION
**Pull request by jhoare**
Fix for build errors encountered for ROS CI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2855)

### CODE REVIEW

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ros/drake_ros_systems/include/drake_ros/ros_sensor_publisher_joint_state.h, line 292 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2855#-KN7qRzf96NaDSJ1Vkic:-KN7qRzf96NaDSJ1Vkid:1944674899) ([raw file](https://github.com/robotlocomotion/drake/blob/cc81ce218846046ef3233cc49c7aac87ca7a4907/ros/drake_ros_systems/include/drake_ros/ros_sensor_publisher_joint_state.h#L292)):*
> ```objc
>               rigid_body_tree->FindBodyIndex(rigid_body->name()));
>           auto translation = transform.translation();
>           auto rpy = drake::math::rotmat2rpy(transform.linear());
> ```

BTW, I wonder how this worked on my local PC. Is CI somehow different?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2855)*

**Comment by jamiesnape** [comment]
Ignore the "default" and "continuous-integration/jenkins/pr/mac" builds.

**Comment by jhoare** [comment]
Had the first ROS CI Build succeed, need to still make some improvements on how it is being sent to CDash. 

https://drake-jenkins.csail.mit.edu/view/ROS/job/linux-gcc-experimental-ros/11/

**Comment by liangfok** [comment]
I just tried setting up ROS / Drake on someone else's computer and ran into the `rotmat2rpy` issue that's fixed by this PR. I switched to this PR and verified that the changes in this PR fixed the problem. Thus, :lgtm_strong: .

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2855#-:-KN9CUz1KUXJ0XxV5TX2:-869906900)*

**Comment by jhoare** [comment]
In that case, there's no reason why we can't merge this. 
+@david-german-tri

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2826/ and is thus ready for platform review. Since today's Friday, -@david-german-tri and +@ggould-tri for platform review. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2855#-:-KNGx1h2Kpjv6irMBXvF:706056427)*

**Comment by ggould-tri** [comment]
Trivial change obviously correct. :lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2855#-:-KNHWZRefYIfRzo9eFD5:1573006552)*

**Pull request merged**
