### PR TITLE
Update DrakeShapes::Element and DrakeCollsion::Element copy

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Rewrite the Collision copy constructor to be defaulted, the Shapes copy constructor with a TODO comment, and delete the stuff that is broken and we don't want.

There are a whole bunch more Shapes and Geometry copy/clone implementations that are broken, but this PR doesn't fix them (nor do I plan to in the future).  This PR is at least one example of work-arounds that others could apply to that code when they care.

A portion of #4861.  Relates #5252.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5253)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@seancurtis-tri for feature review, please.
/CC @amcastro-tri FYI.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5253#-:-KdYUFc0nQlZyUoc2E7F:b4pxvhd)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5253#-:-KdaRWDnjThKRlEmBdWt:bmxilld)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5253#-:-KdaS25v7jNT4N4wjqcg:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5253#-:-KdaW1CxVS-z-8RQiAmO:bnfp4nl)*

**Pull request merged**
