### PR TITLE
Work around incompatibilities between Eigen <= 3.3.7 and Apple LLVM 11.0.0

### LINKED ISSUE #12107: Bus error / abort trap related to Eigen usage under Xcode 11
Appears to be in release configuration only. One such failure relates to this line: https://github.com/RobotLocomotion/drake/blob/7d672344d45d8badd94b5bc76a47b138532c7bba/math/continuous_algebraic_riccati_equation.cc#L24

```
)$ clang -v
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ bazel test //math:continuous_algebraic_riccati_equation_test

FAIL: //math:continuous_algebraic_riccati_equation_test (see /private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/execroot/drake/bazel-out/darwin-py2-opt/testlogs/math/continuous_algebraic_riccati_equation_test/test.log)
INFO: From Testing //math:continuous_algebraic_riccati_equation_test:
==================== Test output for //math:continuous_algebraic_riccati_equation_test:
Using drake_cc_googletest_main.cc

[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from CARE
[ RUN      ] CARE.TestCare
external/bazel_tools/tools/test/test-setup.sh: line 310: 12507 Bus error: 10           "${TEST_PATH}" "$@" 2>&1
================================================================================
```

Apparently still an issue using Eigen 3.3.7, but may be fixed in `tip`. CC #11758.

Blocks macOS Catalina support. CC #11692.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #12107 (I guess).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12133)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please

**Comment by soonho-tri** [comment]
I've tested it locally on a mac with XCode11.0.

**Comment by soonho-tri** [comment]
Separately, I've tried to reproduce the problem in Ubuntu by using different versions of compilers (gcc/clang) with different options (-fstack-check, -fstack-protector, etc). But so far I have no luck.

**Comment by jamiesnape** [comment]
High Sierra failures are lint timeouts.

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Pull request merged**
