### PR TITLE
Export transitive dependencies, use new install framework

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify Drake's CPS to properly export its transitive dependencies (so e.g. users no longer need to find and "link" to Eigen). Update/rewrite `package_drake.sh` to use the new install framework.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6205)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPx0dtIrfUizKUTAf1:-KlPx0du2M_UYV-V0uRI:baifzyu) (no related file):*
First pass complete, but I want to test locally before LGTM.  I'll wait for the next push before I do that, though.

---

*[tools/package_drake.sh, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPuxWv9kNyjplZTH1F:-KlPuxWwu4cTRKjrRRzH:b-r10z02) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/tools/package_drake.sh#L36)):*
> ```Shell
> done
> shift $((OPTIND - 1))
> [ -z "$output_tarfile" ] && output_tarfile="$1"
> ```

I don't see how this line makes sense given the `output_tarfile="$1"` default already enacted a ~dozen lines prior.

---

*[tools/package_drake.sh, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPvFCDG1gVsTmxnDBw:-KlPvFCDG1gVsTmxnDBx:bl08mr2) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/tools/package_drake.sh#L39)):*
> ```Shell
> 
> # Test that an output tar file name was given.
> if [ -z "$output_tarfile" ]; then
> ```

I'm not sure how this can ever be true, given the `-z` check 3 lines prior.

---

*[tools/package_drake.sh, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPwMvvEWBhIEIq1WBh:-KlPwMvvEWBhIEIq1WBi:b-vng29z) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/tools/package_drake.sh#L67)):*
> ```Shell
> # Create tar file.
> cd "$tmpdir"
> tar -czf "$output_tarfile" *
> ```

I think relying so much on `cwd` being a particular thing makes this script difficult to read.  Could the above two lines be combined into a subshell as `( cd "$tmpdir" && tar -czf "$output_tarfile" *)`?  At which point the `cd "$workspace"` below can also go away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[WORKSPACE, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPxzJFVboDnjyqf7ac:-KlPxzJFVboDnjyqf7ad:blj2kgi) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/WORKSPACE#L303)):*
> ```Python
>     name = "pycps",
>     repository = "mwoehlke/pycps",
>     commit = "1c806dcecabbc877c7bf80c3565643169968a4e8",
> ```

Wouldn't it make sense to bump to the latest revision (d68a10ce1130f87d38a13ae42ddb263042e2352a) that also suppose definitions? That would avoid to have a second PR that takes care of that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPx0dtIrfUizKUTAf1:-KlPyFDYhUHvD3Ijr6Fj:bb6ywmx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

First pass complete, but I want to test locally before LGTM.  I'll wait for the next push before I do that, though.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[WORKSPACE, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPxzJFVboDnjyqf7ac:-KlPyo-yPvBIJBTrs_Rn:b-41f7s5) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/WORKSPACE#L303)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Wouldn't it make sense to bump to the latest revision (d68a10ce1130f87d38a13ae42ddb263042e2352a) that also suppose definitions? That would avoid to have a second PR that takes care of that.
</blockquote></details>

I'd somewhat like to hold off; @jamiesnape is going to have a PR that needs that revision anyway, so it makes sense to do it there (this PR doesn't need that SHA), and given that SHA didn't exist until very recently due to finding a bug, I'd prefer to not point at an untested and possibly broken (and thus, subject to disappearing) SHA.

---

*[tools/package_drake.sh, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPuxWv9kNyjplZTH1F:-KlPxRzjO2k9ZVwb2rRz:b-2790tb) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/tools/package_drake.sh#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't see how this line makes sense given the `output_tarfile="$1"` default already enacted a ~dozen lines prior.
</blockquote></details>

Oh... because L25 is wrong (see also next comment); I'd started to rip out the option handling entirely, then changed my mind. L25 should be setting it to empty. This should set it to the positional argument if `-f` was not given (thus restoring the pre-#5941 behavior `package_drake.sh FILE.tar.gz`).

---

*[tools/package_drake.sh, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPvFCDG1gVsTmxnDBw:-KlPy5R8L4hSpw-bywk3:b-8i64wz) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/tools/package_drake.sh#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure how this can ever be true, given the `-z` check 3 lines prior.
</blockquote></details>

```
$ tools/package_drake.sh 
tools/package_drake.sh: line 25: $1: unbound variable
```

Um. Right... well, it's *supposed* to get here...

---

*[tools/package_drake.sh, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPwMvvEWBhIEIq1WBh:-KlPyeowGxaSMC5iF5Ng:b-3j89jx) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/tools/package_drake.sh#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think relying so much on `cwd` being a particular thing makes this script difficult to read.  Could the above two lines be combined into a subshell as `( cd "$tmpdir" && tar -czf "$output_tarfile" *)`?  At which point the `cd "$workspace"` below can also go away.
</blockquote></details>

I suppose... the second one is only really needed for "don't remove the current directory", though; it could `cd /` just as easily.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by jwnimmer-tri** [comment]
*[WORKSPACE, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPxzJFVboDnjyqf7ac:-KlQ-2YplS-P_TzpQrg4:b-lnk8ez) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/WORKSPACE#L303)):*
(FTR I'm fine with using this commit, but...)

> ...  subject to disappearing) SHA.

This part confused me.  The `d68a...` commit is on pycps master, how could it disappear?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by fbudin69500** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[WORKSPACE, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPxzJFVboDnjyqf7ac:-KlQ0028fuyWSyobFp2a:b-8ds5d3) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/WORKSPACE#L303)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(FTR I'm fine with using this commit, but...)

> ...  subject to disappearing) SHA.

This part confused me.  The `d68a...` commit is on pycps master, how could it disappear?
</blockquote></details>

Ok. I also have a PR that will require the update of pycps. I will just wait for @jamiesnape to merge his PR before I rebase and push mine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by fbudin69500** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPx0dtIrfUizKUTAf1:-KlQ0N1q7EnuiE8sztHt:bg7igkv) (no related file):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by fbudin69500** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[WORKSPACE, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPxzJFVboDnjyqf7ac:-KlQ-myqsc5PHelCHerK:b76typ7) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/WORKSPACE#L303)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Ok. I also have a PR that will require the update of pycps. I will just wait for @jamiesnape to merge his PR before I rebase and push mine.
</blockquote></details>

...because I've been known to rewrite PyCPS history when recent changes have bugs. Until recently, `master` was ddcfb4a27f8344ce4bfbe735edd12fd094e0a7e8; that SHA no longer exists unless you'd fetched it locally and it hasn't yet been garbage collected. If there is another bug in the `Definitions` handling, that could happen again.

Obviously, I would be less willing to rewrite history being referenced by Drake in the main repo, but that isn't yet true for d68a10ce1130f87d38a13ae42ddb263042e2352a.

If someone has a PR that needs `Definitions` support that can reasonably show that the feature is working, I have no objection to merging that PR first (then this one won't need to change the PyCPS SHA at all).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by jwnimmer-tri** [comment]
*[WORKSPACE, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPxzJFVboDnjyqf7ac:-KlQ0pth4Y05VPU6yFA0:bjinhwj) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/WORKSPACE#L303)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...because I've been known to rewrite PyCPS history when recent changes have bugs. Until recently, `master` was ddcfb4a27f8344ce4bfbe735edd12fd094e0a7e8; that SHA no longer exists unless you'd fetched it locally and it hasn't yet been garbage collected. If there is another bug in the `Definitions` handling, that could happen again.

Obviously, I would be less willing to rewrite history being referenced by Drake in the main repo, but that isn't yet true for d68a10ce1130f87d38a13ae42ddb263042e2352a.

If someone has a PR that needs `Definitions` support that can reasonably show that the feature is working, I have no objection to merging that PR first (then this one won't need to change the PyCPS SHA at all).
</blockquote></details>

The Drake platform reviewers rely a commit being on a `master` branch as sufficient evidence that the commit will persist forever, so that bisecting the Drake build will be effective.  Is there a way we can reduce the possibility of that reasoning being in error, either by agreeing never to force-push to pycps master, or by setting up some way to record the required revisions, such as a tag that moves and gates Drake's ability to use the tree?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPx0dtIrfUizKUTAf1:-KlQ2Sg5bpw-8v_oA-h2:b-40ckl5) (no related file):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

@fbudin69500 FYI you posted the LGTM(s) to the wrong discussion thread.  (This is a not-unusual failure more for new Reviewable users.)  Note the "Review discussion" box above, versus this PR-wide discussion "In progress".  Doing so doesn't break any review interlocks or anything, but is merely confusing to others.

I will test this PR shortly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPx0dtIrfUizKUTAf1:-KlQ3Ult4iunitzfrXWD:b513ky0) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@fbudin69500 FYI you posted the LGTM(s) to the wrong discussion thread.  (This is a not-unusual failure more for new Reviewable users.)  Note the "Review discussion" box above, versus this PR-wide discussion "In progress".  Doing so doesn't break any review interlocks or anything, but is merely confusing to others.

I will test this PR shortly.
</blockquote></details>

Thanks for the info.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPxzJFVboDnjyqf7ac:-KlQ6uWsVNJp7lK_hAyk:begc2sf) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/WORKSPACE#L303)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The Drake platform reviewers rely a commit being on a `master` branch as sufficient evidence that the commit will persist forever, so that bisecting the Drake build will be effective.  Is there a way we can reduce the possibility of that reasoning being in error, either by agreeing never to force-push to pycps master, or by setting up some way to record the required revisions, such as a tag that moves and gates Drake's ability to use the tree?
</blockquote></details>

For now, I think full branching would be overkill for PyCPS, but I can try to remember to push not-yet-"verified" stuff to some other branch, which simply becomes `master` later.

I don't think other approaches will work, since in order to test, Drake needs to locally refer to something that has already been pushed. (I'll repeat again my *intent*, which is that once the upstream Drake repo references a SHA, that SHA is "permanent". That is expected to be sufficient that bisecting will work, as long as PR's are cleaned up to not refer to non-existing SHA's before being merged. Note that the latter is required in any case.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by jwnimmer-tri** [comment]
*[WORKSPACE, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlPxzJFVboDnjyqf7ac:-KlQ8mibr0q_zIHYCoP2:b286skv) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2773b0205131a7934e5211aa1af89246b8bd25/WORKSPACE#L303)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

For now, I think full branching would be overkill for PyCPS, but I can try to remember to push not-yet-"verified" stuff to some other branch, which simply becomes `master` later.

I don't think other approaches will work, since in order to test, Drake needs to locally refer to something that has already been pushed. (I'll repeat again my *intent*, which is that once the upstream Drake repo references a SHA, that SHA is "permanent". That is expected to be sufficient that bisecting will work, as long as PR's are cleaned up to not refer to non-existing SHA's before being merged. Note that the latter is required in any case.)
</blockquote></details>

For workstation testing, you can use `local_repository_override` and not need to push commits at all.  For CI testing, citing a non-`master` branch in `WORKSPACE` is okay prior to asking for platform LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/package_drake.sh, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlQF1WIDd8D0ROgoH4s:-KlQF1WJ5byQXysD5cDf:b-xk04jt) ([raw file](https://github.com/robotlocomotion/drake/blob/8e90d081a15a33feb9cfd2cab4aedfc3a2da2b34/tools/package_drake.sh#L62)):*
> ```Shell
> tmpdir=$(mktemp -d)
> # Build Drake.
> bazel run install -- "$tmpdir"
> ```

This command produces lots of output (`[Installing] include/...`).  Could it be guarded by some kind of verbosity flag, off by default?  (Whether the mute is at the call site here, or built into `:install` itself, I don't care either way.  Whether its the same `-v` as induces the `set -x` above or not, I don't care either way.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-:-KlQEBd2YA6XhoXX0RBP:bnfp4nl)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-:-KlQMT013TWNj5SUmVGt:bnfp4nl)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-:-KlQShSev0bfKjfl3aF_:bnfp4nl)*

**Comment by fbudin69500** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/package_drake.sh, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6205#-KlQF1WIDd8D0ROgoH4s:-KlTjG2c6t-FBcLqZJR5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e90d081a15a33feb9cfd2cab4aedfc3a2da2b34/tools/package_drake.sh#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This command produces lots of output (`[Installing] include/...`).  Could it be guarded by some kind of verbosity flag, off by default?  (Whether the mute is at the call site here, or built into `:install` itself, I don't care either way.  Whether its the same `-v` as induces the `set -x` above or not, I don't care either way.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6205)*

**Pull request merged**
