### PR TITLE
Bump io_bazel_rules_go to 0.4.4

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6111)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jamiesnape , feature-review please.
+@jwnimmer-tri , platform-review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6111#-:-KkGm_NPxmlR1LFhyCoO:bv4s6sw)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6111#-:-KkGtjwy1NTgd_3VKRef:bnfp4nl)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6111#-:-KkGtzPF9x3COIUzD5av:bnfp4nl)*

**Comment by jamiesnape** [comment]
All Bazel passed, overriding the CMake flake.

**Pull request merged**
