### PR TITLE
Stop uploading local test results to CDash

### LINKED ISSUE #2279: The 'make test' target should not upload user data to the web
The `drake-distro/drake/Makefile`'s `make test` target should not upload user data to the web by default (https://drake-cdash.csail.mit.edu/index.php?project=Drake).  It is mean to take users' test result data and publish it for all to see without their consent.

### PR DESCRIPTION
**Pull request by david-german-tri**
Resolves #2279

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2282) &emsp; Multiple assignees:&emsp;@jamiesnape&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jamiesnape">jamiesnape</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>

### CODE REVIEW

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/Makefile, line 61 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2282#-KH1kejpF8JTvpteDxkO:-KH1kejpF8JTvpteDxkP:-334218926) ([raw file](https://github.com/robotlocomotion/drake/blob/ccd91d16406822d25058b62b4eb11d6e06b5ead0/drake/Makefile#L61)):*
Aside: In an ideal world we would not be specifying a global timeout here at all. Then again, we also would not have this hand-coded Makefile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2282)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2282#-:-KH1lLV56U-Og1LF_xrf:1417088721)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2282#-:-KH1rsBgoOl-tFinXAAu:1417088721)*

**Comment by sherm1** [comment]
Does this also stop CI from uploading test results?

**Comment by jwnimmer-tri** [comment]
I'm pretty sure that CI never runs this `Makefile`, under any conditions :sob:.  The upshot, though, is at least this PR shouldn't disturb anything.

**Comment by jwnimmer-tri** [comment]
The only jenkins error was #2257, so I'm going to use override-merge.

**Comment by jamiesnape** [comment]
CI indeed never runs the tests target, although the script driving the CI basically does the same thing. The differences are smaller than you would imagine. The CDash uploads here were incomplete anyway, so I doubt anyone will miss this.

**Pull request merged**
