### PR TITLE
Teach `find_resource` to use `libdrake_marker.so` in lieu of `libdrake.so`; remove `drake_example_cc_library`;

### LINKED ISSUE #8908: `//examples/kuka_iiwa_arm:kuka_simulation` violates ODR due to `:iiwa_common` and `:iiwa_lcm`
At present, `iiwa_common` and `iiwa_lcm` depend on static libraries within Drake (e.g. `//multibody:rigid_body_tree`), but `kuka_simulation` also links against `libdrake.so` via `drake_example_cc_binary`.

In drafting #8906, I realized this when digging into an issue captured by the following comments:
https://github.com/EricCousineau-TRI/drake/blob/59d9d37d8d6a5fb427b5872a8d85ed03698e756e/tools/skylark/drake_cc.bzl#L611-L617

With @sammy-tri's help, we found that when the example binary has `srcs = ["//tools/install/libdrake:libdrake.so", ...]`, Bazel or the linker somehow magically realize that there are some duplications in the object code, and culls duplicate code from the resultant binary `kuka_simulation`.

To see the symbols:
```
objdump --all-headers -T -R bazel-bin/examples/kuka_iiwa_arm/kuka_simulation_test | c++filt | less
```

However, when moving `libdrake.so` to be in `drake_shared_library`'s `srcs`, it seems that Bazel or the linker do not catch this case, and ends up duplicating globals such as `std::set<int> RigidBodyTreeConstants::default_model_instance_id_set` (which is a GSG violation, as it is not trivially destructible).
This manifests itself when the binary is running its exit handlers, and it ends up double-freeing memory within `default_model_instance_id_set`.

Potential solutions:
- Avoid ODR violations, and somehow ensure that `iiwa_common` and `iiwa_lcm` do not double-declare their dependencies.
- Change `default_model_instance_id_set` to `never_destroyed<>` as a stop-gap. This should be done regardless, but won't solve the issue since there will be other violations.

Ultimately, this seems to be pointing towards the pains of trying to offer both static and dynamically linked libraries from Bazel without a concrete plan (that I know of?) for offering both types of targets at the same level of granularity and with compatibility. (Bazel has [plans](https://docs.google.com/document/d/1d4SPgVX-OTCiEK_l24DNWiFlT14XS5ZxD7XhttFbvrI/edit#heading=h.jwrigiapdkr2) for doing this hopefully well, but it seems to be stalled at the moment.)

@fbudin69500 This was the issue that we had discussed earlier, which we weren't sure if it was due to `FindResource` logic or not. This tends to indicate that it is not.

@jwnimmer-tri @jamiesnape Can I ask if y'all know what linker or Bazel magic is presently preventing this from being a problem on the current `master`?

EDIT: Reproduction commit:
https://github.com/EricCousineau-TRI/drake/commit/cf555031b73cb49867c4f7cb27d715a360825911

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8908 

While it would be ideal to have `find_resource` be its own library and ultimately carve up shared libraries, this is a relatively quick solution to the above issue.

\cc @jwnimmer-tri @fbudin69500 @jamiesnape 

Tested on RobotLocomotion/drake-shambhala@af8d27e

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@fbudin69500 for feature review, please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909#-:-LDs0t_N3pnrnL_YHxj5:b-7ky81)*

**Comment by fbudin69500** [comment]
While this solution seems to solve an important problem, it would be good it the commit message explicitly stated why this PR does not implement the other suggested solution: an independent library for `libdrake_find_resource.so` ro something like this. I think I tried that in the past and I ran into linking issues with GFLAGS, but I don't recall exactly.

My concern about this patch: If the flag `--as-needed` is used when compiling a project downstream, when the project is not compiled in debug, I am worried that the new "empty" library `libdrake_marker.so` will not be linked, and that  will create issues. I haven't tested this locally yet, but I will create a small example to test this hypothesis.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909#-:-LEA-w8nE5iAcDG2QqD3:b-6adrog)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for platform review (and secondary feature review).

> ... I am worried that the new "empty" library libdrake_marker.so will not be linked, ...

Why wouldn't it be?  It provides a public function symbol that is required by find_resource.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8909#-LEA0ePo9E1N7qxRj2el:-LEA0ePp-qltiOjzVj6z:b-sz33ml) (no related file):*
Needs macOS CI testing.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8909#-LEA0phiEdVfJaz34zCt:-LEA0phiEdVfJaz34zCu:b-d2sj4j) (no related file):*
I need to double-check locally that the installed demo(s) still function correctly (though the CI testing _should_ be authoritative now).

---

*[common/drake_marker.cc, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8909#-LEA1WIj1yPSUE7veGwO:-LEA1WIj1yPSUE7veGwP:b-suge9l) ([raw file](https://github.com/robotlocomotion/drake/blob/84b792ed100e7fb2223f038b25a1407e06299069/common/drake_marker.cc#L1)):*
> ```cpp
> namespace drake {
> ```

This should include the header file, so that the function signature is forward-declared (and checked to match).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909#-:-LEA0gFw7hR_ZHE6e1dN:b2ppz9l)*

**Comment by fbudin69500** [comment]
The only place where I saw the public function called was in the DRAKE_DEMAND macro call which I thought was basically an `assert()` call, and therefore only included in debug. Am I incorrect?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909#-:-LEA5cdu9Wn7MuNVntwX:b835c1b)*

**Comment by EricCousineau-TRI** [comment]
Actually, `DRAKE_DEMAND` will always compile (even in release mode); `DRAKE_ASSERT` only compiles in debug mode.

(In reading the docs for `drake_assert.h`, I realize this is not stated explicitly, but `DRAKE_ASSERT_IS_ARMED` implies that `DRAKE_ASSERT` will redirect to `DRAKE_DEMAND`.)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909#-:-LEA9Tlr3q8mkH7__uzH:b9l9ymg)*

**Comment by EricCousineau-TRI** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8909#-LEACY1-2Kd_OK0g5tcC:-LEACY10-JS7VCJA5C8R:b-dw5r40) (no related file):*
@fbudin69500 I have updated the commit message. Can you resolve this discussion if it meets your criteria?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909#-:-LEADXdt6OYKUG9aXool:bnfp4nl)*

**Comment by fbudin69500** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8909#-LEACY1-2Kd_OK0g5tcC:-LEAEjQz66_OwpymlEJl:bb6ywmx) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@fbudin69500 I have updated the commit message. Can you resolve this discussion if it meets your criteria?
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[common/drake_marker.h, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8909#-LEAHbFi90WhW41bVca8:-LEAHbFi90WhW41bVca9:b-o163mt) ([raw file](https://github.com/robotlocomotion/drake/blob/b36747f8c37e5874b9ece107d12050ab955a3f6b/common/drake_marker.h#L1)):*
> ```objc
> /// @file
> ```

Missing pragma-once.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909)*

**Comment by EricCousineau-TRI** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/drake_marker.h, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8909#-LEAHbFi90WhW41bVca8:-LEATOzPBycMeHildWVJ:b-r08yfo) ([raw file](https://github.com/robotlocomotion/drake/blob/b36747f8c37e5874b9ece107d12050ab955a3f6b/common/drake_marker.h#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing pragma-once.
</blockquote></details>

Done. D'oh!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909)*

**Comment by EricCousineau-TRI** [comment]
Prior Mac CI testing should effectively be the same:
https://drake-jenkins.csail.mit.edu/job/mac-highsierra-clang-bazel-experimental/141/
https://drake-jenkins.csail.mit.edu/job/mac-sierra-clang-bazel-experimental/131/

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8909#-LEA0phiEdVfJaz34zCt:-LEAWUJ85qbyaZNeRw-A:b-lls6x7) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I need to double-check locally that the installed demo(s) still function correctly (though the CI testing _should_ be authoritative now).
</blockquote></details>

I tested both resource_tool and kuka_simulation and they passed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909#-:-LEAWYgG3zpTLsYp1Mh_:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8909#-LEA0ePo9E1N7qxRj2el:-LEAyGrY3cy1DqIJ7SqG:b-dhf3ry) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs macOS CI testing.
</blockquote></details>

Done (via the links posted). The only change between `r2` and `r3` was the `#pragma once`, which has been tested by the Ubuntu flavored CI.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8909)*

**Pull request merged**
