### PR TITLE
Add python binding for ReplaceBilinearTerms

### PR DESCRIPTION
**Pull request by hongkai-dai**
As requested in stackoverflow https://stackoverflow.com/questions/72823452/how-to-use-callback-functions-of-gurobi-in-drake/72831395?noredirect=1#comment129374867_72831395

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for review, could you take a look at this PR? I have two thoughts
1. I now feel the function `ReplaceBilinearTerms` should belong to `common/symbolic` folder, instead of `solvers` folder, as this function just manipulate symbolic expressions. WDYT? If we want to move this to `common/symbolic` folder, how should I deprecate this function? Do I add a deprecation message saying that we will deprecate it in 3 months, and for the moment I add `ReplaceBilinearTerms` function in `common/symbolic` folder, and add its python binding in `symbolic_py.cc`?
2. If we think this function should continue to live in `solvers` folder, could you make sure that adding a new file `solvers_py_bilinear_product_util` is the right thing? Also I didn't add the submodule like `pydrake.solvers.mathematicalprogram`, but this function is added to `solvers` module directly as `pydrake.solvers.ReplaceBilinearTerms`. Is this the right thing to do?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707#-:-N90Ba5n3gFBYtAFDnFH:b-avgc6b)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> (1) I now feel the function ReplaceBilinearTerms should belong to common/symbolic folder, instead of solvers folder, as this function just manipulate symbolic expressions. WDYT?

I think it's a fine proposal.  We could say that code that only manipulates symbolic expressions can live in `common/symbolic`, while the actual Cost and Constraint objects live in `solvers`.

> If we want to move this to common/symbolic folder, how should I deprecate this function?

It's a simple, one-PR process:

(a) Copy the files to `common/symbolic`, including the unit test.
(b) Change the `solvers/bilinear_product_util.cc` to just call into the common function.
(c) Change the `solvers/bilinear_product_util.h` to add `DRAKE_DEPRECATED`.

When moving the files to common, avoid using the semantically meaningless filename `util`.  The file could be named `replace_bilinear_terms.h`, for example.

**Review by hongkai-dai — COMMENTED** [review]
Done. I moved the code to `common/symbolic` and deprecate `solvers::ReplaceBilinearTerms`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707#-:-N984wrwCieSi27z6AvX:br5ggap)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707#-:-N98EsxL6VKHqxkcWVCo:bnfp4nl)* status: 4 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`bindings/pydrake/symbolic_py.cc` line 1133 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17707#-N98Ej3695RG-EwXMLUX:-N98Ej3695RG-EwXMLUY:b-556jr9) ([raw file](https://github.com/robotlocomotion/drake/blob/3e3e3539f4b24901d236f416fefd4e662694776d/bindings/pydrake/symbolic_py.cc#L1133)):*
> ```cpp
>           doc.DecomposeLumpedParameters.doc);
> 
>   // Bind free function in replace_bilinear_terms
> ```

nit Missing period at end of sentence.
___
*[`common/symbolic/replace_bilinear_terms.cc` line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17707#-N98EMBjCwsgrC-LFYMZ:-N98EMBjCwsgrC-LFYM_:b-k7ky73) ([raw file](https://github.com/robotlocomotion/drake/blob/3e3e3539f4b24901d236f416fefd4e662694776d/common/symbolic/replace_bilinear_terms.cc#L19)):*
> ```cpp
> using symbolic::Monomial;
> using symbolic::Variable;
> using symbolic::Variables;
> ```

nit These "using" from `symbolic::` are no-ops now.
___
*[`common/symbolic/test/replace_bilinear_terms_test.cc` line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17707#-N98EWDHEjzeJtyXdpmC:-N98EWDHEjzeJtyXdpmD:bfhfd6m) ([raw file](https://github.com/robotlocomotion/drake/blob/3e3e3539f4b24901d236f416fefd4e662694776d/common/symbolic/test/replace_bilinear_terms_test.cc#L7)):*
> ```cpp
> #include "drake/common/test_utilities/symbolic_test_util.h"
> 
> using drake::symbolic::Variable;
> ```

nit This using from `symbolic::` is not necessary now.
___
*[`common/symbolic/test/replace_bilinear_terms_test.cc` line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17707#-N98E_cbD6T6oA2yH_uo:-N98E_cbD6T6oA2yH_up:b-bpvres) ([raw file](https://github.com/robotlocomotion/drake/blob/3e3e3539f4b24901d236f416fefd4e662694776d/common/symbolic/test/replace_bilinear_terms_test.cc#L50)):*
> ```cpp
>   Vector3<symbolic::Variable> x_;
>   Vector4<symbolic::Variable> y_;
>   Vector2<symbolic::Variable> z_;
> ```

nit Unnecessary `symbolic::` qualifier; ditto throughout.

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for Thursday's platform review please, thanks!

The file `replace_bilinear_terms.h/cc` and `replace_bilinear_terms_test.cc` are directly copied from the existing `bilinear_product_util.h/cc`. The only actual new change in this PR is to add the python binding.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707#-:-N99FQ9YE6vt0NC6U5yV:bscp6a7)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, with one small nit

> Reviewed 7 of 16 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707#-:-N9Byzto6zjAkuweAq2-:b-pgy24e)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`common/symbolic/replace_bilinear_terms.h` line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17707#-N9Bwjuv170jUYpgXhSd:-N9Bwjuw1DolcLJBW0n5:b-nff23e) ([raw file](https://github.com/robotlocomotion/drake/blob/bbdc60b92ae32d5bd22e465fd0e35b2373d8309a/common/symbolic/replace_bilinear_terms.h#L24)):*
> ```objc
>  * corresponding term in `W.
>  * @throws std::exception if `y` contains duplicate entries.
>  * @param W Bilinear product term x(i) * y(j) will be replaced by W(i, j). If
> ```

nit There is no `@pre` or `@throws` expressing `assert(W.rows() == x.rows() && W.cols() == y.rows())` in below code.

(It is implied, but perhaps useful to state in an explicit way.)

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: newly deprecated) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707#-:-N9Bz4XC9Ngg1hkt_ruN:b-dngdyv)* status: 1 unresolved discussion (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`common/symbolic/replace_bilinear_terms.h` line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17707#-N9Bwjuv170jUYpgXhSd:-N9DsyTS3r5ItFqHHfan:bfa36jg) ([raw file](https://github.com/robotlocomotion/drake/blob/bbdc60b92ae32d5bd22e465fd0e35b2373d8309a/common/symbolic/replace_bilinear_terms.h#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit There is no `@pre` or `@throws` expressing `assert(W.rows() == x.rows() && W.cols() == y.rows())` in below code.

(It is implied, but perhaps useful to state in an explicit way.)
</blockquote></details>

It we say "throws", that is a _promise_ to the user that we detect the error condition and throw.  However, the implementation currently uses DRAKE_ASSERT, which will be compiled out and will typically not throw.

Either the Doxygen should say `@pre` with the pre-condition, or else the DRAKE_ASSERT should morph into DRAKE_THROW_UNLESS.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @pre)

___
*[`common/symbolic/replace_bilinear_terms.h` line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17707#-N9Bwjuv170jUYpgXhSd:-N9DxHA030qC0t5uwu0k:bqrmd5k) ([raw file](https://github.com/robotlocomotion/drake/blob/bbdc60b92ae32d5bd22e465fd0e35b2373d8309a/common/symbolic/replace_bilinear_terms.h#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It we say "throws", that is a _promise_ to the user that we detect the error condition and throw.  However, the implementation currently uses DRAKE_ASSERT, which will be compiled out and will typically not throw.

Either the Doxygen should say `@pre` with the pre-condition, or else the DRAKE_ASSERT should morph into DRAKE_THROW_UNLESS.
</blockquote></details>

Done. I changed the Doxygen to say @pre.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17707)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
