### PR TITLE
Implement DifferenceState for Diagrams. 

### PR DESCRIPTION
**Pull request by david-german-tri**
Add diagram_test and diagram_context_test to Bazel.

+@jadecastro for feature review, +@sherm1 for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4031)

### CODE REVIEW

**Comment by jadecastro** [comment]
Some minor comments below. 

---

Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KW2TcXocZg6uCubqTcA:-KW2TcXqlEnt4GA2tZH5:b47gus5) ([raw file](https://github.com/robotlocomotion/drake/blob/f1462604202971d7bfc4c70f03efe844b2304897/drake/systems/framework/diagram.h#L32)):*
> ```objc
> 
> /// Returns a vector of raw pointers that correspond placewise with the
> /// unique_ptrs in @p in.
> ```

nit: "unique_ptrs in the vector @p in"

---

*[drake/systems/framework/diagram.h, line 135 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KW2dCOjHHzdjcWgiHkk:-KW2dCOkHGfoQ49I9eyp:bpm7bxl) ([raw file](https://github.com/robotlocomotion/drake/blob/f1462604202971d7bfc4c70f03efe844b2304897/drake/systems/framework/diagram.h#L135)):*
> ```objc
>   }
> 
>   std::vector<std::unique_ptr<DifferenceState<T>>> substates_;
> ```

Perhaps consider calling this `subdifferences_`, to avoid confusion?

---

*[drake/systems/framework/diagram.h, line 814 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KW2XDp75tsH0Kuaw9l3:-KW2XDp8ArLikEmpqMlC:b-7uauq3) ([raw file](https://github.com/robotlocomotion/drake/blob/f1462604202971d7bfc4c70f03efe844b2304897/drake/systems/framework/diagram.h#L814)):*
> ```objc
>           diagram_context->GetSubsystemContext(index);
>       DRAKE_DEMAND(subcontext != nullptr);
>       DifferenceState<T>* subdifference =
> ```

No nullptr protection here for subdifference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-:-KW2fdMFL0IjkxZtj-md:ba7j27d)*

**Comment by david-german-tri** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KW2TcXocZg6uCubqTcA:-KW464-mKsRVVaBMz59M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f1462604202971d7bfc4c70f03efe844b2304897/drake/systems/framework/diagram.h#L32)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary>
> nit: "unique_ptrs in the vector @p in"
</details>
Done.

---

*[drake/systems/framework/diagram.h, line 135 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KW2dCOjHHzdjcWgiHkk:-KW46MUaP7BgU0Kpg74k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f1462604202971d7bfc4c70f03efe844b2304897/drake/systems/framework/diagram.h#L135)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary>
> Perhaps consider calling this `subdifferences_`, to avoid confusion?
</details>
Done.

---

*[drake/systems/framework/diagram.h, line 814 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KW2XDp75tsH0Kuaw9l3:-KW46RhK1rL5QJxcJWG0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f1462604202971d7bfc4c70f03efe844b2304897/drake/systems/framework/diagram.h#L814)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary>
> No nullptr protection here for subdifference?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4031)*

**Comment by jadecastro** [comment]
Reviewed 12 of 12 files at r1.
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_test.cc, line 665 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KW4j6i2_1__Rp7rSGGG:-KW4j6i3kL8f7dQoWY2l:b-v9k8te) ([raw file](https://github.com/robotlocomotion/drake/blob/1eb5d93961d8995031defa5ce9f4ec7cdfab3040/drake/systems/framework/test/diagram_test.cc#L665)):*
> ```cpp
> 
> // Tests that the next update time after 0.05 is 2.0.
> TEST_F(DifferenceStateTest, CalcNextUpdateTimeHold1) {
> ```

I'm not sure this section at all tests the `HandlePublish` call within the `DoCalcNextUpdateTime` (or at least I couldn't find it). I would think you would want to do that, since it embodies a fair chunk of the new code in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4031)*

**Comment by jadecastro** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4031)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/test/diagram_test.cc, line 665 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KW4j6i2_1__Rp7rSGGG:-KWE5GhM8oYkAxBcyXIA:bs9ezh4) ([raw file](https://github.com/robotlocomotion/drake/blob/1eb5d93961d8995031defa5ce9f4ec7cdfab3040/drake/systems/framework/test/diagram_test.cc#L665)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary>
> I'm not sure this section at all tests the `HandlePublish` call within the `DoCalcNextUpdateTime` (or at least I couldn't find it). I would think you would want to do that, since it embodies a fair chunk of the new code in this PR.
</details>
Yeah, kudos for calling me on this.  Working on an update now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4031)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/test/diagram_test.cc, line 665 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KW4j6i2_1__Rp7rSGGG:-KWEAv7TzILLFMCH72QH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1eb5d93961d8995031defa5ce9f4ec7cdfab3040/drake/systems/framework/test/diagram_test.cc#L665)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Yeah, kudos for calling me on this.  Working on an update now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4031)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: 7 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-:-KWEDvwDqBt_w7iGdENU:bnfp4nl)*

**Comment by sherm1** [comment]
Looks great -- a few minor comments, PTAL. :lgtm:

---

Reviewed 7 of 12 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 779 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGdNvbCNQn4o4EObQC:-KWGdNvbCNQn4o4EObQD:b-91ylji) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/diagram.h#L779)):*
> ```objc
>   void HandlePublish(
>       const Context<T>& context,
>       std::vector<std::pair<int, UpdateActions<T>>> sub_actions) const {
> ```

Should be `const&`

---

*[drake/systems/framework/diagram.h, line 803 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGdTtAuHo3j9tQ8jsD:-KWGdTtAuHo3j9tQ8jsE:b-91ylji) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/diagram.h#L803)):*
> ```objc
>   void HandleUpdate(
>       const Context<T>& context, DifferenceState<T>* update,
>       std::vector<std::pair<int, UpdateActions<T>>> sub_actions) const {
> ```

Should be `const&`

---

*[drake/systems/framework/primitives/BUILD, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGf46zWWHynZDS07CP:-KWGf46zWWHynZDS07CQ:bgcqvjq) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/primitives/BUILD#L54)):*
> ```Python
>     ],
>     linkstatic=1)
>     
> ```

BTW, missing newline at eof?

---

*[drake/systems/framework/test/BUILD, line 93 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGfJyYnywbV63jCi5m:-KWGfJyYnywbV63jCi5n:bxh027q) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/test/BUILD#L93)):*
> ```Python
>     size = "small",
>     linkstatic=1,
>     testonly=1)
> ```

BTW, newline missing at eof?

---

*[drake/systems/framework/test/diagram_context_test.cc, line 120 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGfjtqaDqASX9fB7_w:-KWGfjtqaDqASX9fB7_x:b-vo0dkt) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/test/diagram_context_test.cc#L120)):*
> ```cpp
>   EXPECT_EQ(2, xc->get_misc_continuous_state().size());
> 
>   // The zero-order hold as a difference state vector of length 1.
> ```

BTW, as->has

---

*[drake/systems/framework/test/diagram_test.cc, line 750 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGht86hmDzRTBay4KE:-KWGht86hmDzRTBay4KF:b-1d7h0p) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/test/diagram_test.cc#L750)):*
> ```cpp
>   diagram_.CalcNextUpdateTime(*context_, &actions);
>   EXPECT_EQ(12.0, actions.time);
>   ASSERT_EQ(1u, actions.events.size());
> ```

BTW, why aren't their two events here if hold1 & hold2 have updates at 12?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-:-KWGixHFM0XXVwt2EwTy:by0njk3)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 779 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGdNvbCNQn4o4EObQC:-KWJ-dKlnlaABfL2wiK_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/diagram.h#L779)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should be `const&`
</details>
Done.

---

*[drake/systems/framework/diagram.h, line 803 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGdTtAuHo3j9tQ8jsD:-KWJ-dqo8lOHsRGWauc5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/diagram.h#L803)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should be `const&`
</details>
Done.

---

*[drake/systems/framework/primitives/BUILD, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGf46zWWHynZDS07CP:-KWJ-mRcTnzGn2NYphzx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/primitives/BUILD#L54)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, missing newline at eof?
</details>
Done.

---

*[drake/systems/framework/test/BUILD, line 93 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGfJyYnywbV63jCi5m:-KWJ-hgxOs44ClJVA1yI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/test/BUILD#L93)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, newline missing at eof?
</details>
Done.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 120 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGfjtqaDqASX9fB7_w:-KWJ-rVDxPacD_cNfxUz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/test/diagram_context_test.cc#L120)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, as->has
</details>
Done.

---

*[drake/systems/framework/test/diagram_test.cc, line 750 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4031#-KWGht86hmDzRTBay4KE:-KWJ09ZiQtEQ-tlOHIS0:b12lvsw) ([raw file](https://github.com/robotlocomotion/drake/blob/3d20d5c7ae2b1af5fc5e9c8fb45cfe8b0ed99740/drake/systems/framework/test/diagram_test.cc#L750)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, why aren't their two events here if hold1 & hold2 have updates at 12?
</details>
Because the Diagram callback expands the single event to two sub-events.  See the call to std::bind in `DoCalcNextUpdateTime`.  Added a comment here, and tweaked the test to better prove that's actually happening.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4031)*

**Comment by david-german-tri** [comment]
I don't know why Jenkins has fallen over on the release-mode open source build.  Since all the others (including debug-mode open-source, and various other release-mode builds) are passing, I'm going to override merge.

**Pull request merged**
