### PR TITLE
Update drake CMake config files for DEE

### PR DESCRIPTION
**Pull request by nicolecheetham**
Updated deprecated CMake code find_dependency to find_package 
Updated CMake policy version

Issue: https://github.com/RobotLocomotion/drake/issues/21099

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21804)

### CODE REVIEW

**Review by nicolecheetham — COMMENTED** [review]
+@BetsyMcPhail for review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21804#-:-O47Ml95AqJcQB9-pi-I:b6t817a)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nicolecheetham)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21804#-:-O47RlIOAgqaR8YwqpaH:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by nicolecheetham — COMMENTED** [review]
+@rpoyner-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21804#-:-O4ArNlA2oMMZBac7LQ7:ba0u6f9)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21804#-:-O4BHwzqA28HLL8shxPM:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21804)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail

**Pull request merged**
