### PR TITLE
Fix a memory bug when setting gurobi dual solution.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Replaces #18377

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18378)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18378#-:-NI3Za3v0enCfgNI2jPE:b79lg6w)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18378#-:-NI3lMkG00kOyPIuLk-r:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18378)* status: 1 unresolved discussion (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18378#-NI3lSatBbd5yVOQu1RL:-NI3lSatBbd5yVOQu1RM:b-n2497u) (no related file):*
Blocking until the test finishes.

___

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18378)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18378#-NI3lSatBbd5yVOQu1RL:-NI4D8j5DpDUT5JL6A-r:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Blocking until the test finishes.
</blockquote></details>

Done.

___

**Pull request merged**
