### PR TITLE
[workspace] Add clarabel_cpp_internal as an opt-in dependency

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19449.

To test Clarabel.cpp on a sample program, use this command line:

```
bazel test --define=WITH_CLARABEL=ON //tools/workspace/clarabel_cpp_internal/...
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20246)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20246)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/clarabel_cpp_internal/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-Nf4HcKU02N_tgnwGcxu:-Nf4HcKU02N_tgnwGcxv:bpoj18q) ([raw file](https://github.com/RobotLocomotion/drake/blob/04134c49008df25cb5b26445ec780dec7f23cc8c/tools/workspace/clarabel_cpp_internal/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "oxfordcontrol/Clarabel.cpp",
>         commit = "dc5ed49e0ae32c45e22fffc931c6bee75fb2974d",
> ```

Working

There seems to be numbered releases like `v0.6.0` on this repository now.  (I don't think there were, when I started.)  We should probably switch to that.

**Review by jwnimmer-tri — COMMENTED** [review]
Clarabel does not support Ubuntu 20.04 ("Focal"); the version of GCC and Eigen there are both too old.  Since Drake is dropping support for Ubuntu 20.04 in March of 2024, I think it's fine to opt-out of ClarabelSolver on that platform.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-:-Nf4ZWqAETG5NRyPz0gs:b-nwnsem)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/clarabel_cpp_internal/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-Nf4HcKU02N_tgnwGcxu:-Nf4ZViUDG_dk4Wr9ArX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/04134c49008df25cb5b26445ec780dec7f23cc8c/tools/workspace/clarabel_cpp_internal/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

There seems to be numbered releases like `v0.6.0` on this repository now.  (I don't think there were, when I started.)  We should probably switch to that.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-debug please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please -- time permitting.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 50 of 53 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-:-NfI-FpF7feadXz0-rTe:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-NfHnyi7CyDgrpoHpY0v:-NfHnyi7CyDgrpoHpY0w:b-9w5tqm) (no related file):*
BTW I had to re-run install_prereqs locally to get this patch to work. I'm not sure why -- I may have been lagging on bazel version and just getting by with it, or something.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20246)* status: 1 unresolved discussion, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-NfHnyi7CyDgrpoHpY0v:-NfI-h_xCohbUUzK_6qf:bouslhf) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW I had to re-run install_prereqs locally to get this patch to work. I'm not sure why -- I may have been lagging on bazel version and just getting by with it, or something.
</blockquote></details>

Working

I'll double-check whether the default build (not opted-in to clarabel) still works with our minimum supported Bazel (4.0).

___

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule (tomorrow), please.

Free free to pass along to Sam on Thursday, if this is too far off the beaten path.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-:-NfISn9d-o5cT_1JYML3:b4dm6ji)* status: LGTM missing from assignee sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-NfHnyi7CyDgrpoHpY0v:-NfIR-lD7546FaD2jwPj:b-5vibpu) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'll double-check whether the default build (not opted-in to clarabel) still works with our minimum supported Bazel (4.0).
</blockquote></details>

OK I tested this PR using `drake_bazel_external` and bazel 5.1.0 and it passed.  (It turns out that the vtk_internal build requires a minimum bump to >= 5.1.0.  I'll fix our docs in a separate PR.)

If you have any repro instructions you think are worth me looking into, just let me know.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20246)* status: LGTM missing from assignee sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-NfHnyi7CyDgrpoHpY0v:-NfIaBiD7rb-pb424tmX:b-412hh9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I tested this PR using `drake_bazel_external` and bazel 5.1.0 and it passed.  (It turns out that the vtk_internal build requires a minimum bump to >= 5.1.0.  I'll fix our docs in a separate PR.)

If you have any repro instructions you think are worth me looking into, just let me know.
</blockquote></details>

Not sure I could repro. I'll see if I still have any crash evidence left.

___

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please (-@sherm1).

**Review by sammy-tri — COMMENTED** [review]
:lgtm: tested locally as well

> Reviewed 50 of 53 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20246#-:-NfSopR07qYbLBkFa583:b-9oztpo)* status: LGTM missing from assignee sherm1(platform)

**Pull request merged**
