### PR TITLE
Update install instructions for ros-indigo-ackermann-msgs.

### LINKED ISSUE #2926: error when building drake as a ROS catkin package
I followed the instruction on http://drake.mit.edu/from_source_ros.html#build-from-source-using-ros-catkin to build drake using catkin. But I get the following message after I call
```
catkin build -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
```

```
Errors     << drake_cars_examples:make /home/hongkai/dev/drake_catkin_workspace/logs/drake_cars_examples/build.make.001.log
In file included from /home/hongkai/dev/drake_catkin_workspace/src/drake_ros_integration/drake_cars_examples/src/car_sim_lcm_and_ros.cc:10:0:
/home/hongkai/dev/drake_catkin_workspace/src/drake_ros_integration/drake_ros_systems/include/drake_ros/ros_vehicle_system.h:9:50: fatal error: ackermann_msgs/AckermannDriveStamped.h: No such file or directory
#include "ackermann_msgs/AckermannDriveStamped.h"
                                                 ^
compilation terminated.
make[2]: *** [CMakeFiles/car_sim_lcm_and_ros.dir/src/car_sim_lcm_and_ros.cc.o] Error 1
make[1]: *** [CMakeFiles/car_sim_lcm_and_ros.dir/all] Error 2
make: *** [all] Error 2
cd /home/hongkai/dev/drake_catkin_workspace/build/drake_cars_examples; catkin build --get-env drake_cars_examples | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.........................................................................................................................................
Failed     << drake_cars_examples:make           [ Exited with code 2 ]
Failed    <<< drake_cars_examples                [ 4.7 seconds ]
[build] Summary: 2 of 3 packages succeeded.
[build]   Ignored:   1 packages were skipped or are blacklisted.
[build]   Warnings:  1 packages succeeded with warnings.
[build]   Abandoned: None.
[build]   Failed:    1 packages failed.
[build] Runtime: 1 minute and 27.9 seconds total.
```

### PR DESCRIPTION
**Pull request by liangfok**
Moved instructions to install `ros-indigo-ackermann-msgs` to the top of the Drake/ROS install section.

Resolves #2926.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2927)

### CODE REVIEW

**Comment by liangfok** [comment]
+@hongkai-dai for feature review please.
+@sherm1 for platform review please.

Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2927#-:-KNYnGptnKSAFmsC0IBL:1600904998)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2927#-:-KNYplQifO-0dasDqEmf:1417088721)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
@hongkai-dai I just updated this PR with a modification to `package.xml` that explicitly lists `ackermann-msgs` as a build and run dependency of `drake_ros_systems`. PTAL. Thanks.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2927#-:-KNYs-kigs6fHlxbKOGp:-1631249028)*

**Comment by sherm1** [comment]
Platform review: :lgtm:. Feel free to merge when CI is green.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2927#-:-KNYylMB_wnZqQ7LJXgm:-1489550402)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2927#-:-KNZ6BWQpuf4BY6gJy4u:1417088721)*

**Pull request merged**
