### PR TITLE
[geometry] Add rigid and deformable representation for proximity

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This is the first of the PR train towards #16875.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
Early checkpoint.  I'm in deformable_contact_geometries.h right now.

> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947#-:-N-ecwOeCZ-mNaUBNsbU:b-6a4r5z)* status: 4 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eYzPYCAS_2bCb1ZBK:-N-eYzPYCAS_2bCb1ZBL:bpp1vyu) (no related file):*
I note the following comment here, so we can think about it more later.

Right now the `ReferenceDeformableGeometry` owns a `VolumeMesh`.  Instead, we might want to store a reference `const VolumeMesh&` with the assumption that the `VolumeMesh` belongs to someone else, e.g., GeometryState?

---
___
*[geometry/proximity/deformable_contact_geometries.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eXPoA6h-kOqLqQFcB:-N-eXPoB8h0jRXhB9moS:b1a04z6) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L37)):*
> ```objc
> 
>   /* Constructs a deformable geometry at reference configuration with the given
>   `shape` and its spacial discretization `mesh`. An internal approximate signed
> ```

typo? s/`spacial`/`spatial`
___
*[geometry/proximity/deformable_contact_geometries.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eMV835eTmrf-TxAV1:-N-eMV835eTmrf-TxAV2:bw7d0j5) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L51)):*
> ```objc
> 
>   /* Returns the approximate signed distance field to the surface of the
>    deformable geometry in the reference configuration. */
> ```

nit: Add a precondition that this reference deformable geometry is not empty, please.

```C++
  /* Returns the approximate signed distance field to the surface of the
   deformable geometry in the reference configuration.
   @pre  This ReferenceDeformableGeometry is not empty. */
```
___
*[geometry/proximity/deformable_contact_geometries.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eP4Kz7No6fJnNq1Ng:-N-eP4Kz7No6fJnNq1Nh:bwalq52) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L53)):*
> ```objc
>    deformable geometry in the reference configuration. */
>   const VolumeMeshFieldLinear<double, double>& signed_distance_field() const {
>     return *signed_distance_field_;
> ```

```C++
DRAKE_DEMAND(signed_distance_field_ != nullptr);
```
___
*[geometry/proximity/deformable_contact_geometries.h, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eWS_3DTC8yCLKU3Az:-N-eWS_3DTC8yCLKU3B-:brz6rv5) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L57)):*
> ```objc
> 
>  private:
>   struct ReifyData {
> ```

Optional. Add this description to help the readers please.
```C++
  // Data to be used during reification. It is passed as the `user_data`
  // parameter in the ImplementGeometry API.
```

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947#-:-N-ygA8d1P32K-TVAOFV:bnfp4nl)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-xUwP6ButAaxGNoBIo:-N-xUwP6ButAaxGNoBIp:bwdwq22) (no related file):*
Per f2f discussion, I comment that I'm a bit confused about the owner of meshes, but, for now, I approve the current design that ReferenceDeformableGeometry and RigidGeometry own their meshes.

---
___
*[geometry/proximity/deformable_contact_geometries.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-xwE08Dr1qWBqMP9Rc:-N-xwE08Dr1qWBqMP9Rd:b-smszdh) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L30)):*
> ```objc
>  1. This class doesn't provide a bounding volume hierarchy.
>  2. This class calculates an approximate signed distance field instead of taking
>     a prescribed pressure field. */
> ```

Optional. To make it clear, could you also mention the signed distance is negative meter inside, while the pressure field is positive Pascal?
```
 2. This class calculates an approximate signed distance field (meters, negative inside)
    instead of taking a prescribed pressure field (Pascals, positive inside). */
```

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for platform review (on Tuesday) per rotation please, thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947#-:-N-yueXnEx-wJ1Y_PGIn:b-6f230o)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @DamrongGuoy and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eYzPYCAS_2bCb1ZBK:-N-yrMVx3r7XgvLX_Suv:b7n8o8r) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I note the following comment here, so we can think about it more later.

Right now the `ReferenceDeformableGeometry` owns a `VolumeMesh`.  Instead, we might want to store a reference `const VolumeMesh&` with the assumption that the `VolumeMesh` belongs to someone else, e.g., GeometryState?
</blockquote></details>

I added a TODO in the code to capture this discussion.

---
___
*[geometry/proximity/deformable_contact_geometries.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-xwE08Dr1qWBqMP9Rc:-N-yrvLL18IU302-e5bK:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L30)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional. To make it clear, could you also mention the signed distance is negative meter inside, while the pressure field is positive Pascal?
```
 2. This class calculates an approximate signed distance field (meters, negative inside)
    instead of taking a prescribed pressure field (Pascals, positive inside). */
```
</blockquote></details>

Done, thanks.
___
*[geometry/proximity/deformable_contact_geometries.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eXPoA6h-kOqLqQFcB:-N-yrzNCDjPUosBF9INs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L37)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

typo? s/`spacial`/`spatial`
</blockquote></details>

Done.
___
*[geometry/proximity/deformable_contact_geometries.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eMV835eTmrf-TxAV1:-N-yspX68N1_4HBtBprX:bjydml2) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L51)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit: Add a precondition that this reference deformable geometry is not empty, please.

```C++
  /* Returns the approximate signed distance field to the surface of the
   deformable geometry in the reference configuration.
   @pre  This ReferenceDeformableGeometry is not empty. */
```
</blockquote></details>

I don't understand the concern. What do you mean by an "empty" reference deformable geometry? Is it a volume mesh with no element? I don't think a mesh like that can be constructed to begin with. Consequently, any reference deformable geometry that's successfully constructed is "non-empty".
___
*[geometry/proximity/deformable_contact_geometries.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eP4Kz7No6fJnNq1Ng:-N-yt2iD2ux6n5ykJtW-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L53)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

```C++
DRAKE_DEMAND(signed_distance_field_ != nullptr);
```
</blockquote></details>

Done.
___
*[geometry/proximity/deformable_contact_geometries.h, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eWS_3DTC8yCLKU3Az:-N-yt96qCMJhSNDQo3x6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L57)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional. Add this description to help the readers please.
```C++
  // Data to be used during reification. It is passed as the `user_data`
  // parameter in the ImplementGeometry API.
```

</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[geometry/proximity/deformable_contact_geometries.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eMV835eTmrf-TxAV1:-N01Iy4X2No5xzutaU11:bio7a3d) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L51)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't understand the concern. What do you mean by an "empty" reference deformable geometry? Is it a volume mesh with no element? I don't think a mesh like that can be constructed to begin with. Consequently, any reference deformable geometry that's successfully constructed is "non-empty".
</blockquote></details>

Sorry for not being clear.  I meant:
```C++
/* Constructs an empty reference deformable geometry. */
ReferenceDeformableGeometry empty;
empty.signed_distance_field(); // Assertion failure
```
___
*[geometry/proximity/deformable_contact_geometries.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eP4Kz7No6fJnNq1Ng:-N01K_ge3vD3azDKzMdA:b-9755fn) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L53)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you!

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947#-:-N01U_OICk78KwM4MG1z:bnfp4nl)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[geometry/proximity/deformable_contact_geometries.h, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01Ogw8DIzUb5-hQWes:-N01Ogw8DIzUb5-hQWet:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L11)):*
> ```objc
> #include "drake/common/drake_assert.h"
> #include "drake/common/text_logging.h"
> #include "drake/geometry/geometry_ids.h"
> ```

unused?

**Review by amcastro-tri — COMMENTED** [review]
I am a bit confused by this design @xuchenhan-tri. While most uses of `Reifier` are for "container like things" like ProximityEngine, `hydroelastic::internal::Geometries` and `RenderEngine`, here it'd seem each deformable mesh is its own reifier. It might just be a matter of how things are documented. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947#-:-N01ZBMd2b9l7d_e-6I-:bf8z8t4)* status: 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[geometry/proximity/deformable_contact_geometries.h, line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01Yk_PAL4uK5miFZ80:-N01Yk_PAL4uK5miFZ81:b490p9i) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L40)):*
> ```objc
>   // the mesh instead of owning a copy of the mesh.
>   /* Constructs a deformable geometry at reference configuration with the given
>   `shape` and its spatial discretization `mesh`. An internal approximate signed
> ```

maybe document precondition that `mesh` is a reasonable tessellation of `shape`. 
___
*[geometry/proximity/deformable_contact_geometries.h, line 54 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01V-0z4hMDCTAJzIqC:-N01V-0z4hMDCTAJzIqD:bwa3utk) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L54)):*
> ```objc
> 
>   /* Returns the approximate signed distance field to the surface of the
>    deformable geometry in the reference configuration. */
> ```

nit, it'd help to document how this distance field is "approximate"
___
*[geometry/proximity/deformable_contact_geometries.h, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01XUJW2JDIo8O2PiZO:-N01XUJW2JDIo8O2PiZP:b2pkbhp) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L106)):*
> ```objc
>   }
> 
>   /* Returns the approximate signed distance field for the deformable geometry.
> ```

define approximate. I guess what you mean is "signed distance field for the geometry at the reference configuration Lagrangially transported to the deformed configuration"? (not sure if there'd be a better term of art to express that mouthful) 
___
*[geometry/proximity/deformable_contact_geometries.h, line 121 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01WnSa03mPw5GtCxEo:-N01WnSb-HpPUovkz6VY:b7nn0jg) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L121)):*
> ```objc
>  of the mesh. We need to locally store the pose of the mesh because right now we
>  aren't relying on FCL's broadphase. */
> class RigidGeometry {
> ```

nit, I find `internal::hydroelastic::RigidGeometry` and `geometry::internal::deformable::RigidGeometry` somehow confusing. We should always scope the names in order to avoid any sort of confusion. 
Maybe consider a more specific name for what this class does? like maybe `PosedRigidMesh` or `RigidTrasformRigidMeshPair?

**Review by xuchenhan-tri — COMMENTED** [review]
> While most uses of Reifier are for "container like things"

Not necessarily. A quick search of `ShapeReifier` in the codebase reveals multiple other usage. `ShapeReifier` takes a shape specification and turns it into a concrete geometry instance, which is what `ReferenceDeformableGeometry` does.

> ...here it'd seem each deformable mesh is its own reifier

I don't quite understand the comment. Perhaps a more local comment would help me.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947#-:-N01jBlK9ePjvHXcM1am:bktwb7o)* status: 5 unresolved discussions (waiting on @amcastro-tri, @DamrongGuoy, and @rpoyner-tri)

___
*[geometry/proximity/deformable_contact_geometries.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N-eMV835eTmrf-TxAV1:-N01fFkl5o7qxNB7Sacf:byw1wz8) ([raw file](https://github.com/robotlocomotion/drake/blob/a731bef15f2a05cd3b79ce5f76322d0f4023e792/geometry/proximity/deformable_contact_geometries.h#L51)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Sorry for not being clear.  I meant:
```C++
/* Constructs an empty reference deformable geometry. */
ReferenceDeformableGeometry empty;
empty.signed_distance_field(); // Assertion failure
```

</blockquote></details>

I see. Thanks for the explanation.

I have a hard time justifying the default constructor so I removed it. PTAL.
___
*[geometry/proximity/deformable_contact_geometries.h, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01Ogw8DIzUb5-hQWes:-N01i1v62z8YzZAfOAKZ:b2ar3so) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L11)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done. (removed)
___
*[geometry/proximity/deformable_contact_geometries.h, line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01Yk_PAL4uK5miFZ80:-N01iJCc989cBaMsqHlI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

maybe document precondition that `mesh` is a reasonable tessellation of `shape`. 
</blockquote></details>

Done.
___
*[geometry/proximity/deformable_contact_geometries.h, line 54 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01V-0z4hMDCTAJzIqC:-N01gTb9ChOcvq1nQj1j:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L54)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, it'd help to document how this distance field is "approximate"
</blockquote></details>

Done.
___
*[geometry/proximity/deformable_contact_geometries.h, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01XUJW2JDIo8O2PiZO:-N01gUezBhYi8E4bovBy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L106)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

define approximate. I guess what you mean is "signed distance field for the geometry at the reference configuration Lagrangially transported to the deformed configuration"? (not sure if there'd be a better term of art to express that mouthful) 
</blockquote></details>

Done.
___
*[geometry/proximity/deformable_contact_geometries.h, line 121 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16947#-N01WnSa03mPw5GtCxEo:-N01gdP99StcgnXMG193:b-78ep4e) ([raw file](https://github.com/robotlocomotion/drake/blob/51bde79e3fdf41439db9cd1d7f6ab76766e7799f/geometry/proximity/deformable_contact_geometries.h#L121)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, I find `internal::hydroelastic::RigidGeometry` and `geometry::internal::deformable::RigidGeometry` somehow confusing. We should always scope the names in order to avoid any sort of confusion. 
Maybe consider a more specific name for what this class does? like maybe `PosedRigidMesh` or `RigidTrasformRigidMeshPair?
</blockquote></details>

I prefer the parallel naming convention. The namespace indicates how each geometry is to be used `hydroelastic vs. deformable(_contact)`.
Also, I'd imagine that when we eventually get rid of FCL, the hydro rigid geometry would need to keep track of its pose in the world as well and we can drop the distinction between hydro and deformable geometry then.

**Review by amcastro-tri — COMMENTED** [review]
A deeper look reveals a similar pattern introduced in `geometry/optimization`. I was mostly familiar with proximity and render engines, which use a different pattern. So it looks like this is not a new way of using the reification. So it is resolved.

> I don't quite understand the comment. 

I'll respond here not to loose the thread. I meant `ReferenceDeformableGeometry`. For instance with hydroelastic I see `geometry::internal::hydroelastic::Geometries` to be the reifier for "a set of geometries". In contrast, `ReferenceDeformableGeometry` is the reifier for a single geometry. I was not aware of this patter for reifiers and it took me by surprise. However, resolved per previous comment.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947#-:-N02EzLC-alK8mOPu1G0:b-1ysnn3)* status: 2 unresolved discussions (waiting on @DamrongGuoy and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16947)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

**Pull request merged**
