### PR TITLE
Port PoseAggregator to SystemScalarConverter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This adds `symbolic::Expression` support as a side-effect.  We rely on the existing `AutoDiffXd` test cases to infer that symbolic will work correctly because they share the same codepath, and thus are not adding new symbolic-specific unit tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6750)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature and platform review, please.

**Comment by SeanCurtis-TRI** [comment]
That's compact and elegant. :LGTM:  +@ggould-tri for final review.

FTR, I'd say we rely on the existing AutoDiffXd test case *and* the test in which `PoseAggregator` is instantiated on a `symbolic::Expression` to infer successful conversion. But I agree that taken together, this is sufficient.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6750#-:-KqYZ3TuEXA4ep2mAXzH:b-f6t2zx)*

**Comment by ggould-tri** [comment]
:lgtm:, one small non-defect question below.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_aggregator.h, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6750#-KqYjqLLKPHYfii5HXfQ:-KqYjqLLKPHYfii5HXfR:b3002sf) ([raw file](https://github.com/robotlocomotion/drake/blob/d63358e896c41d1a71c12dfba0326c23a352de0d/drake/systems/rendering/pose_aggregator.h#L105)):*
> ```objc
>  private:
>   // Allow different specializations to access each other's private data.
>   template <typename> friend class PoseAggregator;
> ```

BTW is `template <typename>` really needed here?  It doesn't seem to be doing any work but I don't fully understand friend resolution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6750#-:-KqYja9kFV2GFe0KUE2n:b2ui7j4)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/rendering/pose_aggregator.h, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6750#-KqYjqLLKPHYfii5HXfQ:-KqYuKmHbrbVFsgksQkJ:b6snh36) ([raw file](https://github.com/robotlocomotion/drake/blob/d63358e896c41d1a71c12dfba0326c23a352de0d/drake/systems/rendering/pose_aggregator.h#L105)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW is `template <typename>` really needed here?  It doesn't seem to be doing any work but I don't fully understand friend resolution.
</blockquote></details>

Yes. 

By default `PoseAggregator<double>` and `PoseAggregator<AutoDiffXd>` are not friends, but we need them to be, in order to write the copy constructor.  (I think this much was already clear.)

Here, if we just had `friend class PoseAggregator;`, that would mean `PoseAggregator<T>`, which would be declaring _ourself_ as a friend.  We need some (all) _other_ template choices for `U` to also be friends.  This is the C++ way that you say that you are friends with all specializations of your own class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6750)*

**Pull request merged**
