### PR TITLE
Integrator derivative stats

### PR DESCRIPTION
**Pull request by edrumwri**
This PR adds counting of ODE derivative calls to the integrator suite. This basic statistic allows comparing integrators in an apples-to-apples manner.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5738)

### CODE REVIEW

**Comment by sherm1** [comment]
+@sherm1 for all review

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5738#-:-Kh-VHgAc8bSTVTrJYam:b7wjjn2)*

**Comment by sherm1** [comment]
:lgtm: after some minor BTWs are addressed.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/integrator_base.h, line 453 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5738#-Kh-VnhaxLuJxTjz975j:-Kh-VnhaxLuJxTjz975k:b-v27ygu) ([raw file](https://github.com/robotlocomotion/drake/blob/6184b0151cb634c5d852a01d89b52dd09cd05cea/drake/systems/analysis/integrator_base.h#L453)):*
> ```objc
>   /**
>    * Returns the number of ODE function evaluations since the last call to
>    * ResetStatistics() or Initialize().
> ```

BTW please clarify:
- that "ODE function evaluations" means "calls to CalcTimeDerivatives()"
- and whether this means *all* evaluations, even those used for calculating numerical Jacobians and those that were used in calculating steps that were ultimately rejected, and those added just for the purpose of error estimation

(assuming that's correct)

---

*[drake/systems/analysis/integrator_base.h, line 454 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5738#-Kh-VbXNEmPQ5B4cmOcg:-Kh-VbXNEmPQ5B4cmOch:b-5pdozy) ([raw file](https://github.com/robotlocomotion/drake/blob/6184b0151cb634c5d852a01d89b52dd09cd05cea/drake/systems/analysis/integrator_base.h#L454)):*
> ```objc
>    * Returns the number of ODE function evaluations since the last call to
>    * ResetStatistics() or Initialize().
>   */
> ```

BTW odd alignment

---

*[drake/systems/analysis/integrator_base.h, line 822 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5738#-Kh-WZ5HEaYjZhZDLEdv:-Kh-WZ5HEaYjZhZDLEdw:b7is4ia) ([raw file](https://github.com/robotlocomotion/drake/blob/6184b0151cb634c5d852a01d89b52dd09cd05cea/drake/systems/analysis/integrator_base.h#L822)):*
> ```objc
>                            ContinuousState<T>* dxdt) {
>     get_system().CalcTimeDerivatives(context, dxdt);
>     num_ode_evals_++;
> ```

BTW prefer ++preincrement when it doesn't matter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5738#-:-Kh-Y2TJUnCICpL_yorx:blcvm2d)*

**Comment by edrumwri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/integrator_base.h, line 453 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5738#-Kh-VnhaxLuJxTjz975j:-Kh2zRrlHwRYcUpmW6Pa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6184b0151cb634c5d852a01d89b52dd09cd05cea/drake/systems/analysis/integrator_base.h#L453)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please clarify:
- that "ODE function evaluations" means "calls to CalcTimeDerivatives()"
- and whether this means *all* evaluations, even those used for calculating numerical Jacobians and those that were used in calculating steps that were ultimately rejected, and those added just for the purpose of error estimation

(assuming that's correct)
</blockquote></details>

Done.

---

*[drake/systems/analysis/integrator_base.h, line 454 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5738#-Kh-VbXNEmPQ5B4cmOcg:-Kh2zXZG76bYP-upfndb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6184b0151cb634c5d852a01d89b52dd09cd05cea/drake/systems/analysis/integrator_base.h#L454)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW odd alignment
</blockquote></details>

Done.

---

*[drake/systems/analysis/integrator_base.h, line 822 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5738#-Kh-WZ5HEaYjZhZDLEdv:-Kh2zbPGMYGauxxawBEy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6184b0151cb634c5d852a01d89b52dd09cd05cea/drake/systems/analysis/integrator_base.h#L822)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW prefer ++preincrement when it doesn't matter
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5738)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5738)*

**Comment by sherm1** [comment]
Lint is sad: `drake/systems/analysis/integrator_base.h:828:  Line contains only semicolon. If this should be an empty statement, use {} instead.  [whitespace/semicolon] [5]`

**Pull request merged**
