### PR TITLE
Do not use pods_use_pkg_config_packages with yaml-cpp

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3473)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by david-german-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[externals/yaml_cpp, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3473#-KRnjwrxyMTQ6o4NS_yB:-KRnjwrxyMTQ6o4NS_yC:b-o0g07o) ([raw file](https://github.com/robotlocomotion/drake/blob/f9789cf63f27f223c702e53f9c27407a9f946d67/externals/yaml_cpp#L1)):*
> ```
> Subproject commit 519d33fea3fbcbe7e1f89f97ee0fa539cec33eb7
> ```

What are we pulling in from this update?  If it's not required for zapping pkg_config, maybe make it a separate PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3473)*

**Comment by jamiesnape** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[externals/yaml_cpp, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3473#-KRnjwrxyMTQ6o4NS_yB:-KRnmmBt2xnw_he3am21:b-sjahy) ([raw file](https://github.com/robotlocomotion/drake/blob/f9789cf63f27f223c702e53f9c27407a9f946d67/externals/yaml_cpp#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> What are we pulling in from this update?  If it's not required for zapping pkg_config, maybe make it a separate PR?
</details>
It is required. They had forgotten to install the cmake package config file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3473)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3473#-:-KRnqKvKAgawiQYd0B4U:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
