### PR TITLE
Remove remarkably resilient typo "the the".

### PR DESCRIPTION
**Pull request by rpoyner-tri**
In some cases, update word wrapping.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15510)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15510#-:-MfjO_v23D4FHTaZXP29:b3dcro0)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by rpoyner-tri — COMMENTED** [review]
+@ericcousineau-tri for both reviews, on tomorrow schedule. Fortunately, reviewable does pretty good job of colorizing.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15510#-:-MfjQ9g67-fIfl4Iu6np:b506ajc)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
I bet many of these are mine!  I make this typo all the the time.

**Review by rpoyner-tri — COMMENTED** [review]
@jwnimmer-tri you were the winner in my informal count. To be fair I only used one-level and not recursive 'git blame'.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15510#-:-MfjQonnESUNd0siVioS:b-dg9jky)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
Er, you were the winning platform reviewer. I think @mitiguy won the overall count.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15510#-:-MfjR6Lc3d2AxS6fIra_:b7agbtr)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by sherm1 — COMMENTED** [review]
Yay! Thanks, Rico.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15510#-:-MfjRyJC9KxfOMAR_grT:b49r1gj)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by SeanCurtis-TRI** [comment]
I was going to say it's an easy trap to to fall in.

**Review by rpoyner-tri — COMMENTED** [review]
Indeed:
```
$ git grep '\bto to\b'
doc/_release-notes/v0.13.0.md:* pydrake.geometry.render.RenderLabel cast to to int ([#12390][_#12390])
math/autodiff.h:/** Resize derivatives vector of each element of a matrix to to match the size
math/rotation_matrix.h:  /// Returns how close the matrix R is to to being a 3x3 orthonormal matrix by
tools/clion/bazel_wrapper:    benefit of non-GCC compilers to to compile gdb-friendly STL symbols.
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15510#-:-MfjSqMv0HCCFacsgVpw:bh25bf)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x 2

> Reviewed 40 of 41 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15510#-:-MfngGuVE24AomtDNpST:b4xzgsb)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @rpoyner-tri)

**Pull request merged**
