### PR TITLE
Add support for coverage locally with CMake

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4699)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/tools.cmake, line 329 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSXe3lG_OldwuJeDM:-K_oSXe3lG_OldwuJeDN:bre7lrh) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L329)):*
> ```CMake
>         add_custom_command(OUTPUT lcov_output
>           COMMAND "${LCOV_EXECUTABLE}" --capture --directory . --output-file coverage.info
>           COMMAND "${GENHTML_EXECUTABLE}" "${CMAKE_CURRENT_BINARY_DIR}/coverage.info" --output-directory "${CMAKE_CURRENT_BINARY_DIR}/coverage-html")
> ```

Can the arguments to this maybe be split onto new lines so this is not so excessively long?

---

*[cmake/tools.cmake, line 331 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSR5uKGU7hoGQQeYZ:-K_oSR5uKGU7hoGQQeY_:bpdw9ue) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L331)):*
> ```CMake
>           COMMAND "${GENHTML_EXECUTABLE}" "${CMAKE_CURRENT_BINARY_DIR}/coverage.info" --output-directory "${CMAKE_CURRENT_BINARY_DIR}/coverage-html")
>         set_property(SOURCE lcov_output PROPERTY SYMBOLIC ON)
>         add_custom_target(lcov DEPENDS lcov_output)
> ```

Remind me why you don't just add a custom target with a command?

---

*[cmake/tools.cmake, line 362 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSsasaCXWjbGa5x7K:-K_oSsatjj4VAtGIhPvl:b-pvv8jl) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L362)):*
> ```CMake
>       endif()
> 
>       set(ENV{UBSAN_OPTIONS} "coverage=1:$ENV{UBSAN_OPTIONS}")
> ```

Um... this will be in effect only for configuring the project; is that a problem?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699)*

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/tools.cmake, line 329 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSXe3lG_OldwuJeDM:-K_oWu7ULGGMFtnXlhet:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L329)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Can the arguments to this maybe be split onto new lines so this is not so excessively long?
</blockquote></details>

Done.

---

*[cmake/tools.cmake, line 331 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSR5uKGU7hoGQQeYZ:-K_oWRgiIyERnLw1Wf1F:bjapye2) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L331)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Remind me why you don't just add a custom target with a command?
</blockquote></details>

Personal preference since there is an actual output. I am just making it symbolic so that it always runs.

---

*[cmake/tools.cmake, line 362 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSsasaCXWjbGa5x7K:-K_oWvNkcLGSp_eCT0IM:b-vlqjoa) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L362)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Um... this will be in effect only for configuring the project; is that a problem?
</blockquote></details>

True. Not sure. If it is a problem here, I am going to have to follow up for the memcheck tools.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/tools.cmake, line 331 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSR5uKGU7hoGQQeYZ:-K_ozub7nBPwqYQ4wKrk:b-v5gnxk) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L331)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Personal preference since there is an actual output. I am just making it symbolic so that it always runs.
</blockquote></details>

...but the "actual output" is not really `lcov_output`, is it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/tools.cmake, line 329 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSXe3lG_OldwuJeDM:-K_p-RejVpsOtU7zIScY:ba7ba99) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L329)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, if you make further changes, it is probably clearer to put *all* the arguments on new lines:

```cmake
  COMMAND "${GENHTML_EXECUTABLE}"
    "${CMAKE_CURRENT_BINARY_DIR}/coverage.info"
    --output-directory "${CMAKE_CURRENT_BINARY_DIR}/coverage-html")
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699)*

**Comment by jamiesnape** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/tools.cmake, line 329 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSXe3lG_OldwuJeDM:-Kad2Bjeeb-nyM9LVgfL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L329)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, if you make further changes, it is probably clearer to put *all* the arguments on new lines:

```cmake
  COMMAND "${GENHTML_EXECUTABLE}"
    "${CMAKE_CURRENT_BINARY_DIR}/coverage.info"
    --output-directory "${CMAKE_CURRENT_BINARY_DIR}/coverage-html")
```
</blockquote></details>

Done.

---

*[cmake/tools.cmake, line 362 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSsasaCXWjbGa5x7K:-Kad26-pPKvsUAEKBc10:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L362)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

True. Not sure. If it is a problem here, I am going to have to follow up for the memcheck tools.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699)*

**Comment by jamiesnape** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/tools.cmake, line 331 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-K_oSR5uKGU7hoGQQeYZ:-Kad2H4Elj6Gyi8s-pie:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f858e09077f375cd475ec7b3003c0c877920f24e/cmake/tools.cmake#L331)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...but the "actual output" is not really `lcov_output`, is it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-:-Kah1_1DRagEwGmulNsZ:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by david-german-tri** [comment]
What's the motivation for this?  It looks reasonable at a glance (haven't tested it locally yet), but we should be investing new feature effort primarily in Bazel, not in CMake.

---

Reviewed 1 of 7 files at r1, 3 of 5 files at r2.
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-:-KahMxKBL6PgE_5A4mXb:b4k8hzy)*

**Comment by jamiesnape** [comment]
It has been sitting around locally for a couple of months, long before decisions about Bazel.

---

Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-:-KahO8JHseSVlXdRDqFI:bc3u1pw)*

**Comment by jamiesnape** [comment]
In other words, minimal time was invested recently. Up to you if you want it.

---

Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-:-KahOWoQIpKmu4OjauDJ:b39xzlw)*

**Comment by jamiesnape** [comment]
(Also Bazel cannot build MATLAB or Fortran or half the externals.)

---

Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-:-KahPJxPNcR2iDRMdFTU:bifpvub)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@david-german-tri We should probably either rebase, retest, and review this, or else close it.  What's your decision on the should-we-invest-in-this discussion?

**Comment by david-german-tri** [comment]
Yeah, let's not.

**Comment by jamiesnape** [comment]
Well your memcheck builds will remain broken too, then.

**Comment by david-german-tri** [comment]
Broken in what way?

---

Reviewed 1 of 7 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4699#-:-Ke5O0p3reOT6JL2btiV:b-w42u4p)*

**Comment by jamiesnape** [comment]
https://github.com/RobotLocomotion/drake/pull/4699/commits/0e2daa000c8da492c7d540d2e5698032b88e6e09

**Pull request closed without merging**
