### PR TITLE
Remove PR2 MATLAB demos

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The model files stay intact, since they are actively used by new python bindings.  A new README helps make this clear.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6270)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.
+(status: do not merge) until I've assigned additional review.

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6270#-:-KmQlKtaGqMNnCl0THs3:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge) 
+@sherm1 for all review, please.  (I'm manually cycling the MATLAB PRs through platform review, off-schedule.)

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6270#-:-KmRYw3lkEXaCJUQI2wu:b-ortea)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6270#-:-KmRtbcV7TqbSCCLpawj:bnfp4nl)*

**Pull request merged**
