### PR TITLE
workspace: Upgrade dreal to latest release 4.21.06.2

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15212)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@RussTedrake for review, please. If you don't have cycles for this, please let me know. I'll find another reviewer tomorrow.

**Comment by RussTedrake** [comment]
___
*[tools/workspace/dreal/repository.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15212#-McdQLkG6PViEwvR4Han:-McdQLkG6PViEwvR4Hao:b-2q8d) ([raw file](https://github.com/robotlocomotion/drake/blob/a27fc0c8baa21c0457a5e1c1a713d239dd8a5e09/tools/workspace/dreal/repository.bzl#L12)):*
> ```Starlark
>         repository = "dreal/dreal4",
>         commit = "4.21.06.2",
>         sha256 = "7bbd328a25c14cff814753694b1823257bb7cff7f84a7b705b9f111624d5b2e4",  # noqa
> ```

Sorry if I'm not understanding, but I see a different sha for that revision here: https://github.com/dreal/dreal4/tags ?

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15212)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

___
*[tools/workspace/dreal/repository.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15212#-McdQLkG6PViEwvR4Han:-McdQqIyDHoPLWZeA2QR:b-g1tv3h) ([raw file](https://github.com/robotlocomotion/drake/blob/a27fc0c8baa21c0457a5e1c1a713d239dd8a5e09/tools/workspace/dreal/repository.bzl#L12)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Sorry if I'm not understanding, but I see a different sha for that revision here: https://github.com/dreal/dreal4/tags ?
</blockquote></details>



FYI, here `4067225` is a commit for this tag, not SHA.

To double check it, I ran:

```
wget https://github.com/dreal/dreal4/archive/4.21.06.2.tar.gz
shasum -a 256 4.21.06.2.tar.gz
```
and I have:
```
7bbd328a25c14cff814753694b1823257bb7cff7f84a7b705b9f111624d5b2e4  4.21.06.2.tar.gz
```

**Review by RussTedrake — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15212#-:-McdRMr1-C3IT86rFltP:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Pull request merged**
