### PR TITLE
Cspace free path parametrized polynomial

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai. I will use this class in the trajectory certifier code in order to allow me to quickly construct certification programs. Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-:-NQVjLuZ3IO782X7KxwH:b-4b2anx)* status: LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
+(status: do not review) I am going to make a quick design change sorry

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-:-NQW4vGV9QFuo6Pyfa4P:b-1a0cpm)* status: LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 1 of 5 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995)* status: 11 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 34 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYtBnQ-oGeuDm7L99d:-NQYtBnQ-oGeuDm7L99e:b9xv8fo) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.h#L34)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(ParametrizedPolynomialPositiveOnUnitInterval)
> 
>   ParametrizedPolynomialPositiveOnUnitInterval(
> ```

Document the variable?
___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 40 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYygcBCGow1R3soIen:-NQYygcBCGow1R3soIeo:ba0tdbn) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.h#L40)):*
> ```objc
>   // Add the constraint that this parametrized polynomial is positive on the
>   // unit interval. The Environment env must contain an evaluation for all the
>   // parameters in parameters_. The MathematicalProgram prog must already
> ```

What is `parameters_`?
___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 43 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYylvJ4rXA9qwAuA6f:-NQYylvJ4rXA9qwAuA6g:bb7n9kb) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.h#L43)):*
> ```objc
>   // contain the indeterminates of psatz_variables_and_psd_constraints_.
>   void AddPositivityConstraintToProgram(const symbolic::Environment& env,
>                                         solvers::MathematicalProgram* prog);
> ```

Why this function is not a const function?
___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 49 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYuDov8ID-3aqgH1NN:-NQYuDov8ID-3aqgH1NO:b-vtbx1z) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.h#L49)):*
> ```objc
>   const symbolic::Polynomial& get_nu() const { return nu_; }
> 
>   const solvers::MathematicalProgram* get_psatz_variables_and_psd_constraints()
> ```

Why return a pointer here instead of a const reference? The other getters all return the const reference.
___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 65 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYxQAU7ZgO6DZWOy5S:-NQYxQAU7ZgO6DZWOy5T:b8n49j6) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.h#L65)):*
> ```objc
>   // deg(ψᵢ, μ) ≤ d - 1, and in the second deg(ψᵢ, μ) ≤ d. If deg(poly,μ) > 0 we
>   // construct the polynomial p_(μ,y) = poly(μ,y)-q(μ,y) which we will later
>   // constrain to be equal to 0.
> ```

Should also document what is p_ if deg(poly, mu) = 0.
___
*[`geometry/optimization/dev/polynomial_positive_on_path.cc` line 3 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYuPvq175zmuyN-IsQ:-NQYuPvq175zmuyN-IsR:bsz17cj) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.cc#L3)):*
> ```cpp
> #include "drake/geometry/optimization/dev/polynomial_positive_on_path.h"
> 
> #include <iostream>
> ```

iostream is redundant?
___
*[`geometry/optimization/dev/polynomial_positive_on_path.cc` line 22 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYuvK366HDWONrudOd:-NQYuvK366HDWONrudOe:b8xz35) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.cc#L22)):*
> ```cpp
>   const int deg = poly.Degree(interval_variable);
>   if (deg == 0) {
>     // If poly is of degree 0, then it is a scalar, and we just need to
> ```

Sorry, I don't think I understand this part. poly could contain other indeterminates, so poly.Degree(interval_variable) = 0 doesn't mean that `poly` is a scalar constant? I understand that if poly doesn't contain mu, then we won't need to impose a matrix sos, so if the users call this function correctly, poly should not contain any other indeterminates. But the user might call this function incorrectly.

I think here we need `DRAKE_DEMAND(poly.TotalDegree() == 0)`, and document that if poly doesn't contain mu, then we don't need the matrix-sos condition.just 
___
*[`geometry/optimization/dev/polynomial_positive_on_path.cc` line 39 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYvMXI-cwxAv7o11U5:-NQYvMXI-cwxAv7o11U6:b-6nzv6e) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.cc#L39)):*
> ```cpp
>         d + poly.indeterminates().size()};
> 
>     std::cout << multiplier_basis_d.size() << std::endl;
> ```

Remove this?
___
*[`geometry/optimization/dev/polynomial_positive_on_path.cc` line 59 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYwlhR1RpVigZBgO_R:-NQYwlhR1RpVigZBgO_S:b508s4y) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.cc#L59)):*
> ```cpp
>         psatz_variables_and_psd_constraints_.NewSosPolynomial(
>             multiplier_basis_d, type, "Sl");
>     lambda_ = lambda;
> ```

BTW, you could do `lambda_ = std::move(lambda)`.
___
*[`geometry/optimization/dev/polynomial_positive_on_path.cc` line 74 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYxgtW9z_hyTdY_8xH:-NQYxgtW9z_hyTdY_8xI:b-7a2slo) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.cc#L74)):*
> ```cpp
>       nu_ = nu;
>       p_ -= lambda * interval_variable +
>             nu * (symbolic::Polynomial(1, {interval_variable}) -
> ```

I don't think you need to specify `interval_variable` here? `symbolic::Polynomial(1) - interval_variable` should work here?
___
*[`geometry/optimization/dev/polynomial_positive_on_path.cc` line 83 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NQYz6uQ3JH3yYRTesTR:-NQYz6uQ3JH3yYRTesTS:b21s1er) ([raw file](https://github.com/RobotLocomotion/drake/blob/24092ca54772168f43ab2e8a8442aee6e156c01b/geometry/optimization/dev/polynomial_positive_on_path.cc#L83)):*
> ```cpp
>     AddPositivityConstraintToProgram(const symbolic::Environment& env,
>                                      solvers::MathematicalProgram* prog) {
>   DRAKE_DEMAND(env.size() == p_.decision_variables().size());
> ```

Sorry I don't understand this part. p_.decision_variables() include the Gram matrices in lambda and nu, do you expect the users to specify these Gram matrices as well?

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 6 files at r8, 1 of 5 files at r9, 3 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995)* status: 6 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 22 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NRLR6EV7sSej9IdNKOV:-NRLR6EV7sSej9IdNKOW:bszkwxf) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/polynomial_positive_on_path.h#L22)):*
> ```objc
>  * @param poly The parametrized polynomial which we will enforce positivity of.
>  * This polynomial can be arbitrary degree in the interval variable and must be
>  * quadratic in all other indeterminates.
> ```

I think here "other indeterminates" refer to `y` documented above? I would suggest to be explicit here, that poly's indeterminates include μ and y, and it has to be quadratic in y.
___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 61 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NRLRp1UCCshtJ_ITBIi:-NRLRp1UCCshtJ_ITBIj:b-rz6mvl) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/polynomial_positive_on_path.h#L61)):*
> ```objc
>   const symbolic::Variable mu_;
> 
>   // A polynomial q(μ,y) = ∑ f(μ)yᵢyⱼ (where μ is univariate and y is
> ```

Sorry for being pedantic, but I don't think q(μ,y) = ∑ f(μ)yᵢyⱼ is the right equation here. I assume this summation is over the subscript i and j, then it looks like the coefficient for every yᵢyⱼ term is the same, namely the coefficient is always f(μ).

How about writing it as q(μ,y) = yᵀP(μ;s)y as in the class documentation?
___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 69 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NROjYnhBXTyLjVQHiDp:-NROjYnhBXTyLjVQHiDq:b2joy35) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/polynomial_positive_on_path.h#L69)):*
> ```objc
>   // deg(ψᵢ, μ) ≤ d - 1, and in the second deg(ψᵢ, μ) ≤ d. If deg(poly,μ) > 0 we
>   // construct the polynomial p_(μ,y) = poly(μ,y)-q(μ,y) which we will later
>   // constrain to be equal to 0. If deg(poly,μ) = 0, then either q is either
> ```

duplicated `either`.
___
*[`geometry/optimization/dev/polynomial_positive_on_path.cc` line 55 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NROkdqq9t5REXjYcpBc:-NROkdqq9t5REXjYcpBd:b-jgrkf1) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/polynomial_positive_on_path.cc#L55)):*
> ```cpp
>     for (const auto& var : poly.indeterminates()) {
>       if (!var.equal_to(mu_)) {
>         DRAKE_DEMAND(poly.Degree(var) <= 2);
> ```

Why we require the degree to be <= 2 instead of exactly equal to 2? In the documentation, poly is always a quadratic polynomial of y
___
*[`geometry/optimization/dev/test/polynomial_positive_on_path_test.cc` line 203 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NROlUcb9PGgTQy6b4a5:-NROlUcc79OZ3XB3DKRv:b-xrkkrt) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/test/polynomial_positive_on_path_test.cc#L203)):*
> ```cpp
> 
>   EXPECT_TRUE(p.EqualTo(poly - lambda));
>   EXPECT_TRUE(nu.EqualTo(Polynomial(0)));
> ```

Check the degree of lambda here?
___
*[`geometry/optimization/dev/test/polynomial_positive_on_path_test.cc` line 235 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NROlgB65vjaJFtECMS3:-NROlgB65vjaJFtECMS4:b-fkywa1) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/test/polynomial_positive_on_path_test.cc#L235)):*
> ```cpp
> 
>   const Polynomial lambda{poly_prog.get_lambda()};
>   const Polynomial nu{poly_prog.get_nu()};
> ```

Check the degree of lambda and nu?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995)* status: 6 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 22 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NRLR6EV7sSej9IdNKOV:-NRYTaAd6D67dpk2zrR-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/polynomial_positive_on_path.h#L22)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think here "other indeterminates" refer to `y` documented above? I would suggest to be explicit here, that poly's indeterminates include μ and y, and it has to be quadratic in y.
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 61 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NRLRp1UCCshtJ_ITBIi:-NRYTnQA3nxOkIUNgVKg:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/polynomial_positive_on_path.h#L61)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry for being pedantic, but I don't think q(μ,y) = ∑ f(μ)yᵢyⱼ is the right equation here. I assume this summation is over the subscript i and j, then it looks like the coefficient for every yᵢyⱼ term is the same, namely the coefficient is always f(μ).

How about writing it as q(μ,y) = yᵀP(μ;s)y as in the class documentation?
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/polynomial_positive_on_path.h` line 69 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NROjYnhBXTyLjVQHiDp:-NRYTw6k2AgCvC_DRSof:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/polynomial_positive_on_path.h#L69)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

duplicated `either`.
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/polynomial_positive_on_path.cc` line 55 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NROkdqq9t5REXjYcpBc:-NRYTxvt8Kz49DJ0Hl7e:b-4m1b4g) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/polynomial_positive_on_path.cc#L55)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why we require the degree to be <= 2 instead of exactly equal to 2? In the documentation, poly is always a quadratic polynomial of y
</blockquote></details>

If we use the basis [1,y] as we do in the certification code, this polynomial could in general have linear terms. The theorem still works in this case for positivity on the interval.
___
*[`geometry/optimization/dev/test/polynomial_positive_on_path_test.cc` line 235 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NROlgB65vjaJFtECMS3:-NRYXOJI9aTrt3PYWdB3:b-ljdnih) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/test/polynomial_positive_on_path_test.cc#L235)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Check the degree of lambda and nu?
</blockquote></details>

included in the method `validate_parametrized_polynomial_prog`

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/polynomial_positive_on_path.cc` line 55 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-NROkdqq9t5REXjYcpBc:-NRYtrEn0z3ymzJd3fZi:bqng7iw) ([raw file](https://github.com/RobotLocomotion/drake/blob/66c932c0ec87a5fa5baf65e6085ac29c6ad51da1/geometry/optimization/dev/polynomial_positive_on_path.cc#L55)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

If we use the basis [1,y] as we do in the certification code, this polynomial could in general have linear terms. The theorem still works in this case for positivity on the interval.
</blockquote></details>

This was not clear in the documentation. In the class documentation we said that poly is yᵀP(μ;s)y which is always quadratic in y.

I would suggest to add it to the class documentation, that we allow both yᵀP(μ;s)y which is a homogeneous quadratic polynomial in y, and [1;y]ᵀP(μ;s)[1;y] which is not homogeneous quadratic polynomial in y.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@sherm1 for platform review please, thanks!

> Reviewed 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-:-NRjdOT_9Jl_1dnLOXKc:b-z000um)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Timed out -@sherm1 +@rpoyner-tri for platform review, please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-:-NRkA6kTDxyXXNpz1Ub7:b-gesw5b)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
per [this policy](https://drake.mit.edu/directory_structure.html#dev-directories), dev/ directory code doesn't need platform review.
I'll give it a once-over, but expect it to be read again in full when it makes the transition out of dev/.

:lgtm: 
+(release notes: feature) or maybe none? Not sure how dev/ code is usually done in release notes.

> Reviewed 1 of 6 files at r8, 1 of 5 files at r9, 1 of 4 files at r11, 1 of 3 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-:-NRnTmO461hw6FviS1_k:b44jn81)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by rpoyner-tri — COMMENTED** [review]
-(release notes: feature) +(release notes: none) +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18995#-:-NRnW1Ny0j11GrOPDyUJ:b-illlxi)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),hongkai-dai, exempt from platform review (waiting on @AlexandreAmice)

**Pull request merged**
