### PR TITLE
Move into tools/cc_toolchain the toolchain support

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.  The full WIP branch is https://github.com/jwnimmer-tri/drake/tree/build-drake-folder-6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7220)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@sammy-tri for platform review per rotation (tomorrow), please.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7220#-:-Kw0Sp53piZPqseieG6N:bnfp4nl)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/gtest.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7220#-Kw0jYszKhH1WVbW5-2a:-Kw0jYt-D5dy9M7e8kjK:b-gomlwi) ([raw file](https://github.com/robotlocomotion/drake/blob/cc5912b57cabd3152f33214402cdbd202f00d820/tools/gtest.BUILD#L3)):*
> ```
> # -*- python -*-
> 
> config_setting(
> ```

Is there a quick explanation for why this needs to be repeated now when it didn't before?  (I'm wondering about what changed for the `.BUILD` files which didn't get this treatment?)

---

*[tools/cc_toolchain/BUILD, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7220#-Kw0icoIXS8v-GX7N4yG:-Kw0icoIXS8v-GX7N4yH:b-o7hb3b) ([raw file](https://github.com/robotlocomotion/drake/blob/cc5912b57cabd3152f33214402cdbd202f00d820/tools/cc_toolchain/BUILD#L1)):*
> ```Python
> # -*- python -*-
> ```

BTW I didn't verify that this code is unchanged vs. the previous location.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7220#-:-Kw0jw02LIjI1giJsjTX:bvb1a6z)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/gtest.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7220#-Kw0jYszKhH1WVbW5-2a:-Kw1cu0lk-FKL1J1A_Ac:bitgdmo) ([raw file](https://github.com/robotlocomotion/drake/blob/cc5912b57cabd3152f33214402cdbd202f00d820/tools/gtest.BUILD#L3)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is there a quick explanation for why this needs to be repeated now when it didn't before?  (I'm wondering about what changed for the `.BUILD` files which didn't get this treatment?)
</blockquote></details>

It's a design choice -- how much do we want the third-party code's build system to be dependent on Drake's choices.  With the new phrasing, it stands on its own (doesn't have to `load(...)` any of Drake's skylark).  With the old phrasing, it was coupled into how Drake proper decided to declare a few config settings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7220)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7220#-:-Kw5dwyJjcdYPKBk2Mx-:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7220)*

**Pull request merged**
