### PR TITLE
Add glib-2.0 link flags to lcm and libbot CMake configuration files

### PR DESCRIPTION
**Pull request by fbudin69500**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6423)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm-create-cps.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZjyDmGcON6msY7ObX:-KnZjyDmGcON6msY7ObY:bo6awcu) ([raw file](https://github.com/robotlocomotion/drake/blob/0414b9cad253bae1645f872fadf41d08f9380f2a/tools/lcm-create-cps.py#L22)):*
> ```Python
>     "lcm": {
>       "Type": "dylib",
>        "Link-Flags": ["-lglib-2.0", "-lpthread"],
> ```

Indent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423)*

**Comment by jamiesnape** [comment]
Can you fix up libbot in this PR too. `-lglib-2.0`, `-lgthread-2.0`.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-:-KnZk6MKaqn4duE1nUJJ:bhsl868)*

**Comment by fbudin69500** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm-create-cps.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZjyDmGcON6msY7ObX:-KnZqG6WwyaSxrBB_WvG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0414b9cad253bae1645f872fadf41d08f9380f2a/tools/lcm-create-cps.py#L22)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Indent?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.cps, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZs5GigXcPwiJXoTWH:-KnZs5GigXcPwiJXoTWI:b88nn10) ([raw file](https://github.com/robotlocomotion/drake/blob/065f8af335df43454b551876a8a23cb291ce1d0a/tools/libbot.cps#L26)):*
> ```delphi
>       "Type": "dylib",
>       "Includes": ["@prefix@/include/libbot"],
>       "Link-Flags": ["-lglib-2.0", "-lpthread"],
> ```

`-lgthread-2.0` not `-lpthread`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/libbot.cps, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZtFbvTplzZhA-k5I6:-KnZtFbwjkaTR9Gkc9aO:be1uqd1) ([raw file](https://github.com/robotlocomotion/drake/blob/065f8af335df43454b551876a8a23cb291ce1d0a/tools/libbot.cps#L52)):*
> ```delphi
>       "Type": "dylib",
>       "Includes": ["@prefix@/include/libbot"],
>       "Location": "@prefix@/lib/libbot2_param_client.so",
> ```

Add -lglib-2.0,  -lgthread-2.0

---

*[tools/libbot.cps, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZtLmPmcH1LPGqA4Pc:-KnZtLmPmcH1LPGqA4Pd:bf5qwi0) ([raw file](https://github.com/robotlocomotion/drake/blob/065f8af335df43454b551876a8a23cb291ce1d0a/tools/libbot.cps#L78)):*
> ```delphi
>       "Type": "dylib",
>       "Includes": ["@prefix@/include/libbot"],
>       "Location": "@prefix@/lib/libbot2_frames.so",
> ```

Add -lglib-2.0

---

*[tools/libbot.cps, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZswMI5TESIzOEPvbh:-KnZswMI5TESIzOEPvbi:bf5qwi0) ([raw file](https://github.com/robotlocomotion/drake/blob/065f8af335df43454b551876a8a23cb291ce1d0a/tools/libbot.cps#L105)):*
> ```delphi
>       "Type": "dylib",
>       "Includes": ["@prefix@/include/libbot"],
>       "Location": "@prefix@/lib/libbot2_lcmgl_client.so",
> ```

Add -lglib-2.0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423)*

**Comment by fbudin69500** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tools/libbot.cps, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZs5GigXcPwiJXoTWH:-Kna9kzo1WN6SvP5KIyb:bv39y23) ([raw file](https://github.com/robotlocomotion/drake/blob/065f8af335df43454b551876a8a23cb291ce1d0a/tools/libbot.cps#L26)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`-lgthread-2.0` not `-lpthread`.
</blockquote></details>

Actualy bot2-core only depends on glib

---

*[tools/libbot.cps, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZtFbvTplzZhA-k5I6:-Kna9xrG6ukriJfufYO2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/065f8af335df43454b551876a8a23cb291ce1d0a/tools/libbot.cps#L52)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Add -lglib-2.0,  -lgthread-2.0
</blockquote></details>

Done.

---

*[tools/libbot.cps, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZtLmPmcH1LPGqA4Pc:-Kna9ziApRnurN7HKSgd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/065f8af335df43454b551876a8a23cb291ce1d0a/tools/libbot.cps#L78)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Add -lglib-2.0
</blockquote></details>

Done.

---

*[tools/libbot.cps, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KnZswMI5TESIzOEPvbh:-KnaA08-VYSe54KS8tuQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/065f8af335df43454b551876a8a23cb291ce1d0a/tools/libbot.cps#L105)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Add -lglib-2.0
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-:-KnaCkUsT2vLyp8sDv_W:bnfp4nl)*

**Comment by fbudin69500** [comment]
+@sherm1 platform review please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-:-KnaFJzEAaG7oogEq8MY:b-xso5tn)*

**Comment by sherm1** [comment]
:lgtm: but before you merge this please update the PR description to include the additional changes made here.

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-:-Knax9E6xUgN_ZohsLTM:bbzukg9)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[WORKSPACE, line 314 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6423#-KndzVwenVI-Znx2Ug7R:-KndzVwenVI-Znx2Ug7S:b-gqctk) ([raw file](https://github.com/robotlocomotion/drake/blob/2b93ceccee20c570592ead4989b2a7dc97654c59/WORKSPACE#L314)):*
> ```Python
>     name = "pycps",
>     repository = "mwoehlke/pycps",
>     commit = "adff2def458928902ad482337330676beeeedb93",
> ```

FYI / FTR, this was not on `master` when this branch was merged. I've promoted it now (on the assumption that this PR being merged means it is working), but that's supposed to block platform review...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6423)*

**Comment by jwnimmer-tri** [comment]
That's an upvote for #5230, I guess.

**Pull request merged**
