### PR TITLE
Document Bazel support on Trusty and OS X.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jwnimmer-tri for both levels of review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4994)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4994#-KbqIGSwQ2BnmTB3Ok5i:-KbqIGSwQ2BnmTB3Ok5j:b-10ofug) (no related file):*
BTW The pre-merge matrix for Bazel probably needs a tune-up.  It looks to be gcc-only right now, and doesn't cover debug?  Also the OSX Bazel debug isn't covered anywhere yet AFAICT.

---

*[drake/doc/developers.rst, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4994#-KbqJ1wm2Vona2e0Wq82:-KbqJ1wm2Vona2e0Wq83:b13nk6d) ([raw file](https://github.com/robotlocomotion/drake/blob/7a79c17575ac9adefd11c867a710c0ef8e4612cc/drake/doc/developers.rst#L95)):*
> ```reStructuredText
> |                              |                  |                    +-------------------+---------+
> |                              |                  |                    | Default + MATLAB  | Release |
> |                              |                  +--------------------+-------------------+---------+
> ```

BTW the "Minimal" and "+ MATLAB" don't really exist / make sense for Bazel.  I guess that's fine though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4994#-:-KbqJ_PDrDaZFT2mb6lI:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4994#-KbqIGSwQ2BnmTB3Ok5i:-KbqNph_fAUuutWWg0uN:b-t0wjst) (no related file):*
> BTW The pre-merge matrix for Bazel probably needs a tune-up. It looks to be gcc-only right now, and doesn't cover debug?

Yes, known issue.

> Also the OSX Bazel debug isn't covered anywhere yet AFAICT.

@jamiesnape says it's failing, but @soonho-tri and I haven't had problems locally.  Looking into that is on my TODO list.

---

*[drake/doc/developers.rst, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4994#-KbqJ1wm2Vona2e0Wq82:-KbqNh256ajYG2r9E_my:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a79c17575ac9adefd11c867a710c0ef8e4612cc/drake/doc/developers.rst#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW the "Minimal" and "+ MATLAB" don't really exist / make sense for Bazel.  I guess that's fine though.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4994)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4994)*

**Pull request merged**
