### PR TITLE
[solvers] Hotfix for fmt errors

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Hotfix for #22079.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22080)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-everything-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

+@SeanCurtis-TRI 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22080#-:-OA314Sy5_yZ-0hvTQ36:b-ts5vdl)* status: 2 unresolved discussions

___
*[`solvers/mosek_solver_internal.cc` line 1522 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22080#-OA30XGZ7XbXZFPZ7MED:-OA30XGZ7XbXZFPZ7MEE:b-a3zb2g) ([raw file](https://github.com/RobotLocomotion/drake/blob/6037dc190feeb4d11e00d915b42c12087d38b697/solvers/mosek_solver_internal.cc#L1522)):*
> ```cpp
>         throw std::runtime_error(fmt::format(
>             "MosekSolver(): kPrintToConsole=1 failed with response code {}",
>             static_cast<std::underlying_type_t<MSKrescodee>>(rescode)));
> ```

My fix was different. Elsewhere in the file, we already have `fmt_streamed(rescode)`. (Line 1481). I'd assume that would be preferred.
___
*[`solvers/nlopt_solver.cc` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22080#-OA30wL9Cji9rcTNmHzP:-OA30wL9Cji9rcTNmHzQ:b-2whiod) ([raw file](https://github.com/RobotLocomotion/drake/blob/6037dc190feeb4d11e00d915b42c12087d38b697/solvers/nlopt_solver.cc#L11)):*
> ```cpp
> #include <vector>
> 
> #include <fmt/ranges.h>
> ```

I can't believe I missed this *again*. That's two PRs in a row.

We really need to get that into our linters.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22080)* status: 1 unresolved discussion

___
*[`solvers/mosek_solver_internal.cc` line 1522 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22080#-OA30XGZ7XbXZFPZ7MED:-OA32Mpq11CbRigqFloj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6037dc190feeb4d11e00d915b42c12087d38b697/solvers/mosek_solver_internal.cc#L1522)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

My fix was different. Elsewhere in the file, we already have `fmt_streamed(rescode)`. (Line 1481). I'd assume that would be preferred.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22080)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
