### PR TITLE
Refined RigidBodySystem unit test

### PR DESCRIPTION
**Pull request by liangfok**
Mostly adding more checks and fixing grammar and spelling issues in the comments.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2574)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2116/ and is thus ready for review.
May I suggest:
+@sherm1 for feature review since he reviewed the previous version of this unit test.
+@ggould-tri for platform review since it's Friday.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2574#-:-KKT7bGQFkm_iKk7Mrp9:1052742722)*

**Comment by ggould-tri** [comment]
Big readability improvements; thanks!

I have added one item to consider below.  However because it is author's discretion I am applying platform :LGTM: anyway and you can decide if you want to bother.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 125 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2574#-KKTYnBLMIO7o1rFutJS:-KKTYnBLMIO7o1rFutJT:-1365817660) ([raw file](https://github.com/robotlocomotion/drake/blob/28ec00d273b486c16a003f2dca362588dd247f10/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L125)):*
> ```cpp
>   EXPECT_NE(tree->findLink("link_3", "model_2", 1), nullptr);
>   EXPECT_NE(tree->findLink("link_3", "model_1", 2), nullptr);
>   EXPECT_NE(tree->findLink("link_3", "model_2", 3), nullptr);
> ```

Consider using a for loop here for conciseness (`for (auto link : {"link1", ...}) { for (auto model : {"model_1", ...}) ...`)

Author's discretion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2574#-:-KKTYxZZV_hseA9yxHMh:-1312448644)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 125 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2574#-KKTYnBLMIO7o1rFutJS:-KKUXMt3qZMwMUK4iRjH:1308595048) ([raw file](https://github.com/robotlocomotion/drake/blob/28ec00d273b486c16a003f2dca362588dd247f10/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L125)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Consider using a for loop here for conciseness (`for (auto link : {"link1", ...}) { for (auto model : {"model_1", ...}) ...`)
> 
> Author's discretion.
</details>
Unfortunately, using a `for` loop is not trivial because there are certain combinations that do not exist. For example, there's no such thing as <"link_1", "model_1", 1> or <"link_1", "model_2", 0>. Because of this, I'm going to merge as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2574)*

**Comment by sherm1** [comment]
Feature review: :lgtm:; merging.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2574#-:-KKUsSqJx3443jaI0Jlp:1810933815)*

**Pull request merged**
