### PR TITLE
solveLCPmex now respects TSRBMs enable_fastqp flag

### PR DESCRIPTION
**Pull request by psiorx**
Using fastQP's solution to the LCP is still causing feet to slide in Atlas terrain sims.  We should figure out exactly why this is happening but, in the interim, the ability to turn it off will suffice.

### CODE REVIEW

**Comment by RussTedrake** [comment]
Looks good here.  Agreed we should figure out why

**Comment by psiorx** [comment]
I have a fix for this in my latest pull request.

**Comment by atefemoosavi** [comment]
I have a same problem for Nao robot simulation, I simulated a 3D model of robot in contact with terrain by TimeSteppingRigidBodyManipulator class and see the result in drake viewer. my program makes robot to raise one of it's leg and keeps it's balance. but robot slides on terrain for ever with constant speed! I think lack of terrain friction causing this problem, should I implement a friction force between the feet and terrain? how can I do that?

**Comment by psiorx** [comment]
The friction forces should be handled by the LCP formulation.  You can try setting: 

```MATLAB
options.enable_fastqp = false;
```
when constructing your TimeSteppingRigidBodyManipulator to see if that resolves your sliding issues.

**Comment by atefemoosavi** [comment]
I set that options before comment here, but the sliding persists yet and It didn't solve the issue. after my robot begins to go to one leg, it start to slide on ground,although balance is kept.

**Comment by atefemoosavi** [comment]
As a simple example,  I described a ball by urdf, then simulated it by an initial speed, as result the ball rolled down by a constant speed and it shows terrain has no friction, another question is how does friction handle by LCP and how can set the friction coefficients? 

```
function testFriction()
    options = [];
    options.floating = true;
    options.terrain = RigidBodyFlatTerrain();
    options.enable_fastqp = true;
    options.twoD = true;
    p = TimeSteppingRigidBodyManipulator('ball.urdf', 0.001, options);
    v = p.constructVisualizer();
    v.axis = [-1 1 -0.1 1.1];
    initial_state = [0;0.1;0;0.1;0;0];
    y = p.simulate([0 10], initial_state);
    v.playback(y,struct('slider',true));
end
```
 URDF is here:
```
<?xml version="1.0" ?>
<robot xmlns="http://drake.mit.edu"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://drake.mit.edu ../../doc/drakeURDF.xsd" name="ball">
<link name="ball">
    <inertial>
       <origin xyz="0 0 0" />
      <mass value="50" />
     <inertia ixx="269612.04e-09" ixy="-5876.90e-09" ixz="-139244.46e-09" iyy="643878.18e-09" iyz="18870.96e-09" izz="525191.67e-09" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
         <sphere radius="0.1"/>
      </geometry>
      <material name="red">
          <color rgba="1 0 0 1" />
      </material>
    </visual>
 <collision>
 <origin xyz="0 0 0" rpy="0 0 0" />  
       <geometry>
          <sphere radius="0.1"/>
        </geometry>
       </collision>
  </link>
 </robot>
```

**Comment by psiorx** [comment]
>  the ball rolled down by a constant speed and it shows terrain has no friction

Since the ball is rolling perfectly, no energy is lost due to friction.  If you examine the states of the ball as it's rolling, you should see that some of the initial velocity in the direction tangent to the surface should have been transferred into angular velocity of the ball as friction produces a torque at the point of contact.  If there were no friction, the ball would not develop an angular velocity.

If you try this with a shape that can't roll smoothly (e.g. a box), you should see the effects of friction more clearly.

> how does friction handle by LCP and how can set the friction coefficients

Friction is handled within the LCP by a constraint that enforces the complementarity between relative motion (slipping) and contact forces being on the interior of a polyhedral approximation to the Coulomb friction cone(sticking).  Currently, the friction coefficient is hard-coded to a value of 1 which corresponds approximately to rubber on rubber.

**Comment by atefemoosavi** [comment]
Thank you.
I found out that options.enable_fastqp by default is false in TimeSteppingRigidBody. I solved my Nao sliding problem by adding option:
```
options.use_bullet = false 
```
but I didn't understand why use_bullet should be false to have fixed robot on terrain !

**Pull request merged**
