### PR TITLE
Add SpatialInertia::SolidCubeWithMass().

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19171)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/19171 is work to helping resolve part of issue https://github.com/RobotLocomotion/drake/issues/18416.

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-:-NShjh1D6S517gq1OHU1:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:
+@xuchenhan-tri for platform review please (since I'm tomorrow's on-call)

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-:-NSmpLNz4QhOGJTzcJsr:bczhbxx)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with two minor points.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-:-NSmssJw5pbdi6UwNcnk:bmz0a3i)* status: 2 unresolved discussions (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 179 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-NSmrN5S2ejqRRlvg50O:-NSmrN5S2ejqRRlvg50P:b-26vpi9) ([raw file](https://github.com/RobotLocomotion/drake/blob/97b6dc4a1e7ceba13ee5b7730551d85ab24e4761/multibody/tree/spatial_inertia.h#L179)):*
> ```objc
>   /// @note B's rotational inertia about Bo is triaxially symmetric, meaning
>   /// B has an equal moment of inertia about any line passing through Bo.
>   /// @throws std::exception if length is zero or negative.
> ```

BTW, what about non-positive mass?
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 182 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-NSmse4A-C3mjdxYTgfs:-NSmse4A-C3mjdxYTgft:bjgvxiz) ([raw file](https://github.com/RobotLocomotion/drake/blob/97b6dc4a1e7ceba13ee5b7730551d85ab24e4761/multibody/tree/test/spatial_inertia_test.cc#L182)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       SpatialInertia<double>::SolidCubeWithDensity(density, 0),
>       "[^]* The length of a solid cube is negative or zero: .*.");
> ```

minor, I'm confused by the regex (?) here. What is this intended to match?



_Code quote:_
```cpp
[^]*
```

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19171)* status: 2 unresolved discussions (waiting on @pre and @xuchenhan-tri)

___
*[`multibody/tree/spatial_inertia.h` line 179 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-NSmrN5S2ejqRRlvg50O:-NSnE5537QW2_DAtUdC5:bcpmv73) ([raw file](https://github.com/RobotLocomotion/drake/blob/97b6dc4a1e7ceba13ee5b7730551d85ab24e4761/multibody/tree/spatial_inertia.h#L179)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, what about non-positive mass?
</blockquote></details>

Not thrown here or in related methods.
Perhaps we can add a @pre here and elsewhere (there are many similar methods).
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 182 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-NSmse4A-C3mjdxYTgfs:-NSnERNK4K9VfNkApKSE:b5o8bez) ([raw file](https://github.com/RobotLocomotion/drake/blob/97b6dc4a1e7ceba13ee5b7730551d85ab24e4761/multibody/tree/test/spatial_inertia_test.cc#L182)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, I'm confused by the regex (?) here. What is this intended to match?
</blockquote></details>

From what I learned from Sean, it matches everything, including line endings, much like .*, except better.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19171)* status: 1 unresolved discussion (waiting on @pre)

___
*[`multibody/tree/spatial_inertia.h` line 179 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-NSmrN5S2ejqRRlvg50O:-NSqDF8B8ONkcjCqC4E6:br09cq3) ([raw file](https://github.com/RobotLocomotion/drake/blob/97b6dc4a1e7ceba13ee5b7730551d85ab24e4761/multibody/tree/spatial_inertia.h#L179)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Not thrown here or in related methods.
Perhaps we can at a @pre here and elsewhere?
</blockquote></details>

That sounds reasonable to me.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 182 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-NSmse4A-C3mjdxYTgfs:-NSqCubc1ZFIeCqhWPNq:bepnlj5) ([raw file](https://github.com/RobotLocomotion/drake/blob/97b6dc4a1e7ceba13ee5b7730551d85ab24e4761/multibody/tree/test/spatial_inertia_test.cc#L182)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

From what I learned from Sean, it matches everything, including line endings, much like .*, except better.
</blockquote></details>

I see. It seems to be a non-standard pattern that std::regex accepts. Thanks for the explanation.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19171)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 179 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19171#-NSmrN5S2ejqRRlvg50O:-NSqdPxy21HjhwNT0YQh:b-71v7pa) ([raw file](https://github.com/RobotLocomotion/drake/blob/97b6dc4a1e7ceba13ee5b7730551d85ab24e4761/multibody/tree/spatial_inertia.h#L179)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

That sounds reasonable to me.
</blockquote></details>

per f2f, this will be addressed in a separate pass.

**Pull request merged**
