### PR TITLE
Updated CLion instructions to reflect the latest working version

### PR DESCRIPTION
**Pull request by rcory**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6681)

### CODE REVIEW

**Comment by rcory** [comment]
+@jwnimmer-tri for review please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq0cTjRi2PDeaK7TiGC:b8qd208)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform review, but we'll need a CLion user to serve as the feature reviewer (to confirm the accuracy of the changes).  Maybe +@sherm1, or someone could steal it if they get here first.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq0g2OvY_uP6ccIFRFR:bhpwkgi)*

**Comment by SeanCurtis-TRI** [comment]
+@seancurtis-tri for feature review (it'll give me the opportunity to upgrade myself).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq3RpY4OeNBETeYXlPc:b-p4kbcv)*

**Comment by SeanCurtis-TRI** [comment]
-@sherm1 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq3Rwx7dPRC8pzpm99D:blu3ide)*

**Comment by SeanCurtis-TRI** [comment]
When I'm done upgrading, I find my CLion isn't happy. There were errors during the resync such that the project didn't finish building; so I have a bazillion unresolved symbols and header files. Does anyone else have that?  @sherm1, @rcory?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-Kq3W1520TEi6pI_-Jc_:-Kq3W153-Fwv0LVBI515:bcpkkpo) ([raw file](https://github.com/robotlocomotion/drake/blob/d1a6f868074b5e9adf4263a5c3a7f38785c5599e/drake/doc/clion.rst#L30)):*
> ```reStructuredText
>    ``locate jetbrains-clion.desktop`` and edit the located file. If more than
>    one file is located, you may want to consolidate to a single launch file in
>    your user directory, typically ``~/.local/share/applications``.
> ```

In my upgrade, I had to uninstall the old plugin and reinstall the new. That might be worth noting here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq3W8po0Xt0Xzp7i8EW:b-w7ewu)*

**Comment by sherm1** [comment]
Not sure how much this matters but @seancurtis-tri is trying this on his crusty Trusty (Ubuntu 14.04) machine; Rick and I both have Xenial (16.04).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-Kq3W1520TEi6pI_-Jc_:-Kq3bktkJvLkpWSYkcC1:b-pya950) ([raw file](https://github.com/robotlocomotion/drake/blob/d1a6f868074b5e9adf4263a5c3a7f38785c5599e/drake/doc/clion.rst#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In my upgrade, I had to uninstall the old plugin and reinstall the new. That might be worth noting here.
</blockquote></details>

BTW I had the same problem as @seancurtis-tri and had to manually uninstall and then reinstall the Bazel plug in to get it uplevel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq3cIMTJYgivX9PQja2:b5laian)*

**Comment by SeanCurtis-TRI** [comment]
So, after wrestling through updating things myself, I recommend the following:

1. The single bullet about an upgrading issue should be made into a topic (Upgrading CLion).  Under that topic should include the following:
    - Updating the .desktop file.
    - Uninstalling the previous bazel plug-in and installing the newest version.
    - Confirming that for clion 2017.1.3 you use clion plugin 2017.07.05.02 and bazel version 0.5.2.
    - Indicate that it isn't necessary to import the project into a *new* clion project, overwriting the old is appropriate (i.e., the directory likely located in `~/ClionProjects/project-name`).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq3gL6O5kj6s48SQ_FC:b-pu6uw4)*

**Comment by rcory** [comment]
Thanks Sean! Added a section on Upgrading CLion, per your suggestion.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq3tKTMt18DabffH2KF:boa0bpx)*

**Comment by SeanCurtis-TRI** [comment]
Great.  One little typo and then :LGTM: +(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/clion.rst, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-Kq3tpH0EkYQxl3-kPxk:-Kq3tpH0EkYQxl3-kPxl:b-3faop1) ([raw file](https://github.com/robotlocomotion/drake/blob/5fd935030972b6be86af1ef62c6d68123adc97da/drake/doc/clion.rst#L38)):*
> ```reStructuredText
> 2. Uninstall the previous version of the Bazel plugin and update to the latest
>    version. See `Installing the Bazel Plugin`_.
> 3. CLion 2017.3.1 users, confirm that you are using Bazel plugin 2017.05.02
> ```

Typo: 2017.1.3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq3txQ4yRPVngruD_p-:b-tlgxfo)*

**Comment by rcory** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-Kq3tpH0EkYQxl3-kPxk:-Kq4M3A-8omN97D_VPC_:b-376vyo) ([raw file](https://github.com/robotlocomotion/drake/blob/5fd935030972b6be86af1ef62c6d68123adc97da/drake/doc/clion.rst#L38)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Typo: 2017.1.3
</blockquote></details>

Done. Good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681)*

**Comment by SeanCurtis-TRI** [comment]
+@soonho-tri for final review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq4j3nHgkpyAsHvcQDI:b9rxnnj)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6681#-:-Kq4o7k8yjd3ymFKE7GX:bnfp4nl)*

**Pull request merged**
