### PR TITLE
Provide documentation for working with the continuous contact model

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This provides documentation for working with the new contact model -- how it works and what its properties are.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5455)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@jwnimmer-tri  for platform -- given that this is strictly a doxygen file, we can proceed with platform simulataneously with feature with particular focus on how images are integrated.  I have one open question, the figures referenced (.png) are generated from other sources (and .svg in one case and python files in the other cases), should those sources be included?

+@sherm1 for feature review.  Lots of language to make sure I didn't butcher the concepts.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-KenxH2xX4njz5Bmrug7:b-oi7dcn)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-KeoT4ChN0AAzx_hTqzd:b-rm2p6t)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

:lgtm: platform.  I didn't read text much.  You might want a second feature reviewer if you think that's warranted (but I'm fine either way).

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-KeoaSNmN1EaNO6aYeEt:bgoi2or)*

**Comment by SeanCurtis-TRI** [comment]
@jwnimmer-tri do you have any opinions about including the "source" files for the png images?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-KeodYKpnwIYj0HO0iM8:b-7fipi)*

**Comment by jwnimmer-tri** [comment]
That is a good question.  I thought about whether to ask for how someone would update the images if they needed to correct a defect, but wasn't too worried; maybe I should have been?

I would say discuss within the dynamics team and make a proposal.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-KeopbCcHRsdPwqndmzN:b-f4r176)*

**Comment by jwnimmer-tri** [comment]
With respect to image source materials, that boils down to "try to commit the image source, if it reasonably fits in `git`", which SGTM.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-KeowzQmm7VANzC19SoV:b-4pmiu4)*

**Comment by SeanCurtis-TRI** [comment]
I agree with @sherm1.  If I can take the liberty of modifying @jwnimmer-tri's summary slightly:

> Commit the image source if it reasonably fits in `git`, making sure that the relationship between source and product is clear.

---

Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-KeoxO42e1p2w1f25NLA:b-j2wfhc)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KeozJH8hf8gLCA9Lkh7:-KeozJH8hf8gLCA9Lkh8:bf2poqc) (no related file):*
Neat!  The feature reviewer should run the programs to make sure that (at least at this moment in time) they can repro the images.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by sherm1** [comment]
@seancurtis-tri, I pushed some updates to the documentation. PTAL and have at it. :lgtm:

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-Kezs6Kc4Zgay6YtvMkS:b4sk1hg)*

**Comment by sherm1** [comment]
Reviewed 6 of 7 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 819 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KezsaYHiDME0zhKie3V:-KezsaYHiDME0zhKie3W:b-z2a65p) ([raw file](https://github.com/robotlocomotion/drake/blob/56cad90d724191e59cfb9d983474a4a937c307fc/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L819)):*
> ```cpp
>       // local variables as follows:
>       //  x = -pair.distance -- penetration depth.
>       //  ̇ẋ = -rv_BcAc_C(2)  -- change of penetration (in normal direction).
> ```

BTW, per discussion with @mitiguy, this could be `v_CBcAc` (final `_C` allowed but not necessary) though it isn't clear whether that clarifies anything!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by SeanCurtis-TRI** [comment]
A great deal of wonderful refinement.  Thank you.  I've tweaked some myself.  PTAL

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 819 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KezsaYHiDME0zhKie3V:-Kf7XVTPygVj9toSi7iC:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/56cad90d724191e59cfb9d983474a4a937c307fc/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L819)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, per discussion with @mitiguy, this could be `v_CBcAc` (final `_C` allowed but not necessary) though it isn't clear whether that clarifies anything!
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-Kf7XXBkv0ptTV72soHS:b-j2infh)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KeozJH8hf8gLCA9Lkh7:-Kf7Z1Owdfu325ajkIFy:btd51a6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Neat!  The feature reviewer should run the programs to make sure that (at least at this moment in time) they can repro the images.
</blockquote></details>

I agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KeozJH8hf8gLCA9Lkh7:-Kf7_FR4y0J_o-0N-sKb:bffxjad) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I agree.
</blockquote></details>

@sherm1 let us know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by sherm1** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KeozJH8hf8gLCA9Lkh7:-Kf9CP7l1B3_OY7BPN5i:b-igrjv1) (no related file):*
On Ubuntu I was able to view the `.svg` and it did look like the png, but there wasn't an option to generate a png. So I don't know how to do that and there were no instructions. I don't think it is enough just to include the svg.

I failed completely on the Python sources. I didn't have the necessary modules. I attempted "pip install pylab" and got the message  
> Collecting pylab
>  Could not find a version that satisfies the requirement pylab (from versions: )
> No matching distribution found for pylab

When I tried to install matplotlib it did better but eventually said I should install "python-tk". When I attempted that with pip I got the same message as for pylab.

I am running Python 2.7.12 which is what I get when I type "python" at the Ubuntu 16.04 prompt. There is also "python3" but I don't know how to install modules for it; pip wants to install into 2.7.

So to whatever degree I count as a random developer sampling, I am unable to use the provided sources to create the images. I think a short README would be very helpful.

---

*[drake/multibody/rigid_body_plant/contact_model_doxygen.h, line 36 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-Kf99GPUqgzl2Zyroi2R:-Kf99GPUqgzl2Zyroi2S:b-bgdpu7) ([raw file](https://github.com/robotlocomotion/drake/blob/6287c319910d134395d9ddd0b0339c7bfbae4a8e/drake/multibody/rigid_body_plant/contact_model_doxygen.h#L36)):*
> ```objc
>  deformations in the contacting surfaces. This deformation is not modeled
>  explicitly; the contact geometry in the collision element is not actually
>  deformed.  Instead, deformation is modeled implicitly by allowing the collision
> ```

BTW, lost some clarity here. Should say that that it is the deformed surfaces that can't occupy the same space, so the undeformed surfaces will overlap. Not sure what it means to say the the geometry is not "actually" deformed. Maybe say that contact elements specify only the undeformed geometry? We don't currently produce a representation of the deformed geometry but we could -- but I don't think it would be any more deformed then than it is now, just represented better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KeozJH8hf8gLCA9Lkh7:-KfCXU5mJ7BhMmU4aXVL:ba1jpor) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

On Ubuntu I was able to view the `.svg` and it did look like the png, but there wasn't an option to generate a png. So I don't know how to do that and there were no instructions. I don't think it is enough just to include the svg.

I failed completely on the Python sources. I didn't have the necessary modules. I attempted "pip install pylab" and got the message  
> Collecting pylab
>  Could not find a version that satisfies the requirement pylab (from versions: )
> No matching distribution found for pylab

When I tried to install matplotlib it did better but eventually said I should install "python-tk". When I attempted that with pip I got the same message as for pylab.

I am running Python 2.7.12 which is what I get when I type "python" at the Ubuntu 16.04 prompt. There is also "python3" but I don't know how to install modules for it; pip wants to install into 2.7.

So to whatever degree I count as a random developer sampling, I am unable to use the provided sources to create the images. I think a short README would be very helpful.
</blockquote></details>

I'm addressing this in two passes: addressing compliant model language and adding image generation instructions.  This includes the changes to the discussion of the compliant model.  

---

*[drake/multibody/rigid_body_plant/contact_model_doxygen.h, line 36 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-Kf99GPUqgzl2Zyroi2R:-KfCXQY0a5P_Ir41uzdg:b-txfgks) ([raw file](https://github.com/robotlocomotion/drake/blob/6287c319910d134395d9ddd0b0339c7bfbae4a8e/drake/multibody/rigid_body_plant/contact_model_doxygen.h#L36)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, lost some clarity here. Should say that that it is the deformed surfaces that can't occupy the same space, so the undeformed surfaces will overlap. Not sure what it means to say the the geometry is not "actually" deformed. Maybe say that contact elements specify only the undeformed geometry? We don't currently produce a representation of the deformed geometry but we could -- but I don't think it would be any more deformed then than it is now, just represented better.
</blockquote></details>

I think I've cleaned it up. Give it another read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KeozJH8hf8gLCA9Lkh7:-KfChpWiQqHlzdXpiWUY:b-7qso6r) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm addressing this in two passes: addressing compliant model language and adding image generation instructions.  This includes the changes to the discussion of the compliant model.  
</blockquote></details>

@sherm1 I've added a `README.md` file to the images folder.  Let me know if that resolves issues.  (Or presents new problems.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by sherm1** [comment]
A few BTWs, then :lgtm:.

---

Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KeozJH8hf8gLCA9Lkh7:-KfCpIZQrcqakiIaWwcc:b-w6txev) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@sherm1 I've added a `README.md` file to the images folder.  Let me know if that resolves issues.  (Or presents new problems.)
</blockquote></details>

A few minor comments that like are difference between Ubuntu 16.04 and 14.04, but I was able to make the image files.

---

*[drake/multibody/rigid_body_plant/images/README.md, line 14 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfCoD0wMkpnIJsxyF-F:-KfCoD0wMkpnIJsxyF-G:biklhod) ([raw file](https://github.com/robotlocomotion/drake/blob/5616e2fe1f963cdc07bc138e1f3336b5bae3531f/drake/multibody/rigid_body_plant/images/README.md#L14)):*
> ```Markdown
> 2. Open the .svg file.  File -> Open
> 3. Export a png
>    1. File -> Export Bitmap...
> ```

BTW, on Ubuntu 16.04 the installed inkscape reads "Export PNG Image..." rather than "Export Bitmap..."

---

*[drake/multibody/rigid_body_plant/images/README.md, line 17 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfCoNuNP8k6vKXzXjRc:-KfCoNuNP8k6vKXzXjRd:b-fq5zd2) ([raw file](https://github.com/robotlocomotion/drake/blob/5616e2fe1f963cdc07bc138e1f3336b5bae3531f/drake/multibody/rigid_body_plant/images/README.md#L17)):*
> ```Markdown
>    2. In "Export area", select "Drawing"
>    3. In "Bitmap size", set "pixels at" to 100.0 dpi
>    4. Click "Browse" and direct it to the `$DRAKE_DISTRO$/drake/multibody/rigid_body_plant/images` directory.
> ```

BTW, there was no "Browse" in my version; it said "Export As" instead.

---

*[drake/multibody/rigid_body_plant/images/README.md, line 19 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfCoXwd90ox-xSWD3mx:-KfCoXwd90ox-xSWD3my:b-9q2kgt) ([raw file](https://github.com/robotlocomotion/drake/blob/5616e2fe1f963cdc07bc138e1f3336b5bae3531f/drake/multibody/rigid_body_plant/images/README.md#L19)):*
> ```Markdown
>    4. Click "Browse" and direct it to the `$DRAKE_DISTRO$/drake/multibody/rigid_body_plant/images` directory.
>    5. Use the same file name as the .svg file (e.g., image.svg --> image.png).
>    6. Click the "Export" button.
> ```

BTW, this resulted in some kind of Gtk assertion failure! But when I retried it worked fine. Probably something to do with my VM and not worth mentioning. Didn't stop me from generating the png.

---

*[drake/multibody/rigid_body_plant/images/README.md, line 35 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfCo8v8-jjxBiE96fPK:-KfCo8v9e1utdqZgvCNk:b-lc7aoz) ([raw file](https://github.com/robotlocomotion/drake/blob/5616e2fe1f963cdc07bc138e1f3336b5bae3531f/drake/multibody/rigid_body_plant/images/README.md#L35)):*
> ```Markdown
> 
> - `sudo apt-get install python-matplotlib`
> - `sudo apt-get install python-numpy`
> ```

BTW, missing newline at eof.

These instructions worked perfectly. I would suggest moving the dependency installs to the beginning though. No harm in someone installing them first -- apt-get is a no-op if the module is already installed. Otherwise you have to paw through a bunch of python gobbledygook to figure out what went wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-:-KfCpfMi3FMC5TYIYS8W:bnnoy0d)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KeozJH8hf8gLCA9Lkh7:-KfD4Y5T6ysIJOCdbPVJ:b-ooumqy) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

A few minor comments that like are difference between Ubuntu 16.04 and 14.04, but I was able to make the image files.
</blockquote></details>

README modified

---

*[drake/multibody/rigid_body_plant/images/README.md, line 14 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfCoD0wMkpnIJsxyF-F:-KfD47EGddYy50E2hkgW:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5616e2fe1f963cdc07bc138e1f3336b5bae3531f/drake/multibody/rigid_body_plant/images/README.md#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, on Ubuntu 16.04 the installed inkscape reads "Export PNG Image..." rather than "Export Bitmap..."
</blockquote></details>

Done

---

*[drake/multibody/rigid_body_plant/images/README.md, line 17 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfCoNuNP8k6vKXzXjRc:-KfD47ynKOafgKU3thAm:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5616e2fe1f963cdc07bc138e1f3336b5bae3531f/drake/multibody/rigid_body_plant/images/README.md#L17)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, there was no "Browse" in my version; it said "Export As" instead.
</blockquote></details>

Done

---

*[drake/multibody/rigid_body_plant/images/README.md, line 19 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfCoXwd90ox-xSWD3mx:-KfD4AS-nZFZLhoz77XD:bvc1er7) ([raw file](https://github.com/robotlocomotion/drake/blob/5616e2fe1f963cdc07bc138e1f3336b5bae3531f/drake/multibody/rigid_body_plant/images/README.md#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this resulted in some kind of Gtk assertion failure! But when I retried it worked fine. Probably something to do with my VM and not worth mentioning. Didn't stop me from generating the png.
</blockquote></details>

BTW madness.  Madness, I tell you.

---

*[drake/multibody/rigid_body_plant/images/README.md, line 35 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfCo8v8-jjxBiE96fPK:-KfD4FBZsAPSOT273dKu:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5616e2fe1f963cdc07bc138e1f3336b5bae3531f/drake/multibody/rigid_body_plant/images/README.md#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, missing newline at eof.

These instructions worked perfectly. I would suggest moving the dependency installs to the beginning though. No harm in someone installing them first -- apt-get is a no-op if the module is already installed. Otherwise you have to paw through a bunch of python gobbledygook to figure out what went wrong.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/images/README.md, line 9 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfD9CgbZXFq3AMY03Qa:-KfD9CgbZXFq3AMY03Qb:bcc9qso) ([raw file](https://github.com/robotlocomotion/drake/blob/e405bf24f7f5051b8eb3b404531b56849fbd2217/drake/multibody/rigid_body_plant/images/README.md#L9)):*
> ```Markdown
> To install: `sudo apt-get install inkscape`
> 
> The version of inkscape will depend on which version of ubuntu you are running.  There are differences between Trusty (14.04) and Xenial (16.04).  These differences manifest themselves in some of the relevant GUI.  In those cases, the two options will be shown as [Trusty|Xenial].
> ```

BTW, line length > 80 here. We suggest, but don't require, 80 character limits for all file types if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/images/README.md, line 9 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/5455#-KfD9CgbZXFq3AMY03Qa:-KfDGaGfYaLPA3IxtOyX:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/e405bf24f7f5051b8eb3b404531b56849fbd2217/drake/multibody/rigid_body_plant/images/README.md#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, line length > 80 here. We suggest, but don't require, 80 character limits for all file types if possible.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5455)*

**Pull request merged**
