### PR TITLE
update individual entry in A/b of some costs.

### LINKED ISSUE #22131: Update Coefficients in Cost with Copying Whole Vector
In scenarios where we're solving a sequence of similar mathematical programs (e.g. #22084), we have to copy over the entire coefficient vector to update the cost. It would be much more efficient if we could just modify the internally held coefficient vector in-place. I specifically care about LinearCost, but I imagine it would be applicable to other costs as well.

cc @AlexandreAmice

### PR DESCRIPTION
**Pull request by hongkai-dai**
Including LInfNormCost, L1NormCost, PerspectiveQuadraticCost.

Resolves #22131

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22260)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@cohnt for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-:-ODD_BZL-WQINrOfJbvr:bhsqy6j)* status: LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by cohnt — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-:-ODSIAF669LZ7-seBWRm:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/cost.h` line 307 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-ODSHsUu73c_KgUDsHLp:-ODSHsUu73c_KgUDsHLq:b-m1wjp) ([raw file](https://github.com/RobotLocomotion/drake/blob/55ede2da81a6063b9c4f5d9d6ed69fbfdedf75ae/solvers/cost.h#L307)):*
> ```objc
>                           const Eigen::Ref<const Eigen::VectorXd>& new_b);
> 
>   /** Updates A(i, j) = val */
> ```

nit document the throw if i and j are invalid indices

**Review by SeanCurtis-TRI — COMMENTED** [review]
Fundamental question about the API design -- see below.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-:-ODhLYYqECIb4E0dGPNv:bhk2usq)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/cost.h` line 307 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-ODSHsUu73c_KgUDsHLp:-ODhKI2G4A32HO4gHhrD:b-j9bbpt) ([raw file](https://github.com/RobotLocomotion/drake/blob/55ede2da81a6063b9c4f5d9d6ed69fbfdedf75ae/solvers/cost.h#L307)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

nit document the throw if i and j are invalid indices
</blockquote></details>

This applies to all of the new "entry" methods.
___
*[`solvers/cost.h` line 308 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-ODhKcoWDAUMaEVah64X:-ODhKcoWDAUMaEVah64Y:benl6hg) ([raw file](https://github.com/RobotLocomotion/drake/blob/55ede2da81a6063b9c4f5d9d6ed69fbfdedf75ae/solvers/cost.h#L308)):*
> ```objc
> 
>   /** Updates A(i, j) = val */
>   void update_A_entry(int i, int j, double val);
> ```

BTW Had you considered simply giving mutable access to `A` and `b`? As the functions doesn't really *do* anything, you could just allow people to grab the matrices and write values however they like. (Setting directly from an existing matrix, blocks, etc.)  `mutable_A()` would go well with `A()`, etc.

The primary argument against doing so is if some other cost *does* do extra work related to setting matrix values, then they'd have to have different APIs. But that doesn't apply to any of the added members.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22260)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes

___
*[`solvers/cost.h` line 308 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-ODhKcoWDAUMaEVah64X:-ODlQcMKC_j8jkdGne0C:bjb7jpz) ([raw file](https://github.com/RobotLocomotion/drake/blob/55ede2da81a6063b9c4f5d9d6ed69fbfdedf75ae/solvers/cost.h#L308)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Had you considered simply giving mutable access to `A` and `b`? As the functions doesn't really *do* anything, you could just allow people to grab the matrices and write values however they like. (Setting directly from an existing matrix, blocks, etc.)  `mutable_A()` would go well with `A()`, etc.

The primary argument against doing so is if some other cost *does* do extra work related to setting matrix values, then they'd have to have different APIs. But that doesn't apply to any of the added members.
</blockquote></details>

That is an interesting idea!

For the moment I think it is better not to give mutable access to `A` and `b`. I am still debating with myself on whether internally we should store a dense `Eigen::MatrixXd A_` or a sparse `Eigen::SparseMatrix<double> A_`. If we do end up with changing to `Eigen::SparseMatrix<double> A_`, then we will need to deprecate the mutable getter to `A` and `b`.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22260)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/cost.h` line 307 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-ODSHsUu73c_KgUDsHLp:-ODlXeX17uZvFo72J7Zk:b-lset03) ([raw file](https://github.com/RobotLocomotion/drake/blob/55ede2da81a6063b9c4f5d9d6ed69fbfdedf75ae/solvers/cost.h#L307)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This applies to all of the new "entry" methods.
</blockquote></details>

"Should be valid" doesn't sufficiently correlate with `DRAKE_THROW_UNLESS`.

It should be `@throws if i or j are invalid indices.`.
___
*[`solvers/cost.h` line 308 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-ODhKcoWDAUMaEVah64X:-ODlXXzA5GF50rB7BiD6:b-ymxmqc) ([raw file](https://github.com/RobotLocomotion/drake/blob/55ede2da81a6063b9c4f5d9d6ed69fbfdedf75ae/solvers/cost.h#L308)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

That is an interesting idea!

For the moment I think it is better not to give mutable access to `A` and `b`. I am still debating with myself on whether internally we should store a dense `Eigen::MatrixXd A_` or a sparse `Eigen::SparseMatrix<double> A_`. If we do end up with changing to `Eigen::SparseMatrix<double> A_`, then we will need to deprecate the mutable getter to `A` and `b`.
</blockquote></details>

That's the best reason to hide it, alright.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22260)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Oops. Forgot. :LGTM:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-:-ODpymViAa1gWIP4BVFH:b-i4ion9)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22260#-:-ODpysPK6-UmAnw7nfQf:b-l8xbmn)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),cohnt

**Pull request merged**
