### PR TITLE
[doc] Add  component for issues

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoL4xTxAw-kkcR1YS0g:b-51ktqu)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform, but for things like labels names which are a kind of "shared resource" across everyone who works with Drake's github issues database, I'd like to have two reviewers on this change, to make sure everyone understands and buys into this.

Could you assign a feature reviewer from within Dynamics to double-check this?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoLTaSz-vd6wyZjvVWh:b-m0ll09)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Of course. +@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoLUAA0EnHbhQ2cOkrV:b-2h6ctr)* status: LGTM missing from assignee amcastro-tri, missing label for release notes (waiting on @amcastro-tri)

**Review by sherm1 — COMMENTED** [review]
Drive-by comment: I agree we should have a component for this. Is `fem` the right name? Other possibilities that come to mind are `softsim` or `multibody fem` (analogous to the various geometry components).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoLcj0c7OEoCuxIAqql:bepny5x)* status: LGTM missing from assignee amcastro-tri, missing label for release notes (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
I see softsim as a project that involves more than one components: fem, geometry, perhaps some other components when we move beyond deformable solids in the future. Therefore, I prefer `fem` or `multibody fem`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoVZRnZAWoldEewtOHK:bsogxkh)* status: LGTM missing from assignee amcastro-tri, missing label for release notes (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
IMO it makes sense to have a more umbrella naming like `softsim` rather than the specific `fem` component which is very narrow. I can see how we'll work on other technologies (particles comes in mind) in the future. I think having specific tags for each would be a bit overkill. 
The other option is to do what we do with the `geometry` label, that has several (four?) subgroups. In that regard, probably `multibody fem` is more appropriate?
Thoughts?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoYpWWR5vAfqCSF_OYN:b-njmdan)* status: LGTM missing from assignee amcastro-tri, missing label for release notes (waiting on @amcastro-tri)

**Review by sherm1 — COMMENTED** [review]
My suggestion would be to go with `softsim` for now and then split it into more categories (like `softsim fem`) later if it seems too broad.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoZINkD4jH1H64kmwSG:bjva9fw)* status: LGTM missing from assignees amcastro-tri,sherm1(platform) (waiting on @amcastro-tri and @sherm1)

**Review by xuchenhan-tri — COMMENTED** [review]
My understanding of the component tags is that they should be mutually exclusive because one can assign at most one to the issue.  In my mind, `softsim` and `geometry` aren't mutually exclusive. 
OTOH, if my perceived property of the component tags is incorrect, I'm happy with `softsim`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoZbOlt7Ut8YcZgLpNq:be7csnu)* status: LGTM missing from assignees amcastro-tri,sherm1(platform) (waiting on @amcastro-tri and @sherm1)

**Comment by jwnimmer-tri** [comment]
> ... one can assign at most one [component] to the issue.

That's correct!  There are a handful of issues that have >1 component label at the moment, and it's quite annoying when scrubbing through the issues database.

**Review by sherm1 — COMMENTED** [review]
Mutually exclusive does seem preferable! In that case adding a narrow tag is better as you proposed. Would `softsim fem` be better than just `fem`? How do you see this growing -- would we have `softsim cloth` and `softsim mpm`?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoZhLF5168e5rENAEYM:by4hrdw)* status: LGTM missing from assignees amcastro-tri,sherm1(platform) (waiting on @amcastro-tri and @sherm1)

**Review by sherm1 — COMMENTED** [review]
Great, thanks -- platform :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16093#-:-MoZn6C15A4v8UXmThML:byqxnys)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Comment by sherm1** [comment]
FYI -- I added the new label.

**Comment by xuchenhan-tri** [comment]
Thanks Sherm!

**Pull request merged**
