### PR TITLE
Report whether a joint can rotate and/or translate

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17222)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17222#-:-N2UOibo9MO1tO6VbHO4:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending a few small changes.

> Reviewed 11 of 14 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17222#-:-N2mnk0D8vC6gwOtzOux:bu6c4c9)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/joint.h` line 605 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17222#-N2mlwPV5uHt0A2CI-V-:-N2mlwPV5uHt0A2CI-V0:bgv2osm) ([raw file](https://github.com/robotlocomotion/drake/blob/f4c5cd6a9f371d7e11ca9fbd04a7733c28c246fb/multibody/tree/joint.h#L605)):*
> ```objc
>   /// joint, otherwise false checks whether the mobilizers allow translation.
>   /// @see can_rotate() and can_translate().
>   bool can_rotate_or_translate(bool is_check_rotate) const {
> ```

This method seems awkward and unnecessary -- definitely an odd addition to the public interface of Joint. Much cleaner simply to implement can_rotate() and can_translate() separately. If you also need something like can_move() you can implement in terms of the others or give it its own two-line implementation.
___
*[`multibody/tree/planar_mobilizer.h` line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17222#-N2mmpr47Nyd86ECywbc:-N2mmpr47Nyd86ECywbd:b-q56gqm) ([raw file](https://github.com/robotlocomotion/drake/blob/f4c5cd6a9f371d7e11ca9fbd04a7733c28c246fb/multibody/tree/planar_mobilizer.h#L53)):*
> ```objc
>   std::string velocity_suffix(int velocity_index_in_mobilizer) const final;
> 
>   // Overloads that define whether this mobilizer can rotate and/or translate.
> ```

minor: this comment is redundant given the method names (same for the many copies of it)

**Review by mitiguy — COMMENTED** [review]
Platform review +@jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17222#-:-N2narqdAkhopLgbhrCE:b-sh0554)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[`multibody/tree/joint.h` line 605 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17222#-N2mlwPV5uHt0A2CI-V-:-N2nQ9T30XGF3QcJII4D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f4c5cd6a9f371d7e11ca9fbd04a7733c28c246fb/multibody/tree/joint.h#L605)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This method seems awkward and unnecessary -- definitely an odd addition to the public interface of Joint. Much cleaner simply to implement can_rotate() and can_translate() separately. If you also need something like can_move() you can implement in terms of the others or give it its own two-line implementation.
</blockquote></details>

Done.
___
*[`multibody/tree/planar_mobilizer.h` line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17222#-N2mmpr47Nyd86ECywbc:-N2nQYJu84iQnDRGTMv7:b-pnkj6f) ([raw file](https://github.com/robotlocomotion/drake/blob/f4c5cd6a9f371d7e11ca9fbd04a7733c28c246fb/multibody/tree/planar_mobilizer.h#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this comment is redundant given the method names (same for the many copies of it)
</blockquote></details>

Done (here and elsewhere).

**Review by sherm1 — COMMENTED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17222)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17222)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[`multibody/tree/joint.h` line 226 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17222#-N2qZW1N2CLVRUTrj4hf:-N2rmxJo2cymDOSnM9Lc:ba0vxb9) ([raw file](https://github.com/robotlocomotion/drake/blob/5ef40ab5cc3b535c36203b3e57478a0328f35194/multibody/tree/joint.h#L226)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I don't think the period here is adding anything useful to the website docs; it looks like a mistake in preview:



Ditto for both functions.
</blockquote></details>

Done here and for can_translate().
___
*[`multibody/tree/joint.h` line 227 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17222#-N2q_5Uh-6H99wHSohle:-N2rq1f01tBqeD66nJ4A:b-dxmhge) ([raw file](https://github.com/robotlocomotion/drake/blob/5ef40ab5cc3b535c36203b3e57478a0328f35194/multibody/tree/joint.h#L227)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this function requires that the plant is already finalized?  At least, that's what `get_implementation()` claims in its documentation.  That seems important to note in this API as well.

Suggestion:
```c++
  /// @pre the MultibodyPlant must be finalized.
```

Ditto for both functions.
</blockquote></details>

Done for both functions.
___
*[`multibody/tree/joint.h` line 230 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17222#-N2q_HvyBN6t5Wg-lUZR:-N2rpzr64WJmKQ1A2_j8:b-dxmhge) ([raw file](https://github.com/robotlocomotion/drake/blob/5ef40ab5cc3b535c36203b3e57478a0328f35194/multibody/tree/joint.h#L230)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Loops should not be inlined.  (I don't imagine that we need inner-loop-simulation speed in this function, since it's purpose will be for error reporting.)

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

_It's typically not cost effective to inline functions with loops or switch statements (unless, in the common case, the loop or switch statement is never executed)._

Ditto for both functions.
</blockquote></details>

Done for both functions.
___
*[`multibody/tree/mobilizer.h` line 295 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17222#-N2qXWp9EwWf55LZ8nK5:-N2rqPQqBzb70x4ZB_ln:b-dxmhge) ([raw file](https://github.com/robotlocomotion/drake/blob/5ef40ab5cc3b535c36203b3e57478a0328f35194/multibody/tree/mobilizer.h#L295)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The phrasing here is atypical for an API specification -- see above in this file for examples.  We want something along the lines of "// Returns true iff this mobilizer can rotate."

https://drake.mit.edu/styleguide/cppguide.html#Function_Comments

Also, saying "pure virtual" is superfluous and should be removed.  It's obvious from the C++ signature that these functions are pure and virtual.
</blockquote></details>

Done for both functions.



_Code quote:_
```objc
// Pure virtual to define whether this mobilizer can rotate and/or translate.
```

**Review by mitiguy — COMMENTED** [review]
@jwnimmer-tri   I think this may be ready to merge.  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17222#-:-N2s7TzlDKNBoi94Yiit:b-p9uzmh)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17222)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Pull request merged**
