### PR TITLE
[yaml] Add sugar to read serialized files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #15868.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902#-:-MnWU1yv9CbgVd-CpJCh:bk7giky)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature review done. PTAL, thanks.

> Reviewed 2 of 11 files at r5, 1 of 24 files at r6, 1 of 9 files at r7, 38 of 38 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902#-:-MnWps0-43zHi6QCi07_:b-l8luuj)* status: 6 unresolved discussions, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWg1H33mpx9plU_MUZ:-MnWg1H33mpx9plU_MU_:bkjjlvv) (no related file):*
nit, is there a reason that some usage of YamlReadArchive is not upgraded to use the sugar? E.g. `multibody/parsing/process_model_directives.cc` line 271.

---
___
*[common/yaml/yaml_doxygen.h, line 34 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWeKR5A0OlR_6RW4rV:-MnWeKR5A0OlR_6RW4rW:b55mayb) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_doxygen.h#L34)):*
> ```objc
> MyData LoadData(const std::string& filename) {
>   MyData result;
>   const YAML::Node& root = YAML::LoadFile(filename);
> ```

This should be updated to use the sugar.
___
*[common/yaml/yaml_doxygen.h, line 45 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWeNGn3dOCbdWtt9sR:-MnWeNGn3dOCbdWtt9sS:b-xgz315) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_doxygen.h#L45)):*
> ```objc
> also be used.
> 
> YAML's "merge keys" (https://yaml.org/type/merge.html) are supported.
> ```

BTW, this is somewhat unsatisfying. Could you say a few words on "how" they are supported by giving an example similar to the one you give above?x
___
*[common/yaml/yaml_io.h, line 20 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWl0H7-tjI0UtfvpCe:-MnWl0H7-tjI0UtfvpCf:brq8kr) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L20)):*
> ```objc
> @param child_name (optional) If provided, loads data from given-named child of
>   the document's root instead of the root itself.  In other words, the YAML
>   document will look like `{child_name: { data }}` rather than just `{ data }`.
> ```

nit, the description of this parameter is slightly confusing. 

First, the how the "YAML document will look" won't change regardless of this parameter. We are deserializing here.

Second, The example given makes it look like the loaded data are almost the same with the only difference being a top level map with name "child_name" is added instead ofnnnnn only a portion of the document is parsed. Consider something along the line of
```
{child_name: {sub_data}} vs. {data}
```
___
*[common/yaml/yaml_io.h, line 21 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWoYkh3YfLCidw8VQx:-MnWoYkh3YfLCidw8VQy:b4b2g78) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L21)):*
> ```objc
>   the document's root instead of the root itself.  In other words, the YAML
>   document will look like `{child_name: { data }}` rather than just `{ data }`.
> @param defaults (optional) If provided, then any members fields that are not
> ```

nit, this is technically a false advertisement if certain options are set below, right?
___
*[common/yaml/yaml_io.h, line 29 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWfaTb4mRfjDSl1q7B:-MnWfaTcCt2be1uuskHg:be3s8b0) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L29)):*
> ```objc
> 
> @tparam Serializable must implement a
>   @ref serialize_tips "Serialize" function. */
> ```

nit, this is not accurate is it? `Serializable` could also be supported built-in types.
___
*[common/yaml/yaml_io.h, line 123 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWgptPAXNo-l-CLbnI:-MnWgptPAXNo-l-CLbnJ:bukzyv2) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L123)):*
> ```objc
>     const std::optional<YamlReadArchive::Options>& options) {
>   // Reify our optional arguments.
>   Serializable result = defaults.value_or(Serializable{});
> ```

nit, the doc didn't mention that Serializable needs to be default constructible. 
___
*[common/yaml/yaml_read_archive.h, line 29 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWi0s4AJlpbgukexEj:-MnWi0s4AJlpbgukexEk:b-7hk9lr) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_read_archive.h#L29)):*
> ```objc
> namespace yaml {
> 
> /// (Advanced) A helper class for @ref yaml_serialization "YAML Serialization"
> ```

BTW, are there direct usage of this class (i.e. not through the new sugar)? If not, consider moving this class into internal namespace.
___
*[common/yaml/test/yaml_io_test.cc, line 53 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWnJVXBT2enxVMFUnu:-MnWnJVXBT2enxVMFUnv:b-jk8xo7) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/test/yaml_io_test.cc#L53)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       LoadYamlString<StringStruct>(data, "wrong_child_name"),
>       ".* no such .*wrong_child_name.*");
> ```

BTW, I'm amused by the choice of throw message here. Why is "no such" specifically listed everything else in "there was no such top-level map entry" hidden behind ".*"?

**Comment by jwnimmer-tri** [comment]
___
*[common/yaml/yaml_io.h, line 21 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWoYkh3YfLCidw8VQx:-MnWyueRBmwxwhaRYLal:bq0bob3) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this is technically a false advertisement if certain options are set below, right?
</blockquote></details>

Yes, interesting.  To be precise, and confirm we're on the same page -- you're referring to the case where the user provides a non-null `defaults` and a non-null `options` whose settings said _not_ to retain the defaults.  Is that right?

Will fix.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: 6 unresolved discussions, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[common/yaml/yaml_io.h, line 21 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWoYkh3YfLCidw8VQx:-MnX0KS8-SfjtueeR6cP:bwh8l57) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, interesting.  To be precise, and confirm we're on the same page -- you're referring to the case where the user provides a non-null `defaults` and a non-null `options` whose settings said _not_ to retain the defaults.  Is that right?

Will fix.
</blockquote></details>

Yes, as exercised in your unit tests.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: 5 unresolved discussions, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWg1H33mpx9plU_MUZ:-MnWyh1C9TSDx1JIQpVQ:b-cmmi5i) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, is there a reason that some usage of YamlReadArchive is not upgraded to use the sugar? E.g. `multibody/parsing/process_model_directives.cc` line 271.
</blockquote></details>

I have a separate checkbox on https://github.com/RobotLocomotion/drake/issues/15868 for porting all of the uses over.  It felt like too much to try to fit into a single PR.  (Also, doing it to 100% is blocked on one other prereq PR.)

---
___
*[common/yaml/yaml_doxygen.h, line 34 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWeKR5A0OlR_6RW4rV:-MnX2TCt0L2KfGXOH4x_:bpef2rp) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_doxygen.h#L34)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This should be updated to use the sugar.
</blockquote></details>

Done.  (D'oh!)
___
*[common/yaml/yaml_doxygen.h, line 45 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWeNGn3dOCbdWtt9sR:-MnXBvuA4GXWTt6QR1Xx:b-729q18) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_doxygen.h#L45)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this is somewhat unsatisfying. Could you say a few words on "how" they are supported by giving an example similar to the one you give above?x
</blockquote></details>

Done (via TODO, and an checkbox item in #15868).
___
*[common/yaml/yaml_io.h, line 20 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWl0H7-tjI0UtfvpCe:-MnXEZ33DhyDjGe1ov8s:b-m1v9c1) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L20)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the description of this parameter is slightly confusing. 

First, the how the "YAML document will look" won't change regardless of this parameter. We are deserializing here.

Second, The example given makes it look like the loaded data are almost the same with the only difference being a top level map with name "child_name" is added instead ofnnnnn only a portion of the document is parsed. Consider something along the line of
```
{child_name: {sub_data}} vs. {data}
```
</blockquote></details>

Hmm.  The point is that the `{data}` _is_ always a congruent with the C++ structure -- it is the same placeholder in either case.  If the C++ structure defines fields "foo" and "bar", then the document is either `{child: { foo: 1, bar: 2 }}` (when using child_name=child) or `{ foo: 1, bar: 2}` (when not using child_name).

I will need to think about how to document this more clearly.
___
*[common/yaml/yaml_io.h, line 29 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWfaTb4mRfjDSl1q7B:-MnX5m-Q7_r9KRA1l-9X:b1ltw9) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this is not accurate is it? `Serializable` could also be supported built-in types.
</blockquote></details>

At the moment, I believe it is accurate.  This code does not compile:

```c++
GTEST_TEST(YamlIoTest, LoadBareString) {
  const std::string data = "some_value";
  const auto result = LoadYamlString<std::string>(data);
  EXPECT_EQ(result, "some_value");
}
```

 (`drake/common/yaml/yaml_read_archive.h:163:14: error: 'Serialize' was not declared in this scope`)

I think in the future we could extend it to be supported, but for now it is not.
___
*[common/yaml/yaml_io.h, line 123 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWgptPAXNo-l-CLbnI:-MnX5PSy-af3jL5NZ9fr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L123)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the doc didn't mention that Serializable needs to be default constructible. 
</blockquote></details>

Done.
___
*[common/yaml/yaml_read_archive.h, line 29 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWi0s4AJlpbgukexEj:-MnWzP4r46BkcRKwm4E8:b-ocu8ql) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_read_archive.h#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, are there direct usage of this class (i.e. not through the new sugar)? If not, consider moving this class into internal namespace.
</blockquote></details>

I have a separate checkbox on https://github.com/RobotLocomotion/drake/issues/15868 to consider whether to do that or not.  I am not 100% sure yet whether the sugar can fulfill all use cases.
___
*[common/yaml/test/yaml_io_test.cc, line 53 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWnJVXBT2enxVMFUnu:-MnX1kG9CNbB2IH_16YO:bpps5ju) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/test/yaml_io_test.cc#L53)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm amused by the choice of throw message here. Why is "no such" specifically listed everything else in "there was no such top-level map entry" hidden behind ".*"?
</blockquote></details>

My goal with the regex is do enough to prove which line of code failed (so that I know I'm testing the correct code path) without doing so much that it turns into a change-detector test (e.g., if I had just pasted the entire literal error string into here).

The prior revision was probably a bit too terse for the proof; I've added "map entry" now to tighten it up.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWg1H33mpx9plU_MUZ:-MnXMh5d47CduPCmd5_0:b-kufkx2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I have a separate checkbox on https://github.com/RobotLocomotion/drake/issues/15868 for porting all of the uses over.  It felt like too much to try to fit into a single PR.  (Also, doing it to 100% is blocked on one other prereq PR.)
</blockquote></details>

I see, thanks.

---
___
*[common/yaml/yaml_io.h, line 20 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWl0H7-tjI0UtfvpCe:-MnXLIWU7cSYgvLVlCgS:b74d63f) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm.  The point is that the `{data}` _is_ always a congruent with the C++ structure -- it is the same placeholder in either case.  If the C++ structure defines fields "foo" and "bar", then the document is either `{child: { foo: 1, bar: 2 }}` (when using child_name=child) or `{ foo: 1, bar: 2}` (when not using child_name).

I will need to think about how to document this more clearly.
</blockquote></details>

This is what I had in mind. 

If the YAML doc looks like 
`{child: { foo: 1, bar: 2 }, other_child: { baz: 3 }}` and my c++ struct looks like
``` 
struct Mydata {
  int foo;
  int bar;
};
```
In this case, calling the method with child_name=child gives the desired results whereas calling with child_name would throw (I think).
___
*[common/yaml/yaml_io.h, line 29 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWfaTb4mRfjDSl1q7B:-MnXK_Pr1vs77P7OvnQU:b-tetz8) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

At the moment, I believe it is accurate.  This code does not compile:

```c++
GTEST_TEST(YamlIoTest, LoadBareString) {
  const std::string data = "some_value";
  const auto result = LoadYamlString<std::string>(data);
  EXPECT_EQ(result, "some_value");
}
```

 (`drake/common/yaml/yaml_read_archive.h:163:14: error: 'Serialize' was not declared in this scope`)

I think in the future we could extend it to be supported, but for now it is not.
</blockquote></details>

Ah. right, of course.
___
*[common/yaml/test/yaml_io_test.cc, line 53 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWnJVXBT2enxVMFUnu:-MnXKr-oETA4hFMpZXml:bi7r74i) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/test/yaml_io_test.cc#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My goal with the regex is do enough to prove which line of code failed (so that I know I'm testing the correct code path) without doing so much that it turns into a change-detector test (e.g., if I had just pasted the entire literal error string into here).

The prior revision was probably a bit too terse for the proof; I've added "map entry" now to tighten it up.
</blockquote></details>

Makes sense. Thanks for the explanation.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[common/yaml/yaml_io.h, line 20 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWl0H7-tjI0UtfvpCe:-MnY6o1L3Fl0YlLIY1BT:bbiunyq) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L20)):*
Done.  Rather than trying to shove more detail into the `@param` string here, I think it makes most sense to focus on the module overview Doxygen.  I've started that in the latest push, and plan to expand and clarify in the next (doxygen-only) PR.

> ... calling the method with child_name=child gives the desired results whereas calling with child_name would throw (I think).

That is correct.  (Unless the advanced `options` are set to ignore both kinds of "missing" error conditions.)
___
*[common/yaml/yaml_io.h, line 21 at r9](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnWoYkh3YfLCidw8VQx:-MnY6MXE0US7AydnjEEl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5c2ef87134bf30a4ed157544da23640b9d34208e/common/yaml/yaml_io.h#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yes, as exercised in your unit tests.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule later this week, please.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @xuchenhan-tri)

___
*[common/yaml/yaml_doxygen.h, line 56 at r11](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnY_801C9iYuWvf_RbK:-MnY_801C9iYuWvf_RbL:b-pl5ohj) ([raw file](https://github.com/robotlocomotion/drake/blob/9bfc722dd40fa5b7b5a38fdd4b86b5df9bc11702/common/yaml/yaml_doxygen.h#L56)):*
> ```objc
> `Serialize` method.  Many common built-in types (int, double, std::string,
> std::vector, std::array, std::optional, std::variant, Eigen::Matrix) may
> also be used.
> ```

This paragraph for `Reading YAML files` is almost the same as the one for `Writing YAML files` below.  One difference is that `map` and `unordered_map` are not listed here. Is that intentional?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: LGTM missing from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @DamrongGuoy, @EricCousineau-TRI, and @xuchenhan-tri)

___
*[common/yaml/yaml_doxygen.h, line 56 at r11](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnY_801C9iYuWvf_RbK:-MnYsQ880-KnWLzFyAeg:bl6desc) ([raw file](https://github.com/robotlocomotion/drake/blob/9bfc722dd40fa5b7b5a38fdd4b86b5df9bc11702/common/yaml/yaml_doxygen.h#L56)):*
> One difference is that map and unordered_map are not listed here.

Done, thanks.

> This paragraph for Reading YAML files is almost the same as the one for Writing YAML files below.

One of the the next PRs will overhaul this documentation.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902#-:-MnZMIFl0vrbOSXCux39:bg7igkv)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with some minor nits and BTWs

> Reviewed 2 of 11 files at r5, 1 of 24 files at r6, 1 of 9 files at r7, 5 of 38 files at r9, 1 of 3 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902#-:-MnfPuAc8AJBtt-MKWFo:b-3oslge)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[common/yaml/yaml_io.h, line 26 at r12](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnfNR_c5xYOeOf0UqFF:-MnfNR_c5xYOeOf0UqFG:bcm4z3h) ([raw file](https://github.com/robotlocomotion/drake/blob/42b8c19f18ebffc8ae46cb8bacb0eee80bd31be8/common/yaml/yaml_io.h#L26)):*
> ```objc
>   any member fields that are not mentioned in the YAML will retain their
>   default values.
> @param options (optional, advanced) If provided, overrides the nominal parsing
> ```

nit Not clear to me what `(advanced)` is communicating here.

Is it because the concept itself is advanced? If so, perhaps just let the user figure it out?
Is it because the API may be unstable, as in other usages of `(Advancd)`? If so, we'd probably end up deprecating?

Is it possible to remove that qualifier?
___
*[common/yaml/yaml_io.h, line 113 at r12](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnfP_3K0lOuvNiZy6Zg:-MnfP_3K0lOuvNiZy6Zh:beimysd) ([raw file](https://github.com/robotlocomotion/drake/blob/42b8c19f18ebffc8ae46cb8bacb0eee80bd31be8/common/yaml/yaml_io.h#L113)):*
> ```objc
> @tparam Serializable must implement a
>   @ref serialize_tips "Serialize" function. */
> template <typename Serializable>
> ```

BTW (perhaps existing defect) Separation between declaration and definition seems purely aesthetic, and I'm not sure what the gain is (since definitions are relatively small).
___
*[common/yaml/yaml_io.h, line 132 at r12](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnfOC5nA2mDsDzujJxN:-MnfOC5o0wTwNE4gSbNA:b-d7w9nk) ([raw file](https://github.com/robotlocomotion/drake/blob/42b8c19f18ebffc8ae46cb8bacb0eee80bd31be8/common/yaml/yaml_io.h#L132)):*
> ```objc
>   YamlReadArchive::Options new_options = options.value_or(
>       YamlReadArchive::Options{});
>   if (defaults.has_value() && !options.has_value()) {
> ```

BTW Usage of `optional<>` with default constructible types (`Serializable`, `Options`), and reifying those options, has a bit of an odd code smell (vs. just using the default-constructed values).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @xuchenhan-tri)

___
*[common/yaml/yaml_io.h, line 26 at r12](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnfNR_c5xYOeOf0UqFF:-Mnfma3FBhNrZplRRi7f:b-yp11p4) ([raw file](https://github.com/robotlocomotion/drake/blob/42b8c19f18ebffc8ae46cb8bacb0eee80bd31be8/common/yaml/yaml_io.h#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Not clear to me what `(advanced)` is communicating here.

Is it because the concept itself is advanced? If so, perhaps just let the user figure it out?
Is it because the API may be unstable, as in other usages of `(Advancd)`? If so, we'd probably end up deprecating?

Is it possible to remove that qualifier?
</blockquote></details>

Done.

The conventional meaning of "(Advanced)" in Drake is not that the feature is experimental or otherwise going away, but rather that it's unlikely to be something the user should be touching -- it's could be arcane, or brittle, or better done via some other mechanism.

I updated the comment to say that more directly here.
___
*[common/yaml/yaml_io.h, line 113 at r12](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnfP_3K0lOuvNiZy6Zg:-MnfnVrB8bEmtc7CornN:b-ws2bbx) ([raw file](https://github.com/robotlocomotion/drake/blob/42b8c19f18ebffc8ae46cb8bacb0eee80bd31be8/common/yaml/yaml_io.h#L113)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW (perhaps existing defect) Separation between declaration and definition seems purely aesthetic, and I'm not sure what the gain is (since definitions are relatively small).
</blockquote></details>

Done (via comment).
___
*[common/yaml/yaml_io.h, line 132 at r12](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnfOC5nA2mDsDzujJxN:-MnfnaDc11bJB-V-i__y:b6aea1a) ([raw file](https://github.com/robotlocomotion/drake/blob/42b8c19f18ebffc8ae46cb8bacb0eee80bd31be8/common/yaml/yaml_io.h#L132)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Usage of `optional<>` with default constructible types (`Serializable`, `Options`), and reifying those options, has a bit of an odd code smell (vs. just using the default-constructed values).
</blockquote></details>

For each of those, a nullopt and a default-constructed value have different semantics.  Passing a non-null defaults value (even if its just default constructed) changes the implicit parsing options.  Passing non-null parsing options (even if its just default constructed) overrides the "Do not overwrite" default semantics when defaults are provided.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

___
*[common/yaml/yaml_io.h, line 132 at r12](https://reviewable.io/reviews/robotlocomotion/drake/15902#-MnfOC5nA2mDsDzujJxN:-MnfpR293X7POYamEU0l:b-pnr3o) ([raw file](https://github.com/robotlocomotion/drake/blob/42b8c19f18ebffc8ae46cb8bacb0eee80bd31be8/common/yaml/yaml_io.h#L132)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For each of those, a nullopt and a default-constructed value have different semantics.  Passing a non-null defaults value (even if its just default constructed) changes the implicit parsing options.  Passing non-null parsing options (even if its just default constructed) overrides the "Do not overwrite" default semantics when defaults are provided.
</blockquote></details>

OK Gotcha - thanks for explaining!

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15902)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Pull request merged**
