### PR TITLE
Disallow Value<AbstractValue>

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
After this PR, if you try to use `Value<AbstractValue>` for anything more than just a forward declaration you will see something like:

```
In file included from drake/systems/framework/test/value_test.cc:1:
./drake/systems/framework/value.h:342:28: error: field has incomplete type 'typename Traits::Storage' (aka 'drake::systems::value_detail::ValueTraitsImpl<drake::systems::AbstractValue, false>::Error')
  typename Traits::Storage value_;
                           ^
drake/systems/framework/test/value_test.cc:293:6: note: in instantiation of template class 'drake::systems::Value<drake::systems::AbstractValue>' requested here
  foo->GetValue<int>();
     ^
./drake/systems/framework/value.h:81:9: note: forward declaration of 'drake::systems::value_detail::ValueTraitsImpl<drake::systems::AbstractValue, false>::Error'
  class Error;  // Forward declaration; Value<AbstractValue> is not allowed.
```

I tried but was unable to figure out how to write a unit test using `static_assert` or otherwise.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6220)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
A follow-up to #6177.
+@siyuanfeng-tri for feature review, please.
+@soonho-tri for platform review, please.

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/value.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-KlWZeJlA031D0XKEFJV:-KlWZeJlA031D0XKEFJW:b2nhh85) ([raw file](https://github.com/robotlocomotion/drake/blob/aaa837677f345cd07921b24ca56ae5c1a03811e2/drake/systems/framework/value.h#L72)):*
> ```objc
> };
> 
> // We explicitly disallow Value<AbstractValue>.  It cases where it occurs, it
> ```

In?

---

*[drake/systems/framework/value.h, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-KlW_IlBZh92qbY-BFfe:-KlW_IlBZh92qbY-BFff:b2kuh49) ([raw file](https://github.com/robotlocomotion/drake/blob/aaa837677f345cd07921b24ca56ae5c1a03811e2/drake/systems/framework/value.h#L75)):*
> ```objc
> // is likely that someone has created functions such as
> //   template DoBar(const AbstractValue& foo) { ... }
> //   template <class Foo> DoBar(const Foo& foo) { DoBar(Value<Foo>{foo}; }
> ```

missing ) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-:-KlW_NogJQBdG9pEx9UK:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
*[drake/systems/framework/value.h, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-KlW_IlBZh92qbY-BFfe:-KlW_pMeLSEgdr1fOyP8:b9mzc1o) ([raw file](https://github.com/robotlocomotion/drake/blob/aaa837677f345cd07921b24ca56ae5c1a03811e2/drake/systems/framework/value.h#L75)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

missing ) ?
</blockquote></details>

on a second thought, this didn't quite parse for me.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6220)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/value.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-KlWZeJlA031D0XKEFJV:-KlYa1np-MAvh4scY49k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aaa837677f345cd07921b24ca56ae5c1a03811e2/drake/systems/framework/value.h#L72)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

In?
</blockquote></details>

Done.

---

*[drake/systems/framework/value.h, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-KlW_IlBZh92qbY-BFfe:-KlYa2WEQnv-Fztz6Mrt:b-1i8qaq) ([raw file](https://github.com/robotlocomotion/drake/blob/aaa837677f345cd07921b24ca56ae5c1a03811e2/drake/systems/framework/value.h#L75)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

on a second thought, this didn't quite parse for me.. 
</blockquote></details>

Good eye on the paren, I've added the missing one.

I'm not sure what else is confusing you -- please let me know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6220)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/value.h, line 227 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-KlYtI6csjiRm4PVxXBk:-KlYtI6csjiRm4PVxXBl:b18to4g) ([raw file](https://github.com/robotlocomotion/drake/blob/63a1763abab68b4686ff2ce916154768ff38970b/drake/systems/framework/value.h#L227)):*
> ```objc
> template <typename T>
> class Value : public AbstractValue {
>  public:
> ```

This works and looks good to me. I just want to know your opinion on an alternative method:

```c++
  static_assert(!std::is_same<T, std::remove_cv<AbstractValue>::type>::value,
                "T in Value<T> should not be AbstractValue.");
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6220)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/value.h, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-KlW_IlBZh92qbY-BFfe:-KlYxl87rw2FUq833cMo:b-464vbt) ([raw file](https://github.com/robotlocomotion/drake/blob/aaa837677f345cd07921b24ca56ae5c1a03811e2/drake/systems/framework/value.h#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Good eye on the paren, I've added the missing one.

I'm not sure what else is confusing you -- please let me know.
</blockquote></details>

probably it was too late for my brain to parse anything. Looks fine now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6220)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/value.h, line 227 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-KlYtI6csjiRm4PVxXBk:-Kl_BulsV-l1cy-VqzrC:babcg3e) ([raw file](https://github.com/robotlocomotion/drake/blob/63a1763abab68b4686ff2ce916154768ff38970b/drake/systems/framework/value.h#L227)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

This works and looks good to me. I just want to know your opinion on an alternative method:

```c++
  static_assert(!std::is_same<T, std::remove_cv<AbstractValue>::type>::value,
                "T in Value<T> should not be AbstractValue.");
```
</blockquote></details>

Done.

(If I can't find a way to unit test the traits substitution anyway, of course it's better to static_assert.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6220)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6220#-:-Kl_KQf2tV8uFc5rXn8d:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6220)*

**Pull request merged**
