### PR TITLE
Use stx and tinydir from github

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Using `new_local_repository` with a workspace-relative path works alright most of the time but has some sharp edges when used downstream.  For things that are anyway on github, we might as well just download the source archives rather than vendor the files.  (We had avoided this earlier because adding them as git submodules to the CMake superbuild didn't seem worthwhile at the time.)

This also upgrades both to the newest upstream, while we're at it.

Relates #7259.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7723)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/stx/stx.cps, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7723#-L2VSjqniMyR3_xn8Yjk:-L2VSjqniMyR3_xn8Yjl:bln79ra) ([raw file](https://github.com/robotlocomotion/drake/blob/948bc45347fa5c74788e70d735163cfbb43c9e1f/tools/workspace/stx/stx.cps#L10)):*
> ```delphi
>     "stx": {
>       "Type": "interface",
>       "Includes": ["@prefix@/include/stx/include"]
> ```

BTW Use `hdr_strip_prefix` in the `install` to strip the extra `include`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7723)*

**Comment by jwnimmer-tri** [comment]
*[tools/workspace/stx/stx.cps, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7723#-L2VSjqniMyR3_xn8Yjk:-L2VTOC6iP2HF3qa03pw:b-q8mz0y) ([raw file](https://github.com/robotlocomotion/drake/blob/948bc45347fa5c74788e70d735163cfbb43c9e1f/tools/workspace/stx/stx.cps#L10)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Use `hdr_strip_prefix` in the `install` to strip the extra `include`.
</blockquote></details>

Is that preferable?  I wasn't sure which was better.  I'll do that in the next push.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7723)*

**Comment by jamiesnape** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/stx/stx.cps, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7723#-L2VSjqniMyR3_xn8Yjk:-L2VTikook4jiWN3m9-O:bnrls6b) ([raw file](https://github.com/robotlocomotion/drake/blob/948bc45347fa5c74788e70d735163cfbb43c9e1f/tools/workspace/stx/stx.cps#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is that preferable?  I wasn't sure which was better.  I'll do that in the next push.
</blockquote></details>

Marginally, I think, looking at the other externals that we install.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7723)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 9 of 11 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7723#-:-L2VVhcpLqodokspy8Fm:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.  I'll wait until macOS builds pass before merging.

**Comment by jwnimmer-tri** [comment]
Aha, I forgot that in #7022 we edited the vendored file for macOS.  I will have to resolve that first.

**Comment by jwnimmer-tri** [comment]
I've filed tcbrindle/cpp17_headers#12 upstream with the fix, and (hopefully) put a local work-around in place in the meantime.

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 9 of 11 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7723#-:-L2WxMr3C05hWrlXiF5G:bmxilld)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
All passed.

**Pull request merged**
