### PR TITLE
Rename SimpleLqrTrajectoryController to SimpleFeedbackTrajectoryController

### PR DESCRIPTION
**Pull request by sammy-tri**
I've been informed that a time varying LQR controller used for
following a trajectory is a concept with a much more specific meaning,
and this controller is very much not that.  Rename to avoid confusion.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3213)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review, +@sherm1 for platform review

I would normally wait for Jenkins to confirm the build is sane(ish) before asking for review, but it's not kicking this one off in a hurry (and it's pretty small), so let's go ahead and open it up.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3213#-:-KPnhhZQHyx5K47cRTmE:b-vmrgp)*

**Comment by sherm1** [comment]
Platform: :lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3213#-:-KPnpSuY0P4dBjiu0unj:b-nxaeye)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/controllers/simple_feedback_trajectory_controller.h, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3213#-KPrs8nHBLviIIFXWeWH:-KPrs8nItP4DMzlZZg2Q:b6c0v6k) ([raw file](https://github.com/robotlocomotion/drake/blob/aa66e0e4a5cd0715dd255b85a1d6c230d92b8c18/drake/systems/controllers/simple_feedback_trajectory_controller.h#L16)):*
> ```objc
>  * trajectory.
>  *
>  * @concept{system_concept}
> ```

BTW if I understood it right, you are implementing a linear state feedback controller. Consider elaborating a little more in this doxygen description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3213)*

**Comment by sammy-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/simple_feedback_trajectory_controller.h, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3213#-KPrs8nHBLviIIFXWeWH:-KPsG87r43xT25ljrywk:b-2ejpn5) ([raw file](https://github.com/robotlocomotion/drake/blob/aa66e0e4a5cd0715dd255b85a1d6c230d92b8c18/drake/systems/controllers/simple_feedback_trajectory_controller.h#L16)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW if I understood it right, you are implementing a linear state feedback controller. Consider elaborating a little more in this doxygen description.
</details>
Elaborated slightly...  I'm a little wary of using overly specific terminology since that's part of what got me into this mess by calling it an LQR controller.

It does seem to look like a linear state feedback controller, I'm not 100% sure it counts (mostly since I hacked this together out of other bits in the first place, and because I'm having trouble finding a sufficiently precise definition).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3213)*

**Comment by naveenoid** [comment]
:lgtm: 

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/controllers/simple_feedback_trajectory_controller.h, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3213#-KPrs8nHBLviIIFXWeWH:-KPt3xL2a3WdUq-DghYu:b-4vk3vd) ([raw file](https://github.com/robotlocomotion/drake/blob/aa66e0e4a5cd0715dd255b85a1d6c230d92b8c18/drake/systems/controllers/simple_feedback_trajectory_controller.h#L16)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Elaborated slightly...  I'm a little wary of using overly specific terminology since that's part of what got me into this mess by calling it an LQR controller.
> 
> It does seem to look like a linear state feedback controller, I'm not 100% sure it counts (mostly since I hacked this together out of other bits in the first place, and because I'm having trouble finding a sufficiently precise definition).
</details>
BTW (leaving this to be non blocking), alternative choice is to express with an equation in the comments what the controller applies as input, i.e. in the form u = -Kx +  u_traj_poly(t) + K x_traj_poly(t).

I will leave it to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3213#-:-KPt4s2IfUWyT32Dir5C:bg7igkv)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
