### PR TITLE
[geometry] Add python bindings for Meshcat/MeshcatVisualizerCpp

### PR DESCRIPTION
**Pull request by RussTedrake**
Follow-up to #13038.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683#-:-MiMDyFy0mxr93J710Ys:b-t5m2ic)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
(Looked like a download flake, so I retriggered to be sure.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683#-:-MiMPvP21LoKgchCg6Gz:b-6t3ucb)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass. Mostly easy, quick fix things. I did have a question for @ericcousineau-tri about pybind and `shared_ptr`.

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683#-:-MiMalPO5SVpektnW6Ip:b-h8wxfo)* status: 8 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/geometry_py.cc, line 970 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMQNzF6NEUe9LhFlw6:-MiMQNzF6NEUe9LhFlw7:brs3547) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L970)):*
> ```cpp
>         .def(py::init<std::shared_ptr<Meshcat>, MeshcatVisualizerParams>(),
>             py::arg("meshcat"), py::arg("params") = MeshcatVisualizerParams{},
>             // Keep alive, reference: `self` keeps `meshcat` alive.
> ```

Question for @ericcousineau-tri. Given the parameter type for the `meshcat` parameter is `shared_ptr` (pass by value), does pybind11 handle reference counting automatically? In otherwords, is "keep alive" necessary here?

While I can imagine it's quite innocuous on this constructor (as any pybind "keep_alive" behavior would simply shadow the C++ behavior due to the `shared_ptr`), I'd imagine it's a bit different for the `AddToBuilder` APIs. It introduces an *artificial* relationship between `builder` and `meshcat` that we'd like to only introduce if necessary.

As I don't see a lot of `shared_ptr` come through, I'd really appreciate your insight.
___
*[bindings/pydrake/geometry_py.cc, line 1416 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZ3191WjIOd7vIt49:-MiMZ3191WjIOd7vIt4A:bvo4jlb) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1416)):*
> ```cpp
>         .def(py::init<>(), cls_doc.ctor.doc)
>         .def("web_url", &Class::web_url, cls_doc.web_url.doc)
>         .def("ws_url", &Class::ws_url, cls_doc.ws_url.doc)
> ```

Do we want to bind "advanced" methods? Those type of APIs are usually made public for convenience, but we rarely want users to exercise them. Is there a particular workflow that this supports?
___
*[bindings/pydrake/geometry_py.cc, line 1418 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZGGf0ke7ArDerVws:-MiMZGGf0ke7ArDerVwt:bxd56k7) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1418)):*
> ```cpp
>         .def("ws_url", &Class::ws_url, cls_doc.ws_url.doc)
>         .def("SetObject", &Class::SetObject, py::arg("path"), py::arg("shape"),
>             py::arg("rgba") = Rgba(.9, .9, .9, 1.), cls_doc.SetObject.doc)
> ```

BTW I don't know why this didn't occur to me before. But I realized `SetObject` might have been better taking a `GeometryProperties` and then you could arbitrarily expand the data you want to consume. Definitely nothing to do vis a vis this PR, but something to consider for the future. I can imagine it might be more heavyweight than you'd like for shoving in arbitrary visual decorators, but it definitely leaves things infinitely expandable without changing interfaces.
___
*[bindings/pydrake/geometry_py.cc, line 1423 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZlLA-4faoemH9N24:-MiMZlLA-4faoemH9N25:b-wk2be0) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1423)):*
> ```cpp
>         .def("Delete", &Class::Delete, py::arg("path") = "", cls_doc.Delete.doc)
>         .def("SetProperty",
>             py::overload_cast<std::string_view, std::string, double>(
> ```

nit: Copypasta. This should be `bool`.
___
*[bindings/pydrake/geometry_py.cc, line 1449 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiM_-4f6DBBkbEuaZtL:-MiM_-4f6DBBkbEuaZtM:b-oica4c) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1449)):*
> ```cpp
>         .def_readwrite(
>             "prefix", &MeshcatVisualizerParams::prefix, cls_doc.prefix.doc)
>         .def_readwrite("delete_prefix_on_initialization_event",
> ```

nit: I also just noticed that the name change of `DeletePrefix` --> `Delete` left *this* anachronism behind. Can we patch this quickly while binding it?
___
*[bindings/pydrake/test/geometry_test.py, line 376 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMaYBd3lmM7DaM4S36:-MiMaYBd3lmM7DaM4S37:bs6oik9) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/test/geometry_test.py#L376)):*
> ```Python
>                           rgba=mut.Rgba(.5, .5, .5))
>         meshcat.SetTransform(path="/test/box", X_ParentPath=RigidTransform())
>         meshcat.SetProperty(path="/Background",
> ```

nit: Given the error in the bindings on this overload and the ability to implicitly convert types. Can we extend this test to make sure we're *actually* setting a bool and float, respectively?
___
*[bindings/pydrake/test/geometry_test.py, line 382 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiM_OTMD0_PAlApWQrE:-MiM_OTN4PaCL66ORQrR:btq9ii4) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/test/geometry_test.py#L382)):*
> ```Python
>                             property="intensity", value=1.0)
> 
>         # Confirm that I can scalar-convert the visualizer.
> ```

BTW Seems this last paragraph should go into the *next* test. Admittedly, doing so requires dancing around `T` a bit, but given this tests `MeshcatVisualizer`, putting that in the test that *claims* to test `MeshcatVisualizer` seems to be more logical.
___
*[bindings/pydrake/test/geometry_test.py, line 392 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiM_VxI-iMGDkNA5iO8:-MiM_VxI-iMGDkNA5iO9:b-10w8n5) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/test/geometry_test.py#L392)):*
> ```Python
>         meshcat = mut.Meshcat()
>         params = mut.MeshcatVisualizerParams()
>         params.publish_period = 1.0/10.0
> ```

BTW I liked in the C++ test that you picked a value that had an incredibly low probability of being hard-coded. 10Hz feels like it's far more likely to become a default than a period of 0.123 s. It provides only the *smallest* value here so is probably not worth making the change. I just wanted to share the passing thought.
___
*[geometry/meshcat.h, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMa8v463B8nMdq9tp1:-MiMa8v463B8nMdq9tp2:b-qmgx1v) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/geometry/meshcat.h#L135)):*
> ```objc
>   @param value the new value.
> 
>   @pydrake_mkdoc_identifier{bool}
> ```

BTW Two thumbs way up. A very judicious use of characters. It reads so clearly in the bindings.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683)* status: 8 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 970 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMQNzF6NEUe9LhFlw6:-MiNCIKz14SFZnPkruCf:bgkqmc1) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L970)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Question for @ericcousineau-tri. Given the parameter type for the `meshcat` parameter is `shared_ptr` (pass by value), does pybind11 handle reference counting automatically? In otherwords, is "keep alive" necessary here?

While I can imagine it's quite innocuous on this constructor (as any pybind "keep_alive" behavior would simply shadow the C++ behavior due to the `shared_ptr`), I'd imagine it's a bit different for the `AddToBuilder` APIs. It introduces an *artificial* relationship between `builder` and `meshcat` that we'd like to only introduce if necessary.

As I don't see a lot of `shared_ptr` come through, I'd really appreciate your insight.
</blockquote></details>

Correct; `shared_ptr` has lifetime managed appropriately by Python, so keep alive acting upon an argument whose lifetime is directly managed by `shared_ptr` is unnecessary. (Though, TBH, not that harmful.)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 970 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMQNzF6NEUe9LhFlw6:-MiNGsjo8a96VGOuhwDY:bwzagd) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L970)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Correct; `shared_ptr` has lifetime managed appropriately by Python, so keep alive acting upon an argument whose lifetime is directly managed by `shared_ptr` is unnecessary. (Though, TBH, not that harmful.)
</blockquote></details>

Done.  I've removed those keep_alives.
___
*[bindings/pydrake/geometry_py.cc, line 1416 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZ3191WjIOd7vIt49:-MiNAXAz7WCsIcu9TJ68:buf7rpy) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1416)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Do we want to bind "advanced" methods? Those type of APIs are usually made public for convenience, but we rarely want users to exercise them. Is there a particular workflow that this supports?
</blockquote></details>

I consciously did *not* bind them, in the same spirit of not including them in the public documentation.  I've documented the omission.
___
*[bindings/pydrake/geometry_py.cc, line 1418 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZGGf0ke7ArDerVws:-MiNBOgk2dgC7HZmGkml:b38jffe) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1418)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I don't know why this didn't occur to me before. But I realized `SetObject` might have been better taking a `GeometryProperties` and then you could arbitrarily expand the data you want to consume. Definitely nothing to do vis a vis this PR, but something to consider for the future. I can imagine it might be more heavyweight than you'd like for shoving in arbitrary visual decorators, but it definitely leaves things infinitely expandable without changing interfaces.
</blockquote></details>

I thought about a lot of alternatives when I picked this variant, and decided that I still liked having this version, even if turns into sugar for something more general down the line.  I hadn't thought about GeometryProperties.  That could be a good choice.
___
*[bindings/pydrake/geometry_py.cc, line 1423 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZlLA-4faoemH9N24:-MiNBleq6TulzgzrB6YF:b-19zebg) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1423)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Copypasta. This should be `bool`.
</blockquote></details>

Done.  Oops.
___
*[bindings/pydrake/geometry_py.cc, line 1449 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiM_-4f6DBBkbEuaZtL:-MiNCB2QC5OvZhHs6t9q:b-5a4mjs) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1449)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I also just noticed that the name change of `DeletePrefix` --> `Delete` left *this* anachronism behind. Can we patch this quickly while binding it?
</blockquote></details>

Done.  It wasn't actually an omission.  I still sort of like the original better.  But I don't have a strong opinion, and have changed it.
___
*[bindings/pydrake/test/geometry_test.py, line 376 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMaYBd3lmM7DaM4S36:-MiNE6AC6Ps0vM5Pfw_5:b6m0y41) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/test/geometry_test.py#L376)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Given the error in the bindings on this overload and the ability to implicitly convert types. Can we extend this test to make sure we're *actually* setting a bool and float, respectively?
</blockquote></details>

I hear you, but I don't have a good way to do it.  I could shell out to my python client, but that's heavy for the geometry_test.  I think the best path forward is to cover them with examples.  (and secretly, the javascript code is sufficiently untyped so a float could go through and accomplish the same.  i've distinguished the types to avoid those shenanigans in c++, but they aren't strictly necessary.
___
*[bindings/pydrake/test/geometry_test.py, line 382 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiM_OTMD0_PAlApWQrE:-MiNEM7sA4H2dSDkHYu5:bnme5mz) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/test/geometry_test.py#L382)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Seems this last paragraph should go into the *next* test. Admittedly, doing so requires dancing around `T` a bit, but given this tests `MeshcatVisualizer`, putting that in the test that *claims* to test `MeshcatVisualizer` seems to be more logical.
</blockquote></details>

Done.  (by making a new test)
___
*[bindings/pydrake/test/geometry_test.py, line 392 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiM_VxI-iMGDkNA5iO8:-MiNESq74MbjQY4HEPWd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/test/geometry_test.py#L392)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I liked in the C++ test that you picked a value that had an incredibly low probability of being hard-coded. 10Hz feels like it's far more likely to become a default than a period of 0.123 s. It provides only the *smallest* value here so is probably not worth making the change. I just wanted to share the passing thought.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

Still not clear on binding `ws_url()`.

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683#-:-MiNNshE76hadoWvDYup:b-i27nfc)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/geometry_py.cc, line 1416 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZ3191WjIOd7vIt49:-MiNNHAL1e2PNuPOTC_l:b-9964re) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1416)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I consciously did *not* bind them, in the same spirit of not including them in the public documentation.  I've documented the omission.
</blockquote></details>

I was specifically alluding to the fact that `ws_url()` documentation is:

```c++
  /** (Advanced) Returns the ws:// URL for direct connection to the websocket
  interface.  Most users should connect via a browser opened to web_url(). */
```

I.e., `ws_url()` is the "advanced" API that is being bound.
___
*[bindings/pydrake/test/geometry_test.py, line 376 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMaYBd3lmM7DaM4S36:-MiNNYQ70yR0-zoyDoBg:bq3hqwj) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/test/geometry_test.py#L376)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I hear you, but I don't have a good way to do it.  I could shell out to my python client, but that's heavy for the geometry_test.  I think the best path forward is to cover them with examples.  (and secretly, the javascript code is sufficiently untyped so a float could go through and accomplish the same.  i've distinguished the types to avoid those shenanigans in c++, but they aren't strictly necessary.
</blockquote></details>

Right. There's no way to look at the result of `SetProperty` except as it percolates to the visualizer. Good 'nuff.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ggould-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683#-:-MiNO-B6DMQ13xzb0UfQ:bcav8r0)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @RussTedrake)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683#-:-MiNPhthEOyLVOyAEfGO:bnfp4nl)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 1416 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZ3191WjIOd7vIt49:-MiNgQQHC_vFbX5UGag5:b25ie0g) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1416)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I was specifically alluding to the fact that `ws_url()` documentation is:

```c++
  /** (Advanced) Returns the ws:// URL for direct connection to the websocket
  interface.  Most users should connect via a browser opened to web_url(). */
```

I.e., `ws_url()` is the "advanced" API that is being bound.
</blockquote></details>

I see.  There is zero chance of this one doing any harm; it's only returning a const string.  I'd say we leave it?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[bindings/pydrake/geometry_py.cc, line 1416 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZ3191WjIOd7vIt49:-MiNn1rR8Hnn4hx6fb9f:bhwpj8f) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1416)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I see.  There is zero chance of this one doing any harm; it's only returning a const string.  I'd say we leave it?
</blockquote></details>

I'm 100% fine with that. I just wanted to make sure we hadn't done anything undesirable by accident.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15683)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 1416 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15683#-MiMZ3191WjIOd7vIt49:-MiOeh6551Cv_4ArzfQO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5b2177ae46a0d1f6b6829c18dcc991928c6a86/bindings/pydrake/geometry_py.cc#L1416)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm 100% fine with that. I just wanted to make sure we hadn't done anything undesirable by accident.
</blockquote></details>

Done.

**Pull request merged**
