### PR TITLE
Removes hsrb from Drake.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5370)

### CODE REVIEW

**Comment by liangfok** [comment]
Looks like I did not do a clean removal:

```
20:58:39 -- Preparing to build hsrb_description
20:58:39 error: pathspec 'ros/hsrb_description' did not match any file(s) known to git.
20:58:40 error: pathspec 'ros/hsrb_description' did not match any file(s) known to git.
20:58:42 error: pathspec 'ros/hsrb_description' did not match any file(s) known to git.
20:58:47 error: pathspec 'ros/hsrb_description' did not match any file(s) known to git.
20:58:55 error: pathspec 'ros/hsrb_description' did not match any file(s) known to git.
```
Looking into it...

**Comment by jwnimmer-tri** [comment]
I think https://github.com/RobotLocomotion/drake/tree/master/drake/examples/toyota_hsrb also needs to go, and https://github.com/RobotLocomotion/drake/blob/master/CMakeLists.txt#L357.

**Comment by liangfok** [comment]
Thanks. Done. Fingers crossed.

**Comment by jwnimmer-tri** [comment]
:lgtm: assuming CI passes.

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5370#-:-KeBnrthoFeZiQHFuw-H:b-jzb55v)*

**Comment by jwnimmer-tri** [comment]
Still something else missing:
```
control config: /home/ubuntu/workspace/linux-gcc-experimental-matlab/drake/examples/Valkyrie/@Valkyrie/../config/control_config_sim.yaml
Unexpected Standard exception from MEX file.
What() is:Could not add package://hsrb_description to the search path because directory /home/ubuntu/workspace/linux-gcc-experimental-matlab/drake/../ros/hsrb_description does not exist
Error in bipedControllers.InstantaneousQPController (line 23)
```

**Comment by jwnimmer-tri** [comment]
https://github.com/RobotLocomotion/drake/blob/master/drake/examples/examples_package_map.h#L26

**Comment by liangfok** [comment]
I hope I got all of them now.

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5370)*

**Pull request merged**
