### PR TITLE
[sensors] Add lcmt_image_array_to_images output for label images

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #20554.

Towards #18862.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20598)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please.

**Review by zachfang — COMMENTED** [review]
+@zachfang for feature. :lgtm: I will leave @sammy-tri for the platform review.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20598#-:-NkaaF1g-KzdsSQcRpYx:bhw1fin)* status: LGTM missing from assignee sammy-tri(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@jwnimmer-tri did you want to wait for @sammy-tri ?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20598#-:-NlQ0xfi3PXkD9g7HZvF:b1emcw1)* status: LGTM missing from assignee sammy-tri(platform)

**Comment by jwnimmer-tri** [comment]
Tentatively, yes.  He's SME for this file, and the next PR in the train isn't finished yet so it's not actively blocking anything.

**Comment by jwnimmer-tri** [comment]
I'm re-pinging here to ensure it stays in the Reviewable dashboard (by default, 14+ days idle are hidden).

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20598#-:-NnBgCN2BmCjp_3qikdP:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),zachfang

**Pull request merged**
