### PR TITLE
Increase size of Toppra test to prevent failure on mosek builds

### PR DESCRIPTION
**Pull request by mpetersen94**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15824)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-weekly-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-weekly-mosek-debug please

**Comment by ggould-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-weekly-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-weekly-mosek-debug please

**Comment by ggould-tri** [comment]
Oops, those magic words aren't right.  Trying again.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-debug please

**Review by ggould-tri — COMMENTED** [review]
:lgtm: pending CI success.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15824#-:-MkbgGA71kngRa87yrbe:b-8uu7yr)* status: needs at least two assigned reviewers (waiting on @mpetersen94)

**Review by ggould-tri — COMMENTED** [review]
+(status: single reviewer ok)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15824#-:-MkbrVFy0kBi4JAIbIT_:b-9219tc)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @mpetersen94)

**Pull request merged**
