### PR TITLE
Fixed a couple signed / unsigned warnings.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2392)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri  for both feature and platform review please.
You are the official platform reviewer today right?

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Fixed a couple signed / unsigned warnings\.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2392#-:-KI3jcK2S52tcroHbpjV:-468552838)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform and feature.

I am slightly curious how you chose these two (out of the hundreds) to fix, but +1 for incremental progress.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@jwnimmer-tri  for both feature and platform review please.
> You are the official platform reviewer today right?
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2392#-:-KI3lpd_Oe7XH6OZkqKs:-1035925393)*

**Comment by liangfok** [comment]
They were prominently displayed by the Windows compiler output on my machine (2 of 3 warnings). Not sure why all of the others didn't trigger warnings. Maybe the compiler decided they did not need to be recompiled?

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> :lgtm: platform and feature.
> 
> I am slightly curious how you chose these two (out of the hundreds) to fix, but +1 for incremental progress.
> 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2392#-:-KI3mA21Eo-awoGIhBMj:-2038307623)*

**Comment by sherm1** [comment]
:+1:  :lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> They were prominently displayed by the Windows compiler output on my machine (2 of 3 warnings). Not sure why all of the others didn't trigger warnings. Maybe the compiler decided they did not need to be recompiled?
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2392#-:-KI3sOOU3PU4D2cRM9qQ:-2074503637)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to 'out of date with master'.

**Pull request merged**
