### PR TITLE
Make drake::symbolic::Expression::ToPolynomial => ::ToPolynomial

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12950)

### CODE REVIEW

**Comment by soonho-tri** [comment]
from the slack conversation:

> I hope we can deprecate the old one while still inverting the dependency -- by having it delegate to the new one + adding a dummy-and-defaulted template parameter (so the body does not need to compile) with the disclaimer that anyone who calls it need to include polynomial.h also.

@jwnimmer-tri , could you elaborate the "dummy-and-defaulted template parameter" part here? To include `Polynomiald Expression::ToPolynomial()` in `symbolic_expression.h`, I think I need to have `#include "drake/common/polynomial.h"` in `symbolic_expression.h`. Then, we still have the cyclic dependency issue.

**Comment by jwnimmer-tri** [comment]
I was wondering if something like this worked:
```c++
class Expression {
  template <typename Dummy = int>
  auto ToPolynomial(Dummy = {}) { return ::ToPolynomial(*this); }
};
```

I can play with a couple other spellings later tonight, perhaps.

**Comment by jwnimmer-tri** [comment]
The trick is to guide us into dependent name lookup.  This gets the job done; probably a slightly more compact formulation could also work, I didn't push on it.

```patch
diff --git a/common/polynomial.h b/common/polynomial.h
index 542b6d6f1..379abd959 100644
--- a/common/polynomial.h
+++ b/common/polynomial.h
@@ -484,3 +484,13 @@ typedef Eigen::Matrix<Polynomiald, Eigen::Dynamic, 1> VectorXPoly;
  * @pre e.is_polynomial() is true.
  */
 Polynomiald ToPolynomial(const drake::symbolic::Expression& e);
+
+namespace drake {
+namespace symbolic {
+namespace internal {
+inline Polynomiald ToPolynomial(const drake::symbolic::Expression& e, const ToPolynomialHelperTag&) {
+ return ::ToPolynomial(e);
+}
+}
+}
+}
diff --git a/common/symbolic_expression.h b/common/symbolic_expression.h
index 740daaaf6..21803bcb3 100644
--- a/common/symbolic_expression.h
+++ b/common/symbolic_expression.h
@@ -37,6 +37,15 @@
 namespace drake {
 
 namespace symbolic {
+class Expression;
+
+namespace internal {
+struct ToPolynomialHelperTag {};
+template <typename Dummy>
+auto ToPolynomialHelper(const Expression& e, const Dummy&) {
+  return ToPolynomial(e, Dummy{});
+}
+}  // namespace internal
 
 /** Kinds of symbolic expressions. */
 enum class ExpressionKind {
@@ -230,11 +239,11 @@ class Expression {
   /** Checks if this symbolic expression is convertible to Polynomial. */
   bool is_polynomial() const;
 
-  // /** Returns a Polynomial representing this expression.
-  //  *  Note that the ID of a variable is preserved in this translation.
-  //  *  \pre{is_polynomial() is true.}
-  //  */
-  // Polynomiald ToPolynomial() const;
+  // DRAKE_DEPRECATED("2020-07-01", "...")
+  template <typename Dummy = internal::ToPolynomialHelperTag>
+  auto ToPolynomial() const {
+    return internal::ToPolynomialHelper<Dummy>(*this, Dummy{});
+  }
 
   /** Evaluates using a given environment (by default, an empty environment) and
    * a random number generator. If there is a random variable in this expression
diff --git a/common/test/symbolic_expression_test.cc b/common/test/symbolic_expression_test.cc
index 655a40275..17908d87f 100644
--- a/common/test/symbolic_expression_test.cc
+++ b/common/test/symbolic_expression_test.cc
@@ -588,7 +588,7 @@ TEST_F(SymbolicExpressionTest, ToPolynomial2) {
       e_uf_};
   for (const Expression& e : test_vec) {
     EXPECT_FALSE(e.is_polynomial());
-    EXPECT_THROW(ToPolynomial(e), runtime_error);
+    EXPECT_THROW(e.ToPolynomial(), runtime_error);
   }
 }
 
```

**Comment by soonho-tri** [comment]
+@RussTedrake for platform-review, please!

**Pull request merged**
