### PR TITLE
Rename doc/README.txt to doc/README.md

### PR DESCRIPTION
**Pull request by oh-tarnished**
Renamed the docs readme. simple commit

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20051)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Could explain why a rename is desirable here?

Our website generator (Jekyll) publishes `*.md` files onto our website as generated html.  This README is documentation about the website build infrastructure, and should not itself appear on the website.  So to me, we must no use `*.md` for this file.

**Comment by oh-tarnished** [comment]
Well for people who are reading the documentation on `GitHub` it's easier to do it in README.md since GitHub allows it inside and outside the folder to render that html page. 

Solution for Jekyll to exclude this file 

https://idratherbewriting.com/documentation-theme-jekyll/mydoc_exluding_files.html

**Review by jwnimmer-tri — COMMENTED** [review]
Fair points, thanks.

:lgtm: +(status: single reviewer ok) +(release notes: none).

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20051#-:-NcikqW-8iIABk9C6sUO:bhhr1k4)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-documentation please

**Pull request merged**
