### PR TITLE
Bring in all the changes from DRC drake

### PR DESCRIPTION
**Pull request by rdeits**
There are a ton of lines changed here, but most of them are just organizational changes (especially the separation of all of the mex-specific c++ functions into new files). I'll be interested to see what the build servers have to say about it.

### CODE REVIEW

**Comment by tkoolen** [comment]
I'm taking a look at the compile errors on OSX right now.

**Comment by tkoolen** [comment]
Done. See https://github.com/rdeits/drake/pull/11/

**Comment by tkoolen** [comment]
I can take a look at Windows later as well.

**Comment by tkoolen** [comment]
See https://github.com/rdeits/drake/pull/13 for the MSVC fixes.

**Comment by tkoolen** [comment]
@rdeits, you might want to accept https://github.com/rdeits/drake/pull/12 as well, which should at least fix the error on drake006 shown in the build log (there may be more, but I wasn't able to reproduce on my machine).

**Comment by tkoolen** [comment]
Tracked down the errors in the Windows build by ssh'ing into drake003. Looks like the errors are:
```
..\..\..\..\systems\plants\test\testIKpointwise.cpp(28): error C3861: 'nan': identifier not found
```
and
```
..\..\..\..\systems\plants\test\testIKtraj.cpp(69): error C3861: 'nan': identifier not found
..\..\..\..\systems\plants\test\testIKtraj.cpp(70): error C3861: 'nan': identifier not found
..\..\..\..\systems\plants\test\testIKtraj.cpp(72): error C3861: 'nan': identifier not found
..\..\..\..\systems\plants\test\testIKtraj.cpp(73): error C3861: 'nan': identifier not found
```
It's weird that I didn't get those on my end.

For linux, I forgot to add a <cmath> include in drakeFloatingPointUtil while adding isNormal

I'll fix those and do another pull request.

**Comment by tkoolen** [comment]
* Ubuntu: @rdeits, could you look at the Ubuntu build? Just like you, I can't reproduce the build errors on my machine.
* OSX: do we trust drake001 at this point? Everything compiles fine on my machine.
* Windows: I find the current way of figuring out what drake003 is complaining about quite frustrating. I have to ssh into drake003, then figure out which build directory corresponds to this pull request based on modification date. I'm not even sure if I'm looking at the right directory right now, since there are two builds on July 3 and I don't see a way to tell which one is the right one. The source in the two build folders for July 3 doesn't appear to have my latest fixes included. Last I checked the branch compiles fine on my machine under Windows; I'll check again in a minute.

**Comment by tkoolen** [comment]
Yup, still compiles on Windows on my machine.

**Comment by RussTedrake** [comment]
drake001 is ok, but gets stuck occasionally.  i've just kicked it and put this pull request back into the queue.  

agreed that the windows machines are a pain.  they were a pain to set up this well, :)  and could certainly be set up better.

**Comment by RussTedrake** [comment]
sigh.  maybe drake001 is more hosed than normal. 

i just made a small change to the build server logic that should make the directory clear for the make errors. (it was reported clearly for unit test errors, but I didn't realize i was reporting the drake-distro directory instead of the drake directory for the make errors.  that should be resolved now.)

**Comment by RussTedrake** [comment]
am working to merge this one.  will reopen it from my own fork (where I can push minor compiler fixes).

**Pull request closed without merging**
