### PR TITLE
Move test helper code into //drake/common/test_utilities

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We had about three or four different ways of phrasing where common test utilities live.  This consolidates them down to one way.

This commit only encompasses the relocation and renaming.  It does not attempt to prune or otherwise abbreviate the deps in BUILD files.

The important changes here are in `//drake/common/...` and `//tools/...`.  The other changes are chaff.  Chaff changes to files named `*test.cc` were fully automated.  Other chaff fixups were manual.

One could imagine keeping an `eigen_matrix_compare.h` deprecation stub in place, so that cross-merged PRs are less likely to break.  I'm not sure whether its worth it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7064)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@ggould-tri ; I wasn't getting anything accomplished this afternoon anyway :-/

---

Review status: 0 of 226 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7064#-:-KuVtcOmMRIIfmySoVKD:brrs4ip)*

**Comment by ggould-tri** [comment]
:lgtm: with one issue below.

---

Reviewed 237 of 237 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/BUILD, line 516 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7064#-KuVvCYKXkRUPmVhFyAp:-KuVvCYKXkRUPmVhFyAq:bp78bkr) ([raw file](https://github.com/robotlocomotion/drake/blob/2263e0ea9a3305993ebc932c6669e146b9a07262/drake/common/BUILD#L516)):*
> ```Python
> )
> 
> # XXX
> ```

FYI -- this is not an adequate comment.  Please be descriptive of the defect and/or use TODO syntax.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7064#-:-KuVyrf7ACLxrseCeDAF:b-d2srp3)*

**Comment by jwnimmer-tri** [comment]
Review status: 222 of 226 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/BUILD, line 516 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7064#-KuVvCYKXkRUPmVhFyAp:-KuW1PaQMtiJSjOnZccS:bc6np1n) ([raw file](https://github.com/robotlocomotion/drake/blob/2263e0ea9a3305993ebc932c6669e146b9a07262/drake/common/BUILD#L516)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- this is not an adequate comment.  Please be descriptive of the defect and/or use TODO syntax.
</blockquote></details>

Oops, I meant to finish some work here before push.  PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7064)*

**Comment by ggould-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7064)*

**Comment by jwnimmer-tri** [comment]
Ah.  I need to self-bless the :car: emoji.

**Pull request merged**
