### PR TITLE
Set a CMake Default build type when one is not defined.

### LINKED ISSUE #2803: add_mex is not working on my mac
yet another one.  this happens on a completely clean build on master on my home laptop:

```
[ 21%] Linking CXX shared module /Users/russt/drake-distro/drake/util/barycentricInterpolation.mexmaci64
Undefined symbols for architecture x86_64:
  "_mexErrMsgIdAndTxt", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
  "_mexPrintf", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
  "_mxCreateDoubleMatrix_730", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
  "_mxCreateNumericMatrix_730", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
  "_mxGetCell_730", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
  "_mxGetData", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
  "_mxGetM", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
  "_mxGetN", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
  "_mxGetNumberOfElements", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
  "_mxGetPr", referenced from:
      _mexFunction in barycentricInterpolation.cpp.o
```

because (with VERBOSE=1) it's not actually linking in the matlab libs
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -Werror=all -Werror=ignored-qualifiers -DGTEST_DONT_DEFINE_FAIL=1 -DGTEST_DONT_DEFINE_SUCCEED=1 -DGTEST_DONT_DEFINE_TEST=1 -bundle -Wl,-headerpad_max_install_names  -o /Users/russt/drake-distro/drake/util/barycentricInterpolation.mexmaci64 CMakeFiles/barycentricInterpolation.dir/barycentricInterpolation.cpp.o  -L/Users/russt/drake-distro/build/drake/lib  -L/Users/russt/drake-distro/build/install/lib
```

if it helps, the only occurence of the mex libraries I could find were:
```
drake008% more CMakeCache.txt| grep -i libmex
Matlab_MEX_LIBRARY:FILEPATH=/Applications/MATLAB_R2015b.app/bin/maci64/libmex.dylib
FIND_PACKAGE_MESSAGE_DETAILS_Matlab:INTERNAL=[/Applications/MATLAB_R2015b.app/extern/include][/Applications/MATLAB_R2015b.app/bin/maci64/libmex.dylib][mexmaci64][/Applications/MATLAB_R2015b.app][cfound components:  MAIN_PROGRAM ][v8.6()]
```

### LINKED ISSUE #2830: On Ubuntu 14.04, can CMake automatically default to `CXX=g++4.9` and etc?
On Ubuntu 14.04, can Drake's superbuild CMake automatically default to `CXX=g++4.9` and related (`CC`, fortran, etc.) if they are not explicitly set by the environment (and/or if the as-invoked default is too old; and/or are not already in the cache)?

The documentation and instructions to set up `CXX` are error-prone and annoying to users.  I've had two different teams try to use `update-alternatives` to make it move convenient, with the obvious disastrous results.

I tried googling for this a month ago, seemed like it was difficult, and so gave up.  But perhaps Kitware has a solution at-hand.

### PR DESCRIPTION
**Pull request by jhoare**
Fixes #2803 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2807)

### CODE REVIEW

**Comment by liangfok** [comment]
Just one minor comment. :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2807#-KMdoGnQZKJbPTkPoyQZ:-KMdoGnQZKJbPTkPoyQ_:-117341729) ([raw file](https://github.com/robotlocomotion/drake/blob/5d12099457d5cd5b830cab4f70abf18b6ccc3b76/CMakeLists.txt#L19)):*
> ```CMake
> if(NOT CMAKE_BUILD_TYPE)
>   set(CMAKE_BUILD_TYPE "Release" CACHE STRING
>     "Choose the type of build, options are: Debug Release RelWithDebInfo MinSizeRel."
> ```

BTW, the above sentence is imperative. Is it actually commanding the user to select the build type? Or, is it simply stating a fact?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2807#-:-KMdoNKSqLB9CHOUOa_F:-614093673)*

**Comment by RussTedrake** [comment]
Thank you.  Will review when i get to the computer.  I believe that the old logic would have been in the first few lines of the pods makefiles.  Can you please look to see if this is consistent and if there are any other flags there that have been thrown out with the bathwater?

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2807#-KMe14qY4w8KUd7XGG_C:-KMe14qY4w8KUd7XGG_D:-642401707) ([raw file](https://github.com/robotlocomotion/drake/blob/5d12099457d5cd5b830cab4f70abf18b6ccc3b76/CMakeLists.txt#L18)):*
> ```CMake
> # Set Default build type to Release if none specified
> if(NOT CMAKE_BUILD_TYPE)
>   set(CMAKE_BUILD_TYPE "Release" CACHE STRING
> ```

BTW, I prefer "RelWithDebInfo" as a default because it runs at full speed but provides better information when disasters occur. "Release" builds are smaller but obfuscated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2807)*

**Comment by jhoare** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[CMakeLists.txt, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2807#-KMe14qY4w8KUd7XGG_C:-KMe6GMl2zVHi88ZktP3:-87033610) ([raw file](https://github.com/robotlocomotion/drake/blob/5d12099457d5cd5b830cab4f70abf18b6ccc3b76/CMakeLists.txt#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I prefer "RelWithDebInfo" as a default because it runs at full speed but provides better information when disasters occur. "Release" builds are smaller but obfuscated.
</details>
I agree and was going to make that default, but the old pod Makefile set it as Release if no build type was defined, so I mimicked that behavior. I'll let Russ decide if we should leave as Release or change to RelWithDebInfo. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2807)*

**Comment by RussTedrake** [comment]
I’m inclined to stick with Release.  Do we know what assertions are enabled/disabled in Eigen for RelWithDebInfo?

**Comment by jhoare** [comment]
CI Failure was due to submission failure to cdash...

@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
> Do we know what assertions are enabled/disabled in Eigen for RelWithDebInfo?

RelWithDebInfo defines `NDEBUG` the same as Release and normally performs the same optimizations (that's overrideable by us in CMake). It is ABI-compatible with Release builds so can be mixed in (unlike Debug). AFAIK, the only difference is that it stores names in the object files so that you can get meaningful stack traces and poke around in the debugger.

**Comment by jhoare** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2807#-KMdoGnQZKJbPTkPoyQZ:-KMe_lIB-2pk0mCiOS2U:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5d12099457d5cd5b830cab4f70abf18b6ccc3b76/CMakeLists.txt#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, the above sentence is imperative. Is it actually commanding the user to select the build type? Or, is it simply stating a fact?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2807)*

**Comment by david-german-tri** [comment]
:lgtm: confirmed working on my Mac locally with a make build as follows:

```
mkdir build
cd build
cmake ..
make
```

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2807#-:-KMeahef_HSJf6MqL9xI:-852798869)*

**Comment by david-german-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2807#-KMe14qY4w8KUd7XGG_C:-KMearUj_1kz6QIPbOjl:559043116) ([raw file](https://github.com/robotlocomotion/drake/blob/5d12099457d5cd5b830cab4f70abf18b6ccc3b76/CMakeLists.txt#L18)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> I agree and was going to make that default, but the old pod Makefile set it as Release if no build type was defined, so I mimicked that behavior. I'll let Russ decide if we should leave as Release or change to RelWithDebInfo. 
</details>
@sherm1, I'd like to get this PR in as quickly as possible, since it's blocking for various users.  Can we stick with Release for now and consider RelWithDebInfo in a separate change?  It's pretty easy for individual developers to override.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2807)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2807#-:-KMegaIQBUlVxGxZpx9e:-1868698381)*

**Comment by david-german-tri** [comment]
Please don't merge this until @RussTedrake signs off.

Russ, I looked at the PODs makefile as you requested, and this is the only flag that has a default value there.

https://github.com/RobotLocomotion/drake/blob/master/drake/Makefile#L8

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CMakeLists.txt, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2807#-KMe14qY4w8KUd7XGG_C:-KMf49qCT6HIG1v2ynnM:1094189467) ([raw file](https://github.com/robotlocomotion/drake/blob/5d12099457d5cd5b830cab4f70abf18b6ccc3b76/CMakeLists.txt#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> @sherm1, I'd like to get this PR in as quickly as possible, since it's blocking for various users.  Can we stick with Release for now and consider RelWithDebInfo in a separate change?  It's pretty easy for individual developers to override.
</details>
OK either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2807)*

**Comment by RussTedrake** [comment]
tested and confirmed.

**Pull request merged**
