### PR TITLE
Tighten joint limits when the parent link is fixed.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Impose a linear constraint to represent the joint limit, when the parent link is fixed to the world.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6757)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@gizatt for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6757#-:-Kq_6a-akrfvgoWBHS5F:biagjkq)*

**Comment by gizatt** [comment]
Just one thing below, really simple and clean! Not sure about the Jenkins fail though?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/global_inverse_kinematics.cc, line 590 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6757#-KqaDLQ4zQKvrsgeEPoW:-KqaDLQ5dGEuYa0KTMUU:bcse46s) ([raw file](https://github.com/robotlocomotion/drake/blob/747982bd076064177c411dd0d678e7f2255a3b77/drake/multibody/global_inverse_kinematics.cc#L590)):*
> ```cpp
>                 AddLinearConstraint(R_joint_beta_trace >=
>                                         1 + 2 * joint_bound_cos &&
>                                     R_joint_beta_trace <= 3);
> ```

While it certainly makes the documentation more clear and complete, isn't `trace(R) <= 3` redundant with other constraints already added (primarily -1 <= R <= 1 elementwise)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6757#-:-KqaDrcNnkmZTyL0rWap:b-gg5uuo)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/global_inverse_kinematics.cc, line 590 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6757#-KqaDLQ4zQKvrsgeEPoW:-KqaFn_5ig1owefjkt2F:b-ku6gi) ([raw file](https://github.com/robotlocomotion/drake/blob/747982bd076064177c411dd0d678e7f2255a3b77/drake/multibody/global_inverse_kinematics.cc#L590)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

While it certainly makes the documentation more clear and complete, isn't `trace(R) <= 3` redundant with other constraints already added (primarily -1 <= R <= 1 elementwise)?
</blockquote></details>

Yes you are right. `R_joint_beta = [R_WP * R_PF * R(k, (a+b)/2)]ᵀ * R_WC` , as explained in the documentation above. Here only `R_WC`, the orientation of the child link, is a decision variable. So the entries in `R_joint_beta` are not actually decision variables; instead they are expressions of decision variables. Thus we do not have constraint that `-1 <= R_joint_beta(i, j) <= 1` automatically.

I can add the constraint `-1 <= R_joint_beta(i, j) <= 1`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6757)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/global_inverse_kinematics.cc, line 590 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6757#-KqaDLQ4zQKvrsgeEPoW:-Kqcuy5YNVNUAui5owBi:bxv39ud) ([raw file](https://github.com/robotlocomotion/drake/blob/747982bd076064177c411dd0d678e7f2255a3b77/drake/multibody/global_inverse_kinematics.cc#L590)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes you are right. `R_joint_beta = [R_WP * R_PF * R(k, (a+b)/2)]ᵀ * R_WC` , as explained in the documentation above. Here only `R_WC`, the orientation of the child link, is a decision variable. So the entries in `R_joint_beta` are not actually decision variables; instead they are expressions of decision variables. Thus we do not have constraint that `-1 <= R_joint_beta(i, j) <= 1` automatically.

I can add the constraint `-1 <= R_joint_beta(i, j) <= 1`.
</blockquote></details>

Just realized that `R_joint_beta(i, j)` is guaranteed to be within [-1, 1], with our other constraint on `R_WC`. Removed the redundant constraint `-1 <= R_joint_beta(i, j) <= 1` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6757)*

**Comment by gizatt** [comment]
Assuming tests are good, :lgtm:!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/global_inverse_kinematics.cc, line 590 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6757#-KqaDLQ4zQKvrsgeEPoW:-KqcvJSdOT3m0YRIBS1w:b-4hvi0z) ([raw file](https://github.com/robotlocomotion/drake/blob/747982bd076064177c411dd0d678e7f2255a3b77/drake/multibody/global_inverse_kinematics.cc#L590)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just realized that `R_joint_beta(i, j)` is guaranteed to be within [-1, 1], with our other constraint on `R_WC`. Removed the redundant constraint `-1 <= R_joint_beta(i, j) <= 1` here.
</blockquote></details>

Got it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6757#-:-KqcvPqRG2VsaZOlrybF:bk270pz)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6757#-:-Kqd0DKZg5WtHWhU7V_U:b-vt9vbo)*

**Comment by soonho-tri** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6757#-:-Kqd39WrX6_Uass8NHtk:bg7igkv)*

**Pull request merged**
