### PR TITLE
[manipulation_station] Optionally publish point clouds in sim

### LINKED ISSUE #14985: Add minimal LCM point_cloud support
Drake ships `drake-visualizer` with the ability to display point clouds, but the feature is untested and actually does not even have a demo inside of Drake.  (We do have several uses of it in TRI's Anzu projects.)

In order for Drake reviewers to test PRs that affect this feature, we need some minimal demo within Drake.  My proposal is to extend the `examples/manipulation_station/mock_mock_station_simulation` to offer the ability to publish LCM point clouds.

We already have the ability to convert images into clouds (`drake/perception/depth_image_to_point_cloud`).  We just need to write the lcm encoder system ([see prototype](https://github.com/lukaslaobeyer/drake/commits/feature/drake_pcl_to_lcm_pcl)), and then cascade it all together inside the demo, under a gflag.  Possibly we'll run into #12125 but we can TODO that for now.

At the same time, I plan to add a new `lcmt_point_cloud` message to Drake.  We should not be using the unlicensed bot_core message for point clouds; its use in Drake is deprecated and will be removed soon (per #14362).  Also, the `points[n][3]` storage order for `bot_core.point_cloud_t` is extremely inefficient; the replacement will be ~`points[3][n]`~ _based on PCL's PointCloud2_.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Patch drake_visualizer to show Drake point clouds.

Resolves #14985 towards #14362.

~Requires #14982 and #14990 first.~

Screenshot at https://github.com/RobotLocomotion/drake/issues/14985#issuecomment-830468107.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI would be able to feature review, please?  I think the most relevant changes here are to the visualizer plug-in.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14991#-MbxD3lc8EhqGfAg9yLB:-MbxD3lc8EhqGfAg9yLC:b1fw5xq) (no related file):*
Working: Testing locally:
```
$ bazel build //examples/manipulation_station:mock_station_simulation //tools:drake_visualizer
# Terminal 1
$ bazel-bin/tools/drake_visualizer
# Terminal 2
$ bazel-bin/examples/manipulation_station/mock_station_simulation --publish_point_cloud=true
```

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14991#-MbxD3lc8EhqGfAg9yLB:-MbxFx9n0zD8oPlJ0qO8:bp0rujf) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Testing locally:
```
$ bazel build //examples/manipulation_station:mock_station_simulation //tools:drake_visualizer
# Terminal 1
$ bazel-bin/tools/drake_visualizer
# Terminal 2
$ bazel-bin/examples/manipulation_station/mock_station_simulation --publish_point_cloud=true
```
</blockquote></details>

I can reproduce the image here:
https://github.com/RobotLocomotion/drake/issues/14985#issuecomment-830468107

However, the intersection of these points at valid (non-red?) values (a) do not agree with the rendered 3d models and (b) do not agree with each other.

That leads me to be believe that the transforms for these cameras are wrong.
e.g. the background color (blue) should *not* be projected onto the cabinet.


This is either a bug with this PR, or existing code?

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14991#-MbxD3lc8EhqGfAg9yLB:-MbxG9ml3wTT3A0e4dHl:b-n0396m) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I can reproduce the image here:
https://github.com/RobotLocomotion/drake/issues/14985#issuecomment-830468107

However, the intersection of these points at valid (non-red?) values (a) do not agree with the rendered 3d models and (b) do not agree with each other.

That leads me to be believe that the transforms for these cameras are wrong.
e.g. the background color (blue) should *not* be projected onto the cabinet.


This is either a bug with this PR, or existing code?
</blockquote></details>

Soz, I forgot to delete "(non-red?)". Please ignore that part.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14991#-MbxD3lc8EhqGfAg9yLB:-MbxGmfm-8QnpLxWSMqd:b-psspbq) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Soz, I forgot to delete "(non-red?)". Please ignore that part.
</blockquote></details>

Oops, I meant to cite #12125 here but I must have forgotten.

Where would be a good place to put that -- the gflag description for `--publish_point_cloud` maybe?

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14991#-MbxD3lc8EhqGfAg9yLB:-McAVbdDD-Jb13UDvpsH:btahpet) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, I meant to cite #12125 here but I must have forgotten.

Where would be a good place to put that -- the gflag description for `--publish_point_cloud` maybe?
</blockquote></details>

Eh, anywhere is fine for me.

It's hard to qualitatively review this PR with the pre-existing defect, but will try. May also apply small patch so I have non-lying point clouds.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14991#-MbxD3lc8EhqGfAg9yLB:-McAYnFm1BxB7DVb6jVb:b-6iu5no) (no related file):*
K, qualitative review with #15186 as a patch looks good!
> 

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14991#-MbxD3lc8EhqGfAg9yLB:-McAYxw_4E38M-nghklL:b-dly4y) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

K, qualitative review with #15186 as a patch looks good!
> 

</blockquote></details>

Working

See below for the new gflags comment.   (I'll wait to re-push until other review changes are due.)

```console
  Flags from examples/manipulation_station/mock_station_simulation.cc:
...
    -publish_point_cloud (Whether to publish point clouds to LCM.  Note that
      per issue https://github.com/RobotLocomotion/drake/issues/12125 the
      simulated point cloud data will have registration errors.) type: bool
      default: false
...
```

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with some minor nits

> Reviewed 4 of 6 files at r3, 4 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991#-:-McA_Ua89rvXoCujVHWh:bpxr2va)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14991#-MbxD3lc8EhqGfAg9yLB:-McAZByw0QSubyCFfDql:b-q5ox15) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

See below for the new gflags comment.   (I'll wait to re-push until other review changes are due.)

```console
  Flags from examples/manipulation_station/mock_station_simulation.cc:
...
    -publish_point_cloud (Whether to publish point clouds to LCM.  Note that
      per issue https://github.com/RobotLocomotion/drake/issues/12125 the
      simulated point cloud data will have registration errors.) type: bool
      default: false
...
```
</blockquote></details>

OK Looks good per gflags! I think it should be in one more place, will comment elsewhere to that effect.

---
___
*[examples/manipulation_station/manipulation_station.h, line 71 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McAZI5n4Z4MejA9EtX_:-McAZI5o46N8706Rx9nH:b-kwan90) ([raw file](https://github.com/robotlocomotion/drake/blob/a42ce845585a5a0fb85b086af7c51ace15c34064/examples/manipulation_station/manipulation_station.h#L71)):*
> ```objc
> /// - camera_[NAME]_depth_image
> /// - <b style="color:orange">camera_[NAME]_label_image</b>
> /// - <b style="color:orange">camera_[NAME]_point_cloud</b>
> ```

nit Can you add the same warning regarding this port?
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, line 27 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McAZV2E9_Ky6x1Le3dx:-McAZV2E9_Ky6x1Le3dy:b-rdh1iu) ([raw file](https://github.com/robotlocomotion/drake/blob/a42ce845585a5a0fb85b086af7c51ace15c34064/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py#L27)):*
> ```Python
>         if msg.flags != lcmt_point_cloud.IS_STRICTLY_FINITE:
>             return
>         fields = (
> ```

nit This is a 4-tuple and meaning wasn't declared until later (though only a few lines).

Consider using `namedtuple`.
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, line 48 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McA_-h21yMlrB3H7v_q:-McA_-h21yMlrB3H7v_r:b-lq48f9) ([raw file](https://github.com/robotlocomotion/drake/blob/a42ce845585a5a0fb85b086af7c51ace15c34064/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py#L48)):*
> ```Python
>         points = np.frombuffer(msg.data, dtype=np.float32)
>         points.shape = (-1, 4)
>         xyz = np.delete(points, 3, 1)
> ```

nit Unclear why usages of `np.delete` is better than keeping original memory and taking a slice? (alias)

Then you don't need to do `del` or any fancy memory mgmt.
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, line 50 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McAZhGY-TRRpF-TXvq3:-McAZhGZCFD9cdHKlTI7:b-kbs4lq) ([raw file](https://github.com/robotlocomotion/drake/blob/a42ce845585a5a0fb85b086af7c51ace15c34064/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py#L50)):*
> ```Python
>         xyz = np.delete(points, 3, 1)
>         rgba_float = np.delete(points, range(3), 1)
>         del points
> ```

nit Usage of `del` doesn't seem merited for sake of memory management.

If you wish to downscope memory usage, consider using a separate function?
At a minimum, comment as to usage of `del`.

**Comment by jwnimmer-tri** [comment]
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, line 48 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McA_-h21yMlrB3H7v_q:-McAaRL2Ab5Ew_sjUqZ9:b136rji) ([raw file](https://github.com/robotlocomotion/drake/blob/a42ce845585a5a0fb85b086af7c51ace15c34064/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why usages of `np.delete` is better than keeping original memory and taking a slice? (alias)

Then you don't need to do `del` or any fancy memory mgmt.
</blockquote></details>

I didn't find the np method that allowed me to alias.  If you can point in the right direction, I'll look into it.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, line 48 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McA_-h21yMlrB3H7v_q:-McAdtIz3eHc-0EWlqXr:b-7y6sg9) ([raw file](https://github.com/robotlocomotion/drake/blob/a42ce845585a5a0fb85b086af7c51ace15c34064/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I didn't find the np method that allowed me to alias.  If you can point in the right direction, I'll look into it.
</blockquote></details>

I believe slicing will alias the existing memory, e.g.
```
xyz = points[:3, :]
rgba = points[3:, :].view(np.uint8)
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[examples/manipulation_station/manipulation_station.h, line 71 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McAZI5n4Z4MejA9EtX_:-McAg6Xj68HKW_81qKfH:bpw41qf) ([raw file](https://github.com/robotlocomotion/drake/blob/a42ce845585a5a0fb85b086af7c51ace15c34064/examples/manipulation_station/manipulation_station.h#L71)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add the same warning regarding this port?
</blockquote></details>

Done (below).
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, line 48 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McA_-h21yMlrB3H7v_q:-McAfQmj3UJN3VeOs8wI:be4uwiv) ([raw file](https://github.com/robotlocomotion/drake/blob/a42ce845585a5a0fb85b086af7c51ace15c34064/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I believe slicing will alias the existing memory, e.g.
```
xyz = points[:3, :]
rgba = points[3:, :].view(np.uint8)
```
</blockquote></details>

OK It didn't seem to like an astype of a view.  (`ValueError: new type not compatible with array.`)

I added slicing where it worked, though.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule (tomorrow), please.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 14 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, line 48 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McA_-h21yMlrB3H7v_q:-McArUXY05Z0NWoAn309:b-ieyay5) ([raw file](https://github.com/robotlocomotion/drake/blob/a42ce845585a5a0fb85b086af7c51ace15c34064/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK It didn't seem to like an astype of a view.  (`ValueError: new type not compatible with array.`)

I added slicing where it worked, though.
</blockquote></details>

OK Sweet, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 9 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 6 files at r3, 3 of 14 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991#-:-McG2l_uDhRYasmeEPQ6:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, line 7 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McG165G49ja1QMRqcj1:-McG165H97DH7u1eINka:b-pp0ky1) ([raw file](https://github.com/robotlocomotion/drake/blob/aca4c59ec466345fffdde57957d32324014dfc91/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py#L7)):*
> ```Python
> 
> from director import lcmUtils
> from director import applogic
> ```

BTW does the order of import between lcmUtils and applogic matter? can we alpha-sort imports in this stanza?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14991)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, line 7 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14991#-McG165G49ja1QMRqcj1:-McG3Qus2lPpryt4wWAs:b-vk1d6n) ([raw file](https://github.com/robotlocomotion/drake/blob/aca4c59ec466345fffdde57957d32324014dfc91/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW does the order of import between lcmUtils and applogic matter? can we alpha-sort imports in this stanza?
</blockquote></details>

Hmm, this is pasta taken from _all_ of the other builtin scripts also doing it wrong.  Changing the order will require manual retesting, so I'm going to merge this commit now and then fix this and all of the other plugins (with manual testing of each) in a follow-up.

**Pull request merged**
