### PR TITLE
[geometry/render_gltf_client] Add integration test for RPC pipeline

### LINKED ISSUE #15921: RenderRpc: Integration test between RenderEngineRpcClient and VtkRpcServer
The integration test between RenderEngineRpcClient and VtkRpcServer. The rendered images from the new RPC pipeline should be lossless comparing to the ones from RenderEngineVtk.

### PR DESCRIPTION
**Pull request by zachfang**
Close #15921

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079)

### CODE REVIEW

**Comment by zachfang** [comment]
@jwnimmer-tri I think this is my implementation based on what we discussed. I ended up doing all the image differencing using `PIL` and `Numpy`, and the actual comparisons for `depth` and `label` images are close to pixel-perfect (precisely the same given a reasonable per-pixel threshold).

However, the comparison of color images is not quite straightforward. They are obviously different even from a visual inspection. I wonder if it makes sense to include that for the test.
Screenshot from 2022-10-11 14-37-39

I will CC\ @SeanCurtis-TRI as well if you like to weigh in. Thanks!

**Comment by jwnimmer-tri** [comment]
As I recall, the metric we'd proposed for image comparison was something like "80% of the pixels are within 80% of the right color value".  Maybe you need to change that to "90% are within 50%" but there's probably _some_ threshold that would pass.  I think we _do_ want to fail on completely-wrong (e.g., all-black) images.

**Review by SeanCurtis-TRI — COMMENTED** [review]
FTR This is very concerning to me. Without doing full image diffs, I see deviation is wholly attributable to whether an object is *textured*. The objects on the left seem to match perfectly across the two images. The objects on the right don't match. So, it's not a system wide difference (e.g., different ambient light or some such thing). Somehow, colored objects are instantiated identically, but textured objects are not. That localized disparity feels like a noteworthy issue.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079#-:-NEBrAv84TTTygOwrYm0:b-sbgdte)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Comment by zachfang** [comment]
Thanks for the input. I will go back and check the rendering for textured/untextured objects.

This is the per-channel difference for the color images (without masking or anything).
Screenshot from 2022-10-12 12-04-38

**Review by jwnimmer-tri — COMMENTED** [review]
First pass completed.

I think we should merge the test infrastructure as-is, even with those differences.  (Capture ground and hold it.)

If there needs to be a follow-up to fix bugs and tighten up the allowed tolerances, so be it.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079#-:-NECaVWG1g52MlgePi77:b-wp5pnd)* status: 12 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @zachfang)

___
*[`geometry/render_gltf_client/BUILD.bazel` line 293 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECZQlN5DdFlFuw5hyF:-NECZQlN5DdFlFuw5hyG:bbricua) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/BUILD.bazel#L293)):*
> ```Starlark
>     data = [
>         ":client_demo",
>         ":server_vtk_backend",
> ```

nit I think this `data` (vtk_backend) might be spurious?  It's never directly mentioned by the source code of this test; it's only an indirect dependency which should already be provided by virtue of depending on the `:server_demo`.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECZqre8LMmHriZek0N:-NECZqre8LMmHriZek0O:b-kgm2r1) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L9)):*
> ```Python
> each image type and an overall percentage threshold for invalid pixels.
> 
> Two images are considered close enough if 90% of the pixels are within the
> ```

nit My gut feeling is that trying to document the specific thresholds in the file overview here will bitrot as we tune the named constants below over time.  What do you think about removing this first sentence?



_Code quote:_
```Python
90%
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECe1UZ5CYzSBnswssa:-NECe1UZ5CYzSBnswssb:b-v0l0ci) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L28)):*
> ```Python
> DEPTH_PIXEL_THRESHOLD = 0.001  # Depth measurement tolerance in meters.
> LABEL_PIXEL_THRESHOLD = 0
> INVALID_PIXEL_PERCENTAGE = 0.1
> ```

nit This is a dimensionless fraction, not a "percentage".  (A percentage would be 10.0, i.e., scaled 0..100.)
___
*[`geometry/render_gltf_client/test/integration_test.py` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NEC_HQPAR1ZuMeot_JU:-NEC_HQPAR1ZuMeot_JV:b-wq2r66) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L33)):*
> ```Python
> 
> 
> def run_server(host="127.0.0.1", port=8000):
> ```

A hard-coded port number here is likely to cause spurious failures in CI.

The ideal approach would be to ask Flask to bind to any free port, and then tell us which one is chose.

Does it offer any API to do that?
___
*[`geometry/render_gltf_client/test/integration_test.py` line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NEC_qvSBOZmlM8WrrJd:-NEC_qvSBOZmlM8WrrJe:b-nosvo9) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L45)):*
> ```Python
> 
>     def tearDown(self):
>         if self.server_proc is not None:
> ```

It's not clear to me how this could ever be `None`?  It's never set to None anywhere.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECaG2ND3_ald5WFRtV:-NECaG2ND3_ald5WFRtW:bxxleu7) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L64)):*
> ```Python
>             client_demo,
>             "--render_engine",
>             "vtk",
> ```

nit The readability of this test function is suffering due to the vertical decompression.

For starters, we don't need two lines per flag.



_Suggestion:_
```Python
            "--render_engine=vtk",
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECaqVG9rav6o8SAURI:-NECaqVG9rav6o8SAURJ:bhx1sdc) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L70)):*
> ```Python
>             vtk_dir,
>         ]
>         subprocess.run(vtk_args)
> ```

nit When using `subprocess.run`, always pass the `check=...` kwarg so that it's clear to the reader whether or not we're going to ignore errors.

In this case, it doesn't seem like we should be ignoring errors.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECaQdo-_c-Fpam-w3U:-NECaQdp5H_o44G78ZM0:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L77)):*
> ```Python
>             "0.1",
>             "--save_dir",
>             client_dir,
> ```

nit



_Suggestion:_
```Python
            f"--save_dir={client_dir}",
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECb6TH2D8zBqtmHvh9:-NECb6TH2D8zBqtmHvhA:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L89)):*
> ```Python
> 
>         # Group images with the same index number for comparison, e.g.,
>         # color_00.png, depth_000.tiff, and label_000.png.
> ```

typo



_Suggestion:_
```Python
color_000
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECbZkECRayBod1AB9m:-NECbZkECRayBod1AB9n:b-h3m8dk) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L101)):*
> ```Python
>             )
>             client_image_sets.append(client_image_set)
> ```

The features of the above code are like so:
- create a render-specific output tmpdir
- run the demo using that renderer
- find the non-zero set of output image filenames

However, we're duplicated that logic twice with a "client" vs "vtk" prefix on it and interwoven the two.  That's both difficult to read and to maintain.

We should have a helper function something like `generate_demo_images` that takes the renderer name as as argument, and returns the set of image filenames, and just call it twice.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECdRftAN0ezq-UJIYG:-NECdRftAN0ezq-UJIYH:b-5letl) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L119)):*
> ```Python
>             )
>             color_diff_percentage = (
>                 np.count_nonzero(color_diff) / color_diff.size
> ```

nit The "count_nonzero / size" logic is duplicated 3 times.  Especially with the parenthesis-and-newline splatter (which I assume is from pyblack?), it's too difficult to follow along this way, and thus should be factored out into helper function.

The function could even encapsulate the assert if you like, i.e.,
```
self.assert_pixel_errors_less(color_diff, INVALID_PIXEL_FRACTION)
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECdBJ7BPZ93GfRQcC7:-NECdBJ7BPZ93GfRQcC8:bmhkbqs) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L121)):*
> ```Python
>                 np.count_nonzero(color_diff) / color_diff.size
>             )
>             self.assertTrue(color_diff_percentage < INVALID_PIXEL_PERCENTAGE)
> ```

nit Use `assertLess(a, b)` not `assertEqual(a < b)`, so that unittest will print out the numbers upon a failure.

Ditto throughout.



_Code quote:_
```Python
assertTrue
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079)* status: 13 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @zachfang)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECrFR72-p7k49Yto6o:-NECrFR72-p7k49Yto6p:bqubggu) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L94)):*
> ```Python
>         for index in range(min(vtk_file_number, client_file_number) // 3):
>             vtk_image_set = sorted(
>                 glob.glob(os.path.join(vtk_dir, f"*{index:03d}*"))
> ```

The globbing here ("give me whatever you happened to spit out") doesn't make any sense to me.

We know _exactly_ what the filenames are going to be, and we can hard-code exactly how many to expect (e.g., `2`).  (It's fine if the demo produces more than we expected; we only need to check some of them.)

We should be able to loop over the frame number range and load _exactly_ the file pathnames we want to compare, no searching/globbing required.

**Review by zachfang — COMMENTED** [review]
Addressed most of the comments and fixed a bug for the uint8 calculation.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079#-:-NE7XGZk5A8L7QwAFtqE:b-d3x7as)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECZqre8LMmHriZek0N:-NECj8VjBIckgHw0kVm1:b-10kuwf) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit My gut feeling is that trying to document the specific thresholds in the file overview here will bitrot as we tune the named constants below over time.  What do you think about removing this first sentence?
</blockquote></details>

Would changing from a specific number to `the majority of the pixels` be better?



_Code quote:_
```Python
per-pixel threshold.  The ground truth images are generated by RenderEngineVtk.
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECe1UZ5CYzSBnswssa:-NECh4rX50S2CT-cJLMU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is a dimensionless fraction, not a "percentage".  (A percentage would be 10.0, i.e., scaled 0..100.)
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NEC_qvSBOZmlM8WrrJd:-NEChcgt-qats6YfoJbs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's not clear to me how this could ever be `None`?  It's never set to None anywhere.
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECaqVG9rav6o8SAURI:-NECtKyq5stUcq1vB9Q0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit When using `subprocess.run`, always pass the `check=...` kwarg so that it's clear to the reader whether or not we're going to ignore errors.

In this case, it doesn't seem like we should be ignoring errors.
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECrFR72-p7k49Yto6o:-NED3Z8TEsC0Qh3BbPxe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L94)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The globbing here ("give me whatever you happened to spit out") doesn't make any sense to me.

We know _exactly_ what the filenames are going to be, and we can hard-code exactly how many to expect (e.g., `2`).  (It's fine if the demo produces more than we expected; we only need to check some of them.)

We should be able to loop over the frame number range and load _exactly_ the file pathnames we want to compare, no searching/globbing required.
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECbZkECRayBod1AB9m:-NECtRPX7QPL1zBeiC6t:bhefik2) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L101)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The features of the above code are like so:
- create a render-specific output tmpdir
- run the demo using that renderer
- find the non-zero set of output image filenames

However, we're duplicated that logic twice with a "client" vs "vtk" prefix on it and interwoven the two.  That's both difficult to read and to maintain.

We should have a helper function something like `generate_demo_images` that takes the renderer name as as argument, and returns the set of image filenames, and just call it twice.
</blockquote></details>

Done with the consolidation.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NECdRftAN0ezq-UJIYG:-NED-820ASLFxLyL0tRK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L119)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The "count_nonzero / size" logic is duplicated 3 times.  Especially with the parenthesis-and-newline splatter (which I assume is from pyblack?), it's too difficult to follow along this way, and thus should be factored out into helper function.

The function could even encapsulate the assert if you like, i.e.,
```
self.assert_pixel_errors_less(color_diff, INVALID_PIXEL_FRACTION)
```
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 111 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED3CiE3yTWDtliP20W:-NED3CiE3yTWDtliP20X:bp39kg3) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L111)):*
> ```Python
>             color_diff = (
>                 np.absolute(
>                     vtk_color.astype(float) - client_color.astype(float)
> ```

FYI, this is added as the previous calculation for uint8 color images is overflow and wrong (and thus the visualization).

**Comment by zachfang** [comment]
After fixing the uint8 overflow bug, this is the correct image differencing for color images.
Screenshot from 2022-10-12 16-52-14

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079#-:-NED6nFq1t-IAjRaFHzh:b-n37teh)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @zachfang)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED6K5r6jCfjpXAnShI:-NED6K5s7sm3MXQ9o-5Z:bfc6hzn) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L47)):*
> ```Python
>         self.server_proc.kill()
> 
>     def render_demo_images(self, renderer):
> ```

nit Needs a docstring.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED4b0G-G4Xejmx0lfF:-NED4b0G-G4Xejmx0lfG:bawfl6t) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L49)):*
> ```Python
>     def render_demo_images(self, renderer):
>         tmp_dir = os.path.join(
>             os.environ.get("TEST_TMPDIR", "/tmp"), f"{renderer}"
> ```

nit No need for fstring.



_Suggestion:_
```Python
renderer
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 64 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED41dN49M4JNlFw-Zo:-NED41dN49M4JNlFw-Zp:b-5krl4u) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L64)):*
> ```Python
>         ]
>         proc = subprocess.run(render_args, check=True)
>         self.assertEqual(proc.returncode, 0)
> ```

nit The returncode check is superfluous given `check=True` just above.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED56av91CVFyFKbcAE:-NED56av91CVFyFKbcAF:b-za87g) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L70)):*
> ```Python
>         # for inspection.
>         rendered_file_number = len(os.listdir(tmp_dir))
>         self.assertTrue(
> ```

I'm not sure I buy this test condition.

We already have a hard-coded list of file names below.  If any of those files are absent, then we'll get a (nice) error message explaining so later on when we try to open it and it's not there.  If we wanted to, we could check here that all of the files exist, but I think the error later on is probably sufficient.

So the _only_ thing we're checking for here is whether they are any _extra_ files, and in particular that there are "== 0 mod 3" of them.  Is that an important fact to check about the demo program?  It's doesn't seem very RPC-relevant.

If anything, I could buy a check that all of the filenames in the tmp_dir match a specific pattern `(color|depth_label)_NNN.(png|tiff)`.  I could live with that -- at least it makes _sense_ -- but I would probably err on the side of leaving it out until we find such kinds of bugs in our demo program.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 85 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED6GGR1iIP0FQtBI7n:-NED6GGR1iIP0FQtBI7o:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L85)):*
> ```Python
>         return image_sets
> 
>     def assert_error_fraction_less(self, image_diff, fration):
> ```

typo



_Suggestion:_
```Python
fraction
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED6Xrm7Tm5CkxQ1Z_A:-NED6XrnCsNFhoHosghc:b-kgkxqe) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L96)):*
> ```Python
>             vtk_image_sets, client_image_sets
>         ):
>             # Load the images and convert them to numpy arrays with float data
> ```

nit This comment appears to be inaccurate, given the "uint8" conversion comment down below.



_Code quote:_
```Python
arrays with float data
```

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NEC_HQPAR1ZuMeot_JU:-NEEEBwR-P0EMQf-JARh:bu0pdoe) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

A hard-coded port number here is likely to cause spurious failures in CI.

The ideal approach would be to ask Flask to bind to any free port, and then tell us which one is chose.

Does it offer any API to do that?
</blockquote></details>

I don't think Flask provides a way to find an available port, so one suggests finding a free port by binding to `0`. Another approach is to iterate through a range of ports and try-catch the error, which is less ideal, in my opinion.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED6K5r6jCfjpXAnShI:-NEE1gg80IHD_qiUVYzl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Needs a docstring.
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED56av91CVFyFKbcAE:-NEE1HvREhf-uLRbYeDC:b-50yue3) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure I buy this test condition.

We already have a hard-coded list of file names below.  If any of those files are absent, then we'll get a (nice) error message explaining so later on when we try to open it and it's not there.  If we wanted to, we could check here that all of the files exist, but I think the error later on is probably sufficient.

So the _only_ thing we're checking for here is whether they are any _extra_ files, and in particular that there are "== 0 mod 3" of them.  Is that an important fact to check about the demo program?  It's doesn't seem very RPC-relevant.

If anything, I could buy a check that all of the filenames in the tmp_dir match a specific pattern `(color|depth_label)_NNN.(png|tiff)`.  I could live with that -- at least it makes _sense_ -- but I would probably err on the side of leaving it out until we find such kinds of bugs in our demo program.
</blockquote></details>

Done. Removed the test statement.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NED6Xrm7Tm5CkxQ1Z_A:-NEDycHm3s4WibVFDcvJ:b-6vsk08) ([raw file](https://github.com/robotlocomotion/drake/blob/07d2a70c17d8fcaf65990c44a63910f800a09529/geometry/render_gltf_client/test/integration_test.py#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This comment appears to be inaccurate, given the "uint8" conversion comment down below.
</blockquote></details>

Done. The comment was addressing an intermediate change.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079)* status: needs at least two assigned reviewers (waiting on @zachfang)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18079#-NEC_HQPAR1ZuMeot_JU:-NEEOHwS7SO0lvx2AzGE:bkmpvnj) ([raw file](https://github.com/robotlocomotion/drake/blob/fd9fc365fbaeacce2f9790bb01a2e08bc372af62/geometry/render_gltf_client/test/integration_test.py#L33)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

I don't think Flask provides a way to find an available port, so one suggests finding a free port by binding to `0`. Another approach is to iterate through a range of ports and try-catch the error, which is less ideal, in my opinion.
</blockquote></details>

I posted a fixup at https://github.com/zachfang/drake/pull/4

Assuming that a just-closed port can be immediately rebound without error is still a race condition that may lead to CI flakes under load.

We can obtain the flask port number from its stdout.

**Review by SeanCurtis-TRI — COMMENTED** [review]
There we go! That's the diff I would've expected to see. The other confused me.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079#-:-NEGbFAOEJINMij5-Bn_:b-t2xxbn)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @zachfang)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079)* status: needs at least two assigned reviewers (waiting on @zachfang)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18079#-:-NEHc14Q-ZXEmcXBd5I_:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @zachfang)

**Pull request merged**
