### PR TITLE
simulator: Add test to track heap hygiene

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #14543, #14802

This is the beginning of a PR train to make heapless simulation
possible, with careful system construction.  All the good ideas are
inspired by @edrumwri's PR #14707; all the sketchy ones are mine.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14900)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
FYI @edrumwri feel free to comment if you have time.
+@joemasterjohn for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14900#-:-MYAwsDp6uPQsRqQ-dqO:b1bfzw0)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with one small suggestion.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14900#-:-MYBYdWQ1mPyoMKuvxBu:b-ul6xck)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[systems/analysis/test/simulator_test.cc, line 1145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14900#-MYBYVj3CVByWpECQoyz:-MYBYVj4A9oqXUtBwN_d:b-4ercie) ([raw file](https://github.com/robotlocomotion/drake/blob/76a12bd7d22d38dda83c99be6fa35e827afdeb05/systems/analysis/test/simulator_test.cc#L1145)):*
> ```cpp
>     simulator.AdvanceTo(1.0);
>     simulator.AdvanceTo(2.0);
>     simulator.AdvanceTo(3.0);
> ```

nit: for completion you could put an `simulator. AdvancePendingEvents()` here.

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14900)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[systems/analysis/test/simulator_test.cc, line 1138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14900#-MYBYntL-9RvFLWFyADt:-MYBYntL-9RvFLWFyADu:b-16tvtu) ([raw file](https://github.com/robotlocomotion/drake/blob/76a12bd7d22d38dda83c99be6fa35e827afdeb05/systems/analysis/test/simulator_test.cc#L1138)):*
> ```cpp
>   // Create a Simulator and use it to advance time until t=3*h.
>   Simulator<double> simulator(*diagram);
>   simulator
> ```

nit: weird formatting here

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14900)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[systems/analysis/test/simulator_test.cc, line 1136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14900#-MYBZjLxApOi2GoaQ_WB:-MYBZjLxApOi2GoaQ_WC:b-mf2ivg) ([raw file](https://github.com/robotlocomotion/drake/blob/76a12bd7d22d38dda83c99be6fa35e827afdeb05/systems/analysis/test/simulator_test.cc#L1136)):*
> ```cpp
>   auto diagram = builder.Build();
> 
>   // Create a Simulator and use it to advance time until t=3*h.
> ```

nit: just until t=3, you're not setting a fixed time step on an integrator here or anything.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14900)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

___
*[systems/analysis/test/simulator_test.cc, line 1136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14900#-MYBZjLxApOi2GoaQ_WB:-MYBmQUKCNduZ79qcype:byg13nx) ([raw file](https://github.com/robotlocomotion/drake/blob/76a12bd7d22d38dda83c99be6fa35e827afdeb05/systems/analysis/test/simulator_test.cc#L1136)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: just until t=3, you're not setting a fixed time step on an integrator here or anything.
</blockquote></details>

I suppose that's true, but all the AdvanceTo() calls thrash heap, at least at this stage.
___
*[systems/analysis/test/simulator_test.cc, line 1145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14900#-MYBYVj3CVByWpECQoyz:-MYBn1nfAOa8rc_bliwy:bgwjlsv) ([raw file](https://github.com/robotlocomotion/drake/blob/76a12bd7d22d38dda83c99be6fa35e827afdeb05/systems/analysis/test/simulator_test.cc#L1145)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: for completion you could put an `simulator. AdvancePendingEvents()` here.
</blockquote></details>

Added to the heap count, but that's probably worth looking into anyway. Thanks!

**Review by rpoyner-tri — COMMENTED** [review]
+@soonho-tri for platform review; Wednesday schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14900#-:-MYBpwp87kgiKwpxBqyn:bubf200)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @joemasterjohn and @soonho-tri)

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14900)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

___
*[systems/analysis/test/simulator_test.cc, line 1136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14900#-MYBZjLxApOi2GoaQ_WB:-MYBryEk2j8JQP5cCgFx:b-1mwexi) ([raw file](https://github.com/robotlocomotion/drake/blob/76a12bd7d22d38dda83c99be6fa35e827afdeb05/systems/analysis/test/simulator_test.cc#L1136)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I suppose that's true, but all the AdvanceTo() calls thrash heap, at least at this stage.
</blockquote></details>

Sorry for the confusion. I just meant in your comment you have `t=3*h` and it should just be `t=3`.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14900#-:-MYF0A3N5HySEPNigBW5:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),joemasterjohn (waiting on @rpoyner-tri)

**Pull request merged**
