### PR TITLE
MultibodyPlant methods to retrieve actuated joints

### LINKED ISSUE #18956: Function to report actuated joints
From [comment](https://github.com/RobotLocomotion/drake/issues/12778#issuecomment-1459059775) in #12778.

The request is to implement a function `MultibodyPlant::GetActuatedJointIndices(ModelInstanceIndex)`  that reports actuated joints associated with a model instance.

Quoting here:

> I noticed that Drake MultibodyPlant has a function Mbp::GetJointIndices(ModelInstanceIndex) that returns a vector of all joint indices associated with the given model instance.
> 
> Would it make sense to make a GetActuatedJointIndices(...) version of this method that will return a list of only the actuated joints associated with a model instance? Since there appears to be no convenience method for returning the list of all actuated joint names for a model instance, I think this method would make it much easier to set states of closed loop kinematic chains where only a subset of its joints are actuated.
> 
> I also do not see anything in the multibody::Joint class documentation that allows users to query if a joint is actuated, which would permit me to loop over all regular joint indices and set states for the joints that have joint actuators attached.

cc'ing @yu-fz

### PR DESCRIPTION
**Pull request by amcastro-tri**
closes #18956

cc'ing @yu-fz 

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
-@joemasterjohn 

+@sammy-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-:-NQ1tKHzDKrP47tjdN2U:b-ivftae)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

+@xuchenhan-tri for platform review (I'm scheduled for tomorrow)

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-:-NQS-aU44L8_4shDFpmU:b-x6a3z)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @sammy-tri and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-:-NQS412q11e2qe0aBn5m:b-cxwtpw)* status: 3 unresolved discussions (waiting on @amcastro-tri, @sammy-tri, and @xuchenhan-tri)

___
*[`multibody/tree/multibody_tree.h` line 614 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli:-NQS2K06B7e2iJXCUllj:bsmggis) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.h#L614)):*
> ```objc
>   // See MultibodyPlant method.
>   int num_actuators(ModelInstanceIndex model_instance) const {
>     DRAKE_MBT_THROW_IF_NOT_FINALIZED();
> ```

BTW, this snake_case function violates our naming convention as it calls a CamelCase function. It also appears to violate the rule on inline. https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions
With that in mind, probably best to keep the style in sync with the function below.
___
*[`multibody/tree/multibody_tree.cc` line 447 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS4WpaD-utCZMYeqTV:-NQS4WpaD-utCZMYeqTW:b68ndov) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.cc#L447)):*
> ```cpp
> std::vector<JointActuatorIndex> MultibodyTree<T>::GetJointActuatorIndices(
>     ModelInstanceIndex model_instance) const {
>   return model_instances_.at(model_instance)->GetJointActuatorIndices();
> ```

BTW, do we want to guard against invalid ModelInstanceIndex like some of the other tree functions do?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959)* status: 1 unresolved discussion (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`multibody/tree/multibody_tree.h` line 614 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli:-NQVXghiC2xRLwaP6-BL:b-t8f2zo) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.h#L614)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this snake_case function violates our naming convention as it calls a CamelCase function. It also appears to violate the rule on inline. https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions
With that in mind, probably best to keep the style in sync with the function below.
</blockquote></details>

ah, good point. Probably the right solution is to make the call in `DRAKE_MBT_THROW` be `snake_case`.
But, what do you suggest for this PR?
___
*[`multibody/tree/multibody_tree.cc` line 447 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS4WpaD-utCZMYeqTV:-NQVYQes554u7CYLdRPK:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.cc#L447)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, do we want to guard against invalid ModelInstanceIndex like some of the other tree functions do?
</blockquote></details>

Done

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959)* status: 1 unresolved discussion (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`multibody/tree/multibody_tree.h` line 614 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli:-NQV_OwTEvox07VRwaZ4:b-6ztj53) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.h#L614)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ah, good point. Probably the right solution is to make the call in `DRAKE_MBT_THROW` be `snake_case`.
But, what do you suggest for this PR?
</blockquote></details>

Reading the style guide I found this comment to be interesting:
"Drake's assertion-like macros DRAKE_DEMAND, DRAKE_ASSERT, and DRAKE_THROW_UNLESS are carefully crafted with an eye to object code size and therefore are valid to call within an inline function. "

However, browsing through the implementation for `DRAKE_THROW_UNLESS`, nothing seems to indicate (to me) that our `MultibodyTree<T>::ThrowIfFinalized()` would generate more object code. Am I missing something here? I wonder if we could optimize our `ThrowIfFinalized()` or simply update the docs to state that it is performant enough to use within `snake_case` functions.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959)* status: 1 unresolved discussion (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`multibody/tree/multibody_tree.h` line 614 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli:-NQWCdBa4jR8T081lJpg:b-cpugn7) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.h#L614)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Reading the style guide I found this comment to be interesting:
"Drake's assertion-like macros DRAKE_DEMAND, DRAKE_ASSERT, and DRAKE_THROW_UNLESS are carefully crafted with an eye to object code size and therefore are valid to call within an inline function. "

However, browsing through the implementation for `DRAKE_THROW_UNLESS`, nothing seems to indicate (to me) that our `MultibodyTree<T>::ThrowIfFinalized()` would generate more object code. Am I missing something here? I wonder if we could optimize our `ThrowIfFinalized()` or simply update the docs to state that it is performant enough to use within `snake_case` functions.
</blockquote></details>

This is the object code for the drake internal throw (used by DRAKE_THROW_UNLESS):
```
0000000000000000 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold>:
   0:	bf 10 00 00 00       	mov    $0x10,%edi
   5:	e8 00 00 00 00       	callq  a <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xa>
   a:	48 8d bd 10 fe ff ff 	lea    -0x1f0(%rbp),%rdi
  11:	48 8d b5 58 fe ff ff 	lea    -0x1a8(%rbp),%rsi
  18:	49 89 c5             	mov    %rax,%r13
  1b:	e8 00 00 00 00       	callq  20 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x20>
  20:	4c 8d a5 30 fe ff ff 	lea    -0x1d0(%rbp),%r12
  27:	48 8b b5 10 fe ff ff 	mov    -0x1f0(%rbp),%rsi
  2e:	48 8d 95 0f fe ff ff 	lea    -0x1f1(%rbp),%rdx
  35:	4c 89 e7             	mov    %r12,%rdi
  38:	e8 00 00 00 00       	callq  3d <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x3d>
  3d:	4c 89 e6             	mov    %r12,%rsi
  40:	4c 89 ef             	mov    %r13,%rdi
  43:	e8 00 00 00 00       	callq  48 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x48>
  48:	48 8b 05 00 00 00 00 	mov    0x0(%rip),%rax        # 4f <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x4f>
  4f:	48 8b bd 30 fe ff ff 	mov    -0x1d0(%rbp),%rdi
  56:	48 83 c0 10          	add    $0x10,%rax
  5a:	49 89 45 00          	mov    %rax,0x0(%r13)
  5e:	48 8d 85 40 fe ff ff 	lea    -0x1c0(%rbp),%rax
  65:	48 39 c7             	cmp    %rax,%rdi
  68:	74 05                	je     6f <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x6f>
  6a:	e8 00 00 00 00       	callq  6f <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x6f>
  6f:	48 8b bd 10 fe ff ff 	mov    -0x1f0(%rbp),%rdi
  76:	48 8d 85 20 fe ff ff 	lea    -0x1e0(%rbp),%rax
  7d:	48 39 c7             	cmp    %rax,%rdi
  80:	74 05                	je     87 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x87>
  82:	e8 00 00 00 00       	callq  87 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x87>
  87:	48 8b 15 00 00 00 00 	mov    0x0(%rip),%rdx        # 8e <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x8e>
  8e:	48 8b 35 00 00 00 00 	mov    0x0(%rip),%rsi        # 95 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x95>
  95:	4c 89 ef             	mov    %r13,%rdi
  98:	e8 00 00 00 00       	callq  9d <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0x9d>
  9d:	f3 0f 1e fa          	endbr64 
  a1:	49 89 c4             	mov    %rax,%r12
  a4:	4c 89 ff             	mov    %r15,%rdi
  a7:	e8 00 00 00 00       	callq  ac <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xac>
  ac:	4c 89 e7             	mov    %r12,%rdi
  af:	e8 00 00 00 00       	callq  b4 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xb4>
  b4:	f3 0f 1e fa          	endbr64 
  b8:	48 8b bd 30 fe ff ff 	mov    -0x1d0(%rbp),%rdi
  bf:	48 89 c3             	mov    %rax,%rbx
  c2:	48 8d 85 40 fe ff ff 	lea    -0x1c0(%rbp),%rax
  c9:	48 39 c7             	cmp    %rax,%rdi
  cc:	74 05                	je     d3 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xd3>
  ce:	e8 00 00 00 00       	callq  d3 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xd3>
  d3:	48 8b bd 10 fe ff ff 	mov    -0x1f0(%rbp),%rdi
  da:	48 8d 85 20 fe ff ff 	lea    -0x1e0(%rbp),%rax
  e1:	48 39 c7             	cmp    %rax,%rdi
  e4:	74 05                	je     eb <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xeb>
  e6:	e8 00 00 00 00       	callq  eb <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xeb>
  eb:	4c 89 ef             	mov    %r13,%rdi
  ee:	49 89 dc             	mov    %rbx,%r12
  f1:	e8 00 00 00 00       	callq  f6 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xf6>
  f6:	eb ac                	jmp    a4 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xa4>
  f8:	f3 0f 1e fa          	endbr64 
  fc:	48 89 c3             	mov    %rax,%rbx
  ff:	eb d2                	jmp    d3 <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xd3>
 101:	f3 0f 1e fa          	endbr64 
 105:	48 89 c3             	mov    %rax,%rbx
 108:	eb e1                	jmp    eb <_ZN5drake8internal5ThrowEPKcS2_S2_i.cold+0xeb>
```

And this is for MbT::ThrowIfNotFinalized:
```
0000000000000000 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc>:
   0:	f3 0f 1e fa          	endbr64 
   4:	55                   	push   %rbp
   5:	48 89 e5             	mov    %rsp,%rbp
   8:	41 56                	push   %r14
   a:	41 55                	push   %r13
   c:	41 54                	push   %r12
   e:	53                   	push   %rbx
   f:	48 83 c4 80          	add    $0xffffffffffffff80,%rsp
  13:	64 48 8b 04 25 28 00 	mov    %fs:0x28,%rax
  1a:	00 00 
  1c:	48 89 45 d8          	mov    %rax,-0x28(%rbp)
  20:	31 c0                	xor    %eax,%eax
  22:	80 bf 68 02 00 00 00 	cmpb   $0x0,0x268(%rdi)
  29:	74 21                	je     4c <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x4c>
  2b:	48 8b 45 d8          	mov    -0x28(%rbp),%rax
  2f:	64 48 33 04 25 28 00 	xor    %fs:0x28,%rax
  36:	00 00 
  38:	75 0d                	jne    47 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x47>
  3a:	48 83 ec 80          	sub    $0xffffffffffffff80,%rsp
  3e:	5b                   	pop    %rbx
  3f:	41 5c                	pop    %r12
  41:	41 5d                	pop    %r13
  43:	41 5e                	pop    %r14
  45:	5d                   	pop    %rbp
  46:	c3                   	retq   
  47:	e8 00 00 00 00       	callq  4c <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x4c>
  4c:	bf 10 00 00 00       	mov    $0x10,%edi
  51:	48 89 b5 68 ff ff ff 	mov    %rsi,-0x98(%rbp)
  58:	4c 8d b5 70 ff ff ff 	lea    -0x90(%rbp),%r14
  5f:	e8 00 00 00 00       	callq  64 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x64>
  64:	48 8b b5 68 ff ff ff 	mov    -0x98(%rbp),%rsi
  6b:	4c 89 f7             	mov    %r14,%rdi
  6e:	49 89 c4             	mov    %rax,%r12
  71:	e8 00 00 00 00       	callq  76 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x76>
  76:	4c 8d 6d 90          	lea    -0x70(%rbp),%r13
  7a:	4c 89 f2             	mov    %r14,%rdx
  7d:	48 8d 35 00 00 00 00 	lea    0x0(%rip),%rsi        # 84 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x84>
  84:	4c 89 ef             	mov    %r13,%rdi
  87:	e8 00 00 00 00       	callq  8c <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x8c>
  8c:	4c 8d 75 b0          	lea    -0x50(%rbp),%r14
  90:	48 8d 15 00 00 00 00 	lea    0x0(%rip),%rdx        # 97 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x97>
  97:	4c 89 ee             	mov    %r13,%rsi
  9a:	4c 89 f7             	mov    %r14,%rdi
  9d:	e8 00 00 00 00       	callq  a2 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xa2>
  a2:	4c 89 f6             	mov    %r14,%rsi
  a5:	4c 89 e7             	mov    %r12,%rdi
  a8:	e8 00 00 00 00       	callq  ad <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xad>
  ad:	48 8b 7d b0          	mov    -0x50(%rbp),%rdi
  b1:	48 8d 45 c0          	lea    -0x40(%rbp),%rax
  b5:	48 39 c7             	cmp    %rax,%rdi
  b8:	74 05                	je     bf <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xbf>
  ba:	e8 00 00 00 00       	callq  bf <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xbf>
  bf:	48 8b 7d 90          	mov    -0x70(%rbp),%rdi
  c3:	48 8d 45 a0          	lea    -0x60(%rbp),%rax
  c7:	48 39 c7             	cmp    %rax,%rdi
  ca:	74 05                	je     d1 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xd1>
  cc:	e8 00 00 00 00       	callq  d1 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xd1>
  d1:	48 8b bd 70 ff ff ff 	mov    -0x90(%rbp),%rdi
  d8:	48 8d 45 80          	lea    -0x80(%rbp),%rax
  dc:	48 39 c7             	cmp    %rax,%rdi
  df:	74 05                	je     e6 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xe6>
  e1:	e8 00 00 00 00       	callq  e6 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xe6>
  e6:	48 8b 15 00 00 00 00 	mov    0x0(%rip),%rdx        # ed <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xed>
  ed:	48 8b 35 00 00 00 00 	mov    0x0(%rip),%rsi        # f4 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xf4>
  f4:	4c 89 e7             	mov    %r12,%rdi
  f7:	e8 00 00 00 00       	callq  fc <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0xfc>
  fc:	f3 0f 1e fa          	endbr64 
 100:	48 89 c3             	mov    %rax,%rbx
 103:	eb 39                	jmp    13e <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x13e>
 105:	48 8b 7d b0          	mov    -0x50(%rbp),%rdi
 109:	48 8d 45 c0          	lea    -0x40(%rbp),%rax
 10d:	48 39 c7             	cmp    %rax,%rdi
 110:	74 05                	je     117 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x117>
 112:	e8 00 00 00 00       	callq  117 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x117>
 117:	48 8b 7d 90          	mov    -0x70(%rbp),%rdi
 11b:	48 8d 45 a0          	lea    -0x60(%rbp),%rax
 11f:	48 39 c7             	cmp    %rax,%rdi
 122:	74 05                	je     129 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x129>
 124:	e8 00 00 00 00       	callq  129 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x129>
 129:	48 8b bd 70 ff ff ff 	mov    -0x90(%rbp),%rdi
 130:	48 8d 45 80          	lea    -0x80(%rbp),%rax
 134:	48 39 c7             	cmp    %rax,%rdi
 137:	74 05                	je     13e <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x13e>
 139:	e8 00 00 00 00       	callq  13e <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x13e>
 13e:	4c 89 e7             	mov    %r12,%rdi
 141:	e8 00 00 00 00       	callq  146 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x146>
 146:	48 89 df             	mov    %rbx,%rdi
 149:	e8 00 00 00 00       	callq  14e <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x14e>
 14e:	f3 0f 1e fa          	endbr64 
 152:	48 89 c3             	mov    %rax,%rbx
 155:	eb ae                	jmp    105 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x105>
 157:	f3 0f 1e fa          	endbr64 
 15b:	48 89 c3             	mov    %rax,%rbx
 15e:	eb b7                	jmp    117 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x117>
 160:	f3 0f 1e fa          	endbr64 
 164:	48 89 c3             	mov    %rax,%rbx
 167:	eb c0                	jmp    129 <_ZNK5drake9multibody8internal13MultibodyTreeIdE19ThrowIfNotFinalizedEPKc+0x129>
```

One is about 50% more than the other. I'm not sure why that is and whether that's enough difference for us to care.
I would like to hear @jwnimmer-tri 's opinion on this.

**Comment by jwnimmer-tri** [comment]
*[`multibody/tree/multibody_tree.h` line 614 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli:-NQWEDJ_ALkTBkVaQZ1p:br375ix) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.h#L614)):*
Alejandro was on the right track.

---

The styleguide rule for naming `snake_case() const` getters is (only):

> Such methods should have a time complexity of O(1) and be less than 5 lines long.

We certainly clear the bar for "5 lines".  Even expanding the macro, it's just 1 line.

So the next the question is -- is this function constant time?  Yes, there is no looping over N items, it does the same work every time.

So the next question is -- is it clear to someone reading this function definition that the code _is_ constant time?  To me, it's sufficiently clear, but you guys can discuss and decide.  If it's not clear enough, the documentation of the `DRAKE_MBT_THROW_IF_FINALIZED` and `DRAKE_MBT_THROW_IF_NOT_FINALIZED` macros should be amended to make a promise that they are constant-time.

---

The styleguide rule for inline functions is multi-prong so I won't paste it here.

But option (1) is what clears us here -- the function is `snake_case`, so we're fine by the rule.

But even looking at the object code to match the "spirit" of what inline is for -- the object code for `ThrowIfNotFinalized` is irrelevant, since that code is not what's lined.

What gets inlined is:
* A plain function call to `ThrowIfNotFinalized` -- just a couple instructions.
* A `vector::at` followed by a direct read from memory into the return value.

So the only thing questionable there is whether the object code for `vector::at` exception checking is too large to be inline.

We could take it on trust that the STL is well-implemented, but it's not hard to check either: reading the source code for vector::at, we see that it's just a single memory compare, and then iff that fails it calls an out-of-line helper function `__throw_out_of_range_fmt`.  So the total instruction count for this function should end up very low, probably ~10.  Fine for inline.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959)* status: 1 unresolved discussion (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`multibody/tree/multibody_tree.h` line 614 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli:-NQWIcwS-DDc5JLJ39Fl:bqgddet) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.h#L614)):*
Thanks for the clear explanation.

> But even looking at the object code to match the "spirit" of what inline is for -- the object code for ThrowIfNotFinalized is irrelevant, since that code is not what's lined.

I missed that!

I think a way forward for this PR is to merge as-is, and we can come back and fix the snake_case-CamelCase inconsistency as a follow-up.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959)* status: 1 unresolved discussion (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`multibody/tree/multibody_tree.h` line 614 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli:-NQWJTc85Q211zs41hoG:b-z6o2xk) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.h#L614)):*
> ... snake_case-CamelCase inconsistency ...

Just to be very clear in my exposition -- the function names are correct and should not change: it's OK for snake_case to call CamelCase, as long as CamelCase is constant-time; we cannot rename ThrowIfNotFinalized to be snake_case because it's not a getter nor setter.

The only question is whether the code structure is sufficiently clear / well-documented enough for the next person who comes through here reading it.  A little sentence in the `...MBT_THROW_IF...` docs should clear that up.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959)* status: 1 unresolved discussion (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`multibody/tree/multibody_tree.h` line 614 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli:-NQWKWKM7rB1bzdULvj8:b-cgvtyt) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.h#L614)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... snake_case-CamelCase inconsistency ...

Just to be very clear in my exposition -- the function names are correct and should not change: it's OK for snake_case to call CamelCase, as long as CamelCase is constant-time; we cannot rename ThrowIfNotFinalized to be snake_case because it's not a getter nor setter.

The only question is whether the code structure is sufficiently clear / well-documented enough for the next person who comes through here reading it.  A little sentence in the `...MBT_THROW_IF...` docs should clear that up.
</blockquote></details>

Ok, I see. So we are all good! Thanks Jeremy.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18959)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/tree/multibody_tree.h` line 614 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli:-NQWPGUq2AkJQ5yPkLLz:b-hqogiz) ([raw file](https://github.com/RobotLocomotion/drake/blob/550dcc6a9f38153096a083fc1e435c56a7d5f766/multibody/tree/multibody_tree.h#L614)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ok, I see. So we are all good! Thanks Jeremy.
</blockquote></details>

wow, thank you for the hard work on trying to figure this one out guys. 

I'll merge this as-is and open a separate PR updating the docs on MBT_THROW_IF

**Pull request merged**
