### PR TITLE
switch to superbuild with cmake ExternalProject

### LINKED ISSUE #1169: replace PODS build system with cmake external projects

### PR DESCRIPTION
**Pull request by RussTedrake**
i just wanted to make a pull request with every single file in drake changed.  :)

Resolves #1169 .  this will blow away drake-distro.  drake will now be it's own project.  see the discussion in #1169.  

this has been tested on mac (old), mac (new), windows 64, and linux.  have been testing/tweaking all weekend.  seems very solid.  the build servers will be doing extra work, but might actually be ok with it.

I was worried about doing this with the many open pull requests, but Robin helped me test that workflow.  From Robin:
```
Hey Russ,

I'm still playing around to see what the best way to do this is. It looks like the easy thing will *mostly* just work. To experiment I did the following:

* get a fresh clone of drake
* do "git mv" on everything into a new drake/ folder
* add pete's fork as a remote
* merge peteflorence/QuadPlandPennCpp into my working branch

That worked without any conflicts, and all of the changes to existing files seemed to work correctly. However, any *new* files added in Pete's pull request got added without the drake/ prefix. That actually makes sense, since git treats all files independently of one another. So, as a cleanup, I had to move his new files into the correct place in the repo. 

So, I think this can be made to work, although it will require some manual cleanup to merge the currently outstanding pull requests. 

I'm thinking about some other ideas for how to make this easier. I'll let you know if I come up with anything good. 

-Robin
```

### CODE REVIEW

**Comment by RussTedrake** [comment]
sorry to say this, but I'd like to merge this asap.  the build servers are sort of in limbo until it's resolved.  (plus it's been consuming me, and i need to move on! :)

**Comment by RussTedrake** [comment]
that was drake006, which was a pass.  :)  it just failed to fine the ctest output since it had moved.  the other build servers will presumably do the same.

**Comment by RussTedrake** [comment]
have updated the wiki documentation.  am going to go ahead and pull this (to possibly suffer the consequences) so that I can finish switching the build servers over tonight.

**Comment by rdeits** [comment]
Awesome! I just did the same thing to IRIS (a somewhat smaller effort, to be sure...). I think this is going to be great.

**Pull request merged**
