### PR TITLE
[pydrake] Fix race condition in text_logging_gil_test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16731)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri or @xuchenhan-tri are you available to review?

**Review by xuchenhan-tri — COMMENTED** [review]
rubber stamp :lgtm:
I'm not following the problem nor the solution. Could you explain a little?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16731#-:-MxftQ1N1_q2CztO4Y0O:bv98p5x)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
There is a deadlock during test case shutdown.  The `worker.Stop()` call was holding the GIL (lock) on the main thread, while the worker thread was trying to post a log message into Python so was blocking waiting to acquire the GIL, never even noticing the flag that requests a shutdown.  The main thread needs to momentarily release the GIL while it waits for the worker thread to be joined.

**Review by xuchenhan-tri — COMMENTED** [review]
I think I understood. Is it correct to understand that releasing the GIL is always necessary in a c++ function that syncs threads and is supposed to be called via PyBind?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16731#-:-Mxg3y014Xcooa4ZsgEH:b-ecv4jp)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

**Pull request merged**
