### PR TITLE
doc: Refactor pydrake sphinx builds to use common code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14803. (That PR contains more example uses of the `defs.py` common helpers, as well as new `drake/doc/_pages/documentation_instructions.md` that show the overall UX goal.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY6-aKv60DiHTMQt5ld:-MY6-aKw1U6SQLmvP_D6:b-yg92hq) (no related file):*
Working

I still need to edit `doc/build.py` to refer to the new `doc/pydrake/build` target, instead of gen_sphinx.  However, something with the "manual" tags there is causing things to not recompile when they are supposed to!  Investigating now.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY6-aKv60DiHTMQt5ld:-MY6d5fqEf4C13d2LTPM:b1eem14) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I still need to edit `doc/build.py` to refer to the new `doc/pydrake/build` target, instead of gen_sphinx.  However, something with the "manual" tags there is causing things to not recompile when they are supposed to!  Investigating now.
</blockquote></details>

(FYI I think the rest of the PR, including instructions, is ready for review though.  The changes to fix the deployment pipeline should be minor.)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done pending CI fixes.

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887#-:-MY76yNw70hk1jwIArXM:b-bndgfc)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/_pages/documentation_instructions.md, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY76SAA0je_qSuGGHMx:-MY76SAA0je_qSuGGHMy:b-qrytsy) ([raw file](https://github.com/robotlocomotion/drake/blob/d7a994149ce148faa51c554fde7f3d6d9c30e3c5/doc/_pages/documentation_instructions.md#L63)):*
> ```Markdown
> 
> ```sh
> # Limiting preview to a subset of the modules.
> ```

BTW This comment line seems superfluous given surrounding text and below trailing comment.
___
*[doc/_pages/documentation_instructions.md, line 64 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY76WZj-dInokh3JBbG:-MY76WZj-dInokh3JBbH:bcwrhei) ([raw file](https://github.com/robotlocomotion/drake/blob/d7a994149ce148faa51c554fde7f3d6d9c30e3c5/doc/_pages/documentation_instructions.md#L64)):*
> ```Markdown
> ```sh
> # Limiting preview to a subset of the modules.
> $ bazel run //doc/pydrake:build -- --serve pydrake.systems    # Only drake/systems/... Python API.
> ```

nit Confused on `drake/systems` vs. `pydrake.systems`, coupled to help text about `.` or `/` being allowed. (Also, statement may not be accurate if there is add'l API not in C++.)

Suggestions:
- Remove trailing comment?
- Clarify help text in `build` that it still needs to be Python module, not C++ dir path?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY6-aKv60DiHTMQt5ld:-MY7AbYoBo13uOQNXI_b:b-qa5zie) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(FYI I think the rest of the PR, including instructions, is ready for review though.  The changes to fix the deployment pipeline should be minor.)
</blockquote></details>

Still working.

---
___
*[doc/_pages/documentation_instructions.md, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY76SAA0je_qSuGGHMx:-MY79kkC2yG89vdlbP5d:b9x4oc9) ([raw file](https://github.com/robotlocomotion/drake/blob/d7a994149ce148faa51c554fde7f3d6d9c30e3c5/doc/_pages/documentation_instructions.md#L63)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW This comment line seems superfluous given surrounding text and below trailing comment.
</blockquote></details>

Yup, rebase error.  Fixed.
___
*[doc/_pages/documentation_instructions.md, line 64 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY76WZj-dInokh3JBbG:-MY7AVSx0rCJX1EzTox_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7a994149ce148faa51c554fde7f3d6d9c30e3c5/doc/_pages/documentation_instructions.md#L64)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Confused on `drake/systems` vs. `pydrake.systems`, coupled to help text about `.` or `/` being allowed. (Also, statement may not be accurate if there is add'l API not in C++.)

Suggestions:
- Remove trailing comment?
- Clarify help text in `build` that it still needs to be Python module, not C++ dir path?
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY6-aKv60DiHTMQt5ld:-MY7X-3y8bdZZZUKtOtQ:b-lxu2w7) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Still working.
</blockquote></details>

Hopefully fixed now.  We'll see what CI says.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature!

+@sammy-tri for platform review on Tuesday!

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887#-:-MY7ZlsKCDYvXMHuiYln:bvw21bx)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[doc/_pages/documentation_instructions.md, line 56 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY7_16t9Q71Ln4AxH9l:-MY7_16t9Q71Ln4AxH9m:b-f79vt4) ([raw file](https://github.com/robotlocomotion/drake/blob/78a8da4b9ec5f6b61b75045f29e55f8a8dd3017c/doc/_pages/documentation_instructions.md#L56)):*
> ```Markdown
> 
> ```
> $ bazel run //doc/pydrake:build -- --serve
> ```

Working: Testing locally.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule (tomorrow), please.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

___
*[doc/defs.py, line 206 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY7cnup3o5AbgVLSrpV:-MY7cnur6-UX9MsPSjj-:b-djmba1) ([raw file](https://github.com/robotlocomotion/drake/blob/78a8da4b9ec5f6b61b75045f29e55f8a8dd3017c/doc/defs.py#L206)):*
> ```Python
>     if args.out_dir is None:
>         assert args.serve
>         _do_preview(build=curried_build, subdir=subdir, port=args.port)
> ```

nit I don't know why, but using the local server from this commit is way slower (like ~1-5s to change pages) than using the local server from base commit (like ~0.1s consistently).
It's enough to where it impacts "user experience".

Had to apply patch to run w/ base commit:
```
$ git log -n 1 --oneline --no-decorate
f22df9831a doc: Remove manual tag from documentation binaries (#14892)
$ git diff
diff --git a/doc/pydrake/sphinx_base.py b/doc/pydrake/sphinx_base.py
index 2b78303531..0de5dbebd7 100644
--- a/doc/pydrake/sphinx_base.py
+++ b/doc/pydrake/sphinx_base.py
@@ -100,7 +100,7 @@ def preview_main(gen_script, default_port):
         gen_script: Generation script, required to generate docs.
         default_port: Default port for local HTTP server.
     """
-    sphinx_build = runfiles.Create().Rlocation("sphinx/sphinx-build")
+    sphinx_build = "/usr/share/sphinx/scripts/python3/sphinx-build"
     assert isfile(sphinx_build), "Please execute via 'bazel run'"
     parser = argparse.ArgumentParser()
     parser.register('type', 'bool', _str2bool)
$ bazel run //doc/pydrake:serve_sphinx
```

Try clicking into different modules, and see the diff btw this PR's state and base commit's (with patch).
___
*[doc/_pages/documentation_instructions.md, line 56 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY7_16t9Q71Ln4AxH9l:-MY7e0rc8z6SCyPVg2Ew:b-4lw2ws) ([raw file](https://github.com/robotlocomotion/drake/blob/78a8da4b9ec5f6b61b75045f29e55f8a8dd3017c/doc/_pages/documentation_instructions.md#L56)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Testing locally.
</blockquote></details>

OK Done. See above nit.

(Neat that we can now select modules!)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[doc/defs.py, line 206 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY7cnup3o5AbgVLSrpV:-MY7jmeH-0inB66MxSSU:bhax2wc) ([raw file](https://github.com/robotlocomotion/drake/blob/78a8da4b9ec5f6b61b75045f29e55f8a8dd3017c/doc/defs.py#L206)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I don't know why, but using the local server from this commit is way slower (like ~1-5s to change pages) than using the local server from base commit (like ~0.1s consistently).
It's enough to where it impacts "user experience".

Had to apply patch to run w/ base commit:
```
$ git log -n 1 --oneline --no-decorate
f22df9831a doc: Remove manual tag from documentation binaries (#14892)
$ git diff
diff --git a/doc/pydrake/sphinx_base.py b/doc/pydrake/sphinx_base.py
index 2b78303531..0de5dbebd7 100644
--- a/doc/pydrake/sphinx_base.py
+++ b/doc/pydrake/sphinx_base.py
@@ -100,7 +100,7 @@ def preview_main(gen_script, default_port):
         gen_script: Generation script, required to generate docs.
         default_port: Default port for local HTTP server.
     """
-    sphinx_build = runfiles.Create().Rlocation("sphinx/sphinx-build")
+    sphinx_build = "/usr/share/sphinx/scripts/python3/sphinx-build"
     assert isfile(sphinx_build), "Please execute via 'bazel run'"
     parser = argparse.ArgumentParser()
     parser.register('type', 'bool', _str2bool)
$ bazel run //doc/pydrake:serve_sphinx
```

Try clicking into different modules, and see the diff btw this PR's state and base commit's (with patch).
</blockquote></details>

Try again now.  The pydrake API doc css references non-existent woff2 font files, and the 404 traces from that were gumming up the (previously single-threaded) server.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[doc/defs.py, line 206 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14887#-MY7cnup3o5AbgVLSrpV:-MY7p2s_0V0me9jXFiDG:b-glzlob) ([raw file](https://github.com/robotlocomotion/drake/blob/78a8da4b9ec5f6b61b75045f29e55f8a8dd3017c/doc/defs.py#L206)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Try again now.  The pydrake API doc css references non-existent woff2 font files, and the 404 traces from that were gumming up the (previously single-threaded) server.
</blockquote></details>

OK Wayyy better - thanks!

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14887#-:-MYBa2VhDUvw1Ichzeu3:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
