### PR TITLE
Changed comments and set up of autodiff_test.cc 

### PR DESCRIPTION
**Pull request by ManuelAhumada-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777)

### CODE REVIEW

**Comment by ManuelAhumada-TRI** [comment]
+@mitiguy for feature review, please. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777#-:-LC0wG3J3p3jesdOGAY7:b-hsechj)*

**Comment by mitiguy** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/test/autodiff_test.cc, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC5F2LPAdr5kS0aNX9d:-LC5F2LPAdr5kS0aNX9e:b-183e3t) ([raw file](https://github.com/robotlocomotion/drake/blob/6868f725dfcc15bdf8712a3f81f5ae153c2218a6/math/test/autodiff_test.cc#L30)):*
> ```cpp
> 
>     // Set the value of the variables (vec_[0] and vec_[1]) to the value at
>     // which the derivative is to be evaluated.  Arbitrarily chose [7.0, 9.0].
> ```

BTW chose to choose ?

---

*[math/test/autodiff_test.cc, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC5FXIa41PfPK21PqJl:-LC5FXIa41PfPK21PqJm:b-2sxgkz) ([raw file](https://github.com/robotlocomotion/drake/blob/6868f725dfcc15bdf8712a3f81f5ae153c2218a6/math/test/autodiff_test.cc#L49)):*
> ```cpp
>     vec_[1].derivatives()(1) = 1.0;
> 
>     // Do a calculation that is a function of variables v0 and v1.
> ```

BTW add one more line ?
// Store the result (output_calculation_) for subsequent use below.

---

*[math/test/autodiff_test.cc, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC5GI2i0RCXfvuAev_p:-LC5GI2i0RCXfvuAev_q:bp8ooh8) ([raw file](https://github.com/robotlocomotion/drake/blob/6868f725dfcc15bdf8712a3f81f5ae153c2218a6/math/test/autodiff_test.cc#L53)):*
> ```cpp
>   }
> 
>   // Do a calculation that is a real function of two real variables.  This
> ```

BTW  
Do a calculation involving real functions of two real variables.  These functions were chosen due to ease of differentiation.

---

*[math/test/autodiff_test.cc, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC5QMzc9JqRPzriqQSa:-LC5QMzc9JqRPzriqQSb:bcu2jxo) ([raw file](https://github.com/robotlocomotion/drake/blob/6868f725dfcc15bdf8712a3f81f5ae153c2218a6/math/test/autodiff_test.cc#L92)):*
> ```cpp
>   // Function 1: y1 = sin(v0) + v1.
>   // Function 2: y2 = v0^2 + v1^3.
>   // Calculate the six partial derivatives below.
> ```

BTW 
// Calculate partial derivatives of y0, y1, y2 with respect to v0, v1, v2 below.
// ∂y0/∂v0  = -sin(v0) + (cos(v0)^2 - sin(v0)^2) / v1
(no need to repeat words - spare Sherm).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777)*

**Comment by mitiguy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777#-:-LC5QzwtDCM_ESk45msM:bnfp4nl)*

**Comment by ManuelAhumada-TRI** [comment]
+@seancurtis-tri for platform review, please. 

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[math/test/autodiff_test.cc, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC5FXIa41PfPK21PqJl:-LC5U-eC2qaE_3Ht36aj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6868f725dfcc15bdf8712a3f81f5ae153c2218a6/math/test/autodiff_test.cc#L49)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

BTW add one more line ?
// Store the result (output_calculation_) for subsequent use below.
</blockquote></details>

Done.

---

*[math/test/autodiff_test.cc, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC5GI2i0RCXfvuAev_p:-LC5U1SM28YUDvyWewSk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6868f725dfcc15bdf8712a3f81f5ae153c2218a6/math/test/autodiff_test.cc#L53)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

BTW  
Do a calculation involving real functions of two real variables.  These functions were chosen due to ease of differentiation.
</blockquote></details>

Done.

---

*[math/test/autodiff_test.cc, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC5QMzc9JqRPzriqQSa:-LC5U2rJ1weifcwsXgo-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6868f725dfcc15bdf8712a3f81f5ae153c2218a6/math/test/autodiff_test.cc#L92)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

BTW 
// Calculate partial derivatives of y0, y1, y2 with respect to v0, v1, v2 below.
// ∂y0/∂v0  = -sin(v0) + (cos(v0)^2 - sin(v0)^2) / v1
(no need to repeat words - spare Sherm).

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777#-:-LC5U3gjCq2xFxGuiO2M:b-autost)*

**Comment by mitiguy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[math/test/autodiff_test.cc, line 95 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC5gJsI5kJhWdiEo1lM:-LC5gJsI5kJhWdiEo1lN:b8gd48q) ([raw file](https://github.com/robotlocomotion/drake/blob/6559e37427618d58c216c4fe3dd15720b8b8bb7e/math/test/autodiff_test.cc#L95)):*
> ```cpp
>   // Calculate partial derivatives of y0, y1, y2 with respect to v0, v1, v2.
>   // ∂y0/∂v0 = -sin(v0) + (cos(v0)^2 - sin(v0)^2) / v1
>   expected(0, 0) = -sin(7) + (cos(7) * cos(7) - sin(7) * sin(7)) / 9;
> ```

BTW Change all these.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777)*

**Comment by ManuelAhumada-TRI** [comment]
The original was changed in order to show a more pedagogical example on how to use AutoDiff. By expanding on the comments, and explicitly showing how to set up the independent variables for partial differentiation, it makes it more clear what is going on under the hood with AutoDiff.  Original documentation was difficult to follow if someone wasn't already familiar with how to use AutoDiff. 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[math/test/autodiff_test.cc, line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC6B_XDCpOhTYgNBNrr:-LC9uilF5DglQUGu7FqM:b-f49tri) ([raw file](https://github.com/robotlocomotion/drake/blob/ae0261f6bf0c4440c749018097e787f291d38788/math/test/autodiff_test.cc#L29)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW For example: the two statements below make it clear that you are assigning values 7 and 9 to [0] and [1], respectively. The only interesting part of this is that the values 7 and 9 are arbitrary (i.e. the reader shouldn't look for higher meaning.
</blockquote></details>

Agreed, but it also seems useful to explain that by using the .value() operation you are setting the value at which the partial derivative will be evaluated. If someone isn't already familiar with AutoDiff, that particular operation may not be totally obvious. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777#-:-LC9qfeo0xI6dnEIcIgz:bk49nhq)*

**Comment by SeanCurtis-TRI** [comment]
But why change the *values*? It wasn't obvious to me that the values 7 & 9 made the example clearer than 1 & 10.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777#-:-LC9wxTODwP9iofNVF8z:b-qudjx6)*

**Comment by ManuelAhumada-TRI** [comment]
Changing those values doesn't do much more than set it aside from the repeated use of 1s and 0s across the test. 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777#-:-LC9xQ2kCkeo9Mfs_Hy4:bwnvq81)*

**Comment by SeanCurtis-TRI** [comment]
Fair enough. In future PRs, if you make a change like that, you should document the reason for it in the main PR comment (note: not the same as the git commit). That way reviewers have a basis for understanding the whys of what it is they're seeing.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[math/test/autodiff_test.cc, line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC6B_XDCpOhTYgNBNrr:-LC9xH-z1LwyGFcr83zb:b-z3ltge) ([raw file](https://github.com/robotlocomotion/drake/blob/ae0261f6bf0c4440c749018097e787f291d38788/math/test/autodiff_test.cc#L29)):*
So, there are two parts here: the semantics and syntax. 

The first half of your comment is about semantics and, as such, is good:

> Set up to evaluate the derivatives at the arbitrary values 7 & 9.

The second half is syntax comment and, as such, redundant w.r.t. the code ("for vec_[0] and vec_[1] to be 7.0 and 9.0, respectively"). It's 100% obvious in the code that vec_.[0] is being assigned the value 7, etc.

---

*[math/test/autodiff_test.cc, line 37 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC9yRLoCaWFUPxpZA3Z:-LC9yRLoCaWFUPxpZA3_:bdxzujj) ([raw file](https://github.com/robotlocomotion/drake/blob/a08cfebbc8ccf6c637a154963d5ce5b12109f2e0/math/test/autodiff_test.cc#L37)):*
> ```cpp
>     vec_[1].derivatives().resize(2);
> 
>     // Herein, the shorthand notation is used: v0 = vec_[0] and v1 = vec_[1].
> ```

FYI One of the things you've lost in this transformation is the *arbitrary* interpretation of the derivative placement. The new documentation suggests there's something intrinsic in `∂v0/∂v0` being in `vec_[0].derivatives()(0)`, but that's not strictly true. That said, it's reasonable and logical to act as such. So, it seems you omitted the arbitrariness of this aspect in favor of simplicity, hoping to lead to clarity. Is that the case?

---

*[math/test/autodiff_test.cc, line 74 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LCA-M1h6PrZXYwBjlsV:-LCA-M1h6PrZXYwBjlsW:bfnmil0) ([raw file](https://github.com/robotlocomotion/drake/blob/a08cfebbc8ccf6c637a154963d5ce5b12109f2e0/math/test/autodiff_test.cc#L74)):*
> ```cpp
>   const VectorXd values = autoDiffToValueMatrix(output_calculation_);
>   VectorXd expected(3);
>   expected[0] = cos(7) + sin(7) * cos(7) / 9;
> ```

BTW You've got magic constants 7 and 9 all over this code. I know the old code did the same with 1 and 10. It would be *much* better if you created const variables `v0` and `v1`, assigned them as 7 & 9, and then simply referenced `v0` and `v1` everywhere. 7 & 9 should only appear once.

---

*[math/test/autodiff_test.cc, line 91 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LCA-62e68H19oIg88q3:-LCA-62e68H19oIg88q4:b-i0dm9n) ([raw file](https://github.com/robotlocomotion/drake/blob/a08cfebbc8ccf6c637a154963d5ce5b12109f2e0/math/test/autodiff_test.cc#L91)):*
> ```cpp
>   // Function 1: y1 = sin(v0) + v1.
>   // Function 2: y2 = v0^2 + v1^3.
>   // Calculate partial derivatives of y0, y1, y2 with respect to v0, v1, v2.
> ```

BTW there is no `v2`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777#-:-LCA-pSSD1n1icIHGWrd:b-rnuj91)*

**Comment by ManuelAhumada-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[math/test/autodiff_test.cc, line 37 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8777#-LC9yRLoCaWFUPxpZA3Z:-LCAAMUV0xm6EaPdz_J_:bpuh75m) ([raw file](https://github.com/robotlocomotion/drake/blob/a08cfebbc8ccf6c637a154963d5ce5b12109f2e0/math/test/autodiff_test.cc#L37)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI One of the things you've lost in this transformation is the *arbitrary* interpretation of the derivative placement. The new documentation suggests there's something intrinsic in `∂v0/∂v0` being in `vec_[0].derivatives()(0)`, but that's not strictly true. That said, it's reasonable and logical to act as such. So, it seems you omitted the arbitrariness of this aspect in favor of simplicity, hoping to lead to clarity. Is that the case?
</blockquote></details>

I see. Yes, it seems as though the arbitrary placement may have been lost, but the hope is that the comment makes up for that and adds clarity. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Thanks for playing along.  :)

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8777#-:-LCAKEFX-Odpe0-dXMnS:b-19nnxr)*

**Pull request merged**
