### PR TITLE
Improve "native CMake" support

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify how externals are built, when using CMake directly, to use the CMake build directory and not pod-style build directories, and to propagate build flags to the external projects. (There is an option, turned on by the pods `Makefile`, to preserve the old behavior.)

This brings us closer to being able to build in any directory (not just `<clone>/pod-build`) and with any generator (tested with ninja), and reduces the number of build artifacts that are placed in the source tree (and thus interfere with having multiple builds from a single source). Note however that some externals may still fail to "play nice" (e.g. libbot still forces its external projects to build in the source tree).

Note that this changes the build location for external projects from `<source>/externals/<name>/pod-build` to `<build>/externals/<name>`. (This seems like a reasonable place, but I'm open to alternative suggestions if anyone feels strongly.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/1884)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@RussTedrake, I'm submitting this for *consideration*. We probably want to continue the discussion if this is a direction in which we want to go.

If I did this right, anyone using the pods `Makefile` to build won't see a change. The main change is that a) I'm much more confident building this "the pure CMake way", i.e. create a build directory anywhere (as previously noted, my build directory and source directory are about six levels deep with only two levels in common) and with any generator (I'm using [ninja](https://ninja-build.org/)), and b) many of the build artifacts will actually reside in the build directory (previously, nearly all build artifacts were guaranteed to be somewhere below the source directory).

Also, because it will be interesting to see what CI makes of it :smile:. (I've been using this on my machine for a couple weeks or so. However, I'm building something close to the minimal package set.)

We've talked about getting rid of pods... I don't see a reason why we would need to excise everything pods all at once. This is intended as a first step in a more gradual approach. Between this, a CMake-ified LCM, and revisiting the use of some of the pods helper functions (i.e. `pods.cmake`), my feeling is that we should be able to have, or at least get very close to, a "clean, pure CMake" build that still has the option to conform to pods. At that point, we can revisit if we want to drop pods and only support the new system.

**Comment by jamiesnape** [comment]
I think we should make a clean break from pods, if we decide to move away from it. The helper functions and other infrastructure are just extra complexity and maintenance. If we were to still allow the old pods infrastructure we will have to use it and test it, otherwise it may as well not be there.

**Comment by billhoffman** [comment]
I think if we move away from the pods it can be done gradually.  This is a good step in that direction.  Next step would be to get rid of all makefile pods so that this will work cleanly with them.  There is a bunch of infrastructure and it would be too hard to make a clean break one day.

**Comment by patmarion** [comment]
By the way, the openhumanoids project builds many of the same pod projects (and drake is also a dependency of openhumanoids).

Changes to these pods will have to be incorporated into openhumanoids, too.  Fortunately, the superbuild in openhumanoids has support for pods and standard cmake projects, so I don't foresee any problems.  Openhumanoids only targets Ubuntu and Unix Makefiles.  Openhumanoids currently builds 30+ externals via this script:

https://github.com/openhumanoids/oh-distro/blob/master/software/externals/cmake/externals.cmake

**Comment by RussTedrake** [comment]
in addition to the complaining build servers, i would like to hear more the developers thoughts on this... comments appreciated.

**Comment by tkoolen** [comment]
I haven't looked at the code changes, but judging by @mwoehlke-kitware's description, I think this is an important step in the right direction. There is a lot of value in doing things in a way that's standardized not only within the Drake universe (which is what we sort of have now with pods), but throughout a large part of the C++ developer community.

**Comment by sherm1** [comment]
I like the idea of moving Drake's build to best-practices use of CMake. For mere mortals it is not always clear what that means, but with Kitware working on it this is a great opportunity for us to get the best possible build system. So I would support re-engineering of the build system if Kitware folks say they are confident they know how to do it better.

**Comment by RussTedrake** [comment]
does the cmake best-practices provide a mechanism for avoiding the big compile time hit for externals which can be labeled as "changing almost never"?

**Comment by jamiesnape** [comment]
If the external has not changed, it will not be recompiled.

**Comment by jamiesnape** [comment]
There should be less recompilations than pods, even, as pods forces re-configuration in some instances where CMake would not do so otherwise.

**Comment by RussTedrake** [comment]
That sounds fantastic. But i thought cmake external projects also forced 
recompilation in the same way as pods?

**Comment by mwoehlke-kitware** [comment]
@RussTedrake, @jamiesnape, note that this branch *removes the force-configure step*, replacing it with a force-*build* step. CMake knows when it needs to be re-run and does so as part of a build if necessary.

I just did a no-op build for *all of drake*:

    real    0m2.227s
    user    0m2.469s
    sys     0m1.272s

(Caveats: a) I'm using ninja, which among other things is especially designed to have really fast no-op build times; build time with make will be slower, b) this is from the second run, so my file caches were "hot"; build time with cold caches will be slower, and c) I have a fairly minimal set of externals turned on; more externals will obviously equate to longer build time. That said, being generator-agnostic is one of those "best practices", so I wouldn't just ignore that part of the reason it's fast is due to ninja...)

**Comment by jamiesnape** [comment]
Why is there a force build?

**Comment by mwoehlke-kitware** [comment]
> Why is there a force build?

Because otherwise nothing triggers the external project to actually be built if the code is modified. Especially for drake itself, this would... work poorly :grin:.

Possibly we could add an option to disable this for external projects besides drake itself, but I would not want it on by default... and it's probably better to just use ninja; you only add a few seconds to ordinary builds but save a lot of pain when you actually *need* those builds.

(Also, just as a reminder... you can still `cd` into the build directory of any external project and build only that... The names are different, but they're still there.)

**Comment by jamiesnape** [comment]
You mean if the code was manually changed vs. changing the hash in the update step?

**Comment by mwoehlke-kitware** [comment]
> You mean if the code was manually changed vs. changing the hash in the update step?

Yes.

**Comment by RussTedrake** [comment]
In that case, we should seriously consider removing the force_build step for everything but drake. (or disabling it by default).
Re: ninja. I’ve not actually ever used it. Is that something that could play well with CLion?

**Comment by jamiesnape** [comment]
There is a feature request, but no official support yet. Some people have made it work, though.

https://youtrack.jetbrains.com/issue/CPP-870

**Comment by mwoehlke-kitware** [comment]
I'm pretty sure I've been burned before by not having the force-build step. At least, I want to keep it as an option; it only adds a few seconds to the build time, but saves a lot of pain when it's needed.

**Comment by patmarion** [comment]
+1 for using the force-build step on all external projects.  I think force-configure is the safest, even though it costs more time, but maybe that's overkill.  I guess the situation there is if a user changes a configuration variable in an external project that the superbuild needs to set, the variable won't be switched back?

**Comment by RussTedrake** [comment]
started discussion in #1939

**Comment by mwoehlke-kitware** [comment]
> I think force-configure is the safest, even though it costs more time, but maybe that's overkill. I guess the situation there is if a user changes a configuration variable in an external project that the superbuild needs to set, the variable won't be switched back?

That seems like a feature. If you're monkeying around in there, presumably you have a reason; having the top level build reset your changes every time in that case would be annoying.

A few observations to add... AFAICT the configure step *does* have a dependency on what arguments are passed to configure, so if this changes, the configure will re-run without user intervention. (Pat's previous comment seems to be the only reason you would ever need/want to force it.) Also, the configure step depends on dependencies, which means a few projects (drake in particular) will always configure anyway due to force-build of said dependencies. (This does mean the force-build slows things down a little, but as shown it is on the order of a few seconds. This also means, however, that configure should re-run whenever a download changes.)

**Comment by jhoare** [comment]
I kind of think the ``clean-all`` and ``clean-${proj}`` targets should only be made when ``POD_BUILD=True``

**Comment by mwoehlke-kitware** [comment]
> I kind of think the clean-all and clean-${proj} targets should only be made when POD_BUILD=True

I think they're still potentially useful. Anyway, I'd like to defer this for later. It would be good to get the initial branch merged. This is going to be an ongoing project; if we wait for it to be "perfect" before making any changes, it will be much harder to get anything done.

**Comment by jhoare** [comment]
Could  you please address the merge conflicts?

**Comment by jhoare** [comment]
I tested this out to try to see what still gets done to the source directory while attempting an out of source build. 

It looks like the culprits that still are touching the source directory after this change are: ``director``, ``swig_matlab``, ``libbot`` and some of the ``pydrake``

I think this is a great first step to enabling out of source builds but more will need to be done to fully enable it. 

Output is here: https://gist.github.com/jhoare/5d9934dc74788b06944d

**Comment by mwoehlke-kitware** [comment]
> I tested this out to try to see what still gets done to the source directory while attempting an out of source build.

Thanks for researching this!

> It looks like the culprits that still are touching the source directory after this change are: `director`, `swig_matlab`, `libbot` and some of the `pydrake`

I know that the problem with `libbot` resides in `libbot` itself. Basically, it would need a similar change as this one to fix (or we could get rid of `libbot`). Without checking, I would strongly suspect that at least `director` and possibly the other two also are in the same boat. The upshot is that changes need to be made in those repositories.

**Comment by rdeits** [comment]
The pydrake bindings leave build artifacts in the source tree because it made my life easier when iterating on the python code. But being able to build fully out-of-source seems like a worthwhile goal. You should be able to prevent pydrake from polluting the source by changing this line: https://github.com/RobotLocomotion/drake/blob/master/drake/bindings/swig/CMakeLists.txt#L16 

to 

```
set(python_install_subdir lib/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/dist-packages)
```

**Comment by jhoare** [comment]
I should also mention that I only tested the default build that runs without matlab installed. There are likely a number of the private or non-default pods that also put stuff in the source directory. I would imagine just about every Makefile pod would do it.

**Comment by patmarion** [comment]
@jhoare for proper out of source build, shouldn't all the externals also be downloaded into the build directory?

All pod projects support out of source builds, but the pod Makefile puts the build directory (pod-build) into the source dir.  It's possible to change the drake top-level CMakeLists.txt to compile the pod projects by skipping the pod Makefile and configure them directly with the ExternalProject configure step.  Some pod Makefiles hard code some configuration args, those will have to be migrated into drake's top-level CMakeLists.txt.

For example, both libbot and director support out of source builds.  But if you call their pod Makefile, then then you'll see the pod-build directory appear inside the project source dirs.  For director, the pod makefile is under director/distro/pods/drake-distro/Makefile, but standard CMakeLists.txt is director/distro/superbuild/CMakeLists.txt.  If drake now has support for configuring non-pod projects, then drake can build libbot and director as a standard cmake projects, not pod projects.

**Comment by jhoare** [comment]
> @jhoare for proper out of source build, shouldn't all the externals also be downloaded into the build directory?

I think there's a couple of ways of looking at it, and I think that it should be an option to do either. I view the ``download-alll`` step/target as sort of a continuation of checking out the repository or a step to bootstrap the entire source tree. 

> All pod projects support out of source builds, but the pod Makefile puts the build directory (pod-build) into the source dir. It's possible to change the drake top-level CMakeLists.txt to compile the pod projects by skipping the pod Makefile and configure them directly with the ExternalProject configure step. Some pod Makefiles hard code some configuration args, those will have to be migrated into drake's top-level CMakeLists.txt.

I agree, although as you said, some pods will need to be modified in order to support being built out of source. 

> For example, both libbot and director support out of source builds. But if you call their pod Makefile, then then you'll see the pod-build directory appear inside the project source dirs. For director, the pod makefile is under director/distro/pods/drake-distro/Makefile, but standard CMakeLists.txt is director/distro/superbuild/CMakeLists.txt. If drake now has support for configuring non-pod projects, then drake can build libbot and director as a standard cmake projects, not pod projects.

Thanks for the expanded info for director. It does however, look like libbot would need to be modified to build out of source, unless I am missing something. Each subdirectory is set up using ExternalProject, and it hard-codes the build directory to be the pod-build folder within the source directory. https://github.com/RobotLocomotion/libbot/blob/master/CMakeLists.txt#L64

Primarily what I was trying to do here was see how close this pull request gets us to being able to build out of source. It looks like the answer is it makes a good step in the right direction, but does not fully enable it. I think making the updates that you and I have mentioned would be good next steps. 

That said, is there anything controversial about the changes this pull request is proposing?

**Comment by patmarion** [comment]
Ok great, that makes sense.  Ah, yes you are right (and @mwoehlke-kitware mentioned that too) about libbot, its CMakeLists.txt will need to be modified if we want to build it without creating in source pod-build dirs.

I think director should work without modification, but let me know if you find something that gives a problem.

**Comment by mwoehlke-kitware** [comment]
@RussTedrake, can this be merged? If not, please advise what is blocking it...

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Comment by david-german-tri** [comment]
Apologies for letting this PR fall through the cracks!  I think it looks like a great step in the right direction, but I'm going to wait a couple hours before merging in case there are last-minute objections.

:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/1884#-:-KFFOMK6jFGU9cgk8a7f:-528005629)*

**Comment by david-german-tri** [comment]
Actually, could you also share the `cmake` invocation you use to build "the new way"?  I know this is a basic question, but many of us at TRI have never built Drake by any means other than `make` before.

**Comment by mwoehlke-kitware** [comment]
The *exact* invocation I am using is a complicated artifact of my development environment, which has a bunch of shared machinery for building CMake-based software. All of that, however, is optional and built upon common CMake convention.

The "short" answer, that works with any "conventional" CMake-based project, is:

    $ mkdir path/to/build; cd path/to/build; cmake path/to/source

...or use the CMake GUI. The source and build directories can be the same (not recommended or tested), totally unrelated (e.g. `/opt/builds/drake-debug` and `$HOME/dev/drake`), or anything in between.

You can also add additional arguments (before the path to the source directory) to taste. Among others (e.g. build and link flags), I use `-G Ninja -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo`.

**Comment by mwoehlke-kitware** [comment]
Addendum: running CMake will generate build scripts for the chosen generator (on UNIX platforms, the default is `UNIX Makefiles`, so after running CMake, you would run `make` in your build directory). On Windows, I recommend using the GUI to configure. Most Windows developers in my experience will generate VS solution files and use VS (i.e. the graphical IDE, rather than a command line tool) to build. You can also build, on any platform and regardless of generator selected, with (e.g.):

    $ cmake --build path/to/build --config Release --target all

(The `--target all` is optional; shown to demonstrate how to build a target other than the default `all`. The `--config <config>` is only relevant for multi-configuration generators, e.g. VS and XCode.)

**Comment by david-german-tri** [comment]
Awesome.  Passes CI, works for me, and no one else has complained.  Merging.

**Comment by liangfok** [comment]
Using this new `CMake` way of compiling Drake, how does one select which packages to include in the build? For example, if I want to enable `SNOPT` and disable `SNOPT-PRECOMPILED` how do I do that?

**Comment by mwoehlke-kitware** [comment]
@liangfok, use `ccmake` or `cmake-gui`. You can replace the initial invocation of `cmake` with `ccmake` instead (you'll need to hit 'c' to configure initially before ccmake will know what options are available, or run `ccmake path/to/existing/build` / `cd path/to/build; ccmake .` at any time.

Note that the old `make options` just ran `cmake` followed by `ccmake` (or `cmake-gui`, on Windows).

(You can also pass e.g. `-DWITH_SNOPT:BOOL=ON` to `cmake`, but the above options are obviously much easier :smile:.)

**Comment by liangfok** [comment]
Thanks. That worked. For reference, the commands I executed for an out-of-source build on Ubuntu Linux are as follows:

```
$ mkdir -p [path to new directory for holding build artifacts]
$ cd [path to new directory for holding build artifacts]
$ env CXX=g++-4.9 CC=gcc-4.9 ccmake [drake-distro]
// type 'c' to get the available options
// select desired options
// type 'c' again to configure
// then type 'g' to generate the build files and exit
$ env CXX=g++-4.9 CC=gcc-4.9 make
```
@david-german-tri: Should Drake's wiki be updated with out-of-source build instructions?

**Comment by jhoare** [comment]
Note that an out of source build still is not possible, although this change is a good step in the right direction. See my post above: https://github.com/RobotLocomotion/drake/pull/1884#issuecomment-201449219

**Comment by mwoehlke-kitware** [comment]
> $ env CXX=g++-4.9 CC=gcc-4.9 make

Setting `CC` and `CXX` here is superfluous; CMake will "bake" them into the build files. (Setting them before running `cmake` — as seen elsewhere in the above recipe ­— is important, if you need to override the default compilers.)

Otherwise, the above recipe is correct (thanks for sharing!). One caveat that may be worth mentioning is that, when you reconfigure, if any new options are created, you need to configure again before you can generate. That may not happen for drake, but it's something to be aware of in general when using `ccmake`.

**Pull request merged**
