### PR TITLE
Implements AutoDiff tester for ImplicitStribeckSolver Jacobian.

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR implements an AutoDiffXd version for the Jacobian of the residual in order to verify the internals of the implicit Stribeck solver. This will become even more handy as we add more terms to the implementation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9007)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@edrumwri for feature review please. 

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9007#-:-LF37kgl8q06JcSGv7Nb:b-xtq7wg)*

**Comment by amcastro-tri** [comment]
-@edrumwri since he's leaving on vacation. 
+@hongkai-dai for feature review please.
+@sherm1 for platform review please.

---

Review status: all discussions resolved, LGTM missing from assignee edrumwri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9007#-:-LF3pPfZ1GVodKFWxRnI:bf3w405)*

**Comment by hongkai-dai** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: 3 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9007#-LF5rAZUCq5d8UaidYpt:-LF5rAZUCq5d8UaidYpu:b-byixw1) ([raw file](https://github.com/robotlocomotion/drake/blob/158719cf2aeb63876142c0a616a97be23aebb88b/multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h#L36)):*
> ```objc
> 
>   VectorX<U> ft(2 * nc);
>   VectorX<U> mus(nc);
> ```

I didn't realize that `mus` means `μₛ` until I read the code below, maybe you could rename the variable as `mu_s`?

---

*[multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9007#-LF5pQr3DxY3_vKHBUnr:-LF5pQr3DxY3_vKHBUns:b-5nzxbq) ([raw file](https://github.com/robotlocomotion/drake/blob/158719cf2aeb63876142c0a616a97be23aebb88b/multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h#L37)):*
> ```objc
>   VectorX<U> ft(2 * nc);
>   VectorX<U> mus(nc);
>   VectorX<U> that(2 * nc);
> ```

I don't think a variable name `that` can be confused with the English word `that, could you change it to a different name? maybe `t_hat`?

---

*[multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9007#-LF5rPM_4SssPq_nCzak:-LF5rPM_4SssPq_nCzal:b-dd0htm) ([raw file](https://github.com/robotlocomotion/drake/blob/158719cf2aeb63876142c0a616a97be23aebb88b/multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h#L40)):*
> ```objc
>   VectorX<U> v_slip(nc);
> 
>   auto ModifiedStribeck = [](U x, double friction_coefficient) {
> ```

For my own educational purpose, is the intention of `ModifiedStribeck` to return a new friction coefficient μₛ from the original coefficient μ, why you choose to multiply x*(2-x)? I guess `x * (2-x)` has some nice property here, that it is continuous and differentiable at `x = 1`. With your piecewise function as
```
μₛ = x*(2-x) μ when x < 1
μₛ = μ when x >= 1
```
I suppose you want to find a function `f(x)` such that f(0) = 0, f(1) = 1 and df/dx(1) = 0, and f(x) = x * (2-x) is the polynomial with the lowest degree that satisfy the requirement. Is this the reason?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9007#-:-LF5tjfs7VCmJuIygyLZ:bg7igkv)*

**Comment by amcastro-tri** [comment]
Thank you for the speedy review.

---

Review status: 3 unresolved discussions, platform LGTM from [sherm1], commit history needs curation

---

*[multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9007#-LF5rAZUCq5d8UaidYpt:-LFJ0SFMDhi6hUemOdU6:bxvx4rc) ([raw file](https://github.com/robotlocomotion/drake/blob/158719cf2aeb63876142c0a616a97be23aebb88b/multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h#L36)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I didn't realize that `mus` means `μₛ` until I read the code below, maybe you could rename the variable as `mu_s`?
</blockquote></details>

I agree it is a bad name, sorry. Chunks of my initial prototype. I changed it to (hopefully) something more sensible. 

---

*[multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9007#-LF5pQr3DxY3_vKHBUnr:-LFJ0h6D6vrJd9NbOzNH:bv7ro1y) ([raw file](https://github.com/robotlocomotion/drake/blob/158719cf2aeb63876142c0a616a97be23aebb88b/multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h#L37)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't think a variable name `that` can be confused with the English word `that, could you change it to a different name? maybe `t_hat`?
</blockquote></details>

yes! thank you.

---

*[multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9007#-LF5rPM_4SssPq_nCzak:-LFJ0r7k3wP__AAbyj_7:bprpzvt) ([raw file](https://github.com/robotlocomotion/drake/blob/158719cf2aeb63876142c0a616a97be23aebb88b/multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h#L40)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

For my own educational purpose, is the intention of `ModifiedStribeck` to return a new friction coefficient μₛ from the original coefficient μ, why you choose to multiply x*(2-x)? I guess `x * (2-x)` has some nice property here, that it is continuous and differentiable at `x = 1`. With your piecewise function as
```
μₛ = x*(2-x) μ when x < 1
μₛ = μ when x >= 1
```
I suppose you want to find a function `f(x)` such that f(0) = 0, f(1) = 1 and df/dx(1) = 0, and f(x) = x * (2-x) is the polynomial with the lowest degree that satisfy the requirement. Is this the reason?
</blockquote></details>

yes!, that is the reason. Another very important reason is that  `df/dx > 0`, always. That leads to the stability of the implicit Euler scheme. That is why I changed this function from the Stribeck function we have say, in RBT, to what we use here. Notice this only has one friction coefficients (i.e. there's no distinction between static and dynamic friction) 

---

*[multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9007#-LFItHa43gp276mOL_bI:-LFJ2-9B4hj1A6w45ODQ:b-9qlpue) ([raw file](https://github.com/robotlocomotion/drake/blob/158719cf2aeb63876142c0a616a97be23aebb88b/multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Minor: this is binding to a temporary if U != double. If that's your intention you should comment. Otherwise just drop the `&` to copy from double to U.
</blockquote></details>

nice catch!.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9007#-:-LFJ2qDdBTYbyjZx9XeC:b8l0uoa)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: 3 unresolved discussions, platform LGTM from [sherm1], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9007)*

**Comment by hongkai-dai** [comment]
Review status: all discussions resolved, platform LGTM from [sherm1], commit history needs curation

---

*[multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9007#-LF5rPM_4SssPq_nCzak:-LFJFSoW5NBRyBLKAm5S:by9dhnx) ([raw file](https://github.com/robotlocomotion/drake/blob/158719cf2aeb63876142c0a616a97be23aebb88b/multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

yes!, that is the reason. Another very important reason is that  `df/dx > 0`, always. That leads to the stability of the implicit Euler scheme. That is why I changed this function from the Stribeck function we have say, in RBT, to what we use here. Notice this only has one friction coefficients (i.e. there's no distinction between static and dynamic friction) 
</blockquote></details>

I see, that is very smart. I like this trick, very clever. Thanks for the explanation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9007)*

**Pull request merged**
