### PR TITLE
[geometry/dev] Client-Server API Doxygen documentation

### PR DESCRIPTION
**Pull request by svenevs**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16876)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
This is a work in progress transcription of `README.md` to doxygen documentation.  The main difference is "prettifying" output (made a `<table>`), and the order is switched -- the API is described first, and then description about how to use the test server and make your own comes next.  To view the documentation rendered on this PR, enable `dev` in doxygen configs:

```diff
diff --git a/doc/doxygen_cxx/Doxyfile_CXX.in b/doc/doxygen_cxx/Doxyfile_CXX.in
index 128f70260f..db41ea370f 100644
--- a/doc/doxygen_cxx/Doxyfile_CXX.in
+++ b/doc/doxygen_cxx/Doxyfile_CXX.in
@@ -130,8 +130,8 @@ FILE_PATTERNS          = *.h \
 RECURSIVE              = YES
 EXCLUDE                =
 EXCLUDE_SYMLINKS       = NO
-EXCLUDE_PATTERNS       = "@INPUT_ROOT@/*/dev/*" \
-                         "@INPUT_ROOT@/*/test/*" \
+# EXCLUDE_PATTERNS       = "@INPUT_ROOT@/*/dev/*"
+EXCLUDE_PATTERNS       = "@INPUT_ROOT@/*/test/*" \
                          "@INPUT_ROOT@/*/MG/*"
 EXCLUDE_SYMBOLS        = "*::internal" \
                          "pybind11"
```

and run `bazel run //doc/doxygen_cxx:build -- --serve drake.geometry.render drake.common drake.systems.sensors` (so that all of the links work).

Most of this was transcribed a while ago but we're close to being able to finalize it so opening now for people to begin review.  The end game of this PR is to land in dev, with the intent that the file is just `git mv`'d to where it should end up for platform.  But having the docs available for people for the rest of review is a good idea.

This is the dev version so +@zachfang for review please.

CC @jwnimmer-tri two questions for you directly

1. is `@defgroup render_engine_gltf_client_server_api glTF Render Client-Server API` and adding to `@ingroup render_engines` OK?
2. Note that per [the move render around slack thread](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1646937427862689), the `render_engines` (and say, `MakeRenderEngineVtk`) is linking to e.g., `RenderEngineVtk` so if those become `internal` then it will need to be updated.  I avoided any direct links to `RenderEngineGltfClient` as a result, that is not going to be in the docs right?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16876#-:-Mz2AEZy-m5XOr_6j4_J:b8qot4p)* status: 8 unresolved discussions, LGTM missing from assignee zachfang, labeled "do not merge", missing label for release notes (waiting on @zachfang)

___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DQHXA516EvzjGT5O:-Mz2DQHXA516EvzjGT5P:bz3u9uh) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L61)):*
> ```objc
>  RenderEngineGltfClientParams.  The returned RenderEngine implements the client
>  side of the @ref gltf_server_api.  The rules for supported geometries and
>  textures are described in MakeRenderEngineVtk(). */
> ```

TODO: add notes about curl initialization and links to scary curl docs about thread safety.
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2CmQXDThhy-3UGsGw:-Mz2CmQXDThhy-3UGsGx:b-lgyp9v) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L90)):*
> ```objc
> uploaded scene file, rendering the scene, and transmitting an image back to the
> client.  In addition to the scene file, the render endpoint is provided with the
> full specification of the systems::sensors::CameraInfo object.  Depending on the
> ```

I followed `render_doxygen.h` example and am currently in `namespace drake::geometry::render`.  I think that's why I cannot get `CameraInfo` without `systems::sensors::` prefix to link, is this preferable to `@ref`?
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2D98I3t7_GSxWmINK:-Mz2D98I3t7_GSxWmINL:b-xm419h) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L234)):*
> ```objc
>     <td>
>       Width of the desired rendered image in pixels as specified by the
>       systems::sensors::CameraInfo::width() being rendered, the server **must**
> ```

FYI this and subsequent descriptions are mostly identical to original README.md, just with links to the camera info related field.
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2Djg7AQNw4n2Kr-dc:-Mz2Djg7AQNw4n2Kr-dd:b6gduuu) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L341)):*
> ```objc
> 
> [flask]: https://flask.palletsprojects.com/en/2.0.x/
> [test_server]: https://github.com/RobotLocomotion/drake/blob/master/geometry/render/dev/test/gltf_render_server.py
> ```

link will need to update.  First of a few.  Should we just put in the final destinations now?  Hard to decide what makes things easiest for people to review, we can also just annotate as part of #16750 in a checklist that these need to update when moving out of `dev/`, so the PR would be a `git mv` and then a few link and target updates.
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 362 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DpHD0c0pJvSuCS8x:-Mz2DpHD0c0pJvSuCS8y:b-mnfepk) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L362)):*
> ```objc
> 
> For development purposes, you may run
> `bazel run //geometry/render/dev:gltf_render_server` to launch a single threaded
> ```

target will need to update
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 371 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DqjPEmfM5QxFqjhN:-Mz2DqjPEmfM5QxFqjhO:b-mnfepk) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L371)):*
> ```objc
> @code{.console}
> # Run on the default host and port.
> $ bazel run //geometry/render/dev:gltf_render_server
> ```

target will need to update
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 374 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DsTi4M3hy8KLCJOQ:-Mz2DsTjDolVSUyxAMUx:b-mnfepk) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L374)):*
> ```objc
> 
> # Run on custom host and port.
> $ bazel run //geometry/render/dev:gltf_render_server -- --host 0.0.0.0 --port 8192
> ```

target will need to update
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 382 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2Dtn74tK82jmfO_K-:-Mz2Dtn74tK82jmfO_K0:b-mnfepk) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L382)):*
> ```objc
> - In a separate terminal, run the test simulation:
>     - To see the scene with the normal VTK rendering:
>       `bazel run //geometry/render/dev:run_simulation_and_render -- --render_engine vtk`
> ```

target will need to update
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 384 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DvIWCP8LmUuDAn5y:-Mz2DvIWCP8LmUuDAn5z:b-mnfepk) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L384)):*
> ```objc
>       `bazel run //geometry/render/dev:run_simulation_and_render -- --render_engine vtk`
>     - To render over the server:
>       `bazel run //geometry/render/dev:run_simulation_and_render -- --render_engine client`
> ```

target will need to update

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please.

Ignore this test, verifying CI updates...

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16876)* status: 11 unresolved discussions, LGTM missing from assignee zachfang, labeled "do not merge", missing label for release notes (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N--0wOK-811LDA9p2l8:-N--0wOLA0ZmJQ8z3Zp_:b6doqmo) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L20)):*
> ```objc
>   std::optional<RenderLabel> default_label{};
> 
>   /** The url of the server communicate with.  Should **not** include a trailing
> ```

Maybe `to communicate`?
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-0TfAL9sgLlLN0pUPK:-N-0TfAL9sgLlLN0pUPL:b-o0k7kn) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L35)):*
> ```objc
> 
>   /** Whether or not the client should log information about which files are
>    being generated, information about HTTP communications being coordinated with
> ```

nit: maybe missing an `and` here? The following sentence isn't obvious to me.
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-0Uq_C2E8bGtKQP-Qh:-N-0Uq_C2E8bGtKQP-Qi:b1i4v0) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L42)):*
> ```objc
>   /** Whether or not the client should cleanup files generated / retrieved from
>    the server.  By default (`no_cleanup=false`), as soon as a glTF scene file
>    as well as server image response for a given frame is no longer needed they
> ```

nit: should this be
```
... a glTF scene file as well as server image response for a given frame ARE no longer needed they ...

```
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2Djg7AQNw4n2Kr-dc:-N-0c9qv13Ak7wzayBil:b9aehkz) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L341)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

link will need to update.  First of a few.  Should we just put in the final destinations now?  Hard to decide what makes things easiest for people to review, we can also just annotate as part of #16750 in a checklist that these need to update when moving out of `dev/`, so the PR would be a `git mv` and then a few link and target updates.
</blockquote></details>

I think we can leave the links as is. Since there might be some back and forth with the platform reviews, it makes more sense to me to update the link when it's time for this doc to graduate.

**Review by svenevs — COMMENTED** [review]
OK almost there with this one!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16876#-:-N-4nkun7XG8Aja-8NzT:bfqd61e)* status: 2 unresolved discussions, LGTM missing from assignee zachfang, labeled "do not merge", missing label for release notes (waiting on @zachfang)

___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N--0wOK-811LDA9p2l8:-N-4jJlgBdE0fDeYOkuN:b-gqs0mo) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L20)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Maybe `to communicate`?
</blockquote></details>

Hmmm, we could maybe find a different wording altogether?  Just say `The url of the server.`?  AFAICT this is the [intransitive (3) construction](https://www.oxfordlearnersdictionaries.com/us/definition/american_english/communicate): "I am communicating _with_ the server."  I don't think it's grammatically well formed if you just have `communicate` without anything after?  There's a couple of other locations I'd want to update this phrasing for, and probably for uniformity we should decide the `port` phrasing as well :slightly_smiling_face:
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-0TfAL9sgLlLN0pUPK:-N-4kokuEQo8ZmopFINx:bqxphow) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L35)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: maybe missing an `and` here? The following sentence isn't obvious to me.
</blockquote></details>

Done, fixed up the contraction and included a little more information.  Does this work?  We're trying to explain that setting `verbose=true` also triggers

https://github.com/RobotLocomotion/drake/blob/ed6613ec77bc1f4218aee37b76430d2cffcffdeb/geometry/render/dev/http_service_curl.cc#L142

which is all of curl's logging information, without enumerating ... all of that.
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-0Uq_C2E8bGtKQP-Qh:-N-4lIcF7Z_fx0S6Iez8:b2zdyb0) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L42)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: should this be
```
... a glTF scene file as well as server image response for a given frame ARE no longer needed they ...

```
</blockquote></details>

Done, yes it absolutely should be!
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DQHXA516EvzjGT5O:-N-4mKihAqXpJ8H4TLK1:b-ucn205) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L61)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

TODO: add notes about curl initialization and links to scary curl docs about thread safety.
</blockquote></details>

This has been completed, @zachfang can you read through this before I mark it as resolved please (new docs)?
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2CmQXDThhy-3UGsGw:-N-4mU8i26SFRo2Cj319:bu1bs34) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L90)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

I followed `render_doxygen.h` example and am currently in `namespace drake::geometry::render`.  I think that's why I cannot get `CameraInfo` without `systems::sensors::` prefix to link, is this preferable to `@ref`?
</blockquote></details>

Done, this will come up in platform if it is a problem.
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2Djg7AQNw4n2Kr-dc:-N-4m_y567UZEb1z0qyD:bv67jfp) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L341)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

I think we can leave the links as is. Since there might be some back and forth with the platform reviews, it makes more sense to me to update the link when it's time for this doc to graduate.
</blockquote></details>

OK, going to mark as resolved and just make a mental note that for platform review when this gets promoted there are a number of bazel targets and html links that will need to be updated in the promotion PR :+1:
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 362 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DpHD0c0pJvSuCS8x:-N-4n4sDC1D5VYAr9TQR:bqz8f2m) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L362)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

target will need to update
</blockquote></details>

Done per discussion above, this will update in the final PR.
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 371 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DqjPEmfM5QxFqjhN:-N-4n9E08c-nvrh9SZVb:bqz8f2m) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L371)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

target will need to update
</blockquote></details>

Done per discussion above, this will update in the final PR.
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 374 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DsTi4M3hy8KLCJOQ:-N-4n9m68kJdWytM0d1v:bqz8f2m) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L374)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

target will need to update
</blockquote></details>

Done per discussion above, this will update in the final PR.
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 382 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2Dtn74tK82jmfO_K-:-N-4nAPAA3ZiaNWE87lz:bu1qwwn) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L382)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

target will need to update
</blockquote></details>

Done per discussion above, this will update in the final PR.Done per discussion above, this will update in the final PR.
___
*[geometry/render/dev/render_gltf_client_doxygen.h, line 384 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DvIWCP8LmUuDAn5y:-N-4nDkYEP4dtKMTxbq5:bqz8f2m) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_gltf_client_doxygen.h#L384)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

target will need to update
</blockquote></details>

Done per discussion above, this will update in the final PR.

**Review by zachfang — COMMENTED** [review]
:lgtm:
Re-read all the changes with small suggestions.

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16876#-:-N-OBXsA32ZDmszmuzXw:b-f31mzm)* status: 2 unresolved discussions, labeled "do not merge", missing label for release notes (waiting on @svenevs)

___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N--0wOK-811LDA9p2l8:-N-Numu78MXKEZ7JPfh4:bv9utez) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L20)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Hmmm, we could maybe find a different wording altogether?  Just say `The url of the server.`?  AFAICT this is the [intransitive (3) construction](https://www.oxfordlearnersdictionaries.com/us/definition/american_english/communicate): "I am communicating _with_ the server."  I don't think it's grammatically well formed if you just have `communicate` without anything after?  There's a couple of other locations I'd want to update this phrasing for, and probably for uniformity we should decide the `port` phrasing as well :slightly_smiling_face:
</blockquote></details>

OK. We can keep it this way!
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DQHXA516EvzjGT5O:-N-O6YtKDVRjYChFCw4I:bl6vyi7) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L61)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

This has been completed, @zachfang can you read through this before I mark it as resolved please (new docs)?
</blockquote></details>

nit: to be consistent, do you consider using `server URL` instead of `server location`?
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 65 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-O8xnf6vno2roVSaav:-N-O8xnf6vno2roVSaaw:bv81p5v) ([raw file](https://github.com/robotlocomotion/drake/blob/6a31358fd1408efb78ba826acdc7e99720eeffae/geometry/render/dev/render_engine_gltf_client_factory.h#L65)):*
> ```objc
> 
>  @note
>    The underlying RenderEngine utilizes [libcurl][libcurl] to communicate with
> ```

BTW, the write-up is super clear to me. Thanks!
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-O7nzu1MMIh8whdOfP:-N-O7nzu1MMIh8whdOfQ:brfa0yb) ([raw file](https://github.com/robotlocomotion/drake/blob/6a31358fd1408efb78ba826acdc7e99720eeffae/geometry/render/dev/render_engine_gltf_client_factory.h#L96)):*
> ```objc
>    // Situation (2), if needed cleanup and re-initialize curl with your
>    // application's specific needs.
>    curl_global_cleanup();
> ```

nit: should we have a step in the Situation(2) that does the normal `auto render_engine = MakeRenderEngineGltfClient(params);` first to reiterate the doc above?

I am thinking:
```
  // Situation (2), if needed cleanup and re-initialize curl with your
  // application's specific needs.
  ...
  auto render_engine = MakeRenderEngineGltfClient(params);
  curl_global_cleanup();
  curl_global_init();  // <<< your custom flags here
```

or

```
  // Complete RenderEngine initialization first as Situation (1)
  curl_global_cleanup();
  curl_global_init();  // <<< your custom flags here
```

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16876)* status: 1 unresolved discussion, labeled "do not merge", missing label for release notes (waiting on @svenevs)

___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N--0wOK-811LDA9p2l8:-N-ObJDx0nz5Ix3GwnJR:b-vr0f48) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L20)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

OK. We can keep it this way!
</blockquote></details>

OK, works for me :+1:
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16876#-Mz2DQHXA516EvzjGT5O:-N-Oc4wa7ty5yWik8ROm:b-989b23) ([raw file](https://github.com/robotlocomotion/drake/blob/73dc21102e744c66ab7e4d8ebd9d12c30c25994a/geometry/render/dev/render_engine_gltf_client_factory.h#L61)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: to be consistent, do you consider using `server URL` instead of `server location`?
</blockquote></details>

Done, good call -- updated to use `url` rather than `location`!
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 65 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-O8xnf6vno2roVSaav:-N-Oc9zu5m7kpNbhKhQa:b-ra0xjj) ([raw file](https://github.com/robotlocomotion/drake/blob/6a31358fd1408efb78ba826acdc7e99720eeffae/geometry/render/dev/render_engine_gltf_client_factory.h#L65)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW, the write-up is super clear to me. Thanks!
</blockquote></details>

:partying_face: 
___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-O7nzu1MMIh8whdOfP:-N-Of-3X-Zk7TDTVCFVY:bjgk4vr) ([raw file](https://github.com/robotlocomotion/drake/blob/6a31358fd1408efb78ba826acdc7e99720eeffae/geometry/render/dev/render_engine_gltf_client_factory.h#L96)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: should we have a step in the Situation(2) that does the normal `auto render_engine = MakeRenderEngineGltfClient(params);` first to reiterate the doc above?

I am thinking:
```
  // Situation (2), if needed cleanup and re-initialize curl with your
  // application's specific needs.
  ...
  auto render_engine = MakeRenderEngineGltfClient(params);
  curl_global_cleanup();
  curl_global_init();  // <<< your custom flags here
```

or

```
  // Complete RenderEngine initialization first as Situation (1)
  curl_global_cleanup();
  curl_global_init();  // <<< your custom flags here
```

</blockquote></details>

Working, I agree that was a bit confusing.  Let me know what you think of the newest revision.  Though there is a bit of redundancy, I think it makes things clearer to just have two separate example code blocks rather than trying to keep things in one code block to try and explain two different situations.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16876)* status: 1 unresolved discussion, labeled "do not merge", missing label for release notes (waiting on @svenevs)

___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-O7nzu1MMIh8whdOfP:-N-On2XpBM8eocENxyFC:bb6ywmx) ([raw file](https://github.com/robotlocomotion/drake/blob/6a31358fd1408efb78ba826acdc7e99720eeffae/geometry/render/dev/render_engine_gltf_client_factory.h#L96)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, I agree that was a bit confusing.  Let me know what you think of the newest revision.  Though there is a bit of redundancy, I think it makes things clearer to just have two separate example code blocks rather than trying to keep things in one code block to try and explain two different situations.
</blockquote></details>

LGTM

**Review by svenevs — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16876#-:-N-Ot3cADgGzCaI3iaLW:bnfp4nl)* status: missing label for release notes (waiting on @svenevs)

___
*[geometry/render/dev/render_engine_gltf_client_factory.h, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16876#-N-O7nzu1MMIh8whdOfP:-N-Ot6Ft12zT9WEYfyMd:bb6ywmx) ([raw file](https://github.com/robotlocomotion/drake/blob/6a31358fd1408efb78ba826acdc7e99720eeffae/geometry/render/dev/render_engine_gltf_client_factory.h#L96)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

LGTM

**Pull request merged**
