### PR TITLE
Bump STX to latest and enable optional::has_value

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #8170.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8299)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review, please.  Note that this definition was already set for macOS (within the upstream header, based on Xcode version), so this effectively only a change on Ubuntu.

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[common/drake_optional.h, line 3 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8299#-L75KHqh48MxuUkSfbRi:-L75KHqh48MxuUkSfbRj:bvz3qht) ([raw file](https://github.com/robotlocomotion/drake/blob/b6efef3b5349353e43b108d9100e3a700db55bf4/common/drake_optional.h#L3)):*
> ```objc
> #pragma once
> 
> // As of our currently supported platforms (Ubuntu 16.04 Xenial and macOS 10.13
> ```

I guess you haven't checked macOS 10.12. Do you think running `common:drake_optional_test` target is a sufficient test there?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8299)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/drake_optional.h, line 3 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8299#-L75KHqh48MxuUkSfbRi:-L75LBqQB3teOjpZ2VOo:bzg3lfd) ([raw file](https://github.com/robotlocomotion/drake/blob/b6efef3b5349353e43b108d9100e3a700db55bf4/common/drake_optional.h#L3)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I guess you haven't checked macOS 10.12. Do you think running `common:drake_optional_test` target is a sufficient test there?
</blockquote></details>

Since forever on macOS, `std::bad_optional_access` is missing.  Does that help?  I guess I'm not sure what you're asking.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8299)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/drake_optional.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8299#-L75KHqh48MxuUkSfbRi:-L75LYKG6fR7lP2lYuNw:b-xc45vy) ([raw file](https://github.com/robotlocomotion/drake/blob/b6efef3b5349353e43b108d9100e3a700db55bf4/common/drake_optional.h#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Since forever on macOS, `std::bad_optional_access` is missing.  Does that help?  I guess I'm not sure what you're asking.
</blockquote></details>

Never mind, I didn't parse the whole paragraph when I asked the question. 

I recall the situation on Mac and see no problem now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8299)*

**Comment by soonho-tri** [comment]
:lgtm: 

FTR, the upstream change is from https://github.com/tcbrindle/cpp17_headers/pull/14.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8299#-:-L75N1VPbcmKuJ1GLVWd:b-wh792b)*

**Pull request merged**
