### PR TITLE
Add AggregateQuadraticCosts

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165#-:-MIju5hW7cElgpdw6AwD:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
I'll need some explanation about the situation or context here.  There is no issue number, rationale in the commit message, or file overview comment that explains why we should add an internal function that nothing calls.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165#-:-MItcrVnBvIiYknxP_sL:b-erd8qt)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/parse_mathematical_program.h, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItcWno1sO4iPAiBMjd:-MItcWno1sO4iPAiBMje:b-425zh4) ([raw file](https://github.com/robotlocomotion/drake/blob/88e7862dde62d3f80607e5368e5783e618052d9e/solvers/parse_mathematical_program.h#L2)):*
> ```objc
> #pragma once
> /** This file contains helper functions to parse a MathematicalProgram object to
> ```

nit Don't use `/**` -- we don't want to add an API comment for `namespace drake {`.
___
*[solvers/parse_mathematical_program.h, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItcb0k9M92Pu9c9Qc1:-MItcb0l76NEhT2W0_De:b90jy74) ([raw file](https://github.com/robotlocomotion/drake/blob/88e7862dde62d3f80607e5368e5783e618052d9e/solvers/parse_mathematical_program.h#L3)):*
> ```objc
> #pragma once
> /** This file contains helper functions to parse a MathematicalProgram object to
>  * solvers. The functions in this file are for internal usage only
> ```

nit Punctuation.
___
*[solvers/parse_mathematical_program.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItce5i-cRXT4zIjhoD:-MItce5i-cRXT4zIjhoE:b-i7wkst) ([raw file](https://github.com/robotlocomotion/drake/blob/88e7862dde62d3f80607e5368e5783e618052d9e/solvers/parse_mathematical_program.h#L14)):*
> ```objc
> namespace solvers {
> namespace internal {
> /**
> ```

nit Don't use `/**` style on internal namespace; a `/*` would be fine.

**Review by hongkai-dai — COMMENTED** [review]
I modified the commit message to explain the rationale for this commit.

I created this commit to handle the `Mosek with quadratic cost` PR you reviewed a while ago https://reviewable.io/reviews/RobotLocomotion/drake/14129#- I decided to support quadratic cost in Mosek, that first I aggregate all the quadratic costs into one quadratic cost, and then convert the aggregated quadratic cost into a Lorentz cone constraint with linear cost. I will file another PR once this one is merged, and in that follow-up PR it will use this `AggregatedQuadraticCost` function. This function will also be useful later, when we integrate the Conex solver into Drake.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165#-:-MItfEAA2t6oFzcFuuPe:bertnrh)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM so far.

I still need to go back and double-check the mathematics in the unit test.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165#-:-MIu377o4LEuxadhDfr8:b-qz0uhn)* status: 8 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/parse_mathematical_program.h, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItxEVy28ENiHqFhl27:-MItxEVzDwnGN6Yv9yG-:b-xfw7aj) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.h#L1)):*
> ```objc
> #pragma once
> ```

This filename is both odd -- "parse" is usually about going from something into a `MathematicalProgram`, not the other way around.

Maybe we could call this `aggregate_quadratic_costs.h` or `internal_aggregate_quadratic_costs.h`?
___
*[solvers/parse_mathematical_program.h, line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItxvQY2QcIZkILD3Xk:-MItxvQY2QcIZkILD3Xl:bigpa84) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.h#L5)):*
> ```objc
> // solvers. The functions in this file are for internal usage only.
> 
> #include <vector>
> ```

nit Unused `<vector>` (move to cc file).
___
*[solvers/parse_mathematical_program.cc, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItzMTJ3X7oEHqC5CYd:-MItzMTJ3X7oEHqC5CYe:b6zjdhm) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L25)):*
> ```cpp
>     Q_lower_triplets.reserve(Q_lower_triplets.size() +
>                              (num_cost_var + 1) * num_cost_var / 2);
>     linear_coeff_triplets.reserve(linear_coeff_triplets.size() + num_cost_var);
> ```

It's not clear to me why reserving small `vector` chunks of the triplets at we loop (linear number of allocations) is better than allowing the vector to do is normal exponential growth as we append to it (logarithmic number of allocations)?  It seems like we should just remove the two prior lines.
___
*[solvers/parse_mathematical_program.cc, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu151KETrUaDIc37Dm:-MIu151KETrUaDIc37Dn:b-npjm2f) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L32)):*
> ```cpp
>     for (int i = 0; i < num_cost_var; ++i) {
>       int var_index = -1;
>       auto it = var_to_index_map.find(quadratic_cost.variables()(i).get_id());
> ```

nit We say `quadratic_cost.variables()(i)` three times within this loop.  I suspect it would read more clearly if we captured that result into a named local variable.
___
*[solvers/parse_mathematical_program.cc, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu0ghM0-DQwxSvItfs:-MIu0ghM0-DQwxSvItft:buueu87) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L38)):*
> ```cpp
>         var_index = num_vars;
>         var_to_index_map.emplace_hint(
>             it, quadratic_cost.variables()(i).get_id(), num_vars);
> ```

nit Saying "var_index" here instead of "num_vars" would be much more clear to me as a reader.
___
*[solvers/parse_mathematical_program.cc, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItynkq2H82L6hE0AiX:-MItynkr-vXHWurqlO1f:b-t112hu) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L63)):*
> ```cpp
>   Q_lower->setFromTriplets(Q_lower_triplets.begin(), Q_lower_triplets.end());
>   *linear_coeff = Eigen::SparseVector<double>(num_vars);
>   linear_coeff->setZero();
> ```

nit I think setZero on an empty sparse vector is a no-op?
___
*[solvers/parse_mathematical_program.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu2DF-BsHz-yC2TQ-4:-MIu2DF-BsHz-yC2TQ-5:bqiree0) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L67)):*
> ```cpp
>     linear_coeff->coeffRef(triplet.row()) += triplet.value();
>   }
>   vars->conservativeResize(num_vars);
> ```

I'm not sure what this line is doing?  To my eye, its size is already `== num_vars` at this point.  Should this be a `DRAKE_DEMAND` instead?
___
*[solvers/test/parse_mathematical_program_test.cc, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu2sH0Bk95gyKlo9un:-MIu2sH0Bk95gyKlo9uo:bj6ro9r) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/test/parse_mathematical_program_test.cc#L52)):*
> ```cpp
>   Eigen::Vector3d b2(0.1, 0, 0.5);
>   double c2 = 0.4;
>   const Vector3<symbolic::Variable> vars2(x[2], x[1], x[3]);
> ```

nit Use `const` on the above 3 lines.  We used it above, and this function is very long so it's important to note what's mutable.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/parse_mathematical_program.h, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItxEVy28ENiHqFhl27:-MIvAnQAB6PSixUWpDK-:b-k1j63g) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.h#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This filename is both odd -- "parse" is usually about going from something into a `MathematicalProgram`, not the other way around.

Maybe we could call this `aggregate_quadratic_costs.h` or `internal_aggregate_quadratic_costs.h`?
</blockquote></details>

I am hesitant to name it `aggregate_quadratic_costs.h`. I think later I will add a function to aggregate the linear costs (sum up each individual linear costs), and also a function to aggregate the bounding box constraints (find the tightest bound for each variable across all bounding box constraints). 

What about "aggregate_costs_constraints.h`?
___
*[solvers/parse_mathematical_program.cc, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItzMTJ3X7oEHqC5CYd:-MIvj2DE-XPOahxRk-QN:b37jaxy) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's not clear to me why reserving small `vector` chunks of the triplets at we loop (linear number of allocations) is better than allowing the vector to do is normal exponential growth as we append to it (logarithmic number of allocations)?  It seems like we should just remove the two prior lines.
</blockquote></details>

Thanks! I didn't realize just using `push_back` is the more efficient way, until I saw your comment and read the article https://www.drdobbs.com/c-made-easier-how-vectors-grow/184401375

So I guess there is just not a very good reason to use `reserve`, unless I either know the actual size very precisely (in that case I should just use `resize`), or I reserve a very large amount of memory?
___
*[solvers/parse_mathematical_program.cc, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu151KETrUaDIc37Dm:-MIvtms0AL-W3YkL38se:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We say `quadratic_cost.variables()(i)` three times within this loop.  I suspect it would read more clearly if we captured that result into a named local variable.
</blockquote></details>

Done.
___
*[solvers/parse_mathematical_program.cc, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu0ghM0-DQwxSvItfs:-MIvttIWEULSSud9HCrl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Saying "var_index" here instead of "num_vars" would be much more clear to me as a reader.
</blockquote></details>

Done.
___
*[solvers/parse_mathematical_program.cc, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItynkq2H82L6hE0AiX:-MIvtyfM-cbx1q-2Cnqm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think setZero on an empty sparse vector is a no-op?
</blockquote></details>

Done.
___
*[solvers/parse_mathematical_program.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu2DF-BsHz-yC2TQ-4:-MIvu0_02BVBaa1TEv7u:b-beluz3) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure what this line is doing?  To my eye, its size is already `== num_vars` at this point.  Should this be a `DRAKE_DEMAND` instead?
</blockquote></details>

Not really. For each `quadratic_cost`, we resize `vars` to `vars.size() + quadratic_cost.variables().rows()`. If a variable in `quadratic_cost.variables()` hasn't shown up in `vars` before, then we append it to `vars`. If it has shown in `vars` before, then we do nothing, and the last few entries in `vars` would be empty. Thus the size of `vars`  can be larger than `num_vars`. 

One example is that if we have two costs `x² + y²` and `y²`, notice that `y` show up in both costs. Then before this line `vars.rows() = 3` since the first cost has two variables, and the second cost has one variables. But `num_vars = 2`. In other words, `num_vars` considers shared variables across different costs, while `vars` hasn't.

I added some documentations, hopefully it is more clear.
___
*[solvers/test/parse_mathematical_program_test.cc, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu2sH0Bk95gyKlo9un:-MIvvlUO-XKh7y5OAw6G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/test/parse_mathematical_program_test.cc#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Use `const` on the above 3 lines.  We used it above, and this function is very long so it's important to note what's mutable.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/parse_mathematical_program.h, line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItxvQY2QcIZkILD3Xk:-MIwKFiQBw-jd6G_HCIA:b6r7fxc) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.h#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unused `<vector>` (move to cc file).
</blockquote></details>

I think `<vector>` is used, as the input argument to `AggregateQuadraticCosts` include `std::vector<Binding<QuadraticCost>>`

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165#-:-MIyrBqv4KwVt_598unu:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/parse_mathematical_program.h, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItxEVy28ENiHqFhl27:-MIyFUt6DC2ujQvvvd7A:b-ra74ya) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.h#L1)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am hesitant to name it `aggregate_quadratic_costs.h`. I think later I will add a function to aggregate the linear costs (sum up each individual linear costs), and also a function to aggregate the bounding box constraints (find the tightest bound for each variable across all bounding box constraints). 

What about "aggregate_costs_constraints.h`?
</blockquote></details>

Fine by me.
___
*[solvers/parse_mathematical_program.cc, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItzMTJ3X7oEHqC5CYd:-MIyFZax6vkxB07swkUE:b-hq0tcf) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L25)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks! I didn't realize just using `push_back` is the more efficient way, until I saw your comment and read the article https://www.drdobbs.com/c-made-easier-how-vectors-grow/184401375

So I guess there is just not a very good reason to use `reserve`, unless I either know the actual size very precisely (in that case I should just use `resize`), or I reserve a very large amount of memory?
</blockquote></details>

It can be useful to call `reserve` once ahead of looping, if you know a safe upper limit on memory.
___
*[solvers/parse_mathematical_program.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu2DF-BsHz-yC2TQ-4:-MIyqL5U3NqefRiw1qVR:ba3zxd9) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L67)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not really. For each `quadratic_cost`, we resize `vars` to `vars.size() + quadratic_cost.variables().rows()`. If a variable in `quadratic_cost.variables()` hasn't shown up in `vars` before, then we append it to `vars`. If it has shown in `vars` before, then we do nothing, and the last few entries in `vars` would be empty. Thus the size of `vars`  can be larger than `num_vars`. 

One example is that if we have two costs `x² + y²` and `y²`, notice that `y` show up in both costs. Then before this line `vars.rows() = 3` since the first cost has two variables, and the second cost has one variables. But `num_vars = 2`. In other words, `num_vars` considers shared variables across different costs, while `vars` hasn't.

I added some documentations, hopefully it is more clear.
</blockquote></details>

OK Yes, I can follow it now.

It is a bit awkward to use `VectorX` for an incrementally-growing container type, though.  You might consider just using `std::vector<>` like everything else in those loops (the triplets, etc.) to simplify the logic, and then copy it to `VectorX` at the very end.  That would also get rid of carefully tracking `num_vars` separately.
___
*[solvers/test/parse_mathematical_program_test.cc, line 43 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIyr7C256C6UDW_fYUL:-MIyr7C35BkXYFQdUCu0:b-vl92d1) ([raw file](https://github.com/robotlocomotion/drake/blob/fda63abed02c9c33c1cc5f74432c158a9b7cf4c3/solvers/test/parse_mathematical_program_test.cc#L43)):*
> ```cpp
>   EXPECT_EQ(constant_cost, c1);
> 
>   // Now test multiple costs. These costs share variables.
> ```

I still need to review the arithmetic below.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/test/parse_mathematical_program_test.cc, line 21 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIyvZH71Sx0ZIEvnWc3:-MIyvZH71Sx0ZIEvnWc4:b-wupa3s) ([raw file](https://github.com/robotlocomotion/drake/blob/fda63abed02c9c33c1cc5f74432c158a9b7cf4c3/solvers/test/parse_mathematical_program_test.cc#L21)):*
> ```cpp
>   std::vector<Binding<QuadraticCost>> quadratic_costs;
>   Eigen::Matrix2d Q1;
>   Q1 << 1, 2, 2, 3;
> ```

nit Please format the whitespace to match the matrix (with a newline after the first row).  Spelling it out linearly is difficult to read.
___
*[solvers/test/parse_mathematical_program_test.cc, line 48 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIyvqUEBkzx6cprnE42:-MIyvqUEBkzx6cprnE43:b-xhkxpg) ([raw file](https://github.com/robotlocomotion/drake/blob/fda63abed02c9c33c1cc5f74432c158a9b7cf4c3/solvers/test/parse_mathematical_program_test.cc#L48)):*
> ```cpp
>   Q2 << 1, 0.2, 3,
>         0.2, 2, 0,
>         3, 0, 0.1;
> ```

nit Please align the whitespace columns to match the matrix.  The alike digits (e.g. ones places) should line up vertically.  An easy way to do this is to type out the same precision for all entries.

Ditto for Q_expected below.
___
*[solvers/test/parse_mathematical_program_test.cc, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIywAks2sSpAzQucX0O:-MIywAktDFgjQCHP8L15:baxh2rg) ([raw file](https://github.com/robotlocomotion/drake/blob/fda63abed02c9c33c1cc5f74432c158a9b7cf4c3/solvers/test/parse_mathematical_program_test.cc#L67)):*
> ```cpp
>                 2, 4, 0, 0,
>                 0, 0.2, 2, 0,
>                 0, 3, 0, 0.1;
> ```

I found it very time-consuming to match this expected result up with the Q1 and Q2 above.  In part that was because they are all formatted differently, but also we reuse numbers like "2" in both Q1 and Q2 so I have to go back and untangle all of the row alignment on scratch paper to check.

There are a few different ways to untangle this so it's clearer, depending on your preference:
- Layout the matrix literals the same whitespace everywhere.
- Change the input digits to be unique, or even better use numbers where their pairwise sums are unique (e.g. 10, 20, 1, 2 -- if we see "11" we know where it came from, vs 12, vs 21, etc.).
- Change the expected matrix to use `Q1(1, 1) + Q2(0, 0)` expressions as matrix elements, instead of their sum `4`.
- Choose Q1 and Q2 literals that exactly denote either which Q row & col they come from, or which indices of `x` they multiply with.  So "100" could be "Q1, row 0, col 0" for example and "200.11" could be "Q2, row 1, col 1".  Or likewise for which x they match.  (The symmetry requirement makes this a bit trickier than usual.)
- Walk through in comments (with some math, probably) how Q_expected is obtained.

Any of these solutions (or other similar ideas) would be fine.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/parse_mathematical_program.h, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MItxEVy28ENiHqFhl27:-MJ-dOGi2gR6g_uiMrXZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.h#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Fine by me.
</blockquote></details>

Done.
___
*[solvers/parse_mathematical_program.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIu2DF-BsHz-yC2TQ-4:-MJ-eIJaADZXEqd5May2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8e2271e33df07195380ebbdea1ac63c5951c7a8/solvers/parse_mathematical_program.cc#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Yes, I can follow it now.

It is a bit awkward to use `VectorX` for an incrementally-growing container type, though.  You might consider just using `std::vector<>` like everything else in those loops (the triplets, etc.) to simplify the logic, and then copy it to `VectorX` at the very end.  That would also get rid of carefully tracking `num_vars` separately.
</blockquote></details>

Done.
___
*[solvers/test/parse_mathematical_program_test.cc, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MIywAks2sSpAzQucX0O:-MJ-fv5PAPCP3BvKHbKL:b-phfjru) ([raw file](https://github.com/robotlocomotion/drake/blob/fda63abed02c9c33c1cc5f74432c158a9b7cf4c3/solvers/test/parse_mathematical_program_test.cc#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I found it very time-consuming to match this expected result up with the Q1 and Q2 above.  In part that was because they are all formatted differently, but also we reuse numbers like "2" in both Q1 and Q2 so I have to go back and untangle all of the row alignment on scratch paper to check.

There are a few different ways to untangle this so it's clearer, depending on your preference:
- Layout the matrix literals the same whitespace everywhere.
- Change the input digits to be unique, or even better use numbers where their pairwise sums are unique (e.g. 10, 20, 1, 2 -- if we see "11" we know where it came from, vs 12, vs 21, etc.).
- Change the expected matrix to use `Q1(1, 1) + Q2(0, 0)` expressions as matrix elements, instead of their sum `4`.
- Choose Q1 and Q2 literals that exactly denote either which Q row & col they come from, or which indices of `x` they multiply with.  So "100" could be "Q1, row 0, col 0" for example and "200.11" could be "Q2, row 1, col 1".  Or likewise for which x they match.  (The symmetry requirement makes this a bit trickier than usual.)
- Walk through in comments (with some math, probably) how Q_expected is obtained.

Any of these solutions (or other similar ideas) would be fine.
</blockquote></details>

Done. thanks for the suggestion.

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165#-:-MJ-hIZJ2AoqRO8D6cyn:b-c9pjop)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165#-:-MJ3XysD6-saP_lspwdy:bnfp4nl)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[solvers/aggregate_costs_constraints.h, line 2 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MJ3TPKI1kFCAAsI0CCc:-MJ3TPKI1kFCAAsI0CCd:be2f7mr) ([raw file](https://github.com/robotlocomotion/drake/blob/8361734cb9d9bd02e6fd9c5ef1a92025e1b2a2be/solvers/aggregate_costs_constraints.h#L2)):*
> ```objc
> #pragma once
> // This file contains helper functions to parse a MathematicalProgram object to
> ```

Is this comment stale?  I don't see anything in this function which deals with `MathematicalProgram` objects at all.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @sammy-tri)

___
*[solvers/aggregate_costs_constraints.h, line 2 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14165#-MJ3TPKI1kFCAAsI0CCc:-MJ7zr8G12QliGYpPU7s:b-s9ewq5) ([raw file](https://github.com/robotlocomotion/drake/blob/8361734cb9d9bd02e6fd9c5ef1a92025e1b2a2be/solvers/aggregate_costs_constraints.h#L2)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this comment stale?  I don't see anything in this function which deals with `MathematicalProgram` objects at all.
</blockquote></details>

Done. I removed it.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165)* status: 1 unresolved discussion (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14165)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
