### PR TITLE
Add very basic SDP bindings in python

### PR DESCRIPTION
**Pull request by rdeits**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6246)

### CODE REVIEW

**Comment by RussTedrake** [comment]
n.b. @weiqiao has some local edits to resolve the build issues.

**Comment by weiqiao** [comment]
Russ fixed the build error by replacing 
`const Eigen::ref<const MatrixXd>&))`
with
`const Eigen::Ref<const MatrixXDecisionVariable>&)) `

I don't know how to push it here. 

After the change, when I executed the test line by line, I got error the following error at the line `prog.AddPositiveSemidefiniteConstraint(S)`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unable to convert function return value to a Python type! The signature was
	(self: pydrake.solvers._pydrake_mathematicalprogram.MathematicalProgram, arg0: numpy.ndarray[object[m, n]]) -> drake::solvers::Binding<drake::solvers::PositiveSemidefiniteConstraint>`

**Comment by rdeits** [comment]
Yeah, sorry, this is what I get for trying to edit files without having a local build.

**Comment by weiqiao** [comment]
"Ref" should be uppercase, isn't it?

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by EricCousineau-TRI** [comment]
@rdeits Is this PR still relevant? Looks like it could be easily rebased onto `master` (with maybe some minor changes).

Would you like me to handle this?

**Comment by rdeits** [comment]
I believe this is still useful, yeah (although I'm not currently doing any work with SDPs). I'd be thrilled to have you rebase it, if you've got time.

**Comment by EricCousineau-TRI** [comment]
@rdeits Are you OK with me closing this in lieu of #7902?

**Pull request closed without merging**
