### PR TITLE
Remove some AxisAngle functionality and replace it with AngleAxis functionality.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8524)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 
Platform review +@sherm1 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-:-L9NA7G6-9YeKJdnvl-K:b-ycr44k)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by hongkai-dai** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524)*

**Comment by sherm1** [comment]
Really nice to see this old code evaporating! :lgtm: with a few BTWs, ptal.

---

Reviewed 4 of 9 files at r1, 6 of 7 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/api/lane_data.h, line 54 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-L9RUaG92jmcWII32Vhz:-L9RUaG92jmcWII32Vi-:bkifojd) ([raw file](https://github.com/robotlocomotion/drake/blob/98aa0b06dfa7f267c1ac34e280ec70f11d067afc/automotive/maliput/api/lane_data.h#L54)):*
> ```objc
> 
> /// A 3-dimensional rotation.
> class Rotation {
> ```

BTW Arggh. Disappointing to see this class here. Maybe a TODO to replace it with RotationMatrix? (Have a look at the API to see if it could be replaced easily.)

---

*[math/quaternion.h, line 206 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-L9RFOr7DiVdaDzY7MlN:-L9RFOr7DiVdaDzY7MlO:b-eyy75m) ([raw file](https://github.com/robotlocomotion/drake/blob/98aa0b06dfa7f267c1ac34e280ec70f11d067afc/math/quaternion.h#L206)):*
> ```objc
> 
> /**
>  * Computes SpaceXYZ Euler angles from quaternion representation.
> ```

BTW consider "Computes SpaceXYZ Euler angles _(RPY)_ from ..." so a robot person looking for a method in doxygen will see the familiar "RPY" here.

---

*[math/random_rotation.h, line 39 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-L9RTpBr9VeigcvpC5k2:-L9RTpBr9VeigcvpC5k3:b-h50nq6) ([raw file](https://github.com/robotlocomotion/drake/blob/98aa0b06dfa7f267c1ac34e280ec70f11d067afc/math/random_rotation.h#L39)):*
> ```objc
> template <class Generator>
> // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> Eigen::Vector4d UniformlyRandomQuat(Generator& generator) {
> ```

FYI random thought: you could create a new method now `UniformlyRandomQuaternion` that returns and Eigen::Quaternion. Then this method could remain temporarily but you could use the new one below and anywhere else where the switch is easy.

---

*[math/random_rotation.h, line 62 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-L9RAD7g0VJo9iNpXct7:-L9RAD7g0VJo9iNpXct8:bdu8fjh) ([raw file](https://github.com/robotlocomotion/drake/blob/98aa0b06dfa7f267c1ac34e280ec70f11d067afc/math/random_rotation.h#L62)):*
> ```objc
> Eigen::Vector3d UniformlyRandomRPY(Generator& generator) {
>   const Eigen::AngleAxisd angle_axis = UniformlyRandomAngleAxis(generator);
>   const Eigen::Quaterniond q(angle_axis);
> ```

BTW should have a TODO here to replace this with a call to UniformlyRandomQuat when that returns a real Quaternion.

---

*[math/test/rotation_conversion_test.cc, line 370 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-L9RAgSE7FSVlradUF1S:-L9RAgSE7FSVlradUF1T:b-gnsmnc) ([raw file](https://github.com/robotlocomotion/drake/blob/98aa0b06dfa7f267c1ac34e280ec70f11d067afc/math/test/rotation_conversion_test.cc#L370)):*
> ```cpp
> 
>   void setupRotationMatrixTestCases() {
>     for (const Vector3d& rpyi : rpy_test_cases_) {
> ```

BTW since you're making changes here please make name styleguide-compliant (needs an initial cap). 

---

*[math/test/rotation_conversion_test.cc, line 470 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-L9RTRG47WB4l6g2j9J8:-L9RTRG47WB4l6g2j9J9:b-y1e9qz) ([raw file](https://github.com/robotlocomotion/drake/blob/98aa0b06dfa7f267c1ac34e280ec70f11d067afc/math/test/rotation_conversion_test.cc#L470)):*
> ```cpp
>   for (const Vector3d& rpyi : rpy_test_cases_) {
>     const Vector3d bodyZYX_angles(rpyi(2), rpyi(1), rpyi(0));
>     const Eigen::Quaterniond q = BodyZYXAnglesToEigenQuaternion(bodyZYX_angles);
> ```

BTW surprised to see BodyZYX here -- looks like you standardized on SpaceXYZ elsewhere. Maybe switch this for consistency?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-:-L9RX2spAV7Os4Gp3VrL:b-6erxqc)*

**Comment by sherm1** [comment]
One new BTW ...

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[math/test/rotation_conversion_test.cc, line 69 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-L9RspQB7A5fpPR81jsr:-L9RspQB7A5fpPR81jss:b2v90st) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3b81c3ba7d66b7ef7faaa7db1cad5badae3a13/math/test/rotation_conversion_test.cc#L69)):*
> ```cpp
>   const T y = c0 * s1 * c2 + s0 * c1 * s2;
>   const T z = c0 * c1 * s2 - s0 * s1 * c2;
>   return Eigen::Quaternion<T>(w, x, y, z);
> ```

BTW couldn't you just switch the order in the original code so it reads:
```c++
return AngleAxisd(rpy(2), Vector3d::UnitZ()) *
       AngleAxisd(rpy(1), Vector3d::UnitY()) *
       AngleAxisd(rpy(0), Vector3d::UnitX());
```
? That seems much better than spelling it out elementwise (can't see immediately any more that this is correct), and since this is a test case there is no performance advantage. Or is this a better test for some reason?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8524#-:-L9RubM8-qRO_GZGkevr:b-lq2cq4)*

**Pull request merged**
