### PR TITLE
[doc] Drop Focal as a supported platform

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This doesn't yet rip it out of the code or Jenkins, rather just the docs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20952)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@svenevs or +@BetsyMcPhail for feature review, please.

**Review by svenevs — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20952)* status: 1 unresolved discussion, LGTM missing from assignees svenevs,BetsyMcPhail, needs platform reviewer assigned

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20952#-NqiNC7T8sbe41c3kiMR:-NqiNC7T8sbe41c3kiMS:br1xzl2) (no related file):*
working, some others possibly worth considering for this PR:

```
doc/\_pages/buildcop.md:175:- \[https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-continuous-release/lastBuild/consoleFull\](https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-continuous-release/lastBuild/consoleFull)

doc/\_pages/jenkins.md:154:\* \`\`@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please\`\`

doc/\_pages/release\_playbook.md:130: - \[Linux Wheel Staging\](https://drake-jenkins.csail.mit.edu/view/Staging/job/linux-focal-unprovisioned-gcc-wheel-staging-release/)

doc/\_pages/troubleshooting.md:149:When installing Drake from PyPI on older platforms such as Ubuntu Focal,

doc/\_release-notes/template.txt:122:\`\`drake-{version}-{{focal|jammy|mac|mac-arm64}}.tar.gz\`\`. See \[Stable Releases\](/from\_binary.html#stable-releases) for instructions on how to use them.

  

examples/hydroelastic/spatula\_slip\_control/README.md:111:Ubuntu Focal, not Jammy.

  

tools/release\_engineering/dev/README.md:20:\*\*Warning:\*\* When running this process on on Focal, \`aptly\` will need to be

tools/release\_engineering/dev/README.md:91:configuration (e.g. focal, jammy and mac).

tools/release\_engineering/dev/README.md:94:has \`<version>\` tags for each supported configuration (e.g. focal and jammy).

tools/release\_engineering/dev/README.md:98:\`/<configuration>/drake-dev\_<version>-1\_amd64.deb\` for each supported configuration (e.g. focal and jammy)

  

tools/workspace/README.md:249:- \`setup/ubuntu/binary\_distribution/packages-focal.txt\` with the \`libfoo0\`

tools/workspace/README.md:251:- \`setup/ubuntu/source\_distribution/packages-focal.txt\` with the \`libfoo-dev\`
```

However, this doesn't necessarily need to block here, e.g., "fixup all `tools/release_engineering` in one batch"

___
___
*[`doc/_pages/pip.md` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20952#-NqiMzHiE1jogRPD8Liq:-NqiMzHiE1jogRPD8Lir:b-13r64h) ([raw file](https://github.com/RobotLocomotion/drake/blob/295eb0f07591f932e06ffd5c3576b51409ebfd7d/doc/_pages/pip.md#L47)):*
> ```Markdown
> ```bash
> python3 -m venv env
> env/bin/pip install --upgrade pip
> ```

FYI NICE! These can finally go away :slightly_smiling_face:

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20952#-:-Nqiitws94hGT7a56wwa:b-1krawd)* status: 1 unresolved discussion, LGTM missing from assignees svenevs,sammy-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20952#-NqiNC7T8sbe41c3kiMR:-NqiY_5r8t583b5gxdLb:bn79k93) (no related file):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, some others possibly worth considering for this PR:

```
doc/\_pages/buildcop.md:175:- \[https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-continuous-release/lastBuild/consoleFull\](https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-continuous-release/lastBuild/consoleFull)

doc/\_pages/jenkins.md:154:\* \`\`@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please\`\`

doc/\_pages/release\_playbook.md:130: - \[Linux Wheel Staging\](https://drake-jenkins.csail.mit.edu/view/Staging/job/linux-focal-unprovisioned-gcc-wheel-staging-release/)

doc/\_pages/troubleshooting.md:149:When installing Drake from PyPI on older platforms such as Ubuntu Focal,

doc/\_release-notes/template.txt:122:\`\`drake-{version}-{{focal|jammy|mac|mac-arm64}}.tar.gz\`\`. See \[Stable Releases\](/from\_binary.html#stable-releases) for instructions on how to use them.

  

examples/hydroelastic/spatula\_slip\_control/README.md:111:Ubuntu Focal, not Jammy.

  

tools/release\_engineering/dev/README.md:20:\*\*Warning:\*\* When running this process on on Focal, \`aptly\` will need to be

tools/release\_engineering/dev/README.md:91:configuration (e.g. focal, jammy and mac).

tools/release\_engineering/dev/README.md:94:has \`<version>\` tags for each supported configuration (e.g. focal and jammy).

tools/release\_engineering/dev/README.md:98:\`/<configuration>/drake-dev\_<version>-1\_amd64.deb\` for each supported configuration (e.g. focal and jammy)

  

tools/workspace/README.md:249:- \`setup/ubuntu/binary\_distribution/packages-focal.txt\` with the \`libfoo0\`

tools/workspace/README.md:251:- \`setup/ubuntu/source\_distribution/packages-focal.txt\` with the \`libfoo-dev\`
```

However, this doesn't necessarily need to block here, e.g., "fixup all `tools/release_engineering` in one batch"
</blockquote></details>

For buildcop & jenkins & playbook: I'll let the CI switch (#20594) own that part.  Any edits there will need to be sync'd with `drake-ci` changes.

For troubleshooting: I added a comment to clarify (and cleaned up the text).

For notes template: Fixed.

For examples, I'll defer to a future PR.  It's somewhat complicated.

For release engineering: I'll let the CI switch (#20594) own that part.  Any edits there will need to be sync'd with `drake-ci` changes.

For workspace: Fixed.

___

**Review by svenevs — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20952#-:-NqirQj8ACukWgHjJrFO:bg7igkv)* status: LGTM missing from assignee sammy-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20952#-NqiNC7T8sbe41c3kiMR:-NqirNGV5z3g3l5l7lIr:bnchnmj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For buildcop & jenkins & playbook: I'll let the CI switch (#20594) own that part.  Any edits there will need to be sync'd with `drake-ci` changes.

For troubleshooting: I added a comment to clarify (and cleaned up the text).

For notes template: Fixed.

For examples, I'll defer to a future PR.  It's somewhat complicated.

For release engineering: I'll let the CI switch (#20594) own that part.  Any edits there will need to be sync'd with `drake-ci` changes.

For workspace: Fixed.
</blockquote></details>

done, excellent, the above sounds like a great plan to me!

___

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20952)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20952#-:-NqxAt4U9SnHhJfcX_L9:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),svenevs

**Pull request merged**
