### PR TITLE
MeshcatVisualizer sets visibility directly without events

### PR DESCRIPTION
**Pull request by RussTedrake**
Previously, the visibility parameter was not respected (a) before the initialization event or (b) if delete_on_initialization_event was false.

+@jwnimmer-tri for both reviews, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19578)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19578)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19578#-NXlJ58U4QHIcTMvF9Oy:-NXlJ58U4QHIcTMvF9Oz:b-bg9uih) (no related file):*
See https://github.com/RussTedrake/drake/pull/50.

Changing the visibility should be congruent with sending the initial batch of geometry.  There is no need to send it prior to that.

___

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19578)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19578#-NXlJ58U4QHIcTMvF9Oy:-NXmTq2e8IQ9-A1g8msM:b-uz07h0) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

See https://github.com/RussTedrake/drake/pull/50.

Changing the visibility should be congruent with sending the initial batch of geometry.  There is no need to send it prior to that.
</blockquote></details>

I reviewed and like that change.  Thanks.  How should we finish out the review process?

___

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature review.

+@rpoyner-tri for platform review per schedule, please.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19578#-:-NXmZpB0-91cbgNferth:beqph7n)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19578#-NXlJ58U4QHIcTMvF9Oy:-NXmZJSq93QyCz1mDN2o:b-m7tbpd) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I reviewed and like that change.  Thanks.  How should we finish out the review process?
</blockquote></details>

I think we can treat it as co-author and co-feature-reviewer, so all we'll need is platform review as a final step.

___

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19578#-:-NXo3hAD6y1eyqvEdVBr:bnfp4nl)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19578)* status: 1 unresolved discussion

**Pull request merged**
