### PR TITLE
Proposed PR train for deprecation and replacement of SignalLogger

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to #10228.

This branch is for reference (and possibly will get updated) as the actual PR train rolls through review.

Rather than try to preserve the class names SignalLogger and SignalLog, instead rewrite the functionality under new names VectorLogSink and VectorLog. This strategy avoids assorted awkwardness and complexity of maintaining two workflows in one set of modules. It also avoids paying two deprecation periods to get rid of both the original problematic API and the shims necessary to support an in-place transition.

While this does involve more than a bit of copy-paste, the new code can be clear and direct, and it will get some tests added that were missed before.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
FYI @sherm1 here's a branch pursuing the new-names-and-single-deprecation strategy. Doesn't need a detailed read now, but perhaps a sanity check to support closing the older PR. there are probably still warts here and maybe missing tests, but it should be pretty close to final form.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482#-:-MfZGj8U4DJyjxJhlNlA:b-24wifj)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by rpoyner-tri — COMMENTED** [review]
r2 fixes deprecation patch w.r.t. clang.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482#-:-MfZRoDaCzMpvLN5wkfw:b-vwi2do)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by rpoyner-tri — COMMENTED** [review]
r3 adopts the updated-for-review VectorLog and tests.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482#-:-MfZcaoR7zapEG7IJ_v_:bgnokj9)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sherm1 — COMMENTED** [review]
My 2 cents: looking at the examples here, they got longer and have some additional boilerplate required to extract the Log. That seems less user-friendly than the previous interface. I would suggest making the VectorLog an internal helper class and running the whole user interface through the VectorLogSink object so the user doesn't need to deal with two closely-related abstractions.

> Reviewed 1 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482#-:-MfeMaEdEodmgISb6j7h:bwbcgzj)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[examples/acrobot/run_lqr_w_estimator.cc, line 136 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15482#-MfeLWB4-TWeARBgFwP_:-MfeLWB4-TWeARBgFwPa:brvhqr8) ([raw file](https://github.com/robotlocomotion/drake/blob/3383ef34d4601a86f2d7b0193a7f3c75a286974f/examples/acrobot/run_lqr_w_estimator.cc#L136)):*
> ```cpp
>   // Plot the results (launch call_python_client to see the plots).
>   const auto& x_log = x_logger->FindLog(simulator.get_context());
>   const auto& xhat_log = xhat_logger->FindLog(simulator.get_context());
> ```

This extra boilerplate seems like a step back in usability -- the user now has to think about both a logger and log. Consider making the log an internal class and having the whole user interface run through the logger.

**Comment by jwnimmer-tri** [comment]
Counter-proposal:

- The existing SignalLogger is a _simple_ and _perfect_ abstraction for some use cases.
- We should not deprecate it.
- We should continue to use it in simple programs that only ever use one context.
- We should _also_ offer a primitive system that stores the log in the Context (i.e., the new VectorLogger) for users who need a multi-context logger (e.g., for multi-hypothesis or multi-threaded uses, or at least in cases where thread safety is in doubt).
- Perhaps SignalLogger and VectorLogger should both be backed by the new, more performant VectorLog storage.
- Perhaps we should rename the classes to best reflect their distinction.
- The two classes should obviously cross-reference each other in their docs and explain their distinction.

Capturing trace data from a Simulator is a very common use case.  When using a Simulator, there is only ever one Context being clocked in one thread -- the simulator owns the context.  We should be sure to preserve the simplicity of that use case, while still offering a more complicated abstraction when needed.  The damage we see to these examples comes from ignoring that common-case invariant.

Systems can have mutable member fields.  It's okay.  We just need to be clear in their documentation.

**Comment by sherm1** [comment]
I don't think it's worth keeping SignalLogger around. Even in the Simulator case you mentioned there is always a Context available so it is little trouble to log there. I would advocate hiding the VectorLog class in normal use so that the new interface looks as close as possible to the old one, which I agree was nice. I don't relish the thought of having to explain the limitations of SignalLogger and the dangerous example it sets with its mutable members, provide advice as to when to use one or the other, etc. The cost outweighs the reward, IMO.

Also at some point we'll likely want a logger that can deal with abstract output ports. It would be nice just to have a single class for that too -- I wouldn't like to see us have to write an AbstractSignalLogger and an AbstractSinkLogger to maintain parallel with the dual-class Vector loggers.

**Comment by jwnimmer-tri** [comment]
You should probably review Rico's proposed patch to Anzu before you conclude what's is or isn't ergonomic about this new API.  The toy programs here in Drake don't do justice to the use of the logger in more complicated diagrams, or when repeating and scoring simulations as per reinforcement learning.

**Comment by sherm1** [comment]
> You should probably review Rico's proposed patch to Anzu ...

That sounds like a good idea! @rpoyner-tri can you point me to that? I was unable to find a PR or issue in Anzu that matches Jeremy's description.

**Review by rpoyner-tri — COMMENTED** [review]
anzu 7361 contains the (outdated) porting patch. I'll work on updating it to keep pace with this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482#-:-MfiEhafAvlyglLzQdBm:b-lw3uxw)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[examples/acrobot/run_lqr_w_estimator.cc, line 136 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15482#-MfeLWB4-TWeARBgFwP_:-MfiUbmhE3U5KwsG1Tfw:bhp0xue) ([raw file](https://github.com/robotlocomotion/drake/blob/3383ef34d4601a86f2d7b0193a7f3c75a286974f/examples/acrobot/run_lqr_w_estimator.cc#L136)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This extra boilerplate seems like a step back in usability -- the user now has to think about both a logger and log. Consider making the log an internal class and having the whole user interface run through the logger.
</blockquote></details>

That presumes that the FindLog/GetLog steps are of completely negligible cost,  that the client wants to *always* at every call site present a context to get log access, and that we want to have a proliferation of methods to support the find/get lookup methods. Do we really want to support the cartesian product of lookup-method X log-method directly on VLS?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[examples/acrobot/run_lqr_w_estimator.cc, line 136 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15482#-MfeLWB4-TWeARBgFwP_:-Mfif5_DCYp5w2ml8Akx:beffmxv) ([raw file](https://github.com/robotlocomotion/drake/blob/3383ef34d4601a86f2d7b0193a7f3c75a286974f/examples/acrobot/run_lqr_w_estimator.cc#L136)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

That presumes that the FindLog/GetLog steps are of completely negligible cost,  that the client wants to *always* at every call site present a context to get log access, and that we want to have a proliferation of methods to support the find/get lookup methods. Do we really want to support the cartesian product of lookup-method X log-method directly on VLS?
</blockquote></details>

Those are good questions, but the answers aren't obvious to me -- best resolved with real use cases I think.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[examples/acrobot/run_lqr_w_estimator.cc, line 136 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15482#-MfeLWB4-TWeARBgFwP_:-Mfj26yOB9xQvKvvzkws:byoegt4) ([raw file](https://github.com/robotlocomotion/drake/blob/3383ef34d4601a86f2d7b0193a7f3c75a286974f/examples/acrobot/run_lqr_w_estimator.cc#L136)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Those are good questions, but the answers aren't obvious to me -- best resolved with real use cases I think.
</blockquote></details>

Updates to the anzu patch are in progress; perhaps they will help answer the question. Also, let's recall that *not* thing about the logger and the log is what got us here.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[examples/acrobot/run_lqr_w_estimator.cc, line 136 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15482#-MfeLWB4-TWeARBgFwP_:-Mfj2qmu4fl8wyh17DGq:bqwjcp9) ([raw file](https://github.com/robotlocomotion/drake/blob/3383ef34d4601a86f2d7b0193a7f3c75a286974f/examples/acrobot/run_lqr_w_estimator.cc#L136)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Updates to the anzu patch are in progress; perhaps they will help answer the question. Also, let's recall that *not* thing about the logger and the log is what got us here.
</blockquote></details>

s/thing/thinking/

**Review by rpoyner-tri — COMMENTED** [review]
r6 is work-in-progress on assimilated publish schedule API changes; python bindings need work.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482#-:-MfoYhEl2uSTB0fXeSOM:bk07ubu)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
r7 is updated to reflect the TriggerTypeSet spelling of the trigger/period API in VectorLogSink. No attempt was yet made to python-bind TriggerTypeSet.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15482#-:-MgBIFdq0n8L-XaEmquq:bv6z7oa)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Comment by rpoyner-tri** [comment]
The train is just about complete; closing this demonstration PR as no longer necessary.

**Pull request closed without merging**
