### PR TITLE
Updates MBP::AddJointActuator() documentation

### PR DESCRIPTION
**Pull request by rcory**
to alert users of unused effort limit argument.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14736)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14736#-:-MUuQyL27QEkB1Nj-QRD:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Thanks @rcory. Two nits. :lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14736#-:-MUxQlsU9USqfJp7m502:b-s9ui9h)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rcory)

___
*[multibody/plant/multibody_plant.h, line 1072 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14736#-MUxQSfF7f0qjlRdQotr:-MUxQSfF7f0qjlRdQots:b-njoiz7) ([raw file](https://github.com/robotlocomotion/drake/blob/e6081cd8f6ba735e9d8d1ebe9ac4897e3761b4d8/multibody/plant/multibody_plant.h#L1072)):*
> ```objc
>   ///   N⋅m (torque) for revolute joints while it will have units of N (force)
>   ///   for prismatic joints.
>   ///   @note This effort limit is not used in any MultibodyPlant calculations.
> ```

nit, indentation.
___
*[multibody/plant/multibody_plant.h, line 1073 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14736#-MUxPfro8JysV8eoZrLc:-MUxPfrpCeULKeGWDcqM:b-yit13y) ([raw file](https://github.com/robotlocomotion/drake/blob/e6081cd8f6ba735e9d8d1ebe9ac4897e3761b4d8/multibody/plant/multibody_plant.h#L1073)):*
> ```objc
>   ///   for prismatic joints.
>   ///   @note This effort limit is not used in any MultibodyPlant calculations.
>   ///   Its intended purpose is to communicate effort limits to the user.
> ```

nit. Well, it is the user here providing this number. 
Maybe say: 
"This effort limit is not used in any MultibodyPlant calculations. That is, MultibodyPlant will not, for instance, saturate external inputs based on these values.
Users can provide an effort limit value here for bookkeeping purposes so that other components in an application layer can access it (typically a planner and/or controller)"

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14736)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rcory)

___
*[multibody/plant/multibody_plant.h, line 1077 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14736#-MUy1w8l1hvUkXK3c9J9:-MUy1w8l1hvUkXK3c9JA:bvec7hp) ([raw file](https://github.com/robotlocomotion/drake/blob/75072efd3232726e699fd235d969b205d13b1ce9/multibody/plant/multibody_plant.h#L1077)):*
> ```objc
>   /// intends to saturate the force/torque that is applied to the MultibodyPlant
>   /// via this actuator, the user-level code (e.g., a controller) should query
>   /// this effort limit and impose the saturation there.
> ```

nice!, I like your version much better

**Review by rcory — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14736#-:-MUy5GaF9mJ-JiOvs-IS:b-ruv0ff)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14736#-:-MUy6Ma02Eu8wHROI3fl:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri

**Pull request merged**
