### PR TITLE
Temporarily strike testonly from drake_path.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4315)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4315#-:-KXqoxx1_bUEVj35xUDs:bnfp4nl)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental/5/ (drake-jenkins-bot doesn't like this build)

**Comment by david-german-tri** [comment]
Success!  Proceeding with merge.

**Pull request merged**
