### PR TITLE
In QP tutorial, mention the convexity check on the quadratic cost

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077#-:-MaUPLC87dB2qnI4Wfhh:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[tutorials/quadratic_program.ipynb, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15077#-MaZlP575jxGEuIJahX1:-MaZlP575jxGEuIJahX2:b-3rt2bj) ([raw file](https://github.com/robotlocomotion/drake/blob/2849dd8a7fa0ad0d9c0ea7c570773db5ac87df55/tutorials/quadratic_program.ipynb#L64)):*
> ```
>    "metadata": {},
>    "source": [
>     "We can call `AddQuadraticCost(expression, is_convex)` to add the quadratic cost, where `expression` is a symbolic expression representing a quadratic cost. Note that Drake will check if the added quadratic cost is convex or not, if you leave `is_convex` flag unspecified. If you already know the convexity of your cost, to speed up the computation, you should set `is_convex` flag."
> ```

My initial reaction is that this is too much detail to have so early in the tutorial.

Most users, and certainly all new users, should not use this flag.  By describing it so prominently here, we're going to encourage new users to think about this dangerous flag.

What do you think about keeping the "## Convexity of the cost" section as-is below, but reverting these two changes to the front matter of the tutorial (i.e., here and on L79-80)?
___
*[tutorials/quadratic_program.ipynb, line 213 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15077#-MaZmawWAbUQ-jzOFPna:-MaZmawWAbUQ-jzOFPnb:b-1d2x7z) ([raw file](https://github.com/robotlocomotion/drake/blob/2849dd8a7fa0ad0d9c0ea7c570773db5ac87df55/tutorials/quadratic_program.ipynb#L213)):*
> ```
>     "Drake checks the convexity of every added quadratic cost, by checking whether the Hessian of each quadratic cost is positive semidefinite or not. Currently the user could solve a QP with a convex solver (Gurobi/Mosek/OSQP/CLP/SCS etc) only if <em> every </em> quadratic cost is convex.\n",
>     "\n",
>     "It takes some computation to check if a quadratic cost is convex. To improve the computation speed, if you know the convexity of your quadratic cost, you can set `is_convex` flag in `AddQuadraticCost` function; Drake won't compute whether the cost is convex or not when `is_convex` flag is set. In the following example we show how to set this `is_convex` flag."
> ```

nit I wonder if somewhere near "to improve the computation speed", we want to give some guidance about when this micro-optimization is necessary.  Something like if you're solving within an inner control loop?
___
*[tutorials/quadratic_program.ipynb, line 224 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15077#-MaZkMwx-TuUW_nU7T0n:-MaZkMwy8ksgrZ30zOQd:bog4w8h) ([raw file](https://github.com/robotlocomotion/drake/blob/2849dd8a7fa0ad0d9c0ea7c570773db5ac87df55/tutorials/quadratic_program.ipynb#L224)):*
> ```
>     "# Call AddQuadraticCost with is_convex flag unspecified. Drake will check the convexity\n",
>     "# of this cost.\n",
>     "cost6 = prog.AddQuadraticCost(x[0]**2 + 3 * x[1]**2 + x[0] * x[1] + 2 * x[0])\n",
> ```

nit We already have "cost6" from an above cell.  Did you want to start numbering with "cost7" here, perhaps?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[tutorials/quadratic_program.ipynb, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15077#-MaZlP575jxGEuIJahX1:-Ma_ka5eB5f-snAmNDx2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2849dd8a7fa0ad0d9c0ea7c570773db5ac87df55/tutorials/quadratic_program.ipynb#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My initial reaction is that this is too much detail to have so early in the tutorial.

Most users, and certainly all new users, should not use this flag.  By describing it so prominently here, we're going to encourage new users to think about this dangerous flag.

What do you think about keeping the "## Convexity of the cost" section as-is below, but reverting these two changes to the front matter of the tutorial (i.e., here and on L79-80)?
</blockquote></details>

Done.
___
*[tutorials/quadratic_program.ipynb, line 213 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15077#-MaZmawWAbUQ-jzOFPna:-Ma_lJY2D1TcVDnX_gxt:b-od5wcs) ([raw file](https://github.com/robotlocomotion/drake/blob/2849dd8a7fa0ad0d9c0ea7c570773db5ac87df55/tutorials/quadratic_program.ipynb#L213)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I wonder if somewhere near "to improve the computation speed", we want to give some guidance about when this micro-optimization is necessary.  Something like if you're solving within an inner control loop?
</blockquote></details>

Done, I changed the text.
___
*[tutorials/quadratic_program.ipynb, line 224 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15077#-MaZkMwx-TuUW_nU7T0n:-Ma_lfE35f_pVutOMgsU:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/2849dd8a7fa0ad0d9c0ea7c570773db5ac87df55/tutorials/quadratic_program.ipynb#L224)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We already have "cost6" from an above cell.  Did you want to start numbering with "cost7" here, perhaps?
</blockquote></details>

Done, good call.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077#-:-Ma_o-aM5SVFRXjKNFPR:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[tutorials/quadratic_program.ipynb, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15077#-MaZlP575jxGEuIJahX1:-Ma_ndle1g-boYpVofVR:b-89ef7h) ([raw file](https://github.com/robotlocomotion/drake/blob/2849dd8a7fa0ad0d9c0ea7c570773db5ac87df55/tutorials/quadratic_program.ipynb#L64)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The `, is_convex` change that still remains on L64 as of r2 still seems like it would be confusing / misleading, especially without explanation and that we're omitting it most of the example to follow?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[tutorials/quadratic_program.ipynb, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15077#-MaZlP575jxGEuIJahX1:-Ma_oiaRCMbc81wwN1zC:b-a93ail) ([raw file](https://github.com/robotlocomotion/drake/blob/2849dd8a7fa0ad0d9c0ea7c570773db5ac87df55/tutorials/quadratic_program.ipynb#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `, is_convex` change that still remains on L64 as of r2 still seems like it would be confusing / misleading, especially without explanation and that we're omitting it most of the example to follow?
</blockquote></details>

Oops, I missed that change. Done.

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077#-:-Ma_oodh2PhvgFzJEdn0:buer3go)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
+@soonho-tri for platform review per schedule (tomorrow), please.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077#-:-Ma_ovWJ9Lnxj5YuqseO:b-583msa)* status: LGTM missing from assignees sherm1(platform),soonho-tri(platform) (waiting on @sherm1 and @soonho-tri)

**Comment by jwnimmer-tri** [comment]
Oops, wires crossed.  We'll see if @sherm1 gets to it.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few nits.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077#-:-Maa9WcO5U7Hw2KSQPlS:bvqyt9b)* status: 3 unresolved discussions (waiting on @hongkai-dai)

___
*[tutorials/quadratic_program.ipynb, line 209 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15077#-Maa8ACO0HtA5StSZdoM:-Maa8ACO0HtA5StSZdoN:b-ql3lie) ([raw file](https://github.com/robotlocomotion/drake/blob/52c218c0a6b2f2608f01e2f784b5d0cd6568b4b9/tutorials/quadratic_program.ipynb#L209)):*
> ```
>    "source": [
>     "## Convexity of the cost\n",
>     "Drake checks the convexity of every added quadratic cost, by checking whether the Hessian of each quadratic cost is positive semidefinite or not. Currently the user could solve a QP with a convex solver (Gurobi/Mosek/OSQP/CLP/SCS etc) only if <em> every </em> quadratic cost is convex.\n",
> ```

nit: could solve -> can solve
___
*[tutorials/quadratic_program.ipynb, line 211 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15077#-Maa8_mJDXYsalMDicjK:-Maa8_mJDXYsalMDicjL:b-44qvh7) ([raw file](https://github.com/robotlocomotion/drake/blob/52c218c0a6b2f2608f01e2f784b5d0cd6568b4b9/tutorials/quadratic_program.ipynb#L211)):*
> ```
>     "Drake checks the convexity of every added quadratic cost, by checking whether the Hessian of each quadratic cost is positive semidefinite or not. Currently the user could solve a QP with a convex solver (Gurobi/Mosek/OSQP/CLP/SCS etc) only if <em> every </em> quadratic cost is convex.\n",
>     "\n",
>     "It takes some computation to check if a quadratic cost is convex. If your application requires solving the QP as fast as possible (for example, solving a QP within the robot control loop), then it makes sense to bypass this convexity check. To do so, if you know the convexity of your quadratic cost, you can set `is_convex` flag in `AddQuadraticCost` function; Drake won't compute whether the cost is convex or not when `is_convex` flag is set. In the following example we show how to set this `is_convex` flag."
> ```

nit: 
"you can set is_convex flag in" -> "you can set _the_ is_convex flag in _the_"
"when is_convex flag" -> "when the is_convex flag"
___
*[tutorials/quadratic_program.ipynb, line 220 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15077#-Maa99Yb9xWmbYStGFSg:-Maa99Yb9xWmbYStGFSh:beuo89k) ([raw file](https://github.com/robotlocomotion/drake/blob/52c218c0a6b2f2608f01e2f784b5d0cd6568b4b9/tutorials/quadratic_program.ipynb#L220)):*
> ```
>    "outputs": [],
>    "source": [
>     "# Call AddQuadraticCost with is_convex flag unspecified. Drake will check the convexity\n",
> ```

nit: "with is_convex flag" -> "with _the_ is_convex flag"

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15077)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
