### PR TITLE
[mkdoc] Report a more specific error when libstdc++ is broken

### LINKED ISSUE #15652: Better diagnostics for broken libclang
Commit bfe196, latest install_prereqs.sh has been run, this is on Ubuntu 20:

```
└─ $ ▶ bazel build -c dbg manipulation/util:geometry_inspector
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //manipulation/util:geometry_inspector (173 packages loaded, 8271 targets configured).
INFO: Found 1 target...
ERROR: /home/drum/drake-new/bindings/pydrake/BUILD.bazel:57:37: Action bindings/pydrake/documentation_pybind.h failed: (Exit 1): mkdoc failed: error executing command bazel-out/host/bin/tools/workspace/pybind11/mkdoc -DDRAKE_COMMON_SYMBOLIC_DETAIL_HEADER -DEIGEN_MPL2_ONLY -DHAVE_CSTDDEF '-DFMT_HEADER_ONLY=1' '-DFMT_NO_FMT_STRING_ALIAS=1' -DSPDLOG_COMPILED_LIB ... (remaining 743 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/eigen/include/_usr_include_eigen3/Eigen/Core:82:12: fatal error: 'new' file not found
Traceback (most recent call last):
  File "/home/drum/.cache/bazel/_bazel_drum/2059ccae995efcc54d793ceb88203d5b/sandbox/linux-sandbox/1197/execroot/drake/bazel-out/host/bin/tools/workspace/pybind11/mkdoc.runfiles/drake/tools/workspace/pybind11/mkdoc.py", line 841, in <module>
    main()
  File "/home/drum/.cache/bazel/_bazel_drum/2059ccae995efcc54d793ceb88203d5b/sandbox/linux-sandbox/1197/execroot/drake/bazel-out/host/bin/tools/workspace/pybind11/mkdoc.runfiles/drake/tools/workspace/pybind11/mkdoc.py", line 801, in main
    raise RuntimeError(
RuntimeError: Parsing headers using the clang library failed with 0 error(s) and 1 fatal error(s)
----------------
Note: The failure of target //tools/workspace/pybind11:mkdoc (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
```

Looks like the error has something to do with Eigen, not python.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #15652.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15798)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I tested this locally by changing `<optional>` to `<foobar>` and trying `bazel build //bindings/pydrake:documentation_pybind.h`.

+@rpoyner-tri for both reviews, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15798#-:-Mk92H8NCLjB7GPp1ucH:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tools/workspace/pybind11/mkdoc.py, line 801 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15798#-Mk92B8qCfvmgQDKaVRL:-Mk92B8qCfvmgQDKaVRM:b7r124y) ([raw file](https://github.com/robotlocomotion/drake/blob/226fdfd00ef1f558821e9154970b08a2094b1479/tools/workspace/pybind11/mkdoc.py#L801)):*
> ```
> is an error is 
> ```
typo -- extra `is`

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @rpoyner-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15798)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15798)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
