### PR TITLE
Move RigidTransform code from .h file to .cc file.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19084)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
@sherm1 for both reviews?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-:-NRjBVvuATQvqPOCGNWr:b-y8hddf)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by sherm1 — COMMENTED** [review]
I'm not sure why you want to move tiny computational routines to where they can't be inlined. There are two here that definitely should stay in the header file, and the others are marginal (see comments below).

:lgtm: x 2 pending putting at least the two I noted back in the .h

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-:-NRjITzO55zmeqap8fJd:b-in4172)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @mitiguy)

___
*[`math/rigid_transform.h` line 200 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjGhoY3dja5Eh9wF0O:-NRjGhoY3dja5Eh9wF0P:b-qbb74u) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L200)):*
> ```objc
>     DRAKE_ASSERT_VOID(ThrowIfInvalidBottomRow(pose));
>     set_rotation(RotationMatrix<T>(pose.template block<3, 3>(0, 0)));
>     set_translation(pose.template block<3, 1>(0, 3));
> ```

minor: this is a very small routine -- just copying 12 numbers (the ASSERT is gone in Release builds and all the Eigen stuff is inline). With SIMD instructions this could be as few as 6 machine instructions; with AVX it could be 3.
I think it should remain inlineable -- to me it looks like something that could be in an inner loop somewhere and we don't have any good way to prove that it doesn't matter.
___
*[`math/rigid_transform.h` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjHZDM9ieNNIkrENdG:-NRjHZDM9ieNNIkrENdH:byz93is) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L360)):*
> ```objc
>     pose.template topRightCorner<3, 1>() = translation();
>     pose.row(3) = Vector4<T>(0, 0, 0, 1);
>     return pose;
> ```

BTW I could go either way with this one. It is still very small, and return value optimization means it isn't necessarily allocating new memory. Still this conversion seems unlikely to occur anywhere important.
___
*[`math/rigid_transform.h` line 373 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjHoS5DqiYeGGFLqPB:-NRjHoS5DqiYeGGFLqPC:b-7wok9) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L373)):*
> ```objc
>     pose.template topLeftCorner<3, 3>() = rotation().matrix();
>     pose.template topRightCorner<3, 1>() = translation();
>     return pose;
> ```

BTW same comment here. _Probably_ doesn't matter but this is definitely small enough to stay inlined.
___
*[`math/rigid_transform.h` line 385 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjHtnw9Q5Epciu0K3_:-NRjHtnw9Q5Epciu0K3a:b-vkniri) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L385)):*
> ```objc
>     pose.translation() = translation();
>     pose.makeAffine();
>     return pose;
> ```

BTW Very happy to see this one moved! No point optimizing misuse of Isometry.
___
*[`math/rigid_transform.h` line 452 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjI46E3NATGB1VzSk8:-NRjI46E3NATGB1VzSk9:baxnu09) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L452)):*
> ```objc
>     // @internal This method's name was chosen to mimic Eigen's inverse().
>     const RotationMatrix<T> R_BA = R_AB_.inverse();
>     return RigidTransform<T>(R_BA, R_BA * (-p_AoBo_A_));
> ```

minor: _definitely_ keep this one inlineable. That's a very small function and very frequently used.

**Comment by jwnimmer-tri** [comment]
*[`math/rigid_transform.h` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjHZDM9ieNNIkrENdG:-NRjNyUz8vv36_ULPnjY:b-b8voa3) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L360)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I could go either way with this one. It is still very small, and return value optimization means it isn't necessarily allocating new memory. Still this conversion seems unlikely to occur anywhere important.
</blockquote></details>

This is heavily used in motion planning / collision checking and **must not** go into cc.  (We often multiply transforms using this representation, instead of the `operator*`.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19084)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @mitiguy and @sherm1)

___
*[`math/rigid_transform.h` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjHZDM9ieNNIkrENdG:-NRjPfnC7oBvdt_1E2xg:b-8l7r6c) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L360)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is heavily used in motion planning / collision checking and **must not** go into cc.  (We often multiply transforms using this representation, instead of the `operator*`.)
</blockquote></details>

... well, I take that back in part.  Our inner loop uses of this have dwindled over time.

I still think PR is mad-hatter crazy to de-inline these functions that are just memcopies!  Copying is like one of the core things that should stay inlined, so the compiler can elide the copies when they chain with other things.

The only positive change in this PR is the `Isometry3` one.  All of the others are ill-motivated.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19084)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri and @mitiguy)

___
*[`math/rigid_transform.h` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjHZDM9ieNNIkrENdG:-NRjTp_wDrwd5ZUoqRXp:bsje6yr) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L360)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

... well, I take that back in part.  Our inner loop uses of this have dwindled over time.

I still think PR is mad-hatter crazy to de-inline these functions that are just memcopies!  Copying is like one of the core things that should stay inlined, so the compiler can elide the copies when they chain with other things.

The only positive change in this PR is the `Isometry3` one.  All of the others are ill-motivated.
</blockquote></details>

I agree -- I'd be happiest with just the Isometry function getting buried.

**Review by mitiguy — COMMENTED** [review]
Reverted most code.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-:-NRjZucc0az_nWXS5Pxq:b-om6qh0)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[`math/rigid_transform.h` line 200 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjGhoY3dja5Eh9wF0O:-NRjUAYZ4eyzrsyV9YlZ:bp3aow6) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L200)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this is a very small routine -- just copying 12 numbers (the ASSERT is gone in Release builds and all the Eigen stuff is inline). With SIMD instructions this could be as few as 6 machine instructions; with AVX it could be 3.
I think it should remain inlineable -- to me it looks like something that could be in an inner loop somewhere and we don't have any good way to prove that it doesn't matter.
</blockquote></details>

Reverted.
___
*[`math/rigid_transform.h` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjHZDM9ieNNIkrENdG:-NRjU84B2yDuNgSBsPZU:bp3aow6) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L360)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I agree -- I'd be happiest with just the Isometry function getting buried.
</blockquote></details>

Reverted.
___
*[`math/rigid_transform.h` line 373 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjHoS5DqiYeGGFLqPB:-NRjUDQJ-yNBzPbr7yXB:bp3aow6) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L373)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW same comment here. _Probably_ doesn't matter but this is definitely small enough to stay inlined.
</blockquote></details>

Reverted.
___
*[`math/rigid_transform.h` line 385 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjHtnw9Q5Epciu0K3_:-NRjUErF21xjjeEitm_s:bb70vmb) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L385)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Very happy to see this one moved! No point optimizing misuse of Isometry.
</blockquote></details>

OK. 
___
*[`math/rigid_transform.h` line 452 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjI46E3NATGB1VzSk8:-NRjUGb81G4QqC63fmsb:bn85buz) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L452)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: _definitely_ keep this one inlineable. That's a very small function and very frequently used.
</blockquote></details>

Reverted with perceived improvement.  Feel free to comment.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19084)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @sherm1)

___
*[`math/rigid_transform.h` line 452 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjI46E3NATGB1VzSk8:-NRja0N8AlyaDb--i3o3:b-po5le5) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L452)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Reverted with perceived improvement.  Feel free to comment.
</blockquote></details>

What kind of improvement is this?  I am not seeing it.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19084)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[`math/rigid_transform.h` line 452 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjI46E3NATGB1VzSk8:-NRk9gHgEj9m-t9e-Y0L:b-jbv6lh) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L452)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What kind of improvement is this?  I am not seeing it.
</blockquote></details>

@SeanCurtis-TRI  --  I think this often-used inverse() function was a piece of code optimization that we discussed. 

From what I remember, we anticipated that the new code used here copies one RotationMatrix R_BA immediately into the memory of the returned RigidTransform X_BA whereas on its human-readable surface, the older code creates one RotationMatrix named R_BA and then copies it into the returned RigidTransform X_BA (in other words two memory copies are done).  I can imagine compiler optimization may do something different.  Feel free to weigh in or not.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19084)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[`math/rigid_transform.h` line 452 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19084#-NRjI46E3NATGB1VzSk8:-NRkfL-w8c0vWPP3VJ_r:bqoqfuw) ([raw file](https://github.com/RobotLocomotion/drake/blob/4caa45959dc2ef362ff2ac8ce9e32b978c1f43e3/math/rigid_transform.h#L452)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

@SeanCurtis-TRI  --  I think this often-used inverse() function was a piece of code optimization that we discussed. 

From what I remember, we anticipated that the new code used here copies one RotationMatrix R_BA immediately into the memory of the returned RigidTransform X_BA whereas on its human-readable surface, the older code creates one RotationMatrix named R_BA and then copies it into the returned RigidTransform X_BA (in other words two memory copies are done).  I can imagine compiler optimization may do something different.  Feel free to weigh in or not.
</blockquote></details>

Ah.  Yes, it is plausibly saving a few MOV instructions compared to the original version.

Since we're speculating about performance improvements without so much as even attempting even a single benchmark, my speculation would be that it would show an approx 3% improvement in a micro-benchmark and 0% in a macro-benchmark.

I don't mind one way or the other whether this change happens.  I'll defer to Sherm.

**Pull request merged**
