### PR TITLE
autodiffxd atan(): Use abs2()

### LINKED ISSUE #14051: fishy-looking math in AutoDiffScalar atan()
Questions were raised in the context of #14045 about the details of the math implementing atan() for AutoDiffXd. I couldn't answer without a bit of history, and some way to evaluate the alternatives. This issue is to track that follow-up.

Comments:
https://github.com/RobotLocomotion/drake/pull/14045#pullrequestreview-487016357
and 
https://github.com/RobotLocomotion/drake/pull/14045#pullrequestreview-487052140

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes #14051.

This is mostly to answer complaints about inconsistencies with similar
functions.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) 
+@sherm1 for both reviews.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075#-:-MoEpJl02WiR4pizcZpE:b-cb3zk)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[common/autodiffxd.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16075#-MoF-fEwDssaft6oH2Kc:-MoF-fEwDssaft6oH2Kd:b-ctl4ae) ([raw file](https://github.com/robotlocomotion/drake/blob/ed980019843e285a4c1ad200ab92466f928900b2/common/autodiffxd.h#L461)):*
> ```objc
> DRAKE_EIGEN_AUTODIFFXD_DECLARE_GLOBAL_UNARY(
>     atan, using std::atan;
>     x.derivatives() *= Scalar(1) / (1 + numext::abs2(x.value()));
> ```

This seems wrong to me. According to all the references I could find, the derivative of atan(z) is 1/(1 + z²). With the proposed change, this
would be 1/(1 + |z|²). When z is real, those are the same.
But when z=a+bi is complex
|z|²=a²+b² while z²= a²−b² + 2abi. The former is the "absolute square" (product of z and conj(z)) and the latter is just the "square" (product of z with itself).

I believe all the other uses of abs2 here are also wrong. Since we don't support complex in Drake I suppose it doesn't matter but I wouldn't compound the problem by making this one wrong also!

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[common/autodiffxd.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16075#-MoF-fEwDssaft6oH2Kc:-MoF3L-H-ldKvugobD4V:b-fjxh7j) ([raw file](https://github.com/robotlocomotion/drake/blob/ed980019843e285a4c1ad200ab92466f928900b2/common/autodiffxd.h#L461)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This seems wrong to me. According to all the references I could find, the derivative of atan(z) is 1/(1 + z²). With the proposed change, this
would be 1/(1 + |z|²). When z is real, those are the same.
But when z=a+bi is complex
|z|²=a²+b² while z²= a²−b² + 2abi. The former is the "absolute square" (product of z and conj(z)) and the latter is just the "square" (product of z with itself).

I believe all the other uses of abs2 here are also wrong. Since we don't support complex in Drake I suppose it doesn't matter but I wouldn't compound the problem by making this one wrong also!
</blockquote></details>

Let me anticipate the follow-up question we will get from the peanut gallery.

"You have expression * expression here, isn't that going to evaluate expression twice, at some cost?"

Maybe yes, maybe no, depending on optimizer details. I doubt we care enough to write the code to measure alternatives.

**Comment by jwnimmer-tri** [comment]
___
*[common/autodiffxd.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16075#-MoF-fEwDssaft6oH2Kc:-MoF47Vb1DZEERnlJ4HM:b593rma) ([raw file](https://github.com/robotlocomotion/drake/blob/ed980019843e285a4c1ad200ab92466f928900b2/common/autodiffxd.h#L461)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Let me anticipate the follow-up question we will get from the peanut gallery.

"You have expression * expression here, isn't that going to evaluate expression twice, at some cost?"

Maybe yes, maybe no, depending on optimizer details. I doubt we care enough to write the code to measure alternatives.
</blockquote></details>

As I said in the original PR -- `Scalar` is always `double` here.  Imaginary doesn't matter.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[common/autodiffxd.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16075#-MoF-fEwDssaft6oH2Kc:-MoF4qZZEhH_MwOhIBbj:b-v7cw2s) ([raw file](https://github.com/robotlocomotion/drake/blob/ed980019843e285a4c1ad200ab92466f928900b2/common/autodiffxd.h#L461)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As I said in the original PR -- `Scalar` is always `double` here.  Imaginary doesn't matter.
</blockquote></details>

@rpoyner-tri: x.value() is just an accessor, not a computation. So I don't think there is an efficiency argument. 

@jwnimmer-tri: writing the math correctly in the source code does matter. If we wanted to use the wrong expression to take computational advantage of our knowledge of the particular scalar type that would be reasonable if surrounded by explanatory comments to avoid future cargo culting or even just looking like we don't know what we're doing. However, in this case there is no computational advantage and no reason to use anything other than `x*x` here.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[common/autodiffxd.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16075#-MoF-fEwDssaft6oH2Kc:-MoF6gFQ9bwcbEW8XK_f:b-nal27o) ([raw file](https://github.com/robotlocomotion/drake/blob/ed980019843e285a4c1ad200ab92466f928900b2/common/autodiffxd.h#L461)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

@rpoyner-tri: x.value() is just an accessor, not a computation. So I don't think there is an efficiency argument. 

@jwnimmer-tri: writing the math correctly in the source code does matter. If we wanted to use the wrong expression to take computational advantage of our knowledge of the particular scalar type that would be reasonable if surrounded by explanatory comments to avoid future cargo culting or even just looking like we don't know what we're doing. However, in this case there is no computational advantage and no reason to use anything other than `x*x` here.
</blockquote></details>

Whatever.  This entire issue is a waste of everyone's time.  And so, I should just take my own advice and unsubscribe from this entire review and issue -- it's certainly not worth _my_ time.  I'm marking myself resolved here.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[common/autodiffxd.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16075#-MoF-fEwDssaft6oH2Kc:-MoF8pqo6nm0cqz_1qYl:b-v8kge7) ([raw file](https://github.com/robotlocomotion/drake/blob/ed980019843e285a4c1ad200ab92466f928900b2/common/autodiffxd.h#L461)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Whatever.  This entire issue is a waste of everyone's time.  And so, I should just take my own advice and unsubscribe from this entire review and issue -- it's certainly not worth _my_ time.  I'm marking myself resolved here.
</blockquote></details>

I would also be happy with just closing the original issue and taking no action. I'm only objecting to making it worse.

If you do want to make a change here I think the best one would be to remove the TODO here and move it to the fishy uses of abs2() elsewhere. To actually "fix" the code, we would have to check carefully all the derivatives to make sure there isn't one that actually needs abs2(). But nothing would actually change since we're specialized on `double` so this might not be the best use of time!

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[common/autodiffxd.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16075#-MoF-fEwDssaft6oH2Kc:-MoFCfpUAMDUz5ZceFtg:b-msdvd4) ([raw file](https://github.com/robotlocomotion/drake/blob/ed980019843e285a4c1ad200ab92466f928900b2/common/autodiffxd.h#L461)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I would also be happy with just closing the original issue and taking no action. I'm only objecting to making it worse.

If you do want to make a change here I think the best one would be to remove the TODO here and move it to the fishy uses of abs2() elsewhere. To actually "fix" the code, we would have to check carefully all the derivatives to make sure there isn't one that actually needs abs2(). But nothing would actually change since we're specialized on `double` so this might not be the best use of time!
</blockquote></details>

cosh(x.value()) is not just an accessor. Also, I don't think there is an efficiency argument, but changes like this attract bikeshedding like no other.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

___
*[common/autodiffxd.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16075#-MoF-fEwDssaft6oH2Kc:-MoFENhV15Ej_mTL_yJv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ed980019843e285a4c1ad200ab92466f928900b2/common/autodiffxd.h#L461)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

cosh(x.value()) is not just an accessor. Also, I don't think there is an efficiency argument, but changes like this attract bikeshedding like no other.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
That should silence the haters! Thanks.
:lgtm: x 2

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16075#-:-MoFYxVI30202RqS1EhA:b-4ujtsk)* status: missing label for release notes (waiting on @rpoyner-tri)

**Pull request merged**
