### PR TITLE
Strip installed executables and libraries on macOS

### PR DESCRIPTION
**Pull request by jamiesnape**
This is something that CMake does during its install that we are missing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8134)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
Since we have the `ld -s` on Mac, I do not want to delay this while I fix the problems with the Linux install that are causing `strip` to choke there, so making macOS only for now.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

\CC @soonho-tri

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8134#-:-L5zrH1REHkbVIc1vori:bgk1jgr)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8134#-:-L5zugGh9uwk3ifzK4jI:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
I think we can count as platform also.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8134#-:-L5zw2Zo0qolpFxL_K9e:b-80u669)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
@jamiesnape Could you add a note to #8253 with the problems you saw on Ubuntu, if you still remember or have notes?  Or if you have any partway-done patch to post that would help also.

**Pull request merged**
