### PR TITLE
common: Add internal pool-ladder allocator

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #14215

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333)* status: needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MM8Iyuc4RJrsEMLtL7F:-MM8Iyuc4RJrsEMLtL7G:b663vdl) (no related file):*
This is part 1 of a PR train toward faster autodiff. The full PR sequence (approximately) can be seen in not-for-formal-review PR #14318.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[common/pool_ladder_allocator.h, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MM8MoxICKGz--oQIIxH:-MM8MoxICKGz--oQIIxI:b-7ilvee) ([raw file](https://github.com/robotlocomotion/drake/blob/223e5e8a0a94ea00095d76f75232123ac96a0120/common/pool_ladder_allocator.h#L5)):*
> ```objc
> // @file
> // Allocate arrays of doubles from a sequence of memory pools, graduated in
> // size. This allocator is not thread-safe; ; the design leaves synchronization
> ```

typos
___
*[common/pool_ladder_allocator.h, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MM8L0Ei-i3r_dYwsf56:-MM8L0Ei-i3r_dYwsf57:b8jm2b7) ([raw file](https://github.com/robotlocomotion/drake/blob/223e5e8a0a94ea00095d76f75232123ac96a0120/common/pool_ladder_allocator.h#L45)):*
> ```objc
> 
>   // Put an object in the pool.
>   // @precondition: p != nullptr
> ```

There is another precondition: either the incoming block came from Get(), or is at least big enough to store kSize doubles.

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333#-:-MM8NfQvDhsIwFSi2t1T:btfsfbp)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[common/pool_ladder_allocator.h, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MM8OPzR-dwo2GY7y9At:-MM8OPzR-dwo2GY7y9Au:b3wql78) ([raw file](https://github.com/robotlocomotion/drake/blob/223e5e8a0a94ea00095d76f75232123ac96a0120/common/pool_ladder_allocator.h#L125)):*
> ```objc
>       default: {
>         // If you really need large objects, consider extending this class.
>         DRAKE_DEMAND(power > 0 && power <= 15);
> ```

use kMaxPower constant here.
___
*[common/pool_ladder_allocator.h, line 161 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MM8OTrrDXtk1YjOJkYv:-MM8OTrrDXtk1YjOJkYw:b3wql78) ([raw file](https://github.com/robotlocomotion/drake/blob/223e5e8a0a94ea00095d76f75232123ac96a0120/common/pool_ladder_allocator.h#L161)):*
> ```objc
>         // The input block was not made by Get(), or other code violated array
>         // bounds by overwriting p[-1].
>         DRAKE_DEMAND(power > 0 && power <= 15);
> ```

use kMaxPower constant here.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[common/pool_ladder_allocator.h, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MMDEI6xD0szuQ0roCoo:-MMDEI6yAjEJqb-foo4J:b-irvixy) ([raw file](https://github.com/robotlocomotion/drake/blob/17400eda343fb6e07ff13bca0e1aaf86f88e8f72/common/pool_ladder_allocator.h#L76)):*
> ```objc
> inline int ceil_log2(unsigned int x) {
>   DRAKE_ASSERT(x > 1);
>   return std::numeric_limits<unsigned int>::digits - __builtin_clz(x - 1);
> ```

Use of builtins is proscribed by GSG.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[common/pool_ladder_allocator.h, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MMDEI6xD0szuQ0roCoo:-MMDN7MNBp_tVRwhzh8x:b-mr0o0o) ([raw file](https://github.com/robotlocomotion/drake/blob/17400eda343fb6e07ff13bca0e1aaf86f88e8f72/common/pool_ladder_allocator.h#L76)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Use of builtins is proscribed by GSG.
</blockquote></details>

From GSG: "You may use portability wrappers that are implemented using nonstandard extensions, so long as those wrappers are provided by a designated project-wide portability header."

We would just need to implement a slow clz for use with compilers that don't support __builtin_clz. However gcc and clang both support this already and translate it into the appropriate machine instruction. So IMO it would be fine for now to have the "portability wrapper" test for gcc or clang and just `#error` for other compilers until we have one to deal with.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[common/pool_ladder_allocator.h, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MMDEI6xD0szuQ0roCoo:-MMGdpjH4damNgg2EdgV:b9ijfj) ([raw file](https://github.com/robotlocomotion/drake/blob/17400eda343fb6e07ff13bca0e1aaf86f88e8f72/common/pool_ladder_allocator.h#L76)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

From GSG: "You may use portability wrappers that are implemented using nonstandard extensions, so long as those wrappers are provided by a designated project-wide portability header."

We would just need to implement a slow clz for use with compilers that don't support __builtin_clz. However gcc and clang both support this already and translate it into the appropriate machine instruction. So IMO it would be fine for now to have the "portability wrapper" test for gcc or clang and just `#error` for other compilers until we have one to deal with.
</blockquote></details>

What's your position on the introduction of a project-wide portability header?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MMGmOsrEgoO54w98vOO:-MMGmOsrEgoO54w98vOP:b-ej8c3v) (no related file):*
Pertinent discussion also here: https://github.com/RobotLocomotion/drake/issues/14215#issuecomment-727670081

---

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14333)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[common/pool_ladder_allocator.h, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14333#-MMDEI6xD0szuQ0roCoo:-MMGsLY37-bKpxgmD0WW:b-uei44w) ([raw file](https://github.com/robotlocomotion/drake/blob/17400eda343fb6e07ff13bca0e1aaf86f88e8f72/common/pool_ladder_allocator.h#L76)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

What's your position on the introduction of a project-wide portability header?
</blockquote></details>

I don't think we actually need one literally -- a drake/common header for the next-power-of-2 function would serve the same purpose in a more-targeted manner.

**Comment by rpoyner-tri** [comment]
Closing this, based on discussion of costs and benefits. Will keep the dev-branch for a bit to see if I can improve things any further.

**Pull request closed without merging**
