### PR TITLE
[geometry] Implements `CalcVolume` for basic `Shape`s

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@damrongguoy for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354#-:-Mt9FIbN-HhhExPKPzZz:b-7aaes1)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16354#-Mt9gNgu-x4yhGwKnfv4:-Mt9gNgu-x4yhGwKnfv5:bswuf8p) (no related file):*
Just a thought: `geometry::Shape` is just a blueprint specification, metadata for a geometry. It may not make sense to ever implement `CalcVolume()` for any non-primitives since they only hang onto a path for the specified geometry and would have to reify that geometry (into a `VolumeMesh`) in order to calculate the volume. `VolumeMesh::CalcVolume()` already does that calculation.

And in thinking about the use case: "produce default inertial values for geometries specified in an xml file without having their inertias declared explicitly" we might want to think about whether you want the *ideal* inertia of the `Shape`, or the more accurate inertia of the concrete mesh. `resolution_hint` has a big impact on how close the actualized mesh is to the ideal shape, and may have a non-trivial impact on the difference of the inertial values. Thoughts?

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16354#-Mt9gNgu-x4yhGwKnfv4:-Mt9kQ_P-MCynBp8PNky:b-f79h6r) (no related file):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Just a thought: `geometry::Shape` is just a blueprint specification, metadata for a geometry. It may not make sense to ever implement `CalcVolume()` for any non-primitives since they only hang onto a path for the specified geometry and would have to reify that geometry (into a `VolumeMesh`) in order to calculate the volume. `VolumeMesh::CalcVolume()` already does that calculation.

And in thinking about the use case: "produce default inertial values for geometries specified in an xml file without having their inertias declared explicitly" we might want to think about whether you want the *ideal* inertia of the `Shape`, or the more accurate inertia of the concrete mesh. `resolution_hint` has a big impact on how close the actualized mesh is to the ideal shape, and may have a non-trivial impact on the difference of the inertial values. Thoughts?
</blockquote></details>

Joe is right -- the `Shape` is supposed to be _only_ a data-holder.  Its class hierarchy should not contain any operators.  If we want a Volume operation, then we should put that code into a concrete reifier subclass, not into the `Shape` itself.

Promoting to blocking.

---

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16354#-Mt9gNgu-x4yhGwKnfv4:-Mt9mRLrBgcBtm4YKRzF:b-6oso7e) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Joe is right -- the `Shape` is supposed to be _only_ a data-holder.  Its class hierarchy should not contain any operators.  If we want a Volume operation, then we should put that code into a concrete reifier subclass, not into the `Shape` itself.

Promoting to blocking.
</blockquote></details>

I have no problem with reifiers.  I'll only review that all the formulae in this PR are correct.  We'll want to refactor it into reifiers.

---
___
*[geometry/shape_specification.h, line 354 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16354#-Mt9eezp8XfjKLWB49oy:-Mt9eezp8XfjKLWB49oz:b-5ad8e8) ([raw file](https://github.com/robotlocomotion/drake/blob/72d6c43c2c4f43e56909cf8510fb40b485f8874f/geometry/shape_specification.h#L354)):*
> ```objc
> 
>  where `a` and `b` are the lengths of the principle semi-axes of the horizontal
>  section at `z=1`.
> ```

Optional.  This is not a part of this PR, so you could ignore or postpone.

```C++
section at `z=height`
```
not `z=1`
___
*[bindings/pydrake/geometry_py_common.cc, line 362 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16354#-Mt9k_k-DzmIhZBpYbkp:-Mt9k_k-DzmIhZBpYbkq:b-vcl41c) ([raw file](https://github.com/robotlocomotion/drake/blob/72d6c43c2c4f43e56909cf8510fb40b485f8874f/bindings/pydrake/geometry_py_common.cc#L362)):*
> ```cpp
>     py::class_<Shape> shape_cls(m, "Shape", doc.Shape.doc);
>     DefClone(&shape_cls);
>     shape_cls.def("CalcVolume", &Shape::CalcVolume, doc.Shape.CalcVolume.doc);
> ```

Question. Python is beyond my expertise. Does this one binding cover all shape types (Sphere, Cylinder, Box, Capsule, Ellipsoid, Halfspace, Mesh, Convex, MeshcatCone)?

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: in terms of correct volume formulae. However, we might want to discuss whether to do it through reifiers instead.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354#-:-Mt9nVxx1xoA_le2pg__:bsdl7th)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354#-:-MtCzcJnCiXCVqvr-fq6:bz1t39v)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16354#-Mt9gNgu-x4yhGwKnfv4:-MtCxtZh2mNknvE_6QyT:b-896fix) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I have no problem with reifiers.  I'll only review that all the formulae in this PR are correct.  We'll want to refactor it into reifiers.
</blockquote></details>

Done.

---
___
*[geometry/shape_specification.h, line 354 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16354#-Mt9eezp8XfjKLWB49oy:-MtCzEWp11B3agUd0hWO:b-u899uy) ([raw file](https://github.com/robotlocomotion/drake/blob/72d6c43c2c4f43e56909cf8510fb40b485f8874f/geometry/shape_specification.h#L354)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional.  This is not a part of this PR, so you could ignore or postpone.

```C++
section at `z=height`
```
not `z=1`

</blockquote></details>

Done.  You are right.  I also confirmed this change is consistent with the `ImplementGeometry` implementation in in `meshcat.cc`; do you agree?
___
*[bindings/pydrake/geometry_py_common.cc, line 362 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16354#-Mt9k_k-DzmIhZBpYbkp:-MtCzVeLDBE9ePPe6OL7:brg0f2d) ([raw file](https://github.com/robotlocomotion/drake/blob/72d6c43c2c4f43e56909cf8510fb40b485f8874f/bindings/pydrake/geometry_py_common.cc#L362)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Question. Python is beyond my expertise. Does this one binding cover all shape types (Sphere, Cylinder, Box, Capsule, Ellipsoid, Halfspace, Mesh, Convex, MeshcatCone)?
</blockquote></details>

Yes.  But it's moved to a workspace method now anyhow.

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: again.

It's a Reifier now.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354#-:-MtEWpOQCxgis3_8vRVZ:b-4iwtib)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[geometry/shape_specification.h, line 354 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16354#-Mt9eezp8XfjKLWB49oy:-MtEOlQX5F0Nm8sqfKP8:b-9755fa) ([raw file](https://github.com/robotlocomotion/drake/blob/72d6c43c2c4f43e56909cf8510fb40b485f8874f/geometry/shape_specification.h#L354)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  You are right.  I also confirmed this change is consistent with the `ImplementGeometry` implementation in in `meshcat.cc`; do you agree?
</blockquote></details>

Thank you.

**Review by sammy-tri — COMMENTED** [review]
+@xuchenhan-tri for shadow platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354#-:-MtEwbVw5-Uqc_X_y9Lj:bvy48z2)* status: LGTM missing from assignees sammy-tri(platform),xuchenhan-tri (waiting on @sammy-tri and @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354#-:-MtF04HyAYhGvSOPxk9o:bnfp4nl)* status: LGTM missing from assignee xuchenhan-tri (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16354#-:-MtFA6RJ40XaWf65-mGw:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),DamrongGuoy,xuchenhan-tri (waiting on @RussTedrake)

**Pull request merged**
