### PR TITLE
fastQP test

### PR DESCRIPTION
**Pull request by RussTedrake**
adds a QP test case where the active set changes in a gradual and predictable way, in preparation for the fast qp solver PR.  

This adds setter methods to QuadraticConstraint, which I believe is the best option here... but I wanted to discuss before bringing in the solver.

@ggould-tri , @sammy-tri -- PTAL?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3501)

### CODE REVIEW

**Comment by ggould-tri** [comment]
It seems to me like there are three reasonable approaches to making constraints mutable:

(1) Don't; treat constraints as const and rely on on add/remove.  PRO: Simple, correct.  Does not surprise users when strength reduction logic causes surprising return types.  CON: Makes warm-start nearly impossible.

(2) This PR's style: setters for all elements.  This would involve both your change here and also moving `Constraint::set_bounds` from protected to public.  Setters appropriate to particular constraint types could be added as needed.  PRO: Readable, easy.  CON: Might interact badly with other information deduced about a constraint (eg convexity) cached at the solver.

(3) Single setter of all elements analogous to `LinearEqualityConstraint::UpdateConstraint`.  PRO: Could be a single idiom shared by all constraint classes.  Single point of invalidation for any future warm-start logic.  CON:  Might be verbose in some use cases.

I think 2 (this approach) is reasonable but the PR that implements it should purge the instance of 3 and document the behaviour of MathematicalProgram under constraint mutation.

In particular I think this is the time to document that strength reduction such as the `LinearConstraint` logic in `AddPolynomialConstraint` belongs where it is at the MathematicalProgram level (with possibly strength-reducing operations returning `Constraint` rather than a more specific type).  This implies that constraints added via such methods are not usefully mutable, which I think is correct.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/constraint.h, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-KS1mGf-E2XO2uyO0OKK:-KS1mGf0JwzKu1eUzZjB:by3dads) ([raw file](https://github.com/robotlocomotion/drake/blob/210bb80daeca08ad60391ab52cdf8ecdde6ed536/drake/solvers/constraint.h#L115)):*
> ```objc
> 
>   template <typename DerivedQ>
>   void set_Q(const Eigen::MatrixBase<DerivedQ>& Q) {
> ```

No test coverage of this method.
While I am not concerned that this method itself could be wrong, a test using this method would help to catch any solvers accidentally retaining Q (or Q-derived data, such as convexity of the constraint) between runs (which was arguably valid before this change).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KS1n6OetqFfMvpJPfly:b-ksyyu4)*

**Comment by sammy-tri** [comment]
:lgtm:

I don't have a fully baked opinion about constraint mutability yet, and I might need to talk it out in person to get there.  Thoughts on the options above:

2 and 3 seem mostly identical in terms of what's required of MathematicalProgram and any solvers.

1 actually is interesting in that it seems like one solution where the MathematicalProgram knows with certainty which constraints have changed since the last Solve() invocation.   I'm not sure if this is important...  With mutable constraints some solvers (those which don't allow generic constraints) could cache the constraint information from the previous run and check it on the next invocation for changes...   Nonlinear/generic solvers would have no way of knowing, which might not be important.  (like I said, I need to think this out some more)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KS2XiVJG8GHVYsRABp4:b2urk45)*

**Comment by ggould-tri** [comment]
The more I think about it the more I think the strength reduction argument I made above is more correct than I thought.  The cases where an `Add*Constraint` method returns `Constraint` rather than a more specific type are exactly those where different values could cause different solvers to be invoked.  As such, retaining warm-start data across them would be wrong under most conditions.

I think 2 and 3 are fairly similar; I think 2 is a bit easier to write and I can't really construct an argument for why we might need some sort of invalidation boilerplate in every call.  So I think I come down on 'this PR is right iff it also promotes `set_bounds` and replaces `UpdateConstraint` as well'.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KS2fdd70geDZ4KMcz8K:bc0sh7h)*

**Comment by RussTedrake** [comment]
Sorry I was offline.  I agree that (2) is what is happening here and (1) and (3) are the most reasonable alternatives.  My slight preference for (3) is not that it is verbose, but that I could imagine many cases where we update only a part of the constraint, and it might be inefficient to recompute all of them.

I’m happy to add the additional documentation and update set_bounds and remove UpdateConstraint (which I’m embarassed that I missed).  

We could still come up with some invalidation approach by requiring that any setter method increments some unique id (generalized dirty bit) owned by the constraint object.  Solvers could check that ID quickly.

**Comment by ggould-tri** [comment]
@drake-jenkins-bot retest this please.

**Comment by ggould-tri** [comment]
@drake-jenkins-bot msvc-ninja-32,windows,debug please

**Comment by ggould-tri** [comment]
@drake-jenkins-bot retest this please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KSasyl_ZUYBrmaG9GWM:bvi7gqa)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
@drake-jenkins-bot retest this please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KSbuwlKflp7IShI5cO-:bvi7gqa)*

**Comment by ggould-tri** [comment]
Okay, after enough retests, that most recent test failure is real.  On win32 only, `C:\Users\Administrator\workspace\experimental\0b4ef046\drake\solvers\test\fastqp_solver_test.cc(59): error: Expected: result = prog.Solve() doesn't throw an exception.
  Actual: it throws.
`

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KSc5ypru61TcF5QJ1SS:b-3wwr9i)*

**Comment by siyuanfeng-tri** [comment]
@RussTedrake Just a heads up, I also need to update Q and b for quadratic constraints (https://github.com/RobotLocomotion/drake/pull/3593). I did something like (3).

**Comment by RussTedrake** [comment]
implemented (2) throughout.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/constraint.h, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-KS1mGf-E2XO2uyO0OKK:-KT5ptPJZSj_96zgy3VM:b-mvi8cu) ([raw file](https://github.com/robotlocomotion/drake/blob/3cc941839de1d0a4f5c8871360a678d9005a7b66/drake/solvers/constraint.h#L115)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> No test coverage of this method.
> While I am not concerned that this method itself could be wrong, a test using this method would help to catch any solvers accidentally retaining Q (or Q-derived data, such as convexity of the constraint) between runs (which was arguably valid before this change).
</details>
added a test to the fastqp test to provide minimal coverage (for at least one solver), but I agree we should add coverage for all solvers for all possible setters, etc, for constraints/objectives.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KT6-Lqun9AKutCg2kPc:b-gajijj)*

**Comment by RussTedrake** [comment]
sorry... i've actually switched back to option (3)... using "UpdateConstraint" instead of "set_*" methods, because they are slightly more general. (e.g., you cannot change the number of constraints by setting A then b individually... you really need to set them at the same time). but I do not think it would be bad to have both types of methods available.

**Comment by RussTedrake** [comment]
NB - still looking into the win32 exception.  hope to resolve it by the morning.

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-gcc-ninja-nightly-matlab-debug please
@drake-jenkins-bot mac-clang-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-clang-experimental-memcheck-valgrind please

**Comment by RussTedrake** [comment]
i can (finally) reproduce the error on my machine.  in win32 debug mode, I see (but am summarizing, because I cannot copy from the window)

```
Debug Assertion Failed!
in drakeOptimization.dll
in Visual Studio/.../memory()
Line 106

Expression: "(_Ptr_user & (_BIG_ALLOCATION_ALIGNMENT - 1)) == 0" && 0
```

haven't actually be able to step in with the debugger yet (and leaving this machine soon).  but am close.

**Comment by RussTedrake** [comment]
fwiw - am able to step into the assertion on msvc now.  the trick was to build as RelWithDebInfo.  Debug trips assertions in gtest all over the place and is unusable.

Confusingly, the assertion trips with the following call stack
```
 	drakeOptimization.dll!std::_Deallocate<char>(char * _Ptr, unsigned int _Count) Line 105	C++
 	drakeOptimization.dll!std::allocator<char>::deallocate(char * _Ptr, unsigned int _Count) Line 640	C++
 	drakeOptimization.dll!std::_Wrap_alloc<std::allocator<char> >::deallocate(char * _Ptr, unsigned int _Count) Line 912	C++
 	drakeOptimization.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy(bool _Built, unsigned int _Newsize) Line 2241	C++
 	drakeOptimization.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> >() Line 1007	C++
>	drakeOptimization.dll!drake::solvers::MathematicalProgram::AddContinuousVariables(unsigned int num_new_vars, std::basic_string<char,std::char_traits<char>,std::allocator<char> > name) Line 312	C++
 	fastqp_solver_test.exe!drake::solvers::`anonymous namespace'::testFastQP_unitBallExample_Test::TestBody() Line 19	C++
 	gtest.dll!59483360()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for gtest.dll]	
 	gtest.dll!59483400()	Unknown
 	gtest.dll!594830ab()	Unknown
 	gtest.dll!594a2bd3()	Unknown
 	gtest.dll!594a2eb9()	Unknown
 	gtest.dll!594a2d29()	Unknown
 	gtest.dll!594a3349()	Unknown
 	gtest.dll!594834b0()	Unknown
 	gtest.dll!5948328b()	Unknown
 	[External Code]	
```

i don’t see anything strange going on there.

**Comment by RussTedrake** [comment]
and just for giggles, it still asserts (with the same error) if I reduce my entire test to

```
GTEST_TEST(testFastQP, unitBallExample) {
  MathematicalProgram prog;
  auto x = prog.AddContinuousVariables(2);
}
```

how could this have not happened before?

**Comment by sammy-tri** [comment]
Wow, that operation (creating a MathematicalProgram on the stack and then adding continuous variables to it) happens in pretty much every case in the MathematicalProgram tests, which are passing in Jenkins...  Is that test passing locally for you?

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KTF2tIKyh-AYYp4Ooh6:bz4c7th)*

**Comment by RussTedrake** [comment]
@ggould-tri , @sammy-tri  -- i believe this is ready to merge.  PTAL?

**Comment by sammy-tri** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r4, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/constraint.h, line 155 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-KTKcGx9SAnM36olQ7aX:-KTKcGx9SAnM36olQ7aY:b-pplhp5) ([raw file](https://github.com/robotlocomotion/drake/blob/2daafe7efc04d67234be5572e11d46489c913f04/drake/solvers/constraint.h#L155)):*
> ```objc
>     void UpdateQuadraticAndLinearTerms(const Eigen::MatrixBase<DerivedQ>& new_Q,
>       const Eigen::MatrixBase<DerivedB>& new_b) {
>     if (new_Q.rows() != new_Q.cols() || new_Q.rows() != new_b.rows() ||
> ```

FYI This is a different/stronger assertion than above in the constructor...  namely it always runs as opposed to being debug only (as DRAKE_ASSERT is).  I'm also concerned that the test is duplicated...   Consider a single helper method to check the constraint parameters?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501)*

**Comment by ggould-tri** [comment]
I will get back to this review later this afternoon.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KTKe9Kz0pusynZPSULE:b-r4ll3i)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/solvers/constraint.h, line 155 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-KTKcGx9SAnM36olQ7aX:-KTMZ_qKLQAbhgT48vgy:b-5xnhuy) ([raw file](https://github.com/robotlocomotion/drake/blob/2daafe7efc04d67234be5572e11d46489c913f04/drake/solvers/constraint.h#L155)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> :+1: 
</details>
totally agree.  but it actually wasn't a change introduced in this PR (came in through a merge w/ master)

---

*[drake/solvers/test/fastqp_solver_test.cc, line 59 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-KTKytSuntqPkHYeEOjS:-KTM_jkYxABX2E9e2vTx:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/2daafe7efc04d67234be5572e11d46489c913f04/drake/solvers/test/fastqp_solver_test.cc#L59)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI:  Code conventions prefer `TODO(username)` format.
</details>
done

---

*[drake/solvers/test/fastqp_solver_test.cc, line 61 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-KTKz2qnT009zmW6HJSg:-KTM_kPP5aGGELmIvSks:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/2daafe7efc04d67234be5572e11d46489c913f04/drake/solvers/test/fastqp_solver_test.cc#L61)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI:  Code conventions prefer `TODO(username)` format.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501)*

**Comment by RussTedrake** [comment]
all fixed.  thx.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KTM_pYZzOPC2Hn1BeM6:buv0008)*

**Comment by RussTedrake** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/constraint.h, line 155 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-KTKcGx9SAnM36olQ7aX:-KTOGIrRClO1NUxeoVMd:b-520ayp) ([raw file](https://github.com/robotlocomotion/drake/blob/2daafe7efc04d67234be5572e11d46489c913f04/drake/solvers/constraint.h#L155)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> totally agree.  but it actually wasn't a change introduced in this PR (came in through a merge w/ master)
</details>
@sammy-tri , @ggould-tri -- blocked by your ok on this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501)*

**Comment by sammy-tri** [comment]
:lgtm: pending Jenkins

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501#-:-KTP71e7QeKQkRMYGBT4:bvlq01q)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3501)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
