### PR TITLE
Remove Gurobi and SNOPT 'from_source.rst'

### PR DESCRIPTION
**Pull request by soonho-tri**
Related #6474.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6624)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jamiesnape , feature-review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6624#-:-KpYHW4_GTdYKsE3L895:bgwxwsk)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6624)*

**Comment by soonho-tri** [comment]
+@seancurtis-tri , platform-review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6624#-:-Kp_IzhQYnpx7J6feyqh:b-bgt2kp)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: @sherm1 for final platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6624#-:-Kp_fDF5dx285Ll2WiFt:blugt0z)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6624#-:-KpaLGCn7RsjaUHrhdnv:bnfp4nl)*

**Comment by soonho-tri** [comment]
@jamiesnape , I am waiting for your LGTM.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6624#-:-KpaMSkM-5zL_J40P0TV:b-46avp8)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6624#-:-KpaNHVNSdk3AjGoQp9i:bnfp4nl)*

**Pull request merged**
