### PR TITLE
Fixes issue with integrators limiting simulator time advancement even when no continuous state is present.

### PR DESCRIPTION
**Pull request by edrumwri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6593)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@pangtao22 for feature review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpLZjezsPt5ZAdMEvoS:b-s5i9v5)*

**Comment by pangtao22** [comment]
I am not familiar with the internal mechanics of simulator. And this is also the first time I am reviewing a PR. What am I supposed to do?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpLqsOGifHFe0_ABNAU:b-dptjvp)*

**Comment by edrumwri** [comment]
Hi Pang, just look at the little bit of code (this is a very small PR) and see whether it looks reasonable or anything stands out to you. And see whether it fixes the problem we discussed last night without having to adjust the maximum simulator step size.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpLvF1reyYgbKshRzl1:bgnkn4w)*

**Comment by pangtao22** [comment]
I can't say I understand every line, but I think the code does what the comment says it does, and should fix my problem. Sorry that I am not able to provide more useful feedback.   

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpMZm9D6boK08whucLX:b-19nqzb)*

**Comment by pangtao22** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpM_qFvj7PQmsBZ_Xy7:bnfp4nl)*

**Comment by sherm1** [comment]
Sorry I don't have the context for this, but at first glance it doesn't seem right to me. Shouldn't the simulation always obey the maximum step size? Any per-step event would be affected, as would any internal code that might contain mutable counters, logging or whatever. Happy to feature review this if you can clarify the intent for me -- is there a motivating discussion somewhere? 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpMxKzQbdFYLYhav2to:bo44uf9)*

**Comment by pangtao22** [comment]
I was simulating this system:
[discrete-time system (period = 1s)] --> [SignalLogger]
and noticed that the logged data is 1KHz. 

I then asked if there's a way to log data at the frequency of the discrete-time system. Liang suggested setting `Simulator::get_mutable_integrator()->set_maximum_step_size()` to the period of the discrete-time system. Evan thought the simulator shouldn't run at any shorter time step when the system being simulated doesn't have continuous states, and hence this PR. 

There's also a discussion on slack: https://drakedevelopers.slack.com/archives/C2CHRT98E/p1500347588355315

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpNhTxFJuIIacf5-0Jz:b-jun3fu)*

**Comment by edrumwri** [comment]
@sherm1, are you satisfied with Pang's description?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpPqpA334tUsORPpc85:bl8s8rn)*

**Comment by sherm1** [comment]
Let's discuss f2f.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpQLpxZRq5WglML0whI:b-yatr66)*

**Comment by sherm1** [comment]
+@sherm1 for feature & platform.

:lgtm: except for one minor change per f2f, and pending CI.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/test/simulator_test.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-KpQi4g9uJHxeyUKMUYq:-KpQi4gAzTDmId6OcAMB:bsg1wju) ([raw file](https://github.com/robotlocomotion/drake/blob/afe811c28a534249deae0c086cb3c2a135242b63/drake/systems/analysis/test/simulator_test.cc#L101)):*
> ```cpp
> 
>   // Construct the simulation without any publishing and using the RK2
>   // (fixed step) integrator with a small time step.
> ```

BTW, per f2f it shouldn't matter whether there is per-step publishing or not, so I found this confusing. Please remove publish-related stuff here and just take the defaults.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpQinApULYJEmK_jX95:b1vc6jw)*

**Comment by edrumwri** [comment]
@pangtao, since @sherm1 found only a very minor issue with this, and he is one of our top reviewers, I'd say you did a good job. Congratulations on a successful review!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpQqU3kQ5Osfz54gTrB:b-4iz2nc)*

**Comment by edrumwri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6593#-:-KpR2rmo6vouZunA3Ikp:b-ckwj5z)*

**Pull request merged**
