### PR TITLE
Fix more uninitialized variable warnings

### PR DESCRIPTION
**Pull request by jamiesnape**
There is one more warning for non-MATLAB builds, but it will be fixed by #4143.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4173)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review and +@david-german-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by david-german-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/externals.cmake, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWtdnVzR07Lw0fxuMPZ:-KWtdnW-UUem_MQdcYrq:b2qn186) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/cmake/externals.cmake#L72)):*
> ```CMake
>   set(_out)
>   foreach(_var ${ARGN})
>     if(DEFINED ${_var})
> ```

this...seems like cheating.  What's it working around?

---

*[drake/CMakeLists.txt, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWteLMZQ7aoTFJP95uP:-KWteLMZQ7aoTFJP95uQ:bdhd71u) ([raw file](https://github.com/robotlocomotion/drake/blob/1e043bdd74bf6eeba55464bc04b469eb8e65d686/drake/CMakeLists.txt#L233)):*
> ```CMake
> else()
>   set(LD_LIBRARY_PATH "$ENV{LD_LIBRARY_PATH}" CACHE STRING "Environment variable used to launch processes from Matlab")
>   mark_as_advanced(LD_LIBRARY_PATH)
> ```

why get rid of this?

---

*[drake/doc/CMakeLists.txt, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWteUlE6MVkxs46Ru4O:-KWteUlE6MVkxs46Ru4P:b-3ecygp) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/drake/doc/CMakeLists.txt#L67)):*
> ```CMake
> endif()
> 
> if(DEFINED OXYGEN_DIR)
> ```

ditto for "seems like cheating"; why is this sometimes undefined?

---

*[drake/doc/CMakeLists.txt, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWteZ21xxykmj70fDb0:-KWteZ21xxykmj70fDb1:b-7355o3) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/drake/doc/CMakeLists.txt#L67)):*
> ```CMake
> endif()
> 
> if(DEFINED OXYGEN_DIR)
> ```

btw CMake doesn't short-circuit boolean evaluation?  TIL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173)*

**Comment by david-german-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/externals.cmake, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWtdnVzR07Lw0fxuMPZ:-KWtf_qDYB7rnyfFbHMK:bn4emtf) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/cmake/externals.cmake#L72)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> this...seems like cheating.  What's it working around?
</details>
CMAKE_JAVA_COMPILE_FLAGS which may not be defined by the user. MATLAB_Root_DIR which will not be defined if MATLAB is not present. A lot of these things are only important if the user decided to define them. If you define them as empty, you can get a different behavior in the child project.

---

*[drake/CMakeLists.txt, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWteLMZQ7aoTFJP95uP:-KWtf7QUkTugo58bfoAO:b-u2yd9p) ([raw file](https://github.com/robotlocomotion/drake/blob/1e043bdd74bf6eeba55464bc04b469eb8e65d686/drake/CMakeLists.txt#L233)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> why get rid of this?
</details>
INTERNAL cache variables are already advanced.

---

*[drake/doc/CMakeLists.txt, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWteUlE6MVkxs46Ru4O:-KWtfSdNcMXYZ3TV867B:b-falcfn) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/drake/doc/CMakeLists.txt#L67)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> ditto for "seems like cheating"; why is this sometimes undefined?
</details>
If you do not have oXygen XML Editor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/externals.cmake, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWtdnVzR07Lw0fxuMPZ:-KWtgw4lAXMgNhRnR8uH:b-gmgraq) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/cmake/externals.cmake#L72)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> CMAKE_JAVA_COMPILE_FLAGS which may not be defined by the user. MATLAB_Root_DIR which will not be defined if MATLAB is not present. A lot of these things are only important if the user decided to define them. If you define them as empty, you can get a different behavior in the child project.
</details>
See, for instance, here https://github.com/RobotLocomotion/drake/blob/master/CMakeLists.txt#L46-L48 where setting cache variables to empty has a different effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/externals.cmake, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWtdnVzR07Lw0fxuMPZ:-KWtm7pKKyGzGyKSSpd8:b3kljnr) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/cmake/externals.cmake#L72)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> See, for instance, here https://github.com/RobotLocomotion/drake/blob/master/CMakeLists.txt#L46-L48 where setting cache variables to empty has a different effect.
</details>
Makes sense.  Please add a comment, though!

---

*[drake/doc/CMakeLists.txt, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWteUlE6MVkxs46Ru4O:-KWtmIeJZi6hXtpj4XvC:bbqdowi) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/drake/doc/CMakeLists.txt#L67)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> If you do not have oXygen XML Editor.
</details>
oh, I see, it's directly above.  Maybe just combine these if statements?  then it's clear the condition is really just on an env var.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/CMakeLists.txt, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWteUlE6MVkxs46Ru4O:-KX6LqWnYB7a31Zyp3Ic:bfohnv4) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/drake/doc/CMakeLists.txt#L67)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> oh, I see, it's directly above.  Maybe just combine these if statements?  then it's clear the condition is really just on an env var.
</details>
That changes the logic. The environment variable initializes the cache variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cmake/config.cmake, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KX6Op13COE4GfSRm-Cm:-KX6Op14AjSmIX9fVaUv:bhxpm86) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/cmake/config.cmake#L57)):*
> ```CMake
>           SIMULINK)
>     else()
>       unset(MATLAB_EXECUTABLE CACHE)
> ```

I don't think we should do this... if we are here, the user has *not* disabled MATLAB, but it can't be found. In this case, I think it makes sense to have MATLAB_EXECUTABLE in the cache, in case the user wants to point to it manually. (Compare: we leave `Foo_DIR` in the cache if `Foo` can't be found...)

---

*[cmake/externals.cmake, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWtdnVzR07Lw0fxuMPZ:-KX6PKwchINEtpgmzbKT:b4ofr02) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/cmake/externals.cmake#L72)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Makes sense.  Please add a comment, though!
</details>
I guess this would have stopped drake from unintentionally becoming static, also :smile:.

---

*[drake/CMakeLists.txt, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KX6QBIS2_qgnZgR9tIo:-KX6QBITaeIOlt7gAYMw:b-sv9r1i) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/drake/CMakeLists.txt#L228)):*
> ```CMake
> # Used by matlab/util/systemWCMakeEnv.m
> if(APPLE)
>   if(DEFINED ENV{DYLD_LIBRARY_PATH})
> ```

BTW, this is feeling like a function/macro candidate...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/CMakeLists.txt, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KX6QBIS2_qgnZgR9tIo:-KX6UK8KOkaTpsW02ui_:b6vp3sl) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/drake/CMakeLists.txt#L228)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> BTW, this is feeling like a function/macro candidate...
</details>
BTW I am hoping we can just drop this soon... I need to do a little more investigation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/config.cmake, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KX6Op13COE4GfSRm-Cm:-KX6XOMKi8hKmVHT7Sld:bmqftfh) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/cmake/config.cmake#L57)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I don't think we should do this... if we are here, the user has *not* disabled MATLAB, but it can't be found. In this case, I think it makes sense to have MATLAB_EXECUTABLE in the cache, in case the user wants to point to it manually. (Compare: we leave `Foo_DIR` in the cache if `Foo` can't be found...)
</details>
Done, though I am thinking that we may be able to drop the `MATLAB_EXECUTABLE` logic now that Windows is not involved.

---

*[cmake/externals.cmake, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KWtdnVzR07Lw0fxuMPZ:-KX6XcB2Lw5MI9LVhgtE:bs3mhdg) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/cmake/externals.cmake#L72)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I guess this would have stopped drake from unintentionally becoming static, also :smile:.
</details>
Comment added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/config.cmake, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-KX6Op13COE4GfSRm-Cm:-KX6Y3c7JfUO2YmfnbTa:bd9czsh) ([raw file](https://github.com/robotlocomotion/drake/blob/df1fac095d40f8b243c371e9b8e5d684c8ec4b1f/cmake/config.cmake#L57)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Done, though I am thinking that we may be able to drop the `MATLAB_EXECUTABLE` logic now that Windows is not involved.
</details>
Hmm, yes, that seems plausible; the trouble was something with the Windows registry IIRC? In that case, I assume FindMatlab.cmake will set whatever is needed for the user to "help", if needed, which WFM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-:-KX6Y_27pR9xxjfx7W7T:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4173#-:-KX6_R36OkXxuzRqVJYa:bnfp4nl)*

**Pull request merged**
