### PR TITLE
[geometry/dev] drop gunicorn for single threaded flask server

### PR DESCRIPTION
**Pull request by svenevs**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16595)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@zachfang for review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16595#-:-MvyuZTE2ezxbABN2v1E:b95hb89)* status: 2 unresolved discussions, LGTM missing from assignee zachfang (waiting on @zachfang)

___
*[geometry/render/dev/BUILD.bazel, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-Mvyue-K059-ZO42x2qD:-Mvyue-K059-ZO42x2qE:bafxrcf) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/BUILD.bazel#L125)):*
> ```Starlark
>     srcs = ["render_server/gltf_render_server.py"],
>     data = [":vtk_render_server_backend"],
>     main = "render_server/gltf_render_server.py",
> ```

The other option we have here is to set an environment variable `FLASK_APP` and use `flask run`, **but** I don't know how to get the path to wherever bazel is going to _copy_ the file to.  It needs to be the file in the bazel build tree, because we depend on `data = [":vtk_render_server_backend"]` so that the `render_callback` can just blindly find `vtk_render_server_backend` compiled executable.

So instead of trying to figure that out, I just simplified the `gltf_render_server.py` to have some simple command line arguments for `--host` and `--port` and otherwise use all flask defaults.  This seems fine to me but wanted to call out the change directly.
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 953 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-Mvyvg6384iHwwCdtYVT:-Mvyvg6384iHwwCdtYVU:b-15ydb0) ([raw file](https://github.com/robotlocomotion/drake/blob/7285618ae24341714485ca1669b7edb92c1bf734/geometry/render/dev/render_server/gltf_render_server.py#L953)):*
> ```Python
>             )
>         # NOTE: this just runs the formatting and linting checks on this file.
>         elif sys.argv[1] == "devcheck":
> ```

FYI i'm just running black / flake8 / mypy locally now.
___
*[geometry/render/dev/render_server/README.md, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MvywJm0DSu-R7ZSXYlZ:-MvywJm0DSu-R7ZSXYl_:b-1isd4u) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/render_server/README.md#L47)):*
> ```Markdown
> A single threaded worker flask server is not a good idea to run in production,
> as it will not be able to handle concurrent requests.  You may use any number
> of WSGI runners, in the example below we use [gunicorn](https://gunicorn.org/):
> ```

FYI including instructions on using a WSGI runner such as `gunicorn` is good for consumers who want to make their own servers.  There are other choices, but I don't know them well enough to say anything else.  Back when I learned all this stuff, IIRC I chose `gunicorn` exclusively because of its name :upside_down_face:
___
*[geometry/render/dev/render_server/README.md, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MvyvpY-5-Lo7ZKyG8Wi:-MvyvpY-5-Lo7ZKyG8Wj:b-qblmyy) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/render_server/README.md#L64)):*
> ```Markdown
>   demand, adjust the number of workers accordingly.  **Note** that in the API
>   the worker does not respond until the rendering is complete -- so if 8 workers
>   are being used actively, the ninth request will not be able to be handled.
> ```

This note is important enough to reiterate to review, this is the implication of having everything in one curl transaction.  Does not need to block this PR (unless verbiage should change).  Meaning if your render server is to handle many requests, you will need many workers in the current design.  This may be good to discuss in the meeting.
___
*[geometry/render/dev/render_server/wsgi.py, line 0 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MvywfV43XqQZMJpVm6W:-MvywfV43XqQZMJpVm6X:b-2ichzw) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/render_server/wsgi.py#L0)):*
FYI this file, as documented above, is only needed when using a WSGI wrapper.  They wrap the flask app and do a bunch of changes on their own, e.g. in the docs `--bind {host}:{port}` args for `gunicorn` replace the standard flask `app.run(host={host}, port={port})`.

**Review by zachfang — COMMENTED** [review]
:lgtm:. I left some comments, most of them are none-blocking.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16595#-:-MwAEH211ToO_HtThSru:b4xdk6r)* status: 4 unresolved discussions (waiting on @svenevs)

___
*[geometry/render/dev/BUILD.bazel, line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MwA6TdM9TfBLavspln-:-MwA6TdM9TfBLavspln0:b-suyagt) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/BUILD.bazel#L118)):*
> ```Starlark
> # instructions to run this server, the drake setup scripts do not include the
> # dependencies for this target.
> # TODO(svenevs): install the final list of dependencies when decided.
> ```

Nit: is this comment still relevant?
___
*[geometry/render/dev/BUILD.bazel, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-Mvyue-K059-ZO42x2qD:-MwA5OjkE3kAadh6Doca:bhsdzs3) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/BUILD.bazel#L125)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

The other option we have here is to set an environment variable `FLASK_APP` and use `flask run`, **but** I don't know how to get the path to wherever bazel is going to _copy_ the file to.  It needs to be the file in the bazel build tree, because we depend on `data = [":vtk_render_server_backend"]` so that the `render_callback` can just blindly find `vtk_render_server_backend` compiled executable.

So instead of trying to figure that out, I just simplified the `gltf_render_server.py` to have some simple command line arguments for `--host` and `--port` and otherwise use all flask defaults.  This seems fine to me but wanted to call out the change directly.
</blockquote></details>

LGTM. IMO running via `bazel run` is preferred.
___
*[geometry/render/dev/render_server/README.md, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MwAA6ff6RPmClRbDtHm:-MwAA6ff6RPmClRbDtHn:b-lgb6vn) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/render_server/README.md#L43)):*
> ```Markdown
> to launch a single threaded / single worker flask development server.  By
> default this will run the server on host `127.0.0.1` and port `8000`, you may
> specify `--host x.y.z.w` or `--port XYZW` to change the host or port.
> ```

Nit: can we put the full command with arguments here to be super explicit (people sometimes forget to put `--` in between). I.e.,
```
bazel run //geometry/render/dev:server -- --host x.y.z.w --port XYZW
```
___
*[geometry/render/dev/render_server/README.md, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MvyvpY-5-Lo7ZKyG8Wi:-MwADlAR45a376hxsL50:b7wvwm6) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/render_server/README.md#L64)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

This note is important enough to reiterate to review, this is the implication of having everything in one curl transaction.  Does not need to block this PR (unless verbiage should change).  Meaning if your render server is to handle many requests, you will need many workers in the current design.  This may be good to discuss in the meeting.
</blockquote></details>

OK. Thanks for bringing this up. Yes, I think this is what we are envisioning from our initial proposal.

Regarding `the ninth request will not be able to be handled`, will the ninth request be dropped or waiting on a queue (or similar)?

**Review by svenevs — COMMENTED** [review]
:lgtm: but see additional comments below, in case more information should be included re: what happens when all the workers are tied up.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16595#-:-MwTVD4P7Gch7s2rERa_:b-mwk4nz)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @zachfang)

___
*[geometry/render/dev/BUILD.bazel, line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MwA6TdM9TfBLavspln-:-MwTJZkp1cDuVtWYpkt0:bd326w7) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/BUILD.bazel#L118)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Nit: is this comment still relevant?
</blockquote></details>

Done.  Yes, `flask` at the very least will need to end up in the test requirements.  If something gets promoted to an example then possibly the source distribution requirements.  We should solve that in the future, the comment here is the note to remember to do that :slightly_smiling_face:
___
*[geometry/render/dev/render_server/README.md, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MwAA6ff6RPmClRbDtHm:-MwTKvve4ltdUuJJsE8h:b-ohdol) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/render_server/README.md#L43)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Nit: can we put the full command with arguments here to be super explicit (people sometimes forget to put `--` in between). I.e.,
```
bazel run //geometry/render/dev:server -- --host x.y.z.w --port XYZW
```
</blockquote></details>

Done, good call!
___
*[geometry/render/dev/render_server/README.md, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MvyvpY-5-Lo7ZKyG8Wi:-MwTRdePEPC6K5895a7V:b-xou0gm) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/render_server/README.md#L64)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

OK. Thanks for bringing this up. Yes, I think this is what we are envisioning from our initial proposal.

Regarding `the ninth request will not be able to be handled`, will the ninth request be dropped or waiting on a queue (or similar)?
</blockquote></details>

OK, great question, I did some additional research and updated the verbiage here as well as linked to https://github.com/benoitc/gunicorn/issues/1492#issuecomment-294436705 as well as did some stress testing.  With 4 workers sleeping for 2 minutes per render request, they were all eventually able to process something when running ~16 different clients.  I tried to super-stress test it but bazel ultimately won't allow me to have more processes running than would hit the suggested cap of `2048` requests waiting in queue.  In other words, I can't say with certainty what happens :no_mouth:

The tagline being that ultimately, if you are hosting a render server and more than one person is trying to render things on it, you'll want to coordinate.  We don't have any fancy queue here and that's beyond the scope of this document / implementation. My understanding is you could have a server backend (apache, nginx) reject new requests.  Alternatively, if we change things to have the client submit a render request that returns immediately and then continue to poll, I guess the server could try and respond with something like

1. In queue
2. Currently rendering
3. Send final result, and for completion
4. No such render request

Meaning server responses become more or less instantaneous, but now we need to implement an actual database on the server and implement polling on the client with possible timeouts.  It is not clear to me that this would be worth the effort.  I vote that this PR merges provided the above verbiage is sufficient, and we contemplate the above if it seems necessary.

**Review by zachfang — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16595)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @svenevs)

___
*[geometry/render/dev/render_server/README.md, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16595#-MvyvpY-5-Lo7ZKyG8Wi:-MwXzhm5C9fmc6jMoKkk:b-q7cgks) ([raw file](https://github.com/robotlocomotion/drake/blob/6072ea348ca0001bf6d6d311cf694f8a724ee835/geometry/render/dev/render_server/README.md#L64)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

OK, great question, I did some additional research and updated the verbiage here as well as linked to https://github.com/benoitc/gunicorn/issues/1492#issuecomment-294436705 as well as did some stress testing.  With 4 workers sleeping for 2 minutes per render request, they were all eventually able to process something when running ~16 different clients.  I tried to super-stress test it but bazel ultimately won't allow me to have more processes running than would hit the suggested cap of `2048` requests waiting in queue.  In other words, I can't say with certainty what happens :no_mouth:

The tagline being that ultimately, if you are hosting a render server and more than one person is trying to render things on it, you'll want to coordinate.  We don't have any fancy queue here and that's beyond the scope of this document / implementation. My understanding is you could have a server backend (apache, nginx) reject new requests.  Alternatively, if we change things to have the client submit a render request that returns immediately and then continue to poll, I guess the server could try and respond with something like

1. In queue
2. Currently rendering
3. Send final result, and for completion
4. No such render request

Meaning server responses become more or less instantaneous, but now we need to implement an actual database on the server and implement polling on the client with possible timeouts.  It is not clear to me that this would be worth the effort.  I vote that this PR merges provided the above verbiage is sufficient, and we contemplate the above if it seems necessary.
</blockquote></details>

LGTM and yes this documentation should suffice for now.

**Review by svenevs — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16595#-:-MwYLqDm4ZYTfMI2AZIe:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @svenevs)

**Pull request merged**
