### PR TITLE
MBT energy shaping for pendulum example

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implements the equivalent example in `drake/examples/pendulum` using an MBT model in `drake/examples/multibody/pendulum`.

Right now dependent on #7172 and on #7542.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7543)

### CODE REVIEW

**Comment by RussTedrake** [comment]
i think you should replace the examples/pendulum, not add a parallel example in the multibody directory?

**Comment by amcastro-tri** [comment]
@RussTedrake, they way I see it is that both add value on different ways. `examples/pendulum` illustrates how to simulate a pendulum with hand-written dynamics while `examples/multibody/pendulum` illustrates the MBT pipeline.
That, of course, is my own view of things. Would you like me to entirely replace `example/pendulum`? (I don't think for instance that you'll get a neatly printed dynamics equations using `symbolic::Expression` in the MBT version)

**Comment by RussTedrake** [comment]
i see.  matlab drake had both examples in the same directory -- one with hand-written dynamics and one from Pendulum.urdf.  I agree that both are useful and should stick around, but would think they should be collocated?

**Comment by amcastro-tri** [comment]
IMO @RussTedrake separate directories helps to control the number of files in the same place. Not super strong about it though. Separate directories were in general prefered by people when asking in Slack, [see here](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1511966730000138)

**Comment by jwnimmer-tri** [comment]
@amcastro-tri time to close this?  Or if is is only for CI testing, please rename it as such.

**Comment by jwnimmer-tri** [comment]
@amcastro-tri I will take silence to mean assent.  You can reopen if / when needed.

**Pull request closed without merging**
