### PR TITLE
Build shared LCM

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Build LCM as shared with hidden visibility. Implement export header generation for LCM.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6078)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tools/generate_export_header.bzl, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-Kjt2SBR8JRigqUITAHv:-Kjt2SBR8JRigqUITAHw:bo6awcu) ([raw file](https://github.com/robotlocomotion/drake/blob/4d3c03a9f9fa1e5a8816b7abe03880f69b814159/tools/generate_export_header.bzl#L27)):*
> ```Python
>         "",
>         "#endif",
>         ]
> ```

Indent?

---

*[tools/generate_export_header.bzl, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-Kjt3fEfujJTuOB2lysf:-Kjt3fEgn5T2zj3IDgtH:b-qxki8i) ([raw file](https://github.com/robotlocomotion/drake/blob/4d3c03a9f9fa1e5a8816b7abe03880f69b814159/tools/generate_export_header.bzl#L52)):*
> ```Python
>     is an incomplete implementation of CMake's generate_export_header. (In
>     particular, it does not generate NO_EXPORT or DEPRECATED symbols, and it
>     assumes an ELF platform.)
> ```

What about  Mach-O?

---

*[tools/generate_export_header.bzl, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-Kjt2lApzllL88299BxD:-Kjt2lApzllL88299BxE:bng02rt) ([raw file](https://github.com/robotlocomotion/drake/blob/4d3c03a9f9fa1e5a8816b7abe03880f69b814159/tools/generate_export_header.bzl#L62)):*
> ```Python
>     """
> 
>     if name == None:
> ```

BTW `== None` always bothers me for some reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6078)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tools/generate_export_header.bzl, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-Kjt2SBR8JRigqUITAHv:-Kjt4w3M1ERGHQb7rf2X:btpy1ct) ([raw file](https://github.com/robotlocomotion/drake/blob/4d3c03a9f9fa1e5a8816b7abe03880f69b814159/tools/generate_export_header.bzl#L27)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Indent?
</blockquote></details>

Gah, that's how katepart thinks it _should_ be indented...

---

*[tools/generate_export_header.bzl, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-Kjt3fEfujJTuOB2lysf:-Kjt56HvQBq5RCloYEhl:bxr7ns1) ([raw file](https://github.com/robotlocomotion/drake/blob/4d3c03a9f9fa1e5a8816b7abe03880f69b814159/tools/generate_export_header.bzl#L52)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

What about  Mach-O?
</blockquote></details>

...seems to use the same stuff; I guess the comment should read `ELF/Mach-O`?

---

*[tools/generate_export_header.bzl, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-Kjt2lApzllL88299BxD:-Kjt5DFGNH-1-rBGhMle:b-yjtoxr) ([raw file](https://github.com/robotlocomotion/drake/blob/4d3c03a9f9fa1e5a8816b7abe03880f69b814159/tools/generate_export_header.bzl#L62)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW `== None` always bothers me for some reason.
</blockquote></details>

There is no `is None` in Skylark... I'm open to alternative suggestions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6078)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/generate_export_header.bzl, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-Kjt2SBR8JRigqUITAHv:-Kjt6JuWY9voWo9P5lCX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4d3c03a9f9fa1e5a8816b7abe03880f69b814159/tools/generate_export_header.bzl#L27)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Gah, that's how katepart thinks it _should_ be indented...
</blockquote></details>

Done.

---

*[tools/generate_export_header.bzl, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-Kjt3fEfujJTuOB2lysf:-Kjt6KeQ-Lm4Rv7XlOJv:b-6yn1ko) ([raw file](https://github.com/robotlocomotion/drake/blob/4d3c03a9f9fa1e5a8816b7abe03880f69b814159/tools/generate_export_header.bzl#L52)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...seems to use the same stuff; I guess the comment should read `ELF/Mach-O`?
</blockquote></details>

Done. (Reworded to say "uses `__attribute__((visibility("default")))`" instead.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6078)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[tools/generate_export_header.bzl, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-Kjt2lApzllL88299BxD:-Kjt7H_6rjWp2LHcSL3F:baa6tmw) ([raw file](https://github.com/robotlocomotion/drake/blob/4d3c03a9f9fa1e5a8816b7abe03880f69b814159/tools/generate_export_header.bzl#L62)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

There is no `is None` in Skylark... I'm open to alternative suggestions?
</blockquote></details>

I tend to use `if not name:`, but `if name == None:` is fine despite it bothering me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-:-Kjt8v7ax-LB7G2Av3O_:bnfp4nl)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6078)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/generate_export_header.bzl, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-KjuIMsrHbpX1bQTe9qE:-KjuIMsrHbpX1bQTe9qF:b-l403jn) ([raw file](https://github.com/robotlocomotion/drake/blob/a678b5361a63e0cc774071bedc8a91e1e4194167/tools/generate_export_header.bzl#L14)):*
> ```Python
>     output = ctx.outputs.out
> 
>     guard = _make_identifier(output.basename.upper())
> ```

FYI I would be fine dropping `_make_identifier` and `guard` code, and just doing `#pragma once`; some of the other `tools/*.bzl` header-generation scripts already presume that pragma-once needs to work.

---

*[tools/lcm.BUILD, line 60 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-KjuGlIiRrwb7oP6scxf:-KjuGlIj10aqda3Lhr8C:bu935ay) ([raw file](https://github.com/robotlocomotion/drake/blob/a678b5361a63e0cc774071bedc8a91e1e4194167/tools/lcm.BUILD#L60)):*
> ```
>     copts = LCM_COPTS,
>     deps = ["@glib//:lib"],
>     includes = [".", "lcm"],
> ```

Please add something like `# TODO(jwnimmer-tri) Try to remove "lcm" here because it pollutes the include path.` above this statement.  I had started digging into that but got distracted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-:-KjuIbz0s0TOiAwKNGzl:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/generate_export_header.bzl, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-KjuIMsrHbpX1bQTe9qE:-KjwzhCBazMuf60xs1xm:b-7omj9x) ([raw file](https://github.com/robotlocomotion/drake/blob/a678b5361a63e0cc774071bedc8a91e1e4194167/tools/generate_export_header.bzl#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I would be fine dropping `_make_identifier` and `guard` code, and just doing `#pragma once`; some of the other `tools/*.bzl` header-generation scripts already presume that pragma-once needs to work.
</blockquote></details>

If this was just for Drake, maybe... when I wrote it, I was keeping in mind the ideal of eventually having it replicate all of the function of CMake's `generate_export_header` (including platform support) and possibly being upstreamed.

---

*[tools/lcm.BUILD, line 60 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6078#-KjuGlIiRrwb7oP6scxf:-Kjx-42L8ZgZUSMNqZCH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a678b5361a63e0cc774071bedc8a91e1e4194167/tools/lcm.BUILD#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please add something like `# TODO(jwnimmer-tri) Try to remove "lcm" here because it pollutes the include path.` above this statement.  I had started digging into that but got distracted.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6078)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6078)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

**Pull request merged**
