### PR TITLE
buildcop: Disable a test failing TSAN

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18478)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-thread-sanitizer please.

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-thread-sanitizer please.
</blockquote></details>

@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-thread-sanitizer please.

**Review by rpoyner-tri — COMMENTED** [review]
FYI @hongkai-dai 
+@ggould-tri for both +(status: single reviewer ok) 
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18478#-:-NJf5h6C5lkbq7Gte4AF:b-sb90xn)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:
I'm assuming we don't need an issue number for the todo-equivalent-comment there because it's dev.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18478#-:-NJfC54S4W6Gx7c1yCaA:bowlyc7)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

**Pull request merged**
