### PR TITLE
Remove pod-build from the documented Windows library paths.

### PR DESCRIPTION
**Pull request by david-german-tri**
It is not supported in CI since https://github.com/RobotLocomotion/drake-ci/commit/538b885acaf760186aa852ae16bbdd3e4775f671.  It came back briefly for MATLAB, but has since been removed altogether.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2497)

### CODE REVIEW

**Comment by david-german-tri** [comment]
+@jamiesnape 

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> #### Remove pod\-build from the documented Windows library paths\.
> 
> It is not supported in CI since https://github.com/RobotLocomotion/drake-ci/commit/538b885acaf760186aa852ae16bbdd3e4775f671.  It came back briefly for MATLAB, but has since been removed altogether.
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2497#-:-KJGVxi_rk9VnxkB1FJe:865962077)*

**Comment by jamiesnape** [comment]
Hopefully, this will eventually be build directory or install directory and the install will be optional, but with the current limitations :lgtm:.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> +@jamiesnape 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2497#-:-KJGXC4TvNlfWQzjJEkB:-772729375)*

**Comment by liangfok** [comment]
Let me double check that this works on my Windows PC...just a sec.

<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Hopefully, this will eventually be build directory or install directory and the install will be optional, but with the current limitations :lgtm:.
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2497#-:-KJGYGQ1OgpwjLDqyJG2:316505941)*

**Comment by david-german-tri** [comment]
@liangfok thanks for double-checking!  What was the outcome?

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Let me double check that this works on my Windows PC...just a sec.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2497#-:-KJHJKwyn332_049h-Lq:-577148842)*

**Comment by liangfok** [comment]
Sorry I haven't had a chance to run the test yet. I need to meet some people on campus now but will have it done before I leave the office today. Sorry for the delay!

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> @liangfok thanks for double-checking!  What was the outcome?
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2497#-:-KJHMkcbGc5omfTEzAbD:-228846041)*

**Comment by david-german-tri** [comment]
No rush, thanks for volunteering to do it at all!

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Sorry I haven't had a chance to run the test yet. I need to meet some people on campus now but will have it done before I leave the office today. Sorry for the delay!
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2497#-:-KJHODwwi7jyHZiZqCM5:884486568)*

**Comment by liangfok** [comment]
:lgtm: I verified it works on my windows PC.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> No rush, thanks for volunteering to do it at all!
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2497#-:-KJILOgqQiCZ4lFQuJbC:352014922)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> :lgtm: I verified it works on my windows PC.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2497#-:-KJINK1t3alorMCl0aaN:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to out-of-date-with-master.

**Pull request merged**
