### PR TITLE
Revert "Start to use SystemScalarConverter"

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Dear @jwnimmer-tri ,

The on-call build cop, @m-chaturvedi, believes that your PR #6684 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-clang-bazel-continuous-everything-release/4/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6740)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-continuous-release please
@drake-jenkins-bot mac-clang-bazel-continuous-release please
@drake-jenkins-bot mac-clang-bazel-continuous-everything-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
This appears to be a CI-only failure.  Several local macs at TRI cannot repro it.  I don't think we should merge this in a hurry, until it matters to some user or developer.  Hopefully we can fix-forward once someone finds a way to repro it.

**Comment by jwnimmer-tri** [comment]
Results from CI builds of master:
- FAIL OS X 10.11: https://drake-jenkins.csail.mit.edu/view/Mac/job/mac-elcapitan-clang-bazel-experimental/3/
  - ???(building) OS X 10.11 debug: https://drake-jenkins.csail.mit.edu/view/Mac/job/mac-clang-bazel-experimental/85/
- PASS macOS 10.12: https://drake-jenkins.csail.mit.edu/view/Mac/job/mac-sierra-clang-bazel-experimental/3/

**Comment by jwnimmer-tri** [comment]
So it looks like a bug in El Capitan in release mode only.  My guess is either a wrong-code generation bug in that version of Apple Clang, or that the PR was invoking UB that only that version of Clang noticed.

**Comment by jwnimmer-tri** [comment]
Summary from slack: with Soonho driving a machine that he downgraded to Xcode 7.3, we were able to repro and then try various work-arounds.  The problem seemed related to the move constructor for `std::map<> funcs_;`.  Trying to change its linkage and inlining didn't help, but replacing it with a `std::unordered_map` instead seems to avoid the problem.  I will PR that fix-forward.

**Comment by jwnimmer-tri** [comment]
Fix-forward attempt is at #6747.

**Comment by jwnimmer-tri** [comment]
Should be fixed now.  We can re-open if Continuous Production says others.

**Pull request closed without merging**
