### PR TITLE
Add more functionality to PR2 IK test and wrap RigidBodyFrame

### PR DESCRIPTION
**Pull request by rdeits**
This makes the PR2 IK demo more useful by showing off custom frames and a more sensible set of constraints.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2311)

### CODE REVIEW

**Comment by rdeits** [comment]
@amcastro-tri can you take a look at this?

**Comment by liangfok** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 19 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KIhgVj3iruK1CjpLd-E:-KIhgVj3iruK1CjpLd-F:-956688519) ([raw file](https://github.com/robotlocomotion/drake/blob/6807a81dcc3ae9d632053c5318fc8cd221069d57/drake/bindings/python/pydrake/test/testPR2IK.py#L19)):*
> ```Python
> 
> constraints = [
>                # These three constriants ensure that the base of the robot is
> ```

"constriants" → "constraints"

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KIhfjvbU2iWkXwqV7Ex:-KIhfjvbU2iWkXwqV7Ey:-794960908) ([raw file](https://github.com/robotlocomotion/drake/blob/6807a81dcc3ae9d632053c5318fc8cd221069d57/drake/bindings/python/pydrake/test/testPR2IK.py#L23)):*
> ```Python
>                # constraining orientation, we just require that the points at
>                # [0, 0, 0], [1, 0, 0], and [0, 1, 0] in the robot's base's
>                # frame must a all be at z = 0 in world frame. NaN values
> ```

"a all" →"all"

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 36 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KIhghahegtPLiaX8xpy:-KIhghahegtPLiaX8xpz:20908972) ([raw file](https://github.com/robotlocomotion/drake/blob/6807a81dcc3ae9d632053c5318fc8cd221069d57/drake/bindings/python/pydrake/test/testPR2IK.py#L36)):*
> ```Python
>                                           np.array([0., 1, 0]),
>                                           np.array([np.nan, np.nan, 0]),
>                                           np.array([np.nan, np.nan, 0])),
> ```

Do the NaN values above mean "no constraint along this dimension"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311)*

**Comment by rdeits** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 36 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KIhghahegtPLiaX8xpy:-KIi8kBdNx4EYZ8Dq-_S:-317573705) ([raw file](https://github.com/robotlocomotion/drake/blob/6807a81dcc3ae9d632053c5318fc8cd221069d57/drake/bindings/python/pydrake/test/testPR2IK.py#L36)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Do the NaN values above mean "no constraint along this dimension"?
</details>
Yes. I've updated the comment above to make that more clear

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311)*

**Comment by liangfok** [comment]
:lgtm: However, I'm not classifying myself as either platform or feature reviewer b/c I didn't actually test the code. Hopefully +@amcastro-tri can provide an official feature review and +@jwnimmer-tri can provide the official platform review.

<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary>
> @amcastro-tri can you take a look at this? 
</details>


---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-:-KIiCjCTSPHUW4tMSmxd:188839270)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311)*

**Comment by jwnimmer-tri** [comment]
Looks decent in a 60-second read through.  I will wait for feature review to finish before diving in any deeper, though.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> :lgtm: However, I'm not classifying myself as either platform or feature reviewer b/c I didn't actually test the code. Hopefully +@amcastro-tri can provide an official feature review and +@jwnimmer-tri can provide the official platform review.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-:-KIiE5xuWylS78WtCV_7:-584917638)*

**Comment by jwnimmer-tri** [comment]
This PR is lucky!  Drake hasn't documented yet that we must follow pep-8 rules (now filed as #2465), so I won't defect any of the python style problems.

:lgtm:

This PR still needs feature review, which is assigned to @amcastro-tri.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Looks decent in a 60-second read through.  I will wait for feature review to finish before diving in any deeper, though.
</details>


---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/swig/rbtree.i, line 58 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KIju-DHABHgPkihOPO-:-KIju-DHABHgPkihOPO0:-741225169) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/swig/rbtree.i#L58)):*
> ```
> %include "drake/systems/plants/RigidBody.h"
> 
> %include "drake/systems/plants/RigidBodyFrame.h"
> ```

BTW It is slightly sad to expose the RBFrame's public fields into the python API  -- C++ rules say the fields must not be public, so eventually we are going to have to make them private and add getters -- but I guess it shouldn't be too hard to keep the python-side API stable in this PR's spelling (e.g., `my_frame.frame_index`) using carefully-named new C++ getters, and/or SWIG's method renaming via additional `%.i` file details.

(N.B. By starting this comment with "BTW", I've indicated to reviewable (and the author) no further action is required.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-:-KIjtdx1zK6iiJfixrGR:496841266)*

**Comment by amcastro-tri** [comment]
Sorry for the delay. My 2 cents on this.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This PR is lucky!  Drake hasn't documented yet that we must follow pep-8 rules (now filed as #2465), so I won't defect any of the python style problems.
> 
> :lgtm:
> 
> This PR still needs feature review, which is assigned to @amcastro-tri.
</details>


---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 9 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1DJC_lb6SSBxvZs9U:-KJ1DJC_lb6SSBxvZs9V:1958649130) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L9)):*
> ```Python
> robot = pydrake.rbtree.RigidBodyTree(os.path.join(pydrake.getDrakePath(), "examples/PR2/pr2.urdf"))
> 
> # Add a convenient frame, positioned 0.1m away from the r_gripper_palm_link along that link's x axis
> ```

Even though this is python and not c++ I would still indent this to have 80 characters long since it still is code. 

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 18 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1F5gMBRmjn4OddDYj:-KJ1F5gMBRmjn4OddDYk:2098769429) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L18)):*
> ```Python
> base_body_id = robot.findLink('base_footprint').body_index
> 
> constraints = [
> ```

I am not familiar with this module but, if the robot is let free to move in the x-y plane, doesn't that mean that this problem has multiple solutions? is the robot then going to move forward or to extend it's gripper or both? wouldn't we like to make a test to have a unique solution?

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 26 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1CBhahhpTq8Lv8J7K:-KJ1CBhahhpTq8Lv8J7L:-1591800215) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L26)):*
> ```Python
>                # We don't care about the x or y position of the robot's base,
>                # so we use NaN values to tell the IK solver not to apply a
>                # constraint along those dimensions.
> ```

I would explain here that using `NaN`'s is equivalent to having a lower bound of minus infinity and an upper bound of plus infinity which tells the IK solver not to apply a constraint along these directions. 

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 28 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1AynqJUsiaE-444Sq:-KJ1AynqJUsiaE-444Sr:-1038710715) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L28)):*
> ```Python
>                # constraint along those dimensions.
>                ik.WorldPositionConstraint(robot, base_body_id,
>                                           np.zeros((3,)),
> ```

suggestion. Why not o use `np.array([0.0, 0.0 , 0.0])` so that the same style is used for all arguments?

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 32 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1BD0EYNLHWKwbPlzL:-KJ1BD0EYNLHWKwbPlzM:-591097862) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L32)):*
> ```Python
>                                           np.array([np.nan, np.nan, 0])),
>                ik.WorldPositionConstraint(robot, base_body_id,
>                                           np.array([1., 0, 0]),
> ```

You are using `1.` (with a period) for the "one" but for the "zeros" you don't put a period at the end. If they are all floating point numbers I suggest writing `1.0`, `0.0` for all of them to keep consistency. That helps to quickly identify floating points from integers to anybody new to this code and also it indents more nicely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-:-KJ1FpTCSxiNmKBTRo33:1572815231)*

**Comment by rdeits** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 18 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1F5gMBRmjn4OddDYj:-KJ1SP9YoW3AyzPnqdd3:-148461113) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L18)):*
> to
The xyz pose of the gripper is fully constrained, and we have a nominal posture which is used to regularize the solution. Since this is just a demonstration of the API, I don't really think we need to more aggressively constrain the solution. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311)*

**Comment by jwnimmer-tri** [comment]
Still :lgtm:.  Need @amcastro-tri to acknowledge the fixes.

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Sorry for the delay. My 2 cents on this.
</details>


---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-:-KJ3MfIT-L4vLNRFtqGi:-1082430140)*

**Comment by amcastro-tri** [comment]
:lgtm: now. Thank you @rdeits! 

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Still :lgtm:.  Need @amcastro-tri to acknowledge the fixes.
</details>


---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 9 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1DJC_lb6SSBxvZs9U:-KJ6gfLJL6Lgxp14bQiO:160383625) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L9)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Even though this is python and not c++ I would still indent this to have 80 characters long since it still is code. 
</details>
OK

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 18 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1F5gMBRmjn4OddDYj:-KJ6gk8rEZVGPHVHRPn1:1208692831) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L18)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary>
> > to
> The xyz pose of the gripper is fully constrained, and we have a nominal posture which is used to regularize the solution. Since this is just a demonstration of the API, I don't really think we need to more aggressively constrain the solution. 
</details>
OK. But then the solution will depend on the particular solver/library being used.  I will resolve it since this test is only meant to show the use of this capability. 

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 26 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1CBhahhpTq8Lv8J7K:-KJ6hA4oGNkB_LVd8wwg:5173665) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L26)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I would explain here that using `NaN`'s is equivalent to having a lower bound of minus infinity and an upper bound of plus infinity which tells the IK solver not to apply a constraint along these directions. 
</details>
OK

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 28 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1AynqJUsiaE-444Sq:-KJ6hCFzs1aZ_ZKXGQtp:5173665) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L28)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> suggestion. Why not o use `np.array([0.0, 0.0 , 0.0])` so that the same style is used for all arguments?
</details>
OK

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 32 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-KJ1BD0EYNLHWKwbPlzL:-KJ6hFPR5neHAcALB4u5:5173665) ([raw file](https://github.com/robotlocomotion/drake/blob/b2d3cccdf675f0c211402174ce4fc4c67da79477/drake/bindings/python/pydrake/test/testPR2IK.py#L32)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> You are using `1.` (with a period) for the "one" but for the "zeros" you don't put a period at the end. If they are all floating point numbers I suggest writing `1.0`, `0.0` for all of them to keep consistency. That helps to quickly identify floating points from integers to anybody new to this code and also it indents more nicely.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2311#-:-KJ6hI1RUiYFIDmK9BGu:-462506172)*

**Comment by jwnimmer-tri** [comment]
All green.  Merging now.

**Pull request merged**
