### PR TITLE
[lcm] Add SubscribeMultichannel

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #18774.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18826)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please -- at least insofar as testing that the point cloud feature can use this OK.  If you'd like someone else to do the actual code review, just let me know.

**Comment by zachfang** [comment]
Thanks for the quick turnaround time. Reviewing it now.

**Review by zachfang — COMMENTED** [review]
:lgtm: !

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18826#-:-NOkOMKN9qiWcbxHzTjc:b593w5u)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`lcm/drake_lcm.cc` line 309 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18826#-NOkKV_6156rGITq54hu:-NOkKV_6156rGITq54hv:b-92dolj) ([raw file](https://github.com/RobotLocomotion/drake/blob/3408ba12b8adb457de201bd51184c9890cb7613a/lcm/drake_lcm.cc#L309)):*
> ```cpp
>   return result;
> 
>   DRAKE_DEMAND(false);
> ```

nit. I think this was for development/debugging.



_Code quote:_
```cpp
  DRAKE_DEMAND(false);
  return nullptr;
```
___
*[`bindings/pydrake/lcm_py.cc` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18826#-NOkMglT0cSW-VkqfU4s:-NOkMglT0cSW-VkqfU4t:bzht8t) ([raw file](https://github.com/RobotLocomotion/drake/blob/7b588cca335e5536746766aa64ec19eda906e78b/bindings/pydrake/lcm_py.cc#L85)):*
> ```cpp
>             },
>             py::arg("channel"), py::arg("handler"), cls_doc.Subscribe.doc);
>     // TODO(eric.cousineau): Add remaining methods.
> ```

nit. Maybe we can also remove this TODO.



_Code quote:_
```cpp
// TODO(eric.cousineau): Add remaining methods.
```

**Review by zachfang — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18826)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by zachfang — COMMENTED** [review]
+@SeanCurtis-TRI for platform review (hope it's not too late). The change is from a need to subscribe to a group of channels with a prefix, e.g., `DRAKE_POINT_CLOUD_.*`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18826#-:-NOkXW7b7JbhXNKuKFze:bpodxuh)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18826)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`lcm/drake_lcm.cc` line 291 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18826#-NOkOXQVDqy6TZR5Ux6G:-NOkOXQW8YFlVv-MM8if:b-ap6kgl) ([raw file](https://github.com/RobotLocomotion/drake/blob/3408ba12b8adb457de201bd51184c9890cb7613a/lcm/drake_lcm.cc#L291)):*
> ```cpp
>         handler(channel, data, length);
>       } else {
>         drake::log()->debug(
> ```

Working

I think this might be dead code now.  I will check.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18826)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @zachfang)

___
*[`lcm/drake_lcm.cc` line 291 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18826#-NOkOXQVDqy6TZR5Ux6G:-NOkio4Z8Tj-j2VPwJr8:b-h0pwbz) ([raw file](https://github.com/RobotLocomotion/drake/blob/3408ba12b8adb457de201bd51184c9890cb7613a/lcm/drake_lcm.cc#L291)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I think this might be dead code now.  I will check.
</blockquote></details>

Done (with bugfix).

**Review by zachfang — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18826)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[`lcm/drake_lcm.cc` line 109 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18826#-NOkxXaC67lhn9KhNMd9:-NOkxXaC67lhn9KhNMdA:bfb4tvw) ([raw file](https://github.com/RobotLocomotion/drake/blob/34e79ec46745dbf3e1a0efe827179f0be9b3b723/lcm/drake_lcm.cc#L109)):*
> ```cpp
> namespace {
> 
> // Given a literal string, escape it to be safe to use in a lcm channel regex.
> ```

BTW. Should this be `an lcm`?



_Suggestion:_
```cpp
an lcm
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@SeanCurtis-TRI I've run out of time. But +@sherm1 said he'd field this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18826#-:-NOl71HK95yhgElezONf:b-xllddc)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri, @sherm1, and @zachfang)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending all-green CI.

> Reviewed 7 of 10 files at r1, 2 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18826#-:-NOlDoBd1RtdeS2Cx0gW:b6o8t0q)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),zachfang (waiting on @jwnimmer-tri)

**Comment by zachfang** [comment]
CC\ @EricCousineau-TRI for visibility as we briefly discussed this last week.

**Pull request merged**
