### PR TITLE
pydrake: In pydrake.all, prefer pydrake.math over pydrake.symbolic

### LINKED ISSUE #15038: pydrake: math overloads provide inconsistent user experience
Consider the following example:
```
from pydrake.all import AutoDiffXd, Variable

x = 1
y = AutoDiffXd(1, [1, 0])
z = Variable('z')
```

Here's a simple basic use case, which does work fine. 
```
import pydrake.math

print(pydrake.math.sin(x))
print(pydrake.math.sin(y))
print(pydrake.math.sin(z))
```
returns 
```
0.8414709848078965
AD{0.8414709848078965, nderiv=2}
sin(z)
```

But there are some nearby patterns that lay a trap for users:
```
import numpy as np

print(np.sin(x))
print(np.sin(y))
print(np.sin(z))
```
gives 
```
0.8414709848078965
AD{0.8414709848078965, nderiv=2}
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'pydrake.symbolic.Variable' object has no attribute 'sin'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-206-4a0ca175cc23> in <module>
      1 print(np.sin(x))
      2 print(np.sin(y))
----> 3 print(np.sin(z))

TypeError: loop of ufunc does not support argument 0 of type pydrake.symbolic.Variable which has no callable sin method
```
Q: Can we teach `Expression` to understand the numpy version?

Here is another one:
```
from pydrake.all import sin

print(sin(x))
print(sin(y))
print(sin(z))
```
gives 
```
0.8414709848078965
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-207-74707ae6920c> in <module>
      1 print(sin(x))
----> 2 print(sin(y))
      3 print(sin(z))

TypeError: sin(): incompatible function arguments. The following argument types are supported:
    1. (arg0: pydrake.symbolic.Expression) -> pydrake.symbolic.Expression

Invoked with: <AutoDiffXd 1.0 nderiv=2>
```
Q: Can we move the `math` import in [all.py](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/all.py#L33) below the `symbolic` import, so the symbolic version doesn't clobber the more general one?  
(I know that we're in the land of perhaps ill-advised `pydrake.all`ness, but I believe that should be better for non-expert users).  

cc @EricCousineau-TRI .  @soonho-tri -- might you be willing to take a look?

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #15038.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15052)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for feature review, please.

**Review by soonho-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15052#-:-M_tvdJbEqu7wxX1Y46c:bg7igkv)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by soonho-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15052#-:-M_tvnrH9Iq4VlDrQRgt:b-6cxuoj)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15052#-:-M_uTuK53cdyQ5PvoE3B:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
