### PR TITLE
Implement a pybind11 type_caster for drake::EigenPtr

### PR DESCRIPTION
**Pull request by alesgenova**
Fixes: #10769

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625)

### CODE REVIEW

**Comment by alesgenova** [comment]
+@jwnimmer-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
The changes to the existing bindings look good.  I'll come back later on to review the caster implementation itself.

> Reviewed 8 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625#-:-MwbjnkH279ijgZR4w9I:box4uj1)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI as a subject-matter expert you should review this as well, and since you're on call today let's add you for platform review now (even though I haven't finished feature review quite yet).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova, @EricCousineau-TRI, and @jwnimmer-tri)

___
*[bindings/pydrake/common/BUILD.bazel, line 587 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwgtD5N5m5JkZAxFxuk:-MwgtD5N5m5JkZAxFxul:bw7nb7b) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/BUILD.bazel#L587)):*
> ```Starlark
>     deps = [
>         ":eigen_pybind_test_util_py",
>         "//bindings/pydrake/common/test_utilities",
> ```

nit I think the `common/test_utilities` dependency is unused (and thus, should be removed)?
___
*[bindings/pydrake/common/test/eigen_pybind_test_util_py.cc, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwgtSUG0cy4UAyORsTv:-MwgtSUG0cy4UAyORsTw:b5uu5ew) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/test/eigen_pybind_test_util_py.cc#L7)):*
> ```cpp
> 
> PYBIND11_MODULE(eigen_pybind_test_util, m) {
>   m.doc() = "Bindings for Eigen types.";
> ```

nit This doesn't seem accurate.



_Suggestion:_
```cpp
"Example bindings that use drake::EigenPtr types, for testing."
```
___
*[bindings/pydrake/common/test/eigen_pybind_test_util_py.cc, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-Mwgtsxy3H_drpmd26Fn:-Mwgtsxy3H_drpmd26Fo:bvzfsgh) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/test/eigen_pybind_test_util_py.cc#L21)):*
> ```cpp
>     }
> 
>     return mat;
> ```

I think the most common case in bindings that have `EigenPtr` as as parameter is they do _not_ to return anything, or at least they not to return the matrix.  I'd like to see at at least one example function here that does not return `EigenPtr`, to prove that the common-case works.

One easy way to do that would be to change this function to return void, though adding a new function that's void-valued is also fine.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova and @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks great on first pass - PTAL! Some comments in addition to feature review

> Reviewed 7 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625#-:-MwgwfkK4_-Rx0CW6uDj:b-gf7jhh)* status: 6 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova)

___
*[bindings/pydrake/common/eigen_pybind.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwguYmt7AYdS941YdIo:-MwguYmu4lND1lvwPBsm:bsx1dzs) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/eigen_pybind.h#L82)):*
> ```objc
> more details on custom type casters.
> */
> template <typename T>
> ```

nit For consistency, we tend to define main code in `drake::pydrake::internal`, and then alias into`pybind11::detail`

For example:
https://github.com/RobotLocomotion/drake/blob/c95ac12807375c61d9426802570a9fc635e377c1/bindings/pydrake/common/cpp_param_pybind.h#L152-L155

I believe the macro mixin should still work.
___
*[bindings/pydrake/common/eigen_pybind.h, line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwgvBD5-FYtbiv5f4AZ:-MwgvBD5-FYtbiv5f4A_:b-cqyag8) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/eigen_pybind.h#L89)):*
> ```objc
> 
>  public:
>   PYBIND11_TYPE_CASTER(PtrType, InnerCaster::name + _(" | None"));
> ```

nit For consistency, I believe this should be `Optional[T]`

e.g., pybind11's `std::optional<>` caster uses it, which is closer to builtin `typing` formatting:
https://github.com/pybind/pybind11/blob/da15bb206c21be7180bd428e4e69907756eb70dc/include/pybind11/stl.h#L317
https://docs.python.org/3.6/library/typing.html#typing.Optional

I do see that `| None` is permissible for later versions of Python:
https://docs.python.org/3/library/typing.html#typing.Optional
However, I would recommend sticking closer to pybind11, so "outfix" vs. infix.
___
*[bindings/pydrake/common/test/eigen_pybind_test_util_py.cc, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwgwPF-AbfYmiQ4KkeE:-MwgwPF-AbfYmiQ4KkeF:b-g685qn) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/test/eigen_pybind_test_util_py.cc#L16)):*
> ```cpp
>   m.def("scale_matrix_ptr", [](drake::EigenPtr<MatrixX<T>> mat, T factor) {
>     if (mat != nullptr) {
>       for (auto it = mat->data(); it != mat->data() + mat->size(); ++it) {
> ```

nit I recommend using Eigen's affordances for this math which can shorten code:
```
*mat *= factor
```

**Comment by alesgenova** [comment]
___
*[bindings/pydrake/common/eigen_pybind.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwguYmt7AYdS941YdIo:-MwhwGH34Tk_h0KKSy4Z:b-cb0zbr) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/eigen_pybind.h#L82)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For consistency, we tend to define main code in `drake::pydrake::internal`, and then alias into`pybind11::detail`

For example:
https://github.com/RobotLocomotion/drake/blob/c95ac12807375c61d9426802570a9fc635e377c1/bindings/pydrake/common/cpp_param_pybind.h#L152-L155

I believe the macro mixin should still work.
</blockquote></details>

I refactored it so that most of the logic is in `drake::pydrake::internal` and then a minimal `pype_caster` is declared in `pybind11::detail`.
Let me know if the way I implemented is similar to what you had in mind.

**Comment by alesgenova** [comment]
___
*[bindings/pydrake/common/test/eigen_pybind_test_util_py.cc, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-Mwgtsxy3H_drpmd26Fn:-Mwhwu5o8y3K9YzvIaLx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/test/eigen_pybind_test_util_py.cc#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the most common case in bindings that have `EigenPtr` as as parameter is they do _not_ to return anything, or at least they not to return the matrix.  I'd like to see at at least one example function here that does not return `EigenPtr`, to prove that the common-case works.

One easy way to do that would be to change this function to return void, though adding a new function that's void-valued is also fine.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova, @EricCousineau-TRI, and @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova)

___
*[bindings/pydrake/common/eigen_pybind.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwguYmt7AYdS941YdIo:-MwhwkIj-yZ5lJpVn6zV:bpen8ox) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/eigen_pybind.h#L82)):*
<details><summary><i>Previously, alesgenova (Alessandro Genova) wrote…</i></summary><blockquote>

I refactored it so that most of the logic is in `drake::pydrake::internal` and then a minimal `pype_caster` is declared in `pybind11::detail`.
Let me know if the way I implemented is similar to what you had in mind.
</blockquote></details>

Ah, I see `PYINBD11_TYPE_CASTER` does not use qualified symbols, so it won't work:
https://github.com/pybind/pybind11/blob/da15bb206c21be7180bd428e4e69907756eb70dc/include/pybind11/cast.h#L82-L103

I've filed upstream PR: https://github.com/pybind/pybind11/pull/3758

Can you add TODO to fully consolidate? e.g.
```
TODO(eric.cousineau): Place all logic inside of `drake` namespace once our fork includes macro w/ fully qualified symbols.
```

**Comment by alesgenova** [comment]
___
*[bindings/pydrake/common/eigen_pybind.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwguYmt7AYdS941YdIo:-Mwi0MQCA5lVhITwAjOi:bd9098p) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/eigen_pybind.h#L82)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, I see `PYINBD11_TYPE_CASTER` does not use qualified symbols, so it won't work:
https://github.com/pybind/pybind11/blob/da15bb206c21be7180bd428e4e69907756eb70dc/include/pybind11/cast.h#L82-L103

I've filed upstream PR: https://github.com/pybind/pybind11/pull/3758

Can you add TODO to fully consolidate? e.g.
```
TODO(eric.cousineau): Place all logic inside of `drake` namespace once our fork includes macro w/ fully qualified symbols.
```
</blockquote></details>

Ok, I'll add the todo and a refence to that upstream PR.

In the meantime, do you want to keep the current split with a `Wrapper` and the actual `type_caster` separate, or do you want me to revert back to having it all together like it was originally? The latter would probably make it easier to just copy paste the code block in the pydrake namespace once the upstream PR is accepted.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625)* status: LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova)

___
*[bindings/pydrake/common/eigen_pybind.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwguYmt7AYdS941YdIo:-MwiDuzHARArFfbsgmQ5:bbb48cn) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/eigen_pybind.h#L82)):*
<details><summary><i>Previously, alesgenova (Alessandro Genova) wrote…</i></summary><blockquote>

Ok, I'll add the todo and a refence to that upstream PR.

In the meantime, do you want to keep the current split with a `Wrapper` and the actual `type_caster` separate, or do you want me to revert back to having it all together like it was originally? The latter would probably make it easier to just copy paste the code block in the pydrake namespace once the upstream PR is accepted.
</blockquote></details>

No strong opinions given current state of affairs - I'm fine with whatever is less work for you at the moment!
Feel free to revert what you had at r1, or keep this as is at r2 (but w/ TODO as you mentioned).

**Comment by alesgenova** [comment]
___
*[bindings/pydrake/common/eigen_pybind.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwguYmt7AYdS941YdIo:-MwlafA66jbuutNEeV1n:boplnhm) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/eigen_pybind.h#L82)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

No strong opinions given current state of affairs - I'm fine with whatever is less work for you at the moment!
Feel free to revert what you had at r1, or keep this as is at r2 (but w/ TODO as you mentioned).
</blockquote></details>

Done, I have added the TODO comment, and reverted the type_caster code to how it was in r1 (I think it was easier to read).

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625#-:-MwlbZAx-cEvT6DyZ3t6:bg7igk9)* status: LGTM missing from assignee EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625#-:-MwlcEogDCkbwA8J04uV:bcpz082)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova)

___
*[bindings/pydrake/common/eigen_pybind.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwguYmt7AYdS941YdIo:-MwlcARk81kcBSdllpBm:b56uezr) ([raw file](https://github.com/robotlocomotion/drake/blob/3eddcb4180ca864f9872266a8ff0bea1dddb94d4/bindings/pydrake/common/eigen_pybind.h#L82)):*
<details><summary><i>Previously, alesgenova (Alessandro Genova) wrote…</i></summary><blockquote>

Done, I have added the TODO comment, and reverted the type_caster code to how it was in r1 (I think it was easier to read).
</blockquote></details>

OK Sounds good!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625)* status: 1 unresolved discussion, when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwlbvTv1059XiNe0zS1:-MwlbvTv1059XiNe0zS2:bvpospo) (no related file):*
Oops, I missed one thing:

Now that this is "status: commits are properly curated" (which means that we're going to keep your commit messages intact when merging), we need to drop the "Signed-off-by" in the message body.  We don't use that convention in Drake.

If we were squashing this, the platform reviewer could just edit it out during merge, but with "curated" we'll need a force-push to adjust the message.

---

**Comment by alesgenova** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16625#-MwlbvTv1059XiNe0zS1:-Mwlej2k9JMnEWAVjIM8:b-iw1ipt) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, I missed one thing:

Now that this is "status: commits are properly curated" (which means that we're going to keep your commit messages intact when merging), we need to drop the "Signed-off-by" in the message body.  We don't use that convention in Drake.

If we were squashing this, the platform reviewer could just edit it out during merge, but with "curated" we'll need a force-push to adjust the message.
</blockquote></details>

Good to know, I have fixed the commit messages

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @alesgenova)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16625)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), base commit is latest master (waiting on @alesgenova)

**Comment by alesgenova** [comment]
> The other thing with "curated" is that it needs to be rebased onto the top of master and force-pushed, before we can merge it.

Oh I see. I rebased it on current master

**Comment by jwnimmer-tri** [comment]
Looks great.  This will be ready to merge once Jenkins finishes its testing.

**Pull request merged**
