### PR TITLE
MathematicalProgram tutorial

### PR DESCRIPTION
**Pull request by hongkai-dai**
@mitiguy and I created this jupyter notebook on MathematicalProgram. Currently this notebook is hosted in my google drive https://drive.google.com/file/d/1EwX03N1XIemz05Ozy8x_hzNGtMT_xR57/view?usp=sharing. We should host this jupyter notebook elsewhere.

Questions:
1. How shall we review the jupyter notebook? On reviewable, we cannot render the jupyter notebook.
2. In this jupyter notebook tutorial, I add links to other tutorials. Let's say tutorial1 -> tutorial2, and the link currently is a google drive URL. That link would be broken, once we host the jupyter notebook not on my google drive. And if the user downloads drake, and run the jupyter notebook locally (instead of through colab), the google drive link won't point the user to the tutorial2 file downloaded locally, but to a URL on the google drive.

Requires:
- [x] #11960 Bazel Jupyter stuff

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11694)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I think we have a failure to communicate here.  Or at least, I am very surprised with the platform review assignment, because I don't think this PR is anywhere near ready for master.

Code that's in Drake master should be able to maintained by most or all Drake Developers, and should be (more or less) tested by CI.  I don't think a single ipynb file on its own meets either of these two criteria.  At worst, it needs developer documentation explaining how to (locally) run and test it.  Really though, I think #9650 should be a prerequisite for landing any ipynb files in Drake.

**Comment by jwnimmer-tri** [comment]
> Since python-jupyter only exists in Bionic, not in Xenial,  ...

Since Drake will be removing support for Xenial later this year, I think having the notebook and/or notebook documentation only support Bionic is fine.

> Do we have a standard on which python version to use?

Since Drake will be removing support for Python 2 later this year, I think having the tutorial in Python 3 is perfect.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Maybe we should consider deferring the `doc/index.rst` changes to a future PR, until we have a chance to test them?  It seems to me like we can't test it currently since they refer to the tutorial on master.

> In this jupyter notebook tutorial, I add links to other tutorials. Let's say tutorial1 -> tutorial2, and the link currently is a google drive URL. That link would be broken, once we host the jupyter notebook not on my google drive. And if the user downloads drake, and run the jupyter notebook locally (instead of through colab), the google drive link won't point the user to the tutorial2 file downloaded locally, but to a URL on the google drive.

Maybe just leave a TODO for now, if the intra-tutorial links are still not working?

**Pull request merged**
