### PR TITLE
First round of name changes for caching implementation

### LINKED ISSUE #4400: Systems implement EvalTimeDerivatives but DoEvalDifferenceUpdates and DoPublish
... because e.g. there is a little bit of wrapper logic in EvalDifferenceUpdates in System.

Can we make the naming more consistent at the (Leaf)System implementation level?  I would prefer, e.g., for systems to implement EvalDifferenceUpdates, and to change EvalDifferenceUpdates at the System level to something more like EvalDifferenceUpdatesWrapper.

pinging @david-german-tri , @sherm1 for their thoughts.

### PR DESCRIPTION
**Pull request by sherm1**
Renames methods to consistently use the Eval/Calc/DoCalc naming scheme for cacheable computations. This is intended to be a no-op change needed as a first step to making the Eval methods use the cache, [like this](https://github.com/RobotLocomotion/drake/issues/3155#issuecomment-240258256). For where this is headed see #4364. Fixes #4400.

I am hoping to implement this in several easy(ish)-to-review passes. To that end this pass is not intended as the final destination for many of the changes it includes. This provides consistent naming so that a later pass can make substantive changes without having them lost in a renaming tsunami. Included:
- Renamed the existing `Eval` methods to `Calc` since they write to output arguments. A later pass will go back and replace those `Calc` uses with cache-aware `Eval`s where appropriate, returning cache references instead.
- `CalcX()` methods now uniformly use an NVI pattern and invoke virtual `DoCalcX()`  methods after argument validation.
- Removed the sporadic argument validation that some diligent authors had added to their overrides since they are no longer needed.
- Rearranged and doxygen "member grouped" related methods together in `system.h`, with group documentation added. That looks like a lot changed in Reviewable but it is entirely shuffling.
- Made `set_name()/get_name()` non-virtual and removed the two places where they were being overridden (per discussion with @liangfok).

This required a lot of small, repetitive name changes distributed over many files. The only large changes appear in `system.h` due to the renaming and rearrangement. The easiest way to see what happened there (I think) is to generate the doxygen and look at the System class.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4520)

### CODE REVIEW

**Comment by sherm1** [comment]
This is ready for review now. +@david-german-tri for feature and platform, please.

---

Review status: 0 of 133 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-:-KZ9DcD879MyK2FFojYV:b-h0vppq)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

:lgtm: aside from a few small comments

---

Reviewed 133 of 133 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/system.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNngDz1wh_xMFPcIBW:-KZNngDz1wh_xMFPcIBX:b-vzy5nv) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L22)):*
> ```objc
> 
> /// A description of a discrete-time event, which is passed from the Simulator
> /// to the recipient System's appropriate event handler method.
> ```

BTW good catch, thanks

---

*[drake/systems/framework/system.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNqJYp94y9fbzocEew:-KZNqJYp94y9fbzocEex:b-yujwqh) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L208)):*
> ```objc
>   const T& EvalPotentialEnergy(const Context<T>& context) const {
>     // TODO(sherm1) Replace with an actual cache entry.
>     static T fake_cache_entry;
> ```

BTW (here and below) I find it vaguely odd that the `fake_cache_entry` is `static`, but I guess it doesn't really matter.

---

*[drake/systems/framework/system.h, line 442 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNrQlx3b_5njeubt-h:-KZNrQlzJKUQudJgYxBY:bsqjgj1) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L442)):*
> ```objc
>   /// to generalized velocities `v`. `v` and `qdot` are related linearly by
>   /// `qdot = N(q) * v`, where `N` is a block diagonal matrix with a block for
>   /// each tree joint. Although `N` is not necessarily square,
> ```

This seems overly specific for `system.h`.

---

*[drake/systems/framework/system.h, line 478 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNrYHt-vZm4NV4mK4c:-KZNrYHt-vZm4NV4mK4d:b-y4tnpl) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L478)):*
> ```objc
>   void set_name(const std::string& name) { name_ = name; }
> 
>   /// Retrieve the name last supplied to set_name().
> ```

BTW retrieves

---

*[drake/systems/framework/system.h, line 746 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNsTC9amM-H0xrX_Dw:-KZNsTC9amM-H0xrX_Dx:b-birf3w) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L746)):*
> ```objc
>   /// produced by AllocateTimeDerivatives().
>   ///
>   /// The default implementation does nothing if the `derivatives` vector is,
> ```

nit: stray comma

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-:-KZNum9fRncD8zA21amb:bbhzh1t)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/system.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNqJYp94y9fbzocEew:-KZNvdfifYGiNxaZGkiN:b-s1nsc8) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L208)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW (here and below) I find it vaguely odd that the `fake_cache_entry` is `static`, but I guess it doesn't really matter.
</blockquote></details>

@jwnimmer-tri points out this is actually a style guide violation, because `T` is not POD: https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4520)*

**Comment by sherm1** [comment]
Review fixes & response plus some more comment tweaks -- PTAL, @david-german-tri.

---

Review status: 132 of 133 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/system.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNqJYp94y9fbzocEew:-KZP0JjiGwWFqqTQkJyH:bwyifcz) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L208)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

@jwnimmer-tri points out this is actually a style guide violation, because `T` is not POD: https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables
</blockquote></details>

I agree. I won't leave it like this but want to include a few examples of the intended API to act as placeholders for the now-missing Eval methods. They help with the Doxygen layout and telegraph the coming changes for those who may wonder what's up. I can fake these scalar quantities temporarily using statics to provide a referenceable address until I can supply one from the cache a few PRs from now. These methods are functional for the current instantiations and are only being used in one unit test anyway at the moment. I hope you'll deem the TODOs here adequate for the short term.

---

*[drake/systems/framework/system.h, line 442 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNrQlx3b_5njeubt-h:-KZPcej7D17vouNeR3u1:bkj72rz) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L442)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This seems overly specific for `system.h`.
</blockquote></details>

Done. Agreed. I switched that to an example and added some more text.

---

*[drake/systems/framework/system.h, line 478 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNrYHt-vZm4NV4mK4c:-KZPdtFl25A6RFiPEx9w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L478)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW retrieves
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 746 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNsTC9amM-H0xrX_Dw:-KZPduJ8gsgNld5Pk0Ul:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L746)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

nit: stray comma
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-:-KZPg8mi45SGn8RuNuhN:b-706fno)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 4 files at r2.
Review status: 131 of 134 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNqJYp94y9fbzocEew:-KZS5YFnZGPpoiTJgsIu:b-7vy51u) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L208)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I agree. I won't leave it like this but want to include a few examples of the intended API to act as placeholders for the now-missing Eval methods. They help with the Doxygen layout and telegraph the coming changes for those who may wonder what's up. I can fake these scalar quantities temporarily using statics to provide a referenceable address until I can supply one from the cache a few PRs from now. These methods are functional for the current instantiations and are only being used in one unit test anyway at the moment. I hope you'll deem the TODOs here adequate for the short term.
</blockquote></details>

OK, I'm willing to live with it, but you could just have class members instead, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4520)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/system.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNqJYp94y9fbzocEew:-KZS8k1zjbWU3BJuqDpo:bcyykbp) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L208)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

OK, I'm willing to live with it, but you could just have class members instead, no?
</blockquote></details>

Or just leak it, which is what we usually do when we want static initialization but no destruction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4520)*

**Comment by david-german-tri** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4520)*

**Comment by sherm1** [comment]
Review status: 133 of 135 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4520#-KZNqJYp94y9fbzocEew:-KZUZ4yKPhknmjSVu6Xt:b9dyuhn) ([raw file](https://github.com/robotlocomotion/drake/blob/95710159249a8dafb7fc6cd10b4af52417ba64ac/drake/systems/framework/system.h#L208)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Or just leak it, which is what we usually do when we want static initialization but no destruction.
</blockquote></details>

Done. Switched to mutable class members as a temporary fake cache for these four methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4520)*

**Pull request merged**
