### PR TITLE
Revert "[py systems] Allow scalar conversion for subclassed diagrams …

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
…(#18813)"

This reverts commit 917dcfa98af3306729ae8f7e49d04953be23d1ed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18832)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18832)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18832#-NOlOODMDwj8pZdkx6Iz:-NOlOODN8bNmtJOVuUn7:b6gntrf) (no related file):*
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please.

___

**Comment by xuchenhan-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please.

**Review by xuchenhan-tri — COMMENTED** [review]
+@EricCousineau-TRI in case you need it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18832#-:-NOlQUS90qQEr9a5PhIE:b7r3jrc)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Thanks! Looks like Jeremy's #18833 should be set to land.

**Comment by jwnimmer-tri** [comment]
:lgtm: stamp.

We're not 100% convinced about the fix-forward, so we'll revert for now.

**Pull request merged**
