### PR TITLE
DAE solver and bead on a wire example

### PR DESCRIPTION
**Pull request by edrumwri**
This PR adds the following capabilities:

* Modifies the System framework class to enable evaluating algebraic constraint functions (to permit solutions of DAEs using approaches other than "ODE on a manifold").
* Adds a first-order, index 3 DAE solver.
* Adds the example of a bead on a wire (with support for a large class of parametric wire functions) to test the DAE solution capabilities.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5028)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review please (I don't think anyone else is equipped to do the feature review) and +@ggould-tri for platform review per normal rotation

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5028#-:-Kcb6w-EdM9M82llQZuz:b6yuhpq)*

**Comment by edrumwri** [comment]
(I just realized that this is well over the standard 500 line limit for PR's- but it really isn't feasible to make it smaller). 

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5028#-:-Kcb7I_2T7NiX5uNXUms:b-dqa8h3)*

**Comment by ggould-tri** [comment]
For future reference, the obvious way to break this PR into smaller pieces would be to PR the new solver and the new example separately.

Because of the size of this PR, I expect that I will be spreading review over several days to keep my eyes fresh.  I will add comments as I go, but don't expect to see the whole lot until Tuesday or so.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5028#-:-KccNxUOEepAl7QLf6Z6:b-8pxzp4)*

**Comment by edrumwri** [comment]
The "obvious way" won't work, I'm afraid. The bead on the wire needs the half-explicit DAE solver to compute one of the solutions, and there is no existing system that exercises the new functionality of the half-explicit solver. PR'ing the bead on the wire using only the other solution would be one possibility, but there would be no way to evaluate the correctness of the dynamics. 

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5028#-:-KccYknmA3tGFm1_xF9W:b-myx9yh)*

**Comment by jwnimmer-tri** [comment]
PRing the solver with unit tests but with no application example would be perfectly fine, and preferable to this mega-PR.

**Comment by edrumwri** [comment]
Jeremy, I need an example system to do any real testing of the DAE solver- the bead on the wire is that system. Two other points I'll mention: about 40% of this PR is documentation, and I'm also ok with the review taking place over a longer period of time. 

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5028#-:-Kcd_4zWXnYrlDJCKrAa:bsv4zow)*

**Comment by jwnimmer-tri** [comment]
My apologies, I only looked too quickly.  It looks like the Bead system could go in first (since its unit test doesn't use the solve), and then the uses of it secondarily.

**Comment by edrumwri** [comment]
Sherm had a good suggestion for making this happen- closing this PR accordingly.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5028#-:-Kcdo5BGuLHx90t-IURQ:bsznk92)*

**Pull request closed without merging**
