### PR TITLE
Modify ShapeSpecificaiton reification to include user data

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Support reification process which uses user data. A necessary preliminary step to getting #7652 through.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7710)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@sherm1 for feature review

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-:-L2Mfhdp-PmPGZN0P3Px:b-f384lj)*

**Comment by sherm1** [comment]
Feature review: :lgtm: with a few BTWs.

FYI for platform reviewer: @seancurtis-tri, @edrumwri, and I discussed the alternative of using a virtual "info" interface rather than a `void*` for the arbitrary user data. For a class used only internally the need for extra boilerplate at every call seemed like overkill and a net minus in readability. Plenty of room for disagreement there.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[geometry/shape_specification.h, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2MwQAOr82U1kjfBtuJ:-L2MwQAOr82U1kjfBtuK:bj7iuug) ([raw file](https://github.com/robotlocomotion/drake/blob/9502faef66dbd526227a00f903b371e89d09746e/geometry/shape_specification.h#L156)):*
> ```objc
>  class ConcreteReifier : public ShapeReifier {
>    void ProcessShape(const Shape& shape) {
>      shape.Reify(this);
> ```

BTW should show passing the user data here, something like:
```c++
   void ProcessShape(const Shape& shape) {
    MyImportantThing thing; // ...
     shape.Reify(this, &thing);
}
```

---

*[geometry/shape_specification.h, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2MwqcNdDGZ423VQp_h:-L2MwqcNdDGZ423VQp_i:b-hlb12e) ([raw file](https://github.com/robotlocomotion/drake/blob/9502faef66dbd526227a00f903b371e89d09746e/geometry/shape_specification.h#L160)):*
> ```objc
>    ...
>    void ImplementGeometry(const Sphere& sphere, void* user_data) override {
>      // Do work to create a sphere (optionally using the provided user data.
> ```

BTW should show use of user data here, e.g.
```c++
  MyImportantThing& thing = *reinterpret_case<MyImportantThing*>(user_data);
```

---

*[geometry/test/shape_specification_test.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2MxLqn8aa8CAKo4Dqo:-L2MxLqn8aa8CAKo4Dqp:bseedad) ([raw file](https://github.com/robotlocomotion/drake/blob/9502faef66dbd526227a00f903b371e89d09746e/geometry/test/shape_specification_test.cc#L18)):*
> ```cpp
> // Confirm correct interactions with the Reifier.
> 
> class ReifierTest : public ShapeReifier, public ::testing::Test {
> ```

BTW should have a unit test that verifies that user_data makes it from reifier to shape and back to reifier correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-:-L2MxXVGTbVBsaY9hL_7:b-d2p4qk)*

**Comment by SeanCurtis-TRI** [comment]
Comments addressed. +@sammy-tri for tuesday platform review, please.

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[geometry/shape_specification.h, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2MwQAOr82U1kjfBtuJ:-L2N014gyF58otyl-_Fk:b-eh3fmp) ([raw file](https://github.com/robotlocomotion/drake/blob/9502faef66dbd526227a00f903b371e89d09746e/geometry/shape_specification.h#L156)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should show passing the user data here, something like:
```c++
   void ProcessShape(const Shape& shape) {
    MyImportantThing thing; // ...
     shape.Reify(this, &thing);
}
```

</blockquote></details>

OK Docs extended

---

*[geometry/shape_specification.h, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2MwqcNdDGZ423VQp_h:-L2N0AIm1Gj2dPnu1zNm:b-rorydd) ([raw file](https://github.com/robotlocomotion/drake/blob/9502faef66dbd526227a00f903b371e89d09746e/geometry/shape_specification.h#L160)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should show use of user data here, e.g.
```c++
  MyImportantThing& thing = *reinterpret_case<MyImportantThing*>(user_data);
```
</blockquote></details>

OK docs extended

---

*[geometry/test/shape_specification_test.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2MxLqn8aa8CAKo4Dqo:-L2N0EFQC8Gg_64-sDht:b-xlrm9v) ([raw file](https://github.com/robotlocomotion/drake/blob/9502faef66dbd526227a00f903b371e89d09746e/geometry/test/shape_specification_test.cc#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should have a unit test that verifies that user_data makes it from reifier to shape and back to reifier correctly.
</blockquote></details>

OK I'd hoped you wouldn't notice.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-:-L2N16_O72yZft1uwUrq:bfgrpb)*

**Comment by sherm1** [comment]
Still :lgtm: with a few new BTWs.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[geometry/shape_specification.h, line 162 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2NAgDRZ_x8f40ovSWT:-L2NAgDRZ_x8f40ovSWU:b-jo13bh) ([raw file](https://github.com/robotlocomotion/drake/blob/ecdf269ac5a148c5bfa97f1f794a2016450a74f1/geometry/shape_specification.h#L162)):*
> ```objc
>    ...
>    void ImplementGeometry(const Sphere& sphere, void*) override {
>      // Do work to create a sphere (optionally using the provided user data.
> ```

BTW this comment seems wrong for the "simple" case -- there is no user data.

---

*[geometry/shape_specification.h, line 179 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2NAuhVV0wFhIebIAdz:-L2NAuhVV0wFhIebIAe-:b-o2aw9v) ([raw file](https://github.com/robotlocomotion/drake/blob/ecdf269ac5a148c5bfa97f1f794a2016450a74f1/geometry/shape_specification.h#L179)):*
> ```objc
>      DRAKE_ASSERT(data);
>      ImportantData& data = *reinterpret_data<ImportantData*>(data);
>      // Do work to create a sphere (optionally using the provided user data.
> ```

BTW closing paren missing. But probably you don't want to say this here since the point of the complex example was to use the user_data.

---

*[geometry/test/shape_specification_test.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2MxLqn8aa8CAKo4Dqo:-L2NB1FFrcOIrV1G6SoP:b14wdcs) ([raw file](https://github.com/robotlocomotion/drake/blob/9502faef66dbd526227a00f903b371e89d09746e/geometry/test/shape_specification_test.cc#L18)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

OK I'd hoped you wouldn't notice.  :)
</blockquote></details>

Worth a try!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-:-L2NBRQpd3Y0pozXRq1g:bb547km)*

**Comment by SeanCurtis-TRI** [comment]
Cleaned up

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[geometry/shape_specification.h, line 162 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2NAgDRZ_x8f40ovSWT:-L2QUT5rCc_Lp78k2BW0:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ecdf269ac5a148c5bfa97f1f794a2016450a74f1/geometry/shape_specification.h#L162)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this comment seems wrong for the "simple" case -- there is no user data.
</blockquote></details>

Done

---

*[geometry/shape_specification.h, line 179 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2NAuhVV0wFhIebIAdz:-L2QUTrWUtYc53hnw7XY:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ecdf269ac5a148c5bfa97f1f794a2016450a74f1/geometry/shape_specification.h#L179)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW closing paren missing. But probably you don't want to say this here since the point of the complex example was to use the user_data.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-:-L2QUVZE-x-pf8fc0NH9:b-4iduyw)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[geometry/shape_specification.h, line 178 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2Qg_wcQONlaZZd7_up:-L2Qg_wcQONlaZZd7_uq:b68y34k) ([raw file](https://github.com/robotlocomotion/drake/blob/4351107da6ab027714404e035bf87bcefbfcdda4/geometry/shape_specification.h#L178)):*
> ```objc
>    void ImplementGeometry(const Sphere& sphere, void* data) override {
>      DRAKE_ASSERT(data);
>      ImportantData& data = *reinterpret_data<ImportantData*>(data);
> ```

should this say `reinterpret_cast`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-:-L2Qh1n1vAr4UseJXD0o:bvb1a6z)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[geometry/shape_specification.h, line 178 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-L2Qg_wcQONlaZZd7_up:-L2QnB1sDKzVfKk8Bd-s:b98pj93) ([raw file](https://github.com/robotlocomotion/drake/blob/4351107da6ab027714404e035bf87bcefbfcdda4/geometry/shape_specification.h#L178)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

should this say `reinterpret_cast`?
</blockquote></details>

Done Only if you're using *traditional* C++.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7710#-:-L2R1st_dUkKkSdqiFSL:bnfp4nl)*

**Pull request merged**
