### PR TITLE
tools: Move cc macros for per_os support to common skylark

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This keeps us aligned the the pattern in #14470.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14471)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

(Already tested locally on macsim.)

**Review by jamiesnape — COMMENTED** [review]
My macOS machines feel sad there is no `drake_cc_library_macos_only`, but we don't need one. :lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14471#-:-MOlvl-y4LTdExbSVBxF:bjrrb31)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

(Tagged DNM because I'm going to wait for #14470 approval before merging this one, in case there are sync changes necessary.)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14471#-:-MOlz-ihBngh259PyD-J:bnfp4nl)* status: labeled "do not merge"

**Pull request merged**
