### PR TITLE
[py planning] Bind max clique solver

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20505)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@jwnimmer-tri for feature review? Thanks!

I believe I addressed all the points on slack save your comment about checking if that the diagonal of the adjacency matrix needing to be `0`. This is in fact not true. The max clique does not change if you allow for self-loops in the graph.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-:-Nip4omh9ToA-xmtcnet:bywow5l)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Comment by jwnimmer-tri** [comment]
> The max clique does not change if you allow for self-loops in the graph.

OK, but it seemed to me that the DRAKE_DEMAND (cross-checking the num non zeros) would abort if there were any non-zeros on the diagonal.  Maybe add a unit test case that has some non-zeros there, if it's supposed to be a valid use?  I can look more closely later today.

**Review by AlexandreAmice — COMMENTED** [review]
Good catch! Test case added

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-:-NipDDpp2y8LHvx2ePVe:b-u5hfa6)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok).

I'll mark it +(release notes: none) since the original pull already covered this new feature.

> Reviewed 2 of 6 files at r1, 6 of 9 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-:-NiqNqL23s9Tn9aSRUXp:b-5xyhlp)* status: 23 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/BUILD.bazel` line 78 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqJxMk3Z99gzLt4jAs:-NiqJxMk3Z99gzLt4jAt:b-bd2ug9) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/BUILD.bazel#L78)):*
> ```Starlark
> 
> drake_cc_googletest(
>     name = "max_clique_via_mip_test",
> ```

nit File names should be consistent throughout.



_Suggestion:_
```Starlark
max_clique_solver_via_mip_test
```
___
*[`planning/graph_algorithms/max_clique_solver_base.h` line 4 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqHg374YtIRtJ8DWaz:-NiqHg374YtIRtJ8DWb-:b-gll2qq) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_base.h#L4)):*
> ```objc
> #include <Eigen/Sparse>
> 
> #include "drake/common/drake_throw.h"
> ```

nit The "drake_throw" is not used by the header file.  (It should move to the cc file.)
___
*[`planning/graph_algorithms/max_clique_solver_base.h` line 18 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqGaYu33qkgxBOxkO7:-NiqGaYvBPKX2fMJZi6l:b9akjjs) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_base.h#L18)):*
> ```objc
> class MaxCliqueSolverBase {
>  public:
>   MaxCliqueSolverBase() = default;
> ```

nit The constructor is not sensible for users to directly call.  It should be part of the `protected:` section instead of public.
___
*[`planning/graph_algorithms/max_clique_solver_base.h` line 26 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqGpIdEdABSz9Se4HK:-NiqGpIeCmRfyvDUCY2f:b2dh48h) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_base.h#L26)):*
> ```objc
>    * each pair of vertices is connected by an edge (i.e. a fully connected
>    * subgraph). This problem is known to be NP-complete, and so the choice of
>    * solvers in @param options determines whether the return of this function is
> ```

nit The mention of `options` here is stale.
___
*[`planning/graph_algorithms/max_clique_solver_base.h` line 29 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqGw0t-UBWnZR5oVMf:-NiqGw0t-UBWnZR5oVMg:b-8v4ieh) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_base.h#L29)):*
> ```objc
>    * the true maximum clique in the subgraph (which may take very long to
>    * compute), or only an approximate solution found via heuristics.
>    * @param adjacency_matrix a symmetric (0,1)-matrix encoding the edge
> ```

nit The scalar type of of the matrix is a `bool`, so `0` and `1` are probably not the best way of explaining its values.  Also `(0,1)` reads like a `(row,col)` literal, not a set of allowed values.

Maybe "a symmetric binary matrix" or "a symmetric matrix of booleans" or something like that?
___
*[`planning/graph_algorithms/max_clique_solver_base.h` line 31 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqH8Ut4GRWC9aFDY8D:-NiqH8Ut4GRWC9aFDY8E:b2dh48h) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_base.h#L31)):*
> ```objc
>    * @param adjacency_matrix a symmetric (0,1)-matrix encoding the edge
>    * relationship.
>    * @param options options for solving the max-clique problem.
> ```

nit The mention of `options` here is stale.
___
*[`planning/graph_algorithms/max_clique_solver_base.h` line 33 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqHT8CCSqBHYq2MzX0:-NiqHT8D19JO2L212zQn:b7f1xr2) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_base.h#L33)):*
> ```objc
>    * @param options options for solving the max-clique problem.
>    * @return A binary vector with the same indexing as the adjacency matrix,
>    * with 1 indicating membership in the clique.
> ```

nit Membership is indicated by `true` not `1`.
___
*[`planning/graph_algorithms/max_clique_solver_base.h` line 38 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqHuyA9kkHpPV0R7V0:-NiqHuyA9kkHpPV0R7V1:bqv6nnm) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_base.h#L38)):*
> ```objc
>    * options.
>    */
>   VectorX<bool> SolveMaxClique(
> ```

BTW Other place in this PR we have `[[nodiscard]]` marked.  Possibly worth marking here also, for consistency?
___
*[`planning/graph_algorithms/max_clique_solver_via_mip.h` line 26 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqIHGK9IM97SWRohza:-NiqIHGL9Xr01Fr4xF6F:b-qzelzp) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.h#L26)):*
> ```objc
>  * solvers if possible (https://drake.mit.edu/bazel.html#proprietary_solvers).
>  *
>  * @throws This solver throws if no Mixed-Integer Linear Programming solver is
> ```

nit When using the `@throws` markup, the exception type is required to immediately follow, so:

```
@throws std::exception if no MILP ...
```

Possibly simpler though would just be to nix the `@throws` markup and just say the prose ("This solver throws ...").
___
*[`planning/graph_algorithms/max_clique_solver_via_mip.h` line 37 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqJWSDAusjY5jQAcJh:-NiqJWSDAusjY5jQAcJi:b-p6cpvx) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.h#L37)):*
> ```objc
>                         const solvers::SolverOptions& solver_options);
> 
>   void set_solver_options(const solvers::SolverOptions& solver_options) {
> ```

nit For all of these setters and getters, a `lower_case` name is only permitted when the operation is constant-time (https://drake.mit.edu/styleguide/cppguide.html#Function_Names).

All of these functions are copying the whole data structure, which is not constant time, so we must use SetSolverOptions, GetSolverOptions, SetInitialGuess, GetInitialGuess as the function names.
___
*[`planning/graph_algorithms/max_clique_solver_via_mip.h` line 46 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqJF4A699gN5lQ3u-L:-NiqJF4A699gN5lQ3u-M:bp6sod2) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.h#L46)):*
> ```objc
> 
>   void set_initial_guess(
>       const Eigen::Ref<const Eigen::VectorXd>& initial_guess) {
> ```

nit This function somewhat breaks the pattern of how the guess works.  Everywhere else (constructor, getter) the guess can be optional, and setting it to nullopt clears the prior guess.

Is there a reason the argument here is not `optional`?
___
*[`planning/graph_algorithms/max_clique_solver_via_mip.h` line 55 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqIkFk-ETxOwWBP4Gn:-NiqIkFk-ETxOwWBP4Go:b-tcef2h) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.h#L55)):*
> ```objc
> 
>  private:
>   /** Initial guess to the MIP for solving max clique. */
> ```

nit Don't use Doxygen (`/**`) for private fields (https://drake.mit.edu/styleguide/cppguide.html#Doxygen).

Saying `/* Initial ... */` (with a single asterisk, instead) is fine.

Ditto below.
___
*[`planning/graph_algorithms/max_clique_solver_via_mip.h` line 62 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqJ0NW3--_3uT0SNzz:-NiqJ0NW3--_3uT0SO--:b2df078) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.h#L62)):*
> ```objc
> 
>   VectorX<bool> DoSolveMaxClique(
>       const Eigen::SparseMatrix<bool>& adjacency_matrix) const final;
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Declaration_Order

Within the private section, all functions should appear first, followed by the variables afterward.
___
*[`bindings/pydrake/planning/BUILD.bazel` line 41 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqK2DGCSK6ZdYRJhyP:-NiqK2DGCSK6ZdYRJhyQ:bckm9nu) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/bindings/pydrake/planning/BUILD.bazel#L41)):*
> ```Starlark
>         "planning_py_robot_diagram.cc",
>         "planning_py_trajectory_optimization.cc",
>         "planning_py_graph_algorithms.cc",
> ```

nit Place this in alphabetical order.
___
*[`bindings/pydrake/planning/planning_py.h` line 30 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqKAD3BdZikHJGT7wA:-NiqKAD3BdZikHJGT7wB:bfu0qd1) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/bindings/pydrake/planning/planning_py.h#L30)):*
> ```objc
> 
> /* Defines bindings per planning_py_graph_algorithms.cc. */
> void DefinePlanningGraphAlgorithms(py::module m);
> ```

nit Move this new part up a bit higher, so that it's in alphabetical order.
___
*[`bindings/pydrake/planning/test/graph_algorithms_test.py` line 3 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqMuxH2JCsMa9gxK1P:-NiqMuxICNB6Q3ydPNfc:btn1xuh) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/bindings/pydrake/planning/test/graph_algorithms_test.py#L3)):*
> ```Python
> import numpy as np
> import scipy.sparse as sp
> import unittest
> ```

nit Keep built-in vs third-party modules separated (with built-in first).



_Suggestion:_
```Python
import unittest

import numpy as np
import scipy.sparse as sp
```
___
*[`bindings/pydrake/planning/test/graph_algorithms_test.py` line 64 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqNN5kCTPFeLVJTOHr:-NiqNN5l6st5HvKVlGql:bv783lj) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/bindings/pydrake/planning/test/graph_algorithms_test.py#L64)):*
> ```Python
>         solver = mut.MaxCliqueSolverViaMip(solver_options=solver_options,
>                                            initial_guess=initial_guess)
>         # Test the getters
> ```

nit Missing punctuation (a period).

Ditto again two more times, below.
___
*[`bindings/pydrake/planning/test/graph_algorithms_test.py` line 82 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqNhNM7kzQKtRdTI1G:-NiqNhNM7kzQKtRdTI1H:b-fsmyj3) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/bindings/pydrake/planning/test/graph_algorithms_test.py#L82)):*
> ```Python
> 
>         # Test solve max clique
>         def GurobiOrMosekSolverAvailable():
> ```

BTW It's a bit weird to have this as an inline function.  WYDT about moving it to the top level, like we have in `trajectory_optimization_test`?  I suspect we'll be re-using this function as we add more graph tests over time.
___
*[`planning/graph_algorithms/max_clique_solver_via_mip.cc` line 21 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqKeSiAEmsSyU8hUDZ:-NiqKeSiAEmsSyU8hUD_:b-nwfv3k) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.cc#L21)):*
> ```cpp
> VectorX<bool> MaxCliqueSolverViaMip::DoSolveMaxClique(
>     const SparseMatrix<bool>& adjacency_matrix) const {
>   const int n = adjacency_matrix.rows();
> ```

BTW Here might be a good point to THROW_UNLESS the initial guess is of the wrong size.  I'm pretty sure the error will still noticed later (by the mathematical program) but the error message if detected early here might be better?
___
*[`planning/graph_algorithms/max_clique_solver_via_mip.cc` line 69 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqKv3B04y11FrsC-wm:-NiqKv3B04y11FrsC-wn:b-26hkb3) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.cc#L69)):*
> ```cpp
>   try {
>     solvers::SolverId solver_id = solvers::ChooseBestSolver(prog);
>     solver = solvers::MakeSolver(solver_id);
> ```

nit When rewriting the try-catch error, it's important that we know _exactly_ what failed.  Thus, we should have as little as possible inside the `try {}` block.  The `MakeSolver` should happen outside the block, just before `Solve()`.  (I'm pretty sure only the Choose throws, not Make, right?)
___
*[`planning/graph_algorithms/max_clique_solver_via_mip.cc` line 81 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqLFyO9P_ws22HvLNK:-NiqLFyP5K3QlwEJ0ULU:b-d8gv0i) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.cc#L81)):*
> ```cpp
>   }
>   solver->Solve(prog, initial_guess_, solver_options_, &result);
>   DRAKE_ASSERT(result.is_success());
> ```

BTW The upside of `DRAKE_ASSERT` vs `DRAKE_DEMAND` is that really expensive checks can be skipped in Release builds (i.e., so that they are only checked in CI).

This particular check is extremely inexpensive compared to solving the MIP, so it's not apparent why DRAKE_DEMAND wasn't used instead.
___
*[`planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc` line 39 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqLnWDBsDD0SZD-fHu:-NiqLnWDBsDD0SZD-fHv:bsar4qb) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc#L39)):*
> ```cpp
>     bool solution_match_found = false;
>     for (const auto& possible_solution : possible_solutions) {
>       if (CompareMatrices(max_clique_inds.cast<int>(),
> ```

nit Using `CompareMatrices` for a non-EXPECT test is overkill.  A simple `operator==` should work here?

```c++
if (max_clique_inds.cast<int>() == possible_solution.cast<int>()) {
```

?
___
*[`planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc` line 58 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqMEkJ2ovk7e_evzKR:-NiqMEkJ2ovk7e_evzKS:b-d1ehp3) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc#L58)):*
> ```cpp
>   EXPECT_EQ(solver1.get_solver_options(), solvers::SolverOptions());
> 
>   // Test the constructor with only the solver id passed.
> ```

Something about this comment, the following lines of code, and the next test case (SettersAndGetters) doesn't make sense to me.

Could you take another pass a make sure both of these test cases are very clear about what they are trying to cover in their testing, and how they are going about it?

**Review by AlexandreAmice — COMMENTED** [review]
Thanks for all the help!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-:-NiqXqU21JRnrRg_Lx7e:bdda62x)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/planning/test/graph_algorithms_test.py` line 82 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqNhNM7kzQKtRdTI1G:-NiqWkvd7xQnXW6mD9sX:b-mdxhkc) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/bindings/pydrake/planning/test/graph_algorithms_test.py#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW It's a bit weird to have this as an inline function.  WYDT about moving it to the top level, like we have in `trajectory_optimization_test`?  I suspect we'll be re-using this function as we add more graph tests over time.
</blockquote></details>

Happy to move it.
___
*[`planning/graph_algorithms/max_clique_solver_via_mip.cc` line 69 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqKv3B04y11FrsC-wm:-NiqUGcZ0nqlfr_6ma5f:b-4j6ygs) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.cc#L69)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit When rewriting the try-catch error, it's important that we know _exactly_ what failed.  Thus, we should have as little as possible inside the `try {}` block.  The `MakeSolver` should happen outside the block, just before `Solve()`.  (I'm pretty sure only the Choose throws, not Make, right?)
</blockquote></details>

`solvers::SolverId solver_id` is not default constructible, so I can't do 
```
solvers::SolverId solver_id;
try {  
  solver_id = solvers::ChooseBestSolver(prog);  
  solver = solvers::MakeSolver(solver_id);  
}
```
So I am not sure how I can make `solver_id` survive the scope of the try block to pass it to `MakeSolver` 
___
*[`planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc` line 58 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqMEkJ2ovk7e_evzKR:-NiqWGKe8b5N4JSIO7BV:b-ejucbs) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Something about this comment, the following lines of code, and the next test case (SettersAndGetters) doesn't make sense to me.

Could you take another pass a make sure both of these test cases are very clear about what they are trying to cover in their testing, and how they are going about it?
</blockquote></details>

Cleaned it up and consolidated it into one test.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20505)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/max_clique_solver_via_mip.cc` line 69 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20505#-NiqKv3B04y11FrsC-wm:-NirMJi439IQRLp5VQn7:byf4oyi) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee193e61a3d36e2089373525bb12620ed21f7f4a/planning/graph_algorithms/max_clique_solver_via_mip.cc#L69)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

`solvers::SolverId solver_id` is not default constructible, so I can't do 
```
solvers::SolverId solver_id;
try {  
  solver_id = solvers::ChooseBestSolver(prog);  
  solver = solvers::MakeSolver(solver_id);  
}
```
So I am not sure how I can make `solver_id` survive the scope of the try block to pass it to `MakeSolver`
</blockquote></details>

It can be `std::optional<solvers::SolverId> solver_id_`.  In case nothing throws, we'll know it was set so we can `MakeSolver(*solver_id)` after.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 11 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20505)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please.

**Pull request merged**
