### PR TITLE
another cleanup pass on the pendulum directory.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7000)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@siyuanfeng-tri for feature review, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7000#-:-KtkTSoaDfXUxqiRMV6V:b-1z9bi2)*

**Comment by siyuanfeng-tri** [comment]
nice! the dircol example looks really clean now (minus the trq constraint) :lgtm: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/pendulum/pendulum_plant.h, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7000#-Ktnc3zoZbZfgV2Eu_Vu:-Ktnc3zoZbZfgV2Eu_Vv:b39ktqa) ([raw file](https://github.com/robotlocomotion/drake/blob/d82c6814c502b223cc0521b440ffdc93766fa093/drake/examples/pendulum/pendulum_plant.h#L44)):*
> ```objc
>   T CalcTotalEnergy(const systems::Context<T>& context) const;
> 
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(PendulumPlant);
> ```

BTW i think this is better at the top. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7000#-:-KtndGJC-8O5QYd28xoO:b-lhnhzx)*

**Comment by RussTedrake** [comment]
+@sammy-tri for platform review.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/pendulum/pendulum_plant.h, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7000#-Ktnc3zoZbZfgV2Eu_Vu:-Ktno3cWGoh-aK1BzXlg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d82c6814c502b223cc0521b440ffdc93766fa093/drake/examples/pendulum/pendulum_plant.h#L44)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW i think this is better at the top. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7000#-:-KtnoD6UY_9o9UCZ3ydj:bpk00vl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7000#-:-KtqUSXuIJtCEQ4yo45z:bnfp4nl)*

**Pull request merged**
