### PR TITLE
Fix finding Fortran compiler when $FC is not set

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3871)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@sammy-tri for feature and platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/externals.cmake, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3871#-KUchxEfUaMsm1mVXHSv:-KUchxEge_ptkoRKG_zz:b-64nv93) ([raw file](https://github.com/robotlocomotion/drake/blob/7ad657a4904c88da9b31a380a7b645823e8caf2a/cmake/externals.cmake#L9)):*
> ```CMake
>   # compiler and set any flags passed in by environment variable
>   find_program(CMAKE_Fortran_COMPILER
>     NAMES "$ENV{FC}" gfortran gfortran-6 gfortran-5 gfortran-4
> ```

BTW my system actually has "gfortran-4.9" as opposed to "gfortran-4" for the name of the gcc 4.x fortran compiler.  This doesn't really matter, as the "gfortran" and "gfortran-5" names would be found first.

---

*[cmake/externals.cmake, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3871#-KUciCPSDgP0e2tuM8Jd:-KUciCPT4j7E5zKxZdio:b87c0ay) ([raw file](https://github.com/robotlocomotion/drake/blob/7ad657a4904c88da9b31a380a7b645823e8caf2a/cmake/externals.cmake#L14)):*
> ```CMake
>     message(STATUS "Found Fortran compiler: ${CMAKE_Fortran_COMPILER}")
>   else()
>     message(FATAL_ERROR "Could NOT find Fortran compiler")
> ```

BTW  I'm not sure this should be fatal?  Only one external uses it and that external is optional.  It would be nice to fail faster than getting all the way to building IPOPT before the error is observed, I admit.  Mixed opinions here.  If the make version is fatal if no fortran compiler is found, then I guess I'm fine with this being fatal too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3871#-:-KUciXF0N-UNQF7mOqQr:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/externals.cmake, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3871#-KUciCPSDgP0e2tuM8Jd:-KUcpw6pZgbT0RavUch7:bnav8ih) ([raw file](https://github.com/robotlocomotion/drake/blob/7ad657a4904c88da9b31a380a7b645823e8caf2a/cmake/externals.cmake#L14)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW  I'm not sure this should be fatal?  Only one external uses it and that external is optional.  It would be nice to fail faster than getting all the way to building IPOPT before the error is observed, I admit.  Mixed opinions here.  If the make version is fatal if no fortran compiler is found, then I guess I'm fine with this being fatal too.
</details>
BTW There are at least three at the moment, though they are all optional. We could make a Fortran compiler optional, but then we would want to correctly guard those externals. The make version does indeed throw a fatal error if there is no Fortran compiler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3871)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/externals.cmake, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3871#-KUchxEfUaMsm1mVXHSv:-KUctRqPSiA_kAAnZwWm:b-47dsa7) ([raw file](https://github.com/robotlocomotion/drake/blob/7ad657a4904c88da9b31a380a7b645823e8caf2a/cmake/externals.cmake#L9)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW my system actually has "gfortran-4.9" as opposed to "gfortran-4" for the name of the gcc 4.x fortran compiler.  This doesn't really matter, as the "gfortran" and "gfortran-5" names would be found first.
</details>
BTW Yes, I think the environment variable is still the way to go for those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3871)*

**Pull request merged**
