### PR TITLE
Remove PODS output dealing with library outputs

### LINKED ISSUE #4225: Build libraries in a location that mirrors the source tree
Libraries are built in `build/lib`, but should be built in `drake/path/to/my/lib.so` by analogy to binaries (post #4162).

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Remove PODS logic to force libraries to be written to a particular (and sometimes wrong) directory. Remove logic to add this location to the global link directories and pkg-config search path. The second part should never have been done; anything that actually needed that logic was doing something very wrong.

Fixes #4225

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4245)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
:lgtm: if it passes CI, but I would not bet against some legacy code doing something very wrong.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4245#-:-KXHPsaXkbavDtFWX1qB:bhh3aoa)*

**Comment by mwoehlke-kitware** [comment]
> I would not bet against some legacy code doing something very wrong.

Well, I'm not trying to push it *upstream* :smile:.

The only way I see that the additional removed code would ever be relevant is if library A creates a `.pc`, and library B searches for that `.pc` and uses it to link to library A (all of which must happen at configure time). That's a fair amount of work to go through to avoid doing the *right* — and much, much *easier* — thing, which is to just link to library A directly. (Note that this only applies for A and B both being in the same project; in this case, drake proper.)

Considering that managing to pull this off would additionally result in a missing dependency...

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4245#-:-KXHQSx1wIdA36_3UpfZ:bmf9kp7)*

**Comment by jamiesnape** [comment]
MOSEK problems, which reminds me that I need to PR the non-POD version of that wrapper.

**Comment by david-german-tri** [comment]
@wxmerkt heads-up on this one, in case you depend on any of the pkg-config weirdness

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4245#-:-KXfaKQ0eiOLQb4baRjC:bcohyf5)*

**Comment by david-german-tri** [comment]
I'll await green CI (including some Mac builds, please) before testing this locally.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4245#-:-KXfak0kAplKsAvAYLGI:bz6y80h)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
> wxmerkt heads-up on this one, in case you depend on any of the pkg-config weirdness

Since there are not changes to the install directories, this should not affect any external consumers of pkg-config files. How drake searches for libraries and where it builds artifacts are invisible to them.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-clang-experimental-debug please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
`Undefined variable "drake" or class "drake.matlab.util.BotLCMGLClient".`

**Comment by jamiesnape** [comment]
Is `BotLCMGLClient` Java?

**Comment by mwoehlke-kitware** [comment]
> Is BotLCMGLClient Java?

Probably? I'm not sure what's going on here; the only references I can find (at least in drake itself) are in MATLAB code... I have no idea why these changes would be causing that breakage...

**Comment by jamiesnape** [comment]
BotLCMGLClient is not in the Java classpath, so the MATLAB JVM cannot find it.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
> I have no idea why these changes would be causing that breakage...

Solved. See @9a19e5b96e24 for explanation. (Moral: never trust comments.)

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4245#-:-KXqmlZvFQ_Kdm2FrmGL:bnfp4nl)*

**Pull request merged**
