### PR TITLE
Rename AddL2NormCost to Add2NormSquaredCost

### LINKED ISSUE #15124: solvers: Rename AddL2NormCost
since the cost that gets added, |Ax-b|^2, is not the L2 norm.  It's the L2-norm squared?

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #15124

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15134)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please.

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15134#-:-MbOOt1WC3e4AIOuLkn9:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15134)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15134#-MbOSxH24FQ07jiWpRi2:-MbOSxH3CW31KdnLVVFL:b-gpj5ts) ([raw file](https://github.com/robotlocomotion/drake/blob/5c9efd8a45e3c2f5d2472085bf089f12250e972d/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1254)):*
> ```cpp
>                 const Eigen::Ref<const Eigen::VectorXd>&,
>                 const Eigen::Ref<const VectorXDecisionVariable>&>(
>                 &MathematicalProgram::AddL2NormCost)),
> ```

should this point to 2Norm (not L2Norm)?
___
*[solvers/mathematical_program.h, line 1039 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15134#-MbOTIUcEvOYIvDB_X_W:-MbOTIUcEvOYIvDB_X_X:bozp4ph) ([raw file](https://github.com/robotlocomotion/drake/blob/5c9efd8a45e3c2f5d2472085bf089f12250e972d/solvers/mathematical_program.h#L1039)):*
> ```objc
>    * Adds a cost term of the form | Ax - b |^2.
>    */
>   DRAKE_DEPRECATED("2021-09-01", "Rename this function to Add2NormSquaredCost")
> ```

can this be a message to the user?  Like "Please use ..." as you did above? (also below)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15134)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15134#-MbOSxH24FQ07jiWpRi2:-MbP5vgSEvF-jSCZeED9:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/5c9efd8a45e3c2f5d2472085bf089f12250e972d/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1254)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

should this point to 2Norm (not L2Norm)?
</blockquote></details>

Done. Good call.
___
*[solvers/mathematical_program.h, line 1039 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15134#-MbOTIUcEvOYIvDB_X_W:-MbP64xkCmaOan4YhtUx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5c9efd8a45e3c2f5d2472085bf089f12250e972d/solvers/mathematical_program.h#L1039)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

can this be a message to the user?  Like "Please use ..." as you did above? (also below)
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:LGTM:
+@ericcousineau-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15134#-:-MbQR1e-70DCwDAxefxb:b1swea7)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15134)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15134#-Mbbs6fb8rQXYv257e0q:-Mbbs6fc4I4swQpgYrm6:bz87rii) (no related file):*
Not sure if I understand why we prefer "2-norm" in lieu of "L2-norm", especially in terms of consistency with our codebase and others.

What's the benefit in clarity for "2-norm" over "L2-norm"? Where else do we use it, and when is "2-norm" clearer?

I reviewed the issue, but the most I could see is `People use "l2 norm" and "2-norm" interchangeably`, which IMO doesn't merit deviation?

---

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15134)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15134#-Mbbs6fb8rQXYv257e0q:-Mbbtexr6BtY557rN4YI:bkfn86r) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Not sure if I understand why we prefer "2-norm" in lieu of "L2-norm", especially in terms of consistency with our codebase and others.

What's the benefit in clarity for "2-norm" over "L2-norm"? Where else do we use it, and when is "2-norm" clearer?

I reviewed the issue, but the most I could see is `People use "l2 norm" and "2-norm" interchangeably`, which IMO doesn't merit deviation?
</blockquote></details>

I want to change the behavior of `AddL2NormCost` from adding `(Ax-b)ᵀ(Ax-b)` to `sqrt(Ax-b)ᵀ(Ax-b)`. If I keep the original name `AddL2NormCost` but change the behavior, it would silently change the behavior of all the downstream code, causing confusion to the user. So the solution is to change the name to `Add2NormCost`. Then to stay consistent with this new name, I also use `Add2NormSquaredCost`.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15134)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15134#-Mbbs6fb8rQXYv257e0q:-Mbbvz9J4iPmRqWg4LG5:b-gsx5) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I want to change the behavior of `AddL2NormCost` from adding `(Ax-b)ᵀ(Ax-b)` to `sqrt(Ax-b)ᵀ(Ax-b)`. If I keep the original name `AddL2NormCost` but change the behavior, it would silently change the behavior of all the downstream code, causing confusion to the user. So the solution is to change the name to `Add2NormCost`. Then to stay consistent with this new name, I also use `Add2NormSquaredCost`.
</blockquote></details>

OK Gotcha!

I've attempted to reiterate your point here (IMO will be important for future reviews)
https://github.com/RobotLocomotion/drake/issues/15124#issuecomment-856198466

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform given rationale for going from `AddL2Norm*` to `Add2Norm*` - thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15134#-:-MbbwjBiBD7-Y4r7KuWI:b-ydxlb9)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Comment by EricCousineau-TRI** [comment]
Ah, it was in upthread discussion in issue -  oops!

**Pull request merged**
