### PR TITLE
Auto reverts jvm to use ipv4 on OSX

### PR DESCRIPTION
**Pull request by peteflorence**
Fixes https://github.com/RobotLocomotion/drake/issues/558

@RussTedrake wasn't sure if this is the best way to implement, but thought might be helpful

To note:
- Not sure if addpath_drake is the right spot, but it seemed best to query matlabroot within matlab
- An edge case to consider:
 - If:
   - You still haven't fixed your ipv6 problem (i.e., never successfully ran any Drake examples with lcm)
    - You have addpath_drake in your startup.m
  - Then MATLAB will freeze during startup.m since the script requires command line input (to edit the java.opts file, you need `sudo` password) 
 - But since a first-time Drake user during setup probably doesn't have a startup.m with addpath_drake in it, this doesn't seem to be a problem
- I haven't tested on different versions (2015a, 2013 a/b).  I'm running 2014b.

### CODE REVIEW

**Comment by RussTedrake** [comment]
@peteflorence -- awesome.  but i think the right thing to do is to issue a warning and link to the bug report with the solution (not to overwrite their config file).  addpath_drake is a fine place for it.  also wish there was a way to check programmatically instead of string-matching the config file.

**Comment by peteflorence** [comment]
Okay will make it a link to the bug report.  Will also see if I can check jvm's IP version without string-matching

**Comment by peteflorence** [comment]
@RussTedrake -- changed the behavior to just issue a warning and link to https://github.com/RobotLocomotion/drake/issues/558.

I could not figure out how to avoid using string matching.  I started a stackoverflow question for it, maybe a more knowledgable Java person will come through:

http://stackoverflow.com/questions/32098223/check-programatically-without-string-matching-whether-using-ipv6-or-ipv4-for-j

**Comment by peteflorence** [comment]
There was a solution submitted by a mysterious 'rdeits' on stackoverflow (@rdeits)

Can now check without doing a string compare on -Djava.net...

(Technically still doing a string comparison since Matlab gets back a string 'true' rather than boolean when calling java.lang.System.getProperty)

**Comment by RussTedrake** [comment]
fwiw - drake001 triggers this warning, but has never had a problem.  
what do people think, is it good to have this in?

**Comment by peteflorence** [comment]
Is drake001 on a pre-Yosemite version of OSX?

Robin's computer also never has problems. Think it's Yosemite only. Could
check for Yosemite.

**Comment by RussTedrake** [comment]
Yes.  It's also only wired ethernet...

**Pull request merged**
