### PR TITLE
adds a InitiliazeContext method to system / diagram

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5687)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@jwnimmer-tri for feature review. 
+@sherm1 for platform.
Sherm and I talked about this a bit today. 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5687#-:-KgaoZKxtQNJQ-CUA4_O:blcbkj)*

**Comment by jwnimmer-tri** [comment]
I am highly skeptical, but in any case you don't have to convince me (so -@jwnimmer-tri), you have to convince +@david-german-tri.  Please do not merge without letting him weigh in.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5687#-:-KgapbXbbC4C6GF9BzFG:bgqb4rk)*

**Comment by siyuanfeng-tri** [comment]
well, alright then. i guess this is not happening any time soon. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5687#-:-Kgaqiiq7JkwXcZUk6nx:b-6v2a8q)*

**Comment by jwnimmer-tri** [comment]
Objections for consideration:
1. The API doesn't explain what is allowed during Initialize, nor under what conditions its guaranteed to be (i.e., supposed to be) called, and how many times it can or cannot be called (idempotency), etc..  This makes it harder for code that's not the Simulator to use a System.
2. Even if (1) were clear, whatever obligations that (1) documents must be met by every System caller, so it's yet more friction from using a System outside of a Simulator, e.g., with the optimization tools.
3. The implementation doesn't fail-fast if the guarantees conditions are not met.  If a method that requires Initialize to preceded it is called without the Initialize, nobody will notice.  Fixing this is even more difficult wiring within the mechanics of a Context.
4. The DrakeVisualizer example is not motivating, both because that nit can be solved without adding new APIs, and because there are very few answers for (1) above where the DrakeVisualizer change ends up being correct.

**Comment by sherm1** [comment]
The need for a System API like this has been clear for a long time and discussed before, e.g. in #4191 in November. May I quote:
> My hope is that the System abstraction will offer a "starting sim now, please populate your t=0 values into this Context param", and that the Simulator would invoke that without main-program boilerplate in the common case. 
-- @jwnimmer-tri

> jwnimmer-tri Thanks for the clarification. Seems reasonable to me. -- @david-german-tri

> We are planning to add an Initialize() call from the Simulator at simulation start. -- @sherm1

I take that exchange as a ringing endorsement for the concept, if not necessarily the details! In any case because the Simulator is solving initial value problems we need a way for a System to set its initial state at the start of a simulation. I agree with Jeremy's objection 1 above that the method's semantics need clarification, and with objection 2 that the method may need to be directed only at time simulations. (However that would by no means be the only such method -- the whole concept of events assumes time advancement and is useless in an optimization context.)

I'll work with @siyuanfeng-tri to clarify the purpose and specification. 

---

Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5687#-:-Kgbrn-GCkSNw-oYbSVZ:blcl6jt)*

**Comment by sherm1** [comment]
@siyuanfeng-tri, there are CI test failures.

**Comment by sherm1** [comment]
It may be better to think of this as an initialization *event* so that initialization is one of the many events that a time simulation is expected to handle.

**Comment by siyuanfeng-tri** [comment]
i change the tags to reflect the current status, and i will change those back once it's more ready. 

i agree with @jwnimmer-tri's first concern. for the second, that's sort of true for all the systems api in some way. 
from my perspective, i don't see any convincing reason for me to have anything wrapped in systems other than to use simulator. that's probably not the original intention. i could imagine using it with the opt pipeline, but initialization is almost always needed there as well. 
for 3, i could add some checks at run time. 
4. that's the simplest example. all my walking stuff needs to be properly initialized. i didn't convert those in this pr. 

---

Review status: 1 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5687#-:-KgbyYZ9TtyDNIqxTKG6:bj2q2ah)*

**Comment by jwnimmer-tri** [comment]
From the 4191 post, "Populate your starting values" is what the "SetDefaults" family of APIs solved already.  "Please transmit this message" is manifestly _not_ that.

**Comment by jwnimmer-tri** [comment]
Here's the way I think about it.

Say I want to begin using a system from its genesis.  (This would be as opposed to, say, starting up an autodiff system at some intermediate time as a linearization of some other system.)

Right now, I do this:
```c++
// (1)
void use_a_system(const System& system) {
  auto context = system.CreateDefaultContext();
  auto xdot = system.AllocateTimeDerivatives();
  system.CalcTimeDerivatives(context, xdot.get());
  // ...
}
```

Given my understanding of the `Initialize` concept, I would instead have to do this:
```c++
// (2)
void use_a_system(const System& system) {
  auto context = system.CreateDefaultContext();
  system.InitializeContext(context.get());
  auto xdot = system.AllocateTimeDerivatives();
  system.CalcTimeDerivatives(context, xdot.get());
  // ...
}
```

Surely if we need an `Initialize` call every time I want to start using a fresh `Context`, the `CreateDefaultContext` should just do it for me instead?

If Create + Initialize must always be twins, then they should be the same thing.  If they are not twins, we need to clarify what Create is guaranteed to produce and/or when Initialize must or must not be used, but it's hard for me to imagine cases for when Create vs Initialize should be severed.

---

I _could_ imagine something like what Sherm is perhaps alluding to with the events comment -- that I (as a user) ask for a default Context, and then _I mess around with the data in the context_, and then somehow I need to ask the System to do some follow-up work before I begin moving time forward.  That seems worth exploring, but this PR does not appear to be aimed at that problem, and in any case we need a specific motivating example before we change the framework to support that.

**Comment by siyuanfeng-tri** [comment]
CreateDefaultContext creates / initializes to the "default" values. On the other hand, there are plenty of applications that needs to be started from some values other than default, and that's what InitializeContext is intended for. Another extreme case is that we could have made the decision that BasicVector's constructor sets all elements to nan, and none of our simulation would run without Initialize.

Here is a concrete example for robot controllers. When the controller initializes, it should always initialize its desired posture to whatever the current measured posture to hold the current posture. If you initialize the desired posture to some default values, as soon as you turn on the controller it will try to servo to that, which is a really bad idea. 
There are plenty of other examples, like monte carlo simulation and whatnot. 

I always think CreateDefaultContext is more like allocate some memory, and Initialize is to properly set it up. You inherently need more information for the second part. 

"I could imagine something like what Sherm is perhaps alluding to with the events comment -- that I (as a user) ask for a default Context, and then I mess around with the data in the context, and then somehow I need to ask the System to do some follow-up work before I begin moving time forward." I totally agree with this. This should also fall in the Initialize step.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5687#-:-KgeBwURsJJcN2gL9UaB:b-w690v2)*

**Comment by jwnimmer-tri** [comment]
> I always think CreateDefaultContext is more like allocate some memory, and Initialize is to properly set it up.

I think that's the problem.  `AllocateContext` is the API to allocate memory, `SetDefaults` the API to initialize it, and `CreateDefaultContext` is sugar that does both in a row.  If you want to choose special defaults, use the existing defaults tooling.

> You inherently need more information for the second part.

Perhaps, but _the `Initialize` method in this PR doesn't have access to any more information than `SetDefaults` does_!

> ... there are plenty of applications that needs to be started from some values other than default ... [including e.g. the posture starting point] ..

Absolutely!  So either (1) write application-specific main code that writes values into a `Context` before running the System, or (2) override `SetDefaults` (or one of its helpers) if you want to tie the logic into the `System` directly.  I don't see why _another_ method that only operates on the `Context` is required to meet this need?

> Another extreme case is that we could have made the decision that BasicVector's constructor sets all elements to nan, ...

We _did_ make that decision, and it _does_ that, and e.g. `LeafSystem::AllocateOutputVector` keeps the NaN there.

> ... and none of our simulation would run without Initialize.

... which is why `SetDefaults` exists.

**Comment by siyuanfeng-tri** [comment]
alright, silly me. 
i was not aware of SetDefaultState's existence. i am happy with initializing.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5687#-:-KgeJ2fNyJ0W61b9VlS6:b-weukdt)*

**Comment by siyuanfeng-tri** [comment]
I also need to do something unrelated to Context or System before the code can properly run, e.g. wait for some network traffic to get my initial condition numbers, hand shaking etc.. Drake viz is one instance, my lcm driven loop thing is another. Maybe I should wait for 3 to do something about it. 
In any event, I am going to retract this pr later today unless @sherm1 has more to add. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5687#-:-KgeMOv5hijFqahtbB5B:b-o10hcu)*

**Comment by jwnimmer-tri** [comment]
> I also need to do something unrelated to Context or System before the code can properly run, ...

It would be interesting to explore whether that's best to declare within a `System`, or as part of configuring the `Simulator`, or something else entirely.

**Comment by sherm1** [comment]
What triggered this discussion, and @siyuanfeng-tri's visit to HQ, was the currently-awkward handling of Publish() calls, where the Simulator has to guess that the System's Publish() method should be called at initialization (among other oddities). This is different than the need to be able to set some default values into the state, where there is no implication that we are at the start of a time-advancing simulation. An initialization event generated just prior to the start of time stepping could be handled or ignored by a System. If handled, an appropriate event handler (like CalcUnrestrictedUpdate()) would be called and that handler can publish, compute appropriate initial values for state variables, or set default ones if it wants. A bookend termination event may be useful also.

One very common thing to do in an initialization event handler is to find values for the state variables that are consistent with the System's constraints -- that is required prior to the start of any simulation and is much harder than setting default values.

**Comment by jwnimmer-tri** [comment]
The `DrakeVisualizer` System should:
- declare an abstract state variable that models whether the remote end has been sent an appropriate `load_robot` message;
- default the initial value of that state to be "remote has not been sent`load_robot`";
- iff that state indicates "remote has not been sent `load_robot`", the System should declare an immediate unrestricted update;
- when that update is invoked, the System should transmit `load_robot` and set the post-state to "remote has been sent `load_robot`".

In this way, the message is sent no matter what else happens in establishing a Context (e.g., start time); the application developer can exert control if the defaults are not good (e.g., mute the original message, or transmit a new one by frobbing the abstract state); the System remains pure (no hidden state); and the System APIs do not need to change.

If we find that such a sequence is common, we can bake it in as sugar into `LeafSystem` (where a subclass constructor could call `DeclareOneTimeEvent`), and still nothing in the core System APIs has to change, and callers of the System class still do not have to remember to fire off an initialization event.

There may be a reason to do something separate to solve for initial conditions, but let's net conflate that with `load_robot` unnecessarily.

**Comment by sherm1** [comment]
That sounds good but there is an unsolved step in that recipe:
> iff that state indicates "remote has not been sent load_robot", the System should declare an immediate unrestricted update

There are two abstractions used by the Simulator for events: (1) event triggers, and (2) event handlers. Current triggers are: 
- periodic time reached, 
- calculated update time reached, 
- major time step reached, 
- witness (guard) function crossed zero [almost]. 

These can invoke any of the three handler APIs: 
- Publish(), 
- DiscreteUpdate(), 
- UnrestrictedUpdate(). 

There isn't currently a trigger that will invoke a handler based on a discrete condition at start-of-step (e.g. in this case `remote_has_been_sent load_robot"==false). A discrete event trigger would be a valuable complement to the continuous event triggers (witnesses) we currently have in the works, and we have discussed discrete triggers before though haven't designed the API yet. Start- and end-simulation triggers are also missing and useful and require only a minor API mod so are likely to land first.

/cc @edrumwri

**Comment by jwnimmer-tri** [comment]
In https://github.com/jwnimmer-tri/drake/commits/simulator-zerotime-update, I tweak the simulator and unit test to prove that we already have the tools in place for `Value<bool>` abstract state to trigger an event at the start of simulation.

**Comment by sherm1** [comment]
Hmmm ... looks good but I was under the impression we required next-update times to be strictly greater than the current time to prevent duplicate events in tight roundoff corners. @edrumwri?

**Comment by jwnimmer-tri** [comment]
Yes, the `if`-statement I added in the simulator skips the integrator's enforcement that the step is strictly positive.  It does mean that misbehaved systems will not fail-fast like they used to, so it still would need polish and clear thinking, but I don't think that we're far away in term of supporting the `load_robot` needs.  I guess you could even imagine sending `load_robot` at `start_time + epsilon` and nobody would notice.

**Comment by david-german-tri** [comment]
The `SetDefault` family meets @siyuanfeng-tri's need to initialize state.  

Application code can generate one-time publish events outside the Simulator's purview, perhaps making use of domain-specific helper functions on Systems.  The [visualizer connection in AutomotiveSimulator](https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/automotive_simulator.cc#L300) is a good example.  This stands in contrast to the DrakeVisualizer `load_robot`, which is just a design holdover from System1.  My feeling is that we should remove it and discourage any similar strategies, such as the one in @jwnimmer-tri's `simulator-zerotime-update` branch.

Are there other problems an `Initialize` family is expected to solve?  If not, I agree with @siyuanfeng-tri's decision to close.

**Comment by siyuanfeng-tri** [comment]
To summarize, the Initialization function proposed in the pr was to provide a handle in the System api for two things, one is to set context, the other is to do some other side effects that has nothing to do with system. like publishing some init signal / load robot model etc. the first is taken care of by SetDefault, we have decided to leave the second to user space code for now.

**Comment by sherm1** [comment]
I don't think there is a need for a generic System::Initialize() method, since the actions to be taken would depend on what kind of analysis is about to be performed. For the Simulator in particular there are preconditions that must be satisfied prior to the start of the first time-advancing step (position and velocity constraint equations must be satisfied, contact geometry can't be overlapping, other system-specific requirements). Availability of an initialization event trigger (meaning that a call to Simulator::Initialize() is being processed) would be sufficient for bootstrapping a time simulation in a straightforward way. (P.S. Time is not necessarily 0 at initialization.)

**Comment by RussTedrake** [comment]
sorry I'm late to the discussion.  fwiw, in matlab we did eventually need to add a second method:
http://drake.mit.edu/doxygen_matlab/class_drake_system.html#a949bc5a77597809560cca5fab8e76d65
because that is the extra information that might be useful to initialize the system, which is available at sim time but possibly not before.

**Comment by siyuanfeng-tri** [comment]
i think we have agreed that the individual subsystems should do their own initialization because there is no common api at the system level. to make life easier, we now provide easier access to sub system's context in https://github.com/RobotLocomotion/drake/pull/5740

**Pull request closed without merging**
