### PR TITLE
Remove remaining CMake matlab logic to matlab subdirectory

### PR DESCRIPTION
**Pull request by jamiesnape**
In part so we do not package MATLAB configuration in C++ only binary packages.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4368)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by mwoehlke-kitware** [comment]
Um... :lgtm:, I guess, but please have someone familiar with MATLAB also do a feature review

---

Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/CMakeLists.txt, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-KYJf9qgBytrWdq8AugT:-KYJf9qj8bNsOxucxtSt:b8zbvyk) ([raw file](https://github.com/robotlocomotion/drake/blob/933511ef4e8d781c07b74b597c47666275c66c94/drake/matlab/CMakeLists.txt#L50)):*
> ```CMake
>   function(drake_add_matlab_addpath_test dependency)
>     drake_add_matlab_test(NAME matlab/addpath_${dependency}_test
>       REQUIRES ${dependency} COMMAND "addpath_${dependency}" SIZE small)
> ```

BTW, a `;` has gone away here, I guess that is harmless?

---

*[drake/matlab/CMakeLists.txt, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-KYJg0886HDBNuyPadyi:-KYJg08A7Xy74w-b84_5:b-np0kbv) ([raw file](https://github.com/robotlocomotion/drake/blob/933511ef4e8d781c07b74b597c47666275c66c94/drake/matlab/CMakeLists.txt#L101)):*
> ```CMake
>   drake_add_matlab_check_dependency_test_no(xfoil)
> 
>   if(NOT Bullet_FOUND)
> ```

BTW, `set(bullet_FOUND ${Bullet_FOUND})` would simplify this...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-:-KYJhRkK6ws-jl0Ae6Bn:b-wagaub)*

**Comment by jamiesnape** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/CMakeLists.txt, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-KYJf9qgBytrWdq8AugT:-KYJhpK9EjxHZv5xFvvq:b-uq22z) ([raw file](https://github.com/robotlocomotion/drake/blob/933511ef4e8d781c07b74b597c47666275c66c94/drake/matlab/CMakeLists.txt#L50)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, a `;` has gone away here, I guess that is harmless?
</blockquote></details>

BTW Yes. Here the semicolon suppresses output, but the function has no output, so it is redundant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4368)*

**Comment by jamiesnape** [comment]
+@david-german-tri for MATLAB and platform review.

Note before 544 tests, after 563 tests.

https://drake-cdash.csail.mit.edu/index.php?project=Drake&filtercount=2&showfilters=1&filtercombine=and&field1=revision&compare1=61&value1=4f0937061ec3b282f684c2af5d295c487c5cbdce&field2=buildstarttime&compare2=84&value2=now

**Comment by david-german-tri** [comment]
For future readers - the 19 new tests are from `drake_add_matlab_addpath_test` and `drake_add_matlab_check_dependency_test`.

:lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/matlab/CMakeLists.txt, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-KYL05p28sj3VbAstqgV:-KYL05p25q--v6KwReyH:b5w772r) ([raw file](https://github.com/robotlocomotion/drake/blob/933511ef4e8d781c07b74b597c47666275c66c94/drake/matlab/CMakeLists.txt#L60)):*
> ```CMake
>   drake_add_matlab_addpath_test(yalmip)
> 
>   function(drake_add_matlab_check_dependency_test dependency)
> ```

BTW this is nice, thanks!

---

*[drake/matlab/CMakeLists.txt, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-KYL0_nd2oDbdpkT2M0t:-KYL0_ne-adrEjcguiz5:bedlgjl) ([raw file](https://github.com/robotlocomotion/drake/blob/933511ef4e8d781c07b74b597c47666275c66c94/drake/matlab/CMakeLists.txt#L103)):*
> ```CMake
>   if(NOT Bullet_FOUND)
>     drake_add_matlab_test(NAME matlab/check_dependency_no_bullet
>       COMMAND "checkDependency('bullet')" CHECK_DEPENDENCY_STRICT SIZE small)
> ```

BTW why not use the helper function for this one?

---

*[drake/matlab/systems/plants/BotVisualizer.m, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-KYLKvyq3LXQBJz7dFQr:-KYLKvyr6sXooJUmgn8E:bfkcx28) ([raw file](https://github.com/robotlocomotion/drake/blob/933511ef4e8d781c07b74b597c47666275c66c94/drake/matlab/systems/plants/BotVisualizer.m#L222)):*
> ```objc
>     
>     function playbackMovie(obj,xtraj,filename,options)
>       checkDependency('ffmpeg');
> ```

BTW, how did you discover the need for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-:-KYL-j4p0mwWyzG8q7WJ:bvtdx57)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/matlab/CMakeLists.txt, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-KYL0_nd2oDbdpkT2M0t:-KYLLOcl3uzETtEAMdto:bd0kmdf) ([raw file](https://github.com/robotlocomotion/drake/blob/933511ef4e8d781c07b74b597c47666275c66c94/drake/matlab/CMakeLists.txt#L103)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW why not use the helper function for this one?
</blockquote></details>

BTW Capitalization `Bullet_FOUND` vs. `bullet_FOUND`.

---

*[drake/matlab/systems/plants/BotVisualizer.m, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4368#-KYLKvyq3LXQBJz7dFQr:-KYLLW_F95M-NWKQ_glb:bjsyc2b) ([raw file](https://github.com/robotlocomotion/drake/blob/933511ef4e8d781c07b74b597c47666275c66c94/drake/matlab/systems/plants/BotVisualizer.m#L222)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, how did you discover the need for this?
</blockquote></details>

BTW Just by inspection when looking at `FFMPEG_EXECUTABLE`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4368)*

**Pull request merged**
