### PR TITLE
Fix sign-compare warnings in systems/controllers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Fix sign-compare warnings in systems/controllers.
- Stop suppressing sign-compare warnings in systems/controllers.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2715)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@ggould-tri for all review, please.

**Comment by ggould-tri** [comment]
A significant improvement in an ugly part of the code :lgtm:

I was going to ding trailing whitespace and then I realized it was all `^M` world.

Too much to hope that your changes fixed the creeping memory corruption that lives somewhere in InstantaneousQP I suppose...

---

Reviewed 3 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 210 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2715#-KLakHageFQs94jx68RQ:-KLakHageFQs94jx68RR:677247605) ([raw file](https://github.com/robotlocomotion/drake/blob/50cecaea2218065ff77c9f9026870922b2e43f37/drake/systems/controllers/InstantaneousQPController.cpp#L210)):*
> ```cpp
>   VectorXd qdd_limited = qdd;
>   // Do not wind the vref integrator up against the joint limits for the legs
>   for (const int& pos_ind : rpc.position_indices.legs.at(Side::RIGHT)) {
> ```

Yay!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2715#-:-KLakegHSr1naqhGYeaq:1882161527)*

**Comment by jwnimmer-tri** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 210 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2715#-KLakHageFQs94jx68RQ:-KLamHZWJpiewZcklLS8:540075198) ([raw file](https://github.com/robotlocomotion/drake/blob/50cecaea2218065ff77c9f9026870922b2e43f37/drake/systems/controllers/InstantaneousQPController.cpp#L210)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Yay!
</details>
Totally!  I am super happy every time I convert an indexed loop to a for-range loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2715)*

**Comment by jwnimmer-tri** [comment]
FTR, this was a portion of #2372.

**Pull request merged**
