### PR TITLE
Use a single iiwa_plan_source

### PR DESCRIPTION
**Pull request by sammy-tri**
De-duplicate some cut and pasted code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5916)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-:-KiG60TqQtzBGfBdXk88:b-psw9ws)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 10 of 12 files at r1.
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-KiVJljhetfbsV5YBp2u:-KiVJljiVpYm83FqmSw9:b9vz1ri) ([raw file](https://github.com/robotlocomotion/drake/blob/e19dc46b35fa3e4facc5b9b1255e86264cc1815b/drake/examples/kuka_iiwa_arm/iiwa_plan_source.h#L21)):*
> ```objc
> ///
> /// If a plan is received with no knot points, the system will create
> /// a plan which commands the arm to hold at the measured position.
> ```

BTW : Might be useful to note that a plan has positions & velocities + accelerations and is sent out on separate ports. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-:-KiVXYUfNcImgwgwzzgr:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm: for non-dev parts.

---

Reviewed 4 of 12 files at r1, 1 of 3 files at r2.
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-KiVm25D8txvG1DuSLKz:-KiVm25D8txvG1DuSLL-:b-h20jb6) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4820ff614c483a20b15667abe5bb072c66fcef/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L56)):*
> ```cpp
>           .get_index()),
>       state_output_port_(
>           this->DeclareOutputPort(systems::kVectorValued, kNumJoints * 2)
> ```

BTW Inconsistent `2 * num` vs `num * 2` here vs above.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 106 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-KiVmGf6FaDUdI-l9vnM:-KiVmGf6FaDUdI-l9vnN:brgwz8n) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4820ff614c483a20b15667abe5bb072c66fcef/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L106)):*
> ```cpp
>       plan.pp_deriv.value(context.get_time() - plan.start_time);
>   output_acceleration_vec =
>       plan.pp_double_deriv.value(context.get_time() - plan.start_time);
> ```

FYI Consider named local for the common `now - start_time` subexpression for prior three statements.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.h, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-KiVloH79x8XPv2379Gm:-KiVloH79x8XPv2379Gn:bf89mzo) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4820ff614c483a20b15667abe5bb072c66fcef/drake/examples/kuka_iiwa_arm/iiwa_plan_source.h#L80)):*
> ```objc
>                   systems::State<double>* state) const;
> 
>   static constexpr double kDefaultPlanUpdateInterval = 0.1;
> ```

This is ODR-used to needs storage defined in the `.cc` file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-:-KiVn6aFxipU-nsE2xT3:b-sufjoh)*

**Comment by sammy-tri** [comment]
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-KiVm25D8txvG1DuSLKz:-KiWBMZxCGktRmT1ppjl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4820ff614c483a20b15667abe5bb072c66fcef/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Inconsistent `2 * num` vs `num * 2` here vs above.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 106 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-KiVmGf6FaDUdI-l9vnM:-KiWBF0BnaM1JMbonVJu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4820ff614c483a20b15667abe5bb072c66fcef/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider named local for the common `now - start_time` subexpression for prior three statements.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.h, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5916#-KiVloH79x8XPv2379Gm:-KiWAm1AmC1pAusO41y3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4820ff614c483a20b15667abe5bb072c66fcef/drake/examples/kuka_iiwa_arm/iiwa_plan_source.h#L80)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is ODR-used to needs storage defined in the `.cc` file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5916)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: 10 of 12 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5916)*

**Comment by naveenoid** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5916)*

**Pull request merged**
