### PR TITLE
Adds a magnetometer sensor.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5251)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR is close to being ready for review. I'll keep this open for now.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@liangfok This PR is old and conflicted.  Perhaps it can be closed?  An issue could track the lack of Magnetometer and could link to this draft for someone else to pick up?

**Comment by liangfok** [comment]
@jwnimmer-tri thanks for the note. I'll do as you suggest. The tracking issue is #6565.

**Pull request closed without merging**
