### PR TITLE
graduate Monomial

### PR DESCRIPTION
**Pull request by hongkai-dai**
As we discussed in #5234 , we need to move `Monomial` class out of `internal` namespace.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5249)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-:-KdX_KATj4cY6PH_DCzh:bboswjz)*

**Comment by hongkai-dai** [comment]
+@david-german-tri for platform review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-:-KdXjw_U8-WyVRULlZAh:b93ll5)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.h, line 334 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-KdY8Pg8sObySNVKD36F:-KdY8Pg8sObySNVKD36G:byvtq47) ([raw file](https://github.com/robotlocomotion/drake/blob/f59c8eadf18b6e29ee4eaaa055660ea65e58fbfb/drake/common/monomial.h#L334)):*
> ```objc
> /** Computes the hash value of a Monomial. */
> template <>
> struct hash_value<symbolic::Monomial> {
> ```

BTW should this be in an anonymous namespace?

---

*[drake/common/monomial.h, line 340 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-KdY8SKn0sAY3rVNARaD:-KdY8SKn0sAY3rVNARaE:b-8o3rbm) ([raw file](https://github.com/robotlocomotion/drake/blob/f59c8eadf18b6e29ee4eaaa055660ea65e58fbfb/drake/common/monomial.h#L340)):*
> ```objc
> };
> 
> namespace symbolic {
> ```

It's kind of odd to close this namespace 10 lines above, and then reopen it here.  Can you consolidate them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-:-KdY8jIL8rXMSqKc0JC1:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.h, line 334 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-KdY8Pg8sObySNVKD36F:-KdYAHp0wmSbnAwpr6WM:b-vbtswt) ([raw file](https://github.com/robotlocomotion/drake/blob/f59c8eadf18b6e29ee4eaaa055660ea65e58fbfb/drake/common/monomial.h#L334)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW should this be in an anonymous namespace?
</blockquote></details>

I think this is in the drake namespace?

---

*[drake/common/monomial.h, line 340 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-KdY8SKn0sAY3rVNARaD:-KdY9yHe0-cze4DCICpY:bi2o1a8) ([raw file](https://github.com/robotlocomotion/drake/blob/f59c8eadf18b6e29ee4eaaa055660ea65e58fbfb/drake/common/monomial.h#L340)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

It's kind of odd to close this namespace 10 lines above, and then reopen it here.  Can you consolidate them?
</blockquote></details>

The reason is that to define `MonomialToCoefficientMap` in this namespace, I need the declaration `hash_value<Monomial>>` above. So I can only define `MonomialToCoefficientMap` after defining `hash_value<Monomial>>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-:-KdYC2d6Ur4ki2ax6yo-:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 375 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-KdYKz6DwnPmtaomCvED:-KdYKz6E5QftSwJ2KmfY:b-vd02rf) ([raw file](https://github.com/robotlocomotion/drake/blob/f59c8eadf18b6e29ee4eaaa055660ea65e58fbfb/drake/common/monomial.cc#L375)):*
> ```cpp
>       // For each monomial in the dividend, compute the division from the
>       // dividend monomial by the divisor monomial.
>       const Monomial dividend_monomial(p1.first);
> ```

nit: `const Monomial&` works.

---

*[drake/common/monomial.h, line 344 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-KdYNn-2Qk2UNigu7DCB:-KdYNn-2Qk2UNigu7DCC:bo8paja) ([raw file](https://github.com/robotlocomotion/drake/blob/f59c8eadf18b6e29ee4eaaa055660ea65e58fbfb/drake/common/monomial.h#L344)):*
> ```objc
>  * Maps a monomial to a coefficient. This map can be used to represent a
>  * polynomial, such that the polynomial is
>  * sum map[key] * key
> ```

Probably better to use unicode here (+ some indentation)?
```
 *   ∑ map[key] * key
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-:-KdYO9Q07jnz9_7pJwi0:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 375 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-KdYKz6DwnPmtaomCvED:-KdYOZt1HoFvXM5jU9HE:b-lgr4d2) ([raw file](https://github.com/robotlocomotion/drake/blob/f59c8eadf18b6e29ee4eaaa055660ea65e58fbfb/drake/common/monomial.cc#L375)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit: `const Monomial&` works.
</blockquote></details>

Hmm, what is the advantage of calling this constructor with a const ref?

---

*[drake/common/monomial.h, line 344 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-KdYNn-2Qk2UNigu7DCB:-KdYPJywU52r6f8JSjUl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f59c8eadf18b6e29ee4eaaa055660ea65e58fbfb/drake/common/monomial.h#L344)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Probably better to use unicode here (+ some indentation)?
```
 *   ∑ map[key] * key
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249)*

**Comment by soonho-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 375 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5249#-KdYKz6DwnPmtaomCvED:-KdYQ5oyobPfgpExhDbn:b-550pon) ([raw file](https://github.com/robotlocomotion/drake/blob/f59c8eadf18b6e29ee4eaaa055660ea65e58fbfb/drake/common/monomial.cc#L375)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Hmm, what is the advantage of calling this constructor with a const ref?
</blockquote></details>

Ah. My mistake. Please forget about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5249)*

**Pull request merged**
