### PR TITLE
rigid_body_tree: Suppress deprecation warnings when constructing `bodies` and `frames`

### LINKED ISSUE #8184: Compiler warnings in RigidBodyTree when using GCC
Four warnings along the lines of this one: 

```
multibody/rigid_body_tree.cc:110:63: warning: 'RigidBodyTree::bodies' is deprecated: 
DRAKE DEPRECATED: Direct access to `bodies` has been deprecated, mutable access has been removed. Use `get_bodies` and `add_rigid_body` instead [-Wdeprecated-declarations]
     : collision_model_(drake::multibody::collision::newModel()) {
                                                               ^
In file included from multibody/rigid_body_tree.cc:1:0:
bazel-out/k8-dbg/bin/multibody/_virtual_includes/rigid_body_tree_cc/drake/multibody/rigid_body_tree.h:1526:67: note: declared here
   const std::vector>>& bodies{bodies_};
```

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Closes #8184

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8186)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.

\cc @jwnimmer-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8186#-:-L6IkbMLEElmbzZJyCju:bpri65n)*

**Comment by EricCousineau-TRI** [comment]
Confirmed that this suppresses the warnings with `--compiler=gcc-5`. (No change for default compiler, `clang`, on Ubuntu.)
Sorry about that!

**Comment by jamiesnape** [comment]
Any particular reason we cannot `-Werror` this particular class of warnings?

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8186#-:-L6Is9FxZk2oh2wfDOGO:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by jamiesnape** [comment]
(CDash is less unhappy: https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-xenial-gcc-bazel-experimental-release-10837&field2=buildstarttime&compare2=84&value2=now, just #8178 left)

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8186#-:-L6IuNsu_ZqfEdiCaYks:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
> Any particular reason we cannot -Werror this particular class of warnings?

I agree.  #8204.

**Pull request merged**
