### PR TITLE
Add pre-commit hook to reject submodule rewinds

### PR DESCRIPTION
**Pull request by bradking**
Since Git does not automatically update submodule checkouts after a checkout updates recorded submodule versions it is common for the work tree to end up with submodules locally modified.  It is easy for developers to accidentally commit a submodule rewind by using `git commit -a` or `git add -u; git commit` from such a state.

Help developers avoid this by adding a pre-commit hook to reject submodule rewinds.  On rejection, print instructions about what local operations to run to resolve the condition.

Install a `.git/hooks/pre-commit` hook into the local repository during CMake configuration.  Rather than trying to do all the checks directly, make it a simple launcher that loads a configured pre-commit hook from the checkout in the work tree.  This will allow us to add checks to pre-commit over time without re-installing the hook into an unversioned location or depending on CMake re-runs to update the installation.

See issue #2757.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2834)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2a6121NGUEqqpsgA2:-KN2a61529kjztuv_nN3:752644086) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/CMakeLists.txt#L45)):*
> ```CMake
> find_package(Git REQUIRED)
> 
> include(util/git/pre-commit.cmake)
> ```

@david-german-tri's comment in #2820 seems likely to apply here too. In fact, I'm going to reiterte it just because scope isolation of all the variables floating around in there would be good.

---

*[util/git/pre-commit.bash, line 42 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2bTCvup0vbGSGoRNv:-KN2bTCxHv8buIyi317x:335508390) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.bash#L42)):*
> ```Shell
> 
> to checkout the newer version of the submodule in your work tree.
> Then try the commit again.
> ```

Maybe mention how to keep the change if it's intended?

---

*[util/git/pre-commit.cmake, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2wEudOIwMOxfkhBZz:-KN2wEufIoDQ84JxAk99:617614808) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.cmake#L1)):*
> ```CMake
> set(_git_dir "${CMAKE_CURRENT_SOURCE_DIR}/.git")
> ```

FWIW, I've been trying to use `PROJECT_{SOURCE,BINARY}_DIR` instead...

---

*[util/git/pre-commit.in, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2xZmsDOeDE8hVmxtH:-KN2xZmtRwmixCyg_aTo:-1635979583) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.in#L5)):*
> ```
> 
> # Look up a configured pre-commit hook to call.
> chain="$(git config --get hooks.chain-pre-commit)" ||
> ```

Typo? Shouldn't this be `hooks.chain.pre-commit`? (Note `.` after `chain` vs. `-`). Also, I'm not sure I understand how this would work to chain multiple hooks. I wonder if something like KW's vision hooks `hooks.d` wouldn't be better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834)*

**Comment by bradking** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2a6121NGUEqqpsgA2:-KN35GCvyfmIa4wgJXcg:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/CMakeLists.txt#L45)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> @david-german-tri's comment in #2820 seems likely to apply here too. In fact, I'm going to reiterte it just because scope isolation of all the variables floating around in there would be good.
</details>
Done.

---

*[util/git/pre-commit.bash, line 42 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2bTCvup0vbGSGoRNv:-KN34qjqxvsWFUiaFY_V:-927536409) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.bash#L42)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Maybe mention how to keep the change if it's intended?
</details>
I'd like to keep the message as simple as possible.  The hook provides no escape hatch for this.  If someone is rewinding a submodule intentionally then we can presume they know enough to commit with `--no-verify`.

---

*[util/git/pre-commit.cmake, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2wEudOIwMOxfkhBZz:-KN34IuCfU4QHvDpwOvx:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.cmake#L1)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> FWIW, I've been trying to use `PROJECT_{SOURCE,BINARY}_DIR` instead...
</details>
Done.

---

*[util/git/pre-commit.in, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2xZmsDOeDE8hVmxtH:-KN34JS0nmS9wgQdKvaA:-635882687) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.in#L5)):*
This difference is intentional.  I'll add comments justifying the difference.  Also, these configuration options match Kitware's [GitSetup](https://gitlab.kitware.com/utils/gitsetup/tree/hooks) hooks branch behavior in case we ever switch to that in the future.

> I'm not sure I understand how this would work to chain multiple hooks.

This is the bare minimum to chain into a single hook provided by the project.  That hook can forward to a `hooks.d` if it wants.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[util/git/pre-commit.bash, line 42 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2bTCvup0vbGSGoRNv:-KN37QJAaB1x7qrwfwRB:-461815744) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.bash#L42)):*
<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> I'd like to keep the message as simple as possible.  The hook provides no escape hatch for this.  If someone is rewinding a submodule intentionally then we can presume they know enough to commit with `--no-verify`.
</details>
I have somewhat mixed feelings about not being able to skip the hook except with `--no-verify`. The danger there could be that this hook runs and aborts the commit early, and then `--no-verify` bypasses other hooks that would have caught some other problem.

(The copyright check hook that KW vision uses can be bypassed by setting an environment variable.)

---

*[util/git/pre-commit.in, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2xZmsDOeDE8hVmxtH:-KN38foMuyvxM4a-416H:247302277) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.in#L5)):*
<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> This difference is intentional.  I'll add comments justifying the difference.  Also, these configuration options match Kitware's [GitSetup](https://gitlab.kitware.com/utils/gitsetup/tree/hooks) hooks branch behavior in case we ever switch to that in the future.
> 
> > I'm not sure I understand how this would work to chain multiple hooks.
> 
> This is the bare minimum to chain into a single hook provided by the project.  That hook can forward to a `hooks.d` if it wants.
> 
</details>
So, to clarify... for now we only support one hook; if in the future we want more, we leave this hook alone but replace the One True Hook that it calls with a `hooks.d` style dispatcher?

I... guess that works, but it seems unnecessarily complex. OTOH I suppose we could instead replace this with a `hooks.d` style hook in the future.

(Lest this seem overly hypothetical, I could easily imagine adding style hooks, especially as we take `clang-format` as canonical. A hook to check for proper use of `#pragma once` would probably be good, also, and could be written without requiring external tools.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834)*

**Comment by bradking** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[util/git/pre-commit.bash, line 42 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2bTCvup0vbGSGoRNv:-KN3EfMy8HbuUx2lpcll:-1750681307) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.bash#L42)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I have somewhat mixed feelings about not being able to skip the hook except with `--no-verify`. The danger there could be that this hook runs and aborts the commit early, and then `--no-verify` bypasses other hooks that would have caught some other problem.
> 
> (The copyright check hook that KW vision uses can be bypassed by setting an environment variable.)
</details>
We can always add a bypass option later.  Right now I just want to protect developers from this mistake.

---

*[util/git/pre-commit.in, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN2xZmsDOeDE8hVmxtH:-KN3EmqUJjiBBOna4ikV:-1541497960) ([raw file](https://github.com/robotlocomotion/drake/blob/4d22700152b0720f1d5170966327f00a84378f26/util/git/pre-commit.in#L5)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> So, to clarify... for now we only support one hook; if in the future we want more, we leave this hook alone but replace the One True Hook that it calls with a `hooks.d` style dispatcher?
> 
> I... guess that works, but it seems unnecessarily complex. OTOH I suppose we could instead replace this with a `hooks.d` style hook in the future.
> 
> (Lest this seem overly hypothetical, I could easily imagine adding style hooks, especially as we take `clang-format` as canonical. A hook to check for proper use of `#pragma once` would probably be good, also, and could be written without requiring external tools.)
</details>
A `hooks.d` dispatcher will be much more complicated than this simple chaining hook.  Since`.git/hooks/pre-commit` is not part of the work tree and does not change when different versions are checked out we should keep it as simple as possible and update it as infrequently as possible.  I see no reason that the multi-hook dispatcher shouldn't live in the work tree with the hooks it loads and be versioned with the rest of the source tree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[CMakeLists.txt, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN3I1x0dThV6V5vTiLi:-KN3I1x2lIATwt5a8s2L:595099221) ([raw file](https://github.com/robotlocomotion/drake/blob/6cf893b4b498a20a884865284bdaff027b122530/CMakeLists.txt#L46)):*
> ```CMake
> 
> include(util/git/hooks.cmake)
> drake_git_hooks()
> ```

This name seems a bit odd; maybe `drake_setup_git_hooks`? :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834)*

**Comment by bradking** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[CMakeLists.txt, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN3I1x0dThV6V5vTiLi:-KN3Kh5ANdtDsvpYAoCJ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6cf893b4b498a20a884865284bdaff027b122530/CMakeLists.txt#L46)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> This name seems a bit odd; maybe `drake_setup_git_hooks`? :smile:
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-:-KN3LJvQcEWciiHxxNCu:1417088721)*

**Comment by bradking** [comment]
Assigned to @david-german-tri for platform review and integration.

**Comment by david-german-tri** [comment]
Apologies for the delay - I will get to this tomorrow morning.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-:-KN4BxRACUwTuusLDvSf:-1332378289)*

**Comment by jamiesnape** [comment]
Ignore the "default" and "continuous-integration/jenkins/pr/mac" builds.

**Comment by david-german-tri** [comment]
Locally, I ran `cmake` to install this hook, and then performed the following tests.

* Roll back `externals/lcm` to an older commit.  The hook objected.  I followed its instructions to clean up, and that worked fine.

* Make some additional commits to `externals/lcm`, then commit the updated SHA to Drake.  The hook did not object.

So, that all seems good.  I'd appreciate some additional documentation - see comments below.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[.hooks-config, line 1 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8Tu76Iqq2WdS9NHOd:-KN8Tu776eCHq-5PwRNS:-196778613) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/.hooks-config#L1)):*
> ```
> [hooks "chain"]
> ```

A file comment explaining that CMake installs a pre-commit hook that parses this file to obtain the actual scripts to run would be helpful. 

---

*[util/git/hooks.cmake, line 1 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8RSWAB1Idr1wu8UME:-KN8RSWB-uU1EQrcBgwR:1934453056) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/hooks.cmake#L1)):*
> ```CMake
> function(drake_setup_git_hooks)
> ```

In #2820, @mwoehlke-kitware is creating the top-level `cmake` directory.  Perhaps that would be a logical place for this too?

---

*[util/git/pre-commit.bash, line 1 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8por1Z75MPGow6tmq:-KN8por1Z75MPGow6tmr:650208193) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/pre-commit.bash#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

A file-level comment explaining what this script enforces would be useful for future readers.

---

*[util/git/pre-commit.bash, line 21 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8pU3n81o843xa-Lux:-KN8ircavP_ekkp6ssnH:-1964938682) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/pre-commit.bash#L21)):*
> ```Shell
> 
> filter_diffs_module() {
>   grep '^...... 160000'
> ```

I can see that this squares with the output of `git diff-index`, but I have no idea what's magic about `160000`.  Could you add a comment?

---

*[util/git/pre-commit.bash, line 27 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8qhSP_XYk_3GWYulz:-KN8qhSP_XYk_3GWYum-:-1302225359) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/pre-commit.bash#L27)):*
> ```Shell
>   readonly parent_name="$1"
>   readonly base="$(GIT_DIR="$file/.git" \
>                    git merge-base "$src_obj" "$dst_obj" 2>/dev/null)" || base=''
> ```

This is some advanced git magic.  Could you add a comment explaining what it does?

---

*[util/git/pre-commit.bash, line 42 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8rjMvPY9PBKPZ9eYp:-KN8rjMvPY9PBKPZ9eYq:1704822769) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/pre-commit.bash#L42)):*
> ```Shell
> 
> to checkout the newer version of the submodule in your work tree.
> Then try the commit again.
> ```

Please also add instructions here to override the hook.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-:-KN8r6ccVujrZLUS-QRe:-1422741927)*

**Comment by bradking** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[.hooks-config, line 1 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8Tu76Iqq2WdS9NHOd:-KNCp3nNsotSzDiN4nsd:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/.hooks-config#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> A file comment explaining that CMake installs a pre-commit hook that parses this file to obtain the actual scripts to run would be helpful. 
</details>
Done.

---

*[util/git/hooks.cmake, line 1 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8RSWAB1Idr1wu8UME:-KNCqZaa-X-OlHmmTMO5:-565784362) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/hooks.cmake#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> In #2820, @mwoehlke-kitware is creating the top-level `cmake` directory.  Perhaps that would be a logical place for this too?
</details>
Okay, I've renamed the entire `util/git` directory to `cmake/git`.  That will nicely combine with the other place and share a top-level directory name.

---

*[util/git/pre-commit.bash, line 1 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8por1Z75MPGow6tmq:-KNCqyxhD-j4ZMpPFp4O:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/pre-commit.bash#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> A file-level comment explaining what this script enforces would be useful for future readers.
</details>
Done.

---

*[util/git/pre-commit.bash, line 21 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8pU3n81o843xa-Lux:-KNCrPLC4fW_AP1z_KtV:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/pre-commit.bash#L21)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I can see that this squares with the output of `git diff-index`, but I have no idea what's magic about `160000`.  Could you add a comment?
</details>
Done.

---

*[util/git/pre-commit.bash, line 27 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8qhSP_XYk_3GWYulz:-KNCsr_SB_Qr5mYAXRrN:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/pre-commit.bash#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This is some advanced git magic.  Could you add a comment explaining what it does?
</details>
Done.

---

*[util/git/pre-commit.bash, line 42 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KN8rjMvPY9PBKPZ9eYp:-KNCyTicw2yG1kAU5y_d:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/39f4b0a38416bf5df98be31a2f4b7103b21450e3/util/git/pre-commit.bash#L42)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please also add instructions here to override the hook.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/git/pre-commit.bash, line 2 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-KNDrgvmgFlOCdh8SQ7X:-KNDrgvmgFlOCdh8SQ7Y:1328818956) ([raw file](https://github.com/robotlocomotion/drake/blob/c07ba35b46b04d84b824b723d10e27eaed474c97/cmake/git/pre-commit.bash#L2)):*
> ```Shell
> #!/usr/bin/env bash
> # This is a local Git pre-commit hook to enforce the following:"
> ```

BTW, trailing quote

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-:-KNDsPZ4FCcfXHKvCeKP:1417088721)*

**Comment by david-german-tri** [comment]
One comment about a typo.  Feel free to merge this yourself with or without resolving that.

---

Reviewed 1 of 6 files at r2, 8 of 8 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-:-KNDsTHmukRPm_OfvHY_:-1921784389)*

**Comment by bradking** [comment]
Thanks.  Typo fixed.

---

Reviewed 1 of 8 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-:-KNDuI4JWPQMoFjfQHC6:181944758)*

**Comment by david-german-tri** [comment]
I leave it to you to press the green button whenever you're ready.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2834#-:-KNEcAzV9kXKmEUISbKF:1710956126)*

**Pull request merged**
