### PR TITLE
Add if-then-else and cond to symbolic classes

### PR DESCRIPTION
**Pull request by soonho-tri**
The first commit c07b032 is to restructure code base to avoid the circular dependency between `symbolic::Expression` and `symbolic::Formula`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4104)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , both reviews please.
+@david-german-tri , both reviews please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-:-KWE7X5amYzATR7Lr_9I:b709r0f)*

**Comment by soonho-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWEDVt1dj20ov4FXzYv:-KWEDVt1dj20ov4FXzYw:bgzfpmw) (no related file):*
@david-german-tri , I'll double-check hash values of `Expression`s and `Formula`s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 7 files at r2.
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 944 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWEGq-eO0TIHGpoxr1_:-KWEGq-fMLgt2RFuPjE-:borlm2c) ([raw file](https://github.com/robotlocomotion/drake/blob/f85e32cd9a99a12971ccbd98e100358895a290f7/drake/common/symbolic_expression_cell.cc#L944)):*
> ```cpp
>                                            const Expression& e_then,
>                                            const Expression& e_else)
>     : ExpressionCell{ExpressionKind::IfThenElse,
> ```

from f2f: shouldn't this contain the kind?  Do other expressions?

---

*[drake/common/test/symbolic_expression_test.cc, line 1124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWEHDgv8iDisZhqmtOC:-KWEHDgv8iDisZhqmtOD:b-nbn69e) ([raw file](https://github.com/robotlocomotion/drake/blob/f85e32cd9a99a12971ccbd98e100358895a290f7/drake/common/test/symbolic_expression_test.cc#L1124)):*
> ```cpp
> 
> TEST_F(SymbolicExpressionTest, IfThenElse1) {
>   // should be simplified to 1.0 since (x  1.0 > x) => true.
> ```

missing + sign?

---

*[drake/common/test/symbolic_expression_test.cc, line 1128 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWEHFx37xLlpd6BsYnD:-KWEHAx4QEz7-8PQTU-Z:b-nbn69e) ([raw file](https://github.com/robotlocomotion/drake/blob/f85e32cd9a99a12971ccbd98e100358895a290f7/drake/common/test/symbolic_expression_test.cc#L1128)):*
> ```cpp
>   EXPECT_PRED2(ExpEqual, ite1, 1.0);
> 
>   // should be simplified to 0.0 since (x > x  1.0) => false.
> ```

missing + sign?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by david-german-tri** [comment]
Reviewed 9 of 9 files at r1.
Review status: 3 of 10 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by david-german-tri** [comment]
:lgtm: aside from open threads

---

Review status: 3 of 10 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-:-KWETx5Nce_oUjAJnOlj:b-9zavfy)*

**Comment by soonho-tri** [comment]
*[drake/common/symbolic_expression_cell.cc, line 944 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWEGq-eO0TIHGpoxr1_:-KWElAETIFeO5siJmGiz:bjidd3v) ([raw file](https://github.com/robotlocomotion/drake/blob/f85e32cd9a99a12971ccbd98e100358895a290f7/drake/common/symbolic_expression_cell.cc#L944)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> from f2f: shouldn't this contain the kind?  Do other expressions?
</details>
I double-checked. It's taken care by the constructor of `ExpressionCell`
```c++
ExpressionCell::ExpressionCell(ExpressionKind const k, size_t const hash)
    : kind_{k}, hash_{hash_combine(static_cast<size_t>(kind_), hash)} {}
```

https://github.com/RobotLocomotion/drake/blob/master/drake/common/symbolic_expression.cc#L425-L426

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by soonho-tri** [comment]
Review status: 2 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/test/symbolic_expression_test.cc, line 1124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWEHDgv8iDisZhqmtOC:-KWEltwAcJi9Y66qXa-d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f85e32cd9a99a12971ccbd98e100358895a290f7/drake/common/test/symbolic_expression_test.cc#L1124)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> missing + sign?
</details>
Done.

---

*[drake/common/test/symbolic_expression_test.cc, line 1128 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWEHFx37xLlpd6BsYnD:-KWEluLd4VqiWtfBWg6d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f85e32cd9a99a12971ccbd98e100358895a290f7/drake/common/test/symbolic_expression_test.cc#L1128)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> missing + sign?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r3, 4 of 7 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-:-KWEnTsYOzyhb0R6nfn1:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Checkpoint on the periphery stuff.... will review the new feature next.

---

Reviewed 9 of 9 files at r1, 1 of 8 files at r3, 2 of 7 files at r7, 2 of 3 files at r8, 2 of 3 files at r9.
Review status: 8 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/symbolic_expression.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWFyFzarDo_soqpzeMk:-KWFyFzb11UrpkAksGwC:b5s7l18) ([raw file](https://github.com/robotlocomotion/drake/blob/c07b032771e3b5e1678b1c71e0898aa70e16d3a0/drake/common/symbolic_expression.h#L55)):*
> ```objc
> bool operator<(ExpressionKind k1, ExpressionKind k2);
> 
> class ExpressionCell;
> ```

Now that this class lives in another file, please comment here where the class can be found (not using Doxygen style).

---

*[drake/common/symbolic_expression.h, line 17 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG1SvqUu0h7nvHDhJx:-KWG1SvqUu0h7nvHDhJy:bx4924w) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression.h#L17)):*
> ```objc
> #include "drake/common/number_traits.h"
> #include "drake/common/symbolic_environment.h"
> #include "drake/common/symbolic_formula.h"
> ```

This is an include cycle, and I suppose unwanted given the forward declaration below?

---

*[drake/common/symbolic_expression.h, line 284 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG1sjUJHztYmRyz-ao:-KWG1sjUJHztYmRyz-ap:b-588fy0) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression.h#L284)):*
> ```objc
> DRAKE_EXPORT Expression min(const Expression& e1, const Expression& e2);
> DRAKE_EXPORT Expression max(const Expression& e1, const Expression& e2);
> DRAKE_EXPORT Expression if_then_else(const Formula& f_cond,
> ```

Please add API comment -- this is not a cstdlib primitive, it's one we've invented.

In the API doc, also consider a citation and compare / contrast with the ternary conditional operator in C++.

---

*[drake/common/symbolic_expression.h, line 301 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG2ewyVn2QpZ4CWPjP:-KWG2ewzgEd1wNIs9XRI:bvz7wpk) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression.h#L301)):*
> ```objc
>   true; else if @c cond_2 is true then @c exp_2; ... ; else if @c cond_n is true
>   then @c exp_n. If none of the conditions are true, it returns @c exp_{n+1}.
>  */
> ```

BTW Did you check that this doxygen comes out okay?  There are two functions declarations immediately below, and it perhaps only grabs the first one?

---

*[drake/common/symbolic_expression_cell.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWFxSJaAYeGP3Gh0SH0:-KWFxSJbKj0GwJtdzD1O:b2lg6dv) ([raw file](https://github.com/robotlocomotion/drake/blob/c07b032771e3b5e1678b1c71e0898aa70e16d3a0/drake/common/symbolic_expression_cell.cc#L17)):*
> ```cpp
> #include "drake/common/hash.h"
> #include "drake/common/symbolic_environment.h"
> #include "drake/common/symbolic_expression_cell.h"
> ```

Shouldn't this one be first (atop the file)?

---

*[drake/common/symbolic_formula.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWFyX7OZ8Pdi_PwA4ME:-KWFyX7OZ8Pdi_PwA4MF:b5s7l18) ([raw file](https://github.com/robotlocomotion/drake/blob/c07b032771e3b5e1678b1c71e0898aa70e16d3a0/drake/common/symbolic_formula.h#L39)):*
> ```objc
> bool operator<(FormulaKind k1, FormulaKind k2);
> 
> class FormulaCell;
> ```

Now that this class lives in another file, please comment here where the class can be found (not using Doxygen style).

---

*[drake/common/symbolic_formula.h, line 40 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG2I508upu9QlARd_A:-KWG2I508upu9QlARd_B:bkii7cn) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_formula.h#L40)):*
> ```objc
> 
> class FormulaCell;
> class Expression;
> ```

`symbolic_expression.h` is directly `#included` above, so I'm unclear why this is needed?

---

*[drake/common/symbolic_formula_cell.h, line 22 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG3Ox1DERxCXxce9ON:-KWG3Ox1DERxCXxce9OO:b8tytvp) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_formula_cell.h#L22)):*
> ```objc
> 
> class Expression;
> class Formula;
> ```

These are both `#included` above, so I'm unclear why the fwds are needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-:-KWG3Zs-F1Te_sfkUrkL:boymc4n)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 7 files at r7, 1 of 3 files at r8, 1 of 3 files at r9.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG7zBgSWoPTCRugl7s:-KWG7zBhkvgsG3C-YcSx:b-uoizus) (no related file):*
BTW So this PR is probably fine as-is, but I don't want to wait too long before adding double and AutoDiff operators for `if_then_else` and `cond`, to make sure that these functions are sane for generic programming.  Is that on deck soon?

---

*[drake/common/symbolic_expression.h, line 284 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG1sjUJHztYmRyz-ao:-KWG6FNqT0cbsHLLyoq-:bgz72iq) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression.h#L284)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Please add API comment -- this is not a cstdlib primitive, it's one we've invented.
> 
> In the API doc, also consider a citation and compare / contrast with the ternary conditional operator in C++.
</details>
Also consider encouraging users to use `min`, `max`, `abs` instead of ITE.

---

*[drake/common/symbolic_expression_cell.cc, line 950 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG50xqp_EJfWjmWejJ:-KWG50xqp_EJfWjmWejK:b-o14qxj) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression_cell.cc#L950)):*
> ```cpp
>   Variables ret{f_cond_.GetFreeVariables()};
>   const Variables& vars_in_then = e_then_.GetVariables();
>   ret.insert(vars_in_then.begin(), vars_in_then.end());
> ```

BTW https://github.com/RobotLocomotion/drake/blob/0c23a1e73759a5399d8be9213be0c81e005b7744/drake/common/symbolic_variables.h#L96-L97

There's a nice overload for this (META).

---

*[drake/common/symbolic_expression_cell.h, line 25 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG3ki9v_eF4rYrO7Ym:-KWG3kiBslcbyCYS4Rmz:b78k4yv) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression_cell.h#L25)):*
> ```objc
> 
> class Expression;
> class Formula;
> ```

These are both #included above, so I'm unclear why the fwds are needed?

---

*[drake/common/test/symbolic_expression_test.cc, line 1167 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG7luZLP3lHdxyvjar:-KWG7lu_79mzhLBVVOBq:b-1oturj) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/test/symbolic_expression_test.cc#L1167)):*
> ```cpp
> 
> TEST_F(SymbolicExpressionTest, Cond2) {
>   // clang-format off
> ```

FYI lol at clang-format and lisp fighting.  That makes sense, I guess.

---

*[drake/common/test/symbolic_expression_test.cc, line 1170 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG6q9Tuw5YfveOQETx:-KWG6q9UMFmJSgAfFUR_:b-vzwsch) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/test/symbolic_expression_test.cc#L1170)):*
> ```cpp
>   const Expression e{cond(x_ >= 10, 10.0,
>                           x_ >= 5,  Expression{5.0},
>                           x_ >= 2,  Expression{2.0},
> ```

BTW Does the compiler demand the `Expression` construction here, and not conversion?  That's too bad.

Would making the f1,e1 a std::pair be any better (for type coercion and clang formatting?)
```
cond({x >= 10, 10.0},
     {x >= 5, 5.0},
     0.0)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by soonho-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG7zBgSWoPTCRugl7s:-KWGRa5R3ZyGNxKq6LxH:b-rb67sc) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW So this PR is probably fine as-is, but I don't want to wait too long before adding double and AutoDiff operators for `if_then_else` and `cond`, to make sure that these functions are sane for generic programming.  Is that on deck soon?
</details>
I'll do that after this PR. I wanted to ask you the best place (in terms of file) to put `if_then_else` and `cond` for each `ScalarType`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1167 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG7luZLP3lHdxyvjar:-KWGS1V3_qEsDVUdgRzw:b8yjkgp) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/test/symbolic_expression_test.cc#L1167)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI lol at clang-format and lisp fighting.  That makes sense, I guess.
</details>
LISP FTW!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1170 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG6q9Tuw5YfveOQETx:-KWGS4sT7Mt6kMK9EFb3:b-naajws) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/test/symbolic_expression_test.cc#L1170)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Does the compiler demand the `Expression` construction here, and not conversion?  That's too bad.
> 
> Would making the f1,e1 a std::pair be any better (for type coercion and clang formatting?)
> ```
> cond({x >= 10, 10.0},
>      {x >= 5, 5.0},
>      0.0)
> ```
</details>
Ooops, I wrote this part before I made `Expression(double)` non-explicit. I'll change the test code soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by soonho-tri** [comment]
Review status: 2 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/common/symbolic_expression.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWFyFzarDo_soqpzeMk:-KWHeHG4VOwetinIV_Wy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c07b032771e3b5e1678b1c71e0898aa70e16d3a0/drake/common/symbolic_expression.h#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Now that this class lives in another file, please comment here where the class can be found (not using Doxygen style).
</details>
Done.

---

*[drake/common/symbolic_expression.h, line 17 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG1SvqUu0h7nvHDhJx:-KWHRS4PXbY6-atrvT1i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression.h#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This is an include cycle, and I suppose unwanted given the forward declaration below?
</details>
Done.

---

*[drake/common/symbolic_expression.h, line 284 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG1sjUJHztYmRyz-ao:-KWHXlUaZlW7LJG5LF1n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression.h#L284)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Also consider encouraging users to use `min`, `max`, `abs` instead of ITE.
</details>
Done.

---

*[drake/common/symbolic_expression.h, line 301 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG2ewyVn2QpZ4CWPjP:-KWHbpCG1VM8ngJhQgJR:bh7rl9k) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression.h#L301)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Did you check that this doxygen comes out okay?  There are two functions declarations immediately below, and it perhaps only grabs the first one?
</details>
Surprisingly, it's bounded to the second one.

Now, I'm using 'Member groups` feature documented in http://www.stack.nl/~dimitri/doxygen/manual/grouping.html. It does not do exactly what I want, but it's better I think.

---

*[drake/common/symbolic_expression_cell.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWFxSJaAYeGP3Gh0SH0:-KWHcF9Ux5OGb03k0gf9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c07b032771e3b5e1678b1c71e0898aa70e16d3a0/drake/common/symbolic_expression_cell.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Shouldn't this one be first (atop the file)?
</details>
Done.

---

*[drake/common/symbolic_expression_cell.cc, line 950 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG50xqp_EJfWjmWejJ:-KWHcNd6exaZBoLt45Wu:b2gik8l) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression_cell.cc#L950)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW https://github.com/RobotLocomotion/drake/blob/0c23a1e73759a5399d8be9213be0c81e005b7744/drake/common/symbolic_variables.h#L96-L97
> 
> There's a nice overload for this (META).
</details>
Done. (META)

---

*[drake/common/symbolic_expression_cell.h, line 25 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG3ki9v_eF4rYrO7Ym:-KWHcTRbyMUgy0oBY0pi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_expression_cell.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> These are both #included above, so I'm unclear why the fwds are needed?
</details>
Done.

---

*[drake/common/symbolic_formula.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWFyX7OZ8Pdi_PwA4ME:-KWHchFB6oqU69KIvxHJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c07b032771e3b5e1678b1c71e0898aa70e16d3a0/drake/common/symbolic_formula.h#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Now that this class lives in another file, please comment here where the class can be found (not using Doxygen style).
</details>
Done.

---

*[drake/common/symbolic_formula.h, line 40 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG2I508upu9QlARd_A:-KWHch_xGCR7QAEI07hd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_formula.h#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `symbolic_expression.h` is directly `#included` above, so I'm unclear why this is needed?
</details>
Done.

---

*[drake/common/symbolic_formula_cell.h, line 22 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG3Ox1DERxCXxce9ON:-KWHcpo0RMR23zxAF7m-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87d9454cd1fe9dc66c7e50cf82f883d2e5d262f6/drake/common/symbolic_formula_cell.h#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> These are both `#included` above, so I'm unclear why the fwds are needed?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-KWG7zBgSWoPTCRugl7s:-KWIJHtqoECmPZjIXC2k:bdr6z2j) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> I'll do that after this PR. I wanted to ask you the best place (in terms of file) to put `if_then_else` and `cond` for each `ScalarType`.
</details>
Great (marking resolved).

- `AutoDiff` ITE operator goes in `common/autodiff_overloads.h`.
- `FunctionalForm` ITE operator _would_ go in `common/functional_form.h`, but I think it can't easily get ITE unless we overload the comparisons there.  Maybe it gets a TODO explaining the work it would take?  It would be a bunch of verbiage, but conceptually easy.  Not sure how valuable it is.
- `double` I don't think we have a scalartype home for, so will need a new header in common.  Possibly it could even take on a generic `cond` implementation to share that code?  I don't have a good filename suggestion handy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4104#-:-KWIMDThzOXs9jD4_vS4:bnfp4nl)*

**Pull request merged**
