### PR TITLE
Remove drake/regtests.

### LINKED ISSUE #5216: Re-enable visualizer_startup_test.py
The `drake/regtests/visualizer_startup_test.py` sayeth:
```
# TODO(patmarion)
# The visualization test is currently disabled due to a recent change in
# dependencies.  Now director depends on drake, so the drake-visualizer
# program is compiled after drake.  The ctest scripts running continuous
# integration will be updated to run director tests which will cover the
# visualizer.  Afterward, drake developers will decide whether we remove
# this test here or add new support for running tests after superbuild.
```

So, should we re-enable this test, or remove it?

### PR DESCRIPTION
**Pull request by david-german-tri**
@patmarion for feature review.

Fixes #5216.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5217)

### CODE REVIEW

**Comment by patmarion** [comment]
LGTM

**Comment by david-german-tri** [comment]
If you don't :lgtm: as an emoji, Reviewable doesn't count it :-D

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5217#-:-KdD9yIPb8JejDC6lDIo:by40g5l)*

**Comment by patmarion** [comment]
good to know, thanks!  :lgtm:

**Comment by patmarion** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5217#-:-KdDAVDCJ_IS8AVZDyn7:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri platform :lgtm:.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5217#-:-KdDAGBgQqXLzpt_tldE:bwt0yrs)*

**Pull request merged**
