### PR TITLE
[proximity] Improve/fix obb hierarchy construction

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
We fit an OBB to a mesh (or cluster of features) using PCA analysis. It provides a reasonable estimate of a good OBB orientation. We have an optimization step that attempts to create a *better* orientation (and, thereby, a better fit). To optimize, we compute the partial derivative of OBB volume w.r.t. orientation of the box.

Previously, it was possible for that partial to have *zero* magnitude. This led to failures because the optimization algorithm would end up with infinite values (which could, in turn, lead to NaN values). So, we have to protect ourselves against that.

But beyond that, if the magnitude of the partial derivative is sufficiently small, there's really very little value in trying to further optimize the fit. So, we apply a threshold test for optimization to skip the effort if it doesn't seem worth it, and protect ourselves from introducing bad inf and NaN values.

Incidentally, also moved the constructor to the .cc file where it belonged all along.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17937)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@damrongguoy for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17937#-:-NC5vOXa4I2URvl2wJJZ:b3ljvfd)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17937#-:-NC6WOezA9PCrmtGtWGL:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
TRI is closed on Friday (perhaps we should find a non-TRI platform reviewer on Friday). Monday platform reviewer is @seancurtis-tri  the author.  Tuesday's platform reviewer is @rpoyner-tri.

+@rpoyner-tri for Tuesday's platform review, please.  (Please feel free to change if someone could pitch in earlier).
 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17937#-:-NC6WgxH1WOPDXFSTYAc:b-8gtzfz)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
cc: @nepfaff 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17937#-:-NC6XQwVEFbn_Tj7CWya:buh7j35)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by sherm1 — COMMENTED** [review]
-@rpoyner-tri +@sherm1 for platform review
+(release notes: fix) 
+(type: bug) 

:lgtm: with one comment suggestion

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17937#-:-NC7C257B4Z28YIcg7gC:b-z1mejm)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/obb.cc` line 344 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17937#-NC7Aeez9R0V_KzLVFq2:-NC7Aeez9R0V_KzLVFq3:bfweikc) ([raw file](https://github.com/robotlocomotion/drake/blob/96459b9ba89704dc5b9eb6b5f55d359d01ac7ba0/geometry/proximity/obb.cc#L344)):*
> ```cpp
>   // If the gradient doesn't have an appreciable effect, skip the work to
>   // optimize it further. The threshold given is based on the idea that we'd
>   // like the box to change at least 1 mm in measure. Since the volume is a
> ```

BTW this seems incomplete. I think it means "at least 1 mm for a 1 radian change in orientation". I know technically radians are unitless but it seems worth mentioning that we're talking about a nearly 60 degree change! Consider saying something about that.

**Pull request merged**
