### PR TITLE
Update drake-visualizer and vtk packages

### PR DESCRIPTION
**Pull request by jamiesnape**
Apparently Mac packages are broken, so this is now high priority, I think.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9938)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review and local testing. FYI @RussTedrake.

**Comment by jwnimmer-tri** [comment]
I started to platform review it, but seeing the changes I think we need to +@EricCousineau-TRI for Ubuntu feature review and platform review, please.

**Comment by jamiesnape** [comment]
BTW We can defer actually using the vendored LCM Python if we prefer; it is not necessary for the present. This PR got accelerated as the Mac packages broke.

**Comment by jamiesnape** [comment]
Should be unchanged.

**Comment by EricCousineau-TRI** [comment]
Yup, all looks good to me.

**Comment by jwnimmer-tri** [comment]
Oops.. Changes to `//tools/workspace` should be tested pre-merge on bionic as well (this PR broke bionic).

**Pull request merged**
