### PR TITLE
py deprecation: Expose `deprecated_callable` as decorator

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Add example

Motivated by #15875

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15877)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Thanks, Eric!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15877#-:-MlFvreQ18tWJ2aQkR13:bnmvrzs)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15877#-:-MlG6IK55Cyj_W5AAkXs:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15877#-MlG65BM03La2_1-L2Pz:-MlG65BNCo4ENMD4Umlc:bma0xel) (no related file):*
BTW, would it be possible down the road to use type introspection so that the `deprecated` name could cover both descriptors and free callables? Not blocking on this PR, but food for thought. By comparison with c++, `DRAKE_DEPRECATED` works on a variety of names, though the syntax placement can be obscure, say, for aliases with `using` or `typedef`.

---

**Review by rpoyner-tri — COMMENTED** [review]
@ericcousineau-tri does this need a not-me platform reviewer, or is single review ok? Up to you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15877#-:-MlGDnqT3PKeG4nn5ROC:bwc8sf5)* status: needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
Yes, new infrastructure intended for all developers to use should have two reviewers, for a clarity check if nothing else.

+@sherm1 for review, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15877)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @EricCousineau-TRI and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15877#-MlG65BM03La2_1-L2Pz:-MlGUoOs5zCUboV1XvDV:b-ux7wlz) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, would it be possible down the road to use type introspection so that the `deprecated` name could cover both descriptors and free callables? Not blocking on this PR, but food for thought. By comparison with c++, `DRAKE_DEPRECATED` works on a variety of names, though the syntax placement can be obscure, say, for aliases with `using` or `typedef`.
</blockquote></details>

Working: Good point. Let me try this out now; if it doesn't work out, I'll add a TODO.

---

**Review by sherm1 — COMMENTED** [review]
:lgtm: with a request for clarification

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15877#-:-MlGiCAWA4BUhNPwlR6z:bz1p6nm)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/common/deprecation.py, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15877#-MlGgnxs-_C8KthpHBTe:-MlGgnxs-_C8KthpHBTf:b-ofyc0d) ([raw file](https://github.com/robotlocomotion/drake/blob/593c32608db5c67a862100a2b03dbccb6222138c/bindings/pydrake/common/deprecation.py#L239)):*
> ```Python
> def deprecated_callable(message, *, date=None):
>     """
>     Deprecates a callable (a free function or class definition itself) by
> ```

minor: I'm not sure what you mean by "class definition itself". That doesn't seem like a "callable" to me, but I probably don't have a good grasp of Python's meaning for that term. Can you clarify that in text or with an example?
___
*[bindings/pydrake/common/deprecation.py, line 259 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15877#-MlGhBwZ0XUb5Qo3IABy:-MlGhBwZ0XUb5Qo3IABz:b-pmn8yw) ([raw file](https://github.com/robotlocomotion/drake/blob/593c32608db5c67a862100a2b03dbccb6222138c/bindings/pydrake/common/deprecation.py#L259)):*
> ```Python
>         my_alias = deprecated_callable(
>             "Please use `my_original` instead", date="2038-01-19"
>         )(my_original)
> ```

BTW this example is great for me -- thanks!
___
*[bindings/pydrake/common/test/deprecation_test.py, line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15877#-MlGhQl_6zJZQZS1Dibf:-MlGhQl_6zJZQZS1Dibg:bsm9nhm) ([raw file](https://github.com/robotlocomotion/drake/blob/593c32608db5c67a862100a2b03dbccb6222138c/bindings/pydrake/common/test/deprecation_test.py#L160)):*
> ```Python
>         higher-level API.
>         """
>         import deprecation_example as mut
> ```

BTW what's "mut"? My first thought was "mutable" but that obviously isn't right! "module under test"?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15877)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15877#-MlG65BM03La2_1-L2Pz:-MlGhpGkAgUJRBG5dRe1:b-iwheh3) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Good point. Let me try this out now; if it doesn't work out, I'll add a TODO.
</blockquote></details>


OK Had tried for about 20min, but I'm not sure how to distinguish:
https://github.com/EricCousineau-TRI/repro/blob/ada2ff7be51cf205e45520b61cf72a4ab3b15ac9/python/check_descriptor_vs_func.py

Leaving as TODO.

---
___
*[bindings/pydrake/common/deprecation.py, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15877#-MlGgnxs-_C8KthpHBTe:-MlGm66g6EMQFcwuBabq:b-nveu7s) ([raw file](https://github.com/robotlocomotion/drake/blob/593c32608db5c67a862100a2b03dbccb6222138c/bindings/pydrake/common/deprecation.py#L239)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I'm not sure what you mean by "class definition itself". That doesn't seem like a "callable" to me, but I probably don't have a good grasp of Python's meaning for that term. Can you clarify that in text or with an example?
</blockquote></details>

Done. "type/class object" is more accurate, while staying concise.
___
*[bindings/pydrake/common/deprecation.py, line 259 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15877#-MlGhBwZ0XUb5Qo3IABy:-MlGmIwF0YUJpfYEABiP:b-m78k76) ([raw file](https://github.com/robotlocomotion/drake/blob/593c32608db5c67a862100a2b03dbccb6222138c/bindings/pydrake/common/deprecation.py#L259)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this example is great for me -- thanks!
</blockquote></details>

OK Welcome!
___
*[bindings/pydrake/common/test/deprecation_test.py, line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15877#-MlGhQl_6zJZQZS1Dibf:-MlGm9xl6Zyp23vjraax:b-jts007) ([raw file](https://github.com/robotlocomotion/drake/blob/593c32608db5c67a862100a2b03dbccb6222138c/bindings/pydrake/common/test/deprecation_test.py#L160)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW what's "mut"? My first thought was "mutable" but that obviously isn't right! "module under test"?
</blockquote></details>

OK Yup! It's used elsewhere, not sure where to document.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15877)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
