### PR TITLE
Add double-negation simplification for symbolic formulas

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6214)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@ericcousineau-tri , feature-review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6214#-:-KlU3H3eSu0SMXvqKnoa:bcq2m3k)*

**Comment by soonho-tri** [comment]
I think -@EricCousineau-TRI is busy. 
+@nikos-tri , could you feature-review this?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6214#-:-KlVaQ50ARPzCv5vODgZ:b-naxrpw)*

**Comment by nikos-tri** [comment]
Got it, reviewing now.

**Comment by nikos-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6214#-:-KlVhbCrHVw34tV5O1TB:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , platform-review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6214#-:-KlVmm8YxXazPyZIbUiF:bq8ci7j)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.cc, line 218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6214#-KlVtORhlWg05pfEKTZ8:-KlVtORhlWg05pfEKTZ9:b-uotuiw) ([raw file](https://github.com/robotlocomotion/drake/blob/0af40079213ea3e68c151d3f3781776cf11c749a/drake/common/symbolic_formula.cc#L218)):*
> ```cpp
>     return Formula::True();
>   }
>   // Simplification: ¬(¬f₁)  =>  f₁
> ```

The `symbolic_formula.h` lists all of the simplifications; this one should be added to that list, I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6214#-:-KlVuyPB9Bp9jRo-v5Hp:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.cc, line 218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6214#-KlVtORhlWg05pfEKTZ8:-KlVyRyqePHI7Ia6_yrk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0af40079213ea3e68c151d3f3781776cf11c749a/drake/common/symbolic_formula.cc#L218)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `symbolic_formula.h` lists all of the simplifications; this one should be added to that list, I think?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6214)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6214)*

**Pull request merged**
