### PR TITLE
[multibody, dev] Refactor DeformableContactSurface and ComputeTetMeshTriMeshContact

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Separate DeformableContactSurface and ComputeTetMeshTriMeshContact into two different files for future development.

They are still in `dev` directory, so only one reviewer will be requested.

Helps #16875.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16958)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
This is the first time I do refactoring to split one file into two files using `git mv` and `merge` of two helper branches (learned from [here](https://devblogs.microsoft.com/oldnewthing/20190916-00/?p=102892)). Unfortunately, I do not know how to tell Reviewable what I did.

You'll have to trust me that up to r4, I only renamed files.  The actual code change is in r4-45 diff only.

+@xuchenhan-tri for feature review, please.

+(status: single reviewer ok) since it's still `dev` code.


 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16958#-:-N-_3MdO67mxwKkZr12J:b5xmwpq)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16958)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @xuchenhan-tri)

___
*[-- commits, line 14 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16958#-N-_6jGh-g6A8mRxmYfj):*
Remind myself to change the commit log before merging.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:  Thanks!

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16958#-:-N-_A-qg3_WPxFYURHzY:b-e7bejd)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[multibody/fixed_fem/dev/deformable_contact_surface.h, line 16 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16958#-N-_97aaBbQNj8rradM4:-N-_97ab5raPF1IsMvKt:b-cvh5x6) ([raw file](https://github.com/robotlocomotion/drake/blob/29fd3fa37118703a97f5b353cc13453adecabde9/multibody/fixed_fem/dev/deformable_contact_surface.h#L16)):*
> ```objc
> namespace drake {
> namespace multibody {
> namespace fem {
> ```

BTW, we can probably put this into `geometry/internal` namespace when this comes out of dev.
___
*[multibody/fixed_fem/dev/deformable_contact_surface.h, line 23 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16958#-N-_9JQw2exKy5Lr1PbD:-N-_9JQw2exKy5Lr1PbE:bgmsva) ([raw file](https://github.com/robotlocomotion/drake/blob/29fd3fa37118703a97f5b353cc13453adecabde9/multibody/fixed_fem/dev/deformable_contact_surface.h#L23)):*
> ```objc
> //  be the case. But for now, we'll assume a homogenous scalar environment.
> 
> // TODO(xuchenhan-tri) Consider either beefing this struct upon or creating some
> ```

BTW, it'd be nice if you could also help me resolve this TODO some time in the future. I'd imagine this will be similar to what's being done in hydro.

**Review by DamrongGuoy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16958#-:-N-_G10x3UkB0UpMP52X:b-jzc2h8)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

**Pull request merged**
