### PR TITLE
Use temporary DiagnosticPolicy object

### PR DESCRIPTION
**Pull request by zachfang**
Amends #19747.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19769)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review. Thanks!

CC\ @EricCousineau-TRI

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19769#-:-N_F9k0ZCO38gbBn2HUS:b30qdc9)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review.

Eric was the one who objected to the clarity this formulation originally, so he should be the one to decide whether you've sufficiently resolved his concern.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19769)* status: LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), missing label for release notes (waiting on @zachfang)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19769#-:-N_FAzig6NJ8ivi3T4pM:b-n37teh)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @zachfang)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, just a small BTW (can be ignored)

My concern was just whether the policy should be shared (whether default or otherwise), but if it's understandable to others to construct a temporary to denote a default, then it works for me. Sorry about the noise in the earlier review.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19769#-:-N_FFozqE4SSSEBiA39a:bkgd86s)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 651 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19769#-N_FG54r48cx05Q4__vU:-N_FG54sB8rkAk8RQiiB:b-o2bfu0) ([raw file](https://github.com/RobotLocomotion/drake/blob/821d7e5852fe3178492b2c06a81e43d4aea4b8d1/geometry/render_gl/internal_render_engine_gl.cc#L651)):*
> ```cpp
>     material = MakeMeshFallbackMaterial(data.properties, filename_in,
>                                         parameters_.default_diffuse,
>                                         drake::internal::DiagnosticPolicy());
> ```

BTW Perhaps for clarity, consider using named temporary (here and elsewhere)
```
const drake::internal::DiagnosticPolicy default_diagnostic_policy;
```

**Comment by zachfang** [comment]
Thanks both. I will merge it as-is for now. Will spend some cycles checking out `DiagnosticPolicy` to understand it better.

**Pull request merged**
