### PR TITLE
call_python: Ensure SIGINT is installed (since `exec` does not work the same on Mac).

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Python does not seem to install the `SIGINT` handler on Mac under a bash script, even if run using `exec` in `bash`.

This resolves this on the Python side.

(NOTE: Some of the other CI failures have another error: `ERROR: global name 'time' is not defined`. However, at present, I cannot reproduce this on our local Mac machines.)

\cc @soonho-tri @jamiesnape

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7597)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/call_python_client.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7597#-L0Gh1TJkeP3Olv1i48R:-L0Gh1TJkeP3Olv1i48S:b-yh4nj4) ([raw file](https://github.com/robotlocomotion/drake/blob/75966004b8b02b314fe9631dde0b9b2db192faee/common/proto/call_python_client.py#L23)):*
> ```Python
> def _ensure_sigint_handler():
>     # On Mac, even using `exec <cmd>` in `bash` still yields an ignored SIGINT.
>     sig = signal.getsignal(signal.SIGINT)
> ```

Can it be just `signal.getsignal(signal.SIGINT)`? (w/o `sig = ` part)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7597)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[common/proto/call_python_client.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7597#-L0Gi2XGPLwih0S6-3Xx:-L0Gi2XGPLwih0S6-3Xy:bknqfar) ([raw file](https://github.com/robotlocomotion/drake/blob/75966004b8b02b314fe9631dde0b9b2db192faee/common/proto/call_python_client.py#L22)):*
> ```Python
> 
> def _ensure_sigint_handler():
>     # On Mac, even using `exec <cmd>` in `bash` still yields an ignored SIGINT.
> ```

Maybe worth adding the link https://stackoverflow.com/a/47801921/2654527 here to provide the context?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7597)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[common/proto/call_python_client.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7597#-L0Gh1TJkeP3Olv1i48R:-L0GjCmANlIi3m6tEh-u:b-yq20wk) ([raw file](https://github.com/robotlocomotion/drake/blob/75966004b8b02b314fe9631dde0b9b2db192faee/common/proto/call_python_client.py#L23)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Can it be just `signal.getsignal(signal.SIGINT)`? (w/o `sig = ` part)
</blockquote></details>

f2f, let's delete the line :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7597)*

**Comment by jamiesnape** [comment]
> (NOTE: Some of the other CI failures have another error: ERROR: global name 'time' is not defined. However, at present, I cannot reproduce this on our local Mac machines.)

FWIW I saw that error locally on my Mac too.

**Comment by EricCousineau-TRI** [comment]
@jamiesnape Huh... I'm not sure where that's coming from... The only places `time` is used as a variable are (a) in the first `import` statements, and (b) in plotting tests are disabled in `call_python_full_test`.

I've pushed changes that print out the stack trace of the error.
If you have a chance, could you run `//common/proto:call_python_full_test` off of this push and let me know what the trace of that error is?

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/proto/call_python_client.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7597#-L0Gi2XGPLwih0S6-3Xx:-L0GtOOJ6JnvXd2n9iad:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/75966004b8b02b314fe9631dde0b9b2db192faee/common/proto/call_python_client.py#L22)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Maybe worth adding the link https://stackoverflow.com/a/47801921/2654527 here to provide the context?
</blockquote></details>

Done.

---

*[common/proto/call_python_client.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7597#-L0Gh1TJkeP3Olv1i48R:-L0GtOtzV4AXsO03rtNb:bu9g4k6) ([raw file](https://github.com/robotlocomotion/drake/blob/75966004b8b02b314fe9631dde0b9b2db192faee/common/proto/call_python_client.py#L23)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

f2f, let's delete the line :-)
</blockquote></details>

Done. Thanks for catching that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7597)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7597)*

**Comment by soonho-tri** [comment]
:lgtm: 

FYI, I can't reproduce the `time` problem with this PR in my mac.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7597#-:-L0GvIyvSjzkmlhF7w_2:b8velzr)*

**Comment by EricCousineau-TRI** [comment]
It cropped up again on CI; will re-trigger once more.

@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.

**Comment by soonho-tri** [comment]
Added `do not merge` label to prevent an accidental merge. Please feel free to remove it when the result for the mac build is in.

**Comment by soonho-tri** [comment]
@EricCousineau-TRI, FYI, `mac-sierra-clang-bazel-experimental` failed.

**Comment by EricCousineau-TRI** [comment]
Ah jeepers, looks like it's a bug in certain versions of `matplotlib`. The error's stack trace (from here):
```
Traceback (most recent call last):
  File "/Users/sierra/workspace/mac-sierra-clang-bazel-experimental/_bazel_sierra/061142d1f0ff4d733b753574c8ac9aae/bazel-sandbox/7359111385415258530/execroot/drake/bazel-out/osx-opt/bin/common/proto/call_python_full_test.runfiles/drake/common/proto/call_python_client.py", line 423, in _handle_messages_threaded
    pause(0.001)
  File "/Users/sierra/workspace/mac-sierra-clang-bazel-experimental/_bazel_sierra/061142d1f0ff4d733b753574c8ac9aae/bazel-sandbox/7359111385415258530/execroot/drake/bazel-out/osx-opt/bin/common/proto/call_python_full_test.runfiles/drake/common/proto/call_python_client.py", line 193, in pause
    plt.pause(interval)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 294, in pause
    time.sleep(interval)
NameError: global name 'time' is not defined
```

Here's the issue: matplotlib/matplotlib#9412

Seems like we can just inject `time` into `pyplot`s `globals()`, as in this example:
[inject_test.py](https://github.com/EricCousineau-TRI/repro/blob/a235986ea715464880830d13ba3d937fdff2eb6a/python/matplotlib/inject_test.py)

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7597)*

**Pull request merged**
