### PR TITLE
[doc] Updates to Docker/Apt/S3 release documentation

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20018)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20018#-:-Nc3lmiBAHbpweQF2Yo9:bnyvoyh)* status: LGTM missing from assignee mwoehlke-kitware

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20018)* status: 2 unresolved discussions, LGTM missing from assignee mwoehlke-kitware

___
*[`tools/release_engineering/dev/README.md` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20018#-Nc48spp7smZ1De2c2cs:-Nc48spp7smZ1De2c2ct:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4c701b064c2260f415f8e843559f520c5d3ec35/tools/release_engineering/dev/README.md#L61)):*
> ```Markdown
> ### Create GitHub API Token
> 
> To create the required ~/.config/readonly_github_api_token.txt file, open a
> ```





_Suggestion:_
```Markdown
`~/.config/readonly_github_api_token.txt`
```
___
*[`tools/release_engineering/dev/README.md` line 98 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20018#-Nc47JloCZGUobRaWvF4:-Nc47JlpB6Qa2MG0pR25:bp7t618) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4c701b064c2260f415f8e843559f520c5d3ec35/tools/release_engineering/dev/README.md#L98)):*
> ```Markdown
> 1. The `*.deb` files are in AWS
> [s3://drake-packages/drake/release](https://s3.console.aws.amazon.com/s3/buckets/drake-packages?region=us-east-1&prefix=drake/release/&showversions=false)
> `/<configuration>/drake-dev_<version>-1_amd64.deb` for each supported configuration (e.g. Focal and jammy)
> ```

I think the (lack of) capitalization here was deliberate to match the file names (which are not capitalized). In any case, please be consistent between "Focal" and "Jammy". :slightly_smiling_face: (Adding quotes might make the intent clearer; that would be fine!)



_Suggestion:_
```Markdown
focal and jammy
```

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20018)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware

___
*[`tools/release_engineering/dev/README.md` line 98 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20018#-Nc47JloCZGUobRaWvF4:-Nc4CueLDQF1tz_xRHvz:bhhnnyv) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4c701b064c2260f415f8e843559f520c5d3ec35/tools/release_engineering/dev/README.md#L98)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I think the (lack of) capitalization here was deliberate to match the file names (which are not capitalized). In any case, please be consistent between "Focal" and "Jammy". :slightly_smiling_face: (Adding quotes might make the intent clearer; that would be fine!)
</blockquote></details>

 I was certain I was _fixing_ a mismatch but it appears as though I _introduced_ one. Yikes. Let's do lowercase throughout.

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20018#-:-Nc9WEYE9ayAeYPhTHLG:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignee mwoehlke-kitware, exempt from platform review

**Pull request merged**
