### PR TITLE
Update drake_models

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Accept drake_models PR#30, and adjust the models-with-errors/warnings lists.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20858)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20858)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`tools/workspace/drake_models/repository.bzl` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20858#-NpWOX6w2qxcm8PEVOZ1:-NpWOX6xAjkwdeVgtAiw:b-y7bpxp) ([raw file](https://github.com/RobotLocomotion/drake/blob/5b401993f77109f30adcf552e0dd7bba4c08dd16/tools/workspace/drake_models/repository.bzl#L10)):*
> ```Starlark
>         repository = "RobotLocomotion/models",
>         commit = "268a68c6b7575068be48a54561e4aee19578bc94",
>         sha256 = "078af2ba9fc61cb9c736d999c67212e2fa8815837442202c7a09a4ba9fc9a035",  # noqa
> ```

Working temporary SHA1 until the models PR <LINK> is merged.

**Review by rpoyner-tri — COMMENTED** [review]
https://github.com/RobotLocomotion/models/pull/30

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20858#-:-NpWOt2L9mgj3X5MPKmx:b-unddqx)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`tools/workspace/drake_models/repository.bzl` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20858#-NpWOX6w2qxcm8PEVOZ1:-NpWOo2KE8J8wSAuX06S:bwjpyg4) ([raw file](https://github.com/RobotLocomotion/drake/blob/5b401993f77109f30adcf552e0dd7bba4c08dd16/tools/workspace/drake_models/repository.bzl#L10)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Working temporary SHA1 until the models PR <LINK> is merged.
</blockquote></details>

er, models PR is https://github.com/RobotLocomotion/models/pull/30

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for both reviews. +(status: single reviewer ok) 
+(release notes: feature) 
See https://drake.mit.edu/model_version_control.html for process notes.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20858#-:-NpWOvQl5UwxKM4hicDs:b9qb8jg)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 pending CI -- one failure, is it a flake?
IIUC the models PR needs to be merged first and then the SHA updated here prior to merge.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20858#-:-NpX3Cmv728kRLHMbOHl:bw4vjad)* status: 1 unresolved discussion

**Review by rpoyner-tri — COMMENTED** [review]
https://github.com/RobotLocomotion/drake/issues/18726 is the failure. It has a good chance of disappearing when I re-run that build.

I'll wait until the models pr is merged before I fret about CI gremlins.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20858#-:-Np_XR1Y1fMYzJMY4_AM:b-jo089w)* status: 1 unresolved discussion

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-everything-release please.

**Pull request merged**
