### PR TITLE
IiwaCommandReceiver latches initial position until first command

### LINKED ISSUE #13465: Design of input (not parameter) for no-op IIWA command
From #13340:

@siyuanfeng-tri writes:
> sorry i didn't catch this earlier.
> i just realized that setting desired q to measured q is probably not the best thing to do before receiving a real command... since that effectively wipes out the position feed back loop. this would be more weird when we compute the desired velocity based on numeric difference between commanded q, and would be extra weird if we specified a integral gain in the pid loop downstream. we are currently doing all of these in the standard iiwa pipeline..

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #13465.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13540)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
fyi, i tried to use anzu with this, and i think i have run into issues with wsg controller. still debugging...

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-focal-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
I've confirmed that Anzu CI passes vs this PR.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri could you begin feature review of the `manipulation/**` parts, if you're game?  The framework parts are in another PR, separately.

**Comment by jwnimmer-tri** [comment]
The framework PR got bogged down, so I rewrote this to avoid any framework changes.

**Pull request merged**
