### PR TITLE
[doc] Add release notes v1.26.0

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
I have finished editing the list from the first `--action=update`.  I'll do the second `--action=update` now. (I'll also pull upstream master.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-:-Nq4hOKbEM-2K2pWmGFw:b-2ksl42)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Thank you for helping me, Jeremy.  I'll merge up my local branch (no rebase, no force push) as instructed in [Release Playbook.](https://drake.mit.edu/release_playbook.html) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-:-NqUErAe8D5IWKtDWBmg:b-rrb6da)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-:-NqUQJjL68iOhiQ7-Puo:ba0k9zt)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by jwnimmer-tri — COMMENTED** [review]
+@jwnimmer-tri :lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-:-NqYVX8vA4nEo3vJwTad:b-dkds0x)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.26.0.md` line 78 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-NqYUYBs20hRLPD8sweB:-NqYUYBs20hRLPD8sweC:b6g3sg5) ([raw file](https://github.com/RobotLocomotion/drake/blob/8c48a75d6d4e1b3abbcea7b15d16b5856f2b792f/doc/_release-notes/v1.26.0.md#L78)):*
> ```Markdown
> * Defer surface meshing for deformables when inactive ([#20822][_#20822])
> * Fast initialize compliant-hydroelastic nonconvex meshes and deformables ([#20798][_#20798])
> * Fix bug in glTF depth and label representations ([#20854][_#20854])
> ```

BTW @SeanCurtis-TRI should this say "VTK" somewhere on this line?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.26.0.md` line 78 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-NqYUYBs20hRLPD8sweB:-NqYilx2CcZZ2sWSO3Ge:b-fkzp8u) ([raw file](https://github.com/RobotLocomotion/drake/blob/8c48a75d6d4e1b3abbcea7b15d16b5856f2b792f/doc/_release-notes/v1.26.0.md#L78)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW @SeanCurtis-TRI should this say "VTK" somewhere on this line?
</blockquote></details>

Yep. Let's add the phrase, "in RenderEngineVtk" to the end.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.26.0.md` line 78 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-NqYUYBs20hRLPD8sweB:-NqYvUOZ3cjabLcDyTv4:b-ik3clt) ([raw file](https://github.com/RobotLocomotion/drake/blob/8c48a75d6d4e1b3abbcea7b15d16b5856f2b792f/doc/_release-notes/v1.26.0.md#L78)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Yep. Let's add the phrase, "in RenderEngineVtk" to the end.
</blockquote></details>

Thanks for helping me.   Working.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.26.0.md` line 78 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-NqYUYBs20hRLPD8sweB:-NqYwHYQ4xzYjgwrahLV:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8c48a75d6d4e1b3abbcea7b15d16b5856f2b792f/doc/_release-notes/v1.26.0.md#L78)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Thanks for helping me.   Working.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)* status: 2 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.26.0.md` line 152 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-Nqd9imGDthMS6kY1dAG:-Nqd9imGDthMS6kY1dAH:b-a1urh1) ([raw file](https://github.com/RobotLocomotion/drake/blob/98e104079e4ea21385047d440492b609dd759c01/doc/_release-notes/v1.26.0.md#L152)):*
> ```Markdown
> * Upgrade drake_models to latest commit ([#20858][_#20858])
> * Upgrade eigen to latest release 3.4.0 for wheel builds ([#20802][_#20802])
> * Upgrade meshcat to latest commit ([#20805][_#20805], [#20876][_#20876], [#20904][_#20904]), ([#20938][_#20938])
> ```

nit Drop the inner pair of parens.  We just want a single parenthetical with all of the numbers as comma-separated items inside of it.
___
*[`doc/_release-notes/v1.26.0.md` line 164 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-Nqd9tCQEbUrnpPyXQkG:-Nqd9tCQEbUrnpPyXQkH:buucm49) ([raw file](https://github.com/RobotLocomotion/drake/blob/98e104079e4ea21385047d440492b609dd759c01/doc/_release-notes/v1.26.0.md#L164)):*
> ```Markdown
> * Upgrade suitesparse_internal to latest release v7.6.0 ([#20900][_#20900])
> * Upgrade tinyobjloader_internal to latest commit ([#20900][_#20900])
> * Upgrade rules_python to latest release 0.29.0 ([#20902][_#20902])
> ```

nit Alpha-sort (after rules_license).

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-NqdjK0J6oncS6BvFiOF:-NqdjK0J6oncS6BvFiOG:bezvbz2) (no related file):*
Working.  Wait for all seven staging jobs to succeed.

___
___
*[`doc/_release-notes/v1.26.0.md` line 152 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-Nqd9imGDthMS6kY1dAG:-NqdjiphA3p2t7YcmrOG:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/98e104079e4ea21385047d440492b609dd759c01/doc/_release-notes/v1.26.0.md#L152)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Drop the inner pair of parens.  We just want a single parenthetical with all of the numbers as comma-separated items inside of it.
</blockquote></details>

Done. Thanks.
___
*[`doc/_release-notes/v1.26.0.md` line 164 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-Nqd9tCQEbUrnpPyXQkG:-Nqdl7LW0m-JyYss16i0:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/98e104079e4ea21385047d440492b609dd759c01/doc/_release-notes/v1.26.0.md#L164)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Alpha-sort (after rules_license).
</blockquote></details>

Done. Thanks.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: WIth one typo

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-:-Nqdsmu85HstydaiILb8:b-ldf48n)* status: 2 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.26.0.md` line 112 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-NqdsOyXE5300tlnih5d:-NqdsOyXE5300tlnih5e:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/7aeac9968a7f3f792c237ed7b884f65e16e70163/doc/_release-notes/v1.26.0.md#L112)):*
> ```Markdown
> * Add `Sha256` utility class ([#20779][_#20779])
> * Fix for `SchunkWsgTrajectoryGenerator` failing on delta=0 ([#20828][_#20828])
> * Add `EigenMapView` to aid inerop with C++ containers ([#20906][_#20906])
> ```

nit: typo



_Suggestion:_
```Markdown
interop
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.26.0.md` line 112 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-NqdsOyXE5300tlnih5d:-Nqdt0sM93otLCr2mf3g:bix7gpd) ([raw file](https://github.com/RobotLocomotion/drake/blob/7aeac9968a7f3f792c237ed7b884f65e16e70163/doc/_release-notes/v1.26.0.md#L112)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

Typo fixed.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-NqdjK0J6oncS6BvFiOF:-NqeYPIU4syWztF0tjRj:bh0pls2) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Working.  Wait for all seven staging jobs to succeed.
</blockquote></details>

Done. 

After fixing typos in `download_release_candidate.py`, I can get 45 files as expected.

___

**Review by DamrongGuoy — COMMENTED** [review]
I forgot to +@SeanCurtis-TRI .  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-:-NqeYs8o-cxiwlkzV5Qc:b-gz1h0e)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-:-NqeZ1Nl44BiM7t2udyf:b-b9fcpn)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20883#-:-NqeZC7479z1RmwhRSBx:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
