### PR TITLE
More fixes and improvements to mkdoc.py

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9703)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review.

**Comment by EricCousineau-TRI** [comment]
___
*[third_party/com_github_pybind_pybind11/mkdoc.py, line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9703#-LPBkehf-vjqpZV23Y3y:-LPBmBe3ENxWvJXiGTQ3:b-1ondng) ([raw file](https://github.com/robotlocomotion/drake/blob/b897eb061955694f39468f1e489a0166ab3558cd/third_party/com_github_pybind_pybind11/mkdoc.py#L186)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Somewhere in here, can you add a rule to convert `` `<expr>` `` to ` ``<expr>`` `. At present, `WrapToSystem` shows expressions that should be preformatted as italics in Sphinx:
> 

As an example, Doxygen:
> 

</blockquote></details>

Er, bad grammar: "shows expressions, which *should* be preformatted, as italics"

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by EricCousineau-TRI** [comment]
Reading the commits and the diffs, they seem pretty curated. Will remove the tag and merge.

**Pull request merged**
