### PR TITLE
[doc] Add release notes v0.37.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[doc/_release-notes/v0.37.0.md, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16154#-Mpm-jCt5Ao9opLZi__k:-Mpm-jCt5Ao9opLZi__l:b94bmpn) ([raw file](https://github.com/robotlocomotion/drake/blob/7ed4d9d596ce2cc3e6aba5d859c258e3de37028b/doc/_release-notes/v0.37.0.md#L55)):*
> ```Markdown
> * TBD Add collection of fixes to speed up Iris region generation ([#16037][_#16037])
> * TBD [meshcat] Avoid dropping messages due to backpressure, and provide Flush() ([#16144][_#16144])  # Resolves #16109 After reading through the uwebsockets code, I understand now that the maxBackpressure websocket option was *only* being used to decide when to drop packets.  We never want to drop packets, so setting that to zero is the correct behavior. Backpressure is still a legitimate concern.  If we keep shoving data into the send buffer faster than the websocket can send, then backpressure will build up (consuming memory and causing the visualizer to fall behind the main thread).  I've provided a `Flush()` command for Meshcat which allows users to manually sync the main thread if it is useful/needed in their application.
> * TBD [hydro] Make MeshFieldLinear compatible with PolygonSurfaceMesh ([#16122][_#16122])  # - The mesh field has conditional barycentric behavior (as barycentric coordinates are not well defined for polygonal elements). - Provides an alias and instantiation for MeshFieldLinear on PolygonSurfaceMesh (to parallel TriangleSurfaceMeshFieldLinear).
> ```

As usual, the hydro PRs can get combined into a "New hydroelastic contact model in progress" item. This is perhaps the last time hydro will duck the release notes :crossed_fingers:

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[doc/_release-notes/v0.37.0.md, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16154#-Mpm-jCt5Ao9opLZi__k:-Mpm36dD14jDhmigCRXn:bkx4qjr) ([raw file](https://github.com/robotlocomotion/drake/blob/7ed4d9d596ce2cc3e6aba5d859c258e3de37028b/doc/_release-notes/v0.37.0.md#L55)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

As usual, the hydro PRs can get combined into a "New hydroelastic contact model in progress" item. This is perhaps the last time hydro will duck the release notes :crossed_fingers: 
</blockquote></details>

My plan for this (multibody) section of the notes was to ask the dynamics team to push their own notes-curation into this branch.  Y'all are welcome to do that at any point along the way.  I think Monday, December 13th would be the earliest candidate date for release.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[doc/_release-notes/v0.37.0.md, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16154#-Mpm-jCt5Ao9opLZi__k:-Mpr6feBET3MMFcfKwAj:b-hzwrfr) ([raw file](https://github.com/robotlocomotion/drake/blob/7ed4d9d596ce2cc3e6aba5d859c258e3de37028b/doc/_release-notes/v0.37.0.md#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My plan for this (multibody) section of the notes was to ask the dynamics team to push their own notes-curation into this branch.  Y'all are welcome to do that at any point along the way.  I think Monday, December 13th would be the earliest candidate date for release.
</blockquote></details>

OK Done -- this was easier that I thought (I haven't bothered to read the wall-of-text commit messages here).  In the past, I'd had to guess which PRs were hydro.  Of late, people have been doing a good job of putting 'hydro' in the commit title, which makes it easy for me to roll up.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri and +@sherm1 for reviews, please.  My plan will be to release on Monday the 13th.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154#-:-MqQoofx5yjslPT7JIft:b-b20843)* status: LGTM missing from assignees rpoyner-tri(platform),sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154#-:-MqQyImjCOoOvpzkC_N0:bg7igkv)* status: LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154#-:-MqRDGVr1qAK3kxmIRTJ:bnfp4nl)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16154)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail we're ready to manually tag docker images, upload the releases to S3, and publish the Debian packages.

https://github.com/RobotLocomotion/drake/releases/tag/v0.37.0
binary date: 20211213
commit SHA: 5357d9aad2a9e34c8a2d283de7a93a6595c5293a
release tag: v0.37.0

I'll work on publishing the pip wheels, later today.

**Comment by BetsyMcPhail** [comment]
Docker images, S3 and deb packages have been updated.

The gpg key for the apt packages expired on 12/15/2021. That has been renewed and  https://drake-apt.csail.mit.edu/drake.asc has been updated.

**Pull request merged**
