### PR TITLE
[config] Provide bindings for CameraConfig and ApplyCameraConfig

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This also includes bindings of `CameraConfig`s substructs: `FovDegress` and `FocalLength`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17852)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
> The default constructed version are "invalid".

This seems like something worth fixing at its source?

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'd suggest it's not "broken" and therefore doesn't need fixing. It's simply incompatible.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17852#-:-NBNTV3r2G-usJveaZ0X:b-1ny5tw)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
It's not about serialization, it's about making the user flail at their keyboard to use the feature.  The ideal outcome is that the user can turn on a camera with a little syntax/code as possible.  Anything we make _required_ is just another hurdle they need to cross in order to use the feature.  I'll see if I can convince myself about a patch that makes sense.

**Comment by jwnimmer-tri** [comment]
=> #17854

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks for the PR. Based on that PR, the question of `ASSERT_NO_THROW(CameraConfig().ValidateOrThrow())` is obviously resolved. :)

As soon as that merges, I'll rebase and respell the bindings.

+(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17852#-:-NBNnobs5A7-bBPEXZZD:bnfvi12)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not review) 

Ok, ready for review without caveats.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17852#-:-NBOrK1O8QX3yaQjDDD2:bxulkou)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: feature, nice!
+@xuchenhan-tri for platform review, please

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17852#-:-NBP-8K7DlD8xBjqzm0Y:b9d73fm)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: with one copypasta issue.

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17852#-:-NBP4xrpCMxfJiHuhC0s:buwcb7n)* status: 2 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17852#-NBP5GSIExyarpYEBIt6):*
typo s/FovDegress/FovDegrees.
___
*[`bindings/pydrake/systems/sensors_py.cc` line 245 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17852#-NBP3cgT3vKHfcikvmC8:-NBP3cgT3vKHfcikvmC9:ban6led) ([raw file](https://github.com/robotlocomotion/drake/blob/c3ea2676cd93297dcf6c81468f13164ca2c38c5f/bindings/pydrake/systems/sensors_py.cc#L245)):*
> ```cpp
>         .def(ParamInit<CameraConfig>())
>         .def("focal_x", &CameraConfig::focal_x, config_cls_doc.focal_x.doc)
>         .def("focal_y", &CameraConfig::focal_x, config_cls_doc.focal_x.doc)
> ```

copypasta



_Suggestion:_
```cpp
        .def("focal_y", &CameraConfig::focal_y, config_cls_doc.focal_y.doc)
```
___
*[`bindings/pydrake/systems/test/sensors_test.py` line 190 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17852#-NBP3rmq-S9wf1KxPrnP:-NBP3rmq-S9wf1KxPrnQ:bbk3glq) ([raw file](https://github.com/robotlocomotion/drake/blob/c3ea2676cd93297dcf6c81468f13164ca2c38c5f/bindings/pydrake/systems/test/sensors_test.py#L190)):*
> ```Python
>         copy.copy(config)
>         self.assertEqual(config.focal_x(), 10)
>         self.assertEqual(config.focal_y(), 10)
> ```

BTW would have caught it if focal_y != focal_x.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17852)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @xuchenhan-tri)

___
*[`bindings/pydrake/systems/sensors_py.cc` line 245 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17852#-NBP3cgT3vKHfcikvmC8:-NBSbsAP2aT4TsLWj-7r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c3ea2676cd93297dcf6c81468f13164ca2c38c5f/bindings/pydrake/systems/sensors_py.cc#L245)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

copypasta
</blockquote></details>

Done.
___
*[`bindings/pydrake/systems/test/sensors_test.py` line 190 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17852#-NBP3rmq-S9wf1KxPrnP:-NBSbsmL21JCHkZFFhgJ:b-x8ui4o) ([raw file](https://github.com/robotlocomotion/drake/blob/c3ea2676cd93297dcf6c81468f13164ca2c38c5f/bindings/pydrake/systems/test/sensors_test.py#L190)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW would have caught it if focal_y != focal_x.
</blockquote></details>

Done

I fell victim to my own trap. I always advocate make every bit count. Bad Sean!

**Pull request merged**
