### PR TITLE
framework: Add DeclareCacheEntry overload for std::function

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For use by #13540.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13542)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-focal-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

**Comment by jwnimmer-tri** [comment]
I had trouble getting template argument deduction to work with `std::function` parameterized on a `MyContext`.

**Comment by jwnimmer-tri** [comment]
As the control logic of #13540 evolved, it turned out to be better to use the member functions instead of lambdas, so I no longer have any use case to justify this overload.  We can resurrect this patch (with fixes) if we ever need it later on.

**Pull request closed without merging**
