### PR TITLE
Port maliput to test_utilities pattern

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Per discussion in Drake's `#bazel` channel 2017-09-20, we're proposing a convention that widely shared testonly `cc_library` targets live in a subfolder named `test_utilities`, for easier discoverability and less `deps=` ceremony when there is more than one helper class.  This PR ports maliput/... to that new idiom.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7125)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@maddog-tri for feature review, please.

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7125#-:-Kv899kr7LHBtG4v34tr:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review per rotation, please.

**Comment by soonho-tri** [comment]
Reviewed 16 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7125)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 9 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7125#-:-Kv8S18jsBg4kxpiHV--:bnfp4nl)*

**Pull request merged**
