### PR TITLE
[parsing] Drop compatibility code for Ventura

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) +@jwnimmer-tri for both reviews, Monday schedule.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-:-O8xaGW51RUxLaO8BnWh:b-gpr6ks)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-:-O8xdCZuCmQQUMBWFsmA:bb6yyy8)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-O8xdPnW1UId17TNu9Hm:-O8xdPnW1UId17TNu9Hn:bb3l38x) (no related file):*
Working

I'm hoping to still do one last x86_64 ventura wheel release, so let's hold off merging this until later next week, if possible.

___
___
*[`multibody/parsing/test/detail_instanced_name_test.cc` line 34 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-O8xdL13DeFPErpsbqEi:-O8xdL13DeFPErpsbqEj:blaxn7h) ([raw file](https://github.com/RobotLocomotion/drake/blob/2662e2bb7546d73c303d6f4b149f947c3ced159e/multibody/parsing/test/detail_instanced_name_test.cc#L34)):*
> ```cpp
> }
> 
> GTEST_TEST(InstanceNameTest, ToString) {
> ```

I think we still want to keep the to_string regression tests?

**Comment by jwnimmer-tri** [comment]
Also it looks like our version of XCode 15 isn't new enough yet.  Do we need to upgrade the CI images?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029)* status: 3 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-O8xewwUC8i_b3JY_PXI:-O8xewwUC8i_b3JY_PXJ:b8fhzc1) (no related file):*
I will check on xcode versions.

___
___
*[`multibody/parsing/test/detail_instanced_name_test.cc` line 34 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-O8xdL13DeFPErpsbqEi:-O8xf0184RfsFyimajRX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2662e2bb7546d73c303d6f4b149f947c3ced159e/multibody/parsing/test/detail_instanced_name_test.cc#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think we still want to keep the to_string regression tests?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029)* status: 2 unresolved discussions

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-O8xewwUC8i_b3JY_PXI:-O8xjgyP9un-3KCeZbzT:b-7zmp07) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I will check on xcode versions.
</blockquote></details>

So far, I got Xcode 16 to build it. I tried Xcode 15.3 and got some completely unrelated and prior error. Don't know what to make of that yet. Xcode 15.4 is still untested.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-O8xewwUC8i_b3JY_PXI:-O8xlACk35YnKOMFqBo_:bnq4nsc) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So far, I got Xcode 16 to build it. I tried Xcode 15.3 and got some completely unrelated and prior error. Don't know what to make of that yet. Xcode 15.4 is still untested.
</blockquote></details>

We might as well just upgrade to >= 16.  No reason to use something older, so long as all our supported OSs (>= Sonoma) can install it, and it seems they can.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-O8xewwUC8i_b3JY_PXI:-O90P2SW4qZEvK64DXqd:b-4zpn4p) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We might as well just upgrade to >= 16.  No reason to use something older, so long as all our supported OSs (>= Sonoma) can install it, and it seems they can.
</blockquote></details>

Filed as #22031.  I anticipate the new images in ~1-3 weeks.

___

**Review by jwnimmer-tri — COMMENTED** [review]
See #22031 for the ticket re: new XCode images in CI.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-:-O9L4oNi3D_m6wNOZm74:bovf00m)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-O8xdPnW1UId17TNu9Hm:-O9L4k9E9j2c6YQ4HNwd:btqvjab) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'm hoping to still do one last x86_64 ventura wheel release, so let's hold off merging this until later next week, if possible.
</blockquote></details>

The release is about to be tagged now, so I've removing my blocking discussion here.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-O9kHNLv3NfWjbYxEA6d:-O9kHNLw6WFHH4bf4dve:bwfv1w8) (no related file):*
This PR is blocked from landing by #22061 being fixed, and then by getting all supported mac platforms to Xcode 16.

___

**Comment by rpoyner-tri** [comment]
**@drake-jenkins-bot** linux-jammy-gcc-bazel-experimental-debug please.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029)* status: 1 unresolved discussion

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-ODvs5NC5oKNyw5Xq4Ye:-ODvs5NC5oKNyw5Xq4Yf:bupntms) (no related file):*
build failure was:
\[12:06:53 PM\]  FLAKY: //examples/allegro\_hand/joint\_control:py/run\_twisting\_mug\_test (Summary)

Might just work on a retry, but don't want to hammer on our feeble mac builders just now.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22029)* status: 1 unresolved discussion

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22029#-ODvs5NC5oKNyw5Xq4Ye:-ODvweoI73vU4RhUg5tf:bjldnsm) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

build failure was:
\[12:06:53 PM\]  FLAKY: //examples/allegro\_hand/joint\_control:py/run\_twisting\_mug\_test (Summary)

Might just work on a retry, but don't want to hammer on our feeble mac builders just now.
</blockquote></details>

The actual error was in `//bindings/pydrake/systems:py/custom_test` with `bad_cast`, I imagine because the PR started prior to the XCode 16 patch landing on master.

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The actual error was in `//bindings/pydrake/systems:py/custom_test` with `bad_cast`, I imagine because the PR started prior to the XCode 16 patch landing on master.
</blockquote></details>

**@drake-jenkins-bot** mac-arm-sonoma-clang-bazel-experimental-release please.

**Pull request merged**
