### PR TITLE
update capabilities on front page with updated status and lots of links

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6376)

### CODE REVIEW

**Comment by RussTedrake** [comment]
Note that I consider this a bit of a mess (links going to other sphinx docs, doxygen, and code... not always in the same tree), but it's much better than what we had and has given me a clearer head about what we should do to clean all the docs up.  

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6376#-:-Kmt4UdmICCtZADBP8aC:b-cyvbkp)*

**Comment by RussTedrake** [comment]
+@sherm1 for both reviews, in the hopes that he checks today.  

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6376#-:-KmvffvTOwE2iTyWzi-F:b-qhnaac)*

**Comment by sherm1** [comment]
I generated the docs and tried out the links. Everything worked but one link noted below. :lgtm: pending replacing that link with the one in the note.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/index.rst, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6376#-KmvrsAOej0JmVmAlp6P:-KmvrsAPukAOAsZPCiBc:b1tc3dl) ([raw file](https://github.com/robotlocomotion/drake/blob/82fd2d48207346569c6d02162e0fee0844d85f48/drake/doc/index.rst#L50)):*
> ```reStructuredText
> 	* For nearly all of the above we aim to expose sparsity in the governing equations and provide analytical gradients / symbolic analysis
> 	* **Coming soon**:
> 		* API upgrade from `RigidBodyTree <http://drake.mit.edu/doxygen_cxx/class_rigid_body_tree.html>`_ to `MultiBodyTree <http://drake.mit.edu/doxygen_cxx/class_multibody_tree.html>`_
> ```

BTW the multibodytree link doesn't work, that was the broken one. The correct link is `http://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_tree.html`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6376#-:-KmvtskMrVRlIipc5zhn:b-8ukes7)*

**Comment by RussTedrake** [comment]
done.  thanks!

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6376#-:-Kmw9FRE12bQ_4DmBNcD:b-w4a567)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6376)*

**Pull request merged**
