### PR TITLE
Fix document of ComputeContactSurfaces() that compliant Mesh is supported

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@SeanCurtis-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-:-NVVlQen7Vghl0Rn8EMS:b-6cxuoj)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done (I know, funny thing to say for a one-word PR -- but I anticipate with my comment I've increased this size of this PR by a factor of 10 or even 20.)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-:-NVW3x4gBaez4QKEB9_i:b-uhr232)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[`geometry/query_object.h` line 318 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NVW3ZPC8BX3JRWGN5H_:-NVW3ZPC8BX3JRWGN5Ha:b-r4h8yt) ([raw file](https://github.com/RobotLocomotion/drake/blob/caf7ceb39e3a14aa491d1df0e1e57596dfc4ed92/geometry/query_object.h#L318)):*
> ```objc
>        | Ellipsoid |    yes    |  yes  |
>        | HalfSpace |    yes    |  yes  |
>        | Mesh      |    yes    |  yes  |
> ```

nit: This *definitely* calls for a footnote. For every other square in this table, it is pretty simple to put a geometry into `SceneGraph` representing that cell (declare the right shape, declare the right compliance). However, for a compliant mesh, that requires some extra effort.

We should put a footnote on this cell and redirect them to where they can read more about how they get compliant meshes into Drake.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/query_object.h` line 318 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NVW3ZPC8BX3JRWGN5H_:-NVlqnO75QRDDMJVNYF2:b-eesrfo) ([raw file](https://github.com/RobotLocomotion/drake/blob/caf7ceb39e3a14aa491d1df0e1e57596dfc4ed92/geometry/query_object.h#L318)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This *definitely* calls for a footnote. For every other square in this table, it is pretty simple to put a geometry into `SceneGraph` representing that cell (declare the right shape, declare the right compliance). However, for a compliant mesh, that requires some extra effort.

We should put a footnote on this cell and redirect them to where they can read more about how they get compliant meshes into Drake.
</blockquote></details>

Would you like to add the footnote to this PR directly?  I didn't quite get what you said.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[`geometry/query_object.h` line 318 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NVW3ZPC8BX3JRWGN5H_:-NW2ZWJ4DvlWyolUABRH:bb0tnl3) ([raw file](https://github.com/RobotLocomotion/drake/blob/caf7ceb39e3a14aa491d1df0e1e57596dfc4ed92/geometry/query_object.h#L318)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Would you like to add the footnote to this PR directly?  I didn't quite get what you said.
</blockquote></details>

The idea is this:

While a compliant `Mesh` is _supported_, it's not simple to implement. (It's not just a tag in your URDF/SDF.) This documentation should have a footnote hinting at that. Ideally, the footnote would link to some documentation explaining how one *actually* provides a compliant mesh in practice.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/query_object.h` line 318 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NVW3ZPC8BX3JRWGN5H_:-NW5ZJNK7C4D2x9nTp2B:b-f31l3l) ([raw file](https://github.com/RobotLocomotion/drake/blob/caf7ceb39e3a14aa491d1df0e1e57596dfc4ed92/geometry/query_object.h#L318)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The idea is this:

While a compliant `Mesh` is _supported_, it's not simple to implement. (It's not just a tag in your URDF/SDF.) This documentation should have a footnote hinting at that. Ideally, the footnote would link to some documentation explaining how one *actually* provides a compliant mesh in practice.
</blockquote></details>

I get it better. Thanks for explanation.  I interpret what you said in three ways:

1.  Isn't that a part of the Mesh class?  You meant you want to expand the documentation of the [geometry::Mesh](https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_mesh.html) class?  Perhaps you meant something like this?
- Mesh(Obj file) 
- Mesh(STL file)
- Mesh(VTK file)
- Mesh(DAE file)

I can do that in another PR.

2. Or did you mean to expand in [Hydroelastic Users Guide](https://drake.mit.edu/doxygen_cxx/group__hydroelastic__user__guide.html) on how to make VTK files of tetrahedral meshes?  I can do that in a different PR.  (On the other hand, we do not provide guidance on how to make Obj files for triangle meshes.)

3. Or you meant a two-line footnote like this?  This one we can do in this PR.
```
a. For compliant-hydroelastic Mesh, please use Mesh(VTK file) of tetrahedral mesh.
b. For rigid-hydroelastic Mesh, please use Mesh(Obj file) for triangle mesh.
```

I think you prefer option 3, correct?

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/query_object.h` line 318 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NVW3ZPC8BX3JRWGN5H_:-NW7q0ln982zNt_k-rsl:b60m495) ([raw file](https://github.com/RobotLocomotion/drake/blob/caf7ceb39e3a14aa491d1df0e1e57596dfc4ed92/geometry/query_object.h#L318)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I certainly like the idea of evolving the user guide as our feature set evolves, but all I had in mind for this PR was number three (something of limited scope, well suited to the purpose of this PR). Your suggested text draws exactly the contrast I would hope for.

In an ideal world, it would also include a URL explaining where that VTK file comes from. I know you've done a write up for creating a VTK file for use as a compliant mesh. I *don't* know that it's publicly available. If it is publicly available (in a fixed location), then I'd love a link to it. If there's no link currently available, then some language that suggests that guidance is coming and what someone can do if they want to have a compliant mesh (ask on slack. Ask on stackoverflow, something.) I don't know how you currently handle the question, "I want a compliant mesh. How do I do that?" But the closer that someone can get to discovering that answer via the footnote, the better.
</blockquote></details>

Thank you!  I'll do number 3 and set up a link to a public document for "I want a compliant mesh. How do I do that?"

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/query_object.h` line 318 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NVW3ZPC8BX3JRWGN5H_:-NW7qRV54CIO0e7xgA2J:b-tkpx0h) ([raw file](https://github.com/RobotLocomotion/drake/blob/caf7ceb39e3a14aa491d1df0e1e57596dfc4ed92/geometry/query_object.h#L318)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Thank you!  I'll do number 3 and set up a link to a public document for "I want a compliant mesh. How do I do that?"
</blockquote></details>

Set to working.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[`geometry/query_object.h` line 318 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NVW3ZPC8BX3JRWGN5H_:-NWAXjnv3BHMKjw83XG4:b-40apfo) ([raw file](https://github.com/RobotLocomotion/drake/blob/caf7ceb39e3a14aa491d1df0e1e57596dfc4ed92/geometry/query_object.h#L318)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Set to working.
</blockquote></details>

Done.

FYI, I used this command to check doxygen:

 bazel run //doc/doxygen_cxx:build -- --serve --quick drake.geometry

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[`geometry/query_object.h` line 318 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NVW3ZPC8BX3JRWGN5H_:-NWI-gwj05XHnHGYmh7d:b-bgqa8h) ([raw file](https://github.com/RobotLocomotion/drake/blob/caf7ceb39e3a14aa491d1df0e1e57596dfc4ed92/geometry/query_object.h#L318)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.

FYI, I used this command to check doxygen:

 bazel run //doc/doxygen_cxx:build -- --serve --quick drake.geometry

</blockquote></details>

Yep. You got what I was going for.
___
*[`geometry/query_object.h` line 327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NWI-yIf4DDgFcvfWFSM:-NWI-yIf4DDgFcvfWFSN:b-o8hfnj) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5d6ae85e0a377dab7c574beee053201bad8ce13/geometry/query_object.h#L327)):*
> ```objc
> 
>      - ᵃ For compliant Mesh, please specify a tetrahedral mesh
>          in VTK file in Mesh(filename). This external working
> ```

nit: grammar

Same applies to "in __*an*__ OBJ", etc. Multiple times.



_Suggestion:_
```objc
in a VTK
```
___
*[`geometry/query_object.h` line 330 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NWI06J4AzHvyN2XvKjU:-NWI06J4AzHvyN2XvKjV:bhb0i3u) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5d6ae85e0a377dab7c574beee053201bad8ce13/geometry/query_object.h#L330)):*
> ```objc
>          <a href="https://docs.google.com/document/d/1VZtVsxIjOLKvgQ8SNSrF6PtWuPW5z9PP7-dQuxfmqpc/edit?usp=sharing">
>          document</a> provides guidance how to generate a tetrahedral mesh
>          in VTK file from a surface mesh in Obj file.
> ```

nit: consistency. If you capitalize VTK you should probably likewise capitalize OBJ.



_Suggestion:_
```objc
in an OBJ file
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[`geometry/query_object.h` line 327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NWI-yIf4DDgFcvfWFSM:-NWJ2D7B6iAISgPsXLlY:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5d6ae85e0a377dab7c574beee053201bad8ce13/geometry/query_object.h#L327)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: grammar

Same applies to "in __*an*__ OBJ", etc. Multiple times.
</blockquote></details>

Done. Thanks.
___
*[`geometry/query_object.h` line 330 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-NWI06J4AzHvyN2XvKjU:-NWJ2FRj8SWezpG36OAc:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5d6ae85e0a377dab7c574beee053201bad8ce13/geometry/query_object.h#L330)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: consistency. If you capitalize VTK you should probably likewise capitalize OBJ.
</blockquote></details>

Done. Thanks.

**Review by DamrongGuoy — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19411#-:-NWJ2rdrAPyScLf_sVZc:b3dcro0)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
