### PR TITLE
framework: Remove more heap allocations from events

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #14543

Remove unnecessary heap allocations from the rest of the event system.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15101)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@joemasterjohn for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15101#-:-MaoeriGEizTn2mCjMrU:b-3ya7ei)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by rpoyner-tri — COMMENTED** [review]
FYI @edrumwri -- this is the end of the #4543 allocations.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15101#-:-MaogjvT4-115guSij2h:b-z4svbg)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
Nice, pretty easy :lgtm: +@sammy-tri for platform review, please.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15101#-:-MbCSYcTBDz9Slo5uEPE:bhzz14o)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
___
*[systems/framework/event_collection.h, line 432 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15101#-MbCUs0F3ISvJDEIj1N-:-MbCUs0G1znXR43wXi3S:bu7ao5m) ([raw file](https://github.com/robotlocomotion/drake/blob/b12934227e9d4d30af28ab9d9e4f3f378877af72/systems/framework/event_collection.h#L432)):*
> ```objc
>     const std::vector<const EventType*>& other_events = other.get_events();
>     for (const EventType* other_event : other_events) {
>       this->AddEvent(std::move(*other_event));
> ```

nit Does `move` do anything useful when applied to a `const EventType`?  On first read at least, this seems like a misleading change, but maybe I'm missing a subtlety.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15101)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

___
*[systems/framework/event_collection.h, line 432 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15101#-MbCUs0F3ISvJDEIj1N-:-MbC_nDmE-R2bWnUA8jl:b-67zig5) ([raw file](https://github.com/robotlocomotion/drake/blob/b12934227e9d4d30af28ab9d9e4f3f378877af72/systems/framework/event_collection.h#L432)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Does `move` do anything useful when applied to a `const EventType`?  On first read at least, this seems like a misleading change, but maybe I'm missing a subtlety.
</blockquote></details>

I could be wrong, but the choice of move was made based on discussion here: https://github.com/robotlocomotion/drake/pull/15081#pullrequestreview-669462939

I'll try adding `const` various ways to Sean's example program and see what results.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15101)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

___
*[systems/framework/event_collection.h, line 432 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15101#-MbCUs0F3ISvJDEIj1N-:-MbCahgK9Lc4FZL0kQL3:bge4r1c) ([raw file](https://github.com/robotlocomotion/drake/blob/b12934227e9d4d30af28ab9d9e4f3f378877af72/systems/framework/event_collection.h#L432)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I could be wrong, but the choice of move was made based on discussion here: https://github.com/robotlocomotion/drake/pull/15081#pullrequestreview-669462939

I'll try adding `const` various ways to Sean's example program and see what results.
</blockquote></details>

In my local experiment, `const` does defeat any benefit of `move`.

**Comment by jwnimmer-tri** [comment]
___
*[systems/framework/event_collection.h, line 432 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15101#-MbCUs0F3ISvJDEIj1N-:-MbCbPRN3iKvT-vWdjeu:bb1b9ne) ([raw file](https://github.com/robotlocomotion/drake/blob/b12934227e9d4d30af28ab9d9e4f3f378877af72/systems/framework/event_collection.h#L432)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

In my local experiment, `const` does defeat any benefit of `move`.
</blockquote></details>

Yes, I'm quite happy with the design of pass-by-value for `AddEvent` -- it provides the best mnemonics in cases where the caller is able to donate the value to the callee.  In this case, though, since the `other` collection is const, we must always eat a copy _somewhere_, and this is a fine place for it.  The only problem is `move` misleading the reader to infer no-copy.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15101#-:-MbD3Ivj1QOjckapxp34:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),joemasterjohn (waiting on @rpoyner-tri)

**Pull request merged**
