### PR TITLE
Install lcm spy

### PR DESCRIPTION
**Pull request by fbudin69500**
This may be necessary for Spartan which builds `libbot`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7802)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-:-L3TQhTNbAB5A25-dIWL:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Needs some lint fixing.

:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tools/install/install.py.in, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-L3TSwX2GvQ9n6JJPGgG:-L3TSwX2GvQ9n6JJPGgH:bw61gr6) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2b73ede600adde480e948648d0486a3d0eab70/tools/install/install.py.in#L224)):*
> ```
>     # In list-only mode, just display the filename, don't do any real work.
>     print("[Generating] %s" % filename)
>     if list_only:
> ```

In `list_only` mode, the output should be exactly and only a list of filenames, never progress text like `[Generating]`.

---

*[tools/install/install.py.in, line 252 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-L3TU6L-jlPEp9v-H1hp:-L3TU6L-jlPEp9v-H1hq:b-m5npwc) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2b73ede600adde480e948648d0486a3d0eab70/tools/install/install.py.in#L252)):*
> ```
> 
> java %s %s "$@"
> """ % (strclasspath, jvm_flags, main_class)
> ```

FYI Consider using `.format()` not `%`, for easier reading.

---

*[tools/skylark/drake_java.bzl, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-L3TTb7W2a1VlQugZz0H:-L3TTb7W2a1VlQugZz0I:b-g9jzcq) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2b73ede600adde480e948648d0486a3d0eab70/tools/skylark/drake_java.bzl#L15)):*
> ```Python
>             classpath = classpath,
>             filename = ctx.attr.filename,
>             jvm_flags = " ".join(ctx.attr.jvm_flags)
> ```

The place that emits the python code (`install.bzl` near 288) is the place that should handle type conversion and quoting, not here where we're merely proxying the metadata.

---

*[tools/workspace/lcm/package.BUILD.bazel, line 279 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-L3TRNZr4G1fN2NvP03r:-L3TRNZs2ovoNFTj410z:bx0qo87) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2b73ede600adde480e948648d0486a3d0eab70/tools/workspace/lcm/package.BUILD.bazel#L279)):*
> ```
>         ":lcm-logplayer",
>         ":lcm-spy",
>         ":lcm-spy-launcher",
> ```

The documentation on `drake_java.bzl` does not tell the user that it is going to create `${name}-launcher`.  It took me a few minutes to figure out where this target is coming from.

At a minimum, the docs there need a tweak.

However, I would prefer if `drake_java_binary` got a new argument such as `launcher_name = `lcm-spy-launcher` where the caller would have to specify the launcher explicitly.  In general BUILD rules should be immediately obvious, so creating targets that the user has to know about, but didn't explicitly name, tends to be a surprise.

If you want to fix that (across the tree) a follow-up PR, that's fine by me; just dismiss this discussion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-:-L3TSnsRFhbULRZQyfSs:b-r6134c)*

**Comment by jwnimmer-tri** [comment]
FYI I tested this locally and it seemed to work OK.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-:-L3Tahc3SvFSOkwoHEog:b-aiej84)*

**Comment by fbudin69500** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/install/install.py.in, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-L3TSwX2GvQ9n6JJPGgG:-L3ZzsW618k99StmM-Ko:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2b73ede600adde480e948648d0486a3d0eab70/tools/install/install.py.in#L224)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In `list_only` mode, the output should be exactly and only a list of filenames, never progress text like `[Generating]`.
</blockquote></details>

Done.

---

*[tools/install/install.py.in, line 252 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-L3TU6L-jlPEp9v-H1hp:-L3Zzt1NywIq1PrMk4yI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2b73ede600adde480e948648d0486a3d0eab70/tools/install/install.py.in#L252)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider using `.format()` not `%`, for easier reading.
</blockquote></details>

Done.

---

*[tools/skylark/drake_java.bzl, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-L3TTb7W2a1VlQugZz0H:-L3_-eBb1gIQETsyUw8i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2b73ede600adde480e948648d0486a3d0eab70/tools/skylark/drake_java.bzl#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The place that emits the python code (`install.bzl` near 288) is the place that should handle type conversion and quoting, not here where we're merely proxying the metadata.
</blockquote></details>

Done.

---

*[tools/workspace/lcm/package.BUILD.bazel, line 279 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7802#-L3TRNZr4G1fN2NvP03r:-L3_2VqNhFBDlngU2kEl:b-sjl4gq) ([raw file](https://github.com/robotlocomotion/drake/blob/bc2b73ede600adde480e948648d0486a3d0eab70/tools/workspace/lcm/package.BUILD.bazel#L279)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The documentation on `drake_java.bzl` does not tell the user that it is going to create `${name}-launcher`.  It took me a few minutes to figure out where this target is coming from.

At a minimum, the docs there need a tweak.

However, I would prefer if `drake_java_binary` got a new argument such as `launcher_name = `lcm-spy-launcher` where the caller would have to specify the launcher explicitly.  In general BUILD rules should be immediately obvious, so creating targets that the user has to know about, but didn't explicitly name, tends to be a surprise.

If you want to fix that (across the tree) a follow-up PR, that's fine by me; just dismiss this discussion.
</blockquote></details>

The documentation was made more explicit. An issue was added to the issue tracker to add a parameter to drake_java_binary: https://github.com/RobotLocomotion/drake/issues/7842

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7802)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7802)*

**Pull request merged**
