### PR TITLE
[geometry/optimization] Remove self loop edges from GCS ShortestPath

### LINKED ISSUE #18076: Self Loop Leads to Unusual Error in GraphOfConvexSets
### What happened?

It's not clear whether or not the underlying graph structure in GraphOfConvexSets should allow self loops. Although the theoretical formulation allows for self-loops, they won't affect the outcome of the problem. However, adding a self loop in the drake formulation will throw an error when one tries to solve the problem (but not when one actually defines the edge, which in turn leads to the problem). Also, the error message doesn't state that the cause of the problem is the self loop, it simply states, `Failure at solvers/gurobi_solver.cc:1095 in DoSolve(): condition 'num_gurobi_linear_constraints == num_gurobi_linear_constraints_expected' failed.`

I think any of the following three changes might help with this situation:
1. When an edge is added to the graph, check that it's not a self loop (and throw an error if it is).
2. Check for self loops when setting up the optimization problem, and throw an error if any are present.
3. Modify GraphOfConvexSets to be able to handle self loops in the optimization problem.

### Version

45971d6c0c

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

```shell
# The following program will successfully solve a GCS problem.
# Un-commenting the line containing `#[left, left]` in the definition of `E` will cause it to fail with the above error message.

import numpy as np

from pydrake.all import HPolyhedron, Point, GraphOfConvexSets, GraphOfConvexSetsOptions, L2NormCost, Binding

def graph_of_convex_sets_example(convex_relaxation = False):
    b = np.array([-1, -1, 4])
    A_left = np.array([[1,1], [1, -1], [-1, 0]])
    A_right = np.array([[-1,-1], [-1, 1], [1, 0]])
    A_top = np.array([[-1,-1], [1, -1], [0, 1]])
    A_bottom = np.array([[1,1], [-1, 1], [0, -1]])

    H_left = HPolyhedron(A_left, b)
    H_right = HPolyhedron(A_right, b)
    H_top = HPolyhedron(A_top, b)
    H_bottom = HPolyhedron(A_bottom, b)

    G = GraphOfConvexSets()
    source = G.AddVertex(Point([0.2, -2]), "source")
    left =  G.AddVertex(H_left, "left")
    right = G.AddVertex(H_right, "right")
    top =     G.AddVertex(H_top, "top")
    bottom =    G.AddVertex(H_bottom, "bottom")
    target = G.AddVertex(Point([0, 2]), "target")

    E = [
    	#[left, left],
        [source, left],
        [source, bottom],
        [source, right],
        [bottom, left],
        [bottom, right],
        [left, top],
        [right, top],
        [left, target],
        [top, target],
        [right, target],
    ]

    cost = L2NormCost(A=np.block([np.eye(2), -np.eye(2)]), b=np.zeros((2,1)))
    for u,v in E:
        e = G.AddEdge(u, v)
        e.AddCost(Binding[L2NormCost](cost, np.concatenate([e.xu(),
                                                            e.xv()])))

    options = GraphOfConvexSetsOptions()
    options.convex_relaxation = convex_relaxation
    result = G.SolveShortestPath(source, target, options)
    
    print(result.is_success())

graph_of_convex_sets_example()
```

### PR DESCRIPTION
**Pull request by mpetersen94**
Implements solution 3 from the issue by not including self edges in the optimization and logging a warning that a self loop edge in the graph is being ignored.

Closes #18076

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18082)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@cohnt @TobiaMarcucci @RussTedrake

**Review by RussTedrake — COMMENTED** [review]
+@russtedrake for feature review.

To be clear, if there was no constraints on the edge, then can we guarantee that for any optimal path that includes the self-loop, then the path with that self-loop removed would also be optimal?  (If yes, then I think in that case we could remove it without warning, and set the corresponding phi to be zero in the result)?

If there is a constraint on the edge, then I think it gets more tricky, right?  For instance, if I had a graph with the X_source = {1}, X_target = {3}, and X_middle = R; with edges from source to middle to target and a self-loop in the middle, all with the constraint that xv = xu+1, then perhaps the shortest path *would* contain the self-loop?

It might be that ignoring self loop and throwing a log is reasonable, but let's agree on the scope first?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18082#-:-NE7tkHqAkn-0aI90eaf:bdp5buu)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes

**Comment by RussTedrake** [comment]
oops.  X_target = {4}.  ;-)

**Comment by TobiaMarcucci** [comment]
I just spoke with Russ, and we agreed that self-edges can never be optimal. However, we also think that rather than removing self-edges from the optimization problem, it'd be more important to actually understand why Tommy got the Gurobi error that he got by asking to solve the problem with self edges? Since in principle, unless we are missing some detail, Gurobi should not complain and just solve the problem and return an optimal solution that assigns zero flow to that self edge. With this PR it seems to me that we are not actually solving the bug that Tommy encountered? But we are rather ensuring that the user is never exposed to that bug?

**Comment by bernhardpg** [comment]
Why can't the self-edge be optimal for Russ' example @TobiaMarcucci ? Isn't the only feasible path to travel along the self-edge and visit X_middle twice?

However, on another note: with the current GCS formulation, there is only one set of decision variables for each vertex, even if there is a self-edge and a self-loop is technically permitted. For @RussTedrake's example, doesn't this mean that there could only be one value for X_middle, i.e. the same value for both visits, rendering the problem infeasible?

**Comment by TobiaMarcucci** [comment]
@bernhardpg The reason why it is not optimal is exactly what you write in the second part of you message: because the continuous variable is only one.

**Comment by TobiaMarcucci** [comment]
@RussTedrake Thinking more about this though, I think that the convex relaxation can get looser by adding self-edges. I've an example in mind similar to the one in the paper. I can give more details if needed.

So I think the best thing would be the following:

1. Figure out why Gurobi is throwing an error, since it should be because of some bug that we have not identified yet.
2. Understand if self-cycles can actually make the convex relaxation looser. They certainly should not affect the optimal cost of the mixed integer program.
3. If self-edges can deteriorate the convex relaxation, then we can either neglect them at solution time or throw an error when they are added to the GCS. Personally I would vote for the second. Because I think that the only scenario in which a user would ass self-edges is when he/she didn't get that since the continuous variable attached to a vertex is only one, adding self loops Is never useful. Therefore by throwing an error in that scenario we can tell the user directly that his/her understanding of the problem is wrong. On the other hand, turning off the self-edge at solve time would be correct but this user would have a hard time realizing that his/her understanding of the problem statement is incorrect.

**Comment by bernhardpg** [comment]
I second @TobiaMarcucci's opinion! Allowing self-edges without allowing different values for the different visits to the vertices only sounds like a big cause of confusion to me.

**Comment by RussTedrake** [comment]
Where in the "contract" (e.g. api documentation), precisely, should we have introduced the concept that multiple visits to the same set are disallowed by construction?  It's not obviously disallowed from the way that the general graph of convex sets machinery is described here.  Is it a restriction that we introduce at the GCS level?  Or at the GCS::SolveShortestPath level?  I think we need to document it; otherwise it would be reasonable for someone to author a graph with my example and be surprised by the result.

I'm ok with throwing the error, even though we know how to handle it properly.  It's a little unkind to the user in the short term, but I can buy your argument that it is kinder to them in the longer term.

**Comment by TobiaMarcucci** [comment]
I would disallow it at the GCS level and, yes, it should be carefully explained why it is disallowed (it could be handled fine, but it weakens the formulation and it can never be useful).

**Comment by mpetersen94** [comment]
My takeaway from this discussion is that I should:
1) Investigate what causes Gurobi to throw the error when there is a self loop in the graph.
2) Change the contract of GCS to disallow adding a self loop edge to the graph and throw when a user tries to.
I'll look into all of this tomorrow!

**Comment by TobiaMarcucci** [comment]
Yes, let's just double check that the relaxation can actually get weaker when there are self edges.

**Comment by RussTedrake** [comment]
I will add the do not review tag until you've done those checks.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18082)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

**Review by RussTedrake — COMMENTED** [review]
@mpetersen94 , @TobiaMarcucci , @cohnt -- what is the status / plan for this?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18082#-:-NO7clOy6vz_Unthz_2W:b-4jd0qm)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

**Comment by cohnt** [comment]
I'm not really sure what the status is here. Note that the error in #18076 still occurs, even with the fixes pushed to the solvers. So this change would be helpful, but ultimately shouldn't be necessary, since there's a bug somewhere else.

**Pull request closed without merging**
