### PR TITLE
Add eigen3 to appropriate pkg-config files

### PR DESCRIPTION
**Pull request by jamiesnape**
Apparently no-one has added explicitly added eigen3 to anything, so looks like I will need to do this again for CMake.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4165)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4165#-:-KWsFdAP4yofTMpgSRd_:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4165#-:-KWs_l_WkulPUHz-IwNC:bnfp4nl)*

**Pull request merged**
