### PR TITLE
Fix optitrack_client install

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7372)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@sammy-tri for feature review and local testing.

**Comment by sammy-tri** [comment]
:lgtm:

Thanks Jamie!  This looks easier than trying to figure out how to install the bazel-built optitrack artifacts.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-:-KxiqpkbGpI5tBvFPdDs:bm7bxsz)*

**Comment by sammy-tri** [comment]
Also, I did test locally and it works for me.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-:-KxirFfaPRw6mbMsa2N5:b-oopvx)*

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for platform review.

**Comment by EricCousineau-TRI** [comment]
First pass with some general questions about the `optitrack_client` script.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/optitrack_driver/optitrack_client, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-Kxj8T6rV61yu2HQyC2j:-Kxj8T6sVfKhqcNG7FQS:ba8hhmw) ([raw file](https://github.com/robotlocomotion/drake/blob/dcfed63b502384f11b51c51239f211d6f852c5d3/tools/workspace/optitrack_driver/optitrack_client#L8)):*
> ```
> 
> def main():
>     python_program = None
> ```

Can I ask why this is searching for `python2`, when the shebang is already present? (AFAIK, this wouldn't be able to execute unless executed under `python2`.)
Should this instead just use `sys.executable`?

Also, since we use `#!/usr/bin/env python` rather than `... python2` in other shebangs, should we try to keep that consistent?
(Is this specifically for the Mac issue? If so, I believe this is, at present, only used on Linux machines...)

---

*[tools/workspace/optitrack_driver/optitrack_client, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-Kxj9AzqymM8jZh9v-EL:-Kxj9AzqymM8jZh9v-EM:bsclu7e) ([raw file](https://github.com/robotlocomotion/drake/blob/dcfed63b502384f11b51c51239f211d6f852c5d3/tools/workspace/optitrack_driver/optitrack_client#L24)):*
> ```
>         raise AssertionError('Could not find python2 executable')
> 
>     python_path = os.path.abspath(os.path.join(
> ```

Can I ask if this is meant to address a Bazel-based workflow or a install-based workflow?
This seems to be structured to emulate a working `PYTHONPATH` -- but shouldn't that be an implicit prerequisite of having installed the files and wishing to use them?

Could `execfile` be used instead? Unless `optitrack_client.py` depends on `sys.argv[0]`, it should work as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-:-Kxj9h6xXZeuhlR-9KGe:b-leerdl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/optitrack_driver/optitrack_client, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-Kxj9AzqymM8jZh9v-EL:-KxjAn4pC4UJnMGOojd0:b-8wbxdw) ([raw file](https://github.com/robotlocomotion/drake/blob/dcfed63b502384f11b51c51239f211d6f852c5d3/tools/workspace/optitrack_driver/optitrack_client#L24)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can I ask if this is meant to address a Bazel-based workflow or a install-based workflow?
This seems to be structured to emulate a working `PYTHONPATH` -- but shouldn't that be an implicit prerequisite of having installed the files and wishing to use them?

Could `execfile` be used instead? Unless `optitrack_client.py` depends on `sys.argv[0]`, it should work as-is.
</blockquote></details>

For the install, but it is replicating the wrapper provided by Bazel, so it is true to the behavior of that script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7372)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/optitrack_driver/optitrack_client, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-Kxj9AzqymM8jZh9v-EL:-KxjCVRCz-45aCRlFDRA:ba6nk9x) ([raw file](https://github.com/robotlocomotion/drake/blob/dcfed63b502384f11b51c51239f211d6f852c5d3/tools/workspace/optitrack_driver/optitrack_client#L24)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

For the install, but it is replicating the wrapper provided by Bazel, so it is true to the behavior of that script.
</blockquote></details>

I was able to get it working with the following setup:

`build_install/bin/optitrack_client`:
```
#!/usr/bin/env python
from optitrack.optitrack_client import main
main()
```

In my terminal:
```
$ bazel run //:install -- ~+/build_install
$ fhs-extend ~+/build_install  # Sets up PYTHONPATH, PATH, LD_LIBRARY_PATH, etc.
$ ./build_install/bin/optitrack_client -h
usage: optitrack_client [-h] [--multicast-address MULTICAST_ADDRESS]           │In [2]: optitrack.
                        [--local-address LOCAL_ADDRESS]                        │optitrack.optitrack_data_descriptions_t
```

Can I ask if we could use something like this, and not expect the script to set up the environment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7372)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/optitrack_driver/optitrack_client, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-Kxj9AzqymM8jZh9v-EL:-KxjDjfHFLcEstTW6226:bkd8h8b) ([raw file](https://github.com/robotlocomotion/drake/blob/dcfed63b502384f11b51c51239f211d6f852c5d3/tools/workspace/optitrack_driver/optitrack_client#L24)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I was able to get it working with the following setup:

`build_install/bin/optitrack_client`:
```
#!/usr/bin/env python
from optitrack.optitrack_client import main
main()
```

In my terminal:
```
$ bazel run //:install -- ~+/build_install
$ fhs-extend ~+/build_install  # Sets up PYTHONPATH, PATH, LD_LIBRARY_PATH, etc.
$ ./build_install/bin/optitrack_client -h
usage: optitrack_client [-h] [--multicast-address MULTICAST_ADDRESS]           │In [2]: optitrack.
                        [--local-address LOCAL_ADDRESS]                        │optitrack.optitrack_data_descriptions_t
```

Can I ask if we could use something like this, and not expect the script to set up the environment?
</blockquote></details>

Depends if you want the same behavior as the Bazel build. That was the specification I was working from. @sammy-tri what would you prefer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7372)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/optitrack_driver/optitrack_client, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-Kxj9AzqymM8jZh9v-EL:-KxjKhhBsVLSknYXp209:bap8wjv) ([raw file](https://github.com/robotlocomotion/drake/blob/dcfed63b502384f11b51c51239f211d6f852c5d3/tools/workspace/optitrack_driver/optitrack_client#L24)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Depends if you want the same behavior as the Bazel build. That was the specification I was working from. @sammy-tri what would you prefer?
</blockquote></details>

Talked to @sammy-tri, and he would like to maintain being able to execute the script without a stateful terminal (e.g. sourcing `setup.bash`).

In that case, could this script be compacted to the following?
```
#!/usr/bin/env python
# Inject path to enable running without extending FHS environment variables.
import os
import sys
_install_prefix = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
sys.path.insert(
    0, os.path.join(_install_prefix, 'lib/python2.7/site-packages'))
from optitrack.optitrack_client import main
main()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7372)*

**Comment by jamiesnape** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/optitrack_driver/optitrack_client, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-Kxj8T6rV61yu2HQyC2j:-KxmPGsvc8wNiODFGWN6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcfed63b502384f11b51c51239f211d6f852c5d3/tools/workspace/optitrack_driver/optitrack_client#L8)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can I ask why this is searching for `python2`, when the shebang is already present? (AFAIK, this wouldn't be able to execute unless executed under `python2`.)
Should this instead just use `sys.executable`?

Also, since we use `#!/usr/bin/env python` rather than `... python2` in other shebangs, should we try to keep that consistent?
(Is this specifically for the Mac issue? If so, I believe this is, at present, only used on Linux machines...)
</blockquote></details>

Done.

---

*[tools/workspace/optitrack_driver/optitrack_client, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-Kxj9AzqymM8jZh9v-EL:-KxmPIh6UyALHSb_D9un:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcfed63b502384f11b51c51239f211d6f852c5d3/tools/workspace/optitrack_driver/optitrack_client#L24)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Talked to @sammy-tri, and he would like to maintain being able to execute the script without a stateful terminal (e.g. sourcing `setup.bash`).

In that case, could this script be compacted to the following?
```
#!/usr/bin/env python
# Inject path to enable running without extending FHS environment variables.
import os
import sys
_install_prefix = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
sys.path.insert(
    0, os.path.join(_install_prefix, 'lib/python2.7/site-packages'))
from optitrack.optitrack_client import main
main()
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7372)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7372#-:-KxmrxyYKTVHddBLGG9r:bpqxd5f)*

**Pull request merged**
