### PR TITLE
Add and use drake::temp_directory function instead of using /tmp

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #8470. I guess I could write a `temp_directory(_path)_tool` for use in shell scripts, but that may well be overkill. I am trying to match the naming of `std::filesystem::temp_directory_path()` here. Since it does not return a `std::filesystem::path`, I left off the `_path`, but I would not really have a problem with calling this `drake::temp_directory_path()` regardless.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8471)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
I have no idea about `call_python_full_test.sh`.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Pausing for now, until first round of design Q&A resolve.

---

Reviewed 7 of 19 files at r1.
Review status: 7 of 19 files reviewed at latest revision, all discussions resolved.

---

*[automotive/automotive_simulator.cc, line 447 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpnzL2sYaRskKE8k-:-L8mpnzL2sYaRskKE8k0:bss14vz) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/automotive/automotive_simulator.cc#L447)):*
> ```cpp
>   std::transform(filename.begin(), filename.end(), filename.begin(),
>                  [](char ch) { return ch == ' ' ? '_' : ch; });
>   const std::string tmpdir = drake::temp_directory();
> ```

So clearly this is better than hard coding, but if we are going to offer a non-testonly helper function, I think we'd best look more towards `mkdtemp` in cases where `TEST_TMPDIR` is undefined, so that our prod code doesn't expose us to symlink attacks or any of the other faults related to hard-coded paths in `/tmp` (even if indirected through `$TMPDIR`).

I do not think this would harm CI, since all uses should be within test rules, and I think I'm willing to live with cruft lingering in `/tmp/fooijsadf.9387` or whatever for prod code.

In which case, probably offering a suffix or prefix hint as in https://docs.python.org/3/library/tempfile.html might be nice also, so that when the files to linger in /tmp, we can more easily blame who made them.  (Or possibly this macro should always write a `blame.txt` with the argv[0] or something, instead of prefix arg?)

---

*[common/proto/call_matlab.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8moTmN6f5BzSS2xl3U:-L8moTmN6f5BzSS2xl3V:b1g1xn9) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/common/proto/call_matlab.h#L25)):*
> ```objc
> /// To play the remote calls in matlab, simply run call_matlab_client from your
> /// matlab terminal.  For synchronous playback, use a named pipe by running
> ///    `mkfifo "${TMPDIR}/matlab_rpc"`
> ```

I think the call_matlab and call_python stuff is intended to be an ugly duckling and hard-code /tmp everywhere for "convenience" (grumble).  I'd at least ask that the fraction of this PR that touches that feature (the `common/proto` and `matlab` folders) be split off to a future PR, where the call_foo experts and users can weigh in.

---

*[solvers/BUILD.bazel, line 575 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpPPZ9rdE3BaCRrYF:-L8mpPPZ9rdE3BaCRrYG:be1hnn8) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/solvers/BUILD.bazel#L575)):*
> ```Python
>         "//tools:with_snopt": [
>             ":mathematical_program_api",
>             "//common:temp_directory",
> ```

I think maybe only the test needs this, not the solver library itself?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-:-L8mqlvgBFuooA2-Qhg7:b-4yzd64)*

**Comment by jamiesnape** [comment]
Review status: 7 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/automotive_simulator.cc, line 447 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpnzL2sYaRskKE8k-:-L8mredRDQmZUeEmRHb2:biw4gka) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/automotive/automotive_simulator.cc#L447)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So clearly this is better than hard coding, but if we are going to offer a non-testonly helper function, I think we'd best look more towards `mkdtemp` in cases where `TEST_TMPDIR` is undefined, so that our prod code doesn't expose us to symlink attacks or any of the other faults related to hard-coded paths in `/tmp` (even if indirected through `$TMPDIR`).

I do not think this would harm CI, since all uses should be within test rules, and I think I'm willing to live with cruft lingering in `/tmp/fooijsadf.9387` or whatever for prod code.

In which case, probably offering a suffix or prefix hint as in https://docs.python.org/3/library/tempfile.html might be nice also, so that when the files to linger in /tmp, we can more easily blame who made them.  (Or possibly this macro should always write a `blame.txt` with the argv[0] or something, instead of prefix arg?)
</blockquote></details>

Maybe,  the intention was match C++17 using save for `TEST_TMPDIR`.

---

*[common/proto/call_matlab.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8moTmN6f5BzSS2xl3U:-L8mrGE65axCCKJL9G6l:bf9rk7u) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/common/proto/call_matlab.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the call_matlab and call_python stuff is intended to be an ugly duckling and hard-code /tmp everywhere for "convenience" (grumble).  I'd at least ask that the fraction of this PR that touches that feature (the `common/proto` and `matlab` folders) be split off to a future PR, where the call_foo experts and users can weigh in.
</blockquote></details>

Well this the main offender, so not sure whether this PR is even needed without it (certainly it would be overkill).

---

*[solvers/BUILD.bazel, line 575 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpPPZ9rdE3BaCRrYF:-L8msc577TJ_QJRwVUMz:b-64lgb6) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/solvers/BUILD.bazel#L575)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think maybe only the test needs this, not the solver library itself?
</blockquote></details>

Yes, my mistake.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/automotive_simulator.cc, line 447 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpnzL2sYaRskKE8k-:-L8msw0PB54b8FPioY_p:b-4nmbh4) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/automotive/automotive_simulator.cc#L447)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Maybe,  the intention was match C++17 using save for `TEST_TMPDIR`.
</blockquote></details>

Right, I understood and considered that.  I think we need the prod code to be careful about this attack surface though, so with the `std` semantics we'd need to write a wrapper anyway that make a secure subdir within the `std` result, and I figure if we have to write that anyway, there's not much point to exposing the `std` semantics in the first place.

However, I guess I'm seeing now (once I skim the call_foo stuff) is that we want a way to use TEST_TMPDIR when tested, but `/tmp` in prod.  Maybe that's a good start (hard-coding tmp, and not listing all of the optional TMPDIR stuffs), with a TODO about the symlink attacks etc?

---

*[common/proto/call_matlab.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8moTmN6f5BzSS2xl3U:-L8mtWqyBpbAkZsNpYum:b-y10ehi) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/common/proto/call_matlab.h#L25)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Well this the main offender, so not sure whether this PR is even needed without it (certainly it would be overkill).
</blockquote></details>

I think there's still a bunch of C++ unit tests that assume `.` is the correct writable tempdir, so they would definitely use a `TEST_TMPDIR` helper, so I don't think its overkill in general, at least for test purposes.

If the pain point is the call_foo stuff though, then maybe that PR happens first?  Or at least ask the call_foo users what the right goal is, that also meets CI needs.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jamiesnape** [comment]
Review status: 7 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/automotive_simulator.cc, line 447 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpnzL2sYaRskKE8k-:-L8mwMfnChua1SbrH7vJ:b-kp0284) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/automotive/automotive_simulator.cc#L447)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

So what you would like is `TEST_TMPDIR` if defined, else `mkdtemp("/tmp/drakeXXXXXX")` or similar?
</blockquote></details>

(except for the `call_foo` things for now, I guess)

---

*[common/proto/call_matlab.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8moTmN6f5BzSS2xl3U:-L8mviMf6D3VXr91AYGb:b-tiuiwj) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/common/proto/call_matlab.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think there's still a bunch of C++ unit tests that assume `.` is the correct writable tempdir, so they would definitely use a `TEST_TMPDIR` helper, so I don't think its overkill in general, at least for test purposes.

If the pain point is the call_foo stuff though, then maybe that PR happens first?  Or at least ask the call_foo users what the right goal is, that also meets CI needs.
</blockquote></details>

So for now `TEST_TMPDIR` or `/tmp`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jwnimmer-tri** [comment]
*[common/proto/call_matlab.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8moTmN6f5BzSS2xl3U:-L8mxY4F00SaTtWeZgcZ:by4knzu) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/common/proto/call_matlab.h#L25)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

So for now `TEST_TMPDIR` or `/tmp`?
</blockquote></details>

Hmm.

So I am remembering now that one of the points of `call_python` is to _write to /tmp even during unit tests_ so that someone with a receiving console can watch the debugging visualizations.  So even using TEST_TMPDIR by default when its set is probably a regression for those users.

Since it sounds like this is the most acute issue for CI, I wonder if we should just explore the call_foo stuff first.

Given the "watch my test run" use case, I guess I'd need to know more about in what way this is causing trouble in CI, before I can suggest a final answer.  My rough understanding is that all of the paths are hard-coded, so why would they grow without bound?  Do some tmp filesnames also have random salt?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jamiesnape** [comment]
Review status: 7 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/proto/call_matlab.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8moTmN6f5BzSS2xl3U:-L8mzLBj8HYExKHLz7iM:b-j667s3) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/common/proto/call_matlab.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm.

So I am remembering now that one of the points of `call_python` is to _write to /tmp even during unit tests_ so that someone with a receiving console can watch the debugging visualizations.  So even using TEST_TMPDIR by default when its set is probably a regression for those users.

Since it sounds like this is the most acute issue for CI, I wonder if we should just explore the call_foo stuff first.

Given the "watch my test run" use case, I guess I'd need to know more about in what way this is causing trouble in CI, before I can suggest a final answer.  My rough understanding is that all of the paths are hard-coded, so why would they grow without bound?  Do some tmp filesnames also have random salt?
</blockquote></details>

Yes for some and for others they persist between builds so our builds may have state if things go wrong.

Plus it is highly incorrect for a Bazel test to write outside its sandbox (and a behavior they could disallow in future).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jamiesnape** [comment]
Review status: 7 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/proto/call_matlab.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8moTmN6f5BzSS2xl3U:-L8n12IG1nEmJkY_qnJg:blci9pz) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/common/proto/call_matlab.h#L25)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Yes for some and for others they persist between builds so our builds may have state if things go wrong.

Plus it is highly incorrect for a Bazel test to write outside its sandbox (and a behavior they could disallow in future).
</blockquote></details>

(Could they `bazel run` to get the old behavior as a compromise?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/automotive_simulator.cc, line 447 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpnzL2sYaRskKE8k-:-L8n1fdcDUFcTzAXvMl3:b-z1qugx) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/automotive/automotive_simulator.cc#L447)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

(except for the `call_foo` things for now, I guess)
</blockquote></details>

Yes, I would be happy with that.

I also talked myself into the "security" facet being a TODO also being fine, more like what's here already.

---

*[common/proto/call_matlab.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8moTmN6f5BzSS2xl3U:-L8n-uDV77PhAeGAeMMB:b-3j4nkr) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/common/proto/call_matlab.h#L25)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

(Could they `bazel run` to get the old behavior as a compromise?)
</blockquote></details>

Yes, I guess if the user wants to see the test visualization they'd have to turn off the test sandbox.  So I guess I'll buy that TEST_TMPDIR should win out for this case, and then use `bazel run` for when the user wants to watch the test program interactively.

So yes, I think for the `call_foo` stuff we have TEMP_TMPDIR if set, else hardcoded `/tmp` so that the non-testing ICD remains stable.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jamiesnape** [comment]
Review status: 5 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/automotive_simulator.cc, line 447 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpnzL2sYaRskKE8k-:-L8n59uA-Ckoz81v1BVj:bt261zg) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/automotive/automotive_simulator.cc#L447)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, I would be happy with that.

I also talked myself into the "security" facet being a TODO also being fine, more like what's here already.
</blockquote></details>

I added a TODO for this revision. Do you want a `drake::mkdtemp` function or make this the function that uses `mkdtemp` and have a different one for `call_foo`?

---

*[solvers/BUILD.bazel, line 575 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpPPZ9rdE3BaCRrYF:-L8n58YQ06zjt9QYwpFZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/solvers/BUILD.bazel#L575)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Yes, my mistake.
</blockquote></details>

Done.

---

*[common/proto/call_matlab.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8moTmN6f5BzSS2xl3U:-L8n5OCF0S1G51a3Q58q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/common/proto/call_matlab.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, I guess if the user wants to see the test visualization they'd have to turn off the test sandbox.  So I guess I'll buy that TEST_TMPDIR should win out for this case, and then use `bazel run` for when the user wants to watch the test program interactively.

So yes, I think for the `call_foo` stuff we have TEMP_TMPDIR if set, else hardcoded `/tmp` so that the non-testing ICD remains stable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@soonho-tri for platform review please.

---

Reviewed 7 of 19 files at r1, 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/automotive_simulator.cc, line 447 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8mpnzL2sYaRskKE8k-:-L8nAlk92Mx81nWwdBM4:b-26pl14) ([raw file](https://github.com/robotlocomotion/drake/blob/4452dfbf5755ba7fa6d9e9263605293a247e1b1e/automotive/automotive_simulator.cc#L447)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I added a TODO for this revision. Do you want a `drake::mkdtemp` function or make this the function that uses `mkdtemp` and have a different one for `call_foo`?
</blockquote></details>

OK I can argue myself either way.  My best guess for now is to treat call_foo as the special case, so that this function gains mkdtemp semantics, and then for call_foo we with have either:
- an optional argument here to turn off security, or
- a call_foo specific helper like get_call_foo_default_dir or getenv_or_else or something.

In other words, the only (permanent) option that I don't like is having a function directly in `common` that is insecure by default.

---

*[common/test/temp_directory_test.cc, line 18 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8nASYkB9xP6ckomfqt:-L8nASYkB9xP6ckomfqu:b-fmo3bd) ([raw file](https://github.com/robotlocomotion/drake/blob/8e63d4ec4e34c28ca4d9397517fb94661731a2c0/common/test/temp_directory_test.cc#L18)):*
> ```cpp
>   EXPECT_NE('/', tmpdir.back());
>   EXPECT_EQ(tmpdir, std::string(test_tmpdir));
> }
> ```

Missing test that when `TEST_TMPDIR` is unset, we see `"/tmp"`.  (Or if the sandbox defeats this somehow, a comment to that effect.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-:-L8nBY7NCi8Zg9WjIhXF:bavgfs)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test/temp_directory_test.cc, line 18 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8nASYkB9xP6ckomfqt:-L8nCIuH6d7fQ4fcP0Pe:b-tv92zp) ([raw file](https://github.com/robotlocomotion/drake/blob/8e63d4ec4e34c28ca4d9397517fb94661731a2c0/common/test/temp_directory_test.cc#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing test that when `TEST_TMPDIR` is unset, we see `"/tmp"`.  (Or if the sandbox defeats this somehow, a comment to that effect.)
</blockquote></details>

I guess so long as I restore `TEST_TMPDIR` afterward just in case it should be fine.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jwnimmer-tri** [comment]
*[common/test/temp_directory_test.cc, line 18 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471#-L8nASYkB9xP6ckomfqt:-L8nE3C78v7a70NT9z7J:b-fd97hp) ([raw file](https://github.com/robotlocomotion/drake/blob/8e63d4ec4e34c28ca4d9397517fb94661731a2c0/common/test/temp_directory_test.cc#L18)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I guess so long as I restore `TEST_TMPDIR` afterward just in case it should be fine.
</blockquote></details>

Yeah, I hadn't thought of that, but good point.  If it ends up something like ~10-20 LOC I think its worth confirming the fallback.  If its some yak shave then we can punt.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8471)*

**Pull request merged**
