### PR TITLE
SapDriver supports fixed constraints

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Also add an integration test for fixed constraints between deformable bodies and rigid bodies.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20249)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20249#-:-NfCjWxoBUqmXLDGeNNU:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
Very nice! :lgtm: +@rpoyner-tri for platform review, per schedule tomorrow. 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20249#-:-NfDEN5o479c2olVeewm:b9zggi)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20249)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20249#-NfDEsmz9F9S9Gl9LRU2:-NfDEsmz9F9S9Gl9LRU3:bfvvhqz) (no related file):*
Actually one follow up: I see you have `release notes: none`. Since this buttons up the PR train on fixed constraints and enables them in SAP, don't you want to include this in the release notes as a new feature?

___

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20249)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20249#-NfDEsmz9F9S9Gl9LRU2:-NfDHgx869e02mNOPJhc:b-jf2kn5) (no related file):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Actually one follow up: I see you have `release notes: none`. Since this buttons up the PR train on fixed constraints and enables them in SAP, don't you want to include this in the release notes as a new feature?
</blockquote></details>

See https://drake.mit.edu/release_playbook.html section "Polishing the release notes" on deformables.

We should start thinking about what pieces we need to fill in before we officially "release" the deformable feature.

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20249)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20249#-:-NfHHVG01qXwjEYLFtMs:bnfp4nl)* status: 1 unresolved discussion

**Pull request merged**
