### PR TITLE
[workspace] Upgrade rules_rust, rust_toolchain to latest

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
- Upgrade rules_rust to latest release 0.38.0
- Upgrade rust_toolchain to latest

Additionally, add repository metadata for rust_toolchain, make rules_rust and rust_toolchain cohorts, and remove no-longer-needed upgrade advice from rules_rust.

Towards #20868.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20901)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for review (both?), please (due to `new_release` changes)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-mirror-to-s3 please

**Comment by mwoehlke-kitware** [comment]
Hehe... I *did* copy the `downloads = {}` bit this time. Which... I think should be right, since the downloads are hung off `rust_toolchain_downloads` entries... only I can't seem to find any such? (This was on *master*, not this branch, so it shouldn't be a case of not seeing them because this PR broke them...)

**Review by jwnimmer-tri — COMMENTED** [review]
+(status: single reviewer ok)

Well, the jenkins job was useless: it built the tool, but didn't run it.  I'll try running it locally (in dry-run mode) instead.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-:-Nq4MD7-8hhmgcAvog2B:b-gzr7nl)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`tools/workspace/new_release.py` line 98 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-Nq4KWyD1fY0a8q1IjR2:-Nq4KWyE0qu2AO9lTnrP:b-uzzala) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83d02d4c9b0c247fb91865917edbe178d537309/tools/workspace/new_release.py#L98)):*
> ```Python
>     # clarabel_cpp uses crate_universe; be sure to keep them aligned.
>     {"clarabel_cpp_internal", "crate_universe"},
>     # rules_rust uses rust_toolchain; be sure to keep them aligned.
> ```

nit Do we want to keep the _COHORTS tuple alpha-sorted (with rules_rust inbetween between mypy and sdformat)?

**Review by jwnimmer-tri — COMMENTED** [review]
Ah, I forgot that I decided not to mirror the toolchain.  I'll post an inline comment below.

:lgtm: as no worse than previously.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-:-Nq4QqwHDQh8c7hk8muN:bn8lkq1)* status: 2 unresolved discussions

___
*[`tools/workspace/metadata.py` line 65 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-Nq4QxK-3Ob7TssSuFzY:-Nq4QxK-3Ob7TssSuFzZ:b-e48gaf) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83d02d4c9b0c247fb91865917edbe178d537309/tools/workspace/metadata.py#L65)):*
> ```Python
>         "repository_rule_type": "scripted",
>         "upgrade_script": "upgrade.py",
>         "downloads": {},
> ```

nit This is slightly misleading.  See the comment here:

https://github.com/RobotLocomotion/drake/blob/2cdf815d985be27b16b90e347d9fbadf42248983/tools/workspace/rust_toolchain/repository.bzl#L5-L7

There are downloads associated with the toolchain, we're just (purposefully) not wiring them up into the `metadata.py` for archiving.

My suggestion: add a comment here citing that file / comment.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20901)* status: 1 unresolved discussion

___
*[`tools/workspace/metadata.py` line 65 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-Nq4QxK-3Ob7TssSuFzY:-Nq4RgJJ7hMG_ktbKwB-:b-pyjmo) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83d02d4c9b0c247fb91865917edbe178d537309/tools/workspace/metadata.py#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is slightly misleading.  See the comment here:

https://github.com/RobotLocomotion/drake/blob/2cdf815d985be27b16b90e347d9fbadf42248983/tools/workspace/rust_toolchain/repository.bzl#L5-L7

There are downloads associated with the toolchain, we're just (purposefully) not wiring them up into the `metadata.py` for archiving.

My suggestion: add a comment here citing that file / comment.
</blockquote></details>

For `crate_universe`, it isn't that there *aren't* downloads, but that they're hung off of different names. It *looks* like that would be the case here also, but see my previous comment (re: CI job). So... yeah, *some* comment is probably warranted (and for `crate_universe` also), but I'm not sure the suggested content is correct.
___
*[`tools/workspace/new_release.py` line 98 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-Nq4KWyD1fY0a8q1IjR2:-Nq4QU3y8CTF32eBD6C4:b-50d8td) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83d02d4c9b0c247fb91865917edbe178d537309/tools/workspace/new_release.py#L98)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Do we want to keep the _COHORTS tuple alpha-sorted (with rules_rust inbetween between mypy and sdformat)?
</blockquote></details>

Yeah, probably. I wasn't sure what the rule was when I added clarabel/crate, and it just happened that the cohorts were *both* in order of dependent-to-requirement and lexicographical order. On further consideration, however, I believe the correct order is for each to start with the most-depending package, then ordered by decreasing dependency (using lexicographical to break ties), and for the list overall to be sorted lexicographically by first item. (Sort order for multi-dimensional things isn't always obvious!)

Anyway, done.

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/metadata.py` line 65 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-Nq4QxK-3Ob7TssSuFzY:-Nq4TFh09sXda_x3su1b:b-jqw0lp) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83d02d4c9b0c247fb91865917edbe178d537309/tools/workspace/metadata.py#L65)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

For `crate_universe`, it isn't that there *aren't* downloads, but that they're hung off of different names. It *looks* like that would be the case here also, but see my previous comment (re: CI job). So... yeah, *some* comment is probably warranted (and for `crate_universe` also), but I'm not sure the suggested content is correct.
</blockquote></details>

Okay, after some additional poking, I think I can verify that the downloads ought to be associated with e.g. `rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools` (i.e. not `rust_toolchain`). And in fact:
```js
{  
   "downloads": [  
       {  
           "sha256": "9684bc337f41110821fc94498e0596f76a061fae4667b195579b03fd141ad538",  
           "stripPrefix": "rustc-1.75.0-x86_64-unknown-linux-gnu/rustc",  
           "url": [  
               "https://static.rust-lang.org/dist/rustc-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "e02b66c86cc55ba4f9c1bcbd75c06dc4387445629d182b67bc5b54431bbd538d",  
           "stripPrefix": "clippy-1.75.0-x86_64-unknown-linux-gnu/clippy-preview",  
           "url": [  
               "https://static.rust-lang.org/dist/clippy-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "ccd5f13a3101efadf09b1bbbebe8f099d97e99e1d4f0a29a37814a0dae429ede",  
           "stripPrefix": "cargo-1.75.0-x86_64-unknown-linux-gnu/cargo",  
           "url": [  
               "https://static.rust-lang.org/dist/cargo-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "ee077bf5ead714e7cd2b94babc6673b7d91e485f7c1583441a8d8f701d4b5c6e",  
           "stripPrefix": "rustfmt-1.75.0-x86_64-unknown-linux-gnu/rustfmt-preview",  
           "url": [  
               "https://static.rust-lang.org/dist/rustfmt-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "3efa2c600c2b5a6493975c4bf6d8d52fb7ddba3c131dbf84363da4e049ce9ed7",  
           "stripPrefix": "llvm-tools-1.75.0-x86_64-unknown-linux-gnu/llvm-tools-preview",  
           "url": [  
               "https://static.rust-lang.org/dist/llvm-tools-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "b7a43ed4bc9a9205b3ee2ece2a38232c8da5f1f14e7ed84fbefd492f9d474579",  
           "stripPrefix": "rust-std-1.75.0-x86_64-unknown-linux-gnu/rust-std-x86_64-unknown-linux-gnu",  
           "url": [  
               "https://static.rust-lang.org/dist/rust-std-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       }  
   ],  
   "name": "rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools",  
   "repository_rule_type": "rust_toolchain_downloads"  
}
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20901)* status: 1 unresolved discussion

___
*[`tools/workspace/metadata.py` line 65 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-Nq4QxK-3Ob7TssSuFzY:-Nq4TYq0D9neT7Co3sjF:b-b0v2yh) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83d02d4c9b0c247fb91865917edbe178d537309/tools/workspace/metadata.py#L65)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Okay, after some additional poking, I think I can verify that the downloads ought to be associated with e.g. `rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools` (i.e. not `rust_toolchain`). And in fact:
```js
{  
   "downloads": [  
       {  
           "sha256": "9684bc337f41110821fc94498e0596f76a061fae4667b195579b03fd141ad538",  
           "stripPrefix": "rustc-1.75.0-x86_64-unknown-linux-gnu/rustc",  
           "url": [  
               "https://static.rust-lang.org/dist/rustc-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "e02b66c86cc55ba4f9c1bcbd75c06dc4387445629d182b67bc5b54431bbd538d",  
           "stripPrefix": "clippy-1.75.0-x86_64-unknown-linux-gnu/clippy-preview",  
           "url": [  
               "https://static.rust-lang.org/dist/clippy-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "ccd5f13a3101efadf09b1bbbebe8f099d97e99e1d4f0a29a37814a0dae429ede",  
           "stripPrefix": "cargo-1.75.0-x86_64-unknown-linux-gnu/cargo",  
           "url": [  
               "https://static.rust-lang.org/dist/cargo-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "ee077bf5ead714e7cd2b94babc6673b7d91e485f7c1583441a8d8f701d4b5c6e",  
           "stripPrefix": "rustfmt-1.75.0-x86_64-unknown-linux-gnu/rustfmt-preview",  
           "url": [  
               "https://static.rust-lang.org/dist/rustfmt-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "3efa2c600c2b5a6493975c4bf6d8d52fb7ddba3c131dbf84363da4e049ce9ed7",  
           "stripPrefix": "llvm-tools-1.75.0-x86_64-unknown-linux-gnu/llvm-tools-preview",  
           "url": [  
               "https://static.rust-lang.org/dist/llvm-tools-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       },  
       {  
           "sha256": "b7a43ed4bc9a9205b3ee2ece2a38232c8da5f1f14e7ed84fbefd492f9d474579",  
           "stripPrefix": "rust-std-1.75.0-x86_64-unknown-linux-gnu/rust-std-x86_64-unknown-linux-gnu",  
           "url": [  
               "https://static.rust-lang.org/dist/rust-std-1.75.0-x86_64-unknown-linux-gnu.tar.gz"  
           ]  
       }  
   ],  
   "name": "rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools",  
   "repository_rule_type": "rust_toolchain_downloads"  
}
```
</blockquote></details>

Right, so to be precise:

- Neither crate_universe nor rust_toolchain have any direct downloads.
- The effects of crate_universe on downloads show up in the individual repos like `@crate__amd-0.2.2`.  Since those are build-time dependencies, they already show in the metadata report and will be mirrored.
- The effects of rust_toolchain are at load-time only (not build-time), so the metadata sweep report does not find them, and therefore they are not being mirrored.  The json files you find on disk are the relevant ones, but they are not wired into `metadata`.  So the comment I'm thinking of would be make more sense around line 39, where we talk about bazel_skylib (another load-time-only dependency).  I think rules_python and such also fall into the same bucket.  So maybe no new comment is necessary?

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/metadata.py` line 65 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-Nq4QxK-3Ob7TssSuFzY:-Nq4VBls9ibXzovt95Qi:brh1v9q) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83d02d4c9b0c247fb91865917edbe178d537309/tools/workspace/metadata.py#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Right, so to be precise:

- Neither crate_universe nor rust_toolchain have any direct downloads.
- The effects of crate_universe on downloads show up in the individual repos like `@crate__amd-0.2.2`.  Since those are build-time dependencies, they already show in the metadata report and will be mirrored.
- The effects of rust_toolchain are at load-time only (not build-time), so the metadata sweep report does not find them, and therefore they are not being mirrored.  The json files you find on disk are the relevant ones, but they are not wired into `metadata`.  So the comment I'm thinking of would be make more sense around line 39, where we talk about bazel_skylib (another load-time-only dependency).  I think rules_python and such also fall into the same bucket.  So maybe no new comment is necessary?
</blockquote></details>

I'm sort of leaning toward a note "there are no downloads here because ...", but I'm okay skipping it for this PR (since `crate_universe` ought to have such and already doesn't).

I don't think line 39 is relevant to the note *I* have in mind, as L39 is about supplementing `bazel query deps(//...) --output package`. But that's only relevant if metadata for that name is generated in the usual way. Both `crate_universe` and `rust_toolchain` have metadata, but for multiple names each that are not the workspace name(s).

IIUC, *you* are thinking of a note explaining why e.g. `rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools` doesn't show up in `read_repository_metadata()`? I'd have no objection to that, though that even more so I'd probably do in a separate PR.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20901)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

___
*[`tools/workspace/metadata.py` line 65 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20901#-Nq4QxK-3Ob7TssSuFzY:-Nq4evYT3-ksOUljxQ4R:b-xo4a95) ([raw file](https://github.com/RobotLocomotion/drake/blob/d83d02d4c9b0c247fb91865917edbe178d537309/tools/workspace/metadata.py#L65)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I'm sort of leaning toward a note "there are no downloads here because ...", but I'm okay skipping it for this PR (since `crate_universe` ought to have such and already doesn't).

I don't think line 39 is relevant to the note *I* have in mind, as L39 is about supplementing `bazel query deps(//...) --output package`. But that's only relevant if metadata for that name is generated in the usual way. Both `crate_universe` and `rust_toolchain` have metadata, but for multiple names each that are not the workspace name(s).

IIUC, *you* are thinking of a note explaining why e.g. `rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools` doesn't show up in `read_repository_metadata()`? I'd have no objection to that, though that even more so I'd probably do in a separate PR.
</blockquote></details>

The line 39 thought was along the lines of "The bazel query only finds build-time dependencies.  Drake also requires some load-time dependencies such as starlark libraries, compilers, etc. Here, we add a few of those by hand so that they get archived and upgraded. There are a bunch due to rust_toolchain and ... that we've chosen to skip for now".

But I am totally fine to not do any of that in this PR.

**Pull request merged**
