### PR TITLE
Addresses -Wundefined-var-template warnings.

### LINKED ISSUE #4169: Warning Related to default_model_instance_id
# The Warning

The following was observed on an Ubuntu 14.04 system using clang-3.9.

```
[170/210] Building CXX object examples/Valkyrie/test/CMakeFiles/valkyrie_ik_test.dir/valkyrie_ik_test.cc.o
In file included from /home/liang/dev/drake-distro-1/drake/examples/Valkyrie/test/valkyrie_ik_test.cc:11:
In file included from /home/liang/dev/drake-distro-1/drake/../drake/multibody/rigid_body_ik.h:9:
/home/liang/dev/drake-distro-1/drake/../drake/multibody/rigid_body_tree.h:289:11: warning: instantiation of variable 'RigidBodyTree<double>::default_model_instance_id_set' required here, but no definition is available [-Wundefined-var-template]
          default_model_instance_id_set) const;
          ^
/home/liang/dev/drake-distro-1/drake/../drake/multibody/rigid_body_tree.h:1164:30: note: forward declaration of template entity is here
  static const std::set<int> default_model_instance_id_set;
                             ^
/home/liang/dev/drake-distro-1/drake/../drake/multibody/rigid_body_tree.h:289:11: note: add an explicit instantiation declaration to suppress this warning if 'RigidBodyTree<double>::default_model_instance_id_set' is explicitly instantiated in another translation unit
          default_model_instance_id_set) const;
          ^
1 warning generated.
```

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4169. The numerous warnings were getting bothersome to me. So I resolved them in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4706)

### CODE REVIEW

**Comment by patmarion** [comment]
Is there a way to resolve the warning without breaking the API?

**Comment by liangfok** [comment]
Yes, I am updating this PR now to not change `RigidbodyTree`'s API per F2F meeting with @jwnimmer-tri.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4706#-:-Ka2zYY-CJB-vCPbBPoF:biethij)*

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@david-german-tri for platform review please.

Thanks!

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4706#-:-Ka6xMpewO_xv8gJdJYJ:b-uxw1p5)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 10 of 18 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_tree.h, line 38 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4706#-Ka7i024uqVU1DJYS3mb:-Ka7i024uqVU1DJYS3mc:b-qm77aq) ([raw file](https://github.com/robotlocomotion/drake/blob/c40be1dc5d2baf5cb29944f3b47e1c7724bd4003/drake/multibody/rigid_body_tree.h#L38)):*
> ```objc
> 
> /**
>  * Defines RigidBodyTree constants.
> ```

BTW, could you comment here a bit more why in a separate struct? like to avoid having these templated on `T`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4706#-:-Ka7kOZswZq6LujsqAyp:bnfp4nl)*

**Comment by liangfok** [comment]
@amcastro-tri I addressed your comment.

---

Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.h, line 38 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4706#-Ka7i024uqVU1DJYS3mb:-Ka7lMDiCTgF8paGye7O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c40be1dc5d2baf5cb29944f3b47e1c7724bd4003/drake/multibody/rigid_body_tree.h#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, could you comment here a bit more why in a separate struct? like to avoid having these templated on `T`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4706#-:-Ka7lNaPzzvDD15jxWFO:b-d0eiqv)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4706)*

**Comment by liangfok** [comment]
This PR is now waiting on @david-german-tri's platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 9 of 18 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4706#-:-Ka83IXnrC70f4YZ0bo5:bnfp4nl)*

**Pull request merged**
