### PR TITLE
Add python binding for MakeMatrixVariable and MakeVectorVariable.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14342)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!
+@soonho-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14342#-:-MMIkaSX06ql16SyTJmr:bjs1c8j)* status: LGTM missing from assignees RussTedrake(platform),soonho-tri(platform) (waiting on @RussTedrake and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14342#-:-MMIm84t7J5CSmEgHria:bnfp4nl)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14342)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai)

___
*[bindings/pydrake/symbolic_py.cc, line 154 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14342#-MMIw1NVCw_h-joAhcOE:-MMIw1NVCw_h-joAhcOF:b-6px91d) ([raw file](https://github.com/robotlocomotion/drake/blob/d2b57db10706b10aeb4193bfcdcb7c2db29d24f6/bindings/pydrake/symbolic_py.cc#L154)):*
> ```cpp
>   DefCopyAndDeepCopy(&var_cls);
> 
>   // Bind the free functions for MakeVectorXXXVariable
> ```

Should we bind the others while we're at it?
___
*[bindings/pydrake/symbolic_py.cc, line 162 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14342#-MMIw8F-6RwN1udcAXoU:-MMIw8F-6RwN1udcAXoV:b5mb3tz) ([raw file](https://github.com/robotlocomotion/drake/blob/d2b57db10706b10aeb4193bfcdcb7c2db29d24f6/bindings/pydrake/symbolic_py.cc#L162)):*
> ```cpp
>           },
>           py::arg("rows"), py::arg("cols"), py::arg("name"),
>           py::arg("type") = symbolic::Variable::Type::CONTINUOUS,
> ```

i definitely like this as sugar, but I think we should set that default argument for the c++ method, too?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14342)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake and @soonho-tri)

___
*[bindings/pydrake/symbolic_py.cc, line 154 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14342#-MMIw1NVCw_h-joAhcOE:-MMJU6OA96L3KOpHASCm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2b57db10706b10aeb4193bfcdcb7c2db29d24f6/bindings/pydrake/symbolic_py.cc#L154)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Should we bind the others while we're at it?
</blockquote></details>

Done.
___
*[bindings/pydrake/symbolic_py.cc, line 162 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14342#-MMIw8F-6RwN1udcAXoU:-MMJU6yY1b3pB-yjLkdQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2b57db10706b10aeb4193bfcdcb7c2db29d24f6/bindings/pydrake/symbolic_py.cc#L162)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i definitely like this as sugar, but I think we should set that default argument for the c++ method, too?
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14342)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: thank you for doing this!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14342#-:-MMLQ0_6DZGzmzmUi1q8:bw1z3jx)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),RussTedrake(platform)

**Pull request merged**
