### PR TITLE
Update the Gurobi install instructions.

### PR DESCRIPTION
**Pull request by david-german-tri**
Relocate discussion of specialized externals so that it doesn't interrupt the basic Drake install workflow.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4092)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 267 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4092#-KW8ySleFbKWnwAp0NNb:-KW8ySleFbKWnwAp0NNc:bx6eolt) ([raw file](https://github.com/robotlocomotion/drake/blob/fbe6b67ebe2e1f40c87ed7cca4cf5bb22992784b/drake/doc/from_source.rst#L267)):*
> ```reStructuredText
> 
> Drake includes support for some externals which we are not able to redistribute
> directly (SNOPT, SEDUMI, ...).  In order to have drake locally install these for
> ```

Remove SEDUMI, it open-source now. SNOPT is the only private external now. MOSEK needs a license installing, but otherwise it is public.

Drake, not drake

---

*[drake/doc/from_source.rst, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4092#-KW8yKyG_9fiGQkNjlWg:-KW8yKyG_9fiGQkNjlWh:bt023wp) ([raw file](https://github.com/robotlocomotion/drake/blob/fbe6b67ebe2e1f40c87ed7cca4cf5bb22992784b/drake/doc/from_source.rst#L282)):*
> ```reStructuredText
> Before building Drake with Gurobi, create an account and obtain a license on
> Gurobi's website, <http://www.gurobi.com/>. Download Gurobi 6.0.5, and set
> the ``GUROBI_DISTRO`` environment variable to the path to the downloaded file.
> ```

absolute path

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4092)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 267 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4092#-KW8ySleFbKWnwAp0NNb:-KW9-2ls858puzM3xHPW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbe6b67ebe2e1f40c87ed7cca4cf5bb22992784b/drake/doc/from_source.rst#L267)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Remove SEDUMI, it open-source now. SNOPT is the only private external now. MOSEK needs a license installing, but otherwise it is public.
> 
> Drake, not drake
</details>
Done.

---

*[drake/doc/from_source.rst, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4092#-KW8yKyG_9fiGQkNjlWg:-KW9-3BdG-hNOXNKewTz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbe6b67ebe2e1f40c87ed7cca4cf5bb22992784b/drake/doc/from_source.rst#L282)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> absolute path
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4092)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4092#-:-KW96zuc5-4JL8Urinai:bnfp4nl)*

**Comment by david-german-tri** [comment]
+@russtedrake for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4092#-:-KW9CVYqACCbP7DLlRQ3:b-ddhj1v)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 279 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4092#-KW9IjKWGkJR3Jp3WeCX:-KW9IjKWGkJR3Jp3WeCY:bydxg4i) ([raw file](https://github.com/robotlocomotion/drake/blob/5652a084cc3177a575c8c71e633aa24030421af5/drake/doc/from_source.rst#L279)):*
> ```reStructuredText
> 
> Before building Drake with Gurobi, create an account and obtain a license on
> `Gurobi's website <http://www.gurobi.com/>`_. Download Gurobi 6.0.5, and set
> ```

I think gurobi 6.5 also works. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4092)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 279 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4092#-KW9IjKWGkJR3Jp3WeCX:-KW9LMYoMnK5G1fuhJTa:b-c2ctmn) ([raw file](https://github.com/robotlocomotion/drake/blob/5652a084cc3177a575c8c71e633aa24030421af5/drake/doc/from_source.rst#L279)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> I think gurobi 6.5 also works. 
</details>
It would not work with the current build infrastructure, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4092)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4092#-:-KWAlZ0_SXMnkBRnb6Z2:bnfp4nl)*

**Pull request merged**
