### PR TITLE
Tweak wheel test image tag

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Use the unique identifier as part of the image tag name when building the wheel test container. This allows us to *not* use said identifier (without collisions) when asked to preserve the tagged images, which in turn allows for inspection and debugging of the test environment.

+@svenevs for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17248)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Review by svenevs — COMMENTED** [review]
:lgtm: +@jwnimmer-tri for platform review per schedule please.  I believe this one can have a +(release notes: none) 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17248#-:-N2mrf9OACedc9Gnl2R-:brzvlqx)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[`tools/wheel/wheel_builder/linux.py` line 263 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17248#-N2mqXYJ4nEdSbyp4m_f:-N2mqXYK-yiuU9fcqf29:b-6vugkz) ([raw file](https://github.com/robotlocomotion/drake/blob/0a6485fa26565a43f96f38a39faa603c2c337f9b/tools/wheel/wheel_builder/linux.py#L263)):*
> ```Python
>     # Generate a unique identifier for this build, if needed.
>     if options.tag_stages:
>         identifier = None
> ```

FYI above in the changeset for this PR when `container = _tagname(target, f'test-{identifier}')`, it's not ever going to be the case that `identifier=None`.

**Comment by mwoehlke-kitware** [comment]
>  I believe this one can have a (release notes: none)

Indeed; thanks.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17248)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),svenevs (waiting on @jwnimmer-tri and @svenevs)

___
*[`tools/wheel/wheel_builder/linux.py` line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17248#-N2qe7WN6TUxJtWsB4lc:-N2rCIVM4L9kiOYFRXRR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0a6485fa26565a43f96f38a39faa603c2c337f9b/tools/wheel/wheel_builder/linux.py#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit verb mood
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17248)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),svenevs (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-debug please

**Pull request merged**
