### PR TITLE
Add and use boost_repositories repository rule

### PR DESCRIPTION
**Pull request by jamiesnape**
Needed by RobotLocomotion/drake-shambhala#8.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6574)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0N49Yad1EB-nMoZ-t:-Kp0N49Yad1EB-nMoZ-u:bkd8745) (no related file):*
I'm not convinced that fine-grained `cc_library` is the right answer for boost.  It seems like a lot of work with low payoff.  Is this based on some other-party boost BUILD files that we are trying to remain consistent with?

My counter-proposal is `@boost//:boost_headers` as one cc_library that contains as many header-only boost library pieces as we need (a whitelist), or possibly even just the full glob (and so don't worry about fail-fast on linker errors if someone tried to use something that needs a shared library).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0N49Yad1EB-nMoZ-t:-Kp0Q3tnZgRGefvKTGqR:b7nn3ao) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not convinced that fine-grained `cc_library` is the right answer for boost.  It seems like a lot of work with low payoff.  Is this based on some other-party boost BUILD files that we are trying to remain consistent with?

My counter-proposal is `@boost//:boost_headers` as one cc_library that contains as many header-only boost library pieces as we need (a whitelist), or possibly even just the full glob (and so don't worry about fail-fast on linker errors if someone tried to use something that needs a shared library).
</blockquote></details>

We definitely cannot do a full glob given where boost is installed on Ubuntu. It is a variation on https://github.com/nelhage/rules_boost, but using system libraries. I am hoping Boost will be gone shortly and we need this in urgently, so using those a basis seemed reasonable for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0N49Yad1EB-nMoZ-t:-Kp0RHCLvTSC_TnZz2H5:b-9iv54q) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We definitely cannot do a full glob given where boost is installed on Ubuntu. It is a variation on https://github.com/nelhage/rules_boost, but using system libraries. I am hoping Boost will be gone shortly and we need this in urgently, so using those a basis seemed reasonable for now.
</blockquote></details>

Actually, I take that back, everything is in a `boost` subdir. Maybe, that would work, though it leaves open the possiblity of someone using a non-header-only part and finding it broken.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by soonho-tri** [comment]
:lgtm: 

Tested on a local mac to build `//drake/multibody/parsers/...` which uses `sdformat`.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-:-Kp0Mur9092wH-wWwU-Q:bg22fo3)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0N49Yad1EB-nMoZ-t:-Kp0UJZWnR_WrodMXEcJ:bl3vlzb) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Actually, I take that back, everything is in a `boost` subdir. Maybe, that would work, though it leaves open the possiblity of someone using a non-header-only part and finding it broken.
</blockquote></details>

Yes, Boost headers are always in a subfolder.  I'm not really worried about "using a non-header-only-part" accidentally.

In this thread, I'm looking for a decision about whether we have any need for fine-grained libraries.  If the answer is no, I suspect the couple minutes it takes to rewrite to use glob is less than the time it will take me to review the 200 lines of dependency declarations.   If the answer is yes, then I can start in on the `.bzl` file review.

---

*[tools/boost.bzl, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0WXKLIZTlzSpjcEZu:-Kp0WXKMIc0TVrAZLtfY:bl4vmq9) ([raw file](https://github.com/robotlocomotion/drake/blob/3209e07691c2d53f0da8f5f3e01b48d8aa5001d1/tools/boost.bzl#L84)):*
> ```Python
>              attr = repository_ctx.os.name)
> 
>     repository_ctx.symlink("{}/include".format(prefix), "include")
> ```

I suspect that we should symlink on the necessary folder (e.g., `/usr/include/boost`), not all of `/usr/include`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0N49Yad1EB-nMoZ-t:-Kp0amEP1S_HHtiUNziI:b-3v2sfj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, Boost headers are always in a subfolder.  I'm not really worried about "using a non-header-only-part" accidentally.

In this thread, I'm looking for a decision about whether we have any need for fine-grained libraries.  If the answer is no, I suspect the couple minutes it takes to rewrite to use glob is less than the time it will take me to review the 200 lines of dependency declarations.   If the answer is yes, then I can start in on the `.bzl` file review.
</blockquote></details>

The honest answer is that I don't know. If you want to contribute a glob version instead of reviewing this, feel free. I have a long list of Shambhala things that need doing by the end of day and since this is functional, it is lower priority that the parts that are not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by jamiesnape** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/boost.bzl, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0WXKLIZTlzSpjcEZu:-Kp0dO8I0HCTYazhl2r2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3209e07691c2d53f0da8f5f3e01b48d8aa5001d1/tools/boost.bzl#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I suspect that we should symlink on the necessary folder (e.g., `/usr/include/boost`), not all of `/usr/include`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by jwnimmer-tri** [comment]
:lgtm: pending discussions.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0N49Yad1EB-nMoZ-t:-Kp0djj8yqpXiVNs51K3:b2b7yxs) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

The honest answer is that I don't know. If you want to contribute a glob version instead of reviewing this, feel free. I have a long list of Shambhala things that need doing by the end of day and since this is functional, it is lower priority that the parts that are not.
</blockquote></details>

(Aside: I think putting a deadline on Shambhala is a poor decision, though of couse I'll take that up with @stonier and not here.)

@soonho-tri In your review, did you cross-check that the `deps` in `boost.bzl` are both comprehensive and precise?  If not, could you please do so and report back?  (Alternatively, you could file a PR into this branch that replaces them with a glob.)

---

*[tools/boost.bzl, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0epEALTqHBAZRkmAW:-Kp0epEALTqHBAZRkmAX:b-l1xflu) ([raw file](https://github.com/robotlocomotion/drake/blob/6dff526498d46b2fd954195ee389d4a23a7f31b6/tools/boost.bzl#L58)):*
> ```Python
>     name = "{}",
>     srcs = {},
>     hdrs = glob({}) + glob({}),
> ```

I'm unclear on why the first `glob()` is here; the value is directly `hdrs` from the caller, which seems like it should never contain intentionally-missing elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-:-Kp0fXdQnxC6IBv6ncoO:b67tr8b)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/boost.bzl, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0epEALTqHBAZRkmAW:-Kp0ftlickyDK6f9AtEG:bsfxeft) ([raw file](https://github.com/robotlocomotion/drake/blob/6dff526498d46b2fd954195ee389d4a23a7f31b6/tools/boost.bzl#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm unclear on why the first `glob()` is here; the value is directly `hdrs` from the caller, which seems like it should never contain intentionally-missing elements.
</blockquote></details>

Headers were added between the Boost shipped with Trusty and the Boost shipped with Xenial.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by jwnimmer-tri** [comment]
*[tools/boost.bzl, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0epEALTqHBAZRkmAW:-Kp0gWKE2WSgrzC069sx:bfvgvvo) ([raw file](https://github.com/robotlocomotion/drake/blob/6dff526498d46b2fd954195ee389d4a23a7f31b6/tools/boost.bzl#L58)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Headers were added between the Boost shipped with Trusty and the Boost shipped with Xenial.
</blockquote></details>

Sounds fine, but then that hint to the reader should be made clear in the code or comments here somehow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0N49Yad1EB-nMoZ-t:-Kp1D6IbmyEuPUeGLVPJ:b4adzh5) (no related file):*
> (Alternatively, you could file a PR into this branch that replaces them with a glob.)

I'll do this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/boost.bzl, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0epEALTqHBAZRkmAW:-KpFfxrGiVZEtr9qxZ0M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6dff526498d46b2fd954195ee389d4a23a7f31b6/tools/boost.bzl#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sounds fine, but then that hint to the reader should be made clear in the code or comments here somehow.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6574#-Kp0N49Yad1EB-nMoZ-t:-KpFsqYarGGeBkRya9v2:b-c5v923) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> (Alternatively, you could file a PR into this branch that replaces them with a glob.)

I'll do this.
</blockquote></details>

@jwnimmer-tri , done. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6574)*

**Pull request merged**
