### PR TITLE
doc: Add release notes v0.24.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14208)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14208)* status: 15 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[doc/release_notes/v0.24.0.rst, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmBW4W8vFvKF3tbRZI:-MJmBW4W8vFvKF3tbRZJ:bnfh4w0) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L67)):*
> ```reStructuredText
> New features
> 
> * [plant] Code and test for spatial momentum of a plant or subset of bodies (`#13916`_)
> ```

nit Users don't need to know "and test".  Saying "Code" isn't particularly helpful either.  What is the actual new feature?  It should be something like "Add new method to" or "Provide" or "Enhance" or etc.
___
*[doc/release_notes/v0.24.0.rst, line 69 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmBrLP1vAxKDTrwJBX:-MJmBrLP1vAxKDTrwJBY:b-rptydp) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L69)):*
> ```reStructuredText
> * [plant] Code and test for spatial momentum of a plant or subset of bodies (`#13916`_)
> * Rewrite GlobalInverseKinematics using MultibodyPlant public API. (`#13921`_)
> * [plant] Introduce ContactSolver and MultibodyPlant::set_contact_solver() (`#13958`_)
> ```

nit `set_contact_solver` is marked as experimental.  It is not a feature we should mention to users.  (Remove this line.)
___
*[doc/release_notes/v0.24.0.rst, line 70 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmC1AC38qnHHUVmHhQ:-MJmC1AC38qnHHUVmHhR:bb6of0w) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L70)):*
> ```reStructuredText
> * Rewrite GlobalInverseKinematics using MultibodyPlant public API. (`#13921`_)
> * [plant] Introduce ContactSolver and MultibodyPlant::set_contact_solver() (`#13958`_)
> * [plant] Refactor TamsiContactResults --> ContactSolverResults (`#14069`_)
> ```

nit This is an internal class.  It should not appear in the release notes.
___
*[doc/release_notes/v0.24.0.rst, line 73 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmACNBDotbqRtCL_D9:-MJmACNBDotbqRtCL_DA:b-iywt63) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L73)):*
> ```reStructuredText
> * [plant] Add parameters for FixedOffsetFrame (`#14137`_)
> 
> * [dev] Add quadrature class for FEM (`#14202`_)
> ```

nit `dev` code is not installed, so doesn't get release notes.
___
*[doc/release_notes/v0.24.0.rst, line 79 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmANRLDbTHMt_D3aiH:-MJmANRM8q5_bcq343mi:b-zgntb9) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L79)):*
> ```reStructuredText
> * [geometry] Make BoundingVolumeHierarchy uses Obb (Oriented Bounding Box) (`#13978`_)
> * [geometry] Remove the non-BoundingVolumeHierarchy interface for rigid-soft mesh intersection (`#14110`_)
> * [geometry] Add hydroelastic support for Convex shapes (`#14178`_)
> ```

nit Hydroelastic is experimental, so does not get itemized bullets -- it just all rolls up into a single bullet point.  See prior release for examples.
___
*[doc/release_notes/v0.24.0.rst, line 80 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAGtDD92Xcc6Occjr:-MJmAGtDD92Xcc6Occjs:b-2zpqft) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L80)):*
> ```reStructuredText
> * [geometry] Remove the non-BoundingVolumeHierarchy interface for rigid-soft mesh intersection (`#14110`_)
> * [geometry] Add hydroelastic support for Convex shapes (`#14178`_)
> * [geometry] Add volume mesh testing utilities to :proximity_utilities (`#14209`_)
> ```

nit Test utilities are not installed, so don't get release notes.
___
*[doc/release_notes/v0.24.0.rst, line 82 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAUXcE8h_QSOdWTlD:-MJmAUXcE8h_QSOdWTlE:blt8vno) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L82)):*
> ```reStructuredText
> * [geometry] Add volume mesh testing utilities to :proximity_utilities (`#14209`_)
> 
> * [pydrake] Add pydrake bindings for model directives (`#14144`_)
> ```

nit When a new feature and its bindings go into the same release, we don't note the bindings on their own.  Either kill this line, or at most append this PR number to the model directives bullet (so there are two PR numbers for one bullet).
___
*[doc/release_notes/v0.24.0.rst, line 83 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmCDcNBRh10bPkSrnn:-MJmCDcNBRh10bPkSrno:b-s0rtt7) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L83)):*
> ```reStructuredText
> 
> * [pydrake] Add pydrake bindings for model directives (`#14144`_)
> * [pydrake] Add python binding for static equlibrium problem (`#14140`_)
> ```

nit New bindings have their own section below "Newly bound".  Please move this lines down there, and add "TBD" to them it I know to revisit it later.  (We list out every new binding one by one using is module, class, and function name, not prose statements like these.)
___
*[doc/release_notes/v0.24.0.rst, line 86 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAem7-oRt9cMticLp:-MJmAem7-oRt9cMticLq:b-1pch85) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L86)):*
> ```reStructuredText
> 
> * [model directives] Move model directives mechanism out of dev (`#14038`_)
> * [model directives] This commit applies all of the post-dev changes to model directives: (`#14038`_)
> ```

nit Neither of the two above lines are useful to a reader.  From their point of view, the important thing is that there is a new feature called "model directives" that's available.  So the phrasing here should be something more like "Add", not "Move".
___
*[doc/release_notes/v0.24.0.rst, line 93 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAptvD7E5U7Pcsvkg:-MJmAptw5L1-ncWQ5pHl:bhw4fdg) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L93)):*
> ```reStructuredText
> * [plant] Improve inlining for RotationalInertia::ReExpress (`#14088`_)
> * [plant] Change UnitInertia::ReExpress to use frame A instead of frame F (`#14112`_)
> * [plant] Don't warn when re-discovering the same package.xml (`#14089`_)
> ```

nit Typo "warn warn"
___
*[doc/release_notes/v0.24.0.rst, line 95 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAu9p3F8BTSmuvCg5:-MJmAu9p3F8BTSmuvCg6:bkprdhe) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L95)):*
> ```reStructuredText
> * [plant] Don't warn when re-discovering the same package.xml (`#14089`_)
> * [plant] Merge all multibody/math targets into :spatial_algebra (`#14113`_)
> * [plant] Use spatial_algebra.h as the sole header for the  package (`#14117`_)
> ```

nit The prior two bullets are a single fix; combine them into one line.
___
*[doc/release_notes/v0.24.0.rst, line 97 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAy5p3Vqe4hsdQj8q:-MJmAy5p3Vqe4hsdQj8r:b-o7iwe2) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L97)):*
> ```reStructuredText
> * [plant] Use spatial_algebra.h as the sole header for the  package (`#14117`_)
> * [plant] Improve error message for LinearBushingRollPitchYaw gimbal-lock singularity (`#14126`_)
> * [plant] Fix unit_quaternion_constraint_test failure on CI (`#14182`_)
> ```

nit This is not a feature users care about.  Either remove it, or at most move the PR number to adjoin whatever original PR this hotfix was required for.
___
*[doc/release_notes/v0.24.0.rst, line 100 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmB3244TfMjtkJHbVq:-MJmB3244TfMjtkJHbVr:bpho6gv) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L100)):*
> ```reStructuredText
> 
> * [pydrake] Bind some missing MultibodyPlant-related items (`#14192`_)
> * [pydrake] Bind some missing MultibodyTree-related items (`#14195`_)
> ```

nit New bindings have their own section below "Newly bound".  Please move these lines down there, and add "TBD" to them so I know to revisit them later.  (We list out every new binding one by one, not broad statements like these.)
___
*[doc/release_notes/v0.24.0.rst, line 102 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmBDMA2JiLC-l_szXq:-MJmBDMA2JiLC-l_szXr:b9zbcwt) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L102)):*
> ```reStructuredText
> * [pydrake] Bind some missing MultibodyTree-related items (`#14195`_)
> 
> * [model directives] Cleanups of issues revealed in integrating model directives downstream (`#14145`_)
> ```

nit This is not a useful bullet for a user of Drake.  The model directives is a new feature in this release.  Merge this PR number into the "Add new model directives feature" bullet above.
___
*[doc/release_notes/v0.24.0.rst, line 106 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmBPNCBeOQnUz9k4zr:-MJmBPNCBeOQnUz9k4zs:b3u04nx) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L106)):*
> ```reStructuredText
> 
> REMOVE THE FOLLOWING:
> * TBD Add utility function that uses AutoDiff and vector differentiation in a non-world frame.  Resolves issue #13562 (`#13593`_)
> ```

nit Agreed.  Please nix.

**Comment by jwnimmer-tri** [comment]
___
*[doc/release_notes/v0.24.0.rst, line 93 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAptvD7E5U7Pcsvkg:-MJmCpLN4CStbLxEQ8tW:b-sritda) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L93)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Typo "warn warn"
</blockquote></details>

Oops, no.  I misread it.  Withdrawn.

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14208)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[doc/release_notes/v0.24.0.rst, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmBW4W8vFvKF3tbRZI:-MJz-FxKC7K0YBf3oJNk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Users don't need to know "and test".  Saying "Code" isn't particularly helpful either.  What is the actual new feature?  It should be something like "Add new method to" or "Provide" or "Enhance" or etc.
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 69 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmBrLP1vAxKDTrwJBX:-MJz-Ha9BRibgszKMqe-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L69)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `set_contact_solver` is marked as experimental.  It is not a feature we should mention to users.  (Remove this line.)
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 70 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmC1AC38qnHHUVmHhQ:-MJz-OmV3XWGd7c5tU4k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is an internal class.  It should not appear in the release notes.
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 73 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmACNBDotbqRtCL_D9:-MJz-RLj6cBYuwWgTj22:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `dev` code is not installed, so doesn't get release notes.
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 79 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmANRLDbTHMt_D3aiH:-MJz2jM-DC65Du3eNuJ6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Hydroelastic is experimental, so does not get itemized bullets -- it just all rolls up into a single bullet point.  See prior release for examples.
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 80 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAGtDD92Xcc6Occjr:-MJz-kRq98gTnrq6BrP6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L80)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Test utilities are not installed, so don't get release notes.
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 82 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAUXcE8h_QSOdWTlD:-MJz1DW1B_7Ugr-NrokR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit When a new feature and its bindings go into the same release, we don't note the bindings on their own.  Either kill this line, or at most append this PR number to the model directives bullet (so there are two PR numbers for one bullet).
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 83 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmCDcNBRh10bPkSrnn:-MJz0Aph6OgU85vSjTbH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L83)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit New bindings have their own section below "Newly bound".  Please move this lines down there, and add "TBD" to them it I know to revisit it later.  (We list out every new binding one by one using is module, class, and function name, not prose statements like these.)
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 86 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAem7-oRt9cMticLp:-MJz0I8pB-J4-TClHRki:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L86)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Neither of the two above lines are useful to a reader.  From their point of view, the important thing is that there is a new feature called "model directives" that's available.  So the phrasing here should be something more like "Add", not "Move".
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 95 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAu9p3F8BTSmuvCg5:-MJz0boqAM_j6eueDmrx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The prior two bullets are a single fix; combine them into one line.
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 97 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmAy5p3Vqe4hsdQj8q:-MJz0lfI51T8g7ZM7tKA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L97)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is not a feature users care about.  Either remove it, or at most move the PR number to adjoin whatever original PR this hotfix was required for.
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 100 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmB3244TfMjtkJHbVq:-MJz0qcj5yvHB_mj1aZW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L100)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit New bindings have their own section below "Newly bound".  Please move these lines down there, and add "TBD" to them so I know to revisit them later.  (We list out every new binding one by one, not broad statements like these.)
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 102 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmBDMA2JiLC-l_szXq:-MJz10i77BJjg5XYGtww:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is not a useful bullet for a user of Drake.  The model directives is a new feature in this release.  Merge this PR number into the "Add new model directives feature" bullet above.
</blockquote></details>

Done.
___
*[doc/release_notes/v0.24.0.rst, line 106 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MJmBPNCBeOQnUz9k4zr:-MJz16n4EIESLgPnKgOA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dda8398fc4ed8457408a5fb0d0462b13f60a6b45/doc/release_notes/v0.24.0.rst#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Agreed.  Please nix.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14208)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[doc/release_notes/v0.24.0.rst, line 71 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MK0IZPP-qWKlPI52ltb:-MK0IZPP-qWKlPI52ltc:b-5uvqna) ([raw file](https://github.com/robotlocomotion/drake/blob/d6ce9aaebb45cb53d0e7ae2f0de32baa61e0a174/doc/release_notes/v0.24.0.rst#L71)):*
> ```reStructuredText
> * [plant] Add parameters for FixedOffsetFrame (`#14137`_)
> 
> * [rendering] Add normal computation for parsed/generated meshes (`#14035`_)
> ```

nit @SeanCurtis-TRI to my eye, this might be an internal-only change not (yet) relevant to end users?  Is that correct?  If yes, we should nix this bullet point.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for review per schedule, please.

Still to come is an intro paragraph explaining the macOS situation, but I think the rest of the document is ready.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: on all information local to here.

I did not check the consistency of referenced PR's and actual titles (trusting that to automation)
Will try to replay instructions

> Reviewed 2 of 4 files at r1, 1 of 2 files at r5, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14208#-:-MKa-sBgBUbEC5WpTKBn:bpkspwx)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/release_playbook.rst, line 22 at r9](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MK_e2MT3GMr9hsaEIg7:-MK_e2MT3GMr9hsaEIg8:bb0j1n8) ([raw file](https://github.com/robotlocomotion/drake/blob/13a7d9fa69ef77ddfe03dea1c790f31aefacf07a/doc/release_playbook.rst#L22)):*
> ```reStructuredText
> 
> 1. Choose the next version number.
> 2. Create a local Drake branch named ``release_notes-v0.N.0`` (so that others
> ```

Working: Will try these locally.
___
*[doc/release_playbook.rst, line 40 at r9](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MK_dqb16h8YYN_T--GE:-MK_dqb16h8YYN_T--GF:brcczgm) ([raw file](https://github.com/robotlocomotion/drake/blob/13a7d9fa69ef77ddfe03dea1c790f31aefacf07a/doc/release_playbook.rst#L40)):*
> ```reStructuredText
> 5. For release notes, on an ongoing basis, add recent commit messages to the
>    release notes draft using the ``tools/dev/relnotes`` tooling.
>    run,
> ```

nit grammar This looks odd.

Should this "run" be connected to the above sentence? ("[...] tooling.")

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14208)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/release_playbook.rst, line 22 at r9](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MK_e2MT3GMr9hsaEIg7:-MKa30yE7TPJW_Vj5Tzr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13a7d9fa69ef77ddfe03dea1c790f31aefacf07a/doc/release_playbook.rst#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will try these locally.
</blockquote></details>

Done.
___
*[doc/release_playbook.rst, line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MKa36ew0tL4JQMAFpX6:-MKa36ew0tL4JQMAFpX7:b7n1xol) ([raw file](https://github.com/robotlocomotion/drake/blob/13a7d9fa69ef77ddfe03dea1c790f31aefacf07a/doc/release_playbook.rst#L25)):*
> ```reStructuredText
>    can easily find and push to it after the PR is opened).
> 3. As the first commit on the branch, mimic the commit
>    (`link <https://github.com/RobotLocomotion/drake/pull/12408/commits/674b84877bc08448b59a2243f3b910a7b6dbab43>`_)
> ```

This commit is not easily discoverable (from this link):


I'd suggest using this link:
https://github.com/RobotLocomotion/drake/commit/674b84877bc08448b59a2243f3b910a7b6dbab43
___
*[doc/release_playbook.rst, line 39 at r9](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MKa1NPB3xhUKlUypo4b:-MKa1NPB3xhUKlUypo4c:b-v5wrqz) ([raw file](https://github.com/robotlocomotion/drake/blob/13a7d9fa69ef77ddfe03dea1c790f31aefacf07a/doc/release_playbook.rst#L39)):*
> ```reStructuredText
>    enabled (the checkbox is checked).
> 5. For release notes, on an ongoing basis, add recent commit messages to the
>    release notes draft using the ``tools/dev/relnotes`` tooling.
> ```

BTW It was not immediately clear to me how to run `relnotes`.

These instructions could be clarified by stating "Please open `tools/dev/relnotes.py` and follow the instructions at the toplevel."
___
*[doc/release_playbook.rst, line 44 at r9](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MKa2WXY8SOqBZjpXk6P:-MKa2WXY8SOqBZjpXk6Q:b-6oltoi) ([raw file](https://github.com/robotlocomotion/drake/blob/13a7d9fa69ef77ddfe03dea1c790f31aefacf07a/doc/release_playbook.rst#L44)):*
> ```reStructuredText
>    a. On the first run, use ``--action=create`` to bootstrap the file.
>       Be sure to cite the new file from the list in ``doc/release_notes.rst``.
>    b. On the subsequent runs, use ``--action=update`` to refresh the file.
> ```

BTW This command froze (did not complete within 60s) for me.

Commands run:
```
$ git log -n 1 --oneline --no-decorate
13a7d9fa69 20201026
$ bazel build //tools/dev:relnotes
$ rm ./doc/release_notes/v0.24.0.rst
$ bazel build //tools/dev:relnotes
$ bazel-bin/tools/dev/relnotes --action=create --prior_version=v0.23.0 --version=v0.24.0
# <good>
$ bazel-bin/tools/dev/relnotes --action=update --prior_version=v0.23.0 --version=v0.24.0
# <froze>
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14208)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[doc/release_playbook.rst, line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MKa36ew0tL4JQMAFpX6:-MKaJnVk7zayavlcz19z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13a7d9fa69ef77ddfe03dea1c790f31aefacf07a/doc/release_playbook.rst#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This commit is not easily discoverable (from this link):


I'd suggest using this link:
https://github.com/RobotLocomotion/drake/commit/674b84877bc08448b59a2243f3b910a7b6dbab43
</blockquote></details>

Done.
___
*[doc/release_playbook.rst, line 39 at r9](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MKa1NPB3xhUKlUypo4b:-MKaJ-_nCHY6xdNchw--:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13a7d9fa69ef77ddfe03dea1c790f31aefacf07a/doc/release_playbook.rst#L39)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW It was not immediately clear to me how to run `relnotes`.

These instructions could be clarified by stating "Please open `tools/dev/relnotes.py` and follow the instructions at the toplevel."
</blockquote></details>

Done.
___
*[doc/release_playbook.rst, line 40 at r9](https://reviewable.io/reviews/robotlocomotion/drake/14208#-MK_dqb16h8YYN_T--GE:-MKaJ9Zx0-6rQvUTTPv_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13a7d9fa69ef77ddfe03dea1c790f31aefacf07a/doc/release_playbook.rst#L40)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit grammar This looks odd.

Should this "run" be connected to the above sentence? ("[...] tooling.")
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @EricCousineau-TRI from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14208)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Pull request merged**
