### PR TITLE
Add ccache-bazel-wrapper to ubuntu 16.04 setup

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This builds on prior fixes to #4464, now hopefully without even involving the developer.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5369)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-:-KeEFsx9ED8SKssbmxbT:bbpa3zd)*

**Comment by jwnimmer-tri** [comment]
git failures
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Comment by rpoyner-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEO9v3OAvc54Koxfyj:-KeEO9v3OAvc54Koxfyk:b7bpobx) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh#L29)):*
> ```Shell
> rm -rf draketmp
> fakeroot alien \
>   --description="Compatability shim to turn of ccache when invoking bazel" \
> ```

typo: s/of/off/

---

*[setup/ubuntu/16.04/ccache-bazel-wrapper.sh, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEMDYcEF-GDVu6uJWu:-KeEMDYdXHZH8jaa_GdM:bskh653) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/ccache-bazel-wrapper.sh#L19)):*
> ```Shell
> 
> # Remove the magic ccache directory from the $PATH.
> export PATH=$(
> ```

bash can do a good-enough job on its own: `export PATH=${PATH/\/usr\/lib\/ccache/}`. I don't think the extra ':' characters actually matter.

---

*[setup/ubuntu/16.04/ccache-bazel-wrapper.sh, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEGmkpXmr5MOxDo5Et:-KeEGmkqnU0kSOf39o6r:b-j73q4o) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/ccache-bazel-wrapper.sh#L21)):*
> ```Shell
> export PATH=$(
>     echo -n "$PATH:" |
>         awk -v RS=: -v ORS=: '$0 != "/usr/lib/ccache"' |
> ```

btw, not sure about how I feel being made to read AWK documentation for the first time in 20+ years =P

---

*[setup/ubuntu/16.04/ccache-bazel-wrapper.sh, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEMzaWLjc86KhRyVxy:-KeEMzaX7iFwCJfwfnTk:b-hjwfxs) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/ccache-bazel-wrapper.sh#L25)):*
> ```Shell
> 
> # Run the real Bazel tool.
> exec bazel "$@"
> ```

btw, the whole thing might work on one line: `PATH=${PATH/\/usr\/lib\/ccache/} exec bazel "$@"`

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEOMoGfiy4-4bQeoS6:-KeEOMoGfiy4-4bQeoS7:b-ty3w2k) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/install_prereqs.sh#L128)):*
> ```Shell
> 
> # Repair a bad Bazel/ccache interaction.
> # See https://github.com/RobotLocomotion/drake/issues/4464.
> ```

Either issue 4464 or some text in these files should maybe refer to whatever the bazel team has written about the ccache problem. It would be good to have a prompt somewhere to remove this festa if/when bazel itself gets fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5369)*

**Comment by jwnimmer-tri** [comment]
*[setup/ubuntu/16.04/ccache-bazel-wrapper.sh, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEMDYcEF-GDVu6uJWu:-KeEP9rn2AJVQQwizqbl:bfxnalx) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/ccache-bazel-wrapper.sh#L19)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

bash can do a good-enough job on its own: `export PATH=${PATH/\/usr\/lib\/ccache/}`. I don't think the extra ':' characters actually matter.
</blockquote></details>

Does that leave intact paths like `/usr/lib/ccache/workaround`?  (In other words, is the removal anchored to colons?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5369)*

**Comment by rpoyner-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/ccache-bazel-wrapper.sh, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEMDYcEF-GDVu6uJWu:-KeES_wiz60gGwReY4Wh:bho4e29) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/ccache-bazel-wrapper.sh#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Does that leave intact paths like `/usr/lib/ccache/workaround`?  (In other words, is the removal anchored to colons?)
</blockquote></details>

It is not anchored, as shown, no. That doesn't mean it couldn't be...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5369)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEO9v3OAvc54Koxfyj:-KeEP3t6m_3IGAXeNba0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh#L29)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo: s/of/off/
</blockquote></details>

Done.

---

*[setup/ubuntu/16.04/ccache-bazel-wrapper.sh, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEMDYcEF-GDVu6uJWu:-KeESsfGpwPpmv6c1Hh5:b735iqo) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/ccache-bazel-wrapper.sh#L19)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

It is not anchored, as shown, no. That doesn't mean it couldn't be...
</blockquote></details>

I worked for a while on a sed rexexp that would anchor on either colon, start-of-line, or end-of-line.  It got a bit complicated.  The direct phrasing of "split on colon, filter out some literal values, then reassemble" seemed more straightforward.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEOMoGfiy4-4bQeoS6:-KeESivQKTyYrHNFZz7Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/install_prereqs.sh#L128)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Either issue 4464 or some text in these files should maybe refer to whatever the bazel team has written about the ccache problem. It would be good to have a prompt somewhere to remove this festa if/when bazel itself gets fixed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5369)*

**Comment by rpoyner-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/ccache-bazel-wrapper.sh, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-KeEMDYcEF-GDVu6uJWu:-KeETEVHePOndd8VghZq:b-jnts55) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2a66efdde393137b0cf3181bf3041cc16ef92a/setup/ubuntu/16.04/ccache-bazel-wrapper.sh#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I worked for a while on a sed rexexp that would anchor on either colon, start-of-line, or end-of-line.  It got a bit complicated.  The direct phrasing of "split on colon, filter out some literal values, then reassemble" seemed more straightforward.
</blockquote></details>

fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5369)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri Do you want to platform review to see if this solves your ccache problems?

You can test it without re-running all of `install_prereqs.sh` via:
```
drake-distro$ ./setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh --install
```

Then make sure ccache _is_ on your $PATH, and try to run `bazel build //drake/common/...` or something similar.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-:-KeEUezG7s3ZZ4VtdZB0:b-31aubl)*

**Comment by sammy-tri** [comment]
:lgtm: Tested locally, and it does seem to work.

I'm, uhm....    impressed by this solution.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-:-KeFO16ztVTN0470W3b4:b-r6rnxw)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5369#-:-KeFOCfCCeNX4oKrfoO7:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
For the record, this fix gets overwritten when you install a new compiler; `/usr/sbin/update-ccache-symlinks` removes the symlink installed by this fix.  Running the setup script again (or just the `./setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh --install` part) will fix it.

**Pull request merged**
