### PR TITLE
ScsSolver adds quadratic cost directly.

### LINKED ISSUE #18365: ScsSolver adds quadratic cost directly instead of converting it to rotated Lorentz cone constraints
The current version of SCS supports quadratic cost now

### PR DESCRIPTION
**Pull request by hongkai-dai**
Instead of converting it to rotated Lorentz cone constraints with linear costs.

resolves #18365

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18605)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-:-NM0qiusEP_yN2k28s-Q:b-w629gj)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
Just pointed out some typos, otherwise :lgtm:

+@sammy-tri for platform review, please.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-:-NM6IGV9B8ivlpMMEPkf:b-gxj9m9)* status: 4 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai and @sammy-tri)

___
*[`solvers/scs_solver.cc` line 627 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-NM5eccXEVaXk-SN1WHG:-NM5eccXEVaXk-SN1WHH:b-71jro8) ([raw file](https://github.com/RobotLocomotion/drake/blob/18f8f3c37da0ee931c9506412d20eab424205f42/solvers/scs_solver.cc#L627)):*
> ```cpp
>     scs_problem_data->P = static_cast<ScsMatrix*>(malloc(sizeof(ScsMatrix)));
>     // This scs_calloc doesn't need to accompany a ScopeExit since
>     // //scs_problem_data->P->x will be cleaned up recursively by freeing up
> ```

typo: there are two `//`s here



_Code quote:_
```cpp
// //scs_problem_data
```
___
*[`solvers/scs_solver.cc` line 633 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-NM5enlJ2CdPYpU8fPY1:-NM5enlJ2CdPYpU8fPY2:b-cc6zg3) ([raw file](https://github.com/RobotLocomotion/drake/blob/18f8f3c37da0ee931c9506412d20eab424205f42/solvers/scs_solver.cc#L633)):*
> ```cpp
> 
>     // This scs_calloc doesn't need to accompany a ScopeExit since
>     // //scs_problem_data->P->i will be cleaned up recursively by freeing up
> ```

typo, same here



_Code quote:_
```cpp
// //scs_problem_data
```
___
*[`solvers/scs_solver.cc` line 937 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-NM5dH7wAisCiJonoWg6:-NM5dH7xEsGz3hXblKqs:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/18f8f3c37da0ee931c9506412d20eab424205f42/solvers/scs_solver.cc#L937)):*
> ```cpp
>   std::vector<Eigen::Triplet<double>> A_triplets;
> 
>   // We need to construct a sparse matrix in Column Compressed Stoarge (CCS)
> ```

typo



_Code quote:_
```cpp
Stoarge
```
___
*[`solvers/scs_solver.cc` line 1032 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-NM6HIDQDhFmaZ4dBkEN:-NM6HIDQDhFmaZ4dBkEO:byvfshy) ([raw file](https://github.com/RobotLocomotion/drake/blob/18f8f3c37da0ee931c9506412d20eab424205f42/solvers/scs_solver.cc#L1032)):*
> ```cpp
>       prog.linear_matrix_inequality_constraints().empty() &&
>       prog.exponential_cone_constraints().empty()) {
>     // A_triplets.empty() = true means up to now (after loop through box, linear
> ```

I guess this should be "looping"?



_Code quote:_
```cpp
loop
```
___
*[`solvers/scs_solver.cc` line 1033 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-NM6HYkb4Sy-LMamVthx:-NM6HYkb4Sy-LMamVthy:b-nfs7lt) ([raw file](https://github.com/RobotLocomotion/drake/blob/18f8f3c37da0ee931c9506412d20eab424205f42/solvers/scs_solver.cc#L1033)):*
> ```cpp
>       prog.exponential_cone_constraints().empty()) {
>     // A_triplets.empty() = true means up to now (after loop through box, linear
>     // and second-order cone constraints) no constrains have been added to SCS.
> ```

typo: "constraints"



_Code quote:_
```cpp
constrains
```
___
*[`solvers/scs_solver.cc` line 1034 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-NM6G8J8AzTYXna6-Ms4:-NM6G8J8AzTYXna6-Ms5:b-k1pi53) ([raw file](https://github.com/RobotLocomotion/drake/blob/18f8f3c37da0ee931c9506412d20eab424205f42/solvers/scs_solver.cc#L1034)):*
> ```cpp
>     // A_triplets.empty() = true means up to now (after loop through box, linear
>     // and second-order cone constraints) no constrains have been added to SCS.
>     // Combining this with the fact that the positive_semidefinite, the linear
> ```

FWIW, two minor suggestions to consider:
1. change "positive_semidefinite" to "positive semidefinite" for consistency
2. remove the second "the", i.e., "the positive-semidefinite, the linear matrix inequality and exponential cone constraints" to the positive semidefinite, linear matrix inequality and exponential cone constraints"

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (with some typo nits)

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-:-NMAEahjA7uLYF3fMhwd:b-st2yyq)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`solvers/scs_solver.cc` line 628 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18605#-NMAD0vfBLLPoQeu1hXf:-NMAD0vg-nJpINktEs-b:b-u2v6z6) ([raw file](https://github.com/RobotLocomotion/drake/blob/a42ae8180bc0c04a8ff94a21b4cd80939aea0a4f/solvers/scs_solver.cc#L628)):*
> ```cpp
>     // This scs_calloc doesn't need to accompany a ScopeExit since
>     // scs_problem_data->P->x will be cleaned up recursively by freeing up
>     // scs_problem-data in scs_free_data()
> ```

nit: typo (also below) `scs_problem-data` has a hyphen in place of an underscore

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18605)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,sammy-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
