### PR TITLE
adds simplest case of integration for symbolic polynomial

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please
+@soonho-tri for platform review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807#-:-MWHfH6p3rsHHTK8XXRH:bkz28bw)* status: LGTM missing from assignees hongkai-dai,soonho-tri(platform) (waiting on @hongkai-dai and @soonho-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

BTW, in our MonomialBasisElement class, it supports `Integrate` function https://github.com/RobotLocomotion/drake/blob/dd18fde30250c0a7e89a436cd3f73e4c6ce948d5/common/symbolic_monomial_basis_element.h#L114-L123. I haven't rewritten Polynomial class with `MonomialBasisElement` yet, but will do that in the future. (The goal is to support different type of basis, including monomial and ChebyshevPolynomial).

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807#-:-MWHyX9ADWbAJJ5XC5hr:bslbtsq)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform) (waiting on @RussTedrake and @soonho-tri)

___
*[common/symbolic_polynomial.cc, line 514 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWHzsM69F927MVJIzai:-MWHzsM69F927MVJIzaj:b-mmncpw) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/symbolic_polynomial.cc#L514)):*
> ```cpp
>     const Monomial& m{term.first};
>     const Expression& coeff{term.second};
>     int n = 0;
> ```

I think to construct the new Monomial m * x, it would be faster to construct the new `powers` map directly, something like
```cc
auto new_powers = m.get_powers();
auto it = new_powers.find(x);
if (it != new_powers.end()) {
  it->second++;
} else {
  new_powers.emplace_hint(it, x, 1);
}
DoAddProduct((coeff / (n+1)).Expand(), Monomial(new_powers), &map);
```

The reason is that when we do `m * Monomial{x}`, it will need to find the variable `x` in `m` again, which is redundant.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807)* status: 4 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @RussTedrake)

___
*[common/symbolic_polynomial.h, line 173 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWKAEoT7TGafNAtvN-x:-MWKAEoT7TGafNAtvN-y:b-g0t2i3) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/symbolic_polynomial.h#L173)):*
> When documenting exceptions in an API, only state that the function will throw std::exception; never promise a more specific subclass:

From https://drake.mit.edu/styleguide/cppguide.html#Exceptions
___
*[common/symbolic_polynomial.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWJscfNEr0Pr_-WBcWI:-MWJscfO5ZK3uEjMYQ6-:b-3oceu9) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/symbolic_polynomial.h#L180)):*
> ```objc
>    * indeterminate @p x over the domain [a, b].  Integration with respect to
>    * decision variables is not supported yet.
>    * @throws std::runtime_error if @p x is a decision variable.
> ```

`std::runtime_error` => `std::exception`

Also, do we want to handle the case `a > b` (where `[a, b]` does not form a proper interval)?
___
*[common/test/symbolic_polynomial_test.cc, line 663 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWKBfnt-jWDx4uFuFR0:-MWKBfnt-jWDx4uFuFR1:br1vt7p) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/test/symbolic_polynomial_test.cc#L663)):*
> ```cpp
>   EXPECT_PRED2(PolyEqual, p.Integrate(var_z_, -1, 1), def_int_p_dz);
> 
>   EXPECT_THROW(p.Integrate(var_a_), std::runtime_error);
> ```

1) `std::runtime_error` => `std::exception` after following the C++ guideline.
2) Let's add another line:

```c++
EXPECT_THROW(p.Integrate(var_a_, -1, 1), std::exception);
```

**Review by RussTedrake — COMMENTED** [review]
i saw the `GenericPolynomial` in progress, and figure we might have to copy this over there at some point.  But this is the first one I needed.  ;-)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807#-:-MWKbxML46T3GIyX1r5-:b2jitxn)* status: 4 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @hongkai-dai and @soonho-tri)

___
*[common/symbolic_polynomial.h, line 173 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWKAEoT7TGafNAtvN-x:-MWKYDaeCAUnCDuQqT6x:b7a540m) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/symbolic_polynomial.h#L173)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> When documenting exceptions in an API, only state that the function will throw std::exception; never promise a more specific subclass:

From https://drake.mit.edu/styleguide/cppguide.html#Exceptions

</blockquote></details>

Done.  (fwiw, there are many instances of documenting with runtime_error elsewhere in this file)
___
*[common/symbolic_polynomial.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWJscfNEr0Pr_-WBcWI:-MWKYLM_7DsHX5B8rD2K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/symbolic_polynomial.h#L180)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`std::runtime_error` => `std::exception`

Also, do we want to handle the case `a > b` (where `[a, b]` does not form a proper interval)?
</blockquote></details>

Done.
___
*[common/symbolic_polynomial.cc, line 514 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWHzsM69F927MVJIzai:-MWKbWly4e423QkhRt0K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/symbolic_polynomial.cc#L514)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think to construct the new Monomial m * x, it would be faster to construct the new `powers` map directly, something like
```cc
auto new_powers = m.get_powers();
auto it = new_powers.find(x);
if (it != new_powers.end()) {
  it->second++;
} else {
  new_powers.emplace_hint(it, x, 1);
}
DoAddProduct((coeff / (n+1)).Expand(), Monomial(new_powers), &map);
```

The reason is that when we do `m * Monomial{x}`, it will need to find the variable `x` in `m` again, which is redundant.

</blockquote></details>

Done.
___
*[common/test/symbolic_polynomial_test.cc, line 663 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWKBfnt-jWDx4uFuFR0:-MWKbfHr2lHDOOChHzvQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/test/symbolic_polynomial_test.cc#L663)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

1) `std::runtime_error` => `std::exception` after following the C++ guideline.
2) Let's add another line:

```c++
EXPECT_THROW(p.Integrate(var_a_, -1, 1), std::exception);
```
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807#-:-MWKpoqM92NpYnMXEA4Y:bnfp4nl)* status: 1 unresolved discussion (waiting on @hongkai-dai and @soonho-tri)

___
*[common/symbolic_polynomial.h, line 173 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWKAEoT7TGafNAtvN-x:-MWKpsHo15CTqipnEoW9:bwtc1bt) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/symbolic_polynomial.h#L173)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  (fwiw, there are many instances of documenting with runtime_error elsewhere in this file)
</blockquote></details>

I understand. FYI, we introduced the rule a month ago and didn't update the existing code.

https://github.com/RobotLocomotion/styleguide/commit/3422cc1d75e9989aba5bbd7675b8e9343f01c5f3

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807)* status: 1 unresolved discussion (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),hongkai-dai (waiting on @RussTedrake)

___
*[common/symbolic_polynomial.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWJscfNEr0Pr_-WBcWI:-MWKqjnB-zh0o3McJYxG:b-26uzsn) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/symbolic_polynomial.h#L180)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit. I thought that when a > b, the integral is still well defined? It is just the negation of the integral from b to a?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),hongkai-dai (waiting on @soonho-tri)

___
*[common/symbolic_polynomial.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14807#-MWJscfNEr0Pr_-WBcWI:-MWMF0Vg738AHJWF1tXl:b-wv0ss9) ([raw file](https://github.com/robotlocomotion/drake/blob/c8dcff36e62142c460c9868e3c2175795bbff08d/common/symbolic_polynomial.h#L180)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit. I thought that when a > b, the integral is still well defined? It is just the negation of the integral from b to a?
</blockquote></details>

gosh.  of course you are right (and my original code was correct).  I was too quick to change it.  ;-)
https://www.shmoop.com/fundamental-theorem-calculus/order-limits-integration.html

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14807)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),hongkai-dai (waiting on @soonho-tri)

**Pull request merged**
