### PR TITLE
[geometry] ReadVtkToVolumeMesh

### LINKED ISSUE #17767: [external] Access vtkDataReader in Drake
Please change drake/tools/workspace/vtk/repository.bzl so that we can use vtkDataReader and vtkUnstructuredGridReader from code inside drake.

CC: @jwnimmer-tri @mwoehlke-kitware @svenevs

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Read VTK files of tetrahedral meshes using VTK library.

Also fixes #17767.

CC: @xuchenhan-tri

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 

+@xuchenhan-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-N9iRFyP9yE3pJJ3P1pD:bcl0imp)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Since I coauthored some of these code, would it be better if we find a fresh set of eyes for review?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-N9nQbO90T5sI_xiJSZe:bpkqtfy)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by DamrongGuoy — COMMENTED** [review]
-@xuchenhan-tri 

+@vincekurtz for feature review, please.

https://docs.reviewable.io/reviews.html is a long read but should help you understand how to use Reviewable.

@vincekurtz, If it's too much, please feel free to decline to review for now.  I'm not sure how busy you are at the moment.

This is the PR in Reviewable https://reviewable.io/reviews/RobotLocomotion/drake/17725#-

CC: @amcastro-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NA6DL1GA4G_OugboPpJ:bys3vqn)* status: LGTM missing from assignee vincekurtz, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @vincekurtz)

**Review by vincekurtz — COMMENTED** [review]
:lgtm: with the caveat that I was not previously familiar with the VTK file type.

> Reviewed 1 of 6 files at r1, 2 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NA6temGBANLRI3diWW7:bh5cqov)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[`geometry/proximity/vtk_to_volume_mesh.h` line 52 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NA6qa2dDPIMhs_LCPEO:-NA6qa2dDPIMhs_LCPEP:b-g1ll8x) ([raw file](https://github.com/robotlocomotion/drake/blob/6f559e6a5dd5da6ff60790a6228768ac7124a2ce/geometry/proximity/vtk_to_volume_mesh.h#L52)):*
> ```objc
>  @return tetrahedral volume mesh
> 
>  @warn It has limited error checking and support only a subset of VTK files.
> ```

nit, "supports only a subset"
___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 30 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NA6raxmA0I1_wE4k_Ph:-NA6raxn2FBAJ-Qlhbe7:b-1md259) ([raw file](https://github.com/robotlocomotion/drake/blob/6f559e6a5dd5da6ff60790a6228768ac7124a2ce/geometry/proximity/vtk_to_volume_mesh.cc#L30)):*
> ```cpp
>   std::vector<VolumeElement> elements;
>   std::vector<Vector3<double>> vertices;
>   while (std::getline(*input_stream, line)) {
> ```

minor, the VTK file format indicates that the single line `# vtk DataFile Version x.x` will be at the top of each file. Do you want to check for this header, or is it more-or-less assumed that the file that's being passed in is a proper VTK file?

Similarly, do you need to check the file format (`ASCII` or `BINARY`)?

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @vincekurtz)

___
*[`geometry/proximity/vtk_to_volume_mesh.h` line 52 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NA6qa2dDPIMhs_LCPEO:-NAAM_oA0uMvaen76g40:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/dba7461f10d1b9f612f57946f36c50b304b0ee22/geometry/proximity/vtk_to_volume_mesh.h#L52)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, "supports only a subset"
</blockquote></details>

Done. Thanks.
___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 30 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NA6raxmA0I1_wE4k_Ph:-NAAaUbb5VGMM_h823X0:b-qb8ode) ([raw file](https://github.com/robotlocomotion/drake/blob/dba7461f10d1b9f612f57946f36c50b304b0ee22/geometry/proximity/vtk_to_volume_mesh.cc#L30)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

minor, the VTK file format indicates that the single line `# vtk DataFile Version x.x` will be at the top of each file. Do you want to check for this header, or is it more-or-less assumed that the file that's being passed in is a proper VTK file?

Similarly, do you need to check the file format (`ASCII` or `BINARY`)?
</blockquote></details>

Done.  I added a simple check with a TODO for more checking later.

**Comment by jwnimmer-tri** [comment]
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 32 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NAAbDNx-QkWMSp-zX0S:-NAAbDNy3CsgI8z8J2pE:b-t3bqy4) ([raw file](https://github.com/robotlocomotion/drake/blob/528694b27093555eee0ce5dccf50dc0aa22397b0/geometry/proximity/vtk_to_volume_mesh.cc#L32)):*
> ```cpp
>   }
>   // TODO(DamrongGuoy): More error checking or use the VTK library to read
>   //  the file instead of this code.
> ```

Why is it _ever_ appropriate to write a VTK file parser by instead instead of calling VTK to do it for us?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @vincekurtz)

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 32 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NAAbDNx-QkWMSp-zX0S:-NAAbr2w-vkCEYY77yPt:b-illz2v) ([raw file](https://github.com/robotlocomotion/drake/blob/528694b27093555eee0ce5dccf50dc0aa22397b0/geometry/proximity/vtk_to_volume_mesh.cc#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why is it _ever_ appropriate to write a VTK file parser by instead instead of calling VTK to do it for us?
</blockquote></details>

(*... parser by _hand_ ...)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs, @vincekurtz, and @zachfang)

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 32 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NAAbDNx-QkWMSp-zX0S:-NABaWl1836d8l4to5mZ:bwn6f6k) ([raw file](https://github.com/robotlocomotion/drake/blob/528694b27093555eee0ce5dccf50dc0aa22397b0/geometry/proximity/vtk_to_volume_mesh.cc#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(*... parser by _hand_ ...)
</blockquote></details>

I'll need [vtkDataReader](https://vtk.org/doc/nightly/html/classvtkDataReader.html) (or specifically its subclass [vtkUnstructuredGridReader](https://vtk.org/doc/nightly/html/classvtkUnstructuredGridReader.html)), but I don't think Drake has it yet.

I don't see it in this [list in find_vtk_headers.py](https://github.com/RobotLocomotion/drake/blob/857441b5f169814e3164e3ad22d8470e8d937a31/tools/workspace/vtk/find_vtk_headers.py#L35-L69) in this [directory.](https://github.com/RobotLocomotion/drake/tree/master/tools/workspace/vtk)

Please let me know if I misunderstood. CC: @svenevs @zachfang

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware, @svenevs, @vincekurtz, and @zachfang)

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 32 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NAAbDNx-QkWMSp-zX0S:-NABfPvq5zkvQMThnxxa:b-7gjluc) ([raw file](https://github.com/robotlocomotion/drake/blob/528694b27093555eee0ce5dccf50dc0aa22397b0/geometry/proximity/vtk_to_volume_mesh.cc#L32)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'll need [vtkDataReader](https://vtk.org/doc/nightly/html/classvtkDataReader.html) (or specifically its subclass [vtkUnstructuredGridReader](https://vtk.org/doc/nightly/html/classvtkUnstructuredGridReader.html)), but I don't think Drake has it yet.

I don't see it in this [list in find_vtk_headers.py](https://github.com/RobotLocomotion/drake/blob/857441b5f169814e3164e3ad22d8470e8d937a31/tools/workspace/vtk/find_vtk_headers.py#L35-L69) in this [directory.](https://github.com/RobotLocomotion/drake/tree/master/tools/workspace/vtk)

Please let me know if I misunderstood. CC: @svenevs @zachfang


</blockquote></details>

Most anything that is part of VTK 9.1 is available.  It looks to me like the grid reader has been around forever, so it is part of 9.1 for sure.  (You can grep around in `drake/bazel-drake/external/vtk/include/...` to see what's there.  I definitely see the grid readers.)

If the header isn't exposed to bazel yet, then we will need to edit `drake/tools/workspace/vtk/repository.bzl` to mention the header (and its underlying module) so that our code knows how to `#include` it.

I think @mwoehlke-kitware or @svenevs should be able to help you with the `repository.bzl` edits.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware, @svenevs, @vincekurtz, and @zachfang)

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 32 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NAAbDNx-QkWMSp-zX0S:-NABjV_n9EcfecHFv8bK:b-1rjji4) ([raw file](https://github.com/robotlocomotion/drake/blob/528694b27093555eee0ce5dccf50dc0aa22397b0/geometry/proximity/vtk_to_volume_mesh.cc#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Most anything that is part of VTK 9.1 is available.  It looks to me like the grid reader has been around forever, so it is part of 9.1 for sure.  (You can grep around in `drake/bazel-drake/external/vtk/include/...` to see what's there.  I definitely see the grid readers.)

If the header isn't exposed to bazel yet, then we will need to edit `drake/tools/workspace/vtk/repository.bzl` to mention the header (and its underlying module) so that our code knows how to `#include` it.

I think @mwoehlke-kitware or @svenevs should be able to help you with the `repository.bzl` edits.
</blockquote></details>

Thanks!  Indeed I see them in `drake/bazel-drake/external/vtk/include/...`.

I created issue #17767 to expose them to bazel.

**Review by DamrongGuoy — COMMENTED** [review]
@vincekurtz We changed the code to use VTK library directly instead of writing a simple parser ourselves.  Would you kindly review the code again?

It's much shorter and assumes error handling is performed by VTK.

+@vincekurtz for feature review again, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NAHFU9o32hQv8SPt6C_:b-6dsqky)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware, @svenevs, @vincekurtz, and @zachfang)

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 32 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NAAbDNx-QkWMSp-zX0S:-NAHG6N_Eah62uwwqAgK:b-r7dvs2) ([raw file](https://github.com/robotlocomotion/drake/blob/528694b27093555eee0ce5dccf50dc0aa22397b0/geometry/proximity/vtk_to_volume_mesh.cc#L32)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Thanks!  Indeed I see them in `drake/bazel-drake/external/vtk/include/...`.

I created issue #17767 to expose them to bazel.
</blockquote></details>

Done. Now it calls VTK. @jwnimmer-tri please take a look.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @vincekurtz)

**Review by vincekurtz — COMMENTED** [review]
Sure, no problem. Looks good, just one minor comment. 

Let me know if there are other reviewable buttons I need to press to let the process move on!

> Reviewed 4 of 7 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NAK0MTD1rdnZhT1RR8Q:bwaq5cl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`geometry/proximity/test/vtk_to_volume_mesh_test.cc` line 6 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NAK-ueQE5Pv5b0SPp-E:-NAK-ueQE5Pv5b0SPp-F:bsyzzuk) ([raw file](https://github.com/robotlocomotion/drake/blob/1487c2da2f54c756e79cc55b3701817dc34e4592/geometry/proximity/test/vtk_to_volume_mesh_test.cc#L6)):*
> ```cpp
> 
> #include "drake/common/find_resource.h"
> #include "drake/common/test_utilities/expect_throws_message.h"
> ```

minor, is this used here?

**Review by DamrongGuoy — COMMENTED** [review]
@svenevs CI got multiple [leak-sanitizer errors](https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=1627184) in multibody.  Could you give me a hint, please?  I am adding a new function that no one is using it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NALIjep0BwfICmphQA7:bhfwltd)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @vincekurtz)

**Comment by jwnimmer-tri** [comment]
I can try to help.

What is the intended use for `vtk_to_volume_mesh`?

Will it be used by production code (i.e., at runtime as part of a Drake feature), or is it _only_ going to be used in unit tests or something like that?

**Review by DamrongGuoy — COMMENTED** [review]
Thanks.  It will be at runtime as part of a Drake feature.

BTW, I ran these cammands and they are ok.
```
  515  bazel test -c dbg --config=clang --config=asan //examples/multibody/cart_pole:cart_pole_test
  516  bazel test -c dbg --config=clang --config=asan //multibody/plant:external_forces_test
  517  bazel test -c dbg --config=clang --config=asan //multibody/plant:multibody_plant_forward_dynamics_test
  518  bazel test -c dbg --config=clang --config=asan //multibody/plant:multibody_plant_mass_matrix_test
  519  bazel test -c dbg --config=clang --config=asan //multibody/plant:multibody_plant_test
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NALL1DiDFP6jFgglRBV:bq8rtqs)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @vincekurtz)

**Review by DamrongGuoy — COMMENTED** [review]
We'll use `vtk_to_volume_mesh` to read user-generated tetrahedral meshes for deformables or compliant hydroelastics.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NALLISF10loo4G9yD8N:bxnatyd)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @vincekurtz)

**Comment by jwnimmer-tri** [comment]
Update from f2f:
- We can't use `*.obj` for volume meshes (it only does surface meshes).
- Thus we plan to add a new ShapeType something like VolumeMesh that would have a filename (URI) pointing to a VTK mesh file.
- We need to load those files into the geometry/dynamics engines.

Thus, this is not a test-only dependency, it's one we need to support and ship in `libdrake` as a first-class citizen.

I'll take a quick pass to see if the lsan problem is easily resolved.  Otherwise, we'll circle back here in a week or two.

**Comment by jwnimmer-tri** [comment]
Note that it's **LSan** that's failing (`--config lsan`) not ASan.

**Comment by jwnimmer-tri** [comment]
From grepping, it seems like `std::vector<vtkInformationKey*>` in the error message comes from the global variable in `vtkCommonInformationKeyManager.h`:
```
static vtkCommonInformationKeyManager vtkCommonInformationKeyManagerInstance;
```

To confirm that, the trick is telling LSan to give is better stack traces:

```patch
--- a/tools/dynamic_analysis/lsan.sh
+++ b/tools/dynamic_analysis/lsan.sh
@@ -1,7 +1,7 @@
 #!/bin/bash
 me=$(python3 -c 'import os; print(os.path.realpath("'"$0"'"))')
 mydir=$(dirname "$me")
-export LSAN_OPTIONS="$LSAN_OPTIONS:strip_path_prefix=/proc/self/cwd/:suppressions=$mydir/lsan.supp"
+export LSAN_OPTIONS="$LSAN_OPTIONS:strip_path_prefix=/proc/self/cwd/:suppressions=$mydir/lsan.supp:fast_unwind_on_malloc=0"
 # Ensure executable named llvm-symbolizer is on the PATH.
 export PATH="$PATH:/usr/lib/llvm-12/bin:/usr/local/opt/llvm/bin"
 "$@"
```

... which now prints ...

```console
Direct leak of 2048 byte(s) in 1 object(s) allocated from:
    #0 0x560626ab1bc8 in operator new(unsigned long) (cart_pole_test+0x2968bc8)
    #1 0x7ff4ccc23115 in void std::vector<vtkInformationKey*>::_M_realloc_insert... (libvtkCommonCore-9.1.so.1+0x3e1115)
    #2 0x7ff4ccc23091 in vtkCommonInformationKeyManager::Register(vtkInformationKey*) (libvtkCommonCore-9.1.so.1+0x3e1091)
    #3 0x7ff4cccae6d9 in vtkInformationStringKey::vtkInformationStringKey(char const*, char const*) (libvtkCommonCore-9.1.so.1+0x46c6d9)
    #4 0x7ff4ce1ed4a5  (libvtkFiltersGeneral-9.1.so.1+0xaa4a5)
    #5 0x7ff4cf565b99 in call_init dl-init.c:72:3
```

So yes, the VTK shared library is allocated memory when loaded, and then since we never unload it the memory is leaked.

The main question is why the "still reachable" logic isn't finding it.  Perhaps because the code uses malloc and placement new, to avoid the static initialization order fiasco?

**In any case, that's why library code that uses global variables should be burned at the stake, VTK!**  Goddammit.

This hasn't been a problem previously because we use `vtk_test_tags()` (which disables LSan) for most VTK-based rendering tests, because the whole graphics stack (libGL and the driver support code) have tons of errors.

Here though, we definitely don't want to turn off LSan for all of Drake (i.e., anything that uses libgeometry)!

So now the question is whether we can suppress this (unavoidable) complaint about VTK from LSan.

It seems like this works:
```patch
--- a/tools/dynamic_analysis/lsan.supp
+++ b/tools/dynamic_analysis/lsan.supp
@@ -1 +1 @@
-
+leak:libvtk*-9.1.so.1
```

@DamrongGuoy can you make that change to this PR and push it to CI?

I suppose we should probably put a comment before that like, something like:
```
# Suppress leaks from global variables in VTK's dynamic libraries.
leak:libvtk*-9.1.so.1
```

**Review by DamrongGuoy — COMMENTED** [review]
Thank you.  I'll do that.

And you're right, it's `LSan` not `ASan` to show the problem.
```
 2015  bazel test -c dbg --config=clang --config=lsan //examples/multibody/cart_pole:cart_pole_test
 2016  bazel test -c dbg --config=clang --config=lsan //multibody/plant:external_forces_test
 2017  bazel test -c dbg --config=clang --config=lsan //multibody/plant:multibody_plant_forward_dynamics_test
 2018  bazel test -c dbg --config=clang --config=lsan //multibody/plant:multibody_plant_mass_matrix_test
 2019  bazel test -c dbg --config=clang --config=lsan //multibody/plant:multibody_plant_test
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NALeRenA3px4zZumTAw:b-6x4ji5)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @vincekurtz)

**Review by DamrongGuoy — COMMENTED** [review]
Done. I have tested the five unit tests above on my computer, and they passed.  Now we wait for CI.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NALim358U9Zzdyuwb9l:bpr5fhz)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @vincekurtz)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 3 of 7 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NALoQAgAxVAXdIXBy7q:bnfp4nl)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`geometry/proximity/BUILD.bazel` line 1350 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALgcccCCC0o8adgWG-:-NALgccd0ITVTXlFdxkc:b-jqd3z2) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/BUILD.bazel#L1350)):*
> ```Starlark
>         ":vtk_to_volume_mesh",
>         "//common:find_resource",
>         "//common/test_utilities:expect_throws_message",
> ```

nit Unused
___
*[`geometry/proximity/vtk_to_volume_mesh.h` line 6 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALfxLC-3CqWlE1cix1:-NALfxLC-3CqWlE1cix2:b6nwecf) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/vtk_to_volume_mesh.h#L6)):*
> ```objc
> #include <istream>
> #include <string>
> #include <string_view>
> ```

nit Many of these `#include` seem to be unused?
___
*[`geometry/proximity/vtk_to_volume_mesh.h` line 17 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALg5oP3UQl4J84gQhw:-NALg5oP3UQl4J84gQhx:bkp92u3) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/vtk_to_volume_mesh.h#L17)):*
> ```objc
>  geometries. These internal functions import VolumeMesh from a subset of VTK
>  files (legacy, serial, ASCII, UNSTRUCTURED_GRID). They only support a limited
>  number of tags and ignore the rest. The file format is described in:
> ```

nit Are the comments about "only a limited number of tags" still accurate?
___
*[`geometry/proximity/vtk_to_volume_mesh.h` line 38 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALgB4O7y1JmZ3D4qRz:-NALgB4O7y1JmZ3D4qS-:b-lso150) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/vtk_to_volume_mesh.h#L38)):*
> ```objc
>       10
> 
>  Other sections like POINT_DATA and CELL_DATA for field variables are ignored.
> ```

nit Are these comments still accurate?
___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 14 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALhTsjB5gEMgGtfeEH:-NALhTsk7PvJPSmlabfs:b6vnheu) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/vtk_to_volume_mesh.cc#L14)):*
> ```cpp
> 
> #include "drake/common/eigen_types.h"
> #include "drake/common/text_logging.h"
> ```

nit A lot of these includes above seem to be unused.
___
*[`geometry/proximity/test/vtk_to_volume_mesh_test.cc` line 39 at r8](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALoJQi87SewP27C3Tl:-NALoJQi87SewP27C3Tm:b-c27u4p) ([raw file](https://github.com/robotlocomotion/drake/blob/5bd4a5d30d80d5f91405a204d616ecd9734109aa/geometry/proximity/test/vtk_to_volume_mesh_test.cc#L39)):*
> ```cpp
> }
> 
> }  // namespace
> ```

nit Up to you, but it might be worth a unit test to confirm that if you give it a bogus filename, that you get an exception message.

**Review by DamrongGuoy — COMMENTED** [review]
CI has passed.  The LSan errors were resolved.

And now I'll push minor clean-ups per platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725#-:-NAM-Du911bMhwuffFdv:b-tcvwd0)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`geometry/proximity/BUILD.bazel` line 1350 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALgcccCCC0o8adgWG-:-NALpmfw14Rvj_PDRY9Z:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/BUILD.bazel#L1350)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unused
</blockquote></details>

Done. Thanks.
___
*[`geometry/proximity/vtk_to_volume_mesh.h` line 6 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALfxLC-3CqWlE1cix1:-NALqCnU0jeF-LHPuAx4:bah6nqk) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/vtk_to_volume_mesh.h#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Many of these `#include` seem to be unused?
</blockquote></details>

Done. I removed all except `<string>`. Thanks.
___
*[`geometry/proximity/vtk_to_volume_mesh.h` line 17 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALg5oP3UQl4J84gQhw:-NALqlAM0mQZyHaiMHso:bp173yc) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/vtk_to_volume_mesh.h#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Are the comments about "only a limited number of tags" still accurate?
</blockquote></details>

Ok. It's still accurate because other tags for field variables (scalar, vector, time series) or other kinds of meshes/grids (hexahedral meshes, cartesian grids) are ignored.
___
*[`geometry/proximity/vtk_to_volume_mesh.h` line 38 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALgB4O7y1JmZ3D4qRz:-NALrrfq1H1iXfrDiFZ2:b-ficgd3) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/vtk_to_volume_mesh.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Are these comments still accurate?
</blockquote></details>

Done.  I think the tags `POINT_DATA` and `CELL_DATA` can confuse readers to think about the coordinates of vertices and connectivity of tetrahedra.  Actually, they refer to field variables like pressure field or velocity field.

I added more explanation.
___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 14 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALhTsjB5gEMgGtfeEH:-NALuC4YDAcuePR7c1fK:be9nfur) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c616e6c734281ef048fdc59f0b93cf26bc6a03/geometry/proximity/vtk_to_volume_mesh.cc#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit A lot of these includes above seem to be unused.
</blockquote></details>

Done. Thanks.  I removed most of them.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725)* status: :shipit: complete! all discussions resolved, LGTM from assignees vincekurtz,jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @vincekurtz)

___
*[`geometry/proximity/test/vtk_to_volume_mesh_test.cc` line 39 at r8](https://reviewable.io/reviews/robotlocomotion/drake/17725#-NALoJQi87SewP27C3Tl:-NAM0T447urTh_Nj2PtL:b-3s3nif) ([raw file](https://github.com/robotlocomotion/drake/blob/5bd4a5d30d80d5f91405a204d616ecd9734109aa/geometry/proximity/test/vtk_to_volume_mesh_test.cc#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Up to you, but it might be worth a unit test to confirm that if you give it a bogus filename, that you get an exception message.
</blockquote></details>

Done. I added a TODO.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17725)* status: :shipit: complete! all discussions resolved, LGTM from assignees vincekurtz,jwnimmer-tri(platform) (waiting on @DamrongGuoy)

**Pull request merged**
