### PR TITLE
Fix some issues with RigidBodyConstraint not conforming to the style guide.

### LINKED ISSUE #2306: RigidBodyConstraint does not conform to style guide
Mostly it's just the locations of the `&` and `*` symbols.

Run `clang-format` to see.

### PR DESCRIPTION
**Pull request by sammy-tri**
Fixes #2306...   well, partly.  I could, I think, spend days cleaning up in there.  But it fixes the spacing issue identified there along with access controls and variable names.  I did not get to function names, namespaces, etc...

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2325)

### CODE REVIEW

**Comment by liangfok** [comment]
Looks like there are some API changes here. Need to update the CHANGELOG documenting those changes.

<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> #### Fix some issues with RigidBodyConstraint not conforming to the style guide\.
> 
> Fixes #2306...   well, partly.  I could, I think, spend days cleaning up in there.  But it fixes the spacing issue identified there along with access controls and variable names.  I did not get to function names, namespaces, etc...
> 
> 
> </details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.cpp, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_NBr_O4EwEkdlsgCl:-KH_NBr_O4EwEkdlsgCm:1026787712) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.cpp#L54)):*
> ```cpp
>                           robot, tspan),
>       m_robotnumset_(robotnumset),
>       shrink_factor_(0.9),
> ```

Shouldn't these be initialized using in-class member initialization? https://github.com/RobotLocomotion/drake/pull/2310

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_PF5jGtEo3CBqUDvs:-KH_PF5jGtEo3CBqUDvt:-1256212392) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L19)):*
> ```objc
> namespace DrakeRigidBodyConstraint {
> extern DRAKERIGIDBODYCONSTRAINT_EXPORT Eigen::Vector2d default_tspan;
> }
> ```

Can we add ` // namespace DrakeRigidBodyConstraint` after the above `}`?

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Ou7W-OciFwA5EFGz:-KH_Ou7W-OciFwA5EFH-:431092135) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L22)):*
> ```objc
> 
> /**
>  * @class RigidBodyConstraint       The abstract base class. All the constraints
> ```

"All the" -> "All"

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_P10BxP3NQt_AaXcr:-KH_P10BxP3NQt_AaXcs:1854031089) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L25)):*
> ```objc
>  * used in the inverse kinematics problem are inherited from
>  * RigidBodyConstraint. There are 6 main categories of the RigidBodyConstraint,
>  * each category has its own interface
> ```

Can you add a paragraph describing each of the six categories? Any by "categories" do you mean "collections of subclasses"?

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 67 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oef5A-w7o0JgahyG:-KH_Oef5A-w7o0JgahyH:1278905826) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L67)):*
> ```objc
>       int category, RigidBodyTree* robot,
>       const Eigen::Vector2d& tspan = DrakeRigidBodyConstraint::default_tspan);
>   int getType() const { return type_; }
> ```

Should this be `type()`? @amcastro-tri?

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 68 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_O_F9QN9mK-df52DD:-KH_O_F9QN9mK-df52DE:-1985093740) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L68)):*
> ```objc
>       const Eigen::Vector2d& tspan = DrakeRigidBodyConstraint::default_tspan);
>   int getType() const { return type_; }
>   int getCategory() const { return category_; }
> ```

Should this be `category()`?  @amcastro-tri?

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 69 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_OHXXPiB_jXyL9AUT:-KH_OHXXPiB_jXyL9AUU:-295092438) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L69)):*
> ```objc
>   int getType() const { return type_; }
>   int getCategory() const { return category_; }
>   RigidBodyTree* getRobotPointer() const { return robot_; }
> ```

@amcastro-tri, do you approve of this method name? Would `robot_pointer()` or `robot()` be better and more consistent with the latest code styling customs we're trying to foster?

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oko_Pb7nzuApwoyP:-KH_Oko_Pb7nzuApwoyQ:-1360928411) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L73)):*
> ```objc
> 
>  protected:
>   std::string getTimeString(const double* t) const;
> ```

Should this be `time_string(const double* t)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-:-KH_Npmaq-rYOEU-UAjR:1689320125)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_PF5jGtEo3CBqUDvs:-KH_Q3Ikg_p0yOAKX7i0:-139667878) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Can we add ` // namespace DrakeRigidBodyConstraint` after the above `}`?</details>
Not required when the namespace is less than 10 lines.  Here, it would reduce clarity, not add it.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 67 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oef5A-w7o0JgahyG:-KH_QJuBUmC65HAPtTXv:416279668) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L67)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should this be `type()`? @amcastro-tri?</details>
This PR is only a partial style fix.  This is just the prior spelling.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 68 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_O_F9QN9mK-df52DD:-KH_QilxZprx7q7QM8EY:416279668) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L68)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should this be `category()`?  @amcastro-tri?</details>
This PR is only a partial style fix.  This is just the prior spelling.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 69 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_OHXXPiB_jXyL9AUT:-KH_QQ6zQ0WPETuqJtKe:416279668) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L69)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> @amcastro-tri, do you approve of this method name? Would `robot_pointer()` or `robot()` be better and more consistent with the latest code styling customs we're trying to foster?</details>
This PR is only a partial style fix.  This is just the prior spelling.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oko_Pb7nzuApwoyP:-KH_QUsVudHHxEHd-4Q0:1858771095) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L73)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should this be `time_string(const double* t)`</details>
This PR is only a partial style fix.  This is just the prior spelling.  This line isn't even changed in the diff!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oko_Pb7nzuApwoyP:-KH_UoKrGztWgPRd50w4:-1623546545) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This PR is only a partial style fix.  This is just the prior spelling.  This line isn't even changed in the diff!</details>
Alas, the ever-present inherent conflict between pace of fixing defects and trying to conform to the small PR-size-objective.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oko_Pb7nzuApwoyP:-KH_W_XZ1zHbh49Toniw:848582485) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L73)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Alas, the ever-present inherent conflict between pace of fixing defects and trying to conform to the small PR-size-objective.</details>
Not really.  A PR chain of "batch 1 of N style fixes", evaluated on "is this monotonically better" is actually faster paced than any other mechanism available under the umbrella of pre-commit review.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oko_Pb7nzuApwoyP:-KH_dyn7pbqV3c99vWAQ:695396541) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Not really.  A PR chain of "batch 1 of N style fixes", evaluated on "is this monotonically better" is actually faster paced than any other mechanism available under the umbrella of pre-commit review.</details>
I believe the ability to create a "batch of 1 of N style fixes" where each element in the batch is "small" is in conflict with the fact that it's difficult, if not impossible, to undergo a rational process when creating a new feature. Perhaps this gets back to my other post about needing to first charge forward developing a new feature, then go back and "fake" a batch of 1-N incremental and rational changes that eventually lead up to the new feature being integrated into master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oko_Pb7nzuApwoyP:-KH_fDSRBGLutaB2lXWw:959837684) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L73)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I believe the ability to create a "batch of 1 of N style fixes" where each element in the batch is "small" is in conflict with the fact that it's difficult, if not impossible, to undergo a rational process when creating a new feature. Perhaps this gets back to my other post about needing to first charge forward developing a new feature, then go back and "fake" a batch of 1-N incremental and rational changes that eventually lead up to the new feature being integrated into master.</details>
But this PR isn't a feature.  It's _only_ a style fix, for which there is a well-known checklist to traverse (the list of rules), and a clear intermediate pass criteria (CI passes and every edit is a strict improvement).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oko_Pb7nzuApwoyP:-KH_gBcr6AjooT_2KWVr:-1911252891) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> But this PR isn't a feature.  It's _only_ a style fix, for which there is a well-known checklist to traverse (the list of rules), and a clear intermediate pass criteria (CI passes and every edit is a strict improvement).</details>
Ah. Good point. I was clearly coming from a different context. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325)*

**Comment by sammy-tri** [comment]
I did not make any deliberate changes to the external API for RigidBodyConstraint or its derived classes.  Could you be more specific?  I may want to revert.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Looks like there are some API changes here. Need to update the CHANGELOG documenting those changes.</details>


---

Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.cpp, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_NBr_O4EwEkdlsgCl:-KH_qbNgXLAVPbJOjedP:-2142740532) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.cpp#L54)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Shouldn't these be initialized using in-class member initialization? https://github.com/RobotLocomotion/drake/pull/2310</details>
Added {} to the declarations in the header file.  From discussion with @jwnimmer-tri, I believe #2310 is intended only to make sure all POD types have an in-class initializer (even if it's the default), not to ban use of initializers at the constructor. 

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Ou7W-OciFwA5EFGz:-KH_r18V57KW-Cd5MhCr:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "All the" -> "All"</details>
Done.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_P10BxP3NQt_AaXcr:-KH_r4L6obC0ojN651aV:-203628513) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Can you add a paragraph describing each of the six categories? Any by "categories" do you mean "collections of subclasses"?</details>
Honestly?  Not with any significant amount of clarity.  All the categories really mean to me are their APIs.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 67 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oef5A-w7o0JgahyG:-KH_shnRRjCG83YbgSd9:690461880) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This PR is only a partial style fix.  This is just the prior spelling.</details>
== @jwnimmer-tri

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 68 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_O_F9QN9mK-df52DD:-KH_smOe4iuWCsjhHm9G:690461880) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This PR is only a partial style fix.  This is just the prior spelling.</details>
== @jwnimmer-tri

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 69 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_OHXXPiB_jXyL9AUT:-KH_sopggLGV2kwGGWAP:690461880) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L69)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This PR is only a partial style fix.  This is just the prior spelling.</details>
== @jwnimmer-tri

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-:-KH_pz_Vea6vwtH2nnXW:1930106320)*

**Comment by liangfok** [comment]
:lgtm: 

<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I did not make any deliberate changes to the external API for RigidBodyConstraint or its derived classes.  Could you be more specific?  I may want to revert.</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_P10BxP3NQt_AaXcr:-KH_uLXZJjIAeDqc8C0k:564457086) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L25)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Honestly?  Not with any significant amount of clarity.  All the categories really mean to me are their APIs.</details>
I guess the names of each `static const int` is sufficiently self explanatory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-:-KH_uXk99Z1gf9Fpy0ik:980077423)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri for platform review.  Thanks @liangfok!

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> :lgtm: </details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-:-KH_xv9F5EX3rGAATKn-:-155580128)*

**Comment by amcastro-tri** [comment]
wow! I wouldn't've had the patience myself to make all these style changes. Thank you @sammy-tri!

<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> +@jwnimmer-tri for platform review.  Thanks @liangfok!</details>


---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.cpp, line 166 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KHaKM9JEFZ9qZ3zlScH:-KHaKM9JEFZ9qZ3zlScI:1100381783) ([raw file](https://github.com/robotlocomotion/drake/blob/0786e4faa3e3c6704806f6974ac7061aa29f24f8/drake/systems/plants/constraint/RigidBodyConstraint.cpp#L166)):*
> ```cpp
>   for (int i = 0; i < num_new_bodies; i++) {
>     bool findDuplicateBody = false;
>     if (new_body_pts[i].rows() != 3) {
> ```

Is this check needed? the argument is a Matrix3Xd so it has to have 3 rows or it wont compile.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 67 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_Oef5A-w7o0JgahyG:-KHaKsOqdwWXCyNZzy_W:-1082324122) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L67)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> == @jwnimmer-tri</details>
I agree. It'd be nice if it was just `type()` but I wouldn't block this PR because of this

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 68 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_O_F9QN9mK-df52DD:-KHaL-zQQv911im-mZSI:1422984132) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L68)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> == @jwnimmer-tri</details>
same as above

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 69 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KH_OHXXPiB_jXyL9AUT:-KHaL6_kN1nC_WvoSXfd:-2020124892) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L69)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> == @jwnimmer-tri</details>
That method is part of the previous API. It'd be nice to fix it as you suggest but I won't block this PR for this. I would block it if `getRobotPointer` was a new method. I am ok if @sammy-tri wants to fix this now though :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-:-KHaLe5afI-d4BH57B2e:-413736287)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KHaMgbLFwgBl2Z-aWwa:-KHaMgbMTio8GtxyCTA0:-1818214151) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L17)):*
> ```objc
> class RigidBodyTree;
> 
> namespace DrakeRigidBodyConstraint {
> ```

Sorry I don't understand but what happened here to `com_pts` and `WorldCoMDefaultRobotNum`. Where did they go?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325)*

**Comment by jwnimmer-tri** [comment]
I reviewed the commits, not the all-in diffs, and it looks good.  There is still _so much more_ to do, but this is a great start.

:lgtm:

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> wow! I wouldn't've had the patience myself to make all these style changes. Thank you @sammy-tri!</details>


---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-:-KHaU3n04rNVsp9_Pn8z:-448007821)*

**Comment by sammy-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.cpp, line 166 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KHaKM9JEFZ9qZ3zlScH:-KHaT7cjntZAbNxjtdYn:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0786e4faa3e3c6704806f6974ac7061aa29f24f8/drake/systems/plants/constraint/RigidBodyConstraint.cpp#L166)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Is this check needed? the argument is a Matrix3Xd so it has to have 3 rows or it wont compile.</details>
Done.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-KHaMgbLFwgBl2Z-aWwa:-KHaTKQqb-Kdp-cl0iGw:662853316) ([raw file](https://github.com/robotlocomotion/drake/blob/25de4752690b67ae1353fada6cc8b7773b313cfd/drake/systems/plants/constraint/RigidBodyConstraint.h#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Sorry I don't understand but what happened here to `com_pts` and `WorldCoMDefaultRobotNum`. Where did they go?</details>
com_pts was a Vector3d::Zero which was only used in one place in the cpp file, so I changed it to a Vector3d::zero in that location.  WorldComDefaultRobotNum moved into the anonymous namesapce in the cpp file.  I didn't see how these values formed part of the external API (and they weren't used externally), so I moved them out of the header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325)*

**Comment by amcastro-tri** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I reviewed the commits, not the all-in diffs, and it looks good.  There is still _so much more_ to do, but this is a great start.
> 
> :lgtm:</details>


---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-:-KHasFAs6_tg3RBvgqvG:1417088721)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325)*

**Comment by jwnimmer-tri** [comment]
Just need @liangfok to OK his discussions, and we should be able to merge.

**Comment by liangfok** [comment]
Done. PTAL and them merge!

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Just need @liangfok to OK his discussions, and we should be able to merge.</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2325#-:-KHauwTSMYTJ53n88ZKW:-739699892)*

**Comment by jwnimmer-tri** [comment]
Using override-merge from out-of-date-with-master.

**Pull request merged**
