### PR TITLE
camera_info: Permit constructing from intrinsic matrix

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
No acute need, just been wanting this.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14402)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sammy-tri for both reviews, please!

+(status: single reviewer ok) 
FYI @seancurtis-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14402#-:-MNVsAtr97tKDu10vRjc:b6jalan)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14402)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[systems/sensors/camera_info.cc, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14402#-MNVsSU0-dK3P6lb45pE:-MNVsSU0-dK3P6lb45pF:bz1rirn) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebac222af148e22d89385fffa38ea16e86ab208/systems/sensors/camera_info.cc#L11)):*
> ```cpp
> CameraInfo::CameraInfo(int width, int height, double focal_x, double focal_y,
>              double center_x, double center_y)
>     : CameraInfo(width, height, (
> ```

BTW A bit less efficient, but IMO it feels weird to duplicate the logic. But meh, it's not that much anywho.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14402)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI)

___
*[systems/sensors/camera_info.cc, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14402#-MNZwan-4d7pglog0kKW:-MNZwan07QaFdrjTO1Ze:b-7frjxd) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebac222af148e22d89385fffa38ea16e86ab208/systems/sensors/camera_info.cc#L34)):*
> ```cpp
>   DRAKE_ASSERT(K(2, 0) == 0.0);
>   DRAKE_ASSERT(K(2, 1) == 0.0);
>   DRAKE_ASSERT(K(2, 1) == 1.0);
> ```

I don't think both of these assertions can pass...

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14402)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[systems/sensors/camera_info.cc, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14402#-MNZwan-4d7pglog0kKW:-MNfE6Oi-38mmYgRMNHo:b-z57jll) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebac222af148e22d89385fffa38ea16e86ab208/systems/sensors/camera_info.cc#L34)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think both of these assertions can pass...
</blockquote></details>

Done. D'oh!
Though I feel like the correct solution should involve the `volatile` keyword :thinking:

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14402#-:-MNiYrCL-2AAXGGFrQ0j:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

**Pull request merged**
