### PR TITLE
WIP: make a python launcher to replace the shell scripts we have been…

### PR DESCRIPTION
**Pull request by rpoyner-tri**
… using.

 * refactor some common path wrangling into drake_paths.py.
 * some refactor/cleanup in steering_command_driver.py.
 * introduce automotive_demo.py, the launcher script.
 * tweak .pylintrc.

Much is not yet addressed. TODOs:

 * fix/rewrite README.md.
 * produce a list of python packages for apt-get install.
 * better command line options/doc for the launcher modes.
 * more documentation, comments, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3561)

### CODE REVIEW

**Comment by liangfok** [comment]
I confirm this script works on my machine. One nit is I initially ran `./automotive_demo.py` thinking it would exit printing the command line options but instead it went ahead and ran `simple_car_demo`.

**Comment by rpoyner-tri** [comment]
noted. Like i said, there's more work to do...

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-:-KSRpotccoGbVkRpiTyB:b-2uekdi)*

**Comment by rpoyner-tri** [comment]
The python script wants to become a regression test when it grows up, but that involves a fair amount of cmake script refactoring and careful configuration testing. A test was attempted here, but is now withdrawn from this PR.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-:-KSRyfg9sOz7WDf6wX5Z:bxoc2dc)*

**Comment by rpoyner-tri** [comment]
+@jwnimmer-tri for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-:-KSRzwFe9wmRu7QlOsQ_:b-qf68jg)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSTc6uISSox-YvL1Sge:-KSTc6uJTvVFnAeO7FD_:bafrowv) ([raw file](https://github.com/robotlocomotion/drake/blob/1cbf8a01d17318927abb5ea352d850db2aeaee13/drake/automotive/automotive_demo.py#L64)):*
> ```Python
>         supplied, a label is synthesized from the supplied command line.
>         """
>         command_words = command.split()
> ```

BTW Concatenating a string in using-code and then splitting it apart again here seems like it will be brittle, though it appears to work for now.

---

*[drake/automotive/automotive_demo.py, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSTd5Wp8ya6inaWSwqd:-KSTd5WqThArASi-mU_G:berqwd) ([raw file](https://github.com/robotlocomotion/drake/blob/1cbf8a01d17318927abb5ea352d850db2aeaee13/drake/automotive/automotive_demo.py#L97)):*
> ```Python
>                 print "[%s] %s exited via duration elapsed" % (
>                     self.name, self.name)
>                 done = True
> ```

This seems to miss setting self.returncode = 0, per the comment on the outer `wait` method.

---

*[drake/automotive/automotive_demo.py, line 148 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSTayde729eJHr-YRTV:-KSTaydf3DLPA25rrLQq:bzcnaun) ([raw file](https://github.com/robotlocomotion/drake/blob/1cbf8a01d17318927abb5ea352d850db2aeaee13/drake/automotive/automotive_demo.py#L148)):*
> ```Python
>     """Wait for a single message to arrive on the specified LCM channel.
>     """
>     lc = lcm.LCM()
> ```

BTW `lc` is an odd abbreviation.

---

*[drake/automotive/automotive_demo.py, line 199 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSTbYWqwPxbqEL2v3hO:-KSTbYWr2fNZgttNYxcH:bmw0pu0) ([raw file](https://github.com/robotlocomotion/drake/blob/1cbf8a01d17318927abb5ea352d850db2aeaee13/drake/automotive/automotive_demo.py#L199)):*
> ```Python
>     theLauncher.launch(os.path.join(DRAKE_INSTALL_BIN_DIR, "drake-visualizer"))
> 
>     # Wait, to be sure drake-visualizer sees the load_robot message.
> ```

This comment is a bit unclear.  I believe we are waiting for drake-visualizer to be ready, so that it _will be able to see_ the load_robot message from the demo; as written, it sounds a bit like we are waiting _until_ it sees the load_robot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561)*

**Comment by rpoyner-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSTc6uISSox-YvL1Sge:-KSXMgXuVh2NnVAB_ZWG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1cbf8a01d17318927abb5ea352d850db2aeaee13/drake/automotive/automotive_demo.py#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Concatenating a string in using-code and then splitting it apart again here seems like it will be brittle, though it appears to work for now.
</details>
Done.

---

*[drake/automotive/automotive_demo.py, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSTd5Wp8ya6inaWSwqd:-KSXJdlZaNADOK2QXoqJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1cbf8a01d17318927abb5ea352d850db2aeaee13/drake/automotive/automotive_demo.py#L97)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This seems to miss setting self.returncode = 0, per the comment on the outer `wait` method.
</details>
Done.

---

*[drake/automotive/automotive_demo.py, line 148 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSTayde729eJHr-YRTV:-KSXKUR63T61M78-1D-c:bg9n2b3) ([raw file](https://github.com/robotlocomotion/drake/blob/1cbf8a01d17318927abb5ea352d850db2aeaee13/drake/automotive/automotive_demo.py#L148)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW `lc` is an odd abbreviation.
</details>
changed to 'm', to match the example code at https://lcm-proj.github.io/python/index.html

---

*[drake/automotive/automotive_demo.py, line 199 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSTbYWqwPxbqEL2v3hO:-KSXInwylUYmPWq_H4cN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1cbf8a01d17318927abb5ea352d850db2aeaee13/drake/automotive/automotive_demo.py#L199)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This comment is a bit unclear.  I believe we are waiting for drake-visualizer to be ready, so that it _will be able to see_ the load_robot message from the demo; as written, it sounds a bit like we are waiting _until_ it sees the load_robot.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-:-KSXWZQh0mW1Vzy7_3nv:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
+@ggould-tri for platform review, please.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-:-KSaudIH2YDI94crawBz:bcav8r0)*

**Comment by ggould-tri** [comment]
:lgtm: pending open discussions.

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSb70hoHfApD6BOOybO:-KSb70hoHfApD6BOOybP:bp99xzi) ([raw file](https://github.com/robotlocomotion/drake/blob/0ea0c13619aeee6db3c345fb1c18a3aa90532fe7/drake/automotive/automotive_demo.py#L139)):*
> ```Python
>                 child.process.kill()
> 
> theLauncher = Launcher()
> ```

pep8 disallows `mixedCase` names except for compatibility or consistency.

---

*[drake/automotive/steering_command_driver.py, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSbCxI-88lHzEUniGO_:-KSbCxI-88lHzEUniGOa:b-dwnj9h) ([raw file](https://github.com/robotlocomotion/drake/blob/0ea0c13619aeee6db3c345fb1c18a3aa90532fe7/drake/automotive/steering_command_driver.py#L19)):*
> ```Python
> from drake_paths import add_module_search_paths
> 
> add_module_search_paths()  # so we can find lcm stuff.
> ```

FYI: Cap

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-:-KSbDDQWXrDsYLgnPkoM:buvdl6p)*

**Comment by rpoyner-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSb70hoHfApD6BOOybO:-KSb_HvfmHPftXu-jBO1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0ea0c13619aeee6db3c345fb1c18a3aa90532fe7/drake/automotive/automotive_demo.py#L139)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> pep8 disallows `mixedCase` names except for compatibility or consistency.
</details>
Done.

---

*[drake/automotive/steering_command_driver.py, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3561#-KSbCxI-88lHzEUniGO_:-KSb_Ja3F1wAJ9ffw4-_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0ea0c13619aeee6db3c345fb1c18a3aa90532fe7/drake/automotive/steering_command_driver.py#L19)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI: Cap
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3561)*

**Pull request merged**
