### PR TITLE
Move QueryHandle to QueryObject

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The old QueryHandle required the user to maintain a pointer
to the GeometrySystem. This interefered with transmogrication;
the transmogrified source system would have to have a pointer
to the transmogrified GeometrySystem -- while not impossible,
it's an ugly, inelegant workflow. This provides a better,
independent interface.

```
Category            added  modified  removed  
----------------------------------------------
code                205    30        69       
comments            82     16        61       
blank               54     0         24       
----------------------------------------------
TOTAL               341    46        154 
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7662)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@avalenzu  or +@amcastro-tri  for feature review -- whoever gets to it first. Please kick the other off.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-:-L0zh-jU3NceWHict6IM:b-qb9f14)*

**Comment by avalenzu** [comment]
-@amcastro-tri 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-:-L21YjBm4zpBByYQ8waT:bsv1qg2)*

**Comment by avalenzu** [comment]
Review pass done. PATL.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21_AeSftOWf7Szk597:-L21_AeSftOWf7Szk598:b-mxzye7) (no related file):*
Meta question: Should `QueryObject` just be `Query`? I mean, yes, it's an object, but, by that logic, all class names should end in `Object`. Is the intention to avoid confusion due to "Query" also being a verb?

---

*[geometry/geometry_system.cc, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21ZAwx27cErUpSWSiz:-L21ZAwx27cErUpSWSj-:b-wg80i5) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/geometry_system.cc#L235)):*
> but initialize to null anyways.

Why?

---

*[geometry/geometry_system.cc, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21ZPgh99QlzUGmldaD:-L21ZPgh99QlzUGmldaE:b-2dpst9) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/geometry_system.cc#L248)):*
> ```cpp
>       dynamic_cast<const GeometryContext<T>*>(&context);
>   DRAKE_DEMAND(geom_context);
>   // The result of calling calc should *always* produce a live query object.as
> ```

Trailing characters after the period.

---

*[geometry/geometry_system.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21Z_QvYckhvnnr5mI7:-L21Z_QvYckhvnnr5mI8:bk2hvob) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/geometry_system.h#L24)):*
> ```objc
> template <typename T> class QueryObject;
> 
> /** GeometrySystem serves
> ```

BTW, this is much easier to review (as opposed to having the entire paragraph re-wrapped), but don't forget to re-wrap this before merging the PR

---

*[geometry/query_object.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21_uemDOGdPLhPMbWi:-L21_uemDOGdPLhPMbWj:b-qlsaek) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L16)):*
> One of the GeometrySystem output ports is abstract-valued on the %QueryObject.

Is "abstract-valued on" really how we want to phrase this concept? Perhaps,

> One of the GeometrySystem output ports is an abstract-valued port that contains a %QueryObject.

instead? Yes, I know this isn't really new code, but that's what you get for renaming things :)

---

*[geometry/query_object.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21awFXXFAJNH-h69zw:-L21awFXXFAJNH-h69zx:bv5dadq) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L19)):*
FYI you give another example of an alternate phrasing here:

> a %QueryObject-valued input port

---

*[geometry/query_object.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21bQagMNU113MPR1UJ:-L21bQagMNU113MPR1UK:b-293rea) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L27)):*
> This const reference should _never_ be persisted.

Below you mention that copying and then performing queries will lead to an exception. What happens if someone does persist the reference?

---

*[geometry/query_object.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21bkfQkTVR4hmC9hIv:-L21bkfQkTVR4hmC9hIw:b-lvexu9) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L40)):*
> To acquire a %QueryObject with a particular scalar type, it must be provided by a GeometrySystem instance of that scalar type from a corresponding GeometryContext based on the scalar type.

Something about the combination of "To acquire ... it must be provided" seems awkward. Could this be

> A %QueryObject of a particular scalar type can only be provided by a GeometrySystem instance of that scalar type from a corresponding GeometryContext based on the scalar type.

instead?

---

*[geometry/query_object.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21dEJDd7r4aRbPWaCr:-L21dEJDd7r4aRbPWaCs:b-fkvki0) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L68)):*
FYI

> Throws an exception for

Consider using `@throws` here and for `GetFrameId()`

---

*[geometry/query_object.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21dSx12aABXtt0AfJx:-L21dSx12aABXtt0AfJy:b-omovep) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L70)):*
> ```objc
>   /** Reports the name for the given source id. Throws an exception for
>    invalid identifiers.  */
>   const std::string& get_source_name(SourceId id) const;
> ```

Should this be `GetSourceName()`? It seems like we'd want all the queries to use the same convention.

---

*[geometry/test/query_object_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21eY9es7mQgVW2b5JH:-L21eY9es7mQgVW2b5JI:b-enmw2c) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/test/query_object_test.cc#L64)):*
> ```cpp
>     geom_context_ = dynamic_cast<GeometryContext<double>*>(context_.get());
>     ASSERT_NE(geom_context_, nullptr);
>     query_object_ = QueryObjectTester::MakeQueryObject(geom_context_, &system_);
> ```

Since you provided a shorthand for `QueryObjectTester`, do you want to use it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-:-L21euAb3izlXItoNDtC:b82vq79)*

**Comment by SeanCurtis-TRI** [comment]
Thanks for the comments -- PTAL.

---

Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21_AeSftOWf7Szk597:-L22QqeJ-Xf3h4QkCpGg:bt60l0d) (no related file):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Meta question: Should `QueryObject` just be `Query`? I mean, yes, it's an object, but, by that logic, all class names should end in `Object`. Is the intention to avoid confusion due to "Query" also being a verb?
</blockquote></details>

An interesting question. In an earlier incarnation, it was a `QueryHandle` -- it was something you got from the input port and passed into a copy of the `GeometrySystem`. It's no longer handle. It's not **a** `Query` itself, it's a mechanism by which many different types of queries can be made. So, I think not `Query`, but I'm open to alternatives.

---

*[geometry/geometry_system.cc, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21ZAwx27cErUpSWSiz:-L22Rj0Bkf7rikXZAIdS:bi7rn5c) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/geometry_system.cc#L235)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> but initialize to null anyways.

Why?
</blockquote></details>

Elaboration provided.

---

*[geometry/geometry_system.cc, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21ZPgh99QlzUGmldaD:-L22Rtsdv6EmJe0KFu6H:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/geometry_system.cc#L248)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Trailing characters after the period.
</blockquote></details>

Done

---

*[geometry/geometry_system.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21Z_QvYckhvnnr5mI7:-L22SByZjY96jCiS-szY:bjdwaeu) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/geometry_system.h#L24)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, this is much easier to review (as opposed to having the entire paragraph re-wrapped), but don't forget to re-wrap this before merging the PR
</blockquote></details>

With a strong admonition to wrap -- I went ahead and wrapped now. The impact is limited to this paragraph (and reviewable usually does a decent job with it.)

---

*[geometry/query_object.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21_uemDOGdPLhPMbWi:-L22SSMIjFx1GTh9rxk9:b53x2ay) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L16)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> One of the GeometrySystem output ports is abstract-valued on the %QueryObject.

Is "abstract-valued on" really how we want to phrase this concept? Perhaps,

> One of the GeometrySystem output ports is an abstract-valued port that contains a %QueryObject.

instead? Yes, I know this isn't really new code, but that's what you get for renaming things :)

</blockquote></details>

Verbing weirds language.  :D

Done

---

*[geometry/query_object.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21awFXXFAJNH-h69zw:-L22Slk2W7oGVYfprVZa:bezcic9) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L19)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

FYI you give another example of an alternate phrasing here:

> a %QueryObject-valued input port

</blockquote></details>

I elaborated in the previous definition to allow for this shorthand.

---

*[geometry/query_object.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21bQagMNU113MPR1UJ:-L22T4Tc3bJA70c9PlUr:bhuu6lo) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L27)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> This const reference should _never_ be persisted.

Below you mention that copying and then performing queries will lead to an exception. What happens if someone does persist the reference?
</blockquote></details>

Clarified

---

*[geometry/query_object.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21bkfQkTVR4hmC9hIv:-L22TWOlkfNku7SC2HVE:b8n1yq1) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L40)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> To acquire a %QueryObject with a particular scalar type, it must be provided by a GeometrySystem instance of that scalar type from a corresponding GeometryContext based on the scalar type.

Something about the combination of "To acquire ... it must be provided" seems awkward. Could this be

> A %QueryObject of a particular scalar type can only be provided by a GeometrySystem instance of that scalar type from a corresponding GeometryContext based on the scalar type.

instead?
</blockquote></details>

You're right about the unwieldiness of that phrase. Inspired by your suggestion, I tried a third option.

---

*[geometry/query_object.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21dEJDd7r4aRbPWaCr:-L22UECOB7jNKIUGYiUo:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L68)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

FYI

> Throws an exception for

Consider using `@throws` here and for `GetFrameId()`

</blockquote></details>

Done

---

*[geometry/query_object.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21dSx12aABXtt0AfJx:-L22UJGdHFoq39ItSTfb:bjfrcgz) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L70)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Should this be `GetSourceName()`? It seems like we'd want all the queries to use the same convention.
</blockquote></details>

Well, get source name is cheap, allowing this alternative name. However, the fact that it's cheap is probably irrelevant. This isn't something someone would be calling at the bottom of some tight iteration. So, we'll go for matching instead.

---

*[geometry/test/query_object_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21eY9es7mQgVW2b5JH:-L22UnUlsKwY09wI3tUO:b-oz8o77) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/test/query_object_test.cc#L64)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Since you provided a shorthand for `QueryObjectTester`, do you want to use it here?
</blockquote></details>

Good catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-:-L22UpG-g8f46jtg4ydL:b-on5ugd)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21_AeSftOWf7Szk597:-L25XmVaDRq4kJI9pHh2:b-6t91is) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

An interesting question. In an earlier incarnation, it was a `QueryHandle` -- it was something you got from the input port and passed into a copy of the `GeometrySystem`. It's no longer handle. It's not **a** `Query` itself, it's a mechanism by which many different types of queries can be made. So, I think not `Query`, but I'm open to alternatives.
</blockquote></details>

Ah, yes, I'd forgotten that it wasn't the query itself. Since `MechanismByWhichManyDifferentQueriesCanBeMade` is kind of long, and I haven't been able to think of a good alternative, `QueryObject` is fine with me.

---

*[geometry/geometry_system.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21Z_QvYckhvnnr5mI7:-L25WeHGyrsbcGz7nsir:b-olnzz2) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/geometry_system.h#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

With a strong admonition to wrap -- I went ahead and wrapped now. The impact is limited to this paragraph (and reviewable usually does a decent job with it.)
</blockquote></details>

Yeah, that's better than I expected Reviewable to do. No dark highlights!

---

*[geometry/query_object.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21_uemDOGdPLhPMbWi:-L25Wt8UwhosbqVl_UL7:b72scyk) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L16)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Verbing weirds language.  :D

Done
</blockquote></details>

+1 for the Calvin & Hobbes reference.

---

*[geometry/query_object.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L21bkfQkTVR4hmC9hIv:-L21bir7Y7xzH2pyuErl:b-j60pj2) ([raw file](https://github.com/robotlocomotion/drake/blob/2ab319778653f96afaa7a5be07638233a1669a4c/geometry/query_object.h#L40)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You're right about the unwieldiness of that phrase. Inspired by your suggestion, I tried a third option.
</blockquote></details>

Yes, that's much better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-:-L25YP2nnRMOi-rfa6ZV:bnfp4nl)*

**Comment by avalenzu** [comment]
+@sherm1 for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-:-L25YTHsjnFN8gffKguz:buasbda)*

**Comment by sherm1** [comment]
Platform :lgtm: after dealing with some BTWs, ptal.

---

Reviewed 2 of 8 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[geometry/geometry_system.cc, line 237 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27IZYGRKlprjd74V3M:-L27IZYGRKlprjd74V3N:bc7pmu9) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/geometry_system.cc#L237)):*
> ```cpp
>   // anyways. It *must* be initialized to null to be compatible with how this
>   // instance is used to initialize the context (see documentation on
>   // QueryObject).
> ```

BTW this seems an odd use of the supplied Context and I don't really get it. I did read the QueryObject documentation and I still don't get it. Checking that the context is the right type seems like an unrelated error check -- why does that have to be done while making a default QueryObject? Can you separate these two operations?

---

*[geometry/geometry_system.cc, line 245 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27JLGd_knvzhruXStv:-L27JLGd_knvzhruXStw:by2vo1y) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/geometry_system.cc#L245)):*
> ```cpp
> 
> template <typename T>
> void GeometrySystem<T>::CalcQueryObject(const Context<T>& context,
> ```

BTW per styleguide this should be a `const Context<T>*` since the object retains a copy of the pointer.

---

*[geometry/geometry_system.cc, line 249 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27JD4jfjafDZ2zXswS:-L27JD4jfjafDZ2zXswT:bhwuya3) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/geometry_system.cc#L249)):*
> ```cpp
>   const GeometryContext<T>* geom_context =
>       dynamic_cast<const GeometryContext<T>*>(&context);
>   DRAKE_DEMAND(geom_context);
> ```

BTW here it makes sense since the object hangs on to the context.

---

*[geometry/geometry_system.h, line 436 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27GGXrF08bWnmraz8J:-L27GGXrF08bWnmraz8K:b-eqm96n) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/geometry_system.h#L436)):*
> ```objc
> 
>   // Constructs a QueryObject for OutputPort allocation.
>   QueryObject<T> MakeQueryObject(const systems::Context<T>& context) const;
> ```

BTW consider a comment about what this does with the context.

---

*[geometry/query_object.h, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27Hkd7PUnbn5ZwFokK:-L27Hkd7PUnbn5ZwFokL:b-mmrn77) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/query_object.h#L112)):*
> ```objc
>   // context).
>   const GeometryContext<T>* context_{};
>   const GeometrySystem<T>* system_{};
> ```

BTW per f2f -- these could be replaced by a single `SystemIndex` giving the GeometrySystem index in the parent diagram which is shared by both the Source system and GeometrySystem. That is enough to obtain these two pointers from the parent system and parent context. No defect here but in case the presence of these pointers causes problems, you could get rid of them.

---

*[geometry/test/geometry_system_test.cc, line 539 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27EYCBDfKFoortVDgZ:-L27EYCBDfKFoortVDg_:bqw680e) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/test/geometry_system_test.cc#L539)):*
> ```cpp
> // facility for me to edit the pose written to the output port between
> // invocations.
> class DummySourceSystem : public systems::LeafSystem<double> {
> ```

BTW is this unused? Maybe defer until a later PR.

---

*[geometry/test/query_object_test.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27F93QQfZJ37kGGFDT:-L27F93QQfZJ37kGGFDU:b-z7qzg3) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/test/query_object_test.cc#L15)):*
> ```cpp
> 
> // Helper class for testing the query object.
> class QueryObjectTester {
> ```

BTW consider templatizing class on T so you don't have to templatize the individual methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-:-L27JaTaPY6nUWVCCLY8:b-hpnkbz)*

**Comment by SeanCurtis-TRI** [comment]
Comments addressed.

---

Review status: 4 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[geometry/geometry_system.cc, line 237 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27IZYGRKlprjd74V3M:-L2LW7PobbcQJ7zevBba:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/geometry_system.cc#L237)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this seems an odd use of the supplied Context and I don't really get it. I did read the QueryObject documentation and I still don't get it. Checking that the context is the right type seems like an unrelated error check -- why does that have to be done while making a default QueryObject? Can you separate these two operations?
</blockquote></details>

Done

---

*[geometry/geometry_system.cc, line 245 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27JLGd_knvzhruXStv:-L2LY6u4PAAA5adDKaP0:b-kibrxi) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/geometry_system.cc#L245)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per styleguide this should be a `const Context<T>*` since the object retains a copy of the pointer.
</blockquote></details>

As per f2f - this function is the callback for output port calculation; it must be a const reference. Furthermore, the "persistence" of the context should be transient at best. I'll put in a note explaining the reason for this exception to the guide.

---

*[geometry/geometry_system.cc, line 249 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27JD4jfjafDZ2zXswS:-L2LW9R55obexF3VOZN8:b-13pula) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/geometry_system.cc#L249)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW here it makes sense since the object hangs on to the context.
</blockquote></details>

OK I removed the other; you're right, it was redundant and unnecessary and the important work is done here. One of those relics from the old code that survived.

---

*[geometry/geometry_system.h, line 436 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27GGXrF08bWnmraz8J:-L2LYPfZ0TDm3yWZ5Z9v:b-vbvcbs) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/geometry_system.h#L436)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider a comment about what this does with the context.
</blockquote></details>

OK I believe by removing the test, this is no longer necessary.

---

*[geometry/query_object.h, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27Hkd7PUnbn5ZwFokK:-L2LYSslnyBApuD7C0gi:bllrgrm) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/query_object.h#L112)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per f2f -- these could be replaced by a single `SystemIndex` giving the GeometrySystem index in the parent diagram which is shared by both the Source system and GeometrySystem. That is enough to obtain these two pointers from the parent system and parent context. No defect here but in case the presence of these pointers causes problems, you could get rid of them.
</blockquote></details>

I'll put a big TODO in this file capturing this idea.

---

*[geometry/test/geometry_system_test.cc, line 539 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27EYCBDfKFoortVDgZ:-L2LVQ14VTO8D6J3_toy:b-w85x6n) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/test/geometry_system_test.cc#L539)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this unused? Maybe defer until a later PR.
</blockquote></details>

Done Simply a mistake - something that should've been deleted in the first place.

---

*[geometry/test/query_object_test.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L27F93QQfZJ37kGGFDT:-L2LVbMYP2MQUZn9ClLn:ba5sle2) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1d94e510e522b2796c36b125a411340688ae36/geometry/test/query_object_test.cc#L15)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider templatizing class on T so you don't have to templatize the individual methods.
</blockquote></details>

By doing it *this* way, I get invocations like `QOT::expect_default(thing);` which will work for whatever template type `thing` is. It makes my utility function a bit more agnostic without bleeding templates everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-:-L2LYVmPHvWnD9s-GD8v:bel95ya)*

**Comment by avalenzu** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662)*

**Comment by amcastro-tri** [comment]
Reviewed 2 of 8 files at r1, 2 of 6 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[geometry/query_object.cc, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L2MXf4GrCVPojebR0UM:-L2MXf4GrCVPojebR0UN:bd9xn9r) ([raw file](https://github.com/robotlocomotion/drake/blob/f9975bc77bbc7a4ee1409cb003e25c3aaa728377/geometry/query_object.cc#L37)):*
> ```cpp
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS(
> ```

BTW, I am fuzzy after my vacations but, haven't you made already GS compatible with symbolics? (i.e can you use `DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS` instead?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[geometry/query_object.cc, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-L2MXf4GrCVPojebR0UM:-L2MaxVF-OjsGJcK39Kh:b-cye21q) ([raw file](https://github.com/robotlocomotion/drake/blob/f9975bc77bbc7a4ee1409cb003e25c3aaa728377/geometry/query_object.cc#L37)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, I am fuzzy after my vacations but, haven't you made already GS compatible with symbolics? (i.e can you use `DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS` instead?)
</blockquote></details>

`GeometrySystem` is *not* symbolics compatible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662)*

**Comment by sherm1** [comment]
Still :lgtm:

---

Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7662#-:-L2OMbQuihtzHMnmu4E_:b-2pygyf)*

**Pull request merged**
