### PR TITLE
Add a BUILD file for drake/multibody/multibody_tree/math.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jwnimmer-tri for all review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5387)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/multibody_tree/math/BUILD, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5387#-KeGKQgGc0T8_1fIUXSn:-KeGKQgGc0T8_1fIUXSo:b-kzm3q0) ([raw file](https://github.com/robotlocomotion/drake/blob/fa1c6bc5e085fdfcd3a55c6a587b0fcec3cdd78e/drake/multibody/multibody_tree/math/BUILD#L24)):*
> ```Python
> 
> drake_cc_googletest(
>     name = "spatial_algebra_test",
> ```

Both CMake and the filename think that "tests" should be plural in the name.  Sure, its silly, but why go against the author's decision?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5387#-:-KeGKfZNSjh_O956Ar5X:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/multibody/multibody_tree/math/BUILD, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5387#-KeGKQgGc0T8_1fIUXSn:-KeGNgJCzMlbny2u-tC8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa1c6bc5e085fdfcd3a55c6a587b0fcec3cdd78e/drake/multibody/multibody_tree/math/BUILD#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Both CMake and the filename think that "tests" should be plural in the name.  Sure, its silly, but why go against the author's decision?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5387)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/multibody/multibody_tree/math/BUILD, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5387#-KeGO6YGl4E8FpXOZXg2:-KeGO6YHO3T3KlhfjHkV:bc2gmh) ([raw file](https://github.com/robotlocomotion/drake/blob/c29c894a1dd6ad9cac41952b4714fad5f60a086f/drake/multibody/multibody_tree/math/BUILD#L25)):*
> ```Python
> drake_cc_googletest(
>     name = "spatial_algebra_tests",
>     srcs = ["test/spatial_algebra_tests.cc"],
> ```

BTW This is the default now, so doesn't need to be listed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5387)*

**Comment by jwnimmer-tri** [comment]
Merging anyway, we can tidy-forward the next time we add BUILD files for new multibody work.

**Pull request merged**
