### PR TITLE
[tutorials] Make Hydroelastic Contact use images from User Guide

### LINKED ISSUE #19641: Hydroelastic Contact: Basics images missing on Deepnote
### What happened?

Open our online hosted tutorials to the [Hydroelastic Contact: Basics](https://deepnote.com/workspace/Drake-0b3b2c53-a7ad-441b-80f8-bf8350752305/project/Tutorials-2b4fc509-aef2-417d-a40d-6071dfed9199/notebook/hydroelastic_contact_basics-1d03814005274062aad03a875aa5bd86) page.

There are two problems:

(1) Hard linebreaks.  Apparently Jupyter locally and Deepnote use different markdown conventions.  The hard linebreaks in the source Markdown are showing up in Deepnote and disrupting the flow.  In local Jupyter preview, all is fine.

(2) Missing images.  Apparently, Deepnote cannot handle image attachments.

### Version

1.18.0

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

dockerhub

### Relevant log output

Here's a screenshot:

---

image

### PR DESCRIPTION
**Pull request by DamrongGuoy**
- Remove attached images because Deepnote does not support attachments.
- Also fix section markers "###".

Fix #19641

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19660)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19660)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19660#-NYZ9qR5D-2snEjca1fK:-NYZ9qR6DtGfPUx24FUC:b-d3wind) (no related file):*
Remind myself to change all the image URL from DamrongGuoy/drake/blob/copy_images_from_HydroTutorial_to_UserGuide to RobotLocomotion/drake/blob/master when #19652 lands.

___

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19660)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tutorials/hydroelastic_contact_basics.ipynb` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19660#-NYZATnf1t_eoM9vPRQu:-NYZATnf1t_eoM9vPRQv:bdp7vs3) ([raw file](https://github.com/RobotLocomotion/drake/blob/d696bac5ff1c5ac400cb8f2bfd6482995651375b/tutorials/hydroelastic_contact_basics.ipynb#L29)):*
> ```
>     "\n",
>     "\n",
>     "\n",
> ```

Remove this when #19652 lands.



_Code quote:_
```
    "<!-- Developer note: **Change all the image URL from DamrongGuoy/drake/blob/copy_images_from_HydroTutorial_to_UserGuide to RobotLocomotion/drake/blob/master when [19652](https://github.com/RobotLocomotion/drake/pull/19652) landed.** -->\n",
    "\n",
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19660)* status: needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19660#-NYZ9qR5D-2snEjca1fK:-NYzFgYO2U2T4D5b-h14:b-uano0v) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Remind myself to change all the image URL from DamrongGuoy/drake/blob/copy_images_from_HydroTutorial_to_UserGuide to RobotLocomotion/drake/blob/master when #19652 lands.
</blockquote></details>

Done.  Now it uses images in https://drake.mit.edu/doxygen_cxx/*

___
___
*[`tutorials/hydroelastic_contact_basics.ipynb` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19660#-NYZATnf1t_eoM9vPRQu:-NYzGDKj5J6vrW4Twxci:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d696bac5ff1c5ac400cb8f2bfd6482995651375b/tutorials/hydroelastic_contact_basics.ipynb#L29)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Remove this when #19652 lands.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19660#-:-NYzHBf09shMiSH-0zV3:b-qf68jg)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19660#-:-NZ1bdJv1QnNxli3C7T0:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`tutorials/hydroelastic_contact_basics.ipynb` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19660#-NZ1akPGDTDYMSwwH_4O:-NZ1akPH2e-AtxVyjhvz:bhqgl7a) ([raw file](https://github.com/RobotLocomotion/drake/blob/1caff0b3f3e83d4fb25cbb9ad37ff290c04eb99a/tutorials/hydroelastic_contact_basics.ipynb#L23)):*
> ```
>   },
>   {
>    "cell_type": "markdown",
> ```

nit Now that we don't have attachments, splitting up the introduction into multiple cells is no longer necessary. The extra cell breaks don't look good on Deepnote.  Please condense all of the markdown here into one cell.

Ditto for the "Contact surface" section.

**Review by DamrongGuoy — COMMENTED** [review]
+@EricCousineau-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19660#-:-NZ1r7HS02y5WBROfyy8:b-r34yat)* status: LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`tutorials/hydroelastic_contact_basics.ipynb` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19660#-NZ1akPGDTDYMSwwH_4O:-NZ1q_eD-LYGmjoGPJiw:b-2be3k1) ([raw file](https://github.com/RobotLocomotion/drake/blob/1caff0b3f3e83d4fb25cbb9ad37ff290c04eb99a/tutorials/hydroelastic_contact_basics.ipynb#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Now that we don't have attachments, splitting up the introduction into multiple cells is no longer necessary. The extra cell breaks don't look good on Deepnote.  Please condense all of the markdown here into one cell.

Ditto for the "Contact surface" section.
</blockquote></details>

Done.  Thanks. Good point.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19660)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Pull request merged**
