### PR TITLE
solvers: Amend SolverInterface for more detailed error messages

### LINKED ISSUE #15019: solvers: OSQP requires a Quadratic Cost, but doesn't tell the user that.
A student was getting the message:
```
ValueError: The capabilities of drake::solvers::OsqpSolver do not meet the requirements of the MathematicalProgram ({ProgramAttributes: LinearConstraint, LinearEqualityConstraint})
```
for a very simple problem, which had only linear constraints and linear equality constraints.  Looking at the code, I found a hidden:
```
prog.required_capabilities().count(ProgramAttribute::kQuadraticCost) > 0;
```
I believe that they needed to add a Quadratic Cost to satisfy the requirements.  Can we make a better error message?

(I can try to come up with a repro after office hours).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is breaking change; any direct subclasses of SolverInterface need to implement the new ExplainUnsatisfiedProgramAttributes method.

Suggested order for code review:
- osqp_solver_test
- osqp_solver
- linear_system_solver_test
- linear_system_solver
- solver_interface
- solver_base and its unit test
- program_attribute and its unit test
- pydrake changes

Resolves #15019.  Closes #15020.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15028)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.

**Review by hongkai-dai — COMMENTED** [review]
:LGTM: +@rpoyner-tri for platform review please, thanks!

> Reviewed 1 of 15 files at r1, 10 of 14 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15028#-:-M_wg4bLEeZHp4clIr7Z:b-fcblgr)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[solvers/linear_system_solver.cc, line 113 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15028#-M_weYvz0uUSr74xE4uE:-M_weYvz0uUSr74xE4uF:b-g21ba) ([raw file](https://github.com/robotlocomotion/drake/blob/202ee5317a99e0e437f0f79a57261b4955b10634/solvers/linear_system_solver.cc#L113)):*
> ```cpp
>     return false;
>   }
>   return true;
> ```

The explanation is not cleared when returning true, but the documentation says it will clear the explanation.
___
*[solvers/test/program_attribute_test.cc, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15028#-M_wfy8q9WBGYPqMGPw6:-M_wfy8q9WBGYPqMGPw7:b5dqa2i) ([raw file](https://github.com/robotlocomotion/drake/blob/202ee5317a99e0e437f0f79a57261b4955b10634/solvers/test/program_attribute_test.cc#L53)):*
> ```cpp
>   // - expected unsupported message (if any).
>   using namespace std::literals;  // NOLINT(build/namespaces)
>   std::vector<std::tuple<ProgramAttributes, ProgramAttributes, const char*>>
> ```

Just curious why we use const char* instead of std::string

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15028)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @hongkai-dai and @rpoyner-tri)

___
*[solvers/linear_system_solver.cc, line 113 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15028#-M_weYvz0uUSr74xE4uE:-M_wi02xAPup3Fan9OJj:b-hhrm0k) ([raw file](https://github.com/robotlocomotion/drake/blob/202ee5317a99e0e437f0f79a57261b4955b10634/solvers/linear_system_solver.cc#L113)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The explanation is not cleared when returning true, but the documentation says it will clear the explanation.
</blockquote></details>

Oops.  It turns out it doesn't matter anyway (the input argument is always empty already), but I added the clear as well as more focused unit tests to confirm the user-expected behavior.
___
*[solvers/test/program_attribute_test.cc, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15028#-M_wfy8q9WBGYPqMGPw6:-M_wh5rn5NipbpqPJX3e:b-2x21wd) ([raw file](https://github.com/robotlocomotion/drake/blob/202ee5317a99e0e437f0f79a57261b4955b10634/solvers/test/program_attribute_test.cc#L53)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just curious why we use const char* instead of std::string
</blockquote></details>

Oops... it's vestigial from when I was trying to find ways to express the test cases without bloating the code.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15028)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 15 files at r1, 9 of 14 files at r2, 3 of 5 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15028#-:-Ma-PoPu5HhVaeHcKRQ_:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),hongkai-dai (waiting on @jwnimmer-tri)

**Pull request merged**
