### PR TITLE
Bind Hyperrectangle::MaybeCalcAxisAlignedBoundingBox

### PR DESCRIPTION
**Pull request by cohnt**
Very small PR to create a python binding for the static method `Hyperrectangle::MaybeCalcAxisAlignedBoundingBox`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20804)

### CODE REVIEW

**Comment by cohnt** [comment]
+@sadraddini for feature review

**Comment by cohnt** [comment]
-@sadraddini
+@alexandreAmice

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: minus the nit. +@ggould-tri for platform review per schedule. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20804#-:-NorbuOp9a3CbsCZUkLw:bdbg960)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @cohnt)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; I concur as to the nit.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20804#-:-NordXehAkCpbdZJJChv:bgsq15c)* status: 1 unresolved discussion

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20804)* status: 1 unresolved discussion

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 384 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20804#-Norbi7-DQSIp2sMlBUa:-Norv6WQEECRJy_SgVDe:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d315e85f60c7c0831fdbbe8152bf7e398af1c74/bindings/pydrake/geometry/test/optimization_test.py#L384)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can you call a method on `bbox` here to ensure that the type of `bbox` is `Hyperrectangle` as expected? Maybe just a call to one of its members.
</blockquote></details>

Done

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20804)* status: 1 unresolved discussion

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20804)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice

**Pull request merged**
