### PR TITLE
MosekSolver accepts option write to write the model file.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15568)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@avalenzu for feature review please, thanks (since you reviewed the Gurobi counterpart in PR https://github.com/RobotLocomotion/drake/pull/15438)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15568#-:-MgImils1D4g0LM67wW5:b-c79o7d)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
:lgtm: +@jwnimmer-tri for platform review.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15568#-:-MgLl5sG-pCqePPmo_ZO:b-xrxq0n)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15568#-:-MgLuzOiDQg1Drbf4ILM:bcpz082)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[solvers/mosek_solver.h, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15568#-MgLu9wG41DoldwJBzOu:-MgLu9wH0qQpOb9qnSuo:b-lppyzz) ([raw file](https://github.com/robotlocomotion/drake/blob/db5723a28510e90991adf328dac63692aec3323e/solvers/mosek_solver.h#L60)):*
> ```objc
>  * https://docs.mosek.com/9.2/capi/param-groups.html#doc-param-groups for C API
>  * and https://docs.mosek.com/9.2/pythonapi/param-groups.html#doc-param-groups
>  * for python API. On top of these parameters, we also provide the following
> ```

I'm not yet following why we are giving users the Python API link, with its flavor of spellings.  I think neither Drake nor pydrake accepts those spellings?
___
*[solvers/mosek_solver.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15568#-MgLuXmW-JUiZPFV7g5o:-MgLuXmW-JUiZPFV7g5p:b-6nv266) ([raw file](https://github.com/robotlocomotion/drake/blob/db5723a28510e90991adf328dac63692aec3323e/solvers/mosek_solver.h#L62)):*
> ```objc
>  * for python API. On top of these parameters, we also provide the following
>  * additional parameters
>  * 1. "write", set to a file name so that Mosek solver will write the
> ```

The mosek function is named "writedata".  It seems to me like matching that name here would both be more consistent with upstream, and also help clarify that we're writing the _model_, not a trace of the attempt to solve (as with "print file").  WDYT?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15568)* status: 2 unresolved discussions (waiting on @avalenzu and @jwnimmer-tri)

___
*[solvers/mosek_solver.h, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15568#-MgLu9wG41DoldwJBzOu:-MgMQDAV9eONqQlA5lRh:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/db5723a28510e90991adf328dac63692aec3323e/solvers/mosek_solver.h#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not yet following why we are giving users the Python API link, with its flavor of spellings.  I think neither Drake nor pydrake accepts those spellings?
</blockquote></details>

Done. Good call.
___
*[solvers/mosek_solver.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15568#-MgLuXmW-JUiZPFV7g5o:-MgMSVT02Wgfcoj1hi1M:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/db5723a28510e90991adf328dac63692aec3323e/solvers/mosek_solver.h#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The mosek function is named "writedata".  It seems to me like matching that name here would both be more consistent with upstream, and also help clarify that we're writing the _model_, not a trace of the attempt to solve (as with "print file").  WDYT?
</blockquote></details>

Done. Good call.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15568)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),avalenzu (waiting on @hongkai-dai)

**Pull request merged**
