### PR TITLE
Abstract value reference wrapper unit test

### PR DESCRIPTION
**Pull request by amcastro-tri**
Fun and games with `AbstractValue` and `std::reference_wrapper`. Exploring what kind of things we can store in the context (and possibly cache entries) I was curios about storing some sort of reference object. Thus I ended up writing this sort of pedagogical tiny unit test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7951)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@jwnimmer-tri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7951#-:-L4XBDrb1asgXnYKikHY:bs3tquo)*

**Comment by jwnimmer-tri** [comment]
This seems extraordinarily dangerous.  `systems::Value`s have value semantics, not reference semantics.  Lifetime management would be a huge concern.  I'll need to understand the application use case for this before we proceed.

**Comment by amcastro-tri** [comment]
Right. Difficult to explain by text on github. I'll share with you what application I have in mind tomorrow during our lunch break.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7951#-:-L4XrO5dQFqxgR5CqTEv:b-hd69kq)*

**Comment by amcastro-tri** [comment]
`AbstractValue` and `Value` must have a copy semantics. By wrapping a `std::reference_wrapper` with an `AbstractValue` we'd essentially be able to place a pointer inside a `Context` and for instance cloning a context would make those reference point into the old context.
Thanks @jwnimmer-tri for the helpful discussion on this topic, it made a lot of the value semantics concepts way clearer for me now.

**Pull request closed without merging**
