### PR TITLE
Disable System<T>::DoCalcNextUpdateTime if T is non-numeric type

### LINKED ISSUE #4132: Instantiating Diagram with symbolic::Expression generates build errors
Originally reported by @jadecastro.

Adding `template class SingleLaneEgoAndAgent<symbolic::Expression>;` to `drake/automotive/single_lane_ego_and_agent.cc` generates the following errors:

```
/Users/soonhok/work/drake-distro/drake/../drake/systems/framework/diagram.h:462:11: error: value of type 'drake::symbolic::Formula' is not contextually convertible to 'bool'
      if (time < actions->time) {
          ^~~~~~~~~~~~~~~~~~~~
/Users/soonhok/work/drake-distro/drake/automotive/single_lane_ego_and_agent.cc:70:16: note: in instantiation of member function 'drake::systems::Diagram<drake::symbolic::Expression>::DoCalcNextUpdateTime' requested here
template class SingleLaneEgoAndAgent<symbolic::Expression>;
               ^
In file included from /Users/soonhok/work/drake-distro/drake/automotive/single_lane_ego_and_agent.cc:1:
In file included from /Users/soonhok/work/drake-distro/drake/../drake/automotive/single_lane_ego_and_agent.h:8:
/Users/soonhok/work/drake-distro/drake/../drake/systems/framework/diagram.h:468:9: error: value of type 'drake::symbolic::Formula' is not contextually convertible to 'bool'
    if (actions->time == std::numeric_limits<T>::infinity()) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/soonhok/work/drake-distro/drake/../drake/systems/framework/diagram.h:476:11: error: value of type 'drake::symbolic::Formula' is not contextually convertible to 'bool'
      if (sub_actions[i].time > actions->time) continue;
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
```

Just did f2f with @david-german-tri and @jadecastro: Basically we need a patch similar to the one that we applied to `LeafSystem`.

### PR DESCRIPTION
**Pull request by soonho-tri**
close #4132

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4134)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm: assuming you've confirmed this fixes the problem

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4134#-:-KWZ5Nt2c2ZrbzIYS_PT:b-27ivjh)*

**Comment by soonho-tri** [comment]
+@david-german-tri , both reviews please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4134#-:-KWZ5N1iKPKm8CCKBIIr:b-1p43ur)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
