### PR TITLE
use DRAKE_ASSERT_IS_ARMED

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fixes the CI failure

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4679)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for both review. 
@drake-jenkins-bot mac-clang-continuous-release please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4679#-:-K_fRQjPiKRIWQbpFgtQ:b25toi)*

**Comment by hongkai-dai** [comment]
-@jwnimmer-tri +@ggould-tri for both review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4679#-:-K_fSFwV1ad-voEz9Q8S:b31r2si)*

**Comment by ggould-tri** [comment]
:lgtm: pending mac build pass.

This is a high-priority build-breaker so I won't defect this, but please return to this later with explanatory comments or a rework using `__attribute` so as to not confuse or mislead future readers.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4679#-:-K_fS8_-yHj8PqYHIblH:b617qk9)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-continuous-release please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4679#-:-K_fVff4qaYFebDoXFN7:be7gmn0)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot test mac-clang-continuous-release please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4679#-:-K_fWNafAQNr6A0Ix_1a:b-90ita4)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-continuous-release please

**Comment by mwoehlke-kitware** [comment]
(Sorry, github is being slow showing comments!)

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-experimental please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4679#-:-K_fcH8QnzF-LFt_pxxt:b-ixvtlv)*

**Pull request merged**
