### PR TITLE
[tools] Disable implicit __init__.py creation

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21333)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI I can confirm that it's grammatical and well punctuated. For confirming this addresses the flakes, do we just pull the cord?

Googling the flag leads down a weird rabbit hole of bazel development where public issues and PRs get merged (quietly) to internal code., but I'm good with letting this go as is.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21333#-:-NvqrImAE3VlI2rUg3Ka:bpdhzt9)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21333#-:-NvqtaTn7NPvntS8-zk9:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
Of note, I _think_ every flake in the past 24h has been for one of these ghost files (a file not in git).  This disables those files, so has a fair chance of helping.  I already turned this on in Anzu to solve the same kinds of flakes there.  In Drake the #21126 was _supposed_ to have already solved this (opting out on a case-by-case basis) but I guess it's not quite thorough enough.

**Comment by SeanCurtis-TRI** [comment]
In fact, one of the most commonly appearing complaints is about `binding/pydrake/__init__.py` which definitely is in git.

**Comment by SeanCurtis-TRI** [comment]
For a couple of quick examples of a missing `__init__.py` file that is definitely in the repo:

https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-jammy-clang-bazel-nightly-everything-debug/58/consoleFull
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-jammy-clang-bazel-nightly-mosek-release/58/consoleFull

**Comment by jwnimmer-tri** [comment]
My hypothesis is that in the cases of those failures, the real file was not part of runfiles (because it's not being linted), so the file being complained about would be a ghost one.

In any case, this is a flag we've wanted to have turned on for a while now, so I'm thinking we try it in CI to see if it fixes the flakes and if not we can still revert the Bazel 7.1.1 upgrade, but keep this PR intact (no need to revert this one).

**Comment by SeanCurtis-TRI** [comment]
Sounds reasonable.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Are we waiting on anything in particular to merge this?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21333#-:-Nvr7V_95xaIJ4CYNZmc:b-2wj6qz)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
Nope, just the last build to go green.

**Pull request merged**
