### PR TITLE
Add an infrastructure for Drake lint checks.

### LINKED ISSUE #3150: automation to prevent regressions of DOS-style line endings
A loose end from #3029: add/verify automation to guard against regression of DOS-style line endings.

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #3150.

@rpoyner-tri for feature review, @jwnimmer-tri for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4785)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Bazel CI passing; ready for review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-:-KagxqlyQ9mWV-wtp1Pn:b-1z9p7h)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/drakelint.py, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-KagxzPkAV1AUL0ThX3X:-KagxzPlsXkDCmRdUVaF:b-olqi5d) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L2)):*
> ```Python
> import sys
> ```

pep8 expects 2 blank lines here.

---

*[tools/drakelint.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah195H0udCldt3Gs5_:-Kah195I2qj2KyAG7odd:b-xpr6ms) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L3)):*
> ```Python
> import sys
> 
> # Returns 0 if all of the @p newlines are Unix, and 1 otherwise.
> ```

This comment would be more idiomatic in the docstring style.  See PEP 257.

---

*[tools/drakelint.py, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah0RIrx6hosvL8j8EF:-Kah0RIrx6hosvL8j8EG:betwjrn) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L5)):*
> ```Python
> # Returns 0 if all of the @p newlines are Unix, and 1 otherwise.
> def _check_invalid_line_endings(newlines):
>     for newline in newlines:
> ```

Careful here. `newlines` is documented as possibly being `None`, a bare string (say '\r\n`), or a tuple of strings. I *think* you still end up getting the result you want, but it appears to be by luck rather than strategy.

---

*[tools/drakelint.py, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kagy14JYNQJpJoEHNyn:-Kagy14JYNQJpJoEHNyo:b-olqi5d) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L10)):*
> ```Python
>             return 1
>     return 0
> ```

pep8 expects 2 blank lines here.

---

*[tools/drakelint.py, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah1HL6f_ODztWGAP17:-Kah1HL7h1i0iUoEpfks:b-xpr6ms) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L13)):*
> ```Python
> # Runs Drake lint checks on each path specified as a command-line argument.
> # Exits 1 if any of the paths are invalid or any lint checks fail.
> # Otherwise exits 0.    
> ```

This comment would be more idiomatic in the docstring style.  See PEP 257.

---

*[tools/drakelint.py, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kagxm5yNoBzhzmf52i1:-Kagxm5yNoBzhzmf52i2:bfffix7) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L23)):*
> ```Python
>             print("Unable to open " + filename)
>             sys.exit(1)
>             
> ```

trailing whitespace, here and several lines below.

---

*[tools/drakelint.py, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kagy3ntBtzLZJcS8CZ6:-Kagy3ntBtzLZJcS8CZ7:bav47lz) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L25)):*
> ```Python
>             
>         # Read its data.
>         data = file.read()
> ```

`data` is unused.

---

*[tools/drakelint.py, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah-fpWPX50FYoXdXfB:-Kah-fpXB3wujZdDFH42:b69uwoi) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L36)):*
> ```Python
>         
>         # Wrap up.
>         file.close()
> ```

BTW, consider using `with` (context manager pattern) to close files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4785)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/drakelint.py, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-KagxzPkAV1AUL0ThX3X:-Kah6-9nm4jZj1q87qCq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L2)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

pep8 expects 2 blank lines here.
</blockquote></details>

Done.

---

*[tools/drakelint.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah195H0udCldt3Gs5_:-Kah6-VkXcZgTRvDo7NQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L3)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This comment would be more idiomatic in the docstring style.  See PEP 257.
</blockquote></details>

Done.

---

*[tools/drakelint.py, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah0RIrx6hosvL8j8EF:-KahHh6X39Ik-vQfn4-8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L5)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Careful here. `newlines` is documented as possibly being `None`, a bare string (say '\r\n`), or a tuple of strings. I *think* you still end up getting the result you want, but it appears to be by luck rather than strategy.
</blockquote></details>

Done.

---

*[tools/drakelint.py, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kagy14JYNQJpJoEHNyn:-Kah64azOzVziFpfPfqo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L10)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

pep8 expects 2 blank lines here.
</blockquote></details>

Done.

---

*[tools/drakelint.py, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah1HL6f_ODztWGAP17:-Kah65QWYPks1j43zT2P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L13)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This comment would be more idiomatic in the docstring style.  See PEP 257.
</blockquote></details>

Done.

---

*[tools/drakelint.py, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kagxm5yNoBzhzmf52i1:-Kah6ZpdL_DJQDSBretg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L23)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

trailing whitespace, here and several lines below.
</blockquote></details>

Done.

---

*[tools/drakelint.py, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kagy3ntBtzLZJcS8CZ6:-Kah6PbD9vv5N90JDY3a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L25)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

`data` is unused.
</blockquote></details>

Done.

---

*[tools/drakelint.py, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah-fpWPX50FYoXdXfB:-Kah6PAItGka5Ha7Cg9y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L36)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, consider using `with` (context manager pattern) to close files.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4785)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/drakelint.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah195H0udCldt3Gs5_:-KahUcIlFurQkAF4KQ7h:b9uob0c) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L3)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doc strings go inside the definition, at the same indent as the implementation. PEP 257 recommends prescriptive phrasing ("Return") rather than descriptive ("Returns").

---

*[tools/drakelint.py, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah1HL6f_ODztWGAP17:-KahVQ1D1Nv24ZUnsGN7:b-2g0kai) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L13)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As above: belongs inside main(), prefer prescriptive phrasing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4785)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/drakelint.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah195H0udCldt3Gs5_:-KahYea2109fwDVh1pwI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L3)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Doc strings go inside the definition, at the same indent as the implementation. PEP 257 recommends prescriptive phrasing ("Return") rather than descriptive ("Returns").
</blockquote></details>

Done.

---

*[tools/drakelint.py, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-Kah1HL6f_ODztWGAP17:-KahYf6GTZZu4D_k4oRU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f6aa03a13706c398998273663d5df6f3ca54d0/tools/drakelint.py#L13)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

As above: belongs inside main(), prefer prescriptive phrasing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4785)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-:-KahZ89Rkr6sIxrrHxgI:bnfp4nl)*

**Comment by david-german-tri** [comment]
-@jwnimmer-tri +@sammy-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-:-KahZWlVS1N6PG7ww9U7:bckow25)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-:-Kai4azK9k061lKCL40H:bnfp4nl)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-clang-experimental please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4785#-:-Kan0S8GgH-zM9qxHm67:bl7nx6w)*

**Pull request merged**
