### PR TITLE
[setup] Upgrade Bazel to latest release 8.0.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22285)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-coverage please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-coverage please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-noble-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-noble-clang-bazel-experimental-release please
@drake-jenkins-bot linux-noble-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-noble-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-noble-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-sonoma-clang-cmake-experimental-everything-release please
@drake-jenkins-bot mac-arm-sonoma-clang-cmake-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22285)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22285#-ODhEKEEDsjBHjP0MzR1:-ODhEKEEDsjBHjP0MzR2:bkfpbu5) (no related file):*
Working

Test coverage reports locally.

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22285#-:-ODlQ5Lj8r5N5Ln-5ovN:b-pvz8jw)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22285#-ODhEKEEDsjBHjP0MzR1:-ODlPsIL7Xil6EbPYqJ7:b3y9q9b) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Test coverage reports locally.
</blockquote></details>

OK worked great.  The output data are unzipped now by default, but it still works.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22285)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22285#-ODhEKEEDsjBHjP0MzR1:-ODlTvM45rViyqwHPBht:bv1zqrp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK worked great.  The output data are unzipped now by default, but it still works.
</blockquote></details>

Oops.  I tried everything except `kcov_tool clean`.  That needs a separate fix:
https://github.com/RobotLocomotion/drake/pull/22291

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22285#-:-ODltqunAf4KPHIDEcX-:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
