### PR TITLE
Drake Automotive: Adds a TrivialRightOfWayStateProvider

### PR DESCRIPTION
**Pull request by liangfok**
This is a trivial manager that simply allows applications to set all `RightOfWayRule` dynamic states.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8642)

### CODE REVIEW

**Comment by liangfok** [comment]
+@maddog-tri for feature review please. Thanks!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-:-LAUfsBGD9hWjvOaq1sM:b-52qvgv)*

**Comment by maddog-tri** [comment]
First pass complete.

---

Reviewed 4 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---

*[automotive/trivial_traffic_light_manager.h, line 28 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUt7EG6zvRs-b-Z5yv:-LAUt7EG6zvRs-b-Z5yw:b-iqmxvd) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.h#L28)):*
> ```objc
>   void AddState(const maliput::api::rules::RightOfWayRule::Id& id,
>                 const maliput::api::rules::RightOfWayRule::DynamicState&
>                     initial_state);
> ```

BTW:  indent looks weird.

---

*[automotive/trivial_traffic_light_manager.h, line 41 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUnMWZBpCL2hLIcikx:-LAUnMWZBpCL2hLIciky:b-9mdw3z) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.h#L41)):*
> ```objc
> 
>   std::map<maliput::api::rules::RightOfWayRule::Id,
>            maliput::api::rules::RightOfWayRule::DynamicState> dynamic_states_;
> ```

Is the order important?  Otherwise, use `unordered_map`.

---

*[automotive/trivial_traffic_light_manager.cc, line 14 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUs3wN3eFDeIlum8a7:-LAUs3wN3eFDeIlum8a8:b-xyc9q2) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.cc#L14)):*
> ```cpp
>     const RightOfWayRule::DynamicState& initial_state) {
>   DRAKE_THROW_UNLESS(dynamic_states_.count(id) == 0);
>   dynamic_states_[id] = initial_state;
> ```

FYI, an alternate way to do this that involves only one map lookup and less copying:
```
  auto result = dynamic_states_.emplace(id, initial_state);
  DRAKE_THROW_UNLESS(result.second);
```

I love `emplace()`....

---

*[automotive/trivial_traffic_light_manager.cc, line 19 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUnZT0EF0_X5kZaVZo:-LAUnZT0EF0_X5kZaVZp:b-dosbvn) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.cc#L19)):*
> ```cpp
> /// Sets the dynamic state of a RightOfWayRule within this manager.
> ///
> /// Throws an exception if no dynamic state with @p id exists in this manager.
> ```

Duplicate docstring, and doesn't belong in .cc file anyway.

---

*[automotive/trivial_traffic_light_manager.cc, line 30 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUouZYEwom_qV4novk:-LAUouZYEwom_qV4novl:b-8hea20) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.cc#L30)):*
> ```cpp
>     const RightOfWayRule::Id& id) const {
>   DRAKE_THROW_UNLESS(dynamic_states_.count(id) == 1);
>   return dynamic_states_.at(id);
> ```

Hmm... I see now that I left a hole in the contract and the testing of `RightOfWayStateProvider`:  the type of exception thrown is not specified.

I was originally going to write "The DRAKE_THROW_UNLESS is redundant, because dynamic_states_.at(id) will throw if the id is not already present."  `at()` will throw a `std::out_of_range` exception, and elsewhere in the RoadRulebook API I have specified that lookup-by-id methods throw that exception, to be consistent with the behavior of STL lookup failures.

I recommend doing that here and in `SetState()` above, i.e., just use `at()` (for both reading and writing).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-:-LAUtgYT489wop_gBJfg:bvb1a6z)*

**Comment by liangfok** [comment]
Comments addressed.

---

Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[automotive/trivial_traffic_light_manager.h, line 28 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUt7EG6zvRs-b-Z5yv:-LAVFbML7KbqPD8omynS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.h#L28)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

BTW:  indent looks weird.
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.h, line 41 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUnMWZBpCL2hLIcikx:-LAVFotXCMXjm05ujG3o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.h#L41)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Is the order important?  Otherwise, use `unordered_map`.
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.cc, line 14 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUs3wN3eFDeIlum8a7:-LAVGJo3CyGBtc45Yqbm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.cc#L14)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

FYI, an alternate way to do this that involves only one map lookup and less copying:
```
  auto result = dynamic_states_.emplace(id, initial_state);
  DRAKE_THROW_UNLESS(result.second);
```

I love `emplace()`....
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.cc, line 19 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUnZT0EF0_X5kZaVZo:-LAVGNKP3vfPYRXK7UoF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.cc#L19)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Duplicate docstring, and doesn't belong in .cc file anyway.
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.cc, line 30 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUouZYEwom_qV4novk:-LAVHTM73x8zY3_5Ncn4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.cc#L30)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Hmm... I see now that I left a hole in the contract and the testing of `RightOfWayStateProvider`:  the type of exception thrown is not specified.

I was originally going to write "The DRAKE_THROW_UNLESS is redundant, because dynamic_states_.at(id) will throw if the id is not already present."  `at()` will throw a `std::out_of_range` exception, and elsewhere in the RoadRulebook API I have specified that lookup-by-id methods throw that exception, to be consistent with the behavior of STL lookup failures.

I recommend doing that here and in `SetState()` above, i.e., just use `at()` (for both reading and writing).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-:-LAVHRdg2KKlfwfoXq2_:bel95ya)*

**Comment by maddog-tri** [comment]
:lgtm:, modulo a couple of documentation nits.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/trivial_traffic_light_manager.h, line 28 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUt7EG6zvRs-b-Z5yv:-LAVipIS014xFQtkyKwA:b83d59) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.h#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW: I guess I should have said "even though correct".  The jarring part is having the param name separated from the type, which I think could be avoided if there were a linefeed after the `AddState(` and both params ended up closer to the left margin.

---

*[automotive/trivial_traffic_light_manager.h, line 24 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAVjamo7hVO5R8SFEl8:-LAVjamo7hVO5R8SFEl9:b6pyivo) ([raw file](https://github.com/robotlocomotion/drake/blob/2f1ef9e5d072b70fc277fd8665eba1cee89c9569/automotive/trivial_traffic_light_manager.h#L24)):*
> ```objc
>   /// Adds a dynamic state to this manager.
>   ///
>   /// Throws an exception if a RightOfWayRule with an ID of @p id already exists
> ```

"an exception" --> "std::runtime_exception"

---

*[automotive/trivial_traffic_light_manager.h, line 32 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAVjp16Bg5xaP5whqnm:-LAVjp16Bg5xaP5whqnn:bohl46a) ([raw file](https://github.com/robotlocomotion/drake/blob/2f1ef9e5d072b70fc277fd8665eba1cee89c9569/automotive/trivial_traffic_light_manager.h#L32)):*
> ```objc
>   /// Sets the dynamic state of a RightOfWayRule within this manager.
>   ///
>   /// Throws an exception if no dynamic state with @p id exists in this manager.
> ```

"an exception" --> "std::out_of_range"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-:-LAVkR2EAbMZ7Wu4uEC3:b2e34qp)*

**Comment by liangfok** [comment]
+@sherm1 for Friday platform review please. Thanks!

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/trivial_traffic_light_manager.h, line 28 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAUt7EG6zvRs-b-Z5yv:-LAVmL1DCzDxhMbMc2s3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b65a74d6d03093c967f1a6c97ce1d3fc5b6a6b35/automotive/trivial_traffic_light_manager.h#L28)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

BTW: I guess I should have said "even though correct".  The jarring part is having the param name separated from the type, which I think could be avoided if there were a linefeed after the `AddState(` and both params ended up closer to the left margin.
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.h, line 24 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAVjamo7hVO5R8SFEl8:-LAVmUa1BpsoB4uS6R70:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f1ef9e5d072b70fc277fd8665eba1cee89c9569/automotive/trivial_traffic_light_manager.h#L24)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

"an exception" --> "std::runtime_exception"
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.h, line 32 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAVjp16Bg5xaP5whqnm:-LAVmZlkDS7IdWdMdR05:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f1ef9e5d072b70fc277fd8665eba1cee89c9569/automotive/trivial_traffic_light_manager.h#L32)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

"an exception" --> "std::out_of_range"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-:-LAVn79U2S_OqpUcTUhK:biy0zh3)*

**Comment by maddog-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642)*

**Comment by sherm1** [comment]
Platform :lgtm: pending a possible rename, PTAL. There are a few FYIs for your consideration.

---

Reviewed 1 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/trivial_traffic_light_manager.h, line 12 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYw6u159TQCyTh_p4V:-LAYw6u159TQCyTh_p4W:b-h2m732) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L12)):*
> ```objc
> 
> /// A trivial implementation of an api::rules::RightOfWayStateProvider.
> class TrivialTrafficLightManager final
> ```

BTW This class appears to be misnamed. I don't see anything in it specific to traffic lights. Should it be something like `TrivialRightOfWayStateProvider` ? If there is something coming to make it specific to traffic lights, please add a TODO explaining that, and add some traffic-light specific documentation.

---

*[automotive/trivial_traffic_light_manager.h, line 25 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYv-oV9eBuo-bSx3Aa:-LAYv-oV9eBuo-bSx3Ab:bilzijf) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L25)):*
> ```objc
>   ///
>   /// Throws std::runtime_exception if a RightOfWayRule with an ID of @p id
>   /// already exists in this manager.
> ```

FYI would likely be more precise to call this an std::logic_error since it is an error in the calling program rather than in the runtime environment.
- logic_error: reports errors that are a consequence of faulty logic within the program such as violating logical preconditions or class invariants and may be preventable.
- runtime_error: reports errors that are due to events beyond the scope of the program and can not be easily predicted.

(From [cppreference here](http://en.cppreference.com/w/cpp/error/exception))

---

*[automotive/trivial_traffic_light_manager.h, line 32 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYxplpC77boF0G5uxH:-LAYxplpC77boF0G5uxI:b-a55jnd) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L32)):*
> ```objc
>   /// Sets the dynamic state of a RightOfWayRule within this manager.
>   ///
>   /// Throws std::out_of_range if no dynamic state with @p id exists in this
> ```

FYI std::out_of_range is an std::logic_error.

---

*[automotive/trivial_traffic_light_manager.h, line 39 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYu_Xl8urbCNNoiM15:-LAYu_Xl8urbCNNoiM16:b-sjlfwx) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L39)):*
> ```objc
>  private:
>   maliput::api::rules::RightOfWayRule::DynamicState DoGetState(
>       const maliput::api::rules::RightOfWayRule::Id& id) const override;
> ```

FYI consider making this `final` rather than `override`. It will be final anyway because the class is final but that's not obvious looking just at the declaration here.

---

*[automotive/trivial_traffic_light_manager.cc, line 13 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYxEF_B6pcgPygJSYw:-LAYxEF_B6pcgPygJSYx:b-vqdadg) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.cc#L13)):*
> ```cpp
>     const RightOfWayRule::Id& id,
>     const RightOfWayRule::DynamicState& initial_state) {
>   DRAKE_THROW_UNLESS(dynamic_states_.count(id) == 0);
> ```

BTW you don't need this check because it duplicates the check of the returned bool from emplace below.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-:-LAYyZ1N-ZRfFiYgSGuX:bhepkiq)*

**Comment by maddog-tri** [comment]
*[automotive/trivial_traffic_light_manager.h, line 25 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYv-oV9eBuo-bSx3Aa:-LAZ-sYK41fxm9Z6b_zj:bu5akoi) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI would likely be more precise to call this an std::logic_error since it is an error in the calling program rather than in the runtime environment.
- logic_error: reports errors that are a consequence of faulty logic within the program such as violating logical preconditions or class invariants and may be preventable.
- runtime_error: reports errors that are due to events beyond the scope of the program and can not be easily predicted.

(From [cppreference here](http://en.cppreference.com/w/cpp/error/exception))
</blockquote></details>

...except that it does, in fact, throw `std::runtime_error`, not `std::logic_error`, because that is what `DRAKE_THROW_UNLESS()` does, for better or worse.

(PS:  Sorry, Liang, I misspelled it as `std::runtime_exception` in my earlier comment.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[automotive/trivial_traffic_light_manager.h, line 25 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYv-oV9eBuo-bSx3Aa:-LAZ1TUw-rwTO4lkmZ-f:bk47isc) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L25)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

...except that it does, in fact, throw `std::runtime_error`, not `std::logic_error`, because that is what `DRAKE_THROW_UNLESS()` does, for better or worse.

(PS:  Sorry, Liang, I misspelled it as `std::runtime_exception` in my earlier comment.)
</blockquote></details>

True! I meant it would be more precise to _throw_ a logic_error. I wasn't proposing to lie about it!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642)*

**Comment by liangfok** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[automotive/trivial_traffic_light_manager.h, line 12 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYw6u159TQCyTh_p4V:-LAZgcjNCl1SmBQI5xZC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW This class appears to be misnamed. I don't see anything in it specific to traffic lights. Should it be something like `TrivialRightOfWayStateProvider` ? If there is something coming to make it specific to traffic lights, please add a TODO explaining that, and add some traffic-light specific documentation.
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.h, line 25 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYv-oV9eBuo-bSx3Aa:-LAZjCOyCKGwMu5Qbcqv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

True! I meant it would be more precise to _throw_ a logic_error. I wasn't proposing to lie about it!
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.h, line 32 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYxplpC77boF0G5uxH:-LAZjdHm7W6vMqShblCa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L32)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI std::out_of_range is an std::logic_error.
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.h, line 39 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYu_Xl8urbCNNoiM15:-LAZjf_s7DpJI685pEMO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.h#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI consider making this `final` rather than `override`. It will be final anyway because the class is final but that's not obvious looking just at the declaration here.
</blockquote></details>

Done.

---

*[automotive/trivial_traffic_light_manager.cc, line 13 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAYxEF_B6pcgPygJSYw:-LAZk_UXEmh2Jn9_8HeX:b3ohscd) ([raw file](https://github.com/robotlocomotion/drake/blob/23e2d00f4b315e107b1b16c87b25664c95aabc41/automotive/trivial_traffic_light_manager.cc#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW you don't need this check because it duplicates the check of the returned bool from emplace below.
</blockquote></details>

Done. It now throws a `std::logic_error` when the user attempts to add a duplicate ID.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642)*

**Comment by maddog-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[automotive/trivial_right_of_way_state_provider.cc, line 18 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAZoWsYBb30OxMlWgYg:-LAZoWsYBb30OxMlWgYh:b2ca8x9) ([raw file](https://github.com/robotlocomotion/drake/blob/0c06d12f3d8c499247edec4b4ce4240491304727/automotive/trivial_right_of_way_state_provider.cc#L18)):*
> ```cpp
>     throw std::logic_error(
>         "Attempted to add multiple rules with id " + id.string());
>   }
> ```

BTW:  This is exactly what the test of `result.second` below is checking for.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642)*

**Comment by sherm1** [comment]
CI is whining:
> automotive/trivial_right_of_way_state_provider.cc:17:  Add #include <string> for string  [build/include_what_you_use]

A few new BTWs below -- ptal.

---

Reviewed 4 of 10 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[automotive/trivial_right_of_way_state_provider.h, line 34 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAZvgVQ2epTyxAI2F7E:-LAZvgVR3toJfmoicBP1:b-96m9un) ([raw file](https://github.com/robotlocomotion/drake/blob/0c06d12f3d8c499247edec4b4ce4240491304727/automotive/trivial_right_of_way_state_provider.h#L34)):*
> ```objc
>   /// Sets the dynamic state of a RightOfWayRule within this manager.
>   ///
>   /// Throws std::logic_error if no dynamic state with @p id exists in this
> ```

BTW Sorry, Liang -- I really meant that as an FYI, not a suggestion for change. `std::out_of_range` is the perfect exception to throw here. I was just pointing out that it is a kind of logic_error, rather than a kind of runtime_error, in support of my earlier comment. It was better before.

---

*[automotive/trivial_right_of_way_state_provider.cc, line 18 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAZoWsYBb30OxMlWgYg:-LAZvtXN5DF86DPnAYl3:b-x179j1) ([raw file](https://github.com/robotlocomotion/drake/blob/0c06d12f3d8c499247edec4b4ce4240491304727/automotive/trivial_right_of_way_state_provider.cc#L18)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

BTW:  This is exactly what the test of `result.second` below is checking for.
</blockquote></details>

BTW no need to check this twice. Using your new message it should read:
```c++
{
  auto result = dynamic_states_.emplace(id, initial_state);
  if (!result.second) {
     throw std::logic_error(
        "Attempted to add multiple rules with id " + id.string());
  }
}
```

---

*[automotive/test/trivial_right_of_way_state_provider_test.cc, line 20 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAZwlQb-TcCcAy44elB:-LAZwlQb-TcCcAy44elC:bk750b1) ([raw file](https://github.com/robotlocomotion/drake/blob/0c06d12f3d8c499247edec4b4ce4240491304727/automotive/test/trivial_right_of_way_state_provider_test.cc#L20)):*
> ```cpp
>   EXPECT_THROW(dut.GetState(id), std::out_of_range);
>   EXPECT_THROW(dut.SetState(id, RightOfWayRule::DynamicState::kUncontrolled),
>                std::logic_error);
> ```

BTW out_of_range still good here.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-:-LAZv-a25Rhnswpbe171:b-w9a2kn)*

**Comment by liangfok** [comment]
Comments addressed.

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/trivial_right_of_way_state_provider.h, line 34 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAZvgVQ2epTyxAI2F7E:-LA_6lKk5SMoXXViOiYH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0c06d12f3d8c499247edec4b4ce4240491304727/automotive/trivial_right_of_way_state_provider.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Sorry, Liang -- I really meant that as an FYI, not a suggestion for change. `std::out_of_range` is the perfect exception to throw here. I was just pointing out that it is a kind of logic_error, rather than a kind of runtime_error, in support of my earlier comment. It was better before.
</blockquote></details>

Done.

---

*[automotive/trivial_right_of_way_state_provider.cc, line 18 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAZoWsYBb30OxMlWgYg:-LA_6T4y4Hyxs-xtyaZV:bb0g700) ([raw file](https://github.com/robotlocomotion/drake/blob/0c06d12f3d8c499247edec4b4ce4240491304727/automotive/trivial_right_of_way_state_provider.cc#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW no need to check this twice. Using your new message it should read:
```c++
{
  auto result = dynamic_states_.emplace(id, initial_state);
  if (!result.second) {
     throw std::logic_error(
        "Attempted to add multiple rules with id " + id.string());
  }
}
```
</blockquote></details>

Done. Thanks for the code!

---

*[automotive/test/trivial_right_of_way_state_provider_test.cc, line 20 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-LAZwlQb-TcCcAy44elB:-LA_6aRM95a16L_wXBbn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0c06d12f3d8c499247edec4b4ce4240491304727/automotive/test/trivial_right_of_way_state_provider_test.cc#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW out_of_range still good here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-:-LA_6pV87SWOuCxUJZAZ:bel95ya)*

**Comment by sherm1** [comment]
Looks great -- thanks! Ready to merge assuming all-green CI.

---

Reviewed 3 of 6 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8642#-:-LA_CK-2-nB1jXmWSIVq:b-uwm824)*

**Pull request merged**
