### PR TITLE
Move rotation and transform files from drake/multibody/multibody_tree/math to drake/math.

### PR DESCRIPTION
**Pull request by mitiguy**
Reviewer: The point of this PR is to move the functionality in the RotationMatrix and Transform classes (and associated files) from  drake/multibody/multibody_tree/math  to  drake/math.
This impacts some BUILD files, #include paths, etc.
This PR also fixes a BUILD file error in library dependencies in drake/automotive/maliput/api/test_utitilites/BUILD.bazel

Although there is a seemingly large number of new lines of code added to 
drake/math/rotation_matrix.h
The code is simply a cut/paste of the code that was previously in
drake/multibody/multibody_tree/math/rotation_matrix.h

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8275)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@seancurtis-tri 
Platform review +@ggould-tri 

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8275#-:-L6xKVmvd0eo99NzpYSA:b-yhbxz3)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Ready for platform review.

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[math/rotation_matrix.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8275#-L71E6VgDMknjphlR6R6:-L71E6VgDMknjphlR6R7:b-m374az) ([raw file](https://github.com/robotlocomotion/drake/blob/33bbe638eccd46d5efc786b59c2f74f0703a92cb/math/rotation_matrix.cc#L5)):*
> ```cpp
> #include "drake/common/default_scalars.h"
> 
> // Explicitly instantiate on the most common scalar types.
> ```

BTW This is not the "most common". This is purely the numerical types.

---

*[math/rotation_matrix_deprecated.cc, line 0 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8275#-L71DpxEMCe_t-8mRPlf:-L71DpxEMCe_t-8mRPlg:b-olsadv) ([raw file](https://github.com/robotlocomotion/drake/blob/d449ccdda3d3e94d7d0f2489857a676b71afa007/math/rotation_matrix_deprecated.cc#L0)):*
BTW This file shouldn't be in this commit.

---

*[tools/install/libdrake/build_components.bzl, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8275#-L71EXYiQRq3UCPdqY_R:-L71EXYjzMrgQoCr9fX7:b-68xqne) ([raw file](https://github.com/robotlocomotion/drake/blob/33bbe638eccd46d5efc786b59c2f74f0703a92cb/tools/install/libdrake/build_components.bzl#L116)):*
> ```Python
>     "//manipulation/schunk_wsg:schunk_wsg_lcm",
>     "//manipulation/sensors:xtion",
>     "//manipulation/util:bot_core_lcm_encode_decode",
> ```

BTW This confuses me. Does this still exist if you rebase onto master? When in doubt, remove this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8275#-:-L71GdKPrlXhVtkwSVwg:bsfch58)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8275#-:-L71GrX67UR_I1tA3kzI:b-s794vx)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[math/rotation_matrix.h, line 192 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8275#-L71ICHP2dlQqvrv2jPa:-L71ICHP2dlQqvrv2jPb:b-luk44q) ([raw file](https://github.com/robotlocomotion/drake/blob/33bbe638eccd46d5efc786b59c2f74f0703a92cb/math/rotation_matrix.h#L192)):*
> ```objc
>     // clang-format off
>     R << c2 * c1,  c2 * s1 * s0 - s2 * c0,  c2 * s1 * c0 + s2 * s0,
>         s2 * c1,  s2 * s1 * s0 + c2 * c0,  s2 * s1 * c0 - c2 * s0,
> ```

BTW as long as you're clang-format off, why not indent this and the next one more space so it all lines up.

---

*[math/rotation_matrix.h, line 225 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8275#-L71JqeU4znqizP4wo0B:-L71JqeU4znqizP4wo0C:b8bmw2o) ([raw file](https://github.com/robotlocomotion/drake/blob/33bbe638eccd46d5efc786b59c2f74f0703a92cb/math/rotation_matrix.h#L225)):*
> ```objc
>   }
> 
>   /// Returns the 3x3 identity %RotationMatrix.
> ```

BTW -- I assume that this and all the other following repetitions are necessary in order for the doxygen to look pretty?  It seems unfortunate.

---

*[math/rotation_matrix.h, line 274 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8275#-L71JKFk9KDB5uGI97wp:-L71JKFk9KDB5uGI97wq:b-k6yo44) ([raw file](https://github.com/robotlocomotion/drake/blob/33bbe638eccd46d5efc786b59c2f74f0703a92cb/math/rotation_matrix.h#L274)):*
> ```objc
> 
>   /// Returns how close the matrix R is to to being a 3x3 orthonormal matrix by
>   /// computing `‖R ⋅ R⁻¹ - I‖∞` (i.e., the maximum absolute value of the
> ```

R^-1 here, and below, and in the next two methods should all be R transpose, not R inverse.

---

*[math/rotation_matrix.h, line 350 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8275#-L71JfXH4oDgW-CwTN4z:-L71JfXH4oDgW-CwTN5-:b4cfhgv) ([raw file](https://github.com/robotlocomotion/drake/blob/33bbe638eccd46d5efc786b59c2f74f0703a92cb/math/rotation_matrix.h#L350)):*
> ```objc
>   /// value of the difference between the elements of `this` and `other`).
>   /// @param[in] other %RotationMatrix to subtract from `this`.
>   /// @returns `‖`this` - `other`‖∞`
> ```

BTW -- Does this render reasonably in Doxygen?  It seems unlikely to me.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8275#-:-L71LK9B-caRmf9TXDTI:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 20 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8275)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 20 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8275)*

**Comment by sherm1** [comment]
*[math/rotation_matrix.h, line 350 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8275#-L71JfXH4oDgW-CwTN4z:-L76EhGWN-Cxc4jRhZO_:b6kelet) ([raw file](https://github.com/robotlocomotion/drake/blob/33bbe638eccd46d5efc786b59c2f74f0703a92cb/math/rotation_matrix.h#L350)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Done.  Yes this looks OK (to me) in Doxygen.
</blockquote></details>

BTW Paul, did you intend to _nest_ those back ticks? Doxygen won't do that but instead is doing `‖` (symbol in code font) then "this" (not in code font), then ` - ` (space minus space) in code font, then "other" (not in code font), then `‖∞` (symbols in code font).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8275)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8275)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[math/rotation_matrix.h, line 432 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8275#-L76Xty3LB4L7slPrt_u:-L76Xty49A1XQ3iz1KPG:bujxamy) ([raw file](https://github.com/robotlocomotion/drake/blob/6d6d0619f5b9052471218dabd89dd56dafc842ae/math/rotation_matrix.h#L432)):*
> ```objc
>   // @param[in] R matrix from which `other` is subtracted.
>   // @param[in] other matrix to subtract from R.
>   // @returns `‖R - `other`‖∞`
> ```

BTW this also looks wrong -- consider searching for other instances.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8275)*

**Pull request merged**
