### PR TITLE
Monolithic pick-and-place demo BUILD and readme fix

### PR DESCRIPTION
**Pull request by naveenoid**
Addresses #6039

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6056)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@russtedrake for feature review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-:-KjdvfYHBfx8Da0nx6JA:b-e8hf3g)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjeluVLPAm40Cx5eTCj:-KjeluVLPAm40Cx5eTCk:b-v8dl9h) ([raw file](https://github.com/robotlocomotion/drake/blob/c3c0717725a3e49cffee0c4c7f1b52d409b1d0dd/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L9)):*
> ```Markdown
> 
> To run the demo, first you need to launch the drake visualizer and then
> execute from the drake-distro directory :
> ```

something happened here?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-Kjem1hZex8WxuSpONA-:-Kjem1hZex8WxuSpONA0:b-ym78s) ([raw file](https://github.com/robotlocomotion/drake/blob/c3c0717725a3e49cffee0c4c7f1b52d409b1d0dd/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L17)):*
> ```Markdown
> that you run a CMake build per the Drake instructions, using the same source
> tree as this demo.  In that case, the ``drake-visualizer`` will automatically
> be discovered can be launched by :
> ```

another bad sentence.  automatically discovered, or launched manually?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056)*

**Comment by RussTedrake** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjgkSEJEWcD-siyY1Iz:-KjgkSEK10E-yxx1TtOj:b-9xq0vl) ([raw file](https://github.com/robotlocomotion/drake/blob/d0fd000ea7806784eb4a07202c543bdf235fb417/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L24)):*
> ```Markdown
> ```
> 
> If the build system is unable to find the ``drake-visualizer``, you will see a
> ```

please clarify that this is during the bazel build, not the cmake build

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjgkbatqI4lBncuz-DM:-KjgkbatqI4lBncuz-DN:b-jpuy0m) ([raw file](https://github.com/robotlocomotion/drake/blob/d0fd000ea7806784eb4a07202c543bdf235fb417/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L47)):*
> ```Markdown
> or alternatively, navigate to the
> `drake-distro/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place_demo/`
> directory and then execute :
> ```

bazel can launch from any directory, using the full path/target specifier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056)*

**Comment by naveenoid** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjeluVLPAm40Cx5eTCj:-KjgFms287cySBmxkEBG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c3c0717725a3e49cffee0c4c7f1b52d409b1d0dd/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L9)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

something happened here?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-Kjem1hZex8WxuSpONA-:-KjgI-dhxonftYGOVxMn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c3c0717725a3e49cffee0c4c7f1b52d409b1d0dd/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L17)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

another bad sentence.  automatically discovered, or launched manually?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjgkSEJEWcD-siyY1Iz:-Kjh97qv73UYCZHih6A9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0fd000ea7806784eb4a07202c543bdf235fb417/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L24)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

please clarify that this is during the bazel build, not the cmake build
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjgkbatqI4lBncuz-DM:-KjhKy_WDMa0ezQPA6IY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0fd000ea7806784eb4a07202c543bdf235fb417/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L47)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

bazel can launch from any directory, using the full path/target specifier.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056)*

**Comment by RussTedrake** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjiBsIC-314-TBgpSRh:-KjiBsIC-314-TBgpSRi:b-tshj18) ([raw file](https://github.com/robotlocomotion/drake/blob/f747f49203e4282b10df7cf6e1e5cd377f9e7607/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L15)):*
> ```Markdown
> 
> The ``drake-visualizer`` is only available via a CMake build.  We recommend
> that you run a CMake build per the Drake instructions, using the same source
> ```

run cmake before bazel.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjiBlxfJa_6mvRJ7pKW:-KjiBlxfJa_6mvRJ7pKX:bnfif5x) ([raw file](https://github.com/robotlocomotion/drake/blob/f747f49203e4282b10df7cf6e1e5cd377f9e7607/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L46)):*
> ```Markdown
> 
> or alternatively, you can use ``bazel run`` using the appropriate
> full path/target specifier. For instance, from the current directory, you
> ```

"current" --> drake/examples/kuka... ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056)*

**Comment by naveenoid** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjiBsIC-314-TBgpSRh:-KjilxFLGsOdTtTWAEll:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f747f49203e4282b10df7cf6e1e5cd377f9e7607/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L15)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

run cmake before bazel.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-KjiBlxfJa_6mvRJ7pKW:-Kjin30sTC0xF8Gt_VVj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f747f49203e4282b10df7cf6e1e5cd377f9e7607/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L46)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"current" --> drake/examples/kuka... ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-:-KjjHhFLzxZJE353V9Ch:bnfp4nl)*

**Comment by naveenoid** [comment]
+@ggould-tri for platform review.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-:-Kjl2BorQS7bhi9FiT7D:b-8qo47q)*

**Comment by ggould-tri** [comment]
+(status: curate commits before merging) 
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-:-KjmZz33rcNqGGFtGByN:bash6sz)*

**Comment by naveenoid** [comment]
-(status: curate commits before merging) 

Moving to Squash merge.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6056#-:-Kjm_w6v5Z1I28ILtnoe:bhg5wvz)*

**Pull request merged**
