### PR TITLE
Switch to ipopt@3.11 formula on macOS

### PR DESCRIPTION
**Pull request by jamiesnape**
To match to the focal version and ameliorate issues relating to missing MA27 solver.

(Note this is a band aid, we really need to stick to `homebrew-core` versions otherwise we hit issues whenever `openblas` is updated.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14288)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

(builds will still fail, but less badly)

**Comment by jamiesnape** [comment]
Looks like a good improvement. +@soonho-tri for feature review.

**Comment by jamiesnape** [comment]
Doubling checking this does not break provisioned images. It really should not... 

@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14288#-:-MLNx3W3Avqj1xSzv380:bnfp4nl)* status: needs at least two assigned reviewers

___
*[tools/workspace/ipopt/repository.bzl, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14288#-MLNx5-W6j_Mll9xv6OE:-MLNx5-X8mX8fTWM8GTV:b-s75nfa) ([raw file](https://github.com/robotlocomotion/drake/blob/c89646e811357f9e7636cedcc563c73d2c2533f3/tools/workspace/ipopt/repository.bzl#L17)):*
> ```Starlark
>         pkg_config_paths = [
>             "/usr/local/opt/ipopt@3.11/lib/pkgconfig",
>             "/usr/local/opt/ipopt/lib/pkgconfig",
> ```

BTW, do we still need this line?

**Comment by jwnimmer-tri** [comment]
I'm having trouble finding where `ipopt@3.11` is defined on homebrew core.  Can you post a link in this discussion?  Maybe also a "teach a man to fish" for what website or URL pattern I can try to find this on my own.

**Review by soonho-tri — COMMENTED** [review]
=> https://github.com/RobotLocomotion/homebrew-director/blob/master/Formula/ipopt%403.11.rb

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14288#-:-MLNyDw98FJnJU_KIZZO:bbs6v7n)* status: needs at least two assigned reviewers

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14288)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jamiesnape)

___
*[setup/mac/binary_distribution/Brewfile, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14288#-MLNyNtk0iCxLAecKL_w:-MLNyNtk0iCxLAecKL_x:bb3sy9y) ([raw file](https://github.com/robotlocomotion/drake/blob/c89646e811357f9e7636cedcc563c73d2c2533f3/setup/mac/binary_distribution/Brewfile#L17)):*
> ```Ruby
> brew 'glib'
> brew 'graphviz'
> brew 'ipopt@3.11'
> ```

should be `robotlocomotion/director/ipopt@3.11`?

**Review by jamiesnape — COMMENTED** [review]
Homebrew will search all currently enabled taps for `ipopt@3.11`, but I am going to change it per the below discussion.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14288#-:-MLOSuzD-v0ouTZgbSs4:b-ag6wgh)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @soonho-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14288#-MLNyNtk0iCxLAecKL_w:-MLOSWqICYUiza8R3SI_:bubes7g) ([raw file](https://github.com/robotlocomotion/drake/blob/c89646e811357f9e7636cedcc563c73d2c2533f3/setup/mac/binary_distribution/Brewfile#L17)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

should be `robotlocomotion/director/ipopt@3.11`?
</blockquote></details>

It could be either, but I think you are right `robotlocomotion/director/ipopt@3.11` would be clearer just in case `ipopt@3.11` appears in `homebrew-core`
___
*[tools/workspace/ipopt/repository.bzl, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14288#-MLNx5-W6j_Mll9xv6OE:-MLOSKfG3ymc13_AecZQ:b-80zw5c) ([raw file](https://github.com/robotlocomotion/drake/blob/c89646e811357f9e7636cedcc563c73d2c2533f3/tools/workspace/ipopt/repository.bzl#L17)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, do we still need this line?
</blockquote></details>

Yes, I want to keep the current provisioned images working while we resolve the remaining issues.

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14288)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @soonho-tri)

___
*[tools/workspace/ipopt/repository.bzl, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14288#-MLNx5-W6j_Mll9xv6OE:-MLOWDv93-QaM8muztAN:b-4hvi0m) ([raw file](https://github.com/robotlocomotion/drake/blob/c89646e811357f9e7636cedcc563c73d2c2533f3/tools/workspace/ipopt/repository.bzl#L17)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Yes, I want to keep the current provisioned images working while we resolve the remaining issues.
</blockquote></details>

Got it.

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14288)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @soonho-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14288#-MLNyNtk0iCxLAecKL_w:-MLP68CN7mRM2AdMYUhV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c89646e811357f9e7636cedcc563c73d2c2533f3/setup/mac/binary_distribution/Brewfile#L17)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

It could be either, but I think you are right `robotlocomotion/director/ipopt@3.11` would be clearer just in case `ipopt@3.11` appears in `homebrew-core`
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14288)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14288#-:-MLP7k0y4B7Xkb4984Ht:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),soonho-tri(platform) (waiting on @ggould-tri)

**Pull request merged**
