### PR TITLE
quasistatic iiwa grasping and pick-up demo

### PR DESCRIPTION
**Pull request by pangtao22**
Simulation of iiwa arm grasping and moving an object initially at rest on a table using quasistatic time-stepping.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)

### CODE REVIEW

**Comment by pangtao22** [comment]
+@hongkai-dai for feature review.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-:-L9IR8zaEJwNcV39Xjp7:bl5ccwd)*

**Comment by pangtao22** [comment]
Question about unit test: what would be an appropriate unit test for a simulation demo? Comparing the system state at the end of the simulation to some desired value? The controlled-kuka demo (https://github.com/RobotLocomotion/drake/tree/master/examples/kuka_iiwa_arm/controlled_kuka ) doesn't seem to have any test.  

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-:-L9IRDpzC_lcytE0B8A5:b-3psb1e)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by hongkai-dai** [comment]
:lgtm:

This demo is complicated enough, that I do not think it is really a unit test. This is more like a demo of how the quasistatic simulator works. You can compare the system state at the end of the simulation to some desired value, if that desired value can be obtained using a separate approach from simulation, like in the closed form.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf, line 3 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-L9LfRV16zQK2IpvdUe3:-L9LfRV16zQK2IpvdUe4:b33ctp) ([raw file](https://github.com/robotlocomotion/drake/blob/421d27442be9f454a1a320c78473d289ff0fbcd6/manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf#L3)):*
> ```XML
> <?xml version="1.0" ?>
> 
> 
> ```

I suppose this document is not auto generated by the xacro file? If it is, please also upload the xacro file.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-:-L9gTJ0-BD2rRYhpU4RM:bkq08vc)*

**Comment by pangtao22** [comment]
Should I compare the final state of the simulation with the desired value in an assertion? 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf, line 3 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-L9LfRV16zQK2IpvdUe3:-L9mcyghD97Yn4fl-FvU:b-62aqi2) ([raw file](https://github.com/robotlocomotion/drake/blob/421d27442be9f454a1a320c78473d289ff0fbcd6/manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf#L3)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I suppose this document is not auto generated by the xacro file? If it is, please also upload the xacro file.
</blockquote></details>

It's not. In fact, this urdf is simply https://github.com/RobotLocomotion/drake/blob/master/manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf with the collision geometry removed. Is it possible to do this in `rigidbodytree` after loading the urdf? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-:-L9mckeu13OvNIpoZdHA:bj96nhs)*

**Comment by hongkai-dai** [comment]
Yes, please compare the final state of the simulation with the desired value, using `EXPECT_TRUE(CompareMatrices(...))`

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf, line 3 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-L9LfRV16zQK2IpvdUe3:-L9vWvfg1AX25hixeajF:bv63qs0) ([raw file](https://github.com/robotlocomotion/drake/blob/421d27442be9f454a1a320c78473d289ff0fbcd6/manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf#L3)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

It's not. In fact, this urdf is simply https://github.com/RobotLocomotion/drake/blob/master/manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf with the collision geometry removed. Is it possible to do this in `rigidbodytree` after loading the urdf? 
</blockquote></details>

I suppose you can modify the original `xacro` that generates `dual_iiwa14_polytope_collision.urdf`, and upload the xacro that generates the urdf without collision.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-:-L9vWZK78-25YgXUFTcw:bigawyh)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 287 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAV-yv350moKh0D2f4o:-LAV-yv350moKh0D2f4p:bywqzru) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L287)):*
> ```cpp
> 
>   // test final simulation state.
>   Eigen::Vector3d position_final_expected(0.3279, 0.1950, 0.8081);
> ```

Eigen::Vector3d -> const Eigen::Vector3d

BTW, could you comment on how you obtain the expected final position? If in the future, we change some parameter in the simulation, how do we know the expected final position?

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 288 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAV0Nd714T6LRuxDrnm:-LAV0Nd714T6LRuxDrnn:b-89a4l7) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L288)):*
> ```cpp
>   // test final simulation state.
>   Eigen::Vector3d position_final_expected(0.3279, 0.1950, 0.8081);
>   Eigen::Vector3d rpy_final_expected(2.2039, -0.0770, -0.0252);
> ```

Ditto

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 291 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAV0S081C6htPhssgBT:-LAV0S081C6htPhssgBU:b-57b5hq) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L291)):*
> ```cpp
> 
>   Eigen::VectorXd q_final = log_state->data().topRightCorner(n1, 1);
>   Eigen::Vector4d quaternion_final = q_final.tail(4);
> ```

const Eigen::Vector4d quaternion_final = q_final.tail<4>()

q_final.tail(4) creates a dynamically sized vector, with size 4, this would incur heap memory allocation. On the other hand, q_final.tail<4>() allocates the memory on the stack.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by pangtao22** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 287 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAV-yv350moKh0D2f4o:-LAVIGUB4Ch7sV-xTXkR:b3xbdzr) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L287)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Eigen::Vector3d -> const Eigen::Vector3d

BTW, could you comment on how you obtain the expected final position? If in the future, we change some parameter in the simulation, how do we know the expected final position?
</blockquote></details>

The final orientation (rpy) of the object should be the same as the end-effector rpy as specified in the trajectory optimization constraints. The final position (xyz) of the object should be the same as the end-effector position, plus some offset in the x-direction. But for some reason (tolerance in IK solve or the limited accuracy of the simulator), the error between those quantities is on the order of 0.1, which is pretty large. 

Therefore, instead of comparing the final state to the values set in IK constraints, I simply got these expected final states by simulating the system forward. Is this Ok?

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 288 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAV0Nd714T6LRuxDrnm:-LAVIH4qEM4hS8poIzUZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L288)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 291 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAV0S081C6htPhssgBT:-LAVJsaFDxhQfv100uPu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L291)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

const Eigen::Vector4d quaternion_final = q_final.tail<4>()

q_final.tail(4) creates a dynamically sized vector, with size 4, this would incur heap memory allocation. On the other hand, q_final.tail<4>() allocates the memory on the stack.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by hongkai-dai** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 287 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAV-yv350moKh0D2f4o:-LAVNLPbBzY3BYaq-yRk:b-f8jdyb) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L287)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

The final orientation (rpy) of the object should be the same as the end-effector rpy as specified in the trajectory optimization constraints. The final position (xyz) of the object should be the same as the end-effector position, plus some offset in the x-direction. But for some reason (tolerance in IK solve or the limited accuracy of the simulator), the error between those quantities is on the order of 0.1, which is pretty large. 

Therefore, instead of comparing the final state to the values set in IK constraints, I simply got these expected final states by simulating the system forward. Is this Ok?
</blockquote></details>

I would suggest to compare the result in this way
```C++
const Eigen::Vector3d position_final_expected = IK_FINAL_POSITION_CONSTRAINT_VALUE;

const double tolerance = 0.1;
EXPECT_TRUE(CompareMatrices(q_final.head<3>(), position_final_expected, tol));
```
which makes it more clear to the reader, that where `position_final_expected` come from, and also explain why that tolerance is so big here (0.1 is a very large discrepancy in the simulation).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by pangtao22** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 287 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAV-yv350moKh0D2f4o:-LAVgK4F2M3-yianFrnu:b-2bmoi7) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L287)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I would suggest to compare the result in this way
```C++
const Eigen::Vector3d position_final_expected = IK_FINAL_POSITION_CONSTRAINT_VALUE;

const double tolerance = 0.1;
EXPECT_TRUE(CompareMatrices(q_final.head<3>(), position_final_expected, tol));
```
which makes it more clear to the reader, that where `position_final_expected` come from, and also explain why that tolerance is so big here (0.1 is a very large discrepancy in the simulation).
</blockquote></details>

Another source of error is that the trajectory given by SNOPT and IKOPT are not exactly the same. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 287 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LAV-yv350moKh0D2f4o:-LAsZHrR2sw464cHxMrj:b-alkgwz) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L287)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Another source of error is that the trajectory given by SNOPT and IKOPT are not exactly the same. 
</blockquote></details>

Apologize for being pedantic, but where does that 0.12 come from?

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 296 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LAsZZKbAQ4NLJDoh7v_:-LAsZZKbAQ4NLJDoh7va:bo52p67) ([raw file](https://github.com/robotlocomotion/drake/blob/2bd189ecd04587c4cc7cd8632128a738aa1e8ffa/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L296)):*
> ```cpp
>   // optimization (MakePlan) are large. The large tolerances are needed for
>   // IPOPT to return feasible solutions.
>   EXPECT_TRUE(CompareMatrices(position_final_expected, q_final.head(3), 5e-2,
> ```

BTW, q_final.head(3) -> q_final.head<3>()

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 300 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LAsZj834N43iCvOqrO3:-LAsZj834N43iCvOqrO4:b-upbi3n) ([raw file](https://github.com/robotlocomotion/drake/blob/2bd189ecd04587c4cc7cd8632128a738aa1e8ffa/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L300)):*
> ```cpp
> 
> 
>   return 0;
> ```

How about the orientation? Do you also have `orientation_final_expected`, and compare it with your result?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by pangtao22** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 287 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LAV-yv350moKh0D2f4o:-LAs_cCx7TYQedv3EaBg:bpl1lds) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L287)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Apologize for being pedantic, but where does that 0.12 come from?
</blockquote></details>

It's the offset from the CG of the object to the end effector frame's origin along the x-axis. 

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 300 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LAsZj834N43iCvOqrO3:-LAs_6YwDm0XisHBSO2R:b-npbh0g) ([raw file](https://github.com/robotlocomotion/drake/blob/2bd189ecd04587c4cc7cd8632128a738aa1e8ffa/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L300)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

How about the orientation? Do you also have `orientation_final_expected`, and compare it with your result?
</blockquote></details>

The orientation sometimes gets tricky. Both RPY and quaternions have multiple representations for the same orientation, and different values have been returned by drake's conversion functions. How do you usually deal with this problem?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 287 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAV-yv350moKh0D2f4o:-LAsa32y2IOKyRXFCLGl:b-zcj3cu) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L287)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

It's the offset from the CG of the object to the end effector frame's origin along the x-axis. 
</blockquote></details>

You can get that offset value by `RigidBody::get_center_of_mass()` to return the center of mass position to the body's origin. It is better to use named variables here to improve the readability; otherwise future maintainers do not know how to maintain this code.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 300 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518#-LAsZj834N43iCvOqrO3:-LAsaU4aDAfsbdxJ-921:b56lzon) ([raw file](https://github.com/robotlocomotion/drake/blob/2bd189ecd04587c4cc7cd8632128a738aa1e8ffa/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L300)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

The orientation sometimes gets tricky. Both RPY and quaternions have multiple representations for the same orientation, and different values have been returned by drake's conversion functions. How do you usually deal with this problem?
</blockquote></details>

You can compare the rotation matrix, which has a unique value for each orientation.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by pangtao22** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 287 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LAV-yv350moKh0D2f4o:-LB2eT9g5iQ7eebKzuWX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76135b12c806edf7b0d0e583215aa0e0f1f3ece4/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L287)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

You can get that offset value by `RigidBody::get_center_of_mass()` to return the center of mass position to the body's origin. It is better to use named variables here to improve the readability; otherwise future maintainers do not know how to maintain this code.
</blockquote></details>

Done.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 296 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LAsZZKbAQ4NLJDoh7v_:-LB1iBXn3W9wOGVCTrZn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2bd189ecd04587c4cc7cd8632128a738aa1e8ffa/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L296)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, q_final.head(3) -> q_final.head<3>()
</blockquote></details>

Done.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 300 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LAsZj834N43iCvOqrO3:-LB2eRlM6NVfNqExTLy8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2bd189ecd04587c4cc7cd8632128a738aa1e8ffa/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L300)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

You can compare the rotation matrix, which has a unique value for each orientation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r4.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 309 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LB2fEIy-WgpamiQPmBZ:-LB2fEIy-WgpamiQPmB_:bgwhabo) ([raw file](https://github.com/robotlocomotion/drake/blob/b369dd88d5490c50ac986b80a5601c5e90ba8478/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L309)):*
> ```cpp
>   // compute expected_object_CG_final_position =
>   // expected_end_effector_final_position + [x_offset, 0, 0]
>   const Eigen::Vector3d position_final_expected(0.2 + x_offset, 0.2, 0.8);
> ```

I assume `0.2, 0.2, 0.8` is `pos_end` defined in line 110? Can you use the named variable `pos_end` here, and pass `pos_end` as an input argument of `MakePlan` function?

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 313 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LB2fnd6C2XxfH6Pq5mH:-LB2fnd6C2XxfH6Pq5mI:b-u8wfpd) ([raw file](https://github.com/robotlocomotion/drake/blob/b369dd88d5490c50ac986b80a5601c5e90ba8478/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L313)):*
> ```cpp
> 
>   // compute expected_object_orientation as a rotation matrix.
>   Eigen::Vector3d rpy_dumbbell_expected(M_PI / 4, 0, 0);
> ```

Also `rpy_dumbell_expected` is `rpy_end` in `MakePlan`? Then `MakePlan` should take `rpy_end` as an input argument.

We want to avoid the case that the future maintainer changes `rpy_end` in `MakePlan` function, but does not change `rpy_dumbbell_expected` here.

BTW, `Eigen::Vector3d` -> `const Eigen::Vector3d`.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 314 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LB2gFwt6nxUWq19ieTU:-LB2gFwt6nxUWq19ieTV:bxqggog) ([raw file](https://github.com/robotlocomotion/drake/blob/b369dd88d5490c50ac986b80a5601c5e90ba8478/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L314)):*
> ```cpp
>   // compute expected_object_orientation as a rotation matrix.
>   Eigen::Vector3d rpy_dumbbell_expected(M_PI / 4, 0, 0);
>   math::RotationMatrix<double> R_dumbbell_expected(
> ```

`const math::RotationMatrix<double>`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by hongkai-dai** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc, line 284 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LB2jCmi00sIqwUpL8VI:-LB2jCmi00sIqwUpL8VJ:b-pxkr3s) ([raw file](https://github.com/robotlocomotion/drake/blob/d2583b6d51d321219f213772057f50f9cd373d0e/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc#L284)):*
> ```cpp
>   simulator.get_mutable_integrator()->set_maximum_step_size(h);
>   simulator.Initialize();
>   simulator.StepTo(kTimes.back()); 
> ```

Remove the trailing empty space in this line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by hongkai-dai** [comment]
+(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518#-:-LB2qNOj74iPuzPjOl02:b-s794vx)*

**Comment by rcory** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8518#-L9LfRV16zQK2IpvdUe3:-LB2x-Aj2-7xiku4QHK1:b4frcw8) ([raw file](https://github.com/robotlocomotion/drake/blob/421d27442be9f454a1a320c78473d289ff0fbcd6/manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf#L3)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

I find it easier to just remove the comments saying that this file is generated by xacro. 
</blockquote></details>

BTW sorry to jump in here, but given that this model contains no collision elements, the word "polytope" in the file name doesn't really belong anymore, correct? I believe the original model was referencing the polytope geometry defined for link 7. Given that this model has no collision elements defined, perhaps a better name would be `iiwa14_no_collision.urdf`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by pangtao22** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8518#-L9LfRV16zQK2IpvdUe3:-LB3MdFvA38YSfoFeiOR:bpvmdbp) ([raw file](https://github.com/robotlocomotion/drake/blob/421d27442be9f454a1a320c78473d289ff0fbcd6/manipulation/models/iiwa_description/urdf/iiwa14_polytope_no_collision.urdf#L3)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

BTW sorry to jump in here, but given that this model contains no collision elements, the word "polytope" in the file name doesn't really belong anymore, correct? I believe the original model was referencing the polytope geometry defined for link 7. Given that this model has no collision elements defined, perhaps a better name would be `iiwa14_no_collision.urdf`?
</blockquote></details>

Name changed as suggested. Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review. This PR is in a dev folder, that does not have to be platform reviewed.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518#-:-LB6pJLmAlT7dByhiCBD:b6ew3g2)*

**Comment by pangtao22** [comment]
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[manipulation/dev/box_as_table.sdf, line 44 at r7](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LB7-FJG78o3hPskVtmk:-LB7XP2c50mN6mdg9mJb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/514221c8206c9ea6782e974745e9e59be051d1c0/manipulation/dev/box_as_table.sdf#L44)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI two minor issues: the file contains tabs (should only use spaces), and is missing newline at end of file.
</blockquote></details>

Done.

---

*[manipulation/dev/double_dumbbell_for_pick_up.sdf, line 127 at r7](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LB7-crAAU1yoSXOHYR8:-LB7XnQ7DcToXVp3d3Wg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/514221c8206c9ea6782e974745e9e59be051d1c0/manipulation/dev/double_dumbbell_for_pick_up.sdf#L127)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI two minor issues: the file contains tabs (should only use spaces), and is missing newline at end of file. (Also applies to the other sdf files in this PR.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Comment by sherm1** [comment]
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[manipulation/dev/dumbbell_for_pick_up.sdf, line 79 at r8](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LB7j-N2Aa0Qv2HOq8C7:-LB7j-N2Aa0Qv2HOq8C8:b-cv26nf) ([raw file](https://github.com/robotlocomotion/drake/blob/6e81ec26b93285feb42f0963be7b5487bf34ac0f/manipulation/dev/dumbbell_for_pick_up.sdf#L79)):*
> ```
> 
> 	</model>
> </sdf>
> ```

FYI -- this one still has tabs and a missing newline.

---

*[manipulation/dev/simplified_schunk_gripper.sdf, line 116 at r8](https://reviewable.io/reviews/robotlocomotion/drake/8518#-LB7jPDm5jumcyg16J8y:-LB7jPDn0xhC_t7hTw1W:b-vp9ff2) ([raw file](https://github.com/robotlocomotion/drake/blob/6e81ec26b93285feb42f0963be7b5487bf34ac0f/manipulation/dev/simplified_schunk_gripper.sdf#L116)):*
> ```
> 
> 	</model>
> </sdf>
> ```

FYI still has tabs and missing newline.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8518)*

**Pull request merged**
