### PR TITLE
[visualization] ColorizeDepthImage takes 32F and 16U depth as input

### PR DESCRIPTION
**Pull request by zachfang**
Relates #20221

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254)

### CODE REVIEW

**Comment by zachfang** [comment]
Need to figure out why one of the CIs failed.

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-:-NfGv56x7qALo1n_nwhG:b-1wvd9i)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

**Comment by jwnimmer-tri** [comment]
Would you be OK passing this off to Sean for feature review?   I'm already drowning in reviews today.

**Comment by zachfang** [comment]
Sure thing. @SeanCurtis-TRI would you have time for a feature review? This is not urgent though.

**Comment by SeanCurtis-TRI** [comment]
Happy to do so. -@jwnimmer-tri +@SeanCurtis-TRI.

**Review by zachfang — COMMENTED** [review]
Thanks. For context, it came up on the Meldis image visualization that we can only visualize 32F depth because it uses ColorizeDepthImage internally to convert depth to color.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-:-NfH3wBY4XbHVPZxfWnW:b-y8k0gl)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`bindings/pydrake/visualization/BUILD.bazel` line 215 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfH5-KpByjV4_K7yURa:-NfH5-KqDeSKH6_WVt7D:bxmfwdt) ([raw file](https://github.com/RobotLocomotion/drake/blob/b91fb2202c596c876ccce51c11cb72ba68c8141f/bindings/pydrake/visualization/BUILD.bazel#L215)):*
> ```Starlark
> drake_py_unittest(
>     name = "video_test",
>     size = "medium",
> ```

FYI. I encountered a timeout error in the CI debug build without this tag.



_Code quote:_
```Starlark
size = "medium"
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some small cosmetic things (and one non-blocking design question....probably targeted toward the original author).

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-:-NfHFhop92Jk1HtrToMs:b-plsps2)* status: 6 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfH9Rz-3lMua9Qh2Hhx:-NfH9Rz01U-pF022wesR:b5jv3z2) (no related file):*
A quick question orthogonal to this PR. This is not intended to be blocking.

We use a different color strategy from RViz (based on my limited experience while at Woven). Three traits jump out at me specifically.

- We remove the "invalid" distance from the color map (RViz includes it). 
    - I consider this to be good. This means we map our color map to the range of meaningful values. RViz treats the maximum 16-bit value as a value that need to be accounted for. In scenarios where a box lies near the camera without a detectable background, RViz renders the box a featureless black. This code would actually provide a gradation of values to the box.
- We put white near and black far. RViz reverses that.
    - On the one hand, I can make an argument for matching RViz so that people always see the "same" images (modulo the previous point).
    - The flip side is that without gamma correction, humans would be very bad at discerning the varying features in the dark end of the color range. And if the dark range is applied to near objects (those objects most likely to be of interest to the robot), those near objects become featureless (depending on the full depth range being mapped to). So, reversing the scale caters to humans better.
- We render an invalid color that RViz does not.
    - Again, I think the "no information" signal is a good thing.

I just broach the issue to see if these had been explicit decisions vis a vis RViz. I just wanted to make sure we were aware of the distinction in behavior.

___
___
*[`bindings/pydrake/visualization/_lcm_image_array_viewer.py` line 154 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfH7Di_7JR-F2uaApN6:-NfH7Di_7JR-F2uaApN7:bfzwzi2) ([raw file](https://github.com/RobotLocomotion/drake/blob/b91fb2202c596c876ccce51c11cb72ba68c8141f/bindings/pydrake/visualization/_lcm_image_array_viewer.py#L154)):*
> ```Python
>                 if image.channel_type == lcmt_image.CHANNEL_TYPE_UINT16:
>                     depth = ImageDepth16U(w, h)
>                 else:  # lcmt_image.CHANNEL_TYPE_FLOAT32
> ```

nit: Right now, you're relying on the fact that if the pixel format is depth, the `channel_type` can only be one of two values. Given that `channel_type` can actually take more values than just the two implied here, would it be better to make this a bit more robust?

It can either be an `assert` in the current `else` or an `elif ... = ...TYPE_FLOAT32` with a final `else` branch that raises an exception with more information? 
___
*[`bindings/pydrake/visualization/_video.py` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfH7le5--nxDwaP9sV0:-NfH7le672Nnb_QKy2hz:b-nyxnm6) ([raw file](https://github.com/RobotLocomotion/drake/blob/b91fb2202c596c876ccce51c11cb72ba68c8141f/bindings/pydrake/visualization/_video.py#L33)):*
> ```Python
>     """Converts a depth image, either 32F or 16U, to a color image. It is
>     assumed that only one of the input ports has value, or an exception will be
>     thrown.
> ```

BTW I think we could/should make this statement stronger/more direct.



_Suggestion:_
```Python
    """Converts a depth image, either 32F or 16U, to a color image. One
    input port, and only one, must be connected.
```
___
*[`bindings/pydrake/visualization/_video.py` line 79 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfH8F7EC1f1cKX2yUy_:-NfH8F7EC1f1cKX2yUya:b-emddf0) ([raw file](https://github.com/RobotLocomotion/drake/blob/b91fb2202c596c876ccce51c11cb72ba68c8141f/bindings/pydrake/visualization/_video.py#L79)):*
> ```Python
>         has_depth16u = self._depth16u_input.HasValue(context)
>         # Only one of the input ports should have value (not both or neither).
>         assert has_depth32f ^ has_depth16u
> ```

nit: This is slightly clever but perhaps unnecessary. There is a more intuitive `bool` operation: `has_depth32f != has_depth16u`.
___
*[`bindings/pydrake/visualization/test/video_test.py` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfHBOPZ49aPeAH4vJIi:-NfHBOP_6VeX5MwU3txj:b-462lri) ([raw file](https://github.com/RobotLocomotion/drake/blob/b91fb2202c596c876ccce51c11cb72ba68c8141f/bindings/pydrake/visualization/test/video_test.py#L39)):*
> ```Python
>         """
>         default_invalid_color = [100, 0, 0, 255]
>         expected_color = ImageRgba8U(6, 2, 0)
> ```

btw: Setting the initial value to zero to simply stomp on it in the very next line seems redundant. But that's not new to this PR.
___
*[`bindings/pydrake/visualization/test/video_test.py` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfHCgcK2DepAu_Retcw:-NfHCgcL9nTZDjC2sD1D:b8yco0v) ([raw file](https://github.com/RobotLocomotion/drake/blob/b91fb2202c596c876ccce51c11cb72ba68c8141f/bindings/pydrake/visualization/test/video_test.py#L61)):*
> ```Python
>         return depth
> 
>     def test_duplicated_inputs(self):
> ```

nit: This should be `test_badly_connected_inputs()` and you should test both connected and *none* connected. Fortunately, it just takes a couple of additional lines of code before fixing values on the ports.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254)* status: 6 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfH9Rz-3lMua9Qh2Hhx:-NfHHq5BDBOjNovFFrtE:b-tsu36f) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

A quick question orthogonal to this PR. This is not intended to be blocking.

We use a different color strategy from RViz (based on my limited experience while at Woven). Three traits jump out at me specifically.

- We remove the "invalid" distance from the color map (RViz includes it). 
    - I consider this to be good. This means we map our color map to the range of meaningful values. RViz treats the maximum 16-bit value as a value that need to be accounted for. In scenarios where a box lies near the camera without a detectable background, RViz renders the box a featureless black. This code would actually provide a gradation of values to the box.
- We put white near and black far. RViz reverses that.
    - On the one hand, I can make an argument for matching RViz so that people always see the "same" images (modulo the previous point).
    - The flip side is that without gamma correction, humans would be very bad at discerning the varying features in the dark end of the color range. And if the dark range is applied to near objects (those objects most likely to be of interest to the robot), those near objects become featureless (depending on the full depth range being mapped to). So, reversing the scale caters to humans better.
- We render an invalid color that RViz does not.
    - Again, I think the "no information" signal is a good thing.

I just broach the issue to see if these had been explicit decisions vis a vis RViz. I just wanted to make sure we were aware of the distinction in behavior.
</blockquote></details>

This is just how we've always done it.  IIRC it originated with Eric's MbP rendering tutorial.   (The library code for colorizing was refactored out of the tutorial back into pydrake.)  For myself, I was not aware of how RViz did it.

Having said that -- I think RViz is just wrong?  To me, the obvious answer is brighter=nearer, as if we had a light on our camera.

If people really wanted darker=nearer, I guess it would be fine to add a flag to the class for which one it should do.

___

**Comment by SeanCurtis-TRI** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is just how we've always done it.  IIRC it originated with Eric's MbP rendering tutorial.   (The library code for colorizing was refactored out of the tutorial back into pydrake.)  For myself, I was not aware of how RViz did it.

Having said that -- I think RViz is just wrong?  To me, the obvious answer is brighter=nearer, as if we had a light on our camera.

If people really wanted darker=nearer, I guess it would be fine to add a flag to the class for which one it should do.
</blockquote></details>

re: Rviz is just wrong

Yeah. For all of the arguments I gave, RViz's (default?) behavior seems difficult to defend. For all I know, it's default behavior is better and I just happened to sample it in a domain that was configured a particular way. Thanks for the info. As of now, we can say, "Ah...different. And better."

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254)* status: needs at least two assigned reviewers, missing label for release notes

___
*[`bindings/pydrake/visualization/_lcm_image_array_viewer.py` line 154 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfH7Di_7JR-F2uaApN6:-NfN0f5M7y-ZLPhQw08R:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b91fb2202c596c876ccce51c11cb72ba68c8141f/bindings/pydrake/visualization/_lcm_image_array_viewer.py#L154)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Right now, you're relying on the fact that if the pixel format is depth, the `channel_type` can only be one of two values. Given that `channel_type` can actually take more values than just the two implied here, would it be better to make this a bit more robust?

It can either be an `assert` in the current `else` or an `elif ... = ...TYPE_FLOAT32` with a final `else` branch that raises an exception with more information?
</blockquote></details>

Done.
___
*[`bindings/pydrake/visualization/_video.py` line 79 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-NfH8F7EC1f1cKX2yUy_:-NfN0i0p-sRjlmHPN_AV:b-dqp63m) ([raw file](https://github.com/RobotLocomotion/drake/blob/b91fb2202c596c876ccce51c11cb72ba68c8141f/bindings/pydrake/visualization/_video.py#L79)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This is slightly clever but perhaps unnecessary. There is a more intuitive `bool` operation: `has_depth32f != has_depth16u`.
</blockquote></details>

Ah, nice trick.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254)* status: needs at least two assigned reviewers, missing label for release notes

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-:-NfQt6vh6jNvxxS0ONah:bz1t39v)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @zachfang)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-:-NfSeOQ06GV8lluMszhZ:bnfp4nl)* status: missing label for release notes (waiting on @zachfang)

**Review by sammy-tri — COMMENTED** [review]
I'm gonna go with +(release notes: none) as this seems to be incremental progress to the actual feature in #20221

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20254#-:-NfSey3t0-dv_rbV3jZL:b-ek4ot2)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
> ... this seems to be incremental progress to the actual feature in https://github.com/RobotLocomotion/drake/pull/20221.

That's true.  In this case however since `ColorizeDepthImage` is public API, I think it's with "notes: feature" to mention that small improvement on its own, outside of the Meldis Epic.

**Pull request merged**
