### PR TITLE
Expand pydrake IK bindings

### PR DESCRIPTION
**Pull request by rconnorlawson**
I needed these constraints for my work with Draper this summer. No functional changes were made; the items below were simply added to the bindings.

Constraints added:

* WorldGazeTargetConstraint
* RelativePositionConstraint
* RelativeGazeDirConstraint
* MinDistanceConstraint

Functions added:

* RigidBodyTree::get_num_frames
* RigidBodyTree::getBodyOrFrameName

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6844)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot add to whitelist

**Comment by sammy-tri** [comment]
+@sammy-tri for feature review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KraRK_E79GJ7Gqvebio:b-an7kl2)*

**Comment by rdeits** [comment]
It would probably be good to add some tests like the ones in https://github.com/RobotLocomotion/drake/tree/master/drake/bindings/python/pydrake/test just to make sure these bindings work. Otherwise this all looks good to me. 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrahABXNL66lGwmx_U0:b5kvk53)*

**Comment by rconnorlawson** [comment]
Smoke tests are added for the new constraints. These just check that the constructors don't throw any exceptions. As discussed in Slack, anything more belongs in the C++ tests since this is just a wrapper.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-Krb38vTK0vcWK9fK25D:b-p6rx5u)*

**Comment by sammy-tri** [comment]
+@seancurtis-tri for first round of review, I'll do second round (let's both do feature and platform since the change is relatively small and straightforward)

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrbJgnnDEOE1f_zlKQh:b-71ckx)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) I need to brush up on my pep-8 knowledge. I put in a number of FYIs regarding python style standards. Rather than hold this up while I dig for everything I'm questioning, I'm going to :LGTM: this and pass it on to @sammy-tri who can dismiss/confirm my issues.

Second, there's the question of do we have a explicit binding style where we mirror bad parameter names, regardless? I can see arguments in both directions (mirroring APIs as perfectly as possible vs. propagating badness).

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_ik.cc, line 51 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbWS4rJ09tkvztTKut:-KrbWS4rJ09tkvztTKuu:b-qnaswv) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/pybind11/pydrake_ik.cc#L51)):*
> ```cpp
>                   const Eigen::Matrix<double, 7, 1>&,
>                   const Eigen::Vector2d&>(),
>          py::arg("model"),
> ```

FYI I recognize this mirrors the C++ code. But these are bad parameter names.

---

*[drake/bindings/python/pydrake/solvers/ik.py, line 17 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbW1mCuBdxaeMn3sAx:-KrbW1mCuBdxaeMn3sAy:b-p5s6sk) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/solvers/ik.py#L17)):*
> ```Python
>                           WorldGazeTargetConstraint,
>                           RelativeGazeDirConstraint,
>                           MinDistanceConstraint,
> ```

FYI I'm somewhat surprised these aren't alphabetized.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 65 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbUaLhBOoHgK2kvHRO:-KrbUaLi2lAvqU_gljl4:bhojp8) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L65)):*
> ```Python
> 
>     def testWorldGazeTargetConstraint(self):
>         # Test that construction doesn't fail (default timespan)
> ```

nit: META cappunc in these comments (i.e., trailing period). And I mean the `# Test that ....` comments and not the parameter labels.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 67 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbUn8lghCDPh2_Lwie:-KrbUn8lghCDPh2_Lwif:b-j709eg) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L67)):*
> ```Python
>         # Test that construction doesn't fail (default timespan)
>         gaze_constraint = ik.WorldGazeTargetConstraint(
>             self.r,             # model
> ```

BTW I'm mildly curious about the verbosity of the parameter labels. It doesn't seem to be the style of the rest of the file. Generally, the previous test seems to use (somewhat) named variables (except for threshold). You may consider assigning the values to variables and simply invoking the method using those named locals.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 83 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbVNdNgsDEVpvhOhKT:-KrbVNdNgsDEVpvhOhKU:b20umnr) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L83)):*
> ```Python
>             np.zeros([3, 1]),   # gaze_origin
>             1e-3,               # conethreshold
>             np.array([0., 1.])  # tspan
> ```

FYI nit: This should probably be spelled out: timespan

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 88 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbVd2ZZc7X1Cb1SaDx:-KrbVd2ZZc7X1Cb1SaDy:b-j0nxfi) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L88)):*
> ```Python
>     def testRelativePositionConstraint(self):
>         # Transform from origin of B to points on B
>         bTbp = np.concatenate([
> ```

BTW variable name has disallowed abbreviation?

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 94 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbVlu5NMdv79zbF1VE:-KrbVlu5NMdv79zbF1VF:b-bnrqwx) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L94)):*
> ```Python
> 
>         # Test that construction doesn't fail (default timespan)
>         position_constraint = ik.RelativePositionConstraint(
> ```

FYI meta: You probably don't have to capture the return value if you're not actually doing anything with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrbUGLaSDycvu5sNidY:bckxpfh)*

**Comment by rconnorlawson** [comment]
I've added specific response inline, but overall opinion on parameter style in these tests is that consistency is most important due to the lack of documentation in the C++ source. Figuring out what Python types/shapes these parameters need and what they mean is hard. These tests should serve as a reference for Python usage, but all roads should lead to  C++ as the source of truth for meaning.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_ik.cc, line 51 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbWS4rJ09tkvztTKut:-KrbibnWtxB0F2z-wC4o:b-deb0to) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/pybind11/pydrake_ik.cc#L51)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I recognize this mirrors the C++ code. But these are bad parameter names.
</blockquote></details>

I absolutely agree. The parameters are really obscure. When using these, I had to work out the math to figure out what was going on.

---

*[drake/bindings/python/pydrake/solvers/ik.py, line 17 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbW1mCuBdxaeMn3sAx:-KrbitDbXIq5k2Tw0qHt:b41f15e) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/solvers/ik.py#L17)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I'm somewhat surprised these aren't alphabetized.
</blockquote></details>

I agree that alphabetical would make more sense. The constraints roughly mirror the order in the C++ header, but imperfectly (RelativePositionConstraint and QuasiStaticConstraint are in the wrong places).

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 67 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbUn8lghCDPh2_Lwie:-Krbz_CjMXV9tlhPUWOY:b-4wru7s) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L67)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm mildly curious about the verbosity of the parameter labels. It doesn't seem to be the style of the rest of the file. Generally, the previous test seems to use (somewhat) named variables (except for threshold). You may consider assigning the values to variables and simply invoking the method using those named locals.
</blockquote></details>

Given the poor naming of the C interface and lack of documentation, I opted for consistency over stylistic correctness here, because the C code is the ultimate source of truth for the meaning of these parameters. Any other name we use probably won't be much help since these parameters have such specific meaning and would be added noise for a future dev to figure out. I think this style most clearly shows the correspondence to the C interface without giving the impression that "pts" is a name that should carry meaning outside of that context. Types are also challenging to get right with these C interfaces, and this style puts an immediate value with the correct type right next to the corresponding parameter name. I can say from experience using these bindings that this is a helpful reference.

But that's just my opinion and you make a good argument too. I'll defer to Sam's review.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 83 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbVNdNgsDEVpvhOhKT:-KrbmPrXJUta8LhUeW8n:bbuwgql) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L83)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI nit: This should probably be spelled out: timespan
</blockquote></details>

Usage of tspan here is consistent with the rest of the file in mirroring the C parameter names

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 88 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbVd2ZZc7X1Cb1SaDx:-KrbxFUpjcUoiYELeORQ:b-czio9) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L88)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW variable name has disallowed abbreviation?
</blockquote></details>

This is for again for consistency with C, but this is a particularly difficult variable to name. Logically, it represents points relative to the origin of body B, but unlike any other constraint parameter it has to be expressed as a matrix whose columns are transforms (concatenated position and quaternion).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-Krc-n_AsSjJopx9yH0n:b-8sagr1)*

**Comment by SeanCurtis-TRI** [comment]
I can certainly accept those issues where things are directly bound to the C++ code. But there are still some issues that are uniquely python.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 67 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbUn8lghCDPh2_Lwie:-KrcB42yGiZhgieDjFHC:b-nejkd7) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L67)):*
<details><summary><i>Previously, rconnorlawson (Connor Lawson) wrote…</i></summary><blockquote>

Given the poor naming of the C interface and lack of documentation, I opted for consistency over stylistic correctness here, because the C code is the ultimate source of truth for the meaning of these parameters. Any other name we use probably won't be much help since these parameters have such specific meaning and would be added noise for a future dev to figure out. I think this style most clearly shows the correspondence to the C interface without giving the impression that "pts" is a name that should carry meaning outside of that context. Types are also challenging to get right with these C interfaces, and this style puts an immediate value with the correct type right next to the corresponding parameter name. I can say from experience using these bindings that this is a helpful reference.

But that's just my opinion and you make a good argument too. I'll defer to Sam's review.
</blockquote></details>

I may not have been clear.  Rather than this:

```py
foo(1.3,   # a parameter
    3.2    # another parameter
   )
```

I would've expected
```py
a_paramter = 1.3
another_parameter = 3.2
foo(a_parameter, another_parameter)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrcBo7-XRNwOTw11XSZ:b29l9s2)*

**Comment by rconnorlawson** [comment]
Thanks for the feedback, requested changes are in the latest push.

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 65 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbUaLhBOoHgK2kvHRO:-KrfFoEoN8TOPwX90Noi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: META cappunc in these comments (i.e., trailing period). And I mean the `# Test that ....` comments and not the parameter labels.
</blockquote></details>

Done.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 67 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-KrbUn8lghCDPh2_Lwie:-KrfBfVL8elL1vu8s_tK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/080f9af7723da8c587960472a881497f6764bb3d/drake/bindings/python/pydrake/test/testRBTIK.py#L67)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I may not have been clear.  Rather than this:

```py
foo(1.3,   # a parameter
    3.2    # another parameter
   )
```

I would've expected
```py
a_paramter = 1.3
another_parameter = 3.2
foo(a_parameter, another_parameter)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrfFpVxnD4fSa3-2j0F:b-26qft3)*

**Comment by SeanCurtis-TRI** [comment]
@sammy-tri over to you.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrfK62A9cCiBc3Qi5Fy:b-bjzpk6)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrfaFRw3VG2mg9jlfpD:bnfp4nl)*

**Comment by sammy-tri** [comment]
@rconnorlawson I'm not sure if you have the bits to do a squash merge...  If you want to manually clean up the commit history (`git rebase -i` style or similar) and then remove the "curate commits before merging" label, I'll merge.  If you're OK with me trying the auto-squash-merge thing (which I've never actually done), I can give that a shot too.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrfaMtkWuEUQsX0X9V2:bk95wyb)*

**Comment by rconnorlawson** [comment]
@sammy-tri I'm also inexperienced with the rebase/squash merge in context of pull requests. Would `git rebase -i` not rewrite history? I can force push a curated branch to my own repo, but I don't know how the CI/code review/pull request tools handle that kind of change.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrfcBEJ2mVqr0muKeub:b-1n7yaz)*

**Comment by SeanCurtis-TRI** [comment]
I've used the reviewable squash merge a great deal. If you grab the pull down, you can edit the resultant commit message and everything else proceeds as expected. Then you have no worries about history.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-KrfsyDTuabhwBbsnyj2:b5kp3ku)*

**Comment by sammy-tri** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-Krg37LKlpiOsmJ_EXLc:b-l70wzf)*

**Comment by sammy-tri** [comment]
I went ahead and squashed here.  Reviewable is fine with `git rebase -i` antics.  the "revisions" of a PR in Reviewable correspond to what the code under review looked like at that time, not the git commit history (that may have been a crappy explanation but hopefully it made a little sense)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6844#-:-Krg3I2vyA8ArogmgdV9:b-aoux89)*

**Pull request merged**
