### PR TITLE
Add feature to visually highlight specific Segments in GenerateObj().

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6194)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature review, please.

The result looks like this:


---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6194#-:-Kl5fuRbyhaYCPYkCMkD:b-qtfs11)*

**Comment by liangfok** [comment]
:lgtm:

Note that the highlighted segment looks better in `view3dscene`:



than it does in `meshlab`:



In `meshlab`, it almost looks at though the highlighted segment is grayed out!

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6194#-:-KlOV_hBeP1t1mBX73Z3:babxv64)*

**Comment by maddog-tri** [comment]
Yeah, I've never seen `meshlab` load an OBJ/MTL convincingly correctly, hence my use of `view3dscene` instead. (`meshlab` does do a little better if one selects "Render -> Color -> Per Face", though.)

+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6194#-:-KlOqPeClFSB5kHBtGxS:b-xjm3kb)*

**Comment by sammy-tri** [comment]
:lgtm: pending CI

---

Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6194#-:-KlPlSDvfY_z9gfunoTY:b3cfjge)*

**Comment by maddog-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6194#-:-KlPq8iFQs-kmIzeyasK:b-3f2dwx)*

**Pull request merged**
