### PR TITLE
Clean up the two remaining errors in Clang and turn on -Werror.

### PR DESCRIPTION
**Pull request by david-german-tri**
Contributes to #1936.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2370)

### CODE REVIEW

**Comment by sherm1** [comment]
One comment, otherwise :lgtm:.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> #### Clean up the two remaining errors in Clang and turn on \-Werror\.
> 
> Contributes to #1936.
> 
> 
> </details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/test/testPolynomial.cpp, line 161 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvbHzVU7bOyWyRRBJ8:-KHvbHzVU7bOyWyRRBJ9:-1290122210) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4b0b835b0e6bbc5209eafea6e466ac07e20660/drake/util/test/testPolynomial.cpp#L161)):*
> ```cpp
> 
>       double expected_product = 0.0;
>       for (size_t i = 0; i < A.cols(); i++) {
> ```

Index is size_t here, int in the outer loops. Should be consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-:-KHvbW9wD9wb0bdvcLET:-2015181726)*

**Comment by david-german-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/test/testPolynomial.cpp, line 161 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvbHzVU7bOyWyRRBJ8:-KHvcU0SnDW1dRxBO9V1:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4b0b835b0e6bbc5209eafea6e466ac07e20660/drake/util/test/testPolynomial.cpp#L161)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Index is size_t here, int in the outer loops. Should be consistent.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testPolynomial.cpp, line 156 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvcdSP7kH-39MBM1J9:-KHvcdSQeB1TtA8jNAAF:-1192807382) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4b0b835b0e6bbc5209eafea6e466ac07e20660/drake/util/test/testPolynomial.cpp#L156)):*
> ```cpp
>     for (int col = 0; col < A.cols(); ++col) {
>       double t = uniform(generator);
>       EXPECT_NEAR(sum(row, col).evaluateUnivariate(t),
> ```

Should this be `GTEST_EXPECT_NEAR`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by sherm1** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/test/testPolynomial.cpp, line 156 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvcdSP7kH-39MBM1J9:-KHvhWrv8LbxQ_FGlbcc:-531282753) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4b0b835b0e6bbc5209eafea6e466ac07e20660/drake/util/test/testPolynomial.cpp#L156)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should this be `GTEST_EXPECT_NEAR`?</details>
Does that exist?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by jwnimmer-tri** [comment]
Wow, I remember the `bool coverings` from some prior tool that was yelling (cpplint?) that I didn't get around to fixing yet.  Yay for `-Werror`!

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> One comment, otherwise :lgtm:.</details>


---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testPolynomial.cpp, line 153 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvi3NAHF0mH2Uedl5u:-KHvi3NBHuFybq7mTRzU:-1512206034) ([raw file](https://github.com/robotlocomotion/drake/blob/4c2475b406bd1f5be847fd6ee382ece7b9ca01ac/drake/util/test/testPolynomial.cpp#L153)):*
> ```cpp
> 
>   uniform_real_distribution<double> uniform;
>   for (size_t row = 0; row < A.rows(); ++row) {
> ```

Are you sure these are all unsigned (size_t?).  Eigen seems to use std::ptrdiff_t through various typedefs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-:-KHvg_m7kR3SCL1ojgDh:-358406679)*

**Comment by david-german-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testPolynomial.cpp, line 156 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvcdSP7kH-39MBM1J9:-KHvoxoV6UaewS5Zt_Ks:1744014868) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4b0b835b0e6bbc5209eafea6e466ac07e20660/drake/util/test/testPolynomial.cpp#L156)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Does that exist?</details>
Appears not: https://github.com/google/googletest/blob/d225acc90bc3a8c420a9bcd1f033033c1ccd7fe0/googletest/include/gtest/gtest.h

---

*[drake/util/test/testPolynomial.cpp, line 153 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvi3NAHF0mH2Uedl5u:-KHvsKPqzSYhVmc-YL5B:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4c2475b406bd1f5be847fd6ee382ece7b9ca01ac/drake/util/test/testPolynomial.cpp#L153)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Are you sure these are all unsigned (size_t?).  Eigen seems to use std::ptrdiff_t through various typedefs.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testPolynomial.cpp, line 10 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvtE4l6hKkT-w61Gty:-KHvtE4l6hKkT-w61Gtz:-199393419) ([raw file](https://github.com/robotlocomotion/drake/blob/6498c5d90ef9c97b9e22086092c44a5d6dac3240/drake/util/test/testPolynomial.cpp#L10)):*
> ```cpp
> #include "drake/util/testUtil.h"
> 
> #include <Eigen/Dense>
> ```

Out of place (other libraries should appear prior to drake).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testPolynomial.cpp, line 10 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvtE4l6hKkT-w61Gty:-KHvyGziztfQnZ5kBYmz:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6498c5d90ef9c97b9e22086092c44a5d6dac3240/drake/util/test/testPolynomial.cpp#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Out of place (other libraries should appear prior to drake).</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by jwnimmer-tri** [comment]
:lgtm: (not sure which of sherm1 and I are feature / platform, but either way).

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Wow, I remember the `bool coverings` from some prior tool that was yelling (cpplint?) that I didn't get around to fixing yet.  Yay for `-Werror`!
> 
> </details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-:-KHvy_Gdd5zNDVqmcwrm:-1149172993)*

**Comment by sherm1** [comment]
One new comment.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> :lgtm: (not sure which of sherm1 and I are feature / platform, but either way).</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testPolynomial.cpp, line 158 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvxDiwUP8t5WZHhmEI:-KHvxDiwUP8t5WZHhmEJ:-2067407222) ([raw file](https://github.com/robotlocomotion/drake/blob/6498c5d90ef9c97b9e22086092c44a5d6dac3240/drake/util/test/testPolynomial.cpp#L158)):*
> ```cpp
>   uniform_real_distribution<double> uniform;
>   for (std::ptrdiff_t row = 0; row < A.rows(); ++row) {
>     for (std::ptrdiff_t col = 0; col < A.cols(); ++col) {
> ```

`size_t` and `ptrdiff_t` are very closely related. If we're going to allow `size_t` without the `std::` qualifier (which I think is a good idea), then we should write `ptrdiff_t` the same way. For a long discussion, see [stackoverflow](http://stackoverflow.com/questions/5813700/difference-between-size-t-and-stdsize-t). Bottom line is `<cstddef>` must define `std::size_t, std::ptrdiff_t` and other things, and may define `::size_t, ::ptrdiff_t` etc. and if so they must be identical to the `std::` definitions. Apparently all compilers actually do that, because they implement `<cstddef>` by including `<stddef.h>`, which is obligated to define `::size_t` and so on. So, like `#pragma once` this will work in practice and will save us a *lot* of ugly `std::`s. And ... if it ever failed we could just add `using size_t = std::size_t;` to a common header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-:-KHvyld3MZRi-wuA0JAQ:-1492332850)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testPolynomial.cpp, line 158 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvxDiwUP8t5WZHhmEI:-KHvzSWXy--mvFUze_Ju:-1390414613) ([raw file](https://github.com/robotlocomotion/drake/blob/6498c5d90ef9c97b9e22086092c44a5d6dac3240/drake/util/test/testPolynomial.cpp#L158)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `size_t` and `ptrdiff_t` are very closely related. If we're going to allow `size_t` without the `std::` qualifier (which I think is a good idea), then we should write `ptrdiff_t` the same way. For a long discussion, see [stackoverflow](http://stackoverflow.com/questions/5813700/difference-between-size-t-and-stdsize-t). Bottom line is `<cstddef>` must define `std::size_t, std::ptrdiff_t` and other things, and may define `::size_t, ::ptrdiff_t` etc. and if so they must be identical to the `std::` definitions. Apparently all compilers actually do that, because they implement `<cstddef>` by including `<stddef.h>`, which is obligated to define `::size_t` and so on. So, like `#pragma once` this will work in practice and will save us a *lot* of ugly `std::`s. And ... if it ever failed we could just add `using size_t = std::size_t;` to a common header.</details>
I like the proposal in general, but I'm wary of us inventing new defect rules that hold up PRs for things we've not yet agreed on.  Perhaps consider filing an issue instead, letting this PR through, and then fixing the extra `std::`s _everywhere_ throughout the code that has that defect, as part of that issue resolution?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testPolynomial.cpp, line 156 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvcdSP7kH-39MBM1J9:-KHwJKROfpaa_AOQlAv3:-1075844351) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4b0b835b0e6bbc5209eafea6e466ac07e20660/drake/util/test/testPolynomial.cpp#L156)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Appears not: https://github.com/google/googletest/blob/d225acc90bc3a8c420a9bcd1f033033c1ccd7fe0/googletest/include/gtest/gtest.h</details>
I guess this must be a hazard of using macros. I tested by replacing `EXPECT_NEAR` with `GTEST_EXPECT_NEAR`, compiled the code, and ran the unit test. If `GTEST_EXPECT_NEAR` in fact does not exist, it must have failed silently. Maybe the macro evaluated to nil?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by sherm1** [comment]
*[drake/util/test/testPolynomial.cpp, line 156 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvcdSP7kH-39MBM1J9:-KHwgYDJwpTbJ3uUJL5B:654708050) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4b0b835b0e6bbc5209eafea6e466ac07e20660/drake/util/test/testPolynomial.cpp#L156)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I guess this must be a hazard of using macros. I tested by replacing `EXPECT_NEAR` with `GTEST_EXPECT_NEAR`, compiled the code, and ran the unit test. If `GTEST_EXPECT_NEAR` in fact does not exist, it must have failed silently. Maybe the macro evaluated to nil?</details>
Wait ... that can't be right! If you use an undefined macro you'll get an error message. For it to work the way you said it would either have to be defined as something empty (where?), or (maybe more likely) the code you changed didn't actually get compiled for some reason, or it failed but the error wasn't noticeable somehow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by sherm1** [comment]
*[drake/util/test/testPolynomial.cpp, line 158 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvxDiwUP8t5WZHhmEI:-KHx7Mv19dKKCRY6P659:-1044511359) ([raw file](https://github.com/robotlocomotion/drake/blob/6498c5d90ef9c97b9e22086092c44a5d6dac3240/drake/util/test/testPolynomial.cpp#L158)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I like the proposal in general, but I'm wary of us inventing new defect rules that hold up PRs for things we've not yet agreed on.  Perhaps consider filing an issue instead, letting this PR through, and then fixing the extra `std::`s _everywhere_ throughout the code that has that defect, as part of that issue resolution?</details>
Done -- see #2374.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370)*

**Comment by liangfok** [comment]
:lgtm_strong: 

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> One new comment.</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testPolynomial.cpp, line 156 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-KHvcdSP7kH-39MBM1J9:-KHx091VMIUR17-0qP3O:171239163) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4b0b835b0e6bbc5209eafea6e466ac07e20660/drake/util/test/testPolynomial.cpp#L156)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Wait ... that can't be right! If you use an undefined macro you'll get an error message. For it to work the way you said it would either have to be defined as something empty (where?), or (maybe more likely) the code you changed didn't actually get compiled for some reason, or it failed but the error wasn't noticeable somehow.</details>
OK after poking around a bit, I was able to get an compile-time error saying `GTEST_EXPECT_NEAR` is undefined. I'm not sure why I didn't get an error before, but one thing I did change was disable documentation generation, which significantly reduced the amount of text printed to the screen. 

I've marked this thread as being satisfied so it should not be a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2370#-:-KHxD5tGfEP18tUyl4aZ:-1868698381)*

**Pull request merged**
