### PR TITLE
multibody: Implement PlanarJoint

### PR DESCRIPTION
**Pull request by mpetersen94**
Adds a 3 dof planar joint that allows motion in the xy plane and rotation about the z-axis of the parent frame.

- [x] Requires #13711 

Towards #12404
Relates #12401

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13747)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@RussTedrake or @amcastro-tri for feature review.  Either wait for #13711 to merge or only review the second commit (the first is a copy of #13711 and will be rebased once that merges).

**Comment by mpetersen94** [comment]
___
*[multibody/tree/planar_joint.h, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13747#-MD2DYgZ507HB05pWkEi:-MDB1qPR0_y9N3ZmiiqD:b7d990p) ([raw file](https://github.com/robotlocomotion/drake/blob/07b9a574fa5e79bde11e7cfc3517519b68e6edae/multibody/tree/planar_joint.h#L24)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

those are the configurations, not the states.
</blockquote></details>

Doesn't adding the rates make it state?

**Comment by RussTedrake** [comment]
___
*[multibody/tree/planar_joint.h, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13747#-MD2DYgZ507HB05pWkEi:-MDB9EVMBl507NJLVmro:bxsnw63) ([raw file](https://github.com/robotlocomotion/drake/blob/07b9a574fa5e79bde11e7cfc3517519b68e6edae/multibody/tree/planar_joint.h#L24)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Doesn't adding the rates make it state?
</blockquote></details>

oops.  my bad.  i withdraw my comment.

**Comment by mpetersen94** [comment]
I've added most of the changes and am rewriting the tests to match the updated API as we speak!  Should have it back for review by lunch.

**Comment by mpetersen94** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
