### PR TITLE
Remove Windows documentation.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3685)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FYI to any other readers, a `mex -setup` step got removed here also for all platforms, but it seems like a correct improvement.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3685#-:-KTKlOTX4CTKfwz6JIIb:b-en3eoz)*

**Comment by jwnimmer-tri** [comment]
:lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: :lgtm: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3685#-:-KTKlVsanb7uANKsuScV:bvrz1r)*

**Comment by liangfok** [comment]
There are numerous images in https://github.com/RobotLocomotion/drake/tree/master/drake/doc/images/windows_install. Should they be removed with this PR since this PR removes the `.rst` file that references them?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3685#-:-KTKoc2diGbLEiZEBLSt:b-ru97bk)*

**Comment by david-german-tri** [comment]
Done.

---

Review status: 8 of 12 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3685#-:-KTKqSZdccgwrcAbdEBX:b-896fix)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3685)*

**Comment by liangfok** [comment]
+@liangfok :lgtm: 

---

Reviewed 8 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3685#-:-KTKrDqRBoB2gSJM2LNR:bkgbgk3)*

**Pull request merged**
