### PR TITLE
Remove gurobi, mosek, and snopt from CMake build

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6474)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
I suspect at some point we will want CMake configuration options that govern the Bazel `--config` that gets shelled out to (and those options would appear to the user to be very much like the options we're ditching here), but I don't think this PR is the right place to add them.

:lgtm: +@soonho-tri for platform review.

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6474#-:-KnousAxvT9b83SXWtiY:bui93cs)*

**Comment by soonho-tri** [comment]
:lgtm: 

BTW, don't we need to update https://github.com/RobotLocomotion/drake/blob/master/tools/bazel.rc#L81-L82 ?

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6474#-:-KnqjJ4-ivxSl6YNUITS:bote0jg)*

**Comment by jamiesnape** [comment]
Done.

---

Review status: 17 of 22 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6474#-:-Knqp0s8F9U2Bgnp8cYd:b-896fix)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6474)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6474#-:-KnqqEt6rnYlgY4UbxNK:bnfp4nl)*

**Pull request merged**
