### PR TITLE
[render_gltf_client] Actually test something in the acceptance test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In support of #21894.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22008)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22008#-:-O8mH2QXBiEQtMfSVi18:bxqo58p)* status: needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
Oops.. X1

+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22008#-:-O8mH9JIBhfbZG4B_zIU:baoqlcm)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22008#-:-O8mMojh5puQpYN1lNU2:b8qx53o)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Pull request merged**
