### PR TITLE
Remove examples/dev

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This removes `Hubo`, `Manipulator2D`, `mass_spring_damper`.

The `dev` folder signifies experimental work, and we'll not (immediately) be porting it forward to the new bindings.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6234)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.  I'll wait to assign feature / platform review until after that.

**Comment by jwnimmer-tri** [comment]
-(status: do not merge)
+@sherm1 for all review, please.

**Comment by sherm1** [comment]
:lgtm:

---

Review status: 0 of 118 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6234#-:-Kldal54smgCkPKXAOtk:bnfp4nl)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 118 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6234#-:-KleLxSZEWyLJU7HU9Sr:bnfp4nl)*

**Pull request merged**
