### PR TITLE
Update show_rgb documentation

### LINKED ISSUE #20957: Multiple `CameraConfig`s with reused renderers do not `show_rgb` correctly
### What happened?

When instantiating multiple cameras with the same render engine, enabling `show_rgb` generates "flickering" behavior from the display window. This comes in 2 variants. If both cameras have `show_rgb` enabled, the window flickers back and forth between the 2 (or more) views. If only one camera has `show_rgb` enabled, the window flickers open and closed.

To reproduce apply this diff
```
diff --git a/examples/hardware_sim/example_scenarios.yaml b/examples/hardware_sim/example_scenarios.yaml
index a033ed6847..29cc2b6843 100644
--- a/examples/hardware_sim/example_scenarios.yaml
+++ b/examples/hardware_sim/example_scenarios.yaml
@@ -52,9 +52,16 @@ Demo:
   cameras:
     oracular_view:
       name: camera_0
+      show_rgb: true
       X_PB:
         translation: [1.5, 0.8, 1.25]
         rotation: !Rpy { deg: [-120, 5, 125] }
+    secondary_view:
+      name: camera_1
+      show_rgb: true
+      X_PB:
+        translation: [1.5, 0.8, 0.25]
+        rotation: !Rpy { deg: [-120, 5, 125] }
   model_drivers:
     iiwa: !IiwaDriver
       hand_model_name: wsg
```
and run `bazel run //examples/hardware_sim:demo_cc`

### Version

295eb0f07591f932e06ffd5c3576b51409ebfd7d

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by zachfang**
Close #20957

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21018)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review, to confirm if the updated doc aligns with your image viewer road map.

CC @dmcconachie-tri

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21018#-:-NrGpmLOB44A1qWp92Or:bn4km9m)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

**Comment by jwnimmer-tri** [comment]
I agree that it makes sense to clarify the API docs to explain what does and doesn't work about the setting as currently implemented, and/or to provide guidance about when it's the most effective / ineffective.

I don't really want to point the general public the replacement tool until it's officially supported (part of releases, documented, etc.).

If you think it makes sense, I think it would be OK to point people to the tracking issue for #18862.

**Review by zachfang — COMMENTED** [review]
I tweaked the documentation to state that the flag (1) is for debug use, (2) has known issues, and (3) the proposal for visualizing images in the future.

> I don't really want to point the general public the replacement tool until it's officially supported (part of releases, documented, etc.).

My thought for mentioning `lcm_image_array_viewer` was to at least provide some utility before 18862 is ready because I imagine visualizing images is a very common need.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21018#-:-NrRskZoDGPI_s_EOar_:b-697q37)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: none)

:lgtm: feature.

+@sherm1 for platform review per schedule please.

> My thought for mentioning `lcm_image_array_viewer` was to at least provide some utility before 18862 is ready because I imagine visualizing images is a very common need.

Trying to explain the ever-changing, multi-caveated answer isn't appropriate for the Doxygen website.  If we want to teach people about work-arounds, then we can post into the issue text of 18862 to do that.  That way they can ask questions, and we can quickly fix up any advice that bitrots without cycling through the nightly website build.

Seeing live images is a fine need, but anyway if people are dealing with images, then they must have _some_ other tool that would show them.  The show_rgb is only a debug accelerator.  If they are making ML data sets, then then already must have the tooling to append the images to a dataset them with their ML image viewing tools, it's just maybe a slower test loop.  In other words, the need it not urgent.  In the extreme, they can use ImageWriter and dump them to a pile of `png` files on disk.  That's pretty easy to use, and works robustly.

Also I'm not convinced that most users would benefit from trying the current WIP tool.  TRI users already have better tools so it doesn't matter for them, and for non-TRI users in many cases building drake _from source_ and _installing flask_ will take a lot of time and struggle.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21018#-:-NrWescSE1qFE9kpeaef:b-q5hls6)* status: LGTM missing from assignee sherm1(platform)

**Review by zachfang — COMMENTED** [review]
> Trying to explain the ever-changing, multi-caveated answer isn't appropriate for the Doxygen website. If we want to teach people about work-arounds, then we can post into the issue text of 18862 to do that. That way they can ask questions, and we can quickly fix up any advice that bitrots without cycling through the nightly website build.

SGTM!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21018#-:-Nr_u2B4CAZ7ZTCHC4C8:beetm6p)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21018#-:-NraRKye6rGIdiXEYxm-:b8qx53o)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Pull request merged**
