### PR TITLE
Refactor symbolic classes by running clang-tidy

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5942)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

FYI, this PR does not provide any functional changes. I started using [clang-tidy](http://clang.llvm.org/extra/clang-tidy) and this PR is the result of the changes suggested by clang-tidy. Main changes include:

 - Match the parameter names in declarations (`.h`) and definitions (`.cc`).
 - Use `const std::shared_ptr<T>&` instead of `cosnt std::shared<T>`.
 - [No else after return](https://clang.llvm.org/extra/clang-tidy/checks/readability-else-after-return.html)
 - [pass-by-value-in-constructors](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html#pass-by-value-in-constructors). This is related to the item26 of "Effective Modern C++11".
 - [Use `auto` when its type is clearly inferable because of `static_cast`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-auto.html#cast-expressions)
 - Minor formatting changes by `clang-format`.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-:-KiaxNA59WJCbtMm4oOa:b1y166n)*

**Comment by hongkai-dai** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 811 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-Kib22gYsYk5YkkdwMLr:-Kib22gYsYk5YkkdwMLs:bwf4e0i) ([raw file](https://github.com/robotlocomotion/drake/blob/ac0bb38f51284c8f8468a8722115ff128c36ce83/drake/common/symbolic_expression.cc#L811)):*
> ```cpp
> MatrixX<Expression> Jacobian(const Eigen::Ref<const VectorX<Expression>>& f,
>                              const vector<Variable>& vars) {
>   DRAKE_DEMAND(!vars.empty());
> ```

Sorry for my ignorance, is it because vars.empty() is atomic, so supposedly faster than checking vars.size() >0?

---

*[drake/common/symbolic_expression_cell.cc, line 566 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-Kib2azZLKaRUoQWIADB:-Kib2azZLKaRUoQWIADC:b-id3j0c) ([raw file](https://github.com/robotlocomotion/drake/blob/ac0bb38f51284c8f8468a8722115ff128c36ce83/drake/common/symbolic_expression_cell.cc#L566)):*
> ```cpp
> ExpressionAddFactory::ExpressionAddFactory(
>     const double constant, map<Expression, double> expr_to_coeff_map)
>     : constant_{constant}, expr_to_coeff_map_{std::move(expr_to_coeff_map)} {}
> ```

Why using `std::move` is better than using a const reference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5942)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 811 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-Kib22gYsYk5YkkdwMLr:-Kib3qL3fxic9LLZ6OGW:b4d32rn) ([raw file](https://github.com/robotlocomotion/drake/blob/ac0bb38f51284c8f8468a8722115ff128c36ce83/drake/common/symbolic_expression.cc#L811)):*
> The emptiness of a container should be checked using the empty() method instead of the size() method. It is not guaranteed that size() is a constant-time function, and it is generally more efficient and also shows clearer intent to use empty().

https://clang.llvm.org/extra/clang-tidy/checks/readability-container-size-empty.html

---

*[drake/common/symbolic_expression_cell.cc, line 566 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-Kib2azZLKaRUoQWIADB:-Kib42p54JQlZNCv6LhO:bs2ypzw) ([raw file](https://github.com/robotlocomotion/drake/blob/ac0bb38f51284c8f8468a8722115ff128c36ce83/drake/common/symbolic_expression_cell.cc#L566)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why using `std::move` is better than using a const reference?
</blockquote></details>

First of all this topic is explained in item 41 of "Modern Effective C++11". Let me try to explain it with my own words though.

Consider the following example which uses the old `const T&` pattern:

```c++
class Person {
public:
    Person(const std::string& name) : name_{name} {}

private:
    std::string name_;
}

int main() {
     std::string name = "Drake";
     Person p1(name);
     Person p2(name + "!");
}
```

In this example, `name_` field of `Person` class is copy-constructed in both cases `p1` and `p2`. 
The main motivation of the new pattern is to *move-construct* `name_` for the `p2` case. 

Let's consider the new code:

```c++
class Person {
public:
    Person(std::string name) : name_{std::move(name)} {}

private:
    std::string name_;
}

int main() {
     std::string name = "Drake";
     Person p1(name);
     Person p2(name + "!");
}
```

 - For `p1` case, in the constructor `Person(std::string name)`, `name` is *copy-constructed* and then *moved* to `name_` because of `std::move`. There is no real advantage here in a sense that both of old and new patterns have the same number of copy operation.

 - For `p2` case, in the constructor `Person(std::string name)`, `name` is *move-constructed* and then *moved* to `name_` because of `std::move`. Note that there is zero copy-operations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5942)*

**Comment by hongkai-dai** [comment]
:lgtm: +@ggould-tri for platform review please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression_cell.cc, line 566 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-Kib2azZLKaRUoQWIADB:-KibFsq5muX0vJ4eWh6y:b-kz6xz0) ([raw file](https://github.com/robotlocomotion/drake/blob/ac0bb38f51284c8f8468a8722115ff128c36ce83/drake/common/symbolic_expression_cell.cc#L566)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

First of all this topic is explained in item 41 of "Modern Effective C++11". Let me try to explain it with my own words though.

Consider the following example which uses the old `const T&` pattern:

```c++
class Person {
public:
    Person(const std::string& name) : name_{name} {}

private:
    std::string name_;
}

int main() {
     std::string name = "Drake";
     Person p1(name);
     Person p2(name + "!");
}
```

In this example, `name_` field of `Person` class is copy-constructed in both cases `p1` and `p2`. 
The main motivation of the new pattern is to *move-construct* `name_` for the `p2` case. 

Let's consider the new code:

```c++
class Person {
public:
    Person(std::string name) : name_{std::move(name)} {}

private:
    std::string name_;
}

int main() {
     std::string name = "Drake";
     Person p1(name);
     Person p2(name + "!");
}
```

 - For `p1` case, in the constructor `Person(std::string name)`, `name` is *copy-constructed* and then *moved* to `name_` because of `std::move`. There is no real advantage here in a sense that both of old and new patterns have the same number of copy operation.

 - For `p2` case, in the constructor `Person(std::string name)`, `name` is *move-constructed* and then *moved* to `name_` because of `std::move`. Note that there is zero copy-operations.

</blockquote></details>

Thanks for the explanation, that is very clear! I should go to read Modern Effective C++11

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-:-KibG3LPrxXE5bblLnxB:b-9ir12m)*

**Comment by ggould-tri** [comment]
:lgtm: with one issue below.

---

Reviewed 2 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.clang-tidy, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-KiePeEQPsVM3MrkPZHI:-KiePeEQPsVM3MrkPZHJ:b-miekbq) ([raw file](https://github.com/robotlocomotion/drake/blob/ac0bb38f51284c8f8468a8722115ff128c36ce83/.clang-tidy#L2)):*
> ```
> ---
> Checks: 'clang-diagnostic-*,clang-analyzer-*,cppcoreguidelines-*,google-*,modernize-*,performance-*,readability-*,-modernize-use-using,-modernize-use-bool-literals,-readability-named-parameter,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-type-static-cast-downcast,-modernize-use-transparent-functors'
> ```

Per discussion on #platform-review, this should use `-readability-else-after-return` to enable author's discretion on that feature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-:-Kie8kzVZpc9bO0ChfYK:b-d2srp3)*

**Comment by soonho-tri** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[.clang-tidy, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-KiePeEQPsVM3MrkPZHI:-KieSAz4Dm7cj7R1oF4W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ac0bb38f51284c8f8468a8722115ff128c36ce83/.clang-tidy#L2)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Per discussion on #platform-review, this should use `-readability-else-after-return` to enable author's discretion on that feature.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5942)*

**Comment by ggould-tri** [comment]
Although this is green to merge, I suggest giving this one a couple of hours for the discussion on #platform_review to get opinions from the PAL crowd.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5942#-:-KieVMypqlONBKu0GebJ:burujni)*

**Pull request merged**
