### PR TITLE
[geometry/dev] cleanup gltf UpdateViewpoint transform modification

### PR DESCRIPTION
**Pull request by svenevs**
Document how / why the UpdateViewpoint transform modification needs to happen, and mark when it can be removed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16533)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
Per discussion [on slack](https://drakedevelopers.slack.com/archives/C02HMU7B15Y/p1644028193640599), this seems to be the cleanest way to do this.  It seems possible to instead operate on a `RotationMatrix<double>` and `Eigen::Vector3d` translation directly, but the overhead in comparison is negligible and I believe this explicit implementation is a lot clearer to potential future readers.

:lgtm: :slightly_smiling_face: 

+@zachfang for feature review please.

CC @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16533#-:-MvLDj723_aIpNPoMZq_:bj6cdyt)* status: LGTM missing from assignee zachfang, missing label for release notes (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: I think the explanation is great! Thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16533#-:-MvRtW2A1LwqftJHVVfZ:bnub590)* status: 1 unresolved discussion (waiting on @svenevs)

___
*[geometry/render/dev/render_client_gltf.cc, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16533#-MvRt3hv5m3tlZZSnQlD:-MvRsbVKDwsNpAvnGPjl:blpcgao) ([raw file](https://github.com/robotlocomotion/drake/blob/74c9afcc026ae98e06436b16b57b1a4c82711ea8/geometry/render/dev/render_client_gltf.cc#L138)):*
> ```cpp
>    https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8883
> 
>    When VTK is updated, this method override in the header, as well as the
> ```

nit: this method `overrides` or `overridden`, or the `override method`? Not sure my grammar is correct : -)

**Review by svenevs — COMMENTED** [review]
OK great!  :lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16533#-:-MvUPdjjELImw4Si-Zko:bq7b09r)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @zachfang)

___
*[geometry/render/dev/render_client_gltf.cc, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16533#-MvRt3hv5m3tlZZSnQlD:-MvUPgrc9p59X9YkC4xt:b-es2kjx) ([raw file](https://github.com/robotlocomotion/drake/blob/74c9afcc026ae98e06436b16b57b1a4c82711ea8/geometry/render/dev/render_client_gltf.cc#L138)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: this method `overrides` or `overridden`, or the `override method`? Not sure my grammar is correct : -)  
</blockquote></details>

OK.  Yes, that verbiage was awkward.  I have updated it to just say

```
When VTK is updated, RenderClientGltf::UpdateViewpoint, can be deleted as
RenderEngineVtk::UpdateViewpoint will correctly update the transforms on the
cameras.
```

That work for you?

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16533)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @svenevs)

___
*[geometry/render/dev/render_client_gltf.cc, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16533#-MvRt3hv5m3tlZZSnQlD:-MvUjgmR60DWGIVIrtqI:b-85i63v) ([raw file](https://github.com/robotlocomotion/drake/blob/74c9afcc026ae98e06436b16b57b1a4c82711ea8/geometry/render/dev/render_client_gltf.cc#L138)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

OK.  Yes, that verbiage was awkward.  I have updated it to just say

```
When VTK is updated, RenderClientGltf::UpdateViewpoint, can be deleted as
RenderEngineVtk::UpdateViewpoint will correctly update the transforms on the
cameras.
```

That work for you?
</blockquote></details>

LGTM.

**Pull request merged**
