### PR TITLE
introduce System::SetRandomContext and friends

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7192)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@sammy-tri for feature review.  (please assign platform review to soonho if you're happy with this; would like to catch him today if possible).  

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-:-Kvg-mvVGYQYDXvtXx6A:bwhj842)*

**Comment by soonho-tri** [comment]
+@soonho-tri for platform review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-:-KvgK4M1OXgZhIXNU3l3:bxw8cpy)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 385 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-Kvh2dmv0BAev8UWAq7K:-Kvh2dmwX2SkwyOF6JJu:bq1pk80) ([raw file](https://github.com/robotlocomotion/drake/blob/222ec1785a6c3a95325582e84402a312283335f7/drake/systems/framework/diagram.h#L385)):*
> ```objc
>     DRAKE_DEMAND(diagram_state != nullptr);
> 
>     // Set default state of each constituent system.
> ```

copy/pasted comment (I think?)...   at any rate it doesn't seem accurate here

---

*[drake/systems/framework/diagram.h, line 401 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-Kvh2u-9koVSR5ZlxQdX:-Kvh2u-9koVSR5ZlxQdY:b-x1wxcw) ([raw file](https://github.com/robotlocomotion/drake/blob/222ec1785a6c3a95325582e84402a312283335f7/drake/systems/framework/diagram.h#L401)):*
> ```objc
>     int abstract_parameter_offset = 0;
> 
>     // Set default state of each constituent system.
> ```

see above re: "default state" in comment

---

*[drake/systems/framework/system.h, line 207 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-Kvh15EtJQKKoJOfWWOt:-Kvh15EtJQKKoJOfWWOu:baz754j) ([raw file](https://github.com/robotlocomotion/drake/blob/222ec1785a6c3a95325582e84402a312283335f7/drake/systems/framework/system.h#L207)):*
> ```objc
>   /// Overrides must not change the number of state variables.
>   virtual void SetRandomState(const Context<T>& context, State<T>* state,
>                       RandomGenerator* generator) const {
> ```

odd indentation

---

*[drake/systems/framework/test/diagram_test.cc, line 1969 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-Kvh3uBF81shrlC9EvnK:-Kvh3uBF81shrlC9EvnL:bf7pj8v) ([raw file](https://github.com/robotlocomotion/drake/blob/222ec1785a6c3a95325582e84402a312283335f7/drake/systems/framework/test/diagram_test.cc#L1969)):*
> ```cpp
> }
> 
> class RandomContextTestSystem : public LeafSystem<double> {
> ```

BTW it's only at two copies so far, so I can't claim rule of three, but consider moving this out into somewhere common...  or commenting in both places that the code is duplicated.  (apologies if I missed a subtle distinction between the two)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-:-Kvh4UrFIeIZ2JNciyQw:bvb1a6z)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 385 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-Kvh2dmv0BAev8UWAq7K:-Kvl9jpgJRP2XvIOmm9W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/222ec1785a6c3a95325582e84402a312283335f7/drake/systems/framework/diagram.h#L385)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

copy/pasted comment (I think?)...   at any rate it doesn't seem accurate here
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram.h, line 401 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-Kvh2u-9koVSR5ZlxQdX:-Kvl9jRq_yypB0iIyQ8f:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/222ec1785a6c3a95325582e84402a312283335f7/drake/systems/framework/diagram.h#L401)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

see above re: "default state" in comment
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 207 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-Kvh15EtJQKKoJOfWWOt:-Kvl9QIN_evMkuWlc22A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/222ec1785a6c3a95325582e84402a312283335f7/drake/systems/framework/system.h#L207)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

odd indentation
</blockquote></details>

Done.

---

*[drake/systems/framework/test/diagram_test.cc, line 1969 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-Kvh3uBF81shrlC9EvnK:-Kvl9KaPzxmwas3I8AcI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/222ec1785a6c3a95325582e84402a312283335f7/drake/systems/framework/test/diagram_test.cc#L1969)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW it's only at two copies so far, so I can't claim rule of three, but consider moving this out into somewhere common...  or commenting in both places that the code is duplicated.  (apologies if I missed a subtle distinction between the two)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7192)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-:-KvlzW_BBB_eGZxkjOAF:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7192#-:-Kvns229bmnW_K4LHNFp:bnfp4nl)*

**Pull request merged**
