### PR TITLE
Bump externals to latest upstream

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is just monthly hygiene.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8728)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Absent #8595, ping me when this is ready and I will update the mirrors.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for all review please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8728#-:-LBRT70R-TPWhQDqwsLH:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
FYI @jamiesnape new URLs are in use now.

**Pull request merged**
