### PR TITLE
Add libbz2-dev in ubuntu setup script

### PR DESCRIPTION
**Pull request by soonho-tri**
To fix the problem mentioned in #7416

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7418)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jamiesnape for feature-review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7418#-:-KyOAhCMjVbm7XETbV-_:bg4w8lp)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7418#-:-KyOBE7WrEaGy0TAywBg:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Comment by soonho-tri** [comment]
@BetsyMcPhail , could you add this change to the Ubuntu CI image(s)?

**Pull request merged**
