### PR TITLE
Refactoring in the Implicit Stribeck solver internals

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR only is a refactor, nothing new is introduced. It just factors out code into smaller blocks as a cleanup before I extend this to also solve for the normal forces (thus more Jacobian code).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8984)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for platform/feature review please (would we need feature for this? I wanna ease @edrumwri's workload and, considering this is just a refactor probably platform alone is just fine?)

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8984#-:-LEuqeof1PgCmgRB2r-5:bdhzik9)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with cosmetic notes

---

Reviewed 2 of 2 files at r1.
Review status: 2 unresolved discussions, platform LGTM from [seancurtis-tri], commit history needs curation

---

*[multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h, line 499 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8984#-LEusFqQ5idiiXTv1ZNH:-LEusFqQ5idiiXTv1ZNI:b42vjre) ([raw file](https://github.com/robotlocomotion/drake/blob/8e5d4a7576770ca825ff8fa4a19879695c6fb2a2/multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h#L499)):*
> ```objc
>       EigenPtr<VectorX<T>> v_slip,
>       EigenPtr<VectorX<T>> t_hat,
>       EigenPtr<VectorX<T>> mus,
> ```

Meta: Why is mu the only one pluralized? 

---

*[multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h, line 503 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8984#-LEusbXi3S5cFTbiZ7zW:-LEusbXi3S5cFTbiZ7zX:b-e7b6q3) ([raw file](https://github.com/robotlocomotion/drake/blob/8e5d4a7576770ca825ff8fa4a19879695c6fb2a2/multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h#L503)):*
> ```objc
> 
>   // Helper to compute gradient dft_dvt = ∇ᵥₜfₜ(vₜ), as a function of the
>   // normal forces fn, friction coefficient mus, tangent versors t_hat and
> ```

You've got plural-itis. normal forces and tangent versors are all plural, but firction coefficient and slip velocity is all single. It seems that you want it to be singular everywhere (with the understanding that the "single" value may be a vector.)

Having read through things, I see you have *two* mu values (the parameter passed into these functions and the parameter provided by `problem_data_aliases_`. I'm not sure what the relationship is, but I don't care for the obvious disparity in plurality on these parameters that should be the same.

---

*[multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8984#-LEutiMY4KRvHxRKEOFK:-LEutiMY4KRvHxRKEOFL:b37ozxb) ([raw file](https://github.com/robotlocomotion/drake/blob/8e5d4a7576770ca825ff8fa4a19879695c6fb2a2/multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc#L77)):*
> ```cpp
>   // "soft norm":
>   //    ‖v‖ₛ ≜ sqrt(vᵀv + εᵥ²)
>   // (in code εᵥ is named epsilon_v and εᵥ² is named epislon_v2). We use
> ```

BTW s/epislon_v2/epsilon_v2

---

*[multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8984#-LEuuE9YBWwQ68u0OMwe:-LEuuE9YBWwQ68u0OMwf:b-tfch5j) ([raw file](https://github.com/robotlocomotion/drake/blob/8e5d4a7576770ca825ff8fa4a19879695c6fb2a2/multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc#L178)):*
> ```cpp
>     // (P and Pperp) where the coefficients of the combination are positive
>     // scalars. Therefore,
>     // IMPORTANT NOTE: dft_dvt also PSD.
> ```

BTW "dft_dvt *is* also PSD.

---

*[multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc, line 189 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8984#-LEuuNWJ8uDDgf2v8ZHC:-LEuuNWJ8uDDgf2v8ZHD:bkz7xgn) ([raw file](https://github.com/robotlocomotion/drake/blob/8e5d4a7576770ca825ff8fa4a19879695c6fb2a2/multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc#L189)):*
> ```cpp
>     dft_dvt[ic] = Pperp_ic * mus(ic) / v_slip(ic);
> 
>     // Changes in the magnitude of vt (which in turns makes mu_stribeck
> ```

BTW oops, no "s" on turn

---

*[multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc, line 249 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8984#-LEuzwiw177zFv4jbyKj:-LEuzwiw177zFv4jbyKk:b7zfork) ([raw file](https://github.com/robotlocomotion/drake/blob/8e5d4a7576770ca825ff8fa4a19879695c6fb2a2/multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc#L249)):*
> ```cpp
>   statistics_.Reset();
> 
>   // If there are no contact points return a zero generalized friction forces
> ```

BTW s/forces/force

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8984#-:-LEv0bnF8a7yC-Q46ahk:b4q7lyz)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: 2 unresolved discussions, platform LGTM from [seancurtis-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8984)*

**Comment by amcastro-tri** [comment]
Review status: 2 unresolved discussions, platform LGTM from [seancurtis-tri], commit history needs curation

---

*[multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h, line 499 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8984#-LEusFqQ5idiiXTv1ZNH:-LEvD1Me4M2tOfNi9Syv:b-iy42ix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e5d4a7576770ca825ff8fa4a19879695c6fb2a2/multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h#L499)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Meta: Why is mu the only one pluralized? 
</blockquote></details>

Just a bad name we didn't care curating in the previous version. We already have `mu` as a variable for the actual (constant) friction coefficients. This is meant to store the value of the slip velocity dependent Stribeck friction coefficient. I renamed it to something more sensible.

---

*[multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h, line 503 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8984#-LEusbXi3S5cFTbiZ7zW:-LEvDpH7EKAgj6sH_bAW:b-ya5zor) ([raw file](https://github.com/robotlocomotion/drake/blob/8e5d4a7576770ca825ff8fa4a19879695c6fb2a2/multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h#L503)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You've got plural-itis. normal forces and tangent versors are all plural, but firction coefficient and slip velocity is all single. It seems that you want it to be singular everywhere (with the understanding that the "single" value may be a vector.)

Having read through things, I see you have *two* mu values (the parameter passed into these functions and the parameter provided by `problem_data_aliases_`. I'm not sure what the relationship is, but I don't care for the obvious disparity in plurality on these parameters that should be the same.
</blockquote></details>

I renamed `mus` to `mu_stribeck`, not a plural, just a bad variable name choice. I chose to pass parameters by argument to make it explicit that outputs from these methods depend on the given inputs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8984)*

**Comment by SeanCurtis-TRI** [comment]
Excellent

---

Reviewed 2 of 2 files at r3.
Review status: all discussions resolved, platform LGTM from [seancurtis-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8984#-:-LEyS9S81BfcX075GF6S:b-ryhtu7)*

**Comment by SeanCurtis-TRI** [comment]
-(status: curate commits before merging) 

---

Review status: all discussions resolved, platform LGTM from [seancurtis-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8984#-:-LEySGAa9wSI8No260nk:b-l70wzf)*

**Pull request merged**
