### PR TITLE
[workspace] Upgrade styleguide latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a non-functional change, because the upgrade only changes the documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15378)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Were you aware of #15381. Seems like one should be closed in the favor of the other (although I haven't explored which).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15378#-:-MeUtLyY5XzV6nA_ScuJ:b-cdmwkw)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
This PR is fine.  The other PR is "do not merge" and points to an unmerged branch, for the purposes of CI coverage.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15378)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
... and the styleguide change just merged.  I'll rework this now.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15378#-:-MeVKbAb5I2-WLcIAsFK:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
