### PR TITLE
[C-IRIS] move CspaceFreePolytope constructor out of dev folder.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18863)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for next Monday's platform review please, thanks!

I move the constructor CspaceFreePolytope out of the dev folder. It has been feature reviewed. Could you platform-review this file? Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-:-NP-uQz19RIWzSptM1hm:b3hjcd1)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: ; a few notes below.
+(release notes: feature) 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-:-NPIgE_-AODb4fPL86bg:b-9qn6up)* status: 6 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIssnc4g8_Fy873dZX:-NPIssnc4g8_Fy873dZY:bmcnmw7) (no related file):*
Is there a follow-up PR to move the unit test?  Moving the implementation without its corresponding test coverage is a bit surprising.

___
___
*[`geometry/optimization/cspace_free_polytope.cc` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIhR6ICaw1VhbhLLc2:-NPIhR6ICaw1VhbhLLc3:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L11)):*
> ```cpp
> namespace {
> // Returns true if all the bodies on the kinematics chain from `start` to `end`
> // are welded together (namely all the mobilizer in between are welded).
> ```

typo



_Suggestion:_
```cpp
mobilizers
```
___
*[`geometry/optimization/cspace_free_polytope.cc` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIhbE1Bj7SAXtMWHAq:-NPIhbE1Bj7SAXtMWHAr:b-62n41v) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L12)):*
> ```cpp
> // Returns true if all the bodies on the kinematics chain from `start` to `end`
> // are welded together (namely all the mobilizer in between are welded).
> [[nodiscard]] bool ChainIsWeld(const multibody::MultibodyPlant<double>& plant,
> ```

typo: grammar -- "is welded" seems more fluent.



_Suggestion:_
```cpp
 ChainIsWelded(c
```
___
*[`geometry/optimization/cspace_free_polytope.cc` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIkJEl7Vr2ETc15Bgq:-NPIkJEmCrVHskFDWya4:b3jby3i) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L78)):*
> ```cpp
> 
> // Returns the number of y_slack variables in `rational`.
> int GetNumY(const symbolic::RationalFunction& rational,
> ```

minor:  The name `GetNumY` is not at all descriptive of what the function does; it's particularly confusing given the explicit `Vector3`, and the common just restates the content of the function without explaining it.
Also this function is only ever used for its zero/nonzero return, so it could easily return bool (and return instead of incrementing count, for a small performance improvement.
Finally, the actual logic of this function mostly already exists in `Variables` so it could probably be more clearly written as a one-liner.
As a sketch, you could for instance write something like
```
bool FunctionContainsVar(const symbolic::RationalFunction& rational, const Vector3<symbolic::Variable>& vars) {
  return !rational.numerator().indeterminates().intersect(symbolic::Variables(vars)).empty();
}
```
___
*[`geometry/optimization/cspace_free_polytope.cc` line 118 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIoWNA33Xy9DHjBROg:-NPIoWNA33Xy9DHjBROh:ba1xe5e) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L118)):*
> ```cpp
>     std::array<VectorX<symbolic::Monomial>, 4>* monomial_basis_array) {
>   auto it = map_body_to_monomial_basis_array->find(body_pair);
>   if (it == map_body_to_monomial_basis_array->end()) {
> ```

minor:  For readability, consider using `count` or `contains` for membership checking.

Alternatively, if you are relying on the iterator position for the hinting performance of the later `emplace_hint` call, `it` is not a sufficiently descriptive variable name.



_Suggestion:_
```cpp
  if (!map_body_to_monomial_basis_array->contains(body_pair)()) {
```
___
*[`geometry/optimization/cspace_free_polytope.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIq31oBERMkhnbyNNk:-NPIq31oBERMkhnbyNNl:b536l7e) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L158)):*
> ```cpp
>     }
>     it = map_body_to_monomial_basis_array->emplace_hint(it, body_pair,
>                                                         *monomial_basis_array);
> ```

minor:
(1) assigning to `it` seems unnecessary, as it is being discarded.
(2) I don't see any basis for hinting the end of the list for the emplace; if we expect the body pairs to be visited in order, that should be mentioned in the function comment, but nothing at the call site suggests that this is the case.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18863)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIssnc4g8_Fy873dZX:-NPJ1mc_3m_0V0GcqjBV:bm0x9qj) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Is there a follow-up PR to move the unit test?  Moving the implementation without its corresponding test coverage is a bit surprising.
</blockquote></details>

Yes, there is a follow-up PR to move the unit test. Doing it all in one PR can make the PR size too large. (I tried to put the test code in one PR, but easily exceed 800 LOC).

___
___
*[`geometry/optimization/cspace_free_polytope.cc` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIhR6ICaw1VhbhLLc2:-NPJ8Yp660yyOve1fEHe:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L11)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`geometry/optimization/cspace_free_polytope.cc` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIhbE1Bj7SAXtMWHAq:-NPJ8gHiBD5boDYQx64c:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L12)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

typo: grammar -- "is welded" seems more fluent.
</blockquote></details>

Done.
___
*[`geometry/optimization/cspace_free_polytope.cc` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIkJEl7Vr2ETc15Bgq:-NPJ9LoS7lu0Df2Oohv_:b-fbdu7r) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L78)):*
> Also this function is only ever used for its zero/nonzero return, so it could easily return bool (and return instead of incrementing count, for a small performance improvement.

It is only used in its zero/nonzero return in the code that gets moved out from `dev` folder. In the code that still lives in the `dev` folder, it uses the actual integer value of the return, not just the boolean value.

I re-named the function and add some documentation. Is it better now?
___
*[`geometry/optimization/cspace_free_polytope.cc` line 118 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIoWNA33Xy9DHjBROg:-NPJAXim0CjP0fccuU-i:bk4w3g8) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L118)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  For readability, consider using `count` or `contains` for membership checking.

Alternatively, if you are relying on the iterator position for the hinting performance of the later `emplace_hint` call, `it` is not a sufficiently descriptive variable name.
</blockquote></details>

Done. I changed the variable name to `body_pair_it`.
___
*[`geometry/optimization/cspace_free_polytope.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIq31oBERMkhnbyNNk:-NPJB5sx6YY_E0Ge92K4:b66h97p) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L158)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:
(1) assigning to `it` seems unnecessary, as it is being discarded.
(2) I don't see any basis for hinting the end of the list for the emplace; if we expect the body pairs to be visited in order, that should be mentioned in the function comment, but nothing at the call site suggests that this is the case.
</blockquote></details>

Done. I removed the return.

I use emplace_hint with the end of list because we have tried to find this key in the map but hasn't found it yet. In this case I suppose we should emplace it at the end?

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18863)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIkJEl7Vr2ETc15Bgq:-NPJIV7o-PG2S_UKKAEB:bb71kmx) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L78)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> Also this function is only ever used for its zero/nonzero return, so it could easily return bool (and return instead of incrementing count, for a small performance improvement.

It is only used in its zero/nonzero return in the code that gets moved out from `dev` folder. In the code that still lives in the `dev` folder, it uses the actual integer value of the return, not just the boolean value.

I re-named the function and add some documentation. Is it better now?
</blockquote></details>

Okay
___
*[`geometry/optimization/cspace_free_polytope.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIq31oBERMkhnbyNNk:-NPJI_-g80aMhg07pzM2:b6kqquy) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L158)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I removed the return.

I use emplace_hint with the end of list because we have tried to find this key in the map but hasn't found it yet. In this case I suppose we should emplace it at the end?
</blockquote></details>

Hinting is useful when the iterator is at the correct insertion point; in this case because of the check on line 118 you know that `it` was at the end, so that's what you were hinting.  Because `unordered_map` is implemented as a sorted list, this will be more efficient than `emplace` if you know that the item you are adding is in fact the greatest element, and (slightly) slower otherwise.
So the case elsewhere in this PR where it hints `end()` and is in fact always inserting a new greatest element (because it traverses the pairs in order) is correct.
In this case, I can't see a good argument for why the new element will be last.
Regardless it doesn't matter very much -- the savings and costs are small for a small map.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18863)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIq31oBERMkhnbyNNk:-NPJMsFCDPmrVmtTpwlG:b33ljkt) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L158)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry I think I missed something, I thought that `unordered_map` is <b> not </b> sorted, it doesn't even require the key in the map to be comparable, so how to implement `unordered_map` as a sorted list?
</blockquote></details>

Oh, you're right, it's bucketed -- I had it confused.  But I think that's actually worse -- hinting `end()` will never be right in that case, I think?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18863)* status: needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18863#-NPIq31oBERMkhnbyNNk:-NPJNFzJ9RulZ64b05cK:b-4u28rf) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5919838e43d89087910259e270bd1bb2a37b7e4/geometry/optimization/cspace_free_polytope.cc#L158)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Oh, you're right, it's bucketed -- I had it confused.  But I think that's actually worse -- hinting `end()` will never be right in that case, I think?
</blockquote></details>

I see, after reading the answer in this stackoverflow question https://stackoverflow.com/questions/22800405/when-do-you-use-stdunordered-mapemplace-hint I think I understand it better.

I also modified the other emplace_hint to emplace in this file.

**Pull request merged**
