### PR TITLE
[workspace] Flag sdformat, ignition_math, ignition_utils as internal

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We are substantially patching these libraries to weave them into Drake. We should not give the illusion to users that they are available for reuse downstream.

Also take this opportunity to track the ignition => gz project rename.

Towards #17231.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17303)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17303#-:-N3_tQZA5MAXDRDCJ0VX:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17303#-N3_ssHdCp-Y3_AWAk1u:-N3_ssHdCp-Y3_AWAk1v:bd4d2fj) (no related file):*
Do the `ignition_*`names in `tools/workspace/new_release.py` also need to change?

https://github.com/RobotLocomotion/drake/blob/9c9e57540876545172baf70ac955bdb497171227/tools/workspace/new_release.py#L68-L69=

___

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17303#-:-N3_xYuT7EkD3SwNQb6C:b-1krawd)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17303#-N3_ssHdCp-Y3_AWAk1u:-N3_xT7m3fahSjZoZHTR:b-iqe7hp) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Do the `ignition_*`names in `tools/workspace/new_release.py` also need to change?

https://github.com/RobotLocomotion/drake/blob/9c9e57540876545172baf70ac955bdb497171227/tools/workspace/new_release.py#L68-L69=
</blockquote></details>

Done.

Right you are.  I also missed qhull_internal in the prior PR, fixed here now as a follow-up.

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17303)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Is there a guideline for when we should be using `cc_library` vs `cc_library_vendored` for `_internal` packages?  If I tried to guess the difference between this an `qhull_internal`, I'd guess that it's something about when the package is only being used by libraries with `internal = True`, but also the onl;y user of `@qhull_internal` explicitly marks it as an implementation dependency.

> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17303#-:-N3a8Csq7MlGLLQx8CZC:boxtjwj)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 17 of 20 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17303)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Review by sammy-tri — COMMENTED** [review]
err, merge conflict

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17303#-:-N3aEqM585oFN5K4v7NY:b-fqkvwy)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
