### PR TITLE
[pydrake] Remove deprecated MeshcatVisualizerCpp 2022-11

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Likewise remove MeshcatPointCloudVisualizerCpp.

Follow-up from #17462.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18225)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews please, follow-up from #17462.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18225)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18225#-NFnewnX6QQGBS8YixYr:-NFnewnX6QQGBS8YixYs:b-slyh1j) (no related file):*
I'm seeing that symbol in our old favorite `examples/manipulation_station/end_effector_teleop_dualshock4.py`.

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: except for a stray

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18225#-:-NFnf6DF95BHQrVu7l8o:b-59cosl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18225)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18225)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18225#-NFnewnX6QQGBS8YixYr:-NFng4ur0Esrwi0QnT5O:b354xp0) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'm seeing that symbol in our old favorite `examples/manipulation_station/end_effector_teleop_dualshock4.py`.
</blockquote></details>

I'm shocked, _shocked_, that code without any CI tests is bitrotting.

(See what I did there?  I was dual-shocked.)

___

**Pull request merged**
