### PR TITLE
pybind cpp_param: Use type_info::name() for hashing, not ::hash_code(), due to Mac linking

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Supersedes #8704 

\cc @m-chaturvedi

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8706)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything-debug please.

**Comment by EricCousineau-TRI** [comment]
Adding "do not merge" pending non-required Mac CI

**Comment by EricCousineau-TRI** [comment]
+@m-chaturvedi for feature review, please.
+@sherm1 for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8706#-:-LB7Ai7v7z2PW920qfwH:b5o40dz)*

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8706#-:-LB7pDG51KhTwZmZqpds:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8706)*

**Pull request merged**
