### PR TITLE
Fix lights expressed in camera frame for RenderEngineVtk

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The old code misrepresented the device frame; it was incomplete. It flipped to left-handed when it is more accurate to rotate the around Cx 180 deg.

This also changes the light direction vector semantics. The input value need not be unit length, just normalizable. `RenderEngineVtk` had to change what it was doing, but `RenderEngineGl` was already doing this. Only its test was expanded to explicitly cover normalization.

This also provides a patch to VTK's rendering logic.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
This changes the reference color image for the "whole scene custom configuration".


[Original image]


[Updated image]


[The difference]

Note the addition of the rim light.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-:-NqUlMXI2UsIZPlVoWnB:bojcel9)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@joemasterjohn for feature review. Willing to dust off some of your graphics skills?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-:-NqZ0g_k4sdY3Ctv8GNI:b4a1jo6)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`tools/workspace/vtk_internal/repository.bzl` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-NqZHMu7CAmxzFfddsMZ:-NqZHMu7CAmxzFfddsM_:b-3koml7) ([raw file](https://github.com/RobotLocomotion/drake/blob/428ff17649c0fcbe4c4279572608acdd2794bed7/tools/workspace/vtk_internal/repository.bzl#L180)):*
> ```Starlark
>         patches = [
>             ":patches/common_core_version.patch",
>             ":patches/fix_illumination_bugs.patch",
> ```

If you want to see the impact of the patch, simply comment out this line and watch what happens to the lights.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with an ask for clarification in one of the comments. The vtk patch looks good. +@EricCousineau-TRI for platform review, please.

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-:-NqdQpS63RJaFU17BdTV:bclvtpy)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 587 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-NqdP4IxDFAsT9jp-wif:-NqdP4IxDFAsT9jp-wig:ba931ly) ([raw file](https://github.com/RobotLocomotion/drake/blob/674095146279c7deabe460335196d672f8b6016b/geometry/render_vtk/internal_render_engine_vtk.cc#L587)):*
> ```cpp
>     // Drake's camera frame C has the camera looking in the Cz direction (with
>     // Cx pointing right in the image and Cy down). The light parameters are
>     // expressed in that frame. VTK's camera is ultimately the *device* frame D.
> ```

I'm confused by this. It seems to imply that the VTK Camera frame C and device frame D are identical, but that's obviously not true. There's a rigid transform relationship between Drake's camera frame and VTK's camera frame X_CvtkCdrake and then the projection that goes from VTK's camera frame all the way to D (ultimately in normalized device coordinates.) correct? Maybe this could be clarified here to just say that you are transforming from Drake's camera frame to VTK's without mentioning the device frame D?



_Code quote:_
```cpp
 VTK's camera is ultimately the *device* frame D.
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 587 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-NqdP4IxDFAsT9jp-wif:-NqduJTa1kUuyvE7M6-2:b-nyqbg0) ([raw file](https://github.com/RobotLocomotion/drake/blob/674095146279c7deabe460335196d672f8b6016b/geometry/render_vtk/internal_render_engine_vtk.cc#L587)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I'm confused by this. It seems to imply that the VTK Camera frame C and device frame D are identical, but that's obviously not true. There's a rigid transform relationship between Drake's camera frame and VTK's camera frame X_CvtkCdrake and then the projection that goes from VTK's camera frame all the way to D (ultimately in normalized device coordinates.) correct? Maybe this could be clarified here to just say that you are transforming from Drake's camera frame to VTK's without mentioning the device frame D?
</blockquote></details>

Simplified. PTAL.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform!

> Reviewed 2 of 2 files at r1, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-:-NqdzRu17Szt_KOBjIAC:b-vtj4w1)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 587 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-NqdP4IxDFAsT9jp-wif:-NqhWFhk8xGR_QWbf8DJ:b-suujcu) ([raw file](https://github.com/RobotLocomotion/drake/blob/674095146279c7deabe460335196d672f8b6016b/geometry/render_vtk/internal_render_engine_vtk.cc#L587)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Simplified. PTAL.
</blockquote></details>

@joemasterjohn are you aware you're blocking?

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 587 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-NqdP4IxDFAsT9jp-wif:-NqhXziZ7VWkaYO-sXF1:bltp2kv) ([raw file](https://github.com/RobotLocomotion/drake/blob/674095146279c7deabe460335196d672f8b6016b/geometry/render_vtk/internal_render_engine_vtk.cc#L587)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@joemasterjohn are you aware you're blocking?
</blockquote></details>

My bad, unblocked now.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(type: feature request) +(release notes: fix) 

Feature is that the light directions don't have to be unit length. Fix is that the lights actually work. Arguably, the feature may not be worth emphasizing.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20930#-:-NqhYJZlDDUWtVqQ9f2G:b1w369h)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn

**Pull request merged**
