### PR TITLE
Add documentation to pydrake.multibody.* modules

### PR DESCRIPTION
**Pull request by jamiesnape**
This was partially reviewed in #9510 with a different notation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9571)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review.

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by jwnimmer-tri** [comment]
-@ggould-tri +@jwnimmer-tri for platform review.

**Comment by jamiesnape** [comment]
What fun....

GCC:
```error: 'doc' is not captured```

... capture lambda...

Clang:
```error: lambda capture 'doc' is not required to be captured for this use```

**Pull request merged**
