### PR TITLE
[doc] Add Thomas Cohn as a contributor.

### PR DESCRIPTION
**Pull request by cohnt**
+@RussTedrake for feature review?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21034)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for both reviews
+(status: single reviewer ok) 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21034#-:-NrNMXBl2iQqdHi4ZALF:bqsp8zm)* status: 1 unresolved discussion, LGTM missing from assignees sherm1(platform),RussTedrake(platform), missing label for release notes (waiting on @cohnt)

___
*[`doc/_pages/credits.md` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21034#-NrNMMZa31TVy1a4WAlm:-NrNMMZa31TVy1a4WAln:b-y9ddji) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab9ee65efd8e4e216db280736320baa63e77c4/doc/_pages/credits.md#L68)):*
> ```Markdown
> * Matthew Woehlke
> * Huihua Zhao
> * [Thomas Cohn](https://tommycohn.com/)
> ```

minor: this list is alphabetized. You should be up just above Rick Cory.

**Review by RussTedrake — COMMENTED** [review]
:lgtm: also, once you address Sherm's request.  your contributions are very much appreciated!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21034#-:-NrR9l_wClazI2vC0VvZ:b-mr52mu)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21034)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @cohnt)

___
*[`doc/_pages/credits.md` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21034#-NrNMMZa31TVy1a4WAlm:-NrRiluw-a-JR6Y4plLR:bhb54w) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab9ee65efd8e4e216db280736320baa63e77c4/doc/_pages/credits.md#L68)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this list is alphabetized. You should be up just above Rick Cory.
</blockquote></details>

Fixed! Sorry :)

**Review by jwnimmer-tri — COMMENTED** [review]
-@sherm1 
+(release notes: none) 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21034#-:-NrWFEczEfntWWCt6ImH:b-aoee08)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee RussTedrake(platform)

**Pull request merged**
