### PR TITLE
[parsing] Error out if <drake:diffuse_map> is specified in a URDF

### PR DESCRIPTION
**Pull request by zachfang**
Toward #18844 

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066)

### CODE REVIEW

**Comment by zachfang** [comment]
@SeanCurtis-TRI @jwnimmer-tri This is my initial attempt to add some clarity when specifying a texture map in URDF. Also, if either of you would like to be the feature reviewer assuming the changes make sense to you.

**Comment by SeanCurtis-TRI** [comment]
+@SeanCurtis-TRI  I'll take feature

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'm not persuaded that *all* of the changes in this PR are necessary or even desirable. The changes to *code* seem to be solving a non-existent problem.

1. The new code guards against the usage of a non-URDF tag in a URDF file. That's generally a problem we don't tackle.
    - Of course, if we're generally validating the XML against a schema, then I take that back. But I assume we're not, or this tag would already cause an error/warning to be dispatched.
2. The *particular* tag you're guarding against is [explicitly defined](https://drake.mit.edu/doxygen_cxx/group__multibody__parsing.html#tag_drake_diffuse_map) as applying to `SDFormat` but *not* `URDF`. So, I wouldn't predict that a user would have the expectation that this tag works in a URDF. I'm open to being persuaded otherwise.

The portion of this PR where you clarify that the offending tag only applies to SDF has the greatest value.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-:-NR_729zCQwRs-FuE_A2:bgx3xy1)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

___
*[`multibody/parsing/parsing_doxygen.h` line 425 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-NR_7wSA66arBfsSsqnf:-NR_7wSA66arBfsSsqng:b-l9n27f) ([raw file](https://github.com/RobotLocomotion/drake/blob/4b08c035c5cce225e3a923b30650264658f74edd/multibody/parsing/parsing_doxygen.h#L425)):*
> ```objc
> to use as a diffuse texture map. The resolved path name is stored in a
> PerceptionProperties object under `(phong, diffuse_map)`. URDF provides a
> built-in tag, i.e., <texture>, to specify a diffuse texture map for a link.
> ```

nit: Instead of just "<texture>", I'd provide the full path(s) as is done for the SDFormat path above:

`//robot/material/texture` or `//robot/link/visual/material/texture`

**Comment by jwnimmer-tri** [comment]
> ... if we're generally validating the XML against a schema ... I assume we're not, or this tag would already cause an error/warning to be dispatched.

That's right; in URDF we don't validate yet.  See #16997.  \CC @rpoyner-tri FYI

> The new code guards against the usage of a non-URDF tag in a URDF file. That's generally a problem we don't tackle.

Given the lack of schema validation, in principle it's OK for us to add specific warnings to mitigate user confusion.  The only question is: do we think this is a mistake a user could plausibly make?  If yes, we should warn.  If no, you're right that we could skip it here with the hope of #16997 down the line.

> The particular tag you're guarding against is [explicitly defined](https://drake.mit.edu/doxygen_cxx/group__multibody__parsing.html#tag_drake_diffuse_map) as applying to SDFormat but not URDF. So, I wouldn't predict that a user would have the expectation that this tag works in a URDF. I'm open to being persuaded otherwise.

That page is really difficult to use.  I don't think we can rely on users consulting or understanding it.

Do we think someone might take some SDFormat example text and paste it into the URDF file?  Seems plausible enough to me, and the "fix" here is pretty cheap.

**Review by SeanCurtis-TRI — COMMENTED** [review]
If we think there is a credible possibility of someone injecting that tag into a URDF file, then I say a response is good. Do we have any evidence that this has ever happened?

If we decide to respond, I'd suggest that we should raise an error and not a warning. The warning makes sense for a valid URDF with tags Drake doesn't handle yet -- "Hey! Nice URDF. Sorry, I can't do that right now."  In this case, they've gone out of their way to create a generally *invalid* URDF for the express purpose of making Drake happy. There's no reason we should let them just continue on their merry way in that case. They should simply fix their URDF and limit the potential for future copypasta.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-:-NR_EQeL6a2BbIBlSqJz:b-99sw9v)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
> So, I wouldn't predict that a user would have the expectation that this tag works in a URDF. I'm open to being persuaded otherwise.

I am probably a bit biased on that as I did try to add that tag after viewing some SDFormat examples when I was rendering a URDF/xacro file and found out the documentation later on.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-:-NRZ0qjCCVXv64p7wj54:b-h6fwm9)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Then I'd suggest that's a slam dunk. We do have evidence that this has happened. And if it can happen to you, it can happen to anyone.

So, back to my suggestion about changing the nature of the response.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-:-NR_Gkom1_e21YVtC6qJ:b-tegd)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Comment by jwnimmer-tri** [comment]
> If we decide to respond, I'd suggest that we should raise an error and not a warning.

I'll defer to @rpoyner-tri on the policy here.  I can live with it either way.

**Review by rpoyner-tri — COMMENTED** [review]
Having a few specific cases covered until #16997 is done is not a terrible outcome. Such code has happened before. ( /me blesses without actually reviewing. )

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-:-NRcpT3DCdexm3KG7tyy:b1km2ss)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Comment by zachfang** [comment]
OK. I will summarize the above discussions as follows:
(1) Continue this PR as an intermedia "fix".
(2) Throw a parser **error** instead of a warning.
(3) Might remove the code if 16997 lands in the future.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`multibody/parsing/parsing_doxygen.h` line 425 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-NR_7wSA66arBfsSsqnf:-NRdLAncCr5nb3ZV587J:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4b08c035c5cce225e3a923b30650264658f74edd/multibody/parsing/parsing_doxygen.h#L425)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Instead of just "<texture>", I'd provide the full path(s) as is done for the SDFormat path above:

`//robot/material/texture` or `//robot/link/visual/material/texture`
</blockquote></details>

Done.
___
*[`multibody/parsing/test/detail_urdf_geometry_test.cc` line 750 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-NRdLDLmEMvqt815FewR:-NRdLDLmEMvqt815FewS:b-8jh64o) ([raw file](https://github.com/RobotLocomotion/drake/blob/f8f3f479b1c0507969f90c1e7aa0f0ea17ba85a6/multibody/parsing/test/detail_urdf_geometry_test.cc#L750)):*
> ```cpp
>         <visual name='hello'>
>           <geometry><box size='1 2 3'/></geometry>
>           <material><drake:diffuse_map>abc.png</drake:diffuse_map></material>
> ```

FYI. I changed to the actual SDFormat syntax to specify the diffuse map, which was exactly what I did before. :sweat_smile: 



_Code quote:_
```cpp
<material><drake:diffuse_map>abc.png</drake:diffuse_map></material>
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-:-NRdTiLv4khZwBnomR9b:bmxilld)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`multibody/parsing/detail_urdf_geometry.cc` line 142 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-NRdSVoeCg0FWG4hybax:-NRdSVoeCg0FWG4hybay:bckrs7o) ([raw file](https://github.com/RobotLocomotion/drake/blob/f8f3f479b1c0507969f90c1e7aa0f0ea17ba85a6/multibody/parsing/detail_urdf_geometry.cc#L142)):*
nit: Instead of explicitly proposing the built-in tag, I'd include an html to the tag information.


> <drake:diffuse_map> is not supported in URDF. See https://drake.mit.edu/doxygen_cxx/group__multibody__parsing.html#tag_drake_diffuse_map for more details.

This means that whatever we want to say about it, we only have to say it one place. Plus, they might become aware of documentation from which they could learn other stuff.
___
*[`multibody/parsing/parsing_doxygen.h` line 425 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-NR_7wSA66arBfsSsqnf:-NRdSxln8_dfLuFURqfC:b-r3pqe7) ([raw file](https://github.com/RobotLocomotion/drake/blob/4b08c035c5cce225e3a923b30650264658f74edd/multibody/parsing/parsing_doxygen.h#L425)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For a URDF both paths I provided above are valid definitions of `<texture>`. I think you probably want to include both.
___
*[`multibody/parsing/test/detail_urdf_geometry_test.cc` line 750 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-NRdLDLmEMvqt815FewR:-NRdT8X6CpvFg8JYzZeb:b87cew1) ([raw file](https://github.com/RobotLocomotion/drake/blob/f8f3f479b1c0507969f90c1e7aa0f0ea17ba85a6/multibody/parsing/test/detail_urdf_geometry_test.cc#L750)):*
An interesting choice.

It might be worth making of note of what you're modeling. Something like:

> This models a user that copies <drake:diffuse> from an sdf file verbatim (so it maintains SDFormat style instead of URDF).

Otherwise, it's possible that someone reading that in the future would say, "Why does this URDF look like SDF?"

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-:-NRdY5rR3EON7hAOESzj:bqljb9l)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri and @zachfang)

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`multibody/parsing/detail_urdf_geometry.cc` line 142 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-NRdSVoeCg0FWG4hybax:-NRdnZ353bzMVRIlwZxY:bt0owyg) ([raw file](https://github.com/RobotLocomotion/drake/blob/f8f3f479b1c0507969f90c1e7aa0f0ea17ba85a6/multibody/parsing/detail_urdf_geometry.cc#L142)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Instead of explicitly proposing the built-in tag, I'd include an html to the tag information.


> <drake:diffuse_map> is not supported in URDF. See https://drake.mit.edu/doxygen_cxx/group__multibody__parsing.html#tag_drake_diffuse_map for more details.

This means that whatever we want to say about it, we only have to say it one place. Plus, they might become aware of documentation from which they could learn other stuff.
</blockquote></details>

Done. I can merge the second and third lines together if the formatting looks prettier.
___
*[`multibody/parsing/parsing_doxygen.h` line 425 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-NR_7wSA66arBfsSsqnf:-NRdnSMn12Ex_VIaF0Xi:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4b08c035c5cce225e3a923b30650264658f74edd/multibody/parsing/parsing_doxygen.h#L425)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

For a URDF both paths I provided above are valid definitions of `<texture>`. I think you probably want to include both.
</blockquote></details>

Done.
___
*[`multibody/parsing/test/detail_urdf_geometry_test.cc` line 750 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-NRdLDLmEMvqt815FewR:-NRdnVqT6eT3dMeJilja:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f8f3f479b1c0507969f90c1e7aa0f0ea17ba85a6/multibody/parsing/test/detail_urdf_geometry_test.cc#L750)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

An interesting choice.

It might be worth making of note of what you're modeling. Something like:

> This models a user that copies <drake:diffuse> from an sdf file verbatim (so it maintains SDFormat style instead of URDF).

Otherwise, it's possible that someone reading that in the future would say, "Why does this URDF look like SDF?"
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-:-NReDnILCEJqHtqUelOk:bnfp4nl)* status: missing label for release notes (waiting on @zachfang)

**Review by rpoyner-tri — COMMENTED** [review]
-(release notes: feature) +(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19066#-:-NReKOMf03PnOOsyc82A:b-rtv606)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @zachfang)

**Pull request merged**
