### PR TITLE
Add cast method to Transform class

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7970)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@amcastro-tri 
Platform review +@sammy-tri 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7970#-:-L4ggM_jq50cCKEF1CSo:bohk43p)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm: (pending feature review)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7970#-:-L4h9AuGydG2nqycxZlz:b-2kq7o9)*

**Comment by amcastro-tri** [comment]
:lgtm: @mitiguy, please notice the repeated line of code in `GetAsMatrix4()`

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7970#-L4iC6L86rewUtLx84wj:-L4iC6L86rewUtLx84wk:b-1clh9v) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4fae1a67671b2a24af958e31d88ed0aedb3152/multibody/multibody_tree/math/rotation_matrix.h#L8)):*
> ```objc
> #include "drake/common/drake_copyable.h"
> #include "drake/common/eigen_types.h"
> #include "drake/common/never_destroyed.h"
> ```

BTW interesting, I would've thought the linter would complain?

---

*[multibody/multibody_tree/math/transform.h, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7970#-L4iEcQ8c6ou-brEDQVZ:-L4iEcQ8c6ou-brEDQV_:b-wk8p77) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4fae1a67671b2a24af958e31d88ed0aedb3152/multibody/multibody_tree/math/transform.h#L119)):*
> ```objc
>   void set_translation(const Vector3<T>& p) { p_AoBo_A_ = p; }
> 
>   /// Returns the 4x4 matrix associated with a %Transform.
> ```

BTW "a %Transform" --> "`this` %Trasform"

---

*[multibody/multibody_tree/math/transform.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7970#-L4iErEnuOXQ7quneVQc:-L4iErEnuOXQ7quneVQd:b98ion5) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4fae1a67671b2a24af958e31d88ed0aedb3152/multibody/multibody_tree/math/transform.h#L120)):*
> ```objc
> 
>   /// Returns the 4x4 matrix associated with a %Transform.
>   /// @returns the 4x4 matrix associated with a %Transform, i.e., returns
> ```

BTW "a %Transform" --> "`this` %Trasform `X_AB`" 

---

*[multibody/multibody_tree/math/transform.h, line 127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7970#-L4iDSjMgV9SRRpZNNa3:-L4iDSjMgV9SRRpZNNa4:b-tdz2gt) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4fae1a67671b2a24af958e31d88ed0aedb3152/multibody/multibody_tree/math/transform.h#L127)):*
> ```objc
>   ///  └                ┘
>   Matrix4<T> GetAsMatrix4() const {
>     Matrix4<T> pose;
> ```

BTW here you can actually do `pose.topLeftCorner<3, 3>()` since you know the size at compile time.

---

*[multibody/multibody_tree/math/transform.h, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7970#-L4iDe2XsoV1LI_gRaF5:-L4iDe2Yi_uroMbN7fuq:b-yvol1k) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4fae1a67671b2a24af958e31d88ed0aedb3152/multibody/multibody_tree/math/transform.h#L129)):*
> ```objc
>     Matrix4<T> pose;
>     pose.topLeftCorner(3, 3) = rotation().matrix();
>     pose.topLeftCorner(3, 3) = rotation().matrix();
> ```

BTW line copied twice

---

*[multibody/multibody_tree/math/transform.h, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7970#-L4iDrq52UKiMZctvsgM:-L4iDrq52UKiMZctvsgN:bh9wjd7) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4fae1a67671b2a24af958e31d88ed0aedb3152/multibody/multibody_tree/math/transform.h#L130)):*
> ```objc
>     pose.topLeftCorner(3, 3) = rotation().matrix();
>     pose.topLeftCorner(3, 3) = rotation().matrix();
>     pose.topRightCorner(3, 1) = translation();
> ```

BTW `topRightCorner<3, 1>()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7970#-:-L4iF5YQw9TwL1NGV4Nj:b7nb7pd)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7970)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/math/transform.h, line 130 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7970#-L4iDrq52UKiMZctvsgM:-L4ky_sSAIyqcDp_wXEm:bx6a5ex) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4fae1a67671b2a24af958e31d88ed0aedb3152/multibody/multibody_tree/math/transform.h#L130)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW `topRightCorner<3, 1>()`
</blockquote></details>

BTW  there is nothing wrong with this. We just tend to use the "known-at-compile-time-size" methods since Eigen optimizes them. So I guess I should've used FYI.
The reason it didn't work for you I am pretty sure is because you forgot to add the `.template`. So you'd need to do `pose.template topLeftCorner<3, 3>()`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7970)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/math/transform.h, line 130 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7970#-L4iDrq52UKiMZctvsgM:-L4kzHyJ9Xh7gpotykE3:b-8rh3xf) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4fae1a67671b2a24af958e31d88ed0aedb3152/multibody/multibody_tree/math/transform.h#L130)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW  there is nothing wrong with this. We just tend to use the "known-at-compile-time-size" methods since Eigen optimizes them. So I guess I should've used FYI.
The reason it didn't work for you I am pretty sure is because you forgot to add the `.template`. So you'd need to do `pose.template topLeftCorner<3, 3>()`
</blockquote></details>

BTW, context for @sammy-tri, this is in reply to a question regarding this comment from @mitiguy by email. 
Questions were:
- what is wrong with this?
- why is it that your suggestion didn't work for me?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7970)*

**Pull request merged**
