### PR TITLE
Remove spurious "too small step" messages from implicit integrator.

### PR DESCRIPTION
**Pull request by edrumwri**
If the continuous state advanced by the turbo integrator veered into NaN territory (due to overflow from expected occasional divergence in the Newton-Raphson process), reusing the Jacobian matrix (which, naturally, would become NaN as well) would cause any step size to fail. This PR fixes that issue.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6448)

### CODE REVIEW

**Comment by avalenzu** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 313 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-Knj2fz5pvMljEORC4sH:-Knj2fz5pvMljEORC4sI:bis0osa) ([raw file](https://github.com/robotlocomotion/drake/blob/cb1e1962c12f5a1799acaddd835571566bfc2e4d/drake/systems/analysis/implicit_euler_integrator-inl.h#L313)):*
> ```objc
>   using std::isnan;
> 
>   return (isnan(J.norm()));
> ```

BTW just curious, is there a reason to prefer `isnan(J.norm())` over `J.allFinite()` in this case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448)*

**Comment by edrumwri** [comment]
+@avalenzu for feature review please

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 313 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-Knj2fz5pvMljEORC4sH:-Knj9XB80m4nvBi7IdV1:b-n9ocxm) ([raw file](https://github.com/robotlocomotion/drake/blob/cb1e1962c12f5a1799acaddd835571566bfc2e4d/drake/systems/analysis/implicit_euler_integrator-inl.h#L313)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW just curious, is there a reason to prefer `isnan(J.norm())` over `J.allFinite()` in this case?
</blockquote></details>

BTW No, your suggestion is much more reasonable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-KnjCYZWW5wyDQXcCEbp:b-qss0xd)*

**Comment by avalenzu** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 311 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-KnjF9uEdQyrQR_JYs2b:-KnjF9uEdQyrQR_JYs2c:b-rdh91h) ([raw file](https://github.com/robotlocomotion/drake/blob/d8350c63d08e0f7913354b7367ab508465bf3deb/drake/systems/analysis/implicit_euler_integrator-inl.h#L311)):*
> ```objc
> template <class T>
> bool ImplicitEulerIntegrator<T>::IsBadJacobian(const MatrixX<T>& J) const {
>   using std::isnan;
> ```

This `using` statement is no longer necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448)*

**Comment by avalenzu** [comment]
LGTM once the unneeded `using` statement is removed.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-Knjd5c4cKjHYDPM7BXT:b7cmc1w)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by edrumwri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 311 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-KnjF9uEdQyrQR_JYs2b:-Knk6GqOLaYzB-tTEQK6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d8350c63d08e0f7913354b7367ab508465bf3deb/drake/systems/analysis/implicit_euler_integrator-inl.h#L311)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

This `using` statement is no longer necessary.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-KnkAVC3jYu12DkX34ns:bnfp4nl)*

**Comment by edrumwri** [comment]
Thanks Andres!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-KnkKjFETqd5a6JuS3AJ:b-x06p16)*

**Comment by edrumwri** [comment]
+@soonho-tri for platform review, per regular rotation

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-KnoE8v5OKv6b3Lt6waM:b-ayhsbj)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-KnoFd3e1DAhLZ_yN_cw:bkd1jye)*

**Comment by soonho-tri** [comment]
:lgtm:

BTW, could you check the title of this PR? It doesn't seem to be related to the changes.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 327 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-Knop4ftMIRdJ-U9oO8I:-Knop4ftMIRdJ-U9oO8J:b-f2a4tz) ([raw file](https://github.com/robotlocomotion/drake/blob/3432e4d8fef945f68773e70de3963fb9ad152f02/drake/systems/analysis/implicit_euler_integrator-inl.h#L327)):*
> ```objc
>   // rationale for the negation below) and factor them, if necessary.
>   if (!reuse_ || J_.rows() == 0 || IsBadJacobian(J_)) {
>     J_ = CalcJacobian(tf, xtplus);
> ```

Thanks for the comments in the Slack. I think it's worth adding the following here for future debugging efforts:
```c++
DRAKE_ASSERT(!IsBadJacobian(J_));
```
or add a comment section (copy/paste from the discussion) explaining why this is not bad again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-KnopjPSf4cCiM1oxsOD:b-u114ok)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448)*

**Comment by edrumwri** [comment]
Although strange, it is exactly descriptive. When this problem occurs, overflow causes the step size to continue decreasing until it can decrease no further, at which point an exception is thrown with the corresponding too small message.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/analysis/implicit_euler_integrator-inl.h, line 327 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-Knop4ftMIRdJ-U9oO8I:-KnoyOOWCnUdr-vN6VJn:buy12n9) ([raw file](https://github.com/robotlocomotion/drake/blob/3432e4d8fef945f68773e70de3963fb9ad152f02/drake/systems/analysis/implicit_euler_integrator-inl.h#L327)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Thanks for the comments in the Slack. I think it's worth adding the following here for future debugging efforts:
```c++
DRAKE_ASSERT(!IsBadJacobian(J_));
```
or add a comment section (copy/paste from the discussion) explaining why this is not bad again.
</blockquote></details>

Done. The assertion is not sufficient, because the Jacobian may temporarily become bad (this should be a sufficiently rare occurrence that I do not believe special code is warranted for speeding the detection and eliminating some unnecessary computation).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-KnowtGYu0KZEqm27zzt:b-nwhywl)*

**Comment by soonho-tri** [comment]
Thanks for explanations. The added comment helped my understanding.

:lgtm: 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-Knp0RLtvAc2nDf497Y2:b-myw1zj)*

**Comment by edrumwri** [comment]
Thanks for the excellent reviews Andres and Soonho!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6448#-:-Knp4nD2bqS1BDNfCr6U:b-pissm2)*

**Pull request merged**
