### PR TITLE
Add symbolic support to maliput/api/lane_data

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7642)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jadecastro for feature-review, please.

/cc @maddog-tri , the author of Maliput APIs.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7642#-:-L0jc3o8uxItl4aO1RsO:bva4w8t)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7642#-:-L0kOQVD4ycjJKQrMizr:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@sammy-tri for platform-review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7642#-:-L0kOqelEMZYcDpDMGEK:b-3ojlqy)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7642#-:-L0kUOwcl6oS3XilNyvb:bnfp4nl)*

**Pull request merged**
