### PR TITLE
[visualization] Meldis displays point cloud data

### PR DESCRIPTION
**Pull request by zachfang**
This PR is a re-apply of a previous commit, #18774, with a fix for a unit test.

Investigation:
EDIT: The root cause is the indeterministic order of `FrameId` when constructing `lcmt_viewer_load_robot` messages. The test depends on two LCM messages to be encoded exactly the same to pass its test objectives.

~~I haven't fully grasped what the root cause is, but one of the LCM message comparisons behaves differently due to the order of a field, i.e., `lcmt_viewer_load_robot.link`.~~ This is an example from: https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/visualization/_meldis.py#L102
```
(message.encode() == self._load_message.encode()) yields `false` when it should be `true`.

b'\x89\x87 \x9b\x10\xaa-9\x00\x00\x00\x02\x00\x00\x00\x16plant::acrobot::Link1\x00\x00\x00\x00\x02\x00\x00\x00\x02\x03\x00\x00\x00\x00\x00\x00\x00\x00\xbf\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x02=L\xcc\xcd?\x8c\xcc\xcd\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00?\x80\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x01>\x00\x00\x00\x00\x00\x00\x16plant::acrobot::Link2\x00\x00\x00\x00\x02\x00\x00\x00\x01\x03\x00\x00\x00\x00\x00\x00\x00\x00\xbf\x80\x00\x00?\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x02=L\xcc\xcd@\x06ff'
vs.
b'\x89\x87 \x9b\x10\xaa-9\x00\x00\x00\x02\x00\x00\x00\x16plant::acrobot::Link2\x00\x00\x00\x00\x02\x00\x00\x00\x01\x03\x00\x00\x00\x00\x00\x00\x00\x00\xbf\x80\x00\x00?\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x02=L\xcc\xcd@\x06ff\x00\x00\x00\x16plant::acrobot::Link1\x00\x00\x00\x00\x02\x00\x00\x00\x02\x03\x00\x00\x00\x00\x00\x00\x00\x00\xbf\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x02=L\xcc\xcd?\x8c\xcc\xcd\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\x80\x00\x00?\x80\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x01>\x00\x00\x00'
```

Oddly, if I comment out some of the point cloud tests, the order will then be the same, and it seems persistent.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896)

### CODE REVIEW

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
Good observation!

The problem is here:

https://github.com/RobotLocomotion/drake/blob/54667de5c2df601ddb3ca4b2fced0d7f21ec91e3/geometry/scene_graph_inspector.cc#L22-L27

We need to sort the vector prior to returning it, so that all visualizers show things in a well-defined order, not an unordered_map hash bucket order.

**Comment by zachfang** [comment]
Tested locally on mac and Ubuntu machines.

@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
The PR title is not accurate.  The subject here should be like "[visualization] Meldis displays point cloud data".

The PR description text can explain that this is a re-apply with some fixes.

**Review by zachfang — COMMENTED** [review]
Fixing a lint issue now (waiting for the local `--config=lint //...` result).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-:-NPNoD8A-fpv4aVgg9wf:b384zmr)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-:-NPNuwZhCEIO-oHCU4Wp:bli80v6)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: feature) 

:lgtm: +(status: single reviewer ok) given that the new code here is just a couple lines of new code (modulo comment grammar fixes).

Just one question for @SeanCurtis-TRI below.

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-:-NPNvZPc17-JC_wj_X09:b4y4ldz)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[`geometry/scene_graph_inspector.cc` line 28 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-NPNvPFC5IMXyinLfy-2:-NPNvPFDDQq39lB6Sx8U:b8wdswz) ([raw file](https://github.com/RobotLocomotion/drake/blob/44184affa516b2ca41f16afc36b805b6ce861161/geometry/scene_graph_inspector.cc#L28)):*
> ```cpp
>   typename GeometryState<T>::FrameIdRange range = state_->get_frame_ids();
>   std::vector<FrameId> frame_ids(range.begin(), range.end());
>   std::sort(frame_ids.begin(), frame_ids.end());
> ```

@SeanCurtis-TRI I'm not sure if we need a unit test for this, nor if we did how we'd go about making a useful one.

Are you OK merging this PR as-is?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[`geometry/scene_graph_inspector.cc` line 28 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-NPNvPFC5IMXyinLfy-2:-NPNyuS33lEVAMsppNxP:b-a8r4ts) ([raw file](https://github.com/RobotLocomotion/drake/blob/44184affa516b2ca41f16afc36b805b6ce861161/geometry/scene_graph_inspector.cc#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@SeanCurtis-TRI I'm not sure if we need a unit test for this, nor if we did how we'd go about making a useful one.

Are you OK merging this PR as-is?
</blockquote></details>

I'm inclined to do so:

The documentation says that order is *not* guaranteed. However, we now have code that is relying on that.

I'd suggest we update the documentation and add a unit test.

The unit test should be simple enough. @zachfang let me know if you'd like me to push a commit.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[`geometry/scene_graph_inspector.cc` line 28 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-NPNvPFC5IMXyinLfy-2:-NPNzsQfEEBpxfMwmvMb:blggqkd) ([raw file](https://github.com/RobotLocomotion/drake/blob/44184affa516b2ca41f16afc36b805b6ce861161/geometry/scene_graph_inspector.cc#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm inclined to do so:

The documentation says that order is *not* guaranteed. However, we now have code that is relying on that.

I'd suggest we update the documentation and add a unit test.

The unit test should be simple enough. @zachfang let me know if you'd like me to push a commit.


</blockquote></details>

In that case, how about this: @SeanCurtis-TRI will open a PR that incorporates this hunk as well as his proposed additional updates.  We merge that, then circle back here after a rebase.

**Comment by SeanCurtis-TRI** [comment]
*[`geometry/scene_graph_inspector.cc` line 28 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-NPNvPFC5IMXyinLfy-2:-NPO-Wob5zMd6E8H3enS:bb0cbe5) ([raw file](https://github.com/RobotLocomotion/drake/blob/44184affa516b2ca41f16afc36b805b6ce861161/geometry/scene_graph_inspector.cc#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In that case, how about this: @SeanCurtis-TRI will open a PR that incorporates this hunk as well as his proposed additional updates.  We merge that, then circle back here after a rebase.
</blockquote></details>

Alright. Give me a few minutes.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[`geometry/scene_graph_inspector.cc` line 28 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-NPNvPFC5IMXyinLfy-2:-NPOSjlh3io_q5spAi64:b-icn8fv) ([raw file](https://github.com/RobotLocomotion/drake/blob/44184affa516b2ca41f16afc36b805b6ce861161/geometry/scene_graph_inspector.cc#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Alright. Give me a few minutes.
</blockquote></details>

Sorry for the delay. Meetings.

#18903

As long as I was imparting order to one API that returned a vector of ids, I made sure all of the APIs had good ordering as well.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[`geometry/scene_graph_inspector.cc` line 28 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-NPNvPFC5IMXyinLfy-2:-NPQ4q6j-HKtkMl2yT8_:b-t79t38) ([raw file](https://github.com/RobotLocomotion/drake/blob/44184affa516b2ca41f16afc36b805b6ce861161/geometry/scene_graph_inspector.cc#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Sorry for the delay. Meetings.

#18903

As long as I was imparting order to one API that returned a vector of ids, I made sure all of the APIs had good ordering as well.
</blockquote></details>

Merged now.  Ready for a rebase here.

**Comment by zachfang** [comment]
Working. Rebase now.

**Review by zachfang — COMMENTED** [review]
My understanding is to squash into one commit as there isn't much left after the rebase. Let me know otherwise.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-:-NPNwgzA1byxzX73DMyu:bedgkqm)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Comment by zachfang** [comment]
Run the faster mac CI to be on the safe side.
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-:-NPQB91J1rvk7w7KvQtQ:b-85g6de)* status: 2 unresolved discussions (waiting on @zachfang)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-NPQB23S7P9ZHLEhND6X):*
nit Be sure we remove the old/wrong number "18874"  in the commit message when we merge this.  We only want the new number (18896).

**Review by zachfang — COMMENTED** [review]
All tests passed. Looks like there is still an unintended blocking comment.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-:-NPQFnQg8EVL3H02SxVi:bzho2uv)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18896#-NPQB23S7P9ZHLEhND6X):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Be sure we remove the old/wrong number "18874"  in the commit message when we merge this.  We only want the new number (18896).
</blockquote></details>

OK. Will do.

**Pull request merged**
