### PR TITLE
Fix long test timeouts

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2295)

### CODE REVIEW

**Comment by jamiesnape** [comment]
For context, some tests that were guarded with `if (0)` were changed to `if (LONG_RUNNING_TESTS)` and have either always failed or always timed out since `LONG_RUNNING_TESTS` were enabled on CI.

**Comment by jamiesnape** [comment]
@jwnimmer-tri Could you review if @david-german-tri is unavailable? This should fix the Linux / MATLAB continuous job.

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> @jwnimmer-tri Could you review if @david-german-tri is unavailable? This should fix the Linux / MATLAB continuous job.</details>


---

Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Atlas/runAtlasHandControl.m, line 180 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2295#-KHLd09UUJj75m2yi7dk:-KHLd09UUJj75m2yi7dl:-2005970447) ([raw file](https://github.com/robotlocomotion/drake/blob/9a87643b6f71d6faa21cd79854eb136213e684df/drake/examples/Atlas/runAtlasHandControl.m#L180)):*
> ```objc
> end
> 
> % TIMEOUT 3000
> ```

do these comments have an effect on something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2295#-:-KHLdDayUlKBfxQ_6dgw:1417088721)*

**Comment by jamiesnape** [comment]
Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Atlas/runAtlasHandControl.m, line 180 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2295#-KHLd09UUJj75m2yi7dk:-KHLdbCgGYtNyYPOETom:534853883) ([raw file](https://github.com/robotlocomotion/drake/blob/9a87643b6f71d6faa21cd79854eb136213e684df/drake/examples/Atlas/runAtlasHandControl.m#L180)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> do these comments have an effect on something?</details>
They used to, but not entirely sure if they still do given how much the way MATLAB tests run has changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2295)*

**Pull request merged**
