### PR TITLE
Python bind SpatialInertia::SolidBoxWithMass().

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19172)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/19172 is work to helping resolve part of issue https://github.com/RobotLocomotion/drake/issues/18416.

**Review by mitiguy — COMMENTED** [review]
Feature review +@DamrongGuoy  (after it passes CI).
Please also do Platform review. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19172#-:-NShlh0TEsDoiFMBEO50:b-uai4ck)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

I'm not a platform reviewer, so +@rpoyner-tri for platform review tomorrow (Tuesday).

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19172#-:-NShrikn6wb7hyLUPZgc:bh9cber)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
+(status: squashing now) 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19172#-:-NSlBA9K0QdWACg2HQix:b-9kn1by)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),DamrongGuoy (waiting on @mitiguy)

**Comment by jwnimmer-tri** [comment]
For the record, this little 5-line PR has a non-zero cost for release engineers.  The #19141 was already pretty small (~100 lines).  Maybe next time do the new function and the bindings in the same PR?  It would be lot easier for reviewers and release managers.

Or failing that, use "release notes: none" for PRs like this with bindings that appear within the same release cycle as the new C++ function.

**Comment by DamrongGuoy** [comment]
@mitiguy,  what you described is the opposite of what @jwnimmer-tri asked, which is what I like too.

Right now you are doing this:
PR1 five  C++ functions
PR2 five python bindings

@jwnimmer-tri asked that:
PR1 2 C++ functions + 2 python bindings
PR2 2 C++ functions + 2 python bindings
PR3 1 C++ function + 1 python binding

It would satisfy my need as well if we have both C++ SolidBoxWithMass() and its python binding in the same PR.

We are trying to make Python bindings our first-class citizens for the benefit of the user majority.

I wonder whether we have Style Guide advising that C++ and Python should preferably sync in the same PR?

**Comment by DamrongGuoy** [comment]
Sounds good to me.  First do C++ API until everybody agrees, then add Python binding in the same PR.

Perhaps the reviewer should, then, set `status:do not merge` until python binding is available.

**Comment by jwnimmer-tri** [comment]
I think we can leave it up to the PR author how exactly to handle the code review logistics.  For some people, keeping the Python and C++ in sync from the first draft onward is not onerous, so we shouldn't be too prescriptive about the mechanism.  The more important point is the result to aim for, i.e., that for a new public API typically Python bindings happen concurrently or almost-concurrently with the C++ API.

> @jwnimmer-tri asked that:
> PR1 2 C++ functions + 2 python bindings
> PR2 2 C++ functions + 2 python bindings
> PR3 1 C++ function + 1 python binding

To be precise, I suggested just one PR with all 5 function in both C++ and Python.  The reason to split into multiple PRs would be if the lines of code blew through the 1500 ceiling, which the "inertia of primitive shape" functions and test did not.

**Pull request merged**
