### PR TITLE
Actually fix storage and visibility for generated integer constants

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A follow-up on #3222:
- Add a missed kConstant from the original PR (sorry!).
- Now that I've merged the visibility fixes, we need EXPORT ornaments on the struct.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3233)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
As with the prior PR:
+@rpoyner-tri for feature review, please.
+@david-german-tri for platform review, please.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3233#-:-KPt72wL6Y1VXC5_XhV2:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3233#-:-KPt7z0duC-KEChIhPdY:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
This is an example of a very slow pre-merge check.  Right now it has "Build has been executing for 53 min" and it's still not even started to run the tests yet.

**Comment by jwnimmer-tri** [comment]
@david-german-tri 
For the record, the final result of msvc pre-merge build was:
```
Started 1 hr 35 min ago
Took 1 hr 6 min
```
https://drake-jenkins.csail.mit.edu/job/experimental/4012/compiler=msvc-ninja-32,label=windows,type=debug/consoleFull

This appears to just be slowness throughout; I don't see that any initial start-up operation was spectacularly slow.

**Pull request merged**
