### PR TITLE
Hydro margin parsing support

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
This will need some doc xref adjustments once #21809 is merged.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-:-O4lw78iEzrllBM14ZuJ:b-94n2cu)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
FYI @joemasterjohn @amcastro-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-:-O4lxebZ7QD9_O_AfYV2:b-35p0si)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_common.cc` line 125 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O4lw_s36YUSMDRuqKJe:-O4lw_s36YUSMDRuqKJf:b8wcu9v) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9860cc08b6385876b5020d0bdd31a2b0f0422d9/multibody/parsing/detail_common.cc#L125)):*
> ```cpp
>       throw std::logic_error(
>           fmt::format("The dissipation time scale can't be negative; given {}",
>                       *dissipation));
> ```

nit the old code here was definitely wrong, and not tested. This motivated a mild rewrite, mostly to tighten up variable scopes with in the function body.
___
*[`multibody/parsing/detail_sdf_geometry.h` line 171 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O4lxIyb8CUlXNWSK4Y_:-O4lxIyb8CUlXNWSK4Ya:b-1pnbqc) ([raw file](https://github.com/RobotLocomotion/drake/blob/50f8e0072c138df6ae9eade719bab4c73c94374f/multibody/parsing/detail_sdf_geometry.h#L171)):*
> ```objc
>  | drake:mesh_resolution_hint       | hydroelastic | resolution_hint           | Required for shapes that require tessellation to support hydroelastic contact.                                                   |
>  | drake:hydroelastic_modulus       | hydroelastic | hydroelastic_modulus      | Finite positive value. Required for compliant hydroelastic representations.                                                      |
>  | drake:hydroelastic_margin        | hydroelastic | margin                    | Finite nonnegative value. XXX ??? Optional. XXX
> ```

Need to verify the value limits and logic.
___
*[`multibody/parsing/parsing_doxygen.h` line 592 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O4lxTyuAPGdAtBNEMOD:-O4lxTyuAPGdAtBNEMOE:b-djflkk) ([raw file](https://github.com/RobotLocomotion/drake/blob/50f8e0072c138df6ae9eade719bab4c73c94374f/multibody/parsing/parsing_doxygen.h#L592)):*
> ```objc
> @ref hydro_model_parameters "Hydroelastic contact parameters",
> @ref hug_properties
> XXX are references correct, complete, useful?g
> ```

Waiting for other doc to land from #21809, then will update references.
___
*[`multibody/parsing/test/detail_sdf_geometry_test.cc` line 1228 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O4lwxm03ZQg5clKqh4_:-O4lwxm03ZQg5clKqh4a:b-65wu8g) ([raw file](https://github.com/RobotLocomotion/drake/blob/50f8e0072c138df6ae9eade719bab4c73c94374f/multibody/parsing/test/detail_sdf_geometry_test.cc#L1228)):*
> ```cpp
>     <drake:hunt_crossley_dissipation>4.5</drake:hunt_crossley_dissipation>
>     <drake:relaxation_time>3.1</drake:relaxation_time>
>     <drake:mu_dynamic>4.25</drake:mu_dynamic>
> ```

minor adjustments here and below ensure that all of the arbitrary input values are distinct.
___
*[`multibody/parsing/test/detail_urdf_geometry_test.cc` line 681 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O4lxDjwDt-Ur7QGUZQV:-O4lxDjwDt-Ur7QGUZQW:b-65wu8g) ([raw file](https://github.com/RobotLocomotion/drake/blob/50f8e0072c138df6ae9eade719bab4c73c94374f/multibody/parsing/test/detail_urdf_geometry_test.cc#L681)):*
> ```cpp
>     <drake:hydroelastic_modulus value="3.5" />
>     <drake:hydroelastic_margin value="1.3" />
>     <drake:hunt_crossley_dissipation value="4.5" />
> ```

minor adjustments here and below ensure that all of the arbitrary input values are distinct.

**Review by rpoyner-tri — COMMENTED** [review]
-(status: do not merge) -(status: do not review)  +@joemasterjohn for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-:-O7ZznHy4VkXx52fG8SE:bplxdt2)* status: 3 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @rpoyner-tri)

**Review by joemasterjohn — COMMENTED** [review]
Pass done, PTAL.

> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-:-O7_MqNI2u6hknxoKPaS:b-k85idd)* status: 6 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_common.cc` line 125 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O4lw_s36YUSMDRuqKJe:-O7_MMi47e8HlZsmm5lx:bwx6cmq) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9860cc08b6385876b5020d0bdd31a2b0f0422d9/multibody/parsing/detail_common.cc#L125)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit the old code here was definitely wrong, and not tested. This motivated a mild rewrite, mostly to tighten up variable scopes with in the function body.
</blockquote></details>

See my note below on code coverage for proximity parsing failures.
___
*[`multibody/parsing/detail_common.cc` line 143 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_Mfiy5P3M1Q2JhvtC:-O7_Mfiy5P3M1Q2JhvtD:b-p97omv) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_common.cc#L143)):*
> ```cpp
>       if (*margin < 0) {
>         throw std::logic_error(fmt::format(
>             "The hydroelastic margin can't be negative; given {}", *margin));
> ```

Should this be strictly throwing? Or should we be using the `DiagnosticPolicy`? Here and elsewhere where we throw for proximity properties.



_Code quote:_
```cpp
        throw std::logic_error(fmt::format(
            "The hydroelastic margin can't be negative; given {}", *margin));
```
___
*[`multibody/parsing/detail_sdf_geometry.h` line 164 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_JqHhBKqF4a5EgSTw:-O7_JqHhBKqF4a5EgSTx:bc8nchs) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_sdf_geometry.h#L164)):*
> ```objc
> 
>  Mapping from SDF tag to geometry property. See
>   @ref YET_TO_BE_WRITTEN_HYDROELASTIC_GEOMETRY_MODULE for details on the
> ```

nit: This can be updated to point to the parsing doxygen module now, correct?



_Code quote:_
```objc
  @ref YET_TO_BE_WRITTEN_HYDROELASTIC_GEOMETRY_MODULE for details on the
```
___
*[`multibody/parsing/detail_sdf_geometry.h` line 171 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_K6sgCZL1pUddoGvA:-O7_K6sgCZL1pUddoGvB:b-gb0zp0) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_sdf_geometry.h#L171)):*
> ```objc
>  | drake:mesh_resolution_hint       | hydroelastic | resolution_hint           | Required for shapes that require tessellation to support hydroelastic contact.                                                   |
>  | drake:hydroelastic_modulus       | hydroelastic | hydroelastic_modulus      | Finite positive value. Required for compliant hydroelastic representations.                                                      |
>  | drake:hydroelastic_margin        | hydroelastic | margin                    | Finite nonnegative value.
> ```

Should probably add that `margin` is completely optional always.



_Code quote:_
```objc
 | drake:hydroelastic_margin        | hydroelastic | margin                    | Finite nonnegative value.
```
___
*[`multibody/parsing/detail_urdf_geometry.h` line 185 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_KNgP9S3AlGICv6NB:-O7_KNgP9S3AlGICv6NC:ba9omlr) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_urdf_geometry.h#L185)):*
> ```objc
>  | drake:mesh_resolution_hint       | hydroelastic | resolution_hint           | Required for shapes that require tessellation to support hydroelastic contact.                                                   |
>  | drake:hydroelastic_modulus       | hydroelastic | hydroelastic_modulus      | Finite positive value. Required for compliant hydroelastic representations.                                                      |
>  | drake:hydroelastic_margin        | hydroelastic | margin                    | Finite nonnegative value.
> ```

nit: Ditto add that `margin` is always optional.



_Code quote:_
```objc
 | drake:hydroelastic_margin        | hydroelastic | margin                    | Finite nonnegative value.
```
___
*[`multibody/parsing/parsing_doxygen.h` line 581 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_KbEw5vZ_UMW4EKSs:-O7_KbEw5vZ_UMW4EKSt:b-p581mp) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/parsing_doxygen.h#L581)):*
> ```objc
> - SDFormat path: `//model/link/collision/drake:proximity_properties/drake:hydroelastic_margin`
> - URDF path: `/robot/link/collision/drake:proximity_properties/drake:hydroelastic_margin/@value`
> - Syntax: Positive floating point value.
> ```

0 margin is allowed.



_Suggestion:_
```objc
- Syntax: Non-negative floating point value.
```
___
*[`multibody/parsing/test/detail_common_test.cc` line 267 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_LvAp9iqzXZWxiyKd:-O7_LvAp9iqzXZWxiyKe:b-ylr8ib) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/test/detail_common_test.cc#L267)):*
> ```cpp
> }
> 
> // Confirms successful parsing of margin.
> ```

I don't see code coverage for the unsuccessful parsing path (negative margin). Is it covered somewhere else or missing?

Ditto to detect the failure from the change you made to the bug for `relaxation_time`.



_Code quote:_
```cpp
// Confirms successful parsing of margin.
```

**Review by rpoyner-tri — COMMENTED** [review]
Still working on tests.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-:-O7_UBo_47h981mOHTva:b-6a3zry)* status: 4 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`multibody/parsing/detail_common.cc` line 143 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_Mfiy5P3M1Q2JhvtC:-O7_ReghE5hm0xEx1Xee:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_common.cc#L143)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Should this be strictly throwing? Or should we be using the `DiagnosticPolicy`? Here and elsewhere where we throw for proximity properties.
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_sdf_geometry.h` line 164 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_JqHhBKqF4a5EgSTw:-O7_RkHHCAizCy6J-WLM:b5gzj1d) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_sdf_geometry.h#L164)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: This can be updated to point to the parsing doxygen module now, correct?
</blockquote></details>

Sure. This whole "doc" nightmare is #16558 and copy-pasta vs. the urdf file, but I guess I can maintain it a little, and move it later.
___
*[`multibody/parsing/parsing_doxygen.h` line 581 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_KbEw5vZ_UMW4EKSs:-O7_TRKhDLFcyXSG5ZjQ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/parsing_doxygen.h#L581)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

0 margin is allowed.
</blockquote></details>

Done.

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_common.cc` line 143 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_Mfiy5P3M1Q2JhvtC:-O7_Z1vF56i6-1sVlg7Z:b-b8ark6) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_common.cc#L143)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, Reviewable is not showing any change here between r2 and r4. Maybe you forgot to push?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_common.cc` line 143 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_Mfiy5P3M1Q2JhvtC:-O7__PJiByYAS1XvkSvG:b-r2hqrc) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_common.cc#L143)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Hmm, Reviewable is not showing any change here between r2 and r4. Maybe you forgot to push?
</blockquote></details>

oops. r5 has the changes. Tests are still pending; I have to rewrite the fixture.
___
*[`multibody/parsing/test/detail_common_test.cc` line 267 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_LvAp9iqzXZWxiyKd:-O7__bjX3jM8DurWNF7h:b1l89z8) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/test/detail_common_test.cc#L267)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I don't see code coverage for the unsuccessful parsing path (negative margin). Is it covered somewhere else or missing?

Ditto to detect the failure from the change you made to the bug for `relaxation_time`.
</blockquote></details>

Nope. still pending. This swath of tests never got rewritten for diagnostic policy, even though inertia ones down below in this file did.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_common.cc` line 143 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_Mfiy5P3M1Q2JhvtC:-O7_eIh08ChEHw_xLkHk:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_common.cc#L143)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

oops. r5 has the changes. Tests are still pending; I have to rewrite the fixture.
</blockquote></details>

Done.
___
*[`multibody/parsing/test/detail_common_test.cc` line 267 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_LvAp9iqzXZWxiyKd:-O7_eHPT09Gp11cq95Mn:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/test/detail_common_test.cc#L267)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Nope. still pending. This swath of tests never got rewritten for diagnostic policy, even though inertia ones down below in this file did.
</blockquote></details>

Done.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: feature. +@sherm1 for platform review tomorrow, please.

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-:-O7_iPvU9MSTGo35hG6G:b-olhn4j)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_common.cc` line 143 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7_Mfiy5P3M1Q2JhvtC:-O7_iE5W8hq8_hXZhk8C:b-ucfknh) ([raw file](https://github.com/RobotLocomotion/drake/blob/95af2802cf6b471f1cf2a77be9acde51d5d7ec98/multibody/parsing/detail_common.cc#L143)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one suggestion

> Reviewed 3 of 8 files at r1, 1 of 3 files at r2, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-:-O7eVE-hEPKRNtruV3hi:b-g6fn90)* status: 1 unresolved discussion, missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/parsing_doxygen.h` line 587 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7eTFFr4bUWEvfdxsa6:-O7eTFFr4bUWEvfdxsa7:b-9ufgwc) ([raw file](https://github.com/RobotLocomotion/drake/blob/8843c868efc47432caaefaede7dd611ec22c35ab/multibody/parsing/parsing_doxygen.h#L587)):*
> ```objc
> If present, this element provides a value (units of length, i.e. m)
> for the hydroelastic margin. It is stored in a ProximityProperties object
> under `(hydroelastic, margin)`.
> ```

BTW consider noting here that a typical value is .0001m and that .01m (a cm) would be a _huge_ margin. As written ("units of length, i.e. m") I wouldn't be surprised if naive users picked an absurdly large value like 1 or .1.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831)* status: missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/parsing_doxygen.h` line 587 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7eTFFr4bUWEvfdxsa6:-O7ehgjU3uz6yqFKoZFK:b-i2c0is) ([raw file](https://github.com/RobotLocomotion/drake/blob/8843c868efc47432caaefaede7dd611ec22c35ab/multibody/parsing/parsing_doxygen.h#L587)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider noting here that a typical value is .0001m and that .01m (a cm) would be a _huge_ margin. As written ("units of length, i.e. m") I wouldn't be surprised if naive users picked an absurdly large value like 1 or .1.
</blockquote></details>

Note that none of the sections here give any advice about typical values. Most of that stuff lives in other articles (hydro user guide, the new margin docs that are referenced just below here).  Adding value advice here seems like an invitation to start doing that for all of the other tags as well. I don't think it is necessary here.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21831)* status: missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/parsing_doxygen.h` line 587 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21831#-O7eTFFr4bUWEvfdxsa6:-O7elA8d7kPBI0njS_xD:b-dxcbts) ([raw file](https://github.com/RobotLocomotion/drake/blob/8843c868efc47432caaefaede7dd611ec22c35ab/multibody/parsing/parsing_doxygen.h#L587)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Note that none of the sections here give any advice about typical values. Most of that stuff lives in other articles (hydro user guide, the new margin docs that are referenced just below here).  Adding value advice here seems like an invitation to start doing that for all of the other tags as well. I don't think it is necessary here.
</blockquote></details>

Makes sense.

**Pull request merged**
