### PR TITLE
Zap some unnecessary toolbox dependencies

### PR DESCRIPTION
**Pull request by david-german-tri**
Contributes to #2017.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2026)

### CODE REVIEW

**Comment by liangfok** [comment]
LGTM. Handing it to @jwnimmer-tri  for final review / merge.

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Comment by jwnimmer-tri** [comment]
I am not entirely sure that I should ever merge matlab code.  It all looks like pasta to me.

**Comment by david-german-tri** [comment]
@sherm1, would you mind taking a look?

**Comment by sherm1** [comment]
100+ tests failed on linux_matlab, with this message:
```
License checkout failed.
License Manager Error -15
MATLAB is unable to connect to the license server. 
Check that the license manager has been started, and that the MATLAB client machine can communicate
with the license server.

Troubleshoot this issue by visiting: 
http://www.mathworks.com/support/lme/R2015b/15

Diagnostic Information:
Feature: MATLAB 
License path: /home/ubuntu/.matlab/R2015b_licenses:/usr/local/MATLAB/R2015b/licenses/license.dat:/usr/local/MATLAB
/R2015b/licenses/network.lic 
Licensing error: -15,570. System Error: 115
Severe:
Error checking out license
The program '[32596] : Native' has exited with code 1 (0x1).
matlab exit code: 1
```

**Comment by david-german-tri** [comment]
Sure enough.  @jamiesnape?

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2026)*

**Comment by sherm1** [comment]
> @sherm1, would you mind taking a look?

@david-german-tri, the Matlab code changes look good. I'm not sure what's going on with CI.

**Comment by jwnimmer-tri** [comment]
Let's do another round of CI.

**Comment by RussTedrake** [comment]
+1 for the changes.

**Comment by david-german-tri** [comment]
On retest, only failures are drake005 infrastructure flakes.  Performing no-conflict branch update, and merging without waiting for CI re-run.

**Pull request merged**
