### PR TITLE
Mathematical program solver interface

### PR DESCRIPTION
**Pull request by hongkai-dai**
Move `MathematicalProgramSolverInterface` to its own header file, to make `MathematicalProgram.h` a little bit smaller.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4558)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri for feature review. +@david-german-tri for platform review.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4558#-:-KZShJq6A2tSg8rZYocC:b-6oxrm6)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  linux-gcc-experimental-ros please

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4558#-:-KZSlVTJ4mXRwUj0fcn_:b-682qxn)*

**Comment by david-german-tri** [comment]
:lgtm:

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-bazel-experimental please

---

Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4558#-:-KZTiVqILsoWOS1Z7PcS:b1g7grn)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4558)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4558#-:-KZXuubSmLi1VZ4bCRIa:bnfp4nl)*

**Pull request merged**
