### PR TITLE
Added interpolation type gflag and logic to iiwa_controller

### PR DESCRIPTION
**Pull request by rcory**
---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7116)

### CODE REVIEW

**Comment by rcory** [comment]
+@sammy-tri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-:-Kv49X6tkLQoNmb_mPV2:bjquaum)*

**Comment by rcory** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-:-Kv4sj0FZlBcqhBxgSiw:b-1hejgk)*

**Comment by sammy-tri** [comment]
:lgtm: with a couple BTWs  +@soonho-tri for platform review per rotation

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_controller.cc, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-Kv7jYT3zJKux6AcemRF:-Kv7jYT4uBStEnySa6CG:b9y7ziw) ([raw file](https://github.com/robotlocomotion/drake/blob/209c400a7aa12b4b98d4ab3ee4c628b398becd4c/drake/examples/kuka_iiwa_arm/iiwa_controller.cc#L63)):*
> ```cpp
>   // Sets the robot plan interpolation type.
>   RobotPlanInterpolator* plan_source;
>   if (FLAGS_interp_type == "ZOH") {
> ```

BTW I'm not entirely thrilled about having to remember to capitalize the options correctly.  Perhaps a case insensitive compare?

---

*[drake/examples/kuka_iiwa_arm/iiwa_controller.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-Kv7n6TMOtBncPlG5ZNr:-Kv7n6TMOtBncPlG5ZNs:bsee421) ([raw file](https://github.com/robotlocomotion/drake/blob/209c400a7aa12b4b98d4ab3ee4c628b398becd4c/drake/examples/kuka_iiwa_arm/iiwa_controller.cc#L76)):*
> ```cpp
>         urdf, InterpolatorType::Pchip);
>   } else {
>     DRAKE_ABORT_MSG("Robot plan interpolation type not recognized.");
> ```

BTW it might be helpful to print the valid options here...   of course the tradeoff is that the message gets out of sync with the actual options and becomes worse than useless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-:-Kv7nK6y0ZI-ANP4iJcm:b-gu0v6u)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-:-Kv87b5gBn2w0KPYM1UY:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7116)*

**Comment by rcory** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_controller.cc, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-Kv7jYT3zJKux6AcemRF:-Kv8Zs9AuYc-7jP4y2k0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/209c400a7aa12b4b98d4ab3ee4c628b398becd4c/drake/examples/kuka_iiwa_arm/iiwa_controller.cc#L63)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I'm not entirely thrilled about having to remember to capitalize the options correctly.  Perhaps a case insensitive compare?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_controller.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-Kv7n6TMOtBncPlG5ZNr:-Kv8ZxBykwhrmrb1NzpS:bhnsj0t) ([raw file](https://github.com/robotlocomotion/drake/blob/209c400a7aa12b4b98d4ab3ee4c628b398becd4c/drake/examples/kuka_iiwa_arm/iiwa_controller.cc#L76)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW it might be helpful to print the valid options here...   of course the tradeoff is that the message gets out of sync with the actual options and becomes worse than useless.
</blockquote></details>

Yeah. I worry about the getting out of sync issue. The gflag help string lists the options. I've added to the drake abort msg pointing to that. Having it in once place seems better than two.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7116)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_controller.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-Kv7n6TMOtBncPlG5ZNr:-Kv8dluVJsZakl7nxLr2:br8a6g) ([raw file](https://github.com/robotlocomotion/drake/blob/209c400a7aa12b4b98d4ab3ee4c628b398becd4c/drake/examples/kuka_iiwa_arm/iiwa_controller.cc#L76)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Yeah. I worry about the getting out of sync issue. The gflag help string lists the options. I've added to the drake abort msg pointing to that. Having it in once place seems better than two.
</blockquote></details>

Thanks!  This is better than what I suggested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-:-Kv8dt8ckQbiKBu5RxJs:b-s794vx)*

**Comment by rcory** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7116#-:-Kv99CrOBkfIsOkhj4FQ:b-l70wzf)*

**Pull request merged**
