### PR TITLE
adds steady state kalman filter + unit test

### PR DESCRIPTION
**Pull request by RussTedrake**
@naveenoid for feature review
@sammy-tri for platform review

(note: first commit is from my luenberger PR which is hopefully about to land)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4309)

### CODE REVIEW

**Comment by RussTedrake** [comment]
doh. build error is a cross-dependency with my LQR PR.  please still review, will (almost) fix itself if LQR gets merged first.

**Comment by naveenoid** [comment]
This PR is mostly ready, although it obviously needs rebasing to remove the LuenbergerObserver..

---

Reviewed 5 of 14 files at r1.
Review status: 5 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/estimators/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KXtap1w_cNqkSHsT_x7:-KXtap1w_cNqkSHsT_x8:bi841jn) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/CMakeLists.txt#L2)):*
> ```CMake
> 
> add_library_with_exports(LIB_NAME drakeEstimators SOURCE_FILES luenberger_observer.cc kalman_filter.cc)
> ```

BTW: (nit) Consider organising the source list vertically for easier readability.

---

*[drake/systems/estimators/CMakeLists.txt, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KXtazAr45j3Ja7ds9wt:-KXtazAr45j3Ja7ds9wu:buldkjt) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/CMakeLists.txt#L6)):*
> ```CMake
> 
> drake_install_libraries(drakeEstimators)
> drake_install_headers(luenberger_observer.h kalman_filter.h)
> ```

BTW: (nit) same as the source list, please consider organising this list vertically.

---

*[drake/systems/estimators/test/kalman_filter_test.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KXtlDNaoAp1iB6zicNR:-KXtlDNaoAp1iB6zicNS:byb4stl) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/test/kalman_filter_test.cc#L57)):*
> ```cpp
> 
>   EXPECT_TRUE(CompareMatrices(filter->L(), L, tol));
> }
> ```

What about a test case that also tests the linearisation? I think there definitely needs to be a test since this PR includes the interface for a linearization based filter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-:-KXtlf8KKh2pdfQTyO0t:b-jqqqic)*

**Comment by sammy-tri** [comment]
I think we're good to rebase, The LQR PR #4308 got merged this morning, and I think the LuenbergerObserver is in too now (don't remember PR # offhand)

---

Review status: 5 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-:-KXvSgJjc6PAtra8xVGD:b-lwsr2i)*

**Comment by RussTedrake** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/estimators/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KXtap1w_cNqkSHsT_x7:-KY3R5FtrKhQIsVBmBeP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/CMakeLists.txt#L2)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: (nit) Consider organising the source list vertically for easier readability.
</blockquote></details>

Done.

---

*[drake/systems/estimators/CMakeLists.txt, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KXtazAr45j3Ja7ds9wt:-KY3R5cgRA--TSQDppL1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/CMakeLists.txt#L6)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: (nit) same as the source list, please consider organising this list vertically.
</blockquote></details>

Done.

---

*[drake/systems/estimators/test/kalman_filter_test.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KXtlDNaoAp1iB6zicNR:-KY3RSNDvEpRY_6w5ZiY:b-a8oj00) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/test/kalman_filter_test.cc#L57)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

What about a test case that also tests the linearisation? I think there definitely needs to be a test since this PR includes the interface for a linearization based filter.
</blockquote></details>

This second call to steady state kalman filter tests that interface.  It passes in a Linear System, but using the generic system interface.  So the linear system gets linearized (using that machinery), and this confirms that we still get the same answer out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309)*

**Comment by naveenoid** [comment]
Wow thats a massive bunch of extra stuff included into this PR. I guess you need to clean it up and rebase instead of merging. 

---

Review status: 2 of 335 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-:-KY4HuurE7IWSB43DS1b:b-lnrn1a)*

**Comment by liangfok** [comment]
Reviewed 1 of 14 files at r1, 1 of 335 files at r3.
Review status: 4 of 335 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/estimators/kalman_filter.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY3vP5R69qchavOtFST:-KY3vP5R69qchavOtFSU:bfqxqe4) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/kalman_filter.h#L19)):*
> ```objc
> /// The resulting observer is of the form
> ///   @f[ \dot{\hat{x}} = A\hat{x} + Bu + L(y - C\hat{x} - Du). @f]
> /// The process noise, w, and the measurement noise, v, are assumed to be iid
> ```

BTW, does "iid" stand for "independent and identically distributed"? If so, is this something we expect most folks who read this to know?

---

*[drake/systems/estimators/kalman_filter.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY3vtYyDtrvp4APqt8A:-KY3vtYyDtrvp4APqt8B:b-4hoh2h) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/kalman_filter.h#L23)):*
> ```objc
> ///
> /// This is a simplified form of the full Kalman filter obtained by assuming
> /// that the state-covariance matrix (referred to as P below) has already
> ```

BTW, is P mentioned below?

---

*[drake/systems/estimators/kalman_filter.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY3w9zuLYLeL3j1G0Om:-KY3w9zuLYLeL3j1G0On:buamm5a) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/kalman_filter.h#L34)):*
> ```objc
> /// num_outputs.
> ///
> /// @throws std::runtime_error if V is not PSD.
> ```

BTW, does "PSD" stand for "Positive-Semi-Definite"? If so, is this something we expect a typical reader of this code to know?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309)*

**Comment by RussTedrake** [comment]
@naveenoid - fixed the merge issue.

**Comment by RussTedrake** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/estimators/kalman_filter.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY3vP5R69qchavOtFST:-KY68Fup9ox-RpIyuqT8:b-csko7x) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/kalman_filter.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, does "iid" stand for "independent and identically distributed"? If so, is this something we expect most folks who read this to know?
</blockquote></details>

yes, and I would say yes.  it's an easy google if they don't.

---

*[drake/systems/estimators/kalman_filter.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY3vtYyDtrvp4APqt8A:-KY68OyBrk6vHIFSarLs:bkem86j) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/kalman_filter.h#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is P mentioned below?
</blockquote></details>

oops.  it will be as soon as @siyuanfeng-tri enables it as an optional argument/return value. 

---

*[drake/systems/estimators/kalman_filter.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY3w9zuLYLeL3j1G0Om:-KY68ZXuN48OWCN4ntka:bjqhqzx) ([raw file](https://github.com/robotlocomotion/drake/blob/47dfcb700c275b0fc19dcf36cbdd4f7fac9193e2/drake/systems/estimators/kalman_filter.h#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, does "PSD" stand for "Positive-Semi-Definite"? If so, is this something we expect a typical reader of this code to know?
</blockquote></details>

again, i would say yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309)*

**Comment by liangfok** [comment]
I left some minor comments.

---

Reviewed 3 of 14 files at r1, 1 of 335 files at r3, 1 of 12 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/estimators/CMakeLists.txt, line 3 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6CroMnZyEcJ1zgfJu:-KY6CroMnZyEcJ1zgfJv:bby1za0) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/CMakeLists.txt#L3)):*
> ```CMake
> 
> add_library_with_exports(LIB_NAME drakeEstimators SOURCE_FILES
>   luenberger_observer.cc
> ```

BTW: nit: This is not a style guide violation since this is not C++, but to be consistent with the C++ style guide and the formatting of `drake_install_pkg_config_file()` below, line continuations should be indented by four spaces.

---

*[drake/systems/estimators/kalman_filter.cc, line 20 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6DLdpo0KEP6D0Ddn8:-KY6DLdpo0KEP6D0Ddn9:b1pud38) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/kalman_filter.cc#L20)):*
> ```cpp
>   const auto& P =
>       ContinuousAlgebraicRiccatiEquation(A.transpose(), C.transpose(), W, V);
>   return P * C.transpose() * (V.inverse());
> ```

BTW: I just wanted to confirm: Is the parentheses around `V.inverse()` required?

---

*[drake/systems/estimators/luenberger_observer.h, line 8 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6EwY1PCBzcbMVuWCm:-KY6EwY1PCBzcbMVuWCn:bp9mrw8) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/luenberger_observer.h#L8)):*
> ```objc
> 
> #include "drake/systems/framework/leaf_system.h"
> #include "drake/systems/framework/primitives/linear_system.h"
> ```

BTW: Is this needed?

---

*[drake/systems/estimators/luenberger_observer.h, line 61 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6F0p6xlmZwwiY0N8C:-KY6F0p6xlmZwwiY0N8D:b-n629fh) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/luenberger_observer.h#L61)):*
> ```objc
>                   systems::SystemOutput<T>* output) const override;
> 
>   /// Access to the observer gain
> ```

BTW: nits: (1) per style guide, "Access" should be "Provides access", and (2) missing period at end of sentence.

---

*[drake/systems/estimators/luenberger_observer.h, line 64 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6FGl-tZG7g4hlL4Hk:-KY6FGl-tZG7g4hlL4Hl:bpnbzkn) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/luenberger_observer.h#L64)):*
> ```objc
>   const Eigen::MatrixXd& observer_gain() { return observer_gain_; }
> 
>   /// Provide access via the short-hand name, too.
> ```

BTW: nit: per style guide, "Provide" should be "Provides". Also, consider replacing "too" with "L".

---

*[drake/systems/estimators/test/kalman_filter_test.cc, line 25 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6Fn5HxuUSFPHcezWQ:-KY6Fn5HxuUSFPHcezWR:by0yohd) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/test/kalman_filter_test.cc#L25)):*
> ```cpp
>   D << 0;
> 
>   // Trivial cost:
> ```

BTW: nit: The style guide recommends that comments be full sentences.

https://google.github.io/styleguide/cppguide.html#Punctuation,_Spelling_and_Grammar

---

*[drake/systems/estimators/test/kalman_filter_test.cc, line 31 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6FaLTzt0OC8kdCbD2:-KY6FaLTzt0OC8kdCbD3:b-avnugo) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/test/kalman_filter_test.cc#L31)):*
> ```cpp
>   V << 1;
> 
>   // Analytical solution
> ```

BTW: nit: Missing period at end of sentence.

---

*[drake/systems/estimators/test/kalman_filter_test.cc, line 37 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6FXy2ZNR-jDoIHB-g:-KY6FXy2ZNR-jDoIHB-h:b-avnugo) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/test/kalman_filter_test.cc#L37)):*
> ```cpp
>   double tol = 1e-10;
> 
>   // Test the matrix-only version
> ```

BTW: nit: Missing period at end of sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-:-KY6GX46W0HbXbfCacSd:b-9fij1c)*

**Comment by RussTedrake** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/estimators/CMakeLists.txt, line 3 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6CroMnZyEcJ1zgfJu:-KY8fJebDyoXMfxHsIny:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/CMakeLists.txt#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: This is not a style guide violation since this is not C++, but to be consistent with the C++ style guide and the formatting of `drake_install_pkg_config_file()` below, line continuations should be indented by four spaces.
</blockquote></details>

Done.

---

*[drake/systems/estimators/kalman_filter.cc, line 20 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6DLdpo0KEP6D0Ddn8:-KY8fpeiDYM8ZfhxkYZa:bjbyktm) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/kalman_filter.cc#L20)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: I just wanted to confirm: Is the parentheses around `V.inverse()` required?
</blockquote></details>

no.  done

---

*[drake/systems/estimators/luenberger_observer.h, line 8 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6EwY1PCBzcbMVuWCm:-KY8gBqV2rlk4SrkgxzQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/luenberger_observer.h#L8)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: Is this needed?
</blockquote></details>

Done.

---

*[drake/systems/estimators/luenberger_observer.h, line 61 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6F0p6xlmZwwiY0N8C:-KY8gNvA5otwmxWyRbae:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/luenberger_observer.h#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nits: (1) per style guide, "Access" should be "Provides access", and (2) missing period at end of sentence.
</blockquote></details>

Done.

---

*[drake/systems/estimators/luenberger_observer.h, line 64 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6FGl-tZG7g4hlL4Hk:-KY8gUHBBt3p-cmnIFKz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/luenberger_observer.h#L64)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: per style guide, "Provide" should be "Provides". Also, consider replacing "too" with "L".
</blockquote></details>

Done.

---

*[drake/systems/estimators/test/kalman_filter_test.cc, line 25 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6Fn5HxuUSFPHcezWQ:-KY8gowXCSf06cHUgE3o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/test/kalman_filter_test.cc#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: The style guide recommends that comments be full sentences.

https://google.github.io/styleguide/cppguide.html#Punctuation,_Spelling_and_Grammar
</blockquote></details>

Done.

---

*[drake/systems/estimators/test/kalman_filter_test.cc, line 31 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6FaLTzt0OC8kdCbD2:-KY8gpnpConzy9qdj6D-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/test/kalman_filter_test.cc#L31)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: Missing period at end of sentence.
</blockquote></details>

Done.

---

*[drake/systems/estimators/test/kalman_filter_test.cc, line 37 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-KY6FXy2ZNR-jDoIHB-g:-KY8gqWvCSObSB2mTua_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9e37a1241ca6cc80c125dcfdf14a993c3c0ff09/drake/systems/estimators/test/kalman_filter_test.cc#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: Missing period at end of sentence.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-:-KY8wwbk0f1gBtGU43l7:bnfp4nl)*

**Comment by liangfok** [comment]
One unit test timed out in `linux-gcc-experimental-matlab`:
```
07:18:39 435/544 Test #303: systems/plants/test/testMassSpringDamperTrajOpt .......................................***Timeout 300.32 sec
```
@drake-jenkins-bot linux-gcc-experimental-matlab please.

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-:-KY9gAoz5GFhXSfJNwge:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 14 files at r1, 1 of 12 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4309#-:-KYE_4xkcfrTiqgOeQvo:bnfp4nl)*

**Pull request merged**
