### PR TITLE
Implements Demultiplexer system

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR implements a system that takes a vector valued input signal of size "length" and splits it into "length" output signals of size "1".

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3279)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@david-german-tri for feature since you asked for it!

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-:-KQBjujFox958NonKfyl:bap616u)*

**Comment by jwnimmer-tri** [comment]
Let's not make the `length` vs `size` problem any worse.  @david-german-tri was going to choose one, and all new code should use it.  My vote is `size` to remain consistent with Eigen, but mostly I just want us to be consistent.

**Comment by amcastro-tri** [comment]
Sure, that makes sense to me. System 2.0 uses length all over the place though. 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-:-KQGCUkp6UdmJfPEPVyp:b-e8pulm)*

**Comment by jwnimmer-tri** [comment]
Sure, except for all of the main APIs that use `size`.

**Comment by liangfok** [comment]
I'm agnostic to whatever final term is chosen and agree it should ultimately be consistent, but I just wanted to highlight the fact that "length" carries more semantic meaning in that it implies a single dimension. The word "size" is more general in that it covers single as well as multi-dimensional measurements.

**Comment by amcastro-tri** [comment]
> The word "size" is more general in that it covers single as well as multi-dimensional measurements.

Not in Eigen though. In Eigen `size() = rows() * cols()`. What you are saying is correct in Matlab however. In Matlabe `size` is a 1 by 2 matrix with the number of rows and columns. In Matlab `length` is the larger of rows or columns.

That is why it is not good enough to check for `size()` in Eigen objects because you could be mistaking a 2x2 matrix with a 4 elements column vector. 

All that being said, I think `size` is good when the question is asked to a column vector (System 2.0 objects) but more specific checks (`rows()`, `cols()`) must be performed on general Eigen matrices.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-:-KQGUR_o1Y-bO2UTRwOU:bqxstx8)*

**Comment by david-german-tri** [comment]
:lgtm: I don't think this should block on the great `length` vs `size` debate.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/test/demultiplexer_test.cc, line 65 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-KQLpBE-V2qk4dSjdXB_:-KQLpBE-V2qk4dSjdXBa:b5pyucd) ([raw file](https://github.com/robotlocomotion/drake/blob/8126e23b73aa2f15c1902e9eb937a69301e249ad/drake/systems/framework/primitives/test/demultiplexer_test.cc#L65)):*
> ```cpp
>   ASSERT_EQ(input_vector.size(), demux_->get_num_output_ports());
> 
>   EXPECT_EQ(1, output_->get_vector_data(0)->size());
> ```

`ASSERT_EQ` on the sizes (here and below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-:-KQLq74pFsJxCaRJxCrd:b-ioodza)*

**Comment by sherm1** [comment]
:lgtm: -- a couple of BTWs. PTAL.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/primitives/demultiplexer.cc, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-KQO_vjJDFDNStlWH2nh:-KQO_vjJDFDNStlWH2ni:b5t3764) ([raw file](https://github.com/robotlocomotion/drake/blob/8126e23b73aa2f15c1902e9eb937a69301e249ad/drake/systems/framework/primitives/demultiplexer.cc#L23)):*
> ```cpp
>   DRAKE_ASSERT_VOID(System<T>::CheckValidContext(context));
>   // TODO(amcastro-tri): the output should simply reference the input port's
>   // value to avoid copy.
> ```

BTW, I agree -- shouldn't copy! This one is interesting because an input port will have only a single depedency list (that will include all output ports in this case), but the *value* is not the input port's value but rather a specific element. That is actually a common situation -- the dependents granularity will often be more coarse than the values it covers. For example, I can have an output port that references a few continuous state variables, like maybe the two angles associated with a U-joint. But there might be only a single dependency list for all the q's. (@david-german-tri)

---

*[drake/systems/framework/primitives/demultiplexer.h, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-KQO_HL2BHlmBRi7XIJB:-KQO_HL2BHlmBRi7XIJC:b3vm1el) ([raw file](https://github.com/robotlocomotion/drake/blob/8126e23b73aa2f15c1902e9eb937a69301e249ad/drake/systems/framework/primitives/demultiplexer.h#L24)):*
> ```objc
>   explicit Demultiplexer(int length);
> 
>   /// Sets the i-th output port to the value of the i-th component of the input
> ```

BTW, to clarify: "Writes to each output port in `output`, putting the value of the i-th input element into the i-th output port."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-:-KQObZ5rjZdZQCn_p8xg:b-s12g2i)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/primitives/demultiplexer.cc, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-KQO_vjJDFDNStlWH2nh:-KQR7fQ4jKizvGiqTHLi:b-7yqqvg) ([raw file](https://github.com/robotlocomotion/drake/blob/8126e23b73aa2f15c1902e9eb937a69301e249ad/drake/systems/framework/primitives/demultiplexer.cc#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I agree -- shouldn't copy! This one is interesting because an input port will have only a single depedency list (that will include all output ports in this case), but the *value* is not the input port's value but rather a specific element. That is actually a common situation -- the dependents granularity will often be more coarse than the values it covers. For example, I can have an output port that references a few continuous state variables, like maybe the two angles associated with a U-joint. But there might be only a single dependency list for all the q's. (@david-german-tri)
</details>
Interesting, we should support that.

---

*[drake/systems/framework/primitives/test/demultiplexer_test.cc, line 65 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-KQLpBE-V2qk4dSjdXB_:-KQRHndrcJCbJIjscvtq:b589zpc) ([raw file](https://github.com/robotlocomotion/drake/blob/8126e23b73aa2f15c1902e9eb937a69301e249ad/drake/systems/framework/primitives/test/demultiplexer_test.cc#L65)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> `ASSERT_EQ` on the sizes (here and below)
</details>
I believe I am doing that? what other test I am missing here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/primitives/test/demultiplexer_test.cc, line 65 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-KQLpBE-V2qk4dSjdXB_:-KQRI96eBBWxFuqiHyFC:bpbj299) ([raw file](https://github.com/robotlocomotion/drake/blob/8126e23b73aa2f15c1902e9eb937a69301e249ad/drake/systems/framework/primitives/test/demultiplexer_test.cc#L65)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I believe I am doing that? what other test I am missing here?
</details>
`EXPECT_EQ` and `ASSERT_EQ` are different.  The former continues after a failure, the latter stops.  Here, you want to stop, or the next line might segfault or abort.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279)*

**Comment by amcastro-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/primitives/test/demultiplexer_test.cc, line 65 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-KQLpBE-V2qk4dSjdXB_:-KQRKFIE56GsxbBV3Fs9:br89qhj) ([raw file](https://github.com/robotlocomotion/drake/blob/8126e23b73aa2f15c1902e9eb937a69301e249ad/drake/systems/framework/primitives/test/demultiplexer_test.cc#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `EXPECT_EQ` and `ASSERT_EQ` are different.  The former continues after a failure, the latter stops.  Here, you want to stop, or the next line might segfault or abort.
</details>
Ah! thank you. I was reading `ASSERT_EQ` even when I had `EXPECT_EQ` all over the place. My parsing skills go way down after lunch. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279)*

**Comment by david-german-tri** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/framework/primitives/demultiplexer.cc, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-KQO_vjJDFDNStlWH2nh:-KQS7ROZbOFsSDrl4XUO:b2ype88) ([raw file](https://github.com/robotlocomotion/drake/blob/8126e23b73aa2f15c1902e9eb937a69301e249ad/drake/systems/framework/primitives/demultiplexer.cc#L23)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Interesting, we should support that.
</details>
I think this will be pretty straightforward post 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279)*

**Comment by david-german-tri** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/demultiplexer.cc, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3279#-KQO_vjJDFDNStlWH2nh:-KQSVO1Nkd6w6mdc0_8k:b4hibub) ([raw file](https://github.com/robotlocomotion/drake/blob/8126e23b73aa2f15c1902e9eb937a69301e249ad/drake/systems/framework/primitives/demultiplexer.cc#L23)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I think this will be pretty straightforward post 
</details>
...post #3208, which will make the subvector/supervector notion available to I/O.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3279)*

**Pull request merged**
