### PR TITLE
Re-enable director tests on macOS

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
This reverts commit 06f6ae0f40bfa3cf976a06ce5b34614606112a6d, re-enabling director tests on macOS.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4830)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

This will fail, but it seems to only fail on CI, so using the PR to drive CI builds in order to try to fix the problem... at a guess, the fix will be adjusting the CI environment, after which this PR can be merged as-is.

**Comment by mwoehlke-kitware** [comment]
For the record, here is a sample error (all the errors seem to be generally consistent with the same library being missing):

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/elcapitan/workspace/mac-clang-experimental/build/install/lib/python2.7/dist-packages/director/drakevisualizer.py", line 6, in <module>
    import director.applogic as app
  File "/Users/elcapitan/workspace/mac-clang-experimental/build/install/lib/python2.7/dist-packages/director/applogic.py", line 5, in <module>
    import director.vtkAll as vtk
  File "/Users/elcapitan/workspace/mac-clang-experimental/build/install/lib/python2.7/dist-packages/director/vtkAll.py", line 2, in <module>
    from vtkDRCFiltersPython import *
ImportError: dlopen(/Users/elcapitan/workspace/mac-clang-experimental/build/install/lib/python2.7/dist-packages/director/vtkDRCFiltersPython.so, 2): Library not loaded: liblcmtypes_bot2-core.dylib
  Referenced from: /Users/elcapitan/workspace/mac-clang-experimental/build/install/lib/libbot2-frames.2.dylib
  Reason: image not found
```

**Comment by patmarion** [comment]
there's a chance it could be related to https://github.com/RobotLocomotion/libbot/issues/20

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot mac-clang-experimental please

**Comment by jwnimmer-tri** [comment]
@mwoehlke-kitware Not having CI coverage of Director on a primary platform seems like a big hazard.  What's the status of this fix?

**Comment by patmarion** [comment]
I can repeat this on my laptop.  Here is what I see happening:

first build pass:
  1. libbot compiles and installs its subprojects, including liblcmtypes_bot2-core.a, and libbot2-frames.dylib.
  2. bot_core_lcmtypes compiles and installs it's own copy of liblcmtypes_bot2-core.dylib.

at this point, everything is good

second build pass:
  1. libbot compiles, this time it links libbot2-frames.dylib against bot_core_lcmtypes' installed liblcmtypes_bot2-core.dylib.

now there is a runtime dlopen error.

```
$ find . -name liblcmtypes_bot2-core.*
 ./install/lib/liblcmtypes_bot2-core.a
  ./install/lib/liblcmtypes_bot2-core.dylib
```

```
$ otool -L  ./install/lib/liblcmtypes_bot2-core.dylib
./install/lib/liblcmtypes_bot2-core.dylib:
	liblcmtypes_bot2-core.dylib (compatibility version 0.0.0, current version 0.0.0) 
	@rpath/liblcm.1.dylib (compatibility version 1.0.0, current version 1.3.95)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

See, liblcmtypes_bot2-core.dylib has a bad install name.  It ought to be something like `@rpath/liblcmtypes_bot2-core.dylib`.  So if that was fixed, everything would work, but it's still weird to have libbot2-frames.dylib linking against a different library on subsequent build passes.  This weirdness comes from an incorrect implementation of the libbot cmake build, and from RobotLocomotion/libbot#20.

**Comment by liangfok** [comment]
I'm also running into the above issue on my OSX machine (unable to run numerous `director` unit tests).

**Comment by patmarion** [comment]
btw, you can set `DYLD_LIBRARY_PATH` to workaround the dlopen issue:

`export DYLD_LIBRARY_PATH=/path/to/drake-distro/build/install/lib`

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4830)*

**Comment by patmarion** [comment]
Any new progress @mwoehlke-kitware?  This issue affects users and CI testing.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by patmarion** [comment]
The tests are failing on mac because `import yaml` fails.  It looks like `PyYAML` is listed in the `pip install` command of the mac platform instructions `drake/doc/mac.rst`, but perhaps nobody has actually installed it on the mac build machines?

**Comment by mwoehlke-kitware** [comment]
> The tests are failing on mac because `import yaml` fails.

That's in improvement, I think?

@drake-jenkins-bot mac-clang-experimental please ← PyYAML has been installed

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
CI passed! :champagne: :tada:

**Comment by patmarion** [comment]
looks good!  By the way, have you considered adding the corrected RPATH logic to the problem library (I think bot_core_lcmtypes) so that the fix is available for other projects?  Having the RPATH logic imposed by drake seems reasonable, but it does cover up the issues in the external projects' cmake scripts.

**Comment by jwnimmer-tri** [comment]
@mwoehlke-kitware What's the status on this?  Can we get it merged?

**Comment by mwoehlke-kitware** [comment]
Apparently it is missing platform review...

**Comment by mwoehlke-kitware** [comment]
+@ggould-tri

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4830#-:-KgQazBPBPgfDBZJejsA:bnfp4nl)*

**Pull request merged**
