### PR TITLE
[common] Add lambda-using example to never_destroyed documentation

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15329)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for feature review
:lgtm: with a few teeny comments

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15329#-:-Me1bFbB1BnRyF5Legx3:b-z03djh)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[common/never_destroyed.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15329#-Me1aOni56WKzkrk5nPT:-Me1aOni56WKzkrk5nPU:bz7gqdk) ([raw file](https://github.com/robotlocomotion/drake/blob/9c7fd45edbc756c5ee1960cbccacfef0fea50e05/common/never_destroyed.h#L62)):*
> ```objc
> /// In cases where computing the static data is more complicated than an
> /// initializer_list, you can use a temporary lambda to populate the value:
> /// @code
> ```

Consider pointing out the "()" which is easy to miss, e.g. "Note the '()' after the lambda. That causes it to be invoked."
___
*[common/test/never_destroyed_test.cc, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15329#-Me1b2Uh7o6S0NfbS04V:-Me1b2Uh7o6S0NfbS04W:b-w4tyxh) ([raw file](https://github.com/robotlocomotion/drake/blob/9c7fd45edbc756c5ee1960cbccacfef0fea50e05/common/test/never_destroyed_test.cc#L90)):*
> ```cpp
>   return result.access();
> }
> GTEST_TEST(NeverDestroyedExampleTest, GetConstantMagicNumbers) {
> ```

BTW I'd be inclined to put a blank line before GTEST_TEST.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15329#-:-Me1cEvl0xK6vIx1VCid:bg7igkv)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15329)* status: needs at least two assigned reviewers (waiting on @sherm1)

___
*[common/never_destroyed.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15329#-Me1aOni56WKzkrk5nPT:-Me1d9LA0EXEBrWCqTB8:bc852em) ([raw file](https://github.com/robotlocomotion/drake/blob/9c7fd45edbc756c5ee1960cbccacfef0fea50e05/common/never_destroyed.h#L62)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Consider pointing out the "()" which is easy to miss, e.g. "Note the '()' after the lambda. That causes it to be invoked."
</blockquote></details>

Done.  Good idea!

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15329)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review by dice roll (no hurry) please, just to get one more set of eyes to check this.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:  It's a fiddly pattern, so the excellent documentation will be very helpful.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15329#-:-Me53GF-6jEpbYaMc7bI:b5g6yvp)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
