### PR TITLE
[multibody] Fix bug in SapContactProblem::velocities_start()

### PR DESCRIPTION
**Pull request by joemasterjohn**
Fixes a small off by one introduced in #19557 and adds a unit test to catch the error.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19681)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@amcastro-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19681#-:-NYtogwmDaf-WRi9EfX-:b5xll3r)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19681)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`multibody/contact_solvers/sap/sap_contact_problem.cc` line 34 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19681#-NYxExI3BXPXdc6Rvnrr:-NYxJ0IqDYyXIl40RJ_M:blh98s5) ([raw file](https://github.com/RobotLocomotion/drake/blob/feaf60cca711ed5ff3359fe1aa7ba76c9ce923a6/multibody/contact_solvers/sap/sap_contact_problem.cc#L34)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, really `clique_nv` is not used, and personally I prefer:
```c++
for (int i = 0; i < ssize(A_); ++i) {
    const auto& Ac = A_[i];
    DRAKE_THROW_UNLESS(Ac.rows() == Ac.cols());
    if (i > 0)
      velocities_start_[i] = velocities_start_[i - 1] + num_velocities(i - 1);
    nv_ += Ac.rows();
  }
```

</blockquote></details>

Nice, I like that.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19681)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19681#-:-NYyK3627l9VSIDxfLyQ:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri

**Pull request merged**
