### PR TITLE
Add names to systems in Acrobot and Pendulum examples.

### PR DESCRIPTION
**Pull request by david-german-tri**
@hongkai-dai for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5838)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
:lgtm: +@soonho-tri for platform review please.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5838#-:-KhhzBaLjx4y5JVpXfen:b-mkkz8q)*

**Comment by soonho-tri** [comment]
:lgtm:

Probably not in the scope of this PR, but do we have a plan to add a new method (or overloading) to take care of this common pattern:

```c++
  acrobot_plant_ = builder.template AddSystem<AcrobotPlant<T>>();
  acrobot_plant_->set_name("acrobot_plant");
```

with something like the following?

```c++
  acrobot_plant_ = 
     builder.template AddSystemWithName<AcrobotPlant<T>>("acrobot_plant", arg_1, ..., arg_n);
```

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5838#-:-KhlNzbWKMASZ3FpLY_d:bsvaxrz)*

**Comment by soonho-tri** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5838)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot , linux-gcc-experimental-ros please

**Comment by soonho-tri** [comment]
@drake-jenkins-bot , linux-gcc-experimental-ros please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5838#-:-KhsMYCgHd5TwEQs51Ge:b-yw5nhh)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot , linux-gcc-experimental-ros please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5838#-:-KhtbM4KQnnQDkDWvDdp:b-yw5nhh)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5838#-:-KhwInCa-hsCQxfAL1Un:bzdwe9o)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5838#-:-KhxKvXu_EOpO-PYH_yk:b-qgwxgk)*

**Pull request merged**
