### PR TITLE
Fixes problem with velocity stepping using purely bilaterally...

### PR DESCRIPTION
**Pull request by edrumwri**
constrained systems.

A short-circuit employed to keep from building the complementarity problem if not required caused the bilateral constraint forces to not be computed. This PR fixes that and adds a unit test which will detect the condition if reverted.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9054)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@seancurtis-tri for feature review please

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9054#-:-LFrx3gQBgU96Y_DfN8a:b-kr3pa2)*

**Comment by SeanCurtis-TRI** [comment]
A few cosmetic issues, but otherwise :LGTM:.

---

Reviewed 2 of 2 files at r1.
Review status: 3 unresolved discussions, platform LGTM from [seancurtis-tri]

---

*[multibody/constraint/constraint_solver.h, line 1393 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwWR8U9675wQeKnw-L:-LFwWR8U9675wQeKnw-M:boggym1) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L1393)):*
> ```objc
> 
> template <typename T>
> void ConstraintSolver<T>::PopulatePackedConstraintForcesFromLCPSolution(
> ```

FYI This name breaks the styleguide; Acronyms shouldn't be left in in all caps. I.e., it should be `PopulatePackedConstraintFrocesFromLcpSolution`. Same applies to all of the `*LCP*()` methods.

---

*[multibody/constraint/constraint_solver.h, line 1409 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwWJdD7z2cUituTLDJ:-LFwWJdE2W2Rb08d2DdE:bzbwqow) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L1409)):*
> ```objc
>       num_eq_constraints);
> 
>   // Quit now if zz is empty.
> ```

BTW You should probably update this comment as it no longer reflects the functionality.

---

*[multibody/constraint/constraint_solver.h, line 1413 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFw_-zI4vQ9GlPCuFEn:-LFw_-zI4vQ9GlPCuFEo:b2pbks0) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L1413)):*
> ```objc
>     cf->setZero();
>     if (num_eq_constraints > 0) {
>       VectorX<T> aug = a;
> ```

It is not clear to me why you are copying `a`.

---

*[multibody/constraint/constraint_solver.h, line 1415 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFw_wWe92CLopCYEywl:-LFw_wWe92CLopCYEywm:b-gsrsqb) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L1415)):*
> ```objc
>       VectorX<T> aug = a;
>       const VectorX<T> u = -mlcp_to_lcp_data.A_solve(aug);
>       auto lambda = cf->segment(num_contacts +
> ```

FYI This clearly relies on the various force types to appear in ordered contiguous blocks. However, this doesn't seem to be documented anywhere.

---

*[multibody/constraint/constraint_solver.h, line 2013 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwbyEGEc11I9hmWWsF:-LFwbyEGEc11I9hmWWsG:buhpsdq) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L2013)):*
> ```objc
> 
>   // Check that the blocks are nearly equal.
>   if (nr > 0 && num_contacts > 0)
> ```

This might be more readable if you rephrased these tests as:

```c++
if (F_iM_NT.rows() > 0 && F_iM_NT.cols() > 0) {
  ...
}
```

Similarly, if you *instantiated* the `*_true` variants using their corresponding matrix sizes, then the relationships between the two pairs of matrix will be more obviously coupled.

---

*[multibody/constraint/constraint_solver.h, line 2015 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwdRaS-Lhl9skeAHZl:-LFwdRaS-Lhl9skeAHZm:b-to9blw) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L2015)):*
> ```objc
>   if (nr > 0 && num_contacts > 0)
>     DRAKE_ASSERT((F_iM_NT - F_iM_NT_true).norm() < zero_tol);
>   if (num_contacts > 0 && nl > 0)
> ```

With these new tests, you can move some of the rote invocations above inside these conditionals (not all, but most). 

---

*[multibody/constraint/test/constraint_solver_test.cc, line 2061 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFweYkoC-_yKIz8AySa:-LFweYkoC-_yKIz8AySb:b2kgp8f) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/test/constraint_solver_test.cc#L2061)):*
> ```cpp
>   // Set the rod to a ballistic state.
>   ContinuousState<double>& xc = context_->get_mutable_continuous_state();
>   xc[0] = 0.0;     // com horizontal position
> ```

BTW This is where a named vector would've helped your code.

---

*[multibody/constraint/test/constraint_solver_test.cc, line 2062 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFweR-G7jMFvGQwkki5:-LFweR-G7jMFvGQwkki6:b-mzbjho) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/test/constraint_solver_test.cc#L2062)):*
> ```cpp
>   ContinuousState<double>& xc = context_->get_mutable_continuous_state();
>   xc[0] = 0.0;     // com horizontal position
>   xc[1] = 10.0;     // com vertical position
> ```

FYI Extra space mars your pretty formatting

---

*[multibody/constraint/test/constraint_solver_test.cc, line 2064 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwf6-e0BHLnzF_pWPO:-LFwf6-e0BHLnzF_pWPP:br5a5eo) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/test/constraint_solver_test.cc#L2064)):*
> ```cpp
>   xc[1] = 10.0;     // com vertical position
>   xc[2] = 0.0;     // rod rotation
>   xc[3] = 0.0;     // no horizontal velocity.
> ```

FYI Inconsistent punctuation

---

*[multibody/constraint/test/constraint_solver_test.cc, line 2075 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwgEZyBMlsy6XEL8DR:-LFwgEZyBMlsy6XEL8DS:ba2zyg9) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/test/constraint_solver_test.cc#L2075)):*
> ```cpp
> 
>   // Add in bilateral constraints on rotational motion.
>   vel_data_->G_mult = [](const VectorX<double>& w) -> VectorX<double> {
> ```

BTW The declared return type on this lambda (and the next) is not necessary. It is inferred from the return statement.

---

*[multibody/constraint/test/constraint_solver_test.cc, line 2077 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwg_0QCwI46zvpTlP1:-LFwg_0QCwI46zvpTlP2:b4ehnls) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/test/constraint_solver_test.cc#L2077)):*
> ```cpp
>   vel_data_->G_mult = [](const VectorX<double>& w) -> VectorX<double> {
>     VectorX<double> result(1);   // Only one constraint.
> ```

FYI Did you mean this empty line?

---

*[multibody/constraint/test/constraint_solver_test.cc, line 2084 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwgVkvCHICs05JH66n:-LFwgVkvCHICs05JH66o:b4qtoxg) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/test/constraint_solver_test.cc#L2084)):*
> ```cpp
>   vel_data_->G_transpose_mult =
>       [this](const VectorX<double>& f) -> VectorX<double> {
>         // An impulsive force (torque) applied to the third component needs no
> ```

FYI Indentation error - clang-format this.  

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9054#-:-LFwhI9r4y2VnvzjKVd2:bfo2n50)*

**Comment by edrumwri** [comment]
Thanks for the feature review, Sean. +@sammy-tri for platform review please.

---

Review status: 3 unresolved discussions, platform LGTM from [seancurtis-tri]

---

*[multibody/constraint/constraint_solver.h, line 1413 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFw_-zI4vQ9GlPCuFEn:-LFx6Y9rCOP_MKUr6RLl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L1413)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It is not clear to me why you are copying `a`.
</blockquote></details>

Done.

---

*[multibody/constraint/constraint_solver.h, line 1415 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFw_wWe92CLopCYEywl:-LFx9OAG-v_1y7nSB2xH:b-3y71ib) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L1415)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI This clearly relies on the various force types to appear in ordered contiguous blocks. However, this doesn't seem to be documented anywhere.
</blockquote></details>

PTAL documentation for this function.

---

*[multibody/constraint/constraint_solver.h, line 2013 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwbyEGEc11I9hmWWsF:-LFxATth1AGga5dqhpyt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L2013)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This might be more readable if you rephrased these tests as:

```c++
if (F_iM_NT.rows() > 0 && F_iM_NT.cols() > 0) {
  ...
}
```

Similarly, if you *instantiated* the `*_true` variants using their corresponding matrix sizes, then the relationships between the two pairs of matrix will be more obviously coupled.
</blockquote></details>

Done.

---

*[multibody/constraint/constraint_solver.h, line 2015 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwdRaS-Lhl9skeAHZl:-LFxBCN26Dg3Ec79Lr-F:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L2015)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

With these new tests, you can move some of the rote invocations above inside these conditionals (not all, but most). 
</blockquote></details>

PTAL.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9054#-:-LFxCFBd7t1wONcecwKa:b-tnlfll)*

**Comment by SeanCurtis-TRI** [comment]
Thanks for tackling the LCP vs Lcp thing. In the future, it would be a boon if you had the cosmetic change and the functional changes in separate commits as a service to your reviewer.

---

Reviewed 2 of 2 files at r2.
Review status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM from [seancurtis-tri]

---

*[multibody/constraint/constraint_solver.h, line 2013 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwbyEGEc11I9hmWWsF:-LFxFMWO5i4GEkopNhY7:b-1gqbw4) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L2013)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not *everything* I wished for, but I can take it.

---

*[multibody/constraint/constraint_solver.h, line 2015 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9054#-LFwdRaS-Lhl9skeAHZl:-LFxFPP00f4ZRRkCptLG:b-y0kozr) ([raw file](https://github.com/robotlocomotion/drake/blob/f5c7d17e4c06430b646652cd10d8c4d6030714c8/multibody/constraint/constraint_solver.h#L2015)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

PTAL.
</blockquote></details>

Again, not quite what I asked -- you're still doing work (creation of `_true` invariant) which may never be used, but I'll mark myself as satisfied. This is, after all, a utility function for validation that only runs when assertions are armed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9054#-:-LFxFsai3Nhf3rNTxOtR:b-sqp6tj)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [seancurtis-tri, sammy-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9054#-:-LFxqN8t1dqE2hmSI2i3:bnfp4nl)*

**Pull request merged**
