### PR TITLE
Remove submodules and consolidate CMake options

### LINKED ISSUE #3499: Mysterious CI Failure - Index File Smaller Than Expected, Unable to Recurse Into Submodule Path
# Example Error

```
fatal: index file smaller than expected
Failed to recurse into submodule path 'externals/meshconverters'
```
# Example Logs
- https://drake-jenkins.csail.mit.edu/job/experimental/4742/compiler=gcc,label=linux,type=release/

### LINKED ISSUE #3628: MATLAB dependency names, option names, package names, and submodule names, are inconsistent.
e.g.,

```
option             find_package    submodule     checkDependency.m
------------------------------------------------------------------
WITH_EIGEN         Eigen3          eigen         N/A
WITH_LIBBOT        N/A             libbot        lcmgl
WITH_YAML_CPP      yaml-cpp        yaml_cpp      yaml-cpp
```

### LINKED ISSUE #4034: Mysterious CI Error - could not lock config file
# The Error

```
15:10:33 Cloning into 'drake/doc/textbook'...
15:10:33 Submodule path 'drake/doc/textbook': checked out 'e051917c15a513e1924465060134164c85fe5141'
15:10:33 error: could not lock config file /home/ubuntu/workspace/linux-gcc-ninja-continuous-matlab-debug/.git/modules/drake/doc/textbook/config: File exists
15:10:33 Failed to register url for submodule path 'HTMLBook'
15:10:33 Failed to recurse into submodule path 'drake/doc/textbook'
```

# Example Console Logs

* https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-ninja-continuous-matlab-debug/379/consoleFull

### LINKED ISSUE #4451: Mysterious CI Error: fatal: Not a git repository
# The Error:

```
fatal: Not a git repository: ../../../.git/modules/drake/doc/textbook
```

# Example Logs

https://drake-jenkins.csail.mit.edu/job/linux-clang-ninja-experimental-open-source/1476/

### LINKED ISSUE #4551: Document CMake build "comprehensive nuke"
Sometimes, a CMake-generated build gets confused or produces wrong results.  There's various lore floating around in slack land about how to fix it, especially with the case of `git submodules` being used.

Perhaps we should curate and document one good set of instructions for this, and post it into our sphinx docs.  Then we can always point devs at that best advice, instead of some good-but-not-quite variant from last week's slack or etc.

(This issue was broken out of #1973.)

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #3499, closes #3628, closes #4034, closes #4451, closes #4551.

Ultimately, the CMake externals will be removed, but it will take a little while to get the MATLAB bindings coexisting fully with the Bazel, and this removes the # 1 cause of CI flakes and saves some CI resources.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7134)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review (high priority).

**Comment by jamiesnape** [comment]
Of course, I wrote the PR before the more GitHub archive checksum debacle....

**Comment by fbudin69500** [comment]
:lgtm: once CI fixed.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7134#-:-KvClld5uFqfsxuHC2zK:b6c3a84)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/options.cmake, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7134#-KvDsglBqK3wcFK2Ih9s:-KvDsglBqK3wcFK2Ih9t:b6waek9) ([raw file](https://github.com/robotlocomotion/drake/blob/50626e1e390b92203a826eff492cfd4340e66512/cmake/options.cmake#L228)):*
> ```CMake
>   drake_system_dependency(
>     FMT REQUIRES fmt VERSION 3.0.1
>     "Eigen C++ matrix library")
> ```

BTW Paste-o.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7134#-:-KvDsyv59u0CCCY4p4qN:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/options.cmake, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7134#-KvDsglBqK3wcFK2Ih9s:-KvDuz8Z_745Ab02ON2X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/50626e1e390b92203a826eff492cfd4340e66512/cmake/options.cmake#L228)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Paste-o.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7134)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7134)*

**Pull request merged**
