### PR TITLE
Add python binding for MinimumDistanceConstraint with CollisionChecker.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19921)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19921#-:-Nas9mBR37AYzQNjzAsR:be2t5nx)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
This has enough tricky Python (e.g. keep_alives) that it needs a feature review prior to platform. Please assign a suitable feature reviewer.  -(status: single reviewer ok)  -@sherm1 for now

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19921#-:-NasFzO00sDlzoASvOSy:bqhrp5v)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@EricCousineau-TRI for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19921#-:-NasTHoFB2GDjTYkDEJS:b-g5jkj8)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature, +@sammy-tri for platform, please!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19921#-:-NasgoXX8EHkiMs2F0-a:b2uiefm)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

___
*[`bindings/pydrake/multibody/inverse_kinematics_py.cc` line 529 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19921#-NasgZyz1eXH5jL-dxaa:-NasgZyz1eXH5jL-dxab:b-z7gg89) ([raw file](https://github.com/RobotLocomotion/drake/blob/010b1ca206f8c552bbda270bf05f0be2fa377f05/bindings/pydrake/multibody/inverse_kinematics_py.cc#L529)):*
> ```cpp
>             py::arg("collision_checker_context"), py::arg("penalty_function"),
>             py::arg("influence_distance"),
>             // Keep alive, reference: `self` keeps collision_checker
> ```

nit (here and elsewhere) Should have backticks around `collision_checker` and `collision_checker_context`?

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19921#-:-Navty1T29lb3wOUowMc:bnfp4nl)* status: 1 unresolved discussion

**Pull request merged**
