### PR TITLE
[multibody] Refactor MbP reaction forces output calc

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21623 and therefore also #20545.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21644)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 33 of 36 files at r1, 5 of 5 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21644)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21644)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/multibody_plant.cc` line 3684 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21644#-O0jQGI7B_lyWIPOS_mY:-O0jQGI7B_lyWIPOS_mZ:bigiri) ([raw file](https://github.com/RobotLocomotion/drake/blob/b37c5f229dc783884cc38de26471c5a206244ded/multibody/plant/multibody_plant.cc#L3684)):*
> ```cpp
>       // Nothing after here needs to change w.r.t. output port sampling, since
>       // the swear word `context` doesn't appear anywhere in the below.
>       Fapplied_Bo_W_array, tau_applied, &A_WB_vector, &F_BMo_W_vector, &tau_id);
> ```

This seems awkward and brittle. It makes me think we're taking the wrong approach if we have to do this much hacking to get it to work. At the least I think we should stop treating this as an emergency fix and instead use it to figure out what we're missing from the System Framework that could provide an elegant and maintainable solution.

For example, Simbody's framework has explicit support for discrete variables that are frozen but updated during a step (see [allocateAutoUpdateDiscreteVariable()](https://simbody.github.io/3.7.0/classSimTK_1_1State.html#aaa2b067d10792c14666301c9bf2d77b9)) with principled avoidance of recomputation. That won't translate exactly to Drake since its underlying abstractions are different, but I feel like something along those lines is what we need here.

Looking forward to discussing f2f this afternoon.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21644)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/multibody_plant.cc` line 3684 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21644#-O0jQGI7B_lyWIPOS_mY:-O0jdvktEu6ovwhPN5Uf:bxdteq2) ([raw file](https://github.com/RobotLocomotion/drake/blob/b37c5f229dc783884cc38de26471c5a206244ded/multibody/plant/multibody_plant.cc#L3684)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This seems awkward and brittle. It makes me think we're taking the wrong approach if we have to do this much hacking to get it to work. At the least I think we should stop treating this as an emergency fix and instead use it to figure out what we're missing from the System Framework that could provide an elegant and maintainable solution.

For example, Simbody's framework has explicit support for discrete variables that are frozen but updated during a step (see [allocateAutoUpdateDiscreteVariable()](https://simbody.github.io/3.7.0/classSimTK_1_1State.html#aaa2b067d10792c14666301c9bf2d77b9)) with principled avoidance of recomputation. That won't translate exactly to Drake since its underlying abstractions are different, but I feel like something along those lines is what we need here.

Looking forward to discussing f2f this afternoon.
</blockquote></details>

I agree with Sherm, this seems to indicate a bigger problem.
Maybe the solution we chose is not the right one. I was expecting to be a ble to recover everything needed for ports computations from your `Memory` state, but now I realize that's not true.

Probably we should reconcider Sherm's alternative of having both `x[n]` and `x[n+1]` as states, with the corresponding re-wring of dependencies and cache entries.

**Comment by jwnimmer-tri** [comment]
From f2f -- this approach was overkill, because as it turns out calculating reaction forces is cheap, so the better answer is to do it on every time step, even if nobody is pulling on the output port.  So, we will discard this PR.

A few parts here were small clean-ups for clarity, which have been split off into #21660 and #21661 to follow-up with later on.  (Those PR's are fully cleaned up yet.)

**Pull request closed without merging**
