### PR TITLE
[hotfix] Patch missing fmt_eigen usage in debug logging

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18858)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+(status: single reviewer ok) 
+(priority: high)

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot  mac-arm-monterey-clang-bazel-experimental-debug please

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(release notes: none).

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18858#-:-NOyjTWE3quVJIi2jPNr:b-il7ptu)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@jwnimmer-tri The linux builds have passed and the mac build has gotten past `unrevised_lemke_solver_test` (one of the previous failure points). Shall we simply merge?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18858#-:-NOymAb50Dd9YLClrbnu:b-vpmndz)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
hmmm....mac finished angry. Let me see if it's related.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18858#-:-NOyp4UrCp0TUQj5MDaK:b-btacx3)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Nope. It failed on writing manifests and stats. Merging. It's complaining about running out of space "no space on device".

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18858#-:-NOypLEe2VlLmr1pQb6k:b-yr2kx2)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
