### PR TITLE
[geometry] Support point-to-ellipsoid results in ComputeSignedDistanceToPoint query

### LINKED ISSUE #15227: geometry: ComputeSignedDistanceToPoint does not return distances to Ellipsoids
I've managed to trip myself on this both in c++ (#15194) and in python (below).  The warning tells me to expect the signed distances to ellipsoids to be potentially inaccurate; but in fact no signed distances are returned.   Here is a minimal repro:
```
from pydrake.all import (
    DiagramBuilder, AddMultibodyPlantSceneGraph, SpatialInertia, RigidTransform,
    CoulombFriction, Role, Ellipsoid, Box,
)

def MakeSceneGraphWithShape(shape, X_WG):
  builder = DiagramBuilder()
  plant, scene_graph = AddMultibodyPlantSceneGraph(builder, 0.0)
  instance = plant.AddModelInstance("test")
  body = plant.AddRigidBody("test", instance, SpatialInertia())
  geom_id = plant.RegisterCollisionGeometry(
      body, RigidTransform.Identity(), shape, "test",
      CoulombFriction())
  plant.WeldFrames(plant.world_frame(), body.body_frame(), X_WG)
  plant.Finalize()
  diagram = builder.Build()
  return diagram, scene_graph

diagram, scene_graph = MakeSceneGraphWithShape(Box(1.,1., 1.), RigidTransform.Identity())
context = diagram.CreateDefaultContext()
query = scene_graph.get_query_output_port().Eval(scene_graph.GetMyContextFromRoot(context))
assert query.inspector().NumGeometriesWithRole(Role.kProximity) == 1
assert len(query.ComputeSignedDistanceToPoint([10, 10, 10])) == 1

diagram, scene_graph = MakeSceneGraphWithShape(Ellipsoid(1.,1., 1.), RigidTransform.Identity())
context = diagram.CreateDefaultContext()
query = scene_graph.get_query_output_port().Eval(scene_graph.GetMyContextFromRoot(context))
assert query.inspector().NumGeometriesWithRole(Role.kProximity) == 1
assert len(query.ComputeSignedDistanceToPoint([10, 10, 10])) == 1
```

Results in 
```
[2021-06-22 08:22:13.974] [console] [warning] Ellipsoid is primarily for ComputeContactSurfaces in hydroelastic contact model. The accuracy of other collision queries and signed distance queries are not guaranteed.
---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-3-67dd62655407> in <module>
     27 query = scene_graph.get_query_output_port().Eval(scene_graph.GetMyContextFromRoot(context))
     28 assert query.inspector().NumGeometriesWithRole(Role.kProximity) == 1
---> 29 assert len(query.ComputeSignedDistanceToPoint([10, 10, 10])) == 1
     30 

AssertionError: 
```
Because ComputeSignedDistanceToPoint returns an empty vector.

A bandaid resolution would be to update the warning.  But I'd of course prefer to get the result.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Add point-to-ellipsoid signed distance support

This extends the `ComputeSignedDistanceToPoint()` method to support `Ellipsoid` primitives. Previously, they were simply ignored. The support is partial -- `double` only.

1. Add to `DistanceToPointCallback` to exercise `fcl` in order to produce *some* answer (albeit a sloppy one).
   - Test it.
2. Modify the characterization test for the callback to reflect the new support and the corresponding documentation.
3. This also removes the former warning about `Ellipsoid`s. The distance-to-point query was the only outlier; its support is now clearly documented across all of the proximity queries.

Closes #15227.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@russtedrake for feature review (because you were eager to have it). Feel free to delegate the feature review if you don't have the time.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232#-:-Mcpq6ym16du3q1w_YLn:b-hh8s4e)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15232#-Mcppsnq5K-RIdG_OEwM:-Mcppsnq5K-RIdG_OEwN:bc0t286) (no related file):*
Note to reviewers:

The PR has two commits (and two corresponding initial revisions):

R1: the shapes were ordered without much pattern, so it was difficult to assess what is accounted for and what isn't. I re-ordered declarations, definitions, enumerations so the shapes are ordered alphabetically. Otherwise, there is no change to the code.
R2: This add the actual new code that requires review.

I'd recommend *glancing* at R1 but focusing your review efforts on R2 and subsequent revisions.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
@russtedrake  (see the note below about reviewing the revisions).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232#-:-McpqE8S4G9_3OW1ZbDb:bs0xfce)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@russtedrake +@joemasterjohn Shuffling feature review. @joemasterjohn, please note the review notes in the discussion below (regarding reviewing revision 1 vs all the rest).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232#-:-McyD128BW-hHk3QurGQ:b-lce76u)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
Full pass done. Mostly nits, but I wanted some clarification of a few things. PTAL.

> Reviewed 4 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232#-:-MdRyCTWEtpZNjQYs_UH:b-1lfxis)* status: 6 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15232#-Mcppsnq5K-RIdG_OEwM:-MdRyIKr9sZmswd_z0z5:b7uvfv) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Note to reviewers:

The PR has two commits (and two corresponding initial revisions):

R1: the shapes were ordered without much pattern, so it was difficult to assess what is accounted for and what isn't. I re-ordered declarations, definitions, enumerations so the shapes are ordered alphabetically. Otherwise, there is no change to the code.
R2: This add the actual new code that requires review.

I'd recommend *glancing* at R1 but focusing your review efforts on R2 and subsequent revisions.
</blockquote></details>

Got it. Took a look at R1 for a sanity check. All of the comments pertain to post R2 changes.

---
___
*[geometry/query_object.h, line 566 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRprsj2GC21kEcy0hx:-MdRprsj2GC21kEcy0hy:b-ju5x3d) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/query_object.h#L566)):*
> ```objc
>    - ᵃ Unsupported geometry/scalar combinations are simply ignored; no results
>        are reported for that geometry.
>    - ᵇ As the eccentricity of the ellipsoid increases, this error will get
> ```

nit: Is there any way to say how worse the error gets? Or at the least a suggested maximum eccentricity maybe?
___
*[geometry/proximity/distance_to_point_callback.cc, line 322 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRtu877GxhZPX-xLYe:-MdRtu877GxhZPX-xLYf:b-ksp4kx) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/distance_to_point_callback.cc#L322)):*
> ```cpp
>   if constexpr (std::is_same_v<T, double>) {
>     // TODO(SeanCurtis-TRI): Replace this short-term hack with something that
>     //  provides higher precision and derivatives.
> ```

nit: I'm not convinced that the method described there would immediately provide derivatives. In all cases the closest point is a function of an algebraic number. Some of the cases admit a closed form, but the remaining cases require an iterative root finding algorithm which would break the differentiability. 
___
*[geometry/proximity/distance_to_point_callback.cc, line 371 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRwG9C1k9hyrcLYGeV:-MdRwG9C1k9hyrcLYGeW:b5pci31) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/distance_to_point_callback.cc#L371)):*
> ```cpp
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
>     return SignedDistanceToPoint<T>(geometry_id_, p_GN, result_W.min_distance,
>                                     grad_W, true /*is_grad_w_unique */);
> ```

There are potential query points on the interior of the ellipsoid where `grad_W` is non-unique, no? Do we not care about that here because this is currently only supporting double?
___
*[geometry/proximity/test/distance_to_point_callback_test.cc, line 335 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRwaqvDm2tfNfjIx1i:-MdRwaqvDm2tfNfjIx1j:b-xj92g8) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/test/distance_to_point_callback_test.cc#L335)):*
> ```cpp
> GTEST_TEST(DistanceToPoint, Ellipsoid) {
>   // Provide some arbitrary pose of the ellipsoid G in the world.
>   // const RotationMatrix<double> R_WG(
> ```

nit: did you mean to use this (commented out) arbitrary pose instead of identity? Otherwise I don't see it's purpose as a comment.
___
*[geometry/proximity/test/distance_to_point_callback_test.cc, line 390 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRxzBR5JBjekNs8DbZ:-MdRxzBR5JBjekNs8Db_:b-pvsf9g) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/test/distance_to_point_callback_test.cc#L390)):*
> ```cpp
>   for (const auto& coord : coords) {
>     const auto& [p_GN, n_G] = get_sample(coord.theta, coord.phi);
>     for (const double distance : {-0.125, 0.0, 0.2}) {
> ```

What about a test for potentially problematic query points? (e.g. the origin of the ellipsoid)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed, PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232#-:-MdSdmGWDaCnJFQnRmJF:b-idmig1)* status: 3 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn and @SeanCurtis-TRI)

___
*[geometry/query_object.h, line 566 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRprsj2GC21kEcy0hx:-MdSUBF962aUho-qYX2I:b-trkhuz) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/query_object.h#L566)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Is there any way to say how worse the error gets? Or at the least a suggested maximum eccentricity maybe?
</blockquote></details>

Done

Sadly not. It depends on eccentricity and relative configuration both. I'll elaborate the comment.
___
*[geometry/proximity/distance_to_point_callback.cc, line 322 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRtu877GxhZPX-xLYe:-MdSa4RJ7sfuYD5Ma8Ge:b-93iyv2) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/distance_to_point_callback.cc#L322)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: I'm not convinced that the method described there would immediately provide derivatives. In all cases the closest point is a function of an algebraic number. Some of the cases admit a closed form, but the remaining cases require an iterative root finding algorithm which would break the differentiability. 
</blockquote></details>

Done

To be perfectly frank, I don't completely trust my intuition on this.

I *know* that I can compute an approximate derivative via finite differences. I also know that if I use an `AutoDiffXd` scalar in that operation, that *its* derivative is an approximation of the second derivative. So, that's an example of a numerical approximation that produces derivatives. Where my intuition betrays me is at the point where I determine what lesson I can infer from it. I don't have a strong sense for the distinction between that and root finding vis a vis derivatives. I have to ponder it - maybe do some root finding on a trivial problem and see what happens.

So, in the shade of doubt, I've modified the TODO message.
___
*[geometry/proximity/distance_to_point_callback.cc, line 371 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRwG9C1k9hyrcLYGeV:-MdSXvLiCn0yEkXnm3of:b56e7pz) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/distance_to_point_callback.cc#L371)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

There are potential query points on the interior of the ellipsoid where `grad_W` is non-unique, no? Do we not care about that here because this is currently only supporting double?
</blockquote></details>

The bigger issue is that that particular field is deprecated. It's always been a crappy lie that users should ignore. The fact that it's being used at all here is because we're still during the deprecation period.
___
*[geometry/proximity/test/distance_to_point_callback_test.cc, line 335 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRwaqvDm2tfNfjIx1i:-MdSYRzqEkar8fIU2qbK:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/test/distance_to_point_callback_test.cc#L335)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: did you mean to use this (commented out) arbitrary pose instead of identity? Otherwise I don't see it's purpose as a comment.
</blockquote></details>

Done
___
*[geometry/proximity/test/distance_to_point_callback_test.cc, line 390 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRxzBR5JBjekNs8DbZ:-MdSYy5aE5-0RGETdIr5:b-qpa7mm) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/test/distance_to_point_callback_test.cc#L390)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

What about a test for potentially problematic query points? (e.g. the origin of the ellipsoid)
</blockquote></details>

Done

I've tested what can be.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: thanks! +@ericcousineau-tri for platform review tomorrow, please.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232#-:-MdTnfNr76ruP6ix47J5:b-83favm)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[geometry/query_object.h, line 566 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRprsj2GC21kEcy0hx:-MdT4d8QDFuay7NuX7Yi:b-1f6qc2) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/query_object.h#L566)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

Sadly not. It depends on eccentricity and relative configuration both. I'll elaborate the comment.
</blockquote></details>

Got it. Comment looks good.
___
*[geometry/proximity/distance_to_point_callback.cc, line 322 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRtu877GxhZPX-xLYe:-MdTftkXDXE_e9z_1-BV:b-t11ne6) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/distance_to_point_callback.cc#L322)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

To be perfectly frank, I don't completely trust my intuition on this.

I *know* that I can compute an approximate derivative via finite differences. I also know that if I use an `AutoDiffXd` scalar in that operation, that *its* derivative is an approximation of the second derivative. So, that's an example of a numerical approximation that produces derivatives. Where my intuition betrays me is at the point where I determine what lesson I can infer from it. I don't have a strong sense for the distinction between that and root finding vis a vis derivatives. I have to ponder it - maybe do some root finding on a trivial problem and see what happens.

So, in the shade of doubt, I've modified the TODO message.
</blockquote></details>

Ok, thanks for the updated comment. Given the coefficients of the polynomial are functions of the independent variables I could write by hand the partial derivative of a root of that polynomial w.r.t. one of the input parameters. But, it requires evaluating derivatives of the polynomial at that root, so it could only be computed after the root is found. So it is definitely possible to construct the derivatives after the fact. But, I think forward mode AD would be out of the question given the way root finding algorithms initialize that root. 


It definitely will take a bit more careful thought, but we can leave it until needed.
___
*[geometry/proximity/distance_to_point_callback.cc, line 371 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRwG9C1k9hyrcLYGeV:-MdTnLf6CgYnDwdO-PGo:b-ohg0l) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/distance_to_point_callback.cc#L371)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The bigger issue is that that particular field is deprecated. It's always been a crappy lie that users should ignore. The fact that it's being used at all here is because we're still during the deprecation period.
</blockquote></details>

OK, thanks for letting me know.
___
*[geometry/proximity/test/distance_to_point_callback_test.cc, line 390 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdRxzBR5JBjekNs8DbZ:-MdTnbdV-sGphAX78U3d:brujzsz) ([raw file](https://github.com/robotlocomotion/drake/blob/9961e65a201b6c3daeb59715a1f297f4f870702f/geometry/proximity/test/distance_to_point_callback_test.cc#L390)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

I've tested what can be.
</blockquote></details>

OK, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15232#-Mcppsnq5K-RIdG_OEwM:-MdXJh96-n9wk3hE0H04:b-w196av) (no related file):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Got it. Took a look at R1 for a sanity check. All of the comments pertain to post R2 changes.
</blockquote></details>

OK Thanks!

---
___
*[geometry/proximity/distance_to_point_callback.cc, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdXJYJQBTnngxiFO-fi:-MdXJYJQBTnngxiFO-fj:b21q3qo) ([raw file](https://github.com/robotlocomotion/drake/blob/88da7069e5cf8651eb7550db15881de30b5bc1ff/geometry/proximity/distance_to_point_callback.cc#L175)):*
> ```cpp
> 
> template <typename T>
> SignedDistanceToPoint<T> DistanceToPoint<T>::operator()(const fcl::Boxd& box) {
> ```

nit Given that you took the time to reorder this code in at least two places, consider cross-referencing between the two and state that the order of Shape classes should be maintained?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with a couple of minor nits

> Reviewed 1 of 6 files at r2, 1 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232#-:-MdXMm46C-ZwTYtFC4zx:b-ph2g1j)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[geometry/query_object.h, line 566 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdXMTxvAgywkyL7yBNY:-MdXMTxvAgywkyL7yBNZ:b-g4ylwi) ([raw file](https://github.com/robotlocomotion/drake/blob/04c3194b23f25e0b6236d11132cd853b706135c7/geometry/query_object.h#L566)):*
> ```objc
>    - ᵃ Unsupported geometry/scalar combinations are simply ignored; no results
>        are reported for that geometry.
>    - ᵇ As the eccentricity of the ellipsoid increases, this error may get
> ```

nit From skimming this document in isolation, I'm not sure if I saw why this error is so much higher. (for this or other cases?)

Given that it seems empirical in some cases, is it worth citing FCL (GJK / EPA) explicitly here, given that it's the only relevant algorithm atm?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232#-:-MdXfRKTEejOqYGgBEpb:bel95ya)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @joemasterjohn)

___
*[geometry/query_object.h, line 566 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdXMTxvAgywkyL7yBNY:-MdXd_ZS4VX3r-k8WVn4:bf34ijz) ([raw file](https://github.com/robotlocomotion/drake/blob/04c3194b23f25e0b6236d11132cd853b706135c7/geometry/query_object.h#L566)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit From skimming this document in isolation, I'm not sure if I saw why this error is so much higher. (for this or other cases?)

Given that it seems empirical in some cases, is it worth citing FCL (GJK / EPA) explicitly here, given that it's the only relevant algorithm atm?
</blockquote></details>

Done. 
I've elaborated.
___
*[geometry/proximity/distance_to_point_callback.cc, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdXJYJQBTnngxiFO-fi:-MdXdfA9DR8f1FwRJG18:bsdycn4) ([raw file](https://github.com/robotlocomotion/drake/blob/88da7069e5cf8651eb7550db15881de30b5bc1ff/geometry/proximity/distance_to_point_callback.cc#L175)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Given that you took the time to reorder this code in at least two places, consider cross-referencing between the two and state that the order of Shape classes should be maintained?
</blockquote></details>

OK

Alphabetical ordering is pretty obvious. And I'm propagating that pattern around the rest of geometry. So, I don't think that it'll be necessary to be explicit about it.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[geometry/query_object.h, line 566 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdXMTxvAgywkyL7yBNY:-MdY6QVh4QLwkZEd1azY:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/04c3194b23f25e0b6236d11132cd853b706135c7/geometry/query_object.h#L566)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done. 
I've elaborated.
</blockquote></details>

OK Thanks!
___
*[geometry/proximity/distance_to_point_callback.cc, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15232#-MdXJYJQBTnngxiFO-fi:-MdY6NqQ1jTkdo5pFS6k:bl00cdx) ([raw file](https://github.com/robotlocomotion/drake/blob/88da7069e5cf8651eb7550db15881de30b5bc1ff/geometry/proximity/distance_to_point_callback.cc#L175)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

OK

Alphabetical ordering is pretty obvious. And I'm propagating that pattern around the rest of geometry. So, I don't think that it'll be necessary to be explicit about it.
</blockquote></details>

OK SGTM!

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15232#-:-MdYcLMd30xxZw9o9HSm:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn (waiting on @SeanCurtis-TRI)

**Pull request merged**
