### PR TITLE
[workspace] Upgrade petsc to latest release v3.17.1

### LINKED ISSUE #17093: Upgrade externals to latest - May 2022
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue: #16879

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a rework of #17119.  Closes #17093.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17273)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
Waiting for CI to confirm no linker error. Otherwise :lgtm: 
(Thanks for helping with maintaining @jwnimmer-tri @betsymcphail).

> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17273#-:-N301jVe3eB5bS_RIQoe:b-g8ke67)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17273#-:-N30LY721O81XUNJaK4W:bnfp4nl)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
