### PR TITLE
Revert "Add in the prerequisites for using the system version of libc…

### PR DESCRIPTION
**Pull request by clalancette**
…cd."

This reverts commit 674703bd126560d99f02b5959905d916fea516d0.

@BetsyMcPhail FYI, we'll have to update the Xenial and Mac images with this.  Sorry for the back and forth on this one.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7398)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FWIW I think we can leave the image bump until the next addition that rolls around.  Having extra things installed is unlikely to be a problem?

**Comment by clalancette** [comment]
> FWIW I think we can leave the image bump until the next addition that rolls around. Having extra things installed is unlikely to be a problem?

Yeah, that's totally fine with me.  Just cleaning up after myself, as suggested in https://github.com/RobotLocomotion/drake/pull/7371#issuecomment-341175911

**Comment by jamiesnape** [comment]
:lgtm: (feature)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7398#-:-KxxkvlSUrJ4gYS-Pfsp:b8j5bpo)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7398#-:-Kxy-LI6N89Gg847z1Yi:bnfp4nl)*

**Pull request merged**
