### PR TITLE
Implements BezierCurve::AsLinearInControlPoints()

### PR DESCRIPTION
**Pull request by RussTedrake**
This will enable us to write many optimizations over Bezier curves without resorting to symbolic Expression parsing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19867)

### CODE REVIEW

**Comment by RussTedrake** [comment]
*[`common/trajectories/bezier_curve.h` line 67 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-Nac9YXu3p8j_0vU67uc:-Nac9YXu3p8j_0vU67ud:b-tksvw1) ([raw file](https://github.com/RobotLocomotion/drake/blob/39ee398e4c54eae424642808273313a7e314bf6e/common/trajectories/bezier_curve.h#L67)):*
> ```objc
>    is the reason that we do not return, for instance,
>    `vec(all_deriv_control_points) = N * vec(original_control_points)`.
>    @pre derivative_order >= 0. */
> ```

btw -- I could see an argument for returning M as the transpose of what I'm returning right now.  As you can see in #19873, I use the transpose to write the constraint, and taking the transpose of a SparseMatrix is relatively expensive.

I think the current version is a bit cleaner mathematically, but since `AddLinearConstraint` takes constraints in the form Ax <= b, I do think using the transpose is likely to be a bit more common.

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19867)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/bezier_curve.h` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-NaYDeTY-0xmudNbh0YR:-NaYDeTY-0xmudNbh0YS:b-7fib14) ([raw file](https://github.com/RobotLocomotion/drake/blob/a854a9b261d10169043b6b7de8a58132bd9cd0d2/common/trajectories/bezier_curve.h#L68)):*
> ```objc
>    `vec(all_deriv_control_points) = N * vec(original_control_points)`.
>    @pre derivative_order >= 0. */
>   Eigen::SparseMatrix<double> DerivativeControlPointCoefficients(
> ```

Maybe `CoefficientMatrix` or `ControlPointCoefficients` is more concise, since one can pass in derivative_order=0?
___
*[`common/trajectories/bezier_curve.h` line 67 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-Nac9YXu3p8j_0vU67uc:-NaconJb0u5-V4qkYsEg:b-ip5kyj) ([raw file](https://github.com/RobotLocomotion/drake/blob/39ee398e4c54eae424642808273313a7e314bf6e/common/trajectories/bezier_curve.h#L67)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- I could see an argument for returning M as the transpose of what I'm returning right now.  As you can see in #19873, I use the transpose to write the constraint, and taking the transpose of a SparseMatrix is relatively expensive.

I think the current version is a bit cleaner mathematically, but since `AddLinearConstraint` takes constraints in the form Ax <= b, I do think using the transpose is likely to be a bit more common.
</blockquote></details>

I agree. The coefficient Matrix on the left hand side seems more common. derivative.control_points().transpose( = M*this.control_points().transpose(). One can argue that the transpose is "unclean", but I think multiplying with a matrix on the rhs is more "unclean" :) 
___
*[`common/trajectories/bezier_curve.cc` line 132 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-Nad0y3J7-KW1YGbE4N_:-Nad0y3J7-KW1YGbE4Na:b-a7492o) ([raw file](https://github.com/RobotLocomotion/drake/blob/39ee398e4c54eae424642808273313a7e314bf6e/common/trajectories/bezier_curve.cc#L132)):*
> ```cpp
>     // M *= deltaM isn't supported for SparseMatrix.
>     SparseMatrix<double> Mprev = std::move(M);
>     M = Mprev * deltaM;
> ```

Instead the following worked for me.



_Suggestion:_
```cpp
    M = M * deltaM;
```

**Review by RussTedrake — COMMENTED** [review]
+@ggould-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-:-NafGc10BIUx_avLMlP-:bcav8r0)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

___
*[`common/trajectories/bezier_curve.h` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-NaYDeTY-0xmudNbh0YR:-NafFtWO1bdFyXI0BuSK:b-l9ety7) ([raw file](https://github.com/RobotLocomotion/drake/blob/a854a9b261d10169043b6b7de8a58132bd9cd0d2/common/trajectories/bezier_curve.h#L68)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Maybe `CoefficientMatrix` or `ControlPointCoefficients` is more concise, since one can pass in derivative_order=0?
</blockquote></details>

done. I thought about it, and went with `AsLinearInControlPoints()` since I think it's the most clear.  WDYT?
___
*[`common/trajectories/bezier_curve.h` line 67 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-Nac9YXu3p8j_0vU67uc:-NafG0kp4SOPUG7_nDo4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/39ee398e4c54eae424642808273313a7e314bf6e/common/trajectories/bezier_curve.h#L67)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

I agree. The coefficient Matrix on the left hand side seems more common. derivative.control_points().transpose( = M*this.control_points().transpose(). One can argue that the transpose is "unclean", but I think multiplying with a matrix on the rhs is more "unclean" :) 
</blockquote></details>

Done.
___
*[`common/trajectories/bezier_curve.cc` line 132 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-Nad0y3J7-KW1YGbE4N_:-Naf8VTwCqAleymp1qcc:bq0fctj) ([raw file](https://github.com/RobotLocomotion/drake/blob/39ee398e4c54eae424642808273313a7e314bf6e/common/trajectories/bezier_curve.cc#L132)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Instead the following worked for me.
</blockquote></details>

I don't think that would be correct.  https://eigen.tuxfamily.org/dox/group__TopicAliasing.html 

SparseMatrix has less immediate support for (no)aliasing, so I've done it manually here.

**Review by wrangelvid — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-:-NagM9OPDUMbvzHN2vzZ:bg7igkv)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-:-NagkzgS1IH8fncDZTSr:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`common/trajectories/bezier_curve.cc` line 103 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19867#-NagkaPmDwYydZ0WUXK-:-NagkaPmDwYydZ0WUXK0:b-nmm88y) ([raw file](https://github.com/RobotLocomotion/drake/blob/c1069dbf64fcaefc357c29454656794b8e8df73e/common/trajectories/bezier_curve.cc#L103)):*
> ```cpp
>   DRAKE_THROW_UNLESS(derivative_order >= 0);
>   if (derivative_order > order()) {
>     return SparseMatrix<double>(0, order() + 1);  // return the empty matrix.
> ```

nit: Capitalize complete sentence.



_Suggestion:_
```cpp
Return 
```

**Comment by RussTedrake** [comment]
+@wrangelvid for feature review.  (to make reviewable happy)

**Pull request merged**
