### PR TITLE
[workspace] Upgrade curl_internal to latest release 8.11.0

### PR DESCRIPTION
**Pull request by nicolecheetham**
Towards: #22240

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22256)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: as co-author.

+@SeanCurtis-TRI for both reviews per schedule, please.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22256#-:-ODNxFJ47X6L4kG5-hdJ:b1wo0pk)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22256)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22256#-ODNxUiy8mEmOZVT-KMO:-ODNxUiy8mEmOZVT-KMP:b20eq3y) (no related file):*
Working

Make sure at least one macOS build has passed, before we land this.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22256)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22256#-ODNxUiy8mEmOZVT-KMO:-ODOd8jv5eMWREFmkF4f:b32w0x) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Make sure at least one macOS build has passed, before we land this.
</blockquote></details>

OK

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: single reviewer ok) 

:LGTM:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22256#-:-ODgKpfl1qBWoaE8O7YF:b-6e4oo6)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22256#-:-ODgKvePAaO0wjEpkeNP:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
