### PR TITLE
[workspace] install flask for unit tests

### PR DESCRIPTION
**Pull request by svenevs**
Prerequisite for #16822, CI images will need to be updated by Kitware.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.

Expectation: standard CI jobs will fail, unprovisioned will succeed.

**Review by svenevs — COMMENTED** [review]
+@zachfang for feature review please.  This should not be merged until (a) platform approves and (b) Kitware has rebuilt the CI images and removes do-not-merge label.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864#-:-MyxBiy37d7mNAngNpuv:bbrupjo)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @zachfang)

**Review by svenevs — COMMENTED** [review]
Results appear to be good, we will re-run this PR with updated images after they are built as well.

- [linux-bionic-clang-bazel-experimental-everything-release](https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-experimental-everything-release/13497/consoleFull): `[2:28:52 PM]  AssertionError: False is not true : Cannot import flask.`
- [linux-bionic-unprovisioned-clang-bazel-experimental-everything-release](https://drake-jenkins.csail.mit.edu/job/linux-bionic-unprovisioned-clang-bazel-experimental-everything-release/7/consoleFull): `[3:15:10 PM]  //geometry/render/dev:py/flask_import_test                               PASSED in 0.4s`
- [linux-focal-unprovisioned-clang-bazel-experimental-everything-release](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/15/consoleFull): `[3:18:09 PM]  //geometry/render/dev:py/flask_import_test                               PASSED in 0.5s`
- [mac-big-sur-unprovisioned-clang-bazel-experimental-release](https://drake-jenkins.csail.mit.edu/job/mac-big-sur-unprovisioned-clang-bazel-experimental-release/46/consoleFull): `[5:16:52 PM]  //geometry/render/dev:py/flask_import_test                               PASSED in 0.6s`
    - Note: I only ran one unprovisioned mac job (big sur) since they both use the same files for setup.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864#-:-Myxo9edAZi6FhnLBvyk:b-xcdfw7)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
:lgtm: with some suggestions about the README.

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864#-:-Mz0lHdoCDZhY_wVp2nR:b-ipwk0k)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/render_server/README.md, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16864#-Mz0ktze1BqtDQzMQAsD:-Mz0ktze1BqtDQzMQAsE:b33zlgi) ([raw file](https://github.com/robotlocomotion/drake/blob/720d297f8934bea1c9123f72b2b2c28a7c57de91/geometry/render/dev/render_server/README.md#L15)):*
> ```Markdown
> depending on how you ran drake's `setup/` scripts and which platform you are on.
> `flask` is required to run the test server, and is a "test-only" requirement
> for drake.  To use the server you will need to install `flask`.
> ```

BTW
To me, `To use the server you will need to install flask.`is well covered by the added section `flask is required to run the test server`.
___
*[geometry/render/dev/render_server/README.md, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16864#-Mz0kFsv59aLtFlyFRsG:-Mz0kFsv59aLtFlyFRsH:b-m5ontp) ([raw file](https://github.com/robotlocomotion/drake/blob/720d297f8934bea1c9123f72b2b2c28a7c57de91/geometry/render/dev/render_server/README.md#L17)):*
> ```Markdown
> for drake.  To use the server you will need to install `flask`.
> 
> The easiest way to install install the requirements is to run
> ```

duplicated `install`
___
*[geometry/render/dev/render_server/README.md, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16864#-Mz0kIIgAeU7KZ43p5cV:-Mz0kIIgAeU7KZ43p5cW:bhulb1j) ([raw file](https://github.com/robotlocomotion/drake/blob/720d297f8934bea1c9123f72b2b2c28a7c57de91/geometry/render/dev/render_server/README.md#L25)):*
> ```Markdown
> #### Ubuntu
> 
> Option 1: use the system package manager.
> ```

nit: I wonder if it's clearer to just categorize `sudo ./setup/ubuntu/install_prereqs.sh` as option 1 and emphasize that's the recommended way to go.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @zachfang)

___
*[geometry/render/dev/render_server/README.md, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16864#-Mz0ktze1BqtDQzMQAsD:-Mz1DRIEENKF4SGzH5gX:b-frx0n2) ([raw file](https://github.com/robotlocomotion/drake/blob/720d297f8934bea1c9123f72b2b2c28a7c57de91/geometry/render/dev/render_server/README.md#L15)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW
To me, `To use the server you will need to install flask.`is well covered by the added section `flask is required to run the test server`.
</blockquote></details>

Done... you're absolutely right...
___
*[geometry/render/dev/render_server/README.md, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16864#-Mz0kFsv59aLtFlyFRsG:-Mz1JhII7PQ8xXl41zH9:beviwa0) ([raw file](https://github.com/robotlocomotion/drake/blob/720d297f8934bea1c9123f72b2b2c28a7c57de91/geometry/render/dev/render_server/README.md#L17)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

duplicated `install`
</blockquote></details>

Done, removed ... sorry x0
___
*[geometry/render/dev/render_server/README.md, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16864#-Mz0kIIgAeU7KZ43p5cV:-Mz1JkCW-BxJXGsuvUNc:b7jteih) ([raw file](https://github.com/robotlocomotion/drake/blob/720d297f8934bea1c9123f72b2b2c28a7c57de91/geometry/render/dev/render_server/README.md#L25)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: I wonder if it's clearer to just categorize `sudo ./setup/ubuntu/install_prereqs.sh` as option 1 and emphasize that's the recommended way to go.
</blockquote></details>

Done.  I decided to just simplify this more and fold it into one step since the platform specific notes are pointlessly long for little benefit.

**Review by zachfang — COMMENTED** [review]
Feature review done pending on the CI result.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864#-:-Mz1LyyV8LxCKa3_IiyP:b-ll231j)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

**Review by zachfang — COMMENTED** [review]
+@ggould-tri for the platform review for only the `setup/**/requirements-test-only.txt` files.

This PR adds the `flask` python library as a test-only dependency for the tests of the upcoming RenderRpc PRs. The CI is failing now because we need to rebuild the images after getting approval from the platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864#-:-MzFg27A3HKH0-jSQ_Au:bbtul7j)* status: LGTM missing from assignee ggould-tri(platform), labeled "do not merge" (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: pending image rebuild and subsequent test passing.

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864#-:-MzG1sdr0ImyIC285RQo:b8j4g3v)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @svenevs)

___
*[geometry/render/dev/BUILD.bazel, line 143 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16864#-MzG1CQqEWciLUsIlxdE:-MzG1CQqEWciLUsIlxdF:bmtlf8k) ([raw file](https://github.com/robotlocomotion/drake/blob/f1693a1c6f3dfb469945d89a6ef258941a70576a/geometry/render/dev/BUILD.bazel#L143)):*
> ```Starlark
> # NOTE: see geometry/render/dev/render_server/README.md for installation
> # instructions to run this server, flask is only installed for testing.
> # TODO(svenevs): this test confirms `flask` can be imported, not run.  Remove
> ```

minor:  `TODO(#16822)` is the usual spelling for TODOs gated on specific issues/PRs.

**Review by svenevs — COMMENTED** [review]
Thanks for the reviews!  We'll be doing this update in tandem with a `bazel` upgrade in #16878.

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864#-:-MzGVL6BAdaTRD-_RjzX:b-qsaz3)* status: labeled "do not merge" (waiting on @ggould-tri, @svenevs, and @zachfang)

___
*[geometry/render/dev/BUILD.bazel, line 143 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16864#-MzG1CQqEWciLUsIlxdE:-MzGVCh1BWQNfMjhr9-j:b-2i282p) ([raw file](https://github.com/robotlocomotion/drake/blob/f1693a1c6f3dfb469945d89a6ef258941a70576a/geometry/render/dev/BUILD.bazel#L143)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  `TODO(#16822)` is the usual spelling for TODOs gated on specific issues/PRs.
</blockquote></details>

Done, good to know -- thanks :slightly_smiling_face:

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864)* status: labeled "do not merge" (waiting on @svenevs)

**Comment by BetsyMcPhail** [comment]
CI has been update.

@drake-jenkins-bot retest this please

**Comment by svenevs** [comment]
FYI `EC2 (us-east-1) - drake-linux-bionic-2022-03-14-c5d.4xlarge (i-0ec50a8aa1da0cec5)`  (images have been updated, but jenkins is still using the old one due to build queue and caching.  Will be rerunning this later :+1:

**Comment by svenevs** [comment]
2020-03-28 images are now active in jenkins

@drake-jenkins-bot retest this please

**Review by svenevs — COMMENTED** [review]
:lgtm: success with the new images.

> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16864#-:-MzHa4M58niPhzXn3h_h:br7fogp)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),zachfang (waiting on @svenevs)

**Pull request merged**
