### PR TITLE
[optimization] Split convex_set_test into solver vs non-solver

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19258.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19260)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-leak-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-mosek-leak-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-mosek-thread-sanitizer please

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for both reviews per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19260#-:-NToG6A4BB0MX_1O04e8:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`geometry/optimization/test/convex_set_solving_test.cc` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19260#-NToES1x3hmE5cdAtZfk:-NToES1x3hmE5cdAtZfl:bl5oxlr) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee10ad85c933b17491c2669034531916c89d83e8/geometry/optimization/test/convex_set_solving_test.cc#L41)):*
> ```cpp
>   EXPECT_FALSE(set_A.IntersectsWith(set_C));
>   EXPECT_FALSE(set_C.IntersectsWith(set_A));
> }
> ```

nit:  I am surprised that A∩A, B∩B, C∩C are not tested here as well; I'm more surprised that that doesn't seem to be tested anywhere else either.

Author's discretion to keep this pure refactor; it just seemed a bit weird.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19260)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @jwnimmer-tri)

___
*[`geometry/optimization/test/convex_set_solving_test.cc` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19260#-NToES1x3hmE5cdAtZfk:-NToHbWd8plXdgr4oLhq:b67s6jx) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee10ad85c933b17491c2669034531916c89d83e8/geometry/optimization/test/convex_set_solving_test.cc#L41)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  I am surprised that A∩A, B∩B, C∩C are not tested here as well; I'm more surprised that that doesn't seem to be tested anywhere else either.

Author's discretion to keep this pure refactor; it just seemed a bit weird.
</blockquote></details>

Yeah, for a CI hotfix that loses git history, I'm not going to change the test body at all.

**Pull request merged**
