### PR TITLE
[doc] Add release notes v1.4.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Targeting June ~13th~ _19th_ for the release.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17343)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17343)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17343#-N4mGTRE7Q8IhTAG1omw:-N4mGTRF45bYbOK-_MQn:bjksdzn) (no related file):*
Working

Do not merge until we have release candidate builds in hand, estimated to be 2022-06-19.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri for (basic) review
:lgtm: with small nit

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17343#-:-N4njMuP4dpfSMKD3H9-:boit711)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.4.0.md` line 138 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17343#-N4nj-9s0fS2ZJg9pJKm:-N4nj-9s0fS2ZJg9pJKn:b-ou4ql8) ([raw file](https://github.com/robotlocomotion/drake/blob/b7aee8e644d08792c8798848bef028146962e477/doc/_release-notes/v1.4.0.md#L138)):*
> ```Markdown
> * Build NLopt from source; upgrade to 2.7.1 ([#17288][_#17288])
> * Upgrade abseil_cpp_internal to latest commit ([#17322][_#17322], [#17352][_#17352])
> * Update clang-cindex-python3 to latest commit ([#17315][_#17315])
> ```

nit `Update` is inconsistent with other usages, `Upgrade`

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17343)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17343)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-documentation please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17343)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17343#-N4mGTRE7Q8IhTAG1omw:-N55WWfGD7Dwyb4IyYdz:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Do not merge until we have release candidate builds in hand, estimated to be 2022-06-19.
</blockquote></details>

Done.

___

**Pull request merged**
