### PR TITLE
adds @system doxygen block for MBP

### PR DESCRIPTION
**Pull request by RussTedrake**
image

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11686)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@amcastro-tri I think the background information you're missing is that by convention the names in the figure are the _string port names_, i.e., the `port.get_name()` for all ports.

**Comment by jwnimmer-tri** [comment]
@amcastro-tri To be fair, I think most of your defects are valid, it's just that they are not defects on the overview doc, but rather on the code itself.  The fact that the string port names and C++ port getter method names diverge is a bug on its own.

**Comment by jwnimmer-tri** [comment]
(The discussions are blocking on @sammy-tri, not @amcastro-tri.)

I think the two open comments about port names being inconsistent with their getters are valid, but correct not to change in this PR.  Maybe open an issue to fix them in the future though (or add TODOs), so that the inconsistency does not last forever.

**Comment by RussTedrake** [comment]
@jwnimmer-tri -- i believe I've left a trail in to repair the string names in #12214.

**Comment by jwnimmer-tri** [comment]
Okay.  I read that issue to mean "add a new framework feature" not "be sure to repair MBP".

**Pull request merged**
