### PR TITLE
Remove (most) examples from CMake build

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129. Leaving Atlas (used by drake/systems) and kuka_iiwa_arm (used by spartan).

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6441)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm: 

---

Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHmM4dyf_PEwKWmMv:-KnjHmM4dyf_PEwKWmMw:b-8v19kz) (no related file):*
What's the plan for Bazel possibly installing the models (i.e., data files) from `examples`?

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjI8SwE8gMMBpuh-4x:-KnjI8SxAkQrSd9L7-4P:bn36n6w) (no related file):*
I need to double-check that all of this code has BUILD files in place.  Will post back here soon.

---

*[drake/examples/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjGEfCVLcmDdCY6AKl:-KnjGEfDO_jTcaWnr0SI:by8r2u9) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/drake/examples/CMakeLists.txt#L2)):*
> ```CMake
> drake_install_headers(
>     examples_package_map.h)
> ```

This file is dead code and is not known to Bazel.  Can we either remove it in this PR, or elsewhere track that we need to remove it?

---

*[drake/examples/kuka_iiwa_arm/CMakeLists.txt, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHZX7aWA0Ik9Y_AM3:-KnjHZX8zuxDXfneL0MT:b-conq0y) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/drake/examples/kuka_iiwa_arm/CMakeLists.txt#L104)):*
> ```CMake
> 
> add_subdirectory(controlled_kuka)
> add_subdirectory(dev)
> ```

I'm not sure why only this one thing gets removed?  Is this per some kind of separate discussion with the kuka team?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-:-KnjHkVtTGAVY4PlU5x8:bg7igkv)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjGEfCVLcmDdCY6AKl:-KnjIzrDUNxFqM25TJcT:b-80tlqk) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/drake/examples/CMakeLists.txt#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This file is dead code and is not known to Bazel.  Can we either remove it in this PR, or elsewhere track that we need to remove it?
</blockquote></details>

Sure.

---

*[drake/examples/kuka_iiwa_arm/CMakeLists.txt, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHZX7aWA0Ik9Y_AM3:-KnjITEix2xhMa7lpcVJ:b-e970el) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/drake/examples/kuka_iiwa_arm/CMakeLists.txt#L104)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure why only this one thing gets removed?  Is this per some kind of separate discussion with the kuka team?
</blockquote></details>

Actually, all the subdirectories should go. Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6441)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/kuka_iiwa_arm/CMakeLists.txt, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHZX7aWA0Ik9Y_AM3:-KnjJGUBfCaWm2Pm2wtX:bejnk09) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/drake/examples/kuka_iiwa_arm/CMakeLists.txt#L104)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Actually, all the subdirectories should go. Will fix.
</blockquote></details>

Still unclear on why only some of the CMake goes and some stays (i.e., what's the dividing line).  Hold-over glue for Spartan transition?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6441)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHmM4dyf_PEwKWmMv:-KnjJcFX1WdhwTznoNfu:b-vo0ajp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What's the plan for Bazel possibly installing the models (i.e., data files) from `examples`?
</blockquote></details>

Sure, unless the plan has changed from the days of CMake, @RussTedrake wanted all the examples to be part of redistributable packages..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6441)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHmM4dyf_PEwKWmMv:-KnjKJHGbAA_rEcu0VSg:b-vrkrnu) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Sure, unless the plan has changed from the days of CMake, @RussTedrake wanted all the examples to be part of redistributable packages..
</blockquote></details>

Should we block CMakeLists turn-down on verifying that an appropriate `install` dependency is listed in `//:BUILD.bazel`?  The example models don't seem to be there yet.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjI8SwE8gMMBpuh-4x:-KnjM1MxFpknUOsbbr02:b-p4sxf5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I need to double-check that all of this code has BUILD files in place.  Will post back here soon.
</blockquote></details>

All good; `drake/examples` is fully-covered by Bazel, other than the `examples_package_map.h` already noted in a different discussion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6441)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 7 files at r2.
Review status: 39 of 40 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6441)*

**Comment by jamiesnape** [comment]
Review status: 39 of 40 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHmM4dyf_PEwKWmMv:-KnjOYETGPL-V1HOiCDT:b-p5dmxg) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Should we block CMakeLists turn-down on verifying that an appropriate `install` dependency is listed in `//:BUILD.bazel`?  The example models don't seem to be there yet.
</blockquote></details>

We could, though in practice, CMake did not package them either. I can add something to this PR.

---

*[drake/examples/kuka_iiwa_arm/CMakeLists.txt, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHZX7aWA0Ik9Y_AM3:-KnjPLmoYXcdZdU0WfqZ:b-edltqr) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/drake/examples/kuka_iiwa_arm/CMakeLists.txt#L104)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Still unclear on why only some of the CMake goes and some stays (i.e., what's the dividing line).  Hold-over glue for Spartan transition?
</blockquote></details>

Exactly: https://github.com/RobotLocomotion/spartan/blob/master/cmake/modules/FindDrake.cmake#L29

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6441)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHmM4dyf_PEwKWmMv:-KnjRsUkdThAlgmNw1zL:bmirinu) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We could, though in practice, CMake did not package them either. I can add something to this PR.
</blockquote></details>

OK I'm satisfied either way here, as long as there is some rationale for where we cross-check that everything is installed -- either incrementally in the CMake turn-down PRs, or in an "install all the things" PR based on `bazel query` were we just do a top-to-bottom inspection of the install list.

---

*[drake/examples/kuka_iiwa_arm/CMakeLists.txt, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-KnjHZX7aWA0Ik9Y_AM3:-KnjRBvhXVVhnf0uNTZP:bi992zg) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/drake/examples/kuka_iiwa_arm/CMakeLists.txt#L104)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Exactly: https://github.com/RobotLocomotion/spartan/blob/master/cmake/modules/FindDrake.cmake#L29
</blockquote></details>

OK I'm convinced.  Can you be sure to ping slack `#drake-kuka-iiwa` to make sure they are ready for this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6441)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 33 of 34 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6441#-:-Knja6-0pc9djZSDh1so:bnfp4nl)*

**Pull request merged**
