### PR TITLE
Use EmitFromEvents from emitfromevents.{cpp,h} vendored from yaml-cpp

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #13102 and #13366.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13383)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
We have to fix the Focal issue this way. The static library was not compiled with PIC (which is normal for Debian, I just forgot).

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by soonho-tri** [comment]
@jamiesnape , it seems that the failures in `linux-focal-unprovisioned-gcc-bazel-experimental` have nothing to do with this PR. But could you double-check and merge this PR if so?

**Comment by jamiesnape** [comment]
`linux-focal-unprovisioned-gcc-bazel-{continuous|experimental}` are yet to pass, though we are getting closer.

**Pull request merged**
