### PR TITLE
SapModel caches the Hessian factorization

### PR DESCRIPTION
**Pull request by amcastro-tri**
Towards the support of gradients through SAP, see https://github.com/RobotLocomotion/drake/issues/21370.

We need the Hessian to propagate gradients. The best way to ensure it's up-to-date, is by caching it in the model's context as we do with every other quantity that depends on v.

As a quick reminder, everything SAP computes is a function of generalized velocities v. Thefore the "state" of the SAP model is generalized velocities v stored in the context. Every other quantity, say impulses, cost, gradients and even Hessian, are functions of v that we cache in the context.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
This deserves standalone unit tests for `SapHessianFactorization`, but I figured I could assing a reviewer to get a first pass before commiting to those tests.

+@sherm1 for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-:-NxUTby844V6CSCdbi4m:bglj4oo)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
not that it matters, but now `SapHessianFactorization` was replace by `DenseSuperNodalSolver`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-:-NxhzSwg5QWKX76rz15r:b-stp2py)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

**Review by sherm1 — COMMENTED** [review]
Feature review checkpoint.

> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-:-NxmsXeQ10lHfCbydb17:bfqjpd9)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.h` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxmqVCv72BhHFglWdAs:-NxmqVCv72BhHFglWdAt:b-5ugmew) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.h#L38)):*
> ```objc
>   bool DoSetWeightMatrix(
>       const std::vector<Eigen::MatrixXd>& block_diagonal_G) final;
>   Eigen::MatrixXd DoMakeFullMatrix() const final { return H_; }
> ```

BTW is there any guarantee H_ has been calculated when this is called? Is there a way to check with a DRAKE_DEMAND or whatever? Also I'm wondering why this returns a copy rather than a reference?
___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.h` line 52 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxmrrFwBcFYNTRGu0zf:-NxmrrFxEQrECdVf7joH:b-elij9u) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.h#L52)):*
> ```objc
>   MatrixX<double> H_;
>   // N.B. This instantiates an in-place LDLT solver that uses the memory in H_.
>   Eigen::LDLT<MatrixX<double>> Hldlt_{H_};
> ```

BTW Eigen's documentation suggests it won't do this in place unless the MatrixType template argument is an EigenRef. Have you checked that this is actually doing what you want it to?

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few minor comments.

> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-:-Nxn6XPVDwwvijdmxuGN:b-anrp9p)* status: 13 unresolved discussions, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.h` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn2PbO1i2qzbYCDvID:-Nxn2PbO1i2qzbYCDvIE:bp4ppvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.h#L24)):*
> ```objc
>   // outlive this object.
>   // @throws std::runtime_error if A or J is nullptr.
>   // @throws std::runtime_error if a block in A is not square.
> ```

nit: should just promise std::exception here
___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.cc` line 42 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn2jKI0BTKG9yHNUq7:-Nxn2jKI0BTKG9yHNUq8:b415s96) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.cc#L42)):*
> ```cpp
>   const MatrixX<double> Jdense = J_->MakeDenseMatrix();
> 
>   // Make dense Hessian matrix G.
> ```

minor: Hessian -> Weight
___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.cc` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn3RIBE47EGZaGcC-w:-Nxn3RIBE47EGZaGcC-x:b-jujx1i) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.cc#L54)):*
> ```cpp
>     Gdense.block(offset, offset, ni, ni) = Gi;
>     offset += ni;
>   }
> ```

BTW if G doesn't have enough rows it will be left with zeroes to fill in the rest. Is that OK, or is that also a kind of incompatibility with the Jacobian?
___
*[`multibody/contact_solvers/sap/sap_model.h` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn3uZvCbbkgKpK3Lf5:-Nxn3uZvCbbkgKpK3Lf6:bkc9u1p) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.h#L123)):*
> ```objc
> // SuperNodalSolver, with the underlying type specified by
> // SapHessianFactorizationType.
> class HessianFactorizationCache {
> ```

BTW this is a "cache entry" rather than a "cache". Probably should be renamed HessianFactorizationCacheEntry to make that clear.
___
*[`multibody/contact_solvers/sap/sap_model.h` line 132 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn4Caf16550VAcYeFx:-Nxn4Caf16550VAcYeFy:bul26l9) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.h#L132)):*
> ```objc
>   HessianFactorizationCache& operator=(HessianFactorizationCache&&) = default;
> 
>   // Creates an empty cache, with no heap allocation. This is used to delay the
> ```

nit: cache -> cache entry
___
*[`multibody/contact_solvers/sap/sap_model.h` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn4KuQ2089ihOOAxs7:-Nxn4KuQ2089ihOOAxs8:b-m4vbga) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.h#L145)):*
> ```objc
>   //
>   // @warning This is a potentially expensive constructor, performing the
>   // necessary symbolic analysys for the case of sparse factorizations.
> ```

typo: analysys -> analysis
___
*[`multibody/contact_solvers/sap/sap_model.h` line 179 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn4mVZ3VMhrfyn_AuP:-Nxn4mVZ3VMhrfyn_AuQ:bwfpv7i) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.h#L179)):*
> ```objc
>   // avoided at all costs. Therefore this implementation always throws. We can
>   // do this because in the well controlled lifespan of a context generated by a
>   // SapModel, we know that a HessianFactorizationCache is default construted
> ```

typo: construted -> constructed

BTW great comment, thanks!
___
*[`multibody/contact_solvers/sap/sap_model.h` line 410 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn563wDnX-U6dTZ7o4:-Nxn563wDnX-U6dTZ7o5:bj8wl37) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.h#L410)):*
> ```objc
>   //
>   // @note This is an expensive computation and therefore only T = double is
>   // supported.
> ```

BTW not clear why being expensive means only T=double (we have other expensive things that can be Autodiffed). Can you elaborate?
___
*[`multibody/contact_solvers/sap/sap_model.h` line 412 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn546f2GCO_kNHMlWM:-Nxn546f2GCO_kNHMlWN:b-dbx53a) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.h#L412)):*
> ```objc
>   // supported.
>   //
>   // @trows std::runtime_error when attempting to perform the computation on T
> ```

typo: trows -> throws
___
*[`multibody/contact_solvers/sap/sap_model.cc` line 192 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn5y5y5aKrXS3nPtM3:-Nxn5y5y5aKrXS3nPtM4:b-pt95ai) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.cc#L192)):*
> ```cpp
> 
>   // N.B. The default constructible SapHessianFactorizationCache is empty. Since
>   // the computation of the factorization is costly, we dealy its construction
> ```

typo: dealy -> delay
___
*[`multibody/contact_solvers/sap/sap_model.cc` line 193 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn60fI6mFKl_-tY28X:-Nxn60fI6mFKl_-tY28Y:b-l9tdqv) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.cc#L193)):*
> ```cpp
>   // N.B. The default constructible SapHessianFactorizationCache is empty. Since
>   // the computation of the factorization is costly, we dealy its construction
>   // to the very first time is computed.
> ```

typo: time is -> time it is

**Review by sherm1 — COMMENTED** [review]
+@SeanCurtis-TRI for platform review per rotation, please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-:-Nxn6eYjBcHACgv2Zszu:b-ttkrno)* status: 13 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by amcastro-tri — COMMENTED** [review]
Thanks for the quick review guys!
I added the promissed unit tests on `DenseSuperNodalSolver`. I believe that also helps mitiage some of your questionns in the first round of reviews.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-:-NxnQgNZ3Pab_d6VilIY:b-rlcui5)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.h` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxmqVCv72BhHFglWdAs:-NxnITjd07BJo0T6nEUD:b51kges) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.h#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is there any guarantee H_ has been calculated when this is called? Is there a way to check with a DRAKE_DEMAND or whatever? Also I'm wondering why this returns a copy rather than a reference?
</blockquote></details>

added comment.
___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.h` line 43 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnETJx8XHYfc5l9vNl:-NxnNgFBCQWdIQefImNo:b-1m81e1) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.h#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given that this isn't movable or copyable, `A_` and `J_` could be const references instead of pointers to const. It eliminates the need to default construct values and guarantees that they are non-null (spelled as is, the line `A_ = nullptr;` is still valid.
</blockquote></details>

Thanks, I like that.
___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.h` line 52 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxmrrFwBcFYNTRGu0zf:-NxnIVvb0AvS6-qCTqhg:b-cjm4fd) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.h#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Eigen's documentation suggests it won't do this in place unless the MatrixType template argument is an EigenRef. Have you checked that this is actually doing what you want it to?

</blockquote></details>

Great catch Sherm! It only works if you explictly spell the `Eigen::Ref` in the template argument.
___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.cc` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn3RIBE47EGZaGcC-w:-NxnJDDY7SusJ58Cc5tZ:b33vck5) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.cc#L54)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW if G doesn't have enough rows it will be left with zeroes to fill in the rest. Is that OK, or is that also a kind of incompatibility with the Jacobian?
</blockquote></details>

nice, I added a check for this.
___
*[`multibody/contact_solvers/sap/sap_model.h` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn3uZvCbbkgKpK3Lf5:-NxnL2OLDIHYOTAl_ZkZ:b-ca7mts) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.h#L123)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is a "cache entry" rather than a "cache". Probably should be renamed HessianFactorizationCacheEntry to make that clear.
</blockquote></details>

right now I am naming it consistently with the rest of the cache structs in this file.
___
*[`multibody/contact_solvers/sap/sap_model.h` line 410 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-Nxn563wDnX-U6dTZ7o4:-NxnMPJn98SUTYHpSfh9:b51kges) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.h#L410)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW not clear why being expensive means only T=double (we have other expensive things that can be Autodiffed). Can you elaborate?
</blockquote></details>

added comment.
___
*[`multibody/contact_solvers/sap/sap_model.cc` line 45 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnID79D_1_9i4thbZo:-NxnM_d30oR9aFpUlDlh:bfcjfmq) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.cc#L45)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Presence of `throw` negates the need for `return`.
</blockquote></details>

I sometimes forget how smart the compiler is.
___
*[`multibody/contact_solvers/sap/sap_model.cc` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnJKfG8HjZOFT0Gy6w:-NxnNNAX1jjb-gLSZGdQ:bozx68q) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/sap_model.cc#L63)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW  It looks ever so slightly odd that this doesn't call `factorization()->SolveInPlace()`.
</blockquote></details>

I agree. Added note.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 4 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421)* status: 7 unresolved discussions

___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.h` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnXW1ODUUeaQX2dznV:-NxnXW1ODUUeaQX2dznW:b-1xp7sp) ([raw file](https://github.com/RobotLocomotion/drake/blob/1fc1b77c5ae42b493e2f4c35c41a958b0d023e65/multibody/contact_solvers/sap/dense_supernodal_solver.h#L32)):*
> ```objc
> 
>   // @returns the size of the system.
>   int size() const { return H_.rows(); }
> ```

nit: Why this method when the parent class already has `GetSize()`? It really just feels like the implementation of `DoGetSize()`. But adding a redundant public API when the inherited API already includes something doesn't seem like a good idea.
___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.h` line 48 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnXjMHAkSvjNOdUGuj:-NxnXjMHAkSvjNOdUGuk:b-3dfoi7) ([raw file](https://github.com/RobotLocomotion/drake/blob/d303c7587c9352e54a95505817ba1f2767a114f7/multibody/contact_solvers/sap/dense_supernodal_solver.h#L48)):*
> ```objc
>   int DoGetSize() const final { return size(); }
> 
>   static int CalcSize(const std::vector<MatrixX<double>>& A) {
> ```

nit: this function does not appear to be invoked.
___
*[`multibody/contact_solvers/sap/sap_model.cc` line 63 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnUnlD9NWfROTd7P_F:-NxnUnlD9NWfROTd7P_G:brrwry2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d303c7587c9352e54a95505817ba1f2767a114f7/multibody/contact_solvers/sap/sap_model.cc#L63)):*
> ```cpp
>     auto rhs_i = rhs->col(i);
>     // N.B. Unfortunately SolveInPlace() only accepts VectorXd*, while here the
>     // return of col() is a block object. Therefore, we are    forced
> ```

nit: Looks like your spacebar ran wild.



_Suggestion:_
```cpp
we are forced
```
___
*[`multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc` line 81 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnVo8G0srdDnP_h1xl:-NxnVo8G0srdDnP_h1xm:bflod49) ([raw file](https://github.com/RobotLocomotion/drake/blob/d303c7587c9352e54a95505817ba1f2767a114f7/multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc#L81)):*
> ```cpp
>   DRAKE_DEMAND(block_positions.size() == dense_positions.size());
>   DRAKE_DEMAND(block_positions.size() == block_sizes.size());
>   const int num_blocks = block_positions.size();
> ```

nit: I'm surprised you're not getting a signed-unsigned mismatch.



_Suggestion:_
```cpp
const int num_blocks = ssize(block_positions);
```
___
*[`multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc` line 121 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnWcqt-dPOo8oBm91z:-NxnWcqt-dPOo8oBm92-:b-89k8d2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d303c7587c9352e54a95505817ba1f2767a114f7/multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc#L121)):*
> ```cpp
>   BlockSparseMatrixBuilder<double> builder(num_row_blocks_of_J,
>                                            num_col_blocks_of_J, 3);
>   for (auto& block : Jtriplets) {
> ```

nit: You're not actually using its mutable nature, so better not to imply such.



_Suggestion:_
```cpp
for (const auto& block 
```
___
*[`multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc` line 129 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnY8cn8fbkoggJFdR7:-NxnY8cn8fbkoggJFdR8:bqc6src) ([raw file](https://github.com/RobotLocomotion/drake/blob/d303c7587c9352e54a95505817ba1f2767a114f7/multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc#L129)):*
> ```cpp
> 
>   DenseSuperNodalSolver solver(&blocks_of_A, &J);
>   EXPECT_EQ(solver.GetSize(), 6);
> ```

BTW As to my earlier point about the two size APIs, this part of the test makes it look particularly silly.
___
*[`multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc` line 223 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnYfUGAcFvG4AoRlO-:-NxnYfUGAcFvG4AoRlO0:b-xf2dc6) ([raw file](https://github.com/RobotLocomotion/drake/blob/d303c7587c9352e54a95505817ba1f2767a114f7/multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc#L223)):*
> ```cpp
>   }
> 
>   // Calling Solve() before Factor() throws.
> ```

nit: This doesn't feel like a test of `DenseSuperNodalSolver`. The dut doesn't take responsibility for this throw, that's part of the parent class's responsibilities.

Same applies to order of operations on `MakeFullMatrix()` and `Factor()` below.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

___
*[`multibody/contact_solvers/sap/dense_supernodal_solver.h` line 48 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnXjMHAkSvjNOdUGuj:-Nxngm1d8CahlmylJvDa:b-fe75uu) ([raw file](https://github.com/RobotLocomotion/drake/blob/d303c7587c9352e54a95505817ba1f2767a114f7/multibody/contact_solvers/sap/dense_supernodal_solver.h#L48)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: this function does not appear to be invoked.
</blockquote></details>

good catch, thanks
___
*[`multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc` line 81 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnVo8G0srdDnP_h1xl:-Nxnh9Zt8SMPJDCaEVoS:bgnrax1) ([raw file](https://github.com/RobotLocomotion/drake/blob/d303c7587c9352e54a95505817ba1f2767a114f7/multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc#L81)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I'm surprised you're not getting a signed-unsigned mismatch.
</blockquote></details>

I've sen these mismatch errors when comparing an int to the result of size(). 
I belive the assignment always works.
___
*[`multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc` line 223 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-NxnYfUGAcFvG4AoRlO-:-NxniS2gExm1wsWq1l_-:b-uuh5xd) ([raw file](https://github.com/RobotLocomotion/drake/blob/d303c7587c9352e54a95505817ba1f2767a114f7/multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc#L223)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This doesn't feel like a test of `DenseSuperNodalSolver`. The dut doesn't take responsibility for this throw, that's part of the parent class's responsibilities.

Same applies to order of operations on `MakeFullMatrix()` and `Factor()` below.
</blockquote></details>

I agree. But it seemed like with very little you get a nice coverage of all cases making this very self contained.
Do you think it's a defect and I should remove them?

**Review by sherm1 — COMMENTED** [review]
Looks great!

> Reviewed 2 of 6 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21421#-:-Nxo5hFo5pqVh1xmndgC:b9bkkp1)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Pull request merged**
