### PR TITLE
[sap] Use C++20 'requires' syntax for double-only functions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21440)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
Thank you so much @jwnimmer-tri! this is definitely a useful C++20 fature, making the intetion very clear.
:lgtm_strong: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21440#-:-Ny0_pL052crer7t8nj7:b-ny0w64)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_solver.h` line 306 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21440#-Ny0_kEL3Ke6pAo-VMU-:-Ny0_kEM00RD7can0oan:b-udwk3k) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd6548dc01c60f3324736aa5adf8ce66fc1468a9/multibody/contact_solvers/sap/sap_solver.h#L306)):*
> ```objc
>   // @pre context is not nullptr.
>   // @pre context was created via a call to model.MakeContext().
>   SapSolverStatus SolveWithGuessImpl(const SapModel<T>& model,
> ```

btw, I like this function name change!

**Review by amcastro-tri — COMMENTED** [review]
adding myself +@amcastro-tri for feature review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21440#-:-Ny0a3pN5CqauYhgZXAU:b-y6lpgw)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21440)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 218 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21440#-Ny0lt0LB5IooaH7fMrY:-Ny0lt0LB5IooaH7fMrZ:bkjs1oj) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd6548dc01c60f3324736aa5adf8ce66fc1468a9/multibody/contact_solvers/sap/sap_solver.cc#L218)):*
> ```cpp
>                                                  systems::Context<T>* context)
>   requires std::is_same_v<T, double>
> {  // NOLINT(whitespace/braces)
> ```

BTW What's the story with this linting directive? Is this going to have to be part of every incantation that uses `requires`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21440)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 218 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21440#-Ny0lt0LB5IooaH7fMrY:-Ny0mNSK0InzWm4Evyeo:b-nhubhf) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd6548dc01c60f3324736aa5adf8ce66fc1468a9/multibody/contact_solvers/sap/sap_solver.cc#L218)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW What's the story with this linting directive? Is this going to have to be part of every incantation that uses `requires`?
</blockquote></details>

As of today, yes.  The medium-term goal is to either:

(1) Change our linters so that when `enable_clang_format_lint = True`, the `whitespace/*` rules in CPPLINT are disarmed, or

(2) Upgrade to a newer cpplint that understands `requires`.

**Comment by jwnimmer-tri** [comment]
FYI We'll give this until my afternoon time for any platform reviewers to raise objections (per my slack post), but then we can merge it.

**Pull request merged**
