### PR TITLE
workspace: Build dreal from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
It's a pain point to have C++ libraries in the build that are not compiled directly from source.

Relates #12136.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12186)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@soonho-tri or @jamiesnape -- Is there any reason we need to use a pre-compiled dReal anymore?    Even on my laptop, this only adds <60 seconds to the build time.

Also if we go this route, I assume we don't need to compile dReal as a shared library, nor install it individually either?  It could be hidden (eventually) just like any other solver back-end we use?

**Comment by jamiesnape** [comment]
Not as far as I am aware.

**Comment by soonho-tri** [comment]
SGTM.

**Comment by jwnimmer-tri** [comment]
OK, in that case I'll continue drafting this.  I still have work to do on polish, macOS support and testing, etc.

**Comment by jwnimmer-tri** [comment]
On master, we have:
```
tap 'dreal/dreal'
brew 'dreal/dreal/dreal'
```

What should those change to if we only want `ibex@2.7.4` now, not dreal, from homebrew?

**Comment by soonho-tri** [comment]
The following should work:
```
tap 'dreal-deps/ibex'
brew 'dreal-deps/ibex/ibex@2.7.4'
```

**Comment by soonho-tri** [comment]
> @soonho-tri When you have a chance (no rush), please update dreal's cds.BUILD.bazel and picosat.BUILD.bazel to say exports_files(["LICENSE"]) or exports_files(glob(["**"])), so that Drake can install package those files as required by the upstream authors.

Done. https://github.com/dreal/dreal4/commit/61a199ee9d99fb9913ed51c9569e7f0c36ce1476

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12186#-LqvXeZFDs_qyzcHFiHZ:-Lr4EveX-KRriqHm79Mf:b1oudjq) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@soonho-tri When you have a chance (no rush), please update dreal's `cds.BUILD.bazel` and `picosat.BUILD.bazel` to say `exports_files(["LICENSE"])` or `exports_files(glob(["**"]))`, so that Drake can install package those files as required by the upstream authors.
</blockquote></details>

@soonho-tri Please change dReal's root BUILD file to say `exports_files(["LICENSE.txt"])` instead of `exports_files(["LICENSE"])`.

---

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape +@soonho-tri for feature review, please.

**Comment by jamiesnape** [comment]
> There is no CI option that would cover this to my knowledge.

I was just thinking to myself that having a "re-provisioned" build or two would be nice.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

**Pull request merged**
