### PR TITLE
Add LinearSystem::MakeLinearSystem()

### LINKED ISSUE #6710: symbolic::Expression constructors for AffineSystem and LinearSystem
I was hoping to add an extra constructor to AffineSystem (and LinearSystem) that looks something like this:

```
  AffineSystem(const symbolic::Variables& state_vars, const symbolic::Variables& input_vars, const Eigen::Ref<const VectorX<symbolic::Expression>>& dynamics, const Eigen::Ref<const VectorX<symbolic::Expression>>& output, double time_period = 0.0)
```

I think this should be simple, but to do it, I need to extract the linear and constant parts of the expression.  I feel like I can get `A` , `B`, `C`, and `D` from calling `symbolic::Jacobian(dynamics,state_vars)`, but don't actually see an easy way to extract the constant terms (`get_constant_value` etc assume special cases).  I see `DecomposeLinearExpression` , but it's embedded in symbolic_extraction and special cased for the solvers use case.  I also need to `DRAKE_DEMAND` that the system is affine/linear in (only) the input variables.

What is the recommended API for this?  (any chance there is something simple enough to use in a delegating constructor)?  Thanks!

### PR DESCRIPTION
**Pull request by soonho-tri**
Also refactor the decomposition methods into `drake/common:symoblic_decompose`.

Close #6710

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6755)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@russtedrake, feature-review please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-:-KqZhHYk6uHdYk6ab7Cu:bqrowhy)*

**Comment by soonho-tri** [comment]
+@hongkai-dai , may I have your review on it? (I think I can consider Russ's review as a platform).

@russtedrake , I'll work on `MakePiecewiseAffineSystem()` using your branch as discussed last night.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-:-KqZiGTwXsAOEIgflIzt:bsyascd)*

**Comment by hongkai-dai** [comment]
checkpoint.

---

Reviewed 5 of 10 files at r1.
Review status: 5 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/symbolic_decompose.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZv-R_PI87W27iOvLd:-KqZv-R_PI87W27iOvLe:b-e829u7) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.cc#L44)):*
> ```cpp
> }  // namespace
> 
> void DecomposeLinearExpressions(
> ```

There is quite a lot of code duplication with `DecomposeAffineExpressions`. Can we pull out the common part into a function like
```C++
namespace {
void DecomposeLinearOrAffineExpressions(const Eigen::Ref<const VectorX<Expression>>& expressions,
const EIgen::Ref<const VectorX<symbolic::Variable>>& vars1,
const Eigen::Ref<const VectorX<symbolic::Variable>>& vars2,
Eigen::MatrixXd* const M1, Eigen::MatrixXd* const M2, Eigen::VectorXd* v, bool is_affine);
}
```

---

*[drake/common/symbolic_decompose.cc, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZltFhqC2auwAvr_W3:-KqZltFhqC2auwAvr_W4:b-2czyaa) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.cc#L48)):*
> ```cpp
>     const Eigen::Ref<const VectorX<symbolic::Variable>> vars1,
>     const Eigen::Ref<const VectorX<symbolic::Variable>> vars2,
>     Eigen::MatrixXd* const M1, Eigen::MatrixXd* const M2) {
> ```

Should we resize `M1` and `M2` first?
```C++
M1->resize(expressions.rows(), vars1.rows());
M2->resize(expressions.rows(), vars2.rows());
```

---

*[drake/common/symbolic_decompose.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZmIo7sGCe9VuQvXJQ:-KqZmIo7sGCe9VuQvXJR:b-pm3yjx) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.cc#L54)):*
> ```cpp
>       ThrowError("non-polynomial", e.to_string());  // e should be a polynomial.
>     }
>     const Polynomial p{e, Variables{vars1} + Variables{vars2}};
> ```

Also check `p.decision_variables().size() == 0`? To make sure `e` does not contain variables other than those in `vars1` or `vars2`.

---

*[drake/common/symbolic_decompose.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZk5ncgdlKRKbrDtKI:-KqZk5ncgdlKRKbrDtKJ:bf1wyxz) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.h#L19)):*
> ```objc
>     const Eigen::Ref<const VectorX<Expression>>& expressions,
>     const Eigen::Ref<const VectorX<Variable>> vars1,
>     const Eigen::Ref<const VectorX<Variable>> vars2, Eigen::MatrixXd* const M1,
> ```

This might be an overkill, but if we use `Eigen::MatrixXd*`, does it exclude the possibility that `M1` is a static-size matrix? If that is a concern, then we can consider to use `Eigen::Ref<Eigen::MatrixXd> M1`, or write a template function 
```C++
template<typename DerivedM1, typenameDerivedM2>
void DecomposeLinearExpressions(
    const Eigen::Ref<const VectorX<Expression>>& expressions,
    const Eigen::Ref<const VectorX<Variable>> vars1,
    const Eigen::Ref<const VectorX<Variable>> vars2, DerivedM1* M1, DerivedM2* M2);
```

---

*[drake/common/symbolic_decompose.h, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZxt0J4135k-V7XWGb:-KqZxt0J4135k-V7XWGc:b9dic7g) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.h#L28)):*
> ```objc
> void DecomposeAffineExpressions(
>     const Eigen::Ref<const VectorX<Expression>>& expressions,
>     const Eigen::Ref<const VectorX<Variable>> vars1,
> ```

there should be `&` before `vars1` and `vars2`.

---

*[drake/systems/primitives/linear_system.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZj7QQwMekuTA09oij:-KqZj7QR7DWJSy5n1aho:b37kmc0) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/systems/primitives/linear_system.h#L64)):*
> ```objc
>   ///
>   /// @throws runtime_error if either @p dynamics or @p outputs is not linear in
>   /// @p state_vars and @p input_vars.
> ```

Also check `state_vars` and `input_vars` do not overlap?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-:-KqZy-W44UJZGfbtUAeB:b6o68ox)*

**Comment by soonho-tri** [comment]
Thanks for the comments. I'll address the other two tomorrow morning.

---

Review status: 4 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/symbolic_decompose.cc, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZltFhqC2auwAvr_W3:-Kqai-WPAthbL4ZeJDef:b-z05irg) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.cc#L48)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should we resize `M1` and `M2` first?
```C++
M1->resize(expressions.rows(), vars1.rows());
M2->resize(expressions.rows(), vars2.rows());
```
</blockquote></details>

Done.
 - Added `@pre`s in the documentations.
 - Added `DRAKE_DEMAND`s in the code to check.

---

*[drake/common/symbolic_decompose.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZmIo7sGCe9VuQvXJQ:-Kqai7TlYspAJI_uCJ7t:btpv2mp) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.cc#L54)):*
> Also check p.decision_variables().size() == 0? To make sure e does not contain variables other than those in vars1 or vars2.

This is true and we can check it, but it already throws an exception if this polynomial `p` has a non-constant coefficient which covers `p.decision_variables().size() != 0` case.

---

*[drake/common/symbolic_decompose.h, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZxt0J4135k-V7XWGb:-KqaiXhWWsc_X47SWO1s:bu9gagv) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.h#L28)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

there should be `&` before `vars1` and `vars2`.
</blockquote></details>

Done. Thanks for catching this!

---

*[drake/systems/primitives/linear_system.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZj7QQwMekuTA09oij:-Kqaj41tzO-rtPSCbEp5:bkbw4dd) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/systems/primitives/linear_system.h#L64)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Also check `state_vars` and `input_vars` do not overlap?
</blockquote></details>

Done.
 - Added `@pre` in the documentations.
 - Added `DRAKE_DEMAND`s in the code to check.
 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-:-Kqam5G6h20ktPva-FVL:bx4mjqa)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_decompose.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZmIo7sGCe9VuQvXJQ:-KqcmIwMi1mQqowLfyrz:bcr5s2o) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.cc#L54)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> Also check p.decision_variables().size() == 0? To make sure e does not contain variables other than those in vars1 or vars2.

This is true and we can check it, but it already throws an exception if this polynomial `p` has a non-constant coefficient which covers `p.decision_variables().size() != 0` case.
</blockquote></details>

Got it, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755)*

**Comment by soonho-tri** [comment]
Review status: 2 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_decompose.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZv-R_PI87W27iOvLd:-KqiDGsHZaUl8LyqZq8P:b-j9uapa) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.cc#L44)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

There is quite a lot of code duplication with `DecomposeAffineExpressions`. Can we pull out the common part into a function like
```C++
namespace {
void DecomposeLinearOrAffineExpressions(const Eigen::Ref<const VectorX<Expression>>& expressions,
const EIgen::Ref<const VectorX<symbolic::Variable>>& vars1,
const Eigen::Ref<const VectorX<symbolic::Variable>>& vars2,
Eigen::MatrixXd* const M1, Eigen::MatrixXd* const M2, Eigen::VectorXd* v, bool is_affine);
}
```
</blockquote></details>

I understand that there are common factors in the two functions, but I try to avoid combining them into one function at the same time. I will handle the refactoring when I move `drake/solvers:symbolic_extraction` (I added a TODO).

---

*[drake/common/symbolic_decompose.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqZk5ncgdlKRKbrDtKI:-KqiDgkrtjpSmFVfMaLB:bqgqki1) ([raw file](https://github.com/robotlocomotion/drake/blob/6407e6b041f1c0f001e3026550662035ba051173/drake/common/symbolic_decompose.h#L19)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This might be an overkill, but if we use `Eigen::MatrixXd*`, does it exclude the possibility that `M1` is a static-size matrix? If that is a concern, then we can consider to use `Eigen::Ref<Eigen::MatrixXd> M1`, or write a template function 
```C++
template<typename DerivedM1, typenameDerivedM2>
void DecomposeLinearExpressions(
    const Eigen::Ref<const VectorX<Expression>>& expressions,
    const Eigen::Ref<const VectorX<Variable>> vars1,
    const Eigen::Ref<const VectorX<Variable>> vars2, DerivedM1* M1, DerivedM2* M2);
```
</blockquote></details>

Done (switched to `Eigen::Ref`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 10 files at r1, 1 of 8 files at r2.
Review status: 4 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_decompose.cc, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqiHSzldieakU7nkWzu:-KqiHSzldieakU7nkWzv:bulxv48) ([raw file](https://github.com/robotlocomotion/drake/blob/53bc68f4695867544eae94c269f352f3b698c753/drake/common/symbolic_decompose.cc#L25)):*
> ```cpp
> template <typename Derived>
> void FindCoefficientAndFill(const Polynomial::MapType& map, const Monomial& m,
>                             const int i, const Eigen::MatrixBase<Derived>& M) {
> ```

As we discussed in slack, instead of passing in a const matrix M here, we can change the type to `Eigen::Ref<Eigen::MatrixXd> M`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755)*

**Comment by soonho-tri** [comment]
Review status: 4 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_decompose.cc, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqiHSzldieakU7nkWzu:-KqiQstnynfDo69ubYX5:b-s0soug) ([raw file](https://github.com/robotlocomotion/drake/blob/53bc68f4695867544eae94c269f352f3b698c753/drake/common/symbolic_decompose.cc#L25)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

As we discussed in slack, instead of passing in a const matrix M here, we can change the type to `Eigen::Ref<Eigen::MatrixXd> M`?
</blockquote></details>

Hmm, actually, `Eigen::Ref<Eigen::MatrixXd> M` doesn't compile. We have two use cases of this function. In one case, we pass a row of a matrix,`M.row(i)`. In another, we pass an `Eigen::Vector`, `v`. The template version works because `M(i)` makes sense for both cases while `Eigen::Ref<...>` approach doesn't since we fixated the type in `<...>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_decompose.cc, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-KqiHSzldieakU7nkWzu:-KqiXZMBBObC3eBl5RKO:beqczgu) ([raw file](https://github.com/robotlocomotion/drake/blob/53bc68f4695867544eae94c269f352f3b698c753/drake/common/symbolic_decompose.cc#L25)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Hmm, actually, `Eigen::Ref<Eigen::MatrixXd> M` doesn't compile. We have two use cases of this function. In one case, we pass a row of a matrix,`M.row(i)`. In another, we pass an `Eigen::Vector`, `v`. The template version works because `M(i)` makes sense for both cases while `Eigen::Ref<...>` approach doesn't since we fixated the type in `<...>`.
</blockquote></details>

I see, I think `M.row(i)` will probably fail, since the stride is not 1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755)*

**Comment by soonho-tri** [comment]
Review status: 3 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_decompose_test.cc, line 149 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-Kqx2fMjMcBgMh_lbRfZ:-Kqx2fMjMcBgMh_lbRf_:b-mq4in1) ([raw file](https://github.com/robotlocomotion/drake/blob/16ea87995c6a5340a47b24bca9fe1807ecf26362/drake/common/test/symbolic_decompose_test.cc#L149)):*
> ```cpp
>   Eigen::Matrix4d M2_expected;
>   DecomposeAffineExpressions(M1_ * x_ + M2_ * u_ + v_, x_, u_,
>                              M1_expected.block(0, 0, 3, 3),
> ```

@hongkai-dai , I've checked that it works with `.block(...)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755)*

**Comment by hongkai-dai** [comment]
:lgtm: 

---

Reviewed 4 of 8 files at r2, 3 of 5 files at r3.
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_decompose_test.cc, line 149 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-Kqx2fMjMcBgMh_lbRfZ:-KqxdLmRVtIUKHIcei5Y:ba59tit) ([raw file](https://github.com/robotlocomotion/drake/blob/16ea87995c6a5340a47b24bca9fe1807ecf26362/drake/common/test/symbolic_decompose_test.cc#L149)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@hongkai-dai , I've checked that it works with `.block(...)`.
</blockquote></details>

Awesome! Thanks for testing it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-:-Kqxdsq1g7iXKwnlTVEl:bg7igkv)*

**Comment by RussTedrake** [comment]
Reviewed 3 of 10 files at r1, 4 of 8 files at r2, 4 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_decompose.h, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-Kr0Lb6hBoKs6yexxIZD:-Kr0Lb6hBoKs6yexxIZE:b-9p82t) ([raw file](https://github.com/robotlocomotion/drake/blob/16ea87995c6a5340a47b24bca9fe1807ecf26362/drake/common/symbolic_decompose.h#L12)):*
> ```objc
> namespace symbolic {
> 
> /// Decomposes @p expressions into @p M1 * @p vars1 + @p M2 * @p vars2.
> ```

The reason for this signature is obvious in MakeLinearSystem, etc, but it seems bizarre in general.  I think a more natural API would be just factoring into M*vars (no M1 and M2)... on the MakeLinearSystem side the caller could easily call it with [x;u] and extract M1 = M.topRows(..) and M2 = M.bottomRows().  That would be more general for other callers, too.

---

*[drake/common/symbolic_decompose.h, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-Kr0MAmtJD-TynuN3ZV2:-Kr0MAmtJD-TynuN3ZV3:b-ch4h5j) ([raw file](https://github.com/robotlocomotion/drake/blob/16ea87995c6a5340a47b24bca9fe1807ecf26362/drake/common/symbolic_decompose.h#L26)):*
> ```objc
>     Eigen::Ref<Eigen::MatrixXd> M1, Eigen::Ref<Eigen::MatrixXd> M2);
> 
> /// Decomposes @p expressions into @p M1 * @p vars1 + @p M2 * @p vars2 + v.
> ```

same comment as above.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755)*

**Comment by soonho-tri** [comment]
Review status: 7 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_decompose.h, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-Kr0Lb6hBoKs6yexxIZD:-Kr1PpblOgugGQXH2flG:b1b9y3m) ([raw file](https://github.com/robotlocomotion/drake/blob/16ea87995c6a5340a47b24bca9fe1807ecf26362/drake/common/symbolic_decompose.h#L12)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The reason for this signature is obvious in MakeLinearSystem, etc, but it seems bizarre in general.  I think a more natural API would be just factoring into M*vars (no M1 and M2)... on the MakeLinearSystem side the caller could easily call it with [x;u] and extract M1 = M.topRows(..) and M2 = M.bottomRows().  That would be more general for other callers, too.
</blockquote></details>

Done. (Please see the diffs in `affine_system.cc` and `linear_system.cc`).

---

*[drake/common/symbolic_decompose.h, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-Kr0MAmtJD-TynuN3ZV2:-Kr1PwXIry2zjSmjrwa_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16ea87995c6a5340a47b24bca9fe1807ecf26362/drake/common/symbolic_decompose.h#L26)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

same comment as above.  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 7 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-:-Kr3Npar5b7Optf0wgX2:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/symbolic_decompose.h, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6755#-Kr3ReTviqSgTIPbSY8G:-Kr3ReTwZ4usi_DLwCK9:bn3skbx) ([raw file](https://github.com/robotlocomotion/drake/blob/5dec7d7ead492fc8b6070bb61eb2bb5eb629cbb7/drake/common/symbolic_decompose.h#L19)):*
> ```objc
>     const Eigen::Ref<const VectorX<Expression>>& expressions,
>     const Eigen::Ref<const VectorX<Variable>>& vars,
>     Eigen::Ref<Eigen::MatrixXd> M);
> ```

It would be really nice if there were a way to offer these methods without using GSG-violating mutable reference types for output parameters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6755)*

**Comment by soonho-tri** [comment]
I thought that it's fine since there is no `&` in `Eigen::Ref<Eigen::MatrixXd> M`. Now I think it's against the principle of the rule because merely looking at a call-site, it's not clear if the argument is modified or not?

Let me check if I can simply change its signature to take a pointer to `Eigen::Ref<Eigen::MatrixXd>`. If it doesn't work, I think we need to go to a template version (which I tried hard to avoid).

**Comment by jwnimmer-tri** [comment]
`Ref` is a library form of `&`, really no different.  All the same rules should ideally apply.

**Comment by soonho-tri** [comment]
Just tested. `Eigen::MatrixXd *` can't be converted into `Eigen::Ref<Eigen::MatrixXd> *`. Following GSG, it seems that we can't use non-const `Eigen::Ref` and should rely on the template method.

**Comment by jwnimmer-tri** [comment]
I agree with your upthread implication that a template version would be annoying.  I believe there are other solutions.  Fundamentally we want `Eigen::Ptr` that is like `Eigen::Ref` but implicitly converts from the address of a matrix, rather than the reference of a matrix.  I am playing around with ideas now.

**Comment by jwnimmer-tri** [comment]
This compiles, and I think is a sketch of what we want?
```diff
diff --git a/drake/common/symbolic_decompose.cc b/drake/common/symbolic_decompose.cc
index 2e3d206..65d01e7 100644
--- a/drake/common/symbolic_decompose.cc
+++ b/drake/common/symbolic_decompose.cc
@@ -72,9 +72,9 @@ void DecomposeLinearExpressions(
 void DecomposeAffineExpressions(
     const Eigen::Ref<const VectorX<Expression>>& expressions,
     const Eigen::Ref<const VectorX<symbolic::Variable>>& vars,
-    Eigen::Ref<Eigen::MatrixXd> M, Eigen::Ref<Eigen::VectorXd> v) {
+    Eigen::Ref<Eigen::MatrixXd> M, Ptr<Eigen::VectorXd> v) {
   DRAKE_DEMAND(M.rows() == expressions.rows() && M.cols() == vars.rows());
-  DRAKE_DEMAND(v.rows() == expressions.rows());
+  DRAKE_DEMAND(v->rows() == expressions.rows());
   for (int i = 0; i < expressions.size(); ++i) {
     const Expression& e{expressions(i)};
     if (!e.is_polynomial()) {
@@ -90,7 +90,7 @@ void DecomposeAffineExpressions(
       FindCoefficientAndFill(map, Monomial{vars.coeff(j)}, j, M.row(i));
     }
     // Fill v(i).
-    FindCoefficientAndFill(map, Monomial{}, i, v);
+    FindCoefficientAndFill(map, Monomial{}, i, *v);
   }
 }
 }  // namespace symbolic
diff --git a/drake/common/symbolic_decompose.h b/drake/common/symbolic_decompose.h
index 0ce711a..c33b953 100644
--- a/drake/common/symbolic_decompose.h
+++ b/drake/common/symbolic_decompose.h
@@ -9,6 +9,18 @@
 namespace drake {
 namespace symbolic {
 
+template <typename PlainObjectType>
+class Ptr {
+ public:
+  Ptr(PlainObjectType* m) : m_(*m) {}
+
+  Eigen::Ref<PlainObjectType>& operator*() { return m_; }
+  Eigen::Ref<PlainObjectType>* operator->() { return &m_; }
+
+ private:
+  Eigen::Ref<PlainObjectType> m_;
+};
+
 /// Decomposes @p expressions into @p M * @p vars.
 ///
 /// @throws runtime_error if @p expressions is not linear in @p vars.
@@ -26,7 +38,7 @@ void DecomposeLinearExpressions(
 void DecomposeAffineExpressions(
     const Eigen::Ref<const VectorX<Expression>>& expressions,
     const Eigen::Ref<const VectorX<Variable>>& vars,
-    Eigen::Ref<Eigen::MatrixXd> M, Eigen::Ref<Eigen::VectorXd> v);
+    Eigen::Ref<Eigen::MatrixXd> M, Ptr<Eigen::VectorXd> v);
 
 }  // namespace symbolic
 }  // namespace drake
diff --git a/drake/common/test/symbolic_decompose_test.cc b/drake/common/test/symbolic_decompose_test.cc
index 1ad18f0..15672ca 100644
--- a/drake/common/test/symbolic_decompose_test.cc
+++ b/drake/common/test/symbolic_decompose_test.cc
@@ -113,11 +113,12 @@ TEST_F(SymbolicDecomposeTest, DecomposeLinearExpressionsExceptionAffine) {
 
 TEST_F(SymbolicDecomposeTest, DecomposeAffineExpressionsDynamic) {
   DecomposeAffineExpressions(M_ * x_ + v_, x_, M_expected_dynamic_,
-                             v_expected_dynamic_);
+                             &v_expected_dynamic_);
   EXPECT_EQ(M_expected_dynamic_, M_);
   EXPECT_EQ(v_expected_dynamic_, v_);
 }
 
+#if 0
 TEST_F(SymbolicDecomposeTest, DecomposeAffineExpressionsStatic) {
   DecomposeAffineExpressions(M_ * x_ + v_, x_, M_expected_static_,
                              v_expected_static_);
@@ -173,6 +174,7 @@ TEST_F(SymbolicDecomposeTest,
                                  M_expected_static_, v_expected_static_),
       runtime_error);
 }
+#endif
 
 }  // namespace
 }  // namespace symbolic
```

**Comment by jwnimmer-tri** [comment]
Oops, I should have enabled the static-size unit test too.  For that, we need change `Ptr` to have a templated constructor, like so:
```c++
  template <typename PlainObjectTypeIn>
  Ptr(PlainObjectTypeIn* m) : m_(*m) {}
```

**Comment by soonho-tri** [comment]
Thanks for the pointers. I'll work based on them.

**Pull request merged**
