### PR TITLE
Backfill another old-Eigen bug

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
It is looking like I won't be able to stay on old-Eigen for long.  I'll work on prioritizing porting the other project to bleeding-edge Eigen, but for now this patch gets me compiling again.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4032)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4032#-:-KVlByVifAWXrJKPMKMY:bnfp4nl)*

**Comment by sherm1** [comment]
One flaw, PTAL. Otherwise :lgtm:.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/math/autodiff_overloads.h, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4032#-KVlf8b3CcQzyibJ3yMx:-KVlf8b3CcQzyibJ3yMy:bjlu5x3) ([raw file](https://github.com/robotlocomotion/drake/blob/002f3f853ea0bddf6a0786527eb94f035993a710/drake/math/autodiff_overloads.h#L93)):*
> ```objc
> Eigen::AutoDiffScalar<DerType>& max(
>     Eigen::AutoDiffScalar<DerType>& x,
>     Eigen::AutoDiffScalar<DerType>& y) {
> ```

These should be const references.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4032#-:-KVlfDkn1TQyvjCQodlQ:b-mpgwm2)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/autodiff_overloads.h, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4032#-KVlf8b3CcQzyibJ3yMx:-KVlj8bASjuYuEC2960n:b-98sso1) ([raw file](https://github.com/robotlocomotion/drake/blob/002f3f853ea0bddf6a0786527eb94f035993a710/drake/math/autodiff_overloads.h#L93)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> These should be const references.
</details>
Right, thanks!  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4032)*

**Comment by sherm1** [comment]
Perfect -- just waiting for CI. :ltgm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4032#-:-KVlok1foXn9Ydic003U:b3zx9gg)*

**Pull request merged**
