### PR TITLE
increase the test size for global IK

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6615)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@m-chaturvedi for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6615#-:-KpWqb33-NXT1vsUVkSi:b-7zm30o)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  linux-xenial-clang-bazel-continuous-everything-debug please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6615#-:-KpWqjMGDjwzX-f5fYdl:b-iz120)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please.

**Comment by m-chaturvedi** [comment]
:LGTM:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6615#-:-KpX2Vqsr1J3-XABRmhb:bmxilld)*

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6615#-:-KpX2dzmG6s39qZGcg85:b72l57d)*

**Comment by soonho-tri** [comment]
:lgtm:
+@soonho-tri 
-@EricCousineau-TRI 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6615#-:-KpX2zJnfpPR2ujDji8M:b-soghw6)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6615)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-debug please

**Pull request merged**
