### PR TITLE
Revert "Add CheckSatisfiability and Minimize in DrealSolver"

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Reverts RobotLocomotion/drake#7631

Dear @soonho-tri ,

The on-call build cop, @m-chaturvedi, believes that your PR #7631 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
[1](https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-continuous-memcheck-tsan/629/consoleText), [2](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-gcc-bazel-continuous-memcheck-lsan/1015/consoleText), [3](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-clang-bazel-continuous-memcheck-asan/812/consoleText)

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7647)

### CODE REVIEW

**Comment by soonho-tri** [comment]
> If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

:lgtm:

I'll update the upstream dReal and open new PRs to use it.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7647#-:-L0kU4-35HonKjTNBfvQ:b6culwg)*

**Comment by soonho-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7647)*

**Comment by jwnimmer-tri** [comment]
You could open a PR to disable the one new test if you wish, instead of the revert-reapply dance.

**Comment by soonho-tri** [comment]
> You could open a PR to disable the one new test if you wish

Will do that.

**Pull request closed without merging**
