### PR TITLE
Fix cpplint build/include

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix all cpplint build/include warnings, and then enable it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2083)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
The build failure is just known-issue #2088.  This is ready for code review now.

**Comment by rpoyner-tri** [comment]
don't know if fixing all the c-ish header names to c++ was really in your charter. i flagged a few in files you did touch; i suspect more remain in the wild.

---

Review status: 0 of 72 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/solvers/gurobiQPmex.cpp, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2083#-KFGVonTNKFBJdVvImMB:-KFGVonTNKFBJdVvImMC:-1138668048) ([raw file](https://github.com/robotlocomotion/drake/blob/b520c3a798ddf14a2661f103ce52d5d53cd9e663/drake/solvers/gurobiQPmex.cpp#L3)):*
cmath fugitive?

---

*[drake/systems/plants/approximateIKEIQPmex.cpp, line 7 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2083#-KFGVw4-Nu1lw4vrpUog:-KFGVw4-Nu1lw4vrpUoh:-1138668048) ([raw file](https://github.com/robotlocomotion/drake/blob/b520c3a798ddf14a2661f103ce52d5d53cd9e663/drake/systems/plants/approximateIKEIQPmex.cpp#L7)):*
cmath fugitive?

---

*[drake/systems/trajectories/isCollisionFree_mex.cpp, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2083#-KFGV6hDvGGUAcutmlwr:-KFGV6hED0ltXATGHiD9:67288876) ([raw file](https://github.com/robotlocomotion/drake/blob/b520c3a798ddf14a2661f103ce52d5d53cd9e663/drake/systems/trajectories/isCollisionFree_mex.cpp#L27)):*
did this one escape the cmath hammer?

---

*[drake/systems/trajectories/replanFunnels_mex.cpp, line 34 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2083#-KFGVLheKJ59COnHx-vK:-KFGVLheKJ59COnHx-vL:1620834642) ([raw file](https://github.com/robotlocomotion/drake/blob/b520c3a798ddf14a2661f103ce52d5d53cd9e663/drake/systems/trajectories/replanFunnels_mex.cpp#L34)):*
another cmath escapee?

---

*[drake/systems/trajectories/shiftFunnel_snopt_mex.cpp, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2083#-KFGVPrKamqS3fX12MBS:-KFGVPrKamqS3fX12MBT:-1837037153) ([raw file](https://github.com/robotlocomotion/drake/blob/b520c3a798ddf14a2661f103ce52d5d53cd9e663/drake/systems/trajectories/shiftFunnel_snopt_mex.cpp#L26)):*
want cmath?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2083#-:-KFGX1gaijON3DOAb5I2:1541382803)*

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri The charter was to fix the double quotes in `"math.h"` (which I replaced with `<cmath>`) but not chartered to fix `<math.h>`.  I believe that a different rule will have to enforce using the proper spelling of std headers.  Would you support merging this without fixing the `math.h` bogies you called out?

**Comment by rpoyner-tri** [comment]
@jwnimmer-tri sure, ship it.

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: 0 of 72 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2083#-:-KFGjXcEz2KJXYB2HVcs:1417088721)*

**Comment by jwnimmer-tri** [comment]
Ready for platform review and merge.  Over to @david-german-tri.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 72 of 72 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2083#-:-KFGmZ1pc5aftmiQqaKh:1417088721)*

**Pull request merged**
