### PR TITLE
Cars cleanups

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Fix up some namespaces.
- Extract LcmTap.
- Remove publish_driving_command.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2294) &emsp; Multiple assignees:&emsp;@ggould-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/ggould-tri">ggould-tri</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok (feature) please.
+@ggould-tri (platform) please.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### Cars cleanups
> 
> - Fix up some namespaces.
> 
> - Extract LcmTap.
> 
> - Remove publish_driving_command.
> 
> 
> </details>


---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-:-KHLGWAvbc3lqtElYjcQ:561615989)*

**Comment by liangfok** [comment]
This is going to complicate my efforts in https://github.com/RobotLocomotion/drake/pull/2253 where I'm in the midst consolidating code that is shared between `car_sim_lcm` and `car_sim_lcm_and_ros` (as requested by @david-german-tri). However, since this is strictly an improvement above the existing code, I shall declare that it :lgtm_strong: .

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@liangfok (feature) please.
> +@ggould-tri (platform) please.</details>


---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/steering_command_driver.py, line 184 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLHKmjIC07jNRH3rYg:-KHLHKmjIC07jNRH3rYh:1990399968) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/steering_command_driver.py#L184)):*
> ```Python
>     parser.add_argument(
>       '--steering-angle', type=float, default='0.0',
>         help='initial sterring angle (in radians)')
> ```

"sterring" -> "steering"

Also, should we indicate that it is positive counter clockwise?

---

*[drake/examples/Cars/steering_command_driver.py, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLHaR2D2KK9sw8vsxQ:-KHLHaR2D2KK9sw8vsxR:-1934064122) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/steering_command_driver.py#L194)):*
> ```Python
> 
>     if 'pygame' not in sys.modules:
>         print >>sys.stderr, 'error: missing pygame; see README.md for help.'
> ```

I wonder whether we should point the user to an URL instead of a file they may not have.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-:-KHLGD3MjMDRJ1l6S9XB:-1737568230)*

**Comment by jwnimmer-tri** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/steering_command_driver.py, line 184 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLHKmjIC07jNRH3rYg:-KHLJarBRfRxRepZgooB:-1457988611) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/steering_command_driver.py#L184)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "sterring" -> "steering"
> 
> Also, should we indicate that it is positive counter clockwise?</details>
Done for both.

---

*[drake/examples/Cars/steering_command_driver.py, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLHaR2D2KK9sw8vsxQ:-KHLJBsD31k1N-Muc2Jg:340353614) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/steering_command_driver.py#L194)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I wonder whether we should point the user to an URL instead of a file they may not have.</details>
Do you mean in case the example is run from out-of-tree?  That doesn't apply here, because this python file is not installed out-of-tree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/steering_command_driver.py, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLHaR2D2KK9sw8vsxQ:-KHLKO9SdqxTrw7YJYv-:322657918) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/steering_command_driver.py#L194)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Do you mean in case the example is run from out-of-tree?  That doesn't apply here, because this python file is not installed out-of-tree.</details>
Should this python file be installed out of tree? Do we have plans to eventually distribute Drake via something like `apt` or `brew` or a Windows `setup.exe` file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/Cars/steering_command_driver.py, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLHaR2D2KK9sw8vsxQ:-KHLL6rutGhtyNFABVQ8:-323440242) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/steering_command_driver.py#L194)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should this python file be installed out of tree? Do we have plans to eventually distribute Drake via something like `apt` or `brew` or a Windows `setup.exe` file?</details>
I would rather drive that discussion from a ticket about shipping pre-packaged examples and how that gets done, instead of of mucking with it now.  I doubt that just "copy the program into bindir during `make all`" will be the correct answer, and I'd rather not try to guess.  Right now, my concept of `examples/Cars` is that you only use it in-tree from source builds by developers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/steering_command_driver.py, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLHaR2D2KK9sw8vsxQ:-KHLNM8z1BK_hYCxAz7n:-33375737) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/steering_command_driver.py#L194)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I would rather drive that discussion from a ticket about shipping pre-packaged examples and how that gets done, instead of of mucking with it now.  I doubt that just "copy the program into bindir during `make all`" will be the correct answer, and I'd rather not try to guess.  Right now, my concept of `examples/Cars` is that you only use it in-tree from source builds by developers.</details>
OK :+1: .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294)*

**Comment by ggould-tri** [comment]
Platform :lgtm:, with one informational question below.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This is going to complicate my efforts in https://github.com/RobotLocomotion/drake/pull/2253 where I'm in the midst consolidating code that is shared between `car_sim_lcm` and `car_sim_lcm_and_ros` (as requested by @david-german-tri). However, since this is strictly an improvement above the existing code, I shall declare that it :lgtm_strong: .</details>


---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/car_sim_lcm.cpp, line 162 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLKjm-FKj0U27k4-E1:-KHLKjm-FKj0U27k4-E2:1288056249) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/car_sim_lcm.cpp#L162)):*
> ```cpp
> 
> int main(int argc, const char* argv[]) {
>   return drake::do_main(argc, argv);
> ```

Not clear to me why we are indirecting main here -- it isn't really required by any of our code conventions.  Is this in aid of future incorporation into another tool?  Or just to move more code into the anon namespace?

(Also I am surprised that the anonymous namespace works this way.  I learn something new about C++ every day.)

---

*[drake/examples/Cars/lcm_tap.h, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLLOLqfWsDYh5nOMx3:-KHLLOLqfWsDYh5nOMx4:800103811) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/lcm_tap.h#L24)):*
> ```objc
>   using InputVector = Vector<ScalarType>;
>   template <typename ScalarType>
>   using OutputVector = Vector<ScalarType>;
> ```

I wrote up a whole nasty comment about this (unenforceable type puns) before discovering that System demands it.  Oh well.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 207 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLMTzqZOLEL79YakUj:-KHLMTzqZOLEL79YakUk:-342605605) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/lcm_vector_gen.py#L207)):*
> ```Python
> #include "lcmtypes/drake/lcmt_%(snake)s_t.hpp"
> 
> namespace drake {
> ```

Yay! :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-:-KHLO9jsJoEfYrg1ohYz:1099945794)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/Cars/car_sim_lcm.cpp, line 162 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLKjm-FKj0U27k4-E1:-KHLOeV7gFkmsLZWYhV0:-2037639708) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/car_sim_lcm.cpp#L162)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Not clear to me why we are indirecting main here -- it isn't really required by any of our code conventions.  Is this in aid of future incorporation into another tool?  Or just to move more code into the anon namespace?
> 
> (Also I am surprised that the anonymous namespace works this way.  I learn something new about C++ every day.)</details>
Heh, I get asked that every time I do this.  The purpose is to write code without either saying `drake::Foo` or `using drake::Foo` for  every single typename.  Approximately ~all code in Drake can already do this, because its in a class in that namespace.  Putting `main()` code into that namespace makes it more alike with all the rest of Drake code, and lets it be concise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/Cars/lcm_tap.h, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLLOLqfWsDYh5nOMx3:-KHLPLaSifkPeB1pzJfs:695094271) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/lcm_tap.h#L24)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> I wrote up a whole nasty comment about this (unenforceable type puns) before discovering that System demands it.  Oh well.</details>
Oops, these should have been within the doxygen block for the concept, to make clear where the blame lies.  As much as I hate having to wait for another Jenkins round, I will fix that now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294)*

**Comment by jwnimmer-tri** [comment]
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/Cars/lcm_tap.h, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-KHLLOLqfWsDYh5nOMx3:-KHLSDpR10z_ReCAfrAn:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8749713736faf1834476755bd4748892ad94e7/drake/examples/Cars/lcm_tap.h#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Oops, these should have been within the doxygen block for the concept, to make clear where the blame lies.  As much as I hate having to wait for another Jenkins round, I will fix that now.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294)*

**Comment by jwnimmer-tri** [comment]
@ggould-tri Give me a green eyeball on r3, if you like it?

**Comment by ggould-tri** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> @ggould-tri Give me a green eyeball on r3, if you like it?</details>


---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2294#-:-KHLXc_bWWfSQ71vd_H-:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge:
- The jenkins errors is only msvc-64 hitting #2257.
- Out-of-date-with-master is only with respect to few unrelated commits.

**Pull request merged**
