### PR TITLE
Remove some calls to Rotmat2rpy

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9059)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9059#-:-LFtxLD2CuDKBQQud17b:b9rqlek)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri for platform review please.

---

Reviewed 10 of 10 files at r1.
Review status: 2 unresolved discussions, platform LGTM missing

---

*[manipulation/util/robot_state_msg_translator.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9059#-LFu-qpo1Im5cXUr1RNs:-LFu-qpo1Im5cXUr1RNt:b-59two6) ([raw file](https://github.com/robotlocomotion/drake/blob/38379ba04c12297d570a40f5d79f8f20ca99ffe4/manipulation/util/robot_state_msg_translator.cc#L165)):*
> ```cpp
>       const math::RotationMatrix<double> R_BJ = R_JB.inverse();
>       v.segment<3>(velocity_start) =  R_BJ * V_WB_J.head<3>();     // Rotational
>       v.segment<3>(velocity_start + 3) = R_BJ * V_WB_J.tail<3>();  // Translate.
> ```

`Translate` -> `Translational`, since you used `Rotational` above.

---

*[math/test/roll_pitch_yaw_test.cc, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9059#-LFu-0pM3ktdgr8pykOz:-LFu-0pM3ktdgr8pykP-:bbqknr4) ([raw file](https://github.com/robotlocomotion/drake/blob/38379ba04c12297d570a40f5d79f8f20ca99ffe4/math/test/roll_pitch_yaw_test.cc#L123)):*
> ```cpp
>   // Test SetFromQuaternionAndRotationMatrix.
>   rpy2.SetFromQuaternionAndRotationMatrix(quat, R1);
>   EXPECT_TRUE(rpy2.IsNearlySameOrientation(rpy, kEpsilon));
> ```

Also add a test for `SetFromQuaternionAndRotationMatrix` but with inconsistent quaternion and rotation matrix?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9059#-:-LFu-xaoE0bNVC3ha5gU:b-t6qajt)*

**Comment by sammy-tri** [comment]
Checkpoint (most of the way through)

Looking at CI I think this change found a real error in the pick and place tests.  Haven't checked to see if it will be difficult to fix...  hopefully not?

---

Reviewed 7 of 10 files at r1.
Review status: 2 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9059#-:-LFxC7Cs87qxitag6x_9:b9d260c)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: 2 unresolved discussions, platform LGTM from [sammy-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9059#-:-LG0sapVCbhC0Kil2sWf:bsf2vkf)*

**Pull request merged**
