### PR TITLE
Bazel Python Suppressions

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Adding python suppressions for Bazel.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6019)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-open-source

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please

**Comment by jamiesnape** [comment]
The other option is to simply not run Python tests under Valgrind by specifying a language filter (see #6046 for an example). Ideally, we would have test coverage of the core code elsewhere, and the question is whether there is much to gain by testing the glue for the bindings.

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
I am hesitant to commit to running valgrind on python tests across the board.  Possibly some opt-in valgrind tests focused on the `bindings` folder directly would make sense, but I'd probably want to be clear on the "python2 or python3 or both" call first.

Have we found any true-positive problems by running valgrind on python code yet?  If not, it might be worth turning on the language filter instead.

Any thoughts @stonier?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6019#-:-Kjj-_xidNIko7iP6Uqn:b-kge37l)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6019)*

**Comment by jamiesnape** [comment]
Python tests are being disabled by language filter in  #6077.

**Pull request closed without merging**
