### PR TITLE
Refactor macOS wheel build

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Rework macOS wheel build script to completely separate provisioning, dependency building, and building of the actual wheel. This more closely aligns with how the builder allows these stages to be skipped, and will also make it easier to build multiple wheels (which can share a dependency build).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20595)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for (feature? both?) review, please

**Review by mwoehlke-kitware — COMMENTED** [review]
(Note: not re-running CI for a change that only affects a comment...)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20595#-:-NkMrGkVEJO3bmLfDCiY:b-x6kjf9)* status: 3 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20595#-NkMBpTX7zjlKDPnAMt7:-NkMrMmK0DqH-QnOdkfC:b-r3iisc) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This patch caused me to notice an endemic problem with all wheel builder code that should probably be fixed in a separate pull request:

By default, Python uses an arbitrary platform-dependent encoding (between str and bytes) when nothing specific is specified as an argument.  This makes programs behave differently on different computers.  In the CI machines it will _probably_ still be consistent because they will have a consistent configuration during provisioning, but it's a bad habit and might bite us down the road.  For every call to `open` or `check_output` or etc. that assumes an unspecified encoding, at all of our call sites we must specify `encoding='utf-8'` to remove all ambiguity.
</blockquote></details>

That would imply ensuring that whatever command runs is also told to output UTF-8 rather than whatever locale is set. Blindly assuming that commands output UTF-8, rather than that they respect the system locale, doesn't seem like an improvement. OTOH, the chances that the system locale *isn't* UTF-8 and that the default `text=True` behavior is thus something other than converting from UTF-8, are slim.

___
___
*[`tools/wheel/macos/build-wheel.sh` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20595#-NkMAm4O8AmYIcejjyNb:-NkMsN4R6YzluDk__yaV:b-xathiy) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ea43fd3a8034dcef175467e0c61368455debfb0/tools/wheel/macos/build-wheel.sh#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This says "to build dependencies" but that doesn't seem accurate.  I think this is building Drake, not Drake's dependencies.
</blockquote></details>

Fixed. The text got copied from `build-dependencies.sh` and apparently I missed updating that sentence. Thanks for the catch!
___
*[`tools/wheel/macos/build-wheel.sh` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20595#-NkMDR3o8Fc532m3scKU:-NkMsYjQ-RSpWZyv9fKV:b17jlql) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c550ff71c8693d6b10bc72965f24de99fbdac0/tools/wheel/macos/build-wheel.sh#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Removing this seems like we're opening the door to bugs, even if our current CI provisioning gets lucky and avoids the trap.  Are we 100% sure that we don't need this variable to be set while Drake's own repository rules are running?
</blockquote></details>

:shrug: The comment suggests that only `gfortran` is affected. Does Drake's own build use Fortran? If yes (hmm... snopt?), or if we want to be paranoid about it, the logic should probably move to `macos.py`. WDYT?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20595)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20595#-NkMBpTX7zjlKDPnAMt7:-NkMtq0bBnh82PbAg7px:bx6kpsy) (no related file):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

That would imply ensuring that whatever command runs is also told to output UTF-8 rather than whatever locale is set. Blindly assuming that commands output UTF-8, rather than that they respect the system locale, doesn't seem like an improvement. OTOH, the chances that the system locale *isn't* UTF-8 and that the default `text=True` behavior is thus something other than converting from UTF-8, are slim.
</blockquote></details>

Most everything we touch (e.g., our Dockerfile) is definitely UTF-8.  I think the only exception might be the known_hosts, which anyway if it's not UTF-8 then we need to actually handle that correctly.  In no case is "let Python choose something arbitrarily" ever a satisfactory posture.  By rote, every single text-mode "open" or "subprocess" function call in Drake _must_ pass an encoding.  Think of it as a styleguide rule we haven't written a linter for yet.

___
___
*[`tools/wheel/macos/build-wheel.sh` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20595#-NkMDR3o8Fc532m3scKU:-NkMunuCCGNpmX7tvKyV:b-bulmsm) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c550ff71c8693d6b10bc72965f24de99fbdac0/tools/wheel/macos/build-wheel.sh#L56)):*
> Does Drake's own build use Fortran? If yes (hmm... snopt?)

Yes.  Drake's build runs `gfortran` to compile SNOPT.

> ... the logic should probably move to `macos.py`.

Seems like a good idea.  My goal is for you to convince yourself that the approach you take it sounds, however it works.

**Comment by mwoehlke-kitware** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Most everything we touch (e.g., our Dockerfile) is definitely UTF-8.  I think the only exception might be the known_hosts, which anyway if it's not UTF-8 then we need to actually handle that correctly.  In no case is "let Python choose something arbitrarily" ever a satisfactory posture.  By rote, every single text-mode "open" or "subprocess" function call in Drake _must_ pass an encoding.  Think of it as a styleguide rule we haven't written a linter for yet.
</blockquote></details>

How do we ensure that `ssh-keygen` is opening `known_hosts` in UTF-8? How do we ensure it's *outputting* in UTF-8?

`text=True` isn't "let[ting] Python choose something arbitrarily", it's telling Python to use the currently configured system encoding, which is the encoding the subprocess is *supposed* to use for output. Specifying `encoding='utf-8'` is either superfluous *or incorrect*; in order to not be incorrect, we would also need to instruct the subprocess to output in UTF-8. (And if we do that by changing the locale for the Python process, specifying the encoding is superfluous.)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20595)* status: 1 unresolved discussion

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20595)* status: 1 unresolved discussion

___
*[`tools/wheel/macos/build-wheel.sh` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20595#-NkMDR3o8Fc532m3scKU:-NkR42W02TZf0fhiMauX:b7msi6a) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c550ff71c8693d6b10bc72965f24de99fbdac0/tools/wheel/macos/build-wheel.sh#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Does Drake's own build use Fortran? If yes (hmm... snopt?)

Yes.  Drake's build runs `gfortran` to compile SNOPT.

> ... the logic should probably move to `macos.py`.

Seems like a good idea.  My goal is for you to convince yourself that the approach you take it sounds, however it works.
</blockquote></details>

Fixed (moved to `macos.py`).

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by mwoehlke-kitware** [comment]
@jwnimmer-tri, waiting on you to review/approve the latest changes...

**Comment by jwnimmer-tri** [comment]
Yes.  It will take me some time to go and study how the `locale...` subsystem works, before I can review that part of this change.  (The other parts are fine.)

**Comment by jwnimmer-tri** [comment]
(If this needs to merge to unblock other work, you could carve out the locale handling into a separate PR.)

**Comment by mwoehlke-kitware** [comment]
Done.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please.

**Pull request merged**
