### PR TITLE
August 2022 upgrades

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #17659.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17669)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(status: single reviewer ok).

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17669#-:-N8VWh7O1ztQmGBVe_WH:b-fl40af)* status: 1 unresolved discussion, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/rules_python/repository.bzl` line 17 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17669#-N8VW4_q9ykdpfZ1d6XA:-N8VW4_q9ykdpfZ1d6XB:b1my5a3) ([raw file](https://github.com/robotlocomotion/drake/blob/ce9ccce2dcc4c1621767c8954ce949bbcdeaecd9/tools/workspace/rules_python/repository.bzl#L17)):*
> ```Starlark
>         # The commit (version) and sha256 here should be identical to the
>         # commit listed in
>         # drake/tools/install/bazel/test/drake_bazel_installed_test.py.
> ```

The required edit to `drake_bazel_installed_test` appears to be be missing from this PR.  It should be incorporated into the same commit that changed this file.

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/rules_python/repository.bzl` line 17 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17669#-N8VW4_q9ykdpfZ1d6XA:-N8ZCbEBDzp0rufaOA4r:b-h40qwz) ([raw file](https://github.com/robotlocomotion/drake/blob/ce9ccce2dcc4c1621767c8954ce949bbcdeaecd9/tools/workspace/rules_python/repository.bzl#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The required edit to `drake_bazel_installed_test` appears to be be missing from this PR.  It should be incorporated into the same commit that changed this file.
</blockquote></details>

Ack, I missed that. Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17669)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
macOS was happy.  Just needs a rebase.

**Pull request merged**
