### PR TITLE
Add "multiple choice formulation" to approximate a bilinear product with its McCormick Envelope

### PR DESCRIPTION
**Pull request by hongkai-dai**
@avalenzu I added this new formulation based on equation 4.22 of your thesis. Equation 4.22 is for univariate partitioning. Do you think this PR uses the right formulation for bivariate partitioning?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8655)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8655#-:-LAaFn6P3pOOg0XVdysJ:bll7v0f)*

**Comment by avalenzu** [comment]
Checkpoint. Halfway through the doc.
+(status: curate commits before merging) 

---

Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---

*[solvers/mixed_integer_optimization_util.h, line 288 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAsf1888pjC_99A8Aw3:-LAsf1888pjC_99A8Aw4:b-vypj2e) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L288)):*
> ```objc
>  * y_min = φy(0) < φy(1) < ... < φy(n) = y_max
>  * </pre>
>  * , and divide the range of x to small intervals [φx(0), φx(1)],
> ```

BTW,

s/to small intervals/into intervals

Same for y below.

---

*[solvers/mixed_integer_optimization_util.h, line 291 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAsfPsB4ZmeRTAJWYM-:-LAsfPsB4ZmeRTAJWYM0:b-ufzlcp) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L291)):*
> ```objc
>  * [φx(1), φx(2)], ... , [φx(m-1), φx(m)], and the range of y to small
>  * intervals [φy(0), φy(1)], [φy(1), φy(2)], ..., [φy(n-1), φy(n)]. The xy
>  * plane is thus cut into grids, with each rectangle as
> ```

s/grids/rectangles

---

*[solvers/mixed_integer_optimization_util.h, line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAsfZHKD_EvcPcHap8K:-LAsfZHKD_EvcPcHap8L:bbx50aq) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L310)):*
> ```objc
>  *
>  * One formulation of the constraint is
>  * <pre>
> ```

FYI, doxygen [supports fenced code blocks](https://www.stack.nl/~dimitri/doxygen/manual/markdown.html#md_fenced), so  you can replace

```
<pre>
MATH
</pre>
```

with

````
```
MATH
```
````

---

*[solvers/mixed_integer_optimization_util.h, line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAssfnBDn1zRyPlmrC9:-LAssfnBDn1zRyPlmrCA:b-lgk4w1) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L321)):*
> ```objc
>  * w ≤ ∑ᵢⱼ (xij(i, j)*φy(j) + φx(i+1)*yij(i, j) - φx(i+1)*φy(j) * Bxy(i, j))
>  * w ≤ ∑ᵢⱼ (xij(i, j)*φy(j+1) + φx(i)*yij(i, j) - φx(i)*φy(j+1) * Bxy(i, j))
>  * </pre>
> ```

How would you feel about replacing this code block with
```
* x = ∑ᵢⱼ x̂ᵢⱼ
* y = ∑ᵢⱼ ŷᵢⱼ
* Bˣʸᵢⱼ = Bˣᵢ & Bʸⱼ
* ∑ᵢⱼ Bˣʸᵢⱼ = 1
* φˣᵢ Bˣʸᵢⱼ ≤ x̂ᵢⱼ ≤ φˣᵢ₊₁ Bˣʸᵢⱼ
* φʸⱼ Bˣʸᵢⱼ ≤ ŷᵢⱼ ≤ φʸⱼ₊₁ Bˣʸᵢⱼ
* w ≥ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ   + φˣᵢ   ŷᵢⱼ - φˣᵢ  φʸⱼ   Bˣʸᵢⱼ)
* w ≥ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ₊₁ + φˣᵢ₊₁ ŷᵢⱼ - φˣᵢ₊₁ φʸⱼ₊₁ Bˣʸᵢⱼ)
* w ≤ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ   + φˣᵢ₊₁ ŷᵢⱼ - φˣᵢ₊₁ φʸⱼ   Bˣʸᵢⱼ)
* w ≤ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ₊₁ + φˣᵢ   ŷᵢⱼ - φˣᵢ   φʸⱼ₊₁ Bˣʸᵢⱼ)
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8655#-:-LAtDfpQ6AKCV6jtIiA0:byvxgpt)*

**Comment by avalenzu** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/mixed_integer_optimization_util.h, line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAssfnBDn1zRyPlmrC9:-LAtDvMQC3rsdpQluxcm:bx3slxb) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L321)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

How would you feel about replacing this code block with
```
* x = ∑ᵢⱼ x̂ᵢⱼ
* y = ∑ᵢⱼ ŷᵢⱼ
* Bˣʸᵢⱼ = Bˣᵢ & Bʸⱼ
* ∑ᵢⱼ Bˣʸᵢⱼ = 1
* φˣᵢ Bˣʸᵢⱼ ≤ x̂ᵢⱼ ≤ φˣᵢ₊₁ Bˣʸᵢⱼ
* φʸⱼ Bˣʸᵢⱼ ≤ ŷᵢⱼ ≤ φʸⱼ₊₁ Bˣʸᵢⱼ
* w ≥ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ   + φˣᵢ   ŷᵢⱼ - φˣᵢ  φʸⱼ   Bˣʸᵢⱼ)
* w ≥ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ₊₁ + φˣᵢ₊₁ ŷᵢⱼ - φˣᵢ₊₁ φʸⱼ₊₁ Bˣʸᵢⱼ)
* w ≤ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ   + φˣᵢ₊₁ ŷᵢⱼ - φˣᵢ₊₁ φʸⱼ   Bˣʸᵢⱼ)
* w ≤ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ₊₁ + φˣᵢ   ŷᵢⱼ - φˣᵢ   φʸⱼ₊₁ Bˣʸᵢⱼ)
```
</blockquote></details>

No changes to the math, just changing nomenclature.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8655)*

**Comment by avalenzu** [comment]
Checkpoint. Done with the doc. Math looks right. Now I just need to check that the implementation matches.

---

Reviewed 1 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/mixed_integer_optimization_util.h, line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAssfnBDn1zRyPlmrC9:-LAxvDzO4m7Mwtp_lryp:b-i2s6c9) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L321)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

No changes to the math, just changing nomenclature.
</blockquote></details>

Use this version (fixed spacing in the first `w ≥` constraint) and added the rest of the description (up to the number of new variables).
````
 * One formulation of the constraint is
 * ```
 * x = ∑ᵢⱼ x̂ᵢⱼ
 * y = ∑ᵢⱼ ŷᵢⱼ
 * Bˣʸᵢⱼ = Bˣᵢ & Bʸⱼ
 * ∑ᵢⱼ Bˣʸᵢⱼ = 1
 * φˣᵢ Bˣʸᵢⱼ ≤ x̂ᵢⱼ ≤ φˣᵢ₊₁ Bˣʸᵢⱼ
 * φʸⱼ Bˣʸᵢⱼ ≤ ŷᵢⱼ ≤ φʸⱼ₊₁ Bˣʸᵢⱼ
 * w ≥ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ   + φˣᵢ   ŷᵢⱼ - φˣᵢ   φʸⱼ   Bˣʸᵢⱼ)
 * w ≥ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ₊₁ + φˣᵢ₊₁ ŷᵢⱼ - φˣᵢ₊₁ φʸⱼ₊₁ Bˣʸᵢⱼ)
 * w ≤ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ   + φˣᵢ₊₁ ŷᵢⱼ - φˣᵢ₊₁ φʸⱼ   Bˣʸᵢⱼ)
 * w ≤ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ₊₁ + φˣᵢ   ŷᵢⱼ - φˣᵢ   φʸⱼ₊₁ Bˣʸᵢⱼ).
 * ```
 * The "logical and" constraint Bˣʸᵢⱼ = Bˣᵢ & Bʸⱼ can be imposed as
 * ```
 * Bˣʸᵢⱼ ≥ Bˣᵢ + Bʸⱼ - 1
 * Bˣʸᵢⱼ ≤ Bˣᵢ
 * Bˣʸᵢⱼ ≤ Bʸⱼ
 * 0 ≤ Bˣʸᵢⱼ ≤ 1.
 * ```
 *
 * We can further simplify these constraints, by defining two vectors
 * `x̅ ∈ ℝⁿ`, `y̅ ∈ ℝᵐ` as
 * ```
 * x̅ⱼ = ∑ᵢ x̂ᵢⱼ
 * y̅ᵢ = ∑ⱼ ŷᵢⱼ
 * ```
 * and the constraints above can be re-formulated using `x̅` and `y̅` as
 * ```
 * x = ∑ⱼ x̅ⱼ
 * y = ∑ᵢ y̅ᵢ
 * Bˣʸᵢⱼ = Bˣᵢ & Bʸⱼ
 * ∑ᵢⱼ Bˣʸᵢⱼ = 1
 * ∑ᵢ φˣᵢ Bˣʸᵢⱼ ≤ x̅ⱼ ≤ ∑ᵢ φˣᵢ₊₁ Bˣʸᵢⱼ
 * ∑ⱼ φʸⱼ Bˣʸᵢⱼ ≤ y̅ᵢ ≤ ∑ⱼ φʸⱼ₊₁ Bˣʸᵢⱼ
 * w ≥ ∑ⱼ( x̅ⱼ φʸⱼ   ) + ∑ᵢ( φˣᵢ   y̅ᵢ ) - ∑ᵢⱼ( φˣᵢ   φʸⱼ   Bˣʸᵢⱼ )
 * w ≥ ∑ⱼ( x̅ⱼ φʸⱼ₊₁ ) + ∑ᵢ( φˣᵢ₊₁ y̅ᵢ ) - ∑ᵢⱼ( φˣᵢ₊₁ φʸⱼ₊₁ Bˣʸᵢⱼ )
 * w ≤ ∑ⱼ( x̅ⱼ φʸⱼ   ) + ∑ᵢ( φˣᵢ₊₁ y̅ⱼ ) - ∑ᵢⱼ( φˣᵢ₊₁ φʸⱼ   Bˣʸᵢⱼ )
 * w ≤ ∑ⱼ( x̅ⱼ φʸⱼ₊₁ ) + ∑ᵢ( φˣᵢ   y̅ᵢ ) - ∑ᵢⱼ( φˣᵢ   φʸⱼ₊₁ Bˣʸᵢⱼ ).
 * ```
 * In this formulation, we introduce new continuous variables `x̅`, `y̅`, `Bˣʸ`. The
 * total number of new variables is m + n + m * n.
````
You may want to rename `xj` and `yi` to `x_bar` and `y_bar` in the code as well.

---

*[solvers/mixed_integer_optimization_util.h, line 323 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAtFkFW3OGG0PS3Z3cz:-LAtFkFW3OGG0PS3Z3d-:be3g9ug) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L323)):*
> ```objc
>  * </pre>
>  *
>  * The "logical and" constraint Bxy(i, j) = Bx(i) & By(j) can be imposed as
> ```

BTW, you could consider using `∧` instead of `&`, since this is a mathematical description.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8655#-:-LAxwhRi3itEW6eZTc2D:b87jxi5)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[solvers/mixed_integer_optimization_util.h, line 288 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAsf1888pjC_99A8Aw3:-LAyTY4A2T5jq845Lg2c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L288)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW,

s/to small intervals/into intervals

Same for y below.

</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 291 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAsfPsB4ZmeRTAJWYM-:-LAyTlRoDT1mPaQDSOGF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L291)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/grids/rectangles
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAsfZHKD_EvcPcHap8K:-LAyTz6DEVw88kE6lMPU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L310)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

FYI, doxygen [supports fenced code blocks](https://www.stack.nl/~dimitri/doxygen/manual/markdown.html#md_fenced), so  you can replace

```
<pre>
MATH
</pre>
```

with

````
```
MATH
```
````
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAssfnBDn1zRyPlmrC9:-LAyWtPv04LLHe0krZI-:bkes82i) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L321)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Use this version (fixed spacing in the first `w ≥` constraint) and added the rest of the description (up to the number of new variables).
````
 * One formulation of the constraint is
 * ```
 * x = ∑ᵢⱼ x̂ᵢⱼ
 * y = ∑ᵢⱼ ŷᵢⱼ
 * Bˣʸᵢⱼ = Bˣᵢ & Bʸⱼ
 * ∑ᵢⱼ Bˣʸᵢⱼ = 1
 * φˣᵢ Bˣʸᵢⱼ ≤ x̂ᵢⱼ ≤ φˣᵢ₊₁ Bˣʸᵢⱼ
 * φʸⱼ Bˣʸᵢⱼ ≤ ŷᵢⱼ ≤ φʸⱼ₊₁ Bˣʸᵢⱼ
 * w ≥ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ   + φˣᵢ   ŷᵢⱼ - φˣᵢ   φʸⱼ   Bˣʸᵢⱼ)
 * w ≥ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ₊₁ + φˣᵢ₊₁ ŷᵢⱼ - φˣᵢ₊₁ φʸⱼ₊₁ Bˣʸᵢⱼ)
 * w ≤ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ   + φˣᵢ₊₁ ŷᵢⱼ - φˣᵢ₊₁ φʸⱼ   Bˣʸᵢⱼ)
 * w ≤ ∑ᵢⱼ (x̂ᵢⱼ φʸⱼ₊₁ + φˣᵢ   ŷᵢⱼ - φˣᵢ   φʸⱼ₊₁ Bˣʸᵢⱼ).
 * ```
 * The "logical and" constraint Bˣʸᵢⱼ = Bˣᵢ & Bʸⱼ can be imposed as
 * ```
 * Bˣʸᵢⱼ ≥ Bˣᵢ + Bʸⱼ - 1
 * Bˣʸᵢⱼ ≤ Bˣᵢ
 * Bˣʸᵢⱼ ≤ Bʸⱼ
 * 0 ≤ Bˣʸᵢⱼ ≤ 1.
 * ```
 *
 * We can further simplify these constraints, by defining two vectors
 * `x̅ ∈ ℝⁿ`, `y̅ ∈ ℝᵐ` as
 * ```
 * x̅ⱼ = ∑ᵢ x̂ᵢⱼ
 * y̅ᵢ = ∑ⱼ ŷᵢⱼ
 * ```
 * and the constraints above can be re-formulated using `x̅` and `y̅` as
 * ```
 * x = ∑ⱼ x̅ⱼ
 * y = ∑ᵢ y̅ᵢ
 * Bˣʸᵢⱼ = Bˣᵢ & Bʸⱼ
 * ∑ᵢⱼ Bˣʸᵢⱼ = 1
 * ∑ᵢ φˣᵢ Bˣʸᵢⱼ ≤ x̅ⱼ ≤ ∑ᵢ φˣᵢ₊₁ Bˣʸᵢⱼ
 * ∑ⱼ φʸⱼ Bˣʸᵢⱼ ≤ y̅ᵢ ≤ ∑ⱼ φʸⱼ₊₁ Bˣʸᵢⱼ
 * w ≥ ∑ⱼ( x̅ⱼ φʸⱼ   ) + ∑ᵢ( φˣᵢ   y̅ᵢ ) - ∑ᵢⱼ( φˣᵢ   φʸⱼ   Bˣʸᵢⱼ )
 * w ≥ ∑ⱼ( x̅ⱼ φʸⱼ₊₁ ) + ∑ᵢ( φˣᵢ₊₁ y̅ᵢ ) - ∑ᵢⱼ( φˣᵢ₊₁ φʸⱼ₊₁ Bˣʸᵢⱼ )
 * w ≤ ∑ⱼ( x̅ⱼ φʸⱼ   ) + ∑ᵢ( φˣᵢ₊₁ y̅ⱼ ) - ∑ᵢⱼ( φˣᵢ₊₁ φʸⱼ   Bˣʸᵢⱼ )
 * w ≤ ∑ⱼ( x̅ⱼ φʸⱼ₊₁ ) + ∑ᵢ( φˣᵢ   y̅ᵢ ) - ∑ᵢⱼ( φˣᵢ   φʸⱼ₊₁ Bˣʸᵢⱼ ).
 * ```
 * In this formulation, we introduce new continuous variables `x̅`, `y̅`, `Bˣʸ`. The
 * total number of new variables is m + n + m * n.
````
You may want to rename `xj` and `yi` to `x_bar` and `y_bar` in the code as well.
</blockquote></details>

Wow, thanks a lot for typing all these equations in unicode! Much appreciate it!

---

*[solvers/mixed_integer_optimization_util.h, line 323 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAtFkFW3OGG0PS3Z3cz:-LAyWznw11XSBJJrFTOt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L323)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, you could consider using `∧` instead of `&`, since this is a mathematical description.
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.cc, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAy9YigD3MR5Xd9NzET:-LAyX-xu9GAMiR3m3KCN:b322et1) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.cc#L144)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, what are the unary `+` operators for here?
</blockquote></details>

It is the trick to convert a symbolic variable `Bx(i)` to a symbolic expression.

---

*[solvers/test/mixed_integer_optimization_util_test.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAyCABQ8fdU1M9cxPna:-LAyY2BaCTTcrd-w9njf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/test/mixed_integer_optimization_util_test.cc#L286)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Could this be renamed `CheckFeasibility`? The current name doesn't quite fit with the fact that sometimes the desired outcome is for the program to be infeasible. It also makes me expect a `bool` as the return type.
</blockquote></details>

Done.

---

*[solvers/test/mixed_integer_optimization_util_test.cc, line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAyF4GKB6w5d1aDjMTi:-LAyYCmYDaVbmzIW3BW2:b-jj8f9b) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/test/mixed_integer_optimization_util_test.cc#L336)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Does this comment about "gray code" still belong here?
</blockquote></details>

I think so. This function works for both linear number of binary variables, and the logarithmic number of binary variables. In logarithmic case, it uses gray code.

---

*[solvers/test/mixed_integer_optimization_util_test.cc, line 494 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAyFK_M8NPGgRyXjX_Z:-LAyYTWs1gbaQ-6MSrge:b-4b232v) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/test/mixed_integer_optimization_util_test.cc#L494)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Just double checking: This class does not need to override `TestLinearObjectiveCheck()` correct?
</blockquote></details>

That is right, it does not need to override `TestLinearObjectiveCheck()`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8655)*

**Comment by avalenzu** [comment]
:lgtm: with one remaining BTW. +@sherm1 for platform review.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mixed_integer_optimization_util.h, line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAssfnBDn1zRyPlmrC9:-LB6CJwx5L0-hZrTL7hX:blyphgc) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L321)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Wow, thanks a lot for typing all these equations in unicode! Much appreciate it!
</blockquote></details>

No problem!

---

*[solvers/mixed_integer_optimization_util.h, line 356 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6DL0w3V4fX8p-8cj0:-LB6DL0w3V4fX8p-8cj1:b-255rg1) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L356)):*
> ```objc
>  * this formulation is called "Multiple Choice Model"
>  * @note We DO NOT add the constraint
>  * Bx(i) ∈ {0, 1}, By(j) ∈ {0, 1}
> ```

BTW. Sorry, I didn't provide an updated version of this paragraph in my earlier comments. Could you change the symbols here to match the ones above?

---

*[solvers/mixed_integer_optimization_util.cc, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LAy9YigD3MR5Xd9NzET:-LB6DXbWC7nF9TuxCJzV:bb6skj0) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.cc#L144)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is the trick to convert a symbolic variable `Bx(i)` to a symbolic expression.
</blockquote></details>

Aha!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8655#-:-LB6DyLn7MBRQqw0K1es:b-fbym1v)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[solvers/mixed_integer_optimization_util.h, line 155 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6rpS28ZaGBy0tFvhr:-LB7923h8qyTIUhJoFB_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adb5d9239489eca89fe98f6102981943cb682799/solvers/mixed_integer_optimization_util.h#L155)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider using superscript φˣ and φʸ as you did below.  
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 158 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6sO8F49UB9dXxVJZY:-LB792P47w1qvakbRXmo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adb5d9239489eca89fe98f6102981943cb682799/solvers/mixed_integer_optimization_util.h#L158)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should be n intervals for φʸ rather than m.
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 191 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6tf-z--UfG9rUSBSX:-LB79zU2ANZfCV54FNtJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adb5d9239489eca89fe98f6102981943cb682799/solvers/mixed_integer_optimization_util.h#L191)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW constraint -> constraints or (constraint ... is)
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 195 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6tku49A3URiDkhhnQ:-LB7A-tu4XkkLX8YK8r4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adb5d9239489eca89fe98f6102981943cb682799/solvers/mixed_integer_optimization_util.h#L195)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW here you switched to φx rather than φˣ. Either seems good but should be consistent.
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 282 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6vMNR-KFMnMOwqDX3:-LB7AQGu0-ICaIJCfCK1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adb5d9239489eca89fe98f6102981943cb682799/solvers/mixed_integer_optimization_util.h#L282)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is the same first sentence ("brief") as for the SOS2 version. Consider reworking the brief so that a user looking at the doxygen can tell from the first sentence how the two methods are different.
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 284 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6v00S8wLMA1lZ0Q5T:-LB7AWBYCjW2ays-qKIr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adb5d9239489eca89fe98f6102981943cb682799/solvers/mixed_integer_optimization_util.h#L284)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW φˣ φʸ ?
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 301 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6vih94LRS2a2FffPd:-LB7AadV11aPICJ2UXTl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adb5d9239489eca89fe98f6102981943cb682799/solvers/mixed_integer_optimization_util.h#L301)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW will approximates -> will approximate, or just say "~~will~~ approximates"
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.h, line 354 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6wB8A9hR4qoXX7jyh:-LB7Anb56i-JejsFaTzd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adb5d9239489eca89fe98f6102981943cb682799/solvers/mixed_integer_optimization_util.h#L354)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI first line short -- consider reflow.
</blockquote></details>

Done.

---

*[solvers/mixed_integer_optimization_util.cc, line 146 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6whO69RI6DBrqd2xH:-LB7Gs4v4a3dPZFrIPwy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adb5d9239489eca89fe98f6102981943cb682799/solvers/mixed_integer_optimization_util.cc#L146)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per f2f confusion -- this trick needs a comment to explain that you are creating an expression from a variable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8655)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[solvers/mixed_integer_optimization_util.h, line 356 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8655#-LB6DL0w3V4fX8p-8cj0:-LB7H16n802KhWbAOEDb:b-c40xmw) ([raw file](https://github.com/robotlocomotion/drake/blob/dcd89f5e8b0bcf310dbbc969cac738b4b9dc8e4b/solvers/mixed_integer_optimization_util.h#L356)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I deliberately leave `Bx` and `By` here, since they are the name of the variables.
</blockquote></details>

If you think it is better to use Bˣ instead of `Bx` here, I will change it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8655)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8655)*

**Pull request merged**
