### PR TITLE
Remove vtk from CMake build

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6476)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm: +@soonho-tri for platform review, please.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6476#-:-KnpQuTGQdsGtdvSWnQ7:b-yrdi02)*

**Comment by soonho-tri** [comment]
:lgtm:

BTW, a related issue: When this PR gets merged, can we update http://drake.mit.edu/mac.html to remove `pyqt@4`, `qwt-qt4`, and `vtk5`? My understanding is that we have them for a CMake build. They cause problems when we use `bazel` and have to remove them to make it work.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6476#-:-KnqkTJk7OfsxW9emuin:b-2nind1)*

**Comment by soonho-tri** [comment]
> pyqt@4

OK. We don't have this one anymore at least.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6476#-:-KnqlBftBDgNpJN8xrY7:bhcdj5u)*

**Comment by jamiesnape** [comment]
Still needed for Director for the moment, though that will change in the next few days.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6476#-:-KnqlQHQIxOjt2FbHZMm:bhg84tp)*

**Comment by soonho-tri** [comment]
I see. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6476#-:-KnqmHfuQi4JLVu9haxu:bhxjq5r)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6476)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6476)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6476)*

**Pull request merged**
