### PR TITLE
Scs solver for linear programs

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7447)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/scs/scs.BUILD.bazel, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-KyaGBVDOR0uRvX6sKdf:-KyaGBVDOR0uRvX6sKdg:bezrybd) ([raw file](https://github.com/robotlocomotion/drake/blob/78f9f029c568addc6f5aead9a11a8fbaa6dd77ee/tools/workspace/scs/scs.BUILD.bazel#L28)):*
> ```
> # libdrake.so links only to :scsdir.
> 
> SCS_HDRS = glob(["include/*.h"]) + ["linsys/amatrix.h"] + ["linsys/common.h"]
> ```

BTW Since we need both headers in `linsys`, try`glob(["include/*.h", "linsys/*.h"] )` (may need to split onto two lines to keep the linter happy)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/scs/scs.BUILD.bazel, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-KyaGBVDOR0uRvX6sKdf:-KybMS5lr2NT4JmvtdfN:bi3zwor) ([raw file](https://github.com/robotlocomotion/drake/blob/78f9f029c568addc6f5aead9a11a8fbaa6dd77ee/tools/workspace/scs/scs.BUILD.bazel#L28)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Since we need both headers in `linsys`, try`glob(["include/*.h", "linsys/*.h"] )` (may need to split onto two lines to keep the linter happy)
</blockquote></details>

Done. Thanks! I realized that I do not need to expose `linsys/common.h`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-KybMmFOV8-yhCfciEjq:bfa19nn)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
El Capitan is gone now in favor of High Sierra.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-Kyb_9X1Z3e9w57PsmnZ:b-icpdbq)*

**Comment by hongkai-dai** [comment]
-(status: do not review) +@frankpermenter for feature review please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-KybxVSfeR8QUWfnUjIm:bak9nh5)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  linux-xenial-clang-cmake-experimental please

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-KyqMQLaaQSmfThwzxdf:b4i1e0u)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  linux-xenial-gcc-cmake-experimental-matlab please

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-KyqT6Ufluce4mK9P-IF:b-dn4s1m)*

**Comment by hongkai-dai** [comment]
+@avalenzu for feature review please.
@drake-jenkins-bot retest everything please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-KyqwGDSgOpqK__xhQfp:bd0ns19)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot retest this please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-KyqwjGzvJQIfaTsw5vM:bvi7gqa)*

**Comment by frankpermenter** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-KyvbGRlKqqRFh-fymad:bnfp4nl)*

**Comment by frankpermenter** [comment]
Reviewed 6 of 11 files at r1, 5 of 6 files at r2, 2 of 2 files at r3.
Review status: 12 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review please.

---

Review status: 12 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-Kz1u088YcYXmFgAiirl:b-1zm1j3)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 6 of 11 files at r1, 4 of 6 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/scs_solver.cc, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4EX3t00t0pXeCmzcu:-Kz4EX3t00t0pXeCmzcv:b-psng54) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/scs_solver.cc#L35)):*
> ```cpp
>                            std::vector<double>* b, int* A_row_count,
>                            SCS_CONE* cone) {
>   // The linear constraint l <= aᵀx <= u is converted to
> ```

I'd recommend against using `l` as a single-character name, even in comments. It's just too easy for it to end up looking like  `1` in fonts (like the one used by Reviewable) that don't make those characters visually distinct. Might I suggest `ℓ`("ell") instead? Also, I'd replace `<=` with `≤`. Or you could go all out and use unicode's special math italics: `ℓ ≤ 𝑎ᵀ𝑥 ≤ 𝑢` but that might be overkill :)

---

*[drake/solvers/scs_solver.cc, line 54 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4MyzdUkeylaqYqVwD:-Kz4MyzdUkeylaqYqVwE:b-njxm7o) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/scs_solver.cc#L54)):*
> ```cpp
>          ++i) {
>       const bool is_u_inf{std::isinf(u(i))};
>       const bool is_l_inf{std::isinf(l(i))};
> ```

Again, I'd recommend against `l` here. `is_{lower,upper}_bound_finite` might be better to avoid the double negatives in the following if statement. 

---

*[drake/solvers/scs_solver.cc, line 209 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4R1FBlwtKlLixNhHY:-Kz4R1FBlwtKlLixNhHZ:byanqn9) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/scs_solver.cc#L209)):*
> ```cpp
> 
> void SetScsProblemSettingsToDefault(SCS_SETTINGS* settings) {
>   settings->alpha = ALPHA;
> ```

Where are these macro's coming from?

---

*[drake/solvers/scs_solver.cc, line 263 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4ROoIE7fL_mJTnnAO:-Kz4ROoIE7fL_mJTnnAP:bkerl58) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/scs_solver.cc#L263)):*
> ```cpp
>   //     s in K
>   // where K is a Cartesian product of some primitive cones.
>   // The cones has to be in this order
> ```

"has" -> "have"

---

*[drake/solvers/test/scs_solver_test.cc, line 42 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4Rzm2gVnlK8ThK2d3:-Kz4Rzm2gVnlK8ThK2d4:btdvh0v) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/test/scs_solver_test.cc#L42)):*
BTW

> The accuracy of SCS is not high, so we choose 1E-2 here, 10x the epsilon defined in SCS.

So SCS can't solve with accuracy beyond than 1e-3?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-Kz4SqgvDo8pKsOt0dQh:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/scs_solver.cc, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4EX3t00t0pXeCmzcu:-Kz4YyNXB7tHJqbLlv77:b-4wlqq0) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/scs_solver.cc#L35)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

I'd recommend against using `l` as a single-character name, even in comments. It's just too easy for it to end up looking like  `1` in fonts (like the one used by Reviewable) that don't make those characters visually distinct. Might I suggest `ℓ`("ell") instead? Also, I'd replace `<=` with `≤`. Or you could go all out and use unicode's special math italics: `ℓ ≤ 𝑎ᵀ𝑥 ≤ 𝑢` but that might be overkill :)
</blockquote></details>

Done. I changed `l` to `lb`, `u` to `ub`. Hopefully a two-letter name makes the meaning more clear.

---

*[drake/solvers/scs_solver.cc, line 54 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4MyzdUkeylaqYqVwD:-Kz4ZS6bL-8ktYwZC_li:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/scs_solver.cc#L54)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Again, I'd recommend against `l` here. `is_{lower,upper}_bound_finite` might be better to avoid the double negatives in the following if statement. 
</blockquote></details>

Done. Good call.

---

*[drake/solvers/scs_solver.cc, line 209 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4R1FBlwtKlLixNhHY:-Kz4ZUNN53VclUTV6tya:b-n27nr6) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/scs_solver.cc#L209)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Where are these macro's coming from?
</blockquote></details>

They are defined in SCS

---

*[drake/solvers/scs_solver.cc, line 263 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4ROoIE7fL_mJTnnAO:-Kz4Zo5WyuEfgBbZ9WKh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/scs_solver.cc#L263)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

"has" -> "have"
</blockquote></details>

Done.

---

*[drake/solvers/test/scs_solver_test.cc, line 42 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz4Rzm2gVnlK8ThK2d3:-Kz4ZpDlNPwW0KPY0-En:brlgtu) ([raw file](https://github.com/robotlocomotion/drake/blob/a3150e0d18ba3da155e47cb1f307794f5fcebab0/drake/solvers/test/scs_solver_test.cc#L42)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW

> The accuracy of SCS is not high, so we choose 1E-2 here, 10x the epsilon defined in SCS.

So SCS can't solve with accuracy beyond than 1e-3?
</blockquote></details>

It can, but the default is 1E-3, as `EPS` defined in https://github.com/cvxgrp/scs/blob/master/include/constants.h#L26

SCS uses a ADMM method, which converges fast to modest accuracy, but then improves very slowly. This is explained in http://stanford.edu/~boyd/admm.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) Partial pass done.  Unfortunately I don't think I'll be able to get to the rest of this today.  Sorry for the delay!

---

Reviewed 6 of 11 files at r1, 2 of 6 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: 12 of 13 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/solvers/BUILD.bazel, line 591 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5n4exo2cTXSkWCPnj:-Kz5n4f-q109ojYk_hNX:b40znhd) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/BUILD.bazel#L591)):*
> ```
>     hdrs = ["scs_solver.h"],
>     deps = select({
>         "//conditions:default": [
> ```

BTW it would look a bit nicer if this `select` had the conditions in the same order as the one above.

---

*[drake/solvers/mathematical_program.cc, line 662 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5oIuOdUSCSYgvzCE6:-Kz5oIuQ1SvkSTPn2w6e:bwl6aeu) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/mathematical_program.cc#L662)):*
> ```cpp
>              nlopt_solver_->available()) {
>     return nlopt_solver_->Solve(*this);
>   } else if (is_satisfied(required_capabilities_, kScsCapabilities) &&
> ```

Should this come before the generic solvers?  If any of snopt, nlopt, or ipopt are enabled (which at least one probably is) they'll get called before we ever get to scs.  (If this is the desired behavior, we should probably mention why scs is only called in this last resort scenario, even if it's just to comment that SCS isn't generally accurate enough (or whatever)).

---

*[drake/solvers/scs_solver.cc, line 18 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5pimXvRAE-oqf3eNL:-Kz5pimXvRAE-oqf3eNM:bbc0yq) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/scs_solver.cc#L18)):*
> ```cpp
> namespace drake {
> namespace solvers {
> void ParseLinearCost(const MathematicalProgram& prog, Eigen::VectorXd* c,
> ```

Should this function (along with `ParseLinearConstraint` and the other free functions in this file be in the anonymous namespace?

---

*[drake/solvers/scs_solver.h, line 29 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5oquAV0BHYg4bBO4u:-Kz5oquBv2WV74MsdYtY:b1khcj4) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/scs_solver.h#L29)):*
> ```objc
>   // If the user want the solver to print out debug message, then set this to
>   // true; otherwise set it to false. The default is false.
>   void SetVerbose(bool verbose) {verbose_ = verbose;}
> ```

missing whitespace inside '{}'.

---

*[drake/solvers/scs_solver.h, line 29 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5ovHhFp1vN6fq_jNv:-Kz5ovHhFp1vN6fq_jNw:bo126y3) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/scs_solver.h#L29)):*
> ```objc
>   // If the user want the solver to print out debug message, then set this to
>   // true; otherwise set it to false. The default is false.
>   void SetVerbose(bool verbose) {verbose_ = verbose;}
> ```

BTW I feel like this would more typically be done with SetSolverOption, but that interface also leaves a bit to be desired, so this might be OK as it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-Kz5k-7mVplPfRCHg2Ya:bi3hpvf)*

**Comment by hongkai-dai** [comment]
Review status: 12 of 13 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/solvers/BUILD.bazel, line 591 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5n4exo2cTXSkWCPnj:-Kz7WmTxgrqJ82T59qb5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/BUILD.bazel#L591)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW it would look a bit nicer if this `select` had the conditions in the same order as the one above.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 662 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5oIuOdUSCSYgvzCE6:-Kz7XC-AfKZspr4AgBip:b394mty) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/mathematical_program.cc#L662)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this come before the generic solvers?  If any of snopt, nlopt, or ipopt are enabled (which at least one probably is) they'll get called before we ever get to scs.  (If this is the desired behavior, we should probably mention why scs is only called in this last resort scenario, even if it's just to comment that SCS isn't generally accurate enough (or whatever)).
</blockquote></details>

Done. Good call, I added the documentation.

---

*[drake/solvers/scs_solver.cc, line 18 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5pimXvRAE-oqf3eNL:-Kz7XXWutOoO8mjMp_Zb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/scs_solver.cc#L18)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this function (along with `ParseLinearConstraint` and the other free functions in this file be in the anonymous namespace?
</blockquote></details>

Done.

---

*[drake/solvers/scs_solver.h, line 29 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5oquAV0BHYg4bBO4u:-Kz7XdfKr30KOMCYMH8e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/scs_solver.h#L29)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

missing whitespace inside '{}'.
</blockquote></details>

Done.

---

*[drake/solvers/scs_solver.h, line 29 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz5ovHhFp1vN6fq_jNv:-Kz7XeE1BLKOkW2uTrFL:b3cexp5) ([raw file](https://github.com/robotlocomotion/drake/blob/23b0c4f5a19cbedbf710197b5a99350d1d024479/drake/solvers/scs_solver.h#L29)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I feel like this would more typically be done with SetSolverOption, but that interface also leaves a bit to be desired, so this might be OK as it is.
</blockquote></details>

I now feel it is more natural to set this for each solver interface. When setting the solver options, the user already know which solver he/she would choose, so we should provide the API to set the option in each solver interface. I can add a TODO here, so that we can set the option through either the solver interface, or `MathematicalProgram`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447)*

**Comment by avalenzu** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-:-Kz9nyyfgotWLQHNF-DX:b-l70wzf)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/scs_solver.cc, line 171 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/7447#-Kz9X_jv__VsbETTYEgJ:-Kz9o_O3rZ671d08ixuM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/262374232a9dc7f8520cb1cbd94429f761a4d535/drake/solvers/scs_solver.cc#L171)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Missing whitespace after ':' http://drake.mit.edu/styleguide/cppguide.html#Horizontal_Whitespace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7447)*

**Pull request merged**
