### PR TITLE
[meldis] Support deformable geometries

### PR DESCRIPTION
**Pull request by DamrongGuoy**
- Subscribe to DRAKE_VIEWER_DEFORMABLE lcm channel
- Convert lcmt_viewer_link_data and lcmt_viewer_geometry_data to meshcat's triangle meshes.

Towards #16875

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848#-:-NBKjC4sCXYV4zgHqD9v:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
CC: @xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848#-:-NBKjf-K3NxFNmerjfeM:buj42el)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
@rpoyner-tri I have finished what we discussed about `lcm.Publish()`.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848#-:-NBOn3aB0veJPsPzIPgU:b-1xqa5k)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: minor stuff

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848#-:-NBOsaay6NaXwLP3Su6c:bo23mka)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[`bindings/pydrake/visualization/meldis.py` line 202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOr5uK7_i7I2pvSK3M:-NBOr5uK7_i7I2pvSK3N:b-dzaej5) ([raw file](https://github.com/robotlocomotion/drake/blob/e09f6b0fcf2b006fd65d40cd8cdc585a838926b8/bindings/pydrake/visualization/meldis.py#L202)):*
> ```Python
>         """Given an lcmt_viewer_geometry_data, parse it into a tuple of
>         (vertices, faces, Rgba, RigidTransform) if the geometry type is a
>         MESH"""
> ```

same as below -- need period (.), and move closing triple-quote to its own line.
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 191 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOqDjZENo1LVhtKCbR:-NBOqDj_EMTryKfmTPmK:b-m9i8yw) ([raw file](https://github.com/robotlocomotion/drake/blob/e09f6b0fcf2b006fd65d40cd8cdc585a838926b8/bindings/pydrake/visualization/test/meldis_test.py#L191)):*
> ```Python
>     def test_deformable(self):
>         """Check that _ViewerApplet doesn't crash for deformable geometries
>         in DRAKE_VIEWER_DEFORMABLE channel"""
> ```

End sentence with a period (.) .
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 191 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOqIi86iIMnc_D1H2z:-NBOqIi86iIMnc_D1H3-:bz7ct0l) ([raw file](https://github.com/robotlocomotion/drake/blob/e09f6b0fcf2b006fd65d40cd8cdc585a838926b8/bindings/pydrake/visualization/test/meldis_test.py#L191)):*
> ```Python
>     def test_deformable(self):
>         """Check that _ViewerApplet doesn't crash for deformable geometries
>         in DRAKE_VIEWER_DEFORMABLE channel"""
> ```

Typical python formatting for multiline docstrings is to put the closing triple-quote on a line by itself. See guidance from the famous style document [PEP 8](https://peps.python.org/pep-0008/#documentation-strings).
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 223 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOpkKP8rVNJt9K3_tR:-NBOpkKP8rVNJt9K3_tS:b-2uuzjl) ([raw file](https://github.com/robotlocomotion/drake/blob/e09f6b0fcf2b006fd65d40cd8cdc585a838926b8/bindings/pydrake/visualization/test/meldis_test.py#L223)):*
> ```Python
>         message.num_geom = 1
>         message.geom = [geom0]
>         meshcat_path = "/DRAKE_VIEWER/"
> ```

nit For readability, I might take these lines that construct the expected  `meshcat_path` and move them down to group them with the first assert below. As it is, they blend in with the code that builds the message.

Also, you may prefer modern python magic of [f strings](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals):

```
meshcat_path = f"/DRAKE_VIEWER/{message.robot_num}/{message.name}"
```

You don't have to convert to f strings, but you might like it. Try it and see!

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOoXvg-8jjCEQsJR1_:-NBOoXvg-8jjCEQsJR1a:bvs2b2p) (no related file):*
@rpoyner-tri I also played around to see whether I can hack the unit test to show me the picture.  My failed attempts are:

1. `webbrowser.open(url=dut.meshcat.web_url(), new=1)`.  It opened the meshcat window, but I didn't see anything drawn.
2. Add `dut.serve_forever()` at the last line. It crashed.

I do have an interesting observation.  If I do this:
1. ` bazel run //tools:meldis -- -w` in a separate terminal.
2.  run the unit test `bazel run //bindings/pydrake/visualization:py/meldis_test` in another terminal.
then, I saw the picture from the first test (`def test_viewer_applet(self):`) which uses `acrobot.sdf`.


Then, it gave me an idea.  I removed all the other tests except deformable (`def test_deformable(self):`) and run the unit test `bazel run //bindings/pydrake/visualization:py/meldis_test` again.  Then, I can see the deformable tetrahedron from the unit test.


I do not completely understand why.  I'm guessing if I can tell `bazel` to run only one test in the python unit test, I'll be able to see the same thing without changing the source code at all.

___

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`bindings/pydrake/visualization/meldis.py` line 202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOr5uK7_i7I2pvSK3M:-NBOvdvYAM_oehSZs4Xd:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/e09f6b0fcf2b006fd65d40cd8cdc585a838926b8/bindings/pydrake/visualization/meldis.py#L202)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

same as below -- need period (.), and move closing triple-quote to its own line.
</blockquote></details>

Done. Thanks.
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 191 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOqDjZENo1LVhtKCbR:-NBOvv6kBTdSUVytF7YF:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/e09f6b0fcf2b006fd65d40cd8cdc585a838926b8/bindings/pydrake/visualization/test/meldis_test.py#L191)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

End sentence with a period (.) .
</blockquote></details>

Done. Thanks.
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 191 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOqIi86iIMnc_D1H2z:-NBOwAFF8VQmiwjnlLys:bhxjq5r) ([raw file](https://github.com/robotlocomotion/drake/blob/e09f6b0fcf2b006fd65d40cd8cdc585a838926b8/bindings/pydrake/visualization/test/meldis_test.py#L191)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Typical python formatting for multiline docstrings is to put the closing triple-quote on a line by itself. See guidance from the famous style document [PEP 8](https://peps.python.org/pep-0008/#documentation-strings).
</blockquote></details>

I see. Thanks!
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 223 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOpkKP8rVNJt9K3_tR:-NBOwZi9EDp6jRPlWgz-:b-vrmwht) ([raw file](https://github.com/robotlocomotion/drake/blob/e09f6b0fcf2b006fd65d40cd8cdc585a838926b8/bindings/pydrake/visualization/test/meldis_test.py#L223)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit For readability, I might take these lines that construct the expected  `meshcat_path` and move them down to group them with the first assert below. As it is, they blend in with the code that builds the message.

Also, you may prefer modern python magic of [f strings](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals):

```
meshcat_path = f"/DRAKE_VIEWER/{message.robot_num}/{message.name}"
```

You don't have to convert to f strings, but you might like it. Try it and see!
</blockquote></details>

Done.  That is really neat!  (I did learn about it in LinkedInLearning but forgot to use it here.)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOoXvg-8jjCEQsJR1_:-NBOz55x8GmTldRs-8gU:b-ofpjio) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

@rpoyner-tri I also played around to see whether I can hack the unit test to show me the picture.  My failed attempts are:

1. `webbrowser.open(url=dut.meshcat.web_url(), new=1)`.  It opened the meshcat window, but I didn't see anything drawn.
2. Add `dut.serve_forever()` at the last line. It crashed.

I do have an interesting observation.  If I do this:
1. ` bazel run //tools:meldis -- -w` in a separate terminal.
2.  run the unit test `bazel run //bindings/pydrake/visualization:py/meldis_test` in another terminal.
then, I saw the picture from the first test (`def test_viewer_applet(self):`) which uses `acrobot.sdf`.


Then, it gave me an idea.  I removed all the other tests except deformable (`def test_deformable(self):`) and run the unit test `bazel run //bindings/pydrake/visualization:py/meldis_test` again.  Then, I can see the deformable tetrahedron from the unit test.


I do not completely understand why.  I'm guessing if I can tell `bazel` to run only one test in the python unit test, I'll be able to see the same thing without changing the source code at all.
</blockquote></details>

```
$  bazel run //bindings/pydrake/visualization:py/meldis_test -- --help
$  bazel run //bindings/pydrake/visualization:py/meldis_test -- TestMeldis.test_deformable
```

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848)* status: needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBOoXvg-8jjCEQsJR1_:-NBPF4YyArS_m7OokKAP:b-9755fn) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

```
$  bazel run //bindings/pydrake/visualization:py/meldis_test -- --help
$  bazel run //bindings/pydrake/visualization:py/meldis_test -- TestMeldis.test_deformable
```

</blockquote></details>

Thank you!

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBPFCJF13u3r5YILyib:-NBPFCJF13u3r5YILyic:b-oekco0) (no related file):*
CI has debug time out in `hardware_sim` that @jwnimmer-tri will fix it soon via #17864.  We'll test linux-focal-gcc-bazel-experimental-debug again after that.

___

**Review by DamrongGuoy — COMMENTED** [review]
+@ericcousineau-tri for platform review tomorrow (Thursday).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848#-:-NBPFuLjDOK51V-foUu6:b-1zseyx)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Comment by DamrongGuoy** [comment]
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

CI has debug time out in `hardware_sim` that @jwnimmer-tri will fix it soon via #17864.  We'll test linux-focal-gcc-bazel-experimental-debug again after that.
</blockquote></details>

@drake-jenkins-bot linux-focal-gcc-bazel-experimental-debug please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with small nits

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848#-:-NBSWeWz00ty-qPSzAIp:b-t7zhza)* status: 2 unresolved discussions (waiting on @DamrongGuoy)

___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 200 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBSWOlpDNh5b0voEz17:-NBSWOlpDNh5b0voEz18:b-y8tzi8) ([raw file](https://github.com/robotlocomotion/drake/blob/18aa920d35f2c94fbe566f376be989cf6d46f668/bindings/pydrake/visualization/test/meldis_test.py#L200)):*
> ```Python
>         # of a tetrahedron.
>         geom0 = lcmt_viewer_geometry_data()
>         geom0.type = 4
> ```

nit What is `type = 4`?

If this comes from an enum in LCM, can we use that field?
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 205 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBSWVWz6rWh0oJCJCNf:-NBSWVWz6rWh0oJCJCNg:bgf9ob5) ([raw file](https://github.com/robotlocomotion/drake/blob/18aa920d35f2c94fbe566f376be989cf6d46f668/bindings/pydrake/visualization/test/meldis_test.py#L205)):*
> ```Python
>         geom0.color = [0.9, 0.9, 0.9, 1.0]
>         geom0.string_data = "tetrahedron"
>         geom0.num_float_data = 26
> ```

nit For simplicity, why not put this in line below as `geom0.num_float_data = len(geom0.float_data)`?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848)* status: 2 unresolved discussions (waiting on @DamrongGuoy)

___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 200 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBSWOlpDNh5b0voEz17:-NBSWoR-DT0e-EjLlqGj:b10fxi0) ([raw file](https://github.com/robotlocomotion/drake/blob/18aa920d35f2c94fbe566f376be989cf6d46f668/bindings/pydrake/visualization/test/meldis_test.py#L200)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit What is `type = 4`?

If this comes from an enum in LCM, can we use that field?
</blockquote></details>

From code above, can you instead use `lcmt_viewer_geometry_data.MESH`?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848)* status: 3 unresolved discussions (waiting on @DamrongGuoy)

___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 202 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBSXOLn0duqS_idK4RZ:-NBSXOLo9V8G5FcrEDTb:b-w506v0) ([raw file](https://github.com/robotlocomotion/drake/blob/18aa920d35f2c94fbe566f376be989cf6d46f668/bindings/pydrake/visualization/test/meldis_test.py#L202)):*
> ```Python
>         geom0.type = 4
>         geom0.position = [0.0, 0.0, 0.0]
>         geom0.quaternion = [1.0, 0.0, 0.0, 0.0]
> ```

nit Quaternion coordinates without indication of ordering are scary.

Can you please denote with trailing comment, `# w, x, y, z`?
That, or you can do it as code:
```
q_wxyz = [1.0, 0.0, 0.0, 0.0]
geom0.quaternion = q_wxyz
```
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 202 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBSXcdI54Bp69LqheQr:-NBSXcdI54Bp69LqheQs:bg1jz7j) ([raw file](https://github.com/robotlocomotion/drake/blob/18aa920d35f2c94fbe566f376be989cf6d46f668/bindings/pydrake/visualization/test/meldis_test.py#L202)):*
> ```Python
>         geom0.type = 4
>         geom0.position = [0.0, 0.0, 0.0]
>         geom0.quaternion = [1.0, 0.0, 0.0, 0.0]
> ```

BTW Ah, this field in the lcmtype doesn't denote ordering :/

**Review by DamrongGuoy — COMMENTED** [review]
@ericcousineau-tri I appreciate your review by giving me the code.  Thanks!  Giving code is the best code reviewing.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17848#-:-NBStMWC5zgwONSjcIsJ:b-z07g6s)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 200 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBSWOlpDNh5b0voEz17:-NBSrTbYAT25uiduoa3I:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/18aa920d35f2c94fbe566f376be989cf6d46f668/bindings/pydrake/visualization/test/meldis_test.py#L200)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

From code above, can you instead use `lcmt_viewer_geometry_data.MESH`?
</blockquote></details>

Done. Thanks.
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 202 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBSXOLn0duqS_idK4RZ:-NBSrppt2FavdZmjwTq2:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/18aa920d35f2c94fbe566f376be989cf6d46f668/bindings/pydrake/visualization/test/meldis_test.py#L202)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Quaternion coordinates without indication of ordering are scary.

Can you please denote with trailing comment, `# w, x, y, z`?
That, or you can do it as code:
```
q_wxyz = [1.0, 0.0, 0.0, 0.0]
geom0.quaternion = q_wxyz
```
</blockquote></details>

Done. Thanks.
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 205 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17848#-NBSWVWz6rWh0oJCJCNf:-NBSs51XCPKywFSbQGOq:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/18aa920d35f2c94fbe566f376be989cf6d46f668/bindings/pydrake/visualization/test/meldis_test.py#L205)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For simplicity, why not put this in line below as `geom0.num_float_data = len(geom0.float_data)`?
</blockquote></details>

Done. Thanks.

**Comment by jwnimmer-tri** [comment]
https://github.com/RobotLocomotion/drake/pull/17853#issuecomment-1251221742

+(release notes: none) -(release notes: feature)

**Pull request merged**
