### PR TITLE
[setup] Switch to libclang-14 on Jammy

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates to https://github.com/RobotLocomotion/ros-drake-vendor/issues/2.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20732)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@BetsyMcPhail what's the easiest way to coordinate this PR with a CI provisioned image update (only Jammy changes)?

Do you want to manually deploy a temporary image that has `libclang-12-dev` and `libclang-14-dev` both installed (so that Production CI passes, as well as this PR)?  Then once this PR merges, you could drop 12.

Or, I could use unprovisioned jobs to get through code review, and then we concurrently could depoy a new image (with only 14, not 12) the same time as we merge this PR.

Or, something else?

**Review by BetsyMcPhail — COMMENTED** [review]
There's only one image that needs to be updated (Jammy provisioned), so temporary deploying both `libclang-12-dev` and `libclang-14-dev` seems to be the easiest way to go. I'll create and deploy the new image now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20732#-:-NnKIS-B8N-YxgKOPEVf:b-h4l8dc)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Sounds good, thanks!  Please "jenkins bot retest" this PR once that's deployed.

+@sammy-tri for both reviews per schedule, please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for platform stamp

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20732#-:-NnPQdBr4KN5TgzjhsbQ:b4xf2wm)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),BetsyMcPhail

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20732)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),BetsyMcPhail

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20732#-:-NnPR-fe5jIxpxwZD4yC:bnfp4nl)* status: LGTM missing from assignees sammy-tri(platform),BetsyMcPhail

**Review by rpoyner-tri — COMMENTED** [review]
Still are some crashy test failures.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20732#-:-NnPRC9D7TqZpPj0XP0v:b-mcyy66)* status: LGTM missing from assignees sammy-tri(platform),BetsyMcPhail

**Comment by jwnimmer-tri** [comment]
I think Jenkins seems happy.  It's only CDash having stale results which shows as broken.

**Pull request merged**
