### PR TITLE
Add unit test for buildifier's diagnostic user output

### LINKED ISSUE #7271: buildifier lint error reporting
I suspect that #7200 broke buildifier lint user error reporting?  Previously, in `-mode=check`, buildifier returned 0 but printed to stdout with errors, so we used non-empty stdout to indicate a problem and then tell the user how to fix it.  I suspect upstream changed the tool to `exit(4)` when fixes are needed, which our wrapper reports as a tool error, not a lint error.  Thus, we're no longer printing instructions for how users should fix `builfidier` lint problems.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #7271.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7360)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for all review please, per rotation.

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with minor BTW

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lint/test/buildifier_test.py, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7360#-Kxhk4XzlMw3VYH3Lx0B:-Kxhk4Y-iVzf1hyZ0eL8:b-a6c6th) ([raw file](https://github.com/robotlocomotion/drake/blob/12e9df5f8dd642832a8a40ff7f03ef9b101938c2/tools/lint/test/buildifier_test.py#L32)):*
> ```Python
>         return process.returncode, stdout
> 
>     def test_mode_check(self):
> ```

BTW Can a small test be added for ensuring that `-mode=fix` won't work in this environment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7360#-:-KxhkGinky6TQ6HWANhY:bgh44at)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/lint/buildifier.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7360#-Kxhp0A2zMMyForaYVnF:-Kxhp0A2zMMyForaYVnG:bg83bkl) ([raw file](https://github.com/robotlocomotion/drake/blob/12e9df5f8dd642832a8a40ff7f03ef9b101938c2/tools/lint/buildifier.py#L1)):*
> ```Python
> """Run Google's buildifier tool to fix, check, or fix-diff BUILD files.
> ```

BTW Should executables contain a shebang, per Python style guide?
http://drake.mit.edu/code_style_guide.html#additional-rules

---

*[tools/lint/test/buildifier_test.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7360#-KxhouchkuTSYYHsQzug:-KxhouchkuTSYYHsQzuh:bgiekue) ([raw file](https://github.com/robotlocomotion/drake/blob/12e9df5f8dd642832a8a40ff7f03ef9b101938c2/tools/lint/test/buildifier_test.py#L1)):*
> ```Python
> import os
> ```

BTW Should executables contain a shebang, per Python style guide?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7360)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/lint/buildifier.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7360#-Kxhp0A2zMMyForaYVnF:-Kxhr2hQVMLZg5t-7xTr:b-c8brh4) ([raw file](https://github.com/robotlocomotion/drake/blob/12e9df5f8dd642832a8a40ff7f03ef9b101938c2/tools/lint/buildifier.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Should executables contain a shebang, per Python style guide?
http://drake.mit.edu/code_style_guide.html#additional-rules
</blockquote></details>

This file is not executable:
```console
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ git checkout buildifier-unit-test
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ ls -l tools/lint/buildifier.py 
-rw-rw-r-- 1 jwnimmer jwnimmer 5129 Oct 30 11:19 tools/lint/buildifier.py
```

---

*[tools/lint/test/buildifier_test.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7360#-KxhouchkuTSYYHsQzug:-KxhvdWjwAkdRUKemFNi:b-i3r6m3) ([raw file](https://github.com/robotlocomotion/drake/blob/12e9df5f8dd642832a8a40ff7f03ef9b101938c2/tools/lint/test/buildifier_test.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Should executables contain a shebang, per Python style guide?
</blockquote></details>

Done.  I removed the executable mode bits from this file in git.

---

*[tools/lint/test/buildifier_test.py, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7360#-Kxhk4XzlMw3VYH3Lx0B:-Kxhtuu_7y3V9xZf1bzt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/12e9df5f8dd642832a8a40ff7f03ef9b101938c2/tools/lint/test/buildifier_test.py#L32)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can a small test be added for ensuring that `-mode=fix` won't work in this environment?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7360)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7360)*

**Pull request merged**
