### PR TITLE
[geometry] Removing the now unused contact_surface_from_level_set functionality

### LINKED ISSUE #14183: [hydroelastic] Remove `contact_surface_from_level_set.h`
In an early incarnation, `MultibodyPlant` code had implemented a representation and algorithm for computing a contact surface. It used a level set representation. The implementation has since been supplanted with all `ContactSurface` calculation taking place in `SceneGraph` infrastructure.

The code in `contact_surface_from_level_set.h` is no longer referred to anywhere and is located in an internal name space. It can simply be removed.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This was stop-gap code that has been supplanted by SceneGraph support and, more generally, this approach has issues; bad relative scales between level set representation and mesh can cause valid contact to not register valid ContactSurfaces.

This removes functionality wholly contained in an `internal` namespace; as such, no deprecation is required.

resolves #14183

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14184)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) +@ggould-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14184#-:-MJ7rQs96lNdCP9Z_OKe:b-jzmp36)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: do not merge) I'll merge this and edit the commit message upon merging to indicate the reason for no deprecation.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14184#-:-MJ8DVDWCxAMYEm7L_oC:b-ms1cjh)* status: LGTM missing from assignee ggould-tri(platform), labeled "do not merge" (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
Okay, I'll :lgtm: this and leave an issue below for the commit message.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14184#-:-MJ8PE8j5ptqDvNBpEQG:b-q8fnvu)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14184#-MJ8PJkfAyCy9IP61Qnf:-MJ8PJkfAyCy9IP61Qng:bb4451n) (no related file):*
minor:  Commit message should explain the reason this is not going through deprecation.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14184)* status: labeled "do not merge"

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14184#-MJ8PJkfAyCy9IP61Qnf:-MJ8f_22AP8ZmOOU1Qao:bb6un1j) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Commit message should explain the reason this is not going through deprecation.
</blockquote></details>

Done

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14184#-:-MJ8fdAS-gs_ddkcVcpX:b-b9fcpn)* status: labeled "do not merge"

**Pull request merged**
