### PR TITLE
Enable removal of subgraphs

### PR DESCRIPTION
**Pull request by wrangelvid**
Often we build very large and complicated graphs. Rather than having to rebuild it each to for a new start and goal configuration, we could make use of the existing graph by removing and creating a new subgraph and connecting it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006)

### CODE REVIEW

**Review by wrangelvid — COMMENTED** [review]
+@sadraddini for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-:-Nr8c-a-ESu-mcAtRHHu:b4li04k)* status: LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @wrangelvid)

**Review by sadraddini — COMMENTED** [review]
Thanks for doing this. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-:-NrAAnt6-_WVUh0Px5_4:b-sfbl4u)* status: 3 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 401 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrAB-ysEfMudFNzTpdV:-NrAB-ysEfMudFNzTpdW:bdx5c99) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d3ceaea2d8c8566d0e451f898296d75c8a9280a/planning/trajectory_optimization/gcs_trajectory_optimization.h#L401)):*
> ```objc
>   /** Remove a subgraph and all associated edges found in the subgraph and
>   to and from other subgraphs.
>   @pre The subgraph must be part of the graph.
> ```

nit The subgraph must have been created from a call to [AddRegions()](https://drake.mit.edu/doxygen_cxx/classdrake_1_1planning_1_1trajectory__optimization_1_1_gcs_trajectory_optimization.html#aff9544b6375a592b1b9bda5eb1149a6f "Creates a Subgraph with the given regions and indices.") on this object,
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 914 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrA9Ox29XCisN7fBHMl:-NrA9Ox29XCisN7fBHMm:b-dgg3pa) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d3ceaea2d8c8566d0e451f898296d75c8a9280a/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L914)):*
> ```cpp
>                                     return s.get() == &subgraph;
>                                   }),
>                    subgraphs_.end());
> ```

Don't you also need to remove elements from `std::vector<std::unique_ptr<EdgesBetweenSubgraphs>> subgraph_edges_`? 

I suggest having a unit test for them as well. 
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrAAPXkBDaMkjFnJdcH:-NrAAPXkBDaMkjFnJdcI:b2pfurq) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d3ceaea2d8c8566d0e451f898296d75c8a9280a/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L85)):*
> ```cpp
> 
>   // If we would like to find another path for a different goal, we can remove
>   // the target subgraph and add a new one while keeping the remaining graph.
> ```

This test would succeed even if you don't remove the old goal subgraph. I suggest having a test where you remove a subgraph that its regions should lie on the path toward a goal, and removing the subgraph either leads to in feasibility, or taking a different route.

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006)* status: 2 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 401 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrAB-ysEfMudFNzTpdV:-NrI53X294mayg0OMplo:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d3ceaea2d8c8566d0e451f898296d75c8a9280a/planning/trajectory_optimization/gcs_trajectory_optimization.h#L401)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit The subgraph must have been created from a call to [AddRegions()](https://drake.mit.edu/doxygen_cxx/classdrake_1_1planning_1_1trajectory__optimization_1_1_gcs_trajectory_optimization.html#aff9544b6375a592b1b9bda5eb1149a6f "Creates a Subgraph with the given regions and indices.") on this object,
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 914 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrA9Ox29XCisN7fBHMl:-NrI564d9yT-sirsLB7R:bva65kq) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d3ceaea2d8c8566d0e451f898296d75c8a9280a/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L914)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Don't you also need to remove elements from `std::vector<std::unique_ptr<EdgesBetweenSubgraphs>> subgraph_edges_`? 

I suggest having a unit test for them as well.
</blockquote></details>

Good catch! I'll get back to this, looks like I would have to return the internally stored list of subgraphs_ and subgraph_edges_
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrAAPXkBDaMkjFnJdcH:-NrI6Xsz81HsFDLFCFcP:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d3ceaea2d8c8566d0e451f898296d75c8a9280a/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L85)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

This test would succeed even if you don't remove the old goal subgraph. I suggest having a test where you remove a subgraph that its regions should lie on the path toward a goal, and removing the subgraph either leads to in feasibility, or taking a different route.
</blockquote></details>

Done.

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006)* status: 3 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 300 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrIlzkX8vNQfTGu9n-6:-NrIlzkX8vNQfTGu9n-7:b-nie1nf) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1bf52c785198a39f82e23760202ed3195f48406/planning/trajectory_optimization/gcs_trajectory_optimization.h#L300)):*
> ```objc
> 
>     GcsTrajectoryOptimization& traj_opt_;
>     const Subgraph& from_subgraph_;
> ```

What is the reason behind this change?
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 374 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrImXu14kt0wXjEPUzP:-NrImXu14kt0wXjEPUzQ:b-4wxbw7) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1bf52c785198a39f82e23760202ed3195f48406/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L374)):*
> ```cpp
>   // through the gravel. Thus we expect the number of segments in the trajectory
>   // to be 1 (one for the walking_regions).
>   EXPECT_EQ(rain_path_traj.get_number_of_segments(), 1);
> ```

nit you can use `GetSolutionPath` on the result and verify that none of the vertices belongs to the removed subgraph.

**Review by wrangelvid — COMMENTED** [review]
+@RussTedrake for platform review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-:-NrMk36iEWFpvcjCdYjO:b-ctes9b)* status: 2 unresolved discussions, LGTM missing from assignees sadraddini,RussTedrake(platform)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 300 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrIlzkX8vNQfTGu9n-6:-NrLvB4I51Ljf5VreFMA:b4jed8z) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1bf52c785198a39f82e23760202ed3195f48406/planning/trajectory_optimization/gcs_trajectory_optimization.h#L300)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

What is the reason behind this change?
</blockquote></details>

To remove an element in a subgraph_edges_, we need to know which subgraph the edges correspond to.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 914 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrA9Ox29XCisN7fBHMl:-NrMjiJKCXA7cvDs7XZ9:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d3ceaea2d8c8566d0e451f898296d75c8a9280a/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L914)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Good catch! I'll get back to this, looks like I would have to return the internally stored list of subgraphs_ and subgraph_edges_
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 374 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrImXu14kt0wXjEPUzP:-NrM1wtY05m2kCD-ilYb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1bf52c785198a39f82e23760202ed3195f48406/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L374)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit you can use `GetSolutionPath` on the result and verify that none of the vertices belongs to the removed subgraph.
</blockquote></details>

Done.

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006)* status: LGTM missing from assignees sadraddini,RussTedrake(platform)

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 374 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrImXu14kt0wXjEPUzP:-NrNPlk1Bajdm-qHpT1z:b5q9r9g) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1bf52c785198a39f82e23760202ed3195f48406/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L374)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where is it?

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006)* status: LGTM missing from assignees sadraddini,RussTedrake(platform)

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 374 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrImXu14kt0wXjEPUzP:-NrO0Sqd1pTJOdkxK_Nf:b-1f5qu9) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1bf52c785198a39f82e23760202ed3195f48406/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L374)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

where is it?
</blockquote></details>

I am checking that all the edges in solution correspond to the edges in the walking path, which is equivalent.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  a few minor requests below.

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-:-NrWSGTHDeUCM2uKY3Hp:bd2q76e)* status: 3 unresolved discussions, LGTM missing from assignee sadraddini

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 585 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrWQY6n0Nib0T6XtHQi:-NrWQY6n0Nib0T6XtHQj:b-ojr1kz) ([raw file](https://github.com/RobotLocomotion/drake/blob/51bbb4a53c7f146cd193aaba4ff0280611a377e3/planning/trajectory_optimization/gcs_trajectory_optimization.h#L585)):*
> ```objc
>   double EstimateComplexity() const;
> 
>   /** A getter to the subgraphs created by a call to AddRegions() */
> ```

nit: perhaps just "/** Returns a vector of all subgraphs. */"

(they weren't created by a single call to AddRegions)



_Code quote:_
```objc
/** A getter to the subgraphs created by a call to AddRegions() */
```
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 918 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrWR3EP7KJqeSIEYxUe:-NrWR3EP7KJqeSIEYxUf:b-npxjy6) ([raw file](https://github.com/RobotLocomotion/drake/blob/51bbb4a53c7f146cd193aaba4ff0280611a377e3/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L918)):*
> ```cpp
>                                  [&](const std::unique_ptr<Subgraph>& s) {
>                                    return s.get() == &subgraph;
>                                  }));
> ```

minor: The DRAKE_THROW_UNLESS is useful when the code is self-documenting.  This one would make for a very messy/difficult to read error message.  Can we instead do, e.g.
```
if (!std::any_of(...)) {
   throw std::runtime_error("Subgraph {} is not registered with `this`", subgraph.name());
}
```
or whatever the best human-readable error message is?
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 927 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrWRgxpETcIGbrC-Nyf:-NrWRgxpETcIGbrC-Nyg:b-yqzznw) ([raw file](https://github.com/RobotLocomotion/drake/blob/51bbb4a53c7f146cd193aaba4ff0280611a377e3/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L927)):*
> ```cpp
>   }
> 
>   // We still have to remove the edges between subgraphs objects.
> ```

btw -- i would have thought you'd want to remove the edges first, then remove the vertices.  clearly this can work, but perhaps the alternative order is more clean?  (and future proof?)

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006)* status: 1 unresolved discussion, LGTM missing from assignee sadraddini

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 585 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrWQY6n0Nib0T6XtHQi:-NrWr3Qt1P4jIPNLQHG7:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/51bbb4a53c7f146cd193aaba4ff0280611a377e3/planning/trajectory_optimization/gcs_trajectory_optimization.h#L585)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: perhaps just "/** Returns a vector of all subgraphs. */"

(they weren't created by a single call to AddRegions)
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 918 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrWR3EP7KJqeSIEYxUe:-NrWsMNU0Y5E05by2lYq:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/51bbb4a53c7f146cd193aaba4ff0280611a377e3/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L918)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

minor: The DRAKE_THROW_UNLESS is useful when the code is self-documenting.  This one would make for a very messy/difficult to read error message.  Can we instead do, e.g.
```
if (!std::any_of(...)) {
   throw std::runtime_error("Subgraph {} is not registered with `this`", subgraph.name());
}
```
or whatever the best human-readable error message is?
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 927 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrWRgxpETcIGbrC-Nyf:-NrWrfkk66nzqoZ42G4D:bj6uhye) ([raw file](https://github.com/RobotLocomotion/drake/blob/51bbb4a53c7f146cd193aaba4ff0280611a377e3/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L927)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i would have thought you'd want to remove the edges first, then remove the vertices.  clearly this can work, but perhaps the alternative order is more clean?  (and future proof?)
</blockquote></details>

I am not sure if I see what you mean. Removing the edges between subgraph objects, doesn't actually remove edges. That step is happening in RemoveVertex.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006)* status: 1 unresolved discussion, LGTM missing from assignee sadraddini

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 927 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrWRgxpETcIGbrC-Nyf:-NrX69Cx8NuLwnQzxIIe:b2ddjab) ([raw file](https://github.com/RobotLocomotion/drake/blob/51bbb4a53c7f146cd193aaba4ff0280611a377e3/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L927)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

I am not sure if I see what you mean. Removing the edges between subgraph objects, doesn't actually remove edges. That step is happening in RemoveVertex.
</blockquote></details>

The order of construction is AddRegions and then AddEdgesBetweenSubgraphs.  I think the deletion should reverse that order.  You can safely RemoveEdgesBetweenSubgraphs, then RemoveRegions.  (subgraphs make sense without the edges between them, but not the other way around?)

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006)* status: LGTM missing from assignee sadraddini

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 927 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrWRgxpETcIGbrC-Nyf:-NrXOct28KTLDTPaOggo:bdpj76m) ([raw file](https://github.com/RobotLocomotion/drake/blob/51bbb4a53c7f146cd193aaba4ff0280611a377e3/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L927)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The order of construction is AddRegions and then AddEdgesBetweenSubgraphs.  I think the deletion should reverse that order.  You can safely RemoveEdgesBetweenSubgraphs, then RemoveRegions.  (subgraphs make sense without the edges between them, but not the other way around?)
</blockquote></details>

Okay, I made removing the actual edges stored in the EdgesBetweenSubgraphs more explicit.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006)* status: LGTM missing from assignee sadraddini

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 927 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-NrWRgxpETcIGbrC-Nyf:-NrXU0UEC7ipUfOWJviA:b-6ooxmc) ([raw file](https://github.com/RobotLocomotion/drake/blob/51bbb4a53c7f146cd193aaba4ff0280611a377e3/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L927)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Okay, I made removing the actual edges stored in the EdgesBetweenSubgraphs more explicit.
</blockquote></details>

Thanks.  Simply moving the RemoveVertex down (as you have done) was my request.  But this works, too.

**Review by RussTedrake — COMMENTED** [review]
@sadraddini -- we're waiting on an LGTM from you.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-:-NrXUuAt5Gr5c-994CAl:b1qj4b0)* status: LGTM missing from assignee sadraddini

**Review by sadraddini — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21006#-:-NrXVGtw9UwAEi_mB7-m:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sadraddini,RussTedrake(platform)

**Pull request merged**
