### PR TITLE
math: Add symbolic support for orthonormal projection

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6631.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9338)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy and +@sherm1 for review please, in light of #6631.  If you think this is an improvement, then we can also bring in @mitiguy for additional review.

**Comment by DamrongGuoy** [comment]
___
*[math/rotation_matrix.h, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9338#-LLFp56l0JucMykDJe7y:-LLFp56l0JucMykDJe7z:b-zfu1dm) ([raw file](https://github.com/robotlocomotion/drake/blob/159dc387d3028c2a95a00e7c1e2eb664253cfbe5/math/rotation_matrix.h#L427)):*
> ```objc
>   template <typename S = T>
>   static typename std::enable_if<
>     !std::is_same<S, symbolic::Expression>::value,
> ```

Question.  Switching from `is_numeric<S>...>` to `!is_same<S, symbolic::Expresssion...>` will permit types like `std::complex`,  `AutoDiffScalar` and `adouble` in the future, correct?  Or they will need specializations too?

**Comment by DamrongGuoy** [comment]
I think it is a very nice improvement.  We should invite @mitiguy for review.
+@mitiguy  for feature review, please.

**Comment by DamrongGuoy** [comment]
___
*[math/rotation_matrix.h, line 445 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9338#-LLFr4Gi2KpvbG_vpOiE:-LLFr4Gi2KpvbG_vpOiF:b3l1xua) ([raw file](https://github.com/robotlocomotion/drake/blob/159dc387d3028c2a95a00e7c1e2eb664253cfbe5/math/rotation_matrix.h#L445)):*
> ```objc
>         M.unaryExpr([](const S& term) { return term.GetVariables(); })
>         .redux([](const auto& a, const auto& b) { return a + b; } );
>     // Return a rotation matrix and quality_factor where every scalar value is
> ```

BTW, inserting one empty line before this line would help me read the code easier. Well...it's just style.

**Comment by DamrongGuoy** [comment]
___
*[math/test/rotation_matrix_test.cc, line 492 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9338#-LLFrzlA02OgkPYyksVU:-LLFrzlA02OgkPYyksVV:b3zjyed) ([raw file](https://github.com/robotlocomotion/drake/blob/159dc387d3028c2a95a00e7c1e2eb664253cfbe5/math/test/rotation_matrix_test.cc#L492)):*
> ```cpp
>   EXPECT_NO_THROW(R.set(m_symbolic));
> 
>   // Set one of the matrix terms to a variable.  Still no throw.
> ```

Now we can orthogonaly normalized a symbolic matrix.  That is so cool!

**Comment by DamrongGuoy** [comment]
Done review. Only minor comments. :lgtm:

**Comment by jwnimmer-tri** [comment]
I have a counter-proposal (to myself) that I will also PR.  Stay tuned.

**Comment by jwnimmer-tri** [comment]
Closing in favor of #9349.

**Pull request closed without merging**
