### PR TITLE
Remove depth sensor demo given that there is a unittest.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This addresses Issue #6202 by removing the demo.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6203)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@liangfok for feature review, please.
+@sammy-tri for platform review, please.

(Please let me know if you think it may be better to fix the existing test.)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6203#-:-KlPJWZSkrdOQVLLdSB_:b3598eu)*

**Comment by sammy-tri** [comment]
:lgtm: in that this is consistent with the commentary in #6202 and doesn't seem to present any platform issues.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6203#-:-KlPZyS3hTHp5ye72Fjq:b-18cj97)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6203)*

**Comment by liangfok** [comment]
:lgtm: Thanks for doing this!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6203#-:-KlQ9ieBDouNQKOt1BJy:b-pt8m11)*

**Pull request merged**
