### PR TITLE
Import cpplint

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Copy `cpplint.py` from the google_styleguide external into drake proper. Besides making maintenance easier (e.g. considering we are using a private fork at the moment), this will eventually make it possible for the CI cpplint build to not need to check out or actually "build" anything besides the drake repository itself, which will both simplify that "build" significantly, and remove the need for us to introduce hacks into the build system to support a less-than-minimal build for the sake of the CI cpplint "build".

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3242)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3242#-:-KPxa2HlAo8bYrinqQFp:bnfp4nl)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3242)*

**Comment by jwnimmer-tri** [comment]
Disagree.  I'm stuck in meetings but will try to respond by tomorrow.

**Comment by jwnimmer-tri** [comment]
Quick version;
1. The files of interest are 0.5 MB (cpplint and its unittest).  Repeatedly revving those in Drake will be expensive.
2. The cpplint fixes and customizations should be shared (shareable) with a wider audience within RobotLocomotion and TRI.  All projects in the family should share a cpplint; Drake shouldn't have a one-off fork.
3. Having a project family fork provides a cleaner workflow for upstreaming our changes.

**Comment by mwoehlke-kitware** [comment]
Okay, will try to find a reasonable way to make the CI script pull the submodule without having to configure and build the superbuild.

**Pull request closed without merging**
