### PR TITLE
Remove MATLAB examples misc

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6369.

This removes the top-level canonical examples and tests (not a subfolder).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6379)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.
+(status: do not merge) until I've assigned additional review.

**Comment by jwnimmer-tri** [comment]
@RussTedrake ping, anything I can do to help unblock this?

**Comment by RussTedrake** [comment]
Just missed it.  :lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6379#-:-KnGOiy5PHNFaywyJdeE:buq0hcp)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.

**Comment by ggould-tri** [comment]
Pleasantly straightforward. :lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6379#-:-KnK1qpitInNgeWAeZPq:bfb8t6v)*

**Pull request merged**
