### PR TITLE
[doc] Update build cop play book to check github pages

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16600)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16600#-:-MvzGjaS-OtHEXKbIud5:b-51ktqu)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both -- this looks correct.  However, note that I'm not going to be a good reviewer to see if it makes sense to anyone other than myself.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16600#-:-MvzHGJUBR5JgBX4l6bV:b-qh92bp)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[doc/_pages/buildcop.md, line 271 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16600#-MvzH6EJBrtMrkm6pJB2:-MvzH6EJBrtMrkm6pJB3:bqlq50o) ([raw file](https://github.com/robotlocomotion/drake/blob/387f75c021a19458f9ec88237bfcd22ff93c5c2d/doc/_pages/buildcop.md#L271)):*
> ```Markdown
> channel on Slack, ensuring that `@betsymcphail` is mentioned in the message.
> 
> ## Documentation Repo Failures.
> ```

nit Usually we don't use punctuation in headings



_Code quote:_
```Markdown
.
```
___
*[doc/_pages/buildcop.md, line 274 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16600#-MvzHC2r7B8jmn_naTfX:-MvzHC2r7B8jmn_naTfY:b-iu0b6f) ([raw file](https://github.com/robotlocomotion/drake/blob/387f75c021a19458f9ec88237bfcd22ff93c5c2d/doc/_pages/buildcop.md#L274)):*
> ```Markdown
> If the [automatically generated documentation repo](https://github.com/RobotLocomotion/RobotLocomotion.github.io/commits/master)
> fails, post in [DrakeDevelopers Slack channel #buildcop](https://drakedevelopers.slack.com/messages/buildcop/details/),
> and try to locate the offensive Drake commit. Each commit in the documentation repo is associated with a matching Drake commit.
> ```

nit Missing a final newline.

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for some additional vetting. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16600#-:-MvzHlDE4Om_m6ctNGI5:b-2av354)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[doc/_pages/buildcop.md, line 271 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16600#-MvzH6EJBrtMrkm6pJB2:-MvzI3di9sAvBNluJiVb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/387f75c021a19458f9ec88237bfcd22ff93c5c2d/doc/_pages/buildcop.md#L271)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Usually we don't use punctuation in headings
</blockquote></details>

Done.
___
*[doc/_pages/buildcop.md, line 274 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16600#-MvzHC2r7B8jmn_naTfX:-MvzI4a76jwOxTVzZuaB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/387f75c021a19458f9ec88237bfcd22ff93c5c2d/doc/_pages/buildcop.md#L274)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing a final newline.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16600)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16600)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16600#-:-MvzIdPv9AZSibaUTRDO:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
