### PR TITLE
Move into third_party two private dependencies

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

The `tinydir` and `spruce` components are not part of Drake's API (they are only used by our cc files, not our header files). This PR makes a few changes to how they are handled:
- moves their sources from `/drake/thirdParty` to just `/third_party`;
- removes their header files from Drake's installed package;
  - they are already statically linked into `libdrake.so`;
- adds their license files to Drake's installed package.

This PR also contains a few commits to tidy up the `/third_party` documentation and related nits.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7232)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review please, following up on #7219, if you're up for it?

/cc @jamiesnape FYI on these changes.  If you want to try to finish #7198 first we can try to coordinate.

**Comment by jamiesnape** [comment]
I will work around this, so you can merge as soon as the reviews are complete.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7232#-:-KwB7TF2FJPk2R4HdH3P:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per rotation, please.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Platform

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7232#-:-KwBkjwSqP4yO3oEMHNF:b-uap05a)*

**Pull request merged**
