### PR TITLE
add python bindings for signal logger

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7759)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri  for feature review, please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7759#-:-L2rzJhWhUxPDdUcllZj:bqgjn1a)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/test/general_test.py, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7759#-L2v_d-PYsAQq0ZcKKBM:-L2v_d-PYsAQq0ZcKKBN:bdggf8b) ([raw file](https://github.com/robotlocomotion/drake/blob/76274203ebdd49386ac0a452bf22887d4e5ac9d3/bindings/pydrake/systems/test/general_test.py#L144)):*
> ```Python
>         # source and an integrator.
>         builder = DiagramBuilder()
>         kValue = 2.4
> ```

BTW For pure-Python code, I think this can be `value = 2.4` rather than `kValue` (same for `kSize`).

PEP8 only defines naming conventions for module-level constants:
https://www.python.org/dev/peps/pep-0008/#constants

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7759#-:-L2vinlrkRaowlxKGwl1:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@ggould-tri for platform review

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7759#-:-L30uI6HKjOYrF3tuDN1:b-gbk9vg)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7759#-:-L33UkGbx2SRiuy_VT1o:bnfp4nl)*

**Pull request merged**
