### PR TITLE
Fix trajectory optimization for systems with parameters; add simple car example

### PR DESCRIPTION
**Pull request by RussTedrake**
also makes a small but major performance / functional improvement to snopt and ipopt solvers' use of autodiff.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5666)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@soonho-tri -- looks like the compiler issue I showed you yesterday is a distinction between xenial-clang and other compilers?

**Comment by soonho-tri** [comment]
@russtedrake , I'll check that as soon as I get to the office. 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-:-KgU0cdYoBpHaDoSaJAU:b-q62929)*

**Comment by soonho-tri** [comment]
I can reproduce the problem on my mac. I'm investigating the issue.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-:-KgUQl35nIv469Sv2kiQ:b-2y6j60)*

**Comment by soonho-tri** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-KgUZkqZTPv4PsUNWfaY:-KgUZkqZTPv4PsUNWfaZ:badlkds) ([raw file](https://github.com/robotlocomotion/drake/blob/868c4838ea0b0c5e5392607d2b18a1b65a24394b/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L120)):*
> ```objc
>   /// Adds support for passing in a (scalar) matrix Expression, which is a
>   /// common output of most symbolic linear algebra operations.
>   /*
> ```

@russtedrake , we have a workaround:
```c++
  template <typename Derived>
  void AddRunningCost(const Eigen::MatrixBase<Derived>& g) {
    DRAKE_DEMAND(g.rows() == 1 && g.cols() == 1);
    DoAddRunningCost(g(0, 0));
  }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by Lucy-tri** [comment]
Reviewed 2 of 9 files at r1.
Review status: 2 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-:-KgZIAcUkvpNFJm5T2b0:bltox9h)*

**Comment by RussTedrake** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-KgUZkqZTPv4PsUNWfaY:-KgZIFfVAypvQvxagyY-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/868c4838ea0b0c5e5392607d2b18a1b65a24394b/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L120)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@russtedrake , we have a workaround:
```c++
  template <typename Derived>
  void AddRunningCost(const Eigen::MatrixBase<Derived>& g) {
    DRAKE_DEMAND(g.rows() == 1 && g.cols() == 1);
    DoAddRunningCost(g(0, 0));
  }
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sherm1 for platform review please.

---

Reviewed 4 of 9 files at r1, 2 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_ScatIxVDCTX9ZgS0:-Kg_ScatIxVDCTX9ZgS1:byowov) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L61)):*
> ```cpp
>   // Cost function: int_0^T [ u'u ] dt
>   prog.AddRunningCost(prog.input().transpose() * prog.input());
> ```

BTW, I find sometimes I need to set a lower bound and/or upper bound on each individual time interval, to avoid the time interval goes too small, or too big (large integration error).

---

*[drake/solvers/snopt_solver.cc, line 280 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_QYcpFKGgo_pNhDRC:-Kg_QYcpFKGgo_pNhDRD:bz8weq9) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/solvers/snopt_solver.cc#L280)):*
> ```cpp
>       size_t vj_index =
>           current_problem->FindDecisionVariableIndex(binding.variables()(j));
>       G[vj_index] += static_cast<snopt::doublereal>(ty(0).derivatives()(j));
> ```

Hmm, using `vj_index` as the index for `G` suggests that we are assuming that the cost has dense gradient. Also by https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/snopt_solver.cc#L422~L425, we are assuming dense gradient for the cost function. @sammy-tri why we implemented the dense gradient in the first place? Could you shed some light on this? Thanks!

This is outside of the scope of this PR, but I would like to know if dense gradient for cost function is a deliberate choice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-:-Kg_TMaCdc4781Ux_lWw:bozh2sc)*

**Comment by sherm1** [comment]
Platform: needs a hand-merge with master. :lgtm: pending merge & some BTWs, ptal.

---

Reviewed 4 of 9 files at r1, 2 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[drake/automotive/BUILD, line 762 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_Zp1o3qB57f9_WuKv:-Kg_Zp1o3qB57f9_WuKw:b-4vlzpb) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/BUILD#L762)):*
> ```Python
>         "//drake/common:eigen_matrix_compare",
>         "//drake/systems/trajectory_optimization:direct_collocation",
>         "//drake/lcm:lcm_call_matlab"
> ```

BTW alphabetize

---

*[drake/automotive/simple_car.cc, line 171 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_Zyj4euD3UZ1il2yk:-Kg_Zyj4euD3UZ1il2yl:bvh4fky) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/simple_car.cc#L171)):*
> ```cpp
>   // Sanity check our input.
>   DRAKE_DEMAND(abs(input.steering_angle()) < M_PI);
>   // TODO(jwnummer): Update DrivingCommand to a single value for throttle/brake
> ```

BTW typo: jwnimmer. Also, Jeremy's PR may already have landed in which case this should go away after merge.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_b5yxJNKhH_NM9app:-Kg_b5yxJNKhH_NM9apq:bppn3tn) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L16)):*
> ```cpp
> namespace {
> 
> GTEST_TEST(TrajectoryOptimizationTest, SimpleCarDircolTest) {
> ```

BTW, a comment explaining what is being tested would be helpful here.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 35 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_bjKgLm0o2r5NZUkc:-Kg_bjKhXhpe83D7xLiU:b7tyyk7) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L35)):*
> ```cpp
>   const int kNumTimeSamples = 10;
>   const double kTrajectoryTimeLowerBound = 0.8 * initial_duration,
>                kTrajectoryTimeUpperBound = 1.2 * initial_duration;
> ```

BTW why is the trajectory only part of the duration? (A comment here would help.)

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 43 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_c0gSwz_cC4YOsQbs:-Kg_c0gSwz_cC4YOsQbt:b-4soh3t) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L43)):*
> ```cpp
>   // Input limits (note that the steering limit imposed by SimpleCar is larger).
>   DrivingCommand<double> lower_limit, upper_limit;
>   lower_limit.set_steering_angle(-M_PI_2);
> ```

BTW wow I guess this car is easy to park!

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_cKC0nMKoByVYI-U3:-Kg_cKC0nMKoByVYI-U4:bv3sxkx) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L49)):*
> ```cpp
>   upper_limit.set_throttle(std::numeric_limits<double>::infinity());
>   upper_limit.set_brake(std::numeric_limits<double>::infinity());
>   prog.AddInputBounds(lower_limit.get_value(), upper_limit.get_value());
> ```

BTW may be some interaction here with @jwnimmer-tri's change today from (throttle,brake) to just acceleration.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_d4jToMADGQOQSrOR:-Kg_d4jToMADGQOQSrOS:bk47p1e) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L59)):*
> ```cpp
>                            xf.get_value().array());
> 
>   // Cost function: int_0^T [ u'u ] dt
> ```

BTW, Unicode ∫ is available if you're interested.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 62 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_eEeTLCLEx91G7LQf:-Kg_eEeTLCLEx91G7LQg:b-immkla) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L62)):*
> ```cpp
>   prog.AddRunningCost(prog.input().transpose() * prog.input());
> 
>   auto initial_state_trajectory = PiecewisePolynomial<double>::FirstOrderHold(
> ```

BTW, comment here: "set initial guess to a simple ramp" (I think)

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 71 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_ecduMBk_ZEIzzGrE:-Kg_ecduMBk_ZEIzzGrF:bbkrrtb) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L71)):*
> ```cpp
>   EXPECT_EQ(result, solvers::SolutionResult::kSolutionFound);
> 
>   // Plot the solution.
> ```

BTW this has to be checked by hand. Is there any hope for a test more precise than "solution found"? If not, it would still be helpful to have a comment here saying what the human-in-the-loop should expect to see in the plot. A link to an explanation as to how to enable LcmCallMatlab to work would also be good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-:-Kg_ZJxO2dcuvq2L1iBf:bql7gtk)*

**Comment by jwnimmer-tri** [comment]
:car: approved

---

Reviewed 1 of 3 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[drake/automotive/simple_car.cc, line 208 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kga2oLmWzYw-n8Ukp6M:-Kga2oLnCf5k9hNNpU40:b-10eumj) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d8f3e200b555e001f7b106d15650f3836515b9/drake/automotive/simple_car.cc#L208)):*
> ```cpp
>     const systems::InputPortDescriptor<T>& descriptor) const {
>   return new DrivingCommand<T>();
> }
> ```

The `this->DeclareVectorInputPort(DrivingCommand<T>());` in the constructor means that this override should not be necessary, I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-:-Kga4A7mJquop3pnl0Cd:b-wrjbb8)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_ScatIxVDCTX9ZgS0:-KgbFs82bZrOhUa7Nbil:bvr9zyj) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L61)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, I find sometimes I need to set a lower bound and/or upper bound on each individual time interval, to avoid the time interval goes too small, or too big (large integration error).
</blockquote></details>

I realize that we have the constraint, that the time intervals are all equal. So retract the previous comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by RussTedrake** [comment]
Review status: 5 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/BUILD, line 762 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_Zp1o3qB57f9_WuKv:-Kg_sdzK_yzZYGq-ttA1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/BUILD#L762)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW alphabetize
</blockquote></details>

Done.

---

*[drake/automotive/simple_car.cc, line 171 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_Zyj4euD3UZ1il2yk:-Kg_sfh_2CRgT408fm5F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/simple_car.cc#L171)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW typo: jwnimmer. Also, Jeremy's PR may already have landed in which case this should go away after merge.
</blockquote></details>

Done.

---

*[drake/automotive/simple_car.cc, line 208 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kga2oLmWzYw-n8Ukp6M:-Kgd0cXgU_oT_vxx78DH:b2fbae3) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d8f3e200b555e001f7b106d15650f3836515b9/drake/automotive/simple_car.cc#L208)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `this->DeclareVectorInputPort(DrivingCommand<T>());` in the constructor means that this override should not be necessary, I think?
</blockquote></details>

good catch.  done.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_b5yxJNKhH_NM9app:-Kg_tAjpViqiuW637Wit:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, a comment explaining what is being tested would be helpful here.
</blockquote></details>

Done.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 35 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_bjKgLm0o2r5NZUkc:-Kg_tOQJYhNjh2kM3eO4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why is the trajectory only part of the duration? (A comment here would help.)
</blockquote></details>

Done.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_cKC0nMKoByVYI-U3:-Kgd0k6NsA3nkJhgvetq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW may be some interaction here with @jwnimmer-tri's change today from (throttle,brake) to just acceleration.
</blockquote></details>

Done.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_ScatIxVDCTX9ZgS0:-Kgd2TKrjd25NkIw3e0F:b-2hlxi4) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L61)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I realize that we have the constraint, that the time intervals are all equal. So retract the previous comment.
</blockquote></details>

actually, we did not have that constraint.  i've added it.  (the plots suggested this was not a problem, but I agree it's more robust to have it)

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 62 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_eEeTLCLEx91G7LQf:-Kgd19LZGQ56vTrAW7FO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L62)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, comment here: "set initial guess to a simple ramp" (I think)
</blockquote></details>

Done.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 71 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_ecduMBk_ZEIzzGrE:-Kgd6fs1TAWBo8S7_nAN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L71)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this has to be checked by hand. Is there any hope for a test more precise than "solution found"? If not, it would still be helpful to have a comment here saying what the human-in-the-loop should expect to see in the plot. A link to an explanation as to how to enable LcmCallMatlab to work would also be good.
</blockquote></details>

Done.

---

*[drake/solvers/snopt_solver.cc, line 280 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_QYcpFKGgo_pNhDRC:-Kgd4kNmYMvcIDPNl0mm:b-caedwj) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/solvers/snopt_solver.cc#L280)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Hmm, using `vj_index` as the index for `G` suggests that we are assuming that the cost has dense gradient. Also by https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/snopt_solver.cc#L422~L425, we are assuming dense gradient for the cost function. @sammy-tri why we implemented the dense gradient in the first place? Could you shed some light on this? Thanks!

This is outside of the scope of this PR, but I would like to know if dense gradient for cost function is a deliberate choice.
</blockquote></details>

i agree.  and we should be able to do much better in some cases, but I don't think the gradient sparsity is supported in the constraint classes yet.  can you add a TODO about it?

note that the change I've made here is already a huge improvement... we were passing around an autodiff with derivatives allocated for every variable in the mathematicalprogram, instead of autodiff that was just the size relevant to this cost/constraint?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 5 files at r5.
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by hongkai-dai** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/snopt_solver.cc, line 280 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_QYcpFKGgo_pNhDRC:-KgeaQ42yRv_ju2er81i:b-oy7q26) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/solvers/snopt_solver.cc#L280)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i agree.  and we should be able to do much better in some cases, but I don't think the gradient sparsity is supported in the constraint classes yet.  can you add a TODO about it?

note that the change I've made here is already a huge improvement... we were passing around an autodiff with derivatives allocated for every variable in the mathematicalprogram, instead of autodiff that was just the size relevant to this cost/constraint?
</blockquote></details>

I just filed #5693 . Thanks for using the autodiff, whose gradient only depends on the decision variables in the cost/constraint.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by sherm1** [comment]
Reviewed 1 of 3 files at r4, 4 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by jwnimmer-tri** [comment]
:lgtm: full review.

---

Reviewed 2 of 9 files at r1, 1 of 5 files at r5, 8 of 9 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 85 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kgk35TJ0GYI59o4nIu2:-Kgk35TJ0GYI59o4nIu3:b-85gqen) ([raw file](https://github.com/robotlocomotion/drake/blob/96dd88076956e0a36fec8596da209235a0ea915b/drake/automotive/test/trajectory_optimization_test.cc#L85)):*
> ```cpp
>                                                           // Ipopt for this
>                                                           // example.
>   else
> ```

BTW Multi-line if-else bodies require curly braces per cppguide.

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.cc, line 92 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kgk47R2vWkRqmcYFL2B:-Kgk47R3XplS1dYGpRbz:b-8f1ivn) ([raw file](https://github.com/robotlocomotion/drake/blob/96dd88076956e0a36fec8596da209235a0ea915b/drake/systems/trajectory_optimization/direct_collocation_constraint.cc#L92)):*
> ```cpp
>   context_->SetTimeStateAndParametersFrom(context);
>   // Set derivatives of all parameters in the context to zero (but with the
>   // correct size).
> ```

BTW The autodiff sizing seems like an important bugfix.  Is there a unit test that prevents it from regressing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-:-Kgk4KsZGKxU5g92OBY_:be7wxf8)*

**Comment by RussTedrake** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 85 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kgk35TJ0GYI59o4nIu2:-KgkLOgVewIF6BfM3wUf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/96dd88076956e0a36fec8596da209235a0ea915b/drake/automotive/test/trajectory_optimization_test.cc#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Multi-line if-else bodies require curly braces per cppguide.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.cc, line 92 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kgk47R2vWkRqmcYFL2B:-KgkENgfNUIpNu1uhVaK:b-xz9ha7) ([raw file](https://github.com/robotlocomotion/drake/blob/96dd88076956e0a36fec8596da209235a0ea915b/drake/systems/trajectory_optimization/direct_collocation_constraint.cc#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The autodiff sizing seems like an important bugfix.  Is there a unit test that prevents it from regressing?
</blockquote></details>

Yes -- if I can ever get this PR to land.  ;-)  The simple_car trajectory optimization will fail if the autodiff derivs are different sizes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.cc, line 92 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kgk47R2vWkRqmcYFL2B:-Kgk_xDaZuBGCCCWoLWO:bpab23b) ([raw file](https://github.com/robotlocomotion/drake/blob/96dd88076956e0a36fec8596da209235a0ea915b/drake/systems/trajectory_optimization/direct_collocation_constraint.cc#L92)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Yes -- if I can ever get this PR to land.  ;-)  The simple_car trajectory optimization will fail if the autodiff derivs are different sizes.
</blockquote></details>

The standard rules of engagement are that a unit test in the same folder (+ `test/`) covers the code; application uses are not good enough  (e.g., we might move `automotive` out of tree, etc.).  If that happens in a follow-up PR, that's okay by me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/automotive/test/trajectory_optimization_test.cc, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5666#-Kg_ScatIxVDCTX9ZgS0:-KglwWODieVywBp3XXIy:b-s3hadk) ([raw file](https://github.com/robotlocomotion/drake/blob/d6c89825b97df0d14ea3500fe5ed7d64ef8f0144/drake/automotive/test/trajectory_optimization_test.cc#L61)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

actually, we did not have that constraint.  i've added it.  (the plots suggested this was not a problem, but I agree it's more robust to have it)
</blockquote></details>

We have the constraint `h[i+1] = h[i]` in https://github.com/RobotLocomotion/drake/blob/master/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L49~L51. Why we decide to impose this constraint?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5666)*

**Pull request merged**
