### PR TITLE
examples: Fully port monte carlo acrobot and add a demo program

### PR DESCRIPTION
**Pull request by ggould-tri**
This PR brings the full acrobot monte carlo example from downstream into Drake.
In addition it adds a simple demonstration program, since the downstream code that uses this example is not ported.

Co-authored-by: Jeremy Nimmer <jeremy.nimmer@tri.global>
Co-authored-by: Andrés K. Valenzuela <andres.valenzuela@tri.global>
Co-authored-by: Eric Cousineau <eric.cousineau@tri.global>
Co-authored-by: Sam Creasey <sam.creasey@tri.global>

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
-(status: do not review) 
+(status: commits are properly curated)
+(priority: low) 
+@jwnimmer-tri 

This PR consists of three dev commits, each of which passes tests.
 * The first commit is a verbatim copy of every non-batch acrobot monte carlo file from anzu.  There is no new code here, just verbatim copies.
 * The second commit handles the renaming, build rules, and superficial checklisting to make this work with Drake.  These are new diffs.
 * The third commit adds a demonstration program to actually run the monte carlo and metrics code, so that this example is actually meaningful.  This is new code.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478#-:-MPA3fTAA25_sNNnqmSb:by4eqtz)* status: LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
Trivial comment so that reviewable will not mark this "stalled"

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478#-:-MQDWk_e8b8Bb_RNjyKs:b67bwrb)* status: LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
(Checkpoint as I begin review.)

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478#-:-MQE-ymKCWqSuTepMCwb:b-c9t2ee)* status: LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint r2.

> Reviewed 8 of 8 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478#-:-MQE7W_ZAzEgxU94IUYt:b-awxamd)* status: 13 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @ggould-tri and @jwnimmer-tri)

___
*[examples/acrobot/dev/acrobot_io.py, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE1PU33AINSuzbYgU1:-MQE1PU59rCBwk2N_5dG:b-mpd7mo) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/acrobot_io.py#L12)):*
> ```Python
>     may only be omitted when the file contains a single scenario.
>     """
>     data = yaml_load(filename=filename, data=data)
> ```

This (in r2 patch) reuse of `data` to be both a str (argument) and a dict (after parsing the str) will be confusing to a naive reader.  The extant "scenarios = ..." in r1 seemed both better, and less churn.
___
*[examples/acrobot/dev/acrobot_io.py, line 46 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE2DPV0s6XRbv1-OoM:-MQE2DPV0s6XRbv1-OoN:b-i0wriu) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/acrobot_io.py#L46)):*
> ```Python
>     `yaml_load`) in order to use `yaml.CLoader`, which greatly improves
>     performance, but cannot be used for all the cases supported by
>     yaml_load."""
> ```

nit "place the closing quotes on a line by themselves"
-- https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings
___
*[examples/acrobot/dev/acrobot_io.py, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE2RaR9jIhKrwZcr5p:-MQE2RaS9dVqpyWqdKi2:b-yv20of) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/acrobot_io.py#L62)):*
> ```Python
>     """Given an acrobot output `x_tape`, returns a yaml-formatter str for it.
>     """
>     return yaml.dump({"x_tape": x_tape.tolist()})
> ```

nit I'm not sure why this `yaml.dump` to `yaml_dump` change is staged in the third commit; other changes to use `yaml.dump` in this file were staged in the second commit.
___
*[examples/acrobot/dev/BUILD.bazel, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE7G3m4d4WOYtHsPKr:-MQE7G3m4d4WOYtHsPKs:b-fzejmy) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L17)):*
> ```Starlark
> load("//tools/lint:lint.bzl", "add_lint_tests")
> 
> # This our public python package, i.e., our py_library with everything
> ```

I think this example should _always_ remain private (i.e., nobody should be able to import it; we're not going to be installing it).  As such, this target serves no purpose and should disappear.
___
*[examples/acrobot/dev/BUILD.bazel, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE7m97Bg264fgyB-8c:-MQE7m98BJqumeQNrDT7:b9glqzr) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L41)):*
> ```Starlark
>     name = "acrobot_io",
>     srcs = ["acrobot_io.py"],
>     deps = [
> ```

nit Missing deps on `:module_py` -- all libraries in this module need to deps on module_py, to get the checked-in `__init__.py` instead of the auto-generated one.  (Having a commited-but-ignored file is misleading.)

Alternatively, punt the committed one, since it's empty anyway.
___
*[examples/acrobot/dev/BUILD.bazel, line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE4UVo09-9YAH5OpKu:-MQE4UVo09-9YAH5OpKv:b-ec07hv) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L49)):*
> ```Starlark
>     name = "metrics",
>     srcs = ["metrics.py"],
> )
> ```

nit Missing deps on `:module_py` -- all libraries in this module need to deps on module_py, to get the checked-in `__init__.py` instead of the auto-generated one.
___
*[examples/acrobot/dev/BUILD.bazel, line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE7kOQBIC3I5gdmJcC:-MQE7kOQBIC3I5gdmJcD:b-ec07hv) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L55)):*
> ```Starlark
>     name = "spong_sim_lib_py",
>     srcs = ["spong_sim.py"],
>     deps = [
> ```

nit Missing deps on `:module_py` -- all libraries in this module need to deps on module_py, to get the checked-in `__init__.py` instead of the auto-generated one.
___
*[examples/acrobot/dev/BUILD.bazel, line 65 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE7-RL9T7JdrxHEequ:-MQE7-RL9T7JdrxHEeqv:b-yozz5h) ([raw file](https://github.com/robotlocomotion/drake/blob/4c1f387b15f49bf4332c6a0fc72213f24c309167/examples/acrobot/dev/BUILD.bazel#L65)):*
> ```Starlark
>     deps = [
>         ":acrobot_io",
>         "//bindings/pydrake",
> ```

nit The test code says "from pydrake.common import FindResourceOrThrow", so this deps on `//bindings/pydrake` is still required.
___
*[examples/acrobot/dev/BUILD.bazel, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE5FRK-FFMAss_03Uh:-MQE5FRL5vo1ljqvpKPZ:b-9w113v) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L92)):*
> ```Starlark
> # === test/ ===
> 
> drake_py_test(
> ```

I'm not clear on why `drake_py_unittest` is no longer applicable for this target.  To my understanding, it seems like the perfect fit, and we should remove the dunder-text from the test file.  The default should be `drake_py_unittest`, any uses of `drake_py_test` directly should be few and far between, for oddball situations only.  Basic `def test_foo(self)` stuff should use `drake_py_unittest.
___
*[examples/acrobot/dev/BUILD.bazel, line 104 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE6PtYEU7qp6RDnV8N:-MQE6PtYEU7qp6RDnV8O:bozm54c) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L104)):*
> ```Starlark
> )
> 
> drake_py_test(
> ```

Ditto -- why not `drake_py_unittest` and drop the dunder-text?
___
*[examples/acrobot/dev/BUILD.bazel, line 112 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE6lwPEu-T3U1zDkwM:-MQE6lwPEu-T3U1zDkwN:bozm54c) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L112)):*
> ```Starlark
> )
> 
> drake_py_test(
> ```

Ditto -- why not `drake_py_unittest` and drop the dunder-text?
___
*[examples/acrobot/dev/BUILD.bazel, line 129 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE752J5-O4GXLEe8AL:-MQE752J5-O4GXLEe8AM:b7i2p1l) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L129)):*
> ```Starlark
>     ],
>     main = "test/spong_sim_main_test.py",
>     deps = [
> ```

nit The test code says "from pydrake.common import FindResourceOrThrow", so an explicit deps on `//bindings/pydrake` should appear here.
___
*[examples/acrobot/dev/spong_sim.cc, line 160 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE2lNn2L6T2OH1atu9:-MQE2lNn2L6T2OH1atuA:bs31yoq) ([raw file](https://github.com/robotlocomotion/drake/blob/4c1f387b15f49bf4332c6a0fc72213f24c309167/examples/acrobot/dev/spong_sim.cc#L160)):*
> ```cpp
>   }
>   const std::string name = scenario_nodes.begin()->first.Scalar();
>   std::cout << "Loading a scenario named '" << name << "'\n";
> ```

I am not sure why this line evaporated in the "respell for Drake" commit?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478)* status: 14 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @ggould-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE8eBoDwFXrhxp_GiP:-MQE8eBoDwFXrhxp_GiQ:bcgijhz) (no related file):*
Please kick the third commit to a follow-up PR.  It's too much for me to deal with in the same review.

---

**Comment by ggould-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE8eBoDwFXrhxp_GiP:-MQmP7JF1peic1y2_0ba:b-3qmmmp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please kick the third commit to a follow-up PR.  It's too much for me to deal with in the same review.
</blockquote></details>

Okay, I have created https://github.com/RobotLocomotion/drake/pull/14513 with the two initial commits and will address these comments there.

---

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE8eBoDwFXrhxp_GiP:-MQmPU0Y85Qkvbo-CKvT:b-1l208y) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Okay, I have created https://github.com/RobotLocomotion/drake/pull/14513 with the two initial commits and will address these comments there.
</blockquote></details>

Why not simply evict the third commit here?  In a new PR, I'll have to locally three-way-diff these commits to manually reconcile these discussion threads vs the incremental changes.

---

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE8eBoDwFXrhxp_GiP:-MQmT5H11_XtQzM8uasz:beupim6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why not simply evict the third commit here?  In a new PR, I'll have to locally three-way-diff these commits to manually reconcile these discussion threads vs the incremental changes.
</blockquote></details>

I'll attempt that.  I was not sure I could make reviewable understand that, but I'll give it a shot.

---
___
*[examples/acrobot/dev/acrobot_io.py, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE1PU33AINSuzbYgU1:-MQmPpKf3jjUfy98j11_:b-nidbki) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/acrobot_io.py#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This (in r2 patch) reuse of `data` to be both a str (argument) and a dict (after parsing the str) will be confusing to a naive reader.  The extant "scenarios = ..." in r1 seemed both better, and less churn.
</blockquote></details>

Done (I seem to have inadvertently undone a change I previously failed back to anzu, a sin on which I will now reflect...)
___
*[examples/acrobot/dev/acrobot_io.py, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE2RaR9jIhKrwZcr5p:-MQmQ4lt-cVqnZ3pf9ku:bws4vgg) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/acrobot_io.py#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm not sure why this `yaml.dump` to `yaml_dump` change is staged in the third commit; other changes to use `yaml.dump` in this file were staged in the second commit.
</blockquote></details>

OK: This was an error in reviewable attribution; it was in the second commit but attributed to the third revision for unclear reasons.
___
*[examples/acrobot/dev/BUILD.bazel, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE7G3m4d4WOYtHsPKr:-MQmQZQ04rWqww4nGDHF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this example should _always_ remain private (i.e., nobody should be able to import it; we're not going to be installing it).  As such, this target serves no purpose and should disappear.
</blockquote></details>

Done.
___
*[examples/acrobot/dev/BUILD.bazel, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE5FRK-FFMAss_03Uh:-MQmQgCSEDCkGXfFd7oi:b-i8fu9l) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not clear on why `drake_py_unittest` is no longer applicable for this target.  To my understanding, it seems like the perfect fit, and we should remove the dunder-text from the test file.  The default should be `drake_py_unittest`, any uses of `drake_py_test` directly should be few and far between, for oddball situations only.  Basic `def test_foo(self)` stuff should use `drake_py_unittest.
</blockquote></details>

Discussed offline; corrected.
___
*[examples/acrobot/dev/BUILD.bazel, line 104 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE6PtYEU7qp6RDnV8N:-MQmQvt0Et4X-4cuFA_c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L104)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto -- why not `drake_py_unittest` and drop the dunder-text?
</blockquote></details>

Done.
___
*[examples/acrobot/dev/BUILD.bazel, line 112 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE6lwPEu-T3U1zDkwM:-MQmR1SP-vv8K5MgZ4o6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ab8bad63d5a6dbb8cc113c2e64197c1dad45d0e/examples/acrobot/dev/BUILD.bazel#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto -- why not `drake_py_unittest` and drop the dunder-text?
</blockquote></details>

Done.
___
*[examples/acrobot/dev/spong_sim.cc, line 160 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE2lNn2L6T2OH1atu9:-MQmRJVt24Yxn4Hx6i07:blv1014) ([raw file](https://github.com/robotlocomotion/drake/blob/4c1f387b15f49bf4332c6a0fc72213f24c309167/examples/acrobot/dev/spong_sim.cc#L160)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am not sure why this line evaporated in the "respell for Drake" commit?
</blockquote></details>

Done.  It was spammy and annoying and would not have passed review of the r3 commit the moment a reviewer actually ran the code, but that is an argument it belongs in r3.  In moving this to a new PR with just r1+r2 I have replaced this line, and will re-remove it in the r3 PR.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQE8eBoDwFXrhxp_GiP:-MQmW-Vm6JaxOQpbrbsB:bc9wxiu) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I'll attempt that.  I was not sure I could make reviewable understand that, but I'll give it a shot.
</blockquote></details>

Okay, r2 vs r4 is now exactly your review comments, with r3 placed into the memory hole next to the alleged _Highlander_ and _Matrix_ sequels.

---

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478#-:-MQmgb8h-ihcmzOmiRYv:bnfp4nl)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQmfMqmAodxst06pibQ:-MQmfMqmAodxst06pibR:b-iw6ki6) (no related file):*
nit The first commit adds an empty `__init_..py`, and the second commit removes it.  That doesn't seem useful.

---
___
*[examples/acrobot/dev/acrobot_io.py, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQmgMjY7Fz-lRUG2VEl:-MQmgMjY7Fz-lRUG2VEm:bxbhsdy) ([raw file](https://github.com/robotlocomotion/drake/blob/a387ee8ed40799e140cd4f7cf8252fb51c8cda86/examples/acrobot/dev/acrobot_io.py#L1)):*
> ```Python
> import numpy as np
> ```

BTW I didn't realize until after a few false starts that the changes to this file were sync'ing the existing Drake copy to the most recent Anzu copy.  It would probably help in the future to keep "copy more files" and "sync some files" PRs separate.  It _was_ noted in the commit message ("Update existing dev material") but there's was so much commit message text that I missed the implication of what that line meant.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQmfMqmAodxst06pibQ:-MQmifh06zQX7VZJ7AdW:b-qgedu) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The first commit adds an empty `__init_..py`, and the second commit removes it.  That doesn't seem useful.
</blockquote></details>

Heh.  The dangers of "verbatim copy" :-)  I'll do some history surgery and see if I can't fix that.  It won't be legible from reviewable, though.

---
___
*[examples/acrobot/dev/acrobot_io.py, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14478#-MQmgMjY7Fz-lRUG2VEl:-MQmiucK04yw2Ab4Ihvz:b3pgigq) ([raw file](https://github.com/robotlocomotion/drake/blob/a387ee8ed40799e140cd4f7cf8252fb51c8cda86/examples/acrobot/dev/acrobot_io.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I didn't realize until after a few false starts that the changes to this file were sync'ing the existing Drake copy to the most recent Anzu copy.  It would probably help in the future to keep "copy more files" and "sync some files" PRs separate.  It _was_ noted in the commit message ("Update existing dev material") but there's was so much commit message text that I missed the implication of what that line meant.
</blockquote></details>

A lesson for the playbook!

**Review by ggould-tri — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14478#-:-MQmpuyn8x_oAR9UXPVV:b-b9fcpn)* status: labeled "do not merge"

**Pull request merged**
