### PR TITLE
CableLength / Soft Paddle Model / Soft Paddle Controller

### PR DESCRIPTION
**Pull request by tarquasso**
Adding CableLength / Soft Paddle Model / Soft Paddle Controller Capabilities
This pull request only affects Matlab files within drake.

Summary:
in matlab/solvers/*drakeFunction/+kinematic:
CableLength.m overhaul, adding second derivatices

in drake/matlab/systems/plants:
RigidBodyTorsionalSpring: fix bug in computespatialforce, second derivative was not calculated before
TimeSteppingRigidBodyManipulator: add get and set methods for this class
addRobotFromURDF: allow to use analytical gradient of CableLength.m for CableContraints
RigidBodyManipulator: allow to use analytical gradient of CableLength.m for CableContraints

in drake/matlab/util:
ddcross.m: second derivative of cross product
ddaxis2rotmatdtheta.m: second derivative of axis2rotmat

in drake/examples/ChineseYoYo:
SoftPaddleModel and Soft Paddle Controller
test by executing: SoftPaddleControl.run

in drake/examples/ChineseYoYo/dev:
further SoftPaddle related files that are academic or that can be further expanded on in the future for parameterized approaches

in drake/examples/SimplePulleys:
adds twopulley version of tension.m and minor initial state adjustments of existing models

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4001)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@tarquasso Please assign an appropriate feature reviewer - see http://drake.mit.edu/developers.html#code-review.  For platform review, I think this one will have to go to @RussTedrake.  

One question: are there any unit tests in here?

**Comment by tarquasso** [comment]
@david-german-tri Working with this reviewable.io interface the first time, how to assign a reviewer in here? Russ Tedrake should be it.
There are a few test files for the code within it, but no unit tests that can be run within the testing framework. Again, I have no experience with that either, I guess I have to dig a bit into the documentation. The code changes in here affect primarily only CableLength constraint related things and that only in Matlab

---

Review status: 0 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4001#-:-KVapILuvWqoH74oEfIm:b-iy2kc0)*

**Comment by tarquasso** [comment]
@RussTedrake for platform review
@jwnimmer-tri for feature review

---

Review status: 0 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4001#-:-KVaxelnlEdJRSaCUHJf:b-z76gn0)*

**Comment by jwnimmer-tri** [comment]
I've assigned Russ for review.  Russ, I'll let you delegate additional reviews beyond yourself.

**Comment by RussTedrake** [comment]
let's close this for now (every push you make is launching lots of tests on the build servers).

**Pull request closed without merging**
