### PR TITLE
Bind Multiplexer and Automotive subset

### PR DESCRIPTION
**Pull request by jadecastro**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8361)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@ericcousineau-tri for feature review (when you have time)

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-:-L7XWHFP7bPCzsAcuw2i:bni3qfl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/automotive_py.cc, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZovNs7UuEFqWlNJG5:-L7ZovNs7UuEFqWlNJG6:b2sv3sr) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/automotive_py.cc#L25)):*
> ```cpp
>   m.doc() = "Bindings for Automotive systems.";
> 
>   py::module::import("pydrake.systems.framework");
> ```

Does this use `systems/rendering` (e.g. for `Pose` port values)? If so, could you add `py::module::import("pydrake.systems.rendering")`?

---

*[bindings/pydrake/automotive_py.cc, line 44 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZomftBO5OelJHwTXF:-L7ZomftBO5OelJHwTXG:b-evzkuo) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/automotive_py.cc#L44)):*
> ```cpp
>   pysystems::AddValueInstantiation<LaneDirection>(m);
> 
>   py::class_<DrivingCommand<T>, BasicVector<T>>(m, "DrivingCommand")
> ```

BTW Can you add TODO for me related to #8096?

---

*[bindings/pydrake/systems/test/primitives_test.py, line 174 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZlhOZ2iNwKwudDodN:-L7ZlhOZ2iNwKwudDodO:b-hunwjh) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/systems/test/primitives_test.py#L174)):*
> ```Python
>         mytest((.2, .3), (.2, 1.3))
> 
>     def test_multiplexer_scalar_inputs(self):
> ```

Can you collapse these tests? Maybe generalize it to:
```
inputs = [
  dict(args=dict(num_scalar_inputs=3), data=([5.], [3.], [4.])),
  dict(args=dict(input_sizes=[2, 3]), data=([5., 4.], [3., 6., 9.])),
  ...
]
```
and then process / test `inputs`?

---

*[bindings/pydrake/test/automotive_test.py, line 161 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZoOJq2GEd0hqfWvOO:-L7ZoOJrBONH6YVwubL-:b2pekh5) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/test/automotive_test.py#L161)):*
> ```Python
> 
>         # Fix the input.
>         command = DrivingCommand()
> ```

FYI Just for my own thoughts on https://github.com/RobotLocomotion/drake/issues/8096:
Would it be convenient to have named initializers in named vectors, to reduce the `set_{value}` stuff?
(so you could have `command = DriveCommand(steering_angle=0.5, acceleration=1.)`)

---

*[bindings/pydrake/test/automotive_test.py, line 169 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7Zo4-y2ub-hnyoUnus:-L7Zo4-y2ub-hnyoUnut:bcz7j3p) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/test/automotive_test.py#L169)):*
> ```Python
>         command_eval = simple_car.EvalVectorInput(context, 0)
>         self.assertTrue(np.allclose(
>             [command.steering_angle(), command.acceleration()],
> ```

BTW Since you've already tested `DrivingCommand`s API, can you reduce this to:
```
self.assertTrue(np.allclose(command.get_value(), command_eval.get_value()))
```

---

*[bindings/pydrake/test/automotive_test.py, line 173 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZmofNDhHoqyVBKBuf:-L7ZmofO6EBLrAYUq4FR:b-9ecm08) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/test/automotive_test.py#L173)):*
> ```Python
> 
>         # Initialize all the states to zero and take a simulation step.
>         state = context.get_mutable_continuous_state_vector()
> ```

BTW No explicit initialization is going on here?
Could you change this to the indicative tense? (or indicate that's implicitly initialized by `StepTo`?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-:-L7ZpTyM3SagztZjk__I:b-2l0s3s)*

**Comment by jadecastro** [comment]
Comments addressed. 

---

Review status: 10 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/automotive_py.cc, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZovNs7UuEFqWlNJG5:-L7_mdpoBLUodbsoARMu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/automotive_py.cc#L25)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Does this use `systems/rendering` (e.g. for `Pose` port values)? If so, could you add `py::module::import("pydrake.systems.rendering")`?
</blockquote></details>

Done.

---

*[bindings/pydrake/automotive_py.cc, line 44 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZomftBO5OelJHwTXF:-L7_medK-lg-_WnuVoJi:b-ul4ike) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/automotive_py.cc#L44)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you add TODO for me related to #8096?
</blockquote></details>

Done. (also below)

---

*[bindings/pydrake/systems/test/primitives_test.py, line 174 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZlhOZ2iNwKwudDodN:-L7aEomn9Q6raU40ekOC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/systems/test/primitives_test.py#L174)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you collapse these tests? Maybe generalize it to:
```
inputs = [
  dict(args=dict(num_scalar_inputs=3), data=([5.], [3.], [4.])),
  dict(args=dict(input_sizes=[2, 3]), data=([5., 4.], [3., 6., 9.])),
  ...
]
```
and then process / test `inputs`?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/automotive_test.py, line 161 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZoOJq2GEd0hqfWvOO:-L7_j12KAZengy4oh5xd:bpfnagb) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/test/automotive_test.py#L161)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

FYI Just for my own thoughts on https://github.com/RobotLocomotion/drake/issues/8096:
Would it be convenient to have named initializers in named vectors, to reduce the `set_{value}` stuff?
(so you could have `command = DriveCommand(steering_angle=0.5, acceleration=1.)`)
</blockquote></details>

It would be nice to have. Would this imply that this sugar would get added to the C++ side also (so that C++ > python)? 

---

*[bindings/pydrake/test/automotive_test.py, line 169 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7Zo4-y2ub-hnyoUnus:-L7aFi8g7xV3Ijndljen:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/test/automotive_test.py#L169)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Since you've already tested `DrivingCommand`s API, can you reduce this to:
```
self.assertTrue(np.allclose(command.get_value(), command_eval.get_value()))
```
</blockquote></details>

Done.

---

*[bindings/pydrake/test/automotive_test.py, line 173 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7ZmofNDhHoqyVBKBuf:-L7aFiRe5IgnZQeRG_Qp:b77u0xk) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/test/automotive_test.py#L173)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW No explicit initialization is going on here?
Could you change this to the indicative tense? (or indicate that's implicitly initialized by `StepTo`?)
</blockquote></details>

Done. (actually instantiated the states this time!)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-:-L7aFka1Do38y2dshYO_:bq47sou)*

**Comment by jadecastro** [comment]
+@seancurtis-tri platform review, please.

---

Review status: 10 of 13 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-:-L7aGhJl0QqBmLrvfPgz:b7pxy8m)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with some cosmetic suggestions and questions for my own edification.

---

Reviewed 10 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[bindings/pydrake/automotive_py.cc, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aKCsl19RkMpfHN542:-L7aKCsl19RkMpfHN543:b-jxvakb) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/automotive_py.cc#L23)):*
> ```cpp
>   using namespace drake::automotive;
> 
>   m.doc() = "Bindings for Automotive systems.";
> ```

FYI While these doc strings frequently have periods in Drake's bindings, there are plenty of cases without. My preference is to omit the period because this isn't actually a sentence.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aLmevxcvPPrwIT7P4:-L7aLmevxcvPPrwIT7P5:b-2kmtg8) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/systems/test/primitives_test.py#L27)):*
> ```Python
>     SignalLogger,
>     WrapToSystem,
>     Multiplexer,
> ```

BTW Hmmm...this list seems *almost* alphabetized. Probably should be.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 198 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aMXsdhFNsA3ihvsHM:-L7aMXsdhFNsA3ihvsHN:b-57fmia) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/systems/test/primitives_test.py#L198)):*
> ```Python
>                 np.allclose(output.get_vector_data(0).get_value(),
>                             [elem for vec in case['data'] for elem in vec]))
>             if i == 3:  # Check that it is of type MyVector.
> ```

BTW I see three test cases above. Will this ever get invoked? Perhaps add a `bool` to your dictionaries including "I'm a `MyVector`"-ness and then you can also get rid of `enumerate` and `i`.

---

*[bindings/pydrake/systems/test/test_util_py.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aN21MAuoRh0U3SIzB:-L7aN21MAuoRh0U3SIzC:b66vwgm) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/systems/test/test_util_py.cc#L68)):*
> ```cpp
> struct UnknownType {};
> 
> // A simple 2-dimensional subclass of BasicVector for testing.
> ```

BTW Given this is in `test_util_py.cc` and can be used by others, perhaps it would be better to call it `MyVector2`?

---

*[bindings/pydrake/test/automotive_test.py, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aNGrZg-X__O-aa-ev:-L7aNGrZg-X__O-aa-ew:b-as36tp) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L4)):*
> ```Python
>     DrivingCommand,
>     LaneDirection,
>     IdmController,
> ```

BTW Swap Idm... and Lane... for alphabetical order.

---

*[bindings/pydrake/test/automotive_test.py, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aNkNnLnAUb5HfETU3:-L7aNkNnLnAUb5HfETU4:b-kz8cgw) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L12)):*
> ```Python
> )
> 
> import numpy as np
> ```

BTW pep8 suggests import order:

1. standard library
2. related third party
3. local application

(with the caveat, of course, that `pydrake.automotive` is what is under test.)

---

*[bindings/pydrake/test/automotive_test.py, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aPI8CxgByDenu9WSG:-L7aPI8CxgByDenu9WSH:bflfl6n) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L69)):*
> ```Python
>         self.assertTrue(isinstance(driving_command, framework.BasicVector))
>         self.assertEqual(driving_command.size(), 2)
>         driving_command.set_steering_angle(5.)
> ```

FYI Meta(maybe) These tests aren't 100% robust against being fooled. If the `set` methods were broken but the default constructor initialized the tested values to 5 and 23, the getters would pass, but the setters wouldn't have been confirmed.

Two options:
1. Assert that the values are *not* the desired value before setting.
2. Add a comment indicating that you're only testing spelling.

---

*[bindings/pydrake/test/automotive_test.py, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aPqBvT9M_Uhp5DOAJ:-L7aPqBvT9M_Uhp5DOAK:bfj3are) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L87)):*
> ```Python
>         context.FixInputPort(lane_index, ld_value)
> 
>         pos = [1., 2., 3.]  # +2 r-offset from the s-axis.
> ```

FYI I'm not in automotive code much but the notation "+2" confuses me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-:-L7aQpxCkbsE1Pay1yuF:b188ki1)*

**Comment by jadecastro** [comment]
Review status: 9 of 13 files reviewed at latest revision, 12 unresolved discussions.

---

*[bindings/pydrake/automotive_py.cc, line 23 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7aKCsl19RkMpfHN542:-L7auGpG3lmzf04NzKr3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/automotive_py.cc#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI While these doc strings frequently have periods in Drake's bindings, there are plenty of cases without. My preference is to omit the period because this isn't actually a sentence.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 27 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7aLmevxcvPPrwIT7P4:-L7audK-0AERYE6aXLAv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/systems/test/primitives_test.py#L27)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Hmmm...this list seems *almost* alphabetized. Probably should be.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 198 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7aMXsdhFNsA3ihvsHM:-L7b4jK96qpw61oliKLJ:b-rmzgv3) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/systems/test/primitives_test.py#L198)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I see three test cases above. Will this ever get invoked? Perhaps add a `bool` to your dictionaries including "I'm a `MyVector`"-ness and then you can also get rid of `enumerate` and `i`.
</blockquote></details>

Aha. It doesn't get invoked (oops). I've made the link stronger between the third case and this if statement. PTAL.

---

*[bindings/pydrake/systems/test/test_util_py.cc, line 68 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7aN21MAuoRh0U3SIzB:-L7auu9J2FpEOoXnqaqa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/systems/test/test_util_py.cc#L68)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given this is in `test_util_py.cc` and can be used by others, perhaps it would be better to call it `MyVector2`?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/automotive_test.py, line 4 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7aNGrZg-X__O-aa-ev:-L7b3bMv9b54oPueNZ0c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L4)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Swap Idm... and Lane... for alphabetical order.
</blockquote></details>

Done.

---

*[bindings/pydrake/test/automotive_test.py, line 12 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7aNkNnLnAUb5HfETU3:-L7b3pMj7tDWIRLUJ-qI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW pep8 suggests import order:

1. standard library
2. related third party
3. local application

(with the caveat, of course, that `pydrake.automotive` is what is under test.)
</blockquote></details>

Done.

---

*[bindings/pydrake/test/automotive_test.py, line 69 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7aPI8CxgByDenu9WSG:-L7b7utM4rLtMkUHHd2y:b-2ectng) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L69)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Meta(maybe) These tests aren't 100% robust against being fooled. If the `set` methods were broken but the default constructor initialized the tested values to 5 and 23, the getters would pass, but the setters wouldn't have been confirmed.

Two options:
1. Assert that the values are *not* the desired value before setting.
2. Add a comment indicating that you're only testing spelling.
</blockquote></details>

Done. Added `assertNotEqual` before each `set_foo()`.

---

*[bindings/pydrake/test/automotive_test.py, line 87 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361#-L7aPqBvT9M_Uhp5DOAJ:-L7b4Vbp0Ngz0HTs7Yy5:b-kd3g1p) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L87)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I'm not in automotive code much but the notation "+2" confuses me.
</blockquote></details>

 The numbers are really unimportant; what's important is that they all lie within the lane, and that wasn't really clear. Fixed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8361)*

**Comment by SeanCurtis-TRI** [comment]
Thanks for the explanations. Two left overs. @ericcousineau-tri you also have some blocking comments.

---

Reviewed 4 of 4 files at r3.
Review status: 12 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 198 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aMXsdhFNsA3ihvsHM:-L7bNaD-RN-p2j2LJi9w:b-dp4lkh) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/systems/test/primitives_test.py#L198)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Aha. It doesn't get invoked (oops). I've made the link stronger between the third case and this if statement. PTAL.
</blockquote></details>

I note you still are using `enumerate`, but it doesn't look like you're still using the enumerated value 'i'.

---

*[bindings/pydrake/test/automotive_test.py, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aNkNnLnAUb5HfETU3:-L7bNod-5s6SQSW7SDpo:b-2k2rgk) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L12)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops...my comment led to an unintended result.

I'd meant that it was alright to have the `pydrake.automotive` first (because that's what's being tested. then `unittest` would be second (as a standard library) and `numpy` would be last as "related third party". (With an empty line between each group.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-:-L7bf3iP6cwipIaKI27p:b-cwx2tw)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8361)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 198 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aMXsdhFNsA3ihvsHM:-L7biUokt4vSzIcjvSzU:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/systems/test/primitives_test.py#L198)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I note you still are using `enumerate`, but it doesn't look like you're still using the enumerated value 'i'.
</blockquote></details>

Fixed.

---

*[bindings/pydrake/test/automotive_test.py, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7aNkNnLnAUb5HfETU3:-L7biZ2CaAaw1Rf8KMMh:b-ieoxyk) ([raw file](https://github.com/robotlocomotion/drake/blob/4915c35525130765d90b7969f131dcb1849a7fb9/bindings/pydrake/test/automotive_test.py#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Oops...my comment led to an unintended result.

I'd meant that it was alright to have the `pydrake.automotive` first (because that's what's being tested. then `unittest` would be second (as a standard library) and `numpy` would be last as "related third party". (With an empty line between each group.)
</blockquote></details>

Done. Hopefully in the right order this time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8361)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8361)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 4 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/test/automotive_test.py, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8361#-L7ZoOJq2GEd0hqfWvOO:-L7eEqrinH3wDiFECt49:bts5f3v) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0003c2680b53078fd1b81ef11b75c15a67dbf7/bindings/pydrake/test/automotive_test.py#L161)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

It would be nice to have. Would this imply that this sugar would get added to the C++ side also (so that C++ > python)? 
</blockquote></details>

Er, probably just on the Python side to start, but I can see what would be required to port that to the C++ side; however, since [named / designated initializers](https://stackoverflow.com/q/18731707/7829525) are (unfortunately) a contentious issue, it'd still be a tad hand-wavy :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8361)*

**Pull request merged**
