### PR TITLE
[doc] Add release notes v1.28.0

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-:-Nv9E38Q1PkMHvhZN20b:bg7igkv)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.28.0.md` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9D-F-CsswjDdiY5sK:-Nv9D-F-CsswjDdiY5sL:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ee5cf3aed8afda3f0febaee9d7bb07d44643e1c/doc/_release-notes/v1.28.0.md#L48)):*
> ```Markdown
> 
> * Change the type of F in LinearMatrixInequalityConstraint ([#21152][_#21152])
> * Add Optional Sparsity Groups to MakeSemidefiniteRelaxation ([#21043][_#21043])
> ```

nit



_Suggestion:_
```Markdown
Add optional sparsity groups to MakeSemidefiniteRelaxation ([#21043][_#21043])
```
___
*[`doc/_release-notes/v1.28.0.md` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9Bfy88hqb79RSx7Af:-Nv9Bfy95nFqc-xalDyW:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ee5cf3aed8afda3f0febaee9d7bb07d44643e1c/doc/_release-notes/v1.28.0.md#L68)):*
> ```Markdown
> 
> * Report accumulated collision filter groups ([#21138][_#21138])
> * Update definition of Convex shape to mean "use the convex hull ([#21147][_#21147])
> ```

typo



_Suggestion:_
```Markdown
Update definition of Convex shape to mean "use the convex hull"
```
___
*[`doc/_release-notes/v1.28.0.md` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9BjEk4PsqaDW3bIUw:-Nv9BjEk4PsqaDW3bIUx:b-2gzw1i) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ee5cf3aed8afda3f0febaee9d7bb07d44643e1c/doc/_release-notes/v1.28.0.md#L70)):*
> ```Markdown
> * Update definition of Convex shape to mean "use the convex hull ([#21147][_#21147])
> * Add Shape::Visit ([#21181][_#21181])
> * Convex shapes render as flat-shaded convex polytopes in visual roles ([#21189][_#21189], [#21281][_#21281]) 
> ```

nit extraneous space. Here and in lines below.



_Code quote:_
```Markdown
·
```
___
*[`doc/_release-notes/v1.28.0.md` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9BxCk3P8HCnr0z4A3:-Nv9BxCl5760SNeu2Cs_:bgffhch) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ee5cf3aed8afda3f0febaee9d7bb07d44643e1c/doc/_release-notes/v1.28.0.md#L73)):*
> ```Markdown
> * Mujoco parser supports new autolimits ([#21205][_#21205]) 
> * Implement MultibodyPlant::RemoveJointActuator ([#20711][_#20711])
> * Allow model directive 'add_model' to pose free body with respect to an arbitrary frame ([#21263][_#21263]) 
> ```

BTW, would it be less confusing to omit the word "free" here. After all, the body might not be "free" in the MbP sense of the word.



_Suggestion:_
```Markdown
Allow model directive 'add_model' to pose body with respect to an arbitrary frame
```
___
*[`doc/_release-notes/v1.28.0.md` line 93 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9DO5P9GCZqHhUiquo:-Nv9DO5P9GCZqHhUiqup:b8z861o) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ee5cf3aed8afda3f0febaee9d7bb07d44643e1c/doc/_release-notes/v1.28.0.md#L93)):*
> ```Markdown
> Fixes
> 
> * Match RobotDiagram default time step to MbP's default ([#21098][_#21098])
> ```

nit MultibodyPlant



_Code quote:_
```Markdown
MbP
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.28.0.md` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9BjEk4PsqaDW3bIUw:-Nv9IUPD2BY494rKQDHR:bqfz1vf) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ee5cf3aed8afda3f0febaee9d7bb07d44643e1c/doc/_release-notes/v1.28.0.md#L70)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit extraneous space. Here and in lines below.
</blockquote></details>

I'm not seeing it, could you elaborate? 
___
*[`doc/_release-notes/v1.28.0.md` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9BxCk3P8HCnr0z4A3:-Nv9Hnni1R8bG4jJ8KeQ:b-mboh10) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ee5cf3aed8afda3f0febaee9d7bb07d44643e1c/doc/_release-notes/v1.28.0.md#L73)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, would it be less confusing to omit the word "free" here. After all, the body might not be "free" in the MbP sense of the word.
</blockquote></details>

Hmmm....while I see what you mean, I'm going to leave it.

- the actual model directive is called `default_free_body_pose`.
- It's only meaningful for bodies that were free *prior* to the invocation, even though the invocation removes the technical definition but preserves the dynamic appearance of being a free body.
- Eventually, it *will* be a free body and the trick implemented in *that* PR will be replaced by one without the limitation -- but the syntax won't change.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.28.0.md` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9BjEk4PsqaDW3bIUw:-Nv9Ksw2Axi9FIS9kO9S:bii0jm8) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ee5cf3aed8afda3f0febaee9d7bb07d44643e1c/doc/_release-notes/v1.28.0.md#L70)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm not seeing it, could you elaborate?
</blockquote></details>

There's a space at the end of this line (line 70) and (line 71 and line 73) as indicated by the red dots.

Not sure if it's worth us typing three comments in total but now I feel the need to elaborate.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.28.0.md` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9UCMq1NduSaqjDpSl:-Nv9UCMq1NduSaqjDpSm:b-g1zfem) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L7)):*
> ```Markdown
> ---
> 
> # Announcements
> ```

nit We should announce some summary of "Model files now live in drake_models"  here atop the document.
___
*[`doc/_release-notes/v1.28.0.md` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9SQ6E5jgkQ-jgmtX3:-Nv9SQ6E5jgkQ-jgmtX4:b1561qv) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L9)):*
> ```Markdown
> # Announcements
> 
> * Change the type of F in LinearMatrixInequalityConstraint from std::vector<Eigen::Ref<const Eigen::MatrixXd>> to std::vector<Eigen::MatrixXd> for two reasons: ([#21152][_#21152])
> ```

nit This 21152 isn't an announcement, it's a breaking change.  (Wrong section.)

Also the C++ types show up oddly in the preview, I suggest backticking them.

Also no need to copy-paste the rationale, just noting the change is enough.  People can read the PR for details (and few will care about the rationale anyway).
___
*[`doc/_release-notes/v1.28.0.md` line 31 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9SpLE1QkFMNZMna4E:-Nv9SpLE1QkFMNZMna4F:bx9waxo) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L31)):*
> ```Markdown
> 
> 
> * [feature] Implement DiscreteTimeIntegrator primitive ([#21222][_#21222])
> ```

nit 21222 Stray "feature" text.  Move it down into feature section below, I assume
___
*[`doc/_release-notes/v1.28.0.md` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9T9RTAeESuWPyDFVF:-Nv9T9RU6v1Pq6hNFFeM:b-vqmaei) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L88)):*
> ```Markdown
> New features
> 
> * Remove Gurobi and Mosek solver dependencies ([#21164][_#21164])
> ```

nit 21164 struck me as non-notable (test-only). The PR says https://github.com/RobotLocomotion/drake/pull/21164#pullrequestreview-1947198621 but I don't buy it.  In any case if this is supposed to be an announcement it's in the wrong place in this file and doesn't communicate the change with sufficient precision for anyone to comprehend what the announcement means.
___
*[`doc/_release-notes/v1.28.0.md` line 89 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9TZGa9a566dfs0h_9:-Nv9TZGa9a566dfs0h_A:b-fion5m) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L89)):*
> ```Markdown
> 
> * Remove Gurobi and Mosek solver dependencies ([#21164][_#21164])
> * Add zero derivative constraints ([#21180][_#21180])
> ```

nit 21180 the leading bracket phrase provided important context to this bullet.  As it reads now, nobody will understand what it means.  Adding "In GcsTrajectoryOptimization" ahead of the bullet or something would help.
___
*[`doc/_release-notes/v1.28.0.md` line 101 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9Tq2JA37PgYCXJ60G:-Nv9Tq2JA37PgYCXJ60H:b-nnmtv6) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L101)):*
> ```Markdown
> 
> 
> * Remove pr2_description ([#21185][_#21185])
> ```

nit Given later changes (where it was added back into drake_models), this would be best phrased as "Move pr2_description to drake_models" or something.
___
*[`doc/_release-notes/v1.28.0.md` line 104 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9TyrI8XxNac5wIgsV:-Nv9TyrI8XxNac5wIgsW:b7n9q0d) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L104)):*
> ```Markdown
> * Move manipulation_station models into drake_models ([#21233][_#21233])
> * Move punyo files into drake_models ([#21231][_#21231])
> * Copy quadrotor.urdf to drake_models ([#21238][_#21238])
> ```

nit 21238 should probably say "move" not "copy" since the intention long-term is that the drake copy will be deleted ASAP.
___
*[`doc/_release-notes/v1.28.0.md` line 159 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9UQNa4DEvd6cPodoN:-Nv9UQNa4DEvd6cPodoO:b-8si0pl) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L159)):*
> ```Markdown
> * Upgrade stable_baselines3_internal to latest release v2.3.0 ([#21260][_#21260])
> * Upgrade suitesparse_internal to latest release v7.7.0 ([#21260][_#21260])
> * Upgrade sdformat_internal, gz_math_internal to latest ([#21262][_#21262])
> ```

nit 21262 please re-edit this into two distinct lines (from the body of the commit message), kinda like each bump was a separate commit.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293)* status: 10 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.28.0.md` line 73 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9_tXY2rwq2s2qOrQu:-Nv9_tXY2rwq2s2qOrQv:bk6axdu) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L73)):*
> ```Markdown
> * Mujoco parser supports new autolimits ([#21205][_#21205]) 
> * Implement MultibodyPlant::RemoveJointActuator ([#20711][_#20711])
> * Allow model directive 'add_model' to pose free body with respect to an arbitrary frame ([#21263][_#21263]) 
> ```

BTW PR #21198 added an overload of AddRigidBody() that has a default for SpatialInertia (zero), and also added factory method SpatialInertia::Zero().

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.28.0.md` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9BjEk4PsqaDW3bIUw:-NvC_A6T-0ao8dcnygWq:b1skp99) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ee5cf3aed8afda3f0febaee9d7bb07d44643e1c/doc/_release-notes/v1.28.0.md#L70)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There's a space at the end of this line (line 70) and (line 71 and line 73) as indicated by the red dots.

Not sure if it's worth us typing three comments in total but now I feel the need to elaborate.
</blockquote></details>

Sorry...my eyes weren't good enough to notice the trailing space. The little red dot *still* looks like a spec on my display. I envy your eyes.

Couple of strategies to accommodate the old codgers next time:

- Highlight more than just the space so the code quote provides context.
- Indicate "extraneous space _at end of line_".
___
*[`doc/_release-notes/v1.28.0.md` line 73 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9_tXY2rwq2s2qOrQu:-NvC_-2z4-IO1y8X4LxD:biziuwb) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L73)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW PR #21198 added an overload of AddRigidBody() that has a default for SpatialInertia (zero), and also added factory method SpatialInertia::Zero().
</blockquote></details>

It was tagged as "fix", so the detail about `AddRigidBody()` is part of the fix. However, I've added the `SpatialInertia` detail in "new features".
___
*[`doc/_release-notes/v1.28.0.md` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-Nv9T9RTAeESuWPyDFVF:-NvCY_kXAhJpXSqkmzQW:b-hv4jwm) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc30d747e45a7ced87380a1f2f4e279e362736c1/doc/_release-notes/v1.28.0.md#L88)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit 21164 struck me as non-notable (test-only). The PR says https://github.com/RobotLocomotion/drake/pull/21164#pullrequestreview-1947198621 but I don't buy it.  In any case if this is supposed to be an announcement it's in the wrong place in this file and doesn't communicate the change with sufficient precision for anyone to comprehend what the announcement means.
</blockquote></details>

Agreed. It's out.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM so far for parts I looked at / care about.

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-:-NvCb27J-_e1tUp432tu:b-mw53b4)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.28.0.md` line 152 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-NvCahVI54p-zGLFlUyA:-NvCahVI54p-zGLFlUyB:blple3n) ([raw file](https://github.com/RobotLocomotion/drake/blob/d6dd38bb3ca559314b67dd80690d63cb0c64d7f6/doc/_release-notes/v1.28.0.md#L152)):*
> ```Markdown
> * Upgrade curl_internal to latest release 8.7.1 ([#21265][_#21265])
> * Upgrade drake_models to latest commit ([#21217][_#21217], [#21213][_#21213], [#21241][_#21241], [#21250][_#21250], [#21227][_#21227], [#21233][_#21233], [#21231][_#21231], [#21238][_#21238], [#21244][_#21244], [#21258][_#21258], [#21079][_#21079], [#21184][_#21184], [#21190][_#21190], [#21191][_#21191], [#21218][_#21218])
> * Upgrade gz_math_internal to latest ([#21262][_#21262])
> ```

nit 21262



_Suggestion:_
```Markdown
to latest release 7.4.0
```
___
*[`doc/_release-notes/v1.28.0.md` line 158 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-NvCalsY9asfqsgRFGew:-NvCalsY9asfqsgRFGex:blple3n) ([raw file](https://github.com/RobotLocomotion/drake/blob/d6dd38bb3ca559314b67dd80690d63cb0c64d7f6/doc/_release-notes/v1.28.0.md#L158)):*
> ```Markdown
> * Upgrade stable_baselines3_internal to latest release v2.3.0 ([#21260][_#21260])
> * Upgrade suitesparse_internal to latest release v7.7.0 ([#21260][_#21260])
> * Upgrade sdformat_internal to latest ([#21262][_#21262])
> ```

nit 21262



_Suggestion:_
```Markdown
to latest release 14.1.1
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.28.0.md` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-NvDjKBm1ZffWoIwMjqo:-NvDjlZC8GkqUv3O3Ru0:bhgw873) ([raw file](https://github.com/RobotLocomotion/drake/blob/5fb99a843227fb0c653ec8d78bc6e817f1a8814d/doc/_release-notes/v1.28.0.md#L9)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW @jwnimmer-tri do we want to get the glTF conversion into this release? Or simply defer that to the next release?
</blockquote></details>

I thought about blocking for that but eventually decided it didn't really matter.  If you'd rather wait, that's OK by me though.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@xuchenhan-tri +@SeanCurtis-TRI (for self stamping)
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21293#-:-NvJ2oEMDJ7SahZSlDJ6:b-m3whr5)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Comment by SeanCurtis-TRI** [comment]
+(status: squashing now)

**Pull request merged**
